### ISSUE TITLE
CompositeImplicitAutograd operators should not perform operations that do not dispatch

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#61669]
## 🚀 Feature

CompositeImplicitAutograd operations should not be allowed to call operations that do not dispatch. This means that we should rewrite existing CompositeImplicitAutograd ops that do not dispatch to actually perform dispatches and prevent this from happening in the future. The changes include the following that were discovered by OpInfo testing (but there may be more hiding somewhere):
1. native::resize_output in CompositeImplicitAutograd operations (covered in https://github.com/pytorch/pytorch/issues/61485)
2. Error checking in CompositeImplicitAutograd operations directly accesses the data_ptr (this happens a lot in linalg operations, see [linalg_cholesky](https://github.com/pytorch/pytorch/blob/9b3cbeaf7d2e57203d43d2cfaa453674912b3c48/aten/src/ATen/native/BatchLinearAlgebra.cpp#L1432-L1436))

## Motivation

@ngimel said in another thread that the native::resize_output problem would be a more general problem for functorch (that any CompositeImplicitAutograd operation that doesn’t dispatch causes a problem) and she was right. I think this is also going to be a problem for meta tensors as well.

### for functorch
Right now, the above cases causes problems for functorch. To not go into too much detail,
- functorch’s grad transform wraps all Tensors in a GradTensorWrapper (this is a Tensor that holds a GradTensorWrapperImpl).
- Let's assume that GradTensorWrapper does not have storage. Then directly accessing its data_ptr field like in  [linalg_cholesky](https://github.com/pytorch/pytorch/blob/9b3cbeaf7d2e57203d43d2cfaa453674912b3c48/aten/src/ATen/native/BatchLinearAlgebra.cpp#L1432-L1436) raises an exception.

One interesting thing we’ve tried is to give the GradTensorWrapper the same storage as its underlying Tensor so that the data_ptr access works (data_ptr isn’t virtual). This triggers a fun assert in Autograd (see https://github.com/facebookresearch/functorch/issues/72) and isn’t a complete solution because we don’t allow accesses for BatchedTensorImpls that wrap a Tensor.

### for meta tensors

What happens when one accesses the data_ptr for a meta tensor? meta tensors currently don't work with `linalg_cholesky`, but is the data_ptr read going to be problematic?

## Pitch

1. Make CompositeImplicitAutograd operations not call out= variants (covered in https://github.com/pytorch/pytorch/issues/61485)
2. Turn the [data_ptr access](https://github.com/pytorch/pytorch/blob/9b3cbeaf7d2e57203d43d2cfaa453674912b3c48/aten/src/ATen/native/BatchLinearAlgebra.cpp#L1432-L1436) inside linalg functions into an operator
3. Add guidelines for future CompositeImplicitAutograd operator authors to not call operators that skip dispatch.
4. Figure out some automated testing plan for this.

## Alternatives

I'm not sure, but I'd love to hear thoughts and feedback. cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @bhosmer @smessmer @ljk53 @bdhirsh @ngimel @mruberry @Chillee.

**Comment by mruberry** [comment]
Can we reliably test for this? That is, if we require that CompositeImplicitAutograd operators only call ops that dispatch, can we detect when they don't?

**Comment by zou3519** [comment]
> Can we reliably test for this? That is, if we require that CompositeImplicitAutograd operators only call ops that dispatch, can we detect when they don't?

Possibly. We can definitely test for a subset of this -- we can use one of the Backend private keys to create a Tensor Extension (call it Wrapper) that wraps a Tensor. If a CompositeImplicitAutograd operation bypasses dispatch then it will act directly on the Wrapper and not the underlying Tensor, leading to hard errors in most situations.

**Comment by bdhirsh** [comment]
> CompositeImplicitAutograd operations should not be allowed to call operations that do not dispatch

I'm not sure how to define "operations" here. I'm pretty sure that operations in this case should refer to the TensorImpl API? (i.e. in `TensorImpl.h`).

In two of the failing cases that you pointed out:
* `data_ptr()` call in a composite fails - composites should work across all backends (including Batched and XLA), and can't assume that the underlying TensorImpl has storage
* `at::native::resize_output()` "fails", because it resizes the tensor incorrectly - it resizes the wrapper TensorImpl rather than the inner tensor

So for example, I don't think that we want to ban all calls to functions in the `at::native::` namespace from composite ops.

If that sounds right, one thing I'm not sure about is if we want to ban **all** calls on the TensorImpl, or just a subset of them. It seems reasonable to ban all methods that mutate state (like resizing the TensorImpl). But `data_ptr()` is technically a read operation. Should read-only methods be banned too? Or is it valid for a composite op to call `.sizes()` and do something with it.

Maybe it would be helpful to come up with a test like what you described above:
> we can use one of the Backend private keys to create a Tensor Extension (call it Wrapper) that wraps a Tensor. 

that figures out how to raise an error when any TensorImpl methods are called on the wrapper? I don't think that will just work out of the box, since most TensorImpl methods aren't virtual, so the wrapper would have no way of knowing if they were called so it can error out. Maybe some codegen could help.


Aside: I think this is also a native_functions.yaml labeling problem. The cases you mentioned above sound like legitimately composite ops, but there are other cases where the ops just shouldn't be composite, and we should update their native_functions.yaml entry to point that out. A recent example of that was https://github.com/pytorch/pytorch/issues/60892 (`linalg.eigh()` is implemented using DispatchStub, so it can't be composite. That particular bug was pretty bad - the codegen didn't generate a cuda device guard, because it thought it was a composite kernel)

**Comment by zou3519** [comment]
> > CompositeImplicitAutograd operations should not be allowed to call operations that do not dispatch
> 
> I'm not sure how to define "operations" here. I'm pretty sure that operations in this case should refer to the TensorImpl API? (i.e. in `TensorImpl.h`).

"Direct accesses to the TensorImpl API" sounds like the right thing here. Maybe we should come up with more examples of other things that are problematic for backends.

> Maybe we should just agree on which methods are not okay, and figure out how to test/error for those.

We're probably not going to end up with a solution that really works for "all backends". For example, sizes() access is problematic for nestedtensor but not for most backends (and sizes() is really useful in implementing operators so I'd feel bad about banning it). So agreeing on which methods are not okay seems reasonable.

> Maybe it would be helpful to come up with a test like what you described above:
> 
> > we can use one of the Backend private keys to create a Tensor Extension (call it Wrapper) that wraps a Tensor.

Hmm, so my quick thought was:
- we can use one of the Backend private keys to create a Tensor Extension (call it Wrapper) that wraps a Tensor.
- We give this a backend fallback that (1) unwraps the tensor, (2) calls the underlying operation on the Tensor, and (3) re-wraps the result
- We test a CompositeImplicitAutograd op `foo` by calling `expected = foo(normal_tensor)` and `result = foo(wrap(normal_tensor)).unwrap()` and comparing `expected`.
- This catches data_ptr access (because the Wrapper does not have a data_ptr). This also catches cases where we directly resize the TensorImpl because the Wrapper would be resized but the underlying Tensor would not be resized. There are some edge cases around in-place operations, though.

This won't catch all the problems though and I wish there were an easy way to mock TensorImpl to detect these things

**Comment by bdhirsh** [comment]
> For example, sizes() access is problematic for nestedtensor but not for most backends (and sizes() is really useful in implementing operators so I'd feel bad about banning it). 

Hmm... so if you try to use NestedTensor and call composite ops, do a bunch of them just break? I'm not sure if that's an inherent problem with NestedTensor or if there are just better ways to write the composites that avoid those issues (either not using sizes() at all, or using it in a way that's more resilient to different outputs somehow).

> we can use one of the Backend private keys to create a Tensor Extension (call it Wrapper) that wraps a Tensor. ..... his won't catch all the problems though and I wish there were an easy way to mock TensorImpl to detect these things

In particular, how would that catch the cases where we resize the wrapper directly? I think we'd need to make sure the wrapper is written kinda like BatchedTensorImpl, where it ensures that it sets its sizes differently from the wrapped tensor. That kinda makes me think that we'll need to add extra functionality the wrapper to catch each type of error. It would be nice to be able to more generically catch errors, but maybe this is fine for now (catching all data_ptr and resize issues in composites).

The crazy idea that I had was to codegen a different version of `TensorImpl` that has something like `ASSERT(dynamic_cast<TestTensorImpl*>(this) == nullptr)` in each method that we never want composites to call on the wrapper. That way we can just blanket assert that composites never call the "bad" API's on the wrapper. But I'm not sure if we can do that without just having a separate build.

**Comment by zou3519** [comment]
> Hmm... so if you try to use NestedTensor and call composite ops, do a bunch of them just break? I'm not sure if that's an inherent problem with NestedTensor or if there are just better ways to write the composites that avoid those issues

It depends on where the dispatch key is... If there's a single dispatch key above autograd then nested tensor doesn't see any primitives. If there's a single dispatch key below autograd then yes the composite ops will break. Maybe htis is more of a design problem.

> In particular, how would that catch the cases where we resize the wrapper directly? I think we'd need to make sure the wrapper is written kinda like BatchedTensorImpl, where it ensures that it sets its sizes differently from the wrapped tensor. 

Yes, we'd have to make sure the wrapper is written like BatchedTensorImpl.

> That kinda makes me think that we'll need to add extra functionality to the wrapper for each class of error that we want to catch (e.g. for data_ptr access, we need to explicitly set the wrapper to have null storage). It would be nice to be able to more generically catch errors, but maybe this is fine for now (catching all data_ptr and resize issues in composites).

Agree it would be nice to have a better way to generically catch errors. Another crazy idea is using [LD_PRELOAD to overwrite](http://www.goldsborough.me/c/low-level/kernel/2016/08/29/16-48-53-the_-ld_preload-_trick/) TensorImpl methods (not sure if this actually works though)

**Comment by ngimel** [comment]
A lot of TensorImpl methods are inline (as they should be), you can't intercept them with LD_PRELOAD

**Comment by ezyang** [comment]
> What happens when one accesses the data_ptr for a meta tensor? meta tensors currently don't work with linalg_cholesky, but is the data_ptr read going to be problematic?

For meta tensors, the correct resolution is to just implement Meta at a high enough level (e.g., `linalg_cholesky`, not the internal helpers) so the `data_ptr` read can be completely bypassed.

**Comment by zou3519** [comment]
> > What happens when one accesses the data_ptr for a meta tensor? meta tensors currently don't work with linalg_cholesky, but is the data_ptr read going to be problematic?
> 
> For meta tensors, the correct resolution is to just implement Meta at a high enough level (e.g., `linalg_cholesky`, not the internal helpers) so the `data_ptr` read can be completely bypassed.

This would involve turning `linalg_cholesky` into not-a-CompositeImplicitAutograd op, right?Because `linalg_cholesky` is a CompositeImplicitAutograd op, the Autograd key will first decompose it into its constituents before hitting the meta key and the constituents involve a data_ptr access

**Comment by ezyang** [comment]
Regarding direct access to TensorImpl, you can't catch these problems immediately, but you can catch them after the fact. This is because the wrapper tensor, and the inner tensor, have different metadata. So you just want to assert (e.g., on entry to every function) that the metadata between the wrapper and the inner are always consistent. This is a generally useful facility that most wrapper tensor implementors would like to have.

> This would involve turning linalg_cholesky into not-a-CompositeImplicitAutograd op, right?Because linalg_cholesky is a CompositeImplicitAutograd op, the Autograd key will first decompose it into its constituents before hitting the meta key and the constituents involve a data_ptr access

Yes, that's my proposal. Sometimes this will be a huge lift but in the case of `linalg_cholesky` it is no big deal.

```
Tensor linalg_cholesky(const Tensor &self) {
  Tensor result, info;
  std::tie(result, info) = at::linalg_cholesky_ex(self, /*check_errors=*/false);

  // we pass check_errors=false above and do the check here
  // so that the name of the function is correct in the error message
  if (self.dim() > 2) {
    batchCheckErrors(info, "torch.linalg.cholesky");
  } else {
    singleCheckErrors(info.item<int64_t>(), "torch.linalg.cholesky");
  }

  return result;
}

```

**Comment by albanD** [comment]
> So some dispatch keys could say "yes I have item, please give me the composite", while others would say "I don't have it, you gotta override linalg_cholesky directly"

Isn't that what happens for functions like addr: https://github.com/pytorch/pytorch/blob/ac5a40e068b0a1ce3c873ef1f681564376dbae52/aten/src/ATen/native/native_functions.yaml#L458-L462
Where the autograd is defined only for CPU/CUDA and for other backends, we hit the composite function implementation.

**Comment by ezyang** [comment]
Sort of, but it's kind of the reverse situation: you want composite implicit autograd behavior for CPU and CUDA (because the wrapper function will work with AD only on the inner call) and an explicit autograd for other backends (since they are going to override the entire thing)

**Comment by zou3519** [comment]
I've been playing around with various ways to implement the testing mechanism. So far the following seems promising, would love to hear thoughts about it (especially from @ezyang and @bdhirsh because it involves dispatch to python, see the "Funny business" section).

First off, here is the behavior that we are "banning" inside of CompositeImplicitAutograd operations:
- accessing data_ptr
- calling .set_, .copy_, .resize_ on ANY tensor (even on tensors that are unrelated from the inputs that were created inside the operator)

The idea is to create a `__torch_dispatch__` wrapper tensor object (call it CompositeImplicitAutogradCompliantTensor) that holds a standard PyTorch tensor
- `__torch_dispatch__` checks if .set_, .copy_, .resize_ get called and error out if so
- the wrapper tensor object has a Meta storage. When the data_ptr gets accessed, the Meta storage complains loudly.

We would add new OpInfo tests, one for each operator, that creates these special CompositeImplicitAutogradCompliantTensor using sample inputs and runs the operator on it.

This doesn't completely solve the problem of what happens if someone creates a new Tensor and then calls `.resize_` on it because tensors created via e.g. torch.empty are not instances of CompositeImplicitAutogradCompliantTensor. For this, we introduce a "python mode key".

### Python Mode Key

On the Python side, a user can use a context manager `with torch.python_mode(torch_dispatch_object_instance):` (please bikeshed) by passing it an instance of the torch_dispatch object.

Inside the context manager, all factory functions (e.g. `torch.empty`) will go through `__torch_dispatch__` and return whatever it returns.

This means that for our tests, for each operator:
- we create CompositeImplicitAutogradCompliantTensors
- we set the python mode
- Inside the context manager we invoke the operator on the CompositeImplicitAutogradCompliantTensors

### Funny business with implementing Python Mode Key

There are a lot of weird things I ran into while trying to prototype this out.

**Problem 1: torch deploy**
I'm not sure if the current design is a problem with torch deploy. All the internal and external CI tests fail. `torch.python_mode(torch_dispatch_object_instance)` sets global state (not thread-local state) ([see here](https://github.com/pytorch/pytorch/pull/62509/files#diff-8eb0a9f931de889597414e56b61c407848aaa4b2ab9fad59a2d5bb9264fdb794R9)) -- should this be thread-local instead so that multiple subinterpreters work?

**Problem 2: wrapper-style torch_dispatch objects run into #62182**
To recap, the problem here is that wrapper-style torch_dispatch objects have unrelated meta tensors as their storages. Autograd has some asserts to check that for e.g. `B = A.permute(1, 2, 0)`, `A.storage()` and `B.storage()` are the same and these get triaged.

To make this work right now, inside the `__torch_dispatch__` of an object, we check if the operation is a view. If the operation is a view (e.g. `B = A.permute(1, 2, 0)`), then we attempt to get the meta storage of B to alias the meta storage of A via some surgery (implementation [here](https://github.com/pytorch/pytorch/pull/62509/files#diff-989c7c7ac95c2c037644e61157c29eee13347f01d81d59f8ca8a0acafe086e61R103-R118)).

My questions for this are: does this seem like a reasonable workaround, or should we try to explore alternatives (like registering a new meta device type that doesn't have storage?)

**Comment by ezyang** [comment]
> should this be thread-local instead so that multiple subinterpreters work?

Yeah, making this thread local seems like the right call.

> My questions for this are: does this seem like a reasonable workaround, or should we try to explore alternatives (like registering a new meta device type that doesn't have storage?)

This seems reasonable

**Comment by albanD** [comment]
> calling .set_, .copy_, .resize_ on ANY tensor

I'm confused. Why are these ops banned in particular? What about all the other inplace ops?

**Comment by zou3519** [comment]
> > calling .set_, .copy_, .resize_ on ANY tensor
> 
> I'm confused. Why are these ops banned in particular? What about all the other inplace ops?

I'm down to ban all in-place ops in CompositeImplicitAutograd out-of-place ops but I'm not sure that's OK and it might be too big of a hammer.

The thing we are trying to prevent with {set_, copy_, resize_} is that the user should not be calling the out= variant of an operator (i.e. https://github.com/pytorch/pytorch/issues/61485).

**Comment by albanD** [comment]
In my mind, CompositeImplicitAutograd are just like any other non-native function.
There are quite a lot of inplace ops in these (especially in torch.nn at the python level).
So that feels a bit unrealistic to forbid all inplace (or even things like copy_).
Am I missing something here?

**Comment by zou3519** [comment]
The claim is that CompositeImplicitAutograd ops should work with all (or most) backends. We don't have to forbid all in-place operations, but we do need to forbid {set_, copy_, resize_}.

The specific reason why we are forbidding copy_ is that it prevents backends (other than vmap!) from working. For example, using copy_ in a CompositeImplicitAutograd function can cause "Dispatch to Python" objects to lose their typing (https://github.com/pytorch/pytorch/pull/62262, https://github.com/pytorch/pytorch/pull/61456)

**Comment by ezyang** [comment]
I think copy_ is definitely the marginal case, since it is pretty similar to inplace operations, and the same problem (loss of typing) can occur for inplace, e.g., `plain_tensor.add_(proxy)`, although it is less likely to occur. The thing about `copy_`, however, is that as long as you're not specifically writing into a view, it's always cost free to replace with the functional version.  And if you are writing into a view, then @ailzhang/@bdhirsh's functionalization pass is the way to get it working.

**Comment by bdhirsh** [comment]
Do you think that all of the info here should also apply to `CompositeExplicitAutograd` kernels? If the idea is that they should also work on all backends (and the only difference is that autograd is disabled for every operator that we call inside of the kernel).

**Comment by ngimel** [comment]
The reason we are here again is that CompositeImplicitAutograd `matmul` is calling `at::native::` operations https://github.com/pytorch/pytorch/pull/64387/files#diff-db2b91c51cffd1fba933933ac20de256f5f0ced095890a1a49a17d73037001a2R1455. The link is to a call added by a PR under review, but `at::native::dot_out` call existed before the PR.

**Comment by zou3519** [comment]
> Do you think that all of the info here should also apply to `CompositeExplicitAutograd` kernels? If the idea is that they should also work on all backends (and the only difference is that autograd is disabled for every operator that we call inside of the kernel).

Probably, especially if some backends don't support data_ptr. This is going to be different to test for (than the idea I had to use Python Mode to test for CompositeImplicitAutograd compliance).

**Comment by zou3519** [comment]
> https://github.com/pytorch/pytorch/pull/64387/files#diff-db2b91c51cffd1fba933933ac20de256f5f0ced095890a1a49a17d73037001a2R1455

Ugh matmul is really weird because it has combined both the out variant and the regular variant into a single native:: function

**Comment by ezyang** [comment]
The code just needs a straight up rewrite from scratch. Also cc @mruberry

**Comment by zou3519** [comment]
`is_conj` (and probably many of the `is_{blah}` functions) has this problem where it is CompositeImplicitAutograd and directly accesses the TensorImpl API, leading to incorrect behavior (see https://github.com/facebookresearch/functorch/issues/117). We probably want to make these CompositeExplicitAutograd

**Comment by ngimel** [comment]
THey are not really CompositeImplicitAutograd, they are `manual_cpp_binding`, so they skip the dispatch mechanism altogether (for perf reasons).

**Comment by bdhirsh** [comment]
> `is_conj` (and probably many of the `is_{blah}` functions) has this problem where it is CompositeImplicitAutograd and directly accesses the TensorImpl API, leading to incorrect behavior (see [facebookresearch/functorch#117](https://github.com/facebookresearch/functorch/issues/117)). We probably want to make these CompositeExplicitAutograd

Those ops are probably meant to bypass the dispatcher for perf.

What do you think of setting up the metadata on TensorImpl's in functorch (BatchedTensorImpl, etc) to reflect their base tensor, such that all of these functions work?

In the `is_conj` example, if you have a batched_tensor(cpu_tensor), you would need to make sure that if the cpu_tensor's keyset has the `Conjugate` dispatch key, then the wrapping `BatchedTensorImpl` also has that key in its keyset. So if the wrapped tensor "is_conj", then the wrapper "is_conj" too.

I'm doing something kind of similar in functionalization, where I copy all of the meta data from the wrapped TensorImpl onto the wrapper, except for a few things (keyset and storage).

**Comment by malfet** [comment]
@zou3519 can this be closed? Or is there any work planned for 1.11? Tentatively moving to 1.12

**Comment by zou3519** [comment]
@malfet let's leave this open, but there's no work to be done for 1.11

**Comment by zou3519** [comment]
This issue is technically the same as https://github.com/pytorch/pytorch/issues/69991. It's still on our radar, but PyTorch operators are not 100% composite compliant yet. Let's kick the milestone to (1.13?) and plan around it.

**Comment by zou3519** [comment]
We hit our goals for this for 1.13, so I'm closing this issue.
