### ISSUE TITLE
TCPStoreTest.testWatchKeyCallback Timed Out

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#61671]
https://app.circleci.com/pipelines/github/pytorch/pytorch/350200/workflows/dcfc939b-ad6f-4238-8ea3-c022931473d1/jobs/14751699

```
Jul 13 16:30:44 [       OK ] TCPStoreTest.testHelperPrefix (1135 ms)
Jul 13 16:30:44 [ RUN      ] TCPStoreTest.testWatchKeyCallback

Too long with no output (exceeded 1h30m0s): context deadline exceeded
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by mrshenli** [comment]
cc @H-Huang

**Comment by H-Huang** [comment]
Closed as the watch key callback feature was removed, test does not exist anymore
