### ISSUE TITLE
torch.sort docs

### ISSUE THREAD

**Issue by agadetsky** [pytorch/pytorch#61682]
## 📚 Documentation

torch.sort documentation has wrong info about torch.sort with stable=True on cpu. At the moment it already works for GPU too. The GPU version was added with this PR https://github.com/pytorch/pytorch/pull/56821

cc @brianjo @mruberry

**Comment by malfet** [comment]
Thank you for reporting. Indeed this warning can be removed

**Comment by mruberry** [comment]
We would accept a PR removing the warning.
