### ISSUE TITLE
Export operator hardsigmoid to onnx

### ISSUE THREAD

**Issue by rabbitHog** [pytorch/pytorch#61705]
## 🚀 Feature
Export operator hardsigmoid to onnx

## Motivation

I need to export a model to onnx and I called function torch.onnx.export. Then I got an error: RuntimeError: "Exporting the operator hardsigmoid to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub."

## Pitch

I hope that exporting a model with hardsigmoid is supported.

## Additional context

cc @BowenBao @neginraoof

**Comment by BowenBao** [comment]
hardsigmoid is already supported in latest PyTorch https://github.com/pytorch/pytorch/blob/aa01a7a61caecbfeaf868fd379fa5d6a595362ea/torch/onnx/symbolic_opset9.py#L1936 please upgrade your PyTorch version, thanks.
