### ISSUE TITLE
Compute csr representation on torch.sparse.Tensor.coalesce for faster sparse matrix multiplication 

### ISSUE THREAD

**Issue by kose-y** [pytorch/pytorch#6171]
On the code on sparse matrix-dense matrix multiplication
https://github.com/pytorch/pytorch/blob/master/aten/src/THS/generic/THSTensorMath.c#L305
and 
https://github.com/pytorch/pytorch/blob/master/aten/src/THCS/generic/THCSTensorMath.cu#L58 , 
it first computes csr representation, then perform sparse matrix-dense matrix multiplication based on that representation, then destroy the csr representation. 
If we repeatedly perform matrix multiplication on the same sparse matrix, computing csr representation is redundant. This could be resolved by computing csr representation only once when coalescing  and save it as a member of `THSTensor` or `THCSTensor` ( https://github.com/pytorch/pytorch/blob/master/aten/src/THS/generic/THSTensor.cpp#L428 and
https://github.com/pytorch/pytorch/blob/master/aten/src/THCS/generic/THCSTensor.cu#L38 ). This would enhance speed of sparse matrix-dense matrix multiplication.

Will this be a good modification? Shall I try to make a pull request on this one?

cc @vincentqb @aocsa @nikitaved @pearu @mruberry

**Comment by kose-y** [comment]
This may be a good starting point for https://github.com/pytorch/pytorch/issues/3158, https://github.com/pytorch/pytorch/issues/4247, and https://github.com/pytorch/pytorch/issues/5262 .

**Comment by livenletdie** [comment]
CuSparse libraries support multiple sparse matrix formats such as COO, CSR, ELLPACK etc where a different format might make sense depending on the sparse matrix property. Given that, would it be possible to allow the user to control the sparse matrix layout to begin with? Like say we extend .layout option beyond just sparse_coo to allow addition of other sparse matrix formats. Is that easy to extend? I dont know enough about how these tensors are implemented to know that myself.

**Comment by ezyang** [comment]
Yes, this makes sense (indeed, with the new `torch.layout` API bits, we have planned for it), but no, it's not so easy to support. It basically entails adding a new backend to PyTorch, and there are a lot of moving bits to making this happen, especially because we are rewriting how all of this works internally (C10).

**Comment by matthieuheitz** [comment]
@kose-y Did you finda workaround ? I'm thinking about trying to adapt the same function `THCSTensor_(spaddmm)`, and wrapping it in the same way, so that I can call it from PyTorch. Did you start doing something of the sort by any chance ?
I also noticed that these files have disappeared now in master. So, you should maybe update the links in your first comment, to v0.4.0 for example.

**Comment by matthieuheitz** [comment]
Starting from `master`, my first attempt consists of splitting this function: https://github.com/pytorch/pytorch/blob/bc66d982482e6d6c586d12de5176d9d4bf38eec5/aten/src/ATen/native/sparse/cuda/SparseCUDATensorMath.cu#L44

in 2 parts (see code below), so that I can call the first part at the very beginning, and then the second part every time I need to do a matmat product.

I know it's not very pretty, but I'm just trying to write something that could work, while waiting for the next release of PyTorch.
Now I need to do the wrapping in order to be able to call `sp_coo_to_csr` from PyTorch, and replace the calls to `s_addmm_out_sparse_dense_cuda` by `s_addmm_out_spcsr_dense_cuda`, and I'm not sure how to do that...

@ezyang, can I have some guidance on if my functions could potentially work, and if the wrapping would be easy ? Also, do you have a timeline for when this issue will be adressed ?

```c++
// Takes a SparseTensor (in COO) and returns the CSR representation as a tuple (or array) of Tensors 
// sp_sizes is a vector containing the important sizes of the sparse matrix : [m, k, nnz]
ArrayRef<Tensor> sp_coo_to_csr(const SparseTensor& sparse_, ArrayRef<int64_t>* sp_sizes) {
#ifndef __HIP_PLATFORM_HCC__
  AT_CHECK(sparse_.is_cuda(), "addmm: expected 'mat1' to be CUDA, but got CPU");

  AT_CHECK(_check_device({sparse_}));

  // TODO: This error message seems awfully opaque
  AT_CHECK(sparse_._sparseDims() == 2, "addmm: 2D tensor expected, got ", sparse_._sparseDims(), "D tensor");
  AT_CHECK(sparse_._denseDims() == 0, "addmm: scalar values expected, got ", sparse_._denseDims(), "D values");

  // mxk * kxn = mxn
  int64_t m = sparse_.size(0);
  int64_t k = sparse_.size(1);
  int64_t nnz = sparse._nnz();

  sp_sizes[0] = m;
  sp_sizes[1] = k;
  sp_sizes[2] = nnz;

  SparseTensor sparse = sparse_.coalesce();

  LongTensor indices = sparse._indices();
  Tensor values = sparse._values();

  LongTensor rowIndices = indices.select(0, 0);
  LongTensor colIndices = indices.select(0, 1);
  IntTensor csr = _to_csr_int(rowIndices, m, nnz);
  IntTensor colIndicesInt = at::empty({colIndices.size(0)}, indices.type().toScalarType(kInt));
  colIndicesInt.copy_(colIndices);

  return {colIndicesInt, csr, values};
#else
  AT_ERROR("s_addmm_out_sparse_dense_cuda: HIP not supported");
#endif
}

// Takes the sparse matrix as a array of Tensors, and an array of sizes
Tensor& s_addmm_out_spcsr_dense_cuda(Tensor& r_, const Tensor& t, const ArrayRef<Tensor> sparse_, const ArrayRef<int64_t> sp_sizes, const Tensor& dense, Scalar beta, Scalar alpha) {
#ifndef __HIP_PLATFORM_HCC__
  AT_ASSERT(t.is_cuda()); // dispatch argument
  AT_CHECK(r_.is_cuda(), "addmm: expected 'out' to be CUDA, but got CPU");
  AT_CHECK(dense.is_cuda(), "addmm: expected 'mat2' to be CUDA, but got CPU");

  // Get back the info on the sparse matrix
  IntTensor colIndicesInt = sparse_[0];
  IntTensor csr = sparse_[1];
  Tensor values = sparse_[2];

  // mxk * kxn = mxn
  int64_t m = sp_sizes[0];
  int64_t k = sp_sizes[1];
  int64_t nnz = sp_sizes[2];
  int64_t n = dense.size(1);

  AT_CHECK(_check_device({colIndicesInt,csr,values}));
  AT_CHECK(_check_device({r_, t, dense}));

  // TODO: This error message seems awfully opaque
  AT_CHECK(dense.dim() == 2, "addmm: 2D tensor expected, got ", dense.dim(), "D tensor");


  AT_CHECK(t.size(0) == m,
	  "addmm: Argument #1 (t): Expected dim 0 size ", m, ", got ", t.size(0));
  AT_CHECK(t.size(1) == n,
	  "addmm: Argument #1 (t): Expected dim 1 size ", n, ", got ", t.size(1));
  AT_CHECK(dense.size(0) == k,
	  "addmm: Argument #3 (dense): Expected dim 0 size ", k, ", got ", dense.size(0));

  r_.resize_({m, n});

  // No half support, so we don't have to use CUDATypeConversion
  Tensor r__;
  AT_DISPATCH_FLOATING_TYPES(
	  values.type(), "addmm_sparse_cuda", [&] {
		scalar_t cast_beta = beta.to<scalar_t>();
		scalar_t cast_alpha = alpha.to<scalar_t>();
		if (cast_beta == 0) {
		  r_.zero_();
		} else if (cast_beta == 1) {
		  if (!isSameTensor(t, r_)) {
			r_.copy_(t);
		  }
		} else {
		  at::mul_out(r_, t, beta);
		}

		/* r_ */
		if(r_.stride(0) == 1 && r_.stride(1) == r_.size(0)) {
		  r__ = r_;
		} else {
		  // TODO: how... strange
		  r__ = r_.transpose(0, 1).clone();
		  r__.transpose_(0, 1);
		}

		/* dense */
		Tensor dense_;
		char transpose_dense;
		if(dense.stride(0) == 1 && dense.stride(1) == dense.size(0)) {
		  transpose_dense = 'n';
		  dense_ = dense;
		} else if(dense.stride(1) == 1 && dense.stride(0) != dense.size(1)) {
		  transpose_dense = 't';
		  dense_ = dense;
		} else {
		  transpose_dense = 't';
		  dense_ = dense.contiguous();
		}

		sparse::cuda::csrmm2(
		  'n',
		  transpose_dense,
		  m,
		  n,
		  k,
		  nnz,
		  cast_alpha,
		  values.data<scalar_t>(),
		  csr.data<int32_t>(),
		  colIndicesInt.data<int32_t>(),
		  dense_.data<scalar_t>(),
		  (transpose_dense == 'n' ? dense_.stride(1) : dense_.stride(0)),
		  cast_beta,
		  r__.data<scalar_t>(),
		  r__.stride(1));

	  });

  r_.copy_(r__);
  return r_;
#else
  AT_ERROR("s_addmm_out_sparse_dense_cuda: HIP not supported");
#endif
}

```

**Comment by kose-y** [comment]
@matthieuheitz 
My initial try is in #6225 , which is before the release of 0.4.0, but haven't tried since then.

**Comment by matthieuheitz** [comment]
Happy new year ! :tada: 
Any updates on this issue ?

**Comment by IvanYashchuk** [comment]
It's now possible in PyTorch to convert a COO 2D tensor to CSR explicitly:
```python
In [1]: import torch

In [2]: a = torch.randn(2, 3, device='cuda').to_sparse()

In [3]: a.layout
Out[3]: torch.sparse_coo

In [4]: a.to_sparse_csr()
Out[4]:
tensor(crow_indices=tensor([0, 3, 6]),
       col_indices=tensor([0, 1, 2, 0, 1, 2]),
       values=tensor([-0.3945, -2.1194, -0.3086, -0.1866,  0.1779,  0.6291]),
       device='cuda:0', size=(2, 3), nnz=6, layout=torch.sparse_csr)
```
CSR matrices support `torch.matmul` operation.
