### ISSUE TITLE
Apply not Supported in Torchscript

### ISSUE THREAD

**Issue by Explorer90** [pytorch/pytorch#61743]
## 🐛 Bug

I have installed the following https://github.com/erikwijmans/Pointnet2_PyTorch/tree/acda965224f35854bc331cd5fe140393216b0a71/pointnet2_ops_lib library for use.  I am trying to import a function from that (e.g. ball_query) and call it in my forward. However, I get the following error when trying to compile with torchscript
`Python builtin <built-in method apply of FunctionMeta object at 0x41289c8> is currently not supported in Torchscript`

## To Reproduce

1. Install pointnet2_ops (from source)
1. Here is a very trivial example to reproduce the error.

```
import torch
import pointnet2_ops

class DummyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        return pointnet2_ops.pointnet2_utils.ball_query(3.4, 5, x, x)
    
model = torch.nn.Sequential(DummyModule()).to('cuda')
model = torch.jit.script(model)
```

## Expected behavior

Support the Apply functionality or state a workaround

## Environment

PyTorch version: 1.8.1+cu102

cc @gmagogsfm

**Comment by JiaweiShiCV** [comment]
the same issue

**Comment by gmagogsfm** [comment]
This is a known unsupported feature blocked by first-class function as a value in TorchScript. There is currently no immediate plan to add this support. I will close this for now
 
[For future readers of this comment]
If you have similar need, feel free to comment on this thread if you have the same feature request or if you are interested in contributing this feature.

**Comment by gioipv** [comment]
Yes, I also meet this problem.
I use [DCNv2](https://github.com/MatthewHowe/DCNv2) pakage install from source for my model. When converting from pytorch to torchscrip. It will raise an error
```
RuntimeError: 
Python builtin <built-in method apply of FunctionMeta object at 0x561c6db40f80> is currently not supported in Torchscript:
  File "./module/models/networks/DCNv2/dcn_v2.py", line 161
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)
        return dcn_v2_conv(
               ~~~~~~~~~~~ <--- HERE
            input,
            offset,
```
I hope that torchscript will support this feature in the next version.

**Comment by syfbme** [comment]
Same issue...

**Comment by heweweh** [comment]
Same issue...

**Comment by jiayixu64** [comment]
Same issue! We are wondering what is the challenge to support this? Is it possible to prioritize the support of this? Thanks!

**Comment by cunliangkong** [comment]
Same issue !!! Would be useful to get this support.

**Comment by punitsingh2009** [comment]
Same issue !!! Would be useful to get this support.

**Comment by maichm** [comment]
Same issue !!! Would be useful to get this support.

**Comment by yulinfeng000** [comment]
Same issue !!!!

**Comment by humayun0156** [comment]
Same issue !!!!
