### ISSUE TITLE
enabling older computing capabilities like 5.0

### ISSUE THREAD

**Issue by wilkluka** [pytorch/pytorch#6175]
I am using ubuntu 16.04 and I am trying to compile pytorch and I want to enable 5.0 cuda computing capability where to set it - in what file or maybe in environment variable?

**Comment by zou3519** [comment]
The environment variable is `TORCH_CUDA_ARCH_LIST`. You can build with `TORCH_CUDA_ARCH_LIST=5.0 python setup.py build develop`.

This should probably be added to the README (or setup.py, where the other common env variables are documented).
