### ISSUE TITLE
Can we initialize a progress in an async way?

### ISSUE THREAD

**Issue by densechen** [pytorch/pytorch#61762]
Currently, the distributed package needs each node to run over the same code at the same time and then the progress group will be created by init_progress_group() function. While waiting for other nodes connecting to this progress, the process will be zombied. Are there any methods that we can build the connection in an async operation that will return a handler but not occupy the process?

👀🙂😝😋😋

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by SciPioneer** [comment]
Sounds interesting! 

However, since normally we expect calling `init_process_group` only once and definitely not calling it in a loop, how much speedup an async initialization can give for your use case? Before adding another API at the cost of simplicity, we need to first evaluate its potential value.

Moreover, the primitives in process group API are not that novel and are mainly dependent on the underlying communication backends including NCCL, GLOO, and MPI. Do you see any of these libraries provide such an async API?

**Comment by densechen** [comment]
@SciPioneer I have not seen an API provided such feature yet. Rather than speed up the program, this feature can make the program more flexible. We can do many extra things while waiting for the connection between each node. What's more, if we run multi-thread in python, this feature can largely reduce the influence on each thread. Currently, this occupying operation will also stop all threads in a process.🙈

**Comment by SciPioneer** [comment]
> Rather than speed up the program, this feature can make the program more flexible. We can do many extra things while waiting for the connection between each node.

As I mentioned, the initialization should be an one-off operation and shouldn't be a performance bottleneck, so I'm not sure if this can make a real performance difference between "async init + do extra things" and "init and do extra things sequentially".

> What's more, if we run multi-thread in python, this feature can largely reduce the influence on each thread. Currently, this occupying operation will also stop all threads in a process.🙈

Multi-threading in Python is already blocked by GIL, so it won't be real multi-threading.

**Comment by densechen** [comment]
`As I mentioned, the initialization should be an one-off operation and shouldn't be a performance bottleneck, so I'm not sure if this can make a real performance difference between "async init + do extra things" and "init and do extra things sequentially".`
It has less influence on the perfomrance, but will make programing more flexible. If we want to build the connection between different node with different address. Suppose that, if address A may contains with 4 node but is unstable, but address B may only be 2 nodes  but rather stable. Sometimes, the address A may be failed to connect, but we can shift to address B.
At those cases, (federated learning), it will be usefull to do a async init operation.

`Multi-threading in Python is already blocked by GIL, so it won't be real multi-threading.`
Yes, it is. So, we are unable to build the connection on a thread make it look as an async operation.

**Comment by SciPioneer** [comment]
Thanks for the explanation! 

It may make sense to support async `init_process_group` in your scenario like federated learning. However, process group in PyTorch API is mainly a wrapper of NCCL/GLOO/MPI libraries. If the underlying library does not support this functionality, it will be really hard for us to support this.

In your scenario, I think PyTorch RPC framework or parameter-server paradigm can probably be a better approach.

**Comment by densechen** [comment]
@SciPioneer 😀😀😀
Yes, as you said, PyTorch RPC is a better choice!
And I will try it as soon as possible.
Thanks for your advise!
