### ISSUE TITLE
Make direct network downloading reliable to reduce flakiness in CI

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#61793]
One source of CI flakiness is network downloading.

- [ ] Find all the possible network downloading scripts
- [ ] Prefer using a systematic level of egress proxy with "cache" so that CI have higher reliability on networking
- [ ] Wrap network fetch with something like `@retry` decorators
- [ ] Optionally, before the proxy is in place, make sure these downloads have retries, correct exceptions handling, and/or mirrors as fallback (e.g. s3)

E.g. recent fix:
- https://github.com/pytorch/pytorch/pull/61789

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
I think more resilient solution would be to setup an egress proxy on the test runner, but also make certain builds (say nightlies) bypass it, to make sure that our CI/CD gets periodic updates against latest ecosystem changes

**Comment by ezyang** [comment]
egress proxy is a good idea. Actually it is pretty easy to just turn of network access entirely via Docker, but that would have required a flag day where we fixed all of the network access and that's just too hard. Egress proxy you could whitelist everything that exists today and then slowly start removing stuff.

**Comment by zhouzhuojie** [comment]
Closing it as we shipped the squid cache proxy for all the `build` and `test` phases in GHA.
