### ISSUE TITLE
batches_outstanding == 0 in dataloader during iteration

### ISSUE THREAD

**Issue by Mabinogiysk** [pytorch/pytorch#6179]
- PyTorch or Caffe2: Pytorch
- OS: ubuntu16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6
- CUDA/cuDNN version: cuda8.0

I got this error during iteration:
```
~/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    269         if self.batches_outstanding == 0:
    270             self._shutdown_workers()
--> 271             raise StopIteration
    272 
    273         while True:

StopIteration: 
```
Is anybody can help?

**Comment by Mabinogiysk** [comment]
I found that the data_loader can only go through my data once. After iterating every data in dataset, it stops.

**Comment by apaszke** [comment]
That’s just how iterators in Python work. You can get a new iterator by calling `iter(data_loader)`

**Comment by Mabinogiysk** [comment]
Thanks!
