### ISSUE TITLE
Enable benchmark scribe reporting for GHA

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#61809]
The issue is that `os.environ.get("SCRIBE_GRAPHQL_ACCESS_TOKEN")` won't be available at PR time, so benchmark stats reporting from PR (especially from fork PRs) won't be able to report the stats to the scribe.

This could be fixed by leveraging GHA's aws instance IAM to directly connect to scribe proxy.

https://github.com/pytorch/pytorch/blob/master/benchmarks/upload_scribe.py#L44-L47

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
We've identified scribe as a deprecated way of reporting test stats and are instead moving towards a more OSS oriented solution, closing.
