### ISSUE TITLE
RuntimeError: Function 'AcosBackward' returned nan values in its 0th output.

### ISSUE THREAD

**Issue by onlinehuazai** [pytorch/pytorch#61810]
## ❓ Questions and Help

RuntimeError: Function 'AcosBackward' returned nan values in its 0th output.

**Comment by soulitzer** [comment]
It easy for AcosBackward to get nan values because its only defined on the range [-1, 1]. You'll want to be more careful about what your gradients are propogating back into the AcosBackward.

Please use the PyTorch forums https://discuss.pytorch.org/ is a better place for these types of questions. The issues should only be for discussion of bugs and features.

**Comment by onlinehuazai** [comment]
Function 'ThnnConv2DBackward' returned nan values in its 0th output.  

so many ''***Backward'' errors.

**Comment by loeweX** [comment]
Leaving this reply for others who might stumble upon this issue in the future:

AcosBackward actually only works in the range (-1, 1), i.e. it cannot handle values that are exactly -1 or 1. If your inputs are in the range [-1, 1] (i.e. they might contain -1 and 1), a simple fix could be to use torch.clamp(x, -0.99999, 0.99999) before applying the arccos on x.

**Comment by snknitin** [comment]
If it is an error in the 0th output, that means your weights are still not fully updated so some values in some batch's predictions , during your first epoch are nans. So it's not your inputs, but your model predictions that are nans. Could be an overflow or underflow error. This will make any loss function give you a `tensor(nan)`.What you can do is put a check for when loss is nan and let the weights adjust themselves

```python
criterion = SomeLossFunc()
eps = 1e-6
loss = criterion(preds,targets)
if loss.isnan(): loss=eps
else: loss = loss.item()
loss = loss+ L1_loss + ...
```
