### ISSUE TITLE
[feature request]: Add an X11-enabling Dockerfile

### ISSUE THREAD

**Issue by topiaruss** [pytorch/pytorch#6182]
Mine extends the pytorch image built by the current Dockerfile.

I tag the extended image pytorchX11 and the new build file is DockerfileX11

I'll be happy to contribute, together with additional lines in the README to explain the build step.

**Comment by apaszke** [comment]
I’m not sure if we will want this. You can just build your own dockerfile on top of what we provide, but adding a new one for every other program people use with PyTorch would result in explosion in the number of dockerfiles we need. Thanks for the proposal!
