### ISSUE TITLE
torch.permute missing in docs

### ISSUE THREAD

**Issue by BramVanroy** [pytorch/pytorch#61830]
## 📚 Documentation

When I search for the permute function (torch.permute) I can only [find](https://pytorch.org/docs/stable/search.html?q=torch.permute&check_keywords=yes&area=default) the method (torch.Tensor.permute). The irony is that torch.Tensor.permute tries to redirect to the function for more information, but (because it does not exist) it cannot link to it, as evident [here](https://pytorch.org/docs/stable/generated/torch.Tensor.permute.html).

cc @brianjo @mruberry

**Comment by Lezcano** [comment]
This has been fixed in [master](https://pytorch.org/docs/master/generated/torch.permute.html).

That being said, the docs are not well formatted, so I'll fix that.
