### ISSUE TITLE
How to support multi-arch in built Docker

### ISSUE THREAD

**Issue by DonggeunYu** [pytorch/pytorch#61836]
Hello?
I'm using pip3 to install and use PyTorch by writing my own Dockerfile.
Arch error when trying to use an image built on V100 on RTX3090.
I want to build an image that supports multiple Arches, such as V100, A100, RTX3090, and use it.
Any good way?

cc @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org/ to ask questions and issues to report incorrect behavior/propose a new feature.
And the answer can be found in `setup.py` comment: `TORCH_CUDA_ARCH_LIST` environment variable could be used to build for multiple architectures
https://github.com/pytorch/pytorch/blob/26d17ddc9f4f765ac07d550f296b0b35340a3a34/setup.py#L107-L111
