### ISSUE TITLE
usage of shared_cache in reductions.py

### ISSUE THREAD

**Issue by abhishek179** [pytorch/pytorch#61853]
## ❓ Questions and Help
Hi Pytorch Team,

i have a question on the usage of shared_cache storage in "torch/multiprocessing/reductions.py". 
specifically in the routine def rebuild_storage_fd(cls, df, size):

if i disable cache lookup "storage = storage_from_cache(cls, fd_id(fd))" in rebuild_storage_fd(cls, df, size). 
it will end up allocating new storage "cls._new_shared_fd(fd, size)" instead of reading from the cache.

will disabling the shared_cache lookup have any other side effect on training job & its outcome?
are there any other usage of the shared_cache lookup in rebuild_storage_fd(cls, df, size) apart from data loader scenario?

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by mrshenli** [comment]
Hey @abhishek179, please use [PyTorch Forum](https://discuss.pytorch.org/) for questions. I am closing this issue. If this turns out to be a feature request or bug report, please feel free to open another one. 

cc @vitaly-fedyunin for multiprocessing
