### ISSUE TITLE
Variable.type and Tensor.type have inconsistent behavior

### ISSUE THREAD

**Issue by robert-wagner** [pytorch/pytorch#6186]
When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: Pytorch
- OS: Ubuntu
- PyTorch version: 3.0cpu
- How you installed PyTorch (conda, pip, source): Pip
- Python version: 3.6
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): N/A
- CMake version: N/A
- Build command you used (if compiling from source): N/A
- Versions of any other relevant libraries:

The type method of the various tensor types does not have the same behavior. The type method for tensors returns the type of the tensor as a string when passed with no arguments and casts the tensor to the input type when it has an input. The type method for variables casts the data to a different type when passed an input but throws an error when there is no input. The behavior of these methods should be consistent

**Comment by zou3519** [comment]
This is fixed on the latest master because Tensors and Variables are now the same

**Comment by robert-wagner** [comment]
Awesome! Thanks. For reference which behavior does type take on the latest master?

**Comment by zou3519** [comment]
It should take the Variable path.
