### ISSUE TITLE
torch.save/load lost some attributes for quantized model

### ISSUE THREAD

**Issue by xin3he** [pytorch/pytorch#61881]
## 🐛 Bug

torch.save/load have a bug for quantized model. some attributes is lost and we cannot run it after loading.
The error wasn’t happened in save/load function, just in model.eval() , run model.

## To Reproduce
```
import torch
import torchvision.models.quantization as models

def save_and_load(M):
    torch.save(M, 'b.pt')
    M.qconfig = torch.quantization.get_default_qconfig('fbgemm')
    from torch.quantization import prepare, convert
    M = prepare(M)
    M = convert(M)
    print(M)
    torch.save(M, 'a.pt')
    a = torch.load('a.pt')
    a.eval()
    print(a)
    return

resnet18 = models.resnet18()
save_and_load(resnet18)
```
1. run above code, you will get following error message:

File ".../pytorch19/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv2d' object has no attribute '_modules'

## Expected behavior

fix it

## Environment

PyTorch1.9

cc @mruberry @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
Please check out https://pytorch.org/docs/master/quantization.html#saving-and-loading-quantized-models, for quantized models `torch.save/torch.load` is not supported, you can use the state dict instead.

**Comment by xin3he** [comment]
Thanks!

**Comment by ramkrishna1121** [comment]
@vkuzo will this support be added in the near future?

**Comment by vkuzo** [comment]
there are no plans to enable torch.load and torch.save for quantized models, we recommend that people use the state dict
