### ISSUE TITLE
There is no description about torch.optim._multi_tensor

### ISSUE THREAD

**Issue by shizao** [pytorch/pytorch#61884]
## 📚 Documentation

I'm wandering how to use torch.optim._multi_tensor, and what is the difference between the algorithms in folder torch.optim._multi_tensor and torch.optim ? 
The document has no description about that.
Any help would be appreciated.

cc @brianjo @mruberry @vincentqb @iramazanli

**Comment by shizao** [comment]
Any update?

**Comment by albanD** [comment]
Hi,

This is a work in progress feature and the leading `_` means that this is not ready to be public yet.
We will keep you updated when it is ready!
