### ISSUE TITLE
RESOLVED: Retire component-wise closeness tests for complex tensors

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#61906]
Closeness checks in our the test suite, i.e. `TestCase.assertEqual`, are performed component wise meaning closeness is computed for the real and imaginary components separately.

https://github.com/pytorch/pytorch/blob/39ce29efe05dc09fe9de6919715548476e4ab7b6/torch/testing/_core.py#L137-L164

The recently introduced `torch.testing.assert_close` inherited the behavior:

https://github.com/pytorch/pytorch/blob/39ce29efe05dc09fe9de6919715548476e4ab7b6/torch/testing/_asserts.py#L72-L88

The componentwise checking was introduced in #34258 but no public explanation was provided on the reason behind it.

Pros:

- Since `complex64` is comprised of two `float32`, we can reuse the testing tolerances. Of course the same is true for `complex128` and `complex32`.

Cons:

- `torch.testing.assert_close` and `torch.isclose` diverge for complex tensors:

    ```python
    >>> rtol, atol = 0.1, 0.3
    >>> expected = torch.tensor(1 + 1j)
    >>> actual1 = torch.tensor(1 + 1.43j)
    >>> torch.testing.assert_close(actual1, expected, rtol=rtol, atol=atol)
    AssertionError: Scalars are not close!
    >>> torch.isclose(actual1, expected, rtol=rtol, atol=atol)
    tensor(True)
    >>> actual2 = torch.tensor(0.6 + 1.3j)
    >>> torch.testing.assert_close(actual2, expected, rtol=rtol, atol=atol)
    >>> torch.isclose(actual2, expected, rtol=rtol, atol=atol)
    tensor(False)
    ```

    `torch.isclose` follows the implementation of `numpy` and partially `cmath` by comparing the absolute values of the difference of the two values. `torch.testing.assert_close` on the other hand compares the absolute values of the difference of the individual components. To be exact, `torch.isclose` as well as `numpy` evaluate the closeness inequality `abs(a - b) <= atol + rtol * abs(b)` the same way for complex as for real numbers. `torch.testing.assert_close` evaluates it twice for the real and imaginary component and checks the logical and of the results.
- The implementation is more messy and introduces more edgecases:

    - Is `complex(inf, 0)` close to `complex(inf, 1)`?
    - Is `complex(0, NaN)` close to `complex(NaN, 0)`?

    The second case led to `equal_nan="relaxed"` in `TestCase.assertEqual` which accepts these comparisons while they will be rejected for `equal_nan=True`. `torch.isclose` currently bails out for complex values and `equal_nan=True`

    https://github.com/pytorch/pytorch/blob/a26a9f8b75f4e8c9c7c34907a099b3a1d41f8a2c/aten/src/ATen/native/TensorCompare.cpp#L101-L102

## Regions of closeness

By checking the components individually we are forming a rectangle region of closeness around the expected value. Despite the divergence on the tolerance definition, `torch.isclose`, `numpy`, and `cmath` form a circle around the expected values. Thus is impossible to convert the old tolerances to achieve the same behavior if we go for this change.

## RFC

Since in most cases the specific values of the tolerances hardly matter, IMHO the cons severly outweigh the pros. Thus, the current plan is to retire the componentwise checking and merge the complex behavior of our internal and public testing functions with `torch.isclose` and in turn with `numpy`. If you disagree with that plan, please let us know in this issue.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @VitalyFedyunin @walterddr

**Comment by ezyang** [comment]
this sgtm

**Comment by pmeier** [comment]
Another argument to move in this direction is that the behavior of the testing functions for complex `NaN`s diverge from `torch.isnan`: While `torch.isnan` considers a complex value `NaN` if any component is `NaN` (this is in line with `cmath` and `numpy`), 

```python
torch.testing.assert_close(
    complex(float("nan"), 0), 
    complex(0, float("nan")), 
    equal_nan=True
)
```

would fail. To succeed `equal_nan="relaxed"` would need to be used.

**Comment by anjali411** [comment]
SGTM!
