### ISSUE TITLE
the outcome of autograd.Variable will converge？

### ISSUE THREAD

**Issue by wiyglm** [pytorch/pytorch#61900]
I use the function autograd.Variable to process data， but the outcome of differentiation always change each time. I wonder if the result is ordinary or not.Does anyone know the problem?Any help you provide is appreciated.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @malfet @seemethere @jerryzh168 @jianyuh @raghuramank100

**Comment by ejguan** [comment]
Hey,

We use github issues only for bugs or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
If it's a bug, can you please provide a minimum script for us to reproduce the issue?

**Comment by albanD** [comment]
Also `Variable` was removed a few years back. You should not be using it and you can just use plain Tensors for everything now.
