### ISSUE TITLE
DDP comm. hook:`torch.futures.Future.then()` callback returns singleton list

### ISSUE THREAD

**Issue by andwgu** [pytorch/pytorch#61914]
IIUC, the callback passed into `torch.future.then()` must return a list containing a single tensor corresponding to the contents of a bucket. Since `DistributedDataParallel` has retired single-process multiple-device (SPMD), we should flatten this to be the tensor itself rather than wrapping it in a list.

See [here](https://github.com/pytorch/pytorch/blob/a0c9d70fba659be0cce04b6d83d8aa427a57724c/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py#L63), [here](https://github.com/pytorch/pytorch/blob/a0c9d70fba659be0cce04b6d83d8aa427a57724c/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py#L96), and [here](https://github.com/pytorch/pytorch/blob/a0c9d70fba659be0cce04b6d83d8aa427a57724c/torch/distributed/algorithms/ddp_comm_hooks/quantization_hooks.py#L113) for examples.

cc: @SciPioneer 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by SciPioneer** [comment]
Thanks for the proposal! Indeed the return type of a singleton list is not ideal for many cases as we only have SPMD mode.

Once concern I have is that, a future can not only be returned by `allreduce`, but also by other communication primitives such as `allgather`, which naturally returns a list of output tensors. How are you going to handle this case by `then()` if it can only return a single tensor?

**Comment by andwgu** [comment]
I see. In that case, preserving the current way of returning a `list` makes sense. I wonder, when bandwidth permits, if we could explain this expected return behavior in the PyTorch docs. When I was reading about DDP comm. hook and futures, I did not find anything specifying this expectation the callback passed into `then()` to return a `list` and only saw in the implemented hooks.

I looked at:
https://pytorch.org/docs/stable/ddp_comm_hooks.html
https://pytorch.org/docs/stable/futures.html

**Comment by SciPioneer** [comment]
> I see. In that case, preserving the current way of returning a `list` makes sense. I wonder, when bandwidth permits, if we could explain this expected return behavior in the PyTorch docs. When I was reading about DDP comm. hook and futures, I did not find anything specifying this expectation the callback passed into `then()` to return a `list` and only saw in the implemented hooks.
> 
> I looked at:
> https://pytorch.org/docs/stable/ddp_comm_hooks.html
> https://pytorch.org/docs/stable/futures.html


Agree that the documentation is not that clear.

It will still be great to update DDP comm hook API to only accept a single tensor though.
