### ISSUE TITLE
WinError 127 Error loading D:\Python\Python37\Lib\site-packages\torch\lib\caffe2.dll or one of its dependencies.

### ISSUE THREAD

**Issue by ccyccxcl** [pytorch/pytorch#61947]
## ❓ when I tried to impotr torch,it always occured _"WinError 127 Error loading D:\Python\Python37\Lib\site-packages\torch\lib\caffe2.dll or one of its dependencies."_

some informations:
     C:\Users\Administrator>nvcc -V
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2020 NVIDIA Corporation
     Built on Tue_Sep_15_19:12:04_Pacific_Daylight_Time_2020
     Cuda compilation tools, release 11.1, V11.1.74
     Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0

    
![image](https://user-images.githubusercontent.com/24389529/126463738-038c4405-44cd-440a-ac9a-0ab0be91cd62.png)

and I installed :torch-1.9.0+cu111-cp37-cp37m-win_amd64.whl   &  torchvision-0.9.1+cu111-cp37-cp37m-win_amd64.whl
 Any help?

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mszhanyi** [comment]
Does D:\Python\Python37\Lib\site-packages\torch\lib\caffe2.dll exist?
if not, please try reinstall the wheel.
if yes, could you please use https://www.dependencywalker.com/ or https://github.com/lucasg/Dependencies to check which dlls are missing.

**Comment by peterjc123** [comment]
Since you are from China, I recommend you to read the related post in my blog. https://blog.peterjc.stream/2020-04-21-python-dll-load-failure-windows/

**Comment by vladimir-aubrecht** [comment]
Closing the issue as issue seems stale, I couldn't reproduce it with latest stack and seems like environment problem. Please feel free to create new issue if problem still persist.
