### ISSUE TITLE
torch.linalg.svd out of memory

### ISSUE THREAD

**Issue by KKIverson** [pytorch/pytorch#61949]
When I run the following code: 

**print(m.shape)
pcs = torch.linalg.svd(m, full_matrices=False)[0]**

---------------output-------------
torch.Size([3, 1048576])
RuntimeError: CUDA out of memory. Tried to allocate 4096.00 GiB (GPU 0; 23.70 GiB total capacity; 24.00 MiB already allocated; 22.06 GiB free; 34.00 MiB reserved in total by PyTorch)

But the same verion in numpy works well:

**print(m.shape)
n = m.cpu().numpy();
pcs = np.linalg.svd(n, full_matrices=False)[0]
print(pcs)**

--------------output--------------
torch.Size([3, 1048576])
[[-0.6821615   0.73033303 -0.03562753]
 [-0.6553572  -0.632287   -0.41318282]
 [-0.32428792 -0.25850865  0.9099509 ]]

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by albanD** [comment]
Hi,

I think the reason is that the matrix is too big and so you run out of memory here.
Does running the same code on cpu with pytorch works?

**Comment by malfet** [comment]
Hmm, for 3x1048576 matrix, V matrix size would be 1048576x1048576, i.e. `2**40`, that is 4096Gb of memory, which is more than what is available on any GPU, isn't it?

**Comment by ngimel** [comment]
Yep, even though `full_matrices=False` is requested, pytorch still unconditionally allocates VT as  1048576*1048576 in LinearAlgebraUtils.h, even though just a few columns from it will be subsequently used by the cusolver call. Cusolver call correctly sets econ=1 in this case.  cc @xwang233

**Comment by IvanYashchuk** [comment]
The code in LinearAlgebraUtils.h for svd is wrong it incorrectly initializes large matrix and then narrows it if full_matrices=False. The whole svd code was not refactored during recent linalg updates, only linalg_svd wrapper of the old code was added.

**Comment by xwang233** [comment]
Thanks for the report. Yes, the `_create_U_S_VT` function always allocates a full square matrix for VT. We definitely need a refactor for this code. 

Also, we may consider adding another SVD path of cusolver gesvda ([doc link](https://docs.nvidia.com/cuda/cusolver/index.html#cuSolverDN-lt-t-gt-gesvda)), which is specially optimized for tall skinny matrix. A heuristic and transpose would be needed.

**Comment by KKIverson** [comment]
> The code in LinearAlgebraUtils.h for svd is wrong it incorrectly initializes large matrix and then narrows it if full_matrices=False. The whole svd code was not refactored during recent linalg updates, only linalg_svd wrapper of the old code was added.

Thank you, and how can I use the right version of svd in pytorch?

**Comment by IvanYashchuk** [comment]
> > The code in LinearAlgebraUtils.h for svd is wrong it incorrectly initializes large matrix and then narrows it if full_matrices=False. The whole svd code was not refactored during recent linalg updates, only linalg_svd wrapper of the old code was added.
> 
> Thank you, and how can I use the right version of svd in pytorch?

You will be able to use `torch.svd`, `torch.linalg.svd` and `torch.linalg.svdvals` with the input you provided after https://github.com/pytorch/pytorch/pull/62022 is merged.
