### ISSUE TITLE
Delete unrelated Windows test results from S3 bucket

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#61978]
Because Windows runners were re-used across the workflows, which obscured bug when `TEST_CONFIG` was not set and end up uploading data from the previous runs, as could be seen in 
https://github.com/pytorch/pytorch/runs/3119377276

TODO:
- [ ] Remove this data from S3 bucket
- [ ] Preserve host name, commit hash and/or test time in those reports (unless we do it already)

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
commit_hash + workflow_id seems to be a good unique ID for this?
