### ISSUE TITLE
Fix integral tensor division 

### ISSUE THREAD

**Issue by li-roy** [pytorch/pytorch#6197]
Example below. While we don't support ops between different dtype tensors, we should consider changing this behavior. In numpy, this would return a floating tensor.

```
>>> import torch
>>> a = torch.tensor([1,2,3], dtype=torch.long)
>>> b = torch.tensor([3,2,1], dtype=torch.long)
>>> a/b

 0
 1
 3
[torch.LongTensor of size (3,)]
```

**Comment by SsnL** [comment]
I'm curious. Given that this is the case, how does one do integer division in numpy?

**Comment by goldsborough** [comment]
With `//`

**Comment by li-roy** [comment]
@mdraw Oh oops. We can close this one.
