### ISSUE TITLE
https://pytorch.org/docs/master/__config__.html is a "dead end"

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#62018]
This link appears in the left hand navigation pain as torch.__config__, but clicking it leads to a "dead end." Either the link should be removed or made valid.

cc @brianjo @mruberry

**Comment by brianjo** [comment]
Thanks. This is an issue with the way github pages handles underscore/double underscore leading files. I've tried to fix 1.9 and stable by hand, but that doesn't seem to be working. @mattip Do you have any ideas for a long term fix? (I would vote to remove it from the left nav if it's not needed.)
