### ISSUE TITLE
Support for opset 15 for pytorch model -> onnx model

### ISSUE THREAD

**Issue by leoozy** [pytorch/pytorch#62023]
## 🚀 Feature
Hello, the latest onnx version is 1.9.0 and the 1.10.0 will be released soon. The lated onnx opset version is opset 15. But currently pytorch only supports opset 13.

## Additional context

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment]
@leoozy Thanks for reaching out. We will support it.
