### ISSUE TITLE
Please verify ONNX v1.10.0 Release Candidate

### ISSUE THREAD

**Issue by rajeevsrao** [pytorch/pytorch#62039]
Hello ONNX partner,
We have published (to TestPyPI) a Release Candidate package for the upcoming ONNX v1.10.0 release. Please help validate it and let us know if you encounter any issues. Note that the tentative release date for ONNX v1.10.0 is July 31, 2021. Thank you for your assistance!

```
pip install numpy protobuf typing-extensions>=3.6.2.1
pip install -i https://test.pypi.org/simple/ onnx==1.9.101
```

* 07/26/2021: RC2 with `make_sequence_value_info` alias - [onnx 1.9.101](https://test.pypi.org/project/onnx/1.9.101/) - commit [5d9ba9b](https://github.com/onnx/onnx/tree/5d9ba9b6db8f35a15654b169928e6dacd95d83be)
* 07/21/2021: RC1 for validation - [onnx 1.9.100](https://test.pypi.org/project/onnx/1.9.100/) - commit [691fcf2](https://github.com/onnx/onnx/commit/691fcf21205af164f17f727a852667dae35ce3a8)

cc  @BowenBao @faxu @garymm @neginraoof

**Comment by jspisak** [comment]
@malfet

**Comment by garymm** [comment]
@rajeevsrao how did you get the list of people to CC?
I'd like to update the list.

**Comment by rajeevsrao** [comment]
> @rajeevsrao how did you get the list of people to CC?
> I'd like to update the list.

@garymm I got it from the PR for previous onnx release [here](https://github.com/pytorch/pytorch/issues/55605) and frequent contributors. Please let me know what the cc list should be and I will update.

**Comment by garymm** [comment]
I suggest:
@BowenBao @faxu @garymm @neginraoof

Also I believe PyTorch consumes onnx from source, not from the packages, so in the future if you could provide commit IDs for testing that would be helpful.

**Comment by rajeevsrao** [comment]
> I suggest @BowenBao @faxu @garymm @neginraoof
Thanks, updated.

> if you could provide commit IDs for testing that would be helpful
Updated in the PR description.

**Comment by rajeevsrao** [comment]
@BowenBao @faxu @garymm @neginraoof did you get a chance to test RC2? Please let us know at the earliest since we are planning a release end of this week?

**Comment by rajeevsrao** [comment]
@garymm @faxu do you think we can get the validation results by tomorrow, or would postponing the release to Monday help? Thanks.

**Comment by garymm** [comment]
It seems testing this in PyTorch CI is going to take a while, so I'm testing locally.
I should have results tomorrow.

One issue I've found is this seems to introduce new compilation warnings into the PyTorch build, which I'm fixing: https://github.com/onnx/onnx/pull/3616. That doesn't need to block the release, but it'd be nice to get it merged soon.

**Comment by garymm** [comment]
Tests passed locally with onnx submodule at a57bc99daa6ddeef2ad535f8f78d1847f57216f0, which I guess is two commits behind RC2, but the 2 missing commits seem not problematic.
I ran:
`python test/onnx/test_pytorch_onnx_onnxruntime.py`
