### ISSUE TITLE
[FR] Support for non-Parameter, non-Buffer objects in state_dict

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#62094]
## 🚀 Feature
Support adding arbitrary things to a module's `state_dict`. Currently, serialization of a module is tied to what is stored in its `state_dict`, and there is no public API for storing arbitrary things in the `state_dict`. This limits control over what is serialized.

### Use Cases
1. Serialize arbitrary objects within a module (flags, integers, etc.)
    * See #51471
2. Define "buffers" that are serialized but don't take part in device moves / floating pointing dtype conversions (e.g. `to()`, `cuda()`, etc.)
    * No current way to do this; serialization can be turned off for buffers by marking them as non-persistent, but they cannot be left out of device moves / floating point dtype conversions
    * Equivalent to allowing non-Parameter, non-buffer Tensors in `state_dict`
3. Support custom Tensor types within modules (e.g. `DiagTensor`, `ShardedTensor`, etc.)
    * Part of the solution is to allow custom Tensor types to be serialized
    * Full solution would allow custom Tensor types to act as Parameters for use in optimization (likely a separate discussion)

### Possible solutions
One possible solution is to add `state_dict` hooks to the public API. Currently we have `_register_state_dict_hook()` / `_register_load_state_dict_pre_hook()`, which are limited since they do not receive the module instance itself. More direct mechanisms should be considered as well.

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment]
Here's some possible approaches for adding this support:

**Approach 1: Make private hook API public**
`_register_state_dict_hook()` and `_register_load_state_dict_pre_hook()` become public. Hooks have interface:
* `state_dict_hook(module, state_dict, prefix, local_metadata)`
* `load_state_dict_pre_hook(module, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)`

Pros: Minimal API changes, flexible enough
Cons: Not great UX. Hooks are not serialized; if a module with extra state is serialized, a pre-hook always has to be registered on a module instance before calling `load_state_dict()` to load the extra state correctly

**Approach 2: Maintain a static list of objects to include within the state_dict**
Add e.g. an `_extra_state_dict_items` dict in the vein of `_parameters` / `_buffers`, with a `register_in_state_dict(item)` API to add to it.

Pros: Simple and consistent with `register_parameter()` / `register_buffer()`
Cons: Rigid; doesn't allow for dynamically-generated `state_dict` additions

**Approach 3: Define overridable methods for handling extra state**
Add functions to `nn.Module` that can be implemented for custom modules. Following the hook interface above:
* `save_extra_state(self, state_dict, prefix, local_metadata)` 
* `load_extra_state(self, state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)`

Pros: Allows for dynamically-generated `state_dict` additions, defined per module class rather than per module instance
Cons: Not great UX having to handle all the loading and prefix logic manually

For a cleaner UX, maybe something like:

* `extra_state(local_metadata) -> OrderedDict`
* `load_extra_state(extra_state, local_metadata)`

One interesting thing to figure out is the interplay with `strict=True` passed to `load_state_dict()`. I guess the user needs to indicate somehow which keys were handled by `load_extra_state()`. I think this approach has the most promise, but needs a little bit more work to get right.

**Comment by albanD** [comment]
> Cons: Not great UX having to handle all the loading and prefix logic manually

If I understand correctly that the idea here is not to modify existing content of the state dict (which the `_register_state_dict_hook` were for) but add/load arbitrary data into it.
I think we can use something similar to what python serialization does where the user provides a pair of functions `getstate(self)/setstate(self, state)` and we take care of saving this into the state dict under a special key like "this.is.the.prefix.user_state"?

**Comment by jbschlosser** [comment]
> I think we can use something similar to what python serialization does where the user provides a pair of functions getstate(self)/setstate(self, state) and we take care of saving this into the state dict under a special key like "this.is.the.prefix.user_state"?

I like the idea of storing the state under a special key & just skipping this key for the strict check. For consistency with `__getstate__(self)` / `__setstate__(self, state)`, how about:
* `get_extra_state(self) -> dict or OrderedDict`
* `set_extra_state(self, state)`

`user_state` would work too; I chose the name `extra_state` along the lines of `Module.extra_repr()`.

Would `local_metadata` be useful to provide or can that be left out?

**Comment by albanD** [comment]
I don't know what `local_metadata` contains to be honest :D

> just skipping this key for the strict check.

Actually in the strict case, if the user implements `set_extra_state` then there must be a `user_state` entry in the state dict. Otherwise we report it.
Similarly, if that function is not overwritten by the user, and there is a `user_state` in the state dict for that Module, we report it.

**Comment by pritamdamania87** [comment]
> get_extra_state(self) -> dict or OrderedDict
> set_extra_state(self, state)

From a ShardedTensor perspective, I'm assuming `get_extra_state` could return something like `Dict[str, ShardedTensor]`. Then `set_extra_state` would receive this same state and then the user needs to manually apply this state to the parameters of the nn.Module? Wouldn't the user also have to recurse through submodules and add the ShardedTensors there too?

If so, I feel option 2 might be much simpler from a UX perspective, where users just call `register_in_state_dict` and we take care of the rest. Are there some examples of dynamically created entries where this won't work?

**Comment by jbschlosser** [comment]
> From a ShardedTensor perspective, I'm assuming `get_extra_state` could return something like `Dict[str, ShardedTensor]`. Then `set_extra_state` would receive this same state and then the user needs to manually apply this state to the parameters of the nn.Module? Wouldn't the user also have to recurse through submodules and add the ShardedTensors there too?

Good question - in the linked draft PR, the recursion is handled automatically within the base `nn.Module`. Each module's `get_extra_state()` / `set_extra_state()` implementations only take care of the module's immediate extra state (see tests in linked PR for an example with submodules).

That said, since extra state is defined as methods on the module class (i.e. at the module class level), there's no way to store different extra state in different instances of the same module. It seems this limitation is too restrictive for nice use with ShardedTensor, since sharding is done on a module instance. Thus, we need a way to define extra state at the module instance level (which option 2 gives us)- is that correct? @pritamdamania87

**Comment by pritamdamania87** [comment]
> That said, since extra state is defined as methods on the module class (i.e. at the module class level), there's no way to store different extra state in different instances of the same module. It seems this limitation is too restrictive for nice use with ShardedTensor, since sharding is done on a module instance. Thus, we need a way to define extra state at the module instance level (which option 2 gives us)- is that correct? @pritamdamania87

I don't think this is an issue since the ShardedTensor would be part of the module itself. I think an example would be something like this which would work:

```
def MyShardedModule(torch.nn.Module):

  def __init__(self):
      self.foo = torch.nn.Parameter(torch.rand(10))
      self.bar = ShardedTensor(....)
     
  def get_extra_state():
     return {'bar': self.bar}
```

**Comment by pritamdamania87** [comment]
@albanD I think you should look through this test case: https://github.com/pytorch/pytorch/blob/master/test/distributed/_sharded_tensor/test_sharded_tensor.py#L963 (test_state_dict). We previously used `_register_state_dict_hook` and `_register_load_state_dict_pre_hook` to achieve our goal of adding ShardedTensor to state_dict.

The hope was the API proposed here would be simpler than that and users don't need to register such hooks. However, the API here is actually more involved (since you need to add these methods to each submodule) and we would rather use the hooks compared to this.

> In your case, it seems that what you want is Tensor centric: you want that any Module with that Tensor does extra logic.

Yes, this is our use case and the hope was that we could have a simple API at the nn.Module level to enable this.

**Comment by jbschlosser** [comment]
@pritamdamania87 An alternative approach to a Tensor-centric API for adding `ShardedTensor` into module `state_dict`s would be to have proper support for custom tensors as buffers, as Alban alluded to above. The example you linked above would change slightly:
```python
class MyShardedModel2(torch.nn.Module):
    def __init__(self, spec=None, group=None):
        super(MyShardedModel2, self).__init__()
        self.register_buffer('sharded_tensor2', None if spec is None else
                             _sharded_tensor.empty(spec, 10, 20, process_group=group, init_rrefs=True))
        self.random_tensor2 = torch.nn.Parameter(torch.rand(2, 2))

class MyShardedModel1(torch.nn.Module):
    def __init__(self, spec=None, group=None):
        super(MyShardedModel1, self).__init__()
        self.register_buffer('sharded_tensor1', None if spec is None else
                             _sharded_tensor.empty(spec, 10, 20, process_group=group, init_rrefs=True))
        self.random_tensor1 = torch.nn.Parameter(torch.rand(2, 2))
        self.submodule = MyShardedModel2(spec, group)
```

These buffers would be included in the `state_dict` so you wouldn't need any additional hooks or per-module-class tweaks. Does this seem okay to you or is it too restrictive? AFAICT there's just a couple minor tweaks needed in the Module code to get this support.

**Comment by HanatoK** [comment]
@jbschlosser 
I like the feature, but I don't think that calling `get_extra_state` in the base class (`torch.nn.Module`) should raise a `RuntimeError`. Returning `None` or throwing other meaningful exception is a better choice.
The reason is that if I have two classes `A` and `B`, and `A` is derived from `torch.nn.Module` while B is derived from `A`. In this case, I would call the parent method of `get_extra_state` in `B`'s implementation of `get_extra_state` to update the extra state of the parent class at first, and then update the extra state of B itself. That being said, the following code should be more consistent and reusable for both `A` and `B` if `get_extra_state` in `torch.nn.Module` return `None`:
```python3
def get_extra_state():
    state = super(self).get_extra_state()
    if state is not None:
        if isinstance(state, dict):
             state.update({'foo': self.foo})
    return state
```

**Comment by jbschlosser** [comment]
Hey @HanatoK, thanks for bringing this up! I'd be happy with the base behavior changing to return `None` instead of throwing an error, along with the relevant doc and testing changes. If you'd like to contribute, please free to open a PR with the changes and I can review it :)
