### ISSUE TITLE
yolo5 convert to onnx failed.

### ISSUE THREAD

**Issue by ccl-private** [pytorch/pytorch#62090]
## To Reproduce

1.https://github.com/ultralytics/yolov5/issues/2153
2.windows pc failed, but ubuntu pc succeed.

## Expected behavior

convert PyTorch yolo5 model to onnx.

## Environment

 - PyTorch Version (e.g., 1.0):1.9.0
 - OS (e.g., Linux):windows10
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.8
 - CUDA/cuDNN version:11.0
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @BowenBao @neginraoof @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ccl-private** [comment]
@skyline75489 @jbschlosser how is it going?

**Comment by jspisak** [comment]
@garymm

**Comment by garymm** [comment]
Hi @jspisak I'm in the process of putting a GH triage and resolution process in place. Please don't mention or assign onnx issues. As long as they have the `module: onnx` label, my team will work to address them.

**Comment by jspisak** [comment]
> Hi @jspisak I'm in the process of putting a GH triage and resolution process in place. Please don't mention or assign onnx issues. As long as they have the `module: onnx` label, my team will work to address them.

Will do. thanks for supporting @garymm

**Comment by jiafatom** [comment]
@ccl-private pytorch-onnx exporter does not support exporting in Windows. Is it ok you convert the model in Linux?

**Comment by ccl-private** [comment]
Linux is ok. @jiafatom

**Comment by jiafatom** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1322241

**Comment by BowenBao** [comment]
This issue should be resolved after https://github.com/onnx/onnx/pull/3644 is merged into onnx.

**Comment by BowenBao** [comment]
Closing. Feel free to comment or reopen if this issue is not resolved by above workarounds and solutions.
