### ISSUE TITLE
Decouple functional/zero optimizer from RPC Distributed Optimizers

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#62137]
## 🚀 Feature
Currently when attempting to import functional optimizers or Zero Redundancy Optimizer, we implicitly need to import RRef, which requires torch.distributed.rpc package, see:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/optim/__init__.py#L8
which calls into
https://github.com/pytorch/pytorch/blob/master/torch/distributed/optim/optimizer.py#L9, which tries to import RRef. This causes test failures in Windows at import time even though these tests would not be run under Windows e.g. if they require NCCL backend.

Current workaround is to gate the import base on IS_WINDOWS, see for example https://github.com/pytorch/pytorch/pull/61678/files#diff-9f639571a250cffbe9cded7d2fbb5ad6311e4be9c0c7610e5ba85930806e7f38R51

Although functional optimizers are not distributed in nature at all, and Zero should work with DDP running with Gloo on windows, so we should actually support and enable tests for these. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by SciPioneer** [comment]
One more DP: this design also blocks local SGD optimizer. Basically any new distributed optimizer that needs to work with DDP will be blocked by this bug.

**Comment by mrshenli** [comment]
@wanchaol any reason functional optimizer lives in the `distributed/optim` folder. Those optimizers all seem local. Is it just because they are mainly used by distributed applications/algorithms?

**Comment by wanchaol** [comment]
> @wanchaol any reason functional optimizer lives in the `distributed/optim` folder. Those optimizers all seem local. Is it just because they are mainly used by distributed applications/algorithms?

Yeah they are mainly used by distributed applications. But I think this is not because of those functional optimizers. This is because `distributed/optim/optimizer.py`, which initializes the `DistributedOptimizer` and it creates RRefs to all the local optimizers inside, that's why they are depending on RPC, and Zero does not support RPC. This location of this is not a bug, but the bug of windows not supporting RPC might be a issue, I don't know how much effort it involves on fixing that, if that takes long, we can think about decoupling `distributed/optim/optimizer.py` and `ZeroOptimizer`

**Comment by mrshenli** [comment]
> But I think this is not because of those functional optimizers. This is because distributed/optim/optimizer.py, which initializes the DistributedOptimizer and it creates RRefs to all the local optimizers inside, that's why they are depending on RPC, and Zero does not support RPC. This location of this is not a bug, but the bug of windows not supporting RPC might be a issue, I don't know how much effort it involves on fixing that, if that takes long, we can think about decoupling distributed/optim/optimizer.py and ZeroOptimizer

I might miss sth. It doesn't seem moving `ZeroRedundancyOptimizer` out of `distributed/optim` gonna solve the problem. If I am going to add one new distributed optimizer that depends on functional optimizers, my new optimizer cannot be imported on Windows regardless of whether `ZeroRedundancyOptimizer` is in `distributed/optim` or not. 

I agree that the problem is `distributed/optim/optimizer.py`. To make `distributed/optim` work on Windows, does it make sense if we conditionally import `DistributedOptimizer` based on the availability of RPC?

**Comment by rohan-varma** [comment]
@mrshenli I think `DistributedOptimizer` is only meant to be used with RPC, so making it work with windows will require enabling RPC for windows which is a larger project? i.e. 

> If I am going to add one new distributed optimizer that depends on functional optimizers, my new optimizer cannot be imported on Windows regardless of whether ZeroRedundancyOptimizer is in distributed/optim or not.

A prerequisite is windows support for RPC IIUC.

Regarding `ZeroRedundancy`, a quick way to enable it for windows is to just move it to a separate namespace, to remove the dependency on RPC?

**Comment by mrshenli** [comment]
Hey @rohan-varma, thanks for the explanation. I am still a little puzzled. Will something like below be sufficient?

```python
if torch._C._rpc_init():
    from .optimizer import DistributedOptimizer

from .post_localSGD_optimizer import PostLocalSGDOptimizer
from .zero_redundancy_optimizer import ZeroRedundancyOptimizer
```


> A prerequisite is windows support for RPC IIUC.

Why this is a prerequisite? I assume we can add non-RPC optimizers to the `distributed/optim` package like ZeRO?

**Comment by rohan-varma** [comment]
@mrshenli Sorry I think I misunderstood, when you said 
> distributed optimizer that depends on functional optimizers

I thought this meant RPC's `DistributedOptimizer` but I think you meant any general one like zero. I think I'll try out the `torch._C._rpc_init()` suggestion and see if that is sufficient to fix things.

**Comment by rohan-varma** [comment]
@mrshenli looks like we cannot directly call `torch._C._rpc_init()`, as we run into the following when running rpc tests:

```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0804 15:16:22.061866 78922 ExceptionTracer.cpp:185] Invalid trace stack for exception of type: std::runtime_error
terminate called after throwing an instance of 'std::runtime_error'
  what():  generic_type: cannot initialize type "RpcBackendOptions": an object with that name is already defined
```

**Comment by rohan-varma** [comment]
done by #62774
