### ISSUE TITLE
Migrate test status/time statistics to Rockset

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#62136]
## 🚀 Feature

It would be nice to have OSS queryable CI metrics. To do this, the following steps should be taken:
- [x] Make sure we are collecting test stats for the workflows that run our Python test suite (ROCm, MacOS, Win, Linux)
- [x] Route test stats to Rockset (directly, not using S3 as S3 doesn't support batching objects)
- [x] Rewrite sharding code/slow test code to use Rockset stats
- [ ] Retire S3 ossci-metrics/test-times 
  
## Motivation

Currently, we store OSS CI metrics (test case times and statuses) in S3 in the format of JSON that is grouped by
commits -> CI jobs -> test modules -> test suites -> test cases. For example, for commit ae87fc2760cdbea3bcff91, there would be a folder of CI jobs. Per CI job, there would be a JSON that looks somewhat like:
```
{ <metadata> ...
  test_total_time: 78239,
  test_files: 
  { test_filename: TestModuleA,
    test_suites: 
    { test_suitename: TestSuiteB,
      test_cases: { <lots of test cases> }
    }, ...
  }, ...
}
```
This has been convenient for several of our tasks so far, such as in automating sharding and slow test categorization. However, this format is not directly queryable with SQL and processing lots of this data on a local machine would take hours, if not days.

Now we also maintain the same data in a more queryable format internally, on FB servers. The downside is that we cannot easily access that data with external, public processes, making automating anything we'd want to do with OSS PyTorch difficult and manual. For example, in order to gather up Windows smoke tests, we run an internal query to compare test stats between different platforms across many commits. We would have to regularly manually update this set of tests as we cannot access these stats through a public cronjob of sorts. (This is just a sample use case, as the future of Windows smoke tests is currently unclear.)

If these metrics were stored publicly somewhere and were directly queryable through SQL, they could be useful for several reasons such as:
* enabling more OSS automation within our CI that would require bigger amounts of data
* creating external dashboards that would enlighten external contributors about our CI

## Pitch

To make this happen, we would host this queryable data somewhere externally.
1. Start reporting to a third channel (maybe a in addition to internal Scribe and OSS S3. The third channel could be somewhere on AWS or any other external storage option--this is up for discussion as I don't claim familiarity with what would be best here.
2. Write a lambda/external cronjob that would convert our current OSS stats to a queryable format. This may be easiest if we hosted the converted data somewhere in AWS.

## Alternatives

I have considered that maybe my knowledge in data processing is not deep and that it may be possible to:
1. Use SQL on our current OSS JSON data. If this is the case, it may be easiest to just figure out how this would work and do extra parsing versus hosting a completely different set of data.
2. Somehow access our internal stats externally and automatically. I doubt this is the case, though, because of security risks.
3. Please suggest any other ideas that would allow us to query OSS metrics externally in a quick and automatic manner!

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by driazati** [comment]
The metrics in S3 are currently broken down per workflow (so it includes everything from both PRs and `master` runs as well as re-runs), but for stats on tests we only care about statistics from the last run on master, right?

Site note: something like [this](https://phiresky.github.io/blog/2021/hosting-sqlite-databases-on-github-pages/) could be cool (querying statically hosted sqlite databases), though it's just someone's side project so I don't know if it is really "production ready." A quick estimate of (40,000 tests + 100 B of data per test (name, time, conclusion)) puts us at ~ 10 MB for test data, which is not totally intractable to download each time we need it (so we wouldn't need that blog posts tool). The main advantage of sqlite-ing the data would be that we can still keep it in S3, but it's all globbed together into a single, queryable binary and we don't need to maintain any kind of DB server.

**Comment by walterddr** [comment]
i guess it is first partitioned by commit id then by workflow id. so you can distinguish between PR jobs and master jobs by looking at the commit ID

**Comment by janeyx99** [comment]
> The metrics in S3 are currently broken down per workflow (so it includes everything from both PRs and `master` runs as well as re-runs), but for stats on tests we only care about statistics from the last run on master, right?

We would like both PR and master stats for data processing, but not necessarily to display yet. The reason is because PR stats are really useful for detecting the signals that developers are caring about and fixing.

**Comment by janeyx99** [comment]
Now that we have Rockset, we should report test stats to Rockset and these claims would be satisfied.

**Comment by janeyx99** [comment]
@suo completed most of this work--closing
