### ISSUE TITLE
[feature request] torch.aminmax

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#62161]
Often min and max are computed together (e.g. for min-max normalization). It may be convenient to have a special idiomatic method for this (similar to torch.std_mean, torch.var_mean). At least, for version that doesn't return the index, it may be a reasonably convenient API

it exists in opencv as `cv2.minMaxLoc`

**Comment by ngimel** [comment]
Duplicate of #62164, functionality exists already as torch._aminmax

**Comment by vadimkantorov** [comment]
@ngimel I don't mind you closing this one, but i would claim that it's #62164 that's duplicate of this earlier one #62161 ^^

**Comment by vadimkantorov** [comment]
So the proposal is then to make torch._aminmax public and supported

**Comment by ngimel** [comment]
> @ngimel I don't mind you closing this one, but i would claim that it's #62164 that's duplicate of this earlier one #62161 ^^

True, but #62164 already mentions that the requested functionality exists, so it's a more accurate request of making it public API.
