### ISSUE TITLE
Concurrent minmax reduction operator

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#62164]
## 🚀 Feature
Provide a torch.minmax reduction operator that concurrently computes both the min and the max of the inputs.

## Motivation

torch.min and torch.max often occur in pairs in pytorch code.  It is desirable to have a concurrent min and max computation for efficiency.

## Pitch

 It is desirable to have a concurrent min and max computation for efficiency.  This operator already exists internally as torch._aminmax and the proposal is to make this a public API

## Alternatives

Build an FX optimizer (and/or a TorchScript JIT optimizer) that recognizes calls to torch.min and torch.max and replaces them with the optimized function.

## Additional context

Computing min and max is often used together, e.g., in computing quantization parameters.

cc @VitalyFedyunin @ngimel @heitorschueroff

**Comment by vadimkantorov** [comment]
Haha, I also just filed this: https://github.com/pytorch/pytorch/issues/62161

**Comment by vadimkantorov** [comment]
Duplicating my comment here about torch._aminmax return value format:

```maybe also the return value format to be discussed - should it be a single tensor, if yes, where should be the dimension 2 (corresponding to min and max - if it's the made the first one, then it would unbind automatically), or should it only be a tuple without)```

**Comment by jbschlosser** [comment]
After some internal discussion, we agree that `torch._aminmax` should be brought into the public API. Most likely we want to maintain its current API (return 2 tensors) since it's in use already in a few places in the code, including the quantization logic.
