### ISSUE TITLE
Out of GPU Memory After Training

### ISSUE THREAD

**Issue by congvmit** [pytorch/pytorch#62173]
## ❓ Questions and Help

After training my own model, I cannot train anymore because of strange out-of-memory error even my GPU still has available memory.

This is sample code and error status.
![image](https://user-images.githubusercontent.com/43516400/126925663-cbac36ef-cb4e-4d0a-a2ce-d9e31c76bd6b.png)

This is my current GPU status on my PC.
![image](https://user-images.githubusercontent.com/43516400/126925824-4989e6fe-e5d9-4a4f-99e0-0e0e406f5744.png)

I have no idea why this happens. To keep on training, I have to restart my PC. But this problem still occurs several times after training. 
Please help me.

**Comment by mruberry** [comment]
Trying asking for help by posting in the forums: https://discuss.pytorch.org/.

I think you'll need to provide more information about what, exactly, you're doing, however.
