### ISSUE TITLE
propagate output names to gradient inputs to backward functions in derivatives.yaml

### ISSUE THREAD

**Issue by dagitses** [pytorch/pytorch#62196]
## 🚀 Feature
In derivatives.yaml, when defining a backward implementation for a native function that returns multiple named outputs (e.g. `func: attn(Tensor q, Tensor k, Tensor v) -> (Tensor output, Tensor attn)`), provide named gradients for each output, i.e. `grad_output` and `grad_attn` as aliases for `grads[0]` and `grads[1]` respectively.

## Motivation

The motivation for this would be consistency with how derivatives.yaml provides named aliases to use instead of `resultX`. Also will allow for more readable implementations than references to `grads[X]`.

## Pitch

Modify codegen for derivatives.yaml to allow `grad_OUTPUT_NAME` in addition to `grads[X]` for each named output. Update documentation to make it clear that this is an alternative for such functions.

## Alternatives

The obvious alternative is to do nothing. This provides no new expressive power.

More opinionated alternatives would be to remove `grads[X]` for such cases. I lack context, but I think that would be a good idea and would go further to ensure that `resultX` is also removed for such cases.

## Additional context

n/a

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by ezyang** [comment]
SGTM
