### ISSUE TITLE
When an nn's member point to a submodule's submodule, it's state_dict value appears multiple times

### ISSUE THREAD

**Issue by HuadingLing** [pytorch/pytorch#62236]
## 🐛 Bug

When define a nn module, and let its member point to a submodule's submodule, then this submodule's weight(s) will appears twice in the model's state_dict. Although there are from the same object (same id).

## To Reproduce

Run the following code:

```
import torch
from torch import nn

class subsubmodule(nn.Module):
    def __init__(self, input_size, output_size):
        super(subsubmodule, self).__init__()
        self.emb = nn.Embedding(input_size, output_size)
        
    def forward(self, x):
        pass
    
class submodule(nn.Module):
    def __init__(self, input_size, output_size):
        super(submodule, self).__init__()
        self.emb = subsubmodule(input_size, output_size)
        
    def forward(self, x):
        pass
    
class model(nn.Module):
    def __init__(self, input_size, output_size):
        super(model, self).__init__()
        self.encode = submodule(input_size, output_size)
        self.emb = self.encode.emb.emb  # I want to use a shortcut in some case
        
    def forward(self, x):
        pass
    
if __name__ == "__main__":
    a = model(100, 32)
    print(a)
    print("len of state_dict:", len(a.state_dict()))
    for k,v in a.state_dict().items():
        print(k, v.shape)
    print(a.emb is a.encode.emb.emb)
```
Then it would output
```
model(
  (encode): submodule(
    (emb): subsubmodule(
      (emb): Embedding(100, 32)
    )
  )
  (emb): Embedding(100, 32)
)
len of state_dict: 2
encode.emb.emb.weight torch.Size([100, 32])
emb.weight torch.Size([100, 32])
True
```
In `a.state_dict()`, `encode.emb.emb.weight` and `emb.weight` are the same thing but they both appear.

## Expected behavior

The same object in model's state_dict() only appears one time (len of a.state_dict() is 1). 
As for the print of model, consider about add note such as "ref submodule"? then the print of model would be something like this:
```
model(
  (encode): submodule(
    (emb): subsubmodule(
      (emb): Embedding(100, 32)
    )
  )
  (emb): Embedding(100, 32) [ref encode.emb.emb]
)
```

## Environment

```
PyTorch version: 1.9.0
```

cc @albanD @mruberry @jbschlosser

**Comment by albanD** [comment]
Hi,

This is the expected behavior I'm afraid. If a Module or Parameter or Buffer is referenced multiple times, it will appear multiple times on the state dict.
Note that the serialization will take care of making sure that they remain the same if you save/load the state_dict via torch.save.

**Comment by HuadingLing** [comment]
> Hi,
> 
> This is the expected behavior I'm afraid. If a Module or Parameter or Buffer is referenced multiple times, it will appear multiple times on the state dict.
> Note that the serialization will take care of making sure that they remain the same if you save/load the state_dict via torch.save.

ok, I probably got it. So it's not a bug. I just afraid that if there is something weird happend when I use this way. Now I'm understand it, thanks!
