### ISSUE TITLE
undefined reference to ` __stack_chk_guard'

### ISSUE THREAD

**Issue by aruhela** [pytorch/pytorch#62241]
Hi PyTorch Team,

I am trying to build PyTorch on a CPU system but getting the following error in the linking stage. I have also tried adding "-fno-stack-protector" in CFLAGS and CXXFLAGS but the error still persists.  Could you please let me know if there is any other flag to resolve the issue?

command : USE_CUDA=0 USE_CUDNN=0 BUILD_TEST=0 USE_DISTRIBUTED=mpi DEBUG=1 python setup.py develop
SourceCode : clone from https://github.com/pytorch/pytorch

Error 
[5559/5564] Linking CXX executable bin/torch_shm_manager
FAILED: bin/torch_shm_manager
: && /opt/apps/gcc/9.1.0/bin/c++ -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -g -fno-omit-frame-pointer -O0 -rdynamic -Wl,-rpath -Wl,/opt/apps/gcc9_1/mvapich2-x/2.3/lib64 -Wl,--enable-new-dtags    -rdynamic caffe2/torch/lib/libshm/CMakeFiles/torch_shm_manager.dir/manager.cpp.o -o bin/torch_shm_manager  -Wl,-rpath,/scratch3/05231/aruhela/mlcommons/pytorch/build/lib:/scratch3/05231/aruhela/libs/miniconda/conda/envs/cpu/lib:  lib/libshm.so  -lrt  lib/libtorch.so  -Wl,--no-as-needed,"/scratch3/05231/aruhela/mlcommons/pytorch/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobufd.a  /scratch3/05231/aruhela/libs/miniconda/conda/envs/cpu/lib/libmkl_intel_lp64.so  /scratch3/05231/aruhela/libs/miniconda/conda/envs/cpu/lib/libmkl_gnu_thread.so  /scratch3/05231/aruhela/libs/miniconda/conda/envs/cpu/lib/libmkl_core.so  -fopenmp  -lpthread  -lm  -ldl  lib/libdnnl.a  -pthread  -ldl  lib/libc10.so && :
/opt/apps/gcc/9.1.0/bin/ld: /scratch3/05231/aruhela/mlcommons/pytorch/build/lib/libtorch_cpu.so: undefined reference to `__stack_chk_guard'
collect2: error: ld returned 1 exit status
[5562/5564] Linking CXX shared module caffe2/python/caffe2_pybind11_state.cpython-38-x86_64-linux-gnu.so
ninja: build stopped: subcommand failed.

(cpu) staff.frontera(1016)$ module list
Currently Loaded Modules:
  1) git/2.24.1   2) autotools/1.2   3) cmake/3.20.3   4) pmix/3.1.4   5) hwloc/1.11.12   6) xalt/2.10.13   7) TACC   8) gcc/9.1.0   9) phdf5/1.10.4  10) mvapich2-x/2.3

(cpu) staff.frontera(1020)$ hostnamectl
   Static hostname: staff.frontera.tacc.utexas.edu
         Icon name: computer-server
           Chassis: server
        Machine ID: 63ba500ed0494c2c87a9f8925f2c0aab
           Boot ID: 68b2f90543b74bd3810db4c5c46da90c
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1127.19.1.el7.x86_64
      Architecture: x86-64

(cpu) staff.frontera(1022)$ python --version
Python 3.8.10

**Comment by aruhela** [comment]
Specifying export LDFLAGS=" -fstack-protector" resolves the problem.

**Comment by adamjstewart** [comment]
I just ran into this issue on CentOS 7 with GCC 9.1.0. Any idea when this flag is necessary and when it isn't? Is there any way this could be set by CMake automatically? I would consider manually setting LDFLAGS to be a workaround, not a solution.
