### ISSUE TITLE
Problem in installing latest version

### ISSUE THREAD

**Issue by sjsy** [pytorch/pytorch#6224]
- PyTorch 
- OS: Ubuntu 16.04
- PyTorch version: -
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 9.0/7 as well as 8.0/6
- GPU models and configuration: -
- GCC version (if compiling from source): -
- CMake version: -
- Build command you used (if compiling from source): -
- Versions of any other relevant libraries:

Hi, 
when I try to install pytorch by the following command, an old version is installed.

`conda install pytorch torchvision cuda90 -c pytorch`

	$ conda install pytorch torchvision cuda90 -c pytorch
	Using Anaconda Cloud api site https://api.anaconda.org
	Fetching package metadata .........
	Solving package specifications: ..........

	Package plan for installation in environment /opt/anaconda3/envs/cntk-py36:

	The following packages will be downloaded:

	    package                    |            build
	    ---------------------------|-----------------
	    numpy-1.11.3               |           py36_0         6.7 MB
	    scipy-0.19.0               |      np111py36_0        35.9 MB
	    scikit-learn-0.18.1        |      np111py36_1        11.1 MB
	    ------------------------------------------------------------
		                                   Total:        53.7 MB

	The following NEW packages will be INSTALLED:

	    cffi:         1.10.0-py36_0                        (soft-link)
	    cuda90:       1.0-h6433d27_0               pytorch (soft-link)
	    cudatoolkit:  8.0-3                                (soft-link)
	    cudnn:        6.0.21-cuda8.0_0                     (soft-link)
	    libgcc:       5.2.0-0                              (soft-link)
	    nccl:         1.3.4-cuda8.0_1                      (soft-link)
	    pycparser:    2.18-py36_0                          (soft-link)
	    pytorch:      0.1.12-py36cuda8.0cudnn6.0_1         (soft-link)
	    torchvision:  0.1.8-py36_0                         (soft-link)

	The following packages will be UPDATED:

	    mkl:          11.3.3-0                             --> 2017.0.3-0         (soft-link)
	    numpy:        1.11.2-py36_0                        --> 1.11.3-py36_0      (soft-link)
	    scikit-learn: 0.18.1-np111py36_0                   --> 0.18.1-np111py36_1 (soft-link)
	    scipy:        0.18.1-np111py36_0                   --> 0.19.0-np111py36_0 (soft-link)

How should I install the latest version?
Thanks.

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) for support questions.
In particular, yours has been answered [here](https://discuss.pytorch.org/t/how-to-update-pytorch-using-cuda-to-the-most-recent-version/15416).
