### ISSUE TITLE
[pytorch mobile][JIT] After "optimize_for_mobile" , I got adb shell errors like "Unsupported value kind: Object"

### ISSUE THREAD

**Issue by jinnyjinny** [pytorch/pytorch#62248]
## ❓ Questions and Help
Hi! I had a error message from adb shell :0 Here's the message: 
```
user$ adb shell /data/local/tmp/clova/speed_benchmark_torch --pthreadpool_size=1 --model=/data/local/tmp/clova/test/conv32x32.pth  --input_dims="1,32,56,56" --input_type="float" --warmup=100 --iter=1000

terminating with uncaught exception of type torch::jit::constant_not_supported_error: Unsupported value kind: Object
```
Q. As you can see there is not Object value. Anybody knows why "terminating with uncaught exception of type torch::jit::constant_not_supported_error: Unsupported value kind: Object" came from??

Q. I didn't quantization in this code. It can give raise to error? 
I want to check float 32 model inference latency on android mobile cpu. 
Not using`optimize_for_mobile`, it works on speed_benchmark_torch.sh! 

Q. What is difference using`optimize_for_mobile` before quantization or not?
After using `optimize_for_mobile`, it was happened:( 

Here's my code (+ Build environments attached below this code): 

```
import torch
import torch.nn as nn
from torch.utils.mobile_optimizer import optimize_for_mobile

class InvertedResidual(nn.Module):
    def __init__(self, in_channels, out_channels, hidden_dim_factor=1.):
        super(InvertedResidual, self).__init__()

        hidden_dim = int(in_channels * hidden_dim_factor)
        self.model = nn.Sequential(
            nn.Conv2d(in_channels, hidden_dim, 1, 1, 0, bias=True),
            nn.Conv2d(hidden_dim, hidden_dim, 3, 1, 1, groups=hidden_dim, bias=True),
            nn.Conv2d(hidden_dim, out_channels, 1, 1, 0, bias=True),
        )
    def forward(self, x):
        x = self.model(x)
        return x

net = InvertedResidual(32, 32)
net.eval()
net_traced = torch.jit.trace(net, torch.randn(1,32,56,56))
net_traced.save("model.pth")
# net_traced_optimized = optimize_for_mobile(net_traced)
# net_traced_optimized.save("model.pth")
```
 
### Build Environments
TORCH_VERSION         : 1.8.0
--   CAFFE2_VERSION        : 1.8.0
--   BUILD_CAFFE2          : ON
--   BUILD_CAFFE2_OPS      : OFF
--   BUILD_CAFFE2_MOBILE   : OFF
--   BUILD_STATIC_RUNTIME_BENCHMARK: OFF
--   BUILD_BINARY          : OFF
--   BUILD_CUSTOM_PROTOBUF : OFF
--     Protobuf compiler   : 
--     Protobuf includes   : 
--     Protobuf libraries  : 
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : OFF
--   BUILD_SHARED_LIBS     : OFF
--   CAFFE2_USE_MSVC_STATIC_RUNTIME     : ON
--   BUILD_TEST            : OFF
--   BUILD_JNI             : OFF
--   BUILD_MOBILE_AUTOGRAD : OFF
--   INTERN_BUILD_MOBILE   : ON
--   USE_ASAN              : OFF
--   USE_CPP_CODE_COVERAGE : OFF
--   USE_CUDA              : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FBGEMM            : OFF
--     USE_FAKELOWP          : OFF
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : OFF
--   USE_GLOG              : OFF
--   USE_LEVELDB           : OFF
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : OFF
--   USE_METAL             : OFF
--   USE_PYTORCH_METAL     : OFF
--   USE_MKL               : 
--   USE_MKLDNN            : ON
--   USE_NCCL              : OFF
--   USE_NNPACK            : ON
--   USE_NUMPY             : ON
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_TBB               : OFF
--   USE_VULKAN            : ON
--   USE_PROF              : OFF
--   USE_QNNPACK           : OFF
--   USE_PYTORCH_QNNPACK   : ON
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   USE_DISTRIBUTED       : OFF

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @gmagogsfm

**Comment by ansley** [comment]
I can't reproduce the issue with the code you provided. It runs fine on my machine. What version of Python are you using?

Also, I don't mind helping you here, but I would suggest asking for help at the [PyTorch Forums](https://discuss.pytorch.org/) instead. GitHub issues are meant for tracking specific bugs, while the forums are for "why doesn't this work?"-style questions. You may get better advice at the forums!
