### ISSUE TITLE
Using torch.from_numpy function inside function which use python multiprocessing 

### ISSUE THREAD

**Issue by emreanilterzioglu4dsight** [pytorch/pytorch#62256]
Hi, 
I want to use torch function on multiprocessed function. 

I create multiprocess like this 
`Process(target=bufferHandler, args=(numpyFrameList)).start()`

My function is like this:
```
def bufferHandler(image_list):

                    array = np.array(image_list)

                    tensor = array.reshape((array.shape[0], 1, array.shape[1], array.shape[2]))
                    tensor = torch.from_numpy(tensor / 255.).float().to(self.device)
```
But torch.from_numpy function never returns. It was working with python threading module but I want  to use multiprocessing now. 
Could you please help me?

cc @mruberry @rgommers @heitorschueroff

**Comment by rgommers** [comment]
`args=(numpyFrameList)` is not a tuple with a list, the `()` does nothing there. It should be `args=(numpyFrameList,)` (note the comma).

I think that'll fix it. If not, it would be good if you could provide a self-contained example that can be run @emreanilterzioglu4dsight

**Comment by emreanilterzioglu4dsight** [comment]
Actually, I wrote a test code yesterday and that worked fine. On main code i'm checking whats wrong. Give me few days please. By the way too much thanks for your fast help reply. @rgommers  @ejguan
