### ISSUE TITLE
Adding a new operator shouldn't need to trigger a rebuild of CUDA kernels

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#62258]
## 🚀 Feature

If someone adds a new operator into native_functions.yaml, it results in many CUDA kernels being rebuilt. This is probably because the ATen/ATen.h header changes (to include the new operator) and ATen/ATen.h is included almost everywhere. We should be able to get into a state where we put implementations of CUDA kernels (that do not call PyTorch operators) into .cu files that do not include ATen/ATen.h

## Motivation

CUDA builds seem painful, but maybe we have better stats on this somewhere

## Pitch

- For e.g. [group_norm_kernel.cu](https://github.com/pytorch/pytorch/blob/228b50e053527b594ae0fbb4fdc42c67e650f131/aten/src/ATen/native/cuda/group_norm_kernel.cu#L27-L475), move the CUDA kernels that do not depend on PyTorch into their own .cu files (e.g. group_norm_kernel_cudaonly.cu), add a new group_norm_kernel_cudaonly.cuh, and include group_norm_kernel_cudaonly.cuh in group_norm_kernel.cu

## Alternatives

Taking suggestions!

## Additional context

n/a

cc @malfet @seemethere @walterddr @ngimel

**Comment by malfet** [comment]
I love the idea, but we also need some sort of liner in place to prevent those from regressions
Cc: @makslevental

**Comment by makslevental** [comment]
I have a sketch of how this might work here https://github.com/pytorch/pytorch/pull/61915. Basic idea is to factor out any positive diff of `native_functions.yaml` into its own headers and include those only in the places where the originally generated headers were included. As you noted most of the recompile is through `ATen.h`, which we leave alone. 

I've also started experimenting with [include-what-you-use](https://include-what-you-use.org/) https://github.com/pytorch/pytorch/pull/62010/files which should more generally solve these problems. I'm not sure how much progress I'll be able to make on this over this summer (I'm a summer intern) but I'll try to get it done.

**Comment by peterbell10** [comment]
Closing as most CUDA kernels are compiled under `TORCH_ASSERT_NO_OPERATORS` now
