### ISSUE TITLE
Different results when loading weights

### ISSUE THREAD

**Issue by VinhLoiIT** [pytorch/pytorch#62264]
## 🐛 Bug

Our model behaves differently while using the same weights and inputs. We just change the order of loading weights using `torch.load()`.

## To Reproduce

This is a small script that I've extracted from my training source code.
```python
import torch
from model import GeneralizedConvSeq2Seq

device = 'cuda'

def make_model1():
    model = GeneralizedConvSeq2Seq()
    # move model and weights to GPU
    model.to(device)
    ckpt = torch.load('weights.pth', map_location=device)

    # then load model and make prediction
    model.load_state_dict(ckpt['model'])
    model.eval()
    return model

def make_model2():
    model = GeneralizedConvSeq2Seq()
    # model and weights are on CPU
    ckpt = torch.load('weights.pth', map_location='cpu')
    model.load_state_dict(ckpt['model'])

    # move model to GPU and make predictions
    model.to(device)
    model.eval()
    return model

inputs = torch.rand((1, 3, 32, 64))
model1 = make_model1()
model2 = make_model2()

with torch.no_grad():
    # check same output backbone
    out1 = model1.backbone(inputs.to(device))
    out2 = model2.backbone(inputs.to(device))
    print(out1.shape)
    print(out2.shape)
    assert torch.equal(out1, out2)

    # flatten out1 B,C,H,W -> B,S,E
    B, E, H, W = out1.shape
    out1 = out1.reshape(B, E, H * W)                    # B, E, H * W
    out1 = out1.transpose(-2, -1)                       # B, S = H * W, E

    # flatten out2 B,C,H,W -> B,S,E
    B, E, H, W = out2.shape
    out2 = out2.reshape(B, E, H * W)                    # B, E, H * W
    out2 = out2.transpose(-2, -1)                       # B, S = H * W, E
    assert torch.equal(out1, out2)

    out1 = model1._forward_eval(out1, image_padding_mask=None)
    out2 = model2._forward_eval(out2, image_padding_mask=None)
    print(out1.shape)
    print(out2.shape)
    assert torch.equal(out1, out2), f'{out1.shape} != {out2.shape}'  # False
```

Without a deeper look inside the model implementation, we can clearly see that the same methods are called given the same inputs.

Steps to reproduce the behavior: See [my simple reproducible repo](https://github.com/VinhLoiIT/pytorch-load-weight)

The output on the terminal is as below:
```
torch.Size([1, 128, 4, 8])
torch.Size([1, 128, 4, 8])
torch.Size([1, 38, 114])
torch.Size([1, 151, 114])
Traceback (most recent call last):
  File "run.py", line 55, in <module>
    assert torch.equal(out1, out2), f'{out1.shape} != {out2.shape}'  # False
AssertionError: torch.Size([1, 38, 114]) != torch.Size([1, 151, 114])
```

## Expected behavior

The output should be the same in both model loading approaches.

## Environment

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.10

Python version: 3.7.9 (default, Aug 31 2020, 12:42:55)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.8.0-63-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1650
Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.3.8
[pip3] torch==1.9.0
[pip3] torch-tb-profiler==0.2.1
[pip3] torchinfo==1.5.2
[pip3] torchmetrics==0.4.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.0            py37h42c9631_2  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.20.3           py37h74d4b33_0  
[conda] pytorch                   1.9.0           py3.7_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         1.3.8                    pypi_0    pypi
[conda] torch-tb-profiler         0.2.1                    pypi_0    pypi
[conda] torchinfo                 1.5.2                    pypi_0    pypi
[conda] torchmetrics              0.4.1                    pypi_0    pypi
[conda] torchtext                 0.10.0                     py37    pytorch
[conda] torchvision               0.10.0               py37_cu102    pytorch

cc @albanD @mruberry @jbschlosser

**Comment by albanD** [comment]
Hi,

Can you check what happens if you replace `torch.equal` with `torch.allclose`?
It is very much possible that you get very small difference due to the different ways to load the weights (we're talking 1 bit difference).

**Comment by jbschlosser** [comment]
Am I reading this correctly that the *shapes* of the two outputs are unexpectedly different? Without knowing what's going on in `_forward_eval()`, it's hard to track down why. There's no guarantee that calling the same function with the same inputs produces the same outputs since it's possible to have non-deterministic logic inside that affects output shape (silly example: logic that generates random output shapes).

**Comment by jbschlosser** [comment]
Hey @VinhLoiIT, the problem is that your model's `decoder.in_embed.weight` and `decoder.out_embed.weight` reference the same Parameter. From your `model.py`:

```python
...
out_embed = nn.Linear(128, 114, bias=False)
in_embed = nn.Embedding(114, 128, 2,_weight=out_embed.weight)
...
```

When calling `model.load_state_dict()`, `decoder.in_embed.weight` is first loaded correctly but is then overwritten by the value of `decoder.out_embed.weight` when it is loaded due to the reference.

Calling `to('cuda')` makes `decoder.in_embed.weight` and `decoder.out_embed.weight` no longer reference the same Parameter, which is why things work as expected when `to()` is called first.

You can fix model loading by ensuring separate parameters (e.g. using `clone()`):
```python
...
out_embed = nn.Linear(128, 114, bias=False)
in_embed = nn.Embedding(114, 128, 2,_weight=out_embed.weight.clone())
...
```

**Comment by VinhLoiIT** [comment]
Hi, @jbschlosser,

The point of passing `_weight` into the embedding's constructor is to share the weights between `in_embed` and `out_embed`. I've just found in `weights.pth` that the tensor data of `in_embed` and `out_embed` are different, so there must be some things wrong here.

Just wondering, which of below approaches is correct when I sharing the weight of these two modules:
```python
out_embed = nn.Linear(128, 114, bias=False)
in_embed = nn.Embedding(114, 128, 2,_weight=out_embed.weight)
```
or
```python
out_embed = nn.Linear(128, 114, bias=False)
in_embed = nn.Embedding(114, 128, 2)
in_embed.weight = out_embed.weight
```

My model used the first one and it resulted in this issue.

**Comment by jbschlosser** [comment]
@VinhLoiIT I bet the reason that `in_embed` and `out_embed` are different is because of a `to()` call before training that breaks the reference to the same parameter. Since `to()` doesn't maintain references, I'd recommend the second approach once the model is on the correct device.

**Comment by VinhLoiIT** [comment]
Thank you. The second approach solved this issue.

However, as you said, it seems the `_weight` parameter in the `nn.Embedding`'s constructor would be a little bit confusing. It is supposed to share the weights but has different behavior before and after moving the model to another device.

**Comment by jbschlosser** [comment]
Note that the `_weight` parameter exists mainly for `from_pretrained()`. In general, args with names that begin with an underscore are not considered part of the public API - they are undocumented and we don't make strong guarantees about their usage.

**Comment by VinhLoiIT** [comment]
Thank you for your clarification.

The problem was solved and I will close this issue.
