### ISSUE TITLE
`docker_for_ecr_gc_build_job` broken on master CI due to reaching maximum number of images on Amazon ECR

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#62269]
## 🐛 Bug

CI test (`docker_for_ecr_gc_build_job`) on Master is consistently failing:
When `push refers to repository [308535385114.dkr.ecr.us-east-1.amazonaws.com/gc/ecr]`, it raises `denied: The repository with name 'gc/ecr' in registry with id '308535385114' already has the maximum allowed number of images which is '10000'`

Example test:
https://app.circleci.com/pipelines/github/pytorch/pytorch/356564/workflows/3a3aa850-19eb-4d86-900a-f2f5e8a228c6/jobs/15031783

## Task list (from @seemethere)

- [x] Remove intermediate build images with an ECR lifecycle policy (https://github.com/pytorch/pytorch/pull/62610)
- [ ] Remove preview base docker image builds with an ECR lifecycle policy

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Alleviated the issue by deleting older containers from Jan 2020, but we need to add this registry to garbage collection

**Comment by malfet** [comment]
@driazati can you please consider adding tracking for  ECR total size + image count in grafana?

**Comment by zhouzhuojie** [comment]
Going to add a ECR lifecycle policy to clean up the old images

**Comment by zhouzhuojie** [comment]
@malfet @seemethere 

Potential solution is to refactor
- https://github.com/pytorch/pytorch/blob/master/.circleci/config.yml#L9623 and only push new `gc/ecr` when there's a change to the `.circleci/ecr_gc_job` folder
- all the existing images on 308535385114.dkr.ecr.us-east-1.amazonaws.com/gc/ecr looks safe to remove (except the latest one)

**Comment by seemethere** [comment]
> @malfet @seemethere
> 
> Potential solution is to refactor
> 
> * [https://github.com/pytorch/pytorch/blob/master/.circleci/config.yml#L9623](https://github.com/pytorch/pytorch/blob/master/.circleci/config.yml?rgh-link-date=2021-07-27T17%3A19%3A43Z#L9623) and only push new `gc/ecr` when there's a change to the `.circleci/ecr_gc_job` folder
> * all the existing images on 308535385114.dkr.ecr.us-east-1.amazonaws.com/gc/ecr looks safe to remove (except the latest one)

This seems reasonable, we need a garbage collector for the garbage collector!

**Comment by seemethere** [comment]
Migration of ECR GC to Github Actions as well as removing the docker push altogether: https://github.com/pytorch/pytorch/pull/62284

**Comment by ejguan** [comment]
@seemethere 
It seems the master CI still complains about these tests after your patch.

**Comment by seemethere** [comment]
This should be resolved after #62438

**Comment by malfet** [comment]
PR was reverted so reopening

**Comment by seemethere** [comment]
Okay so I'm going to take a slightly different approach to solving this and I'm going to be looking to just remove our Garbage collection script altogether and rely instead on ECR lifecycle policies to dictate how long we keep specific images. I've submitted #62610 as a first step towards this

**Comment by malfet** [comment]
`docker_for_ecr_gc` jobs is gone, closing
