### ISSUE TITLE
potential hazard: in-place modification of index tensor of coalesced sparse tensor

### ISSUE THREAD

**Issue by kose-y** [pytorch/pytorch#6227]
This is pointed out on https://github.com/pytorch/pytorch/pull/6225. 
- PyTorch or Caffe2: PyTorch
- PyTorch version: 2e156f3eabb6fa4ae88c2e831aea7da344cf43a3

If we modify the indices tensor for a coalesced sparse tensor in-place, the premise of coalesced sparse tensor breaks down, but it is still marked as coalesced. I can't imagine ways for a sparse tensor to detect when the index tensor is modified in-place. Checking it every time when coalesced tensor is needed will slow down the performance.

```python
import torch
i = torch.LongTensor([
            [0, 1, 2],
            [2, 1, 0],
         ])
v = torch.FloatTensor([1, 1, 1])
D = torch.sparse.FloatTensor(i, v, torch.Size([3,3]))
Dc = D.coalesce()
```

```python
ii = Dc._indices()
ii[0,0] = 2
ii[1,0] = 1
ii
```

    
     2  1  2
     0  1  0
    [torch.LongTensor of size (2,3)]

```python
Dc._indices()
```

    
     2  1  2
     2  1  0
    [torch.LongTensor of size (2,3)]

```python
Dc.is_coalesced()
```

    True

**Comment by zou3519** [comment]
We don't support modifications to sparse tensors through their `_indices()` and `_values()` field very well; those methods are prefaced with an underscore to users that they shouldn't be used directly.

**Comment by apaszke** [comment]
Yep, closing because that's an abuse of the internal APIs.
