### ISSUE TITLE
What is slow-path and fast-path?

### ISSUE THREAD

**Issue by tarekmak** [pytorch/pytorch#62282]
## ❓ Questions and Help

I am reading pytorch code base and issue to get a better understanding of the design choices. I keep seeing fast-pathed or fast-passed function. I was wondering what these are? For instance, the issue here (https://github.com/pytorch/pytorch/pull/46469 2).

Thank you in advance!

**Comment by ejguan** [comment]
Thanks for taking interest in PyTorch. 
As mentioned at the very top of the template you use, we use github issues only for bugs or feature requests. Please use the [forum](https://discuss.pytorch.org/) to ask questions.
