### ISSUE TITLE
How can I get output of the intermediate layers with quantized jit model

### ISSUE THREAD

**Issue by AndyDrill** [pytorch/pytorch#62287]
Hello everyone.
I've get the quantized jit model with following link.
[https://leimao.github.io/blog/PyTorch-Static-Quantization/](url)

What I want to know is how to get the output value of the intermediate layers with loaded quantized jit model.
I'm not sure if it's possible and the output value will be int8 data type.
Any hints will be very helpful.
Thanks for your time.

cc @gmagogsfm

**Comment by ansley** [comment]
Hey @AndyDrill, thanks so much for your question! Could you please post it to the [PyTorch Forums](https://discuss.pytorch.org/)? We use the GitHub issue tracker for bugs and feature requests. I'm going to close this issue, but feel free to open another GH request if you do run into a specific bug. Good luck!
