### ISSUE TITLE
IntelliJ trips on parameter documentation

### ISSUE THREAD

**Issue by cowwoc** [pytorch/pytorch#62296]
`_TensorBase.py` contains the following documentation:

```
            dtype (type or string): The desired type
```

If I pass a `dtype` for this parameter IntelliJ warns ``Expected type `Union[type, string]`, got `dtype` instead``

I suspect replacing `type` with ``:class:`torch.dtype` `` would resolve this error.

cc @brianjo @mruberry

**Comment by bdhirsh** [comment]
We would accept a patch that fixes this!

**Comment by cowwoc** [comment]
I don't know what happened but I can no longer reproduce this problem. The situation is actually kind of worse now.

Given code like `torch.from_numpy(y).type(torch.get_default_dtype())` I am now seeing IntelliJ cannot resolve `type()`. It reports "Cannot find declaration to go to".

`torch.from_numpy()` returns `Tensor` and `Tensor.type()` seems to resolve to `_TensorBase.type()`. There is no documentation for the latter and the class is said to be `Defined in torch/csrc/autograd/python_variable.cpp`.

Any idea when this behavior changed? I can no longer find `_TensorBase.py`.
