### ISSUE TITLE
Windows "smoke tests" are not very "smoky" 

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#62298]
## Future of Windows Smoke Tests

To save on CI cost while maintaining a level of signal quality, we currently run a small subset of test cases (instead of the full test suite) on Windows CUDA configs on PRs. An example can be found [here](https://github.com/pytorch/pytorch/actions/runs/1071698069) for the pytorch-win-vs2019-cuda10-cudnn7-py3 job. 

The subset of tests we run are based on the list [here](https://github.com/pytorch/test-infra/blob/master/stats/windows_smoke_tests.csv), which are the results from running internal queries regarding the test case statuses on Windows vs Linux platforms from the last 30 days. The idea is that if a test case is more likely to fail on Windows than Linux, then it would be counted as a smoke test for Windows.

Originally, our initial query results yielded valid, non-flaky tests, that very much seemed like good smoke tests. Theses results are still the ones used today in CI.

However, our past two query results were not so:
Our second attempt (two weeks ago) ended up with mostly distributed tests, which are known to be flaky.
Our third attempt (last week) ended up with NO test cases satisfying our query. There were no test cases with failures for Windows CUDA only and not also Linux CUDA.

Thus, we should consider what to do as the idea of having smoke tests for Windows seems less practical/realistic now.

## Our Options

1. We could forego our idea of "smoke" tests but still keep the idea of running a subset of tests on PRs. Instead of using a query, we can randomly choose a subset to run. This will save CI cost and potentially maintain signal quality, though research will have to be done to verify that.

1.5 An extension of the first point makes the assumption that there indeed is no idea of smoke tests for Windows. If that's the case, maybe we can further cut costs by sharding our tests and splitting them across our configs randomly. For example, Windows platforms could test 1 shard while Linux would run the other, but who runs what would be randomized. While randomization effectively allows all tests to be covered by all platforms eventually, it introduces nondeterminism and potential frustration in the debugging process of development.

2. It is possible that there are indeed smoke tests that are more prone to failure on PRs, but maybe they are failed so infrequently that our queries cannot always catch them (as we are confined to the last 30 days). To make this happen, we would need to store and query more long-term stats, or we would have to maintain our own manual list of tests.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @mruberry @VitalyFedyunin @walterddr

**Comment by mszhanyi** [comment]
My understanding of the purpose is to find the failure tests ASAP to save the cost.
It'd better to choose the most related tests of the PR, if we can, than randomly choose a subset.

**Comment by janeyx99** [comment]
A recent run of our internal query returned ~15 likely smoke test candidates once again, **signifying that there _are_ still potential Windows smoke tests!**

I will be adding these new finds to our current windows smoke test list. To my dismay, I also suspect my previous runs of the query showed only partial results amidst our GHA migration, as we renamed our build jobs from `blah-windows-blah` to `blah-win-blah`, which explains the lack of results.

This manual system is certainly too fault-prone and not very maintainable, so I still believe we should invest in the following:
1. Having open source stats so we can query externally. This would allow us to automate the process and enable more code review that would verify the query. I believe the process in getting these stats is ongoing. 
2. A next step for myself is to move the query to a bento so it could get diff reviewed and have more visibility when it updates.
3. Following @mszhanyi's suggestion of choosing relevant tests. 

@mszhanyi do you think the MSFT team can curate a list of tests more likely to fail for the Windows platform? If so, we would love to add that list to https://github.com/pytorch/test-infra/blob/main/stats/windows_smoke_tests.csv? As experts on Windows, that would significantly improve the quality of these smoke tests while we do not yet have an automatic way of gathering them.

**Comment by janeyx99** [comment]
Next steps:
We should automate this process once we have external stats.

**Comment by janeyx99** [comment]
We've removed the smoke test functionality in https://github.com/pytorch/pytorch/pull/73042, so closing as this has become less relevant. Can be re-opened later when we are better suited for support smoke tests
