### ISSUE TITLE
Pytorch Discuss forum is down !

### ISSUE THREAD

**Issue by Abhranta** [pytorch/pytorch#62294]
## 🐛 Bug

When I try to open discuss.pytorch.org , it says that  "This site can’t be reachedThe web page at https://discuss.pytorch.org/ might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED"

## To Reproduce

1. O=Try to visit the website.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @brianjo @mruberry

**Comment by bdhirsh** [comment]
Are you still having issues getting to the forums? I'm able to follow the link successfully.

**Comment by brianjo** [comment]
I am as well. It may be a caching issue on your machine. Can you try another device? Thanks!

**Comment by Abhranta** [comment]
Okay, it working now. I think it was a caching issue or something. I tried after a day and it is working now. Thanks for the help !!!
