### ISSUE TITLE
Core dumped when dividing long tensor by a float

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#6231]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: Pytorch
- OS: Ubuntu 16.04
- PyTorch version: .4+4c81282c (yesterday's master)
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6
- CUDA/cuDNN version: n/a
- GPU models and configuration: n/a 
- GCC version (if compiling from source): 5.4
- CMake version:n/a
- Build command you used (if compiling from source): python setup.py build develop
- Versions of any other relevant libraries:

```
In [1]: import torch

In [2]: a = torch.LongTensor([1,2,3,4])

In [3]: a.sum() / 0.001
Floating point exception (core dumped)
```
I'm pretty sure related to #6197 and recent scalar changes.

**Comment by li-roy** [comment]
Caused by #6196. 0.001 float is being cast to 0 integral and we get divide by 0.

**Comment by ailzhang** [comment]
let's use #6196 to track the progress
