### ISSUE TITLE
DISABLED test_fn_gradgrad_linalg_det_cuda_complex128 (__main__.TestGradientsCUDA)

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#62328]
As it breaks https://app.circleci.com/pipelines/github/pytorch/pytorch/356909/workflows/c5e75110-4a25-40a2-8738-839b900c6caf/jobs/15048492

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by Lezcano** [comment]
cc @nikitaved who recently implemented this function.

**Comment by nikitaved** [comment]
Strange, the double backward path goes through eig and prod. I wonder whether the old SVD path is going to fix that...

**Comment by krshrimali** [comment]
`gradcheck` failures are also breaking: https://app.circleci.com/pipelines/github/pytorch/pytorch/358643/workflows/3a69bb7b-3828-45ae-9e18-71568867e197/jobs/15127451. Hoping that the opened PR for fixing this issue can also take care of `gradcheck` failures. Thanks!

cc: @nikitaved

**Comment by soulitzer** [comment]
Reopening this since it seems to be failing again - https://app.circleci.com/pipelines/github/pytorch/pytorch/363351/workflows/eb7afa3d-2000-42bd-957e-698aad957a0e/jobs/15330183

**Comment by nikitaved** [comment]
Now it gets really weird. Looks like these tests do not fail consistently. Requires some deep look through these tests.

**Comment by clee2000** [comment]
Closing as this issue doesn't actually disable anything anymore since the test got renamed
