### ISSUE TITLE
DISABLED test_fn_gradgrad_linalg_det_cuda_float64 (__main__.TestGradientsCUDA)

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#62327]
As it broken https://app.circleci.com/pipelines/github/pytorch/pytorch/356909/workflows/c5e75110-4a25-40a2-8738-839b900c6caf/jobs/15048492

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by nikitaved** [comment]
Strange, the double backward path goes through eig and prod. I wonder whether the old SVD path is going to fix that...

**Comment by soulitzer** [comment]
Reopening this since it seems to be failing again - https://app.circleci.com/pipelines/github/pytorch/pytorch/363351/workflows/eb7afa3d-2000-42bd-957e-698aad957a0e/jobs/15330183

**Comment by anjali411** [comment]
cc. @nikitaved

**Comment by nikitaved** [comment]
Need to see what kind of tests these are. They do not fail consistently.
