### ISSUE TITLE
[feature request] log2, log10 computation pytorch

### ISSUE THREAD

**Issue by RerRayne** [pytorch/pytorch#6233]
I've found that numpy computes log2 and log10 not just do log(x)/log(2.) or log(x)/log(10.). It uses [a more tricky way](https://github.com/numpy/numpy/blob/master/numpy/core/src/npymath/npy_math_internal.h.src#L318) to avoid a cancellation error. 

For example, I have a vector with 800 elements. After log2 calculation on it using numpy and torch (log(x)/log(2.)) I have the norm of the difference between two resulted vectors near 1.7e-05. But after a few operations after logarithm, it comes to 1.0-2.0.

It would be great if torch can do it in the same way.

**Comment by vishwakftw** [comment]
I can take this up. @soumith please let me know if that is fine.

**Comment by apaszke** [comment]
Please do!
