### ISSUE TITLE
Bus error (core dumped) when import torch

### ISSUE THREAD

**Issue by jikechao** [pytorch/pytorch#62330]
### Please note that this issue tracker is not a help form and this issue will be closed.
I built pytorch from source.  I can run well. 
However, when I run it again today, It crashed throwing an exception  **Bus error (core dumped)**
Note that it crashed when I ` import torch`
How strange it is. 

cc @malfet @seemethere @walterddr

**Comment by bdhirsh** [comment]
Hi,

It'll be difficult to help unless you have reproduction instructions + information about the environment that you're building pytorch on. Have you tried reproducing the issue using the `1.9.0` and `nightly` wheels? https://pytorch.org/get-started/locally/
