### ISSUE TITLE
Shorten job names in HUD

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62357]
-  `cuda10.2-cudnn7`->`cu10.2`
- Drop `pytorch-` prefix and only keep libtorch one
But before doing any renaming work on a script that does the same in HUD (perhaps based on https://github.com/pytorch/test-infra/blob/main/tools/scripts/update_pending_hud.py )

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
Also renaming needs to be carefully crafted because the build_environment also is used for some other string matches on test logic. (e.g. `if [[ BUILD_ENVIRONMENT == *cuda* ]]; then ...` in test.sh).

will take a closer look into this.
