### ISSUE TITLE
[rfc] Simplify the PyTorch CI

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#62370]
PyTorch’s CI has many moving parts, any of which can fail and cause churn on PRs or master, confusing devs and reducing trust in our tests. The CI has grown organically over time, so there are likely places that can be improved with a concerted effort.

## Survey

Most of the things in this issue are just ideas without any real data to back them up or track over time. We should have some way of measuring the complexity of our CI and track that over time. Things could include:

* Number of CI jobs
* Number of conceptual steps per job (i.e. not just the steps as the CI platform defines, but any time we switch runtimes (i.e. a bash script → a bash script → a Python script)). It’d be cool if we could assemble a big graph of these and visualize everything in one place
* Configuration length - This is a pretty indirect measure, but the more logic we push from platform specific definitions to Python scripts, the more flexible we become and the easier it is to understand what is happening when our CI runs

## Possible Improvements

* Remove Jenkins - We currently maintain 3 CI platforms - GitHub Actions, CircleCI, and Jenkins. We only host a single ROCm build on Jenkins and it’s not clear that it’s necessary to maintain a third CI system when we can use custom runners with GitHub Actions
    * Migrate pytorch-linux-bionic-rocm4.2-py3.6-* jobs to GitHub Actions with a custom runner
    * Remove [ci.pytorch.org](http://ci.pytorch.org/) and [jenkins.ci.pytorch.org](jenkins.ci.pytorch.org) DNS entries
    *  Shut down (but don’t terminate) the Jenkins and Worker EC2 instances
        * If everything is fine after some period of time, we can permanently decommission these
    * Remove Jenkins logic from the HUD
* Consolidate on Python in CI - Many of our build scripts are a combination of CircleCI/GHA dispatching logic, a few bash scripts, then finally a Python harness. Migrating these bash scripts to Python will improve cross-platform running (no need for batch scripts) and be more approachable to PyTorch devs.
* Use templates / community GitHub Actions for common patterns
    * We have some common steps that are duplicated in a bunch of places in our GitHub Actions workflows: Chown workspace, archive / store artifacts, clean up docker images, Parse ref. We could make more liberal use of Jinja templates so these could be defined in one place, and for actions that fit the pattern we could write custom actions like with https://github.com/seemethere/upload-artifact-s3
* Migrate nightly and viable/strict pushes from internal FB infra to GitHub Actions cron jobs

cc @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
One thing about moving bash scripts to python scripts would be that we'd probably still need to maintain two separate branches of conditional logic, especially for windows vs. linux

They'd have the same entry point but the conditional logic especially around dependency installation is going to end up being completely different.

I do think moving them to a central language is still good but just noting that we'll still have to maintain separate logic

**Comment by seemethere** [comment]
I believe @suo is already work towards this but his proposal is a bit different. Going to close since this issue does not contain the relevant issue anymore, feel free to re-open if necessary.
