### ISSUE TITLE
libtorch on Apple m1

### ISSUE THREAD

**Issue by vermouth1992** [pytorch/pytorch#62371]
## 🚀 Feature
Prebuilt libtorch on Apple m1. 
Just wonder is there any pre-built libtorch on Apple m1? I am using Pytorch C++ on Mac m1 which won't link to a library built on Intel platform. I tried to build Pytorch on my own but weird errors occur. Thanks for the help!

cc @malfet @ezyang @seemethere @walterddr @pytorch/pytorch-dev-infra @yf225 @glaringlee @albanD

**Comment by malfet** [comment]
There isn't one right now. I'll be happy to review PR that adds the workflow to CI system.

Please note, that regular M1 wheels are just a superset of libtorch shared library build.

**Comment by vermouth1992** [comment]
Thank you for your response. I tried to use the version installed by Conda. Here is the exact steps I took by following the example at https://pytorch.org/cppdocs/installing.html#support:

1. conda install pytorch (using the one on miniforge3)
2. cmake -DCMAKE_PREFIX_PATH=`python -c 'import torch;print(torch.utils.cmake_prefix_path)'`. And I got this error: 

CMake Error at /Users/chizhang/miniforge3/lib/python3.9/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:58 (message):
  Your installed Caffe2 version uses protobuf but the protobuf library cannot
  be found.  Did you accidentally remove it, or have you set the right
  CMAKE_PREFIX_PATH? If you do not have protobuf, you will need to install
  protobuf and set the library path accordingly.
Call Stack (most recent call first):
  /Users/chizhang/miniforge3/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)

Then, I add the miniforge to the DCMAKE_PREFIX_PATH as well and I got the following warning:

CMake Warning at /Users/chizhang/miniforge3/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /Users/chizhang/miniforge3/lib/python3.9/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:4 (find_package)

3. Then, I build the example and the following error occurs:

make[2]: *** No rule to make target `/Users/chizhang/miniforge3/lib/libopenblas.dylib', needed by `example-app'.  Stop.
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
make: *** [all] Error 2

Do you have any suggestions on what might be wrong? My python programs using Pytorch can run without any problems though.

Thanks!!

**Comment by vermouth1992** [comment]
After some exploration, I found that libopenblas.dylib is actually installed, but named as libopenblas.0.dylib. After creating a symbolic link, I can successfully build my application on Mac M1. Thank you for your help!

**Comment by vermouth1992** [comment]
I just leave the issue open in case someone else would like to add the workflow to CI system.

**Comment by bakkot** [comment]
@malfet It would still be nice to have prebuilt binaries for mps devices. You mentioned above you'd be willing to review a PR which adds it to the CI workflow system. Any chance you could reopen and review https://github.com/pytorch/pytorch/pull/88911 ?

Also, for anyone else who (like me) comes across this issue by Googling, you can get a copy of the pytorch binaries by installing the full package, as mentioned above. That is:

```sh
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install torch
$ python -c 'import torch; from pathlib import Path; print(Path(torch.__file__).parent)'
```
will print the path to a `torch` install which includes `libtorch` headers and prebuilt shared libraries and so suitable for use by other projects which need it (like [tch-rs](https://github.com/LaurentMazare/tch-rs/)).

**Comment by ZainRizvi** [comment]
Looks like this was merged in by the above PR
