### ISSUE TITLE
Test  PyTorch wheel packages

### ISSUE THREAD

**Issue by tktrungna** [pytorch/pytorch#62380]
## 🚀 Feature
Build PyTorch wheel packages during build stage on GitHub for pull requests, upload it to Amazon S3 and install during test stage. 

## Motivation

Currently, most of the tests depends on the `build/` folder. We may want to test the shipped package such as wheel. Removing that dependency would help to reduce time of running build, test

## Pitch

Update test scripts and relevant paths to make sure CI workflows pass without the `build/` folder

## Alternatives

TBD

## Additional context

TBD

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment]
It's important to test that `setup.py develop` workflow still works in CI. However, I agree it would be very convenient if CI vended wheels that you could download and try locally. Note that you can trigger this manually using the ci/binaries label (as the binary builds do in fact produce wheels)>
