### ISSUE TITLE
Profiler reports profiling overhead & inaccurate numbers for last record_function

### ISSUE THREAD

**Issue by dabeschte** [pytorch/pytorch#62390]
## 🐛 Bug

The profiler is currently not very useful to me as it includes its own overhead in the report.
The more I try to pin the bottleneck down by adding "record_function" to all my functions, the more overhead is included.
This does not only make the performance worse, but it adds many additional function calls in the report. This makes it nearly impossible for me to find problems/bottlenecks in my model. 

Also, some numbers are simply not correct. E.g. when I call 3 functions in a method and only record the first two, the second will have a much larger duration (10x in my case) than when I also record the third function. In this case, the overhead is added to the third function.

## To Reproduce

Overhead
1.  Simply add more "record function" decoration to every function in the stack trace. suddenly "aten::add, aten::cat", etc. will be called more often.

Last function inaccurate
1. Profile 1 out of 2 functions with record_function and log times
2. Profile both functions with record_function and compare times --> first function is much faster now

## Expected behavior

Profiling overhead should be excluded from reports.
Profiling should report valid timings without having to add dummy calls at the end which collects a large part of the profiling overhead.

## Environment

Win 10, Cuda, same issue on multiple workstations

cc @ilia-cher @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by nbcsm** [comment]
Thanks for the feedback.
Could you help to share a minimal sample script please? So we can reproduce it.

**Comment by dabeschte** [comment]
Hi! This is a very small example that shows the increasing number of aten::zeros and aten::empty calls when using _record_function_. If you need other examples for aten::cat, aten::add as well, I would first need to find out when that happens. In this example, we don't see those calls. I hope this is still helpful!

```
import torch
import torch.nn as nn
from torch.autograd.profiler import profile, record_function


class A(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(100, 100)
        self.record = False

    def forward (self, x):
        if self.record:
            with record_function("a"):
                return self.l1(x)
        return self.l1(x)


class B(nn.Module):
    def __init__(self):
        super().__init__()
        self.l2 = nn.Linear(100, 100)
        self.record = False

    def forward (self, x):
        if self.record:
            with record_function("b"):
                return self.l2(x)
        return self.l2(x)


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.a = A()
        self.b = B()


    def forward(self, x):
        y = self.a(x)
        y = self.b(x)
        y = self.b(x)
        return y


device = "cuda:0"
x = torch.ones((100, 100), device=device)
model = Net().to(device)

y = model(x)


######## Expectation: all calls should return same number of aten::zeros and aten::empty

# this returns 2 aten::zeros calls and 8 aten::empty calls

with profile(use_cuda=True, record_shapes=True) as prof:
    with record_function("model"):
        y = model(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=20))

model.a.record = True
model.b.record = False

# this returns 3 aten::zeros calls and 7 aten::empty calls

with profile(use_cuda=True, record_shapes=True) as prof:
    with record_function("model"):
        y = model(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=20))

model.a.record = True
model.b.record = True

# this returns 4 aten::zeros calls and 11 aten::empty calls

with profile(use_cuda=True, record_shapes=True) as prof:
    with record_function("model"):
        y = model(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=20))
```

**Comment by cloudhan** [comment]
@dabeschte  I would say this is expected behavior XDDD

This is because `record_function` is currently implemented in a hacky way.
It [create a tensor]( https://github.com/pytorch/pytorch/blob/d6130f324abeda404f36cd0072bdc71060898a66/torch/autograd/profiler.py#L612) with `zeros` and [hack the tensor](https://github.com/pytorch/pytorch/blob/fd8004b42e2a2348ec8837e3fb524b960c1b4cdb/aten/src/ATen/cpp_custom_type_hack.h#L97) with `empty`

**Comment by dabeschte** [comment]
I understand your point. It is not a bug, more like an imperfection. It is just not what I expected as a user ;)
Would it be possible to add a torch.no_profile guard for all calls originating from the profiler and record_function?
