### ISSUE TITLE
PR without checks on CI

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#62400]
PR https://github.com/pytorch/pytorch/pull/61820 breaks mypy on master CI as the tests are not carried out at the original PR.

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@ejguan do you know if this is the first commit by the author? To prevent CI abuse, GitHub instituted a policy that requires approvals for the first time contributors, see https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by ejguan** [comment]
@malfet I see. So, I guess the main reason is reviewer didn't enable the workflow. Closing this Issue.
