### ISSUE TITLE
Double sign error at density transformations

### ISSUE THREAD

**Issue by SebGruber1996** [pytorch/pytorch#62404]
## 🐛 Double sign error at density transformations

[These docs](https://github.com/pytorch/pytorch/blob/1b147a52f573643b2775c9bd3efca123e1fcb41a/torch/distributions/transformed_distribution.py#L10) correctly state the following:

```
Let f be the composition of transforms applied::
        X ~ BaseDistribution
        Y = f(X) ~ TransformedDistribution(BaseDistribution, f)
        log p(Y) = log p(X) + log |det (dX/dY)|
```

but in [this line](https://github.com/pytorch/pytorch/blob/1b147a52f573643b2775c9bd3efca123e1fcb41a/torch/distributions/transformed_distribution.py#L145) the following is calculated (in pseudo code):
`log p(Y) = log p(X) - log |det (dX/dY)|`

This would give wrong values, but it seems that the method `log_abs_det_jacobian` (for example [here](https://github.com/pytorch/pytorch/blob/945d40dca6e6fc98ccbc209d7d19e99ac8d4badd/torch/distributions/transforms.py#L513) ) returns the wrong sign in every implementation I have seen.
In the linked example the determinant of the jacobian of `log(y)` is `1/y`. Consequently, the log of it is `- log(y) = - x` and not `x`.
For all current implementations, this double sign error cancels out and has no consequence.
But every user, who is unfamiliar with this bug, will implement the `log_abs_det_jacobian` with the correct sign at first, which will give wrong results.

## To Reproduce

1. Implement the correct `log_abs_det_jacobian` function in a `Transform` class.
2. Create a transformed density with this `Transform` class.
3. Compare the log density values of the implementation with the real log density values.

## Expected behavior

It is expected that a `TransformedDistribution` subclass with the correctly implemented `Transform` class returns the correct log density values.

## Environment

PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.3.1 (arm64)
GCC version: Could not collect
Clang version: 12.0.1
CMake version: version 3.20.3
Libc version: N/A

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:27:18)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-11.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] torch==1.8.0
[pip3] torchvision==0.2.2
[conda] numpy                     1.21.1           py38hbf7bb01_0    conda-forge
[conda] pytorch                   1.8.0           cpu_py38hc43b888_1    conda-forge
[conda] torchvision               0.2.2                      py_3    pytorch

cc @fritzo @neerajprad @alicanb @nikitaved @jbschlosser @bhosmer @cpuhrsch

**Comment by neerajprad** [comment]
> but in this line the following is calculated (in pseudo code):
> log p(Y) = log p(X) - log |det (dX/dY)|

Note that the transform returns `log |det (dY / dX)|` not `log |det (dX / dY)|` (see [docstring](https://github.com/pytorch/pytorch/blob/945d40dca6e6fc98ccbc209d7d19e99ac8d4badd/torch/distributions/transforms.py#L177)), hence the negative sign in the expression, i.e. `log p(Y) = log p(X) - log |det (dY/dX)|`.

**Comment by SebGruber1996** [comment]
ah, yes, you are right. I overlooked that. Then the implementations are indeed correct.
But to be honest, it is quite confusing the way it is right now since I have never seen the density transformation being formulated with `dY / dX`.
