### ISSUE TITLE
Support more ops in LazyTensor to TorchScript lowering

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#62431]
## 🚀 Feature
Support more ops in LazyTensor to TorchScript lowering

## Motivation

Currently Lazy Tensor lowers [a limited set of ops](https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/ts_native_functions.yaml ) to TorchScript IR. For those are not supported yet, Lazy Tensor will fall back to the Eager execution. From the correctness perspective, this works fine. But various backends optimizers would rely on Lazy Tensor to capture larger IR graph for more aggressive optimizations. 

Here is a maybe-growing list for missing ops. If you want to sign up for adding an op, simply put your name behind the item and cross it out after you are done.

- [x] addcdiv (@desertfire)
- [x] fill_ (@wconstab)
- [x] _log_softmax (@alanwaketan)
- [x] _log_softmax_backward_data (@alanwaketan)
- [x] mean (@Gamrix)
- [x] nll_loss_backward (@alanwaketan)
- [x] nll_loss_forward (@alanwaketan)
- [x] random_ (@alanwaketan)
- [x] sqrt (@kshitij12345)
- [x] zero_ (@alanwaketan)
- [x] threshold_backward (@alanwaketan)
- [x] threshold (@anijain2305)

How to add an op (using `relu` as an example, credit to @asuhan):
- https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/QUICKSTART.md - instructions for building Lazy Tensor Core

- https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/ts_native_functions.yaml - add relu
note- op name should match one found in pytorch's `native_functions.yaml` 
- https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/lazy_tensor_core/csrc/ts_backend/aten_ltc_ts_type.cpp - add an implementation using LazyTensor::relu

- https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/lazy_tensor_core/csrc/ts_backend/ts_node_lowering.cpp - add lowering to TorchScript

- To test, `test/cpp/build/test_ptltc --gtest_filter=AtenLtcTsTensorTest.TestRelu`

A complete lowering guide can be found (credit to @asuhan):
- https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/OP_LOWERING_GUIDE.md

cc @gmagogsfm

**Comment by alanwaketan** [comment]
A lowering guide can be found: https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/OP_LOWERING_GUIDE.md.

**Comment by alanwaketan** [comment]
Also, we might still want `threshold_backward_out`. (#626129)

**Comment by alanwaketan** [comment]
> Can anyone clarify what `zero` is here? I can only find the following operators that look like `zero`: @jjsjann123
> 
> ```
> - func: zeros(int[] size, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor
> - func: zero_(Tensor(a!) self) -> Tensor(a!)
> ```

It should be zero_ according to #62619.

**Comment by alanwaketan** [comment]
Close this issue as all sub-tasks are completed.
