### ISSUE TITLE
Support half type in LazyTensor

### ISSUE THREAD

**Issue by asuhan** [pytorch/pytorch#62440]
## 🚀 Feature
Add support for half (aka fp16) type for lazy tensors.

## Motivation
This is useful for reduced precision training on GPU, which is the way we measure eager training throughput for several models.

## Code pointers

Most of the infrastructure for this is already in place. What remains to be done are cast and arithmetic operations: https://github.com/pytorch/pytorch/blob/ee1c705c1c16a47842638db027f8470397edcac7/lazy_tensor_core/lazy_tensors/types.h#L23. We can simply typedef (or wrap) `c10::Half`, which appears to support all we need already:

https://github.com/pytorch/pytorch/blob/master/c10/util/Half.h and https://github.com/pytorch/pytorch/blob/master/c10/util/Half-inl.h.

**Comment by wconstab** [comment]
meeting note: should be able to add 'half' test coverage by iterating over that type- see XLA tests.

**Comment by alanwaketan** [comment]
Should we close this since the PR is merged?

**Comment by asuhan** [comment]
@alanwaketan I think so.
