### ISSUE TITLE
GHA windows CI runners are waiting in queue for hours

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#62443]
We are seeing some examples that windows CI runners are waiting in queue for hours, we may want to monitor the CI's queue stats and scale up the windows runner accordingly.

![image](https://user-images.githubusercontent.com/658840/127573983-5c41cbef-0157-4bfc-af70-016a86cfbd4f.png)

```
Can't find any online and idle self-hosted runner in the current repository, account/organization and enterprisethat matches the required labels: 'windows.8xlarge.nvidia.gpu'
Found online and busy self-hosted runner(s) in the current repository that matches the required labels: 'windows.8xlarge.nvidia.gpu'. Waiting for one of them to get assigned for this job.
Waiting for a self-hosted runner to pick up this job...
```

https://github.com/pytorch/pytorch/runs/3196048846 (link for the error message above, may change once opened later)

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
is this related to the outage today?

**Comment by seemethere** [comment]
This is related to an outage that we were having with our own internal infra
