### ISSUE TITLE
[jit][script] Develop a plan for annotating static types for script methods

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#6246]
Currently the only type the script subset supports is Tensor. In the future, we want to support additional types:

* Tuples (an immutable list of static length)
* Lists (a potentially mutable list of dynamic length)
* (maybe) Records, dicts, etc.

Since script is used as a basis for optimizing pytorch code and for export, we want it to be statically typed. So far this static typing was easy since we just assumed _everything_ was a Tensor. Once we add one of the above features (such as Tuples #6153), we need a way to annotate types for things we would otherwise not know the type for. This occurs in at least two places right now:

* the arguments to a script function or method
* the return values of a pure python function called from a script method.

How we approach this problem depends on the technology we are using. In Python 3, we can use type annotations to do this (both on python functions that we want the script to call, and on our own script functions). If we use the string frontend, we can also add Python 3 style annotations. However, in Python 2 without the script frontend, we really do not have a good way to add annotations. The approach suggested by [PEP0484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) requires a separate parser to parse the python code.  This is ok for optional type checking, but a non-starter for mandatory type annotations.  

We need to:
* decide whether we should have a consistent interface across Python 2/Python 3, or to use Python 2 and 3 act differently
* come up with a viable annotation strategy for python 2
* plan to implement these annotations when we first need them (e.g. for tuples)

**Comment by apaszke** [comment]
I think conforming to the existing conventions (i.e. annotations when supported, with a fallback to the comment-based syntax) is the best. It's fairly simple to implement, would avoid confusion, and avoid forcing people to learn new ways to do the same things.

**Comment by zdevito** [comment]
How do we parse the comments? As far as I know, mypy and others come with their own parser.

**Comment by apaszke** [comment]
It looks like the strings are pretty much valid Python expressions, so I think we could just reuse the parser from `ast` and have our own translation pass. It's pretty easy, I can write this.

**Comment by zdevito** [comment]
Can you explain in more detail what approach you have in mind? Are you going to parse the entire function on its own, and then make our parser aware of the comments?

**Comment by ezyang** [comment]
I vote for Python 3 only for the hybrid frontend, and then use existing syntax for types.

Do we have any customers who fiat Python 2?

**Comment by soumith** [comment]
I think python3-only for something as fundamental as the hybrid frontend is a non-starter. that's 25% of our users, who due to various constraints (not everything in their control) are using py2.

**Comment by zdevito** [comment]
Yeah, we have to support Python 2. We also should even be hesitant to make the hybrid frontend look different across 2 and 3. Then people would need to learn 2 APIs. Not sure how I feel about `# type:` comments. It seems like a good solution for optional  type checking, but not a great solution for required meta-data needed by the frontend.

**Comment by apaszke** [comment]
@zdevito I'm not sure where the difficulty is. You just search for the `->` token, and you know that there is an expr before it, and an expr after it. We stich those parts to create e.g. a function that has those two statements in the body, use `ast` to as our parser, and then traverse the two exprs and translate them into our types.

Basically we hackily reuse the `ast` module as a parser, and then write a tiny and very simple interpreter that will construct tuples of types from the AST.

**Comment by apaszke** [comment]
Oh, and I just mean that we only look in the first line following the `def`, and if it has the type annotation then we parse the comment, and only then use `ast` on parts of it.

**Comment by apaszke** [comment]
Implemented in #7009.
