### ISSUE TITLE
ImportError:failed to load Pytorch C extensions:It appears that Pytorch has loaded the ‘torch/_C’ folder of the Pytorch repository rather than the C extensions which are expected in the ‘torch._C’ namespace.

### ISSUE THREAD

**Issue by baikaishui35** [pytorch/pytorch#62470]
I am using Jetson agx xavier from nvida.
jetpack4.4 ubuntu18.04 CUDA 10.02.
Now i want to download torch 1.7.0 into this ARM, here is how Nvida tells me to do.
![image](https://user-images.githubusercontent.com/88184005/127620923-7bd2f240-6621-4db3-b45d-b94fa249d45a.png)
But my internet can not do the first step ,i can not wget https://nvida.box.com.
So i download it by chrom, then pip install and import it into pycharm.
Then i see this error, it has bother me for a half month.
![image](https://user-images.githubusercontent.com/88184005/127620970-2962df62-6dc5-4554-b934-d1aca6a30425.png)
ImportError:failed to load Pytorch C extensions:It appears that Pytorch has loaded the ‘torch/_C’ folder of the Pytorch repository rather than the C extensions which are expected in the ‘torch._C’ namespace.This can occur when using the ‘install’ workflow.
$ pthon setup.py install && python -c “import torch”
This error can generally be solved using the ‘develop’ work flow
$ python setup.py develop &&python -c “import torch” #This should succeed or by running Python from a different directory.

I find this error from the init.file:
![image](https://user-images.githubusercontent.com/88184005/127620990-9cf22d1b-d45e-4d82-94fd-849a9240665a.png)
My anaconda is python3.7, then i see this and change it to python3.6. And then i see this error:
![image](https://user-images.githubusercontent.com/88184005/127621019-c64b4fba-42c4-4232-bca5-9ee3c43fad2b.png)
The both error bothered me for a long time, i really hope someone to save me.

**Comment by malfet** [comment]
It feels like you are trying to report 3 issues in one:
 - Not been able to configure your internet connection on Jetson board (although it's not specific to PyTorch)
 - Not been able to `import torch` for pytorch source folder (which is expected behaviour,  as you've self diagnosed, `python setup.py develop` helps in this case, but if you want to use official binaries than there are no need to have pytorch source checkout on the system)
 -  Python C API are not compatible across minor revisions, which is expected

**Comment by HamdiTarek** [comment]
I have the same problem with `ImportError:failed to load Pytorch C extensions:It appears that Pytorch has loaded the ‘torch/_C’ folder of the Pytorch repository rather than the C extensions which are expected in the ‘torch._C’ namespace. `

**Comment by Qruiqi** [comment]
hey，guys，could you solve it？，哥们，这个问题能教我解决吗？同问

**Comment by three-sheep** [comment]
> hey，guys，could you solve it？，哥们，这个问题能教我解决吗？同问

解决了嘛，哥们。我突然打开遇到这个问题，之前用都好好的

**Comment by baikaishui35** [comment]
后来解决了，是numpy这个库的问题，你环境里本来就有一个numpy库，结果装torch的时候又给你装了另一个版本的numpy库，调用的时候就出现了调用错乱的问题。先把numpy库卸载，看环境里还有没有numpy库，有的话就不用动了，没有的话再装个numpy。

**Comment by wwcc1107** [comment]
have  you  solved  this  problem:ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace.
thank you

**Comment by wen20220913** [comment]
I have the same problem when using Spyder IDE, and I solved this problem by uninstalling Spyder and using Anaconda to download Spyder. 
```conda install spyder```

**Comment by NadineAngermeier** [comment]
I still receive the same error to load PyTorch extensions. Where is the referenced setup.py file?

**Comment by Kivo0** [comment]
reinstall Torch

pip uninstall torch
pip install torch

**Comment by chenjunyan1** [comment]
卸载已安装的 numpy 库：
```pip uninstall numpy```
检查环境中是否还存在其他版本的 numpy：
```pip list | grep numpy```
如果输出结果中仍然存在 numpy 库，说明环境中还存在其他版本的 numpy。你可以考虑卸载这些版本。
重新安装 numpy 库：
如果你确认环境中已经没有 numpy 库了，你可以尝试重新安装 numpy：
```pip install numpy```

**Comment by TheW3ird1** [comment]
Same error, tried reinstalling torch, didnt work
