### ISSUE TITLE
Add `allow_empty_param_list` arg for all functional optimizers

### ISSUE THREAD

**Issue by andwgu** [pytorch/pytorch#62481]
The pull request https://github.com/pytorch/pytorch/pull/61678 added an argument `allow_empty_param_list` to `_FunctionalSGD`. If `allow_empty_param_list=True`, then the optimizer does not raise a `ValueError` upon an empty parameter list.

Overlapping `DistributedDataParallel.backward()` with `ZeroRedundancyOptimizer.step()` relies on using a functional optimizer as the local optimizer for ZeRO. Moreover, the current design has ZeRO share the same bucketing strategy as DDP. As a result, for certain configurations, there may be fewer buckets than ranks, in which case some `ZeroRedundancyOptimizer` instances have an empty shard of the parameters (i.e. they do not need to update any shard of the parameters). (An example is ResNet-50 with `bucket_cap_mb=25` yields 5 buckets, so training on 8 GPUs will have 3 ranks with empty parameter lists.)

One approach is to detect the empty parameter list in `ZeroRedundancyOptimizer` logic and modify the behavior. However, since the new `OptimizerHookState` class introduced in the aforementioned PR [seems to expect an `allow_empty_param_list` argument for all functional optimizers](https://github.com/pytorch/pytorch/blob/b3781f02441cace80f09b1564fc6994fa86a177c/torch/distributed/algorithms/ddp_comm_hooks/default_hooks.py#L88), a simpler solution would be to follow through and add that argument to the remaining optimizers. In that case, `ZeroRedundancyOptimizer` does not need to modify its logic to check for an empty parameter list explicitly.

The changes would take place in `functional_adadelta.py`, `functional_adagrad.py`, `functional_adam.py`, `functional_adamax.py`, `functional_adamw.py`, `functional_rmsprop.py`, and `functional_rprop.py`.

cc @vincentqb @iramazanli

**Comment by andwgu** [comment]
cc: @rohan-varma @wanchaol 

I can open a PR for this change later today if you guys agree with this.

**Comment by rohan-varma** [comment]
@andwgu That would be great, thank you!

**Comment by andwgu** [comment]
https://github.com/pytorch/pytorch/pull/62522
