### ISSUE TITLE
[rfc] Consolidate pytorch linter scripts

### ISSUE THREAD

**Issue by 1ntEgr8** [pytorch/pytorch#62499]
Our linter scripts are scattered across numerous ad-hoc scripts. A large part of our linter logic is also encoded inside of `.github/workflows/lint.yml`. These features make it difficult to re-use logic, thereby making it both bug-prone and cumbersome to express more complex linter workflows. Further, ad-hoc scripts do not enable a good user experience, making it harder for users to detect and debug flakiness.

Here are some examples of the mentioned issues:
- File filtering logic
    - https://github.com/pytorch/pytorch/blob/master/tools/actions_local_runner.py#L165-L172
    - https://github.com/pytorch/pytorch/blob/master/tools/linter/clang_tidy/run.py#L376-L460
    - https://github.com/pytorch/pytorch/blob/master/tools/linter/clang_format_all.py#L33-L44
    - https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml
    - https://github.com/pytorch/pytorch/blob/master/tools/linter/clang_format_all.py#L33-L44
- Running shell commands
    - https://github.com/pytorch/pytorch/blob/master/tools/linter/clang_tidy/run.py#L173-L195
    - https://github.com/pytorch/pytorch/blob/master/tools/linter/clang_format_all.py#L57-L59
    - https://github.com/pytorch/pytorch/blob/master/tools/actions_local_runner.py#L105-L130
- Error reporting
    - https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml#L117-L123
    - https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml#L391-L399
- Multiple ways to run lints
    - `make <lint name>`
    - `python3 tools/linter/<linter name>`
    - Commit hooks
    - `python3 tools/actions_local_runner.py <lint name>`
- Dependency requirements are scattered

## Proposal
I'm proposing that we consolidate our linter scripts into a single framework (written in Python) that supports common operations like file filtering, running lints on changes, running shell commands, and reliable error reporting. The lints will be exposed through a dispatcher script that will invoke the appropriate linter and report back results.

Once we have this, we should migrate all of the logic from within `.github/workflows/lint.yml` to this new framework, thereby making python scripts the source of ground truth. The new `.github/workflows/lint.yml` would simply invoke the dispatcher script and report back errors (if any)

### Goals
- Support only one way to run linters
- Make it easier to run lints locally
- Provide an ergonomic way to run lints
- Enable code re-use and linter extensibility

This is how I envision the usage to be:
```bash
alias lint="python3 tools/linter/lint.py"

# Run all lints on the codebase
lint

# Run all lints only on changes
lint --changed-only

# Run a single lint on the codebase
lint mypy

# Run a single lint configured with options
lint clang-tidy --paths torch/csrc --diff-file pr.diff --verbose
```

Once we have this dispatcher script, we can use it to create a `setup.py lint` target, which is advantageous as PyTorch devs use `setup.py` to build their code.

## Implementation

I have a WIP PR (#62393) that implements the aforementioned infrastructure.

It provides a `Lint` base class. Each linter is implemented in a separate module. The module must expose a class that extends the `Lint` base class. Each linter declares the options it accepts (this includes things like file filters, verbose output, extra arguments). The dispatcher script with take the declaration, instantiate the linter, and run it. 

Related issue: #62370

Future vision:
- Possibly release our framework as a separate package
- How can we support existing linter workflows?

@pytorch/pytorch-dev-infra 

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by driazati** [comment]
This also addresses some of #62370 which is cool. One thought about the linter though, IMO the default option should be what people are usually doing, and a full lint takes on the order of several minutes, so I'm thinking we should flip these:

```bash
# Run all lints only on changes
lint
lint --changed-only

# Run all lints on the codebase
lint --full/--all
```

**Comment by seemethere** [comment]
I remember @suo had a PR to do this, is there any update on that?

**Comment by suo** [comment]
Addressed by lintrunner https://github.com/pytorch/pytorch/wiki/lintrunner
