### ISSUE TITLE
find issues in Reproducibility doc

### ISSUE THREAD

**Issue by kyshel** [pytorch/pytorch#62531]
## 📚 Documentation

in [Reproducibility doc page](https://pytorch.org/docs/stable/notes/randomness.html#dataloader), Dataloader section, there is some thing as below :   

![image](https://user-images.githubusercontent.com/11898075/127733946-8601e156-4f72-4360-bca2-77058c697579.png)

Please fix it if it's confirmed. else please explain how is correct. Thanks!

cc @SsnL @VitalyFedyunin @ejguan @brianjo @mruberry

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/62492
