### ISSUE TITLE
rocm build installation fails to false missing component

### ISSUE THREAD

**Issue by gggh000** [pytorch/pytorch#62536]
## 🐛 Bug

During build for rocm, cmake configuration fails due to missing rocclr cmake file but file exists. Various efforts to include that file has not succeeded.
Ubuntu 1804.
ROCM4.2

## To Reproduce

Follow the instruction for rocm, install anaconda and libraries
Install rocm4.2 fully (including rocclr + all dependencies) 
```
(base) root@nonroot-Standard-PC-i440FX-PIIX-1996:/git.co/pytorch# python setup.py build --cmake-only

CMake Error at /opt/anaconda3/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindROCclr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ROCclr", but
  CMake did not find one.

  Could not find a package configuration file provided by "ROCclr" with any
  of the following names:

    ROCclrConfig.cmake
    rocclr-config.cmake

```

cc @malfet @seemethere @walterddr @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by gggh000** [comment]
```
Setting ROCclr=  to this path and doing cmake .. from build directory did not help either:

`(base) root@nonroot-Standard-PC-i440FX-PIIX-1996:/git.co/pytorch/build# cmake ROCclr_DIR=/opt/rocm-4.2.0/rocclr/ ..
`with same error.

**Comment by malfet** [comment]
@gggh000 not sure how ROCm search path are working, but if you want to pass CMAKE variable, you need to do it with `-D` option, i.e. `cmake -DROCclr_DIR=/opt/rocm-4.2.0/rocclr ..`, if instead you want to pass it as environment variable you need to specify it in front of the command, i.e. `ROCclr_DIR=/opt/rocm-4.2.0/rocclr cmake ..`

**Comment by hongxiayang** [comment]
There is no ROCclr dependency for new version pytorch on new version of ROCm. Close this.
