### ISSUE TITLE
Potential mistakes in installation instructions for version 1.8.1 (https://pytorch.org/get-started/locally/)

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#62541]
## 🐛 Bug

Running `pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html` as instructed in the official guide (https://pytorch.org/get-started/locally/) will install 1.9.0 instead of 1.8.1.

## To Reproduce

Just run `pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html`:

```
pip install --no-cache-dir torch torchvision torchaudio -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Collecting torch
  Downloading torch-1.9.0-cp38-cp38-manylinux1_x86_64.whl (831.4 MB)
     |████████████████████████████████| 831.4 MB 179.9 MB/s 
Collecting torchvision
  Downloading torchvision-0.10.0-cp38-cp38-manylinux1_x86_64.whl (22.1 MB)
     |████████████████████████████████| 22.1 MB 46.0 MB/s 
Collecting torchaudio
  Downloading torchaudio-0.9.0-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 47.6 MB/s 
```

## Expected behavior

Version 1.8.1 should be downloaded and installed, not version 1.9.0.

## Environment

Linux with `pip`.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr

**Comment by ezyang** [comment]
related https://github.com/pytorch/pytorch/issues/62590

**Comment by malfet** [comment]
It installs 1.9.0 as it is newer, even though it is not present in the specified channel. For LTS installation instruction correct fix seems to update the instruction to install correct versions.
