### ISSUE TITLE
Document CI label and what they do

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62585]
Ideas:
 - MD file
 - Wiki page (and add link from CONTRIBUTING.MD)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @brianjo @mruberry

**Comment by mruberry** [comment]
A section could be added to: https://github.com/pytorch/pytorch/wiki/Running-and-writing-tests-in-PyTorch-1.9

**Comment by zhouzhuojie** [comment]
Related issue https://github.com/pytorch/pytorch/issues/59818, and we'd like to document all the existing labels.

I'm also thinking to codify all the labels https://github.com/pytorch/pytorch/pull/60798, it helps to have a main place that all the labels are codified. The downside is that it may change how people use to create labels - shifting towards creating PRs to add any new definition of labels.

**Comment by mruberry** [comment]
> Related issue #59818, and we'd like to document all the existing labels.
> 
> I'm also thinking to codify all the labels #60798, it helps to have a main place that all the labels are codified. The downside is that it may change how people use to create labels - shifting towards creating PRs to add any new definition of labels.

Each place it might make sense to show the labels can link to where they're actually documented. I recommend we document them in the Developer Wiki and point people to it. We can change the name of "Running and Writing Tests in PyTorch 1.9" to just "Running and Writing Tests" to keep the links working.

**Comment by samestep** [comment]
> We can change the name of "Running and Writing Tests in PyTorch 1.9" to just "Running and Writing Tests" to keep the links working.

I went ahead and did this (and also updated [@mruberry's comment above](https://github.com/pytorch/pytorch/issues/62585#issuecomment-891205564) and [the wiki homepage](https://github.com/pytorch/pytorch/wiki) to reflect the change). Are there any other pages that link to this which need to be updated?

**Comment by mruberry** [comment]
> > We can change the name of "Running and Writing Tests in PyTorch 1.9" to just "Running and Writing Tests" to keep the links working.
> 
> I went ahead and did this (and also updated [Mike's comment above](https://github.com/pytorch/pytorch/issues/62585#issuecomment-891205564) and [the wiki homepage](https://github.com/pytorch/pytorch/wiki) to reflect the change). Are there any other pages that link to this which need to be updated?

None that I know of. Since the title of the document no longer refers to a specific point in time each section should probably start with the date it was written or the version of PyTorch it refers to. Updating all of them at once isn't a requirement but if updating a section please add this information.

**Comment by samestep** [comment]
I updated [this section](https://github.com/pytorch/pytorch/wiki/Running-and-writing-tests#using-github-label-to-control-ci-behavior-on-pr-last-updated-2021-08-13) to add the `ci/slow-gradcheck` label; I think that's everything, given that [`ci/all` has been removed](https://github.com/pytorch/pytorch-probot/pull/34)? Also, should I open a PR to add another link to this in `CONTRIBUTING.md`?

**Comment by janeyx99** [comment]
Should `ciflow/scheduled` and other ciflow/blah labels be documented in this same note or should there be a different place for those as they don't currently work with Circle (to my understanding)
