### ISSUE TITLE
[v.1.9.1] Release Tracker 

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62586]
We cut a [release branch](https://github.com/pytorch/pytorch/tree/release/1.9) for the 1.9.1 release.

Our plan from this point from this point is roughly:

Phase 1 (until Sep 10th): work on finalizing the release branch
Phase 2 (after Sep 10th): perform extended integration/stability/performance testing based on Release Candidate builds.

This issue is for tracking cherry-picks for changes tagged with [1.9.1 milestone](https://github.com/pytorch/pytorch/milestone/23) into [release/1.9](https://github.com/pytorch/pytorch/tree/release/1.9).

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by xconverge** [comment]
Is there a planned timeline for this release? I have seen the milestone already, thanks!

**Comment by malfet** [comment]
Link to landed master PR: https://github.com/pytorch/pytorch/pull/60059
Link to release branch PR: https://github.com/pytorch/pytorch/pull/64616
Criteria category: Silence warning

**Comment by malfet** [comment]
Link to landed master PR: NA
Link to release branch PR: https://github.com/pytorch/pytorch/pull/64617
Criteria category: Fix CI/build

**Comment by malfet** [comment]
Link to landed master PR: #62290
Link to release branch PR: https://github.com/pytorch/pytorch/pull/64648
Criteria category: Fix CI

**Comment by malfet** [comment]
LInk to landed master PR: #60318
Link to release branch PR: #64651
Criteria category: Silence warning

**Comment by malfet** [comment]
Link to the landed master PR: #62072 
Link to the release branch PR: https://github.com/pytorch/pytorch/pull/64659
Criteria category: Regression from previous release

**Comment by malfet** [comment]
Link to the landed master PR: #62139
Link to the release branch PR: https://github.com/pytorch/pytorch/pull/64677
Criteria category: Regression from previous release

**Comment by malfet** [comment]
Link to the landed master PR: #63953
Link to the release branch PR: https://github.com/pytorch/pytorch/pull/64679
Criteria category: Silence warning

**Comment by malfet** [comment]
Link to the landed master PR: #64036
Link to the release branch PR: #64681
Criteria category: Better error messages

**Comment by malfet** [comment]
Link to the landed master PR: #61394
Link to the release branch PR: #64702 
Criteria category: Regression from the previous release

**Comment by malfet** [comment]
Link to the landed master PR: #61552 
Link to the release branch PR: #64791
Criteria category: Regression from the previous release

**Comment by malfet** [comment]
Link to the landed master PR: #60807 
Link to the release branch PR: #64792
Criteria category: Silence warning

**Comment by malfet** [comment]
Link to the landed master PR: #59409 
Link to the release branch PR: #64796 
Criteria category: Prerequisite refactor for #61294

---
merged

**Comment by malfet** [comment]
Link to the landed master PR: #61127 + #59152 + #61294
Link to the release branch PR: #64797
Criteria category: Aggregate docs + logging update PR

**Comment by malfet** [comment]
Link to the landed master PR: #62378
Link to the release branch PR: #64798
Criteria category: Doc update

---
merged

**Comment by aivanou** [comment]
With `1.9` the TCPStore creation moved to the launcher process for `torch.distributed.launch`.  When `TCPStore` instance is stuck on waiting for response from other workers, it will ignore  SIGINT as described in https://github.com/pytorch/pytorch/issues/63802

**Comment by malfet** [comment]
Link to the landed master PR: #61773
Link to the release branch PR: #64831 
Criteria category: CI fixes

**Comment by malfet** [comment]
Link to the landed master PR: #63910
Link to the release branch PR: #64826
Criteria category: Regression from the previous release

**Comment by malfet** [comment]
Link to landed master PR: NA
Link to the release branch PR: https://github.com/pytorch/pytorch/pull/64971
Criteria category: CI fixes

**Comment by malfet** [comment]
RC2 build is available at https://anaconda.org/pytorch-test/pytorch and https://download.pytorch.org/whl/test/cpu/torch_test.html
