### ISSUE TITLE
[feature request] use mkl_vml.h for exp, log vectorization on CPU

### ISSUE THREAD

**Issue by mingfeima** [pytorch/pytorch#6258]
@cpuhrsch #6192 disables imprecise vectorized function from avx_mathfunc.h
[vml](https://software.intel.com/en-us/mkl-developer-reference-c-vm-mathematical-functions) is a vector math library from MKL, both performance and precision is promised. As long as `mkl` and `mkl-include` is installed in conda, vml can be used in ATen.
@MlWoo was preparing the code previously, the job got interrupted since he is in hospital lately :(
Below is the performance comparison of avx_mathfunc and vml in exp. Though the performance improvement is not so much, the precision is guaranteed.
if this looks ok to you, we will continue the job, after @MlWoo finish his therapy anyway.
```
avx_mathfunc.h
exp:            size: 10^2      elapsed avg: 0.00018437 variance: 0.00002326    type: torch.FloatTensor
exp:            size: 10^3      elapsed avg: 0.00051801 variance: 0.00012947    type: torch.FloatTensor
exp:            size: 10^4      elapsed avg: 0.00399129 variance: 0.00030216    type: torch.FloatTensor
exp:            size: 10^5      elapsed avg: 0.05558920 variance: 0.00430511    type: torch.FloatTensor

vml
exp:            size: 10^2      elapsed avg: 0.00004063 variance: 0.00001652    type: torch.FloatTensor
exp:            size: 10^3      elapsed avg: 0.00048499 variance: 0.00003081    type: torch.FloatTensor
exp:            size: 10^4      elapsed avg: 0.00325508 variance: 0.00007704    type: torch.FloatTensor
exp:            size: 10^5      elapsed avg: 0.04254997 variance: 0.00301427    type: torch.FloatTensor

```

**Comment by apaszke** [comment]
@mingfeima that sounds like a nice addition! Please only remember that it would have to remain an optional, albeit recommended, path.

**Comment by cpuhrsch** [comment]
Hello @mingfeima, I hope @MlWoo is doing well and will feel good again soon! 

This looks great! I didn't know MKL also included this, given that there's also [SVML](https://software.intel.com/en-us/node/524289).

**Comment by colesbury** [comment]
I would prefer integrating an open-source library rather than additional proprietary libraries as long as performance is similar. https://github.com/shibatch/sleef in particular looks promising. (I believe it's under review for inclusion into LLVM)

VML, if I remember correctly, used to always execute the slow path on AMD CPUs [1](http://www.agner.org/optimize/blog/read.php?i=49). @mingfeima is this still the case?

**Comment by mingfeima** [comment]
@apaszke well noticed, if we do it, it will be an optional, albeit recommended, path

@cpuhrsch SVML provides similar functionality, but it is not under MKL, it is a icc submodule. Once you have mkl installed via conda, you have VML. Only in case you have icc installed, you have SVML. So based on current pytorch dependency `conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing`, VML is a better option than SVML.

@colesbury if the open source library [sleef](https://github.com/shibatch/sleef) provides similar performance and also precision is guaranteed, it's going to be the best. Have you started work on that?

**Comment by cpuhrsch** [comment]
@mingfeima I'm looking into sleef next after what I'm currently working on.
