### ISSUE TITLE
Fix libtorch testing for MacOS

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62598]
LIBTORCH testing for MacOS has not been exercised for a while.

From the [pytorch_macos_10_13_py3_test log](
https://app.circleci.com/pipelines/github/pytorch/pytorch/358717/workflows/a3a89639-d709-4acf-a0f8-e06de59c02fb/jobs/15131272):
```
Aug 02 16:55:37 + test_libtorch
Aug 02 16:55:37 + [[ 0 == \1 ]]
```

It was recently re-enabled by 
https://github.com/pytorch/pytorch/pull/62402
Which caused test failures, for example https://app.circleci.com/pipelines/github/pytorch/pytorch/358742/workflows/de4974ac-606e-4d63-aff7-15ef361ea3f7/jobs/15132419

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @albanD

**Comment by seemethere** [comment]
We're not currently running libtorch tests anymore for our nightly / release binary workflows. Users haven't reported issues yet so I'm assuming that these binary tests weren't actually important in the first place. Closing, feel free to re-open if the problem resurfaces.
