### ISSUE TITLE
[Caffe2] CRITICAL:root:Cannot load caffe2.python. Error

### ISSUE THREAD

**Issue by ambigus9** [pytorch/pytorch#6259]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: Caffe2
- OS: Ubuntu 16.04
- PyTorch version: ?
- How you installed PyTorch (conda, pip, source): source
- Python version: Python 3.6.3
- CUDA/cuDNN version: 8.0.61/7.1.1
- GPU models and configuration: Nvidia GTX 1050Ti
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.5.1
- Build command you used (if compiling from source): cmake .. && sudo make install
- Versions of any other relevant libraries: ?

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do
When I try to import core from caffe2, I got this errors:

```
miguel@familia-plazas:/$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /home/miguel/pytorch/build/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct
CRITICAL:root:Cannot load caffe2.python. Error: /home/miguel/pytorch/build/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct
```
Here is another relevant information that I think must help to understand my problem:

```
$ which python
/home/miguel/anaconda3/bin/python
$ python --version
Python 3.6.3 :: Anaconda custom (64-bit)
$ echo $PYTHONPATH
:/home/miguel/pytorch/build
$ echo $PATH
/usr/local/cuda-8.0/bin:/home/miguel/anaconda3/bin:/home/miguel/anaconda2/bin:/home/miguel/bin:/home/miguel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64
```
Thanks for any help!

**Comment by Yangqing** [comment]
This is probably some python dependency issue. Similar one reported in another repo here:

https://github.com/deepmind/lab/issues/13

you can probably strace the run and see what libpython.so library got loaded.

**Comment by pprp** [comment]
# Caffe2 python run does not have GPU support

### system info

- PyTorch or Caffe2: Caffe2
- OS: ubuntu16.04
- How I installed Caffe2: source
- Python version: python 3.6.0
- CUDA/cuDNN version:8.0.61/7.0.5
- GPU models and configuration:Nvidia GTX 1080
- GCC version:5.4.0
- cmake version: 3.5.1
- miniconda

### What I did

- I have tried to build caffe2 from source (following [this](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support)):

After I installed the dependencies on that page and clone the repository, I run this command `FULL_CAFFE2=1 python setup.py install`. I test `from caffe2.python import core` and I got `Failure`

- Then I find a solution in github [following this(@kaisark)](https://github.com/pytorch/pytorch/issues/6259)

I passed the test and got Success but I found it doesn't support GPU.

### Test caffe2 python core

```
(cf2) caffe@learner-pc:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
>>>
```

### Relavent Information

```
(cf2) caffe@learner-pc:~$ which python
/home/caffe/miniconda3/envs/cf2/bin/python
(cf2) caffe@learner-pc:~$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
(cf2) caffe@learner-pc:~$ echo $PYTHONPATH

(cf2) caffe@learner-pc:~$ echo $PATH
/home/caffe/miniconda3/envs/cf2/bin:/home/caffe/bin:/home/caffe/.local/bin:/sbin:/home/caffe/miniconda3/bin:/usr/local/cuda-8.0/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/local/protobuf/bin
(cf2) caffe@learner-pc:~$ echo $LD_LIBRARY_PATH
/usr/local/lib:/usr/local/cuda-8.0/lib64::/usr/local/protobuf/lib:/home/caffe/github/nccl/build/lib
(cf2) caffe@learner-pc:~$
```

### Thanks for any help!

**Comment by pjh5** [comment]
@pprp if you're still encountering this then please open a new issue. This is separate from the orignal issue of this threa.

**Comment by TanLingxiao** [comment]
Ubuntu16.04  Anaconda3.6  pytorch1.0

You envirenment path(such as .bashrc) must add:
```
export PATH="/home/xxxxx/anaconda3/bin:$PATH"
export PYTHONPATH="$PYTHONPATH:/home/xxxxx/pytorch/build"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
```

Then if you run `python caffe2/python/operator_test/activation_ops_test.py` in pytorch file ,the error will happen because of file conflict.You can run `python python/operator_test/activation_ops_test.py` in ~/pytorch/caffe2/ and will be success.

**Comment by Lineldor** [comment]
> Ubuntu16.04 Anaconda3.6 pytorch1.0
> 
> You envirenment path(such as .bashrc) must add:
> 
> ```
> export PATH="/home/xxxxx/anaconda3/bin:$PATH"
> export PYTHONPATH="$PYTHONPATH:/home/xxxxx/pytorch/build"
> export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
> ```
> Then if you run `python caffe2/python/operator_test/activation_ops_test.py` in pytorch file ,the error will happen because of file conflict.You can run `python python/operator_test/activation_ops_test.py` in ~/pytorch/caffe2/ and will be success.

Your advice perfectly solved my problem!
