### ISSUE TITLE
[feature request] Implement CI testing of installation commands

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#62590]
It seems that `-c conda-forge` is needed.

Context: https://github.com/pytorch/vision/issues/4240#issuecomment-891224050

It would be nice if official installation commands could be tested somehow. It seems that it's broken for at least one month since https://github.com/pytorch/vision/issues/4071#issuecomment-865079895. It also would be nice if it was foolproof, e.g. if binaries for torchvision/torchaudio included a code that showed a big warning with URL to docs if it's being imported with a too new PyTorch (e.g. torchvision 0.2.2 bits would detect torch 1.9.0 and show a warning explaining probably installation problems)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra @brianjo @mruberry

**Comment by malfet** [comment]
It looks like installation instructions are wrong for all python-3.9 + torchvision combinations:
```
$ conda install torchvision==0.10.0 cpuonly -c pytorch
....
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - torchvision==0.10.0 -> python[version='>=2.7,<2.8.0a0']

Your python: python=3.9
```

And looks like the culprit is spurious `  - python_abi` dependency, which is present in domain libraries builds:
```
$ conda search 'torchvision[channel=pytorch,subdir=linux-64,version=0.10.0,build=py39_cpu]' --info
Loading channels: done
torchvision 0.10.0 py39_cpu
---------------------------
file name   : torchvision-0.10.0-py39_cpu.tar.bz2
name        : torchvision
version     : 0.10.0
build       : py39_cpu
build number: 0
size        : 6.9 MB
license     : BSD
subdir      : linux-64
url         : https://conda.anaconda.org/pytorch/linux-64/torchvision-0.10.0-py39_cpu.tar.bz2
md5         : 79327462c158050983a426a1b167059f
timestamp   : 2021-06-15 15:44:03 UTC
dependencies: 
  - ffmpeg >=4.2
  - jpeg <=9b
  - libpng
  - pillow >=5.3.0
  - python >=3.9,<3.10.0a0
  - python_abi 3.9.* *_cp39
  - pytorch 1.9.0
```

**Comment by malfet** [comment]
Following [ugly script](https://gist.github.com/malfet/932311d0e7321cfdeed9e814a759b84e) could be used to remove `python_abi` dependency from domain library packages build against 3.9 and thus eliminating the need for `conda-forge` channel, which I've tested by downloading packages from my own channel:
```
 conda install torchvision==0.10.0 cpuonly -c malfet -c pytorch
```
@seemethere , please consider running above-mentioned script against python-3.9 domain libraries conda packages and re-uploading them to the `pytorch` channel.

**Comment by seemethere** [comment]
Removing high priority and adding to the 1.10 milestone

**Comment by malfet** [comment]
First step towards the goal: move install commands to a .json file in https://github.com/pytorch/pytorch.github.io and autogenerate .js and previon_installs from that json file

**Comment by vadimkantorov** [comment]
I think there should also be testing for download URLs (cron-based, every day or every 6 hours):
https://github.com/pytorch/pytorch/issues/64080

**Comment by malfet** [comment]
Partially addressed by https://github.com/pytorch/pytorch.github.io/pull/837

**Comment by vadimkantorov** [comment]
Also, I noticed sometimes there are differences between miniconda and conda release

**Comment by malfet** [comment]
> Also, I noticed sometimes there are differences between miniconda and conda release

@vadimkantorov can you please elaborate when do you mean? Same command might work in miniconda but fail on conda? Or that command syntax should be different.

**Comment by vadimkantorov** [comment]
Yes. I think it may happen because the full conda can have older package versions. I'm always using miniconda, but knowing compatibility with main conda releases may be useful for someone else (?)

**Comment by vadimkantorov** [comment]
It would be nice if it published some status.pytorch.org page detailing the test matrix: OS and which smoke install commands it tried.

**Comment by vadimkantorov** [comment]
@malfet Is it right that the CPU installation commands are different for Linux and Windows?

Windows line misses `index-url`. Are these installation lines CI auto-tested?

Linux:
<img width="516" alt="image" src="https://github.com/pytorch/pytorch/assets/1041752/f9c96d7e-4d11-4f32-a0bc-ce6b76770ee2">

Windows:
<img width="521" alt="image" src="https://github.com/pytorch/pytorch/assets/1041752/fde1360c-2915-4c3d-8a58-4cea52943b10">

**Comment by malfet** [comment]
> @malfet Is it right that the CPU installation commands are different for Linux and Windows?

@vadimkantorov Yes, this is correct: Linux PYPI binaries are CUDA capable, while Window are not, so Linux CPU wheels are hosted on download.pytorch.org, while Windows aren't. You'll see the same discrepancy but inverse for CUDA-11.77



> Windows line misses `--index-url`. Are these installation lines CI auto-tested? 
Yes, they are


> Maybe even if `--index-url` are not required for Windows, it might be good to have it anyways for unification/consistency
This will force downloads from our mirror rather than pypi, who I think is not a desired outcome.

**Comment by vadimkantorov** [comment]
Maybe adjust the Windows installation command as:

`python -m pip install torch torchvision torchaudio # Windows binaries only exist as CPU-only, so no need for --index-url` or sth along these lines?
