### ISSUE TITLE
https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#pre-commit-tidylinting-hook seems out-of-date

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/pytorch#62629]
## 🐛 Bug

https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#pre-commit-tidylinting-hook seems out-of-date

## To Reproduce

1. Visit https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#pre-commit-tidylinting-hook seems out-of-date.
2. Saw `ln -s ../../tools/git-pre-commit .git/hooks/pre-commit`

## Expected behavior

The above command should work.

cc @brianjo @mruberry

**Comment by malfet** [comment]
Can you please elaborate, what is not working for you?

**Comment by alanwaketan** [comment]
For `ln -s ../../tools/git-pre-commit .git/hooks/pre-commit`, it doesn't seem to state where the current directory should be. '../../' is very confused.

**Comment by malfet** [comment]
Well, this is how symlinks work. If you are in `pytorch` repo root directory, to create a symlink in `.git/hooks/pre-commit`, pointing to `tools/git-pre-commit`, it should be prefixed with `../..`

**Comment by alanwaketan** [comment]
> Well, this is how symlinks work. If you are in `pytorch` repo root directory, to create a symlink in `.git/hooks/pre-commit`, pointing to `tools/git-pre-commit`, it should be prefixed with `../..`

Oops, my bad. I got used to the absolute path convention, and therefore I was confused about this relative path usage.
