### ISSUE TITLE
torch.nn.AvgPool2d `divisor_override` described wrongly.

### ISSUE THREAD

**Issue by kylematoba** [pytorch/pytorch#62636]
## 📚 Documentation

https://pytorch.org/docs/stable/generated/torch.nn.AvgPool2d.html writes
```
divisor_override – if specified, it will be used as divisor, otherwise kernel_size will be used
```
which implies that  `torch.nn.AvgPool2d(2, divisor_override=2)` should be equivalent to `torch.nn.AvgPool2d(2)` (which it is not). 
```
torch.nn.AvgPool2d(2)(torch.ones(1, 4, 4))
tensor([[[1., 1.],
         [1., 1.]]])
torch.nn.AvgPool2d(2, divisor_override=2)(torch.ones(1, 4, 4))
tensor([[[2., 2.],
         [2., 2.]]])
```
I suggest using something like the more correct explanation given here:
https://pytorch.org/docs/stable/generated/torch.nn.functional.avg_pool2d.html.

cc @brianjo @mruberry @albanD @jbschlosser @heitorschueroff

**Comment by jbschlosser** [comment]
Thanks for reporting this, @kylematoba! We'd accept a PR implementing the fix to match the wording in the functional form docs.
