### ISSUE TITLE
v1.9.0 branch clashes with tag of the same name

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#62657]
## 🐛 Bug

Recently a branch named `v1.9.0` was created which makes it almost impossible to checkout the tagged release.

Furthermore the v1.9.0 branch is not at the state of the 1.9.0 release which means the whole name is wrong and the branch should be released ASAP!

This causes actual issues with downstream consumers, build scripts on HPC system and so on.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by zou3519** [comment]
Marking hi-pri for urgency. I don't know if that branch can be deleted or not, maybe @malfet would know?

**Comment by malfet** [comment]
@Flamefire thank you for notifying, looking

**Comment by malfet** [comment]
Deleted.
