### ISSUE TITLE
[Distributed PyTorch] Gloo hang at the initialization 

### ISSUE THREAD

**Issue by KaiyuYue** [pytorch/pytorch#6267]
I change the issue, the problem before is solved. Sorry to bother. The only problem is this runtime error:
```
Traceback (most recent call last): 
File "dist_m.py", line 881, in 
Traceback (most recent call last): 
File "dist_m.py", line 881, in 
dist_main() 
dist_main() 
File "dist_m.py", line 421, in dist_main 
File "dist_m.py", line 421, in dist_main 
model = modules.build_model(args) 
model = modules.build_model(args) 
File "/home/slurm/job/tmp/job-21086/modules.py", line 134, in build_model 
groups = args.groups 
File "/home/slurm/job/tmp/job-21086/models/c_resnet_1_nl.py", line 873, in resnet50 
File "/home/slurm/job/tmp/job-21086/modules.py", line 134, in build_model 
groups = args.groups 
File "/home/slurm/job/tmp/job-21086/models/c_resnet_1_nl.py", line 873, in resnet50 
model = torch.nn.parallel.DistributedDataParallel(model.cuda(), device_ids=device_ids) 
model = torch.nn.parallel.DistributedDataParallel(model.cuda(), device_ids=device_ids) 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 97, in __init__ 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 97, in __init__ 
dist.broadcast(p, 0) 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/distributed/__init__.py", line 290, in broadcast 
dist.broadcast(p, 0) 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/distributed/__init__.py", line 290, in broadcast 
return torch._C._dist_broadcast(tensor, src, group) 
RuntimeError: Invalid broadcastT function type 
return torch._C._dist_broadcast(tensor, src, group) 
RuntimeError: Invalid broadcastT function type 
terminate called after throwing an instance of 'gloo::EnforceNotMet' 
what(): [enforce fail at /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down 
terminate called after throwing an instance of 'gloo::EnforceNotMet' 
what(): [enforce fail at /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down 
```
So, What is the type of tensor not supported by gloo? I check my code, the types of functions I use include `torch.scatter_add_()`, `torch.gather()`, `torch.addcmul()`,  and `fft function` from [here](https://github.com/locuslab/pytorch_fft). Is it `fft functions` not supported?

**Comment by teng-li** [comment]
@KaiyuYue  was this hang for nccl backend or gloo backend, your repo script uses gloo.

**Comment by KaiyuYue** [comment]
Hi, @teng-li , the choice of backend is according to the [doc](http://pytorch.org/docs/master/distributed.html#torch.distributed.init_process_group), which has three backends, `mpi`, `tcp` and `gloo`. I try to change the backend into `nccl`, it will give the error: `RuntimeError: _Map_base::at`.

**Comment by KaiyuYue** [comment]
Hi, @apaszke @teng-li @ailzhang :

I use `gloo` as the backend. It gives an error:
```
Traceback (most recent call last): 
File "dist_m.py", line 881, in 
Traceback (most recent call last): 
File "dist_m.py", line 881, in 
dist_main() 
dist_main() 
File "dist_m.py", line 421, in dist_main 
File "dist_m.py", line 421, in dist_main 
model = modules.build_model(args) 
model = modules.build_model(args) 
File "/home/slurm/job/tmp/job-21086/modules.py", line 134, in build_model 
groups = args.groups 
File "/home/slurm/job/tmp/job-21086/models/c_resnet_1_nl.py", line 873, in resnet50 
File "/home/slurm/job/tmp/job-21086/modules.py", line 134, in build_model 
groups = args.groups 
File "/home/slurm/job/tmp/job-21086/models/c_resnet_1_nl.py", line 873, in resnet50 
model = torch.nn.parallel.DistributedDataParallel(model.cuda(), device_ids=device_ids) 
model = torch.nn.parallel.DistributedDataParallel(model.cuda(), device_ids=device_ids) 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 97, in __init__ 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/distributed.py", line 97, in __init__ 
dist.broadcast(p, 0) 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/distributed/__init__.py", line 290, in broadcast 
dist.broadcast(p, 0) 
File "/home/slurm/job/tmp/job-21086/anaconda2/lib/python2.7/site-packages/torch/distributed/__init__.py", line 290, in broadcast 
return torch._C._dist_broadcast(tensor, src, group) 
RuntimeError: Invalid broadcastT function type 
return torch._C._dist_broadcast(tensor, src, group) 
RuntimeError: Invalid broadcastT function type 
terminate called after throwing an instance of 'gloo::EnforceNotMet' 
what(): [enforce fail at /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down 
terminate called after throwing an instance of 'gloo::EnforceNotMet' 
what(): [enforce fail at /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249] error == cudaSuccess. 29 vs 0. Error at: /home/yuekaiyu/code/distributed-pytorch/distributed-pytorch-0.4.0/pytorch/torch/lib/gloo/gloo/cuda.cu:249: driver shutting down 
```

**Comment by teng-li** [comment]
@KaiyuYue yeah, 0.3.x doesn't have nccl backend support yet.  

That error you were seeing mean that that your tensor is not a supported type for gloo broadcast operation in distributed training. 

The only supported data types are Float and Double.

**Comment by KaiyuYue** [comment]
@teng-li 
Really thanks. The functions, like `torch.scatter_add_()`, `torch.gather()`, need the `LongTensor` as their indexes, so I init these long tensors first in the `class __init__`. 

I init them as Float Tensor first, when passing them into functions as the indexes, I convert them type as LongTensor. It should work well. I will close this issue.

**Comment by fmassa** [comment]
I should say I have also experienced deadlocks with `DistributedDataParallel`, but only after hours of training. I'm running some experiments again with `NCCL_DEBUG=INFO` TO se if I get more information on the deadlock

**Comment by KaiyuYue** [comment]
Thanks for the quick reply and thanks for investigating it, @fmassa .  More environmental infos: anaconda2 + torch_0.3.1 installed from pip. When start training, dataloader works well and will feed the data into gpus, after fill a batch to do the first forward or maybe backward procedure, the workers of dataloader will stop and the whole training hangs.

**Comment by fmassa** [comment]
My training deadlocked again, but this time I had some information that was printed by `NCCL_DEBUG=INFO python myscript.py`. I got the following message repeated over and over:

```
transport/net_ib.cu:61 WARN IB Got async event : (null)
```

A quick search on google didn't return anything.

**Comment by fmassa** [comment]
Ah, you are using gloo, so it's probably a different issue, as I'm using NCCL2

**Comment by KaiyuYue** [comment]
Is there a possible that the problem is existed somewhere rather than `gloo` and `nccl2`?

**Comment by fmassa** [comment]
I don't know, but @teng-li knows more than I do

**Comment by teng-li** [comment]
@fmassa I think your problem is different from @KaiyuYue 's problem since he is using Gloo backend.

**Comment by teng-li** [comment]
@KaiyuYue

**Comment by KaiyuYue** [comment]
Hi, @teng-li:

The number of data loader workers I used is `4 * (gpu_nums per single_machine)`, our single machine has 8 gpus, so it is 32. 

According to the [doc](http://pytorch.org/docs/master/notes/multiprocessing.html#sharing-cuda-tensors) about multiprocessing, I add these codes at the beginning of `train.py`:
```python
import multiprocessing as mp
try:
    mp.set_start_method('spawn') # spawn, forkserver, and fork
except RuntimeError:
    pass
```
and try the different methods (spawn, forkserver, and fork) with using `torch.nn.parallel.DistributedDataParallel`. No good news, training still fails. 

Moreover, I change the data loader workers into `1`, as the same result that they can't work.

**Comment by teng-li** [comment]
Can you try 0 data load worker to see if it works. I still think this is dataloader worker related

**Comment by KaiyuYue** [comment]
Setting wokers number as 0 still fails.

**Comment by KaiyuYue** [comment]
Hi, @fmassa, I have a quick question. I use three machines to do the distributed task, as the [doc](http://pytorch.org/docs/0.3.1/distributed.html#basics) said, it provides the `synchronous ` distributed training. In my practical experiments, it seems like that each machine does its own training and epoch number of three machines cannot be synced to be the same. So I want to ask when does the master rank machine gather the gradients of three machines? Or I have the error in my distributed training. Thanks.

**Comment by teng-li** [comment]
@KaiyuYue Could you get the gdb backtrace of all the thread of the process that got stuck

**Comment by KaiyuYue** [comment]
Hi, @teng-li @zou3519 Really sorry. Recently, the resources of our cluster are always insufficient for distributed debug. I will I try my best to reply as soon as possible.

**Comment by marcociccone** [comment]
Hi, I have the same issue. My program hangs when I call `dist.init_process_group`. Can someone help me to debug this problem? Thanks!

**Comment by pietern** [comment]
This issue hasn't been updated in more than a year -- closing it.
