### ISSUE TITLE
no file build_host_protoc.bat in repo

### ISSUE THREAD

**Issue by IgorKasianenko** [pytorch/pytorch#6268]
Hello,
I'm installing [Caffe2](https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile) on Windows 10 via instructions.
There is no file in entire repo.

> browse to the repo’s \caffe2\scripts folder and execute:
> 
>     build_host_protoc.bat, which will build protobuf from source for your system.

P.S. `build_windows.bat` has moved from \caffe2\scripts to pytorch\scripts.

**Comment by pjh5** [comment]
The script it's looking for is https://github.com/pytorch/pytorch/blob/master/scripts/build_host_protoc.sh . The "caffe2" in "\caffe2\scripts" is referring to the top level name of the entire github repo, which is now pytorch. I will update the instructions to be a little clearer.
