### ISSUE TITLE
Preserve complex objects in torch.jit.freeze

### ISSUE THREAD

**Issue by kev-zheng** [pytorch/pytorch#62694]
## 🐛 Bug

I attempt to freeze and preserve an attribute that is an object of a custom class. During loading, it seems that TorchScript relies on the defined class. If it does not exist, I get `classTypeINTERNAL ASSERT FAILED`.

## To Reproduce

Produce `frozen-test.pt` with this example file:
```
import torch
import torch.nn as nn
import torch.fx

@torch.jit.script
class Helper:
    @torch.jit.export
    def hello(self):
        print("hello")

class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.helper = Helper()

    def forward(inputs: torch.Tensor) -> torch.Tensor:
        return torch.zeros(1,1,1)


m = M()
m.helper.hello()

m.eval()

scripted = torch.jit.script(m)
frozen = torch.jit.freeze(scripted, preserved_attrs=['helper'])
torch.jit.save(frozen, 'frozen-test.pt')

test = torch.jit.load('frozen-test.pt')
test.helper.hello()
```

Reproduce error here:
```
import torch

m = torch.jit.load('frozen-test.pt')

m.helper.hello()
```

Error msg:
```
Traceback (most recent call last):
  File "test_load_freeze.py", line 5, in <module>
    m.helper.hello()
  File "/Users/kevzheng/conda/envs/ctrldev/lib/python3.6/site-packages/torch/jit/_script.py", line 659, in __getattr__
    return self._c.getattr(attr)
RuntimeError: classTypeINTERNAL ASSERT FAILED at "/Users/distiller/project/conda/conda-bld/pytorch_1623459046073/work/torch/csrc/jit/python/pybind_utils.h":761, please report a bug to PyTorch.
```

## Expected behavior

Not sure, any idea if this is expected to be supported, any workarounds that we can use, etc.?

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): OSX
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6.10
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

cc @gmagogsfm

**Comment by eellison** [comment]
This doesn't error for me on master, closing.
