### ISSUE TITLE
[feature request] rot90 like numpy.rot90

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#6271]
Requested here: https://discuss.pytorch.org/t/how-to-convert-an-image-with-dimensionality-hxwxc-to-cxhxw/15690/3

**Comment by apaszke** [comment]
Isn’t this just permute?

**Comment by zou3519** [comment]
The thread discussion is mostly about permute, but a user requested that we have https://docs.scipy.org/doc/numpy/reference/generated/numpy.rot90.html as well, which I think is not a permute.

**Comment by vkhalidov** [comment]
`rot90(a)` is equivalent to `transpose(flip(a))`. `transpose` is `permute`, so this should be closely related to https://github.com/pytorch/pytorch/issues/229
