### ISSUE TITLE
`torch.fft.fft()` runtime error on Apple silicon

### ISSUE THREAD

**Issue by 0jg** [pytorch/pytorch#62723]
## 🐛 Bug

It appears as if MKL is not compatible with Apple silicon/M1 processors (and unsurprisingly so!)  When running a project with `torch.fft.fft()`, the program exists with a runtime error.

where `x` is the input to a custom function in the neural network. 

## To Reproduce

1. Run any neural network with a fast Fourier transform

```
Traceback (most recent call last):
  File "/Users/jack/Desktop/torch/gpe1d.py", line 539, in <module>
    out = model(x)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jack/Desktop/torch/gpe1d.py", line 417, in forward
    x1 = self.conv0(x)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/3.9.2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jack/Desktop/torch/gpe1d.py", line 367, in forward
    x_ft = torch.fft.fft(x)
RuntimeError: fft: ATen not compiled with MKL support
```
## Expected behavior

The code should run without any runtime error, successfully calculating the Fourier transform of the input.

## Environment

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.3.1 (arm64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30)  [Clang 11.0.1 ] (64-bit runtime)
Python platform: macOS-11.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.9.0
[conda] numpy                     1.21.0           py39h1f3b974_0    conda-forge
[conda] torch                     1.9.0                    pypi_0    pypi

cc @malfet @mruberry @peterbell10 @walterddr

**Comment by ezyang** [comment]
cc @malfet I could have sworn we already had an issue on this but I couldn't find it

**Comment by malfet** [comment]
@ezyang because it is closed :) (if you are referring to https://github.com/pytorch/pytorch/issues/62107)

This functionality is missing in PyTorch-1.9.0, but should be fixed by #60976 and enabled in nightlies by #62222

**Comment by malfet** [comment]
Closing, as it indeed works with latest nightlies:
```
% python -c "import os;import torch;print(os.uname().machine, torch.__version__, torch.fft.fft(torch.randn(3,3)))"
arm64 1.10.0.dev20210804 tensor([[ 1.6039+0.0000j,  2.1311-2.3638j,  2.1311+2.3638j],
        [-3.7320+0.0000j, -1.4912-2.4378j, -1.4912+2.4378j],
        [ 2.3642+0.0000j, -2.9835-0.8265j, -2.9835+0.8265j]])
```

**Comment by 0jg** [comment]
Magic, thank you!!
