### ISSUE TITLE
Wrapper-based torch_dispatch objects report maybe incorrect device

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#62730]
This is possibly intentional?

Using [LoggingTensor](https://github.com/pytorch/pytorch/blob/master/test/test_python_dispatch.py),
```
x = LoggingTensor(torch.empty([]))
print(x.device)
# prints "meta"
```
The extension writer can add a .device attribute to their class (LoggingTensor) to solve the problem in Python-land but it doesn't solve the problem in C++ land. In C++ land `x.options()` will return a meta device and there is code like [toType](https://github.com/pytorch/pytorch/blob/34c9f5a8dad74ba23de5c2fba9d071a6c2dd1fa4/aten/src/ATen/templates/TensorBody.h#L371-L373) that will use the device to do things.

cc @ezyang @bdhirsh

**Comment by ezyang** [comment]
Yes, this is "intentional". If you want it to report as CPU, you have to pass an honest to goodness cpu tensor to `make_subclass`. This part is a big soft and maybe someone has a better idea about what to do instead.

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/issues/62972 gives an alternative, which is to let people set device='cpu' even though there is nothing in the storage
