### ISSUE TITLE
int8 linear is slower than fp32 linear

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#62804]
## Problem description
Int8 qlinear is found to be slower than fp32 linear for some shapes of input and weight.
The profiler shows that quantized::linear costs more CPU time than aten::linear.
Example: 
M, N, K = 1, 64, 32
Run in a loop for 100 times
```
----- FBGEMM int8 qlinear -----
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                             Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                quantized::linear        81.03%       3.849ms       100.00%       4.750ms      47.501us           100
                    aten::q_scale         5.58%     264.973us         5.58%     264.973us       2.650us           100
    aten::_empty_affine_quantized         4.64%     220.210us         4.64%     220.210us       2.202us           100
                    aten::resize_         3.97%     188.708us         3.97%     188.708us       1.887us           100
                      aten::empty         3.07%     145.993us         3.07%     145.993us       1.460us           100
               aten::q_zero_point         1.71%      81.002us         1.71%      81.002us       0.810us           100
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 4.750ms

----- fp32 linear -----
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
                Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
        aten::linear        13.42%     187.879us       100.00%       1.400ms      14.002us           100
         aten::addmm        40.75%     570.570us        58.48%     818.857us       8.189us           100
             aten::t        16.67%     233.432us        28.10%     393.441us       3.934us           100
     aten::transpose         7.00%      98.010us        11.43%     160.009us       1.600us           100
        aten::expand         6.48%      90.695us         9.27%     129.810us       1.298us           100
         aten::copy_         8.46%     118.477us         8.46%     118.477us       1.185us           100
    aten::as_strided         7.22%     101.114us         7.22%     101.114us       0.506us           200
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.400ms
```

## To Reproduce

1. Copy the code below to a script and name it `profile_linear.py`;
1. (Optional) Set `OMP_NUM_THREADS`: `export OMP_NUM_THREADS=<num of threads>`
1. Run it by `python profile_linear.py`;
1. Check the results.

```python
import torch
from torch import nn

# Define parameters
M, N, K = 1, 64, 32 # 156800, 16, 36

x = 2*torch.randn((M, K), dtype=torch.float)+2
x_scale = 1.2
x_zero_point = 0

w = 2*torch.randn((N, K), dtype=torch.float)
w_scale = 0.2
w_zero_point = 0

bias_float = 3*torch.randn(N, dtype=torch.float)+1

y_scale = 4.2
y_zero_point = 0

# Prepack weight
def prepack_weight(qw):
    return torch.ops.quantized.linear_prepack(qw, bias_float)

# Do qlinear
def linear(qx, w_packed):
    return torch.ops.quantized.linear(qx, w_packed, y_scale, y_zero_point)

run_round = 100

##### int8 #####
# Specify qengine
torch.backends.quantized.engine = 'fbgemm'
# Quantize x, w and prepack w
qx = torch.quantize_per_tensor(x, scale=x_scale, zero_point=x_zero_point, dtype=torch.quint8)
qw = torch.quantize_per_tensor(w, scale=w_scale, zero_point=w_zero_point, dtype=torch.qint8)
w_packed = prepack_weight(qw)

# do qlinear and profiling
with torch.autograd.profiler.profile(use_cuda=False) as prof:
    for i in range(run_round):
        linear_ret = linear(qx, w_packed)

prof.export_chrome_trace('fbgemm-int8-linear.json')
table_res = prof.key_averages().table(sort_by="cpu_time_total")
print('----- FBGEMM int8 qlinear -----')
print(table_res)


##### fp32 #####
m = nn.Linear(K, N)
input = torch.randn(M, K)

with torch.autograd.profiler.profile(use_cuda=False) as prof:
    for i in range(run_round):
        out = m(input)

prof.export_chrome_trace('fp32-linear.json')
table_res = prof.key_averages().table(sort_by="cpu_time_total")
print('----- fp32 linear -----')
print(table_res)

```

## Expected behavior

Quantized op is faster.

## Environment

PyTorch version: 1.10.0a0+git64b3ab6
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: glibc-2.17

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.0a0+git64b3ab6
[pip3] torch-ipex==1.2.0
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.10.0a0+git64b3ab6          pypi_0    pypi
[conda] torch-ipex                1.2.0                    pypi_0    pypi

## Additional context

cc @VitalyFedyunin @ngimel @heitorschueroff @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
Thanks for reporting. @dskhudia do we have any prior insights as to why these shapes may perform worse on FBGEMM? Any workarounds?

**Comment by dskhudia** [comment]
I tried it on a benchmark machine with turbo-off and the following are the results I see. 

----- FBGEMM int8 qlinear -----
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                             Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                quantized::linear        73.10%       1.228ms       100.00%       1.680ms      16.800us           100
    aten::_empty_affine_quantized         9.64%     162.000us         9.64%     162.000us       1.620us           100
                    aten::resize_         6.31%     106.000us         6.31%     106.000us       1.060us           100
                      aten::empty         4.11%      69.000us         4.11%      69.000us       0.690us           100
                    aten::q_scale         4.05%      68.000us         4.05%      68.000us       0.680us           100
               aten::q_zero_point         2.80%      47.000us         2.80%      47.000us       0.470us           100
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.680ms

----- fp32 linear -----
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
                Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
        aten::linear        13.10%     259.000us       100.00%       1.977ms      19.770us           100
         aten::addmm        39.35%     778.000us        55.94%       1.106ms      11.060us           100
             aten::t        13.40%     265.000us        30.96%     612.000us       6.120us           100
     aten::transpose        14.92%     295.000us        17.55%     347.000us       3.470us           100
        aten::expand         8.75%     173.000us        10.12%     200.000us       2.000us           100
         aten::copy_         6.47%     128.000us         6.47%     128.000us       1.280us           100
    aten::as_strided         4.00%      79.000us         4.75%      94.000us       0.470us           200
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.977ms

In general, this is too small a shape to draw any conclusions. At this small shape level, other fixes overhead dominate. 
Also can you post your cpu details (lscpu)?

**Comment by Xia-Weiwen** [comment]
Thank you.
`lscpu` on my machine gives this:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                96
On-line CPU(s) list:   0-95
Thread(s) per core:    2
Core(s) per socket:    24
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
Stepping:              7
CPU MHz:               2288.085
CPU max MHz:           3900.0000
CPU min MHz:           1000.0000
BogoMIPS:              4800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              36608K
NUMA node0 CPU(s):     0-23,48-71
NUMA node1 CPU(s):     24-47,72-95
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local ibpb ibrs stibp dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke spec_ctrl intel_stibp arch_capabilities
```
May I know your CPU specifications?
And could you try `M, N, K = 156800, 16, 36` ? It's larger and int8 is also slower on my machine.

**Comment by dskhudia** [comment]
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              36
On-line CPU(s) list: 0-35
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) CPU @ 1.60GHz
Stepping:            4
CPU MHz:             1421.896
CPU max MHz:         1601.0000
CPU min MHz:         800.0000
BogoMIPS:            3200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-35
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d

**Comment by dskhudia** [comment]
This is for M, N, K = 156800, 16, 36

----- fp32 linear -----
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
                Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
        aten::linear         0.05%     545.000us       100.00%        1.146s      11.461ms           100
         aten::addmm        41.02%     470.160ms        99.84%        1.144s      11.442ms           100
         aten::copy_        58.79%     673.810ms        58.79%     673.810ms       6.738ms           100
             aten::t         0.05%     587.000us         0.11%       1.289ms      12.890us           100
     aten::transpose         0.05%     562.000us         0.06%     702.000us       7.020us           100
        aten::expand         0.02%     219.000us         0.02%     272.000us       2.720us           100
    aten::as_strided         0.02%     193.000us         0.02%     193.000us       0.965us           200
--------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 1.146s

----- FBGEMM int8 qlinear -----
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                             Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
                quantized::linear        99.88%     924.731ms       100.00%     925.817ms       9.258ms           100
                    aten::resize_         0.04%     394.000us         0.04%     394.000us       3.940us           100
    aten::_empty_affine_quantized         0.03%     277.000us         0.03%     277.000us       2.770us           100
                      aten::empty         0.02%     223.000us         0.02%     223.000us       2.230us           100
                    aten::q_scale         0.01%     126.000us         0.01%     126.000us       1.260us           100
               aten::q_zero_point         0.01%      66.000us         0.01%      66.000us       0.660us           100
---------------------------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 925.817ms

**Comment by dskhudia** [comment]
Since your machine is a two socket machine, you may want to try something like the following:

OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 numactl -m 0 -C 3 <command> 

Also make sure you have a release build and turn turbo-off to reduce variations due to turbo kicking in.

**Comment by Xia-Weiwen** [comment]
Thanks. That was helpful. But as you can see int8 linear is still slower. Shouldn't we expect this to be faster? I understand that the implementation of int8 op will introduce extra overhead somewhere. Chrome tracing showed that overhead of preparation was big. Is it possible to reduce it?
![image](https://user-images.githubusercontent.com/12522207/130001883-34090f32-df80-4093-a17f-dfb3aba32d28.png)

**Comment by dskhudia** [comment]
@supriyar back to you regarding some of the fixed overhead introduced in qlinear op

**Comment by dskhudia** [comment]
> But as you can see int8 linear is still slower. Shouldn't we expect this to be faster? 

int8 is faster in my benchmarking. See above. The order of fp32 and int8 is reversed.

**Comment by Xia-Weiwen** [comment]
> > But as you can see int8 linear is still slower. Shouldn't we expect this to be faster?
> 
> int8 is faster in my benchmarking. See above. The order of fp32 and int8 is reversed.

Sorry for that. I reproduced your result.
Anyway it would be great if the overhead of preparation could be further reduced.
For example, I saw overhead of `Tensor::q_scale` and `Tensor::q_zero_point` was somewhat high considering they are just getters. There was also a time gap between them, but they are actually two consecutive sentences.
