### ISSUE TITLE
Support `torch.linalg.cross`

### ISSUE THREAD

**Issue by AnirudhDagar** [pytorch/pytorch#62810]
## 🚀 Feature
Support `torch.linalg.cross`.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

## Motivation & Pitch

Python Array API proposes the use of `linalg.cross` among other linear algebra functions. Currently, PyTorch supports the same functionality with `torch.cross`. Array-API Ops tracker (#58742) lists a few aliases and it would be nice to add an alias `torch.linalg.cross` to `torch.cross` making it compliant with Array API.

## Additional context

* [Python Array API linalg.cross](https://data-apis.org/array-api/latest/extensions/linear_algebra_functions.html#linalg-cross-x1-x2-axis-1)

**Comment by mruberry** [comment]
We should be careful because I don't think torch.cross is compliant with the Python Array API specification or NumPy, so we may need a plan to deprecate its behavior.

**Comment by AnirudhDagar** [comment]
I might have missed something. @mruberry could you be more specific about the divergence from Array API?  Thanks!

Also, I have a small question (if there are no compliance issues and we go ahead) with the alias to `linalg` namespace (had a brief offline discussion with @IvanYashchuk yesterday).

Currently `torch.cross` lies in [cross.cpp](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Cross.cpp), if we go ahead with this, would it be better to rename the actual function to `linalg.cross` and then alias `torch.cross` to that?
This is inspired by what you did with `torch.det` in #42802.

I've something of this sort working locally, will raise a draft PR after fixing a few small issues hopefully for more detailed discussion.

**Comment by IvanYashchuk** [comment]
`torch.cross` is not compliant with NumPy. NumPy has the possibility to choose the axes (dimensions) which are considered as vectors separately for each input and result, and it has the `axis=None` argument that overwrides other choices and is same as `dim` in PyTorch when specified but the default behavior is different.

`torch.cross` has a similar function signature as the current Array API.
```
array_api.linalg.cross(x1, x2, /, *, axis=-1)  |  torch.cross(input, other, dim=None)
```
In PyTorch, if `dim` is not specified it defaults to the first dimension found with the size 3. In NumPy and Array API the default axis/dimension is the last one.

In addition, NumPy works with 2D (the third component is treated as zero) and 3D vectors, while PyTorch accepts only 3D vectors. Array API also specifies that `linalg.cross` should work only with 3D vectors.

NumPy has more functionality in its `cross` function than PyTorch and Array API.

**Comment by Lezcano** [comment]
It's very funny that in the docs of `torch.cross`  it warns (emph mine):
> If dim is not given, it defaults to the first dimension found with the size 3. **Note that this might be unexpected.**

In other words, don't pass tensors of shape `(3, 3)`, or you'll be up for an interesting bug-hunt evening.

I think that this is a great time to correct this. I believe that the behaviour suggested by the array API is a much better one. We could do with this as we've done with other functions such as QR, SVD, eig, symeig... where we correct the behaviour when moving it to `linalg` and add a deprecation warning and a deprecation rule in the original function, and then we'll continue the deprecation process in upcoming releases. @mruberry what do you think?

**Comment by AnirudhDagar** [comment]
Thanks, @IvanYashchuk for sharing the detailed state of `cross` API across the libraries and also linking some very relevant NumPy issues. Looks like the default behaviour is the only divergent thing with Array-API. I'm not sure, but I guess PyTorch will prefer to be compliant with Array-API over NumPy in such scenarios where the three are different. 

Nice catch @Lezcano, I can incorporate this in my PR if we have a green light to go ahead with this.

**Comment by mruberry** [comment]
> I think that this is a great time to correct this. I believe that the behaviour suggested by the array API is a much better one. We could do with this as we've done with other functions such as QR, SVD, eig, symeig... where we correct the behaviour when moving it to `linalg` and add a deprecation warning and a deprecation rule in the original function, and then we'll continue the deprecation process in upcoming releases. @mruberry what do you think?

Unsurprisingly I agree with you, @Lezcano, and thank you for the write-up, @IvanYashchuk. linalg.cross being consistent with the Python Array API (over NumPy) makes sense because NumPy has no linalg.cross. I also think we can implement linalg.cross without immediately deprecating torch.cross, although we should definitely refer users to linalg.cross. Deprecating torch.cross will require additional review. While it's not used often it is used, and it's unclear if users are relying on its unique behavior or not.
