### ISSUE TITLE
AutoGPU header relies on WITH_CUDA

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#6285]
AutoGPU is compiled with WITH_CUDA. Instead, it should be in an auto_gpu.cpp file so we do not have to set this macro while compiling it...

If a third party lib includes auto_gpu.h without doing a `#define WITH_CUDA`, then they try to use it, the things in auto_gpu.h wrapped with `WITH_CUDA` will not compile and it won't work. The solution I can see is to split it out into a .cpp so CUDA is baked into the pytorch .so.

**Comment by ezyang** [comment]
Another classic way to solve this problem is to have a autogenerated header file which sets the parameters properly.
