### ISSUE TITLE
Doing an operation on tensors of a different device

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#6286]
In ATen, doing operation on tensors of a different device seems unspecified. 

```c++
at::Tensor x, y;
{
  AutoGPU autogpu(0);
  x = at::CUDA(at::kFloat).randn({100});
  y = at::CUDA(at::kFloat).randn({100});
}
{
  AutoGPU autogpu(1);
  auto z = x * y; // What happens here? Error | Copy z to GPU 1 | keep z on GPU 0
}
```

Currently, according to @ezyang there's an error. However, writing models, I think it's preferred it be one of the latter options, since my model will work but maybe just a bit slower. I think @gchanan just suggested that keeping z on GPU 0 is the way PyTorch goes, and maybe ATen should also do this

**Comment by ezyang** [comment]
TBC, I hope it's an error, but I am not sure it is. The code will say.

**Comment by ezyang** [comment]
It's an error, but a weird one:

```
  arguments are located on different GPUs at /home/ezyang/Dev/pytorch-python2/
  aten/src/THC/generated/../generic/THCTensorMathPointwise.cu:313
```

The reason you get this error is because a result tensor is allocated on GPU 1, and now it can't participate in the operation because you have two GPU 0 inputs and another GPU 1 input (for the otuput).

**Comment by ebetica** [comment]
Ah, so maybe the treatment would be to allocate the tensor on the device of one of the arguments?

**Comment by gchanan** [comment]
If you did that, you'd just get a different error (the tensors aren't on the current device).
