### ISSUE TITLE
Aten op first round run is slow

### ISSUE THREAD

**Issue by jianlongf** [pytorch/pytorch#62881]
My runtime used aten as the backend, but I found first round of run is slow about 3841 ms, the later round is 369 ms. The reason is the first operation(lstm in my run) is very slow, it can reach about 3564 ms. So I guess the reason is that GPU(AMD Vega 20) is lazy launch. Is it reaonable ? And I wanna know the deep reason behind this. Are there any solution to tackle it. 
Thanks in advance for any resposes and helps.

system: Linux ubuntu133 4.15.0-152-generic #159-Ubuntu SMP Fri Jul 16 16:28:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
pytorch: 1.7 c6bfab116cf0e35814f82aa9a528160a0c88f9f5
docker: Docker version 20.10.2, build 20.10.2-0ubuntu1~18.04.3
GPU hardware:

> ================================= Product Info =================================
GPU[0]          : Card series:          Vega 20
GPU[0]          : Card model:           0x81e
GPU[0]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]          : Card SKU:             D36002
GPU[1]          : Card series:          Vega 20
GPU[1]          : Card model:           0x81e
GPU[1]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[1]          : Card SKU:             D36002
===============================================================================

**Comment by xsacha** [comment]
If it works anything like CUDA, the first run it works out the optimal algorithms to use.
Also, if using JIT I believe it profiles it first run as well.

**Comment by jianlongf** [comment]
@xsacha thanks for interpreting. Is this meaning that the first run can speed up if the algorithm is fixed ?

**Comment by xsacha** [comment]
I don't think so. I believe its intended to warm up first. First run is always slow for me too.

**Comment by jianlongf** [comment]
@xsacha thanks. I found first-time was caused by the cost of rocblas initialization. So just initialize rocblas is ok for my case.
