### ISSUE TITLE
Error messages if tensor is on the wrong gpu

### ISSUE THREAD

**Issue by pcmoritz** [pytorch/pytorch#629]
Dear all,

if I do the following:
```
torch.zeros(10).cuda(1) + torch.zeros(10).cuda(2)
```

I get this error message:
```
RuntimeError: Assertion `THCTensor_(checkGPU)(state, 3, self_, src1, src2)' failed.  at /home/ubuntu/pytorch/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:214
```

Is there a plan to give more informative error messages to users? In this case it is clear what is happening, but sometimes it is more subtle that the tensors are on different gpus and then this error message is a little confusing.

A simple fix is to use THAssertMsg to give an informative error message (and also say which gpus the tensors live on). Any thoughts?

-- Philipp.

**Comment by apaszke** [comment]
Yeah, this needs to be fixed. Thanks for a suggestion!
