### ISSUE TITLE
Improving Multiprocessing Support for Jupyter Notebooks

### ISSUE THREAD

**Issue by teatreeoilchocolate** [pytorch/pytorch#62943]
## 🚀 Feature

An easy to use way of using multi process applications in a jupyter-notebook.

## Motivation

Data science is an explorative process at times and the standard platform with which s.o. starts out exploring data science is the jupyter-notebook. A well known example of this would be the kaggle-platform. Most courses champion this tool stack. A good example would be the fast.ai library and their accompanying courses.
Additionally, the provision of multiprocessing capabilities that fail with a not helpful error-message, in this context, on the platform that it is most likely to be used on might lead to some confusion.
This is also problematic if we consider running the code in a jupyter-notebook in a similar fashion to running a Python script.(Not tested, would just like to point out that there might be an issue lurking.)
nn.DistributedDataParallel is used for Multi-GPU processing if I understand correctly and more skewed towards the model and not e.g. preparing and ingesting data in 2 different processes.

## Pitch

Multiprocessing works in a jupyter-notebook context the same way it would work in a regular script-context.

## Alternatives

An error message stating that the current environment is not suitable for this type processing, so that the programmer immediately knows not to look for a bug in their code.

## Additional context
See
https://github.com/pytorch/pytorch/issues/48931
https://github.com/pytorch/pytorch/issues/17680
https://github.com/pytorch/pytorch/issues/42049

**Comment by mszhanyi** [comment]
I think this issue is beyond the scope of Pytorch.  
It should be an issue of https://github.com/ipython/ipython
Python multiprocessing has different behaviors on spawn and fork, interactive and script mode.
So far, any python multiple processing program are not supported in interactive mode with spawn.

If you have time, you could walk through https://github.com/mszhanyi/pymultiprocessdemo.

**Comment by teatreeoilchocolate** [comment]
Hi!
Thanks for the response and the link.
I was under the impression that pytorch had more to do with the multiprocessing in this regard. 
Under these circumstances there is no point in keeping it open.
Cheers
