### ISSUE TITLE
Linter annotation are no longer displayed for PRs

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62975]
Just noticed that clang-format violations detected in https://github.com/pytorch/pytorch/pull/62929/checks?check_run_id=3266475275 are not rendered in https://github.com/pytorch/pytorch/pull/62929/files

**Comment by malfet** [comment]
@samestep is there a document somewhere describing what linters violations are populated in GH UI and which aren't.

**Comment by malfet** [comment]
Adding screenshots for context:
clang-format detected fix-up on line 29:
```
diff --git a/torch/csrc/jit/runtime/static/passes.cpp b/torch/csrc/jit/runtime/static/passes.cpp
index 17a27000e2..e7b22fcf77 100644
--- a/torch/csrc/jit/runtime/static/passes.cpp
+++ b/torch/csrc/jit/runtime/static/passes.cpp
@@ -25,7 +25,8 @@ bool HasInplaceOp(Block* block, const AliasDb& alias_db) {
   return false;
 }
 
-C10_UNUSED void ConcatAddMulReplaceNaNClip(std::shared_ptr<torch::jit::Graph>& graph) {
+C10_UNUSED void ConcatAddMulReplaceNaNClip(
+    std::shared_ptr<torch::jit::Graph>& graph) {
```

but it's not visible as comment:
![image](https://user-images.githubusercontent.com/2453524/128748868-805d25ab-e21d-44ed-ac76-18d5ef0198ad.png)

**Comment by samestep** [comment]
I think this is expected, right? We only add annotations from Flake8 and clang-tidy, not clang-format:

https://github.com/pytorch/pytorch/blob/978490d7c70973a91285de9adaa21ee26f0eb9f8/.github/workflows/add_annotations.yml#L15-L18
