### ISSUE TITLE
Handle render_test_results's failure due to dependencies

### ISSUE THREAD

**Issue by tktrungna** [pytorch/pytorch#62979]
`render_test_results` failed due to dependent job(s) were skipped and could not find test report artifacts files.

`Error: Unable to find any artifacts for the associated workflow`

Example: https://github.com/pytorch/pytorch/actions/runs/1113514757.  ciflow_should_run,  calculate_docker_image and build-and-test were skipped. However render_test_results was `always()` so it run and failed

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment]
yes please fix this haha
