### ISSUE TITLE
Allow setting empty CPU or CUDA storage for a Tensor with non-zero sizes and strides

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#62972]
## 🚀 Feature
@ezyang tells me that's what https://github.com/facebookresearch/functorch/blob/619f392a0b1afa132b9c791c85c75538b2482788/functorch/_src/python_key.py#L28-L31 is supposed to do, but the code actually resizes the storage to having the passed-in sizes and strides.

## Motivation

This saves memory. Also helps prevent https://github.com/pytorch/pytorch/issues/62730 from happening

**Comment by ezyang** [comment]
Doesn't have to be implemented directly the way spelled here; TBH, probably shouldn't be. Let's figure out some other API for doing this.
