### ISSUE TITLE
Implement `set_flush_denormal ` for ARM

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62983]
Current implementation of `set_flush_denormal ` is very x86-centirc as can be seen in :
https://github.com/pytorch/pytorch/blob/710c419f110bbd2c13a2f6f8710aa47dec857115/aten/src/ATen/cpu/FlushDenormal.cpp#L10-L12

cc @malfet

**Comment by darshanp4** [comment]
https://github.com/pytorch/pytorch/pull/115184
please check this.

**Comment by lezcano** [comment]
Fixed at https://github.com/pytorch/pytorch/pull/115184
