### ISSUE TITLE
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content

### ISSUE THREAD

**Issue by aminrd** [pytorch/pytorch#63006]
Doing the following scenario: 

```bash
conda create -n env_name
conda activate env_name
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
```

 I interfered the following error on downloading the package which apparently after downloading when checking the checksum, it sees a mismatch. I also tried removing those *.bz2 files just in case if there is a pre-downloaded file, it didn't work.

```bash
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchaudio-0.9.0-py39.tar.bz2'.
  download saved to: /home/amin/anaconda3/pkgs/torchaudio-0.9.0-py39.tar.bz2
  expected md5: 7224453f68125005e034cb6646f2f0a3
  actual md5: 6bbb8056603453427bbe4cca4b033361

ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchvision-0.10.0-py39_cu111.tar.bz2'.
  download saved to: /home/amin/anaconda3/pkgs/torchvision-0.10.0-py39_cu111.tar.bz2
  expected md5: 78b4c927e54b06d7a6d18eec8b3f2d18
  actual md5: 69dd8411c573903db293535017742bd9
```

My system information:
```
Linux SPOT-Server 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

My `conda --version` is also `4.8.2`. I also should add that I have same issue on Windows having `conda --version` equal to `4.10.1`.

I also downloaded the links manually using `wget` and calculated the checksums manually using `md5sum` and in both cases, the computed checksum was equal to the `actual md5` mentioned in the `CheckSum` error.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by ModarTensai** [comment]
md5sum seems wrong in anconda.org or in some of its mirrors. @malfet, might need a reupload?

**Comment by malfet** [comment]
I don't have an upload rights to the repo, but torchaudio checksum  match ones I've uploaded https://anaconda.org/malfet/torchaudio/files and they were copied to `pytorch` channel using `anaconda copy`

Have you filed a bug again Anaconda yet?

**Comment by ModarTensai** [comment]
They don't match on my end. The number of downloads is a good indicator.
![image](https://user-images.githubusercontent.com/7101743/128807961-ee1aef51-8d1b-4f93-ad24-106edfc4fded.png)

What about torchvision? (pytorch/vision#4261 and pytorch/vision#4262)

**Comment by ModarTensai** [comment]
For the time being, adding your channel fixes the issue:
```shell
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c malfet -c pytorch -c nvidia
```

**Comment by BSalita** [comment]
I'm getting the same checksum error on torchvision and torchaudio. -c malfet resolves the error. I'm uneasy about checksum failures.

**Comment by malfet** [comment]
https://github.com/pytorch/vision/issues/4261 and https://github.com/pytorch/vision/issues/4262 seems related

**Comment by seemethere** [comment]
Looks like the root cause of this is that the `anaconda copy --replace` command that was run in https://github.com/pytorch/vision/issues/4240#issuecomment-894930357 just uploaded new packages and kept the old packages instead of replacing the new with the old.

I've gone ahead and deleted the old packages and the issue appears to have resolve itself.

**Comment by aminrd** [comment]
The problem is fixed now, thanks!

**Comment by malfet** [comment]
Filed https://github.com/Anaconda-Platform/anaconda-client/issues/581
@rgommers can you please tell me if I filed it against the right issue tracking repo?

**Comment by BSalita** [comment]
Thanks for the fix!

**Comment by rgommers** [comment]
@malfet, that looks like the right repo to me, yes.
