### ISSUE TITLE
Cannot run the TracedModule.code

### ISSUE THREAD

**Issue by zheng-ningxin** [pytorch/pytorch#63024]
### Please note that this issue tracker is not a help form and this issue will be closed.
Hi, I'm using `torch.jit` to trace the `resnet34`, however, I found that the python code returned by the TracedModule.code is not runnable because of the namespace problems. For example.

```
import torch
import torchvision
model =torchvision.models.resnet34()
data = torch.rand(8,3,224,224)
trace=torch.jit.trace(model, data)
_map = {}
for name, trace_m in trace.named_modules():
    _map[name] = trace_m

print(_map['layer4.0'].code)
```
and we can see the output:
```
def forward(self,
    argument_1: Tensor) -> Tensor:
  _0 = self.downsample
  _1 = self.bn2
  _2 = self.conv2
  _3 = self.relu
  _4 = (self.bn1).forward((self.conv1).forward(argument_1, ), )
  _5 = (_1).forward((_2).forward((_3).forward(_4, ), ), )
  input = torch.add_(_5, (_0).forward(argument_1, ))
  return (_3).forward1(input, )

```
We can see that the function calls `torch.add_` which is not an available function in torch. It seems like that the function `torch.Tensor.add_` is moved under the `torch` namespace? right? Besides, I also found other similar functions such as `torch.adaptive_avg_pool2d`

![image](https://user-images.githubusercontent.com/49771382/128859187-e3272710-f17f-47aa-97aa-c0a9cdc6064c.png)

**What should I do if I want to get a runnable python code? thanks! Sincerely looking forward to your reply.**

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
Hi @zheng-ningxin,

The code print out is for debugging and serialization (save to disk via `torch.jit.save`) only. It is not meant to be runnable. If you'd like to run forward of the module, you can call the module (it is a callable with `__call__` defined) directly.
