### ISSUE TITLE
TorchScript doesn't handle ModuleList assignment in conditional branches

### ISSUE THREAD

**Issue by sharvil** [pytorch/pytorch#63033]
## 🐛 Bug

The following code, where a local variable `ml` is assigned to the same value in both branches of a conditional, doesn't compile with TorchScript.

```python
import torch
import torch.nn as nn


class TestModule(nn.Module):
  def __init__(self):
    super().__init__()
    self.mod_list = nn.ModuleList([nn.Linear(10, 10) for _ in range(5)])

  def forward(self, x, flag: bool):
    y = []
    if flag:
      ml = self.mod_list
    else:
      ml = self.mod_list
    for m in ml:
      y.append(m(x))
    y = torch.stack(y)
    return y.sum()


s = torch.jit.script(TestModule())
```

The output is:
```
undefined value ml:
  File "a.py", line 22
    else:
      ml = self.mod_list
    for m in ml:
             ~~ <--- HERE
      y.append(m(x))
    y = torch.stack(y)
```

## Expected behavior

The code above should compile. This example is stripped-down to highlight the error. In practice, each branch may assign different `ModuleList` instances, which also fails. An alternate construction of the branched assignment also fails, but with a different error:

```python
[...]
    ml = self.mod_list
    if flag:
      ml = self.mod_list
    for m in ml:
      y.append(m(x))
[...]
```

which fails with `Cannot re-assign 'ml' to a value of type module because ml is not a first-class value.  Only reassignments to first-class values are allowed:`

## Environment

 - PyTorch Version (e.g., 1.0): 1.9+cpu
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.5
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

cc @gmagogsfm

**Comment by gmagogsfm** [comment]
`ModuleList` is a subclass of `nn.Module`. In TorchScript, all `nn.Module`s can not be used as a value since it is deemed as part of static graph topology. Therefore, the assignment doesn't work here, as expected.

A workaround would be to move assignment of `ml` inside `__init__` so that its value is determined at module construction time rather than during runtime. 

Closing this issue for now, feel free to reopen if the workaround doesn't work.

**Comment by sharvil** [comment]
Fair enough that this construct isn't supported by TorchScript. Maybe this issue should be a feature request instead.

Since the `ModuleList` itself isn't modified at runtime, it still maintains a static graph topology. We're just creating references to existing `ModuleList`s that have been constructed in `__init__`.

The following code which is not accepted by TorchScript:

```python
ml = self.mod_list
if flag:
  ml = self.different_mod_list
for m in ml:
  y.append(m(inputs))
```

can be transformed into this code which is accepted by TorchScript:

```python
if flag:
  for m in self.different_mod_list:
    y.append(m(inputs))
else:
  for m in self.mod_list:
    y.append(m(inputs))
```

The first code example seems more natural and results in less code duplication as far as the programmer is concerned.
