### ISSUE TITLE
"RuntimeError: CUDNN_STATUS_INTERNAL_ERROR"

### ISSUE THREAD

**Issue by Lan1991Xu** [pytorch/pytorch#6310]
Hi
I write the code based on pytorch for a few month, it always work. But currently, I meet a problem "RuntimeError: CUDNN_STATUS_INTERNAL_ERROR". I check the code, and even using other code published in the github. It also meets the same problem.
I search google someone suggest https://github.com/torch/cutorch/issues/677, but it did not work for my case. 
My environment is: python2.7, pytroch 0.3.1.post2, CUDA 8.0.61, CUDNN 7.
Is there any suggestion for this problem?
  File "/homes/xl309/Softwares/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/homes/xl309/Softwares/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_INTERNAL_ERROR

**Comment by SsnL** [comment]
Check your cuda and cudnn install.

**Comment by Lan1991Xu** [comment]
Thanks, I have solved.  The cuda and cudnn seems automatical install by Pytorch install

**Comment by zwangby** [comment]
How to solve the problem?
