### ISSUE TITLE
same platform diff docker (runtime/devel) cant read GPU?

### ISSUE THREAD

**Issue by jaffe-fly** [pytorch/pytorch#63125]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
all test in the same platform(centos,  GPU driver is 416.xxx,  )
in dockerhub
docker image pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel  is ok, it can read gpu(torch.cuda.is_available() is true) but its too big, so i try pytorch/pytorch:1.8.1-cuda11.1-cudnn8-rutime  cant read gpu ,why? where i can see the docker file? or how can i solve use samll docker image can read gpu question

**Comment by bdhirsh** [comment]
Hi!

This seems like a question better suited for the [pytorch forums](https://discuss.pytorch.org/). I'm going to close this issue for now - feel free to repost your question there!
