### ISSUE TITLE
Random CI error 'CUDA xxx installed failed'

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#63139]
## 🐛 Bug

sometimes,  binary windows build CI failed due to random error, For example
https://app.circleci.com/pipelines/github/pytorch/pytorch/363222/workflows/025e38a7-8a73-44d7-b88c-127c9a666035/jobs/15322148

**And it can pass with rerunning it.**
## To Reproduce

Since it's a random error, hard to reproduce.

## Expected behavior

CI don't fail.

## My analysis
Yesterday, one of my PR came across this issue again.
![image](https://user-images.githubusercontent.com/16190118/129164158-a10cdea3-5c35-4462-85a3-e843d2c02712.png)
https://app.circleci.com/pipelines/github/pytorch/pytorch/363222/workflows/025e38a7-8a73-44d7-b88c-127c9a666035/jobs/15322112
https://app.circleci.com/pipelines/github/pytorch/pytorch/363222/workflows/025e38a7-8a73-44d7-b88c-127c9a666035/jobs/15322157
https://app.circleci.com/pipelines/github/pytorch/pytorch/363222/workflows/025e38a7-8a73-44d7-b88c-127c9a666035/jobs/15322146
https://app.circleci.com/pipelines/github/pytorch/pytorch/363222/workflows/025e38a7-8a73-44d7-b88c-127c9a666035/jobs/15322087

We can find multiple workflows failed with the same reason at that time.
So I think it should **NOT** be an issue in single machine.
It most likely there's a network issue at that time so that the cudatoolkit failed to download.

@malfet @seemethere , could we check the S3 access log or circleci can provide those build machine access log.

And linux CI has the similar issue
![image](https://user-images.githubusercontent.com/16190118/129183544-b833e9e3-5aff-47f1-a414-db5940cbcfe9.png)
They all failed in the same step  with the same reason. And they can pass with rerun
![image](https://user-images.githubusercontent.com/16190118/129183633-8737053c-ee8c-4232-9487-397cfaa1afbd.png)
![image](https://user-images.githubusercontent.com/16190118/129183735-7051a1e3-0460-4dee-992a-a133efde4f04.png)
https://app.circleci.com/pipelines/github/pytorch/pytorch/363222/workflows/025e38a7-8a73-44d7-b88c-127c9a666035/jobs/15323086
https://circleci.com/gh/pytorch/pytorch/15323086?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/pytorch/pytorch/15323303?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Marking this as high priority as this is starting to creep into our nightly builds

**Comment by peterjc123** [comment]
Let's export the logs first as we have done [here](https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/windows_cuda_install.sh#L41).

**Comment by mszhanyi** [comment]
Update:
cuda setup failed log is output in 
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/15432889/output/104/0?file=true&allocation-id=611ca3478e509f260e3a0dc2-0-build%2F73673B1D
![image](https://user-images.githubusercontent.com/16190118/129854026-ffb71822-d7d3-4caa-9cf7-bd41360eb5ba.png)

Need more investigation

**Comment by mszhanyi** [comment]
@zasdfgbnm
do you know what does it mean? the below outputs are  different from from a successful installation.
```
      0.159 |  WARNING: [NVI2.CEngineCache] 1059@CEngineCache::PreserveGoldPath : Installer uninstall entry not found, will not preserve engine cache folder. 
      0.195 |    DEBUG: [NVI2.CEngineCache] 954@CEngineCache::DeleteOrphanPackageDataKeys : "Cache" does not exist. 
      0.196 |    DEBUG: [NVI2.CEngineCache] 954@CEngineCache::DeleteOrphanPackageDataKeys : "Extensions" does not exist. 
      0.196 |    DEBUG: [NVI2.CEngineCache] 954@CEngineCache::DeleteOrphanPackageDataKeys : "Configs" does not exist. 
      0.196 |    DEBUG: [NVI2.CEngineCache] 1015@CEngineCache::DeleteOrphanStrippedPackageData : Stripped registry key does not exist. 
      0.197 |    DEBUG: [NVI2.CEngineCache] 435@CEngineCache::CleanupStrippedPackages : Stripped registry key does not exist to perform clean up process. 
```

**Comment by mszhanyi** [comment]
[LOG.RunDll32.EXE.log](https://github.com/pytorch/pytorch/files/7005396/LOG.RunDll32.EXE.log)
[LOG.setup.exe.log](https://github.com/pytorch/pytorch/files/7005397/LOG.setup.exe.log)
They are the logs of one successful installation

**Comment by skyline75489** [comment]
The installer seemed to failed with the following message:

```log
108.757 |    ERROR: [NVI2.InstallThread] 54@CInstallThread::ThreadProc : Install failed - Exception {0xe4080000; File: InstallationStepper.cpp; Line: 382} - going to fail state. 
```

**Comment by peterjc123** [comment]
The following message seems to the fatal one. 
```
     71.772 |  WARNING: [DevicePackageUtil] 303@DevicePackageUtil::IsCompatibleDriverFound : Failed to populate supported devices. 
     71.772 |    ERROR: [DisplayDriver.DisplayDriverExtSite] 985@CDisplayDriverExtSite::CheckConstraint : Failing InfPlatformCheck constraint, no compatible devices found supporting OS 10.0.17763. 
```

**Comment by peterjc123** [comment]
Don't know why `Display,Driver` get selected here.

**Comment by peterjc123** [comment]
I found this when comparing the differences.
```
  WARNING: [NVI2.CNVRejectTestWUInstall] 66@CNVRejectTestWUInstall::InvokeTest : Windows Update is currently installing or uninstalling updates. 
  WARNING: [NVI2.NVRejectTestConstraint] 147@CNVRejectTestConstraint::InvokeCheck : Activity constraint "WUINSTALL" failed. 
    DEBUG: [NVI2.NVInstaller] 3036@CNVInstaller::IsConstraintFailureOverridden : Constraint "WUINSTALL" can not be overridden in failure case. 
```

**Comment by peterjc123** [comment]
@mszhanyi Could you please test whether stopping the Windows Update service before installing CUDA helps?
```cmd
sc query wuauserv
net stop wuauserv
sc query wuauserv
```

**Comment by seemethere** [comment]
Doing work to streamline this CUDA install into our base windows AMIs for GHA here: https://github.com/pytorch/test-infra/pull/103

This won't resolve our CircleCI issues but it should help the interment failures we're seeing like this on GHA

**Comment by peterjc123** [comment]
Looks like the CUDA installation isn't a problem with the patch. But now they are failing probably because the no-action timeout may be too short.

**Comment by mszhanyi** [comment]
That patch looks not working.
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/15462858/output/104/0?file=true&allocation-id=611dfba8958375412939d13b-0-build%2F54936121

**Comment by mszhanyi** [comment]
Disable it is more reliable than stop it.
`sc config wuauserv start= disabled`
https://app.circleci.com/pipelines/github/pytorch/pytorch/366489/workflows/4960978b-8295-42d9-98b4-68bb5b38a51a/jobs/15464015

**Comment by janeyx99** [comment]
Re-opening this issue as it's affecting our trunk CI. Recently, it accounted for 14.5% of our trunk failures. An example log is: https://github.com/pytorch/pytorch/runs/3556677361

**Comment by seemethere** [comment]
I think this might resolve, https://github.com/pytorch/pytorch/pull/64825
