### ISSUE TITLE
About the implementation of torch.svd

### ISSUE THREAD

**Issue by ZYJESJ** [pytorch/pytorch#63136]
Dear source code contributors, hello!
I am currently developing a tensorRT svd plugin, the goal is to align the results of pytorch's torch.svd and torch.linalg.svd. I checked the source code of pytorch and learned that the implementation of cuda is implemented through cuslover. Due to the complexity of the source code, I browsed some of them and found that the results could not be aligned when doing experiments, so I wanted to get some help here.
![image](https://user-images.githubusercontent.com/35914850/129157964-5ccf8e01-e794-498a-9bb0-5f3ce1a8e2b0.png)

The specific questions are as follows: I first checked the definition of svd in native/BatchLinearAlgebra.cpp, and learned how svd will continue to call the underlying functions for specific implementation. The main reference is the call process of _svd_helper_cuda_lib in native/cuda/BatchLinearAlgebra.cu. Through tracking, I determined that the lowest call is cusolverDnSgesvdj and cusolverDnSgesvdjBatched, the two cuslover functions, and then I wrote a test by referring to the nv demo. Collection, but found that the result of opening s at the beginning cannot be completely aligned with torch.svd() and torch.linalg.svd(). After debugging, I found that the matrix input of cusolver is similar to matlab's column-major format, but the real input is still the original linear combination.

Take the above picture as an example, the real data memory arrangement is 1 4 2 2 5 1, but the order of printing is 1 2 4 5 2 1. I entered both of the above two possibilities into svd, and found that when the real data memory beat is not 1 2 4 5 2 1, you can get data that is more similar to cusolver.
![image](https://user-images.githubusercontent.com/35914850/129158072-c1593e3b-d6d4-4b4f-97ec-379e75ceaec5.png)

This situation is very confusing to me. Now I have the following understanding. The format of cuslover is similar to that of matlab. If you want to calculate the situation of 1 2 4 5 2 1, the real input data is 1 4 2 2 5 1, and pytorch is for It is guaranteed to conform to the habits of most people, so when the real data is input into svd, it is 1 2 4 5 2 1, but there is a process in the middle that transposes it to 1 4 2 2 5 1. Is there such a process? I saw that in the apply_svd_lib_gesvdjBatched function under native/cuda/BatchLinearAlgebraLib.cu, the input was transposed twice through the cloneBatchedColumnMajor function. At the same time, the output has done a process similar to transpose. I observed that the real data arrangement of the output of cuslover must be reordered by column first to get the result of svd output. At the same time, the result of cusolver must be multiplied by -1 to be completely aligned with torch.svd. Is this *-1 caused by the version, or pytorch multiplied -1 at the end of svd.
![image](https://user-images.githubusercontent.com/35914850/129158103-4de7f8cf-02f9-4b5f-b11c-0ff7ae51d4e2.png)

Thank you for reading my question and hope to get your reply.
PS：The pytorch version I just used is 1.8.1, and the cuda version is 10.2

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ZYJESJ** [comment]
Thank you very much for your reply.@ xwang233
The first point has completely solved my problem, I am browsing related functions.
The second point, please allow me to talk about my problem again. I understand that the feature vector of svd is not unique, but my goal is to get the same result as torch.linalg.svd or torch.svd. I use Related functions in nvidia's culsover library, I have confirmed that the underlying source code suitable for pytorch is the same. But I found that the result I got is still some factor error with torch.svd, so I am more confused about how to adjust the parameters. The final result of torch.svd and culsover function is exactly the same?

**Comment by Lezcano** [comment]
There is no way to always get the same result when using two different algorithms for mathematical reasons. You can come up with rules that work for most cases though. For example, you can choose your matrix `U` to have a positive first row. To do so, you can compute the signs of the first row of `U` and multiply the columns of `U` and the rows of `Vh` by these signs. Note that this rule does not work for all matrices, as it's not well defined for matrices whose `U` has zeros in the first row.

There are some deeper problems regarding the unicity of the factorisation, and these are described in the documentation. In general, it is possible to prove mathematically that there is no rule that makes this choice consistent, so the problem cannot be solved perfectly in general.

**Comment by ZYJESJ** [comment]
> There is no way to always get the same result when using two different algorithms for mathematical reasons. You can come up with rules that work for most cases though. For example, you can choose your matrix `U` to have a positive first row. To do so, you can compute the signs of the first row of `U` and multiply the columns of `U` and the rows of `Vh` by these signs. Note that this rule does not work for all matrices, as it's not well defined for matrices whose `U` has zeros in the first row.
> 
> There are some deeper problems regarding the unicity of the factorisation, and these are described in the documentation. In general, it is possible to prove mathematically that there is no rule that makes this choice consistent, so the problem cannot be solved perfectly in general.

Thank you very much. My current problem is that, in my understanding, I have used the same underlying algorithm as pytorch (the implementation of pytorch svd is a function provided by NVIDIA’s cusolver library), but after my experiment, the alignment cannot be guaranteed, so this This is where I am very confused. I don't know if I have overlooked something that makes it impossible to get a proper result.

**Comment by Lezcano** [comment]
Have you debugged and checked that you are calling the exact same function with exactly the same inputs as in PyTorch?

Also, as the documentation states, PyTorch does not guarantee which function will be called when solving the problem. In fact, we are in the process of adding more CUDA backends to this function, so I would not rely on being able to achieve this.

**Comment by ZYJESJ** [comment]
> Have you debugged and checked that you are calling the exact same function with exactly the same inputs as in PyTorch?
> 
> Also, as the documentation states, PyTorch does not guarantee which function will be called when solving the problem. In fact, we are in the process of adding more CUDA backends to this function, so I would not rely on being able to achieve this.

Thanks, I understood it all at once. Let me summarize at last, because I really didn't single-step debugging to see the call of pytorch, I just found a part of the underlying implementation of pytorch by searching keywords. Let me summarize what you mean, so please see if I understand it. Regarding svd, pytorch's gpu low-level implementation is not only cuslover. If I use torch.svd, it will select the appropriate back-end implementation based on the matrix I input (cuslover is only one of them), am I right?

**Comment by Lezcano** [comment]
About the backend: I do not know the current state of `svd`, but as backends, we often use a combination of calls to cuSolver and magma. We benchmark their speeds a priori for different sizes and figure out which one is best to call for matrices of which sizes. I do know that we are currently working on improving the performance of `linalg.svd`, so whatever backend is called now in master will likely change to "the optimal choice between cuSolver and magma" for the 1.10 release. As such, I would not rely on any result that you are getting now, but rather would try to build whichever tool you're building atop PyTorch in a backend-agnostic way.

About `torch.svd` vs `torch.linalg.svd`. Always use `linalg.svd`. `torch.svd` will be deprecated in an upcoming release, so please update your code to use `torch.linalg.svd`. Note that, among other things, `torch.svd`'s third return is `V`, while  `torch.linalg.svd`'s third return is `Vh`, that is, `V` transposed (or conjugated transposed in the complex case). There is a full deprecation guide in the `torch.svd` docs.

**Comment by Lezcano** [comment]
Closing this one as this is expected and documented in [`linalg.svd`](https://pytorch.org/docs/master/generated/torch.linalg.svd.html)
