### ISSUE TITLE
_export_onnx(): incompatible function arguments

### ISSUE THREAD

**Issue by MichaelWU0726** [pytorch/pytorch#63142]
## 🐛 Bug

when i export yolov5 to onnx format, it showed that: 
```
_export_onnx(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Graph, initializers: Dict[str, at::Tensor], onnx_opset_version: int = 0, dynamic_axes: Dict[str, Dict[int, str]], defer_weight_export: bool = False, operator_export_type: torch._C._onnx.OperatorExportTypes = <OperatorExportTypes.ONNX: 0>, strip_doc_string: bool = True, keep_initializers_as_inputs: bool = True, custom_opsets: Dict[str, int], add_node_names: bool = True, use_external_data_format: bool = False, onnx_file_path: str = '') -> Tuple[bytes, Dict[str, bytes]]
```  

## To Reproduce

I used the following:
```
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
inp = np.random.randn(batch_size, 3, x, y).astype(np.float32)
inp = torch.from_numpy(inp).to(device)
dynamic_ax = {'input_img': {0: 'batch', 2: 'image_height', 3: 'image_wdith'},
                      'out_1': {0, 2, 3},
                      'out_2': {0, 2, 3},
                      'out_3': {0, 2, 3}}
torch.onnx.export(model, inp, onnx_path,
                      input_names=["input_img"], output_names=["out_1", "out_2", "out_3"], verbose=True, opset_version=11,
                      dynamic_axes=dynamic_ax)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Ubuntu18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.7.8
 - CUDA/cuDNN version: 11.0/0.8.2
 - GPU models and configuration: NVIDIA 2080Ti
 - Any other relevant information:

I hope to get help, thanks!

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment]
Could you use pytorch 1.9 instead of 1.7.1? Also, the error message shows `dynamic_axes` format should be `dynamic_axes: Dict[str, Dict[int, str]]`, but the input `'out_1': {0, 2, 3},` does not follow the format.

**Comment by MichaelWU0726** [comment]
> Could you use pytorch 1.9 instead of 1.7.1? Also, the error message shows `dynamic_axes` format should be `dynamic_axes: Dict[str, Dict[int, str]]`, but the input `'out_1': {0, 2, 3},` does not follow the format. Please change the format and try again.

The usages in the official source codes shows that `dynamic_axes` can only include `int`:
```python
dynamic_axes = {'input_1':[0, 2, 3],
                            'input_2':[0],
                            'output':[0, 1]}
```

**Comment by MichaelWU0726** [comment]
> Could you use pytorch 1.9 instead of 1.7.1? Also, the error message shows `dynamic_axes` format should be `dynamic_axes: Dict[str, Dict[int, str]]`, but the input `'out_1': {0, 2, 3},` does not follow the format. Please change the format and try again.

Thanks, I just found that `dynamic_axes` should be changed to Dict[str, List[int]]` if axes only include `int` as the following:
```python
dynamic_ax = {'input_img': {0: 'batch', 2: 'image_height', 3: 'image_wdith'},
                  'out_1': [0, 2, 3],
                  'out_2': [0, 2, 3],
                  'out_3': [0, 2, 3]}
```
