### ISSUE TITLE
ReduceLROnPlateau is not a subclass of _LRScheduler

### ISSUE THREAD

**Issue by randolf-scholz** [pytorch/pytorch#63143]
## 🐛 Bug

This is probably just a small oversight, but I noticed that [`lr_schedulers.ReduceLROnPlateau`](https://pytorch.org/docs/stable/_modules/torch/optim/lr_scheduler.html#ReduceLROnPlateau) is, contrary to all other `lr_scheduler` classes, not a subclass of `lr_schedulers._LRScheduler`

cc @vincentqb @jbschlosser @albanD @iramazanli

**Comment by janeyx99** [comment]
Thanks for pointing this out--closing in favor of https://github.com/pytorch/pytorch/issues/106767 which explains more deeply why this was the case. Let's continue future discussion there.
