### ISSUE TITLE
PyTorch Profiler

### ISSUE THREAD

**Issue by ma7dev** [pytorch/pytorch#63159]
## ❓ Questions and Help

I was aware of PyTorch Profiler during v1.8.x beta release, but after I have watched [PyTorch Community Voices' latest episode](https://www.youtube.com/watch?v=m6ouC0XMYnc), I became invested in trying out PyTorch Profiler. I have visited all of the relevant resources suggested mentioned in the presentation [40:48](https://youtu.be/m6ouC0XMYnc?t=2448), but I have had some tough time understanding how to add PyTorch Profiler to my current pipeline. I couldn't find a direct example where I have run immediately and see how good is PyTorch Profiler is.

Like most of the components in PyTorch, everything could be plug-and-play where you add some snippet of code to original source code without having any issues. However, it seems that PyTorch Profiler isn't like that. It is an additional component that should work separately from the original code as it consumes a lot of resources to apply the profiling.

So I needed to compile a simple example to understand it, [gist](https://gist.github.com/sudomaze/8aad93386e2b3364edbf0759514af5cc), and I really liked PyTorch Profiler! Here are my insights after using it in the simple example and my actual research work.
- It seems that the profiler adds additional delay (like 10-20%) to the current pipeline and it increases as you increase the number of active iterations to be profiled.
- Profiler suggests some useful changes that impact the performance (like increasing the batch size when GPU load is low or increase the number of workers when the Data Loader takes a lot of time to be processed)
- Although PyTorch Profiler gave more insights and suggestions to understand the general usage of resources based on my model and train structure, it isn't obvious how I can use PyTorch Profiler even further to apply more optimizations.
I wish there was a more direct mapping between the nn.Modules/Components to what is being displayed. In addition, it would be cool if there is a graph showing the data flow and model structure with the amount of data transfer and time took.

cc @ilia-cher @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by guotuofeng** [comment]
@sudomaze, actually, the nn.Module view and graph visualization feature is in our planning now. and we are discussing the minimal costs and impact on existing PyTorch.

**Comment by sudomaze** [comment]
@guotuofeng Awesome! 😄 

In the meantime, can you add a similar tutorial to the [gist](https://gist.github.com/sudomaze/8aad93386e2b3364edbf0759514af5cc) to PyTorch Profiler's documentation that walks you through the process as it is? Because others and myself had an assumption that it works just like [AMP](https://pytorch.org/docs/stable/amp.html) where you just add the suggested snippet to the suggested place, however, it isn't.

**Comment by guotuofeng** [comment]
@sudomaze , does the tutorial https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html enough? are there any additional thing we need add for simplicity?

**Comment by sudomaze** [comment]
@guotuofeng I think it would be better if there is a walkthrough tutorial like in [PyTorch TensorBoard](https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html) where the tutorial shows a full example and explaining the UI and how to utilize it. I think having a similar tutorial to TensorBoard would remove any confusion.

**Comment by sabrina-smai** [comment]
@sudomaze we had recently published a walkthrough of PyTorch Profiler v1.19 in this deep dive ["What's New in PyTorch Profiler?"](https://pytorch.org/blog/pytorch-profiler-1.9-released/) and here [too](https://opendatascience.com/optimizing-pytorch-performance-batch-size-with-pytorch-profiler/). Is this more helpful?

**Comment by sudomaze** [comment]
@sabrina-smai I have looked into ["What's New in PyTorch Profiler?"](https://pytorch.org/blog/pytorch-profiler-1.9-released/), but I haven't looked into [ODS's article](https://opendatascience.com/optimizing-pytorch-performance-batch-size-with-pytorch-profiler/). I think ODS's article is the one that I wished I have come across before. Is it possible to add this article for others to learn more about it?

**Comment by sabrina-smai** [comment]
Do you think it'd be useful to have it hyperlinked? Or having that same content on the PyTorch docs would be more useful?

**Comment by sudomaze** [comment]
I think having the same content would be better as a hyperlinked might be hard to find.

**Comment by aaronenyeshi** [comment]
Tensorboard profiler plugin is deprecated (https://github.com/pytorch/kineto?tab=readme-ov-file#pytorch-tensorboard-profiler-deprecated) . Please try out the latest pytorch profiler, and open an issues / questions you have about it. Closing this older issue.
