### ISSUE TITLE
[docathon] restructure CI documentation 

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#63175]
## 📚 Documentation

We currently have 3 different CI systems (Github Action, CircleCI, Jenkins) and many of the documents about out CI system is scattered around & probably out-dated. We propose to restructure the documentations for CI system.

- CONTRIBUTING.md
  - expand the `[CI failure tips](#ci-failure-tips)` section into a `[Continuous Integration](#ci-main)`
    - make the current CI failure tips a subsection of the new main section. 
    - add section: CI test matrix (generic)
    - add section: what CI jobs are run in what time?
      - subsection: CI control. e.g. `ciflow/*`, `[skipCI]`, `ci/master` etc.
    - link to the `README.md` files in .circleci and creating another one in .github/ and possible .jenkins/
- .circleci/README.md 
  - Move some content that are generic to all CI platform from .circleci/README.md into the main `CONTRIBUTING.md#ci-main`, including: (1) generic FAQs, (2) code structure of the binaries; (3) general notes, (4) how to build binary locally
  - keep the (1) CI config.yaml generator, (2) nightly build steps (are they still in circle?), and remove out-dated contents
- .github/README.md (or should it be .github/workflow/README.md?)
  - add specific sections about (1) how workflow files are generated; (2) how test matrix generator work; 

This is very prelimilary and just an initial thought so open to any comments/suggestions. Please kindly comment below.

cc @brianjo @mruberry @pytorch/pytorch-dev-infra

**Comment by zou3519** [comment]
@walterddr what do you think about adding information to a page on the developer wiki and linking to it from CONTRIBUTING.md and the other locations? (https://github.com/pytorch/pytorch/wiki). The benefit of the wiki is that it's easier to find out what's going on (I didn't even know we had a .circleci/README.txt), it's easier to edit on the fly without code review, and you can use github search and filter out code: (e.g. https://github.com/pytorch/pytorch/search?q=writing+cuda&type=wikis )

**Comment by walterddr** [comment]
I also realize that making direct changes to CONTRIBUTING.md regarding general information of CI might not be a good idea due to merge conflicts and the large amount of refactoring we need to merge. So I think we should just put it in wiki

**Comment by walterddr** [comment]
> @walterddr what do you think about adding information to a page on the developer wiki and linking to it from CONTRIBUTING.md and the other locations? (https://github.com/pytorch/pytorch/wiki). The benefit of the wiki is that it's easier to find out what's going on (I didn't even know we had a .circleci/README.txt), it's easier to edit on the fly without code review, and you can use github search and filter out code: (e.g. https://github.com/pytorch/pytorch/search?q=writing+cuda&type=wikis )

You beat me to it by commenting 14 seconds  earlier :-P

**Comment by zou3519** [comment]
> > @walterddr what do you think about adding information to a page on the developer wiki and linking to it from CONTRIBUTING.md and the other locations? (https://github.com/pytorch/pytorch/wiki). The benefit of the wiki is that it's easier to find out what's going on (I didn't even know we had a .circleci/README.txt), it's easier to edit on the fly without code review, and you can use github search and filter out code: (e.g. https://github.com/pytorch/pytorch/search?q=writing+cuda&type=wikis )
> 
> You beat me to it by commenting 14 seconds earlier :-P

Lol, nice to see we independently came to the same conclusion :)

**Comment by walterddr** [comment]
created https://github.com/pytorch/pytorch/wiki/Continuous-Integration and slowly migrating contents over.
