### ISSUE TITLE
Bug of ByteTensor

### ISSUE THREAD

**Issue by leftthomas** [pytorch/pytorch#6318]
Here is an example which I want to do:
```python
import torch
a = torch.randn(3)
b = torch.randn(3)
c = [a]
if a in c:
    .....
......
if b in c:
    .....
```
But this code will encounter an issue, which raise
`RuntimeError: bool value of non-empty torch.ByteTensor objects is ambiguous`
So how can I judge if a Tensor in a list?

**Comment by SsnL** [comment]
Adding more context, I am able to reproduce this on master. `a in c` works but `b in c` throws the above error.

**Comment by leftthomas** [comment]
@SsnL ，this is what I am saying, the `b in c` will raise a error

**Comment by fmassa** [comment]
So, the reason why it works in one case but not the other is the following.
According to the python doc, [`x in y` can be translated to](https://docs.python.org/3/reference/expressions.html#membership-test-details)
```python
any(x is e or x == e for e in y)
```
in the first case, `a is c[0]` is True, but in the second case it's not, so it compares `b == a[0]`, which returns a 3d tensor which can't be cast to a single bool.

You have a few possibilities:
1 - if you only want to see if the exact same tensor (no clones) is in the list
```python
if any(a in e for e in c):
```
2 - if you want to accept copies:
```python
if any(a in e or a.equal(e) for e in c):
```

PyTorch behavior is compatible with numpy's in this case btw, and I don't think we will be changing it.
