### ISSUE TITLE
Segmentation fault (core dumped) after iterated for thousands of time

### ISSUE THREAD

**Issue by wineoffree** [pytorch/pytorch#6319]
that BUG happen after I had trained for more than 5000 iterators
at first it's all right.
it reports Segmentation fault (core dumped)
and this is the stack trace:
Thread 258769 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff40fff700 (LWP 27775)]
0x00007fffdf84f447 in THRandom_random ()
   from /home/ygh/.conda/envs/pytorch/lib/python2.7/site-packages/torch/lib/libTH.so.1
(gdb) bt
#0  0x00007fffdf84f447 in THRandom_random ()
   from /home/ygh/.conda/envs/pytorch/lib/python2.7/site-packages/torch/lib/libTH.so.1
#1  0x00007fffdf84f4a9 in THRandom_random64 ()
   from /home/ygh/.conda/envs/pytorch/lib/python2.7/site-packages/torch/lib/libTH.so.1
#2  0x00007fffdf84f61a in THRandom_normal ()
   from /home/ygh/.conda/envs/pytorch/lib/python2.7/site-packages/torch/lib/libTH.so.1
#3  0x00007fffdf567120 in THFloatTensor_normal ()
   from /home/ygh/.conda/envs/pytorch/lib/python2.7/site-packages/torch/lib/libTH.so.1
#4  0x00007fffedaa301a in THPFloatTensor_stateless_randn (
    self=<optimized out>, args=<optimized out>, kwargs=<optimized out>)
    at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/csrc/generic/TensorMethods.cpp:59471
#5  0x00007ffff7a42773 in PyObject_Call ()
   from /home/ygh/.conda/envs/pytorch/bin/../lib/libpython2.7.so.1.0
#6  0x00007fffed6c7892 in THPUtils_dispatchStateless (tensor=0x5555562caa00, 
    name=0x7fffee758dd1 "randn", args=0x7fffa4402f80, kwargs=0x0)
    at torch/csrc/utils.cpp:160
#7  0x00007ffff7adc615 in PyEval_EvalFrameEx ()

config
--------------------------------
- PyTorch or Caffe2:pytorch
- OS:Ubuntu 16.04.4 LTS
- PyTorch version:pytorch-0.3.1
- How you installed PyTorch (conda, pip, source):conda
- Python version:2.7
- CUDA/cuDNN version:cuda8.0/7.0.5
- GPU models and configuration:GeForce GTX 1080Ti NVIDIA-SMI 390.25   Driver Version: 390.25 

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

Thanks for any help or suggestions about it.

**Comment by SsnL** [comment]
Are you doing random sampling in multithreaded settings?
