### ISSUE TITLE
parameters not registered in module

### ISSUE THREAD

**Issue by davidenitti** [pytorch/pytorch#632]
I have a problem when I use dictonaries that contain parameters. Such parameters are not registered in the list of module's parameters.
is there a quick fix for this?

e.g. inside the init of a module:
```
self.waggrs = {}
self.list_relations={}
for rel in range(10):
 self.waggrs[rel]={'w':nn.Parameter(1.+torch.randn(1, 2)),'b':nn.Parameter(torch.zeros(1, 4))}
 self.list_relations[rel]=nn.Linear(numfeatures, numrel)
```

**Comment by apaszke** [comment]
We use GitHub issues for bug reports only, if you have a question about usage please ask it on our forums -> [discuss.pytorch.org](https://discuss.pytorch.org).

**Comment by davidenitti** [comment]
thank you for the quick reply!
I thought that the fact that the parameters are not automatically registered was a bug.
