### ISSUE TITLE
setup.py ignores TORCH_CUDA_ARCH_LIST

### ISSUE THREAD

**Issue by nikoliazekter** [pytorch/pytorch#6321]
I added `export TORCH_CUDA_ARCH_LIST="5.0"` to .profile and rebooted Ubuntu.

`printenv` shows `TORCH_CUDA_ARCH_LIST=5.0` in the list.

But `sudo python3 setup.py install` still builds without 5.0 support.

I used the latest sources from github.

**Comment by zou3519** [comment]
Could you please post a full build log?

**Comment by soumith** [comment]
closed via @sdmonov 's comments

**Comment by nikoliazekter** [comment]
@sdmonov so I tried that but I still get the warning. Looking at the `torch.cuda` sources it seems like the warning is hardcoded and does not actually care about specified capability:

**Comment by soumith** [comment]
@nikoliazekter you will still get the warning, but I think your code will work fine if you compiled for 5.0 from source. The warning indeed is hard-coded for architectures that we support officially.
