### ISSUE TITLE
SVD error message is not correct

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#63220]
## 🐛 Bug

When `torch.linalg.svd` fails the error message is wrong telling that the matrix is singular, while the real reason is that the underlying algorithm did not converge.
See https://github.com/pytorch/pytorch/issues/28293#issuecomment-850822958 for a detailed description.

## Additional context

The implementation of `checkBatchErrors` has an optional function name argument that controls the switch to the correct error message. Having this optional argument makes it simple to write code that looks OK on the surface, but chooses the wrong error message.

cc @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by xwang233** [comment]
Also thanks @andreaskoepf for finding this!
