### ISSUE TITLE
AdaHessian Implementation for PyTorch

### ISSUE THREAD

**Issue by pitneitemeier** [pytorch/pytorch#63221]
## 🚀 Feature
Implement the AdaHessian Optimizer in torch.optim. The optimizer was proposed in the Paper [ADAHESSIAN: An Adaptive Second Order Optimizer for Machine Learning](https://arxiv.org/abs/2006.00719).

## Motivation
The optimizer showed very promising Results on a variety of different Tasks and seems to solve many of the problems of other second order optimizers (only 2*cost in comparison to first order optimizers).
In my opinion it would be great if we could make this available to more people.

## Additional context
There are already inofficial Pytorch implementations available, maybe it is as easy as including them in torch.optim but I do not have the knowledge to judge this.
[Implementation by the authors](https://github.com/amirgholami/adahessian)
[Other more easy to use Implementation](https://github.com/davda54/ada-hessian)

cc @vincentqb @iramazanli

**Comment by iramazanli** [comment]
Thanks for the suggestion, AdaHessian is indeed an interesting algorithm but currently we follow rulebook: 

https://github.com/pytorch/pytorch/wiki/Developer-FAQ#i-have-implemented-an-algorithm--feature-from-a-research-paper-that-is-related-to-optimization-when-is-the-correct-time-to-add-it-to-pytorch-core-

to add optimizers for PyTorch Core. In that respect we would like to wait until the time AdaHessian satisfied the requirements.
