### ISSUE TITLE
[quant] Remove dtype arg requirement from `torch.empty_quantized`

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#63234]
Currently, calling torch.empty_quantized fails if dtype argument isn't specified. 

This is not inline with the API definition where dtype is specified as an optional arg
`- func: empty_quantized(int[] size, Tensor qtensor, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, MemoryFormat? memory_format=None) -> Tensor`

To fix, we should remove the dtype argument from this function since the dtype should be derived from qtensor itself.
We should also update the docs to add this function and reflect this.

Repro 
```
>>> qy = torch.empty_quantized([3], qx)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Creation of quantized tensor requires quantized dtype like torch.quint8

>>> qy = torch.empty_quantized([3], qx, dtype=torch.quint8)
>>> qy
tensor([259.5000, 229.5000,  37.5000], size=(3,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.5, zero_point=3)
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
this is a symptom of the dtype not being carried from python to c++ correctly. issue here: https://github.com/pytorch/pytorch/issues/63356
