### ISSUE TITLE
Function `torch.exp()` return float32 in case of amp float16 context

### ISSUE THREAD

**Issue by Veason-silverbullet** [pytorch/pytorch#63292]
## 🐛 Bug

When amp (torch.cuda.amp.autocast) is enable, tensors should be scaled to float16. The bug lies within the function `torch.exp()`, as it returns float32 tensors when amp is enabled. By the way, the behavior of function `torch.exp_()` is normal.

## To Reproduce

import torch 
with torch.cuda.amp.autocast():
    x = torch.zeros([64, 128], dtype=torch.float16).cuda()
    print(x.dtype)
    print(x.exp().dtype)
    print(x.exp_().dtype)

## Outputs
>>> torch.float16
>>> torch.float32
>>> torch.float16

## Expected behavior
>>> torch.float16
>>> torch.float16
>>> torch.float16

## Attached Bug Reprodution
![amp-bug](https://user-images.githubusercontent.com/46241015/129472923-31645931-9c34-4756-9ce9-c9a1bf8049e2.jpeg)

 - PyTorch Version: 1.9.0
 - OS: Centos OS Linux 7
 - Python version: 3.7.0
 - CUDA/cuDNN version: 11.1

cc @ngimel @mcarilli @ptrblck

**Comment by ptrblck** [comment]
This would be expected, as `torch.exp` uses `float32` as described [here](https://pytorch.org/docs/stable/amp.html#ops-that-can-autocast-to-float32). Also, inplace operations are not using automating (mentioned in the previous section of the docs).
