### ISSUE TITLE
Does dataloader creates a copy of the dataset and consequently use up more memory?

### ISSUE THREAD

**Issue by jingxixu** [pytorch/pytorch#63301]
Does dataloader creates a copy of the dataset and consequently use up more memory?

cc @SsnL @VitalyFedyunin @ejguan

**Comment by astaff** [comment]
Could you please share a self-contained script reproducing the behavior, @jingxixu ?

**Comment by VitalyFedyunin** [comment]
Yes, every instance of DataLoader workers gets serialized version of DataSet Python object and executes it.
