### ISSUE TITLE
dataloader multiprocessing start method might influence performance?

### ISSUE THREAD

**Issue by FateScript** [pytorch/pytorch#63311]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Hello, Pytorch team. I have read your [best practice of multiproecssing](https://pytorch.org/docs/stable/notes/multiprocessing.html) and I understand that "spawn" is a recommended way to start mp. However, I also try to use  "fork" as start method and  my network get worse performance. 

The interesting thing is that when I set `num_workers` to 0 and use "fork" to start mp, which mean do not use mp in dataloader, my network get normal performance.

I could not figure out what  really happens, and I know "fork" after cuda init will lead programe to crashing, but the problem I met seems different. Could you please help me or just give me some possible explaination/hint? Thx anyway.

BTW, I tried torch 1.8(with prefetcher) and 1.3(without prefetcher), this wired problem show up at both version.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by astaff** [comment]
Can you share a self-contained script to reproduce the behavior, @FateScript?

**Comment by ejguan** [comment]
Could you please elaborate the "worse performance"? Can't really interpret the root cause without enough info.

BTW, did you set `pin_memory` to True? Recently, we fixed a bug of `mkl_thread` that leads to performance drop when `pin_memory=True`. And, it's solved in #62891. If this is the problem, you can try pytorch-nightly for testing.

**Comment by FateScript** [comment]
> Could you please elaborate the "worse performance"? Can't really interpret the root cause without enough info.
> 
> BTW, did you set `pin_memory` to True? Recently, we fixed a bug of `mkl_thread` that leads to performance drop when `pin_memory=True`. And, it's solved in #62891. If this is the problem, you can try pytorch-nightly for testing.

Thx for replying. "Worse performance" means I got worse evaluation result. I will try nightly build later.
BTW, could you tell me why "spawn" is recommanded than "fork" ? especially for dataloader (In my opinion dataloader has nothing to do with CUDA runtime, so it really confuses me).

**Comment by FateScript** [comment]
> Can you share a self-contained script to reproduce the behavior, @FateScript?

I will try my best to give you a minimal code to reproduce.  Thanks.

**Comment by FateScript** [comment]
Here is my minimal  code to reproduce @astaff , Now I work around this problem by set random state in `worker_init_fn`. considering what "fork" does in operate system,  the phenomena I observer make sense. 

Unlike #56488, this problem could be reporduced on torch version 1.9.0.

Here is the code:

```python
import random
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.utils.data import Dataset, DataLoader


class RandomDataset(Dataset):

    def __getitem__(self, ind):
        item = [ind, random.randint(1, 10000)]
        return item

    def __len__(self):
        return 20


def worker(rank, main_func, world_size, dist_url):
    dist.init_process_group(backend="nccl", init_method=dist_url, world_size=world_size, rank=rank)
    dist.barrier()
    main_func()


def launch(main_func, start_method="fork"):
    port = 12123  # set your own port if provided port is not available
    dist_url = f"tcp://127.0.0.1:{port}"
    world_size = 2

    mp.start_processes(
        worker,
        nprocs=world_size,
        args=(main_func, world_size, dist_url),
        daemon=False,
        start_method=start_method,
    )

def main():
    loader = DataLoader(RandomDataset(), 2, shuffle=False, num_workers=4)
    rank = dist.get_rank()
    for batch in loader:
        print(f"rank{rank}: {batch}")
        dist.barrier()


if __name__ == "__main__":
    print("Start by fork:")
    launch(main, start_method="fork")
    print("Start by spawn:")
    launch(main, start_method="spawn")
```

**Comment by ejguan** [comment]
> "Worse performance" means I got worse evaluation result.

Why dataloader has impact on model performance?

> could you tell me why "spawn" is recommanded than "fork" ?

For perspective of CUDA, if you have cudaTensor within Dataset, you have to use `spawn` since CUDA context doesn't support fork.
Compared with fork, spawn is safer. Fork would do copy-on-write, IIRC, this creates problem when you use functions from other libraries within Dataset like opencv. (We don't want to fork thread pointer for opencv). In this case, spawn is a better method.

**Comment by FateScript** [comment]
> Why dataloader has impact on model performance?

If data augmention on different rank shares the same state, then distributed model might be influenced. However, this impact might be tiny sometimes. The code I share might help to explain.

**Comment by ejguan** [comment]
> If data augmention on different rank shares the same state, then distributed model might be influenced. However, this impact might be tiny sometimes. The code I share might help to explain.

You should be able to control randomness via `worker_init_fn` for each process.

**Comment by ejguan** [comment]
If you use `fork`, the random state for torch or numpy will be referenced across process. When spawn, the random state for torch will be re-initialized by a random value.

**Comment by FateScript** [comment]
> You should be able to control randomness via `worker_init_fn` for each process

Yes, I solve my problem through this function. 

I will close this issue. Thx a lot @ejguan
