### ISSUE TITLE
observer._PartialWrapper extends the lifetime of Tensors, causing leaks.

### ISSUE THREAD

**Issue by robieta** [pytorch/pytorch#63326]
## 🐛 Bug

When calling quantize_fx.prepare_qat_fx, several Tensors live longer than they should which is triggering the memory leak check in TorchBench. This seems to be related to `fake_quantize.default_per_channel_weight_fake_quant`, and one other `_PartialWrapper` whose name/location I haven't been able to pin down.

## To Reproduce

```
import gc

import torch
from torch.quantization import quantize_fx
from torch.quantization import fake_quantize


def is_tensor(x) -> bool:
    # https://discuss.pytorch.org/t/how-to-debug-causes-of-gpu-memory-leaks/6741/3
    try:
        return (
            torch.is_tensor(x) or
            torch.is_tensor(getattr(x, "data", None))
        )
    except:
        return False


def live_tensors():
    # Only record id and repr, because we don't want to extend the lifetime
    # by holding a reference.
    return {
        id(obj): repr(obj) for obj in gc.get_objects()
        if is_tensor(obj)
    }


def print_new_tensors(initial_live_tensors):
    for tensor_id, tensor_repr in live_tensors().items():
        if tensor_id not in initial_live_tensors:
            print(tensor_repr)


def quantize_model():
    gc.collect()
    quantize_fx.prepare_qat_fx(
        torch.nn.ReLU(),
        {"": torch.quantization.get_default_qat_qconfig('fbgemm')},
    )
    gc.collect()


initial_live_tensors = live_tensors()
quantize_model()
print("Leaked Tensors:")
print_new_tensors(initial_live_tensors)

print("\nLeaked Tensors after _PartialWrapper args clear:")
from torch.quantization import observer
for obj in gc.get_objects():
    if isinstance(obj, observer._PartialWrapper):
        obj.callable_args.clear()
gc.collect()
print_new_tensors(initial_live_tensors)
```

```
Leaked Tensors:
tensor([1], dtype=torch.uint8)
tensor([1], dtype=torch.uint8)
tensor([1.])
tensor([0], dtype=torch.int32)
tensor([1.1921e-07])
tensor(inf)
tensor(-inf)

Leaked Tensors after _PartialWrapper args clear:
```

## Expected behavior

Quantization artifacts should not persist after their logical scope.

## Environment
 - PyTorch Version (e.g., 1.0):  1.10.0.dev20210812 (Aug 12th nightly)
 - OS (e.g., Linux): CentOS (devserver)
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

Every time `prepare_qat_fx` is called, `factory_kwargs` changes to a different instance of `get_factory_kwargs_based_on_module_device`. (And the captures for that function is what is keeping the extra Tensors alive.)

CC @HDCharles @raghuramank100 

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
I'm a bit confused about the repro, QAT is an ongoing process, among those tensors you are outputing, I recognize things like the obs max/min val (+-inf) and the uint8 tensors for the fakequant that are absolutely needed for QAT to work at all.

I'm not sure exactly what is supposed to be getting garbage collected here. The get_factory_kwargs_based_on_module_device instance will be stored on the qconfig of the module, so get_factory_kwargs_based_on_module_device is only accessible as long as the module is, which should also be when the module parameters should be accessible too, right?

**Comment by robieta** [comment]
> so get_factory_kwargs_based_on_module_device is only accessible as long as the module is

It's not; both the module and the quantized version of the module have gone out of scope but a reference to `get_factory_kwargs_based_on_module_device` outlives them.

**Comment by robieta** [comment]
Chatted offline with @HDCharles, the conclusion was that if the factory holds a weakref all of these lifetime issues go away.
