### ISSUE TITLE
bug in bi-lstm's input h0 and c0 when use bi-lstm train netword

### ISSUE THREAD

**Issue by stanli124** [pytorch/pytorch#63323]
## 🐛 Bug

when use numpy.random.randn to init h0 and c0, the output will have nan value; but use torch.randn can train correct, and will not have nan value.
## To Reproduce

1.define a bi-lstm layer
2.use np.random.randn to init h0 and c0 
3.train lstm 

    self.h0 = torch.tensor(np.random.randn(2, self.batch_size, self.hidden_size)).to(self.device)
    self.c0 = torch.tensor(np.random.randn(2, self.batch_size, self.hidden_size)).to(self.device)
   
    self.h0 = torch.randn(2,self.batch_size,self.hidden_size).to(self.device)
    self.c0 = torch.randn(2,self.batch_size,self.hidden_size).to(self.device)
## Environment
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux):win10
 - How you installed PyTorch (`conda`, `pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: 3.6.9 
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: one layer bi-lstm with embedding layer
 - Any other relevant information:

## Additional context

cc @mruberry @rgommers @heitorschueroff

**Comment by astaff** [comment]
Duplicates https://github.com/pytorch/pytorch/issues/63322.
