### ISSUE TITLE
`viable/strict` is more than a week old

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#63335]
At the time of this posting, https://github.com/pytorch/pytorch/tree/viable/strict points to https://github.com/pytorch/pytorch/commit/3c1d1170a4ca2e50a846c69cc61583a29952afee which is 7+ days behind https://github.com/pytorch/pytorch/commit/d5d5f42ea977d61fe21f5986e664efa6609881ff

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by gchanan** [comment]
do we have automated alerting of this?

**Comment by seemethere** [comment]
> do we have automated alerting of this?

We currently do not, we're assessing which jobs might've prevented the promotion right now

**Comment by malfet** [comment]
We should have a rule that post a message to the oncall, if viable strict is 48+ hours behind master

**Comment by driazati** [comment]
> > do we have automated alerting of this?
> 
> We currently do not, we're assessing which jobs might've prevented the promotion right now

We actually do here: https://metrics.pytorch.org/d/L0r6ErGnk/github-status?orgId=1, though we have no data for viable/strict since it's been broken since I stood up the infra for this.

**Comment by malfet** [comment]
Ok, part of the problem was false-positives in internal promotion script after https://github.com/pytorch/pytorch/pull/63022 was merged

**Comment by malfet** [comment]
After the fix have landed, `viable/strict` moved to https://github.com/pytorch/pytorch/commit/d1cbee7b2b1da94ff1a0fa880bd0173de27fb89f

**Comment by seemethere** [comment]
Awesome, with `viable/strict` being updated and an internal fix (D30348055) already submitted I'm going to close this issue.
