### ISSUE TITLE
Nightly windows CUDA builds failing on CUDA install step

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#63344]
See https://app.circleci.com/pipelines/github/pytorch/pytorch/364600/workflows/0ba1f2fd-c831-4840-8312-2b96e9a378d2/jobs/15381589?invite=true#step-104-569

```
C:\w\b>if not exist "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" (
echo CUDA 10.2 installed failed.  
 exit /b 1 
) 
CUDA 10.2 installed failed.
```

Appears to be a transient failure but we should consider this high priority since it appears as though this is happening more often

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm @pytorch/pytorch-dev-infra

**Comment by mszhanyi** [comment]
I think it's duplicated with #63139

**Comment by seemethere** [comment]
Closing in favor of #63139
