### ISSUE TITLE
Nightly Docker image builds are failing with conda install issues (build-publish-docker)

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#63342]
See: https://github.com/pytorch/pytorch/runs/3340344859

Appears to be failing on the install step for nightlies:

https://github.com/pytorch/pytorch/blob/979180cd0118f9379680df9e39fc6acb80d7b80a/Dockerfile#L58-L59

I think this is related to torchtext since I only get installation issues with the following command when I add torchtext:

```
nerdctl run --rm -it continuumio/miniconda3 sh -c 'conda install -c "pytorch-nightly" -c "nvidia" -y python=3.7 pytorch torchvision torchaudio torchtext "cudatoolkit=11.1"'
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @malfet @seemethere @walterddr

**Comment by malfet** [comment]
Could it be a fallout of https://github.com/pytorch/pytorch/issues/63335 <- when nightlies are old enough domain could not be built

**Comment by seemethere** [comment]
I think this might have something to do with this failure:

https://app.circleci.com/pipelines/github/pytorch/text/3760/workflows/01f687a8-220e-4708-a1b3-0e76e55066b2/jobs/120789?invite=true#step-104-344

```
Package __glibc conflicts for:
@|@/linux-64::__glibc==2.31=0
@/linux-64::__glibc==2.31=0
```

**Comment by seemethere** [comment]
I don't actually have the bandwidth to look into this right now so I'm unassigning myself

**Comment by seemethere** [comment]
Perhaps we should just remove torchtext from the nightly docker image / official docker image altogether, thoughts @mthrok

**Comment by seemethere** [comment]
This is now resolved, https://github.com/pytorch/pytorch/runs/3411300066
