### ISSUE TITLE
common_device_type.expectedFailure should report as expected failure

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#63363]
## 🚀 Feature
`torch.testing._internal.common_device_type.expectedFailure` should report as expected failure while being run with python unittest or with pytest.

Using unittest.expectedFailure, a test reports as "expected failure", which is a different status than "success":
![image](https://user-images.githubusercontent.com/5652049/129637747-8fccd4b4-cbc2-4647-96c7-b3c85407b88c.png)
![image](https://user-images.githubusercontent.com/5652049/129637760-565945db-57dc-48de-990e-a8825dc09c54.png)

However, using common_device_type.expectedFailure the test reports as "success":
![image](https://user-images.githubusercontent.com/5652049/129637871-cba3b3b5-574a-42d6-8b8c-fdbba3b3dca2.png)
![image](https://user-images.githubusercontent.com/5652049/129637896-a8f93788-f9e6-42da-8f08-61bc85aacc77.png)

## Motivation

It's really helpful to distinguish between if a test passed or if it "expected fails". This way, as a developer, I know what tests we need to fix. The current state where both of the above report as "passed" means that it's hard to tell without context what actually needs to be fixed.

## Additional context

Discovered while using https://github.com/pytorch/pytorch/issues/62354

cc @mruberry @VitalyFedyunin @walterddr @heitorschueroff

**Comment by heitorschueroff** [comment]
I sent a PR here https://github.com/pytorch/pytorch/pull/63481. Changing the expectedFailure of common_device_type to an XFAIL is not possible because the decision of whether to expect a failure is delayed until the test is called.

**Comment by zou3519** [comment]
Fair enough. Does anyone actually use common_device_type.expectedFailure?

**Comment by heitorschueroff** [comment]
> Fair enough. Does anyone actually use common_device_type.expectedFailure?

Searching for expectedFailure shows people are mostly using unittest.expectedFailure instead of common_device_type.expectedFailure but there are still a few use cases.
