### ISSUE TITLE
codecoverage reporting does not work in GHA 

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#63366]
After https://github.com/pytorch/pytorch/pull/61050 was merged, coverage reporting logic defined in
https://github.com/pytorch/pytorch/blob/b2069e7d01814d776c417042e28133c6b0e5082f/.circleci/verbatim-sources/job-specs/pytorch-job-specs.yml#L197-L201
ceased to work

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
oh is this because it actually needs a token now?

I believe the only reason CircleCI didn't need a token before was because it has some sort of partnership with codecov
