### ISSUE TITLE
__torch_function__ overload resolution between subclasses doesn't work like in the RFC

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#63397]
## 🐛 Bug

[The RFC](https://github.com/pytorch/rfcs/blob/master/RFC-0001-torch-function-for-methods.md#process-followed-during-a-functionmethod-call) states that "A collection of types that implement __torch_function__ is created, with no guaranteed order other than that subclasses come before superclasses.". 

I tried to see what happens with subclasses by creating [this test case](https://gist.github.com/zou3519/f16c490dba17fd00607e74bb52fb5453). The test case seems to show that the Parent's `__torch_function__` is preferred to the Child's. Is this user error or is this a bug?

## Expected behavior

The Child's `__torch_function__` should be preferred. But maybe the RFC is out of date?

## Environment

PyTorch master

## Context

I'm trying to figure out how to hook into the "subclass-superclass overload resolution system" while implementing PythonMode (https://github.com/pytorch/pytorch/pull/62771), but the logic for that doesn't seem to exist in C++.

cc @hameerabbasi @rgommers @peterbell10

**Comment by hameerabbasi** [comment]
That behaviour is only guaranteed for the default version of `__torch_function__`, which I can see you have overridden in this case for both classes.

**Comment by zou3519** [comment]
@ezyang pointed out that I didn't subclass from torch.Tensor and that subclassing fixes the problem: https://gist.github.com/zou3519/07d2559844bd3e772dc9111244729c3e

@hameerabbasi what is the "default version of `__torch_function__`"? (Are there docs on this somewhere?)

**Comment by hameerabbasi** [comment]
By that I meant exactly what you speak of: The version of `__torch_function__` on `torch.Tensor`.

**Comment by zou3519** [comment]
Makes sense. Closing this issue due to user error, thanks for the replies @hameerabbasi.
