### ISSUE TITLE
torch.utils.checkpoint should not only allow variables

### ISSUE THREAD

**Issue by jsrdcht** [pytorch/pytorch#63394]
## 🚀 Feature
Modify CheckpointFunction.forward,the line "ctx.save_for_backward(*args)".The args should be devides into two pieces,becacuse some args needn't to save.
## Motivation
when i write `x = checkpoint(block,x,drop_connect_rate,preserve_rng_state=True)`,drop_connect_rate is a arg needed to be inputed to block.
It caused the error

>  TypeError: save_for_backward can only save variables, but argument 1 is of type float

This leads to that i can't used the parameter that i need

**Comment by ngimel** [comment]
cc @alband for the new checkpointing functionality

**Comment by albanD** [comment]
Hi,

This has been fixed on master.

A simple workaround if you don't have latest pytorch is to use a lambda that only takes the Tensor inputs and capture the other inputs:
```python
x = checkpoint(lambda x: block(x, dtop_connect_rate), x, preserve_rng_state=True)
```
