### ISSUE TITLE
scatter's backward formula should call scatter instead of scatter_

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#63430]
## 🚀 Feature
Replace scatter_ in scatter's backward formula with scatter.

## Motivation

functorch has a hard time with in-place operations and I don't see a good reason why scatter_ gets used here (please correct me if I'm wrong!). cc @albanD @soulitzer for sanity check - please let me know if I missed something here

https://github.com/pytorch/pytorch/blob/495e7e4815d3f9a4000a6671022fd2608440db75/tools/autograd/derivatives.yaml#L1187-L1194

**Comment by soulitzer** [comment]
Could it be because of this?
https://github.com/pytorch/pytorch/issues/56975

**Comment by ngimel** [comment]
#56975 should not affect this, as we can specify the argument with `value`, not `src`. @zou3519 yes, we can use `scatter` instead of `scatter_`, and avoid `clone` in this case, because it will be done in the `scatter` itself.
