### ISSUE TITLE
Norm functions don't call __torch_function__ for weights or bias

### ISSUE THREAD

**Issue by samdow** [pytorch/pytorch#63435]
## 🐛 Bug

Norm functions like GroupNorm only call `__torch_function__` for the inputs, not any weights passed in

## To Reproduce
To demonstrate with print statements, this uses this toy tensor class:
```
import torch
import torch.nn.functional as F

class TestTensor(object):
    def __init__(self, weight):
        self.weight = weight

    def __torch_function__(self, func, _, args=(), kwargs=None):
        print(func)
        print(func == F.group_norm)
```

Case 1:
```
features = TestTensor(torch.randn(3,3))
F.group_norm(features, 3)
```
prints out group_norm and True, so `__torch_function__` is being called with `F.group_norm`

Case 2:
```
features = torch.randn(3,3)
weight = TestTensor(torch.randn(3))
F.group_norm(features, 3, weight=weight)
```
will instead print out group_norm and False. weight's `__torch_function__` is called from `torch.group_norm` instead of `F.group_norm`

## Expected behavior

I would expect in both cases would print group_norm and True, meaning that they're being called with the functional group_norm

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.10.0a0+gitde3a4eb
 - OS (e.g., Linux): Ubuntu 18.04.5 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.9.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: A100-SXM4-40GB
 - Any other relevant information:

## Additional context

If this is not the expected behavior, [this line](https://github.com/pytorch/pytorch/blob/517aa8965abed79a044fb383ad13a841f8f85c1b/torch/nn/functional.py#L2357) might want to look like [this](https://github.com/pytorch/pytorch/blob/517aa8965abed79a044fb383ad13a841f8f85c1b/torch/nn/functional.py#L3286)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @hameerabbasi @rgommers @peterbell10

**Comment by ezyang** [comment]
```
def group_norm(
    input: Tensor, num_groups: int, weight: Optional[Tensor] = None, bias: Optional[Tensor] = None, eps: float = 1e-5
) -> Tensor:
    r"""Applies Group Normalization for last certain number of dimensions.

    See :class:`~torch.nn.GroupNorm` for details.
    """
    if has_torch_function_unary(input):
        return handle_torch_function(group_norm, (input,), input, num_groups, weight=weight, bias=bias, eps=eps)
```

the error is `has_torch_function_unary` need to pass the other tensors too

**Comment by peterbell10** [comment]
This seems to be a general problem that `Optional[Tensor]` arguments aren't being checked.
