### ISSUE TITLE
Add a GitHub actions workflow for Macos

### ISSUE THREAD

**Issue by henrykironde** [pytorch/pytorch#63466]
## 🚀 Feature
Would be nice to have tests runs on Macos in GitHub actions 

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
I've tried to experiment with the possibility of using mac1.metal instances to do this, since the default actions runners are too underpowered, but haven't had much success.

I know @driazati had previously worked on this. see https://github.com/pytorch/pytorch/pull/57474

**Comment by seemethere** [comment]
I'm pretty sure we did this so I'm just going to close it
