### ISSUE TITLE
[op backward] torch.linalg.pinv

### ISSUE THREAD

**Issue by andyjpaddle** [pytorch/pytorch#63474]
hi, I'm learning the op `torch.linalg.pinv`,  I read the source code of forward of the op `torch.linalg.pinv`  in `LinearAlgebra.cpp`. But I didn't find the backward of this op? Can you tell me the procedure of detail backward computation?

**Comment by ejguan** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

IIUC, `torch.linalg.pinv` is a composite function. We are combining the derivatives from the simple functions to compose the derivative of `torch.linalg.pinv`
