### ISSUE TITLE
Multi-gpu training got an unbanlanced memory and redundant processes!!!

### ISSUE THREAD

**Issue by gaojingqian** [pytorch/pytorch#63470]
## 🐛 Bug

I take advantages of "torch.nn.parallel.DistributedDataParallel" to train models in multi-GPUs(4 gpus here) behavior. But once I tried to load pretrained model, the nvidia-smi shown that another 4 redundant processes(8 processes in total) occupied the GPU 0, while not loading pretrained model those processes disappeared(4 process in total). Those redundant processes increase along with the GPU numbers you use, and due to small number of batch size in sum. And could you let me known how to keep redundant processes from appearing when train using multi-GPUs and loading pretrained model??????

## here is it
![无标题](https://user-images.githubusercontent.com/36787418/129865543-1f348405-559d-4640-b655-03e6cfd421a3.png)

## Environment config
 - PyTorch 1.6.0:
 - Linux:
 - pip install pytorch==1.6.0
 - torch.nn.parallel.DistributedDataParallel to change model to multi-gpu
 I have tried to load pretrained model before or after "torch.nn.parallel.DistributedDataParallel", the phenomenon both are same.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by cbalioglu** [comment]
Hi @gaojingqian, do you mind trying to reproduce your problem with PyTorch v1.9?

**Comment by gaojingqian** [comment]
@cbalioglu OK，with PyTorch v1.9.0, the phenomenon is all the same. By the way, the distributed code comes from https://github.com/Tencent/TFace

**Comment by pritamdamania87** [comment]
@gaojingqian `torch.nn.parallel.DistributedDataParallel` doesn't start its own processes, typically the user starts N processes themselves and runs `torch.nn.parallel.DistributedDataParallel` in each one of them. Are you using some sort of launcher script to launch `torch.nn.parallel.DistributedDataParallel`? If so, that script might be creating extra processes.

**Comment by mrshenli** [comment]
It might be because other processes (35531-35533) accidentally used `cuda:0`, and created CUDA context there.

@gaojingqian could you please try setting `CUDA_VISIBLE_DEVICES ` such that each process only sees a single CUDA device?

**Comment by gaojingqian** [comment]
Here load pretrained models should set local rank.
