### ISSUE TITLE
(ROC) ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lelecanfora** [pytorch/pytorch#63480]
## 🐛 Bug

`ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory`
when loading torch ROC

## To Reproduce

1. `pip3 install torch -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html`
2. `pip3 install torchvision==0.10.0 -f https://download.pytorch.org/whl/rocm4.2/torch_stable.html`
3. `from sentence_transformers import SentenceTransformer, util`

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_43555/3476595431.py in <module>
----> 1 from src.nlp.transform import sbert_nlp
      2 transfml = sbert_nlp()

~/app/src/nlp/transform.py in <module>
      1 import os
      2 
----> 3 from sentence_transformers import SentenceTransformer, util
      4 from src.utils import logger
      5 

~/environments/app/lib/python3.9/site-packages/sentence_transformers/__init__.py in <module>
      1 __version__ = "2.0.0"
      2 __MODEL_HUB_ORGANIZATION__ = 'sentence-transformers'
----> 3 from .datasets import SentencesDataset, ParallelSentencesDataset
      4 from .LoggingHandler import LoggingHandler
      5 from .SentenceTransformer import SentenceTransformer

~/environments/app/lib/python3.9/site-packages/sentence_transformers/datasets/__init__.py in <module>
----> 1 from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
      2 from .NoDuplicatesDataLoader import NoDuplicatesDataLoader
      3 from .ParallelSentencesDataset import ParallelSentencesDataset
      4 from .SentencesDataset import SentencesDataset
      5 from .SentenceLabelDataset import SentenceLabelDataset

~/environments/app/lib/python3.9/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py in <module>
----> 1 from torch.utils.data import Dataset
      2 from typing import List
      3 from ..readers.InputExample import InputExample
      4 import numpy as np
      5 import nltk

~/environments/app/lib/python3.9/site-packages/torch/__init__.py in <module>
    196     if USE_GLOBAL_DEPS:
    197         _load_global_deps()
--> 198     from torch._C import *  # noqa: F403
    199 
    200 # Appease the type checker; ordinarily this binding is inserted by the

ImportError: libtinfo.so.5: cannot open shared object file: No such file or directory
```
## Expected behavior

torch (via transformers) imports correctly

## Environment
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.33

Python version: 3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-31-generic-x86_64-with-glibc2.33
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.9.0+rocm4.2
[pip3] torchvision==0.10.0+rocm4.2
[conda] Could not collect

## Additional context

Laptop: IdeaPad-5-15ARE05
GPU: AMD Ryzen 7 4800U with Radeon Graphics

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by jeffdaily** [comment]
Thank you for bringing this to our attention.  Hopefully you can find a quick work-around with `apt install libtinfo5` ?

I believe I have traced the libtinfo.so.5 dependency to the libamd_comgr lib.  This dep is missing from the list of libraries to bundle into the wheel.  But should it be bundled, or should we expect users to install it?

**Comment by jeffdaily** [comment]
I surveyed the various ubuntu versions using their standard docker images.

- ubuntu:16.04 -- libtinfo5 installed by default, located in /lib/x86_64-linux-gnu/libtinfo.so.5
- ubuntu:18.04 -- libtinfo5 installed by default, located in /lib/x86_64-linux-gnu/libtinfo.so.5
- ubuntu:20.04 -- libtinfo6 installed by default, must install libtinfo5 package, then located in /usr/lib/x86_64-linux-gnu/libtinfo.so.5
- ubuntu:21.04 -- libtinfo6 installed by default, must install libtinfo5 package, then located in /usr/lib/x86_64-linux-gnu/libtinfo.so.5

I have looked at the centos images, as well.  The wheels are built using centos 7, and more specifically our rocm/dev-centos-7 image.  By default, the libtinfo.so.5 is not installed in the base centos 7 image, but it is available in our rocm dev image.  

Based on the above survey, it would be far less hassle to just bundle this lib.  This fix will only be available for nightly wheels and the next stable release.  I hope the work-around mentioned earlier can fill the gap.

**Comment by lelecanfora** [comment]
@jeffdaily I confirm that that was the missing library, after ```apt install libtinfo5``` the build works correctly.

**Comment by aaroncsolomon** [comment]
Anyone have a fix for this in RHEL environments? According to yum libtinfo5 is not available for RHEL?

**Comment by jeffdaily** [comment]
Latest nightly wheels should be bundling libtinfo5 now.  PyTorch 1.10 release wheels should also be bundling, once the release is final.  Let us know otherwise.

**Comment by jeffdaily** [comment]
What about ncurses-libs-5?  

https://rpmfind.net/linux/RPM/centos/7.9.2009/x86_64/Packages/ncurses-libs-5.9-14.20130511.el7_4.i686.html

**Comment by marcellodesales** [comment]
> @jeffdaily I confirm that that was the missing library, after `apt install libtinfo5` the build works correctly.

Thank you so much! I got it working as well after doing that on a Docker Container usuing Ubuntu for `GFPGAN`
