### ISSUE TITLE
DataLoader should accept Sampler[Any]

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#63483]
## 🚀 Feature

According to the type hints, the `sampler` argument of `DataLoader` must be `Sampler[int]`. However, I would like to be able to pass a sampler that indexes a `Dataset` with a non-integer index.

## Motivation

I'm working with satellite imagery, where each "image" may be 10K x 10K or larger, and images overlap each other to form a map. For this kind of dataset, "length" and integer index don't really mean anything. Instead, I index the dataset with a lat/long/time bounding box (tuple) and return the corresponding image data. I've designed a custom `Sampler` to handle this, but mypy doesn't think I'm allowed to use this sampler with `DataLoader` due to the strict type hints.

## Pitch

I think `DataLoader` should accept `Sampler[Any]` (or maybe `Sampler[Hashable]`). This will allow greater flexibility for `Dataset`s that aren't indexed with integers.

## Alternatives

I could write my own `DataLoader`, but that seems like overkill.

## Additional context

My custom sampler seems to mostly work as is. However, if `num_workers` is >= 1, I'm encountering the following issue:
```
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py38/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/anaconda/envs/azureml_py38/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda/envs/azureml_py38/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 260, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/anaconda/envs/azureml_py38/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
TypeError: __new__() missing 5 required positional arguments: 'maxx', 'miny', 'maxy', 'mint', and 'maxt'
```
Not sure if I need to pass a custom `init_worker_fn` or what. I'm hoping this isn't a limitation of PyTorch that requires `Sampler[int]`.

@calebrob6

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
I think there are two issues in your case.
- Type hint for Sampler
IIUC, you make sampler run some random operation to generate a tuple to index a data. Can you delegate this functionality to the code inside Dataset?
Just want to check which one are you using, `IterableDataset` or `Dataset`?
- `num_worker > 0`
I don't have your code to figure out the issue. But, I guess this is probably the problem of your custom sampler when multiprocessing is enabled. The index passed into multiprocessing Queue is required to be serialized/deserialized using Pickle. It seems your index doesn't work.
That's also one of the reasons that `Sampler[Hashable]` is incorrect in some cases.

**Comment by adamjstewart** [comment]
> Can you delegate this functionality to the code inside Dataset?

I could, but that kind of defeats the purpose of Sampler. I need several different sampling techniques (random sampling, grid sampler, contrastive sampling, etc.) and I would rather not duplicate the Dataset logic for each one. I was hoping to use Sampler to handle this.

> Just want to check which one are you using, IterableDataset or Dataset?

Dataset

> The index passed into multiprocessing Queue is required to be serialized/deserialized using Pickle.

Let me see if I can make my index pickleable, thanks for the hint!

**Comment by ejguan** [comment]
BTW, you are right about the type hint for sampler in DataLoader. Feel free to submit a PR to improve it.
IMO, `BatchSampler` also needs to change the type hint to support various types.

**Comment by adamjstewart** [comment]
Is Any correct? Pickleable doesn't seem to be a type.

**Comment by ejguan** [comment]
Let's use a TypeVar for now.

**Comment by adamjstewart** [comment]
> > The index passed into multiprocessing Queue is required to be serialized/deserialized using Pickle.
>
> Let me see if I can make my index pickleable, thanks for the hint!

The index is already pickleable, it's just a subclass of tuple:
```python
class BoundingBox(Tuple[float, float, float, float, float, float]):
    """Data class for indexing spatiotemporal data.

    Attributes:
        minx (float): western boundary
        maxx (float): eastern boundary
        miny (float): southern boundary
        maxy (float): northern boundary
        mint (float): earliest boundary
        maxt (float): latest boundary
    """

    def __new__(
        cls,
        minx: float,
        maxx: float,
        miny: float,
        maxy: float,
        mint: float,
        maxt: float,
    ) -> "BoundingBox":
        """Create a new instance of BoundingBox.

        Args:
            minx: western boundary
            maxx: eastern boundary
            miny: southern boundary
            maxy: northern boundary
            mint: earliest boundary
            maxt: latest boundary

        Raises:
            ValueError: if bounding box is invalid
                (minx > maxx, miny > maxy, or mint > maxt)
        """
        if minx > maxx:
            raise ValueError(f"Bounding box is invalid: 'minx={minx}' > 'maxx={maxx}'")
        if miny > maxy:
            raise ValueError(f"Bounding box is invalid: 'miny={miny}' > 'maxy={maxy}'")
        if mint > maxt:
            raise ValueError(f"Bounding box is invalid: 'mint={mint}' > 'maxt={maxt}'")

        # Using super() doesn't work with mypy, see:
        # https://stackoverflow.com/q/60611012/5828163
        return tuple.__new__(cls, [minx, maxx, miny, maxy, mint, maxt])

    def __init__(
        self,
        minx: float,
        maxx: float,
        miny: float,
        maxy: float,
        mint: float,
        maxt: float,
    ) -> None:
        """Initialize a new instance of BoundingBox.

        Args:
            minx: western boundary
            maxx: eastern boundary
            miny: southern boundary
            maxy: northern boundary
            mint: earliest boundary
            maxt: latest boundary
        """
        self.minx = minx
        self.maxx = maxx
        self.miny = miny
        self.maxy = maxy
        self.mint = mint
        self.maxt = maxt

    def __repr__(self) -> str:
        """Return the formal string representation of the object.

        Returns:
            formal string representation
        """
        return (
            f"{self.__class__.__name__}(minx={self.minx}, maxx={self.maxx}, "
            f"miny={self.miny}, maxy={self.maxy}, mint={self.mint}, maxt={self.maxt})"
        )

    def intersects(self, other: "BoundingBox") -> bool:
        """Whether or not two bounding boxes intersect.

        Args:
            other: another bounding box

        Returns:
            True if bounding boxes intersect, else False
        """
        return (
            self.minx <= other.maxx
            and self.maxx >= other.minx
            and self.miny <= other.maxy
            and self.maxy >= other.miny
            and self.mint <= other.maxt
            and self.maxt >= other.mint
        )
```
Will keep investigating to see if I can figure out where that error is coming from.

**Comment by adamjstewart** [comment]
> The index is already pickleable

I stand corrected, I think I've managed to reproduce the issue now:
```python
>>> import pickle
>>> from torchgeo.datasets import BoundingBox
>>> bb = BoundingBox(1, 2, 3, 4, 5, 6)
>>> x = pickle.dumps(bb)
>>> y = pickle.loads(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() missing 5 required positional arguments: 'maxx', 'miny', 'maxy', 'mint', and 'maxt'
```
I should be able to figure things out from here, thanks!

**Comment by ejguan** [comment]
It's an interesting use case. I guess when pickling, python serialize `bb` as tuple, which returns a serialized list (single instance). When deserializing, your `__new__` function takes more argument rather than single. As shown in the bt, `__new__` missing from `maxx` that is the second argument.

Just guess this is not the best way to implement typed tuple.

**Comment by adamjstewart** [comment]
Yeah, I'm not sure of a better way to do things. NamedTuple doesn't allow me to add checks on the input values.

**Comment by adamjstewart** [comment]
Update: just had to implement `__getnewargs__` and pickling seem to work now!

**Comment by ejguan** [comment]
Note: `__reduce__` may also work.

**Comment by adamjstewart** [comment]
Seems like `__getnewargs__` is preferred: https://docs.python.org/3/library/pickle.html#pickling-class-instances

> Although powerful, implementing `__reduce__()` directly in your classes is error prone. For this reason, class designers should use the high-level interface (i.e., `__getnewargs_ex__()`, `__getstate__()` and `__setstate__()`) whenever possible.

**Comment by ejguan** [comment]
Wow. Thanks for pointing it out
