### ISSUE TITLE
[Windows] where could I set MKL and MKLDNN

### ISSUE THREAD

**Issue by etveritas** [pytorch/pytorch#6349]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2:PtTorch
- OS:windows
- PyTorch version:master
- How you installed PyTorch (conda, pip, source):source
- Python version:3.6
- CUDA/cuDNN version:9.0/7.0
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:3.10.1
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by etveritas** [comment]
I have MKL and MKL_dnn on my laptop, but when I build pytorch, it shows can not find this...

**Comment by soumith** [comment]
we do not have official support for Windows yet. If you are installing on windows from source, ask in this thread. https://github.com/pytorch/pytorch/issues/494

Also, please dont use "HELP ME", it is not helpful for us.

**Comment by etveritas** [comment]
@soumith I'm so sorry for my behavior just now, but I really hope your team can make support on windows, and is there a certain day?

**Comment by peterjc123** [comment]
@etveritas To include MKL, you need to add the lib path and include path of them into some env variables.
```
set CMAKE_INCLUDE_PATH=%cd%\\mkl\\include
set LIB=%cd%\\mkl\\lib;%LIB
```
As for MKLDNN, i have never tried it before. So there's nothing to tell right now.

**Comment by peterjc123** [comment]
This is just an example. You can take a look at my repo peterjc123/pytorch-scripts for building from source.

**Comment by etveritas** [comment]
@peterjc123 ok， xiexieni, keyi jiani weixin huozhe qitalianxifangshi ma? fangbian xiangnin qingjiao,hahaha

**Comment by peterjc123** [comment]
@etveritas Haha, nice pingying. My QQ is 170384518.
