### ISSUE TITLE
Deprecation notice at torch.autograd.grad - only_inputs argument

### ISSUE THREAD

**Issue by eliphatfs** [pytorch/pytorch#63544]
## 📚 Documentation
The argument is now ignored in new versions of pytorch, but the documentation has not been updated accordingly.

cc @brianjo @mruberry @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
Thanks for the report, we would accept a PR fixing this.
