### ISSUE TITLE
[RFC] A Launch script with Best Recipe of Deep Learning on Intel Xeon CPU  

### ISSUE THREAD

**Issue by liangan1** [pytorch/pytorch#63556]
## Problem statement 

To accelerate training and inference of deep learning on Intel Xeon CPU, we generally need to enable a set of optimized configurations and best practices which include Non-Uniform Memory Access (NUMA) aware controls, memory allocator and OpenMP thread runtime configurations. A user should know a lot of details about hardware architecture and software features and write a specific launcher script for different workload to use all above optimizations. There is a performance tuning guide in PyTorch tutorial, but it would make the usage much easier to have a general launch script that configures the best recipes automatically for the users.  

## Additional context  

In this RFC, a _process_ denotes one training/inference instance. _Multi-instance_ denotes multiple independent processes without inter-process communication, while _multi-process_ (on single node or multiple nodes) denotes multiple processes with inter-process communication. _Multi-instance_ scenario is generally used for inference workloads, while _multi-process_ can be used for both inference and training workloads. The proposed launch script covers _multi-instance_ and _multi-process_ scenarios for inference workloads, as well as _multi-process_ scenario for distributed training workloads with oneCCL backend of PyTorch. 

Non-uniform memory access (NUMA) is a computation-memory design. Memory access time depends on memory location relative to current working processor. On Xeon platform, each CPU socket is connected to a number of memory slots. The directly connected memories are called local memory. Memories connected to another CPU socket are known as remote memory. Each CPU socket can access both local memories and remote memories. However, since accessing remote memories brings overhead for accessing UPI bus and another CPU socket, memory access is faster with local memory access. All deep learning workloads, training or inference, can get better performance without accessing hardware resources from remote NUMA nodes. ‘numactl’ command in Linux platform can be used to control the cores and memory resources used for each instance. For training workloads, distributed training is a good alternative to do single-node multi-process or multi-node multi-process computations. 

For distributed training workloads on CPU, to avoid resource conflicts between communication and computation tasks, oneCCL features to reserve user designated CPU cores for communication tasks only. Computation and communication tasks are separated on different cores. This non-overlap methodology brings performance benefit.  

OpenMP is often used to speed up the operator kennel performance with multi-threading parallel computation. OMP_NUM_THREADS can be utilized in user level to control the number of threads of OpenMP. For PyTorch, GNU OpenMP is the default OpenMP library, but Intel OpenMP can generally get better performance on Intel CPU. User can enable Intel OpenMP by LD_PRELOAD. Besides, CPU affinity setting controls how workloads are distributed over multiple cores. It affects communication overhead, cache line invalidation overhead, or page thrashing, thus proper setting of CPU affinity brings performance benefits.  

For deep learning workloads, Jemalloc or TCMalloc can get better performance by reusing memory as much as possible than default malloc function. Jemalloc is a general purpose malloc implementation that emphasizes fragmentation avoidance and scalable concurrency support. TCMalloc also features a couple of optimizations to speed up program executions. One of them is holding memory in caches to speed up access of commonly-used objects. Holding such caches even after deallocation also helps avoid costly system calls if such memory is later re-allocated. Use environment variable LD_PRELOAD to take advantage of one of them. 

## Launcher design and implementation 

The main usage scenarios of launch script include training and inference. The multi-instance mode is often used for inference and multi-node mode is used for distributed training with oneCCL DDP backend. Besides, most of configurations are set via environment variables, such as, KMP_AFFINITY for Intel OpenMP library. Thus, the main design goals of the launch script are as follows: 

- The best recipes for deep learning workload used in launcher should be general to different Intel Xeon CPUs and different model workloads.  Besides, it should also auto detect the architecture information to apply these recipes.   

- Most environment used in launcher are tunable, the launcher should provide a default best recipe and give higher priority to user’s config.  

- We should differentiate the common recipe and specific recipe for different usage scenarios. For example, both training and inference can get better performance with Intel OpenMP and TCMalloc allocator, but the MPI config is only used for multi-node training.  

According all above design goals, the basic workflow for our launch script as the following graph. Launcher firstly use “lscpu” (only support Linux platform now) to detect the CPU architecture information. Secondly, launcher will use LD_PRELOAD to enable different allocators which include TCMalloc, Jemalloc and default allocator. By default, MALLOC_CONF will also set if JeMalloc is enabled. Thirdly, launcher choose Intel OpenMP or GNU OpenMP and setup the thread affinity. Lastly, launcher will use numactl to launch multi-instance for multi-instance case while use MPI to launch multi-process for distributed training case. The multi-instance case is NUMA aware and there will be warning information for remote access memory config. for multi-process case, CCL_WORKER_AFFINITY and I_MPI_PIN_DOMAIN is used to avoid the resources conflict between computation and communication.  
<p align="center">
<img src="https://user-images.githubusercontent.com/46986936/130169627-9aba4cac-333a-4d90-9ce4-a9ff5d5b700f.png" width=50% height=50%>
</p>

## Use cases                 

1. single instance 
In this case, launcher will only launch one instance and use all physical cores. Intel OpenMP will be the enabled by default and prefer to use TCMalloc.  
``` shell 
    python -m pytorch.launch python_script args 
```
2. multi-instance  
In this case, launcher will use numactl to launch #ninstances instance and use #ncore_per_instance cores for every instance. Intel OpenMP will be the enabled by default and prefer to use TCMalloc. 
``` shell 
    python -m pytorch.launch --ninstances xxx --ncore_per_instance xx python_script args 
```
3. Single-Node multi-process distributed training 
In this case, launcher will launch #sockets process and use all physical cores in the current socket for every process. Intel OpenMP will be the enabled by default and prefer to use TCMalloc. 
```shell
   python  -m pytorch.launch --distributed  python_script args 
```
4. Multi-Node multi-process distributed training: (e.g. two nodes)    
In this case, launcher will launch 4 process. Intel OpenMP will be the enabled by default and prefer to use TCMalloc.  
```shell
   #rank 0: *(IP: 192.168.10.10, and has a free port: 295000)* 
   python -m pytorch.launch --distributed --nproc_per_node=2 --nnodes=2 --hostfile hostfile python_script args 
```
5. More use cases can be found [here](https://github.com/jingxu10/intel-extension-for-pytorch/blob/jingxu10/launch/tutorials/intro_launch.md). 

  

cc @VitalyFedyunin @ngimel @heitorschueroff @yf225 @glaringlee

**Comment by jgong5** [comment]
cc @VitalyFedyunin

**Comment by louie-tsai** [comment]
@aice-support
