### ISSUE TITLE
Add (at least a daily) DEBUG=1 tests on a common platform

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#63583]
## 🚀 Feature
All of our CI tests currently run with DEBUG=0 for performance reasons. However, there is code that relies on begin run in DEBUG mode to detect errors. We could say that this is not allowed, but it seems very convenient to set asserts at specific locations in the code and raise errors with an exact location in the code base.

## Motivation

This issue is motivated by https://github.com/pytorch/pytorch/issues/61103 . Our external and internal CI did not catch this issue and it's not possible to add a test, because we don't run any test with DEBUG=1

## Pitch

Let's run a single representative CI job with DEBUG=1 (for example linux, python3.7, CUDA 10.2 or whichever we deem most common) on at least a periodic basis (master, nightly, weekly) to detect issues such as the above.

## Alternatives

Alternatively we could ask developers to build in debug mode and run tests locally.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra @walterddr

**Comment by driazati** [comment]
A periodic job sounds pretty reasonable, especially since a lot of devs use DEBUG=1 locally.

cc @pytorch/pytorch-dev-infra

**Comment by walterddr** [comment]
we might want to be very careful on what to test when debug flag is on. since it is going to be slow.

**Comment by malfet** [comment]
Well, DEBUG=ON does not mean code needs to be compiled without optimization, does it? It just adds some extra checks which are unreasonable to do in production code

**Comment by cpuhrsch** [comment]
@malfet - Yes, I don't think there is a reason why you would not want to pass some mild optimization flags, but I can imagine that the debug code enabled could hurt certain optimizations. So then even if you compile it with all optimizations enabled the extra code could void their efficacy.

**Comment by ezyang** [comment]
We need an "optimized but with DEBUG" flag, I don't think we have one right now. DEBUG is "unoptimized with DEBUG" and REL_WITH_DEB_INFO is "optimized with debug info but not DEBUG"

**Comment by cpuhrsch** [comment]
Any progress on this? Because we're still somewhat relying on it within sparse https://github.com/pytorch/pytorch/pull/60838/files. Should we just assume we won't run a CI job like this? Also I've not seen this being run internally.

**Comment by seemethere** [comment]
Closed with https://github.com/pytorch/pytorch/pull/67192
