### ISSUE TITLE
Using FFT on Apple/M1

### ISSUE THREAD

**Issue by DruvPai** [pytorch/pytorch#63592]
## 🐛 Bug

Calling `torch.fft.fft` or its variants on Apple with M1 chip, gives error indicating lack of MKL support.

## To Reproduce

1. Install the latest version of Pytorch from `conda` (currently my version is `cpu_py39he8fdc14_2`.
2. Open a file/Python shell and `import torch`.
3. Give any vector of floats, i.e., `x = torch.randn((3, ))`.
4. Write `torch.fft.fft(x)`.

Sample code:
```py
import torch

x = torch.randn((3, ))
y = torch.fft.fft(x)
print(y)
```
Here's the corresponding stack trace when running this code:
```
Traceback (most recent call last):
  File "/Users/druv/temp.py", line 4, in <module>
    torch.fft.fft(x)
RuntimeError: fft: ATen not compiled with MKL support
```

## Expected behavior

A print-out of a complex-valued vector which is the DFT of `x`.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0.post2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.2 (arm64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:35:11)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-11.5.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.4.2
[pip3] torch==1.9.0.post2
[pip3] torchmetrics==0.5.0
[pip3] torchvision==0.10.0a0
[conda] numpy                     1.21.2           py39h1f3b974_0    conda-forge
[conda] pytorch                   1.9.0           cpu_py39he8fdc14_2    conda-forge
[conda] pytorch-cpu               1.9.0           cpu_py39hd610c6a_2    conda-forge
[conda] pytorch-lightning         1.4.2              pyhd8ed1ab_0    conda-forge
[conda] torchmetrics              0.5.0              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.10.0          py39h0a40b5a_0_cpu    conda-forge
```

## Additional context

Clearly this is because MKL is Intel-specific. Will there be any focus on making functions that invoke MKL platform-agnostic? It would be a great help for many people, as Apple's chip sets continue to grow in popularity.

cc @malfet @albanD @mruberry @peterbell10 @walterddr

**Comment by mruberry** [comment]
cc @nikitaved @albanD

**Comment by malfet** [comment]
This should already be available in [pytorch/conda nightlies](https://anaconda.org/pytorch-nightly/pytorch), please try `conda install pytorch -c pytorch-nightly`
I.e. this is a duplicate of https://github.com/pytorch/pytorch/issues/41592

**Comment by DruvPai** [comment]
Yes, it works, sorry for the delay and double post.
