### ISSUE TITLE
torch.trapezoid broadcasting behavior is incorrect

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#63608]
## 🐛 Bug

PyTorch version: 1.10.0.dev20210819+cu102

I'm not 100% sure, but I think there are both documentation and functional bugs here.  The order I'll describe here is a little strange, but I think it shows the progression most clearly:

## Documentation

> If x is also specified and is one-dimensional, then that dimension defines the spacing for each computation. If x is also specified and is not one-dimensional, then it is broadcast to the shape of y and the corresponding sizes are used for each computation. 
 
I think these two sentences are saying the same thing?  In both cases, the shape has to match up (post broadcast).

## Functional

In this case, the code also doesn't broadcast correctly, for example the number of dimensions have to be exactly the same:
```
>>> torch.trapezoid(torch.randn(3,4,5), torch.randn(1,5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
>>> torch.trapezoid(torch.randn(3,4,5), torch.randn(1,1,5))
tensor([[-0.9381, -0.0843,  0.0344, -0.2251],
        [-0.0255,  0.1701,  0.8801, -0.4495],
        [-0.1404, -0.2855,  0.6871,  0.0302]])
```

## Documentation

The code doesn't actually broadcast x to y (nor should it).  What's actually happening is that:
1) because we are considering differences, we subtract 1 from the shape of x and y at dim and broadcast from there.
```
>>> torch.trapezoid(torch.randn(3,4,5), torch.randn(1,1,2))
tensor([[ 0.3361,  1.2546,  0.0072, -2.2503],
        [ 1.2909,  0.3975, -2.2868,  0.4210],
        [-1.2577,  1.6699, -0.8114, -1.7664]])
```
2) we don't actually broadcast x "to the shape of y", they are broadcast together:
```
>>> np.trapz(torch.randn(3,4,2), torch.randn(1,1,5))
array([[-0.09643671, -0.11016101, -0.14512837,  0.01621936],
       [ 0.5205121 ,  0.12895668, -0.03590207,  0.10696524],
       [-0.05388248, -0.07491347, -0.4282483 ,  0.7440176 ]],
      dtype=float32)
```

cc @mruberry @rgommers @heitorschueroff

**Comment by mruberry** [comment]
cc @NivekT to take a first look
