### ISSUE TITLE
Issue with contiguous() attribute

### ISSUE THREAD

**Issue by sriharsha0806** [pytorch/pytorch#6360]
PyTorch 
- OS: Ubuntu 16.0.4
- PyTorch version: 0.3
- installation of  PyTorch (conda, pip, source): Conda
- Python version: 3.6
- CUDA/cuDNN version: 9
- GPU models and configuration: GTx 1050 Ti

I am using torch.contiguous to change a Tensor Variable but I am getting  the following output contiguous is not attribute of torch

sriharsha@sriharsha-Inspiron-15-7000-Gaming:~$ python 
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.3.1.post2'
>>> exit()
sriharsha@sriharsha-Inspiron-15-7000-Gaming:~$ python test.py
Number of Parameters: 3159080
torch.Size([1, 3, 224, 224])
Traceback (most recent call last):
  File "test.py", line 234, in <module>
    output = model(input)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "test.py", line 134, in forward
    x = self.conv_bn(x, alpha)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "test.py", line 54, in forward
    masked_wt = torch.contiguous(masked_wt)
AttributeError: module 'torch' has no attribute 'contiguous'
sriharsha@sriharsha-Inspiron-15-7000-Gaming:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by SsnL** [comment]
There is no `torch.contiguous` but only `tensor.contiguous`. Use `masked_wt.contiguous()` instead.

**Comment by sriharsha0806** [comment]
ok Thanks
