### ISSUE TITLE
with-ssh doesn't work when job is triggered by probot

### ISSUE THREAD

**Issue by walterddr** [pytorch/pytorch#63603]
This is specifically for the FB-EMPLOYEE ONLY "with-ssh" label. 

It doesn't attach the proper ssh key when trigger by probot, it will show this message:
```
Grabbing public ssh keys from https://github.com/pytorch-probot[bot].keys
Warning: No SSH keys found for user, ssh keys will not be added
```

It would be super helpful if it knows how to attach the actual user's github key instead of the probot's

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
This is true, currently the action that adds ssh keys to the node relies on the `github.actor` value which makes sense why it defers to probot when it's triggered by probot

**Comment by seemethere** [comment]
I've submitted https://github.com/seemethere/add-github-ssh-key/pull/45 as a potential fix for this issue

**Comment by seemethere** [comment]
This should be resolved now with https://github.com/seemethere/add-github-ssh-key/pull/45, going to close, if you see this again we can re-open the issue
