### ISSUE TITLE
Error in git clone pytorch wiki

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#63622]
## 🐛 Bug

There're errors in `git clone https://github.com/pytorch/pytorch.wiki.git`.

## To Reproduce

1. `git clone https://github.com/pytorch/pytorch.wiki.git`

![image](https://user-images.githubusercontent.com/16190118/130163237-89ccc569-66e4-4e0a-9822-3d271b09a305.png)

## Expected behavior

No error in `git clone https://github.com/pytorch/pytorch.wiki.git`

cc @brianjo @mruberry

**Comment by ejguan** [comment]
Can't reproduce on Linux. I think the problem is the file name `Maintainer-notes-for-"@pytorchbot-merge-this-please"-(Archived).md` is not allowed on Windows.

**Comment by ejguan** [comment]
Maybe change the name of md file should be a solution.

**Comment by mszhanyi** [comment]
Thanks @ejguan , I use one Linux to complete my work.
@zou3519 @zhouzhuojie , could you rename these 2 posts.
![image](https://user-images.githubusercontent.com/16190118/130547919-72597a87-96d2-4d3c-aa17-ebb4eda4c999.png)

**Comment by zou3519** [comment]
To clarify: is the problem the special characters?

**Comment by zhouzhuojie** [comment]
Updated

https://github.com/pytorch/pytorch/wiki/Maintainer-notes-for-_pytorchbot-merge-this-please_-(Archived)
https://github.com/pytorch/pytorch/wiki/Where-or-how-should-I-add-documentation

**Comment by mszhanyi** [comment]
Awesome, it works now.
