### ISSUE TITLE
SyncBatchNorm should behave like BatchNorm when running on single GPU.

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#63662]
## 🚀 Feature
SyncBatchNorm should fall back and behave like BatchNorm when running on single GPU. However, currently it throws an error like:
```
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

## Motivation

This is useful to test-run models (with SyncBatchNorm) on a single GPU during development or debugging.
Currently, we had to if-else and select BatchNorm or SyncBatchNorm based on #GPUs.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23 @albanD @mruberry @jbschlosser

**Comment by pritamdamania87** [comment]
Can you just use SyncBatchNorm even for a single GPU and just create a process group with world_size 1? This way your code is independent of the number of GPUs.

**Comment by ppwwyyxx** [comment]
Yes we could create a dummy 1-GPU process group. But I think this is not user-friendly, because we'll then need to have a strange line during job setup that creates a process group that seems useless - its only purpose is to make SyncBatchNorm happy. 
The purpose of the issue is to avoid workarounds like creating a dummy process group or if-else checks to select BatchNorm/SyncBatchNorm. I expect the behavior of SyncBatchNorm to be the same as BatchNorm when it founds that the global process group is not initialized.

As a bonus, when running in single-process mode, SyncBatchNorm could allow CPU inputs instead of throwing an error. This would be very valuable for running unittests (since GPU tests are difficult in fb).

**Comment by pritamdamania87** [comment]
My proposal was to actually have the same code for development and your actual job run as well. My understanding is that for your actual training job, you will use SyncBatchNorm with > 1 GPUs, in that case you would write code where you will initialize process group and use SyncBatchNorm. Now you can just make the world_size in init_process_group a parameter and run the same code for dev/testing by just setting world_size 1.

My proposal was to make dev/testing similar to your actual production job run and not add any dummy process group or if-else checks. 

> I expect the behavior of SyncBatchNorm to be the same as BatchNorm when it founds that the global process group is not initialized.

This might lead to unintended consequences. For example if a user is actually running a job on 8 GPUs and wants to use SyncBatchNorm but forgets to initialize the process group, this would silently convert SyncBatchNorm to BatchNorm and might result in incorrect results. It is probably better to have an explicit failure rather than silent correctness issues.

**Comment by ppwwyyxx** [comment]
>  in that case you would write code where you will initialize process group and use SyncBatchNorm. Now you can just make the world_size in init_process_group a parameter and run the same code for dev/testing by just setting world_size 1.

The problem is that the code where we initialize process group may not exist or be in the right place, so that's not a very good/accessible place to add workarounds.

 A simple example is when writing unittests for models, one would need to write an extra `init_process_group` to create a dummy process group in every such unit test, just because the model __may__ have SyncBatchNorm. 

Another example would be to train inside trainer systems like lightning, which take full control of creating processes. A user that implements models will not be able to change lightning's code and therefore won't be able to add this workaround.

>  if a user is actually running a job on 8 GPUs and wants to use SyncBatchNorm but forgets to initialize the process group

If a user forgets to initialize process group, DDP will fail way before SyncBatchNorm runs. So typically I feel this won't lead to silent errors. Although there might be other valid cases.

**Comment by an99990** [comment]
Would this affect loading weights or saving weights ? I am training a model using detectron2 framework. using 
`    dist.init_process_group(
        backend="nccl", init_method="tcp://localhost:23456", rank=0, world_size=1
    )`
makes it possible to train on single GPU, however when I am loading the weights to test , i get 

```
Some model parameters or buffers are not found in the checkpoint:
basis_module.seg_head.0.weight
basis_module.seg_head.1.{bias, running_mean, running_var, weight}
basis_module.seg_head.3.weight
basis_module.seg_head.4.{bias, running_mean, running_var, weight}
basis_module.seg_head.6.{bias, weight}
```

So i try stopping the training and reloading the weights but I dont get that warning.
Does anyone have a theory on this matter ?

**Comment by wenbo-cv** [comment]
> backend="nccl", init_method="tcp://localhost:23456", rank=0, world_size=1

Thank you for the answer. It helps me run my training code successfully.

**Comment by MathijsNL** [comment]
@an99990 What lines did you add to make this work?

When I add the **dist.init_process_group** I get a **CUDA out of memory.**  error instantly.
