### ISSUE TITLE
Minor documentation improvements.

### ISSUE THREAD

**Issue by Stevenjin8** [pytorch/pytorch#63728]
## 📚 Documentation

Hello!

I think the docs for the [Word Embeddings](https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html) could be improved. Mainly, `CONTEXT_SIZE` is defined in the last two code examples, but isn't used to preprocess the data.

Also, I think it might be a good idea to get rid of the punctuation/lowercase the raw training data in the last two code examples (`test_sentence` and `raw_text` correspondingly).

I'm happy to make these changes. 

Potential improvements:

- [ ] unused variables in https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html
- [ ] more text preprocessing in https://pytorch.org/tutorials/beginner/nlp/word_embeddings_tutorial.html
- [ ] inconsistent quotation and spacing in https://pytorch.org/tutorials/intermediate/dist_tuto.html
- [ ] tex \left \right in https://pytorch.org/tutorials/intermediate/dist_tuto.html
- [ ] Word embeddings tutorial not accessible from the tutorials main page.

cc @brianjo @mruberry @albanD @jbschlosser

**Comment by jbschlosser** [comment]
Hey @Stevenjin8, thanks for the report! We'd accept a PR addressing this.

**Comment by Stevenjin8** [comment]
Hey @jbschlosser, I didn't see your reply. Sorry about that. I opened a [ticket](https://discuss.pytorch.org/t/grammar-in-docs-unused-variables/131008) on the forums. I've been going through the docs quite a bit so I'll collect potential issues in this issue and make a PR sometime soon.

**Comment by Stevenjin8** [comment]
Moving this issue [here](https://github.com/pytorch/tutorials/issues/1666).
