### ISSUE TITLE
torch.nn.Linear() behaves randomly

### ISSUE THREAD

**Issue by HMEIatJHU** [pytorch/pytorch#6373]
Linear layer torch.nn.Linear() behaves randomly
Two passes of exactly the same input returns different outputs
--------------------------------
I would like to report a bug:
- PyTorch or Caffe2: PyTorch
- OS: OS X Yosemite 10.10.2
- PyTorch version: 0.4.0a0+64e94f0
- How you installed PyTorch (conda, pip, source): source
- Python version: Python 3.6.3
- CUDA/cuDNN version: NO
- GPU models and configuration: NO
- GCC version (if compiling from source): GCC 7.2.0
- CMake version: 3.9.4

- A script to reproduce the bug. 
```py
import torch
from torch.autograd import Variable

torch.manual_seed(0)

dim = 10000
lin1 = torch.nn.Linear(dim,10)
infeat = torch.FloatTensor(1,dim).fill_(1.0)

infeat = Variable(infeat)

out = lin1(infeat)
out_new = lin1(infeat)

print(out)
print(out_new)
print("sum of abs diff is {}".format((out - out_new).abs().sum()))

lin2 = torch.nn.Linear(dim,100)

out = lin2(infeat)
out_new = lin2(infeat)

print(out)
print(out_new)
print("sum of abs diff is {}".format((out - out_new).abs().sum()))
```

**Comment by matthewfl** [comment]
To add to this, we also observed that there were some segfaults when running with this version of pytorch when trying to train.  I believe that it is possibly related to the above issue in that there might be a pointer that is uninitialized when performing the Linear operations causing it to access random memory.

**Comment by SsnL** [comment]
I can't reproduce this with master.

**Comment by fmassa** [comment]
Maybe a problem with your blas installation?

**Comment by HMEIatJHU** [comment]
@SsnL @fmassa Thanks for feedback. 
I tried with different environments, and this bug only shows up in the particular environment with the particular version of PyTorch listed above.

I used the same blas for different environments so it does not seem a blas installation issue?

**Comment by goldsborough** [comment]
Can you try again with current master and close this issue if it does not persist?

**Comment by HMEIatJHU** [comment]
@goldsborough yes i did.
