### ISSUE TITLE
‘DeviceType’ is ambiguous

### ISSUE THREAD

**Issue by q671383789** [pytorch/pytorch#63735]
libtorch/include/ATen/core/DeprecatedTypeProperties.h:41:1: error: reference to ‘DeviceType’ is ambiguous DeviceType device_type() const.
really needs some help.
Ubuntu 16.04 cuda10.2 cudnn7.6.5

**Comment by bdhirsh** [comment]
Hi,

Please repost your question in the PyTorch forum for help. Thanks!
