### ISSUE TITLE
Slicing with : from a collection

### ISSUE THREAD

**Issue by damtharvey** [pytorch/pytorch#63741]
## 🚀 Feature
Be able to put `:` in a collection to use in an index.

## Motivation

Be able to slice a `Tensor` using varying numbers of `:`.

## Pitch

I would like a function `f` to do this.
```
def f(x: torch.Tensor, n: int) -> torch.Tensor:
    return eval(f"x[{':, ' * n}0]")
```
I think this is ugly and I would like to say 
```
    return x[*(:,) * n, 0]
```

## Alternatives

Building a string and using `eval()`. If there is a better way, please inform me.

**Comment by ngimel** [comment]
You can use ellipsis `x[..., 0]` to get this behavior
