### ISSUE TITLE
type(any_tensor) is always Variable

### ISSUE THREAD

**Issue by davidbau** [pytorch/pytorch#6374]
On current builds of pytorch, `type(t)` for any tensor `t` seems to always be `autograd.Variable` now. 
Is there any way to get the actual tensor type back out, e.g., for coercing one tensor to the same data type of another tensor?

```
>>> import torch
>>> type(torch.zeros(2))
<class 'torch.autograd.variable.Variable'>
```

**Comment by SsnL** [comment]
You may want to update your copy
```
>>> import torch
>>> type(torch.zeros(2))
<class 'torch.Tensor'>
>>> 

```
