### ISSUE TITLE
CUDA memory leak problem

### ISSUE THREAD

**Issue by gudiandian** [pytorch/pytorch#63752]
## ❓ Questions and Help

I am encountering a  CUDA memory leak problem with torch.distributed, I have posted [a post](https://discuss.pytorch.org/t/cuda-memory-not-released-by-torch-cuda-empty-cache/129913) in the forum to describe the symptom. 

I wish to train multiple models in turn in one python script. After the training of one model, I will run this to release memory, so that there will be enough memory for the training of the next model:
```
def destruction(self):
    torch.cuda.synchronize(device=self._get_device())
    dist.destroy_process_group(group=self.group)
    del self.optimizer
    del self.ddp_model
    del self.train_loader
    torch.cuda.set_device(device=self._get_device())
    torch.cuda.empty_cache()
    torch.cuda.synchronize(device=self._get_device())
```

However, from `nvidia-smi`, I see that after calling destruction() each time, there was still some GPU memory allocated. And the unreleased memory increase as I train more model. For example, after training the 3rd model and calling destruction(), the memory allocation is like this:

![image](https://user-images.githubusercontent.com/23579389/130447550-c0e50c36-c720-4bf2-ab8a-0e0d4f98b215.png)

Then, after training the 4th model, the memory allocation is like this:

![image](https://user-images.githubusercontent.com/23579389/130447573-88485097-819b-443e-b01d-b9cf33f9e48d.png)

Finally, this leads to OOM error in training. 

I have examined with `torch.cuda.memory_allocated(device=device)` API. After I ran `torch.cuda.empty_cache()`, the output is always 0, which is conflict with the output of `nvidia-smi`. 

I also tried to use Numba to clean up CUDA context, but it doesn't work. You may refer to [this post](https://numba.discourse.group/t/cannot-reset-cuda-context-with-numba/856) in Numba forum for details.

I am wondering that is there any way to clean up CUDA memory in PyTorch? or is there any way to trace the details of CUDA memory allocation? I would really appreciate any help. Thank you!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23 @ngimel

**Comment by mrshenli** [comment]
Hey @gudiandian, a few questions:

1. Could you please share a repro? 
2. Do you still see memory leak when doing local training without using DistributedDataParallel? 
3. Which version of PyTorch are you using?

BTW, the process group should be destroyed after deleting DDP model, but I don't think that is relevant to the memory leak.

**Comment by gudiandian** [comment]
> Hey @gudiandian, a few questions:
> 
> 1. Could you please share a repro?
> 2. Do you still see memory leak when doing local training without using DistributedDataParallel?
> 3. Which version of PyTorch are you using?
> 
> BTW, the process group should be destroyed after deleting DDP model, but I don't think that is relevant to the memory leak.

Thanks for your reply! 
1. I am really sorry that I cannot share the repo because it is not allowed to share the codes outside of the company. 
2. I just tried to replace the DDP model with the original model, and I still see this memory leak. However, in my code I need to build up some sub-process groups with `dist.new_group` API because there can be multiple training tasks on different GPUs at the same time. If I do not build up these sub-groups, there won't be such memory leak! I am pretty sure that I ran `dist.destroy_process_group(group=group)` to destroy all the subgroups after running `destruction()`. 
3. I am using PyTorch

Do you have any idea why `dist.destroy_process_group(group=group)` cannot clean up the resources of the subgroups? Thanks again!

**Comment by mrshenli** [comment]
Hey @gudiandian 

> Do you have any idea why `dist.destroy_process_group(group=group)` cannot clean up the resources of the subgroups?

This is because `ProcessGroup` is just an object wrapping communication resources and APIs, and it does not own the model  parameters or other tensors. 

> I just tried to replace the DDP model with the original model, and I still see this memory leak. 

In this case, are you still using collective communications and process groups?

>  If I do not build up these sub-groups, there won't be such memory leak! 

Could you please share a code sample of how do you build these sub-groups? And could you please try both gloo and nccl backend and see if the behavior is the same?

If the switch between different models are not that frequent, one work-around could be letting the existing sub-processes to exit and re-spawn a set of new ones. This should clear all memories allocated by the previous sub-processes.

**Comment by gudiandian** [comment]
> Hey @gudiandian
> 
> > Do you have any idea why `dist.destroy_process_group(group=group)` cannot clean up the resources of the subgroups?
> 
> This is because `ProcessGroup` is just an object wrapping communication resources and APIs, and it does not own the model parameters or other tensors.
> 
> > I just tried to replace the DDP model with the original model, and I still see this memory leak.
> 
> In this case, are you still using collective communications and process groups?
> 
> > If I do not build up these sub-groups, there won't be such memory leak!
> 
> Could you please share a code sample of how do you build these sub-groups? And could you please try both gloo and nccl backend and see if the behavior is the same?
> 
> If the switch between different models are not that frequent, one work-around could be letting the existing sub-processes to exit and re-spawn a set of new ones. This should clear all memories allocated by the previous sub-processes.

Thank you so much! I will close the issue as I have decided to use a workaround.
