### ISSUE TITLE
Negative OpInfo tests

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#63766]
## 🚀 Feature
We should extend OpInfo tests to check that error cases correctly raise an error instead of crashing or returning something silently wrong.

## Motivation

Decompositions. Let's say we want to define decompositions for operators. Then we need a mechanism to test that the decomposition is correct. In addition to the existing OpInfo machinery, which will test that correct inputs produce the desired outputs, we would also like a mechanism to check that inputs that should cause an error to be raised do raise an error rather than crashing or returning something silently incorrect.

## Pitch

This needs design.

cc @mruberry @VitalyFedyunin @walterddr

**Comment by mruberry** [comment]
I think https://github.com/pytorch/pytorch/pull/67354 addresses this, although additional architecture extensions (like supporting different CPU and CUDA messages) may be needed in the future. Those additions should probably be tracked in new issues (one idea per issue).
