### ISSUE TITLE
GHA Windows builds were failing for a short period of time

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#63771]
Have a look at https://github.com/pytorch/pytorch/runs/3396094904 and https://github.com/pytorch/pytorch/runs/3396094884

Failure signature is suspiciously similar to one we had in the past when old WinSDK image was installed:
```
C:\actions-runner\_work\pytorch\pytorch\pytorch-1157045279\third_party\kineto\libkineto\src\ThreadUtil.cpp(92): error C2065: 'SetThreadDescription': undeclared identifier
C:\actions-runner\_work\pytorch\pytorch\pytorch-1157045279\third_party\kineto\libkineto\src\ThreadUtil.cpp(98): error C2064: term does not evaluate to a function taking 2 arguments
C:\actions-runner\_work\pytorch\pytorch\pytorch-1157045279\third_party\kineto\libkineto\src\ThreadUtil.cpp(119): error C2065: 'GetThreadDescription': undeclared identifier
C:\actions-runner\_work\pytorch\pytorch\pytorch-1157045279\third_party\kineto\libkineto\src\ThreadUtil.cpp(124): error C2064: term does not evaluate to a function taking 2 arguments
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Can we perhaps print a base AMI version?

**Comment by seemethere** [comment]
This is mostly related to the AMI deploy we had last night related to https://github.com/pytorch/test-infra/pull/91

Still investigating what exactly happened but it's related to Windows SDK issues

**Comment by seemethere** [comment]
Testing with https://github.com/pytorch/test-infra/pull/105 to see if that resolves

**Comment by seemethere** [comment]
Turns out these issues were actually resolved in our own internal packer build scripts but had not been propagated to our new open source home, submitted https://github.com/pytorch/test-infra/pull/106 to resolve and am building new AMIs now to test with

**Comment by malfet** [comment]
Everything looks good, closing
