### ISSUE TITLE
Compiling vs Installing via pip

### ISSUE THREAD

**Issue by GarrisonD** [pytorch/pytorch#6380]
Is there any reason why should I prefer compiling PyTorch from source to installing it by `pip`?

**Comment by GarrisonD** [comment]
And why did you stop to upload fresh Docker images of PyTorch to Docker Hub?

The latest one was built and uploaded 8 months ago 😢

**Comment by GarrisonD** [comment]
@ezyang

**Comment by albanD** [comment]
Hi,

Please use the [forum](https://discuss.pytorch.org/) for questions.
We use the github issue for bug report / features only.

**Comment by GarrisonD** [comment]
@albanD sure! sorry for that!
