### ISSUE TITLE
WinML or DirectML support planned?

### ISSUE THREAD

**Issue by oscarbg** [pytorch/pytorch#6381]
As Windows support seems coming in 0.4 I would like to request WinML and or DirectML support.. it’s Windows only API, but this should support AMD and Intel GPUs using D3D12 backend or even DirectML which with custom metacommands seems even able to use tensor cores on Volta GPUs..
Hope to hear news at least by Build conference in May

**Comment by soumith** [comment]
We dont have plans for direct vertical integration of WinML or DirectML support.
We do support ONNX exporting of models that can be executed by WinML

**Comment by Coderx7** [comment]
@soumith has anything changed regarding your policy since roughly 2.5 years ago?

**Comment by Immortalin** [comment]
@apaszke especially since Ryzen cores are very common now

**Comment by melihozaydin** [comment]
support for 
`tensor.to("dml")`
would` be really nice and clean (at least for the user experience ).

instead of having to do `pip install pytorch-directml`, as it has problems with libraries that use torch like torchvision etc.
