### ISSUE TITLE
`min`/`max` require a huge allocation on GPU

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#63869]
## 🐛 Bug

`torch.max` and `torch.min` use a large amount of memory due to `static constexpr bool can_accumulate_in_output = std::is_convertible<arg_t, out_scalar_t>::value;` being `false` in `Reduce.cuh` and requiring a huge allocation for `sizeof(thrust::pair<scalar_t, int64_t>)` times the number of elements. The result is that a tensor that uses ~1/8 of GPU memory will result in an OOM if we try to call max.

## To Reproduce
On a ~24 GiB card:
```
import torch
a = torch.rand(1200, 1000, 3, 256).cuda() # about 3.4GiB
b = a.max(dim=2)
```
On a ~48 GiB card:
```
import torch
a = torch.rand(2300, 1000, 3, 256).cuda() # about 6.6GiB
b = a.max(dim=2)
```

CC @ngimel @ptrblck

cc @ngimel @heitorschueroff

**Comment by ngimel** [comment]
cc @jjsjann123, looks like allocated owned_buf_ptr is significantly bigger than it needs to be
