### ISSUE TITLE
Make Windows build stop clobbering tools/shared/cwrap_common.py

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6386]
Because this file is implemented as a symlink, in Windows we copy the source over it as part of the build process. This dirties the working copy, and is generally annoying. It would be good to work out a way to make this not happen.

CC @peterjc123

**Comment by peterjc123** [comment]
How could this be done? Copy this file in the `setup.py` script and add it to `.gitignore`?

**Comment by ezyang** [comment]
I think you would also have to delete the symlink. Assuming no one tries to access the file before the copy happens (I'm not sure if this is the case or not), it should be.
