### ISSUE TITLE
[torch.distributed.run] Assert (and fail fast w/ message) init_method=="env://" on the trainer

### ISSUE THREAD

**Issue by kiukchung** [pytorch/pytorch#63874]
## 🐛 Bug

Per launch-utility [documentation](https://pytorch.org/docs/stable/distributed.html#launch-utility) `init_method` other than `env://` used for `dist.init_process_group(init_method)` is incompatible with `torch.distributed.launch` and `torch.distributed.run`. 

![image](https://user-images.githubusercontent.com/43595115/130670330-b55d0e26-fbd4-4dad-bb2a-60bb35e55b0a.png)

this technically makes `torch.distributed.launch` not 100% backwards compatible for cases where the training script's process group was initialized as (for example):

```
# in training_script.py

dist.init_process_group(init_method="tcp://localhost:6000")
```

Which is the case with megatron's [initialize.py](https://github.com/microsoft/Megatron-DeepSpeed/blob/main/megatron/initialize.py#L213)

## To Reproduce

1. Create a training script.py as such

     ```python
      import torch.distributed as dist

      if __name__ == "__main__":
           dist.init_process_group(backend="gloo", init_method="tcp://localhost:6000", world_size=1, rank=0)
     ```
2. Run it with
    ```
    $ LOGLEVEL=INFO python -u -m torch.distributed.run \
                   --max_restarts 0 \
                    --nproc_per_node 1 \
                    --nnodes 1 \
                    --master_addr $(hostname) \
                    --master_port 6000 \ 
                    ~/test_script.py
    ```
3. Observe the `Address already used` error.

```
(venv385) ubuntu@ip-172-31-26-180% LOGLEVEL=INFO python -u -m torch.distributed.run --max_restarts 0 --nproc_per_node 1 --nnodes 1 --master_addr $(hostname) --master_port 6000 ~/tmp/test.py                                                                           ~/tmp
[INFO] 2021-08-24 18:36:44,701 run: Running torch.distributed.run with args: ['/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py', '--max_restarts', '0', '--nproc_per_node', '1', '--nnodes', '1', '--master_addr', 'ip-172-31-26-180', '--master_port', '6000', '/home/ubuntu/tmp/test.py']
[INFO] 2021-08-24 18:36:44,703 run: Using nproc_per_node=1.
[INFO] 2021-08-24 18:36:44,703 api: Starting elastic_operator with launch configs:
  entrypoint       : /home/ubuntu/tmp/test.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : ip-172-31-26-180:6000
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 0
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[INFO] 2021-08-24 18:36:44,705 local_elastic_agent: log directory set to: /tmp/torchelastic__vqrf9if/none_m4vzbxcx
[INFO] 2021-08-24 18:36:44,705 api: [default] starting workers for entrypoint: python
[INFO] 2021-08-24 18:36:44,705 api: [default] Rendezvous'ing worker group
[INFO] 2021-08-24 18:36:44,705 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:52: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
[INFO] 2021-08-24 18:36:44,707 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=ip-172-31-26-180
  master_port=6000
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

[INFO] 2021-08-24 18:36:44,708 api: [default] Starting worker group
[INFO] 2021-08-24 18:36:44,708 __init__: Setting worker0 reply file to: /tmp/torchelastic__vqrf9if/none_m4vzbxcx/attempt_0/0/error.json
Traceback (most recent call last):
  File "/home/ubuntu/tmp/test.py", line 4, in <module>
    dist.init_process_group(backend="gloo", init_method="tcp://localhost:6000", world_size=1, rank=0)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 142, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
[ERROR] 2021-08-24 18:36:49,718 api: failed (exitcode: 1) local_rank: 0 (pid: 34564) of binary: /home/ubuntu/.pyenv/versions/venv385/bin/python
[ERROR] 2021-08-24 18:36:49,719 local_elastic_agent: [default] Worker group failed
[INFO] 2021-08-24 18:36:49,719 api: Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:70: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
[INFO] 2021-08-24 18:36:49,719 api: Done waiting for other agents. Elapsed: 0.00044846534729003906 seconds
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "34564", "role": "default", "hostname": "ip-172-31-26-180.us-west-2.compute.internal", "state": "FAILED", "total_run_time": 5, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [1]}", "agent_restarts": 0}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": null, "group_rank": 0, "worker_id": null, "role": "default", "hostname": "ip-172-31-26-180.us-west-2.compute.internal", "state": "SUCCEEDED", "total_run_time": 5, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\"}", "agent_restarts": 0}}
/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:354: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 34564 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py", line 637, in <module>
    main()
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py", line 629, in main
    run(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py", line 621, in run
    elastic_launch(
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
    /home/ubuntu/tmp/test.py FAILED
=======================================
Root Cause:
[0]:
  time: 2021-08-24_18:36:49
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 34564)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************
```

## Expected behavior
Ideally the launcher should work. But in this case, lets just roll forward to make the error more accurate: the command failed because any other `init_method` is incompatible with `torch.distributed.launch` and `torch.distributed.run`, the `Address already used` is a side-effect.

## Proposed Fix
There's a couple ways to fix this (options mutually exclusive so pick one):

1. In `def init_process_group()` check whether this trainer is launched using the launcher and fail-fast with a clear error message if `init_method != env://`. Whether the launcher was used to launch the trainer can be checked using an env var that is set from the launcher side (better yet from the elastic agent) (e.g. TORCHELASTIC_LAUNCHED or something of the sorts). 
     1. **Pros:**
          1. users get a much better error message so that they can modify their training scripts accordingly
          1. a good forcing function to migrating all distributed users over to elastic for uniform launch experience
     1.  **Cons:**
          1. launcher is still not 100% backwards compatible, may have downstream impact if users do not own the training script.

2. Make `init_method="tcp://master_addr:master_port"` reuse the torchelastic agent's TCP store by checking the env var `TORCHELASTIC_USE_AGENT_STORE` (see how [init_method=env:// supports this]( https://github.com/pytorch/pytorch/blob/master/torch/distributed/rendezvous.py#L187)). What will happen is that all trainer ranks just connect to the agent 0's (agent master) TCPStore rather than creating a TCPStore server on trainer rank 0 (which is why the address already used error is happening).
     1. **Pros:**
          1. launcher is more backwards compatible (at least with tcp)
      2. **Cons:**
          1. does not cover other init_methods (e.g. file:// - although this one should be compatible already)

## Environment

Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.23

Python version: 3.8.5 (default, Mar 24 2021, 22:32:23)  [GCC 5.4.0 20160609] (64-bit runtime)
Python platform: Linux-4.4.0-1102-aws-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.3.5
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.9.0
[pip3] torchelastic==0.2.3.dev0
[pip3] torchmetrics==0.3.2
[pip3] torchserve==0.4.0
[pip3] torchvision==0.9.1
[pip3] torchx==0.1.0rc0
[conda] Could not collect

## Additional context

1. Reported by @stas00  on Slack.
2. Once this is fixed, create an issue with [Megatron-DeepSpeed](https://github.com/microsoft/Megatron-DeepSpeed) to propose a fix for the initiazer (https://github.com/microsoft/Megatron-DeepSpeed/blob/main/megatron/initialize.py#L213). The exact semantics of the fix differs depending on what option was selected from the proposed fixes.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by stas00** [comment]
Right! I thought that we would need to update the upstream repo, which is https://github.com/NVIDIA/Megatron-LM, but I see that it relies on the default `init_method`:

https://github.com/NVIDIA/Megatron-LM/blob/68797d90935354cf8510dd84711ab6ef5db095f1/megatron/initialize.py#L178-L181

So we only need the fix in https://github.com/microsoft/Megatron-DeepSpeed and then I will sync its downstream fork (https://github.com/bigscience-workshop/Megatron-DeepSpeed).

**Comment by kiukchung** [comment]
@stas00 I managed to make torchelastic backwards compatible with init_method=tcp:// (so we don't have to make any changes to megatron - for now). Once my PR (https://github.com/pytorch/pytorch/pull/63910) lands I'll still go ahead and do these two followups (will tag you on both for visibility):

1. file a github issue with megatron-deepspeed so that they can switch over to env:// at some point (we are trying to deprecate other forms of init_methods to prevent these types of BC issues in the future and make the code base more streamlined).
2. file a github issue with pytorch-lightning so that they can use `dist.is_torchelastic_launched()` instead of their own proxy.

**Comment by stas00** [comment]
Fantastic work, @kiukchung! Thank you!

Since pt-1.9.0's launcher still won't be compatible, as there is no 1.9.1. planned as I understand, therefore the change in Megatron and its forks should be done sooner than later.
