### ISSUE TITLE
[FX] Explicit GraphModule.__new__ call adds another GraphModuleImpl class to the inheritance hierarchy

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#63883]
Repro:

```
import torch
import torch.fx

class MyModule(torch.nn.Module):
    def forward(self, x):
        return torch.relu(x)

mod = MyModule()
traced = torch.fx.symbolic_trace(mod)

x = torch.randn(5, 3)
torch.testing.assert_allclose(traced(x), torch.relu(x))

new_instance = traced.__new__(type(traced))
new_instance.__init__(traced, traced.graph)

torch.testing.assert_allclose(new_instance(x), torch.relu(x))
"""
RecursionError: maximum recursion depth exceeded while calling a Python object
"""
```

The root cause for this is in the implementation of `GraphModule.__new__`:

https://github.com/pytorch/pytorch/blob/4a0776100e347c887378b676f3deabd14b88d7b2/torch/fx/graph_module.py#L236

This custom `__new__` implementation makes it so that we create a new class for each instance of `GraphModule` so that we can install an auto-generated `forward` method on the class type, without disturbing the `forward` of other instances of `GraphModule`.

This works fine when Python calls `GraphModule.__new__` from an explicit GraphModule instantiation:

```
import torch
import torch.fx

mod = torch.nn.Module()
graph = torch.fx.Graph()
x = torch.fx.GraphModule(mod, graph)

print(x.__class__.__mro__)
"""
(<class 'torch.fx.graph_module.GraphModule.__new__.<locals>.GraphModuleImpl'>, <class 'torch.fx.graph_module.GraphModule'>, <class 'torch.nn.modules.module.Module'>, <class 'object'>)
"""
```

However, when a class that is not the base `GraphModule` is passed to `__new__`, the redundant class definition problem occurs:

```
new_instance = x.__new__(type(x))
print(new_instance.__class__.__mro__)
"""
(<class 'torch.fx.graph_module.GraphModule.__new__.<locals>.GraphModuleImpl'>, <class 'torch.fx.graph_module.GraphModule.__new__.<locals>.GraphModuleImpl'>, <class 'torch.fx.graph_module.GraphModule'>, <class 'torch.nn.modules.module.Module'>, <class 'object'>)
"""
```

Thus, calling `super().__call__` causes infinite recursion since that will always return the same method and we never reach any higher in the class hierarchy:

https://github.com/pytorch/pytorch/blob/4a0776100e347c887378b676f3deabd14b88d7b2/torch/fx/graph_module.py#L593

To fix this, we should adjust the implementation of `GraphModule.__new__` to internally traverse the class hierarchy of the passed-in `type`, and instantiate a `GraphModuleImpl` that is a subtype of the first class that is not another `GraphModuleImpl`. Thus, in each of the `__mro__` print-outs above, there should always be exactly one instance of a `GraphModuleImpl` class.

**Comment by jamesr66a** [comment]
@Linux-cpp-lisp It's hard to tell what the root cause is from the description, but since it only happens after thousands of epochs it might be good to track down where the nondeterminism is coming from. The issue reported here is deterministic, which leads me to believe there might be something different happening in your case

**Comment by Linux-cpp-lisp** [comment]
Since it always fails in the same place, just at different epoch counts, I assumed that the non-determinism was really just the different training tasks => different batch + epoch sizes => bottom out the call stack at different times. Regardless, I have had almost no success tracking down the source of this error in a reproducible way given the amount of time required to trigger the error, and have settled for the workaround (https://github.com/e3nn/e3nn/pull/297). Hopefully if others encounter something similar with other codes, they can find this comment and we can track down similarities.
