### ISSUE TITLE
torchvision.transforms.ToTensor implicitly also divides by 255

### ISSUE THREAD

**Issue by murphyk** [pytorch/pytorch#6390]
I was surprised that transforms.ToTensor()  also divides by 255. This is documented 
(http://pytorch.org/docs/master/torchvision/transforms.html#conversion-transforms) but is not apparent from the name. Should this be fixed (which would make the function more transpararent and usable for non-image data)?

Demo:

transform = transforms.ToTensor() 
X = np.ones((3, 2, 2))
XX = transform(X)

XX looks like this:

(0 ,.,.) = 
1.00000e-03 *
   3.9216  3.9216
   3.9216  3.9216
   3.9216  3.9216

(1 ,.,.) = 
1.00000e-03 *
   3.9216  3.9216
   3.9216  3.9216
   3.9216  3.9216
[torch.FloatTensor of size 2x3x2]

**Comment by fmassa** [comment]
Torchvision in general needs a revamp, and I'm looking into it now, but I'm not sure it's best to use ToTensor for general conversion between numpy and torch tensors. In your case, it's just simpler to do `torch.from_numpy(array)`.
