### ISSUE TITLE
[feature request] Nightly pip install

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#6391]
It could be very convenient to support a nightly built pip install package for PyTorch, so one can track up-to-date feature in an easier way than building from source.

**Comment by hhsecond** [comment]
@zuoxingdong Conda channel has [pytorch nightly build](https://anaconda.org/pytorch/pytorch-nightly)

**Comment by lanpa** [comment]
The package dependency seems incorrect.
if I run `conda install -c pytorch pytorch-nightly`
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ninja-1.8.2                |       h6bb024c_1         1.3 MB
    pytorch-nightly-2018.04.08 |py36_cuda8.0.61_cudnn7.1.2_1       605.9 MB  pytorch
    cudatoolkit-9.0            |       h13b8566_0       340.4 MB
    ------------------------------------------------------------
                                           Total:       947.7 MB
```

Which results in `libcudart.so.8.0: cannot open shared object file: No such file or directory`

**Comment by hhsecond** [comment]
@lanpa That looks like some issue with the latest release I remember version `2018.04.05` working without any issue

**Comment by soumith** [comment]
i am fixing the package dependency.

**Comment by soumith** [comment]
the latest anaconda nightly just uploaded `2018.04.09` should have dependencies set correctly.

**Comment by soumith** [comment]
I will keep the issue open until we also have:

- cuda 90, cuda91 conda nightlies
- wheel nightlies

**Comment by soumith** [comment]
@lanpa looking into it.

**Comment by zuoxingdong** [comment]
@soumith  Is it possible to write up an automated tool to upload nightly build for different settings (CPU/GPU, different CUDA version etc. ) every midnight ?

**Comment by neerajprad** [comment]
@soumith mentioned that this should be available using the "preview" button in the download selector.

**Comment by soumith** [comment]
yes, this is officially being auto-pushed now. Use the "Preview" button in the download selector for nightly builds.
