### ISSUE TITLE
Some problems with pytorch cpuinfo library

### ISSUE THREAD

**Issue by nmanhong** [pytorch/pytorch#63922]
I read the introduction of cpuinfo and said that there is performance optimization, but I did not find any performance optimization when I turned it on and off. Could you tell me what aspects are optimized by cpuinfo?

**Comment by nmanhong** [comment]
@Yangqing

**Comment by nmanhong** [comment]
@ZolotukhinM

**Comment by ezyang** [comment]
cpuinfo detects what AVX/AVX2 is supported by the cpu and then we use it to turn on or off vectorized instructions. For more detailed discussion go to https://discuss.pytorch.org/
