### ISSUE TITLE
Cannot compile in Windows 10

### ISSUE THREAD

**Issue by VasLem** [pytorch/pytorch#6393]
- PyTorch or Caffe2: Both (setup.py)
- OS: Windows 10
- PyTorch version: Cloned from Master
- How you installed PyTorch (conda, pip, source): source (have not yet imanaged to install)
- Python version: 2.7 (Anaconda)
- CUDA/cuDNN version: Cuda 9.1
- GPU models and configuration:
- GCC version (if compiling from source): Using MSVC 15 2017
- CMake version:
- Build command you used (if compiling from source): As it is instructed in documentation

I seem to hit in a wall when trying to install pytorch in Windows 10 distro. I follow the instructions almost by letter, apart from the fact I had to change 'Enterprise' to 'Community', ie:
```
xcopy /Y aten\src\ATen\common_with_cwrap.py tools\shared\cwrap_common.py

set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1

call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
python setup.py install
```
The last command is not executed successfully, printing after 2-3 hours of compilation the following log, which seems to be limited inside xatomic.h file. I seem not able to keep track of the whole log, mainly due to the time needed to reproduce the error (I did not undergo the procedure of recompiling), so only the last ~100 lines were kept:
[log.txt](https://github.com/pytorch/pytorch/files/1886906/log.txt)

I think that this is a bug, so I reported it, in case anyone can provide a workaround. Thank you!

**Comment by apaszke** [comment]
As @peterjc123 said we only support Python 3 on Windows

**Comment by VasLem** [comment]
Can you confirm that caffe2 can be installed using python3? I followed the tutorial (https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile) where experimental compatibility of Python3 is mentioned
