### ISSUE TITLE
AttributeError: 'PlanarFlow' object has no attribute 'domain'

### ISSUE THREAD

**Issue by 5466a** [pytorch/pytorch#63945]
Do not know whether the version of the problem, how to solve?

**Comment by 5466a** [comment]
Dear Professor, I'm honored and excited to hear from you.
The program I ran was your flows tutorial on GitHub, part 3 -Normalizing Flows in PyTorch (Part 3), where the VAE model about flows reported an error when running.




The specific error is shown in the figure below:




I am very interested in Flows, but my programming skills are not good enough to solve this problem.
I didn't change a thing about the whole program, which really bothered me. 
Therefore, I would like to ask you how to solve this problem.
Thank you again and look forward to your next reply.


| |
宫文涛
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/27/2021 ***@***.***> wrote：

Thanks for the report, do you have a short snippet that we can run on colab for example to replicate this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by soulitzer** [comment]
Ah gotcha - Do you have a link to this tutorial? I could not find it.

**Comment by 5466a** [comment]
The tutorial address is as follows：
https://github.com/acids-ircam/pytorch_flows
I was embarrassed to find that I thought of you as the author of this tutorial, and only now did I find out that you are an expert in PyTorch open source.
Thank you again, I still hope to get your help. This tutorial is mainly related to torch.distributions.
I don't know if there is a problem with the version, please help me to check whether there is a problem caused by the PyTorch version.

**Comment by soulitzer** [comment]
Thanks for the link. For questions about how to use PyTorch you should use the PyTorch forum https://discuss.pytorch.org/.
To check if it is a problem with the PyTorch version you could try running the tutorial on a different machine - colab for example, which uses the latest release 1.9.

I will close this issue for now, since issues are generally for reporting bugs/requesting features.

**Comment by black0017** [comment]
Here is one solution, as proposed in [pytorch forum](https://discuss.pytorch.org/t/solved-pytorch1-8-attributeerror-tanhbijector-object-has-no-attribute-domain/116092/6) 

```python
import torch.distributions as distrib
import torch.distributions.transforms as transform

class PlanarFlow(transform.Transform):
    def __init__(self, weight, scale, bias):
        super(PlanarFlow, self).__init__()
        self.bijective = False

        # Add these 2 lines
        self.domain = torch.distributions.constraints.Constraint()
        self.codomain = torch.distributions.constraints.Constraint()
        
        self.weight = weight
        self.scale = scale
        self.bias = bias

    def _call(self, z):
        f_z = F.linear(z, self.weight, self.bias)
        return z + self.scale * torch.tanh(f_z)

    def log_abs_det_jacobian(self, z):
        f_z = F.linear(z, self.weight, self.bias)
        psi = (1 - torch.tanh(f_z) ** 2) * self.weight
        det_grad = 1 + torch.mm(psi, self.scale.t())
        return torch.log(det_grad.abs() + 1e-7)

```
