### ISSUE TITLE
Recovering input data fails for rff -> irfft

### ISSUE THREAD

**Issue by lucastepper** [pytorch/pytorch#63943]
## 🐛 Bug

Recovering input data fails for rff -> irfft for a 1-dim array of uneven length.

## To Reproduce

````python
ref_array = torch.randn(int(1e4) + 1)
test_array1 = torch.Tensor(ref_array)
test_array2 = torch.Tensor(ref_array)
test_array3 = torch.Tensor(ref_array)

# recovering input array works for fft -> ifft for array of uneven len
test_array1 = torch.fft.fft(test_array1)
test_array1 = torch.fft.ifft(test_array1)
assert torch.allclose(ref_array, torch.real(test_array1), atol=1e-6)
# recovering input array works for rfft -> irfft for array of even len
test_array2 = torch.fft.rfft(test_array2[:int(1e4)])
test_array2 = torch.fft.irfft(test_array2[:int(1e4)])
assert torch.allclose(ref_array[:int(1e4)], test_array2, atol=1e-6)
# recovering input array fails for rfft -> irfft for array of odd len
test_array3 = torch.fft.rfft(test_array3)
test_array3 = torch.fft.irfft(test_array3)
# we get size error and the array does not match
try:
    assert torch.allclose(ref_array, test_array3, atol=1e-6)
except RuntimeError:
    assert not torch.allclose(ref_array[:int(1e4)], test_array3[:int(1e4)], atol=1e-1)
```` 

## Expected behavior

Input array should be recovered when concatenating an inverse realFFT and a realFFT.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
CMake version: version 3.13.4
Libc version: glibc-2.28

Python version: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-0.bpo.8-amd64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.2.152
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.9.0
[conda] blas                      1.0                         mkl    anaconda
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2020.2                      256    anaconda
[conda] numpy                     1.21.2           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.9.0           py3.9_cuda11.1_cudnn8.0.5_0    pytorch

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @mruberry @peterbell10 @walterddr

**Comment by mruberry** [comment]
@peterbell10, what do you think?

**Comment by peterbell10** [comment]
This is expected behaviour, as per the examples in the [documentation](https://pytorch.org/docs/stable/generated/torch.fft.irfft.html). The output is half-size, so there's no way to tell the difference between half of an odd number and half of an even number.

**Comment by peterbell10** [comment]
To round trip properly, just pass the `n` argument:
```
ref_array = torch.randn(int(1e4) + 1)
test_array3 = torch.fft.rfft(ref_array)
test_array3 = torch.fft.irfft(test_array3, n=ref_array.numel())
assert torch.allclose(ref_array, test_array3, atol=1e-6)
```
