### ISSUE TITLE
[JIT] Serialization of Sparse Tensors doesnt work

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#63987]
## 🐛 Bug
```
import torch
import io

class SparseTensorModule(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.a = torch.sparse.FloatTensor()

	def forward(self):
		pass

torch.jit.save(torch.jit.script(SparseTensorModule()), io.BytesIO())
```

> NotImplementedError: Cannot access storage of SparseTensorImpl

## Additional context

Ran into this when fixing a freezing / sparsity bug which was requested internally.

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

**Comment by Linux-cpp-lisp** [comment]
+1 on this issue, which I have also come across when trying to freeze a model that includes a sparse tensor:
```
import torch

class SparseTensorModule(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.a = torch.sparse.FloatTensor()

	def forward(self):
		pass

torch.jit.freeze(torch.jit.script(SparseTensorModule()).eval())
```

It would be great if this could be fixed along with the other upcoming improvements to sparse tensors in 1.10; as much as we'd like to be able to use sparse tensors in our models, we can't really do so without the ability to deploy them to TorchScript.

**Comment by Linux-cpp-lisp** [comment]
I did a little more digging, and the undocumented `some_sparse_tensor._coalesced_(True)` seems to be a workaround:
 - Save the `indices`, `values`, and shape of a `coalesce`d tensor
 - In `forward` of the TorchScript model, call `torch.sparse_coo_tensor` using them
 - Use `_coalesced_(True)` to set the flag for full performance of matmuls, etc.

Any obvious reasons why this is a bad idea, until a fix for this issue lands?

**Comment by eellison** [comment]
@Linux-cpp-lisp that seems like a fine fix to me! honestly the fix here should be pretty simple just know ones done it yet. i can take a look before the next release

**Comment by Linux-cpp-lisp** [comment]
Great, it seems to be working well but glad to have the confirmation that it makes sense. Thanks!

Looking forward to all the sparse matrix features set to land in 1.10, gonna be great :smile:

**Comment by cpuhrsch** [comment]
We'll also need this for torch.ao.

@eellison are you still planning to look into this?

**Comment by z-a-f** [comment]
We wanted to use the SparseTensors for the sparsifier project (within `torch.ao`), but serialization is a big blocker -- currently resorting to custom serialization routines

**Comment by davidberard98** [comment]
afaik, serialization was fixed in #62794 (but we still need to fix freezing)

**Comment by Linux-cpp-lisp** [comment]
Lines up with what I'm seeing: saving does appear to be fixed in PyTorch 1.10 (though not in 1.9) and freezing is still broken.

**Comment by eellison** [comment]
Fixed by @davidberard98 !

**Comment by cpuhrsch** [comment]
@Linux-cpp-lisp - does the recent nightly resolve your issue as well?

**Comment by Linux-cpp-lisp** [comment]
It appears that freezing and JIT serialization works now with COO/CSR sparse tensors--- thanks! I'll fill more issues as they come up.
