### ISSUE TITLE
test_binary_ufuncs.test_inplace_comparison_ops_require_inputs_have_same_dtype May have been damaged

### ISSUE THREAD

**Issue by Freey0** [pytorch/pytorch#64018]
## 🐛 Bug

In file test_binary_ufuncs.py, This test expects every operation to throw a runtime error, but in fact only logical_xor_, logical_and_, logical_or_ throws a runtime error
```
@onlyCPU
def test_inplace_comparison_ops_require_inputs_have_same_dtype(self, device):
    with self.assertRaisesRegex(RuntimeError, 'Expected object of scalar type'):
        for op in ['lt_', 'le_', 'gt_', 'ge_', 'eq_', 'ne_', 'logical_xor_', 'logical_and_', 'logical_or_']:
            x = torch.tensor([1], dtype=torch.int)
            y = torch.tensor([2], dtype=torch.long)
            in_place_method = getattr(x, op)
            in_place_method(y)
```

## To Reproduce

```
In [13]: x = torch.tensor([1], dtype=torch.int)

In [14]: y = torch.tensor([2], dtype=torch.long)

In [15]: x.lt_(y)
Out[15]: tensor([1], dtype=torch.int32)

In [16]: x.le_(y)
Out[16]: tensor([1], dtype=torch.int32)

In [17]: x.logical_xor_(y)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-1594f07c6eff> in <module>
----> 1 x.logical_xor_(y)

RuntimeError: Expected object of scalar type int but got scalar type long long for argument 'other'
```

## Expected behavior
I've recently been trying to port logical_xor to structured, and logical_xor doesn't throw runtime errors either, I'm not sure what the correct behavior should be

## Environment

Collecting environment information...
PyTorch version: 1.10.0.dev20210826
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.4 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.16)
CMake version: version 3.20.0
Libc version: N/A

Python version: 3.9.6 (default, Aug 18 2021, 12:38:10)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] torch==1.10.0a0+gita40659a
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.3.0           hecd8cb5_517
[conda] mkl-service               2.4.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.0            py39h4a7008c_2
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] mypy                      0.910              pyhd3eb1b0_0
[conda] mypy_extensions           0.4.3            py39hecd8cb5_0
[conda] numpy                     1.20.3           py39h4b4dc7a_0
[conda] numpy-base                1.20.3           py39he0bd621_0

**Comment by ezyang** [comment]
yes the context manager needs to be done inside the loop. Can you submit a PR to fix this (and restore the errors?)

**Comment by Freey0** [comment]
The problem may be due to #60177 dropping special checks for in-place operations when porting eq (and other comparison operations) to structured cores.

```
// To avoid overflow during type promotion we will check that both dtypes of self and other are same
template <typename OutImpl>
Tensor& comparison_op_(Tensor& self, const Tensor& other, OutImpl& out_impl) {
  TORCH_CHECK(self.dtype() == other.dtype(),
              "Expected object of scalar type ", self.dtype(), " but got scalar type ",
              other.dtype(), " for argument 'other'");
  return out_impl(self, self, other);
}

Tensor& eq_(Tensor& self, const Tensor& other) { return comparison_op_(self, other, static_cast<OutFunc>(at::eq_out)); }
```

Question: How do I perform special checks for in-place operations in the structured core?

**Comment by ezyang** [comment]
cc @ysiraichi 

You can detect if inplace is in operation if `maybe_get_output()` reports the output is self. At minimum you can just reinsert the test as necessary there. Maybe there's some broader fix we should make, although I'm a little surprised this test only needs to be done for inplace and not for other cases...

**Comment by ysiraichi** [comment]
@Freey0  Nice catch! I didn't realize I had dropped that check.
@ezyang To be honest, I'm not sure why we need that check in the first place. Maybe I'm missing something, but isn't setting `promote_inputs_to_common_dtype` enough? i.e. doesn't `compute_common_dtype()` already avoids overflow?

**Comment by ezyang** [comment]
> To be honest, I'm not sure why we need that check in the first place. Maybe I'm missing something, but isn't setting promote_inputs_to_common_dtype enough? i.e. doesn't compute_common_dtype() already avoids overflow?

I'm not sure, and would have to analyze the situation. Maybe you can trace through and see why?

**Comment by ysiraichi** [comment]
Apparently, that check was introduced when porting `lt` to ATen, in #25998. Here is the reason given in that PR:

> **`a.lt_(Tensor b)`**
Expects that a and b has same dtype, otherwise it's possible to get an overflow(Example: 'a' is uint8, 'b' is float32. 'a' will be promoted to float32 and the result will be also float32. Then it will be casted back to uint8 so potential for overflow). Will not compute common dtype. Result will have type of a.

Maybe I'm missing something, but I can't see how that's the case. Both CPU and CUDA had very similar implementations, differing only in which `TensorIterator` consumer function was used: `cpu_kernel` and `gpu_kernel_with_scalars`, respectively. For example, the relevant part of [the CPU kernel](https://github.com/ifedan/pytorch/blob/2fed6b12dfbb7fa3f0a5ab540c8de665301145ca/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp#L106-L122) follows:

```c++
AT_DISPATCH_ALL_TYPES_AND(kBFloat16, iter.dtype(), "lt_cpu", [&]() {
  cpu_kernel(iter,
    [=](scalar_t a, scalar_t b) -> scalar_t {
      return a < b;
    });
});
```

Note that the lambda function used return an implicit conversion of `bool` (the return type of the `<` operator) to `scalar_t`. As far as I understand, in that case, the result will always be either 0 or 1 of the return type. I can't really see how that could cause an overflow.

That said, I may be missing something. Any thoughts?
@ezyang @ifedan @zou3519

**Comment by ezyang** [comment]
Yeah, I agree with this reasoning. My best guess is that this was in the context of some other operators that were getting type promotion (and therefore did have overflow risk). Not this one.
