### ISSUE TITLE
tools/nightly.py  raises: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Freey0** [pytorch/pytorch#64017]
## 🐛 Bug

./tools/nightly.py checkout -b my-nightly-branch   
does not work
```
Traceback (most recent call last):
  File "./tools/nightly.py", line 327, in <module>
    def pytorch_install(url: str) -> tempfile.TemporaryDirectory[str]:
TypeError: 'type' object is not subscriptable
```
## To Reproduce

1. Follow the CONTRIBUTING.md documentation 'Nightly Checkout & Pull' operation
1. ./tools/nightly.py checkout -b my-nightly-branch

## Expected behavior

No error reported
## Environment

Collecting environment information...
PyTorch version: 1.10.0a0+gita40659a
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.4 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.16)
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.8.8 (default, Feb 24 2021, 13:46:16)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.10.0a0+gita40659a
[conda] mkl                       2020.2                      260
[conda] mkl-include               2021.3.0           hecd8cb5_517
[conda] mypy                      0.812              pyhd3eb1b0_0
[conda] mypy_extensions           0.4.3                    py38_0
[conda] numpy                     1.20.0                   pypi_0    pypi
[conda] torch                     1.10.0a0+gita40659a           dev_0    <develop>

## Additional context

File tools/nightly.py line 327
```
def pytorch_install(url: str) -> tempfile.TemporaryDirectory[str]:
```
Change to
```
def pytorch_install(url: str) -> tempfile.TemporaryDirectory:
```
Working locally, If correct, I can send a pr

cc @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by malfet** [comment]
Alas, fix like that would cause type mypy regression. I think proper fix would be to just escape it with quotes
