### ISSUE TITLE
Torch crashes when calling torch.rand(2,3)

### ISSUE THREAD

**Issue by dgorbachev** [pytorch/pytorch#6406]
Hello,

I'm on Ubuntu, AMD processor. numpy is the latest: 1.14.2
Encountered the following crash:

mitra@CAPRICA:~$ python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.rand(2,3)
Illegal instruction (core dumped)
mitra@CAPRICA:~$ 

Thanks

Dmitriy

PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2:
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by soumith** [comment]
your processor is old enough that it doesn't support SSE4.1/SSE4.2/SSE4.3 instruction. We do not support processors that dont have these features in binaries.
Your only choice is to install from source: https://github.com/pytorch/pytorch#from-source

**Comment by Lewington-pitsos** [comment]
@soumith how did you know that the processor was too old? Is there a list somewhere? Cheers.

**Comment by soumith** [comment]
@Lewington-pitsos `Illegal instruction (core dumped)` points to the fact that an instruction that isn't supported by the processor was executed. I happen to know that in the RNG code, we do use `SSE4.1/SSE4.2/SSE4.3` instructions. There isn't a list, but you can check what features your processor supports by issuing particular commands:

- Windows: Download and run coreinfo -f
- OSX: Run sysctl -a | grep machdep.cpu.features
- Linux: Check /proc/cpuinfo

Reference: https://arnoldsupport.com/2016/10/08/arnold-mtoa-how-to-check-if-your-processor-supports-sse4-1/
