### ISSUE TITLE
Libtorch LTS couldn't be downloaded in Pytorch.Org

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#64080]
## 🐛 Bug

Libtorch LTS couldn't be downloaded!

## To Reproduce

1. go to pytorch.org. 
![image](https://user-images.githubusercontent.com/16190118/131069540-057b315f-677a-49a2-8237-993f74dfed09.png)
2. click the link
For example:
(Linux)https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.2%2Bcu102.zip
(Windows)https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.8.2%2Bcu102.zip

There's the error
![image](https://user-images.githubusercontent.com/16190118/131069615-cfa2f9c0-2f30-47a7-b217-f38190a6ce8b.png)

## Expected behavior

LibTorch LTS(1.8.2) could be downloaded

## Additional context

One user has reported the issue in forum https://discuss.pytorch.org/t/fail-to-download-libtorch-1-8-2-for-windows/130307

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr

**Comment by EwaFengler** [comment]
I had the same problem as well, I couldn't download Libtorch LTS. I was able to download an earlier version when I replaced "1.8.2" in the URL with "1.8.1". That satisfies me, maybe someone else will find this helpful.

**Comment by malfet** [comment]
cc: @harishsk

**Comment by seemethere** [comment]
I can take care of this today, seems with the new lts stuff we neglected the libtorch uploads
