### ISSUE TITLE
Disambiguate JOB_BASE_NAME, BUILD_ENVIRONMENT in our scripts

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#64095]
Currently we have the following concepts in our CI scripts/test structure:

* The idea of a job prefix, used when trying to consolidate test time stats between build and test jobs. Relevant code https://github.com/pytorch/pytorch/blob/f2c47cf4dbbdd0cafc1bd2118121c6eda3947f3f/tools/testing/test_selections.py#L25-L35 

* The idea of a job name, which is the most specific one could go with test names, used here https://github.com/pytorch/pytorch/blob/f2c47cf4dbbdd0cafc1bd2118121c6eda3947f3f/tools/stats/print_test_stats.py#L782-L793

* The idea of a build environment, which is used everywhere in our build and test scripts in .jenkins/pytorch.

To address those concepts, we use the following environment variables:
* BUILD_ENVIRONMENT: this is sometimes used as ALL three of the concepts above
* JOB_BASE_NAME: this attempts to be a job name but is not very specific on GHA and _is_ specific on Circle because we set JOB_BASE_NAME to CIRCLE_JOB. This variable is also used to derive BUILD_ENVIRONMENT like the first code example above.

All this is not fun to deal with. We should clean it up. A good idea is to revamp what we mean by BUILD_ENVIRONMENT and JOB_BASE_NAME. 

Example proposal:

* BUILD_ENVIRONMENT: should represent the environment in which pytorch was built! This could also function as a great job prefix.
* JOB_NAME: should represent the most specific description of a job. This would include test config and shard number and all that good stuff. 
* We may want other variables to represent other ideas, and I am not opposed to more variables, but we should clarify the existing ones and stick to our definitions of them. 

cc @ezyang @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
This is already done, closing...
