### ISSUE TITLE
Question about torchvision.io.decode_image

### ISSUE THREAD

**Issue by lxy443626128** [pytorch/pytorch#64090]
when we use torchvision.io.decode_image(img,device = local_rank)  to train with ddp，we find num_workers>0 can't work.
 
RuntimeError: DataLoader worker (pid 58353) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment]
Hi,
We use github issues only for bugs or feature requests.
Please use the forum to ask questions:  https://discuss.pytorch.org/

I don't know `decode_image` accepting `device` as an argument. Please check https://pytorch.org/vision/stable/io.html#torchvision.io.decode_image

And, this is too vague for us to understand the issue. Please re-open it if it's a bug and provide detailed information about the issue. Closing it for now.
