### ISSUE TITLE
sccache error in Windows nightly build.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#64154]
## 🐛 Bug

binary_windows_conda_3_7_cpu_nightly_build failed due to sccache error on Aug 29.

## To Reproduce

error link:
https://app.circleci.com/pipelines/github/pytorch/pytorch/372424/workflows/479f5428-5a9b-4a8a-9653-689da796d708/jobs/15711349
```
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
```
## Expected behavior

This build should be always successful.

## Additional context

It can pass by rerunning it.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @ezyang @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

**Comment by mszhanyi** [comment]
https://github.com/mozilla/sccache/issues/256#issuecomment-398957995

**Comment by mszhanyi** [comment]
@malfet @seemethere @janeyx99 
I think CI shouldn't be broken by sccache errors like below.
https://app.circleci.com/pipelines/github/pytorch/pytorch/433160/workflows/a42a6a9e-479b-4805-a167-5dd8049753a5/jobs/16910060?invite=true#step-104-3423.

It's inevitable that there's connection issue at some time.
For sccache server, It only means that it fails to get the cache.
Then, it should run compilation commands locally like missing cache rather than stopping the build.

I've submitted an issue and PR to sccache https://github.com/mozilla/sccache/issues/1089 and https://github.com/mozilla/sccache/pull/1090

**Comment by janeyx99** [comment]
@mszhanyi Just also linking over the issue we have that tracks the sccache issues in non-nightly CI https://github.com/pytorch/pytorch/issues/67720. This should also be fixed if the fixes you submit to sccache are correct, yes?

**Comment by Blackhex** [comment]
Can you please confirm this issues has been fixed and can be closed?

**Comment by janeyx99** [comment]
Closing this issue as it is not affecting us anymore.
