### ISSUE TITLE
libtorch to path

### ISSUE THREAD

**Issue by ASB1993** [pytorch/pytorch#64177]
Hi, 
I have installed pytorch with anaconda3. Now I need to export libtorch to the PATH-variable on Ubuntu 20.04. 
Now, my question is: what should the path name be? For building the example, the -DCMAKE_PREFIX_PATH was python -c 'import torch;print(torch.utils.cmake_prefix_path)'. However, the path to the conda pytorch installation directory is  _/home/anna/anaconda3/lib/python3.8/site-packages/torch.

How should I set the path variable for libtorch, so that another program will accept libtorch?

cc @brianjo @mruberry

**Comment by malfet** [comment]
Are you saying that instructions in https://pytorch.org/tutorials/advanced/cpp_frontend.html are not working for you?

**Comment by ASB1993** [comment]
no it is not a bug. However, I am wondering how to link Libtorch to the path, when installing the whole pytorch package! The cpp-frontend is working for me yes!
