### ISSUE TITLE
Lint rule that checks that new test files are being tested in CI

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#64178]
## 🚀 Feature
We should have a lint rule that checks that new python test files are being tested in CI (i.e. are added to run_test.py)

## Motivation

It's really easy to forget to add a test to run_test.py. In particular, I noticed recently that we're missing `test/test_python_dispatch.py` from `run_test.py`.

## Pitch

Add some lint rule. Upon creation of a new `test_*.py` file under the `test/` folder, check that the file also gets added to a list in `run_test.py`.

## Alternatives

Better documentation around what to do when you're adding a new test file?

cc @ezyang @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra @mruberry @VitalyFedyunin

**Comment by walterddr** [comment]
+1. also a related topic: there were several times that test files were added to run_test.py but not internal buck target.

**Comment by zou3519** [comment]
> but not internal buck target.

I didn't know this was necessary... TIL

**Comment by ezyang** [comment]
Wouldn't globbing be better 🤔

**Comment by dagitses** [comment]
> Wouldn't globbing be better 🤔

I agree. It seems unnecessary to me to explicitly register these files. Is the motivation for that files like test_ao_sparsity.py that just import and run other tests?

**Comment by zou3519** [comment]
I support globbing, it solves a lot of our problems. Can we also glob for buck tests internally as well?

**Comment by malfet** [comment]
Jumping late to the discussion, but yes, that was my idea as well: glob + blocklist, will implement it later today.
