### ISSUE TITLE
Improve CI documentation

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#64192]
## 📚 Documentation

Our CI could be better documented + we should update .circleci/README.md.

This issue can track the following tasks (feel free to add more):

- [ ] Create a README for GitHub Actions somewhere (maybe in the .github/ folder?)
- [ ] Update .circleci/README.md
- [ ] Have other docs that mention CI redirect to our updated CI documentation.
    - [ ] Update CONTRIBUTING.md to contain .github in the codebase structure

merge with https://github.com/orgs/pytorch/projects/2#card-66752598

cc @brianjo @mruberry @ezyang @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

**Comment by zhouzhuojie** [comment]
Thanks @janeyx99 We did a doc hackathon and moved some of the CI docs to Wiki https://github.com/pytorch/pytorch/wiki/Continuous-Integration, 
I think we can document more clearly there with less editing friction without going through PR and ci to make doc changes, that's also the recommended place for CI related docs.

A README.md under .github is also quite nice to document all the things related to github
