### ISSUE TITLE
Does pytorch.distributed support support MPI_THREAD_MULTIPLE

### ISSUE THREAD

**Issue by iso-p** [pytorch/pytorch#64211]
## MPI_THREAD_MULTIPLE not enabled with torch.distributed.init_process_group

I had the following code in c++ to use torch.distributed-intialized MPI processes. However I got ```supportProvided != MPI_THREAD_MULTIPLE``` when running these c++ code after ```import torch.distributed as dist;dist.init_process_group(backend='mpi')```

```
  int supportProvided;
  int initialized;
  int initSuccess;
  MPI_Initialized(&initialized);
  if (!initialized){
    initSuccess = MPI_Init_thread(NULL, NULL, MPI_THREAD_MULTIPLE, &supportProvided);
  }
  else {
    MPI_Query_thread(&supportProvided);
    initSuccess = MPI_SUCCESS;
  }
  if (initSuccess != MPI_SUCCESS) {
    MPI_Abort(MPI_COMM_WORLD, initSuccess);
  }

  if (supportProvided != MPI_THREAD_MULTIPLE) {
        std::cout<<"MPI_THREAD_MULTIPLE not supported by installed MPI library")<<std::endl;
  }
```

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by zou3519** [comment]
Please ask questions on our forums: https://discuss.pytorch.org/.

**Comment by dipikagurtoo** [comment]
Hi Everyone,
I amt trying to run MPI with Pytorch from Source for distributed runs. I am able to build, compile and instal. But post installation, i am unable to import torch.

I am using OpenMPi and Pytorch latest version.

Let me know if i have to export any variables or if there is anything other information needed from side to proceed further.
