### ISSUE TITLE
Move distributed tests into its own jobs or workflows to isolate the flakiness

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#64216]
TODO: add context and concrete steps

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23 @ezyang @seemethere @malfet @walterddr @lg20987 @pytorch/pytorch-dev-infra

**Comment by zhouzhuojie** [comment]
Created as the follow-ups from #60344

**Comment by malfet** [comment]
I believe it was accomplished by #62896, wasn't it? Please do not hesitate to reopen if there is anything left to do there.
