### ISSUE TITLE
[caffe2] Run resnet50_trainer.py error between 2 machines using GLOO/Redis and ibverbs

### ISSUE THREAD

**Issue by boriskovalev** [pytorch/pytorch#6422]
Caffe2
OS: Ubuntu 16.04
Python version: 2.7
CUDA/cuDNN version: 9.1 , 7.0.5
GPU models and configuration: P100
GCC version (if compiling from source):5.4.0
Mellanox OFEDversion: 4.2.
NCCL 2.1.15

I try to run resnet50_trainer.py on two nodes with several GPUs and ibverbs by:

python /root/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data /data/ilsvrc12_train_lmdb/ --test_data /data/ilsvrc12_val_lmdb --batch_size 64 --run_id 1 --epoch_size 10000 --num_epochs 10 --image_size 256 --num_gpus 2 --redis_host 10.143.119.44 --redis_port 5555 --num_shards 2 --shard_id 0 --dtype float16 --float16_compute --distributed_transport ibverbs --distributed_interfaces mlx5_3

python /root/caffe2/caffe2/python/examples/resnet50_trainer.py --train_data /data/ilsvrc12_train_lmdb/ --test_data /data/ilsvrc12_val_lmdb --batch_size 64 --run_id 1 --epoch_size 10000 --num_epochs 10 --image_size 256 --num_gpus 2 --redis_host 10.143.119.44 --redis_port 5555 --num_shards 2 --shard_id 1 --dtype float16 --float16_compute --distributed_transport ibverbs --distributed_interfaces mlx5_3

**On first node:**
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
E0409 17:14:15.448786  5047 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0409 17:14:15.449039  5047 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0409 17:14:15.449051  5047 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 9984
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E0409 17:14:16.092067  5047 operator.cc:463] Shape inference error: [enforce fail at conv_pool_op_base.h:601] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E0409 17:14:16.092497  5047 operator.cc:464] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E0409 17:14:16.092525  5047 operator.cc:465] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0500400066376 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0491058826447 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/10
E0409 17:14:27.317248  5177 net_dag.cc:188] Exception from operator chain starting at 'comp_15_conv_3_w_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_4_cw" input: "gpu_0/comp_15_conv_3_w_grad" input: "gpu_1/comp_15_conv_3_w_grad" output: "gpu_0/comp_15_conv_3_w_grad" output: "gpu_1/comp_15_conv_3_w_grad" name: "comp_15_conv_3_w_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_conv_3_w_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
E0409 17:14:27.324991  5184 net_dag.cc:188] Secondary exception from operator chain starting at 'comp_15_spatbn_2_s_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_6_cw" input: "gpu_0/comp_15_spatbn_2_s_grad" input: "gpu_1/comp_15_spatbn_2_s_grad" output: "gpu_0/comp_15_spatbn_2_s_grad" output: "gpu_1/comp_15_spatbn_2_s_grad" name: "comp_15_spatbn_2_s_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_spatbn_2_s_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
E0409 17:14:27.363723  5178 net_dag.cc:188] Secondary exception from operator chain starting at 'comp_15_conv_2_w_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_7_cw" input: "gpu_0/comp_15_conv_2_w_grad" input: "gpu_1/comp_15_conv_2_w_grad" output: "gpu_0/comp_15_conv_2_w_grad" output: "gpu_1/comp_15_conv_2_w_grad" name: "comp_15_conv_2_w_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_conv_2_w_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"

**On second:**

Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
E0409 17:14:16.832541  2188 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0409 17:14:16.832834  2188 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0409 17:14:16.832846  2188 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 9984
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E0409 17:14:17.516000  2188 operator.cc:463] Shape inference error: [enforce fail at conv_pool_op_base.h:601] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E0409 17:14:17.516786  2188 operator.cc:464] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E0409 17:14:17.516835  2188 operator.cc:465] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.057541847229 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0494668483734 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/10
E0409 17:14:27.317000  2299 net_dag.cc:188] Exception from operator chain starting at 'comp_15_spatbn_2_b_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_5_cw" input: "gpu_0/comp_15_spatbn_2_b_grad" input: "gpu_1/comp_15_spatbn_2_b_grad" output: "gpu_0/comp_15_spatbn_2_b_grad" output: "gpu_1/comp_15_spatbn_2_b_grad" name: "comp_15_spatbn_2_b_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_spatbn_2_b_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
E0409 17:14:27.325222  2295 net_dag.cc:188] Secondary exception from operator chain starting at 'comp_15_conv_3_w_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_4_cw" input: "gpu_0/comp_15_conv_3_w_grad" input: "gpu_1/comp_15_conv_3_w_grad" output: "gpu_0/comp_15_conv_3_w_grad" output: "gpu_1/comp_15_conv_3_w_grad" name: "comp_15_conv_3_w_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_conv_3_w_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
E0409 17:14:27.365981  2285 net_dag.cc:188] Secondary exception from operator chain starting at 'comp_15_conv_2_w_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_7_cw" input: "gpu_0/comp_15_conv_2_w_grad" input: "gpu_1/comp_15_conv_2_w_grad" output: "gpu_0/comp_15_conv_2_w_grad" output: "gpu_1/comp_15_conv_2_w_grad" name: "comp_15_conv_2_w_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_conv_2_w_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
Original python traceback for operator 829 in network `resnet50` in exception above (most recent call last):
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 615, in <module>
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 611, in main
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 434, in Train
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 271, in Parallelize
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 1149, in _AllReduceBlobs
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 1301, in _AllReduceBlobsDistributed
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 1292, in allreduce
Traceback (most recent call last):
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 615, in <module>
    main()
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 611, in main
    Train(args)
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 529, in Train
    explog
  File "/root/caffe2/caffe2/python/examples/resnet50_trainer.py", line 175, in RunEpoch
    workspace.RunNet(train_model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 215, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 177, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_5_cw" input: "gpu_0/comp_15_spatbn_2_b_grad" input: "gpu_1/comp_15_spatbn_2_b_grad" output: "gpu_0/comp_15_spatbn_2_b_grad" output: "gpu_1/comp_15_spatbn_2_b_grad" name: "comp_15_spatbn_2_b_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_spatbn_2_b_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"

Distributed TCP and locale multi GPUs is running properly.

Thanks.

**Comment by shijieheping** [comment]
I've reproduced the same issue with K80(dual core Kepler), file_store_path, with/without NCCL

OS: Ubuntu 16.04, Linux 4.4.0-119-generic
Python version: 2.7.12
CUDA/cuDNN version: libcudnn7-dev_7.1.2.21-1+cuda9.1_amd64.deb
GPU models and configuration: K80
GCC version (if compiling from source): 5.4.0 
Mellanox OFED version: 4.3-1.0.1.0
NCCL: 2.1.15-1+cuda9.1




root@**u1**:/dev/shm/lmdbexample# PYTHONPATH=/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages LD_LIBRARY_PATH=/dev/shm/ibnoncclcaffe2/lib/ python /dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py --train_data /mnt/data/caffedata/imagenet_cars_boats_train --test_data /mnt/data/caffedata/imagenet_cars_boats_val --batch_size 64 --num_epochs 10 --epoch_size 10000 --num_gpus 2 --run_id 1 --num_shards 2 --shard_id **0** --file_store_path /mnt/fsp --distributed_transport ibverbs --distributed_interfaces mlx5_3

root@**u2**:/dev/shm/lmdbexample# PYTHONPATH=/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages LD_LIBRARY_PATH=/dev/shm/ibnoncclcaffe2/lib/ python /dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py --train_data /mnt/data/caffedata/imagenet_cars_boats_train --test_data /mnt/data/caffedata/imagenet_cars_boats_val --batch_size 64 --num_epochs 10 --epoch_size 10000 --num_gpus 2 --run_id 1 --num_shards 2 --shard_id **1** --file_store_path /mnt/fsp --distributed_transport ibverbs --distributed_interfaces mlx5_3



On Node u1
```
root@u1:/dev/shm/lmdbexample#  PYTHONPATH=/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages LD_LIBRARY_PATH=/dev/shm/ibnoncclcaffe2/lib/ python /dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py --train_data /mnt/data/caffedata/imagenet_cars_boats_train --test_data /mnt/data/caffedata/imagenet_cars_boats_val --batch_size 64 --num_epochs 10 --epoch_size 10000 --num_gpus 2 --run_id 1 --num_shards 2 --shard_id 1 --file_store_path /mnt/fsp --distributed_transport ibverbs --distributed_interfaces mlx5_3
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
E0410 00:05:04.814718  8026 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0410 00:05:04.814929  8026 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0410 00:05:04.814939  8026 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 9984
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E0410 00:05:05.428273  8026 operator.cc:463] Shape inference error: [enforce fail at conv_pool_op_base.h:601] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E0410 00:05:05.428676  8026 operator.cc:464] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E0410 00:05:05.428700  8026 operator.cc:465] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0426690578461 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0411059856415 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/10
E0410 00:05:14.257479  8096 net_dag.cc:188] Exception from operator chain starting at 'comp_15_spatbn_3_b_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_2_cw" input: "gpu_0/comp_15_spatbn_3_b_grad" input: "gpu_1/comp_15_spatbn_3_b_grad" output: "gpu_0/comp_15_spatbn_3_b_grad" output: "gpu_1/comp_15_spatbn_3_b_grad" name: "comp_15_spatbn_3_b_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_spatbn_3_b_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
```

On Node u2
```
root@u2:/dev/shm/lmdbexample#  PYTHONPATH=/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages LD_LIBRARY_PATH=/dev/shm/ibnoncclcaffe2/lib/ python /dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py --train_data /mnt/data/caffedata/imagenet_cars_boats_train --test_data /mnt/data/caffedata/imagenet_cars_boats_val --batch_size 64 --num_epochs 10 --epoch_size 10000 --num_gpus 2 --run_id 1 --num_shards 2 --shard_id 0 --file_store_path /mnt/fsp --distributed_transport ibverbs --distributed_interfaces mlx5_3
Ignoring @/caffe2/caffe2/contrib/nccl:nccl_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/contrib/gloo:gloo_ops_gpu as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:file_store_handler_ops as it is not a valid file.
Ignoring @/caffe2/caffe2/distributed:redis_store_handler_ops as it is not a valid file.
E0410 00:05:06.052727 24038 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0410 00:05:06.053006 24038 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0410 00:05:06.053020 24038 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
INFO:resnet50_trainer:Running on GPUs: [0, 1]
INFO:resnet50_trainer:Using epoch size: 9984
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Adding gradient operators
INFO:data_parallel_model:Add gradient all-reduces for SyncSGD
WARNING:data_parallel_model:Distributed broadcast of computed params is not implemented yet
INFO:data_parallel_model:Post-iteration operators for updating params
INFO:data_parallel_model:Calling optimizer builder function
INFO:data_parallel_model:Add initial parameter sync
E0410 00:05:06.892519 24038 operator.cc:463] Shape inference error: [enforce fail at conv_pool_op_base.h:601] in_size + *pad_head + *pad_tail >= dkernel. 2 vs 3 
E0410 00:05:06.893355 24038 operator.cc:464] Operator: input: "gpu_0/conv1_spatbn_relu" output: "gpu_0/pool1" name: "" type: "MaxPool" arg { name: "order" s: "NCHW" } arg { name: "kernel" i: 3 } arg { name: "stride" i: 2 } arg { name: "ws_nbytes_limit" i: 67108864 } arg { name: "cudnn_exhaustive_search" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
E0410 00:05:06.893406 24038 operator.cc:465] Returning empty results.
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0609338283539 secs
WARNING:memonger:NOTE: Executing memonger to optimize gradient memory
INFO:memonger:Memonger memory optimization took 0.0527391433716 secs
INFO:resnet50_trainer:----- Create test net ----
INFO:data_parallel_model:Parallelizing model for devices: [0, 1]
INFO:data_parallel_model:Create input and model training operators
INFO:data_parallel_model:Model for GPU : 0
INFO:data_parallel_model:Model for GPU : 1
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:resnet50_trainer:Starting epoch 0/10
E0410 00:05:14.254077 24091 net_dag.cc:188] Exception from operator chain starting at 'comp_15_spatbn_3_b_grad' (type 'Allreduce'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_2_cw" input: "gpu_0/comp_15_spatbn_3_b_grad" input: "gpu_1/comp_15_spatbn_3_b_grad" output: "gpu_0/comp_15_spatbn_3_b_grad" output: "gpu_1/comp_15_spatbn_3_b_grad" name: "comp_15_spatbn_3_b_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_spatbn_3_b_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"
WARNING:caffe2.python.workspace:Original python traceback for operator `820` in network `resnet50` in exception above (most recent call last):
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 615, in <module>
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 611, in main
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 434, in Train
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 271, in Parallelize
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 1149, in _AllReduceBlobs
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 1301, in _AllReduceBlobsDistributed
WARNING:caffe2.python.workspace:  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/data_parallel_model.py", line 1292, in allreduce
Traceback (most recent call last):
  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 615, in <module>
    main()
  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 611, in main
    Train(args)
  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 529, in Train
    explog
  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/examples/resnet50_trainer.py", line 175, in RunEpoch
    workspace.RunNet(train_model.net.Proto().name)
  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/dev/shm/ibnoncclcaffe2/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid resource handle Error from operator: 
input: "allreduce_2_cw" input: "gpu_0/comp_15_spatbn_3_b_grad" input: "gpu_1/comp_15_spatbn_3_b_grad" output: "gpu_0/comp_15_spatbn_3_b_grad" output: "gpu_1/comp_15_spatbn_3_b_grad" name: "comp_15_spatbn_3_b_grad" type: "Allreduce" arg { name: "status_blob" s: "allreduce_comp_15_spatbn_3_b_grad_status" } arg { name: "gpu_direct" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "GLOO"

```

**Comment by shijieheping** [comment]
And plus, distributed IBVERBS with "--num_gpus 1" runs properly
With "--num_gpus 2", it crashes

**Comment by brave-hannah** [comment]
@shijieheping How do these two nodes know each other? I find no IP param in resnet50_trainer.py usage description.

**Comment by raminudelman** [comment]
> @shijieheping How do these two nodes know each other? I find no IP param in resnet50_trainer.py usage description. Do I need to use mpirun command to launch them to different nodes?

It uses a Redis server. Both processes refer to the Redis server on the given IP and port (given as arguments to the trainer) for sync purposes.
