### ISSUE TITLE
Converting Pytorch tensor to OrtValue and vice versa

### ISSUE THREAD

**Issue by nguyenvanhoang7398** [pytorch/pytorch#64245]
## 🚀 Feature
There is currently no effective way to convert between Pytorch and OrtValue and vice versa without using NumPy. There should be a way to create a Pytorch tensor from the data pointer in GPU memory, shape, and type, which can be provided by OrtValue.

## Motivation

I'm trying to convert a seq2seq model from Pytorch to Onnx. The beam search implementation includes lots of operations in Pytorch, so the outputs of the encoder and the previous step of the decoder have to be converted from OrtValue to Pytorch tensor, then back to OrtValue. I have found no direct conversion method except for using Numpy as the medium, i.e. converting Pytorch/OrtValue to Numpy then to OrtValue/Pytorch, which causes CPU-GPU data copying overhead. Since the memory allocation can be derived from OrtValue via start pointer, shape, and data type, we should have a way to create Pytorch tensors from these values.

## Additional context

Here is my conversion code via NumPy as a reference.

```
input_ids_np = input_ids.cpu().numpy()
attention_mask_np = attention_mask.cpu().numpy()
input_ids_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(input_ids_np, 'cuda', 0)
attention_mask_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(attention_mask_np, 'cuda', 0)
io_binding = self.encoder.io_binding()
io_binding.bind_input(name='input_ids', device_type=input_ids_ortvalue.device_name(), device_id=0,
                      element_type=np.longlong, shape=input_ids_ortvalue.shape(),
                      buffer_ptr=input_ids_ortvalue.data_ptr())
io_binding.bind_input(name='attention_mask', device_type=attention_mask_ortvalue.device_name(), device_id=0,
                      element_type=np.longlong, shape=attention_mask_ortvalue.shape(),
                      buffer_ptr=attention_mask_ortvalue.data_ptr())
io_binding.bind_output('hidden_states', 'cuda')
self.encoder.run_with_iobinding(io_binding)
# The following call returns an OrtValue which has data allocated by ONNX Runtime on CUDA
encoder_hidden_state = io_binding.get_outputs()[0]
return BaseModelOutput(torch.tensor(encoder_hidden_state.numpy(), dtype=torch.float32).to(self.device))
```

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment]
@nguyenvanhoang7398  Is it possible for you to put encoder and decoder in a single pytorch model and then convert it to onnx model?

**Comment by garymm** [comment]
ONNXRuntime actually already has code that does this. See 
https://github.com/microsoft/onnxruntime/blob/7166586d7ebcb0169980b188615b8044f06de7f4/orttraining/orttraining/python/training/ortmodule/_utils.py#L22

I suggest you file an issue in the onnxruntime repo asking for these APIs to be made public and included in the onnxruntime Python package.
