### ISSUE TITLE
Bugs are there 

### ISSUE THREAD

**Issue by vikramkanishka** [pytorch/pytorch#64248]
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wet https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_enpy before running it.
python collect_enpy
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`coda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - Cuda version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by H-Huang** [comment]
Hi, please provide a description of the bug.
