### ISSUE TITLE
`torch.nn.functional.cross_entropy` fails gradgradcheck in edge case

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#64256]
## 🐛 Bug

gradgradcheck fails for `torch.nn.functional.cross_entropy` in edge case.

## To Reproduce

```python
import torch
from torch.autograd import gradgradcheck
from torch.nn.functional import cross_entropy

device = "cpu"

torch.manual_seed(0)
input = torch.randn((1, 2), device=device, dtype=torch.float64).requires_grad_(True)
target = torch.randint(0, 2, (1,), device=device, dtype=torch.int64)
weight = torch.tensor([1.0, -1.0], device=device, dtype=torch.float64)

gradgradcheck(
    lambda input, target: cross_entropy(input, target, weight=weight),
    (input, target),
)
```

```
GradcheckError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[0., 0.]], dtype=torch.float64)
analytical:tensor([[ 0.8623, -0.8623]], dtype=torch.float64)
```

The failure is only visible, if

- the snippet is run on the CPU,
- `target` are *not* probabilities (`target = torch.rand_like(input)`), and
- `weight` contains at least one negative value. 

## Additional Context

This was detected in  #63547 while adding the `OpInfo` for `torch.nn.functional.cross_entropy`.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr

**Comment by pmeier** [comment]
Internally, `cross_entropy` simply calls into `nll_loss` in case the target are not probabilities:

https://github.com/pytorch/pytorch/blob/3c15822f5f4ab616eb6a519a0ff9b82fc7a3dc63/aten/src/ATen/native/LossNLL.cpp#L594-L601

Thus, the same error can be reproduced by calling `nll_loss` directly: 

```python
import torch
from torch.autograd import gradgradcheck
from torch.nn.functional import nll_loss, log_softmax

device = "cpu"

torch.manual_seed(0)
input = log_softmax(
    torch.randn((1, 2), device=device, dtype=torch.float64), dim=1
).requires_grad_(True)
target = torch.randint(0, 2, (1,), device=device, dtype=torch.int64)
weight = torch.tensor([1.0, -1.0], device=device, dtype=torch.float64)

gradgradcheck(
    lambda input, target, weight: nll_loss(input, target, weight=weight),
    (input, target, weight),
)
```

```
numerical:tensor([[0., 0.]], dtype=torch.float64)
analytical:tensor([[-0., -1.]], dtype=torch.float64)
```

**Comment by pmeier** [comment]
One more condition: the error is *not* visible for `reduction="none"`.

**Comment by jbschlosser** [comment]
@pmeier Does this issue still exist after #64163 landed?

**Comment by pmeier** [comment]
Yes. Snippet fails on a fresh master.

**Comment by jbschlosser** [comment]
@pmeier Thanks for checking that. Do you have any info on whether this a recent regression or has this behavior been around?

**Comment by Lezcano** [comment]
Fwiw, this is, a priori, a very weird behaviour. This function is a linear function in that argument, so its second derivative is zero. This is, in fact, what it's implemented in `derivatives.yaml`:
```c++
name: nll_loss_backward(Tensor grad_output, Tensor self, Tensor target, Tensor? weight, int reduction, int ignore_index, Tensor total_weight) -> Tensor                                                       
grad_output: nll_loss(grad, target, weight, reduction, ignore_index)                                                                                                                                          self: zeros_like(grad)                                                                                                                                                                                        
target: non_differentiable 
```
so there's something odd going on there.
I'll have a look tomorrow with @pmeier see if we find what's going on there.

**Comment by pmeier** [comment]
> Thanks for checking that. Do you have any info on whether this a recent regression or has this behavior been around?

If it is a regression, it is not a recent one. The same happens on `1.9.0`. Note that this is an edge-case, because I can't think of a practical use case for negative weights.
