### ISSUE TITLE
RPC demo unexpected behavior

### ISSUE THREAD

**Issue by gaow0007** [pytorch/pytorch#64263]
## To Reproduce

1. export MASTER_ADDR=localhost
2. export MASTER_PORT=5678
3. python -u test_rpc.py
```
import torch
import torch.distributed.rpc as rpc
rpc.init_rpc("worker0", rank=0, world_size=1)
```

```
Traceback (most recent call last):
  File "test_rpc1.py", line 3, in <module>
    rpc.init_rpc("worker0", rank=0, world_size=1)
  File "/mnt/lustre/wgao/miniconda3/envs/pipe_transformer/lib/python3.8/site-packages/torch/distributed/rpc/__init__.py", line 194, in init_rpc
    _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
  File "/mnt/lustre/wgao/miniconda3/envs/pipe_transformer/lib/python3.8/site-packages/torch/distributed/rpc/__init__.py", line 230, in _init_rpc_backend
    rpc_agent = backend_registry.init_backend(
  File "/mnt/lustre/wgao/miniconda3/envs/pipe_transformer/lib/python3.8/site-packages/torch/distributed/rpc/backend_registry.py", line 99, in init_backend
    return backend.value.init_backend_handler(*args, **kwargs)
  File "/mnt/lustre/wgao/miniconda3/envs/pipe_transformer/lib/python3.8/site-packages/torch/distributed/rpc/backend_registry.py", line 278, in _tensorpipe_init_backend_handler
    api._init_rpc_states(agent)
  File "/mnt/lustre/wgao/miniconda3/envs/pipe_transformer/lib/python3.8/site-packages/torch/distributed/rpc/api.py", line 116, in _init_rpc_states
    _set_and_start_rpc_agent(agent)
RuntimeError: In Reactor at /opt/conda/conda-bld/pytorch_1616554786078/work/third_party/tensorpipe/tensorpipe/transport/shm/reactor.cc:49 "errorCouldn't allocate ringbuffer for reactor: open: Is a directory"
```

## Expected behavior
No bug report

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Clang version: Could not collect
CMake version: version 3.19.3
Libc version: glibc-2.17

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB
GPU 4: Tesla V100-PCIE-32GB
GPU 5: Tesla V100-PCIE-32GB
GPU 6: Tesla V100-PCIE-32GB
GPU 7: Tesla V100-PCIE-32GB

Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.0a0+e4e171a
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3           py38hf144106_0  
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch                   1.8.1           py3.8_cuda10.1_cudnn7.6.3_0    pytorch
[conda] torchaudio                0.8.1                      py38    pytorch
[conda] torchvision               0.9.1                py38_cu101    pytorch

## Additional context
No other problem

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23 @jjlilley

**Comment by mrshenli** [comment]
cc @lw, have you seen this error before?

**Comment by lw** [comment]
My first guess is that the issue comes from the fact that you have an old-ish kernel (3.10), which doesn't support one of the features that TensorPipe tries to use (namely the `O_TMPFILE` flag for `open`, introduced in 3.11).

However, I still consider this a bug in TensorPipe since we should be detecting such a scenario and just avoid that syscall in that case. I am convinced that at some point I landed a fix for that bug, though I don't remember if that happened in time to make it into the 1.8.1 release of PyTorch, or if it only reached 1.9. Would you be able to try 1.9 and tell me if the issue still reproduces?

Note that however we won't be able to patch the 1.8.1 release, hence if you need to remain on that release and want to workaround this problem you should be able to do so by passing the `_transports=["uv"]` argument to the `TensorPipeRpcBackendOptions` object.

**Comment by gaow0007** [comment]
Your response is very informative. Thanks a lot.

**Comment by lw** [comment]
Does this mean 1.9 worked for you?
