### ISSUE TITLE
Investigate warning of unclosed ArchiveStream in DataPipe

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#64281]
For `TarArchiveReader` and `ZipArchiveReader`, we attach the archive file stream to each file stream here:
https://github.com/pytorch/pytorch/blob/0ef8760bf6b3e8098ef42df60f1e451234151f32/torch/utils/data/datapipes/iter/tararchivereader.py#L55-L57

The main reason is preventing archive file stream is closed by `gc`:
If we deplete the archive reader DataPipe using `list(dp)`, all the file streams within the list are actually closed if we do not attach the archive file stream. And, here is the test to validate it:
https://github.com/pytorch/pytorch/blob/0ef8760bf6b3e8098ef42df60f1e451234151f32/test/test_datapipe.py#L225-L232

As a result, like the tests here:
https://github.com/pytorch/pytorch/blob/0ef8760bf6b3e8098ef42df60f1e451234151f32/test/test_datapipe.py#L207
A warning is raised because we are relying on `gc` to close the archive stream at the end.

Two options:
- Remove reference of archive stream from each file stream, but somehow still make `list(dp)` working
- Find a way to eliminate the opened file stream warning in these tests (TODOs)

cc @SsnL @VitalyFedyunin @ejguan

**Comment by VitalyFedyunin** [comment]
Can you try to explicitly invoke gc.collect() at test tearDown

**Comment by ejguan** [comment]
Kevin was going to work on this.
cc: @NivekT
