### ISSUE TITLE
Slicing torch.tensor results in incorrect size

### ISSUE THREAD

**Issue by jjhuang-ca** [pytorch/pytorch#64331]
## 🐛 Bug

When slicing a tensor, sometimes the output size is incorrect.

## To Reproduce

```
import torch

x = torch.randn(24, 10, 133250)
L = 37500
i = 96000
print('Incorrect')
print(x[..., i:i+L].shape)
print('Last dimension should be {}'.format(L))

x = torch.randn(24, 10, 150000)
L = 37500
i = 96000
print('Correct')
print(x[..., i:i+L].shape)
print('Last dimension should be {}'.format(L))
```
Output:

```
Incorrect
torch.Size([24, 10, 37250])
Last dimension should be 37500
Correct
torch.Size([24, 10, 37500])
Last dimension should be 37500

```
## Expected behavior

First print shows the error, and the second one shows the expected behavior

## Environment
This error happens with v1.9.0 and v1.8.1 shown here.  It happens in MacOS and Linux.

Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.2 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: Could not collect
Libc version: N/A

Python version: 3.7.10 (default, Feb 26 2021, 10:16:00)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-ignite==0.2.0
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchinfo==0.1.5
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.2.0           hecd8cb5_269  
[conda] mkl-service               2.3.0            py37h9ed2024_1  
[conda] mkl_fft                   1.3.0            py37h4a7008c_2  
[conda] mkl_random                1.2.1            py37hb2f4e1b_2  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] pytorch                   1.8.0                   py3.7_0    pytorch
[conda] pytorch-ignite            0.2.0                    pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchaudio                0.8.1                    pypi_0    pypi
[conda] torchinfo                 0.1.5                    pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi

cc @mruberry @rgommers @heitorschueroff

**Comment by SsnL** [comment]
96000+37500 > 133250. This is expected.

---
@H-Huang  This isn't about numpy...
