### ISSUE TITLE
Why reports this Warning? Warning: Unsupported operator CylinderQuery. No schema registered for this operator

### ISSUE THREAD

**Issue by captain81** [pytorch/pytorch#64366]
If we didn't set enable_onnx_checker=False to torch.onnx.export(), it reports this error

RuntimeError: No Op registered for CylinderQuery with domain_version of 13

If we set enable_onnx_checker=False to torch.onnx.export(), it reports this Warning

Warning: Unsupported operator CylinderQuery. No schema registered for this operator.
```
class CylinderQuery(Function):
@staticmethod
def forward(ctx, radius, hmin, hmax, nsample, xyz, new_xyz, rot):
# type: (Any, float, float, float, int, torch.Tensor, torch.Tensor, torch.Tensor) -> torch.Tensor
r"""

    Parameters
    ----------
    radius : float
        radius of the cylinders
    hmin, hmax : float
        endpoints of cylinder height in x-rotation axis
    nsample : int
        maximum number of features in the cylinders
    xyz : torch.Tensor
        (B, N, 3) xyz coordinates of the features
    new_xyz : torch.Tensor
        (B, npoint, 3) centers of the cylinder query
    rot: torch.Tensor
        (B, npoint, 9) flatten rotation matrices from
                       cylinder frame to world frame

    Returns
    -------
    torch.Tensor
        (B, npoint, nsample) tensor with the indicies of the features that form the query balls
    """
    return _ext.cylinder_query(new_xyz, xyz, rot, radius, hmin, hmax, nsample)

@staticmethod
def backward(ctx, a=None):
    return None, None, None, None, None, None, None

@staticmethod
def symbolic(g: torch._C.Graph, radius, hmin, hmax, nsample, xyz, new_xyz, rot):
    return g.op("CylinderQuery", new_xyz, xyz, rot, radius_f=radius, hmin_f=hmin, hmax_f=hmax, nsample_i=nsample)

cylinder_query = CylinderQuery.apply
```

cc @BowenBao @neginraoof

**Comment by BowenBao** [comment]
@captain81 `CylinderQuery` is not an official ONNX operator, hence the error. To support exporting custom operator to ONNX and inference in ONNXRuntime, please checkout https://pytorch.org/docs/stable/onnx.html#custom-operators and https://onnxruntime.ai/docs/how-to/add-custom-op.html

**Comment by BowenBao** [comment]
Hi @captain81,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
