### ISSUE TITLE
`torch.empty_strided(size, stride)` not really equivalent to `torch.empty(size).as_strided(size, stride)`

### ISSUE THREAD

**Issue by ysiraichi** [pytorch/pytorch#64389]
## 📚 Documentation

The documentation [states](https://pytorch.org/docs/master/generated/torch.empty_strided.html?highlight=empty_strided#torch.empty_strided) that _"`torch.empty_strided(size, stride)` is equivalent to `torch.empty(size).as_strided(size, stride)`"_. However, it's not really the case:

```python
>>> size = (2, 3)
>>> stride = (10, 2)
>>> torch.empty_strided(size, stride)
tensor([[4.7000e-38, 5.2610e-38, 4.7127e-38],
        [4.7128e-38, 4.8419e-38, 4.6999e-38]])
>>> torch.empty(size).as_strided(size, stride)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: setStorage: sizes [2, 3], strides [10, 2], storage offset 0, and itemsize 4 requiring a storage size of 60 are out of bounds for storage of size 24
```

Even though they are similar, I wouldn't say they are equivalent. If I understand it correctly, `empty_strided` will always allocate enough memory for the `size-stride` combination. `as_strided`, on the other hand, will raise an error if the combination doesn't fit the allocated storage.

cc @brianjo @mruberry @gchanan

**Comment by mruberry** [comment]
Thank you for pointing out this discrepancy, @ysiraichi. We would accept a PR clarifying the documentation.
