### ISSUE TITLE
[install] Debian packaging for Pytorch

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#644]
Currently a experimental and unofficial packaging for pytorch is available here:
https://github.com/cdluminate/pytorch

Pre-built binary packages:
https://github.com/CDLuminate/pytorch-debs

Different from the Torch7 packaging, Debian/Ubuntu users should be able to create their own Pytorch .deb package with my scripts.

This is still a work in progress, and may turn into *Official Packaging* when it's ready.

**Comment by CDLuminate** [comment]
A CPU-ONLY and experimental non-official Debian/Sid package is available here:
http://debomatic-amd64.debian.net/debomatic/unstable/pool/pytorch_0.1.7+0.1/python3-torch_0.1.7+0.1_amd64.deb

Note, the above package was built with `-march=native` flag on E5-2697v3 CPU, so it may not work for your machine. To build a pytorch.deb locally, follow the instructions at https://github.com/cdluminate/pytorch .

**Comment by CDLuminate** [comment]
| - | python2.7 | python3.5 |
| - | -------------| ------------ |
| CPU-ONLY | [deb](http://debomatic-amd64.debian.net/debomatic/experimental/pool/pytorch_0.1.7~1/python-torch-cpu_0.1.7~1_amd64.deb) | [deb](http://debomatic-amd64.debian.net/debomatic/experimental/pool/pytorch_0.1.7~1/python3-torch-cpu_0.1.7~1_amd64.deb) |
| CUDA | x [1] | x [1] |

Several experimental .deb packages are provided for Debian sid/testing (and Ubuntu) users. This time I removed the `-march=native` flag, so they are expected to work for machines with SSE and AVX instruction sets.

Usage:
```
$ sudo dpkg -i pythonXXXX.deb
$ sudo apt install -f  # this is to fix package dependency.
```

[1] blocker: https://github.com/pytorch/pytorch/issues/675

**Comment by timmeinhardt** [comment]
Your links are all down. I would appreciate a reupload. Thank you very much!

**Comment by CDLuminate** [comment]
@timmeinhardt Updated packages to v0.1.12 and uploaded them to one of my github repo, so these files will not be removed automatically. CPU version is available, I'll upload CUDA version later.

**Comment by CDLuminate** [comment]
@timmeinhardt All packages were updated and uploaded.

**Comment by CDLuminate** [comment]
Temporarily uploaded pytorch Debian packages here (webpages is in Chinese):

http://repo.debiancn.org/pool/main/p/pytorch/
http://repo.debiancn.org/pool/main/p/pytorch-contrib/

Thanks to Debian Chinese Community https://github.com/debiancn

**Comment by CDLuminate** [comment]
Update package for v0.2.0, cpu version: http://debomatic-amd64.debian.net/distribution#unstable/pytorch/0.2.0-1

**Comment by soumith** [comment]
i presume @CDLuminate is continuing to maintain this package. I'm closing this issue as no action is to be taken.

**Comment by CDLuminate** [comment]
There remains some problems to be resolved (e.g. Hardening), and the packaging is still maintained. I'll keep posting updates here until the packages has been uploaded.

**Comment by wavexx** [comment]
I happened to stumble upon this before filing an RFP for pytorch. Any progress in making this into an official debian package? Is there already an ITP request filed I can follow?

**Comment by mmstick** [comment]
@cdluminate Are you still maintaining Debian packaging for PyTorch? I would like to include this in the Pop!_OS CUDA repository alongside Tensorflow (was a major PITA to package by hand).

**Comment by cdluminate** [comment]
@mmstick Yes, I'm just waiting for things to be stabilized and released as the 1.0 version. But note that I'm not going to package the CUDA version[1]. Apart from that, there is a WIP tensorflow package in Debian experimental, but it won't be usable enough until one of my colleagues have rewritten the build system from scratch again.

[1] Nvidia's license is very hard to read, so that I've eventually given up packaging cuDNN for Debian and Ubuntu officially. And you know that, without cuDNN a CUDA version of Pytorch would be useless.

**Comment by mmstick** [comment]
@cdluminate We are already quite comfortable with our debian packaging of CUDA (9.0, 9.1, 9.2, 10.0), cuDNN, NCCL, Tensorflow (C, C++, Python for 1.9, 1.11, 1.12) -- [found here](https://github.com/system76/cuda/). We just lack PyTorch packaging.

**Comment by cdluminate** [comment]
@mmstick Don't wait for my packaging scripts. The requirement for official Debian package is very strict, so the result will be definitely different to what you thought. Especially after checking the repo you pointed to.
