### ISSUE TITLE
Loading OpenNMT model gives ModuleNotFoundError

### ISSUE THREAD

**Issue by debparth** [pytorch/pytorch#64417]
## ❓ Questions and Help
I'm trying to load an OpenNMT model [Link](https://buaaeducn-my.sharepoint.com/personal/liminghao1630_buaa_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fliminghao1630%5Fbuaa%5Fedu%5Fcn%2FDocuments%2FTableBank%5Fv1%2E1%5FMODELZOO%2FRecognition&originalPath=aHR0cHM6Ly9idWFhZWR1Y24tbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvbGltaW5naGFvMTYzMF9idWFhX2VkdV9jbi9FcjNlMzl3d1VQeExzRW9vTVlVMXlsc0JXcXI3SEhtOXcybXlXaThaeEZnYUVRP3J0aW1lPXVrNWlVTmh0MlVn) (First one named `Recognition_All.pt`).

## Command I use:
```
import torch

torch.load("/content/Recognition_All.pt")
```

## Error I got:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-ce769809aef1> in <module>()
      1 import torch
      2 
----> 3 torch.load("/content/drive/MyDrive/Recognition_All.pt")

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    605                     opened_file.seek(orig_position)
    606                     return torch.jit.load(opened_file)
--> 607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    609 

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    880     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
    881     unpickler.persistent_load = persistent_load
--> 882     result = unpickler.load()
    883 
    884     torch._utils._validate_loaded_sparse_tensors()

/usr/local/lib/python3.7/dist-packages/torch/serialization.py in find_class(self, mod_name, name)
    873         def find_class(self, mod_name, name):
    874             mod_name = load_module_mapping.get(mod_name, mod_name)
--> 875             return super().find_class(mod_name, name)
    876 
    877     # Load the data (which may in turn use `persistent_load` to load tensors)

ModuleNotFoundError: No module named 'onmt.inputters.image_dataset'
```

## Envirnment: 
- Google Colab

I tried to google this error but didn't find anything. Did anyone got this error before? If so then help me resolve this.

Edit: I tried to install `OpenNMT-py` from scratch i.e. cloning and installing; yet it didn't resolve the error.

**Comment by gchanan** [comment]
have you filed an issue with OpenNMT?  This looks like a BC issue with their library.

**Comment by gchanan** [comment]
I'm going to close for now, people re-open if this looks like it's a PyTorch issue.

**Comment by debparth** [comment]
@gchanan no, I didn't file a issue over there but I'll now. Thanks for reply.
