### ISSUE TITLE
Exporting the operator addcmul to ONNX is not supported.

### ISSUE THREAD

**Issue by shachargluska** [pytorch/pytorch#64423]
## 🐛 Bug

Models containing torch.addcmul operator cannot be exported to opset11 of onnx.
When attempted, the following error is produced:
```
RuntimeError: Exporting the operator addcmul to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

## To Reproduce

1. run the following code:
```python
class Affine(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.alpha = nn.Parameter(torch.ones((1, 1, dim)))
        self.beta = nn.Parameter(torch.zeros((1, 1, dim)))

    def forward(self, x):
         return torch.addcmul(self.beta, self.alpha, x)

m = Affine(64)
torch.onnx.export(m, torch.randn(1, 32, 64), 'model.onnx', opset_version=11)
```

## Expected behavior

Model successfully exported to onnx, as if the following was run:

(Note the implementation of forward)
```python
class Affine(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.alpha = nn.Parameter(torch.ones((1, 1, dim)))
        self.beta = nn.Parameter(torch.zeros((1, 1, dim)))

    def forward(self, x):
        return self.beta + self.alpha * x

m = Affine(64)
torch.onnx.export(m, torch.randn(1, 32, 64), 'model.onnx', opset_version=11)
```
## Environment

PyTorch version: 1.9.0a0+c3d40fd                                                                                                                                                                         [1/1510]Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.20.4
Libc version: glibc-2.31

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] nvidia-dlprof-pytorch-nvtx==1.2.0
[pip3] pytorch-quantization==2.1.0
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.9.0a0+c3d40fd
[pip3] torchtext==0.10.0a0
[pip3] torchvision==0.10.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.20.3           py38h9894fe3_1    conda-forge
[conda] nvidia-dlprof-pytorch-nvtx 1.2.0                    pypi_0    pypi
[conda] pytorch-quantization      2.1.0                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.9.0a0+c3d40fd          pypi_0    pypi
[conda] torchtext                 0.10.0a0                 pypi_0    pypi
[conda] torchvision               0.10.0a0                 pypi_0    pypi

cc @BowenBao @neginraoof

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1355616.

**Comment by rwightman** [comment]
Is there any update on this one, I was going to use addcmul in a model recently and remembered I already have outstanding bugs again my model repo related to this problem in another model... can a symbolic definition be added in PyTorch so ONNX works with existing ONNX releases / opsets?

**Comment by shubhambhokare1** [comment]
PR #72126 adds support for torch.addcmul. Let me know if this resolves you issue.
@rwightman @shachargluska

**Comment by shachargluska** [comment]
@shubhambhokare1 
Does this solve the problem only for opset9 or for multiple opsets?
In this issue I used opset=11, which is also the target of my use case.

**Comment by shubhambhokare1** [comment]
It should resolve the issue for opset 9 onwards, so yes it should cover opset11

**Comment by shubhambhokare1** [comment]
Closing issue, as this is supported in 1.12 release branch
