### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by rgommers** [pytorch/pytorch#64424]
## 🚀 Feature

Python 3.10.0 final release is around the corner - it'd be great to support it now by having binaries available.

## Motivation

Python 3.10 RC 1 is available. Python release policy has changed, and RC 1 is now the point where the ABI is frozen. This means it is safe to upload wheels to PyPI in the 2 months between RC 1 and final release (planned for Oct 4th). There are a decent number of users who, intentionally or not, install Python 3.10.0 right after it is released. At which point they find that they need binaries. As a result, the Python core team is encouraging project to already upload wheels to PyPI. 

For more context, see https://github.com/numpy/numpy/issues/19630#issuecomment-898314636.

## Pitch

- [ ] Add Python 3.10 in CI
- [ ] Add Python 3.10 support in the `builder` repo for wheels and conda packages
- [ ] Upload wheels to PyPI and conda packages to the `pytorch` channel with the next minor or bugfix release

## Alternatives

Just wait and add 3.10 support later.

## Additional context

It seems unlikely that there will be changes between RC 1 and final that would affect PyTorch binaries (as unlikely as between `3.10.x` and `3.10.x+1`). If that happens though, this can be dealt with by uploading new wheels without requiring a new bugfix release - see https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/.

cc @ezyang @seemethere @malfet

**Comment by rgommers** [comment]
@malfet already said he doesn't want a timeline commitment for 1.10. And that maybe we can start with `cpuonly`.

Also, adding 3.10 support without removing 3.6 support means more builds, which is a problem for CI load.

**Comment by seemethere** [comment]
Another thing to consider about this is dependencies being updated to 3.10 and the availability of those dependencies on popular package managers.

For context, with the 3.9 upgrade last year we had multiple difficulties for dependencies, especially on conda leading to us introducing `conda-forge` as a dependency which then added a whole slew of problems that we felt early on into the year with the 3.9 builds.

I'd love to get 3.10 support in as quickly as possible but there should be an understanding that we can't really introduce 3.10 builds until our dependencies update accordingly

**Comment by rgommers** [comment]
> I'd love to get 3.10 support in as quickly as possible but there should be an understanding that we can't really introduce 3.10 builds until our dependencies update accordingly

That makes perfect sense. Now that numpy is dropped as a dependency, there is only one Python runtime dependency left - `typing_extensions`, which is pure Python and already explicitly supports 3.10 in its Aug 30 release.

So it's about build-time dependencies - `numpy`, `pyyaml`, `cffi` look like the three that are relevant (the rest is pure Python or non-Python). 

Are there any others you can think of that may be problematic?

**Comment by ezyang** [comment]
honestly, only pyyaml is a real build-time dependency, and if it is really busted we can technically bootstrap the code generation off of an older version of Python, no biggie.

**Comment by rgommers** [comment]
Continued in gh-66424, so closing this as a duplicate.
