### ISSUE TITLE
[Beta] FSDP flatten parameter redesign

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64464]
Thanks Min Xu's initial idea and discussion about redesign FSDP flatten parameter.

Right now all the original parameters of a module are cat into a big flat tensor, this flat tensor is registered as a new parameter of the module, and it is called "flat_parameter". All the original parameters of the module are de-registered and are set as general attributes of the module.  After flattening, the big flat tensor is sharded into chunks, each rank keeps one chunk of the tensor. 

In this way, all_gather() this big flat tensor from other ranks could only be called once during forward, and thus it is efficient.  

However, this also caused usability issue because of this newly introduced parameter and de-registered original parameters.  Usually users expect original parameter names to be kept and they may have some processing outside of FSDP that is based on these original parameter names (e.g. checkpoint file and optimizer states expect original parameters usually). 

So we may need to redesign this flatten parameter method. Solutions could be: 
1.  Instead of registering the new 'flat_parameter', allocate buffers to hold the flat tensor that cats tensors of original parameters, original parameters will be kept and be views of the flat tensor. This is similar to the "gradient_as_bucket_view" feature in DDP
2. not flatten tensor in advance, instead of all_gather a flat tensor once, we can introduce a new collective call 'all_gather_coaleced' that can all gather a list of parameters tensors once, this may need to copy the list of parameter tensors to a buffer every time when 'all_gather_coaleced' is called and introduce some performance regression. but this approach could simplify FSDP implementation

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by zhaojuanmao** [comment]
redesign this could improve backward pass computation as well, right now this big 'flat_parameter' tensor can not be reduced until backward pass computation of this FSDP instance is done, it does not take advantage of bucketing to overlap communication with computation of current layer

**Comment by zhaojuanmao** [comment]
one example about checkpoint usability problem using 'flatten_parameter'

**Comment by mrshenli** [comment]
another instance of the usability issue. `minGPT` relies on the parameter names to toggle decay. 

https://github.com/karpathy/minGPT/blob/4050db60409b5bbaaa3302cee1e49847fc145c65/mingpt/model.py#L147-L159

**Comment by awgu** [comment]
The `use_orig_params=True` work follows approach 1 outlined above, which we are actively developing.
