### ISSUE TITLE
[caffe2] No gradient for the MergeDim operator

### ISSUE THREAD

**Issue by edubois** [pytorch/pytorch#6447]
There is no gradient operator for the MergeDim operator. It should prepend a dimension.

**Comment by Swetko** [comment]
MergeDim can be modified to output a tensor containing the original dims. Then we can just say the gradient of MergeDim is Reshape and connect the appropriate inputs outputs.

**Comment by edubois** [comment]
Yes, that's the idea, but I'm trying to use a MergeDim instead of a reshape. I don't see why there wouldn't be a gradient for this operator as I see one for the Prepend.

**Comment by Swetko** [comment]
I think even easier solution would be to just do reshape like the original tensor. Let me try this and I'll do Pull request.

**Comment by edubois** [comment]
Ok, but be careful, I saw a strange behavior that I don't understand when trying to reduce dimensionality in caffe2 (from 5d to 4d). The print of the tensor shows the right size, but the gradient gets wrong in its dimensions.

**Comment by Swetko** [comment]
I am not too familiar with that. If that's a separate problem, post more detailed issue with just that resizing example.

**Comment by Swetko** [comment]
Check this:  https://github.com/pytorch/pytorch/pull/6453
If you want to have the changes now and are using source, just copy my changes.

**Comment by edubois** [comment]
Ok, haven't tried, but sounds good to me.
