### ISSUE TITLE
Opset warning keeps popping up even if opset version is set to 11 for torch.onn.export

### ISSUE THREAD

**Issue by fengyuentau** [pytorch/pytorch#64485]
## 🐛 Bug

Trying to convert a model with `torchvision.ops.nms` into onnx. Even if the opset version is set to 11, the opset warning still pops up when converting. However, the convert itself is successful.

## To Reproduce

1. Just run the code attached.

## Expected behavior

Stop the opset warning when the opset version is set to 11 as requested.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Ubuntu 20.04.1 LTS (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): `conda`
 - Build command you used (if compiling from source): None
 - Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
 - CUDA/cuDNN version: 10.2 / 7.6.5
 - GPU models and configuration: GeForce GTX 1080 Ti
 - Any other relevant information: None

## Additional context

```python
from __future__ import print_function
import torch
from torch.autograd import Variable, Function
import torch.nn as nn
import numpy as np
import os.path
import onnx
import io
from torchvision.ops import nms

class NMS(nn.Module):
    def forward(self, x, score):
        return x[nms(x, score, 0.5)]

x = Variable(torch.Tensor(
    [[400, 400, 600, 600],
     [420, 420, 620, 620],
     [427, 427, 627, 627],
     [500, 500, 700, 700],
     [610, 620, 750, 760]
    ]
))
score = Variable(torch.Tensor(
    [0.9, 0.95, 0.88, 0.87, 0.75]
))
model = NMS()
f = io.BytesIO()
with torch.no_grad():
    torch.onnx.export(model, (x, score), f, export_params=True, opset_version=11)
```

cc @BowenBao @neginraoof

**Comment by shubhambhokare1** [comment]
@fengyuentau I ran your script using the latest pytorch nightly, I don't seem to be getting any error message.
Could you:
1) Try this with the latest pytorch nightly build
2) Post the warning you are seeing if 1) does not work

**Comment by fengyuentau** [comment]
@shubhambhokare1 I tried with the latest pytorch nightly, and got no warning messages. Also tried 1.9.0 (stable), and got the following `UserWarning` message:
```shell
/home/***/miniconda3/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:697: UserWarning: This model contains a squeeze operation on dimension 1 on an input with unknown shape. Note that if the size of dimension 1 of the input is not 1, the ONNX model will return an error. Opset version 11 supports squeezing on non-singleton dimensions, it is recommended to export this model using opset version 11 or higher.
  warnings.warn("This model contains a squeeze operation on dimension " + str(squeeze_dim) + " on an input " +
```
