### ISSUE TITLE
Math_gpu.cu fails to compile on windows

### ISSUE THREAD

**Issue by zipy124** [pytorch/pytorch#64484]
## 🐛 Bug

When compiling the 1.9.0 tag under windows the build fails at math_gpu.cu with the following errors:
```
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(908): error: namespace "thrust" has no member "host_vector"
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(908): error: type name is not allowed
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(908): error: expected an expression
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(909): error: namespace "thrust" has no member "host_vector"
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(909): error: type name is not allowed
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(909): error: expected an expression
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(910): error: namespace "thrust" has no member "host_vector"
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(910): error: type name is not allowed
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(910): error: expected an expression
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(912): error: identifier "A_array" is undefined
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(913): error: identifier "B_array" is undefined
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(914): error: identifier "C_array" is undefined
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(917): error: identifier "A_array" is undefined
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(919): error: identifier "B_array" is undefined
c:\users\zaksm\source\repos\pytorch\caffe2\utils\math_gpu.cu(920): error: identifier "C_array" is undefined
```

## To Reproduce

1. Clone repo and sub-modules under 1.9.0 tag
2. run scripts/build_windows.bat
3. Observe failed build

## Expected behavior

A compilation without errors

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: N/A

Python version: 3.9 (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: N/A
CUDA runtime version: 11.4.100
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 970
Nvidia driver version: 471.41
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[conda] Could not collect
```

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Windows 10 Home
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): build_windows.bat
 - Python version: 3.9
 - CUDA/cuDNN version: CUDA 11.4, cuDNN 8.2.4
 - GPU models and configuration: gtx 970
 - Any other relevant information:

**Comment by ptrblck** [comment]
You would need to update your PyTorch repository, as the fix landed [here](https://github.com/pytorch/pytorch/pull/61004) (or use an older CUDA version for the `1.9.0` release branch).

**Comment by zipy124** [comment]
Ok thanks!

**Comment by chi0tzp** [comment]
> You would need to update your PyTorch repository, as the fix landed [here](https://github.com/pytorch/pytorch/pull/61004) (or use an older CUDA version for the `1.9.0` release branch).

Hi @ptrblck, how can I install this specific [version](https://github.com/pytorch/pytorch/commit/c74c0c571880df886474be297c556562e95c00e0) of PyTorch, ideally using pip in a venv? Also, any insights on when CUDA 11.4 will be available in the stableor nightly version? Many thanks!

**Comment by ptrblck** [comment]
You could build PyTorch from source using  commit after the PR was merged (or just the current master) or install the nightly binary using the instructions given [here](https://pytorch.org/get-started/locally/).

There is no definitive time line for CUDA11.4 in the binaries, as this CUDA release needs refactoring of the build pipeline.
