### ISSUE TITLE
Not clear what the word "uninitialized" means in `Returns a tensor filled with uninitialized data`

### ISSUE THREAD

**Issue by bhattbhuwan13** [pytorch/pytorch#64505]
## 📚 Documentation

The documentation [states](https://pytorch.org/docs/master/generated/torch.empty_strided.html?highlight=empty_strided#torch.empty_strided) that the function `torch.empty_strided()` **returns a tensor filled with uninitialized data**. What does *uninitialized* means here? Does it mean random?
<img width="738" alt="Screen Shot 2021-09-04 at 3 53 04 PM" src="https://user-images.githubusercontent.com/15955955/132090848-cb836e8a-cdaa-4de2-a54a-6d98e33dfdd5.png">
 

cc @brianjo @mruberry

**Comment by eedalong** [comment]
I think `Uninitilized` means it just allocate the memory block but do not memset or fill the memory with specific value

**Comment by bhattbhuwan13** [comment]
@eedalong 
> I think `Uninitilized` means it just allocate the memory block but do not memset or fill the memory with specific value

Upon creating the array using `torch.empty_strided()`, I get an array that is initialized with some random values. 
```python
>>> a = torch.empty_strided(
      (1,2),
      (1,2)
    )
>>> print(a)

tensor([[-4.5413e+01,  3.7835e-44]])
```
Hence, `Uninitialized` cannot mean that it doesn't fill the memory with specific values.

You can see the same in official documentation as well:

```python
>>> a = torch.empty_strided((2, 3), (1, 2))
>>> a
tensor([[8.9683e-44, 4.4842e-44, 5.1239e+07],
        [0.0000e+00, 0.0000e+00, 3.0705e-41]])
>>> a.stride()
(1, 2)
>>> a.size()
torch.Size([2, 3])
```

**Comment by eedalong** [comment]
I think the random values you see are just the float number translation of the memory block. Lets say you allocate a 12 bytes memory block and the memory blocks initial value is 000000000000, then you can translate it into [0.0, 0.0, 0.0, 0.0] 4 float values. Number are just how we translate this memory block, you see random numbers here does not mean pytorch initialize it  with random values because set a memory block to random values is time consuming

**Comment by eedalong** [comment]
@bhattbhuwan13

**Comment by bhattbhuwan13** [comment]
@eedalong, Is there any way to confirm what you think?
Since it is initialized with some value, the word uninitialized doesn't make sense. The word needs explanation.

**Comment by eedalong** [comment]
You can call torch.random() to generate a Tensor and call torch.empty to allocate same shape Tensor and measure the time they cost respectively. You should see that torch.empty is much faster then torch.random,  because torch.random really does initialization.

**Comment by bhattbhuwan13** [comment]
@eedalong, if a variable `a` isn't initialized, what is its value? Is it `None` or some value representing the location of the memory it points to? 
My point is that the word `uninitialized` used to describe working mechanism of `torch.empty_strided()` in the documentation is misleading. It could explained a little more in detail so that other users are not confused in future.

**Comment by eedalong** [comment]
It's pretty obvious to me I think ==!!

**Comment by mruberry** [comment]
As @eedalong points out the term "uninitialized" is a computer science term of art for acquiring memory without writing to it (initializing it). The memory is just filled with whatever bits it had when it was acquired from the OS, which are interpreted by PyTorch as numbers in the tensor's datatype. It's expected that users will write to these tensors before using them.

PyTorch could provide a glossary for terms of art like "uninitialized" but we typically don't explain common terms from computer science or even common jargon related to the operators. For example the definition of [linalg.cond](https://pytorch.org/docs/master/generated/torch.linalg.cond.html) uses the term "singular value" without explaining what it is.

**Comment by bhattbhuwan13** [comment]
Your explanation clarifies how the function works. Thanks
