### ISSUE TITLE
Incorrect instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Stevenjin8** [pytorch/pytorch#64507]
## 📚 Documentation

The instructions in the [building documentation](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#building-documentation) instructs to `cd` into the `docs` folder twice.

cc @brianjo @mruberry

**Comment by mrshenli** [comment]
Hey @Stevenjin8, would you like to submit a fix? :)

**Comment by mrshenli** [comment]
Oh, I saw you already submitted a PR at https://github.com/pytorch/pytorch/pull/64508. Thanks!

**Comment by mrshenli** [comment]
closed by #64508
