### ISSUE TITLE
How do I install pytorch 1.3.1?

### ISSUE THREAD

**Issue by atusi-nakajima** [pytorch/pytorch#64506]
OS:ubuntu18.04
cuda10.0
cudnn7.6.5

## ❓ Questions 

I'm having trouble installing pytorch 1.3.1. I tried to install it from the list on the official [website](https://pytorch.org/get-started/previous-versions/) but there is no version 1.3.1.
Can I use this [page](https://github.com/pytorch/pytorch/tree/v1.3.1) as a reference to put it in? Also, do I need anaconda, and if not, how do I put in the following parts for pip?
Please help me.

cc @ezyang @seemethere @malfet

**Comment by pranavarya007** [comment]
Try this -
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
run this command in your terminal

**Comment by atusi-nakajima** [comment]
I tried the above command, but it gave me version 1.4.0.
Is there any way to set it to 1.3.1?

**Comment by atusi-nakajima** [comment]
In the meantime, I will try to install it by following the instructions on this [page.](https://github.com/pytorch/pytorch/tree/v1.3.1) If you find anything wrong, please let me know. 
(After adding cuda, cudnn, and anaconda)

`conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing

#Add LAPACK support for the GPU if needed
conda install -c pytorch magma-cuda90

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
git checkou  ee77ccb  **###I added this part by myself.**
#if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
`

Note that
`export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/. /"} ` is  not clear to me.
Do I need to rewrite the dirname and which conda parts on the right side of = to be appropriate for my environment? Or can I just type it in as is?

**Comment by ezyang** [comment]
we don't support old versions of pytorch; for more help go to https://discuss.pytorch.org/
