### ISSUE TITLE
Pair-wise KL distance

### ISSUE THREAD

**Issue by VietHoang1512** [pytorch/pytorch#64528]
Hi everyone, is there any way to efficiently calculate pair-wise KL divergence between 2 sets of samples A (batch_size x dimension) and B (batch_size x dimension), which returns a tensor of (batch_size x batch_size) in Pytorch. It's similar to torch.cdist but with KL divergence rather than p-norm distance? Thank you so much.

**Comment by mrshenli** [comment]
Hey @VietHoang1512, please use [PyTorch Forum](https://discuss.pytorch.org/) for questions. I am closing this issue. Please feel free to open a new one if this turns out to be a feature request or bug report. Thanks!
