### ISSUE TITLE
tensor.sum() leads to in-contiguous layout grad in backward

### ISSUE THREAD

**Issue by maxwellzh** [pytorch/pytorch#64529]
## To Reproduce

Create a file `test.py` with the content.

```
import torch

class Anything(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        return x.new_ones((5, ))

    @staticmethod
    def backward(ctx, grad_outputs):

        print("Is gradient w.r.t. sum of b contiguous? ",
              grad_outputs.is_contiguous())
        return grad_outputs.new_zeros((1,))


if __name__ == "__main__":
    funct = Anything.apply
    a = torch.zeros((1,), requires_grad=True)
    b = funct(a)
    bs = b.sum()
    print("Is sum of b contiguous? ", bs.is_contiguous())
    bs.backward()
    print(a.grad)
```

Execute the script

```
python test.py
# output
Is sum of b contiguous?  True
Is gradient w.r.t. sum of b contiguous?  False
tensor([0.])
```

## Expected behavior

`grad_outputs.is_contiguous()=True`

## Environment

```
PyTorch version: 1.8.2
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090
GPU 2: GeForce RTX 3090
GPU 3: GeForce RTX 3090
GPU 4: GeForce RTX 3090
GPU 5: GeForce RTX 3090
GPU 6: GeForce RTX 3090
GPU 7: GeForce RTX 3090
GPU 8: GeForce RTX 3090

Nvidia driver version: 455.23.05
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.2
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.9.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3           py38hf144106_0  
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch                   1.8.2           py3.8_cuda11.1_cudnn8.0.5_0    pytorch-lts
[conda] torchaudio                0.8.2                      py38    pytorch-lts
[conda] torchvision               0.9.2                py38_cu111    pytorch-lts
```

## Additional context

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @VitalyFedyunin @jamesr66a

**Comment by maxwellzh** [comment]
I found a similar issue here #35957, which seems like an issue with torch early version.

**Comment by maxwellzh** [comment]
similar issue here #35957

**Comment by albanD** [comment]
Hi,

Actually all the backward function should be able to handle non-contiguous inputs. So I don't think this is a problem.

Note that before populating the `.grad` field of a Tensor, we will make it contiguous to avoid any issue if the user modifies that field inplace.

Does this cause any specific issue for you?

**Comment by ngimel** [comment]
If your c++ function can handle only contiguous inputs, you should call `grad.contiguous()`. Whatever the perf hit, you have to take it. An alternative is for pytorch to call `.contiguous()` when computing the grad_input of the `.sum` function (typically pytorch just expands grad_output inplace) both for cases where its needed (like yours) and when it's not needed (when the next function can handle discontiguous inputs).

**Comment by albanD** [comment]
As mentioned above, you need a `.contiguous()` call anyway if your function can only handle contiguous inputs (it will be in your formula or in the sum one). And having it in your formula only is more efficient in general.

> Wouldn't it be more reasonable that the grad_ouputs (input of the backward function) always has the same properties (size, dtype, device, etc.) as the output of the forward function?

I'm afraid this is too restrictive. In particular, there are many cases where the backward is returning views when the forward wasn't which is a big perf benefit that we don't want to give up.

**Comment by maxwellzh** [comment]
Thanks @albanD and @ngimel for the kindly clarification. 
It seems an invoking of `contigious()` is inevitable for my implementation, but the discussion is helpful.
