### ISSUE TITLE
Random Cuda Installation failed in Windows Nightly CI

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#64536]
## 🐛 Bug

Recently, Random Cuda Installation Failed in CI multiple times on Windows.

## To Reproduce
Sep 5  cuda 11.1
https://app.circleci.com/pipelines/github/pytorch/pytorch/376267/workflows/1ebff479-db25-43de-9adc-81a8a9c6ac3d/jobs/15861939
Aug 28 cuda 11.3
https://app.circleci.com/pipelines/github/pytorch/pytorch/372302/workflows/8a242e28-ad44-4af6-a53a-a031cb9e92d2/jobs/15706071

One of My test PRs cuda 10.2
https://app.circleci.com/pipelines/github/pytorch/pytorch/375941/workflows/d66d1515-7e8c-4e4b-b605-ba7ea758c298/jobs/15849124

## Expected behavior

There shouldn't be errors

## Additional context

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

**Comment by mszhanyi** [comment]
some common error msg:
```
ERROR: [NVI2.Installation] 1208@CInstallationCheckingBase::CheckConstraints : Constraints blocked install.

ERROR: [NVI2.InstallThread] 54@CInstallThread::ThreadProc : Install failed - Exception {0xe4080000; File: InstallationStepper.cpp; Line: 382} - going to fail state.

ERROR: [NVI2.NVInstaller] 240@CNVInstaller::PerformSteps : Installation failed with error Exception {0xe4080000; File: InstallThread.cpp; Line: 112}.
```

**Comment by peterjc123** [comment]
```
     41.231 |  WARNING: [NVI2.CNVRejectTestWUInstall] 66@CNVRejectTestWUInstall::InvokeTest : Windows Update is currently installing or uninstalling updates. 
     41.234 |  WARNING: [NVI2.NVRejectTestConstraint] 147@CNVRejectTestConstraint::InvokeCheck : Activity constraint "WUINSTALL" failed. 
     41.234 |    DEBUG: [NVI2.NVInstaller] 3036@CNVInstaller::IsConstraintFailureOverridden : Constraint "WUINSTALL" can not be overridden in failure case. 
```
@mszhanyi It's just the same issue as https://github.com/pytorch/pytorch/issues/63139.
