### ISSUE TITLE
Replace `clone.detach` with `detach.clone`

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#64532]
## 🐛 Bug

`detach.clone` is recommended over `clone.detach`: https://stackoverflow.com/a/62496418

However, there are a few places in the project that use the latter. Most notably the SGD implementation:

https://github.com/pytorch/pytorch/blob/544c8e6a5d26efdf1cf679b313893fe119825930/torch/optim/_functional.py#L170

Other occurrences can be found with:

https://grep.app/search?q=clone%5C%28.%2A%5C%29.detach%5C%28&regexp=true&filter[repo][0]=pytorch/pytorch

## Additional context

Sorry if this should've been marked as a "feature request"!

cc @vincentqb @iramazanli @jbschlosser

**Comment by albanD** [comment]
Could you send a PR fixing this please?

**Comment by carmocca** [comment]
Do you prefer one PR per file or one larger PR with all changes? There are 26 occurrences.

**Comment by albanD** [comment]
A single PR should be ok. Thanks for checking!
