### ISSUE TITLE
Discrepancy in quantization with Pytorch 1.10

### ISSUE THREAD

**Issue by daniellepintz** [pytorch/pytorch#64564]
Hi, I am working on Pytorch Lightning, and we have noticed a discrepancy/issue with quantization _with Pytorch 1.10 as compared to other versions Pytorch_. This discrepancy can be seen in the following test that is failing: 
```
FAILED tests/callbacks/test_quantization.py::test_quantization[True-True-average]
FAILED tests/callbacks/test_quantization.py::test_quantization[True-False-average]
FAILED tests/callbacks/test_quantization.py::test_quantization[False-True-average]
FAILED tests/callbacks/test_quantization.py::test_quantization[False-False-average]
```
with this error:
```
         quant_score = torch.mean(torch.tensor([mape(qmodel(x), y) for x, y in dm.test_dataloader()]))
         # test that the test score is almost the same as with pure training
>       assert torch.allclose(org_score, quant_score, atol=0.45)
E       assert False
E        +  where False = <built-in method allclose of type object at 0x7f66d3b6a780>(tensor(0.3262), tensor(0.9988), atol=0.45)
E        +    where <built-in method allclose of type object at 0x7f66d3b6a780> = torch.allclose

tests/callbacks/test_quantization.py:56: AssertionError
```

(full stack trace can be found by searching for `test_quantization` in https://github.com/PyTorchLightning/pytorch-lightning/runs/3483032531)

Code pointer:
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/callbacks/test_quantization.py#L34-L74

This test checks for parity between a normal model (Lightning Module) and a quantized model. The failing line is comparing the mean_absolute_percentage_error between normal model and quantized.  It seems quant_score is higher than it should be with Pytorch 1.10. When I run the test locally (with Pytorch 1.9) quant_score = 0.5105 but as seen from stack trace with Pytorch 1.10 it is .9988

Nothing has changed on the Lightning side, so we were wondering if something might have changed on the Pytorch side to cause this?

Thanks in advance!

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
I don't feel there are changes in Linear and Linear ReLU, looks like this is checking the score difference between floating point model and quantized model, there is no guarantee on that, I think it might be better to change the test to test for something else

**Comment by daniellepintz** [comment]
thanks @jerryzh168! @Borda what do you think about changing the test?

**Comment by daniellepintz** [comment]
update on this, I found that https://github.com/pytorch/pytorch/pull/63043 caused this discrepancy, and reverting it "fixes" the test. 

From the PR summary: "There may be some numerics difference between the old observer code in observer.py and the new fused module that was re-written in C++/CUDA to perform observe + fake_quantize."

From @jerryzh168 's answer it sounds like the score differences causing our test failure are okay, and we can safely delete this assertion:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9d982080df5dbc347249eeeae3311b18b397ac54/tests/callbacks/test_quantization.py#L56

but just wanted to comment here to double check 

cc @jerryzh168 @Borda @ananthsub

**Comment by daniellepintz** [comment]
alternatively we can just update this line in the test:

https://github.com/PyTorchLightning/pytorch-lightning/blob/9d982080df5dbc347249eeeae3311b18b397ac54/pytorch_lightning/callbacks/quantization.py#L191
to `get_default_qat_qconfig(self._qconfig, None)`

**Comment by daniellepintz** [comment]
Alternatively we could just update this line in our source code:
https://github.com/PyTorchLightning/pytorch-lightning/blob/9d982080df5dbc347249eeeae3311b18b397ac54/pytorch_lightning/callbacks/quantization.py#L191
to `get_default_qat_qconfig(self._qconfig, None)`

**Comment by vkuzo** [comment]
cc @supriyar , just to clarify, do we expect the results reported here?

**Comment by supriyar** [comment]
> cc @supriyar , just to clarify, do we expect the results reported here?

We do expect some difference in the two approaches. Specifically in the `calculate_qparams` function that is used to compute the scale/zero_point given the min/max. 

The observer code is here https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/observer.py#L278-L292 and it misses a few cases that is used to compute the scale values and nudging the zero-point values which we cover in the operator https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/quantized/cuda/fused_obs_fake_quant.cu#L28-L35.
The operator implementation is based on what we use in fbgemm today to compute the qparams (ref https://github.com/pytorch/FBGEMM/blob/7588d9d804826b428fc0e4fd418e9cc3f7a72e52/src/QuantUtils.cc#L32)

We had tested this out on mobile-vision/d2go model and didn't see a noticeable difference in the predictions with the new approach compared to the previous.

In this case, to clarify are we comparing the output of the FP32 train model and the fake-quantized QAT train model, or is this comparing the outputs of the model after conversion to quantized model (i.e. after calling `torch.quantization.convert`)? And does a higher quant_score signify a regression in the results compared to before?

**Comment by daniellepintz** [comment]
@supriyar This is comparing the outputs of the model after conversion to quantized model (after calling torch.quantization.convert)

**Comment by daniellepintz** [comment]
> This test is comparing both the fake-quantized QAT train model

or rather it was before https://github.com/pytorch/pytorch/pull/63043, now it uses FusedMovingAvgObsFakeQuantize

**Comment by daniellepintz** [comment]
> And does a higher quant_score signify a regression in the results compared to before?

yes, using mean_absolute_percentage_error calculated here: https://github.com/PyTorchLightning/metrics/blob/master/torchmetrics/functional/regression/mean_absolute_percentage_error.py#L68

**Comment by vkuzo** [comment]
hi folks, is this still relevant or safe to close?

**Comment by daniellepintz** [comment]
yup, we can close
