### ISSUE TITLE
Exporting the operator inverse to ONNX is not supported

### ISSUE THREAD

**Issue by AditiDeepak15** [pytorch/pytorch#64577]
## Question

I am trying to convert a model from Pytorch to ONNX format and I am facing the following error during conversion. I have copied the error stack to this post. It would be great to have some suggestions regarding this -

## Further information
Traceback (most recent call last):
File "/code/demo-gen-onnx.py", line 78, in
make_animation(generator, cpu=opt.cpu)
File "/code/demo-gen-onnx.py", line 67, in make_animation
torch.onnx.export(generator.module, args,'first-order-model-generator.onnx',opset_version=11,export_params=True)
File "/anaconda/lib/python3.9/site-packages/torch/onnx/init.py", line 275, in export
return utils.export(model, args, f, export_params, verbose, training,
File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export
_export(model, args, f, export_params, verbose, training, input_names, output_names,
File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 689, in _export
_model_to_graph(model, args, verbose, input_names,
File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
graph = _optimize_graph(graph, operator_export_type,
File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
graph = torch._C._jit_pass_onnx(graph, operator_export_type)
File "/anaconda/lib/python3.9/site-packages/torch/onnx/init.py", line 313, in _run_symbolic_function
return utils._run_symbolic_function(*args, **kwargs)
File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 990, in _run_symbolic_function
symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 944, in _find_symbolic_in_registry
return sym_registry.get_registered_op(op_name, domain, opset_version)
File "/anaconda/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 116, in get_registered_op
raise RuntimeError(msg)
RuntimeError: Exporting the operator inverse to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

Code information -
demo-gen-onnx.py - Conversion script from Pytorch model to ONNX
The model code consists of kp_driving (keypoints of the driving video) and kp_source (keypoints of the source image) each of which consists keypoints of the shape [1,10,2] and jacobian of the shape [1,10,2,2].  
The torch.inverse() function works outside the torch.onnx.export() line, however, exporting the inverse operation to ONNX is throwing a runtime error.  

Dependencies -
torch==1.9.0
torchvision==0.6.0
tqdm==4.24.0
imageio==2.3.0
PyYAML==5.1
scikit-image==0.14.0
scikit-learn==0.19.2
pandas==0.23.4
python-dateutil==2.7.3
pytz==2018.5
scipy==1.1.0
matplotlib==2.2.2
numpy==1.15.0

**Comment by hwangdeyu** [comment]
Seems it's a known operator. https://github.com/onnx/onnx/issues/3300.
Could you tell me which model is met this issue?

**Comment by AditiDeepak15** [comment]
The model mainly utilizes the concept of Generative Adversarial Neural Networks to generate a video by animating the source input image along with the motion derived by the driving video (Keypoints are extracted from the driving video (per frame) and the appearance is extracted from the source image which are used as inputs to the model).

**Comment by garymm** [comment]
@hwangdeyu please add relevant PRs here.

**Comment by hwangdeyu** [comment]
@AditiDeepak15  
This op is added by these two PRs:
https://github.com/onnx/onnx/pull/2578
https://github.com/onnx/onnx/pull/2706
However, removed by this PR https://github.com/onnx/onnx/pull/2747 because it is not fully verified to work as it should.

Please follow this https://github.com/onnx/onnx/issues/3300, I will also contact them.

**Comment by RAJA-PARIKSHAT** [comment]
@AditiDeepak15  @hwangdeyu @garymm did anyone find solution of this, as I am stuck on the same issue.

**Comment by SEUvictor** [comment]
> ## Question
> I am trying to convert a model from Pytorch to ONNX format and I am facing the following error during conversion. I have copied the error stack to this post. It would be great to have some suggestions regarding this -
> 
> ## Further information
> Traceback (most recent call last): File "/code/demo-gen-onnx.py", line 78, in make_animation(generator, cpu=opt.cpu) File "/code/demo-gen-onnx.py", line 67, in make_animation torch.onnx.export(generator.module, args,'first-order-model-generator.onnx',opset_version=11,export_params=True) File "/anaconda/lib/python3.9/site-packages/torch/onnx/init.py", line 275, in export return utils.export(model, args, f, export_params, verbose, training, File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export _export(model, args, f, export_params, verbose, training, input_names, output_names, File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 689, in _export _model_to_graph(model, args, verbose, input_names, File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph graph = _optimize_graph(graph, operator_export_type, File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph graph = torch._C._jit_pass_onnx(graph, operator_export_type) File "/anaconda/lib/python3.9/site-packages/torch/onnx/init.py", line 313, in _run_symbolic_function return utils._run_symbolic_function(*args, **kwargs) File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 990, in _run_symbolic_function symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type) File "/anaconda/lib/python3.9/site-packages/torch/onnx/utils.py", line 944, in _find_symbolic_in_registry return sym_registry.get_registered_op(op_name, domain, opset_version) File "/anaconda/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 116, in get_registered_op raise RuntimeError(msg) RuntimeError: Exporting the operator inverse to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
> 
> Code information - demo-gen-onnx.py - Conversion script from Pytorch model to ONNX The model code consists of kp_driving (keypoints of the driving video) and kp_source (keypoints of the source image) each of which consists keypoints of the shape [1,10,2] and jacobian of the shape [1,10,2,2]. The torch.inverse() function works outside the torch.onnx.export() line, however, exporting the inverse operation to ONNX is throwing a runtime error.
> 
> Dependencies - torch==1.9.0 torchvision==0.6.0 tqdm==4.24.0 imageio==2.3.0 PyYAML==5.1 scikit-image==0.14.0 scikit-learn==0.19.2 pandas==0.23.4 python-dateutil==2.7.3 pytz==2018.5 scipy==1.1.0 matplotlib==2.2.2 numpy==1.15.0

Hi，
Have you solved this problem？

**Comment by thiagocrepaldi** [comment]
@AditiDeepak15 this bug has been closed as a full runnable repro was not provided. Feel free to reopen it if the bug is relevant and you are willing to provide a valid repro
