### ISSUE TITLE
Memory Leak in torch.autograd.grad

### ISSUE THREAD

**Issue by NUS-Tim** [pytorch/pytorch#64586]
I try to realize the gradient penalty in WGAN-GP, but it said:

```
RuntimeError                              Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/lib/python3.8/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    243                 create_graph=create_graph,
    244                 inputs=inputs)
--> 245         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    246 
    247     def register_hook(self, hook):

/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    143         retain_graph = create_graph
    144 
--> 145     Variable._execution_engine.run_backward(
    146         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    147         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 2; 15.75 GiB total capacity; 13.76 GiB already allocated; 2.75 MiB free; 14.50 GiB reserved in total by PyTorch)
```

The problem is from:

     def calculate_gradient_penalty(real_images, fake_images):
  
        eta = torch.FloatTensor(batch_size,1,1,1).uniform_(0,1) # torch.Size([BS, 1, 1, 1])
        eta = eta.expand(batch_size, real_images.size(1), real_images.size(2), real_images.size(3)) 
        eta = eta.to(device) # Send to GPU
    
        interpolated = eta * real_images + ((1 - eta) * fake_images)
        interpolated = interpolated.to(device)
    
        prob_interpolated = D(interpolated) # Calculate Probability of Interpolated Examples
        interpolated.requires_grad_(True)
    
    
        gradients = torch.autograd.grad(outputs = prob_interpolated, 
                                    inputs = interpolated,
                                    grad_outputs = torch.ones(prob_interpolated.size()).to(device), 
                                    create_graph = True,
                                    retain_graph = True,
                                    allow_unused=True)[0] # I think this is the problem
    
        grad_penalty = ((gradients.norm(2,dim=1)-1)**2).mean()*lambda_term 
      
    return grad_penalty

And:

    for g_iter in range(generator_iters):
        
        print('----------G Iter-{}----------'.format(g_iter+1))
        
        for p in D.parameters():
            p.requires_grad = True # This is by Default
            
        d_loss_real = 0
        d_loss_fake = 0
        Wasserstein_D = 0
    
        for d_iter in range(critic_iter):
            D.zero_grad()
                
            images = data.__next__()
            if images.size()[0] != batch_size:
                continue
            
            # Train Discriminator
            # Real Images
            images = images.to(device)
            z = torch.randn(batch_size, 100, 1, 1).to(device)
            d_loss_real = D(images)
            d_loss_real = d_loss_real.mean(0).view(1)
            d_loss_real.backward(mone)
            
            # Fake Images
            fake_images = G(z)
            d_loss_fake = D(fake_images)
            d_loss_fake = d_loss_fake.mean(0).view(1)
            d_loss_fake.backward(one)
            
            # Calculate Penalty
            gradient_penalty = calculate_gradient_penalty(images.data, fake_images.data)
            gradient_penalty.backward()
            
            # Total Loss
            d_loss = d_loss_fake - d_loss_real + gradient_penalty
            Wasserstein_D = d_loss_real - d_loss_fake
            d_optimizer.step()
            print(f'D Iter:{d_iter+1}/{critic_iter} Loss:{d_loss.detach().cpu().numpy()}')
            
            time.sleep(0.1)
            d_progress.append(d_loss) # Store Loss
            d_fake_progress.append(d_loss_fake)
            d_real_progress.append(d_loss_real)
            penalty.append(gradient_penalty)
        
        # Generator Updata
        for p in D.parameters():
            p.requires_grad = False  # Avoid Computation
        
        # Train Generator
        # Compute with Fake
        G.zero_grad()
        z = torch.randn(batch_size, 100, 1, 1).to(device)
        fake_images = G(z)
        g_loss = D(fake_images)
        g_loss = g_loss.mean().mean(0).view(1)
        g_loss.backward(one)
        # g_cost = -g_loss
        g_optimizer.step()
        print(f'G Iter:{g_iter+1}/{generator_iters} Loss:{g_loss.detach().cpu().numpy()}')
            
        g_progress.append(g_loss) # Store Loss    

Version:

    PyTorch version: 1.8.0
    CUDA used to build PyTorch: 11.1
    OS: Ubuntu 18.04.5 LTS (x86_64)
    GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
    Libc version: glibc-2.27
    Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
    Python platform: Linux-4.15.0-55-generic-x86_64-with-glibc2.10
    CUDA runtime version: 11.1.105
    Nvidia driver version: 418.67
    
    cuDNN version: Probably one of the following:
    /usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
    /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
    /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
    /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
    /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
    /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
    /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
    
    Versions of relevant libraries:
    [pip3] numpy==1.19.2
    [pip3] pytorchtools==0.0.2
    [pip3] torch==1.8.0
    [pip3] torchelastic==0.2.2
    [pip3] torchfile==0.1.0
    [pip3] torchsummary==1.5.1
    [pip3] torchtext==0.9.0
    [pip3] torchvision==0.9.0
    [pip3] torchviz==0.0.2
    [conda] blas                      1.0                         mkl  
    [conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
    [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
    [conda] mkl                       2020.2                      256  
    [conda] mkl-service               2.3.0            py38he904b0f_0  
    [conda] mkl_fft                   1.3.0            py38h54f3939_0  
    [conda] mkl_random                1.1.1            py38h0573a6f_0  
    [conda] numpy                     1.19.2           py38h54aff64_0  
    [conda] numpy-base                1.19.2           py38hfa32c7d_0  
    [conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
    [conda] pytorchtools              0.0.2                    pypi_0    pypi
    [conda] torchelastic              0.2.2                    pypi_0    pypi
    [conda] torchfile                 0.1.0                    pypi_0    pypi
    [conda] torchsummary              1.5.1                    pypi_0    pypi
    [conda] torchtext                 0.9.0                      py38    pytorch
    [conda] torchvision               0.9.0                py38_cu111    pytorch
    [conda] torchviz                  0.0.2                    pypi_0    pypi

Should you have any suggestions, please let me know, thanks a lot!

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by mrshenli** [comment]
Hey @NUS-Tim, how did you reach the conclusion that there is a memory leak? And have you tried the suggestion below:

> One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

**Comment by NUS-Tim** [comment]
@mrshenli  Oppps, I paste the wrong error trace. Sorry about that, I will modify it.

**Comment by albanD** [comment]
Hi,

The question remains, why do you think this is a memory leak? And not just that the network is too big to fit in memory?

**Comment by NUS-Tim** [comment]
@albanD Actually, after every epoch, the memory increase...... until run out, however, I had already found where the problem is, .item() should be added, so the problem will be closed.
