### ISSUE TITLE
Replace usages of c10::str with fmt::format in distributed

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#64604]
## 🐛 Bug

As per the discussion in https://github.com/pytorch/pytorch/pull/64241, we would prefer to use `fmt` library (specifically `fmt::format`) to format strings/error messages instead of c10::str. However the `fmt` library is currently only linked to libtorch_python sources, see the PR that added it: https://github.com/pytorch/pytorch/pull/64241. 

To use `fmt::format` we would probably need to link fmt against libtorch, and then we can update the callsites introduced in `ProcessGroupNCCL` and `NCCLUtils`  in the above PR.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by andreigh** [comment]
I can work on this easy refactoring, will send a PR soon

**Comment by andreigh** [comment]
What's the correct way to link fmt::format to libtorch ?
Is this acceptable ?

target_link_libraries(torch_cuda PRIVATE fmt::fmt-header-only) in caffe2/CMakeFiles ?

Thank you !

**Comment by andreigh** [comment]
@rohan-varma can you please take a look at #107268 ? Thank you !
