### ISSUE TITLE
Reuse tensors from state_dict in load_state_dict

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#64601]
## 🚀 Feature

Provide an option for "reusing" tensors passed into `load_state_dict()` as module parameters. This would help reduce memory usage when loading a module from a state_dict.

## Motivation

Currently, loading a model in the canonical way requires 2x the memory of the parameters: one set of parameters within the model and one set of parameters within the state_dict. This can be a problem for models that are too large for two copies to fit within memory. Example:
```python
import torch

# Loads one set of parameters into memory.
m = MyModule()

# Loads a second set of parameters into memory.
state_dict = torch.load('foo.pt')

m.load_state_dict(state_dict)
```

There should be an officially-supported way to load a module with only one set of parameters in memory at once.

## Pitch

One way to avoid the extra copy of the parameters is to instantiate the module with `device='meta'` so as not to allocate any storage.
```python
import torch

m = MyModule(device='meta')
state_dict = torch.load('foo.pt')
m.load_state_dict(state_dict)

# Problem: module parameters are still meta tensors; loading didn't work.
```

However, this currently doesn't work because `load_state_dict()` copies data into  the module parameters when loading; the module's parameters will still be on the meta device after the call to `load_state_dict()`.

One way to address this is to implement a flag that "reuses" the state_dict tensors passed in to `load_state_dict()`. With this set, the underlying data for module parameters will be swapped out to reference the same memory as the state_dict tensors. **Note that this would also require `set_data()` to be implemented for meta tensors, allowing them to be converted to non-meta tensors.**

Thus, only one copy of the module parameters needs to exist in memory for the module to be loaded. Also, since the parameters remain the same objects, optimizers that reference them will still work.
```python
import torch

m = MyModule(device='meta')
optimizer = torch.optim.SGD(m.parameters(), lr=0.01)

state_dict = torch.load('foo.pt')
m.load_state_dict(state_dict, reuse_tensors=True)

# Module parameters now reference the same data as state_dict tensors.
# The optimizer defined above will still correctly operate on the
# module's parameters.
```

## Alternatives

* Implement incremental module loading to avoid needing two full copies of the parameter sets in memory at once (#64327).
* Do nothing and continue to require users to write their own loading logic to sidestep this issue.

cc @VitalyFedyunin @ngimel @heitorschueroff @albanD @mruberry @jbschlosser @walterddr

**Comment by stas00** [comment]
That's a great summary, @jbschlosser!

Plus, in the above code samples, we need to handle weights that don't come from `state_dict` and are generated on the fly.

Currently, to solve this and avoid a multitude of edge cases, I'm trying to do it on tensor level:


https://github.com/huggingface/transformers/blob/478a90b6224cf175743221132c4c9e11ff0897f9/src/transformers/modeling_utils.py#L1374

So basically, I switch to meta only the keys I know will come in the state dict, which requires loading state_dict twice, the first time only saving which keys will be swapped in:

https://github.com/huggingface/transformers/blob/478a90b6224cf175743221132c4c9e11ff0897f9/src/transformers/modeling_utils.py#L1319

**Comment by stas00** [comment]
here is a related proposal: https://github.com/pytorch/pytorch/pull/63601

**Comment by stas00** [comment]
So here is my current hack that works by switching params/buffers that are going to be replaced by state_dict's data to the meta device:

```
        # pre-load
        state_dict = torch.load(resolved_archive_file, map_location="cpu")
        
        # save the keys
        loaded_state_dict_keys = [k for k in state_dict.keys()]
        del state_dict  # free CPU memory - will reload again later

        # dematerialize param storage for keys that are going to be replaced by state_dict, by
        # putting those on the meta device
        for k in loaded_state_dict_keys:
            split_name = k.split(".")
            # print(k)
            m = model
            matched = True
            while len(split_name) > 1:
                if hasattr(m, split_name[0]):
                    m = getattr(m, split_name[0])
                    del split_name[0]
                else:
                    matched = False
                    break
            if matched:
                # selectively switch to the meta device only those params/buffers that will
                # be next replaced from state_dict. This a complex way to do p.to_("meta")
                # since we have no in-place to_ for tensors.
                to_meta_objs = []
                for n, p in m.named_parameters():
                    if n == split_name[0]:
                        to_meta_objs.append(p.data_ptr())

                def selective_to_meta(p):
                    if p.data_ptr() in to_meta_objs:
                        return p.to("meta")
                    else:
                        return p

                m._apply(selective_to_meta)

        # only now can load state_dict
        state_dict = torch.load(resolved_archive_file, map_location="cpu")

        # materialize float sd keys one by one on CPU
        for k in loaded_state_dict_keys:
            split_name = k.split(".")
            m = model
            matched = True
            while len(split_name) > 1:
                if hasattr(m, split_name[0]):
                    m = getattr(m, split_name[0])
                    del split_name[0]
                else:
                    matched = False
                    break
            if matched:
                persistent_buffers = {k: v for k, v in m._buffers.items() if k not in m._non_persistent_buffers_set}
                if split_name[0] in persistent_buffers:
                    m._buffers[split_name[0]] = state_dict[k]
                else:
                    setattr(m, split_name[0], torch.nn.Parameter(state_dict[k]))

        del state_dict

```

this is part of this tentative PR: https://github.com/huggingface/transformers/pull/13466

Of course, it won't have been needed if state_dict were to be granular

**Comment by dzhulgakov** [comment]
Just a random idea: another alternative approach (which is probably harder to implement) is to make `torch.load` variant that returns "tensor promise" instead of the real tensor. Tensor promise refers to the original file and the storage within it. Then only `self.param.set_(loaded_tensor_promise)` would trigger the loading of the data from the file. The hard part is adding new tensor type (can be done with python dispatch I guess) and managing the lifetime of "reader" for the source file (can be a shared_ptr pointed by all tensor promises collectively)
