### ISSUE TITLE
GHA failures require scanning the log

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#64614]
When a test fails on a GHA job engineers have to scan through the log to find the failure. This can be difficult and time consuming. It'd be nicer if failures were collected (like they were on CircleCI). 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra what's the right label for this?

cc @ngimel and @suo who I think also struggled with this recently

**Comment by seemethere** [comment]
So I guess the question is, do we need the web UI that CircleCI provides or are we fine with reading logs that provide a CLI rendered version of the test results.

https://github.com/pytorch/pytorch/pull/64937 should resolve rendering results on the CLI (which should give us structured output logs), but as far as web UI goes we do have the rendering available through hud.pytorch.org (cc @driazati)

**Comment by seemethere** [comment]
Double checked with @mruberry and looks like https://github.com/pytorch/pytorch/pull/64937 resolves this so going to go ahead close, feel free to re-open if necessary
