### ISSUE TITLE
[Beta] FSDP checkpoint APIs

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64625]
Usually checkpoint a model happens on root FSDP instance, there are two ways to checkpoint a model usually: 
1. call state_dict() to checkpoint/save full original params in rank 0 if models can fit into one rank's memory, it is slow as it requires to all gather shards before checkpointing; then call load_state_dict() to load full original params into each rank, and shard it
2. call local_state_dict() to checkpoint/save local shard in each rank in parallel, right now it checkpoints a flat_parameter with local shard data;  then call load_local_state_dict() to load the local shard into each rank

once https://github.com/pytorch/pytorch/issues/64464 is done, the local_state_dict() will checkpoint original parameters with local shard data of a flat tensor, each parameter could be pointed to a full tensor or partial tensor or empty;  we need to add unit tests to make sure this works as expected once https://github.com/pytorch/pytorch/issues/64464 is done. 

### Reshard checkpoint APIs
In distributed inference or fine tuning cases, the world size may change, the local state dicts can not be simply loaded by calling load_local_state_dict(). 

We need to provide APIs to merge shards into original full params: 
1. if these original full params can fit into memory, each rank can create a original model and load these original full params, then wrap the model as FSDP instances to shard layers
2. if these original full params can not fit into memory, each rank possibly needs to create a original model on meta device, we need an API to load these full params layer by layer while materializing these layers, and then shard these layers  

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by awgu** [comment]
I am closing this since we have a good sense of what our checkpointing APIs should look like (for both model and optimizer).
