### ISSUE TITLE
How to set batch_size when using DataParallel mode in pytorch?

### ISSUE THREAD

**Issue by melspectrum007** [pytorch/pytorch#6462]
I can't find document about the batch_size setting and DataParallel mode.
so How to set batch_size when using DataParallel mode in pytorch? Is it similiar with Keras?
Thanks

In Keras, the parallel_model( like DataParallel mode in pytorch), which document is very clear I think:
-------------------------------------------Keras document beginging------------------------------------------
E.g. if your batch_size is 64 and you use gpus=2, then we will divide the input into 2 sub-batches of 32 samples, process each sub-batch on one GPU, then return the full batch of 64 processed samples

This `fit` call will be distributed on 8 GPUs.
 Since the batch size is 256, each GPU will process 32 samples.

parallel_model.fit(x, y, epochs=20, batch_size=256)
-------------------------------------------Keras document ended------------------------------------------

**Comment by apaszke** [comment]
You don't set the batch size in any way when the module is constructed. It will automatically handle all possible sizes you'll pass at run time.
