### ISSUE TITLE
[Prototype] Support multiple activation checkpoints in FSDP

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64633]
Right now FairScale FSDP supports multiple activation checkpoints by making changes in FairScale checkpoint_wrapper module. We either needs to import checkpoint_wrapper changes into PyTorch, or test with new version of PyTorch checkpoint module prototype https://github.com/pytorch/pytorch/pull/62964 and push that prototype into production

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
Landed now
