### ISSUE TITLE
[Beta] Remove all the '.data' usage in FSDP repo

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64630]
tensor.data is used in many places of FSDP codes, we need to remove them as '.data' is not safe to use and will be deprecated soon

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by awgu** [comment]
Yea... this is probably not going to happen anytime soon 😆 

I think the conclusion is that unless Core team provides an alternative to manipulate a Python `Tensor` variable's storage in a safe way, then we will have to continue to rely on `.data` for FSDP.
