### ISSUE TITLE
Anaconda3, Ubuntu 16.04 Python 3.6 Caffe2 installation issue

### ISSUE THREAD

**Issue by shirishr** [pytorch/pytorch#6464]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: **Caffe2**
- OS:**Ubuntu 16.04**
- PyTorch version:
- How you installed PyTorch (conda, pip, source): PyTorch not installed in this environment at this time
- Python version:**3.6**
- CUDA/cuDNN version:**9.0/7.0**
- GPU models and configuration: **GeForce 1050Ti**
- GCC version (if compiling from source):**5.4**
- CMake version:**3.9.0-rc5**
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

Native Python in Ubuntu 16.04 is Python2 (2.7) and Python3 (3.5)

1. Anaconda3 installed (Version4.5.0)
2. Created an environment **conda create --name caffe36 python==3.6**
3. source activate caffe36
4. conda install -c caffe2 caffe2-cuda9.0-cudnn7

Now **python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"**

result is **Failure**

More details from CLI:
CRITICAL:root:Cannot load caffe2.python. Error: No module named 'caffe2.python.caffe2_pybind11_state'

I see that **caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so** and also **caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so** exists in ~/anaconda3/envs/caffe36/lib/python3.6/site-packages/caffe2-0.8.2-py3.6-linux-x86_64.egg/caffe2/python

What do I need to do so that caffe2.python gets loaded (module 'caffe2.python.caffe2_pybind11_state' is found)

Some guidance is needed in documentation

**Update**
If I add 

1. import sys
2. sys.path.append('/home/sam/anaconda3/envs/caffe36/lib/python3.6/site-packages/caffe2-0.8.2-py3.6-linux-x86_64.egg/caffe2/python')
3. from caffe2.python import core

I get an error 

CRITICAL:root:Cannot load caffe2.python. Error: /home/sam/anaconda3/envs/caffe36/lib/python3.6/site-packages/caffe2-0.8.2-py3.6-linux-x86_64.egg/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6google15SetUsageMessageERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by shirishr** [comment]
@pjh5 
I am a unsure if I installed caffe2 by using 

**conda install -c caffe2 caffe2-cuda9.0-cudnn7**

or by

1. git clone --recursive https://github.com/pytorch/pytorch.git 
2. cd pytorch
3. python setup_caffe2.py install

I think it was the second method because when conda list caffe2 shows build channel as <pip>

# Name                    Version                   Build  Channel
caffe2                    0.8.2                     <pip>

**Comment by pjh5** [comment]
It looks like you installed with setup_caffe2.py, as setuptools (the Python package behind setup.py scripts) is what installs .egg files.

Could you try `pip uninstall caffe2` and `conda install -c caffe2 caffe2-cuda9.0-cudnn7` ? This way should be much faster too.

If the pip uninstall caffe2 doesn't seem to work, then you can manually uninstall by deleting every file and folder under /home/sam/anaconda3/envs/caffe36/ that has 'caffe' or 'caffe2' in the name.

**Comment by shirishr** [comment]
**pip uninstall succesful**

pip uninstall caffe2
Uninstalling caffe2-0.8.2:
  /home/sam/anaconda3/envs/caffe36/lib/python3.6/site-packages/caffe2-0.8.2-py3.6-linux-x86_64.egg
Proceed (y/n)? y
  Successfully uninstalled caffe2-0.8.2

**conda install -c caffe2 caffe2-cuda9.0-cudnn7 successfull**

It downgraded opencv from version 3.4.1 to 3.3.1 though

result of **python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"**
is **Failure**

result of **python -c 'from caffe2 import core' 2>/dev/null && echo "Success" || echo "Failure"**
is **Success**
result of **python -c 'from caffe2.python import workspace' 2>/dev/null && echo "Success" || echo "Failure"**
is **Failure**

result of **python -c 'from caffe2 import workspace' 2>/dev/null && echo "Success" || echo "Failure"**
is **Failure**

opening python cli and following some basic commands from the tutorial [notebook](https://github.com/caffe2/tutorials/blob/master/Basics.ipynb) as:
>>> from caffe2.python import core, workspace

which causes error:
WARNING:root:This caffe2 python run **does not have GPU support**. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: /home/sam/anaconda3/envs/caffe36/lib/python3.6/site-packages/caffe2/python/../../../../libcaffe2.so: undefined symbol: _ZN6google15SetUsageMessageERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Dunno what I should do next

**Comment by pjh5** [comment]
That error message is https://github.com/caffe2/caffe2/issues/1980 , but you shouldn't be getting it any more. The output of `gcc --version` is 5.4 ?

When you run `conda list` are any of these packages from 'conda-forge'? That would cause this problem. If your gcc version is 5.4 or higher then you should not use libraries from conda-forge.

**Comment by shirishr** [comment]
@pjh5 

output of gcc --version is indeed 5.4.0:

**gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609**

I do have several packages that are from conda-forge :-(
conda list shows:

# packages in environment at /home/sam/anaconda3/envs/caffe36:
#
# Name                    Version                   Build  Channel
attrs                     17.4.0                    <pip>
blas                      1.1                    openblas    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.1.18                     0    conda-forge
caffe2-cuda9.0-cudnn7     0.8.dev          py36h97851c3_0    caffe2
cairo                     1.14.10                       0    conda-forge
certifi                   2018.1.18                py36_0    conda-forge
chardet                   3.0.4                     <pip>
coverage                  4.5.1                     <pip>
dbus                      1.10.22                       0    conda-forge
expat                     2.2.5                         0    conda-forge
ffmpeg                    3.4.2                         0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
future                    0.16.0                   py36_0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
gflags                    2.2.1                         0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
glog                      0.3.5                         0    conda-forge
gmp                       6.1.2                         0    conda-forge
gnutls                    3.5.17                        0    conda-forge
graphite2                 1.3.11                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.1                        2    conda-forge
hypothesis                3.55.1                    <pip>
icu                       58.2                          0    conda-forge
idna                      2.6                       <pip>
jasper                    1.900.1                       4    conda-forge
jpeg                      9b                            2    conda-forge
leveldb                   1.20                 hf484d3e_1  
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libiconv                  1.15                          0    conda-forge
libidn11                  1.33                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libprotobuf               3.5.2                         0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                         0    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
lmdb                      0.9.21                        0    conda-forge
ncurses                   5.9                          10    conda-forge
nettle                    3.3                           0    conda-forge
numpy                     1.14.2          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        7    conda-forge
opencv                    3.3.1            py36h0a11808_0  
openssl                   1.0.2n                        0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        1    conda-forge
protobuf                  3.5.2                    py36_0    conda-forge
protobuf                  3.5.2.post1               <pip>
python                    3.6.5                         1    conda-forge
qt                        5.6.2                         7    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.18.4                    <pip>
scipy                     1.0.1                     <pip>
setuptools                39.0.1                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
snappy                    1.1.7                         1    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
urllib3                   1.22                      <pip>
wheel                     0.31.0                   py36_0    conda-forge
x264                      20131217                      3    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

**Comment by shirishr** [comment]
@pjh5
Should I remove the environment entirely and start afresh?
Thank you for your help

**Comment by pjh5** [comment]
@shirishr can you make a brand new environment and install Caffe2 there? It shouldn't install any conda-forge packages. Also note that Anaconda will use libraries from your "root" environment (the default conda env when no other env is activated) if it doesn't find them in the current env, so it's best to keep your root env clean and do all work in to envs

**Comment by shirishr** [comment]
I think at some point my ~/.condarc

had 

channels:
 - conda-forge 

So that is how stuff got added

**Comment by shirishr** [comment]
I think I will close this now and look for your help later if I get into similar trouble

**Comment by Marcovaldong** [comment]
@pjh5 Why can not use packages from conda-forge? I am installing caffe2 on a server without Internet. I have to download every package used and I can not find useful packages from other uploaders.

**Comment by pjh5** [comment]
@Marcovaldong please read https://github.com/caffe2/caffe2/issues/1980 . It is because default conda channels use gcc 7.2, conda-forge uses gcc 4.8.5 . If your system gcc is < 5 then use conda-forge, otherwise you shouldn't.
