### ISSUE TITLE
[Beta] Sporadic illegal memory access in FSDP when flatten_parameters = True

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64662]
see issue https://github.com/facebookresearch/fairscale/issues/689

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by awgu** [comment]
Closing this since the issue is stale.
