### ISSUE TITLE
[Better Engineering] Define finer grain TrainingState in FSDP

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64674]
It would be nice to have clear and finer state transition be explicit like:  zero_grad -> fwd -> bwd -> optionally accum grad by repeating fwd/bwd -> stepping -> loop back to zero_grad

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by awgu** [comment]
I think that adding an additional `zero_grad` state may not be high priority. Nonetheless, I am closing this since we already have plans to revamp `TrainingState`.
