### ISSUE TITLE
[Efficiency] Support dividing the `flat_parameter` into smaller ones, and only allgather individual smaller ones on-demand

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64686]
As commented by @mrshenli, need more discussions about this though

Support dividing the `flat_parameter` into smaller ones, and only all_gather individual smaller ones on-demand (this should help save peak memory consumption). https://github.com/pytorch/pytorch/pull/63881#discussion_r703969964
https://github.com/pytorch/pytorch/blob/5f0d937b4da76ec8a66728eb77c90a7eb5a849fa/torch/distributed/_fsdp/fully_sharded_data_parallel.py#L294-L303

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by awgu** [comment]
I am not clear on how the `flat_param` memory layout would look like to support this.
