### ISSUE TITLE
[Possible Bug] Forcing 3D attn_mask to have wrong shape in MultiHeadAttention

### ISSUE THREAD

**Issue by Fed03** [pytorch/pytorch#64706]
Hi,
As you can see in the following
https://github.com/pytorch/pytorch/blob/4533e76e7c3df68697a526e2827d661754ab3326/torch/nn/functional.py#L5009-L5020
when feeding a 3D attn_mask, the expected shape is (bsz * num_heads, tgt_len, src_len) and not simply (bsz, tgt_len, src_len).
Can I ask why?

It seems to me that we have a different way to treat 2D and 3D masks: since the former gets a new leading dimension meaning the same mask will be used for every batch, I would expected a 3D mask to have a leading dimension equal to the batch_size, regardless of heads number.

It is possible that I don't see the real meaning behind this behavior...

cc @jbschlosser @bhosmer @cpuhrsch

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.

**Comment by daspartho** [comment]
any update on this? @Fed03
