### ISSUE TITLE
[Caffe2] ONNX prepare error

### ISSUE THREAD

**Issue by wesleyw72** [pytorch/pytorch#6471]
I am getting an error when running: caffe2.python.onnx.backend.prepare(model)

The error is:
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    prepared_backend = caffe2.python.onnx.backend.prepare(model)
  File "/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/backend.py", line 776, in prepare
    pred_model = cls.optimize_onnx(model, predict=True)
  File "/anaconda2/lib/python2.7/site-packages/caffe2/python/onnx/backend.py", line 733, in optimize_onnx
    out = onnx.optimizer.optimize(input, passes)
TypeError: optimize(): incompatible function arguments. The following argument types are supported:
    1. (arg0: str, arg1: List[unicode]) -> str

The ONNX file has been exported from PyTorch. Strangely it works fine if using onnx-caffe2 repo.
I have tried both the Conda version of Caffe2 and building from source.
Python 2.7

My onnx file: https://drive.google.com/file/d/1L8pVfZ6ZEExvtG5aZTPpbo_st7opNQZT/view?usp=sharing

**Comment by pjh5** [comment]
When you mean 'Conda version' do you mean `conda install -c caffe2 caffe2` or `scripts/build_anaconda.sh` ?

Whenever I see "unicode" in a Python error string, I immediately think of a Python 2-3 mismatch. Does `conda install -c caffe2 caffe2` in a Python 3.6 environment work?

**Comment by wesleyw72** [comment]
Thanks all. That worked, I built onnx and Caffe2 from both repos and am no longer experiencing the error.
