### ISSUE TITLE
Add custom quantization for saved for backwards tensors

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [pytorch/pytorch#64729]
## 🚀 Feature
To reduce training memory, we want to quantize the saved tensors. Instead of storing the original tensor for backward propagation, we want to store a quantized tensor. We proposed an approach in our previous project https://github.com/ucbrise/actnn, which proves to converge after quantization/dequantization and can reduce the activation memory by 12X.

## Motivation

Our previous implementation is not general. We need to add a wrapper for each operator, and currently, we only support operators in convolution neural networks. We think it's better to do the work within PyTorch, which will make the method more general and can be applied to a wider range of networks.

## Pitch
Our previous project provides two high-level APIs in python
(1) quantize(tensor, scheme)
https://github.com/ucbrise/actnn/blob/15ecfc6f25396166c222c5003d5f63e256336d28/actnn/actnn/ops.py#L99
(2) dequantize(quantized_tensor, original tensor shape)
https://github.com/ucbrise/actnn/blob/15ecfc6f25396166c222c5003d5f63e256336d28/actnn/actnn/ops.py#L121

We plan to change the saved variable constructor and the unpack function. Therefore, whenever creating a new saved variable, we call the quantize API and save the quantized tensor. Whenever we try to get back the saved tensor (unpack), we dequantize it.

```
SavedVariable(input) {
      quantized_data_ = quantize(input) // quantize is a python function, so actually here we call into the python code
         // quantized_data_ will also be a PyObject
}

SavedVariable::unpack() {
    variable = dequantize(quantized_data_) // dequantize is also a python function
             // variable is a PyTorch Variable
}
```

We have a simple and hacky implementation now
https://github.com/LiuXiaoxuanPKU/pytorch/blob/847d50d3bc3d7e95dcab4d4f4f05bfe0168e13ae/torch/csrc/autograd/saved_variable.cpp#L149

## Additional context

Our current implementation works for simple networks (VGG16/19, ResNet class). However, when we try it on more complex network structures, such as StyleGAN, it will throw errors, saying the quantized_data_ is not live (We suspect one node is backward twice but how can that happen??). We are not sure if our current way of adding this feature is correct, any comments/ideas are really appreciated.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by LiuXiaoxuanPKU** [comment]
@ezyang

**Comment by albanD** [comment]
Hi,

We actually added very recently special hooks in there that will allow you to implement that very easily.
See the (soon to be published) tutorial about them: https://deploy-preview-1655--pytorch-tutorials-preview.netlify.app/intermediate/autograd_saved_tensors_hooks_tutorial?utm_source=github&utm_campaign=bot_dp

But you should be able to implement this as:
```python
def pack_hook(x):
    return quantize(x)

# You can actually return whatever you want from the pack_hook and it will
# be passed to this function.
def unpack_hook(quant_x):
    return dequantize(quant_x)

with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    # Every SavedVariable in this context will use the above hooks
    your_model(some_input)
```

Does that work for you?

**Comment by LiuXiaoxuanPKU** [comment]
Hi, thanks for pointing it out!
I tried it on both simple and complicated networks. Interestingly, the results are the same as my hacky implementation. It works on simple networks (ResNet). But if I apply it to GAN, it throws a memory access error.  
CUDA error: illegal memory access was encountered.

Traceback looks like this (may not be very helpful)
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/actnn/bin/stylegan2_pytorch", line 33, in <module>
    sys.exit(load_entry_point('stylegan2-pytorch', 'console_scripts', 'stylegan2_pytorch')())
  File "/home/ubuntu/stylegan2-pytorch/stylegan2_pytorch/cli.py", line 190, in main
    fire.Fire(train_from_folder)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ubuntu/stylegan2-pytorch/stylegan2_pytorch/cli.py", line 181, in train_from_folder
    run_training(0, 1, model_args, data, load_from, new, num_train_steps, name, seed)
  File "/home/ubuntu/stylegan2-pytorch/stylegan2_pytorch/cli.py", line 60, in run_training
    retry_call(model.train, tries=3, exceptions=NanException)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/ubuntu/stylegan2-pytorch/stylegan2_pytorch/stylegan2_pytorch.py", line 1049, in train
    fake_output, fake_q_loss = D_aug(generated_images.clone().detach(), detach = True, **aug_kwargs)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/stylegan2-pytorch/stylegan2_pytorch/stylegan2_pytorch.py", line 407, in forward
    return self.D(images)
  File "/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/stylegan2-pytorch/stylegan2_pytorch/stylegan2_pytorch.py", line 672, in forward
    quantize_loss = torch.zeros(1).to(x)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by albanD** [comment]
Is that the error while running with `CUDA_LAUNCH_BLOCKING=1` as suggested in the error message?

**Comment by LiuXiaoxuanPKU** [comment]
Hi, thanks for the reply! After setting CUDA_LAUNCH_BLOCKING=1 and debugging my own quantization code, it can run now. But I there are warnings when I train the stylegan2:

/home/ubuntu/miniconda3/envs/actnn/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py:56: UserWarning: An output with one or more elements was resized since it had shape [245760], which does not match the required output shape [5, 3, 128, 128].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  return torch.stack(batch, 0, out=out)

It seems the warning is triggered here
https://github.com/lucidrains/stylegan2-pytorch/blob/1a789d186b9697571bd6bbfa8bb1b9735bb42a0c/stylegan2_pytorch/stylegan2_pytorch.py#L1035

The warning exits even if I turn off the pack/unpack hook. I guess it has something to do with the PyTorch version? Do I need to worry about the warning?

**Comment by ezyang** [comment]
Yeah it looks like some sort of stylegan2 problem. If you're getting reasonable results I think you can ignore it.

Sounds like you've gotten Alban's new hooks to work, so I'll close this issue.

**Comment by vuhoangminh** [comment]
> Hi,
> 
> We actually added very recently special hooks in there that will allow you to implement that very easily. See the (soon to be published) tutorial about them: https://deploy-preview-1655--pytorch-tutorials-preview.netlify.app/intermediate/autograd_saved_tensors_hooks_tutorial?utm_source=github&utm_campaign=bot_dp
> 
> But you should be able to implement this as:
> 
> ```python
> def pack_hook(x):
>     return quantize(x)
> 
> # You can actually return whatever you want from the pack_hook and it will
> # be passed to this function.
> def unpack_hook(quant_x):
>     return dequantize(quant_x)
> 
> with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
>     # Every SavedVariable in this context will use the above hooks
>     your_model(some_input)
> ```
> 
> Does that work for you?

Hi,

What should I do to force pack_hook pack only variables but not PyTorch module's parameters?

For example, when I do y = nn.Conv2d(32, 32, 3, 1)(x), I expect pack_hook to pack only x but not parameters of Conv2d.

Thank you!

**Comment by albanD** [comment]
Hi,

Depends on what you do but you can check `isinstance(x, Parameter)` ?

**Comment by vuhoangminh** [comment]
> Hi,
> 
> Depends on what you do but you can check `isinstance(x, Parameter)` ?

Hi @albanD, 

Say I want to ignore all convolutional layers' parameters in the following toy example:

```
class Net(nn.Module):
    """
    A silly model.
    """

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(32, 32, 3, 1)
        self.conv2 = nn.Conv2d(32, 32, 3, 1)
        self.conv3 = nn.Conv2d(32, 32, 3, 1)

    def pack_hook(self, x):
        if isinstance(x, Conv's parameters):
            return x, "not_packed"
        else:
            print("Packing")
            return pack(x), "packed"

    def unpack_hook(self, packed):
        x, status = packed
        if status == "not_packed":
            return x
        else:
            print("Unpacking")
            return unpack(x)

    def forward(self, x):
        with torch.autograd.graph.saved_tensors_hooks(
            self.pack_hook, self.unpack_hook
            # pack_hook, unpack_hook
        ):
            x = self.conv1(x)
            x = self.conv2(x)
            x = self.conv3(x)
        # print(x)
        return x
```

My question is: Is there any way to check `if isinstance(x, Conv's parameters):`?

**Comment by soulitzer** [comment]
You could loop through all of convolution's parameters and add them to a set, then check membership in pack_hook

**Comment by vuhoangminh** [comment]
> You could loop through all of convolution's parameters and add them to a set, then check membership in pack_hook

Hi,

Thank you so much. I get it working!

**Comment by LiuXiaoxuanPKU** [comment]
Hi question about the hook trigger order

layer1 --> layer 2 
   |                |
pack1         pack2

**Comment by soulitzer** [comment]
Neither. Saved tensor hooks operate at the tensor level. They trigger when a tensor is saved for backward. Tensors are saved for backward during the forward pass of an op in the autograd kernel. So, the computation of layer1 subsumes that of pack1, and likewise for layer2/pack2. It wouldn't make sense to say whether pack1 runs before or after layer1/layer2 etc.

**Comment by Varal7** [comment]
To expand on soulitzer's answer, it means that if `pack1` is ever called, it will be called during the forward pass of layer1, i.e before you "enter" layer2.

**Comment by LiuXiaoxuanPKU** [comment]
Hi! Thanks for the reply! I am still confused about the order here:

**Comment by LiuXiaoxuanPKU** [comment]
Hi! Thanks for the reply! I am still confused about the order here:
(1) yes, I understand that the computation of `layer1` subsumes that of `pack1`, but is `pack1` a synchronous call? i.e. before we "enter" layer 2, PyTorch already finishes calling `pack1` (if `pack1` includes GPU operations, it has already pushed the kernel launch task to the GPU task queue).
(2) what's the behavior for inplace operator, consider the following example:
```
layer1 ==> inplace layer2 ==> layer3
pack1           pack2          pack3
```
say the output of layer1 is T1, the output of layer 2 is T2
```
layer1 ==>(T1) inplace layer2 ==> (T2) layer3
pack1               pack2              pack3
```
since layer2 is an inplace operator, I imagine T1 and T2 will share the same storage, 
let's say T1, T2 are tensors with one element and T1 = [-1], T2 = [0], (but notice here T1, T2 share the same storage) what will be the input of pack2?
Will pack2 take [-1] as input or [0] as input or both are possible?

Thanks a lot!

**Comment by LiuXiaoxuanPKU** [comment]
@soulitzer @Varal7

**Comment by Varal7** [comment]
Regarding (1) my understanding is that the call of `pack1` will be asynchronous by default, but because devices will execute operations in the order they are queued, `pack1` will be done before we enter `pack2`. cc @albanD 

For (2), it is a common misconception that the input of `layerX` will be used as input to `packX`. That is not always true. Certain operations will save the input (for instance `pow`) but certain operations will save the output (for instance `exp`).
With this in mind, let `x = 2 * torch.ones(1, requires_grad=True)`, and consider four cases:
```python
# 1. out-of-place, saving input
x = 2 * torch.ones(1, requires_grad=True)
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    y = x.pow(2)
# the input of pack is 2  
``` 
```python
# 2. inplace, saving input
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    y = x.pow(2)
# the input of pack is 2  
```

**Comment by Varal7** [comment]
Regarding (1) my understanding is that the call of `pack1` will be asynchronous by default, but because devices will execute operations in the order they are queued, `pack1` will be done before we enter `pack2`. cc @albanD 

For (2), it is a common misconception that the input of `layerX` will be used as input to `packX`. That is not always true. Certain operations will save the input (for instance `pow`) but certain operations will save the output (for instance `exp`).
With this in mind, let `x = 2 * torch.ones(1, requires_grad=True)`, and consider four cases:

```python
# 1. out-of-place, saving input
x = 2 * torch.ones(1, requires_grad=True)
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    y = x.pow(2)
# the input of pack is tensor([2])
``` 

```python
# 2. inplace, saving input
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    x.pow_(2)
# the input of pack is tensor([2])  
``` 

```python
# 3. out-of-place, saving output
x = 2 * torch.ones(1, requires_grad=True)
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    y = x.exp()
# the input of pack is tensor([7.3891]) 
``` 

```python
# 4. inplace, saving output
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    y.exp_()
# the input of pack is tensor([7.3891]) 
```

**Comment by LiuXiaoxuanPKU** [comment]
Thanks for the explanation!
One thing I want to double-check,
As the example you mentioned
```
# 2. inplace, saving input
x = 2 * torch.ones(1, requires_grad=True)
with torch.autograd.graph.saved_tensors_hooks(pack, unpack):
    x.pow_(2)
# the input of pack is tensor([2])
```
even with the asynchronous execution, the save operation will happen before the in-place calculation, 
that is, the inplace will not overwrite the input tensor, therefore 2 is passed to pack instead of 7.3891

I'm just worried the inplace+asynchronous execution will cause some unintentional behavior.
Thanks!

**Comment by Varal7** [comment]
Yes, no need to worry about asynchronous execution. The operations are enqueued synchronously (and dequeued in the order they are enqueued), and PyTorch handles the synchronization across devices when needed, so from our perspective, it is as if everything was synchronous.
