### ISSUE TITLE
 Use libtorch to specify GPU recognition

### ISSUE THREAD

**Issue by zhongqingyang** [pytorch/pytorch#64734]
## To Reproduce

1.I use python model,When I converted the model, after selecting GPU1, I used C++ to call the model and could only forward it on GPU1.
2.When I use GPU0 to load the model of GPU1, an error appears: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
3.When I use GPU1 to load the model of GPU0,Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

Thanks for your help.

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

In your case, make sure to move both the model and inputs to the same GPU device before using them.
