### ISSUE TITLE
can't rebuild with NO_CUDA=1 after clean

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#6474]
I used to be able to do:
```
  python setup.py build_deps develop
  python setup.py clean
  NO_CUDA=1 python setup.py build_deps develop
```

this now fails in THD with:
> In file included from /home/gchanan/local/pytorch9i2/torch/lib/THD/base/data_channels/DataChannelGloo.cpp:3:0:
/home/gchanan/local/pytorch9i2/torch/lib/THD/base/data_channels/GlooCache.hpp: In static member function ‘static thd::GlooCache::key_type thd::gloo_cache::algorithm_spec<(thd::CollectiveType)3u, T>::key(THDGroup, thd::DeviceType, std::size_t, std::size_t, THDReduceOp)’:
/home/gchanan/local/pytorch9i2/torch/lib/THD/base/data_channels/GlooCache.hpp:300:68: error: there are no arguments to ‘THDGetCudaState’ that depend on a template parameter, so a declaration of ‘THDGetCudaState’ must be available [-fpermissive]
       auto cuda_stream = THCState_getCurrentStream(THDGetCudaState());

among other errors.

CC @teng-li @ailzhang

**Comment by gchanan** [comment]
Doing the following seems to have fixed it; I'm not sure which of these is okay for clean to leave around:
`
rm -rf aten/src/ATen/Config.h aten/build/ third_party/build/ third_party/aten/
`

**Comment by anderspapitto** [comment]
so it seems to be resolved - can we close? seems to be just a run-of-the-mill transient build issue when pulling in new code changes.

**Comment by gchanan** [comment]
That seems like a guess.
