### ISSUE TITLE
Support torch.isfinite for ONNX export

### ISSUE THREAD

**Issue by raoul-khour-ts** [pytorch/pytorch#64754]
## 🚀 Feature
Adding isfinite and log10 support.
log10 should be supported with version >= 9 (constrained by log)
isfinite should be supported with version >=10 (constrained by isinf)

## Motivation

Would like to export models more seamlessly.

current solution is to change all torch.log10(x) -> torch.log(x)/torch.log(10) and torch.isfinite(x) -> ~(torch.isnan(x) or torch.isinf(x)).

Hoping to make the exportingmore seemless.

## Pitch

Make exporting log10 and infinite more seamless to onnx

## Alternatives

Everyone will have to rewrite parts of their model when exporting to onnx if they are using log10 or infinite...

cc @BowenBao @neginraoof

**Comment by garymm** [comment]
log10 is covered by https://github.com/pytorch/pytorch/issues/61332. Reducing scope to be about isfinite.
