### ISSUE TITLE
Torchhub core tests are silently broken because of a Github API rate issue

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/pytorch#64760]
While we fixed most of the recent torchhub API rate issues, it looks like some of them remain. The torchhub repo CI is [back to green](https://github.com/pytorch/hub/commits/master) but the torchhub tests here in core are silently failing with a GitHub API rate issue:

Take for example this CI job from yesterday and search for "TestHub" in the "Test Pytorch" tab: https://github.com/pytorch/pytorch/runs/3541268443. There are many failures like:

```
  test_hub_dir (__main__.TestHub) ... ok (0.002s)
  test_list_entrypoints (__main__.TestHub) ... HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
skip (6.077s)
  test_load_commit_from_forked_repo (__main__.TestHub) ... HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
skip (6.074s)
  test_load_from_branch (__main__.TestHub) ... HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
skip (6.077s)
  test_load_from_github (__main__.TestHub) ... HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
skip (6.076s)
  test_load_from_local_dir (__main__.TestHub) ... HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
HTTP Error 403: rate limit exceeded, Retrying in 3 seconds...
skip (6.075s)
```

By default, torchhub relies on the `GITHUB_TOKEN` env variable. @seemethere do you know how to set the GH Action machines with a higher API limit? Or maybe the env variable that GH action sets isn't named `GITHUB_TOKEN`?

CC @malfet 

cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra @nairbv @NicolasHug

**Comment by seemethere** [comment]
You should probably explicitly pass it like:
```
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

As far as rate limits go you probably shouldn't be hitting any: (see [docs](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)
```
When using the built-in GITHUB_TOKEN in GitHub Actions, the rate limit is 1,000 requests per hour per repository. For organizations that belong to a GitHub Enterprise Cloud account, this limit is 15,000 requests per hour per repository.
```
