### ISSUE TITLE
[CI] Add GPU+AVX512 capable runners to the CI config

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#64767]
There are number of operators which are accelerated with AVX512 instructions, which are not checked by CI, but might affect stability and numerical accuracy on number of modern systems.

For example, right now we are not running the test on any of the systems that would return true for the following statement  `cpuinfo_has_x86_avx512bw()
      && cpuinfo_has_x86_avx512vl() && cpuinfo_has_x86_avx512dq`

cc @VitalyFedyunin @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Example of PR that was landed untested: https://github.com/pytorch/pytorch/pull/61891/files#diff-db2b91c51cffd1fba933933ac20de256f5f0ced095890a1a49a17d73037001a2R1127

**Comment by seemethere** [comment]
We have these in GHA so we can close
