### ISSUE TITLE
[RFC] Support native mixed precision training in DDP

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#64770]
It would be nice to support native mixed precision training in DDP without communication hook, the API could be similar to new FSDP API proposed in https://github.com/pytorch/pytorch/issues/64394

// data type is extensible 
class DataType(str, Enum):
   Float32 = "float32"
   Float16 = "float16"
   Bfloat16 = "bfloat16"
   
// Many combinations, it is better to use data class to simplify
// if enabled, default to float16 types 
class MixPrecision:
    InputType: DataType = "float16"
    ParamType: DataType = "float16"
    ComputeType: DataType = "float16"
    BufferType: DataType = "float16"
    ReduceType: DataType = "float16"
    clear_autocast_cache: bool = false

DistributedDataParallel(...., mix_precision: Optional[MixPrecision] = None) 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by rohan-varma** [comment]
This was landed
