### ISSUE TITLE
Feature request: Use LinAlgError instead of raising RuntimeError for linalg operations

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#64785]
## 🚀 Feature
In `torch.linalg` module, instead of raising RuntimeError directly when operations fail due to numerical issues, use `LinAlgError` or `NumericalError`. This is consistent with scipy/numpy linalg module which also raises `LinAlgError`.

## Motivation

This is useful because, in many cases, algorithms already have provisions for dealing with these kind of errors (e.g. adding a jitter in case of cholesky decomposition) or rejecting the sample proposed when running MCMC. This is currently done by catching a more generic RuntimeError and reading the error message to determine whether the exception was due to a numerical issue which is brittle. See for instance https://github.com/pyro-ppl/pyro/blob/dev/pyro/ops/integrator.py#L79, but the error message is outdated as per the latest PyTorch master thereby breaking this code (thanks to @dme65 for reporting this).

## Pitch
Throw `LinAlgError` for all ops in `torch.linalg` when numerical issues are encountered. For backward compatibility, this can inherit from `RuntimeError` so that existing code that catches this should still work. Possibly related - https://github.com/pytorch/pytorch/issues/47608.

cc. @mruberry, @fritzo, @Balandat, @jpchen 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Balandat** [comment]
Note that at least for Cholesky the alternative is to use `torch.linalg.cholesky_ex`, which returns the LAPACK error code (which can then be parsed as needed). The benefit of that is that it's more than 100X faster if there is an error: https://github.com/pytorch/pytorch/issues/34272. 

I also recall there was an issue about having a dedicated "experts" module in which these functions are exposed for people who are comfortable parsing low-level error codes in their packages - can't find that right now though.

**Comment by neerajprad** [comment]
> The benefit of that is that it's more than 100X faster if there is an error: #34272.

Thanks for sharing that thread, that was illuminating! This is worth keeping in mind for all the code that is internal to Pyro/BM. I suppose raising a different error will still be useful since the code that needs to decide on the workaround (e.g. rejecting the sample in MCMC) for the numerical issue might be upstream from the code that actually calls into the cholesky factorization (e.g. a user's model).

**Comment by Lezcano** [comment]
I think that this would be a cool thing to have.
On a side note, recently, in https://github.com/pytorch/pytorch/pull/63864, the errors of the linalg functions have been improved.

**Comment by Balandat** [comment]
Yeah so that improvement is actually what broke a bunch of downstream code since that relied on parsing the error message. That's what prompted this feature request.

**Comment by v0dro** [comment]
I would like to take up this issue. Here's a rough outline of the implementation plan:

1. Make a list of all the operators in torch.linalg that throwing RuntimeError. List those operators here.
2. Create the LinAlgError inherting from RuntimeError along with implementation for some basic operators
   and merge into master.
3. Tackle changes to each of the other operators in separate PRs (or a bunch of operators per PR).

Comments?

**Comment by v0dro** [comment]
List of functions in the linalg namespace that need to be fixed:

-[ ] cholesky
-[ ] cholesky_ex
-[ ] common_notes
-[ ] cond
-[ ] det
-[ ] eig
-[ ] eigh
-[ ] eigvals
-[ ] eigvalsh
-[ ] householder_product
-[ ] inv
-[ ] inv_ex
-[ ] lstsq
-[ ] matmul
-[ ] matrix_exp
-[ ] matrix_norm
-[ ] matrix_power
-[ ] matrix_rank
-[ ] multi_dot
-[ ] norm
-[ ] pinv
-[ ] qr
-[ ] slogdet
-[ ] solve
-[ ] svd
-[ ] svdvals
-[ ] sys
-[ ] tensorinv
-[ ] tensorsolve
-[ ] torch
-[ ] vector_norm

**Comment by Lezcano** [comment]
I think this might be even simpler.

All the error coming from BLAS / LAPACK / etc are parsed in https://github.com/pytorch/pytorch/blob/e795315c638228d4170f3797356c09a70b2ed4cd/aten/src/ATen/native/LinearAlgebraUtils.h#L245-L279

As such, you just need to change the errors there.

The plan looks good to me, this only means that rather than having to do many different PRs, one simple PR updating this function will do.
