### ISSUE TITLE
[feature request] enhance diagonal functionality

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#6479]
# Objective
PyTorch currently does not have a way to take diagonals with respect to arbitrary axes as e.g. `numpy.diagonal` has.
Two immediate use cases are
- Taking the diagonal of a batch of matrices. This is handy e.g. in Gaussian processes, but I have seen this a number of times.
- One of the missing `einsum` features (`torch.einsum('jii->ji', a)`) would benefit from this as well.
# Plan
I propose to do the following (see https://github.com/t-vi/pytorch/tree/diagonal_with_dim for a preliminary implementation)
- Implement `diagonal` natively in ATen instead of referring to TH/THC `diag`.
- Make `diagonal` return a view by adjusting shape, stride, and offset. `diag` copies, but this seems impractical for higher dimensional arrays and also unneeded. *This is not backward compatible.*
- Add two dimension parameters dim1 and dim2.
- Make a diagonal_backward method.
- Include the Tensor method, too.

*Edit*: Based on your feedback, I updated the code to use numpy semantics.

# ~~Limiting numpy compatibility?~~
~~NumPy's implementation has two features that might be worth to differ from:~~
- ~~NumPy's default axes are 0 and 1. I think it is more natural to use -2 and -1 ("batch thinking").~~
- ~~NumPy moves the new axis replacing the two old ones at the end of the tensor. I think it might be more natural to put it into the place of the first axis to be removed. I must admit that this is more a gut feeling than based on hard facts.~~

I would greatly appreciate your input on this, in particular regarding the potential numpy deviations.

**Comment by zou3519** [comment]
cc @SsnL 

Also, we have http://pytorch.org/docs/master/torch.html?highlight=diagonal#torch.diagonal diagonal and diagflat functions in ATen already.

**Comment by zou3519** [comment]
@t-vi the potential numpy deviations are interesting, but I'm not sure if it's worth having confused users.

**Comment by apaszke** [comment]
I also think that if we're going to use a name that's already taken then it's usually a better idea to conform to whatever NumPy is doing, even if it doesn't make too much sense. It's often too confusing otherwise

**Comment by soumith** [comment]
how about we add this as `torch.diagview`, which makes it clear that it's a diagonal view, and we dont have a numpy-equivalent to worry about

**Comment by t-vi** [comment]
Numpy does a view, too...

**Comment by SsnL** [comment]
Yes, NumPy `.diag` returns a view as well, although it is a unwritable view.

**Comment by t-vi** [comment]
Thank you for your feedback, I have updated the code to use `numpy` semantics.
