### ISSUE TITLE
How to get "finfo" in C++ torchlib like that in pytorch

### ISSUE THREAD

**Issue by dbsxdbsx** [pytorch/pytorch#64793]
I am using  C++ torchlib, but I don't know what to do it in c++ like that in pytorch:
```python 
        min_real = torch.finfo(self.logits.dtype).min
# or
        min_real = torch.finfo(self.logits.dtype).tiny

```

cc @yf225 @glaringlee

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by dbsxdbsx** [comment]
@albanD , thanks. I am asking it here:https://discuss.pytorch.org/t/how-to-get-finfo-in-c-torchlib-like-that-in-pytorch/131787
