### ISSUE TITLE
Multiprocessing error with new NVIDIA driver

### ISSUE THREAD

**Issue by agoncharenko1992** [pytorch/pytorch#64800]
## 🐛 Bug
PyTorch Fails to perform dist.all_reduce in PC with 2 GPU. It fails with error:
```
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, invalid usage, NCCL version 2.7.8
ncclInvalidUsage: This usually reflects invalid usage of NCCL library (such as too many async ops, too many collectives at once, mixing streams in a group, etc).
```

## To Reproduce

```python
import os
import time
import sys
import torch
import torch.distributed as dist
import torch.multiprocessing as mp

if __name__ == '__main__':
    print(sys.version)
    print(torch.__version__)
    print(torch.version.cuda)
    print(torch.cuda.nccl.version())

    def run(rank, size):
        print(f'rank: {rank}, size: {size}')
        time.sleep(2.0)
        dist.all_reduce(torch.zeros(1).cuda())
        print(f'dist.all_reduce was executed in: {rank}')

    def init_process(rank, size, fn, backend='nccl'):
        """ Initialize the distributed environment. """
        os.environ['MASTER_ADDR'] = '127.0.0.1'
        os.environ['MASTER_PORT'] = '29500'
        dist.init_process_group(backend, rank=rank, world_size=size)
        fn(rank, size)

    def main():

        world_size = 2
        processes = []
        for rank in range(world_size):
            p = mp.Process(target=init_process, args=(rank, world_size, run))
            p.start()
            processes.append(p)

        for p in processes:
            p.join()

    main()
```

## Expected behavior
It executes without fails.

## Environment
Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-34-generic-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.63.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.9.0+cu111
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] Could not collect
## Additional context

All code executes in virtual environment.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by pritamdamania87** [comment]
The problem is in this line: `dist.all_reduce(torch.zeros(1).cuda())`. Both processes have a tensor on GPU 0 and are trying an allreduce. This is not supported by NCCL. I think changing this line to `dist.all_reduce(torch.zeros(1).cuda(rank))` should work.

**Comment by agoncharenko1992** [comment]
Yep, that's work, thank you.
