### ISSUE TITLE
TypeError when using SparseAdam + GPU

### ISSUE THREAD

**Issue by zhu-y11** [pytorch/pytorch#6481]
- PyTorch 0.3.1
- OS: ubuntu 16.04
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.6.4
- CUDA/cuDNN version: 9.0

When I try to run my [script](https://github.com/zhu-y11/my_wordembs/blob/master/word2vec/pytorch/word2vec.py) (you can clone the repo and directly run the script), using SparseAdam (see in line82) with GPU:
`python3 word2vec.py --train ../../data/de.sent.1e4 --cuda`

I got the error:

> File "word2vec.py", line 158, in <module>
    train(w2v)
  File "word2vec.py", line 96, in train
    total_loss += train_batch(w2v, optimizer, pairs[:w2v.bs], w2v.bs, neg_idxs)
  File "word2vec.py", line 151, in train_batch
    optimizer.step()
  File "/home/yz568/python3/lib/python3.6/site-packages/torch/optim/sparse_adam.py", line 93, in step
    p.data.add_(make_sparse(-step_size * numer.div_(denom)))
  File "/home/yz568/python3/lib/python3.6/site-packages/torch/optim/sparse_adam.py", line 69, in make_sparse
    return constructor(grad_indices, values, size)
TypeError: torch.cuda.sparse.FloatTensor constructor received an invalid combination of arguments - got (torch.cuda.LongTensor, torch.FloatTensor, torch.Size), but expected one of:
 no arguments
 (int size)
 (torch.Size sizes)
 (torch.cuda.LongTensor indices, torch.cuda.FloatTensor values)
 (torch.cuda.LongTensor indices, torch.cuda.FloatTensor values, torch.Size sizes)
      didn't match because some of the arguments have invalid types: (torch.cuda.LongTensor, torch.FloatTensor, torch.Size)
 (int ...)
      didn't match because some of the arguments have invalid types: (torch.cuda.LongTensor, torch.FloatTensor, torch.Size)

But it works well when running with
1. SpaseAdam + CPU
2. SGD + CPU
3. SGD + GPU

**Comment by SsnL** [comment]
Hi @zhu-y11 could you share your data file for me to reproduce this please? Thanks!

**Comment by zhu-y11** [comment]
Hi @SsnL, sorry that I guess I deleted the data from the repo.
Here it is: [de.sent.1e4.txt](https://github.com/pytorch/pytorch/files/2082475/de.sent.1e4.txt).
Feel free to also use other normal text file like [text8](https://cs.fit.edu/~mmahoney/compression/textdata.html).

I tried it on pytorch 0.4, and the same error occurs as well.

Thanks! :)

**Comment by SsnL** [comment]
@zhu-y11 Thank you. I will look into this!. :)

**Comment by albanD** [comment]
Closing this as it uses a very old version of pytorch.
Feel free to re-open if you still see this with the latest version.
