### ISSUE TITLE
torch.clamp fails with half precision args

### ISSUE THREAD

**Issue by jkamalu** [pytorch/pytorch#64840]
## 🐛 Bug

When you use torch.clamp with half precision tensors, the run crashes.

## To Reproduce

1. Open a session in Google Colab
2. Define a half precision tensor and call clamp on this tensor

```
import torch
x = torch.FloatTensor(size=[32, 100]).random_().clamp(max=1) # succeeds
x = torch.FloatTensor(size=[32, 100]).random_().half().float().clamp(max=1) # succeeds
x = torch.FloatTensor(size=[32, 100]).random_().half().clamp(max=1) # fails and causes kernel to restart
x = torch.HalfTensor(size=[32, 100]).random_().clamp(max=1) # fails and causes kernel to restart
```

I expect all assignments to `x` to succeed, with all elements in the tensor clamped to the range [0, 1]

## Environment

Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.11 (default, Jul  3 2021, 18:01:19)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.0.221
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu102
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cu102
[conda] Could not collect

## Additional context

The same problem occurs with torch.clip, torch.clamp_max, etc.

cc @VitalyFedyunin

**Comment by ngimel** [comment]
half precision on cpu is very slow, and not all ops are supported. What is your motivation for using half precision on the cpu?

**Comment by jkamalu** [comment]
I was just prototyping on CPU, but my real use case is on GPU -- I see it works on GPU. It might be nice to include somewhere in the fp16 documentation or error reporting that not all ops are supported. Or at least make it easier to find, since I was not able to find it with ~5-10 minutes of searching.

In any case, not a big issue. Thanks for setting me straight.
