### ISSUE TITLE
Remove Chown Workspace step from GHA

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#64856]
This was a necessary evil from the start--we shouldn't have to chown workspace for our workflows.

Our alternatives
1. Run as the current user in the container  (maybe ec2-user)
2. Use rootless docker since it'd run as user (our current docker runs as root/jenkins so it's problematic)

**Comment by seemethere** [comment]
Probably not that necessary but a nice to have, might not be possible without using rootless docker
