### ISSUE TITLE
einsum on GPU doesn't support 25+ tensor dimensions

### ISSUE THREAD

**Issue by jcmgray** [pytorch/pytorch#64865]
## 🐛 Bug

`torch.einsum` now handles 25+ dimensions (#21412, #56475) fine on the CPU, but seemingly not when the tensors are on the GPU (I have only tested this with cuda).

## To Reproduce

```python
import torch
eq = 'abcdefghijklmnopqrstuvwx,egmpfybhdzAiqcBjaCrntoswxuDv->acijkluvwyzABCD'
x = torch.rand([2] * len('abcdefghijklmnopqrstuvwx'), device='cuda')
y = torch.rand([2] * len('egmpfybhdzAiqcBjaCrntoswxuDv'), device='cuda')
z = torch.einsum(eq, x, y)
# RuntimeError: tensor has too many (>25) dims
```

## Environment

```
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: 11.4.48
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM-80GB
GPU 1: NVIDIA A100-SXM-80GB
GPU 2: NVIDIA A100-SXM-80GB
GPU 3: NVIDIA DGX Display
GPU 4: NVIDIA A100-SXM-80GB

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.0            py39h42c9631_2  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy_extensions           0.4.3            py39h06a4308_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0
```

## Additional context

For context, contractions of this size appear often in quantum simulations.

**Comment by ngimel** [comment]
CUDA tensors in general don't support more than 25 dimensions (you can create high-dimensional tensors, but they will error out on pretty much all operations).

**Comment by jcmgray** [comment]
That doesn't seem to be the case at least for some common operations:
```python
x = torch.rand([2] * 28, device='cuda')
y = torch.rand([2] * 28, device='cuda')
# these all work fine:
z = x + y
z = x * y
z = torch.permute(x, tuple(range(27, -1, -1)))
z = torch.cos(x)
z = torch.tensordot(x, y, 14)
```
maybe it used to be the case and the einsum implementation still guards against it?

**Comment by ngimel** [comment]
YOu are getting lucky in your examples because TensorIterator is able to coalesce the dimensions of the tensors, so that actual tensor to operate on has less than 25 dims. But in your einsum example apparently there really is more than 25. The error is not coming from einsum implementation, it's coming from TensorIterator kernel itself.

**Comment by jcmgray** [comment]
Ah yes I see, this now gives the same error:
```python
# contract every other dimension
z = torch.tensordot(x, y, [tuple(range(0, 28, 2)), tuple(range(0, 28, 2))])
```
Do you know if the 25 hard-coded for some particular reason?

**Comment by ngimel** [comment]
For performance reasons, cuda kernels have to know the maximum number of supported dimensions at compile time, and they create a loop with bounds known at compile time to iterate over maximum dimensions. Increasing maximum would increase kernel size and regress performance. 25 was chosen as a reasonable limit.

**Comment by jcmgray** [comment]
OK, sounds like this will have to worked around then. Thanks for the explanation!
