### ISSUE TITLE
Checking the dimensions of query, key, value in nn.MultiheadAttention

### ISSUE THREAD

**Issue by harshraj22** [pytorch/pytorch#64888]
https://github.com/pytorch/pytorch/blob/30a7c768d77d870c6194f5b6cb0bbd6fe1211069/torch/nn/modules/activation.py#L989

As per documentation, if `batch_first` is set to `True`, the first dimention of shape should be batch_size for key, query, value. But this is not being cross checked. So the code with :

```
query.shape: 1, 1, 640
key.shape: 4, 196, 640
value.shape: 4, 196, 640
```
Returns a tensor, rather than throwing an error. I had this bug in my code and wasted couple of days trying to figure out what part of my model is doing wrong.

I would like to add a pull request, asserting the shape.
@ZolotukhinM @malfet  Please assign me this issue, so that I can add my pull request

![image](https://user-images.githubusercontent.com/46635452/132974079-572a6f8c-f16b-44c7-8dc9-a2490ffdc4e3.png)

cc @jbschlosser @bhosmer @cpuhrsch

**Comment by jbschlosser** [comment]
Hey @harshraj22, what version of PyTorch are you using? Looks like an error is thrown on master:
```python
import torch
from torch import nn

model = nn.MultiheadAttention(640, 1, batch_first=True)
query = torch.randn(1, 1, 640)
key = torch.randn(4, 196, 640)
value = torch.randn(4, 196, 640)
out, weights = model(query, key, value)
print(out.shape, weights.shape)
```
```
Traceback (most recent call last):
  File "transformer_check.py", line 7, in <module>
    out, weights = model(query, key, value)
  File ".../torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../torch/nn/modules/activation.py", line 1003, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File ".../torch/nn/functional.py", line 5046, in multi_head_attention_forward
    k = k.contiguous().view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
RuntimeError: shape '[196, 1, 640]' is invalid for input of size 501760
```

**Comment by harshraj22** [comment]
@jbschlosser oh ! Seems a lot of pull requests have been merged to the master branch since the day I opened this pull request. Anyway, I was using the following version (`pip install torch`)
![image](https://user-images.githubusercontent.com/46635452/133552181-ca18b16b-4945-43b2-acab-dba77e272d3f.png)

**Comment by jbschlosser** [comment]
Closing as resolved.
