### ISSUE TITLE
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'

### ISSUE THREAD

**Issue by JesseWZhang** [pytorch/pytorch#64895]
Hi,when I try to use data distributed parallel to speed up training model, an error occurs: AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'. But it's ok to use data parallel. I have been struggling for this bug for several days, thanks for provides any hints or some informations! 
The output of  python -m torch.utils.collect_env is as followed:
 Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.20200915-gb7590b8
Libc version: glibc-2.17

Python version: 3.7 (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.9.0
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchtext                 0.10.0                   pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi1 

And the all error infomation is as followed:
`
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb1d6035d40>
Traceback (most recent call last):
  File "/root/anaconda3/envs/m4c/lib/python3.7/site-packages/torch-1.9.0-py3.7-linux-x86_64.egg/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/root/anaconda3/envs/m4c/lib/python3.7/site-packages/torch-1.9.0-py3.7-linux-x86_64.egg/torch/utils/data/dataloader.py", line 1295, in _shutdown_workers
    if self._persistent_workers or self._workers_status[worker_id]:
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_workers_status'`

**Comment by ptrblck** [comment]
Could you try to create a minima,l, executable code snippet e.g. by using random data via a `TensorDataset` so that we could try to reproduce this issue?
The `self._worker_status` attribute is created [here](https://github.com/pytorch/pytorch/blob/v1.9.0/torch/utils/data/dataloader.py#L962) and the `_reset` method is called [here](https://github.com/pytorch/pytorch/blob/v1.9.0/torch/utils/data/dataloader.py#L944) so I'm unsure why this attribute is undefined. You could also check, if the code is failing with a previous error somehow interferes with the shutdown.

**Comment by George0726** [comment]
I confront the same issue. It is may result from my personal dataset

**Comment by JesseWZhang** [comment]
Sorry for the late reply.  I fixed the bug by decreasing `num_workers` from 8 to 2. It seems something wrong occurs when creating new threads. And Hope this information may help you.
