### ISSUE TITLE
DataParallel should support multiple inputs

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#649]

**Comment by everwind** [comment]
I implement the data_parallel with two inputs, but it does not work

def data_parallel2(module, input1, input2, device_ids, output_device=None):
    """Evaluates module(input) in parallel across the GPUs given in device_ids.

    This is the functional version of the DataParallel module. 

    Args:   
        module: the module to evaluate in parallel
        input: input to the module
        device_ids: GPU ids on which to replicate module
        output_device: GPU location of the output  Use -1 to indicate the CPU.
            (default: device_ids[0])
    Returns:
        a Variable containing the result of module(input) located on
        output_device
    """
    if not device_ids:
        return module(input1, input2) 

    if output_device is None:
        output_device = device_ids[0]

    replicas = replicate(module, device_ids)
    input1s = scatter(input1, device_ids)
    input2s = scatter(input2, device_ids)
    replicas = replicas[:len(input1s)]
    outputs = parallel_apply2(replicas, input1s, input2s)
    return gather(outputs, output_device)

def parallel_apply2(modules, input1s, input2s):
    assert len(modules) == len(input1s)
    # Fast track
    if len(modules) == 1:
        return (modules[0](input1s[0], input2s[0]),)

    lock = threading.Lock()
    results = {}

    def _worker(module, input1, input2, results, lock):
        var_input1 = input1
        var_input2 = input2
        while not isinstance(var_input1, Variable):
            var_input1 = var_input1[0]
        while not isinstance(var_input2, Variable):
            var_input2 = var_input2[0]
        try:    
            with torch.cuda.device_of(var_input1):
                output = module(input1, input2) 
            with lock:
                results[input1] = output
        except Exception as e:
            with lock:
                results[input1] = e

    threads = [threading.Thread(target=_worker,
                                args=(module, input1, input2, results, lock))
                for module, input1, input2 in zip(modules, input1s, input2s)]

**Comment by soumith** [comment]
wdym by "it does not work"

**Comment by everwind** [comment]
the error info:
Traceback (most recent call last):
  File "translate.py", line 136, in <module>
    data_parallel2(model,batch_enc_inputs, batch_dec_inputs, device_ids=[0, 1] )
  File "/data1/plat/peakzeng/workspace/seq2seq-pytorch-example-master/data_parallel.py", line 115, in data_parallel2
    outputs = parallel_apply2(replicas, input1s, input2s)
  File "/data1/plat/peakzeng/workspace/seq2seq-pytorch-example-master/parallel_apply.py", line 86, in parallel_apply2
    raise output
RuntimeError: equal number of batches expected at /data/plat/peakzeng/solfware/pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:441

**Comment by soumith** [comment]
looks like input1 and input2 don't have equal sizes maybe? either  ways looks like an implementation  bug

**Comment by everwind** [comment]
yes,  input1 and input2 don't have equal sizes,   input1.size =(  input_len1*batch_size*hidden_size)  and  the input2 .size() = (input_len2*batch_size*hidden_size  ) ,  if  i make  input1.size = (batch_size*hidden_size*input_len1)  and  the input2.size()  =  (batch_size*hidden_size*input_len2), can it works ?

**Comment by apaszke** [comment]
Yes, it expects the batch dimension to be first.

**Comment by JianboTang** [comment]
@apaszke the second dimension should be equal?  I encounter this problem while the first dimension is equal

Traceback (most recent call last):
  File "/home/tangjianbo/anaconda2/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/home/tangjianbo/anaconda2/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/home/tangjianbo/anaconda2/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "main_SimpleAoA.py", line 1, in <module>
    import argparse
  File "main_SimpleAoA.py", line 352, in main
    train_loss_epoch, train_prob_epoch = train(epoch)
  File "main_SimpleAoA.py", line 300, in train
    loss, prob = AoA(q1_input, q2_input, lb_input)
  File "/home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 60, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 70, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
RuntimeError: invalid argument 7: equal number of batches expected at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:447
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py(67)parallel_apply()
-> raise output
(Pdb) up
> /home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py(70)parallel_apply()
-> return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
(Pdb) 
> /home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py(60)forward()
-> outputs = self.parallel_apply(replicas, inputs, kwargs)
(Pdb) 
> /home/tangjianbo/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py(224)__call__()
-> result = self.forward(*input, **kwargs)
(Pdb) 
> /data/tangjianbo/question_normalization/AoA/char/main_SimpleAoA.py(300)train()
-> loss, prob = AoA(q1_input, q2_input, lb_input)
(Pdb) q1_input.size()
torch.Size([64, 20, 128])
(Pdb) q2_input.size()
torch.Size([64, 38, 128])
(Pdb) lb_input.size()
torch.Size([64, 1])
