### ISSUE TITLE
Test determination is incorrectly skipping tests

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#64902]
See e.g. #64870, that modified `aten/src/ATen/core/TensorBase.h`  and should have run all tests. Yet a lot of tests were skipped on the PR (and then failed on master) https://github.com/pytorch/pytorch/runs/3572552126#step:15:296

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra @driazati 
cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

**Comment by mruberry** [comment]
This was actually more severe than @ngimel described, because it wasn't clear that a target determinator was running or what is was doing, which led to confusion as we tried to understand the failure the PR was causing in HUD CI but not (apparently) on PR CI

**Comment by malfet** [comment]
Target determinator should not skip anything if any C/C++ source file/header is modified. 
Sounds like best course of action would be to disable it until it can be made reliable.

**Comment by ngimel** [comment]
Also, #64899  shows how target determinator is skipping tests even with ciflow/all label, and that label is put with express intention of running all the tests that are run on master.

**Comment by malfet** [comment]
Let's disable it for now: https://github.com/pytorch/pytorch/pull/64921
