### ISSUE TITLE
How to use python to implement _VF.lstm

### ISSUE THREAD

**Issue by TimothyLiuu** [pytorch/pytorch#64904]
## How to use python to implement _VF.lstm

Hello! When I want to modify the calculation formula of the LSTM，I found the calculation process in nn.LSTM is realized by _VF.lstm. I found the "_VF.lstm" is written by C++, and I can't find the RNN.cpp in my computer.

So I wanna implement _VF.lstm by using python, can u help me? 
Looking forward to your reply！ Thanks a lot！

**Comment by jbschlosser** [comment]
Hey @TimothyLiuu! You may have more luck posting a question like this on the [PyTorch forums](https://discuss.pytorch.org/). Note that the issues here are for problems within PyTorch and not for general assistance.

**Comment by TimothyLiuu** [comment]
Thanks anyway！
