### ISSUE TITLE
Unhelpful error message for mismatched shapes for Linear layer on CUDA

### ISSUE THREAD

**Issue by jfrancis71** [pytorch/pytorch#64920]
## 🐛 Bug

Unhelpful error message for mismatched shapes for Linear layer on CUDA

## To Reproduce

tensor_cpu = torch.ones([16,127])
tensor_cuda = torch.ones([16,127]).cuda()

layer_cpu = nn.Linear(128,64)
layer_cuda = nn.Linear(128,64).cuda()

layer_cpu(tensor_cpu)
>>RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x127 and 128x64)

Although it is not completely clear what mat1 and mat2 are, the error message is nevertheless fairly helpful at hinting at the cause of the problem.

However:
layer_cuda(tensor_cuda)
produces:
>>~/anaconda3/envs/Pytorch19/lib/python3.9/site-packages/torch/nn/functional.py in linear(input, weight, bias)
>>   1845     if has_torch_function_variadic(input, weight):
>>   1846         return handle_torch_function(linear, (input, weight), input, weight, bias=bias)-> 1847     return torch._C._nn.linear(input, weight, bias)
 >> 1848 
>>1849 

>>RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

This error message is far less clear that the source of the problem is mismatched tensor shapes.

## Expected behavior

Expected a similar error message to the CPU version:
>>RuntimeError: mat1 and mat2 shapes cannot be multiplied (16x127 and 128x64)

## Environment

Pytorch 1.9.0
OS: Ubuntu 18.04
conda install
python 3.9.5
CUDA 10.2
GPU: RTX 2070

## Additional context

cc @albanD @mruberry @jbschlosser @walterddr @ngimel @csarofeen @ptrblck @xwang233

**Comment by jbschlosser** [comment]
Thanks for the report, @jfrancis71! I agree that the error message isn't the best for understanding why the call failed.

**Comment by ngimel** [comment]
Fixed on master
