### ISSUE TITLE
`with-ssh` session are not terminated when job is completed/cancelled

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#64941]
For example:
I still have an active session to https://github.com/pytorch/pytorch/runs/3589553546?check_suite_focus=true

But I can still ssh to the node:
```
% ssh ec2-user@ec2-52-207-253-223.compute-1.amazonaws.com date
Mon Sep 13 18:00:41 UTC 2021

```

cc @ezyang @seemethere @malfet @lg20987 @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
We resolved this, closing
