### ISSUE TITLE
Feature request: convert .pth to ONNX

### ISSUE THREAD

**Issue by Praveen-24-mvp** [pytorch/pytorch#64980]
Need a new feature like converting the pytorch model file .pth file to converting onnx for intel openvino

cc @BowenBao @neginraoof

**Comment by fatcat-z** [comment]
Could you please provide a example to describe the concrete issue you met?

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
