### ISSUE TITLE
Why is there a GPU with a utilization rate of 0 when running pytorch's DDP task?

### ISSUE THREAD

**Issue by siaimes** [pytorch/pytorch#64989]
## ❓ Questions and Help
Why is there a GPU with a utilization rate of 0 when running pytorch's DDP task?
I used four RTX3090 graphics cards to train the resnet18 model, but I don't know why the utilization of one of the graphics cards is always 0.

Following this doc [https://github.com/pytorch/examples/tree/master/imagenet](https://github.com/pytorch/examples/tree/master/imagenet) to run the following command:
```
python main.py --arch resnet18 --multiprocessing-distributed --world-size 1 --rank 0 --batch-size 1024 --epochs 90
```

The GPU utilization results recorded by Grafana are as follows:

![image](https://user-images.githubusercontent.com/34199488/133264499-827f286b-b57c-421e-a8c1-d66430de3fa5.png)
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @ngimel

**Comment by mruberry** [comment]
This question might be best asked on the PyTorch forum, where we have an active community that's eager to help
