### ISSUE TITLE
Bump DLPack dependency

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#64995]
## 🚀 Feature

Don't know if the is a feature or a bug, but DLPack has changed in a API-Incompatible way (DLContext disappeared and the field was made opaque - possibly this isn't ABI-incompatible). This appears to mean that cannot compile PyTorch with something using the newer DLPack easily, e.g. recent TVM.

DLPack in TVM is at 0.5, PyTorch's is at 0.4 (I think).

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi @heitorschueroff

**Comment by mruberry** [comment]
cc our dlpack experts @emcastillo and @rgommers

**Comment by emcastillo** [comment]
After a first glance, I don't see any changes in the struct and fields of 0.4 and 0.6
just this typedef is gone

https://github.com/dmlc/dlpack/blob/v0.4/include/dlpack/dlpack.h#L76-L79

I grepped the codebase and this is where it is used

```
aten/src/ATen/DLConvertor.h:TORCH_API DLContext getDLContext(const Tensor& tensor, const int64_t& device_id);
aten/src/ATen/dlpack.h:typedef DLDevice DLContext;
caffe2/python/dlpack.h: * \brief The device type in DLContext.
caffe2/python/dlpack.h:} DLContext;
caffe2/python/dlpack.h:  DLContext ctx;
caffe2/python/pybind_state_dlpack.h:    DLContext tensor_context;
```

We have to replace `aten/src/ATen/DLConvertor.h` when we bump it.
Should we also bump caffe2 dlpack version?

**Comment by ezyang** [comment]
> Should we also bump caffe2 dlpack version?

I guess if it doesn't cause too much trouble...

**Comment by leofang** [comment]
Context: https://github.com/dmlc/dlpack/pull/62. This should be ABI compatible, if not it's a big concern.

**Comment by t-vi** [comment]
Thank you all for weighing in! I'll send a patch.

**Comment by rgommers** [comment]
>> This appears to mean that cannot compile PyTorch with something using the newer DLPack easily, e.g. recent TVM.

> Context: [dmlc/dlpack#62](https://github.com/dmlc/dlpack/pull/62). This should be ABI compatible, if not it's a big concern.

To add to that: DLPack doesn't have a public API that PyTorch exposes, this is just a rename of a struct that is part of the ABI. So there should be no problem mixing TVM and PyTorch in the current state.
