### ISSUE TITLE
Error building from source CMakeFiles/Makefile2:201: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed

### ISSUE THREAD

**Issue by J0** [pytorch/pytorch#6501]
Hi all, 

After running ` python setup.py install `  on Ubuntu 16.04 LTS(CUDA 9.1), I encounter the following error:

/home/ubuntu/pytorch/aten/src/THCUNN/LookupTable.cu(25): warning: function "__shfl(int, int, int)"
/usr/local/cuda/include/sm_30_intrinsics.hpp(152): here was declared deprecated ("__shfl() is deprecated in favor of __shfl_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

/home/ubuntu/pytorch/aten/src/THCUNN/LookupTable.cu(42): warning: function "__any"
/usr/local/cuda/include/device_atomic_functions.h(180): here was declared deprecated ("__any() is deprecated in favor of __any_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

[ 35%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_MSECriterion.cu.o
[ 36%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_MultiLabelMarginCriterion.cu.o
[ 36%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_MultiMarginCriterion.cu.o
[ 36%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_PReLU.cu.o
[ 36%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_RReLU.cu.o
[ 37%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_Sigmoid.cu.o
[ 37%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SmoothL1Criterion.cu.o
[ 37%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SoftMarginCriterion.cu.o
[ 37%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SoftMax.cu.o
[ 38%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SoftPlus.cu.o
[ 38%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SoftShrink.cu.o
[ 38%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SparseLinear.cu.o
[ 38%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialAdaptiveAveragePooling.cu.o
[ 39%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialAdaptiveMaxPooling.cu.o
[ 39%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialAveragePooling.cu.o
[ 39%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialClassNLLCriterion.cu.o
[ 39%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialConvolutionLocal.cu.o
[ 40%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialConvolutionMM.cu.o
[ 40%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialCrossMapLRN.cu.o
[ 40%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialDepthwiseConvolution.cu.o
[ 40%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialDilatedConvolution.cu.o
[ 40%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialDilatedMaxPooling.cu.o
[ 41%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialFractionalMaxPooling.cu.o
[ 41%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialFullConvolution.cu.o
[ 41%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialFullDilatedConvolution.cu.o
[ 41%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialGridSamplerBilinear.cu.o
[ 42%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialMaxPooling.cu.o
[ 42%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialMaxUnpooling.cu.o
[ 42%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialReflectionPadding.cu.o
[ 42%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialReplicationPadding.cu.o
[ 43%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialSubSampling.cu.o
[ 43%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialUpSamplingBilinear.cu.o
[ 43%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_SpatialUpSamplingNearest.cu.o
[ 43%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_Sqrt.cu.o
[ 44%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_Square.cu.o
[ 44%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_Tanh.cu.o
[ 44%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalConvolution.cu.o
[ 44%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalMaxPooling.cu.o
[ 44%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalReflectionPadding.cu.o
[ 45%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalReplicationPadding.cu.o
[ 45%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalRowConvolution.cu.o
[ 45%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalUpSamplingLinear.cu.o
[ 45%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_TemporalUpSamplingNearest.cu.o
[ 46%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_Threshold.cu.o
[ 46%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricAdaptiveAveragePooling.cu.o
[ 46%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricAdaptiveMaxPooling.cu.o
[ 46%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricAveragePooling.cu.o
[ 47%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricConvolution.cu.o
[ 47%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricDilatedConvolution.cu.o
[ 47%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricDilatedMaxPooling.cu.o
[ 47%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricFractionalMaxPooling.cu.o
[ 48%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricFullConvolution.cu.o
[ 48%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricFullDilatedConvolution.cu.o
[ 48%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricGridSamplerBilinear.cu.o
[ 48%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricMaxPooling.cu.o
[ 48%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricMaxUnpooling.cu.o
[ 49%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricReplicationPadding.cu.o
[ 49%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricUpSamplingNearest.cu.o
[ 49%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCUNN/ATen_generated_VolumetricUpSamplingTrilinear.cu.o
[ 49%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCS/ATen_generated_THCSTensor.cu.o
[ 50%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THCS/ATen_generated_THCSparse.cu.o
[ 50%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/cuda/ATen_generated_CUDAHalf.cu.o
[ 50%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/cuda/detail/ATen_generated_IndexUtils.cu.o
[ 50%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Distributions.cu.o
[ 51%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Embedding.cu.o
/home/ubuntu/pytorch/aten/src/TH/THStorage.h(26): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(136): error: identifier "THDescBuff" is undefined

/home/ubuntu/pytorch/aten/src/TH/generic/THTensor.h(137): error: identifier "THDescBuff" is undefined

17 errors detected in the compilation of "/tmp/tmpxft_0000539b_00000000-6_Distributions.cpp1.ii".
CMake Error at ATen_generated_Distributions.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/ubuntu/pytorch/aten/build/src/ATen/CMakeFiles/ATen.dir/native/cuda/./ATen_generated_Distributions.cu.o

src/ATen/CMakeFiles/ATen.dir/build.make:1148: recipe for target 'src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Distributions.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Distributions.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ubuntu/pytorch/aten/src/ATen/native/cuda/Embedding.cu(37): warning: function "__any"
/usr/local/cuda/include/device_atomic_functions.h(180): here was declared deprecated ("__any() is deprecated in favor of __any_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

CMakeFiles/Makefile2:201: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

 PyTorch version:
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.6.4
- CUDA/cuDNN version: 9.1
- GPU models and configuration: K80
- GCC version (if compiling from source): 5.4.0 20160609
- CMake version: cmake version 3.9.4

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

Just wondering if anyone knows how I can fix this.

Thanks

**Comment by zhuhaozh** [comment]
I also have the same question. 
--------
Files/ATen.dir/native/cuda/ATen_generated_TensorCompare.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_TensorCompare.cu.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rien333** [comment]
@Zhuaozh did you manage to fix this? I'm getting the same error.

**Comment by rien333** [comment]
Yeah, that was it. I think you have to try with a gcc version starting from 6.3.0 or below.

**Comment by Kongsea** [comment]
The same error as you.

**Comment by rgreenblatt** [comment]
I had the same problem and I think I found the root cause and a solution. The issue is that different header files are present in the cmake include path and these headers are included instead of the correct headers. Specifically, a distinct `THGeneral.h` file causes this issue. For me, the problematic lingering headers were in `miniconda3/envs/<ENV_NAME>/include`. They are in the cmake include path due adding conda directories to the cmake prefix path. ie, running `export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"`. My build hasn't finished yet, but I have gotten past the point where this error occurs. To reasonably easily determine if this is your issue and figure out where the old headers are, try running something along the files of `find / -name 'THGeneral.h'`.

I will update this post once/if the build finishes.

**Comment by jybaek** [comment]
I had the same problem and renamed `THGeneral.h` from `conda/envs/<ENV_NAME>/` to something similar to what @rgreenblatt  said, and it was installed normally. Good luck to friends who are having the same problem.

**Comment by pietern** [comment]
This issue hasn't seen updates for a while and the build system has seen many change since last year.

If this issue has persisted regardless, please feel free to reopen and update the issue.
