### ISSUE TITLE
Caffe2/detectron: GPU not configured

### ISSUE THREAD

**Issue by Flock1** [pytorch/pytorch#6503]
Caffe2/Detectron
OS: Ubuntu 16.04
Python: 2.7
GPU: GTX 1080
gcc version: 5.4.0

I have installed CUDA, Cudnn and nccl in a conda environment and followed the steps:

conda install -c caffe2 caffe2-cuda9.0-cudnn7
--
Then, to see if GPU is working, I get the following:
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libnccl.so.2: cannot open shared object file: No such file or directory
Segmentation fault (core dumped)

I don't know what I am doing wrong or something I am missing. Please let me know.

**Comment by pjh5** [comment]
The CUDA packages require NCCL. You will need to install it from Nvidia's instructions https://developer.nvidia.com/nccl

**Comment by Flock1** [comment]
@pjh5, Thanks. I have installed NCCL using conda since I am using a conda environment. Anaconda provides installation for NCCL.

**Comment by pjh5** [comment]
Don't install the '-gcc4.8' versions; they will definitely break on your machine.

I did not realize that NCCL was provided in an anaconda package. Unfortunately, the Caffe2 packages are built assuming NCCL is installed in your system directories (some place like /usr/lib/ or /usr/local/lib/), so for now you will still have to install NCCL from that link above.

**Comment by pjh5** [comment]
@Flock1 do not install caffe2-cuda9.0-cudnn7-gcc4.8 . It does not come with it's own gcc; it is built specifically for gcc < 5. Your gcc is 5.04 so it will break for sure. It also might install conda packages specifically built for gcc < 5 which will corrupt your conda environment and break lots of things.

What is your error message now?

**Comment by Flock1** [comment]
@pjh5, I don't have my work machine right now. I will post it in a few hours. In the meantime, what do you recommend I should run? 

I have installed NVIDIA packages, both on machine and though conda. `conda install -c caffe2 caffe2-cuda9.0-cudnn7` is on the webpage of caffe2. So what do you suggest?

**Comment by Flock1** [comment]
@pjh5, I get this warning now:
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcurand.so.9.0: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: /home/sarvagya/anaconda3/envs/caffe2/lib/python2.7/site-packages/caffe2/python/../../../../libcaffe2.so: undefined symbol: _ZN6google15SetUsageMessageERKSs`

**Comment by Flock1** [comment]
@pjh5, Do you have a solution to this?
`It appears that an X server is running. Please exit X before installation. If you're sure that X is not running, but are getting this error, please delete any X lock files in /tmp.`

**Comment by pjh5** [comment]
That error is caused by https://github.com/caffe2/caffe2/issues/1980 , which is caused by installing caffe2-cuda9.0-cudnn7-gcc4.8 instead of caffe2-cuda9.0-cudnn7 . You should clean out your anaconda environment and install caffe2-cuda9.0-cudnn7 in a new conda environment.

**Comment by pjh5** [comment]
The "X server" error is an error about X http://www.linfo.org/x_server.html and is unrelated to Caffe2.

**Comment by Flock1** [comment]
Hi,
Yeah, I did it. My Ubuntu crashed because I followed this:
https://askubuntu.com/questions/149206/how-to-install-nvidia-run

I installed Ubuntu all over again, created new conda environment and used `caffe2-cuda9.0-cudnn7`. Still getting the error.

**Comment by pjh5** [comment]
What warning do you get?

**Comment by Flock1** [comment]
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcurand.so.8.0: cannot open shared object file: No such file or directory
Segmentation fault (core dumped`

**Comment by pjh5** [comment]
You need to install caffe2-cuda9.0-cudnn7 not caffe2-cuda8.0-cudnn7

**Comment by Flock1** [comment]
Hi, 
I did that. It still gives the warnings

**Comment by Flock1** [comment]
@pjh5, I was able to get rid of the warnings and got 1 as the output, meaning, GPU is being used. I am facing a new issue. 
I am getting a new error now when I run `python2 $DETECTRON/tests/test_spatial_narrow_as_op.py`:

```
E0421 16:01:19.569461 10741 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0421 16:01:19.569483 10741 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0421 16:01:19.569500 10741 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.h:155] . Encountered CUDA error: invalid device ordinal 
*** Aborted at 1524306679 (unix time) try "date -d @1524306679" if you are using GNU date ***
PC: @     0x7fe69f7ea428 gsignal
*** SIGABRT (@0x3e8000029f5) received by PID 10741 (TID 0x7fe6a0a65700) from PID 10741; stack trace: ***
    @     0x7fe6a02a0390 (unknown)
    @     0x7fe69f7ea428 gsignal
    @     0x7fe69f7ec02a abort
    @     0x7fe69151cb39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7fe69151b1fb __cxxabiv1::__terminate()
    @     0x7fe69151a640 __cxa_call_terminate
    @     0x7fe69151ae6f __gxx_personality_v0
    @     0x7fe69a4b8564 _Unwind_RaiseException_Phase2
    @     0x7fe69a4b881d _Unwind_RaiseException
    @     0x7fe69151b409 __cxa_throw
    @     0x7fe68f6c2b89 caffe2::CUDAContext::~CUDAContext()
    @     0x7fe68f84e52e caffe2::Operator<>::~Operator()
    @     0x7fe6564abb0a caffe2::SpatialNarrowAsOp<>::~SpatialNarrowAsOp()
    @     0x7fe6564abb3a caffe2::SpatialNarrowAsOp<>::~SpatialNarrowAsOp()
    @     0x7fe68e694acf caffe2::Workspace::RunOperatorOnce()
    @     0x7fe69094feea _ZZN6caffe26python16addGlobalMethodsERN8pybind116moduleEENKUlRKNS1_5bytesEE26_clES6_.isra.2766.constprop.2816
    @     0x7fe690950185 _ZZN8pybind1112cpp_function10initializeIZN6caffe26python16addGlobalMethodsERNS_6moduleEEUlRKNS_5bytesEE26_bJS8_EJNS_4nameENS_5scopeENS_7siblingEEEEvOT_PFT0_DpT1_EDpRKT2_ENUlRNS_6detail13function_callEE1_4_FUNESQ_
    @     0x7fe69097a4bd pybind11::cpp_function::dispatcher()
    @     0x7fe6a058e645 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a058d4b2 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a058d4b2 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a058d4b2 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a05190f7 function_call
    @     0x7fe6a04f47a3 PyObject_Call
    @     0x7fe6a0589500 PyEval_EvalFrameEx
    @     0x7fe6a0590519 PyEval_EvalCodeEx
    @     0x7fe6a051900a function_call
    @     0x7fe6a04f47a3 PyObject_Call
Aborted (core dumped)
```

Can you help me with this?

**Comment by pjh5** [comment]
@Flock1 are you still having this problem? This looks like specifying a GPU that doesn't exist. Your GPU comes with a 'n' devices; if you try to use device >= 'n' then you'll get this error.

If you do have enough devices, then there might be a problem with your CUDA installation.

**Comment by Flock1** [comment]
@pjh5, I'm able to work with it using docker but it's still giving me the error when I run it conda environment.

**Comment by pjh5** [comment]
What is `nvidia-smi` ?

**Comment by Flock1** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.18                 Driver Version: 396.18                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   39C    P8    14W / 200W |    478MiB /  8116MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1156      G   /usr/lib/xorg/Xorg                           261MiB |
|    0      2414      G   compiz                                        57MiB |
|    0      2792      G   ...-token=D604B93340494189446D8A7E923B0268    80MiB |
|    0      4854      G   ...-token=4F41BAE5EFCAE0A586E2FC8AF3B4D662    33MiB |
|    0      7490      G   ...-token=60CEFA0C299771C625922A7EA50550D9    42MiB |
+-----------------------------------------------------------------------------
```
