### ISSUE TITLE
Why DataLoader need a separate thread for pin_memory?

### ISSUE THREAD

**Issue by li-yi-dong** [pytorch/pytorch#65046]
The main process will launch a thread that execute `_pin_memory_loop` when `pin_memory` flag been set. Basically, it pull out a sample from `_worker_result_queue`, apply `pin_memory` on the sample and put it into `_data_queue`.

My question is that why not let each worker call `pin_memory` right after they fetched the sample and put it directly to `_data_queue`. Why we need a separate thread to do this?

Thanks a lot for any information.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by VitalyFedyunin** [comment]
Pin memory allows GPU devices to access page-locked memory of the process (or its threads). Pinning in the worker process will not make this memory accessible by GPU context assigned to the trainer (main) process.

**Comment by li-yi-dong** [comment]
I see, thanks!
