### ISSUE TITLE
Difference in git behaviour in CentOS vs Ubuntu base dockers for ROCm

### ISSUE THREAD

**Issue by jithunnair-amd** [pytorch/pytorch#65048]
## 🐛 Bug

In file https://github.com/pytorch/pytorch/blob/d6d286f651980a5faaa5631c8f8f8934a49978fd/tools/stats/s3_stat_parser.py#L203, a `git rev-list` command is invoked with the `--remotes` flag.
This flag is set to `*origin/viable/strict` by the function call at https://github.com/pytorch/pytorch/blob/d6d286f651980a5faaa5631c8f8f8934a49978fd/tools/testing/test_selections.py#L97

The behaviour of the `git rev-list` command varies between the default git versions installed for CentOS 7 (1.8.3.1) (error) vs Ubuntu 18.04 (2.17.1) (no error) when the remote branch info hasn't been fetched.

## To Reproduce

`git rev-list --remotes=*mybranch`

Output:
Ubuntu18.04 (git 2.17.1) (no error):
```
root@b5c71a8b7a63:/var/lib/jenkins/pytorch# git rev-list --remotes=*mybranch
root@b5c71a8b7a63:/var/lib/jenkins/pytorch#
```
CentOS7 (git 1.8.3.1) (error):
```
[root@db881265096c pytorch]# git rev-list --remotes=*mybranch
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
```

To install the latest git version on CentOS7, I followed the steps here: https://computingforgeeks.com/how-to-install-latest-version-of-git-git-2-x-on-centos-7/
```
sudo yum -y remove git
sudo yum -y remove git-*
sudo yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.9-1.x86_64.rpm
sudo yum install git
```

With these steps, I got a newer git version, which has the same behaviour as Ubuntu18.04:
```
[root@95f5cbec1d94 pytorch]# git --version
git version 2.30.1
[root@95f5cbec1d94 pytorch]# git rev-list --remotes=*mybranch
[root@95f5cbec1d94 pytorch]#
```

**This issue crops up when running PyTorch unit tests in a base docker built using the Dockerfiles at:
https://github.com/pytorch/pytorch/blob/master/.circleci/docker/ubuntu-rocm/Dockerfile, and
https://github.com/pytorch/pytorch/blob/master/.circleci/docker/centos-rocm/Dockerfile**

## Expected behavior

The command should give no output without erroring out if the remote branch hasn't been fetched or doesn't exist.

## Environment

[root@95f5cbec1d94 pytorch]# python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: 13.0.0 (ssh://gerritgit/lightning/ec/llvm-project amd-mainline-open 21355 a82a3af0e468e06e83c7d9e92741493521d7e6ba)
CMake version: version 3.19.6
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.18.0-25-generic-x86_64-with-centos-7.9.2009-Core
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.18.5
[pip3] torch==1.10.0a0+giteeaa676
[pip3] torchvision==0.10.0a0+e828eef
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-include               2021.3.0           h06a4308_520
[conda] mypy                      0.812                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.18.5           py36h7130bb8_0
[conda] numpy-base                1.18.5           py36h2f8d375_0
[conda] torch                     1.10.0a0+giteeaa676          pypi_0    pypi
[conda] torchvision               0.10.0a0+e828eef          pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by seemethere** [comment]
We'd definitely be open to a PR that updates the version of git in the CentOS docker images

**Comment by jithunnair-amd** [comment]
@seemethere And this fix looks okay? If so, I'll file a PR to update the CentOS script:
```
sudo yum -y remove git
sudo yum -y remove git-*
sudo yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.9-1.x86_64.rpm
sudo yum install git
```
