### ISSUE TITLE
LSTM.weight_ih_l[k] dimensions with proj_size

### ISSUE THREAD

**Issue by mrityu-jha** [pytorch/pytorch#65053]
According to Pytorch [LSTM documentation](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html) :-

`~LSTM.weight_ih_l[k]** – the learnable input-hidden weights of the kth layer (W_ii|W_if|W_ig|W_io), of shape (4*hidden_size, input_size) for k = 0. Otherwise, the shape is (4 * hidden_size, num_directions * hidden_size)`

My doubt is, why for `k > 0`  the shape for each weight is `(hidden_size, num_directions * hidden_size)`, according to me, shouldn't be `(hidden_size, num_directions * proj_size)`  because the layer above the lowest layer is receiving the input which is the output of the lowest layer which have the shape of `(L, N, num_directions*proj_size)`

Link to StackOverflow question:- [LSTM.weight_ih_l[k] dimensions with proj_size](https://stackoverflow.com/questions/69190587/lstm-weight-ih-lk-dimensions-with-proj-size)

cc @brianjo @mruberry @zou3519

**Comment by jbschlosser** [comment]
Hey @mrityu-jha, thanks for the report! We'd accept a PR addressing this within the docs.
