### ISSUE TITLE
Pickling `torch.dtype` objects is unnecessarily slow

### ISSUE THREAD

**Issue by nelhage** [pytorch/pytorch#65077]
## 🐛 Bug

Pickling `torch.dtype` objects is unnecessarily slow, due to forcing `pickle` to search the entire Python module namespace to find the right module.

## To Reproduce

A simple benchmark:

```
❯ python -m timeit -s 'import torch, pickle' 'pickle.dumps(torch.float32)'
1000 loops, best of 5: 212 usec per loop
```

Compare to pickling a built-in type, or the class `torch.dtype`:
```
❯ python -m timeit -s 'import torch, pickle' 'pickle.dumps(float)'
500000 loops, best of 5: 687 nsec per loop

❯ python -m timeit -s 'import torch, pickle' 'pickle.dumps(torch.dtype)'
500000 loops, best of 5: 626 nsec per loop
```

Notice the `usec` vs `nsec` -- `torch.float32` is around _3000_ times slower.

I believe the problem is that `torch.dtype` instances:
1. define a `__reduce__` which returns a string, and
2. lack a `__module__` property to tell Pickle the name of the module to which they belong.

In this case, Python reacts by (approximately) **searching every module in `sys.modules`** to find a module s.t. `getattr(mod, obj.__reduce__()) is obj`.

We can reproduce this fallback behavior with a simple script:

```
❯ cat bench.py
import timeit
import pickle
from dataclasses import dataclass

@dataclass
class FakeDtype:
  name: str

  def __reduce__(self):
    return self.name

int = FakeDtype('int')

if __name__ == '__main__':
  N = 10000
  t1 = timeit.timeit(lambda: pickle.dumps(int), number=N)
  print(f"Pickling our fake dtype: {1000000 * t1 / N:0.3f}us")
  int.__module__ = None
  t2 = timeit.timeit(lambda: pickle.dumps(int), number=N)
  print(f"Pickling our fake dtype (no __module__): {1000000 * t2 / N:0.3f}us")

❯ python -m bench
Pickling our fake dtype: 1.156us
Pickling our fake dtype (no __module__): 29.290us
```

We see a similar slowdown when we remove the `__module__` field.

## Expected behavior

I believe the correct fix here is to add a `__module__` attribute to the `torch.dtype` class, which contains the value `torch`. This will be inherited via its instances and avoid the `sys.modules` walk.

## Environment

```
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.2 (arm64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.9)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30)  [Clang 11.0.1 ] (64-bit runtime)
Python platform: macOS-11.5.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.2
[pip3] pytorch-memlab==0.2.3
[pip3] torch==1.9.0
[pip3] torchtyping==0.1.1
[conda] Could not collect
```

## Additional context

cc @VitalyFedyunin @ngimel @heitorschueroff @mruberry

**Comment by mruberry** [comment]
Thank you for filing this issue and the discussion, @nelhage! It'd be great if you wanted to submit a PR fixing this.

**Comment by ezyang** [comment]
Just checking: in principle, we could also fix this by making `torch.dtype.__reduce__` return a tuple (which is what we do for, e.g., Tensor serialization). However, this would be BC-breaking for the pickling format, so fixing sys.module is here. I suppose this also means we should audit all the other sites where we are returning string from reduce.

**Comment by nelhage** [comment]
Yeah, returning a tuple from `torch.dtype.__reduce__` would also work here.

I think we could even potentially be BC as long as the callable (first element of the tuple) was a pre-existing symbol that existed and had the desired behavior in all supported versions. However, I'm not sure if there's such a symbol without doing gross hacks -- one could imagine generating a series of calls that look up `sys.modules["torch"].float32` but that sounds worse to me.
