### ISSUE TITLE
[Efficiency] Sometimes CudaMalloc is slow in FSDP

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#65078]
For FSDP applications, when CUDA memory usage reaches at some point, cudaMalloc will be extremely slow, possibly because FSDP frequently allocate/deallocate memories, which caused bad memory fragmentation and made cuda cache allocator run out of memory sporadically. This caused cudaMalloc to be extremely slow in some cases. We need to take a look at the memory management issue and see how to mitigate it

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by cbalioglu** [comment]
Are we calling `cudaMalloc` directly or through c10's `CUDACachingAllocator`?

**Comment by zhaojuanmao** [comment]
> Are we calling `cudaMalloc` directly or through c10's `CUDACachingAllocator`?

@cbalioglu current codes frequently deallocate old memory and allocate new memory by calling data.storage().resize_(0) and data.storage().resize_(size.numel()). I'm not sure what is called underneath. But I can see cudaMalloc is showed in the traces.  Do you have suggestions to make memory free and allocation more efficient? thanks!

**Comment by cbalioglu** [comment]
I see. Well, then this requires more investigation since by default PyTorch uses the `CUDACachingAllocator` which supposed to provide buffer pools to optimize calls to `cudaMalloc`. I see that @mrshenli is the last (and only) person who touched the allocator code in the past. Maybe he might have a bit more context.

Having said that, do you mind giving a specific number for "when CUDA memory usage reaches at some point"?

**Comment by zhaojuanmao** [comment]
there is no specific number actually, based on my experiments it is different case by case:(, for some cases I've known, they reserved 10G memory for avoiding slow cudaMalloc..

**Comment by awgu** [comment]
The rate limiter addresses the over-prefetching issue for FSDP. The remaining issue is memory fragmentation. This can be tackled from the caching allocator level, from the FSDP level by pre-allocating and explicitly managing buffers, or both.

I am closing this issue as stale, and we can open a new issue if/when we have tangible ideas for how to target the memory fragmentation issue. (Actually, I have one idea and can flesh it out soon.)
