### ISSUE TITLE
[AWS EC2 P3DN] torch sync.pipeline makes the tensor passing to the next stage in CPU device; it's working without using pipeline

### ISSUE THREAD

**Issue by chaoyanghe** [pytorch/pytorch#65093]
## 🐛 Bug
In my context, I create three modules: layer 1 (inter_node_moe_layer_in), layer 2(intra_node_moe_layer), layer 3 (inter_node_moe_layer_out). Then I wrap them as a pipeline. 
```
 # Step 2: wrap the two layers with nn.Sequential
        pipeline_model = nn.Sequential(
            self.inter_node_moe_layer_in, self.intra_node_moe_layer, self.inter_node_moe_layer_out
        )

        # Step 3: build Pipe (torch.distributed.pipeline.sync.Pipe)
        self.pipeline_model = PipeModelWrapper(Pipe(pipeline_model, chunks=1, checkpoint="never"))
```
**Issue**: torch sync.pipeline makes the tensor passing to the next stage **in CPU device.**

Error log:
```
10.0.87.143: 10.0.87.143:     return forward_call(*input, **kwargs)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/pipe.py", line 392, in forward
10.0.87.143: 10.0.87.143:     self.pipeline.run(batches)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/pipeline.py", line 115, in run
10.0.87.143: 10.0.87.143:     self.compute(batches, schedule, skip_trackers)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/pipeline.py", line 255, in compute
10.0.87.143: 10.0.87.143:     raise exc_info[0].with_traceback(exc_info[1], exc_info[2])
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/worker.py", line 79, in worker
10.0.87.143: 10.0.87.143:     batch = task.compute()
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/worker.py", line 60, in compute
10.0.87.143: 10.0.87.143:     return self._compute()
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/pipeline.py", line 220, in compute
10.0.87.143: 10.0.87.143:     return batch.call(partition)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/pipeline/sync/microbatch.py", line 70, in call
10.0.87.143: 10.0.87.143:     return Batch(function(self.value))
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
10.0.87.143: 10.0.87.143:     return forward_call(*input, **kwargs)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 139, in forward
10.0.87.143: 10.0.87.143:     input = module(input)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
10.0.87.143: 10.0.87.143:     return forward_call(*input, **kwargs)
10.0.87.143: 10.0.87.143:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/model/hpb_moe_layer.py", line 451, in forward
10.0.87.143: 10.0.87.143:     self.inter_node_process_group, output_of_intra_node_moe_tensor
10.0.87.143: 10.0.87.143:   File "/home/deepspeed/.local/lib/python3.6/site-packages/moe_layer/model/switch_transformer_layers.py", line 25, in forward
10.0.87.143: 10.0.87.143:     dist.all_to_all_single(output, input, group=group)
10.0.87.143: 10.0.87.143:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 2386, in all_to_all_single
10.0.87.143: 10.0.87.143:     work = group.alltoall_base(output, input, output_split_sizes, input_split_sizes, opts)
10.0.87.143: 10.0.87.143: RuntimeError: Tensors must be CUDA and dense
```
**Checking the tensor status, I can see layer2's output is on GPU device, but the input of layer 3 is in CPU device.**
```
10.0.87.143: 10.0.87.143: 3306 2021-09-15,19:27:08.782 - {hpb_moe_layer.py (424)} - forward(): inter-node out output_of_intra_node_moe_tensor.shape = torch.Size([8192, 1024]), output_of_intra_node_moe_tensor = tensor([
[ 0.0204, -0.0436,  0.0189,  ...,  0.0106,  0.0386,  0.0347],
10.0.87.143: 10.0.87.143:         [ 0.0228, -0.0007,  0.0188,  ...,  0.0000,  0.0327,  0.0484],
10.0.87.143: 10.0.87.143:         [ 0.0140,  0.0074,  0.0197,  ...,  0.0167,  0.0303,  0.0263],
10.0.87.143: 10.0.87.143:         ...,
10.0.87.143: 10.0.87.143:         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
10.0.87.143: 10.0.87.143:         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
10.0.87.143: 10.0.87.143:         [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
10.0.87.143: 10.0.87.143:        grad_fn=<WaitBackward>)   <---- **"cuda:0" is not shown here**
```

It's working if I directly use layer3(layer2(layer1(x)). See log below, the same tensor is in GPU (cuda:0) rather than CPU.
```
10.0.87.143: 10.0.92.117: 3227 2021-09-15,19:05:04.533 - {hpb_moe_layer.py (424)} - forward(): inter-node out output_of_intra_node_moe_tensor.shape = torch.Size([8192, 1024]), output_of_intra_node_moe_tensor = tensor([[0., 0., 0.,  ..., 0., 0., 0.],
10.0.87.143: 10.0.92.117:         [0., 0., 0.,  ..., 0., 0., 0.],
10.0.87.143: 10.0.92.117:         [0., 0., 0.,  ..., 0., 0., 0.],
10.0.87.143: 10.0.92.117:         ...,
10.0.87.143: 10.0.92.117:         [0., 0., 0.,  ..., 0., 0., 0.],
10.0.87.143: 10.0.92.117:         [0., 0., 0.,  ..., 0., 0., 0.],
10.0.87.143: 10.0.92.117:         [0., 0., 0.,  ..., 0., 0., 0.]], **device='cuda:0',**
10.0.87.143: 10.0.92.117:        grad_fn=<FusedDropoutBackward>)
```

## To Reproduce

github repo: https://github.com/chaoyanghe/pytorch_bug_reproduce/blob/master/main.py

## Expected behavior

pipeline can work normally.

## Environment
[hchaoyan@ip-10-0-87-143]/fsx/hchaoyan/home/m5/src/MoELayer/scripts/docker% python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
Clang version: 7.0.1 (Amazon Linux 2 7.0.1-1.amzn2.0.2)
CMake version: version 3.18.2
Libc version: glibc-2.2.5

Python version: 2.7.18 (default, Aug 27 2020, 21:22:52)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)] (64-bit runtime)
Python platform: Linux-4.14.200-155.322.amzn2.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: N/A
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.16.6
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by chaoyanghe** [comment]
I figured out the reason: when I remove all learnable parameters from a pipeline partition, this partition will receive CPU-based tensor. Can we also support GPU tensor for this case? Our goal is to overlap communication and computation, so for pipeline partition that focuses on communication, we also hope it can receive GPU tensor.

```
class InterNodeMoELayerOutTest(nn.Module):
    def __init__(self, shared_module, hidden_size, local_rank, pg):
        super().__init__()
        self.shared_module = shared_module
        # self.fc3 = nn.Linear(hidden_size, hidden_size).cuda(local_rank)  <---- when delete this line, we can reproduce the error.
        self.pg = pg

    def forward(self, x):
        logging.info("Test: output_of_intra_node_moe_tensor = {}".format(x))
        x = _AllToAll.apply(self.pg, x)
        return x
```

**Comment by chaoyanghe** [comment]
I fixed this issue by creating a [1, 1] tensor:
```
class InterNodeMoELayerOutTest(nn.Module):
    def __init__(self, shared_module, hidden_size, local_rank, pg):
        super().__init__()
        self.shared_module = shared_module
        self.dummy_tensor = nn.Linear(1, 1).cuda(local_rank)
        self.pg = pg

    def forward(self, x):
        logging.info("Test: output_of_intra_node_moe_tensor = {}".format(x))
        x = _AllToAll.apply(self.pg, x)
        return x
```

**Comment by pritamdamania87** [comment]
> github repo: https://github.com/chaoyanghe/pytorch_bug_reproduce/blob/master/main.py

@chaoyanghe I tried this repro but ran into the following error:

```
Traceback (most recent call last):
  File "/tmp/pipeline_repro.py", line 14, in <module>
    from model.tree_moe_model import TreeMoEModel
ModuleNotFoundError: No module named 'model'
```

Where can I find this package?

**Comment by pritamdamania87** [comment]
> I figured out the reason: when I remove all learnable parameters from a pipeline partition, this partition will receive CPU-based tensor. Can we also support GPU tensor for this case? Our goal is to overlap communication and computation, so for pipeline partition that focuses on communication, we also hope it can receive GPU tensor.

Currently the placement of the partition is determined by its parameters. So if the partition doesn't have any parameters, it is assumed this is a CPU partition. You can use the workaround you mentioned above to add a dummy tensor, or another option is to merge this partition with a previous partition? Is there a reason you need to have a new partition which doesn't actually have any data in it?

**Comment by pritamdamania87** [comment]
Thinking about this for a while, one option might be to add `devices_override` field to the `Pipe` constructor, this way we don't always rely on implicitly detecting the device for a partition and the user can provide an appropriate device for a partition.

**Comment by chaoyanghe** [comment]
@pritamdamania87 because that partition is for pure communication (all_to_all). I want to overlap it with GPU computation.

**Comment by chaoyanghe** [comment]
@pritamdamania87 could you download the entire repo (https://github.com/chaoyanghe/pytorch_bug_reproduce) and run with:
```
sh run.sh 8 1 0 10.0.87.143 10000 1 eth0
```
Remember to change the IP and port.

**Comment by pritamdamania87** [comment]
@chaoyanghe I was able to repro the issue and come up with a potential fix for the same: https://github.com/pytorch/pytorch/pull/65190. I tested this with your code by making a small modification to your script:

```
diff --git a/model/tree_moe_model.py b/model/tree_moe_model.py
index 2079a76..874220e 100755
--- a/model/tree_moe_model.py
+++ b/model/tree_moe_model.py
@@ -1,5 +1,6 @@
+import torch
 from torch import nn
-from torch.distributed.pipeline.sync import Pipe
+from torch.distributed.pipeline.sync import Pipe, WithDevice
 
 from .hpb_moe_layer import (
     SharedModule,
@@ -109,7 +110,7 @@ class TreeMoEModel(nn.Module):
             pipeline_model = nn.Sequential(
                 self.inter_node_moe_layer_in,
                 self.intra_node_moe_layer,
-                self.inter_node_moe_layer_out,
+                WithDevice(self.inter_node_moe_layer_out, torch.device(self.local_rank)),
                 self.dense,
             )
```

This does seem to resolve the error that you were seeing, however the script then fails for me at a different place as shown below. However, I don't think this might necessarily be an issue with the pipe implementation but probably something that needs to be fixed in `hpb_moe_layer.py`?

```
  File "/data/users/pritam/pytorch/torch/distributed/pipeline/sync/microbatch.py", line 94, in call
        inputs = module(inputs)return Batch(function(self._values))

  File "/data/users/pritam/pytorch/torch/nn/modules/module.py", line 1102, in _call_impl
  File "/data/users/pritam/pytorch/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/tmp/repro/pytorch_bug_reproduce/model/hpb_moe_layer.py", line 509, in forward
    return forward_call(*input, **kwargs)
  File "/data/users/pritam/pytorch/torch/distributed/pipeline/sync/pipe.py", line 132, in forward
    return forward_call(*input, **kwargs)
  File "/data/users/pritam/pytorch/torch/distributed/pipeline/sync/pipe.py", line 132, in forward
    final_output = final_output.view(batch_size, seq_len, d_model)    
        inputs = module(inputs)return forward_call(*input, **kwargs)RuntimeErrorreturn forward_call(*input, **kwargs)

: 
  File "/data/users/pritam/pytorch/torch/nn/modules/module.py", line 1102, in _call_impl
  File "/tmp/repro/pytorch_bug_reproduce/model/hpb_moe_layer.py", line 509, in forward
shape '[8, 128, 1024]' is invalid for input of size 8388608  File "/data/users/pritam/pytorch/torch/distributed/pipeline/sync/pipe.py", line 132, in forward
```

Let me know if the proposed fix makes sense and we can try to land it soon.
