### ISSUE TITLE
[Efficiency] Avoid H2D copy and stream sync in clip_grad_norm_

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#65110]
https://github.com/pytorch/pytorch/pull/63881#discussion_r709551959

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @cbalioglu @gcramer23

**Comment by awgu** [comment]
I think we got rid of the sync point.
