### ISSUE TITLE
[feature request] Complex multiplication

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#6514]
Currently one can do it manually, but it would be nice to have it in core, since FFT functions have landed.

```python
# for Nx2 tensors
def complex_multiplication(t1, t2):
  real1, imag1 = t1.t()
  real2, imag2 = t2.t()
  return torch.stack([real1 * real2 - imag1 * imag2, real1 * imag2 + imag1 * real2], dim = -1)
```

**Comment by vadimkantorov** [comment]
One verbose way may be a kwarg `complex = True` to `torch.mul`

**Comment by ezyang** [comment]
Related #755

**Comment by vadimkantorov** [comment]
Implemented in master. However, casting (*, 2) float tensors to complex tensors seems not done atm: https://github.com/pytorch/pytorch/issues/33152#issuecomment-599735453
