### ISSUE TITLE
[PyTorch] torch.Tensor and torch.Tensor.dtype have confusing repr

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#6518]
```python
>>> torch.Tensor
<class 'torch.Tensor'>
>>> torch.Tensor.dtype
<attribute 'dtype' of 'torch._C._TensorBase' objects>
```
I expect to at least see `torch.Tensor.dtype` print `torch.float32` by default.

cc @gchanan

**Comment by gchanan** [comment]
`torch.Tensor` is now a class, not an alias of the default tensor type.  This seems fine to me.
