### ISSUE TITLE
How to register a Module as one custom OP when export to onnx

### ISSUE THREAD

**Issue by OYCN** [pytorch/pytorch#65199]
## ❓ How to register a Module as one custom OP when export to onnx

The custom modules may be split to multiple OPs when using `torch.onnx.export`.  In many cases, we can manually optimize these OPs into a custom OP(with a custom node in onnx), and handle it by a plugin in TensorRT. Is there any way to register a Module as one custom OP when export to onnx?

cc @BowenBao @neginraoof

**Comment by hwangdeyu** [comment]
In fact, there is a similar feature that's been done recently. 
You can refer this PR [[ONNX] Export nn.Module call as ONNX local function](https://github.com/pytorch/pytorch/pull/63589), which will be merged into PyTorch master branch a few days later.

**Comment by leimao** [comment]
> In fact, there is a similar feature that's been done recently. You can refer this PR [[ONNX] Export nn.Module call as ONNX local function](https://github.com/pytorch/pytorch/pull/63589), which will be merged into PyTorch master branch a few days later.

@hwangdeyu Thanks. This seems to work. The drawback is, it does not support ONNX Opset version < 15.
