### ISSUE TITLE
Any way to map the node in onnx and the module in pytorch modules?

### ISSUE THREAD

**Issue by zheng-ningxin** [pytorch/pytorch#65192]
## ❓ Questions and Help

Hi~ Is there any way to map the nodes in the onnx.graph(exported by torch.onnx.export) to the modules in the pytorch module(for example, conv). The reason I do this is that I need some additional customized attributes in the module to optimize the execution of onnx, but this information is not included in onnx (this information is not used in inference). 

Look forward to your reply. Thanks

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by bdhirsh** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
