### ISSUE TITLE
[Beta] Avoid register hooks to AccumulateGrad in every FSDP iteration

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#65194]
DDP only registers the grad hook in ctor once, but FSDP registers and removes the hook in every iteration. Explore if it is possible to stablize FSDP hook registration logic to only do it once. 

https://github.com/pytorch/pytorch/blob/af20f2e7b0dc086e825dd621f58885bda18f0f6a/torch/distributed/_fsdp/fully_sharded_data_parallel.py#L1187-L1197

https://github.com/pytorch/pytorch/blob/af20f2e7b0dc086e825dd621f58885bda18f0f6a/torch/distributed/_fsdp/fully_sharded_data_parallel.py#L1365-L1372

cc @zhaojuanmao @mrshenli @rohan-varma

**Comment by awgu** [comment]
I do not think we can register the hook only once because the `AccumulateGrad` object can change. This is just based on empirical evidence.
