### ISSUE TITLE
[Efficiency]  Explicit prefetching data in FSDP

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#65248]
https://github.com/pytorch/pytorch/pull/63881#discussion_r710658887
https://github.com/pytorch/pytorch/pull/63881#discussion_r711302920

cc @zhaojuanmao @mrshenli @rohan-varma

**Comment by rohan-varma** [comment]
@zhaojuanmao is this one done with backward prefetch now?

**Comment by awgu** [comment]
Forward and backward prefetch are in `master`.
