### ISSUE TITLE
Rendered docs (in Dr. CI) failing to appear on recent PR

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65250]
See https://github.com/pytorch/pytorch/pull/65217.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
It happens because bunch of jobs were cancelled, namely https://github.com/pytorch/pytorch/actions/runs/1245921082
Not sure if cancellation reason is recorded somewhere. @seemethere do you know by any chance?

**Comment by seemethere** [comment]
If the docs build job doesn't run then it makes sense that the rendered docs link doesn't appear

**Comment by malfet** [comment]
From engineering point of view it makes total sense, but from UX this behavior is quite confusing, it should probably be surfaced somehow.

**Comment by seemethere** [comment]
I believe the reason why this is happening in the first place is actually a bug in ciflow

![ciflow_error](https://user-images.githubusercontent.com/1700823/134044850-7b2d07da-ad87-4833-9b51-d44c6e42efdc.png)

From: https://github.com/pytorch/pytorch/actions/runs/1245921082

From the above screenshot we can see that this workflow got triggered by a PR un-assign event and subsequently canceled the pull_request triggered workflow here: https://github.com/pytorch/pytorch/actions/runs/1245920328

So it appears as though we're still seeing ciflow related triggering based on PR assign / un-assign even when a user hasn't opted into ciflow

cc @zhouzhuojie

**Comment by seemethere** [comment]
> From engineering point of view it makes total sense, but from UX this behavior is quite confusing, it should probably be surfaced somehow.

I mean what would be the correct UX behaviour in this case?

Having the link be there before the docs are built / pushed could be equally as confusing from a UX perspective.

**Comment by malfet** [comment]
> Having the link be there before the docs are built / pushed could be equally as confusing from a UX perspective.
I think having something like: "Doc builds are in progress, see link-to-run-job" and "Doc builds failed, see link-to-runjob-that-failed", would be great, wouldn't it?

**Comment by seemethere** [comment]
> > Having the link be there before the docs are built / pushed could be equally as confusing from a UX perspective.
> 
> I think having something like: "Doc builds are in progress, see link-to-run-job" and "Doc builds failed, see link-to-runjob-that-failed", would be great, wouldn't it?

Would that have even helped in this case though? Since the entire dependency tree leading up to the docs builds didn't even run

**Comment by seemethere** [comment]
Re-opening since #65354 only solves the technical side of the problem but not necessarily the UX

**Comment by malfet** [comment]
> Would that have even helped in this case though? Since the entire dependency tree leading up to the docs builds didn't even run

I don't know, as I'm not aware how this info is communicated to DrCI, but judging by https://github.com/pytorch/pytorch/runs/3637083293?check_suite_focus=true some bot could have received a notification that workflow was cancelled.

**Comment by mruberry** [comment]
This has been fixed.
