### ISSUE TITLE
`test_load_commit_from_forked_repo` started to fail with "Rate Limit Exceeded"

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#65252]
Have a look at this one for example: https://hud.pytorch.org/commit/bbe25af0df2f2f6a58f6cc4ee5899efcba2ee336
I wonder if this is because all requests to `api.github.com` are tunneled thru the same proxy public IP

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Probably good idea to print remaining GH API rate limit in "Display EC2 information" before running the tests, see https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by seemethere** [comment]
Closed with #65256
