### ISSUE TITLE
zip file serialization endianness detection is broken

### ISSUE THREAD

**Issue by andrewsi-z** [pytorch/pytorch#65300]
## 🐛 Bug

When training and saving a model on a little endian platform, there does not seem to be any "host" endianness attribute carried into the saved model data.
When loaded on a big endian platform, the model parameters are incorrect; that is, the byteorder is not checked and corrected on model load.

## To Reproduce

1. Create a simple model as shown below, and set model weights. 
2. Save model state_dict
3. Load model on big endian platform.
4. Display weights

**Build and set model weights on LE system:**
```
lstm = torch.nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
```
```
print("Model weight weight_ih_l0:")
print(lstm.weight_ih_l0)
Model weight weight_ih_l0:
Parameter containing:
tensor([[ 0.3852,  0.1366,  0.0782],
        [ 0.1975, -0.4888,  0.3619],
        [ 0.0071,  0.3601,  0.4281],
        [-0.4235,  0.4426, -0.3384],
        [-0.2385,  0.4222,  0.1653],
        [-0.2102, -0.2984,  0.1414],
        [-0.0508,  0.5562, -0.1868],
        [ 0.2324, -0.3226, -0.5770],
        [-0.4104,  0.0577,  0.2712],
        [-0.4971,  0.2164,  0.1720],
        [-0.3956, -0.0690,  0.1853],
        [-0.2401, -0.1618, -0.5637]], requires_grad=True)
```
**Copy to big endian system, then load model:**
```
filepath = "lstm.pt"
lstm.load_state_dict(torch.load(filepath),strict=True) 
print(lstm.weight_ih_l0)
tensor([[ 1.4603e-25, -1.5686e-21,  1.2081e-19],
        [-2.6189e-12,  1.5163e+28, -3.3969e+12],
        [ 1.7073e-38,  6.6708e+25, -4.6704e-39],
        [-1.6697e-03, -2.6238e-19, -1.3629e+16],
        [-6.7119e-16, -1.0742e+04, -6.3514e-39],
        [ 5.6304e+19,  4.6716e+20, -1.9736e+27],
        [-1.8113e+29, -6.7717e+25, -9.6834e+26],
        [-1.0278e+37, -2.5245e-12, -9.8826e+10],
        [ 3.4006e-17,  1.4774e-19,  1.0029e-10],
        [-8.1701e+28,  6.6931e-05,  9.2278e-03],
        [-7.8279e+19,  5.4253e-05,  1.5379e+03],
        [-8.6688e+24,  5.1006e-06,  1.1713e-11]], requires_grad=True)
```
**Swap byte order on BE system to confirm:**
```

print("Byteswap state_dict")
for param_tensor in lstm.state_dict():
    print(param_tensor, "\t", lstm.state_dict()[param_tensor].size())
    print(lstm.state_dict()[param_tensor])
    updated = lstm.state_dict()[param_tensor].cpu().detach().numpy().byteswap()
    lstm.state_dict()[param_tensor][:] = torch.Tensor(updated)
    print(lstm.state_dict()[param_tensor])
```
_... trimmed results for readability_
```
tensor([[ 0.3852,  0.1366,  0.0782],
        [ 0.1975, -0.4888,  0.3619],
        [ 0.0071,  0.3601,  0.4281],
        [-0.4235,  0.4426, -0.3384],
        [-0.2385,  0.4222,  0.1653],
        [-0.2102, -0.2984,  0.1414],
        [-0.0508,  0.5562, -0.1868],
        [ 0.2324, -0.3226, -0.5770],
        [-0.4104,  0.0577,  0.2712],
        [-0.4971,  0.2164,  0.1720],
        [-0.3956, -0.0690,  0.1853],
```

## Expected behavior

When a model is loaded on a host with a different byteorder than the platform on which it was saved, any endian sensitive values should be byte swapped as appropriate. 

## Environment

Here is the LE environment:
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.8.11 (default, Aug  6 2021, 08:56:27)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.3.0           hecd8cb5_517  
[conda] mkl-include               2021.3.0           hecd8cb5_517  
[conda] mkl-service               2.4.0            py38h9ed2024_0  
[conda] mkl_fft                   1.3.0            py38h4a7008c_2  
[conda] mkl_random                1.2.2            py38hb2f4e1b_0  
[conda] numpy                     1.20.3           py38h4b4dc7a_0  
[conda] numpy-base                1.20.3           py38he0bd621_0  
[conda] torch                     1.8.3a0+4d34b5b           dev_0    <develop>
[conda] torchvision               0.10.0                   pypi_0    pypi

Here is the BE environment:

Collecting environment information...
PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04 LTS (s390x)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.6 (default, Aug 19 2021, 09:14:36)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-26-generic-s390x-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.1
[pip3] torchvision==0.9.0a0
[conda] _pytorch_select           0.1                       cpu_0  
[conda] numpy                     1.20.3           py39hf741b1c_0  
[conda] numpy-base                1.20.3           py39he2a2902_0  
[conda] pytorch                   1.8.1           cpu_py39h9ddbddd_0  
[conda] torchvision               0.9.0a0                  pypi_0    pypi

## Additional context

If the community considers this a feature request, please convert or I can reoopen as appropriate.

Can anyone help me understand if there is a workaround? I would like to get yolo working in this environment; is it adequate to simply byteswap all dict values that are any precision of float or integer? 
Are there any tools that might be helpful here - even as a starting point for a workaround?

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry

**Comment by andrewsi-z** [comment]
Just a quick note: I was able to successfully load vgg16 using torchvision, using:

`model = models.vgg16(pretrained=True)`

I inspected the weights and compared them to my laptop, they matched my s390x environment (no evidence of byteorder issues). I was able to load some sample images for predictions and the results match exactly as well in both environments. 

As mentioned, I do see the endian issues with the yolov5 and sample models above; is torchvision loading with a different method?

**Comment by ezyang** [comment]
I guess, what you don't say in your original bug report, is how you saved the model weights.

**Comment by ezyang** [comment]
Oh you know what, I wonder if this is new zipfile serialization versus old style serialization

**Comment by driazati** [comment]
iirc the actual tensor serialization didn't change between the pickle format (where tensor storages are saved as a range of bytes after the pickle data) vs zip serialization (where they're a file in the zip archive), they both use https://github.com/pytorch/pytorch/blob/6ecc1a4c4faa48c7a6d416d9c09d1bc4b92ed2df/torch/csrc/generic/serialization.cpp via `storage._write_file` which should be mitigating this, but this isn't tested anywhere I know of

A simple test would be to `torch.save(m.state_dict(), "file.pt", _use_new_zipfile_serialization=False)` and see if that has the same issue (I don't have any BE environment to test in, @andrewsi-z can you try it out?)

**Comment by andrewsi-z** [comment]
Sorry for leaving that out @ezyang ! The minimal example above is saved as follows: torch.save(lstm.state_dict(), filepath)

@driazati I will try this today and report back, thank you

**Comment by andrewsi-z** [comment]
I've tested a set of additional models and see no other portability issues when specifying _use_new_zipfile_serialization=False on LE platform save. 

@driazati thank you, this is a better workaround too then what we planned.

**Comment by driazati** [comment]
glad it works! I've edited the issue a bit since I'd still like to eventually investigate why zipfile serialization doesn't work here

**Comment by xuhdev** [comment]
One observation I made is that hardcoding this line to be either big endian or small endian doesn't change result: https://github.com/pytorch/pytorch/blob/588c1787ba0b1a7d7f698a326afc22f78aac2d25/torch/csrc/utils/byte_order.cpp#L121

(Model file is saved on x86 with untouched PyTorch. Hardcoding happens on s390x when loading the model file.)

This makes me wondering whether the new zip serialization code actually runs through the endianness handling code...

**Comment by xuhdev** [comment]
I did more experiments and found that `THPStorage_(readFileRaw)` is only called when zip serialization is not used: https://github.com/pytorch/pytorch/blob/a3bbaf227cc549c49245e310f11788b98eef30ee/torch/csrc/generic/serialization.cpp#L91

I'm not sure where zip serialization code actually locates. If we have more information, we might have an idea of how endianness is handled when zip serialization is used.

**Comment by tehbone** [comment]
I have done some investigation of this and it appears that when zipfile serialization is in use the tensor's storage is allocated via the `MapAllocator` and thus the storage is directly mmap'd from the file. In that particular path, the endianness is effectively ignored.

**Comment by tehbone** [comment]
I would like to take a stab at it, but I wanted to confirm possible approaches before doing anything. The way I see it, there are a few problems:
1. The endianness of the platform used to save the file is not in the new zipfile format. I don't think this is crucial if it is just assumed that the tensor storage will be little endian on disk. On the flip side, if it is saved it could allow for saved models to be loaded efficiently if the endianness matches.
2. I see many comments how `TypedStorage` is deprecated in favor of `UntypedStorage`. In the case of the latter, the dtype is not saved with the storage, which is needed to perform the byte swapping. My thinking is that the dtype of the `Tensor` can be used in such instances but I'm a little shaky on whether or not it is a valid constraint that all Tensors pointing to a Storage must have the same dtype.
3. As I mentioned in my previous comment the storage is loaded via a `MapAllocator` - modifying the tensor storage as a part of the load may result in additional unnecessary IO in such instances. My thinking here was that if there is a difference in endianness to allocate the storage similarly to how the legacy loader does it.

Any thoughts here?

**Comment by kurtamohler** [comment]
I wonder if #92831 may be related to this issue. The endianness arguments to `THP_decode*Buffer()` functions doesn't actually correspond to endianness, rather `THP_LITTLE_ENDIAN` actually means "decode without a byte swap" and `THP_BIG_ENDIAN` means "decode with a byte swap" (some more details: https://github.com/pytorch/pytorch/pull/92834#pullrequestreview-1270042561)

**Comment by tehbone** [comment]
It could be, but fromBuffer is not invoked with the zip file serialization - but it could be identifying a potential issue with the legacy loading which does use fromBuffer.

**Comment by kurtamohler** [comment]
Ah I didn't realize it isn't invoked, makes sense

**Comment by ezyang** [comment]
A few responses:

1. Yes, we should standardize on an endianness on disk, and just assume it is that endianness (with maybe a utility for "fixing" zips that are saved with the wrong endianness.) Do whatever is standard here
2. Yes, untyped storage is trouble. In fact, it is possible to have two tensors pointing to the same storage, e.g., a byte tensor and an int tensor, and then in fact it is impossible to accurately represent the view relationship if the system endianness is not right. @kurtamohler, this is something we didn't think about when doing serialization here. Fortunately, for the longest time, we just didn't support mixed dtype tensor view on same storage. @kurtamohler I feel like what we should do here, is not allow mixed dtype serialization if it would cause endianness to become observable. For common cases like a float view of complex tensor, there is no problem here.

**Comment by tehbone** [comment]
Pardon my ignorance here, but in what cases would I expect to see UntypedStorage? In my rather limited testing, I observed only TypeStorage being saved.

**Comment by ezyang** [comment]
I think the way we setup the code for BC, you only end up with an untyped storage in the cross-dtype view serialization situation

**Comment by tehbone** [comment]
You can ignore my earlier comment about `MapAllocator`. I was following along with the code incorrectly and landed upon the wrong path. The zipfile serialization defined by `get_storage_from_record` in `torch/csrc/jit/python/init.cpp` seems to be the culprit on the loading side of things. I hope to have a PR soon after I perform some more testing.
