### ISSUE TITLE
[pytorch] Installation from source bug

### ISSUE THREAD

**Issue by minasyan** [pytorch/pytorch#6530]
I want to install the current repo version of pytorch to use multivariate_normal and other similar distributions. Following the instructions for mac (I have macOS Sierra, so 10.12) I ran the following command after cloning the repo and cd-ing into it:

`MACOSX_DEPLOYMENT_TARGET=10.12 CC=clang CXX=clang++ python3 setup.py install
`

The command runs for a while, then starts building all the cpp files (from the /torch/csrc/ directory mainly). I've run this many times already and it almost always gets stuck when building the file /torch/csrc/autograd/functions/tensor.cpp. Here is the output that indicates the build of that file (nothing happens for a very long time after this output and I have to interrupt the command):

`clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/minasyan03/pytorch -I/Users/minasyan03/pytorch/torch/csrc -I/Users/minasyan03/pytorch/third_party/pybind11/include -I/Users/minasyan03/pytorch/torch/lib/tmp_install/include -I/Users/minasyan03/pytorch/torch/lib/tmp_install/include/TH -I/Users/minasyan03/pytorch/torch/lib/tmp_install/include/THNN -I/Users/minasyan03/pytorch/torch/lib/tmp_install/include/ATen -I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/Users/minasyan03/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c torch/csrc/autograd/functions/tensor.cpp -o build/temp.macosx-10.12-x86_64-3.6/torch/csrc/autograd/functions/tensor.o -D_THP_CORE -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-zero-length-array -fno-strict-aliasing -Wno-missing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED`

**Comment by zou3519** [comment]
How long has it taken?

**Comment by minasyan** [comment]
I've followed around 20 minutes of it being stuck at this exact part (building tensor.cpp), but it's been longer than that counting my laptop going to sleep in between. Should I wait more? Does the installation work for you?

**Comment by albanD** [comment]
If you hit enter in that state, does it give you back a command line? Or do you have to hit ctrl-C to stop it?

It could be that an error occurred earlier but the multithreaded build printed stuff after the error?

**Comment by albanD** [comment]
The build system has largely changed since then. Please re-open if this still happens with the current version.
