### ISSUE TITLE
How to get the same RandomResizedCrop result of img and gt

### ISSUE THREAD

**Issue by HaoRan-hash** [pytorch/pytorch#65312]
my code snippet is below
![TIM图片20210919214656](https://user-images.githubusercontent.com/54461374/133929974-1baa0031-3562-45ea-95b9-68555206a1eb.png)
![TIM图片20210919214702](https://user-images.githubusercontent.com/54461374/133929964-acf0cb30-dbeb-4d6e-934e-b5af92b00d5d.png)

Now ,the img ,gt do different RandomResizedCrop. But I want they do the same, because the img and gt must be correspond.
How should I modify the code?

**Comment by G-4-R-Y** [comment]
Have you tried defining a random seed?

![image](https://user-images.githubusercontent.com/23420810/133937553-ce50afff-6efb-49ce-a0ef-67e829c53810.png)

**Comment by ptrblck** [comment]
Double post from the [forum](https://discuss.pytorch.org/t/how-to-get-the-same-randomresizedcrop-result-of-img-and-gt/132349) with a link to a working approach using the functional `torchvision.transforms` API.

**Comment by HaoRan-hash** [comment]
Thank you @ptrblck. I have an another question below.
![屏幕截图 2021-09-21 001147](https://user-images.githubusercontent.com/54461374/134036627-85b0f2c7-f44a-4d5f-b81b-579a418704ac.jpg)
![屏幕截图 2021-09-21 001219](https://user-images.githubusercontent.com/54461374/134036658-3b449509-c355-431e-a949-3acabdad49c9.jpg)
![屏幕截图 2021-09-21 001234](https://user-images.githubusercontent.com/54461374/134036671-82164ca2-bb6e-4b11-a18d-ac3dfaafba6e.jpg)

transforms seems not to work, does it have bugs?
my pytorch version is 1.7.1, torchvision version is 0.8.2.

**Comment by ptrblck** [comment]
Based on the error it seems you are not following the [tutorial](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) for object detection and are thus not using [`references/detection/transforms.py`](https://github.com/pytorch/vision/blob/74ac47e3c3944be1e91281cb9685f907d9177512/references/detection/transforms.py).
Please use the [forum](https://discuss.pytorch.org/) to discuss such issues.

**Comment by HaoRan-hash** [comment]
@ptrblck Thank you.
