### ISSUE TITLE
avg_pool2d cannot be traced if kernel_size is determined by input

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#65320]
## 🐛 Bug
We defined a float model and tried to quantize it to int8 by FX. The model has a layer of `torch.nn.function.avg_pool2d`. The argument `kernel_size` is determined by input `x`. Then this `avg_pool2d` cannot be traced. It would raise an error: `argument 'kernel_size' must be tuple of ints, not tuple`.

Is this a bug or by design? If it's by design, is there any workarounds or other ways to quantize such a model? Thanks!

**This issue is seen when quantizing the model DPN68 by FX.**

## To Reproduce
Run the following python code:
```python
import torch
from torch import nn
import torch.nn.functional as F
from torch.quantization import get_default_qconfig
from torch.quantization.quantize_fx import prepare_fx, convert_fx

class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 16, kernel_size=3)

    def forward(self, x):
        x = self.conv(x)
        x = F.avg_pool2d(x, kernel_size=(x.size(2), x.size(3)))
        return x

float_model = M()

float_model.eval()
qconfig = get_default_qconfig("fbgemm")
qconfig_dict = {"": qconfig}

def calibrate(model, data_loader):
    model.eval()
    with torch.no_grad():
        for image, target in data_loader:
            model(image)

prepared_model = prepare_fx(float_model, qconfig_dict)  # fuse modules and insert observers
#calibrate(prepared_model, data_loader_test)  # run calibration on sample data
quantized_model = convert_fx(prepared_model)  # convert the calibrated model to a quantized model
```

## Expected behavior
No errors.

## Environment
PyTorch version: 1.10.0a0+gita9c3567
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 8 (x86_64)
GCC version: (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: glibc-2.17

Python version: 3.7.10 (default, Jun  4 2021, 14:48:32)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.0-intel-next-04535-g391f7252b851-x86_64-with-centos-8.4.2105
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.10.0a0+gitf5f4a44
[pip3] torchvision==0.11.0a0+8541c21
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py37h27cfd23_1
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.1            py37ha9443f7_2
[conda] mypy_extensions           0.4.3                    py37_0
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] torch                     1.10.0a0+gitf5f4a44          pypi_0    pypi
[conda] torchvision               0.11.0a0+8541c21          pypi_0    pypi

## Additional context
None

cc @ezyang @SherlockNoMad

**Comment by byronyi** [comment]
Try use `torch.nn.functional.adaptive_avg_pool2d(x, 1, 1)` instead.

**Comment by Xia-Weiwen** [comment]
Kernel size is determined by input not fixed as 1x1 in model **DPN68**. This model cannot be quantized by FX with this issue.

**Comment by Xia-Weiwen** [comment]
This is a known issue or known drawback of FX. I guess it won't be fixed in short term. It can be bypassed by `torch.nn.functional.adaptive_avg_pool2d(x, 1, 1)`.
So, close it now.
