### ISSUE TITLE
`conda install` from pytorch-nightly channel installs CPU version even from a clean environment.

### ISSUE THREAD

**Issue by dlangerm** [pytorch/pytorch#65338]
## 🐛 Bug

Clean python 3.9 environment fails to install GPU version of pytorch when running the following:

`conda install pytorch torchvision -c pytorch-nightly -c conda-forge`

Happens on both windows and Linux. 

## To Reproduce

1. Run `conda install pytorch torchvision -c pytorch-nightly -c conda-forge` on python==3.9 environment, observe cpuonly version being installed

## Expected behavior

GPU version of pytorch is installed as expected

## Environment

 - PyTorch Version: Attempted 1.10
 - OS (e.g., Linux): Linux/Windows
 - How you installed PyTorch (`conda`, `pip`, source): Conda
 - Python version: 3.9
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: RTX 3090, A100

**Comment by ptrblck** [comment]
The [install instructions](https://pytorch.org/get-started/locally/) show:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch-nightly -c nvidia
```
as the install command for the nightly with the CUDA11.1 runtime, so could you replace the `conda-forge` channel with `nvidia`? (I was running into the same issue last week)

**Comment by soulitzer** [comment]
Closing since this sounds like it is expected? The instructions indeed say to use the `nvidia` channel. Feel free to reopen if I'm missing something.

**Comment by VarunGumma** [comment]
I am trying to install the the latest nightly version with the command `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch-nightly -c nvidia`, but it installs the `cpu` version rather than the `cuda` version. Any leads on this?

**Comment by InnovArul** [comment]
Try installing via `pip`:
```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
```
