### ISSUE TITLE
[docs] Some activation functions are missing images

### ISSUE THREAD

**Issue by rodrigoberriel** [pytorch/pytorch#65368]
## 📚 Documentation

In #5457, images were introduced in the pages of each activation functions. Now, there are a few of them that are missing their images:
- [`RReLU`](https://pytorch.org/docs/master/generated/torch.nn.RReLU.html)
- [`Hardsigmoid`](https://pytorch.org/docs/master/generated/torch.nn.Hardsigmoid.html)
- [`Hardswish`](https://pytorch.org/docs/master/generated/torch.nn.Hardswish.html)
- [`SiLU`](https://pytorch.org/docs/master/generated/torch.nn.SiLU.html)
- [`Mish`](https://pytorch.org/docs/master/generated/torch.nn.Mish.html)

Three of them are already in the [`build_activation_images.py`](https://github.com/pytorch/pytorch/blob/master/docs/source/scripts/build_activation_images.py). So, the fix is really simple: add the other two to the script and fix the docstrings of all these 5 functions.

If this is of interest, I could send this PR: https://github.com/rodrigoberriel/pytorch/commit/aee963c990a26aa14646c22de11d6921ecea22ea

Lastly, I didn't change it, but I guess we could remove the line below, because of [this discussion](https://github.com/pytorch/pytorch/pull/5457#discussion_r171445192) in #5457. If so, I can update when sending the PR.

https://github.com/pytorch/pytorch/blob/2abf3594d519340c8368a24e7407c69b7b52bc60/docs/source/scripts/build_activation_images.py#L49

I didn't open the PR directly because I guess this is the correct workflow. Please, let me know if I need to open an issue for this kind of straightforward doc change.

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @SsnL

**Comment by mruberry** [comment]
Issues are always helpful but not required, it'd be great to fix the docs!

Thanks for filing this issue and offering to follow-up, @rodrigoberriel!
