### ISSUE TITLE
[license] license problem of torch/lib/TH/THHalf.c

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#654]
When performing license check on Pytorch debian package I found this license problem:

https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/THHalf.c

License of Pytorch is BSD-3-Clause, however THHalf.c is non-free according to its header.

**Comment by Maratyszcza** [comment]
A possible replacement can be found in [this header](https://github.com/Maratyszcza/NNPACK/blob/master/include/nnpack/fp16.h) in NNPACK (BSD-3 licensed).

**Comment by CDLuminate** [comment]
Actually NVIDIA's copyright declaration in THHalf.c makes it impossible for Pytorch to enter the main section of Debian archive. To promote https://github.com/pytorch/pytorch/issues/644 to official package, we should have copyright problems done at first.

**Comment by cliffwoolley** [comment]
We're working on getting this cleared -- sorry for the inconvenience.

**Comment by cliffwoolley** [comment]
https://github.com/torch/torch7/pull/922

**Comment by CDLuminate** [comment]
Marking as done since https://github.com/torch/torch7/pull/922 was merged.

**Comment by CDLuminate** [comment]
It's my bad. The fix entered torch/torch7 but is still not synced into pytorch.

**Comment by cliffwoolley** [comment]
Did you want me to patch pytorch separately?  I figured the file can now be
copied over from torch by anyone.

**Comment by soumith** [comment]
i'll sync the subtrees now!

**Comment by CDLuminate** [comment]
Thank you guys.
