### ISSUE TITLE
Build of libtorch_cpu.so is not deterministic due to NNPACK-generated code

### ISSUE THREAD

**Issue by civodul** [pytorch/pytorch#65404]
## 🐛 Bug

As of PyTorch 1.9.0,  builds of `libtorch_cpu.so` on x86_64 GNU/Linux are not [bit-for-bit reproducible](https://reproducible-builds.org/docs/definition/).

## To Reproduce

1. Build PyTorch a first time.
1. Build PyTorch a second time in the exact same conditions (same dependencies, same compiler, same environment variables).

The two `libtorch_cpu.so` files obtained may defer.

## Expected behavior

The two files should be identical.

## Environment

(See below.)

## Additional context

This issue was observed building the `python-pytorch` package of GNU Guix.  As [initially reported](https://issues.guix.gnu.org/50672), investigation suggests that the source of non-determinism has to do with code generated by files such as `NNPACK/src/x86_64-fma/2d-fourier-8x8.py` using PeachPy: the order of symbols such as `nnp_fft8x8_with_offset_and_stream__avx2.__local0` differs between the two different `libtorch_cpu.so` builds (the original report has more details).

cc @malfet @seemethere

**Comment by malfet** [comment]
Thank you for reporting. As the issue in the 3rd party module(NNPACK is PyTorch submodule), I would recommend reporting an issue in https://github.com/Maratyszcza/NNPACK

Also, there is an option to build PyTorch without NNPACK integration, as documented in `setup.py` header
https://github.com/pytorch/pytorch/blob/64d3c7388f3ebb084c6e6998597e94753fde1ffa/setup.py#L53

Can you please try that and let me know if this workaround would make PyTorch builds deterministic

**Comment by civodul** [comment]
Hi @malfet and thanks for your quick reply!

Indeed, having now "unbundled" NNPACK, I can achieve bit-for-bit reproducible builds for PyTorch itself, but not for NNPACK.

I'm closing this issue and will take it to NNPACK.
