### ISSUE TITLE
torch.bmm return wrong result when running on CUDA

### ISSUE THREAD

**Issue by xmeng525** [pytorch/pytorch#65416]
## 🐛 Bug

torch.bmm() return wrong result when running on CUDA

## To Reproduce

Steps to reproduce the behavior: see the sample code

```
import numpy as np
import torch

cuda_id = 0
if cuda_id == -1:
	device = torch.device("cpu")
else:
	device = torch.device("cuda:%d"%cuda_id)
A = torch.Tensor([[
	[   0.0000, -143.2371,    0.0000,    0.0000],
	[-143.2371,    0.0000,    0.0000,    0.0000],
	[   0.0000,    0.0000,   -1.0000,   86.5423],
	[   0.0000,    0.0000,    0.0000,    1.0000]]]).to(device)

B = torch.Tensor([[
	[-0.5000, -0.5000, -0.5000, -0.5000],
	[-0.5000, -0.5000, -0.5000, -0.5000],
	[-0.5000, -0.4980, -0.4961, -0.4941],
	[ 1.0000,  1.0000,  1.0000,  1.0000]]]).to(device)

C = torch.bmm(A, B)
print("C = \n", C)
```
## Expected behavior
with cuda_id = -1  (run on CPU), print the CORRECT result:
```
# C = 
#  tensor([[[71.6186, 71.6186, 71.6186, 71.6186],
#          [71.6186, 71.6186, 71.6186, 71.6186],
#          [87.0423, 87.0403, 87.0384, 87.0364],
#          [ 1.0000,  1.0000,  1.0000,  1.0000]]])`
```

with cuda_id = 0 (run on GPU), print the WRONG result:
```
# C = 
#  tensor([[[0., 0., 0., 0.],
#          [0., 0., 0., 0.],
#          [0., 0., 0., 0.],
#          [0., 0., 0., 0.]]], device='cuda:0')
```
## Environment

PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.12.1
Libc version: glibc-2.23

Python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-47-generic-x86_64-with-glibc2.23
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 465.19.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0+cu111
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] liblapacke                3.9.0                     8_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.21.2           py39hdbf815f_0    conda-forge
[conda] torch                     1.8.0+cu111              pypi_0    pypi
[conda] torchaudio                0.8.0                    pypi_0    pypi
[conda] torchvision               0.9.0+cu111              pypi_0    pypi

**Comment by soulitzer** [comment]
Thanks for your report and the repro. I could not replicate on either 1.9 (Colab) or master, however. Could you upgrade your PyTorch and try again?

Closing for now. Feel free to reopen if it still happens even after upgrading.
