### ISSUE TITLE
Do not print sccache stats on tests/failed builds

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#65431]
When build fails, `sccache` stats are not relevant
And any time during the testing they are not relevant either (or perhaps should not even been used)

sccache stats output can be found using:
```
❯ rg '\--show-stats' .jenkins
.jenkins/pytorch/build.sh
252:      sccache --show-stats
254:      sccache --show-stats | python -m tools.stats.upload_sccache_stats

.jenkins/pytorch/win-test-helpers/build_pytorch.bat
138:python setup.py install --cmake && sccache --show-stats && (
154:sccache --show-stats > stats.txt

.jenkins/pytorch/common.sh
101:      sccache --show-stats
110:    ccache --show-stats
112:      ccache --show-stats

.jenkins/caffe2/build.sh
50:    "$SCCACHE" --show-stats

.jenkins/pytorch/win-test-helpers/installation-helpers/install_sccache.bat
5:  %TMP_DIR_WIN%\bin\sccache.exe --show-stats || (
```

Ideally this would mean only adding the `trap` command here when running a build job and not a test job:

https://github.com/pytorch/pytorch/blob/7e5aa0d35a540807d524966e118d1ead4d3b2eae/.jenkins/pytorch/common.sh#L104

cc @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by hudsonmendes** [comment]
Dear @malfet - if you give me a bit more information, I could possibly look into this one?
Just how this error shows up in the build failure would be sufficient, much appreciated.

**Comment by IvanYashchuk** [comment]
Fixed with https://github.com/pytorch/pytorch/commit/6f0a1f2b8dccc7d734c912768cffcd010b930c1a
