### ISSUE TITLE
Checkout PyTorch failures

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#65437]
New issue, looks different from the previous submodule timeouts:
```
  Error: fatal: Unable to create '/home/ec2-user/actions-runner/_work/pytorch/pytorch/.git/modules/third_party/benchmark/index.lock': File exists.
  
  Another git process seems to be running in this repository, e.g.
  an editor opened by 'git commit'. Please make sure all processes
  are terminated then try again. If it still fails, a git process
  may have crashed in this repository earlier:
```

Examples:
- https://github.com/pytorch/pytorch/runs/3669429651
- https://github.com/pytorch/pytorch/runs/3669425388
- https://github.com/pytorch/pytorch/runs/3669364701
- https://github.com/pytorch/pytorch/runs/3669255435
- https://github.com/pytorch/pytorch/runs/3669255254
- https://github.com/pytorch/pytorch/runs/3669175999
- https://github.com/pytorch/pytorch/runs/3669162432
- 
cc @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
To add to that list: https://github.com/pytorch/pytorch/pull/65435/checks?check_run_id=3669477898
And all of the logs have the same pattern:
```
Machine name: 'ip-10-0-0-184'
```
@seemethere can you please manually kick this machine from the pool?

**Comment by seemethere** [comment]
This machine already got reaped, in the future anyone with access to the fbossci pool should be able to terminate instances like these with the CLI like:

```bash
# aws terminate-instances --instance-ids <instance id>
aws terminate-instances --instance-ids i-04f0d80329752862c
```

**Comment by malfet** [comment]
Thank you for confirming. Wasn't sure if its safe to kill the machine like that.

**Comment by seemethere** [comment]
> Thank you for confirming. Wasn't sure if its safe to kill the machine like that.

Yup should be safe, worst thing that'll happen is that it'll fail out for whatever job it's currently executing

**Comment by seemethere** [comment]
Ephemeral runners has launched so this should be safe to close, will re-open if we notice these issues popping up again
