### ISSUE TITLE
PyTorch dockerfile failed to build

### ISSUE THREAD

**Issue by sjiang17** [pytorch/pytorch#6544]
- PyTorch or Caffe2: PyTorch
- OS: Mac 10.13.4
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source):
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

I have tried to build a docker image with
`git clone https://github.com/pytorch/pytorch.git`
and
`docker build -t pytorch-gpu -f docker/pytorch/Dockerfile .`

The build failed with the following msg:

......
    [ 18%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorConv.cu.o
    [ 18%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorRandom.cu.o
    [ 19%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorScatterGather.cu.o
    [ 19%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorTopK.cu.o
    [ 19%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorSort.cu.o
    [ 19%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorTypeUtils.cu.o
    [ 19%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCSortUtils.cu.o
    [ 20%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/__/THC/ATen_generated_THCTensorMode.cu.o
The command '/bin/sh -c TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all"     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     pip install -v .' returned a non-zero code: 137

Has anyone encountered the same problem & is there any solution?
Thank you!

**Comment by apaszke** [comment]
137 means that the process received a `SIGKILL` signal, which happens if you you e.g. run out of memory. How much RAM do you have in your machine?

**Comment by apaszke** [comment]
Also, you can try some of the workarounds proposed here (increase the threshold for max mem use in Docker): https://github.com/moby/moby/issues/21083

**Comment by sjiang17** [comment]
Thank you
