### ISSUE TITLE
Pytorch Distributed RPC crash with Tensorpipe in 1.9.0 (regression): Cannot extract tensors from value: RuntimeError: Can not pickle rref in python pickler, rref can only be pickled when using RPC

### ISSUE THREAD

**Issue by jeremysalwen** [pytorch/pytorch#65450]
## 🐛 Bug

This is a **crash** which is now occurring in pytorch 1.9.0, but was not present in a previous dev version of 1.9.  The crash occurs when using RRefs with TensorPipe as a backend with device_map.  

I have included a completely self contained minimal reproduction.

## To Reproduce

```
import os
import unittest

from torch import multiprocessing
from torch.distributed import rpc
from torch.distributed.rpc import RRef


def rpc_backed_options():
    device_maps = {
        'simulator': {0: 0},
        'inference': {0: 0}
    }
    return rpc.TensorPipeRpcBackendOptions(device_maps=device_maps)


def run_worker(rank, num_workers: int):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '29500'
    rpc.init_rpc('simulator', rank=rank + 1, world_size=num_workers + 1, rpc_backend_options=rpc_backed_options())
    rpc.shutdown()


class ContainsRRef:
    def __init__(self, rref):
        self.rref = rref

    def foo(self):
        pass


class PytorchDistributedTests(unittest.TestCase):

    def test_rpc_with_rref(self):
        os.environ['MASTER_ADDR'] = 'localhost'
        os.environ['MASTER_PORT'] = '29500'

        self.process_context = multiprocessing.start_processes(
            run_worker,
            args=(1,),
            nprocs=1,
            start_method="forkserver",
            join=False
        )
        local_object = {}
        rpc.init_rpc('inference', rank=0, world_size=2, rpc_backend_options=rpc_backed_options())
        sim_info = rpc.get_worker_info('simulator')
        remote_object = rpc.remote(sim_info, ContainsRRef, args=(RRef(local_object),))
        remote_object.rpc_async().foo()


if __name__ == '__main__':
    unittest.main()
```

Stack Trace:
```
On WorkerInfo(id=1, name=simulator):
RuntimeError('Cannot extract tensors from value: RuntimeError: Can not pickle rref in python pickler, rref can only be pickled when using RPC\n\nAt:\n  /home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/_jit_internal.py(1157): _extract_tensors\n')
Traceback (most recent call last):
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/internal.py", line 210, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/api.py", line 366, in _rref_typeof_on_owner
    rref_type = type(rref.local_value())
RuntimeError: Cannot extract tensors from value: RuntimeError: Can not pickle rref in python pickler, rref can only be pickled when using RPC

At:
  /home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/_jit_internal.py(1157): _extract_tensors



Error
Traceback (most recent call last):
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/tests/pytorch/distributed/test_rpc_rref.py", line 51, in test_rpc_with_rref
    remote_object.rpc_async().foo()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/rref_proxy.py", line 18, in _invoke_rpc
    rref_type = rref._get_type(timeout=timeout)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/api.py", line 386, in _rref_typeof_on_user
    return fut.wait()
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/internal.py", line 224, in _handle_exception
    raise result.exception_type(result.msg.encode("utf-8").decode("unicode_escape"))
RuntimeError: On WorkerInfo(id=1, name=simulator):
RuntimeError('Cannot extract tensors from value: RuntimeError: Can not pickle rref in python pickler, rref can only be pickled when using RPC

At:
  /home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/_jit_internal.py(1157): _extract_tensors
')
Traceback (most recent call last):
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/internal.py", line 210, in _run_function
    result = python_udf.func(*python_udf.args, **python_udf.kwargs)
  File "/home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/distributed/rpc/api.py", line 366, in _rref_typeof_on_owner
    rref_type = type(rref.local_value())
RuntimeError: Cannot extract tensors from value: RuntimeError: Can not pickle rref in python pickler, rref can only be pickled when using RPC

At:
  /home/jeremy/PycharmProjects/hearthstone_battlegrounds/venv/lib/python3.9/site-packages/torch/_jit_internal.py(1157): _extract_tensors
```

## Expected behavior
Expected no crash.

## Environment

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9.1+ (default, Jan 20 2021, 14:49:22)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-4.19.0-11-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 960
Nvidia driver version: 440.33.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @gcramer23

**Comment by SciPioneer** [comment]
Have you tried it on 1.9.1?

@mrshenli  @lw

**Comment by lw** [comment]
On one hand, I am surprised that this crash only occurs if you set a `device_map`. On the other hand, however, we don't currently officially support RRefs when using CUDA mode in RPC (see our docs), hence such "rough edges" are not unexpected.

**Comment by mrshenli** [comment]
cc @pbelevich

**Comment by jeremysalwen** [comment]
Reproduced in 1.9.1.  FWIW removing the `device_map` option does work as a workaround.

(I am a little confused about the broader context of Pytorch RPC supporting CUDA, but "not with RRefs".  I thought RRefs were an integral part of the api, e.g. in `rpc.remote()`.  There isn't even experimental support for this?).

**Comment by mrshenli** [comment]
Hey @jeremysalwen, IIUC this is caused by two things:

1. `CUDAFuture` used by the owner RRef needs to pickle the object (`ContainsRRef `) to extract tensors
2. RRef cannot be pickled outside of an RPC call. 

I believe this is already fixed on master by adding special handling for RRef. I tried it locally and it works (after adding a `rpc.shutdown()`).

To unblock you on v1.9.0, could you please try adding the `__getstate__` method to `PytorchDistributedTests`?

```python
class ContainsRRef:
    def __init__(self, rref):
        self.rref = rref

    def foo(self):
        pass

    def __getstate__(self):
      # explicitly skipping pickling RRef
      return {}
```

**Comment by pbelevich** [comment]
@jeremysalwen, I can confirm that it's already fixed in master, would you mind to use nightly build until 1.10 is released with the fix?
```
conda install pytorch cudatoolkit=10.2 -c pytorch-nightly
```

**Comment by lw** [comment]
> I am a little confused about the broader context of Pytorch RPC supporting CUDA, but "not with RRefs". I thought RRefs were an integral part of the api, e.g. in rpc.remote(). There isn't even experimental support for this?

RPC has several features, the most basic one being just remote execution, which is where CUDA is officially supported. RRefs and dist autograd and async execution etc. are other non-core features where we've observed issues with CUDA which we haven't yet fixed.

**Comment by jeremysalwen** [comment]
Yes, confirmed that this bug is fixed on the latest nightly.
