### ISSUE TITLE
[Caffe2] Error while run the test code, 'python caffe2/python/operator_test/relu_op_test.py'.

### ISSUE THREAD

**Issue by ayumiymk** [pytorch/pytorch#6546]
- Caffe2:
- OS: Ubuntu 16.04
This is my cmake summary:

-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.8.1-1500-g0dd3284
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   :
--
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : OFF
--     Protobuf compiler   :
--     Protobuf includes   :
--     Protobuf libraries  :
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA version        : 8.0
--     CuDNN version       : 6.0.21
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/lib/x86_64-linux-gnu/libcuda.so
--     CUDA NVRTC library  : /usr/local/cuda/lib64/libnvrtc.so
--     CUDA runtime library: /usr/local/cuda/lib64/libcudart.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               :
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.9.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mkyang/caffe2/build

I successfully passed `python -c "from caffe2.python import core"`. But when I test `python2 caffe2/python/operator_test/relu_op_test.py`. There are some errors as follows:

Trying example: test_relu(self=<__main__.TestRelu testMethod=test_relu>, X=array([0.], dtype=float32), gc=, dc=[, device_type: 1], engine=u'')
E0412 16:41:51.498246 24884 operator.cc:114] Cannot find operator schema for . Will skip schema checking.
Traceback (most recent call last):
  File "/home/mkyang/.local/lib/python2.7/site-packages/hypothesis/core.py", line 663, in evaluate_test_data
    result = self.execute(data, collect=True)
  File "/home/mkyang/.local/lib/python2.7/site-packages/hypothesis/core.py", line 578, in execute
    result = self.test_runner(data, run)
  File "/home/mkyang/.local/lib/python2.7/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/home/mkyang/.local/lib/python2.7/site-packages/hypothesis/core.py", line 574, in run
    return test(*args, **kwargs)
  File "caffe2/python/operator_test/relu_op_test.py", line 19, in test_relu
    engine=st.sampled_from(["", "CUDNN"]),
  File "/home/mkyang/.local/lib/python2.7/site-packages/hypothesis/core.py", line 517, in test
    result = self.test(*args, **kwargs)
  File "caffe2/python/operator_test/relu_op_test.py", line 27, in test_relu
    self.assertGradientChecks(gc, op, [X], 0, [0])
  File "/home/mkyang/caffe2/build/caffe2/python/hypothesis_test_util.py", line 390, in assertGradientChecks
    input_device_options=input_device_options
  File "/home/mkyang/caffe2/build/caffe2/python/gradient_checker.py", line 269, in CheckSimple
    outputs_with_grads
  File "/home/mkyang/caffe2/build/caffe2/python/gradient_checker.py", line 186, in GetLossAndGrad
    workspace.RunOperatorsOnce(grad_ops)
  File "/home/mkyang/caffe2/build/caffe2/python/workspace.py", line 169, in RunOperatorsOnce
    success = RunOperatorOnce(op)
  File "/home/mkyang/caffe2/build/caffe2/python/workspace.py", line 164, in RunOperatorOnce
    return C.run_operator_once(StringifyProto(operator))
RuntimeError: [enforce fail at operator.cc:183] op. Cannot create operator of type '' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "Y" input: "Y_grad" output: "X_grad" name: "" type: "" device_option { } engine: "" is_gradient_op: true

What's more, 
`> echo $PATH`
```
/home/mkyang/caffe2/build/caffe2:/home/mkyang/torch/install/bin:/home/mkyang/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/MATLAB/R2015b/bin
```
`> echo $LD_LIBRARY_PATH`
```
/usr/local/cudnn-v6.0-for-cuda8.0/lib64:/home/mkyang/caffe2/build/lib:/home/mkyang/torch/install/lib:/usr/local/lib:/home/mkyang/torch/install/lib:/usr/local/cuda-8.0/lib64
```
`> echo $PYTHONPATH`
```
/home/mkyang/caffe/python:/usr/local:/home/mkyang/caffe2/build
```

I guess this may be caused by the link to cudnn library, but I have added it to `$LD_LIBRARY_PATH`. I have long struggled mightily with this problem, could anyone help me?

**Comment by pjh5** [comment]
Is there a `caffe2` folder in `/home/mkyang/.local/lib/python2.7/site-packages/` ?
If not, is there a `caffe2` folder in `/usr/local/` ?

If there's a `caffe2` folder in both places, then delete the `caffe2` and `caffe` folder in `/usr/local/` .
If there's no `caffe2` in either location then how did you install Caffe2?
If there is a `caffe2` folder in either location then 
- remove `/home/mkyang/caffe2/build/caffe2` from `$PATH`
- remove `/home/mkyang/caffe2/build/lib` from `$LD_LIBRARY_PATH`
- remove `/home/mkyang/caffe/python` and `/home/mkyang/caffe2/build` from `$PYTHONPATH`

Are you using the code in the pytorch repo https://github.com/pytorch/pytorch ?

**Comment by ayumiymk** [comment]
There is no `caffe2` folder in `/home/mkyang/.local/lib/python2.7/site-packages/` and `/usr/local`.
But I find `caffe2` in `/usr/local/include/` and `/usr/local/lib/python2.7/dist-packages/`.

My installation process is:
```
> mkdir build && cd build
> cmake -DCUDNN_INCLUDE_DIR=/usr/local/cudnn-v6.0-for-cuda8.0/include -DCUDNN_LIBRARY=/usr/local/cudnn-v6.0-for-cuda8.0/lib64/libcudnn.so -DUSE_NATIVE_ARCH=ON ..
> sudo make install -j16
```

I try to remove these paths in `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, but still failed with the same errors.

I tried both <https://github.com/caffe2/caffe2> and <https://github.com/pytorch/pytorch>, but the same errors.

**Comment by pjh5** [comment]
Don't use https://github.com/caffe2/caffe2 ; it is no longer updated. Can you verify that this error occurs when you do a clean install on the latest code from https://github.com/pytorch/pytorch ?

Can you post the output of the 'cmake' command?

**Comment by ayumiymk** [comment]
Thanks! I clone the latest code from `pytorch`, and it works. I think I must do something wrong when I compiled it from `pytorch` before.
