### ISSUE TITLE
`torch.nn.functional.kl_div` fails gradgradcheck if the target requires a gradient

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#65466]
## 🐛 Bug

`torch.nn.functional.kl_div` fails gradgradcheck if the target requires a gradient.

## To Reproduce

```python
import torch
from torch.autograd import gradgradcheck
from torch.nn.functional import softmax, log_softmax, kl_div

torch.manual_seed(0)
# input should be log probabilities
input = log_softmax(torch.randn(3, dtype=torch.float64, requires_grad=True))
# target should be probabilities
target = softmax(torch.randn_like(input, requires_grad=True))

gradgradcheck(kl_div, inputs=(input, target))
```

```
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 1,
numerical:tensor([[-0.1344,  0.0000,  0.0000],
        [ 0.0000, -0.1344,  0.0000],
        [ 0.0000,  0.0000, -0.1344]], dtype=torch.float64)
analytical:tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
```

The error only shows up, if the `target` requires a gradient.

## Additional context

- As far as I tried this is not a recent regression. The behavior is the same for `torch==1.8.1`.
- This was detected while adding an `OpInfo` for `kl_div` in #65469.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr

**Comment by nikitaved** [comment]
It is not a bug, the issue is that you create tensors of type `float` rather than `double`.

**Comment by pmeier** [comment]
My bad, I need to recheck why the gradcheck tests failed. They should be run in `float64`.

**Comment by pmeier** [comment]
@nikitaved 

> It is not a bug I guess, the issue is that tensors of type `float` are created, rather than of `double`.

You were right about that. The tests in `test_ops.py` failed, because I used an unreasonable lower limit for the input values. Fixing that, now a `gradgradcheck` error shows up. I've edited the original comment with the new reproduction / error message.

**Comment by nikitaved** [comment]
If gradgrad fails, it could be the issues with the `reduction`.

**Comment by nikitaved** [comment]
OK, looks like the backward to `kl_div` has a custom backward implemented which sets the grad wrt `target` to zero (parameter 1), which, I guess, is wrong as `log` is inf-many times differentiable with non-zero value.

**Comment by Lezcano** [comment]
Note: Interestingly enough, `kl_div_backward` does have the second derivative implemented by hand, but the derivative of wrt the other input `Q`, that is, `kl_div_target_backward` is implicitly differentiable. This is a bit odd.
Given how simple the implementation of the backward is using `TensorIterator`, we could consider implementing the backward and double backward for `kl_div` with it.

**Comment by nikitaved** [comment]
In order to fix that we need to implement `kl_div_backward` which considers `input` and `target` jointly, without the assumption that either of them is a constant, like in this case. Many loss functions suffer for this issue.

**Comment by mruberry** [comment]
@albanD what do you think?

**Comment by albanD** [comment]
> Many loss functions suffer for this issue of having double backward being wrong as the double backward of a forward function is a function that depends on both partial derivatives grad_input and grad_target, not just a single one of them.

I can see individual formulas being wrong but I don't think it is a problem to have the formulas separated out.
You can see the image below where both partial derivative influence properly both inputs inputs.
Or I am missing something?

For example if you do 
```python
import torch
# !pip install torchviz
import torchviz


a = torch.rand(1, 10, requires_grad=True)
t = torch.rand(1, 10, requires_grad=True)

loss = torch.kl_div(a, t).sum()

ga, gt = torch.autograd.grad(loss, (a, t), create_graph=True)

torchviz.make_dot((loss, ga, gt), params={k:v for k,v in locals().items() if isinstance(v, torch.Tensor)})
```

![image](https://user-images.githubusercontent.com/6359743/134509314-85fbc840-15bc-4d0c-917f-be0a4a4f91c2.png)

**Comment by Lezcano** [comment]
fwiw, @pmeier will submit a patch for this later today / tomorrow. We found that having the formulas separated was really the way to go.

On a completely unrelated topic, that's some very cool graph @albanD :D

**Comment by nikitaved** [comment]
@albanD , when only partial derivatives are defined and I want to double backward, the effects of the differentiated backwards will be accumulated, right?

**Comment by albanD** [comment]
@nikitaved each backward formula is only responsible to provide the gradient flowing through the forward function they define. If some other function is also using target, then this other function is responsible for computing that part of the gradient.

> the engine does accumulate grads from the backwards of partial derivatives

Yes, if a variable is re-used multiple times, the engine will make sure that the gradients from all the usage are added before processing more.
In the graph above, you can see 3 arrows coming out of t's AccumulateGrad Node. That's because it is used by 3 different functions.
Most of the complexity of the execution engine is to actually know how many of these arrows we should expect gradients from for a given backward() call and accumulate them properly.
