### ISSUE TITLE
Bug: torch.matmul() on gpu (torch version 1.9.0+cu102)

### ISSUE THREAD

**Issue by ggjy** [pytorch/pytorch#65479]
## To Reproduce

1. import torch
2. a = torch.Tensor(size=(1, 3)).cuda()
1. b = torch.Tensor(size=(2, 4)).cuda()
1. print(torch.matmul(a,b))

## Expected behavior

On GPU:
![image](https://user-images.githubusercontent.com/24435864/134392187-6e503309-8edb-46af-a2eb-310dae52f1c3.png)

But it's normal on CPU:
![image](https://user-images.githubusercontent.com/24435864/134392050-448f00e8-bf4c-494f-a73c-1b426c402610.png)

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (1.9.0+cu102):
 - OS (Linux):
 - How you installed PyTorch (`pip`):
 - Build command you used (if compiling from source):
 - Python version: 3.6.2
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ngimel** [comment]
Fixed on master and 1.9.1
