### ISSUE TITLE
[PyTorch] Dataloader should prefetch a specified number of samples

### ISSUE THREAD

**Issue by Rikorose** [pytorch/pytorch#6547]
Also the number of samples to prefetch may be bigger then one epoch.

I am currently working with small datasets (~500 samples) and a high batch size (64 - 128). This results in a large time for loading the first batch (~1 s) of each epoch where all later batches need about 10 ms.

**Comment by SsnL** [comment]
It prefetches already. The prefetching starts at `iter(loader)`.

With such a small dataset... You might be better off just using TensorDataset and 0 workers,
