### ISSUE TITLE
nn.functional.upsample  returns a Variable when input is a tensor

### ISSUE THREAD

**Issue by Naruto-Sasuke** [pytorch/pytorch#6550]
- PyTorch or Caffe2: Pytorch
- OS: Ubuntu14.04
- PyTorch version: 0.3.1_post2
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 8.0/7.0
- GPU models and configuration: No models
- GCC version (if compiling from source): 4.9
- CMake version: 3.9.4

```python
import torch
import torch.nn.functional as F
a = torch.randn(100,100)
F.upsample(a.view(1,1,100,100), (100,100), mode='bilinear')
```

**Comment by soumith** [comment]
in 0.3.1 this is expected, as `torch.nn.*` is expected to work only on Variables. On `master` branch, Tensor and Variable are merged, so this is no longer relevant.
