### ISSUE TITLE
Question about NCCL backend in torch.distributed documentation

### ISSUE THREAD

**Issue by vycezhong** [pytorch/pytorch#65525]
## ❓ Questions and Help

https://pytorch.org/docs/stable/distributed.html

The document says that `send` and `recv` are not supported for `nccl` on GPUs. But there is already this part of the implementation code and it can work. Is this part of documentation outdated? 

![image](https://user-images.githubusercontent.com/25879526/134487286-e1b26452-8f0d-40fd-85cd-b549d6ee9f45.png)

https://github.com/pytorch/pytorch/blob/dfbd030854359207cb3040b864614affeace11ce/torch/lib/c10d/ProcessGroupNCCL.hpp#L292-L300

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @gcramer23

**Comment by SciPioneer** [comment]
Good observation! I believe the doc is outdated, and I have created a PR to update the doc. Thanks!
