### ISSUE TITLE
tensordot with dims=0 throws

### ISSUE THREAD

**Issue by mganahl** [pytorch/pytorch#65524]
## 🐛 Bug
`torch.tensordot` raises an exception when trying to compute an outer product with `dims=0`.

## To Reproduce
import torch
import numpy as np

a = torch.Tensor(np.random.rand(2,2))
b = torch.Tensor(np.random.rand(2,2))
torch.tensordot(a,b,dims=0) #raises, but should just compute the outer product
## Expected behavior
return the outer product, see for example `numpy.tensordot`.

## Environment

PyTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.2
Libc version: N/A

Python version: 3.9.1 (default, Dec 28 2020, 11:25:16)  [Clang 12.0.0 (clang-1200.0.32.28)] (64-bit runtime)
Python platform: macOS-11.6-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.1
[conda] Could not collect

cc @mruberry @rgommers

**Comment by ngimel** [comment]
Fixed on master in #61331
