### ISSUE TITLE
CUSTOM NN MODULES - Github link is broken

### ISSUE THREAD

**Issue by elisim** [pytorch/pytorch#65527]
## 📚 Documentation

When clicking [here](https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_module.html) on View on Github, the link https://github.com/pytorch/tutorials/blob/master/beginner_source/examples_nn/two_layer_net_module.py 

is broken. I tried to fix the link but couldn't found the `two_layer_net_module.py` in the repo:

![image](https://user-images.githubusercontent.com/17675462/134496159-ab3a5844-096f-4258-b9d1-94057606a63c.png)

**Comment by rodrigoberriel** [comment]
This file was renamed to `beginner_source/examples_nn/polynomial_module.py`:
- See https://github.com/pytorch/tutorials/commit/ce58d5904c04c4be10561447e41a153f573a3f93#diff-e5ef486bd89eb38de15752211d9437953681b8caa8f44d7c86bb820d13151df2.

I don't know why that link is still working, though. It points to 1.7.0 docs, the page is kind of broken as well...

I guess we just need to update the link to the [new one](https://pytorch.org/tutorials/beginner/examples_nn/polynomial_module.html).
