### ISSUE TITLE
Support subclassing torch.nn.Parameter and custom Tensor types.

### ISSUE THREAD

**Issue by anj-s** [pytorch/pytorch#65530]
We are working on a feature that will enable us to offload model parameters to SSD similar to CPU offload. To support this in a way that will require rewriting optimizers and minimize the surface area of user changes when using this feature, we want to create a Parameter that is backed by SSD storage. 

The approach taken has been to subclass both torch.nn.Parameter and SsdTensorHandle (which is a subclass of torch.Tensor) and create a new Parameter type called SsdParameter. SsdTensorHandle is what provides the interface for storing an underlying tensor on SSD and moving it back and forth to CPU as needed using the __torch_dispatch__ mechanism. We create a property in the SsdParameter that points to the SSD tensor.

The issue we are running into is the following: when calling optimizer.step() we don't see the SsdParameters being updated i.e the tensor SsdTensorHandle remains the same. However the .data property of the parameter seems to be updated. It turns out there are two versions of the underlying tensor. How do we implement tracking current grad changes while also supporting property changes on the Parameter object itself. 

[SsdParameter](https://github.com/facebookresearch/fairscale/blob/ssd_offload_train/fairscale/experimental/nn/ssd_offload.py#L341)
[SsdTensorHandle ](https://github.com/facebookresearch/fairscale/blob/ssd_offload_train/fairscale/experimental/nn/ssd_offload.py#L143)and [SsdBuffer](https://github.com/facebookresearch/fairscale/blob/ssd_offload_train/fairscale/experimental/nn/ssd_offload.py#L261)
[Test to repro the issue](https://github.com/facebookresearch/fairscale/blob/ssd_offload_train/tests/nn/data_parallel/test_fsdp_offload.py#L226)

Reference issues that are tackling the same or similar problems and code samples that helped me:
https://github.com/pytorch/pytorch/issues/65018
https://github.com/pytorch/pytorch/pull/62965/files
https://github.com/pytorch/pytorch/issues/62787 

I've tried a [second approach](https://gist.github.com/anj-s/cc3d65e168e51f2affec813a909de5c0) (using one of the implementations above) that I also wanted to mention where instead of subclassing, the SsdTensorHandle is a property of the SsdParameter object. I wasn't able to get that work since I hit the following error `AttributeError: 'SsdParameter' object has no attribute 'wrapped'`. Wasn't able to dig into why wrapped is not recognized.

cc @albanD @mruberry @jbschlosser @walterddr @ezyang who has been helping us through this process! Thank you!

## To Reproduce

1. git clone --branch ssd_offload_train https://github.com/facebookresearch/fairscale.git
2. pytest -rxP tests/nn/data_parallel/test_fsdp_offload.py::TestSsdLoading::test_ssd_offloading_param

## Expected behavior

SsdParameters should be updated post optimizer.step()

## Environment

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.2 (default, Mar  3 2021, 20:02:32)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.790
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.0
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cu111
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py39he8ac12f_0
[conda] mkl_fft                   1.3.0            py39h54f3939_0
[conda] mkl_random                1.0.2            py39h63df603_0
[conda] mypy                      0.790                     <pip>
[conda] mypy-extensions           0.4.3                     <pip>
[conda] numpy                     1.21.0                    <pip>
[conda] numpy                     1.19.2           py39h89c1606_0
[conda] numpy-base                1.19.2           py39h2ae0177_0
[conda] pytorch                   1.7.1           py3.9_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] pytorch-sphinx-theme      0.0.24                    <pip>
[conda] torch                     1.9.0                     <pip>
[conda] torchaudio                0.7.2                      py39    pytorch
[conda] torchaudio                0.9.0                     <pip>
[conda] torchtext                 0.10.0                    <pip>
[conda] torchvision               0.8.2                py39_cu110    pytorch
[conda] torchvision               0.10.0+cu111              <pip>

**Comment by ezyang** [comment]
cc @jbschlosser @albanD

**Comment by albanD** [comment]
Thanks for sending details on what you want to do!
We already have two issues related to wrapping subclasses in Parameters, I think we want to remove duplicate issues, in particular, https://github.com/pytorch/pytorch/issues/62787 is the one tracked on the torch.nn tracker.

> AttributeError: 'SsdParameter' object has no attribute 'wrapped'

For this one, this is most likely related to https://github.com/pytorch/pytorch/issues/65243. You should make sure you manually pass the `grad_output` to `.backward()` until we fix it.

**Comment by anj-s** [comment]
Thanks @albanD. Feel free to close the issue. Wanted to make sure I captured context from my debugging process.

**Comment by jbschlosser** [comment]
Closing as duplicate; please refer to linked issue #65018 to continue discussion.
