### ISSUE TITLE
[ONNX] Error when returning multiple outputs from nested conditional statements

### ISSUE THREAD

**Issue by ig177** [pytorch/pytorch#65540]
## 🐛 Bug

Given this very simple model + code:
```
import torch
import torch.onnx

class MyModel(torch.nn.Module):
    def forward(self, x: torch.Tensor, y: torch.Tensor):
        r = torch.tensor([0, 0])

        if x.numel() > 0:
            if y.numel() > 0:
                return r + 1, r + 1

        return r, r


instance = MyModel()
instance.eval()

x, y = torch.tensor([1, 2, 3, 4]), torch.tensor([1, 2, 3, 4, 5])

torch_result = instance(x, y)

scripted_cell = torch.jit.script(instance)

torch.onnx.export(
    model=scripted_cell,
    args=(x, y),
    f='net.onnx',
    verbose=True,
    input_names=['x', 'y'],
    output_names=['result', 'result2'],
    example_outputs=torch_result,
    opset_version=13,
    dynamic_axes={'y': {0: 'first_axis'}},
)
```

I get the following error:
```
Traceback (most recent call last):
  File "C:\PythonEnvs\onnx3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d566095fefa5>", line 33, in <module>
    dynamic_axes={'y': {0: 'first_axis'}},
  File "C:\PythonEnvs\onnx3\lib\site-packages\torch\onnx\__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "C:\PythonEnvs\onnx3\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "C:\PythonEnvs\onnx3\lib\site-packages\torch\onnx\utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "C:\PythonEnvs\onnx3\lib\site-packages\torch\onnx\utils.py", line 467, in _model_to_graph
    module=module)
  File "C:\PythonEnvs\onnx3\lib\site-packages\torch\onnx\utils.py", line 134, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples, unsupported kind: prim::Uninitialized
```

Seems that the error stems from ONNX converter's inability to handle the _0 variable in TorchScript's IR:
```
def forward(self,
    x: Tensor,
    y: Tensor) -> Tuple[Tensor, Tensor]:
  _0 = uninitialized(Tuple[Tensor, Tensor])  # <<<< this one!
  r = torch.tensor([0, 0])
  if torch.gt(torch.numel(x), 0):
    if torch.gt(torch.numel(y), 0):
      _5 = (torch.add(r, 1), torch.add(r, 1))
      _3, _4 = True, _5
    else:
      _3, _4 = False, _0
    _1, _2 = _3, _4
  else:
    _1, _2 = False, _0
  if _1:
    _6 = _2
  else:
    _6 = (r, r)
  return _6
```
_0 is not actually ever used but ONNX converter insists on looking at it.

Note that this stops being a problem when:
1. A single output is returned (in both return statements).
2. The condition is not nested (e.g. when rewritten as `if x.numel()>0 and y.numel()>0`).

## Expected behavior
Correct conversion to ONNX, without spitting out errors.

## Environment
PyTorch version: 1.9.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.2
Libc version: N/A

Python version: 3.6 (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.3
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect

@BowenBao @neginraoof 

cc @BowenBao @neginraoof

**Comment by hwangdeyu** [comment]
@ig177 Thanks for this detailed information.

This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1429847

Could you also tell us which model you encounter this issue, or just self discovery?

**Comment by ig177** [comment]
Thanks, @hwangdeyu, I hope this issue is fixed soon.
I need this functionality for a proprietary stateful model. In my model, the first element of the returned tuple holds the prediction, and the second element holds the new state.

**Comment by BowenBao** [comment]
@ig177 could you try with pytorch nightly? This issue is likely resolved in master.

**Comment by ig177** [comment]
@BowenBao - I just tried it with the nightly build (torch==1.11.0.dev20210928+cpu). Indeed it solves this issue. I appreciate your help!

**Comment by starryskyyl** [comment]
@BowenBao @ig177 when i use  the latest version of  pytorch to export prophetnet model(similar to transformer, with beam search),  the above issue is solved. but i get a new error: RuntimeError: prim::TupleIndex not matched to tuple construct. Any suggestions?  Thanks.
-----------------------
Traceback (most recent call last):
  File "prophetnet_beam_search.py", line 889, in <module>
    main()
  File "prophetnet_beam_search.py", line 869, in main
    torch.onnx._export(
  File "/mnt/nas/yaoliang.yl/tools/miniconda3/envs/pytorch1.11.0_py38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 28, in _export
    result = utils._export(*args, **kwargs)
  File "/mnt/nas/yaoliang.yl/tools/miniconda3/envs/pytorch1.11.0_py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/mnt/nas/yaoliang.yl/tools/miniconda3/envs/pytorch1.11.0_py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/mnt/nas/yaoliang.yl/tools/miniconda3/envs/pytorch1.11.0_py38/lib/python3.8/site-packages/torch/onnx/utils.py", line 151, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: prim::TupleIndex not matched to tuple construct

**Comment by naor2013** [comment]
@starryskyyl did you find a solution for this?
