### ISSUE TITLE
TestMultiprocessing.test_fs_sharing is flaky

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65559]
See https://github.com/pytorch/pytorch/runs/3690474520, relevant snippet:

```
Failure: TestMultiprocessing.test_fs_sharing
Traceback (most recent call last):
  File "test_multiprocessing.py", line 341, in test_fs_sharing
    self._test_sharing(repeat=TEST_REPEATS)
  File "test_multiprocessing.py", line 282, in _test_sharing
    test_fill()
  File "test_multiprocessing.py", line 260, in test_fill
    self.assertFalse(p.is_alive())
AssertionError: True is not false
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @gcramer23 @mruberry

**Comment by fduwjj** [comment]
Who can the proper owner of this issue, @rohan-varma ?

**Comment by H-Huang** [comment]
Cleaning this up, this was fixed by https://github.com/pytorch/pytorch/pull/93183
