### ISSUE TITLE
ATen mirror needs to start pulling in directories that are not directly in its subdirectory

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6556]
As we start bringing together common pieces between PyTorch and Caffe2, it will no longer be the case that the most logical place for a third party library or a cmake to live is in the aten/ folder. This has implications for ATen mirroring, because it means that if you have *only* the ATen subdirectory, that is not sufficient to build. In this case, we need to copy depended upon files (e.g., `cmake/Modules_CUDA_fix`) into the root dir when we do the mirror, and test for the file in both locations.

CC @zdevito @prigoyal

**Comment by zdevito** [comment]
I'd rather not have to move files around that sounds prone to bugs. Is it
possible to just define a filter of the pytorch repo so that we end up with:

aten/
cmake/

and nothing else and have the build inside the aten folder still work?

I don't think people will care that we added an extra folder level.

**Comment by ezyang** [comment]
That SGTM. We might have to modify the filter, so if it can live in a file somewhere that would be helpful.

**Comment by zdevito** [comment]
Yeah, we can just dump the command into `aten/tools`. The current command,
which we can just put in a script and modify is:

```
rm -rf repo
git clone $EXTRACTED_REPO repo
cd repo
git config user.name "Zach DeVito"
git config user.email "zdevito@fb.com"
git remote add fullrepo $FULL_REPO
git fetch fullrepo
git checkout -b temporary-split-branch fullrepo/master
git filter-branch -f --subdirectory-filter $EXTRACTED_PATH --prune-empty
git checkout master
git merge temporary-split-branch
git push
```

**Comment by prigoyal** [comment]
@ezyang , would it be possible to resolve this issue soon? PR #183 in TC repo is pending lawyers decision on how to include a BSD file in the repo but if we could get this file from the submodule, then we don't need to wait for the lawyers and can merge the PR soon without worrying about any license issues.
