### ISSUE TITLE
RuntimeError: matrix and matrix when loss.backward()

### ISSUE THREAD

**Issue by vanangamudi** [pytorch/pytorch#6559]
I am trying to implement [Dynamic Coattention networks](https://arxiv.org/pdf/1611.01604.pdf)
When running the backward() I get this error.  forward() works fine. 
I use pytorch version 0.3.1 and python3.6 and cuda 9.0.
the loss function is NLLLoss and you can find the entire repo [here](https://github.com/vanangamudi/dcn_squad)
dcn.py is the main file.

```
Traceback (most recent call last):
  File "dcn.py", line 443, in experiment
    if not trainer.train():
  File "/home/vanangamudi/projects/dcn/trainer.py", line 162, in train
    loss.backward()
  File "/home/vanangamudi/env/pytorch35/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/vanangamudi/env/pytorch35/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: matrix and matrix expected at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:241
```

Steps to reproduce:-

1. Clone the repo
2. create a dir under the cloned repo named _dataset_
3. place the [train](https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v1.1.json) and [dev](https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v1.1.json) json files dataset [squad](https://rajpurkar.github.io/SQuAD-explorer/)
4. In dcn.py change set  `flush = True`
5. run as `>>> python dcn.py "" train`

**Comment by soumith** [comment]
this is not a bug, something is wrong with the code. please ask the original authors or post to the forums here: https://discuss.pytorch.org/
