### ISSUE TITLE
Cannot install `torchvision 0.1.7` by using conda

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#656]
According to anaconda [package](https://anaconda.org/soumith/torchvision/files/modal/info/58825b7f966a5a10fb59eac2), the dependent for python 3.5 linux64 version should be `pytorch` instead of `torch`. This should be an easy fix in my opinion.

**Comment by soumith** [comment]
yes, the anaconda package of pytorch is called pytorch.

 conda install torchvision -c soumith

that should install both

**Comment by fehiepsi** [comment]
@soumith  in my case, it just updates pytorch to version 0.1.7, torchvision still at the version 0.1.6. I have tried various ways such as `conda install --force -c soumith torchvision` or `conda install -c soumith torchvision=0.1.7` but conda just throwed various errors.

**Comment by soumith** [comment]
i see. in this case, just remove torchvision (conda uninstall torchvision) and then install it via pip.

pip install torchvision

**Comment by fehiepsi** [comment]
That solves the problem. Thanks a lot!
