### ISSUE TITLE
Stop windows cuda 10.2 CI builds and releases

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#65648]
The main reason to support cuda 10.2 is the size considerations for linux pypi distribution. Windows is exempt from that, so we can have only 11.x builds/releases. At this point, 11.x is old enough and we don't have to worry that someone cannot run 11.x build. 
Windows 10.2 build is flaky (#65612, #25393), so removing it will simplify CI and reduce churn. 
cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel @ezyang @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
To be perfectly objective, according to the [conda](https://anaconda.org/pytorch/pytorch/files?version=1.9.0) download stats, 
PyTorch-1.9.0 for CUDA-10.2 were downloaded 103k times vs CUDA-11.1 that were downloaded 80k times.

**Comment by ngimel** [comment]
Possibly because 
```
NOTE: 'conda-forge' channel is required for cudatoolkit 11.1
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
```
adding conda-forge is an additional step many people don't do.
