### ISSUE TITLE
Layernormal seems only support torch.float32 。

### ISSUE THREAD

**Issue by emptyknowledge** [pytorch/pytorch#65656]
## 🐛 Bug

Tensor has dtype torch.float64, then layernormal raise error.

## To Reproduce

1. a = torch.randn((2,5), dtype=float)
1. normal = torch.nn.LayerNormal((5))
1. normal(a)

RuntimeError: expected scalar type Double but found Float
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-89-413f45b24634> in <module>
----> 1 n(a)

Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\normalization.py in forward(self, input)
    150     def forward(self, input):
    151         return F.layer_norm(
--> 152             input, self.normalized_shape, self.weight, self.bias, self.eps)
    153 
    154     def extra_repr(self):

Anaconda3\envs\py36\lib\site-packages\torch\nn\functional.py in layer_norm(input, normalized_shape, weight, bias, eps)
   1680     """
   1681     return torch.layer_norm(input, normalized_shape, weight, bias, eps,
-> 1682                             torch.backends.cudnn.enabled)
   1683 
   1684 

RuntimeError: expected scalar type Double but found Float

## Expected behavior

Get the result correctly

## Environment

windows10
torch ==1.2.0+cu92

**Comment by gchanan** [comment]
please try an updated version of PyTorch.

**Comment by alexeygolyshev** [comment]
```
import torch

print(torch.__version__)

try:
    torch.nn.LayerNorm(normalized_shape=(3,3))(torch.empty(3,3, dtype=torch.float64))
except Exception as e:
    print(repr(e))
```

> 1.9.1
> RuntimeError('expected scalar type Double but found Float')
