### ISSUE TITLE
-m torch.distributed.launch --nproc_per_node=NUM_GPUS_YOU_HAVE

### ISSUE THREAD

**Issue by alicera** [pytorch/pytorch#65678]
## ❓ Questions and Help
-m torch.distributed.launch --nproc_per_node=NUM_GPUS_YOU_HAVE

How to set these parameter into python  without command line?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @gcramer23

**Comment by SciPioneer** [comment]
I think you can wrap up all the args in a list and then feed it to `launch.main` method.

See: https://github.com/pytorch/pytorch/blob/master/test/distributed/test_launcher.py#L39-L50

**Comment by SciPioneer** [comment]
cc @cbalioglu

**Comment by alicera** [comment]
Where can I find the -m parameter?

**Comment by cbalioglu** [comment]
Hey @alicera, check out https://github.com/pytorch/pytorch/blob/master/torch/distributed/launcher/api.py#L95. Our CLI internally calls `elastic_launch()` after populating a `LaunchConfig`. Let me know if this helps.
