### ISSUE TITLE
How to export split to ONNX with dynamic split_size?

### ISSUE THREAD

**Issue by Wwwwei** [pytorch/pytorch#65682]
## ❓ Questions and Help
I need to implement dynamic tensor split op in work. But when I want to export this split op to ONNX with dynamic split_size, it seems not work. 

I am new to ONNX. Anyone can help me? Thanks a lot.

## To Reproduce

```python
import torch

dummy_input = (torch.tensor([1, 4, 2, 7, 3]), torch.tensor([1, 2, 2]))

class Split(torch.nn.Module):
    def forward(self, x, l):
        return x.split(l.cpu().numpy().tolist(), dim=-1)
    
model = Split()

with torch.no_grad():
    torch.onnx.export(
        model, dummy_input, 'split.onnx', verbose=False, opset_version=13,
        input_names=['a', 'b'],
        output_names=['c'],
        dynamic_axes={'a': [0], 'b': [0], 'c': [0]}
    )
```
when I use the onnx model, it seems not to work. I get this error:
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:b

```python
import onnxruntime as ort

model_path = './split.onnx'
sess = ort.InferenceSession(model_path)

a = torch.tensor([4, 2, 3, 4])
b = torch.tensor([1, 3])
sess.run(['c'], {'a':a.numpy(), 'b':b.numpy()})
```
Tensor b seems can not be used as an input, but I do need a parameter to represent the dynamic split_size.

## Environment
- PyTorch Version (e.g., 1.0): 1.8.1+cu111
- Python version: 3.8

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment]
`l.cpu().numpy().tolist()` will get the static value of `l` in tracing. Then there is no `l` in onnx model any more.
Please take a look at the example `test_split_size_as_list` here https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_onnxruntime.py#L4713
to see how you can change the model script.

**Comment by Wwwwei** [comment]
> @Wwwwei `l.cpu().numpy().tolist()` will get the static value of `l` in tracing. Then there is no `l` in onnx model any more. Please take a look at the example `test_split_size_as_list` here https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_onnxruntime.py#L4713 to see how you can change the model script.

Thank you very much for your reply. Now I understand why it dosen't work. But when I try this example, I get this error: 
```
Model requires 4 inputs. Input Feed contains 2
```
I guess I still didn't use the it correctly. Could you please give me a demo?

```python
import torch
import onnxruntime as ort

dummy_input = (torch.tensor([1, 4, 2, 7, 3]), [torch.tensor(1), torch.tensor(2), torch.tensor(2)])

class Split(torch.nn.Module):
    def forward(self, x, l):
        return x.split(l)
    
model = Split()

with torch.no_grad():
    torch.onnx.export(
        model, dummy_input, 'split.onnx', verbose=False, opset_version=13,
        input_names=['a', 'b'],
        output_names=['c'],
        dynamic_axes={'a': [0], 'c': [0]}
    )

model_path = './split.onnx'
sess = ort.InferenceSession(model_path)

a = torch.tensor([4, 2, 3, 4])
b = [torch.tensor(1).numpy(), torch.tensor(3).numpy(), torch.tensor(1).numpy()]
sess.run(['c'], {'a':a.numpy(), 'b':b})
```

**Comment by jiafatom** [comment]
@Wwwwei In the Torchscript, the aten graph inputs expands `[torch.tensor(1), torch.tensor(2), torch.tensor(2)])` into three inputs. This is why the exported model has 4 inputs instead of 2. If you open the exported ONNX model, you will find the input names. Try the following and it seems working:
```python
    a = torch.tensor([4, 2, 3, 4])
    b = torch.tensor(1).numpy()
    c = torch.tensor(3).numpy()
    d = torch.tensor(1).numpy()
    sess.run(['c'], {'a':a.numpy(), 'b':b, '2':c, '3':d})
```

**Comment by BowenBao** [comment]
Hi @Wwwwei ,

We’ve gone ahead and closed this issue because it has been resolved by above.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
