### ISSUE TITLE
Transpose using negative dimension

### ISSUE THREAD

**Issue by edouardoyallon** [pytorch/pytorch#657]
Hi!

It is not a major fix, however I think that x.transpose(-1,-3) should be valid, as it is in numpy:

```
x=np.zeros((3,5,7))
x.transpose(-1,0,-2).shape
```
> (7,3,5)

```
x=torch.FloatTensor(3,5,7)
x.transpose(-1,-2)
```
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>RuntimeError: out of range at /data/users/soumith/miniconda2/conda-bld/pytorch-
>cuda80-0.1.7_1485449073235/work/torch/lib/TH/generic/THTensor.c:398

Best,
EO

**Comment by goelhardik** [comment]
@apaszke Can I work on this issue? It needs a modification to Tensor.cwrap's transpose function, right?

**Comment by soumith** [comment]
@goelhardik go for it. the fix might be a bit involved, you'll have to touch the TH and THC C libraries, I think. (unless you simply do it within the python wrapper)

**Comment by apaszke** [comment]
We should do that in `cwrap`. It doesn't need any modifications in the C libs.
