### ISSUE TITLE
Cleanup optimizer handling of complex numbers.

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#65711]
Following a long discussion in https://github.com/pytorch/pytorch/issues/59998 (that was especially geared towards the Adam optimizer), we decided that all the optimizers in core should behave with complex numbers as-if it was two real numbers in R^2.

This is both a simple and already used semantic which is a good fit to be properly added to core.
If some algorithms would be very complex to add support to, it is also ok to warn (if the algorithm run with current code but produce surprising results) or raise a nice error (if the algorithm would raise an error anyways).

We should audit all the optimizers to make sure they behave as expected:
- [x] Adadelta
- [x] Adagrad
- [x] Adam
- [x] AdamW
- [ ] SparseAdam
- [x] Adamax
- [x] ASGD
- [ ] LBFGS
- [x] RMSprop
- [x] Rprop
- [x] SGD

cc @vincentqb @jbschlosser @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @iramazanli

**Comment by anjali411** [comment]
@albanD correct me if I am wrong, but isn't this objective implicitly achieved by our derivative convention? (see: `How is Wirtinger Calculus useful in optimization?` https://pytorch.org/docs/stable/notes/autograd.html?highlight=complex%20autograd) i.e., it eliminates the need to view complex numbers as two reals ...

**Comment by Lezcano** [comment]
The problem is how you define things like the momentum and the adaptive term in optimisers. See the discussion in https://github.com/pytorch/pytorch/issues/59998

**Comment by CollinsPeriodLee** [comment]
Hi, Could anyone tell me which optimizers work for the complex-parameter network now? I tried to find an optimizer to train a neural network with complex parameters, there is always a warning occurred, notifying me that the backward() operation will cast complex values to real and it will discard the imaginary part. The optimizers I tried include Adam, Adagrad, and the warnings will pop up for both optimizers. Is it what I need to worry about that discarding the imaginary part could result in incorrect gradients of the complex parameters?

**Comment by Lezcano** [comment]
@albanD is currently on PTO, and he's the one shepherding this issue.
In the meantime, you can use the trick mentioned in https://github.com/pytorch/pytorch/issues/59998#issuecomment-896968598 as a workaround, that is, setting `complex_tensor = torch.complex(real_part, imaginary_part)` and optimise the real and imaginary parameters. This will be Forward Compatible with the changes that we'll be making in the future  (these are the semantics we are implementing for complex numbers), and this should work without warnings with all the optimisers.

**Comment by CollinsPeriodLee** [comment]
Hi, @Lezcano, thanks for your comments, I noticed that https://github.com/pytorch/pytorch/blob/0dc3f829d9d11ca7e972cb5fcc95059742fa71ea/torch/optim/_functional.py#L49 

Does this mean Adagrad works for the network with complex parameters?

**Comment by Lezcano** [comment]
I believe so, yes.

**Comment by CollinsPeriodLee** [comment]
OK, thanks! You are so kind! I tried to use the Adagrad optimizer copied from 
https://github.com/pytorch/pytorch/blob/0dc3f829d9d11ca7e972cb5fcc95059742fa71ea/torch/optim/_functional.py#L16
but the warning still occurs, do I need to report it as a bug?

**Comment by Lezcano** [comment]
That smells like a bug, certainly. Please fill an issue and link this conversation in it please. 
cc @choward232 @albanD

**Comment by CollinsPeriodLee** [comment]
Yeah, sure. Thank you!

**Comment by CollinsPeriodLee** [comment]
Hi, I just noticed it is not the warning from the optimizer, but from my custom activation function, and I created a closed issue in https://github.com/pytorch/pytorch/issues/68524#issue-1056309717 to help those who meet such warning in future. Thank you very much!

**Comment by CollinsPeriodLee** [comment]
A further comment here. I followed the test procedure in testing folder https://github.com/pytorch/pytorch/blob/143491e0ad44929f4df6545314c9383ee90d4c98/test/test_optim.py#L273
with a few modifications
```python
def test_complex_optimizer(optimizer_constructor):
    complex_param = torch.randn(1, 10, dtype=torch.complex64, requires_grad=True)
    complex_opt = optimizer_constructor(complex_param)
    real_param = torch.view_as_real(complex_param).detach().requires_grad_()
    real_opt = optimizer_constructor(real_param)

    for i in range(1):
        complex_param.grad = torch.randn(1,10,dtype=torch.complex64)
        real_param.grad = torch.view_as_real(complex_param.grad)

        complex_opt.step()
        real_opt.step()
        print(torch.view_as_real(complex_param)-real_param)
```
and did several naive tests, 
```python
test_complex_optimizer(
lambda param: torch.optim.Adadelta([param],lr=0.001))
```
`Adadelta, Adagrad, Adam, AdamW, ASGD,  RMSprop` return 
```
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]], grad_fn=<SubBackward0>)
```
For those who want to use default optimizer, it could helps.

**Comment by albanD** [comment]
The list at the top of this issue should be up to date.
Feel free to send a PR with tests for the optimizers that work so that we can cross this from here.

**Comment by CollinsPeriodLee** [comment]
Some recent tests...

What I claimed in https://github.com/pytorch/pytorch/issues/65711#issuecomment-971760607  is wrong... Sorry for that. 

```
======================================================================
FAIL: test_Adam_complex (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 544, in test_Adam_complex
    self._test_complex_optimizer(
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 286, in _test_complex_optimizer
    self.assertEqual(torch.view_as_real(complex_param), real_param)
  File "/mnt/c/Users/47864769/pytorch/torch/testing/_internal/common_utils.py", line 1985, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 43 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0009516477584838867 (0.36476531624794006 vs. 0.36571696400642395), which occurred at index (4, 4, 1).

======================================================================
FAIL: test_adamw_complex (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 596, in test_adamw_complex
    self._test_complex_optimizer(
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 286, in _test_complex_optimizer
    self.assertEqual(torch.view_as_real(complex_param), real_param)
  File "/mnt/c/Users/47864769/pytorch/torch/testing/_internal/common_utils.py", line 1985, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 25 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.001000046730041504 (-1.133029818534851 vs. -1.1340298652648926), which occurred at index (1, 4, 1).

======================================================================
FAIL: test_asgd_complex (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 861, in test_asgd_complex
    self._test_complex_optimizer(
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 286, in _test_complex_optimizer
    self.assertEqual(torch.view_as_real(complex_param), real_param)
  File "/mnt/c/Users/47864769/pytorch/torch/testing/_internal/common_utils.py", line 1985, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 46 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.00019061565399169922 (-1.9052355289459229 vs. -1.9050449132919312), which occurred at index (3, 4, 1).

======================================================================
FAIL: test_rmsprop_complex (__main__.TestOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 810, in test_rmsprop_complex
    self._test_complex_optimizer(
  File "/mnt/c/users/47864769/pytorch/test/test_optim.py", line 286, in _test_complex_optimizer
    self.assertEqual(torch.view_as_real(complex_param), real_param)
  File "/mnt/c/Users/47864769/pytorch/torch/testing/_internal/common_utils.py", line 1985, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 25 element(s) (out of 50) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.01000000536441803 (0.1741265058517456 vs. 0.16412650048732758), which occurred at index (2, 3, 1).

----------------------------------------------------------------------
Ran 138 tests in 30.570s

FAILED (failures=4)
```

**Comment by CollinsPeriodLee** [comment]
For adam, the issue is that the variance `exp_avg_sq` of the real optimizer is not as the same as the variance of the complex optimizer... I think the complex optimizer compute the correct one, but the real optimizer is wrong.

What the complex optimizer do is 
```python
        exp_avg_sq.mul_(beta2).addcmul_(grad, grad.conj(), value=1 - beta2)
```
What the real optimizer do is
```python 
        exp_avg_sq[0].mul_(beta2).addcmul_(grad.real, grad.real, value=1 - beta2)
        exp_avg_sq[1].mul_(beta2).addcmul_(grad.imag, grad.imag, value=1 - beta2)
```
thus, the exp_avg_sq is different for real part and imaginary part.

so... should we consider another test function?

**Comment by Lezcano** [comment]
In case you have missed, there is a discussion in https://github.com/pytorch/pytorch/issues/59998 for why we are implementing the approach we are taking.
Could you comment on these points there if after reading the discussion you still believe that his is not the correct approach?

**Comment by CollinsPeriodLee** [comment]
Thanks, I just read the discussion. I totally agree with you. So I modified the Adam optimizer a little bit. Once I pull a request, I will put a link here.

**Comment by albanD** [comment]
All the high priority optimizers are now done!

**Comment by anjali411** [comment]
@albanD we just have two more optimizers left so maybe keep it open until they are done as well?

**Comment by albanD** [comment]
We can open an issue for the two last ones. No one is working on supporting these at this moment though.
