### ISSUE TITLE
[JIT][script] Script functions should be callable/inlineable from traced methods

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#6572]
This allows us to embed code like the following in a traced module:

```
@torch.jit.script
def maybeTile(timestep, enc_outs):
  if timestep == 0:
    enc_outs = enc_outs.repeat(1, batch_size, 1)
  return enc_outs

**Comment by apaszke** [comment]
That's pretty easy. We should add a C++ clone of symbolic override, and use this in `GraphExecutor.__call__` and `ScriptModule.__call__`.
