### ISSUE TITLE
Something went wrong when running an inference with a trained model

### ISSUE THREAD

**Issue by haythemdhieb** [pytorch/pytorch#65747]
I trained a model on google colab and the I downloaded the pretrained model(pth format) then I tried to run an inference with this trained model but an error occured
![error_pytorch](https://user-images.githubusercontent.com/44007597/135121696-f795e179-6bbc-4f38-ba1d-f18080433ba3.png)

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
