### ISSUE TITLE
`torch.cuda.memory_stats` returns empty dict

### ISSUE THREAD

**Issue by daniellepintz** [pytorch/pytorch#65793]
## 🐛 Bug

`torch.cuda.memory_stats` returns an empty dict when I call it on a GPU device as seen in colab below

## To Reproduce

https://colab.research.google.com/drive/1CSGvME8XjhB_LFHSghe06DI5AqVAYdZ3?usp=sharing (Third cell is most relevant)

## Expected behavior

I would expect a dict of memory stats, even if some of those stats may be 0.

## Environment
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.4.8
[pip3] torch==1.9.0+cu102
[pip3] torchmetrics==0.5.1
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cu102
[conda] Could not collect

cc @ngimel

**Comment by ngimel** [comment]
cuda context is not initialized on device by the time you call `memory_stats`, so this is expected. If you initialize context e.g. by calling 
```
x=torch.randn(1, device="cuda")
torch.cuda.memory_stats(device)
```
then memory_stats dict will be properly filled.

**Comment by daniellepintz** [comment]
Ah I see, thanks so much!
