### ISSUE TITLE
build distributed pytorch with mpi backend

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#6580]
Hi,
I want to install pytorch from source with mpi backend, when i compile gloo, it gives me this error.
![image](https://user-images.githubusercontent.com/7859276/38716499-b34672b6-3f13-11e8-9d75-6d09d3ee2ee0.png)

I specify the mvapi in my **PATH** **LD_LIBRARY_PATH** and **CPATH**, but it does not work, any help will be appreciated.

**Comment by albanD** [comment]
Hi,

The error message seems to suggest that the path that you provided "/usr/mvapich2.2/include" does not exist. Is it the case?

**Comment by gmyofustc** [comment]
@albanD I mannually write a findmpi.cmake in  [torch/lib/THD/cmake](https://github.com/pytorch/pytorch/tree/master/torch/lib/THD/cmake) and specify the MPI_ROOT_DIR，it works.
