### ISSUE TITLE
How to install PyTorch on ppc64le with pip?

### ISSUE THREAD

**Issue by M-Amrollahi** [pytorch/pytorch#65816]
I am going to build a virtual environment (python -m venv) and install PyTorch on a ppc64le machine. But there is no package in pip to install PyTorch, however it is available in conda. But I wanted not to use conda because I need to install some specific packages and versions. So, how can I install PyTorch on a ppc64le(IBM Power8) machine?

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
