### ISSUE TITLE
compile from source error

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#6585]
Hi, I complie the pytorch with distributed support and get an eror here
https://github.com/pytorch/pytorch/blob/62ac7f981271609adaf2220d5dcecab84d71b2ce/torch/csrc/distributed/Module.cpp#L34

The ERROR INFO:
![image](https://user-images.githubusercontent.com/7859276/38731868-a49dc756-3f4e-11e8-91c4-29035b01cd74.png)

I grep the whole file, and does not find the define of this function
![image](https://user-images.githubusercontent.com/7859276/38731941-e179922c-3f4e-11e8-8543-ba55dea93cc8.png)

Any help will be appreciated.

**Comment by apaszke** [comment]
You have `WITH_DISTRIBUTED_MW` enabled, but this is not a flag we support at the moment. Disable it and it should build just fine.

**Comment by gmyofustc** [comment]
@apaszke what does **WITH_DISTRIBUTED_MW** mean, many thanks

**Comment by apaszke** [comment]
It’s an experimental mode of the distributed backend that’s not maintained at the momsnt
