### ISSUE TITLE
High CPU usage occurred when using 'torch::from_blob' to create tensor from Mat in C++

### ISSUE THREAD

**Issue by Nyohohoho** [pytorch/pytorch#65858]
I am now trying to deploy some trained CNNs on my applications developed by C++.
I found that the following code has around 60% CPU usage.
`torch::Tensor tensor = torch::from_blob(image.data, { image.rows, image.cols, 3 }, at::kByte).to(at::kFloat);`

Is there any possibility that I am wrong in something?
If not, could you please tell me how I am able to reduce the CPU usage when using libtorch.
Thank you for your attention and great help.

**Comment by VitalyFedyunin** [comment]
You can reduce number of threads `set_num_threads`. For further question please use https://discuss.pytorch.org/
