### ISSUE TITLE
Couldn't export Python operator when operator_export_type set to ONNX_FALLTHROUGH

### ISSUE THREAD

**Issue by yd2102** [pytorch/pytorch#65853]
## 🐛 Bug

torch.onnx.export() fails to export the model that contains customized function. According to the following documentation, the custom operator should be exported as is if operator_export_type is set to ONNX_FALLTHROUGH:

[torch doc](https://pytorch.org/docs/stable/onnx.html#onnx-fallthrough)

## To Reproduce

1. Run the following simplified python code:

```
import torch

class MyRelu(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input

class MyModule(torch.nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        
    def forward(self, input):
        return MyRelu.apply(input)
    
module = MyModule()
x = torch.randn(5, 5)
y = module(x)

torch.onnx.export(module, x, 'test.onnx', export_params=True, opset_version=13, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_FALLTHROUGH, do_constant_folding=False, verbose=False, input_names=['input'], output_names=['output'])
```

## Expected behavior

The export functionality should behave according to the pytorch documentation. An ONNX model with custom operation "MyRelu" should have been exported without errors.

## Environment

PyTorch version: 1.9.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.9.1
[pip3] torchaudio==0.9.1
[pip3] torchvision==0.10.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0           haa95532_296
[conda] mkl-service               2.3.0            py38h2bbff1b_1
[conda] mkl_fft                   1.3.0            py38h277e83a_2
[conda] mkl_random                1.2.1            py38hf11a4ad_2
[conda] mypy_extensions           0.4.3                    py38_0
[conda] numpy                     1.20.1           py38h34a8a5c_0
[conda] numpy-base                1.20.1           py38haf7ebc8_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.9.1                    pypi_0    pypi
[conda] torchaudio                0.9.1                    pypi_0    pypi
[conda] torchvision               0.10.1                   pypi_0    pypi

## Additional context

cc @BowenBao @neginraoof

**Comment by shubhambhokare1** [comment]
Please have a read at https://pytorch.org/docs/1.10./onnx.html#torch-autograd-functions

In order to export autograd functions, you will need to add a static symbolic method to your class.
In your case it will look something like

```
@staticmethod
def symbolic(ctx, input):
      return g.op("Clip", input, g.op("Constant", value_t=torch.tensor(0, dtype=torch.float)))
```

**Comment by BowenBao** [comment]
@shubhambhokare1 actually this is indeed a bug given that the export mode is ONNX_FALLTHROUGH.
We need to relax the constraint here when said export mode is chosen. https://github.com/pytorch/pytorch/blob/7c758759e3f5c869de2168dd0b40dfbdef7e17a6/torch/csrc/jit/serialization/export.cpp#L72

**Comment by shubhambhokare1** [comment]
Closing issue, as this is supported in 1.12 release branch
