### ISSUE TITLE
distributed training all-reduce error

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#6586]
Hi,
I build pytorch with distibuted backend, and I run code get this error
![image](https://user-images.githubusercontent.com/7859276/38734517-8b8688a2-3f58-11e8-9c94-fad2a2933a85.png)

This is where I call all-reduce
![image](https://user-images.githubusercontent.com/7859276/38734600-c8d6645c-3f58-11e8-90ad-1b753ce27081.png)

I init the distibuted engine Like This
![image](https://user-images.githubusercontent.com/7859276/38734569-b36f7478-3f58-11e8-8136-b5e493dc9b22.png)

More detail info is
I can run this code with thre official release .whl pakage at [pytorch.whl](http://download.pytorch.org/whl/cu90/torch-0.3.1-cp36-cp36m-linux_x86_64.whl)
However,if I build from source, pytorch just gives this error.

Waiting for help, thanks a lot

**Comment by SsnL** [comment]
`no kernel image is available` means that the GPU is too old, and the prebuilt binary doesn't support it. You can try building from source.
