### ISSUE TITLE
DISABLED test_fn_grad_min_binary_cuda_float64 (__main__.TestGradientsCUDA)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#65884]
Platforms: rocm

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by suo** [comment]
This test appears to be broken in rocm by https://github.com/pytorch/pytorch/commit/91611fe1d13ef303b5ddc3f96c230149c75eac4f, cc @soulitzer @albanD

**Comment by albanD** [comment]
High pri at least to make sure this is limited to rocm and find why this is happening. This PR should not have broken any test.

**Comment by albanD** [comment]
Example failure: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test1/2174//console

**Comment by jeffdaily** [comment]
I don't think the indicated commit is to blame.  There seem to be transient memory leak errors on rocm.  Similar to #65797.

**Comment by albanD** [comment]
Should we re-enable this test and see?

**Comment by jeffdaily** [comment]
No rush to re-enable this test.  Now that there are two different tests that indicate a memory leak, please give our triage team a moment to investigate.    I think the comment from #65797 is accurate -- rocm is not actually leaking memory but there seems to be a race in how quickly the memory is recovered and reported as such.

**Comment by albanD** [comment]
@jeffdaily any update on this? Is now a good time to try and re-enable this?

**Comment by jeffdaily** [comment]
We would like to re-enable once our CI images have moved to ROCm 5.0.  Waiting for #73105 to land.
