### ISSUE TITLE
Function request: np.around (alias with torch.round)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65908]
Add `around` as an alias for `round` and extend `round` to handle the "decimals" argument like NumPy: https://numpy.org/doc/stable/reference/generated/numpy.around.html?highlight=around#numpy.around. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @rgommers

**Comment by mruberry** [comment]
High priority because as of this writing #33287 has 40 thumbs up.

**Comment by mruberry** [comment]
When we do this it would be nice to modernize the round documentation and add a seealso to it and related rounding functions (like rint, floor and ceil), too.

**Comment by RylanSchaeffer** [comment]
What's the state of this issue? It looks like the PR is still open?

**Comment by mruberry** [comment]
> What's the state of this issue? It looks like the PR is still open

We expect the associated PR will be merged soon.
