### ISSUE TITLE
Docs: acosh documentation needs its mathematical formula moved above its note

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65905]
See https://pytorch.org/docs/master/generated/torch.acosh.html?highlight=acosh#torch.acosh. The mathematical formula should follow the the first sentence and be above the note.

cc @brianjo @mruberry

**Comment by ayushtues** [comment]
@mruberry @brianjo can I work on this quick fix as my first contribution to the repo?

**Comment by mruberry** [comment]
@ayushtues Sure; anyone can
