### ISSUE TITLE
Deprecation: Remove nn.functional.tanh

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65909]
This operation is deprecated and warns whenever it's used, see it's implementation here:

https://github.com/pytorch/pytorch/blob/4666e3f19228ddb73294c3ce7eba01b1641c083a/torch/nn/functional.py#L1835

The deprecation warning also correctly points users to torch.tanh, for which nn.functional.tanh is an alias. We should finally remove this operator.

cc @albanD @jbschlosser @walterddr @kshitij12345 @saketh-are @mruberry

**Comment by riotonzuk** [comment]
Hi, I can clear the tanh from nn.functional

**Comment by Atcold** [comment]
Can we please remove the deprecation warning?
It makes sense to have *all activation functions* in the same place. Why does one have to go fishing instead?

**Comment by albanD** [comment]
Sounds good to me.
@mruberry can we cancel this one?

**Comment by Atcold** [comment]
Any update?

**Comment by mruberry** [comment]
Sorry, I missed @albanD's ping. No update yet, but yes we could just keep `nn.functional.tanh` as an alias of `tanh` (we have alias support) and remove the deprecation warning

**Comment by albanD** [comment]
Ok let's do that!
