### ISSUE TITLE
Function matmul returns incorrect/imprecise results.

### ISSUE THREAD

**Issue by Student2Pro** [pytorch/pytorch#65919]
## 🐛 Bug

Let **A** and **C** be two matrices. **B** is the first row of **A**. Then the first row of **A**.matmul(**C**) should equal to **B**.matmul(**C**). The result shows that it isn't. I understand that floating-point calculation can cause some errors. But isn't it a little bit too imprecise (see code below)?

## To Reproduce

The following code is the copy of jupyter notebook:

```python
import torch
a = torch.rand(64,300)
b = a[0].unsqueeze(0)
```

```python
a[0] == b[0]
```

    tensor([True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True,
            True, True, True, True, True, True, True, True, True, True, True, True])

```python
c = torch.rand(300,10)
```

```python
ac = a.matmul(c)
bc = b.matmul(c)
```

```python
r0 = ac[0].unsqueeze(0)
```

```python
bc
```

    tensor([[73.0366, 67.9254, 72.3423, 71.3009, 71.8433, 72.6390, 74.7902, 76.8928,
             71.5721, 73.0743]])

```python
r0
```

    tensor([[73.0366, 67.9254, 72.3423, 71.3009, 71.8433, 72.6391, 74.7901, 76.8928,
             71.5721, 73.0743]])

```python
bc == r0
```

    tensor([[False, False, False, False, False, False, False, False, False, False]])

```python
bc - r0
```

    tensor([[ 7.6294e-06,  3.0518e-05, -1.5259e-05,  7.6294e-06, -5.3406e-05,
             -2.2888e-05,  2.2888e-05,  3.8147e-05,  2.2888e-05,  2.2888e-05]])

```python

```

## Expected behavior

I really hope that the error can be smaller.

## Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Window 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.8 (anaconda)
 - CUDA/cuDNN version: Cuda 11.1.74
 - GPU models and configuration: GTX 1050 Ti
 - Any other relevant information:

**Comment by albanD** [comment]
Hi,

You can create your input in double precision to get more precise results by passing `dtype=torch.double` when constructing your Tensors. That will reduce the error.

**Comment by ngimel** [comment]
This is expected behavior, math libraries that pytorch relies upon do not guarantee that these computations will produce identical results. What you see is a typical error from summing 300 fp numbers in possibly different order.

**Comment by Student2Pro** [comment]
Thanks for your help, close it now.
