### ISSUE TITLE
Queue time for GPU tests exceeds 7 hours

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#65922]
Consider https://hud.pytorch.org/commit/de80aff72de5f04a93498a1586cbd14ef0b49da2 for example
Change has been merge around 11PM PST on Sep 29, but  https://github.com/pytorch/pytorch/runs/3753431722 is still in queue for 7+ hours
https://github.com/pytorch/pytorch/runs/3753705370 (which is a Linux GPU test job) has been in the queue for 7+ hours as well:
![image](https://user-images.githubusercontent.com/2453524/135486855-3e320556-a76b-475c-bac1-48844d4abca9.png)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Increased number of workers in the pool by creating fake demand: https://github.com/pytorch/pytorch/pull/65927

**Comment by seemethere** [comment]
This should be resolved now, scaling utilities have been created in our infra repository to manually scale runners if we should ever run into this again.

see: https://github.com/fairinternal/pytorch-gha-infra/tree/main/scale_tools

**Comment by driazati** [comment]
https://metrics.pytorch.org/?orgId=1&viewPanel=35 shows queue time, it's the time the first `workflow_job` webhook was sent for a run with status `queued` to the time the job was started
