### ISSUE TITLE
[JIT] Handle dtypes

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#6593]
Over in https://github.com/pytorch/pytorch/pull/6573 I added support for optional dtypes via specifying an `optional<ScalarType>=nullopt` parameter, but this fails in the jit because the jit doesn't know how to handle ScalarTypes and/or optional values.

For now I believe I can break these up into two separate functions, with a couple of downsides:
1) Can't trace the dtype version
2) The python arg parser will generate two different overloads (which leads to slower parsing and ugly error messages) even though there is really only a single function.

CC @zdevito @apaszke.

**Comment by tugrulates** [comment]
Should be fixed by https://github.com/tugrulates/pytorch/commit/a233a6423e6f6ec109a8b74263dc05982cb8c1d9

Initial stab at prod() https://github.com/tugrulates/pytorch/commit/1e4aca53718164949b35aa29085c00d1d62424d5

Will send a PR after cleaning up the rest of the ops.
