### ISSUE TITLE
[REBASE ON MASTER PLS] `pytorch_linux_xenial_py3_6_gcc5_4_test` failing due to cert issues

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#65931]
**Current status**: mitigated, **rebase on master to get the fix** https://github.com/pytorch/pytorch/pull/65934.
 
Error looks like:
```
Fetched 4466 kB in 4s (1113 kB/s)
Reading package lists...
W: The repository 'https://deb.nodesource.com/node_12.x xenial Release' does not have a Release file.
E: Failed to fetch https://deb.nodesource.com/node_12.x/dists/xenial/main/source/Sources  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

## Incident timeline (times pacific)

- 7:27a Issues started: https://fburl.com/scuba/opensource_ci_jobs/h75x17or
- ~10a: Detected by looking at HUD.
- 10:12a: Googling surfaces an active issue in the package upstream https://github.com/nodesource/distributions/issues/1266
- 11:24a: Mitigation landed https://github.com/pytorch/pytorch/pull/65934

## Root cause

Let's Encrypt's root certificate expired on 9/30 ([helpful explanation](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/)). This broke our calls to the `nodesource` package repository, which we were using to install some tools at test time.

## Mitigation
The issue was mitigated on trunk by forcing an update of gnutls, which contains the new root certificates. 

## Prevention/followups
Pre-installing dependencies in docker. We should not be installing anything during the core build and test phase. While eventually docker rebuilds would fail and we would have to apply the same mitigation, this is much less urgent than a widespread CI breakage.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Looking at https://app.circleci.com/pipelines/github/pytorch/pytorch/387870/workflows/4e58fcb0-8f1c-4044-bdef-4bab293928c1/jobs/16285397

**Comment by malfet** [comment]
Removing SEV label as issue seems mitigated now, but want to keep eyes open for doc builds

**Comment by suo** [comment]
I think @zhouzhuojie said we were supposed to leave it on for tracking purposes.

Anyone I think it's good to leave up, the issue does not actually go away for users unless they rebase.
