### ISSUE TITLE
saved_variable hook

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [pytorch/pytorch#65981]
## ❓ Questions and Help
I am playing with saved_variable hook as described here 
https://deploy-preview-1655--pytorch-tutorials-preview.netlify.app/intermediate/autograd_saved_tensors_hooks_tutorial?utm_source=github&utm_campaign=bot_dp

I implemented the pack/unpack hook as follows
> def pack_hook(input):
>     interesting_stuff(input) 
>     return input
> 
> def unpack_hook(input):
>     return input

I train the same model for the same number of iterations with the same random seed. I compare the parameter gradient before and after commenting out **interesting_stuff(input)** and they are different. I also compared the input before after  **interesting_stuff(input)**  and it shows they are the same. I'm very confused about the possible cause.
interesting_stuff is a self-defined python function that calls a C++ implementation. 
Any hints or comments are highly appreciated!

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
