### ISSUE TITLE
[REBASE ON MASTER PLS] Many iOS jobs are broken due to expired cert

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#65988]
Errors look like:
```
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "**********" with a private key was found. (in target 'TestApp' from project 'TestApp'
```

or

```
error: Signing certificate is invalid. Signing certificate "Apple Development: Tao Xu (Q7PV3L5FKY)", serial number "<DVTSigningCertificateSerialNumber: 0x7ff766b8bef0>", is not valid for code signing. It may have been revoked or expired. (in target 'TestApp' from project 'TestApp')
```

## Incident timeline (PST)
- Failures began 9/30 @ ~11p
- Detected by looking at HUD at around the time failures began.

**Comment by xta0** [comment]
@suo  the fix is on the way - https://github.com/pytorch/pytorch/pull/65982

**Comment by suo** [comment]
@xta0 how come some of the ios jobs started failing with the cert expired and others did not?

**Comment by xta0** [comment]
The iOS x86_64 jobs don't need to be signed when building the TestApp. The iOS arm64 jobs will try building the static libraries together with an app to make sure they can be linked properly. Apple requires every app to signed with a valid developer account. In our case, I'm using my account.
