### ISSUE TITLE
Per-overload torch.ops API

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#65997]
Right now, there's a many-to-one correspondence between entries in native_functions.yaml and functions in torch.ops; specifically, all overloads get mapped to a single torch.ops function. For example, add.Tensor and add.out both show up as torch.ops.aten.add.

This is problematic for the introspection track of primtorch, because the metadata associated with various operators may vary across overloads. As a simple example, in https://github.com/pytorch/pytorch/issues/64874 the user wants to know what the mutable arguments are for the function, but they cannot figure this out without looking at the keyword arguments, because both add.Tensor (which doesn't mutate) and add.out (which does mutate) both get mapped to the same func (torch.ops.aten.add).

The proposal is to add support for indexing on functions in torch.ops that resolve them to a specific overload. So `torch.ops.aten.add` represents all overloads of add, but `torch.ops.aten.add["Tensor"]` represents only the `add.Tensor` overload. You can index with the empty string, e.g., `torch.ops.aten.addmv[""]` in cases where the overload has no overload name.

With this variant, you now can easily attach schema and other annotations on the overloaded functions without any ambiguity, and this makes it easier to do introspection. We also suggest changing `__torch_dispatch__` to accept overloads by default (BC-breaking) rather than overload bundles (traditional `torch.ops.aten.add`); as you can always recover the overload bundle from the overload (perhaps some property like `torch.ops.aten.add["Tensor"].parent`). Alternately, we introduce a new magic method `__torch_dispatch_ex__` that accepts overloads instead of overload bundles.

With this change, we can also offer default argument resolution easily (e.g., please give me the default values for all positional arguments). Previously, this was not easy to do because we would have had to redo overload resolution to understand what positional arguments we'd be getting.

Downside of this proposal: overload names are hypothetically not supposed to be part of public API, this change makes them visible from Python and BC concerns now apply to them. (This was already true for eager mode extensions).

----

An alternate proposal, is to introduce a new variant of torch.ops, maybe `torch.ops.variants` which distinguish between overloads. So you would have `torch.ops.aten.add['Tensor']` and `torch.ops.variants.aten.out` (note: we cannot reuse `torch.ops.aten` for variants with no overload name, as it is ambiguous in some cases; e.g., `addmv` has `addmv` (no overload name) and `addmv.out` (overload name); if I gave you torch.ops.aten.addmv, you would not be able to tell if this was representing all overloads (as is the legacy behavior) or just addmv (no overload name)).

cc @albanD

**Comment by ezyang** [comment]
The existing torch.ops binding code lives in torch/csrc/jit/python/init.cpp look for _jit_get_operation it is called from torch/_ops.py

**Comment by VitalyFedyunin** [comment]
@ezyang I'm having troubles finding right labels for this PR. Can you please help me.

**Comment by ezyang** [comment]
Notes:
* This fixes the torch.add(1, 2) problem
* `__torch_function__` should work on the overloads
