### ISSUE TITLE
Libtorch.so exporting mkl symbols?

### ISSUE THREAD

**Issue by quinor** [pytorch/pytorch#65991]
I am trying to integrate libtorch into my C++ codebase. I do however use Intel MKL internally and libtorch_cpu.so also exports mkl* symbols - linking them together causes the symbols to get mixed up and results in segfaults.

Is there a way to isolate symbols exported by libtorch *.sos or some other supported way for me to proceed?

I’m not using CMake for the builds and have to integrate the process into existing infrastructure.

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
