### ISSUE TITLE
All datapipes that take a single callable, should also take args and kwargs

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#65999]
For example, `Mapper`

https://github.com/pytorch/pytorch/blob/eac218dbc673405e7fdbd02559a63335ccfe7737/torch/utils/data/datapipes/iter/callable.py#L56-L57

and `Filter`

https://github.com/pytorch/pytorch/blob/eac218dbc673405e7fdbd02559a63335ccfe7737/torch/utils/data/datapipes/iter/selecting.py#L42-L49

do this, but `Demultiplexer`

https://github.com/pytorch/pytorch/blob/eac218dbc673405e7fdbd02559a63335ccfe7737/torch/utils/data/datapipes/iter/combining.py#L198-L199

doesn't. With this we can avoid using `functools.partial` everywhere.

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by NivekT** [comment]
@pmeier As part of an effort to make DataPipes' APIs more consistent with the APIs of TorchArrow, we actually plan to remove `args` and `kwargs` from `map` and `filter` in upcoming PRs. We encourage the use of `functools.partial` instead. Let us know if you have any concerns related to that. Thanks!
