### ISSUE TITLE
Difference between torch.rand and nn.init.uniform_ to create a learnable parameter

### ISSUE THREAD

**Issue by xml94** [pytorch/pytorch#66039]
I want to create a learnable parameter, but I do not know the difference between the two options:

1) para = torch.nn.Parameter(torch.rand(1))
2) para = torch.nn.Parameter(torch.tensor(1))
torch.nn.init.uniform_(para)

Thank you in advance.

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org
