### ISSUE TITLE
Building PyTorch without conda

### ISSUE THREAD

**Issue by mfoglio** [pytorch/pytorch#66034]
I am trying to build PyTorch on Ubuntu 18.04 without using Conda. I am trying to do that because of this issue with Nvidia Video Processing Framework integration ( https://github.com/NVIDIA/VideoProcessingFramework/issues/250#issuecomment-930611914 ), and its suggested solution ( https://github.com/NVIDIA/VideoProcessingFramework/issues/36#issuecomment-631765107 ).
It seems that to build PyTorch, I need to install magma. While in conda this is a simple `conda install -c pytorch magma-cuda110`, it seems that the only way to install magma without conda is to build it. 

I tried to do that with:
```
export PATH="/home/ubuntu/.local/bin:/usr/local/cuda-11.1/bin:${PATH}"
export LD_LIBRARY_PATH="/usr/local/cuda-11.1/lib64:${LD_LIBRARY_PATH}"

sudo apt install libopenblas-dev gfortran
wget http://icl.utk.edu/projectsfiles/magma/downloads/magma-2.6.1.tar.gz
tar -xzf magma-2.6.1.tar.gz
export CUDADIR=/usr/local/cuda
export OPENBLASDIR=/usr/lib/x86_64-linux-gnu/openblas
cd magma-2.6.1/
cp make.inc-examples/make.inc.openblas ./make.inc
make
```
But it results in the error:
```
nvcc fatal   : Unsupported gpu architecture 'compute_30'
Makefile:848: recipe for target 'magmablas/zaxpycp.o' failed
make: *** [magmablas/zaxpycp.o] Error 1
```
I am running Ubuntu 18.04 on a AWS EC2 instance with a T4.

My questions are:
- Is there a way to build PyTorch without conda? If it really gets so complicated, I might end up using conda, but for now I'd rather not
- Do I really need magma? I want to use Cuda.
- Is there a simpler way to install magma?

cc @brianjo @mruberry @malfet @seemethere @ngimel

**Comment by malfet** [comment]
> Is there a way to build PyTorch without conda? If it really gets so complicated, I might end up using conda, but for now I'd rather not

Yes, there are several CI configs that build PyTorch without conda, also Python Wheels can be installed on any system.

> Do I really need magma? I want to use Cuda.

No, you don't need MAGMA to compile functionally correct PyTorch that runs on GPUs, but MAGMA speeds up lots of linear algebra operations

**Comment by malfet** [comment]
Closing, as this does not seem to be reporting a bug in PyTorch or requesting a new features (building PyTorch without conda is already supported) Please use https://discuss.pytorch.org/ to ask general questions about PyTorch
