### ISSUE TITLE
Comparison operators throw internal assert for cpu scalar - cuda tensor op

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#66053]
## To Reproduce
```
In [9]: torch.tensor(2) < torch.tensor(2).cuda()
   ...: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-2970c9917e36> in <module>
----> 1 torch.tensor(2) < torch.tensor(2).cuda()

RuntimeError: t == DeviceType::CUDAINTERNAL ASSERT FAILED at "../c10/cuda/impl/CUDAGuardImpl.h":24, please report a bug to PyTorch. 
```
```
torch.tensor(2) + torch.tensor(2).cuda()
```
works. 
The problem was likely introduced in #60177 https://github.com/pytorch/pytorch/blob/8a307640db1097242602e570a271b04294974ae8/aten/src/ATen/TensorIterator.cpp#L817. The output device is declared to match first operand device, and computation of common device is skipped. The correct behavior (in the presence of cpu scalars) is to assign device of the output to be the common device of the inputs, but common device of the inputs is not known at the time TI is built. 
I don't think we can just comment out setting static device and dtype, because then dtype won't be forced to bool. We probably need `set_static_dtype` only function. 
cc @ysiraichi, @ezyang

**Comment by ezyang** [comment]
The proposed resolution SGTM. @ysiraichi do you think you can handle this?
