### ISSUE TITLE
Batched torch.cholesky_solve is incorrect for CUDA inputs in 1.9.1

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#66072]
## 🐛 Bug

cholesky_solve for batched inputs on CUDA returns the result that is very much different from non-batched or CPU versions of the functions.
The bug was originally reported in https://github.com/cornellius-gp/gpytorch/issues/1775.
The problem occurs in pip installed 1.9.1 version of PyTorch. Version 1.9.0 from pip doesn't have this bug.

## To Reproduce

```
pip install pytorch=1.9.1
```
Then
```
import torch
print(torch.__version__) # 1.9.1+cu102
torch.manual_seed(0)

A = torch.randn(11, 100, 100, device='cuda')
A = A @ A.transpose(-2, -1)
b = torch.randn(11, 100, 200, device='cuda')

print(torch.allclose(torch.cholesky_solve(b, A), torch.cholesky_solve(b.cpu(), A.cpu()).cuda())) # False, but should be True

print(torch.allclose(torch.cholesky_solve(b[0], A[0]), torch.cholesky_solve(b[0].cpu(), A[0].cpu()).cuda())) # True
```

## Expected behavior

Results from CPU and CUDA, batched and non-batched variants should match.

## Environment

The bug is reproducible in the current Colab environment by pip-installing PyTorch 1.9.1+cu102.

## Additional context

Locally built master branch of PyTorch with MAGMA and CUDA 11.3.1 doesn't reproduce the problem, but it's still important to investigate the cause of the discrepancy in the 1.9.1 build.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by VitalyFedyunin** [comment]
Need to run tests on binaries

**Comment by xwang233** [comment]
I did bisection on source build from cuda 11.4, and found https://github.com/pytorch/pytorch/pull/59120 to be related.

**Comment by malfet** [comment]
> I did bisection on source build from cuda 11.4, and found #59120 seems to be related.

But this PR was not picked for 1.9.1, it was already part of 1.9.0

**Comment by malfet** [comment]
Can not reproduce it in collab neither with 1.10.0-cu111 nor with 1.10.1-cu102
