### ISSUE TITLE
glibc error while importing torch

### ISSUE THREAD

**Issue by HMEIatJHU** [pytorch/pytorch#6607]
Install PyTorch following the instructions: http://pytorch.org/ 
It gives the error message when I import torch:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "XXX/anaconda3/envs/XXX/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by XXX/anaconda3/envs/XXX/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)

- PyTorch
- OS: CentOS release 6.7 (Final)
- PyTorch version: 3.0.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6
- CUDA/cuDNN version: 8.0/6.0

**Comment by yf225** [comment]
What's the version of glibc on your machine? (can probably run `ldd --version` to find out)

This is likely because you don't have glibc 2.17 installed, but our precompiled binary expects it. You could build from source to let it pick up the version of glibc you have on your machine.

**Comment by HMEIatJHU** [comment]
@yf225 Thanks very much! 

Yes, the glibc on the server that I use is 2.12. Is there a work-around except installing from source? I would like to stick to 0.3.1 for a while.

**Comment by yf225** [comment]
We only support glibc 2.17 at the moment. Can you try to update the glibc version on your machine?

**Comment by soumith** [comment]
updating glibc version is not a thing people do (it's not easy either).

@HMEIatJHU `0.3.1` actually supports CentOS 6.7 (I personally tested it myself), I am not sure why you are running into this error "GLIBC_2.17" not found.

But since you are running into the issue, easiest way of solving this is install from source.

**Comment by HMEIatJHU** [comment]
@soumith does supporting CentOS 6.7 mean that it can actually live with glibc 2.12? I found that is the most recent version on the server I am using. and conda install glibc does not help. 

Thanks very much. I will consider installing the current master.

**Comment by ianbstewart** [comment]
I am also having this issue. I know that the version of GLIBC in my conda environment is up to date (version 2.55) but pytorch seems to be using the global GLIBC on my machine (version 2.12). how can I configure pytorch so that it uses the correct GLIBC installation?

**Comment by deepakee13** [comment]
I am trying to install pytorch in conda environment. but the server runs on glibc12 version. I tried to install pytorch using source but got another configuration error while installing setup.py
