### ISSUE TITLE
Add input node id tracking to autograd profiler along with input tensor dimensions

### ISSUE THREAD

**Issue by alexmsettle** [pytorch/pytorch#66105]
## 🚀 Feature

The autograd profiler has a config option called [report_input_shapes](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_legacy.cpp#L444) this option causes the input tensor shapes of each operator to appear in the nvtx range of each op.  The sequence_nr, or unique id, of each operator is also reported in the nvtx range next to the tensor shapes.  This information is very useful for performance analysis, however in addition to the tensor shapes and sequence_nr it is also useful to know which operators produced the input tensors.  With this information the end user can reconstruct the network graph, which is otherwise quite difficult to get from PyTorch.   This feature request is asking that the sequence_nr of the nodes that produced each input tensor is recorded and made available to the profiler and reported in the nvtx range.  When the [inputSizes()](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/profiler_legacy.cpp#L363) function is called, another function can be called to return the list of sequence_nr's which produced the tensors represented by the inputSizes() function.  
 

## Motivation

I do performance analysis of PyTorch networks for my job at Nvidia and one of the main things I need to be able to do is to map each GPU kernel to the unique instance of the PyTorch op that launched it.  In addition I want to see where the op is in the network graph, a descriptive unique instance name, the tensor dimensions, parameters and op type are for each op.  The information available to the  profiler is quite good today, but is still a challenge to map back to the higher level PyTorch front end. 

## Pitch

I have actually implemented this feature already in a copy of PyTorch that is maintained internally at Nvidia.  I have also implemented software that parses the output of the profiler and generates a network graph visualization based on the sequence_nr and input sequence_nr's as proposed above.  I would like to make these changes available to the PyTorch community.

## Alternatives

We used to rely on a third party extension called PyProf which was used to capture some of the information listed above.  This software proved to be really error prone and required a lot of maintenance.  The proposed solution is simpler and less error prone as it relies on native PyTorch features.

## Additional context
The below timeline view shows the input sequence id numbers (seq_ids) and the sequence_nr (seq) of the aten::cudnn_convolution_op().  The user can follow the input seq_ids to find the ops that produced both the input activation and weight tensor.  The unique seq id of the node coupled with the input seq_ids to the node are all you need to construct the network graph.

![rn50_pyt_seq_ids_example](https://user-images.githubusercontent.com/37422826/135943201-1ceab767-f535-4551-b65a-788318dfe557.png)

Here's a screenshot from a network graph that was generated using the proposed feature.

![rn50_pyt_seq_ids_graph](https://user-images.githubusercontent.com/37422826/135943708-1e24064e-2fc0-4ad6-a21f-09bb812c2b9e.png)

cc @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by ngimel** [comment]
Why do you need to visualize computation graph along with profiling information? If you want to know where bottleneck is coming from, profiler has a "stack trace" feature that will point you to the source line that's responsible for a particular kernel. 
There are other tracing mechanism in pytorch that can provide visualization of the computation graph, but I don't see immediate value of this for profiling.

**Comment by robieta** [comment]
I've actually been thinking of adding this to the profiler. A couple use cases that I can think of:

1) We're currently adding Module hierarchy tracking, and I think it would be very useful to be able to see what part of a computation graph generated a particular string of events in a timeline. (If for no other reason than to make scanning around more ergonomic.)
2) If you have the entire computation graph you can make suggestions for code optimizations which otherwise would not be possible. (e.g. "if you reorder certain ops you can reduce peak memory usage", or "this unsqueeze may be unnecessary because torch.foo broadcasts")

Plus I have feeling that more visibility will foster other ideas down the line. @alexmsettle Is your code public? I'd be curious to browse it.
