### ISSUE TITLE
can you upgrade the website's pytorch?

### ISSUE THREAD

**Issue by yt605155624** [pytorch/pytorch#6612]
hello,I can setup pytorch in your website by conda of cuda8.0,but I can't use GPU，because of the cudnn 's version is too new,in other issue you have said that you have solve this problem in the master,I want to setup by github but always failed when make .. so,can you please upgrade the new version of pytorch which have solved the cudnn 'version problem?thank you~

**Comment by SsnL** [comment]
Are you talking about cudnn 7.1 RNN problem? We will when we are finished with the new release. We are trying our best to solve the few remaining issues. A workaround is to use cudnn 7, which isn't too big a downgrade.
