### ISSUE TITLE
Revise `gather()` method of `ShardedTensor`

### ISSUE THREAD

**Issue by dracifer** [pytorch/pytorch#66187]
Current `gather()` method in `ShardedTensor` does not support CPU and uses inefficient `dist.all_gather_object()` to gather sharded tensors. We need to update the implementation to support CPU and use `dist.gather()` when [NCCL support](https://github.com/pytorch/pytorch/blob/4c4525fa5cffb924d0e9b844449e6bd0a0df4aff/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1939) is ready. 

For more context, see https://github.com/pytorch/pytorch/pull/65671.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by kumpera** [comment]
The fix has being merged and ST::gather no longer uses object collectives.
