### ISSUE TITLE
How to export pytorch to ONNX alternative forward path

### ISSUE THREAD

**Issue by danshirron** [pytorch/pytorch#6620]
If i understand correctly using torch.onnx.export (@ezyang ) uses jit trace module in order to dump forward pathand then it converts to onnx.
Anyone has a suggestion on how to convert/trace for different path (In my example i need incremental_forward of wavenet model from https://github.com/r9y9/wavenet_vocoder/blob/master/wavenet_vocoder/wavenet.py line 236)?

**Comment by ezyang** [comment]
You could try making a module that wraps the module, but its forward calls incremental_forward instead.
