### ISSUE TITLE
Precision issue in matrix-vector multiplication

### ISSUE THREAD

**Issue by jvonbrecht** [pytorch/pytorch#66212]
## Issue description

Matrix-vector multiplication possibly executes in lower precision than expected when called on certain Nvidia GPUs. 

## Code example

import torch
import math
A = torch.randn(50,1000)/math.sqrt(50)
x = torch.randn(1000,1)
x = x/torch.norm(x,p=2)
cpu = A @ x
gpu = ( A.cuda() @ x.cuda() ).cpu()
err = torch.norm(cpu - gpu, p=2)/torch.norm(cpu, p=2)

In PyTorch version 1.8 and 1.9 on an RTX2080 and an RTX3090 produces the following outputs ---

GPU/Precision    err
2080/float32     ~1e-7
2080/float64     ~1e-16
3090/float32     ~3e-4 (*)
3090/float64     ~1e-16

The cpu vs relative error in (*) is several orders of magnitude higher than expected.

## System Info

- PyTorch or Caffe2: Pytorch
- How you installed PyTorch: pip
- OS: Windows 10
- PyTorch version: 1.8 and 1.9
- Python version: 3.8
- CUDA/cuDNN version: 11.1.1
- GPU models and configuration: RTX 2080 and RTX 3090

**Comment by vadimkantorov** [comment]
Is it because 3090 uses tf32 reduced width number format automatically under the hood?

Could you try `torch.backends.cuda.matmul.allow_tf32 = torch.backends.cudnn.allow_tf32 = False` before your benchmark?

**Comment by jvonbrecht** [comment]
Yep, thanks. That is precisely the issue. Same benchmark as before gives ~1e-7 with allow_tf32 = False, ~3e-4 otherwise.
