### ISSUE TITLE
[caffe2]Do you have a function description document for caffe2?

### ISSUE THREAD

**Issue by poppingcode** [pytorch/pytorch#6624]
Do you have a function description document for caffe2?
the same as " http://pytorch.org/docs/master/search.html?q=distributed&check_keywords=yes&area=default# ”

Many of the documents on the official web are missing.

**Comment by orionr** [comment]
We do have https://caffe2.ai/doxygen-python/html/annotated.html, which documents the Python API, but it's limited. We're looking to improve this in the future.
