### ISSUE TITLE
Switch from onnx.optimizer to onnxoptimizer

### ISSUE THREAD

**Issue by jcwchen** [pytorch/pytorch#66250]
## ❓ Questions and Help

If I understand correctly, PyTorch has already used ONNX >= 1.9 (now ONNX 1.10.1) so onnx.optimizer has already been moved out. If so, the following command should not work.

https://github.com/pytorch/pytorch/blob/dcf39f9bb9aa4a30ea82b35986522f79e17f43f8/caffe2/python/onnx/backend.py#L654

https://github.com/onnx/onnx/discussions/3758 A user found that he/she cannot use caffe2 to convert a model because onnx.optimizer is not found. How can we solve it? Thank you for your assistance!

**Comment by jcwchen** [comment]
Friendly ping @garymm @neginraoof @BowenBao Thanks!

**Comment by BowenBao** [comment]
This is tricky to resolve in PyTorch because afaik there are also projects that depend on caffe2 with onnx.optimizer (through older version of onnx). 

@jcwchen can the user use older onnx version accompanying caffe2? On the other hand I don't recall caffe2 supports onnx opset version > 10.

**Comment by garymm** [comment]
@BowenBao @jcwchen can we add a dependency from PyTorch onto https://github.com/onnx/optimizer and then replace calls to `onnx.optimizer` with `onnxoptimizer`?

**Comment by jcwchen** [comment]
> @jcwchen can the user use older onnx version accompanying caffe2? On the other hand I don't recall caffe2 supports onnx opset version > 10.

Yes the user used an older ONNX as a workaround.

> @BowenBao @jcwchen can we add a dependency from PyTorch onto https://github.com/onnx/optimizer and then replace calls to onnx.optimizer with onnxoptimizer?

Yes I believe that's the right way. Caffe2 should be able to use the optimizer from: https://github.com/onnx/optimizer. Otherwise, currently users cannot use the latest caffe2 with newer ONNX.

**Comment by garymm** [comment]
Tracked internally at Microsoft by https://msdata.visualstudio.com/Vienna/_workitems/edit/1512053

**Comment by jcwchen** [comment]
I think this issue has been resolved by https://github.com/pytorch/pytorch/pull/75718. Close here now.
