### ISSUE TITLE
PyTorch Documentation about `nn.CrossEntropyLoss` inaccurate

### ISSUE THREAD

**Issue by vellamike** [pytorch/pytorch#6626]
The documentation for nn.CrossEntropyLoss states
```
The input is expected to contain scores for each class.
input has to be a 2D Tensor of size (minibatch, C).
This criterion expects a class index (0 to C-1) as the target for each value of a 1D tensor of size minibatch
```
However the following code appears to work:
```
loss = nn.CrossEntropyLoss()
input = torch.randn(15, 3, 10)
input = Variable(input, requires_grad=True)
target = torch.LongTensor(15,10).random_(3)
target = Variable(target)
output = loss(input, target)
So my input is a 3D tensor and my targets is a 2D tensor.
```

It seems that `CrossEntropyLoss` is interpreting my input as `minibatch, N_CLASSES, SEQ_LEN` and my targets as `minibatch, SEQ_LEN`.  (see [this discussion](https://discuss.pytorch.org/t/multiclass-classification-with-nn-crossentropyloss/16370) where @ptrblck appears to confirm this)

Am I correct in saying that this documentation is incorrect or am I misunderstanding it? If confirmed I am happy to update it with a pull request.

- PyTorch
- OS: Ubuntu 16
- PyTorch version: `0.3.1`
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.5
- CUDA/cuDNN version: 9.0
- GPU models and configuration: GTX 1080Ti

**Comment by zou3519** [comment]
Yes, the documentation is outdated. CrossEntropyLoss follows the same input scheme as NLLLoss: http://pytorch.org/docs/master/nn.html?highlight=nllloss#torch.nn.NLLLoss .

Please feel free to update with a pull request!

**Comment by vellamike** [comment]
@zou3519 done - #6638

**Comment by zou3519** [comment]
Awesome, thanks @vellamike!
