### ISSUE TITLE
Android and mobile CI build on CircleCI timed out for seemingly no reason

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#66287]
There have been a few instances today where the android and mobile builds (pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build) have simply timed out near the beginning:

10/6: 
https://app.circleci.com/pipelines/github/pytorch/pytorch/390655/workflows/36cdfb8a-4fe8-4b86-8008-8decc0b595b8/jobs/16360119
10/7:
https://app.circleci.com/pipelines/github/pytorch/pytorch/390913/workflows/b2745a7f-b324-4744-91ed-1e49639129a2/jobs/16366656
https://app.circleci.com/pipelines/github/pytorch/pytorch/391172/workflows/347a7893-38e1-4c0c-b2b0-bc954f740354/jobs/16372641
https://app.circleci.com/pipelines/github/pytorch/pytorch/391195/workflows/2748a3d0-f64b-463c-b691-e76ecac9eb3a/jobs/16373151

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Just saw https://app.circleci.com/pipelines/github/pytorch/pytorch/392941/workflows/1d83e929-bd7c-482b-b058-5ca9b867baa9/jobs/16416115--maybe it does have to with checking out googletest?

**Comment by seemethere** [comment]
Android and mobile CI is on GHA now, closing
