### ISSUE TITLE
[Caffe2] Windows CI not building with CUDA enabled

### ISSUE THREAD

**Issue by harrysummer** [pytorch/pytorch#6631]
Dear Team,

I'm submitting this issue not for a specific bug or feature request, but asking for adding a windows CUDA build test for each caffe2 pull request. Recently, PR #6497 introduces some changes that is incompatible with Windows+CUDA build environment. Note that the current PR test `pr/caffe2-py2-cuda9.0-cudnn7-windows-build` is built with [CUDA disabled](https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-windows-build/434/consoleFull). And make my local building environment failed again. Would it be possible that we add a PR test on Windows CUDA environment so that similar issues won't happen again?

Thanks.

**Comment by bddppq** [comment]
The `pr/caffe2-py2-cuda9.0-cudnn7-windows-build` build variant in our CI is intended to guard windows cuda build, there might be some misconfiguration here caused cuda being disabled. @pjh5 Could you take a look?

**Comment by pjh5** [comment]
Fixed https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-windows-build/557/console now builds with CUDA
