### ISSUE TITLE
Better (optional) tensor list handling in native kernels

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#66328]
Here is the question: given `Tensor[]` or `Tensor?[]` in JIT schema, what C++ type should a kernel implementing this function take?

Historically, we have two divergent answers for `Tensor[]` case:

* The unboxed C++ API says you get a `TensorList` aka `ArrayRef<Tensor>`, which is essentially a contiguous array of Tensors
* The boxed API says you get `c10::List<Tensor>`, which is a refcounted pointer to an array of IValues (which happen to be Tensors)

There doesn't seem to be a single correct representation. The boxed representation is heinously inefficient (requiring a dynamic allocation for the array, and requiring ownership of all the tensors), but it has uniform representation and thus works with the JIT interpreter. The unboxed representation is good for direct C++ API calls (as it is compatible with `initializer_list`) but sometimes it is not very convenient; for example, if you have two `const Tensor&`, the only way to assemble them into a TensorList is to do a refcount bump at the new location (unless you play tricks like TensorRef--see OptionalTensorRef), similarly, if you have an ArrayRef<Tensor>, this is not convertible to ArrayRef<optional<Tensor>> without doing a dynamic allocation for the conversion. In an ideal world, we'd be able to support all these use cases:

* C++ API initializer list call `{x, y}`
* C++ API call with ArrayRef<Tensor>
* C++ API call with ArrayRef<TensorRef>
* Boxed call with IValue (internally containing c10::List)
* For optional, also:
  * C++ API call with ArrayRef<optional<Tensor{,Ref}>>
  * C++ API call with ArrayRef<Tensor{,Ref}> but where undefined tensors represent missing tensors
  * Boxed call with IValue (internally containing c10::List)

Without:

* Forcing refcount bumps
* Forcing an O(n) copy of the data structure to an alternate representation (no dynamic allocations)
* Efficient access from within the kernel

Well, you know what they say: if you can't pick one, pick 'em all. Let's make a `ITensorList` type which internally is a *union* over all of the representations we care about. As a start, this would be `ArrayRef<Tensor>` (the current cpp/dispatcher API type) and `c10::List<Tensor>*` (the boxed representation; this had better be a non-owning reference, BTW!) ITensorList would do an if-statement over the representation type and call the appropriate accessor logic depending on what it actually holds. It probably doesn't need to support too many APIs; just iteration and indexing.

The point is that the union is extensible over future types; if we ever have another type that would have required a conversion, we can instead add it directly to the union. The conversions then only happen when we read out the tensors, but since we read them individually, and as const references we have managed to eliminate the cost of allocating another intermediate data structure. The cost of this is the condition branch on access, but you should only really be iterating through the list once anyway.

Flipping the representation everywhere may be a bit painful, but we can put this in place for structured kernels and incrementally port in this way.

Once this is done, there are a lot of follow ups:

* Change dispatcher API to use this type
* Modify boxed-unboxed template to use this logic to avoid intermediate conversion
* Change C++ API to allow passing other types (like c10::List<Tensor>) by generating extra overloads. We could also perhaps make the C++ API directly accept `ITensorList` if this doesn't cause ambiguity (you'll need a lot of implicit constructors)
* Do this all again for list of optional tensors, with the added complication of punning undefined tensor and nullopt tensor. Also note that currently C++ API takes `c10::List<optional<Tensor>>` so we *definitely* want to bring back `ArrayRef<Tensor>` as a valid spelling in C++ API
* Maybe do this again for ArrayRef<int>? (Which gets stored as c10::List<int> in boxed world?) Note that actually ArrayRef<int> is a pretty good API on the kernel end when the size of the integer array is statically known or bounded because you can allocate the read out on the stack, but unfortunately we still allocate a full vector in those cases 

See also https://github.com/pytorch/pytorch/issues/54058

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @yf225 @glaringlee @ysiraichi @swolchok

**Comment by ezyang** [comment]
Yes this seems good. As part of (2) you'll need to teach the codegen how to construct ITensorList (logic for this goes in tools.codegen.api.translate)

**Comment by ysiraichi** [comment]
I am currently trying to make the dispatcher work well with `IList` (see #67964). However, it's been somewhat challenging due to a circular dependency:

- _TensorBody.h_ needs the definition of `IList<T>` (defined at _IList.h_)
    - Implementation of tensor methods have `IList<Tensor>` typed arguments
- _IList.h_ needs the definition of `List<T>` (defined at _List.h_)
    - Access of a nested type alias `List<T>::const_iterator`
- `List<T>` needs the definition of `IValue` (defined at _ivalue.h_)
    - Holds a `std::vector<IValue`, which needs its definition
- `IValue` needs the definition of `Tensor` (defined at _TensorBody.h_)
    - One of the types in its union
   
The whole problem is that _TensorBody.h_ also defines tensors' methods, meaning that `IList` can't be incomplete. So, one obvious solution is to move the definitions to a `cpp` file (e.g. _TensorMethods.cpp_).

Is this okay to do? Is there some other way to get around this problem?
@bdhirsh @albanD

**Comment by bdhirsh** [comment]
@ysiraichi we should be able to forward-declare the class, right? It looks like we already do that with `c10::List` [here](https://github.com/pytorch/pytorch/blob/ad0cd8a76e9ef268d4e49f0709978b16e6cce9ff/aten/src/ATen/templates/TensorBody.h#L40). As long as `IList` isn't used in any signatures with a default value specified in `TensorBody.h` Which I don't think `cat()` does, and hopefully no other operators do.

If that sounds right, then hopefully something like this will work at the top of `TensorBody.h`:

```
template<typename t>
class IList;  // forward declare the template.

using ITensorList = IList<Tensor>;
using IOptionalTensorList = IList<c10::optional<Tensor>>;
```

**Comment by bdhirsh** [comment]
At first I thought that `c10::List` has the same problem, since we use it in some signatures, and it's forward declared in `TensorBody.h`:
```
// c10::List is forward declared
namespace c10{
template<class T> class List;
}
...
// ... and later used directly in a tensor method signature

// aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
inline at::Tensor Tensor::index(const c10::List<c10::optional<at::Tensor>> & indices) const {
    return at::_ops::index_Tensor::call(const_cast<Tensor&>(*this), indices);
}
```

So we can get away with `c10::List` not being a complete type. Is that because all of the tensor methods defined in `TensorBody.h` take `c10::List` by const reference? Can we do the same thing with `IList` and take it by reference (and does lifetime extension save us here? https://abseil.io/tips/107).

**Comment by ysiraichi** [comment]
> Is that because all of the tensor methods defined in `TensorBody.h` take `c10::List` by const reference?

Yes! I think that's the case.

> Can we do the same thing with `IList` and take it by reference (and does lifetime extension save us here?

Now that you mention it, I think so. That's a good idea. I guess I had decided that `IList` should be always passed by value for no good reason. I think in this case, it makes more sense to use const-references, as you said.

**Comment by ysiraichi** [comment]
@ezyang @bdhirsh 
I was wondering if an actual interface (abstract container class) wouldn't be better in this case. Is the performance hit of virtual calls and `dynamic_cast` the only reasons why that wouldn't really be a good idea?
