### ISSUE TITLE
ERROR: could not find a version that satisfies the requirement torch==1.9.1+cu111(from versions 0.1.2, 0.1.2post1, 0.1.2post2 ERROR: No matching distribution found for torch==1.9.1+cu111

### ISSUE THREAD

**Issue by ZeeCur** [pytorch/pytorch#66399]
Hi I am having a problem when I type 

Pip install -requirement.txt

ERROR: could not find a version that satisfies the requirement torch==1.9.1+cu111(from versions 0.1.2, 0.1.2post1, 0.1.2post2
ERROR: No matching distribution found for torch==1.9.1+cu111

I use python 3.10 btw

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
Python-3.10 is not supported neither by 1.9.1 nor but 1.10 so neither pre-build pip nor conda package would be available.
