### ISSUE TITLE
IBM z14/15 simd support

### ISSUE THREAD

**Issue by quickwritereader** [pytorch/pytorch#66406]
## 🚀 Feature
SIMD vectorization for IBM z 15 architecture

cc @VitalyFedyunin

**Comment by quickwritereader** [comment]
implemented z arch 14/15 vector SIMD additions.
so far besides bfloat all other types have their SIMD implementation.

- it has 99% coverage and currently passing the local test.
- it is concise and the main SIMD file is only one header file
- it's using template metaprogramming, mostly. but still, there are a few macrosses left with the intention not to modify PyTorch much
- Sleef supports z15

**Comment by quickwritereader** [comment]
`USE_KINETO=OFF`

**Comment by quickwritereader** [comment]
team @ezyang 
So far, a lot of work has been done to improve and support the Z arch (z14, z15, Telum AI) and Power (power9, power10) arch. 
I believe that supporting these architectures makes Pytorch widely used.
I hope you incorporate my recent changes related to z15.
thanks

**Comment by quickwritereader** [comment]
#66407
I formatted the code with clang-format of yours.
team, were you able to check the issue and my Pr. IBM team alraedy checked it


@malfet , @VitalyFedyunin

**Comment by quickwritereader** [comment]
> #66407 I formatted the code with clang-format. team, could you check my Pr. IBM team already checked it
> 
> thanks
> 
> @malfet , @VitalyFedyunin

**Comment by quickwritereader** [comment]
@malfet thanks for approving my Pr.
I need my Pr to be merged/closed to get money for solving this issue. I also got approval from the IBM team.

thanks

**Comment by malfet** [comment]
@quickwritereader as New Year day fell on Saturday, most of the folks (including myself) are still in semi-afk mode today. Hopefully will be able to merge it in tomorrow
