### ISSUE TITLE
Feature Request: Source code pages should include link to GitHub file

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#66408]
And probably next to traditional [source] link there should be links to [github]. This would allow to navigate the code better and to view the most recent code version.

These source code pages: https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module

cc @brianjo @mruberry

**Comment by ain-soph** [comment]
If you mean for the links to github like this pattern in my small repo:  
https://ain-soph.github.io/alpsplot/utils/basic.html

I'm very willing to implement it.

**Comment by mruberry** [comment]
@ain-soph Most of operations are implemented exclusively in C++ and we autogenerate Python bindings to them.

**Comment by mruberry** [comment]
Yeah but the Python binding for an op doesn't tell you anything interesting about it.

**Comment by mruberry** [comment]
I don't think it's possible to show the C++ code using that technique, but I could be mistaken.

**Comment by ain-soph** [comment]
@mruberry 
So would you like to accept the PR to move from `viewcode` to `linkcode`? Not considering C++ backends for now.  
If so, I'd like to start working on it.

**Comment by mruberry** [comment]
@brianjo what do you think?

**Comment by vadimkantorov** [comment]
@msaroufim could this issue be closed now? :) 

https://x.com/marksaroufim/status/1861163215755116986

I guess what could be cool is being able to have some "tags" in the comments throughout the codebase and then pulling all these links into the docs for a given function. This would allow to link not only to wrapper, but also to relevant places in the underlying code paths

**Comment by ain-soph** [comment]
@vadimkantorov A potential improvement is to link the whole body of codes instead of the beginning line.

Here's my example: https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module
Here's the PyTorch example: https://pytorch.org/docs/main/generated/torch.mps.current_allocated_memory.html

**Comment by msaroufim** [comment]
Thank you @svekars! Let's close this, we can reopen another issue for other doc improvements
