### ISSUE TITLE
torch.isfinite incorrect output on cpu

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#66402]
```python
import torch

for dtype in (torch.complex64, torch.complex128):
    t = torch.tensor([-5.0100e+02-5.0100e+02j, -5.0100e+02+5.0100e+02j,
            -5.0100e+02-1.0012e+03j, -5.0100e+02+1.0012e+03j,
            -5.0100e+02-1.3438e+04j, -5.0100e+02+1.3438e+04j,
            -5.0100e+02-4.9884e+06j, -5.0100e+02+4.9884e+06j,
            -5.0100e+02-1.0000e+20j, -5.0100e+02+1.0000e+20j,
            5.0100e+02-5.0100e+02j,  5.0100e+02+5.0100e+02j,
            5.0100e+02-1.0012e+03j,  5.0100e+02+1.0012e+03j,
            5.0100e+02-1.3438e+04j,  5.0100e+02+1.3438e+04j,])

    print(f"DTYPE: {dtype} , Result:{torch.isfinite(t)}")
```

Output
```
DTYPE: torch.complex64 , Result:tensor([ True,  True,  True,  True,  True,  True,  True,  True, False, False,
         True,  True,  True,  True,  True,  True])
DTYPE: torch.complex128 , Result:tensor([ True,  True,  True,  True,  True,  True,  True,  True, False, False,
         True,  True,  True,  True,  True,  True])
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by Jup11ter** [comment]
I have observed similar incorrect output with `torch.Tensor.isfinite` from 1.9.0 to 1.11.0.
In 1.12.0, the output turns out to be all `True`, which is an expected output.
It seems like the incorrect output on `torch.Tensor.isfinite` is also fixed by this [pr #76606](https://github.com/pytorch/pytorch/pull/76606).

```python
import torch
t = torch.tensor(-5.0100e+02-1.0000e+20j)
print(torch.Tensor.isfinite(t))
print(torch.Tensor.isfinite(t.repeat(20)))
```

**Comment by Jup11ter** [comment]
> We don't backport bugfixes, so this is expected.

Thanks for your reply!
I can see that in the 1.12.0 version, this bug is already fixed.
I'm just curious that whether the buggy output on `torch.Tensor.isfinite` and `torch.isfinite` has the same root cause and is fixed by the same pr.

**Comment by kshitij12345** [comment]
@Jup11ter yes, the root cause was same and both were fixed with the mentioned PR.

**Comment by Jup11ter** [comment]
@kshitij12345 Oh, I get it. Thank you very much. :-）
