### ISSUE TITLE
[Caffe2] Unable to run ONNX models with Caffe2 backend

### ISSUE THREAD

**Issue by jeffreyksmithjr** [pytorch/pytorch#6644]
I attempted to execute the steps shown in the Caffe2 tutorial entitled Run an ONNX model with Caffe2: https://render.githubusercontent.com/view/ipynb?commit=c04c7d721da9b1fa1dd0fe5d5551086c61877586&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6f6e6e782f7475746f7269616c732f633034633764373231646139623166613164643066653564353535313038366336313837373538362f7475746f7269616c732f4f6e6e78436166666532496d706f72742e6970796e62&nwo=onnx%2Ftutorials&path=tutorials%2FOnnxCaffe2Import.ipynb&repository_id=110873948&repository_type=Repository#Run-an-ONNX-model-with-Caffe2

With the squeezenet model it throws the error:
```
warning: onnx optimizer is unable to parse input model. (The IR version of the ONNX model may be too old.)
```

So, I also tried every model from the example models repo: https://github.com/onnx/models and none of them worked. Most of them were learned in CNTK and there appears to be a range of issues with running models learned in CNTK from Caffe2.

e.g.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/onnx/backend/base.py", line 57, in run_model
    return cls.prepare(model, device, **kwargs).run(inputs)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/onnx/backend.py", line 730, in prepare
    super(Caffe2Backend, cls).prepare(model, device, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: model with IR version >= 3 must specify opset_import for ONNX
```

Caffe2 version is 0.8.dev.2018.04.16. 
OS is Debian Stretch.

**Comment by bddppq** [comment]
The `warning: onnx optimizer is unable to parse input model...` is an warning, not an error. It says the model is too old so the new optimizer is not able to do optimization.
re. the models in the onnx/models repo, which model did you run? I'm asking because most of them are converted from caffe2 and we have CI to make sure they are passing. The error you posted indicates the model exported from CNTK failed at the onnx checker's verification (meaning the model is invalid).

**Comment by bddppq** [comment]
Closing because this is unrelated to caffe2 and pytorch. Please create an issue either in the onnx/model or the cntk repo.
