### ISSUE TITLE
Deprecating Python 3.6 support

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#66462]
Python 3.6 is set for EOL sometime later, per [PEP 494](https://www.python.org/dev/peps/pep-0494/#lifespan) this year we should:

- [x] Move all CI workflows off of Python 3.6
- [x] Remove Python 3.6 from our binary builds workflows

`1.10.X` should be the last official PyTorch release to support Python 3.6

cc @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by cdeepali** [comment]
As we remove python 3.6 support, we will need to remove `dataclasses` package from the dependencies. @malfet, shall I work on PR for this change?

**Comment by seemethere** [comment]
> As we remove python 3.6 support, we will need to remove `dataclasses` package from the dependencies. @malfet, shall I work on PR for this change?

We'd happily accept a PR for this change!

**Comment by cdeepali** [comment]
Added PR - https://github.com/pytorch/pytorch/pull/71086 to remove `dataclasses` package.

**Comment by malfet** [comment]
Everything is done, closing
