### ISSUE TITLE
bug of Variable when building from source

### ISSUE THREAD

**Issue by cddlyf** [pytorch/pytorch#6646]
When I build the pytorch from latest source, a very unreasonable bug appears.

`import torch
from torch.autograd import Varibale
a = Variable(torch.Tensor(3,4))
print(a)
`
The output shows that a is a Tensor but not a Variable? Why?? 

`-3.4105e-05  4.5729e-41 -3.4105e-05  4.5729e-41
 1.4047e-35  3.0943e-41  0.0000e+00  0.0000e+00
 2.8175e+20  4.5559e-41 -9.0001e-06  4.5729e-41
[torch.FloatTensor of size (3,4)]`

the torch version is `0.4.0a0+cd21127`

**Comment by cddlyf** [comment]
When I run the exact same code in 0.3.1.post2, it is correct.

**Comment by soumith** [comment]
on master, Tensors and Variables are merged and they are the same thing.

**Comment by cddlyf** [comment]
so it is a new feature in 0.4.0?

**Comment by cddlyf** [comment]
@soumith Is there any doc about this new design?

**Comment by fmassa** [comment]
There is some discussion in https://github.com/pytorch/pytorch/issues/2633
