### ISSUE TITLE
[ci] Tracking issue: GHA cancellations

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#66490]
Cancellations are bad for two reasons:
- Loss of signal at PR time.
- They aggregate to a red X so it prevents "green signal" on PRs.

Of course, there are valid reasons to cancel a workflow (say, if you push a new commit to a PR). One way to see a clean set of "bad" cancellations is by looking at cancellations on master. In a steady state, there should be 0 cancellations. Dataset covering cancellations on master in the last 7d: https://fburl.com/scuba/opensource_ci_jobs/wk7dkzr8

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Should we change the HUD to make cancelled results red for trunk CI?

**Comment by seemethere** [comment]
I don't think we're experiencing this anymore, we can probably close.
