### ISSUE TITLE
Periodic jobs have been skipped on trunk for a long long time now

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#66507]
Should be fixed by https://github.com/pytorch/pytorch/pull/66264.

The concern, however, is that we did not detect this for the longest time, because the HUD aggregates skips to be "green" signal, when in reality it should come out as red, since nothing should be skipped on trunk.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Fix have landed, clsoing
