### ISSUE TITLE
Identify if there are more people struggling with #66434

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#66510]
People who experience the same thing on their PRs as described in https://github.com/pytorch/pytorch/issues/66434 would be having a p bad experience with OSS CI where >10 things are red on their PRs almost all of the time.

We want to identify if anyone is having similar problems and rectify the issue.

Action:
1. Go through the Dr. CI logs and look for error messages like "Unable to locate credentials. You can configure credentials by running "aws configure"." and "This build was not run because we couldn't find the "org-member" context".
2. Detect people that this affects and and notify them of how to solve this issue

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
@seemethere : we just need to add documentation on how to avoid such situations?
@malfet: Also, does it really matter once we migrate away from CircleCI?

**Comment by janeyx99** [comment]
This issue isn't relevant anymore as our PR CI is on GHA now
