### ISSUE TITLE
add unpack_sequence and unpad_sequence functions

### ISSUE THREAD

**Issue by dayyass** [pytorch/pytorch#66549]
## 🚀 Feature

Add inverse function for `torch.nn.utils.rnn.pack_sequence` that takes `PackedSequence` object as input and returns list of variable length `Tensors`.

## Motivation

Working with sequential data with variable length (e.g. working with text or time series using LSTM) the proposed function is almost always needed but you have to implement it yourself.

## Pitch

n/a

## Alternatives

n/a

## Additional context

Usage example ([link](https://gist.github.com/dayyass/b64cdf552576b64c282c3cf06f39b062)):
```python3
import torch
from torch.nn.utils.rnn import pack_sequence, pad_packed_sequence


def unpack_sequence(packed_sequences):
    """Unpacks PackedSequence into a list of variable length Tensors"""
    
    unpacked_sequences = []
    
    padded_sequences, lengths = pad_packed_sequence(packed_sequences, batch_first=True)
    
    max_length = padded_sequences.shape[1]
    idx = torch.arange(max_length)

    for seq, length in zip(padded_sequences, lengths):
        mask = idx < length
        unpacked_seq = seq[mask]
        unpacked_sequences.append(unpacked_seq)
        
    return unpacked_sequences


a = torch.tensor([1,2,3])
b = torch.tensor([4,5])
c = torch.tensor([6])

sequences = [a, b, c]
packed_sequences = pack_sequence(sequences)
unpacked_sequences = unpack_sequence(packed_sequences)

assert all([torch.allclose(a, b) for a, b in zip(sequences, unpacked_sequences)])
```

cc @albanD @mruberry @jbschlosser @walterddr @zou3519

**Comment by jbschlosser** [comment]
Thanks for the detailed request + PR! Seems good to me - will do a review pass on the linked PR shortly.
