### ISSUE TITLE
Scalar equality check does not use tolerances specified in OpInfo decorators

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#66556]
## 🐛 Bug

As in the title.

## To Reproduce

```python
# File: test_foo.py

import torch
import numpy as np

from torch.testing._internal.common_utils import TestCase, run_tests
from torch.testing._internal.common_device_type import instantiate_device_type_tests, ops
from torch.testing._internal.common_methods_invocations import OpInfo, DecorateInfo, toleranceOverride, tol, all_types_and, _dispatch_dtypes

op = OpInfo(
    'foo',
    op=(lambda x:x),
    dtypesIfCPU=_dispatch_dtypes((torch.bfloat16,)),
    dtypesIfCUDA=_dispatch_dtypes(),
    decorators=[DecorateInfo(toleranceOverride({torch.bfloat16: tol(atol=1e-03, rtol=1e-03)}), 'TestFoo', 'test_foo')])


class TestFoo(TestCase):

    @ops([op])
    def test_foo_success(self, device, dtype, op):
        self.assertEqual(torch.tensor(21.3750, dtype=torch.bfloat16), np.array(21.390625, dtype=np.float32), exact_dtype=False)

    @ops([op])
    def test_foo_failing(self, device, dtype, op):
        self.assertEqual(torch.tensor(21.3750, dtype=torch.bfloat16), np.float32(21.390625), exact_dtype=False)

instantiate_device_type_tests(TestFoo, globals())

if __name__ == '__main__':
    run_tests()
```

Running
```bash
python test_foo.py -k test_foo_success_foo_cpu_bfloat16
```
succeeds but the following not:
```bash
$ python test_foo.py -k test_foo_failing_foo_cpu_bfloat16
F
======================================================================
FAIL: test_foo_failing_foo_cpu_bfloat16 (__main__.TestFooCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/pearu/git/pytorch/pytorch/test_foo.py", line 24, in test_foo_failing
    self.assertEqual(torch.tensor(21.3750, dtype=torch.bfloat16), np.float32(21.390625), exact_dtype=False)
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1788, in assertEqual
    self.assertEqual(x.item(), y, atol=atol, rtol=rtol, msg=msg,
  File "/home/pearu/git/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 1957, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Scalars failed to compare as equal! Comparing 21.375 and 21.390625 gives a difference of 0.015625, but the allowed difference with rtol=1.3e-06 and atol=1e-05 is only 3.7807812500000005e-05!

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
```

Apparently, the tolerances specified in OpInfo decorators are ignored when comparing torch tensor against numpy scalar value.

## Expected behavior

`test_foo_failing_foo_cpu_bfloat16` should succeed.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0a0+gitc545b09

**Comment by mruberry** [comment]
@pmeier Would you verify this is fixed?

**Comment by pmeier** [comment]
There was no bug in the first place. The `OpInfo` in the example is configured wrong. We need two decorators here and change `test_foo` to `test_foo_success` and `test_foo_failing` respectively. With that, both tests pass fine.

That leaves the question why one of this test is passing without decorator while the other one is failing. It comes down to different default tolerances for tensor-like and scalar comparison. 

https://github.com/pytorch/pytorch/blob/3d37f5b05273304fb30fe8102434bdd5ee490bd7/torch/testing/_comparison.py#L45-L47

In both cases we take the maximum available tolerance for the given types. For the tensor-likes from the first test this means we are using `rtol=0.016, atol=1e-5` which is sufficient to pass the test.

The difference for scalars is however that `self.assertEqual` converts them to vanilla Python scalars, e.g. `float`, and uses

https://github.com/pytorch/pytorch/blob/3d37f5b05273304fb30fe8102434bdd5ee490bd7/torch/testing/_internal/common_utils.py#L1502-L1506

to determine the dtype for the default tolerances. Thus, for the scalar test we use `rtol=1.3e-6, atol=1e-5` as tolerances, which are not sufficient to pass the test. 

Note that this is a quirk of `assertEqual`. The user-facing `torch.testing.assert_close` does not allow you to compare tensors and scalars to avoid these pitfalls:

```py
>>> torch.testing.assert_close(torch.tensor(21.3750, dtype=torch.bfloat16), np.float32(21.390625), atol=1e-3, rtol=1e-3)
TypeError: No comparison pair was able to handle inputs of type <class 'torch.Tensor'> and <class 'numpy.float32'>.
```
