### ISSUE TITLE
cannot load forum

### ISSUE THREAD

**Issue by lesliejackson** [pytorch/pytorch#6655]
cannot load forum,  the error code is ERR_TIMED_OUT
I get 300ms when ping discuss.pytorch.org
I use Chrome on Win10-64

**Comment by soumith** [comment]
it seems to be online. are you behind great firewall?

**Comment by lesliejackson** [comment]
I tried to turn off the firewall but it didn't work
I can log in any other official websites of Pytorch except the forum
thanks for your reply @soumith

**Comment by SsnL** [comment]
@lesliejackson I think @soumith meant that the one set by the government rather than the one on your machine.. Forum is known to not loadable in China..
