### ISSUE TITLE
DISABLED test_timeout (__main__.TestDataLoader)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#66635]
This test fails nondeterministically on master. Here are all the failures in the last 30 days: https://fburl.com/scuba/opensource_ci_jobs/wa4res83

There are only two, so it may be appropriate to do a retry or something for this test. Nevertheless, I am disabling for now while we decide what to do it.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Closed issue as this test has been fixed
