### ISSUE TITLE
IntList parsing is inconsistent wrt tensors and integers

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#6663]
We generally allow items that are convertible to Ints as elements in IntLists, e.g.:

```
>>> torch.zeros((torch.tensor(2), np.int64(3)))

 0  0  0
 0  0  0
[torch.FloatTensor of size (2,3)]
```

Although it's not clear we always want to:
```
>>> torch.zeros((torch.tensor(2.3), np.float(3.7)))

 0  0  0
 0  0  0
[torch.FloatTensor of size (2,3)]

>>> np.zeros((2, 3.7))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
```

This is also inconsistent with how we bind to Ints/Scalars in a number of ways:

1) We allow variables with `requires_grad=True`:
```
>>> torch.zeros((torch.tensor(2, requires_grad=True), 3))

 0  0  0
 0  0  0
[torch.FloatTensor of size (2,3)]
```

2) We don't allow non-tuple convertible elements (if they are first) in IntList, e.g.:
```
>>> torch.zeros(2, torch.tensor(3))

 0  0  0
 0  0  0
[torch.FloatTensor of size (2,3)]
```

```
>>> torch.zeros(torch.tensor(2), 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: zeros(): argument 'size' (position 1) must be tuple of ints, not Tensor
```

3) We don't bind (non-variable) convertible elements to Ints
```
>>> torch.cumsum(torch.randn(2,3), dim=np.int64(0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cumsum(): argument 'dim' must be int, not numpy.int64
```

There are probably more cases as well.  The main issue comes from the two-stage parse: the binding stage is not the same as the read-out stage.  For example, at the parsing stage for Int64, we call `THPUtils_checkLong`, but in the read-out stage we call `  long long value = PyLong_AsLongLongAndOverflow(obj, &overflow);` which has the convert to int behavior.  So essentially, we have both implicit conversions and function overloading, which gets very complicated.

We could fix this by making the passes the same, e.g. storing the results in the binding stage and then just reading them out, however this could be slower, particularly in cases where e.g. only the last element doesn't bind.

CC @ezyang @colesbury.

**Comment by ezyang** [comment]
Most of the cited examples here look fixed:

```
>>> import torch
import numpy as np
>>> import numpy as np
>>> torch.zeros((torch.tensor(2), np.int64(3)))
tensor([[0., 0., 0.],
        [0., 0., 0.]])
>>> torch.zeros((torch.tensor(2.3), np.float(3.7)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: zeros(): argument 'size' must be tuple of ints, but found element of type Tensor at pos 1
>>> np.zeros((2, 3.7))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object cannot be interpreted as an integer
>>> torch.zeros((torch.tensor(2, requires_grad=True), 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
>>> torch.zeros(2, torch.tensor(3))
tensor([[0., 0., 0.],
        [0., 0., 0.]])
>>> torch.zeros(torch.tensor(2), 3)
tensor([[0., 0., 0.],
        [0., 0., 0.]])
>>> torch.cumsum(torch.randn(2,3), dim=np.int64(0))
tensor([[ 0.1480,  1.0421, -0.6716],
        [ 0.6015,  1.2345, -0.2469]])
```

Going to close this.
