### ISSUE TITLE
RFC: Create unified CI experience for pytorch and domain libraries

### ISSUE THREAD

**Issue by langong347** [pytorch/pytorch#66656]
## Introduction
This is a project to **consolidate** and **standardize** CI process across pytorch, vision, text and audio to allow a uniform CI experience. The current status: each pytorch repository runs its own CI process with no shared standards and the builds of domain libs can be broken due to dependency on `pytorch`. 

### Standardization
- use standard specifications of CI workflows for domain libraries
- develop tooling to support/automate the generation of the standards

### Consolidation 
- create a central repo to host the common build rules that can be shared across repositories
- build e2e CI process across dependent repositories as [integration test to early detect errors](https://github.com/pytorch/builder/issues/833)

### Scope
We started with consolidating linux binary builds for CircleCI and intended to cover Github Action. At the time of writing this proposal all domain libraries are 100% on CircleCI.
### Design
Use `pytorch/builder` as the central repository to:
- host and test changes to common build scripts
- trigger CI of pytorch and domain libraries.
- host tools for CI template generation for domain libraries

### Main Tasks
- [x] https://github.com/pytorch/builder/issues/866
  - [x] https://github.com/pytorch/builder/pull/860
  - [x] https://github.com/pytorch/builder/pull/861
- [ ] https://github.com/pytorch/builder/issues/865 
  - [ ] https://github.com/pytorch/builder/pull/874
  - [ ] https://github.com/pytorch/builder/pull/877
- [x] https://github.com/pytorch/builder/issues/880 
 

cc @ezyang @malfet @zhouzhuojie @janeyx99 @seemethere @orionr @pytorch/pytorch-dev-infra

**Comment by atalman** [comment]
This task is old, Project Nova adressed most of this. Hence closing
