### ISSUE TITLE
win-vs2019-cuda11.3-py3 OOMing

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#66674]
Started happening on master 10/14 1:26p pacific. Not marking as a SEV yet since the failures still appear to be intermittent, but we can upgrade it as necessary.

Examples (you have to download the full raw log because our logs are so long):
- https://github.com/pytorch/pytorch/runs/3901020217
- https://github.com/pytorch/pytorch/runs/3899386168

If you scroll to the bottom of these, you'll see messages like:
```
2021-10-15T00:44:14.3340156Z C:/actions-runner/_work/pytorch/pytorch/aten/src\ATen/core/jit_type.h(2016): catastrophic error: out of memory
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
These instances have 61GB of memory, if we're running out then something's wrong with the tests

**Comment by suo** [comment]
It's just the build :O. I'll try reducing ninja parallelization and see what that buys us

**Comment by suo** [comment]
Uh okay I don't know how to control build parallelization for windows jobs. @peterjc123 do you know how?

**Comment by peterjc123** [comment]
@janeyx99 https://github.com/pytorch/pytorch/blob/master/tools/setup_helpers/cmake.py#L29 Ninja will be used if it is found and not explicitly disabled.

**Comment by malfet** [comment]
Removing high priority, as the issue has been mitigated, but we need to have a better metric here

**Comment by seemethere** [comment]
This has already been mitigated, closing
