### ISSUE TITLE
Can't integrate pytorch-mobile with react-native android app

### ISSUE THREAD

**Issue by Vergil0327** [pytorch/pytorch#66685]
### Description
I want to integrate pytorch mobile in react-native app. though I can build successfully but get error after I invoke method

error messages:
couldn't find DSO to load: libpytorch_jni.so
SoSource 0: com.facebook.soloader.ApkSoSource[root=/data/data/com.example.pytorchmobile/lib-main flags = 1] ...

also try this, but not works
```gradle
implementation ("com.facebook.react:react-native:+") {
        exclude module: 'fbjni-java-only'
}
```
According to [this](https://github.com/facebook/react-native/pull/31191), react-native@0.66.0 already upgrade android fbjni dependency to 0.2.2.

### React Native version:
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 96.56 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.6 - ~/.nvm/versions/node/v12.22.6/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.6/bin/npm
    Watchman: 2021.10.11.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/vergil/.rvm/rubies/ruby-2.6.6/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 3.7.4 - /Users/vergil/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. use [reate-react-native-library](https://github.com/callstack/react-native-builder-bob) to create project
```bash
$ npx reate-react-native-library testproject
```
2. follow [instruction](https://pytorch.org/mobile/android/) to add Gradle dependancies
3. try this [demo app example](https://github.com/pytorch/android-demo-app/blob/master/SpeechRecognition/README.md)
4. build android app & run

I also add these to testproject > example > android > app > build.gradle to fix "More than one file was found with OS independent path 'lib/x86/libfbjni.so'" issue and prevent pytorch model from compression in the APK

```gradle
...

android {
     packagingOptions {
        pickFirst 'lib/arm64-v8a/libfbjni.so'
        pickFirst 'lib/armeabi-v7a/libfbjni.so'
        pickFirst 'lib/x86/libfbjni.so'
        pickFirst 'lib/x86_64/libfbjni.so'

        pickFirst 'lib/arm64-v8a/libc++_shared.so'
        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
        pickFirst 'lib/x86/libc++_shared.so'
        pickFirst 'lib/x86_64/libc++_shared.so'
    }

    aaptOptions {
        // pytorch model
        noCompress 'pt'
        noCompress 'ptl'
    }
}
```

### Expected Results
should load model and run successfully

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by Vergil0327** [comment]
I see related [discussion](https://discuss.pytorch.org/t/pytorch-not-compatible-with-react-native-library/73841/7)
 I think It takes some time to wait for react-native team to updating react-native master.

**Comment by devjta** [comment]
I know thats an old bug, but its still there...

Its NOT COMPATIBLE at all, because pytorch-android-lite isnt. Simple as that. 

For whatever reasons, pytorch-android-lite has its OWN libfbjni.so for arm64 which has 178kb. NO VERSION of libfbjni.so has THAT size.

When I exclude fbjni from pytorch_android_lite import, it will not WORK at all. Getting this _Unwind_resume error:
dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.planradar.demoML-IK4F5CYrCuaaR7Csu8YHzQ==/lib/arm64/libpytorch_jni_lite.so"...

Is there a reason why it needs an own version of that shared-object file? Will open new bug entry anyway.
