### ISSUE TITLE
Without ninja, changing a .h files doesn't cause recompilation

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#6669]
How to reproduce:
```
NO_CUDA=1 DEBUG=1 python setup.py build_deps develop
# change e.g. python_numbers.h to add a bunch of code with syntax errors
NO_CUDA=1 DEBUG=1 python setup.py build_deps develop # WORKS
```

installing ninja fixes this problem.

**Comment by apaszke** [comment]
I think that's a known issue with `setuptools`. I remember I used to alwasy `rm -rf build && python setup.py develop` before we started using `ninja`.

**Comment by gchanan** [comment]
we could maybe solve it with `depends`?  Note a huge deal, I'll just make sure to use ninja.

**Comment by apaszke** [comment]
Maybe? Not sure, as long as you have `ccache` the `rm -rf` is pretty much free
