### ISSUE TITLE
Different package names between conda and pip messes with requirements.txt looking for torch

### ISSUE THREAD

**Issue by luzuku** [pytorch/pytorch#66785]
## 🐛 Bug

Following the instructions on https://pytorch.org/get-started/locally/: conda installs as pytorch. pip installs as torch. The new "pytorch" messes with a lot of the requirements.txt of other packages looking for "torch". This basically makes conda installs unpractical.

Or is this by design?

## Expected behavior

Pytorch should be installed as torch and not pytorch

cc @ezyang @seemethere @malfet

**Comment by ezyang** [comment]
I wonder if @soumith knows why we named the conda package pytorch. Pretty sure there was a good reason. In any case, even if you conda install pytorch, it still gets advertised to Python proper as torch, so requirements.txt should work. If there is a specific situation that doesn't work please feel free to reopen with more detailed info.
