### ISSUE TITLE
TorchBench Performance Event: Score down 0.6% on 20210712

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#66800]
## 🐛 Bug

On 20210712, TorchBench Performance Score drops 0.8%. The reason are the following tests:

```
+-----------------------------------------+----------------+----------------+----------+
|             Benchmark Tests             | 20210628+cu102 | 20210712+cu102 |  Delta   |
+-----------------------------------------+----------------+----------------+----------+
| test_train[hf_T5-cpu-eager]             |         23.578 |        16.9459 | -28.13%  |
| test_eval[soft_actor_critic-cuda-eager] |     0.00915548 |       0.010244 | +11.889% |
+-----------------------------------------+----------------+----------------+----------+
```

## Bisection result
The root cause of test_train[hf_T5-cpu-eager] speedup is commit 3cf267bfa6.
The root cause of test_eval[soft_actor_critic-cuda-eager] slowdown is commit 81e36d02a6.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin @ngimel @fritzo @neerajprad @alicanb @nikitaved

**Comment by xuzhao9** [comment]
After our investigation, it shows the regression of test_eval[soft_actor_critic-cuda-eager] could be caused by this line: https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54 because it forces a CUDA sync and CPU has to block to enforce the constraint. @neerajprad

**Comment by xuzhao9** [comment]
After our investigation, the regression could be caused by this line: https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54. The `valid.all()` call forces a CUDA sync.

**Comment by fritzo** [comment]
@xuzhao9 the line you pointed to is validation logic that helps new users diagnose errors. More confident users who want training to run faster can disable validation either globally `torch.distributions.Distribution.set_default_validate_args(False)` or disable validation on a single distribution via `SomeDistribution(..., validate_args=False)`.

Can you please either flag this "performance regression" as ok, or update the benchmark to disable validation?

**Comment by neerajprad** [comment]
> After our investigation, the regression could be caused by this line: [81e36d0#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54](https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54). The added `valid.all()` call forces a CUDA sync.

I don't see a difference in this diff. Prior to this we were still checking for this using `if not support.check(value).all()`. The line merely breaks this into two steps.

**Comment by xuzhao9** [comment]
> > After our investigation, the regression could be caused by this line: [81e36d0#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54](https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54). The added `valid.all()` call forces a CUDA sync.
> 
> I don't see a difference in this diff. Prior to this we were still checking for this using `if not support.check(value).all()`. The line merely breaks this into two steps.

Please note that `if not support.check(value).all()` is on line 287(https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R287). The `valid.all()` call added by this diff is on line 54 (https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54)

**Comment by neerajprad** [comment]
> Please note that `if not support.check(value).all()` is on line 287([81e36d0#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R287](https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R287)). The `valid.all()` call added by this diff is on line 54 ([81e36d0#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54](https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54))

@xuzhao9: Thanks for explaining and flagging this. I took a look again: this check is also there in the earlier version, but I see that while this was supposed to replace it with a more verbose message, the older check (now on L62) still exists and running this check again might be causing this perf regression. Let me push a fix for this. Is there a way to see if that resolves this?

**Comment by xuzhao9** [comment]
> > Please note that `if not support.check(value).all()` is on line 287([81e36d0#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R287](https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R287)). The `valid.all()` call added by this diff is on line 54 ([81e36d0#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54](https://github.com/pytorch/pytorch/commit/81e36d02a6#diff-3f2b3bd2a60497fca8d91e7c3ab1b822e0f0d29b2ffab34e5e546f82f7605581R54))
> 
> @xuzhao9: Thanks for explaining and flagging this. I took a look again: this check is also there in the earlier version, but I see that while this was supposed to replace it with a more verbose message, the older check (now on L62) still exists and running this check again might be causing this perf regression. Let me push a fix for this. Is there a way to see if that resolves this?

Yes! You can utilize the "TorchBench ondemand CI" to verify your change works.
Here is how to do this:
1. In your PR body, add a line called "RUN_TORCHBENCH: soft_actor_critic"
2. Create a new push to your PR
3. In the CI list, there is an item of "TorchBench CI", and after it finishes successfully, I will manually check the result and see if there is an expected speedup of the test.

**Comment by xuzhao9** [comment]
@neerajprad Thanks for submitting https://github.com/pytorch/pytorch/pull/67725. Unfortunately, the TorchBench ondemand CI only supports on testing pytorch/pytorch branches for security reasons. Could you please push your change to a branch on pytorch/pytorch and try it again?

**Comment by xuzhao9** [comment]
The fix PR has been merged. Closing this issue. Thanks @neerajprad for helping resolve this issue.

**Comment by xuzhao9** [comment]
The fix has been confirmed in TorchBench V1 nightly CI: https://github.com/pytorch/benchmark/issues/545
