### ISSUE TITLE
`random_fullrank_matrix_distinct_singular_value` may not be robust for creating large invertible matrices on CUDA

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#66856]
## 🐛 Bug

`random_fullrank_matrix_distinct_singular_value` from `torch.testing._internal.common_utils` is commonly used in tests for creating matrices that are invertible - `torch.linalg.inv` should not raise an error for this kind of input.
Usually, small size matrices are used in the tests, but for larger matrices and `device='cuda'` `random_fullrank_matrix_distinct_singular_value` may generate a matrix that is not invertible.

## To Reproduce

I couldn't reproduce the failures locally, but here are the links for failing tests on CUDA 10.2:
https://github.com/pytorch/pytorch/runs/3880438252
https://github.com/pytorch/pytorch/runs/3880437217

## Expected behavior

`random_fullrank_matrix_distinct_singular_value` should produce invertible matrix for any size.

## Additional context

Originally the problem appeared when enabling proper use of `device` kwarg in `test_inverse_many_batches` from `test_linalg.py`, see https://github.com/pytorch/pytorch/pull/64930#discussion_r730926860.

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
By the looks of it, it creates a matrix with singular values `1/n, 2/n, ..., 1`. When `n` is large, `1/n` can be close to zero.

In fact, the determinant of that matrix tends to zero, which is undesirable. It'd be better to set its eigenvalues to be equidistant in the range, say, [0.5, 2]. I think that should make all these methods stable enough.
