### ISSUE TITLE
torchaudio has unit tests failing only on Linux CPU Python 3.9

### ISSUE THREAD

**Issue by carolineechen** [pytorch/pytorch#66892]
## 🐛 Bug

Several torchaudio unit tests for `torchaudio.functional.spectrogram`, `torchaudio.transforms.MelSpectrogram`, and `torchaudio.transforms.GriffinLim` have recently been failing on torchaudio's Circle CI for linux CPU Python 3.9, maybe relevant to PyTorch on Python3.9: https://app.circleci.com/pipelines/github/pytorch/audio/7940/workflows/8775fd08-c6ed-4900-b09f-6dc98bc02092/jobs/392998

The common operations in the failing functions are `torch.stft` and `torch.istft`. The same tests are passing on Linux with other versions of Python, and on MacOS and Windows.

## To Reproduce

I am unable to reproduce the failures locally with a different environment from CircleCI, but they have been consistently failing on the one specific CircleCI environment described below.

The following are links/parameters to the failing test cases to reproduce
- [test_spectogram_grad_at_zero](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/functional/functional_impl.py#L212), `power=0.`
- [test_griffinlim (autograd)](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/transforms/autograd_test_impl.py#L107), `momentum=0.99, rand_init=False`
- [test_MelSpectrogram](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/transforms/librosa_compatibility_test_impl.py#L71), `mel_scale="slaney"` cases

## Expected behavior

The unit tests should pass.

## Environment

From CircleCI test log
```
Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-1110-aws-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch-test
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py39h3811e60_0    conda-forge
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.0              py3.9_cpu_0    pytorch-test
[conda] pytorch-mutex             1.0                         cpu    pytorch-test
[conda] torchaudio                0.10.0                   pypi_0    pypi
```

cc @mruberry @peterbell10 @mthrok

**Comment by mruberry** [comment]
@carolineechen Sorry to hear these tests have started failing, do you have some more information about what's making them fail? I don't think we changed the stft or istft operators recently.

**Comment by carolineechen** [comment]
@mruberry sorry for the delayed response -- the tests are still failing but we are not sure what the reason is and why it is only failing on that configuration, and not all failures are reproducible even through circleci ssh. The tests had begun failing after this commit https://github.com/pytorch/audio/commit/bf580c752754d4664376c31060bacc0edb230029, but the changes are unrelated to these operations. We'll keep an eye out over the next few weeks to see if anything changes.

**Comment by seemethere** [comment]
Is this necessarily an issue with `pytorch/pytorch`?

Should we transfer this issue to `pytorch/audio` instead?

**Comment by mthrok** [comment]
I believe this is an issue with PyTorch or some numerical library the PyTorch depends on.

The functions used in the failing tests are implemented with pure-Python and PyTorch, so we cannot make sense why it is failing only on the combination of Linux / Conda / Python3.9 / CPU. The same tests are passing on GPU-enabled nightly binaries.

I am try reverting the commit that started to experience the issue on torchaudio, https://github.com/pytorch/audio/pull/1972.
It would be surprising if this revert fixes the issue, but either case, we cannot think of a way torchaudio's code is causing this issue.

**Comment by mthrok** [comment]
The PR with the revert exhibited the same issue. 

https://app.circleci.com/pipelines/github/pytorch/audio/8220/workflows/6db0fa69-81b6-495e-8dd4-fd236dc12c86/jobs/419393

So this means even though https://github.com/pytorch/audio/commit/bf580c752754d4664376c31060bacc0edb230029 was the first commit to see the issue, but the commit itself was not causing it.

**Comment by mthrok** [comment]
One peculiar thing I realized now is that we are observing this issue on both main branch and the release branch.
So it is happening on both nightly build and PyTorch 1.10 RCs. And IIRC it was not happening when @malfet firstly performed branch cut on torchaudio 0.10 release.

@seemethere Were there any recent change that got cherry-picked to 1.10 RC ? If not, my next hypothesis is something about the dependencies of PyTorch.

**Comment by mthrok** [comment]
Looks like this has been somehow resolved. We are no longer seeing the issue.
