### ISSUE TITLE
Stop using Homebrew in our macos jobs

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#66906]
This arose from our CI SEV Review. We should limit our network access risks, and if homebrew is not really necessary for our dependencies, we should not use it in CI. This could help us be consistent with how we deal with dependencies across platforms too.

Some solutions discussed were to
- use macports instead
- host dependencies that cannot use pip or conda to S3

cc @seemethere @malfet @pytorch/pytorch-dev-infra @albanD

**Comment by malfet** [comment]
How moving away from homebrew to macports, conda or S3 would result in limited network access?
Moving those dependencies to some sort of base image would help, but everything else is just shifting the failures from one hosting provider (GH) to  another

**Comment by janeyx99** [comment]
Oh my bad, let me clarify in the issue body that I was more under the guise that we shouldn’t use homebrew at all if we don’t have to, as it’s an additional thing to care about in terms of network accessing. (not that we’d be needing the network less)

I don’t actually know anything about macports but just mentioned it as it came up in our discussion as an alternative.

**Comment by janeyx99** [comment]
This doesn't seem valuable to do anymore as we have other initiatives to remove network access defined here https://github.com/pytorch/pytorch/issues/65439
