### ISSUE TITLE
[FSDP] Should we have an FSDPParameter? 

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#66908]
## 🚀 Feature

Right now FSDP parameter is basically a `torch.nn.Parameter` but with several attributes and additional data, including (maybe not comprehensive list):

- `_is_sharded` attr
- `_local_shard` attr
- `_full_param_padded` attr
- We also maintain `num_padded` / `numel_padded_per_param` in auxiliary data structure.

Instead, what about defining:

```
class FSDPParameter(torch.nn.Parameter):
    param: torch.nn.Parameter (actual param)
    is_sharded: bool
    _local_shard: torch.Tensor
    _full_param_padded: torch.nn.Parameter
    num_padded: int
```

to encapsulate all this data for easier access and organization?

## Motivation

It seems like this is a better and more robust way to store parameter attributes, but I am not sure if the current version serves some other purpose at the moment.

A couple of challenges to think of:
- Need to ensure `FSDPParameter` can satisfy the same contract as `nn.Parameter`, but this should be doable given that we are subclassing it. 
- Need to think about how this will work with checkpoint.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
I am guessing that `FSDPParameter` would be replacing `FlatParameter`?

I agree that our runtime definition of attributes on `FlatParameter` is not a good practice. One way around this is to define all of the attributes on the `FlatParamHandle` instead and move them to be defined in the `FlatParamHandle` constructor. This needs to be scoped out further and requires some non-trivial refactoring.
