### ISSUE TITLE
[FSDP] Wait for optimizer stream in forward pre hook

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#66911]
## 🚀 Feature

In FSDP we run all_gather on separate stream, thus we need to wait for the current stream corresponding to previous optimizer step to ensure parameters are up to date. 

We currently do this in `_lazy_init`, only in the outermost forward:

This seems a bit hacky as `_lazy_init` just seems to imply it will do some parameter attribute initialization that can't be done in ctor. We could use forward pre hooks for this: https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.register_forward_pre_hook instead which might be more robust and extensible.

In fact we can take this further and investigate whether all of `_lazy_init` can be moved to forward pre hooks.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
This has been refactored to a point where I am reasonably satisfied. I think we can close this one.
