### ISSUE TITLE
Build LibTorch nightly for macOS with Metal support

### ISSUE THREAD

**Issue by RahulBhalley** [pytorch/pytorch#66910]
## ❓ Questions and Help

There's seems to be no documentation about building nightly LibTorch from source specifically for macOS with Metal support enabled. Can someone please guide me about that?

Regards
Rahul Bhalley

**Comment by xta0** [comment]
@RahulBhalley the current Metal backend is meant to be by mobile devices, not desktop. If you want to target on mobile, please refer to this tutorial - https://pytorch.org/tutorials/prototype/ios_gpu_workflow.html

**Comment by RahulBhalley** [comment]
Okay, thanks!

**Comment by RahulBhalley** [comment]
One question, some operators are not Metal supported in LibTorch yet like FFT ops. So how can I convert a model such that other layers (like Conv, Linear, etc.) run on Metal but FFT op (used inside model, say N-dim FFT applied after some convolution layer) falls back to CPU automatically?

**Comment by RahulBhalley** [comment]
> One question, some operators are not Metal supported in LibTorch yet like FFT ops. So how can I convert a model such that other layers (like Conv, Linear, etc.) run on Metal but FFT op (used inside model, say N-dim FFT applied after some convolution layer) falls back to CPU automatically?

Answering to myself and for others who might be having same issue. I created Metal-based models and CPU-based models and then wrote the inference code for whole network using those sub-networks. Simple.
