### ISSUE TITLE
Why slower than torch2trt

### ISSUE THREAD

**Issue by 1309123499** [pytorch/pytorch#66935]
I used 2 ways to convert torch model to trt, torch->onnx->tensorrt and torch2trt. But the former is much slower.
for instance, resnet50 for a 1344*1344 image on average:
Inference time with the PyTorch engine:  0.0224735689163208
Inference time with the TensorRT(ONNX) engine: 0.0033051061630249025
Inference time with the TensorRT(Torch2TRT) engine: 0.0008296775817871094
What makes the difference?

cc @VitalyFedyunin @ngimel

**Comment by garymm** [comment]
@1309123499 could you please try benchmarking torch -> ONNX -> [ONNX Runtime with TensorRT Execution Provider](https://onnxruntime.ai/docs/build/eps.html#tensorrt)?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
