### ISSUE TITLE
DISABLED test_barrier_timeout_global (__main__.TestDistBackendWithSpawn

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#66982]
Example flaky failure on trunk https://github.com/pytorch/pytorch/runs/3958042374

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Closing to see if https://github.com/pytorch/pytorch/pull/68821 helps, or at least provides a better repro command.
