### ISSUE TITLE
torch.onnx.export

### ISSUE THREAD

**Issue by martin0496** [pytorch/pytorch#66987]
does torch.onnx.export() works for all models with .pth extension to convert it from pytorch to onnx ? or is there some requirements concerning the size or the coverage of the model in torchvision ?

**Comment by thiagocrepaldi** [comment]
> The Interhand model I am using is composed of resnet50 as backbone and rootnet as described here: https://github.com/facebookresearch/InterHand2.6M The issue is that I obtain a blank file after applying the onnx.export that's why I wanted to check if it works for all the models or only for specific models

@martin0496 could you provide a repro?

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
