### ISSUE TITLE
DISABLED test_init_pg_and_rpc_with_same_socket (__main__.TCPStoreTest)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#66983]
Example flaky failure on trunk: https://github.com/pytorch/pytorch/runs/3954935266

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by mrshenli** [comment]
closed by #67638
