### ISSUE TITLE
[iOS] [HelloWorld] In Xcode Release mode, any module outputs always same

### ISSUE THREAD

**Issue by darkThanBlack** [pytorch/pytorch#66993]
## Releated

I really don't know which part (PyTorch source or Xcode proj setting)  caused this problem, sorry for that but I also reported this [#72](https://github.com/pytorch/ios-demo-app/issues/72)

## 🐛 Bug

In PyTorch iOS HelloWorld proj, if you just change `Build Configuration` to `Release`，the module output always same value.

## To Reproduce

1. Download PyTorch HelloWorld proj from https://github.com/pytorch/ios-demo-app/tree/master/HelloWorld.
2. Insert different image and model to proj.
3. Create different pixelBuffer from inserted image, print result for `module.predict(image: UnsafeMutableRawPointer(&pixelBuffer))` func, we can find outputs value is different.
4. In Xcode IDE, select `Edit Scheme... -> Run -> Info -> Build Configuration` from `Debug` to `Release`.
5. just print return value for `module.predict(image: UnsafeMutableRawPointer(&pixelBuffer))` again, we can find all outputs value is same.
6. I also uploaded my test proj, just simply changed sth. from HelloWord, you can find it here: https://github.com/darkThanBlack/MOONPyTorchIssue, you may need change `Signing Certificate` or other configs to run it.

## Other Info

1. You can find my sample code in `ViewController.m, Line 24 to Line 67`...
2. I tried change `.pt` and `predict` implement（I have another private proj to do some face recognize and it works well in Debug mode, I can't upload it because relate some user info）, no matter what things I input, outputs seemd a static value.
3. I also tried change all proj  `Build Settings` config releated to Debug/Release but can't fix it.
4. I also tried build PyTorch Libraries from source but still can't fix it , I tried read PyTorch source code but not sure how Xcode proj's Debug/Release affect `.a` libraries...
5. Here is some hint image for help...

![hint02](https://user-images.githubusercontent.com/8111265/138210533-8155c856-b3bd-4093-a722-ffed1e258489.png)

![hint03](https://user-images.githubusercontent.com/8111265/138210542-06ecbc91-b799-4f9c-baa0-892e27a43fca.png)

## Environment

 - Setup PyTorch with `pod 'LibTorch-Lite', '~> 1.9.0'` or build from source.
 - OS : Apple M1, iPhone 12（iOS 14.8）；Other Mac/iOS OS is reproducible too.

**Comment by husthyc** [comment]
Hey @darkThanBlack @bailaohe , the cause is release build uses "-O" as the Swift Compiler Optimization Level but debug build uses "-Onone". The workaround is switch it to "-Onone" which is as shown below. Looking into the root cause.
![image](https://user-images.githubusercontent.com/6876992/140572699-94c3faaf-2b26-4051-8868-317772183400.png)
cc @xta0

**Comment by darkThanBlack** [comment]
Hello @husthyc , because Pytorch is compiled and generated by C++, so I noticed `Optimization Level` from the beginning, but I only tried to modify `Apple Clang - Code Generation`, didn't notice `Swift Compiler - Code Generation` has the same option, what a SAD story. 
I will try verify the impact of this modification on main project, make sure it can be release in Apple Store, if there is any progress worth synchronizing, I will continue to comment here. THANKS for your reply, which helped me a lot. I also expect your guys fixing root cause so I can upgrading Pytorch, GOOD LUCK!

**Comment by husthyc** [comment]
Hey @darkThanBlack and @bailaohe , the root cause is found. `UnsafeMutablePointer()` doesn't guarantee the converted pointer is still pointing to the allocated memory. Therefore you may need to copy the buffer with allocating memory and pass the new pointer to the PyTorch module.

You can replace 
```
      guard let outputs = module.predict(image: UnsafeMutableRawPointer(&pixelBuffer)) else {
          return
      }
```
with 
```
      let copiedBufferPtr = UnsafeMutablePointer<Float>.allocate(capacity: pixelBuffer.count)
      copiedBufferPtr.assign(from: pixelBuffer, count: pixelBuffer.count)
      guard let outputs = module.predict(image: copiedBufferPtr) else {
          return
      }
```
then the output will be expected. Fixes for the demo project are coming out. Thanks for reporting.

**Comment by bradhowes** [comment]
I could be missing something, but this seems to do the job without a copy:

```
    pixelBuffer.withUnsafeMutableBufferPointer { ptr in
      if let outputs = module.predict(image: &(ptr.baseAddress!.pointee)) {
        let zippedResults = zip(labels.indices, outputs)
        let sortedResults = zippedResults.sorted { $0.1.floatValue > $1.1.floatValue }.prefix(3)
        var text = ""
        for result in sortedResults {
          text += "\u{2022} \(labels[result.0]) \n\n"
        }
        resultView.text = text
      }
    }
```
