### ISSUE TITLE
Placeholder variable

### ISSUE THREAD

**Issue by lukeyeager** [pytorch/pytorch#670]
Is there any way to declare a "placeholder" variable in PyTorch? I think I need to either create a Variable without a Tensor or create a Tensor without a fully-defined shape (i.e. `[None, 3, 10, 30]`).

I'm investigating the concept of adding a PyTorch backend for Keras (not currently volunteering to do it) and ran into this issue immediately (see implementations for [theano](https://github.com/fchollet/keras/blob/1.2.1/keras/backend/theano_backend.py#L93-L113), [tensorflow](https://github.com/fchollet/keras/blob/1.2.1/keras/backend/tensorflow_backend.py#L275-L312)). I see that you've already brought up the idea of implementing a Keras backend, so I thought you might have given this some thought.

> Keras Integration
Have a keras backend. Send in a Pull Request to fchollet/keras
https://github.com/pytorch/pytorch/issues/5#issue-173498149

Thanks!

**Comment by apaszke** [comment]
No, we haven't thought too much about that yet. What would you do with such placeholder variable? You need to be able to execute operations on it right?

I think adding a Keras backend might be easier once we have lazy engine. Then you'll be able to define the whole graph before actually executing it.

**Comment by lukeyeager** [comment]
I'm struggling to find the right terminology, but it seems that Theano and Tensorflow provide an API for declaring things using symbolic variables. Then they "compile" the graph before doing anything with it.

I can't see how to do that with PyTorch currently. Maybe this is the "lazy engine" you're talking about?

**Comment by apaszke** [comment]
Yeah I know how Theano and TF do this, and it's completely different from our imperative backends. There's no way to defer the function execution right now, and as far as I know it's necessary for Keras, as it will be calling ops on Variables without the data. If you enable lazy evaluation, it won't actually compute a thing, util you touch the `.data` of some Variable, which is when the whole subgraph before it will get computed. Until then, the leaves can even contain empty tensors, as their won't actually be used.

**Comment by lukeyeager** [comment]
Nice explanation, thanks. Looking forward to lazy execution!

**Comment by jekbradbury** [comment]
I had assumed that a PyTorch backend for Keras would build only the module hierarchy (i.e., run `__init__`) and a lightweight graph structure that represents the Keras connectivity primitives during "graph construction" while running the actual `forward` methods only during "graph execution". But it sounds like this (which would require implementing a bunch of `Module` subclasses analogous to some of Torch's old Table modules, each of which describes a fixed graph in its `forward`) is unnecessary once lazy evaluation is available.
