### ISSUE TITLE
`x.T` used on an input that's not a matrix in the OpInfo of `torch.tile`

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#67012]
The OpInfo of `torch.tile` uses `x.T` to transpose a tensor.
https://github.com/pytorch/pytorch/blob/b6df043f1fa31f37c4b205eb4083918b919751ff/torch/testing/_internal/common_methods_invocations.py#L3464
This is being deprecated, so this test should be updated.

cc @mruberry

**Comment by mruberry** [comment]
> IIRC the reason for having that was to test for noncontiguous case, so second option seems more readable for doing that.

Good news is that with `test_noncontiguous_samples` added now OpInfos probably don't need to create their own noncontiguous inputs for testing, so we can just remove this.
