### ISSUE TITLE
[Distributed Tests] Run a single distributed test in a standalone process

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#67061]
## 🚀 Feature

There are a lot of [distributed flaky tests](https://github.com/pytorch/pytorch/issues?q=is%3Aopen+is%3Aissue+label%3A%22oncall%3A+distributed%22+label%3A%22module%3A+flaky-tests%22+) and we would like to make them easier for developers to reproduce and ultimately drive down the # of flaky tests. 

One major issue is reproducibility of these tests. For example, in our [current test setup](https://github.com/pytorch/pytorch/blob/master/test/run_test.py): we run the entire test file at once, but developers usually run a single flaky test to reproduce. Unifying the way the test is run in OSS and how a developer might run them would make the reproducibility a lot easier and contribute to a reduction in flaky tests. 

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @mruberry

**Comment by janeyx99** [comment]
Would the --subprocess flag help in common_utils.py?

**Comment by rohan-varma** [comment]
This is now done
