### ISSUE TITLE
`torch.Tensor.new_empty((3, 2))` gives weird error

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#6707]
I think this is something that I would try as a confused user and end up more confused at the error:

```
In [7]: torch.Tensor.new_empty((3, 2))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-62523255e019> in <module>()
----> 1 torch.Tensor.new_empty((3, 2))

TypeError: descriptor 'new_empty' requires a 'torch._C._TensorBase' object but received a 'tuple'

In [8]: torch.Tensor.new((3, 2))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-2232049e79b4> in <module>()
----> 1 torch.Tensor.new((3, 2))

TypeError: descriptor 'new' requires a 'torch._C._TensorBase' object but received a 'tuple'
```
cc @SsnL @gchanan

**Comment by zou3519** [comment]
To clarify: we shouldn't tell users that they're missing a 'torch._C._TensorBase', we should tell them the first argument is a tensor.

**Comment by gchanan** [comment]
I don't follow what "we should tell them the first argument is a tensor." means.

**Comment by zou3519** [comment]
Right now, it's
```
TypeError: descriptor 'new' requires a 'torch._C._TensorBase' object but received a 'tuple'
```
This is what I think it should be:
TypeError: descriptor 'new' requires a tensor but received a 'tuple'.

**Comment by gchanan** [comment]
I don't think that's what this is about; take the `new_empty` case: that definitely takes a tuple.  It's that you are trying to call the method on a class and not an object.

**Comment by zou3519** [comment]
True. Maybe we should throw an error when someone tries to call the method on a class and not an object?

**Comment by gchanan** [comment]
I don't think we can do anything here.
