### ISSUE TITLE
Conv3d needs a no-bias option

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#671]
Right now, VolumetricConvolution in THNN doesn't mark or handle bias=NULL cases

**Comment by soumith** [comment]
Places that need to be guarded with: `if (bias != NULL) {...}`

https://github.com/pytorch/pytorch/blob/master/torch/lib/THNN/generic/VolumetricConvolutionMM.c#L303-L310 (if bias == NULL, fill the output with zeros)

https://github.com/pytorch/pytorch/blob/master/torch/lib/THNN/generic/VolumetricConvolutionMM.c#L554-L563

https://github.com/pytorch/pytorch/blob/master/torch/lib/THCUNN/generic/VolumetricConvolution.cu#L173-L196

https://github.com/pytorch/pytorch/blob/master/torch/lib/THCUNN/generic/VolumetricConvolution.cu#L456-L491

When i doubt, look at SpatialConvolution*

cc: @elistevens

**Comment by elistevens** [comment]
Is there any significance to `VolumetricConvolution.cu` not having the `MM` suffix? I'm assuming that it corresponds to `SpatialConvolutionMM.cu`.

**Comment by soumith** [comment]
there's no significance. it's just unfortunate organic historical naming artifacts.

**Comment by elistevens** [comment]
Gotta love those.

Any tests I should be duplicating?

**Comment by soumith** [comment]
probs  need to replicate some of these with bias=False in constructor args:

https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L1562-L1581

I realized that we dont test for bias=False in any of the conv* modules, no wonder we didn't catch the `bias=False` break

**Comment by elistevens** [comment]
Is the comment:
```
for test_params in module_tests + new_module_tests:
    # TODO: CUDA is not implemented yet
```
Still accurate?  I see `.cuda()` etc. in `NewModuleTest._do_test`. I'll remove if needed.

Also, should I approach the `bias=False` cases via copy/paste, or would something like `if 'Conv' in test_params['module_name']: kwargs['bias'] = False; NewModuleTest(**test_params)` be acceptable?

**Comment by fmassa** [comment]
Note that there is a pending PR adding no_bias support in THNN, but a CUDA PR is missing https://github.com/torch/nn/pull/1107

**Comment by elistevens** [comment]
Is there a code migration path from `torch/nn` to `pytorch/pytorch` for the files that I'm presuming are shared between the two projects? I haven't dug in, but it looks like, for the files it touches, torch/nn#1107 is more complete than what I have.

Should I manually copy the files?

**Comment by apaszke** [comment]
It's best if you can submit a PR with the C code to torch/nn, but we're accepting PRs either way I think. We're using git subtrees to merge the history of the repos.

**Comment by elistevens** [comment]
PR here: https://github.com/pytorch/pytorch/pull/688
