### ISSUE TITLE
DISABLED test_nccl_timeout (__main__.NcclErrorHandlingTest)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#67101]
Platforms: rocm, linux

Example failures:
- https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1427//console
- https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1405//console
- https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/1378//console

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by rohan-varma** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/68544
