### ISSUE TITLE
conda install unexpected cpu version on Windows

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#67108]
## 🐛 Bug

conda install cpu version instead of expected cuda version on Windows

## To Reproduce

1. Run `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch` on Windows
2. The output is 
    The following NEW packages will be INSTALLED:
```
    pytorch            pytorch/win-64::pytorch-1.10.0-py3.8_cpu_0
    torchaudio         pytorch/win-64::torchaudio-0.10.0-py38_cpu
    torchvision        pytorch/win-64::torchvision-0.11.1-py38_cpu
```

## Expected behavior

The output should like 
```
    pytorch-1.10.0             |       py3.8_cuda11.3_cudnn8.2.0_0        1.21 GB  pytorch
    torchaudio-0.10.0        |       py38_cu113         4.5 MB  pytorch
    torchvision-0.11.1        |       py38_cu113        30.4 MB  pytorch
```

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mantaionut** [comment]
I did not managed to reproduce this issue. Do you still encounter this issue? If so can you check if you have `cpuonly` package installed and if you have it, uninstall it, does it work then?

**Comment by mantaionut** [comment]
I am closing this issue due to a lack of activity. Please feel free to open a new issue if you still encounter this issue.
