### ISSUE TITLE
Support torch.equal and torch.allclose for ShardedTensor

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#67112]
## 🚀 Feature
Support torch.equal and torch.allclose for ShardedTensor

## Motivation

Unit tests frequently use torch.equal and torch.allclose to compare if Tensors are equal. This applies to ShardedTensor as well since unit tests frequently need to compare equality of two ShardedTensors.

## Pitch

Use __torch_function__ dispatch to enable these ops for ShardedTensor.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by pritamdamania87** [comment]
Have an implementation for `torch.equal` in https://github.com/pytorch/pytorch/pull/69734, `allclose` is not implemented yet though.

**Comment by kumpera** [comment]
PR for `allclose` in #70331
