### ISSUE TITLE
Support for torch.diagonal/torch.trace in ONNX models

### ISSUE THREAD

**Issue by DiffeoInvariant** [pytorch/pytorch#67113]
## 🚀 Feature
It would be great if we could figure out a way to export the `torch.diagonal` operator to ONNX. 

## Motivation

My code runs into the following exception: 
```
RuntimeError: Exporting the operator diagonal to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
when I try to `torch.onnx.export()` a `torch.ScriptModule` that involves taking the trace of matrices, which is passed through `functorch.vmap()`. So the input might have shape `(100, 3, 3)` and it would be taking the trace of 100 different 3x3 matrices. This gets scripted into
```
_0 = torch.sum(torch.diagonal(argument_0, 0, 1, 2), [1])
_1 = torch.diagonal(torch.matmul(argument_0, argument_0), 0, 1, 2)
_2 = torch.sum(_1, [1])
...
```

I tried replacing the `torch.trace(x)` with `torch.einsum('ii',x)` in the hope that it would use the ONNX einsum op, but it scripted to the same code as with `torch.trace`

## Pitch

I would love it if we could figure out how to export this model to ONNX. Any help is appreciated (i.e. if you know how to get `torch` to compile that trace to something that can work in ONNX as-is, I'm open to that as a solution)

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
