### ISSUE TITLE
[CAFFE2] Are all the submodules strictly required to compile Caffe2?

### ISSUE THREAD

**Issue by yxchng** [pytorch/pytorch#6712]
It seems to be that they are because Caffe2 will complain that they are not present. 

For example,

```
CMake Error at cmake/External/nnpack.cmake:68 (add_subdirectory):
  The source directory

    /home/yxchng/pytorch/third_party/NNPACK

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:104 (include)


CMake Error at cmake/External/nnpack.cmake:73 (set_property):
  set_property could not find TARGET nnpack.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:104 (include)


CMake Error at cmake/External/nnpack.cmake:74 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:104 (include)


CMake Error at cmake/External/nnpack.cmake:75 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:74 (include)
  CMakeLists.txt:104 (include)

```

However, I think that most of the packages should be optional (wonder why it is included as submodule instead of being optional), for example some are related to mobile some distributed training. How can I make Caffe2 not complain when they are not present?

**Comment by yxchng** [comment]
I am mainly looking to install a very light version of caffe 2 that has only the core functionalities on server (no mobile stuff) and only for gpu.

**Comment by ezyang** [comment]
CC @orionr @pjh5

**Comment by pjh5** [comment]
The submodules are required for the current cmake setup to work right now, but they are not all used at compile time unless you pass e.g. -DUSE_MPI=ON . The default modules that will be used (if they are found) can all be seen starting here https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L27 . To build without one of these modules, pass the corresponding flag to your cmake command e.g. -DUSE_GLOO=OFF .

**Comment by yxchng** [comment]
@pjh5 Yup but since I am not familiar with all the libraries. I am not sure what are the minimal dependencies required.
