### ISSUE TITLE
cpp_extensions header installation can easily stale

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6721]
I helped @calvinleenyc debug a problem where their ATen/Torch headers were out of sync, leading to very strange compilation errors because Torch headers were attempting to use ATen headers, but the ATen headers were stale.

It seems the method to reproduce this problem is something like install two copies of PyTorch (at different versions) at the same time (I am not sure which order Calvin installed them in; you might have to install one with "install" and the other with "develop") and then attempt to build a `cpp_extension`. It seems that the Python files get installed to different directories for each install, but the headers are installed to a global location.

CC @goldsborough

**Comment by apaszke** [comment]
install and then develop is pretty bad in general. IIRC you can run develop as many times as you want and it will keep using the stale installed version.

**Comment by ezyang** [comment]
Closing as WONTFIX
