### ISSUE TITLE
Different behavior of torch.gels() on CPU tensors vs GPU tensors

### ISSUE THREAD

**Issue by jacobrgardner** [pytorch/pytorch#6723]
I am currently using PyTorch 0.3.0 and I am noticing some (possibly strange) differences between the behavior of `torch.gels` when operating on CPU tensors versus GPU ones, in particular relating to whether the number of rows of A is allowed to be larger than the number of columns or not.

Here is some minimal code that reproduces my problem:

```python
import torch
A = torch.randn(5, 100)
B = torch.randn(5, 5)
ls1 = torch.gels(B, A) # Works!
ls2 = torch.gels(B.cuda(), A.cuda()) # Fails
```
The first solve on the CPU works fine; however, the second solve gives me the error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-757975f749ea> in <module>()
----> 1 ls2 = torch.gels(B.cuda(), A.cuda())

RuntimeError: invalid argument 2: A should have m >= n at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCTensorMathMagma.cu:107
```

Is this a limitation of the CUDA implementation of `gels` that PyTorch uses, or otherwise intended? If so, any guidance about a possible work-around would be greatly appreciated. Our only thought on a work-around was to manually QR decompose A with `torch.qr` and then use `torch.trtrs`, but `torch.trtrs` doesn't support CUDA tensors.

**Comment by SsnL** [comment]
MAGMA gels  doesn't implement the m < n case.
