### ISSUE TITLE
channels_last significantly degrades accuracy

### ISSUE THREAD

**Issue by andrewilyas** [pytorch/pytorch#67239]
## 🐛 Bug

Moving a simple ResNet model and CIFAR images to channels_last format significantly degrades accuracy (by 6+%).

## To Reproduce

1. Download this script: https://gist.github.com/andrewilyas/ac844f3368c97e6d55e40209d2070557
2. Run ``python train.py 1`` and ``python train.py 2`` 
3. The only difference between the two runs is 3 lines that move the images and model to channels_last, but the difference in accuracy is significant (84% for channels_last and 91% for contiguous)

## Expected behavior

The two runs should produce identical results since the only difference between them is the memory format of the model and images.

## Environment

Output of collect_environment.py:

```
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-159-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-PCIE-40GB
GPU 1: A100-PCIE-40GB
GPU 2: A100-PCIE-40GB
GPU 3: A100-PCIE-40GB
GPU 4: A100-PCIE-40GB
GPU 5: A100-PCIE-40GB
GPU 6: A100-PCIE-40GB
GPU 7: A100-PCIE-40GB
GPU 8: A100-PCIE-40GB

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] torch==1.10.0+cu113
[pip3] torchaudio==0.10.0+cu113
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.11.1+cu113
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] cudatoolkit               11.2.2               he111cf0_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     1.10.0+cu113             pypi_0    pypi
[conda] torchaudio                0.10.0+cu113             pypi_0    pypi
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchvision               0.11.1                   pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel @VitalyFedyunin @jamesr66a

**Comment by xwang233** [comment]
I tested with nightly wheels from cuda 11.1 on A100. The 06-26 wheel is good but 06-27 wheel is bad. Here are relevant commits https://github.com/pytorch/pytorch/commits/5b118a7f233a4682e338c9ef14a5ec55183b9a65

**Comment by ngimel** [comment]
Hm, nothing looks immediately suspicious

**Comment by ngimel** [comment]
Aha, this https://github.com/pytorch/pytorch/pull/48920/files#diff-1bbd7759fe5f74c51bd2896fae4a2211ddff0431e0ea7e6ee78a16951b8a3dc3R64 would change the gradInput layout for AdaptiveMaxPool, for both cpu and gpu. Note that this is the correct change (gradInput becomes channels-last, as it should be, whereas previously it was contiguous), but it could trigger further changes.

**Comment by xwang233** [comment]
Thanks @ngimel . I've checked that https://github.com/pytorch/pytorch/commit/dd045ab540ad47e0205cc1c53be400947f4e7477 is the first commit that observes this channels-last training accuracy drop. I'll further check which layer may cause this issue.

**Comment by ngimel** [comment]
Now it would make sense to check if AdaptiveMaxPool itself is producing correct results on the gpu, and if it does, how do subsequent conv/bn call change.

**Comment by xwang233** [comment]
Let the backward of adaptive_max_pool2d to use contiguous path restores accuracy.

From the provided code snippet, there is only a linear layer (which matters) after adaptive_max_pool2d https://gist.github.com/andrewilyas/ac844f3368c97e6d55e40209d2070557#file-train-py-L70-L73

```diff
diff --git a/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp b/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp
index bc9bc60b9d..df66b30fbb 100644
--- a/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp
+++ b/aten/src/ATen/native/AdaptiveMaxPooling2d.cpp
@@ -47,7 +47,8 @@ TORCH_META_FUNC(adaptive_max_pool2d) (const Tensor& input, IntArrayRef output_si
 }
 
 TORCH_META_FUNC(adaptive_max_pool2d_backward)
-(const Tensor& grad_output, const Tensor& input, const Tensor& indices) {
+(const Tensor& grad_output, const Tensor& input_, const Tensor& indices) {
+  const Tensor input = input_.contiguous();
   int64_t ndim = grad_output.ndimension();
   TORCH_CHECK(ndim == 3 || ndim == 4,
     "adaptive_max_pooling2d_backward(): Expected 3D or 4D grad_output, but got: ", grad_output.sizes());
```

**Comment by xwang233** [comment]
For `AdaptiveMaxPool2d` layer with output size of `(1, 1)`, is it possible to add a shortcut to use 
```
input.max({-1, -2}, keepdim=True)
```
to improve the performance?

**Comment by ngimel** [comment]
Yes, we can use `max` to improve performance. 
If max pool backward itself produces correct result with channels last, the accuracy shouldn't change, there's a bug lurking somewhere, and we shouldn't hide it by making max pool contiguous.

**Comment by xwang233** [comment]
Both `adaptive_max_pool2d` forward and backward implementations are likely wrong on CUDA.

Explain:
https://github.com/pytorch/pytorch/blob/8eb85b50277234e792d32f8f141f02d3b7c3042c/aten/src/ATen/native/cuda/AdaptiveMaxPooling2d.cu#L267-L271

The `adaptive_max_pool2d` CUDA kernel uses raw pointer instead of TensorAccessor. The kernel was probably written for output tensors of contiguous instead of channels_last, so passing a channels_last formatted pointer could yield wrong output.

https://github.com/pytorch/pytorch/blob/8eb85b50277234e792d32f8f141f02d3b7c3042c/aten/src/ATen/native/cuda/AdaptiveMaxPooling2d.cu#L56-L59

In the forward output kernel, the `input` pointer takes the advantages of the strides, but the `output` pointer assumes tensor is formatted as NCHW-contiguous.

Similar issues exist for backward impl and backward kernel.

Example:
```python
import torch
from torch.testing._core import _compare_tensors_internal

x = torch.randn(2, 3, 6, 6, device='cuda', dtype=torch.float)\
        .to(memory_format=torch.channels_last)

x_cpu = x.cpu()

out = torch.nn.functional.adaptive_max_pool2d(x, (2, 2))
out_cpu = torch.nn.functional.adaptive_max_pool2d(x_cpu, (2, 2))

_a, _b = _compare_tensors_internal(out.cpu(), out_cpu, rtol=1e-5, atol=1e-5, equal_nan=False)
if _a:
    print('good')
else:
    raise RuntimeError(_b)
```

output:
```
Traceback (most recent call last):
  File "/xxx/67239.py", line 16, in <module>
    raise RuntimeError(_b)
RuntimeError: With rtol=1e-05 and atol=1e-05, found 20 element(s) (out of 24) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.4265955686569214 (3.1810925006866455 vs. 0.7544969320297241), which occurred at index (0, 0, 1, 0).
```
