### ISSUE TITLE
[FSDP][BE] Rename some methods/streams

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#67288]
## 🚀 Feature
Some fsdp methods/attributes can be renamed to more clearly reflect what they do:

- post_backward_hook is not really called post backward, it is called after a grad is ready, the backwards can still be going on. Possibly rename it to _grad_ready_hook. Thus wait_for_post_backward can be renamed appropriately as well.
- wait_for_previous_optim_step actually does a pretty generic sync with the current stream so it is more general, can be renamed aptly as well. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
For the post-backward hook, I think it is okay to keep it as is. It is the post-backward with respect to a particular parameter. Pre-backward is before its gradient is computed, and post-backward is after its gradient is computed.

For `_wait_for_previous_optim_step()`, it is not an ideal name, but it captures the main intent. Perhaps we can call it `_wait_for_computation_stream()` as part of my recent efforts to rename streams.

**Comment by awgu** [comment]
- We converged to "post-backward hook". It is post (i.e. after) the `FlatParameter`'s backward gradient computation.
- This is renamed to `_wait_for_computation_stream()`.
