### ISSUE TITLE
libTH doesn't recognize Intel MKL in its default location

### ISSUE THREAD

**Issue by Maratyszcza** [pytorch/pytorch#673]
When building PyTorch from sources, libTH doesn't find Intel MKL in its default location (`/opt/intel/mkl/include` for includes and `/opt/intel/mkl/lib/intel64` for `.so`/`.a`). This can be worked around by adding these paths to `CMAKE_PREFIX_PATH`, but would be good if libTH searched default path by default: using system BLAS library on Linux is usually tremendously slower than Intel MKL, and its easy to not notice that libTH didn't find MKL.

**Comment by shawnjhenry** [comment]
I think I'm having this issue as well.  I previously installed without MKL, but I decided to update to the latest binary and installed MKL in the process.  Now I'm getting the following error:
```
  File "/usr/local/lib/python3.5/site-packages/torch/__init__.py", line 45, in <module>
    from torch._C import *
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/torch/_C.cpython-35m-darwin.so, 10): Library not loaded: @rpath/libmkl_intel_lp64.dylib
  Referenced from: /usr/local/lib/python3.5/site-packages/torch/lib/libTH.1.dylib
  Reason: image not found
```
What do I need to do to fix it?

**Comment by Maratyszcza** [comment]
Try `. /opt/intel/mkl/bin/mklvars.sh intel64` or something similar.

**Comment by shawnjhenry** [comment]
Hmm, maybe I'm having a different problem.  I installed MKL with anaconda as directed in the install instructions and it appears to have put it somewhere else.

**Comment by apaszke** [comment]
@shawnjhenry It's an unrelated problem. The issue is about the build not finding any MKL, while in your case it was found, but only at build time. I think you need to add the anaconda's `lib` directory to `LD_LIBRARY_PATH`.

**Comment by lynic** [comment]
I encounter the same error, and I solve it by running command 'conda install mkl' in my activated conda env.

>   File "/usr/local/lib/python3.5/site-packages/torch/__init__.py", line 45, in <module>
>     from torch._C import *
> ImportError: dlopen(/usr/local/lib/python3.5/site-packages/torch/_C.cpython-35m-darwin.so, 10): Library not loaded: @rpath/libmkl_intel_lp64.dylib
>   Referenced from: /usr/local/lib/python3.5/site-packages/torch/lib/libTH.1.dylib
>   Reason: image not found

**Comment by Luckick** [comment]
I got same error when import torch.

>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/anaconda/lib/python3.6/site-packages/torch/__init__.py", line 56, in <module>
    from torch._C import *
ImportError: dlopen(/Users/username/anaconda/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/username/anaconda/lib/python3.6/site-packages/torch/lib/libTH.1.dylib
  Reason: image not found

I searched with the file name "libiomp5.dylib", and find the path of this file: "/Users/username/anaconda/pkgs/intel-openmp-2018.0.0-hdd0ccc9_7/lib"

and then type below in terminal:
export DYLD_LIBRARY_PATH="/Users/username/anaconda/pkgs/intel-openmp-2018.0.0-hdd0ccc9_7/lib"

solved!

**Comment by soumith** [comment]
this is fixed now, after refactor of build system
