### ISSUE TITLE
Migrate `android-ndk` build from CircleCI to GHA

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#67301]
Migrate https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=android towards GitHub Actions workflows.

Should be somewhat similar to https://github.com/pytorch/pytorch/pull/66673

Gradle build  CircleCI templates are https://github.com/pytorch/pytorch/blob/00b0d4eeedc7f1928a52f5dc6a70fe3b08646981/.circleci/verbatim-sources/job-specs/job-specs-custom.yml#L252

This specific logic should probably be migrated into https://github.com/pytorch/pytorch/blob/master/.github/templates/linux_ci_workflow.yml.j2 template or create a new template

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
This should be resolved by https://github.com/pytorch/pytorch/pull/68843, no?
