### ISSUE TITLE
Error when running torch.onnx._optimize_trace after torch.onnx.export

### ISSUE THREAD

**Issue by Andrechang** [pytorch/pytorch#67302]
## 🐛 Bug

Running `torch.onnx._optimize_trace` after torch.onnx.export will cause:

TypeError: _jit_pass_onnx_graph_shape_type_inference(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: int) -> None
 

## To Reproduce

Using pytorch version '1.10.0+cu102'
onnx version '1.10.1'

1. Run the attached test code: `python3 test.py`

[test.zip](https://github.com/pytorch/pytorch/files/7422243/test.zip)

## Expected behavior

It will error out on the second call of `torch.onnx._optimize_trace`

TypeError: _jit_pass_onnx_graph_shape_type_inference(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: int) -> None

## Environment

Using pytorch version '1.10.0+cu102'
onnx version '1.10.1'

PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.17.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 460.91.03

**Comment by BowenBao** [comment]
`_optimize_trace` is internal api, and should not be called after `torch.onnx.export`.

**Comment by thiagocrepaldi** [comment]
Closed as the reported scenario is not supported
