### ISSUE TITLE
[Docs] Improve instructions for for how user should ssh into machine

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#67366]
## 🚀 Feature

Title: With-SSH Should have bashrc set conda environment

I am following https://github.com/pytorch/pytorch/wiki/Debugging-using-with-ssh-for-Github-Actions, and have successfully logged into the server, however I am having trouble figuring out how to activate the right build. It would be great if the right conda environment etc would be present in the bashrc, and it were easier to work on the server.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Add better instructions for what the user should do

The tricky part is knowing that chown is necessary, but maybe that's not even necessary anymore...

**Comment by ZainRizvi** [comment]
@malfet : Want to more more environment vars into the docker image itself. The challenge right now is that you can ssh into a machine but you'll be missing those env vars

**Comment by clee2000** [comment]
action: print info on how to how to connect to docker container

**Comment by malfet** [comment]
This has been done a while back, closing
