### ISSUE TITLE
add `set_deterministic_debug_mode`

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#67386]
Currently we have `use_deterministic_algorithms` with `warn_only` kwarg to either error out or warn on encountering a non-deterministic algo. 
The proposal is to add `set_determinism_debug_mode(str)` for consistency with existing [set_sync_debug_mode](https://pytorch.org/docs/master/generated/torch.cuda.set_sync_debug_mode.html?highlight=set_sync_debug_mode#torch.cuda.set_sync_debug_mode) function. 

cc @mruberry @kurtamohler

**Comment by kurtamohler** [comment]
Should we deprecate `use_deterministic_algorithms` as well?

**Comment by ngimel** [comment]
We could throw a warning if someone uses it, but I don't think we should remove it.
