### ISSUE TITLE
Missing doc for torch.onnx functions

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#67393]
The following functions and classes are not documented correctly: they are part of the public API but do not show up on the [docs website](https://pytorch.org/docs/master/)
This means that we want to do either:
- Add a docstring and make sure it is properly added to a .rst file so that it appears on the docs website
- Make it private by prepending a `_` to the function name
- Remove it from the public API by deleting it from your `__init__.py` file (like [here](https://github.com/pytorch/pytorch/blob/708f7b120957f47f22752f49d52c08d5a0ca7fc0/torch/__init__.py#L696))

torch.onnx
----------
Functions:
 * unregister_custom_op_symbolic

Classes:
 * CheckerError
 * ExportTypes

cc @brianjo @mruberry

**Comment by thiagocrepaldi** [comment]
@albanD https://github.com/pytorch/pytorch/pull/67640 will address this issue
