### ISSUE TITLE
Missing doc for torch.hub functions

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#67391]
The following functions and classes are not documented correctly: they are part of the public API but do not show up on the [docs website](https://pytorch.org/docs/master/)
This means that we want to do either:
- Add a docstring and make sure it is properly added to a .rst file so that it appears on the docs website
- Make it private by prepending a `_` to the function name
- Remove it from the public API by deleting it from your `__init__.py` file (like [here](https://github.com/pytorch/pytorch/blob/708f7b120957f47f22752f49d52c08d5a0ca7fc0/torch/__init__.py#L696)

torch.hub
---------
Functions:
 * import_module

cc @brianjo @mruberry @nairbv @NicolasHug

**Comment by NicolasHug** [comment]
Thanks for the feedback, let's deprecate it in 1.11 and remove in 1.12 then. To be extra-nice to the fairinternal repos, we'll try to submit a PR over there to just inline the function - it's just a few lines long.

> If people actually use it, should it be public? Or are they expected to use something else?

That's a good point, but IMHO that function is too low-level to be a nice user-facing function. It's also fairly hacky with surprising side-effects (and even potentially buggy https://github.com/pytorch/hub/issues/243), so I think it's best to make it private.

@jdsgomes has volunteered to work on this, please feel free to ping me for any help Joao

**Comment by jdsgomes** [comment]
Closing issue as the changes have been merged to master: https://github.com/pytorch/pytorch/blob/master/torch/hub.py
