### ISSUE TITLE
[default_collate] Batch with inconsistent sequence length: replace raising RuntimeError with flatten+offset handler

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#67419]
## 🚀 Feature
Batch with inconsistent sequence length: replace raising RuntimeError with flatten+offset handler

## Motivation

Painless use case for `nn.EmbeddingBag`

## Pitch

Replace [raising RuntimeError](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/collate.py#L82) with the following:

```python
...
elif isinstance(elem, collections.abc.Sequence):
        ...
        if not all(len(elem) == elem_size for elem in it):
#            raise RuntimeError('each element in list of batch should be of equal size')
            _1d_flatten = list(itertools.chain(*batch))
            _offsets = [0, *[len(b) for b in batch][:-1]]
            _offsets = list(itertools.accumulate(_offsets))
            return {
                '1D_flatten': collate_fn(_1d_flatten),
                'offsets': collate_fn(_offsets)
            }
        ...
...
```

A toy use case

```python
embag = nn.EmbeddingBag(5, 20)
for X, y in dataloader:
    if torch.is_tensor(X):
        emb = embag(X)
    elif isinstance(X, dict) and '1D_flatten' in X and 'offsets' in X:
        emb = embag(input=X['1D_flatten'], offsets=X['offsets'])
```

## Alternative

The above pitch will affect the behavior of the default collate function, an alternative could be a workaround by alternating recursive calls:

```python
# use original
_default_collate = default_collate
# user-defined customizable
def my_collate(batch):
    try:
        return default_collate(batch)
    except RuntimeError:
        # do my way

def default_collate(batch):
    ...
    # ...default_collate(...)  # recursive call
    # change to the following:
    ..._default_collate(...)
    ...
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by zuoxingdong** [comment]
@ejguan Thanks a lot for the reference! I agree that it already works well for many NLP tasks with variable length text inputs.
The specific use case I was thinking of for this issue is for a setting for recommender systems where the categorical features might refer to multi-selection information, in this case, there can be a nested dictionary from `__getitem__`. 

With similar contexts, we may want to handle various data types with such a nested structure. The support of either a custom handler on variable-length sequences (in **Pitch**) or an alternating recursive call (in **Alternative**) could be quite convenient without _copy-paste-modify_ the original `default_collate` every time, I think.

**Comment by ejguan** [comment]
The main concern for me is the flexibility. IMHO, the pitch seems not for general cases.
- First, we should not provide a fixed way to handle non-equal size batch as suggested in your pitch. Users may want different behaviors
- You want to raise `RuntimeError` to call a fall-back method. This is super dangerous as you are suppressing all the possible Error within `collate_fn`.

As you mentioned, you have a specific use case. Why not to use a specific `collate_fn` to handle. It's better than modifying the `default_collate_fn` to handle it.

**Comment by SsnL** [comment]
The custom `collate_fn` arg is designed exactly to handle cases like yours. You don't have to copy-paste `default_collate`. Just do 
```py
if MATCH_YOUR_CRITERIA: 
   do CUSTOM
else:
  return default_collate(x)
```

**Comment by zuoxingdong** [comment]
@SsnL @ejguan Thanks a lot for your feedbacks!

I have one follow-up question about customizing `collate_fn`:

what if the input is a nested dictionary with variables length of lists, e.g.

```python
x = {
   'A': {
      'numbers': [[1, 2, 3], [4, 5]]
  }
}
```

The abovementioned customization seems to work only with *first-level* criteria, all the successive recursive calls will fall back to the original `default_collate` again. 

For such a multi-level nested case, is there a feasible way to deal with it?
