### ISSUE TITLE
[Caffe2] Translator from Caffe's "Slice" and "Eltwise PROD" layer

### ISSUE THREAD

**Issue by EJShim** [pytorch/pytorch#6741]
Hello. I am trying to convert my .prototxt and .caffemodel data into caffe2(or pytorch)-compatible data.

But there is no "slice" and "eltwise"(with PROD parameter) layer translation support currently..

I can see there has been similar issue since 6 months ago.

Is there a plan to complete translation support  from original caffe model to the caffe2 model?

or is there any alternative solution for now?

**Comment by vijay2249** [comment]
@EJShim can you share how you solved this issue?
