### ISSUE TITLE
gpu memory cannot be used all

### ISSUE THREAD

**Issue by VictorLeeLk** [pytorch/pytorch#6743]
hello,My hardware is ubuntu16.04LTS+gtx1080ti+cuda8.0+pytorch

when I run a pytorch program,which is a CNN.My gpu memorry has 11G,but I can not use all memorry.By using command line `nvidia-smi`,I see it is always used about 3.6G memorry.
what is the proble?how can I solve it?,thank you!

**Comment by albanD** [comment]
Please use the [forum](https://discuss.pytorch.org/) to ask questions, we keep github issues for bug tracking only.
