### ISSUE TITLE
RuntimeError : PyTorch was compiled without NumPy support

### ISSUE THREAD

**Issue by EthanCalvin** [pytorch/pytorch#6747]
My pytorch version is 0.4.0a0_bc6243c. and I got stuck in running pytorch program on Jeson tx2. I got
RuntimeError : Pytorch was compiled without Numpy support. How can I solve this problem?
My spec for python and numpy is below

python : 3.6.3
numpy : 1.14.2
cuda : 8.0

![kakaotalk_20180419_151729531](https://user-images.githubusercontent.com/37919577/38974403-f13534a6-43e4-11e8-89ff-82a2c89173d1.jpg)

**Comment by apaszke** [comment]
Now that you have NumPy installed, try rebuilding PyTorch. It should automatically detect and use it.

**Comment by luulinh90s** [comment]
You have to install another version of numpy.
```
pip install numpy==1.15.0
Collecting numpy==1.15.0
  Downloading https://files.pythonhosted.org/packages/27/92/c01d3a6c58ceab0e6ec36ad3af41bc076014cc916afcb979ab4c9558f347/numpy-1.15.0-cp37-cp37m-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.9MB 2.9MB/s 
Installing collected packages: numpy
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
Successfully installed numpy-1.15.0
```
Above downgrading 1.15.4 -> 1.15.0.

Then install another torch version.
```
pip install torch==0.4.1.post2
Collecting torch==0.4.1.post2
  Downloading https://files.pythonhosted.org/packages/d3/91/1b2871d6c8ca079254deae5872af32e02e9a85f07dd0834e8b3489ce138f/torch-0.4.1.post2-cp37-cp37m-manylinux1_x86_64.whl (519.5MB)
    100% |████████████████████████████████| 519.5MB 170kB/s 
Installing collected packages: torch
  Found existing installation: torch 0.4.1
    Uninstalling torch-0.4.1:
      Successfully uninstalled torch-0.4.1
Successfully installed torch-0.4.1.post2
```
Here upgrade to torch-0.4.1.post2 from torch-0.4.1

**Comment by Statham-stone** [comment]
only install another torch works for me.

**Comment by huangpan2507** [comment]
only installed torch-0.4.1.post2 works for me and don‘t downgrading the numpy
version  from 1.15.4 -> 1.15.0.  I  reinstall the numpy version 1.16。
