### ISSUE TITLE
[checkpointing] Checkpointed model use more GPU memory than original model

### ISSUE THREAD

**Issue by ssidorenko** [pytorch/pytorch#6750]
While working with a model of mine, I've hit ` cuda runtime error (2) : out of memory` when using checkpointing with a model. Using the same model without checkpointing did not trigger the error.

I might have misunderstood something, but I expected that using checkpointing would use less GPU memory, not more?

See in the attached notebook: running cell 1 then 2 do not trigger the error. Restarting the kernel, then running cell 1 then 3 trigger the error (happened with a 1080 GTX Ti, the input size might have to be adjusted to trigger the error depending on the GPU)

[checkpoint memory usage debug.ipynb.zip](https://github.com/pytorch/pytorch/files/1927061/checkpoint.memory.usage.debug.ipynb.zip)

OS: Ubuntu 18.04 x86_64
PyTorch version: 2a628ba3 from source
CUDA: 9.1.85-3 from Ubuntu repository
Python: 3.6.4 :: Anaconda, Inc.
GPU: 1080 GTX Ti
GCC: version 5.5.0 20171010 (Ubuntu 5.5.0-11ubuntu1) 
CMake: version 3.9.4
Build command: python setup.py build && python setup.py install

**Comment by apaszke** [comment]
Can you please try to create a smaller script that would let us reproduce the issue and paste it into a github gist?

Also cc @prigoyal

**Comment by ssidorenko** [comment]
Running the following script should trigger a cuda OOM error when using a GTX 1080 Ti, and should not trigger it when commenting the line with checkpointing and uncommenting the next one.

https://gist.github.com/ssidorenko/c9d250c666498a43d4ba165808ee89a6

**Comment by prigoyal** [comment]
thanks for the report @ssidorenko , I'll repro first based on your gist and will get back to you.

**Comment by prigoyal** [comment]
I took a deeper look and TL;DR is that this model is not the right fit for using checkpointing on. The first segment of the model is checkpointed and has two linear layers which take almost all model memory. Of these two linear layers: one is input layer, one is the output layer. In checkpointing, input data is saved for use in backwards. The outputs activation is in memory as it serves as output to the second model segment. So almost all the data needs to stay in memory here. Hence checkpointing is useless.

Here is the breakdown of memory usage and comparison between checkpoint and non-checkpoint run.

non-checkpoint:
the input buffer + params allocates 2969 MiB memory, the forward pass takes 7004 MiB (all activations are still in memory). Total memory usage in forward pass is 7004 MiB. In the backwards pass, the peak memory usage is 9007 MiB so about 2000MiB extra is needed for the backwards.

checkpointed:
the input buffer + params allocates 2969 MiB memory, the model is divided in two segments and first segment is checkpointed i.e. no intermediate activations are saved except the input. The input 2969MiB is saved and at the end of forward pass on the checkpointed segment, allocated memory* is 5668 MiB. The output of the checkpoint is taken and the forward pass is run on second segment. This allocates no extra memory. Total memory usage at the end of forward pass is 5668 MiB. Now in the backwards pass, memory usage after backward on second segment is 5680 MiB. Now for the backward on 1st segment, we run the forward again, this allocates more memory to 8350 MiB. The activations are retained in memory this time. For backward on this segment, we need extra  ~2000 MiB but this reaches the peak of memory available and OOMs

**Comment by ssidorenko** [comment]
Sorry, I've re-read your explanation many times but I do not understand fully, where does the extra memory comes from ?

**Comment by taehyunzzz** [comment]
Maybe there was a confusing between activation checkpointing and model saving (checkpointing)
