### ISSUE TITLE
linalg.householder_product is incorrect when given non-contiguous inputs

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#67513]
Per title

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @walterddr @IvanYashchuk @xwang233

**Comment by v0dro** [comment]
I can take this up next.

**Comment by mruberry** [comment]
> I can take this up next.

There is a small chance this is actually an artifact of the test, but I think I ruled that out.

**Comment by v0dro** [comment]
Can you provide a test for this? I used the following on master and it seems to pass:
```
        A = torch.randn((5,5), dtype=dtype, device=device)
        reflectors, tau = generate_reflectors_and_tau(A)
        A_nc = A[:,:4]
        expected, _ = torch.linalg.qr(A_nc)
        actual = torch.linalg.householder_product(reflectors[:, :4], tau[:4])

        self.assertEqual(expected, actual)
```
