### ISSUE TITLE
I could't build from source.

### ISSUE THREAD

**Issue by colinxu2020** [pytorch/pytorch#67527]
## 🐛 Bug

I'm trying to install another library that tells me I need to install Pytorch, and since I'm using Python 3.10, I can't use the binary package, so I'm trying to build Pytorch manually, but an error occurs during the build

## To Reproduce

1. Download the latest source code (as stated in [docs](https://github.com/pytorch/pytorch#from-source))
2. Install the dependencies (I use pip, fortunately these packages can be found in pypi)
3. Build (I use the command `python setup.py bdist_wheel`)
4. error appears

[Log for setup.py](https://pastebin.com/yjMGVWwY)

## Expected behavior

Success build pytorch.

## Environment

[Environment](https://pastebin.com/Jh66Di0S)

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mszhanyi** [comment]
I tried that Pytorch could be built with Python 3.10.
did you run `'git submodule sync' `and `'git submodule update'` ?
what's your VS 2019 version?
The latest version might have some issues.
16.8.6 is used in PyTorch CI. My local is 16.9.12.
https://docs.microsoft.com/en-us/visualstudio/releases/2019/history

**Comment by colinxu2020** [comment]
I run `git submodule sync`and`git submodule update`
My CL.exe version is 19.27.29111
I didn't know how to query VS version without open VS.

**Comment by iremyux** [comment]
Hi,

`python setup.py bdist_wheel` command is used after a successful build to create a wheel file. This wheel file (created in the 'pytorch/dist' folder) would come in handy in future if you want to install PyTorch again without re-building it. 
I would suggest using the command `python setup.py install --cmake` to build PyTorch manually.

**Comment by iremyux** [comment]
Closing this issue due to inactiveness.
You can always create a new issue if you think there is a problem with PyTorch. Please keep in mind that this is not a support platform but a platform to report bugs or propose ideas to contribute PyTorch development.
