### ISSUE TITLE
During the Build LibTorch-Lite for arm64 Devices

### ISSUE THREAD

**Issue by Shahrukhpatel007** [pytorch/pytorch#67528]
When I am executing this command  -> BUILD_PYTORCH_MOBILE=1 IOS_ARCH=arm64 ./scripts/build_ios.sh
 I am getting this error 

 
 File "/Users/apple/Documents/GitHub/pytorch/tools/codegen/gen.py", line 81
    def parse_native_yaml(path: str) -> ParsedYaml:
                              ^
SyntaxError: invalid syntax
-- 
CMake Error at cmake/Codegen.cmake:232 (message):
  Failed to get generated_cpp list
Call Stack (most recent call first):
  caffe2/CMakeLists.txt:2 (include)

-- Configuring incomplete, errors occurred!

cc @malfet @seemethere

**Comment by jbschlosser** [comment]
Hey @Shahrukhpatel007, can you please provide more information on your environment to help us identify the problem? In particular, what version of python are you using?

**Comment by Shahrukhpatel007** [comment]
Hi, @jbschlosser Thank you for your response, actually, I have installed the latest version of python but, when I was running this command BUILD_PYTORCH_MOBILE=1 IOS_ARCH=arm64 ./scripts/build_ios.sh it's taking the old version of python which is may be 2.7 something

**Comment by essems** [comment]
in scripts/build_ios.sh
  CMAKE_ARGS+=("-DCMAKE_PREFIX_PATH=$(python3 -c 'import sysconfig; print(sysconfig.get_path("purelib"))')")
  CMAKE_ARGS+=("-DPYTHON_EXECUTABLE=$(python3 -c 'import sys; print(sys.executable)')")

this works find for me..

**Comment by jbschlosser** [comment]
Note that Python 2.x is not supported by PyTorch.

**Comment by seemethere** [comment]
@jbschlosser is correct, this appears to be a Python 2.7 issue and we do not currently support building with Python 2.7 so going to close

If you find the problem persists with Python 3.7+ feel free to open a new issue!
