### ISSUE TITLE
DDP Exception 

### ISSUE THREAD

**Issue by jakeywu** [pytorch/pytorch#67538]
## Two 3090, I have been training for an hour

```
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 102241 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 102242 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    result = agent.run()
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/elastic/agent/server/api.py", line 843, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/wuwanjie/miniconda3/envs/rc_server/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 60, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 102227 got signal: 1
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by jbschlosser** [comment]
Hey @jakeywu, could you please provide more details on the problem you're having? Ideally, this would be in the form a short, reproducible script, but I understand those can be especially hard to come up with for distributed workloads.

**Comment by kiukchung** [comment]
Looks like your trainers got terminated due to a SIGHUP which is typically sent when the controlling terminal is closed. Perhaps you launched the training script from a terminal multiplexer like tmux or screen, which was closed? Feel free to reopen with more details.

**Comment by jakeywu** [comment]
> Hey @jakeywu, could you please provide more details on the problem you're having? Ideally, this would be in the form a short, reproducible script, but I understand those can be especially hard to come up with for distributed workloads.

I'm sorry to just see that my solution to the problem is to lower the pytorch version(1.8.0), and I didn't explore this problem in depth.

**Comment by Dignity-ghost** [comment]
> 

This method really worked! Thanks for adivce.

**Comment by chyohoo** [comment]
I also met this problem using 1.10.1. I use `nohup` to do the training and the training terminated every 10 epchos.

**Comment by Dignity-ghost** [comment]
> I also met this problem using 1.10.1. I use `nohup` to do the training and the training terminated every 10 epchos.

I use tmux and it worked well. Using nohup seems that you can not close terminal otherwise DDP will be interuppted.

**Comment by sdreamforchen** [comment]
> > 
> 
> This method really worked! Thanks for adivce.

Hello， what method work， down to torch 1.8？？？

**Comment by Dignity-ghost** [comment]
> > > 
> > 
> > 
> > This method really worked! Thanks for adivce.
> 
> Hello， what method work， down to torch 1.8？？？

nohup may terminate pytorch program when close the terminal, but tmux really worked.

**Comment by sdreamforchen** [comment]
> > > > 
> > > 
> > > 
> > > This method really worked! Thanks for adivce.
> > 
> > 
> > Hello， what method work， down to torch 1.8？？？
> 
> nohup may terminate pytorch program when close the terminal, but tmux really worked.

Even use '&' after the GPU device number, nohup also may terminate pytorch program?  such as the arg of train: --device 1,2&.

**Comment by juju812** [comment]
> > > > 
> > > 
> > > 
> > > This method really worked! Thanks for adivce.
> > 
> > 
> > Hello， what method work， down to torch 1.8？？？
> 
> nohup may terminate pytorch program when close the terminal, but tmux really worked.

SIGHUP handler in Pytorch undoed `signal(SIGHUP, SIG_IGN)` by nohup, so pytorch program still received SIGHUP and exited.
Check this: [why-nohup-background-process-is-getting-killed](https://unix.stackexchange.com/questions/446625/why-nohup-background-process-is-getting-killed)

**Comment by daikankan** [comment]
Same problem with pytorch 1.10.0
![Screenshot from 2022-07-12 17-18-22](https://user-images.githubusercontent.com/20749514/178457343-1f7cec9b-8f1d-49af-9200-0ef48f50ad20.png)

**Comment by weiaicunzai** [comment]
I also have the same problem, two 3090s, pytorch version 1.13, cuda version 11.7

**Comment by shuuchen** [comment]
I met the same problem. Will this issue be solved in the future versions?

**Comment by sirosann** [comment]
> Same problem with pytorch 1.10.0 ![Screenshot from 2022-07-12 17-18-22](https://user-images.githubusercontent.com/20749514/178457343-1f7cec9b-8f1d-49af-9200-0ef48f50ad20.png)

excuse me,I have the same problem as you .and my torch version is 1.13.0. Did you already fixed the issue?

**Comment by zhuyuedlut** [comment]
![image](https://user-images.githubusercontent.com/24931666/234749583-877ea137-f9ef-468f-912d-8bcb89702d8a.png)

I also meet the same problem, but I don't know why this happen

**Comment by adildahlan** [comment]
> ![image](https://user-images.githubusercontent.com/24931666/234749583-877ea137-f9ef-468f-912d-8bcb89702d8a.png)
> 
> I also meet the same problem, but I don't know why this happen

Hey @zhuyuedlut, I am also facing the exact same problem when using accelerate for distributed training. I wonder if you eventually found a solution to this? Many thanks!

**Comment by kwang2049** [comment]
> > I also met this problem using 1.10.1. I use `nohup` to do the training and the training terminated every 10 epchos.
> 
> I use tmux and it worked well. Using nohup seems that you can not close terminal otherwise DDP will be interrupted.

I found this could work. But I am wondering why `nohup` works well with [transformers' trainer](https://huggingface.co/docs/transformers/main_classes/trainer) when using DDP?

**Comment by Z-Mooz** [comment]
So, if i work on Linux Server through ssh from Windows,  how could i deal with this problem?

**Comment by benchpress100** [comment]
> So, if i work on Linux Server through ssh from Windows, how could i deal with this problem?

1.setsid nohup python script.py > output.log 2>&1
2.update torch to 2.1.0

**Comment by benchpress100** [comment]
> > So, if i work on Linux Server through ssh from Windows, how could i deal with this problem?
> 
> 1.setsid nohup python script.py > output.log 2>&1 2.update torch to 2.1.0

I have tried both, and they both works.

**Comment by OHxhxs** [comment]
Hi, i have good solution!

i run the code like this. i got a same error..
`nohup accelerate launch -m axolotl.cli.train ./config/eeve_pretrain_qlora_fsdp.yml --num_processes=4  > output.log 2>&1 & `

so i make and resemble the file to run.sh 
`nohup accelerate launch -m axolotl.cli.train ./config/eeve_pretrain_qlora_fsdp.yml --num_processes=4 & >> background_logs/EEVE-Korean-Instruct-10.8B-bnb4bit.log 2>&1`

then i give authority to run.sh then, I ran it and it worked fine

`chmod -R 777 run.sh`
`./run.sh `
