### ISSUE TITLE
Cannot find libcaffe2_gpu.so

### ISSUE THREAD

**Issue by Flock1** [pytorch/pytorch#6755]
- PyTorch or Caffe2: Caffe2
- OS: Ubuntu 16.04
- How you installed PyTorch (conda, pip, source): source
- Python version: 2.7
- CUDA/cuDNN version: cuda 8, Cudnn 6
- GPU models and configuration: GTX 1080
- GCC version (if compiling from source): 5.4
- CMake version: 3.5.1
- Build command you used (if compiling from source): from caffe2.python import core (inside Python)
- Versions of any other relevant libraries:
I ran the code inside python and I got the following:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: libcaffe2_gpu.so: cannot open shared object file: No such file or directory
CRITICAL:root:Cannot load caffe2.python. Error: libcaffe2.so: cannot open shared object file: No such file or directory
```
I have added `libcaffe2_gpu.co` in the `LD_LIBRARY_PATH` but it's still giving me the warning). Can someone help?

**Comment by pjh5** [comment]
What is the build command that you used to build Caffe2? "from caffe2.python import core" is not a build command. This is a snippet of python code which the Python executable will try to run based on the libraries that it has installed. You must install Caffe2 for Python to use it correctly, and to install Caffe2 you must either build it from source or download a prebuilt binary from conda.

Please also post your full cmake output.

You should read through https://caffe2.ai/docs/faq.html , it will help you debug many of these types of errors.

**Comment by Flock1** [comment]
@pjh5, I was able to solve it by adding the location of the file to the LD_LIBRARY_PATH. It's solved and now, I'm able to use Caffe2. Thanks
