### ISSUE TITLE
Sharing file for init_process_group and init_rpc can potentially cause issues due to destructor of file

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#67566]
## 🐛 Bug

This issue was likely the reason for the flaky tests for #66488, #66951 which are now fixed.

When using the same file in file initialization for init_process_group and init_rpc, destruction of process_group will trigger the destructor of FileStore and remove the file from disk https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/FileStore.cpp#L277-L288. This can cause issues since the same file is also used by RPC.

## Basic Example

```python
import torch.distributed as dist
import torch.distributed.rpc as rpc
import tempfile
import os.path

file = tempfile.NamedTemporaryFile(delete=False)
file_name = file.name
print(f"Using file: {file_name}, File Exists: {os.path.isfile(file_name)}")

# Init RPC using file
rpc_backend_options = rpc.TensorPipeRpcBackendOptions()
rpc_backend_options.init_method = f"file://{file_name}"
rpc.init_rpc("worker", rank=0, world_size=1, rpc_backend_options=rpc_backend_options)

# Init PG using file
dist.init_process_group("gloo", rank=0, world_size=1, init_method=f"file://{file_name}")

# Destroying PG also removes file
dist.destroy_process_group()
print(f"File Exists: {os.path.isfile(file_name)}")
```

Output:
```
Using file: /tmp/tmplxkgrz_r, File Exists: True
File Exists: False
```

## Solutions 

(UPDATED to add context for bootcamp and incorporate Rohan's suggestion)

On initialization FileStore can [`add()`](https://pytorch.org/docs/master/distributed.html#torch.distributed.Store.add) an internal key for the number of FileStore instances that are currently using that file.

https://github.com/pytorch/pytorch/blob/d71b8e1a8db19facad9b4fdc580cc795b760ba99/torch/csrc/distributed/c10d/FileStore.cpp#L268-L274

On destruction, it should inspect this key and only delete the file if there are no more instances referencing it.

https://github.com/pytorch/pytorch/blob/d71b8e1a8db19facad9b4fdc580cc795b760ba99/torch/csrc/distributed/c10d/FileStore.cpp#L276-L301

## Validation

The script in the beginning of the description should return that the file still exists after `destroy_process_group()` because the FileStore instantiation during `init_rpc()` is still valid.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
If FileStore doesn't remove the final, will something else do so otherwise wouldn't we have a resource leak? 

Another potential idea is maybe to keep a counter of the number of references to the same file, and the FileStore destructor that runs can check the number of open references and only run the destructor if decrementing it would result in 0 references to the file?

**Comment by H-Huang** [comment]
reserve for bootcamp

**Comment by KinglittleQ** [comment]
Hi, I'd like to contribute to it.
