### ISSUE TITLE
Check if XLA-specific failures marked with `onlyOnCPUAndCUDA` in TestNNDeviceType can be skipped on the XLA side

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#67568]
Currently some tests in `TestNNDeviceType` are being marked with `onlyOnCPUAndCUDA`. Some have an additional comment explaining that this decorator is needed because the test is failing on XLA. 

Maybe the skipping should be done using https://github.com/pytorch/xla/blob/b63bb0528083d4d96d92d051eb4b9f9d12ef095b/test/pytorch_test_base.py#L230 instead.

This would allow devices like `meta` to be tested as well.

For context: https://github.com/pytorch/pytorch/issues/67493#issuecomment-954935607

cc @albanD @mruberry @jbschlosser @walterddr @bdhirsh

**Comment by mruberry** [comment]
I think this will be addressed by @kshitij12345's https://github.com/pytorch/pytorch/pull/66857 and https://github.com/pytorch/pytorch/pull/65201

**Comment by bdhirsh** [comment]
@mruberry do you have an opinion on how that should interact with [the allow-list logic](https://github.com/pytorch/xla/blob/1a8ea1f72d791a17283630ce5f6b8ac3be822b91/test/pytorch_test_base.py#L22) in pytorch/xla? They seem redundant, although I'm not sure which one is better (but in the current state, we'll end up with a combination of both).

**Comment by mruberry** [comment]
I think they'll complement each other for the near term. We don't want to litter the test suite with XLA-specific skips, so it probably makes sense for XLA to choose their tests (for now).
