### ISSUE TITLE
[Report] nightly build with Jupyter stuck

### ISSUE THREAD

**Issue by moskomule** [pytorch/pytorch#6757]
## What happened?

When I tried to import `pytorch` (nightly build) in both Jupyter notebook and lab, they got stuck and I got backtraces as below.

## My environment
- PyTorch nightly build
- OS: Ubuntu 16.04
- PyTorch version: Nightly 18 April version
- How you installed PyTorch (conda, pip, source): `conda install -c pytorch pytorch-nightly`
- Python version: 3.6
- CUDA/cuDNN version: 9.0 / 7
- Jupyter lab and notebook

```
jupyter-client (5.2.3)
jupyter-core (4.4.0)
jupyterlab (0.32.0)
jupyterlab-launcher (0.10.5)
```

## Backtrace log

It's a long log so I attach it.

```
*** Error in `/opt/.miniconda/bin/python': free(): invalid pointer: 0x00007fc8945c3d40 ***
```

[error.log](https://github.com/pytorch/pytorch/files/1927896/error.log)

**Comment by colinfang** [comment]
Does any one know which historic nightly version work with Jupyter?

**Comment by fmassa** [comment]
@moskomule just so I understand, when you execute a cell in a Jupyter notebook with the line `import torch`, the kernel of the notebook dies, is that right?

I've faced the same thing, but I didn't manage to get the jupyter notebook run from gdb. Thanks the stack trace!

**Comment by moskomule** [comment]
@fmassa Right. I think it would be critical for the tutorials.

**Comment by moskomule** [comment]
Still the latest nightly (20 April) gets stuck with `import torch`...

**Comment by fmassa** [comment]
Ok. I don't have access to my machine this weekend, I'll try compiling PyTorch from source on Monday to see if I can repro again.
cc. @soumith

**Comment by fmassa** [comment]
@moskomule I have just cloned and installed the latest version of pytorch in a new environment, installed jupyter notebook after updating pip, and I have no problems now importing pytorch in a jupyter notebook.

![image](https://user-images.githubusercontent.com/9110200/39118797-8282cf1a-46ea-11e8-8829-67cba16d5da9.png)


I'm closing this issue now as fixed, but let me know if it still doesn't work for you
