### ISSUE TITLE
How to upgrade the NCCL version of pytorch 1.7.1 from 2.7.8 to 2.11.4? 

### ISSUE THREAD

**Issue by cascgu** [pytorch/pytorch#67596]
I have installed version 2.11.4 in wsl2 and can pass the nccl-tests. However, when training the model, pytorch 1.7.1 still calls NCCL 2.7.8. In addition to rebuilding, is there a way for pytorch 1.7.1 to call NCCL 2.11.4 in the system instead of calling the compiled version NCCL 2.7.8？

**Comment by mruberry** [comment]
This question is better asked on the PyTorch forums. These GitHub issues are intended for feature requests and bug reports.
