### ISSUE TITLE
DISABLED test_create_store_single_server (__main__.DistributedUtilTest)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#67591]
test is flaky, example: https://github.com/pytorch/pytorch/runs/4054754297?check_suite_focus=true

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by mrshenli** [comment]
duplicated with #66207, closing
