### ISSUE TITLE
Feature request: Add option to average overlapping values to torch.nn.Fold

### ISSUE THREAD

**Issue by jayroxis** [pytorch/pytorch#67595]
## 🚀 Feature

Request for Options to Average Overlapping Values in `torch.nn.Fold`.

## Motivation

Sometimes, averaging overlapping values may give smoother transition. 

## Pitch

Add an option `overlap` to `torch.nn.Fold`, which can be `"sum"` or `"mean"`.

cc @albanD @mruberry @jbschlosser @walterddr

**Comment by albanD** [comment]
Aren't the overlaps always the same size? Could this be done by dividing the final result with the overlap size after Fold runs?

**Comment by jayroxis** [comment]
> Aren't the overlaps always the same size? Could this be done by dividing the final result with the overlap size after Fold runs?

Hi, thanks for the response! 

I have thought about division but the problem is, there are areas that are not overlapping so if I divide the entire tensor by a certain value, it can make those "nonoverlap area" have much smaller values. 

The correct way is to find the overlap areas and make divisions only on those areas, but it can be hard to do and I tried to do it, and the implementation is not flexible at all. On the other hand, I guess it can be much easier if it can be solved in the backend of the library.

Thanks a lot!

**Comment by flavioschneider** [comment]
One way you could do this is to fold a tensor of ones with the same shape as the input tensor, then the overlapping parts will be counted twice and by dividing the original folded tensor by the folded tensor of ones you average the overlapping values.
