### ISSUE TITLE
DISABLED test_remote_script_udf (__main__.TensorPipeJitRpcTest)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#67605]
Test timed out here: https://github.com/pytorch/pytorch/runs/4057157651?check_suite_focus=true.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd

**Comment by rohan-varma** [comment]
Closing to see if https://github.com/pytorch/pytorch/pull/68821 helps, or at least provides a better repro command.
