### ISSUE TITLE
DISABLED test_ddp_comparison (__main__.TensorPipeDdpComparisonTest)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#67604]
Test timed out here: https://github.com/pytorch/pytorch/runs/4059791464?check_suite_focus=true. 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @lw @beauby @jjlilley

**Comment by mrshenli** [comment]
duplicated with #66951 

looks like #65946 is not sufficient to fix.

**Comment by rohan-varma** [comment]
Closing to see if https://github.com/pytorch/pytorch/pull/68821 helps, or at least provides a better repro command.
