### ISSUE TITLE
DISABLED test_remote_script_udf (__main__.TensorPipeJitRpcTest)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#67607]
Test timed out waiting for a key here: https://github.com/pytorch/pytorch/runs/4057157651?check_suite_focus=true.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd @lw @beauby

**Comment by mrshenli** [comment]
duplicated with #67605, closing this one
