### ISSUE TITLE
DISABLED test_create_store_single_server (__main__.DistributedUtilTest)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#67606]
Test hit OSError here: https://github.com/pytorch/pytorch/runs/4054754297?check_suite_focus=true

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
cc @kiukchung @aivanou @d4l3k

**Comment by mrshenli** [comment]
oh, this is pointing to the same CI run as #67591, closing this one as #67591 is earlier
