### ISSUE TITLE
CSR to COO conversion

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#67654]
## 🚀 Feature
We currently allow COO to CSR conversion via to_sparse_csr, but not CSR to COO.

```
>>> indices = tensor([[0, 0, 1, 1, 2], [1, 2, 0, 2, 2]])
>>> values  = tensor([1., 2., 0, 3., 4])
>>> s = torch.sparse_coo_tensor(indices, values, (3, 3))
>>> s.to_sparse_csr().to_sparse()
[...]
NotImplementedError: Could not run 'aten::to_sparse' with arguments from the 'SparseCsrCPU' backend. 
```

## Motivation

A user might want to switch between these layouts to take advantage of their unique performance properties.

## Pitch

We support COO to CSR conversion, let's support CSR to COO too.

## Alternatives

The user could use the constructors, which would require a manual conversion of the index formats and doesn't have autograd support. Alternatively they could convert via the dense layout, but might not want to use the additional memory this requires. Further, the information of which zeros are specified or unspecified is lost via ```to_dense```, which matters for operations such as torch.sparse.softmax.

```
>>> s
tensor(indices=tensor([[0, 0, 1, 1, 2],
                       [1, 2, 0, 2, 2]]),
       values=tensor([1., 2., 0., 3., 4.]),
       size=(3, 3), nnz=5, layout=torch.sparse_coo)
>>> s.to_sparse_csr().to_dense().to_sparse()
tensor(indices=tensor([[0, 0, 1, 2],
                       [1, 2, 2, 2]]),
       values=tensor([1., 2., 3., 4.]),
       size=(3, 3), nnz=4, layout=torch.sparse_coo)
```

## Additional context

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

**Comment by pearu** [comment]
#66774 resolves this issue by introducing a new method `to_sparse_coo`.
