### ISSUE TITLE
LP Pooling stability issues

### ISSUE THREAD

**Issue by ejoebstl** [pytorch/pytorch#6765]
The gradient of LP-Pooling is undefined when the sum of all inputs to the power of `p` is zero. The current implementation will yield NAN in this case.

I would like to propose to set the gradient to zero in this case. 

That would, at least, not produce a NAN gradient, which propagates through the network and breaks other parameters.

**Comment by ejoebstl** [comment]
Quoted from @fmassa in #6766

> Another option would be to add an eps before taking the pow.

I'm not sure - there is also the probability of all inputs being epsilon. At least I don't see why the probability of all inputs being epsilon is lower than the probability of all inputs being zero.

**Comment by fmassa** [comment]
For `p` even, `out >= 0`, and thus adding an epsilon avoids the division by zero. That's not the case currently for `p` odd (and in this case I think we should add an `abs` in the code), but if we add the `abs` then the same case happens.

But as I said before, I'm not sure this is numerically better than your proposed solution.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/6766
