### ISSUE TITLE
PyTorch Profiler for distributed time count

### ISSUE THREAD

**Issue by liying-1997** [pytorch/pytorch#67683]
## ❓ What is included in ”Other" exactly?
I used pytorch profiler interface to count the four parts of running time in a 4-GPUs experiment. The result is as follows:

![image](https://user-images.githubusercontent.com/44020031/139894698-fdbe4470-5938-492c-8755-0514570c3068.png)

![image](https://user-images.githubusercontent.com/44020031/139897087-95378e1e-419b-474a-8e28-e6a3a6ae0eec.png)

Of these four parts, “other”(the green part)  accounts for the largest proportion.  What is included in ”Other" or what happened during this time?

 @ilia-cher @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git Thank you.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by mrshenli** [comment]
Hey @liyingathere, which distributed feature are you using?

**Comment by liyingathere** [comment]
> Hey @liyingathere, which distributed feature are you using?

Thank you for your reply. I used PyTorch DistributedDataParallel interface to test training with 4 GPUs. The training data is generated by customized buffer. 
```
with torch.profiler.profile(
            schedule = torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=2),
            on_trace_ready=torch.profiler.tensorboard_trace_handler('./log/trainer-1-10-data'),
            record_shapes=True, 
            profile_memory=True,
            with_stack=True,
        ) as prof:
            for data, indices, weights in loader:
                loss = trainer.step(data, weights=weights)
                prof.step()
```
Looking forward to your reply.

**Comment by guyang3532** [comment]
Yes, the "Computation" part is time for computation on GPU, so the "Other" part includes time for loading data, execution on CPU, etc.

**Comment by aaronenyeshi** [comment]
Closing old issue, please reopen in https://github.com/pytorch/kineto if issue persists.
