### ISSUE TITLE
PicklingError encountered when using multiple GPUs

### ISSUE THREAD

**Issue by TotalVariation** [pytorch/pytorch#67681]
## 🐛 Bug

Hello,

I was using Slurm-based HPC with multiple GPUs to train deep learning models. 

![Screenshot from 2021-11-02 14-31-12](https://user-images.githubusercontent.com/36463966/139871575-67b400f4-a6c9-4848-a1aa-673c7f8390aa.png)

![Screenshot from 2021-11-02 14-32-20](https://user-images.githubusercontent.com/36463966/139871600-0b8c39b8-4874-4472-b616-4cdec4d19d7e.png)

I believe this pickle error was caused by multiprocessing but I have little knowledge about this. Thank you so much.

## Environment
![Screenshot from 2021-11-02 15-03-09](https://user-images.githubusercontent.com/36463966/139873665-3949d1f0-2222-49c3-9dfa-d5e836a11aae.png)
![Screenshot from 2021-11-02 15-03-36](https://user-images.githubusercontent.com/36463966/139873683-d47de0aa-93c8-40c1-a492-94d8c6cb51fb.png)

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Potentially the problem came from your implementation of Dataset based on your trace.

Could you please post more detail about it so we can reproduce the error?

**Comment by TotalVariation** [comment]
Thank you @ejguan for your quick response.

![Screenshot from 2021-11-03 14-20-19](https://user-images.githubusercontent.com/36463966/140078023-2b5bc4b4-01a2-467d-b070-0069f65d08d7.png)

I believe this error is related to multiprocessing used in `Torch`. It would force everything to be pickled. But there are some packages that are dependent on `sh` in my code, which contains a class called `GlobResults` that is not meant for pickling. Here is the same issue I posted on amoffat/sh#590, which you can refer to.

**Comment by ecederstrand** [comment]
Something is calling `sh.glob()`. Is that in your own code? Assuming this happens in your own code, you need to decide whether you want the globbing to happen before or after spawning the process. Either:

1. Pass around the arguments for `sh.glob()` and run the command in the spawned process
2. Convert the result of `sh.glob()` to something that can be pickled, and pass the result around:

```python
>>> import pickle, sh
>>> pickle.dumps(sh.glob('*'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'sh.GlobResults'>: attribute lookup GlobResults on sh failed
>>> pickle.dumps(list(sh.glob('*')))
b'...'
```

**Comment by TotalVariation** [comment]
@ecederstrand Thank you again for your solution. This is the exact reason why there would be a pickling error. I have solved the issue by following your code snippet.

**Comment by NivekT** [comment]
Seems like this issue is resolved, so I will close this.

@TotalVariation let us know if there is any further issue or suggestion for changes.
