### ISSUE TITLE
`test_svd_errors_and_warnings` tests fail on CPU

### ISSUE THREAD

**Issue by casparvl** [pytorch/pytorch#67693]
## 🐛 Bug

The tests `test_svd_errors_and_warnings_cpu_complex128`, `test_svd_errors_and_warnings_cpu_complex64`, `test_svd_errors_and_warnings_cpu_float32` and `test_svd_errors_and_warnings_cpu_float64` fail with the following traceback:

```
======================================================================
FAIL: test_svd_errors_and_warnings_cpu_complex128 (__main__.TestLinalgCPU)
----------------------------------------------------------------------
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/native/LinearAlgebraUtils.h":243, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the
 implementation calling the backend library.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 368, in instantiated_test
    result = test(self, **param_kwargs)
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 769, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 769, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/tmp/casparl/eb_build/PyTorch/1.10.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_linalg.py", line 2903, in test_svd_errors_and_warnings
    svd(a)
AssertionError: "The algorithm failed to converge" does not match "falseINTERNAL ASSERT FAILED at "../aten/src/ATen/native/LinearAlgebraUtils.h":243, please report a bug to PyTorch. svd_cpu: Argument 4 ha
s illegal value. Most certainly there is a bug in the implementation calling the backend library."
```

## To Reproduce

1. Install PyTorch 1.10.0 from sources, building against OpenBLAS 0.3.15
2. Run `python run_test.py -i test_linalg.TestLinalgCPU -v` to run the relevant part of the test suite
3. (alternative): instead of running the test from the test suite, simply do 
```
import torch
a = torch.full((3, 3), float('nan'), dtype=torch.float32, device='cpu')
torch.svd(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/native/LinearAlgebraUtils.h":243, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```

## Expected behavior

It makes sense that torch.svd wouldn't complete on a tensor of NaN's. However, the test suite clearly expects this type of error:

```
with self.assertRaisesRegex(RuntimeError, "The algorithm failed to converge"):
    svd(a)
```
But instead, I get the error above. That error looks more serious: it seems the implementation calling the backend library makes some invalid call in this particular scenario. Note that a

```
a = torch.eye(3, 3, dtype=torch.float32, device='cpu')
torch.svd(a)
```
Runs without any issues, it's really the NaN input that breaks it.

Summarizing: one wouldn't assume a `torch.svd(a)` to complete succesfully when `a` contains NaN's, but I (and the test suite) do expect a different error.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): CentOS 8
 - How you installed PyTorch (`conda`, `pip`, source): source 
 - Build command you used (if compiling from source):
```
USE_CUPTI_SO=1 PYTORCH_BUILD_VERSION=1.10.0 PYTORCH_BUILD_NUMBER=1 MAX_JOBS=72 BLAS=Eigen WITH_BLAS=open USE_FFMPEG=1 BUILD_CUSTOM_PROTOBUF=0 USE_IBVERBS=1 USE_CUDA=1 CUDNN_LIB_DIR=/tmp/sw_stack_gpu/software/cuDNN/8.2.1.32-CUDA-11.3.1/lib64 CUDNN_INCLUDE_DIR=/tmp/sw_stack_gpu/software/cuDNN/8.2.1.32-CUDA-11.3.1/include USE_SYSTEM_NCCL=1 NCCL_INCLUDE_DIR=/tmp/sw_stack_gpu/software/NCCL/2.10.3-GCCcore-10.3.0-CUDA-11.3.1/include USE_METAL=0   /tmp/sw_stack_gpu/software/Python/3.9.5-GCCcore-10.3.0/bin/python setup.py build
```
 - Python version: 3.9.5
 - CUDA/cuDNN version: CUDA: 11.3.1, cuDNN: 8.2.1.32
 - GPU models and configuration: N/A
 - Any other relevant information: I'm building against OpenBLAS 0.3.15, so that should be the CPU backend in this case.

## Additional context

I've also hit [this issue](https://github.com/pytorch/pytorch/issues/67675) due to the fact that my `numpy` was compiled against the same `OpenBLAS` version, and apparantly the behaviour of how NaN's are propagated has changed from OpenBLAS 0.3.15 onwards (see https://github.com/numpy/numpy/issues/18914). I'm not sure if the current issue is related, but since it occurs specifically when the input matrices contain NaN's, I guess it could be.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by IvanYashchuk** [comment]
Thank you @casparvl for submitting the issue! Unfortunately, there are no CI jobs configured to compile PyTorch with OpenBLAS instead of MKL to catch errors like that (https://github.com/pytorch/pytorch/issues/53910).

This comment https://github.com/numpy/numpy/issues/18914#issuecomment-839941847 contains the summary of recent changes in [Reference-LAPACK](https://github.com/Reference-LAPACK/lapack) that OpenBLAS uses.

The fix would be to detect when PyTorch is linked with OpenBLAS and when the returned error code from LAPACK is 4 fill the output with NaNs instead of raising the INTERNAL ASSERT error.

**Comment by casparvl** [comment]
Thanks for the quick response @IvanYashchuk , I had assumed the "Argument 4 has illegal value" refered to a function argument, but I guess this means it refers to the `-4` return statement from LAPACK. Anyway, it's clear to me that at the very least this is a case where one might expect a different error, but it's not like this PyTorch build will give me fundamentally incorrect results. For me, that's enough to confidently ignore the failing test.

Do you still expect anything from me? I'm afraid that implementing a fix along the lines you proposed is beyond my expertise on the PyTorch codebase...

**Comment by IvanYashchuk** [comment]
> Do you still expect anything from me? I'm afraid that implementing a fix along the lines you proposed is beyond my expertise on the PyTorch codebase...

No worries! Reporting the problem is the most important thing and less interesting work of fixing the bug is on the PyTorch team 😉

**Comment by casparvl** [comment]
Thanks! :)

For later reference of myself and others who run into this: this same issue also breaks the `test_norm_extreme_values_cpu (__main__.TestLinalgCPU)` test:

```
======================================================================
ERROR: test_norm_extreme_values_cpu (__main__.TestLinalgCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 373, in instantiated_test
    raise rte
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 368, in instantiated_test
    result = test(self, **param_kwargs)
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 769, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/tmp/casparl/eb_tmp/eb-zicdqucj/tmp5xk49djn/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 769, in dep_fn
    return fn(slf, *args, **kwargs)
  File "/tmp/casparl/eb_build/PyTorch/1.10.0/foss-2021a-CUDA-11.3.1/pytorch/test/test_linalg.py", line 1886, in test_norm_extreme_values
    result = torch.linalg.norm(x, ord=ord)
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/native/LinearAlgebraUtils.h":243, please report a bug to PyTorch. svd_cpu: Argument 4 has illegal value. Most certainly there is a bug in the
 implementation calling the backend library.
```
Reason is that the test runs this https://github.com/pytorch/pytorch/blob/510336499b4f13f10034893333fbd924e271631b/test/test_linalg.py#L1892 with
`x=tensor([[inf, nan]])` and `ord='nuc'`, which results in the same runtime error (and thus fails the subsequent `assertEqual` which would compare numpy and pytorch results).

Similar to the `test_svd_errors_and_warnings` failures, this test can thus be ignored if this error pops up in a PyTorch build against OpenBLAS 0.3.15 (or later)

**Comment by IvanYashchuk** [comment]
The same error started to appear in the MKL build https://github.com/pytorch/pytorch/runs/4899014335?check_suite_focus=true#step:17:15487
Maybe the latest MKL 2022.0.1 uses the latest reference LAPACK.
