### ISSUE TITLE
When will you release a Windows branch for Pytorch?

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#677]
I see there we have finally a python wrapper for torch. Thank you very much for that . 
Do you guys plan on supporting windows any time soon? I'd appreciate if someone sheds some light on this

**Comment by soumith** [comment]
we have no plans of supporting windows, unless someone from the community steps in to do this work.

**Comment by apaszke** [comment]
And there's an issue on that already - #494

**Comment by acerqu** [comment]
Is it possible run a cygwin version on windows?
