### ISSUE TITLE
CI: Add timeouts for GHA jobs

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#67713]
Why?

1. It would make it easier to detect when timeouts happen
2. Given the current behavior, a job could go on forever (or can it?)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
We can probably just set a global `timeout-minutes` that's present for each step that's some sort of sane value like 4hr (250min)

This'd utilize [`defaults.run`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaultsrun) and then [`timeout-minutes`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) to set it at the top level
