### ISSUE TITLE
runHealthCheck in ProcessGroupNCCL constructor causes extra cuda-context 

### ISSUE THREAD

**Issue by zarzen** [pytorch/pytorch#67724]
## 🐛 Bug (on master branch)

Creating sub groups with `torch.distributed.distributed_c10d.new_group` creates extra cuda-context on other GPUs. 
For example, we have 8 GPUs in total, and want to create a sub process group for ranks `[2,3]`. We are going to see
extra cuda-context created on GPU-0 and GPU-1. Because the group rank of rank-2 is `0`, and rank-3's group rank is `1`. 

Reasons:
`runHealthCheck` function create `ncclCommunicator` on device with value returned from `getDeviceForRank(rank_)`. The `rank_` here is the group_rank rather than global rank. 

https://github.com/pytorch/pytorch/blob/0b2f68eadf5e9e99c0fdf8ff761ddcac126f224e/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L562

The reason for `rank_` to be the `group_rank`: 
https://github.com/pytorch/pytorch/blob/0b2f68eadf5e9e99c0fdf8ff761ddcac126f224e/torch/distributed/distributed_c10d.py#L2912

## To Reproduce

1. `torch.distributed.init_process_group('nccl')`
2. `torch.distributed.new_group([2,3], backend='nccl')`

## Expected behavior

The device used for creating `ncclCommunicator` should be the current device user specified. So that the extra cuda-context is avoided. 

## Environment

```
PyTorch version: 1.11.0a0+git7508557
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)
Clang version: 7.0.1 (Amazon Linux 2 7.0.1-1.amzn2.0.2)
CMake version: version 3.18.2
Libc version: glibc-2.2.5

Python version: 3.7.9 (default, Aug 27 2020, 21:59:41)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-9)] (64-bit runtime)
Python platform: Linux-4.14.200-155.322.amzn2.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.3
[pip3] pytorch-ignite==0.4.2
[pip3] torch==1.11.0a0+git7508557
[pip3] torchvision==0.8.1
[conda] Could not collect
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Thanks for the report! Agreed that we shouldn't be creating these extra CUDA contexts, although after the health check completes, we do clean up the communicators, so I'm not sure why the CUDA contexts stay around.

For unrelated reasons, we actually recently landed a PR https://github.com/pytorch/pytorch/pull/67668 to disable this check by default as we debug and improve the feature. If you patch the latest PT the issue should go away due to this, and we'll make sure this is fixed before re-introducing the health check by default.

One quick realization is that we only should ever run the health check when the default process group is created, as the purpose is mainly to ensure NCCL communicators can be created reliably, we don't need to run this health check when a `dist.new_group()` is created.

**Comment by zarzen** [comment]
Thanks for the update! 
The cuda context won't be deleted, until we explicitly destroy the context. 
The `ncclCommDestroy` should not have that functionality, as other components using cuda might have unfinished jobs. 
I think I can close the issue for now.

**Comment by rohan-varma** [comment]
@zarzen Just to clarify, did you only see this issue when creating subgroups? When we re-enable this functionality we don't plan on running the health check for subgroups, so this should be a non-issue?

**Comment by zarzen** [comment]
sorry for the late reply.
right, I think so, if the health check only runs at the first global group initialization, the local rank should match the GPU affinity exactly.
