### ISSUE TITLE
Alleviate sccache connectivity issues on CI

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#67720]
See on 11/2:

[PyTorch] Add IValue::toTupleRef() (#65504) win-vs2019-cuda11.3-py3 on trunk: https://github.com/pytorch/pytorch/runs/4083329308?check_suite_focus=true

and also in binaries
https://app.circleci.com/pipelines/github/pytorch/pytorch/403881/workflows/9fb5af0d-a370-4170-ba55-fab0095f2f73/jobs/16649825

```
FAILED: third_party/fbgemm/CMakeFiles/fbgemm_generic.dir/src/EmbeddingSpMDMNBit.cc.obj 
C:\w\b\windows\tmp_bin\sccache-cl.exe  /nologo /TP -DTH_BLAS_MKL -DWIN32_LEAN_AND_MEAN -D_OPENMP_NOFORCE_MANIFEST -I..\third_party\cpuinfo\include -I..\third_party\fbgemm\third_party\asmjit\src -I..\third_party\fbgemm\include -I..\third_party\fbgemm -I..\cmake\..\third_party\benchmark\include -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -IC:\w\b\windows\mkl\include -I..\third_party\XNNPACK\include /DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/w/b/windows/mkl/include /wd4244 /wd4267 /wd4305 /wd4309 /MD /O2 /Ob2 /DNDEBUG /w /bigobj -std:c++14 /showIncludes /Fothird_party\fbgemm\CMakeFiles\fbgemm_generic.dir\src\EmbeddingSpMDMNBit.cc.obj /Fdthird_party\fbgemm\CMakeFiles\fbgemm_generic.dir\ /FS -c ..\third_party\fbgemm\src\EmbeddingSpMDMNBit.cc
error: failed to execute compile
caused by: error reading compile response from server
caused by: Failed to read response header
caused by: failed to fill whole buffer
```

Some previous investigation done by @suo suggests investigating mozilla/sccache#256. Suggested fixes in that issue are 1) reducing parallelism, and 2) increasing the timeout 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Most likely related to `Windows Sockets error 10054` meaning sccache might've exited with error while clients were attempting to connect

**Comment by seemethere** [comment]
Partially mitigated by migration to GHA, need to research if this is still a prevalent issue

**Comment by mszhanyi** [comment]
Let's see more stat. since https://github.com/pytorch/pytorch/pull/72795 was merged on Last Friday.

**Comment by janeyx99** [comment]
It looks like the last instance was found on Feb 17:

https://circleci.com/gh/pytorch/pytorch/17006834

So this seems fixed!

**Comment by mszhanyi** [comment]
Thanks @janeyx99 
The latest sccache is updated on Feb 17.
![image](https://user-images.githubusercontent.com/16190118/156270335-e13c3ff8-a0ea-40db-8ef8-6c16a1f8411f.png)
If there isn't any other significant changes, it should be caused by this change.
