### ISSUE TITLE
How to build libtorch on aarch64 machine?

### ISSUE THREAD

**Issue by zihaoliao** [pytorch/pytorch#67757]
I used command lines below to build libtorch on aarch64 machine.
```shell
git clone https://github.com/pytorch/pytorch --recursive
cd pytorch
pip3 install pyyaml # 缺失相关依赖，进行安装，如有其他缺失，依次安装即可
export USE_CUDA=False # 使用cpu
export BUILD_TEST=False # 不编译测试部分
python3 ../tools/build_libtorch.py # 会自动创建build文件夹，并进行相关编译
```
But when I test it like [example](https://pytorch.org/cppdocs/installing.html),it shows some error.
![image](https://user-images.githubusercontent.com/7894966/140027833-0e27c9b0-578d-4dde-bb8d-1dd88e2516b7.png)
I see that size of my libtorch_cpu.so is only 100Mb,far less than the official one in cpu. But I dont konw whats wrong with it.

**Comment by bdhirsh** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/.

I'm not sure about the `build_libtorch.py` script, but you should also be able to build libtorch through `python setup.py develop`.
