### ISSUE TITLE
[Caffe2] Unable to clone Caffe2 repo

### ISSUE THREAD

**Issue by gautamkmr** [pytorch/pytorch#6776]
command run
git clone --recursive  https://github.com/caffe2/caffe2

Checking connectivity... done.
Submodule path 'third_party/zstd': checked out 'aec56a52fbab207fc639a1937d1e708a282edca8'
Unable to checkout 'f3c627d517968c20e8269ead1d90cd3a6c199356' in submodule path 'third_party/aten'

PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2:
- OS:
- PyTorch version:
- How you installed PyTorch (conda, pip, source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

**Comment by gautamkmr** [comment]
Do we have any update ?

**Comment by dbermond** [comment]
You should not clone the caffe2 git repository from https://github.com/caffe2/caffe2/ because the code moved to pytorch. See: https://github.com/caffe2/caffe2/commit/a062b05d70c75a6005c6e76109a1dde482729a53.

Instead, clone the one from https://github.com/pytorch/pytorch/.

Like this:

```
$ git clone --recursive https://github.com/pytorch/pytorch.git
```

**Comment by gautamkmr** [comment]
@soumith any help ?

**Comment by pjh5** [comment]
@gautamkmr the instructions from @dbermond are completely correct. The caffe2 code is at https://github.com/pytorch/pytorch
