### ISSUE TITLE
When the result is negative, // operator behaves differently with a torch.Tensor than with a np.ndarray or a standard python value

### ISSUE THREAD

**Issue by lucgiffon** [pytorch/pytorch#67771]
## 🐛 Bug

When applying the // operator to a torch.Tensor with negative values, I get the result of the truncated division instead of the floor division.

## To Reproduce

    neg_val = -4
    expected_result = neg_val // 3
    torch_result = torch.Tensor([neg_val]) // 3
    assert expected_result == torch_result

## Expected behavior

Floor division applied to torch.Tensor should behave the same than floor division.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (beaver-osp1-gilly X33) (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.1+cpu
[pip3] torchaudio==0.9.1
[pip3] torchvision==0.10.1+cpu
[conda] Could not collect

```

cc @mruberry @rgommers

**Comment by lucgiffon** [comment]
Oh yes, you are totally correct.

So that's it. Nothing to add.

**Comment by mruberry** [comment]
> Oh yes, you are totally correct.
> 
> So that's it. Nothing to add.

Yep, sorry you're hitting this known bug but there is a workaround (as the warning message suggests) and (as the warning also states) we will change the behavior of floor divide to actually be floor division in the future. These changes just take time because some users may be relying on the truncation division behavior.
