### ISSUE TITLE
Feature request: add (log_)gamma and (log_)beta functions

### ISSUE THREAD

**Issue by stepelu** [pytorch/pytorch#678]
It would be nice if some special math functions would be available in PyTorch with CUDA support.

I am working with neural networks with probabilistic components and as such it's necessary for me to compute the (log-)pdf, which often requires the computation of currently unavailable math functions.

A good start would be to support the gamma, log_gamma, beta, log_beta and factorial functions.

I am aware that I can write my own NumPy-based-modules, but that precludes the use of CUDA rendering training of such models basically impossible (and it's also error prone in terms of derivatives).

As an aside, great work here!

**Comment by apaszke** [comment]
@stepelu I don't think we have any functions for computing the pdfs, we only have methods that allow to sample from distributions parametrized by tensor contents. Is that what you need? It should be straightforward to compute pdfs by yourself with autograd ops right? This should work with CUDA too.

**Comment by stepelu** [comment]
@apaszke to clarify: I am indeed implementing pdfs, the issue is that some of them require mathematical functions not available in PyTorch. For example the [gamma distribution](https://en.wikipedia.org/wiki/Gamma_distribution) pdf requires the [gamma math function](https://en.wikipedia.org/wiki/Gamma_function), and the Beta and Dirichlet distribution pdfs require the beta math function. In practice, for stability reasons, it's best to work with log-pdfs (which would require the log-gamma and log-beta math functions). As the models I am working with are quite complex CUDA acceleration is required in order to train them.

**Comment by apaszke** [comment]
I see, thanks for the clarification. It seems that log-gamma is already available as part of C99 standard, so it should be quite easy to add that. For beta, we'd need to find a good implementation - it's been only added in C++17. We could compute it using the gamma, but I'm not sure about the numerical stability of that.

**Comment by YutingZhang** [comment]
@apaszke Is there a timeline for this? 
A lgamma autograd Function will be very helpful for handling many probability distributions.

lgamma is available in CUDA, but its derivative (i.e., 0-order polygamma) is not.

Thanks!

**Comment by apaszke** [comment]
That's true. Adding lgamma should be easy and maybe we can do that soon, but I don't think we're going to invest much effort into porting digamma for CUDA right now. It might be possible to adapt some existing implementation (e.g. from [Boost](https://github.com/boostorg/math/blob/242e9d669198415d165bb0213f730c00985bee9a/include/boost/math/special_functions/digamma.hpp)), but it might be quite time consuming.

Still, if any of you knows CUDA and wants to give it a try, then we can help you with some code pointers and reviews.

**Comment by ethanluoyc** [comment]
Hi @apaszke I created a PR for implementing the lgamma function. However, for some reason the function seems not to be registered on the Python side. I changed TensorMethods.cwrap which I believe is where I declare the interface for Python. Do I need to do that anywhere else?

**Comment by ankitp94** [comment]
Any idea when the digamma functionality would be added?

**Comment by apaszke** [comment]
There are a lot of high priority tasks that we're going to tackle first, but we can provide help in case someone wants to submit a PR. It would be nearly equivalent to that of @ethanluoyc, except that digamma is not part of the C/C++ library, so one would have to find a good CPU/CUDA implementation.

**Comment by rachtsingh** [comment]
@ankitp94 if you need an implementation today (for research, not prod) you should check out https://github.com/rachtsingh/lgamma

@apaszke if you're OK with using source from Eigen, they have [an implementation](https://bitbucket.org/eigen/eigen/pull-requests/173/added-zeta-function-of-two-arguments-and/diff) based on Cephes of these functions in C++ which I basically copied for my hacky implementation above. Let me know and I'll start working on a PR.

**Comment by ankitp94** [comment]
@rachtsingh  Thanks a lot! :)

**Comment by stepelu** [comment]
Eigen's license could be an issue, might be worth checking with the specific authors if they're fine dual-licensing the relevant code

**Comment by fritzo** [comment]
@colesbury @soumith could you prioritize this? `digamma` is blocking the following probability distributions: `Binomial`, `Multinomial`, `Gamma`, `Beta`, and `Dirichlet`.

**Comment by soumith** [comment]
will do. @zou3519 can you take this one?

**Comment by zou3519** [comment]
Sure, I can take these

**Comment by rachtsingh** [comment]
Let me know if you want any help on this! I have a few CUDA implementations / have debugged some of the gotchas in this case.

**Comment by fritzo** [comment]
How feasible would it be to wrap all Cephes special functions as in https://github.com/deepmind/torch-cephes ? This wholesale approach is also taken by Scipy.

**Comment by fritzo** [comment]
I believe this can be closed. #4399 implemented `digamma(x)` and `polygamma(1,x)` (aka `trigamma(x)`), so `torch.lgamma` is now be *twice* differentiable.

**Comment by apaszke** [comment]
we still don't have native support for (log)beta. not sure how important that is since it can be computed using lgamma

**Comment by rachtsingh** [comment]
In my experience, implementing it from lgamma is stable enough (https://github.com/rachtsingh/ibp_vae/blob/master/src/lgamma/beta.py#L22).

**Comment by fritzo** [comment]
Right we're already using `lbeta(x,y) = lgamma(x) + lgamma(y) - lgamma(x,y)` in torch.distributions:
https://github.com/pytorch/pytorch/blob/35abc4e/torch/distributions/dirichlet.py#L63

**Comment by rachtsingh** [comment]
Oh, I was trying to remember this: there's a lot of special purpose code handling [here](https://github.com/scipy/scipy/blob/master/scipy/special/cephes/beta.c#L138) (inside Cephes) based on the relative scale of the arguments, but I don't think it ended up mattering much.

**Comment by apaszke** [comment]
Alright, I'll close this. We can always create a new issue if it turns out to be an unstable approximation.

**Comment by teichert** [comment]
@fritzo is that supposed to be `lbeta(x,y) = lgamma(x) + lgamma(y) - lgamma(x+y)` instead of `lbeta(x,y) = lgamma(x) + lgamma(y) - lgamma(x,y)`?

**Comment by Balandat** [comment]
Looks like there currently is no implementation of the (log-) multivariate Gamma function? That would be useful for implementing Wishart / inverse Wishart distributions. Any plans to add this?

The straightforward way to do this would be to reduce it to multiple `lgamma` evaluations using the identity 35.3.4 from https://dlmf.nist.gov/35.3. I'm not sure how numerically stable that is, but it doesn't look too bad at first glance.

**Comment by soumith** [comment]
@Balandat would you open a separate issue for that request. cc: @vishwakftw and @alicanb on any interest in implementing @Balandat 's request.

**Comment by Balandat** [comment]
Sure, new issue here: #9378

**Comment by RylanSchaeffer** [comment]
@apaszke @fritzo @zou3519 I'd like to request that (log) beta be added regardless. I would prefer if I could just use the function in PyTorch without needing to roll my own implementation (which is prone to errors) or find others' solutions, even if @teichert 's solution is fine.

**Comment by RylanSchaeffer** [comment]
It also looks like @rachtsingh did the heavy lifting with the link he shared: https://github.com/rachtsingh/ibp_vae/blob/master/src/lgamma/beta.py#L22.  Could we just add that to PyTorch?

**Comment by LoicGrobol** [comment]
@apaszke @fritzo @zou3519 @RylanSchaeffer The stability of $\log\Gamma(x) + \log\Gamma(y) - \log\Gamma(x+y)$ is not the best. See for instance the strategy used in SciPy: <https://github.com/scipy/scipy/blob/ae3ca70a72ef04547fbc28501009246cef5ee6c8/scipy/special/cdflib/betaln.f>.
