### ISSUE TITLE
[ONNX] Cannot export upsample op

### ISSUE THREAD

**Issue by yzhsjtu** [pytorch/pytorch#6780]
My model contains a 2D upsample op
nn.Upsample(scale_factor=4, mode='bilinear')

But it cannot be exported to ONNX

- PyTorch or Caffe2: Pytorch
- OS: Ubuntu 16.01
- PyTorch version: 0.4.0a0+f8270c0
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6.4

torch.onnx.export(self, [input_var], os.path.join(output_path, "model.onnx"), output_names=output_names)
1070 File "/lib/python3.6/site-packages/torch/onnx/__init__.py", line 12, in export
1071     return utils.export(*args, **kwargs)
1072   File "/lib/python3.6/site-packages/torch/onnx/utils.py", line 83, in export
1073     _export(model, args, f, export_params, verbose, training, input_names, output_names)
1074   File "/lib/python3.6/site-packages/torch/onnx/utils.py", line 138, in _export
1075     _optimize_trace(trace, aten)
1076   File "/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in _optimize_trace
1077     torch._C._jit_pass_onnx(trace, aten)
1078   File "/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in _run_symbolic_function
1079     return utils._run_symbolic_function(*args, **kwargs)
1080   File "/lib/python3.6/site-packages/torch/onnx/utils.py", line 333, in _run_symbolic_function
1081     return fn(g, *inputs, **attrs)
1082 TypeError: upsample_bilinear2d() got an unexpected keyword argument 'align_corners' (occurred when translating upsample_bilinear2d)

**Comment by loztop** [comment]
I have the same issue using Pytorch 0.4.0

**Comment by ojus1** [comment]
Same problem here.

**Comment by fgtoralesch** [comment]
Sorry, my explanation could be misleading (I will correct it now) @springishere. If you try to use tensorboardX the model is exported with ONNX and then the same bug appears.

Answering your question, if you update to the latest ONNX and pytorch-nightly it should work. However, I don't know to which commit the fix belongs to. I hope that helps.

**Comment by glenn-jocher** [comment]
I'm having the same problem currently in both PyTorch 1.0 (stable) and PyTorch 1.0 (nightly). PyTorch fails to properly create the `height_scale` and `width_scale` operators. Instead the `scale_factor=4` parameter remains as a `CPUFloatType{4}` value. Is there any plan to fix this?

`%121 : Tensor = onnx::Constant[value= 1  1  2  2 [ **CPUFloatType{4}** ]](), scope: Darknet/Sequential/UpsampleCustom[upsample_19]`

**Comment by ahirner** [comment]
FWIW, our current workaround is converting shape information to python ints for the size parameter. It works for a fixed resolution trace only, of course.

**Comment by glenn-jocher** [comment]
@ahirner could you elaborate on your solution or show us your code? Thanks!

**Comment by ahirner** [comment]
Sure @glenn-jocher , there are two ways to make bilinear upsample work with certain constraints. 

At first we exported at fixed scale. This works for **pytorch < #59b7539**. 
```
def upsample_fixed_twice(g, x, y):
    # Todo: must wait for https://github.com/onnx/onnx/pull/1467 for true dynamic upsample
    height_scale = y.type().sizes()[-2] / x.type().sizes()[-2]
    width_scale = y.type().sizes()[-1] / x.type().sizes()[-1]

    return g.op("Upsample", x, scales_f=[1., 1., height_scale, width_scale],
                mode_s="linear")

@symbolic_override(upsample_fixed_twice)
def upsample_to(x, y):
    _, _, H, W = y.size()
    return F.interpolate(x, size=[H, W], mode="bilinear",
                         align_corners=False)
```

In **pytorch >= #59b7539** it's not clear how to use symbolic override (#14338). Also, dynamic upsample should actually work. As per this issue, the second best option for us was to fix `size`. Sizes from this trace are then static.

```
def upsample_to(x, y):
    _, _, H, W = y.size()
    # See above, scaling by tensor size would throw:
    # ONNX symbolic expected a constant value in the trace
    return F.interpolate(x, size=[int(H), int(W)], mode="bilinear",
                         align_corners=False)
```


I think adding a test with `bilinear` and dynamic sizes would be a great PR. `nearest` is being [tested for](https://github.com/linkerzhang/onnx/blob/6197198ec3b0ab0f39915af0244d763ebeaf9948/onnx/backend/test/case/node/upsample.py).

**Comment by bhack** [comment]
Any news on this?

**Comment by houseroad** [comment]
Will check it soon. Sorry for the delay.

**Comment by darolt** [comment]
Hi,

I'm using pytorch 1.1 and this issue is still present. @ahirner workaround seems to work. Otherwise this error is raised:
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

**Comment by alexdonchuk** [comment]
If build from sources its ok.

пн, 3 июн. 2019 г., 5:54 darolt <notifications@github.com>:

**Comment by Bridxo** [comment]
I have similar problem just like this @ahirner solution not work on me;;

here is the error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 32, in export
    return utils.export(*args, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 168, in export
    example_outputs=example_outputs, strip_doc_string=strip_doc_string, dynamic_axes=dynamic_axes)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 405, in _export
    _retain_param_name, do_constant_folding)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 316, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 225, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 57, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 639, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 70, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'upsample_bilinear2d'
`
I don't get where the error occurs :(

**Comment by glenn-jocher** [comment]
I receive a PyTorch - ONNX Export Error with Opset 11 caused by F.Interpolate/nn.Upsampling...2d. See https://github.com/pytorch/pytorch/issues/30681

PyTorch model export to ONNX fails when using PyTorch 1.3.1 or nightly and ONNX 1.5.0. Failure is caused by all upsample operations: 

- `nn.UpsamplingBilinear2d(scale_factor=2)`
- `nn.UpsamplingNearest2d(scale_factor=2)`
- `F.interpolate(x, scale_factor=2)`


Error message:
```bash
torch version 1.4.0.dev20191127
onnx version 1.5.0
torch.Size([1, 3, 256, 256]) torch.Size([1, 3, 512, 512])
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/iD/upsample_error_reproduce.py", line 28, in <module>
    onnx.checker.check_model(oml)
  File "/Users/glennjocher/opt/anaconda3/envs/pytorch_nightly/lib/python3.7/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node (Resize_23) has input size 4 not in range [min=2, max=2].

==> Context: Bad node spec: input: "input" input: "20" input: "20" input: "23" output: "24" name: "Resize_23" op_type: "Resize" attribute { name: "coordinate_transformation_mode" s: "asymmetric" type: STRING } attribute { name: "cubic_coeff_a" f: -0.75 type: FLOAT } attribute { name: "mode" s: "nearest" type: STRING } attribute { name: "nearest_mode" s: "floor" type: STRING }
```

## To Reproduce

```python
# conda install pytorch torchvision -c pytorch-nightly
# conda install -c conda-forge onnx
import torch
import torch.nn as nn
import torch.nn.functional as F
import onnx


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

    def forward(self, x):
        # m = nn.UpsamplingBilinear2d(scale_factor=2)  # fails
        # m = nn.UpsamplingNearest2d(scale_factor=2)  # fails
        x = F.interpolate(x, scale_factor=2)  # fails
        return x


print('torch version %s' % torch.__version__)
print('onnx version %s' % onnx.__version__)
img = torch.randn(1, 3, 256, 256)
tml = TestModel()
print(img.shape, tml(img).shape)
torch.onnx.export(tml, img, 'model.onnx', verbose=False, opset_version=11)

oml = onnx.load('model.onnx')  # onnx model
onnx.checker.check_model(oml)
```

**Comment by mattip** [comment]
@glenn-jocher The last reproducer seems to work on latest head (as of today). Could you confirm this is still problematic?

**Comment by glenn-jocher** [comment]
@mattip the code to reproduce now runs without error. Output is:
```python
/Users/glennjocher/opt/anaconda3/envs/env1/bin/python "/Users/glennjocher/Library/Application Support/JetBrains/PyCharmCE2020.1/scratches/onnx_export.py"
torch version 1.5.0
onnx version 1.6.0
torch.Size([1, 3, 256, 256]) torch.Size([1, 3, 512, 512])

Process finished with exit code 0
```

On a closely related note, the actual onnx export from pytorch upsample operator is a convoluted mess (as it has always been as far as I can recall). It's beyond me why one simple pytorch operation baloons into 20 (yes 20) different onnx operations. This is the exported model viewed with netron. What can we do about this?

<img width="744" alt="Screen Shot 2020-05-20 at 9 26 29 AM" src="https://user-images.githubusercontent.com/26833433/82471764-02187180-9a7c-11ea-84fe-753d0414afd2.png">

**Comment by rgommers** [comment]
@mattip I would suggest to check if there's a regression test for this (and if not, adding it), then closing this issue).

> On a closely related note, the actual onnx export from pytorch upsample operator is a convoluted mess (as it has always been as far as I can recall). It's beyond me why one simple pytorch operation baloons into 20 (yes 20) different onnx operations. This is the exported model viewed with netron. What can we do about this?

That doesn't look pretty indeed. Would you mind opening a separate issue for this @glenn-jocher?

**Comment by glenn-jocher** [comment]
@rgommers thanks for the reply! I have done as you said and opened a new issue for this at https://github.com/pytorch/pytorch/issues/6780.

**Comment by mattip** [comment]
Closed by gh-28324, the added test is [here](https://github.com/pytorch/pytorch/pull/28324/files#diff-a219985d0f3f048cfa9ad55fcfd2697cR574).
