### ISSUE TITLE
Can't backward through torch.lobpcg when using "largest" kwarg

### ISSUE THREAD

**Issue by yanghtr** [pytorch/pytorch#67827]
## To Reproduce

With `torch.lobpcg`  in pytorch 1.9.1 .
```
torch.manual_seed(0)
a = torch.randn((100, 100), requires_grad=True)
a = a + a.T
torch.lobpcg(a, largest=False)
```
It will cause an error:
```
---------------------------------------------------------------------------

      1 a = torch.randn((100, 100), requires_grad=True)
      2 a = a + a.T
----> 3 torch.lobpcg(a, largest=False)
      4

~/Software/miniconda3/envs/python38/lib/python3.8/site-packages/torch/_lobpcg.py in lobpcg(A, k, B, X, n, iK, niter, tol, largest, method, tracker, ortho_iparams, ortho_fparams, ortho_bparams)
    518             B_sym = (B + B.transpose(-2, -1)) / 2 if (B is not None) else None
    519
--> 520             return LOBPCGAutogradFunction.apply(
    521                 A_sym, k, B_sym, X, n, iK, niter, tol, largest,
    522                 method, tracker, ortho_iparams, ortho_fparams, ortho_bparams

TypeError: save_for_backward can only save variables, but argument 4 is of type bool
```

It seems that I can not use `bool` for `largest`

## Environment
PyTorch version: 1.9.1         
Is debug build: False                
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A
                   
OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.3     
Libc version: glibc-2.27  
                                                                 
Python version: 3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.17               
Is CUDA available: True                                                         
CUDA runtime version: 10.2.89

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @walterddr @IvanYashchuk @xwang233

**Comment by soulitzer** [comment]
We should just save directly on `ctx` instead of using `ctx.save_for_backward`
