### ISSUE TITLE
DataLoader w/ memory pinning doesn't allow returning custom dict objects from custom data collator

### ISSUE THREAD

**Issue by eladsegal** [pytorch/pytorch#67831]
## 🐛 Bug

When using a DataLoader with memory pinning and a custom collator, it is not possible to get back objects that are subclassing a dictionary (`dict`, `MutableMapping`).

## To Reproduce

```
from torch.utils.data import DataLoader

class CustomDictClass(dict):
    def get_something(self):
        return "something"

dataset = [{"values": [0, 1, 2]}, {"values": [2, 3, 1]}]

def collate_fn(batch):
    return CustomDictClass({key: [elem[key] for elem in batch] for key in batch[0].keys()})

dataloader = DataLoader(
    dataset,
    pin_memory=True,
    collate_fn=collate_fn,
)

for batch in dataloader:
    print(batch)
    print(type(batch))
    print(batch.get_something())

```
The output is
```
{'values': [[0, 1, 2]]}
<class 'dict'>
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    print(batch.get_something())
AttributeError: 'dict' object has no attribute 'get_something'
```

## Expected behavior
The DataLoader should not cast down the custom dictionary object to just a dictionary.

When changing `pin_memory` to `False`, the correct output is received:
```
{'values': [[0, 1, 2]]}
<class '__main__.CustomDictClass'>
something
{'values': [[2, 3, 1]]}
<class '__main__.CustomDictClass'>
something
```

## Environment

- PyTorch version: 1.10.0+cu111
- Is debug build: False
- CUDA used to build PyTorch: 11.1
- ROCM used to build PyTorch: N/A

- OS: Ubuntu 18.04.5 LTS (x86_64)
- GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- Clang version: Could not collect
- CMake version: Could not collect
- Libc version: glibc-2.27

- Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
- Python platform: Linux-5.4.0-66-generic-x86_64-with-glibc2.17
- Is CUDA available: True
- CUDA runtime version: 11.2.142
- GPU models and configuration: 8 NVIDIA GeForce RTX 3090
- Nvidia driver version: 465.19.01

## Additional context

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Thanks for letting us know. We need to do the same thing to `Mapping` and `Sequence` as the `tuple` subclasses in `pin_memory`
https://github.com/pytorch/pytorch/blob/f6a4c80a5acf7454e90814449c4d6f4b73f7fad9/torch/utils/data/_utils/pin_memory.py#L53-L58

**Comment by ejguan** [comment]
Closing this Issue as the corresponding PR has landed,
