### ISSUE TITLE
[ONNX] Broken url for ONNX Runtime custom ops

### ISSUE THREAD

**Issue by jcwchen** [pytorch/pytorch#67849]
## 📚 Documentation

The previous link for [ONNX Runtime custom ops](https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md) from this [section](https://pytorch.org/docs/stable/onnx.html#custom-operators) is broken. IIUC, this should be the updated link:
https://onnxruntime.ai/docs/reference/operators/add-custom-op.html.

cc @brianjo @mruberry

**Comment by soulitzer** [comment]
Thanks for the report! We would accept a PR to fix this.

**Comment by fatcat-z** [comment]
Close this issue since the PR #67944 has been linked.
