### ISSUE TITLE
CUDNN 8.3.0 static library names have changed

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#67905]
## 🐛 Bug

In CUDNN 8.3.0, the static library has been split up in to multiple paths.

See: https://docs.nvidia.com/deeplearning/cudnn/release-notes/rel_8.html#rel-830

This needs to be changed to add all the static files if the version is >= 8.3.0.

It's possibly a bit more complicated in that *_v8.a would only be included if the V8 API is used.

cc @malfet @seemethere @csarofeen @ptrblck @xwang233 @ngimel

**Comment by ptrblck** [comment]
Thanks for creating the issue!

@malfet for the binary builds, we should either repackage these libs or as @xsacha suggested link them separately.

> It's possibly a bit more complicated in that *_v8.a would only be included if the V8 API is used.

Assuming you are referring to the v8 frontend API, then that should not be the case, as cuDNN8 is still used through the legacy v7 API.

**Comment by malfet** [comment]
@atalman to validate that issue has been resolved and close

**Comment by atalman** [comment]
Test python file:

import torch
y=torch.randn([3,5]).cuda()
print(y)
print(torch.backends.cudnn.version())

create and activate new environment using conda create/ conda activate

 Manywheels Windows:

 torch-1.12.0.dev20220221+cu115-cp310-cp310-win_amd64.whl                                                                                       
 torch-1.12.0.dev20220221+cu115-cp39-cp39-win_amd64.whl 
 torch-1.12.0.dev20220221+cu115-cp38-cp38-win_amd64.whl 
 torch-1.12.0.dev20220221+cu115-cp37-cp37-win_amd64.whl 

(env2) atalman@EC2AMAZ-IIQMR6I C:\Users\atalman\vim\vim82>python testc.py                                                                       
C:\Users\atalman\vim\vim82\testc.py:2: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ..\torch\csrc\
utils\tensor_numpy.cpp:68.)                                                                                                                     
  y=torch.randn([3,5]).cuda()                                                                                                                   
tensor([[-0.2648, -0.3199,  0.2563,  1.9191, -0.3408],                                                                                          
        [ 0.6953, -1.0059, -1.1185, -0.0272, -0.4818],                                                                                          
        [ 0.6630,  2.1202,  1.5892,  0.1650, -1.4987]], device='cuda:0')                                                                        
8302      

Linux :
- Requirement libcublas

torch-1.12.0.dev20220221+cu115-cp310-cp310-linux_x86_64.whl
torch-1.12.0.dev20220221+cu115-cp37-cp37m-linux_x86_64.whl
torch-1.12.0.dev20220221+cu115-cp38-cp38-linux_x86_64.whl
torch-1.12.0.dev20220221+cu115-cp39-cp39-linux_x86_64.whl

(env3) [ec2-user@ip-10-0-4-36 bin]$ python testc.py
tensor([[-0.2030,  0.3080,  0.5082,  0.0151, -0.1881],
        [ 0.0168, -0.8440,  1.2614, -0.6903,  0.4114],
        [ 0.0245, -1.2455, -0.7242,  0.0036,  0.6075]], device='cuda:0')
8302

**Comment by atalman** [comment]
Conda Linux :
conda install -c conda-forge -c pytorch-nightly pytorch=1.12.0.dev20220218=py3.9_cuda11.5_cudnn8.3.2_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.10_cuda11.5_cudnn8.3.2_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.8_cuda11.5_cudnn8.3.2_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.7_cuda11.5_cudnn8.3.2_0

Conda Windows
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220207=py3.10_cud
a11.5_cudnn8_0                        <- Need to fix this                      
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.8_cuda
11.5_cudnn8_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.7_cuda
11.5_cudnn8_0

**Comment by atalman** [comment]
libtorch  Linux

libtorch-cxx11-abi-static-with-deps-1.12.0.dev20220221%2Bcu115.zip
libtorch-cuda11_5-shared-with-deps-cxx11-abi-build

root@0d434f8c5f3b:/tmp1# g++ /builder/test_example_code/check-torch-cuda.cpp -I/tmp1/libtorch/include -I/tmp1/libtorch/include/torch/csrc/api/include -D_GLIBCXX_USE_CXX11_ABI=1 -std=gnu++14 -L/tmp1/libtorch/lib -Wl,-R/tmp1/libtorch/lib -Wl,--no-as-needed -ltorch -ltorch_cpu -ltorch_cuda -lc10 -o check-torch-cuda
root@0d434f8c5f3b:/tmp1# .check-torch-coda
bash: .check-torch-coda: command not found
root@0d434f8c5f3b:/tmp1# ./check-torch-cuda
Checking that CUDA archs are setup correctly
Checking that magma is available
Checking that CuDNN is available
CuDNN VERSION 8302root@0d434f8c5f3b:/tmp1# 


Modified CPP file /builder/test_example_code/check-torch-cuda.cpp 

```
#include <torch/torch.h>
#include <ATen/detail/CUDAHooksInterface.h>

int main(int argc, const char* argv[]) {
    std::cout << "Checking that CUDA archs are setup correctly" << std::endl;
    TORCH_CHECK(torch::rand({ 3, 5 }, torch::Device(torch::kCUDA)).defined(), "CUDA archs are not setup correctly");

    // These have to run after CUDA is initialized

    std::cout << "Checking that magma is available" << std::endl;
    TORCH_CHECK(torch::hasMAGMA(), "MAGMA is not available");

    std::cout << "Checking that CuDNN is available" << std::endl;
    TORCH_CHECK(torch::cuda::cudnn_is_available(), "CuDNN is not available");
    std::cout << "CuDNN VERSION " << at::detail::getCUDAHooks().versionCuDNN();
    return 0;
}
```

**Comment by atalman** [comment]
Memory footprint for small test above with cudnn 8.3
/home/ec2-user/miniconda3/envs/env1/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:181: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
testc.py:3: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:68.)
  y=torch.randn([3,5]).cuda()
tensor([[-0.1470, -0.4100,  2.5248, -0.2200, -1.2033],
        [ 0.0288, -0.0764, -1.0174, -0.8250,  1.9304],
        [ 1.7640, -0.9227, -0.3114, -1.7778,  1.3020]], device='cuda:0')
8302
Partition of a set of 186309 objects. Total size = 24513211 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  58492  31  6719105  27   6719105  27 str
     1  40214  22  2863752  12   9582857  39 tuple
     2  12088   6  2141823   9  11724680  48 types.CodeType
     3  23419  13  1744189   7  13468869  55 bytes
     4     46   0  1700160   7  15169029  62 dict of torch.tensortype
     5   1786   1  1671832   7  16840861  69 type
     6  10263   6  1395768   6  18236629  74 function
     7   3127   2  1092328   4  19328957  79 dict (no owner)
     8    613   0   911544   4  20240501  83 dict of module
     9   1786   1   831536   3  21072037  86 dict of type

**Comment by atalman** [comment]
Memory footprint for small test above with cudnn 8.2
env1) [ec2-user@ip-10-0-4-192 bin]$ python testc.py
/home/ec2-user/miniconda3/envs/env1/lib/python3.8/site-packages/torch/_masked/__init__.py:223: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
/home/ec2-user/miniconda3/envs/env1/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:179: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
tensor([[ 0.8191,  0.8754,  1.4302, -0.7658, -0.4782],
        [ 0.4633,  1.3721, -2.0296, -0.4108, -0.8973],
        [-1.3372, -1.8231, -0.0467,  1.1395,  0.4453]], device='cuda:0')
8200
Partition of a set of 186377 objects. Total size = 24201935 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  58945  32  6743679  28   6743679  28 str
     1  40061  21  2854544  12   9598223  40 tuple
     2  12019   6  2129311   9  11727534  48 types.CodeType
     3  23275  12  1737451   7  13464985  56 bytes
     4   1770   1  1656104   7  15121089  62 type
     5     38   0  1404480   6  16525569  68 dict of torch.tensortype
     6  10213   5  1388968   6  17914537  74 function
     7   3077   2  1074032   4  18988569  78 dict (no owner)
     8    622   0   915136   4  19903705  82 dict of module
     9   1770   1   826704   3  20730409  86 dict of type
<430 more rows. Type e.g. '_.more' to view.>

**Comment by atalman** [comment]
Created a followup story [here](https://github.com/pytorch/pytorch/issues/73355)
Closing this one.
