### ISSUE TITLE
Dataloader----Why When multiple threads read data, only one thread is activated?

### ISSUE THREAD

**Issue by liuicheng123** [pytorch/pytorch#67906]
## ❓ Main Questions 
  Dataloader----When multiple threads read data, only one thread is activated. if i set num_worker=8, only one thread is highly activated, but others seem not to work. so the process of dataloader becomes very slow.

![image](https://user-images.githubusercontent.com/36021763/140502551-896b7265-ee98-4583-acc9-249d8ff9454f.png)
how can i copy with it ?
thanks!
(torch 1.9.0)

## torch 1.8.0
when i work with torch 1.8.0, if i  set 
```
torch.set_num_threads(num_workers) 
```
if i  set  num_workers>3, the process will breakdown directly. but if i set 0<num_workers<3, dataloader becomes very good. it can activate all threads as the same number of what i set. for exsample, if i set torch.set_num_threads(3) ,3 threads will be highly activated and occupided 100%.
i hope i can activate all threads in torch1.9.0 like .

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Hi,
We use github issues only for bugs or feature requests.
Please use the forum to ask questions:  https://discuss.pytorch.org/

Please also look at the doc before ask questions. `num_workers` refers to number of processes in DataLoader. `set_num_threads` refers to the threads used by pytorch ops.
