### ISSUE TITLE
`test_softmax_64bit_indexing` requires >20GB CPU memory

### ISSUE THREAD

**Issue by crcrpar** [pytorch/pytorch#67910]
The test https://github.com/pytorch/pytorch/blob/2f68878a055d7f1064dded1afac05bb2cb11548f/test/test_nn.py#L15186-L15203 fails as follows unless CPU memory is sufficiently.

```console
$ pytest test/test_nn.py -k "softmax and 64bit and cuda" -v
========================================================================================================================================================================================================== test session starts ===========================================================================================================================================================================================================
platform linux -- Python 3.8.11, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /opt/conda/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/opt/pytorch/pytorch/.hypothesis/examples')
rootdir: /opt/pytorch/pytorch, configfile: pytest.ini
plugins: hypothesis-4.50.8
collected 3504 items / 3502 deselected / 2 selected

test/test_nn.py::TestNNDeviceTypeCUDA::test_softmax_64bit_indexing_cuda_float16 Killed
r
```

# Environment

- PyTorch version: https://github.com/pytorch/pytorch/commit/04fe438
- GPU: RTX 3090
- CPU memory: 
```
# python -c 'import psutil; print(psutil.virtual_memory().available)'
32308322304
```

# Expected behavior
Either of following is fine to me.

- Skip the test if CPU memory isn't enough.
    - Add another `largeTensorTest`, e.g. `largeTensorTest("40GB", device="cpu")`
- Run the test by dividing the CPU computation, e.g.
```python
for x_ in x.split(len(x) // 4):
    with torch.no_grad(): xx = x_.cpu().requires_grad_()
    yy = F.log_softmax(x_.float())
    ...
```

cc @albanD @mruberry @jbschlosser @walterddr @ptrblck @eqy

**Comment by albanD** [comment]
> Run the test by dividing the CPU computation, e.g.

That won't work as this test is explicitly checking that such big inputs (beyond 32bit index size) work fine.

> Skip the test if CPU memory isn't enough.

That sounds like a good solution.

**Comment by crcrpar** [comment]
Thank you for the comment. 67922 has the test case skipped if there's not enough CPU memory.

**Comment by crcrpar** [comment]
let me close this as #67922 was merged.
