### ISSUE TITLE
Unexpected lack of error when using nn.Linear and cuda

### ISSUE THREAD

**Issue by oguiza** [pytorch/pytorch#67923]
## 🐛 Bug

When using cuda, I can use a linear layer regardless the input tensor size. The same operation causes the expected issue when using cpu.

## To Reproduce
I'm using Pytorch 1.9.0+cu111 in Colab. 
I've created a super simple (gist)[https://colab.research.google.com/gist/oguiza/d7e17d7c157f7a87f689303eb0c7acde/scratchpad.ipynb]

```bash
import torch
import torch.nn as nn
t = torch.rand(2,5)
nn.Linear(2,2)(t).shape
```
causes an expected error: "RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x5 and 2x2)"
However, when doing: 
```bash
t = torch.rand(2,5, device='cuda')
nn.Linear(2,2, device='cuda')(t).shape
```
output = torch.Size([2, 2])

## Expected behavior
I'd expect to get the same error when using cuda as when using cpu.

**Comment by soulitzer** [comment]
I should have been fixed on 1.10, so I will close for now. See #67839.
