### ISSUE TITLE
1.9.1 Docker image is not available

### ISSUE THREAD

**Issue by abitrolly** [pytorch/pytorch#67966]
## Current Status
ongoing

https://hub.docker.com/r/pytorch/pytorch/tags is missing 1.9.1 release.

## User impact

They install latest image (because it is more secure) and then downgrade PyTorch manually.

## Root cause

No idea. Build scripts probably failed to upload on minor release. Although I haven't found the scripts.

## Mitigation

Release new version.

## Prevention/followups

 Add automation for minor releases to be uploaded to Docker Hub.

**Comment by malfet** [comment]
Removed `ci:sev` label as it does not affect PyTorch continuous integration system in any way

**Comment by seemethere** [comment]
Pushing the following:
```
❯ docker push pytorch/pytorch:1.9.1-cuda11.1-cudnn8-devel  
❯ docker push pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime
```

**Comment by seemethere** [comment]
Going to close this since the images have been pushed, will create a follow up issue to create automation for this

**Comment by abitrolly** [comment]
@seemethere thanks. Are there any reasons to push images with CUDA 11.1 instead of the latest 11.5? https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/
