### ISSUE TITLE
how to set the quantized data type in QAT

### ISSUE THREAD

**Issue by mathmax12** [pytorch/pytorch#67965]
When I use the qat and extract the intermedia layer's output I find it's quint8
![MicrosoftTeams-image](https://user-images.githubusercontent.com/32367611/140634280-ce018cf8-2d53-4ee1-98b3-97cf44f9e54f.png)
.
This datatype will be the input to the next layer I think.
But the weights are qint8 type. multiple a qint8 with quin8. Does this make sense?

Currently I use the default way to do the qat prepration:
`model_new.qconfig = torch.quantization.get_default_qat_qconfig('fbgemm')`

It seems the observer controls the data type. is there a way to set the data type and do QAT preparation?

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
Hi @mathmax12 , we are trying to make sure that all questions are asked in https://discuss.pytorch.org/c/quantization/17, and github issues are used more for bug reports and feature requests.  Would you mind asking your question in https://discuss.pytorch.org/c/quantization/17 instead?
