### ISSUE TITLE
Pytorch doesn't use last GB of GPU memory

### ISSUE THREAD

**Issue by tom-huntington** [pytorch/pytorch#67971]
> RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 6.00 GiB total capacity; 4.88 GiB already allocated; 0 bytes free; 4.96 GiB reserved in total by PyTorch)

Minimal reproducible example:
```
import torch

mylist = []
for _ in range(1000000):
    mylist.append(torch.rand(10000, device="cuda"))
```

This happens on both WSL2 and windows.

Someone else had a similar issue:
https://github.com/pytorch/pytorch/issues/35901#issuecomment-797785225

Could I get some guidance on this issue? (I would buy a 3090 if I didn't have to pay scalpers prices, so try to get my 6GB gpu to work for now) 

1) Is this because the other GB is being reserved by other programs (I was unable to switch to integrated graphics). 
2) Is this because PyTorch is inaccurately reporting the memory usage and it's really using the full 6GB? Windows GPU usage stats seems to suggest this.
3) Is this just a bug in pytorch?

cc @ngimel

**Comment by ngimel** [comment]
This is memory used by cuda context on the device, you can check it by running `torch.cuda.list_gpu_processes()` after allocating a small cuda tensor

**Comment by tom-huntington** [comment]
Good to know!

**Comment by JGameCreation** [comment]
Is there any way to get around this? My laptop GPU only has 2GB VRAM so not being able to use the last GB is quite critical. I think this didn't happen on earlier versions of PyTorch?
