### ISSUE TITLE
Why instance norm doesn't propagate channels last suggest memory format?

### ISSUE THREAD

**Issue by SeedKunY** [pytorch/pytorch#67976]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @VitalyFedyunin @jamesr66a

**Comment by SeedKunY** [comment]
I I found that the code segmentation of instance_norm (aten/src/ATen/native/Normalization.cpp) as below:
```
  auto input_reshaped = input.contiguous().view(shape);
  auto out = at::batch_norm(input_reshaped, weight_, bias_, running_mean_, running_var_,
                            use_input_stats, momentum, eps, cudnn_enabled);
```
                            
It seems that instance norm reuse the bach_norm code impl, however, instance_norm would convert the input to contiguous memory format which would break channels last suggestion memory format propagation. Is it wrong here?

**Comment by ngimel** [comment]
Closing in favor of #72341
