### ISSUE TITLE
[ONNX] "If" and "Loop" should not be special cases in ONNX export.

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#6797]
https://github.com/pytorch/pytorch/pull/6608#discussion_r182312792

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ezyang** [comment]
special case still exists at torch/csrc/jit/serialization/export.cpp

**Comment by garymm** [comment]
The special casing is still there:
https://github.com/pytorch/pytorch/blob/988ef190e3df0b48ef59dcf8007258ed79bb7946/torch/csrc/jit/serialization/export.cpp#L520

However I don't see what the problem is. @jamesr66a could you please explain in detail what change in the code this issue refers to?

**Comment by garymm** [comment]
I don't really know what this issue is tracking, so closing it. Feel free to re-open with clarifications.
