### ISSUE TITLE
How can I get a Model Comparison Chart?

### ISSUE THREAD

**Issue by Le0v1n** [pytorch/pytorch#67988]
A comparison chart like Keras:

![image](https://user-images.githubusercontent.com/67271439/140710882-cebb3f5f-8495-4917-ba50-52ae46d19c59.png)

So does PyTorch have such a comparison chart, and how can I find it?

I appreciate it that you can reply me!

**Comment by H-Huang** [comment]
Check out the models in the officially supported PyTorch library for computer vision, torchvision (https://pytorch.org/vision/stable/models.html#classification). There is a chart of accuracies for each model.

You can determine you can determine size/params/depth yourself by going through the `model.parameters()` yourself. Or utilize a 3rd party library like torchinfo (https://github.com/TylerYep/torchinfo). You can also calculate inference step by using a pretrained model and timing it yourself.

**Comment by Le0v1n** [comment]
@H-Huang 

Thanks for ur reply!
