### ISSUE TITLE
Low CPU utilization on ImageNet example

### ISSUE THREAD

**Issue by nadavbh12** [pytorch/pytorch#680]
I'm getting very low utilization on my CPUs on the ImageNet sample code using AlexNet.
So it took me 2 days to reach epoch 5 using two Titans.
```main.py -a alexnet --lr 0.01 ../../datasets/imagenet2012 --workers=10
=> creating model 'alexnet'
Epoch: [0][0/5005]	Time 48.842 (48.842)	Data 45.054 (45.054)	Loss 6.9073 (6.9073)	Prec@1 0.000 (0.000)	Prec@5 0.000 (0.000)
Epoch: [0][10/5005]	Time 22.424 (7.498)	Data 22.372 (7.070)	Loss 6.9065 (6.9074)	Prec@1 0.000 (0.142)	Prec@5 1.172 (0.533)
Epoch: [0][20/5005]	Time 10.452 (5.893)	Data 10.404 (5.632)	Loss 6.9075 (6.9076)	Prec@1 0.391 (0.149)	Prec@5 1.562 (0.446)
```
I see that only 2 or 3 out of my 12 cores are working.

Ubuntu 14.04, Cuda 8.0, python 2.7.12, CPU i7-5930K.
Installed using Conda. Then re-installed from source.
Both exhibit same problem.

**Comment by fmassa** [comment]
It seems that most of the time is spent loading data from the disk, and not running the network.
Could you try increasing the number of threads? Also, is your data in a fast local disk (ssd)?

**Comment by nadavbh12** [comment]
Increasing number of threads other than using the workers flag? results were the same when the flag was set to 4 and to 10.
Unfortunately, using a HDD.

**Comment by soumith** [comment]
if you are training alexnet and you have a hdd, you are bottlenecked by disk random read speed which is very low for hdds. your best bet is to preshuffle your dataset, resize it down to 256, make an lmdb out of it and read the lmdb image entries sequentially.

**Comment by nadavbh12** [comment]
The HDD isn't the issue.
I tried running the sample code on another computer with an HDD with only 1 worker and got much better results (average of 1 second rather than 10). So it looks like it isn't the number of threads either

**Comment by fmassa** [comment]
@nadavbh12 maybe the HDD that is in your current machine is abnormally slow?
You could perform [some disk read tests](http://askubuntu.com/questions/87035/how-to-check-hard-disk-performance) and compare the reading time on both machines. The numbers you sent in your first message clearly indicates that the data loading time is the issue. Maybe the disk was being used at the same time?

**Comment by apaszke** [comment]
Also, note that if HDD is a bottleneck, then increasing the number of workers will only make it worse - the disk is 100% busy, but they're competing for files scattered across it, so the reads get even more random and degrade the performance.

**Comment by nadavbh12** [comment]
@fmassa Ran the commands on both machines. The faulty machine had better performance.

@apaszke Didn't think of that. I reran the command using 1 worker on the same device and results are still bad:
```
Epoch: [0][0/5005]	Time 14.810 (14.810)	Data 9.469 (9.469)	Loss 6.9082 (6.9082)	Prec@1 0.000 (0.000)	Prec@5 0.391 (0.391)
Epoch: [0][10/5005]	Time 7.807 (7.782)	Data 7.756 (7.249)	Loss 6.9076 (6.9076)	Prec@1 0.000 (0.071)	Prec@5 0.000 (0.426)
```
