### ISSUE TITLE
error when loading model saved under newer version

### ISSUE THREAD

**Issue by Microos** [pytorch/pytorch#6801]
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: `PyTorch`
- OS: `Ubuntu 16.04`
- PyTorch version:  save using `0.4.0a0+67bbf58`, load using `0.2.0`
- How you installed PyTorch (conda, pip, source): `source`
- Python version: `python2.7`
- CUDA/cuDNN version: `8.0/6.1`
- GPU models and configuration: `TitanXp`
- GCC version (if compiling from source): `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609`
- CMake version:  `cmake version 3.5.1`
- Build command you used (if compiling from source): `python setup.py install --user`
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
- Error messages and/or stack traces of the bug
- Context around what you are trying to do

* Create a tensor and save it in `0.4.0a0+67bbf58`:
```Python
import torch as tc
print(tc.__version__) # 0.2.0
t = tc.ones(3)
tc.save(t, './t.pth')
```
* Load it in `0.2.0`:
```Python
import torch as tc
print(tc.__version__) # 0.4.0a0+67bbf58
t = tc.load('./t.pth') # error
```
* ERROR:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-5932959b71e5> in <module>()
----> 1 x = tc.load('./t.pth')

/home/ylxie/.local/lib/python2.7/site-packages/torch/serialization.pyc in load(f, map_location, pickle_module)
    229         f = open(f, 'rb')
    230     try:
--> 231         return _load(f, map_location, pickle_module)
    232     finally:
    233         if new_fd:

/home/ylxie/.local/lib/python2.7/site-packages/torch/serialization.pyc in _load(f, map_location, pickle_module)
    377     unpickler = pickle_module.Unpickler(f)
    378     unpickler.persistent_load = persistent_load
--> 379     result = unpickler.load()
    380 
    381     deserialized_storage_keys = pickle_module.load(f)

AttributeError: 'module' object has no attribute '_rebuild_tensor_v2'
```

How could I solve this? this is an abstract version of my issue,  the `t` is actually a `state_dict`. Is there any way I can specify a saving protocol for the convenience of loading models at an older version.

**Comment by SsnL** [comment]
loading model is backward compatible but not forward compatible.

**Comment by SsnL** [comment]
relevant previous issue: https://github.com/pytorch/pytorch/issues/5729

**Comment by SsnL** [comment]
Btw, 0.2 is really old. We recommend updating.

**Comment by Microos** [comment]
@SsnL Sure it is. I will try to transfer everything. Thanks.

**Comment by Hzzone** [comment]
I do not agree with what you said, as so many famous models are trained with previous versions. It is too expensive for us to train model at the newest versions.
