### ISSUE TITLE
1D convolution is broken for mkldnn tensors

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#68034]
## 🐛 Bug

1D convolution is broken for mkldnn tensors and a badly-worded error is thrown for this case.

## To Reproduce
```python
import torch

input = torch.randn(2, 3, 10).to_mkldnn()
weight = torch.randn(3, 3, 3).to_mkldnn()
bias = torch.randn(3).to_mkldnn()
output = torch.nn.functional.conv1d(input, weight, bias)
```
```
RuntimeError: opaque tensors do not have strides
```

## Expected behavior

Either the correct output is returned for mkldnn tensor inputs or a proper error is thrown indicating the lack of support for 1D convolution with mkldnn tensors.

## Additional Context
The problem occurs when trying to view 1D spatial input / weight as 2D. This is done for other backends (e.g. cuDNN) that don't support 1D spatial input directly. However, the [mkldnn convolution docs](https://oneapi-src.github.io/oneDNN/v1.0/dev_guide_convolution.html) indicate that 1D spatial inputs are supported directly, so it should be an easy fix to avoid the view for the mkldnn case.
https://github.com/pytorch/pytorch/blob/a1d733ae8ca4bbad8fa22a4a532b67915114ae93/aten/src/ATen/native/Convolution.cpp#L889-L897

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @walterddr @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by XiaobingSuper** [comment]
@jbschlosser, yes, for mkldnn tensor, it should avoid the view, I find you are refactoring convolution code,  I can fix it after you code merged.
