### ISSUE TITLE
undefined reference to `at::native::DispatchStub` on ppc64le

### ISSUE THREAD

**Issue by cdeepali** [pytorch/pytorch#68057]
## 🐛 Bug

Seeing the following error while compiling PyTorch v1.10 on ppc64le:

```
undefined reference to `at::native::DispatchStub<void (*)(c10::ScalarType, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::ArrayRef<long>, void const*, c10::ArrayRef<long>, void*), at::native::fft_fill_with_conjugate_symmetry_stub>::VSX'
collect2: error: ld returned 1 exit status
```

Details - https://github.com/pytorch/pytorch/issues/66867

cc @malfet @seemethere

**Comment by cdeepali** [comment]
@quickwritereader, @malfet, do you have any ideas how we can get this working for powerpc?  

I can try any suggestions that come along.

**Comment by quickwritereader** [comment]
you need to dispatch missing ones as well
https://github.com/pytorch/pytorch/blob/147de8243b97f5c6e21a5bd948a4be981dea1b9e/aten/src/ATen/native/mkl/SpectralOps.cpp#L151

**Comment by quickwritereader** [comment]
REGISTER_VSX_DISPATCH(fft_fill_with_conjugate_symmetry_stub, &_fft_fill_with_conjugate_symmetry_cpu_)

**Comment by cdeepali** [comment]
Thanks @quickwritereader, I will try this.

**Comment by cdeepali** [comment]
This fix worked like a charm. Thanks @quickwritereader. Would you be raising a PR for this?

**Comment by quickwritereader** [comment]
@cdeepali it would be better if someone from pytorch team solves the issue. this way it will be merged very soon

**Comment by cdeepali** [comment]
Sure @quickwritereader. I have raised PR - https://github.com/pytorch/pytorch/pull/68914. 

@malfet, @quickwritereader, could you please review it.
