### ISSUE TITLE
[docs] `nn.Transformer` is not possible to be used to implement BERT

### ISSUE THREAD

**Issue by ayaka14732** [pytorch/pytorch#68053]
## 📚 Documentation

In the [`nn.Transformer`](https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html) documentation:

> Users can build the [BERT](https://arxiv.org/abs/1810.04805) model with corresponding parameters.

If I understand correctly, BERT only uses the transformer encoder, while `nn.Transformer` includes both encoder and decoder. Therefore, users cannot build the BERT model with `nn.Transformer`.

There is a [related discussion](https://discuss.pytorch.org/t/how-to-implement-bert-using-torch-nn-transformer/90981) on PyTorch Forum:

> Even if I set `num_decoder_layers=0` while initializing it, the `forward()` call mandatorily requires the argument `tgt` for the transformer’s decoder, but BERT has no decoder.

cc @svekars @holly1238 @jbschlosser @bhosmer @cpuhrsch

**Comment by jbschlosser** [comment]
Thankfully, the separate `nn.TransformerEncoder` module exists. We'd accept a PR removing this line from the `nn.Transformer` docs to be more correct.
