### ISSUE TITLE
Distributions for Symmetric Matrices.

### ISSUE THREAD

**Issue by nonconvexopt** [pytorch/pytorch#68050]
## 🚀 Feature
Add [Wishart distribution](https://en.wikipedia.org/wiki/Wishart_distribution) and [Inverse Wishart distribution](https://en.wikipedia.org/wiki/Inverse-Wishart_distribution#Conjugate_distribution) to 'torch.distributions'.

## Motivation
Wishart and Inverse Wishart distributions are key component to model the distribution of symmetric positive definite matrices.
It can help to support wide variety of probabilistic inference method with PyTorch.

## Pitch
May I send PR of the implementation of Wishart and inverse Wishart distribution codes?

Current implementation of Wishart distribution: https://github.com/nonconvexopt/pytorch/blob/wishart_distribution/torch/distributions/wishart.py

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by nonconvexopt** [comment]
[#29044](https://github.com/pytorch/pytorch/issues/29044)
FYI, It seems that the issue was already discussed. It is my bad.
However, according to the thread, it was been pending for 2+ years.
May I solve the issue?

**Comment by fritzo** [comment]
Sure, @nonconvexopt, feel free to implement this.
