### ISSUE TITLE
conda install does not seem to have files in torch/fx/experimental/fx2trt/passes

### ISSUE THREAD

**Issue by nrsatish** [pytorch/pytorch#68059]
## 🐛 Bug

Installing conda packages for 1.10 or nightly does not give files in torch/fx/experimental/fx2trt/passes

## To Reproduce

1. conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch-nightly
2. ls ~/anaconda3/pkgs/pytorch-1.11.0.dev20211108-py3.8_cuda11.3_cudnn8.2.0_0/lib/python3.8/site-packages/torch/fx/experimental/fx2trt/ => no passes directory

## Expected behavior

Expected to see a passes directory

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.11.0.dev20211108
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.8.2 (default, Mar 26 2020, 15:53:00)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.6.13-0_fbk17_zion_5815_gc01d8dbd2635-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.4.120
GPU models and configuration:
GPU 0: NVIDIA A100-PG509-200
GPU 1: NVIDIA A100-PG509-200
GPU 2: NVIDIA A100-PG509-200
GPU 3: NVIDIA A100-PG509-200
GPU 4: NVIDIA A100-PG509-200
GPU 5: NVIDIA A100-PG509-200
GPU 6: NVIDIA A100-PG509-200
GPU 7: NVIDIA A100-PG509-200

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.11.0.dev20211108
[pip3] torchaudio==0.11.0.dev20211108
[pip3] torchvision==0.12.0.dev20211108
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.0            py38h42c9631_2
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.20.1           py38h93e21f0_0
[conda] numpy-base                1.20.1           py38h7d8b39e_0
[conda] pytorch                   1.11.0.dev20211108 py3.8_cuda11.3_cudnn8.2.0_0    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                0.11.0.dev20211108      py38_cu113    pytorch-nightly
[conda] torchvision               0.12.0.dev20211108      py38_cu113    pytorch-nightly

## Additional context

cc @malfet @seemethere

**Comment by malfet** [comment]
Same folder is missing from both whl and conda packages, but my strong hunch that is has something to do with the fact, that files in that folder are not all referenced from the parent folder.

**Comment by yinghai** [comment]
@malfet any more findings, what should we do to proceed?

**Comment by malfet** [comment]
Sorry for the delay, answer is much simpler: only proper Python packages are included i the wheel file, and each package must have `__init__.py` at the top level

One can quickly check that package is missing from the list by running
```
$ python3 -c "from setuptools import find_packages; print([x for x in find_packages(exclude=('tools','tools.*')) if 'torch.fx' in x])"
['torch.fx', 'torch.fx.experimental', 'torch.fx.passes', 'torch.fx.experimental.unification', 'torch.fx.experimental.fx_acc', 'torch.fx.experimental.fx2trt', 'torch.fx.experimental.unification.multipledispatch', 'torch.fx.experimental.fx2trt.tools', 'torch.fx.experimental.fx2trt.converters']
```
But is added there after empty `__init__.py` is added to the folder
