### ISSUE TITLE
Add the `maximize` flag to all optimizers

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#68052]
See https://github.com/pytorch/pytorch/issues/46480 for the original discussion.

All optimizers should get the same treatment:
- [x] SGD https://github.com/pytorch/pytorch/pull/67847
- [x] Adam
- [x] AdamW
- [x] Adadelta
- [x] Adagrad
- [x] Adamax
- [x] ASGD
- [x] RMSprop
- [x] Rprop
- [x] SparseAdam
- [ ] LBFGS

cc @vincentqb @jbschlosser @albanD

**Comment by OliverFM** [comment]
Which one is the next highest priority? Adam?
I would like to try do another at some point in the next week or two

**Comment by albanD** [comment]
Adam sounds like a good candidate. I re-ordered the list above roughly to be in order.

**Comment by wukong1992** [comment]
Hey!
I am new comer, and want to contributing to torch. And which optim else need to be done，i will spend some time for the PR。

**Comment by OliverFM** [comment]
> Hey! I am new comer, and want to contributing to torch. And which optim else need to be done，i will spend some time for the PR。

Hey @wukong1992! Welcome!
I am also new here, however I implemented the fix for SGD, and opened #68164 for Adam.

In my opinion, the best first step is to setup the torch repo locally and run tests. After that, you'd probably want to pick one of the optimizers and mention here that you are working on that implementation.
You can look at the existing implementation in SGD for reference on how this ought to be done and `test_sgd` in `torch/test_optim.py` for an example of the testing that you'd need to do.

I hope this helps!

**Comment by wukong1992** [comment]
> > Hey! I am new comer, and want to contributing to torch. And which optim else need to be done，i will spend some time for the PR。
> 
> Hey @wukong1992! Welcome! I am also new here, however I implemented the fix for SGD, and opened #68164 for Adam.
> 
> In my opinion, the best first step is to setup the torch repo locally and run tests. After that, you'd probably want to pick one of the optimizers and mention here that you are working on that implementation. You can look at the existing implementation in SGD for reference on how this ought to be done and `test_sgd` in `torch/test_optim.py` for an example of the testing that you'd need to do.
> 
> I hope this helps!

OK！Thank you so much！

**Comment by OliverFM** [comment]
Adam is done, #68164, I may start work on AdamW this week.

**Comment by albanD** [comment]
Thanks!

**Comment by Adnios** [comment]
oops. @OliverFM Have you started AdamW? I just finished AdamW.

**Comment by OliverFM** [comment]
> oops. @OliverFM Have you started AdamW? I just finished AdamW(#70146).

Fortunately not :)
I'll pick up `ASGD` instead!

**Comment by zaxtax** [comment]
I'll handle the rest of these!

**Comment by albanD** [comment]
We will not do lbfgs as part of this issue as it is more complex than others.
