### ISSUE TITLE
"test_nadam" is flaky on ROCm

### ISSUE THREAD

**Issue by NivekT** [pytorch/pytorch#68079]
## 🐛 Bug

`test_nadam` within `test_optim` (pytorch-linux-bionic-rocm4.3.1-py3.6-test2) seems to be flaky. It occasionally fails on the master branch. I only started noticing the issue today (Nov 9th, 2021), so I'm unsure how long this has been happening for.

Here is the error message:
```
14:56:03 ======================================================================
14:56:03 FAIL [0.455s]: test_nadam (__main__.TestOptim)
14:56:03 ----------------------------------------------------------------------
14:56:03 Traceback (most recent call last):
14:56:03   File "test_optim.py", line 630, in test_nadam
14:56:03     lambda weight, bias: optimizer(
14:56:03   File "test_optim.py", line 231, in _test_basic_cases
14:56:03     make_two_arg_constructor(constructor, maximize),
14:56:03   File "test_optim.py", line 209, in _test_state_dict
14:56:03     self.assertEqual(bias, bias_cuda)
14:56:03   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1928, in assertEqual
14:56:03     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
14:56:03 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=1.3e-06 and atol=1e-05, found 1 element(s) (out of 10) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 1.9073486328125e-05 (-1.0852036476135254 vs. -1.0851845741271973), which occurred at index 1.
```

Here are two runs that have failed within the past few hours today:

[Run 1](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9175//console)
[Run 2](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9212//console)

Looking through the recent PRs, it might be related to #67847 but I am not confident that it is. Please ignore if they are unrelated.

## To Reproduce

Run the test using on Circle CI and sometimes the test doesn't pass.

## Expected behavior

The test should consistently pass or fail.

## Environment

Circle CI

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @vincentqb @albanD @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jeffdaily** [comment]
We just caught this, as well, and I commented in the same PR as indicated above.

https://github.com/pytorch/pytorch/pull/67847#issuecomment-964505576

**Comment by NivekT** [comment]
Note that the test has been disabled for now by issue #68171

**Comment by albanD** [comment]
Test is re-enabled and passing so should be fine
