### ISSUE TITLE
TorchBench V1 performance signal on 20211106

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#68086]
TorchBench V1 has detected a performance signal on 20211106.

Base PyTorch version: 1.11.0.dev20211105+cu102
Affected PyTorch version: 1.11.0.dev20211106+cu102

The following TorchBench tests are affected (positive means longer latency and worse perf):

- test_eval[LearningToPaint-cuda-jit]: +15.35136%
- test_eval[mnasnet1_0-cuda-jit]: -96.00715%
- test_eval[mobilenet_v3_large-cuda-jit]: -50.97254%
- test_eval[resnet18-cuda-jit]: +10.27948%
- test_eval[resnet50-cuda-jit]: +13.03570%
- test_eval[shufflenet_v2_x1_0-cuda-jit]: +42.71758%
- test_eval[squeezenet1_1-cuda-jit]: +57.48286%
- test_eval[timm_regnet-cuda-jit]: +16.62421%
- test_eval[timm_resnest-cuda-jit]: +14.95034%
- test_eval[timm_vovnet-cuda-jit]: +9.83278%
- test_eval[vgg16-cuda-jit]: +15.94762%

Bisection points to the root cause commit https://github.com/pytorch/pytorch/commit/f6a4c80a5a

cc @VitalyFedyunin @ngimel @csarofeen @ptrblck @xwang233

**Comment by xwang233** [comment]
Thanks for the report. Does the positive number mean better or worse performance?

**Comment by xuzhao9** [comment]
> Thanks for the report. Does the positive number mean better or worse performance?
> 
> #65594

Thanks for the quick response! Positive number means worse performance (increased latency of the test)

**Comment by xuzhao9** [comment]
Result of testing PR #68087 
```
test_eval[LearningToPaint-cuda-jit]                                            0.00290604                                      0.00250814  -15.864294%*
test_eval[mnasnet1_0-cuda-jit]                                                 0.0335896                                       0.0939914   +64.263099%*
test_eval[mobilenet_v3_large-cuda-jit]                                         0.0285932                                       0.0334735   +14.579480%*
test_eval[shufflenet_v2_x1_0-cuda-jit]                                         0.0267638                                       0.0158646   -68.701662%*
test_eval[squeezenet1_1-cuda-jit]                                              0.0205551                                       0.0111315   -84.656317%*
test_eval[timm_regnet-cuda-jit]                                                0.0845917                                       0.055429    -52.612793%*
test_eval[vgg16-cuda-jit]                                                      0.0331581                                       0.0270035   -22.792180%*
```

**Comment by xwang233** [comment]
Conv-Bias-Relu fusion was **disable** on cuda 10.2 + cudnn 7.6.5 due to a unit test failure. See https://github.com/pytorch/pytorch/pull/65594#issuecomment-948989177. 

The failure was only observed on CI machine of M60 + cudnn 7.6.5. I've tested that on P100, V100 on cudnn 7.6.5 and there was no problem, also no problem on cuda 11.x + cudnn 8.x on all platforms.

I support having the fusion **enabled** on all available cuda + cudnn versions, if we can somehow work around/skip the test on M60 + cudnn 7.6.5 in the CI.

cc @ngimel

**Comment by malfet** [comment]
@xwang233 does it mean that Conv-Bias-Relu  is faster but returns less accurate results on M60?

**Comment by xwang233** [comment]
Generally speaking, conv-bias-relu should be faster than and have at least the same accuracy as the non-fused version.

The unit test failure in https://github.com/pytorch/pytorch/pull/65594#issuecomment-948989177 was a `CUDNN_STATUS_NOT_SUPPORTED` error on M60, e.g. https://github.com/pytorch/pytorch/runs/3877542278?check_suite_focus=true

**Comment by malfet** [comment]
> Generally speaking, conv-bias-relu should be faster than and have at least the same accuracy as the non-fused version.
> 
> The unit test failure in [#65594 (comment)](https://github.com/pytorch/pytorch/pull/65594#issuecomment-948989177) was a `CUDNN_STATUS_NOT_SUPPORTED` error on M60, e.g. https://github.com/pytorch/pytorch/runs/3877542278?check_suite_focus=true

@xwang233 sorry, I'm having a hard time connecting statement in the first and 2nd sentence together. Does it mean that cudnn-7.6.5 have a bug on just M60? Or in general, this codepath should be avoided for CuDnn-7.6.5 on all GPUs? Or for a particular shapes of convolution kernels?

**Comment by xwang233** [comment]
> Does it mean that cudnn-7.6.5 have a bug on just M60?

That's right, on M60 only. We've only detected failures on particular shapes on M60 only. Cudnn 7.6.5 works fine on all other devices.

**Comment by malfet** [comment]
Hmm, then perhaps instead of compile time check it can be replaced with a runtime one if CUDNN version is 7?

**Comment by xuzhao9** [comment]
> > Does it mean that cudnn-7.6.5 have a bug on just M60?
> 
> That's right, on M60 only. We've only detected failures on particular shapes on M60 only. Cudnn 7.6.5 works fine on all other devices.

Can we add a runtime check to only disable fusion on M60?

**Comment by eellison** [comment]
@ngimel thoughts on fix here ?

**Comment by ngimel** [comment]
@xuzhao9 does reenabling fusion fix the perf regression? 
Yes, we can replace with the runtime check for cudnn version and hardware capability.

**Comment by eellison** [comment]
Not sure what's going on with 
test_eval[mnasnet1_0-cuda-jit]: -96.00715%
test_eval[mobilenet_v3_large-cuda-jit]: -50.97254%
though..

**Comment by malfet** [comment]
@xuzhao9 for comparison, can you please share changes in the same tests for PyTorch+cu111 or PyTorch+cu113 builds?

**Comment by xuzhao9** [comment]
> @xuzhao9 for comparison, can you please share changes in the same tests for PyTorch+cu111 or PyTorch+cu113 builds?

Since #68087 reverts only when `CUDNN < 8000` and all perf numbers are back, I believe cu111/cu113 are not affected.

**Comment by xuzhao9** [comment]
> Not sure what's going on with test_eval[mnasnet1_0-cuda-jit]: -96.00715% test_eval[mobilenet_v3_large-cuda-jit]: -50.97254% though..

I am able to reproduce the test_eval[mnasnet1_0-cuda-jit] result on the CI machine. Here are the profiling results:
When fusion is enabled (slower):
![image](https://user-images.githubusercontent.com/502017/142132790-56422d9e-37b5-4ca3-9f60-360835a349ec.png)

When fusion is disabled (faster):
![image](https://user-images.githubusercontent.com/502017/142132850-4bf87c03-deab-44b2-b428-7367efdaa345.png)

Here is the full trace:
[traces.tar.gz](https://github.com/pytorch/pytorch/files/7551610/traces.tar.gz)

Hope this can help understand why mnasnet1_0 is slower when fusion is enabled. We are also trying to look into it.

**Comment by xuzhao9** [comment]
> Not sure what's going on with test_eval[mnasnet1_0-cuda-jit]: -96.00715% test_eval[mobilenet_v3_large-cuda-jit]: -50.97254% though..

I took a deeper look into this. First, I rule out the factor of torchvision (because both are torchvision models).
Second, I run profile on mnasnet1_0:

When disable fusion (faster, ~4ms):
![image](https://user-images.githubusercontent.com/502017/142134958-ef93780c-3fb2-4549-bea4-1fb6b1051e5b.png)

When enable fusion (slower, ~100ms):
![image](https://user-images.githubusercontent.com/502017/142134930-3852a10c-749d-46e7-aee8-c99d77b92e1b.png)

Here is the full traces (include both cuda and cpu+cuda traces): [traces.tar.gz](https://github.com/pytorch/pytorch/files/7551703/traces.tar.gz)

**Comment by xuzhao9** [comment]
Here is how test_eval[mnasnet1_0-cuda-jit] result profiles look like on CUDA 11.3:

PR base:
![image](https://user-images.githubusercontent.com/502017/142300252-83593a86-58e2-492e-82dd-cbbe8c161748.png)

PR tip:
![image](https://user-images.githubusercontent.com/502017/142300286-e94ccd49-be08-4b3e-9894-3c6264d81991.png)

**Comment by xuzhao9** [comment]
I rerun mnasnet1_0 in eager mode on CUDA 11.3, CUDNN 8.2.0 and TorchBench V2:
With fusion (default):
![image](https://user-images.githubusercontent.com/502017/142323539-70123095-a2bf-4225-967f-5676d28e8734.png)

Latency ~36.7 ms

Without fusion:
![image](https://user-images.githubusercontent.com/502017/142323769-a87fcf7b-8452-407e-9bb9-73495ed580a6.png)

Latency ~37.080 ms

**Comment by xuzhao9** [comment]
The issue is now resolved. JIT compiler now speeds up the test, not regressing it.
