### ISSUE TITLE
[rfc] Target Determinator

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#68081]
This is a followup to #63781. The approach there has a few problems, namely that it was focused too narrowly on avoiding tests. While this might be good in the future (i.e. some codebases want to run a limited subset of tests and are OK with the increased revert risk), we need a more fundamental approach to dynamically controlling workflows that run on PRs.

## Goal

Decrease time to signal (TTS) on PRs by running fewer jobs. Note that this is different from #63781, that RFC suggested doing less work within jobs (by limiting the tests that run, this is also how the old/dead TD we used to have worked).

## Implementation

Both approaches use CIFlow to determine the jobs to run.

### in-repo

We put the logic to decide if subsequent jobs should run in a file (say `tools/determinator/main.py`) that [prints out a true/false](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idoutputs) at the end. Then we can skip other jobs based on this, similar to how we use `needs: [ciflow_should_run]` in workflows today. This is nice since the triggering logic isn't very complicated and can be defined by Python that lives in the repo. However, any changes to determination would require users to rebase (i.e. if we edit rules or there is a bug)

### probot

We can put the logic to inspect PRs into probot and use that to decide what labels to add to PRs. We'd probably have to extends CIFlow to have a concept of exclusive labels (for a case like doc-only PRs, we want to not run the default jobs and only run a doc build + preview workflow). Probot could then add labels based on PR content similar to how it does now and we edit the workflows to conditionally execute based on these labels.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Closing as a different Target Determinator is now an active project.
