### ISSUE TITLE
Do pytorch 1.10.0 possibly support cuda 10.1?

### ISSUE THREAD

**Issue by llv22** [pytorch/pytorch#68145]
## ❓ Questions and Help

Just wonder if we can downgrade cuda version for pytorch 1.10.0 from 10.2 to 10.1.
Though it seems just a little upgrade for cuda version, there is no official cudnn built for 10.2 on macOS system. That's really weird...
My question is that

in pytorch 1.10.0, do we have certain features closely coupled with cuda 10.2? if no, perhaps such degradation is possible. could you help clarify? 

- [Discussion Forum](https://discuss.pytorch.org/)

cc @ngimel

**Comment by ngimel** [comment]
You can try compiling it from source, but officially it's not supported. Official mac binaries don't support cuda at all, so I'm not sure what the question is here.

**Comment by llv22** [comment]
@ngimel thanks a lot, I modified official torch 1.10.0 and made it working for macOS10.13.6 with cuda10.1. github repository is here https://github.com/llv22/pytorch-macOS-cuda/tree/v1.10.0-built.
