### ISSUE TITLE
Why there isn't a `set_to_none` option for `zero_grad()` in libtorch?

### ISSUE THREAD

**Issue by bitosky** [pytorch/pytorch#68167]
When I call `zero_grad()` of a module, the weight tensors will have their all-zero gradient tensors. In python version pytorch, I can set `set_to_none` to `True`, then the gradients will be set to `None`.  It's convenient for saving memory in some cases. 

But I found there isn't a `set_to_none` option for `zero_grad()` in the C++ version pytorch. Why it isn't the same as the python version API? And how can I do the same thing (set gradients to null value) in C++?

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr

**Comment by albanD** [comment]
There is no reason for that, we would accept a PR adding this!
