### ISSUE TITLE
DISABLED test_Conv2d_naive_groups_cuda_float16 (__main__.TestNNDeviceTypeCUDA)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68172]
Platforms: rocm

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/9624//console

12:34:17 ======================================================================
12:34:17 FAIL [4.075s]: test_Conv2d_naive_groups_cuda_float16 (__main__.TestNNDeviceTypeCUDA)
12:34:17 ----------------------------------------------------------------------
12:34:17 Traceback (most recent call last):
12:34:17   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1447, in wrapper
12:34:17     method(*args, **kwargs)
12:34:17   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1447, in wrapper
12:34:17     method(*args, **kwargs)
12:34:17   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
12:34:17     result = test(self, **param_kwargs)
12:34:17   File "test_nn.py", line 16621, in test_Conv2d_naive_groups
12:34:17     self.assertEqual(output, torch.cat([output1, output2], 1))
12:34:17   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1928, in assertEqual
12:34:17     super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
12:34:17 AssertionError: False is not true : Tensors failed to compare as equal!With rtol=0.001 and atol=1e-05, found 34 element(s) (out of 128) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.0009765625 (-0.51953125 vs. -0.5205078125), which occurred at index (0, 3, 0, 2).
12:34:17 
12:34:17 ----------------------------------------------------------------------

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by ngimel** [comment]
Tolerance issue, should be reenabled with higher tolerance
