### ISSUE TITLE
Out of gpu memory error when consolidate_state_dict

### ISSUE THREAD

**Issue by Kyeongpil** [pytorch/pytorch#68181]
## ❓ Questions and Help

Hi, I'm trying to train the large-size model using DDP and ZeroRedundancyOptimizer on A100 GPUs.
I successfully progressed a few training steps including the forward, backward, and optimizer steps.

However, I failed to save the optimizer's state_dict.
Especially, I run optimizer.consolidate_state_dict(), it throws out-of-gpu-memory error.

Does the consolidate_state_dict function need additional GPU memory?
Then, how to save the optimizer's state_dict avoiding out-of-memory error?
Is there any solution other than to put the model's parameters onto CPU memory to reduce the preoccupied GPU memory?

**Comment by maxwellzh** [comment]
AFAIK, invoking this function collects all the parameter groups of optimizer on to a specific device. So it's reasonable that the memory consumption increases.
I also wonder if we could move this to CPU for reducing the memory footprint of GPU.

**Comment by vinnamkim** [comment]
I took a quick looking at the code.

https://github.com/pytorch/pytorch/blob/2d75703c6a5f53a3df956cf689a0a60a29ef6a06/torch/distributed/optim/zero_redundancy_optimizer.py#L513-L531

There would be an additional memory consumption on a device when receiving a broadcasted state. However, it is copied from the device to CPU right after.

**Comment by Kyeongpil** [comment]
@vinnamkim Yes, I took a look at these codes. I think this function broadcasts all states and then saves them on the CPU device.
Is it impossible to save the optimizer's state_dict directly on CPU memory without consuming GPU memory?

**Comment by Kyeongpil** [comment]
@maxwellzh I guest the GPU memory will be reduced if the model parameters, which are located on GPU memory, are moved onto CPU memory.

**Comment by vinnamkim** [comment]
> @vinnamkim Yes, I took a look at these codes. I think this function broadcasts all states and then saves them on the CPU device. Is it impossible to save the optimizer's state_dict directly on CPU memory without consuming GPU memory?

The most promising solution would be directly to customize `consolidate_state_dict()` to broadcast only at CPU level as follows.

1. Copy local device `state_dict` to local CPU `state_dict`.
2. Broadcast local CPU `state_dict` (not broadcasting local device `state_dict` <- current code).

**Comment by saketh-are** [comment]
Thanks @maxwellzh and @vinnamkim for the helpful discussion here.

On a separate note, we use github issues only for bug reports or feature requests. It's preferrable to use the forum to ask questions: https://discuss.pytorch.org/
