### ISSUE TITLE
DISABLED test_ddp_profiling_torch_profiler (__main__.TestDistBackendWithSpawn)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#68189]
Platforms: rocm

See https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=rocm.*distributed 
For example, see https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4890//console
Seems to be caused by https://github.com/pytorch/pytorch/pull/67901

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by janeyx99** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/68222
