### ISSUE TITLE
"Debug adapter process has terminated unexpectedly" - CANNOT debug cuda?

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#682]
Hi, all:

It looks I failed to debug pytorch cuda ???
My ENV:
OS: Ubuntu 16.04
Python: Anaconda Python 3.5.2
IDE: VSCode 1.9.0

Whenever I tried to debug the example code MNIST at line 80:
```
if args.cuda:
            **data, target = data.cuda(), target.cuda()** // line 80
        data, target = Variable(data), Variable(target)
```

I met this Error:
**Debug adapter process has terminated unexpectedly**

Did anybody meet the same issue? Any possibility to debug pytorch cuda code?

Cheers
Pei

**Comment by apaszke** [comment]
Yeah, run it from the command line and paste the error with a stack trace here please.

I'm not familiar with that IDE and if regular Python binary can execute the program correctly, then I wouldn't consider that a PyTorch problem.

**Comment by soumith** [comment]
will reopen if confirmed that the regular python binary also has this issue.
