### ISSUE TITLE
[JIT][C++ Parser] Bug in processing ternary expressions

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#68221]
## 🐛 Bug 

I ran into the following bug when specifying shape functions in C++. Because we rely on the python ast parser generally, and then export ternary expressions as if statements, this doesn't come up very often. 

```
import torch

cu = torch.jit.CompilationUnit('''
    def foo(x: List[int]):
        return 1 if len(x) == 0 else x[0] if len(x) == 1 else x[1]
''')
print(cu.foo([]))
```
throws an exception

**Comment by etern** [comment]
I checked this bug, which is in the parsing phase.
It can be solved if we parse TernaryIf as right associative.
Should I make a PR to fix this ?

**Comment by eellison** [comment]
Hi @etern, a fix would be great thanks! haven't thought much if the right associative is the fix but that sounds right !

**Comment by etern** [comment]
The fix is one line of code, I've tested myself, it works as expected.

Should I add a test case for it, in file `test/cpp/api/jit.cpp` ?
