### ISSUE TITLE
Can we register forward hooks for functional calls?

### ISSUE THREAD

**Issue by shengchunnan** [pytorch/pytorch#68243]
As we know, we can register forward hooks for **`nn.Module`** instances. But there are functional operations like **`nn.functional.interpolate()`**,  or **`torch.cat()`**, or even an implicit callable like **`<built-in function add>`**  for element-wise summation of tensor_a and tensor_b like this:

```py
tensor_c = tensor_a + tensor_b  # There is a <built-in function add>  here
```
Can we use hooks for these functional calls?

**Comment by saketh-are** [comment]
Hi @shengchunnan, hooks can be registered on `nn.Module` objects, not on operators.

On a separate note, we use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
