### ISSUE TITLE
bug when loss backward, related to AdaptiveAvgPool1d

### ISSUE THREAD

**Issue by zw-xxx** [pytorch/pytorch#68248]
## 🐛 Bug

< Bug comes when loss backward, and it is related to AdaptiveAvgPool1d >

## To Reproduce

When I am training the deep-learning network, I get the following ` RuntimeError ` :
```
RuntimeError: shmem_size <= sharedMemPerBlock INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1603729128610/work/aten/src/ATen/native/cuda/AdaptiveAveragePooling.cu":669, please report a bug to PyTorch.
```
Note that I use quite a lot of ` nn.AdaptiveAvgPool1d ` in my network. 

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): ` conda ` command from official instructions
 - Build command you used (if compiling from source): ~
 - Python version: 3.6.0
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: A100 40G
 - Any other relevant information: ~

cc @ngimel

**Comment by eqy** [comment]
Would it be possible to narrow this down to a specific shape/workload?

**Comment by ptrblck** [comment]
@Wei-Zhuo could you post the input activation shape to this layer which is failing as well as the layer setup?
If possible, a minimal executable code snippet would be great to have for debugging.
Are you also seeing the issue using the latest stable release (`1.10.0`) or the nightly?

**Comment by ngimel** [comment]
It probably happens for a large input, the assert is like 
```
size_t shmem_size = (kernel_size_C * block_x * block_y * block_z + osizeH + osizeW) * sizeof(scalar_t) + 2 * isizeW * sizeof(int32_t);
              AT_ASSERT(shmem_size <= sharedMemPerBlock);
```
where sharedMemPerBlock is hardware limit obtained with cudaGetDeviceProperties.

**Comment by eqy** [comment]
This is a bit difficult for me to reproduce with a few sample large inputs, so a repro snippet/shape would be great.

**Comment by marcmk6** [comment]
[Here](https://github.com/pytorch/pytorch/issues/70701#issuecomment-1006996757) is a repro of the error.
I'm currently working with 2.1.0 and this problem still exists.

**Comment by eqy** [comment]
@marcmk6 Opened https://github.com/pytorch/pytorch/pull/115231, could you verify if it fixes your issue?

**Comment by eqy** [comment]
Closing as the PR has been merged and I have tested it on similar GPUs
