### ISSUE TITLE
FX graph mode quantization broken for torchvision MobileNetV3

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#68250]
## 🐛 Bug

FX graph mode quantization does not correctly quantize torchvision MobileNetV3.

Original report: https://discuss.pytorch.org/t/recreating-fx-graph-quantization-on-mobilenetv3-notimplementederror/136718

## To Reproduce

```
import torch
import torchvision                                                       
                                                                         
m = torchvision.models.mobilenet_v3_small()                              
qconfig_dict = {'': torch.quantization.get_default_qat_qconfig('fbgemm')}
mp = torch.quantization.quantize_fx.prepare_qat_fx(m, qconfig_dict)      
mp(torch.randn(1, 3, 224, 224))                                          
mq = torch.quantization.quantize_fx.convert_fx(mp)                       
res = mq(torch.randn(1, 3, 224, 224))                                    
```

error:

```
Traceback (most recent call last):
  File "/home/vasiliy/local/tmp/test.py", line 31, in <module>
    res = mq(torch.randn(1, 3, 224, 224))
  File "/data/users/vasiliy/pytorch/torch/fx/graph_module.py", line 630, in wrapped_call
    raise e.with_traceback(None)
NotImplementedError: Could not run 'aten::bernoulli_.float' with arguments from the 'QuantizedCPU' backend. This could be be
cause the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom
 build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolu
tions. 'aten::bernoulli_.float' is only available for these backends: [CPU, CUDA, Meta, BackendSelect, Python, Named, Conjug
ate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradML
C, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_
TYPE_ID, Autocast, Batched, VmapMode, Functionalize].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:18972 [kernel]
CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:27320 [kernel]
Meta: registered at aten/src/ATen/RegisterMeta.cpp:13383 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: fallthrough registered at ../aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: registered at ../torch/csrc/autograd/generated/ADInplaceOrViewType_1.cpp:2399 [kernel]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10165 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_3.cpp:11713 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1017 [backend fallback]
VmapMode: registered at ../aten/src/ATen/VmapModeRegistrations.cpp:37 [kernel]
Functionalize: registered at aten/src/ATen/RegisterFunctionalization_2.cpp:4121 [kernel]
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
yeah I remember seeing this before when I test torchvision models. Can we silently replace `Dropout` with `Identity` in quantization flow? or are you talking about providing a helper function for users to do that?

I think we can work around this in quantization flow, by checking the train/eval mode of the module and decide what to do based on that, similar to what we did for sigmoid etc. (FixedQParamOps)

**Comment by vkuzo** [comment]
For option 2, I was proposing replacing Dropout with Identity.  This seems consistent how `nn.BatchNorm2d` (which has different behaviors for train vs eval) gets replaced with `nnq.BatchNorm2d` (which ignores the train flag and assumes eval).

thoughts?

**Comment by jerryzh168** [comment]
discussed offline, I think we can define a nnq.Dropout, so that we may extend it in the future with train mode if needed

**Comment by vkuzo** [comment]
> discussed offline, I think we can define a nnq.Dropout, so that we may extend it in the future with train mode if needed

after thinking about this some more, can we revisit the above and consider replacing with identity for now, and only spend the eng time to set up quantized dropout later if it is actually needed?  The boilerplate for "quantized dropout" which will be the identity function is probably going to be ~0.5K LOC and a day or more of eng time, doesn't seem worth it since it's unclear if there is actually ever going to be quantized dropout logic.  I think identity replacement has a much better eng time to benefit ratio and will get us through the next couple of years.  I think a BC breaking change later if quantized dropout actually becomes a thing is fine.

cc @jerryzh168 , thoughts?

**Comment by jerryzh168** [comment]
just to be clear, quantized dropout would be something similar to https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/activation.py#L4 right, why would it take ~0.5LOC?

On the other hand I don't have a strong preference over one or another, just saying quantized dropout would be a more future proof approach. As you mentioned we probably won't have trainable quantized Dropout in a couple of years, if you prefer swapping in the quantization flow then I'm fine with that as well.

**Comment by vkuzo** [comment]
> why would it take ~0.5LOC?

the code for dropout function and module would be trivial, but there would be boilerplate for defining the swaps, testing, documentation, etc.  We can discuss offline if it's worth it, I feel like deferring that cost until later when quantized dropout is actually needed is reasonable.

**Comment by jerryzh168** [comment]
> > why would it take ~0.5LOC?
> 
> the code for dropout function and module would be trivial, but there would be boilerplate for defining the swaps, testing, documentation, etc. We can discuss offline if it's worth it, I feel like deferring that cost until later when quantized dropout is actually needed is reasonable.

Hi Vasiliy, sorry I forgot to mention that I'm assigning some of the tasks to Terry as his ramp up tasks. Looks like he has put up a PR, please let me know how you would like to proceed, I don't have a strong opinion on whether we implement this now or later I think.

**Comment by vkuzo** [comment]
this is fixed by https://github.com/pytorch/pytorch/pull/71043
