### ISSUE TITLE
expected dtype XXX but got dtype XXX

### ISSUE THREAD

**Issue by beginner401** [pytorch/pytorch#68321]
## To Reproduce
1. just make sure that the dtype of weights differs from that of input tensor
## Expected behavior
PyTorch may automatically cast one of the dtype to the other to make sure the dtypes stay the same.
## Environment
torch 1.8.1
## Addition
This bug may be widely known, however, to some extent, some adaptive operation can be carried out to make it easier to use.

**Comment by mrshenli** [comment]
Hey @beginner401, I believe this is intentional to prevent silent and unintentional type conversions. @albanD @gchanan, please correct me if I was wrong.

**Comment by beginner401** [comment]
Hi, @mrshenli thanks for your help! And maybe I can close this issue.
