### ISSUE TITLE
Quantization: torch._make_per_channel_quantized_tensor doesn't work well

### ISSUE THREAD

**Issue by Force1ess** [pytorch/pytorch#68322]
## To Reproduce

Here's how this bug produce

[bug.ipynb](https://drive.google.com/file/d/1mXDh5HU5Zro3RFaYNqoSrGt8gPcezAJa/view?usp=sharing)

I've installed the nightly version of torch

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by mrshenli** [comment]
Hey @Force1ess, could you please paste the error message in the issue body and also describe the platform, cuda version, etc. that are you using? Thanks!

**Comment by Force1ess** [comment]
Errorinfo:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Setting strides is possible only on uniformly quantized tensor
cudavision: 10.2 and cpu
platform: windows and linux

**Comment by HDCharles** [comment]
```
from torchvision import models
import torch
quant_model = models.quantization.resnet50(pretrained=True,quantize=True)
param = [*quant_model.state_dict().values()]

weight = param[0]
per_tensor =  torch._make_per_tensor_quantized_tensor(weight.int_repr(),weight.q_per_channel_scales()[0],weight.q_per_channel_zero_points()[0])
per_channel = torch._make_per_channel_quantized_tensor(weight.int_repr(),weight.q_per_channel_scales(),weight.q_per_channel_zero_points(),axis=0)

per_tensor[0][0][0][0] = 0.0061
print(per_tensor[0][0][0][0])
# Work Well

print(per_channel.int_repr()[0][0][0][0])
per_channel.int_repr()[0][0][0][0]=8
print(per_channel.int_repr()[0][0][0][0])
# Indirectly Assign doesn't work

per_channel[0][0][0][0]
# RuntimeError: Setting strides is possible only on uniformly quantized tensor
```

Its not intended that you can assign to the int_repr()

not sure about the stride error, will take a closer look

**Comment by z-a-f** [comment]
@Force1ess This doesn't really explain the problem. Could you post a minimum reproducible example with the error message. The notebook is not always helpful

**Comment by z-a-f** [comment]
I think strided convolutions don't support per channel quantization, I might be wrong though.

cc @jerryzh168 @dskhudia

**Comment by dskhudia** [comment]
@z-a-f Strided convolutions do support per-channel. The "stride" mentioned in RunTimeError is not convolution stride but standard pytorch tensor "stride". We somehow, I think, don't support changing tensor strides on per-channel quantized tensors.

**Comment by Force1ess** [comment]
Sorry, I forgot to close this issue.
Actually, this problem has been solved.
https://discuss.pytorch.org/t/how-to-change-a-quant-tensor/135106/11
This is how to do this.
I should change its int_repr not directly change this tensor

**Comment by dzdang** [comment]
For future readers: Slicing a per channel quantized tensor is enabled by https://github.com/pytorch/pytorch/pull/71269 but is limited to contiguous slices. See referenced PR for details
