### ISSUE TITLE
Spectral Normalization issue.

### ISSUE THREAD

**Issue by gorcurek** [pytorch/pytorch#68327]
## 🐛 Bug

I am working on a GAN network, and am making use of *spectral normalization*.
I ran into an error of the implementation when using **from torch.nn.utils.parametrizations import spectral_norm**.
However, everything went fine when using **from torch.nn.utils import spectral_norm**.

I am getting error saying:
**RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation**

Clearly, one of them is not working properly, and it would be really nice to fix this.

## To Reproduce

The below code snippet shows the error:

```
import torch
from torch import nn
from torch.nn.utils import spectral_norm as sn1
from torch.nn.utils.parametrizations import spectral_norm as sn2


def run_with_spectral(spectral):
    discriminator = spectral(nn.Linear(10, 1))
    optim = torch.optim.Adam(discriminator.parameters())
    loss = nn.L1Loss()

    X = torch.ones(4, 10)
    real = torch.ones(4, 1)
    fake = torch.zeros(4, 1)

    optim.zero_grad()
    generated = torch.rand(4, 10)

    loss_real = loss(discriminator(X), real)
    loss_fake = loss(discriminator(generated), fake)

    l = loss_real + loss_fake

    l.backward()
    optim.step()


if __name__ == "__main__":
    run_with_spectral(sn1)
    run_with_spectral(sn2)
```

## Expected behavior

If I am doing something wrong when gradients are being calculated, and then I would expect both of those implementations to pick this up. If I am doing everything correctly, one of them needs fixing either way.

## Environment
 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Arch Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): -
 - Python version: 3.8.8
 - CUDA/cuDNN version: -
 - GPU models and configuration: -
 - Any other relevant information: -

**Comment by Lezcano** [comment]
This was fixed in master, and I believe it made it into 1.10. Please update your PyTorch version and the snippet will work.
