### ISSUE TITLE
Autograd mechanics documentation (grad_fn._saved_self, .save_result)

### ISSUE THREAD

**Issue by cocoaaa** [pytorch/pytorch#68362]
## 📚 Documentation

Hi, I'm going through the documentation on [Autograd's mechanics](https://pytorch.org/docs/stable/notes/autograd.html), and am encountering the following errors in the `Saved tensors` section:
```python
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self))  # AttributeError: 'PowBackward0' object has no attribute '_saved_self'
print(x is y.grad_fn._saved_self)  # Similar AttributeError
```
Same AttributeError occurs with `exp()` function. 

There is also a typo in the paragraph that follows these examples (in the same section):
"Under the hood, to prevent reference cycles, PyTorch has packed the tensor upon saving and unpacked it into a different tensor for reading. Here, the tensor you get from accessing y.grad_fn._saved_result is a different tensor object than x (but they still share the same storage)."

I believe, "x" should be "y".

Could you help me understand if these errors are due to an update in the `autograd` library?
Thanks!

cc @brianjo @mruberry @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by Lezcano** [comment]
Which version of PyTorch are you using? This snippet works for me both en 1.10 and in master.

On the second point, that is indeed an errata. We would accept a PR fixing this one :)

**Comment by Lezcano** [comment]
On a side note, if you're interested in these things and you want to delve deeper, there's this post that explains how things are implemented in the C++ side that may or may not be useful: https://dev-discuss.pytorch.org/t/how-to-read-the-autograd-codebase/383
