### ISSUE TITLE
[PyTorch] add .to on Storage

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#6836]
cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang

**Comment by zou3519** [comment]
I remember storage was made untyped (or was it StorageImpl?) in #33950, so is this still relevant?

**Comment by ezyang** [comment]
The Python storage bindings still distinguish dtype for bc compat, we should have another issue for making these untyped as well.

**Comment by kurtamohler** [comment]
I added a `_to()` method to storage classes in #62030. I didn't know if it should be made public or not, so I erred on the side of caution. I can rename it to `to()` (and probably add some tests)

**Comment by ezyang** [comment]
I think what Kurt did here is sufficient.
