### ISSUE TITLE
[Pytorch] Weird behavior of LBFGS optim.

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#6838]
I am trying to use LBFGS to optimize acquisition function of a Bayesian optimization process. During the training, I observed that LBFGS made some weird behavior at some points.

Here is the notebook to observe the issue:
https://gist.github.com/fehiepsi/bda728ca40b7cb46208eb355b312bacd

At the 4-to-last steps, despite that the previous x_grad is small, the new unconstrained_x has made a big move. So I think that this is a problem of LBFGS.

FYI, I used the lastest pytorch version in 0.4 branch.

**Comment by magnumw** [comment]
Hey @fehiepsi, 

are you running your code with double precision? I've experienced similar issues running my code, and they got fixed once I casted my tensor and model to doubles.

**Comment by fehiepsi** [comment]
Hi @magnumw , I didn't run my code in double precision. Yeah, casting to double might help but it is better to see what is the underlying reason for this problem. It seems like Pytorch's devs don't pay attention to this issue. When having time, I will try to solve it.

**Comment by apaszke** [comment]
@fehiepsi it's not that we don't pay attention. We have a limited amount of resources (most notably developer time), and there's just a ton of other work we have to do. Debugging numerically heavy, complex routines like LBFGS is hard and takes a lot of time, and we didn't get to it just yet. We'd greatly appreciate any help with that!

**Comment by fehiepsi** [comment]
Yup, understood it. Maybe "pay attention" is not a suitable phrase but I meant what you said. :)

**Comment by fehiepsi** [comment]
I checked the LBFGS implementation and saw that it is consistent with the algorithm in the text. In addition, I cannot replicate the old behavior of the above notebook (due to using the new version of pytorch/pyro). In the future, if I met this problem again, I will open the issue.
