### ISSUE TITLE
[subgraph_rewriter] A small bug in subgraph_rewriter

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#68392]
## 🐛 Bug
Looks like https://github.com/pytorch/pytorch/blob/master/torch/fx/subgraph_rewriter.py#L273 should be 
```
if lookup[n].op == "placeholder":
```
instead of
```
if n.op == "placeholder":
```
Is that correct?

cc @ezyang @SherlockNoMad

**Comment by SherlockNoMad** [comment]
Not an issue anymore. Fixed in https://github.com/pytorch/pytorch/pull/82090
