### ISSUE TITLE
[feature request] install pytorch and caffe2 with a unified command

### ISSUE THREAD

**Issue by poppingcode** [pytorch/pytorch#6840]
when i download the pytorch and install it ,Then，Can I install both pytorch and Caffe and caffe2 together?

**Comment by ezyang** [comment]
@pjh5 is working on a unified install for both, it's coming!

**Comment by poppingcode** [comment]
ok

**Comment by pjh5** [comment]
In the meantime, the separate installation instructions for Caffe2 and pytorch are both valid, and they can both be installed without any conflicts. Installing both Caffe and Caffe2 can cause problems depending on how you install; if you want both of these then you should install them into separate virtual environments or into separate conda environments.

**Comment by gabriellap** [comment]
@pjh5 Any update on this unified installation? I have been unable to install pytorch and Caffe2 in the same environment on Ubuntu 16.04.

**Comment by pjh5** [comment]
"python setup.py install" on the current master will install the integrated Pytorch-Caffe2. You should probably thoroughly uninstall previous Caffe2 and Pytorch installations before reinstalling.
