### ISSUE TITLE
Previous Version out of date

### ISSUE THREAD

**Issue by david-waterworth** [pytorch/pytorch#68406]
## 📚 Documentation

The `previous versions` doesn't seem to be getting updated anymore as new versions are released. The current release is 1.10 (https://pytorch.org/get-started/locally/) but the latest `previous version` is still 1.8.0 (https://pytorch.org/get-started/previous-versions/)

At one point this was being updated with minor updates (i.e. 1.7.1 appears on previous releases but 1.8.1 doesn't nor does 1.9.x)

Given that many 3rd party libraries have minimum and/or maximum torch version dependencies it would be nice if this could be maintained.

cc @ezyang @seemethere @malfet @brianjo @mruberry

**Comment by NeoKish** [comment]
I made a pull request#894 in the pull requests of pytorch.github.io providing a partial fix to the issue
