### ISSUE TITLE
Why do I get "CUDA error: illegal memory access" instead of "Cuda error: out of memory"? (at maxpool2d step)

### ISSUE THREAD

**Issue by purplesword** [pytorch/pytorch#68418]
## Problem: 

I have a task whose input tensor size varies. At extreme case I got batches like [200, 1, 64, 3000] (N, C, H, W). When I put it through a simple feature extraction net (see below) the memory usage is undoubtedly high. 

So it is fully understandable I got "Cuda error: out of memory" from a bunch of machines like RTX 5000.  

The odd thing is, when I tried it on a RTX 8000, it became "CUDA error: an illegal memory access was encountered". I can reduce the batch size to get rid of the error. But why? Why do I get "illegal memory access" instead of "out of memory"? What's the difference of the 2 errors? 

net: 
```python
nn.Sequential(
        nn.Conv2d(1, 64, 3, 1, 1), nn.ReLU(True),nn.MaxPool2d(2, 2),
        nn.Conv2d(64, 128, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d(2, 2), 
        nn.Conv2d(128, 256, 3, 1, 1), nn.ReLU(True),
        nn.Conv2d(256, 256, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
        nn.Conv2d(256, 512, 3, 1, 1, bias=False), nn.BatchNorm2d(512), nn.ReLU(True), 
        nn.Conv2d(512, 512, 3, 1, 1, bias=False), nn.BatchNorm2d(512), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
        nn.Conv2d(512, 512, 2, 1, 0), nn.ReLU(True)
) 
```

## Environment 

PyTorch version: 1.8.2
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.2
[pip3] torchvision==0.9.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-include               2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.0            py39h42c9631_2  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] pytorch                   1.8.2           py3.9_cuda11.1_cudnn8.0.5_0    pytorch-lts
[conda] torchvision               0.9.2                py39_cu111    pytorch-lts

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel

**Comment by ngimel** [comment]
Probably some bug. Can you provide a script that would reproduce the error?

**Comment by purplesword** [comment]
Hi, thank you for replying. Here is a small script I can stably reproduce the "illegal memory access" on my said machine with above env. 

```python 
import torch 
import traceback
from torch import nn

#torch.cuda.empty_cache()
#print(f"Allocated: {torch.cuda.memory_allocated()}, reserved: {torch.cuda.memory_reserved()}")

a = torch.randn(190, 1, 64, 2933)
a = a.cuda()

#print(f"Allocated: {torch.cuda.memory_allocated()}, reserved: {torch.cuda.memory_reserved()}")

net = nn.Sequential(
        nn.Conv2d(1, 64, 3, 1, 1), nn.ReLU(True),nn.MaxPool2d(2, 2),
        nn.Conv2d(64, 128, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d(2, 2), 
        nn.Conv2d(128, 256, 3, 1, 1), nn.ReLU(True),
        nn.Conv2d(256, 256, 3, 1, 1), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
        nn.Conv2d(256, 512, 3, 1, 1, bias=False), nn.BatchNorm2d(512), nn.ReLU(True), 
        nn.Conv2d(512, 512, 3, 1, 1, bias=False), nn.BatchNorm2d(512), nn.ReLU(True), nn.MaxPool2d((2, 1), (2, 1)),
        nn.Conv2d(512, 512, 2, 1, 0), nn.ReLU(True)
) 
net.cuda()

try:
    net(a)
except: 
    traceback.print_exc()  
``` 
Traceback: 
```

> python cudamem.py 
Traceback (most recent call last):
  File "/home/myuser/cudamem.py", line 29, in <module>
    net(a)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/pooling.py", line 162, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "/opt/conda/lib/python3.9/site-packages/torch/_jit_internal.py", line 365, in fn
    return if_false(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py", line 659, in _max_pool2d
    return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA error: an illegal memory access was encountered


```

**Comment by ngimel** [comment]
Can you run with environment variable CUDA_LAUNCH_BLOCKING=1?

**Comment by purplesword** [comment]
I have it set already and the result is as above. I also have following values in ENV. 
```
CUDA_LAUNCH_BLOCKING=1
MKL_NUM_THREADS=1
OMP_NUM_THREADS=1
OMP_THREAD_LIMIT=1   
MAX_NUM_OPENCV_THREADS=1
```

**Comment by ngimel** [comment]
Short repro 
```
inp = torch.randn(190,64,64, 2933, device="cuda")
pool = nn.MaxPool2d(2, 2)
out=pool(inp)
torch.cuda.synchronize()
```

**Comment by ngimel** [comment]
https://github.com/pytorch/pytorch/blob/4e21d77dbb86581ba79d8b8179fb61a4e153e2e3/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu#L59
`(n * channels + c) * height * width` overflows before it's upcast to `ptrdiff_t`. There are probably similar places in other kernels. 
cc @xwang233

**Comment by xwang233** [comment]
This is a similar issue as https://github.com/pytorch/pytorch/issues/52822. Will submit a fix soon.

**Comment by purplesword** [comment]
Hi! Any update on it? I see the PR is there and passed all the checks since quite a while. Could you merge it?
