### ISSUE TITLE
ParameterDict should implement `.get` and `.setdefault`

### ISSUE THREAD

**Issue by thomasahle** [pytorch/pytorch#68476]
## 🚀 Feature

`ParameterDict` implements most, but not all methods from `dict`. In particular it doesn't have:

    >>> set(dir({})) - set(dir(nn.ParameterDict()))
    {'__class_getitem__',
     '__ior__',
     '__or__',
     '__reversed__',
     '__ror__',
     'copy',
     'fromkeys',
     'get',
     'popitem',
     'setdefault'}

Arguably `copy`, `fromkeys` and `popitem` are not particularly useful, as well as the various `or` methods.

However `.get()` and `.setdefault()` can make code much nicer.

## Motivation

I'm implementing an optimizable optimizer with parameter specific moment and velocity.
The code looks something like this:

    def __init__(self):
        self.cache = nn.ParameterDict()
        ...
    def adjust(self, params):
        ...
        for name, param in params:
            m = self.cache.get('m', torch.zeros(param.shape))
            v = self.cache.get('v', torch.zeros(param.shape) + self.eps)
            ...

I can't define these parameter specific parameters in my `__init__`, since I only know the shape they need once the first optimization step has started.

## Pitch

The documentation writes "ParameterDict is an ordered dictionary".
It seems that as such it should implement the standard python dictionary methods.
In fact, it already implements nearly all of them, so why not those last two?

## Alternatives

I could write

    if 'm' not in self.cache:
            self.cache[name]['m'] = torch.zeros(param.shape)
    if 'v' not in self.cache 
            self.cache[name]['v'] = torch.zeros(param.shape) + self.eps
    m = self.cache[name]['m']
    v = self.cache[name]['v']

But it is 3 times as many lines of code, and any python developer would wonder "why doesn't this just use `.get` or `.default`?"

cc @albanD @mruberry @jbschlosser @walterddr

**Comment by albanD** [comment]
That is a great suggestion, we would definitely accept a PR adding get and setdefault that match the python dict API/behavior.

**Comment by thisisalbertliang** [comment]
Hi, my friends (@jfrucht25, @saphirasnow, @gramliu, @shawnchan2014) and I would love work on adding `.get()` and `.setdefault()` (and possibly all other unimplemented `dict` methods) to `ParameterDict`, if nobody else is working on it.

We aim to get a PR ready in the next 2 weeks.

**Comment by thomasahle** [comment]
I just ran into a similar problem that `ParameterList` doesn't implement `__delitem__` (and a few other list methods.) I can open a new issue for this if necessary?

**Comment by jbschlosser** [comment]
@thomasahle Sure, opening a new issue would be great :)
