### ISSUE TITLE
[c10d] ProcessGroupNCCL work inconsistent with ProcessGroupGloo

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#68478]
The `work.result()` of ProcessGroupNCCL and ProcessGroupGloo are inconsistent, for example, `all_gather(..).wait()` will return different values for these two process group, this is because in ProcessGroupNCCL, we flatten the output first, then result assigned based on the flattened output, instead of the original output. See https://github.com/pytorch/pytorch/blob/515d9fb2a99586e62cfb941cfc51e86e7d58c1f4/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1275

We need to fix ProcessGroupNCCL to attach the correct output

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Does this also affect futures-based callbacks, i.e. if the user gets a future to this work, will the result of the future be different btwn gloo/nccl?

**Comment by wanchaol** [comment]
> Does this also affect futures-based callbacks, i.e. if the user gets a future to this work, will the result of the future be different btwn gloo/nccl?

Yes I believe it will also affect it, as future will be marked as done using `outputs` of the work

**Comment by kwen2501** [comment]
I chatted with @wanchaol offline, and our short conclusion is that `ProcessGroupNCCL` is doing the right return.

The code referred to in this issue:
https://github.com/pytorch/pytorch/blob/515d9fb2a99586e62cfb941cfc51e86e7d58c1f4/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1275
is matching the output signature of `Work::result()` as declared in the parent class `ProcessGroup`:
https://github.com/pytorch/pytorch/blob/515d9fb2a99586e62cfb941cfc51e86e7d58c1f4/torch/csrc/distributed/c10d/ProcessGroup.hpp#L111
The `std::<vector>` is there for legacy multi-GPU-per-process support, while `at::Tensor` denotes a single tensor, whether it has the same size as the input tensor (in cases like all-reduce, reduce and broadcast), or a different size (in cases like all-gather and reduce_scatter). Per this definition, the `outputs_` of all-gather is expected to be in a "flattened" form.

**Comment by rohan-varma** [comment]
@kwen2501 sounds good! Based on this, is there still an inconsistency or can we close this issue out?
