### ISSUE TITLE
CI test clang-format failed to run, but shown as success

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#68480]
## 🐛 Bug

Link to example CI job https://github.com/pytorch/pytorch/runs/4230547278?check_suite_focus=true

Log of clang-format:

```
Downloading clang-format to /home/runner/work/pytorch/pytorch/.clang-format-bin

The downloaded binary is not what was expected!
Downloaded hash: 'e1c8b97b919541a99e0a355df5c3f9e8abebc64259dbee6f8c68e1ef90582856' vs expected 21ca53c291a88b53dac85751b7a0203ca610ac94b7adaff3c092cf30df4168f2
The binary has been deleted just to be safe
```

## Expected behavior

* clang-format hash to be updated.
* CI to catch this error instead of showing success.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
fixed by lintrunner
