### ISSUE TITLE
[question/pytorch] How to force a part of graph to backward on CPU

### ISSUE THREAD

**Issue by CDLuminate** [pytorch/pytorch#6848]
I'm trying to write a complex function, where I have to calculate the elements in a big matrix one by one. As far as I know performing an amount of such kind of 'one-element operation' is quite inefficient on GPU due to the hardware interruption latency underneath the cudaMemcpy call. Actual implementation proved that. The function uses torch.autograd, which means there is no manual backward method.

So, in my function, all the input cuda tensors are converted to cpu tensor first. The result tensors are converted back into cuda tensors before return. This makes the function a bit faster. However, the function is still slow in the backward stage, which happens on GPU.

My question is, can I force a function, or say a part of the computation graph, to be processed on CPU? Thanks in advamce.

**Comment by SsnL** [comment]
If the part during forward is on cpu, then it is on cpu during backward too.

Please post questions in discuss.pytorch.org. GitHub is for issue tracking.
