### ISSUE TITLE
backward not working properly in svd (pytorch-nightly)

### ISSUE THREAD

**Issue by NiccoloSacchi** [pytorch/pytorch#6849]
## Issue description

I am having problem in running the backward propagation with svd. In particular, it seems working when the first dimension of the matrix x (below) is greater than the second. But I get the following error 

> RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

if the first is smaller than the second.

## Code example

```
from torch.nn import Parameter
from torch import Tensor

dim1, dim2 = 3, 2 # working with these dimensions
dim1, dim2 = 2, 3 # not working with these dimensions
x = Parameter(Tensor(dim1, dim2))
_, _, V = x.svd(some=False)
V.mean().backward()
```

## System Info
PyTorch version: 2018.04.20
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[pip3] torch (2018.4.20)
[pip3] torchvision (0.2.0)
[conda] pytorch                   0.3.1           py35_cuda8.0.61_cudnn7.0.5_2    pytorch
[conda] pytorch-nightly           2018.04.20      py35_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] torchvision               0.2.0            py35heaa392f_1    pytorch

**Comment by SsnL** [comment]
Repro'ed on 0.4 branch. `some=True` works btw.

**Comment by apaszke** [comment]
It's a shorthand for "reproduced", which means that the bug still hasn't been fixed. Sorry, we'll try to get to it soon.
