### ISSUE TITLE
detach not working properly for stochastic variables

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#685]
I'm not able to reproduce a simple example for now, will try to make one later. But basically I'm facing this issue in my code:

`RuntimeError: differentiating stochastic functions requires providing a reward`

I have a variable `sentences`, and doing `sentences = sentences.detach()` does not solve the issue. However, `sentences = Variable(sentences.data)` solves it, which seems weird to me..

**Comment by apaszke** [comment]
Right, I'll fix that soon. Sorry.

**Comment by apaszke** [comment]
It's because right now `.detach()` doesn't remove the reference to the creating graph, even though it should.

**Comment by apaszke** [comment]
Fixed in #752.
