### ISSUE TITLE
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":300, please report a bug to PyTorch. unable to write to file </torch_85217_8371>

### ISSUE THREAD

**Issue by catqaq** [pytorch/pytorch#68501]
## To Reproduce

run a bert model based simcse traing.

67%|███████████████████████▍           | 11156/16617 [1:04:38<31:12,  2.92it/s]Traceback (most recent call last):
  File "/root/miniconda3/envs/se/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/root/miniconda3/envs/se/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/root/miniconda3/envs/se/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":300, please report a bug to PyTorch. unable to write to file </torch_85217_8371>

## Expected behavior

In fact, the error only appeared today. Before, I could train and save the model normally.

## Environment

Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] faiss-gpu                 1.7.1           py3.6_hf4b0e32_1_cuda10.1    pytorch
[conda] libfaiss                  1.7.1           hbf11de5_1_cuda10.1    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.17.0           py36h2f8d375_0  
[conda] torch                     1.10.0                   pypi_0    pypi
[conda] torchaudio                0.10.0                   pypi_0    pypi
[conda] torchvision               0.11.1                   pypi_0    pypi

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin

**Comment by malfet** [comment]
@catqaq can you please confirm that you are using https://github.com/princeton-nlp/SimCSE to train?
Seems to be related to https://github.com/pytorch/pytorch/issues/67864

**Comment by catqaq** [comment]
My code is a little different from the official code from https://github.com/princeton-nlp/SimCSE. But I discovered today that it doesn’t matter what model to use.  It might be caused by insufficient shared memory (shm) in my docker. I have encountered this situation several times. At first, due to the different error messages, I thought they were different problems, but in the end I found that they were all caused by insufficient shm.
Sometimes the error message is relatively simple, and the program will not terminate (but it will not continue to run, a bit like a stuck)：
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":300, please report a bug to PyTorch. unable to write to file </torch_214071_153>
 20%|███████                             | 204/1031 [2:23:51<9:43:12, 42.31s/it]
  4%|█▍                                  | 4/100 [2:45:05<66:02:10, 2476.36s/it]
Sometimes the error message will be more complete, which helped me figure out the source of the problem：
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":300, please report a bug to PyTorch. unable to write to file </torch_204948_303>
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
 
 39%|███████████████▌                        | 401/1031 [01:57<03:02,  3.46it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
RuntimeError: DataLoader worker (pid 204949) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
RuntimeError: DataLoader worker (pid(s) 204947, 204949) exited unexpectedly

**Comment by alexanderhmw** [comment]
> 

Did you solve this problem? I also met this problem. Thx!

**Comment by alexanderhmw** [comment]
Did you solve the problem? I also met this problem. Thx!

**Comment by minhoooo1** [comment]
same questiton  I am looking forward to your reply！ Thx!

**Comment by VitalyFedyunin** [comment]
There are number of fixes in coming 1.11 release, related to this issue. You can try nightly builds and see if they work for you.
