### ISSUE TITLE
Change comparison strategy for quantized tensors

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#68548]
From https://github.com/pytorch/pytorch/pull/58926#discussion_r751260732 @vkuzo:

> Any thoughts on adding back the checks for scale and zero_point equality here? A motivating example could be a tensor where all of the values are 0, the zero_point is 0, and the scale could be any number without changing the value of the dequantized version of the tensor. If we have a test case which only checks the dequantized version, it would not catch any changes in scale. I personally would appreciate the extra safety of knowing that any change in quantized tensor internals would be flagged by these checks, even if the change does not change the dequantized output.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by pmeier** [comment]
I'm ok with either strategy. `torch.testing.assert_close` and after # also `self.assertEqual` should serve the developers to enable convenient testing. Thus, you get to decide how to handle the comparison.

Still, given that we worked out the current strategy with @jerryzh168 in #58926, it would be good to get a consensus of the quantization team on what strategy should be used before we change anything.

**Comment by vkuzo** [comment]
Both schools of thought make sense to me.  One question I would have is what are the downsides to doing the stricter comparisons on representation (int_repr + scale + zero_point)?  Are there any real world use cases where the floating point comparison is correct but the internal representation may differ, and we would want the test to pass?

If there aren't any, I'd vote for the strictest check possible.

**Comment by pmeier** [comment]
> One question I would have is what are the downsides to doing the stricter comparisons on representation (int_repr + scale + zero_point)?

In theory, there is no downside. We went for the other one upon request of @jerryzh168. Maybe there was a misunderstanding before, because in general we prefer stricter checks.

That being said, there is [one test](
https://github.com/pytorch/pytorch/pull/67796/files#r749465820) that is passing with the current checks, but is failing in the `.dequantize()`'d versions: 

https://github.com/pytorch/pytorch/blob/a31aea8eaa99a5ff72b5d002c206cd68d5467a5e/test/quantization/core/test_quantized_tensor.py#L815-L817

Both `scales` and `zero_points` should have `numel` entries, but only have one. By checking the components individually, this went undetected. I admit that is more a bug in the creation rather than testing, but shows that there is some merit to testing all components together rather than just individually. 

---

If we keep the componentwise checking, should the list of checks be expanded or kept as is? Currently we are checking

- `per_tensor_affine`
  - `q_scale()`
  - `q_zero_point()`
- `per_channel_affine`
  - `q_per_channel_scales()`
  - `q_per_channel_zero_points()`
  - `q_per_channel_axis()`

In addition, what should be checked for closeness and what for equality? Currently we check everything for closeness, while the default tolerances are `0`. Meaning if we call `assertEqual` only with the tensors, the attributes like scales and zero points will be checked for equality (`actual == expected`). If we pass `rtol` or `atol` `> 0`, attributes like `q_per_channel_axis` will be checked for closeness (`abs(actual - expected) <= atol + rtol * abs(expected)`). That seems counterintuitive to me.

**Comment by jerryzh168** [comment]
I think strict checks works for equality checks, but not closeness checks, since tolerance is only defined in the floating point domain

**Comment by pmeier** [comment]
> tolerance is only defined in the floating point domain

Nope. [`torch.isclose`](https://pytorch.org/docs/master/generated/torch.isclose), which is at the heart of the comparison, considers two tensors close if the following holds

```python
abs(actual - expected) <= atol + rtol * abs(expected)
```

Example:

```
>>> torch.testing.assert_close(1, 2, atol=1, rtol=0)
```

Meaning, we can freely define how we want to compare each component. In this context when we talk about an equality check for a component, we mean that we hard-code `rtol = atol = 0` for this specific check. Closeness checks on the other hand use the tolerances the comparison was called with. An example of mixing equality and closeness checks is the strategy for sparse tensors:

https://github.com/pytorch/pytorch/blob/5fdcc20d8d96a6b42387f57c2ce331516ad94228/torch/testing/_comparison.py#L701-L716

The indices are compared for equality while the values are compared for closeness. That being said, if a user doesn't pass tolerances, the default ones will be used, which happen to be `0` for integer dtypes. Thus, by default, we will have equality checks for everything. Still, we need to define what components we want to compare for closeness in case we have non-zero tolerances.

**Comment by pmeier** [comment]
Running the test suite against a preliminary implementation of the stricter strategy turned up that `assertEqual` is used to test tensors quantized with the `torch.per_channel_affine_float_qparams`. In the current implementation there is no strategy for them so only the integer representation is compared. For the new implementation I propose we fail the comparison if we encounter an "unknown" quantization scheme in order to not give false security. @vkuzo @jerryzh168 what components need to be checked?

**Comment by vkuzo** [comment]
> Running the test suite against a preliminary implementation of the stricter strategy turned up that assertEqual is used to test tensors quantized with the torch.per_channel_affine_float_qparams. In the current implementation there is no strategy for them so only the integer representation is compared. For the new implementation I propose we fail the comparison if we encounter an "unknown" quantization scheme in order to not give false security. @vkuzo @jerryzh168 what components need to be checked?

for `torch.per_channel_affine_float_qparams`, it could make sense to compare int_repr with equality, and the floating point scale and zero_point with a tolerance.

**Comment by pmeier** [comment]
@vkuzo What about the other schemes? From your previous comment I get that you only want a closeness check for `per_channel_affine_float_qparams`. That would result in the following testing strategy for the parameters:

| scheme                             | parameter                   | current   | future    |
|------------------------------------|-----------------------------|-----------|-----------|
| `per_tensor_affine`                | `q_scale`                   | closeness | equality  |
|                                    | `q_zero_point`              | closeness | equality  |
| `per_channel_affine`               | `q_per_channel_axis`        | closeness | equality  |
|                                    | `q_per_channel_scales`      | closeness | equality  |
|                                    | `q_per_channel_zero_points` | closeness | equality  |
| `per_channel_affine_float_qparams` | `q_per_channel_scales`      | -         | closeness |
|                                    | `q_per_channel_zero_points` | -         | closeness |

In addition, `.int_repr()` would always be checked for equality. 

Is this the strategy you want? Should we also test `.q_per_channel_axis()` for `torch.per_channel_affine_float_qparams`?

**Comment by vkuzo** [comment]
AFAIK conceptually integer values should be usually compared for equality, and floating point values for closeness.  Note: Since quantization is imprecise, there is always a small chance that the integer equality check will fail because a single element could be close to the quantization bin boundary.  I believe for int8 quantization testing we are making the argument that it's more valuable to test int_repr for equality to catch real issues a high percentage of the time, and we could be ok with the small chance of a false positive.

For floating point values, the check should be closeness.

For things like `scale`, currently we only support floating point scales so they should be checked for closeness.  In the future we may support integer scales and those would have to be checked for equality.

**Comment by pmeier** [comment]
@vkuzo IIUC, that would give us the strategy summarized under "future":

| scheme                             | parameter                   | current   | future    |
|------------------------------------|-----------------------------|-----------|-----------|
| `per_tensor_affine`                | `q_scale`                   | closeness | closeness |
|                                    | `q_zero_point`              | closeness | closeness |
| `per_channel_affine`               | `q_per_channel_axis`        | closeness | equality  |
|                                    | `q_per_channel_scales`      | closeness | closeness |
|                                    | `q_per_channel_zero_points` | closeness | closeness |
| `per_channel_affine_float_qparams` | `q_per_channel_axis`        | -         | equality  |
|                                    | `q_per_channel_zero_points` | -         | closeness |
|                                    | `q_per_channel_zero_points` | -         | closeness |

Is that correct?

**Comment by jerryzh168** [comment]
> > tolerance is only defined in the floating point domain
> 
> Nope. [`torch.isclose`](https://pytorch.org/docs/master/generated/torch.isclose), which is at the heart of the comparison, considers two tensors close if the following holds regardless of their dtype:
> 
> ```python
> abs(actual - expected) <= atol + rtol * abs(expected)
> ```
> 
> Example:
> 
> ```
> # abs(1 - 2) <= 1 + 0 * abs(2)
> # 1 <= 1
> torch.testing.assert_close(1, 2, atol=1, rtol=0)
> ```
> 
> Meaning, we can freely define how we want to compare each component. In this context when we talk about an equality check for a component, we mean that we hard-code `rtol = atol = 0` for this specific check. Closeness checks on the other hand use the tolerances the comparison was called with. An example of mixing equality and closeness checks is the strategy for sparse tensors:
> 
> https://github.com/pytorch/pytorch/blob/5fdcc20d8d96a6b42387f57c2ce331516ad94228/torch/testing/_comparison.py#L701-L716
> 
> The indices are compared for equality while the values are compared for closeness.
> 
> In the current implementation of `assertEqual`, every quantization component will be checked for closeness. That being said, if a user doesn't pass tolerances, the default ones will be used, which happen to be `0` for integer dtypes. Thus, by default, we will have equality checks for everything. Still, we should define what components we want to compare for closeness in case we have non-zero tolerances.

sorry I probably need to frame this better. what I mean is how are we going to get the closeness arguments for the components like scale/zero_point/int_repr if we check the closeness? from the top level assert_close api, is atol and rtol supposed to be apply to the floating point domain? let's say if I do:
```
assert_close(a, b, atol = 0.1, rtol=0.2)
```
are you saying we should use the same `atol` and `rtol` for all the components? including scale, zero_point, axis, int_repr and the final dequantized Tensor value?

**Comment by vkuzo** [comment]
I don't have any issue with checking the dequantized version for closeness.  I was just hoping we both check the dequantized version for closeness as a general catch-all check, as well as do some stricter checks if it makes sense.  I don't think we need to define a strategy for checking every single component, instead we could do something like
1. check dequantized tensors for closeness
2. check int_repr() for equality
3. check zero_point for equality, if it's an integer
4. check scale for equality, if it's an integer (this does not exist yet but may exist in the future)

I don't have a strong opinion on whether to check the floating point scale for closeness and with which threshold.  Perhaps we can solve that at a later time, unless it's urgent for some reason?

**Comment by jerryzh168** [comment]
> I don't have any issue with checking the dequantized version for closeness. I was just hoping we both check the dequantized version for closeness as a general catch-all check, as well as do some stricter checks if it makes sense. I don't think we need to define a strategy for checking every single component, instead we could do something like
> 
> 1. check dequantized tensors for closeness
> 2. check int_repr() for equality
> 3. check zero_point for equality, if it's an integer
> 4. check scale for equality, if it's an integer (this does not exist yet but may exist in the future)
> 
> I don't have a strong opinion on whether to check the floating point scale for closeness and with which threshold. Perhaps we can solve that at a later time, unless it's urgent for some reason? 

I think the problem for checking both closeness in the floating point domain and equality for components is that how are we going to map the closeness in floating point (dequantized) form to the components? There are cases when the dequantized Tensor are `close` based on `atol` and `rtol` and int_repr are not the same, or scale/zero_point differ by a little bit etc., I'm not sure why we can check the equality when the type is int for components.

**Comment by jerryzh168** [comment]
to be more specific,
let's say assert_close(a, b, atol=..., rtol=...) = True, for two quantized tensors a and b, and for some non-zero `atol` and `rtol`
(1). it could be that int_repr of a and b differ by 1 or 2 in certain positions and rest are the same
(2). it could be the int_repr of a and b are exactly the same, and scale differ by a little bit
(3). it could even be the zero_point for a and b differ by 1 (unlikely but it could happen when rtol is large)
(4). it also could be a combination of (1), (2) and (3)

I'm not how we can say that when a and b are close, int_repr must be the same, and only scale (float) can fluctuate a little bit (case (2)), and ignore all the other possible cases listed above

**Comment by pmeier** [comment]
@jerryzh168 

> are you saying we should use the same `atol` and `rtol` for all the components? including scale, zero_point, axis, int_repr and the final dequantized Tensor value?

Yes, that is the interface we provide. If more granular control is needed, you can always call `assert_close` multiple times:

```python
assert_close(actual.q_scale(), expected.q_scale(), rtol=scale_rtol, atol=scale_atol)
assert_close(actual.q_zero_point(), expected.q_zero_point(), rtol=zero_point_rtol, atol=zero_point_atol)
```

**Comment by pmeier** [comment]
@vkuzo

> I don't have any issue with checking the dequantized version for closeness. I was just hoping we both check the dequantized version for closeness as a general catch-all check, as well as do some stricter checks if it makes sense. 

If @jerryzh168 is right in https://github.com/pytorch/pytorch/issues/68548#issuecomment-988401992 that there are cases where only either the componentwise checks or the dequantized check works out, we should avoid doing both. 

> I don't think we need to define a strategy for checking every single component, instead we could do something like
> 
>     1. check dequantized tensors for closeness
> 
>     2. check int_repr() for equality
> 
>     3. check zero_point for equality, if it's an integer
> 
>     4. check scale for equality, if it's an integer (this does not exist yet but may exist in the future)

Ignoring 1. and 2. for now, I have a few follow-up questions:

- What about the `q_per_channel_axis`? It is currently checked by `assertEqual` and it seems to make sense to also check it in the future?
- Does "check zero_point for equality, if it's an integer" mean that you only want this check if it is an integer or fall back to a closeness check if it isn't an integer? Furthermore, how do you want to handle the case where only one tensor has an integer zero point?

> I don't have a strong opinion on whether to check the floating point scale for closeness and with which threshold. Perhaps we can solve that at a later time, unless it's urgent for some reason?

There is [one test that fails](https://app.circleci.com/pipelines/github/pytorch/pytorch/416834/workflows/899a80e0-907b-4553-be9d-a7bb37330e2d/jobs/16795669/tests) if we compare for equality. This argument is moot if you want no check for floating point scales. Of course this then also raises the question about how to handle the mixed integer-floating-point case.

**Comment by vkuzo** [comment]
> I think the problem for checking both closeness in the floating point domain and equality for components is that how are we going to map the closeness in floating point (dequantized) form to the components? There are cases when the dequantized Tensor are close based on atol and rtol and int_repr are not the same, or scale/zero_point differ by a little bit etc., I'm not sure why we can check the equality when the type is int for components.

@jerryzh168 , that's a good point, you convinced me that only checking the closeness on dequantized value is a general strategy which would work in all cases, and more specific checks might have to be use case specific.

@pmeier , sorry, I gave incorrect thoughts above, I now think @jerryzh168 's suggestion is better.

**Comment by pmeier** [comment]
@vkuzo So ultimately, you are ok with the current behavior of `assert_close`, i.e. only checking the dequantized versions for closeness?

**Comment by vkuzo** [comment]
yes, originally I was not but the arguments presented above changed my view, I hope that's ok

**Comment by pmeier** [comment]
No worries, this is complicated stuff. @jerryzh168 I'm guessing you are also ok with the current behavior given that you designed it? If yes, I think we can close this.

**Comment by jerryzh168** [comment]
yeah I feel the current behavior would make the most sense for now, thanks for all the discussions @vkuzo @pmeier. Also might be helpful to document this somehow since it might be a bit confusing to people that we only check the dequantized values for quantized Tensors.

**Comment by pmeier** [comment]
@vkuzo @jerryzh168 I've added a note in #68911.

**Comment by pmeier** [comment]
There is one more issue that we need to discuss: default tolerances. As explained in https://github.com/pytorch/pytorch/issues/68548#issuecomment-978945012, the default tolerances for quantized tensors are `rtol = atol = 0`, since they are integral dtypes. This means, without passing the tolerances explicitly, we would check the floating point dequantized versions for equality. That is probably not what we want.

Given that `.dequantize()` returns a `torch.float32` tensor, I propose we reuse its default tolerances for 
- `torch.quint8`,
- `torch.qint8`, and
- `torch.qint32`.

Thoughts?

**Comment by jerryzh168** [comment]
> There is one more issue that we need to discuss: default tolerances. As explained in [#68548 (comment)](https://github.com/pytorch/pytorch/issues/68548#issuecomment-978945012), the default tolerances for quantized tensors are `rtol = atol = 0`, since they are integral dtypes. This means, without passing the tolerances explicitly, we would check the floating point dequantized versions for equality. That is probably not what we want.
> 
> Given that `.dequantize()` returns a `torch.float32` tensor, I propose we reuse its default tolerances for
> 
> * `torch.quint8`,
> * `torch.qint8`, and
> * `torch.qint32`.
> 
> Thoughts?

I think we can adopt the same default tolerance as `torch.float32` since the comparison is done in floating point domain?

**Comment by pmeier** [comment]
> we can reuse it for all quantized tensors no matter the dtype it has I think.

The default tolerances are currently acquired from a dictionary with `(0, 0)` as default if the `dtype` is not in there:

https://github.com/pytorch/pytorch/blob/043098ef7f259d6f389115b47a4466d7efe62f4c/torch/testing/_comparison.py#L46-L55

Thus, we need to be explicit what dtypes have looser default tolerance. Although the documentation only mentions the ones I mentioned in https://github.com/pytorch/pytorch/issues/68548#issuecomment-995518325 from looking through the attributes of `torch`, this seems to be the complete set:

- `quint8`
- `quint2x4`
- `quint4x2`
- `qint8`
- `qint32`

Is this correct, or did I miss one?
