### ISSUE TITLE
Pytorch 1.9.1 cannot be built against cuda 11.4.2

### ISSUE THREAD

**Issue by Heermosi** [pytorch/pytorch#68577]
## 🐛 Bug

The bug was exactly the same as what encountered in v1.9.0 build against cuda 11.4.2, the issue is not fixed in branch v1.9.0 and v1.9.1

`

/pytorch/caffe2/utils/math_gpu.cu(908): error: namespace "thrust" has no member "host_vector"

/pytorch/caffe2/utils/math_gpu.cu(908): error: expected an expression

/pytorch/caffe2/utils/math_gpu.cu(909): error: namespace "thrust" has no member "host_vector"

/pytorch/caffe2/utils/math_gpu.cu(909): error: expected an expression

/pytorch/caffe2/utils/math_gpu.cu(910): error: namespace "thrust" has no member "host_vector"

/pytorch/caffe2/utils/math_gpu.cu(910): error: type name is not allowed

/pytorch/caffe2/utils/math_gpu.cu(910): error: expected an expression

/pytorch/caffe2/utils/math_gpu.cu(912): error: identifier "A_array" is undefined

/pytorch/caffe2/utils/math_gpu.cu(913): error: identifier "B_array" is undefined

/pytorch/caffe2/utils/math_gpu.cu(914): error: identifier "C_array" is undefined

/pytorch/caffe2/utils/math_gpu.cu(917): error: identifier "A_array" is undefined

/pytorch/caffe2/utils/math_gpu.cu(919): error: identifier "B_array" is undefined

/pytorch/caffe2/utils/math_gpu.cu(920): error: identifier "C_array" is undefined
`
## To Reproduce

1.
1.
1.

## Expected behavior

Fix the missing definition?

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version 1.9.0/1.9.1
 - OS (e.g., Linux): Ubuntu Server 20.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: 3.10.0
 - CUDA/cuDNN version: 11.4.2/8.1
 - GPU models and configuration: 8.0&8.6
 - Any other relevant information: no

## Additional context

cc @malfet @seemethere @ngimel

**Comment by ngimel** [comment]
This is expected, 11.4 is not supported with pytorch 1.9

**Comment by seemethere** [comment]
Going to close this since @ngimel already mentioned that pytorch 1.9 does not support CUDA 11.4

If the same error can be observed within `master` we should re-open
