### ISSUE TITLE
When `num_workers=0`, `prefetch_factor` is enforced to be `2` but this is missing from documentation

### ISSUE THREAD

**Issue by agamemnonc** [pytorch/pytorch#68576]
## 📚 Documentation

While constructing a `DataLoader` with `num_workers=0`, it is currently enforced that `prefetch_factor` can only be set to the default value (which is `2`). I am not too sure why and whether this should be expected behavior, for example wouldn't it perhaps be better to also support `prefetch_factor` values of `0` or `1`?

https://github.com/pytorch/pytorch/blob/e56d3b023818f54553f2dc5d30b6b7aaf6b6a325/torch/utils/data/dataloader.py#L180-L182

In any way, even in the case where only `prefetch_factor=2` should be supported when `num_workers=0`, I think there should be a note about that in the related docstring section:

https://github.com/pytorch/pytorch/blob/e56d3b023818f54553f2dc5d30b6b7aaf6b6a325/torch/utils/data/dataloader.py#L117-L119

Please do let me know if this issue should be marked as a bug issue vs. a documentation one.

Otherwise, if an addition to the docstring is required, I am happy to submit a PR. 

cc @brianjo @mruberry @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
`prefetch_factor` is not used and not allowed to be specified for `number_worker==0` (single process mode) as suggested in the Error message. https://github.com/pytorch/pytorch/blob/e56d3b023818f54553f2dc5d30b6b7aaf6b6a325/torch/utils/data/dataloader.py#L180-L182

I personally don't see there should be a change.

**Comment by agamemnonc** [comment]
Well, as a user/practicioner who uses configuration files to keep experiments tracking manageable, it means that whenever I have to switch from e.g. `num_workers=8` to `num_workers=0` (eg for debugging), I need to set `prefetch_factor=2`, which is definitely not intuitive. I think it would be much more elegant to default `prefetch_factor=None` and have something like the following in lieu of the current check:

```python
if num_workers > 0:
    if prefetch_factor is None:
        prefetch_factor = 2   # default value
else:
    if prefetch_factor is not None:
        raise ValueError('prefetch_factor option could only be specified in multiprocessing.' 
                         'let num_workers > 0 to enable multiprocessing, otherwise set prefetch_factor to None.')
```

An alternative would also be to issue a warning as opposed to raising an Exception advising the user that the passed `prefetch_factor` will be ignored since `num_workers==0`. 

Just my two cents.

**Comment by agamemnonc** [comment]
In case my proposal is not accepted, I would definitely recommend including in the documentation the fact that you have to set `prefetch_factor=2` in this case, as it took me quite some time trying to figure out why `num_workers=0, prefetch_factor=None` didn't work (I actually had to look into the code).

**Comment by ejguan** [comment]
> I think it would be much more elegant to default `prefetch_factor=None` and have something like the following in lieu of the current check:

I see. Sounds great. Feel free to open a PR to fix that. Thanks

**Comment by lakshayr31** [comment]
I recently was going through some old code, where they had specified the prefetch_factor to be 2, when the num_workers was 0. This is valid I think?
The current change doesn't accommodate that. 

`

        if num_workers == 0 and prefetch_factor is not None:
            raise ValueError('prefetch_factor option could only be specified in multiprocessing.'
                             'let num_workers > 0 to enable multiprocessing, otherwise set prefetch_factor to None.')
        elif num_workers > 0 and prefetch_factor is None:
            prefetch_factor = 2
        elif prefetch_factor is not None and prefetch_factor < 0:
            raise ValueError('prefetch_factor option should be non-negative')
`

So I propose changing it by 
`

        if num_workers == 0:
            if prefetch_factor is None:
                   prefetch_factor = 2
            elif prefetch_factor != 2:
                   raise ValueError('prefetch_factor option could only be specified in multiprocessing.'
                             'let num_workers > 0 to enable multiprocessing, otherwise set prefetch_factor to None.')
        elif num_workers > 0 and prefetch_factor is None:
            prefetch_factor = 2
        elif prefetch_factor is not None and prefetch_factor < 0:
            raise ValueError('prefetch_factor option should be non-negative')
`
Although I dont know if this is **very** necessary. Let me know your thoughts.
