### ISSUE TITLE
Quantization test `test_embedding_bag_linear` raises error when looping over three qengines

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#68581]
## 🐛 Bug

The quantization test `test_embedding_bag_linear` will raise error when looping over three qengines. The test script only loops over two qengines now but if there are three, the test fails.
Below is detailed explanation.

Test full name: `quantization.eager.test_quantize_eager_qat.TestQuantizationAwareTraining.test_embedding_bag_linear`
The test code is found in `pytorch/test/quantization/eager/test_quantize_eager_qat.py`.
https://github.com/pytorch/pytorch/blob/dbbb02474b9ad8044d061caee9fb0916da93101b/test/quantization/eager/test_quantize_eager_qat.py#L138
The code is something like:
```python
    def test_embedding_bag_linear(self):
        for qengine in supported_qengines: # loop over qengines
            with override_quantized_engine(qengine):
                # do testing on model ManualEmbeddingBagLinear
```
There are only two qengines right now, i.e. FBGEMM and QNNPACK and there will be no errors.
If code is changed to something like:
```python
    def test_embedding_bag_linear(self):
        for qengine in ('fbgemm', 'qnnpack', 'fbgemm'): # loop over any three qengines in any order
            with override_quantized_engine(qengine):
                # do testing on model ManualEmbeddingBagLinear
```
then an error will be raised:
```
======================================================================
ERROR: test_embedding_bag_linear (quantization.eager.test_quantize_eager_qat.TestQuantizationAwareTraining)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home2/weiwenxi/pytorch/test/quantization/eager/test_quantize_eager_qat.py", line 149, in test_embedding_bag_linear
    test_only_train_fn(model, train_indices)
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/testing/_internal/common_quantization.py", line 117, in test_only_train_fn
    output = model(data)
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/testing/_internal/common_quantization.py", line 1699, in forward
    x = self.emb(input, offsets, per_sample_weights)
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1128, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/nn/qat/modules/embedding_ops.py", line 39, in forward
    return F.embedding_bag(input, self.weight_fake_quant(self.weight), offsets,
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home2/weiwenxi/anaconda3/lib/python3.8/site-packages/torch/ao/quantization/fake_quantize.py", line 158, in forward
    X = torch.fake_quantize_per_channel_affine(
RuntimeError: `zero_point` must be between `quant_min` and `quant_max`.

```
**Note**: the qengine list can contain any qengine in any order as long as the length is three or larger.
If one prints out the qengine in each loop, it can be found the error is raised in the third loop.
If one prints out the `zero_point`, it can be found the invalid value of zero point is always -15 (should be between 1 and 255).

It seems to be related to weight initialization of `EmbeddingBag`.
- If weight is printed out, it can be found that the values of weight tensors change in each loop but always are the same values each time the test is run. That means the values of weight are different in each loop of the test. But if the test is run for multiple times, these values are always reproduced.
- If one adds `self.weight.data = torch.randn(self.weight.shape, dtype=float)` to the end of `__init__` funtion of class `EmbeddingBag` (torch/nn/qat/modules/embadding_ops.py), the test will pass.

## To Reproduce

1. Clone the master branch and go to the test directory of PyTorch (e.g. pytorch/test)
1. Open & edit quantization/eager/test_quantize_eager_qat.py and go to line 139
2. Change this line (`for qengine in supported_qengines:`) to  `for qengine in ['fbgemm', 'qnnpack', 'fbgemm']:` (the list of qengines can be anything as long as length is three) Then save and exit.
3. Run the test by `python test_quantization.py TestQuantizationAwareTraining.test_embedding_bag_linear`

Note: If one adds `self.weight.data = torch.randn(self.weight.shape, dtype=float)` to the end of `__init__` funtion of class `EmbeddingBag` (torch/nn/qat/modules/embadding_ops.py), the test will pass.

## Expected behavior

Test should pass with no error.

## Environment

Master branch of PyTorch
PyTorch version: 1.11.0a0+gitf6696c5
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.10

Python version: 3.7.10 (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.11.0a0+gitf6696c5
[pip3] torchvision==0.11.0a0+c6a03c7
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0           h06a4308_296
[conda] mkl-include               2021.2.0           h06a4308_296
[conda] mkl-service               2.3.0            py37h27cfd23_1
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.1            py37ha9443f7_2
[conda] numpy                     1.20.1           py37h93e21f0_0
[conda] numpy-base                1.20.1           py37h7d8b39e_0
[conda] torch                     1.11.0a0+gitf6696c5          pypi_0    pypi
[conda] torchvision               0.11.0a0+c6a03c7          pypi_0    pypi

## Additional context

We found this issue because we are working to add a new quantization backend, i.e. MKLDNN. Once the MKLDNN backend is added, the test with the original code will fail because it will loop over the three qengines. After some investigation we don't think this issue is caused by the new code of MKLDNN.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by Xia-Weiwen** [comment]
Please take a look at this issue. I guess it has something to do with weight initialization and might not be difficult to solve.

**Comment by supriyar** [comment]
> RuntimeError: `zero_point` must be between `quant_min` and `quant_max`.

For embedding/embedding_bag fake-quantization this restriction shouldn't hold since we use the following equation to quantize the value

```
xq = Round(Xf * inv_scale + zero_point),
# setting zero_point to (-1 * min *inv_scale) we get
Xq = Round((Xf - min) * inv_scale)
```

**Comment by Xia-Weiwen** [comment]
Close this issue since it's been solved by https://github.com/pytorch/pytorch/pull/68852
