### ISSUE TITLE
[Caffe2] File "testimg.py", line 5, in <module> caffe2.set_mode_gpu() NameError: name 'caffe2' is not defined

### ISSUE THREAD

**Issue by jonasess** [pytorch/pytorch#6858]
I installed caffe2 and i tested the installation and it gave me success 
When i try this code 

from caffe2.python import workspace, model_helper
import numpy as np
GPU_ID = 1 # Switch between 0 and 1 depending on the GPU you want to use.
caffe2.set_mode_gpu()
caffe2.set_device(GPU_ID)
x = np.random.rand(4, 3, 2)
print(x)
print(x.shape)
workspace.FeedBlob("my_x", x)
x2 = workspace.FetchBlob("my_x")
print(x2)

And run phthon test.py
i get this error
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
Traceback (most recent call last):
  File "testimg.py", line 5, in <module>
    caffe2.set_mode_gpu()
NameError: name 'caffe2' is not defined
`
Any solution?

**Comment by malfet** [comment]
Int the above example, `caffe2` is not defined, because it is not imported (only `workspace` and `model_helper` are imported from `caffe2.python`)
