### ISSUE TITLE
sparse COO comparison strategy

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#68590]
In #58844 the following strategy was enacted for `torch.testing.assert_close`:

1. If `check_is_coalesced` is set (default), `actual.is_coalesced()` and `expected.is_coalesced()` have to match.
    https://github.com/pytorch/pytorch/blob/f9ef807f4d51aba8143f23c446fa723c03c3fc23/torch/testing/_asserts.py#L236-L243
2. In case the check is disabled and `.is_coalesced()` mismatches, both tensors are `.coalesced()` before comparison.
    https://github.com/pytorch/pytorch/blob/f9ef807f4d51aba8143f23c446fa723c03c3fc23/torch/testing/_asserts.py#L293-L295
3. The actual comparison checks the NNZ, the indices and the values individually
     https://github.com/pytorch/pytorch/blob/f9ef807f4d51aba8143f23c446fa723c03c3fc23/torch/testing/_asserts.py#L68-L92

This diverges from the current behavior of `TestCase.assertEqual`:

1. Both tensors are always `.coalesced()` before comparison
    https://github.com/pytorch/pytorch/blob/b1aa45a8a78211fcfec0923b5facca2b2829311d/torch/testing/_internal/common_utils.py#L1923-L1924
2. The actual comparison checks the indices and the values individually
    https://github.com/pytorch/pytorch/blob/b1aa45a8a78211fcfec0923b5facca2b2829311d/torch/testing/_internal/common_utils.py#L1925-L1938

Merging the comparison implementation of `torch.testing.assert_close` and `TestCase.assertEqual` in #67796 turned up a few instances where this divergence fails the test.

Thus, we need to decide how to move forward with this. From a testing perspective, both approaches or any other approach is fine as long as it is the consensus of the sparse team. Feel free to propose another strategy in case you think both strategies above are not what you need.

cc @nikitaved @pearu @cpuhrsch @IvanYashchuk

**Comment by pearu** [comment]
Copying https://github.com/pytorch/pytorch/pull/67796#discussion_r752461445:

The old assertEqual implementation was based on the following considerations:
1. there are different levels of equality tests: mathematical equality (e.g. comparing tensors with different layouts), representation equality (e.g. comparing tensors with the same layout), and internal representation equality (e.g. comparing uncoalesced state of COO tensors as defined by `_values()` and `_indices()`).
2. `assertEqual` mostly deals with representation equality and for all other layouts other than COO (so far), representation and internal representation equalities are identical.
3. Internal representation equality can be valuable for ensuring that internal optimizations function as expected. For instance, when constructing a COO tensor from in-place additions, one would want to ensure that the COO tensor stays uncoalesced in-between such operations. A failure to do so would mean a considerable performance hit. Notice that representation equality would not be able to detect this kind of regressions.

IIUC, it has been suggested here to implement only the representation equality for COO tensors, that is, `assertEqual` would always call `.coalesce()` before comparing the content of tensors. That would be fine with me (in the sense of still being able to test internal representation equality) iff `assertEqual` would support also tuple objects as inputs (unless it does already support that). If so, for internal representation equality tests one could introduce a utility function:
```python
def serialize(coo):
    return coo._indices(), coo._values()
```
and perform the internal representation equality test on COO tensors as follows:
```python
self.assertEqual(serialize(actual), serialize(expected))
```

Does the above make sense?

**Comment by pmeier** [comment]
> That would be fine with me (in the sense of still being able to test internal representation equality) iff `assertEqual` would support also tuple objects as inputs (unless it does already support that)

Yes, `assertEqual` fully accepts containers and checks the content elementwise (the snippets below were run with the code from #67796):

```python
import torch
from torch.testing._internal.common_utils import TestCase

assertEqual = TestCase().assertEqual

indices = (
    (0, 1),
    (1, 0),
)
values = (1, 2)
actual = torch.sparse_coo_tensor(indices, values, size=(2, 2))
expected = actual.clone()

assertEqual(actual, expected)


def serialize(sparse_coo_tensor):
    return sparse_coo_tensor._indices(), sparse_coo_tensor._values()


assertEqual(serialize(actual), serialize(expected))
```

Note that not letting `assertEqual` handle the sparse comparison results in less expressive error messages:

```python
indices = (
    (0, 1),
    (1, 0),
)
actual_values = (1, 2)
actual = torch.sparse_coo_tensor(indices, actual_values, size=(2, 2))

expected_values = (1, 3)
expected = torch.sparse_coo_tensor(indices, expected_values, size=(2, 2))

try:
    assertEqual(actual, expected)
except AssertionError as error:
    print(error)

try:
    assertEqual(serialize(actual), serialize(expected))
except AssertionError as error:
    print(error)
```

```
Sparse COO values are not equal!

Mismatched elements: 1 / 2 (50.0%)
Greatest absolute difference: 1 at index 1
Greatest relative difference: 0.3333333432674408 at index 1

############################################################
Tensor-likes are not equal!

Mismatched elements: 1 / 2 (50.0%)
Greatest absolute difference: 1 at index 1
Greatest relative difference: 0.3333333432674408 at index 1


The failure occurred for item [1]
```

**Comment by pmeier** [comment]
The tensors that failed the tests that were popping up in #67796 were both uncoalesced but had different NNZ (code is run on #67796):

```python
import torch
from torch.testing._internal.common_utils import TestCase

assertEqual = TestCase().assertEqual

actual_indices = (
    (0, 1, 1),
    (1, 0, 0),
)
actual_values = (1, 2, 1)
actual = torch.sparse_coo_tensor(actual_indices, actual_values, size=(2, 2))

expected_indices = (
    (0, 1),
    (1, 0),
)
expected_values = (1, 3)
expected = torch.sparse_coo_tensor(expected_indices, expected_values, size=(2, 2))
```

```
AssertionError: The number of specified values in sparse COO tensors does not match: 3 != 2
```

If we `.coalesce()` before the comparison, everything is fine:

```python
assertEqual(actual.coalesce(), expected.coalesce())
```

**Comment by pearu** [comment]
How about using the following strategy for comparing COO tensors:
- `assertEqual` never coalesces its inputs and its implementation would use only `_indices()` and `_values()` for testing COO equality. Testing `_nnz()` equality is superfluous anyway and testing `is_coalesce()` equality is not important (and if it is for some reasone, tests should explicitly use `assertEqual(actual.is_coalesce(), expected.is_coalesce())` or similar)
- tests should explicitly coalesce COO tensor inputs if the intention is to test COO tensors representation equality. The existing tests must be updated accordingly.

**Comment by pmeier** [comment]
> Testing _nnz() equality is superfluous anyway

Theoretical, yes. From the testing perspective it is more expressive to test that first, because otherwise the error message would tell you that the shapes doesn't match, but this shape is referring to the shape of the values / indices and not the shape of the tensor.

**Comment by pearu** [comment]
IIUC, from
https://github.com/pytorch/pytorch/blob/b1aa45a8a78211fcfec0923b5facca2b2829311d/torch/testing/_internal/common_utils.py#L1932
follows that if `_indices()` shapes do not match, the exception message will contain `Sparse tensor indices failed to compare as equal` (followed by shape-mismatch message) which should be expressive enough to conclude that the shape mismatch message corresponds to indices tensor, not to the COO tensor.

**Comment by pmeier** [comment]
That is true for the current implementation. Using the example from https://github.com/pytorch/pytorch/issues/68590#issuecomment-973839734 and removing the `.coalesce()` calls, the error looks like this:

```
AssertionError: False is not true : Sparse tensor indices failed to compare as equal! Attempted to compare equality of tensors with different sizes. Got sizes torch.Size([2, 3]) and torch.Size([2, 2]).
```

This works, since the `._indices()` are "fully" compared, i.e. attributes as well as values. In contrast, at this stage `assert_close` (which is functionally equivalent to the new implementation of `assertEqual` for this discussion) only compares the values:

https://github.com/pytorch/pytorch/blob/7c6a8a47db112e6efe24d2d55d69fe634b732de1/torch/testing/_comparison.py#L701-L708

If we remove the NNZ check, the error message would read

```
>>> assert_close(actual, expected)
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
```

With #68722 we will get at least some debug information about what is happening, but it is still cumbersome. Thus, we either need to also "fully" compare the indices or keep the NNZ check. My vote is out for the latter, since the error message is more concise while conveying the same information.

**Comment by pearu** [comment]
> If we remove the NNZ check, the error message would read..

We can keep the NNZ check but this sounds like hiding a bug in the `assert_close` exception message. If `assert_close` is equivalent to `assertEqual` and `self._compare_regular_values(..., identifier="Sparse COO indices")` call seems to have enough info to compose an informative exception message, why does `assert_close` strips the `identifier` info?
It is possible that I am not following all the relations in this complex of old/new implementations of assertEqual/assert_close and other parts...

**Comment by pmeier** [comment]
As the name implies, `self._compare_regular_values(..., identifier="Sparse COO indices")` will only compare the values and assumes that attributes like `.shape` or `.layout` were already checked. At the core, it simply calls `torch.isclose` on the inputs:

https://github.com/pytorch/pytorch/blob/7c6a8a47db112e6efe24d2d55d69fe634b732de1/torch/testing/_comparison.py#L774-L776

The error you see above, simply comes from `torch.isclose`:

```python
>>> torch.isclose(torch.zeros(2, 3), torch.zeros(2, 2))
RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
```

So we can either add these checks by calling `TensorLikePair(actual._indices(), expected._indices(), ...).compare()` or simply check the NNZ and by that asserting that the assumption is valid afterwards.

**Comment by pmeier** [comment]
Leaving the NNZ discussion aside for now, what I get is that the following behavior is preferred:

1. Never check coalescences. This implies that the test contributor always needs to call `.coalesce()` themselves in case only representation equality is needed as detailed in https://github.com/pytorch/pytorch/issues/68590#issuecomment-973098211.
2. Remove the `check_is_coalesced` check as consequence of 1.

If we go with this, I propose the following next steps:

1. I'll change #67796 to have the same behavior for sparse COO tensors as the current `assertEqual`, i.e. always coalescing the inputs.
2. Someone from the sparse team sends a follow-up PR, removing this patch and fixing all tests that fail because of that.

In case we go that route, any takers for 2.?

**Comment by pearu** [comment]
> As the name implies, `self._compare_regular_values(..., identifier="Sparse COO indices")` will only compare the values and assumes that attributes like `.shape` or `.layout` were already checked.

This makes sense and implies that `nnz` is required. Notice that `nnz` corresponds to only one dimension of `indices` and `values` that otherwise can have 2 and any dimensions, respectively. What is the exception message when other dimensions will mismatch? Perphaps we should explicitly compare the shapes of indices (and values) instead of just `nnz`?

**Comment by pearu** [comment]
[Recall](https://pytorch.org/docs/master/sparse.html#hybrid-sparse-coo-tensors), a general COO tensor `x` has the following invariants:
```python
x._indices().shape == (x.sparse_dim(), x._nnz())
x._values().shape == (x._nnz(), x.dense_dim())
len(x.shape) == x.sparse_dim() + x.dense_dim()
```
Hence, a closeness test of a two COO tensors x and y involves the following checks as a minimum:
```python
x.shape == y.shape
x.sparse_dim() == y.sparse_dim()
x._nnz() == y._nnz()
x._indices() == y._indices()
x._values() == y._values()
```

**Comment by mruberry** [comment]
@pmeier -- can we close this now?
