### ISSUE TITLE
ONNX export support for quantize_fx

### ISSUE THREAD

**Issue by TingfengTang** [pytorch/pytorch#68638]
code snippet:

```python
model_to_quantize_fx=quantize_fx.prepare_qat_fx(model_to_quantize,qconfig_dict)        
model_to_quantize_fx.apply(torch.quantization.disable_observer)
torch.onnx.export(model_to_quantize_fx,torch.randn(1,1,60,60).cuda(),'xxxxx.onnx',opset_version=13)
```

error:
`RuntimeError: Exporting the operator fused_moving_avg_obs_fake_quant to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

**Comment by dagitses** [comment]
Re-assigning to onnx team to take a look.

**Comment by garymm** [comment]
@TingfengTang did this used to work in PyTorch 1.8?

Can you please provide full repro code? Ideally something we can just run in Google Colab.

**Comment by TingfengTang** [comment]
@garymm, It works well in PyTorch1.8
the code snippet below will reproduce the runtime error:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.quantization.quantize_fx as quantize_fx
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv_0 = nn.Conv2d(in_channels=12, out_channels=16, kernel_size=3)
        self.conv_1 = nn.Conv2d(in_channels=16, out_channels=20, kernel_size=(2,4), stride=(2,1), padding=2, dilation=1)
    def forward(self, x):
        x = self.conv_0(x)
        x = self.conv_1(x)
        return x

def test():
    net = Model()
    net.train()
    qconfig_dict={"":torch.quantization.get_default_qat_qconfig('fbgemm')}
    net=quantize_fx.prepare_qat_fx(net,qconfig_dict)
    x = torch.rand(1, 12, 64, 64)
    result=net(x)
    net.apply(torch.quantization.disable_observer)
    torch.onnx.export(net,x,'xxxxx3.onnx',opset_version=13)
if __name__ == "__main__":
    test()

**Comment by garymm** [comment]
Thanks, I can reproduce the issue now.

According to the [PyTorch 1.10 docs](https://pytorch.org/docs/1.10.0/quantization.html) FX Graph Mode Quantization is still a prototype, so the team that maintains torch.onnx is not likely to support this anytime soon.

We are actively working on supporting eager-mode quantization though. Hopefully that will be ready for PyTorch 1.11.

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1525657>

**Comment by RunningLeon** [comment]
Still have same issue in torch 1.12. Will it be supported in the future?

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

quantization is activelly being worked on by Dynamo team, so the new API is the way to go
