### ISSUE TITLE
quantization of basic 3D ops missing?

### ISSUE THREAD

**Issue by mikeseven** [pytorch/pytorch#68635]
## 🐛 Bug

Conv3D is missing for qnnpack backend but it exists with fbgemm
maxpool3d is missing from fbgemm backend. (not checked with qnnpack but likely missing too)

## To Reproduce

Simply quantize slowfast model from pytorch hub as usual or with FX. Same bugs.

## Expected behavior

1- consistent support of operations in fbgemm and qnnpack backends for quantization on CPU
2- support, even non-optimized, of basic 3D operators such as conv, max/avg pool. This would at least allow using numeric suite or other analysis tools to debug quantization with even reference models on pytorch hub.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10 and master
 - OS (e.g., Linux): linux and mac
 - How you installed PyTorch (`conda`, `pip`, source): conda for 1.10 env, source for main branch env
 - Build command you used (if compiling from source): per documentation online for ubuntu 20.04
 - Python version: 3.9
 - CUDA/cuDNN version: latest
 - GPU models and configuration: irrelevant, it's all CPU
 - Any other relevant information:

## Additional context

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
Conv3D should be supported for both backends, we have a test here that runs on both fbgemm and qnnpack for conv3d ops - https://github.com/pytorch/pytorch/blob/master/test/quantization/core/test_quantized_op.py#L4527-L4528. Do you have a small repro where quantizing this operator fails on qnnpack?

For maxpool3d, would it be possible for you to run the model with this operator in FP32? I'm afraid the un-optimized quantized version of the operator might end up performing worse than the FP32 one.

**Comment by z-a-f** [comment]
@supriyar @mikeseven Is there any action item related to this issue? SHould we close it?

**Comment by vkuzo** [comment]
closing as @supriyar comment should address this.  Please feel free to reopen if needed.
