### ISSUE TITLE
[Numeric Suite] support for multiple inputs

### ISSUE THREAD

**Issue by mikeseven** [pytorch/pytorch#68634]
## 🚀 Feature
Numeric suite has no support for models having multiple inputs, either as list of tensors, or a dict of tensors when it creates GraphModules for float model and int model. 

## Motivation

support models with multiple inputs.

## Pitch

no crash

## Alternatives

1- API should be extended with concrete_args as for fx.symbolic_trace()

2- wrapping model such that: concatenating inputs into 1 tensor and un-concatenating it to feed the multi-input model does work. But it's really a hack for similar input tensors, it won't work for a general list of tensors.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
Hi @mikeseven, thanks for the request. Are you using the eager or fx mode numeric suite for your experiments?

We are planning on making various improvements to the numeric suite in the coming months, this will be one of the things we plan to implement.
cc @vkuzo @HDCharles

**Comment by HDCharles** [comment]
example of functionality: https://github.com/pytorch/pytorch/blob/9d47652bee39ffd0001fc6088ae949be08674710/test/quantization/eager/test_numeric_suite_eager.py#L475
