### ISSUE TITLE
docker bug

### ISSUE THREAD

**Issue by Lingeer** [pytorch/pytorch#68646]
## To Reproduce

1.docker pull pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
2.from torchvision.io import read_image
3.cant use read_image!!!

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @ezyang @seemethere @malfet

**Comment by dagitses** [comment]
What exactly happens in step 3? What can't you do with `read_image`?

**Comment by dagitses** [comment]
module: build isn't ideal, but I think it hits the right people wrto Docker.

**Comment by malfet** [comment]
@dagitses we have `module: docker` which would be more appropriate in this case

**Comment by malfet** [comment]
@Lingeer is there a reason why you need to use PyTorch-1.9 when 1.9.1 and 1.10 are already out?
And I have a repro:
```
 docker run pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel python -c "from torchvision.io import read_image; print(read_image('/usr/local/cuda-10.2/extras/CUPTI/doc/Cupti/doxygen.png'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torchvision/io/image.py", line 259, in read_image
    data = read_file(path)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/io/image.py", line 79, in read_file
    data = torch.ops.image.read_file(path)
  File "/opt/conda/lib/python3.7/site-packages/torch/_ops.py", line 60, in __getattr__
    op = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator image::read_file
```

**Comment by Lingeer** [comment]
@malfet
Got it. Thanks.
