### ISSUE TITLE
[PyTorch] Don't use scientific notation for printing integer tensors

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#6865]
We currently use scientific notation (E-notation) to print large integer tensors. We shouldn't do this because it hides meaningful digits and because E-notation corresponds to floating point data types in Python.

```python
>>> x = torch.ones(525076, dtype=torch.int)
>>> x.sum()
tensor(5.2508e+05)
>>> x.sum().item()
525076
```

**Comment by SsnL** [comment]
duplicate of https://github.com/pytorch/pytorch/issues/6811

**Comment by superbobry** [comment]
I can look into fixing this unless someone is already on it.

**Comment by fmassa** [comment]
@li-roy are you working on this?

**Comment by li-roy** [comment]
@fmassa @superbobry Yeah I'm working on all of the tensor issues.
