### ISSUE TITLE
How to specify the backends when running on CPU

### ISSUE THREAD

**Issue by zheng-ningxin** [pytorch/pytorch#68729]
### How to specify the backends when running on CPU.

Hi, I noticed that there are multiple backends available on CPU in pytorch: mkl, mkldnn, openmp. 
How do I know which backend pytorch is using in current model and can I specify the backend?

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by jbschlosser** [comment]
Hey @zheng-ningxin, I'd encourage you to post a question like this on the forums, as you're more likely to get assistance there.

That said, you can identify which backends are available using the functions documented [here](https://pytorch.org/docs/stable/backends.html) and can disable backends using e.g.
```
with torch.backends.mkldnn.flags(enabled=False):
    # do stuff...
```
