### ISSUE TITLE
GIL is not released in THPVariable_setitem

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#68739]
## 🐛 Bug

GIL is not released in most of slice filling operations called in THPVariable_setitem

## To Reproduce

run `gdb --args python -c 'import torch; t = torch.ones((10, 10, 10), device="cuda"); t[...,3:] = 1'`, set breakpoint on `cudaLaunchKernel` and check GIL status with `p PyGILState_Check()`
Here https://github.com/pytorch/pytorch/blob/39ec0f321b2f5bd218dd1136ee08a951d876a33f/torch/csrc/autograd/python_variable_indexing.cpp#L388-L449 GIL is released for advanced indexing assignment, but not for slice assignment
## Expected behavior
GIL should be released for all nontrivial operations. In particular, `cudaLaunchKernel` should never be called while holding the GIL, and we should think how to systematically test that. 

## Environment

Recent master build

cc @ezyang @gchanan @zou3519 @bdhirsh @mruberry

**Comment by mruberry** [comment]
Update from meeting offline: let's fix this and manually verify the fix, but we don't have a good idea for automated testing of this property at this time.

In the future we might be able to create a debug mode that verifies the GIL is not held when calling CUDA kernels, but that's a separate issue.
