### ISSUE TITLE
PyBind11 doesn’t recognize `torch._C.ScriptModule` as `torch::jit::Module`

### ISSUE THREAD

**Issue by codekansas** [pytorch/pytorch#68747]
## PyBind11 doesn’t recognize `torch._C.ScriptModule` as `torch::jit::Module`

I am trying to write a C++ extension for PyTorch

```cpp
torch::jit::script::Module preprocess(const torch::jit::script::Module& mod) {
  torch::jit::script::Module new_mod(mod._ivalue()->name() + "_txp");
  return new_mod;
}
```

When I call this from Python:

```python
script_model = torch.jit.load(cfg.model_file, map_location="cpu")
preprocessed_model = cpplib.preprocess(script_model._c)
```

I get an error like this:

```
TypeError: func_name(): incompatible function arguments. The following argument types are supported:
    1. (model: torch::jit::Module) -> torch::jit::Module

Invoked with: <torch._C.ScriptModule object at 0x7fc27d657770>
```

For reference, this works fine (can call the PyBind'd function with a tensor argument):

```cpp
torch::Tensor preprocess(const torch::Tensor& mod) { return mod; }

PYBIND11_MODULE(MODULE_NAME, m) { m.def("preprocess", &preprocess); }
```

Here's my CMake file:

```cmake
cmake_minimum_required(VERSION 3.12 FATAL_ERROR)

project(txp-cpp-backend LANGUAGES CXX C)

set(LIB_NAME cpp)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wformat")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=cpp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wformat-security")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fstack-protector")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DMODULE_NAME=lib${LIB_NAME}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -O3 -Wno-reorder")
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
find_package(PythonLibs REQUIRED)

find_library(TORCH_PYTHON_LIBRARY torch_python
             PATHS "${TORCH_INSTALL_PREFIX}/lib")
message(STATUS "TORCH_PYTHON_LIBRARY: ${TORCH_PYTHON_LIBRARY}")

add_library(${LIB_NAME} SHARED txp.cpp)

target_compile_features(${LIB_NAME} PRIVATE cxx_std_14)
set_target_properties(${LIB_NAME} PROPERTIES OUTPUT_NAME ${LIB_NAME})
set_target_properties(${LIB_NAME} PROPERTIES POSITION_INDEPENDENT_CODE ON)
set_target_properties(${LIB_NAME}
                      PROPERTIES LINK_FLAGS "-Wl,-rpath,${CMAKE_INSTALL_RPATH}")
target_compile_options(
  ${LIB_NAME} PUBLIC -Wall -Wno-sign-compare -Wno-unused-function
                     -Wno-unknown-pragmas)
target_include_directories(
  ${LIB_NAME}
  PUBLIC ${TORCH_INCLUDE_DIRS}
  PUBLIC ${PYTHON_INCLUDE_DIRS})
target_link_libraries(
  ${LIB_NAME}
  PUBLIC ${PYTHON_LIBRARIES}
  PUBLIC ${TORCH_LIBRARIES}
  PUBLIC ${TORCH_PYTHON_LIBRARY})
```

And my Torch version:

```python
>>> import torch; torch.__version__
'1.11.0.dev20211121'
```

When I try to manually adding

```cpp
#include <torch/csrc/jit/python/script_init.h>
```

I get this error

```
fatal error: torch/csrc/generic/Storage.h: No such file or directory
```

I made a post on the PyTorch forum [here](https://discuss.pytorch.org/t/pybind11-doesnt-recognize-torch-c-scriptmodule-as-torch-module/137367) but someone suggested making an issue instead.

**Comment by gmagogsfm** [comment]
Hi @codekansas,

Thanks for reporting this issue. Do you mind providing a PR with the minimal changes needed to reproduce? The code examples above don't seem to run (according to my best guesses where they should go). Thanks.

**Comment by codekansas** [comment]
hi @gmagogsfm , I've created an example repository [here](https://github.com/codekansas/torchscript-example) which reproduces the issue I described above

**Comment by codekansas** [comment]
It turns out I was missing some important `-DPYBIND11_` flags which were not included in the `find_package` directive... I've updated the example repo for posterity's sake

**Comment by hengyuan-hu** [comment]
Hey, @codekansas  I recently encountered the same problem. Can you please tell me how to fix it with the CMake? I tried adding 
`
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPYBIND11_COMPILER_TYPE=_gcc -DPYBIND11_STDLIB=_libstdcpp -DPYBIND11_BUILD_ABI=_cxxabi1011")
`

but then I got the following error:

`
lib/python3.7/site-packages/torch/include/pybind11/detail/internals.h: In function ‘pybind11::detail::internals& pybind11::detail::get_internals()’:
<command-line>: error: expected ‘)’ before ‘_gcc’
`

**Comment by hengyuan-hu** [comment]
Ok solved it. Turns out the quote marks have to present in the final make command and cannot be omitted. The correct way should be
`
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPYBIND11_COMPILER_TYPE=\\\"_gcc\\\" -DPYBIND11_STDLIB=\\\"_libstdcpp\\\" -DPYBIND11_BUILD_ABI=\\\"_cxxabi1011\\\"")
`
The example here is very helpful. Thanks a lot!
