### ISSUE TITLE
gradgrad of `nn.functional.prelu` is broken for noncontiguous inputs

### ISSUE THREAD

**Issue by saketh-are** [pytorch/pytorch#68760]
Relevant test marked as expected failure: https://github.com/pytorch/pytorch/pull/68521/files#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R10258

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @bdhirsh

**Comment by Lezcano** [comment]
cc @nikitaved in case you want to have a look at this one.
The current code for the second derivative looks unnecessarily difficult. I think it could be severely golfed down.

The code for the first derivative looks quite complex as well. It may probably be implemented more efficiently via `TensorIterator` in a few lines.

**Comment by Chillee** [comment]
If anybody wants to take a crack at this, here's a "decomposed" implementation of `prelu_backward` that might be easier to understand.

https://github.com/pytorch/functorch/blob/main/functorch/_src/decompositions.py#L125

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/6355099/154397593-43c597d1-3fdc-42f4-a99e-d872b3259248.png">

**Comment by Chillee** [comment]
I (actually) added a `prelu_backward` decomposition here: https://github.com/pytorch/functorch/blob/main/functorch/_src/decompositions.py#L126

The primary thing that makes it tricky is some annoying broadcasting logic:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/6355099/154417821-819320a5-21ca-42fa-a13b-810600081efc.png">

**Comment by pmeier** [comment]
Maybe I'm missing something, but PReLU is a piecewise linear function and thus its second order derivative should be zero everywhere? I'll look into this, since after #72705 the test passes just fine.

**Comment by pmeier** [comment]
The failure only happens for noncontiguous inputs:

```py
import torch
from torch.nn.functional import prelu

torch.manual_seed(1234)

shape = (5, 5)
input = torch.randn(5, 5, dtype=torch.float64, requires_grad=True)
weight = torch.randn(5, dtype=torch.float64, requires_grad=True)

torch.autograd.gradgradcheck(prelu, (input, weight), gen_non_contig_grad_outputs=False)  # passes

torch.autograd.gradgradcheck(prelu, (input, weight), gen_non_contig_grad_outputs=True)  # fails
```

**Comment by jbschlosser** [comment]
@pmeier Any update on this? Still unclear to me where the contiguity assumption is failing.

**Comment by pmeier** [comment]
@jbschlosser I've never looked in the op and just touched on this issue, because working on my PR made it clear, that the problem was misidentified here.

**Comment by nikitaved** [comment]
`prelu_backward` restrides weights as if they contiguous which, I guess, is not always correct.

**Comment by nikitaved** [comment]
`prelu_backward` broadcasts `weights` with the assumption of being contiguous. I guess, the issue is likely there.
