### ISSUE TITLE
the example of torch.empty_like is torch.empty

### ISSUE THREAD

**Issue by Freed-Wu** [pytorch/pytorch#68799]
## 📚 Documentation

In <https://pytorch.org/docs/stable/generated/torch.empty_like.html>,
the example code of torch.empty_like only contains torch.empty.

cc @brianjo @mruberry @gchanan

**Comment by mruberry** [comment]
Thanks for reporting this issue, @Freed-Wu. We would accept a PR updating the examples for empty_like
