### ISSUE TITLE
[ONNX] LSTM weight tensors: wrong dimensions

### ISSUE THREAD

**Issue by stgrue** [pytorch/pytorch#6879]
## Issue description

The [ONNX specification](https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-3---8) requires the following dimensions for the weight tensors `W`, `R`, and `B` of an LSTM:

`W`: `[num_directions, 4*hidden_size, input_size]` (rank 3)
`R`: `[num_directions, 4*hidden_size, hidden_size]` (rank 3)
`B`: `[num_directions, 8*hidden_size]` (rank 2)

However, when exporting an LSTM from PyTorch, the tensors used for the LSTM weights in the resulting model have the following dimensions:

`W`: `[num_directions*4*hidden_size, input_size]` (rank 2)
`R`: `[num_directions*4*hidden_size, hidden_size]` (rank 2)
`B`: `[num_directions*8*hidden_size]` (rank 1),

i.e. the weights for the different directions are concatenated, instead of being stored in separate dimensions. This does not conform to the specification.

## Code example

```python
import torch

inputs = torch.Tensor(5,1,3)
lstm = torch.nn.LSTM(3, 3, bidirectional=True) # Input dim = hidden dim = 3
out, hidden = lstm(inputs)  

torch.onnx.export(lstm, inputs, "lstm.onnx")
```

According to the specification, the weight tensors of the LSTM should have the following dimensions:

`W`: `[2, 12, 3]` (rank 3)
`R`: `[2, 12, 3]` (rank 3)
`B`: `[2, 24]` (rank 2)

However, inspecting `lstm.onnx` yields the following dimensions:

`W`: `[24, 3]` (rank 2)
`R`: `[24, 3]` (rank 2)
`B`: `[48]` (rank 1).

**Comment by houseroad** [comment]
@anderspapitto could you take a look?

**Comment by mathisdon** [comment]
I interpret the Bias spec to be saying that in a single direction LSTM, the Bias tensor should have dimensions

        [1, 4*hidden_size]

> B (optional) : T
> The bias tensor for input gate. Concatenation of `[Wb[iofc], Rb[iofc]]`, and `[WBb[iofc], RBb[iofc]]` (if bidirectional) along dimension 0. This tensor has shape `[num_directions, 8*hidden_size]`. Optional: If not specified - assumed to be 0.
