### ISSUE TITLE
torch.profiler.profile().export_stacks() never finishes.

### ISSUE THREAD

**Issue by sonsus** [pytorch/pytorch#68809]
## 🐛 Bug
<code>export_stacks()</code> never finishes its run

## To Reproduce

1. code to reproduce (envs will follow)
```python
import wandb
import torch
import torch.nn as nn
from fire import Fire
from tqdm import tqdm
from torch.profiler import profile, record_function, ProfilerActivity

class TestModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(10000, 10000)
    def forward(self, x):
        return self.layer(x)

def test_leak():
    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True) as prof:
        with record_function("I was trying to find the source of tremendous mem consumption"):
            # model(nn.Module) with just one layer 
            t = torch.randn(500,10000).to(torch.device('cuda'))
            m = TestModel().to(torch.device('cuda') )
            gt = torch.ones(500,10000).float().to(torch.device('cuda'))

            criterion = lambda x,y: (x-y).mean()
            opt = torch.optim.SGD(m.parameters(), lr=1e-4)

            opt.zero_grad()
            m.train()
            for i in tqdm(range(60000)):
                x = m(t)
                l = criterion(x,gt)
                l.backward()
                opt.step()
                opt.zero_grad()
    print(prof.key_averages().table(sort_by="cuda_time_total"))
    prof.export_stacks("./profiler_stacks.txt", "self_cuda_time_total")
    return

if __name__ == '__main__':
    Fire(test_leak)

================================    
...
..
.
                                  cudaDeviceSynchronize         0.07%     261.084ms         0.07%     261.084ms     261.084ms       0.000us         0.00%       0.000us       0.000us
          1
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------
Self CPU time total: 361.178s
Self CUDA time total: 243.494s

Traceback (most recent call last):
  File "/work/faithsumm_exp/test_profile.py", line 40, in <module>
    Fire(test_leak)
  File "/c/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/c/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/c/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/work/faithsumm_exp/test_profile.py", line 36, in test_leak
    prof.export_stacks("./profiler_stacks.txt", "self_cuda_time_total")
  File "/c/lib/python3.9/site-packages/torch/profiler/profiler.py", line 364, in export_stacks
    return self.profiler.export_stacks(path, metric)
  File "/c/lib/python3.9/site-packages/torch/autograd/profiler.py", line 246, in export_stacks
    assert self.with_stack, "export_stacks() requires with_stack=True"
AssertionError: export_stacks() requires with_stack=True
```
putting the print() line inside the first context (that is <code>with profile():</code>) will  result:

```python
RuntimeError("Profiler didn't finish running")
``` 

## Expected behavior

shouldn't this process finish normally leaving the exported stack file?

## Environment
Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-161-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.10.0+cu113
[conda] numpy                     1.21.4                   pypi_0    pypi
[conda] torch                     1.10.0+cu113             pypi_0    pypi

$nvidia-smi 
Driver Version: 470.57.02    CUDA Version: 11.4
$ conda-env export
```yaml
name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - brotlipy=0.7.0=py39h27cfd23_1003
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - chardet=4.0.0=py39h06a4308_1003
  - conda=4.10.3=py39h06a4308_0
  - conda-package-handling=1.7.3=py39h27cfd23_1
  - cryptography=3.4.7=py39hd23ed53_0
  - idna=2.10=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.3=py39h06a4308_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.5=h12debd9_4
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - setuptools=52.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - tzdata=2021a=h52ac0ba_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - backcall==0.2.0
    - blis==0.7.5
    - catalogue==2.0.6
    - click==8.0.3
    - configparser==5.1.0
    - cycler==0.11.0
    - cymem==2.0.6
    - cython==0.29.24
    - decorator==5.1.0
    - docker-pycreds==0.4.0
    - filelock==3.4.0
    - fire==0.4.0
    - fonttools==4.28.1
    - gitdb==4.0.9
    - gitpython==3.1.24
    - huggingface-hub==0.1.2
    - ipdb==0.13.9
    - ipython==7.29.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - jsonlines==2.0.0
    - kiwisolver==1.3.2
    - langcodes==3.3.0
    - markupsafe==2.0.1
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.3
    - munch==2.5.0
    - murmurhash==1.0.6
    - nltk==3.6.5
    - numpy==1.21.4
    - packaging==21.3
    - pandas==1.3.4
    - parso==0.8.2
    - pathtools==0.1.2
    - pathy==0.6.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - preshed==3.0.6
    - promise==2.3
    - prompt-toolkit==3.0.22
    - protobuf==3.19.1
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py-rouge==1.1
    - pycocoevalcap==1.2
    - pycocotools==2.0.2
    - pydantic==1.8.2
    - pygments==2.10.0
    - pyparsing==3.0.6
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - sacremoses==0.0.46
    - scipy==1.7.2
    - seaborn==0.11.2
    - sentry-sdk==1.5.0
    - setuptools-scm==6.3.2
    - shortuuid==1.0.8
    - smart-open==5.2.1
    - smmap==5.0.0
    - spacy==3.2.0
    - spacy-legacy==3.0.8
    - spacy-loggers==1.0.1
    - srsly==2.4.2
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - thinc==8.0.13
    - tokenizers==0.10.3
    - toml==0.10.2
    - tomli==1.2.2
    - **torch==1.10.0+cu113**
    - traitlets==5.1.1
    - transformers==4.12.5
    - typer==0.4.0
    - typing-extensions==4.0.0
    - wandb==0.12.7
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - yaspin==2.1.0
prefix: /c
```
## Additional context
is it expected that <code>prof.key_averages().table(sort_by="cuda_time_total"))</code> to consume additional memory? I thought it consumes too much (almost same memory as accumulated inside the loop).

cc @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by morganmcg1** [comment]
Hey @sonsus , this won't address your issue, but since you're using W&B you might find it handy to know that we now support the PyTorch profiler in W&B, colab [here](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch-lightning/Profile_PyTorch_Code.ipynb), blog post [here](https://wandb.ai/wandb/trace/reports/A-Public-Dissection-of-a-PyTorch-Training-Step--Vmlldzo5MDE3NjU?galleryTag=)

**Comment by sonsus** [comment]
> Hey @sonsus , this won't address your issue, but since you're using W&B you might find it handy to know that we now support the PyTorch profiler in W&B, colab [here](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/pytorch-lightning/Profile_PyTorch_Code.ipynb), blog post [here](https://wandb.ai/wandb/trace/reports/A-Public-Dissection-of-a-PyTorch-Training-Step--Vmlldzo5MDE3NjU?galleryTag=)

Thanks to know I can profile the code on wandb but I guess my code doesn't include any <code>wandb</code> except unused import at the top.

**Comment by robieta** [comment]
Thanks for the report. We're in the process of optimizing a lot of the internals of the profiler right now; I'll definitely make sure the export code gets some attention.

**Comment by rbavery** [comment]
I am also getting this error with this code in a torchserve container that otherwise works

```
        with profile(activities=[ProfilerActivity.CPU], profile_memory=True, record_shapes=True) as prof:
            with record_function("model_inference"):
                # Do some inference call to engine here and return output
                model_output = self.model.forward(model_input)
            print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=10))
            print(prof.key_averages().table(sort_by="self_cpu_memory_usage", row_limit=10))
                
```

results in

```
2023-02-27T22:28:22,072 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - Backend received inference at: 1677536902
2023-02-27T22:28:22,072 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - trying to open image
2023-02-27T22:28:26,985 [WARN ] W-9002-mdv5_1.0.0-stderr MODEL_LOG - [W CPUAllocator.cpp:305] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - Invoking custom service failed.
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/service.py", line 102, in predict
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     ret = self._entry_point(input_batch, self.context)
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/2021a28a64e44c93b28259dd0a590358/mdv5_handler.py", line 153, in handle
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     model_output = self.inference(model_input)
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/2021a28a64e44c93b28259dd0a590358/mdv5_handler.py", line 110, in inference
2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=10))
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/torch/profiler/profiler.py", line 375, in key_averages
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     return self.profiler.key_averages(group_by_input_shape, group_by_stack_n)
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/torch/autograd/profiler.py", line 250, in key_averages
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     self._check_finish()
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/torch/autograd/profiler.py", line 224, in _check_finish
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     raise RuntimeError("Profiler didn't finish running")
2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - RuntimeError: Profiler didn't finish running
```

**Comment by XapaJIaMnu** [comment]
> I am also getting this error with this code in a torchserve container that otherwise works
> 
> ```
>         with profile(activities=[ProfilerActivity.CPU], profile_memory=True, record_shapes=True) as prof:
>             with record_function("model_inference"):
>                 # Do some inference call to engine here and return output
>                 model_output = self.model.forward(model_input)
>             print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=10))
>             print(prof.key_averages().table(sort_by="self_cpu_memory_usage", row_limit=10))
>                 
> ```
> 
> results in
> 
> ```
> 2023-02-27T22:28:22,072 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - Backend received inference at: 1677536902
> 2023-02-27T22:28:22,072 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - trying to open image
> 2023-02-27T22:28:26,985 [WARN ] W-9002-mdv5_1.0.0-stderr MODEL_LOG - [W CPUAllocator.cpp:305] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - Invoking custom service failed.
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - Traceback (most recent call last):
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/service.py", line 102, in predict
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     ret = self._entry_point(input_batch, self.context)
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/2021a28a64e44c93b28259dd0a590358/mdv5_handler.py", line 153, in handle
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     model_output = self.inference(model_input)
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/2021a28a64e44c93b28259dd0a590358/mdv5_handler.py", line 110, in inference
> 2023-02-27T22:28:27,157 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     print(prof.key_averages().table(sort_by="cpu_time_total", row_limit=10))
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/torch/profiler/profiler.py", line 375, in key_averages
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     return self.profiler.key_averages(group_by_input_shape, group_by_stack_n)
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/torch/autograd/profiler.py", line 250, in key_averages
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     self._check_finish()
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/torch/autograd/profiler.py", line 224, in _check_finish
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG -     raise RuntimeError("Profiler didn't finish running")
> 2023-02-27T22:28:27,158 [INFO ] W-9002-mdv5_1.0.0-stdout MODEL_LOG - RuntimeError: Profiler didn't finish running
> ```

https://discuss.pytorch.org/t/getting-cant-export-a-trace-that-didnt-finish-running-error-with-profiler/109386

Move the print outside of the with block.

**Comment by sraikund16** [comment]
Closing as this does not seem true anymore
