### ISSUE TITLE
Recursive update in `ShardedTensor.state_dict` hook is inefficient

### ISSUE THREAD

**Issue by awaelchli** [pytorch/pytorch#68805]
## 🐛 Bug

When a module is composed of nested modules and a the model registers a state_dict hook for sharded tensors, the time to retrieve the state_dict increases exponentially with the depth of nesting. 

## To Reproduce

```python
from torch import nn
from torch.nn.modules.container import ModuleDict
from torch.distributed._sharded_tensor import state_dict_hook


class LitAutoEncoder(nn.Module):
    def __init__(self, depth):
        super().__init__()
        self.num_dict = depth

        def recursive_build_encoder(stop_num, current_num):
            if stop_num == current_num:
                return nn.Sequential(nn.Linear(current_num + 1, current_num + 1))
            else:
                module_dict = ModuleDict()
                module_dict[str(current_num)] = recursive_build_encoder(stop_num, current_num + 1)
                return module_dict

        self.encoder = recursive_build_encoder(depth, 0)

        # register state dict hook
        self._register_state_dict_hook(state_dict_hook)


# this does not terminate in a reasonable time!
enc = LitAutoEncoder(depth=100)
enc.state_dict()
```

This Python script will not terminate within a reasonable time. For very small numbers of `depth` it is not noticeable.

## Expected behavior

The state dict retrieval time should be linear in the number of submodules. 

### Possible fix

I believe the implementation of this function is inefficient as it redundantly recurses:

https://github.com/pytorch/pytorch/blob/c41d8290b382f90318cc5f2a90e48eaa37023571/torch/distributed/_sharded_tensor/__init__.py#L375-L382

From what I can tell, the recursion is not necessary, because `module.named_modules()` ALREADY returns all the nested submodules in a generator. I would instead propose this: 

```python
def _recurse_update_dict(module, destination, prefix):
    for submodule_name, submodule in module.named_modules():
        for attr_name, attr in module.__dict__.items():
            if isinstance(attr, ShardedTensor):
                destination[prefix + submodule_name + "." + attr_name] = attr
```

A similar issue exists in https://github.com/pytorch/pytorch/blob/c41d8290b382f90318cc5f2a90e48eaa37023571/torch/distributed/_sharded_tensor/__init__.py#L362-L372

## Environment

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.20.1
Libc version: N/A

Python version: 3.8.11 (default, Aug  6 2021, 08:56:27)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.15.7-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.5.0rc1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchmetrics==0.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl  
[conda] efficientnet-pytorch      0.6.3                    pypi_0    pypi
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.3.0           hecd8cb5_517  
[conda] mkl-service               2.4.0            py38h9ed2024_0  
[conda] mkl_fft                   1.3.0            py38h4a7008c_2  
[conda] mkl_random                1.2.2            py38hb2f4e1b_0  
[conda] mypy                      0.910                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.20.3           py38h4b4dc7a_0  
[conda] numpy-base                1.20.3           py38he0bd621_0  
[conda] pytorch                   1.10.0                  py3.8_0    pytorch
[conda] pytorch-lightning         1.5.0rc1                  dev_0    <develop>
[conda] segmentation-models-pytorch 0.2.0                    pypi_0    pypi
[conda] torchaudio                0.10.0                 py38_cpu    pytorch
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchtext                 0.11.0                   pypi_0    pypi
[conda] torchvision               0.11.1                 py38_cpu    pytorch

## Additional context

This issue was reported in PyTorch Lightning https://github.com/PyTorchLightning/pytorch-lightning/issues/10643

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by pritamdamania87** [comment]
@awaelchli Thanks for reporting this issue with a detailed analysis! I'll look into this.

**Comment by pritamdamania87** [comment]
Oh nvm, looks like you already have a PR: https://github.com/pytorch/pytorch/pull/68806, will review it soon :)
