### ISSUE TITLE
pytorch GPU version for Mac

### ISSUE THREAD

**Issue by Yuri-Su** [pytorch/pytorch#68811]
## 🚀 Feature
Is there any plan to launch amd GPU accelerated version for Mac
## Motivation
Mac is very popular with programmers, but it does not support GPU acceleration. Apple has launched its own graphics acceleration engine metal, which has been applied to tensorflow. I hope you can turn it over

cc @malfet @albanD

**Comment by Xylambda** [comment]
It is [planned](https://github.com/pytorch/pytorch/issues/47702#issuecomment-965625139) to add support for the M1 GPU. Go to [this issue](https://github.com/pytorch/pytorch/issues/47702) to check the full discussion.

**Comment by sheljoy** [comment]
Right now! Miniconda is ready to ox-arm64 channel 

https://repo.anaconda.com/pkgs/main/osx-arm64/
https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh

**Comment by mruberry** [comment]
This question is likely more suitable for the PyTorch Forums, but maybe @albanD knows a better place to direct it

**Comment by malfet** [comment]
Please note that metal acceleration of some of the PyTorch operators should already be available in 1.10

**Comment by albanD** [comment]
Some acceleration is already available and you can use the arm part of the processing already.
The BLAS library is using some of the neural core as well automatically under the hood.
For a more detailed discussion on the GPU side, let's keep the discussion in https://github.com/pytorch/pytorch/issues/47702 that has all the details.
