### ISSUE TITLE
torch.kthvalue returns random value when the k is invalid

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#68813]
## 🐛 Bug

`torch.kthvalue` returns a random value when the `k` is beyond the range, like `k=6` for `[0,1,2,]`. The document of this API
does not mention any about this randomly behavior, so I think it should raise an error to remind the users.

## To Reproduce

```python
import torch
arg_1 = torch.tensor([0,1,2,3,4])
arg_2 = 6
res1 = torch.kthvalue(arg_1,arg_2,)
res3 = torch.kthvalue(arg_1,arg_2,)
res2 = arg_1.kthvalue(arg_2,)
print(res1)
print(res2)
print(res3)
```

The result is
```python
torch.return_types.kthvalue(
values=tensor(65),
indices=tensor(65))
torch.return_types.kthvalue(
values=tensor(8315178049699258475),
indices=tensor(81))
torch.return_types.kthvalue(values=tensor(4423495177514940772),indices=tensor(4424065875907452991))
```

## Expected behavior

Raise an error.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0, 1.9.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.9.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: RTX 3090

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by mruberry** [comment]
Thanks for reporting this issue, @ilovepytorch. We would accept a fix for this.
