### ISSUE TITLE
ChainedScheduler get_last_lr not working

### ISSUE THREAD

**Issue by azrael417** [pytorch/pytorch#68820]
## 🐛 Bug

ChainedScheduler crashes when `get_last_lr()` is called because ChainedScheduler does not have a `_last_lr` member.

## To Reproduce

1. Create a chained scheduler with any base schedulers
2. perform a step
3. call call get_last_lr()

It will print

```
Traceback (most recent call last):
  File "/opt/ERA5_wind/scheduler.py", line 19, in <module>
    print(scheduler.get_last_lr())
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 99, in get_last_lr
    return self._last_lr
AttributeError: 'ChainedScheduler' object has no attribute '_last_lr'
```

## Expected behavior

It should print the last learning rate. A potential fix would be:

```
self._last_lr = [group['lr'] for group in self._schedulers[-1].optimizer.param_groups]
```

## Environment

Collecting environment information...
PyTorch version: 1.10.0a0+b6df043
Is debug build: False
CUDA used to build PyTorch: 11.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.4.0-119-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] nvidia-dlprof-pytorch-nvtx==1.6.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.10.0a0+b6df043
[pip3] torchtext==0.11.0a0
[pip3] torchvision==0.11.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.21.3           py38he2449b9_0    conda-forge
[conda] nvidia-dlprof-pytorch-nvtx 1.6.0                    pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.10.0a0+b6df043          pypi_0    pypi
[conda] torchtext                 0.11.0a0                 pypi_0    pypi
[conda] torchvision               0.11.0a0                 pypi_0    pypi

## Additional context

This is run in the current Nvidia NGC DLFW pytorch 21.10 container.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @vincentqb @albanD @malfet @rgommers @xuzhao9 @gramster

**Comment by malfet** [comment]
@malfet we should add this one to mypy-strict list to prevent it from happening again

**Comment by kurtamohler** [comment]
Here's a minimum reproducer:

```python
import torch

model = [torch.nn.parameter.Parameter(torch.randn(2, 2, requires_grad=True))]
optimizer = torch.optim.SGD(model, 0.1)
scheduler1 = torch.optim.lr_scheduler.ConstantLR(optimizer, factor=0.1, total_iters=2)scheduler2 = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.9)
scheduler = torch.optim.lr_scheduler.ChainedScheduler([scheduler1, scheduler2])
scheduler.step()
scheduler.get_last_lr()
```
