### ISSUE TITLE
[checkpoint] Handle requires_grad not explicitly set for checkpoint inputs

### ISSUE THREAD

**Issue by prigoyal** [pytorch/pytorch#6884]
Currently, if the model has one input only (excluding the parameters), then the user needs to set requires_grad=True for backwards to work. This is needed because checkpointing function is an autograd function with no learnable parameters itself. In general, users shouldn't need to set requires_grad=True for the models written using pytorch modules. 

proper way to handle this is not known yet.

**Comment by ngimel** [comment]
closing due to age
