### ISSUE TITLE
[PyTorch] Add torch.astensor and deprecate torch.from_numpy

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#6885]
I believe it would be a good addition to add a new factory function, `torch.astensor`, which is equivalent to `torch.tensor`, but which doesn't perform a copy if possible. This means that passing a `torch.Tensor` returns a view of the same tensor, and passing a numpy array would have a behavior similar to `torch.from_numpy`.

This means that we could potentially have a call on `torch.astensor` in the beginning of every function, as a way of supporting other data types than torch tensors for torch operations.

For example
```python
# in torch namespace
def exp(x):
    x = torch.astensor(x)
    return x.exp()

# can now call `exp` on floats, lists, arrays
torch.exp(1.0)
torch.exp([1.0, 2.0])
torch.exp(np.array([1.0, 2.0]))
```

Given that `torch.tensor` infers the type of the tensor from the content of the data we pass to it, we could then probably deprecate `torch.from_numpy` in favor if this unified constructor.

What do you think?

**Comment by arogozhnikov** [comment]
I believe that role of this function is similar to `numpy.asarray`. In this case I see a reason to use original name, for instance:

```python
def make_computations(x, backend=np):
    x = backend.asarray(x)
    return backend.log(backend.exp(x).sum()) # some complex computations instead of this
```

This trick was particularly useful for theano, when same function could be used with numpy and theano.

**Comment by fmassa** [comment]
This function has already been implemented in https://github.com/pytorch/pytorch/pull/7109

Given that we implement `__array_wrap__` and `__wrap_array__`, it's totally possible to write the following code in PyTorch

```python
a = torch.rand(4)
b = np.sin(a)  # returns a torch tensor!
```
so as long as the underlying operations are respect the `__array_wrap__` API, I think having the same name as numpy is not a hard-requirement.

Also I'm closing this issue because it has already been fixed in the aforementioned PR.
