### ISSUE TITLE
reduction parameter in nn.NLLLoss() depricated?

### ISSUE THREAD

**Issue by felixschltr** [pytorch/pytorch#68872]
## Issue description

When trying to use the optional `reduction` parameter for `nn.NLLLoss()`, I get the following error: 
`TypeError: forward() got an unexpected keyword argument 'reduction'`

Interestingly, when I set `loss_fn = torch.nn.functional.nll_loss`, the code works as expected, i.e. using the `reduction='sum'` does not throw an error. 

Any thoughts, suggestions what may produce this behavior?

Thanks in advance

## Code example
This is the code I try to run:
```
import torch
loss_fn = torch.nn.NLLLoss()
inputs, targets = next(iter(dataloader))
device = 'cuda' if torch.cuda.is_available() else 'cpu'
inputs, targets = inputs.to(device), targets.to(device)
model = model.to(device)
logits = model(inputs)
loss = loss_fn(logits, targets, reduction='sum').item()
```
This is the error stack it produces:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-66-9bf7fc03282e> in <module>
      6 model = model.to(device)
      7 logits = model(inputs)
----> 8 loss = loss_fn(logits, targets, reduction='sum').item()

/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

TypeError: forward() got an unexpected keyword argument 'reduction'
```

## System Info
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.0 (default, Oct 28 2019, 16:14:01)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-132-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] pytorch-sphinx-theme==0.0.19
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0
[pip3] torchvision==0.8.1
[conda] Could not collect

**Comment by ejguan** [comment]
You should provide `reduction` to the constructor of `nn.NLLLoss` rather than forward function.
```py
loss_fn = torch.nn.NLLLoss(reduction='sum')
...
```

**Comment by felixschltr** [comment]
Thank you for the quick answer @ejguan !
