### ISSUE TITLE
Tensor.copy_ to a slice fails silently

### ISSUE THREAD

**Issue by andrewilyas** [pytorch/pytorch#68894]
## 🐛 Bug

When using `.copy_` on a slice of a tensor, no error is thrown but no data is copied. This is true across both CPU and GPU tensors. 

My ultimate goal here is to (asynchronously) copy data from a GPU tensor directly onto a pinned-memory CPU tensor---the ``index_copy_`` function works as expected but does not have a ``non_blocking`` flag and also requires all tensors to already be on the same device.

Separately though, it seems like the code below should either copy the data or throw an error/warning about copying to a slice not being supported. 

## To Reproduce

```
import torch as ch

table = ch.zeros(100, 100)
x = ch.randn(100, 100)
inds = ch.arange(100)

print(a_table[inds])
table[inds].copy_(x, non_blocking=False)
print(a_table[inds])
```

Both prints return an all-zeros matrix.

## Expected behavior

Either the data should be copied (and the second print should show real data), or an error/warning should be thrown.

## Environment

```
Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-153-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: A100-PCIE-40GB
GPU 1: A100-PCIE-40GB
GPU 2: A100-PCIE-40GB
GPU 3: A100-PCIE-40GB
GPU 4: A100-PCIE-40GB
GPU 5: A100-PCIE-40GB
GPU 6: A100-PCIE-40GB
GPU 7: A100-PCIE-40GB
GPU 8: A100-PCIE-40GB

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] pytorch-lightning==1.2.6
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] libblas                   3.9.0            11_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            11_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            11_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            11_linux64_mkl    conda-forge
[conda] magma                     2.5.4                h6103c52_2    conda-forge
[conda] mkl                       2021.3.0           h06a4308_520
[conda] numpy                     1.21.1           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchmetrics              0.6.0                    pypi_0    pypi
[conda] torchvision               0.11.1               py39_cu113    pytorch
```

## Additional context

In case copying to a slice is not supported, I would love advice on how to copy data from a GPU tensor onto a slice of a pinned-memory CPU tensor without blocking in either location.

**Comment by ngimel** [comment]
This is expected behavior, `table[inds]` is not a view into original tensor, it returns a new tensor with its own storage, and you are copying into it. To get the behavior you want, if you need `inds` to be a tensor you can use augmented assignment:
`table[inds]=x`, or, if it's truly just a slice, use a slice notation, e.g. : `table[:100]=x`

**Comment by GuillaumeLeclerc** [comment]
So:
```
table[0:1]
```
doesn't make a copy but
```
table[0]
```
does ?

This is inconsistent with numpy and for sure will trigger copy/memory allocation in many situations for people not aware of this. Any rational reason behind this design choice?

**Comment by andrewilyas** [comment]
Thanks!
