### ISSUE TITLE
Python version is 3.7.11 in latest pytorch docker image

### ISSUE THREAD

**Issue by orilevari** [pytorch/pytorch#68901]
## 🐛 Bug

When pulling the latest pytorch docker image (pytorch/pytorch:latest), the python version it is configured with is 3.7.11, but it is documented in the Dockerfile to use python 3.8. I encountered this when updating my own Dockerfile that is based off of pytorch's Dockerfile to be the latest pytorch version. I previously was using pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime, which had a python version of 3.8.5.

## To Reproduce

docker run --it pytorch/pytorch:latest
python --version
output: 3.7.11

## Expected behavior

output: 3.8.x

 I found this issue because it caused a python version incompatibility error when deploying my container. Thanks in advance!

**Comment by Chris-hughes10** [comment]
Hi, I am also having this problem. Is there any update on the status for this? Additionally, more documentation on the PyTorch docker images generally would be welcomed!

**Comment by matifali** [comment]
same issue.

**Comment by mattcleigh** [comment]
bug is still present
