### ISSUE TITLE
`torch.jit.freeze` and `torch::jit::freeze` are inconsistent

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [pytorch/pytorch#68903]
## 🐛 Bug

In [Python](https://github.com/pytorch/pytorch/blob/4afa5ea0ab778be9bc50f3fe48890bc3c0580aaa/torch/jit/_freeze.py#L117)'s `torch.jit.freeze`:
```python
preserved_attrs = preserved_attrs if preserved_attrs is not None else []

out = RecursiveScriptModule(torch._C._freeze_module(mod._c, preserved_attrs))
RecursiveScriptModule._finalize_scriptmodule(out)
run_frozen_optimizations(out, optimize_numerics)

return out
```

In [C++](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/api/module.cpp#L479)'s `torch::jit::freeze`, on the other hand, the frozen graph optimizations (`torch._C._jit_pass_optimize_frozen_graph`/`OptimizeFrozenGraph`— which are the same, see [here](https://github.com/pytorch/pytorch/blob/ab1d879b33bae968e22e098b0e6aa01af821efe2/torch/csrc/jit/python/init.cpp#L380)) are run on the *input* module, rather than the frozen one:
```c++
Module out_mod = freeze_module(module, preserved_attrs.value_or(std::vector<std::string>({})));
auto graph = module.get_method("forward").graph();
OptimizeFrozenGraph(graph, optimize_numerics);
return out_mod;
```

While this might be correct— I'm not sure if modules are frozen in-place in C++, in which case `out_mod` and `module` would be the same object — it seemed like it might be a logic error.

## Expected behavior

The frozen graph should be optimized.

**Comment by ysc3839** [comment]
It is a bug. Because `freeze_module` clones the module and return the cloned one.
https://github.com/pytorch/pytorch/blob/b0fdca885547efedddc4e9cfe78a5e0d7838e9f0/torch/csrc/jit/passes/freeze_module.cpp#L871-L883

**Comment by suo** [comment]
cc @eellison, @Krovatkin can you take a look?

**Comment by Linux-cpp-lisp** [comment]
@Gamrix just to confirm what I'm seeing here: this was still broken in 1.10, but will be fixed in 1.11?

**Comment by Gamrix** [comment]
That is correct. This is shipping with the 1.11 release.

**Comment by Linux-cpp-lisp** [comment]
@Gamrix great, thank you for the confirmation and the work to resolve this issue.
