### ISSUE TITLE
[feature request] the derivative for 'eig' is not implemented 

### ISSUE THREAD

**Issue by zorrocai** [pytorch/pytorch#6890]
It seems that the derivative for 'eig' is not implemented in torch 0.3.1 .post2.
How could I use the derivate for 'eig'?

**Comment by soumith** [comment]
please fill out the issue description, otherwise we dont know how to help you. thanks.

**Comment by divyanshj16** [comment]
I want to take this issue. 
Where should I start @soumith ?

**Comment by apaszke** [comment]
Almost all the work should be contained in `tools/autograd/derivatives.yaml` and `tools/autograd/templates/Functions.cpp`.

**Comment by divyanshj16** [comment]
Thanks for guiding me. I am working on this.

**Comment by fmassa** [comment]
@divyanshj16 nice! Which differentiation formula are you using for `eig`?

**Comment by divyanshj16** [comment]
@fmassa I haven't figured out yet! I am revising linear algebra atm xD

**Comment by t-vi** [comment]
Note that eig currently does funny (undefined?) stuff for matrices with non-real eigenvalues (see #4533). This may or may not affect the stability.

**Comment by t-vi** [comment]
Note that for imaginary eigenvalues, `torch.eig` only returns the real part of the eigenvectors. (Apologies for the inaccurate earlier comment.)

**Comment by black0017** [comment]
Hi I also try to use torch.eig() to compute the eigenvalues and eigenvectors that I want to use in a custom forward layer. In pytorch version 0.3 i get None in the derivative values when I print them and in pytorch version 0.4  i get this ( RuntimeError: the derivative for 'eig' is not implemented).

Can someone help me plz ? :P 
Thanks in advance.
