### ISSUE TITLE
[docs] {select, slice, diagonal}_scatter not available in documentation

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#68928]
Ops added in #64430 are documented in `_torch_docs` and `_tensor_docs` but not registered for doc generation in `torch.rst` and `tensor.rst`. I don't think this was intended as the op names are not prefixed with `_`.

cc: @bdhirsh 

cc @brianjo @mruberry

**Comment by mruberry** [comment]
We would accept a PR fixing the docs
