### ISSUE TITLE
[Bug] TensorFromBlob on data created from CUDA Driver API Fails

### ISSUE THREAD

**Issue by Wapaul1** [pytorch/pytorch#6892]
## Issue description

If you allocate memory on the GPU using `cuMemAlloc`, then `tensorFromBlob` will fail on it. If you use `cudaMalloc`, it will succeed. 

More generally, is the CUDA Driver API actually supported in Pytorch, or is it only the Runtime API? The actual error appears to occur when `cudaPointerGetAttributes` is called on the data pointer. 

## Code example

Using `cpp_extension`, if you have the following C++ code:

```c++
#include <torch/torch.h>
#include <cuda.h>
#include <cuda_runtime.h>

using namespace at;
using namespace std;

Tensor load() {
  CUdeviceptr data_done;
  CUdevice handle;
  cuDeviceGet(&handle, 0);
  CUcontext context_;
  cuCtxCreate(&context_, 0, handle);
  CUresult err = cuMemAlloc(&data_done, 16*sizeof(float));
  auto f = torch::CUDA(kFloat).tensorFromBlob(reinterpret_cast<void*>(data_done), {16});
  return f;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("load", &load, "load data");
}

```
Then when `load` is called in python, it will fail with:
```python
THCudaCheck FAIL file=/home/devbox/projects/pytorch/aten/src/THC/generic/THCStorage.c line=150 error=49 : incompatible driver context
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-e8b40809576d> in <module>()
----> 1 pyt.load()

RuntimeError: cuda runtime error (49) : incompatible driver context at /home/devbox/projects/pytorch/aten/src/THC/generic/THCStorage.c:150
```
However, if you use `cudaMalloc` as below, then it will succeed:
```c++
#include <torch/torch.h>
#include <cuda.h>
#include <cuda_runtime.h>

using namespace at;
using namespace std;

Tensor load() {
  CUdeviceptr data_done;
  cudaError_t err2 = cudaMalloc(reinterpret_cast<void**>(&data_done), 16*sizeof(float));
  auto f = torch::CUDA(kFloat).tensorFromBlob(reinterpret_cast<void*>(data_done), {16});
  return f;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("load", &load, "load data");
}

```
## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): python setup.py install
- OS: Linux Mint 18.2 Sonya
- PyTorch version: 0.4.0a0+c43c911
- Python version: 3.6
- CUDA/cuDNN version: 9.1.85, no cuDNN
- GPU models and configuration: GTX 970
- GCC version (if compiling from source): 5.4.0 20160609
- CMake version: 3.5.1
- Versions of any other relevant libraries:

**Comment by apaszke** [comment]
We do depend on `cudaPointerGetAttributes` pretty heavily, so unless the driver APIs don't tag the pointers correctly, you won't be able to wrap them into tensors. Is there any reason why you can't use the runtime API? Also, all other driver functions should be ok to use (we use some of them internally too).

**Comment by ngimel** [comment]
closing due to age
