### ISSUE TITLE
`torch.broadcast_shapes` should not handle shape with negative dimension

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#68957]
## 🐛 Bug

When the shape is negative, `torch.broadcast_shapes` works normal. But based on its documentation that `torch.broadcast_shapes(*shapes)` is equivalent with `torch.broadcast_tensors(*map(torch.empty, shapes))[0].shape`, it should raise an error when the dimension is negative.

## To Reproduce

```python
import torch
shapes = [1, -12]
res1 = torch.broadcast_shapes(*shapes)
print(res1)
res2 = torch.broadcast_tensors(*map(torch.empty, shapes))[0].shape
```

Result is
```
torch.Size([-12])
RuntimeError: Trying to create tensor with negative dimension -12: [-12]
```

## Expected behavior

`torch.broadcast_shapes` should raise an error.

## Environment

- PyTorch Version (e.g., 1.0): 1.10.0, 1.9.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.9.5
- CUDA/cuDNN version: 11.1
- GPU models and configuration: RTX 3090

**Comment by ilovepytorch** [comment]
Is there any update?

**Comment by khushi-411** [comment]
It seems an exciting issue. I'd love to work on the same. Thanks! :)
