### ISSUE TITLE
Why we need contiguous method?

### ISSUE THREAD

**Issue by mttbx** [pytorch/pytorch#6895]
Hi,
   I really don't know why do we really need contiguous method? We can automatically call contiguous before view, so that it can hide this information to api user

**Comment by fmassa** [comment]
With the latest version in master, we have `.reshape` which is roughly equivalent to `.contiguous().view()`. This removes the main use-case that we have (for end users) to call `.contiguous()`.

I think over time we will gradually reduce the need of `.contiguous()` to be applied by the end-user, even though it will still exist in the backend implementation, as it simplifies implementation.
