### ISSUE TITLE
No AdaptiveAvg2dPool in Libtorch1.3?

### ISSUE THREAD

**Issue by X1anWang** [pytorch/pytorch#68964]
I use Libtorch 1.3 and give the right libtorch path when cmake the program. But I got the error that **AdaptiveAvgPool2d does not name a type**. I also check the source code of Libtorch 1.3 and **did not find AdaptiveAvgPool2d in /torch/nn**. So,

- 1) Don't Libtorch 1.3 have AdaptiveAvgPool2d?
- 2) Is there any substitude or solution to this issue?

Thanks!

cc @ezyang @seemethere @malfet @jbschlosser @bhosmer @bdhirsh

**Comment by malfet** [comment]
> 1. Don't Libtorch 1.3 have AdaptiveAvgPool2d?

No, LibTorch 1.3 does not have `adaptive_max_pool2d`, but LibTorch-1.4 does:
https://github.com/pytorch/pytorch/blob/74044638f755cd8667bedc73da4dbda4aa64c948/torch/csrc/api/include/torch/nn/functional/pooling.h#L291

> * 2. Is there any substitude or solution to this issue?

Use newer version of LibTorch

**Comment by malfet** [comment]
Closing, as this does not look like a issue with PyTorch but rather a general question about PyTorch C++ API usage. 
Please use https://discuss.pytorch.org/ for general questions about PyTorch and do not hesitate to reopen if you believe it is an issue in the latest release or on master.
