### ISSUE TITLE
torch.cuda.set_device documentation misleading

### ISSUE THREAD

**Issue by namespace-Pt** [pytorch/pytorch#68973]
## 📚 Documentation
In the documentation of [`torch.cuda.set_device`](https://pytorch.org/docs/1.10.0/generated/torch.cuda.set_device.html?highlight=set_device#torch.cuda.set_device), it says 

> Usage of this function is discouraged in favor of device. In most cases it’s better to use CUDA_VISIBLE_DEVICES environmental variable.

However, in case one is using DDP and attempts to **gather objects across gpus (no matter whether this object contains gpu tensors) by `torch.distributed.all_gather_object`**, it is critical to set the device to `local_rank` by this function (only set `os.environ` is not enough); otherwise the program would stuck and no error is raised. 

Although you slightly mentioned this requirement in the doc of [`all_gather_object`](https://pytorch.org/docs/1.10.0/distributed.html?highlight=all_gather#torch.distributed.all_gather_object), I think it is not enough for readers to have a comprehensive view of this function if it were not mentioned in the function's documentation. I think you should include this feature in the main page of `torch.cuda.set_device` documentation.  

cc @brianjo @mruberry @ngimel

**Comment by mruberry** [comment]
Thank you for the suggestion, @namespace-Pt. We would accept a PR improving the documentation.

**Comment by namespace-Pt** [comment]
Do you suggest I initiate a PR that improves the documentation?

**Comment by mruberry** [comment]
> Do you suggest I initiate a PR that improves the documentation?

Documentation is a little tricky to write but sure, if you'd like to submit a PR that'd be great. We'd welcome an improvement from any member of the PyTorch community.
