### ISSUE TITLE
`torch.dsplit` will crash when `sections = 0`

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#68970]
## 🐛 Bug

When `sections = 0`. `torch.dsplit(tensor, sections)` will crash. It is supposed to raise an error like `torch.tensor_split` that `number of sections must be larger than 0, got 0`

## To Reproduce

```python
import torch
tensor = torch.rand(torch.Size([2, 2, 4]), dtype=torch.float32)
sections = 0
res1 = torch.dsplit(tensor, sections)
```

It will crash.

## Expected behavior

Raise an error like `torch.tensor_split` that `number of sections must be larger than 0, got 0`

## Environment

- PyTorch Version (e.g., 1.0): 1.10.0, 1.9.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.9.5
- CUDA/cuDNN version: 11.1
- GPU models and configuration: RTX 3090

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by mruberry** [comment]
Let's track all these in https://github.com/pytorch/pytorch/issues/69270
