### ISSUE TITLE
default dtype is incorrectly set to torch.double when running test_ops.py

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68972]
Imports into test files should not be setting the default dtype. We should add asserts to the test files after imports that the default dtype is float32. 

@eellison maybe leaking from a jit include? 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry

**Comment by malfet** [comment]
Should we add lint for that one?

**Comment by kurtamohler** [comment]
Adding this to `set_default_dtype()` in `torch/__init__.py`:

```python
print(f'd = {d}')
import traceback
traceback.print_stack()
```

and then running `test_ops.py`, I get this trace:

```
d = torch.float64
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/test/test_ops.py", line 21, in <module>
    from torch.testing._internal.jit_metaprogramming_utils import create_script_fn, create_traced_fn, \
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/testing/_internal/jit_metaprogramming_utils.py", line 22, in <module>
    torch.set_default_dtype(torch.double)
  File "/work2/kurtamohler/development/pytorch-storage-virtualization/torch/__init__.py", line 372, in set_default_dtype
    traceback.print_stack()
```

So it comes from here: https://github.com/pytorch/pytorch/blob/3bd7dbf1196fcdd327ec09993444d5c1f5b8757f/torch/testing/_internal/jit_metaprogramming_utils.py#L22

**Comment by kurtamohler** [comment]
Perhaps a solution could be to create initialization functions for `nn_functional_tests` and `additional_module_tests` in `pytorch/torch/testing/_internal/jit_metaprogramming_utils.py`. The initialization functions could be run upon import and they would temporarily switch the default dtype within the context of those functions, and then switch it back to the original default dtype when they return.

**Comment by mruberry** [comment]
Switching the default dtype within each test seems OK but in general mucking with these globals isn't great because people do like to run the tests in parallel using pytest. So bonus points if we can eliminate the need to run the tests with the default datatype being double (which is a very unusual user config).

**Comment by kurtamohler** [comment]
That makes sense. It should be possible to set the dtypes for everything locally. I can work on it

**Comment by kit1980** [comment]
@kurtamohler should we revive this?

**Comment by ezyang** [comment]
Yes, if we can eliminate `set_default_dtype` from the entire test suite this would be extremely useful.

**Comment by kurtamohler** [comment]
Yeah I still plan to fix up the remaining issues with my PR. I'll try to get to it in the next week or two

**Comment by kit1980** [comment]
@kurtamohler I wonder if there is still interest in this?

**Comment by kurtamohler** [comment]
Yeah, I can pick this up again. I had a lot of merge conflicts along the way while working on it and didn't have the bandwidth to fix them at the time

**Comment by kurtamohler** [comment]
There are still some test files that call `torch.set_default_dtype` at the global scope:

```
$ git grep -n -w '^torch\.set_default_dtype' test
test/distributed/test_data_parallel.py:22:torch.set_default_dtype(torch.double)
test/distributions/test_distributions.py:43:torch.set_default_dtype(torch.double)
test/test_cpp_api_parity.py:5:torch.set_default_dtype(torch.double)
test/test_linalg.py:39:torch.set_default_dtype(torch.float32)
test/test_matmul_cuda.py:29:torch.set_default_dtype(torch.float32)
test/test_ops_fwd_gradients.py:13:torch.set_default_dtype(torch.float32)
test/test_ops_gradients.py:14:torch.set_default_dtype(torch.float32)
test/test_ops_jit.py:19:torch.set_default_dtype(torch.float32)
```

I'll continue working on removing them and then I'll add checks to the `setUp` and `tearDown` methods of  `TestCase` in `torch/testing/_internal/common_utils.py` to ensure that the default dtype is always float32 before and after tests are run

**Comment by kurtamohler** [comment]
Reopening because #107246 was reverted
