### ISSUE TITLE
Graph API crashing when allocating memory

### ISSUE THREAD

**Issue by dabeschte** [pytorch/pytorch#68985]
## 🐛 Bug

I tried to use the graph API with my custom CUDA kernels. For them to work, I allocate memory using torch.empty before calling the kernel.
This call raises an exception while capturing the graph that asked me to report the bug to PyTorch, so I happily report it here ;)

From what I understand, the Graph API reuses the same kernel parameters every time, and therefore also the same memory addresses.
Does that mean that I have to allocate the memory for all layers in my network first before capturing the graph?
If that is the case, I would still suggest to handle this case explicitly by improving the error message.

## To Reproduce

1. Define a layer that allocates memory
2. Record the graph according to [Blog](https://pytorch.org/blog/accelerating-pytorch-with-cuda-graphs/)

### Stack trace 
```
  File "foo.py", line 31, in bar
    out = torch.empty((out_b, out_c, out_h, out_w), dtype=torch.float32, device="cuda")
RuntimeError: status != cudaStreamCaptureStatus::cudaStreamCaptureStatusInvalidatedINTERNAL ASSERT FAILED at "..\\c10\\cuda\\CUDACachingAllocator.cpp":978, please report a bug to PyTorch. 
```

the parameters were `out_b=1 out_c=32 out_h=320 out_w=320 x.dtype=torch.float32 x.device=device(type='cuda', index=0)`

## Expected behavior

No crash or a better error message explaining why this did not work

## Environment

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.2
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 496.76
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] mypy_extensions           0.4.3            py39haa95532_0
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.20.3           py39hc2deb75_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.9.1                    pypi_0    pypi
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchcsr                  0.0.0                    pypi_0    pypi
[conda] torchdeltacnn             0.0.0                    pypi_0    pypi
[conda] torchvision               0.10.1                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mcarilli

**Comment by soulitzer** [comment]
Marking as high-prio because internal assert is being triggered

**Comment by mcarilli** [comment]
I'm not sure exactly what you're trying to do, can you post a minimal runnable repro? Generally if the graph needs memory, you should just allocate it during capture as usual, or if some inputs from outside capture are used during capture, make sure you manually hold onto them.
See https://pytorch.org/docs/master/notes/cuda.html#whole-network-capture, https://pytorch.org/docs/master/notes/cuda.html#graph-memory-management

**Comment by dabeschte** [comment]
Thank you for the quick response.

I reimplemented it again (deleted previous version as it did not work) and I did not get the same error this time...not entirely sure why.
But I can say that in my opinion [this blog post](https://pytorch.org/blog/accelerating-pytorch-with-cuda-graphs/) (which is the one that I followed) is wrong. In the first code snippet, the graph is replayed before finishing recording and this triggers an exception as well.

After following your examples, I was able to get parts of the network to run successfully.

**Comment by gmlwns2000** [comment]
I encountered the same issue, however, I could fix the issue by giving stream object explicitly.

```
self.cugraph_inputs = batch['inputs'].clone()
self.cugraph_labels = batch['labels'].clone()

self.cugraph_s = torch.cuda.Stream()
self.cugraph_s.wait_stream(torch.cuda.current_stream())
with torch.cuda.stream(self.cugraph_s):
    for i in range(128):
        output = self.base_model(inputs=self.cugraph_inputs, labels=self.cugraph_labels)
        loss = output['loss']
        loss.backward()
torch.cuda.current_stream().wait_stream(self.cugraph_s)

self.cugraph_graph = torch.cuda.CUDAGraph()
# Sets grads to None before capture, so backward() will create
# .grad attributes with allocations from the graph's private pool
for param in self.base_model.parameters():
    param.grad = None
with torch.cuda.graph(self.cugraph_graph, **stream=self.cugraph_s**):    <---------------- Where I change. I submit the stream explicitly. And finally the stream does not freed because of GC.
    self.cugraph_output = self.base_model(inputs=self.cugraph_inputs, labels=self.cugraph_labels)
    self.cugraph_loss = self.cugraph_output['loss']
    self.cugraph_loss.backward()
```
