### ISSUE TITLE
Pytorch - ONNX graph creation error (in SummaryWriter add_graph) when using Upsampling bilinear mode

### ISSUE THREAD

**Issue by mathmanu** [pytorch/pytorch#6900]
- PyTorch
- OS: Ubuntu 14.04
- PyTorch version: (0.4) nightly build 2018.04.18 from conda
- CUDA/cuDNN version: CUDA 8, CUDNN 7
- GPU models and configuration: GTX 1080 Ti
- Versions of any other relevant libraries: tensorboardx 1.0

@SsnL, @soumith while we are discussing Upsampling, I would like to describe the following error that I get when I try to write an ONNX graph using SummaryWriter's add_graph() function. 'nearest' Upsampling has no issue, but 'bilinear' Upsampling causes this issue.

/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py:1762: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
"See the documentation of nn.Upsample for details.".format(mode))
=> Train Epoch [1/300]: 2%|\u258f | 1/62 [00:20<20:41, 20.36s/it, DataTime=7.515 (Avg:7.515), LR=0.001, Loss=11.365 (Avg:11.365), Output=0.014 (Avg:0.014)(mIoU)]/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py:365: UserWarning: ONNX export failed on ATen operator hardtanh because torch.onnx.symbolic.hardtanh does not exist
.format(op_name, op_name))
Traceback (most recent call last):
File "train_segmentation.py", line 93, in 
main_segmentation.main(cmd)
File "../modules/tools/main_segmentation.py", line 192, in main
train_loss, train_metric, metric_name = train(args, train_dataset, train_loader, model, optimizer, epoch, train_writer, scheduler.get_lr()[0])
File "../modules/tools/main_segmentation.py", line 295, in train
train_writer.add_graph(model, input_zero)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/writer.py", line 400, in add_graph
self.file_writer.add_graph(graph(model, input_to_model, verbose))
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/graph.py", line 48, in graph
torch.onnx._optimize_trace(trace, False)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/init.py", line 30, in _optimize_trace
trace.set_graph(utils._optimize_graph(trace.graph(), aten))
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py", line 95, in _optimize_graph
graph = torch._C._jit_pass_onnx(graph, aten)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/init.py", line 40, in _run_symbolic_function
return utils._run_symbolic_function(*args, **kwargs)
File "/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py", line 368, in _run_symbolic_function
return fn(g, *inputs, **attrs)
TypeError: upsample_bilinear2d() got an unexpected keyword argument 'align_corners' (occurred when translating upsample_bilinear2d)

**Comment by SsnL** [comment]
Claiming as I wrote this. 

We should really have guidelines for how to change function signatures without breaking onnx and sufficient tests too.

**Comment by mathmanu** [comment]
@SsnL kindly let me know if you have pytorch-nightly that fixes it.

**Comment by mathmanu** [comment]
The training is fine.  But I still get the error if I try to add graph to tensorboard during training. This happens even after installing pytorch-nightly 2018.05.07
The error reported is: **UserWarning: ONNX export failed on upsample_bilinear2d because align_corners == True not supported**

Full error log is here:
/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/nn/functional.py:1761: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
=> Train Epoch [1/300]:   1%|          | 1/124 [00:19<39:37, 19.33s/it, DataTime=5.773 (5.773), LR=0.0001, Loss=9.970 (9.970), Output=0.018 (0.018)(Mean_IoU)]/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py:418: UserWarning: ONNX export failed on ATen operator hardtanh because torch.onnx.symbolic.hardtanh does not exist
  .format(op_name, op_name))
/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/utils.py:418: UserWarning: ONNX export failed on ATen operator adaptive_avg_pool2d because torch.onnx.symbolic.adaptive_avg_pool2d does not exist
  .format(op_name, op_name))
/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/onnx/symbolic.py:69: UserWarning: ONNX export failed on upsample_bilinear2d because align_corners == True not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
Traceback (most recent call last):
  File "train_segmentation.py", line 81, in <module>
    main_segmentation.main(args)
  File "../training/tools/main_segmentation.py", line 192, in main
    train_loss, train_metric, metric_name = train(args, train_dataset, train_loader, model, optimizer, epoch, train_writer, scheduler.get_lr()[0])
  File "../training/tools/main_segmentation.py", line 305, in train
    train_writer.add_graph(model, input_zero)
  File "/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/writer.py", line 419, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/graph.py", line 85, in graph
    list_of_nodes = parse(graph)
  File "/user/files/apps/anaconda2/envs/pytorch/lib/python3.5/site-packages/tensorboardX/graph.py", line 61, in parse
    n['inputs'][i] = mapping[s]
KeyError: '408'

**Comment by mathmanu** [comment]
Hi,

I have not set this flag anywhere in my code - just using the default value for functional.upsample() and nn.Upsample(). As I understand the default behaviour is align_corners=False. 

This is surprising!

**Comment by mathmanu** [comment]
I have attached a picture of the call stack that shows the problem. 
![onnx_upsample_error_stack_trace](https://user-images.githubusercontent.com/2990503/39810215-d46fca08-53a1-11e8-819b-5a96f232e721.jpg)

I think the function upsample_bilinear2d() defined in symbolic.py is getting wrong values for the align_corners argument. 

I can see that no default value is defined for this argument. Shouldn't the default argument be given in the function definition?

**Comment by mathmanu** [comment]
If I change one line in tensorboardx package (graph.py line 61 of the function parse), everything works fine:

Original:
          n['inputs'][i] = mapping[s]
New:
          n['inputs'][i] = mapping[s] if s in mapping else ""

I am able to proceed and can see the graph in tensorboard. What does this mean? Is it a tensorboardx 
issue or PyTorch issue?

**Comment by mathmanu** [comment]
If I just print out all the values of s that are not found in mapping, I get this list:
405 is not found in mapping. ignoring!!!
405 is not found in mapping. ignoring!!!
615 is not found in mapping. ignoring!!!
408 is not found in mapping. ignoring!!!
409 is not found in mapping. ignoring!!!
616 is not found in mapping. ignoring!!!
617 is not found in mapping. ignoring!!!
410 is not found in mapping. ignoring!!!
411 is not found in mapping. ignoring!!!
412 is not found in mapping. ignoring!!!
413 is not found in mapping. ignoring!!!
414 is not found in mapping. ignoring!!!
415 is not found in mapping. ignoring!!!
416 is not found in mapping. ignoring!!!
417 is not found in mapping. ignoring!!!
418 is not found in mapping. ignoring!!!
419 is not found in mapping. ignoring!!!
618 is not found in mapping. ignoring!!!
420 is not found in mapping. ignoring!!!
421 is not found in mapping. ignoring!!!
619 is not found in mapping. ignoring!!!
620 is not found in mapping. ignoring!!!
422 is not found in mapping. ignoring!!!
621 is not found in mapping. ignoring!!!
423 is not found in mapping. ignoring!!!
424 is not found in mapping. ignoring!!!
425 is not found in mapping. ignoring!!!
426 is not found in mapping. ignoring!!!
427 is not found in mapping. ignoring!!!
428 is not found in mapping. ignoring!!!
429 is not found in mapping. ignoring!!!
430 is not found in mapping. ignoring!!!
431 is not found in mapping. ignoring!!!
432 is not found in mapping. ignoring!!!
433 is not found in mapping. ignoring!!!
434 is not found in mapping. ignoring!!!
435 is not found in mapping. ignoring!!!
436 is not found in mapping. ignoring!!!
622 is not found in mapping. ignoring!!!
623 is not found in mapping. ignoring!!!
437 is not found in mapping. ignoring!!!
438 is not found in mapping. ignoring!!!
439 is not found in mapping. ignoring!!!
440 is not found in mapping. ignoring!!!
441 is not found in mapping. ignoring!!!
442 is not found in mapping. ignoring!!!
443 is not found in mapping. ignoring!!!
444 is not found in mapping. ignoring!!!
445 is not found in mapping. ignoring!!!
446 is not found in mapping. ignoring!!!
447 is not found in mapping. ignoring!!!
448 is not found in mapping. ignoring!!!
449 is not found in mapping. ignoring!!!
450 is not found in mapping. ignoring!!!
451 is not found in mapping. ignoring!!!
452 is not found in mapping. ignoring!!!
453 is not found in mapping. ignoring!!!
454 is not found in mapping. ignoring!!!
455 is not found in mapping. ignoring!!!
456 is not found in mapping. ignoring!!!
457 is not found in mapping. ignoring!!!
458 is not found in mapping. ignoring!!!
459 is not found in mapping. ignoring!!!
460 is not found in mapping. ignoring!!!
461 is not found in mapping. ignoring!!!
462 is not found in mapping. ignoring!!!
463 is not found in mapping. ignoring!!!
464 is not found in mapping. ignoring!!!
465 is not found in mapping. ignoring!!!
466 is not found in mapping. ignoring!!!
467 is not found in mapping. ignoring!!!
468 is not found in mapping. ignoring!!!
469 is not found in mapping. ignoring!!!
470 is not found in mapping. ignoring!!!
471 is not found in mapping. ignoring!!!
472 is not found in mapping. ignoring!!!
473 is not found in mapping. ignoring!!!
474 is not found in mapping. ignoring!!!
475 is not found in mapping. ignoring!!!
624 is not found in mapping. ignoring!!!
476 is not found in mapping. ignoring!!!
477 is not found in mapping. ignoring!!!
478 is not found in mapping. ignoring!!!
479 is not found in mapping. ignoring!!!
480 is not found in mapping. ignoring!!!
481 is not found in mapping. ignoring!!!
482 is not found in mapping. ignoring!!!
483 is not found in mapping. ignoring!!!
484 is not found in mapping. ignoring!!!
485 is not found in mapping. ignoring!!!
486 is not found in mapping. ignoring!!!
487 is not found in mapping. ignoring!!!
488 is not found in mapping. ignoring!!!
489 is not found in mapping. ignoring!!!
490 is not found in mapping. ignoring!!!
491 is not found in mapping. ignoring!!!
492 is not found in mapping. ignoring!!!
493 is not found in mapping. ignoring!!!
494 is not found in mapping. ignoring!!!
495 is not found in mapping. ignoring!!!
496 is not found in mapping. ignoring!!!
497 is not found in mapping. ignoring!!!
498 is not found in mapping. ignoring!!!
499 is not found in mapping. ignoring!!!
625 is not found in mapping. ignoring!!!
626 is not found in mapping. ignoring!!!
500 is not found in mapping. ignoring!!!
627 is not found in mapping. ignoring!!!
501 is not found in mapping. ignoring!!!
502 is not found in mapping. ignoring!!!
628 is not found in mapping. ignoring!!!
629 is not found in mapping. ignoring!!!
503 is not found in mapping. ignoring!!!
630 is not found in mapping. ignoring!!!
631 is not found in mapping. ignoring!!!
632 is not found in mapping. ignoring!!!
504 is not found in mapping. ignoring!!!
505 is not found in mapping. ignoring!!!
633 is not found in mapping. ignoring!!!
634 is not found in mapping. ignoring!!!
635 is not found in mapping. ignoring!!!
506 is not found in mapping. ignoring!!!
636 is not found in mapping. ignoring!!!
637 is not found in mapping. ignoring!!!
638 is not found in mapping. ignoring!!!
507 is not found in mapping. ignoring!!!
508 is not found in mapping. ignoring!!!
639 is not found in mapping. ignoring!!!
509 is not found in mapping. ignoring!!!
640 is not found in mapping. ignoring!!!
641 is not found in mapping. ignoring!!!
642 is not found in mapping. ignoring!!!
510 is not found in mapping. ignoring!!!
511 is not found in mapping. ignoring!!!
643 is not found in mapping. ignoring!!!
644 is not found in mapping. ignoring!!!
512 is not found in mapping. ignoring!!!
513 is not found in mapping. ignoring!!!
514 is not found in mapping. ignoring!!!
645 is not found in mapping. ignoring!!!
646 is not found in mapping. ignoring!!!
647 is not found in mapping. ignoring!!!
515 is not found in mapping. ignoring!!!
648 is not found in mapping. ignoring!!!
516 is not found in mapping. ignoring!!!
517 is not found in mapping. ignoring!!!
649 is not found in mapping. ignoring!!!
650 is not found in mapping. ignoring!!!
651 is not found in mapping. ignoring!!!
652 is not found in mapping. ignoring!!!
653 is not found in mapping. ignoring!!!
654 is not found in mapping. ignoring!!!
518 is not found in mapping. ignoring!!!
655 is not found in mapping. ignoring!!!
656 is not found in mapping. ignoring!!!
657 is not found in mapping. ignoring!!!
658 is not found in mapping. ignoring!!!
659 is not found in mapping. ignoring!!!
519 is not found in mapping. ignoring!!!
520 is not found in mapping. ignoring!!!
660 is not found in mapping. ignoring!!!
521 is not found in mapping. ignoring!!!
661 is not found in mapping. ignoring!!!
662 is not found in mapping. ignoring!!!
522 is not found in mapping. ignoring!!!
523 is not found in mapping. ignoring!!!
663 is not found in mapping. ignoring!!!
664 is not found in mapping. ignoring!!!
665 is not found in mapping. ignoring!!!
524 is not found in mapping. ignoring!!!
525 is not found in mapping. ignoring!!!
526 is not found in mapping. ignoring!!!
666 is not found in mapping. ignoring!!!
667 is not found in mapping. ignoring!!!
668 is not found in mapping. ignoring!!!
527 is not found in mapping. ignoring!!!
669 is not found in mapping. ignoring!!!
670 is not found in mapping. ignoring!!!
671 is not found in mapping. ignoring!!!
672 is not found in mapping. ignoring!!!
528 is not found in mapping. ignoring!!!
529 is not found in mapping. ignoring!!!
673 is not found in mapping. ignoring!!!
674 is not found in mapping. ignoring!!!
675 is not found in mapping. ignoring!!!
530 is not found in mapping. ignoring!!!
676 is not found in mapping. ignoring!!!
677 is not found in mapping. ignoring!!!
678 is not found in mapping. ignoring!!!
531 is not found in mapping. ignoring!!!
532 is not found in mapping. ignoring!!!
679 is not found in mapping. ignoring!!!
680 is not found in mapping. ignoring!!!
681 is not found in mapping. ignoring!!!
682 is not found in mapping. ignoring!!!
683 is not found in mapping. ignoring!!!
533 is not found in mapping. ignoring!!!
684 is not found in mapping. ignoring!!!
534 is not found in mapping. ignoring!!!
535 is not found in mapping. ignoring!!!
685 is not found in mapping. ignoring!!!
686 is not found in mapping. ignoring!!!
687 is not found in mapping. ignoring!!!
688 is not found in mapping. ignoring!!!
689 is not found in mapping. ignoring!!!
536 is not found in mapping. ignoring!!!
690 is not found in mapping. ignoring!!!
537 is not found in mapping. ignoring!!!
538 is not found in mapping. ignoring!!!
691 is not found in mapping. ignoring!!!
692 is not found in mapping. ignoring!!!
693 is not found in mapping. ignoring!!!
694 is not found in mapping. ignoring!!!
695 is not found in mapping. ignoring!!!
539 is not found in mapping. ignoring!!!
540 is not found in mapping. ignoring!!!
541 is not found in mapping. ignoring!!!
696 is not found in mapping. ignoring!!!
697 is not found in mapping. ignoring!!!
698 is not found in mapping. ignoring!!!
542 is not found in mapping. ignoring!!!
543 is not found in mapping. ignoring!!!
544 is not found in mapping. ignoring!!!
545 is not found in mapping. ignoring!!!
546 is not found in mapping. ignoring!!!
547 is not found in mapping. ignoring!!!
548 is not found in mapping. ignoring!!!
549 is not found in mapping. ignoring!!!
550 is not found in mapping. ignoring!!!
551 is not found in mapping. ignoring!!!
552 is not found in mapping. ignoring!!!
553 is not found in mapping. ignoring!!!
699 is not found in mapping. ignoring!!!
700 is not found in mapping. ignoring!!!
701 is not found in mapping. ignoring!!!
702 is not found in mapping. ignoring!!!
703 is not found in mapping. ignoring!!!
704 is not found in mapping. ignoring!!!
705 is not found in mapping. ignoring!!!
706 is not found in mapping. ignoring!!!
707 is not found in mapping. ignoring!!!
708 is not found in mapping. ignoring!!!
709 is not found in mapping. ignoring!!!
710 is not found in mapping. ignoring!!!
711 is not found in mapping. ignoring!!!
712 is not found in mapping. ignoring!!!
713 is not found in mapping. ignoring!!!
714 is not found in mapping. ignoring!!!
715 is not found in mapping. ignoring!!!
716 is not found in mapping. ignoring!!!
717 is not found in mapping. ignoring!!!
718 is not found in mapping. ignoring!!!
719 is not found in mapping. ignoring!!!
720 is not found in mapping. ignoring!!!
721 is not found in mapping. ignoring!!!
722 is not found in mapping. ignoring!!!
723 is not found in mapping. ignoring!!!
724 is not found in mapping. ignoring!!!
725 is not found in mapping. ignoring!!!
726 is not found in mapping. ignoring!!!
727 is not found in mapping. ignoring!!!
728 is not found in mapping. ignoring!!!
729 is not found in mapping. ignoring!!!
730 is not found in mapping. ignoring!!!
731 is not found in mapping. ignoring!!!
732 is not found in mapping. ignoring!!!
733 is not found in mapping. ignoring!!!
734 is not found in mapping. ignoring!!!
554 is not found in mapping. ignoring!!!
555 is not found in mapping. ignoring!!!
556 is not found in mapping. ignoring!!!
557 is not found in mapping. ignoring!!!
558 is not found in mapping. ignoring!!!
559 is not found in mapping. ignoring!!!
560 is not found in mapping. ignoring!!!
561 is not found in mapping. ignoring!!!
562 is not found in mapping. ignoring!!!
563 is not found in mapping. ignoring!!!
564 is not found in mapping. ignoring!!!
565 is not found in mapping. ignoring!!!
566 is not found in mapping. ignoring!!!
567 is not found in mapping. ignoring!!!
568 is not found in mapping. ignoring!!!
569 is not found in mapping. ignoring!!!
570 is not found in mapping. ignoring!!!
572 is not found in mapping. ignoring!!!
573 is not found in mapping. ignoring!!!
574 is not found in mapping. ignoring!!!
575 is not found in mapping. ignoring!!!
576 is not found in mapping. ignoring!!!
577 is not found in mapping. ignoring!!!
578 is not found in mapping. ignoring!!!
579 is not found in mapping. ignoring!!!
580 is not found in mapping. ignoring!!!
581 is not found in mapping. ignoring!!!
582 is not found in mapping. ignoring!!!
583 is not found in mapping. ignoring!!!
571 is not found in mapping. ignoring!!!
584 is not found in mapping. ignoring!!!
585 is not found in mapping. ignoring!!!
586 is not found in mapping. ignoring!!!
587 is not found in mapping. ignoring!!!
588 is not found in mapping. ignoring!!!
589 is not found in mapping. ignoring!!!
590 is not found in mapping. ignoring!!!
591 is not found in mapping. ignoring!!!
592 is not found in mapping. ignoring!!!
593 is not found in mapping. ignoring!!!
594 is not found in mapping. ignoring!!!
595 is not found in mapping. ignoring!!!
596 is not found in mapping. ignoring!!!
597 is not found in mapping. ignoring!!!
598 is not found in mapping. ignoring!!!
599 is not found in mapping. ignoring!!!
600 is not found in mapping. ignoring!!!
601 is not found in mapping. ignoring!!!
602 is not found in mapping. ignoring!!!
603 is not found in mapping. ignoring!!!
604 is not found in mapping. ignoring!!!
605 is not found in mapping. ignoring!!!
606 is not found in mapping. ignoring!!!
607 is not found in mapping. ignoring!!!
608 is not found in mapping. ignoring!!!
609 is not found in mapping. ignoring!!!
610 is not found in mapping. ignoring!!!
611 is not found in mapping. ignoring!!!
612 is not found in mapping. ignoring!!!
613 is not found in mapping. ignoring!!!
614 is not found in mapping. ignoring!!!
735 is not found in mapping. ignoring!!!
736 is not found in mapping. ignoring!!!
737 is not found in mapping. ignoring!!!
738 is not found in mapping. ignoring!!!
739 is not found in mapping. ignoring!!!
740 is not found in mapping. ignoring!!!
741 is not found in mapping. ignoring!!!
742 is not found in mapping. ignoring!!!
743 is not found in mapping. ignoring!!!
744 is not found in mapping. ignoring!!!
745 is not found in mapping. ignoring!!!
746 is not found in mapping. ignoring!!!
747 is not found in mapping. ignoring!!!
748 is not found in mapping. ignoring!!!
749 is not found in mapping. ignoring!!!
750 is not found in mapping. ignoring!!!
751 is not found in mapping. ignoring!!!
752 is not found in mapping. ignoring!!!
753 is not found in mapping. ignoring!!!
754 is not found in mapping. ignoring!!!
755 is not found in mapping. ignoring!!!
756 is not found in mapping. ignoring!!!
757 is not found in mapping. ignoring!!!
758 is not found in mapping. ignoring!!!
759 is not found in mapping. ignoring!!!
760 is not found in mapping. ignoring!!!
761 is not found in mapping. ignoring!!!
762 is not found in mapping. ignoring!!!
763 is not found in mapping. ignoring!!!
764 is not found in mapping. ignoring!!!
765 is not found in mapping. ignoring!!!
766 is not found in mapping. ignoring!!!
767 is not found in mapping. ignoring!!!
768 is not found in mapping. ignoring!!!
769 is not found in mapping. ignoring!!!
770 is not found in mapping. ignoring!!!
771 is not found in mapping. ignoring!!!
772 is not found in mapping. ignoring!!!
773 is not found in mapping. ignoring!!!
774 is not found in mapping. ignoring!!!
775 is not found in mapping. ignoring!!!
776 is not found in mapping. ignoring!!!
777 is not found in mapping. ignoring!!!
778 is not found in mapping. ignoring!!!
780 is not found in mapping. ignoring!!!
781 is not found in mapping. ignoring!!!
782 is not found in mapping. ignoring!!!
783 is not found in mapping. ignoring!!!
784 is not found in mapping. ignoring!!!
785 is not found in mapping. ignoring!!!
786 is not found in mapping. ignoring!!!
787 is not found in mapping. ignoring!!!
788 is not found in mapping. ignoring!!!
789 is not found in mapping. ignoring!!!
790 is not found in mapping. ignoring!!!
791 is not found in mapping. ignoring!!!
779 is not found in mapping. ignoring!!!
792 is not found in mapping. ignoring!!!
793 is not found in mapping. ignoring!!!
794 is not found in mapping. ignoring!!!
795 is not found in mapping. ignoring!!!
796 is not found in mapping. ignoring!!!
797 is not found in mapping. ignoring!!!
798 is not found in mapping. ignoring!!!
799 is not found in mapping. ignoring!!!
800 is not found in mapping. ignoring!!!
801 is not found in mapping. ignoring!!!
802 is not found in mapping. ignoring!!!
803 is not found in mapping. ignoring!!!
804 is not found in mapping. ignoring!!!

**Comment by aachigorin** [comment]
Hey, guys.
I'm having similar issue with exporting bilinear upsample with align_corners=False on '0.5.0a0+ac5d7bd'.

Here is the minimal example to reproduce:
```
import torch
import torch.onnx
from torch import nn
from torch.autograd import Variable
import torch.nn.functional as F

class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        
    def forward(self, x):
        h1 = x
        h2 = F.upsample(x, size=h1.size()[-2:], mode='bilinear', align_corners=False)
        h = torch.cat([h1, h2], dim=1)
        return h

model = SimpleNet()
x = Variable(torch.randn(1, 3, 10, 10)).cpu()
torch_out = torch.onnx._export(model, x, '~/temp/test_bilinear_onnx_export.txt', export_params=True, verbose=True)
print('finished onnx export')
```

which gives me the following error:
`/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/symbolic.py:69: UserWarning: ONNX export failed on upsample_bilinear2d because align_corners == True not supported
`

Full output:
```
graph(%0 : Float(1, 3, 10, 10)) {
  %1 : Dynamic = onnx::Shape(%0), scope: SimpleNet
  %2 : Dynamic = onnx::Slice[axes=[0], ends=[3], starts=[2]](%1), scope: SimpleNet
  %3 : Long() = onnx::Squeeze[axes=[0]](%2), scope: SimpleNet
  %4 : Dynamic = onnx::Shape(%0), scope: SimpleNet
  %5 : Dynamic = onnx::Slice[axes=[0], ends=[4], starts=[3]](%4), scope: SimpleNet
  %6 : Long() = onnx::Squeeze[axes=[0]](%5), scope: SimpleNet
  %7 : Dynamic = onnx::Unsqueeze[axes=[0]](%3), scope: SimpleNet
  %8 : Dynamic = onnx::Unsqueeze[axes=[0]](%6), scope: SimpleNet
  %9 : Dynamic = onnx::Concat[axis=0](%7, %8), scope: SimpleNet
  %10 : Long() = onnx::Constant[value={0}](), scope: SimpleNet
  %11 : Float(1, 3, 10, 10) = aten::upsample_bilinear2d(%0, %9, %10), scope: SimpleNet
  %12 : Float(1, 6, 10, 10) = onnx::Concat[axis=1](%0, %11), scope: SimpleNet
  return (%12);
}

/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/symbolic.py:69: UserWarning: ONNX export failed on upsample_bilinear2d because align_corners == True not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-13-2b176cabda6d> in <module>()
     11 model = SimpleNet()
     12 x = Variable(torch.randn(1, 3, 10, 10)).cpu()
---> 13 torch_out = torch.onnx._export(model, x, '~/temp/test_bilinear_onnx_export.txt', export_params=True, verbose=True)
     14 print('finished onnx export')

/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/__init__.py in _export(*args, **kwargs)
     18 def _export(*args, **kwargs):
     19     from torch.onnx import utils
---> 20     return utils._export(*args, **kwargs)
     21 
     22 

/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, export_type, example_outputs, propagate)
    205     defer_weight_export = export_type is not ExportTypes.PROTOBUF_FILE
    206     if export_params:
--> 207         proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, export_raw_ir)
    208     else:
    209         proto, export_map = graph.export([], _onnx_opset_version, False, export_raw_ir)

RuntimeError: ONNX export failed: Couldn't export operator aten::upsample_bilinear2d

Defined at:
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/nn/functional.py(1779): upsample
<ipython-input-13-2b176cabda6d>(7): forward
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/nn/modules/module.py(479): _slow_forward
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/nn/modules/module.py(489): __call__
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/jit/__init__.py(288): forward
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/nn/modules/module.py(491): __call__
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/jit/__init__.py(255): get_trace_graph
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/utils.py(137): _trace_and_get_graph_from_model
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/utils.py(167): _model_to_graph
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/utils.py(201): _export
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/torch/onnx/__init__.py(20): _export
<ipython-input-13-2b176cabda6d>(13): <module>
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2881): run_code
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2821): run_ast_nodes
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/IPython/core/interactiveshell.py(2717): run_cell
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel/zmqshell.py(533): run_cell
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel/ipkernel.py(196): do_execute
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel/kernelbase.py(399): execute_request
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel/kernelbase.py(235): dispatch_shell
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel/kernelbase.py(283): dispatcher
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/tornado/stack_context.py(277): null_wrapper
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py(414): _run_callback
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py(472): _handle_recv
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py(440): _handle_events
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/tornado/stack_context.py(277): null_wrapper
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/tornado/ioloop.py(888): start
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/zmq/eventloop/ioloop.py(177): start
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel/kernelapp.py(477): start
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/traitlets/config/application.py(658): launch_instance
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/site-packages/ipykernel_launcher.py(16): <module>
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/runpy.py(85): _run_code
/Users/aachigorin/anaconda/envs/detector_py36_pytorch050/lib/python3.6/runpy.py(193): _run_module_as_main


Graph we tried to export:
graph(%0 : Float(1, 3, 10, 10)) {
  %1 : Dynamic = onnx::Shape(%0), scope: SimpleNet
  %2 : Dynamic = onnx::Slice[axes=[0], ends=[3], starts=[2]](%1), scope: SimpleNet
  %3 : Long() = onnx::Squeeze[axes=[0]](%2), scope: SimpleNet
  %4 : Dynamic = onnx::Shape(%0), scope: SimpleNet
  %5 : Dynamic = onnx::Slice[axes=[0], ends=[4], starts=[3]](%4), scope: SimpleNet
  %6 : Long() = onnx::Squeeze[axes=[0]](%5), scope: SimpleNet
  %7 : Dynamic = onnx::Unsqueeze[axes=[0]](%3), scope: SimpleNet
  %8 : Dynamic = onnx::Unsqueeze[axes=[0]](%6), scope: SimpleNet
  %9 : Dynamic = onnx::Concat[axis=0](%7, %8), scope: SimpleNet
  %10 : Long() = onnx::Constant[value={0}](), scope: SimpleNet
  %11 : Float(1, 3, 10, 10) = aten::upsample_bilinear2d(%0, %9, %10), scope: SimpleNet
  %12 : Float(1, 6, 10, 10) = onnx::Concat[axis=1](%0, %11), scope: SimpleNet
  return (%12);
}
```

Should I create the separate issue for this?
