### ISSUE TITLE
Graphics not displaying properly in Neural Transfer tutorial when run from Jupyter notebook.

### ISSUE THREAD

**Issue by goodlux** [pytorch/pytorch#6903]
## Issue description

In Neural Transfer tutorial, the final image does not display when running the code in a Jupyter notebook. 

http://pytorch.org/tutorials/advanced/neural_style_tutorial.html#gradient-descent

The tutorial does work when running on the command line. 

This is likely an issue with the way plt.imshow renders an image in a Jupyter notebook. 

## Code example

The problem is with the last bit of code in the tutorial:

```python
output = run_style_transfer(cnn, content_img, style_img, input_img)

plt.figure()
imshow(output, title='Output Image')

#sphinx_gallery_thumbnail_number = 4

plt.ioff()
plt.show()
```

Here is a screenshot of what appears in the Jupyter notebook, instead of the expected image. 

Actual: 
<img width="620" alt="screen shot 2018-04-23 at 1 32 21 pm" src="https://user-images.githubusercontent.com/31841/39198489-13c11dfe-479c-11e8-9e06-f09a9d1d35c4.png">

Expected
![sphx_glr_neural_style_tutorial_004](https://user-images.githubusercontent.com/31841/39198593-47f7be2a-479c-11e8-8e25-0a231be750f2.png)

Again, this happens only when the code is run in Jupyter notebooks, and the other images appear as expected in the tutorial.

**Comment by SsnL** [comment]
Your loss is way too high. Something in your code is wrong.

**Comment by goodlux** [comment]
Could it be the Jupyter is only showing the first run of the pattern?

**Comment by SsnL** [comment]
No it is too high. I have recently played with the tutorial code so I am aware what the normal loss range is. The content loss should be in range 1~4. It should be around 4.2 at the first print even.

Loss not decreasing + loss too high can be a result of many things, e.g. wrong lr.

This is not a pytorch bug as you should tune/fix your code. 

If the behavior is inconsistent between jupyter and command line, Feel free to reopen.
