### ISSUE TITLE
forward-mode AD: minimum, min, maximum, max formulas are loudly incorrect

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#69034]
## 🐛 Bug

Using forward-mode AD with `{minimum, maximum}` and fp32 Tensors raises an error

## To Reproduce

```
import torch
import torch.autograd.forward_ad as fwAD

x = torch.randn(3)
y = torch.randn(3)
tx = torch.randn(3)
ty= torch.randn(3)

with fwAD.dual_level():
  x_dual = fwAD.make_dual(x, tx)
  y_dual = fwAD.make_dual(y, ty)
  torch.maximum(x_dual, y_dual)
```
Gives: `RuntimeError: expected scalar type double but found float`

## Expected behavior

No error

## Environment

PyTorch main branch

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by CollinsPeriodLee** [comment]
Using `torch.fmax(x_dual,y_dual)` rather than `torch.maximum` works.

**Comment by albanD** [comment]
These are written as `supports_forward_ad=True` in opinfo. So this case is not tested by opinfo?

**Comment by zou3519** [comment]
The OpInfo tests are testing with torch.double by default. This problem only manifests with tensors that are torch.float
