### ISSUE TITLE
output argument never used in softplus_backward?

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#69042]
As I was writing decompositions for `softplus_backward` (https://github.com/pytorch/functorch/pull/281), I noticed that the argument seemed to be never used: 

Looking at the source (https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Activation.cpp#L94) seems to note the same thing. Is that right or am I missing something?

cc @albanD @mruberry @jbschlosser @walterddr

**Comment by soulitzer** [comment]
Looks like it is used in the double backward formula, i.e,. we want to use the result of softplus in the computation of derivative of softplus_backward wrt to grad_output.

```
- name: softplus_backward(Tensor grad_output, Tensor self, Scalar beta, Scalar threshold, Tensor output) -> Tensor
  grad_output: softplus_backward(grad, self, beta, threshold, output)
  self: softplus_double_backward(grad * grad_output, self, beta, threshold)
```

**Comment by Chillee** [comment]
@soulitzer I'm not totally sure how it's being used there. It looks like it's calling softplus_backward as the derivative wrt itself and passing in output, but isn't the issue that `softplus_backward` isn't using `output` in the first place?

**Comment by soulitzer** [comment]
Oh whoops I didn't even realize it was calling into the same function. Yeah we should probably stop passing it in.
