### ISSUE TITLE
LTC: Same backend being registered multiple times

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#69047]
## 🐛 Bug

Attempting to write a new custom vendor backend for Lazy Tensor Core. I've written up a skeleton that compiles (albeit with many `throw "Unimplemented"` scattered throughout). When I try to load the backend up, it works fine (which isn't surprising as it appears to just be setting some global variable). However, if I also try to load up `lazy_tensor_core`, I get this error:
```
terminate called after throwing an instance of 'c10::Error'
  what():  Tried to register multiple backend fallbacks for the same dispatch key Lazy; previous registration registered at pytorch/lazy_tensor_core/lazy_tensor_core/csrc/ts_backend/aten_eager_fallback.cpp:47, new registration registered at pytorch/lazy_tensor_core/lazy_tensor_core/csrc/ts_backend/aten_eager_fallback.cpp:47
Exception raised from registerFallback at ../aten/src/ATen/core/dispatch/Dispatcher.cpp:267 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x55 (0x7f5b95034505 in pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xb1 (0x7f5b950317e1 in pytorch/torch/lib/libc10.so)
frame #2: c10::Dispatcher::registerFallback(c10::DispatchKey, c10::KernelFunction, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xd6a (0x7f5b95f181ea in pytorch/torch/lib/libtorch_cpu.so)
frame #3: torch::Library::_fallback(torch::CppFunction&&) & + 0x151 (0x7f5b95f42f51 in pytorch/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0xdda98 (0x7f5b937a2a98 in pytorch/lazy_tensor_core/_LAZYC.cpython-37m-x86_64-linux-gnu.so)
```
Its trying to register what I'm guessing is the TorchScript backend multiple times? How do I disable this?

Weirdly, I only get this error, if I load up `lazy_tensor_core` **and** my custom backend. Not if only one or the other. However, I can't really use/test my custom backend without the `lazy_tensor_core` frontend API.

Question is, why would it be trying to register multiple backend fallbacks from the exact same place for the same dispatch key `Lazy`?

## To Reproduce

```python
import torch
import lazy_tensor_core
import my_custom_ltc_backend
```

## Expected behavior

I'd expect to be able to just import my custom backend and expect it to be the most recently registered backend and thus have LTC use that as its backend (not TorchScript).

## Environment
```
PyTorch version: 1.11.0a0+git94ba7cd
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.8.2003 (Core) (x86_64)
GCC version: Could not collect
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 3.15.5
Libc version: glibc-2.2.5

Python version: 3.7.4 (default, Nov 17 2021, 18:04:18)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.11.0a0+git94ba7cd
[conda] Could not collect
```

**Comment by antoniojkim** [comment]
I found the cause of this issue. It was an issue with the rpaths that was causing `_LAZYC.___.so` to be loaded twice.

**Comment by wconstab** [comment]
Oh- I actually had a partly typed reply!  I was going to say that you can only have one backend registered to a given key.  I wanted to make sure you were creating a full backend (with its own registrations) in your plugin, and not relying partially on the TS backend.  Sounds like you figured it out.
