### ISSUE TITLE
how to compute the real Jacobian matrix using autograd tool

### ISSUE THREAD

**Issue by LeZhengThu** [pytorch/pytorch#69070]
I want to compute the real Jacobian matrix instead of the vector-Jacobian product. For example, I have 
```f=(f1, f2, f3), f1=x1^2+2*x2+x3, f2=x1+x2^3+x3^2, f3=2*x1+x2^2+x3^3```
Then the Jacobian is ```J=[2*x1, 2, 1; 1, 3*x2^2, 2*x3; 2, 2*x2, 3*x3^2] ```
But backward() or grad() only gives the vector-Jacobian product. The following is my test code
```
import torch
import numpy as np
x = torch.tensor(np.array([[1,2,3]]), requires_grad=True, dtype=torch.float)
y = torch.randn(3) 
y[0] = x[0][0]**2+2*x[0][1]+x[0][2]
y[1] = x[0][0]+x[0][1]**3+x[0][2]**2
y[2] = 2*x[0][0]+x[0][1]**2+x[0][2]**3
torch.autograd.grad(y, x, torch.ones_like(y))
```
The result is tensor([[5,18,34]]). This is the result of J*[1;1;1] since I put torch.ones_like(y) in the code. Of course, I can use [1,0,0] to get each element of J, but that is too slow. Do we have any faster way to achieve this?

BTW, when I try to replace torch.ones_like(y) with torch.eye(y.shape[0]), an error occurs: Mismatch in shape: grad_output[0] has a shape of torch.Size([3, 3]) and output[0] has a shape of torch.Size([3]).

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
If `is_grads_batched=True` is specified, `autograd.grad` allows an extra batch dimension in the grad outputs. 

The following works for me on the latest master (it did not make it to 1.10 unfortunately, so you will need to use a nightly build or build for source yourself):
```
import torch
import numpy as np
x = torch.tensor(np.array([[1,2,3]]), requires_grad=True, dtype=torch.float)
y = torch.randn(3) 
y[0] = x[0][0]**2+2*x[0][1]+x[0][2]
y[1] = x[0][0]+x[0][1]**3+x[0][2]**2
y[2] = 2*x[0][0]+x[0][1]**2+x[0][2]**3
torch.autograd.grad(y, x, (torch.eye(y.shape[0]),), is_grads_batched=True)
```

**Comment by albanD** [comment]
You can use the autograd.functional.jacobian function: https://pytorch.org/docs/stable/generated/torch.autograd.functional.jacobian.html?highlight=jacobian#torch.autograd.functional.jacobian
