### ISSUE TITLE
need to check manual_cpp_binding in gen_backend_stubs.py

### ISSUE THREAD

**Issue by guoyejun** [pytorch/pytorch#69076]
If an external backend provides an OP whose manual_cpp_binding is True (just like https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L62), gen_backend_stubs.py need to do an error check for such case.

thanks.

cc @ezyang @bhosmer @bdhirsh

**Comment by bdhirsh** [comment]
This would be marginally useful to consumers of external codegen (intel, xla, LazyTensor). If you try to write a custom kernel for a `manual_cpp_binding` op like `is_leaf()` using `gen_backend_stubs.py`, we should raise an error. Right now we silently ignore the kernel.

**Comment by bdhirsh** [comment]
(I'd like to reserve this issue for a bootcamper)

**Comment by guoyejun** [comment]
want to double check that there's no side effect if we register such OPs? (just as if we do not register it)

**Comment by bdhirsh** [comment]
Are you talking about in the current state? I think that we'll want to error out if you try to register one. But in the current state, ops with `manual_cpp_binding` set are codegen'd to skip the dispatcher completely and directly call into the implementation in `aten/src/ATen/templates/Functions.h` so there shouldn't be any side affects other than an unused function getting registered to the dispatcher.

**Comment by guoyejun** [comment]
yes, the current status.  Got it, thanks.
