### ISSUE TITLE
"Symbol not found" when "impot torch" on Mac OS

### ISSUE THREAD

**Issue by WarBean** [pytorch/pytorch#691]
I have installed pytorch from source on Mac OS successfully, but `import torch` cases error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/warbean/anaconda3/envs/py35/lib/python3.5/site-packages/torch/__init__.py", line 45, in <module>
    from torch._C import *
ImportError: dlopen(/Users/warbean/anaconda3/envs/py35/lib/python3.5/site-packages/torch/_C.cpython-35m-darwin.so, 10): Symbol not found: ___emutls_get_address
  Referenced from: /Users/warbean/anaconda3/envs/py35/lib/python3.5/site-packages/torch/lib/libTH.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/warbean/anaconda3/envs/py35/lib/python3.5/site-packages/torch/lib/libTH.1.dylib
```

Looks like the key is `Symbol not found: ___emutls_get_address`. Any suggestions to fix it?

**Comment by apaszke** [comment]
The compiler seems to be picking up some old libraries in your system. For some references see [this](http://stackoverflow.com/questions/13414786/missing-emutls-get-address-with-gcc-4-7-and-openmp) or [that](https://trac.macports.org/ticket/26159).

**Comment by WarBean** [comment]
Try to install from conda package rather than from source:

`conda install osx-64_pytorch-0.1.8-py35_1.tar.bz2`

Fix the problem.

**Comment by shun1024** [comment]
This one happens to me if I used the torch 1.0 installed by pip. If I changed to 0.4, it works. It happens to both of my linux and mac. 

Symbol not found: _PySlice_Unpack

**Comment by zaneclaes** [comment]
3 years later, downgrading torchtext still seems to be the only solution. A fresh install of (homebrew) Python on MacOS still does not appear to be compatible with torchtext.
