### ISSUE TITLE
Copyright notice referred to in, but missing from, LICENSE

### ISSUE THREAD

**Issue by codingatty** [pytorch/pytorch#6911]
## Copyright notice referred to in, but missing from, LICENSE

The three-clause BSD license in file LICENSE says in clause 1 "Redistributions of source code must retain the above copyright notice..." However, there is no longer a copyright notice in the file; it appears to have been removed in commit 90afedb6e222d430d5c9333ff27adb42aa4bb900  (see [here](https://github.com/pytorch/pytorch/commit/90afedb6e222d430d5c9333ff27adb42aa4bb900#diff-9879d6db96fd29134fc802214163b95a)).

**Comment by SsnL** [comment]
cc @ezyang
