### ISSUE TITLE
Ugly and poorer tensor visualisation with v0.4.0

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#6912]
`numpy` deals well with printing arrays.

```python
In [1]: np.array([1, 2, 3])       
Out[1]: array([1, 2, 3])          
                                   
In [2]: print(np.array([1, 2, 3]))
[1 2 3]
```

`torch` no longer does.

```python
In [3]: torch.tensor([1, 2, 3])       
Out[3]: tensor([ 1,  2,  3])

In [4]: print(torch.tensor([1, 2, 3]))
tensor([ 1,  2,  3])
```

```python
 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]

# was much cleaner (no brackets and commas) and informative (`dtype` and `size`) than

tensor([[ 1,  2,  3], 
        [ 4,  5,  6]])
```

**Comment by SsnL** [comment]
I'm not saying your issue isn't valid. But I want to point out that dtype info is still there, except that default ones won't be displayed. The current one also has better device info.

**Comment by Atcold** [comment]
When using the REPL for interactive computing one ends up displaying tensors quite often. Having a leaner rendering (no brackets and commas) is definitely desirable. Moreover, having `dtype` and size information provide a quick insight about the item one is viewing.
The current `tensor()` is redundant, IMO.

**Comment by Aphaniteja** [comment]
Yes. I also the older version better. It actually shows the information that is needed.
I usually develop on Jupyter notebooks and have to see the tensors and size information often. 
Now it's uglier and less useful overall.

 1  2  3
 4  5  6
[dtype: FloatTensor, size: 2x3, device: cpu]

This format would be the best.

**Comment by Atcold** [comment]
@Aphaniteja, add three back-ticks, ```, before and after your code. It's going to be better formatted here, in GitHub.

**Comment by Atcold** [comment]
@SsnL, although `repr()` *should* be the string to reproduce the object, it's really unlikely it's going to do anything sensical when you type something like `np.arange(5000)`.
Instead, we could actually use it for improving the user experience.

**Comment by gchanan** [comment]
It does look like we can improve the (pretty) `__str__` print.

On being able to reproduce the object with `__repr__`, I do find it very useful to be able to reproduce currently.  That said, I'm not against:
* Adding more information as long as it's still reproducible, i.e. we could always print the dtype, even if it's the default dtype.  Or have an option.
* Adding more information when the tensor isn't reproducible anyway, i.e. print a size if we are summarizing.  It would be a little weird to sometimes have the size though, but I don't think that's a huge deal.  Or we could add a size parameter to `torch.tensor` (that just checks it's correct), so it's still reproducible, although that's a little strange too.

**Comment by GuillaumeLeclerc** [comment]
The previous `__str__` was much better, now I need three prints, one for the data,one for the shape and one for the type...

**Comment by gchanan** [comment]
You don't need one for the type, it's implicit (if it prints the data as integers the type is long, if it prints the data as floats, the type is the default dtype (usually float)).

**Comment by fmassa** [comment]
At some point I suggested adding a `legacy` option to the print_options. That could accommodate old users that are not necessarily happy with the now print.
Adding the shape argument is a possibility (and is already present when in some cases in numpy), but maybe we only add the print in `str` and not in `repr`?

**Comment by zou3519** [comment]
@gchanan the dtype printing might be implicit but users might not remember the defaults completely, so I think it would be nice to print the dtype (does numpy use float32 or float64 by default? I think it's float64 but I'd have to look it up a few times before actually commiting it to memory)

**Comment by GuillaumeLeclerc** [comment]
If a display that:

- Is aligned
- Display the size
- Display the type (I don't see how you can differenciate between float32 and float64 by looking at the values)
- Do not display meaningless brackets (do these bracket actually convey information or are they completely useless ?)

is considered "`legacy`" then maybe pytorch is not going forward ?

**Comment by li-roy** [comment]
Maybe we should separate `__repr__` and `__str__`. Have string look something more like the old repr, but also consider the things people previously mentioned for repr:
- Should we print the type if it's implicit
- Should we print device if it's implicit
- Should we include size

I think alignment is something that can't really be fixed. It was also a problem with the old repr, it just happens for smaller sizes with the new repr. For example in the old repr:

```
>>> torch.rand(10,20)


Columns 0 to 9
 0.9021  0.7451  0.9397  0.3682  0.6292  0.9744  0.4691  0.9015  0.5065  0.5431
 0.4572  0.7933  0.1878  0.5731  0.2696  0.6941  0.8501  0.4785  0.6187  0.1533
 0.9366  0.5505  0.2884  0.8264  0.0525  0.1204  0.3278  0.7349  0.7550  0.4861
 0.9438  0.3599  0.2531  0.0649  0.9624  0.1538  0.4233  0.1385  0.2210  0.1176
 0.6091  0.4946  0.7815  0.8481  0.6920  0.4056  0.1918  0.7796  0.2382  0.7418
 0.2681  0.5140  0.5777  0.6781  0.1882  0.7660  0.5754  0.4259  0.3688  0.5173
 0.1062  0.9866  0.7547  0.4543  0.3583  0.6115  0.2747  0.7153  0.7171  0.8373
 0.7611  0.9226  0.7943  0.6499  0.6954  0.3158  0.5290  0.7996  0.3300  0.6613
 0.5909  0.3324  0.6371  0.1142  0.8842  0.6436  0.3294  0.1376  0.4018  0.3414
 0.3820  0.8419  0.3288  0.5143  0.5613  0.9057  0.2400  0.0221  0.8634  0.0656

Columns 10 to 19
 0.5681  0.3047  0.5777  0.0439  0.0334  0.0117  0.6883  0.1151  0.8553  0.0535
 0.6346  0.7784  0.6623  0.5110  0.8255  0.9233  0.8554  0.2003  0.9146  0.5807
 0.4238  0.4664  0.5884  0.5479  0.1571  0.0486  0.2117  0.8111  0.8310  0.3366
 0.8785  0.4957  0.2391  0.2009  0.5385  0.1601  0.2702  0.7325  0.2886  0.2005
 0.5704  0.5903  0.2864  0.9892  0.4678  0.5666  0.9842  0.5488  0.3298  0.6303
 0.1329  0.8764  0.1621  0.7586  0.3570  0.5551  0.5840  0.9981  0.8941  0.6848
 0.0733  0.7516  0.7973  0.6522  0.3866  0.2570  0.7841  0.5425  0.3966  0.7965
 0.7497  0.5281  0.3102  0.4246  0.4842  0.9262  0.1518  0.3877  0.2345  0.9806
 0.5374  0.1435  0.1882  0.5057  0.1711  0.6304  0.4606  0.2386  0.0381  0.6813
 0.0214  0.4233  0.9714  0.2428  0.4283  0.5646  0.6661  0.1618  0.0460  0.6825
[torch.FloatTensor of size 10x20]
```

I don't like how the rows are broken up in the old repr, but if we want to keep the rows together, brackets seem necessary to me.

**Comment by benwu232** [comment]
I like the thing in older version that when typing a tensor in debugger, it shows the size(shape) of the tensor. Sadly, this feature is no longer in 0.40. Actually most of time, what I worry is whether the tensor shape is what I want. Now I must type tensor.shape, which is tedious.
Here is an example in 0.40
...,
         [ -65.2422,  -52.2383,  -35.8047,  ...,    0.5691,
            22.1797,    5.3984],
         [ -65.2422,  -52.2383,  -35.8047,  ...,    0.5691,
            22.1797,    5.3984],
         [ -65.2422,  -52.2383,  -35.8047,  ...,    0.5691,
            22.1797,    5.3984]]], dtype=torch.float64, device='cuda:0')  I hope tensor size is also list here!!!

**Comment by soumith** [comment]
we made tensor printing less ugly in #7632 and a few other PRs. hope you are satisfied :)

**Comment by Coderx7** [comment]
Can you add the tensor shape as well? this was very helpful and I don't think having such information is bad! 
It would be much appreciated to see the tensor shape along with its dtype in a concise manner like before!

**Comment by gchanan** [comment]
@Coderx7 I think my comment above covers that:
```
Adding more information when the tensor isn't reproducible anyway, i.e. print a size if we are summarizing. It would be a little weird to sometimes have the size though, but I don't think that's a huge deal. Or we could add a size parameter to torch.tensor (that just checks it's correct), so it's still reproducible, although that's a little strange too.
```

**Comment by gchanan** [comment]
reopening to get discussion around printing-the-shape question.

**Comment by izdeby** [comment]
We are not gonna print the shape.

**Comment by colesbury** [comment]
I'm closing this for now as we don't have any plans to change the formatting.

**Comment by Coderx7** [comment]
@izdeby : we can easily provide a default behavior (which is what we have currently) and also let the  user decide whether he/she wants to have this kind of information enabled! we already have `torch.set_printoptions`, so we shouldnt really have any issues in this regard, we can easily implement this in `torch.set_printoptions`
