### ISSUE TITLE
warnings.warn('PyTorch is not compiled with NCCL support'）

### ISSUE THREAD

**Issue by NayeeC** [pytorch/pytorch#69200]
## ❓ Questions and Help
Hi，

I run my codes under Windows, and when I try to use multiple GPUs to train, I encounter the following problem:
```
D:\Anaconda3\envs\chtorch2\lib\site-packages\torch\cuda\nccl.py:15: UserWarning: PyTorch is not compiled with NCCL support
  warnings.warn('PyTorch is not compiled with NCCL support')
```
the code can still run, and I can still get the output, but I don't know whether this warning will affect the output of the program. And when I use a single GPU to train the code, this warning doesn't show.

My Questions is:
1. Does this warning affect the output of the program? If so, is using a single card to train the only solution?

Thank you

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by H-Huang** [comment]
Are you using [DistributedDataParallel](https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html)? NCCL for Windows is not supported but you can use the GLOO backend.

You can specify which backend to use with the [`init_process_group()` API ](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group)

If you have any additional questions about training with multiple GPUs then it would be better to post your question in the [PyTorch forum for distributed](https://discuss.pytorch.org/c/distributed/12) along with the APIs that you are using.
