### ISSUE TITLE
Support for cdist export to ONNX

### ISSUE THREAD

**Issue by antoncyrol** [pytorch/pytorch#69201]
## 🚀 Feature

Support for exporting `cdist `operator to ONNX:
https://pytorch.org/docs/stable/generated/torch.cdist.html

## Motivation

Some models, especially those that contain a nearest neighbor search, benefit from cdist.

## Pitch

Add support for exporting `cdist ` operator to ONNX.

## Alternatives

Write custom, exportable cdist implementation (with opset_version>=11), e.g. 

```
def onnx_cdists(x1, x2, p=2):
    """ Custom cdists function for ONNX export since neither cdists nor
    linalg.norm is currently support by the current PyTorch version 1.10.
    """
    s_x1 = torch.unsqueeze(x1, dim=1)
    s_x2 = torch.unsqueeze(x2, dim=0)
    diffs = s_x1 - s_x2
    if p == 1:
        return diffs.abs().sum(dim=2)
    elif p == 'inf':
        return diffs.abs().max(dim=2).values
    elif p % 2 == 0:
        return diffs.pow(p).sum(dim=2).pow(1/p)
    else:
        return diffs.abs().pow(p).sum(dim=2).pow(1/p)
```
Note that the implementation above does not support `p=0`. Furthermore it is much slower an needs much more memory than PyTorch's native cdist implementation.

## Additional context

`RuntimeError: Exporting the operator cdist to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

**Comment by BowenBao** [comment]
@shubhambhokare1 wonder if your PR of linalg.norm could support this.

**Comment by qqaatw** [comment]
Looks supported by this PR: #75278

**Comment by swisman** [comment]
> Looks supported by this PR: #75278

Can confirm that it works, tested with torch == 1.12.1. Thus, issue can be closed!
