### ISSUE TITLE
The `extra_repr` of `nn.ZeroPad2d` is not correctly implemented

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#69205]
## To Reproduce

1. python -c "import torch; print(torch.nn.ZeroPad2d(padding=(0, 1, 0, 1)))"

This prints out `ZeroPad2d(padding=(0, 1, 0, 1), value=0.0)`.

2. python -c "import torch; print(torch.nn.ZeroPad2d(padding=(0, 1, 0, 1), value=0.0))"

The error is thrown as ```TypeError: __init__() got an unexpected keyword argument 'value' ```.

## Expected behavior

The first command should print the following content instead.
```
ZeroPad2d(padding=(0, 1, 0, 1))
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/padding.py#L465

**Comment by jbschlosser** [comment]
Agree that ideally the string representation should be `eval`uable. Thanks for opening a PR with the fix!
