### ISSUE TITLE
.cpu().numpy()[0] too many indices for array in pytorch 0.4

### ISSUE THREAD

**Issue by John1231983** [pytorch/pytorch#6921]
If you have a question or would like help and support, please ask at our
I am using pytorch 0.4 installed from conda. I got an error when using the below code
```
  File "train.py", line 378, in main
    loss += loss_.data.cpu().numpy()[0]/args.iter_size
IndexError: too many indices for array
```
When I downgrade pytorch to 0.3.1, this error disappears and the code run well. What should I change to run with the new version of pytorch?

- How you installed PyTorch (conda, pip, source): conda
- OS: Ubuntu 16.04
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version: 9.1
- GPU models and configuration: TitanX

**Comment by gchanan** [comment]
what's the size of `loss_`?  Most likely this is because the numpy() array you are getting back is now 0-dimensional, so you don't need the `[0]` anymore.

**Comment by John1231983** [comment]
Thanks for your feedback. I have deleted all zero `[0]` in the line and it worked fine in pytorch 0.4. But the problem is that why does it work in pytorch 0.3 with `[0]`?

**Comment by gchanan** [comment]
Because the tensor was 1-d and was converted to a 1-d numpy array, but is now 0-d and converted to a 0-d array.  Pytorch still let's you index 0-d tensor as if they were 1-d for backwards compatibility, so this usually doesn't come up, but numpy doesn't allow it.
