### ISSUE TITLE
Parameters of a model after .cuda() will be different objects with those before the call ?

### ISSUE THREAD

**Issue by Shan19900305** [pytorch/pytorch#69214]
## 📚 Documentation

There a note from https://pytorch.org/docs/stable/optim.html, note content is: "If you need to move a model to GPU via .cuda(), please do so before constructing optimizers for it. Parameters of a model after .cuda() will be different objects with those before the call.
In general, you should make sure that optimized parameters live in consistent locations when optimizers are constructed and used."

As i know, .cuda is a inplace operator, so parameter of models are same object after .cuda(). Do i miss something? 
Thank you a lot.

**Comment by H-Huang** [comment]
`.cuda()` copies the tensor into CUDA memory so it is not an inplace operator, they are different objects.
