### ISSUE TITLE
Issues with build from source

### ISSUE THREAD

**Issue by Priya4607** [pytorch/pytorch#69240]
I'm trying to build pytorch from source by following the instruction given here [here](https://github.com/pytorch/pytorch#from-source).
The installation isn't sucessful although I don't get any errors while building. It stops right after installing torchrun scripts with no errors. I'm not sure if I'm missing something here. I couldn't understand what went wrong I tried installing multiple times (each time in a new conda env), could someone help me figure out the issue? Attached build logs below. 
[log.txt](https://github.com/pytorch/pytorch/files/7636405/log.txt)

# Environment 

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: magma-cuda112

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: 3.19.6

Python version: 3.9.7 
Is CUDA available: Yes
CUDA runtime version: 11.4
GPU models and configuration: GK208B [GeForce GT 710]
Nvidia driver version: 470.82.00
cuDNN version: 8.2.4

Versions of relevant libraries:
[pip3] numpy==1.19.1
[conda] blas 1.0
[conda] magma-cuda102 2.5.2 1
[conda]mkl  2021.4.0
[conda]mkl-include  2021.4.0
[conda]mkl-service  2.4.0
[conda]mkl_fft  1.3.1
[conda]mkl_random  1.2.2 

## Steps to reproduce

1. Created a conda environemnt and installed necessary dependencies, 

    `conda install astunparse numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests 
     dataclasses`
2. As I couldn't find a matching version for 11.4 Cuda version went with magma-cuda112,
     `conda install -c pytorch magma-cuda112` 

3. Cloned the repo, 
    ```
     git clone --recursive https://github.com/pytorch/pytorch 
     cd pytorch 
     git submodule sync 
     git submodule update --init --recursive --jobs 0
    ```
4. Added some env variables, 
    ```
     export MAX_JOBS=2
     export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}\n
     export TORCH_CUDA_ARCH_LIST="3.5"
    ```
5. Ran, `python setup.py install`

cc @malfet @seemethere

**Comment by H-Huang** [comment]
I think pytorch should still be installed, what is the output for:
```
>>> import torch; torch.__version__
```

You can also try creating a conda env for python 3.8.5 (`conda create -n <myenv> python=3.8.5), I'm not sure if 3.9.x is officially supported

**Comment by Priya4607** [comment]
It says `1.11.0a0+git445b31a`
