### ISSUE TITLE
Confusing error message in Criterion output Tensor in v0.4

### ISSUE THREAD

**Issue by varunagrawal** [pytorch/pytorch#6925]
## Issue description

When computing operations on a Tensor returned from a Criterion on a per epoch basis, program always crashes with the error:

`RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58`

if we update the old-style `loss.data[0]` to just `loss`. This issue is not seen is we use `loss.item()`.

While I agree this issue may not be valid since in PyTorch 0.5 indexing of 0-dim tensors will cause an error, I am not convinced a cuda out-of-memory error should be happening.

## Code example

Using the `AverageMeter` class from the [ImageNet example](https://github.com/pytorch/examples/blob/master/imagenet/main.py), if we use `losses.update(loss, input.size(0))` we get the above error message.

But if we use `losses.update(loss.item(), input.size(0))`, the error does not show up.

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: TITAN X (Pascal)
Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7
/usr/local/MATLAB/R2017b/bin/glnxa64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn.so.7
/usr/local/cuda-8.0/lib64/libcudnn.so.7.0.1
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-900fef33.so.7.0.5
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudnn-900fef33.so.7.0.5

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] torch (0.4.0)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by gchanan** [comment]
See "Accumulating Losses" on the release notes: http://pytorch.org/2018/04/22/0_4_0-migration-guide.html.

**Comment by varunagrawal** [comment]
Awesome. Thanks @gchanan.

**Comment by apaszke** [comment]
Shouldn’t `.data` return a detached tensor anyway? It’s definitely not a good practice but it shouldn’t OOM
