### ISSUE TITLE
Fix environment script URL in ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by varunagrawal** [pytorch/pytorch#6926]
## Issue description

The issue template has a link to a script for collecting the user's environment to help with troubleshooting.

The URL to get the script is `https://github.com/pytorch/pytorch/tree/master/torch/utils/collect_env.py`. 
This returns the Github HTML page and not the python script.

The correct URL should be `https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py` aka the *raw* version.

## Code example

N/A

## System Info

N/A

**Comment by zou3519** [comment]
Awesome! Thanks for the fix, @varunagrawal!
