### ISSUE TITLE
torch.{h, v, d}split crash when sections = 0

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#69270]
## 🐛 Bug

It is similar with  #68970 . When sections = 0. `torch.hsplit(tensor, sections)` and `torch.vsplit(tensor, sections)` will crash (floating point exception)

## To Reproduce

```python
import torch
tensor = torch.rand(torch.Size([2, 2, 4]), dtype=torch.float32)
sections = 0
res1 = torch.hsplit(tensor, sections)
```
```python
import torch
tensor = torch.rand(torch.Size([2, 2, 4]), dtype=torch.float32)
sections = 0
res1 = torch.vsplit(tensor, sections)
```

floating point exception

## Expected behavior

They should not crash.

## Environment

- PyTorch Version (e.g., 1.0): 1.10.0, 1.9.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.9.5
- CUDA/cuDNN version: 11.1
- GPU models and configuration: RTX 3090

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by zou3519** [comment]
Hi-pri for crash

**Comment by Stamppot82** [comment]
Can you describe what is expected when you want to devide something over 0 sections?

**Comment by ilovepytorch** [comment]
> Can you describe what is expected when you want to divide something over 0 sections?

Just raise an error like `torch.tensor_split` instead of crash

**Comment by Jup11ter** [comment]
There is similar buggy behavior on `torch.Tensor.{h,v,d}split` in 1.9.0 and 1.10.0, which raises `Floating point exception (core dumped)` and crashes.

In 1.11.0 version, these APIs raise errors instead of crashing. It seems like that they were also fixed by this [commit](https://github.com/cyyever/pytorch_private/commit/fea71410cd0b3927c147a8cb4c90e598d089dc84).

```
import torch

tensor = torch.rand(torch.Size([2, 2, 4]), dtype=torch.float32)
sections = 0
def test():
	# tmp_result= torch.Tensor.hsplit(tensor, sections)
	# tmp_result= torch.Tensor.vsplit(tensor, sections)
	tmp_result= torch.Tensor.dsplit(tensor, sections)
	return tmp_result
res1 = test()
```
