### ISSUE TITLE
skip pytorch errors

### ISSUE THREAD

**Issue by LeZhengThu** [pytorch/pytorch#69275]
I'm using optuna package to tune my model parameters. There is an inverse operation in my code so some configurations raise RuntimeError about matrix singular of the inverse operation. Though I don't think that is a real inverse operation error, how can I skip this error? optuna offers catch function, but how can I know which error type to catch?

**Comment by zou3519** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/

As a quick reply to your question: The matrix singular error should always be a RuntimeError.
