### ISSUE TITLE
`torch.hub` defaults to `master` branch, crashes if it is `main`

### ISSUE THREAD

**Issue by Randl** [pytorch/pytorch#69284]
## 🐛 Bug

By default, `torch.hub` uses `master` branch to fetch. If the repo doesn't have one (e.g., defaults to `main`) the code crashes. I propose to either add `main` as an option to check or to check what is working branch of the repo.

## To Reproduce

Run `torch.hub.load` on repo without master branch (any recent repo defaulted to main)

## Expected behavior

The code defaults to working branch of the repo or at leasts checks for `main` option.

cc @nairbv @NicolasHug @vmoens @jdsgomes

**Comment by zou3519** [comment]
Do you have a stack trace for the crash?

**Comment by NicolasHug** [comment]
What pytorch version do you have? This should be fixed in the latest version, as I handled this case in https://github.com/pytorch/pytorch/pull/64364

**Comment by Randl** [comment]
I see, I'll check with latest version of pytorch

**Comment by NicolasHug** [comment]
I'll close the issue as this should have been fixed in the latest 1.10 release already, but @Randl please feel free to re-open if this issue persists in 1.10.
