### ISSUE TITLE
[FR]

### ISSUE THREAD

**Issue by ghostplant** [pytorch/pytorch#69293]
Given a torch operator, is it possible I only query the output shape of this operator instead of real executing it.

Currently I have to do infer shape by executing real workloads and get `some_op(x).shape`, which is very expensive.

**Comment by zou3519** [comment]
The mechanism exists already. See https://github.com/pytorch/pytorch/issues/55070 for tracking issue. 

The way you go about doing this is create a meta tensor from your tensor and then run the operation:
```
some_op(x.to(device='meta')).shape
```

**Comment by ghostplant** [comment]
Really nice, thanks!
