### ISSUE TITLE
torch.max/torch.min in Fx quantization might have a tuple ouput

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#69307]
As seen in [here](https://github.com/pytorch/pytorch/blob/4484c045132631783a1b15664d7cf528a1905395/torch/ao/quantization/fx/quantization_patterns.py#L1491-L1528), the fx quantization assumes that the `torch.min`/`torch.max` have only a tensor output. However according to the [docs](https://pytorch.org/docs/stable/generated/torch.max.html) they might have a tuple output with the min/max results and the indices (for argmin/argmax).

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by supriyar** [comment]
Can we close this given that https://github.com/pytorch/pytorch/pull/70958 has landed?
cc @jerryzh168, @terrychenism

**Comment by jerryzh168** [comment]
yes I think so, closing
