### ISSUE TITLE
PyTorch CUDA-11.5 readiness

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#69302]
As we are going to have CUDA-11.5 binary builds real soon we need to investigate:

- [ ] Binary size regressions/improvements compared to 11.3
- [ ] Default CPU/GPU memory overhead compared to 11.3
- [ ] Performance regression/importements compared to 11.3
- [ ] Driver enhanced compatibility: Is it installable in Google Collab?

cc @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Maybe also do this for 11.6

**Comment by seemethere** [comment]
We've done this, closing
