### ISSUE TITLE
Exception NameError: "global name 'FileNotFoundError' is not defined"

### ISSUE THREAD

**Issue by R1234A** [pytorch/pytorch#6932]
`Traceback (most recent call last):
  File "trainval_net.py", line 322, in <module>
    rois_label = fasterRCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 50, in forward
    rois, rpn_loss_cls, rpn_loss_bbox = self.RCNN_rpn(base_feat, im_info, gt_boxes, num_boxes)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faster-rcnn.pytorch/lib/model/rpn/rpn.py", line 87, in forward
    rpn_data = self.RPN_anchor_target((rpn_cls_score.data, gt_boxes, im_info, num_boxes))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/faster-rcnn.pytorch/lib/model/rpn/anchor_target_layer.py", line 157, in forward
    positive_weights = 1.0 / num_examples
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 320, in __rdiv__
    return self.reciprocal() * other
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensor
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fb842e6e3d0>> ignored`

This error is coming while implementing pytorch faster-rcnn repository. Any solutions please??

**Comment by soumith** [comment]
can you use the issue template, we need more information to help you.

**Comment by R1234A** [comment]
@soumith Using Pytorch 0.3.0 solves the problem.

**Comment by zou3519** [comment]
@R1234A are you using python 2?

AFAIK FileNotFoundError only exists in python 3, so this should be fixed

**Comment by zou3519** [comment]
@SsnL does the shutdown workers FileNotFoundError happen on python 2.7 as well?

**Comment by SsnL** [comment]
@zou3519 I haven't tested on py2. But I believe it should be an `IOError` with `ENOENT` errno.

**Comment by R1234A** [comment]
@zou3519  Yup I am using Python 2. To overcome this error of FileNotFoundError I have downgraded Pytorch from 0.4.0 version to 0.3.0. Use Pytorch 0.3.0 with Python 2, it will work fine.

**Comment by zou3519** [comment]
@R1234A alternatively, upgrading to Python 3 will fix the issue (and Python 3 is nicer than Python 2). We'll fix this though.

**Comment by bermanmaxim** [comment]
For a quick fix you can make dataloader.py python2 compatible by defining FileNotFoundError somewhere
```
try:
    FileNotFoundError
except NameError:
    FileNotFoundError = IOError
```

**Comment by isalirezag** [comment]
This error still exist in pytorch 0.4

**Comment by SsnL** [comment]
@isacarnekvist Yes it is fixed after 0.4

**Comment by isalirezag** [comment]
@SsnL I am still getting it...

**Comment by soumith** [comment]
@isalirezag did you build pytorch from source? It was fixed after 0.4 is released, so it will be in the next pytorch release.

**Comment by isalirezag** [comment]
I update it via `conda install pytorch torchvision cuda90 -c pytorch`
how should i build it from the source?

**Comment by soumith** [comment]
https://github.com/pytorch/pytorch#from-source

**Comment by azam-1** [comment]
Can anyone help me with my problem?

**Comment by ZiyuBao** [comment]
> @soumith Using Pytorch 0.3.0 solves the problem.

Same working with faster rcnn and got the error. Did you use torch==0.4.0?

**Comment by ZiyuBao** [comment]
> @soumith Using Pytorch 0.3.0 solves the problem.

I was also working with faster r-cnn and got the error. Downgrading to 0.3.0 solved FileNotFoundError but will produce another error: 
`self.ratio_list_batch[left_idx:(right_idx+1)] = torch.tensor(target_ratio.astype(np.float64)) # trainset ratio list ,each batch is same number
TypeError: 'module' object is not callable`

Where this error is related to `torch.tensor` in the above error message. Upgrading can solve this error but will produce the previous one.

How do you cope with the second error?
