### ISSUE TITLE
First and second derivatives for `nn.functional.fractional_max_pool2d` and `nn.functional.fractional_max_pool3d` are implemented incorrectly

### ISSUE THREAD

**Issue by saketh-are** [pytorch/pytorch#69322]
To reproduce, disable the relevant expectedFailures in their OpInfos:

https://github.com/pytorch/pytorch/pull/68922/files/aef50820ab2048e09f31d6a948ed46d0bd44ed80#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R10429

https://github.com/pytorch/pytorch/pull/68922/files/aef50820ab2048e09f31d6a948ed46d0bd44ed80#diff-18a0c3e7cd07089b34760028c387d39de1aa393172f1d5f123692106b3a3d144R10448

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by ngimel** [comment]
This is same issue as #69325, `fractional_max_pool` generates a random input if it's not specifically provided, so results for different invocations aren't the same

**Comment by albanD** [comment]
We need to fix the test to properly handle randomness in the function.
