### ISSUE TITLE
`CrossEntropyLoss` doesn't work using all of `weight`, `label_smoothing`, and ignoring indices

### ISSUE THREAD

**Issue by bryant1410** [pytorch/pytorch#69339]
## 🐛 Bug

`CrossEntropyLoss` doesn't work when using all of 1) `weight` param, `label_smoothing`, and ignoring some indices.

## To Reproduce

Run:

```python
import torch
from torch.nn import CrossEntropyLoss
CrossEntropyLoss(weight=torch.tensor([.2, .3]), label_smoothing=0.1)(torch.tensor([[1, 2], [3, .4]]), torch.tensor([-100, 1]))
```

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1150, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File ".../lib/python3.8/site-packages/torch/nn/functional.py", line 2846, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: index -100 is out of bounds for dimension 0 with size 2
```

Note that removing either the `weight` param, `label_smoothing` param, or ignored index makes it work:

```python
CrossEntropyLoss(label_smoothing=0.1)(torch.tensor([[1, 2], [3, .4]]), torch.tensor([-100, 1]))
```

```python
CrossEntropyLoss(weight=torch.tensor([.2, .3]))(torch.tensor([[1, 2], [3, .4]]), torch.tensor([-100, 1]))
```

```python
CrossEntropyLoss(weight=torch.tensor([.2, .3]), label_smoothing=0.1)(torch.tensor([[1, 2], [3, .4]]), torch.tensor([0, 1]))
```

This happens to me in both CPU and GPU.

## Expected behavior

To work, without crashing.

## Environment

<details>
<summary>collect_env.py output</summary>

```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1056-gcp-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.5.3
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.10.0
[pip3] torch-optimizer==0.3.0
[pip3] torchmetrics==0.6.0
[conda] blas                      2.112                       mkl    conda-forge
[conda] blas-devel                3.9.0            12_linux64_mkl    conda-forge
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-devel                 2021.4.0           ha770c72_730    conda-forge
[conda] mkl-include               2021.4.0           h8d4b97c_729    conda-forge
[conda] numpy                     1.19.5           py38h9894fe3_2    conda-forge
[conda] pytorch                   1.10.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.5.3              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchmetrics              0.6.0              pyhd8ed1ab_0    conda-forge
```
</details>

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @walterddr

**Comment by bryant1410** [comment]
I think the error is (at least) here:

https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L552

That fails for indices such as -100.

Apart from this, in the same method, a bit before, I believe this if-condition is wrong:

https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L542-L544

It should be `ignore_index < 0`, as the `ignore_index` should be negative. See this check:

https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L581

**Comment by jbschlosser** [comment]
Thanks for the detailed report and analysis!

The semantics of `ignore_index` allow it to be negative or positive, and the logic in question was written under the incorrect assumption that it can only be positive & within the range of valid class indices if it is used.

This explains the invalid usage of gather you pointed out:
https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L552

Further, this if-condition is certainly wrong, although I believe the logic should be run unconditionally rather than flipping the predicate, as a positive `ignore_index` is also supported:
https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L542-L544

Also, the check below is insufficient to determine if `ignore_index` is used. It's arguably somewhat useful to provide an error when `ignore_index != 100` (i.e. it's set to a non-default value), but a more robust check would be to verify that all target values are in the `[0, 1]` interval for this case. Performance concerns may indicate that we should not do the more robust check, however.
https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L581

**Comment by bryant1410** [comment]
Cool, thanks for the quick response!

> The semantics of `ignore_index` allow it to be negative or positive, and the logic in question was written under the incorrect assumption that it can only be positive & within the range of valid class indices if it is used.

Do you mean for this function? It seems like it should, but cross-entropy loss checks for it to be outside the valid class indices.

What should it mean when the `ignore_index` value is one of the valid classes?

> It's arguably somewhat useful to provide an error when `ignore_index != 100` (i.e. it's set to a non-default value)

Why does it matter that's non-default?

> but a more robust check would be to verify that all target values are in the `[0, 1]` interval for this case.

Shouldn't `target` values be between 0 and C-1?

**Comment by jbschlosser** [comment]
> What should it mean when the ignore_index value is one of the valid classes?

Same thing - if target is in class indices format, leave out all items from the loss calculation where ``` target[i] == ignore_index ```. This works now when `ignore_index` is within the valid class index range:

```python
import torch
output = torch.nn.CrossEntropyLoss(ignore_index=1)(torch.tensor([[1, 2], [3, .4]]), torch.tensor([0, 1]))
print(output)
```

> Shouldn't `target` values be between 0 and C-1?

Both class indices (long tensor) and class probabilities (float tensor) are supported by `CrossEntropyLoss`, and `ignore_index` doesn't make sense with the latter. The check below is under the case of target as class probabilities, hence the [0, 1] interval. The purpose of the check is to indicate that `ignore_index` is not supported for targets that are class probabilities.
https://github.com/pytorch/pytorch/blob/e2c7bd08b915128f29404e8bede3ce3e2e0b3787/aten/src/ATen/native/LossNLL.cpp#L581

> Why does it matter that's non-default?

Any non-default value means the user explicitly set `ignore_index`, and throwing an error is one way to indicate that it is not supported for the target as class probabilities case.

**Comment by gchanan** [comment]
we might kick it out of milestone if it doesn't meet the 1.10.1 timeline.
