### ISSUE TITLE
The new .to(device) doesn't work with nn.DataParallel

### ISSUE THREAD

**Issue by pobingwanghai** [pytorch/pytorch#6933]
the old code:
```
model=torch.nn.DataParallel(model,device_ids=range(torch.cuda.device_count()))
...
  for input, target in train_loader:
      input, target = Variable(input), Variable(target)
      input, target= input.cuda(), target.cuda()
```
this code works good
new code with .to(device)
```
model=torch.nn.DataParallel(model,device_ids=range(torch.cuda.device_count()))
...
  for input, target in train_loader:
       input, target = input.to(torch.cuda.current_device()), target.to(torch.cuda.current_device())
```
the input and target is only on GPU:0

**Comment by SsnL** [comment]
I don't really understand. Your old code also only copies `input` and `target` to the current GPU, not all GPUs.

Also, it's suggested to use `device` object rather than `.to(torch.cuda.current_device())`.

**Comment by soumith** [comment]
what do you mean by "doesn't work"?

**Comment by Randl** [comment]
The whole pattern is unclear a bit. If I'm using `DataParallel` i assume my model and data are supposed to be on all devices? However, tutorials say to copy it to one of them with `model.to(device='cuda:0')` or something similar. Is it replicated by default? Isn't it?

**Comment by SsnL** [comment]
A tensor is on one and only one device. There is no such thing that a tensor is on more than one devices.

**Comment by SsnL** [comment]
Close due to inactivity and that both code should work fine.

**Comment by Randl** [comment]
@SsnL Yeah, what I meant that data is supposed to be divided between devices. This done upon forward too? Also, does it matters which device out of those used I copy my model and data to? 
I believe this stuff should be clarified in docs.

**Comment by SsnL** [comment]
@Randl yes, it is done in `forward`. The process is described in doc here https://pytorch.org/docs/master/nn.html#torch.nn.DataParallel.
