### ISSUE TITLE
Dynamic output of Upsample causes InstanceNorm2d error in onnx.

### ISSUE THREAD

**Issue by quqixun** [pytorch/pytorch#69346]
## 🐛 Bug

Dynamic output of Upsample causes InstanceNorm2d error in onnx.

## To Reproduce

```python
import torch
import torch.nn as nn


class TestModel(nn.Module):

    def __init__(self, num_features, init_size=None):
        super(TestModel, self).__init__()

        if init_size is None:
            self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        else:
            self.upsample = nn.Upsample(size=init_size * 2, mode='bilinear', align_corners=True)

        self.innorm = nn.InstanceNorm2d(num_features, affine=False)

    def forward(self, x):
        out = self.upsample(x)
        out = self.innorm(out)
        return out


if __name__ == '__main__':

    init_size = 64
    num_features = 32
    x = torch.randn(4, num_features, init_size, init_size)

    model = TestModel(num_features, init_size=None)
    # model = TestModel(num_features, init_size=init_size)
    output = model(x)
    print(output.size())
    # torch.Size([4, 32, 128, 128])

    torch.onnx.export(
        model, x, 'test.onnx',
        export_params=True,
        verbose=True,
        opset_version=14,  # 9 ~ 14
        input_names=['x'],
        output_names=['output']
    )
```

Following infomation is obtained from [instance_norm in onnx/symbolic_opset9.py](https://github.com/pytorch/pytorch/blob/v1.10.0/torch/onnx/symbolic_opset9.py#L1390) by ```print(input)```, which means that the output of nn.Upsample in onnx is dynamic.

```
8 defined in (%8 : Float(*, *, *, *, strides=[524288, 16384, 128, 1], requires_grad=0, device=cpu) = onnx::Resize[coordinate_transformation_mode="align_corners", cubic_coeff_a=-0.75, mode="linear", nearest_mode="floor"](%input.1, %7, %6) # /home/quqixun/miniconda3/envs/pt10/lib/python3.8/site-packages/torch/nn/functional.py:3731:0)
```
This leads to the following error in [instance_norm in onnx/symbolic_opset9.py](https://github.com/pytorch/pytorch/blob/v1.10.0/torch/onnx/symbolic_opset9.py#L1390) because ```channel_size``` is None while affine=False in nn.InstanceNorm2d.
```
RuntimeError: Unsupported: ONNX export of instance_norm for unknown channel size.
```

## Expected behavior

Export onnx file of above simple model.

## Environment

- ubuntu 20.04
- python 3.8
- pytorch 1.10.0+cu113 via pip installing
- numpy 1.21.4

**Comment by BowenBao** [comment]
Tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1544448

**Comment by QitaoZhao** [comment]
I also meet this error.

**Comment by tongchangD** [comment]
Please tell me how to fix this error

only modify this network structure?

**Comment by lhao0301** [comment]
Also met the same problem.

**Comment by tongchangD** [comment]
> Also met the same problem.

you can see [address](https://github.com/pytorch/pytorch/issues/78233#issuecomment-1140638869)

**Comment by BowenBao** [comment]
Should be resolved by #78999

**Comment by ziadb-nvidia** [comment]
Any idea when this would make it to an official release? Nightly builds of Pt don't seem to work properly for me.

**Comment by wugoukanle** [comment]
I find out that this error in pytorch1.13 will not appear, but pytorch1.12.1 have. if hava to use pytorch1.12.1，maybe refer to https://zenn.dev/pinto0309/scraps/1fa87e6fa6f918
