### ISSUE TITLE
windows install pytorch and import error

### ISSUE THREAD

**Issue by zuofeng1997** [pytorch/pytorch#6937]
when I install pytorch in windows, and import torch, I got a error, "from torch._C imort *" failed, how to fix it?

**Comment by kaorou1** [comment]
I met the same mistake too

**Comment by Chloroplast7** [comment]
did you solve it? I met the same mistake!

**Comment by blessxu** [comment]
I think some people miss vs 201X redis or cuda.

**Comment by Lmy0217** [comment]
@kaorou1 @Chloroplast7 @wanganzhi @butterl Install VC Redist 2017 and intel-openmp solved it. [From this issue](https://github.com/pytorch/pytorch/issues/4518)

**Comment by Chloroplast7** [comment]
@Lmy0217 I have used Anaconda install pytorch successfully. But thanks a lot！I will also try to install VC Redist 2017 and intel-openmp，thanks for sharing！
