### ISSUE TITLE
[PyTorch] [conda] torchvision dependency cannot be satisfied by pytorch-cpu

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#6938]
With `pytorch-cpu` installed, installing `torchvision` still installs gpu pytorch.

**Comment by soumith** [comment]
i'm fixing this, it needs a torchvision-cpu package

**Comment by fmassa** [comment]
Is that the only solution?
Currently torchvision is python-only, and I was planning on making the C++/CUDA extensions be compiled on the fly so that we don't need multiple (redundant) cpu/cuda packages

**Comment by soumith** [comment]
let's not aim for a binary (that we ship to users) to compile C++/CUDA "on the fly". We dont know if users have everything installed.

**Comment by soumith** [comment]
latest commands on website are updated. for CPU only builds it is

```
conda install pytorch-cpu torchvision-cpu -c pytorch
```
