### ISSUE TITLE
[ONNX] export of F.pad  with boolean pad  fails in constant_pad_nd

### ISSUE THREAD

**Issue by genolve** [pytorch/pytorch#69388]
## 🐛 Bug

onnx.export with opset 14 of **F.pad** with type bool fails, **aten::constant_pad_nd** won't accept a bool

## To Reproduce

```python
dummy_data = torch.randn(1,  784)
class Network(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = torch.nn.Linear(784, 256)
        self.output = torch.nn.Linear(256, 10)
        
    def forward(self, x):
        mask = torch.zeros((1,392),dtype=torch.bool)
        mask = F.pad(mask, (0, 392), value=True)
        x.masked_fill_(mask, .314)
        x = F.sigmoid(self.hidden(x))
        x = F.softmax(self.output(x), dim=1)
        return x
      
m = Network()
torch.onnx.export(m,                
                  dummy_data,       
                  "smoke_test.onnx",
                  export_params=True,        
                  opset_version=14,          
                  do_constant_folding=True,  
                  input_names  = ['input_ids'],   
                  output_names = ['logits'],  
                  verbose=True
                 )
```

Error message:

> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> /tmp/ipykernel_667874/3979476880.py in <module>
>      33                   input_names  = ['input_ids'],
>      34                   output_names = ['logits'],
> ---> 35                   verbose=True
>      36                  )
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
>     303                         do_constant_folding, dynamic_axes,
>     304                         keep_initializers_as_inputs, custom_opsets,
> --> 305                         export_modules_as_functions)
>     306 
>     307 
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
>     120             do_constant_folding=do_constant_folding, dynamic_axes=dynamic_axes,
>     121             keep_initializers_as_inputs=keep_initializers_as_inputs,
> --> 122             custom_opsets=custom_opsets, export_modules_as_functions=export_modules_as_functions)
>     123 
>     124 
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, onnx_shape_inference, export_modules_as_functions)
>     731                                 fixed_batch_size=fixed_batch_size,
>     732                                 training=training,
> --> 733                                 dynamic_axes=dynamic_axes)
>     734 
>     735             # TODO: Don't allocate a in-memory string for the protobuf
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size, training, dynamic_axes)
>     497         args = (args, )
>     498 
> --> 499     graph, params, torch_out, module = _create_jit_graph(model, args)
>     500 
>     501     params_dict = _get_named_param_dict(graph, params)
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/onnx/utils.py in _create_jit_graph(model, args)
>     438         return graph, params, torch_out, None
>     439     else:
> --> 440         graph, torch_out = _trace_and_get_graph_from_model(model, args)
>     441         torch._C._jit_pass_onnx_lint(graph)
>     442         state_dict = _unique_state_dict(model)
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/onnx/utils.py in _trace_and_get_graph_from_model(model, args)
>     389 
>     390     trace_graph, torch_out, inputs_states = \
> --> 391         torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
>     392     warn_on_static_input_change(inputs_states)
>     393 
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/jit/_trace.py in _get_trace_graph(f, args, kwargs, strict, _force_outplace, return_inputs, _return_inputs_states)
>    1164     if not isinstance(args, tuple):
>    1165         args = (args,)
> -> 1166     outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
>    1167     return outs
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
>    1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
>    1109                 or _global_forward_hooks or _global_forward_pre_hooks):
> -> 1110             return forward_call(*input, **kwargs)
>    1111         # Do not call functions when jit is used
>    1112         full_backward_hooks, non_full_backward_hooks = [], []
> 
> ~/anaconda3/envs/torch/lib/python3.7/site-packages/torch/jit/_trace.py in forward(self, *args)
>     130             _create_interpreter_name_lookup_fn(),
>     131             self.strict,
> --> 132             self._force_outplace,
>     133         )
>     134 
> 
> RuntimeError: 0INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1638173422635/work/torch/csrc/jit/ir/alias_analysis.cpp":611, please report a bug to PyTorch. We don't have an op for aten::constant_pad_nd but it isn't a special case.  Argument types: Tensor, int[], bool, 
> 
> Candidates:
> 	aten::constant_pad_nd(Tensor self, int[] pad, Scalar value=0) -> (Tensor)

## Expected behavior
onnx.export of F.pad should work with a boolean pad 

## Environment

Collecting environment information...
PyTorch version: 1.11.0.dev20211129
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3)
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.18.0-348.el8.x86_64-x86_64-with-centos-8
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 with Max-Q Design
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.11.0.dev20211129
[pip3] torchaudio==0.11.0.dev20211129
[pip3] torchvision==0.12.0.dev20211129
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.0            py37h42c9631_2  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.20.3           py37hf144106_0  
[conda] numpy-base                1.20.3           py37h74d4b33_0  
[conda] pytorch                   1.11.0.dev20211129 py3.7_cuda11.3_cudnn8.2.0_0    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                0.11.0.dev20211129      py37_cu113    pytorch-nightly
[conda] torchvision               0.12.0.dev20211129      py37_cu113    pytorch-nightly

## Additional context
A trivial word-around is to replace True/False with 1/0 
However it is  non-trivial in a model like: https://github.com/lucidrains/routing-transformer

**Comment by BowenBao** [comment]
tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1542301

**Comment by justinchuby** [comment]
```
Exported graph: graph(%input_ids : Float(1, 784, strides=[784, 1], requires_grad=0, device=cpu),
      %hidden.weight : Float(256, 784, strides=[784, 1], requires_grad=1, device=cpu),
      %hidden.bias : Float(256, strides=[1], requires_grad=1, device=cpu),
      %output.weight : Float(10, 256, strides=[256, 1], requires_grad=1, device=cpu),
      %output.bias : Float(10, strides=[1], requires_grad=1, device=cpu)):
  %/Constant_output_0 : Bool(1, 784, strides=[784, 1], requires_grad=0, device=cpu) = onnx::Constant[value=<Tensor>, onnx_name="/Constant"](), scope: __main__.Network:: # <ipython-input-7-e3a1c6c0a0db>:10:0
  %/Constant_1_output_0 : Float(device=cpu) = onnx::Constant[value={0.314}, onnx_name="/Constant_1"](), scope: __main__.Network:: # <ipython-input-7-e3a1c6c0a0db>:10:0
  %/Where_output_0 : Float(1, 784, strides=[784, 1], requires_grad=0, device=cpu) = onnx::Where[onnx_name="/Where"](%/Constant_output_0, %/Constant_1_output_0, %input_ids), scope: __main__.Network:: # <ipython-input-7-e3a1c6c0a0db>:10:0
  %/hidden/Gemm_output_0 : Float(1, 256, strides=[256, 1], requires_grad=1, device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1, onnx_name="/hidden/Gemm"](%/Where_output_0, %hidden.weight, %hidden.bias), scope: __main__.Network::/torch.nn.modules.linear.Linear::hidden # /pytorch/torch/nn/modules/linear.py:114:0
  %/Sigmoid_output_0 : Float(1, 256, strides=[256, 1], requires_grad=1, device=cpu) = onnx::Sigmoid[onnx_name="/Sigmoid"](%/hidden/Gemm_output_0), scope: __main__.Network:: # /pytorch/torch/nn/functional.py:1967:0
  %/output/Gemm_output_0 : Float(1, 10, strides=[10, 1], requires_grad=1, device=cpu) = onnx::Gemm[alpha=1., beta=1., transB=1, onnx_name="/output/Gemm"](%/Sigmoid_output_0, %output.weight, %output.bias), scope: __main__.Network::/torch.nn.modules.linear.Linear::output # /pytorch/torch/nn/modules/linear.py:114:0
  %logits : Float(1, 10, strides=[10, 1], requires_grad=1, device=cpu) = onnx::Softmax[axis=1, onnx_name="/Softmax"](%/output/Gemm_output_0), scope: __main__.Network:: # /pytorch/torch/nn/functional.py:1838:0
  return (%logits)
```

**Comment by justinchuby** [comment]
<img width="772" src="https://user-images.githubusercontent.com/11205048/193465454-df2212b5-e8ca-4226-ac38-f58c7e7b492f.png">
