### ISSUE TITLE
Pytorch 0.4.0 failed build

### ISSUE THREAD

**Issue by floringogianu** [pytorch/pytorch#6939]
## Issue description
Pytorch 0.4.0 build fails on an unsuported GPU (GeForce GTX 960M) when building `ATen_generated_SpectralOps.cu.o`

```
[ 51%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_RoiPooling.cu.o
[ 51%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_SparseMM.cu.o
/home/florin/Tools/pytorch40/aten/src/ATen/native/cuda/Embedding.cu(37): warning: function "__any"
/usr/local/cuda/include/device_atomic_functions.h(180): here was declared deprecated ("__any() is deprecated in favor of __any_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

[ 52%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_SpectralOps.cu.o
/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor&, at::Tensor&, at::Tensor&>}; bool <anonymous> = true; _Elements = {at::Tensor&, at::Tensor&, at::Tensor&}]’:

...
[see full log below]

src/ATen/CMakeFiles/ATen.dir/build.make:1183: recipe for target 'src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_SpectralOps.cu.o' failed
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_SpectralOps.cu.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'src/ATen/CMakeFiles/ATen.dir/all' failed
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
## Code example

[Full error_log](https://gist.github.com/floringogianu/29fc809f875e10270f80d673401c7324)

## System Info
- PyTorch: 0.4.0 200fb22b2
- How you installed PyTorch: source (installation failed)
- Build command you used:

```
export CMAKE_PREFIX_PATH=/home/florin/Tools/anaconda3
conda create -n torch40 python==3.6
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
conda install -c pytorch magma-cuda91

git checkout tags/v0.4.0
git submodule update --init

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/florin/Tools/anaconda3/envs/torch40/lib/ (it will not find mkl_64.so otherwise)

python setup.py install
```

- OS: Ubuntu 17.10 x86_64
- Python version: 3.6.0
- CUDA/cuDNN version: release 9.1, V9.1.85 / cudnn 7.1 patchlevel 3
- GPU models and configuration: GeForce GTX 960M - 390.48 
- GCC version (if compiling from source): 6.4.0 (`gcc`, `g++`, `cc`, `c++`)
- CMake version: 3.9.4 in /anaconda/envs/torch40/cmake
- Versions of any other relevant libraries: `conda` 4.5.1

**Comment by apaszke** [comment]
cc: @SsnL

**Comment by SsnL** [comment]
It's not just SpectralOps. All cuda files with tuples failed. It is because this NVCC [bug](https://devtalk.nvidia.com/default/topic/1028112/cuda-setup-and-installation/nvcc-bug-related-to-gcc-6-lt-tuple-gt-header-/) where it doesn't work with gcc 6.4 tuple header nicely. This has also been reported in [other](https://github.com/kokkos/kokkos/issues/1306) [projects](https://github.com/caffe2/caffe2/issues/1898) as well. According to the NVIDIA forum thread, a fix will come out (at earliest) with next CUDA release.

For now, you can use gcc 6.3 or lower.

**Comment by floringogianu** [comment]
@apaszke @SsnL thank you for the quick reply, I'm now compiling `gcc 6.3` and will report back. I tried with `gcc 5.4` and it failed because of #5229 and #5136

**Comment by sdmonov** [comment]
There are problems with ``GCC 5`` and especially ``libstdc++-5-dev`` packages in Ubuntu 17.10 and newer related to bad build from Ubuntu. This won't be fixed as gcc 5 is considered deprecated. You can try compile gcc 5 / libstdc++ 5 from source if you need to use gcc 5. Unfortunately Ubuntu will not fix this issue. #5229 has more info why this happens.

**Comment by floringogianu** [comment]
Yeah, eventually I was able to compile it with `gcc 4.8.5` after fixing some headers and downloading some missing library, as discussed [here](https://medium.com/@Inoryy/compiling-pytorch-4-0-on-ubuntu-17-10-with-cuda-9-0-and-python-3-6-6769a0df56d5). 

Will try and build `gcc 5.5` at some point, I was not able to do that with `gcc 6.3`, there are some known issues with `gcc 6` and `Ubuntu 17.10`.
