### ISSUE TITLE
`torch.cartesian_prod` failed when input tensors have different dtypes

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#69409]
## 🐛 Bug

`torch.cartesian_prod` failed when input tensors have different dtypes. This is not expected because `cartesian_prod` returns a tensor equivalent to converting all the input tensors into lists, do itertools.product on these lists, and finally convert the resulting list into tensor.

## To Reproduce

```python
import torch
tensor_1 = torch.randint(-1,1,torch.Size([3]), dtype=torch.int64)
tensor_2 = torch.rand([3], dtype=torch.float64)
import itertools
res2 = torch.tensor(list(itertools.product(tensor_1.tolist(), tensor_2.tolist())))
# succeed
res1 = torch.cartesian_prod(tensor_1, tensor_2)
# RuntimeError: meshgrid expects all tensors to have the same dtype
```

## Expected behavior

It succeeds when input tensors have different dtypes.

## Environment

PyTorch Version (e.g., 1.0): 1.10.0
OS (e.g., Linux): Linux
How you installed PyTorch (conda, pip, source): conda
Python version: 3.9.5
CUDA/cuDNN version: 11.1
GPU models and configuration: RTX 3090

cc @nairbv @mruberry

**Comment by albanD** [comment]
Closing as expected behavior

**Comment by ilovepytorch** [comment]
@ngimel I think this is an inconsistency in the documentation so it'd better add a note or warning in the documentation.

**Comment by albanD** [comment]
> I think this is an inconsistency in the documentation

Could you clarify which inconsistencies?

**Comment by ngimel** [comment]
We will accept a documentation fix for this
