### ISSUE TITLE
[Feature request]: Accelerate bernoulli number generation on CPU 

### ISSUE THREAD

**Issue by MlWoo** [pytorch/pytorch#6940]
The bernoulli numbers in current version are generated in series by a single, naive and serial stream. The performance of OPs like Dropout which call the steam is poor on CPU. The evidence of some case shows that the performance on CPU is 250X slower than that on GPU. But the gap should not be that great in consideration of the peak theoretical performance.  
The code shows it is clear that [bernoulli number generation of GPU](https://github.com/pytorch/pytorch/blob/master/aten/src/THC/generic/THCTensorRandom.cu#L414) is not restricted by the only thread. Furtherly, the code also calls the lib of cuda to create random number([curand_uniform_double](https://github.com/pytorch/pytorch/blob/master/aten/src/THC/generic/THCTensorRandom.cu#L400)).

Actually, [Intel-Caffe](https://github.com/intel/caffe) takes advantage of [VSL math lib and openmp](https://github.com/intel/caffe/blob/9f0108f5a82d3a180f9b8837b7b09d72d8af8dcc/src/caffe/util/math_functions.cpp#L424-L457) to do the same work on CPU as that on GPU in PyTorch. We may borrow the code to help PyTorch to get better performance on CPU. However, I also notice that the seed of random number stream of current version could be set mannually. We maybe change the code in Intel-Caffe slightly if necessary.

@cpuhrsch Your advice is important to us because of your effort on CPU. Could you spare some time to look into the part of code? Looking forward to your point.

**Comment by cpuhrsch** [comment]
Thank you for reopening this @MlWoo.

In general it's ok to use MKL and derivatives if they are available. However, we need to also leave the option of providing a correct implementation to users who do not have access to it, since we can't expect OSS users to have it. So, as long as you can detect whether it's available or not and default to the current implementation if it's not, this would be good to have. Do you also expect there to be a speed-up on an AMD CPU? Otherwise we might need to check for that as well.

**Comment by soumith** [comment]
one constraint to keep in mind is that the RNG should be consistent whether it's built with our without MKL, with our without AVX2 feature, etc.

**Comment by MlWoo** [comment]
@soumith I do not think the requirement is reasonable. If we have the version compiled with MKL, we can also freeze the RNG to compare the results of our other developments which use the RNG. In other words, it do not affect the consistency of itself. Actually, do we make sure the RNG on CPU and on GPU are the same if the seeds are the same? Or do we compare the result of RNG from PyTorch with that from TF  if the seeds are the same. I think it is OK if the RNG does not destroy the self-integrity and self-consistency in a version with or without MKL.  Further, it is maybe not necessary to make sure the integrity and consistency in two versions compiled in different envs.

**Comment by soumith** [comment]
@MlWoo will the RNG be consistent across CPUs, i.e. will it give consistent results on a CPU with AVX and CPU without AVX and CPU with AVX2, etc.?
I think relaxing MKL requirement is a bit more feasible and I am willing to make that trade-off,  because we give binaries to our users with MKL.
However, if it's not consistent to expect that different CPU features are generating different RNG.

**Comment by MlWoo** [comment]
@soumith I agree with your view that the RNG should not depend on the CPU features. thanks a lot.

**Comment by MlWoo** [comment]
@cpuhrsch @soumith 
There are some tricky problems should be solved. 
1). [These lines](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L111-L119) shows [the bernoulli_ operation with a scalar probability](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L116)  which is exactly called by `Dropout` is implemented by reusing [the bernoulli operation with a tensor probability](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L112).   And the bernoulli operation with a tensor is instanced only in float and double type. The view could be drew from [the scripts code](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Declarations.cwrap#L3615-L3616). So there are possibly 2 redundant operations(filling a tensr with a scalar AND copying & convcerting floating-point to other type) in term with the bernoulli_ operation with a scalar probability. 
 However, the bernoulli_ operation with a scalar probability could be implemtented by calling  [`THTensor_(bernoulli)` ](https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THTensorRandom.cpp#L54) directly.  I can not figure out why we abandon the simple and efficient way and select a complex and time-consuming path.
2). [The scripts code](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/Declarations.cwrap#L3612-L3630) of  `bernoulli` operation does not provide a interface for a scalar probability and is in `at` scope. But [the scripts code](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L147-L149) of  `bernoulli_` operation does provide that and in `at::native` scope. As what I know, the suffix of `_` just suggests the operation runs in-place. I am also confused by the convention.

I plan to boost `THTensor_(bernoulli)` with vsl and opoenmp. There are my plans.
1). adding a interface for a scalar probability to `bernoulli`. But bernoulli could be not parsed as a in-place functions.  It maybe need to modify the parse code.
2). recover `bernoulli_` in same level of '`bernoulli'. In other words, `bernoulli_` could be visited in the `at` scope

 I am really looking for your professinal advice.

**Comment by cpuhrsch** [comment]
@MlWoo as a first note: Is it possible to use tbb instead of openmp? We're trying to not use openmp, because it doesn't allow things such as work stealing and openmp4.0 doesn't work with MSVC etc.

**Comment by MlWoo** [comment]
@cpuhrsch yeah. It is not hard to replace openmo with tbb. But the code of `THTensor_(bernoulli)`  has not been adapted in OOP. The code will be not elegant if we modify the code with tbb. If PyTorch plans to rewrite the module, I think it is easy to use tbb instead of openmp. 
Actually, I am more concerned with the 'chaos' phenomenon of `bernoulli` and `bernoulli_`. Could you give me some hint?

**Comment by cpuhrsch** [comment]
Hello @MlWoo - let me look into why we've setup bernoulli and bernoulli_ in the way we did (this was before my time). If there's no reason, I'll send a PR to fix what you described in your previous message, which will make it easier to implement your performance improvements, i.e. provide you with a single function that will need to be optimized.
