### ISSUE TITLE
KeyError("module name can't contain \".\"") breaking change 0.4 not mentioned anywhere

### ISSUE THREAD

**Issue by mario98** [pytorch/pytorch#6941]
## Issue description

For some reason, I had to compile pytorch from source. I did this using the latest master five days ago. Previously, I worked with pytorch 0.3. I have pretrained models which I now want to load. However, due to changes in name conventions, I can not create a model such that the layer names are corresponding to the layer names in my pretrained model (which is required if you want to load that pretrained model) Reason: The model names contain a dot, e.g. "norm.1". I receive the error message: `KeyError("module name can't contain \".\"")`. I didn't receive a message (or even a warning) before.

Not good. Pytorch should not break things because developers feel that dots should not be allowed in module names any more. I ask you to reconsider this decision, maybe add a warning first before actually breaking things, or to clearly communicate a workaround such that I can still use my pretrained models from previous pytorch versions.

Update:
I've seen that pytorch 0.4 is out now. In the [migration guide](http://pytorch.org/2018/04/22/0_4_0-migration-guide.html), this breaking change is not mentioned either. (which I am sure exists in the final version, too, [looking at the code](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L168))

## Code example

```
class MyModule(nn.Sequential):
  [...]
  self.add_module('norm.1', BatchNorm(num_input_features))
```

## System Info
Installed pytorch from source (master) 5 days ago. Using python 3.5 with conda 4.3. (BROKEN VERSION)
vs.
Installed pytorch though conda (a few days ago), using python 3.5 with conda 4.3 (WORKING)

**Comment by fmassa** [comment]
Oh, we have missed this breaking change in the migration guide! Thanks for pointing out, we will fix it!

Here is an example PR that can fix your loading logic to fix the `.` in the name of the module https://github.com/pytorch/vision/pull/474

cc @SsnL is there an easier way for users to load old state-dicts that contains dots?

**Comment by mario98** [comment]
Thanks, it was indeed DenseNet for which the error occurred, but used in a different repo. I'm glad to see that the community has already responded with a workaround, I will have a look.

P.S. I found that this change was actually commited [just six says ago](https://github.com/pytorch/pytorch/commit/6a41e2dc4725470062de187eda00399c9bec0479#diff-527b04fec26e044c060ad28b22e842be), so everyone using an earlier version should be fine. And the change was actually introduced to _improve_ backward compatibility by appending the version to the module name. What an irony. :smile:

**Comment by sinnis1991** [comment]
I 'm new learner and I quite don't understand how to fix it. Is that just remove the dot in the module name?

**Comment by SsnL** [comment]
@sinnis1991 You should replace the dots in the names/keys in manual `register_module/buffer/parameter` calls.
