### ISSUE TITLE
import torch macos m1 --> ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by mit-vincode** [pytorch/pytorch#69417]
Hello! I have a similar problem with https://github.com/pytorch/pytorch/issues/47978
As I understand it, this question is already closed, therefore, I create a new one:
Python3.10 , PyCarm (PyCharm 2021.2.3 (Community Edition). Build #PC-212.5457.59, built on October 19, 2021 Runtime version: 11.0.12+7-b1504.40 aarch64. VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.   macOS 11.5.1GC: G1 Young Generation, G1 Old Generation. Memory: 2048M. Cores: 8)
_____________
code:
import torch
result:
ModuleNotFoundError: No module named 'torch'
 ___________________
All attempts to solve the problem through conda and the installation of numpy-1.21.4-cp310-cp310-macosx_10_9_x86_64.whl were unsuccessful 

(base) bolkhovskiydmitriy @ MacBook-Pro-Bolkhovskiy ~% which python
/ opt / anaconda3 / bin / python

/ opt / anaconda3 / bin / pip
(base) bolkhovskiydmitriy @ MacBook-Pro-Bolkhovskiy ~%

(base) bolkhovskiydmitriy @ MacBook-Pro-Bolkhovskiy ~% which pip3
/ opt / anaconda3 / bin / pip3

That being said, I am using python3.10 - other packages work, except for the import torch command
But when I enter in terminal% python —version —-> the result is Python 3.9.7
(base) bolkhovskiydmitriy @ MacBook-Pro-Bolkhovskiy ~% python --version
Python 3.9.7
Result: PackagesNotFoundError: The following packages are not available from current channels:

I do not want to downgrade python, because other packages do not work correctly there.
Please help me figure out the problem

import torch
ModuleNotFoundError: No module named 'torch'

And when I try to install torchvision directly from the project folder via pip, I get the following error:

(base) (venv) bolkhovskiydmitriy @ MacBook-Pro-Bolkhovskiy CamGroup02% pip install torchvision
Collecting torchvision
Using cached torchvision-0.2.2.post3-py2.py3-none-any.whl (64 kB)
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from torchvision) (1.21.4)
Requirement already satisfied: six in ./venv/lib/python3.10/site-packages (from torchvision) (1.16.0)
Using cached torchvision-0.2.2.post2-py2.py3-none-any.whl (64 kB)
Using cached torchvision-0.2.2-py2.py3-none-any.whl (64 kB)
Using cached torchvision-0.2.1-py2.py3-none-any.whl (54 kB)
Using cached torchvision-0.2.0-py2.py3-none-any.whl (48 kB)
Using cached torchvision-0.1.9-py2.py3-none-any.whl (43 kB)
Requirement already satisfied: pillow in ./venv/lib/python3.10/site-packages (from torchvision) (8.4.0)
Using cached torchvision-0.1.8-py2.py3-none-any.whl (37 kB)
Using cached torchvision-0.1.7-py2.py3-none-any.whl (23 kB)
ERROR: Cannot install torchvision == 0.1.7, torchvision == 0.1.8, torchvision == 0.1.9, torchvision == 0.2.0, torchvision == 0.2.1, torchvision == 0.2.2, torchvision == 0.2 .2.post2 and torchvision == 0.2.2.post3 because these package versions have conflicting dependencies.

The conflict is caused by:
torchvision 0.2.2.post3 depends on torch
torchvision 0.2.2.post2 depends on torch
torchvision 0.2.2 depends on torch
torchvision 0.2.1 depends on torch
torchvision 0.2.0 depends on torch
torchvision 0.1.9 depends on torch
torchvision 0.1.8 depends on torch
torchvision 0.1.7 depends on torch

To fix this you could try to:
1.loosen the range of package versions you've specified
2.remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.1.2; however, version 21.3.1 is available.
You should consider upgrading via the '/ Users / bolkhovskiydmitriy / PythonData / aVision / CamGroup02 / venv / bin / python -m pip install --upgrade pip' command.

HELP!

cc @ezyang @seemethere @malfet @albanD

**Comment by malfet** [comment]
Pytorch binary builds for Python-3.10 are not available yet, work is tracked in https://github.com/pytorch/pytorch/issues/66424
