### ISSUE TITLE
`torch.combinations(tensor, r)` should not fail when r=0

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#69414]
## 🐛 Bug

`torch.combinations(tensor, r)` should not fail when r=0. Instead, it should return an empty tensor like `itertools.conbinations`.

## To Reproduce

```python
import torch
tensor = torch.rand(torch.Size([4]))
r = 0
import itertools
res1 = list(itertools.combinations(arg_1.tolist(), r=r))
print(res1)
# [()]
res2 = torch.combinations(tesnor, r=r)
# RuntimeError: Expect a positive number, but got 0
```

## Expected behavior

It should return an empty tensor.

## Environment

PyTorch Version (e.g., 1.0): 1.10.0
OS (e.g., Linux): Linux
How you installed PyTorch (conda, pip, source): conda
Python version: 3.9.5
CUDA/cuDNN version: 11.1
GPU models and configuration: RTX 3090

cc @mruberry @rgommers

**Comment by albanD** [comment]
We would accept a PR adding this.

**Comment by johnpeterson123** [comment]
I'm working on a fix for this!
