### ISSUE TITLE
Why max(a, b) != relu(b-a)+a?

### ISSUE THREAD

**Issue by kaijieshi7** [pytorch/pytorch#69429]
## ❓ Questions and Help
I want to translate maximum to relu, but the results is unexpectedly.

```
import torch
channels = 320
hw = 1 # also can be 10 or other int get similar result
x = torch.rand(channels, channels, hw, hw, dtype=torch.float32, requires_grad=False).cuda()

a = torch.nn.Conv2d(channels, channels, 5, padding=2, bias=False, groups=channels).eval().cuda()
b = torch.nn.Conv2d(channels, channels, 5, padding=2, bias=False, groups=channels).eval().cuda()

y1 = torch.maximum(x, a(x))
y2 = x+torch.nn.functional.relu(a(x)-x)
y3 = a(x)+torch.nn.functional.relu(x-a(x))

print(torch.sum(y1-y2))
print(torch.sum(y1-y3))
```

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by dev-jwel** [comment]
I got a value 2.4997e-06 and this result may caused by [roundoff error](https://en.wikipedia.org/wiki/Round-off_error). when b > a, c = b - a may diffirent from its real value and c + a diffirent from b(for single element).

**Comment by ngimel** [comment]
This is expected behavior for floating point computations, as @dev-jwel said.

**Comment by kaijieshi7** [comment]
3q
