### ISSUE TITLE
[caffe2] eigen has no member named ‘floor’ auto target_lvls

### ISSUE THREAD

**Issue by likedongxi** [pytorch/pytorch#6942]
I am compiling caffe2, following the document:
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile
after the command `sudo make install`, I got this error:
`/home/jack/packageLinux/pytorch/pytorch/caffe2/operators/collect_and_distribute_fpn_rpn_proposals_op.cc:39:59:   required from here
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:56:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<float>::type {aka __vector(4) float}’ [-Wignored-attributes]
/home/jack/packageLinux/pytorch/pytorch/caffe2/operators/collect_and_distribute_fpn_rpn_proposals_op.cc: In function ‘caffe2::ERArrXXf caffe2::utils::MapRoIsToFpnLevels(Eigen::Ref<const Eigen::Array<float, -1, -1, 1, -1, -1> >, float, float, float, float)’:
/home/jack/packageLinux/pytorch/pytorch/caffe2/operators/collect_and_distribute_fpn_rpn_proposals_op.cc:39:62: error: ‘const class Eigen::CwiseUnaryOp<Eigen::internal::scalar_add_op<float>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<float>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_log_op<float>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_add_op<float>, const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<float>, const Eigen::Array<float, -1, -1, 1, -1, -1> > > > > >’ has no member named ‘floor’
   auto target_lvls = (lvl0 + (s / s0 + 1e-6).log() / log(2)).floor();
                                                              ^~~~~
In file included from /usr/include/eigen3/Eigen/Core:277:0,
                 from /home/jack/packageLinux/pytorch/pytorch/caffe2/utils/eigen_utils.h:6,
                 from /home/jack/packageLinux/pytorch/pytorch/caffe2/operators/collect_and_distribute_fpn_rpn_proposals_op.h:6,
                 from /home/jack/packageLinux/pytorch/pytorch/caffe2/operators/collect_and_distribute_fpn_rpn_proposals_op.cc:1:`
It seems that  `(lvl0 + (s / s0 + 1e-6).log() / log(2))` doesn't has a member function called `floor`, Did anyone met this error? How to solve this problem? Any help will be appreciated. Thanks.
Some  information:
gcc version:6.4.0
cuda version: 9.0
cudnn version: 7.0.5
Eigen version: 3.2.8-r2

**Comment by pjh5** [comment]
Can you post the output of the cmake command?

**Comment by likedongxi** [comment]
@pjh5 Thanks for your reply. I solved the problem of "no member named ‘floor’ " by myself. I upgrade Eigen from 3.2.8-r2 to 3.3.4, then the problem of "no member named ‘floor’ " was solved.
