### ISSUE TITLE
`torch.movedim` trigger internal assert failure!

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#69432]
## 🐛 Bug

When the tensor is 0 dimensional and both source and destination are 0, `torch.movedim` will trigger internal assert failure.

## To Reproduce

```python
import torch

tensor = torch.rand(torch.Size([]))
res1 = torch.movedim(tensor, 0, 0)
# RuntimeError: std::distance(source_dims.begin(), source_iter) == rest_dimINTERNAL ASSERT FAILED at "../aten/src/ATen/native/TensorShape.cpp":2448, please report a bug to PyTorch.
```

## Expected behavior

Do not trigger internal assert failure.

## Environment

PyTorch Version (e.g., 1.0): 1.10.0
OS (e.g., Linux): Linux
How you installed PyTorch (conda, pip, source): conda
Python version: 3.9.5
CUDA/cuDNN version: 11.1
GPU models and configuration: RTX 3090

cc @brianjo @mruberry

**Comment by albanD** [comment]
This should raise a nice error message indeed.

**Comment by anjali411** [comment]
+1 for it to be a no-op

**Comment by ilovepytorch** [comment]
@anjali411 @albanD For the same reason as [torch.transpose](https://github.com/pytorch/pytorch/issues/69433#issuecomment-988620472), I think this should raise an error.
1. torch.rand([]) does not have dimension, so it is invalid to move the dimension 0 of it.
2. `torch.movedim` is expected to have the same behavior with `numpy.moveaxis` based on the [document](https://pytorch.org/docs/stable/generated/torch.moveaxis.html?highlight=moveaxis#torch.moveaxis) "Alias for torch.movedim(). This function is equivalent to NumPy’s moveaxis function."
```python
import torch
import numpy

t = torch.randn([])
numpy.moveaxis(t.tolist(), 0, 0)
# AxisError: source: axis 0 is out of bounds for array of dimension 0
```

**Comment by albanD** [comment]
cc @mruberry do you have an opinion on this one?
Should it be silently a no-op or raise an error for consistency with numpy?

**Comment by albanD** [comment]
Re-opening until we get the answer from @mruberry

**Comment by mruberry** [comment]
Sorry for the late reply.

The example above is a little misleading. Let's look at an elaborated example with some additional annotations:

```
import torch
import numpy as np

# This is the previous example
t = torch.randn([])
np.moveaxis(t.tolist(), 0, 0)
: AxisError: source: axis 0 is out of bounds for array of dimension 0

# What is t.tolist()?
# It's just a number!
t.tolist()
: -0.7139869332313538

# A more readable version of the above example
np.moveaxis(-.71, 0, 0)
: AxisError: source: axis 0 is out of bounds for array of dimension 0

# OK, so when np.moveaxis is called on a number it throws an error, sure
# What about some arrays?

# Creating an array with one dimension of size zero works
a = np.random.randn(0)
a 
: array([], dtype=float64)
a.shape
: (0,)
np.moveaxis(a, 0, 0)
: array([], dtype=float64)

# Creating an array with no dimensions does not work
a = np.empty(())
a 
: array(4.64918225e-310)
a.shape
: ()
np.moveaxis(a, 0, 0)
: AxisError: source: axis 0 is out of bounds for array of dimension 0

# swapaxes also fails
np.swapaxes(a, 0, 0)
: AxisError: axis1: axis 0 is out of bounds for array of dimension 0

# transpose also fails
np.transpose(a, [0])
: ValueError: axes don't match array

# torch.permute also fails
t = torch.from_numpy(a)
torch.permute(t, (0,))
: RuntimeError: number of dims don't match in permute

# torch.transpose does work!
torch.transpose(t, 0, 0)
: tensor(4.64918225e-310, dtype=torch.float64)
```

`torch.transpose` is analogous to `np.swapaxes` and `torch.permute` is similar to `np.transpose`, by the way, which is confusing but important to keep in mind.

So our `torch.transpose()` appears divergent from `np.swapaxes()`, but (on this issue, at least) our `torch.permute()` seems to be consistent with `np.transpose()`. Our `torch.transpose` no-ops in this case and that seems fine, and NumPy seems more consistent about throwing an error. 

This suggests to me that either doing nothing or throwing an error would be fine, and obviously an internal assert is bad. In the interest of NumPy compatibility and doing the more future-proof thing we might as well throw an error for now. We can always convert the error to a no-op later with no BC-impact if we decide a no-op is preferable.

**Comment by ilovepytorch** [comment]
@mruberry Thank you for your explanation! I am sorry to not explain my thoughts well since there are so many "alias" in the doc and I do not know which example API is better.

**Comment by albanD** [comment]
Thanks for the detailed view @mruberry 
We will accept PRs to change movedim and transpose to be errors on 0 dim Tensors then!

**Comment by mruberry** [comment]
> Thanks for the detailed view @mruberry We will accept PRs to change movedim and transpose to be errors on 0 dim Tensors then!

Changing `torch.transpose()` would be BC-breaking so I suggest only fixing the `torch.movedim()` internal assert.

**Comment by albanD** [comment]
Don't we want the two of them to be consistent?

**Comment by mruberry** [comment]
> Don't we want the two of them to be consistent?

That would be nice but probably not worth a BC-breaking change.

**Comment by Jup11ter** [comment]
There is similar buggy behavior on `torch.Tensor.Tensor.movedim` in 1.9.0 and 1.10.0, which raises:
```
RuntimeError: std::distance(source_dims.begin(), source_iter) == rest_dimINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1623448265233/work/aten/src/ATen/native/TensorShape.cpp":2357, please report a bug to PyTorch.
```

In 1.11.0 version, it can run well as expected. It seems like they were also fixed by this [pr](https://github.com/pytorch/pytorch/pull/69537).

In addition, I want to confirm whether all `torch.Tensor.xx` APIs are implemented exactly the same as `torch.xx`.
They always have similar bugs.


```python
import torch

func_cls=torch.Tensor.movedim

tensor = torch.rand(torch.Size([]))
def test():
    tmp_result= func_cls(tensor, 0, 0)
    return tmp_result
res1 = test()


```

**Comment by albanD** [comment]
This is now fixed in master
