### ISSUE TITLE
add python 3.10 support

### ISSUE THREAD

**Issue by creativegamer03** [pytorch/pytorch#69440]
## 🚀 Feature
Add Python 3.10 support, since PyTorch only supports up to Python 3.9.9 as of the time I'm writing this.

## Motivation

- Installation for PyTorch in Python 3.10's pip command fails as it fails to find a distribution for it, as well as `torchaudio` and `torchvision`.
- Importing `torch` fails to load for Python 3.10, but older versions prior to 3.10 successfully imports it. (Installed via install using Python 3.9's pip, then copy all torch packages into Python 3.10's)

## Pitch

I want PyTorch support available for Python 3.10.

## Alternatives

For now, I'll be using Python 3.9.

cc @malfet @seemethere

**Comment by vadimkantorov** [comment]
@malfet If tested installation commands were published online in an easy way on pytorch.org, at least it would be clear what works and what does not (even what does not work is a useful information)

**Comment by seemethere** [comment]
Closing this, this is already being tracked here: 

* https://github.com/pytorch/pytorch/issues/66424
