### ISSUE TITLE
How can I write my own activation function with cuda C++?

### ISSUE THREAD

**Issue by yeungkong** [pytorch/pytorch#69441]
Hello, users of pytorch. The reason that I want to write my own activation function with cuda C++ is that I want to calculate my own backpropagation. I tried to find some tutorials but very limited resources can be found. A tutorial here https://pytorch.org/tutorials/advanced/cpp_extension.html is useful. I think some modifications of present files of an activation function would be the easiest way for me to write my own one. Could someone please tell me where should I start or suggest other resources for my request? Thank you in advance.

cc @albanD @mruberry @jbschlosser @walterddr @ngimel

**Comment by ngimel** [comment]
Please ise discuss.pytorch.org to ask questions.

**Comment by yeungkong** [comment]
Thank you for your advice.
