### ISSUE TITLE
[pytorch ppc64le] build break for ppc64le could be related to #4627

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#6944]
The build break could be related to #4627

here is the error when building on ppc64le
you can see the log at :  https://powerci.osuosl.org/job/pytorch-master-nightly-py3-linux-ppc64le/266/consoleFull

In file included from generic/THTensorMath.c:1:0,
                 from /home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/TH/THGenerateIntTypes.h:10,
                 from /home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/TH/THGenerateAllTypes.h:11,
                 from /home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/TH/THTensor.cpp:31:
/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/TH/generic/THTensorMath.c:3868:86: error: macro "TH_TENSOR_APPLY_REDUCTION_OMP" requires 5 arguments, but only 4 given
     TH_TENSOR_APPLY_REDUCTION_OMP(real, tensor, &&:prod, prod = prod && *tensor_data;);
                                                                                      ^
/home/jenkins/workspace/pytorch-master-nightly-py3-linux-ppc64le/pytorch/aten/src/TH/generic/THTensorMath.c:3888:83: error: macro "TH_TENSOR_APPLY_REDUCTION_OMP" requires 5 arguments, but only 4 given
     TH_TENSOR_APPLY_REDUCTION_OMP(real, tensor, ||:sum, sum = sum || *tensor_data;);
                                                                                   ^

**Comment by avmgithub** [comment]
Also I am wondering if this passed your CI builds because your builds do not include MPI builds.  I have ppc64le builds that do not include MPI that passes builds.  Only ones that include MPI  fails to build.

**Comment by BelBES** [comment]
Related issue
#6945
