### ISSUE TITLE
[Feature Request] Expose default_collate as a public method

### ISSUE THREAD

**Issue by randolf-scholz** [pytorch/pytorch#69445]
## 🚀 Feature

Currently, `default_collate` resides in the private module `torch.utils.data._utils.collate `. It would be nice to expose `default_collate` as a public method, in the case one wants to write a custom `collate_fn` that wraps the default one.

## Motivation

Sometimes one would like to perform some default processing to each batch, but still leverage the default `collate_fn` behaviour to do all the lifting of type conversion etc.

## Pitch

Make `default_collate_fn` a public method and document its behaviour in https://pytorch.org/docs/stable/data.html

## Alternatives

One could possibly introduce another attribute `post_processor` that applies another `Callable` after `collate_fn`. 

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by NivekT** [comment]
`torch.data.utils.dataloader` actually contains 'default_collate' and makes it a public method. You can import it from there.

Nonetheless, I just added a PR to make it more explicitly available to users. Hope this helps.
