### ISSUE TITLE
Replace instances of batchCheckErrors with new at::_linalg_check_errors

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#69457]
## 🚀 Feature

Since we've added a new at::_linalg_check_errors function, we should be able to replace all instances of 
```
if (self.dim() > 2) {
  batchCheckErrors(infos, "svd_cpu");
} else {
  singleCheckErrors(infos.item<int64_t>(), "svd_cpu");
}
```
with it

## Motivation

Deduplicate code

## Context

Follow-up to https://github.com/pytorch/pytorch/pull/69437

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
This is already fixed in master
