### ISSUE TITLE
Missed argument

### ISSUE THREAD

**Issue by BelBES** [pytorch/pytorch#6945]
https://github.com/pytorch/pytorch/blob/e7babb1890b1658886835ff4627d8b00aa84bae1/aten/src/TH/generic/THTensorMath.c#L3868

It I think that you missed last argument 'UNCERTAIN_TH_OMP_OVERHEAD_THRESHOLD'

https://github.com/pytorch/pytorch/blob/e7babb1890b1658886835ff4627d8b00aa84bae1/aten/src/TH/generic/THTensorMath.c#L3888

And here too...

**Comment by soumith** [comment]
i'm sending a patch, sorry about this

**Comment by sighingnow** [comment]
Sorry about this. I didn't notice the changes in #5584, which got merged 13 hours ago. Thanks for fixing that @soumith .
