### ISSUE TITLE
Update elementwise binary tests

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#69464]
In https://github.com/pytorch/pytorch/pull/69439 a significant number of new elementwise binary tests were added, and there are still a few updates to be made:

- [ ] elementwise binary OpInfos needs to be labeled as such
- [ ] test_type_promotion needs to be enabled on ROCm
- [ ] skips should be updated to xfails where possible
- [ ] pre-existing tests that are replaced with the new OpInfo-based tests should be removed
- [ ] additional elementwise binary tests where each input has the same shape but a different discontiguity should be investigated

cc @mruberry

**Comment by jithunnair-amd** [comment]
cc @arindamroy-eng @KyleCZH Please keep track of this issue for the "test_type_promotion needs to be enabled on ROCm" sub-item?

**Comment by mruberry** [comment]
The above issues have been addressed.
