### ISSUE TITLE
Distribution `kl_divergence` method

### ISSUE THREAD

**Issue by 0x00b1** [pytorch/pytorch#69468]
## 🚀 Feature

Add a `kl_divergence` method to `pytorch.distributions.Distribution` (and any applicable subclasses from `pytorch.distributions`) that returns the Kullback-Leibler divergence (or relative entropy) between the distribution and another distribution.

## Motivation

`pytorch.distributions.Distribution` is fantastic but it lacks a lot of practical distribution functionality.

## Additional context

See also: #52973

**Comment by sharvil** [comment]
There's an entire section on KL divergence with `Distribution`s in [the official documentation](https://pytorch.org/docs/stable/distributions.html).

**Comment by 0x00b1** [comment]
@sharvil I am embarrassed I missed this! Thanks!
