### ISSUE TITLE
Compilation of <torch/extension.h> error on Windows CUDA 11.5

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#69460]
We have following error when compiling CUDA 11.5 on windows

C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\pybind11\cast.h(1429): error: too few arguments for temp
late template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]
" 
(1507): here

C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\include\pybind11\cast.h(1503): error: too few arguments for temp
late template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]
" 
(1507): here

Complete failure log:
https://github.com/pytorch/pytorch/runs/4408796098?check_suite_focus=true

This looks like the same issue as this one:
https://github.com/facebookresearch/pytorch3d/issues/843

Here is the workaround for this issue:
https://github.com/facebookresearch/pytorch3d/commit/cb170ac024a949f1f9614ffe6af1c38d972f7d48

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @brianjo @mruberry @ngimel @bdhirsh @jbschlosser @malfet @seemethere @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Adding this to the 1.11.0 milestone since this will be a blocker for the 1.11.0 release

**Comment by malfet** [comment]
Grabbing for myself, as it probably involves tweaking pybind a bit

**Comment by malfet** [comment]
I can reproduce it with hello world example that simply includes pybind:
```
#include <stdio.h>
#include <pybind11/pybind11.h>
__global__ void kernel() {
  printf("Hello World");
}
int main(void) {
 kernel<<<1, 1>>>();
 return cudaDeviceSynchronize();
}
```

```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin>nvcc "c:\Users\runneruser\Documents\hello.cu" -o c:\Users\runneruser\Documents\a.exe -IC:\actions-runner\_work\pytorch\pytorch\third_party\pybind11\include -IC:\Jenkins\Miniconda3\include
hello.cu
C:\actions-runner\_work\pytorch\pytorch\third_party\pybind11\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

C:\actions-runner\_work\pytorch\pytorch\third_party\pybind11\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

2 errors detected in the compilation of "c:/Users/runneruser/Documents/hello.cu".
```

**Comment by zasdfgbnm** [comment]
Further narrow down:
```C++
#include <utility>

// Base implementation for std::tuple and std::pair
template <template<typename...> class Tuple, typename... Ts> class tuple_caster {
    using type = Tuple<Ts...>;
};

template <typename T1, typename T2> class type_caster
    : public tuple_caster<std::pair, T1, T2> {};


__global__ void kernel() {
	printf("Hello World");
}
int main(void) {
	kernel <<<1, 1>>> ();
	return cudaDeviceSynchronize();
}
```

**Comment by malfet** [comment]
Need to document the regression of nvcc compiler from CUDA-11.5 on Windows

**Comment by mszhanyi** [comment]
@malfet 
I'd created a project [GPU and CUDA regression on Windows](https://github.com/pytorch/pytorch/projects) to collect GPU and cuda regressions.

**Comment by atalman** [comment]
Test python file:

import torch
y=torch.randn([3,5]).cuda()
print(y)
print(torch.backends.cudnn.version())

create and activate new environment using conda create/ conda activate

 Manywheels Windows:

 torch-1.12.0.dev20220221+cu115-cp310-cp310-win_amd64.whl                                                                                       
 torch-1.12.0.dev20220221+cu115-cp39-cp39-win_amd64.whl 
 torch-1.12.0.dev20220221+cu115-cp38-cp38-win_amd64.whl 
 torch-1.12.0.dev20220221+cu115-cp37-cp37-win_amd64.whl 

(env2) atalman@EC2AMAZ-IIQMR6I C:\Users\atalman\vim\vim82>python testc.py                                                                       
C:\Users\atalman\vim\vim82\testc.py:2: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ..\torch\csrc\
utils\tensor_numpy.cpp:68.)                                                                                                                     
  y=torch.randn([3,5]).cuda()                                                                                                                   
tensor([[-0.2648, -0.3199,  0.2563,  1.9191, -0.3408],                                                                                          
        [ 0.6953, -1.0059, -1.1185, -0.0272, -0.4818],                                                                                          
        [ 0.6630,  2.1202,  1.5892,  0.1650, -1.4987]], device='cuda:0')                                                                        
8302      

Linux :
- Requirement libcublas

torch-1.12.0.dev20220221+cu115-cp310-cp310-linux_x86_64.whl
torch-1.12.0.dev20220221+cu115-cp37-cp37m-linux_x86_64.whl
torch-1.12.0.dev20220221+cu115-cp38-cp38-linux_x86_64.whl
torch-1.12.0.dev20220221+cu115-cp39-cp39-linux_x86_64.whl

(env3) [ec2-user@ip-10-0-4-36 bin]$ python testc.py
tensor([[-0.2030,  0.3080,  0.5082,  0.0151, -0.1881],
        [ 0.0168, -0.8440,  1.2614, -0.6903,  0.4114],
        [ 0.0245, -1.2455, -0.7242,  0.0036,  0.6075]], device='cuda:0')
['/home/ec2-user/miniconda3/bin', '/home/ec2-user/miniconda3/envs/env3/lib/python37.zip', '/home/ec2-user/miniconda3/envs/env3/lib/python3.7', '/home/ec2-user/miniconda3/envs/env3/lib/python3.7/lib-dynload', '/home/ec2-user/.local/lib/python3.7/site-packages', '/home/ec2-user/miniconda3/envs/env3/lib/python3.7/site-packages', '/home/ec2-user/miniconda3/envs/env1/lib/']
8302

**Comment by atalman** [comment]
Conda Linux :
conda install -c conda-forge -c pytorch-nightly pytorch=1.12.0.dev20220218=py3.9_cuda11.5_cudnn8.3.2_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.10_cuda11.5_cudnn8.3.2_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.8_cuda11.5_cudnn8.3.2_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.7_cuda11.5_cudnn8.3.2_0

Conda Windows
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220207=py3.10_cud
a11.5_cudnn8_0                        <- Need to fix this                      
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.8_cuda
11.5_cudnn8_0
conda install -c conda-forge -c pytorch-nightly pytorch==1.12.0.dev20220221=py3.7_cuda
11.5_cudnn8_0

**Comment by atalman** [comment]
libtorch  Linux

libtorch-cxx11-abi-static-with-deps-1.12.0.dev20220221%2Bcu115.zip
libtorch-cuda11_5-shared-with-deps-cxx11-abi-build

root@0d434f8c5f3b:/tmp1# g++ /builder/test_example_code/check-torch-cuda.cpp -I/tmp1/libtorch/include -I/tmp1/libtorch/include/torch/csrc/api/include -D_GLIBCXX_USE_CXX11_ABI=1 -std=gnu++14 -L/tmp1/libtorch/lib -Wl,-R/tmp1/libtorch/lib -Wl,--no-as-needed -ltorch -ltorch_cpu -ltorch_cuda -lc10 -o check-torch-cuda
root@0d434f8c5f3b:/tmp1# .check-torch-coda
bash: .check-torch-coda: command not found
root@0d434f8c5f3b:/tmp1# ./check-torch-cuda
Checking that CUDA archs are setup correctly
Checking that magma is available
Checking that CuDNN is available
CuDNN VERSION 8302root@0d434f8c5f3b:/tmp1# 


Modified CPP file /builder/test_example_code/check-torch-cuda.cpp 
#include <torch/torch.h>
#include <ATen/detail/CUDAHooksInterface.h>

int main(int argc, const char* argv[]) {
    std::cout << "Checking that CUDA archs are setup correctly" << std::endl;
    TORCH_CHECK(torch::rand({ 3, 5 }, torch::Device(torch::kCUDA)).defined(), "CUDA archs are not setup correctly");

    // These have to run after CUDA is initialized

    std::cout << "Checking that magma is available" << std::endl;
    TORCH_CHECK(torch::hasMAGMA(), "MAGMA is not available");

    std::cout << "Checking that CuDNN is available" << std::endl;
    TORCH_CHECK(torch::cuda::cudnn_is_available(), "CuDNN is not available");
    std::cout << "CuDNN VERSION " << at::detail::getCUDAHooks().versionCuDNN();
    return 0;
}

**Comment by atalman** [comment]
@zasdfgbnm Can you confirm if this is resolved on 11.6 ? Should we try to reenable this test for 11.6 ?

**Comment by atalman** [comment]
This issue is still present in 11.6

Workflow: https://github.com/pytorch/pytorch/runs/6370594544?check_suite_focus=true

Test run: https://pipelines.actions.githubusercontent.com/serviceHosts/7d146c05-69c3-4c20-a0e7-818111670117/_apis/pipelines/1/runs/1994481/signedlogcontent/202?urlExpires=2022-05-10T19%3A24%3A39.9634942Z&urlSigningMethod=HMACV1&urlSignature=2k%2BraOQZrw3DxMfaCQkiOYAct0QjOkoqVqgfIV053N8%3D

Full log: https://www.internalfb.com/intern/everpaste/?handle=GICWmADlv7d0NnYCAP8InUwHzUZ1bsIXAAAz&color=1

Will be moving this issue to Release 1.13 milestones.
cc @malfet , @seemethere @ngimel

**Comment by MinttHu** [comment]
My system is window 10+CUDA11.3. My problem is that when I use "torch. utils.cpp_extension.load_inline" to built a C++/CUDA extension, it shows: "ninja: build stopped: subcommand failed."

**Comment by 3a1b2c3** [comment]
Any workarounds?

**Comment by atalman** [comment]
@malfet @ptrblck Since we have cuda 11.7 I will rerun testing on this cuda to see if this issue is resolved for CUDA 11.7

**Comment by atalman** [comment]
Looks like this issue is resolved in 11.7. I am not observing the failure anymore on https://github.com/pytorch/pytorch/pull/85966

**Comment by atalman** [comment]
Removing from milestones, since this issue is not critical for release 1.13 and this is resolved for CUDA 11.7

**Comment by atalman** [comment]
With deprecation of CUDA 11.6, we can resolve this issue, will post a PR once 11.6 is deprecated from CI

**Comment by thiagocrepaldi** [comment]
SHould https://pytorch.org/tutorials/advanced/cpp_extension.html doc be updated now this is closed?
