### ISSUE TITLE
Extending pytorch

### ISSUE THREAD

**Issue by agadetsky** [pytorch/pytorch#6947]
Maybe extending pytorch tutorial needs some refactoring in Pytorch 0.4 docs.

**Comment by SsnL** [comment]
we should probably get this in https://github.com/pytorch/tutorials/pull/214

**Comment by agadetsky** [comment]
UP

**Comment by agadetsky** [comment]
@SsnL do you know if anyone will fix tutorials about autograd extensions in Python and C++ in near future?

**Comment by agadetsky** [comment]
@soumith thank you for the answer!
in autograd extensions section there is a subsection with gradcheck. And in this section Variable is used. I thought that in 0.4 and in future Variable will be fully deprecated. Also for new users it can be confusing because of merging Tensor and Variable.
