### ISSUE TITLE
flake8_hook.py incompatible with flake8 4.x

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#69500]
`flake8.main.git` was removed in flake8 version 4:
https://github.com/PyCQA/flake8/commit/1a1d850e99bb28625e47f4aa3c27014a3ac6758a

[tools/linter/flake8_hook.py](https://github.com/pytorch/pytorch/blob/7e619b95880cdec72d1353c9c99dedbc2575ad36/tools/linter/flake8_hook.py) needs to be updated.

CC @walterddr

**Comment by kit1980** [comment]
Removing the hook because the CVS integration is removed from flake8.
New recommended way from flake8 is to use pre-commit framework https://flake8.pycqa.org/en/latest/user/using-hooks.html , maybe we should look it it at the future.
