### ISSUE TITLE
Hippify script does not work

### ISSUE THREAD

**Issue by TE-PongsakornUchupala** [pytorch/pytorch#69509]
## 🐛 Bug

Hippify script (for ROCm build) does not work.

## To Reproduce

1. Install ROCm 4.5 (I followed [this instruction](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation_new.html))
2. Clone Pytorch, init submodules
```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive --jobs 0
```
3. `python tools/amd_build/build_amd.py`
```
$ python tools/amd_build/build_amd.py
...
/home/ubuntu/projects/pytorch/torch/csrc/deploy/interpreter/interpreter_impl.cpp -> /home/ubuntu/projects/pytorch/torch/csrc/deploy/interpreter/interpreter_impl.cpp skipped
/home/ubuntu/projects/pytorch/torch/csrc/deploy/interpreter/register_numpy.cpp -> /home/ubuntu/projects/pytorch/torch/csrc/deploy/interpreter/register_numpy.cpp skipped
Traceback (most recent call last):
  File "tools/amd_build/build_amd.py", line 173, in <module>
    hip_clang_launch=is_hip_clang())
  File "/home/ubuntu/projects/pytorch/torch/utils/hipify/hipify_python.py", line 1008, in hipify
    clean_ctx=clean_ctx)
  File "/home/ubuntu/projects/pytorch/torch/utils/hipify/hipify_python.py", line 212, in preprocess
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/home/ubuntu/projects/pytorch/torch/utils/hipify/hipify_python.py", line 175, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/home/ubuntu/projects/pytorch/torch/utils/hipify/hipify_python.py", line 828, in preprocessor
    output_source = processKernelLaunches(output_source, stats)
  File "/home/ubuntu/projects/pytorch/torch/utils/hipify/hipify_python.py", line 376, in processKernelLaunches
    cuda_kernel_dim3 = add_dim3(kernel_string, cuda_kernel)
  File "/home/ubuntu/projects/pytorch/torch/utils/hipify/hipify_python.py", line 257, in add_dim3
    second_arg_raw = kernel_string[arg_locs[1]['start']:arg_locs[1]['end']]
KeyError: 'end'
```

## Expected behavior

`python tools/amd_build/build_amd.py` successfully hippify the source code and produce no error.

## Environment

 - PyTorch Version (e.g., 1.0): Github master (as of 2021/12/07)
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python tools/amd_build/build_amd.py`
 - Python version: 3.6.9
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: Not relevance
 - Any other relevant information:

## Additional context

Upon further investigation, it seems like `hippify_python.py` error while trying to process `torch/csrc/deploy/interpreter/builtin_registry.cpp`.

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jithunnair-amd** [comment]
@TE-PongsakornUchupala I tried this at commit 4670f0f2c52483a2060fb6b3475c38191c31497e and the command worked fine for me. I doubt it was the `builtin_registry.cpp` file causing an issue, because it shows up as Skipped by hipify for me:
```
...
/data/pytorch/torch/csrc/deploy/interpreter/register_numpy.cpp -> /data/pytorch/torch/csrc/deploy/interpreter/register_numpy.cpp skipped
/data/pytorch/torch/csrc/deploy/interpreter/interpreter_impl.h -> /data/pytorch/torch/csrc/deploy/interpreter/interpreter_impl.h skipped
/data/pytorch/torch/csrc/deploy/interpreter/builtin_registry.cpp -> /data/pytorch/torch/csrc/deploy/interpreter/builtin_registry.cpp skipped
...
```

**Comment by TE-PongsakornUchupala** [comment]
@jithunnair-amd I tried again at commit https://github.com/pytorch/pytorch/commit/c236247826bbf49d4f491d97bac6df1da6c1abe8 (latest master at the moment) and got the same result as yours (skip `builtin_registry.cpp`). I guess whatever the issue was, it was quickly fixed in the subsequent commits.

Since I could no longer reproduce the issue, please allow me to close the ticket.
