### ISSUE TITLE
libtorch at::Tensor::print() linking error

### ISSUE THREAD

**Issue by juntingzh** [pytorch/pytorch#69515]
## 🐛 Bug

```
Undefined symbols for architecture x86_64:
  "at::Tensor::print() const", referenced from:
      xxxxxxx
ld: symbol(s) not found for architecture x86_64
```

## To Reproduce

calling `tensor.print();` in cpp program causes the linking error. if I remove the related lines, the compilation and linking with libtorch works fine.

It might be introduced by this commit https://github.com/pytorch/pytorch/commit/d701357d921ef167d42c125e65b6f7da6be3ad0f causing the inconsistency between https://github.com/pytorch/pytorch/blame/master/aten/src/ATen/core/Tensor.cpp#L52 and
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/templates/TensorBody.h#L224

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): MacOS 12.0.1 (The issue happens to ubuntu as well)
 - How you installed PyTorch (`conda`, `pip`, source): brew install libtorch
 - Build command you used (if compiling from source):
 - Python version: 
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @jbschlosser

**Comment by zou3519** [comment]
Hi-pri for regression
