### ISSUE TITLE
`torch.sparse.addmm` does not check the dtype of zero tensor

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#69518]
## 🐛 Bug

`torch.sparse.addmm` does check the dtype of empty sparse tensor, so it will succeed when the tensors have different dtypes. But `torch.addmm` will raise an error that `RuntimeError: expected scalar type Long but found Int`

## To Reproduce

```python
import torch
mat = torch.randint(0, 2, torch.Size([2, 3]), dtype=torch.int64)
mat1 = torch.randint(0, 1, torch.Size([2, 3]), dtype=torch.int64) # empty tensor
mat2 = torch.randint(0, 2, torch.Size([3, 3]), dtype=torch.int32)

mat1_sparse = mat1.to_sparse()
print(mat1_sparse.dtype)
# torch.int64
sparse_output = torch.sparse.addmm(mat, mat1_sparse, mat2)
print(sparse_output)

normal_output = torch.addmm(mat, mat1, mat2)
# RuntimeError: expected scalar type Long but found Int
```

## Expected behavior

`torch.sparse.addmm` should check the dtype of all tensors

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.9.6
 - CUDA/cuDNN version: none
 - GPU models and configuration: none
 - Any other relevant information: none

cc @nikitaved @pearu @cpuhrsch

**Comment by TestSomething22** [comment]
It seems that all the APIs supporting sparse tensor have this problems, they don't check the dtype of zero tensor. @zou3519

**Comment by cpuhrsch** [comment]
Hey @TestSomething22, thanks for the report! Can you rerun this on a recent nightly as well and see if the issues persists?

**Comment by TestSomething22** [comment]
@cpuhrsch Yes, it still has such issue. I ran it on '1.12.0.dev20220214'

**Comment by cpuhrsch** [comment]
@pearu - would you be interested in looking into this?

**Comment by pearu** [comment]
This issue is a sub-issue of https://github.com/pytorch/pytorch/issues/69665 and I suggest moving all the related discussion there. So, closing the issue here.
