### ISSUE TITLE
why 'torch.linalg.eigh' slow on GPU enven than that on CPU?

### ISSUE THREAD

**Issue by qingzhouzhen** [pytorch/pytorch#69528]
## ❓ Questions and Help

I hava a Real symmetric matrix(262144x2x2) which I want to caculate Eigenvalue and eigenvectors， 262144 is batch size, I use w, v = torch.linalg.eigh(input, UPLO="U") with torch==1.10.0, on my mac is cost about 0.04447412 second, while on GPU(2080TI), it takes about 3.638 second, it is too slow for me, is there anything wrong? or any solution to this problem?

- [Discussion Forum](https://discuss.pytorch.org/)

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by xwang233** [comment]
Thank you for raising this issue. `torch.linalg.eigh` with batched input on GPU has an optimized cuSOLVER path, but it's only enabled when pytorch is built with **cuda version >= 11.3 update 1**. 

Unfortunately, torch 1.10.0 was built with cuda 10.2 and 11.3, where the optimized path for batched input was not enabled for either. Your choices are: 
1. build from source with cuda >= 11.3U1;
2. wait when cuda 11.5 nightly build is ready, check release page https://download.pytorch.org/whl/nightly/cu115/torch_nightly.html and github issues https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+11.5

**Comment by mruberry** [comment]
Thanks for the answer, @xwang233!
