### ISSUE TITLE
DBR quant - delete floating point weights after weight packing

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#69536]
Currently DBR quant convert creates the quantized weights but leaves the floating point weights on the model.  We should build the functionality to delete the floating point weights after the quantized weights are created.  This will ensure that model size is optimal for quantized models with DBR.

You can check out https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/_dbr/model_utils.py, `pack_weights_for_functionals` for how the weights for functionals are packed.  The logic to delete the original weights could go in this function.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @jgong5 @Xia-Weiwen @leslie-fang-intel @vkuzo

**Comment by vkuzo** [comment]
When investigating how we can integrate DBR quant with torch.jit.script, I realized that we will still need the original weights for a model to be compable with scripting.  So, this functionality should be configurable and off by default.  It could be something like


```
def convert(model, ..., delete_outdated_weights=False, ...):
  ...
  if delete_outdated_weights:
    ... logic to delete the floating point weights
```

**Comment by andrewor14** [comment]
Closing this issue since DBR quant doesn't exist anymore. Please let me know if I'm misunderstanding the issue.
