### ISSUE TITLE
GHA: fully clean our workspace between runs and remove problematic non-ephemeral runners

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#69540]
While for the most part we are using ephemeral runners, there have been instances running that are non-ephemeral that have caused issues on CI. In fact, there were 27 failed jobs due to "persistent dirty checkout" on trunk in the week 11/20-12/6: https://fburl.com/scuba/opensource_ci_jobs/vs1j5mvq. ~We should stamp out all non-ephemeral runners to avoid such errors.~

In response to Eli's comment, as stamping out non-ephemeral runners should not be a goal (as the time it takes to spin them up and down is counterproductive to capacity), we should be diligent about
1. resetting the workspace between runs
2. removing runners that are problematic as a stop-gap measure

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Unfortunately due to the nature of some resource groups (like GPU executors), which continually run into capacity issues if we try to spin up / spin down for every job, we need some level of non-ephemeral runners in order to make that a non-issue.

**Comment by janeyx99** [comment]
#70337 should fix

**Comment by janeyx99** [comment]
Better fixed by #71018
