### ISSUE TITLE
[pytorch] RuntimeError: hardshrink_forward is not implemented for type torch.cuda.FloatTensor

### ISSUE THREAD

**Issue by karandwivedi42** [pytorch/pytorch#6955]
```python
torch.nn.Hardshrink()(torch.rand(10).to('cuda:0'))
```

**Comment by zou3519** [comment]
Thanks for the report, @karandwivedi42 . This is a duplicate of https://github.com/pytorch/pytorch/issues/4154 so I'm closing this issue; please voice your support/concerns there.

**Comment by karandwivedi42** [comment]
Sorry! I searched `hardshrink_forward` but couldn't find matching issues.
