### ISSUE TITLE
Issues with the compilation of libtorch c++ frontend without python dependencies.

### ISSUE THREAD

**Issue by grmnptr** [pytorch/pytorch#69581]
## 🐛 Bug

Hello!
I encountered a weird behavior while I was trying to compile libtorch on a linux HPC using the instructions under:
https://github.com/pytorch/pytorch/blob/master/docs/libtorch.rst

My issue is that there is very limited python support on the machine (no chance of creating a conda environment or installing packages using pip). Python 3.7 is available but most of the python dependencies are not. 
My cmake configure errors out with the following message

```
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/projects/pytorch/tools/codegen/gen.py", line 3, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```
which looks rather weird since I don't think any of my requested target depend on python. 

## To Reproduce

1. Install GCC, cmake, mpich.
2. Try to run 

```
cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DCMAKE_INSTALL_PREFIX:PATH=../pytorch-install ../pytorch
```

## Expected behavior

I expected the cmake configure not error out with python dependencies missing when I only want to compile libtorch.so.

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 8.0.1905 (Core)  (x86_64)
GCC version: (Spack GCC) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.2.5

Python version: 3.7.8 (default, Nov 18 2020, 12:10:09)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-305.10.2.el8_4.x86_64-x86_64-with-centos-8.0.1905-Core
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] Could not collect
[conda] Could not collect

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): CentOS Linux release 8.0.1905 (Core)  (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 ```
cmake -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DPYTHON_EXECUTABLE:PATH=`which python3` -DCMAKE_INSTALL_PREFIX:PATH=../pytorch-install ../pytorch
```
 - Python version: 3.7.8
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

I am not sure if this is a bug or intended behavior. I find it strange that cmake checks for python libraries while trying to make libtorch.

cc @malfet @seemethere @jbschlosser

**Comment by adamcavendish** [comment]
You can use the wheel installation scp-ed from your local machines (if on HPC).
1. Download the whl file on page: https://pypi.org/project/typing-extensions/#files
2. Install the whl via pip command: `pip install typing_extensions*.whl`

**Comment by adamcavendish** [comment]
In addition, python is used in code generation and therefore python (3) executable is a must.

**Comment by grmnptr** [comment]
Got it, it worked. Thank you very much!
