### ISSUE TITLE
RecursionError when using torch.utils.checkpoint

### ISSUE THREAD

**Issue by shubhtuls** [pytorch/pytorch#6959]
Hi,
Thanks for adding the checkpoint feature in the new release.

I was trying to use it in a setting where there are many 'inputs', which we want to first independently process using 'module' (but not store intermediate states) and then jointly reason over. Below is a code sample for this that results in 'RecursionError: maximum recursion depth exceeded'. If the code does not use checkpoint, everything runs fine.

I was wondering if there is a way to handle this.

Thanks!

```python
import torch
from torch import nn
from torch.utils.checkpoint import checkpoint

num_inp = 5000

nz_inp = 10
nz_out = 10
nz_bottleneck = 1000

# small proxy network for some complex reasoning we want to do per input
module = nn.Sequential(
    nn.Linear(nz_inp, nz_bottleneck),
    nn.ReLU(),
    nn.Linear(nz_bottleneck, nz_inp)
)

feat_combined = []
for r in range(num_inp):
    data_r = torch.Tensor(1, nz_inp)
    data_r.uniform_()
    data_r.requires_grad=True
    # feat_r = module(data_r) # using this instead of checkpoint line below works fine
    feat_r = checkpoint(module, data_r)

    feat_combined.append(feat_r)

# compute mean as a proxy for some joint reasoning
mean_combined = torch.stack(feat_combined).mean()

# the backward pass makes the code crash
mean_combined.backward()
```

**Comment by zou3519** [comment]
cc @prigoyal 

Relevant stacktrace:
```
Traceback (most recent call last):
  File "repro.py", line 32, in <module>
    mean_combined.backward()
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/opt/conda/lib/python3.6/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/checkpoint.py", line 34, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 371, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 371, in __call__
    result = self.forward(*input, **kwargs)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by YoelShoshan** [comment]
I encountered the exact same issue when using massive amount of checkpoint-ing, and to workaround it I increased the max recursion depth like this 
`sys.setrecursionlimit(3000)`
notice that you can see the current recursion limit like this:
`sys.getrecursionlimit()`
for me it was 1000

**Comment by shubhtuls** [comment]
Thanks @zou3519  for the workaround! As you said, I'm also not completely sure why checkpoints need to rely on nested recursions - I'll keep this issue open in the hope that there'll eventually be a more elegant way of handling this!

**Comment by sublee** [comment]
When the autograd graph has parallel lanes, `torch.autograd.backward()` in `CheckpointFunction.backward` seems to trigger other lanes which should be independent with the current lane.

This issue matters because we couldn't save the memory usage to split a mini-batch into several micro-batches just like [GPipe](https://arxiv.org/abs/1811.06965).

For example, we can make 2 parallel lanes using `torch.cat` for 2 output tensors:

```python
a = checkpoint(model, a)
b = checkpoint(model, b)
c = torch.cat((a, b))
#                a   b
#                |   |
# checkpoint{model} checkpoint{model}
#                 \ /
#                 cat
#                  |
#                  c
loss = c.mean()
loss.backward()
```

In this case, the backward of `checkpoint(model, b)` calls the backward of `checkpoint(model, a)` recursively even there's no dependency with `a`.

We can expose the recursion by logging timeline before/after the checkpoint. The above `LogBackward` function records a backward event:

```python
timeline = []
class LogBackward(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input, tag):
        ctx.tag = tag
        return input
    @staticmethod
    def backward(ctx, grad_output):
        timeline.append(ctx.tag)
        return grad_output, None
```

Here's the example code with timelining:

```python
a = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)
model = torch.nn.Linear(1, 1)

a = LogBackward.apply(a, 'a:end')
a = checkpoint(model, a)
a = LogBackward.apply(a, 'a:begin')

b = LogBackward.apply(b, 'b:end')
b = checkpoint(model, b)
b = LogBackward.apply(b, 'b:begin')

c = torch.cat((a, b))

loss = c.mean()
loss.backward()
```

`timeline` should be `['b:begin', 'b:end', 'a:begin', 'a:end']` if the backward of `model(b)` and `model(a)` are independent (`{b:begin, b:end}, {a:begin, a:end}`). But it will be `['b:begin', 'a:begin', 'a:end', 'b:end']` (`{b:begin, {a:begin, a:end}, b:end}`). They are stacked.

```python
>>> print(timeline)  # should be ['b:begin', 'b:end', 'a:begin', 'a:end']
['b:begin', 'a:begin', 'a:end', 'b:end']
```

**Comment by sublee** [comment]
I guess https://github.com/pytorch/pytorch/commit/9f0c4c9f9a4c61f28c620618c845a64adb634135 is related to this issue. @apaszke Would you mind if I ask your opinion?

**Comment by albanD** [comment]
This does not crash on master anymore as we changed the order the functions are executed.
Please re-open if you see this happen again in the future.
