### ISSUE TITLE
LTC quickstart run failed

### ISSUE THREAD

**Issue by Yancey1989** [pytorch/pytorch#69602]
## ❓ Questions and Help
Hi LTC dev team,

I tried to run the lazy tensor example followed by [quickstart](https://github.com/pytorch/pytorch/blob/lazy_tensor_staging/lazy_tensor_core/QUICKSTART.md), but I can not execute  the `example.py` file correctly, the error message is as the following:

``` bash
$ python example.py
Traceback (most recent call last):
  File "example.py", line 2, in <module>
    import lazy_tensor_core
  File "/workspace/pytorch/lazy_tensor_core/lazy_tensor_core/__init__.py", line 88, in <module>
    import _LAZYC  # noqa: E402
ImportError: /workspace/pytorch/lazy_tensor_core/_LAZYC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN5torch4lazy6TsNodeE
```

The development Docker image: `pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel`, can you give some help to fix this issue?

**Comment by mrshenli** [comment]
cc @wconstab

**Comment by Yancey1989** [comment]
I have fixed this issue because the develop Docker image has installed `torch`, there is no `*TsNode*` symbol in it,   I should re-install the torch or uninstall it before building LTC. And I will close this issue.
