### ISSUE TITLE
Wrong onnx export for v1.10. LTS was correct

### ISSUE THREAD

**Issue by xonobo** [pytorch/pytorch#69605]
## 🐛 Bug

A simple model does not export to onnx correctly. Sample code is given below. 

## To Reproduce

```
import torch

class PG(torch.nn.Module):
    def __init__(self, axis):
        super().__init__()
        self.axis = axis
    def forward(self, indices, data):
        b = data.shape[self.axis]
        return indices + b

pg = PG(0)
sample_input = (torch.IntTensor(), torch.IntTensor(),)
torch.onnx.export(pg, sample_input, 'pg.onnx', verbose=True, opset_version=11,
				input_names=['indices', 'data'], output_names=['pos_indices'], do_constant_folding=True)
```

Here is the onnx view for pytorch 1.10
![pg_1 10](https://user-images.githubusercontent.com/1115812/145209246-6c66ea99-8c47-460c-ad79-9c60a3e0fbbe.png)

## Expected behavior

With pytorch-lts, this model exports correctly. 
Here is the expected onnx model view in netron
![pg_lts](https://user-images.githubusercontent.com/1115812/145208673-8da5c7b4-2add-405e-b141-a8b453f696b4.png)

## Environment

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.19.4
Libc version: glibc-2.27

Python version: 3.8.8 (default, Apr 13 2021, 19:58:26)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-162-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Quadro M1200
Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-ignite==0.4.7
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.20.1           py38h7d8b39e_0  
[conda] pytorch                   1.10.0          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-ignite            0.4.7                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py38_cu102    pytorch
[conda] torchvision               0.11.1               py38_cu102    pytorch

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1568301.

**Comment by npuichigo** [comment]
@fatcat-z Any updates? I checked the work item and no update is found except for a backlog.

**Comment by fatcat-z** [comment]
> @fatcat-z Any updates? I checked the work item and no update is found except for a backlog.

No, it's not on plan yet. Probably you can provide more background to help improving the priority. And your contributions are definitely welcome.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

**Comment by npuichigo** [comment]
Reopen the issue. The onnx export regression still exists.

**Comment by justinchuby** [comment]
Did you specify dynamic axes?

**Comment by npuichigo** [comment]
specifying dynamic axes works😃. But I wonder why the export result of 1.8.2 is different without dynamic axes.
