### ISSUE TITLE
Libtorch 1.10 GPU package size doubles to 2GB

### ISSUE THREAD

**Issue by huangrenjie** [pytorch/pytorch#69646]
## ❓ Questions and Help

https://download.pytorch.org/libtorch/cu113/libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcu113.zip 

Now the size is double of libtorch 1.9, which is almost 2GB

It looks like the gpu so incrases a lot. 

In V 1.9
1.2G -rwxr-xr-x 1 root root 1.2G Jun 12 06:38 libtorch_cuda.so

In V 1.10 
1.9G -rwxr-xr-x 1 root root 1.9G Oct 15 14:07 libtorch_cuda_cpp.so
1.1G -rwxr-xr-x 1 root root 1.1G Oct 15 14:07 libtorch_cuda_cu.so

What are changed and what are the difference between libtorch_cuda_cpp.so and  libtorch_cuda_cu.so

### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
