### ISSUE TITLE
DISABLED test_fd_pool (__main__.TestMultiprocessing)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#69660]
This test has been determined flaky through reruns in CI and its instances are reported in our flaky_tests table here https://metrics.pytorch.org/d/L0r6ErGnk/github-status?orgId=1&from=1636426818307&to=1639018818307&viewPanel=57.

It is our second flakiest test in the last 15 days with 28 failed instances.

```
======================================================================
FAIL [4.720s]: test_fd_pool (__main__.TestMultiprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_multiprocessing.py", line 341, in test_fd_pool
    self._test_pool(repeat=TEST_REPEATS)
  File "test_multiprocessing.py", line 327, in _test_pool
    do_test()
  File "test_multiprocessing.py", line 206, in __exit__
    self.test_case.assertFalse(self.has_shm_files())
AssertionError: True is not false
```

Please look at the table for details from the past 30 days such as

* number of failed instances
* an example url
* which platforms it failed on
* the number of times it failed on trunk vs on PRs.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin

**Comment by janeyx99** [comment]
@NivekT is this the test you suspect is flaky due to constrained shared memory? it seems to be fine when run multiple times without many other tests, but then is flaky again when run with the test suite.

**Comment by NivekT** [comment]
I don't think this is DataLoader related? I am not familiar enough with this test file to know for sure
