### ISSUE TITLE
Is there an description for "torch.nn.init.trunc_normal_()"?

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#69679]
### 📚 The doc issue

Hi, guys,
I see there is a method of `torch.nn.init.trunc_normal_()`, but I do not find the description of it in the documentation.
So is there a description for this `torch.nn.init.trunc_normal_()`?
I am a little confused.

**Comment by VitalyFedyunin** [comment]
Should be right in the docstrings https://github.com/pytorch/pytorch/blob/3596e13d45d8a69ae83dd2f260b2fa8b8376f182/torch/nn/init.py#L160

**Comment by songyuc** [comment]
Hi, @VitalyFedyunin,
I am wondering why `trunc_normal_` does not appear in the [https://pytorch.org/docs/stable/nn.init.html](https://pytorch.org/docs/stable/nn.init.html), of which is the reason that I think as the doc issue.
