### ISSUE TITLE
hyperlink's displayed text

### ISSUE THREAD

**Issue by TaoweiZhang** [pytorch/pytorch#69675]
## 📚 Documentation

I want to submit a pull request for the document (I found a very small mistake in 'serialization.html'), but, I don't know how to modify in my repository and then PR.

**Comment by VitalyFedyunin** [comment]
Hello!

Please check https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md

Generally, It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
