### ISSUE TITLE
[torch.onnx.export] Some operations were disappeared when converting pytorch model to onnx model by torch.onnx.export

### ISSUE THREAD

**Issue by ChuChengYang** [pytorch/pytorch#69673]
## 🐛 Bug
Hello, when I use torch.onnx.export to convert the pytorch model to the onnx model, some operations will be hard-coded, resulting in the absence of the layer composed of these operations in the generated onnx model structure.

## To Reproduce

1.prepare a pytorch model
2.add some class variables to the class
3.operate on the variables in the forward() function
4.convert the pytorch model to onnx model
5.check the structure of the onnx model, some operations related to the class variables were disappeared

```
class CausalConv1d(nn.Conv1d):
    def __init__(self,
                 in_channels,
                 out_channels,
                 kernel_size,
                 stride=1,
                 dilation=1,
                 groups=1,
                 bias=True):
        super(CausalConv1d, self).__init__(
            in_channels,
            out_channels,
            kernel_size,
            stride=stride,
            padding=0,
            dilation=dilation,
            groups=groups,
            bias=bias)

        self.left_padding = dilation * (kernel_size - 1)
        self.buffer = torch.zeros([1, self.in_channels, self.left_padding])

    def forward(self, input, end_flag):
        x = torch.cat((self.buffer, input), 2)

        self.buffer = x[:, :, input.shape[2]:]
        self.buffer = self.buffer * end_flag[0]

        return super(CausalConv1d, self).forward(x)
```
As you can see in the code above, I created self.buffer in Class CausalConv1d, then I operated on self.buffer in the forward() function. There are 3 operations in total, however, only the first operation, torch.cat convert to onnx model successfully, the second and third operation slice and multiplication were not able to convert to onnx model(might have been hard-coded).

![debug_info](https://user-images.githubusercontent.com/65480575/145359239-5fbbcaf9-eaf9-4106-aa32-b285fe55cefe.png)
![结构](https://user-images.githubusercontent.com/65480575/145359018-a785efde-f4e9-4e07-bddd-5a20613fa021.png)

The first picture above is convert debug info, Next to onnx::Concat is onnx::Conv, which lacks slice and multiplication.
The second picture is onnx model structure, as debug info shows, lacks slice and multiplication too. And the model has two inputs, input and end_ Flag, due to the lack of related layers, there is only one input left in the model, and end_flag is missing.

## Expected behavior
1. All operations in the forward() function are correctly translated into the onnx model
2. Two inputs input and end_flag should both appear in the model structure

## Environment
Collecting environment information...
PyTorch version: 1.8.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.26

Python version: 3.7.10 (default, Mar 23 2021, 15:34:20)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.107-1-tlinux2_kvm_guest-0049-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.0+cpu
[pip3] torchaudio==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.9.0+cpu
[conda] Could not collect

**Comment by fatcat-z** [comment]
@ChuChengYang 

These 2 operations:

        self.buffer = x[:, :, input.shape[2]:]
        self.buffer = self.buffer * end_flag[0]

have no relationship with the final output of forward() method, so it will be optimized during export.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
