### ISSUE TITLE
Follow Up on the usage for cudatoolkit across pytorch projects

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#69691]
### 🐛 Describe the bug

In recent converstion with Nvidia over Slack, we where told that we should no longer be using cudatoolkit and we should be switching to cuda package instead :
The cuda package is officially supported by the CUDA team so if something isn't working, we can follow up with them. cudatoolkit is created as a dependency from another package, and should not be used anymore.

There is an issue installing cudatoolkit with CUDA 11.5, following command does not work:
conda install -yq -c nvidia -c pytorch cudatoolkit=11.5

Fails with following error:
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
Package libgcc-ng conflicts for:
python=3.9 -> libgcc-ng[version='>=7.3.0|>=7.5.0']
python=3.9 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
cudatoolkit=11.5 -> libgcc-ng[version='>=9.4.0']The following specifications were found to be incompatible with your system:
 - feature:/linux-64::__glibc==2.17=0
 - feature:|@/linux-64::__glibc==2.17=0
 - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
Your installed version is: 2.1

We found workaround for this issue by using conda-forge chanell.

Ref PR that implements workaround for cudatoolkit:
https://github.com/pytorch/vision/pull/5024

Hence in this story we want to Follow up with Nvidia on this issue. And decide if we should be switching to cuda package for PyTorch and all dependent repos.

### Versions

CUDA 11.5

cc @ezyang @seemethere @malfet @ngimel

**Comment by seemethere** [comment]
Adding this to the 1.11.0 milestone since we'll need to resolve this _before_ we cut for 1.11.0

**Comment by b0noI** [comment]
Our current plan: migrate to Cuda package and get commitment to Nvidia that there will be no need to do yet another migration in the future. But before final decision we will do quick evaluation of the implication of this migration from the customer perspective.

**Comment by malfet** [comment]
https://anaconda.org/nvidia/cudatoolkit/files?version=11.5.0 linux-64 depends on "__glibc >=2.17,<3.0.a0, libgcc-ng >=9.4.0, libstdcxx-ng >=9.4.0"
And max version of [libstdcxx-ng](https://anaconda.org/anaconda/libstdcxx-ng) published by anaconda is 9.3.0

**Comment by ptrblck** [comment]
A workaround using the `cuda` conda package might be:
```
conda install cuda -c nvidia/label/cuda-11.5.1
```
This should install:
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cuda-11.5.1                |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-cccl-11.5.62          |                0         1.1 MB  nvidia/label/cuda-11.5.1
    cuda-command-line-tools-11.5.1|       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-compiler-11.5.1       |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-cudart-11.5.117       |       h7e867a7_0         195 KB  nvidia/label/cuda-11.5.1
    cuda-cudart-dev-11.5.117   |       h91b5d7a_0        1000 KB  nvidia/label/cuda-11.5.1
    cuda-cuobjdump-11.5.119    |       h32764b9_0         122 KB  nvidia/label/cuda-11.5.1
    cuda-cupti-11.5.114        |       h2757d8a_0        21.9 MB  nvidia/label/cuda-11.5.1
    cuda-cuxxfilt-11.5.119     |       h3f39129_0         281 KB  nvidia/label/cuda-11.5.1
    cuda-driver-dev-11.5.117   |                0          19 KB  nvidia/label/cuda-11.5.1
    cuda-gdb-11.5.114          |       h8765814_0         4.7 MB  nvidia/label/cuda-11.5.1
    cuda-libraries-11.5.1      |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-libraries-dev-11.5.1  |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-memcheck-11.5.114     |       h765d031_0         157 KB  nvidia/label/cuda-11.5.1
    cuda-nvcc-11.5.119         |       h2e31d95_0        41.7 MB  nvidia/label/cuda-11.5.1
    cuda-nvdisasm-11.5.119     |       he465173_0        31.5 MB  nvidia/label/cuda-11.5.1
    cuda-nvml-dev-11.5.50      |       h511b398_0          63 KB  nvidia/label/cuda-11.5.1
    cuda-nvprof-11.5.114       |       hd1b9a7f_0         4.3 MB  nvidia/label/cuda-11.5.1
    cuda-nvprune-11.5.119      |       ha53ebc3_0          53 KB  nvidia/label/cuda-11.5.1
    cuda-nvrtc-11.5.119        |       h411d788_0        17.0 MB  nvidia/label/cuda-11.5.1
    cuda-nvrtc-dev-11.5.119    |       h3fe8e16_0        16.7 MB  nvidia/label/cuda-11.5.1
    cuda-nvtx-11.5.114         |       ha1eacfd_0          47 KB  nvidia/label/cuda-11.5.1
    cuda-nvvp-11.5.114         |       h233c720_0       114.3 MB  nvidia/label/cuda-11.5.1
    cuda-runtime-11.5.1        |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-samples-11.5.56       |       hf1e648b_0        64.4 MB  nvidia/label/cuda-11.5.1
    cuda-sanitizer-api-11.5.114|       h781f4d3_0        14.5 MB  nvidia/label/cuda-11.5.1
    cuda-toolkit-11.5.1        |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-tools-11.5.1          |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    cuda-visual-tools-11.5.1   |       hd4d9352_0           2 KB  nvidia/label/cuda-11.5.1
    libcublas-11.7.4.6         |       hd52c9d2_0       296.6 MB  nvidia/label/cuda-11.5.1
    libcublas-dev-11.7.4.6     |       h9ea41a3_0       305.9 MB  nvidia/label/cuda-11.5.1
    libcufft-10.6.0.107        |       hd5a0538_0        93.6 MB  nvidia/label/cuda-11.5.1
    libcufft-dev-10.6.0.107    |       hb86e5fa_0       197.3 MB  nvidia/label/cuda-11.5.1
    libcurand-10.2.7.107       |       h449470a_0        50.3 MB  nvidia/label/cuda-11.5.1
    libcurand-dev-10.2.7.107   |       hd5b7b69_0        50.8 MB  nvidia/label/cuda-11.5.1
    libcusolver-11.3.2.107     |       hc875929_0        78.0 MB  nvidia/label/cuda-11.5.1
    libcusolver-dev-11.3.2.107 |       h78cb71c_0        50.6 MB  nvidia/label/cuda-11.5.1
    libcusparse-11.7.0.107     |       hf21abff_0       135.0 MB  nvidia/label/cuda-11.5.1
    libcusparse-dev-11.7.0.107 |       h338262b_0       274.0 MB  nvidia/label/cuda-11.5.1
    libnpp-11.5.1.107          |       hb6e5806_0       114.7 MB  nvidia/label/cuda-11.5.1
    libnpp-dev-11.5.1.107      |       he6b01ee_0       111.9 MB  nvidia/label/cuda-11.5.1
    libnvjpeg-11.5.4.107       |       h31e24ca_0         2.2 MB  nvidia/label/cuda-11.5.1
    libnvjpeg-dev-11.5.4.107   |       h6455901_0         1.8 MB  nvidia/label/cuda-11.5.1
```
For 11.5.0 I get an `UnsatisfiableError`.

**Comment by malfet** [comment]
Tentatively moving to 1.12, adding `needs-design`

**Comment by atalman** [comment]
Moving this 1.12.1 , more testing time is needed

**Comment by atalman** [comment]
Closing since migrated to pytorch-cuda for 11.6 and 11.7 cuda versions
