### ISSUE TITLE
[mitigated] The self hosted runner lost communication with the server

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#69722]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.

mitigated

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
![image](https://user-images.githubusercontent.com/1700823/145482356-e83c30b9-3b1b-4cd2-a7c1-20b139cd4bbf.png)

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

- 12/09 10:00a: Incident began
- 12/09 12:30p: Change rolled out to double check runner availability before scaling down
- 12/09 1:00p: Change confirmed to not work correctly due to the [Github API](https://docs.github.com/en/rest/reference/actions#get-a-self-hosted-runner-for-a-repository) not actually returning a 200 when attempting to lookup runners by ID
- 12/09 2:00p: Submitted a ticket to Github to ask if there were any changes to the self hosted API
- 12/09 2:30p: Deployed https://github.com/seemethere/terraform-aws-github-runner/pull/11 to our infra, did not resolve issues
- 12/09 3:00p: infra reverted to previous version prior to 12:30p rollout
- 12/09 3:30p: Submitted https://github.com/actions/runner/issues/1545 since I think this is more of an issue with job renewal more than anything else
- 12/10 8:44a: Github has acknowledged that root cause is server side (https://github.com/actions/runner/issues/1546#issuecomment-991135687)
- 12/10 10:20: Notified from Github that fix has been rolled out and have confirmed through cloudwatch insights that we have mostly returned back to normal, closing this issue

## User impact
*How does this affect users of PyTorch CI?*
All workflows 

## Root cause
*What was the root cause of this issue?*
Server side change from GitHub: https://github.com/actions/runner/issues/1546#issuecomment-991135687

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by seemethere** [comment]
I've submitted a ticket to Github and attempted to deploy https://github.com/seemethere/terraform-aws-github-runner/pull/11 both which haven't produced any results yet.

Since this infrastructure was working well for the past couple of months I'm starting to consider the idea that the Github API might have changed something in relation to self hosted API.

This makes any mitigation attempt contingent on the API being consistent (which right now I wouldn't consider it consistent).

I'm also observing some failures in terms of runner daemon logs, those have been added to the ticket that I submitted to Github support earlier today.

**Comment by seemethere** [comment]
Going to be reverting our infra to the spot where it was at before today since it was previously working and will await a response from Github support.

**Comment by seemethere** [comment]
Infra has now been reverted to previous code

**Comment by seemethere** [comment]
Also submitted https://github.com/actions/runner/issues/1545 since I think this problem is actually more related to the runner daemon than the self hosted API

**Comment by seemethere** [comment]
Something interesting to note, the forbidden error we're observing in the runner daemon logs only started to really manifest itself this morning:
![image](https://user-images.githubusercontent.com/1700823/145493236-718f29bb-29b4-478a-82e4-c3fd22643cc1.png)

**Comment by bigfootjon** [comment]
This is also causing some issues with Dr. CI. I've got a fix ready that I'll deploy in the morning. Until then, Dr. CI may post incorrect information about jobs

**Comment by seemethere** [comment]
Appears as though our suspicions about this being a Github server side issue is correct: https://github.com/actions/runner/issues/1546#issuecomment-991135687

**Comment by seemethere** [comment]
Just did some checking after hearing back from Github, appears as though this is mostly resolved now 
![image](https://user-images.githubusercontent.com/1700823/145624571-4ba39664-7cce-4e14-9602-2db469c6dfe3.png)


Going to tentatively mark this as closed

**Comment by seemethere** [comment]
Re-opening this to increase awareness but the issue has been mitigated

**Comment by seemethere** [comment]
Re-opening to signal boost this back to HUD users, just in case they're wondering why their CI failed earlier, will close by EOD
