### ISSUE TITLE
[RFC] Require users to set `torch.cuda.current_device()` appropriately for ShardedTensor

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#69731]
### 🚀 The feature, motivation and pitch

In several scenarios, ShardedTensor needs to perform certain collective operations using the NCCL process group and needs to build a CUDA tensor on an appropriate device.

This "appropriate device" is hard to determine within ShardedTensor code since a particular rank might not even have a local shard whose device can be reused for this purpose. As a result, we have a few hacks and heuristics in terms of how we come up with the appropriate device:

* https://github.com/pytorch/pytorch/blob/master/torch/distributed/_sharded_tensor/api.py#L275
* https://github.com/pytorch/pytorch/blob/master/torch/distributed/_sharded_tensor/api.py#L326

We should have a clear way of determining the appropriate device for a particular rank. Since we expect users to run a rank per GPU, it seems natural that we ask users to appropriately set the current device appropriately for each rank which is using ShardedTensor.

This simplifies a lot of our logic while implementing core ShardedTensor features and also allows us to write more robust code ensuring users have a good UX.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by wanchaol** [comment]
Thanks for proposing! I am on the same page with this, and im actually facing this problem right now with the case that some ranks don't have local shards, so it's hard to determine a device before the collective. I am right now doing almost exactly the same thing as suggested in the RFC, where in `init_from_local_shards` by default we have the current rank as the proper device. https://github.com/pytorch/pytorch/pull/69493/files#diff-fdb5c2910a7200d505294c41813f34f88d67d6d6d399367d233298fddeaf8f1aR337 
I think this make a lot of sense as the collectives that the sharded tensor internally calling, should follow some rule from the user (i.e. my rank manage my current CUDA device).

Some questions I have:
> users to run a rank per GPU

Is this assumption be true for all cases? Even when user have a smaller world_size but large device set, we don't recommend user to manage multiple devices in one rank?

> it seems natural that we ask users to appropriately set the current device appropriately for each rank which is using ShardedTensor

Should we select the current device for the user by default, or user need to manually call the context manager before any APIs that involves collective? If user need to manually call the context manager, how could user determine which API need to use the collective (some apis might not be that intuitive like `init_from_local_shards`)? It seems like we need to explicitly mention this in the doc if we want to do that.

**Comment by pritamdamania87** [comment]
> Is this assumption be true for all cases? Even when user have a smaller world_size but large device set, we don't recommend user to manage multiple devices in one rank?

I think it is fine for the user to do this, but in general the recommended setup would be similar to DDP where we have a process per GPU.

> Should we select the current device for the user by default, or user need to manually call the context manager before any APIs that involves collective? If user need to manually call the context manager, how could user determine which API need to use the collective (some apis might not be that intuitive like init_from_local_shards)? It seems like we need to explicitly mention this in the doc if we want to do that.

I don't think we can select the current device for the user by default correctly 100% of time. I think in our docs we should clearly mention that user should call `torch.cuda.set_device()` in their training script appropriately. This shouldn't be a context manager, but rather just set globally at the beginning.
