### ISSUE TITLE
[caffe2] YellowFin major bug

### ISSUE THREAD

**Issue by edubois** [pytorch/pytorch#6975]
## Issue description

yellowfin_op_gpu.cu +69
I read:
`moment_out[i] = mu * moment[i] * lr * grad[i];`

To me, it should be:
`moment_out[i] = mu * moment[i] + lr * grad[i];`

The CPU code is not affected.

**Comment by yinghai** [comment]
@edubois The two lines of code are identical?

**Comment by edubois** [comment]
No, one is mu plus moment **time** lr times grad instead of mu plus moment **plus** lr times grad.

**Comment by yinghai** [comment]
I see.  Send a PR? :)

**Comment by edubois** [comment]
Will do :)
