### ISSUE TITLE
ROCM 4.1 nightly builds are broken since Nov12th

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#69773]
### 🐛 Describe the bug

See here https://hud.pytorch.org/ci/pytorch/pytorch/nightly?name_filter=rocm4_1

### Versions

Irrelevant

cc @ezyang @gchanan @zou3519 @bdhirsh @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Since it has been like that for over a month, question: anyone are using 4.1?

**Comment by seemethere** [comment]
I vote to kill it if we're not going to fix it, @jeffdaily, @jithunnair-amd wdyt?

**Comment by jithunnair-amd** [comment]
@seemethere We'll be killing ROCm4.1 nightly builds in the PR to enable nightly wheel builds for ROCm4.5.2. We plan to file the PR shortly, just need to resolve an issue wrt `BUILD_DEBUG_INFO=1` in the wheel build script.
