### ISSUE TITLE
torch.optim.lr_scheduler.SequentialLR.get_last_lr() does not work

### ISSUE THREAD

**Issue by Markus28** [pytorch/pytorch#69794]
### 🐛 Describe the bug

Hi,

if we instantiate a `torch.optim.lr_scheduler.SequentialLR` scheduler, perform a step and call `get_last_lr()`, we get an exception:
```
Traceback (most recent call last):
  File "[foobar]/break_torch.py", line 14, in <module>
    print(lr_scheduler.get_last_lr())
  File "[foobar]/env/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 99, in get_last_lr
    return self._last_lr
AttributeError: 'SequentialLR' object has no attribute '_last_lr'
```
Here is the minimal example that produces this behavior on torch 1.10.0:
```
import torch
from torch.optim.lr_scheduler import SequentialLR, LinearLR, ExponentialLR

param = torch.nn.Parameter(torch.ones(2,2))
optim = torch.optim.Adam(params=[param], lr=0.0004)
warmup_scheduler = LinearLR(optim, start_factor=0.05, end_factor=1, total_iters=10)
decay_scheduler = ExponentialLR(optim, gamma=0.99)
lr_scheduler = SequentialLR(optim, schedulers=[warmup_scheduler, decay_scheduler], milestones=[10])

for _ in range(100):
    optim.zero_grad()
    optim.step()
    lr_scheduler.step()
    print(lr_scheduler.get_last_lr())
```
I believe this is because `self._last_lr` is never set in the `step` method: https://github.com/pytorch/pytorch/blob/41c344d460a941c57f4793690c396f830a992824/torch/optim/lr_scheduler.py#L628

I guess that fixing this is as easy as adding the line
```
self._last_lr = [group['lr'] for group in self.optimizer.param_groups]
```
I'd be happy to raise a small pull request for this.

Best,
Markus

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.0
Libc version: glibc-2.10

Python version: 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.8.0-59-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.10.0+cu111
[pip3] torchvision==0.11.1+cu111
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.20.0                   pypi_0    pypi
[conda] numpydoc                  0.9.2                      py_0  
[conda] torch                     0.4.1.post2              pypi_0    pypi

**Comment by jaketae** [comment]
This should be fixed in https://github.com/pytorch/pytorch/pull/70558!

**Comment by etetteh** [comment]
Please, is there any fix to this error? 
I am having the same error with `1.10.2+cu113`

**Comment by jaketae** [comment]
@etetteh I don't think the merged PR was part of `1.10`. You might want to use torch nightly or build from source.

**Comment by etetteh** [comment]
@jaketae thank you for your suggestion. I ended up using the fix suggested above by @Markus28

**Comment by janeyx99** [comment]
I believe this should be fixed so am closing the issue--please reopen if I am mistaken!
