### ISSUE TITLE
[quant] Add support for ConvTranspose2d + BN fusion

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#69797]
Leverage the existing https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/fusion.py#L16 Conv BN fusion to add support for ConvTranspose.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
this is fixed now with the PR
