### ISSUE TITLE
How to use cudnn in pytorch？

### ISSUE THREAD

**Issue by KangolHsu** [pytorch/pytorch#698]
Could you give me some examples?

**Comment by soumith** [comment]
You dont need to do anything special. It's used automatically.

**Comment by iammarvelous** [comment]
@soumith I am wondering how to set cudnn parameters like `cudnn.benchmark` and `cudnn.fastest`. Also, is there any way to find out whether I am using cudnn or not?

**Comment by nian-liu** [comment]
@iammarvelous  see [this](https://discuss.pytorch.org/t/error-when-using-cudnn/577/11)

**Comment by dizcza** [comment]
To verify that pytorch uses cudnn:
```
>>> torch.backends.cudnn.version()
6021
```

**Comment by D-X-Y** [comment]
I found that if the library path does not include cudnn, the  torch.backends.cudnn.version() still output 6021. So how to verify that I indeed use cudnn?

**Comment by dizcza** [comment]
@D-X-Y I assume because pytorch installs cuda & cudnn packages in its own place, you don't see them in global LD_LIBRARY_PATH

**Comment by D-X-Y** [comment]
@dizcza I think they dynamically load the cudnn library from the system path. Because for the same code, if I put the cudnn lib in LD_LIBRARY_PATH, the gpu memory cost much more less than the cudnn is not in the system path.

**Comment by acgtyrant** [comment]
I find `lib/python3.5/site-packages/torch/lib/libcublas-e78c880d.so.8.0.88` in my virtual environment, so I think the cudnn library is built-in.
