### ISSUE TITLE
torchrl

### ISSUE THREAD

**Issue by sonelu** [pytorch/pytorch#69803]
### 🚀 The feature, motivation and pitch

Given the ubiquity of pytorch in RL should we have a subproject for `torchrl` similar to `torchvision`, `torchaudio` and `torchtext`?

**Pitch**

Every single RL book in the last few years includes author's custom frameworks that cover common RL activities. Unfortunately most of them are only used in the context of those books and rarely become mainstream.

As pointed in #34223 there are a number of 3rd party RL frameworks, but a quick review shows that:
- some have not been updated in more than 2 years
- some only implement specific agents
- most have very limited documentation or no documentation at all

Others like [RLLib](https://docs.ray.io/en/latest/rllib-algorithms.html) are part of a more complex framework and are designed to work with multiple backends, which makes them unnecessary complex.

I think a subproject in the style of `torchvision`, `torchaudio` and `torchtext` would be beneficial for:
- pre-trained models / agents to be used as baseline for new RL research
- generalised environment interation
- common RL tools and utils
- documentation

### Alternatives

Third party frameworks - some discussed above.

### Additional context

A previous request #34223 was not considered, but I think the request was not stated at that time very clear. In this issue I suggest that the RL specific content to be developed as a subproject.

**Comment by gchanan** [comment]
CC @dongreenberg

**Comment by fibbonnaci** [comment]
This is on our radar and we're talking to maintainers of these other repos to think about our approach as they mature.

**Comment by vmoens** [comment]
Well I think we can close this @jisaacso
