### ISSUE TITLE
Wrong dependency specification in libc10.so

### ISSUE THREAD

**Issue by adampauls** [pytorch/pytorch#69812]
### 🐛 Describe the bug

I believe the dependency on libgomp for the pre-built linux binaries is improperly specified. `ldd` on `libc10.so` (and others) shows ```libgomp-52f2fd74.so.1 => /dependencies/libtorch/lib/libgomp-52f2fd74.so.1```, but `readelf -d` on `libgomp-52f2fd74.so.1` gives ```0x000000000000000e (SONAME)             Library soname: [libgomp.so.1]```. These are all from [this pre-built version of libtorch](https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcpu.zip). IIUC, this means that if `libgomp-52f2fd74.so.1` is separately loaded, it will not register as satisfying the dependency of `libc10.so` because loading `libgomp-52f2fd74.so.1` will register `libgomp.so.1` as loaded, but `libc10.so` depends on `libgomp-52f2fd74.so.1`. 

I think the only reason the current setup works is that the rpath of `libgomp-52f2fd74.so.1` correctly points to `libgomp-52f2fd74.so.1`, so as long both `libc10.so` and `libgomp-52f2fd74.so.1` are in the same directory, everything works. This is not true in our setup. 

I think the resolution is either to change the dependency of all libs to specify `libgomp.so.1` (but still with rpath `libgomp-52f2fd74.so.1`), or to change the soname of `libgomp-52f2fd74.so.1` to be `libgomp-52f2fd74.so.1`, depending on whether `libgomp-52f2fd74.so.1` is binary-compatible with other versions of `libgomp.so.1`. 

### Versions

libtorch-cxx11-abi-shared-with-deps-1.10.0+cpu. I have not checked the CUDA builds of the same version, but I would assume they have the same problem.

**Comment by adampauls** [comment]
I've had trying to understand the documentation around dynamic library loading and I am no longer confident that runtime-loading uses the soname to decide when I library has already been loaded. Documentation doesn't seem to be clear one way or the other, but the problem does not seem to exists for the macos binary.

**Comment by adampauls** [comment]
Okay, I think I've misunderstood. Indirection at runtime is supposed to happen with symlinks. The soname is only meant to be used at link time.

**Comment by keith** [comment]
I hit this too, I feel like this is a real issue. Seemingly no matter what I do things end up preferring the globally installed libgomp because of the conflicting soname
