### ISSUE TITLE
[bug] torch.normal

### ISSUE THREAD

**Issue by wanghan0501** [pytorch/pytorch#6981]
environment:
 - pytorch: 0.4.0
 - cuda: 9.0
 - cudnn: 7.0

![bug](https://user-images.githubusercontent.com/13730405/39290558-8fddf99e-4962-11e8-9647-595b316a52c7.png)

However, when I using torch.normal( ), I get an error message and I didn't know why it need  torch.Generator as parameter

**Comment by lanpa** [comment]
`mean`, not `means`

**Comment by wanghan0501** [comment]
however, when pytorch=0.3.1  it works

**Comment by apaszke** [comment]
That means we must have fixed the bug ;)
