### ISSUE TITLE
Using Autograd before and after forking should be possible

### ISSUE THREAD

**Issue by ChristopherBrix** [pytorch/pytorch#69839]
### 🚀 The feature, motivation and pitch

I'm aware that [autograd cannot be used in combination with forking, because it uses thread pools](https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork).
However, it would be nice if autograd could be used both before and after forking, as long as they don't share any information.

I've written a minimal example:
```
import multiprocessing as mp
import torch


def train():
    print("Training started")
    x = torch.Tensor(0)
    x.requires_grad = True
    x.sum().backward()
    print("Training ended")


if __name__ == "__main__":
    print("Entered main")
    train()
    worker = mp.Process(target=train)
    worker.start()
```

Expected output:
```
Entered main
Training started
Training ended
Training started
Training ended
```

Real output:
```
Entered main
Training started
Training ended
Training started
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "mwe.py", line 9, in train
    x.sum().backward()
  File "/home/christopher/.local/share/virtualenvs/src-i_X_I5Sj/lib/python3.8/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/christopher/.local/share/virtualenvs/src-i_X_I5Sj/lib/python3.8/site-packages/torch/autograd/__init__.py", line 98, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Unable to handle autograd's threading in combination with fork-based multiprocessing. See https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork
```

The above example did work in PyTorch 1.4 but stopped working in 1.5.

### Alternatives

If this feature won't be added, I recommend to extend the documentation and to explicitly state that autograd will fail even if there is no sharing of information across threads.

### Additional context

This unsupported behavior seems to be a bit confusing, raising at least two questions on StackOverflow (second one by me):
 - https://stackoverflow.com/questions/63081486/pytorch-multiprocessing-error-with-hogwild
 - https://stackoverflow.com/questions/70308084/using-pytorch-in-multiple-independent-forked-threads

The error message is raised in https://github.com/pytorch/pytorch/blob/065018d8120567976b5f9296e56c3ece5db51e12/torch/csrc/autograd/engine.cpp#L1047-L1053

cc @VitalyFedyunin @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
Hi,
It is the other way around actually, it is ok to fork as long as you didn't use autograd yet.
This is because that way, we know that no state was initialized and so each fork will do its own initialization.

> no sharing of information across threads.

You mean processes right?

**Comment by albanD** [comment]
I think we would be happy to discuss how to do that and accept a PR that does it once the design is accepted.
But I am not sure how to do this from the top of my head so someone would need to look into more details.

Note that this is relatively low priority for us so I am not sure we will have time to look at this soon. But happy to help anyone that wants to take this on.

**Comment by ezyang** [comment]
Even if you could uninitialize autograd, what about the OMP threadpool, or anywhere else?

**Comment by jonlachmann** [comment]
If I run ``torch_set_num_threads(1)`` before initializing autograd, would this mean that I (in theory) am allowed to fork new threads as I want? Or is there another mechanism that causes autograd to not like forking?

I have a use case where many small models are built, why each model is assigned a single thread, so there is no need for multiple threads inside autograd.

**Comment by ezyang** [comment]
I double checked the autograd implementation and set num threads does not affect the number of autograd threads (which is always pegged to the number of devices in your system). IDK if @albanD is interested in having a single threaded autograd mode, I suppose it could hypothetically be useful...

**Comment by albanD** [comment]
If you don't have GPU/TPU devices, there won't be any worker threads actually.
So we can actually relax this constrain to only forbid forking if any worker thread was created.

And yes, set_num_threads is only for intra op parallelism basically (OMP/MKL threading).


I think we would be happy to update the fork detection in the autograd engine only when workers are actually created.

**Comment by jonlachmann** [comment]
@albanD To relax the constraint sounds like a great idea, it would completely solve the problem that I am having, and I think that I am probably not alone in having a similar use case.

Is there something that I can help out with?
