### ISSUE TITLE
[Caffe2] How to change Operator parameters in C++ ? 

### ISSUE THREAD

**Issue by dbrazey** [pytorch/pytorch#6984]
Hello, 

I have loaded a Detectron model (found in model zoo) in a Workspace and I would like to change the value of "nms_th" parameter which is in the operator GenerateProposals. 

How can I change this value (0.7 by default) from my C++ code, through the Workspace object ? 

Actually, from the Workspace, I can get a vector of Operators from the NetBase object. 
Then, I think I need to modify the OperatorDef private member variable, but I cannot manage to do this. 

Thanks for your help :)

**Comment by jimmyoic** [comment]
find the operator you want to modify (Operator op = {the operator contains nms_th})
op.mutable_arg(0)->set_f({the value you want to fill});

**Comment by dbrazey** [comment]
Thanks for your reply, it works. 
I used `op.mutable_arg(i)->name()` to find the right argument to modify.
