### ISSUE TITLE
[NNC] Fusion Error When Running With XNNPACK=0

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#69859]
### 🐛 Describe the bug

If you try to run fusion with `USE_XNNPACK=0` you will run into a compilation failure: 

```
@torch.jit.script
def foo(x, y):
    return torch.sigmoid(x + y)

inp = torch.rand([4, 4])
foo(inp, inp)
foo(inp, inp)
foo(inp, inp)
```
> RuntimeError: 
Unknown custom class type xnnpack.Conv2dOpContext. Please ensure it is registered.:
prepacked::conv2d_clamp_run(Tensor X, __torch__.torch.classes.xnnpack.Conv2dOpContext W_prepack) -> (Tensor Y)

That is because are always trying to register a lowering for XNNPack even if it is not built. See: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/tensorexpr/lowerings.cpp#L34

cc @ZolotukhinM @IvanKobzarev

**Comment by IvanKobzarev** [comment]
@eellison 
Thanks, the fix will be https://github.com/pytorch/pytorch/pull/69870
