### ISSUE TITLE
Some inplace ops fail for forward AD because they mutate ZeroTensor

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#69855]
The issue is that certain in-place forward AD formulas don't handle ZeroTensor properly:

```
# add_

x = torch.ones(5, 3)
p = torch.ones(5, 3)
t = torch.ones(5, 3)

with fwAD.dual_level():
    dual = fwAD.make_dual(p, t)
    x.add_(dual)  # OK


# index_add_

x = torch.ones(5, 3)
t = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
p = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)

index = torch.tensor([0, 4, 2])

with fwAD.dual_level():
    dual = fwAD.make_dual(p, t)
    x.index_add_(0, index, dual)  # RuntimeError: ZeroTensors are immutable.
```

The fix should be to do something like what `add__Tensor` does and check whether `self_t`  is defined:
```
self_new_fw_grad_opt = self_t_raw.defined() ? self_t_raw.copy_(self_t + maybe_multiply(other_t, alpha)) : self_t + maybe_multiply(other_t, alpha);
```

See edit history for original issue.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @anjali411

**Comment by anjali411** [comment]
@soulitzer we made zero tensors in-place to prevent race condition. I haven't run reproduced the test failures yet. Could you share more details about where do we need the in-place modification of gradients?

**Comment by soulitzer** [comment]
@anjali411 You may need to check out the PR to replicate the error since it has not landed. The in-place modification could be happening in the backward formulas. For example in `as_strided_backward` we call into `index_add_`, and that seems to be triggering the error in the zero tensor fallback.

 <details>
<summary>
stack trace for as_strided
</summary>

======================================================================
ERROR: test_fn_fwgrad_bwgrad_as_strided_cpu_float64 (__main__.TestGradientsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 381, in instantiated_test
    raise rte
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    result = test(self, **param_kwargs)
  File "/local/pytorch4/torch/testing/_internal/common_device_type.py", line 753, in test_wrapper
    return test(*args, **kwargs)
  File "test/test_ops.py", line 833, in test_fn_fwgrad_bwgrad
    self._check_helper(device, dtype, op, op.get_op(), "fwgrad_bwgrad")
  File "test/test_ops.py", line 776, in _check_helper
    self.assertTrue(gradgradcheck(fn, gradcheck_args, **kwargs))
  File "/local/pytorch4/torch/testing/_internal/common_utils.py", line 2893, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1544, in gradgradcheck
    return gradcheck(
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1398, in gradcheck
    return _gradcheck_helper(**args)
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1412, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1082, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1281, in _fast_gradcheck
    analytical_vJu = _get_analytical_jacobian_forward_ad(func, inputs, _as_tuple(func_out),
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 343, in _get_analytical_jacobian_forward_ad
    raw_outputs = _as_tuple(fn(*dual_inputs))
  File "/local/pytorch4/torch/autograd/gradcheck.py", line 1539, in new_func
    grad_inputs = torch.autograd.grad(outputs, input_args, grad_outputs, create_graph=True,
  File "/local/pytorch4/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: ZeroTensors are immutable. Please use the materialized zero tensor obtained using .clone() if you want a mutable tensor.
Exception raised from zeroTensorFallback at ../aten/src/ATen/ZeroTensorFallback.cpp:61 (most recent call first):
frame #0: <unknown function> + 0xdf739 (0x7f13284ac739 in /local/pytorch4/torch/lib/libc10.so)
frame #1: std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > ()>::operator()() const + 0x50 (0x7f1335811dfc in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #2: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x44 (0x7f13284ab89e in /local/pytorch4/torch/lib/libc10.so)
frame #3: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x7f (0x7f13284a93e5 in /local/pytorch4/torch/lib/libc10.so)
frame #4: <unknown function> + 0x83d4795 (0x7f13308ce795 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x83d6dc3 (0x7f13308d0dc3 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x907e4c5 (0x7f13315784c5 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #7: at::Tensor& c10::Dispatcher::redispatch<at::Tensor&, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&)> const&, c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) const + 0x2aa (0x7f13314a8d6a in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #8: at::_ops::index_add__alpha::redispatch(c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x195 (0x7f133141a555 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #9: at::redispatch::index_add_(c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x4a (0x7f1334e44da9 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0xd0d81d5 (0x7f13355d21d5 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0xd13a2c6 (0x7f13356342c6 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x907e3bc (0x7f13315783bc in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #13: at::Tensor& c10::Dispatcher::redispatch<at::Tensor&, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&>(c10::TypedOperatorHandle<at::Tensor& (at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&)> const&, c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) const + 0x1dc (0x7f13314a8c9c in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #14: at::_ops::index_add__alpha::redispatch(c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x195 (0x7f133141a555 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #15: at::redispatch::index_add_(c10::DispatchKeySet, at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x4a (0x7f1334e44da9 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0xc8961a5 (0x7f1334d901a5 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0xc919e2a (0x7f1334e13e2a in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #18: <unknown function> + 0x907e3bc (0x7f13315783bc in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #19: at::_ops::index_add__alpha::call(at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x49e (0x7f133141a29c in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #20: at::Tensor::index_add_(long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) const + 0x3f (0x7f133fb30df3 in /local/pytorch4/torch/lib/libtorch_python.so)
frame #21: at::native::index_add_(at::Tensor&, long, at::Tensor const&, at::Tensor const&) + 0x5b (0x7f1330f0f8c7 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #22: <unknown function> + 0x9bf87c9 (0x7f13320f27c9 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #23: <unknown function> + 0x9d3aab4 (0x7f1332234ab4 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #24: <unknown function> + 0x9055695 (0x7f133154f695 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #25: at::_ops::index_add_::call(at::Tensor&, long, at::Tensor const&, at::Tensor const&) + 0x3f6 (0x7f1331ba7a84 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #26: at::Tensor::index_add_(long, at::Tensor const&, at::Tensor const&) const + 0x34 (0x7f133fb30db2 in /local/pytorch4/torch/lib/libtorch_python.so)
frame #27: <unknown function> + 0xc896726 (0x7f1334d90726 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #28: <unknown function> + 0xc919e2a (0x7f1334e13e2a in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #29: <unknown function> + 0x907e3bc (0x7f13315783bc in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #30: at::_ops::index_add__alpha::call(at::Tensor&, long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) + 0x49e (0x7f133141a29c in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #31: at::Tensor::index_add_(long, at::Tensor const&, at::Tensor const&, c10::Scalar const&) const + 0x3f (0x7f133fb30df3 in /local/pytorch4/torch/lib/libtorch_python.so)
frame #32: at::native::index_add_(at::Tensor&, long, at::Tensor const&, at::Tensor const&) + 0x5b (0x7f1330f0f8c7 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #33: <unknown function> + 0x9bf87c9 (0x7f13320f27c9 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #34: <unknown function> + 0x9d3aab4 (0x7f1332234ab4 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #35: <unknown function> + 0x9055695 (0x7f133154f695 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #36: at::_ops::index_add_::call(at::Tensor&, long, at::Tensor const&, at::Tensor const&) + 0x3f6 (0x7f1331ba7a84 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #37: at::Tensor::index_add_(long, at::Tensor const&, at::Tensor const&) const + 0x34 (0x7f133fb30db2 in /local/pytorch4/torch/lib/libtorch_python.so)
frame #38: <unknown function> + 0xdcd9ca2 (0x7f13361d3ca2 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #39: torch::autograd::generated::AsStridedBackward0::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x201 (0x7f13346e42d1 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #40: <unknown function> + 0xd1a2123 (0x7f133569c123 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #41: <unknown function> + 0xd19b7eb (0x7f13356957eb in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #42: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x3a8 (0x7f1335695d72 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #43: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x53d (0x7f1335692d79 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #44: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x237 (0x7f1335697e3d in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #45: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x72 (0x7f13400d334a in /local/pytorch4/torch/lib/libtorch_python.so)
frame #46: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x635 (0x7f13356977b9 in /local/pytorch4/torch/lib/libtorch_cpu.so)
frame #47: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0xb7 (0x7f13400d326d in /local/pytorch4/torch/lib/libtorch_python.so)
frame #48: THPEngine_run_backward(_object*, _object*, _object*) + 0xc5d (0x7f13400d406b in /local/pytorch4/torch/lib/libtorch_python.so)
<omitting python frames>

</details>

**Comment by soulitzer** [comment]
Updated this issue to better describe the root cause

**Comment by albanD** [comment]
For inplace ops where self doesn't have a grad, we want to make an actual Tensor full of zeros.

More importantly we should see why the OpInfo for index_add didn't catch that.

**Comment by anjali411** [comment]
> For inplace ops where self doesn't have a grad, we want to make an actual Tensor full of zeros.

yeah we should add a generic logic in codegen to do that

> More importantly we should see why the OpInfo for index_add didn't catch that.
 
 yeah I agree
