### ISSUE TITLE
Obliviate repeat_test_for_types usage in pytorch

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#69865]
### 🚀 The feature, motivation and pitch

Currently there are still a few tests in the codebase (mostly in test_nn.py) that use repeat_test_for_types to repeat a test for different data types. There is now a better way to do this with OpInfos which is now used across most of pytorch. We should migrate these tests away from using repeat_test_for_types and remove repeat_test_for_types in common_utils.py. 

### Additional context

The current test cases that use this decorator still are below.
In test_nn.py
* test_Conv2d_deterministic_cudnn
* test_Conv2d_large_workspace
* test_ConvTranspose2d_large_output_padding
* test_Conv2d_depthwise_naive_groups_cuda
* test_Conv3d_depthwise_naive_groups_cuda
* test_noncontig_conv_grad_cuda
* test_batchnorm_large_batch
* test_conv_double_backward_cuda

In test_data_parallel.py
* test_data_parallel_module
* test_data_parallel_module_kwargs_only
* test_data_parallel_module_kwargs_only_empty_list
* test_data_parallel_module_kwargs_only_empty_dict
* test_data_parallel_module_kwargs_only_empty_tuple

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by mruberry** [comment]
These tests should be reviewed for redundancy with existing OpInfo tests (and if redundant they should be deleted) or updated to use the device generic test framework and the `@dtypes` decorator
