### ISSUE TITLE
Conflict between dataloader and cupy in single thread

### ISSUE THREAD

**Issue by GuaiYiHu** [pytorch/pytorch#69887]
### 🐛 Describe the bug

When using Dataloader to read data from Dataset processed by cupy in a single thread, cupy raises an error. Here is the sample code bellow.

```
import cupy as cp
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class TestDataset(Dataset):
    def __init__(self):
        pass

    def __getitem__(self, index):
        # cupy code here!
        cp.random.seed(1)
        return index

    def __len__(self):
        return 1000

def test_worker(gpu=0):
    dataset = TestDataset()

    train_loader = DataLoader(dataset,
                              1,
                              shuffle=True,
                              pin_memory=True,
                              num_workers=1)

    for index in train_loader:
        print(index)

if __name__ == '__main__':
    test_worker()
```

The error is as follows.

`cupy_backends.cuda.api.runtime.cudaruntimeerror.__init__ type error: an integer is required`

However, when using multi thread with spawn, cupy works as normal. Here is the sample code.

```
import cupy as cp
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch.multiprocessing as mp


class TestDataset(Dataset):
    def __init__(self):
        pass

    def __getitem__(self, index):
        # cupy code here!
        cp.random.seed(1)
        return index

    def __len__(self):
        return 1000

def test_worker(gpu=0):
    dataset = TestDataset()

    train_loader = DataLoader(dataset,
                              1,
                              shuffle=True,
                              pin_memory=True,
                              num_workers=1)

    for index in train_loader:
        print(index)

if __name__ == '__main__':
    mp.spawn(
        test_worker
    )
```

I'm using cupy 0.9.6. I think there is something wrong with torch.utils.data.Dataloader. Hope it could be fixed. Thank you!

### Versions

PyTorch version: 1.7.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA TITAN Xp
Nvidia driver version: 470.74
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.2
[pip3] numpyencoder==0.3.0
[pip3] pytorch-swats==0.1.0
[pip3] pytorch3d==0.3.0
[pip3] torch==1.7.1+cu101
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.8.2+cu101
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.3.0            py38h54f3939_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] numpyencoder              0.3.0                    pypi_0    pypi
[conda] pytorch-swats             0.1.0                    pypi_0    pypi
[conda] pytorch3d                 0.3.0                    pypi_0    pypi
[conda] torch                     1.7.1+cu101              pypi_0    pypi
[conda] torchaudio                0.7.0                      py38    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.8.2+cu101              pypi_0    pypi

cc @VitalyFedyunin @SsnL @ejguan @NivekT @ngimel

**Comment by ejguan** [comment]
I believe the problem is cupy doesn't work well with multiprocessing using fork. It's probably related to the cuda context.
