### ISSUE TITLE
Pytorch4.0 in win10

### ISSUE THREAD

**Issue by PaulGitt** [pytorch/pytorch#6989]
My system is win10, python3.5.2,  cuda8.0, cudnn6.0
Just install the newest pytorch4.0
I use pycharm to import torch, cannot use it.
But I use cmd to import torch, it can work.
What happened?

**Comment by soumith** [comment]
@PaulGitt do you have a question?

**Comment by PaulGitt** [comment]
Yeah, just update my question @soumith

**Comment by jay960702** [comment]
Your project interpreter of pycharm may not be set properly. @PaulGitt

**Comment by PaulGitt** [comment]
I already check, it set properly
![_20180126105407](https://user-images.githubusercontent.com/23419375/39310355-c2c3289a-499c-11e8-86f1-73b7a0d802d3.png)

**Comment by PaulGitt** [comment]
It solve, it is the project interpreter problem.Thanks.
