### ISSUE TITLE
RuntimeError: UNSUPPORTED DTYPE

### ISSUE THREAD

**Issue by blzheng** [pytorch/pytorch#69903]
# 🐛 Describe the bug

We found that PyTorch1.10 will introduce runtime error when running googlenet bf16 inference. It is very interesting that this error only appears when we install pytorch via "pip install torch", but it doesn't appear when we build from the source code.

# Reproduce
pip install torch
pip install torchvision

```
import torch
import torchvision.models as models

model = models.__dict__['googlenet'](pretrained=True)
input_tensor = torch.randn(1, 3, 224, 224)
model = model.eval()
input_tensor = input_tensor.to(memory_format=torch.channels_last)
model = model.to(memory_format=torch.channels_last)
with torch.cpu.amp.autocast(cache_enabled=False), torch.no_grad():
    model = torch.jit.trace(model, input_tensor, strict=False)
model = torch.jit.freeze(model)

with torch.no_grad():
    for i in range(10):
        output = model(input_tensor)
        print(output)

```

# Error info
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    output = model(input_tensor)
  File "/home/sdp/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: UNSUPPORTED DTYPE

**Comment by eellison** [comment]
I think this means that it has since been fixed on master. Closing. If you can re-repro on nightly feel free to re-open.

**Comment by eagomez2** [comment]
Hi,

How did you solve this error @blzheng ? I am experiencing the same issue with a model. My guess is that it is because I'm tracing a model that inside a function implicitly casts a result to be torch.complex by multiplying by 1j, although I expected torch to be able to trace complex types without issues.
