### ISSUE TITLE
`torch.jit.operator_upgraders` introduces new runtime dependency to `yaml`

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#69905]
### 🐛 Describe the bug

`import yaml` was added to `torch/jit/operator_upgraders.py` by https://github.com/pytorch/pytorch/pull/68772
Which is not properly reflected as `setup.py` dependency. 

TODO: Revert https://github.com/pytorch/vision/commit/743fe1ab802c27c52a5372577d006d595e65677b after issue is closed

### Versions

https://download.pytorch.org/whl/nightly/cpu/torch-1.11.0.dev20211214%2Bcpu-cp36-cp36m-linux_x86_64.whl

cc @ezyang @gchanan @zou3519 @bdhirsh @malfet @seemethere

**Comment by malfet** [comment]
What is the right course of action here:
- Revert PR
- Make it dynamic dependency of `update_operators`
- Make it mandatory runtime dependency for pytorch

**Comment by malfet** [comment]
cc: @tugsbayasgalan

**Comment by cccclai** [comment]
Can be resolved with https://github.com/pytorch/pytorch/pull/69194
