### ISSUE TITLE
AVX related build errors in ATen when using gcc 5.5 on ubuntu 16.04

### ISSUE THREAD

**Issue by prigoyal** [pytorch/pytorch#6992]
I was building a docker image which builds aten as well. ATen failed to build because of errors like 

```
usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11280): error: argument of type "void *" is incompatible with parameter of type "long long *"
```

This happens when using gcc 5.5 (which ubuntu toolchain ships as default now). It seems to be a gcc bug https://github.com/tensorflow/tensorflow/issues/10220#issuecomment-352110064 

filing the issue here so that when pytorch docker images are upgraded on CI, this can be tracked and addressed (if needed).

cc @cpuhrsch

**Comment by prigoyal** [comment]
update: i looked at gcc bug tracker https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=__open__&content=avx512&no_redirect=1&order=changeddate%2Cpriority%2Cbug_severity&product=gcc&query_format=specific and couldn't find any report on this.

**Comment by cpuhrsch** [comment]
@prigoyal - Could you try again now?

**Comment by xingkongliang** [comment]
@prigoyal Do you solve this problem?
