### ISSUE TITLE
Windows Compilation failure with VS2022

### ISSUE THREAD

**Issue by ankurvdev** [pytorch/pytorch#69948]
### 🐛 Describe the bug

Windows compilation with VS2022 fails with the following error

```
pytorch.git\torch/csrc/utils/python_arg_parser.h(123): error C3646: 'max_args': unknown override specifier
pytorch.git\torch/csrc/utils/python_arg_parser.h(123): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
pytorch.git\torch/csrc/utils/python_arg_parser.h(138): error C3646: 'min_args': unknown override specifier
pytorch.git\torch/csrc/utils/python_arg_parser.h(139): error C3646: 'max_args': unknown override specifier
pytorch.git\torch/csrc/utils/python_arg_parser.h(140): error C3646: 'max_pos_args': unknown override specifier
pytorch.git\torch/csrc/utils/python_arg_parser.h(140): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

### Versions

commit e9327ed2cee458229dc3425fc38525dc81219e20 (grafted, HEAD)
Author: Rui Zhu <zrphercule@fb.com>
Date:   Mon Sep 27 18:38:13 2021 -0700

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by seemethere** [comment]
I don't think we currently have a CI configuration that's running with VS2022 so this makes sense why it wasn't caught by CI

**Comment by malfet** [comment]
Interesting... I bet it's because `ssize_t` is not defined. Which poses a nice BE task : we should not be using ssize_t in the codebase

**Comment by mszhanyi** [comment]
@ankurverma85, 
Visual studio upgrades very frequently (about every 2 weeks.) 
There're several cases that PyTorch CI was broken due to regressions. 
(https://github.com/pytorch/pytorch/issues/54502).

If you want to build PyTorch on Windows, currently it'd better to VS 2019 version 16.8.6.

**Comment by ankurvdev** [comment]
FWIW changing ssize_t to size_t fixes the problem with VS2022

**Comment by malfet** [comment]
I believe issue should be resolved now by number of PR ending in https://github.com/pytorch/pytorch/pull/71390
