### ISSUE TITLE
LayerNorm has extremely low SM Efficiency & is slow for large inputs

### ISSUE THREAD

**Issue by jxtps** [pytorch/pytorch#69963]
### 🐛 Describe the bug

I'm trying to train https://github.com/JingyunLiang/SwinIR - it's a Swin Transformer used for Image Reconstruction. As such it has one transformer token per pixel, which leads to very large input tensors like `[1, 1024*1024, 128]`. Running these through `LayerNorm(128)` is extremely non-performant, to the point of being unusable.   

Running the example code below, I get the following pie-chart in tensorboard - `LayerNorm` takes >90% of the time: 
![image](https://user-images.githubusercontent.com/90846/146130413-5a49e7e1-1626-41c0-affe-78aec06db961.png)

The poor SM efficiency can be seen for the main culprit [`GammaBetaBackwardCUDAKernel`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/layer_norm_kernel.cu#L550), called as part of `aten::native_layer_norm_backward`: 
![image](https://user-images.githubusercontent.com/90846/146130645-dc7c948c-2e6c-4ca6-a16c-2ba5d3e1f089.png)

Code to reproduce: 
```python
import time
import torch
import torch.nn as nn
from torch.profiler import tensorboard_trace_handler


class TestNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc_in = nn.Linear(3, 128)
        self.layers = nn.ModuleList()
        for i in range(0, 10):
            self.layers.append(nn.Linear(128, 128))
            self.layers.append(nn.LayerNorm(128))
        self.fc_out = nn.Linear(128, 3)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.fc_in(x)
        for layer in self.layers:
            x = layer(x)
        x = self.fc_out(x)
        return x


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
net = TestNet().to(device).train()
in_data = torch.zeros([1, 1024 * 1024, 3]).to(device)
criterion = nn.MSELoss().to(device)
optimizer = torch.optim.SGD(net.parameters(), 0.01)

with torch.profiler.profile(
        schedule=torch.profiler.schedule(wait=2, warmup=2, active=6, repeat=1, skip_first=2),
        on_trace_ready=tensorboard_trace_handler("tmp/profile"),
        with_stack=True, with_flops=True, with_modules=True) as profiler:
    t0 = time.time()
    for i in range(0, 20):
        print(f"step: {i:,d} {time.time() - t0:.3f}")
        out_data = net(in_data)
        loss = criterion(out_data, in_data)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        profiler.step()
print("Done! ")
```

Please make `LayerNorm` performant on this type of input, thanks! 

### Versions

I'm using the pytorch docker image: `pytorch/pytorch             1.10.0-cuda11.3-cudnn8-runtime   c3f17e5ac010   7 weeks ago     6.26GB` with a handful of additional pip packages installed. 

The output from `collect_env.py`: 
```
# python collect_env.py
Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: NVIDIA A100-SXM-80GB
GPU 1: NVIDIA A100-SXM-80GB
GPU 2: NVIDIA A100-SXM-80GB
GPU 3: NVIDIA A100-SXM-80GB
GPU 4: NVIDIA A100-SXM-80GB
GPU 5: NVIDIA A100-SXM-80GB
GPU 6: NVIDIA A100-SXM-80GB
GPU 7: NVIDIA A100-SXM-80GB

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchelastic==0.2.0
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.2           py37h20f2e39_0
[conda] numpy-base                1.21.2           py37h79a1101_0
[conda] pytorch                   1.10.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchelastic              0.2.0                    pypi_0    pypi
[conda] torchtext                 0.11.0                     py37    pytorch
[conda] torchvision               0.11.0               py37_cu113    pytorch
```

**Comment by jxtps** [comment]
Reshaping the input to `in_data = torch.zeros([1024, 1024, 3]).to(device)` does not make a difference, so this seems to apply to any large input to LayerNorm.

**Comment by jxtps** [comment]
The forward pass does seem to have full SM occupancy, but it's still surprisingly slow compared to doing a matrix multiplication?! (i.e. the fully connected layers)

**Comment by jxtps** [comment]
Hopefully this performance issue has already been addressed by @ngimel in e.g. https://github.com/pytorch/pytorch/pull/68238 and https://github.com/pytorch/pytorch/pull/67977 as those changes were made since the 1.10.0 release I'm using.

**Comment by jxtps** [comment]
The most recent docker image was pushed 2 months ago as of this writing ( https://hub.docker.com/r/pytorch/pytorch/tags ), so I guess I'll have to wait with testing the new code. Closing this in the meantime.

**Comment by ngimel** [comment]
Unfortunately even with those PRs feature size of 128 that you have will still be pretty slow (typical feature size for LayerNorm is 1024)
