### ISSUE TITLE
distributed linear algebra solutions

### ISSUE THREAD

**Issue by amirhajibabaei** [pytorch/pytorch#69971]
### 🚀 The feature, motivation and pitch

It would be great if some of linear algebra operations can be done in parallel using the `distributed` module.
I am in particular interested in least squares `lstsq`, but I suppose the argument applies to many `linalg` ops as well.
```
torch.linalg.lstsq -> torch.distributed.linalg.lstsq
torch.linalg.* -> torch.distributed.linalg.*
```
In many large scale applications pieces of a matrix are built on different processes in a distributed environment.
Currently, if I am not wrong, these pieces should be gathered in a single process and solved (with 1 process).
But, first, all of the processes can contribute on solving the problem.
And second, although some communication is still needed, it may eliminate the need to send pieces of matrix between processes.

I suppose there are two ways to approach this:
1) use SCALAPACK which implements more or less the same existing algorithms in parallel
2) algorithms which are specifically designed for the distributed setup: e.g. arXiv:1709.10157

This is in particular highly desired in HPC setup with massive parallelism in the field of computational physics and chemistry.

### Alternatives

SCALAPCK

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by pritamdamania87** [comment]
@amirhajibabaei Thanks for creating this issue! We are working on a ShardedTensor primitive in PyTorch and have some prototypes supporting things like sharded linear and embedding layers. We believe this can be extended to support linear algebra operations as well.

Do you have some examples in terms of typically how matrices A and B (for lstsq) are partitioned across multiple devices? Today we support operations only when Tensors are partitioned along a single dimension and was wondering if that suffices for your use cases as well?

**Comment by amirhajibabaei** [comment]
@pritamdamania87 Thanks for the great news. That is exactly what I need and, I believe, majority of the problems can be solved by distributing the matrix along one dimension.

In my case, I have local matrices A[n_i, m], B[n_i] on process i and the global matrices (A[N, m], B[N]) are defined as concatenation of the local matrices along dim=0 (N = sum_i n_i). The solution X[m] (after `X = lstsq(A, B)`) should be the same on all processes.
In general n_i is different on each process i, but restricting the local matrices to have the same size can also work (padding with zeros, etc.).

**Comment by fduwjj** [comment]
Hi, @amirhajibabaei sorry for getting back to you a little bit late. As mentioned by @pritamdamania87, what you mentioned here can be covered by the sharded tensor we built. After this PR, https://github.com/pytorch/pytorch/pull/70079, you can even reshard a sharded tensor to other dimensions. We will keep you posted about our plan to support more ops down the road. Thanks!
