### ISSUE TITLE
fx graph mode quant - torch.sort after quantization not scriptable

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#69977]
### 🐛 Describe the bug

quantizing a model with torch.sort and then scripting the model does not work as expected. Repro:

```
print(torch.__version__)

class M(torch.nn.Module):
    def forward(self, x):
        x = torch.sort(x)
        return x

m = M().eval()
mp = torch.quantization.quantize_fx.prepare_fx(m, {'': torch.quantization.default_qconfig})
mq = torch.quantization.quantize_fx.convert_fx(mp)
mqs = torch.jit.script(mq) # this line fails
```

> 'Tuple[Tensor, Tensor]' object has no attribute or method 'dequantize'.:
  File "<eval_with_key>.7182", line 9
    quantize_per_tensor = torch.quantize_per_tensor(x, _input_scale_0, _input_zero_point_0, torch.quint8);  x = _input_scale_0 = _input_zero_point_0 = None
    sort = torch.sort(quantize_per_tensor);  quantize_per_tensor = None
    dequantize = sort.dequantize();  sort = None
                 ~~~~~~~~~~~~~~~ <--- HERE
    return dequantize

### Versions

1.11.0a0+fb

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
same thing happens with `torch.numel`

**Comment by jerryzh168** [comment]
I guess we should remove quantization for these things, I feel these are probably not used. It's added initially because the TorchScript graph mode quantization also has them I think

**Comment by jerryzh168** [comment]
this should be fixed now
