### ISSUE TITLE
Stop compiling master_worker THD

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#6999]
According to @apaszke we shouldn't be building it.

CC @lantiga, maybe?

**Comment by lantiga** [comment]
@ezyang I wasn't notified of the mention for some reason.
Yes, once the IR export / import PR goes in, the intention was to start looking into master-worker. I'm currently working on something conceptually related (a GRPC remote tensor runtime that can load serialized IR's) so it makes sense to get into master-worker as well. With my pace, as usual ;-)

**Comment by lantiga** [comment]
And BTW, regarding this issue: stopping compiling master_worker THD won't have an effect on `libtorch`, so all clear for me.

**Comment by ezyang** [comment]
@lantiga, cool, thanks for the note. If you end up rewriting it all from scratch, if you could also delete the dead `master_worker` THD code that would be great; if you reuse it, no deleting necessary :)
