### ISSUE TITLE
Multigpu test configs intermittently timeout

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#70015]
### 🐛 Describe the bug

From https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=multigpu
For example see
https://github.com/pytorch/pytorch/runs/4491157342?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4494906997?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4515348059?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4516653541?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4520760224?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4524464202?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4524930515?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4526311049?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4526553164?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4526686943?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/4538152008?check_suite_focus=true

### Versions

Irrelevant

cc @ezyang @gchanan @zou3519 @bdhirsh @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Looks like no reaction here, it still affects people, I'm going to disable those

**Comment by ngimel** [comment]
It's weird, the tests that run run pretty quickly, in couple minutes, and then nothing happens for 4 hours until timeout.

**Comment by suo** [comment]
cc @rohan-varma as well

**Comment by suo** [comment]
@malfet shall we disable the cpp tests, at least to see if it stops the hangs?

**Comment by suo** [comment]
https://github.com/pytorch/pytorch/pull/71015

**Comment by huydhn** [comment]
Closing this as this is not relevant anymore.
