### ISSUE TITLE
[rocm] Memory Exception on virtual address

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#70027]
### 🐛 Describe the bug

```
01:57:20   test_fn_fwgrad_bwgrad_gradient_cuda_complex128 (__main__.TestGradientsCUDA) ... Memory exception on virtual address 0x7f60f5d77000, node id 2 : Page not present
01:57:21 Address does not belong to a known buffer
01:57:21 Memory access fault by GPU node-2 (Agent handle: 0x5603f3f007f0) on address 0x7f60f5d77000. Reason: Page not present or supervisor privilege.
01:57:21 Traceback (most recent call last):
01:57:21   File "test/run_test.py", line 1068, in <module>
01:57:21     main()
01:57:21   File "test/run_test.py", line 1046, in main
01:57:21     raise RuntimeError(err_message)
01:57:21 RuntimeError: test_ops failed! Received signal: SIGIOT
```

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test2/14900/console

### Versions

ROCm CI

cc @ezyang @gchanan @zou3519 @bdhirsh @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @mruberry

**Comment by KyleCZH** [comment]
file a PR to skip this test for ROCm
https://github.com/pytorch/pytorch/pull/70061

**Comment by jeffdaily** [comment]
These tests are marked as expected failure for cuda.  But rocm produces a mem access fault instead of raising the error about finding more than one device.

**Comment by anjali411** [comment]
fixed in https://github.com/pytorch/pytorch/pull/71611
