### ISSUE TITLE
Pytorch profiler presents negative memory allocations

### ISSUE THREAD

**Issue by dvirginz** [pytorch/pytorch#70028]
### 🐛 Describe the bug

Using the PyTorch profiler to understand the memory allocation of a specific call, it seems as there are negative memory allocations.

Given the following snippet based on the official [tutorial](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html) :
```
from train_shape_corr import create_model
from torch.profiler import profile, record_function, ProfilerActivity
import torch
from pathlib import Path
def trace_handler(p):
    output = p.key_averages().table(sort_by="self_cuda_time_total", row_limit=10)
    print(output)
    p.export_chrome_trace("output/tmp/trace_" + str(p.step_num) + ".json")

def evaluate_test_runtime():
    model = main(RUN=False)
    model.cuda()
    with profile(
        activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA],profile_memory=True,
        schedule=torch.profiler.schedule(
            wait=1,
            warmup=1,
            active=2),
        on_trace_ready=trace_handler
    ) as p:
        for path in Path('data/cocked').rglob('*'):
            data = torch.load(str(path))
            model.inner_forward(data)
            p.step()

evaluate_test_runtime()
```
I receive the following analysis:
```
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                                   Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg     Self CUDA   Self CUDA %    CUDA total  CUDA time avg       CPU Mem  Self CPU Mem      CUDA Mem  Self CUDA Mem    # of Calls  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
                                 _SidedDistanceFunction         0.03%     262.000us         0.06%     637.000us     106.167us     418.732ms        59.85%     427.038ms      71.173ms           0 b           0 b       2.24 Gb      -2.24 Gb             6  
void kaolin::sided_distance_forward_cuda_kernel<floa...         0.00%       0.000us         0.00%       0.000us       0.000us     418.732ms        59.85%     418.732ms      69.789ms           0 b           0 b           0 b           0 b             6  
                                      aten::_svd_helper         4.39%      44.660ms        17.33%     176.196ms      88.098ms     130.063ms        18.59%     130.155ms      65.078ms           0 b    -781.25 Kb      16.02 Mb      -7.63 Mb             2  
void batched_svd_parallel_jacobi_32x16<float, float>...         0.00%       0.000us         0.00%       0.000us       0.000us     130.055ms        18.59%     130.055ms      65.028ms           0 b           0 b           0 b           0 b             2  
                                              aten::bmm         0.29%       2.955ms         0.65%       6.649ms      24.445us      83.605ms        11.95%      83.605ms     307.371us           0 b           0 b       4.85 Gb           0 b           272  
void batch_gemm_kernel1x1_core<float, float, float, ...         0.00%       0.000us         0.00%       0.000us       0.000us      39.588ms         5.66%      39.588ms       9.897ms           0 b           0 b           0 b           0 b             4  
void batch_gemm_kernel1x1_core<float, float, float, ...         0.00%       0.000us         0.00%       0.000us       0.000us      38.190ms         5.46%      38.190ms       9.547ms           0 b           0 b           0 b           0 b             4  
void at::native::unrolled_elementwise_kernel<at::nat...         0.00%       0.000us         0.00%       0.000us       0.000us      15.728ms         2.25%      15.728ms      35.265us           0 b           0 b           0 b           0 b           446  
                                aten::native_layer_norm         0.14%       1.401ms         0.48%       4.876ms      46.885us      14.311ms         2.05%      14.311ms     137.606us           0 b           0 b     250.38 Mb           0 b           104  
void at::native::(anonymous namespace)::RowwiseMomen...         0.00%       0.000us         0.00%       0.000us       0.000us      12.862ms         1.84%      12.862ms     123.673us           0 b           0 b           0 b           0 b           104  
-------------------------------------------------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
```
As you can see, `Self CUDA mem` shows `-2.24Gb`.

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-64-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce GT 1030

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.5
[pip3] torch==1.10.0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.2
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.10.0
[pip3] torchmetrics==0.6.1
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.21.2           py37h20f2e39_0  
[conda] numpy-base                1.21.2           py37h79a1101_0  
[conda] pyg                       2.0.2           py37_torch_1.10.0_cu102    pyg
[conda] pytorch                   1.10.0          py3.7_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-cluster           1.5.9           py37_torch_1.10.0_cu102    pyg
[conda] pytorch-lightning         1.5.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.0.9           py37_torch_1.10.0_cu102    pyg
[conda] pytorch-sparse            0.6.12          py37_torch_1.10.0_cu102    pyg
[conda] pytorch-spline-conv       1.2.1           py37_torch_1.10.0_cu102    pyg
[conda] torchaudio                0.10.0               py37_cu102    pytorch
[conda] torchmetrics              0.6.1                    pypi_0    pypi
[conda] torchvision               0.11.1               py37_cu102    pytorch

cc @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by ilia-cher** [comment]
Negative numbers in the output represent the freed memory.

**Comment by adityakillekar** [comment]
@ilia-cher torch profiler is showing -38.50Gb for record_function() block, while my GPU is 24Gb. Doesn't makes sense to me releasing more memory than available. Can you please shed some more light on "Self CUDA Mem" interpretation?

**Comment by robieta** [comment]
> @ilia-cher torch profiler is showing -38.50Gb for record_function() block, while my GPU is 24Gb. Doesn't makes sense to me releasing more memory than available. Can you please shed some more light on "Self CUDA Mem" interpretation?

Unfortunately the profiler doesn't currently have any way to reason about "net" memory usage. So if I allocate X in op A and release it in op B and I run that 1000 times in a loop you will see 1000X under A and -1000X under B. Which, I admit, is not particularly intuitive.

**Comment by sanyanliangyu** [comment]
u are all make mistake. 
let me show the  code of torch 

def self_cuda_memory_usage(self):
        if self.is_async or self.device_type != DeviceType.CPU:
            return 0
        return self.cuda_memory_usage - sum(
            [child.cuda_memory_usage for child in self.cpu_children]
        )

u can see this. so if u get negative memory,must be something wrong happend with this function. 

through reading code, i find this function can't compute this mem of cuda using.  because  child thread and parent thread have common memory, when u compute self_negative memory， mem will be recalculated repeatedly， so that u get negative mem

**Comment by orionr** [comment]
@adnanaziz @aaronenyeshi can you maybe take a look at this one? Thanks

**Comment by aaronenyeshi** [comment]
It seems this issue is resolved. We can have more memory freed than the max memory, because we can repeatedly allocate and free memory.

**Comment by HaFred** [comment]
> > @ilia-cher torch profiler is showing -38.50Gb for record_function() block, while my GPU is 24Gb. Doesn't makes sense to me releasing more memory than available. Can you please shed some more light on "Self CUDA Mem" interpretation?
> 
> Unfortunately the profiler doesn't currently have any way to reason about "net" memory usage. So if I allocate X in op A and release it in op B and I run that 1000 times in a loop you will see 1000X under A and -1000X under B. Which, I admit, is not particularly intuitive.

Hi @robieta sorry to bother. May I double check is the unit here gigabytes or gigabits? `Gb` looks confusing and gigabits normally not represented as `Gb`... Thank you!
