### ISSUE TITLE
Could we leave the _two_ most recent nightlies in the conda channel?

### ISSUE THREAD

**Issue by lw** [pytorch/pytorch#70045]
### 🚀 The feature, motivation and pitch

I'm building and distributing a PyTorch extension that requires the nightly version of PyTorch (because it needs fixes that are only in master). Since PyTorch doesn't guarantee ABI compatibility I need to rebuild the extension for each new nightly release, so I did set up a cron job that does that and publishes the package on conda. Each of these packages has a "pinned" dependency on the exact PyTorch version it was built against.

The fact that PyTorch deletes all old nightly binaries whenever it uploads a new one is creating issues to me, because it means users won't be able to install my extension until the time when I build a new version. (Because they can either find the old version of my extension but not of PyTorch, or the new version of PyTorch but not of my extension). I can increase the frequency of my cron job to mitigate this, but there will always inevitably be a gap.

It would be much easier if PyTorch kept the last _two_ versions of the package around, so that until I rebuild my extension for the new nightly my users can still obtain the old nightly of PyTorch.

cc @ezyang @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by lw** [comment]
I fear that perhaps the problem isn't clear, so here's a more detailed explanation.

Timeline:
1. PyTorch releases a new nightly, `pytorch-1.11.0.dev20211216`
2. My CI builds a new package against that nightly, `myext-0.1.dev20211216`, which depends on `pytorch-1.11.0.dev20211216`
3. PyTorch releases the next nightly, `pytorch-1.11.0.dev20211217`, and _removes the old one_!
4. I build a new package against the new nightly, `myext-0.1.dev20211217`

The issue is that in between 3 and 4 people can't install my extension, because the only package they can find is `20211216` (since I haven't yet built the new one), but it depends on PyTorch `20211216` which they cannot find anymore!

**Comment by malfet** [comment]
I think this is a side effect of the total channel size constraint(which I believe is 3Gb) and enormous size of our torch binaries. 
We can (and perhaps we are) totally backup conda nightlies to S3 bucket so that one can download and install them manually.

But I wonder if solution for your particular problem would be to copy nightly version your depend upon into your own channel

**Comment by ezyang** [comment]
I hope we're backing up conda nightlies to s3...

**Comment by lw** [comment]
BTW now that the 1.11 RC binaries are out I'm not directly affected by this anymore.

**Comment by ZainRizvi** [comment]
Closing since the requester no longer needs this feature
