### ISSUE TITLE
Nightly PyTorch is not updated the latest master branch previous day code

### ISSUE THREAD

**Issue by hwangdeyu** [pytorch/pytorch#70096]
### 🐛 Describe the bug

I use the PyTorch nightly to catch [a PR featrue](https://github.com/pytorch/pytorch/commit/c76c6e9bd345ba697ea2a6fb8c2e24f051bb2e00) 2 days ago. And install it by pip command:
```
pip install --pre torch==1.11.0.dev20211216+cu111 torchvision==0.12.0.dev20211216+cu111 -f 

https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
```
However, It looks like that PR function is not into the latest nightly code.

So I checked the [`nightly` branch](https://github.com/pytorch/pytorch/commits/nightly) in PyTorch repo. In the last 3 days, the nightly code was not updated new code any more, and the latest PR is from 4 days ago. 
I guess the nightly code should update the latest master code everyday. So is it an expectation result? 

![image](https://user-images.githubusercontent.com/10047193/146506481-8a7e444a-2583-4e0d-81a8-37e1cf26b939.png)

### Versions

```
pip install --pre torch==1.11.0.dev20211216+cu111 torchvision==0.12.0.dev20211216+cu111 -f 

https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
```

cc @ezyang @gchanan @zou3519 @bdhirsh @malfet @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Hmm, https://github.com/pytorch/pytorch/tree/viable/strict looks pretty recent

**Comment by hwangdeyu** [comment]
> 

Yeah, the 2021-12-17 nightly release is ok. Thanks.
