### ISSUE TITLE
ci: sev:  use $(MAKE) instead of make -j in CMake Exterproject

### ISSUE THREAD

**Issue by mlh0101** [pytorch/pytorch#70091]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.
![image](https://user-images.githubusercontent.com/10190565/146498686-1dba08d5-915c-46fc-82b9-d1c9cda98f87.png)

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
if MAX_JOBS is not defined, the project maybe run like make -j with full resource of the build env. sometimes, it will broke the build procedure.

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

## User impact
*How does this affect users of PyTorch CI?*
None

## Root cause
*What was the root cause of this issue?*
the external project didn't use the Concurrency mechanism of make。

## Mitigation
*How did we mitigate the issue?*
I will send a PR for this issue.

## Prevention/followups
*How do we prevent issues like this in the future?*
use $(MAKE) instead of make -j in CMake Exterproject

cc @malfet @seemethere

**Comment by malfet** [comment]
What makes you think it is a CI service violation? Let's continue discussing the PR, but going to close the issue it has nothing to do with the SEV pattern
