### ISSUE TITLE
[Minor Bug] Pylint E1101 Module 'torch' has no 'from_numpy' member

### ISSUE THREAD

**Issue by willfrey** [pytorch/pytorch#701]
Very minor but worth mentioning.

Pylint isn't picking up that `torch` has the member function `from_numpy`. It's because `torch.from_numpy` is actually `torch._C.from_numpy` as far as Pylint is concerned.

According to [this stackoverflow thread](http://stackoverflow.com/questions/20553551/how-do-i-get-pylint-to-recognize-numpy-members) `numpy` also suffers from this problem.

For reference, you can have Pylint ignore these by wrapping "problematic" calls with the following comments.

```python
# pylint: disable=E1101
tensor = torch.from_numpy(np_array)
# pylint: enable=E1101
```

**Comment by soumith** [comment]
the workaround seems pretty ugly. is there no way to tell pylint to filter certain errors?

**Comment by naifrec** [comment]
I may add that pylint (1.6.5) does not pick up `cat`, `topk` and  `masked_select` as member functions either.

**Comment by soumith** [comment]
i dont think we'll be fixing this. (i dont know if there's a way to do it either).

**Comment by kindlychung** [comment]
mypy seems to be able to pick up these members.

**Comment by neverfox** [comment]
Instead of ignoring, you can now do:
```
[TYPECHECK]

# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E1101 when accessed. Python regular
# expressions are accepted.
generated-members=numpy.*,torch.*
```

**Comment by dscarmo** [comment]
> generated-members=numpy.*,torch.*

For those using vscode, add to user settings

"python.linting.pylintArgs": [
        "--errors-only",
        "--generated-members=numpy.*,torch.*,cv2.*, cv.*"
    ]

errors-only is not realted to the issue but is useful to supres pep 8/formatting "errors" if you want to

**Comment by moi90** [comment]
It would be nice to allow the inspection of the module, also for auto-completion. Maybe one could change `from torch._C import *` to `from torch._C import from_numpy, ...`?

**Comment by cardoso-neto** [comment]
> Maybe one could change `from torch._C import *` to `from torch._C import from_numpy, ...`?
This seems simple enough. Are we certain this is the way to go? 
I thought we'd need type hints (which would be way harder to convince people to use).
Should we open another issue to discuss it @moi90's solution?

**Comment by Immocat** [comment]
> > generated-members=numpy._,torch._
> 
> For those using vscode, add to user settings
> 
> "python.linting.pylintArgs": [
> "--errors-only",
> "--generated-members=numpy.* ,torch.* ,cv2.* , cv.*"
> ]
> 
> errors-only is not realted to the issue but is useful to supres pep 8/formatting "errors" if you want to

You saved part of my life! hahahaha

**Comment by miranthajayatilake** [comment]
On VS code: 
Adding `"python.linting.enabled": false` also worked in this case.

**Comment by SelvamArul** [comment]
Disabling linting all together (as suggested by @miranthajayatilake ) is not a good solution. Seems  `pylint`has issues with pytorch but for me `flake8` works well. 
In VS Code, one can select `flake8` by `Ctrl + Shift + P` ->` Select linter` -> `flake8`.

**Comment by zzj0402** [comment]
> i dont think we'll be fixing this. (i dont know if there's a way to do it either).

Closing issues by "I don't know how to hence not going to" is very naughty.

**Comment by xasopheno** [comment]
> > generated-members=numpy._,torch._
> 
> For those using vscode, add to user settings
> 
> "python.linting.pylintArgs": [
> "--errors-only",
> "--generated-members=numpy.* ,torch.* ,cv2.* , cv.*"
> ]
> 
> errors-only is not realted to the issue but is useful to supres pep 8/formatting "errors" if you want to

If you're using Coc, you can use put the same rule in your coc-settings.json.

**Comment by yangfansun** [comment]
maybe "python.linting.pylintArgs": ["--generate-members"] will solve the problem.
https://stackoverflow.com/questions/56844378/pylint-no-member-issue-but-code-still-works-vscode

**Comment by maejav** [comment]
i got this error for torch.randn!!
what sould i do ? i can not fix it with these solutions.

**Comment by nguyenvulong** [comment]
You don't have to disable `pylint`, just add 1 line to the `settings.json`. 
See https://github.com/nguyenvulong/QA/issues/63 for more references.


<img src="https://github.com/nguyenvulong/QA/assets/1311412/0c71d6d1-c6c8-480a-bb36-e761516f2226" height=100>

**Comment by vindolineKis** [comment]
I met this problem ：
 “Module 'torch' has no 'matmul' member “ [{
	"resource": "/home/guoguo/project1/quantum_transformer/qtransformer/qtransformer.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "E1101:no-member",
		"target": {
			"$mid": 1,
			"path": "/en/latest/user_guide/messages/error/no-member.html",
			"scheme": "https",
			"authority": "pylint.readthedocs.io"
		}
	},
	"severity": 8,
	"message": "Module 'torch' has no 'matmul' member",
	"source": "Pylint",
	"startLineNumber": 57,
	"startColumn": 18,
	"endLineNumber": 57,
	"endColumn": 30
}]，  I have followed the above ways to add "python. linting.pylintArgs": ["--generate-members"]， but it didn't solve my problem

**Comment by BraveDrXuTF** [comment]
> "python.linting.pylintArgs": [
> "--errors-only",
> "--generated-members=numpy.* ,torch.* ,cv2.* , cv.*"
> ]
bro, now it seems not work. I got the problem one morning when typing code with vs code recently.

**Comment by liye-yang** [comment]
> > "python.linting.pylintArgs": [
> > "--errors-only",
> > "--generated-members=numpy.* ,torch.* ,cv2.* , cv.*"
> > ]
> > bro, now it seems not work. I got the problem one morning when typing code with vs code recently.

this way seems work: 
`"pylint.args": [
    "--generated-members=numpy.*, torch.*, cv2.*, cv.*"
]`
