### ISSUE TITLE
`FileLister` output should be sorted for distributed mode

### ISSUE THREAD

**Issue by bryant1410** [pytorch/pytorch#70103]
### 🐛 Describe the bug

`FileLister` (`FileListerIterDataPipe`) output is based on `get_file_pathnames_from_root`, which in turn uses `os.walk` which doesn't guarantee the output order. Then, when used in distributed mode, because of `DistributedSampler`, different processes from different machines may get a different order, and then select arbitrary data, not satisfying that each data sample is selected once and only once across processes.

I think it should sort by default, and maybe not sort if a flag is passed.

Note that it could be sorted by the caller. However, this is error-prone and people may forget by default that this is an issue, and it's a main use case.

### Versions

`master` branch.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Makes sense to me. Feel free to open an PR and our team can review it.

**Comment by ejguan** [comment]
And, just a heads-up, the sampler may not be used for IterDataPipe in the future. But, it would be definitely useful to have a deterministic order of files.
