### ISSUE TITLE
test_multi_keep intermittently hangs in ASAN

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#7011]
[Here](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-py3-clang5-asan-test/3268/console) is an example of a test timing out because of test_multi_keep as part of [this PR](https://github.com/pytorch/pytorch/pull/6119). This is the only test that fails on this PR. I'm going to skip the test for now.

**Comment by yf225** [comment]
I suspect that it’s caused by a recent change because this issue didn’t happen before. I’ll take a look at it.
