### ISSUE TITLE
[feature request] [pytorch] Support inline cpp/cuda JIT extensions

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#7012]
If I understand correctly, currently the JIT variant requires the C++/CUDA files to live on disk. It would be cool to support compiling C++/CUDA code from a string variable from a python variable, like in nvrtc/cupy: https://github.com/vadimkantorov/caffemodel2pytorch (ROI pooling example).

This would reduce boiler-plate files and improve code clarity for small CUDA functions.

**Comment by apaszke** [comment]
That should be really easy to do by wrapping the JIT wariant. wdyt @goldsborough?

**Comment by vadimkantorov** [comment]
from cupy usage I remember that specifying headers had to be via a special method argument to please nvrtc

if there is only a cuda function, will the gcc compiler still be called? (i remember in discussion there was something that cpp extensions must be compiled with the same version of gcc as the pytorch itself which can be problematic if pytorch is installed as a pre-built package)

**Comment by goldsborough** [comment]
We don't use nvrtc, we use gcc for C++ files and nvcc for CUDA files. To be clear, the way I would implement this features is by dumping the inline function into a file and then calling `cpp_extension.load()` on it :)

**Comment by vadimkantorov** [comment]
IIUC now nvrtc is used by PyTorch directly, so maybe this functionality could be simplified

**Comment by ezyang** [comment]
nvrtc isn't going to work for non-CUDA bits though, right?

**Comment by vadimkantorov** [comment]
Probably. But for quick-n-dirty accelarated CUDA code as in https://github.com/NVIDIA/FastPhotoStyle/blob/master/smooth_filter.py it would be enough
