### ISSUE TITLE
docs for eval should be updated.

### ISSUE THREAD

**Issue by crazyoscarchang** [pytorch/pytorch#7013]
in pytorch 0.4.0, running model.eval() will still allow autograd to backprop the weights.
the docs should be updated to reflect what it's doing.

**Comment by SsnL** [comment]
Can you clarify what you mean? `eval` always allows backprop.

**Comment by crazyoscarchang** [comment]
i was under the impression that before 0.4.0, after doing eval, it's like passing in a volatile tensor. autograd doesn't update the .grad.

**Comment by SsnL** [comment]
`eval` always allows backprop. It just changes the behavior of some layers.
