### ISSUE TITLE
multinomial with inf fails in cuda

### ISSUE THREAD

**Issue by kylemcdonald** [pytorch/pytorch#7014]
`torch.multinomial` throws a `RuntimeError` if the probability distribution includes `float('inf')`. On CPU there is no similar problem. This can happen if you take a (what is probably naive) approach to sampling logits like this:

```python
def sample_temp(logits, temperature):
    probs = torch.exp(logits / temperature)
    return torch.multinomial(probs, 1)
```

It's more likely to cause a problem if your logits are very large or your temperature is very small.

## Code example

```python
import torch
x = torch.Tensor([0, float('inf')])
print(torch.multinomial(x, 1))
print(torch.multinomial(x.to('cuda'), 1))
```

```python-traceback
tensor([ 1])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-98dbbe29edf5> in <module>()
      2 x = torch.Tensor([0, float('inf')])
      3 print(torch.multinomial(x, 1))
----> 4 print(torch.multinomial(x.to('cuda'), 1))

RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1524590031827/work/aten/src/THC/generic/THCTensorCopy.c:20
```

## System Info

```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.1/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda80                    1.0                           0    soumith
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```

## Back story

It may look simple, but this was a particularly difficult bug to track down :) I moved my RNN sampling from CPU (with numpy) to GPU (with torch) and started getting errors like:

* `RuntimeError: CUDNN_STATUS_EXECUTION_FAILED`
* `RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1524590031827/work/aten/src/THC/generic/THCTensorCopy.c:20`
* `RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1524590031827/work/aten/src/THC/generated/../THCReduceAll.cuh:339`

I saw https://github.com/pytorch/pytorch/issues/5213 and https://github.com/pytorch/pytorch/issues/6306 had a similar error, which made me think it was related to my sampling code not moving data around correctly, but this didn't explain the intermittent behavior. I audited that and continued searching. Then I saw https://github.com/pytorch/pytorch/issues/5561 which made me check that my embedding indices were being set correctly (not out of bounds). So I looked closer into multinomial and found this bug.

One way to get around the sampling bug above is to just do everything on the CPU. Another solution is to use Gumbel-softmax style sampling:

```python
def sample(logits, temperature=1.0):
    if temperature == 0:
        return torch.argmax(logits, dim=-1)
    noise = torch.FloatTensor(logits.shape).to(logits.device)
    noise.uniform_(1e-5, 1-1e-5)
    return torch.argmax(logits / temperature - torch.log(-torch.log(noise)), dim=-1)
```

But unfortunately this takes longer to execute than the first round of sampling code.

**Comment by apaszke** [comment]
I actually think that the CUDA behavior is reasonable, we should raise an error in the CPU case as well. You can't have a probability distribution where one of the elements has an infinite probability, so there's nothing we can do. What would you expect to happen in that case?

Sorry for the long debugging, unfortunately getting meaningful errors from CUDA kernels is a bit hard. In the future you might want to use `CUDA_LAUNCH_BLOCKING=1` which should report the error in the same operation that caused it.

**Comment by t-vi** [comment]
So the bug here is the CPU non-failure or the CUDA failure?

**Comment by t-vi** [comment]
I guess one could sample from those elements that have `inf` with equal probability - but it is dodgy mathematically and you wouldn't have gradients, so you really are in a degenerate state. As we return integers, returning NaN isn't an option, unfortunately...

**Comment by apaszke** [comment]
The problem is that the semantics of `multinomial` is that it takes an unnormalized vector, and as such it should normalize it to a probability distribution and sample from that. Since our normalization algorithm is simply `/ sum(values)`, it doesn't work with infinite elements (unlike e.g. `softmax`).

**Comment by kylemcdonald** [comment]
as a user, some solutions that would make me really happy:

- an exception from both CPU and GPU saying that infinity is unsupported is multinomial. tracking down the `CUDNN_STATUS_EXECUTION_FAILED` back to multinomial was actually really difficult (as a beginner).
- just a warning, but followed by the same behavior as the CPU.
- add a `logits` parameter to multinomial allowing people to use logits rather than probabilities, making it less likely that people will run into this problem.

**Comment by apaszke** [comment]
Thanks @kylemcdonald. I think the actionable items here would be:
* Start throwing exceptions on CPU when we see `inf` values (not sure what's the behavior now).
* Perhaps improve the `device-side assert triggered` message to suggest people to run their code with `CUDA_LAUNCH_BLOCKING=1`.

I'm not exactly sure what do you mean by `logits` here. `multinomial` already accepts unnormalized vectors (that are not probability distributions), and will normalize them as part of the process. It's just that the normalization procedure doesn't work with infinite values.

**Comment by kylemcdonald** [comment]
`CUDA_LAUNCH_BLOCKING=1` doesn't actually change the error in this case. I get the same obscure error message whether I run with or without that flag.

By `logits` I mean the same kind of parameter that is passed into any of the https://pytorch.org/docs/master/distributions.html objects. I'm not great with probabilities, but I'm pretty sure sampling from log probabilities normalized by the sum of their values is not the same as sampling after normalizing after taking the `exp` of their values, and that's why all the `distribution` objects offer both? The logits aren't infinities until they are `exp`'d so I can imagine an implementation that goes like:

```
def multinomial(probs=None, logits=None, temperature=None):
    if probs:
        logits = torch.log(probs)
    if temperature:
        logits /= temperature
    logits = torch.min(logits, torch.Tensor([40.]))
    probs = torch.exp(logits)
    return torch.multinomial(probs, 1)
```

`40.` being near the point where `exp` starts to create infinity. But I would hope someone with more experience than me has a solution to this conundrum :)

**Comment by t-vi** [comment]
Using `CUDA_LAUNCH_BLOCKING=1` won't change the error message, but it removes the asynchronous behaviour that keeps you from seeing the place where it happens.
I think the `min` is probably a good solution in your specific case, but it might be more idiomatic to use  `probs = logits.clamp(max=40.).exp()`.

**Comment by kylemcdonald** [comment]
Thank you @t-vi. I didn't make the connection that a log probability distribution is equivalent to another that has been shifted by a constant amount (because shifting/addition of log probabilities is equivalent to multiplication of regular probabilities, and is therefore removed by the normalization step).

With that in mind, I think I have been able to define a more direct way of computing `multinomial` with a temperature, on probabilities or log probabilities, with no chance of getting NaN/infinities/crashes.

```python
def multinomial(probs=None, logits=None, temperature=1, num_samples=1,
                     min_prob=1e-20, max_logit=1e+20,
                     min_temperature=1e-20, max_temperature=1e+20):
    if probs is not None:
        probs = probs.clamp(min=min_prob)
        logits = torch.log(probs)
    logits = logits.clamp(max=max_logit)
    temperature = np.clip(temperature, min_temperature, max_temperature)
    logits = (logits - logits.max()) / temperature
    probs = torch.exp(logits)
    return torch.multinomial(probs, num_samples)
```

Here are the cases I tested with. Obviously many of these are undefined, but none of them crash or return NaNs:

```python
test_cases = [
    [0,0,0],
    [1,1,1],
    [1,0,float('+inf')],
    [1,0,float('-inf')],
    [1,0,1e+20],
    [1,0,1e-20],
    [1,0,-1e+20],
    [1,0,-1e-20]
]

for temperature in [float('-inf'), 0, 1e-20, 1, 1e+20, float('+inf')]: 
    for test_case in test_cases:
        for device in ['cpu', 'cuda']:
            x = torch.Tensor(test_case)
            print(multinomial(probs=x.to(device), temperature=temperature))
            print(multinomial(logits=x.to(device), temperature=temperature))
```

**Comment by cle-ros** [comment]
Hi,
I'm not sure how much code `torch.multinomial` and `torch.distributions.categorical.Categorical` share, but `torch.distributions.categorical.Categorical` behaves the same way. 

In addition, the same behavior occurs for negative values. While the docs for `torch.multinomial` state that `probs` should all be positive, the docs for `torch.distributions.categorical.Categorical` do not. They even state that "probs will be normalized to be summing to 1.", which suggests that negative values are possible.

Here's a mwe:

```python
# for inf values
probs = torch.cuda.FloatTensor([np.inf, 0.5, 0.5])
dist = torch.distributions.categorical.Categorical(probs)
[...] cuda runtime error (59) : device-side assert triggered at [...]
# and for negative ones
probs = torch.cuda.FloatTensor([-0.5, 0.5, 0.5])
dist = torch.distributions.categorical.Categorical(probs)
[...] cuda runtime error (59) : device-side assert triggered at [...]
```

On a side note: wouldn't it be interesting to bundle the different issues that deal with the annoyingly unspecific error messages involving `cuda runtime error (59) : device-side assert triggered at [...]` ?
As they are _really_ hard to debug, might it not be interesting to have some additional data-checking before performing the computation? I'd sacrifice that fraction of speed for good error-messages any day ...

Thanks for all the great work!

**Comment by yf225** [comment]
@cle-ros `torch.multinomial` and `torch.distributions.categorical.Categorical` actually use the same code for sampling, so on current master you should be able to see a more detailed error message the first time the device-side assert is triggered. e.g.:

```
>>> import torch
>>> x = torch.Tensor([0, float('inf')])
>>> torch.multinomial(x.to('cuda'), 1)
/home/ubuntu/pytorch/aten/src/THC/THCTensorRandom.cuh:186: void sampleMultinomialOnce(long *, long, int, T *, T *, int, int) [with T = float, AccT = float]: block: [0,0,0], thread: [1,0,0] Assertion `!THCNumerics<T>::isinf(val)` failed.
THCudaCheck FAIL file=/home/ubuntu/pytorch/aten/src/THC/generic/THCTensorCopy.cpp line=70 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/master/lib/python3.6/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "/home/ubuntu/miniconda3/envs/master/lib/python3.6/site-packages/torch/_tensor_str.py", line 253, in _str
    fmt, scale, sz = _number_format(get_summarized_data(self) if summarize else self)
  File "/home/ubuntu/miniconda3/envs/master/lib/python3.6/site-packages/torch/_tensor_str.py", line 83, in _number_format
    tensor = torch.DoubleTensor(tensor.size()).copy_(tensor).abs_().view(tensor.nelement())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /home/ubuntu/pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70
```

If you run the `torch.multinomial(x.to('cuda'), 1)` line again you will only see the `RuntimeError: cuda runtime error (59) : device-side assert triggered at /home/ubuntu/pytorch/aten/src/THC/generic/THCTensorCopy.cpp:20` error, because at that time CUDA hasn't recovered from previous failure yet, and we will need to re-initialize CUDA to set it back to its original state.

Regarding how to debug the `device-side assert triggered` error, you can try to run the program with `CUDA_LAUNCH_BLOCKING=1 python script.py`, and that will produce the correct stack trace pointing to where the assert was triggered from. https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-59/750/8 has more discussion on why it's designed this way.

I will create a PR to update the docs for `torch.distributions.categorical.Categorical` and emphasize that `probs` must be non-negative and have a non-zero sum.

**Comment by guotong1988** [comment]
Thank you.
