### ISSUE TITLE
C++ functional::smooth_l1_loss overrides beta in options with default

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#70163]
### 🐛 Describe the bug

Pull request #44433 added beta to the SmoothL1Options structure but overrides it in the functional call:

In nn/functional/loss.h:

```
inline Tensor smooth_l1_loss(
    const Tensor& input,
    const Tensor& target,
    const SmoothL1LossFuncOptions& options = {},
    double beta = 1.) {
  return detail::smooth_l1_loss(input, target, options.reduction(), beta);
}
```

If a beta is specified in the options, it will be overridden by the default in a call like:
```
torch::nn::functional::smooth_l1_loss(inputs, targets, options.beta(.5));
```

I think the definition in nn/functional/loss.h should remove the added beta in the arguments and reference it in the call to the detail function:

```
inline Tensor smooth_l1_loss(
    const Tensor& input,
    const Tensor& target,
    const SmoothL1LossFuncOptions& options = {})
  return detail::smooth_l1_loss(input, target, options.reduction(), options.beta());
}
```

### Versions

All libtorch versions from 1.7.0 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser

**Comment by jbschlosser** [comment]
Thanks for the report! I agree it's confusing that `beta` can be passed in in two ways, one of which is silently ignored.

The suggested change does seem to be the way to go, but note that it is technically BC-breaking for anyone who explicitly passes `beta` to `smooth_l1_loss()` outside of `SmoothL1LossFuncOptions`.

**Comment by kurtamohler** [comment]
To keep some backward compatibility and still support calling the function like `smooth_l1_loss(input, target, /*reduction=*/..., /*beta=*/...)`, we could overload the function like this:

```cpp
inline Tensor smooth_l1_loss(
    const Tensor& input,
    const Tensor& target,
    const SmoothL1LossFuncOptions& options = {}) {
  return detail::smooth_l1_loss(input, target, options.reduction(), options.beta());
}

inline Tensor smooth_l1_loss(
    const Tensor& input,
    const Tensor& target,
    SmoothL1LossFuncOptions::reduction_t reduction,
    double beta) {
  return detail::smooth_l1_loss(input, target, reduction, beta);
}
```

Is that alright?
