### ISSUE TITLE
Error in Ubuntu cross-compiling

### ISSUE THREAD

**Issue by TD-wzw** [pytorch/pytorch#70176]
### 🐛 Describe the bug

![2XJ01KMVHBULZ~ 9J6AV46F](https://user-images.githubusercontent.com/57340568/146750262-cea0feea-630b-4a66-9a78-110293fcc05d.png)

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.17.3
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-debian-buster-sid
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 460.91.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] Could not collect
[conda] # packages in environment at /opt/conda/envs/libtorch:

cc @malfet @seemethere

**Comment by malfet** [comment]
@TD-wzw please share the invocation command, otherwise it's not clear how are you trying to cross compile PyTorch
Also, would it work if you are to invoke it with `USE_SLEEF=OFF`?

**Comment by TD-wzw** [comment]
It has been settled. Thank you for your reply

**Comment by malfet** [comment]
Closing, if I understand last comment correctly. @TD-wzw if issue still persist do not hesitate to reopen.
