### ISSUE TITLE
Inference mode complains about inplace at torch.mean call, but I don't use inplace

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#70177]
### 🐛 Describe the bug

```
# acc_swav = torch.cat(acc_swav)

  File ".../eval_embeddings_retrieval.py", line 63, in main
    acc_swav = float(acc_swav[..., 1:].float().mean(dim = -1).mean())
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
```

- I don't have any inplace ops in this accuracy computation
- whole function is decorated with `@torch.inference_mode()`, so I definitely don't modify anything outside inference mode, I don't have tensors outside inference mode at all
- i've tried to make a simple repro, no exception got thrown, so something fishy/complex is going on

### Versions

1.9.1

**Comment by vadimkantorov** [comment]
Seems it's another occurrence of https://github.com/pytorch/pytorch/issues/60539

It makes inference_mode not workable for important cases :(

**Comment by ngimel** [comment]
Can't repro on master, please reopen with repro if still repros on 1.11/nightlies

**Comment by vadimkantorov** [comment]
But do you have a clue why this problem happened? Seems quite a strange failure mode. I also wonder if the constants for "big tensor" have simply changed...

**Comment by ngimel** [comment]
As Alban said, this is likely because tls wasn't passed correctly in the multithreading region, these places were cleaned up in #58655 and similar stacks from Peter Bell
