### ISSUE TITLE
Feature request: user specified default values for nn.Embedding

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/pytorch#702]
Hi,

I'm trying to create a module that, given an n-dimensional `LongTensor` returns an n+2 dimensional `FloatTensor` arranged correspondingly from slices of a 3-dimensional `FloatTensor`.  In theory this can be accomplished with `nn.Embedding` plus a reshape, except that I need the matrix corresponding to the `padding_idx` to be the identity matrix instead of a zero matrix.  This could be accomplished by allowing the user to specify what default vector is returned corresponding to `padding_idx`.  Would that be possible?

Thanks,
Shawn

**Comment by soumith** [comment]
this is certainly possible to implement, we have to change our C backends slightly to accommodate this. will put it on a list of things to do

**Comment by jbschlosser** [comment]
Closing this because it is possible to specify a custom value to use for the vector at `padding_idx`. An example of doing so is in the [Embedding docs](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html).
