### ISSUE TITLE
Backproping through Embedding in 0.4.0 fails

### ISSUE THREAD

**Issue by twoertwein** [pytorch/pytorch#7021]
## Issue description
torch.nn.Embedding seems to cause issues in PyTorch 0.4.0 when backproping through it.

## Code example
```py
import torch
embedding = torch.nn.Embedding(10, 3)
embedding(torch.LongTensor([0]).requires_grad_())[0, 0].backward()
```
RuntimeError: No grad accumulator for a saved leaf!

The following works:

```py
import torch
linear = torch.nn.Linear(10, 3)
linear(torch.rand(10).requires_grad_())[0].backward()
```

**Comment by t-vi** [comment]
Well, you can't backprop to the indices, but that's just the way life is. Everything else seems to work as expected. (BTW: functions like `torch.rand` and `torch.tensor` creating `Tensor`s take a keyword argument `requires_grad`.)

**Comment by apaszke** [comment]
This is a bug though. You shouldn't be able to call `requires_grad_()` on non-floating point tensors.

**Comment by t-vi** [comment]
OK. Do you want this tested in test_autograd.py?

**Comment by apaszke** [comment]
Yes please!

**Comment by twoertwein** [comment]
yes, it does not make sense to require gradients for this LongTensor but I think that the previous version of pytorch still didn't end up in a RuntimeError (throwing this error is probably better).

**Comment by ortasa** [comment]
Is there anything to do except returning to previous version?
Ortal

**Comment by t-vi** [comment]
You could un-require gradients on the indices (using detach() when all else fails). It won't get gradients anyway.
