### ISSUE TITLE
The master doc on pytorch.org is stuck on the 12/3/21 version

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#70211]
### 📚 The doc issue

The master doc on pytorch.org is stuck on the 12/3/21 version. The relevant commit seems to be https://github.com/pytorch/pytorch/commits/ef07820

![image](https://user-images.githubusercontent.com/24860335/146845778-ce6b5500-9052-4ef1-b823-c5b538c88aa2.png)

cc @ezyang @zou3519 @brianjo

**Comment by brianjo** [comment]
Thanks for letting us know X. @malfet Nikita, could you take a look at the CI?

**Comment by malfet** [comment]
Push times out as it waits for login in the interactive prompt, but solving it by passing something like `git remote set-url --push origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/pytorch/pytorch.github.io ` would solve the timeout, but not the problem, as github token is strictly limited to repo in question
