### ISSUE TITLE
“RuntimeError: std::bad_alloc” doing forward pass on CPU during deployment on certain hardware

### ISSUE THREAD

**Issue by dgmp88** [pytorch/pytorch#70237]
### 🐛 Describe the bug

During the forward pass of a model on a CPU, I get `RuntimeError: std::bad_alloc`. It's fixable by putting the forward pass in a try/catch loop. The bug only occurs if 

1. I do the forward pass after using the [lifelines](https://pypi.org/project/lifelines/) library (latest version)
2. I run the model on certain CPU architectures, currently an AWS t3.medium (`Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz`). The error doesn't occur on other architectures (tested on `Core i7 (I7-9750H)` and `Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz`

[This code](https://gist.github.com/dgmp88/7b37e3c7b7832abb4b162b3e768a4fa6) causes the bug on the AWS machine, and using GDB results in [this stack trace](https://gist.github.com/dgmp88/462fa02c726ecd85d63c3e0ac4992668). The stack trace seems to point towards a problem with MKL/ideep. 

There's more discussion on the pytorch forums [here](https://discuss.pytorch.org/t/sporadic-runtimeerror-std-bad-alloc-doing-forward-pass-on-cpu-during-deployment-on-certain-hardware/138861/8). 

### Versions

```
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.4.9
[pip3] pytorch-lightning-bolts==0.3.2
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.1              py3.9_cpu_0    pytorch
[conda] pytorch-lightning         1.4.9                    pypi_0    pypi
[conda] pytorch-lightning-bolts   0.3.2                    pypi_0    pypi
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.10.1                 py39_cpu  [cpuonly]  pytorch
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchvision               0.11.2                 py39_cpu  [cpuonly]  pytorch
```

cc @VitalyFedyunin @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh

**Comment by yanbing-j** [comment]
Hi @dgmp88 , I tried to reproduce this issue in a machine with CPU `Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz`, but the UT that you provided always passed. Could you please provide some more information?

My configuration is:
PyTorch version: 1.10.1 (install from `pip install torch` and install from `source file`, UT always passed)
GCC version: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Python version: 3.9.7
lifelines version: 0.26.4

cc @XiaobingSuper

**Comment by dgmp88** [comment]
Hi @yanbing-j . Happy new year, apologies for the very slow reply! Thanks very much for looking into this.

I replicated your setup, and noticed when I switched from conda to using pip as the installer I no longer saw the crash. I also didn't see the crash when I created a fresh conda environment. I created a minimal conda environment (below) which does cause the crash on my `Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz`. However, if I do a `conda update --all` it no longer crashes (it updates MKL, so presumably the bug is there). 

Given the super specific collection of packages/builds/CPU architectures required, maybe it makes sense to close this issue? I'll just fix by updating MKL.

---------

Save as `crashenv.yml`, Install with `conda env create -f crashenv.yml`

```
name: crashenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - cpuonly=1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - jbig=2.1=h7f98852_2003
  - jpeg=9d=h36c2ea0_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libdeflate=1.8=h7f98852_0
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.3.0=h6f004c6_2
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.2=h58526e2_4
  - nettle=3.6=he412f7d_0
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - pillow=8.4.0=py39ha612740_0
  - pip=21.2.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - readline=8.1=h46c0cb4_0
  - setuptools=60.2.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h9cd32fc_0
  - tbb=2021.5.0=h4bd325d_0
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.10.1=py39_cpu
  - torchvision=0.11.2=py39_cpu
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.1=ha95c52a_0
  - pip:
    - astor==0.8.1
    - autograd==1.3
    - autograd-gamma==0.5.0
    - cycler==0.11.0
    - fonttools==4.28.5
    - formulaic==0.2.4
    - future==0.18.2
    - interface-meta==1.2.4
    - kiwisolver==1.3.2
    - lifelines==0.26.4
    - matplotlib==3.5.1
    - packaging==21.3
    - pandas==1.3.5
    - pyparsing==3.0.6
    - pytz==2021.3
    - scipy==1.7.3
    - wrapt==1.13.3
prefix: /home/ubuntu/miniconda3/envs/crashenv
```

**Comment by yanbing-j** [comment]
Hi @dgmp88.  Happy new year! It makes sense to close this issue.

**Comment by enkhtogtokh** [comment]
Exactly same problem happened and killed my productive morning time. **The solution**: is just upgrade your numpy version. It fixes the problem. 
It might appear in Intel XEON cpus and cloud environment.
What i tried were:
upgraded MKL with conda, it did not help.
upgraded and downgraded pytorch versions, no chance. And all previous recommendations, they did not help.
