### ISSUE TITLE
[Caffe2 Bug] ill-formed initializer list

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#7023]
## Issue description

Visual Studio 2017 is complaining about error C2398:
```
error C2398: Element '9': conversion from 'double' to 'float' requires a narrowing conversion
```

In `roi_align_op_gpu_test.cc` there's a code block:
```
    vector<float> rois{0, 0,           0,           79,          59,
                       0, 0,           5.0005703,   52.63237,    43.69501495,
                       0, 24.13628387, 7.51243401,  79,          46.06628418,
                       0, 0,           7.50924301,  68.47792816, 46.03357315,
                       0, 0,           23.09477997, 51.61448669, 59,
                       0, 0,           39.52141571, 52.44710541, 59,
                       0, 23.57396317, 29.98791885, 79,          59,
                       0, 0,           41.90219116, 79,          59,
                       0, 0,           23.30098343, 79,          59};
```
We should add `f` to the end of all double constants since narrowing conversion is ill-formed 

## System Info
- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source
- OS: Win10
- PyTorch version: master branch
- CUDA/cuDNN version: 9.1/7.1.3
- GPU models and configuration: 1080Ti
- Visual Studio version (if compiling from source): Visual Studio 2017.6 + v140 toolset
- CMake version: 3.11.1

**Comment by xkszltl** [comment]
Similar issue posted at https://github.com/caffe2/caffe2/issues/1671

**Comment by xkszltl** [comment]
PR created #7024 .
Please review and merge.

Thanks

**Comment by pjh5** [comment]
Thanks for the contribution!
