### ISSUE TITLE
Update README's gif to reflect Variable changes

### ISSUE THREAD

**Issue by Iwontbecreative** [pytorch/pytorch#7025]
The README dynamic's graph gif ( e.g [dynamic graph](https://github.com/pytorch/pytorch/blob/master/docs/source/_static/img/dynamic_graph.gif) ) is still in 0.3 mode and has Variable all over. Considering the recent release, would make sense to update it.

**Comment by SsnL** [comment]
Duplicate of #6180 . I'll do it.
