### ISSUE TITLE
 Define and Put in place process to regularly update Grafana instance in order to avoid outages

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#70250]
As a software developer I would like to put in place the process to regularly update Grafana version (metrics.pytorch.org) and Nginx version.
In order to avoid outages caused by software vulnerabilities

cc @ezyang @zou3519 @brianjo

**Comment by ezyang** [comment]
untriaging this as doc infra is not right. Who is running metrics these days, @suo do you know?

**Comment by suo** [comment]
@atalman is :)

**Comment by mruberry** [comment]
@atalman I'll let you figure out how best to label this
