### ISSUE TITLE
Norm function is not working for Tensors.

### ISSUE THREAD

**Issue by vinith2** [pytorch/pytorch#70252]
### 🐛 Describe the bug

import torch

x = torch.randn(3,4,5,6,7,8)
y = torch.norm(x,dim=(1,2,3))

The Error I get is:

RuntimeError                              Traceback (most recent call last)
<ipython-input-49-93aafa14300f> in <module>
      2 
      3 x = torch.randn(3,4,5,6,7,8)
----> 4 y = torch.norm(x,dim=(1,2,3))

~/anaconda3/envs/cryo/lib/python3.8/site-packages/torch/functional.py in norm(input, p, dim, keepdim, out, dtype)
   1312                 _dim = [i for i in range(ndim)]  # noqa: C416 TODO: rewrite as list(range(m))
   1313             if out is None:
-> 1314                 return _VF.frobenius_norm(input, _dim, keepdim=keepdim)  # type: ignore
   1315             else:
   1316                 return _VF.frobenius_norm(input, _dim, keepdim=keepdim, out=out)  # type: ignore

RuntimeError: Expected at most 2 dimensions, but got 3 dimensions instead.

### Versions

PyTorch version: 1.7.1

**Comment by rmcavoy** [comment]
That is not a bug. That is the norm function working as intended. As the error message says, you gave it 3 dimensions and it expected at most 2 dimensions.

**Comment by vinith2** [comment]
the dim variable takes lists or tuples, so I should be able to give list of dimensions along which this should be updated right?

**Comment by vinith2** [comment]
The condition that there can only dimensions is not mentioned in the docs too.

**Comment by rmcavoy** [comment]
You can give it a list but only of up to two dimensions as the error message says. BTW it is in fact listed in the docs "Frobenius norm produces the same result as p=2 in all cases except when dim is a list of three or more dims, in which case Frobenius norm throws an error." You just need to read a bit more carefully next time both the error message and the documentation.

**Comment by vinith2** [comment]
Ok, thanks I got it now. So I have to add p=2, as the parameter. Since Frobenius norm is same as norm when p=2, shouldn't this be the default implementation? It easier when specifying dimension right?
