### ISSUE TITLE
How to create build-in buffers which is writable during onnx inference?

### ISSUE THREAD

**Issue by lawlict** [pytorch/pytorch#70280]
### 🚀 The feature, motivation and pitch

First, I'm sorry that this question may not be strictly relative to a feature request, but it has been posted on discuss.pytorch.org without any replies for one week.

Hi, I try to create a first-in-first-out queue as a pytorch model, export it to onnx and infer with onnxruntime. The queue, with a limited size, updates every time when a new input comes, and returns the updated queue. Codes are very simple:
```
import torch
import torch.nn as nn

class WavBuffer(nn.Module):
    def __init__(self, size=10):
        super().__init__()
        self.size = size
        wavbuf = torch.zeros(size)
        self.register_buffer('wavbuf', wavbuf)

    def forward(self, x):
        self.wavbuf = torch.cat([self.wavbuf, x])[-self.size:]
        return self.wavbuf

model = WavBuffer(10)
x = torch.ones(5)
for i in range(2):
    wavbuf = model(x)
    print(wavbuf)
```
As expected, the outputs are:
```
tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```
Then I export the model to onnx format and infer with onnxruntime:
```
torch.onnx.export(
    model, torch.zeros(5), 'model.onnx', verbose=False, input_names=['wav'],
    output_names=['wavbuf'], opset_version=11
)

import numpy as np
import onnxruntime

model = onnxruntime.InferenceSession('model.onnx')
x = np.ones(5, dtype=np.float32)
inputs = {model.get_inputs()[0].name: x}
for i in range(2):
    outputs = model.run(None, inputs)
    wavbuf = outputs[0]
    print(wavbuf)
```
However, now the outputs are:
```
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
```
I guess that weights in onnx models are not changeable, but is there any solution to create writable build-in buffers during model design and change the buffers in onnx inference? An available example is LSTM, where the hidden states update for each time step. However, it is too difficult for me to its implementation.

**Comment by BowenBao** [comment]
hi @lawlict, you can explore the option of using `keep_initializers_as_input` argument in `torch.onnx.export`. In short when set to true, the exported model will set weights/buffers as additional inputs with original value as default value. More info here https://pytorch.org/docs/stable/onnx.html?highlight=onnx#module-torch.onnx.

With that, you will be able to supply updated `wavbuf` as additional input in later iterations. Full updated script below:
```python
import torch
import torch.nn as nn

class WavBuffer(nn.Module):
    def __init__(self, size=10):
        super().__init__()
        self.size = size
        wavbuf = torch.zeros(size)
        self.register_buffer('wavbuf', wavbuf)

    def forward(self, x):
        self.wavbuf = torch.cat([self.wavbuf, x])[-self.size:]
        return self.wavbuf

model = WavBuffer(10)
x = torch.ones(5)
for i in range(2):
    wavbuf = model(x)
    print(wavbuf)

torch.onnx.export(
    model, torch.zeros(5), 'model.onnx', verbose=False, input_names=['wav', 'buf'],
    output_names=['wavbuf'], opset_version=11,
    keep_initializers_as_inputs=True,
)

import numpy as np
import onnxruntime

model = onnxruntime.InferenceSession('model.onnx')
x = np.ones(5, dtype=np.float32)
inputs = {model.get_inputs()[0].name: x}
for i in range(2):
    outputs = model.run(None, inputs)
    wavbuf = outputs[0]
    inputs = {'wav': x, 'buf': wavbuf}
    print(wavbuf)
```

**Comment by lawlict** [comment]
Hi @BowenBao, that is exactly what I want. Thank you very much!
