### ISSUE TITLE
Exporting the operator inverse to ONNX opset version 10 is not supported

### ISSUE THREAD

**Issue by RAJA-PARIKSHAT** [pytorch/pytorch#70299]
### 🚀 The feature, motivation and pitch

I am working with a deep neural network for motion transfer. I tried to convert the model in ONNX format but turns out ONNX does not have any support for certain operators. 
Following is the error I got 
RuntimeError: Exporting the operator inverse to ONNX opset version 10 is not supported. Please open a bug to request ONNX export support for the missing operator.

**Comment by fatcat-z** [comment]
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1567895.

**Comment by gigadeplex** [comment]
> This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1567895.

Jay Z, I'm still having this problem. Any solutions yet?

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

**Comment by chiragsamal** [comment]
Inverse is from the set of custom ops that are built in to most ORT packages. You can see this in [pytorch_export_contrib_ops.py](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/pytorch_export_contrib_ops.py).

To export using those contrib ops, call 

> pytorch_export_contrib_ops.register()

 before calling torch.onnx.export(). For example:

```
from onnxruntime.tools import pytorch_export_contrib_ops
import torch

pytorch_export_contrib_ops.register()
```
Hope this helps!

**Comment by Lucky-BenXie** [comment]
> Inverse is from the set of custom ops that are built in to most ORT packages. You can see this in [pytorch_export_contrib_ops.py](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/pytorch_export_contrib_ops.py).
> 
> To export using those contrib ops, call
> 
> > pytorch_export_contrib_ops.register()
> 
> before calling torch.onnx.export(). For example:
> 
> ```
> from onnxruntime.tools import pytorch_export_contrib_ops
> import torch
> 
> pytorch_export_contrib_ops.register()
> ```
> 
> Hope this helps!

OK, noted. I successfully exported the ONNX model according to your method. However, when I used ONNX Runtime for inference, the result I got was inconsistent with that of the PyTorch model.
