### ISSUE TITLE
`lu_solve` will frequently crash

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#70292]
### 🐛 Describe the bug

`torch.lu_solve` will frequently crash.

```python
import torch
arg_1 = torch.tensor(
        [[[0.7765],
          [0.6088],
          [0.3014]],

         [[0.7765],
          [0.3868],
          [0.0320]]])
arg_2 = torch.tensor(
        [[[0.4053, 0.6713, 0.8894],
          [0.7145, 0.0562, 0.0616],
          [0.6813, 0.5486, 0.9225]],

         [[0.8425, 0.3334, 0.1288],
          [0.3434, 0.7524, 0.9728],
          [0.4400, 0.3666, 0.7364]]])
arg_3 = torch.tensor([[0, 7, 7],
        [4, 3, 6]], dtype=torch.int32)
res= torch.lu_solve(arg_1,arg_2,arg_3,)
# double free or corruption (out)
# [1]    7940 abort (core dumped)  python a.py
```

However, the same code will not crash on colab with the same pytorch version and cuda.

### Versions

```
OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.25

Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.4.100
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 495.44
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0+cu111
[pip3] torchaudio==0.10.0+cu102
[pip3] torchvision==0.11.1+cu102
[conda] Could not collect
```

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @albanD @zou3519

**Comment by malfet** [comment]
Hmm, I can repro it on my Mac using 1.9.1

**Comment by malfet** [comment]
@ilovepytorch can you please share the original matrix, whose LU decomposition yielded `arg_2` and `arg_3`

**Comment by malfet** [comment]
Tentatively closing the issue, as input fed to `lu_solve` is not valid (pivot values, returned by `torch.lu` should not exceed factorized matrix dimension, should they?)

**Comment by ilovepytorch** [comment]
@malfet Yes, the input is invalid. But I think pytorch should raise an good error instead of crash.

**Comment by Lezcano** [comment]
Alas, we don't perform checks on this function, as this function is intended to be used with the output of `torch.lu` (soon `torch.linalg.lu_factor` https://github.com/pytorch/pytorch/pull/66933). If you want to have something that doesn't crash, have a look at `torch.linalg.solve`. Now, if you don't want to use the output of `torch.lu`, but you want to craft your own output, you'll need to be careful as to provide the output in the correct format (which is not a simple task, but it is what it is)
