### ISSUE TITLE
How to intall and use Caffe2 from this Pytorch branch?

### ISSUE THREAD

**Issue by yw155** [pytorch/pytorch#7029]
Hi, I would like to ask a question that how to install and use Caffe2 from this Pytorch branch. Do I need to install Pytorch and Caffe2 simultaneously, or just install Pytorch is enough? In addition, about using Caffe2, is it possible to deploy Pytorch functions and Caffe2 functions in one script at the same time?

**Comment by yw155** [comment]
@xkszltl, thanks.

**Comment by pjh5** [comment]
Right now the installations are completely separate, so you can continue to use the old Pytorch installation instructions to install Pytorch and the old Caffe2 installation instructions to install Caffe2. If you do install both then you should be able to import modules from both Caffe2 and Pytorch in the same script and refer to functions from both.

**Comment by yw155** [comment]
@pjh5, I got that, thank you.
