### ISSUE TITLE
The signature of `multilabel_soft_margin_loss` in the doc misses `reduction` parameter

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#70301]
### 📚 The doc issue

The [documentation](https://pytorch.org/docs/stable/generated/torch.nn.functional.multilabel_soft_margin_loss.html) of `multilabel_soft_margin_loss` misses `reduction` parameter. 

### Suggest a potential alternative/fix

The right signature should be
```
torch.nn.functional.multilabel_soft_margin_loss(input, target, weight=None, size_average=None, reduction='mean') → Tensor
```

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @kshitij12345

**Comment by soulitzer** [comment]
Thanks for the report. We would accept a PR to fix this.
