### ISSUE TITLE
PyTorch RNN Tutorials don't work on Windows

### ISSUE THREAD

**Issue by gothos-folly** [pytorch/pytorch#7033]
The tutorials [Classifying Names with a Character-Level RNN](http://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html) and [Generating Names with a Character-Level RNN](http://pytorch.org/tutorials/intermediate/char_rnn_generation_tutorial.html) don't work on Windows.

They attempt to extract the category from the filename using

    category = filename.split('/')[-1].split('.')[0]

which works on Linux where these look like `'data/names/Arabic.txt'` but not on Windows where they look like `'data/names\\Arabic.txt'`.

I suggest changing the code to

    category = os.path.splitext(os.path.basename(filename))[0]

**Comment by apaszke** [comment]
Can you please send a PR in the tutorials repo?

**Comment by zou3519** [comment]
https://github.com/pytorch/tutorials/pull/232 will fix this.
