### ISSUE TITLE
The DataLoader can't work in Apple Silicon.

### ISSUE THREAD

**Issue by alanyoungCN** [pytorch/pytorch#70344]
### 🐛 Describe the bug

I think the DataLoader can't work in M1 Mac at all.

The following code uses torchvision to download the Fashion-MNIST dataset.
```Python
import torch
from torchvision import transforms
import torchvision
import torch.utils.data

trans = transforms.ToTensor()
mnist_train = torchvision.datasets.FashionMNIST(
    root="./data", train=True, transform=trans, download=True
)
mnist_test = torchvision.datasets.FashionMNIST(
    root="./data", train=False, transform=trans, download=True
)

batch_size = 256

def get_dataloader_workers():
    return 4

train_iter = torch.utils.data.DataLoader(
    mnist_train, batch_size, shuffle=True, num_workers=get_dataloader_workers()
)

for X, y in train_iter:
    continue
```
On my MacBook Pro 16 with M1 Max, it can't run and the results are below:
```
/Users/alanyoung/Documents/Codes/LiMuPytorch/venv/lib/python3.9/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
/Users/alanyoung/Documents/Codes/LiMuPytorch/venv/lib/python3.9/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/alanyoung/Documents/Codes/LiMuPytorch/minimal_fashion.py", line 24, in <module>
    for X, y in train_iter:
  File "/Users/alanyoung/Documents/Codes/LiMuPytorch/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/Users/alanyoung/Documents/Codes/LiMuPytorch/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/alanyoung/Documents/Codes/LiMuPytorch/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/venv_base/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
Due to the num_workers=4, there are 4 same errors and I just paste one.

---

BTW, I also tried to build the Dataset on my own, the code is in my Github Gist.https://gist.github.com/alanyoungCN/6f8f522a4bb4009f781f801ad5521b09
To run the code above, you need to download the Fashion-MNIST first. It can run in my M1 MacBook but it's very very slow. The last iteration takes 21 secs to finish, which is much slower than even an Intel i3 Processer with HDD.

Or is anything wrong in my code?

### Versions

PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 23:53:23)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.10.0
[conda] Could not collect

cc @SsnL @VitalyFedyunin @ejguan @NivekT @malfet @albanD

**Comment by alanyoungCN** [comment]
One more thing, I tried the codes in Google Colab or Kaggle, which could run without errors and takes few seconds(1 sec around).

**Comment by alanyoungCN** [comment]
Can anyone have a try and tell me whether it is a bug/common problem at least?

**Comment by logan-lieou** [comment]
M1 Borked asf

**Comment by ejguan** [comment]
The Error is pretty clear that you should wrap your iteration code within `if __name__ == '__main__'`

```py
if __name__ == '__main__':
    train_iter = torch.utils.data.DataLoader(
        mnist_train, batch_size, shuffle=True, num_workers=get_dataloader_workers()
    )

    for X, y in train_iter:
        continue
```

I believe this is due to the default multiprocessing methods are different between mac and linux.

**Comment by alanyoungCN** [comment]
It works without error, thank you. But there are still some small issues:
-   Dataloaders in Mac don't (or can't) use parallel computing, so the ```num_workers``` should be 0 (https://stackoverflow.com/questions/64772335/) or it will show the following warning:

    > Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
  
    There aren't any warnings in the documentation(https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).

-   There is also one warning left. 

    > UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)

    No such warning in Linux. Maybe it has been discussed in https://github.com/pytorch/vision/issues/4183. Should it be ignored?

**Comment by alanyoungCN** [comment]
> The Error is pretty clear that you should wrap your iteration code within `if __name__ == '__main__'`
> 
> ```python
> if __name__ == '__main__':
>     train_iter = torch.utils.data.DataLoader(
>         mnist_train, batch_size, shuffle=True, num_workers=get_dataloader_workers()
>     )
> 
>     for X, y in train_iter:
>         continue
> ```
> 
> I believe this is due to the default multiprocessing methods are different between mac and linux.

It works without error, thank you. But there are still some small issues:
-   Dataloaders in Mac don't (or can't) use parallel computing, so the ```num_workers``` should be 0 (https://stackoverflow.com/questions/64772335/) or it will show the following warning:

    > Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
  
    There aren't any warnings in the documentation(https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader).

-   There is also one warning left. 

    > UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)

    No such warning in Linux. Maybe it has been discussed in https://github.com/pytorch/vision/issues/4183. Should it be ignored?

**Comment by ejguan** [comment]
> * Dataloaders in Mac don't (or can't) use parallel computing, so the `num_workers` should be 0 (https://stackoverflow.com/questions/64772335/) or it will show the following warning:
>   > Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)

I am not 100% sure about this warning. It may come from https://github.com/pytorch/pytorch/blob/aea3d3ced7dc206bfa98f677e205a80d7bd65543/torch/utils/data/_utils/worker.py#L216. But, I think it won't influence the main process.

> * here is also one warning left.
>   > UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)

I think Vision has already fixed such issue as shown in the link

**Comment by ejguan** [comment]
@alanyoungCN 

> Dataloaders in Mac don't (or can't) use parallel computing, so the num_workers should be 0 (https://stackoverflow.com/questions/64772335/) or it will show the following warning:

I don't think this is correct. I am able to run multi-worker DataLoader on my Mac. But, I don't have access to mac with M1 chip to test. But, I don't think this is going to be a problem.

**Comment by liulhdarks** [comment]
The same error when running program in mac M1 with DataLoader’s num_workers>0,  after set num_workers=0, it works.

**Comment by ejguan** [comment]
@liulhdarks 
Can you take a look at https://github.com/pytorch/pytorch/issues/70344#issuecomment-1005013413

**Comment by alanyoungCN** [comment]
> The Error is pretty clear that you should wrap your iteration code within `if __name__ == '__main__'`
> 
> ```python
> if __name__ == '__main__':
>     train_iter = torch.utils.data.DataLoader(
>         mnist_train, batch_size, shuffle=True, num_workers=get_dataloader_workers()
>     )
> 
>     for X, y in train_iter:
>         continue
> ```
> 
> I believe this is due to the default multiprocessing methods are different between mac and linux.

@ejguan 
Hi, actually I don't think wrapping the code within `if __name__ == '__main__'` will actually work, for I set num_workers=0 at the same time. Once I set num_workers>0, it will show the same error. Maybe there is some conflicts between ARM Mac and DataLoader. Sorry for previous talking, please take a try on an Apple Silicon Mac. 

BTW, recently I test a CV dataset between my ARM Mac and a x86 computer with a GPU(Kaggle free GPU), I think dataloader=0 badly influences the performance. With the batch_size getting bigger(64->128), the ARM Mac becomes slower(0.8 it/s -> 7 s/it) but the x86 computer is getting faster.

**Comment by Sergio-P** [comment]
Same problem here. Any workarounds besides set the workers to 0?

**Comment by yhcc** [comment]
Try to use multiprocessing='fork' in the initialization of DataLoader.

**Comment by zisanyalcinkaya** [comment]
I'm facing the same problem on Mac M2. Setting an environment variable to 1 removes the error:
```export OMP_NUM_THREADS=1; ```
but training is still slow. 
Did you find any solution?


> > * Dataloaders in Mac don't (or can't) use parallel computing, so the `num_workers` should be 0 (https://stackoverflow.com/questions/64772335/) or it will show the following warning:
> >   > Warning: Cannot set number of intraop threads after parallel work has started or after set_num_threads call when using native parallel backend (function set_num_threads)
> 
> I am not 100% sure about this warning. It may come from
> 
> https://github.com/pytorch/pytorch/blob/aea3d3ced7dc206bfa98f677e205a80d7bd65543/torch/utils/data/_utils/worker.py#L216
> 
> . But, I think it won't influence the main process.
> > * here is also one warning left.
> >   > UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:189.)
> 
> I think Vision has already fixed such issue as shown in the link

**Comment by ejguan** [comment]
> export OMP_NUM_THREADS=1;

This would make all processes using non-parallel calls. Please launch worker processes using `spawn` (`DataLoader(multiprocessing_context="spawn"`), this would prevent subprocesses inheriting the object created by your main process.

**Comment by hk6an6** [comment]
I'm having the same issue. I followed every direction in this conversation thread, and the issue remains.

Seeing as this issue is resolved, I am wondering what I missed. AFAIK, data loaders can't work well on apple silicon with multiprocessing.
