### ISSUE TITLE
torch.stft output size is not right.

### ISSUE THREAD

**Issue by erogol** [pytorch/pytorch#7038]
I try replace librosa functions with pytorch here https://github.com/mozilla/TTS

What I realized is, output sequence lengths are different for these two functions.

Below functions are used for testing. The point is given a audio signal in size 224960, pytorch's output is in size [815, 1025, 2] and librosa's [819, 1025].

Given the parameters ```n_fft, hop_length, win_length = [2048, 275, 1102]``` 819 seems right. 

```python
win = torch.hann_window(win_length).cuda()
def spectrogram_torch(y):
    n_fft, hop_length, win_length = [2048, 275, 1102]
    y[1:] = y[1:] - 0.097 * y[:-1]
    print(y.shape)
    start = time.time()
    D = torch.stft(y, frame_length=win_length, hop=hop_length, fft_size=n_fft,
                   onesided=True, window=win)[:, :, 1]
    print(time.time()-start)
    D = torch.abs(D)
    D[D==0] = 1e-5
    D = 20 * torch.log10(D)
    D -= ap.ref_level_db
    D = torch.clamp((D - ap.min_level_db) / -ap.min_level_db, 1e-8, 1)
    return D


def spectrogram(y):
    start = time.time()
    D = ap.apply_preemphasis(y)
    n_fft, hop_length, win_length = [2048, 275, 1102]
    D = librosa.stft(y=D, n_fft=n_fft, hop_length=hop_length, win_length=win_length)
    print(time.time()-start)
    S = ap._amp_to_db(np.abs(D)) - ap.ref_level_db
    S = ap._normalize(S)
    S = S.astype(np.float32)
    return S
```

**Comment by zou3519** [comment]
cc @SsnL

**Comment by SsnL** [comment]
librosa by default has `center=True` which pads the signal so that returned frequency at index `i` is for signal **centered** at index `i * hop`. So return size = `ceil(224960 / 275) = 279`.

PyTorch has returned frequency at index `i` beginning at index `i * hop`. So return size = `ceil((224960 - 1102) / 275) = 815`.

I believe if you set `center=False` for librosa or pad PyTorch tensor properly you will get same outputs.

**Comment by erogol** [comment]
@SsnL when ```center=False```, librosa returns ```811```. I don't know if it is a big problem but still not matching to what you suggest.

**Comment by SsnL** [comment]
@erogol I know what's going on. For reasons I'm not understanding, `librosa` pads the window to same length as `nfft` [here](https://github.com/librosa/librosa/blob/a41361c6629e5163f162bd2e20399b886812f714/librosa/core/spectrum.py#L152-L153). So it would get `ceil(224960 - 2048) / 275) = 811` with `center=False`, and `ceil(224960 / 275) = 819` for `center=True`.

**Comment by SsnL** [comment]
We are matching `scipy.signal` behavior (setting `noverlap=frame_length - hop`) so I think it is good. 

Feel free to reopen if there is any concern. :)

**Comment by SsnL** [comment]
@erogol In the next release, `stft` will have consistent signature and behavior with `librosa`

**Comment by carankt** [comment]
I was facing a similar issue but I realized the librosa gives a complex dtype whereas the torch.stft gives two matrices of float32. If you modify the paratmer `return_complex = True` in the torch.stft you will get the same results almost with some precision error that should be negligible.
