### ISSUE TITLE
[W accumulate_grad.h:184] 

### ISSUE THREAD

**Issue by miaoct** [pytorch/pytorch#70389]
[W accumulate_grad.h:184] Warning: grad and param do not obey the gradient layout contract. This is not an error, but may impair performance.
grad.sizes() = [768, 728, 1, 1], strides() = [728, 1, 1, 1]
param.sizes() = [768, 728, 1, 1], strides() = [728, 1, 728, 728] (function operator())

how to solve it?

I have tried [https://github.com/pytorch/pytorch/issues/47163](https://github.com/pytorch/pytorch/issues/47163 ) , but didn't fix

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @ezyang @albanD @zou3519 @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by gchanan** [comment]
Do you have a reproduction?  Please follow the template.

**Comment by XuecWu** [comment]
@miaoct  Have you ever solved it?  It has confused me for a long period of time.
