### ISSUE TITLE
Rprop Algorithm Missing settng g_t =0 if gprev*g_t<0 :

### ISSUE THREAD

**Issue by chemist29** [pytorch/pytorch#70418]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.optim.Rprop.html?highlight=rprop#torch.optim.Rprop

In the else if in the for loop, there must be a term for setting g_t =0. As is in the code. The documentation is straight up wrong.

cc @brianjo @mruberry @vincentqb @jbschlosser @albanD

**Comment by albanD** [comment]
Hi,

Good catch!
We are indeed missing the zero-ing out of `g_t^i` when the direction is negative.
We would accept a PR fixing that.
