### ISSUE TITLE
[bug report] (Pytorch 0.4.0) Dropout layer error when input is longtensor with 0

### ISSUE THREAD

**Issue by yu45020** [pytorch/pytorch#7042]
## Code example
```
a = torch.LongTensor([[1,2,3,4,5,0],[1,2,3,0,0,0]])
dr = torch.nn.Dropout(p=0.5)
dr(a)
```
=============     Output          ==================
Process finished with exit code -1073741676 (0xC0000094)

When I run my script in Jupyter Notebook, the input is 
```
batch_x
```
```
tensor([[  9275,   7123,   5062,  ...,   4286,   2369,   5854],
        [  1484,   2162,   1908,  ...,   3859,   7213,  10871],
        [ 11265,   2103,   4877,  ...,   5040,  10871,   3859],
        ...,
        [ 11558,    488,   8513,  ...,      0,      0,      0],
        [ 11558,    851,   5770,  ...,      0,      0,      0],
        [ 11558,    488,   4985,  ...,      0,      0,      0]], device='cuda:0')
```
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-f05c20dbc710> in <module>()
      1 dr = torch.nn.Dropout(0.2)
----> 2 dr(batch_x)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    489             result = self._slow_forward(*input, **kwargs)
    490         else:
--> 491             result = self.forward(*input, **kwargs)
    492         for hook in self._forward_hooks.values():
    493             hook_result = hook(self, input, result)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/dropout.py in forward(self, input)
     51 
     52     def forward(self, input):
---> 53         return F.dropout(input, self.p, self.training, self.inplace)
     54 
     55 

/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py in dropout(input, p, training, inplace)
    550 
    551 def dropout(input, p=0.5, training=False, inplace=False):
--> 552     return _functions.dropout.Dropout.apply(input, p, training, inplace)
    553 
    554 

/usr/local/lib/python3.6/dist-packages/torch/nn/_functions/dropout.py in forward(cls, ctx, input, p, train, inplace)
     38             ctx.noise.fill_(0)
     39         else:
---> 40             ctx.noise.bernoulli_(1 - ctx.p).div_(1 - ctx.p)
     41         ctx.noise = ctx.noise.expand_as(input)
     42         output.mul_(ctx.noise)

RuntimeError: invalid argument 3: divide by zero at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:88

```

I am fitting an LSTM model. The input have various lengths, so I pad the shorter examples with 0s. Then I add a dropout layer so that the longer examples have higher probability to be masked out.

**Comment by ngimel** [comment]
Probably related to #6196

**Comment by michaelcapizzi** [comment]
@yu45020 I had a similar error, but it was because I was accidentally feeding a `2D` tensor to the `Dropout2D()` function.

In my code, the shape of each `batch` is this: `sequence_len x batch_size x embedding_size`.  

You seem to be making the same mistake I did by feeding a `tensor` of `sequence_len x batch_size` where the values are indexes to rows in your embedding matrix.  Once you "lookup" the indexes and get a shape of `sequenc_len x batch_size x embedding_size`, it should work.

If you want to do the dropout *before* looking up embeddings, then you just need `Dropout[1D]()`.

**Comment by yu45020** [comment]
@michaelauli  Thank you very much !

**Comment by ailzhang** [comment]
This issue seems to be resolved by @michaelcapizzi 's comment above. Closing, please feel free to reopen if it still exist.

**Comment by YontiLevin** [comment]
had the same error.
tried to drop letters in a char-rnn before the embeddings.
the problem was with the bernoulli.div part
seems that when the input are ints/longs -> ctx.noise.bernoulli is of type int/long
and calling the div_ function with a float results in a crash.
example:
```
dropout_p = 0.5
dropout = torch.nn.Droupout(p=droupout_p)
inputs = torch.LongTensor([[10,15,30,0,3,5,8], [10,30,0,0,0,0,0]])
x = dropout(inputs)

>>> ERROR...
```
ugly solution:

```
dropout_p = 0.5
dropout = torch.nn.Droupout(p=droupout_p)
inputs = torch.LongTensor([[10,15,30,0,3,5,8], [10,30,0,0,0,0,0]])
x = dropout(inputs.float())
print(x)
>>> [[0.0, 22.5,60.0, 0.0, 4.5, 0.0, 12.0], [15.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
x= x.mul(1-dropout_p).long()  
print(x)
>>> [[0, 15,30, 0, 3, 0, 8], [10, 0, 0, 0, 0, 0, 0]]
```

**Comment by shamoji101** [comment]
I faced the same error. But I found solution for this error. 
This error raise because of torch.LongTensor. so, changing into torch.FloatTensor is the solution.
But, need attention for this "the dropout layer's outputs are scaled by a factor of 1/(1-p) during training." 

another solution (don't scale):
```
x=torch.FloatTensor([[1,2,3,4,5],[6,7,8,9,10]])
print("x:",x)
p=torch.full(x.shape,0.5)
print("p:",p)
mask=torch.bernoulli(p)
print("mask:",mask)
print("x * mask:",x * mask)
```

this is useful function for that problem:
```
def LongTensor_dropout_func(x,p=0.5):
    assert 0<=p<=1,"p is must be 0<=p<=1"
    return (x.type(torch.FloatTensor) * torch.bernoulli(torch.full(x.shape,1-p))).type(torch.LongTensor)
```
