### ISSUE TITLE
deleting model does not free space

### ISSUE THREAD

**Issue by jedi2610** [pytorch/pytorch#70431]
### 🐛 Describe the bug

I was using a model and then it failed on the 2nd pass because of OOM error. i then went ahead and checked that if it would work if i initialize the model on every pass and delete it after that pass is over. but to my surprise even after calling `del model`, the memory is not freed.

```python
for i in range(2):
    # fails on the 2nd pass i.e when i = 1
    model = Model(INPUT_DIMS, 9)
    model.to('cuda')
    policy, value = model(randInput, deterministic)

    print(torch.cuda.memory_allocated())    # 4584986624
    del model
    print(torch.cuda.memory_allocated())    # 4584986624
```
Traceback:
```
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.80 GiB total capacity; 4.32 GiB already allocated; 12.44 MiB free; 4.40 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I then tried with `with torch.no_grad()` and not surprising it worked but the weird thing is that the memory is freed after calling `del model`.

```python
for i in range(2):
    # passes both passes (that's 2 passes in a 3 word sentence lol)
    model = Model(INPUT_DIMS, 9)
    model.to('cuda')
    with torch.no_grad():
        policy, value = model(randInput, deterministic)

    print(torch.cuda.memory_allocated())    # 192300544
    del model
    print(torch.cuda.memory_allocated())    # 2401792
```

### Versions

PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: 13.0.0
CMake version: version 3.22.1
Libc version: glibc-2.33

Python version: 3.9.7 (default, Oct 10 2021, 15:13:22)  [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.15.11-arch2-1-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660
Nvidia driver version: 495.46
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.0
/usr/lib/libcudnn_adv_infer.so.8.3.0
/usr/lib/libcudnn_adv_train.so.8.3.0
/usr/lib/libcudnn_cnn_infer.so.8.3.0
/usr/lib/libcudnn_cnn_train.so.8.3.0
/usr/lib/libcudnn_ops_infer.so.8.3.0
/usr/lib/libcudnn_ops_train.so.8.3.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.2
[conda] Could not collect

**Comment by gchanan** [comment]
Try `del policy; del value` as well -- something is holding on to the autograd tape.

Please kindly ask questions on https://discuss.pytorch.org/.

**Comment by jedi2610** [comment]
that worked thank you, should have given it more thought my bad.
