### ISSUE TITLE
3D Convolution Transpose + Layer norm leads to error RuntimeError: ones needs to be contiguous

### ISSUE THREAD

**Issue by ziyi-yang** [pytorch/pytorch#70440]
### 🐛 Describe the bug

Run layer norm after 3D transpose convolution leads to an error regarding "contiguous tensor". A similar issue with 2D transpose conv can be found at #33168. To reproduce the bug:
```python
import torch
import torch.nn as nn
layer = nn.ConvTranspose3d(
            in_channels=768, out_channels=768,
            kernel_size=[2, 1, 1], dilation=[7, 1, 1], output_padding=0)
layer_norm = nn.LayerNorm(768, eps=0.1)

t = torch.ones(2, 768, 1, 3, 3)
t = layer(t)
t = t.permute(0, 2, 3, 4, 1).contiguous()
loss = layer_norm(t.contiguous())
loss.sum().backward()
```
```
Traceback (most recent call last):
  File "foo.py", line 12, in <module>
    t.sum().backward()
  File "/home/user/anaconda3/envs/env/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/user/anaconda3/envs/env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: ones needs to be contiguous
```

Thanks.

### Versions

PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.11.2
[conda] mypy                      0.910                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] torch                     1.10.1                   pypi_0    pypi
[conda] torchaudio                0.10.1                   pypi_0    pypi
[conda] torchvision               0.11.2                   pypi_0    pypi

**Comment by XiaobingSuper** [comment]
This issue has been fixed by https://github.com/pytorch/pytorch/pull/67829. and the master code can work well.

**Comment by ziyi-yang** [comment]
Thanks for the prompt reply. I tried the nightly installation and it worked. Look forward to the bug fix in the next official release.
