### ISSUE TITLE
[feature request] - ModuleList concatenation

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#70441]
## Issue description

Add concatenation for [`torch.nn.ModuleList`](https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html).

## Code example

```python3
from torch import nn

a = [nn.Module()]
b = [nn.Module()]
c = a + b
print(c)

a = nn.ModuleList([nn.Module()])
b = nn.ModuleList([nn.Module()])
c = a + b # TypeError: unsupported operand type(s) for +: 'ModuleList' and 'ModuleList'
print(c)
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by jbschlosser** [comment]
Hey @carlosgmartin, thanks for the request! I think this is a nice idea and we'd accept a PR implementing `ModuleList.__add__` appropriately.

**Comment by ProGamerGov** [comment]
Looks you'd only need to edit the code here: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/container.py#L145, and for the new tests I'm not sure where they should be added.

**Comment by jbschlosser** [comment]
A good place for testing the new functionality is `test_ModuleList()` in `test/test_nn.py`.

**Comment by ProGamerGov** [comment]
So, following the same procedure as `ModuleList.extend()` gives me this, but there may be a better way to concat the lists:

```
class ModuleList(Module):
    def __add__(self, other: 'ModuleList') -> 'ModuleList':
        r"""Concat two ModuleList instances.
        Args:
            other (ModuleList): The ModuleList instance to add on to
                to the existing instance.
        """
        if type(other) != type(self)) and other != type(self):
            raise TypeError("ModuleList concatination should only be "
                            "used with other ModuleList instances, but "
                            " got " + type(other).__name__)
        offset = len(self)
        for i in range(len(other)):
            self.add_module(str(offset + i), other[str(i)])
        return self
```

The above function is untested though.

**Comment by carlosgmartin** [comment]
@ProGamerGov Doesn't that modify in-place?

**Comment by jbschlosser** [comment]
Right, we'd want functional semantics for `ModuleList.__add__`; it should return a new `ModuleList` that represents the addition.

**Comment by jaketae** [comment]
Would the following be more in line with the specs?

```python
class ModuleList(Module):
    def __add__(self, other: 'ModuleList') -> 'ModuleList':
        r"""Concat two ModuleList instances.
        Args:
            other (ModuleList): modulelist to add
        """
        if not isinstance(other, ModuleList):
            raise TypeError("ModuleList concatenation should only be "
                            "used with another ModuleList instance, but "
                            " got " + type(other).__name__)
        offset = len(self)
        concat = ModuleList()
        for i in range(len(self)):
            concat.add_module(str(i), self[str(i)])
        for i in range(len(other)):
            concat.add_module(str(offset + i), other[str(i)])
        return concat
```

I also thought about using `copy.deepcopy` to produce a copy of `self`, then add modules in `other`, but I wasn't entirely sure if that would be preferable over the approach above.
