### ISSUE TITLE
Rocm builds are failing since Nov 12

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#70458]
### 🐛 Describe the bug

Following rocm nightly builds are failing since nov 12.
https://hud.pytorch.org/ci/pytorch/pytorch/nightly?name_filter=rocm

ci/circleci: binary_linux_manywheel_3_6m_rocm4_1_devtoolset7_nightly_build
ci/circleci: binary_linux_manywheel_3_7m_rocm4_1_devtoolset7_nightly_build
ci/circleci: binary_linux_manywheel_3_8m_rocm4_1_devtoolset7_nightly_build
ci/circleci: binary_linux_manywheel_3_9m_rocm4_1_devtoolset7_nightly_build

### Versions

CI/CD pipeline

cc @ezyang @seemethere @malfet @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by malfet** [comment]
Isn't it a duplicate of https://github.com/pytorch/pytorch/issues/69773 ?

**Comment by seemethere** [comment]
> Isn't it a duplicate of #69773 ?

It appears as though it is, closing in favor of https://github.com/pytorch/pytorch/issues/69773
