### ISSUE TITLE
`torch.RRELU` will crash when the input tensor is empty when running on cuda

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#70489]
### 🐛 Describe the bug

`torch.RRELU` will crash on the cuda when the input tensor is empty, like tensor([])

```python
import torch
arg_class = torch.nn.RReLU(0.1, 0.3).cuda()
tensor = torch.rand([0], dtype=torch.float32).cuda()
print(tensor)
arg_class(tensor)
# floating point exception (core dumped)
```

### Versions

pytorch: 1.10.1

@mruberry @albanD @soulitzer @zou3519 

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @ngimel

**Comment by dagitses** [comment]
High priority due to crash.
