### ISSUE TITLE
at::real for real tensors.

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#70495]
### 🚀 The feature

It'd be great that `at::real` would act as the identity function on real tensors.

An example is worth a thousand words (from https://github.com/pytorch/pytorch/pull/70253)
```cpp
auto dS = is_complex ? at::real(dP.diagonal(0, -2, -1)).clone()
                     : dP.diagonal(0, -2, -1).clone();

if (is_complex) {
    at::real(dP.diagonal(0, -2, -1)).zero_();
} else {
    dP.diagonal(0, -2, -1).zero_();
}
```
could be simplified to
```cpp
auto dS = at::real(dP.diagonal(0, -2, -1)).clone();
at::real(dP.diagonal(0, -2, -1)).zero_();
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by anjali411** [comment]
yup seems like a reasonable thing to do.

**Comment by nikitaved** [comment]
Related: https://github.com/pytorch/pytorch/issues/51210

**Comment by mruberry** [comment]
`real` on real tensors should probably return self, and if it'd be preferable for it to return a copy because of the scenarios we expect it to be used in then we should take a moment to consider our self vs copy policies

**Comment by anjali411** [comment]
We disabled `real` and `imag` for real tensors back when we were initially adding support for complex with the thought that we can always enable it if there's a real need which there seems to be as @Lezcano mentioned. Is anyone working on creating a PR for it? If not, I can go ahead and create one.

**Comment by Lezcano** [comment]
I don't think anyone is working on this afaik

**Comment by anjali411** [comment]
Yup this was added in https://github.com/pytorch/pytorch/pull/71718

**Comment by Lezcano** [comment]
Thank you!
