### ISSUE TITLE
torch.get_autocast_cpu_dtype() returns a new dtype (still?)

### ISSUE THREAD

**Issue by JonasGeiping** [pytorch/pytorch#70502]
### 🐛 Describe the bug

Hi, I have the following problem on pytorch 1.10.1:
```
>>> import torch
torch.__version__
'1.10.1'
>>> torch.get_autocast_cpu_dtype()
torch.bfloat16
>>> torch.get_autocast_cpu_dtype() is torch.bfloat16  # This should be true
False
>>> torch.get_autocast_gpu_dtype() is torch.half # Same here
False
```
This issue was already reported at:
https://github.com/pytorch/pytorch/issues/65786#issue-1010279411
but to my understanding, a fix was included in 1.10.1. The relevant PR is:

> Link to landed master PR (if applicable):
> * https://github.com/pytorch/pytorch/pull/66396
> Link to release branch PR:
> * https://github.com/pytorch/pytorch/pull/69620
> Criteria Category (_regression_):
> * https://github.com/pytorch/pytorch/issues/65786
> @seemethere: Merged
> _Originally posted by @seemethere in 
> https://github.com/pytorch/pytorch/issues/69100#issuecomment-989083394_

If I'm not misreading the release tracker, does the issue really persist?

### Versions

```
Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.9.2 (default, Mar  3 2021, 20:02:32)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-41-generic-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] functorch==0.0.1a0+d9f7805
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytorch-wavelets==1.3.0
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchtext==0.11.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.1          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-wavelets          1.3.0                    pypi_0    pypi
[conda] torchaudio                0.10.1               py39_cu113    pytorch
[conda] torchtext                 0.11.1                     py39    pytorch
[conda] torchvision               0.11.2               py39_cu113    pytorch
```

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by gchanan** [comment]
I was able to reproduce this on 1.10.1

**Comment by gchanan** [comment]
hmm this tag for 1.10.1 shows https://github.com/pytorch/pytorch/commit/302ee7bfb604ebef384602c56e3853efed262030, which would mean the following commits are missing from the release:
1) https://github.com/pytorch/pytorch/commit/3e412cd6dff635c0a58d85749e42e9ee1866a84e (this one)
2) https://github.com/pytorch/pytorch/commit/932ac7bd713fbac63d96d86571ba4529ad0423f0
3) https://github.com/pytorch/pytorch/commit/71f889c7d265b9636b93ede9d651c0a9c4bee191

I tried 2) as well, which is https://github.com/pytorch/pytorch/issues/68048 and it also is not fixed.

**Comment by gchanan** [comment]
CC @seemethere

**Comment by seemethere** [comment]
Oh wow I think I might've tagged the wrong commit during this release. We can plan on doing a quick 1.10.2 release to sort this out once everyone is back from PTO next week.

**Comment by vadimkantorov** [comment]
I think dtypes need to be compared using `==`, If I remember well checking tensor dtypes also must be done with `==`, `is` doesn't work - I think it's also the case for NumPy...

**Comment by JonasGeiping** [comment]
Oh sorry, I didn't know whether to use `is` or `==` here. The issue does persist for `==` though:
```
>>> torch.get_autocast_cpu_dtype() == torch.bfloat16
False
```
What I'm really trying to get working is that the `torch.autocast` code at https://github.com/pytorch/pytorch/blob/302ee7bfb604ebef384602c56e3853efed262030/torch/autocast_mode.py#L153 which is an `element in [element]` check

**Comment by vadimkantorov** [comment]
(my own opinion that it would be better if these dtypes were singletons and `is` worked too...)
