### ISSUE TITLE
DISABLED test_proper_exit (__main__.TestDataLoader)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70517]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_proper_exit%2C%20TestDataLoader)).

cc @ezyang @gchanan @zou3519 @bdhirsh @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Closed issue as this test has been fixed (shm filepath conflict)

**Comment by janeyx99** [comment]
@ejguan could you take a look?

**Comment by ejguan** [comment]
@janeyx99 Please correct me if I am wrong. The Error reported by pytorchbot is not related to `test_proper_exit`. `test_correct_module_names` is failed in the log.
