### ISSUE TITLE
Add docs for setting engines correctly for fbgemm/qnnpack

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#70512]
### 🐛 Describe the bug

We need to add an entry in https://pytorch.org/docs/stable/quantization.html#common-errors to talk about the time when user train the model with qnnpack settings and run it with fbgemm quantized engine, which would result in numerical errors (since fbgemm only works with reduce_range settings). This is common when running on mobile.

### Versions

master

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
I agree, we are tracking this in https://github.com/pytorch/pytorch/issues/46749, we have a plan to solve this automatically without needing extra user involvement.  Please take a look at the question we have tagged you in this document (Meta-only): https://docs.google.com/document/d/1jFvmgEkwEOkbCmeRf0w23sND7fZ8ql49JDVIE5DU8xE/edit#heading=h.a8eejvwtn4fb .
