### ISSUE TITLE
Unable to get attributes from Dataset

### ISSUE THREAD

**Issue by KinglittleQ** [pytorch/pytorch#70524]
### 🐛 Describe the bug

Unable to get attributes from Dataset class.

## How to reproduce:
```py
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self):
       self.n = 10

   def __getitem__(self, index):
       return index

    def __len__(self):
        return self.n

ds = MyDataset()
print(ds.n)

```
This would rase AttributeError.

## What I found

I found that Dataset only supports for getting functions since 1.10, because the `__getattr__` function is overloaded.
Is this a **bug** or **feature**?

```py
    def __getattr__(self, attribute_name):
        if attribute_name in Dataset.functions:
            function = functools.partial(Dataset.functions[attribute_name], self)
            return function
        else:
            raise AttributeError
```

### Versions

PyTorch 1.10

**Comment by jaketae** [comment]
I wasn't able to reproduce this on 1.10 nor the nightly build. Are you reporting an issue you ran into or analyzing the source code?

As far as I can tell, `__getattr__` doesn't get called when you call `ds.n`. As [documented](https://docs.python.org/dev/reference/datamodel.html#object.__getattr__), `__getattr__` gets called when an attribute lookup has not found the attribute in the usual places. So I think this is a non-issue!

**Comment by KinglittleQ** [comment]
Thanks!

**Comment by ankitabuntolia** [comment]
> I wasn't able to reproduce this on 1.10 nor the nightly build. Are you reporting an issue you ran into or analyzing the source code?
> 
> As far as I can tell, `__getattr__` doesn't get called when you call `ds.n`. As [documented](https://docs.python.org/dev/reference/datamodel.html#object.__getattr__), `__getattr__` gets called when an attribute lookup has not found the attribute in the usual places. So I think this is a non-issue!

so what's the outcome? I also did not add this in my custom dataset (as it's not part of the PyTorch tutorial for custom Dataset, but I am getting this error. How can I get rid of this error?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-10-d59eb5edbfee>](https://localhost:8080/#) in <module>()
----> 1 print(len(mydataset))
      2 print(mydataset[2])

1 frames
[/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py](https://localhost:8080/#) in __getattr__(self, attribute_name)
     81             return function
     82         else:
---> 83             raise AttributeError
     84 
     85     @classmethod

```

**Comment by jaketae** [comment]
The conclusion is that this is not a bug. My humble suggestion is that you open a separate issue containing your source code and the above traceback!

**Comment by ZihaoZheng98** [comment]
Wow, pytorch is interesting for overwriting this function. I have stubbed for such a long time. Fark.

**Comment by d4nh5u** [comment]
> > I wasn't able to reproduce this on 1.10 nor the nightly build. Are you reporting an issue you ran into or analyzing the source code?
> > As far as I can tell, `__getattr__` doesn't get called when you call `ds.n`. As [documented](https://docs.python.org/dev/reference/datamodel.html#object.__getattr__), `__getattr__` gets called when an attribute lookup has not found the attribute in the usual places. So I think this is a non-issue!
> 
> so what's the outcome? I also did not add this in my custom dataset (as it's not part of the PyTorch tutorial for custom Dataset, but I am getting this error. How can I get rid of this error?
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> [<ipython-input-10-d59eb5edbfee>](https://localhost:8080/#) in <module>()
> ----> 1 print(len(mydataset))
>       2 print(mydataset[2])
> 
> 1 frames
> [/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataset.py](https://localhost:8080/#) in __getattr__(self, attribute_name)
>      81             return function
>      82         else:
> ---> 83             raise AttributeError
>      84 
>      85     @classmethod
> ```

I found a similar problem on the Pytorch Forums.
Check the link here: https://discuss.pytorch.org/t/custom-dataset-attributeerror/147854
