### ISSUE TITLE
torch.multiprocessing.Queue can not pass Tensor after the putting sub-process exits

### ISSUE THREAD

**Issue by Chaser-wind** [pytorch/pytorch#70536]
### 🐛 Describe the bug

This is a toy program that uses a queue to get the tensors generated by its subprocess.
```python
import torch
from torch.multiprocessing import Queue, Process

def simple_agent(queue):
    for i in range(10):
        c = torch.Tensor([i]) # passing tensor will lead to error
        #c = i                # constant is OK
        queue.put(c)

def proc():
    queue = Queue(20)
    subp = Process(target=simple_agent, args=(queue,))
    subp.start()
    time.sleep(1) # make sure subprocess has exited
    # if do not sleep, result will be OK
    for i in range(10):
        v = queue.get()
        print(i, v)
```
Error message:
```
Traceback (most recent call last):                                                                    
File ".\src\train.py", line 218, in <module>                                                          
        proc()                                                                                            
File ".\src\train.py", line 184, in proc                                                              
        v = queue.get()                                                                                   
File "c:\program files\python38\lib\multiprocessing\queues.py", line 116, in get                      
        return _ForkingPickler.loads(res)                                                                 
File "C:\Users\admin\work\.py382\lib\site-packages\torch\multiprocessing\reductions.py", line 305, in rebuild_storage_filename                                                                            
        storage = cls._new_shared_filename(manager, handle, size)                                       
RuntimeError: falseINTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\MapAllocator.cpp":123, 
please report a bug to PyTorch. Couldn't open shared event: <0000018C6D14ABF2>, error code: <2>
```
Maybe the shared memory is incorrectly released when subprocess exits?

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: N/A

Python version: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 497.09
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.11.2+cu113
[conda] Could not collect

cc @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
You need to make sure that producer process kept life until all object from the mp queue is consumed. I agree that the error message here is terrible, but it will take entire feature to make add such resource counters.
