### ISSUE TITLE
DISABLED test_proper_exit (__main__.TestDataLoaderPersistentWorkers)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70547]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_proper_exit%2C%20TestDataLoaderPersistentWorkers)).

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Closed issue as this test has been fixed (shm filepath conflict)

**Comment by ejguan** [comment]
Closing this issue as https://github.com/pytorch/pytorch/pull/81660 has landed
