### ISSUE TITLE
DISABLED test_barrier_group (__main__.TestDistBackendWithSpawn)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70562]
Platforms: mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_barrier_group%2C%20TestDistBackendWithSpawn)).

cc @ezyang @gchanan @zou3519 @bdhirsh @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Looks like the stacktrace is gone, re-enabling to see if we can get it. but my feeling is these tests can be written better: https://github.com/pytorch/pytorch/issues/78885
