### ISSUE TITLE
[torch.autograd.Function] The gradient function of the same result, but different gradients are obtained

### ISSUE THREAD

**Issue by HLSS-Hen** [pytorch/pytorch#70578]
### 🐛 Describe the bug

[code](https://gist.github.com/HLSS-Hen/6acdc9b0d021e54f1024eecdb559c238)

I try to replace a function with a piecewise function to speed up.
This leads to a difference in the gradient, but I think the two functions should be equivalent.

The comment line needs to be modified to compare the differences; 
You need to provide a path to download or save MNIST

### Versions

> Collecting environment information...
> PyTorch version: 1.10.1
> Is debug build: False
> CUDA used to build PyTorch: 11.3
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 20.04.3 LTS (x86_64)
> GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
> Clang version: Could not collect
> CMake version: Could not collect
> Libc version: glibc-2.31
> 
> Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
> Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.31
> Is CUDA available: True
> CUDA runtime version: Could not collect
> GPU models and configuration: 
> GPU 0: NVIDIA GeForce RTX 2080 Ti
> GPU 1: NVIDIA GeForce RTX 3090
> 
> Nvidia driver version: 495.29.05
> cuDNN version: Probably one of the following:
> /usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.1
> /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.1
> /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.1
> /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.1
> /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.1
> /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.1
> /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.1
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.21.2
> [pip3] torch==1.10.1
> [pip3] torchaudio==0.10.1
> [pip3] torchvision==0.11.2
> [conda] blas                      1.0                         mkl    defaults
> [conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
> [conda] mkl                       2021.4.0           h06a4308_640    defaults
> [conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
> [conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
> [conda] mkl_random                1.2.2            py39h51133e4_0    defaults
> [conda] numpy                     1.19.5                   pypi_0    pypi
> [conda] numpy-base                1.21.2           py39h79a1101_0    defaults
> [conda] pytorch                   1.10.1          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
> [conda] pytorch-mutex             1.0                        cuda    pytorch
> [conda] torchaudio                0.10.1               py39_cu113    pytorch
> [conda] torchvision               0.11.2               py39_cu113    pytorch

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by Lezcano** [comment]
Shouldn't it be `hu = ((input< VT + A/2) && (input>VT-A/2)).float()/A` (note the `&&`)?

If not, could you test that the two functions are actually equivalent by passing a inputs to them?

**Comment by HLSS-Hen** [comment]
@Lezcano 

```
temp = torch.rand([100,100])-.5
x=((temp-VT).abs() < A/2).float()/A
y=((temp< VT + A/2) & (temp>VT-A/2)).float()/A
(x==y).float().mean()
```
this result is `1.0`, means all `x==y`, I think this is proved that they are equivalent.
Maybe you can help find inputs that make them unequal

If use `&&`, we will get `SyntaxError: invalid syntax`.

**Comment by Lezcano** [comment]
So there are a number of issues here. First, it's worth mentioning that the gradient you're implementing is wrong. Your function is locally constant (if you move a little bit the input the function will not change) so its gradient should be zero.

Now, assuming that you want to use some incorrect gradients (I would never advise to do so) then the gradients that you should get from two different implementations that are equivalent should be the same. It seems like the different gradients may be coming from some non-determinism in your program. If you are getting different gradients, I would try to isolate the problem to get a minimal reproducing example of 5-10 lines where this happens.

Now, this sort of issues are best discussed in the forum https://discuss.pytorch.org/, we usually use the github issues to track bugs.

**Comment by HLSS-Hen** [comment]
I found out the issue: the characteristics of the floating-point types.

```
import torch

SEED = 7
import random
random.seed(SEED)
torch.manual_seed(SEED)
temp = torch.rand([1000,1000])-.5
t=torch.rand([1000,1000])*7e-9
temp+=t
x=((temp-.5).abs() < .5).float()
y=((temp< 1) & (temp>0)).float()
(x==y).float().sum()
flag = False
for i in range(1000):
    for j in range(1000):
        if x[i,j]!=y[i,j]:
            flag=True
            break
    if flag:
        break
print(temp[i,j])
```
can help find a example shows two functions are not equal.




PS: The original code has been cancelled sharing
