### ISSUE TITLE
Provide an option to statically link MKL

### ISSUE THREAD

**Issue by chamibuddhika** [pytorch/pytorch#70587]
### 🐛 Describe the bug

It is useful to have a build option to statically link against MKL. FindMKL.cmake by default links against
the dynamic MKL libraries.  NCCL and CUDNN seems to have options for linking statically (i.e: USE_STATIC_NCCL and USE_STATIC_CUDNN). Similarly, we could have a USE_STATIC_MKL. 

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cputorchort
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.0
[pip3] torch==1.10.0+cputorchort
[pip3] torch-ort==1.9.0
[pip3] torchtext==1.10.0+cputorchort
[pip3] torchvision==1.10.0+cputorchort
[conda] Could not collect

**Comment by ashari4** [comment]
Hi, I am interested in contributing a fix. I've tagged a WIP branch #73069, and would appreciate any guidance/tips.
