### ISSUE TITLE
Make MAX_NAME_COLUMN_WIDTH modifiable in PyTorch profiler

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#70595]
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/blob/master/torch/autograd/profiler_util.py#L687

This value is often too low, and makes it unable to actually figure out what the profiled kernel is doing (since the part of the name mentioning the actual op is cut off).

Can we make this user configurable, or at least increase it?

I'd be glad to submit the PR myself :)

### Additional context

cc: @ngimel 

cc @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by ngimel** [comment]
That sounds good, however, consider the following: 
1) If you do postprocessing and analysis yourself, you can iterate over events and look at the names, using string table for this is not the best approach
2) for a table to look at, perhaps it makes sense to print only the last part of the qualified kernel name, not all of it? Increasing width makes table hard to read.
cc @robieta

**Comment by robieta** [comment]
I don't have any particular objection to tweaking this value, though I agree with @ngimel that for serious analysis you're going to want to use the underlying events.
