### ISSUE TITLE
test_jit_fuser_te not testing failures properly due to unexpected implicit string concatenation 

### ISSUE THREAD

**Issue by code-review-doctor** [pytorch/pytorch#70607]
### 🐛 Describe the bug

A comma is missing from line 2093

https://github.com/pytorch/pytorch/blob/1b66915f3916273edcf9dc5c3853bb31f21ed8f4/test/test_jit_fuser_te.py#L2092-L2096

This results in `'__rmatmul__'`  and `'frac'` being concatenated together to form `'__rmatmul__frac'` 

so the list evaluates to two items instead of three: `['__rmatmul__frac', 'matmul']`

The impact of this missing comma is `test_failures` and `test_failures` will not be testing `__rmatmul__` and `frac`:

https://github.com/pytorch/pytorch/blob/1b66915f3916273edcf9dc5c3853bb31f21ed8f4/test/test_jit_fuser_te.py#L2159

https://github.com/pytorch/pytorch/blob/1b66915f3916273edcf9dc5c3853bb31f21ed8f4/test/test_jit_fuser_te.py#L2170

The fix is of course to add the comma like so:

```py
 known_failures = [ 
     '__rmatmul__' ,
     'frac', 
     'matmul', 
 ] 
```

I can raise a PR for this?

### Versions

NA

**Comment by davidberard98** [comment]
@code-review-doctor it would be great if you had a PR for this!
