### ISSUE TITLE
test_numba_integration passes tuple into cuda instead of array

### ISSUE THREAD

**Issue by code-review-doctor** [pytorch/pytorch#70611]
### 🐛 Describe the bug

There is an (as far as I can tell) unwanted comma on line 314:

https://github.com/pytorch/pytorch/blob/1b66915f3916273edcf9dc5c3853bb31f21ed8f4/test/test_numba_integration.py#L313-L318

This makes the `numpy_ary` a tuple containing a numpy array rather than a numpy array ie.:
```py
In [3]: numpy.arange(6).reshape(2, 3).astype(numpy.float64)  # no comma at end
Out[3]: 
array([[0., 1., 2.],
       [3., 4., 5.]])

In [4]: numpy.arange(6).reshape(2, 3).astype(numpy.float64),  # comma at end
Out[4]: 
(array([[0., 1., 2.],
        [3., 4., 5.]]),)
```

This is a problem for the test because the tuple is then passed into `numba.cuda.to_device(numpy_ary)` and assertions are done on the output. It is possible the test is affected by the fact a tuple is passed in instead of a numpy array. Indeed, if in "live" a numpy array is passed in but in tests a tuple containing a numpy array is passed in then this reduces the confidence the tests give us as it's not "like live".

### Versions

NA

I can make a PR to fix this :)

cc @mruberry

**Comment by mruberry** [comment]
Hi @code-review-doctor, I agree that comma seems out of place and it's odd that the test passes. We would accept a PR removing it (if that really is the intention of the test).
