### ISSUE TITLE
Improve CI timeout debuggability

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#70645]
### 🚀 The feature, motivation and pitch

PyTorch CI experiences timeouts somewhat regularly (ASAN, multigpu). Whenever a job times out in CI, it is incredibly hard to debug. The current workflow is something like:
1. Notice that a job is timing out
2. Wait for it to time out (4.5hr on GHA), as rerunning isn't available until every job of a workflow is complete.
2. Rerun it so you could SSH into it (if it were on a PR. If it was on trunk, SSHing is not available).
3. Wait for it to build
4. Now SSH into the test job and wait for it to reach the right place in the code for you to investigate--if it even times out again.
5. If not, repeat this process.

What would be amazing if there were a skeleton SSH key available that would allow key people to get into and investigate any runner whenever so that the investigation could be done on the spot.

### Alternatives

Other options:
1. Make all runners ssh'able by default, which has its own security/resource downsides

cc @ezyang @gchanan @zou3519 @bdhirsh @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Suggested to remove `high priority` from this since we typically only use that label for things that will be triage reviewed later on.

This is already do-able within our current CI setup using the AWS session manager:

```bash
aws ssm start-session --target "<instance_id>" --region "<region>"
```

Example:

```bash
aws ssm start-session --target i-0099d5a07d34e8904 --region us-east-1
```

So as long as you have access to our AWS cli tools you should be able to utilize session manager to log in to whatever machine you want.

**Comment by seemethere** [comment]
Added a section in our wiki about SSM access:

https://github.com/pytorch/pytorch/wiki/Debugging-using-with-ssh-for-Github-Actions#for-meta-employees-debugging-using-aws-ssm

**Comment by janeyx99** [comment]
Oh that's great! Thanks for the documentation :)
