### ISSUE TITLE
torch.dot gives strange results 

### ISSUE THREAD

**Issue by jy1993** [pytorch/pytorch#7064]
<img width="528" alt="e6a64da7-bda7-47ab-9c42-ec09f1c44ca0" src="https://user-images.githubusercontent.com/18455572/39391291-829662cc-4ad3-11e8-91dd-7a04ecf795cd.png">

cc @VitalyFedyunin

**Comment by SsnL** [comment]
Is this on mac?

**Comment by apaszke** [comment]
Please update MKL and rebuild if you build from source. It’s a known bug in some older versions

**Comment by soumith** [comment]
additionally, if `numpy` is installed with `nomkl` feature enabled, then you might also see this bug.

**Comment by iondel** [comment]
I've met a similar problem (see #7692) and I just wanted to confirm that updating `mkl` did solve the problem for me.

**Comment by mruberry** [comment]
Confirmed again this does not reproduce. Closing due to age + lack of current repro.
