### ISSUE TITLE
DISABLED test_no_segfault (__main__.TestDataLoader)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70655]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_no_segfault%2C%20TestDataLoader)).

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by suo** [comment]
cc @VitalyFedyunin

**Comment by ejguan** [comment]
Closed issue as this test has been fixed (shm filepath conflict)
