### ISSUE TITLE
Build error: Undefined symbols for architecture x86_64: "_MPI_Comm_rank" on OS X

### ISSUE THREAD

**Issue by sunstarchan** [pytorch/pytorch#7065]
I'm trying to  build caffe2 by following the instruction from https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#brew-and-pip-install-path

but I get following build errors. my openmpi is installed by brew, and the version is 3.0.1

[ 83%] Linking CXX executable ../bin/mpi_test
Undefined symbols for architecture x86_64:
  "_MPI_Comm_rank", referenced from:
      caffe2::MPITest_TestMPIBroadcast_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIReduce_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIAllgather_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIAllreduce_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestInPlaceMPIAllreduce_Test::TestBody() in mpi_test.cc.o
  "_MPI_Comm_size", referenced from:
      caffe2::MPITest_TestMPIBroadcast_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIReduce_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIAllgather_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIAllreduce_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestInPlaceMPIAllreduce_Test::TestBody() in mpi_test.cc.o
  "_MPI_Finalize", referenced from:
      _main in mpi_test.cc.o
  "_MPI_Init_thread", referenced from:
      _main in mpi_test.cc.o
  "_ompi_mpi_comm_world", referenced from:
      caffe2::MPITest_TestMPIBroadcast_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIReduce_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIAllgather_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestMPIAllreduce_Test::TestBody() in mpi_test.cc.o
      caffe2::MPITest_TestInPlaceMPIAllreduce_Test::TestBody() in mpi_test.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/mpi_test] Error 1
make[1]: *** [caffe2/CMakeFiles/mpi_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by pjh5** [comment]
Do you need openmpi? Openmpi is used for parallel training. If you don't need it, turn it off by passing -DUSE_MPI=OFF to the cmake command.

If you do want to use openmpi, can you try uninstalling it from brew and installing it from openmpi's website?

**Comment by ezyang** [comment]
Some debugging of this issue was done in #11213; @Noirai suggested a workaround in https://github.com/pytorch/pytorch/issues/11213#issuecomment-469207422 which I haven't tested, but might be worth a try if you need to unblock on this.
