### ISSUE TITLE
torch.ravel does not return contiguous flattened tensor (as documented)

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#70657]
### 🐛 Describe the bug

```python
>>> import torch
>>> torch.ones(10)[::2].ravel().is_contiguous()
False
```

Link to the doc : https://pytorch.org/docs/stable/generated/torch.ravel.html

### Versions

master

cc @mruberry @rgommers

**Comment by rgommers** [comment]
Looks like a bug indeed. I wasn't sure what `ravel` was supposed to do, so checked numpy: it also explicitly says contiguous 1-D array returned, and enforced that:
```python
>>> x = np.ones(10)[::2]
>>> x.strides
(16,)
>>> x.ravel().strides
(8,)
```

**Comment by mruberry** [comment]
We would accept a PR fixing this! (The PR should add a test that ravel enforces this property.)

**Comment by khushi-411** [comment]
It is an exciting issue. May I give it a try? I would love to learn.
Thanks!

cc: @mruberry @rgommers  @kshitij12345

**Comment by mruberry** [comment]
> It is an exciting issue. May I give it a try? I would love to learn. Thanks!
> 
> cc: @mruberry @rgommers @kshitij12345

Anyone is welcome to address any issue that the community has decided to solve.
