### ISSUE TITLE
`torch.amax` and `torch.amin` will return random value if input tensor is empty

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#70674]
### 🐛 Describe the bug

`torch.amax` and `torch.amin` will return random value if input tensor is empty

```python
import torch
a = torch.rand([0, 3])
print(torch.amax(a))
# tensor(-1.8891e+26)
print(torch.amin(a))
# tensor(9.1477e-41)
```

By contrast, `torch.max` will raise an error

```python
import torch
a = torch.rand([0, 3])
print(torch.max(a))
# RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.
```

### Versions

pytorch: 1.10.1

**Comment by albanD** [comment]
cc @cpuhrsch do we want to re-use the same idea of "default" value that we have for masked Tensor here?

**Comment by cpuhrsch** [comment]
I think raising an error, like we do for max, is the right approach here. Are there any downsides to that?

**Comment by albanD** [comment]
Error sounds good to me as well! 
Is the behavior the same on CUDA?

**Comment by TestSomething22** [comment]
On CUDA, it will trigger an error "RuntimeError: CUDA error: device-side assert triggered", same as `index_select`.

**Comment by ngimel** [comment]
Tracked in #73905
