### ISSUE TITLE
Received `t == DeviceType::CUDAINTERNAL ASSERT FAILED at "../c10/cuda/impl/CUDAGuardImpl.h":24, please report a bug to PyTorch. `

### ISSUE THREAD

**Issue by damianr13** [pytorch/pytorch#70700]
### 🐛 Describe the bug

Today as I was working on a project I encountered the following error:  

```
Using device: cuda

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-39-cbf2e0361087> in <module>()
     58 
     59             gen_optimizer.zero_grad()
---> 60             gen_loss.backward()
     61             gen_optimizer.step()
     62 

1 frames

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    305                 create_graph=create_graph,
    306                 inputs=inputs)
--> 307         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    308 
    309     def register_hook(self, hook):

/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    154     Variable._execution_engine.run_backward(
    155         tensors, grad_tensors_, retain_graph, create_graph, inputs,
--> 156         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    157 
    158 

RuntimeError: t == DeviceType::CUDAINTERNAL ASSERT FAILED at "../c10/cuda/impl/CUDAGuardImpl.h":24, please report a bug to PyTorch. 
```
I am trying to implement the following paper: https://arxiv.org/abs/2107.03312

More probable than not, there is an issue with my implementation. Nevertheless, I decided to post this issue since judging from the error message my execution ended up in some part of your framework you wouldn't expect. 

My full code can be accessed here: https://pastebin.com/70ugL4Hz

I was running the file on Google Colab. Please find attached all the information about my environment. 

### Versions

PyTorch version: 1.10.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0+cu111
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111
[pip3] vector-quantize-pytorch==0.4.10
[conda] Could not collect

**Comment by damianr13** [comment]
Update: in my case, the issue was that I had a CPU tensor lost somewhere, in lines 476, 477 and 496. 
The statement `elements_orig = torch.maximum(torch.tensor(0), 1 - dx[i][-1].squeeze())`, contains `torch.tensor(0)` where I forgot to change the device. 

Still, the question remains. Is it normal that my execution reached that point? IMO it would be a lot more helpful if it would give out a more intelligible error sooner.

**Comment by ngimel** [comment]
This is fixed on master/nightlies in #66245

**Comment by albanD** [comment]
Closing since it is fixed in master.
@damianr13 feel free to re-open if you still see the issue after using the nightlies.

**Comment by lizhenstat** [comment]
@damianr13 Thanks a lot!!!  I encounter the same problem here and your solution works! 
Note: when using pytorch-1.9, the error message is the following 
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
while in pytorch-1.10, the error message is the same as yours.
