### ISSUE TITLE
C++ API masterthread

### ISSUE THREAD

**Issue by goldsborough** [pytorch/pytorch#7073]
Braindump of tasks for C++ API

- [x] Move autogradpp into PyTorch (including making sure its build and examples continue working)
- [x] Plop my naming and API changes from https://github.com/pytorch/pytorch/pull/6345 onto autogradpp
- [x] Implement variant-based forward (where the variant can accept more types by specializing some trait) -- based on https://github.com/ebetica/autogradpp/pull/70
- [x] Design construction interface in the case of many arguments (kwargs or builder)

@ebetica @ezyang @zdevito

**Comment by ebetica** [comment]
We should also generate files from the CMakeLists to reduce build times!

**Comment by goldsborough** [comment]
I'm currently working on getting rid of the `python setup.py build` step, which I think will lead to (1)

**Comment by soulslicer** [comment]
Good day,

May I know if all the features of the Python API is currently available in C++?  Also I would like to know a good resource where I can find some simple forward backward code in c++

**Comment by goldsborough** [comment]
You can check out https://pytorch.org/cppdocs/ and https://pytorch.org/tutorials/advanced/cpp_frontend.html
