### ISSUE TITLE
rocm jobs failing on master due to no space on device

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70751]
rocm jobs are failing on master with:
```
java.nio.file.FileSystemException: /var/lib/jenkins/workspace/pytorch-builds/pytorch-linux-bionic-rocm4.3.1-py3.6-test1: No space left on device
```

See for more examples: https://www.torch-ci.com/minihud?name_filter=rocm

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by jeffdaily** [comment]
No longer relevant.  rocm ci moved from jenkins to GHA.
