### ISSUE TITLE
DISABLED test_batch_sampler (__main__.TestDataLoaderPersistentWorkers)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70756]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_batch_sampler%2C%20TestDataLoaderPersistentWorkers)).

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Closed issue as this test has been fixed (shm filepath conflict)
