### ISSUE TITLE
Advice about the OMP parallel strategy when performing memory limited operations.

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#7087]
This issue is probably related to #3146. I raise this issue to share some of my experiments results, and hopefully, we could come up with a more CPU-efficient openmp solution for **memory bandwidth** limited operations. For **memory bandwidth** limited operations, I mean level-1 blas, and some util methods such as `index_select`, with a complexity of *O(N)*.

In such case, using too many OMP threads won't benefit much, especially when *HyperThreading* is enabled. The majority of CPU time is spent on waiting for memory access.
Here's my exp results on **Intel i7-6800K** (6 cores) when using `THTensor_(indexSelect)`:
```bash
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=2 python index_select.py
3.617363452911377s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=4 python index_select.py
2.15081524848938s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=8 python index_select.py
2.329015016555786s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=10 python index_select.py
2.3334872722625732s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=12 python index_select.py
2.3303682804107666s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=6 python index_select.py
2.334536075592041s
   (py35)  kys10@banana   ~/Workspace/playground 
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=4 python index_select.py
2.149383544921875s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=3 python index_select.py
2.5756006240844727s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=2 python index_select.py
3.624565362930298s
   (py35)  kys10@banana   ~/Workspace/playground  OMP_NUM_THREADS=1 python index_select.py
6.745104551315308s
```

code snippet:
```python
import time

import numpy as np
import torch

INDEX = 100000
NELE = 1000
a = torch.rand(INDEX, NELE)
index = np.random.randint(INDEX-1, size=INDEX*8)
b = torch.from_numpy(index)

res = a.index_select(0, b)
torch.cuda.synchronize()
start = time.time()
for _ in range(10):
    res = a.index_select(0, b)
torch.cuda.synchronize()
print('{}s'.format(time.time() - start))
```

**Comment by mingfeima** [comment]
@Stonesjtu All the CPU operations that rely on OpenMP has a threshold value `OMP_THRESHOLD`, below the threshold will launch serial calls otherwise parallel calls.
Somehow the threshold value is not a generic number, it is related to hardware, operation type (add and exp has diverse threshold value), contiguous memory access or not, etc. So typically it is impossible to make it suitable for every hardware for every operation.

This is the result on my CPU, the latest Xeon [skylake-8180](https://ark.intel.com/products/120496/Intel-Xeon-Platinum-8180-Processor-38_5M-Cache-2_50-GHz), you can access this type of CPU on AWS.
The performance pretty much saturates after OMP_NUM_THREADS=16 which probably means memory bandwidth is already peak.
```
[mingfeim@mlt-skx062 bench]$ OMP_NUM_THREADS=2 python test1.py
0.5540544986724854s
1.1089115142822266s
1.6616630554199219s
2.2161214351654053s
2.7701406478881836s
3.3247148990631104s
3.878696918487549s
4.433142185211182s
4.986017227172852s
5.540700435638428s
[mingfeim@mlt-skx062 bench]$ OMP_NUM_THREADS=4 python test1.py
0.29080915451049805s
0.5815765857696533s
0.8714227676391602s
1.1636464595794678s
1.454512596130371s
1.7470240592956543s
2.0370874404907227s
2.329000949859619s
2.61970591545105s
2.912081241607666s
[mingfeim@mlt-skx062 bench]$ OMP_NUM_THREADS=8 python test1.py
0.16283059120178223s
0.32903051376342773s
0.49161839485168457s
0.6557948589324951s
0.819077730178833s
0.9841725826263428s
1.1471338272094727s
1.3126704692840576s
1.4737608432769775s
1.640467882156372s
[mingfeim@mlt-skx062 bench]$ OMP_NUM_THREADS=16 python test1.py
0.13701176643371582s
0.2756643295288086s
0.41257262229919434s
0.5519325733184814s
0.6888313293457031s
0.8278582096099854s
0.9643378257751465s
1.1032180786132812s
1.2402722835540771s
1.379800796508789s
```

**Comment by Stonesjtu** [comment]
So is it possible to determine a suitable `OMP_NUM_THREADS` at run-time or compile-time for better efficiency? The openmp occupies all the CPU cores by default.

**Comment by apaszke** [comment]
We could probably have an optional benchmark mode, like we do for cuDNN, that would allow us to do some extra runtime tuning to find better parameters.

**Comment by ngimel** [comment]
Closing, parallelization changed a lot since.
