### ISSUE TITLE
Convert torch model metts error : ""number of dims don't match in permute

### ISSUE THREAD

**Issue by twotwoiscute** [pytorch/pytorch#70885]
### 🐛 Describe the bug

I am trying to convert torch model(.pt) to onnx format but meets unexpected error export failure: number of dims don't match in permute, I inspect into model structure and find out where the problem is and the module is shown below:

import onnx
import torch 
import torch.nn as nn
import torch.nn.functional as F 
 
class Integral(nn.Module): 

    def __init__(self, reg_max= 16):
        super(Integral, self).__init__()
        self.reg_max = reg_max
        self.register_buffer('project',
                             torch.linspace(0, self.reg_max, self.reg_max + 1))

    def forward(self, x):
        #x.shape (1, 3549, 68)
        x = F.softmax(x.reshape(x.shape[0], -1, self.reg_max + 1), dim = 2)
        #x.shape(1, 14196, 17)
        x = F.linear(x, self.project.type_as(x)).reshape(x.shape[0],-1, 4) 
        return  x

#model setting
model = Integral()
model.to(device) #cpu or gpu 
model.eval()
#input
x = torch.randn(1, 3549, 68).to(device)
f = opt.weights.replace('.pt', '.onnx')  # onnx filename

#opset_version=12
#opt.train =False
torch.onnx.export(model, x, f, verbose=False, opset_version=opt.opset_version, input_names=['images'],
                    training=torch.onnx.TrainingMode.TRAINING if opt.train else torch.onnx.TrainingMode.EVAL,
                    do_constant_folding=True,
                    dynamic_axes= None)

The code above gives error : RuntimeError: number of dims don't match in permute and I don't see any wrong with tensor operation in foward . Can anyone help me out with this? Thanks!

### Versions

```
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.27

Python version: 3.8.10 (default, May 19 2021, 18:05:58)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.0
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] faiss-cpu                 1.7.1           py3.8_h2a577fa_1_cpu    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libfaiss                  1.7.1            h2bc3f7f_1_cpu    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.20.3           py38hf144106_0  
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch                   1.8.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu102    pytorch
```

**Comment by twotwoiscute** [comment]
The problem has been solved, I change

`self.register_buffer('project'), torch.linspace(0, self.reg_max,self.reg_max + 1) `
to
`self.project = torch.arange(0, self.reg_max + 1 ).float() `
and everything works fine.

**Comment by changzhonghan** [comment]
The case is the [F.linear] expected the weight has the shape of [channel-out X channel-in]; But , the [project] has the shape of [channel-out]. so U can fix this bug : x = F.linear(x, self.project.type_as(x).reshape(-1, 1)).reshape(x.shape[0],-1, 4)
