### ISSUE TITLE
Fix docker update race condition

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#70881]
### 🐛 Describe the bug

At the moment, docker images are rebuilt only for commits that modify docker folder and are assumed to be available by the time next commit is pushed, which might not be the case if base job have failed or CI is executed out of order

For example, see https://github.com/pytorch/pytorch/commit/395f85377022aa40e9e0e87a348d535d072a7659 (which at the time of writing still have docker build jobs in the queue) and https://hud.pytorch.org/commit/pytorch/pytorch/b283b1de39d887518e1bd627d83a54308fd7dd98 which fails because updated docker images are yet not available

Availability of the previous image is checked in
https://github.com/pytorch/pytorch/blob/8e6d1738a41cb28c36db3dc5e10fd812417673de/.github/templates/common.yml.j2#L251-L256

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Original assumption for the change were that commit hash sum will be the same between PR and master commit, but this is often not the case

**Comment by janeyx99** [comment]
Potential fix: instead of failing at that step, simply build the docker again with a flag to NOT push. This way, we won't have the issue of stampede-pushing and these jobs will not fail on CI.

**Comment by suo** [comment]
This is done, right?

**Comment by seemethere** [comment]
Yup, closed by #78186
