### ISSUE TITLE
[docs] Incorrect example for torch.Tensor.new_zeros()

### ISSUE THREAD

**Issue by wongjoel** [pytorch/pytorch#7088]
The example given in the docs for new_zeros() is actually an example for new_ones(). Should be a trivial fix. (Sorry, not quite sure what the etiquette/process is for fixing small errors like these). Thanks.

https://github.com/pytorch/pytorch/blob/bc62645e4ce2ad8f6e05892e22f5df73565655a0/torch/_tensor_docs.py#L124-L144

The example should read:
```
 Example:: 
  
     >>> tensor = torch.tensor((), dtype=torch.float64) 
     >>> tensor.new_zeros((2, 3)) 
     tensor([[ 0.,  0.,  0.], 
             [ 0.,  0.,  0.]], dtype=torch.float64)
```

**Comment by zou3519** [comment]
Thanks for the catch, @wongjoel! If you'd like to take a stab at fixing it, you can fork the pytorch repo and contribute a pull request. Otherwise, I can make the replacement.

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/7128
