### ISSUE TITLE
`libtorch.a` is not in pytorch `static` zip archives

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#70898]
The diagnosis in the discussion item still applies to 1.10.1:

```
Checking existense of 'libtorch.a'
- libtorch-cxx11-abi-static-with-deps-1.9.1%2Bcu102.zip
- libtorch-cxx11-abi-static-with-deps-1.10.1%2Bcu102.zip
```

cc: @seemethere 

# Discussion item

Interestingly enough, it appears as though we haven't regressed, we just never had a `libtorch.a` in our `static` zip archives:

Script used to test:
```bash
#!/usr/bin/env bash

set -eou pipefail

echo "Checking existense of 'libtorch.a'"

for version in "1.2.0" "1.3.1" "1.4.0" "1.5.1" "1.6.0"; do
    filename="libtorch-cxx11-abi-static-with-deps-${version}%2Bcu92.zip"
    if ! curl -fsSL -O "https://download.pytorch.org/libtorch/cu92/${filename}"; then
        echo "https://download.pytorch.org/libtorch/cu92/${filename}" not found
        exit 1
    fi
    if ! unzip -l "${filename}" | rev | cut -d' ' -f1 | rev | grep 'libtorch.a$' >/dev/null 2>/dev/null; then
        echo -n '- '
    else
        echo -n '+ '
    fi
    echo "${filename}"
    rm -f "${filename}"
done
```

Results:
```
❯ bash check_libtorch_static.sh
Checking existense of 'libtorch.a'
- libtorch-cxx11-abi-static-with-deps-1.2.0%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.3.1%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.4.0%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.5.1%2Bcu92.zip
- libtorch-cxx11-abi-static-with-deps-1.6.0%2Bcu92.zip
```

_Originally posted by @seemethere in https://github.com/pytorch/pytorch/issues/25699#issuecomment-700064881_

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
Considering CUDA-11.x binaries sizes I wonder if static linking using stock libraries makes much sense here (as linking is likely to fail with R_X86_64_GOTPCREL overflows)

**Comment by pearu** [comment]
I don't have first-hand experience of linking failures of static CUDA and torch libraries but if the sizes of these libraries reach the 2GB limit, I would presume that using `-mcmodel=large` will help overcome this issue?

**Comment by lazyoracle** [comment]
Are there clear instructions on how to do this locally? I am okay with not have pre-built static binaries for `libtorch` if I can build them myself. I did not find any instructions in the main docs regarding building static binaries from source. Can someone please direct me to where I should look in `pytorch/builder` to try to do this locally?
