### ISSUE TITLE
Bitwise shifts are broken in some cases if shift is greater than bit size

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#70904]
Left- or right-shifting the bits of an integer tensor by equal or more than the number of bits of the dtype, should always result in `0`. This is not the case for some shifts independent of the `dtype`:

```python
import torch

dtype = torch.uint8
info = torch.iinfo(dtype)
input = torch.tensor(info.max, dtype=dtype)

for other in range(info.bits, 100):
    other = torch.full_like(input, other)

    result_left = input << other
    if result_left != 0:
        print(f"{int(input)} << {int(other)}: {int(result_left)}")

    result_right = input >> other
    if result_right != 0:
        print(f"{int(input)} >> {int(other)}: {int(result_right)}")
```

```
255 << 32: 255
255 >> 32: 255
255 << 33: 254
255 >> 33: 127
255 << 34: 252
255 >> 34: 63
255 << 35: 248
255 >> 35: 31
255 << 36: 240
255 >> 36: 15
255 << 37: 224
255 >> 37: 7
255 << 38: 192
255 >> 38: 3
255 << 39: 128
255 >> 39: 1
255 << 64: 255
255 >> 64: 255
255 << 65: 254
255 >> 65: 127
255 << 66: 252
255 >> 66: 63
255 << 67: 248
255 >> 67: 31
255 << 68: 240
255 >> 68: 15
255 << 69: 224
255 >> 69: 7
255 << 70: 192
255 >> 70: 3
255 << 71: 128
255 >> 71: 1
255 << 96: 255
255 >> 96: 255
255 << 97: 254
255 >> 97: 127
255 << 98: 252
255 >> 98: 63
255 << 99: 248
255 >> 99: 31
```

**Comment by albanD** [comment]
@pmeier would have some time to check why this happens by any chance?

**Comment by pmeier** [comment]
The behavior is not present on CUDA.

**Comment by pmeier** [comment]
This comes down to [undefined behavior](https://en.cppreference.com/w/cpp/language/operator_arithmetic):

> ### Bitwise shift operators
> ...
> In any case, if the value of the right operand is negative or is greater or equal to the number of bits in the promoted left operand, the behavior is undefined.

Given that the kernel implementation is the same for CPU

https://github.com/pytorch/pytorch/blob/b10381f42db8ff259a370b6444faf641e58196a3/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp#L350

and CUDA

https://github.com/pytorch/pytorch/blob/84326ef059cd1b321e37d13de8717cef26ab5e38/aten/src/ATen/native/cuda/BinaryShiftOpsKernels.cu#L30

it is "luck" that it is working on CUDA and mostly working on CPU.

---

A possible fix would be to simply check if the second operand is larger than the number of bits of the first after type promotion. If yes, return `0` and otherwise perform the shift.

**Comment by albanD** [comment]
Interesting UB. Note that numpy does return 0 consistently so we want to do something similar to https://github.com/numpy/numpy/blob/d850fc9c47ec1399be64eb716e2731b2270c66be/numpy/core/src/umath/loops.c.src#L652-L660

**Comment by bjhargrave** [comment]
I have made https://github.com/pytorch/pytorch/pull/96659 to fix this issue.
