### ISSUE TITLE
`finfo(...).tiny` should be aliased to `finfo(...).smallest_normal`

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#70909]
The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/data_type_functions.html?highlight=smallest_normal#finfo-type) that the

> smallest positive floating-point number with full precision

should be called `smallest_normal`. We are currently calling it [`tiny`](https://pytorch.org/docs/master/type_info.html#torch.torch.finfo). See [this discussion](https://github.com/data-apis/array-api/pull/129#discussion_r577993658) for the motivation behind this.

cc @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

**Comment by mruberry** [comment]
We would accept this PR.
