### ISSUE TITLE
make `torch.(ceil|floor|round|trunc)` no-ops for integer inputs

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#70918]
The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/elementwise_functions.html?highlight=bitwise_left_shift#id38) that `torch.(ceil|floor|round|trunc)` should be no-ops for integer inputs. We currently have no functionality implemented for these cases

```python
>>> t = torch.tensor(0)
>>> torch.ceil(t)
RuntimeError: "ceil" "_vml_cpu" not implemented for 'Long'
>>> torch.floor(t)
RuntimeError: "floor" "_vml_cpu" not implemented for 'Long'
>>> torch.round(t)
RuntimeError: "round" "_vml_cpu" not implemented for 'Long'
>>> torch.trunc(t)
RuntimeError: "trunc" "_vml_cpu" not implemented for 'Long'
```

cc @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

**Comment by mruberry** [comment]
We can return `self` for these cases (and should clearly document that we do so).

**Comment by HaoZeke** [comment]
@kshitij12345 brought up a concern about the correctness of this behavior in the context of JIT and tracing. Is returning `self` still considered to be the best approach?

**Comment by rgommers** [comment]
This was fixed in gh-85144, so closing.
