### ISSUE TITLE
Tests in test_nn fail when compiled without LAPACK support 

### ISSUE THREAD

**Issue by lithuak** [pytorch/pytorch#70912]
### 🐛 Describe the bug

Running python `test/run_test.py` fails in `test_nn` module when PyTorch is compiled w/o LAPACK support.

The expected behavior is to skip tests for LAPACK-relative functionality in such case.

The full error log is [here](https://gist.github.com/lithuak/ec5f36059015f7c9b33cd4c50efad06e):

My proposition is to fix this by adding the `@skipIfNoLapack` decorator to failing test as itis already done with some other test in the same module. 

I'll add the PR with proposed fix.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.0

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 460.91.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.11.0a0+gitd1dbcb1
[pip3] torchvision==0.11.1
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
Let's discuss in the PR how we want to solve that.
