### ISSUE TITLE
type promotion is broken in `torch.where`

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#70923]
The [array API specification stipulates](https://data-apis.org/array-api/latest/API_specification/searching_functions.html?highlight=where#id7) that the return value of `torch.where` should undergo regular type promotion. Currently we do not support different dtypes for `x` and `y`:

```python
import torch

condition = torch.tensor([False, True])
x = torch.ones(2, dtype=torch.float32)
y = torch.zeros(2, dtype=torch.float64)

torch.where(condition, x, y)
```

```
RuntimeError: expected scalar type float but found double
```

Note that the error message is also misleading since we deal with 1d tensors here. 

cc @nairbv @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/9190, https://github.com/pytorch/pytorch/pull/62084 (fixing this probably)

**Comment by rgommers** [comment]
Agreed, it's the same as gh-9190. Let's close this as a duplicate. I'll move the label to gh-9190. Thanks @pmeier, @vadimkantorov.
