### ISSUE TITLE
[ppc64le pytorch]  test_cpu (test_utils.TestFFI) fails 

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#7093]
test failing on ppc64le.   

Could be related to #6913  that was merged 2 days ago

test_single_drop (test_utils.TestDataLoader) ... ok
test_single_keep (test_utils.TestDataLoader) ... ok
test_cpu (test_utils.TestFFI) ... terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid argument 1: expected 3D tensor at /home/jenkins/pytorch/aten/src/TH/generic/THTensorMath.cpp:2230
Traceback (most recent call last):
  File "test/run_test.py", line 354, in <module>
    main()
  File "test/run_test.py", line 346, in main
    raise RuntimeError(message)
RuntimeError: test_utils failed! Received signal: SIGIOT
[pytorch-linux-cuda9-cudnn7-py3-build-test-gpu] $ /bin/bash +x /tmp/jenkins3467137355149778967.sh
Exited with exit status 1
[pytorch-linux-cuda9-cudnn7-py3-build-test-gpu] $ /bin/sh -xe /tmp/jenkins7824832211748384455.sh
[pytorch-linux-cuda9-cudnn7-py3-build-test-gpu] $ /bin/sh -xe /tmp/jenkins7294624988814926094.sh
Build step 'Run job on SGE' marked build as failure
Finished: FAILURE

**Comment by avmgithub** [comment]
I just looked at previous successful test logs and it looks like these tests were being skipped before:
test_cpu (test_utils.TestFFI) ... skipped 'ffi tests require cffi package'
test_gpu (test_utils.TestFFI) ... skipped 'ffi tests require cffi package'

**Comment by avmgithub** [comment]
Seems like it only happens when running:
python -m unittest -v test_utils.TestFFI.test_cpu,  
it fails in https://github.com/pytorch/pytorch/blob/master/test/test_utils.py#L388-L389

python -m unittest -v test_utils.TestFFI.test_gpu <<<  passes fine

**Comment by avmgithub** [comment]
I did a little more digging.  Basically the stack of the abort is as follows:

"aten/src/ATen/Context.cpp"   argErrorHandler  30
 aten/src/TH/THGeneral.cpp:122    _THArgCheck
generic/THTensorMath.cpp:2239 THFloatTensor_addbmm
_cpulib.c:588  _cffi_f_bad_func
at torch/csrc/Module.cpp:149  THPModule_safeCall

the module extension is called with a bad argument and the _THArgCheck throwsn runtime exception.  But the exception never gets propagated back to python.    I even tried to add -fexceptions flag to the compile arguments at :  https://github.com/pytorch/pytorch/blob/master/torch/utils/ffi/__init__.py#L179    but that did not help.   

The other thing I tried was to add a try/catch block to https://github.com/pytorch/pytorch/blob/7c70c3bdca149918e7c410e75b374e546cb5f52d/aten/src/TH/generic/THTensorMath.cpp#L2235  and that eliminated the abort , but the test still fails because I am not setting the torch.FatalError correctly.  And that may not be the correct way to fix this anyway.

@soumith @apaszke Any pointers to how this can fixed is appreciated.

**Comment by ezyang** [comment]
@avmgithub Yeah, this is a feature which "accidentally works sometimes" and you have hit a place where it doesn't work. The essential problem is that we install an exception handler to throw exceptions from C code, but this requires the C frames to be laid out a way such that the unwinder that PyTorch is built with to be able understand it. If the C frames are compiled by a different compiler than the stdc++ runtime PyTorch is linked with, the unwinder doesn't necessarily know how to deal with it.

I'd recommend disabling this test on PPC for now.

**Comment by ezyang** [comment]
(The test was previously not running at all due to a bug.)

**Comment by avmgithub** [comment]
I tested on ppc64le and it skips the test and all other test are passing .  closing
