### ISSUE TITLE
DISABLED test_multiple_dataloaders (__main__.TestDataLoaderPersistentWorkers)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70947]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_multiple_dataloaders%2C%20TestDataLoaderPersistentWorkers)).

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Closed issue as this test has been fixed (shm filepath conflict)
