### ISSUE TITLE
`_dp_init_subclass` fails on `typing.Annotated`

### ISSUE THREAD

**Issue by Jasha10** [pytorch/pytorch#70959]
### 🐛 Describe the bug

Runtime type checking performed by e.g. `IterableDataset` fails when `typing.Annotated` is used. Here is an example of code that fails:
```python
from typing import Annotated, Iterator

from torch.utils.data import IterableDataset


class MyIterableDataset(IterableDataset[Annotated[int, "foo"]]):
    def __iter__(self) -> Iterator[Annotated[int, "foo"]]:
        yield 123


ds = MyIterableDataset()
```
Output:
```text
$ python tmp.py
Traceback (most recent call last):
  File "/home/jbss/pysc/tmp.py", line 8, in <module>
    class MyIterableDataset(IterableDataset[Annotated[int, "foo"]]):
  File "/home/jbss/miniconda3/envs/pysc/lib/python3.9/site-packages/torch/utils/data/_typing.py", line 273, in __new__
    return super().__new__(cls, name, bases, namespace, **kwargs)  # type: ignore[call-overload]
  File "/home/jbss/miniconda3/envs/pysc/lib/python3.9/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/home/jbss/miniconda3/envs/pysc/lib/python3.9/site-packages/torch/utils/data/_typing.py", line 377, in _dp_init_subclass
    raise TypeError("Expected return type of '__iter__' as a subtype of {}, but found {}"
TypeError: Expected return type of '__iter__' as a subtype of typing.Annotated[int, 'foo'], but found int for MyIterableDataset
```

### Versions

PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:40:17)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080
GPU 1: GeForce RTX 2080

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.940+dev.ba0e9d6427fa15a2c3420d4427e88b99514d22f9
[pip3] mypy-extensions==0.4.3
[pip3] mypy-protobuf==3.1.0
[pip3] numpy==1.22.0
[pip3] torch==1.10.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mypy                      0.940+dev.ba0e9d6427fa15a2c3420d4427e88b99514d22f9          pypi_0    pypi
[conda] mypy-protobuf             3.1.0                    pypi_0    pypi
[conda] mypy_extensions           0.4.3            py39hf3d152e_4    conda-forge
[conda] numpy                     1.22.0           py39h91f2184_0    conda-forge
[conda] pytorch                   1.10.1          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchvision               0.11.2               py39_cu113    pytorch

cc @SsnL @VitalyFedyunin @ejguan @NivekT @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by ejguan** [comment]
Thanks for submitting the issue. Confirm this is a bug, and a fix has landed into master. Could you please use nightly release to bypass it?

**Comment by Jasha10** [comment]
I can confirm that it is fixed on nightly. Thanks!!
