### ISSUE TITLE
fx2trt tests not running?

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#70969]
I'm trying to piece together what is going on with our fx2trt tests. As far as I can tell, https://github.com/pytorch/pytorch/pull/70203 implemented an entirely separate job config with no sharding that runs all our tests, but DOESN'T run fx2trt tests. 

Here is an example recent job from master: https://github.com/pytorch/pytorch/runs/4732473836?check_suite_focus=true. If you search the raw logs, there are no fx2trt tests run at all. This job takes almost 2 hours because it's not sharded and runs a completely redundant set of tests, wasting capacity and time.

Recently, https://github.com/pytorch/pytorch/pull/70658 was landed. I'm not sure what this PR does from the description. It looks like it enables fx2trt tests on our default shards. If we're doing this, why do we have a separate fx2trt job? Can we delete the separate job? Furthermore, fx2trt are not enabled by this PR either, and are not currently running anywhere in master as far as I can tell.

Something seems seriously off; am I missing something?

cc @ezyang @gchanan @zou3519 @bdhirsh @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
Also the second diff was not reviewed in GitHub or by anyone who is marked as a CI owner, despite purporting to affect how we run all linux gpu jobs. cc @houseroad and @wushirong what's going on here?

**Comment by janeyx99** [comment]
The very first PR seemed to do the right thing where it adds a fx2trt config that runs for 1m50s and the tests are not run in the shards.
https://hud.pytorch.org/pr/pytorch/pytorch/70203

The second PR does not actually remove the config nor does it actually enable the fx2trt tests because of this line from the first PR 
https://github.com/pytorch/pytorch/pull/70203/files#diff-e72503c9e3e8766e2d1bacf3fad7b88aa166e0e90a7e103e7df99357a35df8d7R897 

We should probably revert the second PR

**Comment by suo** [comment]
whatever logic the first PR had to gate the execution of tests in the fx2trt config is broken, so we should revert that as well if we can't get a fix tomorrow

**Comment by janeyx99** [comment]
Oh this is wack.

The committed changes for the first PR do NOT match up with the intended changes in the diff. Namely, the fx2trt changes in test.sh are completely missing https://github.com/pytorch/pytorch/commit/31c7e5d62936a41db2758d2786b6e77dff35327c

**Comment by suo** [comment]
Bisecting manually, it looks like: https://github.com/pytorch/pytorch/commit/066c9ff08f49acb9763381e4bdee6185dfc61871  runs all the tests, but https://github.com/pytorch/pytorch/commit/5e113eb24d7ab8aea63c01eed0cb173e1fd690e5 doesn't. I'll dig further later

**Comment by janeyx99** [comment]
@suo I'm okay with either
1. get rid of special config and run tests on all existing jobs
2. use special config and gate the jobs correctly

I think #1 makes more sense and is simpler in this situation.

**Comment by malfet** [comment]
I think special config is necessary as `fx2trt` tests can only run if CUDA is installed and proprietary TensorRT library is present.

**Comment by janeyx99** [comment]
I believe this has already been fixed and is no longer relevant--closing.

Reopen if it is otherwise.
