### ISSUE TITLE
Error in `Tensor.ravel` documentation

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#70975]
### 🐛 Describe the bug

In the [documentation](https://pytorch.org/docs/stable/generated/torch.Tensor.ravel.html?highlight=ravel#torch.Tensor.ravel) of `Tensor.ravel`, "Tensor.ravel(input) → Tensor". But `Tensor.ravel` does not need any argument

```python
import torch
a = torch.rand([2, 2])
a.ravel()
# succeed
b = torch.rand([2, 2])
a.ravel(b)
# TypeError: _TensorBase.ravel() takes no arguments (1 given)
```

### Versions

It should be "Tensor.ravel() → Tensor"

cc @brianjo @mruberry

**Comment by dagitses** [comment]
Mike, note that it looks as though Khushi already has a fix for this.

**Comment by mruberry** [comment]
Thanks for reporting this issue, @TestSomething22. This should now be fixed!
