### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.nn.modules.instancenorm'

### ISSUE THREAD

**Issue by almarri0** [pytorch/pytorch#70984]
### 🐛 Describe the bug

I have been experiencing this error for sometime and I can't understand how it happens, but when I import torch or import torchvision I keep on getting this error, the only way to get around it is to do a clean uninstall to conda and install it again, along with creating the environments all over again and installing their each library respectively,

`>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torch/__init__.py", line 280, in <module>
    from .functional import *
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torch/functional.py", line 2, in <module>
    import torch.nn.functional as F
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F401
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/modules/__init__.py", line 17, in <module>
    from .instancenorm import InstanceNorm1d, InstanceNorm2d, InstanceNorm3d
ModuleNotFoundError: No module named 'torch.nn.modules.instancenorm'
`

What I noticed is when I do import torch followed by an import torchvision I get the following error,

`>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torchvision/models/__init__.py", line 1, in <module>
    from .alexnet import *
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torchvision/models/alexnet.py", line 1, in <module>
    import torch
  File "/home/salem/anaconda3/envs/trades/lib/python3.6/site-packages/torch/__init__.py", line 83, in <module>
    __all__ += [name for name in dir(_C)
NameError: name '_C' is not defined
`

I wanted to note that I have experience this on both python3.6 and python3.8 and after doing a clean install I am able to use torch libraries few times before being striked by the same error again

### Versions

yTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-44-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 470.86
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py36he8ac12f_0  
[conda] mkl_fft                   1.3.0            py36h54f3939_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.19.2           py36h54aff64_0  
[conda] numpy-base                1.19.2           py36hfa32c7d_0  
[conda] pytorch                   1.3.1           py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py36_cu100    pytorch

__________________________________________________________

Note that when the library is working, I can obtain the following version:

PyTorch version: 1.3.1
Is debug build: False
CUDA used to build PyTorch: 10.0.130
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-44-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 470.86
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.3.1
[pip3] torchvision==0.4.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.0.130                      0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py36he8ac12f_0  
[conda] mkl_fft                   1.3.0            py36h54f3939_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.19.2           py36h54aff64_0  
[conda] numpy-base                1.19.2           py36hfa32c7d_0  
[conda] pytorch                   1.3.1           py3.6_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py36_cu100    pytorch

cc @malfet @seemethere @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @fmassa @vfdev-5 @pmeier @ezyang

**Comment by dagitses** [comment]
Does this happen consistently every time you import torch followed by torchvision?

**Comment by almarri0** [comment]
> Does this happen consistently every time you import torch followed by torchvision?
> @dagitses 

No, the issue is caused for another reason which I am not sure yet how to reproduce, but occurs often every several time I use either imports. The reason I mentioned both imports is because it points out to a more specific error when either second library is imported.

After reviewing both versions, before and after the issue takes place I noticed there is a difference of results between the four first parameters, CUDA used to build PyTorch becomes N/A for example.

**Comment by salemalmarri** [comment]
I solved this issue by uninstalling/installing torch,

#1 pip list
#2 Identify which torch version you have
#3 pip uninstall torch
#4 pip install torch==1.11.0 (assuming you replace version 1.11.0 by the number you have)

**Comment by albanD** [comment]
Closing this as this seems to be a botched install.

**Comment by Mehrdadgpt** [comment]
### **You also named your Python file (Torch), Change it and I think it will be good.**
