### ISSUE TITLE
Gather tensor in different gpu

### ISSUE THREAD

**Issue by 7zhanghao** [pytorch/pytorch#70985]
### 🐛 Describe the bug

It seems that dist.all_gather can only be used when tensors in different gpu have the same size. What should i do if they not?
`a = torch.ones(2)`
`b = torch.ones(3)`
`tensor_list = [torch.zeros_like(a), torch.zeros_like(b)]`
`tensor`
`tensor([1,2]) #Rank 1`
`tensor([1,2,3]) #Rank 2`
`dist.all_gather(tensor_list, tensor)`
`Runtime error: All tensor operands to scatter/gather  must have the same number of elements`

### Versions

1.7

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/.

**Comment by vanpersie32** [comment]
@zhhao1 have you solved the problem?

**Comment by zhhao1** [comment]
This can be done dynamically, without specifying the length at the beginning of the training. I first collect the lengths of different GPUs (size: 1). Then I pad the tensor in different GPUs to the max length. After that, it can be collected normally.

**Comment by zhhao1** [comment]
> @zhhao1 have you solved the problem?

This can be done dynamically, without specifying the length at the beginning of the training. I first collect the lengths of different GPUs (size: 1). Then I pad the tensor in different GPUs to the max length. After that, it can be collected normally.
