### ISSUE TITLE
no wheel for Python 3.10.1

### ISSUE THREAD

**Issue by kinestetika** [pytorch/pytorch#70994]
### 🐛 Describe the bug

"pip install torch" does not work with python 3.10,1:

(python-env) [kinestetika@ghost python-env]$ python --version
Python 3.10.1
(python-env) [kinestetika@ghost python-env]$ pip install torch
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
 

### Versions

(python-env) [kinestetika@ghost python-env]$ python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.1.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.15.12-arch1-1-x86_64-with-glibc2.33
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 760
Nvidia driver version: 470.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @seemethere @malfet

**Comment by dagitses** [comment]
High pri since Python 3.10.1 ought to be supported.

**Comment by seemethere** [comment]
This is a duplicate issue. Closing in favor of https://github.com/pytorch/pytorch/issues/66424
