### ISSUE TITLE
CI: Removing Network Connectivity Risks

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71003]
### 🚀 The feature, motivation and pitch

A lot of our CI flakiness is due to failed network access, and stamping those out would yield the next big increase in stability. An idea would be to close up our CI network access by routing everything through a proxy and adding retries when necessary.

Some other tasks that would help with this are (copied over from https://github.com/pytorch/pytorch/issues/69540)
- [x] Bake as many dependencies as we can in the AMI (windows) https://github.com/pytorch/pytorch/issues/73755
- [x] Bake as many dependencies as we can into the Docker images (linux)
    - [x] Miniconda
    - [x] conda/pip install commands (will expand which ones later)
    - [x] Things in the step: Install NVIDIA driver, NVIDIA runtime
      - Example failure https://github.com/pytorch/pytorch/runs/3972904356?check_suite_focus=true
   
- [ ] Add retry logic to commands requiring network access that should be retried
    - [ ] For when conda installs run into issues: e.g., `ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host` in  https://circleci.com/gh/pytorch/pytorch/16331602

### Alternatives

 A more low-maintenance idea is to improve Dr. CI to rerun every failed build job automatically.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by mszhanyi** [comment]
@janeyx99 Are there tools to measure improvements if we make some changes?

**Comment by janeyx99** [comment]
Yes, we track a dashboard for % trunk redness and that number should decrease with improvements here. e.g., the % GHA master fail [here](https://metrics.pytorch.org/?orgId=1&viewPanel=33).

We also have a public dashboard for commits and their redness: https://www.torch-ci.com/minihud. Ideally this page should be all green, but redness occurs due to factors including network connectivity flakiness.

**Comment by ZainRizvi** [comment]
Closing since @huydhn's completed most of the above. However, there still exists a long tail of network risks which will have to be addressed separately
