### ISSUE TITLE
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

### ISSUE THREAD

**Issue by geogeo28** [pytorch/pytorch#71062]
### 🐛 Describe the bug

When using modules having torch.nn.utils.parametrize like:
```
class SWSConv2d(nn.Module):
    r"""
    2D Conv layer with Scaled Weight Standardization.

    Characterizing signal propagation to close the performance gap in unnormalized ResNets
    https://arxiv.org/abs/2101.08692
    """
    def __init__(self,
                 in_channels: int, out_channels: int, kernel_size: int,
                 stride: int=1, padding: int=0, padding_mode: str='zeros', dilation=1, groups: int=1,
                 bias: bool=True):

        super().__init__()

        self._stride = stride
        self._padding = padding
        self._padding_mode = padding_mode
        self._dilation = dilation
        self._groups = groups

        self.weight = nn.Parameter(torch.empty(out_channels, in_channels, kernel_size, kernel_size))
        self.bias = nn.Parameter(torch.empty(out_channels)) if bias else None
        self.gain = nn.Parameter(torch.ones(out_channels, 1, 1, 1))

        # Init weights
        k = groups / (in_channels * kernel_size * kernel_size)
        torch.nn.init.uniform_(self.weight, -k, k)
        if bias:
            torch.nn.init.uniform_(self.bias, -k, k)

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return TF.conv2d(input,
                         weight=self.weight.to(input.device, copy=True) * self.gain, bias=self.bias,
                         stride=self._stride,
                         padding=self._padding,
                         dilation=self._dilation,
                         groups=self._groups)
```

Optimizing training performance by using:
```
# Avoid to recompute parametrization for weights shared
with torch.nn.utils.parametrize.cached():
  pred = self.model.forward(img0, img1, solver_num_iters=solver_num_iters)
```

Training failed with the following error:
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

Anomaly detection points to the following culprit:
```
File "/mnt/task_runtime/src/dibnn_ext/nn/modules.py", line 832, in forward
    weight=self.weight.to(input.device, copy=True) * self.gain, bias=self.bias,
  File "/miniconda/lib/python3.7/site-packages/torch/nn/utils/parametrize.py", line 339, in get_parametrized
    return get_cached_parametrization(parametrization)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/utils/parametrize.py", line 324, in get_cached_parametrization
    tensor = parametrization()
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/utils/parametrize.py", line 260, in forward
    x = self[0](self.original)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/task_runtime/src/dibnn_ext/nn/parametrization.py", line 36, in forward
    weight = DF.weight_standardization(weight, eps=self.eps)
  File "/mnt/task_runtime/src/dibnn_ext/nn/functional.py", line 660, in weight_standardization
    weight = (weight - mean) / (torch.sqrt(var * fan_in + eps))
 (function _print_stack)
```

It seems the cached weights of a parametrize module do not have gradients available when they are used multiple time in a model.

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.7 (default, Mar 23 2020, 22:36:06)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.19.56-1.el7.x86_64-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.40.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.5
[pip3] torch==1.10.0+cu113
[pip3] torchaudio==0.10.0+cu113
[pip3] torchmetrics==0.6.2
[pip3] torchvision==0.11.1+cu113
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.21.2           py37h79a1101_0  
[conda] pytorch-cpu               1.1.0            py37he1b5a44_0    conda-forge
[conda] pytorch-lightning         1.5.5              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.10.0+cu113             pypi_0    pypi
[conda] torchaudio                0.10.0+cu113             pypi_0    pypi
[conda] torchmetrics              0.6.2              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.11.1+cu113             pypi_0    pypi

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by Lezcano** [comment]
This model does not have any `nn.utils.Parametrization`s that I can see. Where did you use parametrizations?

Parametrised weights can indeed be used several times in the model, and that's exactly what `cached` is for.

As a side note, I reckon you've already tried this, but does the training succeed when you do not register the parametrisations?

**Comment by geogeo28** [comment]
Thanks Lezcano  for your reply.
I cannot share the model but I can reproduce the issue consistently with different models.
Here is how I use the parametrization.

```
import torch
import torch.nn as nn
import torch.nn.functional as TF

def weight_standardization(weight: torch.Tensor, eps: float = 1e-6):
    """
    Weight standardization as defined by:
    Characterizing signal propagation to close the performance gap in unnormalized ResNets, https://arxiv.org/abs/2101.08692

    :param weight: weight to standardize
    :param eps: epsilon to ensure safe division
    :return: weight to standardized
    """

    fan_in = nn.init._calculate_fan_in_and_fan_out(weight)[0]

    var, mean = torch.var_mean(weight, dim=list(range(1, weight.ndim)), keepdim=True)
    weight = (weight - mean) / (torch.sqrt(var * fan_in + eps))
    return weight

class WeightStandardization(nn.Module):
    def __init__(self, eps: float=1e-6):
        super().__init__()

        self.eps = eps

    def forward(self, weight: torch.Tensor) -> torch.Tensor:
        weight = DF.weight_standardization(weight, eps=self.eps)
        return weight

class SWSConv2d(nn.Module):
    r"""
    2D Conv layer with Scaled Weight Standardization.

    Characterizing signal propagation to close the performance gap in unnormalized ResNets
    https://arxiv.org/abs/2101.08692
    """
    def __init__(self,
                 in_channels: int, out_channels: int, kernel_size: int,
                 stride: int=1, padding: int=0, padding_mode: str='zeros', dilation=1, groups: int=1,
                 bias: bool=True):

        super().__init__()

        self._stride = stride
        self._padding = padding
        self._padding_mode = padding_mode
        self._dilation = dilation
        self._groups = groups

        self.weight = nn.Parameter(torch.empty(out_channels, in_channels, kernel_size, kernel_size))
        self.bias = nn.Parameter(torch.empty(out_channels)) if bias else None
        self.gain = nn.Parameter(torch.ones(out_channels, 1, 1, 1))

        # Init weights
        k = groups / (in_channels * kernel_size * kernel_size)
        torch.nn.init.uniform_(self.weight, -k, k)
        if bias:
            torch.nn.init.uniform_(self.bias, -k, k)

        TP.register_parametrization(self, 'weight', DP.WeightStandardization(eps=1e-6))

    def forward(self, input: torch.Tensor) -> torch.Tensor:
        return TF.conv2d(input,
                         weight=self.weight.to(input.device, copy=True) * self.gain, bias=self.bias,
                         stride=self._stride,
                         padding=self._padding,
                         dilation=self._dilation,
                         groups=self._groups)

class DummyModel(nn.Module):
    def __init__(self,
                 input_dim: int,
                 output_dim: int,
                 hidden_dim: int):

        super().__init__()

        self.blocks = nn.Sequential(
            SWSConv2d(input_dim, hidden_dim, 3, bias=True, activation=TF.ReLU()),
            SWSConv2d(hidden_dim, output_dim, 1, bias=True
        )

    def forward(self, input) -> torch.Tensor:
        pred = self.blocks(input)
        return pred
```

Overall the training works WITHOUT the parametrization (standard Conv2D instead of SWSConv2d) but an ideal scenario because the SWS helps the convergence.
I have in my models a siamese network for feature extraction which reuses the same weights 2 times.

The training also works WITH the parametrization SWSConv2d and with torch.nn.utils.parametrize.cached(): commented.
It only failed with the cache enabled randomly during training. I suspect the backward pass try to recompute gradients on SWSConv2d already computed in the past. I do not know if we can force to keep the gradients in a cached parametrization?

**Comment by Lezcano** [comment]
What seems odd to me from that piece of is the line `self.weight.to(input.device, copy=True)`. Why do you move it to a different device, rather than creating `nn.Sequential` in the correct device or moving the whole model to the correct device via `to(device)`?

**Comment by geogeo28** [comment]
That's a good point. I had to include this line because when I use the cache it appears the weights are save from one GPU but used to another GPU.
Overall, I move the model to the correct devices but during training when I use cached parametrization the weights can be in another GPU.

**Comment by geogeo28** [comment]
I am using DDP with mixed precision training on 8 GPU.
Not sure how the weights should be cached?

**Comment by Lezcano** [comment]
cc @albanD for an interesting case when using parametrizatons + caches + multi GPU setups. I'm not sure of what's the behaviour of `parametrization`s together with DDP.

**Comment by geogeo28** [comment]
The issue is easier to reproduce with DP and autograd-detect-anomaly.
I am wondering if the problem is simply the cache is global and not thread safe?

**Comment by albanD** [comment]
Can you share what your training loop looks like as well please? Or even better a full example we can run to reproduce this?

Note that the cached result is computed in a differentiable way. So if you do multiple backwards within the cached context, you are trying to backward multiple times indeed so I would expect this error.

**Comment by geogeo28** [comment]
Unfortunately this is a lot of code I cannot share but I will try to create a minimal example to reproduce the issue.
I am using Pytorch Lightning for the training loop. The network is a simple feed forward with a siamnese branch, and to be exact, the issue only occurs when the cache is enabled.

**Comment by geogeo28** [comment]
I found the issue by working on a minimal example.
The issue was simply caching the forward pass not including the computation of the loss:
```
def training_step(...):
  with torch.nn.utils.parametrize.cached():
    pred = self.model.forward(img0, img1, solver_num_iters=solver_num_iters)
  ...
  loss = compute_loss(...)
```

I think we can close this ticket. ^^
