### ISSUE TITLE
Noisy warning raised by 'default_collate'

### ISSUE THREAD

**Issue by naturomics** [pytorch/pytorch#71063]
### 🐛 Describe the bug

After upgrading pytorch version from 1.10.1 to the master branch (commit [d697bb4](https://github.com/pytorch/pytorch/commit/d697bb4220ff5ea8b46591cc082583bbf1a294a4)), `torch.utils.data._utils.collate.default_collate` raises the below noisy warning repeatedly:

```
UserWarning: An output with one or more elements was resized since it had shape [10], which does not
match the required output shape [2, 5].This behavior is deprecated, and in a future PyTorch release outputs will
not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace,
to zero elements with t.resize_(0).
```
The warning is original from [Resize.cpp](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Resize.cpp#L11-L27) and triggered by [these lines](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/collate.py#L130-L138) of `default_colloate`:

```
    elem = batch[0]
    elem_type = type(elem)
    if isinstance(elem, torch.Tensor):
        out = None
        if torch.utils.data.get_worker_info() is not None:
            # If we're in a background process, concatenate directly into a
            # shared memory tensor to avoid an extra copy
            numel = sum(x.numel() for x in batch)
            storage = elem.storage()._new_shared(numel)
            out = elem.new(storage)
        return torch.stack(batch, 0, out=out)
```

In case `default_collate` runs in background/worker process (torch.utils.data.get_worker_info() returns something), `out` is always a 1D tensor, but `batch` may has higher rank, thus a resize operation happens inside the `torch.stack` operation, which triggers the warning.

### Versions

Master branch (commit [d697bb4](https://github.com/pytorch/pytorch/commit/d697bb4220ff5ea8b46591cc082583bbf1a294a4))

# To Reproduce
Use this code snippet to reproduce the problem:

```
import torch

a, b = torch.randn([5]), torch.randn([5])
batch = [a, b]
elem = batch[0]

# In case torch.utils.data.get_worker_info() is not None
numel = sum(x.numel() for x in batch)
storage = elem.storage()._new_shared(numel)
out = elem.new(storage)

torch.stack(batch, 0, out=out)
```

# Expected behavior
No warning raises.

# Workaround

```
    elem = batch[0]
    elem_type = type(elem)
    if isinstance(elem, torch.Tensor):
        out = None
        if torch.utils.data.get_worker_info() is not None:
            # If we're in a background process, concatenate directly into a
            # shared memory tensor to avoid an extra copy
            numel = sum(x.numel() for x in batch)
            storage = elem.storage()._new_shared(numel)

            # reshape `out` before passing to torch.stack
            out = elem.new(storage).view(-1, *list(elem.size()))  

        return torch.stack(batch, 0, out=out)
```

Test code:

```
import torch

a, b = torch.randn([5]), torch.randn([5])
batch = [a, b]
elem = batch[0]

# In case torch.utils.data.get_worker_info() is not None
numel = sum(x.numel() for x in batch)
storage = elem.storage()._new_shared(numel)
out = elem.new(storage).view(-1, *list(elem.size()))

torch.stack(batch, 0, out=out)
```

cc @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Thanks for submitting the issue. The request sounds reasonable to me.

**Comment by ejguan** [comment]
Closing the Issue as PR has landed
