### ISSUE TITLE
Let size=() by default

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#71075]
### 🚀 The feature, motivation and pitch

Make `size=()` the default for functions that take it as an argument, including:
- [`zeros`](https://pytorch.org/docs/stable/generated/torch.zeros.html#torch.zeros)
- [`ones`](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones)
- [`rand`](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand)
- [`randn`](https://pytorch.org/docs/stable/generated/torch.randn.html#torch.randn)
- [`randint`](https://pytorch.org/docs/stable/generated/torch.randint.html#torch.randint)

[`torch.distributions`](https://pytorch.org/docs/stable/distributions.html) already uses the convention of sampling a single scalar by default.

**Comment by vadimkantorov** [comment]
Related: https://github.com/pytorch/pytorch/issues/67571

**Comment by carlosgmartin** [comment]
@vadimkantorov I've closed this issue in favor of yours. I support making `size=()` the default for any function taking `size` as an argument.

**Comment by vadimkantorov** [comment]
@carlosgmartin Please feel free to comment in my issue and add context / usecases there
