### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by Entretoize** [pytorch/pytorch#71083]
### 🐛 Describe the bug

After having tried several version of python (3.6, 3.7, 3.8), install with pip, or conda, fresh environment ... nothing allow me to use torch.
Latest try:
`pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html`

It installs well, but a simple "import torch" gives : No module named 'torch'

### Versions

PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 496.76
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchvision==0.11.2+cu113
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py37h2bbff1b_0
[conda] mkl_fft                   1.3.1            py37h277e83a_0
[conda] mkl_random                1.2.2            py37hf11a4ad_0
[conda] numpy                     1.21.2           py37hfca59bb_0
[conda] numpy-base                1.21.2           py37h0829f74_0
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] torchvision               0.11.2+cu113             pypi_0    pypi

**Comment by jbschlosser** [comment]
Hey @Entretoize! It sounds like there may be some problem with your environment. I'd suggest posting in the [PyTorch forums](https://discuss.pytorch.org/) as you are more likely to receive help there. Note that the issues here are for problems within PyTorch itself.

**Comment by Entretoize** [comment]
I finaly found a solution, upgrading everything in conda.

**Comment by DMNK20888** [comment]
Hello @Entretoize what do you mean by upgrading everything in conda and how would you do it?
Thanks

**Comment by Entretoize** [comment]
I don't remember exactly, I know there's a command `conda update --all` but I also remember one time I had to uninstall conda itself in install the last version because it never updated itself alone.
