### ISSUE TITLE
`TestOperators.test_c2_op` : different raw data generated for the test in my local and CI environment

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#71095]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/67254 cause the following failure. Updating the expect files (by running the `--accept flag`) continue to cause this failure, probably because the raw data generated in my local environment and CI environment are different for some reason.
https://github.com/pytorch/pytorch/runs/4745258391?check_suite_focus=true
```
――――――――――――――――――――――――――― TestOperators.test_c2_op ―――――――――――――――――――――――――――
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/onnx/test_operators.py", line 752, in test_c2_op
    self.assertONNX(model, inputs, custom_opsets={"org.pytorch._caffe2": 0})
  File "/var/lib/jenkins/workspace/test/onnx/test_operators.py", line 71, in assertONNX
    self.assertExpected(onnx_model_pbtxt, subname)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2349, in assertExpected
    self.assertMultiLineEqual(expected, s)
  File "/opt/conda/lib/python3.7/unittest/case.py", line 1233, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/conda/lib/python3.7/unittest/case.py", line 693, in fail
    raise self.failureException(msg)
AssertionError: 'ir_v[91 chars]ut: "0"\n    input: "1"\n    input: "2"\n    i[2817 chars]n}\n' != 'ir_v[91 chars]ut: "scores"\n    input: "bbox_deltas"\n    in[2871 chars]n}\n'
Diff is 3548 characters long. Set self.maxDiff to None to see it.
```

### Versions

Master

cc. @BowenBao

**Comment by garymm** [comment]
Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1609474>

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
