### ISSUE TITLE
Obliviate ALL_TENSORTYPES and ALL_TENSORTYPES2

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71096]
### 🚀 The feature, motivation and pitch

Usage of these two variables in tests is outdated. One should just write in the dtypes in question or use one of the ATen macro dispatch list functions (like `get_all_fp_dtypes()`).

**Comment by khushi-411** [comment]
Hi, @janeyx99!
I want to work on this issue. May I go for it?
Thanks :)

**Comment by khushi-411** [comment]
Thanks for the idea, @janeyx99! Sure, I'll ping you in case of doubts. Thanks :)
