### ISSUE TITLE
in-place version API does not match the broadcast shape

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#71098]
### 🐛 Describe the bug

The in-place version API like `torch.Tensor.eq_` will write the output into the input tensor without making a copy. However, some API will support the broadcast operation and return a tensor with a different shape from the input tensor, which causes failure when trying to write the return tensor into the input tensor. For example,

```python
import torch
input = torch.randint(-1,1,[2], dtype=torch.int64)
other = torch.randint(-1,1,[2, 2], dtype=torch.int64)
torch.eq(input, other)
# succeed
input.eq_(other)
# RuntimeError: output with shape [2] doesn't match the broadcast shape [2, 2]
```

This error is strange because by definition, the in-place and out-of-place API should have the same behavior. However, with broadcasting, the out-of-place and in-place version have different behavior (out-of-place succeeds and in-place fails), this violates the definition. 

### Versions

pytorch: 1.10.1

**Comment by gchanan** [comment]
This is not a bug, as explained here: https://pytorch.org/docs/master/notes/broadcasting.html#in-place-semantics

**Comment by TestSomething22** [comment]
@gchanan Hi, Thank you for your explanation. But some in-place APIs do need the input tensor has the same shape with the output tensor. For example,

```python
import torch
input = torch.randint(-2,1,[1, 3], dtype=torch.int64)
mat1 = torch.randint(-2,4,[2, 3], dtype=torch.int64)
mat2 = torch.randint(-8,1,[3, 3], dtype=torch.int64)
torch.addmm(input, mat1, mat2)
# succeed
input.addmm_(mat1, mat2)
# RuntimeError: The input tensor must be a matrix with size 2x3, but got a 2-D tensor with size 1x3
```

I think the behavior of in-place APIs should be consistent (at least the error message)
