### ISSUE TITLE
[docs] Make examples in docs into auto-runnable smoke tests

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#71105]
### 📚 The doc issue

Original discussion: https://github.com/pytorch/pytorch/issues/70972#issuecomment-1007444643 cc @brianjo @mruberry @dagitses . This will prevent outdated code examples (think deprecated functions / renamed arg names etc)

### Suggest a potential alternative/fix

More advanced version of this would be also verifying printed tensor outputs in docs, but smoke tests should be the first step

**Comment by khushi-411** [comment]
Hi, @vadimkantorov!
A gentle note to view a similar kind of discussion https://github.com/pytorch/pytorch/issues/54881.
Thanks!

**Comment by mruberry** [comment]
I think we do have some testing of doc examples, but I'm not sure how thorough or effective it is. One tricky thing about our current doc examples is that they are often only nonreproducible snippets of programs.

**Comment by vadimkantorov** [comment]
I think it should be a gradual process, e.g. introduce some unique link for every code example (at least in API docs), and produce a table of "goodness" of examples. Then gradually you could have people fix the broken ones or make them more independently runnable.

Similar to 404-link detection.

And then for non-repro - I guess first thing should be the infra for encoding results in some format, so that the results could be compared against them. Then the non-reproducible ones (using torch.rand) could be refactored over time
