### ISSUE TITLE
Custom function forward-mode AD internal assert when returning same tensor

### ISSUE THREAD

**Issue by soulitzer** [pytorch/pytorch#71119]
```python
import torch.autograd.forward_ad as fwAD
import torch

class Test(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        return x

    @staticmethod
    def jvp(ctx, x_t):
        return x_t

x = torch.tensor(1.)
t = torch.tensor(1.)

with fwAD.dual_level():
    dual_x = fwAD.make_dual(x, t)
    Test.apply(dual_x)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
That's only when the jvp is a no-op right? The forward can be anything?

**Comment by soulitzer** [comment]
I think it happens as long as the forward returns the same tensor it received as input and does not that mark that output as dirty. The forward can do other things, e.g. return other outputs. I also checked that we still run into this whether or not we define vjp.

**Comment by albanD** [comment]
This is done right @soulitzer ?
