### ISSUE TITLE
[RFC] Make `c10/util/complex.h` include-free

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#71127]
### 🚀 The feature, motivation, and pitch

Currently, most complex transcendental functions are implemented by dispatching to either `std::complex` (on CPU) or `thrust::complex` (on CUDA). This approach has a few drawbacks:

First, the numerics on CPU vs GPU, Linux vs Windows vs macOS does not match. This causes many conditinoal skips in `test_reference_numerics`. Especially, the libcxx in LLVM is known to have bad numerics for complex transcendentals, I personally have fixed two of them (https://reviews.llvm.org/D112252, https://reviews.llvm.org/D112277), but there are still more. IIRC, macOS uses libcxx as its default C++ library, so PyTorch complex has poor numerics on macOS.

Second, including other headers makes `c10/util/complex.h` hard to use in NVRTC, which is important for Jiterator(https://github.com/pytorch/pytorch/issues/69463) and CUDA fusion of `torch.jit`.

To resolve these issue, I recommend implementing all these functions inside PyTorch, making `c10/util/complex.h` a self contained header. Considering that most complex transcendental functions can be implemented by transcendental functions of real numbers, for example `exp(x+iy) = exp(x)*(cos(y) + i*sin(y)*`, implementing them in PyTorch will not be hard.

### Possible solution

To make the header self-contained, one way is to write everything from scratch. But a faster way could be to copy-paste LLVM's libcxx implementation into PyTorch directly. As I mentioned before, LLVM's libcxx implementation does not have good numerics. So it will not be a mindless copy-paste. My plan is to first investigate the numerics of these function one by one, if there is a problem in some function, then I will submit a differential to LLVM's phabricator. After LLVM approved my differential, I will copy-paste them into PyTorch.

To the best of my knowledge, GNU's libm has the best numerics. But I believe we are not supposed to use their code(unless Meta wants to change PyTorch's license to GPL😝). But LLVM seems to be safe. The license of LLVM is in https://llvm.org/docs/DeveloperPolicy.html#new-llvm-project-license-framework. I am not an expert of copyright law, but my understanding is: as long as we keep the copyright notice, we are free to use it.

There may be better ways than copy-pasting LLVM, suggestions are welcome :)

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by zasdfgbnm** [comment]
cc: @mruberry @ngimel @csarofeen @ptrblck @ezyang @anjali411

**Comment by mruberry** [comment]
This is a really interesting idea, @zasdfgbnm, and we could fix numeric issues in PyTorch first, too. I'd really like to see a draft PR for this -- maybe jiterating sinc would be a good start?

https://github.com/pytorch/pytorch/blob/ce409d8f500b2f916af3976f8e0030ae5f257363/aten/src/ATen/native/cuda/UnarySpecialOpsKernel.cu#L123

**Comment by anjali411** [comment]
cc. @malfet

**Comment by zasdfgbnm** [comment]
Per offline discussion, we copy-paste llvm's complex implementation for JIT, and still use the current c10::complex for precompiled kernels. Jiterator complex support has been added in https://github.com/pytorch/pytorch/pull/71577
