### ISSUE TITLE
Activation checkpointing breaks bfloat16 AMP

### ISSUE THREAD

**Issue by gahdritz** [pytorch/pytorch#71124]
### 🐛 Describe the bug

When bfloat16 AMP is enabled, the backward passes of modules within activation checkpoints run as if float16 AMP is enabled instead. Here's some minimal reproduction code:

```
import torch
from torch.utils.checkpoint import checkpoint

def main():
    class Linear(torch.nn.Module):
        def __init__(self, c_in, c_out):
            super().__init__()
            self.l = torch.nn.Linear(c_in, c_out)

        def forward(self, x):
            out = self.l(x)
            print(f"Output dtype: {out.dtype}")
            return out

    class LinearStack(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.stack = torch.nn.ModuleList()
            for _ in range(10):
                self.stack.append(Linear(10, 10))

        def forward(self, x):
            for b in self.stack:
                x = checkpoint(b, x)

            return x

    model = LinearStack().cuda()
    x = torch.rand(10, 10, requires_grad=True).cuda()

    with torch.cuda.amp.autocast(dtype=torch.bfloat16):
        y = model(x)
        print("End of forward pass...")
    
    loss = torch.mean(y)
    loss.backward()

if __name__ == '__main__':
    main()
```

Running this yields the following output:
```
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
Output dtype: torch.bfloat16
End of forward pass...
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
Output dtype: torch.float16
```

During the forward pass, the output is of type `torch.bfloat16`, as expected. During the backward pass, the output ends up as a `torch.float16`.

Workarounds would be appreciated.

### Versions

PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.9

Python version: 3.7.0 (default, Oct  9 2018, 10:31:47)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.163.1.fi-x86_64-with-centos-7.9.2009-Core
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.5.0
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchmetrics==0.6.2
[pip3] torchvision==0.11.2+cu113
[conda] cudatoolkit               11.2.2               he111cf0_8    conda-forge
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] pytorch-lightning         1.5.0                    pypi_0    pypi
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] torchmetrics              0.6.2                    pypi_0    pypi
[conda] torchvision               0.11.2+cu113             pypi_0    pypi

Tagging @jisaacso

**Comment by jisaacso** [comment]
@ngimel @ezyang @jbschlosser  -- any thoughts on workarounds?

**Comment by ngimel** [comment]
This should fix it D31113421. cc @mcarilli, the linked diff is a one-liner removing thread_local in autocast_mode.cpp:
```
at::ScalarType autocast_gpu_dtype = at::kHalf;
```

**Comment by mcarilli** [comment]
I don't think making the autocast dtype global is a landable general solution. The autocast state should be thread local so people can use python threads flexibly. @ngimel do you agree?

Proposed solution: In CheckpointFunction.forward, alongside [`ctx.had_autocast_in_fwd`](https://github.com/pytorch/pytorch/blob/7397683b575f2feea78219d174a0e1db1d5e1dd2/torch/utils/checkpoint.py#L62), also stash `ctx.dtype = torch.get_autocast_dtype()`, where `get_autocast_dtype()` is a helper we'd need to add (it might already exist by some other name). This won't be hard to implement. I'll make a PR.

(An alternative I briefly thought about just now was to somehow set autocast dtype in backward thread(s) by including it among [`local_graph_task->thread_locals`](https://github.com/pytorch/pytorch/blob/7397683b575f2feea78219d174a0e1db1d5e1dd2/torch/csrc/autograd/engine.cpp#L412), but this wouldn't account for different functions in forward potentially using different autocast dtypes. I think surgical per-checkpoint-context stashing is the least bad approach.)

**Comment by mcarilli** [comment]
@gahdritz Please check if https://github.com/pytorch/pytorch/pull/71169 fixes your use case.

**Comment by gahdritz** [comment]
It works, but I'm now getting a strange warning at the beginning of the backward pass:

```
lib/conda/envs/openfold_venv/lib/python3.7/site-packages/torch/autocast_mode.py:156: UserWarning: In CPU autocast, but the target dtype is not supported. Disabling autocast.
CPU Autocast only supports dtype of torch.bfloat16 currently.
  warnings.warn(error_message)
```

**Comment by mcarilli** [comment]
interesting. Let's continue discussion on the PR itself.
