### ISSUE TITLE
runtime error when adding one more linear layer at resent50 model with ouput as 2 classes

### ISSUE THREAD

**Issue by arpitvw** [pytorch/pytorch#7122]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
i am having a dataset with two ouput classes. i am using pretrained resnet50 network . 
i added one more layer at last so that i can make network as binary classifier with below code         resnet = models.resnet50(pretrained=True)
# freeze all model parameters
for param in resnet.parameters():
    param.requires_grad = False

# new final layer with 2 classes
num_ftrs = resnet.fc.in_features
resnet.fc = torch.nn.Linear(num_ftrs, 2)

labels:
inputs, labels = next(iter(dataloader))
print (labels)
 1
 2
 2
 1
 1
 2
 1
 1
 2
 1
 2
 1
 1
 1
 1
 1
 1
 2
 1
 1
[torch.LongTensor of size 20]
batch size =20

RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at c:\miniconda2\conda-bld\pytorch-cpu_1519449358620\work\torch\lib\thnn\generic/ClassNLLCriterion.c:87

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
It's hard for us to help you if you don't include example code or even a stack trace of the error.

From your previous title,
> RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed

I'm guessing this is the error you ran into. I don't think this is a bug: this error occurs when you're using CrossEntropyLoss or NLLLoss and your `target` value is not in the range `[0, n_classes)`. Please check your the output value of your `target`.

**Comment by arpitvw** [comment]
Yes , my bad :(
i checked its some code issue from my side
