### ISSUE TITLE
`StreamWrapper` does not work with `open`

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#71221]
`StreamWrapper` does not work with `open`. This means that amongst others you can no longer load `.mat` files directly:

```python
import scipy.io

from torchdata.datapipes.iter import FileLoader, IterableWrapper, Mapper

file = "foo.mat"
scipy.io.savemat(file, dict(foo="bar"))

dp = IterableWrapper((file,))
dp = FileLoader(dp)
dp = Mapper(dp, scipy.io.loadmat, input_col=1)

next(iter(dp))
```

```
TypeError: expected str, bytes or os.PathLike object, not StreamWrapper
```

The error message is a little misleading. Although `open` very much supports open file handles as inputs (in which case it is a no-op), this possibility is not included in the message. Internally, `scipy` fails [here](
https://github.com/scipy/scipy/blob/701ffcc8a6f04509d115aac5e5681c538b5265a2/scipy/io/matlab/mio.py#L38-L49). 

Workaround is to explicitly pass the `.file_obj` attribute to `scipy.io.loadmat`:

```python
import scipy.io

from torchdata.datapipes.iter import FileLoader, IterableWrapper, Mapper

file = "foo.mat"
scipy.io.savemat(file, dict(foo="bar"))


def loadmat(stream_wrapper):
    return scipy.io.loadmat(stream_wrapper.file_obj)


dp = IterableWrapper((file,))
dp = FileLoader(dp)
dp = Mapper(dp, loadmat, input_col=1)

data = next(iter(dp))
assert data[1]["foo"] == "bar"
```

_Originally posted by @pmeier in https://github.com/pytorch/pytorch/issues/66715#issuecomment-955998986_

cc @VitalyFedyunin @ejguan @NivekT

**Comment by NivekT** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/71653
