### ISSUE TITLE
DISABLED test_dtypes__masked_amin_cuda (__main__.TestCommonCUDA)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#71248]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_dtypes__masked_amin_cuda%2C%20TestCommonCUDA)).

It actually is failing really consistently, but I can't figure out which commit caused it so disabling so someone else can take a look

cc @ezyang @gchanan @zou3519 @bdhirsh @nairbv @mruberry

**Comment by suo** [comment]
cc @mruberry can you find someone who knows about this test?

**Comment by mruberry** [comment]
@cpuhrsch -- masked_amin issue?

**Comment by pearu** [comment]
This issue appears to be fixed and can be closed. @suo, please confirm.

**Comment by zengk95** [comment]
Reopening since we're seeing some more issues https://hud.pytorch.org/failure/test_dtypes__masked_amin_cuda%2C%20TestCommonCUDA
