### ISSUE TITLE
Move `AT_ERROR` to `TORCH_CHECK(false`

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#71265]
### 🚀 The feature, motivation and pitch

I just learnt we're deprecating `AT_ERROR` in favour of `TORCH_CHECK(false`. I don't know the reasons behind this, but it'd be good to simply regex our way to victory here.

### Alternatives

Not deprecate `AT_ERROR`? In all fairness, I prefer `AT_ERROR` as it's more concise both in intentions and in keystrokes.

**Comment by ngimel** [comment]
While replacing `AT_ERROR` with `TORCH_CHECK(false` indeed doesn't make much sense, the typical usecase is 
```
if (something) {
  AT_ERROR(...)
}
```
and that can be more concisely replaced by `TORCH_CHECK(something, ...)`

**Comment by Lezcano** [comment]
So is `AT_ERROR` being deprecated or not? @IvanYashchuk said it was, but I like it in some cases (e.g. calling a magma function when pytorch is not compiled against magma).

**Comment by ngimel** [comment]
It's soft-deprecated, better not use it, but unlikely we are going to spend time to actually purge it from the codebase.
