### ISSUE TITLE
torch dependencies aren't fully specified + pkg_resources import is slow

### ISSUE THREAD

**Issue by hauntsaninja** [pytorch/pytorch#71280]
### 🐛 Describe the bug

In pytorch/torch_version.py, we do `from pkg_resources import packaging`.

https://github.com/pytorch/pytorch/blob/83b45fe1666fd8ecc697078ca99ff46dabe0286b/torch/torch_version.py#L3

This causes two problems:
- We have an undeclared runtime dependency on setuptools. Currently pytorch only has declared dependencies on typing_extensions and dataclasses: https://github.com/pytorch/pytorch/blob/83b45fe1666fd8ecc697078ca99ff46dabe0286b/setup.py#L409
- pkg_resources is a really slow import. It takes a full 1s on my laptop, sometimes longer depending on disk cache. Moreover, we're not actually using pkg_resources itself, we're using pkg_resource's vendored version of https://github.com/pypa/packaging

Possible fixes:
- Declare a dependency on `packaging` and replace `from pkg_resources import packaging` with `import packaging.version`. This makes torch imports much faster! :-)
- Don't declare a dependency on `packaging`, but try to import it, and fallback to `from pkg_resources import packaging`. This doesn't fix the undeclared dependency, but it does make `import torch` faster.
Another variation on this is to try to steal vendored `packaging` from a package that imports faster, e.g. `pip._vendor.packaging.version`.  We could combine that with fallback to `pkg_resources` as well.
- Vendor the appropriate code from `packaging.version`

### Versions

1.10.1

cc @malfet @seemethere

**Comment by malfet** [comment]
Thank you very much for writing a detailed issue.

> * pkg_resources is a really slow import. It takes a full 1s on my laptop, sometimes longer depending on disk cache. 

Can you please try running something like `time python3 -c "print('Hello')"; time python3 -c "from pkg_resources import packaging; print('Hello')` and share the output?
On my laptop, running python3 takes 0.03 sec and running python that imports pkg_resources takes 0.17 sec, which is indeed pretty bad, but nowhere close to 1 sec

**Comment by malfet** [comment]
Adding `triage review` to discuss, which label should be used for such cases, as `module: build` as well as `module: binaries` feels wrong in this case

**Comment by hauntsaninja** [comment]
I'm also happy to provide a PR if one of those options sounds good to you :-)

**Comment by albanD** [comment]
> Vendor the appropriate code from packaging.version

Given that we use these classes for isinstance check. I don't think this would work.

For the solution I think that trying to import packaging and fallback to the slower import is ok to do. We already do this kind of things for our yaml loader for example [here](https://github.com/pytorch/pytorch/blob/88012c7daf019d0f6a11a744c03fb63231b84830/tools/codegen/utils.py#L12-L16). @malfet would you be happy with this solution?

**Comment by malfet** [comment]
@albanD it would solve rougue dependency, but would not solve a perf penalty everyone have to pay for something very rarely used

**Comment by seemethere** [comment]
> Ho that can be solved by lazy loading the package (or just inline the import inside the methods). The import only creates an instance of our class which doesn't require this package at all. We just import it whenever the user tries to do any comparison. I verified locally that `import torch` indeed never does that.

Lazy load might work but since `torch/torch_version.py` gets imported in the root as part of `import torch` it'll just load it every time anyways.

**Comment by hauntsaninja** [comment]
> Given that we use these classes for isinstance check. I don't think this would work.

But the class used is pkg_resources vendored packaging, not packaging itself. I'm unclear on how this is meant to be used, since users aren't going to be using the vendored package.

```
In [1]: import torch

In [2]: torch.__version__
Out[2]: '1.10.1'

In [3]: type(torch.__version__)
Out[3]: torch.torch_version.TorchVersion

In [4]: import packaging.version

In [5]: packaging.version.Version("1.10.2") > torch.__version__
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-067714c3f7be> in <module>
----> 1 packaging.version.Version("1.10.2") > torch.__version__

TypeError: '>' not supported between instances of 'Version' and 'TorchVersion'

In [6]: from pkg_resources import packaging

In [7]: packaging.version.Version("1.10.2") > torch.__version__
Out[7]: True
```

**Comment by albanD** [comment]
> Lazy load might work but since torch/torch_version.py gets imported in the root as part of import torch it'll just load it every time anyways.

We don't actually use any of these functions on import. So a lazy load would not trigger during the import (I checked by removing the import and importing torch, that works fine).

> @albanD yeah, thats the idea, but I'm debating how to do that without rendering the code too ugly. #71316 is somewhat borderline

It is borderline as is indeed. I like the `_get_pandas()` idea though as it removes a lot of copy pasted error checking in the actual code.
You can even avoid the function call by making it an object instance with a custom getattr that does the lazy init.

**Comment by hauntsaninja** [comment]
Thanks for the fix!

Using `pkg_resources` will still be slow if you do `torch.__version__`. I think there'd still be value in doing:
```
diff --git a/torch/torch_version.py b/torch/torch_version.py
index a7aa6764b5..667c17980b 100644
--- a/torch/torch_version.py
+++ b/torch/torch_version.py
@@ -18,7 +18,10 @@ class _LazyImport:
         self._cls_name = cls_name
 
     def get_cls(self):
-        from pkg_resources import packaging  # type: ignore[attr-defined]
+        try:
+            import packaging.version
+        except ImportError:
+            from pkg_resources import packaging  # type: ignore[attr-defined]
         return getattr(packaging.version, self._cls_name)
 
     def __call__(self, *args, **kwargs):
```

**Comment by malfet** [comment]
@hauntsaninja this sounds good to me, please do not hesitate to propose a fix like that and I will gladly review it
