### ISSUE TITLE
TestSparseCSRCUDA.test_block_triangular_solve_cuda_complex128 fails on A100

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#71297]
### 🐛 Describe the bug

TestSparseCSRCUDA.test_block_triangular_solve_cuda_complex128 fails on A100.

Repro steps:
```
python test/test_sparse_csr.py -v -k TestSparseCSRCUDA.test_block_triangular_solve_cuda_complex128
```

Standalone repros:
```python
import torch

a = torch._sparse_csr_tensor_unsafe(
        crow_indices=torch.tensor([0, 1]),
        col_indices=torch.tensor([0]),
        values=torch.tensor([[[1, 2], [3, 4]]]),
        device='cuda:0',
        size=(2, 2), dtype=torch.complex128)

b = torch.tensor([[1], [2]], device='cuda:0', dtype=torch.complex128)


torch.cuda.synchronize()    # before
torch.triangular_solve(b, a, upper=True, unitriangular=True, transpose=True)
torch.cuda.synchronize()    # after
```

Sample failure messages:
```
Traceback (most recent call last):
  File "e.py", line 15, in <module>
    torch.cuda.synchronize()    # after
  File "/opt/pytorch/pytorch/torch/cuda/__init__.py", line 495, in synchronize
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

The test only fails on A100 randomly, but passes on V100, M60, and other GPUs. However, if `CUDA_LAUNCH_BLOCKING=1` is set, the test passed. I guess there might be concurrency issues. It could be that the test was set up incorrectly.

### Versions

Test started failing after https://github.com/pytorch/pytorch/pull/68709 was merged.

1.11.0a0+gitff78c73
cuda 11.5
A100

cc @nikitaved @pearu @cpuhrsch @ngimel @jianyuh @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @ptrblck

**Comment by IvanYashchuk** [comment]
Is it only complex128 dtype that fails? I don't have an access to A100 to reproduce the failure.

**Comment by xwang233** [comment]
I just checked other 3 dtypes complex64, float32, float64, and they all failed. It could be that `complex128` ranks the first in alphabetical order and its CUDA failure stops the testing process.

**Comment by xwang233** [comment]
Update: With pytorch cuda caching allocator disabled, the test seems passed. It probably indicates some kind of race conditions in memory usages in pytorch sparse code.

```bash
export PYTORCH_NO_CUDA_MEMORY_CACHING=1
```
