### ISSUE TITLE
The random seed will fail when using the repeat_interleave function， the result is not reproducible.

### ISSUE THREAD

**Issue by chenchkx** [pytorch/pytorch#71296]
### 🐛 Describe the bug

The random seed will fail when using the repeat_interleave function， the result is not reproducible.

### Versions

torch1.10.0-cuda102

cc @pbelevich

**Comment by ngimel** [comment]
Backward of `repeat_interleave` is not deterministic https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html?highlight=repeat_interleave

**Comment by mzh1996** [comment]
same problem here
it costs me 2 days to find out the reasons...
using the ```repeat``` function instead

**Comment by ngimel** [comment]
You can enable deterministic mode to see if you are using non-deterministic functions, it doesn't have to be 2 days.
