### ISSUE TITLE
DISABLED test_checkpoint_fsdp_wrapping_cpu_offload_CPUOffload(offload_params=True)_offload_activations_True (__main__.TestFSDPCheckpoint)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#71349]
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_checkpoint_fsdp_wrapping_cpu_offload_CPUOffload(offload_params%3DTrue)_offload_activations_True%2C%20TestFSDPCheckpoint)).

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by clee2000** [comment]
I'm fairly sure this test either got renamed or doesn't exist anymore
