### ISSUE TITLE
{TypeError}pad_sequence(): argument 'sequences' (position 1) must be tuple of Tensors, not Tensor

### ISSUE THREAD

**Issue by douglascvas** [pytorch/pytorch#71365]
### 🐛 Describe the bug

Command:
```python
import torch

seq = torch.nn.utils.rnn.pad_sequence(torch.tensor([[[ 7,  6]], [[-7, -1]]]))
```

When I execute the command above with pytorch 1.10.1 I get this error: 
> {TypeError}pad_sequence(): argument 'sequences' (position 1) must be tuple of Tensors, not Tensor"

On pytorch 1.8.1 it works though. What is wrong there? Has anything changed?

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Linux Mint 20.2 (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.0
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchvision==0.11.2+cu113
[conda] _pytorch_select           0.1                       cpu_0  
[conda] blas                      1.0                         mkl  
[conda] libmklml                  2019.0.5                      0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py39he8ac12f_0  
[conda] mkl_fft                   1.3.0            py39h54f3939_0  
[conda] mkl_random                1.0.2            py39h63df603_0  
[conda] numpy                     1.22.0                   pypi_0    pypi
[conda] numpy-base                1.19.2           py39h2ae0177_0  
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] torchvision               0.11.2+cu113             pypi_0    pypi

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
Thanks for the report.
Most likely due to https://github.com/pytorch/pytorch/pull/57868 that used to work with any sequence like object as input (thus including Tensor). But the c++ side is expecting a tuple.
We can fix the python function to ensure the input is a sequence and convert it to a tuple(Tensor) as expected in the backend.
cc @jbschlosser does that sound good?

**Comment by jbschlosser** [comment]
Yep something like that should do the trick! Note that `Tensor` is not a `Sequence`, but we could verify that the input is an `Iterable` and convert that to a tuple of tensors.
