### ISSUE TITLE
There is no branch named v0.4.0

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#7136]
It would be great if there is a branch named v0.4.0 like other released branches.

```
$ git branch --all   
...
  remotes/origin/v0.1.12
  remotes/origin/v0.2.0
  remotes/origin/v0.3.0
  remotes/origin/v0.3.1
...
```

**Comment by soumith** [comment]
there is a tag named 0.4.0: https://github.com/pytorch/pytorch/tree/v0.4.0
You probably have to `git pull`
