### ISSUE TITLE
Adding node and cell names for tensorboard graph

### ISSUE THREAD

**Issue by promach** [pytorch/pytorch#71361]
### 🚀 The feature, motivation and pitch

I am trying to trace the tensorboard graph for https://github.com/promach/gdas

However, from what I can observe so far, the tensorboard graph generated from [torch.utils.tensorboard](https://pytorch.org/docs/stable/tensorboard.html) does not really indicate user-understandable node names and cell names which makes it so difficult for tracking down the connections within the graph.

Any suggestions ?

![image](https://user-images.githubusercontent.com/3324659/149645149-0ecea1f2-96ce-41ae-a1a2-cf2a599fc863.png)

### Additional context

See https://github.com/tensorflow/tensorboard/issues/5505 for more context.

**Comment by samdow** [comment]
Hi @promach thanks for the issue. We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/

I'm seeing other people on the forums with named nodes, like you want so they should be able to help 😄

**Comment by promach** [comment]
@samdow I am not using `nn.sequential()` which might be the reason that there are no named nodes ?

**Comment by promach** [comment]
@samdow See https://discuss.pytorch.org/t/adding-node-and-cell-names-for-tensorboard-graph/142059

**Comment by promach** [comment]
@samdow A tensorflow guy told me to debug [why there are no nodes names passed into PyTorch implementation of the summary writer](https://github.com/tensorflow/tensorboard/issues/5505#issuecomment-1030940813)

Could you advise how to do this specifically ?

**Comment by samdow** [comment]
Hi, per my previous comment this question is more appropriate for the forums. We use github issues only for bug reports or feature requests
