### ISSUE TITLE
`torch.linalg.tensorsolve(A, B)` is inconsistent with `tensordot(inv(A), B)`

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#71384]
### 🐛 Describe the bug

Based on the [documentation](https://pytorch.org/docs/stable/generated/torch.linalg.tensorinv.html) of `torch.linalg.tensorinv`, `tensorsolve(A, B) == torch.tensordot(tensorinv(A), B)`. However, when the input is empty, `tensorsolve` will succeed but the latter will fail. For example,

```python
import torch
A = torch.rand([0, 4, 4, 3, 0], dtype=torch.float64)
B = torch.rand([0, 3, 3], dtype=torch.float64)
print(torch.linalg.tensorsolve(A, B))
# tensor([], size=(3, 0), dtype=torch.float64)
x = torch.linalg.tensorinv(A)
torch.tensordot(x, B)
# RuntimeError: contracted dimensions need to match, but first has size 4 in dim -1 and second has size 3 in dim 1
```

Besides, there are some cases that `tensorsolve` fails but the latter succeeds. For example,
```python
import torch
A= torch.rand([6, 4, 4, 3, 2], dtype=torch.float64)
B= torch.rand([6, 4, 2], dtype=torch.float64)

x = torch.linalg.tensorinv(A)
print(torch.tensordot(x, B))
# succeed

print(torch.linalg.tensorsolve(A, B))
# RuntimeError: Expected self to satisfy the requirement prod(self.shape[other.ndim:]) == prod(self.shape[:other.ndim]), but got 6 != 48
```

### Versions

pytorch: 1.10.1

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by mruberry** [comment]
@Lezcano would you take a look at this? This may just be a docs issue. The docs for linalg.tensorinv also have some formatting issues we may want to correct.
