### ISSUE TITLE
`torch.linalg.solve` is not consistent with `A.inv @ B`

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#71385]
### 🐛 Describe the bug

Similar with https://github.com/pytorch/pytorch/issues/71384, based on the [documentation](https://pytorch.org/docs/1.10.1/generated/torch.linalg.inv.html?highlight=linalg%20inv#torch.linalg.inv) of `torch.linalg.inv`, `torch.linalg.solve(A, B) == A.inv() @ B`. But there some some conterexamples:

```python
import torch
A = torch.rand([2, 3, 3], dtype=torch.float64)
B = torch.rand([2, 3], dtype=torch.float64)
print(torch.linalg.solve(A, B))
# succeed
torch.linalg.inv(A) @ B
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (6x3 and 2x3)
```

### Versions

pytorch: 1.10.1

cc @brianjo @mruberry @jianyuh @nikitaved @pearu @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nikitaved** [comment]
It is not a big nor inconsistency. Solve accepts B as a batch of either vectors (the case in the repro) or matrices, while matmul only expects matrices, so shapes (2, 3, 3) and (2, 3) are inconsistent because you cannot multiply matrices of shape (3, 3) and (2, 3).

**Comment by malfet** [comment]
I think there are 2 issues: 
 - Update documentation
 - Fix error message (as `torch.linalg.inv(A).shape` is `[2, 3, 3]`)

**Comment by Lezcano** [comment]
It might be the case that this other issue is related https://github.com/pytorch/pytorch/issues/71384

**Comment by ajcost** [comment]
Hello,

Long time user of Pytorch but first time contributor. Not sure if anybody is working on this, but happy to try to resolve both this (#71385) and #71384 . Let me know!

**Comment by IvanYashchuk** [comment]
Hey @ajcost, thanks for offering help with this one! Documentation for the linear algebra module can be found in [`torch/linalg/__init__.py`](https://github.com/pytorch/pytorch/blob/master/torch/linalg/__init__.py). Once you open a pull request a bot would create a preview webpage. You can also check how your changes render using [the instructions from the CONTRIBUTING file](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#building-documentation).

**Comment by ajcost** [comment]
I drafted a PR at #71769, let me know if this is the right direction
