### ISSUE TITLE
cannot pickle 'torch._C.Generator' object for torch.Generator

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#71398]
### 🐛 Describe the bug

Deepcopy error when copying torch.Generator

```
import torch
x = torch.Generator().manual_seed(2)
import copy
copy.deepcopy(x)
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'torch._C.Generator' object
```

### Versions

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.5.0
[pip3] torch==1.10.0
[pip3] torchmetrics==0.6.2
[pip3] torchvision==0.11.0
[conda] Could not collect

cc @pbelevich

**Comment by ringohoffman** [comment]
Related: https://github.com/pytorch/pytorch/issues/11340
