### ISSUE TITLE
Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend

### ISSUE THREAD

**Issue by mikel-brostrom** [pytorch/pytorch#71402]
### 🐛 Describe the bug

I exported a custom model to torchscript by:

```python
def export_torchscript(model, im, model_name, optimize):
    # TorchScript model export
    try:
        logging.info(f'\nstarting export with torch {torch.__version__}...')
        f = Path('model.torchscript')

        ts = torch.jit.trace(model, (im, im), strict=False)
        print(ts(im, im))
        d = {"shape": im.shape, "names": model_name}
        extra_files = {'config.txt': json.dumps(d)}  # torch._C.ExtraFilesMap()
        if optimize:  # https://pytorch.org/tutorials/recipes/mobile_interpreter.html
            # Export mobile interpreter version model (compatible with mobile interpreter)
            optimize_for_mobile(ts)._save_for_lite_interpreter(str(f), _extra_files=extra_files)
        else:
            ts.save(str(f), _extra_files=extra_files)

        logging.info(f'export success, saved as {f} ({file_size(f):.1f} MB)')
        return f
    except Exception as e:
        logging.info(f'export failure: {e}')
```

I have no errors nor warnings during this process. However, when i try to load it on in a c++ application ( after building the application following https://pytorch.org/tutorials/advanced/cpp_export.html) by:

```c++
#include <torch/script.h> // One-stop header.

#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
  if (argc != 2) {
    std::cerr << "usage: example-app <path-to-exported-script-module>\n";
    return -1;
  }

  torch::jit::script::Module module;
  try {
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load(argv[1]);
  }
  catch (const c10::Error& e) {
    std::cerr << "\n\nError loading the model\n\n";
    std::cerr << e.what_without_backtrace();
    return -1;
  }

  std::cout << "Model loaded successfully\n";

  torch::NoGradGuard no_grad; // ensures that autograd is off
  module.eval(); // turn off dropout and other training-time layers/functions

  // Create a vector of inputs.
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(torch::ones({1, 3, 640, 256}));
  inputs.push_back(torch::ones({1, 3, 640, 256}));

  // Execute the model and turn its output into a tensor.
  at::Tensor output = module.forward(inputs).toTensor();
  std::cout << output.slice(/*dim=*/1, /*start=*/0, /*end=*/5) << '\n';
}

```

I get the following error:

```bash
Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty_strided' is only available for these backends: [CPU, Meta, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:18433 [kernel]
Meta: registered at aten/src/ATen/RegisterMeta.cpp:12703 [kernel]
BackendSelect: registered at aten/src/ATen/RegisterBackendSelect.cpp:665 [kernel]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: fallthrough registered at ../aten/src/ATen/ConjugateFallback.cpp:22 [kernel]
Negative: fallthrough registered at ../aten/src/ATen/native/NegateFallback.cpp:22 [kernel]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_2.cpp:10491 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_2.cpp:11425 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.0 (default, Feb 25 2021, 22:10:10)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-67-generic-x86_64-with-glibc2.27
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P2000
Nvidia driver version: 450.102.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[conda] Could not collect

**Comment by davidberard98** [comment]
@mikel-brostrom It looks to me like your c++ binary is missing cuda libraries.

Could you try something like this? (see the extra line added to the `CMakeLists.txt` from the example you linked)

```cmake
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(custom_ops)

find_package(Torch REQUIRED)

add_executable(example-app example-app.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
target_link_libraries(example-app "${TORCH_CUDA_LIBRARIES}") # <-- add this line
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)
```

**Comment by mikel-brostrom** [comment]
Thank you for your time @davidberard98,

So, when I run:

`cmake -DCMAKE_PREFIX_PATH=/home/mikel.brostrom/Documents/libtorch ..`

linking to the CPU LibTorch version (https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.10.1%2Bcpu.zip)
I still get the error in my first post when running the app with `./example-app ../model.torchscript`. But when I run:

`cmake -DCMAKE_PREFIX_PATH=/home/mikel.brostrom/Documents/libtorch ..`

linking to the CUDA LibTorch version (https://download.pytorch.org/libtorch/cu113/libtorch-shared-with-deps-1.10.1%2Bcu113.zip) I get:

```bash
cmake -DCMAKE_PREFIX_PATH=/home/mikel.brostrom/Documents/libtorch_cpu ..
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH) 
CMake Warning at /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Caffe2/public/cuda.cmake:111 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)


-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Error at /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
```

I hope this adds some clarity to my problem

**Comment by mikel-brostrom** [comment]
I found out what the issue was.

In my model I had one line of code that was causing the error:

    if torch.cuda.is_available():
        weight = weight.cuda()

If you have a look at the official documentation for trace (https://pytorch.org/docs/stable/generated/torch.jit.trace.html) you will see that

> the returned ScriptModule will always run the same traced graph on any input. This has some important implications when your module is expected to run different sets of operations, depending on the input and/or the module state

So, as I traced the model on a machine with GPU this operation was recorded and make it impossible to run the model on any machine without GPU. To make this happen you need to make sure that you model is traced in such way that it makes it CPU compatible

**Comment by mikel-brostrom** [comment]
One question is still unresolved. Why do I get this error:

```bash
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH) 
CMake Warning at /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Caffe2/public/cuda.cmake:111 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)


-- /usr/local/cuda/lib64/libnvrtc.so shorthash is 08c4863f
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
CMake Error at /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /home/mikel.brostrom/Documents/libtorch_cuda/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/mikel.brostrom/torchscript_app/build/CMakeFiles/CMakeOutput.log".
See also "/home/mikel.brostrom/torchscript_app/build/CMakeFiles/CMakeError.log".
```

When running: 

`cmake -DCMAKE_PREFIX_PATH=/home/mikel.brostrom/Documents/libtorch_cuda ..`

where `/home/mikel.brostrom/Documents/libtorch_cuda` is the path to the CUDA LibTorch version (https://download.pytorch.org/libtorch/cu113/libtorch-shared-with-deps-1.10.1%2Bcu113.zip). Shouldnät CUDNN be included in the extracted LibTorch folder?

**Comment by davidberard98** [comment]
I'm not really sure whether cuDNN is expected to be packaged with pytorch.

Some options here would be:
1. Get cuDNN
2. Build pytorch from source (based on this error message "Your installed Caffe2 version uses cuDNN but I cannot find cuDNN", I'm guessing that if pytorch is built from source it will not expect cuDNN when you build your c++ binary)
3. Stop using cuda

Another option (in case you're not familiar with it) is [torch.jit.script](https://pytorch.org/docs/stable/generated/torch.jit.script.html). It will allow you to keep the `if torch.cuda.is_available():` check.

**Comment by mikel-brostrom** [comment]
Both the CPU and CUDA version of LibTorch seem to contain some cudnn related stuff

```bash
/home/mikel.brostrom/Documents/libtorch_cpu/include/ATen/cudnn
/home/mikel.brostrom/Documents/libtorch_cpu/include/ATen/cudnn/cudnn-wrapper.h
/home/mikel.brostrom/Documents/libtorch_cpu/include/caffe2/core/cudnn_wrappers.h
/home/mikel.brostrom/Documents/libtorch_cpu/include/caffe2/core/common_cudnn.h
/home/mikel.brostrom/Documents/libtorch_cpu/include/caffe2/operators/conv_op_cache_cudnn.h
/home/mikel.brostrom/Documents/libtorch_cpu/include/caffe2/operators/activation_ops_cudnn.h
/home/mikel.brostrom/Documents/libtorch_cpu/include/caffe2/operators/op_utils_cudnn.h
```

```bash
/home/mikel.brostrom/Documents/libtorch_cuda/include/ATen/cudnn
/home/mikel.brostrom/Documents/libtorch_cuda/include/ATen/cudnn/cudnn-wrapper.h
/home/mikel.brostrom/Documents/libtorch_cuda/include/caffe2/core/cudnn_wrappers.h
/home/mikel.brostrom/Documents/libtorch_cuda/include/caffe2/core/common_cudnn.h
/home/mikel.brostrom/Documents/libtorch_cuda/include/caffe2/operators/conv_op_cache_cudnn.h
/home/mikel.brostrom/Documents/libtorch_cuda/include/caffe2/operators/activation_ops_cudnn.h
/home/mikel.brostrom/Documents/libtorch_cuda/include/caffe2/operators/op_utils_cudnn.h
```


1. I downloaded cudnn here: https://developer.nvidia.com/rdp/cudnn-download and installed it. However, when I run `which nvcc` to check whether CUDNN was installed correctly or not I get `nvcc not found`
2. Will try this in case that nothing else works
3. I don't have any CUDA related stuff in my C++ program as you can see in my first message

**Comment by Tumb1eweed** [comment]
I met the same problem...
Here is my model code, I delete the "torch.cuda.is_available":
`import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()

        self.conv1 = nn.Conv1d(in_channels=2,
                               out_channels=16,
                               kernel_size=3,
                               padding=1)
        self.conv2 = nn.Conv1d(in_channels=16,
                               out_channels=32,
                               kernel_size=3,
                               padding=1)
        self.pool = nn.MaxPool1d(2)
        self.fc1 = nn.Linear(32*256, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 32*256)
        output = self.fc1(x)
        return output

model = torch.jit.script(ConvNet())
torch.jit.save(model, 'sample.pt')`

And I run my gtest, use torch.jit.load, the same problem happened.
![lALPJvuSz0Jz0c7Mjc0GFg_1558_141](https://user-images.githubusercontent.com/27768261/167084617-a525d9a9-5b81-44b8-8e4a-f697dd5a5bdc.png)

(A little diffrent, those libtorch libraries I use conan to install from my own artifactory)
![image](https://user-images.githubusercontent.com/27768261/167084933-d1ba5b26-4a2a-4300-9935-5fbf3dbcc7a1.png)

**Comment by BenLag2906** [comment]
Hi ALL,
 I have the same issu.

Did you found a solution ?

![code](https://user-images.githubusercontent.com/26578899/203279427-dab1d06a-627e-4b72-aef4-1b7b6929f6c1.png)

Thanks in advance

**Comment by JianhuanZhuo** [comment]
get the same problem, any progress?

**Comment by Tumb1eweed** [comment]
try use "-Wl,--no-as-needed" in compile options

**Comment by why-ace** [comment]
before load ：
LoadLibraryA("ATen_cuda.dll");
LoadLibraryA("c10_cuda.dll");
LoadLibraryA("torch_cuda.dll");
LoadLibraryA("torchvision.dll");

**Comment by William9Baker** [comment]
> Hi ALL, I have the same issu.
> 
> Did you found a solution ?
> 
> ![code](https://user-images.githubusercontent.com/26578899/203279427-dab1d06a-627e-4b72-aef4-1b7b6929f6c1.png)
> 
> Thanks in advance

在 链接器->命令行 中写入 /INCLUDE:?warp_size@cuda@at@@YAHXZ 即可。

**Comment by HiDPICoder** [comment]
Hope this helps some of you even if it is in python and not c++.

I trained a Unet on pc that had AMD card. I wanted to run model on pc that had NVIDIA card. Got the same aten::empty_strided.
This is the code that helped me solved it. 

checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
clean_state_dict = {}
for key, tensor in checkpoint['model_state_dict'].items():
  clean_state_dict[key] = tensor.cpu().clone().detach().to(device)
    
model.load_state_dict(clean_state_dict)

after loading model like this all I need to do was saved it.

On pc with NVIDIA card all I need was to run this code:
model = UNet().to(device)
model.eval()
checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
model.load_state_dict(checkpoint['model_state_dict'])

My Unet performed absolutely fine.

What seems to have caused the issue for me was that I was saving a lot of info to the file:
 torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': avg_loss,
            'best_loss': min(best_loss, avg_loss)
        }, checkpoint_path)
