### ISSUE TITLE
torch.linalg.solve updates are causing GPyTorch tests to fail

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#71406]
Since https://github.com/pytorch/pytorch/pull/69752 the tests `test_minres_mat`:

https://github.com/cornellius-gp/gpytorch/blob/2489afb17d53166ee693ebd86b6cf9e152013ce6/test/utils/test_minres.py#L55

and `test_minres_mat_multiple_shifts`:

https://github.com/cornellius-gp/gpytorch/blob/2489afb17d53166ee693ebd86b6cf9e152013ce6/test/utils/test_minres.py#L61

are failing in GPyTorch.

cc @ezyang @gchanan @zou3519 @bdhirsh @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @Balandat

**Comment by Balandat** [comment]
I'm not familiar with that particular test but it appears there are suddenly NaNs appearing in the output of `torch.linalg.solve` where they previously didn't, which is a bit concerning... Should be pretty easy to do a minimal repro just by comparing the solve on the matrix used here.
