### ISSUE TITLE
[rpc] Wrong usage of RRefContext::handleException

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#71458]
### 🐛 Describe the bug

Usage of `RRefContext::handleException` in `torch/csrc/distributed/rpc/rref_context.cpp` is wrong when the future has an error.

`RRefContext::handleException` uses `TORCH_CHECK` which throws.

Callers of `RRefContext::handleException` don't expect that and run code after it without any guarding.

 

### Versions

master

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jjlilley @mrzzd

**Comment by PurnaChandraMansingh** [comment]
Hi @kumpera,
I am new to Open Source and want to start contributing, can I work on this issue?

**Comment by wanchaol** [comment]
@kumpera if i understand correctly, `TORCH_CHECK` throws only if the jit_future has error, are you referring that usage of `RRefContext::handleException` does not expect itself to throw, and runs more error handling code after that? Do we have a example usage where it does more handling after the call of `RRefContext::handleException`?

**Comment by ykabusalah** [comment]
Hello, I see not much work has been done on this since January 25. Would I be able to get started on working on this issue?

**Comment by kumpera** [comment]
> Hello @kumpera , I see not much work has been done on this since January 25. Would I be able to get started on working on this issue?

Yes, feel free to work on this issue.

**Comment by ykabusalah** [comment]
Can you please assign me to the issue?

**Comment by Shinicii** [comment]
Hi, I'm new to github, I'm good with c++ can I work on this issue?

**Comment by joshua-xia** [comment]
@kumpera I am working on this issue and will provide the patch ASAP, Thanks!
