### ISSUE TITLE
Unexpected behaviour of `torch.nn.CosineSimilarity`

### ISSUE THREAD

**Issue by mradul2** [pytorch/pytorch#71468]
### 🐛 Describe the bug

[torch.nn.CosineSimilarity](https://pytorch.org/docs/1.9.1/generated/torch.nn.CosineSimilarity.html) should calculate the cosine similarity between two tensors `x1` and `x2` along the specified dimension `d`. And according to the documentation, both `x1` and `x2` should be of the same shape. But for the torch version `1.10.1` the following code snippet works: 

```python
import torch
CS = torch.nn.CosineSimilarity(dim=1)
a = torch.randn(20,1204,41,41)
b = torch.randn(1204,1,1)
c = CS(a, b)
print(c.shape)
```

And gives the output: 
```bash 
torch.Size([20, 41, 41])
```

For torch version `1.9.1` the same script throws the following error: 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-411fa0377af6> in <module>()
----> 1 c = CS(a, b)
      2 c.shape

1 frames
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/distance.py in forward(self, x1, x2)
     73 
     74     def forward(self, x1: Tensor, x2: Tensor) -> Tensor:
---> 75         return F.cosine_similarity(x1, x2, self.dim, self.eps)

RuntimeError: The size of tensor a (41) must match the size of tensor b (1204) at non-singleton dimension 1
```

### Versions

PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.12 (default, Sep 10 2021, 00:21:48)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111
[conda] Could not collect

**Comment by ngimel** [comment]
In 1.10 CosineSimilarity became more permissive (and 1.10 docs reflect that), this is expected behavior.
