### ISSUE TITLE
[numpy compat] torch.stack doesn't support nested list+tensors (NumPy does support)

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#71479]
### 🐛 Describe the bug

```python
import numpy as np
import torch

a = np.array([1,2,3])
print(np.stack([[a, a, a, a], [a, a, a, a]]).shape)
# (2, 4, 3)

b = torch.tensor([1,2,3])
print(torch.stack([[b, b, b, b], [b, b, b, b]]).shape)
# TypeError: expected Tensor as element 0 in argument 0, but got list
```
A simple alternative would involve two additional calls of `torch.stack` leading to memory overhead. A more contrived alternative is a single stack + reshape, but one should think to make sure that the tensors are provided in the flat list in the order consistent with reshape.

### Versions

1.9.1

cc @mruberry @rgommers

**Comment by Puranjay-del-Mishra** [comment]
Hello. 
I feel the error is obvious, as the torch.stack concatenates a sequence of tensors into a pytorch tensor. It received a list of lists which is why it throws this error.

**Comment by rgommers** [comment]
I'm pretty sure this is a wontfix, PyTorch functions should not be accepting lists as input.

> A more contrived alternative is a single stack + reshape, but one should think to make sure that the tensors are provided in the flat list in the order consistent with reshape.

There are multiple alternatives, like `torch.tile(a, (2, 4, 1))`.

**Comment by vadimkantorov** [comment]
> There are multiple alternatives, like `torch.tile(a, (2, 4, 1))`.

This is a straw suggestion. In practice all the tensor sub-arguments are different (otherwise tile is of course the right solution). I found this issue by upgrading to torch a real-world use-case: https://github.com/open-mmlab/mmdetection/blob/a32d7d40bfe2277f255bf71911a27a76ff871eb2/mmdet/datasets/pipelines/auto_augment.py#L433

> PyTorch functions should not be accepting lists as input.

Not sure what you mean. torch.stack is already accepting lists as input. Another frequent usecase about accepting lists is https://github.com/pytorch/pytorch/issues/27522. Previous discussions about general accepting lists: https://github.com/pytorch/pytorch/issues/33042, https://github.com/pytorch/pytorch/issues/46138

I realize that accepting **nested lists of tensors** may be not worth of support, but I propose that this departure from NumPy is documented somewhere or that the error message is clearly explaining this departure.

A middle ground may also be torch.stack / torch.cat supporting a bit more of nested lists as constructor functions

**Comment by valid999** [comment]
The answer for the torch.stack with this problem  "TypeError: expected Tensor as element 0 in argument 0, but got float "  replace torch.stack with  torch.tensor .
