### ISSUE TITLE
The signature of `Tensor.tile` in the doc is wrong

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#71476]
### 📚 The doc issue

The signature of `Tensor.tile` in the doc is wrong: `Tensor.tile(*reps)`. But it should be `Tensor.tile(dims)` based on `torch.tile(input, dims)`

### Suggest a potential alternative/fix

`Tensor.tile(dims)`

cc @brianjo @mruberry

**Comment by mruberry** [comment]
Thanks for reporting this issue, @TestSomething22. We would accept a PR fixing this.

**Comment by JennyChristopher** [comment]
I would like to work on this issue. Could it be kindly assigned to me ?
