### ISSUE TITLE
Module: parameters are not included if the module is initialized in a list

### ISSUE THREAD

**Issue by kyunghyuncho** [pytorch/pytorch#715]
The code like below in __init__ of a new `nn.module`

```
       self.hids = []
        for li in xrange(options['n_layers']):
            self.hids.append([
                nn.Linear(options['n_hid'], options['n_hid']),
                eval('nn.{}'.format(options['act']))()
                ])
            indim = options['n_hid']

        self.classifier = nn.Linear(options['n_hid'], 3)
```

The parameters of `nn.Linear` in the for-loop are not included in `parameters`, as can be seen below:

```
<bound method SNLINet.parameters of SNLINet (
  (classifier): Linear (256 -> 3)
  )
)>
```

**Comment by kyunghyuncho** [comment]
A work-around I found is to manually register each module by calling `add_module`. Though, this can work, but this breaks consistency. It'll be better if we need to `add_module` everything manually, or `add_module` is done automatically even if the module is not a direct child.

**Comment by apaszke** [comment]
yes, that is expected. You can build a list of modules, and wrap them in `nn.ModuleList` and assign that as `self.hids`. This will register them properly.
