### ISSUE TITLE
GHA: Use retryable steps

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71563]
### 🚀 The feature, motivation and pitch

Today we have a lot of retries that we just tack onto certain flaky calls, and we are forever whack-a-moling additional flaky commands with these "dumb" retries.

We should investigate the idea of a retryable GHA step (like here https://github.com/marketplace/actions/retry-step) and have a bigger retry framework.

For example: https://github.com/pytorch/pytorch/pull/73254 tackles retrying the `Install nvidia driver, nvidia-docker runtime, set GPU_FLAG` step, which is a perfect candidate as it is sometimes flaky and it is a small step to retry.

Use retryable step similar to how it's used in [here](https://github.com/pytorch/pytorch/blob/bbf4bc9f8e1ca4d4de41b2ffba80a318feba4b11/.github/templates/linux_ci_workflow.yml.j2#L209-L217) for the following job steps:
- [x] #73701
- [ ] .github/actions/setup-win/action.yml steps with retrys
    - [ ] #76972
    - [ ] Enable long paths on Windows
    - [ ] Disables Windows Defender scheduled and real-time scanning for files in pytorch directory.
    - [ ] Install Visual Studio 2019 toolchain
    - [x] #76666
    - [ ] Setup Python3 --> a little tricky since it uses another action.
- [ ] Run actionlint (see https://github.com/pytorch/pytorch/actions/runs/2150348071/attempts/1)

### Alternatives

Write our own infra to support retrying steps

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
Potentially good candidate to retry: https://github.com/pytorch/pytorch/runs/5391828478?check_suite_focus=true

**Comment by ZainRizvi** [comment]
We have retryable steps now
