### ISSUE TITLE
Merge to master currently blocked

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#71592]
## Current Status
ongoing

## Error looks like
Merges through fbcode are currently not getting propagated to master

## Incident timeline (all times pacific)

- 1/20 1:05p https://github.com/pytorch/pytorch/commit/5ed8d0dfae6dcf8bacaf6e4229e7b40b5c2b2446 fbsync merge to master fails

## User impact
Can't merge to master.

## Root cause
*What was the root cause of this issue?*

## Mitigation
@seemethere run `.github/script/syncbranches.py` manually

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
Filed CI ticket: https://support.github.com/ticket/personal/0/1470467

**Comment by malfet** [comment]
Seems mitigated, see https://github.com/pytorch/pytorch/actions/workflows/syncbranches.yml

**Comment by seemethere** [comment]
Error message looks like: `failed: fatal commit_refs`

**Comment by seemethere** [comment]
AI: Add retry to syncbranches push (maybe with a delay / backoff)

**Comment by sanchitintel** [comment]
Hi, what does `merge fbsync to master` mean?
Thank you!
