### ISSUE TITLE
Register THNN double and half backends

### ISSUE THREAD

**Issue by danielamassiceti** [pytorch/pytorch#716]
I am having trouble with moving things into double precision with CUDA.

```
x = Variable(torch.DoubleTensor(10,10)).cuda()
emb = nn.Embedding(10, 10).double().cuda()
out = emb(x)
```

Gives me the following error 
File "***/torch/_thnn/__init__.py", line 15, in __getitem__
    return self.backends[name].load()
KeyError: <class 'torch.cuda.DoubleTensor'>

Any thoughts as to why this is?

**Comment by apaszke** [comment]
Yeah, that needs to be fixed. Should be done this weekend. Thanks for the report!

**Comment by apaszke** [comment]
Added in #734.
