### ISSUE TITLE
iOS tests were dropped from CI during CircleCI->GHA migration

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#71617]
### 🐛 Describe the bug

I.e. this step
https://github.com/pytorch/pytorch/blob/9f0227a0ebde20eb50ff2ddc7e224a3a28a40ad2/.circleci/verbatim-sources/job-specs/job-specs-custom.yml#L523-L530
Could not be found anywhere in
https://github.com/pytorch/pytorch/blob/9f0227a0ebde20eb50ff2ddc7e224a3a28a40ad2/.github/templates/ios_ci_workflow.yml.j2#L84-L88

### Versions

N/A

cc @ezyang @gchanan @zou3519 @bdhirsh @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Assigning this to myself

**Comment by malfet** [comment]
Closing as iOS simulator tests has been enabled
