### ISSUE TITLE
Complex GRU does not work

### ISSUE THREAD

**Issue by jonahgluck** [pytorch/pytorch#71614]
### 🐛 Describe the bug

Observed results:
The dtypes don't match even though the tensor is cast to a ComplexFloat.

```bash
>>> torch.__version__
'1.10.1'
>>> torch.nn.GRU(5, 1)(torch.zeros(3, 4, 5, dtype=torch.complex64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jonah/opt/anaconda3/envs/hvac/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/jonah/opt/anaconda3/envs/hvac/lib/python3.9/site-packages/torch/nn/modules/rnn.py", line 849, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: expected scalar type ComplexFloat but found Float
```

Possibly related to [#43477](https://github.com/pytorch/pytorch/issues/43477)

### Versions

Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 08:50:36)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.21.2           py39h4b4dc7a_0  
[conda] numpy-base                1.21.2           py39he0bd621_0  
[conda] torch                     1.10.1                   pypi_0    pypi
[conda] torchvision               0.11.2                   pypi_0    pypi

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by Lezcano** [comment]
You are missing to cast the module to the type you're using:
```python
torch.nn.GRU(5, 1).to(torch.complex64)(torch.zeros(3, 4, 5, dtype=torch.complex64))
```

**Comment by jonahgluck** [comment]
Thank you. Is this functionality cpu only at the moment?
