### ISSUE TITLE
`torch.linalg.solve` INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#71610]
### 🐛 Describe the bug

`torch.linalg.solve` can trigger INTERNAL ASSERT FAILED randomly. For example,

```python
import torch
input = torch.rand([2, 0, 5, 5], dtype=torch.complex128)
A = torch.rand([1, 5, 5], dtype=torch.complex128)
torch.linalg.solve(A, input)
# RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/native/LinearAlgebraUtils.h":244, please report a bug to PyTorch. linalg_solve: (Batch element 0): Argument 335551511 has illegal value. Most certainly there is a bug in the implementation calling the backend library.
```
You should run the code a few times to trigger the internal fail.

### Versions

pytorch: 1.10.1

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by malfet** [comment]
That's a nice one: should probably throw an exception when ether of the tensors is empty

**Comment by Lezcano** [comment]
The problem here is that they are not broadcastable, right?
I think the sizes should be checked, and then in the main function, if the tensors are empty there's nothing to do, so you can return early.
