### ISSUE TITLE
libtorch cannot be consumed by C++20 project

### ISSUE THREAD

**Issue by dipidoo** [pytorch/pytorch#71657]
### 🐛 Describe the bug

Somewhat related to #69290, `std::result_of` is removed from C++20 and instead of resulting in warning, it results in error.

For example:
https://github.com/pytorch/pytorch/blob/085e2f7bddc45f859fcdb786926d60d709b2daa0/c10/util/C%2B%2B17.h#L167

My plan to fix is, for example:
```C++
#if __cpp_lib_is_invocable
    typename std::invoke_result<Functor && , Args && ...>::type>::type
#else
    typename std::result_of<Functor && (Args && ...)>::type>::type
#endif
```
because `std::invoke_result` is introduced in C++17, the fallback enables consumption by C++11 and C++14.

I can submit fix soon, if these 2 questions are answered:
1. Does the fix plan look OK?
2. By default, I will address only the headers. Should I also apply it on the implementation sources as well?

### Versions

(script is not applicable)

downloaded from: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.7.1%2Bcpu.zip
MSVC 19.30.30706 for x64, Visual Studio 2022 Version 17.0.4

cc @jbschlosser

**Comment by malfet** [comment]
Thank you for proposing to fix the issue. Solution sounds reasonable, i would gladly review the PR. 
A small suggestion - perhaps `#if defined(__cpp_lib_is_invocable) ` then `c10:guts::invoke` can simply be aliased to `std::invoke`, similar to 
https://github.com/pytorch/pytorch/blob/f269f990f232233738176a6e406390d8b3392348/c10/util/C%2B%2B17.h#L50-L53

**Comment by xsacha** [comment]
It's just a rename of std::invoke to std::result_of

There is also a templated hash size that can be changed to size_t (or equivalent). I have to keep replacing this in headers.

**Comment by hinmanj** [comment]
https://github.com/pytorch/pytorch/issues/71309#issuecomment-1013672816
