### ISSUE TITLE
ComplexHalf support

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#71680]
Currently our ComplexHalf support is in a bad state. Users file issues complaining that ops on ComplexHalf issues trigger internal asserts (#71671, #71635) and that shouldn't happen even if particular op is not supported for ComplexHalf, the error message should state that datatype is not supported. We have 2 options going forward: disable ComplexHalf completely (#70606) or support it for real. 
Disabling is relatively easy, we already have a PR for this. 
However, there  are requests to enable ComplexHalf because users would like to take advantage of better half performance on the GPUs (see e.g. #67324, https://github.com/pytorch/audio/issues/2097). 
This issue is to track enabling ComplexHalf should we decide to do that. At a minimum, the steps would be
1) Enable common pointwise and reduction ops. Currently those ops for 2 complex datatypes that we support take approximately 40 MB of cuda context size, adding another complex type would result in approximately 20 MB bigger context and build time increase, however, with jiterator we can avoid build and context size penalty, and jiterate pointwise/reduction kernels for complex half. Defining math ops on complex half is not a problem, we can use approach similar to our current half support, where the values are cast to single precision complex first, math is performed in single precision, and result is truncated back.
2) Enable fft operation. CuFFT [supports complex half.](https://docs.nvidia.com/cuda/cufft/#half-precision-transforms)
3) Enable matrix multiplication operations. This unfortunately [is](https://docs.nvidia.com/cuda/cublas/index.html#cublasLtMatmul) [not](https://docs.nvidia.com/cuda/cublas/index.html#cublas-GemmEx) supported by cublas. Alternatives are using Triton, or doing 3 or 4 real matrix multiplications with corresponding copies to accommodate complex data layout.
cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @mthrok, @mruberry, @peterbell10

**Comment by nkaretnikov** [comment]
i've just been told by someone that the current plan is to remove complexHalf support in 1.11, so mentioning here for visibility.

**Comment by anjali411** [comment]
using `:module:complex` + `:module:half` tags to mark `complex32` issues

**Comment by ezyang** [comment]
Automatic mixed precision seems like one motivating use case for ComplexHalf https://github.com/pytorch/pytorch/issues/70664 

I'm not convinced we should spend the effort deleting the dtype (as @anjali411) is currently doing, since when I extrapolate into the future, I expect complex to be there. Maybe we can come up with some lighter touch way of informing users that it doesn't work well.

**Comment by ezyang** [comment]
sounds reasonable

**Comment by JuanFMontesinos** [comment]
Hi,
currently working in audio-visual here. 
After some deprecation warnings I just decided to ask for support for complex32.
Pytorch is doing an effort to close the gap in the production scenario with tensorflow. At least that's my feeling after seeing
native support for half precision, torchscript and jit etcetera...
As I briefly addressed in [#1337 ](https://github.com/pytorch/audio/issues/1337) 
I had to rewrite a bunch of code to move prototypes from complex32 to two-channel fp16 and implementing custom ops such as complex product nor division which are prob very inefficient. 

Just wanted to highlight most of the audio models works with spectrograms. Therefore, complex32 ops and the fft package are required.
I have the feeling that removing the dtype and deprecating the two-channel complex support  is an step back ( moreover if there is no alternative than casting).  I would say this would discourage almost any audio team targeting production. Please, note that this is neither documented in the fft package  docs.   
Note that some other important ops such as fft with non-power2 kernels are not supported.

Hope I can convince you to support it as I did so with torchvision team to support gpu video decoding 😄 

Best
Juan

**Comment by kshitij12345** [comment]
**Tracker : Complex32 Support**

TODO: (categorize ops are per prioritization)

All the ops that support complex dtypes are planned to have complex32 support.

Fundamental Ops
* [ ] copy_ (to support casting to and from `complex32`)
* [ ] print support (Ref: https://github.com/pytorch/pytorch/issues/50097)
* [ ] testing.make_tensor

Tensor Creation Ops:

* [ ] randn (supported, needs tests)
* [ ] rand (supported, needs tests)
* [ ] empty (supported, needs tests)
* [ ] full (supported only on CPU, needs tests)
* [ ] ones (supported only on CPU, needs tests)
* [ ] zeros (supported only on CPU, needs tests)
* [ ] linspace
* [ ] logspace
* [ ] arange
* [ ] eye

Following is the list of Op which support Complex Dtypes (generated by inspecting OpInfo)

* [ ] H
* [ ] T
* [ ] \_\_getitem\_\_
* [ ] \_\_radd\_\_
* [ ] \_\_rdiv\_\_
* [ ] \_\_rmatmul\_\_
* [ ] \_\_rmul\_\_
* [ ] \_\_rpow\_\_
* [ ] \_\_rsub\_\_
* [ ] _masked.mean
* [ ] _masked.prod
* [ ] _masked.sum
* [ ] _masked.var
* [ ] abs
* [ ] acos
* [ ] acosh
* [ ] add
* [ ] addbmm
* [ ] addcdiv
* [ ] addcmul
* [ ] addmm
* [ ] addmv
* [ ] addr
* [ ] all
* [ ] allclose
* [ ] angle
* [ ] any
* [ ] argwhere
* [ ] as_strided
* [ ] asin
* [ ] asinh
* [ ] atan
* [ ] atanh
* [ ] atleast_1d
* [ ] atleast_2d
* [ ] atleast_3d
* [ ] baddbmm
* [ ] bfloat16
* [ ] block_diag
* [ ] bmm
* [ ] bool
* [ ] broadcast_tensors
* [ ] broadcast_to
* [ ] byte
* [ ] cartesian_prod
* [ ] cat
* [ ] char
* [ ] cholesky
* [ ] cholesky_inverse
* [ ] cholesky_solve
* [ ] chunk
* [ ] clone
* [ ] column_stack
* [ ] combinations
* [ ] conj
* [ ] conj_physical
* [ ] contiguous
* [ ] corrcoef
* [ ] cos
* [ ] cosh
* [ ] count_nonzero
* [ ] cov
* [ ] cross
* [ ] cumprod
* [ ] cumsum
* [ ] cumulative_trapezoid
* [ ] diag
* [ ] diag_embed
* [ ] diagflat
* [ ] diagonal
* [ ] diff
* [ ] dist
* [ ] div
* [ ] dot
* [ ] double
* [ ] dsplit
* [ ] dstack
* [ ] eig
* [ ] einsum
* [ ] empty_like
* [ ] eq
* [ ] exp
* [ ] expand
* [ ] expand_as
* [ ] fft.fft
* [ ] fft.fft2
* [ ] fft.fftn
* [ ] fft.fftshift
* [ ] fft.hfft
* [ ] fft.hfft2
* [ ] fft.hfftn
* [ ] fft.ifft
* [ ] fft.ifft2
* [ ] fft.ifftn
* [ ] fft.ifftshift
* [ ] fft.irfft
* [ ] fft.irfft2
* [ ] fft.irfftn
* [ ] fill_
* [ ] flatten
* [ ] flip
* [ ] fliplr
* [ ] flipud
* [ ] float
* [ ] float_power
* [ ] full_like
* [ ] gather
* [ ] geqrf
* [ ] gradient
* [ ] half
* [ ] hsplit
* [ ] hstack
* [ ] imag
* [ ] index_add
* [ ] index_copy
* [ ] index_fill
* [ ] index_put
* [ ] index_select
* [ ] inner
* [ ] int
* [ ] inverse
* [ ] isclose
* [ ] isfinite
* [ ] isinf
* [ ] isnan
* [ ] isreal
* [ ] istft
* [ ] kron
* [ ] ldexp
* [ ] lerp
* [ ] linalg.cholesky
* [ ] linalg.cholesky_ex
* [ ] linalg.cond
* [ ] linalg.cross
* [ ] linalg.det
* [ ] linalg.eig
* [ ] linalg.eigh
* [ ] linalg.eigvals
* [ ] linalg.eigvalsh
* [ ] linalg.householder_product
* [ ] linalg.inv
* [ ] linalg.inv_ex
* [ ] linalg.lstsq
* [ ] linalg.lu_factor
* [ ] linalg.lu_factor_ex
* [ ] linalg.matrix_norm
* [ ] linalg.matrix_power
* [ ] linalg.matrix_rank
* [ ] linalg.multi_dot
* [ ] linalg.norm
* [ ] linalg.pinv
* [ ] linalg.qr
* [ ] linalg.slogdet
* [ ] linalg.solve
* [ ] linalg.solve_triangular
* [ ] linalg.svd
* [ ] linalg.svdvals
* [ ] linalg.tensorinv
* [ ] linalg.tensorsolve
* [ ] linalg.vector_norm
* [ ] log
* [ ] log10
* [ ] log2
* [ ] log_softmax
* [ ] logical_and
* [ ] logical_not
* [ ] logical_or
* [ ] logical_xor
* [ ] long
* [ ] lu
* [ ] lu_solve
* [ ] lu_unpack
* [ ] mH
* [ ] mT
* [ ] masked_fill
* [ ] masked_scatter
* [ ] masked_select
* [ ] matmul
* [ ] matrix_exp
* [ ] mean
* [ ] meshgrid
* [ ] mm
* [ ] movedim
* [ ] mul
* [ ] mv
* [ ] narrow
* [ ] ne
* [ ] neg
* [ ] new_empty
* [ ] new_full
* [ ] new_ones
* [ ] new_zeros
* [ ] nn.functional.feature_alpha_dropout
* [ ] nn.functional.linear
* [ ] nn.functional.normalize
* [ ] nn.functional.pad
* [ ] nn.functional.pairwise_distance
* [ ] nn.functional.pixel_shuffle
* [ ] nn.functional.pixel_unshuffle
* [ ] nn.functional.silu
* [ ] nn.functional.softmin
* [ ] nn.functional.softsign
* [ ] nn.functional.tanhshrink
* [ ] nn.functional.unfold
* [ ] nonzero
* [ ] norm
* [ ] ones_like
* [ ] ormqr
* [ ] outer
* [ ] permute
* [ ] pinverse
* [ ] positive
* [ ] pow
* [ ] prod
* [ ] put
* [ ] qr
* [ ] rand_like
* [ ] randn_like
* [ ] ravel
* [ ] real
* [ ] reciprocal
* [ ] renorm
* [ ] repeat
* [ ] repeat_interleave
* [ ] reshape
* [ ] reshape_as
* [ ] resize_
* [ ] resize_as_
* [ ] resolve_conj
* [ ] resolve_neg
* [ ] roll
* [ ] rot90
* [ ] rsqrt
* [ ] rsub
* [ ] scatter
* [ ] scatter_add
* [ ] select
* [ ] sgn
* [ ] short
* [ ] sigmoid
* [ ] sin
* [ ] sinc
* [ ] sinh
* [ ] softmax
* [ ] solve
* [ ] split
* [ ] split_with_sizes
* [ ] sqrt
* [ ] square
* [ ] squeeze
* [ ] stack
* [ ] std
* [ ] std_mean
* [ ] stft
* [ ] sub
* [ ] sum
* [ ] sum_to_size
* [ ] svd
* [ ] symeig
* [ ] t
* [ ] take
* [ ] take_along_dim
* [ ] tan
* [ ] tanh
* [ ] tensor_split
* [ ] tensordot
* [ ] tile
* [ ] to_sparse
* [ ] trace
* [ ] transpose
* [ ] trapezoid
* [ ] trapz
* [ ] triangular_solve
* [ ] tril
* [ ] triu
* [ ] true_divide
* [ ] unfold
* [ ] unsqueeze
* [ ] var
* [ ] var_mean
* [ ] vdot
* [ ] view
* [ ] view_as
* [ ] view_as_real
* [ ] vsplit
* [ ] vstack
* [ ] where
* [ ] zero_
* [ ] zeros_like

**Comment by JuanFMontesinos** [comment]
Hi @anjali441
I do understand the point. However, I find counterproductive to deprecate the two-channel support for complex numbers until the support for complex32 is implemented. The 2-channel representation of complex numbers is the only workaround to use pytorch and complex32 currently.
Anyway, the 1.11 version is already there so I guess there is point in discussing. 

Best,
Juan Montesinos

**Comment by Guillaume-oso** [comment]
Hi,
same problem with torch.onnx...

```
Traceback (most recent call last):
  File "torch_onnx.py", line 12, in <module>
    torch.onnx.export(
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/guillaume/.local/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator stft to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by anjali411** [comment]
@Guillaume-oso was this supported in the previous release?

**Comment by Guillaume-oso** [comment]
> @Guillaume-oso was this supported in the previous release?

I already tried it before, it wasn't working
