### ISSUE TITLE
Nightlies not building since 1/21/22

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#71716]
## Current Status
closed

## Error looks like
Nightlies not getting built

## Incident timeline (all times pacific)

- 1/20 pytorch/probot transitioned over to pytorch/test-infra, along with all of the bot actions (including the one that is responsible for triggering circleci workflows)
- 1/21 First nightly does not build
- 1/24 Nightlies not building detected (manually?) by @malfet 
- 1/24 Fix pushed to pytorch/test-infra https://github.com/pytorch/test-infra/commit/79df3c60bd9cdbbef2150ddb38c25225d2bc6b79

## User impact
No nightlies depending on CircleCI (e.g. mac/windows) were built during this time.

## Root cause
Bad migration, I did not turn on the circleci workflow trigger in the migrated pytorch bot.

## Prevention/followups
- Better testing for bot actions (integration testing for the entire bot, the unit tests only tested that the trigger logic worked)
- Alarms on nightly build failure

**Comment by seemethere** [comment]
Alarms should be for consecutive failures for nightlies, AI to determine the length of consecutive failures (5 days?)
