### ISSUE TITLE
BLAS options: OpenBLAS vs Accelerate

### ISSUE THREAD

**Issue by ngam** [pytorch/pytorch#71712]
### 🚀 The feature, motivation and pitch

Are there any benchmarks or preference among developers here? Assuming that Intel MacOS users should use MKL; MKL isn't available for Apple Silicon --- is there any benefit from using OpenBLAS vis-a-vis Accelerate? Any documentation or benchmarks? Thanks!

cc @VitalyFedyunin @ngimel

**Comment by vadimkantorov** [comment]
also, BLIS might be an option... https://github.com/flame/blis/pull/492

**Comment by malfet** [comment]
OpenBLAS and Accelerate should have the same API, but I'm not aware of any good benchmark of one vs another. But one should be able to recompile with different BLAS frameworks

**Comment by ngam** [comment]
> OpenBLAS and Accelerate should have the same API, but I'm not aware of any good benchmark of one vs another. But one should be able to recompile with different BLAS frameworks

Yes, I can confirm this. For what is worth, the default mechanism (i.e. no user preference in BLAS flag) in cmake seems to go something like this: it looks for MKL first, then BLIS, and then Accelerate, and I think finally OpenBLAS. I do understand the importance of setting MKL first (it seems to outperform everything else in this context). However, I am slightly confused about Accelerate vis-a-vis Accelerate (and BLIS maybe) from a few comments I gathered around here. Mainly this one: https://github.com/pytorch/pytorch/pull/68812#discussion_r755160355. Perhaps @IvanYashchuk can weigh in?

**Comment by ngam** [comment]
> also, BLIS might be an option... [flame/blis#492](https://github.com/flame/blis/pull/492) although this BLIS seems was not much used with pytorch...

Yes, thanks @vadimkantorov. The default mechanism appears to favor BLIS more than Accelerate as shown above.

**Comment by IvanYashchuk** [comment]
Here's the [FindBLAS.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindBLAS.cmake) and [FindLAPACK.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindLAPACK.cmake) files that PyTorch uses. There's no way to specify the BLAS variant and CMake tries to find it in a specific order (specified in FindBLAS.cmake), but it's possible to compile PyTorch with Accelerate if CMake doesn't find anything with higher priority.

`FindLAPACK.cmake` disallows mixing BLAS & LAPACK from different providers because it's fragile.

**Comment by ngimel** [comment]
cc @robieta

**Comment by ngam** [comment]
> Here's the [FindBLAS.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindBLAS.cmake) and [FindLAPACK.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindLAPACK.cmake) files that PyTorch uses. There's no way to specify the BLAS variant and CMake tries to find it in a specific order (specified in FindBLAS.cmake), but it's possible to compile PyTorch with Accelerate if CMake doesn't find anything with higher priority

No! There is (which is actually good, so thank you for the flexibility!) You can specify `BLAS=OpenBLAS` and you will force it to compile with OpenBLAS.

See more here: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/84#issuecomment-1019802668

**Comment by ngam** [comment]
Also, I am happy to run some benchmarks and tests if you can point me to some meaningful ones for this particular case. I already have both OpenBLAS-based and Accelerate-based PyTorch ready (and reproducible; I can also add BLIS and/or other BLAS libraries to test). I also am happy to help if there is an interest in clarifying this further :)

Note: I believe this whole thing is meaningless outside of Apple Silicon Macs at the moment. MKL BLAS/LAPACK should still be used whenever available, imo, but it is not available on Apple Silicon Macs as far as I could tell.

**Comment by IvanYashchuk** [comment]
> You can specify `BLAS=OpenBLAS` and you will force it to compile with OpenBLAS (if available)

Great it was fixed, if I recall correctly previously it was only affecting Caffe2 and not ATen (for example https://github.com/pytorch/pytorch/issues/60328).

> FindLAPACK.cmake disallows mixing BLAS & LAPACK from different providers because it's fragile

[Reference LAPACK](https://github.com/Reference-LAPACK/lapack) requires BLAS and if LAPACK is built from source against BLAS from Accelerate then I guess there shouldn't be any problems.

**Comment by ngam** [comment]
@robieta any thoughts?

**Comment by ngam** [comment]
From my limited testing, there is little value in choosing one or the other --- they do end up being rather similar. Closing this, thanks everyone for engaging with this and good luck :)
