### ISSUE TITLE
Old warnings from F.interpolate docs should be cleaned up

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#71720]
## Issue description

The [`F.interpolate()` docs](https://pytorch.org/docs/master/generated/torch.nn.functional.interpolate.html) include a couple of old warnings regarding the behavior of `align_corners` and `recompute_scale_factor` referencing PyTorch v0.3.1 and v1.6.0, respectively. These should be removed as no longer relevant. Also, somewhat related: the docstring for `recompute_scale_factor` does not specify what the default value for that arg is and should be updated as well.

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @kshitij12345

**Comment by pejato** [comment]
Hi @jbschlosser , I see the code that should be changed. Could I take this on?

I also see this block of code in `interpolate` that references the 1.6.0 change, should this be removed as well?

```
def interpolate( ... ):

    ...

    if recompute_scale_factor is None:
        # only warn when the scales have floating values since
        # the result for ints is the same with/without recompute_scale_factor
        if scale_factors is not None:
            for scale in scale_factors:
                if math.floor(scale) != scale:
                    warnings.warn(
                        "The default behavior for interpolate/upsample with float scale_factor changed "
                        "in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, "
                        "instead of relying on the computed output size. "
                        "If you wish to restore the old behavior, please set recompute_scale_factor=True. "
                        "See the documentation of nn.Upsample for details. "
                    )
                    break
```

**Comment by jbschlosser** [comment]
Hey @pejato! We would certainly welcome a PR if you'd like to contribute :) And yes you're correct that the warning in the code should be removed now as well.

**Comment by albanD** [comment]
Hi,

There are a couple tests in `test/test_nn.py` that handle these warnings for example in `test_upsamplingNearest2d`. You can update one of the test to properly assert that no warning is raised anymore (`self.assertEqual(len(w), 0)`) and remove the warning catchers for the rest.
