### ISSUE TITLE
what's the difference between required_grad, detach, detach_

### ISSUE THREAD

**Issue by mttbx** [pytorch/pytorch#7174]
Hi:
    I really don't know why we need detach and detach_. Sometimes I should just use it, for example the target of smooth_l1_loss must be detached. what's the difference between required_grad, detach, detach_? Can you give me some info?

**Comment by apaszke** [comment]
We're using GitHub issues for bug reports only, and all questions should be posted on [our forums](http://discuss.pytorch.org).
