### ISSUE TITLE
repr of tensor does't rescale values

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#7175]
Printing a float tensor with < 1 values factors out a common multiplicative power.
But in some cases, it forgets to rescale the values that are printed to take into account the factored value:
```python
torch.tensor(0.05524)
# this is right
# tensor(1.00000e-02 *
#        5.5240)

# but
torch.tensor([0.05524])
# prints
# tensor(1.00000e-02 *
#        [ 0.0552])
```

Also, I think we should be a bit more strict in the cases we want to print the common multiplicative factor (in those cases, we are more verbose and still lose information). Numpy doesn't factor out the aforementioned cases
```python
np.array(0.05224)
# prints array(0.05224)
np.array([0.05224])
# prints array([0.05224])
```

I'm using `torch.__version__ = '0.5.0a0+4caea64'`

**Comment by gchanan** [comment]
CC @li-roy

**Comment by li-roy** [comment]
Will look into being more strict with the rest of the printing changes.

**Comment by colesbury** [comment]
We should just get rid of the common factor. It's too easy to miss it when you print out big tensors. (You think everything is near 1 but everything is actually near 1e-8.)

**Comment by apaszke** [comment]
+1 for getting rid of the scaling factor!
