### ISSUE TITLE
[bug] pytorch doesn`t work after caffe2 installation

### ISSUE THREAD

**Issue by ducha-aiki** [pytorch/pytorch#7176]
## Issue description

I have installed from source (git clone) pytorch, then caffe2. After installation of caffe2, I cannot import torch package:

## Code example

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/caffe2-0.8.2-py2.7-linux-x86_64.egg/torch/__init__.py", line 14, in <module>
    from .version import __version__
ImportError: No module named version

## System Info
Please copy and paste the output from our environment collection script

```
python collect_env.py 
Traceback (most recent call last):
  File "collect_env.py", line 11, in <module>
    import torch
  File "/usr/local/lib/python2.7/dist-packages/caffe2-0.8.2-py2.7-linux-x86_64.egg/torch/__init__.py", line 14, in <module>
    from .version import __version__
ImportError: No module named version

```
- How you installed PyTorch (conda, pip, source):

```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
sudo python setup.py install
sudo python setup_caffe2.py install
```

- Build command you used (if compiling from source):
- OS:
Ubuntu 16.04
- PyTorch version:
https://github.com/pytorch/pytorch/commit/664fe34e0a28318947edaa562247be7b583c1ee7

- Python version:
2.7
- CUDA/cuDNN version:
CUDA 8.0

- GPU models and configuration:
laptop GeForce 940M 

- GCC version (if compiling from source):
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
- CMake version:
cmake version 3.9.0-rc2
- Versions of any other relevant libraries:

**Comment by apaszke** [comment]
Looks like Caffe2 is accidentally bundling the `torch` directory as part of the package.

**Comment by apaszke** [comment]
A quick fix for you would be to `rm -rf /usr/local/lib/python2.7/dist-packages/caffe2-0.8.2-py2.7-linux-x86_64.egg/torch`.

**Comment by apaszke** [comment]
It still is a legit problem, so let's leave it open.

**Comment by ezyang** [comment]
CC @orionr @pjh5

**Comment by zsef123** [comment]
In Mac, Python 3.6.5

Install on this command : `pip3 install caffe2`

```
>>> import torch
>>> torch
<module 'torch' from '/usr/local/lib/python3.6/site-packages/torch/__init__.py'>
>>> torch.__version__
'0.5.0a0.dev100'
```

```
Package             Version        Location
------------------- -------------- ------------------------
....
caffe2              0.5.0a0.dev100
....
torch               0.4.0  # *I'm already install pytorch 0.4.0*
...
```

I thinks caffe2 on pytorch directory(just torch)
