### ISSUE TITLE
DISABLED test_fn_grad_linalg_det_singular_cuda_float64 (__main__.TestGradientsCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71808]
Platforms: linux, win

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_fn_grad_linalg_det_singular_cuda_float64%2C%20TestGradientsCUDA)).

Pretty certain the culprit is #71168, but since @anjali411's fix was to disable some tests, I am thinking the intention was to disable and fix soon. Tagging @terrychenism 

Update: disabled again because of CUDA IMA: see https://github.com/pytorch/pytorch/runs/4999049430?check_suite_focus=true.

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @walterddr @IvanYashchuk @xwang233

**Comment by mruberry** [comment]
Thanks for disabling this test. The PR cited looks like it's about quantization, which seems unlikely to be related to the gradient of `linalg.det`?

**Comment by mruberry** [comment]
@Lezcano, @nikitaved, are one of you available to look into this?

**Comment by Lezcano** [comment]
This OpInfo is the flakiest OpInfo we have. My take on it is that we should just completely disable it / remove it until we have a second go at computing the second derivative of `det`.

**Comment by janeyx99** [comment]
Closing as revert should fix https://github.com/pytorch/pytorch/pull/71611#issuecomment-1022399970

**Comment by mruberry** [comment]
This test just caused an IMA. See here: https://github.com/pytorch/pytorch/runs/4999049430?check_suite_focus=true.

**Comment by mruberry** [comment]
Another IMA: https://github.com/pytorch/pytorch/runs/5000532777?check_suite_focus=true.

**Comment by janeyx99** [comment]
Also adding win to list of skipped platforms (in addition to linux)
