### ISSUE TITLE
Connection refused with torch.multiprocessing

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#7181]
The below code works on a Mac I tested but not on a Linux box. What it does at a high level is:
1) create a (CPU) tensor, put it into a queue
2) on second process: take the tensor from the queue. Send another (different) tensor through the queue.
3) on third process: take the tensor from the queue. Send another (different) tensor through the queue
4) on original process: take the tensor from the queue.

On step (3), taking the tensor for the queue, the program crashes with "ConnectionRefusedError: [Errno 111] Connection refused".

Repro:
```
import torch
import torch.multiprocessing as mp
import os

device = 'cpu'

def check(tensor):
    print("[{}] Checking tensor:".format(os.getpid()))
    print(tensor)
    if (tensor - torch.ones(10, device=device)).norm() > 0.0001:
        raise RuntimeError("bad tensor")

def run(queue):
    print("[{}] spawned".format(os.getpid()))
    tensor = queue.get()
    check(tensor)
    queue.put(torch.ones(10, device=device))

if __name__ == "__main__":
    # mp.set_sharing_strategy('file_system')
    mp.set_start_method('spawn')
    a = torch.ones(100, device=device)

    q = mp.Queue()
    tensor = torch.ones(10, device=device)
    q.put(tensor)

    p = mp.Process(target=run, args=(q,))
    p.start()
    p.join(10)

    p2 = mp.Process(target=run, args=(q,))
    p2.start()
    p2.join(10)

    print("original process")
    t2 = q.get()
    check(t2)
```

Output:
```
[37604] reduce_storage
[37673] spawned
[37673] Checking tensor:
tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])
[37673] reduce_storage
[37741] spawned
Process Process-2:
Traceback (most recent call last):
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/private/home/rzou/pytorch/pytorch/cuda3.py", line 18, in run
    tensor = queue.get()
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/private/home/rzou/pytorch/pytorch/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/private/home/rzou/local/miniconda3/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
original process
```

**Comment by zou3519** [comment]
Yikes, I left out a line. Updated the code snippet

**Comment by apaszke** [comment]
Thanks! Ok, I think that's user error. The problem is that the second worker exits before the main process receives the tensor in its entirety. Would inserting extra synchronization, to prevent the worker from quitting before the main process finishes reading fix the issue?

**Comment by zou3519** [comment]
Adding the synchronization to prevent the worker from quitting before the main process finishes reading works! Thanks @apaszke!

**Comment by neighthan** [comment]
I had this same problem and was about to post asking for an idea of how such synchronization might work, but I figured out a solution that worked in my case. I thought I'd share in case somebody else comes here and isn't sure how to do the necessary synchronization.

Here's a trivial problem which lines up with my use case (needing to pass some tensor to several workers who each compute something based on it). There may be a better way to do this than using 3 queues, but this way is very simple and makes it easy to reason about what's happening with each queue.

```python
import torch
from torch.multiprocessing import Process, Queue, set_start_method

def worker(input_queue, results_queue, exit_queue):
    start, end, tensor = input_queue.get()
    # I put start, end too as an identifier for this process/result
    results_queue.put((start, end, tensor[start:end].float().mean()))
    exit_queue.get()

if __name__ == "__main__":
    set_start_method("spawn")

    input_queue = Queue()
    results_queue = Queue()
    exit_queue = Queue()

    tensor = torch.arange(100)
    step = 10
    n_procs = 0
    for start in range(0, len(tensor), step):
        end = start + step - 1
        input_queue.put((start, end, tensor))
        n_procs += 1

    procs = []
    for _ in range(n_procs):
        proc = Process(target=worker, args=(input_queue, results_queue, exit_queue))
        proc.start()
        procs.append(proc)

    results = [results_queue.get() for _ in range(n_procs)]
    print(results)

    for _ in range(n_procs):
        exit_queue.put(1)

    for proc in procs:
        proc.join()
```

**Comment by oshribr** [comment]
Hi @neighthan , 
Why do you need the exist queue?

**Comment by neighthan** [comment]
@oshribr the exit queue? I don't actually remember why I put that in there; this looks like it would run fine without it. It might be that my actual code was more complicated, and it played a role there, and I just didn't remove it from the simple example that I posted for demonstration here.

**Comment by monchin** [comment]
> Adding the synchronization to prevent the worker from quitting before the main process finishes reading works! Thanks @apaszke!

@zou3519  , I'm sorry to dig this issue out, but would you please illustrate in detail how to add synchronization? 
My code:
```python
def kernel(q,  device):
    batch_tensor = torch.FloatTensor(2, 1000)
    # some operation
    q.put(batch_tensor)
    print('finish')

if __name__ == "__main__":
    q = mp.Queue()
    jobs = []
    device_list = [0, 1]
    for device in device_list:
        proc = mp.Process(
            target=kernel, 
            args=(q, device)
        )
        proc.start()
        jobs.append(proc)
    for job in jobs:
        job.join()
    for device in device_list:
        batch_tensor = q.get()
```
And I got the same error. I can get 2 `finish`, yet I can't `q.get()`. But if I `q.get()` right after `q.put(batch_tensor)` in `kernel`, I can get from `q`. Would you please give me some advice, for example give a doc or an example on how to add synchronization? Thank you!
