### ISSUE TITLE
Migrate master to main: https://github.com/pytorch/contrib 

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#71827]
Please look at the parent issue for instructions.(https://github.com/pytorch/pytorch/issues/62540)

**Comment by ajcost** [comment]
@janeyx99 I'll take this

**Comment by ajcost** [comment]
@janeyx99 I believe https://github.com/pytorch/contrib is stale I think we can close this issue

**Comment by janeyx99** [comment]
Sounds good to me!
