### ISSUE TITLE
Incorrect usage of `TORCH_INTERNAL_ASSERT` and `TORCH_CHECK`

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#71848]
### 🐛 Describe the bug

The first argument to these macros should be a condition for trigger but passing a `const char*` works as pointers are treated as  bool (and treated as true if they are not null or 0). Hence they are never triggered.

https://github.com/pytorch/pytorch/blob/530e7f619507e1d06e75e9afb6b5ace42da6f0b2/torch/csrc/jit/codegen/cuda/lower_alias_memory.cpp#L959-L961

https://github.com/pytorch/pytorch/blob/530e7f619507e1d06e75e9afb6b5ace42da6f0b2/torch/csrc/lazy/core/tensor_impl.cpp#L190

### Versions

master

cc: @mruberry

**Comment by mruberry** [comment]
cc @wconstab

**Comment by kshitij12345** [comment]
Closing as #71879 was merged.
