### ISSUE TITLE
RuntimeError: Caffe2 -The tensor has a non-zero number of elements, but its data is not allocated yet

### ISSUE THREAD

**Issue by alealv** [pytorch/pytorch#71914]
## Description
When training the model, I'm getting this error on the second run of the **Validation set**.

```
    x = torch.arange(max_length, dtype=length.dtype, device=length.device)
RuntimeError: The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

I'm using PytorchLightning and before the first Epoch I go through the whole validation set once with `num_sanity_val_steps=-1`
Then after successfully going through the first Epoch, the second time the validation set is executed I run into this error.

I really don't know how to proceed because the hint that it gives has to do with C++ code.

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-71-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti
GPU 6: NVIDIA GeForce RTX 2080 Ti
GPU 7: NVIDIA GeForce RTX 2080 Ti
GPU 8: NVIDIA GeForce RTX 2080 Ti
GPU 9: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.1
[pip3] pytorch-lightning==1.5.9
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchmetrics==0.7.0
[conda] Could not collect

**Comment by mrshenli** [comment]
Hey @alealv, I tried to run with `torch.arange` with different argument, but couldn't reproduce the error. Could you please print the argument values that caused the crash? 

<img width="728" alt="Screen Shot 2022-01-30 at 10 41 12 PM" src="https://user-images.githubusercontent.com/16999635/151735752-da59df3d-a3a6-4c51-8a13-4e1d035920fe.png">

**Comment by alealv** [comment]
Sorry for the late reply.

In the beginning of this week I found that one sample was making max_length=LONG_MAX_VALUE, so the arrange would be huge. Hence cuda was not putting that into memory.

Thanks!
