### ISSUE TITLE
Windows: Support Jiterator Cache

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#71967]
### 🚀 The feature, motivation and pitch

Jiterator Cache is a useful feature that is currently restricted to POSIX compliant systems.
The only reason is that the POSIX APIs access, mkdir and getpid are called.

I understand there is a TODO for c++17 support (for std::filesystem). However, as a temporary measure, we can simply use _access, _mkdir and _getpid for Windows.

### Alternatives

```C
#ifdef _WIN32
  #include <process.h>
  #include <direct.h>
  #include <io.h>
  #define access _access
  #define getpid _getpid
  #define R_OK    4
  #define W_OK    2
  #define F_OK    0
#else
  #include <sys/types.h>
  #include <sys/stat.h> // mkdir
  #include <unistd.h>
#endif
```

```C
#ifdef _WIN32
    if (_mkdir(p_cache_dir) != 0) {
#else
    if (mkdir(p_cache_dir, S_IRWXU | S_IRWXG | S_IRWXO) != 0) {
#endif
```

A suitable cache directory also has to be selected, rather than $HOME that is used currently. In my workaround, I am using $TEMP.

**Comment by ngimel** [comment]
We'll accept a PR implementing this, however, as we don't have access to windows development environment, it'll be hard for us to do it ourselves.
