### ISSUE TITLE
XLA broken on master after https://github.com/pytorch/pytorch/commit/84f168539725292d0b824c30d1d872fb30811803

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#71964]
### 🐛 Describe the bug

See https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=xla
Starting after https://github.com/pytorch/pytorch/commit/84f168539725292d0b824c30d1d872fb30811803 CI runs fail with 
```
[ RUN      ] AtenXlaTensorTest.TestNuclearNorm
/var/lib/jenkins/workspace/xla/test/cpp/torch_xla_test.cpp:50: Failure
Value of: changed.empty()
  Actual: false
Expected: true
/var/lib/jenkins/workspace/xla/test/cpp/torch_xla_test.cpp:59: Failure
Value of: !changed.empty()
  Actual: false
Expected: true
[  FAILED  ] AtenXlaTensorTest.TestNuclearNorm (33 ms)
```

That tests an API call which does not seem to be documented anywhere, but `torch.norm` has been deprecated for a while: https://pytorch.org/docs/stable/generated/torch.norm.html

### Versions

1.11.0a0+git8ff1a8f

cc @bdhirsh @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by malfet** [comment]
cc: @Lezcano @JackCaoG

**Comment by JackCaoG** [comment]
@malfet Most likely something changed `NuclearNorm` on pytorch end and now it fallback to CPU. Let me quickly disable the test and I will work on a fix.

**Comment by Lezcano** [comment]
Could this come from: https://github.com/pytorch/pytorch/pull/69827?
There's relevant discussion here as well: https://github.com/pytorch/pytorch/pull/69827#discussion_r792838941 that links to how to implement `svd` and `svdvals` in XLA, and also https://github.com/pytorch/xla/issues/2755
Long story short, what would it be better not to have `svd` and `svdvals` as a composite kernels that depend on a private funciton, and rather, have them as stand-alone kernels with their own forward and backward formulas? If this is the case, I can implement this and submit a PR.
What do you think it'd be the right way to go, the current one or the non-composite one @JackCaoG @IvanYashchuk @bdhirsh @albanD  ?

**Comment by albanD** [comment]
Do you mean `_svd_helper` instead of `_linalg_svd` above?
If so, then I think the current solution is good: both `svd` and `svdvals` are composite and call into `_svd_helper`. This `_svd_helper` function is the only one a backend implementer needs to worry about and it has the explicit flag `compute_uv` that should make it clear what the backend implementation should do.

**Comment by Lezcano** [comment]
So the thing is that I naively changed the name of `_svd_helper` to `_linalg_svd`, as I thought that it was just a private function and that was fine. Clearly I was wrong, and that's why this is breaking, sorry for that :(

**Comment by IvanYashchuk** [comment]
> So the thing is that I naively changed the name of `_svd_helper` to `_linalg_svd`, as I thought that it was just a private function and that was fine. Clearly I was wrong, and that's why this is breaking, sorry for that :(

`_svd_helper` is not used in pytorch/xla. It uses just `svd`.

The failure comes from https://github.com/pytorch/pytorch/pull/70253 specifically it changes the implementation of `norm` function to use `at::linalg_svdvals` (which is not covered by pyotrch/xla) instead of `at::svd` (which is covered by pytorch/xla).

**Comment by ngimel** [comment]
The failing test doesn't call `norm`, it calls `nuclear_norm` directly that, as far as I could see, still calls `svd`.

**Comment by JackCaoG** [comment]
I guess the fix is for pytorch/xla to also lower the `svd_helper`?

**Comment by Lezcano** [comment]
@ngimel It does not call `svd` but `svdvals`, as pointed out by @IvanYashchuk See
https://github.com/pytorch/pytorch/blob/aa7ce25f3491363bdd1aa5c840e40f4ade017b67/aten/src/ATen/native/LinearAlgebra.cpp#L2346-L2353

And yes, the fix would be to lower `svd_helper` (now called `_linalg_svd`) and everything should work.

**Comment by malfet** [comment]
I think we can close the issue, as it was resolved on XLA master
