### ISSUE TITLE
PyTorch/XLA jobs are not being run on PR CI, even with ciflow/all

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#71975]
This caused PyTorch/XLA to break and skip a broken test: https://github.com/pytorch/xla/pull/3319. The PR that likely caused this test was https://github.com/pytorch/pytorch/pull/69827, but despite the ciflow/all label the PyTorch/XLA job was not run on it, preventing it from understanding its impact on PyTorch/XLA.

Either we should let PR authors run the PyTorch/XLA job (and document how) or we should update our CI policies to allow the PyTorch/XLA job to be broken. 

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by janeyx99** [comment]
I can confirm tomorrow but could this be because XLA was disabled on trunk at the time the PR was getting tested?

**Comment by malfet** [comment]
XLA were disabled at ghstack head, see https://github.com/pytorch/pytorch/blob/gh/Lezcano/40/head/.github/scripts/generate_ci_workflows.py#L631

Please note that XLA builds/tests are enabled by default.
