### ISSUE TITLE
gcc 7.2 on CI is intermittently OOMing

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7202]
Failure is:

```
virtual memory exhausted: Cannot allocate memory
```

Unclear which file is OOMing.

Sample logs:
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc7.2-build/6344/console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc7.2-build/6283//console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc7.2-build/6326//console
* https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-trusty-py3.6-gcc7.2-build/6346/console

It doesn't seem to be correlated with builder machine. Maybe we can reduce parallelism for these jobs to solve the problem.

**Comment by mruberry** [comment]
Closing due to age and since this is no longer occurring.
