### ISSUE TITLE
error

### ISSUE THREAD

**Issue by saria85** [pytorch/pytorch#7203]
so I am trying to figure it out this but I could not find anything in the web,
I appreciate it if you help me with this
I can not install optimizer, actually I have these on my page 
import torch
from .optimizer import Optimizer, required
but optimizer required library seems have not been installed,
and I could not install it in any way.
I have anaconda environment

I appreciate your help

**Comment by zou3519** [comment]
The right place for questions is the forums: https://discuss.pytorch.org/

If you're talking about pytorch optimizers you can `import torch.optim`. See https://pytorch.org/docs/master/optim.html?highlight=torch%20optimizer .

**Comment by saria85** [comment]
I am using this link to install torch http://torch.ch/docs/getting-started.html

while running the the ./install.sh It got terminated with this:

-- Installing: /home/saria/torch/install/include/luaT.h
-- Installing: /home/saria/torch/install/share/cmake/torch/luaTConfig.cmake
Updating manifest for /home/saria/torch/install/lib/luarocks/rocks
torch scm-1 is now built and installed in /home/saria/torch/install/ (license: BSD)

Updating manifest for /home/saria/torch/install/lib/luarocks/rocks
dok scm-1 is now built and installed in /home/saria/torch/install/ (license: BSD)

gcc -O2 -fPIC -I/home/saria/torch/install/include -c utils.c -o utils.o
gcc -shared -o treplutils.so -L/home/saria/torch/install/lib utils.o
gcc -O2 -fPIC -I/home/saria/torch/install/include -c readline.c -o readline.o
readline.c:8:31: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
                               ^
compilation terminated.

Error: Build error: Failed compiling object readline.o

It is installing error. Also, there are no explanations how to add torch to anaconda environment.
I appreciate it if you give me the links as I searched a lot but no success

**Comment by apaszke** [comment]
That's not the correct repository. You're building [Torch7](http://github.com/torch/torch7).
