### ISSUE TITLE
PyTorch CI should somehow track number of tests executed for PR and notify about sudden changes

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72074]
### 🚀 The feature, motivation and pitch

Followup after https://github.com/pytorch/pytorch/issues/71973 
When tests suddenly got skipped (often unintentionally) it's very hard to detect then it happened, and we found it about it only much later. 
One way to mitigate this one is to count number of tests in nightly and send an alert if number of tests reduces by more than 1% unless there is a specific keyword in commit text to override it

cc @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry

**Comment by suo** [comment]
probably the most straightforward way is to augment our unittest wrapper to dump test stats to rockset keyed by workflow and job id, and compute the aggregations in rockset

**Comment by ZainRizvi** [comment]
We now have test numbers displayed in the metrics page.
