### ISSUE TITLE
can someone provide me a windows executable of this facebook opengo compile

### ISSUE THREAD

**Issue by hydrogenpi** [pytorch/pytorch#7208]
How much stronger is it than leela zero on only one playout?

https://github.com/gcp/leela-zero/issues/1311

https://github.com/pytorch/ELF/issues/1

**Comment by SsnL** [comment]
Hi, Thanks for your interest in PyTorch and OpenGo. However, this repo is for PyTorch issues. Please submit OpenGo related problems to https://github.com/pytorch/elf. Thanks!
