### ISSUE TITLE
[PT-D] More efficient ShardedTensor construction from local tensor.

### ISSUE THREAD

**Issue by fduwjj** [pytorch/pytorch#72092]
### 🚀 The feature, motivation and pitch

We currently only have an API called `_init_from_local_shards` which actually performs an allgather: https://github.com/pytorch/pytorch/blob/master/torch/distributed/_sharded_tensor/api.py#L351. We need a variation of this that doesn't do the validation for perf reasons or have a separate simpler API.

One proposal here is to have a new API like the following:

```
def from_local_tensor(tensor: torch.Tensor, *size: Sequence[int], spec: ShardingSpec) -> ShardedTensor
```
Each local rank can build the sharding metadata locally to avoid more expensive allgather. After implementing this, we then need to update the place where `_init_from_local_shards` is not necessary.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by pritamdamania87** [comment]
@fduwjj I'm assuming we can close this out since https://github.com/pytorch/pytorch/pull/72733 is landed?
