### ISSUE TITLE
ImportError: cannot import name caffe2_pb2

### ISSUE THREAD

**Issue by MahdiNazemi** [pytorch/pytorch#7215]
## Issue description

I have compiled the latest versions of PyTorch, ONNX, and Caffe2, all from source.

When I enter

`import caffe2.python.onnx.backend`

I get the following error messages:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytorch/caffe2/python/onnx/backend.py", line 26, in <module>
    from caffe2.python import core, workspace, rnn_cell, gru_cell
  File "pytorch/caffe2/python/core.py", line 14, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: cannot import name caffe2_pb2
```

Collecting environment information...
PyTorch version: 0.5.0a0+d154d32
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 8.10 (jessie)
GCC version: (Debian 4.9.2-10+deb8u1) 4.9.2
CMake version: version 3.11.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: 
GPU 1: 

Nvidia driver version: 390.12
cuDNN version: Probably one of the following:
/usr/local/cuda-7.5/lib64/libcudnn.so
/usr/local/cuda-7.5/lib64/libcudnn.so.5
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.3
/usr/local/cuda-7.5/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.1)
[pip] torch (0.5.0a0+d154d32, /home/home2/students/nazemi/university/neural-networks/pytorch)
[pip] torchvision (0.2.0)
[conda] Could not collect

**Comment by MahdiNazemi** [comment]
I hadn't noticed there is a separate `setup.py` for Caffe2, so Caffe2 was not installed at all.

**Comment by dankUndertone** [comment]
Where did you find the setup.py file for Caffe2?
