### ISSUE TITLE
[JIT] Models recently failing at specific resolutions (Tensorexpr)

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#72173]
### 🐛 Describe the bug

In latest master, I get the following error running JIT models that have never had an issue before:

> Traceback of TorchScript (most recent call last):
> RuntimeError: symbolic_strides_.count(output)INTERNAL ASSERT FAILED at "C:\\work\\pytorch\\torch\\csrc\\jit\\tensorexpr\\kernel.cpp":1516, please report a bug to PyTorch.

In one case, it is a detection model and fails at a specific resolution but not at other resolutions.

1x3x2176x3264 PASS
1x3x1008x1536 FAIL (Error above)
1x3x517x832 PASS

### Versions

Latest master

## Workaround

Reverting this line fixes the issue:
```Diff
-bool dyn_shapes = tensorExprDynamicShapeFusionEnabled();
+bool dyn_shapes = getCurrentBehavior(remaining_bailout_depth) == FusionBehavior::DYNAMIC;
```
From https://github.com/pytorch/pytorch/pull/71650

@navahgar @eellison

**Comment by eellison** [comment]
Hi, thanks for issue, could you send repro ?

**Comment by eellison** [comment]
Could you try to patch https://github.com/pytorch/pytorch/pull/72210/files and build with BUILD_TEST=0 and see if it still fails ?

**Comment by xsacha** [comment]
@eellison git merge origin/gh/eellison/268

I get a different error now:

> sym_stride_inputs_.count(i)INTERNAL ASSERT FAILED at "C:\\work\\pytorch\\torch\\csrc\\jit\\tensorexpr\\kernel.cpp":925, please report a bug to PyTorch.
> Exception raised from getInputStrideDesc at C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.cpp:925 (most recent call first):
> 00007FFC56EF0E0200007FFC56EF0DA0 c10.dll!c10::Error::Error [C:\work\pytorch\c10\util\Logging.cpp @ 81]
> 00007FFC56EEFECE00007FFC56EEFE80 c10.dll!c10::detail::torchCheckFail [C:\work\pytorch\c10\util\Exception.cpp @ 94]
> 00007FFC56EAB1E900007FFC56EAB1E0 c10.dll!c10::detail::torchInternalAssertFail [C:\work\pytorch\c10\util\Exception.h @ 437]
> 00007FFB7242448700007FFB72424330 torch_cpu.dll!torch::jit::tensorexpr::TensorExprKernel::getInputStrideDesc [C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.cpp @ 925]
> 00007FFB7241AFF000007FFB7241AB60 torch_cpu.dll!torch::jit::tensorexpr::TensorExprKernel::bindInput [C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.cpp @ 1012]
> 00007FFB724197AF00007FFB72418B40 torch_cpu.dll!torch::jit::tensorexpr::TensorExprKernel::bindAllInputs [C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.cpp @ 1413]
> 00007FFB7241C9CF00007FFB7241C750 torch_cpu.dll!torch::jit::tensorexpr::TensorExprKernel::compile [C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.cpp @ 1445]
> 00007FFB724120BA00007FFB72411C30 torch_cpu.dll!torch::jit::tensorexpr::TensorExprKernel::TensorExprKernel [C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.cpp @ 1613]
> 00007FFB71DDE7B700007FFB71DDE5B0 torch_cpu.dll!torch::jit::tensorexpr::TensorExprKernel::TensorExprKernel [C:\work\pytorch\torch\csrc\jit\tensorexpr\kernel.h @ 138]
> 00007FFB72066AB900007FFB72066990 torch_cpu.dll!torch::jit::createTensorExprOp [C:\work\pytorch\torch\csrc\jit\passes\tensorexpr_fuser.cpp @ 1255]
> 00007FFB71B8F39D00007FFB71B8F320 torch_cpu.dll!torch::jit::Operator::getOperation [C:\work\pytorch\torch\csrc\jit\runtime\operator.h @ 111]
> 00007FFB720CDE6100007FFB720CDE10 torch_cpu.dll!torch::jit::interpreter::CodeImpl::add_to_operator_table [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 821]
> 00007FFB720D38B100007FFB720D37E0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitOperator [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 326]
> 00007FFB720D341500007FFB720D26C0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitNode [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 641]
> 00007FFB720D366000007FFB720D35E0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitNodeAtBlockLevel [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 448]
> 00007FFB720D0FFB00007FFB720D0FB0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitCodeForBlock [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 763]
> 00007FFB720D1BD200007FFB720D1AE0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitIf [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 413]
> 00007FFB720D27D700007FFB720D26C0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitNode [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 658]
> 00007FFB720D366000007FFB720D35E0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitNodeAtBlockLevel [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 448]
> 00007FFB720D0FFB00007FFB720D0FB0 torch_cpu.dll!torch::jit::interpreter::CodeImpl::emitCodeForBlock [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 763]
> 00007FFB720C681D00007FFB720C6290 torch_cpu.dll!torch::jit::interpreter::CodeImpl::CodeImpl [C:\work\pytorch\torch\csrc\jit\runtime\interpreter\code_impl.h @ 161]
> 00007FFB720C61EE00007FFB720C6170 torch_cpu.dll!torch::jit::Code::Code [C:\work\pytorch\torch\csrc\jit\runtime\interpreter.cpp @ 1049]
> 00007FFB720AD56E00007FFB720AD510 torch_cpu.dll!torch::jit::ExecutionPlan::ExecutionPlan [C:\work\pytorch\torch\csrc\jit\runtime\graph_executor.h @ 26]
> 00007FFB720F71B300007FFB720F6220 torch_cpu.dll!torch::jit::ProfilingGraphExecutorImpl::getOptimizedPlanFor [C:\work\pytorch\torch\csrc\jit\runtime\profiling_graph_executor_impl.cpp @ 648]
> 00007FFB720F72C100007FFB720F7270 torch_cpu.dll!torch::jit::ProfilingGraphExecutorImpl::getPlanFor [C:\work\pytorch\torch\csrc\jit\runtime\profiling_graph_executor_impl.cpp @ 664]
> 00007FFB720B7E7F00007FFB720B7CF0 torch_cpu.dll!torch::jit::GraphExecutorImplBase::run [C:\work\pytorch\torch\csrc\jit\runtime\graph_executor.cpp @ 542]
> 00007FFB6E6102B500007FFB6E610270 torch_cpu.dll!torch::jit::Function::operator() [C:\work\pytorch\aten\src\ATen\core\function.h @ 62]
> 00007FFB71BE3B2A00007FFB71BE3980 torch_cpu.dll!torch::jit::Method::operator() [C:\work\pytorch\torch\csrc\jit\api\module.cpp @ 209]
> 00007FFC6829192500007FFC68291760 dnnbits.dll!Imagus::predict [C:\work\ifaceengine\iFaceRec\dnn\torch\torchutils.cpp @ 30]
> 00007FFC6828458600007FFC682834E0 dnnbits.dll!`Imagus::DNNNetThread<std::tuple<IFR_RECTF,float,std::vector<IFR_POINT,std::allocator<IFR_POINT> > > >::CreatePredictThread'::`2'::<lambda_1>::operator() [C:\work\ifaceengine\iFaceRec\dnn\DNNNetThreadImpl.h @ 244]
> 00007FFC682806CA00007FFC682806A0 dnnbits.dll!std::thread::_Invoke<std::tuple<`Imagus::DNNNetThread<std::tuple<IFR_RECTF,float,std::vector<IFR_POINT,std::allocator<IFR_POINT> > > >::CreatePredictThread'::`2'::<lambda_1>,std::stop_token>,0,1> [C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\thread @ 56]
> 00007FFC7F9693CC00007FFC7F969370 ucrtbase.dll!recalloc [<unknown file> @ <unknown line number>]
> 00007FFC8091135000007FFC80911340 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
> 00007FFC82451DC800007FFC82451DA0 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]
> 
> Error occurred while generating detection results. No results were returned to us.

**Comment by eellison** [comment]
hmm, is there anyway you could provide a more complete repro ? maybe sharing the file with me over slack if it's confidential ?

**Comment by xsacha** [comment]
Fixed. Thanks.
