### ISSUE TITLE
Including pytorch in C++ project in Visual Studio and building the project throws an error

### ISSUE THREAD

**Issue by InfiniteLife** [pytorch/pytorch#72171]
### 🐛 Describe the bug

I'm building Visual Studio C++ project, and getting errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2061	syntax error: identifier 'IValue'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2238	unexpected token(s) preceding ';'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1389	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1398	
Error	C2061	syntax error: identifier 'IValue'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2238	unexpected token(s) preceding ';'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1389	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1398	
Error	C2061	syntax error: identifier 'IValue'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2238	unexpected token(s) preceding ';'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1389	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1398	
Error	C2061	syntax error: identifier 'IValue'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2238	unexpected token(s) preceding ';'	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue.h	633	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1389	
Error	C2244	'c10::IValue::IValue': unable to match function definition to an existing declaration	Mars Vision	d:\dev\cpp_projects\libtorch_1.9_release\include\aten\core\ivalue_inl.h	1398	
```
Specifics:
- Visual Studio 2019 Version 16.11.3
- building tools v141
- System: Windows 10
- libtorch 1.9 release prebuilt with cuda 11.1

There is a fix that removes these errors and allows to successfully build the solution, all is needed to remove these lines from `ivalue.h`:

```
  /// \cond
  /// DOXYGEN_CANNOT_HANDLE_CONSTRUCTORS_WITH_MACROS_SO_EXCLUDE_THIS_LINE_FROM_DOXYGEN
  C10_DEPRECATED_MESSAGE(
      "IValues based on std::unordered_map<K, V> are slow and deprecated. Please use c10::Dict<K, V> instead.")
      /// \endcond
```

I'm submitting this issue because I looked at the current `ivalue.h` and there are the same lines:
https://github.com/pytorch/pytorch/blob/8757e21c6a4fc00e83539aa7f9c28eb11eff53c1/aten/src/ATen/core/ivalue.h#L660-L664

which I think still will cause building problems on Windows. I hope this issue will help to improve the usage experience for windows users.

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: N/A

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 472.12
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.0+cu113
[pip3] torchaudio==0.10.0+cu113
[pip3] torchvision==0.11.1+cu113
[conda] libblas                   3.9.0              12_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              12_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              12_win64_mkl    conda-forge
[conda] mkl                       2021.4.0           h0e2418a_729    conda-forge
[conda] mypy_extensions           0.4.3            py38haa244fe_4    conda-forge
[conda] numpy                     1.21.4           py38h089cfbf_0    conda-forge
[conda] numpydoc                  1.1.0                      py_1    conda-forge
[conda] torch                     1.10.0+cu113             pypi_0    pypi
[conda] torchaudio                0.10.0+cu113             pypi_0    pypi
[conda] torchvision               0.11.1+cu113             pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mszhanyi** [comment]
did you compile the pytorch souce code?
could you try visual studio 2019 16.8.6 https://developercommunity.visualstudio.com/t/install-specific-version-of-vs-component/1142479

**Comment by InfiniteLife** [comment]
No, I used prebuilt version. I'll try to get around to it

**Comment by vladimir-aubrecht** [comment]
@InfiniteLife Did you manage to solve the issue? If not, could you please share how to reproduce the issue? I tried with latest stack, but wasn't able to reproduce it.

**Comment by vladimir-aubrecht** [comment]
Closing as issue is stale and not managing to reproduce it with latest stack. Feel free to create new issue if problem persist.
