### ISSUE TITLE
pip==22.0.2 throws warning for `torch_stable.html`: "not a proper HTML 5 document [...] violates PEP 503"

### ISSUE THREAD

**Issue by joshuacwnewton** [pytorch/pytorch#72180]
### 🐛 Describe the bug

When installing PyTorch CPU using the `-f` HTML index page, `pip` now throws the following deprecation warning:

> DEPRECATION: The HTML index page being used (https://download.pytorch.org/whl/cpu/torch_stable.html) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip/issues/10825

So, I am reaching out to do just that. :)

### Versions

This occurs with `pip-22.0.2`, but is unrelated to the specific PyTorch version, since it has to do with the HTML index.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Thank you for letting us know. Can you please try https://download.pytorch.org/whl/cpu (which should be PEP503 compliant)

**Comment by joshuacwnewton** [comment]
> Thank you for letting us know. Can you please try https://download.pytorch.org/whl/cpu (which should be PEP503 compliant)

I did so, but I think I may have followed your instructions wrong:

<details>
<summary> Details for https://download.pytorch.org/whl/cpu/ </summary>

In https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/3679, I updated our `requirements.txt` file so that it looks like this:

```diff
- -f https://download.pytorch.org/whl/cpu/torch_stable.html
+ -f https://download.pytorch.org/whl/cpu
torch==1.5.0+cpu; sys_platform != "darwin"
torch==1.5.0; sys_platform == "darwin"
torchvision==0.6.0+cpu; sys_platform != "darwin"
torchvision==0.6.0; sys_platform == "darwin"
```

But, `pip` says:

```
Looking in links: https://download.pytorch.org/whl/cpu
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment

[...]

 ERROR: Could not find a version that satisfies the requirement torch==1.5.0+cpu (from versions: 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2)
ERROR: No matching distribution found for torch==1.5.0+cpu
```

</details>

With that failure, I realized I probably needed to click through to the sub-links https://download.pytorch.org/whl/torch/ and https://download.pytorch.org/whl/torchvision/ from the page you linked, so trying that yields:

<details>
<summary> Details for `torch/` and `torchvision/` subpages </summary>

```diff
- -f https://download.pytorch.org/whl/cpu/torch_stable.html
+ -f https://download.pytorch.org/whl/torch/
+ -f https://download.pytorch.org/whl/torchvision/
torch==1.5.0+cpu; sys_platform != "darwin"
torch==1.5.0; sys_platform == "darwin"
torchvision==0.6.0+cpu; sys_platform != "darwin"
torchvision==0.6.0; sys_platform == "darwin"
```

And pip now installs PyTorch with no issues or warnings.

```
Collecting torch==1.5.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.5.0%2Bcpu-cp37-cp37m-linux_x86_64.whl (127.3 MB)
Collecting torchvision==0.6.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.6.0%2Bcpu-cp37-cp37m-linux_x86_64.whl (5.7 MB)
```

</details>

All good! (Though it's a little confusing that the pages I needed to use didn't have the `cpu/` bit in the URL. :thinking:)

**Comment by aphedges** [comment]
Thanks for pointing to this!

The page <https://download.pytorch.org/whl/torch/> is missing wheels that are present on the old indexes, such as the 1.10.2 wheels on <https://download.pytorch.org/whl/cu111/torch_stable.html> and the cu102 wheels for 1.7.1 on <https://download.pytorch.org/whl/cu102/torch_stable.html>.

**Comment by joshuacwnewton** [comment]
Given that my personal issue here has been solved, and there is another open issue for `pip==22.0` more generally, I think I'm going to close this issue (just to help centralize discussion)? But, feel free to re-open if need be.
