### ISSUE TITLE
MacOS jobs in queue for 18+ hours

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72188]
## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.
ongoing

## Error looks like
Unfinished MacOS jobs on trunk and in PRs

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
- 2/1/22 ~4pm incident began
- 2/2/22 9:05am detected by noticing pending signal on trunk from last night https://hud2.pytorch.org/minihud#a7cebda9552e96edc31e642ea210cf5e7a97a923 
- 2/2/22 ? pm root caused as…
- 2/2/22 ? pm mitigated by…
- 2/2/22 ? pm closed by…

## User impact
*How does this affect users of PyTorch CI?*
MacOS tests are not run in time on CI and some commits on trunk are stuck with pending signal

## Root cause
*What was the root cause of this issue?*
It does NOT seem to be due to capacity as new macOS jobs were able to be scheduled while these really old jobs remain in the queue. However, capacity could be related as we have a capacity of 50 concurrent jobs for MacOS right now. 
We suspect something is weird on the GitHub side and have filed a support ticket.

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by seemethere** [comment]
I've filed a support ticket with Github about this here:

https://support.github.com/ticket/personal/0/1487244

**Comment by seemethere** [comment]
And now it looks like runs are starting to fail due to unavailability.

![image](https://user-images.githubusercontent.com/1700823/152246912-77618e6e-dfef-45be-a963-288c894f9917.png)

This is a bit frustrating.

https://github.com/pytorch/pytorch/actions/runs/1780462126

**Comment by seemethere** [comment]
We've gotten an updated allowance for macOS machines from 50 concurrent to 75 concurrent.

I think this has mostly resolved these issues, going to close this. Will re-open if it appears as though macOS queues have exploded again.

**Comment by janeyx99** [comment]
We have more runners now from AWS, and Eli's working on adding them :) Still unsure how many we will be getting from AWS eventually.

**Comment by malfet** [comment]
We should plan to accelerate spinning our own AWS Mac instances or find capacity by other sources.
