### ISSUE TITLE
ROCM jobs fail due to outdated git version

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72205]
## Current Status
*mitigated*.

## Error looks like
Checkout fails with `To create a local Git repository instead, add Git 2.18 or higher to the PATH`

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by seemethere** [comment]
Are we sure it's the render test results portion? From what I can tell it looks more like it's failing on checkout due to an outdated version of git.

@jeffdaily has told me that this should now be updated

**Comment by jeffdaily** [comment]
git was updated to 2.35.1 on all rocm runners

**Comment by malfet** [comment]
Closing

**Comment by malfet** [comment]
Let's keep it open for a bit longer until trunk is green

**Comment by janeyx99** [comment]
> Are we sure it's the render test results portion? From what I can tell it looks more like it's failing on checkout due to an outdated version of git.
> 
> @jeffdaily has told me that this should now be updated

Yea, the error was due to the runners not having Git version 2.18 or higher

**Comment by jeffdaily** [comment]
Found some hosts were also missing python3-pip.  Fixed.

**Comment by janeyx99** [comment]
Closing as trunk is now green

**Comment by jeffdaily** [comment]
And a subset of hosts were missi python3-setuptools.  Fixed.
