### ISSUE TITLE
[Docs] [Low Priority] Pytorch docs in Google search points to master/unstable

### ISSUE THREAD

**Issue by sherjilozair** [pytorch/pytorch#7222]
When I googled `pytorch nn functional`, this came up as the first link: `pytorch.org/docs/master/_modules/torch/nn/functional.html`

This is, as you know, docs for the master/unstable version. On clicking the link which says it'll take me to the docs for the stable release, I get sent to the home page of the docs, and now I have to search for the page again.

This can be solved by adding a canonical link to their non-stable documentation, i.e. something like this: `<link rel="canonical" href="https://pytorch.org/docs/stable/nn.html#torch-nn-functional">`.

**Comment by zou3519** [comment]
I've noticed this before but I didn't know there was a way to solve it. Thanks @sherjilozair for the idea; I'll try it out and see how it goes -- this would definitely be a great improvement.

**Comment by sherjilozair** [comment]
This is what Python documentation uses. See, eg.: view-source:https://docs.python.org/3.8/library/functions.html 

It would take time for Google's SEO to update though.
