### ISSUE TITLE
DISABLED test_linalg_lstsq_cpu_float64 (__main__.TestLinalgCPU)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72281]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_linalg_lstsq_cpu_float64%2C%20TestLinalgCPU)).

Another flaky LinAlg test?

cc @ezyang @gchanan @zou3519 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
This might be related to https://github.com/pytorch/pytorch/issues/71222

**Comment by janeyx99** [comment]
The above flakiness reappeared because we migrated the stats to a new branch in test-infra and so the disabled test files were not found. I'm going to add them back to the main branch for 2 weeks to allow a period where people can rebase onto the right code.

**Comment by kit1980** [comment]
Probably better to give unique names for the steps to avoid confusion, like I had in https://github.com/pytorch/test-infra/commit/cd0e5385a93e19b08572aa77efe1ee78d8cf8c22
