### ISSUE TITLE
torch.tensor : Inconsistent UX (Python 3.10)

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#72282]
### 🐛 Describe the bug

`torch.tensor` truncates `np.array` if its dtype can't be safe-casted to tensor the type (**similar to NumPy**).
But the same fails if we wrap the array in a list.

```python
import torch
import numpy as np
a = np.random.random((1,)) * 5
print(a)
print(np.array(a, dtype=np.int64))  # works (truncates the values)
print(np.array([a], dtype=np.int64))  # works (truncates the values)
print(torch.tensor(a, dtype=torch.int64)) # works (truncates the values)
print(torch.tensor([a], dtype=torch.int64)) # fails
```

Output
```
[3.46271899]
array([3])
array([[3]])
tensor([3])
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/pytorch_tensor_sequence_release/test/test_edge_case.py", line 6, in <module>
    print(torch.tensor([a], dtype=torch.int64)) # fails
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

~~Ideally, both should error out. For the first case, I think there should at least be a warning.~~

cc: @mruberry 

### Versions

master

Python - 3.10

cc @ezyang @gchanan @zou3519 @mruberry

**Comment by dagitses** [comment]
Assigning high-priority due to the silent correctness issue.

**Comment by albanD** [comment]
Note that pytorch's behavior is consistent with numpy's here: `np.array(a, dtype=np.int64)`
If you specify explicitly a dtype, then the given input will get converted.

**Comment by jbschlosser** [comment]
I'm not seeing this behavior on master. I get:
```python
import torch
import numpy as np
a = np.random.random((1,)) * 5
print(a)
print(torch.tensor(a, dtype=torch.int64)) # works (truncates the values)
print(torch.tensor([a], dtype=torch.int64)) # works with a warning:
# <stdin>:1: DeprecationWarning: an integer is required (got type numpy.float64).  Implicit
# conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
```

**Comment by kshitij12345** [comment]
@jbschlosser I think you are using Python 3.9 or lower. The second call to the constructor is an error on Python 3.10

**Comment by mruberry** [comment]
@kshitij12345 would you update the issue description with a comparison of what NumPy does in this case and describe the Python version you're using?

**Comment by kshitij12345** [comment]
Sure. Didn't realize that problem was due to deprecation in Python 3.10. Have updated the description with a comparison to NumPy and the Python version.

**Comment by kshitij12345** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/69316
