### ISSUE TITLE
DISABLED test_memory_profiler (__main__.TestProfiler)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72280]
Platforms: linux, mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_memory_profiler%2C%20TestProfiler)).

cc @ezyang @gchanan @zou3519 @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by robieta** [comment]
The obvious suspect would be https://github.com/pytorch/pytorch/pull/71539, but I see failures on the 24th and 26th as well. (And it's flakiness rather than failure.) I think the issue is that test is using `del` but not `gc.collect()`, so we're not actually guaranteed to see the deallocation.

**Comment by janeyx99** [comment]
@robieta Would the fix be to use `gc.collect()` after `del`?

**Comment by robieta** [comment]
> @robieta Would the fix be to use `gc.collect()` after `del`?

I think so. Do we have a good way to validate de-flaking of tests?

**Comment by janeyx99** [comment]
@robieta It's a hard problem in general to tell if a test will be unflaky in the long term, but one can re-enable the test on a PR by adding "fixes #issuenum" to the PR body and the bot will re-enable the test for that PR. Closing that PR will also close this issue, and the test will be enabled again.

**Comment by janeyx99** [comment]
Added mac as a response ^
