### ISSUE TITLE
undefined symbol: PyUnicodeUCS4_AsUTF8String 

### ISSUE THREAD

**Issue by jdxyw** [pytorch/pytorch#723]
Hi 

My env is Linux 2.6.32 cuda 8.0 python 2.7. Install pytorch by pip install https://s3.amazonaws.com/pytorch/whl/cu80/torch-0.1.8.post1-cp27-none-linux_x86_64.whl

The installation is successful However I got the error by import torch.

Best Regards,

**Comment by apaszke** [comment]
Duplicate of #591.
