### ISSUE TITLE
Export maximum / minumum to ONNX

### ISSUE THREAD

**Issue by Yosshi999** [pytorch/pytorch#72307]
### 🚀 The feature, motivation and pitch

```python
import torch
import torch.nn as nn
class Model(nn.Module):
    def forward(self, x, y):
        assert x.dtype == y.dtype
        return torch.maximum(x, y)

torch.onnx.export(Model(), (torch.randn(1, 2), torch.randn(1, 2)), "model.onnx",
    dynamic_axes={"0": {0: "batch", 1: "width"}, "1": {0: "batch", 1: "width"}, "2": {0: "batch", 1: "width"}})
```

causes `RuntimeError: Exporting the operator maximum to ONNX opset version 9 is not supported.`

Are there any plans for implementing this for opset9?

### Alternatives

```python
class Model2(nn.Module):
    def forward(self, x, y):
        assert x.dtype == y.dtype
        return torch.where((x > y) | (torch.isnan(x)), x, y)
```

### Additional context

It seems that `Max-*` in ONNX ignores NaN whereas `torch.maximum` doesn't.

**Comment by dagitses** [comment]
Assigning to onnx to look into this further.

**Comment by Yosshi999** [comment]
If my Alternatives is correct, I want to try to implement the maximum/minimum for opset9 in this way!

**Comment by shubhambhokare1** [comment]
Hey @Yosshi999, thanks for the suggestion. I think onnx's "Max" and "Min" operators handle Nan situations. I have added a PR for this, let me know if this resolves your issue.

**Comment by qqaatw** [comment]
Supported by https://github.com/pytorch/pytorch/pull/73103, in `1.12` release branch.

**Comment by shubhambhokare1** [comment]
closing, as supported in 1.12 release branch
