### ISSUE TITLE
device = torch.device("cuda" if args.cuda else "cpu") AttributeError: 'module' object has no attribute 'device'

### ISSUE THREAD

**Issue by pradeephike** [pytorch/pytorch#7231]
Hi ,

I am trying to train the fast_neural_style repo.
I am facing the error :
device = torch.device("cuda" if args.cuda else "cpu")
AttributeError: 'module' object has no attribute 'device'

Traceback :
Traceback (most recent call last):
  File "neural_style.py", line 239, in <module>
    main()
  File "neural_style.py", line 233, in main
    train(args)
  File "neural_style.py", line 32, in train
    device = torch.device("cuda" if args.cuda else "cpu")
AttributeError: 'module' object has no attribute 'device'

Below is the piece of code in which I am facing this error:

def train(args):
    device = torch.device("cuda" if args.cuda else "cpu")

    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    transform = transforms.Compose([
        transforms.Resize(args.image_size),
        transforms.CenterCrop(args.image_size),
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.mul(255))
    ])
    train_dataset = datasets.ImageFolder(args.dataset, transform)
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size)

    transformer = TransformerNet().to(device)
    optimizer = Adam(transformer.parameters(), args.lr)
    mse_loss = torch.nn.MSELoss()

    vgg = Vgg16(requires_grad=False).to(device)
    style_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.mul(255))
    ])
    style = utils.load_image(args.style_image, size=args.style_size)
    style = style_transform(style)
    style = style.repeat(args.batch_size, 1, 1, 1).to(device)

    features_style = vgg(utils.normalize_batch(style))
    gram_style = [utils.gram_matrix(y) for y in features_style]

**Comment by soumith** [comment]
please upgrade your pytorch to v0.4. You are using an older version of pytorch
