### ISSUE TITLE
How is Tensor.type supposed to work with strings?

### ISSUE THREAD

**Issue by marcozullich** [pytorch/pytorch#72365]
### 🐛 Describe the bug

I was looking for a functionality to convert Tensor dtype in-place by passing a string instead of the relevant `torch.dtype`.

`Tensor.type`, according to the docs, is supposed to work with `dtype`s and `str`s:
```python
def type(self: T, dst_type: Union[dtype, str]) -> T:
        r"""Casts all parameters and buffers to :attr:`dst_type`.

        .. note::
            This method modifies the module in-place.

        Args:
            dst_type (type or string): the desired type

        Returns:
            Module: self
        """
```

However, it seems not to work if `dst_type` is passed as a string.
I would expect it to work the same way as NumPy's `astype(...)`
I did not find usage examples around.

Example code:
```python
import torch
import numpy as np

x = torch.rand(5,5)
y = np.random.rand(5,5)

# conversion using the relevant dtype works
x.type(torch.float16)
y.astype(np.float16)

# np supports also dtype passed as strings
y.astype("float16")

# however, torch does not
x.type("float16")

# also this does not work
x.type("torch.float16")
```

#### Error stack
First example:
```
>>> x.type("float16")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid type: 'float16'
```
Second example:
```
>>> x.type("torch.float16")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid type: 'torch.float16'
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.33

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.10.0
[pip3] torch-optimizer==0.1.0
[pip3] torch-pruning==0.2.7
[pip3] torch-summary==1.4.5
[pip3] torchattacks==3.1.0
[pip3] torchaudio==0.10.0
[pip3] torchinfo==0.0.9
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.10.0          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torch-pruning             0.2.7                    pypi_0    pypi
[conda] torch-summary             1.4.5                    pypi_0    pypi
[conda] torchattacks              3.1.0                    pypi_0    pypi
[conda] torchaudio                0.10.0               py38_cu102    pytorch
[conda] torchinfo                 0.0.9                    pypi_0    pypi
[conda] torchvision               0.11.1               py38_cu102    pytorch

cc @mruberry @rgommers

**Comment by gchanan** [comment]
You are looking at the definition for the module code.  But `type` uses the old-style type descriptions like `torch.DoubleTensor` -- if you want to change the dtype I'd recommend just using `tensor.to` and passing in a dtype.

**Comment by andres-fr** [comment]
In case anyone wants a one-liner that actually addresses the question:

```python
torch.arange(10).type(getattr(torch, "float32"))
# returns:  tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
```
