### ISSUE TITLE
Inconsistent behavior between torch.nn.functional.pad and torchvision.transforms.functional.pad when setting padding to be an eight-element lists

### ISSUE THREAD

**Issue by maybeLee** [pytorch/pytorch#72394]
### 🐛 Describe the bug

I was trying to apply the zero padding to a 4-D tensor with size `(1,10,10,64)`. 

However, I find out that `torch.nn.functional.pad` will **accept** the pad to be a eight-element list `[0,1,1,0,0,1,1,0]` and output size `(2, 11, 11, 65)` when **I set the `mode="constant"`**. For your reference, I also try pad this tensor using `torchvision.transforms.functional.pad` with `padding=[0,1,1,0,0,1,1,0]` but torchvision will **directly throw an exception** as follows:

```
[/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_tensor.py](https://localhost:8080/#) in pad(img, padding, fill, padding_mode)
    429     if isinstance(padding, list) and len(padding) not in [1, 2, 4]:
    430         raise ValueError("Padding must be an int or a 1, 2, or 4 element tuple, not a " +
--> 431                          "{} element tuple".format(len(padding)))
    432 
    433     if padding_mode not in ["constant", "edge", "reflect", "symmetric"]:

ValueError: Padding must be an int or a 1, 2, or 4 element tuple, not a 8 element tuple
```

When I tried to look into the implementation of `torch.nn.functional.pad`, I notice that torch does not check the length of `pad` when setting `mode="constant"`:
![image](https://user-images.githubusercontent.com/32777264/152686008-714d2162-12c4-48f0-b994-a196e635240a.png)

Moreover, I also cannot find any usage explanation when I set `pad` to be an eight-element list on PyTorch's documentation. Therefore, I guess setting `pad` to be an eight-element list is invalid? If so, maybe you need to add some pad length check on the constant mode. If setting `pad` to be an eight-element list is actually valid, why does the torchvision library cannot support this functionality and where can I find the related documentation?

You may run the below code or the link to access the code:
```
import torch
import torchvision
import numpy as np
torch_input = torch.from_numpy(np.random.rand(1,10,10,64))
pads = [0,1,1,0,0,1,1,0]
torch_pad_res = torch.nn.functional.pad(torch_input, pad=list(pads), mode="constant")
print(torch_pad_res.size())
torchvision_pad_res = torchvision.transforms.functional.pad(torch_input, list(pads), padding_mode="constant")
```
https://colab.research.google.com/drive/1hRuE43eAVDHBdsfqY5FgPAOBr2TQmX7f?usp=sharing

Thanks for your patience.

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.12 (default, Jan 15 2022, 18:48:18)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.0+cu111
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @fmassa @vfdev-5 @pmeier

**Comment by mruberry** [comment]
Thank you for reporting this issue, @maybeLee.

**Comment by jbschlosser** [comment]
8-dimensional padding is valid for 4D input in `torch.nn.functional.pad`; the underlying `constant_pad_nd` call supports it:
https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/aten/src/ATen/native/ConstantPadNd.cpp#L16-L18

AFAICT, the [`torch.nn.functional.pad` docs](https://pytorch.org/docs/master/generated/torch.nn.functional.pad.html) do mention that this is supported:
* pad ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple)) – m-elements tuple, where m / 2 <= input dimensions and m is even
* Constant padding is implemented for arbitrary dimensions.

That said, we're open to suggestions on how this can be made more clear in the docs.

Regarding torchvision, I'd encourage you to open an issue over in that repo requesting this.

**Comment by maybeLee** [comment]
Hi @jbschlosser @mruberry , thanks for your answer and you help. When checking `torchvision.transforms.Pad` [docs](http://pytorch.org/vision/main/generated/torchvision.transforms.Pad.html), I notice that they specify the dimension of pad should be either 1, 2, or 4. So I think it is the expected inconsistent behavior between `torch` and `torchvision`. I will close this issue, thanks for your time.
