### ISSUE TITLE
About the pseudocode in the torch.optim.SGD document

### ISSUE THREAD

**Issue by nipirennipi** [pytorch/pytorch#72395]
### 📚 The doc issue

[About the pseudocode in the torch.optim.SGD document.md](https://github.com/pytorch/pytorch/files/8010436/About.the.pseudocode.in.the.torch.optim.SGD.document.md)

cc @brianjo @mruberry @vincentqb @jbschlosser @albanD

**Comment by Lezcano** [comment]
Thanks for the issue @nipirennipi!. We would accept a PR fixing this errata :)
