### ISSUE TITLE
Function description containing "w.r.t." are trimmed improperly

### ISSUE THREAD

**Issue by goxeq** [pytorch/pytorch#72428]
### 📚 The doc issue

For example, in the page: 
https://pytorch.org/docs/stable/autograd.html#tensor-autograd-functions
 
we have the description of the "backward" method terminated after w.r.t.:

torch.Tensor.backward([gradient, …]) | Computes the gradient of current tensor w.r.t.

However, the correct description should be

torch.Tensor.backward([gradient, …]) | Computes the gradient of current tensor w.r.t. graph leaves.

Like in page https://pytorch.org/docs/stable/generated/torch.Tensor.backward.html#torch.Tensor.backward

It points to a potential issue with how the  `autosummary` function of the documentation generator defines the first sentence of a docstring. 

### Suggest a potential alternative/fix

Apparently the Sphinx documentation generator has a defined variable  `WELL_KNOWN_ABBREVIATIONS`, to which "w.r.t." could be modified before building the documentation (https://github.com/sphinx-doc/sphinx/blob/d82d37073920ce0e2940dccbd25f719cc92a3352/sphinx/ext/autosummary/__init__.py#L102). 

The simple solution would be to use "wrt" instead of "w.r.t." in the docstrings.

cc @brianjo @mruberry @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by mruberry** [comment]
Thank you for reporting the issue and your thoughtful suggestions for how to address it, @goxeq. We would definitely accept PRs improving our documentation.

**Comment by albanD** [comment]
I agree that changing these to "wrt" is a good fix as fixing sphinx list might take a lot longer.
We would definitely accept a PR fixing this.
