### ISSUE TITLE
DDP debug mode: Throw when static_graph and unused parameter sizes are different across ranks

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#72434]
### 🚀 The feature, motivation and pitch

static_graph training is not meant for the case where unused parameters are variable across ranks, however we've seen a lot of use cases where static_graph is enabled and unused parameter sizes are different across ranks, which leads to hard to debug errors. 

To help with this, In DETAIL debug mode, we can allgather unused parameter sizes across ranks and verify that they are equal under static graph training. Some additional design consideration may be needed as to where to add this detection and if we need to run this check every iteration or only the first few training iterations. 

### Alternatives

Looking at log output can confirm whether unused parameter sizes are different, however this takes additional time and requires DDP specific context / expertise and will increase the troubleshooting time.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by zhaojuanmao** [comment]
static_graph should support the case when unused parameters are not the same across ranks, as long as they do not change over iterations. We had a unit test called "test_different_graph_across_ranks" for this.

**Comment by rohan-varma** [comment]
@zhaojuanmao I see, I'll investigate the internal issue a bit more then and see what's going wrong and if static_graph disable helps

**Comment by rohan-varma** [comment]
@zhaojuanmao is correct, this is a misunderstanding.
