### ISSUE TITLE
Caffe2 ATen dependency error (USE_ATEN ON)

### ISSUE THREAD

**Issue by MahdiNazemi** [pytorch/pytorch#7249]
## Issue description

I'm trying to compile Caffe2 from source with `USE_ATEN` option set to `ON`.

When I run `python setup_caffe2.py build develop --user`, I get the following error:

`ninja: error: '../caffe2/contrib/aten/ATen', needed by 'caffe2/contrib/aten/aten_op.h', missing and no known rule to make it`

## System Info
Collecting environment information...
PyTorch version: 0.5.0a0+d154d32
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 8.10 (jessie)
GCC version: (Debian 4.9.2-10+deb8u1) 4.9.2
CMake version: version 3.11.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: 
GPU 1: 

Nvidia driver version: 390.12
cuDNN version: Probably one of the following:
/usr/local/cuda-7.5/lib64/libcudnn.so
/usr/local/cuda-7.5/lib64/libcudnn.so.5
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.3
/usr/local/cuda-7.5/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so
/usr/local/cuda-9.0/lib64/libcudnn.so.7
/usr/local/cuda-9.0/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.1)
[pip] torch (0.5.0a0+d154d32, pytorch)
[pip] torchvision (0.2.0)
[conda] Could not collect

**Comment by MahdiNazemi** [comment]
This seems to be caused by the dependency that is in `CMakeLists.txt`:

```
...
  ATen
  ${CMAKE_CURRENT_SOURCE_DIR}/gen_op.py
  ${CMAKE_CURRENT_SOURCE_DIR}/aten_op_template.h
```

**Comment by pjh5** [comment]
This should be fixed on master. Please retry on the latest code and reopen if you still encounter this
