### ISSUE TITLE
onnx.export() of Batch1dNorm generates invalid ONNX under torch.cuda.amp.autocast()

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#72494]
### 🐛 Describe the bug

onnx.export() of Batch1dNorm generates invalid ONNX under torch.cuda.amp.autocast().
Here is a small repro case: 

## Repro 
```
import torch
import torch.nn as nn
import onnx


class BatchNorm1dNoAutoCast(nn.BatchNorm1d):
    def init(self, num_features, **kwargs):
        nn.BatchNorm1d.init(self, num_features, **kwargs)

    def forward(self, x):
        if False:  # torch.onnx.is_in_onnx_export():
            ret = nn.BatchNorm1d.forward(self, x.to(torch.float)).to(x.dtype)
        else:
            ret = nn.BatchNorm1d.forward(self, x)
        return ret


mod = BatchNorm1dNoAutoCast(5).to(device="cuda").eval()

data = torch.rand(300, 5, device="cuda").half()
with torch.inference_mode(), torch.cuda.amp.autocast():
    torch.onnx.export(mod,
                      (data),
                      "a.onnx",
                      opset_version=14,
                      verbose=True
                      )

onnx_model = onnx.load("a.onnx")
onnx.checker.check_model(onnx_model, full_check=True)
```
##

## Error
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:BatchNormalization, node name: BatchNormalization_0): scale has inconsistent type tensor(float)             
##
Uncomment the code under torch.onnx.is_in_onnx_export() condition to get correct ONNX exported.

### Versions

Here.  I have also verified the bug manifests with latest 1.11a (NVIDIA pytocrh 22.01).
Seems to happen with all latest upsets : 13, 14, 15.

Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GV100
GPU 1: Quadro GV100
GPU 2: NVIDIA GeForce GT 710

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.5.9
[pip3] torch==1.10.1+cu113
[pip3] torch-stft==0.1.4
[pip3] torchaudio==0.10.1+cu113
[pip3] torchmetrics==0.6.0
[pip3] torchvision==0.11.2+cu113
[conda] Could not collect

cc @ngimel @mcarilli @ptrblck

**Comment by borisfom** [comment]
@vadimkantorov : FWIW, this is refined general wrapper I am using now to work around this bug : 
``
class CastToFloat(nn.Module):
    def __init__(self, mod):
        super(CastToFloat, self).__init__()
        self.mod = mod

    def forward(self, x):
        if torch.is_autocast_enabled():
            ret = self.mod.forward(x.to(torch.float)).to(x.dtype)
        else:
            ret = self.mod.forward(x)
        return ret      
``

Then, before export, I replace all instances of BatchNorm with this wrapper around original modules.

**Comment by BowenBao** [comment]
cc @thiagocrepaldi this looks like a similar case to the Einsum autocast issue.

**Comment by thiagocrepaldi** [comment]
Yup, I will look into it. Thanks

**Comment by thiagocrepaldi** [comment]
@BowenBao Is there an ADO for that issue?

**Comment by BowenBao** [comment]
@thiagocrepaldi no, created just now. Tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1616897

**Comment by thiagocrepaldi** [comment]
This is actually an issue inside shape inference. Batch normalization already has support for Autocast (does not downcast to lower resolution). Will look into it, but this is different than https://github.com/pytorch/pytorch/pull/71916

**Comment by thiagocrepaldi** [comment]
@borisfom TL;DR Working by design, fix is changing opset to 15

The long explanation is that the `BatchNormalization` spec for ONNX opset 14 has the following signature:
![image](https://user-images.githubusercontent.com/5469809/159789376-08d61dba-3101-4c8f-8548-24f120c7b238.png)
Note that input, weight (scale) and bias *must* have the same type `T`. In your repro, `X` (aka ` input`) is fp16 while all `weight` and `bias` are float32. That is not correct by spec

However, on ONNX opset 15, `BatchNormalization` signature changed, supporting mixed precision
![image](https://user-images.githubusercontent.com/5469809/159790084-174c0d59-7363-4d51-b50f-5181ddbbb31c.png)
There, `input` is *T* while `scale` and `B` are *T1* and `running_var` and `running_weight` are *T2*. Each T, T1 and T2 can be different of each other, allowing you to mix fp16 `input` with `fp32` weight

**Comment by thiagocrepaldi** [comment]
If you still have an issue, please reopen it

**Comment by garymm** [comment]
@thiagocrepaldi the current state of this is not very user-friendly IMO.
Could we either:
1. Add casts inside the BatchNormalization symbolic, or otherwise ensure that the exported model is valid?, OR if that's not feasible
2. Have the symbolic check for the mixed input types and raise an error like "Got types <x> and <y>. Mixed input types not supported until opset 15. Please use opset 15 or use the same type for all inputs"

WDYT?

**Comment by thiagocrepaldi** [comment]
> import torch
> import torch.nn as nn
> import onnx
> 
> 
> class BatchNorm1dNoAutoCast(nn.BatchNorm1d):
>     def init(self, num_features, **kwargs):
>         nn.BatchNorm1d.init(self, num_features, **kwargs)
> 
>     def forward(self, x):
>         if False:  # torch.onnx.is_in_onnx_export():
>             ret = nn.BatchNorm1d.forward(self, x.to(torch.float)).to(x.dtype)
>         else:
>             ret = nn.BatchNorm1d.forward(self, x)
>         return ret
> 
> 
> mod = BatchNorm1dNoAutoCast(5).to(device="cuda").eval()
> 
> data = torch.rand(300, 5, device="cuda").half()
> with torch.inference_mode(), torch.cuda.amp.autocast():
>     torch.onnx.export(mod,
>                       (data),
>                       "a.onnx",
>                       opset_version=14,
>                       verbose=True
>                       )
> 
> onnx_model = onnx.load("a.onnx")
> onnx.checker.check_model(onnx_model, full_check=True)

Casting inside `Autocast` is more likely to introduce issues, as the pytorch and ONNX models will have different types

> @thiagocrepaldi the current state of this is not very user-friendly IMO. Could we either:
> 
> 1. Add casts inside the BatchNormalization symbolic, or otherwise ensure that the exported model is valid?, OR if that's not feasible
> 2. Have the symbolic check for the mixed input types and raise an error like "Got types  and . Mixed input types not supported until opset 15. Please use opset 15 or use the same type for all inputs"
> 
> WDYT?

I agree the esception raised is confusing for the user.

Although 1) is doable, what would be the policy? Assuming all 5 inputs can be either float16, float, double or bloat16, which one would be used as the "correct"? Float32 as the most common/higher precision? Or if one float16 is present, all others should follow? Isn't there the risk to introduce precision loss? Should we cast the BatchNormalization output as well?

2) is doable too, but as different opsets for the same op have different spec, we may have to add similar(but not identical) in several symbolics for the same op

**Comment by garymm** [comment]
I think we may have examples of both of these in the existing symbolics.
For the first (mixed input types), look for symbolics that insert Cast ops.
If we know what the ATen op's output type would be given those inputs, then I think any sub-graph that is both valid ONNX and that returns that same type is good. 

For the second, we'd add a helper in `symbolic_helper.py` that checks if the input is compatible with the specified opset version and raises a helpful error message if it's not.
Example: https://github.com/pytorch/pytorch/blob/8e12d2bf253521dee2a91c31daffcbfb7039c06f/torch/onnx/symbolic_helper.py#L841-L844

I'll leave it to you to choose which course to take.

**Comment by thiagocrepaldi** [comment]
> I think we may have examples of both of these in the existing symbolics. For the first (mixed input types), look for symbolics that insert Cast ops. If we know what the ATen op's output type would be given those inputs, then I think any sub-graph that is both valid ONNX and that returns that same type is good.
> 
> For the second, we'd add a helper in `symbolic_helper.py` that checks if the input is compatible with the specified opset version and raises a helpful error message if it's not. Example:
> 
> https://github.com/pytorch/pytorch/blob/8e12d2bf253521dee2a91c31daffcbfb7039c06f/torch/onnx/symbolic_helper.py#L841-L844
> 
> I'll leave it to you to choose which course to take.

The issue that I see in 1) is that me will have to mimic the down/upcast logic that already exists inside Autocast + export for a opset that supports mixed precision. There is no obvious way to predict what should happen to the output based on the input. In fact, I created https://github.com/pytorch/pytorch/issues/73538 to propose a solution for this problem

A reason 2) approach would be something like
```
    if torch.is_autocast_enabled() and \
            not check_args_have_same_dtype([input, weight, bias, running_mean, running_var]) and \
            sym_help._export_onnx_opset_version < 15:
        return sym_help._onnx_opset_unsupported_detailed("BatchNormalization", 14, 15,
                                                         "Tensors with mixed precision are not supported")
```
