### ISSUE TITLE
XLA is broken on master again

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72493]
## Current Status
*ongoing*.

## Error looks like
GitHub looses communication with runner running XLA test after about 30+ min

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 2/7 2:54 pm incident began
- 2/7 4:30 pm detected by looking at [HUD-for-XLA](https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=xla,)
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @bdhirsh

**Comment by badenh** [comment]
I also saw this over the weekend doing some merge-builds, but it always came back, it was just very very slow.
