### ISSUE TITLE
libtorch cudaDeviceSynchronize() operation is VERY SLOW?

### ISSUE THREAD

**Issue by wulaoshi** [pytorch/pytorch#72511]
### 🐛 Describe the bug

In Libtorch, when I using cudaDeviceSynchronize(), I find this step takes about 80 milliseconds:
```
  vector<torch::jit::IValue> inputs = {input_data.input_ids_pt_,
                                       input_data.attention_mask_pt_,
                                       input_data.token_type_ids_pt_};                              
  auto pred_res = (static_cast<torch::jit::script::Module*>(bert_model_))->forward(inputs);      // About 12 milliseconds
  cudaDeviceSynchronize();           // About 80 milliseconds
  auto logits = pred_res.toTensor().to(at::kCPU);        // About 0 milliseconds
```
So is there any way to reduce the time of `cudaDeviceSynchronize()`?
Looking forward to your reply, thanks!

### Versions

GPU: Tesla T4, NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0 
docker: CUDA Version 10.0.130, libtorch-shared-with-deps-1.7.1+cu101

cc @ngimel

**Comment by xsacha** [comment]
cudaDeviceSynchronize() just waits until the work on the GPU is done.

The 80 milliseconds is from the previous call. The forward.

**Comment by ejguan** [comment]
Closing this Issue as the question has been resolved. Feel free to re-open it if needed.
