### ISSUE TITLE
Inconsistency with .numpy()

### ISSUE THREAD

**Issue by markroxor** [pytorch/pytorch#7251]
## Issue description
In the below code everything is same for both `Xtrain` and `X` except that `X` was initialized as a `ch.zeros` tensor and was later converted to numpy ndarray by using `X.numpy`. The principal components are different in both the scenarios provided that rest everything remains same.

## Code example

```python
import torch as ch
from sklearn.decomposition import PCA
import numpy as np
n = 5
n_dim = 3

X = ch.zeros(n, n_dim)
m = 5
c = 2
d = 5
for i in range(n):
    X[i,0] = i
    X[i,1] = m*i + c
    X[i,2] = (d - 2*X[i,0] - 3*X[i,1])/2

X = X.numpy()


Xtrain = np.zeros([n, n_dim])
m = 5
c = 2
d = 5
for i in range(n):
    Xtrain[i,0] = i
    Xtrain[i,1] = m*i + c
    Xtrain[i,2] = (d - 2*Xtrain[i,0] - 3*Xtrain[i,1])/2

print(X, type(X))
>>> (array([[  0. ,   2. ,  -0.5],
       [  1. ,   7. ,  -9. ],
       [  2. ,  12. , -17.5],
       [  3. ,  17. , -26. ],
       [  4. ,  22. , -34.5]], dtype=float32), <type 'numpy.ndarray'>)
print(Xtrain, type(Xtrain))
>>> (array([[  0. ,   2. ,  -0.5],
       [  1. ,   7. ,  -9. ],
       [  2. ,  12. , -17.5],
       [  3. ,  17. , -26. ],
       [  4. ,  22. , -34.5]]), <type 'numpy.ndarray'>)
print(np.allclose(Xtrain, X))
>>> True
pca_x = PCA(n_components=3)
pca_x.fit(X)

pca_xtrain = PCA(n_components=3)
pca_xtrain.fit(Xtrain)

print(pca_x.components_)
>>> [[-1.0088666e-01 -5.0443327e-01  8.5753661e-01]
 [-5.8938619e-02  8.6345071e-01  5.0097811e-01]
 [-9.9315059e-01 -7.4505806e-09 -1.1684125e-01]]
print(pca_xtrain.components_)
>>> [[-0.10088665 -0.50443327  0.85753656]
 [-0.82430398 -0.44025326 -0.35594945]
 [-0.55708601  0.74278135  0.37139068]]
```

## System Info
Collecting environment information...
PyTorch version: 0.3.1
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.9.1

Python version: 2.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1060 3GB
Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-3f9a723f.so.6.0.21

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.3.1)
[pip] torchvision (0.2.0)
[conda] Could not collect

**Comment by apaszke** [comment]
The snippet isn't self contained because it's missing e.g. `n` and `n_dim`. I set them to 10 and 3 respectively and I can't reproduce the issue. That's the output I get:
```
[[  0.    2.   -0.5]
 [  1.    7.   -9. ]
 [  2.   12.  -17.5]
 [  3.   17.  -26. ]
 [  4.   22.  -34.5]
 [  5.   27.  -43. ]
 [  6.   32.  -51.5]
 [  7.   37.  -60. ]
 [  8.   42.  -68.5]
 [  9.   47.  -77. ]] <class 'numpy.ndarray'>
[[  0.    2.   -0.5]
 [  1.    7.   -9. ]
 [  2.   12.  -17.5]
 [  3.   17.  -26. ]
 [  4.   22.  -34.5]
 [  5.   27.  -43. ]
 [  6.   32.  -51.5]
 [  7.   37.  -60. ]
 [  8.   42.  -68.5]
 [  9.   47.  -77. ]] <class 'numpy.ndarray'>
True
[[ 0.10088665  0.5044334  -0.8575365 ]
 [-0.00558278 -0.86163354 -0.50750023]
 [-0.9948823   0.05598746 -0.08411115]]
[[ 0.10088665  0.50443327 -0.85753656]
 [-0.1464699  -0.84501166 -0.51429744]
 [ 0.98405714 -0.17748904  0.01136611]]
```

**Comment by SsnL** [comment]
Also np default dtype is double. So your two arrays' dtype differ.

**Comment by SsnL** [comment]
@markroxor `from_numpy` gives you a `float64` because the input numpy array is `float64`. I was saying that your torch array is `float32` which gets transformed to a `float32` numpy array, but your numpy array is `float64`. There is no `from_numpy` here.

**Comment by markroxor** [comment]
@SsnL I have [observed](https://github.com/jellAIfish/fromscratchtoml/issues/31#issuecomment-386382239) that the issue is with `float64` and `float32`. Still isn't it a bug? or is there a workaround?

**Comment by SsnL** [comment]
@markroxor Sorry, why is it a bug? `float64` tensors gets transformed into `float64` arrays. `float32` tensors gets transformed into `float32` arrays. Why do you expect `float32` tensors getting transformed into `float64` arrays?

**Comment by markroxor** [comment]
I think something like `X = ch.zeros((n, n_dim), , dtype=torch.float64)` should solve my issue. Unfortunately i couldnt find it in the documentation as it is still a unstable build feature. Closing this.
@SsnL thanks.

**Comment by fmassa** [comment]
@markroxor I didn't quite understand the issue, but the `dtype` is [documented for `torch.zeros` here](https://pytorch.org/docs/stable/torch.html?highlight=zeros#torch.zeros), and the [`dtype` are in here](https://pytorch.org/docs/stable/tensors.html).

**Comment by markroxor** [comment]
I am using pytorch v0.3.1 which [doesn't has this feature](https://pytorch.org/docs/0.3.1/torch.html?highlight=zeros#torch.zeros).

**Comment by fmassa** [comment]
Oh, I see. In your case, if you want to generate a tensor of a specific type from `torch.zeros`, you could use something like `tensor = torch.zeros(4, 4, out=torch.DoubleTensor())`, but this is a bit ugly.

**Comment by markroxor** [comment]
or maybe it is time to upgrade to v0.4 :)
