### ISSUE TITLE
DOCS, CI: pushing a tag is not triggering a docs build

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#72519]
The CI has migrated to github actions, in particular the nightly docs are built by [.github/workflows/generated-linux-docs-push.yml](https://github.com/pytorch/pytorch/blob/5bd19ba8460aa174133f74b389861f54106a3086/.github/workflows/generated-linux-docs-push.yml). But the tags triggers are https://github.com/pytorch/pytorch/blob/5bd19ba8460aa174133f74b389861f54106a3086/.github/workflows/generated-linux-docs-push.yml#L8-L12. In the older circleCI build, any tag triggered a build and then we used a [regex](https://github.com/pytorch/pytorch/blob/5e6f29661254e5ebc97fac3d829e5d455cda5864/.circleci/config.yml#L899) `tag=$(echo $CIRCLE_TAG | sed -e 's/v*\([0-9]*\.[0-9]*\).*/\1/')` to set the version. So I think there are two problems:
- remove the restrictions so that any tag will trigger a run
- fix the [TODO](https://github.com/pytorch/pytorch/blob/5bd19ba8460aa174133f74b389861f54106a3086/.github/workflows/generated-linux-docs-push.yml#L340) to incorporate the older logic for choosing `master` or trimming the `1.11.0rc1` tag to `1.11` and using it.

@brianjo

cc @brianjo @mruberry @ezyang @zou3519

**Comment by brianjo** [comment]
Thanks Matti. Adding @malfet @seemethere @holly1238

**Comment by malfet** [comment]
@atalman can you please have a look at it?

**Comment by malfet** [comment]
And 1.11 docs for 1.11.0-rc2 is there: https://pytorch.org/docs/1.11/

**Comment by mattip** [comment]
Thanks!
