### ISSUE TITLE
[FSDP][BE] Remove multiple param logic in FSDP code

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#72520]
### 🚀 The feature, motivation and pitch

Currently we only shard based on flat_param, eventually once it is decided that FSDP will not support non-flat param based training, we should remove/simplify all code such as https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/fully_sharded_data_parallel.py#L275 that assumes that there might be multiple parameters. 

We can probably do this in the future once we've investigated all various use cases such as finetuning and are confident that we won't need non flat param approach, simplifying the code base by quite a bit. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
Instead, we are refactoring to re-add this logic because we want to support non-recursive wrapping / functional-like. The only difference is that we should do everything in terms of `FlatParamHandle` instead of `FlatParameter`.
