### ISSUE TITLE
onnx.export not producing the same results as torch model 

### ISSUE THREAD

**Issue by electricdarb** [pytorch/pytorch#72528]
### 🐛 Describe the bug

the output of the onnx model does not match the output of the torch model, although it is ball park close it is not close enough. The argmax is the same around 2/3 times, so it is similar. I am using the new ConvNext model, perhaps that has something to do with it. 

'''python 

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

def torch_to_onnx(model, path, batch_size, input_shape):
    x = torch.randn(batch_size, *input_shape, requires_grad=True)

    torch.onnx.export(model,           # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  path,   # where to save the model (can be a file or file-like object)
                  export_params = True,        # store the trained parameter weights inside the model file
                  opset_version = 10,          # the ONNX version to export the model to
                  do_constant_folding = True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes = {'input' : {0 : 'batch_size'},    # variable length axes
                                 'output' : {0 : 'batch_size'}})
    
    print(f"model saved to {path}")

def load_onnx_model(path):
    model = onnx.load(path)
    onnx.checker.check_model(model)
    return model

torch_model = models.convnext_tiny(pretrained=True)
path = 'convnext_tiny.onnx'

torch_to_onnx(torch_model, path, batch_size, INPUT_SHAPE)
onnx_model = load_onnx_model(path)

ort_session = ort.InferenceSession(path)

# define model input x to test onx vs torch
inputs = torch.randn(batch_size, *INPUT_SHAPE)

torch_out = torch_model(inputs)

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(inputs)}
ort_outs = ort_session.run(None, ort_inputs)

# compare ONNX Runtime and PyTorch results
np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05)

print("Exported model has been tested with ONNXRuntime, and the result looks good!")
'''
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_29490/169650136.py in <module>
     11 
     12 # compare ONNX Runtime and PyTorch results
---> 13 np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05)
     14 
     15 print("Exported model has been tested with ONNXRuntime, and the result looks good!")

    [... skipping hidden 1 frame]

~/miniconda3/envs/torch_p37/lib/python3.9/site-packages/numpy/testing/_private/utils.py in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    838                                 verbose=verbose, header=header,
    839                                 names=('x', 'y'), precision=precision)
--> 840             raise AssertionError(msg)
    841     except ValueError:
    842         import traceback

AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 998 / 1000 (99.8%)
Max absolute difference: 0.6605562
Max relative difference: 128.67833
 x: array([[-7.407761e-01,  9.383662e-01,  1.014424e+00,  1.805369e-01,
         9.217907e-01, -4.727180e-01, -4.484633e-02, -1.384754e-01,
        -4.865628e-02,  2.109748e-01,  2.006615e+00,  2.775145e+00,...
 y: array([[-9.416272e-01,  1.047131e+00,  1.113519e+00,  4.538115e-01,
         1.140393e+00, -2.991518e-01,  2.725753e-01, -2.814007e-01,
        -1.410045e-01,  1.626909e-03,  2.011779e+00,  2.902045e+00,...

### Versions

python 3.9.7
torch nightly 0.12.0.dev20220208
numpy 1.19.5
onnx 1.10.2
onnxruntime 1.10.0

**Comment by BowenBao** [comment]
@electricdarb Correct. This is due to that in training mode, `StochasticDepth`(https://pytorch.org/vision/master/generated/torchvision.ops.stochastic_depth.html#torchvision.ops.stochastic_depth) in the model will randomly drop residual branches. In eval mode, `StochasticDepth` is disabled.

**Comment by BowenBao** [comment]
Closing.
