### ISSUE TITLE
Remove/refactor BucketReplica in DDP reducer

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#72539]
### 🚀 The feature, motivation and pitch

BucketReplica is now redundant since SPMD (single-process multi device) mode is deprecated, and we don't need to maintain this list: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/reducer.hpp#L426 and index into it as there is always only one replica per bucket. 

We can either:
1) Keep BucketReplica which is sort of a container for gradient tensors and other useful variables, maintain only one instance of it per bucket, and rename it to something better indicative of what it is
2) Remove BucketReplica and move all its member variables to `Bucket` so that there is only one place where all data related to gradient buckets exists.

### Details

1. Previously, DDP would let users replicate the model across GPUs in a single process similar to DataParallel, but this had performance limitations and we deprecated this approach. Most code related to this, and all public-facing code, has since been removed. 
2. The above notion of `BucketReplica`s is a bit of vestiget left over from this time. As a result we only now need one `BucketReplica` and don't have to maintain the list as mentioned above. 
3. `reducer` https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/reducer.cpp is essentially DDP's C++ backend which is responsible for managing and bucketing gradients, reducing them across all workers, and synchronizing with the backwards pass appropriately.

### Tests
- This is not a user facing change so no new tests should be needed. 
- Please ensure all tests in https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/distributed/distributed_test.py and https://github.com/pytorch/pytorch/blob/master/test/distributed/test_c10d_nccl.py (and test_c10d*) pass.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
Closed by https://github.com/pytorch/pytorch/pull/73237.
