### ISSUE TITLE
Enable documentation improvements to be able to land through GH1

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72538]
### 🚀 The feature, motivation and pitch

Since documentation changes shouldn't affect internal functionality, we should add a rule to allow docs changes to be merged.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
You've already proposed a PR, haven't you?

**Comment by janeyx99** [comment]
Closed by #72872
