### ISSUE TITLE
[FSDP] Root frees params in `_post_backward_hook()` though `reshard_after_forward=False`

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#72541]
**Overview**
For an `FSDP` instance, if `self.reshard_after_forward == True`, then it frees its parameters in the forward pass (see [here](https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/torch/distributed/fsdp/fully_sharded_data_parallel.py#L663-L664)).

For a nested FSDP model with a root `FSDP` instance (i.e. `self._is_root == True`), `self.reshard_after_forward` is set to `False` (see [here](https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/torch/distributed/fsdp/fully_sharded_data_parallel.py#L472)). Not resharding and instead keeping its parameters in memory _should_ save the all-gather needed to rebuild the parameters in the next forward pass (see [here](https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/torch/distributed/fsdp/fully_sharded_data_parallel.py#L646-L648)). In that case, [this condition](https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1080-L1086) _should_ evaluate to `True`.

However, the root instance's parameters are freed anyway in the `_post_backward_hook()` (see [here](https://github.com/pytorch/pytorch/blob/7176c92687d3cc847cc046bf002269c6949a21c2/torch/distributed/fsdp/fully_sharded_data_parallel.py#L902)), which means that they must be all-gathered in the next forward pass.

We cannot simply preface the parameter freeing in `_post_backward_hook()` with `if self.reshard_after_forward`. This breaks several tests, and I have not had the chance to determine why. (I.e. why is it critical that we always call `_free_full_params()` in the `_post_backward_hook()`?)

**Upshot**
Fairscale `FSDP` seems to only require `n - 1` all-gather calls in the forward pass (see [here](https://github.com/facebookresearch/fairscale/blob/89e1ae5f1631c6e038268240f92084dc2f6f2dd8/tests/nn/data_parallel/test_fsdp_grad_acc.py#L150-L152)), while PyTorch `FSDP` requires `n`, where `n` is the number of `FSDP` instances in the model and the `-1` comes from excluding the root.

If we can make sense of this issue, we may be able to similarly require `n - 1` all-gather calls in the forward pass.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Great catch! We should probably see if we can resolve this and support not freeing root / outer most instance parameter and run tests to see how it affects the perf. 

Cc @zhaojuanmao

**Comment by zhaojuanmao** [comment]
"Not resharding and instead keeping its parameters in memory should save the all-gather needed to rebuild the parameters in the next forward pass"

==> that is not true. Not resharding for root instance is for saving the all-gather needed to rebuild the parameters in the backward pass, as the backward pass will immediately need the full parameters of the root instance.  It is not for saving rebuild parameter in the next forward pass. 

we should always free full params after grad is ready in the backward pass, so that the memory is freed for next layer's computation. Otherwise, why we need sharding at all?
