### ISSUE TITLE
Add a way to debug when our runners are at capacity

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72553]
Followup to https://github.com/pytorch/pytorch/issues/72188: figure out why we were hitting capacity anyway: why did we run into a capacity problem in the first case? Did GH never give us the runners?

Some actual actions:
- [ ] Add a dashboard or way to tell what's happening in each runner
- [x] Ask GitHub what was up

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
There currently exists a script to view our self hosted runners at https://github.com/pytorch/test-infra/blob/main/tools/self-hosted-runner-utils/check_runners_state.py,

Functionality is coming from github as well per this blog post: https://github.blog/2022-02-23-new-way-understand-github-hosted-runner-capacity/
