### ISSUE TITLE
TestSpectralOps tests incompatible with updated librosa 0.9.0

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72550]
### 🐛 Describe the bug

For context see: https://github.com/pytorch/pytorch/issues/72432

The tests were green after I pinned the library https://github.com/pytorch/pytorch/pull/72433.

### Versions

CI

cc @ezyang @gchanan @zou3519 @mruberry @peterbell10

**Comment by mruberry** [comment]
@peterbell10 would you take a look at the librosa update and check the following:

- should we update the test and the librosa pin?
- should we update our docs to let users know how our stft is different from librosa's?

Follow-up question: should we be looking at implementing `fft.stft` not necessarily based on librosa's UX?

**Comment by peterbell10** [comment]
>Follow-up question: should we be looking at implementing fft.stft not necessarily based on librosa's UX?

This discussion has come up before and the decision was to maintain the existing `stft` interface. See the original `torch.fft` tracking issue https://github.com/pytorch/pytorch/issues/42175#issuecomment-674510661.
