### ISSUE TITLE
Grid sampler fails with CUDNN_STATUS_EXECUTION_FAILED for large images (not due to memory exhaustion)

### ISSUE THREAD

**Issue by emitch** [pytorch/pytorch#7258]
When applying a transformation to large images/stacks of images, a CUDA error is raised (CUDNN_STATUS_EXECUTION_FAILED). The error occurs for variables at or above the following sizes:

    (1,129, 512, 512)
    (1, 49, 1024, 1024)
    (1, 13, 2048, 2048)
    (1, 1, 4096, 4096)

I encountered this issue when using an affine transformation to augment a stack of 50 1024x1024 images. The following code can be used to identify the image volume size at which the sampler fails:

    import torch
    from torch.autograd import Variable
    import torch.nn.functional as F
    import numpy as np
    
    def get_identity_grid(dim):
        gx, gy = np.linspace(-1, 1, dim), np.linspace(-1, 1, dim)
        I = np.stack(np.meshgrid(gx, gy))
        I = np.expand_dims(I, 0)
        I = Variable(torch.FloatTensor(I)).cuda()
        return I.permute(0,2,3,1)
    
    for imdim in [512, 1024, 2048, 4096]:
        for i in range(1,1000):
            try:
                image_stack = Variable(torch.ones((1,i,imdim,imdim))).cuda()
                grid = get_identity_grid(imdim)
                F.grid_sample(image_stack, grid)
            except Exception as e:
                print(str(e) + ' at ' + str(imdim) + ' ' + str(i))
                break

PyTorch version: 0.3.0.post4
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2016b/bin/glnxa64/libcudnn.so.4.0.7
/usr/local/MATLAB/R2017a/bin/glnxa64/libcudnn.so.5.1.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn-7b07b0f1.so.7.0.5
/usr/local/lib/python3.5/dist-packages/torch/lib/libcudnn-a2b758a6.so.7.0.3

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] torch (0.2.0.post3)
[pip] torchvision (0.1.9)
[conda] Could not collect

**Comment by zou3519** [comment]
@emitch, thank you for the report.

This is my output on 0.4.0:

```
CUDNN_STATUS_EXECUTION_FAILED at 512 129
CUDNN_STATUS_EXECUTION_FAILED at 1024 49
CUDNN_STATUS_EXECUTION_FAILED at 2048 13
CUDNN_STATUS_EXECUTION_FAILED at 4096 1
```

I've also gotten the following by running the code in ipython.
```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.cu line=58 error=77 : an illegal memory access was encountered
cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.cu:58 at 512 1
cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.cu:58 at 1024 1
cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.cu:58 at 2048 1
cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1524577177097/work/aten/src/THC/generic/THCStorage.cu:58 at 4096 1
```

It sounds like a bug to me (maybe we're missing memory checks somewhere?).

**Comment by mruberry** [comment]
I was running this script until I hit an OOM error, not an illegal memory access. This issue is pretty old and likely to be fixed. I'm going to close it. @emitch, if you're still seeing this issue would you update and reopen it?
