### ISSUE TITLE
torch.no_grad() can cause nan and random results

### ISSUE THREAD

**Issue by Zhangyanbo** [pytorch/pytorch#72594]
### 🐛 Describe the bug

Running the following code:

```python
import torch
import torch.nn as nn


block = nn.Sequential(nn.Conv2d(1, 8, 3, padding=1), nn.Conv2d(8, 1, 3, padding=1))
with torch.no_grad():
    gx = block(torch.randn(1,1,5,5))

print(gx)
```

Some times, I will get nan result, such as:

```python
tensor([[[[        nan,         nan, -5.0249e+27,         nan,         nan],
          [        nan,         nan, -1.0987e+28,         nan,         nan],
          [        nan,         nan,  2.0282e+36, -2.5592e+36,  8.3669e+35],
          [        nan,         nan, -4.8736e+36, -7.4338e+35,  4.1086e+36],
          [        nan,         nan, -2.9828e+36, -2.1171e+36,  3.1350e+36]]]])
```

> Note: you may need to run this code multiple times to get the bug.

However, if I remove the `nn.Sequential` or `torch.no_grad()`, it will back to normal:

```python
block = nn.Conv2d(1, 1, 3, padding=1)
with torch.no_grad():
    gx = block(torch.randn(1,1,5,5))

print(gx)

'''output
tensor([[[[ 0.5557,  0.4501, -0.1535, -0.8888, -0.8810],
          [ 0.6834,  0.4136, -0.0093, -0.7025, -1.4664],
          [ 0.7698,  0.6245, -0.3802, -1.1841, -1.5778],
          [ 0.6865,  0.5524, -1.0033, -1.0162, -1.3443],
          [ 0.4791,  0.3035, -0.3653, -0.7445, -1.0624]]]])
'''

```

### Versions

Collecting environment information...
PyTorch version: 1.9.0.post2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 01:38:21)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.9.0.post2
[pip3] torchvision==0.2.2
[conda] numpy                     1.21.2           py38hbf7bb01_0    conda-forge
[conda] pytorch                   1.9.0           cpu_py38hff7f1bc_2    conda-forge
[conda] torchvision               0.2.2                      py_3    pytorch

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by Zhangyanbo** [comment]
I tested this code on a different platform, and there is no bug there.

I post the environment information here:


### Versions

Collecting environment information...
PyTorch version: 1.6.0+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:21:18)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.106-1-pve-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1070
GPU 1: NVIDIA GeForce GTX 1070

Nvidia driver version: 465.19.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.6.0+cu101
[pip3] torchvision==0.7.0+cu101
[conda] msgpack-numpy             0.4.7.1                  pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.6.0+cu101              pypi_0    pypi
[conda] torchvision               0.7.0+cu101              pypi_0    pypi

**Comment by ezyang** [comment]
Can you try a recent nightly and see if that has the problem on the first config?

**Comment by Zhangyanbo** [comment]
> Can you try a recent nightly and see if that has the problem on the first config?

Thanks for your suggestion! In the new version (1.10.2), I did't saw any problem.

**Comment by ezyang** [comment]
Ok sounds like we fixed it then!
