### ISSUE TITLE
Functional version of `MultiheadAttention`, `torch.nn.functional.multi_head_attention_forward` has no documentation

### ISSUE THREAD

**Issue by ProGamerGov** [pytorch/pytorch#72597]
### 📚 The doc issue

The functional version of https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html has no documentation, as can be seen when searching for it: https://pytorch.org/cppdocs/search.html?q=multi_head_attention_forward&check_keywords=yes&area=default

This issue appears to have been present for a while, as it this earlier issue was closed prematurely: https://github.com/pytorch/pytorch/issues/49296

The source code for the function also already has documentation written: https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L5049, so I'm not sure why it isn't showing up on the PyTorch site docs. The `in_proj_weight` variable should also be type hinted as `Optional[Tensor]` and not just `Tensor`

### Suggest a potential alternative/fix

Add documentation for `torch.nn.functional.multi_head_attention_forward`.

cc @brianjo @mruberry @jbschlosser @bhosmer @cpuhrsch

**Comment by jbschlosser** [comment]
Hey @ProGamerGov, thanks for the report! Should be as simple as adding it to `docs/source/nn.functional.rst`. The module form `nn.MultiHeadAttention` is listed under the "non-linear activation functions" section so the functional form should be as well for consistency. We'd accept a PR doing this.

**Comment by ProGamerGov** [comment]
@jbschlosser Okay. I made I PR for it here: https://github.com/pytorch/pytorch/pull/72675

**Comment by vadimkantorov** [comment]
@jbschlosser would it be better to adjust the name and remove the suffix `_forward` before documenting / making the function public? this suffix doesn't occur in other public functions and also is a mismatch with the module name

**Comment by jbschlosser** [comment]
@vadimkantorov good points, perhaps this was why it was left undocumented before :) Agreed that suffix is non-ideal, although the function is technically considered public by our usual definition since it doesn't begin with an underscore. It's unfortunately been around long enough that renaming it would be BC-breaking and potentially disruptive. For those reasons, even with the bad name, I think we might as well move forward with the intended second part of #49296 by documenting it.

**Comment by vadimkantorov** [comment]
Maybe introduce the good name + turn old name into alias?

**Comment by ProGamerGov** [comment]
@vadimkantorov OpenAI has been using the current function name for their models: https://github.com/openai/CLIP/blob/main/clip/model.py#L70, and a quick search on GitHub shows a lot of others using it as well

**Comment by vadimkantorov** [comment]
Of course, some people (especially those who participated in feature discussion) used it, but the number is probably not too many, and having a new good name + alias would not break these usages

**Comment by qqaatw** [comment]
Hi, I see the PR got reverted. Can we reland it with some fix for the CI failures?
