### ISSUE TITLE
binary_linux_manywheel_3_7m_cu102_devtoolset7_test is broken

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72610]
As it still using deprecated resource class, see https://hud.pytorch.org/ci/pytorch/pytorch/master?name_filter=binary_linux_manywheel_3_7m_cu102_devtoolset7_test

See example of the failure in https://app.circleci.com/jobs/github/pytorch/pytorch/16987033?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by janeyx99** [comment]
Followup: we need to plan better --> we knew it was gonna happen and none of us fixed it early enough. Action item: go through tasks about deprecation in sprint planning
