### ISSUE TITLE
`torch.kaiser_window` fails for meta tensors and `window_length >= 2`

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#72630]
```py
>>> torch.kaiser_window(0, device="meta")
tensor(..., device='meta', size=(0,))
>>> torch.kaiser_window(1, device="meta")
tensor(..., device='meta', size=(1,))
>>> torch.kaiser_window(2, device="meta")
RuntimeError: DispatchStub: unsupported device typemeta
```

#72508 will skip

https://github.com/pytorch/pytorch/blob/c76c4912bbd6c1f2cb3e04d532643ca19393415e/test/test_tensor_creation_ops.py#L2794

for `torch.kaiser_window` and `device="meta"` unconditionally.

cc @gchanan @mruberry

**Comment by mruberry** [comment]
We would definitely accept a fix for this. 

cc @kshitij12345 kaiser_window is probably a good function to move to the jiterator (and this could possibly be fixed at the same time)
