### ISSUE TITLE
Builder repo is not pinned in release branch

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#72655]
### 🐛 Describe the bug

I've noticed that https://github.com/pytorch/pytorch/pull/72217 configures only old CircleCI builds to point to  https://github.com/pytorch/builder/tree/release/1.11 , while new GHA builds keep using main branch of https://github.com/pytorch/builder/

I think it needs to be remedied by landing 2 changes: One to main branch of PyTorch that adds ability to specify branch to https://github.com/pytorch/pytorch/blob/364055b2771ecf9b54f1d67a8bf44bb5496476d4/.github/templates/common.yml.j2#L188 
and update https://github.com/pytorch/pytorch/blob/master/RELEASE.md to mention that changes need to happen in two templates mentioned below
After this is done, in release specific PR that select `release/1.11` branch in https://github.com/pytorch/pytorch/blob/364055b2771ecf9b54f1d67a8bf44bb5496476d4/.github/templates/linux_binary_build_workflow.yml.j2#L56
and
https://github.com/pytorch/pytorch/blob/364055b2771ecf9b54f1d67a8bf44bb5496476d4/.github/templates/windows_binary_build_workflow.yml.j2#L68

### Versions

1.11-RC0

cc @ezyang @gchanan @zou3519

**Comment by seemethere** [comment]
Removing from https://github.com/pytorch/pytorch/labels/triage%20review

**Comment by atalman** [comment]
reopening since multiple PRs needs to be landed for this
