### ISSUE TITLE
deit_small_patch16_224 weights not working

### ISSUE THREAD

**Issue by pic4seradmin** [pytorch/pytorch#72654]
### 🐛 Describe the bug

Hi,
I was trying to import pretrained DeIT Small (```deit_small_patch16_224```), but I got this error:

```
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

No issue with any other model, so I guess the .pth file is corrupted. Can you check?
Thanks!

### Versions

# Hardware
Ubuntu 16.04
GPU: RTX 2080

# Software
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.8.1                    pypi_0    pypi
addict                    2.2.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                   pypi_0    pypi
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
ca-certificates           2019.10.16                    0  
cachetools                3.1.1                    pypi_0    pypi
certifi                   2019.9.11                py37_0  
cffi                      1.12.3           py37h2e261b9_0  
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.10          py37he6710b0_0  
decorator                 4.4.1                      py_0  
easydict                  1.9                      pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.2                    pypi_0    pypi
google-auth               1.6.3                    pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.24.3                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.8                      pypi_0    pypi
importlib-metadata        0.18                     pypi_0    pypi
intel-openmp              2019.4                      243  
ipython                   7.9.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
jedi                      0.15.1                   py37_0  
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10               h2733197_2  
markdown                  3.1.1                    pypi_0    pypi
matplotlib                3.1.0                    pypi_0    pypi
mkl                       2019.4                      243  
mkl_fft                   1.0.12           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0 
more-itertools            7.0.0                    pypi_0    pypi
msgpack                   1.0.0                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.16.4           py37h7e9f1db_0  
numpy-base                1.16.4           py37hde5b4d6_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
opencv-python             4.1.0.25                 pypi_0    pypi
openssl                   1.1.1d               h7b6447c_3  
opt-einsum                3.1.0                    pypi_0    pypi
packaging                 19.0                     pypi_0    pypi
parso                     0.5.1                      py_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.0.0            py37h34e0f95_0  
pip                       19.1.1                   py37_0  
pluggy                    0.12.0                   pypi_0    pypi
prompt_toolkit            2.0.10                     py_0  
protobuf                  3.10.0                   pypi_0    pypi
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    pypi_0    pypi
pyasn1                    0.4.7                    pypi_0    pypi
pyasn1-modules            0.2.7                    pypi_0    pypi
pycocotools               2.0.0                    pypi_0    pypi
pycparser                 2.19                     py37_0  
pygments                  2.4.2                      py_0  
pyparsing                 2.4.0                    pypi_0    pypi
pytest                    4.6.3                    pypi_0    pypi
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                    pypi_0    pypi
pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
requests-oauthlib         1.2.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
scikit-learn              0.22.1                   pypi_0    pypi
scipy                     1.2.1                    pypi_0    pypi
setuptools                41.0.1                   py37_0  
six                       1.12.0                   py37_0  
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.28.0               h7b6447c_0  
tensorboard               1.14.0                   pypi_0    pypi
tensorboardx              2.0                      pypi_0    pypi
tensorflow                1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
torchvision               0.3.0           py37_cu10.0.130_1    pytorch
traitlets                 4.3.3                    py37_0  
urllib3                   1.25.3                   pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.4                   py37_0  
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zipp                      0.5.1                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.25

Python version: 3.6.9 (default, Dec  8 2021, 21:08:43)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: GeForce RTX 2080 SUPER
GPU 1: GeForce RTX 2080 SUPER

Nvidia driver version: 460.73.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.19.5
[pip3] torch==1.10.0
[pip3] torch-scatter==2.0.6
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] Could not collect

**Comment by soulitzer** [comment]
Hey, thanks for the report. Do you mean to post this to a different repo?

If this is a bug with PyTorch, a reproducible script would be very helpful.
