### ISSUE TITLE
GeneralTensorShapeOpQuantizeHandler skip unless reference mode

### ISSUE THREAD

**Issue by HDCharles** [pytorch/pytorch#72698]
### 🚀 The feature, motivation and pitch

per https://discuss.pytorch.org/t/calibration-of-model-in-post-training-static-quantization-using-fx-api/143661/5

it seems there's no real reason for these patterns to not be skipped outside of reference mode quantization since they work if the user explicitly skips them, alternatively, they can cause issues when not skipped unless the non tensor parameters are all hardcoded.

### Alternatives

ignore this and have users manually bypass this issue as in the link

### Additional context

```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.quantization.quantize_fx import prepare_fx, convert_fx

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.lin = nn.Linear(5,1)

    def forward(self, x, y):
        x = self.pool(F.relu(self.conv1(x)))
        x = torch.flatten(x, 1)  # flatten all dimensions except batch
        x = x.view(-1, y)
        x = self.lin(x)
        return x

model=Net().eval()
model(torch.randn(5,3,32,32), 5)
qconfig = torch.ao.quantization.get_default_qconfig("fbgemm")
qconfig_dict = {"": qconfig}
# qconfig_dict = {"": qconfig, "object_type": [('view', None)]}
prepared_model = prepare_fx(model, qconfig_dict)
print(prepared_model.code)
prepared_model(torch.randn(5,3,32,32), 5)
final_model = convert_fx(prepared_model)
print(final_model.code)
final_model(torch.randn(5,3,32,32), 5)
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
given a user could already avoid quantizing the view op (i.e. the solution mentioned in the forum thread) its unclear how many problems the input_quantized_idxs could solve that aren't already solvable as is. So I don't think input_quantized_idxs would have much impact on this specific problem.

On the other hand for the average non power user, having this handled automatically seems to be a strict win.

Given that, the 2 solution approaches seem to have different targets in mind.

**Comment by vkuzo** [comment]
> given a user could already avoid quantizing the view op (i.e. the solution mentioned in the forum thread) its unclear how many problems the input_quantized_idxs could solve that aren't already solvable as is. So I don't think input_quantized_idxs would have much impact on this specific problem.
> 
> On the other hand for the average non power user, having this handled automatically seems to be a strict win.
> 
> Given that, the 2 solution approaches seem to have different targets in mind.

I think the solution currently taken is also correct, sgtm.

> On the other hand for the average non power user, having this handled automatically seems to be a strict win.

After the current fix, the reason it works is:
1. assume all model inputs are torch.float, unless overridden by `input_quantized_idxs`
2. fix incorrect assumptions on node types by inspecting arguments of known ops

(2) is fine, but long term it would be cleaner to also remove incorrect assumptions from (1).  Since we need to transform the graph ahead of time, we cannot expect to magically detect the dtypes of model inputs at runtime, so we should make sure to expect the user to specify the dtypes if they are not float tensors.

**Comment by vkuzo** [comment]
this is fixed
