### ISSUE TITLE
Torch typing: `load_state_dict` overconstrained

### ISSUE THREAD

**Issue by ikamensh** [pytorch/pytorch#72707]
### 🐛 Describe the bug

Module.load_state_dict defines it's input type as OrderedDict, and complains about perfectly working code:

```python
with open("convmix.pt", "rb") as f:
    state_dict = torch.load(f, map_location=torch.device("cpu"))
state_dict = {k.lstrip("module."): v for k, v in state_dict.items()}
model = ConvMixer(args.hdim, args.depth)
model.load_state_dict(state_dict)  # Argument of type "dict[Unknown, Unknown]" cannot be assigned to parameter "state_dict" of type "OrderedDict[str, Tensor]" in function "load_state_dict"
```

Giving the explicit type hint also doesn't suffice:
```python
x : dict[str, torch.Tensor] = {}
model.load_state_dict(state_dict)  # Argument of type "dict[str, Tensor]" cannot be assigned to parameter "state_dict" of type "OrderedDict[str, Tensor]" in function "load_state_dict"
```

I suggest to define input to [`load_state_dict`](https://github.com/pytorch/pytorch/blob/4737ae7a16e75958efd8e0177af8a1b570e9227d/torch/nn/modules/module.py#L1441) in more general terms, according to its narrowest requirements. That would probably be either `dict` or `typing.Mapping`.

### Versions

VSCode (pylance typechecker) on MacOS.
```
(venv) ~/P/regen [1] $ pip freeze | grep torch                                                               
torch==1.10.2
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by lkct** [comment]
Agreed. I've just run into the same issue.
`state_dict()` can actually return any `Mapping[str, Tensor]` type, and `load_state_dict()` should accept the same.
https://github.com/pytorch/pytorch/blob/c9ccb850abadc3fa1ef471e4630c677491032317/torch/nn/modules/module.py#L1281-L1286

**Comment by albanD** [comment]
Yes. We should update both function's typing to respectively return and take as input `Mapping[str, Any]` to match modern use of these functions.

**Comment by albanD** [comment]
`Mapping[str, Any]` since the introduction of the `get_extra_state()` method: https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.get_extra_state

It doesn't have to be in a single PR. Small self contained changes are easier to review and add test for.
