### ISSUE TITLE
FileOpenerIterDataPipe should support an encoding argument

### ISSUE THREAD

**Issue by erip** [pytorch/pytorch#72713]
### 🚀 The feature, motivation and pitch

Currently FileOpenerIterDataPipe defaults to [opening the underlying file in the platform-dependent encoding](https://github.com/pytorch/pytorch/blob/3e1eff9a0ecbe618f96e0e8444bf976fef129a74/torch/utils/data/datapipes/utils/common.py#L92), which results in breakage for utf8-encoded datasets being opened on Windows (where the default encoding is cp1252).

### Alternatives

FileOpenerIterDataPipe can read bytes and punt the decoding step to downstream datapipes.

### Additional context

Torchtext CI is [failing on Windows](https://app.circleci.com/pipelines/github/pytorch/text/4902/workflows/a42722cd-ad58-4e4d-b873-4dc77f529bfd/jobs/163426) when presented with utf-8 encoded files.

cc @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
I see. Does it work if `FileOpener` exposes `encoding` parameter?

**Comment by erip** [comment]
It should as long as that encoding parameter makes it down to the `open` call. I'm happy to pick this one up.

**Comment by ejguan** [comment]
Sounds great! Code pointer would be https://github.com/pytorch/pytorch/blob/master/torch/utils/data/datapipes/iter/fileopener.py

When it's landed, I will make it into PyTorch 1.11 release.

**Comment by ejguan** [comment]
> The only thing to sort out is making the encoding param and mode=='b' mutually exclusive in a user friendly way.

We should be able to do an extra check to raise `ValueError: binary mode doesn't take an encoding argument`
