### ISSUE TITLE
FloatTensor constructor bug

### ISSUE THREAD

**Issue by jrwalsh1** [pytorch/pytorch#7271]
I have come across a strange bug building a `FloatTensor` from a `numpy` array, where I get garbage entries in the `FloatTensor` compared to the `numpy` array.

This happens if the `numpy` array is read directly from a `pandas.HDFStore`, **only** when the data is saved in the `HDFStore` with a non-default index and with `HDFStore.append`.  The problem goes way if any of the following are true:
- I save with `put` rather than `append`.
- The `DataFrame` is saved with the default `index`.
- The `numpy` array is copied before being sent into `FloatTensor`.

This seems extremely specific and like it may be a `pandas`/`pytables` problem, but working with the objects from the `HDFStore` as `numpy` arrays do not give any problems.

Below is a MWE.

## Code example

```python
import numpy as np
import pandas as pd
import torch

np.random.seed(137)

x = np.random.rand(3,3)
print("initial numpy array:")
print(x)
print("---")

df = pd.DataFrame(x, index=['a','b','c']) # creates a problem when saved with "append"
df_bare = pd.DataFrame(x) # OK

with pd.HDFStore("foo.h5", "w") as store:
    store.append("x", df)
    # store.append("x", df_bare) # OK
    # store.put("x", df) # OK
    # store.put("x", df_bare) # OK

y = pd.read_hdf("foo.h5", "x").values
print("loaded numpy array:")
print(y)
print("---")

# y = np.array(y) # this fixes the problem
t = torch.FloatTensor(y)
print("torch tensor:")
print(t)
```

On my system I get the output
```
initial numpy array:
[[0.94385021 0.08854403 0.69537097]
 [0.69999035 0.49960034 0.50270302]
 [0.89180317 0.08895364 0.84749637]]
---
loaded numpy array:
[[0.94385021 0.08854403 0.69537097]
 [0.69999035 0.49960034 0.50270302]
 [0.89180317 0.08895364 0.84749637]]
---
torch tensor:
tensor([[ 9.4385e-01,  8.8544e-02,  6.9537e-01],
        [       -inf,        -inf,        -inf],
        [-0.0000e+00, -4.0896e+27,  0.0000e+00]])
```

## System Info
Here is the output of `collect_env`:
```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.12.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.1)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```
Additionally, my `pandas` version is 0.22.0 and `tables` version is `3.4.2`.

**Comment by SsnL** [comment]
What if you do `torch.from_numpy(y)`? Also the numpy array should be `float64` dtype iirc, so could you try `DoubleTensor` too?

**Comment by jrwalsh1** [comment]
The behavior is the same using `torch.DoubleTensor(y)` (or casting `x` to `float32` and using `FloatTensor`), and for `torch.from_numpy(y)`.  For example here is the output for `from_numpy` when casting `x` to `float32`:
```
initial numpy array:
[[0.9438502  0.08854403 0.695371  ]
 [0.69999033 0.49960035 0.502703  ]
 [0.89180315 0.08895364 0.8474964 ]]
---
loaded numpy array:
[[0.9438502  0.08854403 0.695371  ]
 [0.69999033 0.49960035 0.502703  ]
 [0.89180315 0.08895364 0.8474964 ]]
---
torch tensor:
tensor([[ 9.4385e-01,  8.8544e-02,  6.9537e-01],
        [ 4.1576e-08,         nan,  1.6268e-38],
        [ 1.9125e+08,  1.2008e-11, -3.4034e+32]])
```

**Comment by jrwalsh1** [comment]
I believe I understand more thoroughly what is going on:  
- The `numpy` array coming from reading the `HDFStore` does not have contiguous memory.
- The strides are not multiples of the byte size of single elements, which I think leads to `PyTorch` reading the wrong memory block *beyond the first row*.

Here is what I get when printing `.array.flags` and `.strides` on the `numpy` arrays (using `float32` arrays):

`x` (direct array creation):
```
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides: (12, 4)
```

`y` (the loaded array):
```
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : False
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

strides: (13, 4)
```
You can see the loaded array is neither `C_CONTIGUOUS` nor `F_CONTIGUOUS`, and it's just a reference (presumably to the `pandas.DataFrame` loaded from the store with `PyTables`).

In [from_numpy](https://github.com/pytorch/pytorch/blob/db53389761fa87af09358bc1afa2157be0468130/torch/csrc/utils/tensor_numpy.cpp#L99), it looks like there's an implicit assumption that the memory is contiguous and in steps that are a multiple of the byte size of single elements.  I assume that making a copy of the array in the `FloatTensor` constructor is needed.

**Comment by fmassa** [comment]
There is no assumption that the array is contiguous in `from_numpy`. But it seems that there is one extra byte that was added to the numpy array that can be handled by numpy (because the strides are specified in bytes), but that can't be handled by pytorch (because the strides are handled wrt the data type size). I think a copy is necessary here

**Comment by apaszke** [comment]
We should just have a check that strides are multiples of element sizes, and raise an error otherwise. There's no way to handle that in PyTorch at the moment.

**Comment by fmassa** [comment]
And do we ever plan to handle that? I thought that strides in c10 will still be multiples of the element size?

**Comment by apaszke** [comment]
That's a question to @ezyang. This issue might actually be an argument to change this convention (with the huge downside being that a lot of our current code will need to be updated).

**Comment by ezyang** [comment]
@fmassa and I chatted about this, and there is no plans in C10 to change strides to be bytes-based.

I suppose once @gchanan finishes rewriting TH/THC to not directly field access, it would be less difficult (though still tough; the public API assumes you can take non-owning references to the per-element strides array) to change the internal representation. But... getting this going, and now having misaligned reads/writes everywhere, sounds awful. Seems like it would almost be better to make a copy, and then do an unaligned copy back into the original struct.
