### ISSUE TITLE
Investigate support for parameters(), named_parameters() in FSDP

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#72716]
### 🚀 The feature, motivation and pitch

Make sure that we have the correct semantics for parameters() and named_parameters() in FSDP.

For example, under full parameter summoning context, we should ensure `parameters()` returns params with the appropriate original shapes, and `named_parameters` appropriately restores parameter names of the original module.

In addition, we should discuss what these APIs should return without non-full parameter summoning context (i.e. possibly we just do not support named_parameters()?)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
This has been discussed internally, especially for the composability efforts. I am marking this as closed.
