### ISSUE TITLE
jit.script mis-optimizes code causing cpu fallbacks

### ISSUE THREAD

**Issue by jatentaki** [pytorch/pytorch#72720]
### 🐛 Describe the bug

I am using the following function (yes, I know there's a variant implemented in `nn.functional`)

```python
@torch.jit.script
def smooth_l1(x, beta: float):
    t = x.abs()
    return torch.where(x < beta, 0.5 * t ** 2 / beta, t - 0.5 * beta)
```

and I just found that the `jit.script` decorator mis-optimizes the code, causing cpu fallsbacks and greatly slowing down the code, as evidenced by the profiler:

Without `jit.script`:
![image](https://user-images.githubusercontent.com/22394841/153630308-1e40b4d7-4bfe-47ac-9520-9f3d1bc9cc7f.png)

with `jit.script`:
![image](https://user-images.githubusercontent.com/22394841/153630569-9e475956-4f4e-4940-bcab-8cdb7d7b0305.png)

(note the huge red block of `fallback_function` on the towards the end of the code block). Similarly to issue #52286 I am using this code with varying sizes of `x`, but I would expect to see overhead in some jit compilation routine, rather than CPU fallbacks.

### Versions

PyTorch version: 1.10.0.dev20210921+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-1029-gcp-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.4.7
[pip3] torch==1.10.0.dev20210921+cu111
[pip3] torch-dimcheck==0.2.3
[pip3] torchmetrics==0.4.1
[pip3] torchvision==0.11.0.dev20210921+cu111
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.20.3           py38h74d4b33_0  
[conda] pytorch-lightning         1.4.7                    pypi_0    pypi
[conda] torch                     1.10.0.dev20210921+cu111          pypi_0    pypi
[conda] torch-dimcheck            0.2.3                     dev_0    <develop>
[conda] torchmetrics              0.4.1                    pypi_0    pypi
[conda] torchvision               0.11.0.dev20210921+cu111          pypi_0    pypi

**Comment by eellison** [comment]
Hi, this is fixed on master and will be in upcoming release. In process of landing docs here: https://github.com/pytorch/pytorch/pull/72639
