### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export Python operator GridSampler

### ISSUE THREAD

**Issue by heils003** [pytorch/pytorch#7273]
I tried to use ONNX to transform my Pytorch model but with error like this:
```
proto = trace.export(list(model.state_dict().values()), _onnx_opset_version)
RuntimeError: ONNX export failed: Couldn't export Python operator GridSampler
```
It seems ONNX can't find the same method like the Pytorch Function GridSampler. And it was setted `UNKNOWN_TYPE` on the Layer Operator???  How can I solve it ?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
I am not sure if `trace.export` pointing to `torch.onnx.export`. Is this a PyTorch API?

**Comment by garymm** [comment]
IIUC, this issue is obsolete now that grid_sampler is a native ATen op. Related issue is #27212 for exporting aten::grid_sampler.
