### ISSUE TITLE
[feature request] make DataParallel and DistributedDataParallel's module as public

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/pytorch#7274]
After training the DataParallel or DistributedDataParallel's model, we may resume the trained model, however [resume the parallel model while not unpack it](https://github.com/pytorch/examples/blob/83f1b5c2667c820b672852d8a5b6971835e6406f/imagenet/main.py#L104) is not a good idea while DataParallel and DistributedDataParallel are just used to accelerate training via parallel. So we would like to unpack them first and save the raw model sometimes.

However, although the `module` is public in the source code, this is not explicit in the doc. If we only reference the explicit and public code, we have to unpack the model like `a = list(b.modules())[0]` while `b` is the paralleled model, it is ugly. So I advice that make DataParallel and DistributedDataParallel's module as public so that we can unpack it comfortably.

**Comment by soumith** [comment]
what do you mean by "make it public", I am not sure I understand.

**Comment by acgtyrant** [comment]
Tell everyone in the doc that `module` is a public member of `DataParallel` or `DistributedDataParallel` that we can use this API .

**Comment by apaszke** [comment]
You can safely access `.module`, we will never change that. If you'd like this clarified, please send a PR with a doc fix!

**Comment by acgtyrant** [comment]
Please wait for a few days because I don’t have a computer at hand.

**Comment by acgtyrant** [comment]
`nn.int.ones_(module.weight)` is always more readable than `nn.init.constant_(module.weight, 1)`, and for `nn.init.zeros_`. as well.
