### ISSUE TITLE
TorchVision Tries To Install Torch Again

### ISSUE THREAD

**Issue by lucifertrj** [pytorch/pytorch#72762]
### 🐛 Describe the bug

When I try to install TorchVision, it tries to re-install Torch Again. Is there any alternative method?

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by soulitzer** [comment]
I think one workaround is to pass `--no-deps` to pip when install torchvision and install the remaining dependencies manually.

**Comment by soulitzer** [comment]
Closing for now, feel free to reopen if this does not address your issue
