### ISSUE TITLE
Determinism for MaxPool3d and AvgPool3d

### ISSUE THREAD

**Issue by skim2257** [pytorch/pytorch#72766]
### 🚀 The feature, motivation and pitch

I mainly train 3D CNN models and I recently updated from PyTorch 1.5 to 1.10. While trying to train my model on the updated environment, I encountered this error: 
```
RuntimeError: avg_pool3d_backward_cuda does not have a deterministic 
implementation, but you set 'torch.use_deterministic_algorithms(True)'. You 
can turn off determinism just for this operation if thats acceptable for your 
application. You can also file an issue at https://github.com/pytorch/pytorch/issues
to help us prioritize adding deterministic support for this operation
```

I've trained non-deterministic models in the past but the main limitation of 3D medical imaging datasets is that they're very small, and are thus prone to large fluctuations in performance based on the random seed. I found that there are large fluctuations even with a fixed torch.manual-seed(). 

I'd really appreciate if support for MaxPool3d and AvgPool3d could be prioritized as (I hope) refactoring MaxPool2d/AvgPool2d determinism for these operations shouldn't be very difficult. 

Thanks dev team for the great work as always 😀

### Alternatives

Training n=500 models for some confidence intervals... But determinism sounds like a better idea h a h a h a

**Comment by mruberry** [comment]
Thank you for this feature request, @skim2257. We would accept a PR adding this functionality.

**Comment by kurtamohler** [comment]
@LvJC, at the moment, they are implemented using an algorithm that can add numbers together in a different order each time it's run. Due to floating point error, different orders can produce slightly different results

**Comment by LvJC** [comment]
@kurtamohler When you said "add numbers together in a different order each time it's run", do you mean CUDA `atomicAdd()` function?

**Comment by kurtamohler** [comment]
> do you mean CUDA `atomicAdd()` function?

Yep, that's right

**Comment by MJGroeneveld** [comment]
Is this already fixed? I get the following warning: UserWarning: avg_pool3d_backward_cuda does not have a deterministic implementation

**Comment by csheaff** [comment]
Any updates on this? Resnets (max_pool3d_with_indices_backward_cuda) and Densenets (avg_pool3d_backward_cuda) are still nondeterministic.
