### ISSUE TITLE
grad strides do not match bucket view strides

### ISSUE THREAD

**Issue by KaoJZhu** [pytorch/pytorch#72787]
### 🐛 Describe the bug

when I used torch.sigmoid(a), occurred  "Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed. This is not an error, but may impair performance. grad.sizes() = [1, 64, 1, 1], strides() = [64, 1, 64 64]".
However, it missed when i uesd a.sigmoid_().

### Versions

pytorch 1.10

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @ezyang @zou3519 @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by gchanan** [comment]
do you have a reproduction?

**Comment by ngimel** [comment]
Likely fixed by #72542
