### ISSUE TITLE
FX graph mode quant: support fusing linear -> view -> BN

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#72797]
### 🐛 Describe the bug

This is a request from one of the customer teams, for fusing syntax such as this one

```
nn.Sequential(
  nn.Linear(num_input_features, int(np.prod(feature_shape))),
  View((-1, *feature_shape)),
  nn.BatchNorm2d(feature_shape[0]),
)
```

### Versions

n/a

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @jgong5 @Xia-Weiwen @leslie-fang-intel @ezyang @SherlockNoMad @EikanWang @wenzhe-nrv @vkuzo

**Comment by jerryzh168** [comment]
fx quant is in maintenance mode, so we'll close this one, backend specific quantizers can support it in pt2 export flow if needed
