### ISSUE TITLE
Export torch.maximum() op in ONNX format

### ISSUE THREAD

**Issue by livankrekh** [pytorch/pytorch#72790]
### 🚀 The feature, motivation and pitch

I'm working with network that contains torch.maximum() operations. Now I need to convert this network to ONNX format, but when I tried to do it I got following error:
```
File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    module=module)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator maximum to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

I'm utilizing PyTorch v. 1.10.2. Does anyone know at what stage in the development of this feature?

**Comment by thiagocrepaldi** [comment]
@livankrekh Could you provide a full repro script?

**Comment by livankrekh** [comment]
@thiagocrepaldi Sorry, I cannot provide full code. I can say in this network I utilized torch.maximum() in every possible way.

**Comment by livankrekh** [comment]
@thiagocrepaldi @samdow Send you code that reproduce this issue. Tried with opset=9 and opset=11
```python
import torch
import torch.nn as nn
from torchvision import models

def _sort(x, dim=0, keepdim=False):
    x_sum = torch.sum(x, dim, keepdim)
    x_rand = torch.randn(x_sum.shape).cuda()
    return torch.maximum(x_sum, x_rand)

class SpatialAttention(nn.Module):
    def __init__(self):
        super(SpatialAttention, self).__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=3, padding=1, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = _sort(x, dim=1, keepdim=True)
        max_out, _ = torch.min(x, dim=1, keepdim=True)
        scale = torch.cat([avg_out, max_out], dim=1)
        scale = self.conv(scale)
        out = torch.maximum(x, self.sigmoid(scale))
        return out


class SpatialFeatureExtractor(nn.Module):
    def __init__(self, onnx_batch_size):
        super(SpatialFeatureExtractor, self).__init__()
        self.onnx_batch_size = onnx_batch_size
        vgg11_model = models.vgg11_bn(pretrained=True)
        vgg11_part1 = vgg11_model.features[:11]
        vgg11_part2 = vgg11_model.features[11:15]
        for param in vgg11_part1.parameters():
            param.requires_grad = False
        for param in vgg11_part2.parameters():
            param.requires_grad = True

        self.feature_extractor_p1 = nn.Sequential(
            vgg11_part1
        )

        self.spatialAtt = SpatialAttention()

        self.feature_extractor_p2 = nn.Sequential(
            vgg11_part2,
            nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(256, 256, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 128, kernel_size=3, stride=2, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        p1_features = self.feature_extractor_p1(x)
        features_after_attention = self.spatialAtt(p1_features)

        p2_features = self.feature_extractor_p2(features_after_attention)
        features = p2_features.view(self.onnx_batch_size, -1, 1, 1)
        
        return features

if __name__ == "__main__":
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    image = torch.zeros(1, 3, 224, 224).to(device)

    nn = SpatialFeatureExtractor(1).to(device)
    nn.train(False)

    torch.onnx.export(nn, (image), "feature_extractor.onnx", verbose=False, \
                      input_names=['input'],
                      output_names=['features'])
```

**Comment by 24werewolf** [comment]
> @thiagocrepaldi @samdow Send you code that reproducing this issue. Tried with opset=9 and opset=11
> 
> ```python
> import torch
> import torch.nn as nn
> from torchvision import models
> 
> def _sort(x, dim=0, keepdim=False):
>     x_sum = torch.sum(x, dim, keepdim)
>     x_rand = torch.randn(x_sum.shape).cuda()
>     return torch.maximum(x_sum, x_rand)
> 
> class SpatialAttention(nn.Module):
>     def __init__(self):
>         super(SpatialAttention, self).__init__()
>         self.conv = nn.Conv2d(2, 1, kernel_size=3, padding=1, bias=False)
>         self.sigmoid = nn.Sigmoid()
> 
>     def forward(self, x):
>         avg_out = _sort(x, dim=1, keepdim=True)
>         max_out, _ = torch.min(x, dim=1, keepdim=True)
>         scale = torch.cat([avg_out, max_out], dim=1)
>         scale = self.conv(scale)
>         out = torch.maximum(x, self.sigmoid(scale))
>         return out
> 
> 
> class SpatialFeatureExtractor(nn.Module):
>     def __init__(self, onnx_batch_size):
>         super(SpatialFeatureExtractor, self).__init__()
>         self.onnx_batch_size = onnx_batch_size
>         vgg11_model = models.vgg11_bn(pretrained=True)
>         vgg11_part1 = vgg11_model.features[:11]
>         vgg11_part2 = vgg11_model.features[11:15]
>         for param in vgg11_part1.parameters():
>             param.requires_grad = False
>         for param in vgg11_part2.parameters():
>             param.requires_grad = True
> 
>         self.feature_extractor_p1 = nn.Sequential(
>             vgg11_part1
>         )
> 
>         self.spatialAtt = SpatialAttention()
> 
>         self.feature_extractor_p2 = nn.Sequential(
>             vgg11_part2,
>             nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1),
>             nn.BatchNorm2d(256),
>             nn.ReLU(inplace=True),
>             nn.MaxPool2d(kernel_size=2, stride=2),
>             nn.Conv2d(256, 256, kernel_size=3, stride=2, padding=1),
>             nn.BatchNorm2d(256),
>             nn.ReLU(inplace=True),
>             nn.Conv2d(256, 128, kernel_size=3, stride=2, padding=1),
>             nn.BatchNorm2d(128),
>             nn.ReLU(inplace=True)
>         )
> 
>     def forward(self, x):
>         p1_features = self.feature_extractor_p1(x)
>         features_after_attention = self.spatialAtt(p1_features)
> 
>         p2_features = self.feature_extractor_p2(features_after_attention)
>         features = p2_features.view(self.onnx_batch_size, -1, 1, 1)
>         
>         return features
> 
> if __name__ == "__main__":
>     device = 'cuda' if torch.cuda.is_available() else 'cpu'
>     image = torch.zeros(1, 3, 224, 224).to(device)
> 
>     network = SpatialFeatureExtractor(1).to(device)
>     network.train(False)
> 
>     torch.onnx.export(network, (image), "feature_extractor.onnx", verbose=False, \
>                       input_names=['input'],
>                       output_names=['features'])
> ```
HI, did you solve this problem

**Comment by 24werewolf** [comment]
> @livankrekh Could you provide a full repro script?

I also have the same problem

**Comment by laurenckim** [comment]
I have the same problem as well

**Comment by sumo2017** [comment]
I have the same problem as well

**Comment by qqaatw** [comment]
Supported by #73103, in `1.12` release branch.
