### ISSUE TITLE
Missing headers in ATen/cuda/DeviceUtils.cuh

### ISSUE THREAD

**Issue by an99990** [pytorch/pytorch#72807]
### 🐛 Describe the bug

As @stas00  suggested, I am opening this issue regarding missing headers.
From https://github.com/pytorch/pytorch/issues/69746 , it was found that replacing the import would suffice but it did not in my case. Some identifiers seems to be missing from `THC/THCDeviceUtils.cuh` migration to `ATen/cuda/DeviceUtils.cuh`
```"
#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>
#include <THC/THC.h>
#include <THC/THCDeviceUtils.cuh>

#include <vector>
#include <iostream>
```
after

```
#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>
#include <THC/THC.h>
#include "ATen/cuda/DeviceUtils.cuh"

#include <vector>
#include <iostream>
```

error while building [AdelaiDET](https://github.com/aim-uofa/AdelaiDet)

```
/AdelaiDet/adet/layers/csrc/ml_nms/ml_nms.cu(68): error: identifier "THCCeilDiv" is undefined

/AdelaiDet/adet/layers/csrc/ml_nms/ml_nms.cu(85): error: identifier "THCCeilDiv" is undefined

/AdelaiDet/adet/layers/csrc/ml_nms/ml_nms.cu(95): error: identifier "THCudaMalloc" is undefined

/AdelaiDet/adet/layers/csrc/ml_nms/ml_nms.cu(106): error: identifier "THCudaCheck" is undefined

/AdelaiDet/adet/layers/csrc/ml_nms/ml_nms.cu(131): error: identifier "THCudaFree" is undefined
```
Replacing  `THCCeilDiv` with `ATenCeilDiv` does not help, I have tried importing `#include <ATen/ceil_div.h>`
and replacing `THCCeilDiv` with `ceil_div` but the issue remains.
please help

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0a0+bfe5ad2
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.55
GPU models and configuration: GPU 0: Quadro RTX 4000
Nvidia driver version: 472.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.11.0a0+bfe5ad2
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.12.0a0
[pip3] torchvision==0.12.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.22.0           py38h6ae9a64_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.11.0a0+bfe5ad2          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.12.0a0                 pypi_0    pypi
[conda] torchvision               0.12.0a0                 pypi_0    pypi
```

**Comment by an99990** [comment]
@ngimel please help

**Comment by ngimel** [comment]
For THCCeilDiv please see instructions in #65472.
For THCudaCheck please see instructions in #66391
For THCudaMalloc/Free, please see instructions in #65492

**Comment by stas00** [comment]
but that means that the fix applied to resolve the BC breakage in https://github.com/pytorch/pytorch/issues/69746 is incomplete, since all it did is to add:

```
$ cat THC/THCDeviceUtils.cuh
#pragma once
// TODO: Remove this header
#include <ATen/cuda/DeviceUtils.cuh>
```

which as @an99990 indicated isn't the same. So if you want to make a cycle of deprecation perhaps then that BC-wrapper should include the includes that were removed?

I'm sure I probably miss the bigger picture, but at which revision was `THC/THCDeviceUtils.cuh` deprecated and for each revision it was scheduled to be removed?

And how this gets communicated to the non-pytorch-core devs who use CUDA extensions?

**Comment by ngimel** [comment]
We don't have bc-compatibility guarantees on c++ helper functions. Release notes for 1.11 will list the 3 PRs above with instructions from PRs on what needs to be replaced.

**Comment by stas00** [comment]
I don't think it's so much of an issue of guarantees as much as it's very difficult to adapt.

Most application developers have to support older pytorch, thus it's not replacing but continuing using old way for older pytorch and new way for newer pytorch versions.

so why put the onus on the users when this can be dealt with once on the pytorch side.

I propose to have a pseudo code version of a header file that tracks the changes and which the CUDA developer could easily sync with and your team could update it every new release or whenever there is a change in c++ API. It'd also help to have the IF definitions to get the python versions right.

e.g.:

```
// tracking newer versions on top

#elif PT_VERSION_1_11

// THCCeilDiv is no more - replaced with XYZ see https://github.com/pytorch/pytorch/pull/65472
// THCudaCheck please see instructions in https://github.com/pytorch/pytorch/pull/66391
// For THCudaMalloc/Free, please see instructions in https://github.com/pytorch/pytorch/pull/65492
// XXX: add other definitions that were moved/renamed/removed

#ifdef PT_VERSION_1_10

// all THC API is here
#include THC/THCDeviceUtils.cuh

#else

// random suggestion as a fallback.
#define THCCeilDiv ...

#endif
```

Please ignore the specifics, I haven't checked if any of these definitions exist

Now this is one file that can have a new section added at each new release and the developers can look it up and adjust their wrappers easily.

This is just an idea of course... Please feel free to ignore.

**Comment by an99990** [comment]
So I made the following changes according to @ngimel 

```
THCudaMalloc(state, boxes_num * col_blocks * sizeof(unsigned long long));
c10::cuda::CUDACachingAllocator::raw_alloc(state, boxes_num * col_blocks * sizeof(unsigned long long));
```
got `error: argument of type "THCState *" is incompatible with parameter of type "size_t"`

```
THCCeilDiv(n_boxes, threadsPerBlock) 
at::ceil_div(n_boxes, threadsPerBlock)
```
That one passed

for `THCudaCheck`, 
replaced with `C10_CUDA_CHECK`
it passed.

and theres `THCudaFree`

**Comment by ngimel** [comment]
`raw_alloc` does not have `state` argument as noted in #65492. THCudaFree has to be replaced by `raw_delete(ptr)` as noted in #65492

**Comment by ngimel** [comment]
> I don't think it's so much of an issue of guarantees as much as it's very difficult to adapt.
> 
> Most application developers have to support older pytorch, thus it's not replacing but continuing using an old way for older pytorch versions and a new way for newer pytorch versions, which often results in more than 2 ways.

The replacement APIs did not appear in pytorch 1.10, they have been available for more than 2 years, that's why the recommendation is to just switch to proposed replacements, and not implement logic to support pytorch versions that are more than 2 years old.

**Comment by an99990** [comment]
thanks @stas00 and @ngimel i was able to build

**Comment by stas00** [comment]
Thank you for quantifying the availability time.

Let's look at the release dates:

1. v1.2.0 was released on Aug 8, 2019 https://github.com/pytorch/pytorch/tree/refs/tags/v1.2.0
2. v1.4.0 was released on Jan 15, 2020 https://github.com/pytorch/pytorch/tree/v1.4.0

so 2 years puts us somewhere in the pt-1.4 brackets, so what you're saying is that if the project supports pt > 1.4 then they can safely replace the old c++ api with the new. If they have to support an even earlier version then things are more complicated.

**Comment by kvnptl** [comment]
> So I made the following changes according to @ngimel
> 
> ```
> THCudaMalloc(state, boxes_num * col_blocks * sizeof(unsigned long long));
> c10::cuda::CUDACachingAllocator::raw_alloc(state, boxes_num * col_blocks * sizeof(unsigned long long));
> ```
> 
> got `error: argument of type "THCState *" is incompatible with parameter of type "size_t"`
> 
> ```
> THCCeilDiv(n_boxes, threadsPerBlock) 
> at::ceil_div(n_boxes, threadsPerBlock)
> ```
> 
> That one passed
> 
> for `THCudaCheck`, replaced with `C10_CUDA_CHECK` it passed.
> 
> and theres `THCudaFree`

Add these two header files, and remove `#include <THC/THC.h>`
```
#include <ATen/ceil_div.h>
#include <ATen/cuda/ThrustAllocator.h>
```

1. For `THCCeilDiv`
- Replace `THCCeilDiv` with `at::ceil_div`

2. For `THCudaCheck`
- Replace `THCudaCheck` with `AT_CUDA_CHECK`

3. For `THCudaFree`
- Replace `THCudaFree(state, mask_dev);` with `c10::cuda::CUDACachingAllocator::raw_delete(mask_dev);`

4. For `THCudaMalloc`
- Replace `THCudaMalloc(state, boxes_num * col_blocks * sizeof(unsigned long long));` with `c10::cuda::CUDACachingAllocator::raw_alloc(boxes_num * col_blocks * sizeof(unsigned long long));`

NOTE: Tested on PyTorch `1.12.0`, CUDA compiler `11.6`, GCC `10.1.0`

**Comment by Arpitrf** [comment]
Hello, by replacing 
`HCudaMalloc(state, boxes_num * col_blocks * sizeof(unsigned long long)); with c10::cuda::CUDACachingAllocator::raw_alloc(boxes_num * col_blocks * sizeof(unsigned long long));`
I am getting:
`error: name followed by "::" must be a class or namespace name`

Any idea how to resolve this?
