### ISSUE TITLE
[distributed] tell which address for RuntimeError: Address already in use

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#72816]
### 🚀 The feature, motivation and pitch

When running a test suite that uses `torch.distributed` and uses multiple ports a failing test with: `RuntimeError: Address already in use` is insufficient information to resolve the problem. Especially when a failure of one test affects a whole series of other tests. - i.e. the impact it remote.

I'm asking if it'd be possible to extend this error and include the actual `addr:port` string in the error message.

Thank you.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by vadimkantorov** [comment]
also, not sure why random port selection fails...

**Comment by cbalioglu** [comment]
Hey @stas00, which version of PyTorch are you using in your tests? A short while ago I rewrote the socket implementation of `TCPStore` from scratch due to similar reasons and substantially improved the error handling and logging (including what you are requesting in this issue). See [the relevant line](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/socket.cpp#L508).

Those changes will be included in v1.11.

**Comment by stas00** [comment]
I tested and indeed it now reports that info in pt-1.11-tobe:
```
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:10999 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:10999 (errno: 98 - Address already in use).
```

It looks that interleaved error messages have been mostly fixed as well in nightly, Amazing!

Thank you very much for fixing that, @cbalioglu!

**Comment by cbalioglu** [comment]
Glad that the improvements helped with your use case! You are welcome!

**Comment by abhishek47kashyap** [comment]
If on an older version of PyTorch i.e. before v1.11, here's one way to obtain `addr:port`:
(may require sudo rights)
(`netstat` is needed which can be installed through `sudo apt install net-tools`)
1. Run `netstat -tulnp | grep python`. Example output:
```
tcp        0      0 172.17.0.3:58007        0.0.0.0:*               LISTEN      120220/python       
tcp        0      0 0.0.0.0:29500           0.0.0.0:*               LISTEN      120148/python       
tcp        0      0 172.17.0.3:41711        0.0.0.0:*               LISTEN      120220/python
```
2. In this example there are 3 PIDs (see rightmost column), each of which has to be checked with `ps -p ## -o pid,cmd` where `##` will be `120220`, `120148`, and `120220` to find the associated `cmd`.

Looking at the `cmd` one can figure out the `addr:port` in use (for example `0 0.0.0.0:29500`).
