### ISSUE TITLE
Allow `nn.Sequential` to take a normal dict (along with OrderedDict)

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#72815]
### 🚀 The feature, motivation and pitch

Right now, `nn.Sequential` allows you to pass in an `OrderedDict` that can label each sub-module with a name. As of Python 3.6 though, normal `dict`s are also ordered, and this has become a language guarantee as-of Python 3.7. Because of this, I think it's worth considering allowing `nn.Sequential` to take just a normal dictionary instead of only `OrderedDict`, which would allow you to use dictionary literals.

### Alternatives

We could wait until we drop Python 3.6 support and only support Python 3.7+ (when dictionary ordering becomes a language guarantee rather than an implementation choice). Alternatively, we could just continue requiring ordereddict to better communicate intent.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
Note that we already dropped support for python 3.6.

That being said, while the `dict` is indeed ordered, it does have a semantic difference with `OrderedDict`: for one, the order is important while for the other it is just a side effect of the implementation.

In the case of Sequential, we want an ordered set of Modules that will be used in order during the forward pass. So the order is actually important. So I think we should keep the `OrderedDict` constraint here.

**Comment by alanhdu** [comment]
> That being said, while the dict is indeed ordered, it does have a semantic difference with OrderedDict: for one, the order is important while for the other it is just a side effect of the implementation.

I'm ok with closing this issue -- I think of the `dict` ordering as part of the semantics now since it's part of the specification, but I could see why using `OrderedDict` might still be desirable for signalling that more.
