### ISSUE TITLE
Extracting weights from .pth file to easy format binary file

### ISSUE THREAD

**Issue by Gleb845** [pytorch/pytorch#7282]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): I don't install PyTorch
- Build command you used (if compiling from source):
- OS: Windows7
- PyTorch version: -
- Python version: -
- CUDA/cuDNN version: -
- GPU models and configuration: -
- GCC version (if compiling from source): -
- CMake version: -
- Versions of any other relevant libraries: -
How can I extract weights from .pth file to binary file?

**Comment by Gleb845** [comment]
For example, we have a convolution layer. It has n filters. Each filter has a three-dimensional array of weights (d - depth, h - height, w-width). Thus, the layer weights can be represented as a four-dimensional array [n, d, h, w]. Moreover, the elements of this array will be of type float or single(depending on the language). InstanceNorm requires 2 one-dimensional parameter arrays(shift and scale). And so for each layer consistently. In the file you just need to sequentially write these arrays in a sequence, made up of groups of 4 bytes(that is how big a variable of type float). For example, for a convolutional layer with 3 filters, 3x3 size and 3 depth, we will have 81 float number, so 81*4=324 bytes will be written to the file. Translate required pre-learned model, Justin Johnson architecture.For example, the same model that is implemented in DeepLearn.JS (https://github.com/reiinakano/fast-style-transfer-deeplearnjs). You can see how model data is stored in this library. Look in the folder with one of the models: https://github.com/reiinakano/fast-style-transfer-deeplearnjs/tree/master/src/ckpts/la_muse. There is a file .JSON with array sizes and a set of files with the weights themselves. Further, this data is used in the program. I need exactly this format.

**Comment by apaszke** [comment]
It shouldn't be too hard to write an exporter yourself in Python in just a few lines. We don't plan to support writing to any other formats than the pickle one and ONNX, because nothing else is standardized and understood by a wide range of software. Hope this makes sense.
