### ISSUE TITLE
Profiler crashes in export_chrome_trace with seg fault if any of record_shapes=True or with_flops=True

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#72858]
### 🐛 Describe the bug

Profiler crashes in export_chrome_trace with seg fault if any of record_shapes=True or with_flops=True:
```
1: Current thread 0x00007fe0445590c0 (most recent call first):
 1:   File "/home/ec2-user/miniconda3/envs/fsdp_1T/lib/python3.8/site-packages/torch/autograd/profiler.py", line 238 in export_chrome_trace
 1:   File "/home/ec2-user/miniconda3/envs/fsdp_1T/lib/python3.8/site-packages/torch/profiler/profiler.py", line 340 in export_chrome_trace
 1:   File "/home/ec2-user/miniconda3/envs/fsdp_1T/lib/python3.8/site-packages/torch/profiler/profiler.py", line 86 in handler_fn
 1:   File "/home/ec2-user/miniconda3/envs/fsdp_1T/lib/python3.8/site-packages/torch/profiler/profiler.py", line 427 in _exit_actions
 1:   File "/home/ec2-user/miniconda3/envs/fsdp_1T/lib/python3.8/site-packages/torch/profiler/profiler.py", line 270 in stop
 1:   File "/home/ec2-user/miniconda3/envs/fsdp_1T/lib/python3.8/site-packages/torch/profiler/profiler.py", line 259 in _exit_
 1:   File "trainer.py", line 226 in train
 1:   File "trainer.py", line 274 in main
 1:   File "trainer.py", line 278 in <module>
 1: Fatal Python error: Segmentation fault
```
I removed record_shapes=True or with_flops=True and it works fine

It happened on AWS p4d.24xlarge with A100-SXM4-40GB

### Versions

Don't have exact versions, the cluster doesn't exist anymore, but it was PT master somewhere in December 2021

cc @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @orionr @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by robieta** [comment]
Thanks for the report. I've noticed trace export can segfault if the trace is too large; my guess it that it's not due to the specific args, but rather because they add extra bytes to the trace. We're currently doing a major stability overhaul of profiler and kineto, so hopefully this will be addressed soon.

**Comment by zhanwenchen** [comment]
@robieta Any update?

**Comment by aaronenyeshi** [comment]
This issue is no longer reproducible. Please open a new issue if this happens again.
