### ISSUE TITLE
REQUIRE(y.sum().toCFloat() < 130) is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7286]
```
15:54:16 /var/lib/jenkins/workspace/test/cpp/api/container.cpp:217: FAILED:
15:54:16   REQUIRE( y.sum().toCFloat() < 130 )
15:54:16 with expansion:
15:54:16   130.0f < 130
```

The test, by its nature, seems to be flaky. Maybe there is a better statistical test you can grab from PyTorch's test suite.

CC @ebetica @goldsborough

**Comment by t-vi** [comment]
As far as I can tell, the RNG is not seeded here and the tested value is random. My back of the envelope calculation would have this test failing very frequently. If I put `setSeed(7);` right below the line [`SECTION("dropout") {`](https://github.com/pytorch/pytorch/blob/54a48676751c28c5d355e7114b17e8942b28c721/test/cpp/api/container.cpp#L209), I get the same result (106 in my particular case) every time.

I don't know Catch2 well enough to say if there is a way to have each SECTION automatically initialize the RNG (at the TEST_CASE level one might work with fixtures).

**Comment by goldsborough** [comment]
Catch2 reruns through a `TEST_CASE` from the top down to a particular section for each section, so putting it at the start of the `TEST_CASE` would set the seed for every section. A `TEST_CASE` is effectively a fixture

**Comment by SsnL** [comment]
130 is only 1.2 std away from mean. Since this is very close to normal, it fails with probability ~0.23 when code is correct.... A test like this probably doesn't make sense.

**Comment by ebetica** [comment]
Binomial(100, x, 0.5) > 65, since dropout is scaled by 1/p, is actually 0.00176 * 2, which is 0.352% probability.

**Comment by SsnL** [comment]
@ebetica You are right! Forgot about the scaling.
