### ISSUE TITLE
IterableDataset concrete subclasses are protocols which breaks isinstance checks

### ISSUE THREAD

**Issue by Craigacp** [pytorch/pytorch#72863]
### 🐛 Describe the bug

In pytorch 1.10 and 1.9 subclasses of `IterableDataset` get the `_is_procotol` field set to `True` by `_DataPipeMeta` (https://github.com/pytorch/pytorch/blob/v1.10.2/torch/utils/data/_typing.py#L265). In Python 3.8 this changes the behaviour of `isinstance` so that any two subclasses of `IterableDataset` are considered to be instances of each other if they have the same members. According to [PEP-544](https://www.python.org/dev/peps/pep-0544/#subtyping-relationships-with-other-types), "Protocols can never be instantiated", yet user created subtypes of `IterableDataset` can be while they have `_is_protocol=True` and I think this has messed up Python's type checking logic quite a bit.

This broke several of our tests where we were checking our dataset construction pipeline. We don't observe this behaviour in Python 3.6, only with Python 3.8 or newer (we've not tested Python 3.7).

Concretely:

```python
class A(IterableDataset):
    def some_method(self):
        print("It's A")


class B(IterableDataset):
    def some_method(self):
        print("It's B")


def test_types():
    a = A()
    b = B()

    # correct isinstance
    assert isinstance(a, A)
    assert isinstance(b, B)

    # incorrect isinstance
    assert isinstance(b, A)
    assert isinstance(a, B)
```

The last two asserts pass on Python 3.8 when they should fail, and correctly fail on Python 3.6.

### Versions

Output is from my laptop, but we observe this on Linux and with GPUs (because it's unrelated to actual computation).

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.2 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.9 (main, Nov 21 2021, 03:23:42)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.2-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.9.0

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Thanks for opening the issue. It has been resolved. You can use nightly release to by-pass it or wait for 1.11 release in the coming weeks.
Closing the issue for now, feel free to open it if such issue persists.
