### ISSUE TITLE
Issue with no_grad() doc

### ISSUE THREAD

**Issue by Helianus** [pytorch/pytorch#72921]
### 📚 The doc issue

The doc of pytorch (https://pytorch.org/docs/stable/generated/torch.no_grad.html#no-grad) shows that
x = torch.tensor([1], requires_grad=True)

but this will yield:
Traceback (most recent call last):
File "", line 1, in
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### Suggest a potential alternative/fix

The correct one should be:
x = torch.tensor([1.], requires_grad=True)

cc @brianjo @mruberry @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by ezyang** [comment]
should be easy fix, send us a pr

**Comment by Helianus** [comment]
what is a pr?

**Comment by soulitzer** [comment]
pull request :)

**Comment by soulitzer** [comment]
This has been fixed
