### ISSUE TITLE
FSDP issue on wrapping  models

### ISSUE THREAD

**Issue by HamidShojanazeri** [pytorch/pytorch#72931]
### 🐛 Describe the bug

Using FSDP from  [torch.distributed.fsdp to wrap a simple mnist model](https://gist.github.com/HamidShojanazeri/67922223f8bdd7fb9fc605694f54a430#file-gistfile1-txt-L128), when running training it [complains](https://gist.github.com/HamidShojanazeri/e67f231d535c05031da1bb3c5fd06aca) about having tensors on multiple devices. 
`
model = Net().to(rank)
model = FSDP(model)
`

Workaround suggested by @mrshenli, setting the device before wrapping works, I wonder if this is the expected behavior 

`
torch.cuda.set_device(rank)
model = Net().to(rank)
model = FSDP(model)
`

### Versions

PT-nightly-FSDP) ubuntu@ip-172-31-37-85:~/mnist_examples$ python collect_env.py
Collecting environment information...
PyTorch version: 1.12.0.dev20220215+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.27

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:53:36)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1061-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 450.142.00
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] torch==1.12.0.dev20220215+cu113
[pip3] torchaudio==0.11.0.dev20220215+cu113
[pip3] torchvision==0.13.0.dev20220215+cu113
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] torch                     1.12.0.dev20220215+cu113          pypi_0    pypi
[conda] torchaudio                0.11.0.dev20220215+cu113          pypi_0    pypi
[conda] torchvision               0.13.0.dev20220215+cu113          pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by zhaojuanmao** [comment]
this issue is not related to FSDP specifically. usually when we do data parallel distributed training using DDP or FSDP, it is good to set_deivce() or set up CUDA_VISIBLE_DEVICES, so that pytorch knows which device is the default device for the process

**Comment by rohan-varma** [comment]
@zhaojuanmao @mrshenli While we do ideally want `torch.cuda.set_device()` for all training calls, I wonder if we should see if we can support this as it is not required for DDP training.

**Comment by awgu** [comment]
I am marking this as closed because it is not directly related to FSDP.
