### ISSUE TITLE
0.4.0 careful with the inline operations like add_

### ISSUE THREAD

**Issue by antigol** [pytorch/pytorch#7294]
You should add into the [Migration Guide](https://pytorch.org/2018/04/22/0_4_0-migration-guide.html) that for instance:

```python
x = Variable(...)
x.add_(y)
x.backward()
```

changes his behavior since version 0.4.0

**Comment by colesbury** [comment]
How does this change in 0.4?

**Comment by apaszke** [comment]
The `.grad`s are None, because they are no longer tensors you created by yourself. It behaves exactly like before, except that the Variable line is now merged into `torch.tensor` (you probably wrapped them after squaring previously).
