### ISSUE TITLE
Migrate binary_smoketest.py from CircleCI -> GHA

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#72956]
We need to migrate the jobs found in https://github.com/pytorch/pytorch/blob/master/.circleci/cimodel/data/simple/binary_smoketest.py to GHA in order to complete out the migration of the binary builds.

cc @ezyang @gchanan @zou3519

**Comment by seemethere** [comment]
Marking as high priority now since we need to finish out the GHA migration sooner rather than later

**Comment by seemethere** [comment]
Re-opening since #73788 did not include macOS binary smoketests

**Comment by malfet** [comment]
Closing as https://github.com/pytorch/pytorch/pull/73949 has been landed
