### ISSUE TITLE
MacOS test jobs failing with botocore.exceptions.NoCredentialsError: Unable to locate credentials

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#72950]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
ongoing

## Error looks like
```
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```
In the Display Stats step of MacOS test jobs

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
- 2/16 8:33am incident began
- 2/16 2:07pm detected by @malfet looking at the HUD
- 2/16 2:58pm fix (#72955) submitted by @seemethere 

## User impact
*How does this affect users of PyTorch CI?*
MacOS tests all red but not their fault

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by seemethere** [comment]
How did this work before? I don't even see credentials _ever_ being included for the test portions of the macOS builds?

**Comment by seemethere** [comment]
Submitted https://github.com/pytorch/pytorch/pull/72955 to add credentials

**Comment by malfet** [comment]
Mitigated, closing

**Comment by janeyx99** [comment]
> How did this work before? I don't even see credentials _ever_ being included for the test portions of the macOS builds?

I'm confused as well. It seems as if the job only fails if test step fails, because from the HUD, the macos tests were green even before @seemethere's change.

<img width="823" alt="image" src="https://user-images.githubusercontent.com/31798555/154508021-27005e4c-8da4-40bf-8722-7d51496eada6.png">
