### ISSUE TITLE
.github/README.md is rendered as main README instead of /README.md

### ISSUE THREAD

**Issue by ben-albrecht** [pytorch/pytorch#73010]
### 🐛 Describe the bug

I am not sure when GitHub made this change, but `.github/README.md` is now rendered as the main `README.md` displayed on https://github.com/pytorch/pytorch -- I suspect that is not the desired result for the PyTorch project.

> If you put your README file in your repository's root, docs, or hidden .github directory, GitHub will recognize and automatically surface your README to repository visitors.

[[GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)]

### Versions

N/A

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ben-albrecht** [comment]
One solution to consider is moving `.github/README.md` into `.github/workflows/README.md` since it mostly describes the workflows anyway.

**Comment by seemethere** [comment]
Assigning myself

**Comment by seemethere** [comment]
Submitted https://github.com/pytorch/pytorch/pull/73023 to fix

**Comment by kit1980** [comment]
This also looks like a GitHub bug to me. Why the README.md from the subdir takes preference over README.md in the root?

**Comment by ben-albrecht** [comment]
> This also looks like a GitHub bug to me. Why the README.md from the subdir takes preference over README.md in the root?

Could be a feature as well, if a project wanted plain text README and github-specific README, for example. In either case, I can't find anything about it in their [changelog](https://github.blog/changelog/)
