### ISSUE TITLE
Windows builds are broken

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73025]
## Current Status
Mitigated

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
All binary windows builds on CI failing build due to:
```
CMake Error at C:/w/b/windows/conda/envs/py37/Library/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "C:/w/b/windows/tmp_bin/sccache-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/w/b/windows/pytorch/build/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/w/b/windows/conda/envs/py37/Scripts/ninja.exe cmTC_4b14c && [1/2] Building CXX object CMakeFiles\cmTC_4b14c.dir\testCXXCompiler.cxx.obj
    FAILED: CMakeFiles/cmTC_4b14c.dir/testCXXCompiler.cxx.obj 
    C:\w\b\windows\tmp_bin\sccache-cl.exe    -o CMakeFiles\cmTC_4b14c.dir\testCXXCompiler.cxx.obj -c C:\w\b\windows\pytorch\build\build\CMakeFiles\CMakeTmp\testCXXCompiler.cxx
    
    Unhandled Exception: System.ComponentModel.Win32Exception: The file or directory is corrupted and unreadable
       at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
       at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
       at shim.ShimProgram.Main(String[] args)
    ninja: build stopped: subcommand failed.
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:27 (project)
```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

- 2/17 7:40am new sccache introduced
- 2/17 8:17am incident began
- 2/17 10:00am detected by failures on HD
- 2/17 10:05am sccache rolled back to May 7th version, but problem not resolved
- 2/17 11:15am root caused as the sccache file not being public 🤦 
- 2/17 11:15am mitigated by making the file readable by public
- 2/17 11:15am closed by making the file readable by public

## User impact
*How does this affect users of PyTorch CI?*
CI broken when it's not their fault

## Root cause
*What was the root cause of this issue?*
the sccache file not being public 🤦 

## Mitigation
*How did we mitigate the issue?*
making the file readable by public

## Prevention/followups
*How do we prevent issues like this in the future?*
- Have a more formal process of testing and upgrading binaries in S3
- Error checking (in builder repo)
- Clearer error message, like "downloaded file is not public"  instead of the failing later on
- Test changes by changing downloadable source in curl rather then renaming files in S3 (this also helps keeping track of regressions)
- Please note, that this should not affect GHA as we (I hope) bake sccache in AMIs

**Comment by janeyx99** [comment]
Example: https://app.circleci.com/pipelines/github/pytorch/pytorch/455949/workflows/30a2db80-9df7-444d-ac88-48f47bb92765/jobs/17007345

**Comment by seemethere** [comment]
> Note: I did update the sccache binary this morning based on #72795, but i've rolled it back to the May 7th 2020 version and it is still broken

Can we add this to the timeline?

**Comment by malfet** [comment]
Well, it's `sccache-cl.exe` which could not longer be launched:
```
c:\w\b\windows\tmp_bin\sccache-cl.exe

Unhandled Exception: System.ComponentModel.Win32Exception: The file or directory is corrupted and unreadable
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at shim.CommandExecutor.execute(String process, String arguments, String working_directory, Boolean is_gui, Boolean wait_for_exit, Boolean requires_elevation)
   at shim.ShimProgram.Main(String[] args)
```

**Comment by malfet** [comment]
Ignore that, looks like file is simply not accessible:
```
 %  curl -k https://s3.amazonaws.com/ossci-windows/sccache.exe
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>DAFD9ETBR3Q5A1XE</RequestId><HostId>VmO8AxMRW/fyezjkj1CCeJbwDNXurMDokyl2AwIBRlt0FYigunhocAxRK51bIw/HEutarb2UL5U=</HostId></Error>%   
```

**Comment by suo** [comment]
It's not just circleci fwiw https://github.com/pytorch/pytorch/runs/5234408643?check_suite_focus=true

**Comment by malfet** [comment]
Fixed (hopefully)
