### ISSUE TITLE
CircleCI Windows builds are broken

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#73024]
## Current Status
*ongoing.

## Error looks like
All builds running on CircleCI would fail with:
```
CMake Error at C:/w/b/windows/conda/envs/py37/Library/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "C:/w/b/windows/tmp_bin/sccache-cl.exe"

  is not able to compile a simple test program.
```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by seemethere** [comment]
Have we updated the `sccache` binaries recently?

**Comment by malfet** [comment]
Closing in favor of #73025
