### ISSUE TITLE
CI: Remove code that differentiates between PR and trunk

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73022]
### 🚀 The feature, motivation and pitch

The recent CIFlow trigger change moves many jobs to push triggers, which breaks our functionality that separates logic dependent on whether the CI running is in PR CI or trunk CI. A lot of this functionality is confusing and not particularly useful, so we should eliminate these instances.

### Alternatives

We fix the logic by changing the ref value in the push trigger

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Closing as too low pri. If/once this becomes a burning issue again we'll file a new ticket
