### ISSUE TITLE
Windows nightly libtorch debug package in pytorch.org is out of date.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#73068]
### 🐛 Describe the bug

Downloading libtorch windows package from pytorch.org
```
Download here (Release version):
https://download.pytorch.org/libtorch/nightly/cu113/libtorch-win-shared-with-deps-latest.zip
Download here (Debug version):
https://download.pytorch.org/libtorch/nightly/cu113/libtorch-win-shared-with-deps-debug-latest.zip
```
The debug package is generated on Jan 25 while the release is Feb 17.
![image](https://user-images.githubusercontent.com/16190118/154643453-90725eab-1501-4628-8e25-22cf3b0d86e5.png)

### Versions

debug is 1.11.0dev20220125+cu113
release is 1.12.0dev20220217+cu113

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Verified that libtorch-win-shared-with-deps-debug-latest.zip was generated on Mar 6th
