### ISSUE TITLE
Warning after exporting repeat_interleave to onnx with dynamic axes

### ISSUE THREAD

**Issue by MartynaKsyta** [pytorch/pytorch#73071]
### 🐛  Bug 
Hi! I export to onnx a model with repeat_interleave and dynamic_axes. When I try to run it in onnxruntime session I get a warning and some tensors are printed:

> [10, 20] [10, 20]
> 2022-02-18 09:05:52.973973100 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of  
> N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_18'
> 2022-02-18 09:05:52.974430500 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of  
> N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_18'
> 2022-02-18 09:05:52.974665000 [W:onnxruntime:, constant_folding.cc:202 ApplyImpl] Unsupported output type of 
> N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_18'

This started to happening after I updated pytorch to the latest version.

### Minimal example
```
import numpy as np
import onnxruntime
import torch


class MyModel(torch.nn.Module):
    def forward(self, input_tensor: torch.Tensor, repeats: torch.Tensor) -> torch.Tensor:
        return torch.repeat_interleave(input_tensor, repeats, dim=0)


if __name__ == "__main__":
    model = MyModel().eval()
    data = torch.randn(10, 20)
    repeats = torch.tensor(np.arange(1, 11))
    model_path = "/tmp/model.onnx"
    torch.onnx.export(
        model,
        (data, repeats),
        model_path,
        export_params=True,
        opset_version=13,
        do_constant_folding=False,
        input_names=["input_tensor", "repeats"],
        dynamic_axes={"repeats": {0: "name"}}
    )

    ort_session = onnxruntime.InferenceSession(model_path)
    ort_inputs = {"input_tensor": data.numpy(), "repeats": np.arange(1, 11)}
    ort_session.run(None, ort_inputs)

```

### Versions

PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.2.5

Python version: 3.7.12 (default, Feb  8 2022, 05:37:08)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.10.76-linuxkit-x86_64-with-debian-11.2
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.10.2
[conda] Could not collect

**Comment by BowenBao** [comment]
Hi @MartynaKsyta , do outputs from PyTorch and ONNXRuntime match each other? If so, it would imply the model is exported correctly. If that's the case, please close this issue, and open one in https://github.com/microsoft/onnxruntime/ regarding the above warnings. Thank you.

**Comment by MartynaKsyta** [comment]
@BowenBao  Hi! Yes, they are the same. I'm created [the issue in onnxruntime repo](https://github.com/microsoft/onnxruntime/issues/10783)
