### ISSUE TITLE
github-actions pings the merger to add release note labels even after the PR has correct release note and topic labels

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#73079]
### 🐛 Describe the bug

As per the title. See https://github.com/pytorch/pytorch/pull/73014 for where this was observed

### Versions

master

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
cc @albanD

**Comment by anjali411** [comment]
closing since no one has run into this issue since this was reported.
