### ISSUE TITLE
ShardedTensor._init_from_local_shards(...) API not working correctly

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#73096]
### 🐛 Describe the bug

It seems this global size is never updated. https://fburl.com/code/a5myasf9

I think this validation doesn't make sense. We only need validation when there is redundant information.

In this API, we need to sum up all shard sizes to get global size, so global size is derived information, no redundant information is provided by API user.

Internal use case, checkpointing and load back sharded tensor. D34284271
Attemptive fix in D34284271 as well.

Code to trigger this bug
```
# Have 2 processes/threads running this function

def rank_build_sharded_tensor(rank: int) -> None:
    shard_tensor = torch.randint(
        low=0,
        high=10,
        size=(1, 4),
    )
    sharding_dim = 0
    sharding_spec = ChunkShardingSpec(
        dim=sharding_dim,
        placements=[
            "rank:0/cpu",
            "rank:1/cpu",
        ],
    )
    shard_offsets = [rank, 0]
    shard_sizes = list(shard_tensor.size())
    shard_metadata = ShardMetadata(
        shard_offsets=shard_offsets,
        shard_sizes=shard_sizes,
        placement=sharding_spec.placements[rank],
    )
    local_shards = [
        sharded_tensor.Shard(
            tensor=shard_tensor,
            metadata=shard_metadata,
        )
    ]
    sharded_tensor = ShardedTensor._init_from_local_shards(
        local_shards,
        (2, 4),
    )
```

### Versions

master branch

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by cbalioglu** [comment]
cc @wanchaol

**Comment by wanchaol** [comment]
@xush6528 The reason why we pass this global_size is that we would like to ensure user creating the tensor in a shape that they are expecting when using this API(ccing @pritamdamania as we had this discussion before). 

I agree with you that we can derive the global_size information from all the local shards metadata, but there might potentially be some cases where the local shards from all ranks form a ShardedTensor, but it's not the same shape as what the user expecting to create (i.e. the local shards are smaller than what user are expecting). By passing in a `global_size` from user, we can detect such an issue.

**Comment by xush6528** [comment]
@wanchaol 
Even we want to do the validation, the number passed here is not corrected. It's always the size of first shard today.

**Comment by pritamdamania87** [comment]
> Even we want to do the validation, the number passed here is not correct. It's always the size of first shard today.

@xush6528 Could you share a code pointer in terms of which number you are referring to here?

**Comment by xush6528** [comment]
@pritamdamania87 

https://github.com/pytorch/pytorch/blob/8c505bbc8622887b4c4a80e62d96c92fab8cb72d/torch/distributed/_shard/sharded_tensor/utils.py#L237

`global_sharded_tensor_metadata.size` is never updated after first assignment.

**Comment by wanchaol** [comment]
> @pritamdamania87
> 
> https://github.com/pytorch/pytorch/blob/8c505bbc8622887b4c4a80e62d96c92fab8cb72d/torch/distributed/_shard/sharded_tensor/utils.py#L237
> 
> `global_sharded_tensor_metadata.size` is never updated after first assignment.

Hmmm I think it's not the first shard size, if you look at the code here https://github.com/pytorch/pytorch/blob/8c505bbc8622887b4c4a80e62d96c92fab8cb72d/torch/distributed/_shard/sharded_tensor/utils.py#L187

When we initialize from local shards, we first build a local `ShardedTensorMetadata`, and the local `ShardedTensorMetadata.size` is actually being initialized to the `global_size` variable that passed in `build_metadata_from_local_shards`, so it's actually each rank initialize them as the user passed global_size, when we call `build_global_metadata`, we simply do the check and validate all ranks ShardedTensorMetadata have the same `size` https://github.com/pytorch/pytorch/blob/8c505bbc8622887b4c4a80e62d96c92fab8cb72d/torch/distributed/_shard/sharded_tensor/utils.py#L205

**Comment by xush6528** [comment]
Thanks for correcting. I attribute to the wrong place.

It turned out the issue is here
https://github.com/pytorch/pytorch/blob/8c505bbc8622887b4c4a80e62d96c92fab8cb72d/torch/distributed/_shard/sharded_tensor/utils.py#L202

With a shallow copy and using the example above I gave.
The error is like
```
    1) ValueError: Shards ShardMetadata(shard_offsets=[1, 0], shard_sizes=[1, 4], placement=rank:1/cpu) and ShardMetadata(shard_offsets=[1, 0], shard_sizes=[1, 4], placement=rank:1/cpu) overlap
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 256, in test_tensor
        lwt_spawn(
      File "caffe2/torch/fb/lwt/spawn.py", line 129, in lwt_spawn
        sched.spawn(
      File "caffe2/torch/fb/lwt/scheduler.py", line 167, in spawn
        self._context_switch()
      File "caffe2/torch/fb/lwt/scheduler.py", line 250, in _context_switch
        next.gr.switch()
      File "caffe2/torch/fb/lwt/scheduler.py", line 56, in _trampoline
        func(*args, **kwargs)
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 182, in _rank_save_load
        component_to_save = component_factory(rank)
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 168, in _tensor_component_factory
        return FakeTensorComponent(rank=rank)
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 127, in __init__
        sharded_t = sharded_tensor.ShardedTensor._init_from_local_shards(
      File "torch/distributed/_shard/sharded_tensor/api.py", line 352, in _init_from_local_shards
        global_sharded_tensor_metadata = build_global_metadata(gathered_metadatas)
      File "torch/distributed/_shard/sharded_tensor/utils.py", line 236, in build_global_metadata
        validate_non_overlapping_shards_metadata(global_sharded_tensor_metadata.shards_metadata)
      File "torch/distributed/_shard/sharding_spec/_internals.py", line 80, in validate_non_overlapping_shards_metadata
        raise ValueError(f'Shards {shards[i]} and {shards[j]} overlap')
```

It's fixed if we change to
```
global_sharded_tensor_metadata = copy.deepcopy(rank_metadata)
```

**Comment by xush6528** [comment]
@wanchaol 
Thanks for correcting. I attributed to the wrong place.

It turned out the issue is here
https://github.com/pytorch/pytorch/blob/8c505bbc8622887b4c4a80e62d96c92fab8cb72d/torch/distributed/_shard/sharded_tensor/utils.py#L202

With a shallow copy and using the example above I gave.
The error is like
```
    1) ValueError: Shards ShardMetadata(shard_offsets=[1, 0], shard_sizes=[1, 4], placement=rank:1/cpu) and ShardMetadata(shard_offsets=[1, 0], shard_sizes=[1, 4], placement=rank:1/cpu) overlap
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 256, in test_tensor
        lwt_spawn(
      File "caffe2/torch/fb/lwt/spawn.py", line 129, in lwt_spawn
        sched.spawn(
      File "caffe2/torch/fb/lwt/scheduler.py", line 167, in spawn
        self._context_switch()
      File "caffe2/torch/fb/lwt/scheduler.py", line 250, in _context_switch
        next.gr.switch()
      File "caffe2/torch/fb/lwt/scheduler.py", line 56, in _trampoline
        func(*args, **kwargs)
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 182, in _rank_save_load
        component_to_save = component_factory(rank)
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 168, in _tensor_component_factory
        return FakeTensorComponent(rank=rank)
      File "aiplatform/modelstore/client/tests/stateful_component_checkpoint_agent_test.py", line 127, in __init__
        sharded_t = sharded_tensor.ShardedTensor._init_from_local_shards(
      File "torch/distributed/_shard/sharded_tensor/api.py", line 352, in _init_from_local_shards
        global_sharded_tensor_metadata = build_global_metadata(gathered_metadatas)
      File "torch/distributed/_shard/sharded_tensor/utils.py", line 236, in build_global_metadata
        validate_non_overlapping_shards_metadata(global_sharded_tensor_metadata.shards_metadata)
      File "torch/distributed/_shard/sharding_spec/_internals.py", line 80, in validate_non_overlapping_shards_metadata
        raise ValueError(f'Shards {shards[i]} and {shards[j]} overlap')
```

It can be fixed if we change to
```
global_sharded_tensor_metadata = copy.deepcopy(rank_metadata)
```

**Comment by wanchaol** [comment]
> 

I see, yeah interesting this shallow copy triggers the trouble, each process should have its own copy, is it because we are using multiple threads?

Either way, feel free to fix it along with your other changes, or I can help fixing it for you ;)
