### ISSUE TITLE
[BUG/Feature request] Missing documentation of torch.jit ?

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/pytorch#7309]
I wonder whether it is OK that there is no API documentation on [torch.jit](https://github.com/pytorch/pytorch/blob/master/torch/jit/__init__.py) on the official [site](https://pytorch.org/docs/stable/index.html)

PS. Sorry if missed something explaining this...

**Comment by soumith** [comment]
it's intentional. we'll add docs when it's ready to use.
