### ISSUE TITLE
[FSDP Checkpoint] Padding helper

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#73117]
### 🚀 The feature, motivation and pitch

See discussion in https://github.com/pytorch/pytorch/pull/72469#discussion_r810128308

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
I want to abstract out the FSDP sharding algorithm, which would be a superset of this issue. This is to enable plugging a different sharding algorithm (such as the one supporting the convex shape constraint). This can be done by adding more hooks to `FSDPExtensions`.
