### ISSUE TITLE
Should we remove `aten::_s_where` and make `aten::where` a primitive?

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#73135]
### 🚀 The feature, motivation and pitch

I think `aten::where` has more clear semantics than `aten::_s_where`, and as a result, most compilers support `aten::where` and not `aten::_s_where`.

Should we remove `aten::_s_where` in favor of `aten::where` as our more primitive operator?

I'm not super certain about this, but we should probably figure out some desiderata for our "primitive" operator set (should it be a subset of our "public" operators?).

@gchanan

**Comment by ngimel** [comment]
Is the only difference that `where` handles broadcast, and `_s_where` nominally doesn't? (Nominally, because it still calls TI that would handle broadcast). If so, yes, looks like we don't need _s_where.

**Comment by Chillee** [comment]
@ngimel yeah, afaict. @gchanan mentioned that it was done at some point when we were trying to make broadcasts implicit.

Which honestly doesn’t seem like a bad idea in principle… but it doesn’t seem like it’s happening now.

**Comment by ngimel** [comment]
Yeah, now all this is done in autograd engine with `sum_to` (which may be not the best idea, but all in due time)

**Comment by gchanan** [comment]
> Yeah, now all this is done in autograd engine with sum_to (which may be not the best idea, but all in due time)

Yeah, people didn't want to write derivative formulas that had to handle broadcasting, thus the original split, and the situation now where they only nominally don't handle broadcasting.

**Comment by mikeiovine** [comment]
Looks like the plan for this has not been decided but FYI I want to add an out variant for `_s_where` here: https://github.com/pytorch/pytorch/pull/73438

Having `_s_where_out` would be useful for static runtime and a few fb-only ops that I'm working on. If there are plans to remove `_s_where`, let me know, I would be happy to re-work the linked PR (we could just add `where_out`)
