### ISSUE TITLE
[shard] init_from_local_tensor API improvement

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#73133]
### 🚀 The feature, motivation and pitch

 is it required to pass a tensor to init_from_local_shard API on every rank? Example: we have four ranks, global tensor size [20, 5], ChunkShardingSpec(dim=1), we will have three chunks: [2, 2, 1, 0], the last rank have 0 (no tensor), what do you think the right behavior should be there?

I guess we have two options: 1. we make init_from_local_tensor to have local_tensor:Optional[Tensor] instead of local_tensor: Tensor, this means we accept None in some ranks if the spec said so 2. we don't allow such kind of sharding spec and explicitly error to user that the sharding spec is not legit because user pass in a tensor but the sharding spec says no tensor on this rank

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
