### ISSUE TITLE
autocast_mode.py causes a user warning on macOS

### ISSUE THREAD

**Issue by DP1701** [pytorch/pytorch#73140]
### 🐛 Describe the bug

I was training a small model with YOLOv5. During the training, the following warning appeared every time: 

```
.../lib/python3.9/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
```
I have specified the device type CPU during training.
Is there any way to turn off this warning?

On another macOS system I have installed Torch 1.9 and this warning does not appear there.

### Versions

- torch  1.10.2
- torchvision 0.11.3

**Comment by VitalyFedyunin** [comment]
Hello! Do you have minimal reproducible example for this problem.

**Comment by DP1701** [comment]
This error can be reproduced with YOLOv5 using the train command. 

´´´
python train.py --img 640 --batch 16 --epochs 3 --data coco128.yaml --weights yolov5s.pt
´´´

To test the command, you can find the record here:
[kaggle-coco128](https://www.kaggle.com/ultralytics/coco128)
