### ISSUE TITLE
I found a BUG in Pytorch 1.10.*, please help me to deal with this.

### ISSUE THREAD

**Issue by wudejian789** [pytorch/pytorch#73152]
I think I found a BUG in Pytroch 1.10.*. I update the Pytorch from 1.10.0 to 1.10.2, while the BUG still exists. 

![image](https://user-images.githubusercontent.com/33439004/154835505-19a58ba2-5087-4665-82ee-b4bf8ce7ef7b.png)
My test code is in this figure. I just compute the attention score in a self-attention module. And I output the variable scores 's shape and values. To show simpler, I sum up the dimensions of scores except the BATCH_SIZE dimension. I gave some same input to it with different BATCH_SIZE. Therefore, normally, the outputs for the inputs should be the same, espectially the "scores[0].sum(dim=-1).sum(dim=-1).sum(dim=-1)" (defined as A) and the "scores.sum(dim=-1).sum(dim=-1).sum(dim=-1)[0]" (defined as B) and the first element of the "scores.sum(dim=-1).sum(dim=-1).sum(dim=-1)" (defined as C).

But I got the outputs like the following figures. It shows that for BATCH_SIZE=1, the outputs of A,B,C are -1521.6455, -1521.6455, -1521.6455; for BATCH_SIZE=2, the outputs are -1521.6455, -1521.6460, -1521.6460;  for BATCH_SIZE=16, the outputs are -1521.6455, -1521.6460, -1521.6460. Why does the output not consistant, sometimes is *.6455, while sometimes is *.6460. I also tried to change the model to CPU device, but the differences still existed. 

![8G%RN648~S~137@QGT}`OUX](https://user-images.githubusercontent.com/33439004/154835485-183676d4-1f03-4cbd-a59d-b5775135a21f.png)

Please if someone or developler could find this, please explain the reason for me. My e-mail is wuyifan@csu.edu.cn. Thanks very much for your replaying.

**Comment by ngimel** [comment]
This is expected behavior, not a bug https://pytorch.org/docs/master/notes/numerical_accuracy.html

**Comment by wudejian789** [comment]
> This is expected behavior, not a bug https://pytorch.org/docs/master/notes/numerical_accuracy.html

Thank you for your replaying! I have used Pytorch so many years but I still didn't know this. WHAT AN AMAZING THING!
