### ISSUE TITLE
Bug in Dataloader

### ISSUE THREAD

**Issue by Sentient07** [pytorch/pytorch#73153]
### 🐛 Describe the bug

I face a stochastic bug with the Dataloader. The traceback is as shown below. The error was observed at Epoch 18 of my training. I resumed my training again without changing anything and it went without an error until epoch 30. I am unable to explain better about the error as it does not point out anything with my code. The third time, I could go until epoch 100. 

```
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 319, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1626851217217/work/aten/src/ATen/MapAllocator.cpp":243, please report a bug to PyTorch. unable to open shared memory object </torch_3348965_1934759801> in read-write mode
```

My Dataset class is quite simple as show here : https://bpa.st/7ZKPPZLTRIKM2G655EOXSIM7YY. Following the suggestions made in [this thread](https://github.com/pytorch/pytorch/issues/11201#issuecomment-895047235), I'm setting the `worker_init_fn` accordingly.

### Versions

Collecting environment information...
PyTorch version: 1.10.0.dev20210721
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-99-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] neuralnet-pytorch==0.0.3
[pip3] numpy==1.20.0
[pip3] numpy-stl==2.16.0
[pip3] pytorch-lightning==1.2.8
[pip3] pytorch-lightning-bolts==0.3.2.post1
[pip3] pytorch-metric-learning==0.9.99
[pip3] siren-pytorch==0.1.5
[pip3] torch==1.10.0.dev20210721
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.7.2
[pip3] torch-points-kernels==0.6.10
[pip3] torch-points3d==1.3.0
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.10
[pip3] torch-tb-profiler==0.3.1
[pip3] torchaudio==0.10.0a0+16c6033
[pip3] torchfile==0.1.0
[pip3] torchmeta==1.4.0
[pip3] torchmetrics==0.7.0
[pip3] torchnet==0.0.4
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.7.0
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] libblas                   3.9.0            11_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            11_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            11_linux64_mkl    conda-forge
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] pytorch                   1.10.0.dev20210721 py3.8_cuda11.1_cudnn8.0.5_0    pytorch-nightly
[conda] pytorch-metric-learning   0.9.99                   pypi_0    pypi
[conda] siren-pytorch             0.1.5                    pypi_0    pypi
[conda] torch-cluster             1.5.9                    pypi_0    pypi
[conda] torch-geometric           1.7.2                    pypi_0    pypi
[conda] torch-points-kernels      0.6.10                   pypi_0    pypi
[conda] torch-points3d            1.3.0                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.10                   pypi_0    pypi
[conda] torch-tb-profiler         0.3.1                    pypi_0    pypi
[conda] torchaudio                0.10.0.dev20210721            py38    pytorch-nightly
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchmeta                 1.4.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @VitalyFedyunin @SsnL @ejguan @NivekT

**Comment by Sentient07** [comment]
Following up, this again happened at epoch 32 (training with different hparam)

```
  File "training/train_MapNet.py", line 30, in <module>
    trainer.train_epoch()
  File "/mnt/disk1/user/Project_Torch/training/map_trainer.py", line 187, in train_epoch
    for inp in iterator:
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/user/.conda/envs/torch1p9/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 305, in rebuild_storage_filename
    storage = cls._new_shared_filename(manager, handle, size)
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1626851217217/work/aten/src/ATen/MapAllocator.cpp":303, please report a bug to PyTorch. unable to mmap 192 bytes from file </torch_1703276_2075601193>: Cannot allocate memory (12)

```

**Comment by vadimkantorov** [comment]
sometimes errors like this can happen if training is done in docker container with too little shared memory size...

**Comment by Sentient07** [comment]
@vadimkantorov No, I'm not using docker.

**Comment by Sentient07** [comment]
I figured what's wrong. calling this `get_FPS` from `__getitem__` causes the bug. When I don't call, 5 runs have been successful with no issue. 

```
def calc_distances(p0, points):
    return ((p0 - points)**2).sum(axis=1)


def get_FPS(pts, K):
    """
    Farthest point sampling alongside indices
    """
    farthest_pts = np.zeros((K, 3))
    init_random = np.random.randint(len(pts))
    farthest_pts[0] = pts[init_random]
    distances = calc_distances(farthest_pts[0], pts)
    pt_indices = [init_random]
    for i in range(1, K):
        arg_max_ind = np.argmax(distances)
        farthest_pts[i] = pts[arg_max_ind]
        pt_indices.append(arg_max_ind)
        distances = np.minimum(distances, calc_distances(farthest_pts[i], pts))
    return farthest_pts, pt_indices
```

**Comment by veer5551** [comment]
Even I am facing a similar issue which might be related to dataloader and workers not exiting gracefully (locked in?)
https://github.com/facebookresearch/detectron2/issues/3953

Any thoughts on this?

Thanks!

**Comment by vadimkantorov** [comment]
(even outside of docker context, it might be good to check at `df -h` output to double-check that tmpfs/ramfs has enought space)

**Comment by Sentient07** [comment]
Hello, if I understand right, there seems to be sufficient memory (see below). I think the traceback is not helpful to say where the error arises from. However, the origin of the error is when I call `get_FPS` from within `__getitem__` _and_ set workers>0. When workers=0 and I call the above method, there is no error. Or, when workers>0 and I do not call `get_FPS`, the code still works fine. I hope this helps

```
Filesystem                         Size  Used Avail Use% Mounted on
udev                               252G     0  252G   0% /dev
tmpfs                               51G  4.2M   51G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  5.0T  1.3T  3.6T  27% /
tmpfs                              252G  144K  252G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              252G     0  252G   0% /sys/fs/cgroup
/dev/nvme0n1p2                     976M  305M  605M  34% /boot
/dev/nvme0n1p1                     511M  5.3M  506M   2% /boot/efi
/dev/sdb1                           11T   64M   11T   1% /mnt/disk2
/dev/loop0                          56M   56M     0 100% /snap/core18/2253
/dev/loop1                          62M   62M     0 100% /snap/core20/1328
/dev/sda1                           11T  5.2T  5.0T  52% /mnt/disk1
/dev/loop3                          62M   62M     0 100% /snap/core20/1270
/dev/loop2                          68M   68M     0 100% /snap/lxd/21835
/dev/loop5                          56M   56M     0 100% /snap/core18/2284
/dev/loop7                          68M   68M     0 100% /snap/lxd/21803
tmpfs                               51G  4.0K   51G   1% /run/user/1004
tmpfs                               51G     0   51G   0% /run/user/1003
tmpfs                               51G  4.0K   51G   1% /run/user/1011
/dev/loop8                          44M   44M     0 100% /snap/snapd/14978
tmpfs                               51G  4.0K   51G   1% /run/user/1005
```

**Comment by VitalyFedyunin** [comment]
Can you please try latest nightly build of pytorch, it have some additional error handling for memory sharing, which will help to identify the issue.

**Comment by Sentient07** [comment]
Hello @VitalyFedyunin I am sorry I wouldn't be able to try before the end of this week as I work on a different branch and I'm afraid re-installing pytorch might be detrimental for other work. If that blocks you with the progress of this issue, can you please try with the code I've shared ( my data loader : https://bpa.st/43SA ) and associated dataset (https://nuage.lix.polytechnique.fr/index.php/s/QpiTJoPLdwGZ96M) ? Thanks !

**Comment by VitalyFedyunin** [comment]
Hi! You can also try with PyTorch 1.11 it has some related fixes. I will close this issue for now, but feel free to reopen if you have new stack traces.

**Comment by ZhiyuanChen** [comment]
@VitalyFedyunin could you please reopen this issue? I can confirm it's still presist in 1.13.0.
