### ISSUE TITLE
Got error about invalid header or archive is corrupted

### ISSUE THREAD

**Issue by TianhangWang** [pytorch/pytorch#73168]
### 🐛 Describe the bug

Hi, I am using the version of `1.7.1+cu110` pytorch under Ubuntu 20.04 with RTX 3090 24G. I used `DDP` to train my model by two GPUs in single machine. I saved my model's weights by `torch.save`. Then I want to test my model on single GPU. Then it throw out following problems

Traceback (most recent call last):
  File "/home/test1/WiseComm/test_codet.py", line 357, in <module>
    main(args)
  File "/home/test1/WiseComm/test_codet.py", line 185, in main
    checkpoint = torch.load(args.resume)
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/94924775021872: invalid header or archive is corrupted

So, I read about some materials, maybe this model file is broken I thought. Then I choose another model I have kept. Then it throw out following problems

Traceback (most recent call last):
  File "/home/test1/WiseComm/test_codet.py", line 357, in <module>
    main(args)
  File "/home/test1/WiseComm/test_codet.py", line 185, in main
    checkpoint = torch.load(args.resume)
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/usr/local/anaconda3/envs/test_1/lib/python3.9/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:222] . file not found: archive/data/93917455579808

Could you tell me how to fix this problem?

### Versions

PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-43-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.63.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.7.1+cu110
[pip3] torchgeometry==0.1.2
[pip3] torchvision==0.8.2+cu110
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2021.4.0           h06a4308_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py39h7f8727e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.2            py39h51133e4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] torch                     1.7.1+cu110              pypi_0    pypi
[conda] torchgeometry             0.1.2                    pypi_0    pypi
[conda] torchvision               0.8.2+cu110              pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @mruberry

**Comment by TianhangWang** [comment]
I can only train on single GPU and test on single GPU, it is no problem. So can you tell how to train on 2-GPUs by DDP and test on single GPU.

**Comment by TianhangWang** [comment]
Here is how I use DDP:

First set environment
```
rank = int(os.environ["RANK"])
local_rank = int(os.environ["LOCAL_RANK"])
torch.cuda.set_device(rank % torch.cuda.device_count())
dist.init_process_group(backend='nccl')
device = torch.device("cuda", local_rank)
```
then  set dataset 

```
trainset = V2XSIMDataset(dataset_roots=[f'{args.data}/agent{i}' for i in range(5)], config=config, config_global=config_global, split='train')
train_sampler = torch.utils.data.distributed.DistributedSampler(trainset, shuffle=True)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, sampler=train_sampler)
```
Then for model
```
model = model.to(device)
model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank], output_device=local_rank, find_unused_parameters=True)
teacher = teacher.to(device)
teacher = torch.nn.parallel.DistributedDataParallel(teacher, device_ids=[local_rank], output_device=local_rank, find_unused_parameters=True)
fafmodule = FaFModule(model, teacher, config, optimizer, criterion, args.kd_flag)
```
Finally, save the model
```
save_dict = {'epoch': epoch,
  'model_state_dict': fafmodule.model.state_dict(),
  'optimizer_state_dict': fafmodule.optimizer.state_dict(),
  'scheduler_state_dict': fafmodule.scheduler.state_dict(),
  'loss': running_loss_disp.avg}
torch.save(save_dict, os.path.join(model_save_path, 'epoch_' + str(epoch) + '.pth'))
```

**Comment by pritamdamania87** [comment]
@TianhangWang Not sure if this might be an issue with serialization/ddp. Can you share a simple self-contained repro script with DDP, torch.save and torch.load so that we can narrow down the issue?

**Comment by TianhangWang** [comment]
> @TianhangWang Not sure if this might be an issue with serialization/ddp. Can you share a simple self-contained repro script with DDP, torch.save and torch.load so that we can narrow down the issue?

Thank you for your advise, I create a simple repro which contains train adn test file, please check [repro](https://github.com/TianhangWang/debug-pytorch-ddp) for more details.

**Comment by newera-001** [comment]
I met same problem as you. And the env is also similar with you excepting the GPU. Did you change or switch your gcc version(9.4.0 to 9.3.0)? A few days ago, My ubuntu , 20.04.3 LTS x86_64 , update the kernel  then the gcc version from 9.3.0 update to 9.4.0. So now this problem happened!

**Comment by cutecutecat** [comment]
I have met a same problem and finally fix it!

**Do not save checkpoints at more than one agent**, or they may write to same file in any sequence, then the file may be broken by all the process.

Change to something like this:
```Python
if not use_ddp or dist.get_rank() == 0:
        logger.info("begin save checkpoint")
        save_checkpoint(...)
if use_ddp:
        dist.barrier()
```

**Comment by TianhangWang** [comment]
@cutecutecat Thanks for your reply! I have been waiting for long time. I will try the method you mentioned about. Anyway, thank you!
