### ISSUE TITLE
`CrossEntropyLoss` triggers floating point exception

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#73165]
### 🐛 Describe the bug

`CrossEntropyLoss` triggers floating point exception

```python
import torch
results = dict()
input_1 = torch.rand([5, 0], dtype=torch.float32)
input_2 = torch.rand([5, 0], dtype=torch.float32)

torch.nn.CrossEntropyLoss()(input_1, input_2)
# floating point exception
```

### Versions

pytorch: 1.10.1

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by TestSomething22** [comment]
Any update?

**Comment by albanD** [comment]
Hi,

We would be happy to accept a fix that avoid the floating point exception here.

**Comment by mikeb127** [comment]
As a possible hint from a brief look......Look at the if statement in line 485 of file pytorch/aten/src/ATen/native/LossNLL.cpp

Both 'Sum' and 'None' reduction work fine, so consider lines 494 and 505.

I want to finish my other PR first, but when I am done with it I will take this one as well if no-one has picked it up by then

**Comment by mikeb127** [comment]
Actually, I've fixed now. Will create PR

**Comment by mikeb127** [comment]
@TestSomething22 @albanD what would the preferred outcome be here? It's a divide by zero exception so what do we want returned? A NaN value? A torch error?

**Comment by jbschlosser** [comment]
@mikeb127 Should quietly return a NaN value when `numel() == 0` for a mean reduction to match here:
https://github.com/pytorch/pytorch/blob/f8c1acea1e78573c04cd18893c4abff9eea64b03/aten/src/ATen/native/LossNLL.cpp#L185-L196
