### ISSUE TITLE
PyTorch Profiler Problem: Can not load GPU kernal!!!!

### ISSUE THREAD

**Issue by Arsmart123** [pytorch/pytorch#73199]
### 🚀 The feature, motivation and pitch

I am using the latest [PyTorch Profiler], and I want to show my GPU kernal situation. 
I am using Geforce 1650 with CUDA11.3, CUDNN, also installed torch-gpu, tensorflow-gpu. 
but my torch version is 1.10! Is this a problem? 
So in the tutorial, the supposed result should have a GPU kernal option, like below:
![image](https://user-images.githubusercontent.com/65449458/155058997-1cb24702-6b86-41d2-a376-1b1243d0f8d1.png)
But my result is like:
![image](https://user-images.githubusercontent.com/65449458/155059057-49806bbd-0433-4b76-b90f-ee3e59829c74.png)
Anyone could help me? Thank you!!!

**Comment by Arsmart123** [comment]
Seems it can not recognize my Geforce 1650? Maybe ok for larger GPU like Tesla?

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.

**Comment by mrgeorge** [comment]
Hi @VitalyFedyunin , thanks for the pointer. This topic was raised a while ago there https://discuss.pytorch.org/t/can-pytorch-profiler-add-s3-support/117397
and the feedback was to create an issue on Github, but I didn't see any related issues created.
