### ISSUE TITLE
Enable use of Pytorch codegen from external libraries

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#73212]
### 🚀 The feature, motivation and pitch

External libraries that have C++ extensions that provide new per-operator functionality will find it helpful to use PyTorch's codegen model that parses native_functions.yaml and has common routines for things like determining if an operation is in-place or if something is being aliased. In particular, in functorch, we really wish we had access to PyTorch's codegen model.

We should offer a way for external libraries to call PyTorch's codegen API to make their lives easier.

### Alternatives

Brainstorming with @bdhirsh offered the following ideas:
- functorch (or an external library) can clone PyTorch as a part of its build workflow. This is not ideal due to needing the additional step
- Copy-paste the codegen library into functorch. Also not ideal because the codegen can go out-of-sync.
- Provide a pytorch-codegen package
- Provide a torch.codegen module

cc @ezyang @bhosmer @bdhirsh

**Comment by bdhirsh** [comment]
One thing @zou3519 and I agreed is worth thinking about is how to deal with (or at least properly advertise) lack of BC. If an out-of-tree codebase like functorch wants to use codegen utilities, we probably can't make any promises that the utilities will be stable API's.

**Comment by ezyang** [comment]
No BC guarantees, but I feel comfortable making it available. Will be helpful to have unified CI so when we refactor I can fix functorch's code.

BTW, functorch may also consider putting their codegen in pytorch/pytorch, if it is relatively stable; that's what we did for XLA and it works ok.

**Comment by zou3519** [comment]
Our options right now so far seem to be:
- kick tools/codegen (including native_functions.yaml!) into a `torch.utils._codegen` package
- figure out how to package tools/codegen into its own pip installable
- move functorch codegen into pytorch/pytorch

I'm not comfortable with moving functorch codegen into pytorch/pytorch because I want to be able to refactor it with less than 1 day (i.e. waiting for the pytorch nightly to update) turnaround.

Setting up packaging also doesn't seem like fun, so, the easiest way to do this is probably to kick tools/codegen (including native_functions.yaml!) into a `torch.utils._codegen` folder. This might be a little painful in terms of needing to update PyTorch's build system though

**Comment by zou3519** [comment]
Offline discussion with @ezyang and co said:
- We're calling the codegen module `torchgen` (this is still bikeshed-able)
- This will live in a top-level torchgen/ folder in the PyTorch repo.
- We will distribute torchgen/ with the pytorch binaries (so out-of-tree package maintainers don't need to figure out which version of torchgen to pair with which version of PyTorch).
