### ISSUE TITLE
ATen: How to get cusparseHandle_t handle?

### ISSUE THREAD

**Issue by Daulbaev** [pytorch/pytorch#7325]
I'm trying to call function from <cusparse.h> inside ATen and don't know how to get cusparseHandle_t handle. Could you help me?

I see a relevant function in THCS, but it depends on THCState *state, and I don't know how to get it too.

**Comment by apaszke** [comment]
Once you have an ATen context object, you can just call `lazyInitCUDA()` and get a `THCState*`. Then, you can pass that into the THCS functions.

Also, please remember that we're using GitHub issues for bug reports only, and all questions should be posted on [our forums](https://discuss.pytorch.org).
