### ISSUE TITLE
[ONNX] Exporting Cast operation with wrong input types

### ISSUE THREAD

**Issue by franchenstein** [pytorch/pytorch#7326]
## Issue description

I am trying to export a PyTorch model to ONNX which contains the Cast operation. When I try to run the ONNX checker on the exported model, I get an error on the cast function:

```
ValidationError: Attribute 'to' is expected to have field 's'

==> Context: Bad node spec: input: "14" output: "15" op_type: "Cast" attribute { name: "to" i: 7 type: INT } 

```

Apparently, the export is using the enum number for the operation instead of its string, which is what the checker expects.

## System Info
PyTorch version: 0.5.0a0+21e0fc8
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: version 3.11.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@franchenstein - 0.5 is an old version and there have been several updates to PyTorch-ONNX exporter since then. I would suggest that you use the latest version of PyTorch to try the export again. If you run into any issues, please provide a clear repro with model and export code.

**Comment by garymm** [comment]
Closing since there's been no reply in several months. @franchenstein please open a new issue with clear repro instructions if this is still a problem with the latest nightly pytorch.
