### ISSUE TITLE
torch.where does not handle scalar type correctly

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#73298]
### 🐛 Describe the bug

The following code:
```python
import torch

ab = torch.zeros(5, dtype=torch.bool)
af = torch.zeros(5, dtype=torch.float)
ad = torch.zeros(5, dtype=torch.double)

# This fail as expected
torch.where(ab, af, ad)  # RuntimeError: expected scalar type float but found double

# This works as expected
torch.where(ab, ad, 3.0)

# WTF are you doing!
torch.where(ab, af, 3.0)  # RuntimeError: expected scalar type float but found double
```
I am expecting `torch.where(ab, af, 3.0)` to work fine, because PyTorch only support double scalar, not float scalar. It does not make any sense to require the user to pass a float scalar as argument.

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0a0+gitec8d677
Is debug build: True
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.22.2
Libc version: glibc-2.35

Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.16.9-arch1-1-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.55
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 510.54
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.1
/usr/lib/libcudnn_adv_infer.so.8.3.1
/usr/lib/libcudnn_adv_train.so.8.3.1
/usr/lib/libcudnn_cnn_infer.so.8.3.1
/usr/lib/libcudnn_cnn_train.so.8.3.1
/usr/lib/libcudnn_ops_infer.so.8.3.1
/usr/lib/libcudnn_ops_train.so.8.3.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.12.0a0+gitec8d677
[pip3] torch-ucc==1.0.0
[pip3] torchani==2.2
[conda] Could not collect
```

cc @nairbv @mruberry

**Comment by george-qi** [comment]
Perhaps I'm missing something, but as you point out, `af` has dtype float whereas 3.0 has dtype double. `torch.where` requires `self` and `other` to have the same dtype or else it will return the RuntimeError that you've encountered, so this seems consistent (i.e. it has the same error message as `torch.where(ab, af, ad)`)?

**Comment by zasdfgbnm** [comment]
@george-qi I would argue that scalar-tensor vs scalar are two different things and needs to be handled differently. Scalar-tensor is something that the user specifies its dtype, so the scalar-tensor should not be different from other tensors. In the above example, if the user did
```python
torch.where(ab, af, torch.tensor(3.0, dtype=torch.double))
```
I have no problem seeing an error. but 
```python
torch.where(ab, af, 3.0)
```
should be a different story, because the user specifies a scalar instead of a scalar-tensor.

For the case of scalar, the user has no way to specify its type. For example, when I write `3.0` in Python, I have no choice whether this should be a float or double because the dtype is totally determined by Python. In such case, PyTorch should take this into consideration.

An example that I think PyTorch handles well is:
```python
>>> (torch.zeros((), dtype=torch.float) + 3.0).dtype
torch.float32
>>> (torch.zeros((), dtype=torch.float) + torch.zeros((), dtype=torch.double)).dtype
torch.float64
```
And I think `torch.where` should be as smart as `torch.add`.

**Comment by kshitij12345** [comment]
https://github.com/pytorch/pytorch/pull/62084 should take care of this.
