### ISSUE TITLE
[JIT] Removing a `print` statement causes `RuntimeError: split_with_sizes expects split_sizes to sum exactly`

### ISSUE THREAD

**Issue by randolf-scholz** [pytorch/pytorch#73291]
### 🐛 Describe the bug

The bug occurs when passing a slice of shape `(0, dim)`. Oddly enough, the bug can be avoided by inserting a `print` statement, which made finding/debugging this quite weird.

NOTE: Below is a maximally reduces MWE. You may ask why care about 0xD inputs. In my use-case, I have multiple inputs which are observation of a time-series within a time-slice. Sometimes there are no observations in a slice and so a tensor with a 0-size axis is passed. The code works fine without JIT.

```python
import torch
from torch import Tensor, jit, nn

class MWE(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(2 * input_size, output_size)

    def forward(self, x: Tensor) -> Tensor:
        r"""[..., input_size] -> [..., output_size]"""
        z = torch.cat([x, x], dim=-1)
        # print("")  # FIXME: Commenting this line causes RunTimeError
        return self.linear(z)

xdim, ydim = 7, 10
device = torch.device('cuda')  # bug happens both on CPU and GPU
model = jit.script(MWE(xdim, ydim)).to(device=device)  # bug only occurs with JIT

for k in range(100):
    num_observations = torch.randint(0, 3, (1,)).item()
    sample = torch.randn(num_observations, xdim, device=device)
    print(f"Sample {k=} of shape {sample.shape}, {sample.device=}")
    model.zero_grad()
    y = model(sample)
    y.norm().backward()
```

### Versions

<details>

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] functorch==0.0.1a0+8ffa328
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] pytorch-forecasting==0.9.2
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[pip3] torchdiffeq==0.2.2
[pip3] torchinfo==1.6.3
[pip3] torchmetrics==0.7.2
[pip3] torchtext==0.11.2
[pip3] torchvision==0.11.3
[conda] blas                      2.113                       mkl    conda-forge
[conda] blas-devel                3.9.0            13_linux64_mkl    conda-forge
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] libblas                   3.9.0            13_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            13_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            13_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            13_linux64_mkl    conda-forge
[conda] mkl                       2022.0.1           h06a4308_117  
[conda] mkl-devel                 2022.0.1           h66538d2_117  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mypy                      0.931            py39h3811e60_2    conda-forge
[conda] mypy_extensions           0.4.3            py39h06a4308_1  
[conda] numexpr                   2.8.0           mkl_py39hba4d566_1    conda-forge
[conda] numpy                     1.21.5           py39haac66dc_0    conda-forge
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-forecasting       0.9.2              pyhd8ed1ab_0    conda-forge
[conda] pytorch-lightning         1.5.10             pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py39_cu113    pytorch
[conda] torchdiffeq               0.2.2              pyhd8ed1ab_0    conda-forge
[conda] torchinfo                 1.6.3              pyhd8ed1ab_0    conda-forge
[conda] torchmetrics              0.7.2              pyhd8ed1ab_0    conda-forge
[conda] torchtext                 0.11.2                     py39    pytorch
[conda] torchvision               0.11.3               py39_cu113    pytorch

</details>

**Comment by randolf-scholz** [comment]
Graph with print included:

```
graph(%self : __torch__.___torch_mangle_11.MWE,
      %x.1 : Tensor):
  %10 : str = prim::Constant[value=""]() # /tmp/ipykernel_136264/479787700.py:12:14
  %8 : int = prim::Constant[value=-1]() # /tmp/ipykernel_136264/479787700.py:11:34
  %5 : Tensor[] = prim::ListConstruct(%x.1, %x.1)
  %x.7 : Tensor = aten::cat(%5, %8) # /tmp/ipykernel_136264/479787700.py:11:12
   = prim::Print(%10) # /tmp/ipykernel_136264/479787700.py:12:8
  %linear : __torch__.torch.nn.modules.linear.___torch_mangle_10.Linear = prim::GetAttr[name="linear"](%self)
  %x.11 : Tensor = prim::CallMethod[name="forward"](%linear, %x.7) # /tmp/ipykernel_136264/479787700.py:13:12
  return (%x.11)
```

With `print("")` excluded:

```
graph(%self : __torch__.___torch_mangle_12.MWE,
      %x.1 : Tensor):
  %8 : int = prim::Constant[value=-1]() # /tmp/ipykernel_136264/1641494950.py:11:34
  %5 : Tensor[] = prim::ListConstruct(%x.1, %x.1)
  %x.7 : Tensor = aten::cat(%5, %8) # /tmp/ipykernel_136264/1641494950.py:11:12
  %linear : __torch__.torch.nn.modules.linear.___torch_mangle_10.Linear = prim::GetAttr[name="linear"](%self)
  %x.11 : Tensor = prim::CallMethod[name="forward"](%linear, %x.7) # /tmp/ipykernel_136264/1641494950.py:13:12
  return (%x.11)
```

**Comment by eellison** [comment]
Hi, I think this is fixed on master. I couldn't repro this. Please re-open if you can repro on master.
