### ISSUE TITLE
pytorch 0.4.  RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by ofirlevy** [pytorch/pytorch#7329]
The MobileNet V2. repo located [here](https://github.com/MG2033/MobileNet-V2) is running flawlessly on pytorch 0.3 but failed on the new 0.4 version with 
```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation. 
```
when it calls backward().

I followed the migration guide but still couldn't point my finger on the problematic code.  I would highly appreciate your help

The train code:
```
for data, target in tqdm_batch:            
    data, target = data.cuda(), target.cuda()                
    # Forward pass
    output = self.model(data)
    cur_loss= self.loss(output, target)
   # Optimization step
    self.optimizer.zero_grad()
    cur_loss.backward()
    self.optimizer.step()
``` 

instead of placing the network here It is more convenient to look at it in the github: [network](https://github.com/MG2033/MobileNet-V2/blob/master/model.py) and its [layers](https://github.com/MG2033/MobileNet-V2/blob/master/layers.py)

**Comment by SsnL** [comment]
try changing your dropout or relu6 to out-of-place

**Comment by soumith** [comment]
@ofirlevy you cannot put the nn.ReLU(inplace=True) at that problematic place and still expect correct gradient computation. PyTorch is complaining that to give correct results for gradients you have to remove that.

**Comment by wenwei202** [comment]
Using the same code, when update to 0.4 from 0.3, I popped up this issue. Does it mean 0.3.0 got the wrong gradients because of some bugs?

**Comment by SsnL** [comment]
@wenwei202 No. But it is possible that the gradient computation for some op changed so they now require different tensors.
