### ISSUE TITLE
torch.range is upper-bound inclusive, while python range and numpy arange are upper-bound exclusive

### ISSUE THREAD

**Issue by stefbraun** [pytorch/pytorch#733]
torch.range(a,b) includes b, while python.range(a,b) or numpy.arange(a,b) do not include b.
Not sure if this is a bug or voluntary, but this is confusing.

pytorch
```
In: torch.range(0,5)
Out: 0 1 2 3 4 5 [torch.FloatTensor of size 6]
```

python standard function
```
In: range(0,5)
Out: [0, 1, 2, 3, 4]

```
numpy
```
In: np.arange(0,5)
Out: array([0, 1, 2, 3, 4])

```

**Comment by soumith** [comment]
while we are debating changing the behavior, I see no reasonable depreciation path for the old behavior.

Any ideas? @jekbradbury ?

**Comment by soumith** [comment]
alright, we're gonna change it and send out an email / @mention everyone in slack when it happens.

**Comment by goelhardik** [comment]
@soumith This needs a change in the TH library, right?

**Comment by soumith** [comment]
yes, i'll be changing it.

**Comment by soumith** [comment]
I think we should make a `torch.arange` that is equivalent to `numpy.arange` and depreceate `torch.range` properly. It is used quite extensively all over the place.
wdyt @colesbury @apaszke ?

**Comment by apaszke** [comment]
Sounds good to me
