### ISSUE TITLE
Caffe2: Is there an equivalent in cpp to workspace.FeedBlob() which is implemented in python?

### ISSUE THREAD

**Issue by ThomusLogitech** [pytorch/pytorch#7333]
Hello,

I posted this question on the pytorch forum but as it is a caffe2 related question I will post it here too:

I am currently working with caffe2 in c++ and I get an error when loading different pre-trained models:

Blob data not in the workspace. 

I searched on internet and found a fix. It consists in creating a blob called “data” and initializing it with random numbers before running the models (https://github.com/caffe2/caffe2/issues/1294). However, I don’t find the way to do it in c++. Indeed, there is a function in python called “FeedBlob” in the “class” workspace that does not exist in c++ (I think). I looked into the caffe 2 files (workspace.h, blob.h…) but I did not find anything to modify a blob in a workspace in cpp (I can create one, delete one but not modifying it).

Does someone know how to fix the original error in c++? Is there a way to modify this blob in c++ that I did not find?

- Caffe2 0.8.4
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): cmake . -DUSE_NATIVE_ARCH=ON

**Comment by alexbuyval** [comment]
Hi @ThomusLogitech 

Did you find how to solve the issue in c++?

Thanks!

**Comment by alejo9719** [comment]
I'm facing the same problem and I need to solve it. Could someone please provide some kind of solution or workaround?
