### ISSUE TITLE
Windows conda builds failed in GHA, blocks windows conda migration

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#73339]
### 🐛 Describe the bug

The details in is https://github.com/pytorch/pytorch/pull/71484#issuecomment-1022617195.

Analysis:
It looks there's something wrong in SOURCES.txt of the attached package. the zip is missing.
![image](https://user-images.githubusercontent.com/16190118/155449665-6c2834dd-67f3-4c6a-973a-0b14d631851a.png)

I build the source code locally with the latest code
![image](https://user-images.githubusercontent.com/16190118/155449873-4f602fe7-ebcf-43da-a037-3388cddf6584.png)

### Versions

1.11

cc @ezyang @gchanan @zou3519 @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
I am curious if we even need these zips in the first place. Like is there a way for us to tell conda to not even worry about these zip files at all?

**Comment by mszhanyi** [comment]
@seemethere 
I tried deleting these zips in my test PR #73342 and the build can pass.
https://github.com/pytorch/pytorch/runs/5374161317?check_suite_focus=true.

But I don't think it could be a solution because I don't the exact root cause now.
Why does it only occur in GHA and Why these zips?

**Comment by seemethere** [comment]
These zips appear to be testing zips, I had a PR to test if not including the zips in the build manifest would actually fix but it doesn't appear as though that did fix: https://github.com/pytorch/pytorch/pull/71793

**Comment by seemethere** [comment]
* I think https://github.com/pytorch/builder/pull/982 might resolve, testing in https://github.com/pytorch/pytorch/pull/73393

**Comment by seemethere** [comment]
> * I think [conda: Delete zip files on windows builder#982](https://github.com/pytorch/builder/pull/982) might resolve, testing in [DO NOT MERGE< testing windows conda #73393](https://github.com/pytorch/pytorch/pull/73393)

Update to this, deleting the zip files prior to the conda build did not seem to resolve fully. For CUDA builds I'm now observing header files being missing so I'm trying to figure out why particular files aren't getting included.

https://github.com/pytorch/pytorch/runs/5400316763?check_suite_focus=true#step:10:31478

```
CondaVerificationError: The package for pytorch located at C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.7_002437\conda\pkgs\pytorch-1.12.0.dev20220303-py3.7_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/_fake_quantize_learnable_per_channel_affine_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.7_002437\conda\pkgs\pytorch-1.12.0.dev20220303-py3.7_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/_fake_quantize_learnable_per_tensor_affine_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.

CondaVerificationError: The package for pytorch located at C:\actions-runner\_work\pytorch\pytorch\builder\tmp_conda_3.7_002437\conda\pkgs\pytorch-1.12.0.dev20220303-py3.7_cuda11.3_cudnn8_0
appears to be corrupted. The path 'Lib/site-packages/torch/include/ATen/ops/fake_quantize_per_channel_affine_cachemask_backward_compositeimplicitautograd_dispatch.h'
specified in the package manifest cannot be found.
```
```

**Comment by mszhanyi** [comment]
@seemethere 
I think I might find the root cause.
The github windows runner doesn't enable the `LongPathEnabled` while circleCI runner does
https://github.com/pytorch/pytorch/runs/5419753343?check_suite_focus=true#step:7:40
![image](https://user-images.githubusercontent.com/16190118/156734254-de66db30-d085-485d-9cda-51e75fee4a15.png)

![image](https://user-images.githubusercontent.com/16190118/156734499-d784a28a-5a7d-4458-a73c-868911e1fc03.png)

**Comment by peterjc123** [comment]
> @seemethere I think I might find the root cause. The github windows runner doesn't enable the `LongPathEnabled` while circleCI runner does https://github.com/pytorch/pytorch/runs/5419753343?check_suite_focus=true#step:7:40 ![image](https://user-images.githubusercontent.com/16190118/156734254-de66db30-d085-485d-9cda-51e75fee4a15.png)
> 
> ![image](https://user-images.githubusercontent.com/16190118/156734499-d784a28a-5a7d-4458-a73c-868911e1fc03.png)
> 
> Could you try updating your github runner's registry since I have no permission.

I think the better way is to shorten the name of that file. Otherwise, it’s still not usable at the user side when they have long path disabled.

**Comment by mszhanyi** [comment]
@seemethere 
test PR passed
https://github.com/pytorch/pytorch/pull/73342
https://github.com/pytorch/pytorch/runs/5420554904?check_suite_focus=true

I think it'd better to set in image.

**Comment by seemethere** [comment]
> > @seemethere I think I might find the root cause. The github windows runner doesn't enable the `LongPathEnabled` while circleCI runner does [pytorch/pytorch/runs/5419753343?check_suite_focus=true#step:7:40](https://github.com/pytorch/pytorch/runs/5419753343?check_suite_focus=true#step:7:40) ![image](https://user-images.githubusercontent.com/16190118/156734254-de66db30-d085-485d-9cda-51e75fee4a15.png)
> > ![image](https://user-images.githubusercontent.com/16190118/156734499-d784a28a-5a7d-4458-a73c-868911e1fc03.png)
> > Could you try updating your github runner's registry since I have no permission.
> 
> I think the better way is to shorten the name of that file. Otherwise, it’s still not usable at the user side when they have long path disabled.

Maybe long path issue in this case (and in the case of CircleCI) is only due to the amount of nesting we do for CI since we install our conda environment in the actual build directory.

@mszhanyi thanks for the fix though! This is huge!!

**Comment by seemethere** [comment]
Just merged the windows conda migration with long key fix here:
* #73262 

Will close this issue after we get a successful nightly run with the new windows conda binaries
