### ISSUE TITLE
Stop CUDA-11.1 binary builds/tests in CI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#73377]
### 🐛 Describe the bug

We've migrated to CUDA-11.3 as default toolkit in 1.9, it's time to stop builds (especially considering forward-compatibility guarantee across CUDA-11.x drivers)

Colab can be updated to 11.3 as well: https://colab.research.google.com/drive/13bdIEU6yinaQHOdytVqS2EEPG5Mir8uP?usp=sharing

### Versions

Nightly

cc @ezyang @seemethere @malfet @ngimel @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
https://github.com/pytorch/pytorch/pull/73376 partially addresses that, need to follow up with changes in domains

**Comment by seemethere** [comment]
https://github.com/pytorch/pytorch/pull/73449 shoudl address the rest of this for CI
