### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by skynbe** [pytorch/pytorch#7337]
Does F.kl_div(a, b) mean KL(b||a), not KL(a||b) ?

**Comment by zou3519** [comment]
https://pytorch.org/docs/master/nn.html?highlight=kldiv#torch.nn.KLDivLoss Does that help? I'm not sure what your notation means.

**Comment by skynbe** [comment]
I mean the notation of D_KL in https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence

**Comment by soumith** [comment]
yes, F.kl_div(x, y) is KL(y||x). Here x is already in log-probabilities, so the formula is changed further.

**Comment by zhangbin0917** [comment]
Can I ask why here using log-probability not probability for x ?
I mean, intuitively, using probability should be better understood.
