### ISSUE TITLE
[JIT] Disable NVFuser for ROCm builds

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#73448]
### 🐛 Describe the bug

NVFuser fails on ROCm builds. See here: https://github.com/pytorch/pytorch/runs/5330819673?check_suite_focus=true

I've disabled the tests on ROCm for now.

I think the right way to do this is with `#ifdef __HIP_PLATFORM_HCC__`

### Versions

ROCm CI build

cc @ngimel @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jjsjann123** [comment]
Looks like PR #75284 should have fixed this one?

**Comment by davidberard98** [comment]
Yeah, thanks for reminding me!
