### ISSUE TITLE
[ROCm] Floating point exception (core dumped) for particular Conv2d call

### ISSUE THREAD

**Issue by Wulfsta** [pytorch/pytorch#73444]
### 🐛 Describe the bug

Running on a Radeon VII, the following convolution fails with a `Floating point exception (core dumped)` for some reason: 
```
torch.nn.Conv2d(3, 96, kernel_size=11, stride=4, padding=5, device=torch.device('cuda'))(torch.randn((1,3,3200,3200), device=torch.device('cuda')))
```

### Versions

$ python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.9.0a0+git4530dc5
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.2.21155-37cb3a34

OS: Ubuntu 21.04 (x86_64)
GCC version: (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.33

Python version: 3.9.6 (default, Jul 17 2021, 18:43:26)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-051300rc6-generic-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Vega 20 [Radeon VII]
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 3.27.5
MIOpen runtime version: 2.11.0
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0a0+git4530dc5
[pip3] torchinfo==0.1.5
[pip3] torchvision==0.9.0a0+8fb5838
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by malfet** [comment]
@Wulfsta just to confirm: you've build pytorch locally from a forked repo? (https://github.com/pytorch/pytorch/commit/4530dc5d382591d91c509836865dc12081c7b2c5 does not seem to belong to pytorch/pytorch repo) Regardless, can you please try PyTorch-1.10.2 ROCm built from https://pytorch.org/get-started/locally/ ?

**Comment by Wulfsta** [comment]
@malfet I don’t think this was a local build, I think I pulled a nightly build from somewhere? I can’t upgrade immediately, but will try sometime within two weeks.

**Comment by hongxiayang** [comment]
@Wulfsta Hi, have you tried to upgrade to pytorch/pytorch and see if this is still a problem? Thanks.

**Comment by Wulfsta** [comment]
I actually haven’t had a chance to try, I am still using the older version on a dedicated machine. I suspect you can close this if nobody else has encountered the issue.

**Comment by jithunnair-amd** [comment]
Tried the testcase on upstream PyTorch (`rocm/pytorch-nightly:latest`) as well as ROCm PyTorch (`rocm/pytorch:latest`), both with ROCm5.6, and both cases passed:
```
>>> torch.nn.Conv2d(3, 96, kernel_size=11, stride=4, padding=5, device=torch.device('cuda'))(torch.randn((1,3,3200,3200), device=torch.device('cuda')))
tensor([[[[-0.0241, -0.3994, -0.1832,  ..., -0.7369, -0.3682,  0.0872],
          [-0.1828,  0.5271,  0.3444,  ...,  0.3833,  0.9857, -0.1832],
          [-0.4145,  0.0635,  0.9180,  ..., -0.0959,  0.7972,  0.0475],
          ...,
          [ 0.2596, -0.1313, -0.0991,  ...,  0.0339, -0.3682, -0.4287],
          [-0.1155, -0.2170,  0.3931,  ..., -0.2126, -0.2969, -0.6371],
          [ 0.3276,  0.2367,  0.1052,  ..., -0.3045,  0.0722, -0.4195]],

         [[-0.0053, -0.8541, -0.3692,  ...,  0.2954,  0.4206,  0.2759],
          [ 0.4617,  0.0683,  0.6479,  ..., -0.5919,  0.2492,  0.8612],
          [-0.1223, -1.1550, -0.1780,  ..., -0.3864,  0.0942, -0.1996],
          ...,
          [ 0.5112,  0.3046,  0.1139,  ..., -0.4483,  0.1811, -0.0444],
          [ 0.0789,  0.1066,  0.6001,  ..., -0.3262,  0.1905, -0.2951],
          [ 0.0776,  0.0191,  0.0540,  ..., -0.0488,  0.1239, -1.1316]],

         [[-0.0921, -0.4202,  0.3718,  ...,  0.3849,  0.0807, -0.4548],
          [-0.1977, -0.4781, -0.2028,  ...,  0.3596, -0.0701, -0.3543],
          [-0.4607,  0.2797,  0.0882,  ..., -0.8800, -0.0472,  0.2604],
          ...,
          [ 0.4532, -0.4388,  0.0141,  ..., -0.2334, -0.0246,  0.0789],
          [ 0.3376,  0.2910,  0.4915,  ...,  0.9339, -0.3300,  0.2486],
          [-0.3175,  0.6696,  0.4073,  ...,  0.0929,  0.1320, -1.1763]],

         ...,

         [[ 0.9317, -0.3304,  0.2299,  ...,  1.0078,  1.2537, -0.4399],
          [ 0.1875, -0.1575,  0.3853,  ...,  0.4429, -0.8288,  0.4027],
          [-0.0397,  0.4777,  0.1076,  ...,  0.6473,  0.3141,  0.0250],
          ...,
          [-0.3209,  0.0233,  0.2237,  ..., -0.2920, -0.5526, -0.0109],
          [ 0.0912,  0.2475, -0.9226,  ...,  0.0172, -0.2727, -0.1182],
          [-0.7990,  0.0772, -0.7705,  ..., -1.0404,  0.7499,  0.1277]],

         [[ 0.1905, -0.1481,  0.1854,  ..., -0.3082, -0.0128, -0.0163],
          [ 0.1226,  1.0126, -0.5331,  ...,  0.4581, -0.1876,  0.0684],
          [-0.0805, -0.3243, -0.9149,  ..., -0.5378, -0.6987, -0.3712],
          ...,
          [-0.1425,  0.7155,  0.5340,  ..., -0.3736,  0.1474, -0.0647],
          [ 0.0444, -0.8453, -0.1724,  ...,  0.7853,  0.0450, -0.0211],
          [ 0.1476, -1.0011, -0.4926,  ...,  0.9966, -0.0205, -0.5797]],

         [[-0.2692, -0.4202,  0.1772,  ...,  0.7652,  0.0549, -0.1919],
          [-0.0323, -0.0507,  1.2373,  ...,  1.2504, -0.1549, -0.1252],
          [ 0.4141,  0.3291, -0.4688,  ..., -0.0930,  0.2243,  0.4514],
          ...,
          [-0.6996,  0.4753, -0.5947,  ...,  0.4404, -0.3302,  0.8005],
          [ 0.4095, -0.3708, -0.4682,  ...,  0.0065, -0.9430,  0.9806],
          [-0.2924,  0.0642, -0.8620,  ...,  0.2675,  0.2749,  0.1380]]]],
       device='cuda:0', grad_fn=<ConvolutionBackward0>)
```

Closing this issue.
