### ISSUE TITLE
MacOS tests sometimes failing with "botocore.exceptions.ClientError: An error occurred (AccessDeniedException)"

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73458]
## Current Status
mitigated

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
On MacOS tests in the Upload Test Statistics step:
```
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when 
calling the Invoke operation: User: arn:aws:iam::308535385114:user/pytorch-pytorch-
ossci-s3-read-write is not authorized to perform: lambda:InvokeFunction on resource: 
arn:aws:lambda:us-east-1:308535385114:function:rds-proxy because no identity-based 
policy allows the lambda:InvokeFunction action
```
e.g., https://github.com/pytorch/pytorch/runs/5337309425?check_suite_focus=true

This seems to only occur when tests fail/are flaky because RDS permissions are missing.

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
- 2/24 unsure when incident began
- 2/25 12:30pm detected by seeing failures on the HUD 
- 2/25 9:00 pm root caused as…
- 2/25 9:10 pm mitigated by…
- 2/25 10: am closed by…

## User impact
*How does this affect users of PyTorch CI?*
Upload test stats will fail when it doesn't relate to the user.

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by seemethere** [comment]
Seems like this is pretty inconsistent, how did we not run into this before? I don't think we changed anything

**Comment by rohan-varma** [comment]
Some more examples 

https://github.com/pytorch/pytorch/runs/5342786901?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/5342280580?check_suite_focus=true

**Comment by malfet** [comment]
The error is super self-explanatory. Added "lambda-invoke-rds-proxy " policy permission to "arn:aws:iam::308535385114:user/pytorch-pytorch-ossci-s3-read-write"

**Comment by malfet** [comment]
> Seems like this is pretty inconsistent, how did we not run into this before? I don't think we changed anything

We probably didn't have flaky tests on Mac before. Or may be we changed the credentials recently...

**Comment by malfet** [comment]
Closing as "mitigated", but we should have post-mortem
Also, if we want to publish those stats to scribe as well, we should add `gh-ci-scribe-proxy` permission
```
ERROR ENCOUNTERED WHEN UPLOADING TO SCRIBE: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:iam::308535385114:user/pytorch-pytorch-ossci-s3-read-write is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:308535385114:function:gh-ci-scribe-proxy because no identity-based policy allows the lambda:InvokeFunction action
```

**Comment by malfet** [comment]
Followups: 
 - We need to make sure that "write-to-rds" codepath is regularly exercised across all types of runners
