### ISSUE TITLE
Support tensor_split in ONNX export

### ISSUE THREAD

**Issue by victorconan** [pytorch/pytorch#73454]
### 🚀 The feature, motivation and pitch

When working with BERT models, doing tensor splits is very common practice. However, such operation is currently not supported in ONNX export. 

When splitting using a list of integers, the tracing does not work if the list is of variable length. When using torhc.tensor_split, the export does not work as it is currently not supported.

Would be great if we can have this supported in ONNX export. Thanks!

**Comment by jinfagang** [comment]
@qqaatw which op will use for tensor_split?

**Comment by qqaatw** [comment]
@jinfagang Not sure what you referred to. The PR just enabled onnx export for `torch.tensor_split`.

**Comment by jinfagang** [comment]
@qqaatw Which onnx op it converts to??

**Comment by qqaatw** [comment]
@jinfagang It dynamically and conditionally converts to a number of onnx ops.

There is no single onnx op that behaves exactly the same as `torch.tensor_split`.

**Comment by jinfagang** [comment]
@qqaatw  Hi, I think it's opposite. onnx have a single Split can mimic behavior of torch op like `tensor_split` `split` `unbind` `chunck` etc.

**Comment by qqaatw** [comment]
@jinfagang At least at the time when I implemented it, there was no single onnx op that behaved `torch.tensor_split`. I see there is a new `Split-18` added in Oct. but having not been released yet, maybe it can do so as you stated.

**Comment by jinfagang** [comment]
@qqaatw  Which op did u symbolic when you create this PR? Just for curiosity.

**Comment by qqaatw** [comment]
@jinfagang Feel free to check the PR as well as the code. This way would be more efficient and time-saving than belaboring every detail of the PR wouldn't it?

**Comment by jinfagang** [comment]
OK, then, Gather + Split + Squeeze is not a good way though...
