### ISSUE TITLE
[quant][graphmode] kwargs breaks convert handling of functional.linear

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#73463]
### 🐛 Describe the bug

Repro using `torchbenchmark:

```
import torch
import torchbenchmark
import torch.fx
import warnings
import time

if __name__ == '__main__':
    device = 'cpu'

    succeeded_count = 0
    succeeded_names = []

    for model_idx, Model in enumerate(torchbenchmark.list_models()):
        if 'nvidia_deeprecommender' not in Model.__module__:
            continue

        try:
            m = Model(device=device)
        except Exception as e:
            warnings.warn(f'{Model.__module__}.{Model.__name__} failed instantiation {str(e)}')
            continue

        float_model, example = m.get_module()

        batch_sizes = [1, 16, 64, 128, 256]
        dataset = [(example[0][:batch_size].contiguous(), None) for batch_size in batch_sizes]

        from torch.quantization import get_default_qconfig
        from torch.quantization.quantize_fx import prepare_fx, convert_fx
        float_model.eval()
        qconfig = get_default_qconfig("fbgemm")
        qconfig_dict = {"": qconfig}
        def calibrate(model, data_loader):
            model.eval()
            with torch.no_grad():
                for image, target in data_loader:
                    model(image)
        s = time.time()
        traced = torch.fx.symbolic_trace(float_model)
        print(traced.code)
        prepared_model = prepare_fx(float_model, qconfig_dict)
        print('prepare', (time.time() - s) * 1000, 'ms')
        s = time.time()
        calibrate(prepared_model, dataset)
        print('calibrate', (time.time() - s) * 1000, 'ms')
        s = time.time()
        quantized_model = convert_fx(prepared_model)
        print('convert', (time.time() - s) * 1000, 'ms')
```

Results in:

```
Traceback (most recent call last):
  File "/home/jamesreed/fx_paper_final_eval/quant_repro.py", line 43, in <module>
    quantized_model = convert_fx(prepared_model)
  File "/data/users/jamesreed/pytorch/torch/ao/quantization/quantize_fx.py", line 692, in convert_fx
    return _convert_fx(
  File "/data/users/jamesreed/pytorch/torch/ao/quantization/quantize_fx.py", line 590, in _convert_fx
    quantized = convert(
  File "/data/users/jamesreed/pytorch/torch/ao/quantization/fx/convert.py", line 570, in convert
    result = obj.convert(
  File "/data/users/jamesreed/pytorch/torch/ao/quantization/fx/quantization_patterns.py", line 990, in convert
    linear_weight = load_arg(quantized=dtype)(self.linear_node.args[1])
IndexError: tuple index out of range
```

Which implicates the handling of `F.linear` nodes: https://github.com/pytorch/pytorch/blob/9a8000fbf112ddc54b5afaa8aa2575f80f8ff8de/torch/ao/quantization/fx/quantization_patterns.py#L990

The following patch to torchbenchmark fixes it by making those arguments positional:

```
diff --git a/torchbenchmark/models/nvidia_deeprecommender/reco_encoder/model/model.py b/torchbenchmark/models/nvidia_deeprecommender/reco_encoder/model/model.py
index 28e9bb7..2197627 100644
--- a/torchbenchmark/models/nvidia_deeprecommender/reco_encoder/model/model.py
+++ b/torchbenchmark/models/nvidia_deeprecommender/reco_encoder/model/model.py
@@ -98,7 +98,7 @@ class AutoEncoder(nn.Module):
 
   def encode(self, x):
     for ind, w in enumerate(self.encode_w):
-      x = activation(input=F.linear(input=x, weight=w, bias=self.encode_b[ind]), kind=self._nl_type)
+      x = activation(input=F.linear(x, w, self.encode_b[ind]), kind=self._nl_type)
     if self._dp_drop_prob > 0: # apply dropout only on code layer
       x = self.drop(x)
     return x
@@ -106,14 +106,14 @@ class AutoEncoder(nn.Module):
   def decode(self, z):
     if False: #self.is_constrained:
       for ind, w in enumerate(list(reversed(self.encode_w))): # constrained autoencode re-uses weights from encoder
-        z = activation(input=F.linear(input=z, weight=w.transpose(0, 1), bias=self.decode_b[ind]),
+        z = activation(input=F.linear(z, w.transpose(0, 1), self.decode_b[ind]),
                      # last layer or decoder should not apply non linearities
                      kind=self._nl_type if ind!=self._last or self._last_layer_activations else 'none')
         #if self._dp_drop_prob > 0 and ind!=self._last: # and no dp on last layer
         #  z = self.drop(z)
     else:
       for ind, w in enumerate(self.decode_w):
-        z = activation(input=F.linear(input=z, weight=w, bias=self.decode_b[ind]),
+        z = activation(input=F.linear(z, w, self.decode_b[ind]),
                      # last layer or decoder should not apply non linearities
                      kind=self._nl_type if ind!=self._last or self._last_layer_activations else 'none')
         #if self._dp_drop_prob > 0 and ind!=self._last: # and no dp on last layer
```

The general solution here would be one of:

1. The code in `quantization_patterns.py` should accept arguments in either their `args` or `kwargs` positions
2. Python targets should be [normalized](https://github.com/pytorch/pytorch/blob/33ca944f294e2724425e0bb2bd5ffdf47827387e/torch/fx/experimental/normalize.py#L18) before processed by quantization

### Versions

Collecting environment information...
PyTorch version: 1.10.0a0+git30214ae
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: CentOS Stream 8 (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3)
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.28

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.6.13-0_fbk19_6064_gabfd136bb69a-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.0.194
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.2.1
/usr/lib64/libcudnn_adv_infer.so.8.2.1
/usr/lib64/libcudnn_adv_train.so.8.2.1
/usr/lib64/libcudnn_cnn_infer.so.8.2.1
/usr/lib64/libcudnn_cnn_train.so.8.2.1
/usr/lib64/libcudnn_ops_infer.so.8.2.1
/usr/lib64/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.12.0a0+git9a8000f
[pip3] torch-struct==0.4
[pip3] torchfile==0.1.0
[pip3] torchtext==0.11.0a0+05623df
[pip3] torchvision==0.12.0a0+194a084
[pip3] torchviz==0.0.2
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.3.0           h06a4308_520  
[conda] mkl-include               2021.3.0           h06a4308_520  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.0            py39h42c9631_2  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] torch                     1.12.0a0+git9a8000f           dev_0    <develop>
[conda] torch-struct              0.4                       dev_0    <develop>
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchtext                 0.11.0a0+05623df           dev_0    <develop>
[conda] torchvision               0.12.0a0+194a084           dev_0    <develop>
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
Thanks for reporting the issue! `convert.py` and `quantization_patterns.py` is undergoing some big refactors, we'll make sure to address this problem after the refactor
