### ISSUE TITLE
[torchelastic] properly format (or don't log) trace info in structured error when the agent process is killed prematurely

### ISSUE THREAD

**Issue by kiukchung** [pytorch/pytorch#73465]
### 🐛 Describe the bug

When running with `torchrun` and:

1. `TORCHELASTIC_ERROR_FILE` env var is not set at the agent level
2. The agent process (process that is running `torchrun`) either raises an error or is killed prematurely due to a signal

Then we end up seeing an ugly unformatted trace info (`extraInfo.py_callstack`) from the error log of the structured error of the agent process (see screenshot below)

![image](https://user-images.githubusercontent.com/43595115/155855468-79a58dd5-0f26-49c6-8ed2-d9f17f4ef168.png)

What should happen is that we either format the trace info in the structured error when logging or just skip the error logging and let python's error handling/console printing do the job.

REPRO STEPS:

1. create a `test.py` with a single line `import time; time.sleep(6000)`
2. `torchrun --nproc_per_node 2 --nnodes 1:1 --rdzv_backend c10d --rdzv_endpoint localhost:29500 --monitor_interval 3 test.py`
3. grab the PID of #2 and run `kill -15` on it 
4. Observe the unformatted error traceback (as shown in the screenshot). The logging is done on this line: https://github.com/pytorch/pytorch/blob/df11e2d6f9782fc3995e17ef09a5ef3812da041d/torch/distributed/elastic/multiprocessing/errors/error_handler.py#L36

ADDITIONAL LINKS:

1) (Original user report): https://github.com/pytorch/pytorch/pull/65041#issuecomment-1051368205

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.23

Python version: 3.8.5 (default, Mar 24 2021, 22:32:23)  [GCC 5.4.0 20160609] (64-bit runtime)
Python platform: Linux-4.4.0-1102-aws-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 440.33.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] pytorch-lightning==1.3.5
[pip3] torchaudio==0.9.0
[pip3] torchelastic==0.2.3.dev0
[pip3] torchmetrics==0.3.2
[pip3] torchserve==0.4.0
[pip3] torchvision==0.10.0+cu111
[pip3] torchx==0.1.1.dev0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2021.3.0           h06a4308_520
[conda] torch                     1.12.0.dev20220225+cu102          pypi_0    pypi

**Comment by stas00** [comment]
Please see these 2 log files for examples of interleaving and too many errors replayed for each node and/or process:

[181B-n48-pp12-bf16-2182654.txt](https://github.com/pytorch/pytorch/files/8147304/181B-n48-pp12-bf16-2182654.txt)
[181B-n48-pp6-bf16-1305.txt](https://github.com/pytorch/pytorch/files/8147305/181B-n48-pp6-bf16-1305.txt)

This 48 nodes of 8 gpus each:

```
$ grep ERROR 181B-n48-pp12-bf16-2182654.out |wc -l
48
$ grep Traceback 181B-n48-pp6-bf16-1305.out |wc -l
429
```

Both exemplify what I have been referring to in various issues.

Some errors are dumped once per node (first `wc -l`, others for each process, 2nd `wc -l`)

and you can see that at times it's impossible to unravel the Tracebacks as they are interleaved, ` 181B-n48-pp12-bf16-2182654.out` is the better example of interleaving. sometimes it's almost perfect, other times it's much much worse interleaving. If need be I can dig up more examples.

If you would like any more input about the setup please let me know but otherwise it's:

```
export LAUNCHER="python -u -m torch.distributed.run \
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --rdzv_endpoint $MASTER_ADDR:$MASTER_PORT \
    --rdzv_backend c10d \
    --max_restarts 0 \
    "
```

Thank you!

**Comment by kiukchung** [comment]
Looks like you have a single .out file for all the nodes. Are you observing intra or inter node trace interleaving?

**Comment by stas00** [comment]
Well, there are typically 2 types of failures:

1. something happened in all processes - e.g. broken code - and they all die at once - same error
2. something happens in one process - e.g. OOM - and then all processes get killed 

currently in either event we end up with n_errors == n_gpus, whereas the ideal situation would be, that only a set of these errors is printed. So if it's the same error on all processes it just says - all processes died with the following error, or there were 2 errors, etc. But I suppose the heuristics of comparing the different backtraces could be complicated.

**Comment by stas00** [comment]
ok, I tried `--tee 3` and it prefixes local rank but how does it help? 

Are you suggesting that it'd be helpful if I get an intra-interleaved traceback and then I'd grep for a single local rank, and thus be able to extract the non-interleaved traceback?

That's doable but that's doing a whole bunch of steps, when I quickly need to determine the cause of failure and act on it.

Typically I have the cursor on the last good line of the `tail -f file` while it continues spitting data or use console's search to find the place before the crash, and I want to get the normal traceback right there. But now I have to copy-n-paste this to another file, grep this file, create new file and only then I get to the traceback. This is very painfully inefficient. but doable.

**Comment by stas00** [comment]
Here is another related issue https://github.com/pytorch/pytorch/issues/60911

**Comment by stas00** [comment]
> I see, yep this is something we've been wanting to fix. Just to be clear, (besides the duplicate error logs) this isn't a regression from torch-1.8 right? AFAIK this has been an issue with the fact that torch runs multiple workers on the same node as different processes.

definitely not a regression and when I tried with 1.11-tobe it looked as if someone worked on it and more often than not the tracebacks were either non-interleaved or close to being non-interleaved. Except when it completely fails and gets very interleaved. So perhaps the "working" was just a coincidence. 

If I try to reproduce it with a small example on a single node 95% of time I get perfect non-interleaved tracebacks. But you have seen now the situation from the logs I attached: https://github.com/pytorch/pytorch/issues/73465#issuecomment-1052474028

**Comment by stas00** [comment]
also if I orchestrate a failure Megatron-Deespeed I consistently get a bunch of segfaults with, so my log ends with:

```
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-02-26_22:02:07
  host      : jean-zay-iam39-ib0
  rank      : 304 (local_rank: 0)
  exitcode  : 1 (pid: 181845)
  error_file: /tmp/torchelastic_78rus22c/none_h9w4ezyp/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/gpfswork/rech/six/commun/conda/py38-pt111/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
      return f(*args, **kwargs)
    File "/gpfswork/rech/six/commun/code/tr8b-104B/Megatron-DeepSpeed/pretrain_gpt.py", line 241, in main
      die
  NameError: name 'die' is not defined
  
============================================================
  File "/gpfswork/rech/six/commun/conda/py38-pt111/l  File "/gpfswork/rech/six/commun/conda/  File "/gpfswork/rech/six/commun/conda/py38-pt111/lib/python3.8/site-packa  File "/gpfswork/rech/six/commun/conda/py38-pt111/lib/python3.8/runpy.py"  File "/gpfswork/rech/six/commun/conda/py38-pt111/lib/pythsrun: error: jean-zay-iam21: task 20: Exited with exit code 1
srun: error: jean-zay-iam29: task 28: Exited with exit code 1
srun: error: jean-zay-iam35: task 34: Segmentation fault (core dumped)
srun: error: jean-zay-iam08: task 7: Exited with exit code 1
srun: error: jean-zay-iam31: task 30: Exited with exit code 1
srun: error: jean-zay-iam41: task 40: Exited with exit code 1
srun: error: jean-zay-iam14: task 13: Exited with exit code 1
srun: error: jean-zay-iam15: task 14: Exited with exit code 1
srun: error: jean-zay-iam26: task 25: Exited with exit code 1
srun: error: jean-zay-iam06: task 5: Exited with exit code 1
srun: error: jean-zay-iam37: task 36: Exited with exit code 1
srun: error: jean-zay-iam24: task 23: Segmentation fault (core dumped)
srun: error: jean-zay-iam17: task 16: Segmentation fault (core dumped)
srun: error: jean-zay-iam46: task 45: Exited with exit code 1
srun: error: jean-zay-iam23: task 22: Segmentation fault (core dumped)
srun: error: jean-zay-iam03: task 2: Exited with exit code 1
srun: error: jean-zay-iam47: task 46: Exited with exit code 1
srun: error: jean-zay-iam13: task 12: Exited with exit code 1
srun: error: jean-zay-iam42: task 41: Exited with exit code 1
srun: error: jean-zay-iam19: task 18: Exited with exit code 1
srun: error: jean-zay-iam33: task 32: Segmentation fault (core dumped)
srun: error: jean-zay-iam25: task 24: Exited with exit code 1
srun: error: jean-zay-iam43: task 42: Exited with exit code 1
srun: error: jean-zay-iam45: task 44: Exited with exit code 1
srun: error: jean-zay-iam36: task 35: Exited with exit code 1
srun: error: jean-zay-iam40: task 39: Exited with exit code 1
srun: error: jean-zay-iam04: task 3: Exited with exit code 1
srun: error: jean-zay-iam12: task 11: Exited with exit code 1
srun: error: jean-zay-iam16: task 15: Exited with exit code 1
srun: error: jean-zay-iam32: task 31: Exited with exit code 1
srun: error: jean-zay-iam09: task 8: Exited with exit code 1
srun: error: jean-zay-iam38: task 37: Exited with exit code 1
srun: error: jean-zay-iam34: task 33: Exited with exit code 1
srun: error: jean-zay-iam28: task 27: Exited with exit code 1
srun: error: jean-zay-iam20: task 19: Exited with exit code 1
srun: error: jean-zay-iam30: task 29: Exited with exit code 1
srun: error: jean-zay-iam10: task 9: Exited with exit code 1
srun: error: jean-zay-iam27: task 26: Exited with exit code 1
srun: error: jean-zay-iam48: task 47: Exited with exit code 1
srun: error: jean-zay-iam39: task 38: Exited with exit code 1
srun: error: jean-zay-iam07: task 6: Segmentation fault (core dumped)
srun: error: jean-zay-iam02: task 1: Segmentation fault (core dumped)
srun: error: jean-zay-iam22: task 21: Segmentation fault (core dumped)
srun: error: jean-zay-iam44: task 43: Segmentation fault (core dumped)
srun: error: jean-zay-iam18: task 17: Segmentation fault (core dumped)
srun: error: jean-zay-iam11: task 10: Segmentation fault (core dumped)
srun: error: jean-zay-iam01: task 0: Exited with exit code 1
```

where the bt is:

```
(gdb) bt
#0  0x000014557cdfb9bf in sigsuspend () from /lib64/libpthread.so.0
#1  0x0000000000000000 in ?? ()
(gdb) thread apply all bt

Thread 3 (LWP 181629):
warning: Section `.reg-xstate/181629' in core file too small.
#0  0x000014557cb15a41 in process_entry () from /lib64/libc.so.6
#1  0x0000000000000000 in ?? ()

Thread 2 (LWP 181583):
warning: Section `.reg-xstate/181583' in core file too small.
#0  0x000014557cdf9bd6 in sem_close () from /lib64/libpthread.so.0
#1  0x000055cdf1a75d30 in ?? () at /tmp/build/80754af9/python-split_1634043551344/work/Modules/_threadmodule.c:64
#2  0x00001454e4000b60 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 1 (LWP 181630):
#0  0x000014557cdfb9bf in sigsuspend () from /lib64/libpthread.so.0
#1  0x0000000000000000 in ?? ()
```

perhaps it's totally unrelated to the launcher and something that this framework causes...
