### ISSUE TITLE
Problem with Einsum

### ISSUE THREAD

**Issue by Srinivas11062000** [pytorch/pytorch#73485]
Hi everyone,i am having some trouble with Einsum
 File "/usr/local/lib/python3.7/dist-packages/torch/functional.py", line 327, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): operands do not broadcast with remapped shapes [original->remapped]: [128, 8, 1, 128]->[128, 8, 128, 1, 1] [1, 64, 64]->[1, 1, 64, 64, 1]

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/

Make sure to share some code to reproduce the issue when you post there.
