### ISSUE TITLE
Windows workflows frequently failing with timeout

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#73495]
## Current Status
Mitigated

## Error looks like
Example failure looks like: https://github.com/pytorch/pytorch/runs/5346428448?check_suite_focus=true

## Incident timeline (all times pacific)
Started on 2/22/22 around 12pm PST, with this commit: https://hud2.pytorch.org/pytorch/pytorch/commit/53faf78143bbca3157dfef41dedf76eb0ba0b9f2

<summary>  
Around 2/22/22, windows CI jobs started to fail with timeout errors such as https://github.com/pytorch/pytorch/runs/5346428448?check_suite_focus=true. It looks like this issue started with this commit: https://hud2.pytorch.org/pytorch/pytorch/commit/53faf78143bbca3157dfef41dedf76eb0ba0b9f2 which may have increased the duration of windows tests resulting in this timeout, though this is yet to be determined. 

</summary>

<details>

e.g.
- 2/22 12:22pm Incident began
- 2/22 12:54pm Manually detected by OSS CI oncall, pinged in chat
- [not yet root caused]
- [not yet mitigated]
- [not yet closed]

</details>

## User impact
- Windows jobs are failing, causing noise on PRs and potentially masking real windows breakages

## Root cause
To be filled out after mitigation

## Mitigation
@malfet sent a PR to bump windows test timeout: https://github.com/pytorch/pytorch/pull/73490

[todo] try to revert https://hud2.pytorch.org/pytorch/pytorch/commit/53faf78143bbca3157dfef41dedf76eb0ba0b9f2

## Prevention/followups
- to be filled out after investigation

**Comment by malfet** [comment]
Followup:
 - Raise an alert when test runtime is 75+% of the specified limit
 - [BE] Why do we need to limits: one on the workflow and another on the job
