### ISSUE TITLE
`torch.nn.init.orthogonal_` does check tensor with zero rows

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#73503]
### 🐛 Describe the bug

`torch.nn.init.orthogonal_` does check tensor with zero dimension

```python
import torch
input = torch.rand([0, 1])
torch.nn.init.orthogonal_(input)
# ZeroDivisionError: integer division or modulo by zero
```

### Versions

pytorch: 1.10.1

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @pbelevich

**Comment by albanD** [comment]
Thanks for the report.
We would accept a PR that makes this function a no-op for empty inputs.
