### ISSUE TITLE
[FSDP] sharded_state_dict

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#73518]
### 🚀 The feature, motivation and pitch

Placeholder issue for FSDP sharded_state_dict implementation. Main checkpoint issue: https://github.com/pytorch/pytorch/issues/73043

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
This is done for both model and optimizer.
