### ISSUE TITLE
PyTorch for ROCm on a Supported Device Throws "hipErrorNoBinaryForGpu"

### ISSUE THREAD

**Issue by richardbrggs7** [pytorch/pytorch#73534]
### 🐛 Describe the bug

I am trying to install PyTorch with ROCm support on a Unibap iX10 ADS - which uses a slightly modified version of Ubuntu 18.04 server with an AMD Ryzen Embedded V1605B with Radeon Vega Gfx GPU - and whether I install from source of via pip the error ```hipErrorNoBinaryForGpu: Unable to find code object for all current devices!``` is thrown when I try to use CUDA, even though C HIP code compiles and runs perfectly well. 
Using the environment variable AMD_LOG_LEVEL=6 I have found that it seems like it tries to look for an incorrect device; I am including a few test script outputs. To summarize them, square.cpp is a HIP file that squares the elements in an array and compiles and runs without issues; based on the output log, it seems to look for the correct device "AMD Ryzen Embedded V1605B with Radeon Vega Gfx."
PyTest.py is a simple python script that does nothing but import torch and ```print(torch.cuda.is_available())``` and throws the error before crashing. The output log shows that it looks for the device "amdgcn-amd-amdhsa--gfx902:xnack+," which is a part of my device - rocminfo lists it as the ISA of Agent 2 - though it seems like it is incorrect, since square does not seem to look for it. 
I am also including the output of rocminfo for more information on my system.
[pyTestOutput.txt](https://github.com/pytorch/pytorch/files/8156819/pyTestOutput.txt)
[rocminfo.txt](https://github.com/pytorch/pytorch/files/8156822/rocminfo.txt)
[squareOutput.txt](https://github.com/pytorch/pytorch/files/8156823/squareOutput.txt)
 

### Versions

Collecting environment information...
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
Aborted (core dumped)

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by mysteryjeans** [comment]
I am facing same issue but for **amdgcn-amd-amdhsa--gfx1010:xnack- - [Not Found]**

```
>>> import torch
>>> torch.cuda.is_available()
:3:rocdevice.cpp            :414 : 34831946688 us: 30   : [tid:0x7f2900de80c0] Initializing HSA stack.
:3:comgrctx.cpp             :33  : 34831974083 us: 30   : [tid:0x7f2900de80c0] Loading COMGR library.
:3:rocdevice.cpp            :205 : 34831979970 us: 30   : [tid:0x7f2900de80c0] Numa selects cpu agent[0]=0x559781b73f90(fine=0x559785447460,coarse=0x559785436740) for gpu agent=0x559785456360
:3:rocdevice.cpp            :1591: 34831980834 us: 30   : [tid:0x7f2900de80c0] HMM support: 1, xnack: 0, direct host access: 40

:4:rocdevice.cpp            :1887: 34831980946 us: 30   : [tid:0x7f2900de80c0] Allocate hsa host memory 0x7f27820d8000, size 0x28
:4:rocdevice.cpp            :1887: 34831981672 us: 30   : [tid:0x7f2900de80c0] Allocate hsa host memory 0x7f2755700000, size 0x101000
:4:rocdevice.cpp            :1887: 34831982652 us: 30   : [tid:0x7f2900de80c0] Allocate hsa host memory 0x7f2755500000, size 0x101000
:4:runtime.cpp              :82  : 34831982956 us: 30   : [tid:0x7f2900de80c0] init
:3:hip_context.cpp          :50  : 34831982976 us: 30   : [tid:0x7f2900de80c0] Direct Dispatch: 1
:1:hip_code_object.cpp      :460 : 34831983045 us: 30   : [tid:0x7f2900de80c0] hipErrorNoBinaryForGpu: Unable to find code object for all current devices!
:1:hip_code_object.cpp      :461 : 34831983061 us: 30   : [tid:0x7f2900de80c0]   Devices:
:1:hip_code_object.cpp      :464 : 34831983075 us: 30   : [tid:0x7f2900de80c0]     amdgcn-amd-amdhsa--gfx1010:xnack- - [Not Found]
:1:hip_code_object.cpp      :468 : 34831983088 us: 30   : [tid:0x7f2900de80c0]   Bundled Code Objects:
:1:hip_code_object.cpp      :485 : 34831983100 us: 30   : [tid:0x7f2900de80c0]     host-x86_64-unknown-linux - [Unsupported]
:1:hip_code_object.cpp      :483 : 34831983120 us: 30   : [tid:0x7f2900de80c0]     hipv4-amdgcn-amd-amdhsa--gfx1030 - [code object v4 is amdgcn-amd-amdhsa--gfx1030]
:1:hip_code_object.cpp      :483 : 34831983138 us: 30   : [tid:0x7f2900de80c0]     hipv4-amdgcn-amd-amdhsa--gfx900 - [code object v4 is amdgcn-amd-amdhsa--gfx900]
:1:hip_code_object.cpp      :483 : 34831983155 us: 30   : [tid:0x7f2900de80c0]     hipv4-amdgcn-amd-amdhsa--gfx906 - [code object v4 is amdgcn-amd-amdhsa--gfx906]
:1:hip_code_object.cpp      :483 : 34831983172 us: 30   : [tid:0x7f2900de80c0]     hipv4-amdgcn-amd-amdhsa--gfx908 - [code object v4 is amdgcn-amd-amdhsa--gfx908]
:1:hip_code_object.cpp      :483 : 34831983198 us: 30   : [tid:0x7f2900de80c0]     hipv4-amdgcn-amd-amdhsa--gfx90a - [code object v4 is amdgcn-amd-amdhsa--gfx90a]
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
Aborted (core dumped)
```

**Comment by gururise** [comment]
Can confirm the same issue on gfx1030 device using PyTorch 1.11.0 (RoCM 5.20) Docker:
```
>>> import torch
>>> torch.cuda.is_available()
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
Aborted (core dumped)
```

**Comment by sunway513** [comment]
Hi @gururise , I'm able to confirm gfx1030 is working as expected on my local dev box:
- reference dockerfile:
```
# Build from a base rocm docker image
FROM rocm/dev-ubuntu-20.04:latest
# Install PyTorch 1.12 whl package fetched from pytorch.org 
RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.1.1
```
- Sample output using the docker container built with it:
```
~/dockerfile_navi21$ drun 1a92498f05d7
root@ixt-sjc2-84:/# cd
root@ixt-sjc2-84:~# ls
root@ixt-sjc2-84:~# import torch
bash: import: command not found
root@ixt-sjc2-84:~# python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```
You can refer to the following document on how to properly install PyTorch-ROCm on supported GPUs:
https://docs.amd.com/bundle/Deep_learning_Guide_5.2/page/Frameworks_Installation_Guide.html

At this moment we have `gfx900, gfx906, gfx908, gfx90a, gfx1030` binary supported in PyTorch WHL package and the dependency libraries.

**Comment by freddybc** [comment]
Hello all,

As clear stated by Unibap, only their versions of ROCm, pyTorch, Tensorflow, pyHIP, etc will work on their products based on AMD APUs.

Do not expect the reglar ROCm or higher order software to work on APUs. They are not officially supported by AMD.

Contact the vendor.
