### ISSUE TITLE
`torch.result_type` does not yield correct type in `torch.autocast()` enabled regions

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#73538]
### 🐛 Describe the bug

# Description

`torch.result_type` incorrectly computes `float32` output within a `torch.autocast()` enabled region

# Repro

```python
import torch

# Creates some tensors in default dtype (here assumed to be float32)
print('Original dtypes')
a_float32 = torch.rand((8, 8), device="cuda")
b_float32 = torch.rand((8, 8), device="cuda")
c_float32 = torch.rand((8, 8), device="cuda")
d_float32 = torch.rand((8, 8), device="cuda")
x_float16 = torch.rand((8, 8), device="cuda").half()

print(a_float32.dtype)
print(b_float32.dtype)
print(c_float32.dtype)
print(d_float32.dtype)

print('\nOutput dtypes within autocast enabled region')
with torch.autocast(device_type='cuda'):
    # torch.mm is on autocast's list of ops that should run in float16.
    # Inputs are float32, but the op runs in float16 and produces float16 output.
    # No manual casts are required.
    e_float16 = torch.mm(a_float32, b_float32)
    assert e_float16.dtype == x_float16.dtype
    # Also handles mixed input types
    f_float16 = torch.mm(d_float32, e_float16)
    assert e_float16.dtype == x_float16.dtype
    # torch.result_type is unaware of autocast's list and fail to compute the right dtype
    i_wrong_float = torch.result_type(a_float32, b_float32)
    assert i_wrong_float == x_float16.dtype
    j_wrong_float = torch.result_type(d_float32, e_float16)
    assert j_wrong_float == x_float16.dtype

print('\nOutput dtypes outside autocast region')
# After exiting autocast, calls f_float16.float() to use with d_float32
g_float32 = torch.mm(d_float32, f_float16.float())
assert g_float32.dtype == d_float32.dtype
# Outside autocast enabled region torch.result_type works as expected
h_float32 = torch.result_type(d_float32, f_float16.float())
assert h_float32 == d_float32.dtype

```

I am willing to help on the fix

### Versions

# Versions
```
Collecting environment information...
PyTorch version: 1.12.0a0+git1e7a4d6
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 15.0.0-++20220222052859+cedc23bc8612-1~exp1~20220222172957.167
CMake version: version 3.19.6
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: Quadro K620

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.12.0a0+git1e7a4d6
[pip3] torchvision==0.13.0.dev20220210+cu111
[conda] blas                      1.0                         mkl  
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] magma-cuda113             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.0            py39h42c9631_2  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] mypy                      0.782                    pypi_0    pypi
[conda] mypy_extensions           0.4.3            py39hf3d152e_4    conda-forge
[conda] numpy                     1.21.4                   pypi_0    pypi
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] torch                     1.12.0a0+git1e7a4d6           dev_0    <develop>
[conda] torchvision               0.13.0.dev20220210+cu111          pypi_0    pypi
```

cc @mcarilli @ptrblck

**Comment by ngimel** [comment]
This is expected behavior, as `result_type` outputs the output type of pointwise operation on its inputs subject to pytorch type promotion rules https://pytorch.org/docs/master/generated/torch.result_type.html?highlight=result_type#torch.result_type. `matmul`, even without autocast, doesn't comply to these type promotion rules.

**Comment by thiagocrepaldi** [comment]
> This is expected behavior, as `result_type` outputs the output type of pointwise operation on its inputs subject to pytorch type promotion rules https://pytorch.org/docs/master/generated/torch.result_type.html?highlight=result_type#torch.result_type. `matmul`, even without autocast, doesn't comply to these type promotion rules.

Thanks for the input @ngimel. From the point of view of the users, does it make sense to compute output's `dtype` based solely on type promotion rules? My understanding is that users want to know the output dtype, regardless of what feature/capability is enabled. By reading the function description (aka `Returns the torch.dtype that would result from performing an arithmetic operation on the provided input tensors`) it seems the aforementioned expectation includes Autocast. 

Maybe Autocast didn't exist when `result_type` was implemented (didn't check that), thus the mention of [type promotion doc](https://pytorch.org/docs/master/tensor_attributes.html#type-promotion-doc) and no mention of [Autocast](https://pytorch.org/docs/stable/amp.html#torch.autocast)?

If indeed this is the desired behavior, I would suggest (or even push a PR) adding a warning note in the doc highlighting the `result_type`'s result may be incorrect when running on a Autocast enabled region.

**Comment by ngimel** [comment]
But it's not just autocast-enabled region, e.g. `mm` on float16/float32 won't work, but `result_type` for float16/float32 will happily output `float32`. Regular pointwise operations (for which `result_type` generally predicts correct result type) will run the same whether in the autocast-enabled region or outside of it, difference is only for ops like `mm`, and `result_type` has only tensor args, not operation arg, so it cannot predict output dtype that depends on the operation.

**Comment by thiagocrepaldi** [comment]
@ngimel yes, ops that do not accept mixed precision out of the box (most of them?) will raise an exception related to the type mismatch. But the same op wrapped by autocast would work properly. This in particular shouldn't be a problem for `result_type`

On the other hand, you brough a great point! `result_type` only take tensors as input, not operator [name].

What do think think about adding a string `op_name` as optional argument, defaulting to None, in which users could use to leverage type inference based on operator name when autocast is enabled?
