### ISSUE TITLE
Forward AD silently loses tangent of dual number tensor subclass

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#73557]
### 🐛 Describe the bug

I was playing around to see if I could simulate multiple levels of forward AD with tensor wrappers but it doesn't work. One reason it doesn't work is that `make_dual` seems to silently lose tangents when you pass a (wrapped) dual tensor as argument to the primal.

```
import torch
from torch.utils._pytree import tree_map
import torch.autograd.forward_ad as fwAD

class WrapperTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, e):
        r = torch.Tensor._make_wrapper_subclass(cls, e.shape, dtype=e.dtype, requires_grad=False)
        r.elem = e 
        return r 

    __torch_function__ = torch._C._disabled_torch_function_impl

    def __str__(self):
        return f'WrapperTensor({self.elem})'

    def __repr__(self):
        return str(self)

    @classmethod
    def __torch_dispatch__(cls, func, types, args=(), kwargs=None):  # type: ignore
        def unwrap(e):
            if isinstance(e, WrapperTensor):
                return e.elem
            else:
                return e 

        def wrap(e):
            if isinstance(e, torch.Tensor):
                return WrapperTensor(e)
            else:
                return e 

        return tree_map(wrap, func(*tree_map(unwrap, args), **tree_map(unwrap, kwargs)))

primal = torch.tensor(1)

with fwAD.dual_level():
    x = fwAD.make_dual(primal, torch.tensor(2))
    y = fwAD.make_dual(WrapperTensor(x), torch.tensor(3))
    print(fwAD.unpack_dual(y))
```

prints

```
UnpackedDualTensor(primal=WrapperTensor(1), tangent=tensor(3))
```

If you delete the WrapperTensor call you get

```
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/foo.py", line 40, in <module>
    y = fwAD.make_dual(x, torch.tensor(3))
  File "/data/users/ezyang/pytorch-tmp/torch/autograd/forward_ad.py", line 73, in make_dual
    return torch._VF._make_dual(tensor, tangent, level=level)
RuntimeError: Making a dual Tensor based on a Tensor that already has a forward gradient at the same level 0 is not supported.
```

which is very reasonable

### Versions

master

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by zou3519** [comment]
This is how composing jvp transforms in functorch works -- jvp(jvp constructs a TensorWrapper(TensorWrapper(x)) where each TensorWrapper has its own tangent and the DynamicLayerStack handles avoiding level confusion

**Comment by soulitzer** [comment]
This is probably happening because we always wrap the wrapped tensor in a fresh wrapper every time but the tangent was on the old wrapper.

**Comment by soulitzer** [comment]
Whoops, actually for the code example in this issue, primal isn't a WrappedTensor, so it's losing the tangent because we're calling alias on the elem when autograd has already been disabled. The reason it works for functorch is that dynamic layer back reenables the autograd key.

**Comment by soulitzer** [comment]
Since we are operating beneath autograd, we actually lose ALL autograd information (e.g. view relationships) for the wrapped tensors, so it is expected that we would also lose the tangent information:
```
x = torch.tensor(1)
wrapped_x = WrapperTensor(x)
wrapped_y = wrapped_x.view_as(wrapped_x)
print(wrapped_y._base is wrapped_x)   # True
print(wrapped_y.elem._base is wrapped_x._base)  # False
```

**Comment by albanD** [comment]
@soulitzer could you edit the code sample above to be what happens? Is it True or False?

**Comment by bdhirsh** [comment]
One thing I'm wondering - PythonTLSSnapshot doesn't let you distinguish between re-entrant dispatcher `::call`s in C++ (e.g. a `CompositeImplicitAutograd` op that calls base ops) vs. re-entrant calls in python (every layer of unwrapping that you would do in a `__torch_dispatch__` wrapper object.

Is it important to be able to distinguish those? It seems like... maybe? For a `CompositeExplicitAutograd` op that decomposes into base ops, you want autograd to run on the composite, but not on the base ops. Which we do now with TLS (by adding the autograd key to the exclude set). But in the presence of python wrapper subclasses, I don't think we want to necessarily "permanently turn off autograd" when we do that.

**Comment by bdhirsh** [comment]
One way to do that (that I just realized actually tries to do something similar to @soulitzer 's referenced commit above) is with side-car TLS:
```
 void pythonFallback(const c10::OperatorHandle& op, torch::jit::Stack* stack) {
   TORCH_INTERNAL_ASSERT(tls_on_entry.size() > 0);
-  c10::impl::ForceDispatchKeyGuard guard(tls_on_entry.top());
+  // keep a side car TLS of "keys that have been excluded at the current python wrapper level,
+  // that need to be reenabled at the next python level" (this would be set in e.g. the autograd or functionalization kernels)
+  auto keys_to_reenable = at::impl::get_excluded_tls_to_reenable_in_python();
+  auto ks_to_force = tls_on_entry.top();
+  if (!exclude_ks.empty()) {
+    ks_to_force.excluded_ = ks_to_force.excluded_ - keys_to_reenable;
+    at::impl::excluded_tls_to_reenable_in_python.set_excluded(c10::DispatchKeySet());
+  }
+  c10::impl::ForceDispatchKeyGuard guard(ks_to_force);
```

**Comment by ezyang** [comment]
Hot take: we should use less TLS (lol) and figure out a way to get all of our internal dispatch passes only using redispatch and stop using exclude key guards

**Comment by albanD** [comment]
To come back to the original question and code sample, I am not sure what the problem is here?
Doing `WrappedTensor(x)` is not a differentiable op in general and so you look requires_grad-ness on x as well as any forward grads.

**Comment by albanD** [comment]
This example shows how to nest this properly: https://github.com/albanD/subclass_zoo/blob/main/nested_forward_ad.py
