### ISSUE TITLE
<c10d/debug.h> included in c10d/ProcessGroup.hpp makes <c10d/ProcessGroup.hpp> unable to expose to users

### ISSUE THREAD

**Issue by jianan-gu** [pytorch/pytorch#73562]
### 🐛 Describe the bug

In the release 1.11 branch https://github.com/pytorch/pytorch/commits/release/1.11

1.  <c10d/ProcessGroup.hpp> is supposed to expose to users
2.  <c10d/ProcessGroup.hpp> recently added include files <c10d/debug.h> in this [commit](https://github.com/pytorch/pytorch/commit/055052bf64ab9ed6196324df38c03107c574f1fe), while <c10d/debug.h> is not exposed to users
      _pytorch/torch/include/c10d/ProcessGroup.hpp:15:10: fatal error: c10d/debug.h: No such file or directory
       15 | #include <c10d/debug.h>
      |          ^~~~~~~~~~~~~~
       compilation terminated._

Based on 1 and 2,  <c10d/ProcessGroup.hpp>  is no longer be compiled with user's code.
Here got a crucial question:
     Is it expected that <c10d/debug.h> is not exposed to users, or will it be available?

### Versions

 python collect_env.py

Collecting environment information...
PyTorch version: 1.11.0a0+gita556333
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.10

Python version: 3.7.7 (default, Mar 26 2020, 15:48:22)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-27-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.10.0+cpu
[pip3] numpy==1.21.2
[pip3] torch==1.11.0a0+gita556333
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl    intel
[conda] mkl                       2021.4.0              intel_640    intel
[conda] mkl-include               2022.0.1              intel_117    intel
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.2           py37h20f2e39_0
[conda] numpy-base                1.21.2           py37h79a1101_0
[conda] torchvision               0.11.3                    <pip>

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by pritamdamania87** [comment]
@jianan-gu Is this part of the bazel build and would https://github.com/pytorch/pytorch/pull/73629 resolve your problem? If not, could you provide some more details about how you are building?

cc @cbalioglu

**Comment by jianan-gu** [comment]
Thanks, @pritamdamania87 , this https://github.com/pytorch/pytorch/pull/73629 did solve the issue here.

**Comment by pritamdamania87** [comment]
@jianan-gu It looks like https://github.com/pytorch/pytorch/pull/73629 was closed but not really committed in the repo, are you able to build fine in PyTorch master despite https://github.com/pytorch/pytorch/pull/73629 not being committed?

**Comment by jianan-gu** [comment]
Hi @pritamdamania87,   https://github.com/pytorch/pytorch/pull/73629 was closed because this commit https://github.com/pytorch/pytorch/commit/46f85865c09be6af232015a539f5260fe3ac344b was landed in the "release/1.11" repo and fixed this issue (works fine with the building). Thanks for your double-check.
