### ISSUE TITLE
C++ ModuleList/ModuleDict segfault with at<ModuleType>() method

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#73565]
### 🐛 Describe the bug

The at<ModuleType>() method of ModuleList and ModuleDict containers both dereference a null pointer if specified type does not match containted type.

in nn/modules/container/modulelist.h

```
  /// Attempts to return the module at the given index as the requested type.
  /// Throws an exception if the index is out of bounds or the types do not
  /// match.
  template <typename T>
  T& at(size_t index) {
    static_assert(
        torch::detail::is_module<T>::value,
        "Can only call ModuleList::at with an nn::Module type");
    TORCH_CHECK(index < size(), "Index out of range");
    return *modules_[index]->as<T>();
  }
```

To reproduce:

```
 torch::nn::ModuleList m( torch::nn::Linear(1,2) );
 std::cerr << m->at<torch::nn::LinearImpl>(0) << "\n";
 std::cerr << m->at<torch::nn::SequentialImpl>(0) << "\n";
```
The second print attempt will segfault.

Maybe replace the last line with something like:

```
 auto *p=modules_[index]->as<T>();
 TORCH_CHECK(p, "Unable to cast module[",index,"] to ",c10::demangle(typeid(T).name()));
 return *p;
```

### Versions

I think this bug is in all libtorch versions since ModuleList & ModuleDict were added

cc @ezyang @gchanan @zou3519 @jbschlosser

**Comment by jbschlosser** [comment]
Hey @meganset, thanks for the report! We'd accept a PR fixing adding the check if you'd like to contribute.
