### ISSUE TITLE
`torch.msort` is not consistent with `torch.sort`

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#73561]
### 🐛 Describe the bug

Based on the documentation of `torch.msort`, `torch.msort(t)` is equivalent to `torch.sort(t, dim=0)[0]`. However, when the the input tensor's 0-dimension is 0, this fails

```python
import torch
results = dict()
input = torch.rand([0, 1, 1], dtype=torch.float64)
torch.msort(input)
# tensor([], size=(0, 1, 1), dtype=torch.float64)
torch.argmax(input, dim=0)
# IndexError: argmax(): Expected reduction dim 0 to have non-zero size.
```

### Versions

pytorch: 1.10.1

**Comment by albanD** [comment]
Hi,

I am not sure to follow? You compared msort and argmax here?
Also is there a specific reason for you to use an empty Tensor (one of the size is 0).

**Comment by TestSomething22** [comment]
So sorry for my mistake. Let me close it.
