### ISSUE TITLE
Add torch.distributions.MultivariateNormalDiag

### ISSUE THREAD

**Issue by xiaomengy** [pytorch/pytorch#73582]
### 🚀 The feature, motivation and pitch

Currently in torch.distributions we only have torch.distributions.MultivariateNormal which needs to pass the full covariance_matrix. While in a lot of cases, we just need the multivariate normal distributions with all of the dimensions independent to each other. In that case the covariance_matrix is a diagonal matrix. So it will be much more convenient to have torch.distributions.MultivariateNormalDiag which received a scale_diag as argument. 

If we have that for this special case, the computation for sample, log_prob and entropy can be also much more efficient.

`dist = torch.torch.distributions.MultivariateNormal(mean, torch.diag(std.square());`
vs
`dist = torch.torch.distributions.MultivariateNormalDiag(mean, std);`

### Alternatives

In Tensorflow there is [tfp.distributions.MultivariateNormalDiag](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalDiag)

Currently we can also use torch.distributions.Normal to simulate it. When compute log_prob and entropy, we can sum up the values in each dimension.

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by fritzo** [comment]
For diagonal covariance matrix, use `Independent(Normal(mean, cov_diag.sqrt()), 1)`, See [Independent](https://pytorch.org/docs/stable/distributions.html#independent).
