### ISSUE TITLE
Deterministic indexing operation fails in indices size check

### ISSUE THREAD

**Issue by Rediness** [pytorch/pytorch#73587]
### 🐛 Describe the bug

Similar to this solved [bug](https://github.com/pytorch/pytorch/issues/61032).

# To Reproduce

```python
import torch
torch.use_deterministic_algorithms(True)

x = torch.arange(2).float().cuda()
x[torch.arange(2)] = 1.

""" Output:
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == value.numel()INTERNAL 
ASSERT FAILED at "C:\\cb\\pytorch_1000000000000\\work\\aten\\src\\ATen\\native\\cuda\\Indexing.cu":250,
please report a bug to PyTorch.
number of flattened indices did not match number of elements in the value tensor21
"""

```
## Additional context

The code runs fine when using torch.use_deterministic_algorithms(False).

### Versions

Pytorch 1.10.2 and Cuda toolkit version 11.3. I basically ran the following command in windows 10:
```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```

**Comment by ngimel** [comment]
Fixed on master/nightlies/1.11, please reopen if you still see the issue
