### ISSUE TITLE
Skip ROCm test using profiler due to latest Kineto Submodule Update

### ISSUE THREAD

**Issue by aaronenyeshi** [pytorch/pytorch#73588]
### 📚 The doc issue

The latest Kineto submodule update will cause some ROCm tests to fail when using torch.profiler.profile. This submodule update can be found here: https://github.com/pytorch/pytorch/pull/73090

There is a segmentation fault found in `test_norm_fusing_type_promotion_cuda_bfloat16` when updating the Kineto Submodule. The test will be skipped to unblock the submodule update of the Kineto component, due to several high priority asks to bring Kineto in sync on PyTorch (S261074). 

Once the bug is fixed, we can re-enable the failing tests.

Logs:
https://github.com/pytorch/pytorch/runs/5327147129?check_suite_focus=true

Log Snippet:
```
2022-02-25T04:12:45.9723334Z   test_norm_fused_type_promotion_cuda_bfloat16 (__main__.TestLinalgCUDA) ... Traceback (most recent call last):
2022-02-25T04:12:45.9725005Z   File "test/run_test.py", line 1106, in <module>
2022-02-25T04:12:45.9735275Z     main()
2022-02-25T04:12:45.9736419Z   File "test/run_test.py", line 1084, in main
2022-02-25T04:12:45.9737545Z     raise RuntimeError(err_message)
2022-02-25T04:12:45.9738517Z RuntimeError: test_linalg failed! Received signal: SIGSEGV
```

### Suggest a potential alternative/fix

- Skip the failing ROCm test, to unblock the submodule update of third_party/kineto.
- Investigate the ROCm test failure (find root cause, and fix)
- Re-enable the ROCm test after fixes are submitted.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by aaronenyeshi** [comment]
Jeff and Michael from AMD are looking into the issue.

**Comment by aaronenyeshi** [comment]
There are many distributed tests that rely on profiler. So I don't want to disable all of them. That may introduce more regressions from other patches.

**Comment by mwootton** [comment]
Reverted the breaking change and cleaned up a bit in:
https://github.com/pytorch/kineto/pull/553

**Comment by aaronenyeshi** [comment]
Thanks @mwootton , this issue is fixed.
