### ISSUE TITLE
Develop Required Status Checks/MergeQueue

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73657]
As we are moving towards GitHub First (GH1), we want to be able to use a merge queue to validate commits as they land. However, before we get to a merge queue, we should start with required status checks!

https://docs.google.com/document/d/1emBy5I_yeEch6FXfiDjzeh56e5qv4MIB8fhooU_00HY/edit for context

Milestones:
- [x] Test viability MergeQueue beta available from GitHub on pytorch/canary. --> GH mergequeue is not compatible with ghstack
- [x] Start with required status checks 

--- PUNTED TO NEXT HALF
- [ ] Design custom MergeQueue
- [ ] Solution available for both ghstack and non-ghstack commits
- [ ] Solution tested and stabilized

**Comment by dagitses** [comment]
This issue does not require triage.

**Comment by janeyx99** [comment]
We finished required status checks + now have close to 0 reverts due to ignored signal! 

MergeQueue has been replaced with the idea of land checks + shifting viable/strict to be trunk: https://docs.google.com/document/d/1mgmT1hmn5qSOl4yeW5BNFKkA_lWpleNTmMBhwcj0JxY/edit#heading=h.3dp8p9qnuk5t
