### ISSUE TITLE
Add functionality to allow a comment to rebase a PR

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73658]
cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
@clee2000 feel free to update progress here!

**Comment by clee2000** [comment]
PR with python scripts for GHA: https://github.com/pytorch/pytorch/pull/76262
PR in test-infra for probot: https://github.com/pytorch/test-infra/pull/305 
For testing: https://github.com/pytorch/pytorch/pull/76448

**Comment by clee2000** [comment]
https://github.com/pytorch/test-infra/pull/346 - pr author and anyone in the pytorch org can rebase the pr
https://github.com/pytorch/pytorch/pull/77911 - should work on ghstack

**Comment by suo** [comment]
this is done right
