### ISSUE TITLE
Release pytorch docker images with newer python versions

### ISSUE THREAD

**Issue by henridwyer** [pytorch/pytorch#73714]
### 🚀 The feature, motivation and pitch

Currently the most recent pytorch docker images published to docker hub (https://hub.docker.com/r/pytorch/pytorch/tags) uses python 3.7.

Projects like numpy or pandas have dropped support for python 3.7 in their newer releases. It would be great to able to use the pre-built torch container with the lastest versions of packages from the ecosystem.

### Additional context

Additionally, it would be useful to tag the docker releases with the python version.

**Comment by henridwyer** [comment]
@seemethere since you seem to have done most recent pytorch docker releases

**Comment by malfet** [comment]
Makes sense, @atalman can you please update the script to pick say 3.8 or 3.9?

**Comment by damonmaria** [comment]
Linking to other issues reporting the same: #68055, #60932.

**Comment by tsteffek** [comment]
The latest `pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel` now even went back from python 3.8 in `pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel` to 3.7 again. I'm having a hard time imagining that's intentional, but I'm also reluctant to create yet another "python version in docker is outdated" issue.

**Comment by TC4476** [comment]
Anyone figured out how to fix this issue with the python version in the latest `pytorch/pytorch:1.12.0-cuda11.3-cudnn8-devel` ? Can we take this as a base image and reinstall a newer python version like 3.8/3.9 to get a modified image?

**Comment by vvsotnikov** [comment]
Any updates on this one?

**Comment by JonathanRayner** [comment]
Would love to see a bump to ubuntu 22.04 and python 3.10 . These versions are lagging behind quite far now... Happy to help if needed to speed it up.

**Comment by abrayne** [comment]
Any update on this?

**Comment by JonathanRayner** [comment]
For those who don't care about building from source, the nividia base image `FROM nvidia/cuda:11.7.0-devel-ubuntu22.04` and `pip install torch` may help. (may need to install `python3` in the image as well, I can't remember)

**Comment by mattpopovich** [comment]
For anyone curious, here are the bundled Python versions in different [PyTorch containers](https://hub.docker.com/r/pytorch/pytorch/tags):
| Python | PyTorch |
| ----------|-------------|
| 3.10.8 | 1.13.1| 
| 3.9.12 | 1.13.0 | 
| 3.7.13 | 1.12.1| 
| 3.7.13 | 1.12.0 |
| 3.8.12 | 1.11.0|
| 3.7.11 | 1.9.1 | 
| 3.8.8 | 1.8.0 | 
| 3.8.3 | 1.7.0 | 

Not an exhaustive list as those were just PyTorch containers I already had downloaded on my machine. 

As we finally have Python 3.9 and 3.10 in the newest versions of PyTorch, I think we can close this issue.

**Comment by escape0707** [comment]
The latest PyTorch docker images are built on Ubuntu 18.04 which has reached its end of life. It's glibc is also so old that I can't copy and run vscode-cli into it for remote development, especially with Apptainer or maybe Podman as a container platform.

Please consider also upgrading to Ubuntu 22.04.

**Comment by radry** [comment]
Please update the pytorch docker image to python 3.11

**Comment by xiachenrui** [comment]
Yeah, We need Python 3.11 !

**Comment by UFO-101** [comment]
3.11 done 🎉

**Comment by SamORichards** [comment]
> 3.11 done 🎉

Which image tag is this?

**Comment by zxzjim** [comment]
> > 3.11 done 🎉
> 
> Which image tag is this?

same question, 3.10 still in the latest or the pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime?

**Comment by UFO-101** [comment]
I don't know actually. I just noticed this was closed as completed.

**Comment by Luciennnnnnn** [comment]
So what's the python version of pytorch/pytorch:2.4.1-cuda11.8-cudnn9-devel? We need python version on tag name

**Comment by grzegorz700** [comment]
> So what's the python version of pytorch/pytorch:2.4.1-cuda11.8-cudnn9-devel? We need python version on tag name

Python 3.11.  Yeah, Including a python version tag will be great.
