### ISSUE TITLE
Cannot load faster-rcnn model with libtorch in C++

### ISSUE THREAD

**Issue by DrChuan** [pytorch/pytorch#73735]
### 🐛 Describe the bug

I cannot load the model which is generated by torch.jit.trace in C++ with libtorch. The model is faster-RCNN archetechture. Pytorch version is 1.2.0 (I've also tried with 1.7.0). 

The error message is `ASSERT FAILED at "..\\..\\torch\\csrc\\jit\\frontend\\schema_matching.cpp":520, please report a bug to Pytorch".`. Nothing more can I get.

```python
import torch
import torchvision
from faster_rcnn.frcnn import FRCNN

# An instance of your model.
frcnn = FRCNN()
model = frcnn.net

# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 224, 224)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)
traced_script_module.save("model.pt")
```

```c++
#include <torch/script.h> // One-stop header.
#include <iostream>
#include <memory>

int main() {
	torch::jit::script::Module module;
	try {
		// Deserialize the ScriptModule from a file using torch::jit::load().
		module = torch::jit::load("model.pt");
	}
	catch (const c10::Error& e) {
		std::cout << "error loading the model\n";
		return -1;
	}

	std::cout << "ok\n";
}
```

### Versions

Collecting environment information...
Traceback (most recent call last):
  File ".\t.py", line 475, in <module>
    main()
  File ".\t.py", line 458, in main
    output = get_pretty_env_info()
  File ".\t.py", line 453, in get_pretty_env_info
    return pretty_str(get_env_info())
  File ".\t.py", line 346, in get_env_info
    is_xnnpack_available=is_xnnpack_available(),
  File ".\t.py", line 297, in is_xnnpack_available
    import torch.backends.xnnpack
ModuleNotFoundError: No module named 'torch.backends.xnnpack'

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
