### ISSUE TITLE
torch.jit.trace will fail on nn.Module with nn.ParameterList

### ISSUE THREAD

**Issue by zhuhaozhe** [pytorch/pytorch#73737]
### 🐛 Describe the bug

Module with ParameterList
```python
import torch
from torch import nn as nn

class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.weights = torch.nn.ParameterList([nn.Parameter(torch.randn(1)) for i in range(10)])

    def forward(self, x):
        return x

m = M()
torch.jit.trace(m, torch.randn(1))
```

will be failed to trace
```
Traceback (most recent call last):
  File "test_trace.py", line 13, in <module>
    torch.jit.trace(m, torch.randn(1))
  File "/home/haozhe/rebase/frameworks.ai.pytorch.private-cpu/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/haozhe/rebase/frameworks.ai.pytorch.private-cpu/torch/jit/_trace.py", line 942, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/haozhe/rebase/frameworks.ai.pytorch.private-cpu/torch/jit/_trace.py", line 568, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/haozhe/rebase/frameworks.ai.pytorch.private-cpu/torch/jit/_trace.py", line 1067, in __init__
    tmp_module._modules[name] = make_module(
  File "/home/haozhe/rebase/frameworks.ai.pytorch.private-cpu/torch/jit/_trace.py", line 556, in make_module
    elif torch._jit_internal.module_has_exports(mod):
  File "/home/haozhe/rebase/frameworks.ai.pytorch.private-cpu/torch/_jit_internal.py", line 675, in module_has_exports
    if hasattr(mod, name):
TypeError: hasattr(): attribute name must be string
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+gitf94b9e3
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.10.0+cpu
[pip3] numpy==1.21.2
[pip3] pytorch-widedeep==1.0.0
[pip3] torch==1.12.0a0+git539acb2
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.12.0a0+c6c1fb6
[conda] intel-extension-for-pytorch 1.10.0+cpu                dev_0    <develop>
[conda] mkl                       2022.0.1           h06a4308_117  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] numpy                     1.21.2           py38hd8d4704_0  
[conda] numpy-base                1.21.2           py38h2b8c604_0  
[conda] pytorch-widedeep          1.0.0                     dev_0    <develop>
[conda] torch                     1.12.0a0+git539acb2           dev_0    <develop>
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.12.0a0+c6c1fb6           dev_0    <develop>

It is likely caused by this PR https://github.com/pytorch/pytorch/pull/70499.

The method "__dir__" of "ParameterList" is changed, the returned value will be int (0, 1, 2, ..., n) and cannot be passed to "hasattr" function since it only accepts "str".
https://github.com/pytorch/pytorch/blob/20a037d80f51a74aabbcd305f2f3e3b55d41dd85/torch/_jit_internal.py#L674-L675

**Comment by davidberard98** [comment]
I think this is fixed by https://github.com/pytorch/pytorch/pull/74997, please reopen if not
