### ISSUE TITLE
Allow LTC to handle special scalars (0, 1) differently

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#73756]
### 🚀 The feature, motivation and pitch

Allowing handling special scalar for the TS backend generates `aten::ScalarImplicit` in the TS graph which will call `.item()` and cause a DtoH data sync. As a quick fix, I disabled that special scalar handling in https://github.com/pytorch/pytorch/pull/73580, which showed [a substantial perf gain](https://docs.google.com/spreadsheets/d/1lU0tgJDLuIcJDe0rrPcfG7GVQCNCn8qoTYEbXgCdxr0/edit#gid=1180267319) .

On the other hand, if we burn those special scalar into the TS graph, we would be able to simplify something like `a+b*1` into `a+b`. @Krovatkin measured this [microbenchmark](https://gitlab.com/-/snippets/2264468) and found about 10% perf gain on A100. So this is a potential performance optimization if we can turn the special scalar handling in LTC back on.

**Comment by Krovatkin** [comment]
👍

**Comment by desertfire** [comment]
deprioritize
