### ISSUE TITLE
Poor performance when chaining operations

### ISSUE THREAD

**Issue by mwmuni** [pytorch/pytorch#73779]
## Issue description

There appears to be a problem when PyTorch tensors are resolving chained operators. Instead of performing the operation all at once, it appears to do them sequentially.

## Code example

```python3
import torch
from timeit import default_timer as timer

vals = torch.arange(1, 10000000, 1).cuda() # Create an array of values
times_tadd = []
times_add = []
times_seq = []
times_pre = []
loops = 10
loops_per_type = 100

for _ in range(loops):
    
    # Using torch add
    s_tadd = timer()
    for _ in range(loops_per_type):
        _vals = torch.add(vals, 10 + 10 + 10)
    e_tadd = timer()
    times_tadd.append([s_tadd, e_tadd])

    # Chaining the operations in a single line
    s_add = timer()
    for _ in range(loops_per_type):
        _vals = vals + 10 + 10 + 10
    e_add = timer()
    times_add.append([s_add, e_add])

    # Performing the operations sequentially
    s_seq = timer()
    for _ in range(loops_per_type):
        _vals = vals + 10
        _vals = _vals + 10
        _vals = _vals + 10  
    e_seq = timer()
    times_seq.append([s_seq, e_seq])

    # Adding the numbers separately first
    s_pre = timer()
    for _ in range(loops_per_type):
        precompute = 10 + 10 + 10
        _vals = vals + precompute
    e_pre = timer()
    times_pre.append([s_pre, e_pre])
    
times_tadd = torch.tensor(times_tadd)
times_add = torch.tensor(times_add)
times_seq = torch.tensor(times_seq)
times_pre = torch.tensor(times_pre)

print('tadd', torch.mean(times_tadd[:, 1] - times_tadd[:, 0]))
print('add', torch.mean(times_add[:, 1] - times_add[:, 0]))
print('seq', torch.mean(times_seq[:, 1] - times_seq[:, 0]))
print('pre', torch.mean(times_pre[:, 1] - times_pre[:, 0]))
```

tadd tensor(0.0252)
add tensor(0.0801)
seq tensor(0.0838)
pre tensor(0.0277)

Changing the offending line to:

```python3
_vals = 10 + 10 + 10 + vals
```

Fixes the issue with the times showing:

tadd tensor(0.0250)
add tensor(0.0244)
seq tensor(0.0773)
pre tensor(0.0281)

## System Info
PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 511.79
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.10.2
[pip3] torch-tb-profiler==0.3.1
[pip3] torchaudio==0.10.2
[pip3] torchvision==0.11.3
[conda] Could not collect

**Comment by mruberry** [comment]
This analysis is correct and expected. PyTorch executes each operation eagerly so in some cases this is performing one tensor x scalar operation, and in other cases the above performs multiple tensor x scalar operations to compute the same result.
