### ISSUE TITLE
Investigate default auto_wrap_policy

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#73809]
### 🚀 The feature, motivation and pitch

Currently, FSDP does not recursively wrap submodules by default, which can result in some usability issues as all users will have to figure out a wrapping policy for their use case or manually annotate some models with wrap(). 

We could run some experiments on key workloads and come up with a general policy, perhaps based on # of parameters to wrap, that appropriately trades off performance with memory saving goals and is ideal for a wide variety of workloads, and then recursively wrap FSDP with this policy by default.

This approach is similar to DDP bucketing where default size of 25 mb works well for many applications via experimentation.

One issue is backwards compatibility, i.e. using recursive wrap with policy by default might break enable_wrap + wrap() API approach.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
I am marking this as not planned because deciding a default policy is a known and challenging problem. We do not have a good solution.
