### ISSUE TITLE
AArch64 Python 3.10 wheel accidentally released?

### ISSUE THREAD

**Issue by connorbrinton** [pytorch/pytorch#73813]
### 🐛 Describe the bug

Hi, I recently noticed that there is a Python 3.10 AArch64 wheel uploaded to PyPI for Torch 1.10.2:
https://pypi.org/project/torch/1.10.2/#files

I've read elsewhere that Python 3.10 support [won't be backported](https://github.com/pytorch/pytorch/issues/71632#issuecomment-1018706501) to the 1.10.x series. Perhaps an in-development CI job for Python 3.10 support was accidentally triggered during the 1.10.2 release process?

I don't have any stake in the matter, I was just naively trying to install in a Python 3.10 virtual environment and noticed the 3.10 wheel while I was debugging my issues. Thanks for maintaining PyTorch! 😄

### Versions

N/A

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
One can try Python-3.10 wheels for the upcoming 1.11 release from https://download.pytorch.org/whl/test/

**Comment by seemethere** [comment]
Going to go ahead and close this since we've decided on keeping the binary on pypi.

Thanks for the report though!
