### ISSUE TITLE
ci: Check if docker daemon is running and start it if it isn't

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#73859]
Some workflows currently fail with the following message: ([example](https://github.com/pytorch/pytorch/runs/5450990477?check_suite_focus=true))
<img width="1197" alt="Screen Shot 2022-03-07 at 10 15 59 AM" src="https://user-images.githubusercontent.com/1700823/157093611-01147ee3-7b80-4951-8c62-d2ec9f390ca8.png">

We should add a check / step to our EC2 linux setup common scripts see if the docker daemon is currently running using `systemctl is-active --quiet docker` and then use `sudo systemctl start docker` if it isn't currently running.

Change can probably be added as a separate step here:

https://github.com/pytorch/pytorch/blob/a3d099ea18043d64d873dd83f344f95765a875d3/.github/templates/common.yml.j2#L97-L125

To be done prior to ECR login so that ECR login should work as expected (which relies on the docker daemon).

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by mehtanirav** [comment]
@seemethere Thanks for adding details on the task. I will work on it.

**Comment by janeyx99** [comment]
closing as this is done by #73987
