### ISSUE TITLE
Tensor._version isn't updated when wrapped in a Parameter

### ISSUE THREAD

**Issue by cbcase** [pytorch/pytorch#7386]
## Issue description

When you perform an in-place operation on a `torch.Tensor` that's been wrapped in a `torch.nn.Parameter`, its version counter isn't bumped -- I'd expect that it would be incremented just as if you'd acted in-place on a raw tensor.

(I recognize `Tensor._version` is an internal detail, but it's really useful!)

## Code example

```python
x = torch.randn(3,)
x.add_(1.)
print(x._version)
# prints "1" -- expected

p = torch.nn.Parameter(torch.randn(3,))
p.data.add_(1.)
print(p.data._version)
# prints "0" -- "1" is expected
```

## System Info
Collecting environment information...
PyTorch version: 0.5.0a0+9ed46c6
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Graphics Device

Nvidia driver version: 387.34
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] numpydoc (0.8.0)
[pip] torch (0.5.0a0+9ed46c6)
[pip] torchtext (0.2.3)
[pip] torchvision (0.2.0)
[conda] magma-cuda90              2.3.0                         1    soumith
[conda] torch                     0.5.0a0+9ed46c6           <pip>
[conda] torchtext                 0.2.3                     <pip>
[conda] torchvision               0.2.0                     <pip>

**Comment by SsnL** [comment]
Everytime you call `._data` it creates a new `Tensor` that shares storage but not the version counter.

**Comment by cbcase** [comment]
Got it, thanks!

**Comment by SsnL** [comment]
So this works :):
```py
>>> import torch
>>> p = torch.nn.Parameter(torch.randn(3,))
>>> p.data.add_(1.)
tensor([ 1.3256,  0.9762,  1.7450])
>>> print(p.data._version)
0
>>> x = p.data
>>> x.add_(1.)
tensor([ 2.3256,  1.9762,  2.7450])
>>> x._version
1
```

**Comment by cbcase** [comment]
Hah, that's pretty great :).

My interest is in caching casted or otherwise-manipulated versions of model weights -- and using the `._version` attribute to know when to invalidate the cache. Since the in-place update is (in general) outside my control -- mostly it's inside the `optim` classes -- I won't be able to use this trick.

I think for now I'll need to force the user to explicitly tell me when an optimizer update happens to mark cached weights as dirty. (I can  imagine doing something w/ hooks, too, but that feels...very fragile.)

Anyway, seeing as the tensor version isn't actually a part of the API, can't complain. Though if you guys consider ever making it so, I think this is pretty surprising behavior :)
