### ISSUE TITLE
ONNX: Document public API for shape inference for custom symbolics

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#73871]
(forked from #34342)

There's already an API for custom ops to specify output shapes, though I it's not public and not documented. Example usage:

https://github.com/microsoft/onnxruntime/blob/e788cc2a2370946977b91b2456166d466df4d14a/orttraining/orttraining/python/training/ortmodule/_custom_op_symbolic_registry.py#L69

This issue tracks making it public and documented.

Tracked internally at Microsoft by <https://msdata.visualstudio.com/Vienna/_workitems/edit/1691059>

**Comment by thiagocrepaldi** [comment]
This is still a valid documentation issue
