### ISSUE TITLE
Both HUDs (HUD 1 and HUD 2) down

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#73880]
## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.
ongoing, please use https://www.torch-ci.com/

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
Both HUD1 and HUD2 are inaccessible:
hud2.pytorch.org:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/31798555/157123235-e4a7513b-c134-411b-8e94-46b2dd6a50a8.png">
hud.pytorch.org:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/31798555/157123315-f09c8a0b-a802-4bf5-ad22-434e5a775e2c.png">

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*
Normal HUD links unusable. Please use https://www.torch-ci.com/!

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*
* Let's announce and give heads up when we're switching over HUDs
* Could we do a rollout/beta testing as we're doing this?

**Comment by seemethere** [comment]
Both appear to be back up now, closing.
