### ISSUE TITLE
[FSDP] summon_full_params + named_params clean full path

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#73890]
#### Clean full path of parameters

- summon_full_params() makes sure that FSDP model .parameters() method works properly i.e. it is the same as local model, see `test_params_count_and_value` in https://github.com/pytorch/pytorch/blob/master/test%2Fdistributed%2Ffsdp%2Ftest_fsdp_summon_full_params.py. However, this is not true for the named counterpart `named_parameters` as the name is not as expected. To reproduce this, see the following patch to `test_params_are_unflattened`: https://gist.github.com/rohan-varma/5e3c306a51b3c4dacd0a96bb7635db99

This results in the following: 
```
name: _fsdp_wrapped_module._fpw_module.weight param shape torch.Size([12, 10])
```

but for local model, the name is just `weight`. 

this basically means that from out to inside summon_full_params context, the name changes `'_fsdp_wrapped_module.flat_param'` -> ` _fsdp_wrapped_module._fpw_module.weight` which makes sense since summon_full_parameters is implemented by rebuilding the full param and unflattening the `FlattenParamsWrapper` module.

To fix this, we could patch `named_parameters()` to strip the appropriate prefix when in a summon_full_params context.

### Versions

main

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/74333
