### ISSUE TITLE
`torch.amax` and `torch.amin` returns random values, if `dim` arg is not provided

### ISSUE THREAD

**Issue by khushi-411** [pytorch/pytorch#73905]
### 🐛 Describe the bug

1. `torch.amax` and `torch.amin` will return random values for empty tensors if `dim` arg is not provided. See:
```python
In [10]: k = torch.rand([0, 3])  # empty tensor; tensor([], size=(0, 3))

In [17]: torch.amax(k)
Out[17]: tensor(-5.9405e-18)

In [18]: torch.amin(k)
Out[18]: tensor(-1.2214e+14)
```
In contrast, as [documented](https://pytorch.org/docs/stable/generated/torch.amax.html); `torch.amax` and `torch.amin` should be similar to `torch.max/min` and hence, I think it should raise error.

2. `torch.max` and `torch.min` throws an error as shown
```python
In [10]: k = torch.rand([0, 3])

In [19]: torch.max(k)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-19-726f94840b3a> in <module>
----> 1 torch.max(k)

RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

```
3. `numpy` for empty arrays with no dim arg will throw the following error:
```python
In [21]: a = numpy.empty([0, 3])

In [23]: numpy.amax(a)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-ab83e49e8deb> in <module>
----> 1 numpy.amax(a)

<__array_function__ internals> in amax(*args, **kwargs)

~/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial, where)
   2731     5
   2732     """
-> 2733     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
   2734                           keepdims=keepdims, initial=initial, where=where)
   2735 

~/anaconda3/lib/python3.8/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86 
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88 
     89 

ValueError: zero-size array to reduction operation maximum which has no identity
```
Similar output in `numpy.amin`, `numpy.max`, and `numpy.min`.

#### NOTE
`torch.{amax, amin, max, min}` works fine (similar to NumPy) if dim arg is given. They return an empty tensor.

### Possible Fixes
I think `torch.amax` and `torch.amin` should throw an error.

### Versions

PyTorch version: `1.11.0.dev20220103`

cc @mruberry @rgommers @kshitij12345! :)

**Comment by MattiaSarti** [comment]
I'd like to work on this issue

**Comment by khushi-411** [comment]
Hey, @MattiaSarti! Thanks for your interest. Unfortunately, I had already started working on this locally. See #73914
Could you pick some other exciting issue in PyTorch? Thanks :)

**Comment by MattiaSarti** [comment]
Sure, @khushi-411
