### ISSUE TITLE
No option for Keyword Arguments (**kwargs) in torch.multiprocessing.spawn

### ISSUE THREAD

**Issue by Mob97** [pytorch/pytorch#73902]
### 🚀 The feature, motivation and pitch

I have a function like this:
`
def foo(a, b, **kwargs):
    pass
`
I read the document and see no option for the **Keyword Arguments**.
How can I deal with this by using mp.spawn?

Thank you!

### Alternatives

Python multiprocessing library have kwargs option:
`class multiprocessing.Process(group=None, target=None, name=None, args=(), kwargs={}, *, daemon=None)`

cc @VitalyFedyunin

**Comment by VitalyFedyunin** [comment]
As far is I remember we do not overload and drop any native [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) arguments and `kwargs = {}` should work just fine.

**Comment by philip-bl** [comment]
Actually, `torch.multiprocessing.spawn` doesn't work with kwargs, so this should be reopened. `torch.multiprocessing.spawn(worker, nprocs=3, join=True, kwargs={"foo": "bar"})` results in `TypeError: spawn() got an unexpected keyword argument 'kwargs'`

**Comment by jeffpicard** [comment]
I'd also love kwargs to be passed through to avoid ugly workarounds. It looks like it might be a straightforward fix [here](https://github.com/pytorch/pytorch/blob/main/torch/multiprocessing/spawn.py#L258) too.
