### ISSUE TITLE
Libtorch dosen't has the function like python api (TORCH.SET_PRINTOPTIONS) 

### ISSUE THREAD

**Issue by majestichou** [pytorch/pytorch#73911]
### 🚀 The feature, motivation and pitch

Libtorch (C++ API of pytorch)  dosen't has the function that can set the precision of output number like python api (TORCH.SET_PRINTOPTIONS) .
For example:
```
torch::Tensor a = torch::randint(0, 5, {2, 2}, torch::kDouble);
auto b = torch::randint(5, 10, {2, 2}, torch::kDouble);
auto c = torch::complex(a, b);
std::cout << "the complex real and img is :" << std::endl;
std::cout << torch::real(c) << std::endl;
std::cout << torch::imag(c) << std::endl;
std::cout << " the abs is : " << std::endl;
std::cout << torch::abs(c) << std::endl;
```
the out put is as follows:
![image](https://user-images.githubusercontent.com/43713443/157200423-51a56c50-f25a-443c-8927-bee64c04b572.png)
the abs of complex number is quoted in four decimal places. But I want make the result  quoted in ten decimal places. In current API， I can't do this.
Thanks a lot.

### Alternatives

Libtorch provides the api like python api (TORCH.SET_PRINTOPTIONS) in the future.

cc @jbschlosser

**Comment by jbschlosser** [comment]
Hey @majestichou, thanks for the request! As you mentioned, the precision is currently hard-coded to 4 here:
https://github.com/pytorch/pytorch/blob/39470387cf17896cf38f3e04b5b81d4647734275/aten/src/ATen/core/Formatting.cpp#L102-L125

Fair warning that maintenance of the C++-side API is currently a low priority, so it's unlikely this will be addressed soon, but I think we'd accept a PR adding the equivalent of `set_printoptions` on the C++ side.

**Comment by majestichou** [comment]
> Hey @majestichou, thanks for the request! As you mentioned, the precision is currently hard-coded to 4 here:
> 
> https://github.com/pytorch/pytorch/blob/39470387cf17896cf38f3e04b5b81d4647734275/aten/src/ATen/core/Formatting.cpp#L102-L125
> 
> Fair warning that maintenance of the C++-side API is currently a low priority, so it's unlikely this will be addressed soon, but I think we'd accept a PR adding the equivalent of `set_printoptions` on the C++ side.

Thank a alot!

**Comment by iustinouatu** [comment]
Has this been resolved? If so, how can one set the print precision? Thanks!

**Comment by majestichou** [comment]
您好：
   您发给我的信件已经收到。
   这是邮件系统自动回复。

                             侯宏伟
