### ISSUE TITLE
Adam optimizer doesn't work with CyclicLR scheduler but works with OneCycleLR.

### ISSUE THREAD

**Issue by aman5319** [pytorch/pytorch#73910]
### 🐛 Describe the bug

Adam doesn't work with CyclicLR  - Here is a code snippet with the error

```python
import torch
net = torch.nn.Linear(1,1)
optimizer = torch.optim.Adam(net.parameters(), lr=0.1 )
scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.1, max_lr=1)
```

Error

```
ValueError                                Traceback (most recent call last)

[<ipython-input-3-44a953f47a4a>](https://localhost:8080/#) in <module>()
      3 net = torch.nn.Linear(1,1)
      4 optimizer = torch.optim.Adam(net.parameters(), lr=0.1 )
----> 5 scheduler = torch.optim.lr_scheduler.CyclicLR(optimizer, base_lr=0.1, max_lr=1)

[/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py](https://localhost:8080/#) in __init__(self, optimizer, base_lr, max_lr, step_size_up, step_size_down, mode, gamma, scale_fn, scale_mode, cycle_momentum, base_momentum, max_momentum, last_epoch, verbose)
   1125         if cycle_momentum:
   1126             if 'momentum' not in optimizer.defaults:
-> 1127                 raise ValueError('optimizer must support momentum with `cycle_momentum` option enabled')
   1128 
   1129             base_momentums = self._format_param('base_momentum', optimizer, base_momentum)

ValueError: optimizer must support momentum with `cycle_momentum` option enabled
```

Looking at the code of CyclicLR it is pretty evident why it doesn't work with Adam because Adam uses beta parameters and CyclicLR doesn't support beta
https://github.com/pytorch/pytorch/blob/5372dcd9bb0e94a9bad1b04b602dc9e2e7e5c20f/torch/optim/lr_scheduler.py#L1144-L1153

But Adam works fine with OneCycleLR

```python
net = torch.nn.Linear(1,1)
optimizer = torch.optim.Adam(net.parameters(), lr=0.1 )
scheduler = torch.optim.lr_scheduler.OneCycleLR(optimizer, max_lr=1, total_steps=10)
```
Now OneCycleLR and CyclicLR are not so different and if OneCycleLR can change the beta parameters of Adam why not give the same support to CyclicLR

https://github.com/pytorch/pytorch/blob/5372dcd9bb0e94a9bad1b04b602dc9e2e7e5c20f/torch/optim/lr_scheduler.py#L1542-L1556

what do you guys think about this? This is my first time raising an issue so please guide me.

### Versions

Collecting environment information...
PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.12 (default, Jan 15 2022, 18:48:18)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111
[conda] Could not collect

cc @vincentqb @jbschlosser @albanD

**Comment by aman5319** [comment]
why not, we should be able to use Adam or any optimizer with Cyclic LR since it is a scheduler. Since Adam doesn't have a momentum parameter we can use the beta parameters in place of momentum and things should work fine.

**Comment by aman5319** [comment]
Whether we use beta in Adam or momentum in sgd that doesn't matter, the problem is in the code if you see how it is written, if the optimizer doesn't have a momentum parameter cycliclr can't be used. My point is to extend the code so that it supports momentum as well as beta.

**Comment by gonzrubio** [comment]
The bug exists in PyTorch 1.9.0
