### ISSUE TITLE
DISABLED test_data_parallel_module_kwargs_only_empty_list_cuda_float32 (__main__.TestDataParallelDeviceTypeCUDA)

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#73923]
### 🐛 Describe the bug

[test_data_parallel_module_kwargs_only_empty_list_cuda_float32 (__main__.TestDataParallelDeviceTypeCUDA)](https://github.com/pytorch/pytorch/runs/5466538017?check_suite_focus=true)

### Versions

main

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
cc @cbalioglu should we stop running data parallel tests depending on the status of DP deprecation?

**Comment by jaglinux** [comment]
Test ran successfully after applying https://github.com/pytorch/pytorch/pull/78824
cc @jeffdaily
