### ISSUE TITLE
Update favicon on the docs site

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#7393]
![image](https://user-images.githubusercontent.com/5652049/39784659-36a38df6-52e7-11e8-9f5e-69693913d09a.png)
left: forums, right: docs

**Comment by soumith** [comment]
it's already updated, you have to clear your cache :p

**Comment by soumith** [comment]
<img width="517" alt="screen shot 2018-05-08 at 5 58 59 pm" src="https://user-images.githubusercontent.com/1310570/39785274-87349254-52e9-11e8-8eec-2c22609edfcf.png">
