### ISSUE TITLE
Calling super().__torch_dispatch__ with arguments list causes segfault

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#73933]
### 🐛 Describe the bug

https://github.com/albanD/subclass_zoo/blob/33d7afe63c2a336e01eaf3e81fba085a68e3955f/bug_zoo.py#L18-L24

```
        class SuperDispatchSegfaultTensor(BaseTensor):
            @classmethod
            def __torch_dispatch__(cls, func, types, args=(), kwargs=None):
                return super().__torch_dispatch__(func, types, list(args), kwargs)
        SuperDispatchSegfaultTensor(torch.tensor(1.0)).neg()
```

This segfaults probably because not doing enough type check in CPython. Maybe `__torch_function__` also has same problem.

### Versions

master

cc @albanD @zou3519

**Comment by SherlockNoMad** [comment]
In `THPModule_disable_torch_dispatch()`, the input list type arguments is first py::reinterpret_borrowed into a py::tuple object. 
However, when the args reaches `_get_operation_for_overload_or_packet()` and get unpacked with 'args[i].ptr()', the resulting PyObject is invalid. It eventually failed when it calls `check_has_torch_function()` on this invalid PyObject. 

I suspect the fix need to happen in `THPModule_disable_torch_dispatch`. Not sure if py::reinterpret_borrowed<py::tuple> is the right way to convert list-type into tuple-type in this case.
