### ISSUE TITLE
[shard] use dist.gather instead of dist.gather_object

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#73935]
### 🚀 The feature, motivation and pitch

See context https://github.com/pytorch/pytorch/pull/71624

Coping some here: 

Now we have `dist.gather` support on NCCL, but `ShardedTensor.gather` couldn't use it for some reasons: 

1. We can use gather_object for metadatas, but we couldn't simply use gather for the local shard tensors, mainly because local_shards() is a list of tensor, but input of gather is a single tensor not a list of tensor, so gather won't work here
2. We can try using torch.cat locally on each rank to form a single tensor before the gather collective, but we need to split them afterwards as they might not be adjacent to each other (local shards on this rank might contain two tensors that's far away in the global position logically). So we might need to insert additional insertion point in the first gather_object to split the combined tensors from the second gather call. This is pretty tricky from my understanding.

### Alternatives

We are right now using `dist.gather_object`, should be slightly better than `dist.allgather_object` but ideally we want to avoid pickling

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by rohan-varma** [comment]
Re pickling, the pickler used by these object-based APIs is actually pluggable, so you could theoretically define a pickler that is able to bypass tensor objects and only do the pickling for non-tensors. @wanchaol

**Comment by kumpera** [comment]
I implemented it as part of debugging some checkpointing hangs:

https://gist.github.com/kumpera/92a731f1582331006df170e96d821597

I can PR this puppy if interested

**Comment by wanchaol** [comment]
> I implemented it as part of debugging some checkpointing hangs:
> 
> https://gist.github.com/kumpera/92a731f1582331006df170e96d821597
> 
> I can PR this puppy if interested

sure, feel free to PR it, thanks!

**Comment by kumpera** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/76865
