### ISSUE TITLE
cudatoolkit version in docker builds needs a bump

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#73971]
Last nightly docker published failed with the message that cudatoolkit=11.3.0 not available: https://github.com/pytorch/pytorch/runs/5480439616?check_suite_focus=true

Looks like our pinned version needs to be bumped, anaconda also doesn't have it: https://anaconda.org/nvidia/cudatoolkit/files

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Oh, bumping the pinned version will cause the base image not to be found (see https://github.com/pytorch/pytorch/pull/73918). A better solution could be to cut the minor version: ${CUDA_VERSION%.*}

**Comment by seemethere** [comment]
> But we can't have `cudatoolkit` that doesn't exactly match the one pytorch was built with

#73974 goes through and bumps cuda version to `11.3.1` to match what's available in docker hub as well as `cudatoolkit`

Since we indiscriminately just ask for `11.3` during our build process I'm assuming `11.3.1` should be okay considering it's the latest available

**Comment by seemethere** [comment]
Closed with #73974
