### ISSUE TITLE
AttributeError: 'CIFAR10' object has no attribute 'tgz_md5'

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#740]
My ENV: 
Ubuntu 16.04.1 + Anaconda 4.3 (with Python 3.6)

Just testing dcgan, and my command line is as simple as:
`python main.py --cuda --dataset=cifar10 --dataroot=....../cifar-10/cifar-10-batches-py`

I got the following error messages:

> (condaenv) pj@XXXXX:dcgan$ python main.py --cuda --dataset=cifar10 --dataroot=....../cifar-10/cifar-10-batches-py
> Namespace(batchSize=64, beta1=0.5, cuda=True, dataroot='....../cifar-10/cifar-10-batches-py', dataset='cifar10', imageSize=64, lr=0.0002, ndf=64, netD='', netG=
> '', ngf=64, ngpu=1, niter=25, nz=100, outf='.', workers=2)
> Random Seed:  815
> Traceback (most recent call last):
>   File "main.py", line 74, in <module>
>     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
>   File ".../anaconda3/envs/condaenv/lib/python3.6/site-packages/torchvision-0.1.7-py3.6.egg/torchvision/datasets/cifar.py", line 38, in __init__
>   File ".../anaconda3/envs/condaenv/lib/python3.6/site-packages/torchvision-0.1.7-py3.6.egg/torchvision/datasets/cifar.py", line 140, in download
> AttributeError: 'CIFAR10' object has no attribute 'tgz_md5'

Any suggestions?

Best Regards
Pei

**Comment by jiapei100** [comment]
Issue found, the dataset it NOT fully downloaded... Sorry. Close this issue.

**Comment by ypxie** [comment]
how did you make it download again? Mine is keeping poping out this error and stop.

**Comment by soumith** [comment]
you can remove the `dataroot` folder that you passed in

**Comment by ypxie** [comment]
It works, thanks!

**Comment by waitwaitforget** [comment]
Maybe you should unzip the file manually, it works for me.
