### ISSUE TITLE
https://discuss.pytorch.org/ is down

### ISSUE THREAD

**Issue by rbavery** [pytorch/pytorch#74019]
###  Describe the bug
Not sure if this is the correct place to report, (but saw a couple of previous [discuss.pytorch.org is down](https://github.com/pytorch/pytorch/issues/5209) down issues were reported here).

[discuss.pytorch.org](discuss.pytorch.org) is down.

### Versions

.

**Comment by ptrblck** [comment]
Pulling the backup and rebuilding. Will update you here once it's done so that you can recheck it.

**Comment by ptrblck** [comment]
@rbavery can you try to access it now, as it should be online again?

**Comment by jpainam** [comment]
down again

**Comment by ptrblck** [comment]
Works for me. https://downforeveryoneorjustme.com/discuss.pytorch.org?proto=https also shows it's up.
Are you seeing it being down even after a reload?

**Comment by jpainam** [comment]
![image](https://user-images.githubusercontent.com/1701705/189429137-16f8711d-8bc4-467e-bfa7-a32a3c70f51d.png)

**Comment by ptrblck** [comment]
Let me rebuild it in any case.
