### ISSUE TITLE
Test `test_reduce_add_coalesced` failed

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#74015]
### 🐛 Describe the bug

Test `test_reduce_add_coalesced` failed after PR #69751

Sample error message
```
root@959bda8c98e3:/opt/pytorch/pytorch# python test/test_cuda.py -v -k test_reduce_add_coalesced
test_reduce_add_coalesced (__main__.TestCudaComm) ... FAIL
test_reduce_add_coalesced_dense_only (__main__.TestCudaComm) ... ok

======================================================================
FAIL: test_reduce_add_coalesced (__main__.TestCudaComm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_cuda.py", line 3978, in test_reduce_add_coalesced
    self._test_reduce_add_coalesced(tensors, num_bytes * 5 // 2)
  File "test/test_cuda.py", line 3944, in _test_reduce_add_coalesced
    self.assertEqual(r, t * 2)
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 2121, in assertEqual
    assert_equal(
  File "/opt/pytorch/pytorch/torch/testing/_comparison.py", line 1074, in assert_equal
    raise error_metas[0].to_error()
AssertionError: The number of specified values in sparse COO tensors does not match: 2 != 1

----------------------------------------------------------------------
Ran 2 tests in 1.100s

FAILED (failures=1)
```

### Versions

b5f2574f36dec86a71ff39d0e07e16d39178abde

V100

cuda 11.6

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @nikitaved @pearu @cpuhrsch @mruberry @ptrblck @pmeier @ngimel

**Comment by pmeier** [comment]
Any idea why CI did not catch this?

**Comment by IvanYashchuk** [comment]
I don't know why it's not caught in CI, but I can reproduce the failure locally (compiled with `USE_DISTRIBUTED=1 USE_NCCL=1 USE_GLOO=1`).
@malfet do you know whether there are CI jobs with `torch.cuda.device_count() >= 2`?

**Comment by rohan-varma** [comment]
There are CI jobs that run multigpu tests for distributed, but test_cuda is not tested as part of distributed tests. I'm unsure if there are multi-gpu CI jobs that run test_cuda. cc @malfet

**Comment by malfet** [comment]
Hmm, there are `multigpu` config, let's see why its not running this test...
