### ISSUE TITLE
Have a `torch.tensor_like` creation op?

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#74026]
### 🚀 The feature, motivation and pitch

Most of our creation ops come in pairs:

- [`full`](https://pytorch.org/docs/master/generated/torch.full.html) / [`full_like`](https://pytorch.org/docs/master/generated/torch.full_like.html)
- [`zeros`](https://pytorch.org/docs/master/generated/torch.zeros.html) / [`zeros_like`](https://pytorch.org/docs/master/generated/torch.zeros_like.html)
- [`rand`](https://pytorch.org/docs/master/generated/torch.rand.html) / [`rand_like`](https://pytorch.org/docs/master/generated/torch.rand_like.html)
- ...

The `*_like` variant takes another tensor as reference and copies its shape and the core attributes. The attributes can be overwritten by keyword argument however, e.g.

```py
>>> a = torch.zeros(1, 2, 3, dtype=torch.float)
>>> b = torch.zeros_like(a, dtype=torch.int)
>>> assert a.shape == b.shape
>>> assert b.dtype == torch.int
```

One creation op that has no `_like` variant is `torch.tensor`. 

I propose to add it and to let it behave just like the other variants with the only difference that we don't take the shape from the reference. Thus, `tensor_like` would only copy the attributes.

I often find myself doing `torch.tensor(..., dtype=other.dtype, device=other.dtype)` when I need specific values, but otherwise want to align it with a reference. It would be more concise and less error-prone to do `torch.tensor_like(other, ...)`. Plus it conveys the intent better.

### Alternatives

I also often see something like

```py
torch.tensor(...).to(other)
```

which potentially adds an unnecessary copy.

cc @gchanan @mruberry

**Comment by mruberry** [comment]
A workaround is to create the tensor and specify its dtype and device using the other tensor's metadata.

Are there really other properties people would like to copy? The shape, for example, seems like it would be overridden by the data used to create the tensor? That seems different from other `_like` operations.

**Comment by pmeier** [comment]
You are right. Besides `shape`, all keyword arguments except for `dtype` and `device` that are copied from the reference are also problematic. Probably not worth to make the API more inconsistent just to make

```py
torch.tensor(..., dtype=other.dtype, device=other.device)
```

more concise. Thanks for considering though!
