### ISSUE TITLE
Ambiguous docstring on `register_module_forward_hook`

### ISSUE THREAD

**Issue by BrandoZhang** [pytorch/pytorch#74024]
### 📚 The doc issue

In current docstring of `forward_hook`, it says:

https://github.com/pytorch/pytorch/blob/38b94f41590d8361fd26bd18ec94938faa648a90/torch/nn/modules/module.py#L100-L102

What's the meaning of `It can modify the input inplace but it will not have effect on forward` while `The hook can modify the output.` also holds?

When I check the implementation of `Module`, the `result` of `forward` is indeed overridden by `hook_result` as long as the hook function returns a modified result.

https://github.com/pytorch/pytorch/blob/38b94f41590d8361fd26bd18ec94938faa648a90/torch/nn/modules/module.py#L1130-L1134

### Suggest a potential alternative/fix

I suppose the above docstring to be modified as follows:

```
     The hook can modify the module output as long as it returns 
     the modified output. It cannot modify the given argument `output` 
     inplace since this is called after :func:`forward` is called. 
```

cc @brianjo @mruberry @albanD @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
Thanks for the feedback.
I am not sure the updated doc is accurate either.
What about simplifying this to `You can optionally modify the output of the module by returning a new value that will be replacing the output from the forward function.` ?

**Comment by albanD** [comment]
Perfect!
Would you have some time to send a PR fixing this by any chance?
