### ISSUE TITLE
torch.quantization.fuse_modules is not backward compatible in PyTorch 1.11

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#74028]
### 🐛 Describe the bug

```py
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.model_0_0 = nn.Conv2d(3, 32, 3, 2, 1, bias=False)
        self.model_0_1 = nn.BatchNorm2d(32)
        self.model_0_2 = nn.ReLU(inplace=True)

    def forward(self, input_1):
        model_0_0 = self.model_0_0(input_1)
        model_0_1 = self.model_0_1(model_0_0)
        model_0_2 = self.model_0_2(model_0_1)
        return model_0_2

model = Model()
model.cpu()
model.train()

torch.quantization.fuse_modules(model, [['model_0_0', 'model_0_1', 'model_0_2']])
```
Running this piece of code yields the following error.
```py
Traceback (most recent call last):
  File "/work/test_fuse.py", line 21, in <module>
    torch.quantization.fuse_modules(model, [['model_0_0', 'model_0_1', 'model_0_2']])
  File "/work/python3.9/site-packages/torch/ao/quantization/fuse_modules.py", line 150, in fuse_modules
    return _fuse_modules(
  File "/work/python3.9/site-packages/torch/ao/quantization/fuse_modules.py", line 93, in _fuse_modules
    _fuse_modules_helper(model, module_list, is_qat, fuser_func, fuse_custom_config_dict)
  File "/work/python3.9/site-packages/torch/ao/quantization/fuse_modules.py", line 77, in _fuse_modules_helper
    new_mod_list = fuser_func(mod_list, is_qat, additional_fuser_method_mapping)
  File "/work/python3.9/site-packages/torch/ao/quantization/fuse_modules.py", line 49, in fuse_known_modules
    fused = fuser_method(is_qat, *mod_list)
  File "/work/python3.9/site-packages/torch/ao/quantization/fuser_method_mappings.py", line 91, in fuse_conv_bn_relu
    fused_conv = nn.utils.fusion.fuse_conv_bn_eval(conv, bn)
  File "/work/python3.9/site-packages/torch/nn/utils/fusion.py", line 7, in fuse_conv_bn_eval
    assert(not (conv.training or bn.training)), "Fusion only for eval!"
AssertionError: Fusion only for eval!
```
But it works for PyTorch < 1.11.

### Versions

Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.8.2003 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: 10.0.1 
CMake version: version 3.15.7
Libc version: glibc-2.24

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              hfd86e86_1    defaults
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py39h51133e4_0    defaults
[conda] numpy                     1.21.2           py39h20f2e39_0    defaults
[conda] numpy-base                1.21.2           py39h79a1101_0    defaults
[conda] pytorch                   1.11.0          py3.9_cuda10.2_cudnn7.6.5_0    defaults
[conda] pytorch-mutex             1.0                        cuda    defaults
[conda] torchvision               0.12.0               py39_cu102    default

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by peterjc123** [comment]
Well, looks like it is written in the release log so doesn't seem to a problem. Actually, I don't know why the conda packages before it is released. But that's okay. Although there is still one small issue, that is `fuse_modules_qat` is not exposed in the `torch.quantization` namespace, but only the new namespace `torch.ao.quantization`. This seems weird.

**Comment by HDCharles** [comment]
the torch.quantization namespace is being discontinued and was left only for BC purposes. It looks like the fuse_modules_qat api was only added during https://github.com/pytorch/pytorch/commit/082ff25f375cd6c31e3430bc38491be75aaa2f31 so it wouldn't qualify.

**Comment by peterjc123** [comment]
@HDCharles So we should use `torch.ao.quantization` instead of `torch.quantization` in PyTorch 1.10+, right?

**Comment by jerryzh168** [comment]
> @HDCharles So we should use `torch.ao.quantization` instead of `torch.quantization` in PyTorch 1.10+, right?

yes, that is correct.

Also we have a bc-breaking note for this I think, you should be able to find it in the release notes in PyTorch 1.11

**Comment by jerryzh168** [comment]
you can search for quantization in the release notes to see the change: https://github.com/pytorch/pytorch/releases

**Comment by peterjc123** [comment]
> Also we have a bc-breaking note for this I think, you should be able to find it in the release notes in PyTorch 1.11

Yes, I see that note. It's just the conda package was accidentally out before the the repo adds a new release. Thanks for your answer.

**Comment by cc-crick** [comment]
I think you can fix the tutorial in [quantization doc on PyTorch website](https://pytorch.org/docs/stable/quantization.html?highlight=get_default_qat_qconfig). I have confused about this web page before I see the issue.
