### ISSUE TITLE
Why convert to float and then convert back for c10::Half operators?

### ISSUE THREAD

**Issue by BruceDai003** [pytorch/pytorch#74020]
https://github.com/pytorch/pytorch/blob/38b94f41590d8361fd26bd18ec94938faa648a90/c10/util/Half-inl.h#L70
Why do we need to convert it to float, do float arithmetics and then convert it all back to c10::Half again? Seems like by doing this, you won't even be able to utilize some NVCC's compiler pass, e.g., FMAD. Also, I tested that without any conversion, just do cuda __half type arithmetics, results are the same. So, I just really don't understand why do we need to do these "extra steps". Thanks.

cc @ngimel

**Comment by ngimel** [comment]
These operators are mostly used in bandwidth-bound pytorch kernels where extra conversion doesn't matter. In general, pytorch is moving towards disallowing half-precision math completely #64023
