### ISSUE TITLE
Lazy Tensor Core - Hardcoded `TsNode` instances

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#74037]
### 🐛 Describe the bug

There are a number of hardcoded uses of `TsNode` in `torch/csrc/lazy/core/tensor.cpp` such as here:
https://github.com/pytorch/pytorch/blob/81962efdea333dcc6186c384802b35157cd205f0/torch/csrc/lazy/core/tensor.cpp#L108
https://github.com/pytorch/pytorch/blob/81962efdea333dcc6186c384802b35157cd205f0/torch/csrc/lazy/core/tensor.cpp#L299-L303
and more. This causes a runtime error when using a custom LTC backend with a custom node type
```
RuntimeError: Expected TsNode but could not dynamic cast
```
I see comments in `TsNode.h` that say
```c++
// TODO(whc) remove these once migrating to codegen and cleaning up Shape use
```
What is the plan to decouple these things to not use `TsNode` (and its related functions)?

CC: @wconstab 

### Versions

PyTorch version: 1.11.0a0+gita77d2be
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 2.8.12.2
Libc version: glibc-2.2.5

Python version: 3.7.4 (default, Jan 28 2022, 18:52:51) [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.9.0
[conda] Could not collect

**Comment by antoniojkim** [comment]
I'm thinking for this issue, that we can make this method
https://github.com/pytorch/pytorch/blob/5b805a6eec2325e46e1df147c83c091f520c7276/torch/csrc/lazy/ts_backend/ts_node.h#L53-L54
pure virtual. Then, the dynamic cast doesn't need to happen.

@wconstab Is there a reason why it wasn't done this way before?

**Comment by antoniojkim** [comment]
@wconstab I've put up a proposed fix for this issue here: https://github.com/pytorch/pytorch/pull/74055

Please let me know what you think

**Comment by wconstab** [comment]
> pure virtual in the parent Node class. Then, the dynamic cast doesn't need to happen.
> @wconstab Is there a reason why it wasn't done this way before?
yea, at one point we were convinced we were deleting shape from our api and just xla node would use it, but in the end we decided to keep it.

Sorry for the thrash.  Looks like we'll get it fixed quickly though.
