### ISSUE TITLE
ONNX export of torch.histc

### ISSUE THREAD

**Issue by ammaryasirnaich** [pytorch/pytorch#74032]
`RuntimeError: Exporting the operator histc to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub. `

cc @nikitaved @pearu @cpuhrsch

**Comment by garymm** [comment]
Sparse tensor support for ONNX is already tracked by https://github.com/pytorch/pytorch/issues/35294, so reduced the scope of this issue to just torch.histc.

If you have some example models that use this operator, please provide that context in the issue description.

**Comment by appindus-jweisberg** [comment]
Ran into this error as well - [here's the model](https://kornia.readthedocs.io/en/latest/_modules/kornia/enhance/equalization.html#equalize_clahe) I was trying to export.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add histc operator

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
