### ISSUE TITLE
torch.nn.Module.__init__ does not call super().__init__

### ISSUE THREAD

**Issue by pbsds** [pytorch/pytorch#74036]
### 🐛 Describe the bug

**Problem:** `torch.nn.Module.__init__` does not call `super().__init__()`

**Consequence:** Mixin-type classes ([example](https://github.com/PyTorchLightning/pytorch-lightning/blob/8577ef7bbaba016fe8d0d3377663dc53fbbefcde/pytorch_lightning/core/mixins/device_dtype_mixin.py#L33) and [example](https://github.com/PyTorchLightning/pytorch-lightning/blob/8577ef7bbaba016fe8d0d3377663dc53fbbefcde/pytorch_lightning/core/mixins/hparams_mixin.py#L25)) must be put before any `nn.Module` in `__mro__`.
This makes for an amazing foot-gun when composing models using mixins that are not not only used for `nn.Module`s, and thus cannot specify it as its parent.

### Reproduction:

```python
from torch import nn

class MyMixin:
    def __init__(self, *a, **kw):
        super().__init__(*a, **kw)
        print("MyMixin.__init__")

class MyModuleWithMixinBefore(MyMixin, nn.Module):
    def __init__(self):
        super().__init__()
        print("MyModuleWithMixinBefore.__init__")

class MyModuleWithMixinAfter(nn.Module, MyMixin):
    def __init__(self):
        super().__init__()
        print("MyModuleWithMixinAfter.__init__")

module1 = MyModuleWithMixinBefore()
print(*(f" - {i.__module__}.{i.__name__}" for i in MyModuleWithMixinBefore.__mro__), sep="\n")

print()

module2 = MyModuleWithMixinAfter()
print(*(f" - {i.__module__}.{i.__name__}" for i in MyModuleWithMixinAfter.__mro__), sep="\n")
```

Output:
```
MyMixin.__init__
MyModuleWithMixinBefore.__init__
 - __main__.MyModuleWithMixinBefore
 - __main__.MyMixin
 - torch.nn.modules.module.Module
 - builtins.object

MyModuleWithMixinAfter.__init__
 - __main__.MyModuleWithMixinAfter
 - torch.nn.modules.module.Module
 - __main__.MyMixin
 - builtins.object
```

Of note is how `MyMixin.__init__` is not printed for `MyModuleWithMixinAfter`.

### Suggested fix:

Add `super().__init__()` to `torch.nn.Module.__init__` after all the class members have been set.

### Versions

Collecting environment information...
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.22.2
Libc version: glibc-2.35

Python version: 3.9.10 (main, Feb 23 2022, 08:45:32)  [GCC 11.1.0] (64-bit runtime)
Python platform: Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
Nvidia driver version: 510.54
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.5.10
[pip3] pytorch3d==0.6.1
[pip3] torch==1.10.2+cu113
[pip3] torchmeta==1.8.0
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.11.3+cu113
[pip3] torchviz==0.0.2
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
The PR was reverted because it breaks existing code that was working around this.
Not sure how to do this change in a smoother way though...

**Comment by pbsds** [comment]
Perhaps try adding `super().__init__()` after all the class variables have been set?

**Comment by albanD** [comment]
In this case the problem is that there is a Mixin that expects some args. So that is wrong. But changing that Mixin will break loading of models. It will take a bit of time on our end to fix that.
