### ISSUE TITLE
Excessive printing for certain ONNX exports

### ISSUE THREAD

**Issue by psmaragdis** [pytorch/pytorch#74086]
### 🐛 Describe the bug

Upon calling `torch.onnx.export`, if I use `Tensor.repeat_interleave()` in my forward function, I get some unexpected printing.  Example code:

```
import torch
import torch.nn as nn

class UC( nn.Module):
    def forward( self, x):
        for _ in range( 8):
            x = x[:,:,::2]
        for _ in range( 8):
            x = x.repeat_interleave( 2, -1)
        return x

torch.onnx.export( UC(), torch.randn( 1, 128, 1024), 'foo.pth', opset_version=14)
```

Which prints:
```
[1, 128, 4] [1, 128, 4]
[0, 0, 0] [-1, -1, -1]
[1, 128, 16] [1, 128, 16]
[0, 0, 0] [-1, -1, -1]
[1, 128, 64] [1, 128, 64]
[0, 0, 0] [-1, -1, -1]
[1, 128, 256] [1, 128, 256]
[0, 0, 0] [-1, -1, -1]
```

For larger networks this becomes an unwieldy amount of printing, which dwarfs any other training information that is being printed.  This problem has been consistent across various platforms and previous Pytorch versions.

### Versions

Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.2.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.21.1
Libc version: N/A

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:43)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] pytorch-lightning==1.5.10
[pip3] torch==1.11.0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.2
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.12.0
[pip3] torchviz==0.0.2
[conda] mypy_extensions           0.4.3            py39h2804cbe_4    conda-forge
[conda] numpy                     1.21.3                   pypi_0    pypi
[conda] pytorch-lightning         1.5.10                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch-cluster             1.5.9                    pypi_0    pypi
[conda] torch-geometric           2.0.2                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.12                   pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

**Comment by shubhambhokare1** [comment]
Thanks for reporting this bug, PR #74125 should resolve this issue
