### ISSUE TITLE
at::unfold is not present in the C++ docs even though it's an available function

### ISSUE THREAD

**Issue by polvalente** [pytorch/pytorch#74091]
### 📚 The doc issue

I couldn't find the function neither in the main page https://pytorch.org/cppdocs/api/library_root.html nor at the `at::native` https://pytorch.org/cppdocs/api/namespace_at__native.html page.

I'm not sure if the function being missing is intentional, but the function works just fine with 1.9.1 and 1.10.2, and unlike `torch::nn::functional::unfold`, it works just like `tensor.unfold` does at the Python level (different behaviors between them).

### Suggest a potential alternative/fix

Perhaps the function should be published in the docs?

cc @brianjo @mruberry @jbschlosser

**Comment by mruberry** [comment]
Thanks for reporting this issue, @polvalente. We would accept a PR improving the C++ API documentation.

**Comment by z6491679** [comment]
hi i am using torch::nn::functional::unfold and there are not any docs or blogs that give any examples，do you have any docs？
