### ISSUE TITLE
'FloatTensor' object has no attribute 'get_device'

### ISSUE THREAD

**Issue by avloss** [pytorch/pytorch#741]
I was going through this example
http://pytorch.org/docs/notes/cuda.html

it seems one can use "get_device" to check the location of the tensor. but it only works if the tensor is on GPU, which calls for ugly "check attr" workaournds!

**Comment by avloss** [comment]
version is `0.1.8` (latest stable AFAIK)

**Comment by apaszke** [comment]
You can use tensor.is_cuda for that

**Comment by soumith** [comment]
also, it's unclear what we should return for `get_device` in the case of CPU tensors...

**Comment by avloss** [comment]
may be "-1". anyways - `is_cuda` seems to be a fiar suggestion! thanks for your answer and thanks for a great project! :) looking forward to see it grow! :)
