### ISSUE TITLE
VC++ does not auto-capture constexpr variables

### ISSUE THREAD

**Issue by dhruvbird** [pytorch/pytorch#74116]
### 🐛 Describe the bug

There's clang and there's MSVC, and they differ on what the expect in terms of capturing constant values (declared `const`).

Example code:

```cpp
int foo() {
  constexpr const int kValue = 100;

  // The lambda below compileable by gcc/clang,  but fails for VC++,  since it expects
  // even constant expressions  to be captured.
  auto lam1 = []() { return kValue + 1; };

  // The lambda below compileable by all compilers, but trigers `unused-lambda-capture`
  // warning in clang, as constant expressions does not need to be captured, per
  // A lambda expression can read the value of a variable without capturing it
  //  -  if the variable is constexpr
  // see https://en.cppreference.com/w/cpp/language/lambda
  auto lam2 = [kValue]() { return kValue + 1; };

  return lam1() + lam2();
}
```

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
Editing PR description and example, as this one does not compile anywhere

**Comment by malfet** [comment]
According to Feb 22 2022 comment from a 6 years old [stackoverflow](https://stackoverflow.com/a/33874942) question, VC++ still does not implement standard correctly

**Comment by kit1980** [comment]
Closing after consulting with Microsoft. This is a VC++ standards compliance issue, not really a PyTorch issue.
