### ISSUE TITLE
libtorch 1.11.0 libiomp5.dylib contains erroneous link to /DLC/torch instead of using @rpath

### ISSUE THREAD

**Issue by adampauls** [pytorch/pytorch#74120]
### 🐛 Describe the bug

Same as https://github.com/pytorch/pytorch/issues/38607, but it seems to have re-appeared between 1.10.2 and 1.10.0.

For 1.10.2 (from https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.10.2.zip)
```
adpauls$ otool -L libtorch/lib/libiomp5.dylib
libtorch/lib/libiomp5.dylib:
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```
For 1.11.0 (from https://download.pytorch.org/libtorch/cpu/libtorch-macos-1.11.0.zip)
```
adpauls$ otool -L libtorch/lib/libiomp5.dylib
libtorch/lib/libiomp5.dylib:
	/DLC/torch/.dylibs/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

### Versions

macos 1.11.0

cc @ezyang @gchanan @zou3519 @seemethere @malfet @jbschlosser @albanD

**Comment by adampauls** [comment]
Friendly ping. Any movement here?

**Comment by malfet** [comment]
@atalman can you please see if this is the case for 1.12 release candidate?

**Comment by atalman** [comment]
@malfet Yes this is present in the 1.12 rc as well
(base) atalman-mbp:libtorch atalman$ otool -L lib/libiomp5.dylib
lib/libiomp5.dylib:
	/DLC/torch/.dylibs/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)

We should definitely fix this asap.

**Comment by atalman** [comment]
As per following issues: https://github.com/matthew-brett/delocate/issues/150 and discussion here : https://github.com/python-lz4/python-lz4/issues/244

This behaviour is done by design, here is the comment from author of delocate module:
macOS distinguishes between the install-name ID - the universal name of the library - and the full or relative path to the library. They are often the same, but need not be. In this case we're just making an ID that isn't a path, but does contain the library name, in order that the install ID is not the same as any other possible (non-delocate) copies of the library in the search path with the same <dylib-name>, and to make sure the directory containing the dylib can be anywhere on the filesystem.

The first item of otool -L output is not necessarily a link, in this case its an ID, 
As per otool man page: 
-L     Display the names and version numbers of  the  shared  libraries
              that  the  object file uses, as well as the shared library ID if
              the file is a shared library.

**Comment by adampauls** [comment]
I believe the problem is this:
```
>> otool -L libtorch/lib/libtorch_cpu.dylib
libtorch/lib/libtorch_cpu.dylib:
	@rpath/libtorch_cpu.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0) // *** problem here***
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
>> otool -L libtorch/lib/libiomp5.dylib
libtorch/lib/libiomp5.dylib:
	/DLC/torch/.dylibs/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0) // *** does not match here
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
````

libtorch thinks the name of `libiomp5.dylib` is what it used to be (`@rpath/libiomp5.dylib`), not what it is now (`/DLC/torch/.dylibs/libiomp5.dylib`). I think maybe that `delocating` is doing something non-standard to load the libs, so I think the reason I'm seeing the breakage is because I'm manually loading the libs.

**Comment by atalman** [comment]
@adampauls Can you please include the Exception you are getting in your code ? I want to understand how is the breakage happening exactly

**Comment by adampauls** [comment]
If I run the following Java code:
```java
 public static void main(String[] args) {
            System.load("/Users/adpauls/Downloads/libtorch/lib/libiomp5.dylib");
            System.load("/Users/adpauls/Downloads/libtorch/lib/libc10.dylib");
            System.load("/Users/adpauls/Downloads/libtorch/lib/libtorch_cpu.dylib");
            System.load("/Users/adpauls/Downloads/libtorch/lib/libtorch.dylib");
    }
```

it will throw 
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/adpauls/Downloads/libtorch/lib/libtorch_cpu.dylib: dlopen(/Users/adpauls/Downloads/libtorch/lib/libtorch_cpu.dylib, 1): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/adpauls/Downloads/libtorch/lib/libtorch_cpu.dylib
  Reason: image not found
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1866)
```

If I run `install_name_tool -id "@rpath/libiomp5.dylib" libiomp5.dylib`, the problem goes away and this code runs fine.

**Comment by atalman** [comment]
@adampauls Ok Thanks! Its clear.

**Comment by adampauls** [comment]
In case it wasn't clear, I think this can be solved my making sure that the downstream libraries depend on the `/DLC` ID, so the original description of the "bug" in the title -- that @rpath needs to be used -- is incorrect I think.

**Comment by adampauls** [comment]
The libs I have are from the libtorch download. Maybe a simple answer is to only run delicate on the wheel, but keep the libtorch libs as they were?
