### ISSUE TITLE
[Documentation Clarification] nn.Upsample

### ISSUE THREAD

**Issue by Naman-ntc** [pytorch/pytorch#7413]
In documentation of [nn.Upsample](https://pytorch.org/docs/master/nn.html#torch.nn.Upsample), for the parameter `scale_factor` if we have a 5D Tensor as input what should be the order of list provided as `scale_factor`?
That is do the elements of `scale_factor` correspond to [`depth`, `height`, `width`] or [`height`, `width`, `depth`] as order is not clearly mentioned in documentation in random order.

Also as in all other Layers MaxPool3D, Conv3D we use the former i.e.  [`depth`, `height`, `width`] so for generality if scale_factor corresponds to latter then it should be maybe changed to former order (just my opinion)?

If it's the former case we should update documentation otherwise maybe we should change the the parameter order.

**Comment by heitorschueroff** [comment]
Closing as docs now reflect this.
