### ISSUE TITLE
`torch.diagonal` can not  take a batch diagonal with correct `dim1` and `dim2`

### ISSUE THREAD

**Issue by leftthomas** [pytorch/pytorch#74136]
### 🐛 Describe the bug

```python
import torch
a = torch.randn(2, 3, 3)
b = torch.diagonal(a, dim1=-2, dim2=-1)
print(b.shape)
```
it should print `torch.Size([3, 3])`, but it prints `torch.Size([2, 3])`

### Versions

1.11.0

**Comment by Sumeet2807** [comment]
@leftthomas You have 2 3X3 matrices for the shape (2,3,3). So, you should have 2 3-element diagonals, which is of shape (2,3). But I am not sure if this was the intended functionality per the documentation. Maybe the documentation could use better words.

**Comment by leftthomas** [comment]
@Sumeet2807 , oh, I see what you mean, the documentation is some confusing.
