### ISSUE TITLE
[Bug][ONNX] Specification Inconsistency in Flatten

### ISSUE THREAD

**Issue by ganler** [pytorch/pytorch#74142]
### 🐛 Describe the bug

```python
import torch

N = 1 # can be anything else

class Net(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
    
    def forward(self, x):
        return x.flatten()

net = Net().eval()

o = net(torch.zeros((N), dtype=torch.float))
print(o.shape)

with torch.no_grad():
  torch.onnx.export(net, (
      torch.ones((N), dtype=torch.float)), "output.onnx", verbose=True, opset_version=14)
```

## In ONNX (Also ONNXRuntime)

Flatten returns a shape of (1, N).

![image](https://user-images.githubusercontent.com/38074777/158040834-851e04c5-147b-4155-80c7-704ba7da6e0e.png)

## However in Torch

Flatten returns a shape of (N).

![image](https://user-images.githubusercontent.com/38074777/158040846-349424d6-eab0-4e91-871e-2fed5dcb022d.png)

### Versions

PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 3GB
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.10.2
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] torch                     1.10.2                   pypi_0    pypi

cc: @garymm @BowenBao @neginraoof @thiagocrepaldi

**Comment by ganler** [comment]
Maybe simply add a "squeeze()" layer when exporting flatten.

**Comment by BowenBao** [comment]
@ganler Thanks for reporting, should be fixed by https://github.com/pytorch/pytorch/pull/74595.

**Comment by ganler** [comment]
@BowenBao Thank you so much!
