### ISSUE TITLE
DISABLED test_pdist_norm_large_cuda (__main__.TestTorchDeviceTypeCUDA)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#74154]
Platforms: windows

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_pdist_norm_large_cuda%2C%20TestTorchDeviceTypeCUDA)).

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @mruberry

**Comment by janeyx99** [comment]
Note that this test is NOT flaky and seems to fail consistently due to over allocating memory.

**Comment by janeyx99** [comment]
Solution perhaps is to decorate the test with "requires lots of memory", but that would disable it on CI still.

Better solution: "modernize" this test.

**Comment by janeyx99** [comment]
My fix did not fix :C

**Comment by mruberry** [comment]
I don't know, sorry, @ptrblck -- but it would be extremely interesting to understand why the test suite is gobbling up so much more memory!
