### ISSUE TITLE
Specify partial inverses using torch.linalg.inv

### ISSUE THREAD

**Issue by JohnLaMaster** [pytorch/pytorch#74168]
### 🚀 The feature, motivation and pitch

Feature: ability to specify the desired indices/rows/cols/diagonal of the inverse so that only the necessary values are calculated.

Most torch.linalg functions are expensive and synchronize with the CPU. As discussed  in #[How to speed up linalg operations](https://discuss.pytorch.org/t/how-to-speed-up-linalg-operations/146300), this makes them very slow, especially in my case because I need to invert matrices from the forward pass and then backpropagate through the inversions. I have 500,000 samples in my dataset so this now takes ~2.5hrs/epoch instead of ~20min/epoch. 

I only need a small fraction of the inverse. The equation I'm using is the following:
![image](https://user-images.githubusercontent.com/7785925/158203565-42c22489-cf13-4d6c-9cb8-6cbb6930417c.png)
where **B** is a 60x512 matrix, **D** is 512x512, and lambda comes from the forward pass. The second matrix is zero-padded from 60x512 to 512x512. Therefore, I only need the first 60 rows of the inverse.

Sometimes you might only need certain columns or rows from the inverse. Or the data might have a special structure that could reduce the cost of the inversion. My particular use case would only require providing row and column indices for the inverse.

### Alternatives

So far torch.linalg.pinv has worked along with manually defining the left of inverse arguments before using torch.linalg.inv. I have also added code to the initialization to calculate and store the indices needed for the minors so that I can simply use torch.gather to collect the necessary values to compute a partial inverse. However, with limited RAM (both CPU and GPU), a matrix that big is wasteful and often too large to keep in memory.

### Additional context

The documentation mentions the GPU/ CPU synchronization for torch.linalg.inv, but I don't understand why that is necessary. I'm sure it is for some reason, but I don't get that part. Maybe a quicker solution would be to eliminate this synchronization and just let it run on the GPU. But as long as this sync slows it down, at least being able to specify what parts of the inverse are needed would be useful to cut down on the expense.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
Which algorithm do you propose we implement / use to compute the first few columns of the inverse? This seems like a task that should be possible to implement on top of the existing api after some algebraic manipulations, either using lu_factor_ex + lu_solve or a qr factorisation of an appropirate matrix.

**Comment by Lezcano** [comment]
Yep, you can do this via lu_factor_ex (no sync) and then lu_solve (no sync) solving for a matrix B of shape 64x512 where the top 64x64 matrix is he identity and the rest is zeros.

Does this solve your problem?

**Comment by JohnLaMaster** [comment]
Hi @Lezcano, thank you for your help. The only problem that comes up with your suggestion is that lu_solve requires a square matrix while the matrix to be inverted in **H** has the shape [batchSize, 60+512, 512]. lu_factor_ex works fine, but the lu_solve throws an error.

Tbh, I haven't had much success finding the implementations in the pytorch source code like I usually do. So it's been hard to figure out how they work. Given that I know the indices I need of the resulting inverse, I should be able to calculate the determinants of the corresponding minors. Of course iterating through a for-loop would be slow, which is why I initially thought to store an index vector but turns out, that is prohibitively expensive. I'm not familiar enough with linear algebra to know what other methods could be used to partially invert a non-square matrix. If you have any suggestions I could look into, I would appreciate whatever you have!

**Comment by Lezcano** [comment]
What is then the proposed algorithm that you are requesting us to implement? Could you provide a short description / some pseudocode describing the it?

**Comment by Lezcano** [comment]
So, a few things. You talk about "the inverse", but the matrix is not square. The notion of an inverse is just defined for square matrices. What do you mean in this case then?

Related to the previous point, is the input matrix full-rank? Things may work differently when the matrix you have is not full-rank. Full-rank matrices have left (or right) inverses, but what's an inverse for a matrix full of zeros?

As a last point, note that in your algorithm you are computing determinants (which is n^3) inside two loops. This is very expensive (and very numerically unstable...), regardless of whether you implement it in Python or C++. I think the approach requires some intrinsic algorithmic rethinking really. Also, it seems too specific to be implemented in PyTorch core.

What I would suggest is that you first try to devise an algorithm to solve the problem that just depends on lu_factor + lu_solve. Then, if you think this could be useful to ither people, you can consider implementing it as an external library for other people to use. 

What do you think?

**Comment by Lezcano** [comment]
Closing this as it's too specific an algorithm to have in core. It would be best to implement it as an external library.
