### ISSUE TITLE
[feature request] `select_index` for sparse tensors

### ISSUE THREAD

**Issue by superbobry** [pytorch/pytorch#7416]
## Issue description

Sparse tensors do not currently support indexing (neither `gather`, nor `select_index`). This could be handy for e.g. embedding categorical features with non-contiguous vocabulary. 

Sidenote: a similar result can be achieved via bucketization (see #7284), without using sparse tensors.

## Code example

```
>>> import numpy as np
>>> import torch
>>> vocab = [102, 104, 2, 103, 0, 101, 3]
>>> lookup_table = torch.sparse.IntTensor(
...     torch.tensor(np.atleast_2d(vocab)), 
...     torch.arange(len(vocab), dtype=torch.int), 
...     torch.Size((max(vocab) + 1, )))
...
>>> lookup_table[102]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Sparse tensors do not have strides.
```

## System Info

```
PyTorch version: 0.5.0a0+3e785d5
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.3
GCC version: Could not collect
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] torch (0.5.0a0+3e785d5)
[pip3] torchvision (0.2.1)
[conda] torch                     0.4.0                     <pip>
[conda] torch                     0.5.0a0+3e785d5           <pip>
[conda] torchvision               0.2.1                     <pip>
```

**Comment by superbobry** [comment]
I'd be happy to tackle this myself if you give me pointers on how to add a new operation to a tensor type.

**Comment by zou3519** [comment]
I think the approach here is to add a new native function. You can declare it in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml and then write the function body in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Indexing.cpp . Indexing a sparse tensor is probably just searching through `tensor._indices()` for the desired indices and returning a new tensor with those indices and their corresponding values.

**Comment by weiyangfb** [comment]
Thanks @f2013519 ! I will need to work on `index_select` on my own since we will need it soon (this two weeks).

**Comment by f2013519** [comment]
Sure, @weiyangfb . Is there any other function / issue, that I could help out with to get started?

**Comment by mrdrozdov** [comment]
This would be a really useful feature. Consider the case where your dataset is 100M sentences, but you are only read 100K sentences at any one time — the vocabulary of the entire dataset is huge (e.g. 1M), but you only need to care about the vocabulary for the current 100K split. If you are using word embeddings with dimension 1024, then keeping the (1M, 1024) embedding matrix in cuda memory is not great.

Until this feature is implemented allowing for sparse embedding lookup, here is a workaround. Sparse lookup using dense embedding matrix:

```
vocab_size = BIGNUM # for example, 1000000
active_size = SMALLNUM # for example, 3000
active_vocab = torch.randperm(vocab_size)[:SMALLNUM].long()
index = active_vocab.argsort()
lookup = torch.zeros(BIGNUM).fill_(SMALLNUM+1).long()
lookup[active_vocab] = index

# A tensor including only indices from the "active vocab"
some_tensor = active_vocab[torch.LongTensor(1000).random_(0, active_size)]

# Your dense embedding matrix.
embedding = torch.FloatTensor(active_size, 400)

# Map your tensor's indices to those corresponding with the dense embeddings.
embedding_lookup = lookup[some_tensor]

# Sparse Embedding Lookup with Dense Embedding
output = embedding[embedding_lookup]
```

**Comment by fbpierazzi** [comment]
Did anyone implement index_select() for sparse PyTorch tensors, eventually?

**Comment by fbpierazzi** [comment]
> Thanks @f2013519 ! I will need to work on `index_select` on my own since we will need it soon (this two weeks).

Did you submit something?

**Comment by xkianteb** [comment]
Is there any update on this feature request? @weiyangfb @fbpierazzi

**Comment by ezyang** [comment]
I believe that @weiyangfb is no longer working on this feature. PRs would be much helpful.

**Comment by xuChenSJTU** [comment]
I have the same problem. Does anyone have some advice???

**Comment by xkianteb** [comment]
What is your use case? @xuChenSJTU

**Comment by xuChenSJTU** [comment]
Thanks. I have solved the problem. I just need to get one-hot embedding for the diag sparse matrix. So I do not need to select the specific row. Instead, I directly generate the one-hot embeddings in the training process rather than select from the sparse matrix.

**Comment by xuChenSJTU** [comment]
> What is your use case? @xuChenSJTU

Thanks. I have solved the problem. I just need to get one-hot embedding for the diag sparse matrix. So I do not need to select the specific row. Instead, I directly generate the one-hot embeddings in the training process rather than select from the sparse matrix.

**Comment by pearu** [comment]
Heads up: PR #24937 implements `select` (that `getitem` is using) and `index_select` for sparse tensors.
