### ISSUE TITLE
intermittent SIGSEGV segfault when plotting during training_step

### ISSUE THREAD

**Issue by JackKelly** [pytorch/pytorch#74188]
## 🐛 Bug

If I create specific, simple `matplotlib` plots during `training_step` then I get a segfault after training for several batches.

Specifically, if I call `plot_data()` from within `training_step`, then I get a segfault:

```python
def plot_data():
    """Plot random data."""
    fig, axes = plt.subplots(ncols=4)  # See note 1 below.
    N_PERIODS = 16
    x = pd.date_range(START_DATE, periods=N_PERIODS, freq="30 min")  # See note 2 below.
    y = np.ones(N_PERIODS)
    for ax in axes:
        ax.plot(x, y)
    plt.close(fig)
```

I initially thought this was a PyTorch Lightning issue, so I first posted this issue to the PyTorch Lightning issue queue: https://github.com/PyTorchLightning/pytorch-lightning/issues/11925

After discussion, it seemed unlikely to be a Lightning issue. So I posted this issue to the Matplotlib issue queue(!): https://github.com/matplotlib/matplotlib/issues/22478

After discussion with both communities, it's looking like the issue might be a PyTorch issue!

Interestingly, I've found two ways to stop the segfaults. You can do one or the other (or both) of these actions to stop the segfaults:

1. Change `ncols` to one of `{2, 3, 5, 6, 7, 9, 10}`.  segfaults only seem to appear if `ncols` is one of `{4, 8, 16, 32}`
2. Convert `x` from a `pd.DatetimeIndex` to a numpy array of matplotlib dates by doing `x = matplotlib.dates.date2num(x)` after line 1.

If I run `gdb --args python script.py` I get this:

```
Epoch 0:   1%|█▏| 7/1024 [00:01<02:52,  5.90it/s, loss=0.281, v_num=34]
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x000055555568bb4b in _PyObject_GC_UNTRACK_impl (filename=0x55555587fef0 
"/home/conda/feedstock_root/build_artifacts/python-split_1643749964416/work/Modules/gcmodule.c", lineno=2236, 
op=0x7fffd05f5e00) at /home/conda/feedstock_root/build_artifacts/python-
split_1643749964416/work/Include/internal/pycore_object.h:76
76  /home/conda/feedstock_root/build_artifacts/python-split_1643749964416/work/Include/internal/pycore_object.h:
 No such file or directory.
```

The minimal code example below seems to always crash whilst training on epoch 7.

In my "real" code, the crash was intermittent.

If `ncols` is large (e.g. 32) then the crash changes randomly between:

* `SIGSEGV` segfault
* `AttributeError: 'weakref' object has no attribute 'grad_fn'`
* `AttributeError: 'builtin_function_or_method' object has no attribute 'grad_fn'`

The two `AttributeErrors` originate from the same bit of code: line 213 of `torch/optim/optimizer.py`: `if p.grad.grad_fn is not None:`.  My guess is that the `SIGSEGV` is the root problem, and the `AttributeErrors` are _symptoms_ of the underlying `SIGSEGV` error. I have (once) seen the code compain, at the same time, about a `SIGSEGV` and an `AttributeError`.

### To Reproduce

These scripts and conda `environment.yaml` are in a tiny GitHub repo for this bug report: https://github.com/JackKelly/pytorch-lighting-segfault

```python
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import pytorch_lightning as pl


START_DATE = pd.Timestamp("2020-01-01")
N_EXAMPLES_PER_BATCH = 32
N_FEATURES = 1


class MyDataset(Dataset):
    def __init__(self, n_batches_per_epoch: int):
        self.n_batches_per_epoch = n_batches_per_epoch

    def __len__(self):
        return self.n_batches_per_epoch

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        x = torch.rand(N_EXAMPLES_PER_BATCH, N_FEATURES, 1)
        y = torch.rand(N_EXAMPLES_PER_BATCH, 1)
        return x, y


class LitNeuralNetwork(pl.LightningModule):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.nn = nn.Linear(in_features=N_FEATURES, out_features=1)

    def forward(self, x):
        x = self.flatten(x)
        return self.nn(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.mse_loss(y_hat, y)
        plot_data()
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.001)


def plot_data():
    """Plot random data."""
    # ncols needs to be 4 or higher to trigger a segfault.
    fig, axes = plt.subplots(ncols=4)
    N_PERIODS = 16
    x = pd.date_range(START_DATE, periods=N_PERIODS, freq="30 min")
    # The segfaults go away if I do:
    # x = mdates.date2num(x)
    y = np.ones(N_PERIODS)
    for ax in axes:
        ax.plot(x, y)
    plt.close(fig)


dataloader = DataLoader(
    MyDataset(n_batches_per_epoch=1024),
    batch_size=None,
    num_workers=2,
)

model = LitNeuralNetwork()
trainer = pl.Trainer()
trainer.fit(model=model, train_dataloader=dataloader)
```

Here's my `environment.yml` file:

```yaml
name: segfault
channels:
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - pandas
  - pytorch
  - cpuonly 
  - pytorch-lightning
```

### Additional context

This same issue, previously posted to Matplotlib and Pytorch Lightning:

These threads contain some excellent debugging information by members of the community.

* https://github.com/matplotlib/matplotlib/issues/22478
* https://github.com/PyTorchLightning/pytorch-lightning/issues/11925

### Versions

* CUDA:
	- GPU:
	- available:         False
	- version:           None
* Packages:
	- numpy:             1.22.2
	- pyTorch_debug:     False
	- pyTorch_version:   1.10.2
	- pytorch-lightning: 1.5.10
	- tqdm:              4.62.3
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.9.10
	- version:           #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022

cc @ezyang @gchanan @zou3519 @vincentqb @jbschlosser @albanD

**Comment by albanD** [comment]
Hi,
Thanks for the report!

I am a bit confused because the `plot_data()` function doesn't call or use any PyTorch object right?

**Comment by JackKelly** [comment]
> I am a bit confused because the plot_data() function doesn't call or use any PyTorch object right?

That's correct! It is a strange bug :slightly_smiling_face: 

To help explain why we think this might be a PyTorch bug, here are some relevant quotes from [the discussion of this issue over on the matplotlib issue queue](https://github.com/matplotlib/matplotlib/issues/22478):

@tacaswell [says](https://github.com/matplotlib/matplotlib/issues/22478#issuecomment-1043069215) (my emphasis):

> There is nothing from Matplotlib in any of those traces, I am skeptical that we are directly involved. **My knee-jerk guess is that with the plotting involved the garbage collector is being fired more often or changing the timing so you are now losing some race in pytorch / lightning that without plotting you were winning.**
>
> It is also possible that when you pass in the series we hold a reference to the original (I think) so that may be keeping somethings alive longer.
>
> On balance, the fact that different numbers of columns affect if it crashes or not makes be lean more towards there being some sort of race-condition.
> ...
> This is weird enough that my guess is that under the hood pytorch/pytoch-lightning is keeping pointers to python objects without properly reference counting them, the objects are getting cleaned up, and then because Python uses an object pool that object is getting resurrected as a new object. I do not have a clear explanation of how the grad is getting miss-mapped to some other attribute (but my guess is that Parameters is slotted so there is a index-based jump-table in there someplace). This would certainly explain the segfaults in the case when the object did not get resurrected and now instead of grabbing the wrong attribute it is looking at a null pointer.
> ...
> I suggested gc.collect() calls to force the issue.

And the conversation continues on the discussion of this issue on [the pytorch lightning issue queue](https://github.com/PyTorchLightning/pytorch-lightning/issues/11925):

@tacaswell [says](https://github.com/PyTorchLightning/pytorch-lightning/issues/11925#issuecomment-1043072607):

> @justusschock Can you check the types of the objects in `self.paramaters()`? I am assuming that somewhere in the pytorch/lightning side there are c-pointers to Python objects being held. If that is true, I suspect there is a bug in your reference counting and somehow resurrected or null objects are being found.
> 
> I would also add I do not see any mechanisim by which Matplotlib would even be aware of the objects in self.parameters(), let alone mutate them.

@justusschock [replies](https://github.com/PyTorchLightning/pytorch-lightning/issues/11925#issuecomment-1043080816): 

> We are indeed doing some pointer mechanics under the hood, but nothing of that is in any sort related to gradient tracking or anything similar (and it is all in Python). Those are all handled by PyTorch directly. So from my understanding it is definitely possible/likely that PyTorch does have some C-/C++-Style Pointers there.
>
> As I really do not have any idea on how to further debug this, I'd actually suggest to ask the torch guys directly. We are never touching the gradients explicitly except through pre-defined torch functions. I am really sorry, that I have to keep the hot-potato-game up and running, but I think this is your best chance to get the issue resolved. At least I am very clueless about what is going on here.
>
> @tacaswell Yes I agree, that matplotlib wouldn't know about the parameters, but my initial guess was, that there might be a collision from one of the matplotlib backends (which might also include some C++ / C code) that might have a collision with the PyTorch C++ part (since torch dispatches to C++ pretty fast). I am not that familiar with the matplotlib mechanics under the hood though so this is a real wild guess and I am sorry if it actually does not make sense at all.

I'd recommend reading the rest of the discussion over on [the pytorch lighting issue queue](https://github.com/PyTorchLightning/pytorch-lightning/issues/11925#issuecomment-1043080816).

**Comment by ezyang** [comment]
confirmed it segfaults even when I run a DEBUG=1 master build of pytorch. It takes some time though.

**Comment by ezyang** [comment]
I recompiled PyTorch with ASAN but it didn't not trigger any memory errors

**Comment by ezyang** [comment]
I built matplotlib from source at master and it no longer segfaults. Give that a try.

**Comment by tacaswell** [comment]
@ezyang if you compile from source of the released version does in segfault or not?  The detail I am pushing at is if this is something to do with how Matplotlib is complied / linked so the important change is you compiled it your self rather than the version change.

**Comment by ezyang** [comment]
It errors with v3.5.1 built from source

**Comment by tacaswell** [comment]
Well, that is wild.  I'm not sure if I will have time to bisect this in the near future....

**Comment by JackKelly** [comment]
Thanks loads @ezyang and @tacaswell for all your work on this!

**Comment by ezyang** [comment]
Gonna close for now, reopen if needed
