### ISSUE TITLE
Lazy Tensor Core - Autograd mechanics not working

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#74196]
### 🐛 Describe the bug

Encountering an issue where the `requires_grad` field is not being set correctly on forward passes.

According to the [docs](https://pytorch.org/docs/stable/notes/autograd.html#setting-requires-grad):
> During the forward pass, an operation is only recorded in the backward graph if at least one of its input tensors require grad.

So, for ops like `aten::nll_loss_forward` with inputs `(self, target, ...)` where `self` has `requires_grad==True`, the output tensors should also have `requires_grad==True`. However, in LTC with a custom backend this is not the case. Because the output tensor has `requires_grad==False`, I get an error like:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
Which makes sense. The problem here is that the output does not have `requires_grad==True`.

Strangely, it is the case for the LTC TorchScript backend. However, for ops (like `aten::nll_loss_forward`) that are "supported" by both the TS backend and my custom backend, the autograd behaviour is different and I can't seem to find why. 

I modified the autogenerated `LazyNativeFunctions::nll_loss_forward` locally and found that even in the TS backend, the output tensors of that function do **not** have `require_grad` set to `True`. So, the `requires_grad` field must be being set elsewhere. However, I can't seem to find where, and I have no idea why its not being set for my LTC backend.

Any help here on where the `require_grad` actually gets set would be helpful.

CC: @wconstab 

### Versions

```
PyTorch version: 1.11.0a0+gita77d2be
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: version 2.8.12.2
Libc version: glibc-2.2.5

Python version: 3.7.4 (default, Jan 28 2022, 18:52:51) [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] torch==1.9.0
[conda] Could not collect
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by antoniojkim** [comment]
@wconstab Investigating a bit further, I've noticed that its when I use a mix of ops that the LTC TS backend doesn't already support such as `aten::linear` for which the LTC TS backend just uses `aten::addmm`. So, my wonder here then is how to get new ops like `aten::linear` to perform the autograd mechanics properly. Is there something that needs to be done to "register" the new ops to perform autograd correctly?

**Comment by albanD** [comment]
Hey,

`linear` is defined as being a composite implicit op in core: https://github.com/pytorch/pytorch/blob/3b421af85a876f727599c647d0111739aac028f0/aten/src/ATen/native/native_functions.yaml#L2579-L2580

So its implementation must be differentiable. If you are overriding it, you have to make sure that you handle autograd properly on your end. You can see details here on how to handle that: https://pytorch.org/docs/stable/notes/extending.html

**Comment by antoniojkim** [comment]
> So its implementation must be differentiable. If you are overriding it, you have to make sure that you handle autograd properly on your end. You can see details here on how to handle that: https://pytorch.org/docs/stable/notes/extending.html

I'm not "overriding" it per say. I'm not changing how its called on the python side or writing a new implementation for it. I'm just changing how its dispatched via a LTC backend. Are you saying that this changes the differentiability of the op? As in `aten::linear` is not inherently differentiable, but since `aten::addmm` is, it is also implicitly differentiable?

**Comment by albanD** [comment]
Yes that what "composite implicit autograd" means (the key when there is no entry in native_functions.yaml).
We are implicitly differentiating it by looking at the functions it calls.
