### ISSUE TITLE
xlogy, xlog1py are all skipping TestGradients

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#74279]
Per title. Previously their sample inputs were less exhaustive and didn't demonstrate the issue with their gradient computations.

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry

**Comment by drisspg** [comment]
Looked into the the pow, and float_power and created this issue with some findings:  #76483
