### ISSUE TITLE
NotImplementedError Description

### ISSUE THREAD

**Issue by zikpefu** [pytorch/pytorch#74303]
### 🚀 The feature, motivation and pitch

I was working on creating my first NN with pytorch using classes and for some reason it kept saying "NotImplementedError: " whenever I would run my input through the model. After tons of digging I figured out that I misspelled "forward" as "foward" (gotta love English). **All of this to say that I wish there was more of a description for the NotImplementedError in terms of the forward function**. Something like:  "NotImplementedError: function "forward" not found; Check Indentation or Spelling".

I  think this will greatly reduce the amount of headache newcomers like me will have learning pytorch for the first time.

![image](https://user-images.githubusercontent.com/34219451/158629879-1fa4d044-6f90-4344-ba1e-054563826505.png)

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by mruberry** [comment]
What do you think, @jbschlosser?

**Comment by zikpefu** [comment]
How hard would this be to implement? @jbschlosser Thanks!

**Comment by jbschlosser** [comment]
Extremely easy - just add a message to the error thrown here:
https://github.com/pytorch/pytorch/blob/a15f78347b0a4a3aed6d1da4b018194407feb640/torch/nn/modules/module.py#L190-L201

**Comment by zikpefu** [comment]
Ok sounds good, I'll do this as soon as I can. Thanks!

**Comment by jbschlosser** [comment]
No need to be assigned - anyone is free to work on whatever they choose :) I'll be out for surgery but @albanD can review the change for you.

**Comment by jaketae** [comment]
Hey @zikpefu, did you get a chance to work on this? If not, I would like to give it a try. Let me know if you're still on it or plan on getting it done soon!

**Comment by zikpefu** [comment]
@jaketae Hey Jake, I'm still planning on working on it, and I should be done by this weekend (with school and life). I need this contribution for my class assignment if you don't mind?

**Comment by jaketae** [comment]
Sure, by all means go for it! Good luck on the assignment.

**Comment by zikpefu** [comment]
Hey everyone, I believe that I completed the code but I am unable to push my local branch to as a remote branch, do I need permission or should I have forked the repo?

**Comment by zikpefu** [comment]
> Hey everyone, I completed the code but I am unable to push my local branch to as a remote branch, do I need permission or should I have forked the repo?

Nevermind I figured it out
