### ISSUE TITLE
GitHub Outage: No Github Actions workflows can be run

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#74304]
## Current Status
ongoing

## Error looks like
Jobs failing to schedule, general flakiness of all things GitHub

## Incident timeline (all times pacific)

- 3/16 9:30a incident detected manually, confirmed by checking https://www.githubstatus.com/

## User impact
CI and other things GitHub-related will be flaky for the time being

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by suo** [comment]
Closing as https://www.githubstatus.com/ shows green.

**Comment by janeyx99** [comment]
Dead man switch inadvertently exists since GH1 merges can't go through during these outages (as they rely on GHAs).
