### ISSUE TITLE
[BUG] replicate/reflect padding fails for 2D tensor

### ISSUE THREAD

**Issue by ganler** [pytorch/pytorch#74310]
### 🐛 Describe the bug

```python
import torch
x = torch.zeros((2, 2))

torch.nn.functional.pad(x, (1, 1, 1, 1), mode='constant', value=0) # OK

torch.nn.functional.pad(x, (1, 1, 1, 1), mode='replicate')   # Err
# NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
torch.nn.functional.pad(x, (1, 1, 1, 1), mode='reflect')   # Err
# NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
```

But wait, `x` is a 2D tensor, right? When x is a 4D tensor and we do padding for the last 2 dims, it works. So I think this seems to be a bug?

### Versions

PyTorch version: 1.10.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 3GB
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.10.2
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] torch                     1.10.2                   pypi_0    pypi

**Comment by ganler** [comment]
Adding 4d padding to 5d tensor also throws an exception of "Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now" but it should have been supported according to it.

```python
import torch
torch.nn.functional.pad(torch.ones((1, 1, 1, 1, 1)), (0, 0, 0, 0, 0, 0, 0, 0), mode='replicate')
```

**Comment by himagrawal14** [comment]
i am still getting the above error when pad mode is reflect/replicate. Any solution for this
