### ISSUE TITLE
Lint rule that would fail for PRs containing subdmodule updates

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#74326]
### 🚀 The feature, motivation and pitch

When submodules gets updated after checkout, devs often forget to run `git submodule update` command and propose PR that effectively reverts the update.

Prevent those accidental updates by requiring one to add "submodule-update" keyword to PR description before change can be merged.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by asmita410** [comment]
Hey! I am an absolute beginner, I would like to contribute to this project. Am I allowed to take this up? Also suggest some relevant resources.

**Comment by janeyx99** [comment]
@asmita410 Yes you can take this up and link me for a review with your draft. We anticipate this task will take ~1 week. 

Our lints can be found in this GitHub action yaml https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml. Feel free to Google some resources about GitHub actions in general for more context on the syntax.

For how to get access to the PR body, you can look at https://github.com/pytorch/pytorch/blob/1dab71ab258df5168bb635530a820625f9d4b522/.github/workflows/_linux-test.yml#L82.

For how to get changed files in a PR, you can look at https://github.com/pytorch/pytorch/blob/0effac2b6aa15b5bf5c941b2b44d8762a787ab36/tools/testing/test_selections.py#L158 for a Python implementation or just a shell command.

**Comment by nik1097** [comment]
Hey, @janeyx99 since this issue is not claimed yet, can I try my hand at it?

**Comment by nik1097** [comment]
Hey @janeyx99 could I work on this issue? If it's not already taken?

**Comment by janeyx99** [comment]
@nik1097 when do you think you could have a draft PR by? Since @asmita410 hasn't worked on this in the last 2 weeks, I think you can go for it!

**Comment by nik1097** [comment]
Hey, @janeyx99 thank you for replying. I'm currently working on another issue, and I also see someone else trying to work on it. I will wait for them to complete.

**Comment by janeyx99** [comment]
@nik1097 no worries! have fun with the other issue :) Who do you see working on the issue though? I am unaware of any attempts.

**Comment by k-bishop** [comment]
hey @janeyx99, @nik1097 might be referring to me (I mistakenly opened a PR to the main repo rather than my fork a few days ago). I am sporadically working on this, and happy to take it up if no one has dibs already?

**Comment by janeyx99** [comment]
@k-bishop go for it! do you think you could have a PR ready within 2 weeks?

**Comment by k-bishop** [comment]
@janeyx99 yes i think so

**Comment by k-bishop** [comment]
@janeyx99 sorry for the commit chaos on this. https://github.com/pytorch/pytorch/pull/76212 should be ready for review. It's failing one of the linux test builds on gh actions, which doesn't seem to be related to my change. Is there a way I can rerun that one specific test? Any other suggestions?

**Comment by janeyx99** [comment]
> @janeyx99 sorry for the commit chaos on this. #76212 should be ready for review now. It's failing one of the linux test builds on gh actions, which doesn't seem to be related to my change. Is there a way I can rerun that one specific test? Any other suggestions?

Taking a look now and will respond on the PR itself :) Thanks so much!
