### ISSUE TITLE
ci: Add lint to check for trailing whitespaces in filenames

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#74341]
### 🚀 The feature, motivation and pitch

After the revert of https://github.com/pytorch/pytorch/commit/7cf9b942daa824267ec3902f1026b3e6353561ff we've identified a need to add a lint that checks file names to ensure that they're compatible with Windows machines. 

Observed error: (from example commit)
```
Error: error: invalid path 'test/test_ops_gradients.py '
```

A simple check on changed files to ensure that the file paths do not include trailing whitespace should be sufficient enough for this.

A good place to start to add this would be here: https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml

### Additional context

This could potentially be expanded to include a litany of lints that check for compatibility on Windows. (see https://github.com/git-for-windows/git/issues/2777 for more context)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by hangletn** [comment]
Hi, I would like to work on this issue

**Comment by abhishinde24** [comment]
I would like to work on this issue

**Comment by janeyx99** [comment]
Hi @hangletn, I assigned you as you “claimed” the issue first but feel free to reach out to @abhishinde24 to work together if you’d like!

When you have a PR, I will be happy to review (ping me in a comment).

**Comment by wannieman98** [comment]
Hi, can I work on this? Thanks!

**Comment by duskvirkus** [comment]
@janeyx99 Interested in working on this issue this weekend. Unless @abhishinde24 or @wannieman98 are still interested.

**Comment by janeyx99** [comment]
@abhishinde24 are you still interested? If so, when do you think you could have a draft PR?

@wannieman98 when do you think you'd have a draft PR ready? 

(If there's no response from @abhishinde24 and @wannieman98 by the end of today, @duskvirkus feel free to do it this weekend.)

**Comment by wannieman98** [comment]
> @abhishinde24 are you still interested? If so, when do you think you could have a draft PR?
> 
> 
> 
> @wannieman98 when do you think you'd have a draft PR ready? 
> 
> 
> 
> (If there's no response from @abhishinde24 and @wannieman98 by the end of today, @duskvirkus feel free to do it this weekend.) 

I'll have a draft PR by this weekend!

**Comment by abhishinde24** [comment]
I'll have a draft PR by this weekend!

**Comment by duskvirkus** [comment]
Who ever ends up working on this if it's not too hard maybe including windows reserved file names (like con and aux) for and file names beginning '-' or '--' (cause problems on unix based systems) in when running ci. Don't know if this would bloat the scope of this issue but seems like the goal is not to break compatibility between os. I know first hand that it's very frustrating if you can't clone a repo because it has incompatible file names.

Boost has done a lot of the work on this sort of thing. https://www.boost.org/doc/libs/1_36_0/libs/filesystem/doc/portability_guide.htm

**Comment by janeyx99** [comment]
@abhishinde24 @wannieman98 did either of you get a chance to work on this?

**Comment by tanmoyio** [comment]
I am going to work on it today

**Comment by janeyx99** [comment]
@ykabusalah Yea, feel free! I don't see updates from @tanmoyio in the past 2 weeks so go ahead. Please feel free to ping me in your attempt PR when it is available :D

**Comment by ykabusalah** [comment]
@janeyx99 Thank you! Would you mind assigning me to the item?

**Comment by alcabilone** [comment]
Is someone still trying to fix this? If not i would like to have a try.

**Comment by janeyx99** [comment]
@ykabusalah Do you have any updates?

@alcabilone if there's no response from @ykabusalah by the end of today, feel free to take it.

**Comment by alcabilone** [comment]
Since this is my first attempt at fixing an issue do you have any suggestions as to how i should aproach this?

**Comment by janeyx99** [comment]
@alcabilone To start contributing to pytorch, please check out the CONTRIBUTING.md at the root of the repo. For how to implement this feature, start examining how the git grep lints under quick checks work and seeing if you could come up with a way to write this lint similarly. https://github.com/pytorch/pytorch/blob/master/.github/workflows/lint.yml#L94

If you're curious about how to adapt this into our new lintrunner, pytorch/tools/linter/adapters/newlines_linter.py  is a good model.

**Comment by Priyansh61** [comment]
Hey @janeyx99 we can remove the trailing spaces using git apply as mentioned below ,
`- name: Ensure no trailing whitespaces
    if: always()
    run: |
    # Since git apply will fix all the flags raised by the whitespace 
    # errors and this will not raise any warinig or error
    git apply --whitespace=fix patchname.patch              `
Do let me know if we can merge this code in the lint.yml to check for windows machine ? In case you have any suggestions please mention them too.

**Comment by janeyx99** [comment]
@Priyansh61 do you have a pull request I can look at? For a lint check, we'd like to modify the pull request without the author's permission. It'd be better to plug into the lintrunner infra to give the user the option of fixing.

@alcabilone Any updates?

**Comment by Priyansh61** [comment]
@janeyx99  Right now i am new to lint but i think that's a good opportunity for me to learn about it , so if you could help me by letting me know whether above quick check will be enough to resolve the issue i will raise a pull repuest by making the required changes in the lint.yml file. And if you have any advice for me do let me know??

**Comment by alcabilone** [comment]
im still in the process of understanding lints and how to implement it, sorry for the wait.
