### ISSUE TITLE
lshift and rshift are supported for non-integral inputs and shifts

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#74358]
Pytorch quite nonsensically supports rshift/lshift on non-integral inputs and shifts:
```
In [13]: a=torch.randn(4)

In [14]: a.bitwise_right_shift(2) #there's nothing bitwise about this shift
Out[14]: tensor([-0.0470, -0.0847,  0.0964,  0.0141])

In [15]: a.bitwise_right_shift(1.5) #what does this even mean?
Out[15]: tensor([-0.0664, -0.1198,  0.1363,  0.0200])
```
numpy sensibly errors out in these cases

cc @ezyang
cc @mruberry @rgommers @nairbv

**Comment by vadimkantorov** [comment]
> In [14]: a.bitwise_right_shift(2) #there's nothing bitwise about this shift
> Out[14]: tensor([-0.0470, -0.0847,  0.0964,  0.0141])

Does it do a bitwise shift to the binary representation of floats?
