### ISSUE TITLE
`dim` argument not checked for any of the fixed dimensional `fft` functions

### ISSUE THREAD

**Issue by josh-gleason** [pytorch/pytorch#74380]
### 🐛 Describe the bug

For example `fft.rfft2` and `fft.rfft` are just directly calling `fft.rfftn` without any checks on the arguments (see [torch/fft.h:144](https://github.com/pytorch/pytorch/blob/f445ed19b2fae12abda723001d1c6c7dd857b266/torch/csrc/api/include/torch/fft.h#L144) and [ATen/native/SpectralOps.cpp:604](https://github.com/pytorch/pytorch/blob/299b40de50d2ab3325b6bd77db6eacb9874813b1/aten/src/ATen/native/SpectralOps.cpp#L604)). This means if you provide an `int` for the `dim` argument to `rfft2` instead of a `tuple` it will run without complaint, but will return a 1D FFT along that dim. Similarly if you provide a 3-tuple it will happily return a 3D FFT. This is unexpected behavior as it should raise an exception.

I'm reporting this as a bug because almost every other function in PyTorch has checks on the input arguments so it really seems like a bug that they are omitted in these functions.

### Versions

```none
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.13.4
Libc version: glibc-2.26

Python version: 3.7.5 (default, Dec  9 2021, 17:04:37)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 510.47.03
cuDNN version: 8.0.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect
```

cc @mruberry @peterbell10

**Comment by peterbell10** [comment]
This is intended behaviour as I wrote it to match the `numpy.fft.fft2` function. Quoting the [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.fft.fft2.html)

>[fft2](https://numpy.org/doc/stable/reference/generated/numpy.fft.fft2.html#numpy.fft.fft2) is just [fftn](https://numpy.org/doc/stable/reference/generated/numpy.fft.fftn.html#numpy.fft.fftn) with a different default for axes.
