### ISSUE TITLE
Android nightly builds failing

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#74405]
e.g. https://github.com/pytorch/pytorch/runs/5594619932?check_suite_focus=true

I have disabled the workflow manually for now https://github.com/pytorch/pytorch/actions/workflows/generated-pytorch-linux-xenial-py3-clang5-android-ndk-r19c-build.yml

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Has been fixed a while back, closing
