### ISSUE TITLE
Copying tensors sometimes doesn't copy last N elements when using cuda graphs

### ISSUE THREAD

**Issue by tomconerlyanth** [pytorch/pytorch#74419]
### 🐛 Describe the bug

Copying tensors sometimes doesn't work when using cuda graphs. Occasionally the last N elements aren't copied. See repro: https://gist.github.com/tomconerlyanth/4970244782fd8e02dd99ea8ca8797eec

### Versions

tc-0 (1m) ~/code$ python collect_env.py
Collecting environment information...
PyTorch version: 1.10.0a0+gitee11606
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.156-83.273.amzn2.x86_64-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.4.152
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.921
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytorch-memlab==0.2.4
[pip3] torch==1.10.0a0+gitee11606
[pip3] torch-ops==0.0.1
[pip3] torchtyping==0.1.4
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] mypy                      0.921                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch-memlab            0.2.4                    pypi_0    pypi
[conda] torch                     1.10.0a0+gitee11606          pypi_0    pypi
[conda] torch-ops                 0.0.1                     dev_0    <develop>
[conda] torchtyping               0.1.4                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @mcarilli

**Comment by ngimel** [comment]
Reproes with a pure c++ outside of pytorch, thanks @tomconerlyanth for the reproduction https://gist.github.com/tomconerlyanth/c6e3bc8caddaa1bb628ce98593a26484

**Comment by ptrblck** [comment]
Thanks for the report @tomconerlyanth and @ngimel for the support in isolating the issue.
It should have been fixed by our CUDA team already so I'll close the issue. Please reopen, if you are still running into it.
