### ISSUE TITLE
Tensor "step" in optimizers causing major performance regression in PyTorch XLA after loading optimizer state dict

### ISSUE THREAD

**Issue by ronghanghu** [pytorch/pytorch#74424]
### 🐛 Describe the bug

There is now a major performance regression (1.5X to 4X slower per training iteration) in PyTorch XLA and a minor regression on CUDA after loading optimizer state dict in AdamW and many other optimizers. It happens in the latest master branch on 03/18/2022 (commit `c064ea07f6263090a40b1a6fc5fe5973a76785e5`).

This is caused by the functional change in optimizers (https://github.com/pytorch/pytorch/pull/71333), which changes `state['step']` from `int` to `torch.Tensor` and causes `state['step']` to be pushed to the same device as the parameter upon `load_state_dict`.

Taking AdamW as an example, the error is that
* `state['step']` is originally initialized as a **CPU tensor** in https://github.com/pytorch/pytorch/blob/c064ea07f6263090a40b1a6fc5fe5973a76785e5/torch/optim/adamw.py#L136
* but in `load_state_dict`, all the state tensors (including `state['step']`, `state['exp_avg']`, and `state['exp_avg_sq']`) will be cast to the same device as the parameter in https://github.com/pytorch/pytorch/blob/c064ea07f6263090a40b1a6fc5fe5973a76785e5/torch/optim/optimizer.py#L177
* this causes `state['step']` to be no longer on CPUs after `load_state_dict`, and now it will be a **CUDA tensor** or an **XLA tensor** if the parameter is on CUDA or XLA
* in each training iteration, now `state['step']` needs to be move back to CPU from CUDA or XLA to compute things like `step = step_t.item()` in https://github.com/pytorch/pytorch/blob/c064ea07f6263090a40b1a6fc5fe5973a76785e5/torch/optim/adamw.py#L245 or `bias_correction1 = [1 - beta1 ** step.item() for step in state_steps]` in https://github.com/pytorch/pytorch/blob/c064ea07f6263090a40b1a6fc5fe5973a76785e5/torch/optim/adamw.py#L296
* the overhead is especially great in PyTorch XLA since `step_t.item()` cuts the XLA graph and forces an execution; it also causes a (less severe) performance regression on CUDA due to moving tensors back to CPU

Potential fix:
* one should avoid casting `state['step']` to CUDA or XLA in `load_state_dict` and keep it on CPU
* another (less ideal) fix would be to cast `state['step']` back to CPU somewhere after `load_state_dict`

cc: @JackCaoG 

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+git5372dcd
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-1021-gcp-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.12.0a0+git5372dcd
[pip3] torch-xla==1.11+8ffef19
[pip3] torchvision==0.13.0a0+d8654bb
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @vincentqb @jbschlosser @albanD @bdhirsh

**Comment by ronghanghu** [comment]
Hi @mikaylagawarecki, I wonder if there is an update or an ETA on this issue? It has been blocking our use cases for quite a while, so it would be great if there can be a timeline on this. Thank you!

**Comment by mikaylagawarecki** [comment]
Hi, @ronghanghu I'm sorry for the delay, will push a PR for this today

**Comment by ronghanghu** [comment]
@mikaylagawarecki Sounds great, thanks!

**Comment by mikaylagawarecki** [comment]
@ronghanghu This should be fixed on master now!

**Comment by albanD** [comment]
@ronghanghu can you confirm this is fixed now on your end and we can close this issue?

**Comment by ronghanghu** [comment]
Thanks for the fix! I'll try out the nightly PyTorch build this evening and confirm it tomorrow

**Comment by ronghanghu** [comment]
Following up: I tested the nightly 20220406 PyTorch build and confirm that this issue is fixed now.
