### ISSUE TITLE
Bad formatting of code in documentation

### ISSUE THREAD

**Issue by dhruvbird** [pytorch/pytorch#74433]
### 📚 The doc issue

See https://pytorch.org/docs/stable/_modules/torch/optim/sgd.html#SGD

Here's the docstring is rendered incorrectly. For example:

```
import torch
from . import _functional as F
from .optimizer import Optimizer, required


[[docs]](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html#torch.optim.SGD)class SGD(Optimizer):
    r"""Implements stochastic gradient descent (optionally with momentum).

    .. math::
       \begin{aligned}
            &\rule{110mm}{0.4pt}                                                                 \\
            &\textbf{input}      : \gamma \text{ (lr)}, \: \theta_0 \text{ (params)}, \: f(\theta)
                \text{ (objective)}, \: \lambda \text{ (weight decay)},                          \\
            &\hspace{13mm} \:\mu \text{ (momentum)}, \:\tau \text{ (dampening)},
            \:\textit{ nesterov,}\:\textit{ maximize}                                     \\[-1.ex]
```

### Suggest a potential alternative/fix

Make the markup in the python docstring go away.

cc @brianjo @mruberry @vincentqb @jbschlosser @albanD

**Comment by albanD** [comment]
This is expected. You are looking at the source code there. The actual doc is rendering properly: https://pytorch.org/docs/stable/generated/torch.optim.SGD.html?highlight=sgd#torch.optim.SGD

**Comment by dhruvbird** [comment]
Thanks for the clarification @albanD! Closing!
