### ISSUE TITLE
JIT operations not found in latest NVIDIA Pytorch Docker container

### ISSUE THREAD

**Issue by ppeetteerrs** [pytorch/pytorch#74437]
### 🐛 Describe the bug

When I run the barebones NVIDIA Pytorch container via `docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:22.02-py3 bash`, Pytorch's JIT operations seem to be missing.

```python
import torch
torch._C._jit_get_operation("aten::cudnn_convolution_backward_weight")
```

The error that I got by running the above in the CLI:
```txt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: No such operator aten::cudnn_convolution_backward_weight
```

However, the above code works fine when I use `docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:21.12-py3 bash`

### Versions

**Version with Error**
Docker Image: nvcr.io/nvidia/pytorch:22.02-py3
Pytorch Version: 1.11.0a0+17540c5

**Version without Error**
Docker Image: nvcr.io/nvidia/pytorch:21.12-py3
Pytorch Version: 1.11.0a0+b6df043

**Comment by davidberard98** [comment]
@ppeetteerrs this op was removed. See the "Convolution consolidation" section in https://dev-discuss.pytorch.org/t/state-of-pytorch-core-september-2021-edition/332, and https://docs.google.com/document/d/123O-v7Ov7VmoRiJrZYEon_L2j0vLTf0Y5UFJKgyuqxE

**Comment by ppeetteerrs** [comment]
Thanks for the information. Can I confirm that the only way to get the new general `convolution_backwards` operations is by using `torch._C._jit_get_operation("aten::convolution_backward")? It doesn't seem to be exposed anywhere in the Python API.

**Comment by davidberard98** [comment]
@ppeetteerrs I think you can also use `torch.ops.aten.convolution_backward`

cc @jbschlosser do you know the preferred way to access this op?

**Comment by sklin93** [comment]
> 

@davidberard98 What op should I call now to replace `aten::cudnn_convolution_backward_weight` and `aten::cudnn_convolution_transpose_backward_weight`? The context is the custom op for StyleGAN ([here](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/torch_utils/ops/conv2d_gradfix.py#L143))

Thank you

**Comment by davidberard98** [comment]
@sklin93 I think `aten::convolution_backward` should work. It has a bool option to whether or not to transpose, and you can pass a list of booleans (bool[] output_mask) to compute grad for only weight.

**Comment by sklin93** [comment]
@davidberard98 Thanks! I'm trying that, but what `bias_sizes` should I pass to the function? It seems to be a required arg.

**Comment by davidberard98** [comment]
It should be the shape of the bias tensor that was provided to the pass. Or if bias was none, you can pass `None` as the sizes.

From native_functions.yaml:

```
- func: convolution_backward(Tensor grad_output, Tensor input, Tensor weight, int[]? bias_sizes, int[] stride, int[] padding, int[] dilation, bool transposed, int[] output_padding, int groups, bool[3] output_mask) -> (Tensor, Tensor, Tensor)
```

The question mark in the type annotation `int[]?` means that it is optional, i.e. it can take None as a parameter

**Comment by sklin93** [comment]
@davidberard98 thank you!
I made these [changes](https://www.diffchecker.com/68YsfWVW) to the previously linked [code](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/6f160b3d22b8b178ebe533a50d4d5e63aedba21d/torch_utils/ops/conv2d_gradfix.py). Basically I need to pass `weight` instead of `weight_shape` to the new `torch.ops.aten.convolution_backward` function. But I get the following error:

```
 File "xxx/conv2d_gradfix.py", line 132, in backward
    grad_weight = Conv2dGradWeight.apply(grad_output, input, bias)
  File "xxx/conv2d_gradfix.py", line 145, in forward
    grad_weight = torch.ops.aten.convolution_backward(grad_output, input, weight,
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

I'm not sure if I should change any tensor's type, and to Half or Float...

**Comment by davidberard98** [comment]
You'll probably need to convert one of the tensors to the correct type. If you're concerned with performance issues from casting tensors, you can experiment with passing empty tensors with correct shape information (e.g. create a small tensor and then torch.expand it to the correct size) - some of the data might not be important to the computation so it might be fine to pass empty tensors for some of the inputs

**Comment by sklin93** [comment]
@davidberard98 thanks!! That's a very good idea since the weight is only used for its shape. I passed `empty_weight = torch.empty(weight_shape, dtype=input.dtype, layout=input.layout, device=input.device)` to the op.

Could you take a look at the [changes](https://www.diffchecker.com/0rXiySXB)? It runs without any problem (!) but I want to make sure I didn't accidentally mess something up. It's only a few changes now.

**Comment by jbschlosser** [comment]
@sklin93 your changes look good, but I'd recommend one tweak to reduce memory usage. Instead of:
```python
empty_weight = torch.empty(weight_shape, dtype=input.dtype, layout=input.layout, device=input.device)
```

you should do:
```python
empty_weight = torch.tensor(0.0, dtype=input.dtype, layout=input.layout, device=input.device).expand(weight_shape)
```

The former allocates memory for a tensor of shape `weight_shape` with undefined values, while the latter allocates memory for only a single element and views it as the correct shape.

**Comment by sklin93** [comment]
> @sklin93 your changes look good, but I'd recommend one tweak to reduce memory usage. Instead of:
> 
> ```python
> empty_weight = torch.empty(weight_shape, dtype=input.dtype, layout=input.layout, device=input.device)
> ```
> 
> you should do:
> 
> ```python
> empty_weight = torch.tensor(0.0, dtype=input.dtype, layout=input.layout, device=input.device).expand(weight_shape)
> ```
> 
> The former allocates memory for a tensor of shape `weight_shape` with undefined values, while the latter allocates memory for only a single element and views it as the correct shape.

thank you!

**Comment by dave-epstein** [comment]
Thanks to both - this thread has been very helpful. However when I train a model with the path length penalty, I get this error: `RuntimeError: function Conv2dGradWeightBackward returned an incorrect number of gradients (expected 3, got 2)`

I'm trying to poke around and see if I can find a fix but would appreciate if @sklin93 or someone else had any ideas too.

Thanks!

**Comment by sklin93** [comment]
> 



> 

I don't have this problem when training with the pl_penalty. And since the backward function of Conv2dGradWeight isn't changed, I think it shouldn't affect the training part?

Did you change other parts of conv2d_gradfix.py accordingly (adding the bias)?

**Comment by dave-epstein** [comment]
@sklin93  - yes, I did, and I think that's the issue. I modified `return grad2_grad_output, grad2_input` to `return grad2_grad_output, grad2_input, None` and it works now without erroring. Just not sure if returning `None` is fine here. 

Maybe the difference in behavior is due to PyTorch version differences or something -- I'm on the latest.

**Comment by jbschlosser** [comment]
@dave-epstein do you have a link to your modifications? I'm happy to do a sanity check for you

**Comment by leeskyed** [comment]
It is better to use an older version like pytorch 1.8.1.



> @dave-epstein do you have a link to your modifications? I'm happy to do a sanity check for you
