### ISSUE TITLE
CUDA out of memory problem in Pytorch 0.4

### ISSUE THREAD

**Issue by yqy** [pytorch/pytorch#7445]
## Issue description
I have implemented a tensorflow project by pytorch. However, I meet a problem of "CUDA out of memory" when calculating the gradient.

 - Does pytorch requires more GPU memory than tensorflow?
 - Or is there any suggestions for saving memory?

Thanks a lot!

**Comment by gwgundersen** [comment]
This isn't a bug or feature request. I think you should close this and ask your question on the [PyTorch forums](https://discuss.pytorch.org/).
