### ISSUE TITLE
with-ssh regression as now the relevant login information is hidden within a composite action

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#74476]
cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Does it not show output?

**Comment by suo** [comment]
It shows, but it's hidden inside another action so it's hard to find:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/1617424/159320449-efe0d432-aba4-4fd5-9246-8bd3444ab18b.png">

I'll put up a PR to pull it out to the top level

**Comment by seemethere** [comment]
https://github.com/pytorch/pytorch/pull/74773 should resolve
