### ISSUE TITLE
CI workflow consolidation tracking issue

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#74475]
This is a tracking issue for any problems that arise due to workflow consolidation. Description of the changes below.

Known issues:
- [x] #74476
- [x] #74777
- [ ] #74478
- [x] #74480
- [x] Flaky test bot is broken 
----

We are making some changes to the implementation of the PyTorch OSS CI so that it’s easier to use, more understandable, and more maintainable. Here is a list of changes, from most general to most power-user-specific.

**All pull request CI runs in a single workflow**. This makes it easier to see results in the [default PR checks view](https://github.com/pytorch/pytorch/pull/74469/checks), and (with recent improvements on the GitHub side) means you can *[rerun all failed PR CI jobs with one click](https://github.blog/2022-03-16-save-time-partial-re-runs-github-actions/)*! We are truly the pinnacle of modern technology.

**CIFlow tags have been simplified**. We had many tags with overlapping coverage that needed to be manually maintained. In practice, people rarely used the “topic” labels and opted to just run everything (e.g. ciflow/all). Now, the tags map directly onto workflows. Want to run all of trunk CI? Use the ciflow/trunk label. Want to run nightlies? Use the ciflow/nightly label, etc. Our bot will tell you if you are using a defunct label.

**Codegen has been eliminated, making the CI easier to understand.** The previous codegen system evolved piecemeal over time and became [somewhat Lovecraftian](https://github.com/pytorch/pytorch/blob/ec071a0815adfd180ba1ab103be2f7d2227f07cc/.github/templates/common.yml.j2#L25-L56). After eliminating codegen, it is much easier to understand what runs on pull request vs. trunk, and what test configurations are actually being run.

For technical details of the actual changes, see: https://fb.quip.com/RcLZAOb9k0qI (or ping me if you care and are not a Meta employee)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Flaky test bot https://github.com/pytorch/test-infra/issues/263

**Comment by malfet** [comment]
with-ssh no longer has "Wait for 2 hours or until sessions are drained", which makes it quite useless for debugging anything after CI failed
