### ISSUE TITLE
Make our functions have correct __module__ information / way to get human readable name for func in __torch_function__

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#74483]
### 🐛 Describe the bug

A common thing to want to do when writing a `__torch_function__` override is to get a human readable name of the func you were passed. Unfortunately, the obvious logic using `__module__` and `__name__` does not work because many functions do not correctly have `__module__` information attached to them.

As a result, there are multiple workarounds for this problem:

* FX https://github.com/pytorch/pytorch/blob/3d6317cbe07a97191991552bebf5a7983fc88910/torch/fx/node.py#L64
* torchdynamo https://github.com/facebookresearch/torchdynamo/blob/00d2af529dc2c98ee201b9503e26bece468d07ea/torchdynamo/allowed_functions.py#L46

Either fix `__module__` so it can be relied upon, or reify the internal hacks into an API that people can use (put it in torch.overrides)

### Versions

master

cc @hameerabbasi @rgommers @peterbell10

**Comment by albanD** [comment]
For context, this is part of the larger Public API cleanup as well as discussed in [this doc](https://docs.google.com/document/d/10yx2-4gs0gTMOimVS403MnoAWkqitS8TUHX73PN8EjE/edit?pli=1#)

**Comment by ezyang** [comment]
use `resolve_name`
