### ISSUE TITLE
cannot log in into with-ssh ci jobs via jumphost

### ISSUE THREAD

**Issue by nkaretnikov** [pytorch/pytorch#74489]
### 🐛 Describe the bug

We (quansight) use a jumphost to ssh into CI jobs. ~i'm not sure this ever worked tbh, but when i tried it a month+ ago, it didn't~. This worked for some time after it was set up on Jan 10th, however it hasn't worked for at least a month. upd: it might be related to the fact that the jumphost changed its ip address at some point. I don't want to list the actual hostnames here or share any infra details, but the command i tried is this:

```
ssh -J <jumphost> <ci-job>
```

which returned:

```
Host key verification failed.
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port <portnum>
```

yes, this was a pr with the `with-ssh` label and an active job, as described here:

(upd: when i tried ssh'ing into a job, it was done immediately, so this shouldn't apply either: "The default timeout for these jobs is 2 hours after workflows have completed, but only if you SSH in before the end of the job")

https://github.com/pytorch/pytorch/wiki/Debugging-using-with-ssh-for-Github-Actions#workflow-for-users

i didn't test the whole thing yesterday, but i did try ssh'ing into a different machine via the jumphost, which worked. so i'm assuming it's an issue on the ci infra side.

could anyone with access to everything (our jumphost and ci infra) test the whole pipeline? ty!

(if you want additional details, feel free to ping me on slack. i was asked to create this issue, so it could be tracked/assigned to someone.)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by nkaretnikov** [comment]
hello, any update on this?

**Comment by seemethere** [comment]
Hey! Wanted to update this, wasn't able to reproduce your issue and could use the jumphost fine like so:
```
❯ ssh -J seemethere@<jumphost> ec2-user@ec2-52-207-253-226.compute-1.amazonaws.com
The authenticity of host 'ec2-52-207-253-226.compute-1.amazonaws.com (<no hostip for proxy command>)' can't be established.
ED25519 key fingerprint is SHA256:jUETQzsm8DIBvj5AoF4NCIm0nCaPRXIhKIhJmv7iRZg.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'ec2-52-207-253-226.compute-1.amazonaws.com' (ED25519) to the list of known hosts.

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[ec2-user@ip-10-0-2-199 ~]$ ls
actions-runner
```

Are you sure you removed the original jumphost from your `~/.ssh/known_hosts` file?

**Comment by nkaretnikov** [comment]
hmm, indeed, i re-ran the job you mention and was able to ssh into it using the login in the "setup ssh" phase (using the jumphost ip i provided on slack).

i don't think i did anything differently tho.
- could it be that i used a different jumphost ip address? maybe, but i'd say it's unlikely.
- could it be that something wasn't right when the job was scheduled? maybe some issue with the "with-ssh" label? i think i re-ran the jobs after setting the label, but it's hard to recall now.
- i also remember that i was trying to ssh into one of the test jobs and this one is a build? could it be the reason?
- i'm pretty sure the job was active when i tried it. could it be that the timeout for ssh-ing into a job is not long enough?

**Comment by seemethere** [comment]
For the original error mentioned:
```
Host key verification failed.
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port <portnum>
```

This is typically indicative of an outdated host key that's stored in your `~/.ssh/known_hosts file` ([reference](https://www.thegeekdiary.com/how-to-fix-the-error-host-key-verification-failed/)).

Since you had previously used the jumphost the old host key for the old jumphost was probably stored in your local `~/.ssh/known_hosts` file. To resolve this in the future you just have to delete the old entry.
