### ISSUE TITLE
[Caffe2] Are you still maintaining Caffe2 docker?

### ISSUE THREAD

**Issue by jgong5** [pytorch/pytorch#7450]
## Issue description

I found the tags are really old. Are you still maintaining the docker release? Thanks.

## Code example

https://hub.docker.com/r/caffe2ai/caffe2/tags/

**Comment by yinghai** [comment]
@pjh5 Are we stiff maintaining docker files?

**Comment by pjh5** [comment]
These seem more up to date https://hub.docker.com/r/caffe2/caffe2/ . But @pietern would know for sure.

**Comment by jgong5** [comment]
@pjh5 Does the build include the recently integrated CPU-based optimization (iDeep/MKL-DNN)?

**Comment by jgong5** [comment]
@pjh5 May I know how often the latest caffe2 docker would be published?

**Comment by pjh5** [comment]
@jgong5 what is your use case for the docker images? I do not think we have a plan to push the docker images at the moment. Can you get around this by using conda-packages or building from source?

**Comment by jgong5** [comment]
@pjh5 I was asking because we are adding MKL-DNN based optimization for Caffe2 CPU devices recently and hope that these optimizations can be easily available to the end users, e.g. via docker images.

**Comment by pjh5** [comment]
@jgong5 you can build off of our Dockerfiles at https://github.com/pytorch/pytorch/tree/master/docker/caffe2/jenkins/ubuntu and the script in docker/caffe2/jenkins/build.sh . We only use these Dockers for our CI, so they're not especially user friendly. I'd recommend writing your own Dockerfile that includes a conda-install of Caffe2. If you have any requested changes to the conda packages then let me know.

**Comment by jgong5** [comment]
@pjh5 Thanks for the suggestion.

**Comment by drcege** [comment]
@jgong5 
I think it's better to update the Caffe2 images. Because the Detectron Dockerfile is based on Caffe2 base. 
It's inconvenient to build our own Caffe2 while I just want to use Detectron.

**Comment by jgong5** [comment]
@drcege Agreed.

**Comment by pjh5** [comment]
@drcege @jgong5 I agree that that would be nice, but I don't think we have the bandwidth for maintaining the docker images right now. We use them pretty heavily for our CI and testing PRs, so we like to be able to change them quickly to suit our testing needs without worry of breaking end-users.

However, we are actively trying to support easy binary installs. If ease of use is all that you need, then hopefully you can install Caffe2 easily with a variant of "conda install -yc caffe2 caffe2" (pip installs hopefully coming soon as well). You should also be able to put this into a dockerfile with something like
""
FROM continuumio:anaconda
#  some user setup
RUN conda install -yc caffe2 caffe2
# other docker commands
