### ISSUE TITLE
torchscript model got different results from first and subsequent inferences 

### ISSUE THREAD

**Issue by wangyunxiaa** [pytorch/pytorch#74534]
### 🐛 Describe the bug

when I traced a model with torch.jit.trace, I got the torchscript model
     
```
        sig, *_ = model_half(in1.half(), in2.half(), in3)
        print("output_sig-222", sig.shape, sig)
        sig, *_ = model_half(in1.half(), in2.half(), in3)
        print("output_sig-333", sig.shape, sig)

        traced_model = torch.jit.trace(model_half,(in1.half(),in2.half(),in3))  #got torch script model
        traced_model_out, *_ = traced_model(in1.half(),in2.half(),in3)
        print("trace model output", traced_model_out.shape, traced_model_out)   #the first time do inference same as python
        traced_model_out, *_ = traced_model(in1.half(),in2.half(),in3)
        print("trace model output-1", traced_model_out.shape, traced_model_out)   #the second time do inference is different
        torch.jit.save(traced_model,"model_half.pt")
        jitmodel = torch.jit.load("model_half.pt")   #saved and load the torch script model
        sig, *_ = jitmodel(in1.half(), in2.half(), in3)
        print("jitmodel output_sig-3", sig.shape, sig)  #the first time do inference same as python
        sig, *_ = jitmodel(in1.half(), in2.half(), in3)
        print("jitmodel output_sig-4", sig.shape, sig) #the second time do inference is different

        #repeat to reload the model from file, also got same result in first time but different after second time
        jitmodel = torch.jit.load("model_half.pt")
        sig, *_ = jitmodel(in1.half(), in2.half(), in3)
        print("jitmodel output_sig-5", sig.shape, sig)
        sig, *_ = jitmodel(in1.half(), in2.half(), in3)
        print("jitmodel output_sig-6", sig.shape, sig)


output_sig-222 torch.Size([1, 1, 215280]) tensor([[[-1.0669e-05, -5.5969e-05, -7.6830e-05,  ...,  4.5061e-05, -8.3447e-06, -4.5121e-05]]],
         device='cuda:0', dtype=torch.float16)
  output_sig-333 torch.Size([1, 1, 215280]) tensor([[[-1.0669e-05, -5.5969e-05, -7.6830e-05,  ...,  4.5061e-05, -8.3447e-06, -4.5121e-05]]],
         device='cuda:0', dtype=torch.float16)
  trace model output torch.Size([1, 1, 215280]) tensor([[[-1.0669e-05, -5.5969e-05, -7.6830e-05,  ...,  4.5061e-05, -8.3447e-06, -4.5121e-05]]],
         device='cuda:0', dtype=torch.float16)
  trace model output-1 torch.Size([1, 1, 215280]) tensor([[[-7.9274e-06, -5.5730e-05, -7.8678e-05,  ...,  4.3869e-05, -7.8082e-06, -4.3750e-05]]],
         device='cuda:0', dtype=torch.float16)
  jitmodel output_sig-3 torch.Size([1, 1, 215280]) tensor([[[-1.0669e-05, -5.5969e-05, -7.6830e-05,  ...,  4.5061e-05, -8.3447e-06, -4.5121e-05]]],
         device='cuda:0', dtype=torch.float16)
  jitmodel output_sig-4 torch.Size([1, 1, 215280]) tensor([[[-7.9274e-06, -5.5730e-05, -7.8678e-05,  ...,  4.3869e-05, -7.8082e-06, -4.3750e-05]]],
         device='cuda:0', dtype=torch.float16)
  jitmodel output_sig-5 torch.Size([1, 1, 215280]) tensor([[[-1.0669e-05, -5.5969e-05, -7.6830e-05,  ...,  4.5061e-05, -8.3447e-06, -4.5121e-05]]],
         device='cuda:0', dtype=torch.float16)
  jitmodel output_sig-6 torch.Size([1, 1, 215280]) tensor([[[-7.9274e-06, -5.5730e-05, -7.8678e-05,  ...,  4.3869e-05, -7.8082e-06, -4.3750e-05]]],
         device='cuda:0', dtype=torch.float16)
```

### Versions

PyTorch version: 1.8.1+5935cd5
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.67
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 460.56
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-asr==0.4.2.dev0+g9792fd3.d20210319
[pip3] torch==1.8.1+5935cd5
[pip3] warpctc-pytorch==0.2.1
[conda] blas                      1.0                         mkl  
[conda] magma-cuda112             2.5.2                         1    <unknown>
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] torch                     1.8.1+5935cd5            pypi_0    pypi
[conda] warpctc-pytorch           0.2.1                    pypi_0    pypi

**Comment by davidberard98** [comment]
@wangyunxiaa, thanks for the report.

On the second invocation of the scripted function, NNC is probably fusing some of the ops to improve performance. You can read more about it [here](https://dev-discuss.pytorch.org/t/nnc-walkthrough-how-pytorch-ops-get-fused/125). During the first invocation information is recorded about the inputs; and on the second invocation the kernels will get fused by NNC.

The fused ops will represent the same mathematical function, but because of the different implementation, there can be numerical differences between the unfused and fused implementations. This could be the reason why the model is giving different results on subsequent inferences, especially considering that half precision has less accuracy.

You can disable NNC with `torch._C._jit_set_texpr_fuser_enabled(False)`. This will prevent the fusions from occuring, but it could also reduce performance.

However, if you think error is larger than expected considering the accuracy of half precision numbers and the details of your model, please let us know.

**Comment by wangyunxiaa** [comment]
Thank you very much for your reply!
with `torch._C._jit_set_texpr_fuser_enabled(False)` all results are consistent.
the half mode got a little error,but it does not affect the final result.

**Comment by wangyunxiaa** [comment]
> @wangyunxiaa, thanks for the report.
> 
> On the second invocation of the scripted function, NNC is probably fusing some of the ops to improve performance. You can read more about it [here](https://dev-discuss.pytorch.org/t/nnc-walkthrough-how-pytorch-ops-get-fused/125). During the first invocation information is recorded about the inputs; and on the second invocation the kernels will get fused by NNC.
> 
> The fused ops will represent the same mathematical function, but because of the different implementation, there can be numerical differences between the unfused and fused implementations. This could be the reason why the model is giving different results on subsequent inferences, especially considering that half precision has less accuracy.
> 
> You can disable NNC with `torch._C._jit_set_texpr_fuser_enabled(False)`. This will prevent the fusions from occuring, but it could also reduce performance.
> 
> However, if you think error is larger than expected considering the accuracy of half precision numbers and the details of your model, please let us know.

**Comment by wangyunxiaa** [comment]
I also encountered a strange problem, after the model is converted to torchscript, it will require more GPU memory than ori python script, the torch script model using python API to do inference, and I have added `model.eval()   with torch.no_grad()` in forward function
when i add with torch.no_grad() before do inference I got an error in second time:
```
decoder = torch.jit.load(sys.argv[1])
with torch.no_grad():
        out = decoder(input1, input2, input3)
```
the error is
```
Traceback (most recent call last):

  File "test_script_model.py", line 88, in <module>

    main()

  File "test_script_model.py", line 73, in main

    out = decoder(input1, input2, input3)

  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl

    result = self.forward(*input, **kwargs)

RuntimeError: _Map_base::at
```

**Comment by davidberard98** [comment]
@wangyunxiaa could you try running with the environment variable `TORCH_SHOW_CPP_STACKTRACES=1` and dump the output ?

e.g.
```
$ TORCH_SHOW_CPP_STACKTRACES=1 python3 myprogram.py
```

(and if you have an easy repro that you can share that would be great as well)

**Comment by wangyunxiaa** [comment]
sorry for the late reply, the problem was solved.
Thanks very much for your suggestion
