### ISSUE TITLE
Different pytorch version consume a different amount of VRAM

### ISSUE THREAD

**Issue by Wang-Tianyu** [pytorch/pytorch#74536]
### 🐛 Describe the bug

I notice that when I run the same code on the same machine with a different version of PyTorch I get different VRAM consumption.

With PyTorch 1.10.2 installed around Dec 2021 and Pytorch 1.8.1 installed around May 2021, my code can run without problem.
But with Pytorch 1.8.1 and PyTorch 1.11.0 installed this week I get Cuda out of memory error.

Interestingly, the error I get is
CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 10.76 GiB total capacity; 839.97 MiB already allocated; 2.88 MiB free; 958.00 MiB reserved in total by PyTorch)
I am using a RTX 2080ti which has 11G memory.
The nvidia-smi does show that all memory is used up but the number in the error message does not add up.
I am sure that no other packages claim VRAM in the same code.

My code is complicated so I cannot find a minimum working example.
Please let me know how I can provide more useful information regarding this problem.

################# pytorch 1.8.1 that induce CUDA out of memory #################

PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.17.0-rc1
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-105-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.8.1
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.1
[pip3] torch-scatter==2.0.8
[pip3] torch-sparse==0.6.12
[pip3] torch-spline-conv==1.2.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89             h8f6ccaa_10    conda-forge
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pyg                       2.0.1           py39_torch_1.8.0_cu102    pyg
[conda] pytorch                   1.8.1           py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-cluster           1.5.9           py39_torch_1.8.0_cu102    pyg
[conda] pytorch-scatter           2.0.8           py39_torch_1.8.0_cu102    pyg
[conda] pytorch-sparse            0.6.12          py39_torch_1.8.0_cu102    pyg
[conda] pytorch-spline-conv       1.2.1           py39_torch_1.8.0_cu102    pyg

################# pytorch 1.10.2 that works #################

PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.17.0-rc1
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-105-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.2
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.3
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.10.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89             h8f6ccaa_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pyg                       2.0.3           py39_torch_1.10.0_cu102    pyg
[conda] pytorch                   1.10.2          py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-cluster           1.5.9           py39_torch_1.10.0_cu102    pyg
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.0.9           py39_torch_1.10.0_cu102    pyg
[conda] pytorch-sparse            0.6.12          py39_torch_1.10.0_cu102    pyg
[conda] pytorch-spline-conv       1.2.1           py39_torch_1.10.0_cu102    pyg
[conda] torchaudio                0.10.2               py39_cu102    pytorch
[conda] torchvision               0.11.3               py39_cu102    pytorch

cc @ngimel

**Comment by VitalyFedyunin** [comment]
Can you try to initialize cuda (without running any code) and compare memory consumption of CUDA context.

**Comment by Wang-Tianyu** [comment]
> Can you try to initialize cuda (without running any code) and compare memory consumption of CUDA context.

pytorch1.8.1 uses 934 MB, pytorch1.10.2 uses  992MB while pytorch1.11.0 uses 1106 MB.
I think the extra 100~200MB memory consumption increase can explain the different behaviors since my model uses almost all VRAM when it works.
Thanks for your help.
