### ISSUE TITLE
RuntimeError: Preprocessing function for backend coreml is not registered.

### ISSUE THREAD

**Issue by arccos2002** [pytorch/pytorch#74541]
### 🐛 Describe the bug

I'm trying to follow the iOS coreml workflow https://pytorch.org/tutorials/prototype/ios_coreml_workflow.html for my model but I am getting the error "Preprocessing function for backend coreml is not registered". 
torch:1.11.0+cu102
python:3.7

### Versions

torch:1.11.0+cu102
python:3.7

**Comment by RyosukeFukatani** [comment]
I found same issue.

### Environment
Mac OS X
python: 3.9
torch==1.10.2
coremltools==5.1

**Comment by jmdetloff** [comment]
Closing, as we don't have a repro, but if OP is still struggling feel free to re-open and ping with current details.
