### ISSUE TITLE
[feature request] add nn.init.zeros_ and nn.init.ones_

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/pytorch#7454]
`nn.int.ones_(module.weight)` is always more readable than `nn.init.constant_(module.weight, 1)`, and for `nn.init.zeros_` as well.

**Comment by karandwivedi42** [comment]
You can use `module.bias.zero_()` and `module.weight.fill_(1)` also.

**Comment by soumith** [comment]
@karandwivedi42 `modile.bias.zero_()` would've done an autograd `zero_()` because `module.bias` requires grad.

**Comment by karandwivedi42** [comment]
Sorry, still getting used to 0.4. @soumith I can raise a PR for this if it's a go-ahead.
