### ISSUE TITLE
[PyTorch][Feature Request] Label Smoothing for CrossEntropyLoss

### ISSUE THREAD

**Issue by KaiyuYue** [pytorch/pytorch#7455]
Hi, guys. The type `torch.LongTensor` of target will hinder the implementation like some methods in [reference](https://arxiv.org/abs/1512.00567). So is there a possible to add a `Arg: label_smoothing` for `torch.nn.CrossEntropyLoss()`, or maybe simply add the docs to show how to convert the `target` into `one-hot vector` to work with `torch.nn.CrossEntropyLoss()` together, or any other simple ways? Thanks.

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @mruberry

**Comment by whr94621** [comment]
@KaiyuYue 
For label_smoothing, you cat look at the implementation of [NJUNMT-pytorch](https://github.com/whr94621/NJUNMT-pytorch)

In the class ```NMTCritierion```

https://github.com/whr94621/NJUNMT-pytorch/blob/aff968c0da9273dc42eabbb8ac4e459f9195f6e4/src/modules/criterions.py#L131

**Comment by mdraw** [comment]
See https://discuss.pytorch.org/t/cross-entropy-with-one-hot-targets/13580/5. The `cross_entropy()` function that's shown there should work with smoothed labels that have the same dimension as the network outputs.

I don't think `CrossEntropyLoss()` should directly support a `label_smoothing` option, since label smoothing can be done in many different ways and the smoothing itself can be easily done manually by the user. But I agree it should at least be mentioned in the docs how to deal with targets that can't be represented by scalar values, or add support for passing (k-hot/smoothed) targets to `CrossEntropyLoss`.

**Comment by Jiaming-Liu** [comment]
Maybe we need sth like `NonSparseCrossEntropy`? (well.. it's hard to name it)

**Comment by PistonY** [comment]
Here is my implement
```python
class LabelSmoothingLoss(nn.Module):
    def __init__(self, classes, smoothing=0.0, dim=-1):
        super(LabelSmoothingLoss, self).__init__()
        self.confidence = 1.0 - smoothing
        self.smoothing = smoothing
        self.cls = classes
        self.dim = dim

    def forward(self, pred, target):
        pred = pred.log_softmax(dim=self.dim)
        with torch.no_grad():
            # true_dist = pred.data.clone()
            true_dist = torch.zeros_like(pred)
            true_dist.fill_(self.smoothing / (self.cls - 1))
            true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
        return torch.mean(torch.sum(-true_dist * pred, dim=self.dim))
```

**Comment by PistonY** [comment]
I agree with @mdraw 
A good choice is do it in two step:
1. Use a function to get smooth label
```python
def LabelSmoothing(true_labels: torch.Tensor, classes: int, smoothing=0.0):
    """
    true_labels shape should be (batch_size, )
    if smoothing==0, it's also a one-hot function
    """
    confidence = 1.0 - smoothing
    with torch.no_grad():
        true_dist = torch.empty(size=(true_labels.size(0), classes), device=true_labels.device)
        true_dist.fill_(smoothing / (classes - 1))
        true_dist.scatter_(1, true_labels.data.unsqueeze(1), confidence)
    return true_dist
```
2. Make `CrossEntropyLoss` support k-hot/smoothed targets.

Then we can use it like
```python
Loss = CrossEntropyLoss(NonSparse=True, ...)
. . .
data = ...
labels = ...

outputs = model(data)

smooth_label = LabelSmoothing(labels, ...)
loss = (outputs, smooth_label)
...

```

By the way I tested my implement on ImageNet, it looks good

|model | epochs| dtype |batch size*|gpus  | lr  |  tricks|top1/top5  |improve |
|:----:|:-----:|:-----:|:---------:|:----:|:---:|:------:|:---------:|:------:|
|resnet50|120  |FP16   |128        | 8    |0.4  | -      |77.35/-    |baseline|
|resnet50|120  |FP16   |128        | 8    |0.4  |Lable smoothing|77.78/93.80| +0.43 |

**Comment by ezyang** [comment]
I believe @zhangguanheng66 said that this is something he might be able to look at in the future.

**Comment by suanrong** [comment]
Just use torch.nn.KLDivLoss. It is the same.

**Comment by sadikneipp** [comment]
I believe this is similar to what the new Snorkel lib implemented:
https://snorkel.readthedocs.io/en/master/packages/_autosummary/classification/snorkel.classification.cross_entropy_with_probs.html

Just some extra info on how people are going around the issue

**Comment by Data-drone** [comment]
see https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Classification/RN50v1.5 for how Nvidia do it that might help?

**Comment by suanrong** [comment]
> Just use torch.nn.KLDivLoss. It is the same.

Unbelievable！There are 5 thumb down given to me？why？ 

The only different between KL divergence and Crossentropy is a constant in this way and it would not be taken to the optimization.

**Comment by steermomo** [comment]
@suanrong Thanks a lot.

**Comment by huanglianghua** [comment]
Suggested implementation:

```Python
class LabelSmoothLoss(nn.Module):
    
    def __init__(self, smoothing=0.0):
        super(LabelSmoothLoss, self).__init__()
        self.smoothing = smoothing
    
    def forward(self, input, target):
        log_prob = F.log_softmax(input, dim=-1)
        weight = input.new_ones(input.size()) * \
            self.smoothing / (input.size(-1) - 1.)
        weight.scatter_(-1, target.unsqueeze(-1), (1. - self.smoothing))
        loss = (-weight * log_prob).sum(dim=-1).mean()
        return loss
```

I have checked that:
(1) When smoothing=0.0, the output is the same as `nn.CrossEntropyLoss` within precision `1e-5`.
(2) When smoothing>0.0, the sums of weights over different classes `weight.sum(dim=-1)` are always 1.

**Comment by hadaev8** [comment]
Implementations here lack of class weights feature.
((

**Comment by alshahrani2030** [comment]
> Just use torch.nn.KLDivLoss. It is the same.

can you please elaborate more

**Comment by suanrong** [comment]
> > Just use torch.nn.KLDivLoss. It is the same.
> 
> can you please elaborate more

Assumed you already have smoothed label, you can just use torch.nn.KLDivLoss since the difference between them is entropy of the label and is a constant.

**Comment by jasstionzyf** [comment]
@PistonY why not use this way much simple:
`    with torch.no_grad():
        confidence = 1.0 - smoothing_factor

        true_dist = torch.mul(labels, confidence)
        print(smoothing_factor / (classNum - 1))

        true_dist = torch.add(true_dist, smoothing_factor / (classNum - 1))
        print(true_dist)`

**Comment by skull3r7** [comment]
> Implementations here lack of class weights feature.

Can i multiply the class weights on the smoothed label tensor?

**Comment by jphdotam** [comment]
> I agree with @mdraw
> A good choice is do it in two step:
> 
> 1. Use a function to get smooth label
> 
> ```python
> def smooth_one_hot(true_labels: torch.Tensor, classes: int, smoothing=0.0):
>     """
>     if smoothing == 0, it's one-hot method
>     if 0 < smoothing < 1, it's smooth method
> 
>     """
>     assert 0 <= smoothing < 1
>     confidence = 1.0 - smoothing
>     label_shape = torch.Size((true_labels.size(0), classes))
>     with torch.no_grad():
>         true_dist = torch.empty(size=label_shape, device=true_labels.device)
>         true_dist.fill_(smoothing / (classes - 1))
>         true_dist.scatter_(1, true_labels.data.unsqueeze(1), confidence)
>     return true_dist
> ```
> 
> 1. Make `CrossEntropyLoss` support k-hot/smoothed targets.
> 
> Then we can use it like
> 
> ```python
> Loss = CrossEntropyLoss(NonSparse=True, ...)
> . . .
> data = ...
> labels = ...
> 
> outputs = model(data)
> 
> smooth_label = smooth_one_hot(labels, ...)
> loss = (outputs, smooth_label)
> ...
> ```
> 
> By the way I tested my implement on ImageNet, it looks good
> 
> model	epochs	dtype	batch size*	gpus	lr	tricks	top1/top5	improve
> resnet50	120	FP16	128	8	0.4	-	77.35/-	baseline
> resnet50	120	FP16	128	8	0.4	Lable smoothing	77.78/93.80	+0.43

I think the sanity check `assert 0 <= smoothing < 1` should be more strict. Where n_classes is 2, any smoothing above 0.5 will **reverse** the labels, which I'm sure the person does not want; when n_classes is 3 it's any smoothing above 2/3, and 0.75 for 4 classes. So maybe:

`assert 0 <= smoothing < (classes-1)/classes`

**Comment by PistonY** [comment]
> > def smooth_one_hot(true_labels: torch.Tensor, classes: int, smoothing=0.0):
> 
> >     """
> 
> >     if smoothing == 0, it's one-hot method
> 
> >     if 0 < smoothing < 1, it's smooth method
> 
> > 
> 
> >     """
> 
> >     assert 0 <= smoothing < 1
> 
> >     confidence = 1.0 - smoothing
> 
> >     label_shape = torch.Size((true_labels.size(0), classes))
> 
> >     with torch.no_grad():
> 
> >         true_dist = torch.empty(size=label_shape, device=true_labels.device)
> 
> >         true_dist.fill_(smoothing / (classes - 1))
> 
> >         true_dist.scatter_(1, true_labels.data.unsqueeze(1), confidence)
> 
> >     return true_dist
> 
> > ```
> 
> 
> 
> 
> 
> The problem with this implementation is it's very sensitive to the number of classes
> 
> 
> 
>  Where n_classes is 2, any smoothing above 0.5 will **reverse** the labels, which I'm sure the person does not want; when n_classes is 3 it's any smoothing above 2/3, and 0.75 for 4 classes. So maybe:
> 
> 
> 
> `assert 0 <= smoothing < (classes-1)/classes` would catch this issue, but I feel the smoothing needs to take the number of classes into account?

It's a wise idea I think.

**Comment by antrec** [comment]
Thanks for the discussion. There are a few points that remain unclear and look like mistakes to me:

- the weight tensor in @PistonY 's implementation
- the equivalence between KL divergence and label-smoothing (@suanrong  )

#### About the weights:

[The label smoothing paper](https://arxiv.org/pdf/1906.02629.pdf) states `y_k = smoothing / n_classes + (1 - smoothing) * y_{one hot}`. So the value of the weight is `smoothing / n_classes` for indices other than the target, and it is `smoothing / n_classes + (1 - smoothing)` for the target class. Yet in @PistonY 's implementation, the function `torch.scatter_` overwrites the value for the target to `(1 - smoothing)` (and the constant term disappears).
Moreover, I do not really understand why we use `n_classes -= 1` in the computation (?)

#### About the equivalence between KL divergence and label-smoothing:

The label-smoothing cross-entropy loss reads, with `y` the weights mentioned above,
```
LS(x, y) = - sum_k {y[k] * log-prob(x)}
         = - sum_k {y[k] * log(exp(x[k]) / (sum_j exp(x[j])))}
         = - sum_k {y[k] * (x[k] - log-sum-exp(x))}
         = - sum_k {y[k] * x[k]} + log-sum-exp(x)
```
where the second to the third line uses the fact that `sum_k y[k] = smoothing / n_classes * n_classes + (1 - smoothing) = 1`.

The KL-divergence loss reads,
```
KL(x, y) = - sum_k {y[k] * x[k] - y[k] * log(y[k])
         = - sum_k {y[k] * x[k]} - sum_k {y[k] * log(y[k])}
         = - sum_k {y[k] * x[k]} - Const.
```

So in the end we have `LS(x, y) = KL(x, y) + log-sum-exp(x) + Const.`, where `Const.` is the constant term corresponding to the entropy of `y`, which is indeed constant in multiclass settings. But what about the log-sum-exp term ?

I did a few computations using a [custom cross entropy function accepting soft targets](https://discuss.pytorch.org/t/cross-entropy-with-one-hot-targets/13580/5), and it shows that it is indeed equal to the `KLDiv` loss plus `log-sum-exp`, up to the constant term corresponding to the entropy of `y`. Is there any assumption on the logits that make it reasonable to drop this term ?

Thanks a lot for the clarifications.
Cheers !

**Comment by suanrong** [comment]
Thanks @antrec !

You are right. I ignored the logsoftmax function and made a mistake.

**Comment by wangleiofficial** [comment]
The implementation of a label smoothing cross-entropy loss function: 
```
import torch.nn.functional as F
def linear_combination(x, y, epsilon): 
    return epsilon*x + (1-epsilon)*y

def reduce_loss(loss, reduction='mean'):
    return loss.mean() if reduction=='mean' else loss.sum() if reduction=='sum' else loss

class LabelSmoothingCrossEntropy(nn.Module):
    def __init__(self, epsilon:float=0.1, reduction='mean'):
        super().__init__()
        self.epsilon = epsilon
        self.reduction = reduction
    
    def forward(self, preds, target):
        n = preds.size()[-1]
        log_preds = F.log_softmax(preds, dim=-1)
        loss = reduce_loss(-log_preds.sum(dim=-1), self.reduction)
        nll = F.nll_loss(log_preds, target, reduction=self.reduction)
        return linear_combination(loss/n, nll, self.epsilon)
```

**Comment by zou3519** [comment]
Bumping to hi-pri based on activity

**Comment by zou3519** [comment]
So, after reading the above thread, it sounds like there are two options here. Apologies if I didn't link your code from here, there are a lot of code examples in this thread so I picked some representative ones.

Option 1: Add a CrossEntropyLossWithProbs that accepts one-hot target vectors and smoothed target vectors. The user must manually smooth their target vector, but that's not too difficult to do. @PistonY and @mdraw proposed this in https://github.com/pytorch/pytorch/issues/7455#issuecomment-513735962 and @sadikneipp pointed out snorkel implements this as https://snorkel.readthedocs.io/en/master/packages/_autosummary/classification/snorkel.classification.cross_entropy_with_probs.html

Option 2: Add a LabelSmoothingCrossEntropyLoss that accepts a target value. Conceptually, this module takes care of the label smoothing: it may turn the target value into a one-hot vector and then apply label smoothing to it. This is what @wangleiofficial's code does: https://github.com/pytorch/pytorch/issues/7455#issuecomment-720100742 and @huanglianghua seems to do something similar.

Some more alternatives: Look at how TensorFlow does it, but I haven't found the link to TF's API for this yet.

Option 1 sounds nicer to me because the resulting function is more general, the user may want to do their own smoothing or just straight up pass their own smoothed vector to CrossEntropyLoss. But I'm curious to hear what the folks in this thread think should be the correct approach.

**Comment by zou3519** [comment]
It looks like TF has a CategoricalCrossentropy and a SparseCategorialCrossentropy https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy
https://www.tensorflow.org/api_docs/python/tf/keras/losses/SparseCategoricalCrossentropy

SparseCategoricalCrossentropy is equivalent to PyTorch's CrossEntropyLoss.

CategorialCrossEntropy accepts only one-hot target vectors but also a `label_smoothing`  argument.

**Comment by sadikneipp** [comment]
Looks like a flexibility vs ease of use tradeoff. 

Baking the smoothing into the loss would be good for someone just trying to experiment with it (you would just pass an eps param or similar) but bad if a more complex smoothing strategy is wanted. Conversely for the reverse.

I think we can also get the best of both worlds by accepting an eps param for standard smoothing  AND a "smoother function"  param that could map a target to it's smoothed counterpart.

**Comment by jbschlosser** [comment]
I like @zou3519's Option 1 for the flexibility in allowing for arbitrary smoothing techniques and agree with @sadikneipp that we should be able to get the best of both worlds to some extent. One possibility is to provide a free-standing `smooth_labels` function that applies the canonical form of label smoothing from [the paper](https://arxiv.org/pdf/1512.00567.pdf). This would compose well with the loss from Option 1, without the need for the eps / smoothing function loss arg(s):

```python
criterion = nn.CrossEntropyLossWithProbs()
...
loss = criterion(output, F.smooth_labels(target, eps=0.1))
```

Additionally, it probably makes sense to have a corresponding `nn.NLLLossWithProbs`, although I'm honestly not sold on the "WithProbs" suffix. "WithProbs" indicates to me that the new loss accepts probs (i.e. softmax outputs) instead of raw unnormalized scores (for CE) / log-probs (for NLL). But this is just a naming concern- I do like the idea of the flexible loss proposed in Option 1.

**Comment by jbschlosser** [comment]
To summarize my previous rambling, I want to expand on @zou3519's excellent options a bit:

Option 1: Same as @zou3519's- "Add a CrossEntropyLossWithProbs that accepts one-hot target vectors and smoothed target vectors."
* Target tensor type: Float
* Loss args: None
* Flexibility: Can do both canonical label smoothing & arbitrary label smoothing
* Performance: Can't utilize `F.nll_loss` for canonical label smoothing in particular
* Ease-of-use:
  * User smooths labels manually (free-standing function that applies canonical label smoothing can help here)
  * No difference in difficulty between canonical & arbitrary label smoothing

Option 2: Same as @zou3519's- "Add a LabelSmoothingCrossEntropyLoss that accepts a target value."
* Target tensor type: Long
* Loss args: One `label_smoothing` arg as described by @sadikneipp
* Flexibility: Can do both canonical label smoothing & arbitrary label smoothing
* Performance: Arg allows us to implement canonical label smoothing in terms of `F.nll_loss`
* Ease-of-use:
  * User sets `label_smoothing=0.1` for canonical label smoothing
  * More involved to do arbitrary label smoothing (through use of a label smoothing function)

Option 3: Add a `label_smoothing` arg to the existing `CrossEntropyLoss`.
* Target tensor type: Long
* Loss args: One `label_smoothing` arg as described by @sadikneipp
* Flexibility: Can do both canonical label smoothing & arbitrary label smoothing
* Performance: Arg allows us to implement canonical label smoothing in terms of `F.nll_loss`
* Ease-of-use:
  * User sets `label_smoothing=0.1` for canonical label smoothing
  * More involved to do arbitrary label smoothing (through use of a label smoothing function)

Did I miss any variations on the above that make sense?

**Comment by NingAnMe** [comment]
https://github.com/NingAnMe/Label-Smoothing-for-CrossEntropyLoss-PyTorch

using as the origin PyTorch 'CrossEntropyLoss' loss function

```python
import torch
import torch.nn.functional as F
from torch.nn.modules.loss import _WeightedLoss


class LabelSmoothCrossEntropyLoss(_WeightedLoss):
    def __init__(self, weight=None, reduction='mean', smoothing=0.0):
        super().__init__(weight=weight, reduction=reduction)
        self.smoothing = smoothing
        self.weight = weight
        self.reduction = reduction

    @staticmethod
    def _smooth_one_hot(targets: torch.Tensor, n_classes: int, smoothing=0.0):
        assert 0 <= smoothing < 1
        with torch.no_grad():
            targets = torch.empty(size=(targets.size(0), n_classes),
                                  device=targets.device) \
                .fill_(smoothing / (n_classes - 1)) \
                .scatter_(1, targets.data.unsqueeze(1), 1. - smoothing)
        return targets

    def forward(self, inputs, targets):
        targets = LabelSmoothCrossEntropyLoss._smooth_one_hot(targets, inputs.size(-1),
                                                              self.smoothing)
        lsm = F.log_softmax(inputs, -1)

        if self.weight is not None:
            lsm = lsm * self.weight.unsqueeze(0)

        loss = -(targets * lsm).sum(-1)

        if self.reduction == 'sum':
            loss = loss.sum()
        elif self.reduction == 'mean':
            loss = loss.mean()

        return loss

loss_function = LabelSmoothCrossEntropyLoss(smoothing=0.3)
loss = loss_function(inputs, targets)
```

**Comment by jaideep11061982** [comment]
> The implementation of a label smoothing cross-entropy loss function:
> 
> ```
> import torch.nn.functional as F
> def linear_combination(x, y, epsilon): 
>     return epsilon*x + (1-epsilon)*y
> 
> def reduce_loss(loss, reduction='mean'):
>     return loss.mean() if reduction=='mean' else loss.sum() if reduction=='sum' else loss
> 
> class LabelSmoothingCrossEntropy(nn.Module):
>     def __init__(self, epsilon:float=0.1, reduction='mean'):
>         super().__init__()
>         self.epsilon = epsilon
>         self.reduction = reduction
>     
>     def forward(self, preds, target):
>         n = preds.size()[-1]
>         log_preds = F.log_softmax(preds, dim=-1)
>         loss = reduce_loss(-log_preds.sum(dim=-1), self.reduction)
>         nll = F.nll_loss(log_preds, target, reduction=self.reduction)
>         return linear_combination(loss/n, nll, self.epsilon)
> ```

Arent you are duplicating the Log . First log of softmax and then again nll  which also does the log

**Comment by ghlai9665** [comment]
> 
> ```python
> criterion = nn.CrossEntropyLossWithProbs()
> ...
> loss = criterion(output, F.smooth_labels(target, eps=0.1))
> ```

This code example you provided @jbschlosser would fall under option 1, right? That seems like the option most aligned with the single-responsibility principle. Given the prediction and target, CrossEntropyLossProbs() would output the loss and that's it - it doesn't smooth/change the input inside it. 

The free-standing function `F.smooth_labels` also sounds sweet; however, is there any reason why we can't extend the existing `nn.CrossEntropyLoss` to support smoothed vectors? Why do we need a new `nn.CrossEntropyLossWithProbs()` class?

**Comment by hadaev8** [comment]
Since we here, should gamma from focal loss be added?

**Comment by brando90** [comment]
what is wrong whti this:

https://github.com/OpenNMT/OpenNMT-py/blob/e8622eb5c6117269bb3accd8eb6f66282b5e67d9/onmt/utils/loss.py#L186 

https://stackoverflow.com/questions/55681502/label-smoothing-in-pytorch 

?

**Comment by lukasfolle** [comment]
Any progress on this issue?

**Comment by jbschlosser** [comment]
> This code example you provided @jbschlosser would fall under option 1, right? That seems like the option most aligned with the single-responsibility principle. Given the prediction and target, CrossEntropyLossProbs() would output the loss and that's it - it doesn't smooth/change the target inside it.

Agreed, it's nice and composable :)

> The free-standing function `F.smooth_labels` also sounds sweet; however, is there any reason why we can't extend the existing `nn.CrossEntropyLoss` to support smoothed vectors as #11959 mentioned (was wondering what the current status is on that since someone last made a comment in May 2020 but received no response @zou3519)? Why do we need a new `nn.CrossEntropyLossWithProbs` class?

It's possible to support soft labels directly in `nn.CrossEntropyLoss` / `nn.NLLLoss`. Note that each of these would have to support 3 target types- hard labels of shape `N`, hard labels of shape `(N, d1, d2, ..., dk)`, and soft labels of shape `(N, C)`. The `(N, C)` and `(N, d1)` for K=1 cases could be disambiguated only by checking the target `dtype`. Switching behavior based solely on the `dtype` of the target would not follow PyTorch precedent and could easily result in unexpected behavior / confusion. Example: accidentally passing the same labels as floating-point instead of integral could invisibly cause a non-negligible performance drop. This sort of specialization also wouldn't play nice with FX.

To get around this, one suggestion from @zou3519 is to add a `soft` flag (default `False`) to `nn.CrossEntropyLoss` / `nn.NLLLoss`. Setting `soft=True` would explicitly indicate that soft labels are desired, addressing the above issues without needing e.g. a new `nn.CrossEntropyLossWithProbs` class.

**Comment by itsnamgyu** [comment]
> Here is my implement
> 
> ```python
> class LabelSmoothingLoss(nn.Module):
>     def __init__(self, classes, smoothing=0.0, dim=-1):
>         super(LabelSmoothingLoss, self).__init__()
>         self.confidence = 1.0 - smoothing
>         self.smoothing = smoothing
>         self.cls = classes
>         self.dim = dim
> 
>     def forward(self, pred, target):
>         pred = pred.log_softmax(dim=self.dim)
>         with torch.no_grad():
>             # true_dist = pred.data.clone()
>             true_dist = torch.zeros_like(pred)
>             true_dist.fill_(self.smoothing / (self.cls - 1))
>             true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
>         return torch.mean(torch.sum(-true_dist * pred, dim=self.dim))
> ```

Canonically, smoothing should be distributed among all classes, not just the non-target classes. Here is a minor fix that follows the canonical version:

```python
class LabelSmoothingLossCanonical(nn.Module):
    def __init__(self, classes, smoothing=0.0, dim=-1):
        super(LabelSmoothingLossCanonical, self).__init__()
        self.confidence = 1.0 - smoothing
        self.smoothing = smoothing
        self.cls = classes
        self.dim = dim

    def forward(self, pred, target):
        pred = pred.log_softmax(dim=self.dim)
        with torch.no_grad():
            # true_dist = pred.data.clone()
            true_dist = torch.zeros_like(pred)
            true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
            true_dist += self.smoothing / self.cls
        return torch.mean(torch.sum(-true_dist * pred, dim=self.dim))
```

### Test Code

```python
pred = torch.tensor([
    [0.7, 0.1, 0.1, 0.1],
    [0.1, 0.7, 0.1, 0.1],
    [0.1, 0.1, 0.7, 0.1],
    [0.1, 0.1, 0.1, 0.7],
])
target = torch.Tensor([
    0, 1, 2, 3
]).long()

loss = LabelSmoothingLoss(classes=4, smoothing=0.1)
print(loss(pred, target))

loss = LabelSmoothingLossCanonical(classes=4, smoothing=0.1)
print(loss(pred, target))
```

### Test Output

```python
tensor(1.0332)
tensor(1.0182)
```

**Comment by itsnamgyu** [comment]
> Here is my implement
> 
> ```python
> class LabelSmoothingLoss(nn.Module):
>     def __init__(self, classes, smoothing=0.0, dim=-1):
>         super(LabelSmoothingLoss, self).__init__()
>         self.confidence = 1.0 - smoothing
>         self.smoothing = smoothing
>         self.cls = classes
>         self.dim = dim
> 
>     def forward(self, pred, target):
>         pred = pred.log_softmax(dim=self.dim)
>         with torch.no_grad():
>             # true_dist = pred.data.clone()
>             true_dist = torch.zeros_like(pred)
>             true_dist.fill_(self.smoothing / (self.cls - 1))
>             true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
>         return torch.mean(torch.sum(-true_dist * pred, dim=self.dim))
> ```

Huge thanks to @PistonY for the example code. Just one tidbit: in label smoothing, epsilon is canonically distributed among all classes, not just the non-target classes. Here is a minor fix that follows the canonical version:

```python
class LabelSmoothingLossCanonical(nn.Module):
    def __init__(self, smoothing=0.0, dim=-1):
        super(LabelSmoothingLossCanonical, self).__init__()
        self.confidence = 1.0 - smoothing
        self.smoothing = smoothing
        self.dim = dim

    def forward(self, pred, target):
        pred = pred.log_softmax(dim=self.dim)
        with torch.no_grad():
            # true_dist = pred.data.clone()
            true_dist = torch.zeros_like(pred)
            true_dist.scatter_(1, target.data.unsqueeze(1), self.confidence)
            true_dist += self.smoothing / pred.size(self.dim)
        return torch.mean(torch.sum(-true_dist * pred, dim=self.dim))
```

### Test Code

```python
pred = torch.tensor([
    [0.7, 0.1, 0.1, 0.1],
    [0.1, 0.7, 0.1, 0.1],
    [0.1, 0.1, 0.7, 0.1],
    [0.1, 0.1, 0.1, 0.7],
])
target = torch.Tensor([
    0, 1, 2, 3
]).long()

loss = LabelSmoothingLoss(classes=4, smoothing=0.1)
print(loss(pred, target))

loss = LabelSmoothingLossCanonical(smoothing=0.1)
print(loss(pred, target))
```

### Test Output

```python
tensor(1.0332)
tensor(1.0182)
```

**Comment by PistonY** [comment]
@itsnamgyu Thanks to fix my version, I'm glad to test it if possible.
@antrec Sorry for late response, quite busy. I checked the tf official implement and I really miss something in this.

**Comment by aiot-tech** [comment]
amazing! Why not write it out！

**Comment by jbschlosser** [comment]
Update: I propose a 2-part solution to this issue to get both performance and flexibility:
1. Support soft labels for cross-entropy loss (see #11959) - allows for arbitrary label smoothing techniques like mixup and cutmix
2. Support `label_smoothing=0.0` arg in current `CrossEntropyLoss` - provides performant canonical label smoothing in terms of existing loss as done in https://github.com/pytorch/pytorch/issues/7455#issuecomment-720100742

Part 1 is in progress; check out the discussion at https://github.com/pytorch/pytorch/issues/11959#issuecomment-875000148 if interested.

**Comment by vigi30** [comment]
Added a ignore index to the answer [wangleioffical]https://github.com/pytorch/pytorch/issues/7455#issuecomment-720100742
```
def linear_combination(x, y, epsilon): 
    return epsilon*x + (1-epsilon)*y

def reduce_loss(loss, reduction='mean'):
    return loss.mean() if reduction=='mean' else loss.sum() if reduction=='sum' else loss



#  Implementation of Label smoothing with CrossEntropy and ignore_index
class LabelSmoothingCrossEntropy(nn.Module):
    def __init__(self, epsilon:float=0.1, reduction='mean',ignore_index=-100):
        super().__init__()
        self.epsilon = epsilon
        self.reduction = reduction
        self.ignore_index = ignore_index
    def forward(self, preds, target):
        n = preds.size()[-1]
        log_preds = F.log_softmax(preds, dim=-1)
        loss = reduce_loss(-log_preds.sum(dim=-1), self.reduction)
        nll = F.nll_loss(log_preds, target, reduction=self.reduction,ignore_index=self.ignore_index)
        return linear_combination(loss/n, nll, self.epsilon)
```

 # Implementation of Label smoothing with NLLLoss and ignore_index
```
class LabelSmoothingNLLLoss(nn.Module):
    def __init__(self, epsilon:float=0.1, reduction='mean',ignore_index=-100):
        super().__init__()
        self.epsilon = epsilon
        self.reduction = reduction
        self.ignore_index = ignore_index
    def forward(self, preds, target):
        n = preds.size()[-1]
        loss = reduce_loss(-preds.sum(dim=-1), self.reduction)
        nll = F.nll_loss(preds, target, reduction=self.reduction,ignore_index=self.ignore_index)
        return linear_combination(loss/n, nll, self.epsilon)
```

**Comment by QuanticDisaster** [comment]
Hello, I see that this issue is closed, but can't find it in the torch documentation. The CrossEntropyLoss I want to use with weights keeps saying that it can't accept non integer values. Could someone point me to the soft-label equivalent in the documentation ?

**Comment by seyeeet** [comment]
@itsnamgyu what does `Canonical` means in your reply?

**Comment by itsnamgyu** [comment]
> @itsnamgyu what does `Canonical` means in your reply?

The canonical version follows the exact details used in the original paper, InceptionV2: https://arxiv.org/pdf/1512.00567.pdf

**Comment by seyeeet** [comment]
would it be possible to have label smoothing CE loss for segmentation task?

**Comment by jbschlosser** [comment]
@QuanticDisaster Label smoothing is available for `nn.CrossEntropyLoss` in PyTorch 1.10 (see docs [here](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html)).

**Comment by jbschlosser** [comment]
> would it be possible to have label smoothing CE loss for segmentation task?

Hey @seyeeet, great question - do you mind opening a separate issue for discussion to help us determine the popularity / impact of that request?

**Comment by arisliang** [comment]
Thanks for a lot of good ideas. What is the conclusion for this request? Since it is closed.

**Comment by seyeeet** [comment]
@arisliang https://github.com/pytorch/pytorch/issues/67863

**Comment by ragulpr** [comment]
@AhmedThahir just use
```
import torch
logits = torch.randn(5)
targets = torch.Tensor([1,0,1,0,1])
smoothing = 0.1
smoothed_targets = targets * (1 - smoothing) + 0.5 * smoothing
print(smoothed_targets)
loss = torch.nn.functional.binary_cross_entropy_with_logits(logits, targets) # binary_cross_entropy if probs
print(loss)

> tensor([0.9500, 0.0500, 0.9500, 0.0500, 0.9500])
> tensor(0.7307)
```
If you want to wrap that as a module just put the above in the forward
```
class BCEWithSmoothedLogits(nn.Module):
    def __init__(self, smoothing=0.1):
        super().__init__()
        self.smoothing = smoothing
    
    def forward(self, logits, targets):
    ...
```

**Comment by AhmedThahir** [comment]
Thanks! 

> I do not condone label smoothing in general I think it works because it hides other problems

Can you pls elaborate on this? I would like to hear your insight.

**Comment by ragulpr** [comment]
@AhmedThahir You're welcome! I think this might be the wrong forum to discuss this, and I don't have very deep insights but I've seen it typically used to mask problems like loss spikes (better solution: initialize output layer better or clamp loss) or to "handle" class imbalance (same thing) or as . If it works and it gets the job done do it! I just like my models calibrated so I don't
