### ISSUE TITLE
Windows 10 16299 Updating KB4103727 Fails the Pytorch v0.4.0

### ISSUE THREAD

**Issue by zjzhangd** [pytorch/pytorch#7458]
## Issue description
Before I update Windows, I got everything ok. After I have KB4103727 patched, 
then `import torch` fails.

## Code example
(base) C:\Users\XXX>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\Programs\Anaconda3\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

## System Info
I even cannot run `python collect_env.py'.
(base) C:\Users\XXX\Desktop>python collect_env.py
Traceback (most recent call last):
  File "collect_env.py", line 11, in <module>
    import torch
  File "C:\Users\Mziji\Programs\Anaconda3\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

Here's info I manually collect.
- PyTorch or Caffe2:  pytorch-cpu               0.4.0           py36_cpuhe774522_1    pytorch
- How you installed PyTorch (conda, pip, source): conda install pytorch-cpu -c pytorch
- Build command you used (if compiling from source): No
- OS: Windows Version 10.0.16299.431
- PyTorch version: v0.4.0
- Python version: Python 3.6.4
- CUDA/cuDNN version: No
- GPU models and configuration: No
- GCC version (if compiling from source): No
- CMake version: No
- Versions of any other relevant libraries: No

**Comment by NevMem** [comment]
Try to do this https://github.com/pytorch/pytorch/issues/4518#issuecomment-384209046
And look some comments before it

**Comment by peterjc123** [comment]
@csonder An issue that may be related #7410.

**Comment by csonder** [comment]
Thanks, guys. I fixed it by uninstalling the patch...

**Comment by heitorschueroff** [comment]
Closing this issue as it was fixed per the comment.
