### ISSUE TITLE
torch.gesv is slow on GPU

### ISSUE THREAD

**Issue by noUmbrella** [pytorch/pytorch#7459]
Hello, I encounter a problem, and it confused me a long time.
When I use torch.gesv, I find that it runs much slower on GPU than on CPU, and this problem seriously destroys the real time of my algorithm. How can I solve it, I wish under GPU, it runs as fast as CPU at least.
Here is my test code:
`import pdb
import time
import torch

x = torch.rand([30,30])
x = x.cuda()
y = torch.rand([30,1])
y = y.cuda()

torch.cuda.synchronize()
start = time.time()
for i in range(10):
  w = torch.gesv(y,x)
end = time.time()

print (end-start)/10.0

x = torch.rand([30,30])
y = torch.rand([30,1])

w = torch.gesv(y,x)

start = time.time()
for i in range(10):
  w = torch.gesv(y,x)
end = time.time()

print (end-start)/10.0
`
and the test result: 0.00425 s on GPU and 2.36034e-05 s on CPU.
Please help me, thank you very much.

**Comment by fmassa** [comment]
I'd say your matrices are too small for the operation on the GPU to be faster than on the CPU. Try increasing the size of the matrix (say 1000x1000) and see if the GPU is still slower

**Comment by apaszke** [comment]
The benchmark doesn't even measure the time of actual GPU work. You're measuring the overhead of CPU-side kernel launch overhead. I'd recommend using e.g. `nvprof` + `nvvp` to see how much time do the kernels actually use.
