### ISSUE TITLE
why don't pytorch website have the version 1.10 with the corresponding cuda version and torchvision version?

### ISSUE THREAD

**Issue by yangrisheng** [pytorch/pytorch#74609]
### 📚 The doc issue

why don't pytorch website have the version 1.10 with the corresponding cuda version and torchvision version?

cc @ezyang @gchanan @zou3519 @seemethere @malfet @brianjo @mruberry

**Comment by gchanan** [comment]
I believe this is asking why https://pytorch.org/get-started/previous-versions/ doesn't have 1.10 listed.

**Comment by brianjo** [comment]
Sorry, I added this last week. Thanks for the report @yangrisheng. I'll go ahead and close.
