### ISSUE TITLE
[Feature Request] nn.Module should also get a `device` attribute

### ISSUE THREAD

**Issue by nehz** [pytorch/pytorch#7460]
Similar to the changes for tensors in 0.4, Modules should also get a .device attribute to allow easy creation of correct tensors.

Use case:

```
class Net(Module):
    def forward(self, x):
        x = x.to(self.device)

net = Net().cuda()
net.forward(Tensor([1]))   # Don't need conditional or additional .to()
```

**Comment by apaszke** [comment]
That’s not possible. Modules can hold parameters of different types on different devices, and so it’s not always possible to unambiguously determine the device.

**Comment by apaszke** [comment]
I think that's a bit too convoluted, for such a simple thing. If you know all parameters are on a single device you can always do `next(model.parameters()).device`.

**Comment by acgtyrant** [comment]
How about make the `device` of nn.Module as not implemented? Then all the official implemented module inherited from nn.Module should have the uniform device for their parameters (if I am wrong, forget it) so that they can have the `device` attribute, so as to `DataParallel` and `DistributedParallel` while their device is their `module`'s device.

So if the user define a new Module class, then he should implement the `device` attributes` by himself, or get the unimplemented exception when he use the unimplemented `device` attribute.

**Comment by spott** [comment]
In simple cases (where all parameters are on the same device, which is probably a pretty common case), `.device` could return the expected answer.  In complicated situations, it could throw a value error or similar.

How expensive would it be to run `device` on all `parameters()` in a module, and then check if they are all the same?

**Comment by aliutkus** [comment]
allowing the parameters of a model to be on several devices is nice, but  it's really painful not to have the `.device` accessible whenever they're all on the same. I guess it's the overwhelming majority of cases..

**Comment by cifkao** [comment]
Something like

```python
@property
def device(self):
    devices = ({param.device for param in self.parameters()} |
               {buf.device for buf in self.buffers()})
    if len(devices) != 1:
        raise RuntimeError('Cannot determine device: {} different devices found'
                           .format(len(devices)))
    return next(iter(devices))
```

would be nice.

It could be a cached property, invalidated by any call to `_apply()` (which is used by `to()` et al.).

**Comment by minhlab** [comment]
This is an one-liner that will throw an exception if the parameters are on different devices.

```device, = list(set(p.device for p in model.parameters()))```
