### ISSUE TITLE
CI is experiencing elevated amount of errors due to outage of GitHub

### ISSUE THREAD

**Issue by b0noI** [pytorch/pytorch#74618]
Root cause: GitHub Actions is experiencing degraded performance. 

Status: https://www.githubstatus.com/incidents/tyc8wpsgr2r8

cc @ezyang @gchanan @zou3519

**Comment by b0noI** [comment]
Please be aware that this will impact landing time for your PRs

**Comment by malfet** [comment]
Unassigning myself (as I'm not sure I can be of any help here)
@b0noI also, can you please edit issue description to follow pattern outlined in https://github.com/pytorch/pytorch/blob/master/.github/ISSUE_TEMPLATE/ci-sev.md

**Comment by b0noI** [comment]
GitHub Actions outage has been resolved, closing this bug
