### ISSUE TITLE
magma in pytorch

### ISSUE THREAD

**Issue by noUmbrella** [pytorch/pytorch#7461]
I find that when I install the pytorch from source, I can install the magma by "conda install -c pytorch magma-cuda80", however, when I install the pytorch by "conda install pytorch torchvision -c pytorch", it seems that the magma does not be installed, why? Do I need install it extraly?

**Comment by apaszke** [comment]
cc @soumith

**Comment by soumith** [comment]
because we statically link magma, the magma package is not needed at runtime.
