### ISSUE TITLE
Decouple LTC from TS backend

### ISSUE THREAD

**Issue by henrytwo** [pytorch/pytorch#74628]
### 🚀 The feature, motivation and pitch

Currently, there are a few instances where components from the TorchScript LTC backend are used for infrastructure that should be backend agnostic. For example, [`LazyTensor::CreateTensorNode`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/lazy/core/tensor.cpp#L426) relies on `DeviceData`, which is a class based on `TsNode`. This causes some issues when implementing a custom LTC backend, especially when the base class of custom nodes is not `TsNode`.

I'm not sure what the best approach to fix this would be, so I think it would be good to get some other ideas.

CC: @wconstab @antoniojkim

**Comment by antoniojkim** [comment]
I think a solution here might be to create an intermediary `Node` subclass (called `LtcNode` or something) that `TsNode` can inherit from as much of the functionality in `TsNode` itself I don't think is TS specific. Besides the `Lower` function, I don't see anything else that is TS specific and could probably be used in any other custom backend as well.

This is further supported by the fact that things like `LazyTensor::CreateTensorNode` have no need to be coupled with `TsNode` as the device data is an internal op and does not need to be lowered.

@wconstab Thoughts?

**Comment by henrytwo** [comment]
Another example of an instance where a TS specific node is created: https://github.com/pytorch/pytorch/blob/master/torch/csrc/lazy/core/lazy_view.cpp#L43

`Permute` is a direct subclass of `TsNode`

**Comment by antoniojkim** [comment]
In fact, it looks like most (if not all) of the view ops are subclasses of `TsNode`

**Comment by wconstab** [comment]
Some of these issues are probably oversight or WIP, others seem more like different design goals.  In general, we didn't aim for a lot of external backends to implement at the LTC plugin layer, we aimed for mainly TS/XLA and then to have vendors reuse integrations with those compilers.  MLIR being an obvious case of a new XLA-like backend, seems to make sense to implement here.

1) Node base class
I think moving 'operands' and 'operands_as_outputs' fields from Node to TsNode was a mistake.  Partly I was not thrilled with having to maintain both fields and thought maybe we'd clean it up at some point, wanted to keep Node simple.  I'd be ok moving operands* stuff back to Node and I think that would unlock some possibilities for Node class reuse
2) View ops
These are indeed all ts_backend specific today.  One option might be after doing (1) to make the view ops (and maybe any other straggler ops that we didn't codegen) simply derive from Node.  To keep the current Ts codebase happy we could then create thin wrappers of e.g. TsViewNode:publicViewNode which adds the lower() method, and doesn't change the current assumption that all nodes are TsNodes when we run with Ts backend
3) lowering functions
I did intend to remove the TSNodeLoweringInterface and just copy the remaining lowering functions into the remaining node classes that are not codegenned.  I deferred doing this until after implementing more codegen functionality, but there aren't too many ops left so it could be manageable now.  

Why is the NodeLoweringInterface approach preferable for you?  You could also override lower() if you subclassed a node.  Is it more work to subclass a node vs doing this?  If so, maybe this is a better way to go.  Open to proposals to simplify here.
4) LTCNode proposal
I'm not thrilled about adding a third level to the hierarchy, if we can avoid it by moving some more stuff to Node and possibly cleaning up some other stuff on the TS side that could be done differently

**Comment by antoniojkim** [comment]
> Why is the NodeLoweringInterface approach preferable for you? You could also override lower() if you subclassed a node.

The need to add and override a `Lower` method was specifically the reason why I thought the `NodeLoweringInterface` approach would be more preferrable. A custom backend could just implement a `NodeLoweringInterface` subclass and handle all lowerings through it.

> we aimed for mainly TS/XLA and then to have vendors reuse integrations with those compilers

However, if this is the case, then I can see the reasoning why it might not make sense to have everything lowered by a `NodeLoweringInterface` subclass as the `Lower` method approach is already how it was done in PyTorch/XLA

> I'm not thrilled about adding a third level to the hierarchy, if we can avoid it by moving some more stuff to Node and possibly cleaning up some other stuff on the TS side that could be done differently

> I'd be ok moving operands* stuff back to Node and I think that would unlock some possibilities for Node class reuse

In this case, what are your thoughts on just moving everything *except* the `Lower` method from `TsNode` into `Node`? Because everything else in `TsNode` I think can be reused by other `Node` subclasses.

**Comment by antoniojkim** [comment]
@wconstab I've put up a draft PR here: https://github.com/pytorch/pytorch/pull/74710

Its the changes I was working on so far before you commented above. As such, it will contain that "third level" `BackendNode` in the hierarchy. I'll work on removing that, but I wanted to get your input and opinion early on as I feel like this impacts the design in a non insignificant way

**Comment by wconstab** [comment]
I am pretty keen on the idea of moving everything except 'Lower' to Node.  @desertfire do you see any issues with this?  I briefly looked through your PR, there is a lot of 'BackendNode' related changes to skim over, anything in particular you want feedback on?  Lowering interface i'm still open minded about; I don't see how backend-independent lowering can be anyway, but I guess the signature of Lower() doesn't return anything but bool success which makes it a useful point to interpose.

**Comment by antoniojkim** [comment]
> there is a lot of 'BackendNode' related changes to skim over, anything in particular you want feedback on?

Not anything specific yet as I'm still working on "merging" `BackendNode` into `Node`. Just high level design stuff that I wanted to make sure we were on the same page about.

> the signature of Lower() doesn't return anything but bool success which makes it a useful point to interpose

This was exactly my thinking when I originally proposed that change above.

> I don't see how backend-independent lowering can be anyway

However, this is a good point. There _probably_ won't be many (if any) other lowerings besides TS, XLA, and MLIR. In which case I think its fine to keep it the way it is.

**Comment by antoniojkim** [comment]
@wconstab I've "merged" `BackendNode` into `Node` and decoupled the `TsNode` references in LT core. Please take a look when you can.
