### ISSUE TITLE
Support channel first(or any dim) LayerNorm

### ISSUE THREAD

**Issue by PistonY** [pytorch/pytorch#74661]
### 🚀 The feature, motivation and pitch

LayerNorm is widely used in Transformer and recently some CNN model(or Transformer + CNN model)  is trying to use this. But CNN has [B, C, H, W] output, that can not use LayerNorm which only support norm last N channel.

### Alternatives

Support specific dim of mean, not last N dim.

**Comment by vadimkantorov** [comment]
related: https://github.com/pytorch/pytorch/issues/51455, https://github.com/pytorch/pytorch/issues/52143,

**Comment by vadimkantorov** [comment]
duplicate of https://github.com/pytorch/pytorch/issues/71465?

**Comment by ngimel** [comment]
Closing as a duplicate
