### ISSUE TITLE
pad_packed_sequence always puts lengths on CPU

### ISSUE THREAD

**Issue by akhti** [pytorch/pytorch#7466]
The last assert below fails. I'm not sure whether this is a feature or bug.
```(python)
packed_seq = torch.nn.PackedSequence(...)
packed_seq = packed_seq.cuda()
outs, lens = torch.nn.utils.rnn.pad_packed_sequence(packed_seq)
assert outs.device.type == 'cuda'   # This passes
assert lens.device.type == 'cuda'   # This fails
```

Tested on pytorch 4.0 installed with
```
pip3 install http://download.pytorch.org/whl/cu90/torch-0.4.0-cp36-cp36m-linux_x86_64.whl 
```

Related line that creates cpu long tensor:
https://github.com/pytorch/pytorch/blob/f1e38725bfe73a29335d921786250bc71b15f7b6/torch/nn/utils/rnn.py#L171:5

**Comment by apaszke** [comment]
It's a feature. Lengths are used in various conditionals and storing them on CUDA would impose unnecessary overheads.
