### ISSUE TITLE
torch.combinations raises a warning casued by torch.meshgrid

### ISSUE THREAD

**Issue by Fitz13009** [pytorch/pytorch#74689]
### 🐛 Describe the bug

Hi, 

I am using torch.combinations and get a warning internally raised by the torch.meshgrid.
But I did not explicitly call this meshgrid myself, so I do not know how to make this warning silent. 

If this is an expected behaviour, please simply close this issue. 

repeat:
`torch.combinations(torch.Tensor([1,2,3,4]), 2)`

### Versions

Pytorch 1.10
cuda 10.2

cc @ezyang @gchanan @zou3519 @mruberry

**Comment by mrshenli** [comment]
Didn't see a "combinations" label. Adding "triage review".

**Comment by gchanan** [comment]
This still happens on 1.11 and here is the message:

```
>>> torch.combinations(torch.Tensor([1,2,3,4]), 2)
<stdin>:1: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /Users/distiller/project/pytorch/aten/src/ATen/native/TensorShape.cpp:2228.)
tensor([[1., 2.],
        [1., 3.],
        [1., 4.],
        [2., 3.],
        [2., 4.],
        [3., 4.]])
>>>
```

**Comment by Fitz13009** [comment]
> Thank you for reporting this issue, @Fitz13009. We should definitely fix this!

You are welcome, I am glad to make this tiny contribution :smile:

**Comment by ezyang** [comment]
see also https://github.com/pytorch/pytorch/issues/60548
