### ISSUE TITLE
CI jobs are not scheduled due to GHA issues

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#74693]
## Current Status
*mitigated*

## Error looks like
Tests are not getting scheduled on the workflows

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Yet another GitHubActions outage </summary>

e.g.
- 3/24 9:09a detected by @cpuhrsch 

</details>

## User impact
No testing is done on master or PRs

## Root cause
https://www.githubstatus.com/incidents/y5hdmv0p49x3

## Mitigation
Please rebase/update your PR to re-trigger the testing

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by b0noI** [comment]
closing since GitHub outage been resolved
