### ISSUE TITLE
CosineSimilarity() requires the two input tensors to have exact same shape, but it shouldn't be the case according to docu

### ISSUE THREAD

**Issue by mszuyx** [pytorch/pytorch#74724]
### 🐛 Describe the bug

``` python
from torch.nn import functional as F
a = torch.rand(16,64,9,256)
b = torch.rand(16,64,4,256)
print(a.shape)
print(b.shape)
similarities = F.cosine_similarity(a, b, dim = 1)
```
I don't think this behavior fits the description in the document:
[https://pytorch.org/docs/stable/generated/torch.nn.CosineSimilarity.html](https://pytorch.org/docs/stable/generated/torch.nn.CosineSimilarity.html)
The documentation seems to allow the two input tensors to have unmatched sizes (except for dim). As long as the number of dimensions match.

```
torch.Size([16, 64, 9, 256])
torch.Size([16, 64, 4, 256])
Traceback (most recent call last):
  File "/home/ros/OS_TR/tools/test_unfold.py", line 11, in <module>
    similarities = F.cosine_similarity(a, b, dim = 1)
RuntimeError: The size of tensor a (9) must match the size of tensor b (4) at non-singleton dimension 2
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-21-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 510.39.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.10.0+cu113
[pip3] torch-tb-profiler==0.3.1
[pip3] torchaudio==0.10.0+cu113
[pip3] torchinfo==1.5.3
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.1+cu113
[conda] Could not collect

**Comment by gchanan** [comment]
The formatting is wrong, but it says the other dimensions have to be broadcastable:
>>> same number of dimensions as x1, matching x1 size at dimension dim,
and broadcastable with x1 at other dimensions.

We should fix the formatting.

**Comment by mszuyx** [comment]
@gchanan Thanks for your response!

Could you please define the term "broadcastable" in this context?

**Comment by awgu** [comment]
> @gchanan Thanks for your response!
> 
> Could you please define the term "broadcastable" in this context?

Perhaps, take a look at the section titled "General semantics": https://pytorch.org/docs/stable/notes/broadcasting.html

Let me know if this does not clarify things.

**Comment by mszuyx** [comment]
@awgu thx!
