### ISSUE TITLE
Unable to import module

### ISSUE THREAD

**Issue by vaibhawc** [pytorch/pytorch#7472]
Hi, this is embarrassing but I did install with pip3 but I cant import in python3.
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip3
- Build command you used (if compiling from source):
- OS: ubuntu 16.04
- PyTorch version: none specified
- Python version: 3.5.2
- CUDA/cuDNN version: none
- GPU models and configuration: none
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
What is your "pip3 list" output?

**Comment by soumith** [comment]
see `pip3 --version`, does it actually specify the same python binary as the one you are using `which python`

**Comment by vaibhawc** [comment]
Oops.
Guys I am really sorry. It is different.
My fault :(
