### ISSUE TITLE
Inference result is different between Pytorch and ONNX model

### ISSUE THREAD

**Issue by YsYusaito** [pytorch/pytorch#74732]
### 🐛 Describe the bug

# Problem
Hi,

I converted Pytorch model to ONNX model.
However, output is different between two models like bellow.
![inference_result](https://user-images.githubusercontent.com/80863816/160040192-770825d4-5c25-4b18-8584-f71e561ef738.PNG)

# inference environment
## Pytorch
・python 3.7.11
・pytorch 1.6.0
・torchvision 0.7.0
・cuda tool kit 10.1
・numpy 1.21.5
・pillow 8.4.0

## ONNX
・onnxruntime-win-x64-gpu-1.4.0
・Visual studio 2017
・Cuda compilation tools, release 10.1, V10.1.243

# Network of model
![multi_inout_network](https://user-images.githubusercontent.com/80863816/160040244-0d621aca-0d51-4c79-a612-a50ba7dd8a79.PNG)
[detail information of my model](https://github.com/YsYusaito/Multi-in-out-model)

# Script for converting model from Pytorch to ONNX
```
import torch
import torch.onnx as onnx
import torchvision.models as models
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self, pretrained):
        # スーパークラス（Module クラス）の初期化メソッドを実行 
        super().__init__() 
        
        self.pretrained = pretrained
        
        self.pretrained.fc = nn.Linear(2048, 128)
        self.fc1 = nn.Linear(256, 128)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(256, 128)
        self.fc_y1 = nn.Linear(128*2, 64)
        self.fc_y1_1 = nn.Linear(64, 32)
        self.fc_y1_2 = nn.Linear(32, 16)
        self.fc_y1_3 = nn.Linear(16, 32)
        self.fc_y1_4 = nn.Linear(32, 16)
        self.fc_y1_5 = nn.Linear(16, 8)
        self.fc_y1_6 = nn.Linear(8, 2)
        
        self.fc_y2 = nn.Linear(128*2, 64)
        self.fc_y2_1 = nn.Linear(64, 32)
        self.fc_y2_2 = nn.Linear(32, 16)
        self.fc_y2_3 = nn.Linear(16, 32)
        self.fc_y2_4 = nn.Linear(32, 16)
        self.fc_y2_5 = nn.Linear(16, 8)
        self.fc_y2_6 = nn.Linear(8, 2)
        
        self.bn_256 = nn.BatchNorm1d(num_features = 256)
        self.bn_128 = nn.BatchNorm1d(num_features = 128)
        self.bn_64 = nn.BatchNorm1d(num_features = 64)
        self.bn_32 = nn.BatchNorm1d(num_features = 32)
        self.bn_16 = nn.BatchNorm1d(num_features = 16)
        self.bn_8 = nn.BatchNorm1d(num_features = 8)

    def forward(self, x0, x1, x2, x3): # 入力から出力を計算するメソッドを定義
        x0 = self.pretrained(x0)
        x1 = F.relu(self.bn_128(self.fc1(x1)))
        x2 = F.relu(self.bn_128(self.fc2(x2)))
        x3 = F.relu(self.bn_128(self.fc3(x3)))
        
        x123 = x1 + x2 + x3
        x = torch.cat((x0, x123), 1)
        
        y0 = F.relu(self.bn_64(self.fc_y1(x)))
        y0 = F.relu(self.bn_32(self.fc_y1_1(y0)))
        y0 = F.relu(self.bn_16(self.fc_y1_2(y0)))
        y0 = F.relu(self.bn_32(self.fc_y1_3(y0)))
        y0 = F.relu(self.bn_16(self.fc_y1_4(y0)))
        y0 = F.relu(self.bn_8(self.fc_y1_5(y0)))
        y0 = self.fc_y1_6(y0)
        
        y1 = F.relu(self.bn_64(self.fc_y2(x)))
        y1 = F.relu(self.bn_32(self.fc_y2_1(y1)))
        y1 = F.relu(self.bn_16(self.fc_y2_2(y1)))
        y1 = F.relu(self.bn_32(self.fc_y2_3(y1)))
        y1 = F.relu(self.bn_16(self.fc_y2_4(y1)))
        y1 = F.relu(self.bn_8(self.fc_y2_5(y1)))
        y1 = self.fc_y2_6(y1)
        
        return y0, y1


resnet = models.resnet50(pretrained=True)

model = Net(resnet)
model.load_state_dict(torch.load('path to Pytorch model'))
model.eval()


input_image = torch.randn(1,3,224,224, requires_grad=True)
input_hist_R = torch.randn(1,256, requires_grad=True)
input_hist_G = torch.randn(1,256, requires_grad=True)
input_hist_B = torch.randn(1,256, requires_grad=True)

input_tuple = (input_image,input_hist_R,input_hist_G,input_hist_B)
input_names = [ "input.1","input.154","input.156","input.158" ]
output_names = [ "593","612" ]

onnx.export(model, input_tuple, 'multi_inout.onnx',export_params=True,opset_version=12,do_constant_folding=True,input_names=input_names, output_names=output_names)
```
# Environment for converting model
・python 3.7.11
・pytorch 1.6.0
・torchvision 0.7.0
・numpy 1.21.5
・pillow 8.4.0

# Additional information
- Actually, I have converted ONNX model into OpenVINO. Then, I have run OpenVINO model in OpenVINO frame work.
The inference results are below(OpenVINO's inference result is the red line). From these results, we can see that there is virtually no difference between the inference results of ONNX model and OpenVINO model. So I think there is no problem in ONNX runtime but there is a problem in ONNX model.

![inference results pth onnx vino](https://user-images.githubusercontent.com/80863816/160040534-eeeed7d5-0570-49d8-a502-f7ecc2c37227.PNG)

-  I useed "onnx.checker.check_model(your_onnx_model, True)" and ran the script. However, no error occured.

Is there something wrong with the way of the model conversion?
If necessary, I can share inference scripts and models via e-mail.

Please help…

### Versions

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro for Workstations
GCC version: (MinGW.org GCC Build-2) 9.2.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.17134-SP0
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro RTX 6000
Nvidia driver version: 471.68
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h74a9793_0  
[conda] mkl                       2021.4.0           haa95532_640  
[conda] mkl-service               2.4.0            py37h2bbff1b_0  
[conda] mkl_fft                   1.3.1            py37h277e83a_0  
[conda] mkl_random                1.2.2            py37hf11a4ad_0  
[conda] mypy_extensions           0.4.3            py37haa95532_1  
[conda] numpy                     1.21.5           py37ha4e8547_0  
[conda] numpy-base                1.21.5           py37hc2deb75_0  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch                   1.6.0           py3.7_cuda101_cudnn7_0    pytorch
[conda] torchvision               0.7.0                py37_cu101    pytorch

**Comment by BowenBao** [comment]
Hello @YsYusaito , could you try testing with more recent version? I tried your script, and on PyTorch 1.11 and onnxruntime 1.10, the models produce same outputs.

**Comment by YsYusaito** [comment]
Hi, @BowenBao  

Thank you for reply.
I'll test on PyTorch 1.11 and onnxruntime 1.10.

I would appreciate it if you could share the Pytorch and ONNX models you have created, and the script to convert from Pytorch to ONNX, just in case via e-mail.

ys.yusaito@gmail.com

**Comment by AllenTiTaiWang** [comment]
cc @BowenBao

**Comment by AyaNasser96** [comment]
Hello @YsYusaito , 
You could check the conversion I used here at the issue description:
https://github.com/openvinotoolkit/openvino/issues/11942

![image](https://user-images.githubusercontent.com/98317981/179495199-715ffb28-bbbf-45cf-b31a-851c090efd9f.png)

What I made is set the dummy variable that equal to your input shape,
Then specify the name of input layer and output layers (which they're usually as I set them)
Then use the export function and you could add the opset_version=11

**Comment by BowenBao** [comment]
Hello @YsYusaito , I used the following script to validate and it showed no mismatch between onnx and pytorch. Could you please try with latest nightly and let us know if mismatch still occurs? 
```python
from torch.onnx import verification

verification.verify(
    model,
    input_tuple,
    opset_version=12,
    do_constant_folding=True,
    input_names=input_names,
    output_names=output_names,
)

verification.find_mismatch(
    model, input_tuple, opset_version=12, do_constant_folding=True
)
```

**Comment by BowenBao** [comment]
Closing as resolved. For similar issues, feel free to give a try with `verification.find_mismatch` to diagnose the onnx model.
