### ISSUE TITLE
num_heads incorrectly represented in math expression

### ISSUE THREAD

**Issue by stanvanlier** [pytorch/pytorch#74743]
### 📚 The doc issue

On https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html in the 'output' section where the output dimensions are specified as latex math. The variable name `num_heads` is used which looks like as if `num` with subscript `h` is multiplied by `eads`. Like this: (N,num<sub>h</sub>​eads,L,S).

### Suggest a potential alternative/fix

This is probably caused by the underscore in `num_heads` which means subscript in a latex math expression when not escaped. can be solved by escaping it like `num\_heads`

cc @jbschlosser @bhosmer @cpuhrsch

**Comment by dogeplusplus** [comment]
I believe this issue was already raised in #74147 and has been addressed with #74181.

**Comment by stanvanlier** [comment]
You're right!
