### ISSUE TITLE
TorchBench V2 nightly run detects 10% slowdown on dcgan model cpu test

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#74752]
### 🐛 Describe the bug

On 20220201, the TorchBench test test_train[dcgan-cpu-jit] and test_train[dcgan-cpu-eager] regresses 10% because of the commit https://github.com/pytorch/pytorch/commit/f499ab9cef.

The perf delta has been validated by PR: https://github.com/pytorch/pytorch/pull/74696. After reverting the commit, the dcgan cpu train tests shows speedup. We observe the latency difference below (lower the better):

```
Benchmark                      Run f499ab9ceff49be0b64a15020103c6baec3387ea    Run 162f7f1c8362e6292d1c5d4c7bdf37957670df80  Delta
---------------------------  ----------------------------------------------  ----------------------------------------------  ------------
test_train[dcgan-cpu-jit]                                         1.37312                                         1.20326    -14.117032%*
test_eval[dcgan-cpu-jit]                                          0.0670233                                       0.0660378  -1.492224%
test_train[dcgan-cpu-eager]                                       1.37992                                         1.19523    -15.452471%*
test_eval[dcgan-cpu-eager]                                        0.064613                                        0.067297   +3.988220%
```

Commit https://github.com/pytorch/pytorch/commit/f499ab9ceff49be0b64a15020103c6baec3387ea contains the commit https://github.com/pytorch/pytorch/commit/f499ab9cef, and commit https://github.com/pytorch/pytorch/commit/162f7f1c8362e6292d1c5d4c7bdf37957670df80 reverts https://github.com/pytorch/pytorch/commit/f499ab9cef. After reverting the commit, the latency of test dcgan decreases (show there is speedup).

### Versions

PyTorch 1.12.0.dev20220201+cu113

cc @VitalyFedyunin @ngimel @rdspring1 @jbschlosser

**Comment by csarofeen** [comment]
How could that PR regress torchbench dcgan-cpu-jit? Are you sure there's a GeLU even in that model?

**Comment by dzhulgakov** [comment]
Yes, it's very suspicious - the PR seems very orthogonal. Let's understand what's going on before reverting since it's been in master for close to 2 months and no one complained so far

**Comment by xuzhao9** [comment]
I run the benchmark locally, but couldn't reproduce it:
```
Base branch: xz9/revrt-61439, building wheel torch-1.11.0a0+gitf499ab9
dcgan train eager (run 10 times):
CPU Total Wall Time: 3555.374 milliseconds
CPU Total Wall Time: 3533.725 milliseconds
CPU Total Wall Time: 3518.126 milliseconds
CPU Total Wall Time: 3567.902 milliseconds
CPU Total Wall Time: 3539.488 milliseconds
CPU Total Wall Time: 3662.840 milliseconds
CPU Total Wall Time: 3554.114 milliseconds
CPU Total Wall Time: 3531.511 milliseconds
CPU Total Wall Time: 3675.938 milliseconds
CPU Total Wall Time: 3521.692 milliseconds
CPU Total Wall Time: 3547.643 milliseconds
CPU Total Wall Time: 3551.979 milliseconds

Revert branch: xz9/revrt-61439-2, building wheel torch-1.11.0a0+git162f7f1
python setup.py bdist_wheel
dcgan train eager (run 10 times):
CPU Total Wall Time: 3512.949 milliseconds
CPU Total Wall Time: 3564.259 milliseconds
CPU Total Wall Time: 3562.136 milliseconds
CPU Total Wall Time: 3555.561 milliseconds
CPU Total Wall Time: 3577.228 milliseconds
CPU Total Wall Time: 3546.203 milliseconds
CPU Total Wall Time: 3559.443 milliseconds
CPU Total Wall Time: 3560.725 milliseconds
CPU Total Wall Time: 3553.631 milliseconds
CPU Total Wall Time: 3538.517 milliseconds
```

There is no significant CPU wall time difference before and after the PR.
Furthermore, I confirm that GeLU is not used in dcgan. Therefore, this is likely caused by noise in our benchmarking environment. Therefore, I am closing this issue.
