### ISSUE TITLE
TorchBench V2 nightly run detects 12% slowdown on dlrm model test

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#74751]
### 🐛 Describe the bug

On 20220309, the TorchBench test test_eval[dlrm-cuda-eager] regresses 12.2% because of the commit https://github.com/pytorch/pytorch/commit/aa5dab02b2.

The perf delta has been validated by PR: https://github.com/pytorch/pytorch/pull/74722. After reverting the commit, the dlrm cuda eval test shows speedup. We observe the latency difference below (lower the better):

```
Benchmark                      Run aa5dab02b246cdd0fe0f81b4fdbf881aeb3ccdb3    Run 098e1c541f00b3796fded53610abf26565895ad7  Delta
---------------------------  ----------------------------------------------  ----------------------------------------------  ------------
test_train[dlrm-cuda-eager]                                      0.0279891                                       0.0271775   -2.986377%
test_eval[dlrm-cuda-eager]                                       0.00707347                                      0.00630243  -12.233998%*
```

Commit https://github.com/pytorch/pytorch/commit/aa5dab0 contains the commit https://github.com/pytorch/pytorch/commit/aa5dab02b2, and commit https://github.com/pytorch/pytorch/commit/098e1c541f00b3796fded53610abf26565895ad7 reverts https://github.com/pytorch/pytorch/commit/aa5dab02b2. After reverting the commit, the latency of test dlrm decreases (show there is speedup).

### Versions

PyTorch 1.12.0.dev20220309+cu113

cc @VitalyFedyunin @ngimel @kshitij12345 @jbschlosser

**Comment by ngimel** [comment]
@kshitij12345 we probably should remove the check from the cuda kernel.
