### ISSUE TITLE
torch.scatter_reduce was erroneously released in 1.11

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#74770]
### 🐛 Describe the bug

`torch.scatter_reduce` was still in development during the 1.11 branch cut but was accidentally released in 1.11 without CUDA support. We might need to break BC for this function in 1.12 by changing the signature. Creating this issue to track the resolution for this

cc @nikitaved @pearu @cpuhrsch @ezyang @gchanan @malfet 

### Versions

N/A

**Comment by atalman** [comment]
@mikaylagawarecki @cpuhrsch @albanD Can we assign someone to this issue ? Please provide mitigation strategy for this issue. What is our plan on addressing this.
