### ISSUE TITLE
with-ssh does not wait on ssh connections to drain before releasing the node on linux

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#74777]
Looks like waiting for ssh connections to drain is turned off by default after the workflow consolidation.

See:

https://github.com/pytorch/pytorch/blob/a75c718d7c370becbf8351f5bba013cfd66cf983/.github/actions/teardown-linux/action.yml#L5-L19

Windows doesn't actually have this issue funnily enough

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
@suo what was the issue with this when you were doing the workflow consolidation?

**Comment by suo** [comment]
Ummmmm, almost certainly just a mistake on my part. I think we were duplicating that step in most of our linux workflows, but I forgot to re-enable it by default after cleaning up the dupes. 

If we always want to wait for ssh to drain on teardown, we can just remove the input and the conditional—I can do it tmr
