### ISSUE TITLE
[ONNX] Export fails with inplace assignments

### ISSUE THREAD

**Issue by timurlenk07** [pytorch/pytorch#74801]
### 🐛 Describe the bug

When trying to export to ONNX a `torch.jit.ScriptFunction` with inplace assignments, the exporter raises a `KeyError: None` and the export fails. The sample code was originally at the end of a YoloX network head that adds grid shifts to the bounding box predictions, but that code was reduced as much as possible to make the debugging (hopefully) easier.

Sample code to reproduce:
```python
from pathlib import Path
from typing import List

import torch
print(torch.__version__)

x1 = ([torch.empty((1, 10, 60, 80)), torch.empty((1, 10, 30, 40)), torch.empty((1, 10, 15, 20))], [8, 16, 32])


def test1(model_outs: List[torch.Tensor], strides: List[int] = (8, 16, 32)) -> torch.Tensor:
    # model_outs: List[Tensor] with len(model_outs) == len(strides), where each tensor is
    # of shape [batch_size, (cxcywh + obj + n_cls), height, width]

    out2 = []
    for i, x in enumerate(model_outs):
        stride = strides[i]

        # x = x.clone()  # Does not help
        x[:, 2:4] = torch.exp(x[:, 2:4]) * stride  # This causes failure
        out2.append(x)

        # # Workaround
        # wh = torch.exp(x[:, 2:4]) * stride
        # out2.append(torch.cat((x[:, :2], wh, x[:, 4:]), dim=1))

    out = [x.reshape(x.shape[0], x.shape[1], -1) for x in out2]  # flatten to [batch_size, n_channels, height * width]
    out = torch.cat(out, dim=2).permute(0, 2, 1)  # reshape to [batch_size, height * width, n_channels]

    return out

test1 = torch.jit.script(test1)
test1(*x1)
print(type(test1))
torch.onnx.export(test1, x1, Path('sth.onnx'),
                  opset_version=15)
```

Output:
```
1.11.0+cu115
<class 'torch.jit.ScriptFunction'>
/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py:359: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
/home/.../env/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:719: UserWarning: allowzero=0 by default. In order to honor zero value in shape use allowzero=1
  warnings.warn("allowzero=0 by default. In order to honor zero value in shape use allowzero=1")
Traceback (most recent call last):
  File "/home/.../random_test.py", line 34, in <module>
    torch.onnx.export(test1, x1, Path('sth.onnx'),
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/__init__.py", line 305, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 719, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 1155, in _run_symbolic_function
    torch._C._jit_pass_onnx_block(b, new_block, operator_export_type, env,
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 1038, in _run_symbolic_function
    return torch._C._jit_onnx_convert_pattern_from_subblock(block, n, env)
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/__init__.py", line 354, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/utils.py", line 1061, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/.../env/lib/python3.8/site-packages/torch/onnx/symbolic_opset11.py", line 186, in index_put
    dtype = sym_help.scalar_type_to_onnx.index(sym_help.cast_pytorch_to_onnx[dtype])
KeyError: None
```

### Versions

```
PyTorch version: 1.11.0+cu115
Is debug build: False
CUDA used to build PyTorch: 11.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-44-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 495.46
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] botorch==0.6.0
[pip3] gpytorch==1.6.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] pytorch-lightning==1.5.9
[pip3] torch==1.11.0+cu115
[pip3] torchaudio==0.11.0+cu115
[pip3] torchmetrics==0.7.1
[pip3] torchvision==0.12.0+cu115
[conda] Could not collect
```

**Comment by BowenBao** [comment]
@timurlenk07 Thanks for reporting, it appears to be fixed in latest pytorch preview build, could you give a try?

**Comment by mzohaibnasir** [comment]
I'm trying to export onxx using torch version=1.12.1+cu113

and I'm encountering the same issue
link to notebook: https://colab.research.google.com/drive/1t9s7_zb6PqHbKRI1VmGGmKuYyWs-qXfL?usp=sharing

p.s. I'm new to pytorch.

`/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py:461: UserWarning: no signature found for <torch.ScriptMethod object at 0x7f76704df8f0>, skipping _decide_input_format
  warnings.warn("%s, skipping _decide_input_format" % e)
/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_helper.py:544: UserWarning: Type cannot be inferred, which might cause exported graph to produce incorrect results.
  "Type cannot be inferred, which might cause exported graph to produce incorrect results."

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[<ipython-input-52-f77621ecf9ae>](https://localhost:8080/#) in <module>
      4     loaded_model,
      5     dummy_input,
----> 6     "/mnist.onnx",
      7 
      8 )

9 frames

[/usr/local/lib/python3.7/dist-packages/torch/onnx/__init__.py](https://localhost:8080/#) in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
    363         keep_initializers_as_inputs,
    364         custom_opsets,
--> 365         export_modules_as_functions,
    366     )
    367 

[/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py](https://localhost:8080/#) in export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, custom_opsets, export_modules_as_functions)
    176         keep_initializers_as_inputs=keep_initializers_as_inputs,
    177         custom_opsets=custom_opsets,
--> 178         export_modules_as_functions=export_modules_as_functions,
    179     )
    180 

[/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py](https://localhost:8080/#) in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, opset_version, do_constant_folding, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names, onnx_shape_inference, export_modules_as_functions)
   1082                 fixed_batch_size=fixed_batch_size,
   1083                 training=training,
-> 1084                 dynamic_axes=dynamic_axes,
   1085             )
   1086 

[/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py](https://localhost:8080/#) in _model_to_graph(model, args, verbose, input_names, output_names, operator_export_type, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size, training, dynamic_axes)
    737             dynamic_axes=dynamic_axes,
    738             input_names=input_names,
--> 739             module=module,
    740         )
    741     except Exception as e:

[/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py](https://localhost:8080/#) in _optimize_graph(graph, operator_export_type, _disable_torch_constant_prop, fixed_batch_size, params_dict, dynamic_axes, input_names, module)
    306         _C._jit_pass_onnx_set_dynamic_input_shape(graph, dynamic_axes, input_names)
    307     _C._jit_pass_onnx_lint(graph)
--> 308     graph = _C._jit_pass_onnx(graph, operator_export_type)
    309     _C._jit_pass_onnx_lint(graph)
    310     _C._jit_pass_lint(graph)

[/usr/local/lib/python3.7/dist-packages/torch/onnx/__init__.py](https://localhost:8080/#) in _run_symbolic_function(*args, **kwargs)
    414     from torch.onnx import utils
    415 
--> 416     return utils._run_symbolic_function(*args, **kwargs)
    417 
    418 

[/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py](https://localhost:8080/#) in _run_symbolic_function(g, block, n, inputs, env, operator_export_type)
   1404             if op_name == "PythonOp":
   1405                 inputs = (n, *inputs)
-> 1406             return symbolic_fn(g, *inputs, **attrs)
   1407         elif ns == "onnx":
   1408             # Clone node to trigger ONNX shape inference

[/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_helper.py](https://localhost:8080/#) in wrapper(g, *args, **kwargs)
    306                 for descriptor, arg in descriptor_args
    307             ):
--> 308                 return fn(g, *args, **kwargs)
    309 
    310             dequantized_args = []

[/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_opset9.py](https://localhost:8080/#) in relu(g, input)
    876 @symbolic_helper.quantized_args(True)
    877 def relu(g, input):
--> 878     return op_with_optional_float_cast(g, "Relu", input, opset_before=14)
    879 
    880 

[/usr/local/lib/python3.7/dist-packages/torch/onnx/symbolic_opset9.py](https://localhost:8080/#) in op_with_optional_float_cast(g, op_name, *args, **kwargs)
    869 
    870     if require_cast:
--> 871         self = g.op("Cast", self, to_i=symbolic_helper.cast_pytorch_to_onnx[dtype_0])
    872 
    873     return self

KeyError: None`

**Comment by thiagocrepaldi** [comment]
Chaning the repro to use the latest onnx exporter, it works

```python
from pathlib import Path
from typing import List

import torch
print(torch.__version__)

x1 = ([torch.empty((1, 10, 60, 80)), torch.empty((1, 10, 30, 40)), torch.empty((1, 10, 15, 20))], [8, 16, 32])


def test1(model_outs: List[torch.Tensor], strides: List[int] = (8, 16, 32)) -> torch.Tensor:
    # model_outs: List[Tensor] with len(model_outs) == len(strides), where each tensor is
    # of shape [batch_size, (cxcywh + obj + n_cls), height, width]

    out2 = []
    for i, x in enumerate(model_outs):
        stride = strides[i]

        # x = x.clone()  # Does not help
        x[:, 2:4] = torch.exp(x[:, 2:4]) * stride  # This causes failure
        out2.append(x)

        # # Workaround
        # wh = torch.exp(x[:, 2:4]) * stride
        # out2.append(torch.cat((x[:, :2], wh, x[:, 4:]), dim=1))

    out = [x.reshape(x.shape[0], x.shape[1], -1) for x in out2]  # flatten to [batch_size, n_channels, height * width]
    out = torch.cat(out, dim=2).permute(0, 2, 1)  # reshape to [batch_size, height * width, n_channels]

    return out

torch.onnx.dynamo_export(test1, *x1)
