### ISSUE TITLE
Failure to build with clang because of unknown warning option error

### ISSUE THREAD

**Issue by aphedges** [pytorch/pytorch#74805]
### 🐛 Describe the bug

I tried to build a development version of PyTorch on macOS Big Sur, but I got the following error:

```console
$ MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py develop
# Many lines omitted here
FAILED: third_party/fbgemm/asmjit/CMakeFiles/asmjit.dir/src/asmjit/core/archtraits.cpp.o 
/Library/Developer/CommandLineTools/usr/bin/clang++  -I/Users/ahedges/projects/personal/pytorch/cmake/../third_party/benchmark/include -isystem /Users/ahedges/projects/personal/pytorch/cmake/../third_party/googletest/googlemock/include -isystem /Users/ahedges/projects/personal/pytorch/cmake/../third_party/googletest/googletest/include -isystem /Users/ahedges/projects/personal/pytorch/third_party/protobuf/src -isystem /Users/ahedges/projects/personal/pytorch/third_party/gemmlowp -isystem /Users/ahedges/projects/personal/pytorch/third_party/neon2sse -isystem /Users/ahedges/projects/personal/pytorch/third_party/XNNPACK/include -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Wall -Wextra -Werror -Wno-deprecated-declarations -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=10.9 -fPIC -fvisibility=hidden -Wall -Wextra -Wconversion -fno-math-errno -fno-threadsafe-statics -DASMJIT_STATIC -O2 -fmerge-all-constants -Wno-deprecated-copy -Wno-unused-but-set-variable -std=c++14 -MD -MT third_party/fbgemm/asmjit/CMakeFiles/asmjit.dir/src/asmjit/core/archtraits.cpp.o -MF third_party/fbgemm/asmjit/CMakeFiles/asmjit.dir/src/asmjit/core/archtraits.cpp.o.d -o third_party/fbgemm/asmjit/CMakeFiles/asmjit.dir/src/asmjit/core/archtraits.cpp.o -c /Users/ahedges/projects/personal/pytorch/third_party/fbgemm/third_party/asmjit/src/asmjit/core/archtraits.cpp
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
# More lines omitted here
```

I was able to create a minimal reproduction with the following code:

```console
$ touch foo.cpp && clang++ -Werror -Wno-unused-but-set-variable foo.cpp
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
```

I'm not 100% sure when this error started, but I believe it was with 14dcb5a1a0f764ec67b7d4d7f607121fe9757b71, which was created to solve #74352. If I make the following change, I am able to build PyTorch successfully:

```diff
diff --git a/cmake/Dependencies.cmake b/cmake/Dependencies.cmake
index ba2e71211f..f68cec720d 100644
--- a/cmake/Dependencies.cmake
+++ b/cmake/Dependencies.cmake
@@ -818,7 +818,7 @@ if(USE_FBGEMM)
     set_property(TARGET fbgemm PROPERTY POSITION_INDEPENDENT_CODE ON)
     if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 13.0.0)
         # See https://github.com/pytorch/pytorch/issues/74352
-        target_compile_options(asmjit PRIVATE -Wno-deprecated-copy -Wno-unused-but-set-variable)
+        target_compile_options(asmjit PRIVATE -Wno-deprecated-copy)
     endif()
   endif()
 
```

I'm not proposing this as a patch because I do not have enough information to not break other's builds. For example, this diff would likely undo the solution for #74352, which applied to a newer version of macOS and Clang.

One of the most confusing parts of this is that the release notes for Clang 13.0.0 say that the warning should be recognized (<https://releases.llvm.org/13.0.0/tools/clang/docs/ReleaseNotes.html#new-compiler-flags>), and the associated commits all appear to be in v13.0.0 (<https://reviews.llvm.org/D100581>). Some of my coworkers should have different versions, so I'll ask some of them next week to test their versions of Clang for the warning.

### Versions

PyTorch version: 1.12.0a0+git5375b2e
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.6.5 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.3
Libc version: N/A

Python version: 3.7.13 (default, Mar 17 2022, 14:15:44)  [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.12.0a0+git5375b2e
[conda] Could not collect

cc @malfet @seemethere @albanD

**Comment by dzdang** [comment]
Did you upgrade your macOS recently? I noticed this error after I upgraded macOS, I think. I have no issues compiling the latest on any of my linux machines

**Comment by aphedges** [comment]
@dzdang, I haven't updated to a new major macOS version recently (my update to Big Sur was in October), but this is the first time I've tried to build PyTorch since mid-2020. The configuration that broke the build was added only 2 weeks ago, so it may or may not be related to your upgrade.

**Comment by kit1980** [comment]
I'm having the same issue on MacOS now trying to build master from scratch.

**Comment by kit1980** [comment]
clang --version                                                          
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode_13.2.1_fb.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by kit1980** [comment]
> One of the most confusing parts of this is that the release notes for Clang 13.0.0 say that the warning should be recognized (https://releases.llvm.org/13.0.0/tools/clang/docs/ReleaseNotes.html#new-compiler-flags), and the associated commits all appear to be in v13.0.0 (https://reviews.llvm.org/D100581).

It looks like D100581 was reverted https://reviews.llvm.org/rG6d8d1338629ceeaf6f56dc9eabc72e1a63f05169

**Comment by aphedges** [comment]
I haven't gotten around to writing up my findings in the past couple of months, but the core problem is that Apple uses a different versioning scheme than upstream Clang. What Apple says is Clang 13 is actually upstream Clang 12. This makes reading release notes a lot more annoying. The full alignment of upstream and Apple versions is available at <https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_14.x_(since_SwiftUI_framework)_2>. My coworkers using Clang 13.1.6 verified they were able to use the flag.

I didn't end up putting a PR in myself because I don't know CMake, I don't have the resources to test the PR on different versions of Clang myself, and I didn't expect it would even get reviewed, given that I'm still waiting for review on a 2-line bug fix PR I created the same week as this issue.

**Comment by zoldaten** [comment]
i tried aphedges suggestion when building pytorch on odroid xu4 ubuntu 20.04 but failed.
i used clang version 10.0.0-4ubuntu1, gcc (Ubuntu/Linaro 8.4.0-3ubuntu2) 8.4.0
here is the traceback:
```
[ 71%] Building CXX object caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/RegisterCompositeImplicitAutogradNestedTensor.cpp.o
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
warning: unknown warning option '-Werror=cast-function-type'; did you mean '-Werror=bad-function-cast'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-stringop-overflow'; did you mean '-Wno-shift-overflow'? [-Wunknown-warning-option]
4 warnings generated.
4 warnings generated.
4 warnings generated.
4 warnings generated.
4 warnings generated.
4 warnings generated.
4 warnings generated.
make[1]: *** [CMakeFiles/Makefile2:6385: caffe2/CMakeFiles/torch_cpu.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

although i havent got any error warnings the build failed.

**Comment by aphedges** [comment]
@zoldaten, I suggest you open a new issue. You're likely using the upstream version of Clang, but Apple has a custom fork that I was having problems with. Even the major version numbers are different between upstream and downstream.
