### ISSUE TITLE
Linker Error MacOSX libtorch for arm64

### ISSUE THREAD

**Issue by arunppsg** [pytorch/pytorch#74811]
### 🐛 Describe the bug

I  am trying to install and run a minimal C++ distribution of Pytorch. I installed the latest stable libtorch distribution for macos and created an `example-cpp` directory with contents for `example.cpp` and `CMakeLists.txt` from pytorch [docs](https://pytorch.org/cppdocs/installing.html). 

Then, I ran the following commands:
```
$ mkdir build
$ cd build
$ cmake -DCMAKE_PREFIX_PATH=/Users/arun/pyt-cpp/libt/libtorch-macos-1-11/libtorch ..

-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- MKL_ARCH: None, set to ` intel64` by default
-- MKL_ROOT /Users/arun/miniconda3/envs/pyg
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
-- MKL_THREADING: None, set to ` intel_thread` by default
-- MKL_MPI: None, set to ` mpich` by default
-- Found Torch: /Users/arun/pyt-cpp/libt/libtorch-macos-1-11/libtorch/lib/libtorch.dylib  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/arun/pyt-cpp/example-app/build

$ cmake --build . --config Release
[ 50%] Building CXX object CMakeFiles/example-app.dir/example-app.cpp.o
[100%] Linking CXX executable example-app
ld: library not found for -lmkl_intel_ilp64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example-app] Error 1
```

Here, I am getting a linker error. I think the issue is based on the first output in the following lines: `MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default`. I am not sure what values to set for `MKL_INTERFACE_FULL` and how to set it (`set(MKL_INTERFACE_FULL, ---)` in CMakeFiles.txt?). Any help would be appreciated.

Thanks!

### Versions

PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.3.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.8.12 (default, Oct 12 2021, 06:23:56)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @malfet @seemethere @jbschlosser @albanD

**Comment by arunppsg** [comment]
I tried a very naive method of fixing it: found the missing linker library `lmkl_intel_ilp64` at `/Users/arun/miniconda3/lib/` and moved it to the `libtorch/lib` folder hoping that linker will be able to find it but it didn't work.

Is there someway I could add a debug option to the linker command or modify it? Sorry if this is a naive question.. This is the first time I am coming across cmake, libtorch and linker, so please bear with me...

**Comment by albanD** [comment]
From the logs above, it looks like you are using an x86 version of python (which runs through mac's conversion layer I guess)?
Is there any specific reason why you're not using an arm64 version of python directly?

**Comment by arunppsg** [comment]
Oops, all this time I was using the python distribution from conda - not the arm64 version of python. I didn't know that the python distribution from conda was an intel one and it probably did not go through the conversion layer. I deactivated the conda environment and ran the commands and it worked. Thanks!

**Comment by chenyixin1008** [comment]
> 

Hi! I met the same problem with you and even if I deactivate the env I still got this linker error.
<img width="440" alt="image" src="https://user-images.githubusercontent.com/37447829/170336925-6a99355d-dcd1-471c-a2d1-4e940845e5fb.png">

**Comment by chenyixin1008** [comment]
> From the logs above, it looks like you are using an x86 version of python (which runs through mac's conversion layer I guess)? Is there any specific reason why you're not using an arm64 version of python directly?

Is it okay to use the arm64 version of python on a non-M1 mac? @albanD

**Comment by albanD** [comment]
Hi,

I'm afraid the x86 macs will not allow that no.
Using the x86 versino on an M1 mac is enabled via the Rosetta layer from Apple to allow "old" macos apps to easily run on the new hardware.
