### ISSUE TITLE
.gitignore core.* regex needs refinement

### ISSUE THREAD

**Issue by vors** [pytorch/pytorch#74890]
### 🐛 Describe the bug

The `core.*` regex https://github.com/pytorch/pytorch/blob/51e50a2ddb9844e0abaf6028fe5e4246448dffff/.gitignore#L313 includes files named `core.py`
[1] https://github.com/pytorch/pytorch/blob/v1.10.0/torch/fx/experimental/unification/core.py
[2] https://github.com/pytorch/pytorch/blob/v1.10.0/torch/fx/experimental/unification/multipledispatch/core.py

This leads to problematic behavior, for example when you are trying to add a new `core.py` file, it's easy to miss force-add.

The suggestion is to refine the regex to avoid including files like `core.py`, `core.cpp` etc.
I would do it myself, but unfortunately I don't know what is the format of the core dump names that the regex is meant to ignore.

In case it's obsolete consider removing it altogether.

### Versions

n/a

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by albanD** [comment]
Thanks @LemonPepperSeasoning 
I'm afraid there isn't much to be done here until we hear back from the Infra team on what was the exact reason for adding this line.

**Comment by albanD** [comment]
@LemonPepperSeasoning could you send a PR updating the gitignore file with this please?
