### ISSUE TITLE
Lookup in my code ,i got NameError: name 'x' is not defined

### ISSUE THREAD

**Issue by Rock8090** [pytorch/pytorch#74905]
# Parametric rectified linear unit (PReLU):
def prelu(x,a=0.01):
  return x*a if x < 0 else x  
  
# PReLU derivative:
def prelu_deriv(x,a=0.01): 
  return a if x < 0 else 1
print("PReLU of x with a = 0.01:" + str(prelu(x)))
print("PReLU of x if x = -1.0 with a = 0.01: " +(prelu(-1.0)))
print("PReLU derivative of x with a = 0.01: " + (prelu_deriv(x)))
print("PReLU derivative of x if x = -1.0 with a = 0.01: " + (prelu_deriv(-1.0)))

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
