### ISSUE TITLE
Virtualize TensorImpl::Layout for sparse formats

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#74916]
## Summary

We want (and should) support all of CSR, CSC, BSR and BSC using just SparseCsrTensorImpl.

We currently have a [many-to-one relationship between dispatch keys and layouts](https://github.com/pytorch/pytorch/blob/master/c10/core/TensorImpl.h#L993-L1004).

```
  Layout layout() const {
    // NB: This method is not virtual and avoid dispatches for perf.
    if (is_sparse()) {
      return kSparse;
    } else if (is_sparse_csr()) {
      return kSparseCsr;
    } else if (is_mkldnn()) {
      return kMkldnn;
    } else {
      return kStrided;
    }
  }
```

Each of the "is_*" methods checks whether the TensorImpl has one of a certain set of dispatch keys.

We should be able to map from one dispatch key to multiple layouts.

## Virtualizing layout for sparse Tensors

`Layout TensorImpl::layout() const` is not virtual for performance and we can't change that. Introducing a new field also has downsides (memory), so if we can we should avoid adding a new field.

Now, to sidestep very long discussions around performance and memory footprint this proposal aims to find a solution that is slower for users of sparse Tensors, but shouldn't interfere with existing applications.

1. Introduce `virtual Layout TensorImpl::slow_layout const`
2. [`SparseCsrTensorImpl`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/SparseCsrTensorImpl.h) overwrites slow_layout to return the correct layout (e.g. CSC or BSC) to yield `Layout SparseCsrTensorImpl::slow_layout const`
3. `Layout TensorImpl::layout() const` calls into `slow_layout` when needed.

The final version of `Layout TensorImpl::layout const` then should look like
```
  Layout layout() const {
    // NB: This method is not virtual and avoid dispatches for perf.
    if (is_sparse()) {
      return kSparse;
    } else if (is_sparse_csr()) {
      return slow_layout(); // This is new
    } else if (is_mkldnn()) {
      return kMkldnn;
    } else {
      return kStrided;
    }
  }
```

## Further fallout
[`dispatchKeyToLayout`](https://github.com/pytorch/pytorch/blob/58dabebcd746aad95a37bdfc7e60e5d22f0f5641/c10/core/TensorOptions.h#L734-L749) will need to be modified to throw in cases where it's not possible to determine the relationship uniquely. This affects the constructors also via [`dispatchKeyToTensorOptions`](https://github.com/pytorch/pytorch/blob/58dabebcd746aad95a37bdfc7e60e5d22f0f5641/c10/core/TensorOptions.h#L805-L809).

Callsites for `dispatchKeyToLayout`
[`legacy constructor`](https://github.com/pytorch/pytorch/blob/a9b0a921d592b328e7e80a436ef065dadda5f01b/torch/csrc/autograd/python_legacy_variable.cpp#L49-L56) - uses dispatchKeyToLayout to get layout of default dispatch key (which is CPU), so this won't have to change.

Callsites for `dispatchKeyToTensorOptions`
[`_validate_sparse_coo_tensor_args`](https://github.com/pytorch/pytorch/blob/2f90c82265c67d153bdb6d5b04782695b62986ab/torch/csrc/utils/tensor_new.cpp#L807-L823) - can construct TensorOptions by other means or we extend `dispatchKeyToLayout` to accept a Layout in cases where it's necessary to disambiguate.

[`_validate_sparse_csr_tensor_args`](https://github.com/pytorch/pytorch/blob/2f90c82265c67d153bdb6d5b04782695b62986ab/torch/csrc/utils/tensor_new.cpp#L826-L846) - same story as `_validate_sparse_coo_tensor_args`

### Alternatives

We could introduce one dispatch key per Layout+Device combination like we're currently doing, but then we'll run out of dispatch keys, which we've just worked so hard to free up.

cc @nikitaved @pearu @cpuhrsch

**Comment by cpuhrsch** [comment]
cc @ezyang @albanD @pearu @IvanYashchuk

**Comment by ezyang** [comment]
I want to add a few extra constraints to the discussion here.

* I want the virtualization mechanism used here to be compatible with `__torch_dispatch__` users; in particular, wrapper semantics will want to forward the layout request to the inner tensor. To do this, we cannot use a stock virtual method; instead, we should go through the dispatcher when going through the slow path.
* I want a simple condition for virtualization that doesn't require people to keep modifying the `layout()` method on TensorImpl every time they want their special case. For example, a single bit in our boolean flags saying "hey, use the dispatcher instead" would be more satisfying than a bunch of if-elses on "is sparse".

Many of these things can be done in stages so I don't mind temporarily not doing some of them if we have a plan on record on how to get to the final state.

**Comment by cpuhrsch** [comment]
@ezyang - are you ok with what we have planned now and doing this later?

**Comment by ezyang** [comment]
Virtual function is OK for now, since it looks like `is_contiguous` on TensorImpl is done the same way. However, `contiguous` on Tensor is the way I'd like things to look eventually everywhere.

**Comment by cpuhrsch** [comment]
Ok, thanks @ezyang!

@pearu could you take a stab at implementing this?

**Comment by pearu** [comment]
Instead of introducing a bunch of `is_sparse_xyz()` methods for xyz in {csc, bsr, bsc}, what do you think about introducing a single method `has_layout(layout)` along the lines of the virtualizing layout() method discussed here?
The `is_sparse_xyz` tests would be implemented as (pseudo-code follows):
```
def is_sparse_xyz(self):
    return self.has_layout(torch.sparse_xyz)
```
both for Python as well as C++ API. What do you think?

**Comment by pearu** [comment]
> @pearu - I think we can do that, but it's separate from this issue. We already have `layout`, so kind of like `dtype` people can compare it to the enum. We don't have `has_dtype`.

We don't have `is_float64`, `is_int32`, etc either. It would be sufficient to have only `layout`, all the `is_sparse*` methods are superfluous. But yeah, I agree, this is another issue.

**Comment by cpuhrsch** [comment]
@pearu - yeah `is_sparse` is likely a remnant of how things were built up a long time ago (since SparseTensor has been around since the beta days). We could perhaps even have `is_sparse` mean all of COO, CSR, CSC, BSR, BSC and then point to `layout` for users to differentiate. We'd then not add any more functions. Maybe, just so we don't introduce something we'll later on have to remove again, we should just not add `is_sparse_csc` and `is_sparse_bsr` for now until this is resolved.

**Comment by pearu** [comment]
As follows from https://github.com/pytorch/pytorch/pull/75023 (below called as the "current state"), SparseCsrTensorImpl holds 4 layouts to represent CSR, CSC, BSR, and BSC sparse tensors.The corresponding tensors can currently be constructed using CSR tensor factory function:
```python
t = torch.sparse_csr_tensor(compressed_indices, other_indices, size, ..., layout=...)
```
where in `layout=...` one can specify `sparse_csr`, `sparse_csc`, `sparse_bsr`, or `sparse_bsc` (prefixed with `torch.`).

In addition, the indices data of these tensors can be accessed via CSR specific methods:
```python
t.crow_indices()
t.col_indices()
```

Clearly, this UI is confusing, say, when working with CSC tensors and in the following, I'd like to discuss possible options for improving the UI for sparse compressed tensors.

First, here follow some possible construction options for a sparse CSC tensor (using CSC just as an example):
1. `t = torch.sparse_csr_tensor(ccol_indices, row_indices, size, ..., layout=torch.sparse_csr)` - the current state
2. `t = torch.sparse_csc_tensor(ccol_indices, row_indices, size, ...)` - each layout would have its own factory function
3. `t = torch.sparse_csc_tensor(row_indices, ccol_indices, size, ...)` - same as 2 but the first two arguments are switched
4. `t = torch.sparse_compressed_tensor(compressed_indices, other_indices, layout=torch.sparse_csc)` - one factory function for all four layouts. `torch.sparse_csr_tensor` would be deprecated (or not?).
5. Any other option?

Second, here follow some possible indices data access methods for a sparse CSC tensor:
1. `t.crow_indices(), t.col_indices()` - the current state
2. `t.ccol_indices(), t.row_indices()` - available only for CSC and BSC layouts, raise exception for CSR and BSR layouts
3. `t.compressed_indices(), t.other_indices()` - usable for all layouts
4. `t.indices()` - returns a tuple of `(compressed_indices, other_indices)` - usable for all layouts, method naming taken from sparse COO feature set.
5. Any other method combination?

What do you think? Could you give your preferences on sparse tensor construction and their indices access methods?

**Comment by cpuhrsch** [comment]
@pearu  - For the purposes of this PR let's follow existing conventions. To the first point, let's go with option 2. To the second, let's go with option 2. However, let's add a leading underscore to these functions and open up a separate discussion around a unified API for these various compressed layout. In particular, could I ask you to open a separate feature proposal for option 4?

**Comment by pearu** [comment]
Resolved via https://github.com/pytorch/pytorch/pull/75821
