### ISSUE TITLE
AttributeError: module 'torch.nn' has no attribute 'BCEWithLogitsLoss'

### ISSUE THREAD

**Issue by linrio** [pytorch/pytorch#7494]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

BCEWithLogitsLoss and torch.version.cuda'

## Code example

I installed pytorch by `conda install pytorch torchvision -c pytorch` 

import torch
import torch.nn as nn
...
criterion = nn.BCEWithLogitsLoss()
AttributeError: module 'torch.nn' has no attribute 'BCEWithLogitsLoss'

cuda_compiled_version=torch.version.cuda,
AttributeError: module 'torch.version' has no attribute 'cuda'

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:pytorch
- How you installed PyTorch (conda, pip, source):conda
- Build command you used (if compiling from source): --
- OS:ubuntu
- PyTorch version:1.0
- Python version:3.6
- CUDA/cuDNN version:8.04
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
What is you `torch.__version__`? You might have gotten an older version.

**Comment by linrio** [comment]
```
import torch
print(torch.__version__)
0.1.12_1
```

**Comment by zou3519** [comment]
That is too old. You should upgrade to the latest version of pytorch (which is 0.4). Installation instructions can be found at our [main website](https://pytorch.org/). Hope that helps!

If you don't want to upgrade you can probably copy and paste the BCELossWithLogits code and make your own Loss function.

**Comment by linrio** [comment]
@zou3519  Okay, Tks!
