### ISSUE TITLE
cmake dependency causing failures on Windows Builds

### ISSUE THREAD

**Issue by zengk95** [pytorch/pytorch#74955]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
Root cause has been determined and currently trying to land fix in #74954 

## Error looks like
```
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
```

## Incident timeline (all times pacific)

<details>
<summary> Click for example </summary>

- 3/29 10PM CST First error on HUD
- 3/30 6AM CST  First alert fired
- 3/30 8AM CST Responded and started debugging
- 3/30 9:15 CST Found issue and attempting to fix

</details>

## User impact
Pytorch users have broken windows builds

## Root cause
Cmake dependency updated and didn't set an internal variable we needed.

## Mitigation
Pinning the Cmake version

## Prevention/followups
- Pin more things
- Retry with older versions?

**Comment by janeyx99** [comment]
Update: Nikita--this is a cmake bug (conda yanked it afterwards). We should just unpin it, make sure it works and then be done with this. (I will add this to Dev Infra Backlog to discuss next sprint.)
