### ISSUE TITLE
cmake==3.23.0 breaks the build with `CMAKE_CUDA_COMPILE_WHOLE_COMPILATION`

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#74985]
### 🐛 Describe the bug

Updating `cmake` to `3.23.0` seems to break the current build and fails with:
```
...
--   USE_DEPLOY           : OFF
--   USE_BREAKPAD         : ON
--   Public Dependencies  : caffe2::Threads;caffe2::mkl
--   Private Dependencies : pthreadpool;cpuinfo;qnnpack;pytorch_qnnpack;nnpack;XNNPACK;fbgemm;/usr/lib/x86_64-linux-gnu/libnuma.so;fp16;/opt/hpcx/ompi/lib/libmpi.so;gloo;tensorpipe;foxi_loader;rt;fmt::fmt-header-only;kineto;gcc_s;gcc;dl
--   USE_COREML_DELEGATE     : OFF
--   BUILD_LAZY_TS_BACKEND   : ON
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_CUDA_COMPILE_WHOLE_COMPILATION
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
...
```
Steps to reproduce:
* `conda install cmake==3.23.0`
* `python setup.py develop` 

Downgrading to `cmake==3.22.3` seems to solve this issue.

Unclear what's causing the failure, so I'll try to dig more into it, but wanted to share the workaround in case more users are hitting the issue.

### Versions

No version information available as the build breaks.
Reproduced the issue with `954c7e2a77` on Ubuntu 20.04 with CUDA11.6.

CC @malfet @atalman 

cc @malfet @seemethere

**Comment by malfet** [comment]
See also: https://github.com/pytorch/pytorch/issues/74955

**Comment by crcrpar** [comment]
fyi: https://gitlab.kitware.com/cmake/cmake/-/issues/23368

**Comment by malfet** [comment]
Please note, that `cmake`=3.23 is yet not available in [conda](https://anaconda.org/anaconda/cmake) only in [conda-forge](https://anaconda.org/conda-forge/cmake)

**Comment by ph-code-repo** [comment]
I am still getting this issue this morning, and will be trying the downgrade option mentioned in OP.

**Comment by ptrblck** [comment]
FYI: `cmake-3.23.1` is now available which fixes the issue
