### ISSUE TITLE
[PyTorch] KeyError: 'momentum' while using SGD optimizer

### ISSUE THREAD

**Issue by hzxie** [pytorch/pytorch#7499]
## Issue description

When I use SGD optimizer, I got an error saying:

```
Traceback (most recent call last):
  File "runner.py", line 100, in <module>
    main()
  File "runner.py", line 82, in main
    train_net(cfg)
  File "/home/hzxie/Development/Python/Pixel2Voxel/core/train.py", line 183, in train_net
    encoder_solver.step()
  File "/usr/lib/python3.6/site-packages/torch/optim/sgd.py", line 84, in step
    momentum = group['momentum']
KeyError: 'momentum'
```

## Code example

```
cfg.TRAIN.ENCODER_LEARNING_RATE = 0.001
cfg.TRAIN.MOMENTUM = 0.9

encoder_solver = torch.optim.SGD(filter(lambda p: p.requires_grad, encoder.parameters()), 
    lr=cfg.TRAIN.ENCODER_LEARNING_RATE, momentum=cfg.TRAIN.MOMENTUM)
```

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Arch Linux
GCC version: (GCC) 8.1.0
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 390.48
cuDNN version: 7.1.3

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] tensorboard-pytorch (0.7.1)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.0)
[conda] Could not collect

**Comment by hzxie** [comment]
Because I loaded checkpoints from an Adam optimizer.

**Comment by Whu-wxy** [comment]
I met the same problem when load state from check point. The following error occurred after changing to adam. Have you encountered it?

```
File "/xxxxxxxxxxxxxx/site-packages/torch/optim/adam.py", line 69, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)

RuntimeError: The size of tensor a (256) must match the size of tensor b (1024) at 
non-singleton dimension 1
```

**Comment by Swjtu-only** [comment]
> Because I loaded checkpoints from an Adam optimizer.
ts for u check
