### ISSUE TITLE
Error (Possibly unintuitive) print value for a Tensor

### ISSUE THREAD

**Issue by successar** [pytorch/pytorch#7501]
## Issue description

In the example below, when printing the value of Tensor, it seems to show multiplication by 1e-3 along with the Tensor's value.

## Code example

```python
import torch
print(torch.Tensor([0.001])
```
Output 
```python
tensor(1.00000e-03 *
       [ 0.0010])
```

## System Info
Please copy and paste the output from our
<pre>Collecting environment information...
PyTorch version: 0.5.0a0+0703357
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.3.0-16ubuntu3) 7.3.0
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GT 1030

Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.7.1.3
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] msgpack-numpy (0.4.3)
[pip3] numpy (1.14.2)
[pip3] numpydoc (0.8.0)
[pip3] torch (0.5.0a0+703357)
[pip3] torchsparseattn (0.2.dev0, /media/sarthak/data/projects/ROB/sparse-structured-attention/pytorch)
[pip3] torchtext (0.2.3)
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+703357            &lt;pip&gt;
[conda] torchsparseattn           0.2.dev0                  &lt;pip&gt;
[conda] torchtext                 0.2.3                     &lt;pip&gt;
</pre>

**Comment by zou3519** [comment]
Thanks for the report! This has been fixed on master:
```
│In [1]: import torch
│   ...: print(torch.Tensor([0.001]))
│   ...:
│tensor(1.00000e-03 *
│       [ 1.0000])
│

```
