### ISSUE TITLE
Inconsistency with the definition of aten::index_put.hacked_twin op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [pytorch/pytorch#75015]
### 🐛 Describe the bug

Hi!

The definition of `aten::index_put.hacked_twin` op is inconsistent. The `indices` argument is declared to be of `TensorListType` https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L1022
but it's getting casted into a `OptionalTensorListType` https://github.com/pytorch/pytorch/blob/3024bcfff5c5e497b602063dc2d948a4d4c10155/torch/csrc/jit/runtime/register_prim_ops.cpp#L1026
which results in the following runtime error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vivek/work/02_07/mlir_venv/lib/python3.8/site-packages/torch/_ops.py", line 48, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Tried to cast a List<Tensor> to a List<Tensor?>. Types mismatch.
```

The bug can be reproduced with the following code:
```
import torch

input = torch.randn(10)
index = torch.randint(10, (20,))
value = torch.randn(20)

torch.ops.aten.index_put.hacked_twin(input, [index], value, accumulate=False)
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220314+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 11.6.55
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.2.0a0+8fa6352
[pip3] numpy==1.22.2
[pip3] torch==1.12.0.dev20220314+cpu
[pip3] torchvision==0.13.0.dev20220314+cpu
[conda] Could not collect

**Comment by vivekkhandelwal1** [comment]
@Chillee Please take a look at this issue.

**Comment by Chillee** [comment]
cc: @eellison

**Comment by vivekkhandelwal1** [comment]
Hi, @Chillee @eellison, any update on this issue?
