### ISSUE TITLE
Drop support for magma v1 (compilation with it is broken right now)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7502]
71626491c40c86eb1ee410e695c467486084144c adds a use of `magma_queue_create_from_cuda` which appears to only be available in Magma 2. This breaks the GH to fbcode sync.

We could add back the macros we need, but perhaps we should just drop support for Magma 1?

CC @zou3519 @soumith

**Comment by soumith** [comment]
yes please, drop support or magma1

**Comment by zou3519** [comment]
I can add a warning and/or compiler error if someone tries to compile with magma 1. What else should be done to drop support for magma1?

**Comment by ezyang** [comment]
Remove all the `MAGMA_V2` ifdefs
