### ISSUE TITLE
[Quant] Quantizable LSTM uses asterisk unpacking, not supported by torchscript

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#75042]
Here are the two lines that do this: https://github.com/pytorch/pytorch/blob/c0a6add7eef8ab3715c0f4281b3b7a2a0f1e24b5/torch/nn/quantizable/modules/rnn.py#L355-L356

**Original user error:**
Hi! I'm running QAT on a model with LSTM and I'm seeing errors in model export using static scripting (tracing works fine but it looses some model attributes that are needed for inference).
```
cannot statically infer the expected size of a list in this context: File <...>
   # We are creating another dimension for bidirectional case
   # need to collapse it
   hx_tensor = hx_tensor.reshape(-1, *hx_tensor.shape[-2:])                                          ~~~~~~~~~~~~~~~~~~~~ <--- HERE         
   cx_tensor = cx_tensor.reshape(-1, *cx_tensor.shape[-2:])
```

**Suggested fix by @gmagogsfm:**
Asterisk-based unpacking is not supported on list in Torchscript because it is unknown how many values should be retrieved.
Instead, you can use something like this (more hard coded) to perform what you'd like:
```
@torch.jit.script
def works(x: torch.Tensor, y: torch.Tensor):
    x = x.reshape(-1, y.shape[1], y.shape[2])
    return x
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vadimkantorov** [comment]
In this particular case, could `flatten` be used? e.g. `hx_tensor.flatten(end_dim = -3)`?

**Comment by andrewor14** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/83304

**Comment by andrewor14** [comment]
Hi @vadimkantorov, it's possible to use flatten, but maybe just explicitly spelling out the items in this case is simpler. I'm not sure if there are plans to add asterisk expansion support in torchscript at this point so we may have to work around it.

**Comment by vadimkantorov** [comment]
I hope the graph is as simple as with flatten :) anyway...
