### ISSUE TITLE
[jit] refactor and document the ways the graph executor will optimize/run programs

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#7507]
Graph executor logic has gotten complicated due to many properties:

* Can we symbolically differentiate this graph?
* Can we compute static sizes for the graph (effects the above but is not checked)?
* Can the graph ever require us to compute a gradient? (Including graphs that have blackbox python ops and no grad-aware inputs)?

Each of these properties make certain approaches to execution invalid. We need to define more clearly what properties must hold along each pathway int the graph executor and when possible add dynamic checks to the slow paths that these properties are not violated. 

We also need to consider what JIT should do in the presence of control flow. Right now we optimize per-size, per-block, but for loops with truly dynamic sizes in the body this may produce an infinite number of options.

**Comment by eellison** [comment]
Old issue, and seems like profiling executor solves this issue. Closing, re-open if you think this is still relevant.
