### ISSUE TITLE
python 3.10 cannot use pytorch

### ISSUE THREAD

**Issue by howtoblind** [pytorch/pytorch#75144]
### 🐛 Describe the bug

`t.sum().backward()`
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    t.sum().backward()
  File "D:\Python\Python310\lib\site-packages\torch\_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "D:\Python\Python310\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### Versions

name: Bug Report
description: File a bug report
title: "[Bug]:could not run the pytorch in python==3.10 "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. 这将自动格式化为代码，因此无需背板。
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
`import torch`
Warning (from warnings module):
  File "D:\Python\Python310\lib\site-packages\torch\_masked\__init__.py", line 223
    example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by ketangangal** [comment]
Hello @howtoblind,

I tried to reproduce this issue but for me torch with python version 3.10.0 is working fine.

`
import torch
import os

os.system('python --version')
print(torch.tensor([1, 2, 3, 4]).float())

`
![image](https://user-images.githubusercontent.com/40850370/161399416-76fcb58a-909e-4ac0-9750-478f5801e666.png)

**Comment by mruberry** [comment]
Make sure `t` requires a gradient.
