### ISSUE TITLE
TLS certificate of download.pytorch.org is expired

### ISSUE THREAD

**Issue by Karuso33** [pytorch/pytorch#75153]
The TLS certificate that is used, for example, at https://download.pytorch.org/whl/torch_stable.html is expired as of right now.

cc @ezyang @gchanan @zou3519

**Comment by fukatani** [comment]
I found certificate of https://download.pytorch.org/whl/cpu has also expired.

**Comment by FrederickGeek8** [comment]
The entire domain is affected so all `download.pytorch.org` URLs are down. 
<img src='https://discuss.pytorch.org/uploads/default/optimized/3X/e/4/e4586d0f0b039514e5cffc2b5ddb8a415b00ff2b_2_1012x1000.png' width='500' alt='Screenshot of TLS cert' />

**Comment by MSFTserver** [comment]
All https urls are down, you can alternatively install manually and use http links, if you do need to get it running for whatever reason

**Comment by johnowhitaker** [comment]
This is quite a high priority - a lot of code relies on these pretrained models and users doing something like 
`import torchvision.models as models`
`m = models.vgg16(pretrained=True)`
Are going to hit the error and have no easy way to fix it.

**Comment by Binxly** [comment]
A quick fix before their renewal rolls out, from using @The Comet Is Coming in the discord
Add a cell above Cell 2, and paste in the following, using the URL for the model with HTTP, instead. 
`!wget -O /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth http://download.pytorch.org/models/vgg16-397923af.pth`

**Comment by soumith** [comment]
@seemethere has just issued new certs. might take a sec to propagate through

**Comment by soumith** [comment]
fixed should be live now (I see it resolve correctly in an incognito window or with a cache-cleared browser)

**Comment by soumith** [comment]
apologies for this. @seemethere will do an internal postmortem next week and put better processes in place for this to not break
