### ISSUE TITLE
ROCm test reports not found

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#75169]
### 🐛 Describe the bug

In CI, we currently cannot collect test reports for ROCm. This means that we cannot analyze stats for ROCm workflows and thus miss out on a variety of features, including:
- Having a test history for ROCm (was a test always skipped or never run, etc)
- Allowing us to debug flakiness that spans overtime
- Automatically disabling flaky tests based on the stats collected automatically 

For example, take these logs here https://github.com/pytorch/pytorch/runs/5796183331?check_suite_focus=true. In the two Upload Test Stat steps (we should probably differentiate them better but that's beside the point here), no test reports were found. Typically, the test reports would tell us that the failed test was rerun and is flaky and send some data to Rockset, where we gather flaky tests. Within 3 hours, our flaky test bot would parse those stats and disable the test/file an issue for us automatically. However, since the reports were missing, flaky test bot couldn't do its job properly and @malfet had to manually open https://github.com/pytorch/pytorch/issues/75139.

**Probable fix**: we current look for test reports under the test/ directory. Moving the test reports there would solve this issue.

### Versions

In all CI for ROCm.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by janeyx99** [comment]
@seemethere's fix would fix the problem for passing ROCm tests, but the no test reports error still occurs for jobs with failed instances. This is bad because the test stats would miss out on all the red signal stats, which are just as crucial if not more crucial than the green signal stats. 

An example: https://github.com/pytorch/pytorch/runs/6058741074?check_suite_focus=true

**Comment by janeyx99** [comment]
@jeffdaily  linking you for context

**Comment by seemethere** [comment]
Assigning to @jeffdaily to fix

**Comment by janeyx99** [comment]
https://github.com/pytorch/pytorch/runs/6218599622?check_suite_focus=true Looks like there are still permission issues for ROCm report uploading. @seemethere is there documentation on how to enable permissions to fix
```
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:iam::308535385114:user/pytorch_ossci_artifact_bot_uploader is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:308535385114:function:rds-proxy because no identity-based policy allows the lambda:InvokeFunction action
Error: Process completed with exit code 1.
```

**Comment by janeyx99** [comment]
Resolved the permissions issue

**Comment by seemethere** [comment]
Follow up to this for context, I've gone ahead and submitted an [internal change](https://www.internalfb.com/diff/D36138154) to our managed IAM bot to add code to manage the permissions rds proxy
