### ISSUE TITLE
Exporting the operator amax to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by sunnyfree0402** [pytorch/pytorch#75167]
Call:
`torch.onnx.export(...)`
`x_max = torch.amax(x, dim=self.dim, keepdim=self.keepdim)`

Error:
`RuntimeError: Exporting the operator amax to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

**Comment by BowenBao** [comment]
Should be supported by #75268
