### ISSUE TITLE
[Libtorch C++] `torch::save` crash if the folder is not created

### ISSUE THREAD

**Issue by qouteall** [pytorch/pytorch#75177]
### 🐛 Describe the bug

example
```
int main(int argc, char* argv[]) {
    auto m = torch::nn::Linear(5, 5);
    torch::save(m, "./aaa/bbb.pt");
}
```
If the folder `aaa` does not exist then it will crash. The correct behavior should be logging error message or creating the folder.

### Versions

Libtorch 1.11.0 (for cuda 11.3)
MSVC2019

cc @ezyang @gchanan @zou3519 @jbschlosser @mruberry

**Comment by albanD** [comment]
Adding an error message sounds like the right way to fix this (note that we already have this in python).
We would accept a PR adding it for the c++ API code.

**Comment by vitrioil** [comment]
I can work on this.

@albanD I was just checking this. It throws this error:
```bash
terminate called after throwing an instance of 'c10::Error'
  what():  File ./aaa/bbb.pt cannot be opened.
```
Followed by a huge dump.

It comes from [inline_container.cc](https://github.com/pytorch/pytorch/blob/3001bda3042eaee01f2e8c4b7b28da74b3566065/caffe2/serialize/inline_container.cc#L341).

This change comes from here: #44266

This seems to be the desired behaviour to avoid double exception. If I comment this [line](https://github.com/pytorch/pytorch/blob/3001bda3042eaee01f2e8c4b7b28da74b3566065/caffe2/serialize/inline_container.cc#L341), it throws this error:
```bash
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:423] . PytorchStreamWriter failed writing file data/0: file write failed
```

Which is also not meaningful in the context of this issue. Maybe we need to add a parent directory check and inform the user about this by explicitly mentioning that parent directory doesn't exist.

Would this make sense to do or leave it as it is?

**Comment by albanD** [comment]
The original report is on Windows, it might be that error handling is not working as smoothly there.
If you have a simple place to add such a test if the folder exists, then that would be great!

**Comment by vitrioil** [comment]
Okay, I will create a PR to check if parent directory exists or not and throw an error in case it does not exist.

**Comment by vitrioil** [comment]
Created #75681
