### ISSUE TITLE
RuntimeError: falseINTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by Leoooo333** [pytorch/pytorch#75185]
### 🐛 Describe the bug

RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_621231_0> in read-write mode

### Versions

1.10.0+cu113

**Comment by ejguan** [comment]
This has been resolved by #https://github.com/pytorch/pytorch/pull/72232. Please try to use new pytorch release or nightly.
Feel free to re-open it if the problem persists.
