### ISSUE TITLE
tree_map doesn't work over return_types

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#75218]
### 🐛 Describe the bug

```
import torch
from torch.utils._pytree import tree_map

print(tree_map(lambda a: None, torch.cummin(torch.randn(3), 0)))
```

This prints `None`.  I expected to get `torch.return_types.cummin(values=None, indices=None)`

cc @zou3519 

### Versions

master

**Comment by zou3519** [comment]
We have a fix for this in functorch, we just need to upstream it to pytorch/pytorch
