### ISSUE TITLE
convolution forward-over-reverse mode AD fails for certain inputs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#75219]
### 🐛 Describe the bug

There are two problems:
1. There is most likely a bug in convolution's forward-over-reverse formula
2. PyTorch's forward-over-reverse testing is not sufficient (it did not catch this case from the OpInfo-generated test, but we caught it in functorch's tests)

## Problem 1: bug in convolution's forward-over-reverse formula

Repro:
```
import torch
import torch.nn.functional as F
import torch.autograd.forward_ad as fwAD

device = 'cpu'
input = torch.randn(2, 4, 6, 6, requires_grad=True, device=device)
weight = torch.randn(8, 1, 3, 3, requires_grad=True, device=device)
bias = None
kwargs = {'groups': 4}

output = F.conv2d(input, weight, bias, **kwargs)
grad_output = torch.randn_like(output)

with fwAD.dual_level():
  input_t = torch.randn_like(input)
  weight_t = torch.randn_like(weight)

  input_d = fwAD.make_dual(input, input_t)
  weight_d = fwAD.make_dual(weight, weight_t)

  output = F.conv2d(input_d, weight_d, bias, **kwargs)

  grad_output_d = fwAD.make_dual(grad_output, torch.randn_like(grad_output))

  result = torch.autograd.grad(output, [input, weight], grad_output_d)
  
```
results in `RuntimeError: Trying to set a forward gradient that has a different size than that of the original Tensor, this is not supported. Tensor is of size [] while the given forward gradient is of size [8].`

There is no error if the device is 'cuda'

## Problem 2: PyTorch's forward-over-reverse testing is not sufficient

I didn't dig into this very much. The above inputs came from the OpInfo for F.conv2d and we caught the failure in [functorch's test suite](https://github.com/pytorch/functorch/blob/a007c642131e68ed717128050f42a35dcacf51b0/test/test_ops.py#L1101). I expect PyTorch's test suite would be able to catch this error as a result but it does not.

### Versions

main

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
CUDA and cpu share the same forward AD formula  for convolution backward (which is relatively simple because it is is multi-linear), so if cuda succeeds but cpu fails, I'm suspecting something is going wrong with the convolution backward implementation

**Comment by soulitzer** [comment]
(1) The issue is that mkldnn's convolution backward does not respect the output_mask argument. Because None is passed in for bias, we expect an undefined tensor to be returned for grad_bias. Instead a scalar tensor is returned. I'm not sure what it would contain (possibly zeros), but it is of the wrong size.

(2) the reason it does not fail in core is that and we only go into the mkldnn path when the dtype is float (and not double).

To fix this, we can either see output_mask as more of a hint for optimization purposes (and just ignore the returned value) or something we should enforce by raise an error. We probably want forward AD codegen to be more robust against this regardless.

**Comment by zou3519** [comment]
> (1) The issue is that mkldnn's convolution backward does not respect the output_mask argument. Because None is passed in for bias, we expect an undefined tensor to be returned for grad_bias. Instead a scalar tensor is returned. I'm not sure what it would contain (possibly zeros), but it is of the wrong size.

This happens inside of convolution_backward, right? The spec of convolution_backward should be "if None is passed in for bias, then an undefined tensor must be returned".

I'd expect convolution_backward to call mkldnn's convolution backward -- we could have convolution_backward always return undefined tensor for grad_bias and ignore the return as a result.

> (2) the reason it does not fail in core is that we only go into the mkldnn path when the dtype is float (and not double).

We probably want to have tests (maybe slow tests?) for float dtype, otherwise, we'll never catch cases like this. The maximum/minimum bug is an example of another bug that only manifested with torch.float that we didn't catch because we were only testing torch.double.

**Comment by soulitzer** [comment]
> This happens inside of convolution_backward, right?

Yep

> I'd expect convolution_backward to call mkldnn's convolution backward -- we could have convolution_backward always return undefined tensor for grad_bias and ignore the return as a result.

Good idea, made a PR that just does the check at the end of convolution

> We probably want to have tests (maybe slow tests?) for float dtype, otherwise, we'll never catch cases like this. The https://github.com/pytorch/pytorch/pull/75277 is an example of another bug that only manifested with torch.float that we didn't catch because we were only testing torch.double.

That would make sense, though getting gradcheck to not be flaky might take a little experimentation

**Comment by zou3519** [comment]
> That would make sense, though getting gradcheck to not be flaky might take a little experimentation

It's probably "good enough" to set the tolerance at 1e-4 or something low like that. The goal of the testing is to (1) check the output values are roughly OK and (2) do a smoke test (e.g. check that the code doesn't raise an exception)

We could possibly also get away with just doing (2) (it would be a lot faster because we wouldn't need to compute an entire jacobian!) It depends on how confident we are that there are no correctness issues for float32.

**Comment by zou3519** [comment]
Did we fix this? @soulitzer
