### ISSUE TITLE
[Caffe2] compilation error on nccl with gcc8

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/pytorch#7523]
hi.I was compiling caffe2 and I ran into a problem. i ran the command below. you can see the results:

cmake -DCUDA_HOST_COMPILER=/usr/bin/gcc53 -DUSE_OPENMP=ON -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx -DCMAKE_DISABLE_FIND_PACKAGE_Eigen3=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_pybind11=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_CUB=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Gloo=TRUE -DUSE_NATIVE_ARCH=ON .. 

-- The CXX compiler identification is GNU 8.1.1
-- The C compiler identification is GNU 8.1.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64 - Success
-- Does not need to define long separately.
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Success
-- NUMA is available
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Success
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE
-- Performing Test COMPILER_SUPPORTS_MARCH_NATIVE - Success
-- Build type not set - defaulting to Release
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/shahriar/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- Found Git: /usr/bin/git (found version "2.17.0") 
-- The BLAS backend of choice:Eigen
-- Brace yourself, we are building NNPACK
-- The ASM compiler identification is GNU
-- Found assembler: /usr/lib64/ccache/cc
-- Found PythonInterp: /usr/bin/python (found version "2.7.14") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Caffe2: Cannot find gflags automatically. Using legacy find.
-- Found gflags: /usr/include  
-- Caffe2: Found gflags  (include: /usr/include, library: /usr/lib64/libgflags.so)
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Found glog: /usr/include  
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib64/libglog.so)
-- Failed to find LLVM FileCheck
-- git Version: v0.0.0-dirty
-- Version: 0.0.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found LMDB: /usr/include  
-- Found lmdb    (include: /usr/include, library: /usr/lib64/liblmdb.so)
-- Found LevelDB: /usr/include  
-- Found LevelDB (include: /usr/include, library: /usr/lib64/libleveldb.so)
-- Found Snappy: /usr/include  
-- Found Snappy  (include: /usr/include, library: /usr/lib64/libsnappy.so)
-- Found Numa: /usr/include  
-- Found Numa  (include: /usr/include, library: /usr/lib64/libnuma.so)
-- OpenCV found (/usr/lib64/OpenCV)
-- Did not find system Eigen. Using third party subdirectory.
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.14", minimum required is "2.7") 
-- Found NumPy: /usr/lib64/python2.7/site-packages/numpy/core/include (found version "1.14.3") 
-- NumPy ver. 1.14.3 found (include: /usr/lib64/python2.7/site-packages/numpy/core/include)
-- Found MPI_C: /usr/lib64/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib64/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI support found
-- MPI compile flags: -pthread
-- MPI include path: /usr/include/openmpi-x86_64
-- MPI LINK flags path: -Wl,-rpath -Wl,/usr/lib64/openmpi/lib -Wl,--enable-new-dtags -pthread
-- MPI libraries: /usr/lib64/openmpi/lib/libmpi_cxx.so/usr/lib64/openmpi/lib/libmpi.so
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Adding -fopenmp
-- Found CUDA: /usr (found suitable version "9.1", minimum required is "7.0") 
-- Found CUDNN: /usr/include/cuda  
-- Caffe2: CUDA detected: 9.1
-- Found cuDNN: v7.1.3  (include: /usr/include/cuda, library: /usr/lib64/libcudnn.so)
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 sm_70
-- Could NOT find NCCL (missing: NCCL_INCLUDE_DIRS NCCL_LIBRARIES) 
-- MPI include path: /usr/include/openmpi-x86_64
-- MPI libraries: /usr/lib64/openmpi/lib/libmpi_cxx.so/usr/lib64/openmpi/lib/libmpi.so
-- CUDA detected: 9.1
-- Found libcuda: /usr/lib64/libcuda.so
-- Found libnvrtc: /usr/lib64/libnvrtc.so
-- Found nccl: /home/shahriar/pytorch/third_party/nccl/build/include  
CMake Warning at cmake/Dependencies.cmake:490 (message):
  mobile opengl is only used in android or ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:109 (include)

CMake Warning at cmake/Dependencies.cmake:566 (message):
  Metal is only used in ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:109 (include)

-- GCC 8.1.1: Adding gcc and gcc_s libs to link line
-- Include NCCL operators
-- Excluding ideep operators as we are not using ideep
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- Include Observer library
-- Using lib/python2.7/site-packages as python relative installation path
-- Automatically generating missing __init__.py files.
CMake Warning at CMakeLists.txt:228 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.

-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.11.0
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.1.11-8176-g604f907bc-dirty
--   System                : Linux
--   C++ compiler          : /usr/lib64/ccache/c++
--   C++ compiler version  : 8.1.1
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -fopenmp -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.14
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ATEN              : OFF
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     CUDA version        : 9.1
--     CuDNN version       : 7.1.3
--     CUDA root directory : /usr
--     CUDA library        : /usr/lib64/libcuda.so
--     cudart library      : /usr/lib64/libcudart_static.a;-pthread;dl;/usr/lib64/librt.so
--     cublas library      : /usr/lib64/libcublas.so;/usr/lib64/libcublas_device.a
--     curand library      : /usr/lib64/libcurand.so
--     CuDNN library       : /usr/lib64/libcudnn.so
--     nvrtc               : /usr/lib64/libnvrtc.so
--     CUDA include path   : /usr/include/cuda
--     NVCC executable     : /usr/bin/nvcc
--     CUDA host compiler  : /usr/bin/gcc53
--     USE_TENSORRT        : OFF
--   USE_EIGEN_FOR_BLAS    : 1
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.20
--     Snappy version      : 1.1.7
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.22
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 3.4.1
--   USE_OPENMP            : ON
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shahriar/pytorch/build

then I ran the command below to compile and install and it ran into a compile problem:
sudo make install

Scanning dependencies of target nccl_external
[  0%] Creating directories for 'nccl_external'
[  0%] No download step for 'nccl_external'
[  0%] No patch step for 'nccl_external'
[  0%] No update step for 'nccl_external'
[  0%] No configure step for 'nccl_external'
[  0%] Performing build step for 'nccl_external'
Compiling src/libwrap.cu                      > /home/shahriar/pytorch/third_party/nccl/build/obj/libwrap.o
/usr/include/c++/8/type_traits(1061): error: type name is not allowed

/usr/include/c++/8/type_traits(1061): error: type name is not allowed

/usr/include/c++/8/type_traits(1061): error: identifier "__is_assignable" is undefined

/usr/include/c++/8/utility(311): error: pack expansion does not make use of any argument packs

4 errors detected in the compilation of "/tmp/tmpxft_00001145_00000000-12_libwrap.compute_70.cpp1.ii".
make[3]: *** [Makefile:138: /home/shahriar/pytorch/third_party/nccl/build/obj/libwrap.o] Error 1
make[2]: *** [CMakeFiles/nccl_external.dir/build.make:111: nccl_external-prefix/src/nccl_external-stamp/nccl_external-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/nccl_external.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

I am using fedora 28
I have compiled it before and it was fine. but when I upgraded from fedora 27 to 28 I ran into this problem.
I don't know if i'm right but I think that nccl can't be compiled with gcc 8. on fedora 27 i had gcc 7 and when I upgraded gcc 8 was installed.

**Comment by pjh5** [comment]
NCCL has been known to have incompatibilities with certain gcc versions in the past. This seems like an issue for Nvidia instead of us.

I recommend downloading pre-built NCCL from Nvidia to see if you can avoid building it yourself, or in turning NCCL off. You can try specifying an older comiler, but that may cause other issues.

**Comment by ShahriarSS** [comment]
it looks like nccl1 is not supported anymore by nvidia and has been replaced. I was actually able to build caffe2 by compiling gcc 7 and compiling caffe with gcc 7 and then compiling the projects that I use caffe in with gcc 8. if I turn nccl off what feature would I loose?

**Comment by pjh5** [comment]
You can find more info about NCCL here https://developer.nvidia.com/nccl . Having NCCL will provide some optimized implementations of certain operations for free, and provide additional implementations of other operations. It is optional though, and if you don't know that you need it then you probably don't need it.

**Comment by ShahriarSS** [comment]
Thank you for your help. I on't know if this issue should be close  or not. I was able to compile with gcc 7 but the original issue remains.

**Comment by pjh5** [comment]
I will close this. I think this is something that Nvidia would need to fix on their side.
