### ISSUE TITLE
[RFC] Add ability to ignore parameters / modules in FSDP

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#75255]
### 🚀 The feature, motivation and pitch

Sometimes, FSDP wraps models with components such as model parallelism modules, and users would like to ignore these parameters / modules when wrapping their overall model with FSDP.

This is similar to DDP which offers the following API to do so: https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/distributed.py#L1698

In order to implement this in FSDP, we can do the following:

1. Add an argument `params_to_ignore` or `modules_to_ignore` which will specify the modules that should _not_ be wrapped in FSDP at all, to ensure that these parameters / modules will not be sharded at all. 
2. Implement this by skipping these parameters when constructing FlatParameter: https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/fully_sharded_data_parallel.py#L343
3. Bypass these parameters explicitly during state_dict / load_state_dict pre and post processing.

As a result, FSDP will not be aware of these parameters.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by awgu** [comment]
In my understanding, there are two approaches, broadly:
1. `module._modules -= modules_to_ignore`, where `module` is the first `FSDP` ctor arg
    - Pros: Additional logic scales constantly (i.e. `O(1)`) in the API surface -- the modules in `modules_to_ignore` truly do not exist in the view of `module`
    - Cons: Without other saved references to the ignored modules, the user may lose access to those modules
2. Check every usage of `torch.nn.Module.named_parameters()`, `parameters()`, `named_modules()`, and `modules()` to ensure that no parameter from a module in `modules_to_ignore` is properly ignored
    - Pros: Avoids depending on PyTorch Core's `nn.Module` implementation
    - Cons: Additional logic scales super-constantly (i.e. `\omega(1)`) in the API surface -- any future features will need to account for `modules_to_ignore`

It seems like the second approach is preferred.

**Comment by rohan-varma** [comment]
Discussed offline, approach (2) seems better, though we should not eliminate these ignored modules from state_dict.

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/75431
