### ISSUE TITLE
`torch.multiprocessing` does not propagate global PyTorch options when `forkserver` is used

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [pytorch/pytorch#75269]
### 🐛 Describe the bug

`torch.multiprocessing` does not propagate global state like the default dtype to worker processes when using the `forkserver` start method:

```python
import torch
from torch import multiprocessing as mp


def func(i):
    print(f"{i}: {torch.get_default_dtype()}")


if __name__ == "__main__":
    torch.set_default_dtype(torch.float64)
    ctx = mp.get_context("forkserver")
    with ctx.Pool() as p:
        p.map(func, range(3))

    print("done")
```
gives
```
$ python torch-mp.py 
0: torch.float32
1: torch.float32
2: torch.float32
done
```
on 1.11 and 1.10. If you change it to `fork`, all of them print `float64`. This leads to dtype errors when the tensors are brought back to the parent process.

Since switching to `forkserver` (necessary for CUDA, and in my experience also on many systems where `fork` leads to hangs because of some kind of OpenMP issue) should not have this problem...

Is there a way to load/restore PyTorch's global settings? Obviously I can manually pass the default dtype to the worker process, but ideally I'd like to use something more general and forward compatible.

### Versions

PT 1.10, 1.11
CUDA
Ubuntu

cc @VitalyFedyunin

**Comment by ppwwyyxx** [comment]
This is expected behavior from python docs: https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

> The spawn and forkserver start methods
Global variables
Bear in mind that if code run in a child process tries to access a global variable, then the value it sees (if any) may not be the same as the value in the parent process at the time that [Process.start](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.start) was called.

**Comment by Linux-cpp-lisp** [comment]
True @ppwwyyxx --- I think it might be helpful to future users to who encounter this to explicitly note that this applies also the global state of PyTorch itself (maybe not expected) in addition to arbitrary user-defined Python globals (expected).

If you do work in multiple processes this can get pretty subtle with silent issues around `allow_tf32`, `set_device`, `set_default_dtype`, etc. PyTorch's behavior to not propagate any of this is fine, but could maybe be explicitly documented?
