### ISSUE TITLE
normal_ with generator produces different results if input is noncontiguous

### ISSUE THREAD

**Issue by samdow** [pytorch/pytorch#75281]
### 🐛 Describe the bug

Calling in-place normal when the input is a view produces a different value, even when using generators. As a note, this works as expected if `y` is just a slice but incorrectly if it's transposed like in this example
 
```python
import torch

x = torch.empty(4, 5)
y = torch.empty(5, 4)

generator = torch.Generator()
orig_state = generator.get_state()

x.normal_(generator=generator)

y = y.transpose(0, 1)
generator = generator.set_state(orig_state)
y.normal_(generator=generator)
assert torch.allclose(x, y)  # fails
```

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.2.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.20.2
Libc version: N/A

Python version: 3.9.1 (default, Dec 11 2020, 06:28:49)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] botorch==0.3.3
[pip3] flowtorch==0.0.dev2
[pip3] functorch==0.1.0
[pip3] gpytorch==1.3.1
[pip3] numpy==1.20.1
[pip3] torch==1.11.0
[pip3] torchvision==0.10.1
[conda] blas                      1.0                         mkl  
[conda] botorch                   0.3.3                         0    pytorch
[conda] flowtorch                 0.0.dev2                 pypi_0    pypi
[conda] functorch                 0.1.0                    pypi_0    pypi
[conda] gpytorch                  1.3.1              pyhd8ed1ab_0    conda-forge
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] mkl                       2020.4             h08c4f10_301    conda-forge
[conda] numpy                     1.20.1           py39h3c955ea_0    conda-forge
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchvision               0.10.1                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @pbelevich

**Comment by bdhirsh** [comment]
marking hi-pri since it looks like a silent correctness issue

**Comment by ngimel** [comment]
This is expected behavior, see #71090
