### ISSUE TITLE
[RFC] Consolidated and unified state_dict and load_state_dict hooks

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#75287]
### 🚀 The feature, motivation and pitch

Today, PyTorch offers a few private hooks for `state_dict` and `load_state_dict` that exist to allow users to run post and pre processing respectively when saving and loading model checkpoints.

Current state_dict post hook: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L1265
Current state_dict pre hook: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L1408

This proposal seeks to:
1) Propose 2 new hooks so that state_dict and load_state_dict both have pre and post hooks
2) Aim to consolidate all of the 4 hooks and make their semantics consistent
3) Provide a vision where all 4 new APIs are public and can be used by PyTorch users in a stable fashion.

#### Current State
1) `_register_state_dict_hook` allows registration of a `Callable[self, state_dict, prefix, local_metadata] -> Optional[Dict[str, Tensor]]` and is run after the state_dict of self (and all of its children) is processed. It can modify `state_dict` and optionally return a new one.
2) `_register_load_state_dict_pre_hook` allows registration of a `Callable[state_dict, prefix, local_metadatra, missing_keys, unexpected_keys, error_msgs]` or a `Callable[self, state_dict, prefix, local_metadatra, missing_keys, unexpected_keys, error_msgs] if with_module=True]`, and is run before loading state dict into self (and all of its children).

#### Proposed State

Revamped existing APIs:
1) `register_state_dict_post_hook` -> Same as (1) above, but we've renamed it to clearly indicate this is a post hook. This is a bit inconsistent with nn.Module register_hook semantics, but arguably more clear and will be consistent with state_dict hook APIs, which should be enough for consistency. This hook will behave in the same way it currently does.
2) `register_load_state_dict_pre_hook` -> Same as (2) above, but we will remove `with_module` argument and always provide the `self` module into the API. Users can simply ignore this module in their function if needed. EDIT (@janeyx99): We should also allow the hook to optionally return a new state_dict, if desired, as it will cover the use case where one may want to completely change up the state_dict. Relevant PR https://github.com/pytorch/pytorch/pull/105953 where we have this for the optimizer.

New APIs:

1) `register_state_dict_pre_hook: Callable[self, prefix] -> None` which is a state_dict() pre hook that will be run before the state_dict is computed for self (and all of its children). We do not pass in the `destination` argument is it is deprecated into this hook.
2) `register_load_state_dict_post_hook: Callable[self] -> None` which is a `load_state_dict()` post hook that runs after state dict is loaded into self module _and_ all of its children. Note that this is consistent with the rest of the APIs - hooks are called either before or after self computation and all children computation has taken place, never in between. Another proposal is that the hook can be a `Callable[self, NamedTuple] -> NamedTuple` where the `NamedTuple` contains the `missing_keys` and `unexpected_keys` that was returned by load_state_dict, and the user can do some optional processing / addition / removal and return a new `NamedTuple`. Although, we are not aware of any use case requiring that at the moment, so suggesting to keep it simple for now.
Similar to https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L1389, we should offer a `_register_load_state_dict_post_hook` that is called after `load_state_dict` for a particular `nn.Module` is completed.

The goal is to have this hook called even for modules that aren't at the top level during load_state_dict; and this hook should be called after self module is loaded as well as all of self's children.

In addition, similar to `load_state_dict`'s existing pre-hook, state_dict should also offer a pre-hook for any module-specific preprocessing that modules may want to run before calling into `state_dict`.  This can be invoked before the call to `self._state_dict_impl`. API to register this could be `_register_state_dict_pre_hook`. Unfortunately, the current state_dict hook is a post hook but is named `_register_state_dict_hook` which is a bit unclear as to whether it is a pre/post hook. Since the API is private, we could consider refactoring `_register_state_dict_hook` to `_register_state_dict_post_hook`.

#### Plan moving forward
Since these are all public facing APIs, we can add them in addition to the old existing hooks and keep the old ones for legacy reasons and add deprecated warnings.

#### Motivating use case:
- FullyShardedDataParallel in particular needs `register_load_state_dict_post_hook` and `register_load_state_dict_pre_hook` to enter/exit the full parameter summoning context. We don't want to do this in `load_state_dict` itself since `load_state_dict` is not overridable (it won't be called for submodules). Draft PR: 

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @kshitij12345 @saketh-are

**Comment by albanD** [comment]
Thanks for writing this down in details!
I think this is very reasonable, some small details:
- The typing for state dict is in a pretty bad state. But I think it should become `Dict[str, Any]` for state_dict and `Mapping[str, Any]` for the load part. See https://github.com/pytorch/pytorch/pull/73483 that is making this more consistent for the rest of the functions.
- "We could also consider adding a simple Callable[self] -> None to begin with and add additional arguments as kwargs in a backwards-compatible way." This is not really possible to do this in a BC way without having a boolean flag that says if you should pass this new argument or not (see today _register_load_state_dict_pre_hook for an example). So I think we should forward all the information we have to the hook to begin with. In this case, I think we want to take both the keep_vars and prefix args here.
- The named tuple proposal sounds great actually for `register_load_state_dict_post_hook `, it would solve https://github.com/pytorch/pytorch/issues/40859 no?

**Comment by rohan-varma** [comment]
@albanD Thanks for your comments!

Regarding `register_post_load_state_dict_hook`, we can go ahead with it being a `Callable[self, NamedTuple] -> NamedTuple` to begin with. It's a good point that these are not regular functions but registrations of functions, so we cannot easily do this in a BC way without having an argument as you mentioned.

Re: https://github.com/pytorch/pytorch/issues/40859, I'll have to take some more time to fully read through the discussion and understand the issue being discussed.

**Comment by jbschlosser** [comment]
> The named tuple proposal sounds great actually for register_load_state_dict_post_hook , it would solve https://github.com/pytorch/pytorch/issues/40859 no?

I don't think it's quite enough to solve that issue. IIUC a weight with mismatched shape would not have an unexpected or missing key, but rather an error_msg would be appended:
https://github.com/pytorch/pytorch/blob/3326fa60ccfb7c717ecfacbb2a216544561f08d2/torch/nn/modules/module.py#L1488-L1493

We could pass `mismatched_keys` to the hook as well, but this might be a bit strange since `load_state_dict()` only returns unexpected / missing keys.

**Comment by jbschlosser** [comment]
Someone just complained about the usage of `_register_load_state_dict_pre_hook()` maintaining an owning reference to the module and preventing it from being deleted: #76434. Might be relevant to the design or implementation.

**Comment by albanD** [comment]
cc @rohan-varma this can be closed now?

**Comment by d4l3k** [comment]
@rohan-varma I have a use case for _register_load_state_dict_pre_hook but it's currently not a public method. Are there plans to make it public/provide it as a stable API?

For the time being we can rely on the private method but I'm worried about API stability for future PyTorch releases

It looks like a number of notable projects (from Apple, NVIDIA, lightning) are depending on it so would be good to stabilize it. https://cs.github.com/?scopeName=All+repos&scope=&q=._register_load_state_dict_pre_hook%28

**Comment by MaigoAkisame** [comment]
Hi, I would like to suggest adding a `prefix` argument to `load_state_dict_post_hook` functions.

I have a use case where I would like to ignore some deprecated keys when loading a state_dict.

Currently the only public method to register a hook is `register_load_state_dict_post_hook`. The hook takes an `incompatible_keys` argument, so it can remove the deprecated keys from `incompatible_keys.unexpected_keys`.

However, one inconvenience is that in `incompatible_keys.unexpected_keys`, the keys come with prefixes. I need to check the last part of each key against the deprecated keys to determine whether to remove the key:
```
def load_state_dict_post_hook(module, incompatible_keys):
    deprecated_keys = {"foo", "bar"}
    incompatible_keys.unexpected_keys[:] = [
        key for key in incompatible_keys.unexpected_keys
        if key.split(".")[-1] not in deprecated_keys
    ]
```

And this is actually not just an inconvenience; it may even cause subtle bugs.
Suppose my module is called `X` in a larger module. While `X.foo` should be removed from `incompatible_keys.unexpected_keys`, we shouldn't remove `Y.foo`, if Y is another sub-module in the larger module.
However, the hook has no knowledge that the current module is called `X`, and it will remove `Y.foo` as well.

If the hook accepted an additional argument called `prefix`, we would be able to remove `X.foo` precisely, without affecting `Y.foo`:
```
def load_state_dict_post_hook(module, incompatible_keys, prefix):
    deprecated_keys = {"foo", "bar"}
    for key in deprecated_keys:
        if prefix + key in incompatible_keys.unexpected_keys:
            incompatible_keys.unexpected_keys.remove(prefix + key)
```

I'm not sure if it is still possible to add a `prefix` argument, since the `register_load_state_dict_post_hook` method is already public.

---

Actually, it would be much more convenient if the method `_register_load_state_dict_pre_hook` or `_load_from_state_dict` was made public.
Both pre-hook functions and `_load_from_state_dict` already take `prefix` as an input argument.
By registering a pre-hook or overriding `_load_from_state_dict`, I can easily delete the deprecated keys from the `state_dict`, e.g.
```
def _load_from_state_dict(self, state_dict, prefix, ...):
    deprecated_keys = {"foo", "bar"}
    for key in deprecated_keys:
        if prefix + key in state_dict:
            del state_dict[prefix + key]
```

**Comment by albanD** [comment]
> Actually, it would be much more convenient if the method _register_load_state_dict_pre_hook or _load_from_state_dict were made public.

Unfortunately it is tricky to do that as different people override this in different places.


> Hi, I would like to suggest adding a prefix argument to load_state_dict_post_hook functions.

That is a great point, this is most likely an oversight on our end.
I'm afraid this hook is already used today quite a bit from a github search so we won't be able to break it. We can add a `with_prefix=False` kwarg to the register function though to allow the user to allow users to opt-in into it without this change being BC-breaking. This will be similar to the with_kwargs on the forward pre hooks that we have today.

**Comment by MaigoAkisame** [comment]
Thanks for the reply! I'd love to see the `register_load_state_dict_post_hook` function with the argument `with_prefix`.

For the time being, do you think it's OK if I override `_load_from_state_dict`?
I'd like to do this in fairseq. It seems people are already overriding `_load_from_state_dict` in many repos, including fairseq:
https://github.com/search?q=super()._load_from_state_dict&type=code
https://github.com/search?q=repo%3Afacebookresearch%2Ffairseq%20super()._load_from_state_dict&type=code

**Comment by albanD** [comment]
It's not great as it prevents us from changing this function (like adding new args to it to make it more versatile).
Hopefully adding the `with_prefix` should be a small impl + test in case you have time to send that!

**Comment by MaigoAkisame** [comment]
I'm afraid I don't have the time right now -- I'm sprinting toward a deadline, and just realized that I needed to update a module in fairseq to unblock.

**Comment by albanD** [comment]
Much better, thanks!

**Comment by rohan-varma** [comment]
agree we should formalize the private load_state_dict_pre_hook as register_load_state_dict_pre_hook with the constraints as described in (2).

**Comment by janeyx99** [comment]
Just updated the toplevel comment to keep things consolidated, but wanted to propose that the load_state_dict_pre_hook should also allow users to optionally return their own state_dict to be used for loading. This is following some discussion in https://github.com/pytorch/pytorch/pull/105953 with @albanD
