### ISSUE TITLE
[caffe2] C2 ONNX build is flaky due to lack of ordering dep

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7528]
When it fails it looks like this:

```
02:41:21 [ 53%] Running C++ protocol buffer compiler on /var/lib/jenkins/workspace/build/third_party/onnx/onnx/onnx-operators_ONNX_NAMESPACE_FOR_C2_CI.proto
02:41:21 onnx_ONNX_NAMESPACE_FOR_C2_CI.proto: File not found.
02:41:21 onnx-operators_ONNX_NAMESPACE_FOR_C2_CI.proto: Import "onnx_ONNX_NAMESPACE_FOR_C2_CI.proto" was not found or had errors.
02:41:21 onnx-operators_ONNX_NAMESPACE_FOR_C2_CI.proto:64:12: "NodeProto" is not defined.
02:41:21 third_party/onnx/CMakeFiles/onnx_proto.dir/build.make:68: recipe for target 'third_party/onnx/onnx/onnx-operators_ONNX_NAMESPACE_FOR_C2_CI.pb.cc' failed
```

This indicates we're trying to run the proto compiler before the proto file is created. This probably means there should be some dep declared which we didn't. It's intermittent because sometimes we're lucky and the build gets ordered the right way.

Maybe this should get reported to onnx repo.

CC @houseroad @bddppq @anderspapitto 

Cases of this failing:
- https://github.com/pytorch/pytorch/pull/7465
- https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-mkl-ubuntu16.04-build/4286//console

**Comment by bddppq** [comment]
This is being fixed https://github.com/onnx/onnx/pull/934

**Comment by ezyang** [comment]
OK closing as an upstream issue.
