### ISSUE TITLE
view(-1)

### ISSUE THREAD

**Issue by KimmoOjala** [pytorch/pytorch#7531]
I installed the source version of pytorch from github (0.5.0a0+580556d) and I noticed that view(-1) doesn't always flatten a tensor. It seems to work on and off. A could not really deduce a pattern when it does work and when it doesn't. 

Update: calling contiguous() seems to have solved the problem. I think you can close this issue.

**Comment by goldsborough** [comment]
I believe the docs explain in detail when `.contingous()` must be called before invoking `.view()`: https://pytorch.org/docs/stable/tensors.html#torch.Tensor.view

**Comment by fmassa** [comment]
Also, note that you can always call `tensor.reshape(-1)`, even on non-contiguous tensors.

**Comment by KimmoOjala** [comment]
Thanks for the tips!
