### ISSUE TITLE
[feature request] torch.diff with n=2

### ISSUE THREAD

**Issue by florian98765** [pytorch/pytorch#75319]
Hi everybody, 
we are using pytorch to solve partial differential equations like to Laplace equation.
using `torch.diff` with `n=2` would allow to directly create get a finite difference version of the Laplace operator.

pytorch currently reports:
```
RuntimeError: diff only supports n = 1 currently. Please file an issue at https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=feature-request.md if your use case requires supporting higher-order differences
```
So, here is the feature request. 

By the way, appending / prepending zeros is a nice way to define homogeneous boundary conditions. Allowing a single float value, alternatively to a full inhomogeneous Tensor would be a useful feature.

thanks and best wishes
Florian

**Comment by lezcano** [comment]
Added in https://github.com/pytorch/pytorch/pull/67260
