### ISSUE TITLE
PyTorch Profiler typo. collecton -> collection

### ISSUE THREAD

**Issue by wassimseif** [pytorch/pytorch#75321]
### 📚 The doc issue

In the overview section of https://pytorch.org/docs/stable/profiler.html#torch-profiler

PyTorch Profiler is a tool that allows the ~~collecton~~ collection of the performance.

I can do the PR for this.

Is this the right file to edit ?https://github.com/pytorch/pytorch/blob/d4f831349756f3739ef69f82a15c86fc677f3eeb/torch/profiler/__init__.py

**Comment by soulitzer** [comment]
Hey thanks for the catch, we typically don't accept fixes small typos like this though due to the developer/machine overhead it takes to land PRs however.
