### ISSUE TITLE
Dictionary input parameter gets interpreted as multiple parameters during pytorch onnx conversion

### ISSUE THREAD

**Issue by miayu79** [pytorch/pytorch#75356]
### 🐛 Describe the bug

model signature: model(input_ids_1, input_ids_2, valid_length_1, valid_length_2, x = None, y = False, z = None, dict=None)
code to convert:
optional_input = {"dict":dict_values}
dummy_input = (input_ids_1, input_ids_2, valid_length_1, valid_length_2, optional_input)
torch.onnx.export(model, dummy_input, model_onnx_path, opset_version=14, input_names=["input_ids_1", "input_ids_2", "valid_length_1", "valid_length_2", "dict"], output_names=["output"])

Issue:  When inferencing on onnx model, it expect me to give > 5 inputs, all the key value pair in the dictionary are interpreted as extra parameters.
For example:
if dict = {
"xx": ***,
"yy": ***,
"zz": ***
} 

the exported onnx model expect the inputs to be ("input_ids_1", "input_ids_2", "valid_length_1", "valid_length_2", "xx", "yy", "zz") instead of ("input_ids_1", "input_ids_2", "valid_length_1", "valid_length_2", "dict")

### Versions

14

**Comment by janarez** [comment]
Hi, from the documentation at https://pytorch.org/docs/stable/onnx.html:

> If a dictionary is the last element of the args tuple, it will be interpreted as containing named arguments. In order to pass a dict as the last non-keyword arg, provide an empty dict as the last element of the args tuple.
