### ISSUE TITLE
torch.pow() return `nan` for negative values with float exponent

### ISSUE THREAD

**Issue by shahad-mahmud** [pytorch/pytorch#75405]
### 🐛 Describe the bug

If `a` is a tensor, then any operation like `a ** 2.2` or `torch.pow(a, 2.2)` return `nan` for negative values in the tensor `a`.

```
import torch

a = torch.tensor([1.2, 3.2, 4, -4, -3.3])
print('With **:', a ** 2.2)
print('With torch.pow():', torch.pow(a, 2.2))
```

This results into:
```
With **: tensor([ 1.4935, 12.9220, 21.1121,     nan,     nan])
With torch.pow(): tensor([ 1.4935, 12.9220, 21.1121,     nan,     nan])
```

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 3.12.3
Libc version: glibc-2.17

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.24.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 3090
GPU 1: GeForce RTX 3090

Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.0
[pip3] torch==1.11.0+cu113
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0+cu113
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.12.0+cu113
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] pytorch-lightning         1.6.0                    pypi_0    pypi
[conda] torch                     1.11.0+cu113             pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                0.11.0+cu113             pypi_0    pypi
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.12.0+cu113             pypi_0    pypi

**Comment by SsnL** [comment]
isn't it expected since it is generally not defined?

**Comment by apoorvjha** [comment]
By leveraging complex number representation of the negative numbers you can get around this issue. Please refer to attached screenshot. 
![image](https://user-images.githubusercontent.com/56272803/162144147-239a5c27-5664-4064-ad33-2503fe779da3.png)

**Comment by shahad-mahmud** [comment]
Got it. Thank you for the explanation :)
