### ISSUE TITLE
[shard] make sharded_tensor.cpu() a `__torch_function__` op instead

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#75402]
### 🚀 The feature, motivation and pitch

as titled, https://github.com/pytorch/pytorch/pull/74941 we are making it a class method, where it should be a torch function op instead.

cc @hameerabbasi @rgommers @peterbell10

**Comment by pritamdamania87** [comment]
@wanchaol Was wondering if this can actually be done via `__torch_function__` since ShardedTensor `cpu` method is slightly different and needs a `process_group` parameter as well which doesn't exist in the torch.Tensor version.

**Comment by wanchaol** [comment]
> @wanchaol Was wondering if this can actually be done via `__torch_function__` since ShardedTensor `cpu` method is slightly different and needs a `process_group` parameter as well which doesn't exist in the torch.Tensor version.

Yeah make sense to me, this is gonna be different from the torch ops where we probably shouldn't lower this to `torch_function` bc of `process_group`. Let's close this issue then.
