### ISSUE TITLE
DISABLED test_readall (test_zipfile.ZipfileTest)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#75406]
Platforms: mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_readall%2C%20test_zipfile.ZipfileTest)).

cc @malfet @albanD

**Comment by suo** [comment]
@PaliC please take a look

**Comment by albanD** [comment]
Note that we can't see the error log anymore.
Also does this test still exist @suo? I can't find it locally.
