### ISSUE TITLE
[Bug] Dilated max-pooling fails due to padding check

### ISSUE THREAD

**Issue by ShayanPersonal** [pytorch/pytorch#7541]
## Issue description
Dilated max-pooling should work even when the amount of padding is greater than half the kernel size, because dilation imitates larger kernels and there shouldn't be any risk of the -inf issue discussed in #3298. 

## Code example

>>> import torch
>>> pool = torch.nn.MaxPool2d(kernel_size=3, stride=2, padding=2, dilation=10)
>>> x = torch.Tensor(1, 1, 1000, 1000)
>>> pool(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/m/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/m/anaconda3/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 142, in forward
    self.return_indices)
  File "/home/m/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 360, in max_pool2d
    ret = torch._C._nn.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: invalid argument 2: pad should be smaller than half of kernel size, but got padW = 2, padH = 2, kW = 3, kH = 3 at /opt/conda/conda-bld/pytorch_1524590031827/work/aten/src/THNN/generic/SpatialDilatedMaxPooling.c:35

## System Info
Pytorch 0.4 installed with conda on Ubuntu 18.04.

**Comment by yqsony** [comment]
Running into the same issue. Pytorch 1.7 installed with conda on Ubuntu 18.04
x2 = F.max_pool2d(x1, kernel_size=(7,7), stride=(1,1), padding=(56,56), dilation=(14,14))
*** RuntimeError: pad should be smaller than half of kernel size, but got padW = 56, padH = 56, kW = 7, kH = 7

**Comment by richard-vogl** [comment]
running into same issue with dilation 3:
`RuntimeError: pad should be smaller than half of kernel size, but got padW = 0, padH = 3, kW = 3, kH = 3`

**Comment by xingyuuchen** [comment]
Why does this issue still exists.....

The limit padding size should be obviously half of `kernel_size * dilation`........

**Comment by daquexian** [comment]
> The limit padding size should be obviously half of kernel_size * dilation........

It should not be half of `kernel_size * dilation` but half of `1 + (kernel_size - 1) * dilation`
