### ISSUE TITLE
ONNX export of torch.minimum

### ISSUE THREAD

**Issue by codgeek** [pytorch/pytorch#75428]
### 🐛 Describe the bug

 Pytorch operator `minimum` cannot be converted to onnx.  Actually the corresponding operator is `Less`, a simple OP that return the smaller element in 2 tensor.  
[pytorch minimum](https://pytorch.org/docs/stable/generated/torch.minimum.html#torch.minimum)
[onnx less](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Less)

`RuntimeError: Exporting the operator minimum to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

```
import torch.onnx
import torch.nn as nn

class test_torch(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        x= torch.minimum(x, x)
        return x

net = test_torch()
test_input = torch.randn(1, 2, 224, 224) 
torch.onnx.export(net.to('cpu'), test_input,'convnet.onnx')

```

the error trace is:
```
Traceback (most recent call last):
  File "pytorch_to_onnx.py", line 18, in <module>
    torch.onnx.export(net.to('cpu'), test_input,'convnet.onnx')
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "~miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    module=module)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "~/miniconda3/envs/tf1.15/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)

RuntimeError: Exporting the operator minimum to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.19.3
Libc version: N/A

Python version: 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.10.2
[pip3] torchvision==0.11.3
[conda] _tflow_select             2.3.0                       mkl    defaults
[conda] mkl                       2019.4                      233    defaults
[conda] mkl-service               2.3.0            py36h9ed2024_0    defaults
[conda] nomkl                     3.0                           0    defaults
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] numpy-base                1.19.2           py36h68fea81_0    defaults
[conda] tensorflow                1.15.0          mkl_py36h975b573_0    defaults
[conda] tensorflow-base           1.15.0          mkl_py36h032239d_0    defaults
[conda] torch                     1.10.2                   pypi_0    pypi
[conda] torchvision               0.11.3                   pypi_0    pypi

**Comment by fatcat-z** [comment]
The returned results of ONNX::Less op is different than aten::minimum, actually ONNX::Min is the correct one.

This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1742314.

**Comment by codgeek** [comment]
hope to solve and merge recently!

**Comment by fatcat-z** [comment]
> hope to solve and merge in a few days!

Actually, https://github.com/pytorch/pytorch/pull/72090 has resolved this issue so if you try a nightly build, it will work for you.

**Comment by fatcat-z** [comment]
Closing it.  Feel free to open a new one if the issue still exists.
