### ISSUE TITLE
[feature request] Support pow in JIT compiler

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#7542]
Hi, I'm trying out the JIT compiler on my model, and find that Pow is not supported yet.
The following simple sample code:
```python
import torch

@torch.jit.script
def f(x):
    return x ** 1.7
```
generates the following error:
```
torch.jit.frontend.NotSupportedError: unsupported binary operator: Pow
@torch.jit.script
def f(x):
    return x ** 1.7
            ~~~~ <--- HERE
```
Is there a plan to supported this recently? If not, is it contribute welcome?

**Comment by apaszke** [comment]
We do want the pow for sure, and it should be fairly simple to add. Feel free to send a PR, or we'll have this fixed sometime soon.

**Comment by zasdfgbnm** [comment]
@jamesr66a Feel free to do this if you want!
