### ISSUE TITLE
Can't save a model with `torch.save` if model has a `torch.Device` attr

### ISSUE THREAD

**Issue by qlwang25** [pytorch/pytorch#7545]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
`File "/home/wangqianlong/MODELS/sentence_express_model/src/sst_main.py", line 393, in main
    train(train_data_set, test_data_set, parameters)
  File "/home/wangqianlong/MODELS/sentence_express_model/src/sst_main.py", line 283, in train
    save_model(model, epoch, loss, e_acc, parameters.model_dir)
  File "/home/wangqianlong/MODELS/sentence_express_model/src/utils.py", line 109, in save_model
    torch.save(model, fp)
  File "/home/wangqianlong/.local/lib/python3.6/site-packages/torch/serialization.py", line 161, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/wangqianlong/.local/lib/python3.6/site-packages/torch/serialization.py", line 118, in _with_file_like
    return body(f)
  File "/home/wangqianlong/.local/lib/python3.6/site-packages/torch/serialization.py", line 161, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/wangqianlong/.local/lib/python3.6/site-packages/torch/serialization.py", line 232, in _save
    pickler.dump(obj)
TypeError: can't pickle torch.Device objects
class RaceModel(nn.Module):
    def __init__(self, parameter):
        super(RaceModel, self).__init__()
        self.cuda_device = parameter.device
        self.A = Model(parameter)
        self.B = Model(parameter)
`

model = RaceModel(parameters).to(parameters.device)

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:0.4
- Python version:3.5
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
Here is a minimal example demonstrating the problem.
```
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.param = nn.Parameter(torch.Tensor(3, 5))
        self.device = torch.device('cpu:0')

net = Net()
torch.save(net.state_dict(), "net.pth")  # OK
torch.save(net, "net2.pth")              # errors out
```

**Comment by SsnL** [comment]
The real problem is that how to make `device` objects serializable.

**Comment by zou3519** [comment]
We can add  __getstate__ and __setstate__ attributes

**Comment by qlwang25** [comment]
thanks you, solve this problem @zou3519

**Comment by apaszke** [comment]
Fixed in #7713

**Comment by eustomaqua** [comment]
> Here is a minimal example demonstrating the problem.
> 
> ```
> import torch
> import torch.nn as nn
> 
> class Net(nn.Module):
>     def __init__(self):
>         super(Net, self).__init__()
>         self.param = nn.Parameter(torch.Tensor(3, 5))
>         self.device = torch.device('cpu:0')
> 
> net = Net()
> torch.save(net.state_dict(), "net.pth")  # OK
> torch.save(net, "net2.pth")              # errors out
> ```

Hi, I used exactly the "torch.save(net.state_dict())" and failed, my codes is like this
```python
>>> torch.save(net.state_dict(), "./4att/bestmodel.pth")
>>> # torch.save(net.state_dict(), "/home/usersname/yourmodel/4att/bestmodel.path")  # will raise the same error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/username/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/username/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
NotADirectoryError: [Errno 20] Not a directory: '/home/username/yourmodel/4att/bestmodel.pth'
```
Could you please tell me what is wrong with this? Thanks

**Comment by leeqiaogithub** [comment]
I still encounter similar problems. How do you solve them
