### ISSUE TITLE
Strict torch.jit.script fusion mode

### ISSUE THREAD

**Issue by cpuhrsch** [pytorch/pytorch#75464]
### 🚀 The feature, motivation and pitch

Not easily knowing when something is fused has bitten the e3nn team quite a bit I think. Turns out control flow prevented all their [ridiculously fuseable code](https://github.com/e3nn/e3nn/blob/main/e3nn/o3/_spherical_harmonics.py#L184-L456) from being fully optimized. [Removing control flow](https://gist.github.com/cpuhrsch/71ff55435c480ff03f399006bfa4c602) shows significant increase in perf (4x to 7x).

Another example is a recent feature request https://github.com/pytorch/pytorch/issues/75251 . The fusers (both nnc(assume this is default) and nvfuser) makes it trivial to try this implementation and gives much better performance, but I don't know whether they actually fully fused the code. In particular, when I replaced `square` with `pow(x, 2)` I [got a significant speedup](https://gist.github.com/cpuhrsch/e5ce5a91c60aec01d939da6c36f16e1e).

Can we have a context in which a call to torch.jit.script fails if it wasn't able to entirely fuse it?

Example
```
with torch.jit.fuser("fuser2", force_fusion=True):
    fused_op = torch.jit.script(op)
```

### Alternatives

There are options to inspect whether a fusion succeeded or not via environment variable, inspecting the result of torch.jit.script, etc. However, this seems pretty difficult for most users to give us good feedback on whether it worked on their case and open issues if it didn't. Surely we'd want to know when fusion failed to collect snippets or user requests.

**Comment by eellison** [comment]
Does this need to work with autodiff as well ? What is the expected behavior with respect to non-fusable ops like matmul, as opposed to missed fused operators ? It might at present be difficult to correct classify missed fused operators vs unfusable ones / compute bound ones

**Comment by cpuhrsch** [comment]
@eellison - or did you mean something else?

**Comment by eellison** [comment]
And do you have the original code ? (not just the sped up code)

**Comment by cpuhrsch** [comment]
Yes, the original code is [here](https://github.com/e3nn/e3nn/blob/main/e3nn/o3/_spherical_harmonics.py#L184-L456) (linked under [ridiculously fuseable code](https://github.com/e3nn/e3nn/blob/main/e3nn/o3/_spherical_harmonics.py#L184-L456) above)
