### ISSUE TITLE
cublas runtime error:  the GPU program failed to execute

### ISSUE THREAD

**Issue by camelhehe** [pytorch/pytorch#7548]
Deay guys,

I'm am trying train crnn model, but I always meet these errors:
Traceback (most recent call last):
  File "crnn_main.py", line 201, in <module>
    cost = trainBatch(crnn, criterion, optimizer)
  File "crnn_main.py", line 188, in trainBatch
    cost.backward()
  File "/home/abc/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/abc/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cublas runtime error : the GPU program failed to execute at /home/abc/caimx/opensource/pytorch/aten/src/THC/THCBlas.cu:249

my environment in my PC is:
CUDA-9.0
CUDNN v7
conda2/python2.7
gcc version:4.9

I can run the test apps in /pytorch/aten/build/src/ATen/test
pytorch source code was downloaded here, I also ran python setup.py install successfully

**Comment by camelhehe** [comment]
I found the root cause, that is a mistake on loading input data, not an environment case

**Comment by jdhao** [comment]
@camelhehe ,can you elaborate on the cause of this problem? I have also met with this issue and can not understand the reason.

**Comment by clarle** [comment]
I also ran into this issue - turns out it's because I have a RTX 2080 TI and I'm hitting this:

https://github.com/pytorch/pytorch/issues/13038

**Comment by jamesjjcondon** [comment]
thanks @jdhao, I was starting a mini version of a net, using labels "2" and "0", from a subset of my data. Changing these to "1" and "0" fixed (and hence the "t < n_classes" part of this error.

**Comment by Yonv1943** [comment]
I meet the same problem as you. And I solve it by:
` "net(x).double().to(device)" --> "net(x).to(device)"`
====================================
cublas runtime error: the GPU program failed to execute
PyTorch 1.1, CUDA 10.0, Python 3.6, *RTX 2080Ti*
====================================

More Detail:
I meet this error when I choose *RTX 2080Ti*, but But the same code can run on *NVIDIA V100*.
When I delete the ".double()", it can run on both  *RTX 2080Ti* and  *NVIDIA V100*.

**Comment by ameliamlz** [comment]
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:411

**Comment by linko994** [comment]
> I meet the same problem as you. **And I solve it by**:
> ` "net(x).double().to(device)" --> "net(x).to(device)"`
> 
> ```
> cublas runtime error: the GPU program failed to execute
> PyTorch 1.1, CUDA 10.0, Python 3.6, RTX 2080Ti
> ```
> 
> More Detail:
> I meet this error when I choose **RTX 2080Ti**, but But the same code can run on NVIDIA V100.
> When I **delete the ".double()"**, it can run on both RTX 2080Ti and NVIDIA V100.

I'm getting this error as well on RTX 2070 SUPER. When I delete the .float() I don't get the Cublas error, but I get another one.

**Comment by ameliamlz** [comment]
I already solved this problem.I installed gcc5.4 and pytorch 1.1.0 . It can adapt my computer environment(RTX2070,python3.6,cuda10.0)
