### ISSUE TITLE
Windows actions failing during setup

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#75482]
Examples:
- https://github.com/pytorch/pytorch/runs/5878041324?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/5877370350?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/5877156070?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/5877098426?check_suite_focus=true

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
cc @atalman could this be related to the AMI update?
