### ISSUE TITLE
Feature Request: Please add a function like dimension transformation like `einops`

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#75497]
### 🚀 The feature, motivation and pitch

Please add a function like dimension transformation like `einops`:
```python
# In einops
y = rearrange(x, "b c h w -> b h w c")
```
So, kindly add a new feature like:
```python
# New feature in PyTorch
y = x.permute_via("b c h w -> b h w c")
# Merge two dimensions
y = x.permute_via("b c h w -> b c (h w)")
# For named tensors,
imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
y = imgs.permute_to("N C (H W)")
```

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ezyang** [comment]
added to triage review to discuss

**Comment by songyuc** [comment]
你好，您的邮件我已经收到，谢谢您！~O(∩_∩)O~                                                    宋玉成

**Comment by Lezcano** [comment]
Is this not [torch.permute](https://pytorch.org/docs/stable/generated/torch.permute.html)?

**Comment by songyuc** [comment]
> Is this not [torch.permute](https://pytorch.org/docs/stable/generated/torch.permute.html)?

I expect that this new function can accept the transformation string as the argument.

**Comment by Lezcano** [comment]
Would the following code do the trick?

```python
s = "b c h w -> b h w c"


def preprocess(s):
    return [x for x in s.split(" ") if x]


def to_permutation(s):
    from_s, to_s = s.split("->")
    from_s = preprocess(from_s)
    to_s = preprocess(to_s)
    map_from_s = dict(zip(from_s, range(0, len(from_s))))
    # Dict is insertion ordered from Python 3.7
    map_to_s = {x: map_from_s[x] for x in to_s}
    return list(map_to_s.values())

y = x.permute(to_permutation(s))
```

**Comment by songyuc** [comment]
> Would the following code do the trick?
> 
> 
> 
> ```python
> 
> s = "b c h w -> b h w c"
> 
> 
> 
> 
> 
> def preprocess(s):
> 
>     return [x for x in s.split(" ") if x]
> 
> 
> 
> 
> 
> def to_permutation(s):
> 
>     from_s, to_s = map(preprocess, s.split("->"))
> 
>     map_from_s = dict(zip(from_s, range(0, len(from_s))))
> 
>     # Dict is insertion ordered from Python 3.7
> 
>     map_to_s = {x: map_from_s[x] for x in to_s}
> 
>     return list(map_to_s.values())
> 
> 
> 
> y = x.permute(to_permutation(s))
> 
> ```

I think a tuple or list comprehension might be better than a dict one.

**Comment by Lezcano** [comment]
Agree, I just simplified the code to be a couple lines. Does this solve this issue?

**Comment by songyuc** [comment]
> Agree, I just simplified the code to be a couple lines. Does this solve this issue?

This implementation does realize the the case mentioned, however, which might be a little unconcise. Besides, the original operation in einops is more powerful, like "n c h w -> n c (hw)".

**Comment by soulitzer** [comment]
From triage review: we would like something like this, but it should be in Python
@ngimel this is more powerful than reshape and could potentially be a footgun
@mike we'll allow it but if doesn't return a view, then we'll error

**Comment by vadimkantorov** [comment]
Btw native `rearrange` seems merged in: https://github.com/pytorch/pytorch/issues/92675

should this issue be closed/completed now as well?
