### ISSUE TITLE
Unable to install pytorch with pip on macOS Monterey 12.0.1 (M1 chip)

### ISSUE THREAD

**Issue by SN4KEBYTE** [pytorch/pytorch#75534]
### 🐛 Describe the bug

I'm trying to install pytorch using pip:
```python -m pip install torch```

The error:
```
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.0.1 (arm64)
GCC version: Could not collect
Clang version: 11.1.0
CMake version: version 3.21.2
Libc version: N/A

Python version: 3.8.12 (default, Apr  5 2022, 20:55:52)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-10.16-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[conda] Could not collect

cc @ezyang @seemethere @malfet @albanD

**Comment by malfet** [comment]
Hmm, this is strange, can you please try downloading and installing https://files.pythonhosted.org/packages/7c/bc/c5ada769b0f31ca1b7f05e15575703641d648100ac432a182e350076e64d/torch-1.11.0-cp38-none-macosx_11_0_arm64.whl directly?

**Comment by SN4KEBYTE** [comment]
Still getting an error:
```ERROR: torch-1.11.0-cp38-none-macosx_11_0_arm64.whl is not a supported wheel on this platform.```

**Comment by chen-little-tom** [comment]
> Hmm, this is strange, can you please try downloading and installing https://files.pythonhosted.org/packages/7c/bc/c5ada769b0f31ca1b7f05e15575703641d648100ac432a182e350076e64d/torch-1.11.0-cp38-none-macosx_11_0_arm64.whl directly?

sorry, it can't work!

**Comment by tgolsson** [comment]
I just went through a dig; it looks like there's just no published wheels for Monterey/OSX 12.x -- neither to PyPi nor anywhere on https://download.pytorch.org/whl. I'm guessing it needs to be handled here: https://github.com/pytorch/builder/blob/main/wheel/build_wheel.sh#L104

**Comment by tgolsson** [comment]
There seems to be hints of that! I'm not a Mac user, I was investigating a similar issue based on a bug report from a user, and then found this topic. That kind of backwards/forwards compatibility is mentioned specifically only on the `pip download` documentation page. I'll try to verify with the original reporter.

**Comment by kulinseth** [comment]
> Still getting an error: `ERROR: torch-1.11.0-cp38-none-macosx_11_0_arm64.whl is not a supported wheel on this platform.`

I tried few things:

1. I am able to install it fine inside a miniconda/miniforge environment:

```
Processing /Users/kulinseth/Downloads/torch-1.11.0-cp38-none-macosx_11_0_arm64.whl
Requirement already satisfied: typing-extensions in /Users/kulinseth/miniconda3/lib/python3.8/site-packages (from torch==1.11.0) (4.0.1)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 1.12.0a0+git9f7f0d9
    Uninstalling torch-1.12.0a0+git9f7f0d9:
      Successfully uninstalled torch-1.12.0a0+git9f7f0d9
Successfully installed torch-1.12.0a0+git38e3068
(base) bash-3.2$ 
(base) bash-3.2$ python
Python 3.8.11 (default, Jul 29 2021, 14:57:32)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>>
```

2. Using system python3. Make sure pip is updated `python -m pip install -U pip`

```
kulinseth@local% source ~/pytorch-venv/bin/activate
(pytorch-venv) kulinseth@local % which python
/Users/kulinseth/pytorch-venv/bin/python
(pytorch-venv) kulinseth@local % python -m pip install /Users/kulinseth/Downloads/torch-1.11.0-cp38-none-macosx_11_0_arm64.whl 
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
ERROR: torch-1.11.0-cp38-none-macosx_11_0_arm64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/kulinseth/pytorch-venv/bin/python -m pip install --upgrade pip' command.
(pytorch-venv) kulinseth@local % python -m pip install -U pip
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Collecting pip
  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 3.8 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-22.0.4
(pytorch-venv) kulinseth@local % 
(pytorch-venv) kulinseth@local % python -m pip install /Users/kulinseth/Downloads/torch-1.11.0-cp38-none-macosx_11_0_arm64.whl 
Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Processing /Users/kulinseth/Downloads/torch-1.11.0-cp38-none-macosx_11_0_arm64.whl
Collecting typing-extensions
  Using cached https://pypi.apple.com/packages/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions, torch
Successfully installed torch-1.11.0 typing-extensions-4.1.1
```

3. The other things to try is if you Xcode Command line tools installed . The python3 used by the command line tools with `arm64` is the right binary format to use

**Comment by welch** [comment]
I had such troubles getting to 1.12.0 today, attempting to use `pip install --upgrade torch` and `pip install torch==1.12.0`, both giving that same cant-find-version error. 

It turned out, my pip was behind by one point release, and letting pip upgrade itself (to 22.1.2) solved the torch installation problem.

**Comment by albanD** [comment]
This should be resolved properly now.
Feel free to open a new issue if you're still encountering this.

**Comment by programmerq** [comment]
This issue can remain closed.

I also ran into this error on Ventura 13.1 on amd64. According to `https://pypi.org/project/torch/#files`, the current version of torch is 1.13.1. I noticed that I was running my homebrew Python 3.11, but macos comes with a Python 3.9. Currently, the only wheel files at the above link for 3.11 are for the `manylinux` platform, and not the `macosx` platform. I created a virtualenv using the macosx-provided /usr/bin/python3 binary, and `pip install -U torch` works. It correctly grabs `torch-1.13.1-cp39-none-macosx_10_9_x86_64.whl` and completes just fine.

Just sharing in case anyone else runs into it between the time that your macosx or python versions are newer than the platforms available for the wheel.

**Comment by p-i-** [comment]
I'm getting this on Python 3.11.1 on macOS Ventura 13.1 (22C65)

3.11.1 came out over 50 days ago.

Team `pytorch`, please oil your CI/CD pipeline, as the focus of our species turns to AI.

Just imagine the developer-hours lost thrashing because of issues such as this!

**Comment by gweber** [comment]
pyenv global 3.9.16 is working, 3.11.1 fails even with updated pip. on mac.

**Comment by malfet** [comment]
We only have 3.11 wheels for Linux at the moment, https://github.com/pytorch/pytorch/pull/93400 will enable it for Mac and Windows, so it should be available in next nightly, but would not be available for 1.13 release

**Comment by MikePendo** [comment]
I have the same issue Sonoma 14.4.1 M1, Python 3.8.16. 
Tried to follow [apple explanation](https://developer.apple.com/metal/pytorch/):
`pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`
same error:
```
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

**Comment by ruidazeng** [comment]
Just had this issue again…Are there reliable fixes available.
