### ISSUE TITLE
Remove conda-forge dependency for cuda 11.5, 11.6

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#75532]
### 🐛 Describe the bug

Here is the one example of the conda-forge dependency  [binary_linux_test](https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/binary_linux_test.sh#L56)

We would want get rid of this. If conda-forge not used we get following error:

```
/opt/conda/bin/conda install -yq -c nvidia -c pytorch cudatoolkit=11.6 UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
Package libgcc-ng conflicts for:
cudatoolkit=11.6 -> libgcc-ng[version='>=9.4.0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0']The following specifications were found to be incompatible with your system:
  - feature:/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__glibc==2.17=0
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
Your installed version is: 2.17
```

### Versions

CUDA 11.5 
CUDA 11.6

cc @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra @ptrblck

**Comment by ptrblck** [comment]
I agree that mixing different channels is not the desired path.
The dependency conflict is btw. also raised for the `cuda` conda binary.

I'm happy to forward this issue and check if we could either relax these dependency or move the required packages.

**Comment by atalman** [comment]
resolved
