### ISSUE TITLE
[Feature request] Support for quantized (INT8) training and inference

### ISSUE THREAD

**Issue by Randl** [pytorch/pytorch#7553]
Given the rising support of low-precision networks (e.g., NVIDIA and Google) it would be nice to have support for INT8 model training and inference. 

https://www.tensorflow.org/performance/quantization#quantization_training_with_tensorflow

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by michaelklachko** [comment]
Also, latest Nvidia cards support INT4. And Tesla T4 has experimental mode for INT1.

**Comment by gottbrath** [comment]
Note that we have a notebook with a preview tutorial on eager mode post training quantization over in #18318 ... please check it out and leave feedback.

**Comment by raghuramank100** [comment]
Closing this issue as we now have quantization support in eager mode, tutorial is at: 
https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html

**Comment by sourabhd** [comment]
@gottbrath @raghuramank100  Could you clarify how the INT8 support can be used on GPUs like Tesla T4 ? (Tesla T4 is the GPU available on GCP, AWS, Azure platforms). The supported quantization backends FBGEMM and QNNPACK are for CPUs. From the Tesla T4 tensor core datasheet specifications, operations per second for single precision, mixed precision, INT8, INT16 are  8.1 T, 65 T, 130 T, 260 T respectively.  Correct me if I am wrong, higher speedups than, 2-4x speedup on Macbook Pro (from the tutorial), could be achieved, if we can make use of the power of the GPUs.
