### ISSUE TITLE
Smart make lint ala arc lint

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#75567]
### 🐛 Describe the bug

make lint takes a pretty long time to run on my machine. This is because it is linting all files in PyTorch, and our tools (flake8, mypy) are not particularly fast. `arc lint` at Facebook takes a different approach: it only runs lint on files that changed for the current diff. We should provide this capability.

### Versions

master

cc @malfet @seemethere

**Comment by suo** [comment]
closed by lintrunner
