### ISSUE TITLE
CI should advertise `make lint`

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#75566]
### 🐛 Describe the bug

When lints fail, the CI should tell the user that they can check lints locally by running `make setup_lint; make lint` so that they get in the habit of running this before submitting.

### Versions

master

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
I know @suo was working on a lint runner for this

**Comment by janeyx99** [comment]
2 solutions:
- add note to lint workflows or Dr. CI
- use lint runner

**Comment by suo** [comment]
okay I did some digging and learned about https://github.com/PyO3/maturin, which basically seems like magic and will let us distribute a rust binary with `pip`.

**Comment by suo** [comment]
that was easy https://pypi.org/project/lintrunner/

**Comment by suo** [comment]
CI now advertises lintrunner
