### ISSUE TITLE
ONNX: ones_like may result in a large ONNX

### ISSUE THREAD

**Issue by shinh** [pytorch/pytorch#75597]
### 🐛 Describe the bug

Torch functions which can be represented by `ConstantOfShape` op are expanded to `Constant` op. This happens even with `do_constant_folding=False`. Here is an example script:

```python
import os

import onnx
import torch


class OnesLike(torch.nn.Module):
    def forward(self, x):
        return x + torch.ones_like(x)


# torch 1.10 or later cannot export this if we change 100 to 1000.
x = torch.ones(100, 1000, 1000)
torch.onnx.export(OnesLike(), x, 'ones_like.onnx',
                  do_constant_folding=False,
                  opset_version=13)

m = onnx.load("ones_like.onnx")

# 1.9: ['Shape', 'ConstantOfShape', 'Add'] 210
# 1.10: ['Constant', 'Add'] 400000191
# 1.11: ['Constant', 'Add'] 400000233
print([n.op_type for n in m.graph.node], os.stat("ones_like.onnx").st_size)
```

With torch 1.9, it output `['Shape', 'ConstantOfShape', 'Add'] 210` but with 1.10 and 1.11, it output `['Constant', 'Add'] 400000XXX`.

Even worse, this may make ONNX export fail due to the 2GB limit of protobuf. It seems `torch.onnx` does not use `DataLocation.EXTERNAL` of `onnx::TensorProto` for `Constant` op, so exporting stops working if we change `100, 1000, 1000` in the above script to `1000, 1000, 1000`.

In general, I think it is better to try using `ConstantOfShape` instead of `Constant` when a `Constant` seems to have the same value. It'd be also a good idea not to apply constant folding for large tensors, especially when `do_constant_folding` is False.

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-39-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.790
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] pytorch-pfn-extras==0.5.8
[pip3] torch==1.11.0+cpu
[pip3] torchaudio==0.10.0+cpu
[pip3] torchvision==0.12.0+cpu
[conda] Could not collect
```

**Comment by fatcat-z** [comment]
With torch 1.10, if we set use_external_data_format=True for torch.onnx.export() function, the model could be exported successfully. It shows:

['Constant', 'Add'] 235

Will take a look.

**Comment by shubhambhokare1** [comment]
Hi @shinh,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
