### ISSUE TITLE
Inference mode throws RuntimeError for `torch.repeat_interleave()` for big tensors

### ISSUE THREAD

**Issue by Harimus** [pytorch/pytorch#75595]
### 🐛 Describe the bug

I think this bug is related to issue: #70177 and #60539 for `torch.inference_mode()`.

When running `torch.repeat_interleave` function on big tensors inside `with torch.inference_mode():` block if causes the RuntimeError:

>RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
 
Below is a python interactive quick example to replicate the bug: (Edit: Running without CUDA or GPU)

```
user@computer: python
Python 3.8.11 (default, Aug  3 2021, 15:09:35) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; torch.__version__
'1.9.0+cu102'
>>> input_small = torch.randn(1000, 111)
>>> input_big = torch.randn(49995, 111)
>>> with torch.inference_mode():
...   output_small = torch.repeat_interleave(input_small, 5, dim=0)
... 
>>> with torch.inference_mode():
...   output_big = torch.repeat_interleave(input_big, 5, dim=0)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
```

### Versions

Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.11 (default, Aug  3 2021, 15:09:35)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-39-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce MX150
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] botorch==0.5.0
[pip3] gpytorch==1.5.0
[pip3] numpy==1.22.2
[pip3] torch==1.9.0
[conda] botorch                   0.5.0                    pypi_0    pypi
[conda] gpytorch                  1.5.0                    pypi_0    pypi
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] torch                     1.9.0                    pypi_0    pypi

**Comment by ngimel** [comment]
Can't repro on master. Please reopen if still repros on 1.11/nightlies

**Comment by Maioy97** [comment]
hello, 
i don't understand the comment that solved the problem
I get the same error when trying this line in the yolov5 project yolov5/utils/general.py
`coords[:, [0, 2]] -= pad[0]  # x padding`
and get this error 

`RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.`

**Comment by jitaxis** [comment]
> hello, i don't understand the comment that solved the problem I get the same error when trying this line in the yolov5 project yolov5/utils/general.py `coords[:, [0, 2]] -= pad[0] # x padding` and get this error
> 
> `RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.`

You need to use the decorator 
    @smart_inference_mode()
    before your display function
