### ISSUE TITLE
torch.sum(Variable(...)) returns Variable(torch.ByteTensor) and overflows

### ISSUE THREAD

**Issue by rtqichen** [pytorch/pytorch#756]
Came across this randomly while testing code:
```
a = Variable(torch.randn(1,4,16,10))
b = Variable(torch.randn(1,4,16,10))
a[:,2:] = b[:,2:]
torch.sum(a==b)
```
gives an incorrect value
```
Variable containing:
 64
[torch.ByteTensor of size 1]
```
while `torch.sum((a==b).data)` returns `320`

Likely caused by overflow of torch.ByteTensor. It seems weird to me ByteTensor is being used instead of IntTensor or LongTensor.

Edit: Just realized it's because a==b returns a ByteTensor. I guess there's really no use case for using Variable here anyway.

**Comment by soumith** [comment]
ByteTensors are accumulated into ByteTensor for now. We dont do accumulations into a different tensor type. This is expected.
Anyways, just fyi, maybe you are looking for: (a==b).all(), i.e. torch.all
