### ISSUE TITLE
[build] File `torch/csrc/lazy/generated/README.md` gets cleaned by `python setup.py clean` but it's tracked by git

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#75624]
### 🐛 Describe the bug

File `torch/csrc/lazy/generated/README.md` gets cleaned by `python setup.py clean` but it's tracked by git.

Every time I started a clean build with `python setup.py clean`, this file gets removed (from .gitignore) and my `git status` shows a deleted file.

### Versions

master

cc @malfet @seemethere

**Comment by malfet** [comment]
cc: @wconstab who added those files as part of https://github.com/pytorch/pytorch/pull/74850
Are they intend to be permanent? Or so, mind removing it from the clean target?

**Comment by malfet** [comment]
Looks like a oneliner - just exclude README.md from .gitignore
