### ISSUE TITLE
Move test/jit/test_onnx_export.py to test/onnx

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#75627]
This file should be moved to the test/onnx dir:
test/jit/test_onnx_export.py

Perhaps combined with test/onnx/test_pytorch_onnx_no_runtime.py which is being added in https://github.com/pytorch/pytorch/pull/73284.

That will let us merge changes to that file without going through the PyTorch internal tests, and it will also just consolidate all the ONNX tests for easier discoverability.

**Comment by garymm** [comment]
@allentitaiwang please comment on this so I can assign it to you :-)

**Comment by AllenTiTaiWang** [comment]
Right here.

**Comment by AllenTiTaiWang** [comment]
@garymm It seems that I am not collaborator of pytorch yet, could you help me with that. Doe it matter if I open another issue assigned to myself to merge test_pytorch_onnx_no_runtime.py into test_pytorch_onnxruntime.py without being collaborator? If I can, I will open it later.
https://github.com/pytorch/pytorch/pull/78116

**Comment by garymm** [comment]
I don't see what being a collaborator has to do with what you wrote, but I have asked the team at Meta to invite you.
Feel free to open issues whenever you want.

**Comment by AllenTiTaiWang** [comment]
Continue on #78119
