### ISSUE TITLE
[ONNX] `ONNX_ATEN_FALLBACK` supports ONNX Runtime

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#75623]
Previously setting `operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK` produed a model that was only usable by Caffe2.
This issue tracks work to make it usable by ONNX Runtime as well.

**Comment by thiagocrepaldi** [comment]
[ONNX Runtime python frontend](https://github.com/microsoft/onnxruntime/pull/10700) depends on this feature

**Comment by thiagocrepaldi** [comment]
All planned PRs have been merged
