### ISSUE TITLE
[ONNX] automatic type checking during export inside autocast

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#75637]
Currently when Autocast is enabled, type check for input arguments is disabled, which results in confusing error messages for the user during torch.onnx.export
One workaround is to manually write type check code for each symbolic by manually analysing its opsets/schemas
https://github.com/pytorch/pytorch/issues/72494 is an example of this approach.

However, a better way might be to leverage ONNX API to get the schema of an operator and form an automatic validation for all symbolics as a new jit pass during export:
`onnx.defs.get_schema(node.op_type, opset.version, opset.domain) or onnx.defs.get_schema(node.op_type, opset.domain)`

**Comment by BowenBao** [comment]
Backlogged since no one is working on this. Closing.
