### ISSUE TITLE
[ONNX] Export should ensure both branches of if statement produce same type

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#75631]
I found a case where I had to modify the model with extra type-casting to make it produce a valid output.

Particular code can be seen in _capacity function here:
https://github.com/microsoft/DeepSpeed/pull/1578/files

If I remove the `.to(int64)` from inside the if statement, the exported model has inconsistent types for the if and else branches.

**Comment by justinchuby** [comment]
This should be able to fix with better type inference support. Closing for now.
