### ISSUE TITLE
cpu only pip3 install preview (Nightly) has CUDA dependency

### ISSUE THREAD

**Issue by denolf** [pytorch/pytorch#75640]
### 🐛 Describe the bug

After installing a cpu only version of the Preview (Nighlty) PyTorch Build using:
`pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`

and resulting in following packages being installed:

Collecting torch
  Using cached torch-1.10.2-cp36-cp36m-manylinux1_x86_64.whl (881.9 MB)
Collecting torchvision
  Using cached torchvision-0.11.2-cp36-cp36m-manylinux1_x86_64.whl (23.3 MB)
Collecting torchaudio
  Using cached torchaudio-0.10.1-cp36-cp36m-manylinux1_x86_64.whl (2.9 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting dataclasses
  Using cached dataclasses-0.8-py3-none-any.whl (19 kB)
Collecting torch
  Using cached torch-1.10.1-cp36-cp36m-manylinux1_x86_64.whl (881.9 MB)
Collecting pillow!=8.3.0,>=5.3.0
  Using cached Pillow-8.4.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting numpy
  Using cached numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Installing collected packages: typing-extensions, dataclasses, torch, pillow, numpy, torchvision, torchaudio
Successfully installed dataclasses-0.8 numpy-1.19.5 pillow-8.4.0 torch-1.10.1 torchaudio-0.10.1 torchvision-0.11.2 typing-extensions-4.1.1

there still seems to be a CUDA dependency:

-- Found PyTorch installation at /home/kristof/XilinxWork/XRLabsRepos/torch-mlir/mlir_venv/lib/python3.6/site-packages/torch/share/cmake
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
CMake Warning at ../../../mlir_venv/lib/python3.6/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:31 (message):
  Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
  or a Caffe2 dependent library, the next warning / error will give you more
  info.

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.4.1708 (Core)  (x86_64)
GCC version: (GCC) 8.3.0
Clang version: 8.0.1 
CMake version: version 3.20.6
Libc version: glibc-2.2.5

Python version: 3.6.5 (default, Apr  2 2018, 15:45:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] (64-bit runtime)
Python platform: Linux-3.10.0-693.el7.x86_64-x86_64-with-centos-7.4.1708-Core
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.11.2
[conda] Could not collect

cc @malfet @seemethere @ngimel

**Comment by denolf** [comment]
Upgrading Python to 3.8 solves this:

$ python3 collect_env.py 
Collecting environment information...
PyTorch version: 1.12.0.dev20220412+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.4.1708 (Core)  (x86_64)
GCC version: (GCC) 8.3.0
Clang version: 8.0.1 
CMake version: version 3.20.6
Libc version: glibc-2.17

Python version: 3.8.3 (default, Jun  1 2020, 03:19:56)  [GCC 6.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220412+cpu
[pip3] torchvision==0.13.0.dev20220412+cpu
[conda] Could not collect

**Comment by seemethere** [comment]
We don't currently support Python 3.6 anymore. Would recommend to upgrade to at least 3.7.

Thanks for reporting though!
