### ISSUE TITLE
DISABLED test_fft_plan_repeatable_cuda (__main__.TestFFTCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#75664]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_fft_plan_repeatable_cuda%2C%20TestFFTCUDA)).

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @mruberry @peterbell10

**Comment by peterbell10** [comment]
I can't see any relevant changes on our end, so suspect this is a ROCm bug. That said, AFAIK the ROCm version is fixed in CI so not sure why this would only start now.

**Comment by janeyx99** [comment]
@jeffdaily could this have to do with the 5.0 update? Or the fact that these tests were recently allowed on trunk?

**Comment by jeffdaily** [comment]
I don't have a full history of this test.  @micmelesse do you know whether this test has been an issue for us in the past?

**Comment by micmelesse** [comment]
We unskipped a bunch of fft tests recently in this pr, https://github.com/pytorch/pytorch/pull/74713 , which was 20 days ago. Is there more data than the last 14 days for the failure rate?

**Comment by peterbell10** [comment]
It's not an OpInfo-based test so I don't think #74713 is relevant.

**Comment by janeyx99** [comment]
@micmelesse We don't have yet have a test history view (that is in our roadmap for the year, though), but I ran the query for this test and got a CSV of relevant stats:
[query-results.csv](https://github.com/pytorch/pytorch/files/8489843/query-results.csv)

I hope it can be useful!

**Comment by peterbell10** [comment]
It looks like the first recorded failure was the day before #74713 was merged, so not relevant.

The most likely candidate is #73105 which is changed the ROCm version being tested in CI and was merged on March 30 which is the date of the first recorded failure.

**Comment by jaglinux** [comment]
Test ran successfully in loop on ROCm 5.1 and 5.2
cc @jithunnair-amd @jeffdaily

**Comment by jeffdaily** [comment]
Closing based on recent comments.

**Comment by peterbell10** [comment]
Has the test been re-enabled?

**Comment by jaglinux** [comment]
> Has the test been re-enabled?

Yes.
