### ISSUE TITLE
[FSDP] [Mixed Precision] using param_dtype breaks transformers ( in attention_probs matmul)

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#75676]
### 🐛 Describe the bug

Using PyTorch nightly, enable mixed precision support parameters for fsdp.
When running with a transformer, you will hit the following error - float expected but received half or bfloat (depending on mp config):
<img width="1109" alt="mp_half_float_expected" src="https://user-images.githubusercontent.com/46302957/163023347-231ac2a5-60f0-422a-a100-c6b2381f71f2.png">

Note that comm mp and buffer mp all work as expected.  You can use partial mixed precision by setting the param_dtype to fp32:
<img width="472" alt="reduce_buffer_working" src="https://user-images.githubusercontent.com/46302957/163023528-6c1d59cb-848e-4c04-9cc7-65a94a8b5394.png">

The issue is specific to the attention_probs matmul:
<img width="1109" alt="attention*value_failing" src="https://user-images.githubusercontent.com/46302957/163023643-a2020557-9cc6-4bf0-820e-e9766ea7fffa.png">

and previous matmuls work as expected:
<img width="1109" alt="q*k_working" src="https://user-images.githubusercontent.com/46302957/163023695-c8c085ae-8c07-40df-aadd-a51fbc01b27d.png">

Enabling stack trace yields:
File "/home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 340, in forward
    context_layer = torch.matmul(attention_probs, value_layer)
RuntimeError: expected scalar type BFloat16 but found Float
Exception raised from data_ptr<c10::BFloat16> at aten/src/ATen/core/TensorMethods.cpp:18 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fa8dadacb82 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fa8dada921b in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::BFloat16* at::TensorBase::data_ptr<c10::BFloat16>() const + 0xde (0x7fa91c90d1ae in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x479b0a1 (0x7fa8df7920a1 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #4: at::native::structured_bmm_out_cuda::impl(at::Tensor const&, at::Tensor const&, at::Tensor const&) + 0x66 (0x7fa8df793356 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #5: <unknown function> + 0x45c94dc (0x7fa8df5c04dc in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #6: <unknown function> + 0x45c956f (0x7fa8df5c056f in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #7: at::_ops::bmm::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&) + 0x74 (0x7fa91c31f064 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x2bc7f33 (0x7fa91d348f33 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2bc87c2 (0x7fa91d3497c2 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::_ops::bmm::call(at::Tensor const&, at::Tensor const&) + 0xb2 (0x7fa91c358a62 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x144bdd0 (0x7fa91bbccdd0 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #12: at::native::matmul(at::Tensor const&, at::Tensor const&) + 0x3a (0x7fa91bbcdaca in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x1e9db5f (0x7fa91c61eb5f in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #14: at::_ops::matmul::call(at::Tensor const&, at::Tensor const&) + 0xb2 (0x7fa91c404e82 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x345de9 (0x7fa942354de9 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #16: PyCFunction_Call + 0x54 (0x55a44eee9f44 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #17: _PyObject_MakeTpCall + 0x31e (0x55a44eef930e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #18: _PyEval_EvalFrameDefault + 0x53cf (0x55a44ef8f6ff in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #19: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #20: _PyFunction_Vectorcall + 0x378 (0x55a44ef6e198 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #21: <unknown function> + 0x1b0dfc (0x55a44ef6edfc in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #22: PyObject_Call + 0x5e (0x55a44eee316e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #23: _PyEval_EvalFrameDefault + 0x21bf (0x55a44ef8c4ef in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #24: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #25: _PyObject_FastCallDict + 0x2c1 (0x55a44eedde11 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #26: _PyObject_Call_Prepend + 0xce (0x55a44eee8abe in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #27: <unknown function> + 0x17f3f9 (0x55a44ef3d3f9 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #28: _PyObject_MakeTpCall + 0x31e (0x55a44eef930e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #29: _PyEval_EvalFrameDefault + 0x53cf (0x55a44ef8f6ff in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #30: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #31: _PyFunction_Vectorcall + 0x378 (0x55a44ef6e198 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #32: <unknown function> + 0x1b0dfc (0x55a44ef6edfc in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #33: PyObject_Call + 0x5e (0x55a44eee316e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #34: _PyEval_EvalFrameDefault + 0x21bf (0x55a44ef8c4ef in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #35: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #36: _PyFunction_Vectorcall + 0x378 (0x55a44ef6e198 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #37: _PyObject_FastCallDict + 0x2fd (0x55a44eedde4d in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #38: _PyObject_Call_Prepend + 0x63 (0x55a44eee8a53 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #39: <unknown function> + 0x17f3f9 (0x55a44ef3d3f9 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #40: _PyObject_MakeTpCall + 0x31e (0x55a44eef930e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #41: _PyEval_EvalFrameDefault + 0x56cb (0x55a44ef8f9fb in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #42: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #43: _PyFunction_Vectorcall + 0x378 (0x55a44ef6e198 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #44: <unknown function> + 0x1b0dfc (0x55a44ef6edfc in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #45: PyObject_Call + 0x5e (0x55a44eee316e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #46: _PyEval_EvalFrameDefault + 0x21bf (0x55a44ef8c4ef in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #47: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #48: _PyObject_FastCallDict + 0x2c1 (0x55a44eedde11 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #49: _PyObject_Call_Prepend + 0xce (0x55a44eee8abe in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #50: <unknown function> + 0x17f3f9 (0x55a44ef3d3f9 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #51: _PyObject_MakeTpCall + 0x31e (0x55a44eef930e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #52: _PyEval_EvalFrameDefault + 0x5026 (0x55a44ef8f356 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #53: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #54: _PyFunction_Vectorcall + 0x378 (0x55a44ef6e198 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #55: <unknown function> + 0x1b0dfc (0x55a44ef6edfc in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #56: PyObject_Call + 0x5e (0x55a44eee316e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #57: _PyEval_EvalFrameDefault + 0x21bf (0x55a44ef8c4ef in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #58: _PyEval_EvalCodeWithName + 0x2c3 (0x55a44ef6cdb3 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #59: _PyFunction_Vectorcall + 0x378 (0x55a44ef6e198 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #60: _PyObject_FastCallDict + 0x2fd (0x55a44eedde4d in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #61: _PyObject_Call_Prepend + 0x63 (0x55a44eee8a53 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #62: <unknown function> + 0x17f3f9 (0x55a44ef3d3f9 in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)
frame #63: _PyObject_MakeTpCall + 0x31e (0x55a44eef930e in /home/ubuntu/anaconda3/envs/pytorch_p38/bin/python)

Repro code is here:
https://github.com/lessw2020/fsdp_review/blob/main/bert/fsdp_bert_fix.py

It does expect the imdb dataset to be present, so if needed I can setup modular repro setup.  

### Versions

Pytorch Nightly 4/08, with YanLi's bert ordered dict fix in fdsp/utils.
*I'll run the env collect if needed once I'm on my server. 

cc @zhaojuanmao @mrshenli @rohan-varma

**Comment by lessw2020** [comment]
Small repo to quickly reproduce:
https://github.com/lessw2020/mixprecision

git clone and run "python fsdp_mp.py" should put you right into stack trace.
adjust active policy to relevant configs to toggle between working (bfSixteen_working) and not (bfSixteen). 
<img width="878" alt="mp_policy_control" src="https://user-images.githubusercontent.com/46302957/163057679-c2f867a3-1315-46de-b8f2-1de873975594.png">

**Comment by rohan-varma** [comment]
Discussed with Less offline, pasting result from discussion here:

**Comment by orchidmajumder** [comment]
Hi, is there a decision made on whether this will be fixed at the FSDP layer or at the HuggingFace layer?

**Comment by awgu** [comment]
It is unlikely that we will fix this in the FSDP layer. I will mark this as not planned for now.
