### ISSUE TITLE
[caffe2]Couldn't import caffe2.python.onnx.backend and caffe2.python.onnx.frontend

### ISSUE THREAD

**Issue by tom888888** [pytorch/pytorch#7567]
1.When I install caffe2 and onnx with conda
`conda install -c caffe2 caffe2`
`conda install -c conda-forge onnx`
`conda install -c conda-forge protobuf numpy`

`python -c "import onnx"`
 #### this error occurs
`Segmentation fault`

and 
`python`
(1)`import caffe2.python.onnx.frontend`
#### this error occurs
```
   WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
   WARNING:root:Debug message: No module named 'caffe2.python.caffe2_pybind11_state_gpu'
   Segmentation fault
```
(2)`import caffe2.python.onnx.backend`
#### this error occurs
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode
WARNING:root:Debug message: No module named 'caffe2.python.caffe2_pybind11_state_gpu'
Segmentation fault
```

## My Python Environment
python 3.6.3
onnx 1.1.1

Could you please advice to solve out this error
Thank you

**Comment by bddppq** [comment]
Could you attach a stack trace?

**Comment by pjh5** [comment]
Can you run conda list caffe2 ? You have either installed a GPU version of Caffe2 or I have misnamed some conda packages

**Comment by sgarcia22** [comment]
I got this error too and am still trying to get it to work, but it is most likely because caffe2 and onnx were compiled with different versions of Protobuf

**Comment by pjh5** [comment]
@sgarcia22 could you attach a stack trace?

You can also try the caffe2-gcc4.8 package, which is built with protobuf from conda-forge.

If it is protobuf related then installing from source should fix it. You'd only have to install onnx from source. I'd recommend something like
```
conda create -yn caffe2 python=3 && source activate caffe2
conda install -yc caffe2 caffe2

# Download this source wherever you want
git clone https://github.com/pytorch/pytorch.git --recursive

# Install onnx from source
cd pytorch
PROTOBUF_INCDIR=/path/to/anaconda/envs/caffe2 pip install third_party/onnx
```

**Comment by sgarcia22** [comment]
@pjh5 Thanks for the response! I was actually able to get it working using yes Anaconda3 and downloading pytorch and onnx from source. In pytorch I also had to run the setup_caffe2.py after setup.py to get caffe2 downloaded.

**Comment by idilsulo** [comment]
@sgarcia22 How were you able to solve your problem? I have done all the steps @pjh5 mentioned. Yet, I am not able to neither run setup.py nor setup_caffe2.py.

When I import caffe2.python.onnx.backend, I get the following error:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: dlopen(/anaconda3/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-darwin.so, 10): Symbol not found: __ZdlPvSt11align_val_t
  Referenced from: /anaconda3/lib/python3.6/site-packages/caffe2/python/../../../../libcaffe2.dylib
  Expected in: /usr/lib/libc++.1.dylib
 in /anaconda3/lib/python3.6/site-packages/caffe2/python/../../../../libcaffe2.dylib
```

**Comment by pjh5** [comment]
Note that this issue is quite obsolete by this point. In particular, you should never need to install the caffe2 package from conda. All the caffe2 code is included in pytorch, and all commands like 
```
conda install -yc caffe2 caffe2
```
will lead to incorrect and unsupported behavior
