### ISSUE TITLE
use ONNX symbolic shape inference in torch.onnx.export

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#75677]
There's some code in the torch.onnx.export for doing symbolic shape inference which is redundant with what exists in the ONNX repo.
This tracks using the code provided by ONNX and thereby simplifying the torch codebase.

**Comment by jcwchen** [comment]
Ongoing one (almost done): https://github.com/pytorch/pytorch/pull/75307. To support more operators in the future: https://github.com/pytorch/pytorch/issues/79208

**Comment by jcwchen** [comment]
I will submit another PR for it. There are some CIs from main branch using older ONNX (1.4.1) which do not have the new API interface I brought in ONNX 1.12.0. Still Investigating.
