### ISSUE TITLE
[Caffe2] Prebuilt gcc4.8 package does not find libcaffe2.so

### ISSUE THREAD

**Issue by louisabraham** [pytorch/pytorch#7572]
I installed CPU caffe2 with anaconda (`conda install -c caffe2 caffe2-gcc4.8`).

The problem is that `caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so` looks for `libstdc++.so.6` in `/usr/lib64` and does not look for `LD_LIBRARY_PATH`.

Is there a way to fix this without recompiling or rewriting `/usr/lib64`?

**Comment by pjh5** [comment]
Can you post the output of ldd on caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so ? Can you also post conda list caffe2 ?

You could rewrite the dependency location with patchelf, and I think if you set rpath in the right way then that will have precedence over system paths.

**Comment by louisabraham** [comment]
My bad, I forgot to precise I installed `caffe2-gcc4.8`.
On the non working system, ldd gives

	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00002aaaac0c9000)

When normal caffe2 is installed (on another linux system), I get

	libstdc++.so.6 => /home/louis/anaconda3/lib/python3.6/site-packages/caffe2/python/./../../../../libstdc++.so.6 (0x00007fb8cdf64000)

**Comment by louisabraham** [comment]
Sorry, my module was actually ill-configured, and `LD_LIBRARY_PATH` was not correct.

Now, the error is with libcaffe2

    ldd: warning: you do not have execution permission for `./caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so'
    ./caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so)
    	linux-vdso.so.1 =>  (0x00002aaaaaaab000)
    	libcaffe2.so => not found
    	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaaada3000)
    	libglog.so.0 => not found
    	libstdc++.so.6 => /cm/shared/apps/gcc/4.8.1/lib64/libstdc++.so.6 (0x00002aaaaafc0000)
    	libm.so.6 => /lib64/libm.so.6 (0x00002aaaab2c3000)
    	libgcc_s.so.1 => /cm/shared/apps/gcc/4.8.1/lib64/libgcc_s.so.1 (0x00002aaaab547000)
    	libc.so.6 => /lib64/libc.so.6 (0x00002aaaab75d000)
    	/lib64/ld-linux-x86-64.so.2 (0x0000003c5b200000)

**Comment by pjh5** [comment]
Can you give the outputs of 
find / -name libcaffe2.so
find / -name caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so

**Comment by louisabraham** [comment]
Sorry for the delay!

    $ find / -name libcaffe2.so 2>/dev/null
    /home/louis/anaconda3/lib/libcaffe2.so
    /home/louis/anaconda3/pkgs/caffe2-0.8.dev-py36_2018.05.09/lib/libcaffe2.so
    $ find / -name caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so 2>/dev/null
    /home/louis/anaconda3/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so
    /home/louis/anaconda3/pkgs/caffe2-0.8.dev-py36_2018.05.09/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so

**Comment by louisabraham** [comment]
Sorry for the delay!

    $ find / -name libcaffe2.so 2>/dev/null
    /home/labraham/.conda/envs/.pkgs/caffe2_gcc4.8-0.8.dev-py36_2018.05.02/lib/libcaffe2.so
    /home/labraham/.conda/envs/.pkgs/caffe2-gcc4.8-0.8.dev-py36_2018.05.05/lib/libcaffe2.so
    /home/labraham/.conda/envs/abx/lib/libcaffe2.so
    $ find / -name caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so 2>/dev/null
    /home/labraham/.conda/envs/.pkgs/caffe2_gcc4.8-0.8.dev-py36_2018.05.02/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so
    /home/labraham/.conda/envs/.pkgs/caffe2-gcc4.8-0.8.dev-py36_2018.05.05/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so
    /home/labraham/.conda/envs/abx/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so

**Comment by pjh5** [comment]
Sorry for the delay. Are you still getting this? What OS is this?

I am unable to repro this on the few Ubuntu configurations that I tried. What is 'conda list caffe2' ?

**Comment by louisabraham** [comment]
No problem. It never worked.

    Linux version 2.6.32-504.8.1.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Wed Jan 28 21:11:36 UTC 2015

It seems now the python3-anaconda module is broken. If you cannot reproduce it, forget it, it's like legacy support and I now use a different server for my computations, I hope this server will be changed this year 😕

Sorry for the trouble and thank you for your help!
