### ISSUE TITLE
LocalResponseNorm seems mismatch with onnx

### ISSUE THREAD

**Issue by 103yiran** [pytorch/pytorch#75722]
### 🐛 Describe the bug

in [`local_response_norm`](https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L2467) function, if  `size` is even, front padding is greater than back.
```python
    if dim == 3:
        div = pad(div, (0, 0, size // 2, (size - 1) // 2))
        div = avg_pool2d(div, (size, 1), stride=1).squeeze(1)
    else:
        sizes = input.size()
        div = div.view(sizes[0], 1, sizes[1], sizes[2], -1)
        div = pad(div, (0, 0, 0, 0, size // 2, (size - 1) // 2))
        div = avg_pool3d(div, (size, 1, 1), stride=1).squeeze(1)
        div = div.view(sizes)
```
While in [onnx](https://github.com/onnx/onnx/blob/main/docs/Operators.md#LRN), the formula is square_sum[n, c, d1, ..., dk] = sum(X[n, i, d1, ..., dk] ^ 2), where max(0, c - floor((size - 1) / 2)) <= i <= min(C - 1, c + ceil((size - 1) / 2)). 
Front uses `floor`.

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-39-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.10.1+cpu
[pip3] torchaudio==0.10.1+cpu
[pip3] torchvision==0.11.2+cpu
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by fatcat-z** [comment]
Hi @103yiran ,

Are you trying to export a model which contains local_response_norm() function to ONNX? Or you are just discussing the difference of them between PyTorch and ONNX?

**Comment by 103yiran** [comment]
@fatcat-z I haven't tried conversion. I noticed the difference while reading the code. Or maybe my observation is wrong？

**Comment by fatcat-z** [comment]
> @fatcat-z I haven't tried conversion. I noticed the difference while reading the code. Or maybe my observation is wrong？

No, I don't mean your observation is wrong. In terms of torch.onnx.export() function, it won't convert the local_response_norm() function to LRN op in ONNX directly so your worries won't impact the converter at this moment.

If you are looking for the reasons why the implementations are different in PyTorch and ONNX. I'd like to suggest you to check the code history to find the author and then start a further discussion.

**Comment by 103yiran** [comment]
> No, I don't mean your observation is wrong. In terms of torch.onnx.export() function, it won't convert the local_response_norm() function to LRN op in ONNX directly so your worries won't impact the converter at this moment.

Thanks for your answer. I am not familiar with torch.onnx.export() function, can you please share more details
