### ISSUE TITLE
torch.autograd.grad needs an extra tuple when handling single outputs and is_grads_batched=True

### ISSUE THREAD

**Issue by HarborYuan** [pytorch/pytorch#75735]
### 🐛 Describe the bug

Hi, 

I am running the torch.autograd.grad for calculating sample wise gradients. However, the following intuitive implementation does not work.

```
import torch

if __name__ == '__main__':
    bmm_weight = torch.ones((8, 8), dtype=torch.float32, requires_grad=True)
    a = torch.ones((5, 8, 8), dtype=torch.float32) * torch.arange(5)[:, None, None]

    b = bmm_weight * a

    b = b.sum((1, 2))
    grads = torch.autograd.grad(b, bmm_weight, torch.eye(len(b), dtype=b.dtype, device=b.device),
                                retain_graph=True, create_graph=True, is_grads_batched=True)

    print(grads[0].shape)

```

The output is 

```
Traceback (most recent call last):
  File "/opt/project/jacob.py", line 10, in <module>
    grads = torch.autograd.grad(b, bmm_weight, torch.eye(len(b), dtype=b.dtype, device=b.device),
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 273, in grad
    return _vmap_internals._vmap(vjp, 0, 0, allow_none_pass_through=True)(grad_outputs)
  File "/usr/local/lib/python3.9/site-packages/torch/_vmap_internals.py", line 271, in wrapped
    batched_outputs = func(*batched_inputs)
  File "/usr/local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 270, in vjp
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: grad_tensors argument is expected to be a tuple, but got Tensor
```

after reviewing the source code, it seems that the codes have already handled the single tensor input situation (but did not pass into the functional function).

I acknowledge that the following modification may have a sound output,

```
-    grads = torch.autograd.grad(b, bmm_weight, torch.eye(len(b), dtype=b.dtype, device=b.device),
+    grads = torch.autograd.grad(b, bmm_weight, (torch.eye(len(b), dtype=b.dtype, device=b.device),),

```

But I think performing a simple modification to the source code can support singe-tensor input situation.

https://github.com/HarborYuan/pytorch/commit/13e4ac08ffa5d53f7f065939883c4c6cb2200f13

I would like to raise a PR if you think it is necessary.

### Versions

Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (aarch64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  7 2022, 04:11:40)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.10.104-linuxkit-aarch64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
Thanks for the report! Fix looks OK as well. We would accept a PR for that.
