### ISSUE TITLE
DISABLED test_large_cumprod_cuda_float16 (__main__.TestTorchDeviceTypeCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#75731]
Platforms: win

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_large_cumprod_cuda_float16%2C%20TestTorchDeviceTypeCUDA)).

Seems similar to https://github.com/pytorch/pytorch/issues/75726 where they both fail to allocate enough memory.

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @mruberry

**Comment by mantaionut** [comment]
I created a test PR #89747 to see if that test still fails. The CI was successful on multiple tries and there should be enough VRAM for this test so I close this issue and see if it happens again.
