### ISSUE TITLE
Make ONNX DepthToSpace op mode accessible

### ISSUE THREAD

**Issue by MrGrayCode** [pytorch/pytorch#75748]
### 🚀 The feature, motivation and pitch

In the [current implementation](https://github.com/pytorch/pytorch/blob/de18c28a4cfee826a4b11b4c37db23ac1ea53f6a/torch/onnx/symbolic_opset11.py#L205), the ONNX conversion uses `mode_s='CRD'` and there is no method to access this variable. It would be useful to access this during the conversion process (for example to change mode to 'DCR' if required).

**Comment by fatcat-z** [comment]
Could you please explain more about your ideas of why you need to access this field during the conversion? The code you provided is to make sure both PyTorch and ONNX will use the same format to handle the inpurts. In this case, it should not be adjusted.

**Comment by MrGrayCode** [comment]
I required the converted onnx model to have 'DRC' mode for further conversion/quantisation steps, hence the need to access the field. But now if I understand correctly, `PixelShuffle` uses the 'CRD' mode hence the onnx op also has the same mode? Thank you for the clarification.
