### ISSUE TITLE
Torch can not run  in Pycharm but it work in cmd

### ISSUE THREAD

**Issue by intellihachi** [pytorch/pytorch#7575]
I installed torch on windows 10 but  meet some problem 
`import torch;
import sys;
print('Python %s on %s' % (sys.version, sys.platform))
torch.cuda.is_available()`
can not run  in Pycharm but it work in cmd

![2](https://user-images.githubusercontent.com/18575285/40058306-5ee5736e-5883-11e8-94be-bce6899ff6b1.png)
![3](https://user-images.githubusercontent.com/18575285/40058308-5f2e1862-5883-11e8-9b63-45b1d05c9281.png)

![1](https://user-images.githubusercontent.com/18575285/40058305-5e996938-5883-11e8-8c2e-c7bddff58639.png)

## System Info

- PyTorch or Caffe2:PyTorch
- How you installed PyTorch ( pip): pip
- Build command you used (if compiling from source):
- OS:windows 10 
- PyTorch version:0.40
- Python version:3.6.4
- CUDA/cuDNN version:9.0

**Comment by peterjc123** [comment]
Why do you name your script torch.py? It's not a good pratice.

**Comment by apaszke** [comment]
And that is also precisely why it doesn't work. Python's module system will always favor a local `torch.py` file over the actual package when you `import torch`.
