### ISSUE TITLE
Add checkpoint_wrapper composability when FSDP module is being auto_wrapped

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#75751]
### 🚀 The feature, motivation and pitch

Current checkpoint_wrapper: requires manual wrap of FSDP module, i.e. first the module is wrapped with the checkpoint wrapper, and then FSDP wrapper is used.

Although, frequently users don't have access to the model code and can't insert wrappers on submodules and thus use FSDP's auto_wrap_policy to automatically nest FSDP instances. Since auto_wrap currently does not support adding checkpoint_wrappers to the module, this means that checkpoint_wrapper + auto_wrap cannot be used effectively. 

To fix this, we can add a `checkpoint=False` argument to FSDP constructor, and pass this into auto_wrapping. This will ensure that modules can be wrapped with checkpointing during auto_wrap.

A downside of this approach would be that activation checkpointed modules would be tightly coupled to FSDP-wrapped modules, because it would only be wrapped with the auto wrap policy decides to wrap an FSDP module. Although ideally, the optimal setup might be some sort of a solution where we might decide to wrap an FSDP module without checkpointing, or wrap a module with checkpointing but not FSDP. This can be taken as a follow up work.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by zhaojuanmao** [comment]
had second thought, auto wrap right nows usually returns a tree structure of nested wrapping, checkpoint_wrapper seems does not fit into this tree structure. How about put "checkpoint=False" argument into auto_wrap_policy instead of FSDP constructor and only apply to leaf modules for first version of implementation?
