### ISSUE TITLE
[NVFuser] Linear decomposition fails when input or weight don't have concrete shapes

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#75768]
### 🐛 Describe the bug

Ran into this assert: https://github.com/pytorch/pytorch/blob/f7e7af80e035a54f44f0668a4d84d4cf00516ac2/torch/csrc/jit/codegen/cuda/graph_fuser.cpp#L2057-L2060

There's a TODO to fix it. In this case I'm guessing we can probably just skip the given node instead of erroring out?

repro
```python
import torch

def fn(x: int):
    y = torch.zeros((x, x+2)).cuda()
    for i in range(2):
        inp = torch.rand((x, x+i)).cuda()
        weight = torch.rand((x+2, x+i)).cuda()
        bias = torch.rand((x, x+2)).cuda()
        y += torch.sin(torch.nn.functional.linear(inp, weight, bias))
    return y

fn.__disable_jit_function_caching__ = True

with torch.jit.fuser("fuser2"):
    fn_s = torch.jit.script(fn)
    fn_s(5)
    fn_s(5)
```

cc @jjsjann123

### Versions

master

**Comment by jjsjann123** [comment]
I think this one is good to be closed since we have #75770 merged.
