### ISSUE TITLE
Pytorch how to use torch.nn.functional.batch_norm ? 

### ISSUE THREAD

**Issue by qlwang25** [pytorch/pytorch#7577]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
if batch_norm is norm C channel , so input shape is (B, L, C) or (B, C, L)?
if batch_size = 5, time_Step = 10, channel = 20, how to code?
I have a mistake. 
Provide a short description.

## Code example
```
>>> a = torch.randn(5, 10, 20)
>>> m = torch.mean(a, 2)
>>> v = torch.var(a, 2)
>>> torch.nn.functional.batch_norm(a, m, v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangshen/.local/lib/python3.5/site-packages/torch/nn/functional.py", line 1194, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 10 elements not 100
```
Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
According to [the docs](https://pytorch.org/docs/master/nn.html?highlight=batchnorm#torch.nn.BatchNorm1d), the input should be (B, C, L), while the running mean and running variance should both be of size `(C,)`.

**Comment by qlwang25** [comment]
I know it .
input shape should be (B, C, L), mean and var shape be (C, )
so can write this code:
```
>>> a = torch.randn(3, 4, 5)
>>> b = a.view(4, -1)
>>> m = torch.mean(b, 1)
>>> m.size()
torch.Size([4])
>>> v = torch.var(b, 1)
>>> v.size()
torch.Size([4])
>>> torch.nn.functional.batch_norm(a, m, v)
tensor([[[ 1.5409, -1.6599,  0.0881,  1.4276, -0.3137],
         [ 1.2909, -0.6643, -0.3365,  0.3201, -0.4026],
         [-0.0069, -0.5163, -0.2968, -0.2134,  0.2119],
         [ 0.6451,  0.3104,  2.0196,  0.6562,  0.4894]],

        [[ 1.4737, -1.4932, -2.3282,  2.1031, -2.6306],
         [-0.1235,  0.9820,  0.2509, -0.2644, -0.0787],
         [ 0.0843,  1.5311, -0.1000, -0.9176,  1.2075],
         [ 0.1302, -0.5708, -0.1808,  1.4909,  1.9037]],

        [[ 0.9402, -1.5737, -0.0843, -2.9246,  0.4191],
         [ 0.1586, -1.0722, -0.0854, -1.7268, -0.8788],
         [-1.3462,  0.4903, -0.9022, -0.1871,  0.6783],
         [ 0.9612, -0.0691, -0.1111, -2.7907,  0.5322]]])

```
