### ISSUE TITLE
UserWarning when running backward on output of irfft with real input

### ISSUE THREAD

**Issue by fakufaku** [pytorch/pytorch#75781]
### 🐛 Describe the bug

🐛 When using `torch.fft.irfft` with a real input as part of a computation, when calling backward on the output, a UserWarning about the complex part being dismissed is generated. The warning is not needed I believe. Making the input complex (e.g., by adding `0j`) makes the warning go away.

The following code generates the warning.
```python
import torch

if __name__ == "__main__":

    n = 8
    x = torch.zeros(n).normal_()
    x.requires_grad = True
    z = torch.fft.irfft(x).sum()
    z.backward()
```
And here is the warning generated.
```
/home/robin/miniconda3/envs/fast_bss_eval/lib/python3.8/site-packages/torch/autograd/__init__.py:154: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at  ../aten/src/ATen/native/Copy.cpp:244.)
  Variable._execution_engine.run_backward(
```

### Versions

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.19.119-1.20200430.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-PCIE-32GB
Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torch-complex==0.4.3
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @peterbell10

**Comment by Lezcano** [comment]
@anjali411 we got a similar issue some time ago, but I don't know whether it was resolved?

I do agree that this warning is not needed. We should probably use `at::real` instead of the float cast that it seems to be used there. cc @peterbell10

**Comment by peterbell10** [comment]
I'm sure I fixed a similar autograd warning quite some time ago. Possibly a regression, or this is hitting a slightly different case.

**Comment by peterbell10** [comment]
#62262 added a new operator `_to_copy` which is used for `tensor.to`. It's backward doesn't correctly handle R->C conversions, unlike `_copy` which was the underlying operator previously. Will open a PR soon.

**Comment by chagelo** [comment]
@lezcano @fakufaku I create a model `a`, then with `input` and `output`, then do `fft` to `output` then do some operation on result of fft without any optimized parameters, then do ifft to the result, so what i do is `ifft(OP(fft(model(input))))`.

I encounter this warning, as @fakufaku mentioned, it's a choice to add `0j` to `input`, but i'm not sure, whether the final optimal model is the same as the model without adding `0j`.

**Comment by peterbell10** [comment]
@chagelo have you tried updating pytorch? Only the 1.12 major release will contain the fix for this issue. If you are using the latest release, then does the original reproducer code from this issue result in the same warning? If not, then the warning might be coming from any of the operators inside your model, so might be a different issue.

**Comment by chagelo** [comment]
@peterbell10 Yes, after updating to 1.12, the warning is not appear.

**Comment by ILoveSE** [comment]
I have observed a similar warning on `torch.fft.ifftn` in PyTorch 1.10/11.0.
And in 1.12.0, this warning does not appear.
I think this [pr #75805](https://github.com/pytorch/pytorch/pull/75805) also on `torch.fft.ifftn`.

```python
import torch

func_cls=torch.fft.ifftn

if __name__ == "__main__":

    n = 8
    x = torch.zeros(n).normal_()
    x.requires_grad = True
    z = func_cls(x).sum()
    z.backward()
```

**Comment by lezcano** [comment]
@ILoveSE PyTorch doesn't backport fixes, so it's expected these errors to be present in previous releases. Even more, as you are discovering, there may be other similar errors caused by exactly the same issue that are incidentally fixed when a given issue is fixed.
Again, all this is expected.

**Comment by ILoveSE** [comment]
> @ILoveSE PyTorch doesn't backport fixes, so it's expected these errors to be present in previous releases.

Yeah, I got it. I'm just curious whether they have the same root cause.
I have a much more clear understanding now. Thanks for your reply and explanation!

**Comment by peterbell10** [comment]
Yes, it's the same root cause. This issue effected all real-to-complex type conversions that are recorded by autograd. The backward formula is a complex-to-real cast which intentionally discards the imaginary component.

**Comment by ILoveSE** [comment]
@peterbell10 Oh, I see. Thanks a lot for your explanation!
