### ISSUE TITLE
cuda.XxxTensor.inverse, svd ... raise errors at even times

### ISSUE THREAD

**Issue by ShigekiKarita** [pytorch/pytorch#758]
I think this is a bug in magma, it happens like this

```
In [69]: x = torch.rand(5, 3)

In [70]: cx = x.cuda()

In [71]: a = cx.svd()

In [72]: a = cx.svd()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-72-e5183868ee83> in <module>()
----> 1 a = cx.svd()

RuntimeError: cuda runtime error (8) : invalid device function at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.8_1486038465652/work/torch/lib/THC/THCTensorCopy.cu:204

...

In [81]: a = cx.svd()

In [82]: a = cx.svd()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-83-e5183868ee83> in <module>()
----> 1 a = cx.svd()

RuntimeError: cuda runtime error (8) : invalid device function at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.8_1486038465652/work/torch/lib/THC/THCTensorCopy.cu:204
```

I confirmed that
+ odd times results are fine. they are equal to cpu results.
+ `torch.cuda.has_magma == True`
+ also this can be happened in `a = torch.svd(cx)` style
+ this error doesn't appear at non-lapack functions `torch.cos, torch.sin`

my enviroment is
+ Python3.6 (anaconda3-4.3.0)
+ CUDA8.0
+ GTX1080
+ CentOS6.5

**Comment by apaszke** [comment]
I can't reproduce the problem 😕 `torch.svd` works fine for me, but I have an older GPU. @soumith we're already building the binaries for 1080 cards right?

You might try doing a source install, maybe this could help.

**Comment by ngimel** [comment]
If it's a magma problem, source install is unlikely to help, because magma is installed through conda anyway.

**Comment by apaszke** [comment]
@ngimel But the error is raised inside a copy function, and there are some of these around magma calls (e.g. [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/generic/THCTensorMathMagma.cu#L327-L331)).

**Comment by ngimel** [comment]
It is only caught in a copy function, the error (invalid device function) was raised in a kernel. @ShigekiKarita, make sure you install magma-cuda80, as it is the one compiled for sm6.1 
https://github.com/pytorch/builder/blob/master/conda/magma-cuda80-2.1.0/cmakelists.patch#L41
magma-cuda75 is not compiled for 6.1. 
https://github.com/pytorch/builder/blob/master/conda/magma-cuda75-2.1.0/cmakelists.patch#L41

**Comment by apaszke** [comment]
Right, that makes sense.

**Comment by rdfong** [comment]
I seem to having this problem as well on a GTX870M which is sm_30. Would it be recommended to try installing from source as well? Perhaps there are some architecture options to change when building? Thanks!

**Comment by ezyang** [comment]
@ShigekiKarita @rdfong Do either of you know if this still happens? It's been a while and we've done many updates of magma version, and so the problem may have been fixed. I am unable to reproduce on the pytorch:     1.0.1-py3.6_cuda9.0.176_cudnn7.4.2_2 pytorch official conda release.

**Comment by ShigekiKarita** [comment]
Hi, I'm still using the same environment except for the pytorch 1.0. I could not reproduce this anymore. Thanks for revisiting this issue.
