### ISSUE TITLE
Standardize workflow job names

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#75817]
Currently we don't have any set convention for workflow job naming and so the names are not always consistent. This makes job searching and grouping difficult and harder to change in the future. We should enforce some sort of standardization and document it.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
A reference is https://ci.chromium.org/p/chromium/g/main/console. You can see that consistent naming lets them group things nicely

**Comment by ZainRizvi** [comment]
Closing as too low pri. If/once this becomes a burning issue again we'll file a new ticket
