### ISSUE TITLE
`pack` and `unpack` expects `StreamId` to use 48 bit virtual address space

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#75854]
### 🐛 Describe the bug

`pack` and `unpack` in [`c10/core/Stream.h`](https://github.com/pytorch/pytorch/blob/1c60b9aaa55866e3ed9d35431e0aa1fdb1943193/c10/core/Stream.h#L125-L167) are concatenating the `DeviceType`, `DeviceIndex` and `StreamId` into an `int64_t`. 
The assumption for this packing mechanism is that the virtual address will use 48 bit and will move the `DeviceType` and `DeviceIndex` into the upper bytes while reading the lower 48 bits from `id()`:
```
uint64_t bits = static_cast<uint64_t>(static_cast<uint8_t>(device_type()))
            << 56 |
        static_cast<uint64_t>(static_cast<uint8_t>(device_index())) << 48 |
        // Remove the sign extension part of the 64-bit address because
        // the id might be used to hold a pointer.
        (static_cast<uint64_t>(id()) & ((1ull << 48) - 1));
```
The same method then verifies this packing and raises asserts in case something failed.

While this assumption seems to be correct for the majority of CPU architectures, we are hitting an error on an `ARM Neoverse N1` CPU. 
After debugging this implementation, we noticed that ARMv8.2 implements "LargeVA" support, which uses up to 52 bits.
The recreation of the actual address will thus fail and we will run into the assert (it was great to see `assert`s there as a silent memory corruption might have been much harder to debug).

Some references:
* https://en.wikichip.org/w/images/b/b3/arm_neoverse_n1_trm.pdf
* https://opensource.com/article/20/12/52-bit-arm64-kernel
* https://developer.arm.com/documentation/101811/0102/Translation-granule
* https://developer.arm.com/documentation/101811/0101/Address-spaces-in-AArch64

Searching a bit more for this VA extension, also yields x86 implementations:
[Intel 5-level paging](https://en.wikipedia.org/wiki/Intel_5-level_paging): 
> [...] It extends the size of [virtual addresses](https://en.wikipedia.org/wiki/Virtual_address) from 48 bits to 57 bits, increasing the addressable [virtual memory](https://en.wikipedia.org/wiki/Virtual_memory) from 256 [TB](https://en.wikipedia.org/wiki/Terabyte) to 128 [PB](https://en.wikipedia.org/wiki/Petabyte). The extension was first implemented in the [Ice Lake](https://en.wikipedia.org/wiki/Ice_Lake_(microprocessor)) processors,[[2]](https://en.wikipedia.org/wiki/Intel_5-level_paging#cite_note-anandtech-13699-2) and the 4.14 [Linux kernel](https://en.wikipedia.org/wiki/Linux_kernel)[](https://en.wikipedia.org/wiki/Intel_5-level_paging#cite_note-3) adds support for it. [...]

which seems to extend it even further to 57 bits.

A workaround might be to shift the payload and reduce the range for `DeviceType` and `DeviceIndex`.
However, if we want to use the full 57 bits, it would leave only 7 bits for the type and id, which sounds too limited.

Extending the `StreamId` to a wider type or using another data structure might be alternatives if we want to support these CPU architectures.

CC @ezyang as the original author of this implementation, @mruberry, @mcarilli, @zasdfgbnm to discuss potential approaches.

### Versions

Current master build with CUDA11.6 on ARM Neoverse N1. 

cc @ngimel

**Comment by ezyang** [comment]
The proper fix is to modify the Python side API to stop treating streams as just ints. If we can do that, world's our oyster. Otherwise, we'll have to do something else, like remapping pointers outside of the range into a table that we can use to index back down to the small enough size. :/

**Comment by ngimel** [comment]
cc @emcastillo

**Comment by zasdfgbnm** [comment]
I think it is not just Python bindings. In `IValue`, we have something like
```C++
  //Stream
  IValue(c10::Stream stream)
    : tag(Tag::Stream), is_intrusive_ptr(false) {
    payload.u.as_int = stream.pack();
  }
```
And in tracer, we have
```C++
void addInputs(Node* n, const char* name, c10::Stream stream) {
  detail::genericAddInput(n, static_cast<int64_t>(stream.pack()));
}
```
I think it will not be hard to modify all of them. But I am not sure if this will break backward compatibility.

**Comment by emcastillo** [comment]
> The proper fix is to modify the Python side API to stop treating streams as just ints.

I am willing to work on this, however, I am a bit worried about backward compatibility. Maybe we can expose the `c10::Stream` struct directly through the python c API / pybind? (early morning thoughts without remembering implementation details). Any comments/insights appreciated!

**Comment by ezyang** [comment]
Exposing c10::Stream struct via python c API sounds like the appropriate thing to do. The good thing is we already do torch.cuda.Stream class for CUDA streams, which are what people mostly use, so it shouldn't be too BC breaking.
