### ISSUE TITLE
Move ninja build to pytorch-dockerfiles

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#7588]
In `.jenkins/pytorch/test.sh` we have:

```
# JIT C++ extensions require ninja.
git clone https://github.com/ninja-build/ninja --quiet
pushd ninja
python ./configure.py --bootstrap
export PATH="$PWD:$PATH"
popd
```

This shouldn't happen in the test script; we should install ninja in our Docker image and then use that installation directly.

CC @goldsborough who added it in 390d542db2bcc884c33c3a81d56576b56ede72cd

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by gchanan** [comment]
I think this is resolved, at least the ninja-build stuff is in a docker file now: `circleci/docker/common/install_ninja.sh`
