### ISSUE TITLE
[Caffe2] Building Android using script errors with ambiguous function call (stod)

### ISSUE THREAD

**Issue by ldesegur** [pytorch/pytorch#7589]
See below. Commenting stod() from caffe2/core/common.h seems to work fine.

Here is my build env:
Mac OS X 10.13.4
Android NDK 17.0.4754217

In file included from /Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.cc:1:0:
/Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h: In member function 'double caffe2::script::Token::doubleValue()':
/Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h:361:33: error: call of overloaded 'stod(std::__ndk1::string, size_t*)' is ambiguous
     double r = stod(text(), &idx);
                                 ^
/Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h:361:33: note: candidates are:
In file included from /Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h:11:0,
                 from /Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.cc:1:
/Users/laurent/Develop/pytorch/caffe2/core/common.h:206:15: note: double caffe2::stod(const string&, size_t*)
 inline double stod(const string& str, std::size_t* pos = 0) {
               ^
In file included from /Users/laurent/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__locale:15:0,
                 from /Users/laurent/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/ios:216,
                 from /Users/laurent/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/iostream:38,
                 from /Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h:4,
                 from /Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.cc:1:
/Users/laurent/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include/string:3874:30: note: double std::__ndk1::stod(const string&, size_t*)
 _LIBCPP_FUNC_VIS double      stod (const string& __str, size_t* __idx = 0);
                              ^
In file included from /Users/laurent/Develop/pytorch/caffe2/contrib/script/parser.h:2:0,
                 from /Users/laurent/Develop/pytorch/caffe2/contrib/script/compiler.cc:5:
/Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h: In member function 'double caffe2::script::Token::doubleValue()':
/Users/laurent/Develop/pytorch/caffe2/contrib/script/lexer.h:361:33: error: call of overloaded 'stod(std::__ndk1::string, size_t*)' is ambiguous

**Comment by soumith** [comment]
Fixed on master via @ljk53 's PRs
