### ISSUE TITLE
Improve FSDP model initialization time 

### ISSUE THREAD

**Issue by zhaojuanmao** [pytorch/pytorch#75893]
### 🚀 The feature, motivation and pitch

Mostly when model is large, users initialize a model on CPU first and then wrap it using FSDP either by auto wrapping or manual wrapping. 

Right now FSDP flatten and shards models on CPUs if the model is on CPU, which is not efficient. Especially if we add broadcast during initialization, the broadcast should happen on GPU for better efficiency (also default process group is NCCL). 

So proposing to improve FSDP model initialization time by: 
Option 1:  in default, we move CPU model to GPU, broadcast, flatten, shard and then move back to CPU 
Option 2: add a device_id argument, similar to DDP, we move CPU model to GPU device, broadcast, flatten, shard and keep the model on GPU device. 

This should greatly improve FSDP model initialization time when users pass a CPU model for FSDP wrapper

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by sisilmehta2000** [comment]
I was testing the FSDP code with pytorch lightning and noticed an edge case. It can be reproduced through following code:


  ```
import os
  import uuid
  
  import torch
  from pytorch_lightning import LightningModule
  from torch.distributed import launcher
  from torch.distributed.distributed_c10d import _get_default_group
  from torch.distributed.fsdp.fully_sharded_data_parallel import FullyShardedDataParallel

  class SimpleModel(LightningModule):
      def __init__(self):
          super().__init__()
          self.layer = torch.nn.Sequential(
              torch.nn.Linear(32, 32), torch.nn.ReLU(), torch.nn.Linear(32, 2)
          )
  
      def forward(self, x):
          return self.layer(x)
  
      def configure(self, pg):
          for i, layer in enumerate(self.layer):
              if i % 2 == 0:
                  self.layer[i] = FullyShardedDataParallel(layer, process_group=pg)
          self.layer = FullyShardedDataParallel(self.layer, process_group=pg)

  def _setup_on_device():
      global_rank = int(os.environ["RANK"])
      world_size = int(os.environ["WORLD_SIZE"])
      local_rank = int(os.environ["LOCAL_RANK"])
      devices = [torch.device("cuda", i) for i in [0, 1]]
      local_device = devices[local_rank]
      torch.distributed.init_process_group(
          "nccl", rank=global_rank, world_size=world_size
      )
      lightning_module = SimpleModel()
      lightning_module.configure(_get_default_group())
      lightning_module.to(local_device)
  
  def test():
      launcher_config = launcher.LaunchConfig(
          min_nodes=1,
          max_nodes=1,
          nproc_per_node=2,
          run_id=str(uuid.uuid4()),
          rdzv_backend="zeus",
          rdzv_endpoint="",
          start_method="spawn",
          monitor_interval=1,
          max_restarts=0,
      )
      launcher.elastic_launch(launcher_config, entrypoint=_setup_on_device)()

```

It fails with the error  "RuntimeError: Tensors must be CUDA and dense". 

It seems the lightning.to() -> calls apply() on the module recursively -> which calls fsdp.summon_params.
However lightning.to() is called when the model is on the CPU and fsdp.summon_params expects that the params are on the GPU. Hence causing the error.

@rohan-varma mentioned this issue which is being worked on in #75977 could help resolve the error.

**Comment by zhaojuanmao** [comment]
@sisilmehta2000 https://github.com/pytorch/pytorch/pull/75977 can definitely help, meanwhile you can construct a GPU model by yourself like this?  self.layer = torch.nn.Sequential(
            torch.nn.Linear(32, 32), torch.nn.ReLU(), torch.nn.Linear(32, 2), device=...,
        )
        
The fundamental issue is that FSDP expects a GPU model when cpu offloading is not enabled for apply()/forward()

**Comment by rohan-varma** [comment]
Fixed
