### ISSUE TITLE
Python garbage collector can deallocate a tensor, even when C++ still has strong references to it.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#75932]
### 🐛 Describe the bug

This is the underlying cause of https://github.com/facebookresearch/torchdynamo/issues/85.

Short repro:
```
import gc
import torch

gc.disable()
cpp_ref = torch.zeros(2, 2)
val = torch.zeros(2, 2)
a = [None]
b = [None, None]
a[0] = b
b[0] = a
b[1] = val
cpp_ref.grad = val
del a, b, val

import gc; gc.collect()
print(cpp_ref.grad)
```

So... what's going on?

Basically, the python garbage collector is calling `tp_clear`, which breaks the strong reference from the Python portion of the tensor to the C++ portion, even though there are still C++ uses of the tensor.

Then, later, when we access the C++ tensor and return it to Python, we think the Python object is still around. So, we try to access it. At this point, however, since the Python object has been deallocated, all bets are off. If the python object still exists in memory, then we'll get an undefined tensor. However, it's also totally possible that the spot in memory has been occupied by another Python object (hence why we were seeing fx.immutable_dicts and such), or a segfault.

I currently plan on fixing this by checking if the object is resurrectable in `tp_clear`, and if so, resurrecting it and cancelling the rest of the clear.

## Background info on Tensor resurrection
To explain what's happening, you should first listen to this podcast episode :) https://pytorch-dev-podcast.simplecast.com/episodes/pyobject-preservation 

Alternately, I will attempt to summarize it now. 

In PyTorch, a Tensor actually consists of 2 components - a Python object and a C++ object. So, when you create a tensor in Python, you actually create both of these objects. By default, the python component of the Tensor owns the C++ component of the tensor. I'll use the names PyTensor and CppTensor to refer to these components respectively.

So, this ownership structure makes sense (usually). If you have a tensor in Python, and it goes out of scope (thus deallocating the PyTensor), then of course the CppTensor should also be deallocated.

But, there's a complication here. What happens if all of the Python references to a tensor die, but there's still C++ references to the tensor? The C++ references are to the CppTensor (which will keep it alive), but since the CppTensor doesn't own the PyTensor, the PyTensor will be freed!

Originally, this was fine. We'd free the PyTensor (which doesn't contain actual storage), do stuff in C++, and then when we needed that tensor in Python again, we'd simply allocate a new PyTensor which pointed to the CppTensor. Somewhat surprising (and it resulted in surprising behavior occasionally), but acceptable.

However, with the advent of tensor subclasses, this would no longer work. If the PyObject went dead, then the entire subclass would also die. So, @ezyang made this change (https://github.com/pytorch/pytorch/pull/56017), which *preserves* the PyObject *even* when there are no more strong references to it, by using an ominous sounding technique called "resurrection".

So, what happens now is that when we call `tp_dealloc` (which is what happens when the ref count hits 0), instead of clearing out the PyTensor, we check to see if there are any C++ references to the CppTensor (i.e. Would the CppTensor be kept alive even if the PyTensor died). if there are, then we *flip* the ownership of the PyTensor and the CppTensor, and make the CppTensor own the PyTensor (which keeps it alive). This happens in a function called `THPVariable_tryResurrect`. Then, we try to use this PyTensor from Python again, we simply flip the ownership again, and let the PyTensor own the CppTensor.

## What's the problem? (Answer: Reference Cycles)
So, this is neat, but what's the issue? Well, reference counts hitting 0 aren't the only way a python object can get deallocated. If you have a reference cycle, then Python clears out your object in a different code path - the cyclic garbage collector. This garbage collector will traverse your Python objects, identify dead reference cycles, and then break the reference cycle (by calling `tp_clear` on an object)! (to allow typical reference count-based deallocation to occur).

But wait! We only check for resurrection when we *deallocate* a tensor. What if we call `tp_clear` on a PyTensor when it's part of a reference cycle, even though the CppTensor is still alive? Well, that's exactly what happens :) We call `THPVariable_clear` on a PyTensor that the Python GC thinks is dead, which kills the reference from the PyTensor to the CppTensor (https://github.com/pytorch/pytorch/blob/cdbd39ba5714d37398c261a283ede26754e1025e/torch/csrc/autograd/python_variable.cpp#L292). Then, we deallocate that PyTensor, but the CppTensor still thinks the PyTensor is alive, since the PyTensor has already lost its reference to the CppTensor and so can't clear out CppTensor's reference.

Then, when we return the CppTensor back to Python, we try to return the PyTensor that the CppTensor still thinks is alive! This can result in anything, ranging from 1. an undefined tensor being returned (if Python hasn't reclaimed that pointer for something else yet), 2. a random Python object being returned (if Python has allocated another Python object at that pointer), or 3. a segfault (who knows??).

One more note: @ezyang and @albanD actually already thought of this scenario for the original PR (see [this comment](https://github.com/pytorch/pytorch/blob/cdbd39ba5714d37398c261a283ede26754e1025e/torch/csrc/autograd/python_variable.cpp#L1528)). The exact details of the approach for handling this are a bit nuanced (and depend on the actual implementation of the Python GC), but can be summarized as "The GC can never find a reference cycle including this PyTensor if we never traverse any outgoing edges from this PyTensor 🤔 ". And this is true! If the PyTensor is part of the reference cycle, then we'll stop traversing the object when we hit it, preventing the Python GC from detecting this as part of the cycle.

**But**, what if the PyTensor is merely *owned* by a reference cycle? Python's GC algorithm doesn't guarantee that it's only going to try to break references that are *part* of the reference cycle (see https://devguide.python.org/garbage_collector/#identifying-reference-cycles). So, we can end up in a situation like

```
A = [None]
B = [None, None]
c = torch.zeros([2])
A[0] = B
B[0] = A
B[1] = c
```
Where A and B are in a reference cycle, but `c` ends up having `tp_clear` called on it first.

## What's the fix?
Well, instead of only checking for the ability to resurrect during `tp_dealloc`, we also check for the ability to resurrect during `tp_clear`. This is a bit suspicious, but I'll copy @ezyang 's comment about why this should be fine.

> Actually, I think this might be a True(TM) fix. Here is the reasoning.

> The main reason why resurrecting in tp_clear is suspicious is because CPython has already condemned an unreachable graph (containing a cycle), and will attempt to break the cycles by running tp_clear on all of the unreachable nodes. What if our Tensor (which we are about to resurrect) contains a reference to another object which is in the unreachable graph? Then we would be able to observe an object which is in a cleared state, which isn't going to look like anything good.

> BUT remember tp_traverse, which we coded to not traverse any fields when an object was resurrectable. This causes all of tensor's references to have unexplained refcounts, causing them to be considered reachable. So those objects will never be considered part of the unreachable graph, and we're saved!

> One more thing: is it OK for an object to still be live after running tp_clear? Yes. If Python is unlucky about the order it clears things, clearing one object may not actually induce deallocation of everything else. The source code explicitly handles this case:

> https://github.com/python/cpython/blob/4e661cd69164318c1f871faa476c68a04092ddc4/Modules/gcmodule.c#L1010-L1025

## Conclusion
So that's it! For future people trying to debug issues like this, I would recommend 

1. Turning off the GC (`gc.disable()`) and calling `gc.collect()` explicitly. Otherwise, random changes you make while minifying the code might cause the GC to get called in a different state, causing the bug to disappear.
2. Visualizing the GC graph. I used `refcycle` to visualize the GC graph (https://refcycle.readthedocs.io/en/latest/), which is what allowed me to finally identify the pattern that was problematic.

### Versions

N/A

cc @ezyang @gchanan @zou3519

**Comment by Chillee** [comment]
I'll add high priority :P 

Seems pretty bad that we have memory ownership issues that can result in {segfault, garbage tensors} being where the user would expect a tensor to be.

**Comment by albanD** [comment]
The resurrect in tp_clear PR will fix this right?

**Comment by Chillee** [comment]
Yes (hopefully).

At least, it fixes the example in this issue + the cases we were running into in the wild.

**Comment by Chillee** [comment]
To clarify for posterity, we are no longer resurrecting in `tp_clear` - instead we simply check for "resurrectability". If it's resurrectable we don't clear it. See the original comment for rationale.
