### ISSUE TITLE
Add distinction between Tensor and NestedTensor in python

### ISSUE THREAD

**Issue by mattangus** [pytorch/pytorch#75939]
### 🚀 The feature, motivation and pitch

As of https://github.com/pytorch/pytorch/pull/74691, the nested tensor class has been removed. From the python interface there seems to be no way to distingush between Tensor and NestedTensor. I think it would be useful to have an efficent way to determine if a tensor is nested or not.

### Alternatives

 Currently I have two work arounds:
```python
    try:
        tensor.shape
        is_nested = False
    except RuntimeError as ex:
        is_nested = "NestedTensorImpl" in str(ex)
```
or 
```python
    is_nested = "nested_tensor" in str(tensor)
```

The former is very slow because of the try except perfomace. The latter requires a copy to the CPU for the print.

cc @cpuhrsch

**Comment by cpuhrsch** [comment]
@mattangus - you can now use `is_nested`.

```
>>> a = torch.nested_tensor([torch.randn(1, 2), torch.randn(2, 3)])
>>> a.is_nested
True
>>> b = torch.randn(3, 2, 3)
>>> b.is_nested
False
```

Does this resolve your issue?

**Comment by mattangus** [comment]
Yes! Thank you!
