### ISSUE TITLE
DISABLED test_data_parallel_module_kwargs_only_empty_dict_cuda_float64 (__main__.TestDataParallelDeviceTypeCUDA)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#75973]
Platforms: rocm

This test was disabled because it is flaky on master ([recent examples](http://torch-ci.com/failure/test_data_parallel_module_kwargs_only_empty_dict_cuda_float64%2C%20TestDataParallelDeviceTypeCUDA)).

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jaglinux** [comment]
Test ran successfully after applying  https://github.com/pytorch/pytorch/pull/78824
