### ISSUE TITLE
Build PyTorch to be supported by Cuda 11.4

### ISSUE THREAD

**Issue by aliasad20** [pytorch/pytorch#75992]
### 🚀 The feature, motivation and pitch

While my PC has CUDA 11.4 installed for my nVidia and various other dependent apps run on it. Presently on the official site the PyTorch just seems compatible with CUDA 11.3 and nothing else in Cuda 11.x. Please update it so it serves the purpose to be installed  and use GPU properly.

cc @malfet @seemethere @ngimel

**Comment by kyoungseoun-chung** [comment]
I have coda version 11.6 and PyTorch is working without any problem.

But I guess by default, PyTorch is delivered with CUDA version 10.x. 

Could you install PyTorch with following command? (in the website explicitly configure CUDA version to 11.3)

```python
pip3 install torch --extra-index-url https://download.pytorch.org/whl/cu113
````

Hope this can help you.

**Comment by seemethere** [comment]
There's no plans to publish binaries for CUDA 11.4 since CUDA 11.3 binaries have been shown to work with CUDA 11.4

Closing this issue since we're not planning on building specifically for CUDA 11.4

**Comment by hygxy** [comment]
> There's no plans to publish binaries for CUDA 11.4 since CUDA 11.3 binaries have been shown to work with CUDA 11.4
> 
> Closing this issue since we're not planning on building specifically for CUDA 11.4

How about libtorch? libtorch cuda 11.3 binaries have been shown NOT to work with CUDA 11.4 [issue](https://github.com/pytorch/pytorch/issues/73829#issuecomment-1142515258)

**Comment by ashuezy** [comment]
+1 
Facing same problems with Cuda 11.4.
Looking for support.

**Comment by jamessmith90** [comment]
+1
Can you release builds for CUDA 11.4 ?

**Comment by seemethere** [comment]
Hey everyone, we have no plans to build CUDA 11.4 specific binaries, going to lock this topic
