### ISSUE TITLE
Visualizing Networks

### ISSUE THREAD

**Issue by shubhamjain0594** [pytorch/pytorch#760]
Is there any module in your pipeline or any way using which we can visualize the network. A similar function that exists in nngraph.

**Comment by soumith** [comment]
this is more of a question for discuss.pytorch.org

sergey has a gist where he creates a graph visualization

**Comment by shubhamjain0594** [comment]
Thanks Soumith. Found it.

Discussion for visualization of DNN can be found [here](https://discuss.pytorch.org/t/how-to-get-the-graph-of-your-dnn-drawn/184).
