### ISSUE TITLE
python3 -OO option does not work

### ISSUE THREAD

**Issue by A-tA-v** [pytorch/pytorch#76034]
### 🐛 Describe the bug

My scripts depend on PyTorch, although I do not use it at the moment. 
When I try optimization options, the **python3 -OO ...** fails but **python3 -O ...** is fine.
This was checked on MacOS and RedHat 7, Anaconda environment 4.12, python 3.9.12, **pytorch 1.10.2**.
The output:
```
python3 -OO my_script
Traceback (most recent call last):
 ...................................
    import torch as th
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/__init__.py", line 643, in <module>
    from .functional import *  # noqa: F403
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/functional.py", line 6, in <module>
    import torch.nn.functional as F
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/Users/albert/miniconda3/envs/qu/lib/python3.9/site-packages/torch/nn/functional.py", line 2231, in <module>
    embedding_bag.__doc__ = embedding_bag.__doc__.format(**reproducibility_notes)
AttributeError: 'NoneType' object has no attribute 'format'
```

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.10.2
[conda] blas                      1.0                         mkl
[conda] libblas                   3.9.0              13_osx64_mkl    conda-forge
[conda] libcblas                  3.9.0              13_osx64_mkl    conda-forge
[conda] liblapack                 3.9.0              13_osx64_mkl    conda-forge
[conda] mkl                       2022.0.0           hecd8cb5_105
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.22.2           py39h9d9ce41_0    conda-forge
[conda] pytorch                   1.10.2                  py3.9_0    pytorch

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
My understanding is that the `-OO` option is remove all the docstring? So it is possible that a lot of our code fails today.
We would be happy to accept a PR fixing such issues to make sure you can run pytorch with -OO.

In this case, I think we can simply check if the `__doc__` is `None` and only format it if it exists.

**Comment by vitrioil** [comment]
I can contribute here to this. Not sure how much improvement it would bring but I can check that.

I had a quick look at how __doc__ is being used:

1) Assigning to __doc__
https://github.com/pytorch/pytorch/blob/04b3313379712098183dfe5bea002a5e43b5af48/torch/nn/functional.py#L2335
>Adding None check should solve this

2)  Directly 
https://github.com/pytorch/pytorch/blob/04b3313379712098183dfe5bea002a5e43b5af48/torch/nn/modules/conv.py#L174-L175
>This will **NOT** be removed by python, this has to be programmatically set (because of format). (Maybe similar to 1. or some other way)


3) Getting __doc__ using `getattr` and performing operations on it
https://github.com/pytorch/pytorch/blob/04b3313379712098183dfe5bea002a5e43b5af48/torch/distributed/rpc/api.py#L491-L495
>This one has an assert to stop it but asserts are removed when the `-OO` flags are set so we need to move everything inside the check or replace `None` with `''`
Like: https://github.com/pytorch/pytorch/blob/3fa77fa51ac3cf627c86d0aa1fdbb71e1a922db2/torch/fx/_compatibility.py#L25

I see some asserts in test but I guess that would be irrelevant here.

I will also check if dependencies are compatible.

What do you think?

**Comment by albanD** [comment]
Thanks for looking into this.
For 1. you can indeed add a None check.
For 2. I would simply remove the `__doc__ = ` and leave that string at the top. Python will properly put it in the `__doc__` field and it will also be properly removed in optimized mode.
For 3. I think we can guard this check with `if __debug__:`.

For testing, I think it is safe to assume that testing does not run in optimized mode.
But we do want to test this not to regress in the future. You can do something similar to this test: https://github.com/pytorch/pytorch/blob/ea1901693e92266a61950ed61bfe8f6068a81b98/test/test_stateless.py#L159-L179 and make sure that import torch does work in optimized mode.

**Comment by vitrioil** [comment]
Cool.

Just one thing, for 2 removing `__doc__` and keeping it as it is will work but not if format is used.
```python
class Works:
    """I won't stay with -OO :)"""

class Problem:
    """I am not a docstring anymore {}""".format(":(")

```
Problem: https://github.com/pytorch/pytorch/blob/04b3313379712098183dfe5bea002a5e43b5af48/torch/nn/modules/conv.py#L174-L233

So we might have to keep it as it is and then after declaration do the formatting if `__doc__` exists for all occurrences.

```python
class WorkAround:
    """I am a {} docstring that won't stay with -OO :)"""

if WorkAround.__doc__:
    WorkAround.__doc__ = WorkAround.__doc__.format("formatted")

```

**Comment by albanD** [comment]
That sounds like a good plan! A bit unfortunate that we have to do that but hey!

**Comment by vitrioil** [comment]
Created: #76619. Still there's a lot of changes pending. Should I make it a draft PR?

**Comment by albanD** [comment]
Thanks for the fix!
I think we can open a new issue for the follow up improvements (as it now works, but not optimally).

Also I would be curious to discuss there the impact of the remaining docstrings.

**Comment by vitrioil** [comment]
Created #76659
