### ISSUE TITLE
Awful official IOS benchmark tutorial from pytorch.org

### ISSUE THREAD

**Issue by codgeek** [pytorch/pytorch#76033]
### 🐛 Describe the bug

The IOS benchmark tutorial  from official website does not work. 
 [https://pytorch.org/tutorials/recipes/mobile_perf.html#benchmarking](https://pytorch.org/tutorials/recipes/mobile_perf.html#benchmarking)

↓ tutorial begin
<img width="860" alt="image" src="https://user-images.githubusercontent.com/20918280/163996792-e8737c24-2cd5-4e36-b71f-e4eabe99368e.png">
↑  tutorial end

After solving some packages dependence,  after a long time of compiling I reach the stage of  compile success and setup.rb the xcode project, unfortunately, the xcode project seem  not to be  real benchmark project, there is no benchmark code  found inside. The `AppDelegate.mm` is empty. 

the android benchmark code `speed_benchmark_torch.cc` is not ported.

**This really waste a lot of time!  hope to see a real official IOS benchmark!** 

```
#import "AppDelegate.h"

@interface AppDelegate ()

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Override point for customization after application launch.
  return YES;
}

- (void)applicationWillResignActive:(UIApplication *)application {
  // Sent when the application is about to move from active to inactive state. This can occur for
  // certain types of temporary interruptions (such as an incoming phone call or SMS message) or
  // when the user quits the application and it begins the transition to the background state. Use
  // this method to pause ongoing tasks, disable timers, and invalidate graphics rendering
  // callbacks. Games should use this method to pause the game.
}

- (void)applicationDidEnterBackground:(UIApplication *)application {
  // Use this method to release shared resources, save user data, invalidate timers, and store
  // enough application state information to restore your application to its current state in case
  // it is terminated later. If your application supports background execution, this method is
  // called instead of applicationWillTerminate: when the user quits.
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
  // Called as part of the transition from the background to the active state; here you can undo
  // many of the changes made on entering the background.
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
  // Restart any tasks that were paused (or not yet started) while the application was inactive. If
  // the application was previously in the background, optionally refresh the user interface.
}

- (void)applicationWillTerminate:(UIApplication *)application {
  // Called when the application is about to terminate. Save data if appropriate. See also
  // applicationDidEnterBackground:.
}

@end

```

![image](https://user-images.githubusercontent.com/20918280/163995559-949482c9-ac6c-41d6-92c0-51116a1b6e1d.png)

### Versions

PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.19.3
Libc version: N/A

Python version: 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] onnx2pytorch==0.4.1
[pip3] torch==1.10.2
[pip3] torch-scatter==2.0.9
[pip3] torchvision==0.11.3
[conda] _tflow_select             2.3.0                       mkl    defaults
[conda] mkl                       2019.4                      233    defaults
[conda] mkl-service               2.3.0            py36h9ed2024_0    defaults
[conda] nomkl                     3.0                           0    defaults
[conda] numpy                     1.18.4                   pypi_0    pypi
[conda] numpy-base                1.19.2           py36h68fea81_0    defaults
[conda] onnx2pytorch              0.4.1                    pypi_0    pypi
[conda] tensorflow                1.15.0          mkl_py36h975b573_0    defaults
[conda] tensorflow-base           1.15.0          mkl_py36h032239d_0    defaults
[conda] torch                     1.10.2                   pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torchvision               0.11.3                   pypi_0    pypi

cc @brianjo @mruberry

**Comment by kimishpatel** [comment]
@jmdetloff is looking into this.
