### ISSUE TITLE
Re-running test jobs does not work

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#76042]
### 🐛 Describe the bug

Re-run from failed does not seem to work correctly if only test job have failed, see https://github.com/pytorch/pytorch/runs/6079730056?check_suite_focus=true which is a re-run of https://github.com/pytorch/pytorch/runs/6071290013?check_suite_focus=true

### Versions

CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Oh this might be related to https://github.com/pytorch/pytorch/commit/2ecc59086a5bc896c82f6f309d25569ec2933467
