### ISSUE TITLE
LayerNorm does not give exactly the same result on GPU vs on CPU

### ISSUE THREAD

**Issue by younesbelkada** [pytorch/pytorch#76052]
### 🐛 Describe the bug

Hi there!
`nn.LayerNorm` seem to not output exactly the same tensors when ran on CPU vs on GPU. I have seem some issues with numercial instability of `nn.LayerNorm` so I guess it might be related. Here is a snippet to reproduce the bug:
```
import torch

dtype = torch.bfloat16

layer_norm_gpu = torch.nn.LayerNorm((64,), eps=1e-05).to("cuda:0").type(dtype) # by default it's 1 everywhere
layer_norm_cpu = torch.nn.LayerNorm((64,), eps=1e-05).to("cpu").type(dtype) # by default it's 1 everywhere

assert torch.equal(layer_norm_gpu.weight.cpu(), layer_norm_cpu.weight)

with torch.no_grad():
    embeddings = torch.randn((20, 64)).type(dtype)
    embeddings_gpu = embeddings.to("cuda:0")
    embeddings_cpu = embeddings.to("cpu")

    embeddings_ln_gpu = layer_norm_gpu(embeddings_gpu)
    embeddings_ln_cpu = layer_norm_cpu(embeddings_cpu)

assert torch.equal(embeddings_ln_gpu.cpu(), embeddings_ln_cpu) # this test does not pass
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.13 (default, Mar 16 2022, 17:37:17)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.10.0+cu111
[pip3] torchaudio==0.10.0+cu111
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.1+cu111
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
Hi,

This is expected that they're not exactly the same. You can only expect them to be close I'm afraid.
More detailed doc on this is at: https://pytorch.org/docs/stable/notes/numerical_accuracy.html

**Comment by younesbelkada** [comment]
Ok I see, thanks for the quick reply!
