### ISSUE TITLE
No documentation for unpack_sequence and unpad_sequence functions

### ISSUE THREAD

**Issue by dayyass** [pytorch/pytorch#76064]
### 📚 The doc issue

torch 1.11.0 added two functions (torch.nn.utils.rnn module):
- unpack_sequence
- unpad_sequence

But there is no documentation for them except docstrings.
How could I add it?

P.S. Docstrings would be sufficient for it. 

cc @svekars @holly1238 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @zou3519 @brianjo

**Comment by dayyass** [comment]
Yesterday was torch v1.12 release and it still doesn't have documentation for unpack_sequence/unpad_sequence

**Comment by ofantomas** [comment]
What is more, function unpad_sequence does not work when padded_sequences' device is "cuda". This happens due to the fact that the tensor "idx"'s device (https://github.com/pytorch/pytorch/blob/8b29b7953a46fbab9363294214f7689d04df0a85/torch/nn/utils/rnn.py#L441) is always going to be "cpu".

**Comment by dayyass** [comment]
I'll fix it

**Comment by jbschlosser** [comment]
FYI to get the docstrings in the generated docs, the function names just need to be added to `docs/source/nn.rst`.

> What is more, function unpad_sequence does not work when padded_sequences' device is "cuda".

@ofantomas Is this true? I'm running on master and it works perfectly fine with CUDA inputs AFAICT.
