### ISSUE TITLE
Torchscript: nonexistent 'momentum' for BatchNorm

### ISSUE THREAD

**Issue by hanlint** [pytorch/pytorch#76086]
### 🐛 Describe the bug

Attempting to access the attribute `momentum` from the `BatchNorm` pytorch class results in an error. Minimal example:
```
import torch

class MinimalExample(torch.nn.Module):

    def __init__(self, batchnorm: torch.nn.BatchNorm2d):
        super().__init__()
        self.batchnorm = batchnorm

    def forward(self, x):
        self.batchnorm.momentum = 1.0
        return self.batchnorm(x)


bn = torch.nn.BatchNorm2d(num_features=64)
m = MinimalExample(batchnorm=bn)

torch.jit.script(m)
```

throws an error:
```
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
Tried to set nonexistent attribute: momentum. Did you forget to initialize it in __init__()?:
  File "minimal_example.py", line 12
    def forward(self, x):
        self.batchnorm.momentum = 1.0
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return self.batchnorm(x)
```

The Torchscript Language Reference notes that this occurs when attempting to access an attribute that is not being set during `__init__`, however, the momentum _is_ being set by the base class here: https://github.com/pytorch/pytorch/blob/bb157dd4eb21019ff396e5ce123d115914dd04a5/torch/nn/modules/batchnorm.py#L41

Is there another restriction I am unaware of?

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.0.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.9 (default, Aug  3 2021, 19:21:54)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] pytorch-lightning==1.5.10
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.10.2
[pip3] torch-optimizer==0.1.0
[pip3] torchmetrics==0.7.1
[pip3] torchvision==0.11.3
[pip3] vit-pytorch==0.27.0
[conda] Could not collect

**Comment by davidberard98** [comment]
It appears to be an issue related to polymorphism, which is unfortunately unsupported by torchscript; the problem is that `BatchNorm` is inheriting from `_NormBase`. Repro below.

However, in this case I think this wouldn't help anyway; `momentum` is marked as constant [here](https://github.com/pytorch/pytorch/blob/133c213415a147a30ebee671545e25ba7ed26c54/torch/nn/modules/batchnorm.py#L18) so even if we fix the torchscript issue, you would still run into an error from trying to modify a constant. @hanlint does that sound accurate?

```python
import torch

class Base(torch.nn.Module):
    __constants__ = ["x"]
    x: float

    def __init__(self):
        super(Base, self).__init__()
        self.x = 5.

class Inside(torch.nn.Module):
    def __init__(self):
        super(Inside, self).__init__()

    def forward(self, x):
        return x + self.x

# if you replace Inside with Base, it works.
class Outside(torch.nn.Module):
    def __init__(self, mod: Inside):
        super(Outside, self).__init__()
        self.mod = mod

    def forward(self, x):
        return self.mod.x + x

# If you replace Inside with Base, it works.
m = Outside(Inside())

x = torch.rand((2, 2))

m_s = torch.jit.script(m)
print(m_s(x) - x)
```

**Comment by hanlint** [comment]
@davidberard98 Thanks, your assessment is accurate. I will close this as this is a known unsupported feature.
