### ISSUE TITLE
The shape inference of ::LearnablePerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#76088]
### 🐛 Describe the bug

```
The shape inference of ::LearnablePerTensorAffine type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
```

Why this wanring appear when export onnx?

How to avoid it? Examples on how to add for cstomized symbolic function?

### Versions

torch1.12

**Comment by BowenBao** [comment]
Type(datatype) is important to ONNX as it is strongly typed. Here is one example of propagating for custom symbolic functions
https://github.com/microsoft/onnxruntime/blob/cbc7bd1d2a050ef0df7a4ec270b9fe6e6a2fc129/onnxruntime/python/tools/pytorch_export_contrib_ops.py#L80

**Comment by jinfagang** [comment]
@BowenBao so, it was becuase of I didn't specific type, then it says mgiht cause shape inference error? I though I need something like spefic shape here.

**Comment by BowenBao** [comment]
Both shape and datatype are preferred. I should mention both in the above comment. Many operator conversions in ONNX depends on both.

**Comment by garymm** [comment]
@jinfagang was your question answered? If so please close the issue.

**Comment by Peeta586** [comment]
how to set both shape and datatype, when i use pytorch to add  customized symbolic function, like:
class Test(Function):
.....

@staticmethod
    def symbolic(g, x):
        return g.op("ai.onnx.contrib::CustomLayer", x)

**Comment by garymm** [comment]
@Peeta586 I think you can do `setType(TensorType.get().with_sizes(...).with_dtype(...))`
Look for similar examples:
https://github.com/pytorch/pytorch/blob/5dd1c677768a94ee4c014438369c8a9f832a7e40/test/onnx/test_pytorch_onnx_shape_inference.py#L113

**Comment by Peeta586** [comment]
> 

thank you very much. by the way,  if the shape of this layer is arbitrary, how can I set it?

**Comment by Peeta586** [comment]
> @Peeta586 I think you can do `setType(TensorType.get().with_sizes(...).with_dtype(...))` Look for similar examples:
> 
> https://github.com/pytorch/pytorch/blob/5dd1c677768a94ee4c014438369c8a9f832a7e40/test/onnx/test_pytorch_onnx_shape_inference.py#L113

@garymm thank you very much. By the way, if the shape of this layer is arbitrary, how can I set it?

**Comment by Peeta586** [comment]
@garymm,  when I set shape and type like, setType(input.type().with_dtype(torch.float).with_sizes([None, None, None, None]) ), the warning message still happened, such as  "WARNING: The shape inference of ai.onnx.contrib::CustomLayer type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function."

**Comment by Peeta586** [comment]
> I'm not sure what setting a size to None actually means, so maybe that's the problem. You can look into the source code for where that message is defined to try to debug further.

Ok @garymm, Thank you very much. I have found the mesage that was written in torch/csrc/jit/passes/onnx/shape_type_inference.cpp file, but I cant understand what is meaning?   By the way  do you understand what g.op will do, why the shape inference warning happened? thank you

**Comment by Daniel-Ehrhardt** [comment]
I am facing the same problem as described in: https://github.com/pytorch/pytorch/issues/76088#issuecomment-1119181584

It seems like setting type and shape by invoking `setType()` inside the symbolic function is _not sufficient_ to make shape inference work for custom operators defined inside a custom ONNX domain.

As already mentioned by @Peeta586, this check in `shape_type_inference.cpp` is triggering the warning:

https://github.com/pytorch/pytorch/blob/8745118ccbed89f7d08ef6ca47eb9ba41cc12ea5/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1872-L1878

As a consequence of these checks, no shape information is present in the graph.

We found a workaround:
when adding our OP `custom_domain::op_name` to the set `nodeTypeReliableForTracer`, the warning disappears and the shape information (that was calculated and set inside the symbolic function) appears in the graph.

https://github.com/pytorch/pytorch/blob/8745118ccbed89f7d08ef6ca47eb9ba41cc12ea5/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1855

Obviously, patching this cpp file is not a solution in general.
And according to [the documentation](https://pytorch.org/docs/stable/onnx.html#pythonop-symbolic), this should not be required at all.

**Comment by garymm** [comment]
@Daniel-Ehrhardt please open a new issue. Thanks!

**Comment by Daniel-Ehrhardt** [comment]
> @Daniel-Ehrhardt please open a new issue. Thanks!

There is a new issue already: https://github.com/pytorch/pytorch/issues/81693

**Comment by Yang-Kaixing** [comment]
> input.type().with_dtype(torch.float).with_sizes([None, 3, 16, 16])

I have met the same problem, could you please share your modified code. It's very urgent for me, your help is greatly appreciated.
