### ISSUE TITLE
LINK ERROR compiling pytorch1.11.0 on windows with CUDA11.5 CUDNN8.2

### ISSUE THREAD

**Issue by ShiinaMitsuki** [pytorch/pytorch#76087]
### 🐛 Describe the bug

Building pytorch1.11.0  from source on windows with CUDA11.5 and CUDNN8.2 failed with LINK2019 error when compiling torch_cuda.dll and torch_cuda.lib

# Error log

[pytorch-1.11.0-cuda115-cudnn82-ninjia.txt](https://github.com/pytorch/pytorch/files/8517811/pytorch-1.11.0-cuda115-cudnn82-ninjia.txt)

# How to reproduce this?

- windows 10 with Visual Studio 2019
- install CUDA 11.5 and CUDNN 8.2 and miniconda3
- run with the following command

```
conda create -n ML3 python=3.7
conda activate ML3
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing typing-extensions
set CMAKE_INCLUDE_PATH=%path_of_mkl%\mkl\include
set LIB=%LIB%;%path_of_mkl%\mkl\lib
set MAGMA_HOME=%path_of_magma%\magma
set USE_CUDA=1
set USE_CUDNN=1
set USE_NINJIA=1
set BUILD_BINARY=1
set TORCH_CUDA_ARCH_LIST=8.0
```

comment cmake/public/cuda.cmake line 40~43, [#76010 ](https://github.com/pytorch/pytorch/issues/76010#issuecomment-1102907255)

```
python setup.py install
```

### Versions

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (MinGW.org GCC Build-2) 9.2.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: N/A
CUDA runtime version: 11.5.50
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 496.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-include               2022.0.0           haa95532_115
[conda] mkl-service               2.4.0            py37h2bbff1b_0
[conda] mkl_fft                   1.3.1            py37h277e83a_0
[conda] mkl_random                1.2.2            py37hf11a4ad_0
[conda] numpy                     1.21.5           py37h7a0a035_1
[conda] numpy-base                1.21.5           py37hca35cd5_1
```

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel

**Comment by ShiinaMitsuki** [comment]
It seems somehow the VS did not compile the `.cu` file thus cause this LINKING error.

Anyone has a clue how to fix this?

**Comment by vladimir-aubrecht** [comment]
@ShiinaMitsuki Did you manage to solve the issue at the end? I cannot reproduce it with latest stack, thou I suspect problem could be caused by commented lines in the cmake file.

**Comment by vladimir-aubrecht** [comment]
Closing as didn't manage to reproduce with latest stack and thread is stale. Feel free to create new issue if problem persists.
