### ISSUE TITLE
[Feature update] Merge `permute` and `transpose` to be more numpy friendly

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#7609]
It could be more convenient to merge the Tensor method `permute` and `transpose` to be more numpy friendly.

**Comment by ailzhang** [comment]
To confirm, the desired API should be 
```
>>> x = torch.rand(4,2,3)
>>> x
tensor([[[ 0.1083,  0.5296,  0.5103],
         [ 0.5415,  0.6124,  0.5825]],

        [[ 0.3477,  0.4046,  0.0978],
         [ 0.0821,  0.6937,  0.8154]],

        [[ 0.6801,  0.7845,  0.9509],
         [ 0.7333,  0.5554,  0.9224]],

        [[ 0.9380,  0.0834,  0.6370],
         [ 0.3868,  0.7264,  0.6967]]])
torcn.transpose(x) # numpy behavior, missing in pytorch
torch.transpose(x, (0, 1)) # numpy behavior
torch.transpose(x, 0, 1)  # current pytorch
torch.transpose(x, (2, 0, 1)) # numpy behavior, currently supported as permute in pytorch, but not transpose. 
```
Please correct me if I'm wrong. 
Btw do we want add a deprecate warning torch.permute() along with the PR?
cc: @apaszke @zou3519

**Comment by zou3519** [comment]
We shouldn't deprecate `torch.permute()`. `torch.transpose` should match numpy's behavior, which means we should be able to give it multiple dimensions. 

The difference between `torch.transpose` with multiple dimensions and `torch.permute` is that one has to specify _all_ the dimensions for `torch.permute`. For example, for a tensor:
```
x = torch.randn(4, 2, 3, 5)
x.permute(1, 2, 0, 3)  # okay
x.transpose(1, 2, 0)  # desired API
x.permute(1, 2, 0)  # should error out (it currently errors out) because we didn't specify 4 dimensions.
```

**Comment by ailzhang** [comment]
@zou3519 Hmm this doesn't align with what I saw from numpy.
```
>>> x = np.ones((1, 2, 3, 4))
>>> np.transpose(x, (1, 0, 2, 3)).shape
(2, 1, 3, 4)
>>> np.transpose(x, (1, 0, 2)).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ailzhang/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/Users/ailzhang/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
```
So if I understand correctly, the desired API is like this
```
x = torch.randn(4, 2, 3, 5)
x.transpose().shape() # should return (5, 3, 2, 4), as np.transpose(x).shape = (4, 3, 2, 1)
x.transpose((1, 2, 0, 3)) # should work like a permute
x.transpose((1, 2, 0)) # should error out, like numpy behavior above
```

**Comment by ailzhang** [comment]
The current torch.transpose() works more like [numpy.swapaxes().](https://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html)  We could rename the current transpose to swapaxes and slightly modify permute() behavior and make it a new transpose().

**Comment by ailzhang** [comment]
Yep the only missing feature is `x.transpose()` which defaults to reverse all dimensions. This is in numpy but not our `permute`. Should be easy to add.  
Agreed on the changing API is confusing, but keeping them is also confusing for new users. Now we have two options. 
1. Rename `permute` to `transpose` and `transpose` to `swapaxes` to match numpy behavior. Add x.transpose() API to `transpose`. So everything matches numpy.
2. Update our doc saying `permute` is `numpy.transpose` and `transpose` is `numpy.swapaxes`. Add x.permute() API to `permute` to match `numpy.transpose` behavior. Sounds confusing to new users but is friendly to existing users. 
cc: @soumith @apaszke

**Comment by apaszke** [comment]
I think I agree with @zou3519. There are too many downsides of changing this API compared to benefits. If we were doing a single big jump to the NumPy API then ok, but changing only those two will only be confusing.

**Comment by ailzhang** [comment]
Closing the issue based on discussion above.

**Comment by kylemcdonald** [comment]
just wanted to chime in to say i've gotten comfortable with the numpy-likeness of pytorch, so this really tripped me up today. if there was a push to make pytorch even more numpy-like, that would be really helpful 👍

**Comment by boeddeker** [comment]
Is there a counterpart to `numpy.transpose(x)` (or `x.T`) for more than two dims?
Or am I forced to use `x.permute([2, 1, 0])`?
