### ISSUE TITLE
Address out of range for architecture x86_64

### ISSUE THREAD

**Issue by erikbylow-vol** [pytorch/pytorch#76094]
### 🐛 Describe the bug

When trying to install Pytorch on my Mac by following the instructions I get

```
ld: in lib/libnnpack.a(conv1x1.py.o), section __TEXT/__const address out of range for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

What I did:
```
conda create --name test-pytorch
conda install astunparse numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
conda install pkg-config libuv
```

```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
# if you are updating an existing checkout
git submodule sync
git submodule update --init --recursive --jobs 0
```

````
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
````
I also tried
```
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
MACOSX_DEPLOYMENT_TARGET=12.0 CC=clang CXX=clang++ python setup.py install
```

Both approaches gave the same error.

System:
- xcode-select version 2395.
- Version: macOS Monterey 12.3.1 (21E258)
- MacBook Pro (16-inch, 2019)
- Processor: 2,6 GHz 6-Core Intel Core i7
- memory: 16 GB 2667 MHz DDR4

### Versions
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[conda] mkl                       2022.0.0           hecd8cb5_105  
[conda] mkl-include               2022.0.0           hecd8cb5_105  
[conda] numpy                     1.21.5           py39h9c3cb84_1  
[conda] numpy-base                1.21.5           py39he782bc1_1

cc @ezyang @seemethere @malfet @albanD

**Comment by Demborg** [comment]
I am running the same environment and get the same issue. Any insight would be very appreciated

**Comment by erikbylow-vol** [comment]
Update: In another repo I get the same error when trying to link to pytorch etc. There I made a minimal case and managed to build when I removed linkning to libtorch_cpu.a.

I can see that we have `libtorch_cpu.dylib` in the `setup.py` script. Maybe that is the cause of the error?

**Comment by erikbylow-vol** [comment]
```
lipo -info libnnpack.a   
Non-fat file: libnnpack.a is architecture: x86_64
```
```
lipo -info libXNNPACK.a
Non-fat file: libXNNPACK.a is architecture: x86_64
```
```
lipo -info libtorch_cpu.a
Non-fat file: libtorch_cpu.a is architecture: x86_64
```

Looks like they are built with the correct architecture.

**Comment by erikbylow-vol** [comment]
More progress, from local minimal case:

`ccache /usr/local/opt/ccache/libexec/clang++ -O2 -g -DNDEBUG -O3 -DVOLUMENTAL_DEBUG_DUMPER=1 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -arch x86_64 CMakeFiles/app_template.dir/app_template.cpp.o -o ../../../installdir_mac_relwithdebinfo/bin/app_template -Wl,-force_load,/Users/erikbylow/Code/Reconstruction/komb/thirdparty_mac_clang/installdir/lib/libtorch_cpu.a ../../../thirdparty_mac_clang/installdir/lib/libeigen_blas.a ../../../thirdparty_mac_clang/installdir/lib/libXNNPACK.a ../../../thirdparty_mac_clang/installdir/lib/libpytorch_qnnpack.a ../../../thirdparty_mac_clang/installdir/lib/libpthreadpool.a ../../../thirdparty_mac_clang/installdir/lib/libnnpack.a`

fails. `app_template.cpp` is just a hello world program.

If `force_load` is removed, then it builds.

**Comment by Den163** [comment]
The same story with PyTorch 1.10.0. The error appears when I'm trying to build with Apple clang 13.1.6 (Xcode Command Line Tools 13.3). But all works correctly if I build it with Apple clang 13.0 (Xcode Command Line Tools 13.2.1)

**Comment by erikbylow-vol** [comment]
Nice, worked for me as well. Is this a bug somewhere or what is the exact problem? I drawback is that XCode needs to be up to date with new iOS versions.

**Comment by dbl001** [comment]
Which version of Apple Clang worked? 13.0.0 or 13.0.1?  Are you on Monterey 12.4?

**Comment by kulinseth** [comment]
Filed an issue: https://github.com/Maratyszcza/PeachPy/issues/119

**Comment by malfet** [comment]
This issue has been fixed in PeachPy a while back by https://github.com/Maratyszcza/PeachPy/pull/85 but pinned version of PeachPy that PyTorch is using has not been updated in a very long time
