### ISSUE TITLE
DISABLED test_multiple_joinable_disable (__main__.TestJoin)

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#76109]
Platforms: rocm 

This test was disabled because it is flaky on master ([recent examples](http://torch-ci.com/failure/test_multiple_joinable_disable%2C%20TestJoin)).

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jaglinux** [comment]
This test is passing on ROCm 5.1 (ran the test in loop)
cc @jithunnair-amd @jeffdaily

**Comment by janeyx99** [comment]
:o we can try closing this then

**Comment by jeffdaily** [comment]
Closing based on recent comments.
