### ISSUE TITLE
No clear answer to issue from torch._C import * (ImportError: DLL load failed: The specified module could not be found. #4518

### ISSUE THREAD

**Issue by dougedmunds** [pytorch/pytorch#7613]
Comments to 4518 have multitude of suggestions, but no clear resolution. 

I am on Win10 no CUDA

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

import torch
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\dae\AppData\Local\Programs\Python\Python36\lib\site-packages\torch_init_.py", line 78, in 
from torch._C import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by apaszke** [comment]
Please don’t create duplicate issues. If you believe the other one should be reopened please comment there.
