### ISSUE TITLE
Replace `RuntimeError` by custom exception for unsupported ONNX operators during export

### ISSUE THREAD

**Issue by thiagocrepaldi** [pytorch/pytorch#76155]
### 🐛 Describe the bug

During `torch.onnx.export()`, `RuntimeError` [is](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_helper.py#L360-L387) raised when the ONNX converter need to express that a specific operator is not supported.

`RuntimeError` can also be raised due to a legitimate user (within training script) error or an implementation bug within a symbolic operator implementation. Up to today, both scenarios are mixed, and it is up to the user to distinguish whether this is a PyTorch (and report a bug) or their own (and fix it). Possibly a PyTorch bug would be filed, causing unnecessary noise to all. 

After https://github.com/pytorch/pytorch/pull/74759, when `operator_export_type=ONNX_ATEN_FALLBACK` and a `RuntimeError` is raised for whatever reason, ONNX exporter will interpret `RuntimeError` as an unsupported operator and will emit ATen operator (instead of raising a possible implementation bug). 

### Versions

All pytorch versions

**Comment by justinchuby** [comment]
Replacing RuntimeError sounds like a good thing to do to me without cons. For other types of errors, (TypeError, ValueError) I think it is more pythonic to use them or create subclasses of them?

**Comment by thiagocrepaldi** [comment]
From Justin at https://github.com/pytorch/pytorch/pull/87245#discussion_r1003883909, a suggestion on how to handle exceptions:

"Giving it a second thought, I actually like the idea of rethrowing now. In most cases, we just catch and set a default, so nothing actually gets thrown to users.

In cases where we do want to throw, the value can be added to the error with the raise xxx from xxx syntax, and users will get a OnnxExporterError to handle, with context.

But I agree it is tricky. For example, if from_value throws in a place where we don't expect it to and thus do not have error handling code, a user will see ValueError, which is what we don't want like you mentioned.

Keeping this as is SGTM for this PR"

**Comment by thiagocrepaldi** [comment]
> Replacing RuntimeError sounds like a good thing to do to me without cons. For other types of errors, (TypeError, ValueError) I think it is more pythonic to use them or create subclasses of them?

Let's split the exception use in two scenarios:
1) `torch.onnx` implementor needs to manually call `raise ...`:

Here is mainly where the original issue focus, especially for `operator_export_type=OperatorExportType.ONNX_ATEN_FALLBACK`. The ATen fallback needs to distinguish 1) an actual runtime error or 2) a symbolic/helper error informing we cannot express a particular operator/input with ONNX only operators - maybe because of a combination of inputs (e.g. an input tensor with unknown rank and an index with negative number). 

For 1), we want the exception to reach the user but for 2), we want to emit an org.pytorch.aten::Aten operator instead and supress the incoming exception. Having native exceptions being raised by ourselves will make impossible for the fallback mechanism to distinguish 1) and 2) for several operator/input combination. RuntimeError was an example, but if a helper raises `ValueError`, how can we distinguish this from an error on user script? 

2) An external dependency (either from `torch` or another `module`) raises:

Letting an external dependency raise an exception means that we didn't handle an internal error correctly, leading to a possibly random, error message to the final user, that has no idea what that dependency error message is talking about. If we call something, we should handle their errors by correcting the behavior or issuing a friendly message to the user, without leaking third-party stuff

**Comment by justinchuby** [comment]
What are some concrete cases when we want to emit an error? Would we not want to fallback in those cases, if those errors are only local to some ops?

**Comment by shubhambhokare1** [comment]
@thiagocrepaldi Does @BowenBao's SARIF work contribute to fixing this issue?

**Comment by thiagocrepaldi** [comment]
SARIF is for diagnosing. this issue is about safe guarding behavior on the exporter, to distinguish between exporter intentional error raising to the user vs unexpected error coming from implementation. 

This is an item that was on "design discussion bucket". Not sure why it is on the stale list

**Comment by shubhambhokare1** [comment]
@thiagocrepaldi Will just keep this as is then for now.

**Comment by thiagocrepaldi** [comment]
Closing as we don't plan to add new features to torch.onnx.export
