### ISSUE TITLE
Check batch size possible

### ISSUE THREAD

**Issue by raels0** [pytorch/pytorch#7616]
I apologise if this is obvious, but I wanted to check why it isn't verified that batch_size is less than the dataset size when initialising a DataLoader (e.g. too obvious - boundary error will be raised in the end either way)?

https://github.com/pytorch/pytorch/blob/c425d0350b9d4a4891eeb47c06ace1efb53da508/torch/utils/data/dataloader.py#L454

**Comment by apaszke** [comment]
Well it's just an extremely uncommon error. Datasets are usually so big that no one uses batches this large, and if you want to process the whole dataset in a single step, then why do you need a data loader?

**Comment by apaszke** [comment]
But feel free to send a PR if you feel that would be useful!

**Comment by SsnL** [comment]
But arguably one can have batch_size > len(dataset). It should just return everything in 1 batch.

**Comment by raels0** [comment]
That's reasonable and after testing, that is exactly what happens.
