### ISSUE TITLE
DISABLED test_multiple_joinables (__main__.TestJoin)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#76162]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_multiple_joinables%2C%20TestJoin)).

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jaglinux** [comment]
This test is passing on ROCm 5.1 (ran the test in loop)
cc @jeffdaily

**Comment by jeffdaily** [comment]
Closing based on recent comments.
