### ISSUE TITLE
stop removing old cuda support completely while keeping every small update to recent cuda online

### ISSUE THREAD

**Issue by 2blackbar** [pytorch/pytorch#76168]
### 🚀 The feature, motivation and pitch

this is some total bullshit what you do, i have to tinker every few months to get enviroments installed cause you keep removing files and keep them hidden on some obscure servers away from public to see, how about keeping the damn links to old versions on main site .
a lot of people have this issue and you keep doing it again and again, and AGAIN
how unorganized are you ? you need some help with storing old versions , thats the reason you keep removing old ones ? people still use cards that support them and still use ai envs that supports ONLY OLD VERSIONS, so stop shitting on peoples work !

### Alternatives

get some better hosting, you have funds for that

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by seemethere** [comment]
Firstly, I think you should understand that the people who work on this are real people and that we should treat conversations surrounding this topic as if you are talking to real people.

Secondly, can you provide us with some details surrounding your problem?

1. What commands are you using to install?
2. What CUDA version are you using?

**Comment by seemethere** [comment]
Since we haven't had a response in the last couple of weeks I'm going to consider this issue closed. Feel free to re-open if / when you add more context to this issue so we can help to resolve your problem
