### ISSUE TITLE
torch.cuda.mem_get_info ignores device

### ISSUE THREAD

**Issue by jjcmoon** [pytorch/pytorch#76224]
### 🐛 Describe the bug

When calling `torch.cuda.mem_get_info` I always get the result for the current device, regardless of what argument I'm passing.
Example:
```
>>> import torch
>>> [torch.cuda.mem_get_info(i) for i in range(3)]
[(8732147712, 11554717696), (8732147712, 11554717696), (8732147712, 11554717696)]
```
I am able to get correct results by using a device context:
```
 >>> def mem_get_info(device):
...     with torch.cuda.device(device=device):
...         return torch.cuda.mem_get_info()
... 
>>> [mem_get_info(i) for i in range(3)]
[(8732147712, 11554717696), (4178444288, 11554717696), (8744402944, 11552096256)]
```

### Versions

PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.16.5
Libc version: glibc-2.27

Python version: 3.8.12 (default, Jan 15 2022, 18:39:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-40-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 470.82.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] torch==1.10.0+cu102
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==2.0.3
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.12
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.10.0+rocm4.1
[pip3] torchio==0.18.65
[pip3] torchvision==0.11.1+cu102
[conda] Could not collect

cc @ezyang @gchanan @zou3519

**Comment by mruberry** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/69640.
