### ISSUE TITLE
[ONNX] Remove the function _graph_constant in utils if not needed

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#76254]
### 🚀 The feature, motivation and pitch

Four years ago in https://github.com/pytorch/pytorch/blob/ea8a0184b76088c477c7cef4fe36d683d57fd880/torch/onnx/utils.py#L1206: We might not need this anymore, since most scalars now show up as tensors

**Comment by thiagocrepaldi** [comment]
@justinchuby are you still think this is something we should handle? If not, feel free to close. will leave open for visibility

**Comment by justinchuby** [comment]
I think this is done!
