### ISSUE TITLE
Module 'Bottleneck' has no attribute 'conv2_offset'

### ISSUE THREAD

**Issue by liyuyuan6969** [pytorch/pytorch#76271]
### 🐛 Describe the bug

# describe
hai,guys,I hava a [dbnet model](https://github.com/MhLiao/DB/blob/master/backbones/resnet.py)，I want convert this pytorch model to torchScript use  `torch.jit.script` function,before this,I have load and inference dbnet successfully on my computer,so i add `torch.jit.script` in my code and run again,it shows err infomation above:Module `'Bottleneck' has no attribute 'conv2_offset'` and can't find self.conv2_offset

# have done
so i check Bottleneck and find it is relations to `self.with_dcn` and `self.with_modulated_dcn`, i print them,and find top three use conv2 and others use dcn,the print info shows model should works well,but not,I don't know if there is a syntax problem or jit bug,so i report its a bug,i really hope you can help me,thanks!

```
class Bottleneck(nn.Module):
    expansion = 4
    def __init__(self, inplanes, planes, stride=1, downsample=None, dcn=None):
        super(Bottleneck, self).__init__()
        self.with_dcn = dcn is not None
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
        self.bn1 = BatchNorm2d(planes)
        fallback_on_stride = False
        self.with_modulated_dcn = False
        if self.with_dcn:
            fallback_on_stride = dcn.get('fallback_on_stride', False)
            self.with_modulated_dcn = dcn.get('modulated', False)
        if not self.with_dcn or fallback_on_stride:
            self.conv2 = nn.Conv2d(planes, planes, kernel_size=3,
                                   stride=stride, padding=1, bias=False)
        else:
            deformable_groups = dcn.get('deformable_groups', 1)
            if not self.with_modulated_dcn:
                from models.dcn import DeformConv
                conv_op = DeformConv
                offset_channels = 18
            else:
                from models.dcn import ModulatedDeformConv
                conv_op = ModulatedDeformConv
                offset_channels = 27
            self.conv2_offset = nn.Conv2d(
                planes, deformable_groups * offset_channels,
                kernel_size=3,
                padding=1)
            self.conv2 = conv_op(
                planes, planes, kernel_size=3, padding=1, stride=stride,
                deformable_groups=deformable_groups, bias=False)
        self.bn2 = BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * 4, kernel_size=1, bias=False)
        self.bn3 = BatchNorm2d(planes * 4)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride
        self.dcn = dcn
        self.with_dcn = dcn is not None
       print("with_dcn:{} with_modulated_dcn:{}".format(self.with_dcn,self.with_modulated_dcn))

    def forward(self, x):
        residual = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        # out = self.conv2(out)
        if not self.with_dcn:
            out = self.conv2(out)
        elif self.with_modulated_dcn:
            offset_mask = self.conv2_offset(out)
            offset = offset_mask[:, :18, :, :]
            mask = offset_mask[:, -9:, :, :].sigmoid()
            out = self.conv2(out, offset, mask)
        else:
            offset = self.conv2_offset(out)
            out = self.conv2(out, offset)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            residual = self.downsample(x)

        out += residual
        out = self.relu(out)

        return out
```

# images
`self.with_dcn` and `self.with_modulated_dcn` infomation

![image](https://user-images.githubusercontent.com/53716679/164888540-668a12b8-8153-4fa4-bd16-dce0e61f3096.png)

err info

![image](https://user-images.githubusercontent.com/53716679/164888701-853e0c1c-117e-41a4-a438-93e2594814bd.png)

### Versions

Collecting environment information...
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Alibaba Cloud Linux (Aliyun Linux) release 2.1903 LTS (Hunting Beagle)  (x86_64)
GCC version: (GCC) 5.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.19.91-24.1.al7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: A10
Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.3.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.3.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.3.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.3.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.3.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.3.3
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.7.1+cu110
[pip3] torch-blade==3.21.0+1.7.1.cu110
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cu110
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.7.1+cu110              pypi_0    pypi
[conda] torch-blade               3.21.0+1.7.1.cu110          pypi_0    pypi
[conda] torchaudio                0.7.2                    pypi_0    pypi
[conda] torchvision               0.8.2+cu110              pypi_0    pypi

**Comment by davidberard98** [comment]
AFAIK this is expected with JIT. This is what happens:

1) you construct a Bottleneck() object with parameters such that self.conv2d_offset is never initialized
2) you try to script it. At this time, it will transform the python code from forward() into torchscript. It notices that self.conv2d_offset doesn't exist in the Bottleneck() object.

To fix this, one option is to create a default value of conv2d_offset so that conv2d_offset will always be available, even if you never use it.

**Comment by liyuyuan6969** [comment]
1.i understand you means whether executed `else` or not,i have to define conv2d_offset variable so torchScript can find it in forward() function?
2.and i want to know whether torchScript support dcn which need compile c++ and cu part and call in python.i check dcn code and find it is a nn.Module which call torch.autograd.Function in forward and then call c++ interface in torch.autograd.Function.

**Comment by davidberard98** [comment]
1. yes
2. I'm not familiar with what DCN is. But you can add custom ops, e.g. https://pytorch.org/tutorials/advanced/cpp_extension.html
3. Not quite sure what error you're talking about here. It sounds like an issue with yolo, you can open an issue there if you need changes in their models.
