### ISSUE TITLE
[ONNX] About custom operator convert PreciseRoIPooling to ONNX

### ISSUE THREAD

**Issue by davidyang180** [pytorch/pytorch#76274]
## Issue description
I want to speed up the model in the project, but the model contains the prroi pooling library compiled by the third party. Through consulting the documents, I learned that custom operators can be added for conversion, but onnx is still cann't export after simple implementation. How can I convert prroi pooling to onnx?(PreciseRoIPooling with dynamically linked C compiler library)

The following is the implementation details of the custom operator for reference.

## Code example

```
import torch
import torch.autograd as ag

__all__ = ['prroi_pool2d']


_prroi_pooling = None


def _import_prroi_pooling():
    global _prroi_pooling

    if _prroi_pooling is None:
        try:
            from os.path import join as pjoin, dirname
            from torch.utils.cpp_extension import load as load_extension
            root_dir = pjoin(dirname(__file__), 'src')

            _prroi_pooling = load_extension(
                '_prroi_pooling',
                [pjoin(root_dir, 'prroi_pooling_gpu.c'), pjoin(root_dir, 'prroi_pooling_gpu_impl.cu')],
                verbose=True
            )
        except ImportError:
            raise ImportError('Can not compile Precise RoI Pooling library.')

    return _prroi_pooling


class PrRoIPool2DFunction(ag.Function):
    @staticmethod
    def forward(ctx, features, rois, pooled_height, pooled_width, spatial_scale):
        _prroi_pooling = _import_prroi_pooling()

        assert 'FloatTensor' in features.type() and 'FloatTensor' in rois.type(), \
                'Precise RoI Pooling only takes float input, got {} for features and {} for rois.'.format(features.type(), rois.type())

        pooled_height = int(pooled_height)
        pooled_width = int(pooled_width)
        spatial_scale = float(spatial_scale)

        features = features.contiguous()
        rois = rois.contiguous()
        params = (pooled_height, pooled_width, spatial_scale)

        if features.is_cuda:
            output = _prroi_pooling.prroi_pooling_forward_cuda(features, rois, *params)
            ctx.params = params
            # everything here is contiguous.
            ctx.save_for_backward(features, rois, output)
        else:
            raise NotImplementedError('Precise RoI Pooling only supports GPU (cuda) implememtations.')

        return output

    @staticmethod
    def backward(ctx, grad_output):
        _prroi_pooling = _import_prroi_pooling()

        features, rois, output = ctx.saved_tensors
        grad_input = grad_coor = None

        if features.requires_grad:
            grad_output = grad_output.contiguous()
            grad_input = _prroi_pooling.prroi_pooling_backward_cuda(features, rois, output, grad_output, *ctx.params)
        if rois.requires_grad:
            grad_output = grad_output.contiguous()
            grad_coor = _prroi_pooling.prroi_pooling_coor_backward_cuda(features, rois, output, grad_output, *ctx.params)

        return grad_input, grad_coor, None, None, None


    @staticmethod
    def symbolic(g, features, rois, pooled_height, pooled_width, spatial_scale):
        return g.op("::PrRoIPool2DFunction", features, rois, pooled_height, pooled_width, spatial_scale)


prroi_pool2d = PrRoIPool2DFunction.apply
```
Then I encountered this problem again. What caused this?
![image](https://user-images.githubusercontent.com/45596935/164953373-8e69d84f-088d-47bb-a4d3-c87b1cf4672a.png)

## System Info
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-109-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 11.2.152
- Versions of any other relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py36he8ac12f_0
[conda] mkl_fft                   1.3.0            py36h54f3939_0
[conda] mkl_random                1.1.1            py36h0573a6f_0
[conda] numpy                     1.19.2           py36h54aff64_0
[conda] numpy-base                1.19.2           py36hfa32c7d_0
[conda] pytorch                   1.10.1          py3.6_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.1               py36_cu113    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.11.2               py36_cu113    pytorch

**Comment by BowenBao** [comment]
hi @davidyang180 , it appears your arguments `pooled_height`, `pooled_width`, `spatial_scale` are python numbers. How to pass them in the symbolic depends on whether these arguments are `inputs` or `attributes` to your custom operator.

If they are expected as `inputs`, you will need to wrap them inside an ONNX Constant node such that to insert them into the IR graph.
e.g.
`pooled_height = g.op("Constant", value_t=torch.tensor(pooled_height))`

Otherwise if they are expected as `attributes`, you will pass it by
`return g.op("::PrRoIPool2DFunction", features, rois, pooled_height_i=pooled_height, ...)`, where `_i` indicates it is attribute of type int.

**Comment by BowenBao** [comment]
@davidyang180 it is likely due to old opset where Slice only takes 1 input. Please try exporting with newer opset version, e.g 14. And btw, did you need to create Slice node in your custom symbolic function?

**Comment by davidyang180** [comment]
> @davidyang180 it is likely due to old opset where Slice only takes 1 input. Please try exporting with newer opset version, e.g 14. And btw, did you need to create Slice node in your custom symbolic function?

Hi! I tried exporting with a newer opset version, but it still gave the same error. Currently, I don't create a slice in custom symbolic function, is it necessary to create such a slice at present? How should this be achieved?
![image](https://user-images.githubusercontent.com/45596935/165704159-9a3c83eb-549f-4b2d-bfcc-efb202b39986.png)

**Comment by BowenBao** [comment]
@davidyang180 I noticed that you are using torch 1.7. If this version is not specifically required, I'd recommend you try with latest pytorch (1.11). It is very likely that the slice issue was a bug back then that has already been fixed.

**Comment by davidyang180** [comment]
> @davidyang180 I noticed that you are using torch 1.7. If this version is not specifically required, I'd recommend you try with latest pytorch (1.11). It is very likely that the slice issue was a bug back then that has already been fixed.

Hi! I didn't update my environment configuration in time. The above error is that I changed to torch 1.10.1 and ran with opset version 14. Is torch version 1.10 not enough? Does it need to be updated to 1.11?

**Comment by BowenBao** [comment]
@davidyang180 please give a try with latest pytorch-nightly. If the issue still persists, please share a runnable repro example for us to take a look. Thanks.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
