### ISSUE TITLE
[docs] Tensor.permute docs missing

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#7627]
https://pytorch.org/docs/master/tensors.html?highlight=permute#torch.Tensor.permute

**Comment by ydawei** [comment]
I also found this issue when I tried to swap axes of a tensor. I googled an older doc [here](http://pytorch-zh.readthedocs.io/en/latest/_modules/torch/tensor.html) in the source code. Hope it helps.

**Comment by Anirudh257** [comment]
@ydawei Even that link is missing. Can you point out to the new link?
