### ISSUE TITLE
qint8 support for activation of Eager mode QAT

### ISSUE THREAD

**Issue by Kentaro-Mikami** [pytorch/pytorch#76298]
### 🚀 The feature, motivation and pitch

We have tried to use Eager mode QAT of PyTorch 1.10.1.
We want to use qint8 for activcvation dtype, but we got a error.
-------------- Error Message --------------
File "C:\Python\Python36\lib\site-packages\torch\nn\intrinsic\quantized\modules\conv_relu.py", line 86, in forward
    input, self._packed_params, self.scale, self.zero_point)
RuntimeError: expected scalar type QUInt8 but found QInt8
-------------- Error Message --------------
My understanding is that qint8 for activation dtype has not been supported yet.
Do you have plan to support qint8 for activation dtype?
Thank you.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
We might also be able to help more if you give some more context, for example, why doesn't quint8 suit your needs in this case?

**Comment by kimishpatel** [comment]
So we already added support for symmetric qat (qint8 activation with qint8 weights with value restriction + zero point=0). @digantdesai landed the change here https://github.com/pytorch/pytorch/pull/74507. There are many operators which are not fully supported but conv, linear and add are and likely a whole bunch others have non-performant implementations. If you can quantize your model with this config then you can try to run it via qnnpack quantized engine. cc: @jerryzh168

**Comment by aimen123** [comment]
i have a question the same,  i need you help @jerryzh168 @mrshenli @kimishpatel @HDCharles @Kentaro-Mikami
