### ISSUE TITLE
Unexpected error when running autograd.grad with is_grads_batched=True

### ISSUE THREAD

**Issue by lucascamaradb** [pytorch/pytorch#76290]
### 🐛 Describe the bug

When running `autograd.grad` with `is_grads_batched=True` a shape mismatch error, even when I don't have any mismatch.

Sample code:

```
import torch
import torch.nn as nn
from torch.autograd import grad

batch_sz = 10
inp_sz = 5
z_sz = 2

f = nn.Sequential(nn.Linear(inp_sz, 50),
                  nn.Sigmoid(),
                  nn.Linear(50,z_sz))

x = torch.randn(batch_sz,inp_sz).requires_grad_()
y = f(x)

v = torch.zeros(batch_sz,z_sz, dtype=torch.float)
v[:,0] = 1.
v = v.requires_grad_()

dy = grad(y,x,grad_outputs=v, create_graph=True, is_grads_batched=True)[0]
```

Outputs:

```
RuntimeError: If `is_grads_batched=True`, we interpret the first dimension of each grad_output as the batch dimension. The sizes of the remaining dimensions are expected to match the shape of corresponding output, but a mismatch was detected: grad_output[0] has a shape of torch.Size([10, 2]) and output[0] has a shape of torch.Size([10, 2]). If you only want some tensors in `grad_output` to be considered batched, consider using vmap.
```

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-35-generic-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 with Max-Q Design
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py38_cu113    pytorch
[conda] torchvision               0.12.0               py38_cu113    pytorch

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
When you specify `batched_grads=True`, only the grad_out is intepreted as having an additional batch dimension. For example if  output has a shape of `(2,)` then grad_out should have a shape of `(B, 2)`. If you'd like to batch the forward as well, you should checkout `vmap` in [functorch](https://github.com/pytorch/functorch.)
