### ISSUE TITLE
No nn.Bilinear

### ISSUE THREAD

**Issue by ebetica** [pytorch/pytorch#763]
It would be great if this was ported into autograd!

https://github.com/pytorch/pytorch/blob/79f5bf84e54d57a4c81912aeedb0b8a27f97c27e/torch/nn/modules/linear.py#L62

**Comment by soumith** [comment]
Adding context to the task for community members to pick it up. ( cc: @uridah )

nn.Bilinear refers to [this Lua-Torch layer](https://github.com/torch/nn/blob/master/doc/simple.md#nn.Bilinear)

It computes a Bilinear transformation `\forall k: y_k = x_1 A_k x_2 + b`.

To contrast this, a Linear transformation is `\forall k: y_k = A_k x_1 + b`.

The source code for it is [here](https://github.com/torch/nn/blob/master/Bilinear.lua) and has been transpiled to `legacy.nn` of PyTorch [here](https://github.com/pytorch/pytorch/blob/79f5bf84e54d57a4c81912aeedb0b8a27f97c27e/torch/legacy/nn/Bilinear.py)

This task is to implement `nn.Bilinear` under the `nn` package (not `legacy.nn`) which uses autograd.

Doing the basic PyTorch tutorials might give you enough familiarity with autograd / neural networks.

Now coming to the task. Take a look at how `nn.Linear` is implemented in PyTorch here:

1. core implementation in nn._functions
https://github.com/pytorch/pytorch/blob/2b23712dc34ad281a1d9c7d5a829a83168503f93/torch/nn/_functions/linear.py#L5-L31
2. then, called in nn via creating an `nn.Linear` which is a subclass of `nn.Module`:
https://github.com/pytorch/pytorch/blob/2b23712dc34ad281a1d9c7d5a829a83168503f93/torch/nn/modules/linear.py#L9-L60

Read the notes [Extending Autograd](http://pytorch.org/docs/notes/extending.html) which would be helpful to understand the need for various functions such as `save_for_backward`.

To test your implementation, you need to write unit tests such as here:
https://github.com/pytorch/pytorch/blob/master/test/test_nn.py#L2256-L2261 

Initially, you probably want to just test it via the interpreter, comparing the output to the reference implementation in `torch.legacy.nn.BIlinear`.

You will have more questions, and we shall resolve them via comments here or on slack.

Lastly, look at the [CONTRIBUTING](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#developing-locally-with-pytorch) document for tips on locally developing pytorch.

**Comment by uridah** [comment]
https://github.com/pytorch/pytorch/pull/1146

**Comment by uridah** [comment]
#1146
