### ISSUE TITLE
lose precision when convert numpy array to torch tensor and execute matrix multiplication

### ISSUE THREAD

**Issue by ztf512** [pytorch/pytorch#76305]
### 🐛 Describe the bug

I find that when I convert numpy array to torch tensor and execute matrix multiplication, there will come out different results, just like this:
```python
import numpy as np
import torch


np.random.seed(0)
na = np.random.randn(256, 256).astype(np.float32)
nb = np.random.randn(256, 256).astype(np.float32)
nres = na @ nb  #  nres = na.dot(nb),  nres = na.__matmul__(nb)
print(nres.sum())  # >>> out: -2984.1348


ta = torch.from_numpy(na)
tb = torch.from_numpy(nb)
tres = ta @ tb  # tres = ta.matmul(tb)
print(tres.sum())  # >>> out: tensor(-2984.1350)
```
My numpy version is 1.21.3, pytorch version is 1.8.1. Could someone tell me how to solve it?

### Versions

PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.23

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.17

**Comment by albanD** [comment]
Hey!

Small numerical differences are expected due to floating point numbers. See https://pytorch.org/docs/stable/notes/numerical_accuracy.html for more details.

**Comment by ngimel** [comment]
This is not losing precision, precision is within expected floating point limits.
