### ISSUE TITLE
FX Quantization Workflow Support for Int8 Quantized Softmax

### ISSUE THREAD

**Issue by salilsdesai** [pytorch/pytorch#76310]
### 🚀 The feature, motivation and pitch

@kimishpatel and I are planning to add int8 support to the quantized softmax operator (in D35621286), and we would like for the fx quantization workflow to be able to support this change. @vkuzo had helped us with the uint8 version of this (D35324817), but he doesn't have the bandwidth to help this time. Is there anyone else on the quantization team who can help?

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
Can you clarify the ask? It seems like in the previous diff the issue was creating the python scaffolding for the quantized kernel. That scaffolding now exists and after a cursory glance I don't see what the blocker would be as far as the python scaffolding and i don't hit ANY error when I try to test it, it seems to work already.

```
>>> torch.ops.quantized.softmax(torch.quantize_per_tensor(torch.randn(3,3),1.0,0,torch.quint8), 1, 1.0, 0)
tensor([[0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 0.]], size=(3, 3), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.0, zero_point=0)
>>> torch.ops.quantized.softmax(torch.quantize_per_tensor(torch.randn(3,3),1.0,0,torch.qint8), 1, 1.0, 0)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], size=(3, 3), dtype=torch.qint8,
       quantization_scheme=torch.per_tensor_affine, scale=1.0, zero_point=0)
```

**Comment by salilsdesai** [comment]
We are specifically interested in the fx quantization workflow. Quantized softmax works for both datatypes and any input scale/zero point in general, but we have added an optimized version for uint8 with input scale 1/256 and zero point 0, and we are planning to land a similarly optimized version for int8 with input scale 1/256 and zero point -128. So we want the fx quantization workflow to allow for and enforce each data type's respective optimized input scales and zero points.

**Comment by HDCharles** [comment]
when you say allow for and enforce, are you looking for the workflow to forcibly select these optimized scale/zero_point and not allow other parameters?

**Comment by vkuzo** [comment]
The default logic of which scale and zero point are used for quantized softmax is here: https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/observer.py#L1495-L1498

@salilsdesai , are you using the defaults?  They are set for `quint8`.  Have you tried modifying this qconfig with the scale and zero_point that you need?

**Comment by kimishpatel** [comment]
> @vkuzo Where did those defaults come from? They don't match the values we are expecting.

affine is what gets used for softmax quantization from what i remember. And that has scale=1/256 and zero point = 0 for quint8. That matches what we expect for quint8?

qint8 is the missing one?

**Comment by vkuzo** [comment]
you can set any values you want for this when you specify the qconfig you want to use for each op.  Have you tried specifying a qconfig with the values you need, and configuring quantized softmax to use your custom qconfig?

The default qconfig for this op is assuming quint8 activations, you can to override it with values which make sense for your use case.

**Comment by jerryzh168** [comment]
in current fx graph mode quantization, we would override the qconfig for these operators actually: https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/backend_config/native.py#L510, we'd need to cleanup this key to allow using a different observer/fake_quant

**Comment by salilsdesai** [comment]
I am trying to test an fx quantized model which uses softmax (following this guide: https://pytorch.org/tutorials/prototype/fx_graph_mode_ptq_static.html#prototype-fx-graph-mode-post-training-static-quantization )- things seem to be ok when I try in a bento notebook, but when I test on my devserver I am getting the following error. Do you know how I can fix this?

```
Traceback (most recent call last):
  File "<string>", line 49, in <module>
  File "<string>", line 47, in __run
  File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform010/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/users/salilsdesai/fbsource/fbcode/buck-out/dev/gen/caffe2/qint8_softmax_fx_quant_test#link-tree/aten/src/ATen/native/quantized/cpu/test/qint8_softmax_fx_quant_test.py", line 4, in <module>
    from torch.quantization.quantize_fx import prepare_fx, convert_fx
  File "/data/users/salilsdesai/fbsource/fbcode/buck-out/dev/gen/caffe2/qint8_softmax_fx_quant_test#link-tree/torch/quantization/quantize_fx.py", line 10, in <module>
    from torch.ao.quantization.quantize_fx import (
  File "/data/users/salilsdesai/fbsource/fbcode/buck-out/dev/gen/caffe2/qint8_softmax_fx_quant_test#link-tree/torch/ao/quantization/quantize_fx.py", line 4, in <module>
    from torch.fx import GraphModule
ModuleNotFoundError: No module named 'torch.fx'
```

**Comment by salilsdesai** [comment]
> if you do
> 
> ```
> import torch.fx
> ```
> 
> it should work, the dependency setup for `torch.fx` is special and currently at Meta you need to import it explicitly

I tried putting "import torch.fx" and the top of the file, and I'm getting the same ModuleNotFoundError on that line. 
Do I need to add a special dependency to the python_binary buck rule? Right now I just have "//caffe2:torch"

**Comment by vkuzo** [comment]
yes, you need to add `"//caffe2:torch_fx"` to dependencies

**Comment by salilsdesai** [comment]
Thanks that fixed that issue. So I'll try to add the qconfig that we need and see how it goes.

**Comment by vkuzo** [comment]
@salilsdesai , here is a code snippet on how to set the scale+zp for softmax for qint8, in today's codebase:

```
 m = nn.Sequential(nn.Softmax()).eval()                                           
                                                                                  
 # Create a custom qconfig for softmax for qint8 data type                        
 softmax_obs_ctr = torch.ao.quantization.FixedQParamsObserver.with_args(          
     dtype=torch.qint8, scale=1.0/256, zero_point=-128)                           
 softmax_qconfig = torch.ao.quantization.QConfig(                                 
     activation=softmax_obs_ctr, weight=softmax_obs_ctr)                          
                                                                                  
 qconfig_dict = {                                                                 
     '': torch.ao.quantization.default_qconfig,                                   
     'object_type': [                                                             
         (nn.Softmax, softmax_qconfig),                                           
         # (nn.Softmax, torch.ao.quantization.default_qconfig),                   
     ],                                                                           
 }                                                                                
                                                                                  
 # Currently, the default backend_config_dict does not allow `nn.Softmax`         
 # to have an activation dtype of `qint8`. For now, fix it by modifying the       
 # dict. In the future, this may need to be committed to the backend_config_dict  
 # code.                                                                          
 from torch.ao.quantization.backend_config import get_native_backend_config_dict  
 backend_config_dict = get_native_backend_config_dict()                           
 for config in backend_config_dict['configs']:                                    
     if config['pattern'] is nn.Softmax:                                          
         config['dtype_configs'].append({                                         
           "input_dtype": torch.qint8,                                            
           "output_dtype": torch.qint8,                                           
         })                                                                       
                                                                                  
 # pass in the custom `backend_config_dict` to ensure we enable qint8 for softmax 
 mp = quantize_fx.prepare_fx(                                                     
     m, qconfig_dict, backend_config_dict=backend_config_dict)                    
                                                                                  
 softmax_obs = getattr(mp, 'activation_post_process_1')                           
 # prints (0.0039, -128)                                                          
 print('(scale, zero_point', softmax_obs.calculate_qparams())                     
```

There are a couple of reasons why the workaround above is needed:
1. the current default `backend_config_dict` assumes `quint8` activations.  We should align on how we can change this to ensure the models targeting xnnpack can still use defaults.  cc @jerryzh168 
2. currently there is overrides of observers for fixed qparam ops if activation dtype is `quint8`, we should remove this.  cc @jerryzh168 

@jerryzh168  assigning to you for the longer term next steps.  @salilsdesai , let us know if you are still blocked here.

**Comment by kimishpatel** [comment]
> * the current default `backend_config_dict` assumes `quint8` activations.  We should align on how we can change this to ensure the models targeting xnnpack can still use defaults.  cc @jerryzh168

Does this not require us to first support qint8 for activation dtype throughout fx quant workflow.

**Comment by jerryzh168** [comment]
> 2\. currently there is overrides of observers for fixed qparam ops if activation dtype is `quint8`, we should remove this.  cc @jerryzh168

I think we can just add this to the current native backend config dict for now in https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/backend_config/native.py#L505

**Comment by jerryzh168** [comment]
> > * the current default `backend_config_dict` assumes `quint8` activations.  We should align on how we can change this to ensure the models targeting xnnpack can still use defaults.  cc @jerryzh168
> 
> Does this not require us to first support qint8 for activation dtype throughout fx quant workflow.

we can just add extra dtype configurations to the ops that needs qint8 support, add something like:

```
{                                         
           "input_dtype": torch.qint8,                                            
           "output_dtype": torch.qint8,                                           
}
```
to the "dtype_configs" config for the target operator/fusion pattern

**Comment by vkuzo** [comment]
@kimishpatel, @jerryzh168  , thoughts on how we should handle the mismatch in capabilities between fbgemm and qnnpack/xnnpack?

Currently we have a single "fbgemm/qnnpack" backend_config_dict, which only includes `quint8` activation capabilities.  If we add `qint8` activation capabilities to this configuration, then it will no longer be valid for fbgemm.  If a user quantizes a model this way and attempts to evaluate accuracy on server with fbgemm, they will get an error.  Is that fine?

The alternative would be to separate the configs for fbgemm and qnnpack/xnnpack.  It's also not ideal as it breaks how things work today.

**Comment by kimishpatel** [comment]
> Currently we have a single "fbgemm/qnnpack" backend_config_dict, which only includes `quint8` activation capabilities. If we add `qint8` activation capabilities to this configuration, then it will no longer be valid for fbgemm. If a user quantizes a model this way and attempts to evaluate accuracy on server with fbgemm, they will get an error. Is that fine?

So if you set engine to qnnpack it should work for the supported ops. For the ops which are not supported and thus the model cannot be run, we can work on those. Those ops likely are not supported on mobile either so we will have to add support for them anyway.

I would separate the question of fbgemm vs. qnnpack. If you use qnnpack as backend for quantizing the model (as it is possible today) then you should be able to validate it on server using qnnpack as qengine.

Note that if you use qnnpack as backend for quantizing the model, such model cannot be run with fbgemm as backend on server anyway due to reduce range issue (at least not on server that are not new x86 ones)

**Comment by kimishpatel** [comment]
> 

What you said makes sense. I just want confirm my understand.

> the user can currently use the "fbgemm/qnnpack" op config

You mean due to being able to specify op level qconfig you can mix up qconfigs and generate a model that is not runnable on fbgemm backend. For example you can train with fbgemm backend but switch out softmax with quantized version with qint8 activation which produces qint8 activation output and that may not work if subquent op is say quantized conv2d and is run on fbgemm?

**Comment by vkuzo** [comment]
> > 
> 
> What you said makes sense. I just want confirm my understand.
> 
> > the user can currently use the "fbgemm/qnnpack" op config
> 
> You mean due to being able to specify op level qconfig you can mix up qconfigs and generate a model that is not runnable on fbgemm backend. For example you can train with fbgemm backend but switch out softmax with quantized version with qint8 activation which produces qint8 activation output and that may not work if subquent op is say quantized conv2d and is run on fbgemm?

Here is the current contents of the "fbgemm/qnnpack" configuration: https://pytorch.org/docs/master/quantization-backend-configuration.html

An excerpt:

```
             {'dtype_configs': [{'bias_dtype': torch.float32,
                                 'input_dtype': torch.quint8,
                                 'output_dtype': torch.quint8,
                                 'weight_dtype': torch.qint8}],
              'observation_type': <ObservationType.OUTPUT_USE_DIFFERENT_OBSERVER_AS_INPUT: 0>,
              'pattern': <class 'torch.nn.modules.conv.Conv1d'>,
              'qat_module': <class 'torch.nn.qat.modules.conv.Conv1d'>,
              'reference_quantized_module_for_root': <class 'torch.nn.quantized._reference.modules.conv.Conv1d'>,
              'root_module': <class 'torch.nn.modules.conv.Conv1d'>},
```

This means "if you see a conv1d with input_dtype of quint8 and output_dtype of quint8, fbgemm/qnnpack has a kernel for that".  

If we add the `qint8` settings to this, then the config would only be correct for qnnpack.  I'm just asking that since we are adding qint8 activations which are only valid for qnnpack and not fbgemm, should we split fbgemm and qnnpack into separate configs, just to ensure that the configs actually represent what the backends can do?

**Comment by vkuzo** [comment]
> > 
> 
> I see. Ok I understand. Adding qint8 dtype results in qconfig that is compatible with qnnpack backend only. I think what you suggested makes sense. We should split fbgemm and qnnpack into separate config. It also more or less lines up with eager mode symmetric qconfig https://fburl.com/code/a0s6l8sz, which is also tied to qnnpack only.
> 
> In terms of work, what would this look like in terms of effort, eta and who is working on it.

makes sense.  I think this is something for AO team to do, I was just asking if it makes sense to you since you have more context on qnnpack plans.

**Comment by kimishpatel** [comment]
> > > 
> > 
> > 
> > I see. Ok I understand. Adding qint8 dtype results in qconfig that is compatible with qnnpack backend only. I think what you suggested makes sense. We should split fbgemm and qnnpack into separate config. It also more or less lines up with eager mode symmetric qconfig https://fburl.com/code/a0s6l8sz, which is also tied to qnnpack only.
> > In terms of work, what would this look like in terms of effort, eta and who is working on it.
> 
> makes sense. I think this is something for AO team to do, I was just asking if it makes sense to you since you have more context on qnnpack plans.

Sounds good but there is some model @salilsdesai is trying to quantize and that only works with fx workflow, so want to make sure we can prioritize this.

**Comment by jerryzh168** [comment]
> @kimishpatel, @jerryzh168 , thoughts on how we should handle the mismatch in capabilities between fbgemm and qnnpack/xnnpack?
> 
> Currently we have a single "fbgemm/qnnpack" backend_config_dict, which only includes `quint8` activation capabilities. If we add `qint8` activation capabilities to this configuration, then it will no longer be valid for fbgemm. If a user quantizes a model this way and attempts to evaluate accuracy on server with fbgemm, they will get an error. Is that fine?
> 
> The alternative would be to separate the configs for fbgemm and qnnpack/xnnpack. It's also not ideal as it breaks how things work today.

I think it depends on the goals, I remember that we would like to hide things from user as much as possible so that user only need to think about device and not backend. That's why we suggest onednn/mkldnn(from intel) to merge with fbgemm engine as well. In this case, it would be fine to error out when something is not supported in a certain quantized engine I think, or we could have a general fallback or something.

I think the question is would be do we consider mobile cpu and server cpu two different backends? and how do we think about the fact that qnnpack also runs on server?

**Comment by jerryzh168** [comment]
as of now, it looks like PyTorch has one quantized cpu backend, and all quantized ops have same signatures, which is trying to hide fbgemm/qnnpack details as much as possible.

**Comment by kimishpatel** [comment]
> I think the question is would be do we consider mobile cpu and server cpu two different devices? and how do we think about the fact that qnnpack also runs on server?
> 

I dont think we should consider quantization engines/backend (as defined today) as tied to mobile or server. It is a backend on which you want to run on your quantized model. In some instances it may fail and it is upto the quantization engine to provide meaningful feedback. This way we dont say whether qnnpack is arm or x86 specific. Same for fbgemm. As far user is concerned they know qnnpack/fbgemm. Then it is a finer details that on x86 better to use fbgemm as execution engine and on arm cpus better to use qnnpack.

**Comment by kimishpatel** [comment]
> right. I think hiding fbgemm vs qnnpack makes sense if they are interchangeable. With addition of qint8 activations, seems like this is no longer true, unless fbgemm also plans to support them?

This is not true today even if the op signatures all the same. We have reduce range in fbgemm. So they are not quite interchangeable. 

> If a user is trying to do qint8 activations with fbgemm backend config, IMO the right behavior is to throw an error saying that "this backend does not support qint8 activations". 

This makes sense to me.

> This seems impossible to detect if we have qint activations in the config which is also used by fbgemm.

Yeah so this is inline with what you are proposing. However if we decouple backend from quantization workflow for the moment (e.g. ignore reduce_range issue), then we dont need to tie qconfig with backend. Now this will produce quantized model that is agnostic of backend it runs on so the error will be thrown only at runtime. But this seems more inline with the notion of backend agnostic quantization workflow. What do you think @vkuzo?

**Comment by jerryzh168** [comment]
> > I think the question is would be do we consider mobile cpu and server cpu two different devices? and how do we think about the fact that qnnpack also runs on server?
> 
> I dont think we should consider quantization engines/backend (as defined today) as tied to mobile or server. It is a backend on which you want to run on your quantized model. In some instances it may fail and it is upto the quantization engine to provide meaningful feedback. This way we dont say whether qnnpack is arm or x86 specific. Same for fbgemm. As far user is concerned they know qnnpack/fbgemm. Then it is a finer details that on x86 better to use fbgemm as execution engine and on arm cpus better to use qnnpack.

we have existing concept of device CPU/CUDA and QuantizedCPU, QuantizedCUDA backend in PyTorch, are you suggesting to introduce another dimension underneath them, e.g. for QuantizedCPU, we can have fbgemm/qnnpack/some_other engine, for QuantizedCUDA, we can have fbgemm/qnnpack/some_other engine and expose the quantized engine as a separate concept in addition to existing backend concepts?

I'm looking at https://github.com/pytorch/pytorch/pull/67177#issuecomment-957169770 again, does the comment still apply here? "We choose the right one based on the compilation mode and provide explicit switch for debugging purposes" --> can this be achieved with the new qint8 stuff or something changed?

**Comment by kimishpatel** [comment]
> we have existing concept of device CPU/CUDA and QuantizedCPU, QuantizedCUDA backend in PyTorch, are you suggesting to introduce another dimension underneath them, e.g. for QuantizedCPU, we can have fbgemm/qnnpack/some_other engine, for QuantizedCUDA, we can have fbgemm/qnnpack/some_other engine and expose the quantized engine as a separate concept in addition to existing backend concepts?

No definitely not. I think we are mixing our defintions of backend. By backend I did not mean backend for Tensors as defined in Pytorch but more specifically quantization engine, thats it. So no need to extend any definition in the pytorch.

> can we choose the correct qengine based on compilation mode now with the xnnpack additions or something has changed?

As far as user visibile quantization engines are concerned, nothing has changed. So we shouldnt really talk about xnnpack. If you enable QNNPACK and chose qnnpack as engine then this engine can run both symmetric and asymmetrically quantized models.

> In https://pytorch.org/docs/stable/quantization.html#natively-supported-backends it says "The corresponding implementation is chosen automatically based on the PyTorch build mode, though users have the option to override this by setting torch.backends.quantization.engine to fbgemm or qnnpack." is this still correct?

Yes that still holds and those are the only two backends we should talk about. Or rename that to engine to avoid confusing that with QuantizedCPU backend.

**Comment by jerryzh168** [comment]
so what is the scenario when user uses qint8 qconfig and runs fbgemm engine? is it:
1). user intends to run the model in fbgemm, but it sets qint8 qconfig and we don't error out
2). user compiles pytorch with fbgemm
3). user runs the model

In this case should we fix 1). and ask user only to use get_default_qconfig("fbgemm") or get_default_qconfig_dict("fbgemm")?

**Comment by vkuzo** [comment]
I'd phrase it as "the current config is called fbgemm/qnnpack, but it's really the union of config for fbgemm and config for qnnpack, and there is no guarantee that a model that passes this config will be runnable on fbgemm".

**Comment by jerryzh168** [comment]
> I'd phrase it as "the current config is called fbgemm/qnnpack, but it's really the union of config for fbgemm and config for qnnpack, and there is no guarantee that a model that passes this config will be runnable on fbgemm".

the config here means backend config?

**Comment by kimishpatel** [comment]
I agree with the phrasing @vkuzo made. Overall my feeling is that quantization config is orthogonal to the engine it runs on. Yes our choices right now _are_ driven by qengine, but in principle they are independent. Thus, we have qconfig that only understands quantization related attributes and then we can have API that says whether a particular qconfig is compatible with some backend/qegine you want to run it on. e.g. `is_qconfig_compatbile_with_backend(qconfig, backend)`. I imagine this also goes well with backend agnostic API/flow you had proposed @jerryzh168

**Comment by jerryzh168** [comment]
Yes, that is the purpose for my RFC: https://github.com/pytorch/rfcs/blob/master/RFC-0019-Extending-PyTorch-Quantization-to-Custom-Backends.md, in general we should do that. But there is another conflicting design principle for native pytorch backends that we'd like to hide backend details as much as we can. From Dima's comment: https://github.com/pytorch/pytorch/pull/67177#issuecomment-957169770, that is what we did for other backends/implementation in pytorch (like cudnn v.s. cuda, normal cpu v.s. mkldnn etc.), where we choose the backend that makes sense for user automatically.

In this case it looks like by default we choose this based on compilation flag?

And if the runtime error only occurs in non-default path, maybe it is OK?

**Comment by kimishpatel** [comment]
> Yes, that is the purpose for my RFC: https://github.com/pytorch/rfcs/blob/master/RFC-0019-Extending-PyTorch-Quantization-to-Custom-Backends.md, in general we should do that. The question here is more of should we treat fbgemm and qnnpack as the same backend?
> 
> There is another conflicting design principle for native pytorch backends that we'd like to hide backend details as much as we can. From Dima's comment: [#67177 (comment)](https://github.com/pytorch/pytorch/pull/67177#issuecomment-957169770), that is what we did for other backends/implementation in pytorch (like cudnn v.s. cuda, normal cpu v.s. mkldnn etc.), where we choose the implementation that makes sense for user automatically based on operator information or some other information.
> 

Yes but cpu vs mkldnn etc. can be completely hidden whereas fbgemm vs qnnpack cannot for 1 due to reduce_range and for 2 due to older quantization API making this user visible thing. I think 2 is what you guys are trying to work around but 1 is still an issue. 

> In this case it looks like by default we choose this based on compilation flag?
> 

This is also a poor choice unfortunately. We can compile with both backends as such. 

> And if the runtime error only occurs in non-default path, maybe it is OK?

What do you mean?

But overall for now lets just split with qnnpack specific config for int8 because there is truly not a way for us to do this in backend agnostic way today, is it?

I would like us to make progress on this in the shorter term, so please suggest what is most feasible.

**Comment by jerryzh168** [comment]
(1). expose a single native backend that includes int8 configs and produce a model that only runs successfully only when qengine is set to qnnpack.
```
qconfig_dict = {some int8 qconfig dict}
# using native backend config dict
model = prepare_fx(model, qconfig_dict, example_inputs)
torch.quantized.backend.engine = "qnnpack"
# run the model
model(x)
# runs

# if user engine is "fbgemm", we error out
# run the model
model(x)
# error: qint8 activation not supported in "fbgemm" engine
```

(2). split the backend_config_dict for qnnpack and fbgemm, and user needs to quantize for qnnpack specifically in prepare,
```
qconfig_dict = {some int8 qconfig dict}
qnnpack_backend_config_dict = get_qnnpack_backend_config_dict()
model = prepare_fx(model, qconfig_dict, example_inputs, qnnpack_backend_config_dict)
torch.quantized.backend.engine = "qnnpack"
# run the model
model(x)

# it is still possible to set qengine to "fbgemm" here
# and we need to error out
```


I think (1) can still be considered as a "backend agnostic way", that is how it works with `reduce_range` as well (since we don't have separate backend_config_dict for `reduce_range` either), except that the error is silent numerical error for `reduce_range` and we should detect that, in this case the error (qint8 act not supported) is pretty explicit and it is better than `reduce_range`, also I think we'd like to remove `reduce_range` in the future.

**Comment by jerryzh168** [comment]
yeah we can't fully hide qnnpack/fbgemm engine, and have to allow user to set the engine themselves, this is not a common path though, IIUC, we only enable qnnpack on server for debugging purpose, and the other times we may only have one engine and user don't need to worry about this?

**Comment by kimishpatel** [comment]
I think 1. sounds good to me.

> we only enable qnnpack on server for debugging purpose, and the other times we may only have one engine and user don't need to worry about this?

if "by the other times" you mean for qint8 then I would say we just error out as suggested in 1.

Basically what you propose in 1 sounds good to me.

**Comment by jerryzh168** [comment]
> if "by the other times" you mean for qint8 then I would say we just error out as suggested in 1.

"the other times" means the cases when we only have qnnpack OR fbgemm available as a backend, e.g. when we compile for mobile, we'd only compile qnnpack engine, so the only available one is qnnpack, similarly for server, we may compile both fbgemm/qnnpack, but we can treat fbgemm as default on server.

Only when we (1) compiled both engines, and (2). we want to choose the non-default engine do we need to set the qengine explicitly, this is the case in server, we compiled both qnnpack and fbgemm, and fbgemm is the default, so user would need to set qengine to qnnpack to test the qnnpack backend there

**Comment by jerryzh168** [comment]
> (1). expose a single native backend that includes int8 configs and produce a model that only runs successfully only when qengine is set to qnnpack.
> 
> ```
> qconfig_dict = {some qint8 qconfig dict}
> # using native backend config dict
> model = prepare_fx(model, qconfig_dict, example_inputs)
> torch.quantized.backend.engine = "qnnpack"
> # run the model
> model(x)
> # runs
> 
> # if user engine is "fbgemm", we error out
> # run the model
> model(x)
> # error: qint8 activation not supported in "fbgemm" engine
> ```
> 
> Basically the quantization works, but the produced model only works in qnnpack engine.
> 
> (2). split the backend_config_dict for qnnpack and fbgemm, and user needs to quantize for qnnpack specifically in prepare,
> 
> ```
> qconfig_dict = {some qint8 qconfig dict}
> qnnpack_backend_config_dict = get_qnnpack_backend_config_dict()
> model = prepare_fx(model, qconfig_dict, example_inputs, qnnpack_backend_config_dict)
> torch.quantized.backend.engine = "qnnpack"
> # run the model
> model(x)
> 
> # it is still possible to set qengine to "fbgemm" here
> # and we need to error out
> ```
> 
> Here it is the same, user is explicitly quantizing for qnnpack engine, we are basically exposing qnnpack engine as the top level concept similar to backend/device here, but in the end, we still have a model that only works for qnnpack engine. (when we have a quantized model, we can still switch to fbgemm engine since fbgemm and qnnpack are wrapped under the same quantized ops signature, controlled only through quantized engine flag, but it will error out)
> 
> I think (1) can still be considered as a "backend agnostic way", that is how it works with `reduce_range` as well (since we don't have separate backend_config_dict for `reduce_range` either), except that the error is silent numerical error for `reduce_range` and we should detect that, in this case the error (qint8 act not supported) is pretty explicit and it is better than `reduce_range`, also I think we'd like to remove `reduce_range` in the future.

cc @vkuzo what do you think about (1)?

**Comment by vkuzo** [comment]
> There is another conflicting design principle for native pytorch backends that we'd like to hide backend details as much as we can.

This makes sense if the the model can be run with the same settings on both backends.  IMO it never made 100% sense for fbgemm vs qnnpack because of reduce_range.  Now that we are adding qint8 activations as the default choice for qnnpack, it makes even less sense to me.

**Comment by vkuzo** [comment]
> (1). expose a single native backend that includes int8 configs and produce a model that only runs successfully only when qengine is set to qnnpack.

To me this sounds like buying a car, and realizing that the engine does not start after I already paid for the car, and no way to get my money back :). I think it would be a better user experience for any incompatibility failures to be shown to the user as early as possible, so they do not waste time optimizing accuracy on a model which cannot run on their chosen backend.  From what I understand, separating fbgemm and qnnpack backend_config_dict objects would be one way to do that.  Any other ideas?

**Comment by jerryzh168** [comment]
> > There is another conflicting design principle for native pytorch backends that we'd like to hide backend details as much as we can.
> 
> This makes sense if the the model can be run with the same settings on both backends. IMO it never made 100% sense for fbgemm vs qnnpack because of reduce_range. Now that we are adding qint8 activations as the default choice for qnnpack, it makes even less sense to me.

I'm wondering if the problem will be solved if we restrict users to use get_default_qconfig("fbgemm")/get_default_qconfig_dict("fbgemm") etc. and only expose the qconfig to more advanced users who knows what they are doing?

**Comment by vkuzo** [comment]
> I'm wondering if the problem will be solved if we restrict users to use get_default_qconfig("fbgemm")/get_default_qconfig_dict("fbgemm") etc. and only expose the qconfig to more advanced users who knows what they are doing?

This doesn't address the fact that "get_native_backend_config_dict" is incorrect, it's promising to return a backend_config_dict that works on fbgemm or qnnpack, but the promise is not fulfilled.  We shouldn't call something "fbgemm or qnnpack" unless all possible combinations of it support both fbgemm and qnnpack.

If we want to keep the current backend_config_dict, a more descriptive name for it would be "could_be_valid_for_fbgemm_or_qnnpack_but_you_dont_know_until_you_run_inference".

**Comment by jerryzh168** [comment]
this problem seems no longer relevant with changes in quantization flow in pytorch 2.0, I'll close this for now
