### ISSUE TITLE
cuda out of memory err:   when my gpu memory still has 4G left 

### ISSUE THREAD

**Issue by abbyQu** [pytorch/pytorch#7634]
## Issue description

i was running a trained model  from github ,i watched the gpu memory, found that the script exited when the memory usage got 2G.
my gpu is 1060 with 6G memory ,how did that come?

PS: torch might has the 2G limit,but i haven't install that 

 

## System Info
RuntimeError: cuda runtime err(2): out of memory at /opt/conda/conda-bld/pytorch_1501953625411/work/pytorch-0.1.12/torch/libTHC/THCstorage.cu:66

 

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS: Ubuntu 14.04
- PyTorch version: pytorch 0.1.10
- Python version:  2.7
- CUDA/cuDNN version: 8.0/5.1 
- GCC version (if compiling from source): 4.9

**Comment by SsnL** [comment]
it can happen when you are allocating >4G

**Comment by abbyQu** [comment]
maybe i should figure out the param size first .thanks.

**Comment by abbyQu** [comment]
maybe i should figure out the param size first .thanks. @Tongzhou Wang
