### ISSUE TITLE
Cannot INSTALL pytorch on ubuntu18.04(nvcc -ccbin clang-3.8)

### ISSUE THREAD

**Issue by lxy598951** [pytorch/pytorch#7635]
When I try to install the pytorch I have a problem as fellow.

## Bug

running install
running build_deps
+ WITH_CUDA=0
+ [[ --with-cuda == \-\-\w\i\t\h\-\c\u\d\a ]]
+ WITH_CUDA=1
+ shift
+ WITH_ROCM=0
+ [[ --with-nnpack == \-\-\w\i\t\h\-\r\o\c\m ]]
+ WITH_NNPACK=0
+ [[ --with-nnpack == \-\-\w\i\t\h\-\n\n\p\a\c\k ]]
+ WITH_NNPACK=1
+ shift
+ WITH_MKLDNN=0
+ [[ nccl == \-\-\w\i\t\h\-\m\k\l\d\n\n ]]
+ WITH_GLOO_IBVERBS=0
+ [[ nccl == \-\-\w\i\t\h\-\g\l\o\o\-\i\b\v\e\r\b\s ]]
+ WITH_DISTRIBUTED_MW=0
+ [[ nccl == \-\-\w\i\t\h\-\d\i\s\t\r\i\b\u\t\e\d\-\m\w ]]
+ CMAKE_INSTALL='make install'
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ dirname tools/build_pytorch_libs.sh
+ cd tools/..
+++ pwd
++ printf '%q\n' /home/leexy/github/pytorch
+ PWD=/home/leexy/github/pytorch
+ BASE_DIR=/home/leexy/github/pytorch
+ TORCH_LIB_DIR=/home/leexy/github/pytorch/torch/lib
+ INSTALL_DIR=/home/leexy/github/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/home/leexy/github/pytorch/third_party
+ CMAKE_VERSION=cmake
+ C_FLAGS=' -DTH_INDEX_BASE=0 -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/TH" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THS" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCUNN"'
+ C_FLAGS=' -DTH_INDEX_BASE=0 -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/TH" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THS" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS='-L"/home/leexy/github/pytorch/torch/lib/tmp_install/lib" '
+ LD_POSTFIX=.so.1
+ LD_POSTFIX_UNVERSIONED=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ LDFLAGS='-L"/home/leexy/github/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ GLOO_FLAGS=
+ THD_FLAGS=
+ NCCL_ROOT_DIR=/home/leexy/github/pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR=/home/leexy/github/pytorch/torch/lib/tmp_install'
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ CWRAP_FILES='/home/leexy/github/pytorch/torch/lib/ATen/Declarations.cwrap;/home/leexy/github/pytorch/torch/lib/THNN/generic/THNN.h;/home/leexy/github/pytorch/torch/lib/THCUNN/generic/THCUNN.h;/home/leexy/github/pytorch/torch/lib/ATen/nn.yaml'
+ CUDA_NVCC_FLAGS=' -DTH_INDEX_BASE=0 -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/TH" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THS" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ [[ '' -eq 1 ]]
+ '[' -z 8 ']'
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p torch/lib/tmp_install
+ for arg in "$@"
+ [[ nccl == \n\c\c\l ]]
+ pushd /home/leexy/github/pytorch/third_party
~/github/pytorch/third_party ~/github/pytorch
+ build_nccl
+ mkdir -p build/nccl
+ pushd build/nccl
~/github/pytorch/third_party/build/nccl ~/github/pytorch/third_party ~/github/pytorch
+ cmake ../../nccl -DCMAKE_MODULE_PATH=/home/leexy/github/pytorch/cmake/FindCUDA -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/leexy/github/pytorch/torch/lib/tmp_install '-DCMAKE_C_FLAGS= -DTH_INDEX_BASE=0 -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/TH" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THS" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1 ' '-DCMAKE_CXX_FLAGS= -DTH_INDEX_BASE=0 -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/TH" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THC"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THS" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCS"   -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THNN" -I"/home/leexy/github/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1  -std=c++11  ' -DCMAKE_SHARED_LINKER_FLAGS=
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leexy/github/pytorch/third_party/build/nccl
+ make install
[100%] Generating lib/libnccl.so
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
/bin/sh: 1: [: -lt: unexpected operator
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
ls: 无法访问'/usr/lib64/libcudart.so.*': 没有那个文件或目录
Compiling src/core.cu                         > /home/leexy/github/pytorch/third_party/build/nccl/obj/core.o
ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
       Use 'nvcc -ccbin clang-3.8' to use that instead.
Makefile:136: recipe for target '/home/leexy/github/pytorch/third_party/build/nccl/obj/core.o' failed
make[3]: *** [/home/leexy/github/pytorch/third_party/build/nccl/obj/core.o] Error 1
CMakeFiles/nccl.dir/build.make:60: recipe for target 'lib/libnccl.so' failed
make[2]: *** [lib/libnccl.so] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nccl.dir/all' failed
make[1]: *** [CMakeFiles/nccl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

## System Info
- PyTorch 0.4.0
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): gcc7.3
- OS: Ubuntu 18.04
- PyTorch version: 0.4.0
- Python version: 3.6.5
- CUDA/cuDNN version: 9.1

**Comment by yf225** [comment]
@lxy598951 According to this thread https://github.com/NVIDIA/nvidia-docker/issues/666 CUDA 9.1 won't work with gcc 7.3 on Ubuntu 18.04. You could try this approach https://askubuntu.com/a/1029153 to install gcc 6 and then install CUDA again, or wait for CUDA 9.2 to come out.

**Comment by thuyen** [comment]
Cuda 9.2 is here: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu

But somehow I dont' see 18.04 on the list.

**Comment by yf225** [comment]
CUDA 9.2 will provide experimental support to Ubuntu 18.04 using the 17.10 repository (https://github.com/NVIDIA/nvidia-docker/issues/666#issuecomment-389725483)
