### ISSUE TITLE
ComplexFloat support for clamp() in Pytorch?

### ISSUE THREAD

**Issue by bhosalems** [pytorch/pytorch#76361]
### 🐛 Describe the bug

I am getting below error,

```
def pdist(A, B = None, squared = False, eps = 1e-4):
    B = B if B is not None else A
    prod = torch.mm(A, B.t())
    normA = (A * A).sum(1).unsqueeze(1)
    normB = (B * B).sum(1).unsqueeze(1)
    D = clamp((normA.expand_as(prod) + normB.t().expand_as(prod) - 2 * prod), mn=0)
    return D if squared else clamp(clamp(D, mn=eps).sqrt(), mn=eps)

```
RuntimeError: "clamp_min_cpu" not implemented for 'ComplexFloat'

### Versions

pytorch 1.11.0

How do I bypass this error?

**Comment by ishaan-mehta** [comment]
https://github.com/pytorch/pytorch/issues/36444#issuecomment-613153990

In summary: this is not a bug. Comparison operations such as `clamp`, `min`, `max`, etc. are not supported for complex types in PyTorch.

**Comment by bhosalems** [comment]
Thanks for pointing that out, Also as suggested https://discuss.pytorch.org/t/complexfloat-supported-in-clam-pytorch/150076 will open the feature request.
