### ISSUE TITLE
ubuntu16.04: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed

### ISSUE THREAD

**Issue by lssily** [pytorch/pytorch#7636]
## Issue description
ubuntu16.04: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed

## System Info
Operating system: ubuntu16.04
Compiler version: gcc version 5.0.4 
CMake version: cmake version 3.5.1
Relevant libraries/versions (e.g. CUDA):CUDA8.0 cudnn 7.0.5

##Cmake summary output
[ 82%] Linking CXX executable ../bin/elementwise_op_gpu_test
../lib/libcaffe2.so: undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
../lib/libcaffe2.so: undefined reference to `google::SetUsageMessage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libcaffe2_gpu.so: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
../lib/libcaffe2.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
../lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:110: recipe for target 'bin/elementwise_op_gpu_test' failed
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
CMakeFiles/Makefile2:1741: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

look forward your help!

**Comment by bddppq** [comment]
From the `abi:cxx11` tag in your error message, this is likely your protobuf was built with the gcc4 abi while your compiler by default uses cxx11 (aka gcc5) abi.
It's better to align the abi in your protobuf installation with your compiler. As a shortcut, add `-DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"` to your cmake command might solve the issue (but will run into similar issues if there are other system libs are compiled with cxx11 abi).

**Comment by lssily** [comment]
Thank you for your answer. I solved this problem with your guide.
