### ISSUE TITLE
The C++ implementation of CAddTable.py

### ISSUE THREAD

**Issue by knandanan** [pytorch/pytorch#7638]
Hi ,
 I was wondering how to find the backend C++ definitions of CAddTable function in PyTorch. Is there any easy way on finding out where the C++ implementations are ?

Thanks in advance,
Kiran

**Comment by fmassa** [comment]
@knandanan which CAddTable are you talking about? This is a legacy Torch function, and I believe is only present in the `legacy` part of PyTorch, and is not maintained anymore.
For completeness, [here](https://github.com/pytorch/pytorch/blob/master/torch/legacy/nn/CAddTable.py) is how it's implemented in PyTorch (and similarly in Torch)

**Comment by knandanan** [comment]
@fmassa okay I understand but I was wondering if https://github.com/pytorch/pytorch/blob/master/aten/src/THC/generic/THCTensorMathPointwise.cu#L231
cadd in the THCTensorMathPointwise.cu is being called

**Comment by fmassa** [comment]
Yes, that's the function being called.
I think we have overloaded it with `torch.add`, which is called when we do `+` on tensors.
Also, for questions, it's better to ask them on the forums: https://discuss.pytorch.org/
