### ISSUE TITLE
the problem of torch.index() function in pytorch-0.4.0

### ISSUE THREAD

**Issue by Dataphz** [pytorch/pytorch#7639]
a = torch.FloatTensor(5)
a.index(3) 
The above code is running right in pytorch-0.3, but is wrong in pytorch-0.4,
TyreError: index(): argument "indices" (position 1) must be tuple of Tensors, not int.

**Comment by fmassa** [comment]
What's the benefit of using the (somewhat internal) `index` function instead of just indexing the tensors?
```python
a = torch.rand(5)
b = a[3]

c = a.index((torch.tensor(3),))  # much more verbose!
```

**Comment by apaszke** [comment]
@fmassa maybe we hsould hide it if it's internal...

**Comment by fmassa** [comment]
Actually, I have the impression that the documentation for the `index` function that was exposed to PyTorch is not the one I had in mind (which corresponds to the ATen `index`).

What probably happened is that internal implementation pointing to `index` has changed, but we have not updated the documentation.

I think we need to fix the documentation.

**Comment by t-vi** [comment]
So should we hide index or just document the current behaviour?

**Comment by fmassa** [comment]
I frankly don't currently see any benefits of exposing `index` (it's more verbose, only accept tensors as argument, it's a strict subset of indexing as only support advanced indexing), so I'd probably just hide it.

But let's see what the others think.

**Comment by vadimkantorov** [comment]
Theoretically one benefit may be more readable functional calls like `map(tensor.index, [0, 1, 2])` (vs sth like `map(tensor.__getitem__, [0, 1, 2])`)

**Comment by t-vi** [comment]
So we do not support the full spectrum of uglyness for [tensor[i] for i in range(3)]. Seems OK. More seriously: that Python does not have that in standard types is a good indication that we do not need it, either.
