### ISSUE TITLE
404 when trying to get pytorch-mutex-1.0-cuda.tar.bz2 from Conda

### ISSUE THREAD

**Issue by jruales** [pytorch/pytorch#76401]
### 🐛 Describe the bug

As part of a Dockerfile, we have a line that runs the following:
`conda install pytorch torchvision torchaudio torchtext cudatoolkit --channel pytorch && pip install torchinfo torchsummary`

This has been working fine, but it stopped working today with the error "404" NOT FOUND for url https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2

If you go to the page https://conda.anaconda.org/pytorch/noarch/, then you do see pytorch-mutex-1.0-cuda.tar.bz2 listed there, but indeed, going to that file opens up a 404 page instead of downloading the file.

What could be going on here? Why was that file removed from the conda channel?

### Versions

N/A

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by zou3519** [comment]
I can reproduce this

**Comment by seemethere** [comment]
Myself and @atalman are currently looking into this

**Comment by seemethere** [comment]
Pinning this issue since this will affect all conda users until it gets resolved

**Comment by atalman** [comment]
Issue created for anaconda repo [here](https://github.com/conda/conda/issues/11437)

**Comment by jiamings** [comment]
Same here. I used the simplest install command `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`, and it complains that pytorch-mutex-1.0-cuda.tar.bz2 does not exist when downloaded.

**Comment by seemethere** [comment]
Update to this, this is an outage from anaconda directly. They have an incident page up here: https://anaconda.statuspage.io/incidents/t1xrstmkf13x

**Comment by jruales** [comment]
Thanks, all. This is fixed.

**Comment by liminn** [comment]
> Thanks, all. This is fixed.

what is the solution, and why dont you write the solution?

**Comment by jruales** [comment]
@liminn This was an issue from April, and I didn't solve it. In the link that @seemethere shared you can see the updates from the Anaconda team about that issue.
