### ISSUE TITLE
[ppc64le pytorch] Error with building sleef when using cmake 3.11.1 (cmake 3.9.4 works)

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#7641]
Error when doing  python setup.py install:

-- COMPILER_SUPPORTS_OPENMP : 1
-- A version of SLEEF compatible  with libm and libmvec in GNU libc will be produced (sleefgnuabi.so)
disable contrib because ATEN_NO_CONTRIB is set
-- Configuring done
CMake Error at /home/jenkins/pytorch/third_party/sleef/src/libm/CMakeLists.txt:363 (add_library):
  No SOURCES given to target: sleefgnuabi

Going back to cmake 3.9.4  works

Collecting environment information...
PyTorch version: 0.5.0a0+331a04d
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB

Nvidia driver version: 384.81
cuDNN version: Probably one of the following:
/usr/lib/powerpc64le-linux-gnu/libcudnn.so.7.0.3
/usr/lib/powerpc64le-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.5.0a0+331a04d)
[conda] torch                     0.5.0a0+331a04d           <pip>

**Comment by soumith** [comment]
cc: @cpuhrsch a SLEEF issue

**Comment by cpuhrsch** [comment]
Let me try to conjure @shibatch, just in case this is something that isn't supported on his end. I'm blinding assuming this is independent of how we build SLEEF since it works on all other architectures and you're using the same build tools. More likely than not, we'll simply have to guard this as well and compile the code without SLEEF on ppc64le. It won't be useful over there anyway, since AVX/AVX2 doesn't exist on ppc64le.

**Comment by shibatch** [comment]
Please try specifying '-DBUILD_GNUABI_LIBS=FALSE'.

**Comment by avmgithub** [comment]
@shibatch thanks,   I build/install  using  "python setup.py  install"  ,  how/where would I specify the flag you suggest ?

**Comment by shibatch** [comment]
Try adding 
```
set(BUILD_GNUABI_LIBS OFF CACHE BOOL "Don't build sleef gnusbi libs" FORCE)
```
at around line 440 of aten/src/ATen/CMakeLists.txt

**Comment by avmgithub** [comment]
@shibatch thanks,  it seems to work with the line added using cmake 3.11.1.   I also tested it with cmake 3.6.3 and it works.
Also, thanks for looking at adding VSX.   Let me know when you are done, I can do some testing work.
I suppose you've seen this already [link](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W51a7ffcf4dfd_4b40_9d82_446ebc23c550/page/Intel%20SSE%20to%20PowerPC%20AltiVec%20migration) already

**Comment by shibatch** [comment]
As for VSX, some work for pytorch could be required in addition to sleef.

**Comment by avmgithub** [comment]
@shibatch  np ,  I'm sure I can find someone here to work on the pytorch changes.  we'll just need some guidance on where to make them :)

**Comment by cpuhrsch** [comment]
I'm also happy to help with this. @avmgithub could you send a PR with that change? That'll make sure it works everywhere.

**Comment by avmgithub** [comment]
@cpuhrsch pr #7679 created

**Comment by avmgithub** [comment]
closing , fixed
