### ISSUE TITLE
[regression] int_tensor.mean(dtype=float32) should work

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#76430]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/61643 broke the originally working case `non_fp_tensor.mean(dtype=fp_dtype)`.

Original code checks 
```
ScalarType scalarType = opt_dtype.has_value() ? opt_dtype.value() : self.scalar_type();
```
but the new code doesn't consider `opt_dtype` in checking:
```
at::isFloatingType(self_dtype) || at::isComplexType(self_dtype),
```

CC @ysiraichi who authored the PR, and @ezyang who merged it.

### Versions

1.10+

**Comment by vadimkantorov** [comment]
would also be nice if booltensor was supported: https://github.com/pytorch/pytorch/issues/64897 ...

**Comment by ngimel** [comment]
The easy workaround is to cast input tensor to fp, that's what would be done internally anyway.

**Comment by ezyang** [comment]
@ysiraichi think you can post the fix for this? Should be easy

**Comment by ysiraichi** [comment]
Ah, nice catch. Yeah, sure. I will do it.

**Comment by ngimel** [comment]
After that fix, can we also allow `mean` to type promote, so that mean of integral tensor would be supported? cc @mruberry, what happened to #34860?

**Comment by mruberry** [comment]
> After that fix, can we also allow `mean` to type promote, so that mean of integral tensor would be supported? cc @mruberry, what happened to #34860?

Funnily enough I believe we ultimately didn't pursue #34860 because some offline feedback was "let's develop a whole framework for systematically testing op properties like this!" and then we made the OpInfo test architecture. It should be easy to resurrect that PR.
