### ISSUE TITLE
`torch.nn.Module` keeps an owning reference that prevents it from properly deleting Module

### ISSUE THREAD

**Issue by otaj** [pytorch/pytorch#76434]
### 🐛 Describe the bug

When using method `_register_load_state_dict_pre_hook` of `torch.nn.Module` with argument `with_module=True`, the call to `functools.partial` keeps an owning reference which prevents the `Module` to be cleanly deleted when using `del module`, because there is still an owning reference.

To reproduce:

```python
import torch

def hook(self, *args, **kwargs):
    pass

module = torch.nn.Module()
module._register_load_state_dict_pre_hook(hook, with_module=True)
del module # there is still an owning reference in `module._load_state_dict_pre_hooks` hidden in closure made by `functools.partial`
```

This issue surfaced in https://github.com/PyTorchLightning/pytorch-lightning/issues/12622.

Proper workaround would probably be to change the call `functools.partial(hook, self)` to `functools.partial(hook, weakref.proxy(self))`

I can submit the PR myself if needed.

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: version 3.23.0
Libc version: glibc-2.35

Python version: 3.9.11 (main, Apr  7 2022, 15:33:34)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.17.1-zen1-1-zen-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: GPU 0: NVIDIA T1200 Laptop GPU
Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.3
/usr/lib/libcudnn_adv_infer.so.8.3.3
/usr/lib/libcudnn_adv_train.so.8.3.3
/usr/lib/libcudnn_cnn_infer.so.8.3.3
/usr/lib/libcudnn_cnn_train.so.8.3.3
/usr/lib/libcudnn_ops_infer.so.8.3.3
/usr/lib/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.7.0.dev0
[pip3] torch==1.11.0+cu113
[pip3] torchmetrics==0.7.3
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by otaj** [comment]
https://docs.python.org/3/library/gc.html
> This module provides an interface to the optional garbage collector.

**Comment by albanD** [comment]
Ho right! Thanks for the link.
Well in general, the memory usage might be very very large if you disable it completely. So I wouldn't go as far as "optional" I think even core CPython library do create such cycles.
