### ISSUE TITLE
Add ciflow/trunk label to PRs touching certain files

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#76443]
A part of enabling required status checks (#73657) is testing more and more on PRs. 

One thing we can start doing is automatically adding ciflow/trunk label to pull requests that touch certain files. 
- [ ] IOS files see https://github.com/pytorch/pytorch/pull/76251#issuecomment-1111129808
- [ ] mac files (as mac tests are not triggered by default)
- [ ] rocm files (as rocm is not triggered by default)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
obsolete
