### ISSUE TITLE
CUDA distributed tests set WORLD_SIZE=2 while ROCm distributed tests set WORLD_SIZE=3

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#76497]
### 🐛 Describe the bug

Recently #76136 added a decorator to skip odd world sizes for certain tests because the tests do not function correctly for such world sizes.  This problem only shows up for ROCm test runners because some of them contain 4 GPUs, whereas CUDA test runners for distributed tests only use 2 GPUs.

Most ROCm runners have 4 GPUs, but run_test.py sets world size to 3 for us.  The following code is in test/run_test.py.

```
"WORLD_SIZE": "2" if torch.cuda.device_count() == 2 else "3"
```

This causes a number of distributed tests to fail seemingly for ROCm only, but we have confirmed that CUDA doesn't handle all such odd-world-size test cases correctly, either.

Lastly, ROCm distributed tests take far longer to execute than their CUDA counterparts.  I'm curious if it is due to the difference in WORLD_SIZE.   Can we try forcing world size to 2 for both cuda and rocm?  For now it would be a waste of half of our GPUs, but as a follow-up we should explore having multiple runners per ROCm CI host.

### Versions

N/A

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by seemethere** [comment]
Adding to triage review to talk about this, want to understand the historical context for limiting to 2 GPUs
