### ISSUE TITLE
scipy computation of digamma at the poles changed, leading to test failure

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#7651]
[pytorch]
Scipy 1.1.0 computes digamma at [0, -2, -239] poles as [-inf, nan, nan] (there actually were documented changes to scipy digamma computation in this version), Scipy 1.0.1 and below used to compute them as [inf, inf, inf], torch computes them as [inf, inf, inf]. Thus, tests on the systems with scipy 1.1.0 fail. Neither computation is wrong, function is undefined at the poles, so perhaps testing strategy should be rethought.

**Comment by t-vi** [comment]
`NaN` would seem to be the more natural return value, but hey, I can do a PR to just adapt the test, too.

**Comment by zou3519** [comment]
@t-vi even if we decide to return NaN instead, if users run the pytorch tests with scipy < 1.1.0 then the same problem happens (the tests fail). I don't think our polygamma tests test pole values.

**Comment by t-vi** [comment]
Thanks @zou3519! For the proposed patch, I just map `+/-inf` to `NaN` for both scipy and torch.
Now I see the `test_poles=False` in `test_polygamma`, too.

**Comment by soumith** [comment]
closed via https://github.com/pytorch/pytorch/pull/7665
