### ISSUE TITLE
String repr for nested tensors no longer includes "nested_tensor(" prefix

### ISSUE THREAD

**Issue by jbschlosser** [pytorch/pytorch#76540]
### 🐛 Describe the bug

```python
x = torch.nested_tensor([torch.randn(2, 3), torch.randn(2, 4)])
print(x)
```
```
tensor([
  tensor([[-1.3230, -0.1327, -0.7044],
          [ 0.9888, -1.1508,  0.7750]]),
  tensor([[-0.8291,  0.5799, -0.6614,  0.2622],
          [-0.1244, -0.0272,  1.1289,  0.7562]])
])
```

The `__repr__` for a nested tensor should have the prefix `nested_tensor(` instead of `tensor(`. This was broken in #73459 by the tensor string representation changes:

https://github.com/pytorch/pytorch/blob/5b6efb824de77bf8bef8eddc7fc7362c47240ee5/torch/_tensor_str.py#L300-L307

Since `type(x)` is `torch.Tensor`, the first path is taken and the prefix is not set to `nested_tensor(`. Simple fix is to reorder these two paths.

### Versions

nightly

cc @ezyang @gchanan @zou3519 @cpuhrsch

**Comment by dagitses** [comment]
It looks like this is already fixed?

**Comment by jbschlosser** [comment]
> It looks like this is already fixed?

Yes that's correct. For some reason, GH is not auto-closing issues when linked PRs are merged.
