### ISSUE TITLE
`fbsync merge to master` failing for some PRs

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/pytorch#76568]
## Current Status
Hi, a bit similar to issue #71592, it seems some merges through fbcode are currently not getting propagated to master.

## Error looks like
Examples of PRs - 

#74596 

#76538

#76240

Each one of these PRs encountered the same issue -

![image](https://user-images.githubusercontent.com/90872293/165864197-4686b003-a181-4ed8-9ca8-2411565d780b.png)

## Incident timeline (all times pacific)
All 3 instances on April 28, 2022
https://github.com/pytorch/pytorch/actions/workflows/syncbranches.yml

## User impact
PRs couldn't land into the public PyTorch master branch.

## Root cause
Currently unknown to the submitter

## Mitigation
Requesting @seemethere & @janeyx99 for help. Thank you!

**Comment by sanchitintel** [comment]
@pytorch label ci:sev

**Comment by sanchitintel** [comment]
@pytorch label ci: sev

**Comment by sanchitintel** [comment]
@pytorch label ci: sev

**Comment by sanchitintel** [comment]
@pytorch label ci

**Comment by sanchitintel** [comment]
Sorry, it actually looks like this CI check was run before attempting to merge a PR (eg. with a pytorchbot command),
and there are some old PRs, for which this CI check had failed, but they successfully landed nevertheless.

**Comment by s4ayub** [comment]
@sanchitintel for these 3 PRs that failed to sync to github and merge:

https://github.com/pytorch/pytorch/pulls/s4ayub

should i just resubmit them as a PR on github?

**Comment by sanchitintel** [comment]
Hi @s4ayub, sorry for any confusion I may have caused!

I only see an fbsync failure on #76538 (out of the 3 pull requests), but I think that failure is inconsequential.
As is usual, your PR would have to be imported first & then merged.
@janeyx99, can you please confirm? Thanks!
