### ISSUE TITLE
inconsistent result between vector_norm and norm

### ISSUE THREAD

**Issue by Ishticode** [pytorch/pytorch#76582]
### 🐛 Describe the bug

Hi PyTorch team.

For multidimensional tensor, the vector_norm and norm are supposed to have same behaviour (docs). Why does their result differ here
`>>> import torch`
`>>> x = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])`
`>>> torch.linalg.norm(x, ord=2)`
` tensor(9.5255)`
while 
`>>> torch.linalg.vector_norm(x, ord=2)`
` tensor(9.5394)`
Sry if its due to my lack of understanding.
Thank you.

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

**Comment by ngimel** [comment]
Per docs, `torch.linalg.norm` with `ord=2` computes largest SVD value and not 2-norm of a flattened tensor, so different results are expected.

**Comment by Ishticode** [comment]
> Per docs, `torch.linalg.norm` with `ord=2` computes largest SVD value and not 2-norm of a flattened tensor, so different results are expected. 

Thanks, makes sense.
