### ISSUE TITLE
Custom CUDA operator only work well on cuda:0

### ISSUE THREAD

**Issue by YuxianMeng** [pytorch/pytorch#76586]
### 🐛 Describe the bug

change [this line](https://github.com/pytorch/extension-cpp/blob/master/benchmark.py#L31) to other devices

### Versions

I'm learning how to write custom cuda operator by your tutorial at https://github.com/pytorch/extension-cpp  

However, I found the operator only output correct results on "cuda:0", and output all_zeros tensor in other devices like "cuda:1"

**Comment by ngimel** [comment]
You should be setting the device guard to the device of your inputs. Please ask questions in discuss.pytorch.org.
