### ISSUE TITLE
Documentation for NCCL backend in torch.distributed is incorrect

### ISSUE THREAD

**Issue by nadiaya** [pytorch/pytorch#7658]
[Documentation](https://pytorch.org/docs/stable/distributed.html) claims that NCCL backend supports scatter and gather operations which aren't supported: 
https://github.com/pytorch/pytorch/blob/v0.4.0/torch/lib/THD/base/data_channels/DataChannelNccl.cpp#L669
https://github.com/pytorch/pytorch/blob/v0.4.0/torch/lib/THD/base/data_channels/DataChannelNccl.cpp#L678

**Comment by soumith** [comment]
thank you for the report. fixed documentation via https://github.com/pytorch/pytorch/commit/d4f6c84041a13a1bbcad824664be65cb1df2c97f
