### ISSUE TITLE
Testing pytorch quantized model export into onnx

### ISSUE THREAD

**Issue by danilopau** [pytorch/pytorch#76595]
### 🐛 Describe the bug

ref https://pytorch.org/tutorials/recipes/quantization.html
float model can be exported into onnx
quantized no;
see also https://github.com/pytorch/pytorch/issues/75960

import torchvision
model_quantized = torchvision.models.quantization.mobilenet_v2(pretrained=True, quantize=True)

import torch.onnx
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(device)

file_onnx = "mbnetv2_q_pytorch.onnx"

# create a random tensor input as needed by the network to be exported into onnx
inp = torch.randn(1,3,224,224)
output = model_quantized(inp)

torch.onnx.export(
    model_quantized,
    inp,
    file_onnx,
    export_params = True,
    opset_version=13,
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
    verbose = True
)

log
cuda
/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py:286: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py:286: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  "`{}` argument will be ignored.".format(arg_name, arg_name))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-79261800f9de> in <module>()
     17     opset_version=13,
     18     operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
---> 19     verbose = True
     20 )

6 frames
/usr/local/lib/python3.7/dist-packages/torch/jit/_trace.py in _unique_state_dict(module, keep_vars)
     69             filtered_dict[k] = v
     70         else:
---> 71             filtered_dict[k] = v.detach()
     72     return filtered_dict
     73 

AttributeError: 'torch.dtype' object has no attribute 'detach'

### Versions

import torchvision
model_quantized = torchvision.models.quantization.mobilenet_v2(pretrained=True, quantize=True)

**Comment by BowenBao** [comment]
hi @danilopau , this issue was captured by https://github.com/pytorch/pytorch/issues/75761, which was resolved via https://github.com/pytorch/pytorch/pull/75921. Please give a try with pytorch-nightly.

**Comment by danilopau** [comment]
In my notebook 
!pip install pytorch-nightly
does not work
ERROR: Could not find a version that satisfies the requirement pytorch-nightly (from versions: none)
ERROR: No matching distribution found for pytorch-nightly

no way from !pip install --pre torch torchvision torchaudio torch-nightly -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html

**Comment by danilopau** [comment]
Can you please edit this notebook to make it super clear ?
[quantisation_pytorch_2.txt](https://github.com/pytorch/pytorch/files/8613749/quantisation_pytorch_2.txt)
just rename it as .ipynb

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.
