### ISSUE TITLE
Add Nesterov Momentum

### ISSUE THREAD

**Issue by ajbrock** [pytorch/pytorch#766]
Hi guys,

Would you be interested in adding Nesterov momentum to the SGD optimizer? I've got a [version](https://github.com/ajbrock/pytorch/blob/master/torch/optim/sgd.py) based on [this parameterization](https://github.com/lisa-lab/pylearn2/pull/136#issuecomment-10381617) that just drops in a quick couple of changes to the SGD file. I'm not entirely sure what test files would need to be modified to make this appropriate, but I'd be down to submit a pull request and hash that out if there's interest.

Best,

Andy

**Comment by apaszke** [comment]
Yes, that would be great! Thanks!

You only need to change some steps inside the loop in `torch/optim/sgd.py`. Let us know if you'll have any questions.

**Comment by ajbrock** [comment]
Closed [#887](https://github.com/pytorch/pytorch/pull/887)
