### ISSUE TITLE
Canonicalize aten operators in IR

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#7660]
Currently many operators in the aten IR have multiple forms.

Any operator that takes a non-tensor argument (e.g. IntList or int64_t) will have two forms: one with the non-tensor arguments encoded as tensor inputs and one with the arguments as attributes on the graph.

This makes every pass that we write in the IR harder because it needs to handle both cases.

Proposed solution:

1. Canonicalize on the tensor input format. Graphs are optimized in this format. This format is more general because inputs are not required to be constants.

2. expose the `at::optional<T> constant_as<T>(Value*)` function in compiler for general usage. Optimizations then check for const-ness of these inputs to work.

3. Before interpretation, lower back to the attribute-only format when thing are constants. `compiler.cpp` already includes this function, it just has to be written into a pass.

**Comment by eellison** [comment]
We got rid of attributes for any aten operator so i believe this has been fixed.
