### ISSUE TITLE
`torch.clamp` type promotes strangely

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#76630]
### 🐛 Describe the bug

`torch.clamp` broadcast strangely that its return tensor has the same dtype as `input` argument. However, `torch.max` and `torch.min` will broadcast the return tensor to the most precise one. For example,

```python
import torch
input = torch.rand([5], dtype=torch.float32)
other = torch.rand([5, 5], dtype=torch.float64)

r1 = torch.maximum(input, other)
r2 = torch.clamp(input, min=other)
print(r1.dtype, r2.dtype)
# torch.float64 torch.float32
```

In the documentation of `torch.clamp`, `y = min(max(x, min_value), max_value)`, so I think it should the same broadcasting behavior as `torch.max` and `torch.min`

### Versions

pytorch: 1.10.0

cc @nairbv @mruberry @ezyang @ngimel

**Comment by mruberry** [comment]
It is odd that their behavior is distinct
