### ISSUE TITLE
GTK4 segfault on Ubuntu 22.04

### ISSUE THREAD

**Issue by duburcqa** [pytorch/pytorch#76631]
### 🐛 Describe the bug

On my setup, python segfault *(at exit only!)* if GTK4 is loaded **BEFORE** `torch.nn` and not after. Here is the backtrace:
```
free(): invalid pointer

Thread 1 "python" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350194304) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350194304) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737350194304) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737350194304, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c80476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c667f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7cc76f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7e19b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff7cded7c in malloc_printerr (str=str@entry=0x7ffff7e17764 "free(): invalid pointer") at ./malloc/malloc.c:5664
#7  0x00007ffff7ce0ac4 in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at ./malloc/malloc.c:4439
#8  0x00007ffff7ce34d3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00007fffa66a1049 in ?? () from /lib/x86_64-linux-gnu/libLLVM-13.so.1
#10 0x00007ffff7c83495 in __run_exit_handlers (status=0, listp=0x7ffff7e57838 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#11 0x00007ffff7c83610 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#12 0x00007ffff7c67d97 in __libc_start_call_main (main=main@entry=0x55555577b8a0, argc=argc@entry=2, argv=argv@entry=0x7fffffffde28) at ../sysdeps/nptl/libc_start_call_main.h:74
#13 0x00007ffff7c67e40 in __libc_start_main_impl (main=0x55555577b8a0, argc=2, argv=0x7fffffffde28, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde18)
    at ../csu/libc-start.c:392
#14 0x000055555577b7d5 in _start ()
```

The important point is `/lib/x86_64-linux-gnu/libLLVM-13.so.1` that gets loaded with GTK4. Here is a snippet to reproduce the bug:
```
import gi
gi.require_version("Gtk", "4.0")
from gi.repository import Gtk
import torch.nn
```

### Versions

PyTorch version: 1.11.0+cu115
Is debug build: False
CUDA used to build PyTorch: 11.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 10.3.0-15ubuntu1) 10.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-27-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==1.11.0+cu115
[conda] Could not collect

cc @ezyang @gchanan @zou3519

**Comment by duburcqa** [comment]
I have reported the issue to matplotlib team [here](https://github.com/matplotlib/matplotlib/issues/22948) but it seems rather related to torch.

**Comment by vadimkantorov** [comment]
@malfet another instance of fuzzying of imports

**Comment by ezyang** [comment]
cc @bertmaher

**Comment by duburcqa** [comment]
Apparently the bug does not manifest itself anymore after update of the system. So I'm closing.
