### ISSUE TITLE
Fix import in torch.profile to satisfy py.typed conventions and allow type checking by Pylance

### ISSUE THREAD

**Issue by ldorigo** [pytorch/pytorch#76652]
### 🐛 Describe the bug

See this issue on Pylance: https://github.com/microsoft/pylance-release/issues/2753#event-6524698001

Due to the current way `torch/profiler/__init__.py` is written, type checkers (at least pyright, used by pylance and most vscode users) assume that torch.profiler.profiler is a private module, and throw an error when importing it as

```python
from torch.profiler import profiler
```

According to Pylance devs (see issue), the fix is as simple as replacing imports in `__init__.py` by:

```python
from .profiler import profile as profile
```

(And similarly for other symbols)

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220421+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.23.1
Libc version: glibc-2.35

Python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.36-1-lts-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 510.60.02
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.3.3
/usr/lib/libcudnn_adv_infer.so.8.3.3
/usr/lib/libcudnn_adv_train.so.8.3.3
/usr/lib/libcudnn_cnn_infer.so.8.3.3
/usr/lib/libcudnn_cnn_train.so.8.3.3
/usr/lib/libcudnn_ops_infer.so.8.3.3
/usr/lib/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.902
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.12.0.dev20220421+cu113
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.12.0.dev20220421+cu113
[pip3] torchinfo==1.6.5
[pip3] torchvision==0.13.0.dev20220421+cu113
[conda] Could not collect   

cc @ilia-cher @robieta @chaekit @gdankel @bitfort @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git

**Comment by davidchencsl** [comment]
Couldn't reproduce the issue with vscode Version: 1.67.2 (Universal) and python extension v2022.6.2
<img width="366" alt="Screen Shot 2022-05-25 at 1 15 46 PM" src="https://user-images.githubusercontent.com/28990907/170359545-ad01e193-7028-4d90-beb1-fee0646904b0.png">

**Comment by ldorigo** [comment]
Did you set pylance mode to strict? "Throws an error" was perhaps a bit hyperbolic - I just meant the typechecker complained. Will see if it's still doing it later today.

**Comment by davidchencsl** [comment]
No, I didn't. After turning that on I can see it now. Will be working on fixing that tomorrow.
