### ISSUE TITLE
[FSDP] Pre-backward hook race

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#76681]
Assuming that autograd hooks are run as separate CPU threads, then there is a race condition in FSDP's pre-backward hook:
https://github.com/pytorch/pytorch/blob/5f98145fd9970d1edfb62acf4ac413193a90436d/torch/distributed/fsdp/fully_sharded_data_parallel.py#L2165-L2197

Suppose a FSDP module has multiple outputs, meaning that its pre-backward hook is triggered multiple times. Say that `t1` and `t2` are the threads running the pre-backward hook. For example, suppose
- `t1` enters `_pre_backward_hook()`, sees `self._pre_backward_hook_has_run == False`, and continues past the check to L2169;
-  the CPU context switches to `t2`; and
- `t2` enters `_pre_backward_hook()`, sees `self._pre_backward_hook_has_run == False`, and continues past the check to L2169.
In this case, both `t1` and `t2` will run the actual pre-backward hook logic.

Thanks @rohan-varma for finding this!

cc @zhaojuanmao @mrshenli @rohan-varma

**Comment by zhaojuanmao** [comment]
nice catch! it may help some perf improvement for some use cases...

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/76687#discussion_r863163361

@mrshenli stated that there should only be one thread per device, which matches what I am seeing in my local experiments, meaning that this race does not actually exist. We can close this for now.
