### ISSUE TITLE
distributed nccl2 backend error

### ISSUE THREAD

**Issue by gmyofustc** [pytorch/pytorch#7668]
Hi,
    I am using nccl2 backend to train my distributed model with pytorch
I can run my model with multiprocesses on one node, however, when i run my model on different node, it gives me this error
![image](https://user-images.githubusercontent.com/7859276/40224809-df087306-5ab9-11e8-95e3-976c57d9af08.png)

**Comment by soumith** [comment]
please post your question at https://discuss.pytorch.org
You must've given an incorrect init address (maybe you left it as the default)
