### ISSUE TITLE
in DataParallel cudnn rnn dropout states are initialized on a single device

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#767]
In multi-GPU runs with cudnn rnn, dropout states are initialized on a single device (non-deterministically, can be any device), and all devices access the states on that one (I suspect if P2P is disabled, it will break outright). That leads to 
1) non-deterministic correlated random numbers generated on the different devices
2) performance implications: shown is the profile where dropout kernels accessing states remotely, take 50 times as long as the kernels where state is local (purple kernels barely visible on upper timeline, and fat purple kernels on the lower timeline)
![selection_008](https://cloud.githubusercontent.com/assets/15841449/23048437/a251c022-f46a-11e6-9073-536081197729.png)
.

**Comment by csarofeen** [comment]
https://github.com/pytorch/pytorch/pull/772
Fix for this issue.
