### ISSUE TITLE
torch.matmul copies instead of broadcasting, while F.linear doesn't

### ISSUE THREAD

**Issue by thomasahle** [pytorch/pytorch#76702]
### 🐛 Describe the bug

I came across this PyTorch thread today, while debugging why my benchmarking traces were full of copy_() calls: https://discuss.pytorch.org/t/matmul-broadcasting-makes-copies/19494

Turns out `torch.matmul` doesn't do broadcasting properly.
That is, in code like this:

```
W = torch.randn(5, 5)
U = torch.randn(10, 5, 3)
torch.matmul(W, U)
```

the matrix `W` is copied 10 times.
Meanwhile, replacing `matmul(W, U)` by `F.linear(U.mT, W.T).mT` is fast and doesn't do any copying (according the the profiling).

### Versions

PyTorch version: pre-release version 1.12.0a0+fb 

cc @VitalyFedyunin @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by mruberry** [comment]
cc @Lezcano @ngimel

**Comment by ngimel** [comment]
Caused by https://github.com/pytorch/pytorch/blob/92d10decc448871cfbed258ad0ad670a9bd37047/aten/src/ATen/native/LinearAlgebra.cpp#L1704, we should instead take bmm path in this case.

**Comment by thomasahle** [comment]
Interesting. Does this mean that if `B` is 3d and `M` is 2d, then `M @ B` is slower than `B @ M`? It seems that the transpose + contiguous only happens when dim_tensor1 == 2 and dim_tensor2 >= 3, but not the other way arround?

**Comment by thomasahle** [comment]
That makes sense. I guess I should try to structure my code so it always does broadcasted multiplication from the right, rather than the left.

Here is a simple benchmark showing a 50% speed difference. If the matrices are not square, I can make it much larger.
```
[ins] In [3]: BS, DIM = 100, 100
         ...: A = torch.randn(DIM, DIM)
         ...: B = torch.randn(BS, DIM, DIM)

[ins] In [4]: %timeit A @ B
6.11 ms ± 117 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

[ins] In [5]: %timeit B @ A
4.02 ms ± 15.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Curiously this doesn't happen with numpy:
```
[ins] In [7]: C = np.random.randn(DIM, DIM)
         ...: D = np.random.randn(BS, DIM, DIM)

[ins] In [9]: %timeit C @ D
7.8 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

[ins] In [10]: %timeit D @ C
7.63 ms ± 85 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Though numpy is just always slower.

Do you think this will eventually be fast "using the BMM path"? Or will this "left vs right" just always be something to keep in mind?

**Comment by Lezcano** [comment]
We're fixing this soon :)

**Comment by Lezcano** [comment]
For context, `matmul` should be as good if not a better option than calling any of `vdot`, `mv`, `mm`, `bmm` for most "reasonable" outputs, so the rule should be that the user should always just use `@` (or `matmul`) unless they have very good reasons not to do so.

**Comment by thomasahle** [comment]
Right, I meant maybe there is a fundamental reason why multiplying on the left can't be as fast as multiplying on the right. (Given what @ngimel said about "folding the first dims of 3D matrix, call mm, and produce contiguous".) So even if this becomes a less obvious problem, it might still be a think to keep in mind when designing algorithms?

**Comment by Lezcano** [comment]
Multiplying on either side should have a comparable performance. Perhaps a small % of variance, but certainly not a 2x. 
https://github.com/pytorch/pytorch/pull/75197 is the PR to follow if you're interested in these points.

**Comment by thomasahle** [comment]
So if the plan is to switch to a "bmm path" when multiplying on the right, would that not require copying? Is there anywhere I can read about how that would work?

**Comment by Lezcano** [comment]
Please, see the linked PR and discussion therein

**Comment by lezcano** [comment]
Reopening. The pr was reverted

**Comment by vadimkantorov** [comment]
Hmm, seems matmul broadcasting might not be working as expected: https://discuss.pytorch.org/t/possible-to-replace-einsum-expr-btgi-gih-btgh-by-any-matmul-call/186930/2?u=vadimkantorov

**Comment by lezcano** [comment]
`x` and `weight[None, None,...]` are not broadcastable. as 20 != 3 in the dim `-3`, so that error is expected. I think what you want is to do is `torch.matmul(x[..., None], weight[None, None, ...]).shape`, if you want to do a batched vector-matrix matmul.
