### ISSUE TITLE
Misleading statement in optim.Optimizer docs

### ISSUE THREAD

**Issue by daniellepintz** [pytorch/pytorch#76752]
### 📚 The doc issue

In the `optim.Optimizer` docs it says:
```
If you need to move a model to GPU via .cuda(), please do so before constructing optimizers for it. 
Parameters of a model after .cuda() will be different objects with those before the call.
```

https://pytorch.org/docs/stable/optim.html#constructing-it

@albanD mentioned this is no longer the case and we can remove this statement from the doc

### Suggest a potential alternative/fix

Remove this statement from the docs

cc @brianjo @mruberry @vincentqb @jbschlosser @albanD

**Comment by jbschlosser** [comment]
Thanks for the report! We'd accept a PR removing the statement from the docs.

**Comment by daniellepintz** [comment]
Can I get a review on https://github.com/pytorch/pytorch/pull/76967? :)

**Comment by liyufan** [comment]
Hi all, it seems the statement is still necessary for `torch.optim.Adagrad` even in [v2.0.0](https://github.com/pytorch/pytorch/releases/tag/v2.0.0), as mentioned in #7321 #7844.
```python
import torch


device = torch.device("cuda:0")
l = torch.nn.Linear(3, 3)
o = torch.optim.Adagrad(l.parameters(), lr=0.1)
l.to(device)
o.zero_grad()
l(torch.randn(1, 3).to(device)).sum().backward()
o.step()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 10
      8 o.zero_grad()
      9 l(torch.randn(1, 3).to(device)).sum().backward()
---> 10 o.step()

File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/optim/optimizer.py:280, in Optimizer.profile_hook_step..wrapper(*args, **kwargs)
    276         else:
    277             raise RuntimeError(f"{func} must return None or a tuple of (new_args, new_kwargs),"
    278                                f"but got {result}.")
--> 280 out = func(*args, **kwargs)
    281 self._optimizer_step_code()
    283 # call optimizer step post hooks

File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/optim/optimizer.py:33, in _use_grad_for_differentiable.._use_grad(self, *args, **kwargs)
     31 try:
     32     torch.set_grad_enabled(self.defaults['differentiable'])
---> 33     ret = func(self, *args, **kwargs)
     34 finally:
     35     torch.set_grad_enabled(prev_grad)

File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/optim/adagrad.py:123, in Adagrad.step(self, closure)
    119     state_steps = []
    121     has_sparse_grad = self._init_group(group, params_with_grad, grads, state_sums, state_steps)
...
--> 359 torch._foreach_addcmul_(device_state_sums, device_grads, device_grads, value=1)
    360 std = torch._foreach_add(torch._foreach_sqrt(device_state_sums), eps)
    361 toAdd = torch._foreach_div(torch._foreach_mul(device_grads, minus_clr), std)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
But codes above work fine with `Adam`, `SGD`, etc. @albanD @daniellepintz

**Comment by boluodaixue** [comment]
Yes! You are right.

> Hi all, it seems the statement is still necessary for `torch.optim.Adagrad` even in [v2.0.0](https://github.com/pytorch/pytorch/releases/tag/v2.0.0), as mentioned in #7321 #7844.
> 
> ```python
> import torch
> 
> 
> device = torch.device("cuda:0")
> l = torch.nn.Linear(3, 3)
> o = torch.optim.Adagrad(l.parameters(), lr=0.1)
> l.to(device)
> o.zero_grad()
> l(torch.randn(1, 3).to(device)).sum().backward()
> o.step()
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> Cell In[1], line 10
>       8 o.zero_grad()
>       9 l(torch.randn(1, 3).to(device)).sum().backward()
> ---> 10 o.step()
> 
> File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/optim/optimizer.py:280, in Optimizer.profile_hook_step..wrapper(*args, **kwargs)
>     276         else:
>     277             raise RuntimeError(f"{func} must return None or a tuple of (new_args, new_kwargs),"
>     278                                f"but got {result}.")
> --> 280 out = func(*args, **kwargs)
>     281 self._optimizer_step_code()
>     283 # call optimizer step post hooks
> 
> File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/optim/optimizer.py:33, in _use_grad_for_differentiable.._use_grad(self, *args, **kwargs)
>      31 try:
>      32     torch.set_grad_enabled(self.defaults['differentiable'])
> ---> 33     ret = func(self, *args, **kwargs)
>      34 finally:
>      35     torch.set_grad_enabled(prev_grad)
> 
> File ~/anaconda3/envs/torch/lib/python3.11/site-packages/torch/optim/adagrad.py:123, in Adagrad.step(self, closure)
>     119     state_steps = []
>     121     has_sparse_grad = self._init_group(group, params_with_grad, grads, state_sums, state_steps)
> ...
> --> 359 torch._foreach_addcmul_(device_state_sums, device_grads, device_grads, value=1)
>     360 std = torch._foreach_add(torch._foreach_sqrt(device_state_sums), eps)
>     361 toAdd = torch._foreach_div(torch._foreach_mul(device_grads, minus_clr), std)
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
> ```
> 
> But codes above work fine with `Adam`, `SGD`, etc. @albanD @daniellepintz

Yes, you are right. When using torch. optim. Adagrad, the model must be moved to the GPU before constructing an optimizer, otherwise an error will be reported:` RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

**Comment by adosar** [comment]
If this:

> If you need to move a model to GPU via .cuda(), please do so before constructing optimizers for it. 
> Parameters of a model after .cuda() will be different objects with those before the call.

was not a misleading statement why it was removed from [docs](https://pytorch.org/docs/stable/optim.html#constructing-it)?
