### ISSUE TITLE
torch.jit.script unable to fuse elementwise operations

### ISSUE THREAD

**Issue by CHDev93** [pytorch/pytorch#76799]
### 🐛 Describe the bug

The gelu activation should just be a sequence of 5 elementwise operations. I've tried running an example fusing these operations with torch script shown on slide 8 from this [slide deck](https://tigress-web.princeton.edu/~jdh4/PyTorchPerformanceTuningGuide_GTC2021.pdf) from nvidia gtc but am not observing any fusion.

I used nvidia nsight to to profile the kernels and in the forward pass I see 
3 `at::native::MulScalarFunctor` calls
1 `at::native::erf_kernel_cuda`
1 `BUnaryFunctor<at::native::AddFunctor...` 

These operations make sense to me given the definition of gelu but this happens regardless of whether I call the torchscript version or not. I would expect just a single CUDA kernel in the forward followed by a reduction rather than 5 kernel calls.

I've reproduced the code here for copy paste-ability

```python
import argparse

import torch

@torch.jit.script  # JIT decorator
def fused_gelu(x: torch.Tensor) -> torch.Tensor:
    return x * 0.5 * (1.0 + torch.erf(x / 1.41421))


def unfused_gelu(x: torch.Tensor) -> torch.Tensor:
    return x * 0.5 * (1.0 + torch.erf(x / 1.41421))


def more_memory(gpu: bool) -> None:
    x = make_data(gpu)
    result = unfused_gelu(x)
    g = result.sum().backward()


def less_memory(gpu: bool, alpha=1) -> None:
    x = make_data(gpu)
    result = fused_gelu(x)
    g = result.sum().backward()


def make_data(gpu: bool = False) -> torch.Tensor:
    n1 = int(1e7)
    if gpu:
        x = torch.randn(n1, requires_grad=True, device=torch.device("cuda"))  # column vector
    else:
        x = torch.randn(n1, requires_grad=True)

    return x

def main(args: argparse.Namespace) -> None:

    more_memory(args.gpu)
    less_memory(args.gpu)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--gpu", action="store_true")

    args = parser.parse_args()

    main(args)
```

### Versions

Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: CentOS Stream release 8 (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.8.12 (default, Sep 21 2021, 00:10:52)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] (64-bit runtime)
Python platform: Linux-4.18.0-348.2.1.el8_5.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: True
CUDA runtime version: 11.4.120
GPU models and configuration: GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.7.6.5
/usr/lib64/libcudnn.so.8.2.4
/usr/lib64/libcudnn_adv_infer.so.8.2.4
/usr/lib64/libcudnn_adv_train.so.8.2.4
/usr/lib64/libcudnn_cnn_infer.so.8.2.4
/usr/lib64/libcudnn_cnn_train.so.8.2.4
/usr/lib64/libcudnn_ops_infer.so.8.2.4
/usr/lib64/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.9.0+cu111
[pip3] torch-tb-profiler==0.3.1
[conda] Could not collect

**Comment by davidberard98** [comment]
@CHDev93 
Fusion occurs _after_ the first run.

Can you try running fused_gelu multiple times and check the profiler again?

**Comment by CHDev93** [comment]
@davidberard98 thanks so much for the quick follow up! I ran it 4 times in the same script and indeed I do see fusion on the third run. I was under the impression the flow was, "if a function is uncompiled, compile it and run it, otherwise run the cached compiled version".

Your comment above implies it's actually more like, "if the function is uncompiled, run it anyway uncompiled then compile it for later"?

I think my mental model is still a little bit fuzzy because I wrote a little context manager to track peak memory usage and I observe the below for 4 runs (timing is probably junk bc I ran it under a profiler)

10 ms     381.47 MiB
59 ms     343.32 MiB
403 ms     228.88 MiB
0 ms     228.88 MiB

Looking at the profiler, I first see two calls to `at::native::erf_kernel_cuda` and then later two calls to `fused_mul_div_erf_add_mul`. So even on the second call it's still not fusing. I'm now happy that I can successfully fuse operations but if you had any more insight as to when/how it occurs, I'd be really interested to learn

**Comment by davidberard98** [comment]
The fusers require additional information that isn't available until runtime. For example, in your gelu function, the fuser needs to know what device to compile the function for (cpu or cuda) and which datatype (float, double, half, etc.).

The first run collects metadata about the tensors observed during runtime. Once this information is collected, the function can be fused and used for future invocations.

**Comment by CHDev93** [comment]
Here's the context manager I used to get the above numbers for reference

```python
import functools
import time

import torch

printnow = functools.partial(print, flush=True)

class TorchGpuProfiler:
    def __init__(self, on=True, msg=None) -> None:
        self.on = on
        self.msg = msg

    def __enter__(self):
        if self.on:
            self._start = time.perf_counter()
            self._mem_start = torch.cuda.memory_allocated()
            torch.cuda.reset_peak_memory_stats()

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.on:
            self.elapsed_time = time.perf_counter() - self._start
            self.max_memory = torch.cuda.max_memory_allocated()
            printnow(
                self.msg, f"{int(1e3 * self.elapsed_time)} ms", f"{self.max_memory / (1<<20): .2f} MiB", sep="    "
            )

```
