### ISSUE TITLE
Non symmetry of torch.median()

### ISSUE THREAD

**Issue by MaratZakirov** [pytorch/pytorch#76800]
### 🐛 Describe the bug

Following code shows non symmetry of torch.median in comparison, numpy shows perfect symmetry of its median function
```
import numpy as np
import torch

print('numpy version: %s torch version: %s' % (np.__version__, torch.__version__))
np.random.seed(1)
a = np.random.rand(100)
b = torch.tensor(a)
print(np.median(a), -np.median(-a), torch.median(b), -torch.median(-b))
```
Output:
```
numpy version: 1.18.3 torch version: 1.11.0
0.4707426463801394 0.4707426463801394 tensor(0.4499, dtype=torch.float64) tensor(0.4916, dtype=torch.float64)
```
This unexpected behavior should be at least documented, but actual documentation https://pytorch.org/docs/stable/generated/torch.median.html do not content any word about non-symmetry.

### Versions

numpy version: 1.18.3
torch version: 1.11.0

**Comment by jbschlosser** [comment]
This is because `torch.median()` does not take the mean of the two medians when there is an even number of elements, as indicated in the [note in the docs](https://pytorch.org/docs/stable/generated/torch.median.html). The note there suggests instead using `torch.quantile()` with `q=0.5` for that behavior.

**Comment by MaratZakirov** [comment]
```
The median is not unique for input tensors with an even number of elements. In this case the lower of the two medians is returned. To compute the mean of both medians, use [torch.quantile()](https://pytorch.org/docs/stable/generated/torch.quantile.html#torch.quantile) with q=0.5 instead.
```
Agree
