### ISSUE TITLE
Complex x float type promotion is incorrect

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#76803]
Typical complex x float type promotion between tensors that are rank 1+ results in a complex result with the highest "value type" among the inputs. For example:

```
a = torch.randn((2, 2), dtype=torch.cfloat)
b = torch.randn((2, 2), dtype=torch.double)
(a + b).dtype
: torch.complex128
```

In the above the complex comes from the cfloat tensor, and the double from the double tensor. And that's fine.

When working with rank 0 x rank 1+ tensors, however, the behavior is incorrect:

```
a = torch.randn((2, 2), dtype=torch.cfloat)
b = torch.tensor(1, dtype=torch.double)
(a + b).dtype
: torch.complex64

a = torch.randn((2, 2), dtype=torch.float)
b = torch.tensor(1, dtype=torch.cdouble)
(a + b).dtype
: torch.complex128
```

In the first case the datatype of the tensor with rank 2 is used, and the higher "value type" of the rank 0 tensor is ignored. This is consistent with our type promotion behavior, which biases towards tensors of rank 1+.

In the second case, however, the "value type" of the rank 0 complex tensor is used. This seems like an error.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @nairbv @ngimel

**Comment by anjali411** [comment]
Is the bug that the expected dtype in this case:

```
a = torch.randn((2, 2), dtype=torch.float)
b = torch.tensor(1, dtype=torch.cdouble)
(a + b).dtype
```

`complex64`?

**Comment by Lezcano** [comment]
> Is the bug that the expected dtype in this case: [...] `complex64`

I believe the bug is in the first case, where it should be promoted to `complex128` to avoid narrowing.

**Comment by ngimel** [comment]
THe first case is fine, it's similar to current `float tensor + double scalar = float tensor` (the issues says that first case is correct, second one isn't).

**Comment by Lezcano** [comment]
Ah, right.
I believe this is coming form these pesky exceptions:
https://github.com/pytorch/pytorch/blob/1ea49c68d05a1eb1fe81d6d7e3c49dc3e2e2caa1/tools/autograd/gen_python_functions.py#L165-L172

More context for why those are there: https://github.com/pytorch/pytorch/issues/76555#issuecomment-1112620338

**Comment by anjali411** [comment]
@kshitij12345 did this make it in time for branch cut?

**Comment by kshitij12345** [comment]
Yes, it did 🎉
