### ISSUE TITLE
Scalar x scalar type promotion is incorrect

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#76801]
```
torch.add(1, 1.)
: tensor(2.)

torch.add(1., 1.)
: tensor(2., dtype=torch.float64)
```

We should be consistently returning the default floating point type or double for both these cases. 

cc @nairbv @mruberry @ezyang @ngimel

**Comment by ezyang** [comment]
Hot take: shouldn't we just return a Python number in this case

**Comment by mruberry** [comment]
> Hot take: shouldn't we just return a Python number in this case

Yes! That would be consistent with JAX and NumPy

**Comment by ezyang** [comment]
I imagine I would probably just add a special case for this

**Comment by mruberry** [comment]
It shouldn't be too hard to special case, either, as very few operators support scalar x scalar inputs: add mul sub and div only, I think.

**Comment by ngimel** [comment]
And all their aliases https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/python_arg_parser.cpp#L84-L95, and we might want to add additional ops there to improve scalar support?
