### ISSUE TITLE
[LTC] Mark step indicator

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#76826]
### 🚀 The feature, motivation and pitch

For LTC backends that require compile and execution to happen within a mark step, it would be nice to be able to tell whether the compile is happening inside a mark step.

The motivation here is to be able to premptively prevent execution outside of a mark step. For example, the following would cause an compile/execute outside of a mark step:
```python
t = torch.zeros(2, 2)
...  # manipulate t
if torch.count_nonzero(t) > 0:  # This would cause compile/execute before mark step is reached
    ...
...
torch._lazy.mark_step()
```

Now, this may be allowed by certain backends, but will not be allowed for others, so what's needed is a way for each backend to check for this inside their backend implementation.

CC: @wconstab @desertfire @henrytwo @ke1337

**Comment by JackCaoG** [comment]
I think what you asked here is a way to avoid

https://github.com/pytorch/pytorch/blob/b557e102d80393fdf1abaaef3454f8e412bc7b2f/torch/csrc/lazy/core/lazy_graph_executor.cpp#L497

to trigger an execution that contains IR value that is not a `DeviceData`.

**Comment by antoniojkim** [comment]
Perhaps not necessarily to avoid it, but a way to know when it happens so that the backend can decide to allow it or not. Right now it just goes and does the compile/execute but there's no way to know when that compile/execute was triggered (unless of course I'm missing something).

**Comment by antoniojkim** [comment]
Proposed solution for this issue: https://github.com/pytorch/pytorch/pull/76840

**Comment by desertfire** [comment]
Is the goal to disallow a sync operation, or just to give a warning when that happens? IIRC, https://github.com/pytorch/pytorch/blob/5dd1c677768a94ee4c014438369c8a9f832a7e40/torch/csrc/lazy/core/tensor.cpp#L446 is where this kind of sync compilation and execution is triggered.

**Comment by antoniojkim** [comment]
> Is the goal to disallow a sync operation, or just to give a warning when that happens?

I think this will be backend specific. Certain backends (like the TS backend) will probably be fine with having a sync operation outside of the mark step as the compile is not particularly expensive. However, for the Cerebras backend, our compile is extremely expensive. So, we want to make sure we avoid recompiling at all costs. So, knowing whether the compile is being called inside a mark step is important.

Not sure if this is possible using what Jack suggested in [this comment](https://github.com/pytorch/pytorch/pull/76840#issuecomment-1118002704). If it is, then we don't have an issue here. But I'm not entirely convinced yet that it is.

**Comment by antoniojkim** [comment]
@JackCaoG helped to figure out an alternative solution to this issue

**Comment by antoniojkim** [comment]
[comment](https://github.com/pytorch/pytorch/pull/76840#issuecomment-1118575518)
> something I'm just now realizing now is that that information is not available at compile time. It is a local variable passed around in the lazy graph executor, but that config is not passed to the computation or the compile. So, we'll still need to mechanism of passing that information to the compile.
