### ISSUE TITLE
Windows CUDA TTS tracking task

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#76838]
Our goal for CI TTS started at 3hrs this half and was not far from there at the start of 2022. However, now we are noticing some pretty large regressions where our Windows jobs have a TTS of 4hrs (per shard!). At peak times, the TTS goes higher due to stressed queuing times. 

Actionable steps:
- Increase our pool of available Windows runners --> if feasible, this would be the ideal solution.
- Aggressively shard --> this is fine but there is an overhead we'd be eating @clee2000 
- Remove Windows CUDA job from PRs --> this would not be ideal as Windows CUDA build signal is valuable to have on pull requests. We used to have smoke tests to not test so much on Windows GPU machines, but those were not worth maintaining as the process of maintaining them was mostly manual.
- Be able to delineate TTS on the job level so we can confirm results in our metrics (compared to spot checks)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
For some stats, the queue time for windows.8xlarge.nvidia.gpu machines is currently ~40min. @seemethere is it possible to get more windows.8xlarge.nvidia.gpu runners?

**Comment by malfet** [comment]
Would it be possible to separate queueing time from runtime? And shard runtime for Win and Linux GPU should be roughly the same, shouldn't it? (And perhaps smaller on Win, as fewer tests are running on those platforms)

**Comment by seemethere** [comment]
> For some stats, the queue time for windows.8xlarge.nvidia.gpu machines is currently ~40min. @seemethere is it possible to get more windows.8xlarge.nvidia.gpu runners?

There's actually not without us going to a multi-region approach. We continuously hit our `vcpu` max limit when attempting to spin up more of these types of instances.

I want to revisit why we feel the need to test windows GPU on every PR given that the user base is small and the cost is very high.

**Comment by janeyx99** [comment]
Update: also noticed windows was unintentionally testing distributed, so @clee2000's #76848 should help with decreasing runtime (distributed tests are almost 2.5hrs today!).

**Comment by suo** [comment]
I am fine punting windows GPU back to master. But we still need to fix the TTS even if it's on master, since we want to eventually make it landcastle-blocking. And even without queueing we're ~4h TTS (30m for build, ~3.5h for tests, based on the duration metrics)

**Comment by janeyx99** [comment]
> There's actually not without us going to a multi-region approach. We continuously hit our `vcpu` max limit when attempting to spin up more of these types of instances.

Ah, I see. Is there any plan to go to multi-region in the next year?

> I want to revisit why we feel the need to test windows GPU on every PR given that the user base is small and the cost is very high. Perhaps we should go back to just doing smoke tests on these particular configurations since they do seem to be affecting TTS so much and don't provide that valuable of a signal.

We have historically included Windows GPU builds on PRs as they do sometimes break with build-system changes. We eventually expanded to include GPU tests as well to allow for consistency between PR + trunk as well as preventing reverts.

I think moving Windows CUDA to trunk only is reasonable, though we would expect to see more reverts until land validation exists. Something we can introduce to counter that in the time being is automatically adding the ciflow/trunk label whenever certain files are changed on a PR.

**Comment by suo** [comment]
So is a plausible plan:
1. Kill distributed tests, buying us effective capacity.
2. Use that capacity to increase #win shards to like 5
3. -----at this point, our TTS is under control (~2h by @clee2000's estimates)
4. Move windows GPU to master once we have landcastle-style merges enabled

**Comment by clee2000** [comment]
#77240

**Comment by suo** [comment]
TTS has improved but we still struggle significantly with queueing times during working hours. Our current vcpu quota for windows instances is 788, which means we have 788/8 = 98.5 theoretical max concurrency.

After sharding, we run 5 jobs per commit, so we can only do 19 commits at once even at theoretical peak, which is not enough to keep up during the average workday even on master only (this week has been especially bad, with more [60+ commits on more than one day](https://hud.pytorch.org/metrics)).

Given that we're trending in the wrong direction (we are increasing our commit rate on master over time, and we are also increasing how much stuff we're testing over time) I suggest we request a quota increase from AWS, maybe somewhere around 150+ max concurrent jobs (1200 vCPUs).

@seemethere, what do you think? I know it's costly but we are running out of options.

**Comment by janeyx99** [comment]
The other extreme we've discussed before is letting windows CUDA be community-supported and not something that can block land/cause reverts.
Some ways we can do this:
1. We can move it to its own branch and test on a periodic basis (since we cannot afford to run on every commit)
2. We can run a much smaller subset of "smoke" tests on it for both trunk + PRs. However, this implies that there is such a set of smoke tests, which we've attempted in the past and the results were not the most conclusive.
3. We can simply run no tests for it anywhere, and simply test the build. I think out of the 3, we can start here and expand to 2 as we identify good smoke tests.

**Comment by suo** [comment]
Okay yeah, I'd like for us to come to a final decision about this and commit to it. I'll write up a summary of the problem and our options for us to discuss further.

**Comment by suo** [comment]
Okay after sharding changes, test fixes, and capacity increases, it looks like we are in decent shape—under 3h TTS for all shards.

I am now coming after `windows-binary-wheel / wheel-py3_7-cuda11_3-test`.
- What is this? What tests does it run? Looking at the workflow it invokes [`smoke_test.bat`](https://github.com/pytorch/pytorch/blob/25ee52570e7e2215f7749775a284260fd1d0f7d3/.circleci/scripts/binary_windows_test.sh#L11) but this file doesn't exist in our repo?
- Can we run fewer (or no) tests? What are we testing that isn't covered by the actual CUDA tests?
- Can we run this nightly instead of on master?

cc @seemethere as I think you are the last person who touched these

**Comment by suo** [comment]
Oh, I'm actually wrong. The TTS for it is high because the BUILD takes so long. Whoa: e.g. https://github.com/pytorch/pytorch/runs/6493200978?check_suite_focus=true

**Comment by janeyx99** [comment]
Don't we intentionally not use sccache for binary builds? @mszhanyi @seemethere 

Maybe we should allow sccache for non-nightly builds.

**Comment by mszhanyi** [comment]
> Don't we intentionally not use sccache for binary builds? @mszhanyi @seemethere
> 
> Maybe we should allow sccache for non-nightly builds.

I didn't disable it in nightly binary builds.

From the log it might not connect the cache server correctly
```
2022-05-18T16:41:37.9712626Z [vcvarsall.bat] Environment initialized for: 'x64'
2022-05-18T16:41:38.0417981Z Stopping sccache server...
2022-05-18T16:41:39.0448545Z sccache: error: couldn't connect to server
2022-05-18T16:41:39.0450812Z sccache: caused by: No connection could be made because the target machine actively refused it. (os error 10061)
2022-05-18T16:41:39.0589270Z sccache: Starting the server...
```

I checked one old log and it looks no error when starting the sccache.
```
022-04-11T04:34:49.5975834Z (base) C:\actions-runner\_work\pytorch\pytorch>set SCCACHE_IGNORE_SERVER_IO_ERROR=1 
2022-04-11T04:34:49.5977928Z 
2022-04-11T04:34:49.5978304Z (base) C:\actions-runner\_work\pytorch\pytorch>sccache --stop-server 
2022-04-11T04:34:49.6097905Z Stopping sccache server...
2022-04-11T04:34:49.6126192Z Compile requests                      0
2022-04-11T04:34:49.6126598Z Compile requests executed             0
2022-04-11T04:34:49.6126923Z Cache hits                            0
2022-04-11T04:34:49.6127251Z Cache misses                          0
2022-04-11T04:34:49.6127573Z Cache timeouts                        0
2022-04-11T04:34:49.6127881Z Cache read errors                     0
2022-04-11T04:34:49.6128614Z Forced recaches                       0
2022-04-11T04:34:49.6128946Z Cache write errors                    0
2022-04-11T04:34:49.6129310Z Compilation failures                  0
2022-04-11T04:34:49.6129650Z Cache errors                          0
2022-04-11T04:34:49.6130010Z Non-cacheable compilations            0
2022-04-11T04:34:49.6130573Z Non-cacheable calls                   0
2022-04-11T04:34:49.6131075Z Non-compilation calls                 0
2022-04-11T04:34:49.6136436Z Unsupported compiler calls            0
2022-04-11T04:34:49.6136797Z Average cache write               0.000 s
2022-04-11T04:34:49.6137133Z Average cache read miss           0.000 s
2022-04-11T04:34:49.6137445Z Average cache read hit            0.000 s
2022-04-11T04:34:49.6137843Z Failed distributed compilations       0
2022-04-11T04:34:49.6138477Z Cache location                  S3, bucket: Bucket(name=ossci-compiler-cache, base_url=http://ossci-compiler-cache.s3.amazonaws.com/)
2022-04-11T04:34:49.6153135Z 
2022-04-11T04:34:49.6153763Z (base) C:\actions-runner\_work\pytorch\pytorch>sccache --start-server 
2022-04-11T04:34:49.6267019Z sccache: Starting the server...
2022-04-11T04:34:49.6595958Z 

```

**Comment by suo** [comment]
@mszhanyi are you investigating why the server isn't connecting properly?
