### ISSUE TITLE
More informative load_state_dict error message

### ISSUE THREAD

**Issue by neverix** [pytorch/pytorch#76886]
### 🚀 The feature, motivation and pitch

Currently, feeding a string into `torch.nn.Module.load_state_dict` results in an undescriptive exception (`AttributeError` in 1.10.2, `ValueError` in the current version). Checking for the object's type before passing the dict to hooks and raising a TypeError with an appropriate message would make the source of the error clearer, especially for new users.

### Alternatives

Adding an assert; using `typeguard`'s decorator

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by albanD** [comment]
Hi,

Thanks for the report.
We would accept a PR verifying that the type of the provided `state_dict` is indeed correct (a Mapping).
