### ISSUE TITLE
EmbeddingBag: Does CUDA calculate error in EmbeddingBag forward when include_last_offset=True ?

### ISSUE THREAD

**Issue by zejun-chen** [pytorch/pytorch#76885]
### 🐛 Describe the bug
Hi, @ezyang @jianyuh 

I am a user of pytorch and want ask some help about the EmbeddingBag.
We found that the CUDA forward output of EmbeddingBag is error(not equal to CPU output) when include_last_offset=True.
Here is our test case, you can run it directly. The mode is sum.
```
import torch
from torch import nn as nn

device = 'cuda:0'
cpu_device = 'cpu'
weight_elem = 10
weight_feature_size = 4
include_last_offset = True

embedding_sum = nn.EmbeddingBag(weight_elem, weight_feature_size, mode='sum', scale_grad_by_freq=False, include_last_offset=include_last_offset)
embedding_sum.weight.data = torch.Tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
                                          [ 0.0539,  0.6684, -0.0597, -0.4675],
                                          [-0.2153,  0.8840, -0.7584, -0.3689],
                                          [-0.3424, -1.4020,  0.3206, -1.0219],
                                          [ 0.7988, -0.0923, -0.7049, -1.6024],
                                          [ 0.2891,  0.4899, -0.3853, -0.7120],
                                          [ 0.7667,  0.0190,  0.0220,  1.1532],
                                          [-0.3393,  0.1559,  0.8966, -0.2968],
                                          [-0.6857, -0.0496, -1.2485, -0.8509],
                                          [-0.7690, -1.5606, -0.5309,  0.2178]]).data
print("sum cpu")
input = torch.Tensor([1, 2, 4, 5, 4, 3, 2, 9], device=cpu_device).long()
offsets = torch.Tensor([0, 3, 6], device=cpu_device).long()
output = embedding_sum(input, offsets)
embedding_sum.zero_grad()

print("sum cuda")
input_cuda = input.to(device)
offsets_cuda = offsets.to(device)
embedding_sum = embedding_sum.to(device)
output_cuda = embedding_sum(input_cuda, offsets_cuda)
embedding_sum.zero_grad()

print('embedding_sum weight = ', embedding_sum.weight.cpu().data)
print('cpu output = ', output)
print('cuda output = ', output_cuda.to("cpu"))
```

We get the following output:
```
cpu output  =  tensor([[ 0.6374,  1.4601, -1.5230, -2.4388],
                       [0.7455, -1.0044, -0.7696, -3.3363]], grad_fn=<EmbeddingBagBackward0>)
cuda output =  tensor([[ 0.6374,  1.4601, -1.5230, -2.4388],
                       [-0.2388, -1.6810, -2.0589, -3.4874]], grad_fn=<ToCopyBackward0>)
```
**Watch out: the second bag value of cuda output is not equal to cpu output.**
```
input    [1, 2, 4, 5, 4, 3, 2, 9]
offsets  [0, 3, 6]
```
For CUDA, the second bag's entries are: 5 4 3 2 9, while for cpu, they are 5 4 3. They are different.
```
idx  value
5    [ 0.2891,  0.4899, -0.3853, -0.7120],
4    [ 0.7988, -0.0923, -0.7049, -1.6024],
3    [-0.3424, -1.4020,  0.3206, -1.0219],
2    [-0.2153,  0.8840, -0.7584, -0.3689],
9    [-0.7690, -1.5606, -0.5309,  0.2178],
Output = 0.2388, -1.6810, -2.0589, -3.4874
```

**Thus, we wonder how to understand the doc's description for include last offsets and which implmentation is right?**
https://pytorch.org/docs/stable/generated/torch.nn.EmbeddingBag.html?highlight=embeddingbag#torch.nn.EmbeddingBag

### Version
My Env:
Torch: build from master, 36420b5e8cce9c783903bbc210ed7f2b6535ebf5
CUDA: 11.2
Device: A100
Ubuntu 20.04
Python: 3.8.12

Thank you.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by chirayuG-nvidia** [comment]
+1 seeing the same issue. Was about to file it before I found this issue. Thanks @zejun-chen  for filing.

Repro script that I wrote:
```
import torch
import numpy as np
​
table_rows = 1 * 1000000
vector_dim = 128
​
cpu = torch.device("cpu")
device = torch.device("cuda:0")

# init embeddingBag object
embedding_sum = torch.nn.EmbeddingBag(table_rows, vector_dim, mode='mean', include_last_offset=True).to(device)
​
# declare indices, offset tensors
input = torch.tensor([1,2,4,5,4,3,2,9,
                      21,32,44,65,74,93,92,349,
                      451,782,4988,5454,4454,3654,2345,439,
                      1433,24343,44343,543,453,353,2534,349,], dtype=torch.long).to(device)
​
offsets = torch.tensor([0, 4, 5, 8, 13, 13, 15, 17,
                        18,20,21,25,28, 29, 30, 31,
                        31], dtype=torch.long).to(device)
# GPU lookup​
e_out = embedding_sum(input, offsets)
​print (e_out.shape)
​
# CPU lookup
e_out_cpu = embedding_sum.to(cpu)(input.to(cpu), offsets.to(cpu))
cmp = torch.eq(e_out.to(cpu), e_out_cpu)
print (cmp, cmp.shape) # output should match
```
```
torch.Size([16, 128])
tensor([[ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        ...,
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [False, False, False,  ..., False, False, False]]) torch.Size([16, 128])
```
```

**Comment by zejun-chen** [comment]
Thank you @chirayuG-nvidia
Have seen your PR https://github.com/pytorch/pytorch/pull/77012, it corrects this bug :)

**Comment by soulitzer** [comment]
Reopening this issue for discussion.

Correct me if I'm wrong, but it seems like the CPU implementation of "include_last_offset" is backward. The docs say:
```
 if True, offsets has one additional element, where the last element is equivalent to the size of indices.
```
We should get an extra bag when `include_last_offset` is True, but currently it's doing the opposite. What the CUDA implementation is doing is hardcoding the case where `include_last_offset` is True, so it also seems wrong, because it would have another bag if that is case as well.

**Comment by chirayuG-nvidia** [comment]
Original issue that added the `include_last_offset` flag: https://github.com/pytorch/pytorch/issues/29019 

My interpretation is that the CPU implementation is correct. Primary motivation of `include_last_offset` is to make the layer CSR format friendly and the offset buffer in CSR contains N+1 values for N rows (bags) worth of data.

**Comment by chantat** [comment]
I think the above's case where the last offset is not equal to the size of indices should be supported as a valid input. For us, we found it particularly useful when we use CSR format tensors with CUDA graphs. Since we pad the indices with dummy data (because CUDA graphs require input tensors to be static shape), the fix here would allow us to early stop our computation leading to significant performance improvements.    

If we agree to support that as a valid input, it should behave the way it is doing with the CPU implementation.

**Comment by jbschlosser** [comment]
I argue [on a relevant PR](https://github.com/pytorch/pytorch/pull/57208#issuecomment-1021727378) that we should allow `0 <= offsets[-1] <= input.size(0)` for flexibility, and it looks like @chantat relies on this. The inconsistencies between CPU and CUDA should certainly be addressed. Now that there is some recent activity, maybe it's worth picking this up again soon? @kurtamohler

**Comment by zejun-chen** [comment]
The issue is fixed.
