### ISSUE TITLE
EmbeddingBag raises RuntimeError if input is on the wrong device 

### ISSUE THREAD

**Issue by nikitakit** [pytorch/pytorch#7689]
## Issue description

`EmbeddingBag` raises a `RuntimeError` if its weights are on the GPU, but the input is on the CPU.

## Code example
```python
import torch
bow = torch.nn.EmbeddingBag(10, 10).cuda()
test = torch.tensor([[1, 2]], dtype=torch.long).cpu()
bow(test)
```

Result: `RuntimeError: get_device is not implemented for type torch.LongTensor`
Expected result: a more informative error about device mismatch

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 384.81
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by t-vi** [comment]
So `checkSameGPU` in `TensorUtils.cpp` calls `TensorArg->get_device` which is only implemented for cuda. The options seem to be amending checking for cuda before doing that in `checkSameGPU`, doing a cuda check before calling it or implementing `get_device` for CPU. I'm leaning towards the first because we'd probably not be able to use the output of `get_device` for CPU in the error message.

**Comment by zou3519** [comment]
@t-vi the first one would be great (checking for CUDA before calling get_device) in TensorUtils.cpp.

Some day we might have a `get_device` function for CPU, but I think the above is a good workaround for now.

**Comment by t-vi** [comment]
OK, thanks, I'll do that.
