### ISSUE TITLE
[bug] floating precision issue with the dot product between 2 vectors

### ISSUE THREAD

**Issue by iondel** [pytorch/pytorch#7692]
Hi, 

I came across this problem while using pytorch:

The dot product between 2 vectors with floating precision can become arbitrarily small/large. This problem does not occur when using the sum and product operation separately:

```
v1, v2 = torch.FloatTensor([1., 1.]), torch.FloatTensor([-1., -0.9999999])
float(v1 @ v2), float(torch.sum(v1 * v2))  
(-3.6893488147419103e+19, -1.9999998807907104)
```

Dot product with tensors with double precision seems ok:

```
v1, v2 = torch.DoubleTensor([1., 1.]), torch.DoubleTensor([-1., -0.9999999])
float(v1 @ v2), float(torch.sum(v1 * v2))
(-1.9999999000000002, -1.9999999000000002)
```

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.4
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.0)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by t-vi** [comment]
This look like bug #7064 to me.

**Comment by iondel** [comment]
Sorry for the duplicate, I didn't spot that one. 

Following [#7064](https://github.com/pytorch/pytorch/issues/7064), updating mkl:

```
$ conda update mkl
```

**Comment by iondel** [comment]
solved the problem.
