### ISSUE TITLE
[feature request] Calling autograd.grad inside autograd.Function

### ISSUE THREAD

**Issue by rtqichen** [pytorch/pytorch#7698]
I'm trying to implement something where I'd like to be able to compute the gradients of existing autograd functions inside a new autograd.Function, but it seems that even with the new 0.4 changes this cannot be done yet. It'd be great if this could be supported.

Here is a trivial new Function that just wraps around an existing one:
```
import torch
from torch.autograd import Function


class TanhWrapper(Function):

    @staticmethod
    def forward(ctx, inputs):
        ctx.save_for_backward(inputs)
        return torch.tanh(inputs)

    @staticmethod
    def backward(ctx, grad_outputs):
        inputs, = ctx.saved_tensors
        inputs.requires_grad = True
        print(inputs.requires_grad)
        outputs = torch.tanh(inputs)
        print(outputs.requires_grad)
        return torch.autograd.grad(outputs, inputs, grad_outputs, retain_graph=False)[0]


if __name__ == '__main__':
    x = torch.randn(2, 2).requires_grad_(True)

    y = TanhWrapper.apply(x)
    y.sum().backward()
    print(x.grad)
```

This prints out 
```
True
False
...
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by t-vi** [comment]
The error message is not where you call `autograd.grad` but about not using a Tensor that requires grad to differentiate by. As this is not a bug, I think you'll get better advice in the [PyTorch forum](https://discuss.pytorch.org/) than here.

**Comment by t-vi** [comment]
PyTorch does have all the features you need for this to work as an autograd Function.

In fact, while updating my [implicit function notebook](https://github.com/t-vi/pytorch-tvmisc/blob/master/misc/Implicit_Functions_Pytorch.ipynb) and removing the obsolete claim that it doesn't work I added a few notes for making the implicit function autograd Function into a fixed point Function at the end of the worksheet.

**Comment by rtqichen** [comment]
I see now, thanks! Seems like `no_grad` is the default behavior in backward.
Your code is very helpful. I'll be looking into it in more detail.
