### ISSUE TITLE
Unnecessary _verify_batch_size check in F.batch_norm?

### ISSUE THREAD

**Issue by yangyanli** [pytorch/pytorch#77014]
### 🐛 Describe the bug

F.batch_norm raises value error when batch size is 1.

```python
import torch
x = torch.tensor([[1.0, 2.0]])
bn = torch.nn.BatchNorm1d(2)
bn(x)
```

Traceback:

```
Traceback (most recent call last):
  File "path/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-16-81e862f8e955>", line 4, in <module>
    bn(x)
  File "path/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "path/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "path/lib/python3.8/site-packages/torch/nn/functional.py", line 2280, in batch_norm
    _verify_batch_size(input.size())
  File "path/lib/python3.8/site-packages/torch/nn/functional.py", line 2248, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 2])
```

The restriction on batch size is not stated in the document. Is this restriction necessary for any reason?

I have dynamic batch size in my model, and it could be 1 in some cases. Due to the aforementioned error, I have to work around by expand the batch size to 2, bn, and then slice the results back to batch size 1.

### Versions

PyTorch version: 1.10.0a0+git71f889c
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.23.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080 with Max-Q Design
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.10.0a0+git71f889c
[pip3] torch-optimizer==0.3.0
[pip3] torch-tb-profiler==0.3.1
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by yangyanli** [comment]
> Hey @yangyanli, the reason for this restriction is that normalizing over a single element batch results in a zero output (i.e. single value - the mean of that single value = 0), which is probably not what you want.

Yes, when track_running_stats is set to False. However,  I think it is set to True in the majority of the use cases. With the running stats, the formulation is meaningful, no?

**Comment by jbschlosser** [comment]
> Yes, when track_running_stats is set to False. However, I think it is set to True in the majority of the use cases. With the running stats, the formulation is meaningful, no?

When `track_running_stats=True`, the running stats will be updated using the computed mean / variance from each batch. For a single element batch, the variance is zero, which will skew the running stats.

**Comment by yangyanli** [comment]
Many thanks for the clarification, @jbschlosser ! 

Now I do think batch size one deserves a special handling, and raising an error there is appropriate.
