### ISSUE TITLE
[FSDP] Crashing at end of training epoch, e1 on clusters, e7+ on single node - collective timeouts, NCCL comm aborts

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#77030]
### 🐛 Describe the bug

Using 504 Nightlies - training with 800M, 3B, 11B T5 models, on cluster and on single node.   Code is all from:
https://github.com/lessw2020/t5_11  
(run it with  "torchrun --nnodes=1 --nproc_per_node=8 --rdzv_id=101 --rdzv_endpoint="localhost:5668" main_elastic.py")
 
Single node is cleaner scenario:

end of epoch 1 - receive All gather sequence out of order warning...this is linked to issue:  https://github.com/pytorch/pytorch/issues/76553 (Investigate execution order)
continue training...
set new val loss record...

crash at end of epoch 8 due to:
[E ProcessGroupNCCL.cpp:737] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3742816, OpType=_ALLGATHER_BASE, Timeout(ms)=1800000) ran for 1801750 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3742816, OpType=REDUCE, Timeout(ms)=1800000) ran for 1801377 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3742816, OpType=_ALLGATHER_BASE, Timeout(ms)=1800000) ran for 1801790 milliseconds before timing out.
(repeated on all ranks)

Which then causes the NCCL communicator on various ranks to abort with full on crash:
RuntimeError: NCCL communicator was aborted on rank 0.  Original reason for failure was: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=3742816, OpType=REDUCE, Timeout(ms)=1800000) ran for 1801377 milliseconds before timing out.
Exception raised from getNcclComm at ../torch/csrc/distributed/c10d/NCCLUtils.cpp:22 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f6b271b3b42 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f6b271b01db in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x149a78 (0x7f6b7fe3ea78 in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #3: c10d::ProcessGroupNCCL::_allgather_base(at::Tensor&, at::Tensor&, c10d::AllgatherOptions const&) + 0x51d (0x7f6b7fe5204d in /home/ubuntu/anaconda3/envs/pytorch_p38/lib/python3.8/site-packages/torch/lib/libtorch_cuda_cpp.so)

full log attached as pdf. 
[end of epoch 8 crash, collective timeout.pdf](https://github.com/pytorch/pytorch/files/8645812/end.of.epoch.8.crash.collective.timeout.pdf)

 
On cluster:
at end of epoch 1 - consistent crashing at end of epoch 1.  The visual output varies and is expressed as 'device out of space' to 'GPU x is failing', broken pipe, etc. along with various warnings/errors. 
The one consistency is that it always happens at the end of the first epoch, just as training finishes and unable to ever move beyond epoch 1 on cluster training with FSDP.  This maps to exactly when we typically see the out of sequence warning on single node as noted above. 
It may be that the out of sequence on single node is more tolerable vs on cluster and inter-node comms, it crashes immediately. The resulting errors seem to be follow on rather than cause.

I have additional log examples from cluster, but it appears a clearer breakout of events on single node and the above pdf has full call stack for review.

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220506+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.27

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1072-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.12.0.dev20220506+cu113
[pip3] torch-model-archiver==0.5.0b20211117
[pip3] torch-workflow-archiver==0.2.0b20211118
[pip3] torchserve==0.5.0b20211117
[pip3] torchtext==0.11.0
[pip3] torchvision==0.13.0.dev20220506+cu113
[pip3] vit-pytorch==0.35.2
[conda] blas                      1.0                         mkl  
[conda] captum                    0.4.1                         0    pytorch
[conda] cudatoolkit               11.1.1               h6406543_9    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h95df7f1_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] mypy_extensions           0.4.3            py38h578d9bd_4    conda-forge
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] numpydoc                  1.1.0                      py_1    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.12.0.dev20220506+cu113          pypi_0    pypi
[conda] torch-model-archiver      0.5.0                    py38_0    pytorch
[conda] torch-workflow-archiver   0.2.0                    py38_0    pytorch
[conda] torchserve                0.5.0                    py38_0    pytorch
[conda] torchtext                 0.11.0                     py38    pytorch
[conda] torchvision               0.13.0.dev20220506+cu113          pypi_0    pypi
[conda] vit-pytorch               0.35.2                   pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by lessw2020** [comment]
Ran another training run - resulted in same crash at end of Epoch 4.  
Plan is to move to P3 and run similar training to see if this is A100 hardware related or FSDP issue proper (or combination). 

![Uploading 3B_fp32_NCCLComm_abort_rank0.png…]()

**Comment by lessw2020** [comment]
<img width="1674" alt="3B_fp32_Reduce_timeout" src="https://user-images.githubusercontent.com/46302957/167305649-32a20eec-37c5-454c-b17a-c0106f8acc5c.png">

**Comment by lessw2020** [comment]
<img width="1674" alt="3B_fp32_Reduce_timeout" src="https://user-images.githubusercontent.com/46302957/167305677-f4ab89e4-f870-476a-b4f3-76f8feba52dc.png">

**Comment by lessw2020** [comment]
One more repro case - in order to differentiate potential A100 hardware issues (receiving some nvlink errors) ran another 10 epoch training run on P3 single node.
It hung midway through epoch 9.  Allowed 2 hours to see if it could recover but was perm hung/frozen.
Received the usual params out of synch warning at end of epoch 1 as well. 
<img width="994" alt="fsdp_hang_800M_p3" src="https://user-images.githubusercontent.com/46302957/167318954-caa8d0c8-2272-4106-9106-8068f919b325.png">
<img width="637" alt="p3_hang_gpu_view" src="https://user-images.githubusercontent.com/46302957/167318955-aaf19b5b-cf22-407c-bcf9-d966df66c164.png">
<img width="1006" alt="p3_epoch_1_warning_oos" src="https://user-images.githubusercontent.com/46302957/167318956-948ee213-3983-4ec6-a51b-0366d4e2fa21.png">

**Comment by lessw2020** [comment]
Additional update in short form (have additional data as needed). 
I turned off activation checkpointing for the next run...that was the first run yet to go to all 10 epochs. 
I then re-ran but turned activation checkpointing ON (the default) ...and then hung during epoch 8 in similar fashion as before.

Also, Hamid ran to epoch 10 but without a validation loop involved. 

So it seems we have three variables at play - cluster or single node, validation loop or not, and activation checkpointing or not:
cluster = **crash** at end of epoch 1, right at end of training.  Crashes with or without validation loop.
single node = **hangs** by epoch 8 if running with validation loop and activation checkpointing.
single node = completes - if run with validation loop and no activation checkpointing. 
single node = completes - if run with no validation loop but with activation checkpointing. 

Attached images from the hang on epoch 8, with activations and with validation loop:
<img width="1155" alt="activation_hang_8_800M" src="https://user-images.githubusercontent.com/46302957/167466648-7b51199d-dcfe-46f3-bf94-2114267bc385.png">
<img width="619" alt="activation_crash_e8_800_gpus" src="https://user-images.githubusercontent.com/46302957/167466650-d06e983d-3ac0-4cf9-a4e5-38b1fba6ec9b.png">

**Comment by lessw2020** [comment]
I was able to pin this down to the following scenario (single node):
run with validation loop and activation checkpointing  = hang by roughly epoch 8. 

In thinking about it, I suspect the core issue is timing between completion is more varied due to activation checkpointing, and then when ranks go into lockdown via the .eval() mode from the training loop, some ranks get locked out from late requests = hang.

**Comment by lessw2020** [comment]
It worked -  Verified with 2 separate runs, 10 epochs each.     
Workaround = I added a dist.barrier() before the validation step (and hence before any rank could call eval())...and then was able to run 2x with no issue, while having both a validation loop and using activation checkpointing.  
This is what would always hang by ~ epoch 8 before on single node.
This appears to let us proceed with training normally now...that's not 'the fix' but with it, we are no longer blocked regarding training. 
<img width="776" alt="block_for_validation" src="https://user-images.githubusercontent.com/46302957/167518644-308d25e5-5d04-49bb-81b9-279cf95d3879.png">
<img width="1110" alt="dist_barrier_no_hang_2" src="https://user-images.githubusercontent.com/46302957/167518650-bc9c3760-99e2-4d5c-a080-e26ca97c5f2f.png">

**Comment by zhaojuanmao** [comment]
the warning should not be related, @awgu had a fix for the warning and will be landed soon. 

will run the updated script and see whether hang still exists

**Comment by zhaojuanmao** [comment]
@lessw2020 I can not reproduce the hang or crash in my setup, I tried the training and it trained 10 epoches without issue. It may be related to your setup?

Times per epoch:
epoch 0, time 6143.40
epoch 1, time 6083.00
epoch 2, time 6093.86
epoch 3, time 6118.01
epoch 4, time 6103.78
epoch 5, time 6100.60
epoch 6, time 6115.45
epoch 7, time 6096.48
epoch 8, time 6124.08
epoch 9, time 6116.12


Train config: 

class train_config:
    # general
    host_port: str = "12368"

    # model
    model_name = "google/t5-v1_1-large"  # "google/t5-v1_1-small"
    tokenizer = "t5-large"
    # available models
    ## t5-base
    # google/t5-v1_1-small
    # google/t5-v1_1-base
    # google/t5-v1_1-large
    # google/t5-v1_1-xl  #3b
    # google/t5-v1_1-xxl #11b
    save_model: bool = True
    model_checkpoint = "t5_small_save.pt"
    print_sharding_plan: bool = False

    # dataloaders
    num_workers_dataloader: int = 2

    # policies
    fsdp_unit_size = 1000000
    use_mixed_precision: bool = True
    activation_checkpointing: bool = True

    # datasets
    dataset_train = "datasets_grammar/grammar_train.csv"  # grammar_13k.csv
    dataset_test = "datasets_grammar/grammar_validation.csv"

    # training
    batch_size: int = 2
    num_epochs: int = 10

    # validation
    run_validation: bool = True
    val_batch_size = 2

    # logging
    track_memory = True
    memory_report: bool = True
    nccl_debug_handler: bool = True

**Comment by zhaojuanmao** [comment]
for t5 slurm script, added "export NCCL_SOCKET_IFNAME="eth0,en,eth,em,bond""

**Comment by zhaojuanmao** [comment]
closing it for now
