### ISSUE TITLE
DISABLED test_forward_mode_AD_nn_functional_max_unpool2d_cuda_float64 (__main__.TestGradientsCUDA)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#77039]
platforms: rocm

This test is *unexpectedly succeeding* intermittently on ROCm.

Examples:
https://hud.pytorch.org/failure/RuntimeError%3A%20test_ops_gradients%20failed!

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by clee2000** [comment]
Closing as this issue doesn't actually disable anything anymore since the test got renamed
