### ISSUE TITLE
`collect_env.py` can fail to detect pip packages on Windows

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#77063]
In pytorch/vision#5953, the env collection script did not work correctly on Windows. [It didn't collect any packages from `pip`](https://github.com/pytorch/vision/issues/5953#issuecomment-1119214369) leading us to believe that the user env is broken. It later turned out that there were [packages in the env](https://github.com/pytorch/vision/issues/5953#issuecomment-1120645455) that were silently ignored by the script.

Given that the only difference between Windows and other platforms for this is the "grep" command

https://github.com/pytorch/pytorch/blob/621ff0f9735cd8c4c5d6becb291ad050c35e01c0/torch/utils/collect_env.py#L278-L284

might it be possible that `findstr` is not available on all machines? #39136 made this more robust, but it might not be enough. cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ezyang** [comment]
I'd recommend not using grep, let's just read in the string to Python and search for it ourselves
