### ISSUE TITLE
DISABLED test_data_parallel_module_cuda_float32 (__main__.TestDataParallelDeviceTypeCUDA)

### ISSUE THREAD

**Issue by b0noI** [pytorch/pytorch#77085]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_data_parallel_module_cuda_float32%2C%20TestDataParallelDeviceTypeCUDA)).

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by jaglinux** [comment]
Test ran successfully after applying https://github.com/pytorch/pytorch/pull/78824
cc @jeffdaily
