### ISSUE TITLE
all_gather not working with NCCL Backend

### ISSUE THREAD

**Issue by Asciotti** [pytorch/pytorch#77090]
### 🐛 Describe the bug

When using NCCL backend, my code stalls on `all_gather` when using nodes > 1 (aka multi-nodes) regardless of number of GPUs. However, it does not stall when using 1 node but any number of GPUs. This issue is actually stemming from trying to get `DDP` working; however, the `all_gather` call underneath that initialization led me to here.

** Big note, I cannot get this to run with `Gloo` either but im primarily interested in `nccl` **

```
import os
import torch.distributed as dist
import torch.nn as nn
import torch

if __name__ == "__main__":
    local_rank = int(os.environ["LOCAL_RANK"])
    print("Local rank gpu: ", local_rank)
    torch.cuda.set_device(local_rank)
    dist.init_process_group(backend="nccl")

    tensor_list = [torch.zeros(2, dtype=torch.int64).cuda() for _ in range(2)]
    tensor = torch.arange(2, dtype=torch.int64).cuda() + 1 + 2 * local_rank
    print(tensor)
    dist.all_gather(tensor_list, tensor)
    print(tensor_list)
```

If I call it single node with any of the invocations below, it works.

### Single node, 1 gpu (I change the list to only generate/collect 1object in this case)
```
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 ddp.py
```

### Single node, 2 gpus
```
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0,1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL python -m torch.distributed.launch --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 ddp.py
```

### Single node, 2 gpus, each called from different terminal
```
# terminal 0
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0 bNCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 ddp.py
```

```
# terminal 1
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=1 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 ddp.py
```

### Multiple node, single gpu on each (so 2 total)

As soon as I move to multiple nodes it stalls in the `all_gather`

```
# node 0
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 ddp.py
```

```
# node 1
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=ALL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 ddp.py
```

Logs on node 1:
```
tensor([1, 2], device='cuda:0')
ddp-1:2766:2766 [0] NCCL INFO Bootstrap : Using eth0:10.106.88.167<0>
ddp-1:2766:2766 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ddp-1:2766:2766 [0] NCCL INFO NET/IB : No device found.
ddp-1:2766:2766 [0] NCCL INFO NET/Socket : Using [0]eth0:10.106.88.167<0>
ddp-1:2766:2766 [0] NCCL INFO Using network Socket
ddp-1:2766:2798 [0] NCCL INFO init.cc:260 Mem Alloc Size 18872 pointer 0x7f1dd8001200
ddp-1:2766:2798 [0] NCCL INFO misc/utils.cc:30 Mem Alloc Size 12 pointer 0x7f1dd800b440
ddp-1:2766:2798 [0] NCCL INFO init.cc:279 Cuda Host Alloc Size 4 pointer 0x7f1ddd800000
ddp-1:2766:2798 [0] NCCL INFO init.cc:286 Mem Alloc Size 311296 pointer 0x7f1dd800c230
ddp-1:2766:2798 [0] NCCL INFO include/enqueue.h:50 Mem Alloc Size 24 pointer 0x7f1dd8058240
ddp-1:2766:2798 [0] NCCL INFO init.cc:305 Mem Alloc Size 8 pointer 0x7f1dd8058290
ddp-1:2766:2798 [0] NCCL INFO init.cc:306 Mem Alloc Size 8 pointer 0x7f1dd80582b0
ddp-1:2766:2798 [0] NCCL INFO init.cc:309 Mem Alloc Size 16 pointer 0x7f1dd80582d0
ddp-1:2766:2798 [0] NCCL INFO init.cc:310 Mem Alloc Size 16 pointer 0x7f1dd80582f0
ddp-1:2766:2798 [0] NCCL INFO bootstrap.cc:330 Mem Alloc Size 128 pointer 0x7f1dd8058310
...
it freezes
```

I looked at https://github.com/pytorch/pytorch/issues/18689 and https://github.com/pytorch/pytorch/issues/75619 added the solutions to my script.

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.26

Python version: 3.7.5 (default, Feb 23 2021, 13:22:40)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.14.238-182.422.amzn2.x86_64-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 470.57.02
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] torch==1.11.0
[conda] Could not collect
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang

**Comment by zhaojuanmao** [comment]
Try following: 
1. remove CUDA_VISIBLE_DEVICE environment variable, as you've already set_device in your codes
2. try to use 'torchrun' instead of using 'torch.distributed.launch'
3. try to set up env vars "export NCCL_SOCKET_IFNAME="eth0,en,eth,em,bond"

**Comment by Asciotti** [comment]
Thanks for the reply!

> Try following:
> 
> 1. remove CUDA_VISIBLE_DEVICE environment variable, as you've already set_device in your codes
`CUDA_VISIBLE_DEVICES`  just merely isolates which GPUs are available to the system, correct? I have 4 GPUs on my machine but I wanted to make the environment less complicated so I figured I would try this with only 2 of them.

> 2. try to use 'torchrun' instead of using 'torch.distributed.launch'
I will!

> 3. try to set up env vars "export NCCL_SOCKET_IFNAME="eth0,en,eth,em,bond"
I will give it a shot!

**Comment by Asciotti** [comment]
Update: Same freezing behavior with all changes. As I mentioned when using `gloo` this also freezes but during the `init_process_group`. Do you know if that is relevant? Why would the `init_process_group` succeed with `nccl` but not `gloo`?

**Comment by Asciotti** [comment]
Is there a definitive way to be calling these scripts from the command line, there are too many resources that contradict each other.

If i use `master_addr/port` I can at least get a `c10d` backend store setup between the nodes, but using the `rdzv` setup which is currently in the official torch docs [here](https://github.com/pytorch/pytorch/blob/master/torch/distributed/run.py#L112) leads to connection issues. I am pretty confident in the node's communication access b/c `netcat/telnet` works between them and Ive logged via `tcpdump` them connecting using `nccl` backend (just not `gloo`).

** Is there an official way of calling these scripts and a minimal working example for multi-node, multi-gpu functionality? **

**Comment by zhaojuanmao** [comment]
@Asciotti did you try torchrun? does it work for you? here is the torch run documentation https://pytorch.org/docs/stable/elastic/run.html

@kiukchung is there some torchrun sample script for users to try?

**Comment by Asciotti** [comment]
> @Asciotti did you try torchrun? does it work for you? here is the torch run documentation https://pytorch.org/docs/stable/elastic/run.html


I did try torchrun as mentioned - same exact "freezing" in the exact same spot. 

I have a feeling something else is wrong besides my code, something that has to do with networking/gpu connectivity but I'm not entirely sure who to seek help from. This is blocking our work on getting past single-node training, which limits the data and model sizes we can look to leverage.

Do you have any recommendations? My next thing is to try https://github.com/NVIDIA/nccl-tests with GPU connectivity across nodes, but they use `openmpi` to do cross-node comms and torch does not as I understand. So it wouldn't exactly be an apples-to-apples comparison.

**Comment by zhaojuanmao** [comment]
This is a working slurm script I'm using recently on AWS cluster for your reference. you can ignore the efa, dcgmi, "--prolog job_prolog.sh --epilog job_epilog.sh" stuffs.  Hope it helps. Meanwhile waiting for @kiukchung who may have some sample script


#!/bin/bash

#SBATCH --job-name=trainer

#SBATCH --ntasks=2

#SBATCH --nodes=2

#SBATCH --gpus-per-task=8

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

echo Node IP: $head_node_ip
export LOGLEVEL=INFO
# Enable for A100
export FI_PROVIDER="efa"

# debugging flags (optional)
export NCCL_DEBUG=WARN
export NCCL_DEBUG_SUBSYS=WARN
export PYTHONFAULTHANDLER=1

export LD_LIBRARY_PATH=/opt/amazon/efa/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
export CUDA_LAUNCH_BLOCKING=0

# on your cluster you might need these:
# set the network interface
export NCCL_SOCKET_IFNAME="eth0,en,eth,em,bond"
dcgmi profile --pause
srun --prolog job_prolog.sh --epilog job_epilog.sh torchrun --nnodes 2 --nproc_per_node 8 --rdzv_id 101 --rdzv_backend c10d --rdzv_endpoint "$head_node_ip:29500" ./main_elastic.py
dcgmi profile --resume

**Comment by Asciotti** [comment]
Thanks! It will take a bit to test this one out due to permissions on our cloud, but I appreciate it.

I tried this with Pytorch lightning as well, same exact freezing in the exact same `all_gather` call under the hood in the `DDP` init portion - for whatever that is worth.

**Comment by kwen2501** [comment]
Other than the above suggestions, I recommend first checking if the two AWS instance can talk to each other. Simply try ssh'ing from one node to the other to see if they are accessible.

If the initialization still hangs, please try acquiring NCCL logs with the following debug options (on both nodes):
`NCCL_DEBUG=INFO`
`NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH,COLL`
(Your NCCL log above is too short and buried by all the memory allocation logs)

**Comment by Asciotti** [comment]
> Other than the above suggestions, I recommend first checking if the two AWS instance can talk to each other. Simply try ssh'ing from one node to the other to see if they are accessible.

They can connect (at least to my experiments) across all ports without any constraints. I've confirmed via `telnet/netcat` and when using the multi-node setup the `rdzv` backend it set to be hosted on my `node 0` and that `init_process_group` setup succeeds and I did see network connectivity between the two nodes by checking `lsof`.

They do not have SSH permissions b/c that requires running sshd which we dont. Is ssh required? I did not see that in any of the documentation.



> If the initialization still hangs, please try acquiring NCCL logs with the following debug options (on both nodes): `NCCL_DEBUG=INFO` `NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH,COLL` (Your NCCL log above is too short and buried by all the memory allocation logs)

I cropped some of the logs, let me re-run and display the full set.

**Comment by Asciotti** [comment]
@kwen2501 I did as suggested, here are the two logs..

# node 0
```
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH,COLL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 blah.py 
/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Local rank gpu:  0
tensor([1, 2], device='cuda:0')
ddp-0:34352:34352 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0,en,eth,em,bond
ddp-0:34352:34352 [0] NCCL INFO Bootstrap : Using eth0:10.106.161.186<0>
ddp-0:34352:34352 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ddp-0:34352:34352 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0,en,eth,em,bond
ddp-0:34352:34352 [0] NCCL INFO NET/IB : No device found.
ddp-0:34352:34352 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0,en,eth,em,bond
ddp-0:34352:34352 [0] NCCL INFO NET/Socket : Using [0]eth0:10.106.161.186<0>
ddp-0:34352:34352 [0] NCCL INFO Using network Socket
NCCL version 2.10.3+cuda10.2
```

# node 1
```
NCCL_SHM_DISABLE=1 CUDA_VISIBLE_DEVICES=0 NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH,COLL python -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="ddp-0.ddp.ml-dev.svc.cluster.local" --master_port=12345 blah.py
/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Local rank gpu:  0
tensor([1, 2], device='cuda:0')
ddp-1:29012:29012 [0] NCCL INFO Bootstrap : Using eth0:10.106.72.56<0>
ddp-1:29012:29012 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ddp-1:29012:29012 [0] NCCL INFO NET/IB : No device found.
ddp-1:29012:29012 [0] NCCL INFO NET/Socket : Using [0]eth0:10.106.72.56<0>
ddp-1:29012:29012 [0] NCCL INFO Using network Socket
```

@zhaojuanmao, torchx's volcano does not support a piece of functionality that we need in our infra to test things out
https://github.com/volcano-sh/volcano/issues/2247

**Comment by Asciotti** [comment]
Update: I am actually able to get this working across multiple nodes, with <2 GPUS on each node. We had linkerd running in our kube cluster which seemed to be affecting the traffic across the nodes.

I will close this but might open another ticket since I am still having issues scaling up to more than 2 gpus on each node. I went through all the various `NCCL_X` settings and no dice.

**Comment by rom1504** [comment]
Hitting a very similar issue, did you have any more success @Asciotti ?

**Comment by Asciotti** [comment]
@rom1504 No, I haven't looked at it any further, I also haven't tried all the various `NCCL_X` settings (like `NCCL_P2P_DISABLE`) that i've seen others have success with. Nor have I tried different pytorch/lightning/python versions. It's a total crap shoot when and how these things will behave reliably.

If you find anything let me know, i'll do the same.

**Comment by mory91** [comment]
I'm having a similar problem but in a 3 VM environment, any idea?

**Comment by sinamps** [comment]
I have the same issue; but even with 1 GPU per node, I cannot get a successful run of pytorch all_reduce on multiple nodes.
