### ISSUE TITLE
Overriding `__getattribute__` is not enough in `stateless.functional_call`

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#77133]
### 🐛 Describe the bug

In `_stateless.functional_call`, it is not sufficient to override `__getattribute__` - we also need to override `__setattr__`.

```
from torch.nn.utils.stateless import functional_call
import torch.nn as nn
import torch
from functorch.compile import memory_efficient_fusion, print_compile, draw_graph_compile, default_decompositions

class Foo(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('foo', torch.zeros(()))

    def forward(self, x):
        self.foo = self.foo + 1
        return x + self.foo

a = {'foo': torch.zeros(())}
mod = Foo()
print(mod.foo)
functional_call(mod, a, torch.ones(()))
print(mod.foo)
```

results in 
```
tensor(0.)
tensor(1.)
```

In other words, despite overriding a value with `functional_call`, we are still modifying the original buffer with `__setattr__`.

We probably need to override `__setattr__` to also look at the `_functional_values` dict.

cc: @albanD @jbschlosser @emcastillo 

### Versions

Nightly

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by jbschlosser** [comment]
Nice catch! The true buffer should definitely not be updated by `functional_call`. My only question is what the semantics around the dict passed to `functional_call` should be - would it be expected that the dict be updated with the set values?

```python
a = {'foo': torch.zeros(())}
mod = Foo()
print(a)  # {'foo': tensor(0.)}
functional_call(mod, a, torch.ones(()))
print(a)  # Should this be {'foo': tensor(0.)} or {'foo': tensor(1.)} ?
```

Might be useful to users to get access to the post-call values.

**Comment by albanD** [comment]
I would expect `{'foo': tensor(1.)}` personaly.
