### ISSUE TITLE
Add Tensor compare support for MPS backend

### ISSUE THREAD

**Issue by kulinseth** [pytorch/pytorch#77144]
### 🐛 Describe the bug

Currently the MPS backend doesn't support all the operations needed for assertEqual. So currently the tensors on `mps` are mapped to cpu and the Equal operation is performed on CPU. This issue tracks enabling all the necessary operations for MPS backend and not-falling back to CPU. This issue was currently identified [here.](https://github.com/pytorch/pytorch/pull/76725/files#r866238060)

### Versions

Python version: 3.8.11 (default, Aug  6 2021, 08:56:27)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.0
[pip3] torch==1.12.0a0+gitcfd4b64
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-include               2022.0.0           hecd8cb5_105
[conda] mkl-service               2.4.0            py38h9ed2024_0
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] nomkl                     3.0                           0
[conda] numpy                     1.21.2           py38h0fa1045_0
[conda] numpy-base                1.21.2           py38hbbe2e76_0
[conda] torch                     1.12.0a0+gitcfd4b64          pypi_0    pypi

**Comment by pmeier** [comment]
The logic mentioned by @kulinseth is

https://github.com/pytorch/pytorch/blob/25c6ebd12c094ca8b02e11cc12cf18102c55acfa/torch/testing/_internal/common_utils.py#L2196-L2203

How "temporary" do you believe this is? If this might stay for longer, we should move it inside the actual testing logic. Otherwise, downstream libraries will not have access to this.

It could go into 

https://github.com/pytorch/pytorch/blob/25fa964d96c79ba1d7654db33516eb3c3ad3fae5/torch/testing/_comparison.py#L667

like

```py
if actual.is_mps or expected.is_mps:
    actual = actual.cpu()
    expected = expected.cpu()
```

**Comment by kulinseth** [comment]
@pmeier , we have all the operations now supported through `mps` backend. We are testing without moving to CPU. we will create a PR and update here to be removed.

**Comment by kulinseth** [comment]
This will continue to be an issue, as Metal doesn't have FP64 support. So 

```
======================================================================
ERROR: test_index_setitem_bools_slices (__main__.TestAdvancedIndexing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kulinseth/miniconda3/envs/loftr/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1217, in not_close_error_metas
    pair.compare()
  File "/Users/kulinseth/miniconda3/envs/loftr/lib/python3.9/site-packages/torch/testing/_comparison.py", line 706, in compare
    self._compare_values(actual, expected)
  File "/Users/kulinseth/miniconda3/envs/loftr/lib/python3.9/site-packages/torch/testing/_comparison.py", line 817, in _compare_values
    compare_fn(
  File "/Users/kulinseth/miniconda3/envs/loftr/lib/python3.9/site-packages/torch/testing/_comparison.py", line 986, in _compare_regular_values_close
    actual, expected = self._promote_for_comparison(actual, expected)
  File "/Users/kulinseth/miniconda3/envs/loftr/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1023, in _promote_for_comparison
    return actual.to(dtype), expected.to(dtype)
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

```
We will have to rely on `comparison.py` to use CPU for comparison. 

```
        if actual.is_mps or expected.is_mps:  # type: ignore[attr-defined]
            actual = actual.cpu()
            expected = expected.cpu()

```

**Comment by kulinseth** [comment]
The tensor compare support has been added.
