### ISSUE TITLE
error when installing Caffe2: undefined reference to `void caffe2::math::BiasCHW

### ISSUE THREAD

**Issue by VeraLau1994** [pytorch/pytorch#7715]
I cannot install Caffe2 on Nvidia TX2 because of such error:

Scanning dependencies of target operator_fallback_gpu_test
[ 80%] Building CXX object caffe2/CMakeFiles/operator_fallback_gpu_test.dir/operators/operator_fallback_gpu_          test.cc.o
[ 80%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state.cc.o
[ 80%] Building CXX object caffe2/CMakeFiles/reshape_op_gpu_test.dir/operators/reshape_op_gpu_test.cc.o
[ 80%] Building CXX object caffe2/CMakeFiles/elementwise_op_gpu_test.dir/operators/elementwise_op_gpu_test.c          c.o
[ 80%] Linking CXX executable ../bin/reshape_op_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `void caffe2::math::BiasCHW<float, caffe2::CUDAContext>(floa          t const*, int, int, float*, caffe2::CUDAContext*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/reshape_op_gpu_test.dir/build.make:109: recipe for target 'bin/reshape_op_gpu_test' failed
make[2]: *** [bin/reshape_op_gpu_test] Error 1
CMakeFiles/Makefile2:1587: recipe for target 'caffe2/CMakeFiles/reshape_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/reshape_op_gpu_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_dlpack.cc.o
[ 80%] Linking CXX executable ../bin/operator_fallback_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `void caffe2::math::BiasCHW<float, caffe2::CUDAContext>(floa          t const*, int, int, float*, caffe2::CUDAContext*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/operator_fallback_gpu_test.dir/build.make:109: recipe for target 'bin/operator_fallback_gp          u_test' failed
make[2]: *** [bin/operator_fallback_gpu_test] Error 1
CMakeFiles/Makefile2:1671: recipe for target 'caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/operator_fallback_gpu_test.dir/all] Error 2
[ 80%] Building CXX object caffe2/CMakeFiles/caffe2_pybind11_state_gpu.dir/python/pybind_state_gpu.cc.o
[ 80%] Linking CXX executable ../bin/elementwise_op_gpu_test
../lib/libcaffe2_gpu.so: undefined reference to `void caffe2::math::BiasCHW<float, caffe2::CUDAContext>(floa          t const*, int, int, float*, caffe2::CUDAContext*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/elementwise_op_gpu_test.dir/build.make:109: recipe for target 'bin/elementwise_op_gpu_test          ' failed
make[2]: *** [bin/elementwise_op_gpu_test] Error 1
CMakeFiles/Makefile2:1629: recipe for target 'caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/elementwise_op_gpu_test.dir/all] Error 2
[ 80%] Linking CXX shared module python/caffe2_pybind11_state_gpu.so
[ 80%] Built target caffe2_pybind11_state_gpu
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Would someone give me any help? I have been stuck on installation for a long time!

- PyTorch or Caffe2: C2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):  ./build_tegra_x1.sh 
- OS: Ubuntu 16.04
- PyTorch version: 
- Python version: 2.7
- CUDA/cuDNN version:  cuda9.0 cudnn7.0.5
- GPU models and configuration: Nvidia TX2
- GCC version (if compiling from source): gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- CMake version: 3.5.1
- Versions of any other relevant libraries:

**Comment by yinghai** [comment]
@BIT-silence I actually don't see `caffe2::math::BiasCHW` defined for `CUDAContext`. How did it pass normal build?

**Comment by yinghai** [comment]
@Maratyszcza I think this is a legit error. The user is building C2 on Jetson pack with TX2, which means it has CUDA as well as NEON. Hence the `ifndef` will route the code to `caff2::math::BiasCHW<CUDAContext>` which is not defined: https://github.com/pytorch/pytorch/blob/921dece2d7de7ab25f87a295c4589f5600778155/caffe2/operators/conv_transpose_op_impl.h#L120. 

We should really use GEMM here. The straightforward solution is to split the code for `ConvTranspose` but it will result in quite a a bit duplicated code. Any magic macro that we can use? :)

**Comment by yinghai** [comment]
Ok. I'm just gonna scoope out this part as a separate function and specialize it based on Context.

**Comment by corysaildrone** [comment]
I had the same error. After #7738 I'm now able to build on TX2 with Jetpack 3.2. I had to update eigen3 to the latest version on the git mirror and cmake with the `-DUSE_MPI=OFF` flag. Thanks for the fix @yinghai

**Comment by yinghai** [comment]
@corysaildrone Yes, that's bascially the trick. I have seen report that Jetpack has x86-64 version of CUDNN installed instead of ARM64 but glad that it worked out for you!
