### ISSUE TITLE
Remove nderivs from torch.jit.trace

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#7717]
`torch.jit.trace` currently takes a `nderivs` argument, which should be equal to the expected number of derivatives of the traced graph that the user is expected to compute at some point. This was necessary in the re-tracing framework of the removed `@compile`, but is incompatible with the new invariant we have for tracing - we record the computation *exactly once* and only inside the actual traced region.

We should still make sure that it possible to use `autograd.grad` inside the traced functions, and the gradient function should be recorded correctly. On the other hand, there's a bunch of logic that handles invalidation and lifetime management of traces that is completely unnecessary now, and should be removed (since `TracingState`s are valid only inside `@trace` now). It might also turn out that we don't even need the subgraph-capturing logic which would lead to additional reductions in code size.

This should conclude the JIT cleanup efforts.

**Comment by suo** [comment]
this has been removed

**Comment by faisalasad3** [comment]
Sorry to revive this, but as far as I can see right now, trace is incompatible with autograd.grad. Is this true?
