### ISSUE TITLE
Cross Compile MacOS binaries for MPS feature

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#77210]
### 🚀 The feature, motivation and pitch

We need to create Macos 12.3 GHA runner and cross compile pytorch, similar to our current cross compiled MacOS 11 builds.

Cross compilation for arm64.
Change Xcode version to: 13.3.1 (the default for the macos-12 GHA runners)
This change should automatically enable MPS build of PyTorch.

So after more chatting, I think our current idea would be.
With the following legend:
- E -> already exists today
- U -> partially exists, needs to be updated (new macos version/enable MPS)
- N -> brand new

The goal would be to have by the end of May (?) the following macos CI/CD:
-  U M1 cross compilation from macos-12 x86 (with MPS enabled)
-  U x86 build from macos-12 x86 (with MPS enabled)
-  E M1 MPS macos-12 test (both cpu and gpu tests) (done by Apple)
-  N M1 macos-11 periodic test (cpu only) (done on our aws runners)
-  E x86 MPS macos-12 test (both cpu and gpu tests) (done by Apple)
-  E x86 macos-11 test (cpu only)
-  N x86 macos-12 test (cpu only)

Does that make sense to you guys?
If so, I think the order of priority would be mainly (with the fist one a lot higher than all the other ones):
- The M1 cross compilation (upgrade to a macos12 runner + enable MPS build)
- The x86 build (upgrade to a macos12 runner + enable MPS build)
- M1 macos-11 cpu only periodic test
- x86 macos-12 cpu only test

cc @ezyang @gchanan @zou3519 @malfet @albanD

**Comment by albanD** [comment]
@atalman 
Some nits here:
- We do not need/want to change the `MACOSX_DEPLOYMENT_TARGET` in any way
- We need machines that have SDK 12.3+ (whatever their macos version).

**Comment by malfet** [comment]
@albanD , after https://github.com/pytorch/pytorch/pull/77263 we have MPS builds already, don't we?

**Comment by albanD** [comment]
We have "The M1 cross compilation (upgrade to a macos12 runner + enable MPS build) part. The next tree are still required.

**Comment by malfet** [comment]
Closing as M1 builds with MPS support are available

**Comment by spiegelball** [comment]
Where exactly are those builds available?

**Comment by albanD** [comment]
Hey,
You can use the usual instructions from the install page to get them: https://pytorch.org/get-started/locally/
