### ISSUE TITLE
[primTorch] view and reshape are not testing 0 numel -> 0 numel views and reshapes

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#77218]
This is because torch function doesn't seem to support storage(), which has to be checked by as_strided. 

There are other ways we could model this behavior, too.

cc @ezyang @mruberry @ngimel

**Comment by ezyang** [comment]
Err, torch function doesn't support as strided? Really?

**Comment by mruberry** [comment]
> Err, torch function doesn't support as strided? Really?

Updated -- it's storage() that's called by prim.as_strided that is not supported

**Comment by mruberry** [comment]
Addressed this by adding a special case for no elem -> no elem
