### ISSUE TITLE
`linalg.lstsq` fails to backward due to "Dimension out of range"

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#77225]
### 🐛 Describe the bug

`linalg.lstsq` fails to backward due to "Dimension out of range". However, its forward pass can work successfully and get the results. I think this may be related to "broadcast" problem that only forward pass broadcast the input tensor automatically.

```python
import torch

A = torch.rand([5, 5], dtype=torch.float64, requires_grad=True)
B = torch.rand([5], dtype=torch.float64, requires_grad=True)

res = torch.linalg.lstsq(A, B)
res.solution.sum().backward()
# IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)
```

### Versions

pytorch: 1.11.0

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nikitaved** [comment]
CC @IvanYashchuk , I think you modified that code after the initial merge of my version, right?

**Comment by nikitaved** [comment]
Ah, @Lezcano , right, this is indeed backward issue. Sorry, @IvanYashchuk !

**Comment by nikitaved** [comment]
Totally slipped off of my list. I will look into it ASAP.

**Comment by lezcano** [comment]
@nikitaved if you have a look at the logic in `linalg.solve`, note that it's a bit buggy, as this was reported two weeks ago:
https://github.com/pytorch/pytorch/issues/89761

If you fix one, feel free to add the fix to the other. Potentially, the logic may even be shared between the two functions.
