### ISSUE TITLE
How can i  remove  'lib/libtorch_cuda.so'  gracefully to make deploy more small.  【Questions and Help】

### ISSUE THREAD

**Issue by wangping886** [pytorch/pytorch#77228]
i want import torch  in my project . and i will not use 'cuda' clearly .

how can i to remove  'lib/libtorch_cuda.so'  gracefully to make deploy package more smaller. (serverless deploy)

i remove lib/libtorch_cuda.so ,then cmd 'python3 index.py'  . the result show...

**Traceback (most recent call last):
  File "index.py", line 7, in <module>
    import torch
  File "/root/python/src/pic-linux_all/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: libtorch_cuda.so: cannot open shared object file: No such file or directory**

what should  I do.

### Versions

Python version: 3.8.0 (default, May 11 2022, 08:57:48)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] (64-bit runtime)
Python platform: Linux-3.10.0-514.26.2.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

**Comment by H-Huang** [comment]
Hi, if I understand your question corerctly, have you tried installing pytorch from source and setting `USE_CUDA=0`? https://github.com/pytorch/pytorch#:~:text=If%20you%20want%20to%20disable%20CUDA%20support%2C%20export%20the%20environment%20variable%20USE_CUDA%3D0.%20Other%20potentially%20useful%20environment%20variables%20may%20be%20found%20in%20setup.py.

**Comment by wangping886** [comment]
thanks for your reply.  maybe I need install torch customized .
