### ISSUE TITLE
The grad of `f(x) = torch.div(x, 0)` should be `NaN`

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#77221]
### 🐛 Describe the bug

The `gradcheck` will fail for `torch.div` if the `other` is 0.

```python
import torch
from torch.autograd import gradcheck

def f(a):
    return torch.div(a, 0)

a = torch.rand([], requires_grad=True, dtype=torch.float64)
gradcheck(f, (a))
# GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
# numerical:tensor([[nan]], dtype=torch.float64)
# analytical:tensor([[inf]], dtype=torch.float64)
```

I think it'd better be `nan` when the division operation is invalid.

### Versions

pytorch: 1.11.0

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
This is expected behavior - when the function is not defined, an arbitrary gradient may be returned. We also recently updated the autograd note to clarify this: https://pytorch.org/docs/master/notes/autograd.html#gradients-for-non-differentiable-functions
