### ISSUE TITLE
Error converting the pointnet++ model to ONNX

### ISSUE THREAD

**Issue by wangyaxin1998** [pytorch/pytorch#77222]
## Vesion
pytorch: 1.6.0

## Problem description

 The model I use is pointnet++ 
 This is a website with network structure 
https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet_sem_seg.py
I only changed the input of the model and changed 9 channels to 4 channels.
 For deployment, I want to convert the model to onnx format .
The program has been stuck in `torch.onnx.export`, and model conversion cannot be completed 
How can i solve this problem?

## Code

```python
    model=MODEL.get_model(NUM_CLASSES)

    model.load_state_dict(torch.load(checkpoint)['model_state_dict']) 

    model=model.eval()

    input = torch.randn(1, 4, 768)

    torch.onnx.export(model, input, onnx_path,verbose=True,
     input_names=input_names, output_names=output_names,
      opset_version=11) 
    print("Exporting .pth model to onnx model has been successful!")
```

 The following is a warning message 

## Warning

```
/media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:75: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
/media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:75: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
/media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:293: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if S == 1:
/home/hust/miniconda3/envs/PointNet++/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2225: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
/home/hust/miniconda3/envs/PointNet++/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2179: UserWarning: Exporting aten::index operator with indices of type Byte. Only 1-D indices are supported. In any other case, this will produce an incorrect ONNX graph.
  warnings.warn("Exporting aten::index operator with indices of type Byte. "
    
        /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:75:
         farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)

        /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:293: 
        points2 = points2.permute(0, 2, 1)
        B, N, C = xyz1.shape
        _, S, _ = xyz2.shape

        if S == 1:
            interpolated_points = points2.repeat(1, N, 1)
        else:
            dists = square_distance(xyz1, xyz2)
            dists, idx = dists.sort(dim=-1)
            dists, idx = dists[:, :, :3], idx[:, :, :3]  # [B, N, 3]

            dist_recip = 1.0 / (dists + 1e-8)
            norm = torch.sum(dist_recip, dim=2, keepdim=True)
            weight = dist_recip / norm
            interpolated_points = torch.sum(index_points(points2, idx) * weight.view(B, N, 3, 1), dim=2)
```

**Comment by wangyaxin1998** [comment]
i use function is torch.onnx.export,and  the function is always executed here ,so i can't get the onnx

**Comment by justinchuby** [comment]
I tried exporting the model and it was successful. Could you try using the pytorch-nightly build and see if you can export?

![out](https://user-images.githubusercontent.com/11205048/168144409-d2db9ded-35b5-48d1-8d2d-4e35f58ab821.png)

**Comment by justinchuby** [comment]
@BowenBao export time seems to be an issue we need to consider for bigger models

**Comment by BowenBao** [comment]
@justinchuby How so? In previous comment you mentioned the export is successful, while for @Juelianqvq it takes infinite time. Why the difference?

**Comment by justinchuby** [comment]
I am not sure. @Juelianqvq do you have a script we can run?

**Comment by Kingxudong** [comment]
@wangyaxin1998  Was the pointnet++ model finally deployed successfully?

**Comment by jkstyle2** [comment]
@justinchuby Hi, any progress with that issue?

**Comment by Wingseter** [comment]
I am also using the same code from the repository and have encountered the issues with export and export time that were mentioned above.
I used PyTorch nightly (2.1.2) version, and in my case, the export issue has been resolved. 
However, when the exported model is used for inference, 
the following problem occurs: 

[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/sa1/Reshape_369'

**Comment by krishanr** [comment]
Try opset_version 16. I was able to export and test a model that used PointNetConv with that version. opset_version 15 and lower were causing issues.

**Comment by lzh1998-jansen** [comment]
> ## Vesion
> pytorch: 1.6.0
> 
> ## Problem description
> The model I use is pointnet++ This is a website with network structure https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet_sem_seg.py I only changed the input of the model and changed 9 channels to 4 channels. For deployment, I want to convert the model to onnx format . The program has been stuck in `torch.onnx.export`, and model conversion cannot be completed How can i solve this problem?
> 
> ## Code
> ```python
>     model=MODEL.get_model(NUM_CLASSES)
> 
>     model.load_state_dict(torch.load(checkpoint)['model_state_dict']) 
> 
>     model=model.eval()
> 
>     input = torch.randn(1, 4, 768)
> 
>     torch.onnx.export(model, input, onnx_path,verbose=True,
>      input_names=input_names, output_names=output_names,
>       opset_version=11) 
>     print("Exporting .pth model to onnx model has been successful!")
> ```
> 
> The following is a warning message
> 
> ## Warning
> ```
> /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:75: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
> /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:75: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
> /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:293: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   if S == 1:
> /home/hust/miniconda3/envs/PointNet++/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2225: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
>   "If indices include negative values, the exported graph will produce incorrect results.")
> /home/hust/miniconda3/envs/PointNet++/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:2179: UserWarning: Exporting aten::index operator with indices of type Byte. Only 1-D indices are supported. In any other case, this will produce an incorrect ONNX graph.
>   warnings.warn("Exporting aten::index operator with indices of type Byte. "
>     
>         /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:75:
>          farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)
> 
>         /media/hust/File/wyx/Pointnet2_water/models/pointnet2_utils.py:293: 
>         points2 = points2.permute(0, 2, 1)
>         B, N, C = xyz1.shape
>         _, S, _ = xyz2.shape
> 
>         if S == 1:
>             interpolated_points = points2.repeat(1, N, 1)
>         else:
>             dists = square_distance(xyz1, xyz2)
>             dists, idx = dists.sort(dim=-1)
>             dists, idx = dists[:, :, :3], idx[:, :, :3]  # [B, N, 3]
> 
>             dist_recip = 1.0 / (dists + 1e-8)
>             norm = torch.sum(dist_recip, dim=2, keepdim=True)
>             weight = dist_recip / norm
>             interpolated_points = torch.sum(index_points(points2, idx) * weight.view(B, N, 3, 1), dim=2)
> ```

i also meet this proble, do you really solve this now?

**Comment by lzh1998-jansen** [comment]
> I tried exporting the model and it was successful. Could you try using the pytorch-nightly build and see if you can export?
> 
> Exported graph

could you show your code ?
