### ISSUE TITLE
DISABLED test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA)

### ISSUE THREAD

**Issue by KyleCZH** [pytorch/pytorch#77237]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_broadcast_in_dim_cuda_float32%2C%20TestPrimsCUDA)).

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @mruberry

**Comment by jeffdaily** [comment]
Failures due to missing nvFuser support for ROCm.  This is being worked on.

**Comment by jeffdaily** [comment]
Still broken.

**Comment by jjsjann123** [comment]
hmmm. so #77468 didn't work, that's surprising...
