### ISSUE TITLE
how to import caffe2

### ISSUE THREAD

**Issue by 994374821** [pytorch/pytorch#7727]
I use 'conda install pytorch torchvision -c pytorch' install pytorch, does this command install caffe2?
if caffe2 has been installed, how can I import caffe2 in python? Thank you!

**Comment by PauliusPoc** [comment]
I tried to install pytorch the way you did, and didn't find caffe2 in my environment.
Please refer to this [link](https://github.com/pytorch/pytorch/tree/master/caffe2) for caffe2.

**Comment by zou3519** [comment]
`conda install pytorch torchvision -c pytorch' install pytorch` does not install caffe2.
