### ISSUE TITLE
`is_wrapped_number` isn't being set for args to `__torch_dispatch__`

### ISSUE THREAD

**Issue by makslevental** [pytorch/pytorch#77326]
### 🐛 Describe the bug

minimal repro

```python
import torch
from torch.utils.cpp_extension import load_inline
source = """
    #include "ATen/core/Tensor.h"
    bool is_wrapped_number(at::Tensor& ten) {
        return ten.unsafeGetTensorImpl()->is_wrapped_number();
    }
    """
check = load_inline(
    name="inline_extension", cpp_sources=[source], functions=["is_wrapped_number"]
)

class ElementwiseWhereScalarModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, a):
        return torch.where(a, 0.25, 0.75)

class TrivTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, elem, *, requires_grad=None):
        if requires_grad is None:
            return super().__new__(cls, elem)
        else:
            return cls._make_subclass(cls, elem, requires_grad)

    @classmethod
    def __torch_dispatch__(cls, func, _types, args=(), kwargs=None):
        for arg in args:
            if isinstance(arg, cls): continue
            print(arg, check.is_wrapped_number(arg))

ElementwiseWhereScalarModule()(TrivTensor(torch.rand((10, 10))))

> tensor(0.2500) False <--- should be true
> tensor(0.7500) False <--- should be true

```

Note that they are floats at `__torch_function__` (which you can see by going up one stack frame).
Maybe related to https://github.com/pytorch/pytorch/issues/74400 (not sure).

cc @silvasean @cathyzhyi @powderluv 

### Versions
Collecting environment information...
PyTorch version: 1.12.0.dev20220511+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.21.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 510.39.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220511+cpu
[pip3] torch-mlir==20220511.445
[pip3] torchvision==0.13.0.dev20220511+cpu
[conda] Could not collect

**Comment by ezyang** [comment]
I think this is "expected". Wrapped numbers only occur for a fixed set of operations: 

```
// TODO: remove this. This is a temporary list of functions that allow Python
// numbers to bind to Tensors. Some binary ops have separate Tensor and Scalar
// overloads and binding to the Tensor overload with a number of a different
// type will trigger a type error.
//
// If you modify this, you will need to adjust the blocklist in
// tools/pyi/gen_pyi.py (and add hardcoded signatures for these
// functions.)
static bool should_allow_numbers_as_tensors(const std::string& name) {
  static std::unordered_set<std::string> allowed = {
    "add", "add_", "add_out",
    "div", "div_", "div_out",
    "divide", "divide_", "divide_out", // alias of div
    "mul", "mul_", "mul_out",
    "multiply", "multiply_", "multiply_out", // alias of mul
    "sub", "sub_", "sub_out",
    "subtract", "subtract_", "subtract_out", // alias of sub
    "true_divide", "true_divide_", "true_divide_out",
    "floor_divide", "floor_divide_", "floor_divide_out"
  };
  return allowed.find(name) != allowed.end();
} 
```

At a guess, did you try `torch.ops.aten.where` with a number and that did become wrapped? This is probably a bug (because I didn't consult the allow list for permitting scalar arguments for overloads). I thought it would be benign but maybe not...
