### ISSUE TITLE
ATen C++ tensor creation places tensors on devices inconsistently from torch.* Python calls

### ISSUE THREAD

**Issue by mcarilli** [pytorch/pytorch#7735]
## Issue description

I'm moving our extension backend to use the ATen interface.  It's very cool and convenient for the most part, but I noticed that when the ATen backend functions create new tensors, the device placement behavior after the current device changes is inconsistent from the behavior of identically named Python torch functions.  Specifically: 

```
x = torch.cuda.FloatTensor(size) # device='cuda:0'
with torch.cuda.device(1):
    y = torch.empty_like(x)
    z = myext._C.create_empty_like(x) # small custom extension that returns z = at::empty_like(x)
y is now on device 0
z is now on device 1
```

Is this the intended behavior, or a bug?
@csarofeen @ngimel @mruberry for interest, @zdevito because I see "TODO:  zach" scattered around the backend code :D

## Code example

I've attached a minimal working repro: [repro.tar.gz](https://github.com/pytorch/pytorch/files/2023467/repro.tar.gz).
Extract, enter the directory, and it should be runnable via
```
python setup.py install
python test_empty_like.py
``` 

## System Info
Collecting environment information...
PyTorch version: 0.5.0a0+d4f6c84
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: Graphics Device

Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5.real
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[pip3] numpydoc (0.7.0)
[pip3] torch (0.5.0a0+d4f6c84)
[pip3] torch-test-cpp-extension (0.0.0)
[pip3] torchvision (0.2.0)
[conda] magma-cuda90              2.2.0                hae16b58_1    pytorch
[conda] torch                     0.5.0a0+d4f6c84           <pip>
[conda] torch-test-cpp-extension  0.0.0                     <pip>
[conda] torchvision               0.2.0                     <pip>

**Comment by apaszke** [comment]
It's been like this since ATen existed. The AutoGPU parts are happening only in our Python bindings. We should probably fix it at some point, although it might be simpler to just wait for c10 to come.

**Comment by ezyang** [comment]
This is a known problem, and it is high priority to fix.

**Comment by goldsborough** [comment]
@mcarilli for context, ATen currently does not have any concept of a "device" beyond CPU vs. CUDA (i.e. the "ordinal" part is missing from ATen's model). I'm working on changing this right now, so you can expect this to be fixed soon
