### ISSUE TITLE
[GHA] Rerunning a test attempts to download a nonexistent build artifact

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#77355]
### 🐛 Describe the bug

See: https://github.com/pytorch/pytorch/runs/6397395077?check_suite_focus=true

The rocm test is attempting its second rerun so it's looking for a build artifact under attempt 2. However, the build was not rerun as it passed in attempt 1. Thus, the test cannot find the build artifact.

### Versions

In CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Isn't this a duplicate of https://github.com/pytorch/pytorch/issues/76042 ?

**Comment by janeyx99** [comment]
Ah yes, I couldn't tell from your description back then what the failure was referring to--closing this then.
