### ISSUE TITLE
Different behaviors when using torch.jit.trace, torch.jit.script, @torch.jit.script, and ONNX 

### ISSUE THREAD

**Issue by fnobis** [pytorch/pytorch#77420]
### 🐛 Describe the bug

I see some differences in the behaviour of the different methods to convert a PyTorch model to ONNX.

I will use this code as an example and describe the differences I encounter when commenting in the comments in the code, only using one of the lines at one run.
```python
from torch import nn
import torch.onnx


class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.conv = nn.Conv2d(1, 50, 2)

    # @torch.jit.script
    def forward(self, x):
        out = self.conv(x)
        return out


torch_model = NeuralNetwork()

input = torch.randn(1, 1, 224, 224)

# torch_model = torch.jit.script(torch_model, input)
# torch_model = torch.jit.trace(torch_model, input)
torch.onnx.export(torch_model, input, "model.onnx")
```

### 1. Running the Code as is:
    The model is exported without any problems.

### 2. Running the code with  `torch_model = torch.jit.trace(torch_model, input)`
    The following warning is issued when using the` torch.onnx.export` function:
```
    /usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py:356: UserWarning: Model has no forward function
  warnings.warn("Model has no forward function")
 ```
  I dont understand this behavior, since I thought ` torch.onnx.export` calls `torch.jit.trace()` anyway.
  Furthermore when I call `print(torch_model.code)`, I see that the forward function is defined.

### 3. Running the code with  `torch_model = torch.jit.script(torch_model, input)`
  The following warning is issued during the call to `torch.jit.script()` function:
```
/usr/local/lib/python3.8/dist-packages/torch/jit/_script.py:1214: UserWarning: `optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead
  warnings.warn(
```
   This does not happen when the input argument is not passed to script, however the warning message seems incomplete.

### 4. Running the code with `@torch.jit.script`
   This throws an error:
```
'Tensor (inferred)' object has no attribute or method 'conv'.:
```
I was expecting this to work, but it does not even compile.

### Additional remark:
I tried to find what other operations might not be supported in the model following this
[official guide](https://pytorch.org/docs/stable/onnx.html#discovering-all-unconvertible-aten-ops-at-once). `onnx_utils.unconvertible_ops` is not found in my installation.

### Versions

Collecting environment information...
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA T500
Nvidia driver version: 510.60.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.10.2+cu113
[pip3] torch-tb-profiler==0.4.0
[pip3] torchvision==0.11.3+cu113
[conda] Could not collect

**Comment by davidberard98** [comment]
2. This is an onnx issue which is coming from torch.onnx.export. cc @BowenBao 
3. You shouldn't pass an example input to torch.jit.script. The second input is `optimize`, which is deprecated.
4. This usage of torch.jit.script isn't supported.

**Comment by fnobis** [comment]
Thanks for the quick answer @davidberard98. With regards to 4: I thought, the  script decorator is intendend to be used in a tracing environment, if a control flow would be necessary in parts of the model, e.g. if there were an if statement in the example forward function?

**Comment by davidberard98** [comment]
AFAIK you can't script a method. You could script a function and call that function from within the class.

**Comment by BowenBao** [comment]
2. I believe this is also resolved in latest pytorch nightly. It is now a warning stating it couldn't get signature from forward method of the traced module.

**Comment by BowenBao** [comment]
Hi @fnobis ,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
