### ISSUE TITLE
PyTorch master OSS build not working on Mac OS

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#77432]
### 🐛 Describe the bug

When I try to build PyTorch on recent master (commit 2b7943c47c8561a46103488b0fe9a592b87dc5bb), it fails with (https://gist.github.com/vkuzo/95d2098bc9e0908202795c47899b43b9).  When I go to an older revision (commit 6cbe9d1f58fdc9288833b8d82db6896af0e4555f), the build succeeds.

Build command I'm using:
```
python setup.py clean
CC=clang CXX=clang++ python setup.py develop
```

### Versions

env: https://gist.github.com/vkuzo/b517a77549db8652307f239a1fff0bc6
note: the revision there is an old one where things work

**Comment by Gamrix** [comment]
I have been able to build it in the last few days on `viable/strict`, which closely follows master. Try including this flag if you aren't able to compile

```
export USE_MPS=0
```
