### ISSUE TITLE
logsumexp out variant raises RuntimeError: value cannot be converted to type int64_t without overflow

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#77472]
### 🐛 Describe the bug

```
  import torch
  from torch import tensor
  expected = torch.logsumexp(tensor(-8), (0,), True)
  torch.logsumexp(tensor(-8), (0,), True, out=expected)
```

raises

```
Traceback (most recent call last):
  File "/data/users/ezyang/pytorch-tmp/f.py", line 13, in <module>
    torch.logsumexp(tensor(-8), (0,), True, out=expected)
RuntimeError: value cannot be converted to type int64_t without overflow
```

which is unexpected

### Versions

master

cc @ezyang @mruberry @ngimel

**Comment by ngimel** [comment]
That's unary type promotion https://github.com/pytorch/pytorch/blob/2166fc55fc009a6f66c96cdeac9a0a308e77bc55/aten/src/ATen/native/ReduceOps.cpp#L1301, the root of <s>all</s> most evil, the original call should have errored out without type promotion too.
