### ISSUE TITLE
Cannot import 'torch' due to Circular import

### ISSUE THREAD

**Issue by Mapleshade20** [pytorch/pytorch#77487]
### 🐛 Describe the bug

python 3.9, anaconda, updated packages of torch 1.11.0 and torchvision 0.12.0.

```
>>> import torch.nn.functional
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\__init__.py", line 234, in <module>
    __all__ += [name for name in dir(_C)
NameError: name '_C' is not defined
```

```
>>> from torch import Tensor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\__init__.py", line 234, in <module>
    __all__ += [name for name in dir(_C)
NameError: name '_C' is not defined
```

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\__init__.py", line 754, in <module>
    from .functional import *  # noqa: F403
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\nn\modules\__init__.py", line 3, in <module>
    from .conv import Conv1d, Conv2d, Conv3d, \
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\nn\modules\conv.py", line 2, in <module>
    from koila import LazyTensor, lazy
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\koila\__init__.py", line 12, in <module>
    from .lazy import Evaluation, LazyFunction, LazyTensor, lazy
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\koila\lazy.py", line 31, in <module>
    from . import gpus, interfaces, prepasses
  File "C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\koila\prepasses.py", line 23, in <module>
    from torch.functional import Tensor
ImportError: cannot import name 'Tensor' from partially initialized module 'torch.functional' (most likely due to a circular import) (C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\functional.py)
```

### Versions

**I added a line of code at C:\Users\howar\anaconda3\envs\disco-diffusion\lib\site-packages\torch\__init__.py line 206**

```
if TYPE_CHECKING:
    import torch._C as _C
    print("RUNNNNNNNNNNNN _C")
else:
    print("_C FAILLLLLLED")
```

**It shows a lot of N/A cuz torch cannot be imported at all!**

(disco-diffusion) C:\Users\howar\disco-diffusion>python collect_env.py
_C FAILLLLLLED
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: N/A
CUDA runtime version: 11.6.124
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 511.65
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.8.2
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] numpy-base                1.21.5           py39hca35cd5_2
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchmetrics              0.8.2                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by Gamrix** [comment]
This likely is happening because you have multiple versions of torch installed. Run `conda uninstall torch` and then `pip uninstall torch` until they say that they do not have a version installed then try installing torch again.

**Comment by Mapleshade20** [comment]
pip / conda reinstalling didn't solve this problem.
Eventually I uninstalled anaconda completely along with the package libs, and then install & configure it all again. Solved

**Comment by NytEEE** [comment]
Glad to find the same problem. No need to reinstall anaconda, I just rebuilt the env and solved. I guess it was truly caused by version conflicts in some package libs.

**Comment by anddr0** [comment]
In my case, I had to create venv and re-download torchvision and recreate the file where I run the script after activating venv
