### ISSUE TITLE
switch-break problem in 'aten/src/ATen/core/IListRef.h' of debug version libtorch.

### ISSUE THREAD

**Issue by kilasuelika** [pytorch/pytorch#77481]
### 🐛 Describe the bug

Simple code using nightly build debug version `libtorch` will triger an exception:
```cpp
#include <torch/torch.h>
#include <vector>
#include <windows.h>

int main() {
    LoadLibraryA("torch_cuda.dll");

    std::vector<torch::Tensor> v;
    v.emplace_back(torch::randn({1, 1, 32}));
    auto y = torch::cat(v, 1);
};
```
After check source code, I find the problem may locates in `aten/src/ATen/core/IListRef.h` line 383 and 397:
```
 switch (tag_) {
      case IListRefTag::Boxed:
        payload_.boxed_iterator = iterator.payload_.boxed_iterator;
      case IListRefTag::Unboxed:
        payload_.unboxed_iterator = iterator.payload_.unboxed_iterator;
      default:
        TORCH_INTERNAL_ASSERT(false, "invalid IListRef tag.");
    }
```
I think there should be `break;` in each `case`, or  `TORCH_INTERNAL_ASSERT` will always be triggered.

### Versions

Collecting environment information...
Traceback (most recent call last):
  File "C:\Users\Administrator\collect_env.py", line 492, in <module>
    main()
  File "C:\Users\Administrator\collect_env.py", line 475, in main
    output = get_pretty_env_info()
  File "C:\Users\Administrator\collect_env.py", line 470, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "C:\Users\Administrator\collect_env.py", line 319, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "C:\Users\Administrator\collect_env.py", line 301, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "C:\Users\Administrator\collect_env.py", line 289, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by Catossun** [comment]
I met the same problem when I using libtorch on C++.
But it works fine in the release version of libtorch.
