### ISSUE TITLE
Use type hints (PEP 484) in generated documentation

### ISSUE THREAD

**Issue by jchia** [pytorch/pytorch#77501]
### 📚 The doc issue

While the current PyTorch source code often contains type hints for signatures of public functions, the type hint information is missing from the generated documentation.

For example, compare https://pytorch.org/docs/stable/generated/torch.nn.functional.relu.html with the linked source at https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#relu

In the source, the signature of `relu` is clearly presented and `input` is clearly indicated to be a `Tensor`: `def relu(input: Tensor, inplace: bool = False) -> Tensor:`

In the documentation, there is no type information at all and it is not obvious what type `input` needs to be: `torch.nn.functional.relu(input, inplace=False) → Tensor`

Thus, a simple reading of the documentation alone does not clarify the expected type of the function arguments.

If API documentation contains type information derived from the type hints in the source code, it will be more useful and understandable to readers without requiring them to examine the source code.

While in some cases there could be an implicit convention regarding function arguments of certain groups of functions, I don't think those conventions are documented clearly in one obvious and accessible document, so explicit type information in the actual API documentation of each function or class will be useful especially to new users of PyTorch.

### Suggest a potential alternative/fix

Modify/configure the sphinx documentation generation to automatically include type information in the generated documentation based on the type hints present in the source code. Remove manually-produced redundant documentation from the source code docstrings like the `relu(input, inplace=False) -> Tensor` above when automatic documentation generation includes relevant type hint information.

cc @svekars @holly1238

**Comment by ShawnZhong** [comment]
For reference, PR #49294 removed type annotations from signatures in HTML docs, and there are some discussions under the issue #44964

**Comment by jchia** [comment]
Thanks, I suppose that's where the discussion should happen.
