### ISSUE TITLE
bfloat16 group_norm on CPU does moments calculation in bfloat16

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#77507]
### 🐛 Describe the bug

RowwiseMoments is a reduction and should not be done in half precision. I added these static asserts

```
template <typename T> 
std::pair<T, T> RowwiseMoments(const T* X, int64_t N, int64_t ddof = 0) {
  static_assert(!std::is_same<T, c10::BFloat16>::value, "RowwiseMoments must not be bfloat16 prec");
  static_assert(!std::is_same<T, c10::Half>::value, "RowwiseMoments must not be half prec");
```

but I got

```
In file included from /private/home/ezyang/pytorch-tmp/aten/src/ATen/native/cpu/group_norm_kernel.cpp:13,
                 from aten/src/ATen/native/cpu/group_norm_kernel.cpp.AVX2.cpp:1:
../aten/src/ATen/native/cpu/moments_utils.h: In instantiation of ‘std::pair<_FIter, _FIter> at::native::utils::RowwiseMoments(const T*, int64_t, int64_t) [with T = c10::BFloat16; int64_t = long int]’:
/private/home/ezyang/pytorch-tmp/aten/src/ATen/native/cpu/group_norm_kernel.cpp:60:59:   required from ‘void at::native::{anonymous}::GroupNormKernelImplInternal(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, int64_t, int64_t, T, at::Tensor&, at::Tensor&, at::Tensor&) [with T = c10::BFloat16; int64_t = long int]’
/private/home/ezyang/pytorch-tmp/aten/src/ATen/native/cpu/group_norm_kernel.cpp:396:7:   required from here
../aten/src/ATen/native/cpu/moments_utils.h:135:17: error: static assertion failed: RowwiseMoments must not be bfloat16 prec
  135 |   static_assert(!std::is_same<T, c10::BFloat16>::value, "RowwiseMoments must not be bfloat16 prec");
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

cc @ngimel @Chillee 

### Versions

master

**Comment by ngimel** [comment]
Low precision reductions/ops on CPU are not in good shape (and we have not prioritized fixing them). cc @frank-wei for awareness.  It's possible that intermediates are still accumulated in float, and only final values are truncated, which is not that bad.

**Comment by frank-wei** [comment]
Yes, @ngimel , it is possible in float. Ask @jgong5 to chime in on the intermediate accumulations.

**Comment by mingfeima** [comment]
This is a valid issue and will have it fixed.  However, I am occupied working on channels last and bfloat16 features at the moment :(  Is it possible that we target this feature for the next release cycle? @ngimel @frank-wei @ezyang

TODO:
- [ ] update `utils::RowwiseMoments` for BFloat16 to use float32 as computation type. (input is bfloat16 but all the moments are kept in float32)

This will affect:
* the channels first kernel of `nn.GroupNorm`; the channels last kernel is already using float32 as computation type.
* `nn.LayerNorm` kernel, right now the kernel did a out-place data type conversion from bfloat16 to float32 and do `utils::RowwiseMoments` on float32, so the accuracy has no issue; in-place version of `utils::RowwiseMoments` might bring some additional performance speedup.

**Comment by ezyang** [comment]
It is fine to target later, I have not seen reports of this affecting people in the wild; I discovered it because I was auditing the code for unrelated reasons.

**Comment by frank-wei** [comment]
> It is fine to target later, I have not seen reports of this affecting people in the wild; I discovered it because I was auditing the code for unrelated reasons.
Thanks @ezyang  for bringing this up. I will work with Intel to fix it in the next release.

**Comment by mingfeima** [comment]
@ezyang this issue will be fixed by https://github.com/pytorch/pytorch/pull/81850 which allows moments to be calculated in float  (for bfloat16 inputs).
