### ISSUE TITLE
`tensordot` will trigger INTERNAL ASSERT FAILED when input requiring grad

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#77517]
### 🐛 Describe the bug

`tensordot` will trigger INTERNAL ASSERT FAILED when input requiring grad

```python
import torch

a = torch.randint(-1, 8, [3, 4, 5], dtype=torch.int8)
b = torch.rand([4, 3, 0], dtype=torch.complex64, requires_grad=True)
torch.tensordot(a, b, dims=[[1, 0], [0, 1]])
# RuntimeError: isDifferentiableType(variable.scalar_type())INTERNAL ASSERT FAILED at "/Users/distiller/project/pytorch/torch/csrc/autograd/functions/utils.h":65, please report a bug to PyTorch. 
```

### Versions

pytorch: 1.11.0

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @nairbv @mruberry @jianyuh @walterddr @IvanYashchuk @xwang233

**Comment by mikaylagawarecki** [comment]
Seems like the error is coming from [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/functions/utils.h#L63-L65), 
`// If the codegen triggers this, you most likely want to add your newly added function
    // to the DONT_REQUIRE_DERIVATIVE list in tools/autograd/gen_variable_type.py
    TORCH_INTERNAL_ASSERT(isDifferentiableType(variable.scalar_type()));`

should `tensordot` be added to the DONT_REQUIRE_DERIVATIVE list?

**Comment by soulitzer** [comment]
`tensors_dot` is composite, it is actually failing in `mm`. Set history is actually complaining that the dtype of the outputs is integral (not differentiable) (logging it out, I get `mm(int8, cfloat) -> int8`). That seems pretty wrong? But it could be because the second arg to `mm` is a zero numel tensor.

> In all linalg. functions the inputs should be of the same dtype.

Oh interesting, maybe checking the dtypes of the inputs could have caught this then.

**Comment by Lezcano** [comment]
I think there's two issues here:
- There is an early return in `mm` for when the reduction dimension is zero that's bypassing some of the checks.
- `tensorproduct` should check that the inputs have the same dtypes.
