### ISSUE TITLE
Preinstalled torch binary does not match NVIDIA driver in Google Colab

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#77528]
Not sure if this is the correct repository to report to. If it is not, feel free to close. I didn't encounter any issues, just wanted to report to avoid potential ones in the future.

---

Running `nvidia-smi` with a GPU accelerator in Google Colab gives the following header

```
Mon May 16 08:27:02 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
```

However, `pip show torch` reveals

```
Name: torch
Version: 1.11.0+cu113
```

Thus, the CUDA version the PyTorch binary is compiled against, is not fully supported by the NVIDIA driver.

**Comment by ngimel** [comment]
There's forward compatibility, so binaries can be compiled with a newer version (11.3) and still run on an older driver (11.2)

**Comment by pmeier** [comment]
For reference, [Table 1 in the CUDA compatibility docs](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#default-to-minor-version) shows that one only needs driver version >= 450.80.02 for FC with CUDA 11.*.
