### ISSUE TITLE
[primTorch] Strides for complex abs are incorrect

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#77526]
```
a = torch.randn((2, 2)).transpose(0, 1)
a.stride()
: (1, 2)

result = torch.abs(a)
result.stride()
: (1, 2)

b = torch.randn((2, 2), dtype=torch.cfloat).transpose(0, 1)
b.stride()
: (1, 2)

result = torch.abs(b)
result.stride()
: (2, 1)
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @nairbv @ngimel

**Comment by mruberry** [comment]
Likely dupe of https://github.com/pytorch/pytorch/issues/77553

**Comment by mruberry** [comment]
I think this is happening because of 

https://github.com/pytorch/pytorch/blob/0f1618ef7627060fd349f4988f5cf9307302ee7b/aten/src/ATen/native/UnaryOps.cpp#L261

**Comment by ngimel** [comment]
Yep, this is wrong.
