### ISSUE TITLE
`out = gather(x @ x, sparse_grad=True); out.sum().backward()` fails as `matmul` does not work with sparse gradients for dense inputs.

### ISSUE THREAD

**Issue by ecolss** [pytorch/pytorch#77532]
### 🐛 Describe the bug

`torch.gather()` can work very well if `sparse_grad=False`, but cannot work  if `sparse_grad=True`, see example below.

```python
import torch as th

x = th.rand((3,3), requires_grad=True)
th.gather(x @ x, 1, th.LongTensor([[0], [1]]), sparse_grad=True).sum().backward()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
----> 1 th.gather(x @ x, 1, th.LongTensor([[0], [1]]), sparse_grad=True).sum().backward()

.../python3.9/site-packages/torch/_tensor.py in backward(self, gradient, retain_graph, create_graph, inputs)
    305                 create_graph=create_graph,
    306                 inputs=inputs)
--> 307         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    308
    309     def register_hook(self, hook):

.../python3.9/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    152         retain_graph = create_graph
    153
--> 154     Variable._execution_engine.run_backward(
    155         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    156         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: sparse tensors do not have strides
```

### Versions

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.5 (default, May 18 2021, 12:31:01)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.4.5
[pip3] torch==1.10.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchmetrics==0.5.1
[pip3] torchtext==0.11.0
[pip3] torchvision==0.10.0
[pip3] torchviz==0.0.2
[conda] _pytorch_select           0.1                       cpu_0
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] libmklml                  2019.0.5                      0
[conda] mkl                       2019.4                      233
[conda] mkl-service               2.3.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.0            py39ha059aab_0
[conda] mkl_random                1.0.2            py39h16bde0e_0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] pytorch-lightning         1.4.5                    pypi_0    pypi
[conda] torch                     1.10.0                   pypi_0    pypi
[conda] torchaudio                0.9.0                      py39    pytorch
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchtext                 0.11.0                   pypi_0    pypi
[conda] torchvision               0.10.0                 py39_cpu    pytorch
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @nikitaved @pearu @cpuhrsch @amjames @ezyang @albanD @zou3519 @gqchen @soulitzer @Lezcano @Varal7 @mikaylagawarecki

**Comment by albanD** [comment]
Thanks for the report!
@mikaylagawarecki will you have some time to check this one?

**Comment by mikaylagawarecki** [comment]
I was able to reproduce this on 1.11, however, on the latest nightly there is a different error message:

```
Traceback (most recent call last):
  File "/fsx/users/mg1998/branches/src_index_shape_bugfix/test.py", line 6, in <module>
    out.sum().backward()
  File "/fsx/users/mg1998/branches/src_index_shape_bugfix/torch/_tensor.py", line 399, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/fsx/users/mg1998/branches/src_index_shape_bugfix/torch/autograd/__init__.py", line 176, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
NotImplementedError: Could not run 'aten::sparse_dim' with arguments from the 'CPU' backend. 
```

If I understand correctly, the issue is that `gather_backward` will return a sparse gradient for `x @ x` but this sparse gradient cannot be backpropped to x when the backward is run for `matmul` since x is dense and expects a dense gradient.

For example, the following snippet without the matmul would work ok (both on 1.11.0+cu113 and 1.12.0.dev20220516+cpu)

```
import torch as th

x = th.rand((3,3), requires_grad=True)
out = th.gather(x, 1, th.LongTensor([[0], [1]]), sparse_grad=True)
out.sum().backward()
print(x.grad)
tensor(indices=tensor([[0, 1],
                       [0, 1]]),
       values=tensor([1., 1.]),
       size=(3, 3), nnz=2, layout=torch.sparse_coo)
```

Is backpropping the sparse gradients from gather something that we support?

**Comment by ecolss** [comment]
@mikaylagawarecki So is this a bug then?

**Comment by mikaylagawarecki** [comment]
@ecolss I don't quite think this is a bug (as per the title change `matmul` doesn't support sparse gradients for dense inputs). I agree with you that the error raised doesn't make this clear though, perhaps we could improve that. 

You could submit a [feature request](https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=feature-request.yml) for this feature if you would like. :)

**Comment by ecolss** [comment]
@mikaylagawarecki Understood, thanks!

**Comment by nikitaved** [comment]
@mikaylagawarecki , thanks for fixing the title :) And sorry for stepping in

**Comment by mikaylagawarecki** [comment]
@nikitaved No, thank you for changing the title to more accurately reflect the problem it was a good idea! :)
