### ISSUE TITLE
`dist.recv` got wrong elements when sending linalg results

### ISSUE THREAD

**Issue by timmywanttolearn** [pytorch/pytorch#77554]
### 🐛 Describe the bug

I am tring to send tensos with `dist.send` and `dist.recv`. But when tensor is produced by `torch.linalg.qr`. The tensor received is not the same as it send.
Here is the code.
```
import torch
import torch.multiprocessing as mp
import torch.distributed as dist

def main_worker(rank, world_size, args):
    dist.init_process_group(
        backend="nccl",
        init_method="tcp://127.0.0.1:9001",
        world_size=world_size,
        rank=rank,
    )
    print("process begin", rank)

    if rank == 0:

        q_buffer = torch.rand([4,4]).to(0)      
        Q,R = torch.linalg.qr(q_buffer)
        print("local before q_buffer",Q)
        dist.send(Q,1)


                    


    elif rank == 1:

        q_buffer = torch.rand([4,4]).to(1)

        dist.recv(q_buffer,0)

        print("recv",q_buffer,q_buffer.shape)


def main():
    mp.spawn(main_worker, nprocs=2, args=(2, 2))


if __name__ == "__main__":
    main()

```
The result is
```
local before q_buffer tensor([[-0.4076,  0.5155,  0.4838, -0.5780],
        [-0.4182, -0.6807, -0.2695, -0.5378],
        [-0.4326,  0.4825, -0.7545,  0.1039],
        [-0.6869, -0.1954,  0.3522,  0.6049]], device='cuda:0')
recv tensor([[-0.4076, -0.4182, -0.4326, -0.6869],
        [ 0.5155, -0.6807,  0.4825, -0.1954],
        [ 0.4838, -0.2695, -0.7545,  0.3522],
        [-0.5780, -0.5378,  0.1039,  0.6049]], device='cuda:1') torch.Size([4, 4])
```
Not the same tensor!!!!

### Versions

pytorch 1.11.0
cuda 10.2

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by pritamdamania87** [comment]
@timmywanttolearn Thanks for the bug report and it indeed is an issue, a workaround would be to call `Q.contiguous()` before the `send` as the bug related to non-contiguous tensors.

**Comment by timmywanttolearn** [comment]
> @timmywanttolearn Thanks for the bug report and it indeed is an issue, a workaround would be to call `Q.contiguous()` before the `send` as the bug related to non-contiguous tensors.

Also R in QR decomposition has the same issue. I highly suggest that we should detect some results of `torch.linalg` here.

**Comment by pritamdamania87** [comment]
@timmywanttolearn Yes, we have a fix in https://github.com/pytorch/pytorch/pull/77809 which would raise an error that the Tensor needs to be contiguous.
