### ISSUE TITLE
Broken conda install Python 3.5/3.5 Conda 9.0 

### ISSUE THREAD

**Issue by KarenUllrich** [pytorch/pytorch#7758]
Hi PyTorch-Team,

I just wanted to report the following install problem. 

I copied the install instructions for Linux,  conda install, python 3.5 (also tried 3.6) and CUDA 9.0.

It installs just fine but at import it raises the following error.

```
from torch._C import *
ImportError: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_ao_zgetrf
```

I work with miniconda3, CUDA 9.0, GPU: Tesla K80.

I just installed via pip3 now. That works flawlessly. So no urgency :) Just reporting.

Best,
Karen

**Comment by soumith** [comment]
@KarenUllrich it seems that you have an MKL in your $LD_LIBRARY_PATH that is taking precedence over the MKL that anaconda ships. If you use conda installs, you might want to remove that MKL reference from your LD_LIBRARY_PATH (pytorch wont be the only package that will have an issue, any package that depends on anaconda-mkl will break)
