### ISSUE TITLE
Einsum modifies variables in-place

### ISSUE THREAD

**Issue by piercefreeman** [pytorch/pytorch#7763]
## Issue description

Einsum currently modifies variables in-place (without an explicit indication that it does so), which prevents pytorch from automatically backpropagating.

## Code example

```
x = torch.randn(3, 3, requires_grad=True)
z1 = torch.einsum("ij,jk->ik", (x, torch.randn(3, 3)))
z2 = torch.einsum("ij,jk->ik", (x, torch.randn(3, 3)))
z1.sum().backward()
```

Results in the following runtime error:

`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`

Demonstration and discussion can also be found [here](https://github.com/jonas-koehler/s2cnn/issues/9).

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip
- OS:
- PyTorch version: 0.4.0
- Python version: 3.6.1

**Comment by t-vi** [comment]
Oops. Thank you for reporting and the minimal example. I'll see to get that fixed.

**Comment by roozmahdavian** [comment]
Saw the same issue over here. Thank you @t-vi !

**Comment by t-vi** [comment]
Yes, but a somewhat expensive one. If you have the ability to recompile, you could also apply the PR fixing this. Somehow it seems to be stuck in the review queue because it hit an unrelated CI problem...

**Comment by V-o-y-a-g-e-r** [comment]
Okay so how to use it then?

**Comment by ezyang** [comment]
Just get a recent enough master and it will work.
