### ISSUE TITLE
[quant] [fuse_modules] fuse_custom_config_dict is hard coded to None

### ISSUE THREAD

**Issue by loiccordone** [pytorch/pytorch#77641]
Hello,

I noticed an error in the fuse_modules function:
https://github.com/pytorch/pytorch/blob/c83f8ee46ab057a8bce7ed7ba7ceccba5c388d8f/torch/ao/quantization/fuse_modules.py#L97-L157

As you can see on the last line, the parameter fuse_custom_config_dict is hard coded to None and not passed on to the fonction _fuse_modules.

The error is also present in the fuse_modules_qat function:
https://github.com/pytorch/pytorch/blob/c83f8ee46ab057a8bce7ed7ba7ceccba5c388d8f/torch/ao/quantization/fuse_modules.py#L159-L168

The solution would be to replace None by fuse_custom_config_dict.
Thanks!

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
replied here: https://github.com/pytorch/pytorch/pull/71956#discussion_r877644399, please feel free to add a PR if you need this, but keep in mind this is not something we plan to commit to long term
