### ISSUE TITLE
Incorrect compilation instructions for Mac

### ISSUE THREAD

**Issue by peastman** [pytorch/pytorch#7764]
The instructions at https://github.com/pytorch/pytorch#from-source for compiling from source say to use the following command on macOS:

```
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install
```

Why I try to compile with that command, it fails with the following error:

```
torch/csrc/distributed/Module.cpp:4:10: fatal error: 'unordered_map' file not
      found
#include <unordered_map>
```

I was able to get it to compile by using the following command instead:

```
MACOS_DEPOYMENT_TARGET=10.9 CC=clang CXX=clang++ CPPFLAGS="-stdlib=libc++" python setup.py install
```

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Source
- Build command you used (if compiling from source): See above
- OS: macOS 10.13.4
- PyTorch version: Latest code from repository
- Python version: 3.6.1

**Comment by ngimel** [comment]
Closing due to age.
