### ISSUE TITLE
PrimTorch's test_ops.py reference_consistency testing is worse than test_decomps.py testing

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#77687]
### 🐛 Describe the bug

`test_python_reference_consistency` appears to assume that the numerics of CPU and CUDA are implemented equivalently. This is not true and leads to a lot of tolerance overrides that have to be manually entered whenever CPU is computing in, e.g., bfloat16, while CUDA is computing in float. test_decomps.py strategy is to compute the "true" result (via double) and then accept whenever the decomp is closer than the ATen implementation. We should do it this way.

Alternately, we can stop testing reference consistency on non-CUDA backends

cc @mruberry @ezyang @ngimel @Chillee 

### Versions

master

**Comment by mruberry** [comment]
The test does seem to assume that and we thought about modeling the difference in opmath between cpu and CUDA but it was very cluttersome. 

I'm not sure the Python references are always strictly closer to the double result than the operators they reference, so I'm not sure we can test that way, however.

**Comment by Chillee** [comment]
> I'm not sure the Python references are always strictly closer to the double result than the operators they reference, so I'm not sure we can test that way, however.

We do "closer with some tolerance", which I think is reasonable.

**Comment by mruberry** [comment]
One negative of this proposal is that it won't reveal bugs like this one: https://github.com/pytorch/pytorch/issues/77942

**Comment by ezyang** [comment]
That doesn't seem so bad though :)

**Comment by mruberry** [comment]
> That doesn't seem so bad though :)

https://github.com/pytorch/pytorch/pull/78026 updates the test per this suggestion and raises a warning when the reference's result is not close to the torch op's result.

**Comment by mruberry** [comment]
Addressed by https://github.com/pytorch/pytorch/pull/78026
