### ISSUE TITLE
[NVFuser] Testing for on-by-default

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#77709]
### 🚀 The feature, motivation and pitch

Requested by Nikita as a dependency for enabling nvfuser by default:

"... we should validte that it would not regress some common trainign workflows like:"
- [ ] ResNet18 (vision)
- [ ] BERT (text?)
- [ ] Tacotron2 (audio)
- [ ] And can we also ask NV to run some basic GPU infrerence tests on consumer GPUs(say 2080/3080)

**Comment by csarofeen** [comment]
@davidberard98 can we close this issue now?
