### ISSUE TITLE
AttributeError during import after building with `USE_DISTRIBUTED=0`

### ISSUE THREAD

**Issue by NivekT** [pytorch/pytorch#77704]
### 🐛 Describe the bug

The following error is triggered when the library is imported (`import torch`), this only happens when the library was built with `USE_DISTRIBUTED=0`.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pytorch/torch/__init__.py", line 780, in <module>
    from .functional import *  # noqa: F403
  File "/Users/pytorch/torch/functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "/Users/pytorch/torch/nn/__init__.py", line 3, in <module>
    from .parallel import DataParallel
  File "/Users/pytorch/torch/nn/parallel/__init__.py", line 5, in <module>
    from .distributed import DistributedDataParallel
  File "/Users/pytorch/torch/nn/parallel/distributed.py", line 21, in <module>
    from torch.distributed.utils import (
  File "/Users/pytorch/torch/distributed/utils.py", line 121, in <module>
    process_group: dist.ProcessGroup,
AttributeError: module 'torch.distributed' has no attribute 'ProcessGroup'
```

See the original comment here: https://github.com/pytorch/pytorch/pull/77492#issuecomment-1129351628

One possible fix is to put a guard prior to importing (adding `if dist.is_available():`):
https://github.com/pytorch/pytorch/blob/7f1e331b34fd0b9caba12aa86469b59366cde9a4/torch/nn/parallel/distributed.py#L21-L25

Going forward, it may be helpful to run CIs with `USE_DISTRIBUTED=0` to catch issues like this one, though I am unsure about the costs associated with doing that.

cc: @rohan-varma 

### Versions

master

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by rohan-varma** [comment]
@drisspg I see, does `test/test_public_bindings` run anywhere in CI at the moment? If USE_DISTRIBUTED=0, do we know why test_public_bindings is importing distributed code?

**Comment by rohan-varma** [comment]
Possibly we should keep this issue open to discuss adding such a test to CI - building without distributed and smoke testing at least `import torch`. 

cc @seemethere @malfet @janeyx99, is this something that would be possible?
