### ISSUE TITLE
Cannot compile Caffe2 on Mac

### ISSUE THREAD

**Issue by peastman** [pytorch/pytorch#7770]
I am trying to compile Caffe2 from source on macOS, but no matter what I try it fails with the error

```
/Users/peastman/pytorch/caffe2/core/flags.h:59:10: fatal error: 
      'gflags/gflags.h' file not found
#include <gflags/gflags.h>
```

I installed gflags with brew, as described in the instructions.  CMake claims to have found it:

```
-- Caffe2: Found gflags with new-style gflags target.
```

and inspecting the cache confirms that:

```
$ grep gflags CMakeCache.txt 
caffe2_LIB_DEPENDS:STATIC=general;gflags;general;glog::glog;general;nomnigraph;general;nnpack;general;cpuinfo;
//The directory containing a CMake configuration file for gflags.
gflags_DIR:PATH=/usr/local/lib/cmake/gflags
```

I confirmed that the directory it selected corresponds to the brew version of gflags:

```
$ ls -l /usr/local/lib/cmake/gflags
lrwxr-xr-x  1 peastman  admin  42 May 22 13:04 /usr/local/lib/cmake/gflags -> ../../Cellar/gflags/2.2.1/lib/cmake/gflags
```

and also that the headers really are there:

```
$ ls /usr/local/Cellar/gflags/2.2.1/include/gflags/
gflags.h		gflags_declare.h
gflags_completions.h	gflags_gflags.h
```

Yet somehow the compiler still fails to find it.

## System Info

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): `make install`
- OS: macOS 10.13.4
- PyTorch version: Latest from repository
- Python version: 3.6.1
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source): Apple LLVM version 9.1.0 (clang-902.0.39.1)
- CMake version: 3.11.2
- Versions of any other relevant libraries: gflags 2.2.1

**Comment by ezyang** [comment]
Can you run `make` as `make VERBOSE=1` and paste the command that is failing? (I'm curious about the `-I` flags)

**Comment by peastman** [comment]
Here's the one it's failing on:

```
cd /Users/peastman/pytorch/buildcaffe/caffe2/perfkernels && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/Users/peastman/pytorch/buildcaffe -I/Users/peastman/pytorch -I/Users/peastman/pytorch/third_party/protobuf/src -I/Users/peastman/pytorch/third_party/googletest/googletest/include -I/Users/peastman/pytorch/third_party/benchmark/include -I/Users/peastman/pytorch/third_party/eigen -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/python2.7 -I/Users/peastman/miniconda3/lib/python3.6/site-packages/numpy/core/include -I/Users/peastman/pytorch/third_party/pybind11/include -I/Users/peastman/pytorch/third_party/onnx -I/Users/peastman/pytorch/buildcaffe/third_party/onnx  -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk   -mavx2 -mfma -mavx -mf16c -std=gnu++11 -o CMakeFiles/Caffe2_perfkernels_avx2.dir/embedding_lookup_avx2.cc.o -c /Users/peastman/pytorch/caffe2/perfkernels/embedding_lookup_avx2.cc
```

**Comment by ezyang** [comment]
Can you cat the contents of `/usr/local/lib/cmake/gflags`?

**Comment by peastman** [comment]
That's a directory.  It contains four files:

gflags-config-version.cmake
gflags-targets-release.cmake
gflags-config.cmake
gflags-targets.cmake

Do you want the full content all of all four?

**Comment by pjh5** [comment]
I have reproduced this on my end, and I'm looking into it.

**Comment by pjh5** [comment]
Some more datapoints. This also breaks the Anaconda builds when using the default gflags from the anaconda channel, but seems to work when you use the gflags from conda-forge instead. The gflags in the anaconda channel has not been updated for months, so that shouldn't be the cause. The cause must be some recent change in our build somewhere; the failures go back about a day, so a recent commit is probably the cause. None of the recent commits look that relevant though. Also, all the linux builds are fine, so whatever change caused this somehow only affects osx

**Comment by peastman** [comment]
Thanks!  I also had to disable USE_GLOG.  Once I did that, it compiled successfully.

**Comment by pjh5** [comment]
This looks resolved on my end. I never actually root caused this; it just disappeared for me a few days ago and I could no longer repro. Please re-open if you still encounter this or if you have more info.
