### ISSUE TITLE
Single Line Fix needed in old pull request, I'm not a contributor

### ISSUE THREAD

**Issue by Sheldonfrith** [pytorch/pytorch#77711]
*I would make a pull request to do this myself, but its a single line of code and I've never contributed to PyTorch so I would appreciate it if an existing contributor who already knows how to follow the pull request procedure could please do this...*

### TLDR: 
This line: https://github.com/pytorch/pytorch/blob/a7aeaaf99ef2963257709e29a856f46e940717df/aten/src/ATen/DeviceGuard.h#L25
needs the namespace `c10` added before `optional`, so that it becomes 
```
 inline c10::optional<Device> device_of(const c10::optional<Tensor>& t) {
```
... seems it got missed in the original pull request.

### More details:

This pull request: https://github.com/pytorch/pytorch/pull/45736
which was fixing this issue: https://discuss.pytorch.org/t/linker-failed-with-ambiguous-references/36255
seems to recently have been broken (see discussion in pull request comments).
This original pull request simply qualified `optional` with the namespace `c10::optional` in two files, which helps to avoid some annoying errors in some environments as mentioned in the issue linked above.

The problem:
This line in the current pytorch code: https://github.com/pytorch/pytorch/blob/a7aeaaf99ef2963257709e29a856f46e940717df/aten/src/ATen/DeviceGuard.h#L25
either did not get updated in the original pull request (unlikely, based on looking at the pull request page itself it seems that the code on the line above did not exist at the time of the pull request, but I may be reading it wrong) or somehow was added after, even though I cannot see that in the history. 

Because of these two instances of `optional` instead of `std::optional`, my compiler (and apparently other people's as well) is giving me a 'reference to ‘optional’ is ambiguous' error. As the only library I currently am using in my code is pytorch, and I have not myself defined anything named 'optional' I believe a quick change to the line mentioned above is the quickest and easiest fix for those of us experiencing this error.

**Comment by davidberard98** [comment]
@Sheldonfrith @sylvieantoun Thanks for the report and the instructions on the fix! I've landed the change that you requested, please check to see if this fixes your issue. If not feel free to reopen the issue and tag me, or open another issue.
