### ISSUE TITLE
multiprocessing: how to put a model which copied from main thread in the shared_queue

### ISSUE THREAD

**Issue by Force1ess** [pytorch/pytorch#77732]
### 🐛 Describe the bug

1. If I shared a model in cuda, it raises
```RuntimeError: Attempted to send CUDA tensor received from another process; this is not currently supported. Consider cloning before sending.``` 
Specifically, I accept a model from the main process and return a duplication create by using ```copy.deepcopy(model)```
2. ```torch.multiprocessing.manager.queue.get``` taken a long time to finish. If the queue just passed a file descriptor, I don't think it should take 1/3 of the total time, is there any faster way?
Here's my script
I opened a [thread](https://discuss.pytorch.org/t/how-sharing-memory-actually-worked-in-pytorch/151706) in pytorch'forum also

I think this is related to #10375 #9996 and #7204

```python
import torch

import torch.multiprocessing as mp

from copy import deepcopy

from functools import partial

from time import *

from torchvision import models

import numpy as np

from tqdm import tqdm

def parallel_produce(

    queue: mp.Queue,

    model_method,

    i

) -> None:

    pure_model: torch.nn.Module = model_method()

    # if you delete this line, model can be passed
    pure_model.to('cuda')

    pure_model.share_memory()

    while True:

        corrupt_model = deepcopy(pure_model)

        dic = corrupt_model.state_dict()

        dic[list(dic.keys())[0]]*=2

        corrupt_model.share_memory()

        queue.put(corrupt_model)

def parallel(

    valid,

    iteration: int = 1000,

    process_size: int=2,

    buffer_size: int=2

):

    pool = mp.Pool(process_size)

    manager = mp.Manager()

    queue = manager.Queue(buffer_size)

    SeedSequence = np.random.SeedSequence()

    model_method = partial(models.squeezenet1_1,True)

    async_result = pool.map_async(

        partial(

            parallel_produce,

            queue,

            model_method,

        ),

        SeedSequence.spawn(process_size),

    )

    time = 0

    for iter_times in tqdm(range(iteration)):

        start = monotonic_ns()

        # this takes a long time

        corrupt_model: torch.nn.Module = queue.get()

        time += monotonic_ns() - start

        corrupt_model.to("cuda")

        corrupt_result = corrupt_model(valid)

        del corrupt_model

    pool.terminate()

    print(time / 1e9)

if __name__ == "__main__":

    valid = torch.randn(1,3,224,224).to('cuda')

    parallel(valid)

```

#total time of queue.get taken

![image](https://user-images.githubusercontent.com/72636351/168984869-cc4e884d-1774-4b9f-81c8-701f4f02b7dc.png)

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.5.119
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
Nvidia driver version: 512.77
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] pytorchfi==0.6.0
[pip3] torch==1.10.0+cu113
[pip3] torch-tb-profiler==0.3.1
[pip3] torchaudio==0.10.0+cu113
[pip3] torchei==0.0.4
[pip3] torchinfo==1.5.4
[pip3] torchstat==0.0.7
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.1+cu113
[conda] Could not collect

cc @VitalyFedyunin

**Comment by Force1ess** [comment]
@apaszke  @colesbury @ptrblck 
Hi, sorry to bother you, but I've been stuck with this problem for months.
you guys were great community participants, I wonder if you have any advanced opinions about this.
Thanks for your patience
Best Wish

**Comment by VitalyFedyunin** [comment]
hello! there is some weird circular referencing going on here. I'm debugging it now.

**Comment by VitalyFedyunin** [comment]
It was interesting issue with two take aways:
1) `mp.Manager` actually does something weird with Queue (pulls items from it and puts them back, causing the error in question). Please avoid using it.
2) Putting model in the Queue is bad. Please put `state_dict` of the model instead.

Below is modified example (not optimized, but working):

```python

import torch

import torch.multiprocessing as mp

from copy import deepcopy

from functools import partial

from time import *

from torchvision import models

import numpy as np

from tqdm import tqdm

def parallel_produce(

    queue: mp.Queue,

    model_method,

    iterations,

    i,

 
) -> None:
    pure_model: torch.nn.Module = model_method()
    # if you delete this line, model can be passed
    pure_model.to('cuda')

    for j in range(iterations):
        corrupt_model = deepcopy(pure_model)
        dic = corrupt_model.state_dict()
        dic[list(dic.keys())[0]]*=2
        queue.put(corrupt_model.state_dict())

def parallel(

    valid,

    iteration: int = 1000,

    process_size: int=2,

    buffer_size: int=2

):
    
    model_method = partial(models.squeezenet1_1,True)
    ctx = mp.get_context('spawn')
    pool = ctx.Pool(process_size)
    queue = ctx.Queue(buffer_size)

    proc = []
    for i in range(process_size):
        p  = ctx.Process(target = parallel_produce, args=(queue,model_method,iteration // process_size,i,))
        p.start()
        proc.append(p)

    time = 0
    
    corrupt_model = model_method()

    for iter_times in tqdm(range(iteration)):        
        start = monotonic_ns()
        # this takes a long time
        state = queue.get()
        corrupt_model.load_state_dict(state)
        time += monotonic_ns() - start
        corrupt_model.to("cuda")
        corrupt_result = corrupt_model(valid)

    for p in proc:
        p.join()

    print(time / 1e9)

if __name__ == "__main__":

    valid = torch.randn(1,3,224,224).to('cuda')

    parallel(valid)

```

**Comment by Force1ess** [comment]
Hi, @VitalyFedyunin 
Your code looks works for me,  you helped a lot, thanks!
Do you have any idea about my other problem, why ```queue.get()``` take so long, since it just passed a file descriptor?

**Comment by Force1ess** [comment]
@VitalyFedyunin 
Also, putting ```state_dict``` in the queue cannot use ```share_memory```
So, does it directly transfer data between processes and that's why it takes so long?
If I use  ```state_dict```, is there any method to pass a file descriptor instead of data

**Comment by Force1ess** [comment]
@VitalyFedyunin 
I tried ```queue.get(block=False)```, and nothing changed at all.
It's not caused by waiting for the producer process.
Is there any more efficient way to transfer data?
You can try this:
```python
import torch

import torch.multiprocessing as mp

from copy import deepcopy

from functools import partial

from time import *

from torchvision import models

import numpy as np

from tqdm import tqdm

def parallel_produce(

    queue: mp.Queue,

    model_method,

    iterations,

    i,

 
) -> None:
    pure_model: torch.nn.Module = model_method()
    # if you delete this line, model can be passed
    pure_model.to('cuda')

    for j in range(iterations):
        corrupt_model = deepcopy(pure_model)
        dic = corrupt_model.state_dict()
        dic[list(dic.keys())[0]]*=2
        queue.put(corrupt_model.state_dict())

def parallel(

    valid,

    iteration: int = 1000,

    process_size: int=2,

    buffer_size: int=2

):
    
    model_method = partial(models.squeezenet1_1,True)
    ctx = mp.get_context('spawn')
    pool = ctx.Pool(process_size)
    queue = ctx.Queue(buffer_size)

    proc = []
    for i in range(process_size):
        p  = ctx.Process(target = parallel_produce, args=(queue,model_method,iteration // process_size,i,))
        p.start()
        proc.append(p)

    time = 0
    
    corrupt_model = model_method()
    sleep(3)
    for iter_times in tqdm(range(iteration)):        
        start = monotonic_ns()
        # this takes a long time
        state = queue.get(block = False)
        corrupt_model.load_state_dict(state)
        time += monotonic_ns() - start
        corrupt_model.to("cuda")
        corrupt_result = corrupt_model(valid)

    for p in proc:
        p.join()

    print(time / 1e9)

if __name__ == "__main__":

    valid = torch.randn(1,3,224,224).to('cuda')

    parallel(valid)
```

**Comment by weilixiang** [comment]
I am using Multiprocess.Manager().dict() to store the copied model state by using deepcopy, but still getting 
RuntimeError: Attempted to send CUDA tensor received from another process; this is not currently supported. Consider cloning before sending.
Is it because of mp.Manager() issue?

**Comment by Force1ess** [comment]
Multiprocessing module definitely needs a separate section to illustrate instead of [original module](https://pytorch.org/docs/stable/multiprocessing.html#:~:text=Because%20of%20the%20similarity%20of%20APIs%20we%20do%20not%20document%20most%20of%20this%20package%20contents%2C%20and%20we%20recommend%20referring%20to%20very%20good%20docs%20of%20the%20original%20module.)
> Because of the similarity of APIs we do not document most of this package contents, and we recommend referring to very good docs of the original module.
How can we issue this proposition?
