### ISSUE TITLE
Error when comparing MPS tensors

### ISSUE THREAD

**Issue by Leonard-Zeng** [pytorch/pytorch#77750]
### 🐛 Describe the bug

I tried the following code but got the wrong results

```
import torch

t = torch.tensor([1, 2, 3, 4], device='mps')
t[2:] <= t[:2] # Expected [False, False] but got [True, True].
```

### Versions

PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:37) [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[conda] numpy                     1.22.3          py310h99fd38b_2    conda-forge
[conda] pytorch                   1.12.0.dev20220518        py3.10_0    pytorch-nightly

cc @ezyang @gchanan @zou3519

**Comment by albanD** [comment]
Hi,

Thanks for the report.
We did identify an issue with the view handling there and we are preparing a PR to fix that.

As a temporary workaround, you can avoid the comparison on the view by cloning the first Tensor: `print(t[2:].clone() <= t[:2])`. Does that work for you?

**Comment by Leonard-Zeng** [comment]
Yes, it works. Thanks. 
Would this issue be solved in the near future? I think it may cause an issue when using the faster-rcnn.

**Comment by albanD** [comment]
Yes, we are planning to solve that before the week end.

**Comment by albanD** [comment]
Fixed in master now.
