### ISSUE TITLE
TypeError: Trying to convert Double to the MPS backend but there is no mapping for it.

### ISSUE THREAD

**Issue by Raphtor** [pytorch/pytorch#77781]
### 🐛 Describe the bug

Steps to reproduce:
```
import torch
mps_device = torch.device("mps")
z = torch.ones(5, device=mps_device)
z = torch.ones(5, device=mps_device, dtype=float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Trying to convert Double to the MPS backend but there is no mapping for it.
z = torch.ones(5, device=mps_device, dtype=torch.float32)
z = torch.ones(5, device=mps_device, dtype=torch.float64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Trying to convert Double to the MPS backend but there is no mapping for it.
```

### Versions

PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:06)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] torch==1.12.0.dev20220518
[conda] numpy                     1.22.0           py39h61a45d2_0    conda-forge
[conda] pytorch                   1.12.0.dev20220518         py3.9_0    pytorch-nightly

**Comment by albanD** [comment]
Hi!

I am afraid that the MPS framework does not support double precision numbers.
You can use `float32` though.

We should improve that error message to clarify this (and potentially link to the metal doc referencing this)

**Comment by Raphtor** [comment]
ah gotcha - I suppose implicit conversion would result in unexpected behavior.

**Comment by philipturner** [comment]
This comment might be particularly relevant:

https://discuss.pytorch.org/t/code-didnt-speed-up-as-expected-when-using-mps/152016/6?u=philipturner

**Comment by albanD** [comment]
Hi,

The PR linked above is going to clarify the double situation.
The issue when converting to float via `.to()` is known and is already fixed in master.

**Comment by albanD** [comment]
The error message is now properly updated in master.
