### ISSUE TITLE
qnnpack cannot be built on Apple M1 and is disabled

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/pytorch#77811]
### 🐛 Describe the bug

I'm trying to build PyTorch 1.11.0 from source using the [Spack](https://spack.io) package manager on macOS 12.3.1 and Apple M1 Pro with Apple Clang 13.1.6 and Python 3.9.12. During installation, I see the following error message:
```
    [471/1268] Linking C static library lib/libpsimd.a
    FAILED: lib/libpsimd.a
    : && /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.1-2ipwayeri23f5s5wp4bpwmtmp3itsvlf/bin/cmake -E rm -f lib/libpsimd.a && /usr/bin/ar qc lib/libpsimd.a   && /usr/bin/ranlib lib/libpsimd.a && /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.1-2ipwayeri23f5s5wp4bpwmtmp3itsvlf/bin/cmake -E touch lib/libpsimd.a && :
    ar: no archive members specified
    usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
    [472/1268] Linking C static library lib/libfxdiv.a
    FAILED: lib/libfxdiv.a
    : && /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.1-2ipwayeri23f5s5wp4bpwmtmp3itsvlf/bin/cmake -E rm -f lib/libfxdiv.a && /usr/bin/ar qc lib/libfxdiv.a   && /usr/bin/ranlib lib/libfxdiv.a && /Users/ajstewart/spack/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/cmake-3.23.1-2ipwayeri23f5s5wp4bpwmtmp3itsvlf/bin/cmake -E touch lib/libfxdiv.a && :
    ar: no archive members specified
    usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]
```
Here are the full build logs:

* [build log](https://github.com/pytorch/pytorch/files/8721819/spack-build-out.txt)
* [build env](https://github.com/pytorch/pytorch/files/8721821/spack-build-env-mods.txt)

### Versions

PyTorch version: 1.11.0
Is debug build: no
CUDA used to build PyTorch: no
ROCM used to build PyTorch: no

OS: macOS 12.3.1 (arm64)
GCC version: 11.2.0 (gfortran only)
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: 3.23.1
Libc version: N/A

Python version: 3.9.12 (main, May 17 2022, 17:23:23) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

cc @malfet @seemethere @albanD

**Comment by adamjstewart** [comment]
I'm seeing the same thing on the master branch too.

**Comment by albanD** [comment]
Just as a side note: 1.11 source does not contain any of the recently added MPS code. So this is independent of that.

Note that internally, we do disable nnpack and xnnpack for our arm builds as they are indeed problematic. If you don't need these libraries, I would recommend you do the same as https://github.com/pytorch/pytorch/blob/fd121dfeec4895a61372d35b96f3d645ab1e73dd/.jenkins/pytorch/macos-build.sh#L36

**Comment by jspisak** [comment]
cc @malfet

**Comment by adamjstewart** [comment]
Thanks @albanD, disabling mkldnn/nnpack/qnnpack worked! Should we keep this issue open as a point of reference that these features don't yet work on M1, or is there an existing issue open to track this?

**Comment by albanD** [comment]
I don't think there are any issues related to that.
The problem I think is that these libs don't build on arm. So not much we can do on our end.

**Comment by adamjstewart** [comment]
Yeah, I've tried opening issues with these repos in the past and didn't have much luck. It looks like the qnnpack repo is actually archived. Not sure where else to open issues.

Spack explicitly enables/disables things like nnpack/qnnpack based on what features the user asks for, it doesn't rely on CMake defaults. Maybe that's why I'm the only one who's hit this problem? Anyway, I'll update our Spack build recipe to disable these options on M1. Thanks for all the help!

P.S. If anyone wants to volunteer to help maintain our build recipe let me know! It currently looks like [this](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-torch/package.py).

**Comment by malfet** [comment]
Actually, NNPACK should be buildable for ARM64, and MKLDNN as well, but QNNPACK is indeed archived repo and as such not usable on M1

**Comment by adamjstewart** [comment]
Thanks, let me try building with NNPACK. I couldn't get MKLDNN working as Intel-oneapi-mkl wasn't working for me: https://github.com/spack/spack/issues/30716. Does anyone know the best way to install MKL on macOS arm64?

**Comment by adamjstewart** [comment]
@malfet you're right, NNPACK builds fine too. Can't test MKLDNN but it sounds like QNNPACK may be the only thing that doesn't work on arm64.

**Comment by albanD** [comment]
As mentioned above, qnnpack is not available of M1 and is archived (so unlikely to add support anytime soon). So closing this for now.
