### ISSUE TITLE
FSDP should work for model outputs that are dataclasses

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#77812]
### 🚀 The feature, motivation and pitch

FSDP currently supports dict/OrderedDict, tuple, list of tensor outputs, although we've seen some use cases also want to output `dataclass` instances from their model. This currently breaks in `_apply_to_tensors` when registering backwards hooks, we should add this support for dataclasses.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by awgu** [comment]
I think this is completed:
https://github.com/pytorch/pytorch/blob/4fecbebc3731161dc0b16a62a889db6d75063acf/torch/distributed/utils.py#L211-L216
