### ISSUE TITLE
tensor([bool], device='mps:0').type(torch.float) returns different values when using 'mps' device and 'cpu' device

### ISSUE THREAD

**Issue by tat757** [pytorch/pytorch#77835]
### 🐛 Describe the bug

mps returns the wrong result when using bool to torch.float

```python
import torch
import numpy as np

test = torch.from_numpy(np.asarray([True, True, True, False])).to('mps')
print(test)

print(test.type(torch.float))

test = torch.from_numpy(np.asarray([True, True, True, False])).to('cpu')
print(test)

print(test.type(torch.float))
```

```
tensor([ True,  True,  True, False], device='mps:0')
tensor([9.2196e-41, 3.6013e-43, 2.3694e-38, 9.1837e-41], device='mps:0')
tensor([ True,  True,  True, False])
tensor([1., 1., 1., 0.])
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14)  [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.12.0.dev20220518          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by albanD** [comment]
Hi,

Thanks for the report!
I think this is the same as https://github.com/pytorch/pytorch/issues/77849

I will close this issue in favor of that other issue to keep all the discussion in the same place.
