### ISSUE TITLE
When will the amd gpu version for mac be released？

### ISSUE THREAD

**Issue by Yuri-Su** [pytorch/pytorch#77833]
### 🚀 The feature, motivation and pitch

I read the good news that pytorch already supports GPU acceleration with Apple silicon, but will AMD GPU support come soon?

cc @ezyang @seemethere @malfet @albanD

**Comment by tcapelle** [comment]
I really really don't think so, as apple is getting rid of AMD gpus in their systems,

**Comment by albanD** [comment]
Hi,

This is already working if you're compiling from source.
The binaries are a bit more tricky as there are a lot of older x86 macos versions. This is being worked on at https://github.com/pytorch/pytorch/pull/77662 if you want to follow when the binaries will be available on nightly.

**Comment by Yuri-Su** [comment]
> Hi,
> 
> This is already working if you're compiling from source. The binaries are a bit more tricky as there are a lot of older x86 macos versions. This is being worked on at #77662 if you want to follow when the binaries will be available on nightly.

Is the latest 1.13 AMD GPU version available?

**Comment by malfet** [comment]
PyTorch nightly builds for both Intel and M1 starting with May 23rd should include mps support:
```
% arch; python -c "import torch;print(torch.__version__, torch.rand(3, 3, device='mps'))"
i386
1.13.0.dev20220524 tensor([[0.5542, 0.5423, 0.7949],
        [0.1751, 0.5634, 0.8227],
        [0.0730, 0.6094, 0.9997]], device='mps:0')

```
