### ISSUE TITLE
[feature request]  Update Tutorials for GPUs

### ISSUE THREAD

**Issue by arsalan993** [pytorch/pytorch#7784]
https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html
Above tutorial is running on CPU. by using the following piece of code it is meant to run on GPU but it is not happening.
`dtype = torch.float`
`device = torch.device("cpu")`
`dtype = torch.device("cuda:0") # Uncomment this to run on GPU`
 I have CUDA version 8. and my GPU is Nvidia 1050ti 
Can you guide me on how to execute your given tutorials on GPU

**Comment by apaszke** [comment]
I can't see those lines in the tutorial you linked. If you'd like to see it ported to GPU, please open an issue in the [tutorials repo](https://github.com/pytorch/tutorials).
