### ISSUE TITLE
torch.zeros(4, 0) returns a Tensor whose size is 4, not 0

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/pytorch#7785]
`torch.zeros(4, 0)` returns a Tensor whose size is 4, not 0

And `torch.zeros(4, 0, 2)` return a Tensor whose size is still 4.

`np.zeros((4, 0))` returns `array([], shape=(4, 0), dtype=float64)`. Any idea?

**Comment by ezyang** [comment]
Yes, this is definitely wrong. In general, we don't currently support zero-size dimensions correctly, because TH has historically not handled it correctly. @gchanan plans to fix this in the near future.

**Comment by acgtyrant** [comment]
My english is poor, you can change my title to discribe the bug accurately. Or if there is any duplicate issue already, just reference it and close my issue.

**Comment by ezyang** [comment]
OK, I think the old bug is: https://github.com/pytorch/pytorch/issues/5014
