### ISSUE TITLE
Autocast causes GRU memory to explode on AMD ROCm

### ISSUE THREAD

**Issue by XabiKrant** [pytorch/pytorch#77878]
### 🐛 Describe the bug

I have an example where the gpu memory used by the GRU explodes on the AMD ROCm but not on a NVIDIA gpu. The issue seems to be caused by autocast, with autocast disabled the memory usage is comparable. Without autocast the allocated memory on AMD is 0.4GB, with autocast the AMD uses 5.1GB. The nvidia gpu uses 0.2GB in both cases. If possible I would still like to use autocast on AMD as well.

```
# -*- coding: utf-8 -*-
import torch
from torch import nn
from torch.cuda.amp import autocast
import sys

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

rnn = nn.GRU(input_size=768, hidden_size=512, batch_first=True,
                                 bidirectional=True, num_layers=3, dropout=0.5).to(device)

inputs = torch.randn(10, 231, 768).to(device)
h0 = torch.randn(2, 3, 768).to(device)
print('Allocated after init:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')

with autocast():
    output, hn = rnn(inputs)
    print(output.dtype)
        
print('Allocated after rnn pass:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
print('Size of output:', sys.getsizeof(output.storage()))
print('Size of hn:', sys.getsizeof(hn.storage()))
```

Output on nvidia:
```
Allocated after init: 0.1 GB
torch.float32
Allocated after rnn pass: 0.2 GB
Size of output: 9461832
Size of hn: 122952
```

Output on AMD:
```
Allocated after init: 0.1 GB
torch.float16
Allocated after rnn pass: 5.1 GB
Size of output: 4730928
Size of hn: 61488
```

### Versions

**NVIDIA**
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A
OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.2.5
Python version: 3.7.4 (default, Jan 28 2020, 11:27:36)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
Nvidia driver version: 460.67
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.6.0
[pip3] torchaudio==0.11.0.dev20211229+cu102
[pip3] torchvision==0.12.0.dev20211228+cu102
[conda] Could not collect

PyTorch version: 1.11.0+rocm4.5.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 4.4.21432-f9dccde4

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

**AMD**
Python version: 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 40421.43.2
MIOpen runtime version: 2.14.0
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0+rocm4.5.2
[pip3] torchvision==0.12.0+rocm4.5.2
[conda] libblas                   3.9.0            14_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            14_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            14_linux64_mkl    conda-forge
[conda] mkl                       2022.0.1           h8d4b97c_803    conda-forge
[conda] numpy                     1.22.3          py310h4ef5377_2    conda-forge
[conda] torch                     1.11.0+rocm4.5.2          pypi_0    pypi
[conda] torchvision               0.12.0+rocm4.5.2          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by malfet** [comment]
@jeffdaily can you please check if this is reproducible on your end?

**Comment by jeffdaily** [comment]
I just tried latest ROCm 5.5 nightly wheel and got the following output:

```
Allocated after init: 0.1 GB
torch.float32
Allocated after rnn pass: 0.3 GB
gru.py:20: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print('Size of output:', sys.getsizeof(output.storage()))
Size of output: 9461808
Size of hn: 122928
```

**Comment by jithunnair-amd** [comment]
Closing based on above comment.
