### ISSUE TITLE
Crashes when working with visual debugger

### ISSUE THREAD

**Issue by Elizaveta239** [pytorch/pytorch#7788]
Hi! I'm working on PyCharm's debugger and we have several users who have problems running PyCharm's debugger with PyTorch: https://youtrack.jetbrains.com/issue/PY-25513

The have the following problems:
"My program is a neural network training program using PyTorch, GPU computations are asynchronous, variables that are stored in GPU are transfered back to CPU memory only when required to print. Let's say A and B are very huge tensors, the low-level implementation is such that C=A+B will finish before the actual calculation is complete. The low-level optimization is even more aggressive such that when there are a series of operations, e.g., A=random(10000,10000), B=A*A+2*A+1, C=A+B, it will finish and return control to the debugger even before the C is allocated, and then PyCharm's auto variable display, i.e., "collecting data...", will try to display the not-yet allocated data object C, which will lead to corrupted output on slower computers, or even causing the program crash. The behavior is very random, i.e., sometimes it can display correctly, sometimes it cannot display, sometime it crashes subsequently. Moreover, the anomaly becomes more frequent when the object is large and the computer is slow."

In PyCharm's debugger, when program execution is stopped at some breakpoint, we're evaluating all the local variables values, and sometimes it can lead to crashes.

We would like to help our users and to create a workaround, or maybe a proper fix for the problem. Could you please help me with the following questions:

1. Do you have any ability to distinguish, which variables are available for showing/printing? And which values are under optimization and can't be reached yet?
2. Do you know about any other visual debuggers, which work fine with variables computed with PyTorch? I didn't manage to find here any issues about similar problems. Do your users use such debuggers at all?

Thank you!

**Comment by apaszke** [comment]
PyTorch generally takes care of all the CPU-GPU synchronization, and will insert it in certain points when it's needed. Because of that we don't need any way of querying whether the data is ready or not. How is your debugger printing the tensors? Is it just calling `__str__`?

I'm not aware of any other debuggers that would have this issue.

**Comment by Elizaveta239** [comment]
@apaszke Thank you for your answer! Yes, we just iterate through local variables and call `__str__` of them. Well, it looks like it isn't the real problem of crash.
Also inside debugger we iterate through all alive threads (returned by `threading.enumerate()`) and add some attributes to these objects. Does PyTorch do anything special with programs's threads? How do you think, can it lead to crashes in some cases?

**Comment by apaszke** [comment]
Yeah, `__str__` should be safe to use any time. Same applies to threads I think. Off the top of my head, I can't think of anything weird we might be doing with threads.

**Comment by Elizaveta239** [comment]
Thank you very much! So, it looks like the problem is somewhere inside our debugger, I'll keep investigating it.

**Comment by ngimel** [comment]
Closing due to age.
