### ISSUE TITLE
Segmentation fault in _compute_linear_combination

### ISSUE THREAD

**Issue by neochristou** [pytorch/pytorch#77889]
### 🐛 Describe the bug

Segmentation fault in `_compute_linear_combination`.

### Example to reproduce

```python
import torch

input = torch.full((), 65534, dtype=torch.int64, requires_grad=False)
coefficients = torch.full((5, 1, 5, 5,), 1, dtype=torch.float32, requires_grad=False)
torch._compute_linear_combination(input, coefficients)
```

### Result
```segmentation fault```

### Expected behavior
Graceful termination or a RuntimeError to be thrown.

### Note
This bug was discovered using IvySyn, a fuzz testing tool which is currently being developed at Secure Systems Labs at Brown University.

### Versions

Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch                   1.11.0              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.11.0                 py39_cpu    pytorch
[conda] torchvision               0.12.0                 py39_cpu    pytorch

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nikitaved** [comment]
It is a private utility function used in matrix_exp for non-empty tensors. So I am not sure we have to fix that.

**Comment by Lezcano** [comment]
@albanD on leaking things to the API. I believe we should just avoid exporting this one in  the relevant `__all__` but that's BC breaking. What to do... @mruberry .

**Comment by albanD** [comment]
@neochristou could you give some details on why you use that function? You should not be using it in general.

**Comment by nikitaved** [comment]
@albanD This is found with some sort of automatic tool.

**Comment by albanD** [comment]
We provide no guarantee for our non-public APIs. So that's fine I think.
