### ISSUE TITLE
Segmentation fault in lu_unpack

### ISSUE THREAD

**Issue by neochristou** [pytorch/pytorch#77898]
### 🐛 Describe the bug

Segmentation fault in `lu_unpack`.

### Example to reproduce

```python
import torch

LU_data = torch.empty((0, 3, 8, 0, 6,), dtype=torch.float64)
LU_pivots = torch.empty((3,), dtype=torch.int32)
unpack_data = True
unpack_pivots = True
torch.lu_unpack(LU_data, LU_pivots, unpack_data, unpack_pivots)
```

### Result
```segmentation fault```

### Expected behavior
Graceful termination or a RuntimeError to be thrown.

### Note
This bug was discovered using IvySyn, a fuzz testing tool which is currently being developed at Secure Systems Labs at Brown University.

### Versions

Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.2           py39h20f2e39_0
[conda] numpy-base                1.21.2           py39h79a1101_0
[conda] pytorch                   1.11.0              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.11.0                 py39_cpu    pytorch
[conda] torchvision               0.12.0                 py39_cpu    pytorch

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @albanD @jbschlosser @kshitij12345

**Comment by nikitaved** [comment]
The documentation mentions that inputs for `lu_unpack` should be coming from the `lu` method.

**Comment by albanD** [comment]
@nikitaved is there a simple way to check that?

In general though, for our public APIs, it should not be able to segfault whatever you do.

**Comment by nikitaved** [comment]
No, unfortunately, there is no way. The pivot tensor has to be of right shape and has to have valid values.

**Comment by nikitaved** [comment]
Or we could push these checks into the kernel that unpacks pivots. What do you think about that, @albanD ?

**Comment by Lezcano** [comment]
Imo we should not check for these things. This and lu_solve are very specific low level functions. Either you use them as lu_factor + one of these or you better know what you are doing.

We could put an assert in these kernels, but as I said, these functions are very low level, so I would not even bother. I do not know if any reasonable way to get a valid LU decomposition in this format other than going through lu_factor
