### ISSUE TITLE
Supper `DimensionNode::isDynamic()` API via `lazy::Shape::is_symbolic()`

### ISSUE THREAD

**Issue by miladm** [pytorch/pytorch#77909]
### 🚀 The feature, motivation and pitch

Please enable [`DimensionNode::isDynamic()`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/lazy/ts_backend/dynamic_ir.h#L48-L51) API (and child classes) to leverage [`lazy::Shape::is_symbolic()`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/lazy/core/shape.h#L43-L45).

**Comment by miladm** [comment]
@miladm to follow this support by integrating it into PyTorch/XLA: https://github.com/pytorch/xla/pull/3558

**Comment by miladm** [comment]
@Gamrix do we have a PR out for this issue already?

CC @Krovatkin

**Comment by Gamrix** [comment]
Yes, it just landed #77917
