### ISSUE TITLE
Compiling C/C++ extension receive undefined symbol: _ZTIN5torch8autograd8Variable4ImplE on importing into python.

### ISSUE THREAD

**Issue by kevinj22** [pytorch/pytorch#7790]
Hello,

I am attempting to compile a C/C++ extension using the ATen library. It compiles fine with the following setup.py file:

```
import setuptools
import torch
import torch.utils.cpp_extension
from torch.utils.cpp_extension import BuildExtension

ext_modules = [setuptools.Extension(
        name='Aten_Example',
        sources=['Aten_Example.cpp'],
        include_dirs= ['/usr/local/lib/python3.6/site-packages/torch/lib/include', '/usr/local/lib/python3.6/site-packages/torch/lib/include/TH', '/usr/local/lib/python3.6/site-packages/torch/lib/include/THC','/usr/local/include/python3.6m/pybind11/','/usr/local/include/python3.6m/'],
        extra_compile_args=['-std=c++11'],
        language='c++')]

setuptools.setup(
        name='Aten_Example',
        ext_modules=ext_modules,
        cmdclass={'build_ext' : BuildExtension}
)
```

The C++ code is the following: 

```
#include <torch/torch.h>
#include <iostream>

at::Tensor d_sigmoid(at::Tensor z)
{
	auto s = at::sigmoid(z);
	return (1-s) * s;
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME,m)
{
	m.def("d_sigmoid", &d_sigmoid,"Derivative of Sigmoid");
}
```

When imported into python I receive the following error:

ImportError: /usr/local/lib/python3.6/site-packages/Aten_Example-0.0.0-py3.6-linux-x86_64.egg/Aten_Example.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN5torch8autograd8Variable4ImplE

I'm not sure how to fix this. From what I've read I assume I need to add some library links to the compiler?

**Comment by apaszke** [comment]
How did you install PyTorch and what’s your compiler version? Please update the issue with the default template, we need this information to help you.

**Comment by kevinj22** [comment]
Hello,

I figured it out by reading the tutorial (https://pytorch.org/tutorials/advanced/cpp_extension.html) more carefully

Once your extension is built, you can simply import it in Python, using the name you specified in your setup.py script. Just be sure to import torch first, as **this will resolve some symbols that the dynamic linker must see.**

If I import torch before the module it works.
