### ISSUE TITLE
TensorList out= ops alias annotations aren't plumbed properly into `torch.ops.aten

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#77920]
Taking `at::split_copy.Tensor_out` as an example and running the below code:
```
>>> str(torch.ops.aten.split_copy.Tensor_out._schema)
'aten::split_copy.Tensor_out(Tensor self, int split_size, int dim=0, *, Tensor[] out) -> ()'
```
You can see that there are no alias annotations printed in the schema.

But the `out=` argument to `split_copy` is supposed to have alias annotations. If you look at the codegen output for registering that operator the dispatcher in `RegisterSchema.cpp`, you can see:
```
m.def("split_copy.Tensor_out(Tensor self, int split_size, int dim=0, *, Tensor(a!)[] out) -> ()");
```

So at some point in the C++ schema parsing code, we're probably losing the alias annotations

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by anjali411** [comment]
hmm not sure where this happens but IIRC, the alias info stored on the actual function schema object is correct
