### ISSUE TITLE
Tag v0.4.0 eigen submodule no longer downloads

### ISSUE THREAD

**Issue by k-chaney** [pytorch/pytorch#7793]
## Issue description

When I checkout v0.4.0 and run a submodule update it can no longer find github.com/RLovelett/eigen.git

This third party repository going down probably coincided with pull request #7089

## Code example

```
git clone https://github.com/pytorch/pytorch
git checkout v0.4.0
git submodule update --init
```

Output that concerns this issue
```
Cloning into 'third_party/eigen'...
Username for 'https://github.com': k-chaney
Password for 'https://k-chaney@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found
fatal: clone of 'https://github.com/RLovelett/eigen.git' into submodule path 'third_party/eigen' failed
```

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Source
- Build command you used (if compiling from source): not there yet
- OS: Ubuntu 16.04
- PyTorch version: v0.4.0
- Python version: 2.7.12
- CUDA/cuDNN version: CUDA 9.0 cuDNN 7
- GPU models and configuration: Titan X
- GCC version (if compiling from source): Not there yet
- CMake version: Not there yet
- Versions of any other relevant libraries:

**Comment by ailzhang** [comment]
We probably want to make a new tag v0.4.0 to point to the right eigen. It doesn't affect pytorch since it not a caffe2 dependency. cc: @soumith

**Comment by soumith** [comment]
I'll fix this tomorrow. I'll fix the v0.4.0 tag itself.

**Comment by mkummer225** [comment]
@soumith @alizhang Were you able to update the v0.4.0 tag? https://github.com/pytorch/pytorch/tree/v0.4.0/third_party

I've been going on 3ish days trying to get PT / Caffe2 to build

**Comment by k-chaney** [comment]
@mkummer225 I haven't tried to build Caffe2, but Pytorch will build and run (my users haven't notified me of anything that is broken) if make the change noted below. While this may not be the official solution (I'm not aware of their plan to fix it) it may work for you temporarily.

```
diff --git a/.gitmodules b/.gitmodules
index 0d88b7d..7b03885 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -22,7 +22,7 @@
        url = https://github.com/NVlabs/cub.git
 [submodule "third_party/eigen"]
        path = third_party/eigen
-       url = https://github.com/RLovelett/eigen.git
+       url = https://github.com/eigenteam/eigen-git-mirror.git
 [submodule "third_party/googletest"]
        path = third_party/googletest
        url = https://github.com/google/googletest.git
```

**Comment by soumith** [comment]
the tag v0.4.0 is now updated to point to the eigenteam github mirror, rather than RLovelett/eigen.git

**Comment by mkummer225** [comment]
@k-chaney awesome, thanks for this - I'll take note in case I run into a similar issue in the future

@soumith thanks for making the change so quickly - I think there was something else wrong with my build env that caused some downstream errors, I was able to resolve them by removing any unnecessary package installs and reverting to the provided caffe2 Dockerfile's (specifically caffe2ai/caffe2:c2v0.8.1.cpu.min.ubuntu16.04)
