### ISSUE TITLE
convolution operator not implemented for mps device

### ISSUE THREAD

**Issue by XWHtorrentx** [pytorch/pytorch#77931]
### 🐛 Describe the bug

I was training resnet50 (code from torchvision) on m1 pro Macbook. 
`NotImplementedError: Could not run 'aten::_slow_conv2d_forward' with arguments from the 'MPS' backend.`
I tried every network from torchvision which consists of convolution operator, same error. 

### Versions

# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.5.18            h4653dfc_0    conda-forge
certifi                   2022.5.18                pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
libffi                    3.4.2                h3422bc3_5    conda-forge
libzlib                   1.2.11            h90dfc92_1014    conda-forge
matplotlib                3.5.2                    pypi_0    pypi
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.22.3                   pypi_0    pypi
openssl                   3.0.3                ha287fd2_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pillow                    9.1.1                    pypi_0    pypi
pip                       22.1               pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.9.12          h14b404e_1_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytorch-ignite            0.4.9                    pypi_0    pypi
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
setuptools                62.3.1           py39h2804cbe_0    conda-forge
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.5               h40dfcc0_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
torch                     1.12.0.dev20220519          pypi_0    pypi
torchaudio                0.11.0                   pypi_0    pypi
torchvision               0.12.0                   pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            h90dfc92_1014    conda-forge

cc @kulinseth @albanD

**Comment by malfet** [comment]
Can you please run `python -mtools.utils.collect_env` and post its output here

**Comment by anirbansaha96** [comment]
@malfet 
```console
(torch-nghtly-gpu) anirbansaha@Anirbans-MacBook-Air ~ % python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 1.13.0.dev20220528
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:16)  [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0rc1
[pip3] torch==1.13.0.dev20220528
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.23.0rc1                pypi_0    pypi
[conda] torch                     1.13.0.dev20220528          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
```

**Comment by Lyken17** [comment]
Same issue here. Here is my environements

```
(mps) ➜  Workspace python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 1.13.0.dev20220529
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.21.3
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0rc1
[pip3] torch==1.13.0.dev20220529
[pip3] torchvision==0.14.0a0+f0f8a3c
[conda] numpy                     1.23.0rc1                pypi_0    pypi
[conda] torch                     1.13.0.dev20220529          pypi_0    pypi
[conda] torchvision               0.14.0a0+f0f8a3c          pypi_0    pypi
```

**Comment by malfet** [comment]
Very likely the problem stems from `pytorch`/`torchvision` nightly builds incompatibility. 
At least I can not reproduce the problem on my M1 machine running following simple script:
```
% conda list|grep torch
torch                     1.13.0.dev20220601          pypi_0    pypi
torchvision               0.14.0.dev20220601          pypi_0    pypi
(py39-test) malfet@Nikitas-Mac-mini ~ % python
Python 3.9.12 (main, Apr  5 2022, 01:52:34) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
import>>> import torchvision
>>> resnet50 = torchvision.models.resnet50().to("mps")
>>> out=resnet50.forward(torch.rand(32, 3, 224, 224, device="mps"))
>>> out.device
device(type='mps', index=0)
>>> out.shape
torch.Size([32, 1000])
```

**Comment by sidroopdaska** [comment]
Any updates on this issue? I'm still observing it for the following versions
```
torch                     1.13.0.dev20220719          pypi_0    pypi
torchaudio                0.14.0.dev20220603          pypi_0    pypi
torchvision               0.14.0.dev20220719          pypi_0    pypi
```
The `PYTORCH_ENABLE_MPS_FALLBACK=1` doesn't work either.

**Comment by nihadtp** [comment]
Is this issue being worked on or Is there a way around?

**Comment by juceyj** [comment]
same problem.

`PyTorch version: 1.13.0.dev20220605
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0rc2
[pip3] torch==1.13.0.dev20220605
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchvision==0.14.0a0+f9f721d
[conda] numpy                     1.23.0rc2                pypi_0    pypi
[conda] torch                     1.13.0.dev20220605          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20220603          pypi_0    pypi
[conda] torchvision               0.14.0a0+f9f721d          pypi_0    pypi`

**Comment by kulinseth** [comment]
@malfet , there are lot of issues error'ing out with the same error message. Do we have a general solution to address these ?

**Comment by Ksyer** [comment]
Same issue here. Here is my environements

```
(torch-nightly) ➜  ~ python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14)  [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchfile==0.1.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.22.3           py39h64940a9_2    conda-forge
[conda] torch                     1.12.0.dev20220518          pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
```

**Comment by helgadnestr** [comment]
In my case, I had the same issue because I noted 'mps' in the nn, but I forgot note 'mps' in the input.

**Comment by helgadnestr** [comment]
In my case, I had the same error because I noted 'mps' in the nn, but I didn't note 'mps' in the input.

**Comment by kulinseth** [comment]
@Ksyer , were you able to fix the issue? The env is using fairly old torch. Can you try with latest nightly on torch and torchvision. This can also happen due to mismatch between those libraries. 

cc. @malfet , how can we resolve this issue ?

**Comment by bluch** [comment]
Having the same issue:

```
pytorch                   1.13.0.dev20220916        py3.10_0    pytorch-nightly
torchaudio                0.13.0.dev20220916       py310_cpu    pytorch-nightly
torchvision               0.14.0.dev20220916       py310_cpu    pytorch-nightly
```

CPU fallback using `PYTORCH_ENABLE_MPS_FALLBACK=1` not working

The operator 'aten::_slow_conv2d_forward' is not currently implemented for the MPS device.

**Comment by malfet** [comment]
Would greatly appreciate if somebody can post a minimal reproducer, as the one I've posted few month ago still works

**Comment by malfet** [comment]
An even simpler repro:
```
% python -c "import torch;print(torch.conv2d(torch.rand(1, 3, 88, 88), torch.rand(64, 3, 7, 7, device='mps')).sum())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NotImplementedError: The operator 'aten::_slow_conv2d_forward' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.```
