### ISSUE TITLE
Doc bug about torch.linalg.inv

### ISSUE THREAD

**Issue by zhongshsh** [pytorch/pytorch#77954]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.linalg.inv.html

In Examples, line 7 ends with an extra bracket. 
```python
A = torch.randn(4, 4)
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4))

A = torch.randn(2, 3, 4, 4)  # Batch of matrices
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4)))

A = torch.randn(4, 4, dtype=torch.complex128)  # Complex matrix
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4))
```

### Suggest a potential alternative/fix

```python
A = torch.randn(4, 4)
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4))

A = torch.randn(2, 3, 4, 4)  # Batch of matrices
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4))

A = torch.randn(4, 4, dtype=torch.complex128)  # Complex matrix
Ainv = torch.linalg.inv(A)
torch.dist(A @ Ainv, torch.eye(4))
```

cc @svekars @holly1238 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
Yup. We'd accept a fix for this.
Even more, the linalg docs (or all docs for the matter) could do with a sanitiser, starting checking that open and closing parents agree.

**Comment by zhongshsh** [comment]
In addition, There are some mistakes in the details.

In `pytorch/aten/src/ATen/native/LinearAlgebraUtils.h`, 
```c++
// Validates input shapes for operations on batches of square matrices (inverse, cholesky, symeig, eig)
static inline void squareCheckInputs(const Tensor& self, const char* const f_name) {
  TORCH_CHECK(self.dim() >= 2, f_name, ": The input tensor must have at least 2 dimensions.");
  TORCH_CHECK(self.size(-1) == self.size(-2),
              f_name,
              ": A must be batches of square matrices, "
              "but they are ", self.size(-1), " by ", self.size(-2), " matrices");
}
```
And in `pytorch/torch/_meta_registrations.py`, 
```python
def squareCheckInputs(self, f_name):
    assert self.dim() >= 2, f"{f_name}: The input tensor must have at least 2 dimensions."
    # TODO: I think the error message has the -2 and -1 swapped.  If you fix
    # it fix the C++ squareCheckInputs too
    assert self.size(-1) == self.size(-2), \
        f"{f_name}: A must be batches of square matrices, but they are {self.size(-1)} by {self.size(-2)} matrices"
```
Maybe they should be {self.size(-2)} by {self.size(-1)}.

**Comment by zhongshsh** [comment]
Thanks for your reply. If you want to fix `linalg.inv`, maybe [this PR](https://github.com/Oneflow-Inc/oneflow/pull/8183/) will give your some ideas.

**Comment by Lezcano** [comment]
We will implement `torch.linalg.inv(A)` as `torch.solve(A, torch.eye(A.size(-1), device=A.device()))` pretty much.

**Comment by zhongshsh** [comment]
I tested this method, and it didn't solve the original problem.

```python
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> A = torch.tensor([[4.1, 2.8], [9.676, 6.608]])
>>> Ainv, LU = torch.solve(torch.eye(A.size(-1), device=A.device), A)
>>> Ainv
tensor([[ 22473374.,  -9522616.],
        [-32907440.,  13943831.]])
>>> torch.dist(A @ Ainv, torch.eye(A.size(-1)))
tensor(4.2426)
```

**Comment by Lezcano** [comment]
We don't aim to solve the original problem, as we don't implement the backends for these functions. Note that detecting whether a matrix is singular is a very difficult problem because we don't work with exact precision. If you do care about these things in your application, you should make sure that the matrix that you pass the solver (`linalg.solve` or `linalg.inv`) is well-conditioned.

That being said, we could update the docs to be a bit less explicit about what happens when the matrix is almost singular.

**Comment by zhongshsh** [comment]
OK, I get the message.

**Comment by Lezcano** [comment]
Fixed in master in https://github.com/pytorch/pytorch/pull/77079
