### ISSUE TITLE
MPS not implemented for aten::index.Tensor

### ISSUE THREAD

**Issue by inspirit** [pytorch/pytorch#77959]
### 🐛 Describe the bug

executing following line:
`y.transpose(0, 1)[torch.arange(y.shape[1]), indices]`
NotImplementedError: Could not run 'aten::index.Tensor' with arguments from the 'MPS' backend.

### Versions

PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.12 (main, Mar 26 2022, 15:44:31) [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

**Comment by johnnynunez** [comment]
I have the same error:
UserWarning: The operator 'aten::index.Tensor' is not currently supported on the MPS backend and will fall back to run
on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  output, target = output[:, :, ..., dimensions_idces], target[:, :, ..., dimensions_idces]

**Comment by kulinseth** [comment]
Fixed in latest nightly.
