### ISSUE TITLE
Exporting the operator isinstance to ONNX opset version 13 is not supported

### ISSUE THREAD

**Issue by YoannPitarch** [pytorch/pytorch#77961]
### 🚀 The feature, motivation and pitch

Is it possible to add support for the operator `isinstance` in the ONNX opset please?
I cannot see any workaround to deal with my problem.
Thanks

**Comment by justinchuby** [comment]
Could you share the problem you are trying to solve?

**Comment by YoannPitarch** [comment]
I am trying to convert the model described [there](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/pointnet2_segmentation.py) to ONNX. This model uses the torch geometric package. I've managed to register some "torch geometric" operators (`fps` and `radius`) but I am now getting an error related to the `isinstance` operator.

**Comment by hgaiser** [comment]
I'm trying to do something similar:

```python
from typing import Union, List
import torch

class SomeModel(torch.nn.Module):
	def forward(self, x: Union[List[torch.Tensor], torch.Tensor]) -> torch.Tensor:
		if isinstance(x, torch.Tensor):
			return x
		else:
			return x[0]

model = SomeModel()
model = torch.jit.script(model)

dummy_input = torch.randn((3, 224, 224))
torch.onnx.export(model, dummy_input, 'test.onnx')
```

Which gives the following error:

```
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator prim::isinstance to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by hgaiser** [comment]
I was afraid that'd be the answer :) thanks.

**Comment by hgaiser** [comment]
> Is instance is a python specific operation that is not supported by ONNX. I suggest tracing the model or refactoring the logic such that the input types are always the same.

Do you happen to know why this operation works in TorchScript? To my understanding, it is not executing TorchScript using a Python interpreter. Has it been implemented for TorchScript, but not for ONNX?
