### ISSUE TITLE
CPU fallback for `aten::index.Tensor` on MPS crashes or gives wrong result

### ISSUE THREAD

**Issue by lhoenig** [pytorch/pytorch#77977]
### 🐛 Describe the bug

Built `main` @ 734a97a7c8. Activating the CPU fallback using `PYTORCH_ENABLE_MPS_FALLBACK=1` to use `aten::index.Tensor` on MPS works but still crashes for a simple indexing. For mask and tensor sizes 1 and 2, it doesn't crash but return an empty tensor. Minimal example:
```python
import torch as pt

x = pt.ones(3, device='mps')  # sizes 1 and 2 work, but result is empty tensor
m = pt.ones_like(x).bool()  # pt.zeros_like works
x[m]  # crash
```
Output:
```
$ PYTORCH_ENABLE_MPS_FALLBACK=1 python3 bug1.py
/Users/lukas/bug1.py:5: UserWarning: The operator 'aten::index.Tensor' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/lukas/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  x[m]  # crash
Traceback (most recent call last):
  File "/Users/lukas/bug1.py", line 5, in <module>
    x[m]  # crash
RuntimeError: out_ptr == out_accessor[thread_count_nonzero[tid + 1]].data() INTERNAL ASSERT FAILED at "/Users/lukas/pytorch/aten/src/ATen/native/TensorAdvancedIndexing.cpp":2038, please report a bug to PyTorch.
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.0a0+git734a97a
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.9.12 (main, May  8 2022, 17:57:49)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.0
[pip3] torch==1.12.0a0+git734a97a
[pip3] torch-scatter==2.0.9
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect
```

**Comment by johnnynunez** [comment]
UserWarning: The operator 'aten::index.Tensor' is not currently supported on the MPS backend and will fall back to run
on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  output, target = output[:, :, ..., dimensions_idces], target[:, :, ..., dimensions_idces]

**Comment by dbl001** [comment]
Same issue in torch==1.13.0a0+gitcaa6ef1
```
   return grad[:, s].detach()
NotImplementedError: The operator 'aten::index.Tensor_out' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```
Environment
```
% python collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.12 (main, Jun  1 2022, 06:36:29)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.13.0a0+gitcaa6ef1
[pip3] torchvision==0.2.2.post3
[conda] blas                      1.0                         mkl    anaconda
[conda] mkl                       2021.4.0           hecd8cb5_637    anaconda
[conda] mkl-include               2022.0.0           hecd8cb5_105    anaconda
[conda] mkl-service               2.4.0            py39h9ed2024_0    anaconda
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0    anaconda
[conda] mkl_random                1.2.2            py39hb2f4e1b_0    anaconda
[conda] numpy                     1.22.3           py39h2e5f0a9_0    anaconda
[conda] numpy-base                1.22.3           py39h3b1a694_0    anaconda
[conda] pytorch                   1.12.0                  py3.9_0    pytorch
[conda] torch                     1.13.0a0+git5af4858          pypi_0    pypi
[conda] torchvision               0.2.2.post3              pypi_0    pypi
```

**Comment by kulinseth** [comment]
@lhoenig , the `index.Tensor_out` is implemented on MPS backend. Please check with the latest nightly.

**Comment by carloszimmer149** [comment]
$ python visualizer_drag_gradio.py
File under cache_dir (./checkpoints):
['stylegan2-afhqcat-512x512.pkl', 'stylegan2-car-config-f.pkl', 'stylegan2-cat-config-f.pkl', 'stylegan2-ffhq-512x512.pkl', 'stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_elephants_512_pytorch.pkl', 'stylegan2_horses_256_pytorch.pkl', 'stylegan2_lions_512_pytorch.pkl']
Valid checkpoint file:
{'stylegan2-afhqcat-512x512': './checkpoints\\stylegan2-afhqcat-512x512.pkl', 'stylegan2-car-config-f': './checkpoints\\stylegan2-car-config-f.pkl', 'stylegan2-cat-config-f': './checkpoints\\stylegan2-cat-config-f.pkl', 'stylegan2-ffhq-512x512': './checkpoints\\stylegan2-ffhq-512x512.pkl', 'stylegan2_dogs_1024_pytorch': './checkpoints\\stylegan2_dogs_1024_pytorch.pkl', 'stylegan2_elephants_512_pytorch': './checkpoints\\stylegan2_elephants_512_pytorch.pkl', 'stylegan2_horses_256_pytorch': './checkpoints\\stylegan2_horses_256_pytorch.pkl', 'stylegan2_lions_512_pytorch': './checkpoints\\stylegan2_lions_512_pytorch.pkl'}
Loading "./checkpoints\stylegan2_lions_512_pytorch.pkl"... Done.
()
{'z_dim': 512, 'c_dim': 0, 'w_dim': 512, 'img_resolution': 512, 'img_channels': 3, 'mapping_kwargs': {'num_layers': 8, 'embed_features': None, 'layer_features': None, 'activation': 'lrelu', 'lr_multiplier': 
0.01, 'w_avg_beta': 0.995}, 'synthesis_kwargs': {'channel_base': 32768, 'channel_max': 512, 'num_fp16_res': 0, 'conv_clamp': None, 'architecture': 'skip', 'resample_filter': [1, 3, 3, 1], 'use_noise': True, 
'activation': 'lrelu'}}
Traceback (most recent call last):
  File "C:\DragGAN\visualizer_drag_gradio.py", line 205, in <module>
    global_state = init_images(global_state)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DragGAN\visualizer_drag_gradio.py", line 96, in init_images
    add_watermark_np(np.array(init_image)))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\DragGAN\viz\renderer.py", line 56, in add_watermark_np
    text_width, text_height = font.getsize(watermark_text)
                              ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
