### ISSUE TITLE
DISABLED test_Conv2d_groups_nobias (__main__.TestNN)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#77976]
Platforms: rocm

This test was disabled because it is failing flakily ([recent examples](http://torch-ci.com/failure/test_Conv2d_groups_nobias%2C%20TestNN)).

**Comment by jeffdaily** [comment]
https://github.com/pytorch/pytorch/pull/77438 should fix various flaky Conv tests.

**Comment by jeffdaily** [comment]
Fixed by #77438.
