### ISSUE TITLE
CosineAnnealingLR: LR stuck at 0 after re-initializing scheduler

### ISSUE THREAD

**Issue by djc26** [pytorch/pytorch#78003]
### 🐛 Describe the bug

Using torch.optim.lr_scheduler.CosineAnnealingLR seems to result in different behavior between torch 1.8.1+cu111 and 1.10.2+cu113. I am using the following code to achieve warm restarts:

The scheduler is initialized 
```
 self.scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(self.optimizer, \
                                len(self.train_loader)*self.t, last_epoch=-1)
```

and periodically re-initialized to acheive warm restarts
```
            # Perform a restart if we're using cosine annealing and we've reach t epochs
            if self.pack["lr_scheduler"] == "ca" and epoch == self.t+self.epoch_period_sum:

                # epoch_period_sum = only increased here
                # self.t is initizliaed accroding to the train pack t_init
                self.epoch_period_sum += self.t
                self.t *= self.t_mult

                self.scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(self.optimizer, \
                                 len(self.train_loader)*self.t, last_epoch=-1)
```

In torch 1.8.1 the behavior is as expected
![Screenshot from 2022-05-20 13-16-00](https://user-images.githubusercontent.com/95946857/169605606-b8404071-7f12-43f8-87b0-7b6b8855f7e5.png)

However in 1.10.2 the learning rate becomes stuck at 0 after the scheduler is re-initialized for the warm restart.
![Screenshot from 2022-05-20 12-56-33](https://user-images.githubusercontent.com/95946857/169605683-bfb40b18-1ef4-49f6-8df6-8b616ee76134.png)

If I do not re-initialize the scheduler I get a continuous sine wave as expected. I have tried deleting the schedule before re-initializing, but this did not change the behavior.

### Versions

The two environments are as follows, both using Python 3.6.9

[pip3] torch==1.8.1+cu111
[pip3] efficientnet-pytorch==0.7.0
[pip3] numpy==1.19.5
[pip3] torchaudio==0.8.1
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.9.1+cu111

[pip3] torch==1.10.2+cu113
[pip3] efficientnet-pytorch==0.7.0
[pip3] numpy==1.19.5
[pip3] torchaudio==0.10.2+cu113
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.3+cu113

cc @ezyang @gchanan @zou3519

**Comment by vadimkantorov** [comment]
Probably because scheduler adds some state to optimizer's param groups? :( It would be easier to work around this if schedulers were also available as free functions: https://github.com/pytorch/pytorch/issues/68332

**Comment by jbschlosser** [comment]
Hey @djc26, if possible, you could please provide a small, self-contained example demonstrating the issue? I'm having trouble reproducing it as-is.

Side note: would using [`CosineAnnealingWarmResarts`](https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingWarmRestarts.html) instead be useful for you?

**Comment by djc26** [comment]
Thank you for working to re-produce the issue! I'll admit I did not create a self-contained example, but instead wrote my own stateless function to unblock my work. Let me try CosineAnnealingWarmResarts since this is my desired behavior.

**Comment by djc26** [comment]
@jbschlosser CosineAnnealingWarmResarts creates the correct learning rate schedule, but does does not allow the scheduler to specify a last_epoch with a new optimizer, ie.

KeyError: “param ‘initial_lr’ is not specified in param_groups[0] when resuming an optimizer”

I understand this is a design choice that I am choosing not to follow so I will close this issue. As others have said, making the scheduler a stateless function would make it usable beyond the basic workflow imagined by the developers.

**Comment by vadimkantorov** [comment]
@djc26 please upvote https://github.com/pytorch/pytorch/issues/68332 since you seem to support basic stateless functional design :)
