### ISSUE TITLE
CUDA streams in ATen

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#7800]
To juggle CUDA streams from C++ I need to call `THCState_getCurrentStreamOnDevice` and friends. It would be nice to have an ATen wrapper for this to not have to include files from `TH*`.

The ATen include tree doesn't expose anything CUDA specific though, so some discussion is warranted before adding a wrapper. What would be the right place such a wrapper?

@ezyang @goldsborough @zdevito

**Comment by apaszke** [comment]
There's a`getTHCState()` function on the ATen Context, so my guess is that it would live somewhere near that.

**Comment by c-hofer** [comment]
Hi guys, I'm also interested in this feature as I'm currently implementing some complex algorithm to be integrated into pytorch with a ATen backend. Stream-based parallelism is one option to get batch functionality. 

It's maybe misplaced here, but do u have any advice where i can get some insight to do this on ATen level? Without any knowledge of the code base it's kind of tough ;) cheers c

**Comment by ezyang** [comment]
@c-hofer Start by writing a tiny wrapper function in your code for `THCState_getCurrentStreamOnDevice` and test it works. Then we can figure out where in the API it makes sense to put.

**Comment by c-hofer** [comment]
@ezyang @pietern ... i've studied the source now a little and as u pointed out messing around with THCState seems the solution. However, how do I get the right THCState in my hands? 

```
#include <torch/torch.h>

using namespace at;

Tensor foo(Tensor t)
{
  auto p_thc_state = globalContext().getTHCState();
 //do something like changing stream and manipulating t ...

  return t
}
```

However, `globalContext()` yields a strange error during compilation:

> /home/pma/chofer/repositories/chofer_torchex/chofer_torchex/pershom/pershom_cpp_src/pershom.cpp:80:26: error: use of deleted function ‘at::Context::Context(const at::Context&)’
>    auto c = globalContext();
>                           ^
> In file included from /scratch2/chofer/opt/anaconda3/envs/pytorch_0_4/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:9:0,
>                  from /scratch2/chofer/opt/anaconda3/envs/pytorch_0_4/lib/python3.6/site-packages/torch/lib/include/torch/torch.h:5,
>                  from /home/pma/chofer/repositories/chofer_torchex/chofer_torchex/pershom/pershom_cpp_src/pershom.cpp:1:
> /scratch2/chofer/opt/anaconda3/envs/pytorch_0_4/lib/python3.6/site-packages/torch/lib/include/ATen/Context.h:23:14: note: ‘at::Context::Context(const at::Context&)’ is implicitly deleted because the default definition would be ill-formed:
> 
> class AT_API Context {
> 
> ...


Maybe I missed something or totally misinterpreted the role of globalContext()? 
Or is there another proper way to get hands on the current THCState struct I overlooked?

help is appreciated :) cheers

**Comment by ezyang** [comment]
Yes it is correct.

**Comment by soulslicer** [comment]
Is there any example code out there to show how to do say..torch::mm and let me pass in a stream?
