### ISSUE TITLE
Error occurred , when compile source code setting  BUILD_CAFFE2=ON

### ISSUE THREAD

**Issue by f291400** [pytorch/pytorch#78034]
### 🐛 Describe the bug

compile source code failed
# compile command:
TORCH_CUDA_ARCH_LIST="7.5" ONNX_NAMESPACE="torch_tmp" USE_NUMPY=0 USE_DISTRIBUTED=OFF USE_NCCL=OFF _GLIBCXX_USE_CXX11_ABI=0 REL_WITH_DEB_INFO=1 BUILD_CAFFE2=ON python setup.py install

## error print
<img width="1529" alt="image" src="https://user-images.githubusercontent.com/13358476/169635520-26b97a21-23e3-40f7-80bc-967f85d3049a.png">
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/13358476/169635531-74175742-2b89-4245-be63-c43ebebc9ade.png">

## envs:
---------------------- -------------------
astunparse             1.6.3
brotlipy               0.7.0
certifi                2021.10.8
cffi                   1.15.0
charset-normalizer     2.0.4
conda                  4.12.0
conda-package-handling 1.8.1
cryptography           37.0.1
future                 0.18.2
idna                   3.3
mkl-fft                1.3.1
mkl-random             1.2.2
mkl-service            2.4.0
numpy                  1.21.5
pip                    21.2.4
pycosat                0.6.3
pycparser              2.21
pyOpenSSL              22.0.0
PySocks                1.7.1
PyYAML                 6.0
requests               2.27.1
ruamel-yaml-conda      0.15.100
setuptools             61.2.0
six                    1.16.0
torch                  1.11.0a0+gitbc2c6ed
tqdm                   4.64.0
typing_extensions      4.1.1
urllib3                1.26.9
wheel                  0.37.1

cc @malfet @seemethere

**Comment by lazybuttrying** [comment]
How about  not BUILD_CAFFE2=ON but BUILD_CAFFE2=1?
I got error, in that message, it said "BUILD_CAFFE2=1"
`Please enable Caffe2 by building PyTorch from source with `BUILD_CAFFE2=1` flag.
  warnings.warn("Caffe2 support is not fully enabled in this PyTorch build. "`
