### ISSUE TITLE
[primTorch] many primTorch test xfails are due to chalf

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#78054]
We should fix these issues or stop testing the references in chalf for now -- it's an outsized developer efficiency issue

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @ngimel

**Comment by kshitij12345** [comment]
I think it should be disabled for now. Even for `torch` ops, it is opt-in at this point as the op coverage is still low.

**Comment by mruberry** [comment]
Should be addressed by https://github.com/pytorch/pytorch/pull/78026
