### ISSUE TITLE
pytorchbot rebase doesn't work for forked PRs

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#78095]
If a pull request was made from a forked repo, it appears that the rebase command will fail, see: https://github.com/pytorch/pytorch/pull/77438#issuecomment-1134868780

**Comment by clee2000** [comment]
i cant seem to replicate this on my forked pr https://github.com/pytorch/pytorch/pull/78096, so i asked @jeffdaily about it.  He says it's likely to be a permissions thing related specifically to the ROCmSoftwarePlatform org as it has 2fa and an allow list and that they are ok with not being able to use rebase bot and will rebase manually if needed.

If this error shows up again, reopen issue and pls let me know

**Comment by suo** [comment]
sounds good, thanks!
