### ISSUE TITLE
Bazel build is very flaky

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#78100]
Failures occur when fetching dependencies. Some examples over the past week:

- https://github.com/pytorch/pytorch/runs/6558537849?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/6540971273?check_suite_focus=true

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
@kit1980 @linbinyu @dagitses are the maintainers perhaps, would you take a look at this?

**Comment by suo** [comment]
@dagitses do you mind taking a look?

**Comment by malfet** [comment]
Should we cache those dependencies in docker? @suo can we get a bit more quantifiable metric how often bazel builds fail compared to others?

**Comment by dagitses** [comment]
Yeah, it's generally considered a great idea to ensure that we don't have to go out to the remote world to fetch dependencies in CI. How do you implement this cache generally? We also want to make sure that it continues to work for people who are building from workstations.
________________________________

**Comment by suo** [comment]
Another example https://github.com/pytorch/pytorch/runs/6597411757?check_suite_focus=true

**Comment by suo** [comment]
> @suo can we get a bit more quantifiable metric how often bazel builds fail compared to others?

It's tricky unfortunately, the data is extremely noisy as we have failures all the time on master for other reasons. My recently introduced manual classification should help things, so in a few weeks we should have good numbers.

**Comment by kit1980** [comment]
> Another example https://github.com/pytorch/pytorch/runs/6597411757?check_suite_focus=true

That's a different workflow, not related to Bazel build.
Github had intermittent issues today from time to time, that's why the download from Github failed. But even if we cache it, something else from Github would probably fail anyway.

**Comment by janeyx99** [comment]
We should install these into our Docker containers so we aren't trying to download these dependencies every time.

**Comment by malfet** [comment]
Our docker build definitions are in https://github.com/pytorch/pytorch/tree/master/.circleci/docker

**Comment by janeyx99** [comment]
@kit1980 observed that this build has not been flaky recently, so this can be closed for now + reopen if this is not the case.
