### ISSUE TITLE
[MPS] The value comparison result of tensor on mps device is incorrect 

### ISSUE THREAD

**Issue by WuChengbin** [pytorch/pytorch#78107]
### 🐛 Describe the bug

import torch
a = torch.tensor([8.2670e-01,-1.0293e+00])
b = a[0]
c = a[1]
b= b.to('mps')
c = c.to('mps')
print(b>c)  # tensor(True, device='mps:0')
print(c>b)  # tensor(True, device='mps:0') 

### Versions

Collecting environment information...
PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14) [Clang 12.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220518
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] numpy 1.22.3 py39h64940a9_2 conda-forge
[conda] torch 1.12.0.dev20220518 pypi_0 pypi
[conda] torchaudio 0.11.0 pypi_0 pypi
[conda] torchvision 0.12.0 pypi_0 pypi

**Comment by thipokKub** [comment]
possible duplicate https://github.com/pytorch/pytorch/issues/77750
