### ISSUE TITLE
[Feature Request] Modified Bessel Function of Order 0....Cuda Implementation

### ISSUE THREAD

**Issue by ishan193** [pytorch/pytorch#7815]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment]
@ishan193 for context, what would this be used for?

**Comment by fermat97** [comment]
Did you figure it out how to implement the modified Bessel of any order on Cuda. I need it to compute the KL-divergence of two von Mises-Fisher distribution. Right now I think I can do it with `scipy` but it is not on GPU.

**Comment by cmpute** [comment]
FYI, I ported modified bessel function of order 0 and 1 to pytorch, you can find it here: https://github.com/cmpute/d3d/tree/master/d3d/math
