### ISSUE TITLE
[GHA] [CI] Strengthening Rockset Test Reporting Dependencies

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#78175]
We currently upload test case runs to Rockset in hopes of storing these stats in a queryable, externally viewable dataset compared to our current S3 solution (see https://github.com/pytorch/pytorch/issues/62136). Since these test stats will become important for our flaky test detection as well as our sharding logic, we need to solidify our test report uploading.

We should address the following issues
- [x] https://github.com/pytorch/pytorch/issues/78138
- [x] I recently noticed that https://github.com/pytorch/pytorch/runs/6563936156 didn't make it to the test_run collection even though the artifacts were correctly uploaded. After investigating, I noticed that the workflow was marked "cancelled" (see https://api.github.com/repos/pytorch/pytorch/actions/runs/2374099866/attempts/1) even though a majority of the tests already ran. We currently bar our upload-test-stats step on failed and succeeded, but we should either broaden this or ask GitHub to change how their workflows get reported (one of these is easier than the other)
- [x] Solidify the upload test artifacts job (We have a heavy dependency on the upload test artifacts job. If the test reports never make it to S3, we cannot download and resubmit them to Rockset.)
    - [ ] Add retries if possible
  
ccing @suo 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
Closing as I think we have resolved all known issues.
