### ISSUE TITLE
torch.jit.script gives a RuntimeError for a custom MaskRCNN model

### ISSUE THREAD

**Issue by vinitveersingh** [pytorch/pytorch#78188]
### 🐛 Describe the bug

We complied a MaskRCNN model shown in [TORCHVISION OBJECT DETECTION FINETUNING TUTORIAL] (https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) with torch.jit.script. They define the model as mentioned below:
```python
def get_model_instance_segmentation(num_classes):
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask,
                                                       hidden_layer,
                                                       num_classes)
    return model
```
torch.jit.script works perfectly for this example. Please find the Google Colab notebook link for the working example [here](https://colab.research.google.com/drive/1eMX93n5UfFS-qYujx_pADv3sSajViEtg?usp=sharing).

We then wrapped the "get_model_instance_segmentation()" function inside a nn.Module class as shown below:
```python
class CustomModel(nn.Module):
    def __init__(self, num_classes=2):
        super(CustomModel, self).__init__()
        self.model = get_instance_segmentation_model(num_classes)

    def forward(self, images, targets=None):
        if targets is not None:
            out = self.model(images, targets)
        else:
            out = self.model(images)
        return out
```

The CustomModel trains and tests correctly. However, it fails when we try to compile it with the torch.jit.script. The runtime error is as follows:
```
forward(__torch__.torchvision.models.detection.mask_rcnn.MaskRCNN` self, Tensor[] images, Dict(str, Tensor)[]? targets=None) -> ((Dict(str, Tensor), Dict(str, Tensor)[])):
Expected a value of type 'List[Tensor]' for argument 'images' but instead found type 'Tensor (inferred)'.
Inferred the value for argument 'images' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "<ipython-input-30-4dfa4e1ed5e5>", line 10
    def forward(self, images, targets=None):
        if targets is not None:
            out = self.model(images, targets)
                  ~~~~~~~~~~ <--- HERE
        else:
            print('target', targets)
```

The link to the Google Colab notebook when CustomModel fails compilation is [here](https://colab.research.google.com/drive/1pczhp1YIHcnj0OEkhbAVxa82VZscw_f8?usp=sharing).

Both notebooks only contain the minimum required code.

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.4
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

**Comment by davidberard98** [comment]
Can you annotate the type of `images` in the forward method?

```python
from typing import List
...
    def forward(self, images: List[torch.Tensor], targets=None):
```

The error message suggests that `self.model(..)` expects an argument that is a list of tensors. Since `images` is not annotated, torchscript assumes that it is a tensor. If it's not a tensor, it needs to be annotated as a tensor.

**Comment by vinitveersingh** [comment]
Thank you. It works.

**Comment by fader111** [comment]
Why didn't you use detectron2 instead torchvision?
