### ISSUE TITLE
Problem running TorchScript models with batch normalization from old versions

### ISSUE THREAD

**Issue by shpotes** [pytorch/pytorch#78207]
### 🐛 Describe the bug

When saving a model using Torchscript in an old version of torch, i.e., 1.4, it's loaded in a newer version, i.e., 1.10.1; and trying to run it using GPU, the following error appears

```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument running_mean in method wrapper__cudnn_batch_norm)
```

This behavior is associated with batch norm, because in the trace it appears
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/nn/modules/module/___torch_mangle_54.py", line 11, in forward
    input: Tensor) -> Tensor:
    _0 = self.classifier
    _1 = (self.avgpool).forward((self.features).forward(input, ), )
                                 ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    input0 = torch.flatten(_1, 1, -1)
    return (_0).forward(input0, )
  File "code/__torch__/torch/nn/modules/module/___torch_mangle_44.py", line 54, in forward
    _1 = (getattr(self, "0")).forward(input, )
    _2 = getattr(self, "3")
    _3 = (getattr(self, "2")).forward((_0).forward(_1, ), )
                                       ~~~~~~~~~~~ <--- HERE
    _4 = getattr(self, "5")
    _5 = (getattr(self, "4")).forward((_2).forward(_3, ), )
  File "code/__torch__/torch/nn/modules/module/___torch_mangle_1.py", line 15, in forward
    _1 = self.running_mean
    _2 = self.bias
    input = torch.batch_norm(argument_1, self.weight, _2, _1, _0, False, 0.10000000000000001, 1.0000000000000001e-05, True)
            ~~~~~~~~~~~~~~~~ <--- HERE
    return input
```

In [this notebook](https://colab.research.google.com/drive/1-rQrbTKWk6xzfixQuzYvy9XLkiDpJU_T?usp=sharing) it is possible to replicate the issue

### Versions

PyTorch version: 1.10.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.4
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.10.1+cu102
[pip3] torchaudio==0.11.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.12.0
[pip3] torchvision==0.5.0
[conda] Could not collect

**Comment by davidberard98** [comment]
Are you sure this works in 1.4 as well? 

e.g. could you duplicate this code into the end of the pytorch 1.4 section and see if it errors out?

```python
model = torch.jit.load("sample.pt")
model.eval()
model.cuda()

sample_tensor = torch.randn(1, 3, 244, 244)

model(sample_tensor.cuda())
```

**Comment by shpotes** [comment]
> 

yes, it works on torch 1.4, and in fact, it also works on torch LTS (1.8.2). I updated the notebook with both examples

**Comment by charlielito** [comment]
Same problem here, any update?

**Comment by nmerrill67** [comment]
Hi I had the same problem, but using 
```
model = torch.jit.load('/path/to/torchscript/model.pt', map_location=torch.device('cuda:0'))
```
fixed it

**Comment by charlielito** [comment]
> map_location=torch.device('cuda:0')

`map_location` is not an argument supported in pytorch 1.4

**Comment by charlielito** [comment]
I confirm that fixes it. @shpotes you could close the issue :3
