### ISSUE TITLE
Deprecate `TSNodeLoweringInterface`

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#78206]
### 🚀 The feature, motivation and pitch

As a follow up to #76535, I'd like to propose a change that would effectively remove the need for `TSNodeLoweringInterface`.

Right now, there is a function called `LowerNonCodegenOps` which dispatches the `lower` function depending on the op type. However, I don't think there is any need to do this. By declaring
```c++
TSOpVector Lower(std::shared_ptr<torch::jit::GraphFunction> function,
                 TSLoweringContext* loctx) const override;
```
for those IR nodes (which is very easily done now that they are being codegen'd), we can implement those lowering functions inside `ts_node_lowerings.cpp`. This would remove the need to cast and dispatch those nodes in the `LowerNonCodegenOps` function which effectively means that we could deprecate `TSNodeLoweringInterface` altogether.

@wconstab @desertfire Thoughts?

cc @bdhirsh

**Comment by wconstab** [comment]
Ok, yea i had wanted to do this too.  But I think @JackCaoG may have concerns with it at least in the short term?  It depends how they do the XLA migration.  Is it a change that would only affect the TS backend?  or it affects how the core code calls into the backends?

**Comment by antoniojkim** [comment]
This is a per-backend thing. So, the changes I'm proposing here will only affect the TS backend. I'll also be changing the MLIR backend soon after to match.

I think if the XLA backend still needs it they can keep it if they need to. I don't think they would have been directly using `TSNodeLoweringInterface` or inheriting it from it, so it shouldn't be a problem. @JackCaoG please confirm.

**Comment by JackCaoG** [comment]
XLA does not use `TSNodeLoweringInterface` since every node has a Lower function. I think we can clean this up if it is not needed for TS.
