### ISSUE TITLE
pytorchbot revert reason validation is confusing

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#78242]
I tried a few here: https://github.com/pytorch/pytorch/pull/78146 but none of them seemed to work. I've reverted other PRs today with `-c nosignal` and that seemed fine.

**Comment by suo** [comment]
Looking at the code, seems like my stuff probably failed a validity check
```
    // Valid reason contains 3+ word
    function isReasonValid(reason: string) {
      return reason.split(" ").filter((x) => x.trim().length > 1).length >= 3;
    }
```

Two comments here:
1. The validity check feel arbitrary; there is no way to predict what it is without looking at the code. We should probably remove it, since the CLI enforces that a *some* reason is required anyway.
2. The comment that the bot gives in response is misleading/confusing. It says that I didn't provide a revert reason, whereas in reality it failed because it didn't like the reason I gave. We should probably improve that (or just delete the branch altogether, per item 1)

**Comment by malfet** [comment]
Agreed, it needs a cleaner error message, but I think we should enforce revert reason to be at least few words long. 

Imo "breaks master" is bad, as it does not include a link to workflow that were broken, "breaks master https://github.com/pytorch/pytorch/runs/NUMBER" is a much better one, as even several month later developer/community can still look at the run this workflow has failed

**Comment by suo** [comment]
sure seems reasonable

**Comment by suo** [comment]
This was confusing as well: reverting via phab breaks because the revert reason (which I don't know how to change) 
does not pass validation. https://github.com/pytorch/pytorch/pull/77941#issuecomment-1140364449

**Comment by malfet** [comment]
> This was confusing as well: reverting via phab breaks because the revert reason (which I don't know how to change) does not pass validation. [#77941 (comment)](https://github.com/pytorch/pytorch/pull/77941#issuecomment-1140364449)

@bigfootjon do you know where this comment is generated? Also, why revert were not propagated to fbsync?

**Comment by suo** [comment]
this thing is driving me totally crazy https://github.com/pytorch/pytorch/pull/69607#issuecomment-1142792632

**Comment by suo** [comment]
it appears that it doesn't like single quotes, it must be double quotes :<
