### ISSUE TITLE
Discrepancy in the dimension wrapping error message and type

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#78252]
### 🐛 Describe the bug

There's a discrepancy in the error message and error type in `torch._prims.utils.canonicalize_dim` and `at::maybe_wrap_dims_n` :
https://github.com/pytorch/pytorch/blob/87148f2b5921557774a535495d7c77b20aa795b6/torch/_prims/utils.py#L408-L410
https://github.com/pytorch/pytorch/blob/87148f2b5921557774a535495d7c77b20aa795b6/aten/src/ATen/WrapDimUtils.h#L48-L50
`canonicalize_dim` raises a `ValueError` while `at::maybe_wrap_dims_n` raises `IndexError`.

This prevents proper use of error inputs with OpInfo for some operations.

### Versions

On the latest main branch.

cc @ezyang @mruberry @ngimel

**Comment by ngimel** [comment]
would changing `canonicalize_dims` error to IndexError solve the issue, or will it break a bunch of other things? We should try to match the types of errors thrown.
