### ISSUE TITLE
Crash with ParameterList and device='meta'

### ISSUE THREAD

**Issue by fzimmermann89** [pytorch/pytorch#78250]
### 🐛 Crash with ParameterList and device='meta'

Hi,

while trying to debug https://github.com/pytorch/functorch/issues/832 I noticed an issue with ParameterList and meta tensors:
```python
import torch
p=torch.nn.Parameter(torch.empty(1,device='meta'))
print(p)
#Parameter containing:
#tensor(..., device='meta', size=(1,), requires_grad=True)
pl=torch.nn.ParameterList([p])
print(pl)
#terminate called without an active exception
#[1]    9276 abort (core dumped)  python
```

This might have a similar root cause as the issue mentioned above (which prevents make_functional of functorch to be used if the modulecontains a ParameterList). 

Expected result:
```Not crashing the interpreter.```

Have a great day,
Felix

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220524
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 450.119.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.3.0a0+76976db
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.6.3
[pip3] pytorch-msssim==0.2.1
[pip3] torch==1.13.0.dev20220524
[pip3] torchinfo==1.6.5
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.13.0.dev20220524
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.6.0              habf752d_10    conda-forge
[conda] functorch                 0.3.0a0+76976db          pypi_0    pypi
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py39h07f9747_2    conda-forge
[conda] mkl_fft                   1.3.0            py39h54f3939_0
[conda] mkl_random                1.0.2            py39h63df603_0
[conda] numpy                     1.19.2           py39h89c1606_0
[conda] numpy-base                1.19.2           py39h2ae0177_0
[conda] pytorch                   1.13.0.dev20220524 py3.9_cuda11.6_cudnn8.3.2_0    pytorch-nightly
[conda] pytorch-lightning         1.6.3              pyhd8ed1ab_0    conda-forge
[conda] pytorch-msssim            0.2.1                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchinfo                 1.6.5              pyhd8ed1ab_0    conda-forge
[conda] torchmetrics              0.7.3              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.13.0.dev20220524      py39_cu116    pytorch-nightly
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @ezyang @gchanan @zou3519

**Comment by ngimel** [comment]
High priority due to crash on basic functionality.
