### ISSUE TITLE
Python warnings printed repeatedly from JIT in libtorch

### ISSUE THREAD

**Issue by HennerM** [pytorch/pytorch#78251]
### 🐛 Describe the bug

I am using the C++ API (libTorch) with a JIT scripted model that was exported with PyTorch 1.11. In this version Pool1D (and Pool 2D) operations were throwing a warning: https://github.com/pytorch/pytorch/blob/v1.11.0/torch/nn/functional.py#L749-L750
```
warnings.warn("Note that order of the arguments: ceil_mode and return_indices will change"
                      "to match the args list in nn.MaxPool2d in a future release.")
```

I would expect this warning only to show up once in stderr, as part of the Model::forward. However, the warning is printed on every invocation.

The only workaround I found was to disable warnings entirely:

```
class NoopWarningHandler: public c10::WarningHandler {
  void process(const c10::SourceLocation& source_location,
      const std::string& msg,
      const bool verbatim) override {
        // do nothing
      }
};

NoopWarningHandler global_warning_handler;

void SetupTorch() {
  c10::Warning::set_warning_handler(&global_warning_handler);
}
```

### Versions

Collecting environment information...
PyTorch version: 1.11.0a0+gitbc2c6ed
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 12.0.1-++20211029101322+fed41342a82f-1~exp1~20211029221816.4
CMake version: version 3.22.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-99-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 11.4.152
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.11.0a0+gitbc2c6ed
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchaudio==0.12.0a0+050b2fb
[pip3] torchpq==0.1.8.3
[conda] Could not collect

**Comment by Gamrix** [comment]
Closing as this warning is not present in `1.12` which will be released in the next few weeks.
