### ISSUE TITLE
[Caffe2]  Building From Source Error : module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by Hammania689** [pytorch/pytorch#7826]
I have followed the installation instructions provided from Caffe2 website, however when I attempt to build I run into this error. I do not understand why this is happening? 

## Here's My Output When I Run `sudo make install` 

```
[ 19%] Building C object confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/linux/smallfile.c.o
[ 19%] Building C object confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/linux/multiline.c.o
[ 19%] Building C object confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/linux/current.c.o
[ 19%] Building C object confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/linux/cpulist.c.o
[ 19%] Building C object confu-deps/cpuinfo/CMakeFiles/cpuinfo.dir/src/linux/processors.c.o
[ 20%] Linking C static library ../../lib/libcpuinfo.a
[ 20%] Built target cpuinfo
[ 21%] Generating src/x86_64-fma/2d-fourier-8x8.py.o
Traceback (most recent call last):
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/hameed/pytorch/third_party/python-peachpy/peachpy/x86_64/__init__.py", line 25, in <module>
    from peachpy.x86_64.function import Function, LocalVariable
  File "/home/hameed/pytorch/third_party/python-peachpy/peachpy/x86_64/function.py", line 16, in <module>
    import peachpy.x86_64.avx
  File "/home/hameed/pytorch/third_party/python-peachpy/peachpy/x86_64/avx.py", line 4, in <module>
    import inspect
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/inspect.py", line 41, in <module>
    import linecache
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/home/hameed/.pyenv/versions/3.6.5/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
confu-deps/NNPACK/CMakeFiles/nnpack.dir/build.make:61: recipe for target 'confu-deps/NNPACK/src/x86_64-fma/2d-fourier-8x8.py.o' failed
make[2]: *** [confu-deps/NNPACK/src/x86_64-fma/2d-fourier-8x8.py.o] Error 1
CMakeFiles/Makefile2:343: recipe for target 'confu-deps/NNPACK/CMakeFiles/nnpack.dir/all' failed
make[1]: *** [confu-deps/NNPACK/CMakeFiles/nnpack.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

## System Info
OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: TITAN X (Pascal)
Nvidia driver version: 384.81
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py27_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py27_1    pytorch

**I am using Pyenv and Conda to manage my installation but I don't believe this is the issue for I have had success in past installations**

## Goal of Installation
I had successfully installed Caffe2 with Python3 but I want to install Detectron and there currently is no support for Python3 so I had to start from scratch. 

Can someone please help me fix this error or inform me of a better method to install Caffe2 and Detectron?
Thank you for your time!

**Comment by chamecall** [comment]
Hey, did you solve the problem in the end?

**Comment by mruberry** [comment]
Closing this issue due to age and because PyTorch is now preferred to Caffe2. If this issue is still relevant then please open a new issue.
