### ISSUE TITLE
MobileProfiler.Backend test is flaky

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#78283]
Examples on master today:
- https://github.com/pytorch/pytorch/runs/6597443451?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/6596207186?check_suite_focus=true

**Comment by suo** [comment]
@kimishpatel you have been identified as the right owner for this test. Can you look into it?

**Comment by suo** [comment]
I disabled this test for now in https://github.com/pytorch/pytorch/pull/78320

**Comment by robieta** [comment]
Is the flakiness recent? If so I might be responsible.

**Comment by suo** [comment]
I think so, although this test is sort of weird so we don't have great visibility into its history.

**Comment by suo** [comment]
@robieta can I assign this to you?

**Comment by robieta** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/78563
