### ISSUE TITLE
Why does the cpp docs build take so long?

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#78295]
The current cpp docs job takes 1h33m average to build. What is making it take so long and how can we speed it up?

https://github.com/pytorch/pytorch/runs/6597818292?check_suite_focus=true

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ezyang @zou3519 @holly1238 @svekars

**Comment by malfet** [comment]
Taking an AI to look into doc builds times

**Comment by janeyx99** [comment]
This is vacuously "fixed" by removing the doxygen part--however the list of functions generated is still referenced from tutorials/other places so we should bring it back (maybe in a periodic fashion).

**Comment by malfet** [comment]
See also https://github.com/pytorch/pytorch/issues/80505

**Comment by malfet** [comment]
Please note that doc generation were re-enabled in https://github.com/pytorch/pytorch/commit/ee86331d0c6f13feac66144a9e1050e22fa9f505
but surprisingly there aren't as many "exit code 137" failures as previously reported in https://github.com/pytorch/pytorch/issues/79992

**Comment by ZainRizvi** [comment]
Closing as low-pri. We can explore this again if this comes close to being a bottleneck on out TTS
