### ISSUE TITLE
[doc] asarray is uglily formatted

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#78290]
### 📚 The doc issue

![image](https://user-images.githubusercontent.com/5674597/170350081-8c28adca-3439-4c87-8306-fe43b237496b.png)

### Suggest a potential alternative/fix

Remove the unnecessary line breaks, and make the formatting consistent among the mentioned functions.

cc @svekars @holly1238 @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

**Comment by ngimel** [comment]
cc @ysiraichi

**Comment by ysiraichi** [comment]
I will take care of it.
