### ISSUE TITLE
[Caffe2] No module named caffe2_pybind11_state_gpu error on running Caffe2 tutorial

### ISSUE THREAD

**Issue by talsperre** [pytorch/pytorch#7830]
## Issue description

Installed Caffe2 using the instructions provided in corresponding [website](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt). Installed using Anaconda binaries for CUDA-8 and cuDNN 7.0.5. 

On running the tutorial: ```Toy_Regression.ipynb``` present in ```https://github.com/caffe2/tutorials caffe2_tutorials```, it shows the error:
```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: No module named caffe2_pybind11_state_gpu
```

All requirements such as CUDA, cuDNN, NCCL etc have been satisfied.

Caffe2 has been installed in a conda environment.

## System Info
```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce 940MX
Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py35_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] torchvision               0.2.1                    py35_1    pytorch
```

**Caffe2:**
- Conda Install: ```conda install -c caffe2 caffe2-cuda8.0-cudnn7```
- OS: Ubuntu 16.0.4
- CUDA/cuDNN version: CUDA-8, cuDNN 7.0.5
- GPU models and configuration: Nvidia GeForce 940MX
- GCC version (if compiling from source): 5.4.0

**Comment by mruberry** [comment]
Closing this issue due to age and because PyTorch is now preferred to Caffe2. If this issue is still relevant then please open a new issue.
