### ISSUE TITLE
The example for Torch.log is not very useful (all nan)

### ISSUE THREAD

**Issue by Kasekopf** [pytorch/pytorch#78301]
### 📚 The doc issue

The current example usage for torch.log generates 5 random numbers. It just so happens that all the numbers generated are negative, so the logs are all nan and thus the example output is not that useful:

```>>> a = torch.randn(5)
>>> a
tensor([-0.7168, -0.5471, -0.8933, -1.4428, -0.1190])
>>> torch.log(a)
tensor([ nan,  nan,  nan,  nan,  nan])
```
From [https://pytorch.org/docs/stable/generated/torch.log.html](https://pytorch.org/docs/stable/generated/torch.log.html)

### Suggest a potential alternative/fix

Use different random numbers.

cc @svekars @holly1238

**Comment by ngimel** [comment]
We'll accept a PR fixing this, `rand` instead of `randn` should do the trick.

**Comment by albanD** [comment]
Fixed in master.
