### ISSUE TITLE
Show parameter types in function signatures

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#78311]
### 📚 The doc issue

The current python API documentation does not capture the annotated types for the function arguments: For example, https://pytorch.org/docs/stable/generated/torch.nn.Linear.html does not show the types even though https://pytorch.org/docs/stable/_modules/torch/nn/modules/linear.html#Linear has annotated types in its `__init__`. Showing parameter types will help readers understand how they can use the APIs better.

### Suggest a potential alternative/fix

Capture the parameter types in the function signatures and show them in the docs.

cc @svekars @holly1238 @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by ShawnZhong** [comment]
For reference, PR #49294 removed type annotations from signatures in HTML docs

**Comment by justinchuby** [comment]
@ShawnZhong thanks! I wasn't aware of them. These are great discussions
