### ISSUE TITLE
`torch.load` does not propagate `map_location` arg to `torch.jit.load`

### ISSUE THREAD

**Issue by shenyih0ng** [pytorch/pytorch#78331]
## Issue description

`torch.load` checks if the given file is a torchscript zip and when it is found to be true, it delegates loading to `torch.jit.load`. However, arguments such as `map_location` is not propagated to the subsequent invocation of `torch.jit.load`(seen below L711).

https://github.com/pytorch/pytorch/blob/e9d0f5fb17ad30939b7217f1a1d0552a6d005ba0/torch/serialization.py#L699-L713

## Code example

This might be out of convention, but when trying to use `torch.load` as a generic way to load both torch and torchscript files, enforcing `torch.load` with `map_location=torch.device('cpu')` will have no effect on `torch.jit.load` since the arg is not propagated.

```python
'''
This following load of torchscript model does not enforce parameters 
to be mapped to a CPU when it is originally mapped to a GPU
'''
torch.load('<torchscript-file-path>', map_location=torch.device('cpu')) # fails when no GPU is available
```

**Comment by andrijdavid** [comment]
I can work on a fix for this issue.
