### ISSUE TITLE
RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by soltkreig** [pytorch/pytorch#78348]
### 🐛 Describe the bug

Hi, I got the error when I tried to export Video-Swin-Transformer model to ONNX format
RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1631630841592/work/torch/csrc/jit/passes/onnx/shape_type_inference.cpp":520, please report a bug to PyTorch. ONNX Expand input shape constraint not satisfied.

### Versions

yTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:22:55)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: A100 Graphics Device
Nvidia driver version: 450.80.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.9.1
[pip3] torchaudio==0.9.0a0+a85b239
[pip3] torchvision==0.10.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.1.1              h6406543_10    conda-forge
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] numpy-base                1.21.5           py39hf524024_2    defaults
[conda] pytorch                   1.9.1           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.9.1                      py39    pytorch
[conda] torchvision               0.10.1               py39_cu111    pytorch

**Comment by BowenBao** [comment]
hi @soltkreig, could you please give a try with newer PyTorch version (latest release is 1.11)? If error persists, please help create a end to end repro for us to investigate. Thanks.

**Comment by redeemme** [comment]
I have the same error as  
RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch\\csrc\\jit\\passes\\onnx\\shape_type_inference.cpp":575, please report a bug to PyTorch. ONNX Expand input shape constraint not satisfied.
But I have already use pytorch 1.11

**Comment by BangwenHe** [comment]
I solved my problem [here](https://github.com/mileyan/AnyNet/issues/35). I don't know whether this is a bug in pytorch or onnx, or whether users should not write in this way.

**Comment by onlytailei** [comment]
Same error in pytorch 1.11.0

**Comment by BangwenHe** [comment]
> Same error in pytorch 1.11.0

Hi, @onlytailei.  I solved my problem by returning the result after one line of code in the forward method. More Specifically, if the exporting process succeeds after returning the result below line i, return the result below line i+1 and iteratively find the final error line. Anyway, hope you can solve the problem finally.

**Comment by onlytailei** [comment]
@BangwenHe   After checking [the doc](https://pytorch.org/docs/stable/onnx.html#writes-sets),  I find that it is because the miss using of multiple tensor indices for assignment.

**Comment by jeungmin717** [comment]
@BangwenHe 
Hello , 
I was struggling with converting (pytorch model) lprnet.pth to (ONNX model) lprnet.onnx
since F.grid_sample and F.affine_grid functions are not supported by pytorch.

I managed to replace these two functions by not using F. (torch.nn.functional)
(found some code in git for replacing these functions, tested output was same)

After training LPRNET model with STN appended., 
Now I have trouble when converting (torch.export) to onnx model.
the error I found is the same error as you mentioned

![image](https://github.com/pytorch/pytorch/assets/34965935/babf5a5a-7169-4613-a013-7ff06573beaa)


RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/onnx/shape_type_inference.cpp":575, please report a bug to PyTorch. ONNX Expand input shape constraint not satisfied.
my code is 

`class STNet(nn.Module):
    def __init__(self):
        super(STNet, self).__init__()

        # Spatial transformer localization-network
        self.localization = nn.Sequential(
                nn.Conv2d(3, 32, kernel_size=3),
                nn.MaxPool2d(2, stride=2),
                nn.ReLU(True),
                nn.Conv2d(32, 32, kernel_size=5),
                nn.MaxPool2d(3, stride=3),
                nn.ReLU(True)
                )
        # Regressor for the 3x2 affine matrix
        self.fc_loc = nn.Sequential(
                nn.Linear(32 * 14 * 2, 32),
                nn.ReLU(True),
                nn.Linear(32, 3*2)
                )
        # Initialize the weights/bias with identity transformation 
        self.fc_loc[2].weight.data.zero_()
        self.fc_loc[2].bias.data.copy_(torch.tensor([1,0,0,0,1,0], dtype=torch.float))
        
    def forward(self, x):
        
        xs = self.localization(x)
        # print("[jeung xs type: ",type(xs))
        # print("[jeung] xs size :",xs.shape)
        xs = xs.contiguous().view(-1, 32*14*2)
        # print("[jeung] transformed xs size :",xs.shape)
        theta = self.fc_loc(xs)
        theta = theta.view(-1,2,3)
        # print("FORWAARD!!!!! x.size(): ", x.size())
        grid = self.affine_grid_pinto(theta,x.size())
        num_dimensions = grid.dim()
        # print(num_dimensions)
        # print(grid[0])
        # print(grid.shape())
        
        # x = self.grid_sample_onnx(x,grid)
        x = self.bilinear_grid_sample(x,grid) #p return
        
        # grid = F.affine_grid(theta, x.size())
        # x = F.grid_sample(x, grid)
        
        return x
    
    def affine_grid_pinto(self, theta, size, align_corners=False):
        N, C, H, W = size
        grid = self.create_grid(N, C, H, W).to(theta.device)
        grid = grid.view(N, H * W, 3).bmm(theta.transpose(1, 2))
        grid = grid.view(N, H, W, 2)
        return grid
    
    def create_grid(self,N, C, H, W):
        grid = torch.empty((N, H, W, 3), dtype=torch.float32)
        grid.select(-1, 0).copy_(self.linspace_from_neg_one(W))
        grid.select(-1, 1).copy_(self.linspace_from_neg_one(H).unsqueeze_(-1))
        grid.select(-1, 2).fill_(1)
        return grid
    
    def linspace_from_neg_one(self,num_steps, dtype=torch.float32):
        r = torch.linspace(-1, 1, num_steps, dtype=torch.float32)
        r = r * (num_steps - 1) / num_steps
        return r
    
    
    def affine_grid_onnx(self, theta, size):
        _, _, height, width = size
        
        # Generate normalized grid coordinates
        grid_y, grid_x = torch.meshgrid([torch.linspace(-1, 1, height), torch.linspace(-1, 1, width)])
        grid = torch.stack((grid_x, grid_y), dim=0)
        grid = grid.unsqueeze(0).expand(theta.size(0), -1, -1, -1)
        
        # Apply affine transformation
        theta = theta.view(theta.size(0), 2, 3)
        theta_expand = theta.unsqueeze(2).unsqueeze(3)
        grid_transformed = torch.matmul(theta_expand[:, :, :, :2, :2], grid) + theta_expand[:, :, :, None, 2:]
        
        # Rescale coordinates to match the image size
        grid_transformed[:, 0] = 2.0 * (grid_transformed[:, 0] / (width - 1)) - 1.0
        grid_transformed[:, 1] = 2.0 * (grid_transformed[:, 1] / (height - 1)) - 1.0
        
        # Reshape and return the transformed grid
        grid_transformed = grid_transformed.permute(0, 2, 3, 1)
        return grid_transformed

    def bilinear_grid_sample(self,im, grid, align_corners=False):
        """
        Given an input and a flow-field grid, computes the output using input
        values and pixel locations from grid. Supported only bilinear interpolation
        method to sample the input pixels.
        Args:
        im (torch.Tensor): Input feature map, shape (N, C, H, W)
        grid (torch.Tensor): Point coordinates, shape (N, Hg, Wg, 2)
        align_corners {bool}: If set to True, the extrema (-1 and 1) are
        considered as referring to the center points of the input’s
        corner pixels. If set to False, they are instead considered as
        referring to the corner points of the input’s corner pixels,
        making the sampling more resolution agnostic.
        Returns:
        torch.Tensor: A tensor with sampled points, shape (N, C, Hg, Wg)
        """
        n, c, h, w = im.shape
        gn, gh, gw, _ = grid.shape
        assert n == gn

        x = grid[:, :, :, 0]
        y = grid[:, :, :, 1]

        if align_corners:
            x = ((x + 1) / 2) * (w - 1)
            y = ((y + 1) / 2) * (h - 1)
        else:
            x = ((x + 1) * w - 1) / 2
            y = ((y + 1) * h - 1) / 2

        x = x.view(n, -1)
        y = y.view(n, -1)

        x0 = torch.floor(x).long()
        y0 = torch.floor(y).long()
        x1 = x0 + 1
        y1 = y0 + 1

        wa = ((x1 - x) * (y1 - y)).unsqueeze(1)
        wb = ((x1 - x) * (y - y0)).unsqueeze(1)
        wc = ((x - x0) * (y1 - y)).unsqueeze(1)
        wd = ((x - x0) * (y - y0)).unsqueeze(1)

        # Apply default for grid_sample function zero padding
        im_padded = torch.nn.functional.pad(im, pad=[1, 1, 1, 1], mode='constant', value=0)
        padded_h = h + 2
        padded_w = w + 2
        # save points positions after padding
        x0, x1, y0, y1 = x0 + 1, x1 + 1, y0 + 1, y1 + 1

        device = im.device  # Get the device of the input tensor

        # Clip coordinates to padded image size
        x0 = torch.where(x0 < 0, torch.tensor(0, device=device), x0)
        x0 = torch.where(x0 > padded_w - 1, torch.tensor(padded_w - 1, device=device), x0)
        x1 = torch.where(x1 < 0, torch.tensor(0, device=device), x1)
        x1 = torch.where(x1 > padded_w - 1, torch.tensor(padded_w - 1, device=device), x1)
        y0 = torch.where(y0 < 0, torch.tensor(0, device=device), y0)
        y0 = torch.where(y0 > padded_h - 1, torch.tensor(padded_h - 1, device=device), y0)
        y1 = torch.where(y1 < 0, torch.tensor(0, device=device), y1)
        y1 = torch.where(y1 > padded_h - 1, torch.tensor(padded_h - 1, device=device), y1)

        im_padded = im_padded.view(n, c, -1)

        x0_y0 = (x0 + y0 * padded_w).unsqueeze(1).expand(-1, c, -1)
        x0_y1 = (x0 + y1 * padded_w).unsqueeze(1).expand(-1, c, -1)
        x1_y0 = (x1 + y0 * padded_w).unsqueeze(1).expand(-1, c, -1)
        x1_y1 = (x1 + y1 * padded_w).unsqueeze(1).expand(-1, c, -1)

        Ia = torch.gather(im_padded, 2, x0_y0)
        Ib = torch.gather(im_padded, 2, x0_y1)
        Ic = torch.gather(im_padded, 2, x1_y0)
        Id = torch.gather(im_padded, 2, x1_y1)

        return (Ia * wa + Ib * wb + Ic * wc + Id * wd).reshape(n, c, gh, gw)`




what was the reason of this error? 

will this error be fixed by updating onnx opset version 14->16 ?
I really need help

**Comment by Yiman-GO** [comment]
> @BangwenHe @onlytailei Hello , I was struggling with converting (pytorch model) lprnet.pth to (ONNX model) lprnet.onnx since F.grid_sample and F.affine_grid functions are not supported by pytorch.
> 
> I managed to replace these two functions by not using F. (torch.nn.functional) (found some code in git for replacing these functions, tested output was same)
> 
> After training LPRNET model with STN appended., Now I have trouble when converting (torch.export) to onnx model. the error I found is the same error as you mentioned
> 
> ![image](https://user-images.githubusercontent.com/34965935/247489305-babf5a5a-7169-4613-a013-7ff06573beaa.png)
> 
> RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/onnx/shape_type_inference.cpp":575, please report a bug to PyTorch. ONNX Expand input shape constraint not satisfied. my code is
> 
> ` class STNet(nn.Module): def **init**(self): super(STNet, self).**init**()
> 
> ```
>     # Spatial transformer localization-network
>     self.localization = nn.Sequential(
>             nn.Conv2d(3, 32, kernel_size=3),
>             nn.MaxPool2d(2, stride=2),
>             nn.ReLU(True),
>             nn.Conv2d(32, 32, kernel_size=5),
>             nn.MaxPool2d(3, stride=3),
>             nn.ReLU(True)
>             )
>     # Regressor for the 3x2 affine matrix
>     self.fc_loc = nn.Sequential(
>             nn.Linear(32 * 14 * 2, 32),
>             nn.ReLU(True),
>             nn.Linear(32, 3*2)
>             )
>     # Initialize the weights/bias with identity transformation 
>     self.fc_loc[2].weight.data.zero_()
>     self.fc_loc[2].bias.data.copy_(torch.tensor([1,0,0,0,1,0], dtype=torch.float))
>     
> def forward(self, x):
>     
>     xs = self.localization(x)
>     # print("[jeung xs type: ",type(xs))
>     # print("[jeung] xs size :",xs.shape)
>     xs = xs.contiguous().view(-1, 32*14*2)
>     # print("[jeung] transformed xs size :",xs.shape)
>     theta = self.fc_loc(xs)
>     theta = theta.view(-1,2,3)
>     # print("FORWAARD!!!!! x.size(): ", x.size())
>     grid = self.affine_grid_pinto(theta,x.size())
>     num_dimensions = grid.dim()
>     # print(num_dimensions)
>     # print(grid[0])
>     # print(grid.shape())
>     
>     # x = self.grid_sample_onnx(x,grid)
>     x = self.bilinear_grid_sample(x,grid) #p return
>     
>     # grid = F.affine_grid(theta, x.size())
>     # x = F.grid_sample(x, grid)
>     
>     return x
> 
> def affine_grid_pinto(self, theta, size, align_corners=False):
>     N, C, H, W = size
>     grid = self.create_grid(N, C, H, W).to(theta.device)
>     grid = grid.view(N, H * W, 3).bmm(theta.transpose(1, 2))
>     grid = grid.view(N, H, W, 2)
>     return grid
> 
> def create_grid(self,N, C, H, W):
>     grid = torch.empty((N, H, W, 3), dtype=torch.float32)
>     grid.select(-1, 0).copy_(self.linspace_from_neg_one(W))
>     grid.select(-1, 1).copy_(self.linspace_from_neg_one(H).unsqueeze_(-1))
>     grid.select(-1, 2).fill_(1)
>     return grid
> 
> def linspace_from_neg_one(self,num_steps, dtype=torch.float32):
>     r = torch.linspace(-1, 1, num_steps, dtype=torch.float32)
>     r = r * (num_steps - 1) / num_steps
>     return r
> 
> 
> def affine_grid_onnx(self, theta, size):
>     _, _, height, width = size
>     
>     # Generate normalized grid coordinates
>     grid_y, grid_x = torch.meshgrid([torch.linspace(-1, 1, height), torch.linspace(-1, 1, width)])
>     grid = torch.stack((grid_x, grid_y), dim=0)
>     grid = grid.unsqueeze(0).expand(theta.size(0), -1, -1, -1)
>     
>     # Apply affine transformation
>     theta = theta.view(theta.size(0), 2, 3)
>     theta_expand = theta.unsqueeze(2).unsqueeze(3)
>     grid_transformed = torch.matmul(theta_expand[:, :, :, :2, :2], grid) + theta_expand[:, :, :, None, 2:]
>     
>     # Rescale coordinates to match the image size
>     grid_transformed[:, 0] = 2.0 * (grid_transformed[:, 0] / (width - 1)) - 1.0
>     grid_transformed[:, 1] = 2.0 * (grid_transformed[:, 1] / (height - 1)) - 1.0
>     
>     # Reshape and return the transformed grid
>     grid_transformed = grid_transformed.permute(0, 2, 3, 1)
>     return grid_transformed
> 
> def bilinear_grid_sample(self,im, grid, align_corners=False):
>     """
>     Given an input and a flow-field grid, computes the output using input
>     values and pixel locations from grid. Supported only bilinear interpolation
>     method to sample the input pixels.
>     Args:
>     im (torch.Tensor): Input feature map, shape (N, C, H, W)
>     grid (torch.Tensor): Point coordinates, shape (N, Hg, Wg, 2)
>     align_corners {bool}: If set to True, the extrema (-1 and 1) are
>     considered as referring to the center points of the input’s
>     corner pixels. If set to False, they are instead considered as
>     referring to the corner points of the input’s corner pixels,
>     making the sampling more resolution agnostic.
>     Returns:
>     torch.Tensor: A tensor with sampled points, shape (N, C, Hg, Wg)
>     """
>     n, c, h, w = im.shape
>     gn, gh, gw, _ = grid.shape
>     assert n == gn
> 
>     x = grid[:, :, :, 0]
>     y = grid[:, :, :, 1]
> 
>     if align_corners:
>         x = ((x + 1) / 2) * (w - 1)
>         y = ((y + 1) / 2) * (h - 1)
>     else:
>         x = ((x + 1) * w - 1) / 2
>         y = ((y + 1) * h - 1) / 2
> 
>     x = x.view(n, -1)
>     y = y.view(n, -1)
> 
>     x0 = torch.floor(x).long()
>     y0 = torch.floor(y).long()
>     x1 = x0 + 1
>     y1 = y0 + 1
> 
>     wa = ((x1 - x) * (y1 - y)).unsqueeze(1)
>     wb = ((x1 - x) * (y - y0)).unsqueeze(1)
>     wc = ((x - x0) * (y1 - y)).unsqueeze(1)
>     wd = ((x - x0) * (y - y0)).unsqueeze(1)
> 
>     # Apply default for grid_sample function zero padding
>     im_padded = torch.nn.functional.pad(im, pad=[1, 1, 1, 1], mode='constant', value=0)
>     padded_h = h + 2
>     padded_w = w + 2
>     # save points positions after padding
>     x0, x1, y0, y1 = x0 + 1, x1 + 1, y0 + 1, y1 + 1
> 
>     device = im.device  # Get the device of the input tensor
> 
>     # Clip coordinates to padded image size
>     x0 = torch.where(x0 < 0, torch.tensor(0, device=device), x0)
>     x0 = torch.where(x0 > padded_w - 1, torch.tensor(padded_w - 1, device=device), x0)
>     x1 = torch.where(x1 < 0, torch.tensor(0, device=device), x1)
>     x1 = torch.where(x1 > padded_w - 1, torch.tensor(padded_w - 1, device=device), x1)
>     y0 = torch.where(y0 < 0, torch.tensor(0, device=device), y0)
>     y0 = torch.where(y0 > padded_h - 1, torch.tensor(padded_h - 1, device=device), y0)
>     y1 = torch.where(y1 < 0, torch.tensor(0, device=device), y1)
>     y1 = torch.where(y1 > padded_h - 1, torch.tensor(padded_h - 1, device=device), y1)
> 
>     im_padded = im_padded.view(n, c, -1)
> 
>     x0_y0 = (x0 + y0 * padded_w).unsqueeze(1).expand(-1, c, -1)
>     x0_y1 = (x0 + y1 * padded_w).unsqueeze(1).expand(-1, c, -1)
>     x1_y0 = (x1 + y0 * padded_w).unsqueeze(1).expand(-1, c, -1)
>     x1_y1 = (x1 + y1 * padded_w).unsqueeze(1).expand(-1, c, -1)
> 
>     Ia = torch.gather(im_padded, 2, x0_y0)
>     Ib = torch.gather(im_padded, 2, x0_y1)
>     Ic = torch.gather(im_padded, 2, x1_y0)
>     Id = torch.gather(im_padded, 2, x1_y1)
> 
>     return (Ia * wa + Ib * wb + Ic * wc + Id * wd).reshape(n, c, gh, gw)
> ```
> 
> `
> 
> what was the reason of this error? or is it the pytorch not supported error. Could you give me some hint? I really need help.

Hello！I have the same error with you. Have you found any solutions to sovle it?

**Comment by Yiman-GO** [comment]
@jeungmin717  Hello！I have the same error with you. Have you found any solutions to sovle it?

**Comment by jeungmin717** [comment]
@Yiman-GO 
Awesome, did you include STN layer into LPRNET model and converted to .onnx ?
could you give me more details on **dynamic_axes** you used? which options or parameters did you use?

**Comment by Yiman-GO** [comment]
@BangwenHe I didn't use the LPRNET model. FYI, my code is  as followed:
`torch.onnx.export(model=model,  
                          f=onnx_path,  
                          input_names=["input"], 
                          output_names=["output"], 
                          opset_version=14, 
                          dynamic_axes=["input"],{0:'batch_size'}, "output":{0:'batch_size'}})`
Pytorch == 1.10.0.

**Comment by lix19937** [comment]
Same error in pytorch 1.13.1+cu116

**Comment by lix19937** [comment]
```
Traceback (most recent call last):
  File "./tools/test.py", line 373, in <module>
    main()
  File "./tools/test.py", line 322, in main
    torch.onnx.export(
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/utils.py", line 497, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/utils.py", line 1032, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 483, in expand_as
    return g.op("Expand", self, shape)
  File "/home/lix/anaconda3/envs/onnx_ref/lib/python3.8/site-packages/torch/onnx/utils.py", line 928, in _graph_op
    torch._C._jit_pass_onnx_node_shape_type_inference(n, _params_dict, opset_version)
RuntimeError: input_shape_value == reshape_value || input_shape_value == 1 || reshape_value == 1INTERNAL ASSERT FAILED at "../torch/csrc/jit/passes/onnx/shape_type_inference.cpp":547, please report a bug to PyTorch. ONNX Expand input shape constraint not satisfied.
```

**Comment by valaxkong** [comment]
Same error when exporting pytorch model to onnx.`A100+torch1.12.1+cu113+python3.9`.
Setting the 0th dimension (the batch dimension) as a dynamic axis can serve as a workaround. However, I'm curious about the necessity of using "dynamic axes". Suppose I actually need a fixed size for the 0th dimension, what steps should I take?
