### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by IlyasDawoodjee** [pytorch/pytorch#78341]
## Issue description

I was running some other code and I faced the error "RuntimeError: Numpy is not available". I searched around and found out that running the code I have attached below produced the same type of error. I haven't been able to find a solution online. Kindly assist please.

## Code example

import numpy
import torch
test_torch = torch.rand(100,1,28,28)
print(test_torch.numpy())

## System Info
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip3 install torch torchvision torchaudio
- OS: Windows 11
- PyTorch version:  1.11.0+cpu
- Python version: 3.10.2
- CUDA/cuDNN version: 11.5/8.3.3
- GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650 with Max-Q Design
- GCC version (if compiling from source): Could not collect
- CMake version: Could not collect
- Versions of any other relevant libraries: N/A

**Comment by IlyasDawoodjee** [comment]
Solved this by downgrading my python version to 3.9.2

**Comment by HemanthSai7** [comment]
It's because of the numpy version. Just upgrading numpy by ``pip install numpy --upgrade``` solved this issue.

**Comment by voidxO7** [comment]
> It's because of the numpy version. Just upgrading numpy by `pip install numpy --upgrade` solved this issue.

I did that and it still gives me this error:

`Error occurred when executing SaveImage:

Numpy is not available

File "O:\stable-diffusion-comfyui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "O:\stable-diffusion-comfyui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "O:\stable-diffusion-comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "O:\stable-diffusion-comfyui\ComfyUI\nodes.py", line 1407, in save_images
i = 255. * image.cpu().numpy()
^^^^^^^^^^^^^^^^^^^`

**Comment by andriy-pc** [comment]
I had to downgrade numpy ( from 2.0.0 to 1.26.4) (btw I'm using Python 3.9.19) to solve the issue

**Comment by 1ranxu** [comment]
> 我不得不将numpy降级（从2.0.0降级到1.26.4）（顺便说一句，我正在使用Python 3.9.19）来解决这个问题

this is a nice method

**Comment by ShoufaChen** [comment]
Downgrading numpy from `2.0.0` to `1.26.4` works, python 3.11.

**Comment by uchihaone** [comment]
That works for me as well.

**Comment by Jimmy586** [comment]
this works for me as well

**Comment by meyush0** [comment]
> I had to downgrade numpy ( from 2.0.0 to 1.26.4) (btw I'm using Python 3.9.19) to solve the issue

thnx it working now

**Comment by manjunathshiva** [comment]
> Downgrading numpy from `2.0.0` to `1.26.4` works, python 3.11.

this worked for me as well! Thank you!
