### ISSUE TITLE
macos build time increased significantly after runner update to macos-12

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#78375]
### 🐛 Describe the bug

Compare https://github.com/pytorch/pytorch/runs/6488531812?check_suite_focus=true (which download binary artifacts from cache) vs https://github.com/pytorch/pytorch/runs/6489629931?check_suite_focus=true (after runner was migrated to macos-12)

Relates to https://github.com/pytorch/pytorch/pull/77645

### Versions

N/A

cc @seemethere @malfet @pytorch/pytorch-dev-infra @albanD

**Comment by malfet** [comment]
Hmm, one reason for the change, is that `macos-12` runners seems to be running on weaker machines:
`macos-12`: `machdep.cpu.brand_string: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz`
`macos-11`: `machdep.cpu.brand_string: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz `

**Comment by albanD** [comment]
Do we have ccache statistics printed on these runners to see if there are caching issues?

**Comment by malfet** [comment]
Nope, this is what I'm trying to add right now, I suspect that cache is not at all used somehow

**Comment by albanD** [comment]
Or that one of the flag we use is preventing caching for obj-c code.

**Comment by malfet** [comment]
This is true, but Obj-C is less than 10% of what we compile, so it does not matter that much

**Comment by atalman** [comment]
I extracted all the MacOS jobs we run yesterday here. Last column is the duration in minutes. macos-12 jobs are constantly hitting 2 hrs+ running time

[query-results-complete-duration.csv](https://github.com/pytorch/pytorch/files/8782377/query-results-complete-duration.csv)

**Comment by albanD** [comment]
> This is true, but Obj-C is less than 10% of what we compile, so it does not matter that much

Yes, but the machines that we run this on are really not powerful. Even a fully cached compilation without MPS takes 20min if I recall correctly from when I was playing with CI to setup the macos-12 runners.

**Comment by malfet** [comment]
Hmm, weak framework is a linker flag and as such should be passed only while linking `libtorch`, let's see if https://github.com/pytorch/pytorch/pull/78630 will improve compilation time
