### ISSUE TITLE
DISABLED test_learnable_forward_per_channel_cpu (quantization.core.test_workflow_ops.TestFakeQuantizeOps)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#78377]
Platforms:  macos

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_learnable_forward_per_channel_cpu%2C%20quantization.core.test_workflow_ops.TestFakeQuantizeOps)).

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by andrewor14** [comment]
Seems like it's reenabled again. Closing this
