### ISSUE TITLE
[ONNX] way to write an opset_version-dependent symbolic function for autograd.Function

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#78391]
`torch.onnx.export` supports autograd.Function defining a static `symbolic` method. However I haven't found a public way for a symbolic method to know what the current value of `opset_version` is, which makes it impossible to write a method that depends on that.

One possibility is to add this to `torch.onnx.SymbolicContext`.

@BowenBao WDYT?

**Comment by BowenBao** [comment]
True, I feel the current story is that versioning is not considered an option for autograd.Function `symbolic`. It's usually used more as one off for export and rarely needed for bouncing between opsets.

For standard symbolic functions (i.e., ones in `torch/onnx/symbolic_opsetx.py`). Currently two patterns
* Inside symbolic function, opset version needs to be known to create ONNX node under correct spec. This is done by using `xxx_helper` in `symbolic_helper.py`.
    * This can be used by autograd.Function `symbolic` directly.
* Outside symbolic function. Each opset has its own version of that symbolic function, should there be subgraph differences.  
    * This is missing for autograd.Function `symbolic`. We could create decorator for opset version to write multiple symbolic function.

Adding version to `torch.onnx.SymbolicContext` is also an option. I think in the long run we would want to rethink and unify the ways how opset versions are dispatched for all symbolic functions.

**Comment by garymm** [comment]
Here's a concrete use case of needing to know opset_version inside a custom symbolic function:
https://github.com/huggingface/transformers/pull/17502/files

 What do you see as the downside of adding version to `torch.onnx.SymbolicContext`?

**Comment by BowenBao** [comment]
> What do you see as the downside of adding version to `torch.onnx.SymbolicContext`?

Consistency in the design. `torch.onnx.SymbolicContext` is also accessible by standard symbolic functions. I know the "helper" solution is more or less the same (or even worse) as the `symbolic_helper.py` functions are just checking a global variable for opset version. But since we already have a mechanism of doing it, maybe just stick to it before we re-think the whole opset version dispatch.

**Comment by garymm** [comment]
I see what you mean about consistency.

So would your suggestion for https://github.com/huggingface/transformers/pull/17502 be to move `dropout` to symbolic_helper.py and then call `symbolic_helper.dropout`?
That would work, but requires us moving symbolic functions from `symbolic_opsetX` to `symbolic_helper` on a case-by-case basis and then the user has to wait for a new release of PyTorch.

Maybe we can have a cleaner solution before the next release of PyTorch.

**Comment by BowenBao** [comment]
Yes, agree continuous dependency on PyTorch updates is a concern. I'm adding this to the design doc.

**Comment by justinchuby** [comment]
#85486

**Comment by BowenBao** [comment]
Closing as #84728 adds access to opset version for `symbolic` method of `autograd.Function`.
