### ISSUE TITLE
Should we test Gloo with TLS in CI?

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#78398]
The only call to test_python_gloo_with_tls() in .jenkins/pytorch/test.sh is with removed some time ago Python 3.6 environment.

Do we want to add the Gloo with TLS test to some other CI config?

cc @seemethere @malfet @pytorch/pytorch-dev-infra @kit1980

**Comment by osalpekar** [comment]
cc @pbelevich @mrshenli

**Comment by kit1980** [comment]
Closing this as nobody said it's needed.
