### ISSUE TITLE
NLLLoss2d is a _WeighedLoss

### ISSUE THREAD

**Issue by jzbontar** [pytorch/pytorch#784]
Shouldn't NLLLoss2d inherit from _WeighedLoss and not from _Loss in https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/loss.py#L109?

**Comment by apaszke** [comment]
Yeah it should inherit from that.

**Comment by desimone** [comment]
Sorry, I fixed this in #687 but I haven't had a chance to work on the rest of the PR so it's just been sitting there.

**Comment by soumith** [comment]
fixed in master
