### ISSUE TITLE
[CI] Enable LGTM's pull request bot

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#78425]
### 🚀 The feature, motivation and pitch

LGTM is a Github's code analysis platform that conducts automated security and other code analysis. It has produced good signals on correctness in my experience. Example of its signals can be found at https://lgtm.com/projects/g/pytorch/pytorch. We can enable its PR integration by installing its github app.

Example of a signal

<img width="733" alt="image" src="https://user-images.githubusercontent.com/11205048/170732923-9a9bbd83-e230-433a-b1e5-514135d8c203.png">

Example of its PR response looks like 

<img width="805" alt="image" src="https://user-images.githubusercontent.com/11205048/170732363-5d5e23f0-9ce7-4476-bb9b-f85c8246d19f.png">

which is minimal and unintrusive.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
The signals LGTM provides look like lint signals. Is there a way to integrate this tool into our existing lintrunner for CI or to figure out the linters it's using under the hood? Otherwise adding another comment onto every PR (in addition to the Dr. CI comment) is not ideal especially if there's no way to enforce that these things will be fixed before landing.

**Comment by justinchuby** [comment]
@kit1980 thanks for checking out the link! The nice thing about the bot is that it will only report newly introduced alerts by a PR. So the noise are largely not seen. If a PR doesn't cause any new alerts, the bot will not comment.

Of the useful findings many of them are meaningful imo. The previous being an example, here is another one:

![image](https://user-images.githubusercontent.com/11205048/171237461-cc276485-977f-41d3-be50-4fd79dab88d6.png)

![image](https://user-images.githubusercontent.com/11205048/171244511-8ce61790-5dff-4b28-9cf1-dd81e21211d2.png)

**Comment by kit1980** [comment]
Some are useful, I agree.
