### ISSUE TITLE
[ONNX] Floor division in ONNX is inconsistent with eager after #78411

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#78442]
See https://github.com/pytorch/pytorch/pull/78411, which finishes the deprecation of `floor_divide` performing truncation division.

I think ONNX's lowering for the "floor" rounding mode was incorrect historically, too; it looks like that was also mapped to truncation division, but in PyTorch the "floor" rounding mode to div did correctly perform floor division.

Long-term we probably want to consider using primTorch for ONNX lowerings so operator semantics are automatically picked up by the ONNX export system.

**Comment by fxmarty** [comment]
Hi @justinchuby , apparently the warning

```
UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently
rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use
torch.div(a, b, rounding_mode='floor').
```

does not show anymore in PyTorch 1.13. Does this mean that for ONNX export I am safe using `//`, or I may expect undesirable behaviors? Thanks!

**Comment by justinchuby** [comment]
onnx has not updated to match the behavior. It will when this issue is closed

**Comment by justinchuby** [comment]
The behavior is updated in the torch.onnx.dynamo_export exporter
