### ISSUE TITLE
permute returning unexpected results on MPS devices

### ISSUE THREAD

**Issue by tanmayb123** [pytorch/pytorch#78445]
### 🐛 Describe the bug

The `permute` function works fine on CPU, but fails (with a warning) on MPS devices (on macOS):

```python
import torch

cpu = torch.device("cpu")
gpu = torch.device("mps")

data = torch.rand((1, 2, 2, 3))

def run_test(device):
    global data
    with torch.no_grad():
        data = data.to(device)
        data = data.permute(0, 3, 1, 2)
        return data

cr = run_test(cpu)
gr = run_test(gpu)

print(cr)
print(gr)

print(cr.shape)
print(gr.shape)

print(cr.numpy())
print(gr.cpu().numpy())
```

Output:

```
/Users/tanmaybakshi/snoo/dataset_snoo/train/test_linear.py:11: UserWarning: The dst MTL buffer in copy_to_mps is non-contiguous (Triggered internally at  /Users/tanmaybakshi/pytorch/aten/src/ATen/native/mps/operations/Copy.mm:409.)
  data = data.to(device)
tensor([[[[0.3521, 0.9337],
          [0.8170, 0.1294]],

         [[0.9098, 0.0335],
          [0.4609, 0.4326]],

         [[0.3229, 0.7986],
          [0.9524, 0.7348]]]])
/Users/tanmaybakshi/miniforge3/lib/python3.9/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/tanmaybakshi/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
tensor([[[[0.3521, 0.0000],
          [0.4609, 0.0000],
          [0.9337, 0.0000]],

         [[0.9524, 0.0000],
          [0.0335, 0.0000],
          [0.7348, 0.0000]]]], device='mps:0')
torch.Size([1, 3, 2, 2])
torch.Size([1, 2, 3, 2])
[[[[0.35213614 0.93369865]
   [0.81702703 0.12944329]]

  [[0.9097897  0.03350586]
   [0.46094316 0.43263036]]

  [[0.32287186 0.79856473]
   [0.9524258  0.7348249 ]]]]
[[[[0.35213614 0.81702703]
   [0.9097897  0.46094316]
   [0.32287186 0.9524258 ]]

  [[0.93369865 0.12944329]
   [0.03350586 0.43263036]
   [0.79856473 0.7348249 ]]]]
```

The print of the GPU tensor has garbage zero values, the shape is wrong, and the resulting numpy array has the wrong shape as well.

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+gitffb3101
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3 (arm64)
GCC version: Could not collect
Clang version: 13.0.1
CMake version: version 3.23.0
Libc version: N/A

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:27:43)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.7.0.dev0
[pip3] torch==1.13.0a0+gitffb3101
[pip3] torchmetrics==0.8.2
[pip3] torchvision==0.12.0a0
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] numpy                     1.21.6           py39h690d673_0    conda-forge
[conda] pytorch                   1.11.0          cpu_py39h19aa3d3_0    conda-forge
[conda] pytorch-lightning         1.7.0.dev0               pypi_0    pypi
[conda] torch                     1.13.0a0+git9e80661          pypi_0    pypi
[conda] torchmetrics              0.8.2                    pypi_0    pypi
[conda] torchvision               0.12.0          cpu_py39h384c48c_1    conda-forge

**Comment by abhudev** [comment]
I think the testing code is wrongly configured, because when you change `data` inside the function (which is global), you change it when it is operated on by permute the second time. A test like this:

`import torch

cpu = torch.device("cpu")
gpu = torch.device("mps")

data = torch.randint(0, 20, (1, 2, 2, 3))
mps_data = data.to('mps')

cr = data.permute(0, 3, 1, 2)
gr = mps_data.permute(0, 3, 1, 2)

print(cr)
print(gr)

print(gr.shape)
print(cr.shape)
`

produces the correct result for me.

**Comment by Harley-Sun** [comment]
I find that `gr = mps_data.permute(0, 3, 1, 2)` should be added `.contiguous()` at the end, or the output will be wrong. Is it a bug?
