### ISSUE TITLE
"Parameters of a model after .cuda() will be different objects with those before the call." is wrong.

### ISSUE THREAD

**Issue by freud14** [pytorch/pytorch#7844]
Hi,

In the documentation, it is written:

> If you need to move a model to GPU via .cuda(), please do so before constructing optimizers for it. Parameters of a model after .cuda() will be different objects with those before the call.
>
> In general, you should make sure that optimized parameters live in consistent locations when optimizers are constructed and used.

However, doing .cuda() after intialiazing the optimizer still works. This is because the Module class applies the .cuda() in this way:
```python
param.data = fn(param.data)
if param._grad is not None:
    param._grad.data = fn(param._grad.data)
```
Thus, by modifying the `.data` attribute, it modifies the parameter tensors in-place. 

I then suggest to remove this "warning" from the documentation since I actually find this quite useful to be able to initialize the optimizer before doing .cuda().

Thank you.

Frédérik

**Comment by SsnL** [comment]
The particular sentence you referenced is wrong, but you still can't initialize optimizer before moving modules in general
```py
>>> l = torch.nn.Linear(3, 3)
>>> o = torch.optim.Adagrad(l.parameters())
>>> l.cuda()
Linear(in_features=3, out_features=3, bias=True)
>>> l(torch.randn(1,3,device='cuda')).sum().backward()
>>> o.step()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssnl/sftp/pytorch/torch/optim/adagrad.py", line 92, in step
    state['sum'].addcmul_(1, grad, grad)
RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'tensor1'
```

**Comment by freud14** [comment]
It seems to be a problem only for Adagrad because the other optimizers work as expected.

**Comment by gchanan** [comment]
CC @yf225.

**Comment by fmassa** [comment]
I'm not sure this is a behavior that we want to keep for the optimizers.

Moving tensors to `cuda` is not an in-place operation, so the references to the tensor should not be the same once we move the tensors to cuda.

**Comment by apaszke** [comment]
Yes, while some optimizers might be implemented in such a way that works (there's nothing wrong with that), we absolutely do not guarantee that this will be the case if you change them, or even if you download a newer version of PyTorch. I'd like us to keep this restriction.

**Comment by ezyang** [comment]
@yf225 can you comment here? This is very related to your Variabble changes.

**Comment by ezyang** [comment]
@gchanan says this also depends on which optimizer you use

**Comment by yf225** [comment]
> If you need to move a model to GPU via .cuda(), please do so before constructing optimizers for it. Parameters of a model after .cuda() will be different objects with those before the call.
>
> In general, you should make sure that optimized parameters live in consistent locations when optimizers are constructed and used.

Starting from https://github.com/pytorch/pytorch/pull/21613, the new behavior we will have in future releases is consistent with this warning, which is that parameters of a model after dtype/device conversion functions such as `.cuda()`/`.cpu()`/`.to()`/`.float()`/`.double()` will be different objects with those before the call (you can enable this new behavior by setting `torch.__future__.set_overwrite_module_params_on_conversion(True)`. Hence we strongly recommend converting the model to a different device / dtype **before** constructing optimizers for it.
