### ISSUE TITLE
[bazel] "Deleting stale sandbox base" on any code modification

### ISSUE THREAD

**Issue by vors** [pytorch/pytorch#78453]
### 🐛 Describe the bug

When I build with bazel the `:all` target and then trying to modify the build, i.e. add a repository to WORKSPACE, bazel deletes the sandbox and I'm rebuilding from scratch.

```
(.venv) :~/src/pytorch$ bazelisk --nohome_rc build --config=gpu //c10/cuda/test:test
Starting local Bazel server and connecting to it...
INFO: Analyzed target //c10/cuda/test:test (38 packages loaded, 3520 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/sergei.vorobev/.cache/bazel/_bazel_sergei.vorobev/496485847ab0cc6cfab3121747593e0a/sandbox
```

### Versions

master 93a969221d06152746af29fc580701d5b50790b3

**Comment by kit1980** [comment]
cc @dagitses

**Comment by dagitses** [comment]
Hey Sergei, I'm not able to reproduce this at all. Can you give me an example of a WORKSPACE change?

**Comment by vors** [comment]
I tried to repro myself and could not -- most likely that was caused by me changing genrules dependencies, which would explain it. Sorry for the noise.
