### ISSUE TITLE
lt is likely that your environment is messed up. As you can see from the traceback, there are two python environments involved here:

### ISSUE THREAD

**Issue by sachin-kanchan** [pytorch/pytorch#78470]
lt is likely that your environment is messed up. As you can see from the traceback, there are two python environments involved here:
1. C:\Users\nouma\AppData\Roaming\Python\Python37
2. C:\Users\nouma\Anaconda3

Please make sure your `PATH` is clean and you can actually remove one of them first.

_Originally posted by @peterjc123 in https://github.com/pytorch/pytorch/issues/27693#issuecomment-540513657_

---------------------------------------------------------------------------
Can you please clarify what cleaning the "PATH" means here?
I have been facing the same issue and have been unable to resolve.

I installed Python 3.7.9 standalone that I use whenever I create venv thru Visual Studio Code or Pycharm.

Anaconda installation came with Python 3.9 (3.9.7 to be exact)
But I am creating a new project using Conda, & Spyder and created a conda environment with Python 3.7.13. 

And have been getting above error while trying to run the file/cells in Spyder.

Do I need to uninstall standalone python and delete everything associated with it? 

P.S. Apologies if I made an error while asking this, I am very new to github.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by peterjc123** [comment]
When you encounter the error `OSError: [WinError 193] %1 is not a valid Win32 application`, it means a conflicting DLL is trying to be loaded. You can use [Debugging Tools for Windows (WinDBG)](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools) to find it out. You need to install it and perform the following step in an admin shell (by pressing Win+X and then A).

```cmd
 # DLL debugging switches
 gflags /i python.exe +sls
 # Attach the debugger and try to import the library
 cdb -o -c "~*g; q" python -c "import torch"
 # DLL debugging switches
 gflags /i python.exe -sls
```

**Comment by Blackhex** [comment]
According to the description this seems as a Python environment configuration issue. To check out your environment variables just type in `set` cmd.exe or `dir Env:` in PowerShell. Look for how your `PATH` is set and what Python installations contribute to that variable in "Environment Variables" system settings. I would not be mixing standalone and Anaconda installer or Python. Not sure about PyCharm but Visual Studio Code can work with Anaconda environment just fine (and there are even plugins to improve that experience).

If you would find out that this is still a PyTorch related issue, please say so and we can re-open it.
