### ISSUE TITLE
Exception when loading images to 'mps' devices

### ISSUE THREAD

**Issue by legendary6** [pytorch/pytorch#78474]
### When I just load the first image to 'mps' device and detach it, it becomes the result of the second image. I would be very grateful if you could tell me why.

<img width="470" alt="1" src="https://user-images.githubusercontent.com/44915642/170867038-5723eeab-f7bc-4133-863b-2162ddb6415b.png" >
<img width="450" alt="1" src="https://user-images.githubusercontent.com/44915642/170867049-959b5ac4-67eb-4763-a9ad-08233b578515.png">

### Versions

PyTorch version: 1.13.0.dev20220528
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0rc1
[pip3] torch==1.13.0.dev20220528
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] numpy                     1.23.0rc1                pypi_0    pypi
[conda] torch                     1.13.0.dev20220528          pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by ejguan** [comment]
Could you please provide a self-contained script which we could use to reproduce the problem?

**Comment by malfet** [comment]
I suspect that problem might be due to torchvision from 0.12.0 installed next to PyTorch nightly

**Comment by kulinseth** [comment]
@legendary6 , can you please try with the latest torchvision and see if the issue exists. Feel free to open this issue if it persists.
