### ISSUE TITLE
How to fine-tuning on a custom dataset?

### ISSUE THREAD

**Issue by panovr** [pytorch/pytorch#785]
May you add some examples to illustrate how to fine-tuning a pre-trained model on a custom dataset with pytorch and torchvision?

**Comment by fmassa** [comment]
[Here is a pending PR](https://github.com/pytorch/examples/pull/58) that shows how to finetune a network

**Comment by soumith** [comment]
https://discuss.pytorch.org/ also has some examples/discussions

**Comment by panovr** [comment]
@fmassa @soumith Thanks!
