### ISSUE TITLE
ONNX operator parameters being set as input nodes

### ISSUE THREAD

**Issue by sreddy-es** [pytorch/pytorch#78505]
If you are submitting a bug report, please fill in the following details.

## Issue description
As the title states. [Onnx file](https://drive.google.com/file/d/1k2-KCTFTUsAbC28oF02NRy9IQcm6kjuR/view?usp=sharing) for reference. The second resize layer has its scale parameter set as a separate input node which ends up causing problems with tensorRT conversion. The onnx inference runs correctly though.

Provide a short description.

## Code example

```
class upsampleTest(nn.Module):

    def __init__(self):
        super().__init__()
        self.up1 = simplenet.UpsampleBlock(32, 32, 64)
        self.up2 = simplenet.UpsampleBlock(64, 32, 64)


    def forward(self, inp, skip, skip2):
        up = self.up1(inp, skip)
        up2 = self.up2(up, skip2)
        return up2


def test_upsample_block2():
    skip2 = torch.rand(1,32,640,368)
    skip = torch.rand(1,32, 320, 184)
    inp = torch.rand(1,32, 160, 92)

    model_name = "upsample_block2"
    blk2 = upsampleTest()
    m = blk2
    m.eval()
    pt_out = m(inp, skip,skip2)
    with torch.no_grad():
        trace_model = torch.jit.trace(m, (inp,skip,skip2))
    trace_model.save(f"{model_name}.pt")

    
    ts_out = trace_model(inp, skip,skip2)

    torch.onnx.export(trace_model.cpu(), (inp.to("cpu"), skip.to("cpu"),skip2.to("cpu")), f"{model_name}.onnx", input_names=["in", "skip","skip2"], 
                    keep_initializers_as_inputs=False,
                    do_constant_folding=True,
                    operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
                    opset_version=12,
                    verbose=True
    )

    ort_session = ort.InferenceSession(f"{model_name}.onnx", providers=['CUDAExecutionProvider'])

    onnx_out = ort_session.run(
        None,
        {"in": inp.cpu().numpy().astype(np.float32),
         "skip": skip.cpu().numpy().astype(np.float32),
         "skip2": skip2.cpu().numpy().astype(np.float32)},
    )

    print(f"{model_name}")
    print("onnx", np.mean(onnx_out[0]))
    print("ts", np.mean(ts_out[0].detach().cpu().numpy()))
    print("pt", np.mean(pt_out[0].detach().cpu().numpy()))
    print("diff", np.mean(onnx_out[0]-pt_out[0].detach().cpu().numpy()))
    print("ts onnx diff", np.mean(onnx_out[0]-ts_out[0].detach().cpu().numpy()))

test_upsample_block2()

```

## System Info
PyTorch version: 1.12.0a0+2c916ef
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:42:07)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-33-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==0.7.5
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+2c916ef
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.12.0a0
[pip3] torchvision==0.13.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h05e7239_0    conda-forge
[conda] pytorch-lightning         0.7.5                    pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+2c916ef          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.12.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi

**Comment by sreddy-es** [comment]
It looks like the issue can be resolved if we use Polygraphy tool built within tensorRT. But the polygraphy tool is basically doing constant folding. This feature is something that ostensibly torch.onnx already has in its params; 'do_constant_folding' and 'keep_initializer_as_input'. So the Polygraphy tool should not be required.

**Comment by BowenBao** [comment]
Should be fixed by #79552

**Comment by BowenBao** [comment]
Actually I'm re-evaluating the solution. @sreddy-es could you share the source code of `simplenet.UpsampleBlock` in the repro?

**Comment by sreddy-es** [comment]
Ohh sure. I thought I had shared all code.

```
class UpsampleBlock(nn.Module):
  def __init__(self, in_channel, skip_in_channel, out_channel):
    super().__init__()
    
    self.layers = nn.Sequential(
      ConvBlock(in_channel, out_channel, k=1)
    )

    self.skip_layers = nn.Sequential(
      ConvBlock(skip_in_channel, out_channel, k=1)
    )

    self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
  
  def forward(self, inp, skip):
    # pdb.set_trace()
    inp = self.layers(inp)
    skip = self.skip_layers(skip)
    inp = self.up(inp)
    return inp + skip

```
