### ISSUE TITLE
[TorchData] Allow random_split to use percentages when applied to map-style datasets

### ISSUE THREAD

**Issue by xiurobert** [pytorch/pytorch#78510]
### 🚀 The feature, motivation and pitch

This allows for the automatic splitting of datasets easily, since splitting a dataset by percentages is quite a common task.
This feature should work on map-style datasets well as they implement `__len__`.

### Alternatives

Current solutions:
```python
train_ds, test_ds = torchdata.random_split(ds, [int(0.8 * len(ds)), len(ds) - int(0.8 * len(ds))])
train_ds, val_ds = torchdata.random_split(train_ds, [int(0.8 * len(train_ds)), len(train_ds) - int(0.8 * len(train_ds))]
```

### Additional context

A small QOL change

cc @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
There is a similar request https://github.com/pytorch/pytorch/issues/11980

Based on the previous discussion, it seems not too much burden for users to run `random_split(ds, [int(p * len(ds)) for p in percentages])`. Percentage has a problem is rounding as the splits would only accepts integer size.

I personally don't have objection on this feature. But, we need to ensure the backward compatibility by allowing people using either integer array or floating array (percentages) to split datasets.

And, this function needs to be well documented with the rounding behavior.

**Comment by xiurobert** [comment]
I was thinking that this feature could be in addition to accepting a list of integers (since that can be easily differentiated from a list of percentages just by checking whether the sum of the list is equal to 1). Also prevents breaking backwards compatibility.

**Comment by ejguan** [comment]
It's not necessary to have the sum of the list equal to 1. As long as the sum is smaller than 1, it should be fine. Feel free to open a PR

**Comment by xiurobert** [comment]
Sounds good. I'll work on it
