### ISSUE TITLE
torch.nn.Sequential can use `+` (add operator) to concatenate

### ISSUE THREAD

**Issue by dinhanhx** [pytorch/pytorch#78512]
## The feature
Like Python List's add operator, `+` can be used to: 
- concatenate two torch.nn.Sequential into 1

The following Python code illustrating the idea, and possibly the implementation
```python
from dataclasses import dataclass
from typing import TypeVar


class Sequential(list):
    def __add__(self, other):
        if isinstance(other, __class__):
            return __class__([*self, *other])
        else:
            raise TypeError(f"unsupported operand type(s) for +: {type(self)} and {type(other)}")
        

@dataclass
class Module(object):
    name: str = ""
    
    
if __name__ == '__main__':
    a = Module(name="a")
    b = Module(name="b")
    c = Sequential([a, b])
    
    d = Module(name="d")
    e = Module(name="e")
    g = Sequential([d, e])
    
    f = c + g
    print(f)
```
## The benefit(s)

- Improve readability
- Less code, more productive 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345

**Comment by jbschlosser** [comment]
Hey @dinhanhx, thanks for the detailed request! Seems like a cool idea, but we're fairly conservative with adding new syntactic sugar. I'll bring this up internally to see what others think.

**Comment by dinhanhx** [comment]
@jbschlosser I shall wait patiently then

**Comment by jbschlosser** [comment]
@dinhanhx We discussed this internally and decided that we'd like to in general follow Python semantics. While Python defines `|` for dicts (see [here](https://peps.python.org/pep-0584/)), it notably does not define the union set operator for lists, and conceptually, `nn.Sequential` is more similar to a python list.

I think we'd be more likely to accept an implementation of `Sequential.__add__` for adding two `Sequential`s, following similar add semantics for lists.

**Comment by dinhanhx** [comment]
@jbschlosser I use `|` because I often perceive `nn.Sequential` like UNIX pipe operator. I agree with you on using `+`. So should I close this issue or edit this one to propose `+`?

**Comment by jbschlosser** [comment]
@dinhanhx I think it's fine to edit this one :)

**Comment by dinhanhx** [comment]
@jbschlosser I have edited the issue.

**Comment by jbschlosser** [comment]
Thanks for the update! I think that, also in line with python's list, we only want to support `Sequential + Sequential` and not `Sequential + Module`. We'd accept a PR implementing the former if you'd like to contribute :)

**Comment by dinhanhx** [comment]
@jbschlosser so I just edited the issue to make it's just about `Sequential + Sequential`. Can one of you add the feature? Sorry I don't think I'm confident enough to do so.

**Comment by jbschlosser** [comment]
On our side we're unfortunately very busy so it's hard to prioritize this, but I'm happy to review the PR if anyone is willing to implement it.

**Comment by khushi-411** [comment]
Hi, I'm picking up this issue! Looks interesting to me. Will send a PR soon :) Thanks!

**Comment by jaketae** [comment]
This seems interesting! Linking a previous RFC thread that discusses related higher-level questions: https://github.com/pytorch/pytorch/issues/71329. I think it would be helpful to extend this discussion to think about specific operations we would like to support for container classes.

**Comment by anshradh** [comment]
Hello! Is it possible for me to pick this up? I have changes working locally for this feature request, as well as other magic method implementations to extend the similarity between Sequential and python lists.

**Comment by khushi-411** [comment]
Hi, @anshradh! Thanks for your interest :) Unfortunately, I started working on this late back. But I got busy with some other task and forgot to commit. Could you please work on adding another feature? I want to work on this. Thank you!

**Comment by anshradh** [comment]
No worries! If there's interest in similar support for __iadd__, __mul__, __rmul__, and __imul__ methods, I can submit a PR for those, but you're of course welcome to make those changes as well!
