### ISSUE TITLE
MPS matrix multiplication fails on a permuted tensor without `contiguous`

### ISSUE THREAD

**Issue by danieldk** [pytorch/pytorch#78511]
### 🐛 Describe the bug

Matrix multiplication does not return correct results with a permuted tensor with the MPS backend. Reproducer:

```
import torch

batch_size = 32
n = 20
hidden = 768
num_attention_heads = 12
attention_head_size = hidden // num_attention_heads

def transpose_for_scores(x: torch.Tensor) -> torch.Tensor:
    new_x_shape = x.size()[:-1] + (num_attention_heads, attention_head_size)
    x = x.view(new_x_shape)
    return x.permute(0, 2, 1, 3)

def attention(query, key, *, workaround=False):
    key = transpose_for_scores(key)
    query = transpose_for_scores(query)

    if workaround:
        return torch.matmul(query, key.contiguous().transpose(-1, -2))
    else:
        return torch.matmul(query, key.transpose(-1, -2))

A = torch.randn(batch_size, n, hidden)
B = torch.randn(batch_size, n, hidden)

A_mps = A.to("mps")
B_mps = B.to("mps")

print(torch.allclose(attention(A, B), attention(A_mps, B_mps).cpu()))
print(torch.allclose(attention(A, B), attention(A_mps, B_mps, workaround=True).cpu()))
```

Output:

```
False
True
```

Expected output:

```
True
True
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+git9dc6d42
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.4 (main, May 26 2022, 08:19:39) [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.0a0+git8f7e379
[conda] Could not collect

**Comment by DenisVieriu97** [comment]
@danieldk, thanks for reporting this issue. 
This has been fixed in https://github.com/pytorch/pytorch/commit/5630f979b83dfe0110b7292c2963dc6023ec4116. Please let me know if you are still seeing any issues.
Binaries found at: https://hud.pytorch.org/commit/pytorch/pytorch/4858c56334aa2b09b1ba10d0a3547ef01edda363.

**Comment by danieldk** [comment]
Awesome! This works as well. I can now do inference with the HF BERT model without any changes. 🎉
