### ISSUE TITLE
Adding support for unsqueeze to fake tensors

### ISSUE THREAD

**Issue by edwardjhu** [pytorch/pytorch#78534]
### 🚀 The feature, motivation and pitch

We are using `torchdistx.deferred_init` to infer shapes of model parameters without instantiating the (potentially large) model. The shapes are used to determine an optimal scaling that transfers training hyperparameters. (See https://github.com/microsoft/mup for details.)
However, the `unsqueeze` operation, which is common in many models, isn't supported yet. We'd love to have it supported so `deferred_init` could be the default option in our package since model instantiation isn't needed in our case. Thanks in advance!

@cbalioglu @thegregyang

### Additional context

The error we got when using `deferred_init` on a model with an `unsqueeze` operation:

*** NotImplementedError: aten::unsqueeze cannot be run with fake tensor(s) because the meta backend has no kernel for it. Please file an issue if you want it to be supported.

**Comment by Chillee** [comment]
cc: @ezyang @eellison

**Comment by ezyang** [comment]
can you try running on master? It seems like unsqueeze should be supported

**Comment by ezyang** [comment]
on master

```
import torch
from torchdistx import deferred_init

m = deferred_init.deferred_init(lambda: torch.unsqueeze(torch.empty(2), 0))
print(m)
```

gives

```
tensor(..., size=(1, 2), fake=True)
```

**Comment by edwardjhu** [comment]
Thanks for the speedy response! We are switching to master and will report back if it works!

**Comment by edwardjhu** [comment]
Confirmed that it works. Thanks again!

**Comment by cbalioglu** [comment]
@edwardjhu I also recommend using the latest torchdistx nightlies. Last week we merged a fix that resolved an issue related to a new feature introduced in PyTorch.
