### ISSUE TITLE
linux-focal-py3.7-gcc7-mobile-lightweight-dispatch-build frequently ooms

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#78540]
Seeing a lot of failures on master where this job is exiting with code 137, which google tells me is Docker's exit code when a container runs out of memory and is killed.

Examples:
- https://github.com/pytorch/pytorch/runs/6674725260?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/6674694392?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/6629200575?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/6621404514?check_suite_focus=true

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
@kit1980, you introduced this job. Can you take a look?

**Comment by suo** [comment]
@larryliu0820: you are the person who introduced this job. Can you take a look as well?

**Comment by kit1980** [comment]
Can we remove the job, do we still need it?
If we can't remove, we probably need to raise available memory.
Not sure why it's out of memory only once in a while, maybe ccache related?

**Comment by suo** [comment]
What is this build doing that's taking so much memory? I wouldn't expect it to *actually* require that much more, given that all our other builds fit just fine on a linux.2xlarge host.

**Comment by larryliu0820** [comment]
I don't think we should remove this, it's covering a workflow being used in production. I think it is oom because we don't do selective build. Let me see if I can fix it with selective build.

**Comment by suo** [comment]
Okay, let me know your progress. I will put up a PR to disable this job for now (as it's our policy for flaky tests in CI). We can re-enable it upon fixing

**Comment by larryliu0820** [comment]
@suo Yes it's on my radar. I will take a look today

**Comment by larryliu0820** [comment]
#78983

**Comment by malfet** [comment]
One more OOM: https://github.com/pytorch/pytorch/runs/6798831777?check_suite_focus=true

**Comment by kit1980** [comment]
The issue should be fixed by https://github.com/pytorch/pytorch/pull/78983
The check was re-enable by that PR, so whoever sees OOM in CI needs to rebase past that PR.
Closing the issue for now as trunk HUD shows all green fro the job.

**Comment by malfet** [comment]
@kit1980 before closing the issue, can you please explain how #78983 fixes the OOM in the first place? I.e. it builds smaller package and as so lowers the probability, but it does nothing to address the underlying cause, does it?

**Comment by larryliu0820** [comment]
Yes. Lightweight dispatch generates more code than vanilla PyTorch codegen (with `RegisterCodegenUnboxedKernels.cpp` and `UnboxingFunctions.cpp`), to trade with static initialization time schema parsing for better performance. Since we are generating more code, it's probably taking more resources such as memory to compile these files. The PR added selective build to the test suite that covers lightweight dispatch, so that we only generate code for operators specified in the yaml file. This largely reduces the size of the generated code. We can keep the issue open for a while and see if OOM still happens.

**Comment by larryliu0820** [comment]
#79215 retry

**Comment by suo** [comment]
fwiw this job is still disabled

**Comment by larryliu0820** [comment]
> fwiw this job is still disabled

I forgot to enable it in the retry PR. I’ll do it soon. Feel free to submit a PR if you have time.

**Comment by larryliu0820** [comment]
I see there’s some mixup in my retry PR. I’ll fix it
