### ISSUE TITLE
torch.svd_lowrank fails for complex matrices

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/pytorch#78605]
The reason is that the function get_floating_dtype from _linalg_utils returns torch.float32 on complex input instead of torch.cfloat or torch.cdouble as appropriate.  This is in version 1.11.0.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @jianyuh @pearu @walterddr @IvanYashchuk @xwang233

**Comment by Lezcano** [comment]
@nikitaved

**Comment by redwrasse** [comment]
Looks to me this has been fixed? The latest code I see on `viable/strict` shows
`dtype = _utils.get_floating_dtype(A) if not A.is_complex() else A.dtype` in the `get_approximate_basis` function. And `test_svd_lowrank` passes on both `torch.double` and `torch.cdouble` in `test_svd_lowrank` in test_linalg.py.

**Comment by lezcano** [comment]
Yes, this was fixed inhttps://github.com/pytorch/pytorch/pull/125580. Closing
