### ISSUE TITLE
Expanded view does not correctly transfer to MPS device

### ISSUE THREAD

**Issue by danieldk** [pytorch/pytorch#78642]
### 🐛 Describe the bug

```
>>> import torch
>>> torch.tensor(1).expand([10]).to("mps")
tensor([                  1,                   0, 5764607523034234880,
        2305843009539677330,          1900544002,     562949953421312,
                          7,          5218224200,     105553124803760,
                 9760927536], device='mps:0')
```

Expected output:

```
>>> import torch
>>> torch.tensor(1).expand([10]).to("mps")
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], device='mps:0')
```

### Versions

PyTorch version: 1.13.0a0+git9dc6d42
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.4 (main, May 26 2022, 08:19:39) [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.0a0+git619db91
[conda] Could not collect

cc @kulinseth @albanD

**Comment by DenisVieriu97** [comment]
@danieldk, this has been fixed in 5630f979b83dfe0110b7292c2963dc6023ec4116. Could you please let me know if you are still seeing the issue? Binaries are found at: https://hud.pytorch.org/commit/pytorch/pytorch/4858c56334aa2b09b1ba10d0a3547ef01edda363.
