### ISSUE TITLE
[PyTorch] [ONNX] Peephole optimizer transpose fusion broken

### ISSUE THREAD

**Issue by jekbradbury** [pytorch/pytorch#7868]
With
```
class Test(torch.nn.Module):
    def forward(self, x):
        return x.transpose(1, 2).transpose(0, 1)
```
we have
```
>>> torch.onnx.export(Test(), torch.rand(2, 3, 5), 'test.onnx', verbose=True)
graph(%0 : Float(2, 3, 5)) {
  %1 : Float(5!, 2, 3!) = onnx::Transpose[perm=[1, 2, 0]](%0), scope: Test
  return (%1);
}
```
when we expect `Transpose[perm=[2, 0, 1]](%0)` or an equivalent.
So one of the transformations in https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/onnx/peephole.cpp is wrong.

cc @ryanleary

**Comment by jamesr66a** [comment]
Try this on for size https://github.com/pytorch/pytorch/pull/7872

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/7872
