### ISSUE TITLE
[ONNX] Refactor the patching process to make it more transparent to users

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#78694]
`torch.onnx` patches _C.Graph with `_patch_torch`. We would like to make the behavior more transparent and controllable.

This is an issue for tracking the TODO item.

**Comment by thiagocrepaldi** [comment]
@justinchuby have you done already or this is another work? is it still relevant? will leave open for visibility

**Comment by justinchuby** [comment]
Done!
