### ISSUE TITLE
fx proxy retracing example is incorrect

### ISSUE THREAD

**Issue by gilfree** [pytorch/pytorch#78705]
### 📚 The doc issue

The code example in https://pytorch.org/docs/stable/fx.html#proxy-retracing seems to be incorrect. It adds the decomposed nodes to the old `graph` instead of to `new_graph`.  The created model does not pass `graph.lint`

### Suggest a potential alternative/fix

Change     
```tracer = torch.fx.proxy.GraphAppendingTracer(graph)```

To
```tracer = torch.fx.proxy.GraphAppendingTracer(new_graph)```

cc @ezyang

**Comment by ezyang** [comment]
fixed
