### ISSUE TITLE
Make `torch.Library` (Python Registration) work with torchdeploy

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#78728]
### 🚀 The feature, motivation and pitch

Python Registration is not compatible with torchdeploy; to handle torchdeploy, we must introduce a level of indirection whereby there is a single registered kernel for all Python interpreters, but it then determines whether or not to fallthrough to the base implementation based on whether or not the registration happened from a matching interpreter
or not. We also need to ensure that if the old implementation for the dispatch key in question was just a fallthrough, then it still has the correct behavior.

cc @ezyang @gchanan @zou3519 @wconstab @anjali411

**Comment by anjali411** [comment]
Hi pri because prims and other features have started using python registration, and are incompatible with torchdeploy in its current state

**Comment by bdhirsh** [comment]
Do we want to fully support being able to register different kernels from differnt python interpreters? Or are we ok with banning that, and we just want to get some version of python registration working properly with `torch::deploy` (the first might be harder to implement without hurting hot-path perf).

**Comment by anjali411** [comment]
> Maybe there are obvious reasons why we wouldn't want to do this? But if not, maybe this would simplify the implementation?

We shouldn't do this because the actual impl function is in python and should only be accessed by its matching py interpreter.

**Comment by wconstab** [comment]
> maybe we can have each py interpreter make copies of the function and error out if the function has a nonlocal state?

hmm, i think we could inspect the bytecode of the function and error if it has any global accessess.

but, even if we make the replication of the function across interpreters 'automatic', don't we still have to introduce some layer of abstraction to let there be multiple pyobj backing one registered function?  If we are ok with having that map of pyobjs, then it might be ok to skip the fancy function-copying and just make it an error if you try to use an op on an interpreter without first calling registration there.

**Comment by ezyang** [comment]
You should support completely different; I would claim that it is more difficult to have them leak over

**Comment by ezyang** [comment]
It has ties to C++ state because we register into the dispatcher which is shared across all processes.

Custom C++ ops feels like it should be ok if the custom op libraries could in principle all be loaded together...

**Comment by d4l3k** [comment]
A lot of these custom C++ ops are loaded from Python C extensions that can be installed from pip etc so we can't grab them upfront. This works in many cases but it causes significant issues during teardown since operators may be registered in a subinterpreter so when the code is unloaded you end up with dangling pointers in libtorch. libtorch_python has a number of operators that are registered per interpreter i.e. RPC ops that depend on accessing the currently running Python interpreter

**Comment by anjali411** [comment]
closing this since https://github.com/pytorch/pytorch/pull/87162 makes deploy work with python registration/ `torch.Library`.
