### ISSUE TITLE
Wrong import in datasets documentation

### ISSUE THREAD

**Issue by thomasahle** [pytorch/pytorch#78745]
### 📚 The doc issue

In https://pytorch.org/torchrec/torchrec.datasets.html we see the code
```
from torchrec.datasets.criteo import criteo_kaggle
datapipe = criteo_terabyte(...
```

### Suggest a potential alternative/fix

It should probably either import criteo_terabyte or use criteo_kaggle. Not the current mixture.
Also it would be nice to see where `dp` is imported from.

**Comment by soulitzer** [comment]
You might want to file in the torch rec repo instead: https://github.com/pytorch/torchrec instead
