### ISSUE TITLE
c extension link error in win10

### ISSUE THREAD

**Issue by xiaoxiangyeyuwangye** [pytorch/pytorch#7877]
Hi everyone
I'm trying to build the c extension in win10, and did it as the follow link.
https://pytorch.org/tutorials/advanced/c_extension.html
But when I run build.py, link errors rasied

`
my_lib.obj : error LNK2001: unresolved external symbol __imp_THFloatTensor_fill

my_lib.obj : error LNK2001: unresolved external symbol __imp_THFloatTensor_resizeAs

my_lib.obj : error LNK2001: unresolved external symbol __imp_THFloatTensor_isSameSizeAs

my_lib.obj : error LNK2001: unresolved external symbol __imp_THFloatTensor_cadd

.\_my_lib.pyd : fatal error LNK1120: 4 unresolved externals
`
Does anyone have any idea about it?

**Comment by Mikerr1111** [comment]
Some helpful information to know would be your Windows 10 build(1709 or 1803) and version of Python(2.7 or 3.4+) are you using.

**Comment by xiaoxiangyeyuwangye** [comment]
I solved this problem with the method in this page.
https://pytorch.org/docs/stable/notes/windows.html#cffi-extension
