### ISSUE TITLE
[collect_env] collect_env python < 3.6 incompatibility 

### ISSUE THREAD

**Issue by mo-arvan** [pytorch/pytorch#78840]
### 🐛 Describe the bug

Recent changes in `collect_env.py` include using f-strings, a feature that has been introduced with PEP 498 (https://peps.python.org/pep-0498/#how-to-denote-f-strings). This file is currently incompatible with python versions below 3.6. 

```bash
docker run -it python:3.5.10-slim-buster bash

# Inside the docker
apt update && apt install -y wget
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
python collect_env.py
```
This will result in the below error:
```bash

  File "collect_env.py", line 92
    out = run_and_read_all(run_lambda, f"{conda} list")
                                                     ^
SyntaxError: invalid syntax
```
If the [goal](https://github.com/pytorch/pytorch/blob/b7cb4eae6b16ce312fb5e285aa82f227be6549a6/torch/utils/collect_env.py#L3) is to maintain the compatibility with earlier versions of python, we need to update this file. 

### Versions

The irony, I had to use future_fstrings to run this file. 

```
python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 9 (stretch) (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.2.5

Python version: 2.7.18 (default, Apr 20 2020, 19:45:25)  [GCC 6.3.0 20170516] (64-bit runtime)
Python platform: Linux-5.11.0-25-generic-x86_64-with-debian-9.12
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip] No relevant packages
[conda] Could not collect

```

**Comment by malfet** [comment]
Hmm, we test `collect_env` to be usable without PyTorch, but looks like we never check that it is actually python-2 compatible....

**Comment by mo-arvan** [comment]
I'd be happy to make the necessary changes and submit a pull request.

**Comment by seemethere** [comment]
Should we just make it error out if you're testing with an unsupported version?

**Comment by seemethere** [comment]
Added https://github.com/pytorch/pytorch/pull/78946 to test for python 3.5 and make it compatible

**Comment by seemethere** [comment]
Closing with https://github.com/pytorch/pytorch/pull/78946
