### ISSUE TITLE
Fit data into PyTorch RNN

### ISSUE THREAD

**Issue by FiammettaC** [pytorch/pytorch#7885]
Hi, I am new to PyTorch and I am trying to train a simple LSTM.

My input is the following: 
X_train: list of vectorized sentences, padded to the same length, shape=(5441, 55)
y_train: list of list of labels converted to categorical, shape=(5441, 13122)

I have some difficulties understanding if I have to modify the data in some ways or I can just fit it into my network.

I was following this tutorial: [https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/02-intermediate/recurrent_neural_network/main.py#L38-L56](url)

So, I defined the following network:

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

sequence_length = 55 #28
input_size = 5441 #28
hidden_size = 128
num_layers = 2
num_classes = vocab_size #10
batch_size = 100
num_epochs = 2
learning_rate = 0.01

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, num_classes):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, num_classes)
    
    def forward(self, x):
        # Set initial hidden and cell states 
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device) 
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        
        # Forward propagate LSTM
        out, _ = self.lstm(x, (h0, c0))  # out: tensor of shape (batch_size, seq_length, hidden_size)
        
        # Decode the hidden state of the last time step
        out = self.fc(out[:, -1, :])
        return out

model = RNN(input_size, hidden_size, num_layers, num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

total_step = len(X_train)
for epoch in range(num_epochs):
    for i, data in enumerate(X_train):

        data = Variable(torch.from_numpy(np.array(X_train)).float())
        labels = Variable(torch.from_numpy(np.array(y_train)).float())
        
        # Forward pass
        outputs = model(data)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

But I get this error: TypeError: new() received an invalid combination of arguments - got (dict, int), but expected one of:
 * (torch.device device)
 * (tuple of ints size, torch.device device)
      didn't match because some of the arguments have invalid types: (dict, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, torch.device device)
      didn't match because some of the arguments have invalid types: (dict, int)

Can anybody help me understand what input to pass to the network? Thanks!

**Comment by crcrpar** [comment]
Hi, @FiammettaC 
I recommend you post this also on [PyTorch forum](https://discuss.pytorch.org/), where you can get a lot help for debugging, enhancement

**Comment by zou3519** [comment]
Please post on the forums!

https://pytorch.org/docs/master/nn.html?highlight=lstm#torch.nn.LSTM

^ the docs say there should be two inputs. The first is `input` and the second is a tuple of tensors (h0, c0) that are the initial hidden and cell states
