### ISSUE TITLE
Functionality that utilizes all GPU devices on a local PC

### ISSUE THREAD

**Issue by xlpiao** [pytorch/pytorch#78872]
### 🚀 The feature, motivation and pitch

I am looking for the functionality that uses all GPU devices on a local PC. If a PC supports both Intel and Nvidia GPU, then utilize all the devices. I am quite interested in it. It seems that this feature is not supported currently. Is it going to be supported or is it working in progress? 

For example:
```python
device = torch.device("all") ## get all available GPUs
x = torch.ones(4096)
y = torch.ones(4096)
z_gpu = torch.add(x + y, device=device) ## split task and schedule internally
z_gpu = torch.add(x + y, device=device[0], batch_size=1024) ## or provide splitting options
z_cpu = z_gpu.to("cpu")
print(z_gpu)
print(z_cpu)
```

**Comment by ezyang** [comment]
We don't support Intel GPUs, so can't do it
