### ISSUE TITLE
Elementwise multiplication between MPS float32 and int Tensors result in LLVM error

### ISSUE THREAD

**Issue by danieldk** [pytorch/pytorch#78879]
### 🐛 Describe the bug

Elementwise operations between MPS float and integer(-like) tensors fail with an LLVM error. For example:

```
>>> import torch
>>> torch.arange(5, dtype=torch.float32, device="mps") * torch.tensor([True, False, True, False, True], device="mps")
loc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): error: input types 'tensor<5xf32>' and 'tensor<5xi1>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
[...]
>>> torch.arange(5, dtype=torch.float32, device="mps") * torch.tensor([1, 0, 1, 0, 1], device="mps")
loc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): error: input types 'tensor<5xf32>' and 'tensor<5xi64>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
[...]
>>> torch.arange(5, dtype=torch.float32, device="mps") + torch.tensor([1, 0, 1, 0, 1], device="mps")
loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): error: input types 'tensor<5xf32>' and 'tensor<5xi64>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
```

It looks like an implicit conversion to the `float32` type is missing.

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+git844368c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.4 (main, May 26 2022, 08:19:39) [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.0a0+gite8b8a9f
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @nairbv @mruberry @kulinseth @albanD

**Comment by kulinseth** [comment]
Can you please check whether this works with latest nightly. We have tested and it works locally.
