### ISSUE TITLE
[Python 3/Pytorch] Error on Fine-tuning BERT for question answering -> RuntimeError: Overflow when unpacking long

### ISSUE THREAD

**Issue by maria364** [pytorch/pytorch#78925]
### 🐛 Describe the bug

While trying to fine-tune a BERT model on COVID-QA dataset for the question answering task, the following error has occurred. 
_RuntimeError: Overflow when unpacking long_
The instructions I am following are on [this](https://huggingface.co/transformers/v3.2.0/custom_datasets.html#qa-squad) link.
The error seems to occur on the following line: ` return {key: torch.tensor(val[idx],dtype=torch.int64) for key, val in self.encodings.items()}`

I am trying to train the model on an ubuntu server, using python 3.6.6 and PyTorch 1.10.0+cu102 (using 1 GPU)

Can anyone help?

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.9

Python version: 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-180-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX

Nvidia driver version: 470.129.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0+cu113
[pip3] torchvision==0.11.1+cu113
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torch                     1.3.0                    pypi_0    pypi
[conda] torchaudio                0.10.1                   pypi_0    pypi
[conda] torchvision               0.11.2                   pypi_0    pypi

**Comment by ezyang** [comment]
This is probably not a framework problem, I suggest going to https://discuss.pytorch.org/

**Comment by ezyang** [comment]
r
