### ISSUE TITLE
[Caffe2] Update the download-site of eigen in previous caffe2

### ISSUE THREAD

**Issue by linrio** [pytorch/pytorch#7893]
The eigen submodule is uavailable for old caff2, the PR is [caffe2](https://github.com/caffe2/caffe2/pull/2525). Sometimes I need to use the previous caffe2. Could update the download-site?

**Comment by linrio** [comment]
The url of eigen module in _caffe2/.gitmodules_ line 10 is unreachable in previous [caffe2](https://github.com/caffe2/caffe2):
```
[submodule "third_party/eigen"]
	path = third_party/eigen
	url = https://github.com/RLovelett/eigen.git 
```

yeah this problem has been fixed in pytorch-caffe2  by [new url](https://github.com/pytorch/pytorch/blob/master/.gitmodules) in _pytorch/.gitmodules_ line 17:

```
[submodule "third_party/eigen"]
	path = third_party/eigen
	url = https://github.com/eigenteam/eigen-git-mirror.git
```

I expect that the previous caffe2 can be updated.

**Comment by pjh5** [comment]
@linrio the old Caffe2 repo is not maintained anymore, as the entire code has been copied to the Pytorch repo and is under further development in the Pytorch repo. Why do you need the old Caffe2 repo? As far as I know there were no breaking changes in the repo migration, and the Caffe2 under the Pytorch repo should always work for people who just want the Caffe2 part.

**Comment by pjh5** [comment]
Closing in since we do not consider this to be an issue.
