### ISSUE TITLE
[bot] Improve mergebot logging

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#78940]
### 🐛 Describe the bug

Several merge workflows have been stuck but there are no logs printing so we don't have insight on what's going on.

e.g., https://github.com/pytorch/pytorch/runs/6759322467?check_suite_focus=true for a merge -f workflow.

We should do the following:
- [ ] print every important action that goes on
- [ ] constantly print a dot so we know something is happening
- [x] notify GH about printing logs for pending steps (since we should be printing every 60s or so)

### Versions

CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Closing this task. When we feel we need some new logs we'll add it
