### ISSUE TITLE
Fully decommission grafana (metrics.pytorch.org) for hud.pytorch.org/metrics

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#78951]
In order to fully decommission Grafana, we need to:

Port over significant metrics
- [x] KPIs page
- [x] Failure classification for things on trunk <img width="567" alt="image" src="https://user-images.githubusercontent.com/31798555/172219611-85b2d92a-9132-4f0f-9cc5-d95daa6c5617.png">

And finally:
- [x] Point metrics.pytorch.org to hud.pytorch.org/metrics
- [ ] Decommission the server
- [ ] Verify RDS database doesn't exist (or if it is, that it isn't used by rockset).  Only if it is, then also do the below steps:

If RDS database exists:
- [ ] Verify we don't emit metrics to RDS database (we prob don't)
- [ ] Stop any lambda that might be publishing to the RDS database (there prob aren't any)
- [ ] Decommission metrics RDS database

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by atalman** [comment]
cc @janeyx99  I updated certificate on metrics, it will expire in Oct 28 2022. We should try to complete this task before that time

**Comment by atalman** [comment]
@ZainRizvi could you please let me know if its possible to drop following points:
- Failure classification for things on trunk
- KPIs page
in order to deprecate this website ?

**Comment by atalman** [comment]
We need to remove test-infra jobs, generated-update-grafana-dashboards : https://github.com/pytorch/test-infra/actions/workflows/generated-update-grafana-dashboards.yml

**Comment by ZainRizvi** [comment]
Remaining tasks:
- Remove all workflows associated with grafana's databases

So far what's known are:

Workflow which deploys the lambda which actually writes to RDS: https://github.com/pytorch/test-infra/blob/main/aws/lambda/github-webhook-rds-sync/Makefile#L7

The lambda it deploys to: https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions/github-webhook-rds-sync-app?tab=configure

The RDS db it uses: pytorch-rds-2.xxxxxx.us-east-1.rds.amazonaws.com/pytorch

**Comment by ZainRizvi** [comment]
Workflows, lambdas, and rds db are now removed & deleted
