### ISSUE TITLE
test_fsdp_pure_fp16 test breaks when using more than 5 GPUs (1.11 and 1.12)

### ISSUE THREAD

**Issue by Micket** [pytorch/pytorch#78975]
### 🐛 Describe the bug

When enabling 6 or more (out of the 8) T4 GPUs on my compute nodes, I'm seeing `test_fsdp_pure_fp16` fail with

```
ERROR:torch.testing._internal.common_distributed:Caught exception: 
Traceback (most recent call last):
  File "/apps/Arch/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 601, in run_test
    getattr(self, test_name)()
  File "/apps/Arch/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 486, in wrapper
    fn()
  File "/apps/Arch/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 207, in instantiated_test
    test(self, **param_kwargs)
  File "/apps/Arch/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/testing/_internal/common_distributed.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "/cephyr/users/ohmanm/Alvis/test_fsdp_pure_fp16.py", line 98, in test_pure_fp16
    self.assertEqual(ddp_state, fsdp_state)
  File "/apps/Arch/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 2121, in assertEqual
    assert_equal(
  File "/apps/Arch/software/PyTorch/1.11.0-foss-2021a-CUDA-11.3.1/lib/python3.9/site-packages/torch/testing/_comparison.py", line 1080, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 4 (25.0%)
Greatest absolute difference: 0.0001220703125 at index (1, 0) (up to 1e-05 allowed)
Greatest relative difference: 0.0014492753623188406 at index (1, 0) (up to 0.001 allowed)
```

Looking at the tensors produced, all numbers look slightly off, but one was sufficient to trip the error. The size of the errors and all values seem identical regardless of if 6, 7, or 8 GPUs are used. When using 5 or fewer GPUs, the ddp_state and fsdp_state are identical.

Comparing the tensors <=5 and >5 GPUs, i can see that it is `fsdp_state` that changes.
It happens identically for both `CPUOffload(offload_params=True)`  and `CPUOffload(offload_params=False)`.

I've tested a custom EasyBuild build, as well as the docker images `pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel` and `nvcr.io/nvidia/pytorch:22.04-py3` (which is version 1.12) via singularity using test script (https://github.com/pytorch/pytorch/blob/release/1.11/test/distributed/fsdp/test_fsdp_pure_fp16.py and 1.12 version respectively).
The exact same errors occur, with the exact same greatest absolute and relative differences.

I don't really know what i'm doing, but i tried digging for the source of the difference.
The `out` tensor looks identical at least.
https://github.com/pytorch/pytorch/blob/8d365ae9402179399e49090f1523bf33bea6ba3a/test/distributed/fsdp/test_fsdp_pure_fp16.py#L71
The only difference i could spot is that at >5 GPUs, the FSDP parameters become single 1x1 tensors.

Perhaps i should not expect this to work? If so, perhaps it needs another activation condition to only run on less than 6 GPUs?

### Versions

(error also present in docker and NGC containers, both version 1.11 and 1.12. Didn't test any other versions)

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.5 (Green Obsidian) (x86_64)
GCC version: (GCC) 10.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.9.5 (default, Feb 20 2022, 22:56:19)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-348.23.1.el8_5.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4
GPU 5: Tesla T4
GPU 6: Tesla T4
GPU 7: Tesla T4

Nvidia driver version: 515.43.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.11.0
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by Flamefire** [comment]
I can confirm this on a PPC node with 6 V100s
