### ISSUE TITLE
[ONNX] scatter_add result is wrong in ONNX model

### ISSUE THREAD

**Issue by zhang0557kui** [pytorch/pytorch#79005]
### 🐛 Describe the bug

scatter_add result is wrong in ONNX model

### Versions

scatter_add result is wrong in ONNX model

cc @mikaylagawarecki

**Comment by samdow** [comment]
Hi! Could you provide a repro for this? Thanks!

**Comment by BowenBao** [comment]
Duplicate of #32960, closing.

`scatter_add` will be properly supported in opset 16 export soon.

**Comment by zhang0557kui** [comment]
scatter_add result is still wrong in ONNX format model by onnxruntime's  inference
