### ISSUE TITLE
Fix overload resolution for SymInt[] and int[] in python_arg_parser.cpp

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/pytorch#79023]
I had to make parsing of int[] suboptimal since a python object can now be parsed as both an int and a `SymbolicIntNode`, so we can't pick the int overload unless we scan through all the objects in a list and confirm there are no nodes.
more details here:

https://github.com/pytorch/pytorch/pull/78135/files#r887418452

**Comment by ezyang** [comment]
we're going to live with the sniffing the rest of the list
