### ISSUE TITLE
[ONNX] CI does not catch an error in `to_device`

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#79035]
### 🐛 Describe the bug

An error introduced in https://github.com/pytorch/pytorch/pull/78085 should have failed [the check in ci](https://github.com/pytorch/pytorch/runs/6516120818?check_suite_focus=true) but did not. This is from the discussion of https://github.com/pytorch/pytorch/pull/78114.

The test expected to fail is `test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset13::test_to_device`

### Versions

NA

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by BowenBao** [comment]
> Although I don't know why the tests passed. Do we set _CAFFE2_ATEN_FALLBACK differently in CI?

from https://github.com/pytorch/pytorch/pull/78114#issuecomment-1148046883

@AllenTiTaiWang I think this issue might turn out to be related to the Caffe2 flag & CI problem that you are looking at.

**Comment by AllenTiTaiWang** [comment]
cc @thiagocrepaldi

**Comment by abock** [comment]
We need to build in CI with both:

```
BUILD_CAFFE2=0
BUILD_CAFFE2=1
```

**Comment by AllenTiTaiWang** [comment]
I will look into the issue, and close as it's tracked in internal issue.

**Comment by titaiwangms** [comment]
Addressed by #90475 that CI test now including built without CAFFE2
