### ISSUE TITLE
Add operator and derivative coverage for nestedtensors

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#79044]
### Summary
Compared to the out of tree nested_tensor impl: https://github.com/pytorch/nestedtensor core does not have as many nestedtensor implementations.  As well since the out of tree version did not support autograd the derivative implementations are not defined yet.  

#### Factory Functions:
- [x] _nested_tensor_from_mask
- [x] _nested_tensor_from_padded
- [x] to_padded_tensor
- [x] nested_tensor

#### MHA Ops:
- [x] linear

#### Other Ops
- [x] numel

### Linked PR:
- #79872
- #80424
- #80397

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @cpuhrsch

**Comment by soulitzer** [comment]
Looks like this is completed
