### ISSUE TITLE
[CI] Flaky initialization of OMP

### ISSUE THREAD

**Issue by robieta** [pytorch/pytorch#79055]
### 🐛 Describe the bug

CI sometimes fails with the message:
```
OMP: Error #15: Initializing libiomp5.so, but found unknown library already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see [http://www.intel.com/software/products/support/.](http://www.intel.com/software/products/support/)
```

[Example](https://github.com/pytorch/pytorch/runs/6777337613?check_suite_focus=true#step:9:677) from https://github.com/pytorch/pytorch/pull/78164. When I [rerun](https://github.com/pytorch/pytorch/runs/6780424827?check_suite_focus=true) the issue did not appear. 

Looks like it could be related to https://github.com/pytorch/pytorch/issues/78490

### Versions

N/A

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
I don't think this has occurred recently anymore. Closing due to that fact. Please re-open if you see any more instances to this.
