### ISSUE TITLE
mark_shared_storage is deprecated

### ISSUE THREAD

**Issue by yangsuxia** [pytorch/pytorch#7906]
When I use pytorch, there will be an alarm as follows:

anaconda3/envs/python36/lib/python3.6/site-packages/torch/autograd/function.py:41: UserWarning: mark_shared_storage is deprecated. Tensors with shared storages are automatically tracked. Note that calls to `set_()` are not tracked
  'mark_shared_storage is deprecated. '

THCudaCheck FAIL file=/home/suxia/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
| WARNING: ran out of memory, skipping batch

Will this affect my program  and   Why is there such an alarm？

my enviroment as follows:
python                    3.6.3                   intel_8  [intel]  intel
torch                     0.4.0                     <pip>

Looking forward to your reply. Thank you！

**Comment by apaszke** [comment]
You can safely remove this line now.

**Comment by yangsuxia** [comment]
Ok, I will comment out the warning information there. 

Thank you very much for your reply！
