### ISSUE TITLE
ROCm runlogs are not uplodaed to the hud

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#79074]
### 🐛 Describe the bug

See https://hud.pytorch.org/pytorch/pytorch/commit/d4eebca7bc14b28688914577f690b68313cb846f  which tries to download log from https://ossci-raw-job-status.s3.amazonaws.com/log/6782471314 where they do not exist

### Versions

CI

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
cc @zengk95 @suo @clee2000

**Comment by suo** [comment]
This isn't related to rocm; I think sometimes github just doesn't deliver webhooks.

**Comment by jithunnair-amd** [comment]
Closing this based on above comment.
