### ISSUE TITLE
How to find the code in '...'?

### ISSUE THREAD

**Issue by husterdjx** [pytorch/pytorch#79106]
https://github.com/pytorch/pytorch/blob/4305f8e9bda34f18eb7aacab51c63651cfc61802/torch/storage.py#L34

Here, I want to read the detailed code in `.cuda` func, however, I do not find any code about this api?😢

Hope someone could help me！❤

cc @ngimel

**Comment by ngimel** [comment]
Please ask questions in discuss.pytorch.org
