### ISSUE TITLE
How to implement the internal zero padding for the feature map?

### ISSUE THREAD

**Issue by PkuRainBow** [pytorch/pytorch#7911]
I want to implment such padding operations within the pytorch framework.

The traditional padding operations add zero at the boundary of the feature maps.

I am wondering how can I insert zero between the feature map.

Such as I have 5x5 feature map like:

```
1 2 3 4 5
2 3 4 5 1
3 4 5 1 2
4 5 1 2 3
5 1 2 3 4
```

Then our target is to insert zero between the values within the feature map and we should support various strides, here we assume the padding stride is one, then we should get the feature map like this,

```
1 0 2 0 3 0 4 0 5
0 0 0 0 0 0 0 0 0
2 0 3 0 4 0 5 0 1
0 0 0 0 0 0 0 0 0
3 0 4 0 5 0 1 0 2
0 0 0 0 0 0 0 0 0
4 0 5 0 1 0 2 0 3
0 0 0 0 0 0 0 0 0
5 0 1 0 2 0 3 0 4
0 0 0 0 0 0 0 0 0
```

Could any one show me some cheap method to implement such padding operations?

I find one possible method is to modify the files "pytorch/caffe2/operators/pad_op.cc" and implement a new padding layer to support such operations.

**Comment by SsnL** [comment]
Is this pytorch or caffe2?

**Comment by karandwivedi42** [comment]
Something like this: https://stackoverflow.com/questions/47125884/how-to-insert-zeros-between-elements-in-a-numpy-array

**Comment by PkuRainBow** [comment]
@SsnL  Pytorch

**Comment by PkuRainBow** [comment]
@karandwivedi42 Thanks for your comments

**Comment by SsnL** [comment]
This works as
```py
>>> import torch.nn.functional as F
>>>
>>> def pad_within(x, stride=2):
...   w = x.new_zeros(stride, stride)
...   w[0, 0] = 1
...   return F.conv_transpose2d(x, w.expand(x.size(1), 1, stride, stride), stride=stride, groups=x.size(1))
...
>>> x = torch.arange(8, dtype=torch.float).view(2, 4).expand(1, 3, 2, 4)
>>> x
tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.]],

         [[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.]],

         [[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.]]]])
>>> pad_within(x)
tensor([[[[ 0.,  0.,  1.,  0.,  2.,  0.,  3.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 4.,  0.,  5.,  0.,  6.,  0.,  7.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  1.,  0.,  2.,  0.,  3.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 4.,  0.,  5.,  0.,  6.,  0.,  7.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

         [[ 0.,  0.,  1.,  0.,  2.,  0.,  3.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
          [ 4.,  0.,  5.,  0.,  6.,  0.,  7.,  0.],
          [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]]])

```

you can wrap this in a module to avoid recomputing the weight every time.

**Comment by PkuRainBow** [comment]
@SsnL I got such error ,
`
AttributeError: 'Variable' object has no attribute 'new_zeros'`

Here is my implementation based the code you provide:

```
class PadWithin(nn.Module):
    def __init__(self, stride=2):
        super(PadWithin, self).__init__()
        self.stride = stride
        
    def forward(self, feats):
        self.w = feats.new_zeros(self.stride, self.stride)
        return F.conv_transpose2d(feats, w.expand(feats.size(1), 1, stride, stride), stride=stride, groups=feats.size(1))
```

**Comment by SsnL** [comment]
You should update to 0.4.

**Comment by SsnL** [comment]
also with module you can initialize the weight in __init__

**Comment by PkuRainBow** [comment]
@SsnL Do I need to modify my code overall if I update to 0.4? I use the 0.3 originally~

**Comment by SsnL** [comment]
Most likely it will just work. See https://pytorch.org/2018/04/22/0_4_0-migration-guide.html for suggested changes.

**Comment by PkuRainBow** [comment]
How about this?

```
class PadWithin(nn.Module):
    def __init__(self, stride=2):
        super(PadWithin, self).__init__()
        self.stride = stride
        self.w = torch.zeros(self.stride, self.stride)
        
    def forward(self, feats):
        return F.conv_transpose2d(feats, self.w.expand(feats.size(1), 1, self.stride, self.stride), stride=self.stride, groups=feats.size(1))


```

**Comment by SsnL** [comment]
@PkuRainBow 0.4 solves the problem by merging Variable and Tensor classes. So being a Variable or not won't matter :)

**Comment by NichitaDiaconu** [comment]
@PkuRainBow  In the last version you forgot to add: self.w[0, 0] = 1

**Comment by sssohrab** [comment]
How about this?:

`output = F.conv_transpose2d(input,F.pad(torch.ones(1,1,1,1),(1,1,1,1)),stride=2,padding=1) `
