### ISSUE TITLE
Figure out our memory management story for SymInts

### ISSUE THREAD

**Issue by Krovatkin** [pytorch/pytorch#79134]
Currently, we don't have a very convincing story how we are going to memory manage `SymbolicIntNode` stored in `SymInts`. The current consensus is that the `SymbolicIntNode`s stored in `SymIntTable` need to be cleared manually.
We have three potential backends that would use `SymbolicIntNode`:
* AOTAutograd which has a pretty clear point of when to clear the table. As soon as tracing is done, sym ints aren't needed anymore. TODO: will this work if there are multiple traces going on concurrently @ezyang @Chillee 
* LTC would require users to add an extra call to `optimizer_step` that would clear the table.
* NT TODO: to elaborate how exactly they would like to use `SymbolicIntNode`s

**Comment by ezyang** [comment]
we are refcounting each symint individually now, so there is no more memory management problem. Can optimize into pools if we decide we need to later.
