### ISSUE TITLE
Quantization Aware Training API Example Not Up to Date

### ISSUE THREAD

**Issue by vspenubarthi** [pytorch/pytorch#79135]
### 📚 The doc issue

At the quantization aware training API found at this link: [https://pytorch.org/docs/stable/quantization.html#quantization-aware-training](Quantization Aware Training Section) on the main quantization page, the code that is written doesn't have up to date code that can be run directly. Specifically, all the code up to the `training_loop(model_fp32_prepared)` should theoretically be able to be cut and pasted and run but it throws a `Fusion only for eval!` error when I try to do so.

### Suggest a potential alternative/fix

The fix to make this run properly is to insert after the:

``` 
# create a model instance
model_fp32 = M()
```

add the lines
```
# model must be set to eval mode for fusion to work
model_fp32.eval()
```

2.) Remove the:

```
# model must be set to train mode for QAT logic to work
model_fp32.train()
```

lines and add right above

```
# Prepare the model for QAT. This inserts observers and fake_quants in
# the model that will observe weight and activation tensors during calibration.
model_fp32_prepared = torch.quantization.prepare_qat(model_fp32_fused)
```

add the lines:

```
# model must be set to train mode for QAT logic to work
model_fp32_prepared.train()
```

At a higher level, it would be great if there were also unit tests created for documentation code so it is verified that code that code presented in the examples is mostly copy and use for PyTorch users.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by HDCharles** [comment]
solved with PR https://github.com/pytorch/pytorch/commit/ffdc5eebc7e8baffa9a68f66d14213f52a222d2f
