### ISSUE TITLE
Pin PyTorch nightly used for comparison in BC test

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#79146]
### 🐛 Describe the bug

Today the backwards compatibility test is a common source of spurious failures on pull request because if your pull request is too old then it will not contain all of the operators from the latest nightly and the test will incorrectly assumed that you remove them. Working with our commit hash pinning, I realized that now that we are GH1 we can do something similar for BC test: we will maintain a file that points to the nightly that should be used for the backwards compatibility test and whenever the new nightly is finished building we run a periodic can GitHub actions job to commit to master with an update. WDYT.

cc @seemethere @malfet @pytorch/pytorch-dev-infra 

### Versions

master

**Comment by ezyang** [comment]
Yes that is true.

I don't think PT moves so fast that rebasing 2+ days is always necessary. But the BC tests always run and will always fail if someone adds new ops in master

**Comment by janeyx99** [comment]
Back in the day, I remember we simply checked out the most recent master for this check, instead of the base of the branch. If we're going to be thinking about pinning the branch, should we just go back to checking out latest master + adding a big comment about that?

**Comment by ezyang** [comment]
You mean, merge with master? IIRC people didn't like it because the CI jobs didn't reflect the code you had actually pushed.

**Comment by janeyx99** [comment]
Yeh, oh I guess with a pin the code you pushed is still what you expect and there would be no risk for a merge conflict. Alright. I'm going to give Nikita's suggestion a try.
