### ISSUE TITLE
ONNX tests intermittently ooming on master

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#79179]
Examples:
- https://github.com/pytorch/pytorch/runs/6802382697?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/6803114292?check_suite_focus=true

I assume this is due to test parallelization, @BowenBao can you take a look?

**Comment by BowenBao** [comment]
Not immediately obvious what might be the root cause. I will start with moving a few larger model tests away from this file.
