### ISSUE TITLE
MPS backend support issue for int64

### ISSUE THREAD

**Issue by navaneetham-aicomputing** [pytorch/pytorch#79200]
### 🐛 Describe the bug

Getting following error in MPS device. Below code will help to reproduce the issue. 

```python
import torch
data = torch.zeros([2, 4], dtype=torch.int64).to('mps')
out = torch.abs(data)
```

```
Error:
Traceback (most recent call last):
  File "/Users/nav/opt/anaconda3/envs/picard-py310/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
RuntimeError: Operation 'abs_out_mps()' doesn not support input type 'int64' in MPS backend
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220609
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.13.0.dev20220609
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchvision==0.14.0a0+f9f721d
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220609          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20220603          pypi_0    pypi
[conda] torchvision               0.14.0a0+f9f721d          pypi_0    pypi

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
Currently we don't have native Int64 support in MPS. We cast the operations to Float. In-order to be transparent and not change the dynamic-range of the operation behind User's back we have a `TORCH_CHECK` to error [out in-case](https://github.com/pytorch/pytorch/blob/e10b762537214ad152724d772b72b17a4448f145/aten/src/ATen/native/mps/operations/UnaryOps.mm#L18) of Int64 support. 

We can relax the Error and make it a warning @albanD to add support for Int64. But currently to be conservative we do error out.
