### ISSUE TITLE
[JIT][caffe2][ONNX] Cannot export Dynamic type tensors to ONNX

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#7925]
Right now we have this hacky check that if we have a Dynamic tensor, we simply skip the export in the ONNX front-end path: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/export.cpp#L162

This is because we cannot populate the metadata fields without this information. As a result, we've had to hack up the checker in the caffe2 back-end to support graphs where this info is absent, namely graphs with control flow: https://github.com/pytorch/pytorch/pull/7832

This flag is clearly marked as `UNSAFE`, so it should be used with caution. Even if we fix the Dynamic type, we may have to keep this if we define the PyT1.0 serialization format to use ONNX, because it will likely not conform to the ONNX spec

**Comment by eellison** [comment]
This issue description appears outdated. We no longer do the hack described and ONNX support for dynamic shapes i'm sure is being tracked in https://github.com/onnx/onnx.
