### ISSUE TITLE
cpu-libtorch1.11 can not load  gpu-libtorch pt-model 

### ISSUE THREAD

**Issue by w1005444804** [pytorch/pytorch#79260]
### 🐛 Describe the bug

cpu-libtorch1.11 can not load  gpu-libtorch pt-model , but there is no Issue when gpu-libtorch load it.

### Versions

cpu-libtorch1.11

**Comment by xsacha** [comment]
You need to set the map_location (or device) to cpu. Otherwise the default location will be 'gpu', if you saved it as such.
