### ISSUE TITLE
Support float tensors as float inputs

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#79279]
### 🚀 The feature, motivation and pitch

Functions that take float tuples as inputs will complain about type mismatch when the input is `Tuple[Tensor]`. When using a dynamic computed value from tensor size as input to `upsample`, for example, the function will complain during tracing since the size is a tensor, whereas the function expects floats.

### Additional context

Example code

```python
import torch
from torch import nn


class Model(torch.nn.Module):
    def forward(self, x):
        return nn.functional.interpolate(
            x,
            scale_factor=(x.size(2) / 100, x.size(3) / 200),
            mode="bicubic",
        )


if __name__ == "__main__":
    model = Model()
    model.eval()
    x = torch.randn(1, 3, 224, 224)
    y = model(x)
    print(y.shape)

    # This will fail
    torch.jit.trace(model, x)
```

```
TypeError: upsample_bicubic2d() received an invalid combination of arguments - got (Tensor, NoneType, bool, tuple), but expected one of:
 * (Tensor input, tuple of ints output_size, bool align_corners, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, NoneType, bool, tuple)
 * (Tensor input, tuple of ints output_size, bool align_corners, float scales_h, float scales_w, *, Tensor out)
```

cc @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @jbschlosser

**Comment by ezyang** [comment]
Cc @Chillee @Krovatkin symbokic floats 🥶

**Comment by ezyang** [comment]
We are building a first class concept of symbolic integer and we were joking about how maybe we might need symbolic floats too. If we had those they would work for your case.

**Comment by BowenBao** [comment]
@ezyang What's the status of symbolic [integer, float]? Could you point us a few links to start with?

**Comment by ezyang** [comment]
These are on master, I'll give more deets when I get to computer

**Comment by BowenBao** [comment]
> https://github.com/pytorch/pytorch/blob/master/c10/core/SymFloat.h https://github.com/pytorch/pytorch/blob/master/c10/core/SymInt.h
> 
> any ops that have been symintified have _symint versions that can take these. Any op that takes Scalar can take these.

I guess then the solution for us is to update tracer to trace scalar as SymFloat/SymInt, instead of as tensor?
With the traced `_C.Value` having jit type [SymIntType/SymFloatType](https://github.com/pytorch/pytorch/blob/916ccd6ca1f1a683cde3e9cd96294ffbb1a2a9a4/aten/src/ATen/core/jit_type.h#L1303).

Any recommendation for boolean? :)

**Comment by Chillee** [comment]
@BowenBao Is it possible to leverage the same tracer we use? Perhaps this is a much longer discussion than what we can have here on Github issues :P

**Comment by ezyang** [comment]
JIT trace should be entirely subsumed by the new tracing infra. Unfortunately we couldn't get ONNX off of TorchScript as they seem to want to capture control flow, but users without control flow should find the transition very easy.

**Comment by BowenBao** [comment]
> @BowenBao Is it possible to leverage the same tracer we use? Perhaps this is a much longer discussion than what we can have here on Github issues :P

Would love to learn more about that as well. For this issue we were looking at if the new SymInt could quickly resolve this type of scalar issues for us.

**Comment by ezyang** [comment]
So, the only frontend that works with symbolic shapes today is `make_fx` with `mode="symbolic"`. And this will automatically replace the input sizes with symbolic sizes for all input sizes.

**Comment by thiagocrepaldi** [comment]
Tracked internally by https://github.com/microsoft/onnx-converters-private/issues/97
