### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by restaste** [pytorch/pytorch#79274]
### 🐛 Describe the bug

Hi! Sorry if this is not the right issue type, I wasn't sure where to put this 😅.

We are using `torch==1.7.1+cu110`  and noticed recently that we had builds failing during `pip install`, with the following error:
```
#13 17.58 Collecting torch==1.7.1+cu110
#13 17.59   Downloading https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl (1156.8 MB)
#13 45.83 ERROR: Exception:
#13 45.83 Traceback (most recent call last):
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
#13 45.83     status = self.run(options, args)
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
#13 45.83     resolver.resolve(requirement_set)
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
#13 45.83     discovered_reqs.extend(self._resolve_one(requirement_set, req))
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
#13 45.83     abstract_dist = self._get_abstract_dist_for(req_to_install)
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
#13 45.83     abstract_dist = self.preparer.prepare_linked_requirement(req)
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
#13 45.83     local_path = unpack_url(
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 282, in unpack_url
#13 45.83     return unpack_http_url(
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 164, in unpack_http_url
#13 45.83     unpack_file(from_path, location, content_type)
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py", line 249, in unpack_file
#13 45.83     unzip_file(
#13 45.83   File "/root/venv/lib/python3.8/site-packages/pip/_internal/utils/unpacking.py", line 139, in unzip_file
#13 45.83     shutil.copyfileobj(fp, destfp)
#13 45.83   File "/usr/lib/python3.8/shutil.py", line 205, in copyfileobj
#13 45.83     buf = fsrc_read(length)
#13 45.83   File "/usr/lib/python3.8/zipfile.py", line 940, in read
#13 45.83     data = self._read1(n)
#13 45.83   File "/usr/lib/python3.8/zipfile.py", line 1016, in _read1
#13 45.83     data = self._decompressor.decompress(data, n)
#13 45.83 zlib.error: Error -3 while decompressing data: invalid code lengths set
#13 ERROR: executor failed running [/bin/sh -c pip install     --extra-index-url https://download.pytorch.org/whl/     -r /requirements-freeze.txt]: exit code: 2
```

After blaming ourselves for a while, we compared the checksums of the wheel downloaded from `https://download.pytorch.org` with the one from an archive we had lying around:
- `md5sum torch-1.7.1+cu110-cp38-cp38-linux_x86_64.whl` (downloaded from `download.pytorch.org`) returns `9ac4df8f0be12fd67d6c8eba246b12f0`
- `md5sum torch-1.7.1+cu110-cp38-cp38-linux_x86_64.whl` (from our local archive) returns `3d7ca72d04412a82401ba0604a82a1cb`

When switching our `pip install` to use our local archive, the error above disappeared.

Additionally, `unzip -t torch-1.7.1+cu110-cp38-cp38-linux_x86_64.whl` reports the following error:
```
...
    testing: torch/lib/libtorch_cuda.so
  error:  invalid compressed data to inflate
...
```

While `unzip -t` on our local copy reports no error.

This led us to believe this file got corrupted somehow in pytorch's pypi repository. Do you believe that might be the case?

### Versions

Collecting environment information...
PyTorch version: 1.7.1+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 470.129.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.17.4
[pip3] torch==1.7.1+cu110
[pip3] torchvision==0.8.2+cu110
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by julienr** [comment]
For a fresh download from Switzerland, I get a different md5sum:
```
~ $ wget https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl
...
~ $ md5sum torch-1.7.1+cu110-cp38-cp38-linux_x86_64.whl 
9ac4df8f0be12fd67d6c8eba246b12f0  torch-1.7.1+cu110-cp38-cp38-linux_x86_64.whl
```

Is this some sort of CDN issue ?

**Comment by malfet** [comment]
Can't reproduce it on my end: both `wget https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl` and `curl -O https://pytorch.s3.amazonaws.com/whl/cu110/torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl` yield binary with expected `3d7ca72d04412a82401ba0604a82a1cb` md5 sum

**Comment by atalman** [comment]
Can't reproduce it either
```
curl -O https://download.pytorch.org/whl/cu110/torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl
md5 -r torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl
3d7ca72d04412a82401ba0604a82a1cb torch-1.7.1%2Bcu110-cp38-cp38-linux_x86_64.whl
```
on mac from Eastern Canada

**Comment by julienr** [comment]
Problem seems solved on my end this morning in Switzerland. I get the correct `3d7ca72d04412a82401ba0604a82a1cb`.
I confirmed this from two different machines/internet connections.

**Comment by xiurobert** [comment]
@restaste can you confirm if this is still an issue?

**Comment by restaste** [comment]
Just gave this a try and that seems fixed as well on my side. Must have been a Swiss thing then probably. I'll close this then, thanks everyone!
