### ISSUE TITLE
Make MPS test workflow correctly report test stats

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#79293]
It doesn't today, we should be calling the `upload-test-artifacts` action and making sure we generate the xml

cc @seemethere @malfet @pytorch/pytorch-dev-infra @kulinseth @albanD

**Comment by suo** [comment]
@malfet or @albanD, are you the right people for this

**Comment by suo** [comment]
Also, dependencies (numpy, expecttest) are not pinned

**Comment by suo** [comment]
Also, because IN_CI was not set, I think test reporting, test disabling, flaky test behavior were all not active.

This was uncovered by https://github.com/pytorch/pytorch/pull/79229 (and is a good argument for why we should use the built-in env var instead of one that we have to set ourselves!)

**Comment by ZainRizvi** [comment]
@suo is this still an issue?

**Comment by clee2000** [comment]
* most dependencies are pinned and consolidated by https://github.com/pytorch/pytorch/issues/88071
* env var IN_CI got set in https://github.com/pytorch/pytorch/pull/87325
* tests are now run through run_test https://github.com/pytorch/pytorch/pull/88829 (gives xml + disable test infra)

Are there any other things we need?
