### ISSUE TITLE
Combine size_average and reduce args in Loss modules

### ISSUE THREAD

**Issue by li-roy** [pytorch/pytorch#7929]
Currently, our loss modules have two boolean args for size_average and reduce. These flags don't operate independently, so it makes sense to have a single enum (or similar) argument instead. This will also make it easier for us to introduce different averaging behaviors, such as averaging over each individual element and averaging over the size of the batch.

**Comment by zou3519** [comment]
One thing to think about is how we're going to represent the enum at the ATen level. It could be a C++ enum, integer flag, etc etc
