### ISSUE TITLE
compile cuda8.0

### ISSUE THREAD

**Issue by xujinchang** [pytorch/pytorch#793]
My environments have already supported the caffe, so some dependcies I have set up before. I didn't use the anaconda, because my python/site-package has the enough things. As I set up pytorch, i only ran  python setup.py, and i can work properly except for .cuda(), it raises
 AssertionError("Torch not compiled with CUDA enabled")
Instead using conda install -c soumith magma-cuda75, what else commands  should i run to compile the pytorch with cuda 8.0?

**Comment by apaszke** [comment]
Please post any future questions on [our forums](discuss.pytorch.org).

The right command to install PyTorch with CUDA 8.0 using anaconda is `conda install pytorch cuda80 magma-cuda80 -c soumith`. If you install from source and CUDA is not found, make sure to set `CUDA_HOME` env variable to where you installed it.
