### ISSUE TITLE
[ONNX] Internal assert error during export

### ISSUE THREAD

**Issue by trantuanngoc** [pytorch/pytorch#79333]
### 🐛Bug
When exporting pytorch script model to onnx, I get an error: ` input_values.size() == param_count_list.size()INTERNAL ASSERT FAILED at "../torch/csrc/jit/python/script_init.cpp":493, please report a bug to PyTorch.  `
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import torch
import torch.nn as nn
import torch.nn.functional as F
import re
import os
import unicodedata
import numpy as np

device = torch.device("cpu")

class EncoderRNN(nn.Module):
    def __init__(self, hidden_size, embedding, n_layers=1, dropout=0):
        super(EncoderRNN, self).__init__()
        self.n_layers = n_layers
        self.hidden_size = hidden_size
        self.embedding = embedding
        self.gru = nn.GRU(hidden_size, hidden_size, n_layers,
                          dropout=(0 if n_layers == 1 else dropout), bidirectional=True)

    def forward(self, input_seq, input_lengths, hidden=None):
        embedded = self.embedding(input_seq)
        packed = torch.nn.utils.rnn.pack_padded_sequence(embedded, input_lengths)
        outputs, hidden = self.gru(packed, hidden)
        outputs, _ = torch.nn.utils.rnn.pad_packed_sequence(outputs)
        outputs = outputs[:, :, :self.hidden_size] + outputs[:, : ,self.hidden_size:]
        return outputs, hidden
        
hidden_size = 500
encoder_n_layers = 2
decoder_n_layers = 2
dropout = 0.1
voc_num_words = 7826
embedding = nn.Embedding(voc_num_words , hidden_size)
encoder = EncoderRNN(hidden_size, embedding, encoder_n_layers, dropout)

test_seq = torch.LongTensor(10, 1).random_(0, voc_num_words ).to(device)
test_seq_length = torch.LongTensor([test_seq.size()[0]]).to(device)
script_encoder = torch.jit.script(encoder)
torch.onnx.export(script_encoder, (test_seq, test_seq_length),"model8.onnx") 
```
### Expected behavior
Successful model export to ONNX.
### Environment

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.4
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
 
cc @svenstaro @eklitzke @dreiss

**Comment by KarelPeeters** [comment]
It's very easy to reproduce with just a single `MultiheadAttention` layer, `torch.jit.scipts` and then `torch.onnx.export`:

```python
model = nn.MultiheadAttention(128, 8, 0.1)
model = torch.jit.script(model)

q = torch.randn(64, 1, 128)
k = torch.randn(64, 1, 128)
v = torch.randn(64, 1, 128)

# prove that these are the correct shapes and args
_ = model(q, k, v)

torch.onnx.export(
    model,
    (q, k, v),
    "test.onnx",
)
```

**Comment by WilliamTambellini** [comment]
@KarelPeeters  good steps.
Have you tried a JIT export: 
torch.jit.save(model, 'output.jit')
?

**Comment by davidberard98** [comment]
cc @BowenBao

**Comment by trantuanngoc** [comment]
> It's very easy to reproduce with just a single `MultiheadAttention` layer, `torch.jit.scipt` and then `torch.onnx.export`:
> 
> ```python
> import torch
> from torch import nn
> 
> model = nn.MultiheadAttention(128, 8, 0.1)
> model = torch.jit.script(model)
> 
> q = torch.randn(64, 1, 128)
> k = torch.randn(64, 1, 128)
> v = torch.randn(64, 1, 128)
> 
> # prove that these are the correct shapes and args
> _ = model(q, k, v)
> 
> torch.onnx.export(
>     model,
>     (q, k, v),
>     "test.onnx",
> )
> ```

I still get the same error when running your reproduction @KarelPeeters

**Comment by trantuanngoc** [comment]
> @KarelPeeters good steps. Have you tried a JIT export: torch.jit.save(model, 'output.jit') ?

What i'm trying is to export onnx model for using, not a script model

**Comment by bmahlbrand** [comment]
This also seems to trigger when I use multiple shapes in my input for a super resolution model.

```
lr_curr = torch.randn(1, 3, 224, 224, requires_grad=False)
lr_prev = torch.randn(1, 3, 224, 224, requires_grad=False)
hr_prev = torch.randn(1, 3, 224 * 4, 224 * 4, requires_grad=False)

jit_obj= torch.jit.script(model, example_inputs=[(lr_curr,lr_prev, hr_prev)])
```

If I create a random tensor of the `hr_prev` shape inside the `forward` call, this error is avoided (obviously incorrect input though)

**Comment by fancoltran** [comment]
@bmahlbrand can you provide your model code?

**Comment by bmahlbrand** [comment]
It's admittedly not a trivial example, but it works if i hardcode the `hr_prev` input that is x4 the size of the other 2 inputs inside `forward` for `FRNet`

https://gist.github.com/bmahlbrand/2daa6cdf8d1c45bf6ec0cbffcf3beeb3

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features, such as keyword arguments with default value

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
