### ISSUE TITLE
How to reimplement same behavior in AdaptiveAvgPooling2D

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#79332]
### 📚 The doc issue

Hi, am trying written an op which should mimic behavior in Pytorch's AdaptiveAvgPooling, but I can not align the result.

Here is what I do:

```
def test_pool():
    a = np.fromfile("in.bin", dtype=np.float32)
    a = np.reshape(a, [1, 12, 25, 25])
    a = torch.as_tensor(a)

    b = F.adaptive_avg_pool2d(a, [7, 7])
    print(b)
    print(b.shape)

    avg_pool = torch.nn.AvgPool2d([7, 7], [3, 3])
    c = avg_pool(a)
    print(c)
    print(c.shape)
```

the `b` and `c` are not equal.

My algorithm was:

```
k = output_size // input_size
stride = input_size - (output_size - 1) * k
padding = 0
```

I think there maybe some gap in real algorithm in pytorch. But can not found any where said it.

so, please make me clarify.

### Suggest a potential alternative/fix

Details in adaptiveavgpool2d

**Comment by mikaylagawarecki** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/. 

Feel free to reopen the issue if you would like to report a gap in the algorithm for AdaptiveAvgPool2D or would like to request better documentation for it :)

**Comment by Asthestarsfalll** [comment]
@jinfagang 
Hi, I'm also wondering how does the AdaptiveAvgPooling2D in  pytorch work.
My algorithm is the same  as yours, but it can't  align with pytorch's
