### ISSUE TITLE
Comparison operators don't accept out typed as one of the inputs

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#7933]
[pytorch]
The docs say that for tensor comparison operators (gt,lt etc) it should be possible to pass out argument typed as input (https://pytorch.org/docs/master/torch.html?highlight=torch%20gt#torch.gt), yet when I try to do it, I hit an error
```
import torch
a=torch.randn(5,5)
b=torch.randn(5,5)
mask = torch.ByteTensor(a.size())
torch.gt(a,b,out=mask)#works
mask = torch.empty_like(a)
torch.gt(a,b,out=mask) #does not work

```
```
RuntimeError: Expected object of type torch.ByteTensor but found type torch.FloatTensor for argument #0 'result'
```
Should the docs be fixed, or is it a bug?

**Comment by zou3519** [comment]
If it's really useful we can add it back; but we'll fix the docs for now
