### ISSUE TITLE
[bazel] build doesn't use sccache

### ISSUE THREAD

**Issue by vors** [pytorch/pytorch#79348]
### 🐛 Describe the bug

A build with sccache used to take 15 minutes according to @malfet .
Right now it take 65-70 minutes. This probably indicates that sccache is not used.
However this also could be because previously GPU build was not enabled and no it is.

This needs a quick investigation.

### Versions

master

**Comment by vors** [comment]
@jjsjann123 I think your experience with bazel tells us that  `sccache` is in fact used, right?
It would be still good to understand why we don't get the time savings benefit (mostly for CI).

**Comment by jjsjann123** [comment]
> @jjsjann123 I think your experience with bazel tells us that `sccache` is in fact used, right? It would be still good to understand why we don't get the time savings benefit (mostly for CI).

Yes. IIRC, when I pull CI docker image to build pytorch with bazel, there's something funny with sccache, but I never get it to work and switched to our development container to WAR it.

Would be great if we actually get CI container to be usable for community contributors. :eyes:
