### ISSUE TITLE
Cannot install Torch

### ISSUE THREAD

**Issue by NoNick96** [pytorch/pytorch#79347]
### 🐛 Describe the bug

I'm trying to install torch on Windows 11 with Python 3.9 installed by using the command:
`pip3 install torch torchvision torchaudio`
I'm getting this error:
`ERROR: Could not find a version that satisfies the requirement torch (from versions: none)`
`ERROR: No matching distribution found for torch`

### Versions

Pip version 22.1.2

**Comment by xsacha** [comment]
Make sure it is 64-bit python. There is no torch available on 32-bit python

**Comment by xiurobert** [comment]
Can you please run the environment collection script?

**Comment by mikaylagawarecki** [comment]
Hi, as @xiurobert mentioned, we use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
