### ISSUE TITLE
MSVC: vec_base size template fails with divide by sizeof(scalar_t)

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#79358]
### 🐛 Describe the bug

When compiling the latest master libtorch on MSVC (MKL + MKLDNN + CUDA + CUDNN), I face this error:

> C:\work\pytorch\aten\src\ATen/cpu/vec/vec_base.h(135): error C2297: '/': not valid as right operand has type 'T'
>         with
>         [
>             T=scalar_t
>         ]
> C:\work\pytorch\aten\src\ATen/cpu/vec/vec_base.h(134): note: while compiling class template member function 'at::vec::DEFAULT::Vectorized<scalar_t>::size_type at::vec::DEFAULT::Vectorized<scalar_t>::size(void)'
> C:/work/pytorch/aten/src/ATen/native/cpu/ReduceOpsKernel.cpp(284): note: see reference to class template instantiation 'at::vec::DEFAULT::Vectorized<scalar_t>' being compiled

You can see from the error it is trying to get sizeof(scalar_t) and failing for some reason.

### Versions

Master from 10th June onwards (haven't tested prior).
Was working at start of May.
Last change to the respective files was 24 days ago but I can't see any specific change to the usage of scalar_t so hopefully someone else has more information.

@kshitij12345

**Comment by waruqi** [comment]
same problem in https://github.com/xmake-io/xmake-repo/pull/1503

**Comment by waruqi** [comment]
This patch should fix the problem. https://github.com/pytorch/pytorch/pull/85958

It works on our ci. https://github.com/xmake-io/xmake-repo/pull/1503#issuecomment-1263104439

**Comment by patrikhuber** [comment]
This is now the source of an ICE again in the latest VS 2022, see https://developercommunity.visualstudio.com/t/Internal-compiler-error-when-compiling-l/10539393?space=62&sort=newest.
