### ISSUE TITLE
Incorrect image upscaling on MPS backend

### ISSUE THREAD

**Issue by Birch-san** [pytorch/pytorch#79383]
### 🐛 Describe the bug

Upscaling images via [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) works on-CPU, but produces visually-incorrect output using MPS backend on M1 Max.

Using PyTorch nightly build, `1.13.0.dev20220610`.

# Setup

I've made an [mps-repro](https://github.com/Birch-san/mps-repro) repository for this.  
[`repro.py` here](https://github.com/Birch-san/mps-repro/blob/main/repro.py).

```bash
git clone https://github.com/Birch-san/mps-repro.git
cd mps-repro

python3 -m venv venv
source ./venv/bin/activate
python3 -m pip install --upgrade pip

#--install Real-ESRGAN
git submodule update --init --recursive
wget https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth -P Real-ESRGAN/experiments/pretrained_models
# GFPGAN is unnecessarily pinned to an old numpy, for which there is no M1 macOS release. my fork fixes this
pip install basicsr facexlib git+https://github.com/Birch-san/GFPGAN.git@newer-numpy
cd Real-ESRGAN
pip install -r requirements.txt
python setup.py develop
cd ..
#--done installing Real-ESRGAN

# our torch nightly probably got nuked by the above, but we do need it for GPU support on macOS
pip install --pre "torch==1.13.0.dev20220610" "torchvision==0.14.0.dev20220609" --extra-index-url https://download.pytorch.org/whl/nightly/
```

# Run

```bash
python repro.py --half_precision_float false --backend_type mps
python repro.py --half_precision_float true --backend_type mps
python repro.py --half_precision_float false --backend_type cpu
# --half_precision_float true on-CPU is unsupported, but that problem's not important.
```

# Results

Attempt to upscale this input image:

![Fruit hypothesized by imagen-pytorch](https://github.com/Birch-san/mps-repro/raw/main/in.jpg)

Fruit hypothesized by [imagen-pytorch](https://github.com/cene555/Imagen-pytorch).

### Half-precision float

[Unsupported](https://github.com/pytorch/pytorch/issues/74625) (`"slow_conv2d_cpu" not implemented for 'Half'`), but that's not what our repro is investigating.

### Single-precision float

![Perfectly 2x upsampled fruit](https://github.com/Birch-san/mps-repro/raw/main/out_cpu_half_False.jpg)

Perfectly 2x upsampled fruit.

### Half-precision float

![Overexposed, white-and-green, high-frequency formless mess](https://github.com/Birch-san/mps-repro/raw/main/out_mps_half_True.jpg)

Overexposed, white-and-green, high-frequency formless mess.

### Single-precision float

![Andy Warhol-esque desaturated tiled fruit](https://github.com/Birch-san/mps-repro/raw/main/out_mps_half_False.jpg)

Andy Warhol-esque desaturated fruit, tiled in tiles 2/3rd the width of the original image.

### Versions

```
PyTorch version: 1.13.0.dev20220610
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.12 (main, Jun  1 2022, 06:34:44)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.0.dev20220610
[pip3] torchvision==0.14.0.dev20220609
[conda] numpy                     1.23.0rc2                pypi_0    pypi
[conda] torch                     1.13.0.dev20220606          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20220603          pypi_0    pypi
[conda] torchvision               0.14.0a0+f9f721d          pypi_0    pypi
```

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
Thanks @Birch-san  for filing the issue and detailed instructions. I was able to repro the issue, locally:
![out_mps_half_False](https://user-images.githubusercontent.com/453004/173705088-ca1f6939-57d6-49dd-8990-b13807e5ed8f.jpg)
![out_mps_half_True](https://user-images.githubusercontent.com/453004/173705091-fe7193b4-a4da-4293-9c6f-277c74dafe3f.jpg)
The Half results are wrong. We would need to isolate this further to the layers where there are correctness issues. Is it possible to provide a smaller layer level correctness test to isolate the issue ? If not we can continue to look at this network.

**Comment by Birch-san** [comment]
thanks for trying this out. 🙂 sorry the repro wasn't simpler.

I'll see what I can do about narrowing it down.

inferences begin in the Real-ESRGAN helper class's [`enhance` method](https://github.com/xinntao/Real-ESRGAN/blob/e2db57602068a839b0f53df9efca7e57fa3c8a99/realesrgan/utils.py#L174), which performs some traditional matrix processing.

I see mentions of "tile processing", and "all the processed tiles are merged into one image". I wonder whether that's related to the unintended tiling effect that we're getting on MPS. perhaps it's failing on the traditional maths before it even reaches the machine-learning model.  
I'll compare CPU and MPS results on the inputs/outputs of the traditional steps. maybe it'll diverge before even reaching the ML model.

deeper into the process, it delegates to the [`RRDBNet` model](https://github.com/XPixelGroup/BasicSR/blob/243b85fd8cb56cab9178a79c41cd6a0c439b61be/basicsr/archs/rrdbnet_arch.py#L67).  
I'm pretty new to machine learning and Python; are there any debugging/programming techniques that are typically used to locate a layer and grab the inputs and outputs as data goes through it?

> The Half results are wrong

very likely, but I'll caveat that with: I've never _seen_ an on-CPU result for `Half=True` (due to unimplemented operation). so I dunno whether it's "wrong because of MPS" versus "wrong because I'm invoking it wrong".  
admittedly the code's based on a [notebook](https://colab.research.google.com/drive/1P2hksAqTWxC69n8zMGJ9ZTN1dOJ2KVTO?usp=sharing#scrollTo=h3FFIeLrcuTX) developed by somebody who had access to CUDA, so this is _probably_ the right way to run a half-precision enhance.

the double-precision result is wrong too, since it differs from CPU (which is a good-looking upsample, as requested).

**Comment by Birch-san** [comment]
@kulinseth okay, I've made a more minimal repro. 🙂 

```python
import numpy as np
from numpy import vectorize, uint8
import torch as th
from torch import tensor, allclose
import cv2

def choose_colour (row_ix: uint8, col_ix: uint8, _channel_ix: uint8) -> uint8:
  if row_ix == 1 and col_ix == 1:
    return 127
  elif (row_ix == 2 and col_ix > 0) or (col_ix == 2 and row_ix > 0):
    return 255
  return 0

def get_tensor():
  img = np.fromfunction(function=vectorize(choose_colour), shape=(3, 3, 3), dtype=uint8)
  img = img.astype(np.float32)
  img = img / 255
  img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
  img = th.from_numpy(np.transpose(img, (2, 0, 1))).float()
  return img

def unsqueeze(tensor, device_type):
  return tensor.unsqueeze(0).to(device_type)

hardcoded_tensor = tensor(
  [[[0.0000, 0.0000, 0.0000],
    [0.0000, 0.4980, 1.0000],
    [0.0000, 1.0000, 1.0000]],

  [[0.0000, 0.0000, 0.0000],
    [0.0000, 0.4980, 1.0000],
    [0.0000, 1.0000, 1.0000]],

  [[0.0000, 0.0000, 0.0000],
    [0.0000, 0.4980, 1.0000],
    [0.0000, 1.0000, 1.0000]]])

unsqueezed_via_cpu = hardcoded_tensor.unsqueeze(0).to('cpu')
unsqueezed_via_mps = hardcoded_tensor.unsqueeze(0).to('mps').cpu()
assert allclose(unsqueezed_via_cpu, unsqueezed_via_mps, rtol=0.0001), "unsqueezing the harcoded tensor gives the same result o both CPU and on MPS"

computed_tensor = get_tensor()
print('hardcoded_tensor:\n', hardcoded_tensor)
print('computed_tensor:\n', computed_tensor)
assert allclose(computed_tensor, hardcoded_tensor, rtol=0.0001), "the hardcoded tensor is equivalent to the one we compute via get_tensor, so we should get the same result when we unsqueeze it… right?"

unsqueezed_via_cpu = computed_tensor.unsqueeze(0).to('cpu')
unsqueezed_via_mps = computed_tensor.unsqueeze(0).to('mps').cpu()
print('unsqueezed_via_cpu:\n', unsqueezed_via_cpu)
print('unsqueezed_via_mps:\n', unsqueezed_via_mps)
assert allclose(unsqueezed_via_cpu, unsqueezed_via_mps, rtol=0.0001), "unsqueezed MPS tensor differs from CPU counterpart"
```

fails on the final line.  
it's weird. if I save the offending input to a hardcoded tensor, then try unsqueezing that on both backends… it works fine (they get the same result).

but if I compute the tensor in a realistic way (still getting the same tensor, to within 0.0001 precision): we get wildly different results from the two backends.

the output is:

```
hardcoded_tensor:
 tensor([[[0.0000, 0.0000, 0.0000],
         [0.0000, 0.4980, 1.0000],
         [0.0000, 1.0000, 1.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.4980, 1.0000],
         [0.0000, 1.0000, 1.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.4980, 1.0000],
         [0.0000, 1.0000, 1.0000]]])
computed_tensor:
 tensor([[[0.0000, 0.0000, 0.0000],
         [0.0000, 0.4980, 1.0000],
         [0.0000, 1.0000, 1.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.4980, 1.0000],
         [0.0000, 1.0000, 1.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.4980, 1.0000],
         [0.0000, 1.0000, 1.0000]]])
unsqueezed_via_cpu:
 tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.4980, 1.0000],
          [0.0000, 1.0000, 1.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.4980, 1.0000],
          [0.0000, 1.0000, 1.0000]],

         [[0.0000, 0.0000, 0.0000],
          [0.0000, 0.4980, 1.0000],
          [0.0000, 1.0000, 1.0000]]]])
unsqueezed_via_mps:
 tensor([[[[0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000]],

         [[0.0000, 0.4980, 1.0000],
          [0.0000, 0.4980, 1.0000],
          [0.0000, 0.4980, 1.0000]],

         [[0.0000, 1.0000, 1.0000],
          [0.0000, 1.0000, 1.0000],
          [0.0000, 1.0000, 1.0000]]]])
```

**Comment by Birch-san** [comment]
@kulinseth I've made another, _even more minimal_ repro.

I wasn't able to trim it down any more than this (I tried eliminating more steps from `get_tensor`, eliminating dimensions from `arr` and making `arr` smaller, but all these ideas made it stop exhibiting symptoms).

```python
import numpy as np
from numpy import float32, array
import torch as th
from torch import tensor, allclose

arr = array([[[0, 0],
        [0, 1]],

       [[0, 0],
        [0, 1]]], dtype=float32)

def get_tensor():
  arr_t = np.transpose(arr, (2, 0, 1))
  img = th.from_numpy(arr_t)
  img = img.unsqueeze(0)
  return img

hardcoded_tensor = tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 1.]]]])

via_mps = hardcoded_tensor.to('mps').cpu()
assert allclose(hardcoded_tensor, via_mps, rtol=0.0001), "hardcoded_tensor == {hardcoded_tensor -> GPU -> CPU}"

computed_tensor = get_tensor()
print('hardcoded_tensor:\n', hardcoded_tensor)
print('computed_tensor:\n', computed_tensor)
assert allclose(computed_tensor, hardcoded_tensor, rtol=0.0001), "hardcoded_tensor == get_tensor()"

via_mps = computed_tensor.to('mps').cpu()
print('computed_on_cpu:\n', computed_tensor)
print('computed_via_mps:\n', via_mps)
assert allclose(computed_tensor, via_mps, rtol=0.0001), "get_tensor() == {get_tensor() -> GPU -> CPU}" # fails!
```

fails on the final assertion.  
outputs:

```
hardcoded_tensor:
 tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 1.]]]])
computed_tensor:
 tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 1.]]]])
computed_on_cpu:
 tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 1.],
          [0., 1.]]]])
computed_via_mps:
 tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [1., 1.]]]])
```

it's weird. transferring tensors from MPS to CPU _sometimes_ works.  
and it doesn't seem to depend on the _content_ of the tensor, it seems to depend on _where it came from_. 😕

**Comment by kulinseth** [comment]
@Birch-san thanks ! . This is very helpful. We will update here with a fix.

**Comment by qqaatw** [comment]
Looks like a non-contiguous memory issue, changing the last `via_mps` to the following works:

`via_mps = computed_tensor.contiguous().to('mps').cpu()`

**Comment by Birch-san** [comment]
@qqaatw genius! thanks so much.

So does this mean the _algorithm_ is wrong (in a way that's non-consequential on-CPU)?

Or is this a _workaround_, and ideally PyTorch would do this for us automatically?

Is there a way to recognise what operations are liable to give us contiguity problems?

**Comment by qqaatw** [comment]
When a tensor is transformed to a new shape but keeps the same data e.g. `permute`, `unsqueeze`, it's likely to become a [view](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) depending on the underlying implementation, which circumvents allocating new memory thereby saving resources. A view is likely to have a non-contiguous memory allocation.

Ideally the memory continuity should be dealt with automatically by PyTorch, this looks like a bug from the copy impl of MPS backend.

**Comment by Birch-san** [comment]
I'm trying to use `.contiguous()` on another model that may be afflicted by the same problem:

**Comment by Birch-san** [comment]
@qqaatw 

I'm trying to use `.contiguous()` to repair another model that may be afflicted by the same problem:

https://github.com/Birch-san/min-dalle/compare/94b097a8286514d7b4cfd9722a4c47a310d4fed9...43e7e92dff37789a5c2a25e9dfd25fa00d277581

but I'm still getting a tensor of all zeroes as the final output:  
https://github.com/kuprel/min-dalle/issues/25#issuecomment-1172894307

am I applying the technique correctly? i.e. slapping `.contiguous()` at the end of every `torch.{reshape,view,unsqueeze,permute}()` (i.e. functions which perform reshaping, and which may utilize a view to do so) call?

**Comment by qqaatw** [comment]
You may only need to add `.contiguous()` right before `.to("mps")` as currently I only see the problem here.

If the output of the model is still abnormal, maybe there is another bug somewhere, and you may need to narrow down the scope to find out which operation causes the other problem and provide a minimal repro code like what you have done in this issue.

**Comment by qqaatw** [comment]
Just made a more concise repro:

```python
def test_contiguous_minimal():
    device = "mps"

    x = torch.randn((3, 2), dtype=torch.float).permute((1, 0))
    print("Is view or contiguous:", x._is_view(), x.is_contiguous(), x.stride())  # True False (1, 2)

    x_mps = x.to(device)
    print("Is view or contiguous:", x_mps._is_view(), x_mps.is_contiguous(), x.stride())  # False False (1, 2)
    
    torch.testing.assert_close(x_mps, x, check_device=False)  # Fail
```

On [commit](https://github.com/pytorch/pytorch/commit/0922cc024eeafa2158c0d00396494a0ae983f8cb).

**Comment by alin256** [comment]
> You may only need to add `.contiguous()` right before `.to("mps")` as currently I only see the problem here.

We are discussing similar issue in #83015 which seems to be related to “non-blocking” behavior.

**Comment by jhavukainen** [comment]
Ran all the repro cases and the initial Real-ESRGAN test with the torch==2.5.1, torchvision==0.20.1. Had to change `from torchvision.transforms.functional_tensor import rgb_to_grayscale ` to `from torchvision.transforms.functional import rgb_to_grayscale` in one of the underlying packages to match the modern torchvision convention but otherwise it went smooth.

Along the way the correctness issues seem to have been addressed, all the tests produce identical outputs and the images seem to match to my eye:

### CPU
Single precision float
![out_cpu_half_False](https://github.com/user-attachments/assets/362709b6-5d04-4b08-a8cb-bcbdebafbacf)

### MPS
Single precision float
![out_mps_half_False](https://github.com/user-attachments/assets/d5f5f9a3-205a-439b-8def-39b48a41c428)

Half precision float
![out_mps_half_True](https://github.com/user-attachments/assets/c27fa235-0b1a-40b3-9a47-908cb366bdec)

I'll close this issue as addressed. Feel free to reopen if that seems inaccurate.
