### ISSUE TITLE
nesterov in SGD

### ISSUE THREAD

**Issue by weigq** [pytorch/pytorch#79405]
https://github.com/pytorch/pytorch/blob/cdf93b03de7ffc33e2762f7fefb8f3c7586fd051/torch/optim/sgd.py#L70-L74

Why dose set the `nesterov` as False when calling `__setstate__`?

**Comment by mikaylagawarecki** [comment]
My understanding is that this is for backward compatibility when loading old models, on master `maximize` and `foreach` are also set to their defaults in `__setstate__`

https://github.com/pytorch/pytorch/blob/dcd8900c39a288b7c7b23bdadfa24d21609908a9/torch/optim/sgd.py#L107-L112

**Comment by weigq** [comment]
Thanks, there is no bug.
