### ISSUE TITLE
Performance drops after running tensor multiplication for 15 seconds on M1 MAX (Pytorch MPS).

### ISSUE THREAD

**Issue by hxssgaa** [pytorch/pytorch#79402]
### 🐛 Describe the bug

Performance drops to half of the original performance after running tensor multiplication for 15 seconds on M1 MAX (Pytorch MPS). 

Python version: 3.9.7
OS: macOS 12.4
Pytorch version: 1.13.0.dev20220612

The code below reproduces the error:
```
from tqdm import tqdm
import torch

x = torch.rand((1024 * 8, 1024 * 8), dtype=torch.float32, device=torch.device('mps'))
y = torch.rand((1024 * 8, 1024 * 8), dtype=torch.float32, device=torch.device('mps'))
@torch.jit.script
def foo():
    x = torch.rand((1024 * 8, 1024 * 8), dtype=torch.float32, device=torch.device('mps'))
    y = torch.rand((1024 * 8, 1024 * 8), dtype=torch.float32, device=torch.device('mps'))
    z = x * y
    return z


if __name__ == '__main__':
    z0 = None
    for _ in tqdm(range(10000000000)):
        zz = foo()
        if z0 is None:
            z0 = zz
        else:
            z0 += zz
    torch.mps.empty_cache()
```

The above code works fine for RTX 3090 and performance never drops (by changing mps to cuda), but the performance will drop from 71 it/s to 25 it/s after 15 seconds running on M1 Max chip. 

Please look into the issue, I suspect that's the reason why training speed of some transformer models dropped after running for a few minutes.

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220612
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.22.3
Libc version: N/A

Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:24:02)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220612
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchtext==0.10.0
[pip3] torchvision==0.14.0a0+f9f721d
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220612          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20220603          pypi_0    pypi
[conda] torchtext                 0.10.0                   pypi_0    pypi
[conda] torchvision               0.14.0a0+f9f721d          pypi_0    pypi

cc @VitalyFedyunin @ngimel @kulinseth @albanD

**Comment by thipokKub** [comment]
I don't think it is a matmul problem, this behaviour seems to stem from repeatedly calling `torch.rand`. For M1 Max this happen around `40` seconds mark. The speed drop from `~165 its/s` to `~110 its/s`, then `~60 it/s`

```python
from tqdm import tqdm
import torch

if __name__ == '__main__':
    for _ in tqdm(range(10000000000)):
        torch.rand((1024 * 8, 1024 * 8), dtype=torch.float32, device=torch.device('mps'))
```

**Comment by xsacha** [comment]
Are you sure it's not related to throttling at all?
I only have the Mac Mini but I assume laptops may need to throttle after running for a while.

**Comment by hxssgaa** [comment]
> I don't think it is a matmul problem, this behaviour seems to stem from repeatedly calling `torch.rand`. For M1 Max this happen around `40` seconds mark. The speed drop from `~165 its/s` to `~110 its/s`, then `~60 it/s`
> 
> ```python
> from tqdm import tqdm
> import torch
> 
> if __name__ == '__main__':
>     for _ in tqdm(range(10000000000)):
>         torch.rand((1024 * 8, 1024 * 8), dtype=torch.float32, device=torch.device('mps'))
> ```

Thanks. It does look like the issue of `torch.rand`. The following code works fine for me:

```
import torch
import torch.nn.functional as F
import numpy as np
from tqdm import tqdm

class NeuralNet(torch.nn.Module):
    # Set layers.
    def __init__(self):
        super(NeuralNet, self).__init__()
        # First fully-connected hidden layer.
        self.fc1 = torch.nn.Linear(256, 8192 * 8 * 2)

    # Set forward pass.
    def forward(self, x):
        x = F.relu(self.fc1(x))
        return x

# Build neural network model.
neural_net = NeuralNet().to(torch.device('mps'))
batch_size = 1024
x = torch.ones((batch_size, 256)).to(torch.device('mps'))
for _ in tqdm(range(10000000)):
    neural_net(x)
```
The performance of the above code never throttles.

**Comment by hxssgaa** [comment]
I will close the issue, as this is not a `matmul` problem but rather a `torch.rand` problem. Thanks!
