### ISSUE TITLE
Pytorch for PPC64LE

### ISSUE THREAD

**Issue by n2018k** [pytorch/pytorch#79419]
### 📚 The doc issue

what versions of Pytorch are available for PPC64LE, RedHat 7.X, and CUDA 10.2?

**Comment by mikaylagawarecki** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by mgiessing** [comment]
@n2018k [OpenCE ](https://github.com/open-ce/open-ce/) provides common deep learning libraries - such as pytorch - for ppc64le & x86.
You can find the latest open-ce release (v1.6.1) which relates to PyTorch 1.10.2 publicly hosted at e.g. Oregon State University:
https://ftp.osuosl.org/pub/open-ce/1.6.1/

OpenCE 1.7.0 with PyTorch 1.11 will probably be released around end of june.
