### ISSUE TITLE
Add doc formatting check to lintrunner

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#79418]
From @mruberry: Docs are difficult to build locally (our documentation for how to do so is often out of date) and formatting errors in CI appear without line numbers (in at least some cases). Some recent example errors/warnings:

```
/opt/conda/lib/python3.7/site-packages/torch/__init__.py:docstring of torch.set_float32_matmul_precision:22: ERROR: Unexpected indentation.
/opt/conda/lib/python3.7/site-packages/torch/__init__.py:docstring of torch.set_float32_matmul_precision:23: WARNING: Block quote ends without a blank line; unexpected unindent.
```

If lintrunner could detect doc formatting issues it would making adding/updating docs much easier.

**Comment by ZainRizvi** [comment]
Todo: Find a linter and integrate it

**Comment by clee2000** [comment]
closing in favor of https://github.com/pytorch/pytorch/issues/102227 which has more discussion
