### ISSUE TITLE
process will be down when the first epoch has finished

### ISSUE THREAD

**Issue by Lmy0217** [pytorch/pytorch#7943]
## Issue description

Pytorch process will be down when the first epoch has finished. I used command  `disown -h %[job id]` and closed the terminal to made process in background. In my code, I setting `num_workers=1` to load dataset. Is there something happened about subprocesses?

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.14.3)
[pip3] pytorchviz (0.0.1)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by SsnL** [comment]
What do you mean that it `will be down`? Did it crash, error?

**Comment by Lmy0217** [comment]
@SsnL Yes, but I don't get any error message because the process is in background.

**Comment by nlgranger** [comment]
Have considered using a terminal multiplexer like screen or tmux as a workaround?

**Comment by SsnL** [comment]
@Lmy0217 Yeah, could you try collecting error message using @nlgranger suggestion?

**Comment by Lmy0217** [comment]
@nlgranger @SsnL 
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
"main", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/media/zonstlab0/c3e7052f-24ed-4743-8506-fb7b8c6f0ba7/zonstlab0/myluo/Diagnosis/main_PVC.py", line 161, in
train(epoch)
File "/media/zonstlab0/c3e7052f-24ed-4743-8506-fb7b8c6f0ba7/zonstlab0/myluo/Diagnosis/main_PVC.py", line 104, in train
for batch_idx, (data, label) in enumerate(train_loader):
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 280, in next
idx, batch = self._get_batch()
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 259, in _get_batch
return self.data_queue.get()
File "/usr/lib/python3.5/queue.py", line 164, in get
self.not_empty.wait()
File "/usr/lib/python3.5/threading.py", line 293, in wait
waiter.acquire()
File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 178, in handler
_error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4161) is killed by signal: Killed.

**Comment by SsnL** [comment]
Yeah your loader process was SIGKILL-ed somehow.  Can you try running with `num_workers=0` and see if it gives you better error message?

**Comment by Lmy0217** [comment]
@SsnL This is same with #8976.

**Comment by sdsy888** [comment]
I've encountered the same problem recently. 

If you're using the `docker` to run the pytorch program, with high probability, it's because the shared memory of docker is not big enough for running your program in the specified batchsize.

The solutions for this circumstance are:
1. use a smaller batchsize to train your model.
2. exit the current docker, and re-run the docker with specified "--shm-size=16g" or bigger depends on your machine.

Hope this could help those who have same problem.:+1:
