### ISSUE TITLE
UnboundLocalError: local variable 'ws' referenced before assignment

### ISSUE THREAD

**Issue by kiedanski** [pytorch/pytorch#79449]
https://github.com/pytorch/pytorch/blob/c10908cd41f6fe18a4d61704d7013d46bb05aeaf/torch/utils/data/dataloader.py#L261

`ws` is not defined within the elif statement.

cc @VitalyFedyunin @ejguan @NivekT

**Comment by yuguo68** [comment]
cc: @ejguan to take a look
