### ISSUE TITLE
Implement NestedTensor size function

### ISSUE THREAD

**Issue by erichan1** [pytorch/pytorch#79477]
### 🚀 The feature, motivation and pitch

NestedTensor does not implement a size method. NestedTensor has been integrated into nn.Transformer, which has revealed a couple of use cases where the sizes of intermediate tensors in the model are needed.

The three main cases are:
- PyTorch profiler fails on nn.Transformer because it attempts to find the size of all intermediate tensors, which includes NestedTensors in the transformer. 
- Autograd with NestedTensor fails because it requires the size of the tensor
- Torchscript with NestedTensor fails because torch.jit.script(model) attempts to find the size of intermediate tensors for performance optimizations.

### Alternatives

Two main ways to fix:
1. In all code that tries to find size of intermediate tensors, check for NestedTensor, and if it's a NestedTensor, do not ask for size. This seems feasible for the above use cases (profiler: has a WIP patch to check for NestedTensor, autograd: WIP in https://github.com/pytorch/pytorch/issues/79039, torchscript: could probably make a torchscript-specific patch). But I imagine that there are many such use cases and it would be hard to cover them all.  
2. Implement NestedTensor size method in a way that does not break existing use cases. 

cc @cpuhrsch @jbschlosser @bhosmer @erichan1

**Comment by erichan1** [comment]
Linking https://github.com/pytorch/pytorch/pull/79480 @eellison. Thanks for the fix! Unfortunately wasn't able to test this before the branch cut.

**Comment by jbschlosser** [comment]
Note that the size of a nested tensor is a nested data structure itself. It's unlikely we would ever implement `sizes()` directly for nested tensors as its signature returns an `IntArrayRef`.

I think it's better to abstract out call-site-specific querying of tensor size. A good example for autograd is providing an `is_same_size()` abstraction that can be implemented differently for nested vs. non-nested tensors (see #79297).
