### ISSUE TITLE
How to stacked RGB images

### ISSUE THREAD

**Issue by kazuma0606** [pytorch/pytorch#79495]
### 🚀 The feature, motivation and pitch

Hi, pytorch support teams.

I want to stack a RGB images.
I want to construct a 3D or 4D RGB tensor.
And, create a GAN model using these tensor.
How do I define how to create such a tensor?
I would like to stack the attached 2D RGB images.
Or can you extract each RGB element from a 3D image as a 3D tensor?

Kind regards,
yoshimura.

### Additional context

![RGB image](https://user-images.githubusercontent.com/68062970/173480331-c74cf544-d349-4c10-a30e-d53735d7c00e.png)

**Comment by xiurobert** [comment]
Hi, this issue tracker is only for issues. Please visit the PyTorch forum instead.

**Comment by mikaylagawarecki** [comment]
Hi, as @xiurobert mentioned, we use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
