### ISSUE TITLE
Suggest for a polynominal lr_scheduler

### ISSUE THREAD

**Issue by Kunlun-Zhu** [pytorch/pytorch#79511]
### 🚀 The feature, motivation and pitch

A polynominal lr_schduler is useful in multiple task.

### Additional context

https://github.com/cmpark0126/pytorch-polynomial-lr-decay
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/schedules/PolynomialDecay

Here is a possible useful repo for this issue.

cc @vincentqb @jbschlosser @albanD

**Comment by datumbox** [comment]
TorchVision has this implemented as a Lambda, see https://github.com/pytorch/vision/issues/4438.

It's something we were interested in putting to Core for a bit now. Maybe we can provide some help to get it in.
