### ISSUE TITLE
New scalars of type IntTensor breaking division

### ISSUE THREAD

**Issue by Mxbonn** [pytorch/pytorch#7951]
## Issue description
Functions that used to return an int pre 0.4 now return IntTensor which has different division behavior.

Provide a short description.

## Code example
< Pytorch 0.4
```
In [1]: a = torch.ByteTensor([1,1,1,0])

In [2]: a.sum()
Out[2]: 3

In [3]: a.sum() / 2
Out[3]: 1.5
```
and now since Pytorch 0.4
```
In [1]: a = torch.ByteTensor([1,1,1,0])

In [2]: a.sum()
Out[2]: tensor(3)

In [3]: a.sum() / 2
Out[3]: 1
```

----
This is probably intended behavior but it seems to me that it would be better to make operations such as sum return a FloatTensor instead of an IntTensor.

**Comment by apaszke** [comment]
cc @gchanan (I know this is expected under our current code, just something we might want to think about in the future)

**Comment by ngimel** [comment]
#6231 is also related.

**Comment by ailzhang** [comment]
let's use #6196 to track the progress
