### ISSUE TITLE
Torch FX return error "`__cuda_array_interface__` must be a dict"

### ISSUE THREAD

**Issue by YosuaMichael** [pytorch/pytorch#79513]
### 🐛 Describe the bug

During development of raft-stereo model on torchvision, I get an error `"TypeError: ``__cuda_array_interface__`` must be a dict"` after testing it with `torch.fx.symbolic_trace`. The error comes from this particular [line](https://github.com/pytorch/vision/blob/871ea0ce32f7bc7882d9ce9fcd44e51cb5a70d4f/torchvision/prototype/models/depth/stereo/raft_stereo.py#L263) and this test is run on cpu device.

Here is a minimum example to reproduce:
```
import torch
import torch.fx

class CustomModule(torch.nn.Module):
    def forward(self, x):
        batch_size, num_channels, h, w = x.shape
        b = x / torch.tensor(num_channels)
        return b

if __name__ == "__main__":
    m = CustomModule()
    m_fx = torch.fx.symbolic_trace(m)  # This will trigger error!
```

The error I got:
```
  File "/Users/yosuamichael/manual_build_lib/pytorch/vision/torchvision/prototype/models/depth/stereo/fx_test.py", line 22, in forward
    b = x / torch.tensor(num_channels)
TypeError: `__cuda_array_interface__` must be a dict
```

Currently I have found a way to fix this by creating global function that is wrapped by `torch.fx.wrap`. Here is the simple code with the fix to illustrate:

```
import torch
import torch.fx

def foo(x, num_channels):
    b = x / torch.tensor(num_channels)
    return b

torch.fx.wrap("foo")

class CustomModule(torch.nn.Module):
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        batch_size, num_channels, h, w = x.shape
        return foo(x, num_channels)

if __name__ == "__main__":
    m = CustomModule()
    m_fx = torch.fx.symbolic_trace(m)  # No error now
```

I would like to ask if my current fix is appropriate or is there a better suggestion for the fix?

Also I think the current error message `"TypeError: ``__cuda_array_interface__`` must be a dict"` is not helpful. It would be great if we can have a better error message.

Thanks in advance!

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0.dev20220531
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.10 (main, Mar  8 2022, 16:21:53)  [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.13.0.dev20220531
[pip3] torchaudio==0.10.2
[pip3] torchdata==0.5.0.dev20220531
[pip3] torchvision==0.13.0a0+d8654bb
[conda] Could not collect
```

cc @ezyang @SherlockNoMad

**Comment by ezyang** [comment]
I think I know what the problem is. FX tracers support ALL attribute accesses, returning proxies when this happens. torch.tensor tests to see if there is `__cuda_array_interface__` to see if it can treat it as if it were a tensor. If you pass a proxy tensor, proxy tensor is like "yeah, I got one of those" and then torch.tensor is like "tf is this, this is a Proxy, not a dict" and errors.

We can make a nicer error message probably by explicitly testing if the input object is a Proxy and just erroring. But the upshot is you won't be able to symbolic trace through code that uses torch.tensor. Consider using `make_fx` instead!

**Comment by fpaissan** [comment]
Hey @ezyang, do you have any news on this? Having the same issue..

**Comment by ezyang** [comment]
Can you try `make_fx`? :)

**Comment by YosuaMichael** [comment]
Sorry I miss your first response @ezyang. I have tried using `make_fx` and indeed it does work like a charm :)
Code after using `make_fx`:
```
import torch
import torch.fx
import functorch

class CustomModule(torch.nn.Module):
    def forward(self, x):
        batch_size, num_channels, h, w = x.shape
        b = x / torch.tensor(num_channels)
        return b

if __name__ == "__main__":
    m = CustomModule()
    # m_fx = torch.fx.symbolic_trace(m)  # This will trigger error!
    x = torch.rand(2, 3, 4, 4)
    m_fx = functorch.make_fx(m)(x) # Work like a charm!
```
