### ISSUE TITLE
Function to automatically calculate Conv shape

### ISSUE THREAD

**Issue by xiurobert** [pytorch/pytorch#79512]
### 🚀 The feature, motivation and pitch

Currently, there is no built in function in pytorch to calculate the output shape of some conv layer. It would be more convenient to have some function which calculates the return shape of some conv layer to make life easier.

### Alternatives

- Doing a forward pass on a test example and checking the shape of that.
- Using the formula listed [here](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html?highlight=torch%20nn%20conv2d#torch.nn.Conv2d)

### Additional context

A function like this:
```python

def calc_conv_return_shape(dim: tuple[int, int],
                           kernel_size: Union[int, tuple],
                           stride: Union[int, tuple] = (1, 1),
                           padding: Union[int, tuple] = (0, 0),
                           dilation: Union[int, tuple] = (1, 1)) -> tuple[int, int]:
    """
    Calculates the return shape of the Conv2D layer.
    Works on the MaxPool2D layer as well

    See Also: https://github.com/pytorch/pytorch/issues/79512

    See Also: https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html

    See Also: https://pytorch.org/docs/stable/generated/torch.nn.MaxPool2d.html

    Args:
        dim: The dimensions of the input. For instance, an image with (h * w)
        kernel_size: kernel size
        padding: padding size
        dilation: dilation size
        stride: stride size

    Returns:
        Dimensions of the output of the layer
    """
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size, kernel_size)
    if isinstance(padding, int):
        padding = (padding, padding)
    if isinstance(dilation, int):
        dilation = (dilation, dilation)
    if isinstance(stride, int):
        stride = (stride, stride)
    h_out = math.floor(
        (dim[0] + 2 * padding[0] - dilation[0] * (kernel_size[0] - 1) - 1)
        / stride[0] + 1)
    w_out = math.floor(
        (dim[1] + 2 * padding[1] - dilation[1] * (kernel_size[1] - 1) - 1)
        / stride[1] + 1)
    return h_out, w_out

``` 
Could be used (with some changes)

Additional function can be used to take in layers:
```python

def calc_layer_return_shape(dim: tuple[int, int],
                            layer: Union[torch.nn.Conv2d,
                                         torch.nn.MaxPool2d]) -> tuple[int, int]:
    """
    Calculates the return shape of a layer.

    Args:
        dim: The dimensions of the input. For instance, an image with (h * w)
        layer: The layer to calculate the return shape of.

    Returns:
        Dimensions of the output of the layer.
    """
    return calc_conv_return_shape(dim, layer.kernel_size, layer.stride,
                                  layer.padding, layer.dilation)
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by jbschlosser** [comment]
Hey @xiurobert, thanks for the request! I agree this seems fairly useful as a utility under e.g. `torch.nn.utils`. On the C++ side, we already do these calculations (at least for conv), and it wouldn't be too hard to expose them. I want to wait for a bit of discussion on how the API should look, etc.

**Comment by xiurobert** [comment]
That's great. Maybe I can open a PR once everything is good on your end

**Comment by xiurobert** [comment]
This can also probably be extended to calculate the return shape of an entire fully-convolutional/pooling sequential container

**Comment by albanD** [comment]
I think this is exactly the kind of things that should be possible with "meta" Tensors (a Tensor that has only metadata and no actual memory allocated).

I would expect something like this to work (it does not today as we don't have the Meta impl):
```python
import torch

a = torch.rand(2, 3, 10, 10, device="meta")
m = torch.nn.Conv2d(3, 5, 2, device="meta")

print(m(a).size())
```

cc @anjali411 do you know how hard it would be to add meta support for `convolution_overrideable` from python give that we already have the formula above?

**Comment by albanD** [comment]
Let's do that!

**Comment by xiurobert** [comment]
Yeah, I'd like to give it a try but I have one more question: should I be exposing a c++ API or is a python implementation fine?

**Comment by albanD** [comment]
Hi,

if you follow what is done in @anjali411 's comment above, you will be able to have a python implementation that will get registered into our c++ backend. So that it will be available from both c++ and Python.
And the code sample I shared above will be the simple way to get the result you are looking for.

**Comment by xiurobert** [comment]
Oh, so the code snippet I provided in the issue can be written in python, but if I register it under the `_meta_registrations.py` it will work in the C++ backend? Or do I need to write C++ here

**Comment by albanD** [comment]
> but if I register it under the _meta_registrations.py it will work in the C++ backend?

Exactly!
No C++ code needed!
You can see average pooling as an example there for example: https://github.com/pytorch/pytorch/blob/9acbaaaf051dc8080e98bf0fa23e4d1a219d7a1e/torch/_meta_registrations.py#L194-L200
That should be enough!

**Comment by xiurobert** [comment]
Got it. I'll see if I can get something written over the weekend or so for review.

**Comment by anjali411** [comment]
@xiurobert sounds great! let me know if you have any questions and feel free to add me as a reviewer once you have a PR

**Comment by xiurobert** [comment]
Will do.
