### ISSUE TITLE
Enable `dim=None` for all reduction functions

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#79525]
Change all reduction function signatures to use `int[1]? dim`. This will make `dim=None` possible, which needs to perform an all-reduce.

#79881 does this for `sum`, so it can be used as a reference

**Comment by gchanan** [comment]
are expected to be any BC issues with this?

**Comment by kurtamohler** [comment]
@gchanan, BC shouldn't be an issue. #79881 did not have anything BC breaking, and I expect all the other reductions to be pretty similar

**Comment by kurtamohler** [comment]
Closing this, tracking progress here instead: https://github.com/pytorch/pytorch/issues/29137#issuecomment-1199992060
