### ISSUE TITLE
Segfault with scikit-learn

### ISSUE THREAD

**Issue by sourabhd** [pytorch/pytorch#796]
Importing sklearn after importing torch cases segmentation fault. I have tried reinstalling both scikit-learn and pytorch. I use pip (not anaconda)

A) Works

ipython
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sklearn

In [2]: import torch

In [3]: print sklearn.__version__
0.18.1

B) Segmentation Fault

ipython
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import torch

In [2]: import sklearn
Segmentation fault (core dumped)

**Comment by wkentaro** [comment]
Seems duplicate to https://github.com/pytorch/pytorch/issues/786.

**Comment by apaszke** [comment]
Yeah, that's a duplicate.
