### ISSUE TITLE
Exporting the operator mode to ONNX opset version 12 is not supported

### ISSUE THREAD

**Issue by awfsgdf** [pytorch/pytorch#79601]
### 🐛 Describe the bug

when I exporting pytorch model to onnx, I use F.interpolate in my pytorch model, finally it got error:

RuntimeError: Exporting the operator mode to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.7.1
[pip3] torch-summary==1.4.5
[pip3] torchaudio==0.7.0a0+a853dff
[pip3] torchvision==0.8.2
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.0.221             h6bb024c_0    defaults
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py38h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py38hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py38h51133e4_0    defaults
[conda] numpy                     1.21.2           py38h20f2e39_0    defaults
[conda] numpy-base                1.21.2           py38h79a1101_0    defaults
[conda] pytorch                   1.7.1           py3.8_cuda11.0.221_cudnn8.0.5_0    pytorch
[conda] torch-summary             1.4.5                    pypi_0    pypi
[conda] torchaudio                0.7.2                      py38    pytorch
[conda] torchvision               0.8.2                py38_cu110    pytorch

**Comment by touzariLiticia** [comment]
hello, did you manage to find a solution to the problem ?

**Comment by awfsgdf** [comment]
> hello, did you manage to find a solution to the problem ?
yes.
dont use torch.mode . 
make the function by yourself.
