### ISSUE TITLE
binary_cross_entropy_with_logits forward-over-reverse rule is silently incorrect

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#79609]
### 🐛 Describe the bug

1. Comment out the skip for the following test
2. run `python test/test_ops_gradients.py -k "test_fn_fwgrad_bwgrad_nn_functional_binary_cross_entropy_with_logits"`
gradcheck ends up failing.
```
Traceback (most recent call last):
  File "/raid/rzou/pt/debug-cpu/test/test_ops_gradients.py", line 196, in test_fn_fwgrad_bwgrad
    self._check_helper(device, dtype, op, op.get_op(), "fwgrad_bwgrad")
  File "/raid/rzou/pt/debug-cpu/test/test_ops_gradients.py", line 131, in _check_helper
    self.assertTrue(gradgradcheck(fn, gradcheck_args, **kwargs))
  File "/raid/rzou/pt/debug-cpu/torch/testing/_internal/common_utils.py", line 3072, in gradgradcheck
    return torch.autograd.gradgradcheck(fn, inputs, grad_outputs, **kwargs)
  File "/raid/rzou/pt/debug-cpu/torch/autograd/gradcheck.py", line 1574, in gradgradcheck
    return gradcheck(
  File "/raid/rzou/pt/debug-cpu/torch/autograd/gradcheck.py", line 1418, in gradcheck
    return _gradcheck_helper(**args)
  File "/raid/rzou/pt/debug-cpu/torch/autograd/gradcheck.py", line 1432, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/raid/rzou/pt/debug-cpu/torch/autograd/gradcheck.py", line 1100, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/raid/rzou/pt/debug-cpu/torch/autograd/gradcheck.py", line 1311, in _fast_gradcheck
    _check_analytical_numerical_equal(analytical_vJu, numerical_vJu, complex_indices,
  File "/raid/rzou/pt/debug-cpu/torch/autograd/gradcheck.py", line 1283, in _check_analytical_numerical_equal
    raise GradcheckError(_get_notallclose_msg(a, n, j, i, complex_indices, test_imag, is_forward_ad) + jacobians_str)
torch.autograd.gradcheck.GradcheckError: Jacobian computed with forward mode mismatch for output 0 with respect to input 0,
numerical:tensor([8.9518e-06, 1.0410e-04, 1.4143e-05, 7.5104e-04, 3.3599e-03, 1.1928e-05,
        1.9389e-06, 5.8225e-04, 4.7362e-05, 1.9877e-04, 1.5380e-05, 3.0837e-03,
        2.2328e-04, 1.2073e-05, 2.4487e-06, 1.4305e-05, 3.8172e-04, 2.3448e-03,
        2.4692e-06, 2.4682e-05, 2.9840e-03, 4.3629e-05, 2.6280e-04, 3.2990e-03,
        8.1318e-06], dtype=torch.float64)
analytical:tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.], dtype=torch.float64, grad_fn=<CopyBackwards>)
```

It's possible that this is a numerical precision error, but I would expect us to not be skipping the test and instead lowering the tolerances in that case.

### Versions

main

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by nikitaved** [comment]
This is weird! I had same issues in the `kl_div`, where removing out-of-place code was the solution....

**Comment by zou3519** [comment]
The gradcheck error message was very long, but at the end it says the following:
```
The max per-element difference (slow mode) is: 2.05178077306023e-09.
Fast gradcheck failed but element-wise differences are small. This means that the
test might've passed in slow_mode!

If you are adding a new operator, please file an issue and then use one of the
workarounds. The workaround depends on how your test invokes gradcheck/gradgradcheck:

If the test
- manually invokes gradcheck/gradgradcheck, then call gradcheck/gradgradcheck
  with `fast_mode=False` as a keyword argument.
- is OpInfo-based (e.g., in test_ops_gradients.py), then modify the OpInfo for the test
  to have `gradcheck_fast_mode=False`
- is a Module test (e.g., in common_nn.py), then modify the corresponding
  module_test entry to have `gradcheck_fast_mode=False`
```

"This means that the test might've passed in slow_mode!"
So maybe this is just a numerical precision error? But the error message doesn't commit to telling us that

**Comment by Lezcano** [comment]
This will be fixed in https://github.com/pytorch/pytorch/pull/79381

**Comment by nikitaved** [comment]
@Lezcano , the issue comes from backward?

**Comment by Lezcano** [comment]
I don't think there's more issues, as now all the tests pass...

**Comment by Lezcano** [comment]
I don't think there's more issues, as now all the tests pass...

**Comment by nikitaved** [comment]
The question is, what was wrong in the backward? :)

**Comment by Lezcano** [comment]
I mean, the tests pass now, so I don't think that's too important, but feel free to investigate further if you want.

**Comment by zou3519** [comment]
The implication here is that there is some silently incorrect behavior in forward-mode AD when in-place operations are involved, right? So I think it's worth figuring out what went wrong, because a user may be able to trigger this in situations outside of binary_cross_entropy

**Comment by soulitzer** [comment]
The issue with `kl_div` was actually in-placing on an input, so shouldn't really be an issue with forward AD in general. I don't know if binary_cross_entropy is failing for the same reason though (so probably not too important to investigate at this stage, unless we have reason to think its indicative of deeper issues).

**Comment by Lezcano** [comment]
There's some in-place operations like `log_()` in the path that has subclasses so it could be simply that?

**Comment by Lezcano** [comment]
Fwiw, Re https://github.com/pytorch/pytorch/issues/79609#issuecomment-1156832635, I would not say that these are silent. There were some xfails that https://github.com/pytorch/pytorch/pull/79381/ removed so, if anything, these failures were known before.

**Comment by nikitaved** [comment]
@zou3519 , right. Turns out the issue was that the forward grad for `add.Scalar` was mutated, hence causing issues in https://github.com/pytorch/pytorch/pull/79007. https://github.com/pytorch/pytorch/pull/79664 Is supposed to fix that.
Regarding cross entropy with logits, it seems you were right, looks like a numeral issue which https://github.com/pytorch/pytorch/pull/79381 is solving.

**Comment by Lezcano** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/80083
