### ISSUE TITLE
[feature request] Official CUDA support for macOS through eGPU

### ISSUE THREAD

**Issue by farleylai** [pytorch/pytorch#7960]
## Issue description

The macOS distribution of pytorch lacks CUDA support while eGPU for macOS is ready on the market.
Some people managed to use eGPU with Tensorflow/Keras successfully on macOS (https://gist.github.com/richardxiong/4d5ca09e5bb3ece846c03416624a36f5). 

Any plans?

**Comment by SsnL** [comment]
We do support macOS with CUDA GPUs. However atm you have to build from source.

**Comment by soumith** [comment]
As Simon mentioned, it's not in our roadmap to support PyTorch binaries with GPU support. We do support PyTorch + CUDA on OSX if you manage to compile from source.
