### ISSUE TITLE
[FSDP] RuntimeError when using FSDP with auto wrap for sequence-to-sequence language models such as T5, Pegasus

### ISSUE THREAD

**Issue by pacman100** [pytorch/pytorch#79605]
### 🐛 Describe the bug

When using FSDP with the latest PyTorch Nightly version, it throws below error when using  sequence-to-sequence language models such as T5, Pegasus on tasks such as translation, summarization ...

### Steps to reproduce the error:
1. Run below command for the official transformers script [run_translation.py ](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation.py) to train T5 on translation task using FSDP integration.
```
torchrun --nproc_per_node=2 examples/pytorch/translation/run_translation.py \
	--model_name_or_path t5-small --per_device_train_batch_size 1   \
	--output_dir output_dir --overwrite_output_dir \
	--do_train --max_train_samples 500 --num_train_epochs 1 \
	--dataset_name wmt16 --dataset_config "ro-en" \
	--source_lang en --target_lang ro \
	--fsdp "full_shard auto_wrap" \
        --fsdp_min_num_params 2000 \ 
```
2. The following error is the output with the stack trace:
```bash
File "/home/sourab/dev/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1852[51/1916]
ard
    outputs = self.module(*args, **kwargs)
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/distributed/fsdp/flatten_params_wrapper.py", line 465, in forward
    return self.module(*inputs, **kwinputs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sourab/transformers/src/transformers/models/t5/modeling_t5.py", line 1601, in forward
    encoder_outputs = self.encoder(
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 1852, in forw
ard
    outputs = self.module(*args, **kwargs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/distributed/fsdp/flatten_params_wrapper.py", line 465, in forward
    return self.module(*inputs, **kwinputs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sourab/transformers/src/transformers/models/t5/modeling_t5.py", line 934, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/functional.py", line 2148, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
    return forward_call(*input, **kwargs)
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
RuntimeError: Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace. This view
 is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. 
You should replace the inplace operation by an out-of-place one.                                                               
    return F.embedding(                                                                                                        
  File "/home/sourab/dev/lib/python3.8/site-packages/torch/nn/functional.py", line 2148, in embedding                          
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)                                             
RuntimeError: Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace. This view
 is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. 
You should replace the inplace operation by an out-of-place one.
```

### Expected Output
No errors and runs for sequence-to-sequence models.

### Versions

PyTorch version: 1.12.0.dev20220505+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0.dev20220505+cu113
[pip3] torchaudio==0.12.0.dev20220505+cu113
[pip3] torchvision==0.13.0.dev20220505+cu113
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @ezyang

**Comment by pacman100** [comment]
Including similar issue raised in transformers repo [#17681](https://github.com/huggingface/transformers/issues/17681)

**Comment by pacman100** [comment]
Hello, any update on this?

**Comment by rohan-varma** [comment]
@pacman100 Unfortunately our oncall missed this one, moving it back to the triage queue.

Could you please link a pointer to the code that absorbs the following FSDP configuration, I couldn't find it in the HF file you linked:

```
--fsdp "full_shard auto_wrap" \
        --fsdp_min_num_params 2000 \ 
```

In PT 1.12, an auto-wrapping policy for transformers is available: https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/wrap.py#L82 - could you try plugging in this policy as opposed to the size-based wrapping policy and letting us know how that goes?

**Comment by lessw2020** [comment]
@zhaojuanmao @rohan-varma  - HF is not using the transformer wrapper atm, and this is definitely the issue here for T5 (and presumably pegasus). 

I've contacted Stas at HF to try and get this corrected on their side.

**Comment by lessw2020** [comment]
@pacman100  - There's a full tutorial on how to implement transformer wrapper here, and has the import and code for T5 as one of the examples:
https://github.com/lessw2020/transformer_central/tree/main/transformer_wrapping_tutorial

Offhand, you should be able to modify their accelerator script to remove the min_num_params wrapper and replace it with the transformer wrapper for the model you are running.
I've been using T5 HF + transformer wrapper, though not with HF trainer, so I know it works. 
Please let us know how it goes and happy to help if you hit issues.

**Comment by pacman100** [comment]
Hello @lessw2020, @rohan-varma, @zhaojuanmao 

Thank you for your pointers and guidance. Transformer wrapping fixes the issue for T5. Also, I tried the `MixedPrecision` and it is also working but I don't know about correctness, I thought it was still an issue as per this https://github.com/pytorch/pytorch/issues/75676.  Let me know if it is acceptable to use FSDP `Mixed Precision` with transformers.

I have raised the following PRs to enable transformer wrapping in 🤗 accelerate and 🤗 Trainer:
1. 🤗 Accelerate - https://github.com/huggingface/accelerate/pull/522
2. 🤗 Trainer - https://github.com/huggingface/transformers/pull/18134

Successfully able to run the below command for the official transformers script [run_translation.py ](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation.py) to train T5 on translation task using FSDP integration with `transformer wrapping` and mixed_precision.
```
torchrun --nproc_per_node=2 examples/pytorch/translation/run_translation.py \
	--model_name_or_path t5-small --per_device_train_batch_size 1   \
	--output_dir output_dir --overwrite_output_dir \
	--do_train --max_train_samples 500 --num_train_epochs 1 \
	--dataset_name wmt16 --dataset_config "ro-en" \
	--source_lang en --target_lang ro \
        --fp16 \
	--fsdp "full_shard auto_wrap" \
        --fsdp_transformer_layer_cls_to_wrap "T5Block" 
```

Below is the screenshot of the output showing successful training and model architecture with FSDP wrapping on T5Block.
![Screenshot 2022-07-14 at 6 06 08 PM](https://user-images.githubusercontent.com/13534540/178985804-17931ce7-391e-4f74-9913-e1a058ae62ae.png)

**Comment by lessw2020** [comment]
@pacman100  - thanks for putting in the PR over there to get this updated!
As @rohan-varma mentioned, mixed precision with FSDP works extremely well (for transformers etc).  Your loss may lag relative to fp32 for 1-3 of the first epochs but after that bfloat will catch up and end up at same place as fp32 ...but 2x+ as fast per epoch.  
If you are an ampere, definitely use bfloat16 and esp for T5.  
For fp16, you have to add a bit more code to implement the sharded grad scaler.
I'm making the video + code tutorial for mixed precision today and tomorrow, so let me send that over for you as soon as it's finished.

**Comment by lessw2020** [comment]
Hi @pacman100  - 
Here's the mixed precision tutorial for FSDP.
https://github.com/lessw2020/transformer_central/blob/main/mixed_precision/readme.md

It's pretty straightforward as it's controlled via custom policies.  

Please make sure you do a BFloat16 supported check as shown in the tutorial and for FP16, you'll need to use the ShardedGradScaler (also shown in tutorial).

Please let me know if any questions!

**Comment by pacman100** [comment]
Thank you everyone 🤗. This is resolved, will close the issue.

**Comment by xingchensong** [comment]
This issue is caused by we tie word_emb with lm_head, that's the meaning of `multiple views`, set tie_word_embeddings=False solved it

**Comment by xingchensong** [comment]
This issue is caused by we tie `word_emb` with `lm_head`, which is the meaning of `multiple_views`. I solved it by disable `tie_word_embedding`

**Comment by lmelinda** [comment]
Hi,

I'm facing the same issue but on the nn.Linear module, the stack trace is as follows, this is happening when I'm using FSDP. I have tried using `transformer_auto_wrap_policy` but that doesn't seem to help. Any ideas?
```
File ".../pnp_dist.runfiles/pip_torch/torch/nn/modules/linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: Output 0 of ViewBackward0 is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

I am using the Linear module in a sequence, if that affects it?
```
block = nn.Sequential(
            nn.Linear(n_input, n_feat),
            LayerNorm2DSlim(n_feat, relu=True),
            nn.Linear(n_feat, n_feat),
        )
```

**Comment by JamesWandy** [comment]
I'm having the same problem. Did you figure it out?
