### ISSUE TITLE
[Bug report] RuntimeError: backward_input can only be called in training mode

### ISSUE THREAD

**Issue by edchengg** [pytorch/pytorch#7961]
## Issue description

The code runs fine on CPU and GPU(pytorch 0.3) but failed on GPU(pytorch 0.4).

## Code example
code can be found from this:
https://github.com/wiseodd/controlled-text-generation

Error message:

Traceback (most recent call last):
File "train_discriminator.py", line 308, in 
main()
File "train_discriminator.py", line 239, in main
loss_G.backward()
File "/home-nfs/yangc1/anaconda3/envs/speech/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home-nfs/yangc1/anaconda3/envs/speech/lib/python3.6/site-packages/torch/autograd/init.py", line 89, in backward
allow_unreachable=True) # allow_unreachable flag
RuntimeError: backward_input can only be called in training mode

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script from here 
https://github.com/wiseodd/controlled-text-generation

and run it with:
```
python train_vae.py --save {--gpu}
python train_discriminator --save {--gpu}
```

- PyTorch or Caffe2: pytorch
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version: 8

**Comment by SsnL** [comment]
The repo you referenced has a bug. It sets model to `eval` when generating samples and logging, but never sets it back to train after returning to training.

You didn't see this error in 0.3.1 because we introduced this check after 0.3.1.

**Comment by SsnL** [comment]
It also calls `generate_soft_embed` in training, but sets to `eval` mode in that functions, for reasons I'm not understanding...

**Comment by edchengg** [comment]
Thank you for your quick response! The code runs fine on CPU(pytorch 0.4) but not GPU(0.4). Thats what confused me.. For the bug you mentioned, it does set back to train as far as i am aware.(line 307,383)

**Comment by Milozms** [comment]
I meet the same bug. I'm sure that I called model.train() before calling loss.backward()

	def update(self, batch):
		logits = self.model(batch)
		labels = batch[-1]
		self.model.train()
		loss = self.criterion(logits, labels)
		self.optimizer.zero_grad()
		loss.backward()
		torch.nn.utils.clip_grad_norm_(self.parameters, self.max_grad_norm)
		self.optimizer.step()

**Comment by sjy11** [comment]
I am new to PyTorch and stuck with this bug.   As above, I get this error on gpu using 0.4 but not when running on cpu.  Is there a fix or work-around?

**Comment by simon555** [comment]
up ?

**Comment by SsnL** [comment]
@edchengg Yes `model.forward()` sets it to training mode. However, the `generate_soft_embed` (`sample_soft_embed` in particular) is still run in eval mode. If you look at https://github.com/wiseodd/controlled-text-generation/blob/master/train_discriminator.py#L107-L121, `x_gen_attr` is from eval mode RNN and is used as G's loss. Hence backward fails.

**Comment by simon555** [comment]
@SsnL 
I get the same error when I use the train() mode : 

def train_epoch(self, iter, loss, optimizer, viz, win, TEXT, infoToPlot=None):
        self.train()
        self.trainingBatches=0

        train_loss = 0
        nwords = 0

        hid = None
        batch_id=0
        for batch in tqdm(iter):
            self.trainingBatches+=1
            
            if hid is not None:
                hid[0].detach_()
                hid[1].detach_()
                
            optimizer.zero_grad()
            x = batch.text
            y = batch.target
            
            if torch.cuda.is_available():
                x=x.cuda()
                y=y.cuda()
                
            out, hid = self(x, hid if hid is not None else None)
            bloss = loss(out.view(-1, self.vsize), y.view(-1))
            
            bloss.backward()
            train_loss += bloss
            # bytetensor.sum overflows, so cast to int
            local_nwords= y.ne(self.padidx).int().sum()
            nwords += local_nwords
            if self.args.clip > 0:
                clip_grad_norm_(self.parameters(), self.args.clip)

            optimizer.step()


error message : 
 torch.autograd.backward(self, gradient, retain_graph, create_graph)

  File "c:\users\simon\anaconda3\lib\site-packages\torch\autograd\__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag

RuntimeError: backward_input can only be called in training mode

**Comment by SsnL** [comment]
@simon555 Can you post a self-contained example? It's hard to judge what is wrong from just a method.

**Comment by simon555** [comment]
Sure! 

I am working on Language Model, here is my model  :

**Comment by simon555** [comment]
And here is my training loop   : 

`for epoch in range(args.epochs):
        print("Epoch {}, lr {}".format(epoch, optimizer.param_groups[0]['lr']))
        train_loss, train_words = model.train_epoch(
            iter=train_iter, loss=loss, optimizer=optimizer,infoToPlot=infoToPlot, viz=viz, win=win, TEXT=TEXT)
        valid_loss, valid_words = model.validate(valid_iter, loss, infoToPlot=infoToPlot, viz=viz, win=win)
        schedule.step(valid_loss)
        print("Train: {}, Valid: {}".format(
            math.exp(train_loss / train_words), math.exp(valid_loss / valid_words)))
        
        print('save info...')
        with open(os.path.join(directoryData,'data.pkl'), 'wb') as f:
            pickle.dump(infoToPlot, f, pickle.HIGHEST_PROTOCOL)
        print('generate sameple sentences...')    
        outputs=model.generate_predictions(TEXT, saveOutputs=True)`

**Comment by SsnL** [comment]
@simon555 You only set training mode before the loop, but set eval mode in `generate_predictions`, which is called in the middle of the loop. So iterations after `generate_predictions` will fail.

**Comment by simon555** [comment]
Thank You @SsnL !!!! :)

**Comment by nwpuhq** [comment]
> @simon555 You only set training mode before the loop, but set eval mode in `generate_predictions`, which is called in the middle of the loop. So iterations after `generate_predictions` will fail.

Thanks!

**Comment by Akhila-Yerukola** [comment]
> @edchengg Yes `model.forward()` sets it to training mode. However, the `generate_soft_embed` (`sample_soft_embed` in particular) is still run in eval mode. If you look at https://github.com/wiseodd/controlled-text-generation/blob/master/train_discriminator.py#L107-L121, `x_gen_attr` is from eval mode RNN and is used as G's loss. Hence backward fails.

I'm not sure if that makes sense. `x_gen_attr`is obtained when the RNN is in eval mode, but the `requires_grad` parameter for the tensor is still `True`. So you should be able to still use them further during training. In `sample_soft_embed`, at the end of the function, the model is set to train again. (https://github.com/wiseodd/controlled-text-generation/blob/master/ctextgen/model.py#L386). Given all this, what do you suggest instead as the fix?
