### ISSUE TITLE
[feature request] Untied biases for nn.Conv?d

### ISSUE THREAD

**Issue by lzamparo** [pytorch/pytorch#7965]
## Issue description

I'm trying to port a model from Lasagne to PyTorch, but am not sure I can do so since the convolutional layers have [untied biases](https://harmdevries89.wordpress.com/2015/03/27/tied-biases-vs-untied-biases/).  

From the Lasagne model:

```
l1a = Conv2DLayer(l0, num_filters=300, filter_size=(1, 19), W=nn.init.Orthogonal(gain='relu'), b=nn.init.Constant(0.1), nonlinearity=None, untie_biases=True)
```
 What does it mean to untie the biases?.  From [the docs](https://lasagne.readthedocs.io/en/latest/modules/layers/conv.html?highlight=untie#lasagne.layers.Conv2DLayer):

> untie_biases : bool (default: False)
If False, the layer will have a bias parameter for each channel, which is shared across all positions in this channel. As a result, the b attribute will be a vector (1D).
>
>If True, the layer will have separate bias parameters for each position in each channel. As a result, the b attribute will be a 3D tensor.

A cursory look at the source for _ConvNd shows that the biases  are currently 1D tensors:
```
if bias:
            self.bias = Parameter(torch.Tensor(out_channels))
        else:
            self.register_parameter('bias', None)
```
it's not a bother to make this larger based on a different flag in the constructor, but would require a change to `F.conv2d` that would discern the different shape of `self.bias` and add accordingly.

**Comment by soumith** [comment]
untied biases would also be tied to the height and width of the input, correct?

**Comment by lzamparo** [comment]
> untied biases would also be tied to the height and width of the input, correct?

Not quite.  [This accounting](https://datascience.stackexchange.com/questions/17671/correct-number-of-biases-in-cnn) suggests the number of bias parameters is now linked to the size of the *filters*, not of the input.  As suggested in [this](https://adbrebs.wordpress.com/2015/02/20/tied-weights-in-convolutions/) comparison from Blocks:
- Tied biases would have one bias parameter per feature map
- Untied biases would have one bias parameter per position per feature map.  

> And user cannot pass a different shaped input after the first invocation.

I think as long as the convolution is valid wrt the input, you can have either tied or untied biases.  If the user decided to change the shape of the kernels, that would cause a problem.

**Comment by lzamparo** [comment]
@fmassa @soumith I'm speculating, since I have not used variable sized inputs in this (or other) models, but the size of the untied bias is dependent on the size of the feature map, so I think you.  If the input changed in size, the tensor of untied bias values would also have to be resized (and some values either discarded or imputed, would be complicated).  Will this dependence prevent untied biases ever being supported?

**Comment by soumith** [comment]
@lzamparo yes, this dependence on input sizes will make it (super) likely that we wont support untied biases. The strain it puts on the API chain is big.

**Comment by lzamparo** [comment]
Understood.  Thanks for helping me understand why, and while I'm here, thanks in general for all your contributions.  Maybe I can replicate the effect of untied biases for this particular use case by subclassing nn.Conv2d

**Comment by soumith** [comment]
@lzamparo this should work for you for untied bias:

```
from torch.nn.modules.utils import _pair

class Conv2dUntiedBias(_ConvNd):
    def __init__(self, height, width, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1):
        kernel_size = _pair(kernel_size)
        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)

        if in_channels % groups != 0:
            raise ValueError('in_channels must be divisible by groups')
        if out_channels % groups != 0:
            raise ValueError('out_channels must be divisible by groups')
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding
        self.dilation = dilation
        self.groups = groups
        self.weight = Parameter(torch.Tensor(
                out_channels, in_channels // groups, *kernel_size))
        self.bias = Parameter(torch.Tensor(out_channels, height, width))
        self.reset_parameters()

    def reset_parameters(self):
        n = self.in_channels
        for k in self.kernel_size:
            n *= k
        stdv = 1. / math.sqrt(n)
        self.weight.data.uniform_(-stdv, stdv)
        self.bias.data.uniform_(-stdv, stdv)


    def forward(self, input):
        output = F.conv2d(input, self.weight, None, self.stride,
                        self.padding, self.dilation, self.groups)
        # add untied bias
        output += self.bias.unsqueeze(0).repeat(input.size(0), 1, 1, 1)
```

**Comment by lzamparo** [comment]
Wow, thanks @soumith!  That's above & beyond.

**Comment by meiji163** [comment]
> @lzamparo this should work for you for untied bias:
> 
> ```python
> import torch.nn as nn
> import torch.nn.functional as F
> from torch.nn.modules.utils import _pair
> 
> class Conv2dUntiedBias(nn.Module):
>     def __init__(self, height, width, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1):
>         kernel_size = _pair(kernel_size)
>         stride = _pair(stride)
>         padding = _pair(padding)
>         dilation = _pair(dilation)
> 
>         if in_channels % groups != 0:
>             raise ValueError('in_channels must be divisible by groups')
>         if out_channels % groups != 0:
>             raise ValueError('out_channels must be divisible by groups')
>         self.in_channels = in_channels
>         self.out_channels = out_channels
>         self.kernel_size = kernel_size
>         self.stride = stride
>         self.padding = padding
>         self.dilation = dilation
>         self.groups = groups
>         self.weight = Parameter(torch.Tensor(
>                 out_channels, in_channels // groups, *kernel_size))
>         self.bias = Parameter(torch.Tensor(out_channels, height, width))
>         self.reset_parameters()
> 
>     def reset_parameters(self):
>         n = self.in_channels
>         for k in self.kernel_size:
>             n *= k
>         stdv = 1. / math.sqrt(n)
>         self.weight.data.uniform_(-stdv, stdv)
>         self.bias.data.uniform_(-stdv, stdv)
> 
> 
>     def forward(self, input):
>         output = F.conv2d(input, self.weight, None, self.stride,
>                         self.padding, self.dilation, self.groups)
>         # add untied bias
>         output += self.bias.unsqueeze(0).repeat(input.size(0), 1, 1, 1)
> ```

Works great! Just need to add super(Conv2dUntiedBias, self).__init()__ and return output
