### ISSUE TITLE
Does torch.utils.checkpoint support custom cuda operators

### ISSUE THREAD

**Issue by Devoe-97** [pytorch/pytorch#79693]
[Does torch.utils.checkpoint support custom cuda operators](https://discuss.pytorch.org/t/does-torch-utils-checkpoint-support-custom-cuda-operators/154183)
Using the checkpoint function should make the training slower. However using the checkpoint function on my custom cuda operator makes the training faster compared to not using checkpoint, is this normal?
Thanks!

python3.8
pytorch: 1.10.1+cu111
torchvision: 0.11.2+cu111
GPU: Tesla V100

**Comment by VitalyFedyunin** [comment]
Hello!

It is better to ask such kinds of questions at https://discuss.pytorch.org/
I am going to close this issue. Feel free to reopen it, if you think that you need to report a bug or make a feature proposal.

Thanks.
