### ISSUE TITLE
DISABLED test_comprehensive__masked_amin_cuda_uint8 (__main__.TestDecompCUDA)

### ISSUE THREAD

**Issue by zengk95** [pytorch/pytorch#79712]
Platforms: linux

This test was disabled because it is failing on master and pull ([recent examples](http://torch-ci.com/failure/test_comprehensive__masked_amin_cuda_uint8%2C%20TestDecompCUDA)).

**Comment by janeyx99** [comment]
Similar to https://github.com/pytorch/pytorch/issues/79716, closing
