### ISSUE TITLE
Registering decompositions to all overloads is problematic for meta functions now.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#79734]
### 🐛 Describe the bug

Now, registering a meta implementation to a CompositeImplicitAutograd op causes "bad things to happen" (cc: @bdhirsh).

So, first, we have a behavior with `register_decomposition` today where it registers the decomposition to all overloads of a function. So, since we register the `where` ref as a decomposition for `torch.ops.aten.where`, we also end up writing the `where` ref as a decomposition for `torch.ops.aten.where.Scalar`. Second, registering a decomposition also registers that function as a meta implementation.

https://github.com/pytorch/pytorch/blob/master/torch/_refs/__init__.py#L1140

So... that causes problems.

cc: @ezyang @bdhirsh @eellison 

### Versions

N/A

**Comment by eellison** [comment]
Some other culprits: https://github.com/pytorch/functorch/blob/fb70a3cb588c4b937bb21479de762179b61b7661/functorch/_src/aot_autograd.py#L112
