### ISSUE TITLE
Compliance with PEP-0523

### ISSUE THREAD

**Issue by daskol** [pytorch/pytorch#79740]
### 🚀 The feature, motivation and pitch

Simple PyPI API index which is used to install PyTorch with `pip` does not meet [PEP-0523][1]. Here is an example of installation script.
```shell
pip install \
    --extra-index-url "https://download.pytorch.org/whl/cu102" \
    torch
```
The issue is that simple PyPI API does not redirect to `/`-URL and uses relative paths to wheels URLs. This is what PEP-0523 says.
> All URLs which respond with an HTML5 page MUST end with a / and the repository SHOULD redirect the URLs without a `/` to add a `/` to the end.

Despite the fact PEP-0523 does not requires mandatory redirect, it is expected and usually assumed by users and developers. 

[1]: https://peps.python.org/pep-0503/

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by malfet** [comment]
This has been fixed a while back:
```
% curl https://download.pytorch.org/whl/cu102 
<!DOCTYPE html>
<html>
  <body>
    <a href="Jinja2/">Jinja2</a><br/>
```
