### ISSUE TITLE
Linear not check shape

### ISSUE THREAD

**Issue by Number1JT** [pytorch/pytorch#79771]
### 🐛 Describe the bug

the shape is not matched, but no exception is raised
```python
import torch
xx = torch.zeros((100, 256)).cuda()
model = torch.nn.Linear(128, 2, bias=True).cuda()
model(xx)
```

### Versions

torch : 1.9.0+cu111

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by VitalyFedyunin** [comment]
pytorch 1.12 checks shape and returns `RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x256 and 128x2)`
