### ISSUE TITLE
android-tests is often flaky

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#79785]
### 🐛 Describe the bug

Twice every day or so, this test will fail to download important things and flakily fail. This detriments CI reliability 
https://github.com/pytorch/pytorch/runs/6923556353?check_suite_focus=true and causes confusion for the oncall and any HUD viewers.

It looks like we have been trying to download certain things and failing. Could we wrap downloads with retries? cc. @kit1980 

### Versions

CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by kit1980** [comment]
@malfet The action for running tests doesn't support docker containers.
