### ISSUE TITLE
Scalar add returns incorrect results for `int32` MPS array

### ISSUE THREAD

**Issue by danieldk** [pytorch/pytorch#79835]
### 🐛 Describe the bug

Scalar addition to an MPS `int32` array returns garbage. For example:

```
>>> torch.arange(10, device="mps", dtype=torch.int32) + 0
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='mps:0', dtype=torch.int32)
>>> torch.arange(10, device="mps", dtype=torch.int32) + 5
tensor([5, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='mps:0', dtype=torch.int32)
```

Expected:

```
>>> torch.arange(10, device="mps", dtype=torch.int32) + 0
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='mps:0', dtype=torch.int32)
>>> torch.arange(10, device="mps", dtype=torch.int32) + 5
tensor([5,  6,  7,  8,  9, 10, 11, 12, 13, 14], device='mps:0', dtype=torch.int32)
```

### Versions

**Note** about the output: this is 7d17e3b88 with b9c5b97a3 reverted to fix the failing build.

Collecting environment information...
PyTorch version: 1.13.0a0+git7d17e3b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.4 (main, May 26 2022, 08:19:39) [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.0a0+gitb9c5b97
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kulinseth @albanD

**Comment by tanmoyio** [comment]
Yes this needs to be fixed but you can use something like this - 
```python3
torch.arange(10, device="mps", dtype=torch.int32) + torch.tensor(5).to('mps', dtype=torch.int32) 
```
the output will be something like
```
tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14], device='mps:0', dtype=torch.int32)
```

**Comment by danieldk** [comment]
That definitely works, but if the scalar addition is outside software you can make this modification (e.g. HF Transformers), it won't do much good.

**Comment by malfet** [comment]
@danieldk hmm, sorry, which commit you had(`git show b9c5b97a3`  returns an ambiguous argument error to me) to revert and what build failures are you talking about?

Also, can you please try latest nightly/1.12 RC, as I can not reproduce the problem on my end:
```
% python
Python 3.10.0 (default, Nov 10 2021, 11:24:47) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
torch.__>>> torch.__version__, torch.version.git_version
('1.13.0.dev20220623', 'f0e1176a37cdce4797b723132cda103bc181074c')
>>> torch.arange(10, device="mps", dtype=torch.int32) + 0
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='mps:0', dtype=torch.int32)
>>> torch.arange(10, device="mps", dtype=torch.int32) + 5
tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14], device='mps:0',
       dtype=torch.int32)
>>> 

```

**Comment by malfet** [comment]
Hmm, though I see very weird results on M1 machine by running something as simple as:
```
python3 -c "import torch; print(torch.ones(10, dtype=torch.int32, device='mps')+1)"
```

**Comment by malfet** [comment]
It is a regression, that happened between Jun 9 and 10th:
```
(torch-py310) ~ % python -c "import torch;print(torch.__version__, torch.version.git_version, torch.ones(4, dtype=torch.int32,device='mps')+1)"
1.13.0.dev20220610 92b4285a8ddcd7f3d715821b341218f4013431b7 tensor([2, 0, 2, 0], device='mps:0', dtype=torch.int32)
(torch-py310)  ~ % pip install torch==1.13.0.dev20220609 --pre --extra-index-url https://download.pytorch.org/whl/nightly/cpu/                  
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu/
Collecting torch==1.13.0.dev20220609
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev20220609-cp310-none-macosx_11_0_arm64.whl (49.5 MB)
Requirement already satisfied: typing-extensions in ./miniforge3/envs/torch-py310/lib/python3.10/site-packages (from torch==1.13.0.dev20220609) (4.2.0)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 1.13.0.dev20220610
    Uninstalling torch-1.13.0.dev20220610:
      Successfully uninstalled torch-1.13.0.dev20220610
Successfully installed torch-1.13.0.dev20220609
(torch-py310)  ~ % python -c "import torch;print(torch.__version__, torch.version.git_version, torch.ones(4, dtype=torch.int32,device='mps')+1)"
1.13.0.dev20220609 18fa2ad3f3f4de557901030d4ed41f6d1b15899e tensor([2, 2, 2, 2], device='mps:0', dtype=torch.int32)
```

**Comment by pedrocolon93** [comment]
Just a heads up that whatever happens here is also happening when you perform torch.topk operation.
