### ISSUE TITLE
Bug while summing Boolean tensors on MPS device

### ISSUE THREAD

**Issue by l0r3m1psum** [pytorch/pytorch#79849]
### 🐛 Describe the bug

Hello I was trying to sum a bunch of boolean tensors on a MPS device and for some reason I get a strange result. This is the code that reproduces the problem:

```
import torch
print(sum(torch.tensor(True, device='mps') for _ in range(10)))
```

Running it prints `tensor(1006567434, device='mps:0')` on my machine. I'm running Python 3.9.13 on macOS Monterey using PyTorch 1.13.0.dev20220530.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0.dev20220530
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 (main, May 24 2022, 21:28:31)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.4-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.13.0.dev20220530
[conda] Could not collect
```

**Comment by mouryarahul** [comment]
Hi  [l0r3m1psum](https://github.com/l0r3m1psum), I had run the same operation, and I get the correct result:

Collecting environment information...
PyTorch version: 1.13.0.dev20220619
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.0.dev20220619
[pip3] torchvision==0.14.0.dev20220619
[conda] numpy                     1.22.4          py310h0a343b5_0    conda-forge
[conda] pytorch                   1.13.0.dev20220619        py3.10_0    pytorch-nightly
[conda] torchvision               0.14.0.dev20220619       py310_cpu    pytorch-nightly
(pytorch-nightly) rm181@HW-FVFF21JBQ05N ~ % python
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.

`>>>` import torch
`>>>` print(sum(torch.tensor(True, device='mps') for _ in range(10)))
tensor(10, device='mps:0')
`>>>`

**Comment by l0r3m1psum** [comment]
Sorry I wasn't on the latest development version of PyTorch, now that I have upgraded it works for me too.
