### ISSUE TITLE
Error using JIT with internal pytorch function dataloader.py

### ISSUE THREAD

**Issue by rpuenter** [pytorch/pytorch#79870]
## Issue description

I'm trying to compile a pytorch model with JIT so it can be deployed from C++ using the C++ API.

I get the error:
NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults

Python pdb postmortem points to the source of the error at torch/utils/data/dataloader.py. I don't think I should be modifying internal pytorch source files, so I am unable to fix this error.

## Code example

```python
import torch
from functools import partial
from numpy import asarray

class SomeFuns(torch.nn.Module):
    def __init__(self):
        super().__init__()


    @torch.jit.export
    def predict(self, X, batch_size):

        # Build DataLoader
        data =  torch.utils.data.DataLoader(torch.utils.data.TensorDataset(X), batch_size, False)
        # Batch prediction
        self.eval()
        r, n = 0, X.size()[0]
        for batch_data in data:
            # Predict on batch
            X_batch = torch.autograd.Variable(batch_data[0])
            y_batch_pred = self(X_batch).data
            # Infer prediction shape
            if r == 0:
                y_pred = torch.zeros((n,) + y_batch_pred.size()[1:])
            # Add to prediction tensor
            y_pred[r : min(n, r + batch_size)] = y_batch_pred
            r += batch_size
        return y_pred




class nonLineaRegression(SomeFuns):
    
    def __init__(self):
        super(nonLineaRegression,self).__init__()
        
        
        self.activation = torch.nn.ReLU()
        
        
        # Input layer
        self.input = torch.nn.Linear(2, 2) 
        
        
        # Hidden layer
        self.hiddenMinusLast = torch.nn.ModuleList()         
        
        layer = torch.nn.Linear(2, 2) 
        self.hiddenMinusLast.append(layer)              
            
        self.hiddenLast = torch.nn.Linear(2, 2) 

            
        # Last layer
        self.output = torch.nn.Linear(2,2) 

    

        
    def forward(self,x):
        
        out = self.activation(self.input(x))
        
        for hiddenLayer in self.hiddenMinusLast:               
            out = self.activation(hiddenLayer(out))
            
        out = self.activation(self.hiddenLast(out))
        out = self.output(out)
        
        return out
 
def main():
    
    model = nonLineaRegression()
  
    script =  torch.jit.script(model)
    torch.jit.save(script,"dbg.pt")
    
if __name__ == '__main__':
    main()
```

## System Info
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] numpydoc==1.4.0
[pip3] torch==1.11.0
[conda] blas                      2.115                       mkl    conda-forge
[conda] blas-devel                3.9.0            15_linux64_mkl    conda-forge
[conda] cpuonly                   2.0                           0    pytorch
[conda] libblas                   3.9.0            15_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            15_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            15_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            15_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.22.4          py310h4ef5377_0    conda-forge
[conda] numpydoc                  1.4.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   1.11.0             py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by VitalyFedyunin** [comment]
You should not put the training loop and data loader into the Model code, it is an anti-pattern. Also, DataLoader is not JIT-able in any condition.
