### ISSUE TITLE
[FSDP] activation checkpointing errs out on T5 HF model

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#79887]
### 🐛 Describe the bug

Applying the new FSDP activation checkpointing works great on standard exposed models (ala DeepViT) but fails out with an error on HF T5:

~~~
File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 57, in forward
  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl
        return forward_call(*input, **kwargs)return checkpoint(

  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 232, in checkpoint
  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 57, in forward
    return self.module(*inputs, **kwinputs)    
return forward_call(*input, **kwargs)  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl

  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py", line 57, in forward
    return checkpoint(
  File "/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 232, in checkpoint
    raise ValueError("Unexpected keyword arguments: " + ",".join(arg for arg in kwargs))
ValueError: Unexpected keyword arguments: attention_mask,position_bias,encoder_hidden_states,encoder_attention_mask,encoder_decoder_position_bias,layer_head_mask,cross_attn_layer_head_mask,past_key_value,use_cache,output_attentions
 ~~~
 
 You can reproduce this with our t5 repo here:
 https://github.com/lessw2020/t5_11
 
 Verify that fsdp checkpointing is set in config/defaults.py:
 
<img width="747" alt="config_checkpointing" src="https://user-images.githubusercontent.com/46302957/174664342-6eb559ea-325b-4af2-b60a-5b3cad163814.png">

and run with bash run_training.sh (may need to adjust your gpu count in this)
 

### Versions

reproduces with PyTorch nightly:
0.14.0.dev20220618+cu113
and likely higher as just need fsdp ac present.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by albanD** [comment]
Hi,

I'm afraid that the checkpoint API does not work for function that take kwargs as input. Can you pass these as positional arguments?

**Comment by rohan-varma** [comment]
@albanD what would be required to make `checkpoint` work with kwarg inputs?

**Comment by albanD** [comment]
The old style one would be very hard I think.
The non reentrant version should be simple in principle. But there might be complications to allow passing them that  I'm not aware of as the current API doesn't allow it.

**Comment by EvgenyUgolkov** [comment]
@albanD Good day! When i try to run the checkpoint_sequential with se_reentrant=False, i am getting the 

ValueError: Unexpected keyword arguments: use_reentrant

However, in the documentation, i can see that checkpoint_sequential can take this argument, so this error should not occur. Could you tell me, did you face this issue before? If yes, how can it be fixed?

![image](https://user-images.githubusercontent.com/92923525/232030472-feaa1038-4ccc-4405-97a3-fb4629364a0d.png)
