### ISSUE TITLE
Delete internal php code for viable/strict promotion

### ISSUE THREAD

**Issue by swang392** [pytorch/pytorch#79892]
Since we have have migrated promoting to the viable/strict branch to an open-source GHA, we can now delete the internal php code that previously handled promoting from master to viable/strict on `pytorch/pytorch`. 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by bigfootjon** [comment]
Yeah I support deleting the PHP code. We don’t have any other internal users of this feature besides PyTorch/PyTorch and an internal test repo

**Comment by swang392** [comment]
Done!
