### ISSUE TITLE
[documentation request] 'clone' needs better documentation

### ISSUE THREAD

**Issue by rsokl** [pytorch/pytorch#7989]
[The current documentation for `Tensor.clone` is](https://pytorch.org/docs/stable/tensors.html?highlight=clone#torch.Tensor.clone):

> Returns a copy of the `self` tensor. The copy has the same size and data type as `self`.

This documentation fails to elucidate the fact that any gradient propagating through the cloned tensor will propagate to the original tensor. This is critical to the functionality of clone (and is why the method isn't called "copy"), and is just begging for newcomers to make hard-to-find mistakes.

**Comment by zou3519** [comment]
Thanks for the report, @rsokl. Please feel free to send a pr!
