### ISSUE TITLE
PR can not be merged/reverted, CircleCI jobs are not schedueld

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#79907]
## Current Status
*ongoing*.

## Error looks like
@pytorchbot does not respond to commands, CircleCI jobs aren't scheduled

## Root cause
https://www.githubstatus.com/incidents/gvzcw6sd0xxb

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
Closing as incident is resolved

**Comment by janeyx99** [comment]
Future mitigation:
- Let's monitor the frequency of this-->if it's more frequent than every 6mo, we should look into the solutions.
  - We could write scripts to backfill HUD stats on Rockset when webhooks are broken 
  - We could try to make mergebot work when webhooks aren't good 
- We could better warn users on their PRs when the bot isn't work (like manually commenting OR writing a spam bot :p)
