### ISSUE TITLE
[feature request] [pytorch] Convenience method for doing unsqueeze / squeeze several times

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#7991]
Currently after some reduction ops in order to recover spatial dimensions I do `x.unsqueeze(-1).unsqueeze(-1)`. Would be nice to make this frequent code more concise.

Some possible variants:
```
x.unsqueeze(-1, -1)
x.unsqueeze(multi_dims = [-1] * 2)
```

I realize it may be non-trivial to design the API so that the result is clear when it's not just trailing dimensions.

**Comment by arogozhnikov** [comment]
Why not using numpy manner?  
`x[..., None, None]` and `x[..., 0,0]`

**Comment by vadimkantorov** [comment]
A valid option, thanks!

I find `unsqueeze` a little more readable, but I agree it's a matter of taste.

**Comment by SsnL** [comment]
The problem is that `unsqueeze` with multidim can be really confusing. It is order dependent. For example, `a.unsqueeze(-2, -1)` and `a.unsqueeze(-1, -2)` give you different results. NumPy's `expand_dim` also only supports 1 dimension. 

I think @aaronmarkham 's suggestion is the correct way to do here.

**Comment by apaszke** [comment]
Something like `squeeze_last` would still be useful though, because you can't do that using indexing.

**Comment by vadimkantorov** [comment]
Also verbose `unsqueeze` is more readable in unsqueeze-squeeze calls, where you first unsqueeze a few dimensions, then call some function, then squeeze them back.

The order can be made deterministic by pre-sorting the list, but I agree it's not very intuitive.

**Comment by arogozhnikov** [comment]
@apaszke why example above with ellipsis doesn't cut it?

**Comment by vadimkantorov** [comment]
For my taste, `some_func(x.unsqueeze(-1, -1)).squeeze(-1, -1)` is more readable than `some_func(x[..., None, None]).squeeze(-1).squeeze(-1)`, but of course it's mainly a question of taste

**Comment by apaszke** [comment]
@arogozhnikov Ok, I got confused. I agree that your solution works if the last two dims have been unsqueezed. What I've been thinking of is a way of flattening non-singleton dimensions, but it's not that important.

**Comment by apaszke** [comment]
@vadimkantorov I agree with @SsnL in that those indices will be very ambiguous, and in fact the indexing-based solution seems more readable in those cases.

**Comment by vadimkantorov** [comment]
Multiple unsqueeze could be used to make jit script's work a bit easier :) https://github.com/pytorch/pytorch/issues/54532
