### ISSUE TITLE
documentation for sparse tensor creation after 0.4.0 update

### ISSUE THREAD

**Issue by juniorrojas** [pytorch/pytorch#7995]
From the 0.4.0 migration guide https://pytorch.org/2018/04/22/0_4_0-migration-guide.html

> ## dtypes, devices and NumPy-style creation functions
> In previous versions of PyTorch, we used to specify data type (e.g. float vs double), device type (cpu vs cuda) and layout (dense vs sparse) together as a “tensor type”. For example, torch.cuda.sparse.DoubleTensor was the Tensor type respresenting the double data type, living on CUDA devices, and with COO sparse tensor layout.
> 
> In this release, we introduce torch.dtype, torch.device and torch.layout classes to allow better management of these properties via NumPy-style creation functions.

Although this introduction to the `dtype`, `device` and `layout` features mentions sparse tensors, there are no examples for sparse tensor creation using the 0.4.0 style. All references I could find online still use things like `torch.sparse.FloatTensor` rather than `torch.tensor`, even in the official `torch.sparse` documentation https://pytorch.org/docs/master/sparse.html . Is there a way to create a sparse tensor using `torch.tensor`? For example, the migration guide mentions examples like `torch.tensor([[1], [2], [3]], dtype=torch.half, device=cuda)` for dense tensors, but for sparse tensors it's not obvious how to use it, since it needs indices, values and size rather than just an array of numbers.

**Comment by gchanan** [comment]
You want `torch.sparse_coo_tensor` -- I haven't checked if we've documented it properly.

**Comment by juniorrojas** [comment]
The last line in the new documentation for tensor attributes (https://pytorch.org/docs/master/tensor_attributes.html) links to `torch.sparse` (https://pytorch.org/docs/master/sparse.html#sparse-docs) for more information:

> For more information on torch.sparse_coo tensors, see torch.sparse.

but I think it hasn't been updated yet, I couldn't find any reference to `sparse_coo_tensor` in the documentation for `torch.sparse`.

**Comment by sethah** [comment]
Looking at the pr that introduced this method, https://github.com/pytorch/pytorch/pull/5781, it looks like it was not documented at the time. I believe one thing that needs to happen is to add a docstring for the method in `_torch_docs.py`. I would be happy to send a PR for it, unless there's some reason it should not have a docstring.
