### ISSUE TITLE
[ONNX] Expose export training mode to public

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#79950]
### 🚀 The feature, motivation and pitch

Users may need to use the training mode information for creating extensions. 

e.g. https://github.com/microsoft/onnxruntime/pull/11900

**Comment by justinchuby** [comment]
Can we expose some kind of context instead of global fields?

**Comment by justinchuby** [comment]
We can have it in the symbolic context

**Comment by BowenBao** [comment]
> We can have it in the symbolic context

Guess we can close this then?

**Comment by justinchuby** [comment]
We haven't implemented it I don't think?

**Comment by BowenBao** [comment]
🤣 I see what it means.
