### ISSUE TITLE
Linkage of `void Lint(const AliasDb* db)` is internal

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#79963]
### 🐛 Describe the bug

I expect the function
```c++
// File: pytorch/torch/csrc/jit/ir/alias_analysis.h
void Lint(const AliasDb* db);
```
has external linkage so my library can reference it. However, I got a missing symbol error and ELF tool also shows

File: pytorch/torch/lib/libtorch_cpu.so
1606970: 00000000072194fe   902 FUNC    `LOCAL`  DEFAULT   12 _ZN5torch3jit4LintEPKNS0_7AliasDbE

Any idea to make it `GLOBAL`? Or this is by design?

### Versions

Latest Pytorch branch should reproduce it.

**Comment by wschin** [comment]
Modify Pytorch to use `TORCH_API void Lint(const AliasDb* db);` solves this problem.

**Comment by davidberard98** [comment]
@wschin would you like to open a PR to fix this or do you want me to do it?

**Comment by wschin** [comment]
> @wschin would you like to open a PR to fix this or do you want me to do it?

Just created a PR. :)
