### ISSUE TITLE
PrimTorch burns in static shapes

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#79968]
With the latest version of PyTorch, I've been migrating TorchInductor to prims (see https://github.com/pytorch/torchdynamo/pull/431) and I've noticed many cases where PrimTorch burns in shapes in cases where the prior _decomps didn't.

The top culprits I see are:
- `prims.broadcast_in_dim` with static integer args
- Tensor constants containing shapes (e.g. numel)

cc @ezyang @mruberry @ngimel @Chillee

**Comment by mruberry** [comment]
I think these should be traceable without "burn-in" because the values passed to them are derived from tensor metadata?

**Comment by ezyang** [comment]
Would these be fixed when we have dynamic shapes in proxy tensor?

**Comment by Chillee** [comment]
Yes I believe so.

**Comment by IvanYashchuk** [comment]
@Chillee do we have dynamic shapes in proxy tensor now?

**Comment by Chillee** [comment]
Yeah, I believe that at least wrt this issue (i.e. prims burning in shapes), we have enough coverage. There's still plenty of other work left for proxy tensor to fully "support" dynamic shapes, but it works for `broadcast_in_dim` :)

```
def f(x):
    return x + x.t()

print(make_fx(f, tracing_mode="symbolic", decomposition_table=get_decompositions([torch.ops.aten.add, torch.ops.aten.expand]))(torch.randn(5, 1)).code)
```
<img width="920" alt="image" src="https://user-images.githubusercontent.com/6355099/191181234-ab78c5cf-1aac-49b6-92c9-17197c160126.png">
