### ISSUE TITLE
question: where (if) are the caffe2 libraries?

### ISSUE THREAD

**Issue by alexge233** [pytorch/pytorch#7997]
Like many others, I've come from the old caffe2 repository.
I used to use the caffe2 shared libraries directly, I'm not interested in python and I had to built and then manually install the libraries.
Right now using pip3 to install pytorch seems an awful lot easier, but I can't find the libraries anywhere on my system. Are built anywhere, are they installed anywhere or does the default pip process not built them?
I've tried building the caffe2 subfolder directly but run into compilation issues, so I'd rather avoid it if pip3 can pull them.

**Comment by soumith** [comment]
the caffe2 libraries are not built as part of the Pip packages currently shipped as `pip install torch`

**Comment by alexge233** [comment]
So do I have to build PyTorch from source? Should I just get the caffe2 folder and build it, or is there a package of caffe2?

**Comment by pjh5** [comment]
Caffe2 only has packages in conda at the moment. 'conda install -c caffe2 caffe2' will install the Caffe2 libraries into an Anaconda env; they will be linked against other libraries in the Anaconda env as well.

**Comment by alexge233** [comment]
Thanks a lot everyone!
