### ISSUE TITLE
Documentation: torch.topk example incorrect

### ISSUE THREAD

**Issue by naifrec** [pytorch/pytorch#800]
Hello,

I post this here though I am not sure it belongs as an issue on github, I am sorry if it is not.

My remark is pretty simple, the example given for [`torch.topk` function](http://pytorch.org/docs/torch.html#torch.topk) is wrong (and hence misleading). It should read:
```python
>>> x = torch.range(1, 5)
>>> x

 1
 2
 3
 4
 5
[torch.FloatTensor of size 5]

>>> torch.topk(x, 3)
(
 5
 4
 3
[torch.FloatTensor of size 3]
,
 4
 3
 2
[torch.LongTensor of size 3]
)
>>> torch.topk(x, 3, 0, largest=False)
(
 1
 2
 3
[torch.FloatTensor of size 3]
,
 0
 1
 2
[torch.LongTensor of size 3]
)
```

The case were `largest=True` is wrongly reported.

Cheers :)

**Comment by apaszke** [comment]
Can you please send a PR? Thanks!

**Comment by naifrec** [comment]
Done, see PR #809
