### ISSUE TITLE
torch.ops.aten.stride doesn't have a default overload

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#80004]
### 🐛 Describe the bug

`torch.ops.aten.stride.default`

```
AttributeError: The underlying op of 'aten.stride' has no overload name 'default'
```

cc: @anjali411 

### Versions

N/A

**Comment by anjali411** [comment]
`torch.ops.aten.stride` doesn't have a default overload. It has the following two overloads: [`int`, `Dimname`](https://github.com/pytorch/pytorch/blob/769df7430d113f5a5729042712bf058492ca970a/aten/src/ATen/native/native_functions.yaml#L4540-L4549)

you can also query this in python:
```
>>> torch.ops.aten.stride._overload_names
['int', 'Dimname']
```

**Comment by Chillee** [comment]
Ah sorry, @anjali411, i misremembered the issue.

The issue is that `__torch_dispatch__` returns `torch.ops.aten.stride` and not an overload.

**Comment by Chillee** [comment]
Seems like the problem is from here: https://github.com/pytorch/pytorch/blob/dynamic_shape_poc_2/torch/csrc/autograd/python_variable.cpp#L2313

**Comment by anjali411** [comment]
@Chillee oh yeah that should return an overload! so `py::module::import("torch").attr("ops").attr("aten").attr("stride").attr("int").ptr()`

**Comment by anjali411** [comment]
resolved on master
