### ISSUE TITLE
PyTorch model converted to ONNX generates scatterNDupdate layers

### ISSUE THREAD

**Issue by ashishpapanai** [pytorch/pytorch#80029]
### 🐛 Describe the bug

Hi,
I converted a PyTorch model to ONNX to run inferences on it using OpenVINO on NCS2 (VPU). The converted model comprises scatterNDupdate layers which are not supported by the VPU. Is there any specific reason for the creation of those layers? and a way to avoid them?

From the PyTorch ONNX logs, I’ve found the code segment which is creating those layers, It will be of great help if I can be suggested a workaround to get rid of those.

```python
while 0 in out_length and now_step < nsteps:
                tmp_result = C[now_step, :, :]

                out_res[now_step] = tmp_result
                tmp_result = tmp_result.topk(1)[1].squeeze(dim=1)
                for j in range(b):
                    if out_length[j] == 0 and tmp_result[j] == 0: #Check Here
                        out_length[j] = now_step + 1
                now_step += 1
            for j in range(0, b):
                if int(out_length[j]) == 0:
                    out_length[j] = nsteps #Check Here
            start = 0
            output = torch.zeros(int(out_length.sum()), self.nclass).type_as(input.data)
            for i in range(0, b):
                cur_length = int(out_length[i])
                output[start: start + cur_length] = out_res[0: cur_length, I, :] #Check Here
                start += cur_length

            return output, out_length
```

### Versions

```
PyTorch version: 1.8.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: glibc-2.17

Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-44-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce MX250
Nvidia driver version: 470.129.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1
[pip3] torchvision==0.9.1
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi

```

**Comment by justinchuby** [comment]
cc @BowenBao

**Comment by ashishpapanai** [comment]
I am bringing it up to your notice @BowenBao. I fear it might have skipped your attention.

**Comment by justinchuby** [comment]
What is the opset version you are exporting it in? Could you share a reproducible example that we can execute to help debugging?

**Comment by ashishpapanai** [comment]
@justinchuby,  I am using Opset Version 13 (tried with 15 as well). 

```
def convert():
    transf = transforms.ToTensor()
    model = load_network()
    model = model.eval()
    img_width = 256
    img_height = 64
    img = Image.open('./demo/4.png').convert('RGB')
    img = img.resize((img_width, img_height))
    img = transf(img)
    img = torch.unsqueeze(img,dim = 0)
    img.to(torch.device("cuda:0" if torch.cuda.is_available() else "cpu"))
    torch.onnx.export(model.module, 
                        img, 
                        'VisionLAN.onnx', 
                        export_params=True, 
                        opset_version=13,
                        do_constant_folding=True,
                        input_names=['input'],
                        output_names=['output', 'out_length'],
                        verbose = True)
```

**Comment by thiagocrepaldi** [comment]
@ashishpapanai please provide a full runnable repro for us to be able to look at it

Nonetheless, if you find the operator inside torch/onnx/symbolic_opsetXXX.py which adds the undesired onnx op, you can try to replace that operator by a [cusmt op op implementation](https://pytorch.org/docs/master/onnx.html#custom-operators)

**Comment by IkrameBeggar** [comment]
> ### 🐛 Describe the bug
> Hi, I converted a PyTorch model to ONNX to run inferences on it using OpenVINO on NCS2 (VPU). The converted model comprises scatterNDupdate layers which are not supported by the VPU. Is there any specific reason for the creation of those layers? and a way to avoid them?
> 
> From the PyTorch ONNX logs, I’ve found the code segment which is creating those layers, It will be of great help if I can be suggested a workaround to get rid of those.
> 
> ```python
> while 0 in out_length and now_step < nsteps:
>                 tmp_result = C[now_step, :, :]
> 
>                 out_res[now_step] = tmp_result
>                 tmp_result = tmp_result.topk(1)[1].squeeze(dim=1)
>                 for j in range(b):
>                     if out_length[j] == 0 and tmp_result[j] == 0: #Check Here
>                         out_length[j] = now_step + 1
>                 now_step += 1
>             for j in range(0, b):
>                 if int(out_length[j]) == 0:
>                     out_length[j] = nsteps #Check Here
>             start = 0
>             output = torch.zeros(int(out_length.sum()), self.nclass).type_as(input.data)
>             for i in range(0, b):
>                 cur_length = int(out_length[i])
>                 output[start: start + cur_length] = out_res[0: cur_length, I, :] #Check Here
>                 start += cur_length
> 
>             return output, out_length
> ```
> 
> ### Versions
> ```
> PyTorch version: 1.8.1+cu102
> Is debug build: False
> CUDA used to build PyTorch: 10.2
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 20.04.4 LTS (x86_64)
> GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
> Clang version: Could not collect
> CMake version: version 3.23.2
> Libc version: glibc-2.17
> 
> Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59)  [GCC 7.5.0] (64-bit runtime)
> Python platform: Linux-5.13.0-44-generic-x86_64-with-debian-bullseye-sid
> Is CUDA available: True
> CUDA runtime version: Could not collect
> GPU models and configuration: GPU 0: NVIDIA GeForce MX250
> Nvidia driver version: 470.129.06
> cuDNN version: Could not collect
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Is XNNPACK available: True
> 
> Versions of relevant libraries:
> [pip3] numpy==1.19.5
> [pip3] torch==1.8.1
> [pip3] torchvision==0.9.1
> [conda] cudatoolkit               11.3.1               h2bc3f7f_2  
> [conda] numpy                     1.19.5                   pypi_0    pypi
> [conda] torch                     1.8.1                    pypi_0    pypi
> [conda] torchvision               0.9.1                    pypi_0    pypi
> ```

Hi @ashishpapanai 
I am currently facing the same issue with ScatterNDUpdate. Did you arrive to solve it?
Thank you
