### ISSUE TITLE
`torch.matmul` does not work properly with tensor indexing

### ISSUE THREAD

**Issue by Dvrki** [pytorch/pytorch#80027]
### 🐛 Describe the bug

There seems to be an inconsistency with the results received from `torch.matmul` when using tensor indexing

```python
import torch

weights = torch.rand(256, 256)

# Example 1
#############################################
x = torch.randn(2, 256)
y1 = torch.matmul(x, weights)
y2 = torch.matmul(x[-1], weights)
# this should print True, but it prints False
print(torch.equal(y1[-1], y2))

# Example 2
#############################################
x = torch.randn(2, 5, 256)
y1 = torch.matmul(x, weights)
y2 = torch.matmul(x[-1], weights)
# Interestingly, this does print True
print(torch.equal(y1[-1], y2))

# Example 3
############################################
# changing the size of the second dimension
# of x (from previous example) from 5 to 4
x = torch.randn(2, 4, 256)
y1 = torch.matmul(x, weights)
y2 = torch.matmul(x[-1], weights)
# This should print True, but prints False
print(torch.equal(y1[-1], y2))
```

### Versions

Pytorch version: 1.11.0

**Comment by gchanan** [comment]
does this cover your issue? https://pytorch.org/docs/stable/notes/numerical_accuracy.html#batched-computations-or-slice-computations

**Comment by nobody81127** [comment]
I applied a floating-point error analysis algorithm to calculate the error bounds for the result of y1, and I found that the result of y2 falls within this range. Therefore, I believe this is indeed a floating-point error, likely caused by differences in the order of operations. @Dvrki
