### ISSUE TITLE
[ONNX] Remove spammy warnings

### ISSUE THREAD

**Issue by garymm** [pytorch/pytorch#80038]
- [ ] `Warning: Constant folding - unsupported opset version. Constant folding not applied.`
- [ ] `WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.`

**Comment by AllenTiTaiWang** [comment]
track in #85015

**Comment by lix19937** [comment]
mark
