### ISSUE TITLE
XLA builds frequently fail during `download_and_install` step

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#80034]
### 🐛 Describe the bug

See last three failure (from Jun 22nd 2022 HUD):
https://github.com/pytorch/pytorch/runs/6998408151?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/6999992948?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7004452840?check_suite_focus=true

All 3 failed with similar pattern:
```
[https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/9c6a2f29660b886044a267bb4de662cd801079bc.tar.gz, https://github.com/llvm/llvm-project/archive/9c6a2f29660b886044a267bb4de662cd801079bc.tar.gz] to /home/jenkins/.cache/bazel/_bazel_jenkins/b463291cb8b07b4bfde1e3a43733cd1a/external/llvm-raw/temp9173948197133452314/9c6a2f29660b886044a267bb4de662cd801079bc.tar.gz: Read timed out
[1657](https://github.com/pytorch/pytorch/runs/6998408151?check_suite_focus=true#step:9:1658)
Loading: 0 packages loaded
```

I wonder if its possible to cache those artifacts in the base docker image?

### Versions

CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra @bdhirsh @janeyx99 @JackCaoG

**Comment by malfet** [comment]
Very likely similar approach can be applied to both bazel and xla builds

**Comment by JackCaoG** [comment]
@yeounoh Can you help to take a look?

**Comment by malfet** [comment]
Disabling for the time being in https://github.com/pytorch/pytorch/pull/80099 (as every build for last 5 commits have failed)

**Comment by JackCaoG** [comment]
yea, I think it is a GCS bucket issue

**Comment by malfet** [comment]
> yea, I think it is a GCS bucket issue

Yep, though I look at the google cloud status and it reported that everything is green

**Comment by yeounoh** [comment]
Hi @malfet, is there a way for us to re-use the tag? The llvm archieve will likely change every 2 ~4 weeks, and I don't want to bump up the tag (version) unless we actually make changes to the image itself. 
```
+ docker push [308535385114.dkr.ecr.us](http://308535385114.dkr.ecr.us/)-[east-1.amazonaws.com/pytorch/xla_base:latest](http://east-1.amazonaws.com/pytorch/xla_base:latest)
tag invalid: The image tag 'latest' already exists in the 'pytorch/xla_base' repository and cannot be overwritten because the repository is immutable.
```

**Comment by malfet** [comment]
> ```
> 
> + docker push [308535385114.dkr.ecr.us](http://308535385114.dkr.ecr.us/)-[east-1.amazonaws.com/pytorch/xla_base:latest](http://east-1.amazonaws.com/pytorch/xla_base:latest)
> 
> tag invalid: The image tag 'latest' already exists in the 'pytorch/xla_base' repository and cannot be overwritten because the repository is immutable.
> 
> ```

@seemethere can we make latest tag for this particular ECR mutable?

**Comment by JackCaoG** [comment]
@seemethere Seems like this issue "same tag" also blocks PyTorch/XLA master CI, if we can resolve it sooner that would be nice.

**Comment by seemethere** [comment]
> > ```
> > 
> > + docker push [308535385114.dkr.ecr.us](http://308535385114.dkr.ecr.us/[](http://308535385114.dkr.ecr.us/))-[east-1.amazonaws.com/pytorch/xla_base:latest](http://east-1.amazonaws.com/pytorch/xla_base:latest[](http://east-1.amazonaws.com/pytorch/xla_base:latest))
> > 
> > tag invalid: The image tag 'latest' already exists in the 'pytorch/xla_base' repository and cannot be overwritten because the repository is immutable.
> > ```
> 
> @seemethere can we make latest tag for this particular ECR mutable?

I would say we shouldn't. I don't want the xla_base image to be a source of a supply chain attack for us and immutable tags are part of that

**Comment by malfet** [comment]
llvm-project download issues started to pop up  again:
https://github.com/pytorch/pytorch/runs/7253866743?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7254314175?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7254952630?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7254933697?check_suite_focus=true
cc: @JackCaoG  @yeounoh

**Comment by JackCaoG** [comment]
@malfet Feel free to disable the build again. @yeounoh Can you take a look? Seems like build direcly fail when it can not fetch the llvm raw instead of try the second layer cache.

**Comment by yeounoh** [comment]
I see, the cache is live, but it's complaining about checksum. I will look into this. Thanks @malfet

**Comment by malfet** [comment]
Looks like its better now, but still not sure

**Comment by malfet** [comment]
I looks like[ 10% of builds](https://hud.pytorch.org/hud/pytorch/pytorch/master/1?name_filter=xla%2C) are failing (some of the failures are occluded as I kicked re-runs), but here are more examples:
- https://github.com/pytorch/pytorch/runs/7259541753?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7259838096?check_suite_focus=true
- https://github.com/pytorch/pytorch/actions/runs/2639720254/attempts/1
- https://github.com/pytorch/pytorch/runs/7264581492?check_suite_focus=true

**Comment by yeounoh** [comment]
It seems like the file was corrupted and thus the checksum changed. I fixed the issue, and bazel should retry a few times before giving up on the secondary cache.

**Comment by yeounoh** [comment]
Hi @malfet the test run passed, and I did a few more tests locally which looked good, too. Should we close this issue and revisit if anything pops up? We will be updating tensorflow & llvm in a few weeks FYI.
