### ISSUE TITLE
DataLoader traverse function doesn't work with `DataPipe` that is unhashable

### ISSUE THREAD

**Issue by ejguan** [pytorch/pytorch#80040]
### 🐛 Describe the bug

`cache` is added [here](https://github.com/pytorch/pytorch/blob/c4d558e2dafa894b07bd7308e5d02545cffa8d12/torch/utils/data/graph.py#L79) to prevent infinite recursion due to circular references of `DataPipe`.

However, this relies on the hash value of each `DataPipe` when adding DataPipe to the cache.

See the issue found by internal tests in [link](https://fburl.com/tasks/bt0d8lpl)

Potentially we can use `id` of each `DataPipe` as the key in `cache` rather than `DataPipe` instance itself.

### Versions

master branch

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by VitalyFedyunin** [comment]
Object id seems to be good and fastest option.

**Comment by ejguan** [comment]
Closing the Issue as https://github.com/pytorch/pytorch/pull/80509 and https://github.com/pytorch/data/pull/559 have landed.
