### ISSUE TITLE
Inference result is different between Pytorch and ONNX model when using an efficientnet architecture

### ISSUE THREAD

**Issue by drorlederman** [pytorch/pytorch#80047]
### 🐛 Describe the bug

I trained some pytorch models, some use resnet and some use efficientnet. I exported the models to onnx using the code below. When running inference, I'm getting significant differences between the torch and onnx models, only for the efficientnet model (I'm using the geffnet package). 
Any idea will be appreciated.
Thanks

```python
@torch.no_grad()
def convert2onnx(architecture, input_size, model_file_name, device, input=None):
    if input is None:
        input = torch.ones(1, 3, input_size, input_size, dtype=torch.float).to(device)
    torch.onnx.export(architecture, input, model_file_name, export_params=True, opset_version=15, do_constant_folding=True)
    onnx_model = onnx.load(model_file_name)
    onnx.checker.check_model(onnx_model)
    opset_version = onnx_model.opset_import[0].version
    #print(onnx.helper.printable_graph(onnx_model.graph))
    return
```

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.1 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.11.0
[pip3] torch-summary==1.4.5
[pip3] torchaudio==0.9.0
[pip3] torchsampler==0.1.1
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] libblas                   3.9.0                     9_mkl    conda-forge
[conda] libcblas                  3.9.0                     9_mkl    conda-forge
[conda] liblapack                 3.9.0                     9_mkl    conda-forge
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.3.0            py38h9ed2024_1  
[conda] mkl_fft                   1.3.0            py38h4a7008c_2  
[conda] mkl_random                1.2.1            py38hb2f4e1b_2  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch-summary             1.4.5                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchsampler              0.1.1                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by justinchuby** [comment]
Could you share a minimum self-contained example that can reproduce the issue, along with the differences you have observed? This will help us locate any errors effectively. Thanks!

**Comment by shubhambhokare1** [comment]
Hi @drorlederman,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
