### ISSUE TITLE
create input tensor on GPU device takes extremely long time when inferencing with transformer models

### ISSUE THREAD

**Issue by LydiaXiaohongLi** [pytorch/pytorch#80129]
### 🐛 Describe the bug

Hi Team, Good day!

Problem: create input tensor on GPU device takes extremely long time when inferencing with transformer models

Description: 

I use below sample full code, to examine inferencing speed with BERT model, it uses bert-base-multilingual-uncased from huggingface's implementation, takes random 5000 texts from SQuAD1. To speed up, the code is optimised so that it first tokenize all the 5000 texts, and sort the tokenized texts by number of tokens, and batching texts with similar length in one batch sent for inference. 

Particularly, I have recorded the time used for model inferencing, below line 
```python
model(input_ids = input_ids_batch, attention_mask = attention_mask_batch)
```

And the time took to put input tensor created to GPU device 
```python
input_ids_batch = input_ids_batch.to(device)
```

Noticed, with maximum sequence length of 128, when set with a big batch size, say 512, the time used for model inference is blazingly fast, less than 0.1s for all 5000 texts, but it takes insanely long time, almost 2s in total to put input tensor to GPU for all 5000 texts. 

However, with same maximum sequence length of 128, when set with a small batch size, say 16, the time used for model inference slows down to more than 2s for all 5000 texts, but it speeds up to put input tensor to GPU, which takes less than 0.2s for all 5000 texts. 

My question is, irregardless of batch_size, put input tensor to GPU should not take long, as the size of input tensor is only batch_size * max_seq_len float matrix, which occupies extremely small memory. We would like to enjoy the fast inferencing speed brought by bigger batch, without being bottlenecked by the step of creating input tensor to GPU. 

I have tried to create input tensor directly on GPU with below code, is still the same story.
```python 
input_ids_batch = torch.tensor(input_ids_batch, device=device)[:,:args.max_seq_len]
```

Interestingly, I noticed, 

-----Scenario 1 ---- 
When I didnt order the text by number of tokens, it takes longer to put input tensors to GPU, when previous padded input tensor of batch is bigger matrix (i.e. batch_size * max_seq_len), and faster when previous padded input tensor is of smaller matrix. 

-----Scenario 2---- 
when I create the mode and put on GPU, using below code  
```python 
model = BertModel.from_pretrained('bert-base-multilingual-uncased', add_pooling_layer=False)
model.eval()
model = model.to(device)
```
but skip the inferencing in every batch, i.e. comment out below code
```python
res = model(input_ids = input_ids_batch, attention_mask = attention_mask_batch)
```
The very first time, to put input tensors to GPU (max_seq_len=128, batch_size=512), is very long, takes more than 3s for a batch of 512 texts. But subsequent batches of the rest of 5000 texts, it is blazingly fast, ~0.01s or faster for every batch of 512 texts. 

-----Scenario 3 ---- 
when I didnt even create the model on GPU, i.e. comment out both of the code above in Scenario 1. Put input tensors to GPU (max_seq_len=128, batch_size=512) is always fast, less than 0.01s for every batch of 512 texts, including the very first one. 

Many thanks! 

The full code: 

```python
from transformers import BertModel, BertTokenizerFast
import numpy as np
from tqdm.autonotebook import trange
import time
import torch
import itertools
from torchtext.datasets import SQuAD1

device = 0
tokenizer = BertTokenizerFast.from_pretrained('bert-base-multilingual-uncased')
model = BertModel.from_pretrained('bert-base-multilingual-uncased', add_pooling_layer=False)
model.eval()
model = model.to(device)

squad = SQuAD1(split='train')
texts = []
for i in range(len(squad)):
    texts.append(next(squad)[0])
np.random.seed(1)
texts = np.random.choice(texts, size=5000)


batch_size = 512
max_seq_len = 128

timings_inference = []
timings_put_input_ids_on_device = []
with torch.no_grad(): # with or without this seems no difference
    # 1. Tokenization
    input_ids = tokenizer._batch_encode_plus(list(texts), return_attention_mask=False, return_token_type_ids=False)['input_ids']

    # 2. sort by sequence length (so that we group length of similar length in one batch) 
    # -- maybe this is not required? as majority time spent on replace input_ids_batch on device??
    length_sorted_idx = np.argsort([len(emb) for emb in input_ids])
    input_ids_sorted = [input_ids[idx] for idx in length_sorted_idx]


    for start_index in trange(0, len(input_ids), batch_size, desc="Batches", disable=True):

        input_ids_batch = input_ids_sorted[start_index:start_index+batch_size]        
        # 3.1 padding 
        input_ids_batch = list(zip(*itertools.zip_longest(*input_ids_batch, fillvalue=0)))

        input_ids_batch = torch.tensor(input_ids_batch)[:,:max_seq_len]
        # Tried to directly create the tensor on GPU (but no luck)
        # input_ids_batch = torch.tensor(input_ids_batch, device=device)[:,:max_seq_len]

        start_time = time.time()
        # Takes long, if previous round in the loop, input_ids_batch is big matrix (batch_size * max_seq_len, int)
        input_ids_batch = input_ids_batch.to(device)
        timings_put_input_ids_on_device.append(time.time()-start_time)

        # 3.2 calculate attention mask
        attention_mask_batch = torch.where(input_ids_batch!=0,1,0).to(device)

        # 3.3 inferencing
        start_time = time.time()
        res = model(input_ids = input_ids_batch, attention_mask = attention_mask_batch)
        timings_inference.append(time.time()-start_time)
        print(f"from {start_index} to {start_index+batch_size},  inferencing time {timings_inference[-1]}s, put input_ids on gpu {timings_put_input_ids_on_device[-1]}s,")

print(f"Total, inferencing time {sum(timings_inference)}s, put input_ids on gpu {sum(timings_put_input_ids_on_device)}s,")

````

### Versions

torch==1.10.1+cu113
torchtext==0.11.1
transformers==4.12.5

Python==3.9.2

NVIDIA-SMI 515.43.04
Driver Version: 515.43.04
CUDA Version: 11.7  

GPU: NVIDIA A100-SXM, 81920MiB memory

cc @ngimel

**Comment by ptrblck** [comment]
>Noticed, with maximum sequence length of 128, when set with a big batch size, say 512, the time used for model inference is blazingly fast, less than 0.1s for all 5000 texts, but it takes insanely long time, almost 2s in total to put input tensor to GPU for all 5000 texts.

> However, with same maximum sequence length of 128, when set with a small batch size, say 16, the time used for model inference slows down to more than 2s for all 5000 texts, but it speeds up to put input tensor to GPU, which takes less than 0.2s for all 5000 texts.

CUDA operations are executed asynchronously so you would need to synchronize the code via `torch.cuda.synchronize()` before starting and stopping the timers which is not the case in your posted code. 
The very first CUDA operation will initialize the CUDA context, load the kernels etc. and is expected to be slow.
Since you are not synchronizing your timers will accumulate the previous runtimes when a sync is enforced and give wrong results.

**Comment by LydiaXiaohongLi** [comment]
Got it, Thank you very much!
