### ISSUE TITLE
[torch::deploy] Cache line optimization in LoaderBalancer has negative effect to performance

### ISSUE THREAD

**Issue by zhuzilin** [pytorch/pytorch#80137]
### 🐛 Describe the bug

When experimenting with `torch::deploy`, we observed that the LoadBalancer (`LoadBalancer::acquire()`) has bad performance, i.e. when running resnet18 with 4 interpreters on 1 gpu, the performance with load balancer (`model(inputs)` directly) will give us 60% gpu utilization, while if we designate a fixed interpreter to each thread, we will reach 100% gpu utilization and a much larger throughput.

After some digging in the code, it seems that if we remove the `8*` optimization for cache line here:
https://github.com/pytorch/pytorch/blob/072311bb28c74eca24acc9bf20288c4de8421be9/torch/csrc/deploy/deploy.h#L92-L93
the performance with LoadBalancer will be come back to normal.

The reason for this issue is that cache line optimizaiton may have a negative impact to machines with small L1/L2 cache. And I wonder if we could set this optimization as optional in `torch::deploy`?

Code we used is here: https://gist.github.com/zhuzilin/6235f16c2dad24355f9f61a3f6e77b0d

Thank you for your time on this issue :) 

### Versions

nightly

cc @wconstab

**Comment by d4l3k** [comment]
@zhuzilin can you share what machines you're using (cpu model, cache sizes, manufacturer)? `lscpu` 

It's surprising that something like this would be the bottleneck given all of the other much heavier computation

With just 4 interpreters it seems like 256 bytes (8 * 4 * 8) shouldn't make much of an impact on L1

Can you capture a perf trace under the two different configurations?

**Comment by d4l3k** [comment]
I chatted with @zdevito about this.

Generally we recommend that you use 1 interpreter thread per GPU. Multi parallelism on a GPU doesn't really work well and can cause performance issues. If you need more throughput, batching at the application level is the recommended approach

Did you change lines other than https://github.com/pytorch/pytorch/blob/072311bb28c74eca24acc9bf20288c4de8421be9/torch/csrc/deploy/deploy.h#L93 or just that one? If you just changed the memset it likely forced all of the requests on to a single interpreter thread (which would be recommended).

Both acquireSession and model(...) use the LoadBalancer so the performance should be very similar.

**Comment by zhuzilin** [comment]
@d4l3k 
> can you share what machines you're using (cpu model, cache sizes, manufacturer)? `lscpu`
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           165
Model name:                      Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Stepping:                        5
CPU MHz:                         4000.022
CPU max MHz:                     4800.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5799.77
Virtualization:                  VT-x
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
                                 ia prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RS
                                 B filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rd
                                 tscp lm constant_tsc art arch_perfmon pebs bts 
                                 rep_good nopl xtopology nonstop_tsc cpuid aperf
                                 mperf pni pclmulqdq dtes64 monitor ds_cpl vmx s
                                 mx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid s
                                 se4_1 sse4_2 x2apic movbe popcnt tsc_deadline_t
                                 imer aes xsave avx f16c rdrand lahf_lm abm 3dno
                                 wprefetch cpuid_fault epb invpcid_single ssbd i
                                 brs ibpb stibp ibrs_enhanced tpr_shadow vnmi fl
                                 expriority ept vpid ept_ad fsgsbase tsc_adjust 
                                 bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx
                                  smap clflushopt intel_pt xsaveopt xsavec xgetb
                                 v1 xsaves dtherm ida arat pln pts hwp hwp_notif
                                 y hwp_act_window hwp_epp pku ospke md_clear flu
                                 sh_l1d arch_capabilities
```
> Can you capture a perf trace under the two different configurations?

I'll try to do perf trace and also double check if the 8* offset is really the issue.

> Did you change lines other than ... or just that one?

I've removed all the "8*" in deploy.cpp and deploy.h.

> Both acquireSession and model(...) use the LoadBalancer so the performance should be very similar.

I'm refering to the `acquireSession` call here:
https://github.com/pytorch/pytorch/blob/7bf1b1dc31132f0e599ddbef7cd639677b6fd542/torch/csrc/deploy/deploy.cpp#L155-L156

I think the different between the two branch is that `acquireOne` will run `LoaderBalancer::acquire()`, while `acquireSession` don't need that.

**Comment by d4l3k** [comment]
@zhuzilin thanks for sharing -- can you share the patch/commit that removes the `8*` just want to reproduce this locally

**Comment by zhuzilin** [comment]
> can you share the patch/commit that removes the 8* just want to reproduce this locally

@d4l3k  Our test machine were rebooted this weekend and I just ran the patch without `8*` again and observed no performance improvement... I may misconfigure the build cache during last test, sorry about that...

However, we still observed that the code with "pin interpreter to thread" is faster than the one that uses load balancer (as the data in the slide we shared last Friday). So there may still be some performance issue with the load balancer.

**Comment by d4l3k** [comment]
For anyone else coming here:

If pinning the interpreter to thread/manual interpreter management works better for your use case that's a totally supported option. Manual thread management can often be faster since it doesn't need to do any cross core/thread syncronization.

**Comment by colin2328** [comment]
@zhuzilin , per @d4l3k  comment -> I had thought you had solved this through your own thread management already? Is this sitll needed for you, or can we close?
