### ISSUE TITLE
ArrayRef length issue when export wav2vec model to onnx

### ISSUE THREAD

**Issue by zhijianli** [pytorch/pytorch#80130]
## ❓ Questions and Help
Hi

I have some problem converting my wav2vec model into onnx. 

In the extract_features method of the Wav2Vec2Model class, I added an init_onnx method, hoping to generate onnx.
![image](https://user-images.githubusercontent.com/33283007/175247653-76fb33d1-397c-4b5e-abbf-fc60b336e632.png)

But the result is wrong

```
 File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 727, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 533, in _model_to_graph
    torch._C._jit_pass_onnx_assign_output_shape(graph, output_tensors, out_desc, _onnx_shape_inference)
RuntimeError: ArrayRef: invalid index Index = 3; Length = 3
```

I want to know why？

#### Code
```
     def extract_features(self, source, padding_mask, mask=False, layer=None):

        self.init_onnx(source, padding_mask, mask, layer)

        res = self.forward(
            source, padding_mask, mask=mask, features_only=True, layer=layer
        )
        return res

    def init_onnx(self,source, padding_mask, mask, layer):

        model = self
        model.eval()
        encoder_input = (torch.randn(1, 800), torch.randn(1, 800), mask,True, layer)
        torch.onnx.export(model,
                          encoder_input,
                          "fairseq_transformer2.onnx",
                          export_params=True,
                          opset_version=12,
                          operator_export_type=torch.onnx.OperatorExportTypes.ONNX
                          )
```

#### What's your environment?
fairseq Version：1.0.0a0+0dfd6b6
PyTorch Version ：1.11.0+cu113
OS ：Ubuntu 20.04.4 LTS
How you installed fairseq: pip3
Python version：3.8.5

**Comment by jbschlosser** [comment]
Hey @zhijianli, I suggest opening a thread for help on the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to get assistance there. Note that the issues here are reserved for issues within PyTorch itself. Please feel free to reopen if investigation reveals a likely PyTorch bug - thanks!

**Comment by tanmc123** [comment]
@zhijianli Hi，I got exactly the same problem. Have you solved it? Is there any hint please? Thank you very much!
