### ISSUE TITLE
Change `@pytorchbot merge` merged failed to Matched rule superuser to include all users

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#80153]
### 🚀 The feature, motivation and pitch

When `@pytorchbot merge` is used from an external user but the code requires a review by a PyTorch team member it gives the below error which is confusing because anyone from the PyTorch team can stamp to allow a merge and not just the listed names. It should just say anyone from Meta should review this.

```
Merge failed due to Matched rule superuser, but PR https://github.com/pytorch/pytorch/pull/79424 was not reviewed yet by any of: bradleyhd, prigoyal, njuvekar, brad-mengchi, simonhollis, ...
Raised by https://github.com/pytorch/pytorch/actions/runs/2490788608
```

**The Ask:**
Change the `superuser` rule failure message to say "The PR has not been reviewed by a person with write access to these  files"

cc: @malfet

**Comment by suo** [comment]
There is an ellipsis, are you saying it's not clear that this list is super long (contains all meta people)?

**Comment by msaroufim** [comment]
Yes exactly

**Comment by ZainRizvi** [comment]
The messaging here has actually been fixed for some time now
