### ISSUE TITLE
Backpropagation not working on KL divergence loss function due to data type mismatch

### ISSUE THREAD

**Issue by padmaksha18** [pytorch/pytorch#80158]
### 🐛 Describe the bug

Backpropagation not working on KL divergence loss function due to data type mismatch

```
kl_loss = nn.KLDivLoss(reduction="batchmean")

input = torch.log_softmax(torch.randn(3, 5, requires_grad=True), dim=1)

target = torch.softmax(torch.rand(3, 5), dim=1).double()

output = kl_loss(input, target)

output.backward()

# RuntimeError: Found dtype Float but expected Double

````

### Versions

Using Pytorch 1.2 on Google Colab

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by Lezcano** [comment]
I'll put up a PR fixing all this, making `kl_div` a composite, next week.
