### ISSUE TITLE
[RFC] Module specific workflows

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#80161]
@jeffdaily asked for a ciflow label to trigger ROCm jobs because `ciflow/trunk` runs a lot of non-rocm things. This is totally reasonable and likely to be a common request from module maintainers, so it's worth designing a process that can scale well.

The problem definition is: module maintainers want to be able to run a set of jobs specific to their module on PRs. Sometimes those jobs are a subset of the `trunk` or `periodic` jobs that we just want PR-time signal on, sometimes they wholly custom to a module (experimental tests, optional tests, etc.).

Here is our proposal. I phrase it specific to ROCm, but it can be read as generic across any module (e.g. onnx, functorch).
- The Infra team will continue to maintain the _core workflows_ (`pull`, `trunk`), etc. as they are today, so no change there.
  - This includes ever-stricter standards on time-to-signal and reliability, since the core workflows are run for all PT devs.
  - It also includes guarantees that the core workflows will be green; i.e. we will revert if one is broken.
- We define a ROCm-specific GitHub Actions workflow.
- The workflow is scoped to only affect ROCm maintainers (or other interested parties).
  - Initially, this means that it will be triggered by `ciflow/rocm` label only (not pull requests or master).
  - In the future, one could imagine tracking a mirror of the master branch with custom validation jobs.
- The workflow is maintained by the ROCm maintainers.
  - There are no restrictions on what stuff can be put in there. The only caveat is that we need to make sure usage of shared global resources (e.g. the AMD runners) does not affect core workflows.
  - The PyTorch Infra team will not maintain the workflow; that is, breakages to the workflow will not be triaged by the infra team and we will not auto-revert PRs based on failures in the workflow.
  - Notably, keeping the workflow in sync with ROCm jobs in core workflows is the responsibility of the ROCm maintainers. We will develop linting/syncing infra to help there though.

The initial version of the ROCm workflow will be a strict subset of what we run on `trunk`, but one could imagine putting arbitrary ROCm-specific testing there.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jithunnair-amd** [comment]
@suo Do we have any plan forward for this? It'd be really helpful for us to at least test PRs that could have major implications on ROCm builds even if the ROCm CI builds are temporarily disabled in pull/trunk/periodic (as it the case right now with ROCm distributed CI)

**Comment by suo** [comment]
I was sort of waiting for a thumbs up that you liked this proposal lol. If we're all good, it's fairly easy to implement

**Comment by jithunnair-amd** [comment]
@jeffdaily @suo Should we revive this effort, if the motivation for this is still valid?
