### ISSUE TITLE
[MPS] segmentation fault when multiplying two scalar tensors

### ISSUE THREAD

**Issue by qqaatw** [pytorch/pytorch#80165]
### 🐛 Describe the bug

When multiplying two scalar tensors in mps kernel, a segmentation fault occurs.
```mm
MPSGraphTensor* aTensor = [mpsGraph constantWithScalar:.4f
                                               //shape:@[@1]  << without specifying shape
                                              dataType:MPSDataTypeFloat32];
MPSGraphTensor* bTensor = [mpsGraph constantWithScalar:.5f
                                               //shape:@[@1]
                                              dataType:MPSDataTypeFloat32]; 
MPSGraphTensor* secondCondTensor = [mpsGraph multiplicationWithPrimaryTensor: aTensor
                                                             secondaryTensor: bTensor
                                                                        name: nil];
```

### Versions

PyTorch version: 1.13.0a0+git44764f1
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==1.13.0a0+git2148e6b
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.0a0+git2148e6b           dev_0    <develop>

cc @kulinseth @albanD

**Comment by malfet** [comment]
Hmm, I'm not sure what this one as about. Can you please provide a reproducer?
I can not repro the crash by running the following:
```
% python -c "import torch; print(torch.tensor(1, device='mps')+torch.tensor(2, device='mps'))"
tensor(3, device='mps:0')
```

**Comment by qqaatw** [comment]
@malfet 

Please clone this branch https://github.com/qqaatw/pytorch/tree/add_huber_loss_mm

Build and run the following: 

```bash
python -m pytest -vv -s test/test_mps.py -k test_huber_loss # works fine
```

Then, comment out the shape arguments below like what I do in the issue content.

https://github.com/qqaatw/pytorch/blob/d49ea958ee31478077567e239d2157680aa89f91/aten/src/ATen/native/mps/operations/LossOps.mm#L1079-L1084

Build and run the following again:

```bash
python -m pytest -vv -s test/test_mps.py -k test_huber_loss # segmentation fault
```

**Comment by malfet** [comment]
@qqaatw I struggle to understand what is has to do with PyTorch? This sounds like a bug that should be filed against Apple (which develops the framework), rather than PyTorch that just uses it.

**Comment by DenisVieriu97** [comment]
Thanks @qqaatw for filling this issue - I was able to reproduce locally as well. I'll check with the relevant engineers and update you back

**Comment by DenisVieriu97** [comment]
Hi @qqaatw, 

This issue has been fixed in [macOS 13 beta 2](https://developer.apple.com/news/releases/?id=06222022c). In order to avoid doing checks based on the OS in PyTorch's MPS backend, I think the best would be to specify directly the shape (`[mpsGraph constantWithScalar: x shape:@[@1] ... ];`.

**Comment by qqaatw** [comment]
Hi @DenisVieriu97,

Thank you so much for your quick feedback! 

Maybe this issue is worth noting on the [wiki](https://github.com/pytorch/pytorch/wiki/Adding-Op-for-MPS-Backend), which prevents people who want to contribute new mps ops from running into the bug.

**Comment by kulinseth** [comment]
@qqaatw , I agree with @DenisVieriu97, please use shape for now to avoid OS specific checks unless absolutely needed. That's a good point, we can add a section to note issues such as these.
