### ISSUE TITLE
[NVFuser] Choose partitioner op list based on supported prim decompositions

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#80188]
### 🚀 The feature, motivation and pitch

Currently the partitioner uses a list of supported ops that was copied from torchscript.

But for the fx -> prims -> nvfuser approach, we want the supported op list to instead be based on the list of ops that can be decomposed to prims. This could be generated by tracing through aten ops and trying to decompose them, and seeing whether or not they can be fully decomposed to prims.

**Comment by jjsjann123** [comment]
I'm tagging #81820 to this issue

**Comment by IvanYashchuk** [comment]
https://github.com/pytorch/pytorch/pull/81764 adds a context manager that replaces torch calls with refs only if the decomposition to prims can be executed by nvFuser.

The main component there is what's now called `get_isolated_graphmodule`, allowing to acquire the FX graph without interfering with the outer tracing. Using that it shouldn't be difficult to write an FX transformer similar to the context manager. Or use the new context manager together with `DecompositionInterpreter` here https://github.com/pytorch/pytorch/blob/e68583b4d180066b8e4f108e0d23176a2676421c/torch/fx/experimental/proxy_tensor.py#L376-L377
