### ISSUE TITLE
[feature request] Add TensorFlow's bfloat16

### ISSUE THREAD

**Issue by Wulfsta** [pytorch/pytorch#8021]
TensorFlow defines a floating point number with 16 bits that is different from the IEEE 754 standard; one bit is for the sign, eight are exponent bits, and seven are mantissa bits. It is essentially a 32 bit float with less precision. More information can be found [here](https://github.com/tensorflow/tensorflow/blob/1e44b15ff02fe3bf4764189eb1b796602d669c3e/tensorflow/core/framework/bfloat16.h) and [here](https://en.wikipedia.org/wiki/Bfloat16_floating-point_format).

**Comment by soumith** [comment]
it's not efficient to use this format on anything other than the TPU, and for network transfers. Adding such a format for the full API (to run on CPU/GPU) would be quite slow.

**Comment by Wulfsta** [comment]
If something like this were implemented, what kind of slowdown in comparison to float32 operations would be expected? Trading speed and precision for memory is still of interest for some applications; for instance [SRGAN](https://arxiv.org/abs/1609.04802) and [Gatys Algorithm](https://arxiv.org/abs/1508.06576).

**Comment by soumith** [comment]
for doing compute in bfloat16 (i.e. mul, add etc. are done in bfloat16) on CPU and GPU I expect a 10x slowdown.

**Comment by apaszke** [comment]
@soumith actually it might be possible to implement it efficiently. If bfloat16 is just the first 16 bits chopped off a 32-bit float, then you could do some union tricks to embed those 16 bits into the high part of the float when you start the kernel, do math in fp32 and slice out the first 16 bits with a union again, save that to memory.

**Comment by Wulfsta** [comment]
@apaszke this is a bit of an unusual request, but could you give a short summary of what would need to be added and modified in the codebase to implement this? I'd be willing to work on it if it I had some guidance.

**Comment by apaszke** [comment]
Hmmm that would be a relatively hard task at the moment, especially with all the moving parts. I think it's better to wait until we will be able to have open registration of tensor types, and then have it as an extension.

**Comment by ezyang** [comment]
Well, we're working on complex numbers out of tree, and bfloat16 seems like it would be fairly similar...

**Comment by soumith** [comment]
@ezyang for bfloat16 we should wait on open registration of types. Complex numbers is a much more straightforward decision (technical feasibility wise and strategically) to have in-tree enums and copies, and do the rest of development out-of-tree. The same is not obvious for bfloat16

**Comment by ftian1** [comment]
hello, @soumith 
now Intel is starting support bfloat16 on new generation h/w. https://software.intel.com/en-us/download/bfloat16-hardware-numerics-definition

we are considering adding such support to pytorch. do you have any insight to share with us?

**Comment by Lyken17** [comment]
May I know the progress of adding bfp16?

**Comment by mrshenli** [comment]
cc @ailzhang

**Comment by gchanan** [comment]
This has been added.
