### ISSUE TITLE
'ThnnConv2DBackward' object has no attribute 'padding'

### ISSUE THREAD

**Issue by kyuusaku** [pytorch/pytorch#8024]
For Pytorch 0.2.0 and 0.3.1, we can access the layer settings by accessing `grad_fn` objects. But in Pytorch 0.4.0, this property seems disappear. 

For example,

```
import torch
import torch.nn as nn

net = nn.Conv2d(3, 12, kernel_size=3, stride=2, padding=1, dilation=1, groups=3, bias=False)
input = torch.rand(1,3,224,224,requires_grad=True)
output = net(input)
output.grad_fn.next_functions[0][0].padding

AttributeError: 'ThnnConv2DBackward' object has no attribute 'padding'
```

Also, it seems hard to recognize the groups of nn.Conv2d.

**Comment by soumith** [comment]
you were trying to rely on an unsupported feature, that we probably broke. What exactly are you trying to do, so that we can suggest a workaround or give you a long-term solution?

**Comment by kyuusaku** [comment]
Hi, @soumith . Thanks for your reply. We want to convert pytorch model to other frameworks, such as caffe. It needs the network graph and corresponding parameters for conversion. I also checked out onnx, which seems not support for U-net.

**Comment by soumith** [comment]
@kyuusaku you can trace a model accurately with pytorch and get the graph.
For example:

```
traced_model = torch.jit.trace(input)(model)
fwd = traced_model._get_method('forward')
print(fwd.graph)
```

**Comment by ys198918** [comment]
hi, @kyuusaku . did you found a way to get the correspanding parameters ?

**Comment by daodao316** [comment]
@soumith ,I want to convert pytorch model to other frameworks. When I get the graph, how can I get the parameters form it ?

**Comment by daodao316** [comment]
@soumith  Once I get the graph, I notice that I can get access to the Nodes and Inputs (I assume they are Nodes containing weights, including the input tensor).
I want to get access to the weights inside the nodes, but I cannot find any instructions related to get the weight values into python.

**Comment by blueardour** [comment]
@soumith 
I tried your code, however it reported 

`
----> fwd = traced_model._get_method('forward')    AttributeError: 'function' object has no attribute '_get_method'
`
Do you have any advise how to fix it.  My torch version is 0.4.1

**Comment by heitorschueroff** [comment]
@kyuusaku I'm closing this issue, feel free to reopen if it is still a problem for you.
