### ISSUE TITLE
 lengths array has to be sorted in decreasing order

### ISSUE THREAD

**Issue by Blues5** [pytorch/pytorch#8026]
[train.txt](https://github.com/pytorch/pytorch/files/2061754/train.txt)
[data.txt](https://github.com/pytorch/pytorch/files/2061755/data.txt)
[model.txt](https://github.com/pytorch/pytorch/files/2061756/model.txt)
 i'm having running the encoder. the error i'm getting--
/usr/local/lib/python2.7/dist-packages/torch/nn/utils/rnn.pyc in pack_padded_sequence(input, lengths, batch_first)
     77 
     78             if current_length > new_length:  # remember that new_length is the preceding length in the array
---> 79                 raise ValueError("lengths array has to be sorted in decreasing order")
     80             batch_size -= 1
     81             current_length = new_length

**Comment by SsnL** [comment]
Hi, as the error message says, you should sort your array before feeding into `pack_padded_sequence`
