### ISSUE TITLE
MPS strange warning

### ISSUE THREAD

**Issue by mdciri** [pytorch/pytorch#80278]
### 🐛 Describe the bug

I am currently writing a training loop for image segmentation using my new mac which has M1 GPU.

When I pass my image tensor `X` to my device:

`device = torch.device("mps")`
`X = X.to(device)`
    
I get this:

/Users/marco/miniforge3/envs/torch/lib/python3.9/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))

How can I fix this? Thanks in advance

### Versions

python: 3.9.13
torch: 1.13.0
torchaudio: 0.14.0
torchvision: 0.14.0

cc @kulinseth @albanD

**Comment by malfet** [comment]
Lack of bitwise ops is tracked in https://github.com/pytorch/pytorch/issues/77764 but can you please provide a bit more complete example?

**Comment by hackroid** [comment]
> Lack of bitwise ops is tracked in #77764 but can you please provide a bit more complete example?

`import torch
device = torch.device('mps')
print(f" - device : {device}")
sample = torch.Tensor([[10, 20, 30], [30, 20, 10]])
print(f" - cpu tensor : ")
print(sample)
sample2 = sample.to(device)   # warning displayed
print(f" - gpu tensor : ")
print(sample)`

**Comment by veriff-javiervgd** [comment]
Happening the same here with the new pytorch version 1.12

```python
In [1]: T.__version__
Out[1]: '1.12.0'

In [2]: T.backends.mps.is_built()
Out[2]: True

In [3]: T.backends.mps.is_available()
Out[3]: True

In [4]: x = T.randn(5,5)

In [5]: x
Out[5]:
tensor([[-1.3372, -0.1323,  2.0674,  0.2852, -0.4266],
        [-0.0311,  1.0278,  1.3286,  0.7991, -0.8794],
        [ 0.0854, -0.5539, -1.2456,  0.9689, -1.9682],
        [-0.5811,  0.1709, -0.0862,  1.1137,  0.3655],
        [ 2.1049, -0.6583,  1.9883,  0.4995, -0.4086]])

In [6]: x.to("mps")
Out[6]: /opt/homebrew/lib/python3.9/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))

tensor([[-1.3372, -0.1323,  2.0674,  0.2852, -0.4266],
        [-0.0311,  1.0278,  1.3286,  0.7991, -0.8794],
        [ 0.0854, -0.5539, -1.2456,  0.9689, -1.9682],
        [-0.5811,  0.1709, -0.0862,  1.1137,  0.3655],
        [ 2.1049, -0.6583,  1.9883,  0.4995, -0.4086]], device='mps:0')
```

**Comment by ifsheldon** [comment]
Also have this weird error but in a different case.

Try this
```python
# in test_torch.py
import torch

mps = torch.device("mps")
a = torch.ones(2, 3, 4, device=mps)
print(a * 2)
```
and run `python test_torch.py`
I got:
```
/Users/user/miniconda3/lib/python3.9/site-packages/torch/_tensor_str.py:103: UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at  /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1656352453927/work/aten/src/ATen/mps/MPSFallback.mm:11.)
  nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]], device='mps:0')
```

**Comment by kulinseth** [comment]
Hi @mdciri , @ifsheldon , @hackroid and @veriff-javiervgd 

This is indeed expected. Currently we don't have support for bitwise ops which is used while `print` is applied on a  tensor on MPS device. For formatting the output those ops are used and currently we fallback to CPU hence the warning. We are looking into adding it as discussed here.
