### ISSUE TITLE
ONNX exporter uses onnx::Gather (making a copy) where onnx::Slice should be used

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#80271]
### 🐛 Describe the bug

While exporting the following code, we have found that Torchscript trace() worked correctly, while onnx.export() generated onnx::Gather (creating a copy) operation where onnx::Slice() should have been - therefore, updates done via that slice, were lost in ONNX version: 
 
https://github.com/VahidooX/NeMo/blob/casual_conformer_lookahead_newdesign_prenorm_mlp/nemo/collections/asr/parts/submodules/causal_convs.py#L120
https://github.com/VahidooX/NeMo/blob/casual_conformer_lookahead_newdesign_prenorm_mlp/nemo/collections/asr/parts/submodules/multi_head_attention.py#L202

Here, I had to modify source code to explicitly use slice on left-hand side of the assignment, to make ONNX exported understand it correctly: 
 https://github.com/VahidooX/NeMo/pull/3/files
 
 Expected behavior: 
 - No source chances should have been necessary. Clearly, both Pytorch and TorchScript get the semantic correctly, while ONNX loses modifications made via slice variable.
 
 
 

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+bd13bc6
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.11.0-37-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: GPU 0: Quadro GV100
Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.15.1.dev20220523+cuda11.6.torch1.12.0a0
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+bd13bc6
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchaudio==0.11.0+6297e97
[pip3] torchmetrics==0.8.2
[pip3] torchvision==0.13.0a0
[conda] k2                        1.15.1.dev20220523+cuda11.6.torch1.12.0a0          pypi_0    pypi
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h1d589f8_2    conda-forge
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+bd13bc6          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchaudio                0.11.0+6297e97           pypi_0    pypi
[conda] torchmetrics              0.8.2                    pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi

**Comment by AllenTiTaiWang** [comment]
Hi @borisfom ,

Could you provide a repro? A small script and model but can reproduce the issue would be ideally.

**Comment by borisfom** [comment]
Here's a simple repo: note the generated ONNX clearly ignores cache_next modification, while TorchScript is correct.
Now if you replace "self.cache = Cache1()" with "self.cache = Cache()" (equivalent Torch code) - TorchScript would stay the same, but ONNX would now also trace cache_next assignment properly.

```
import torch

class Cache(torch.nn.Module):
    def forward(self, key, cache_next):
        cache_next[1,0,1] = cache_next[1,0,1]+2*key
        return key

class Cache1(torch.nn.Module):
    def forward(self, key, cache_next):
        cache_line = cache_next.select(0,1)
        cache_line[0,1] = cache_line[0,1]+2*key
        return key

class Cache3(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.cache = Cache1()
    def forward(self, key):
        cache_next = torch.zeros((2,2,2))
        self.cache(key, cache_next)
        key = key + cache_next[1,0,1]
        return key

key = torch.randint(1,10,(1,))

cache3 = Cache3().eval()
tt = torch.jit.trace(cache3, (key))
tt = torch.jit.optimize_for_inference(torch.jit.freeze(tt))
print(tt.code)

torch.onnx.export(cache3, (key),  'c3.onnx', opset_version=14, verbose=True)

```

**Comment by AllenTiTaiWang** [comment]
Tried to replace onnx::Gather with onnx::Slice, and it's giving me the same thing. I think both of them don't support in-place calculation. It might be something in converter code that handles this.

**Comment by justinchuby** [comment]
@AllenTiTaiWang Even though slice behaves the same, there may be value using it for a more semantically meaningful graph which will also allow for better backend optimization.

**Comment by justinchuby** [comment]
That said, onnx tensors are immutable so a caching mechanism will require more careful thought.

**Comment by borisfom** [comment]
Yes this is not Gather vs Slice issue, but rather a semantic difference between Pytorch select operations (l-values that point to the memory of its operand) and ONNX (making a copy). To properly translate valid Pytorch code like that, a wrapper needs to be added to simulate in-place operation. Should I rename this issue or create a new one ?

**Comment by justinchuby** [comment]
Thanks for the explanation. I'd feel free to keep this open.
