### ISSUE TITLE
Brevitas Trained Model Does Not Get Exported To ONNX

### ISSUE THREAD

**Issue by aydinkaraa** [pytorch/pytorch#80304]
### 🐛 Describe the bug

I have trained my brevitas model with Brevitas. Now I am trying to export my onnx model to use it with finn. As I try to export my model with the command below:

```
build_dir = "./"

base_file_name = "my_model"

bo.export_finn_onnx(my_model, (1, 3, 1024), build_dir + "/{}.onnx".format(base_file_name))
```
I get the error message as:

> TypeError: max_pool1d(): argument ‘kernel_size’ (position 2) must be tuple of ints, not Tensor,

In case if it helps, my max pool 1d line of the trained model is shown below, I have changed the code line after reading some comments, here is the new version:

```
 pool_size = int(xb.size(-1))
 xb = F.max_pool1d(xb, pool_size).squeeze()
```
On its old version this line was:
`xb = nn.MaxPool1d(xb.size(-1))(xb)`

On both cases I was getting the exact same error.

I couldn’t figure it out how to export my .pth extended file. If you help I will be appreciated. Thank you

### Versions

Pytorch version: 1.10.2

**Comment by AllenTiTaiWang** [comment]
Hi @aydinkaraa ,

I don't think this is an API we provide. You might want to raise an issue perhaps [here](https://github.com/Xilinx/brevitas).
If you are interested in using torch.nn.export to export your model, or it failed, please let me know.

**Comment by justinchuby** [comment]
You may want to make sure the kernel_size is not a dynamic number (`.size()`) but is rather static. Is there a way you can know the value of `xb.size(-1)` beforehand? To test, try tracing your model with `torch.jit.trace` https://pytorch.org/docs/stable/generated/torch.jit.trace.html and verify that there is no error when the model is traced.

**Comment by shubhambhokare1** [comment]
Hi @aydinkaraa,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
