### ISSUE TITLE
[ONNX] Only prim ops are allowed to not have a registered operator but aten::mul doesn't have one either

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/pytorch#80300]
### 🐛 Describe the bug

Error happens when trying to export a torch model with variable input size to onnx after being scripted (not traced).

### Versions

torch v1.11.0

**Comment by AllenTiTaiWang** [comment]
Hi @MohamedAliRashad ,

Could you please upload the script that I can reproduce your error? It doesn't have to as complicated as the original one. Just a simple one that point out the issue. And have you tried reproduce it with trace? or it doesn't exist in tracing?

**Comment by thiagocrepaldi** [comment]
@MohamedAliRashad this issue has been closed as stale as a runnable repro was not provided.
If this issue is still relevant repros on latest torch, reopen this issue and please attach a runnable repro

**Comment by AsiaCao** [comment]
Hi @thiagocrepaldi , @titaiwangms,


I got a similar error. Below is the code to reproduce it.
I wrote it as an unit test (pytest) and hope you can run it easily.
I'm just curious what does the error message mean and how to resolve it.


```python
import cv2
import torch
import torchvision.transforms.functional as F

def test_rescale_with_padding():
    img = torch.tensor(
        cv2.imread("tests/data/2022-11-10T02-18-31-036Z-1066.jpg"), dtype=torch.float32
    ).permute(2, 0, 1)[None, :]
    result_img = RescaleWithPadding(512, 512)(img)
    module = torch.jit.script(RescaleWithPadding(512, 512))
    torch.onnx.export(
        model=module,
        args=(img,),
        f="transforms.onnx",
        export_params=True,
        verbose=True,
        input_names=["input"],
        output_names=["output"],
    )
    print(f"finished: {result_img.shape}")

class RescaleWithPadding(torch.nn.Module):
    def __init__(self, height: int, width: int, padding_value: int = 0):
        super(RescaleWithPadding, self).__init__()
        self.height = height
        self.width = width
        self.padding_value = padding_value
        self.max_size = max(height, width)
        self.interpolation = F.InterpolationMode.BILINEAR

    def forward(self, img: torch.Tensor):
        b, c, image_height, image_width = img.shape
        smaller_edge_size = min(image_height, image_width)
        img = F.resize(
            img=img,
            size=[smaller_edge_size],
            interpolation=self.interpolation,
            max_size=self.max_size,
        )
        return img
```

here is the torch version i'm using:
```
torch                         1.12.1
torchvision                   0.13.1
```

my goal is to implement some custom image preprocessing function/module and convert them to ONNX operators.
any pointers / documentations are appreciate to help me better understand the context. (i'm fairly new to pytorch)

thank you!!

i've been reading these docs, but they weren't really helpful.
https://pytorch.org/docs/stable/generated/torch.jit.script.html#torch.jit.script
https://pytorch.org/docs/master/onnx.html
https://pytorch.org/vision/stable/transforms.html#scriptable-transforms
https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html#torchvision.transforms.Resize
https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html#running-the-model-on-an-image-using-onnx-runtime
