### ISSUE TITLE
unable to save the model in TorchScript format?

### ISSUE THREAD

**Issue by IamExperimenting** [pytorch/pytorch#80307]
### 🐛 Describe the bug

I'm trying to save my model in TorchScript format, but unfortunately getting errors.

```
torch.jit.script(model)
```
could you please help me to fix this issue?

### Environment
PyTorch Version (e.g., 1.0):1.11.0+cu113
CPU Architecture:
OS (e.g., Linux): ubuntu 20.04
How you installed PyTorch (conda, pip, libtorch, source): pip
Build command you used (if compiling from source):
Are you using local sources or building from archives:
Python version:3.9.7
CUDA version:11.7
GPU models and configuration: RTX GEFORCE 2060
Any other relevant information:

![image](https://user-images.githubusercontent.com/74839416/175831746-bee0c46a-2db9-43d7-ab89-7afd9195a9f1.png)

### Environment
PyTorch Version (e.g., 1.0):1.11.0+cu113
CPU Architecture:
OS (e.g., Linux): ubuntu 20.04
How you installed PyTorch (conda, pip, libtorch, source): pip
Build command you used (if compiling from source):
Are you using local sources or building from archives:
Python version:3.9.7
CUDA version:11.7
GPU models and configuration: RTX GEFORCE 2060
Any other relevant information:

**Comment by davidberard98** [comment]
As it says in the error message: "compiled functions can't take variable number of arguments **or use keyword-only arguments with defaults**"

You'll need to change the function signature - either don't take keyword-only arguments, or don't provide a default value for that argument.
