### ISSUE TITLE
gradcheck jobs have multiple issues

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#80314]
Timeouts:
- https://github.com/pytorch/pytorch/runs/7063479932?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7062375007?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7059896045?check_suite_focus=true

test failures:
- https://github.com/pytorch/pytorch/runs/7063479968?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7062375039?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7059896094?check_suite_focus=true

OOMs:
- https://github.com/pytorch/pytorch/runs/7057639580?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7053079070?check_suite_focus=true

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
disables https://github.com/pytorch/pytorch/pull/80311

**Comment by nikitaved** [comment]
lobpcg is most likely a numerical issue. I plan on revisiting the backward and the tests to improve that.

**Comment by suo** [comment]
@Lezcano are you the right owner to push this forward and get these jobs re-enabled?

**Comment by janeyx99** [comment]
Just for tracking purposes: issue that disable tests
https://github.com/pytorch/pytorch/issues/80338
https://github.com/pytorch/pytorch/issues/80317

**Comment by janeyx99** [comment]
Also the OOMs have been made into a separate issue here: https://github.com/pytorch/pytorch/issues/80238

**Comment by albanD** [comment]
Note that right now, the slow gradcheck is completely removed. So to be test this in you PR, you will need to both revert https://github.com/pytorch/pytorch/pull/80311 and add the proper ciflow label

**Comment by soulitzer** [comment]
These tests were previously being [skipped](https://ossci-raw-job-status.s3.amazonaws.com/log/7032407678) because only slow tests only ran on slow gradcheck. Now slow gradcheck runs correctly both slow and fast tests possibly because of https://github.com/pytorch/pytorch/pull/80144. (We'd like slow gradcheck to run both slow and fast tests because fast gradcheck is known to fail to catch some types of failures.) 

One issue with this situation though is that our slow gradcheck tests might continue to time out (even if we don't have as many failures, which lead to up to 3 retries) because we have so many more tests to run now.

**Comment by Lezcano** [comment]
I discussed this with Jane, but posting here for visibility. If you want to heavily alleviate the CI, I would very much suggest we revisit the OpInfos for `max_pool{1,2,3}d` and `max_unpool{1,2,3}d`. These PRs have a ridiculous number of samples, pretty much testing all combinations of inputs (and there's many of them). These tests are, by far, the slowest, taking about 100-1000x what normal tests do. Perhaps @jbschlosser could have a look at these?
CC @suo @janeyx99

**Comment by albanD** [comment]
Are test runtime by name something that we can collect from the current test infra?

**Comment by ezyang** [comment]
cc @mruberry

**Comment by suo** [comment]
> Are test runtime by name something that we can collect from the current test infra?

Take a look at https://observablehq.com/d/b95f7b67261147ba

**Comment by jbschlosser** [comment]
> I discussed this with Jane, but posting here for visibility. If you want to heavily alleviate the CI, I would very much suggest we revisit the OpInfos for `max_pool{1,2,3}d` and `max_unpool{1,2,3}d`. These PRs have a ridiculous number of samples, pretty much testing all combinations of inputs (and there's many of them). These tests are, by far, the slowest, taking about 100-1000x what normal tests do. Perhaps @jbschlosser could have a look at these? CC @suo @janeyx99

Opened #80458 for investigation.

**Comment by mruberry** [comment]
We could move some (many, most?) of the samples to "reference inputs" for those operations, instead

**Comment by soulitzer** [comment]
Since (unlike fast gradcheck) the number of times forward/jvp/vjp runs in slow gradcheck scales linearly with total numel of all the inputs, reducing how large the inputs are can also proportionally reduce runtime. 

These are the slowest tests in slow gradcheck `(time in sec, name, total numel)` based on the logs from one of the time outs.
```
742.823, test_fn_fwgrad_bwgrad_diag_embed_cuda_complex128, 7040
662.876, test_fn_fwgrad_bwgrad_diff_cuda_complex128, 21392
524.456, test_fn_fwgrad_bwgrad_linalg_svd_cuda_complex128, 4096
489.465, test_fn_fwgrad_bwgrad_linalg_lu_cuda_complex128, 6500
408.589, test_fn_fwgrad_bwgrad_linalg_lstsq_grad_oriented_cuda_complex128, OK (skipped=1)
328.592, test_fn_fwgrad_bwgrad_linalg_lu_factor_cuda_complex128, 6500
320.207, test_fn_fwgrad_bwgrad_linalg_lu_factor_ex_cuda_complex128, 6500
277.863, test_fn_fwgrad_bwgrad_matmul_cuda_complex128, 17800
272.186, test_fn_fwgrad_bwgrad___rmatmul___cuda_complex128, 17800
269.493, test_fn_fwgrad_bwgrad_baddbmm_cuda_complex128, 12266
234.94, test_fn_fwgrad_bwgrad_istft_cuda_complex128, 6736
190.709, test_fn_fwgrad_bwgrad_lu_unpack_cuda_complex128, 6500
161.455, test_fn_fwgrad_bwgrad_addbmm_cuda_complex128, 9416
130.886, test_fn_fwgrad_bwgrad_kron_cuda_complex128, 450
123.73, test_fn_fwgrad_bwgrad__masked_normalize_cuda_complex128, 3310
118.701, test_fn_fwgrad_bwgrad_dist_cuda_complex128, 7240
114.121, test_fn_fwgrad_bwgrad_diff_cuda_float64, 10696
109.087, test_fn_fwgrad_bwgrad__masked_cumprod_cuda_complex128, 3162
108.905, test_fn_fwgrad_bwgrad_diag_embed_cuda_float64, 3520
95.968, test_fn_fwgrad_bwgrad_nn_functional_bilinear_cuda_float64, 5318
89.624, test_fn_fwgrad_bwgrad_mH_cuda_complex128, 5964
84.776, test_fn_fwgrad_bwgrad_atleast_2d_cuda_complex128, 3124
83.465, test_fn_fwgrad_bwgrad__masked_cumsum_cuda_complex128, 3162
82.376, test_fn_fwgrad_bwgrad_atleast_1d_cuda_complex128, 3124
81.504, test_fn_fwgrad_bwgrad_atleast_3d_cuda_complex128, 3124
79.894, test_fn_fwgrad_bwgrad_linalg_lu_solve_cuda_complex128, 2400
78.649, test_fn_fwgrad_bwgrad_mT_cuda_complex128, 5964
75.415, test_fn_fwgrad_bwgrad___rdiv___cuda_complex128, 2138
72.503, test_fn_fwgrad_bwgrad_ldexp_cuda_complex128, 2138
70.524, test_fn_fwgrad_bwgrad___getitem___cuda_complex128, 5000
```
This PR reduces the input size for some of the tests in this list https://github.com/pytorch/pytorch/pull/80515 (for fwgrad_bwgrad, gradgrad only, and only on slow gradcheck)

One issue though could be that there are some code paths that are only reached for large inputs.

**Comment by janeyx99** [comment]
It seems your proposals are not mutually exclusive, so we could probably do a mix! 
(1) does sound the most straightforward mitigation, though is it something we would want to do longterm (will there  always be the need to manually do this whenever we run into timeouts again)?
(2) we maintain generated lists for disabled tests and slow tests, and we could do something similar. However, I think it would be better to manually use a decorator on test classes that shouldn't run in slow gradcheck. This way, it'd be more visible.
(3) ccing @seemethere about essentially doubling capacity for the slow gradcheck CI.
