### ISSUE TITLE
BFloat16 support for upsampling on CUDA

### ISSUE THREAD

**Issue by jamaliki** [pytorch/pytorch#80339]
### 🚀 The feature, motivation and pitch

Upsampling operations currently do not support bfloat16 on CUDA, as discussed in https://github.com/pytorch/pytorch/issues/57707

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by EvgenyUgolkov** [comment]
Dear Team, good day. Could you tell if the upsample module was finally added to the bfloat16 format, or it is still under the development stage?

**Comment by jamaliki** [comment]
Hi, this is currently included in the nightly release. It will be a part of torch 2.1

**Comment by EvgenyUgolkov** [comment]
@jamaliki  hello, thank you for the fast reply! Could you tell, what is the approximate date of its release?

**Comment by jamaliki** [comment]
I don't know when the next release will be, sorry.

**Comment by EvgenyUgolkov** [comment]
@jamaliki Thank you. The final question, my apologies. It is impossible to use the nightly release now, without torch 2.1, right?

**Comment by jamaliki** [comment]
Yes, sorry for the confusion. The nightly release currently *is* torch 2.1

**Comment by EvgenyUgolkov** [comment]
@jamaliki Many thanks. The chances are low, but if you will still remember, could you kick me here when it will be released, please?)

**Comment by jamaliki** [comment]
Hahah, sure. No promises, I will probably forget :)

**Comment by noamsgl** [comment]
Following
