### ISSUE TITLE
[feature request] Clarify document to avoid "Error Importing cuda extension"

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#8036]
- PyTorch: 0.4
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: Ubuntu 16.04
- PyTorch version: 0,4
- Python version: 2.7
- CUDA/cuDNN version: 8.0
- GPU models and configuration: 1070

Following [here](https://pytorch.org/tutorials/advanced/cpp_extension.html) I compiled my extension with

    python setup.py develop

If I import my extension
    
    import smtl_cuda

I get the error:

```text    
    ImportError: ./smtl_cuda.so: undefined symbol: THPVariableClass
```
But to avoid it I just had to first import torch:

    import torch
    import smtl_cuda

Perhaps this should be mentioned in the above document about cpp_extension (or I am doing something wrong?)

P.S. great setup with the seamless extension compilation and ATen is great!

**Comment by goldsborough** [comment]
Hi @dashesy, this is mentioned in [the tutorial](https://pytorch.org/tutorials/advanced/cpp_extension.html):
![screen shot 2018-06-21 at 11 48 09](https://user-images.githubusercontent.com/6429851/41739156-13d63114-7549-11e8-958e-17c18ecc3242.png)
Let us know if you run into any more issues.
