### ISSUE TITLE
utils.data.DataLoader freezes

### ISSUE THREAD

**Issue by gcr** [pytorch/pytorch#804]
Hello! I'm having trouble loading data: the multiprocessing batch data loader freezes! Running on Ubuntu 14.10, Python 2.7.6, Pytorch 0.1.7.post2.

I'm instantiating a DataLoader like this:
```
    val_loader = torch.utils.data.DataLoader(
        datasets.ImageFolder("data/everything/", transforms.Compose([
            transforms.Scale(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
        ])),
        batch_size=16, shuffle=False,
        num_workers=3, pin_memory=False)
```

- *Symptom*: After a few batches (but sometimes after just one or two), the DataLoader refuses to yield any more batches. CPU and disk use drop to zero and everything is frozen.
- On my machine, this happens absolutely 100% of the time.
- If I set `num_workers=0`, then everything works, so the problem lies within the `multiprocessing` machinery. Ick.
- Using print statement debugging, I can tell that the workers are hanging in the call to `data_queue.put((idx, samples))` inside the worker loop, https://github.com/pytorch/pytorch/blob/4cc11066b267bfc02769cd6124ff01e41405f66b/torch/utils/data/dataloader.py#L36
- If I Ctrl+C this, I get the following (very mangled) traceback from the main process:
```
^CTraceback (most recent call last):
  File "test.py", line 30, in <module>
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Process Process-2:
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line
 27, in _worker_loop
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    for i, (input, target) in enumerate(val_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line
 168, in __next__
    r = index_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    idx, batch = self.data_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in ge
    self.run()
    return recv()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/queue.py", line
 21, in recv
    return recv()
  File "/usr/local/lib/python2.7/dist-packages/torch/multiprocessing/queue.py", line
 21, in recv
    buf = self.recv_bytes()
KeyboardInterrupt
    self._target(*self._args, **self._kwargs)
    buf = self.recv_bytes()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line
 40, in _worker_loop
KeyboardInterrupt
    data_queue.put((idx, samples))
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 388, in put
```

Is there any way to help debug?

**Comment by apaszke** [comment]
What are the sizes of images you're loading?

**Comment by ngimel** [comment]
What is the size of your shared memory segment (df -h | grep shm)? Pytorch uses shared memory to transfer data between processes, and it is quite demanding this way.

**Comment by gcr** [comment]
Aha! I only had `64M` of shared memory. Thanks, @ngimel!

I'm running inside docker, so using `docker run --shm-size 2G` fixed my issue. I can load batches like crazy now.

**Comment by ngimel** [comment]
@gcr, it is actually mentioned in the Docker section in README.md, you are not the first one to hit this issue.

**Comment by esube** [comment]
I have this same issue with two workers and an AWS P2 instance with shared memory of 241G (less than 1% usage). Has anyone run into this issue without  docker?

**Comment by xinleipan** [comment]
I'm not using docker and still having the same problem. The image size is 256*256*3, how could I fix this problem?

**Comment by zhuyangda** [comment]
I have 126G shm, but it seems not enough, how can I reduce shm the program will use?

**Comment by smiles724** [comment]
Hi, I am running completely different tasks on GNNs, but met a similar issue. The program works pretty well if I set the number of workers to 0. But it ran into errors if the number of workers are larger than 0. 

Please see the attached code. 
![image](https://user-images.githubusercontent.com/39299863/194744413-9ffe707f-82e5-450b-b62c-66fc9cdee3ca.png)

**Comment by JoseLuisC99** [comment]
I had the same problem. In my case I added `torch.multiprocessing.set_start_method('spawn')` after my `if __name__ == '__main__'` and it works.
