### ISSUE TITLE
DISABLED test_fq_module_per_tensor (quantization.core.test_workflow_ops.TestFakeQuantizeOps)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#80409]
Platforms: mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_fq_module_per_tensor%2C%20quantization.core.test_workflow_ops.TestFakeQuantizeOps)).

Note: this test is NOT flaky.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by suo** [comment]
cc @janeyx99 looks like this is broken? The parsed output looks reasonable though so not sure what's going on

**Comment by malfet** [comment]
Looks like we can only disable tests in `package.Class` if I read the implementation of [`testNameIsExpected`](https://github.com/pytorch/test-infra/blob/b96caf6fd32e11cb1ddfbcbeb77bcb978911a455/torchci/lib/bot/verifyDisableTestIssueBot.ts#L62) correctly:
```js
function testNameIsExpected(testName: string): boolean {
  const split = testName.split(" ");
  if (split.length !== 2) {
    return false;
  }   
    
  const testSuite = split[1].split(".");
  if (testSuite.length !== 2) {
    return false;
  } 
  return true;
}     

```
