### ISSUE TITLE
Cannot initialise torch.optim modules in torchscript

### ISSUE THREAD

**Issue by fdan** [pytorch/pytorch#80412]
### 🐛 Describe the bug

It does not seem possible to initialise torch optimisers in torchscript.  How should one create or pass in an optim object to a torchscript module?

```
class OptModule(torch.nn.Module):

    def __init__(self) -> None:
        super(OptModule, self).__init__()

    def forward(self, tensor: torch.Tensor) -> torch.Tensor:
        opt = torch.optim.Adam([tensor])
        return tensor

script = torch.jit.script(OptModule())
print(script.code)

RuntimeError: 
 method '__init__' is called recursively. Recursive calls are not supported:
  File "/tmp/ipykernel_71191/1655659191.py", line 7
    def forward(self, tensor: torch.Tensor) -> torch.Tensor:
        opt = torch.optim.Adam([tensor])
              ~~~~~~~~~~~~~~~~ <--- HERE
        return tensor
```

### Versions

pytorch 1.10.2

**Comment by davidberard98** [comment]
As far as I'm aware, optimizers can't be scripted in torchscript. The expected use case for training with torchscript is to script a module, and then train it with an external optimizer. Similarly (in your other issue) torchscript doesn't support scripting function definitions within other methods or functions.

For example, you if you follow [this example](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html) - you can script  `net` right before step 3.

**Comment by fdan** [comment]
Cheers, I was beginning to suspect that was the case.  For my purposes I might go with a torchlib implementation then, thanks
