### ISSUE TITLE
[RFC] Adding custom Metal kernel for mps ops requiring high performance

### ISSUE THREAD

**Issue by qqaatw** [pytorch/pytorch#80437]
Currently, there are a bunch of operators e.g. `aten::bitwise_*` that have not been supported by [MPS graph](https://developer.apple.com/documentation/metalperformanceshadersgraph) natively. 

Therefore, in this case, we can write custom MPS kernel to support these ops as mentioned in the [wiki](https://github.com/pytorch/pytorch/wiki/Adding-Op-for-MPS-Backend). Is there any existing reference we can take to write the custom kernel?

cc @svekars @holly1238 @kulinseth @albanD @DenisVieriu97

**Comment by kulinseth** [comment]
Thanks @qqaatw , we don't have reference for adding a op using the Metal kernel but we are actively working on it. We will update it here and the [wiki](https://github.com/pytorch/pytorch/wiki/Adding-Op-for-MPS-Backend) as how to do it.

**Comment by kulinseth** [comment]
We have added couple of Metal kernels for MPS. Please refer to:
https://github.com/pytorch/pytorch/pull/83678
https://github.com/pytorch/pytorch/pull/82307
https://github.com/pytorch/pytorch/pull/82507
