### ISSUE TITLE
torch.linalg.lstsq has confusing syntax highlighting in example

### ISSUE THREAD

**Issue by jameshamm** [pytorch/pytorch#80441]
### 📚 The doc issue

In the examples for [torch.linalg.lstsq](https://pytorch.org/docs/stable/generated/torch.linalg.lstsq.html) the statement defining `B` is split over two lines. The entire second line looks like a comment, when only part of the line contains a comment.

![Screenshot from 2022-06-28 11-13-59](https://user-images.githubusercontent.com/10179936/176154882-7db6806d-e4a7-495d-a2a4-64a7fc51a4a4.png)

In the screenshot, half of the definition of B is syntax highlighted as if it was commented out.

The syntax highlighting returns to normal for the rest of the example code.

### Suggest a potential alternative/fix

Change the syntax highlighting on that particular line to be consistent with the rest of the code in the examples section.

cc @svekars @holly1238 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
We could make it something like:
```python
>>> # shape (1, 3, 3)
>>> A = torch.tensor([[[10, 2, 3], [3, 10, 5], [5, 6, 12]]], dtype=torch.float)
>>> # shape (2, 3, 3)
>>> B = torch.tensor([[[2, 5, 1], [3, 2, 1], [5, 1, 9]],
                      [[4, 2, 9], [2, 0, 3], [2, 5, 3]]], dtype=torch.float)
```

Now, this is a bug in the docs rendering @brianjo

**Comment by gsc2001** [comment]
I would love to start with this, can you guide to ythe starting point?

**Comment by lezcano** [comment]
A good way to figure out where's the docs (or anything really) in PyTorch is to grep for them in the PyTorch repo. Then, you can have a look at https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#writing-documentation. You can make changes locally, render the documents, and when they look good, put up a PR :)

**Comment by lezcano** [comment]
inb4, you may need to fight sphinx a bit
