### ISSUE TITLE
torch.arange for torch.float16

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#80483]
### 🐛 Describe the bug

It seems that torch.arange is not supported for torch.float16: https://github.com/speechbrain/speechbrain/issues/1470

Would be good to support for consistency? (+ maybe torch.linspace) even if precision is not good

### Versions

N/A

**Comment by ngimel** [comment]
arange is supported on cpu since 11 months ago, on cuda for longer than that.

**Comment by malfet** [comment]
Well, it still does not work on CPU (which is reasonable, `torch.half` perf on CPU is horrible), but should be supported on CUDA...

**Comment by malfet** [comment]
Sure, why not

**Comment by ngimel** [comment]
Keep in mind that fp16 support on cpu is very spotty, inaccurate and won't be improved, so no one should be using fp16 on cpu for anything more than prepare a model to send to gpu (not even try to run through it, because a lot of ops won't be supported).

**Comment by vadimkantorov** [comment]
@ngimel wdyt about generating a webpage with a table in an automated way that shows which ops are supporting for which combinations of dtype x sparse/dense kind etc?

i agree that fp16 on cpu doesn't make much sense anyway at this point, but armed with such an up-to-date automated table, it would be simpler to know if it's a bug or expected or actually a missing support that is a meaningful feature request

**Comment by vadimkantorov** [comment]
Also cc @malfet on the idea of automated support matrix generation above
