### ISSUE TITLE
C++ documentation: link to full API docs disappeared

### ISSUE THREAD

**Issue by lodo1995** [pytorch/pytorch#80505]
### 📚 The doc issue

Until a few days ago, the [C++ documentation](https://pytorch.org/cppdocs/) used to include a link to the full library API documentation (generated with Doxygen, I assume), including ATen, Caffe2 and Torch. I don't remember the exact phrasing of the link, but it used to be in the left navigation bar, just below "The C++ Frontend".

Now (29 June 2022) that link has disappeared.

The rest of the documentation only includes very basic information, so without the full API docs it's impossible to make any advanced use of the C++ frontend.

### Suggest a potential alternative/fix

Have that link as it was until few days ago.

cc @ezyang @gchanan @zou3519 @svekars @holly1238 @jbschlosser

**Comment by lodo1995** [comment]
Looks like this is the result of #80451.

**Comment by cpuhrsch** [comment]
cc @mruberry

**Comment by mruberry** [comment]
cc @jbschlosser
