### ISSUE TITLE
`torch.ops.aten.where` failed to run with scalar inputs

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#80508]
### 🐛 Describe the bug

We use the functions in TorchScript to perform some basic parsing for a TorchScript model. When using PyTorch 1.12, the following operation failed but it used to work in previous versions of PyTorch.

```py
>>> import torch
>>> x = torch.rand(1, 3, 224, 224)
>>> torch.ops.aten.where(x > 0.5, -1.5, 1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/cpu/Loops.h":315, please report a bug to PyTorch. 
```
I've also tried the following cases.
```py
>>> torch.ops.aten.where(x > 0.5, -10, 10)
works...
>>> torch.ops.aten.where(x > 0.5, torch.tensor(-1.5), torch.tensor(1.5))
works...
>>> torch.ops.aten.where(x.cuda() > 0.5, -1.5, 1.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

The reason why I need this to work is that when parsing TorchScript, we want to get the intermediate results by running the graph line by line. So previously, I just get the kind of node through `graph.node.kind()`. And then I can get the function via `torch._C._jit_get_operation(kind)`. Finally, I pass in the arguments so that the output can be retrieved.

### Versions

PyTorch version: 1.12.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 516.40
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.12.0+cu113
[pip3] torchaudio==0.12.0+cu113
[pip3] torchmetrics==0.8.2
[pip3] torchvision==0.13.0+cu113
[conda] Could not collect

cc @ezyang @gchanan @zou3519

**Comment by ngimel** [comment]
cc @ezyang, looks like wrapping of args for `torch.ops.aten` is a bit overzealous, as `torch.where` works fine with this case.

**Comment by ezyang** [comment]
sigh, I guess I'll replicate the allowlist for scalars
