### ISSUE TITLE
Drop Python 3.7 support (following NEP 29)

### ISSUE THREAD

**Issue by EwoutH** [pytorch/pytorch#80513]
According to the [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) schedule Python 3.7 should have been dropped on Dec 26, 2021. PyTorch adopted this depreciation policy in #74203, and with PyTorch 1.12 released (which still supports Python 3.7), this seems like a good moment to drop Python 3.7 and make the minimum required Python version 3.8, in preparation of PyTorch 1.13.

**Comment by RedTachyon** [comment]
Are there some specific features of 3.8 that should be included? This feels needlessly aggressive, especially seeing as colab (for whatever reason) still runs on 3.7

**Comment by malfet** [comment]
FYI we have about 20 jobs that have 3.7 in its name: https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=3.7

**Comment by adamjstewart** [comment]
Note that Google Colab finally upgraded to Python 3.8: https://github.com/googlecolab/colabtools/issues/3246

I'm not the biggest fan of NEP 29 but TorchGeo will likely follow whatever decision PyTorch makes on Python support.

**Comment by seemethere** [comment]
Pinning this issue since _we will_ be dropping Python 3.7 support as part of the 2.0.0 release

**Comment by izaitsevfb** [comment]
A related smaller task is to drop python 3.7 in nightly builds: 
#92636
