### ISSUE TITLE
ROCm periodic jobs are timing out

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#80529]
Examples:
- https://github.com/pytorch/pytorch/runs/7101566093?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7104395879?check_suite_focus=true
- https://github.com/pytorch/pytorch/runs/7106030903?check_suite_focus=true

Check the [HUD](https://hud.pytorch.org/minihud?name_filter=periodic%20/%20linux-bionic-rocm5.1-py3.7-distributed%20/%20test%20(distributed,%201,%202,%20linux.rocm.gpu)) for more examples.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by jeffdaily** [comment]
Yep, we've been discussing this internally most of the morning.  Will post observations soon.

**Comment by jeffdaily** [comment]
distributed/test_c10d_pypg.py added 7 minutes (430s).  That doesn't seem like the issue.

When I look at the last known passing job for rocm periodic, these 4 tests

distributed/test_c10d_spawn_gloo
distributed/test_data_parallel
distributed/test_launcher
distributed/test_pg_wrapper

were replaced with these 5 tests

distributed/test_c10d_pypg    (7m)
distributed/test_c10d_spawn_nccl    (5s)
distributed/test_distributed_spawn    (5s)
distributed/test_nccl    (job timed out before reaching)
distributed/test_store    (job timed out before reaching)

It seems the slowdown must be elsewhere.  Still looking.

**Comment by jeffdaily** [comment]
Oddly, the periodic jobs are back to normal.

**Comment by jeffdaily** [comment]
ROCm distributed tests were restored.  Running times are within bounds.
