### ISSUE TITLE
[feature request] Can we have an option to export static graph?

### ISSUE THREAD

**Issue by qigtang** [pytorch/pytorch#8054]
Sorry if it is double posted to onnx/onnx git, since I am not sure whether the feature is part of pytorch or onnx. 

------------------------------------------------------------------------------------------

When using pytorch 0.4, export resnet to onnx, the FC layer will be something like

%169 : Float(1, 512, 1, 1) = onnx::AveragePoolkernel_shape=[7, 7], pads=[0, 0, 0, 0], strides=[1, 1], scope: ResNet/AvgPool2d[avgpool]
%170 : Float(1, 512) = onnx::Flattenaxis=1, scope: ResNet
%171 : Float(1, 6) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%170, %101, %102), scope: ResNet/Linear[fc]
return (%171);

Latest version of pytorch save it as
%190 : Float(1, 512, 1, 1) = onnx::AveragePoolkernel_shape=[7, 7], pads=[0, 0, 0, 0], strides=[1, 1], scope: ResNet/AvgPool2d[avgpool]
%191 : Dynamic = onnx::Shape(%190), scope: ResNet
%192 : Dynamic = onnx::Sliceaxes=[0], ends=[1], starts=[0], scope: ResNet
%193 : Long() = onnx::Squeezeaxes=[0], scope: ResNet
%194 : Long() = onnx::Constantvalue={-1}, scope: ResNet
%195 : Dynamic = onnx::Unsqueezeaxes=[0], scope: ResNet
%196 : Dynamic = onnx::Unsqueezeaxes=[0], scope: ResNet
%197 : Dynamic = onnx::Concat[axis=0](%195, %196), scope: ResNet
%198 : Float(1, 512) = onnx::Reshape(%190, %197), scope: ResNet
%199 : Float(1, 6) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%198, %121, %122), scope: ResNet/Linear[fc]
return (%199);

The new one actually caused trouble for us. For embedded device, we want fixed size, and let TensorRT optimize the graph for deployment. I don't want the "nice" dynamic feature in onnx.

It is possible to put an option to latest pytorch, so that we can choose to export a static and simpler graph?

**Comment by SsnL** [comment]
maybe @bddppq or @houseroad knows the answer? :)

**Comment by qigtang** [comment]
any update on this? @bddppq @houseroad 
Maybe give me some instructions on where can I make the modification. I can modify myself for my own application case.

**Comment by 0wu** [comment]
There are two ways to implement this.
(1) Add an option in pytorch export routine to prefer static shape output.
(2) Add a post export ONNX optimization pass to infer shape from input+onnx model and generate a static-shaped model from there. 

(1) is probably easier to implement while (2) is more flexible and the same optimization code and apply to model exported from other frameworks.

I used ONNX export to generate inference code running on edge hardware, while in most cases, a static-shaped model is preferred to dynamic one.

**Comment by houseroad** [comment]
I think one solution for this problem is having a constant propagation pass in the ONNX optimizer.

**Comment by qigtang** [comment]
Anyone will implement that? We stop moving to pytorch 1.0 because this issue. For us, being able to depoly an optimized graph using TensorRT is a must have for the whole tool chain setup.

**Comment by houseroad** [comment]
@qigtang I think so. Right now, I am discussing the solution with ONNX community members. It's not specific to PyTorch, but will apply all ONNX models.

**Comment by qigtang** [comment]
@houseroad That is great news! Thanks!

**Comment by houseroad** [comment]
cc: @spandantiwari

**Comment by garymm** [comment]
@qigtang is this still an issue with the latest PyTorch nightly?
`torch.onnx.export` has a `do_constant_folding` arg which is True by default.

**Comment by thiagocrepaldi** [comment]
It’s been over 2 months, so closing this. Feel free to open another one.
