### ISSUE TITLE
Missed "break" statements in IListRef.h (line 385, 387, 399, 401) in IListRefIterator constructor and destructor

### ISSUE THREAD

**Issue by VasilyevAlexander** [pytorch/pytorch#80568]
### 🐛 Describe the bug

Missed breaks in constructor and destructor. So ASSERT always executed
#if defined(_MSC_VER) && _ITERATOR_DEBUG_LEVEL != 0
  // See [Note: MSVC Iterator Debug]
  IListRefIterator(const IListRefIterator& iterator)
      : tag_(iterator.tag_) {
    switch (tag_) {
      case IListRefTag::Boxed:
        payload_.boxed_iterator = iterator.payload_.boxed_iterator;
      case IListRefTag::Unboxed:
        payload_.unboxed_iterator = iterator.payload_.unboxed_iterator;
      default:
        TORCH_INTERNAL_ASSERT(false, "invalid IListRef tag.");
    }
  }
#endif

#if defined(_MSC_VER) && _ITERATOR_DEBUG_LEVEL == 2
  // See [Note: MSVC Iterator Debug]
  ~IListRefIterator() {
    switch (tag_) {
      case IListRefTag::Boxed:
        payload_.boxed_iterator.~boxed_iterator_type();
      case IListRefTag::Unboxed:
        payload_.unboxed_iterator.~unboxed_iterator_type();
      default:
        TORCH_INTERNAL_ASSERT(false, "invalid IListRef tag.");
    }
  }
#endif

### Versions

libtorch-debug 1.12 CUDA 11.6

**Comment by soulitzer** [comment]
Good catch, we'd accept a PR to fix this

**Comment by VasilyevAlexander** [comment]
It is strange but in GitHub repository https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/core/IListRef.h there are "breaks". But in Release source file "pytorch-1.12.0.zip" file IListRef.h is different. 
Probably just rebuild of library is needed.

**Comment by VasilyevAlexander** [comment]
It was corrected 21 days ago [Prevent invariant assert failure on win+debug (](https://github.com/pytorch/pytorch/commit/7541b07f62c1af7763fa6ce49441bea63a1e5e26)https://github.com/pytorch/pytorch/pull/78636[)](https://github.com/pytorch/pytorch/commit/7541b07f62c1af7763fa6ce49441bea63a1e5e26).

But library was build with earlier sources.

**Comment by soulitzer** [comment]
Ahh yeah, sounds like it was fixed on master after the branch cut. Closing.
