### ISSUE TITLE
`arange` returns incorrect results for certain values

### ISSUE THREAD

**Issue by neosunhan** [pytorch/pytorch#80589]
### 🐛 Describe the bug

From the documentation, `arange` should return values from the interval `[start, end)`, i.e. the end of the interval should not be included in returned tensor. However, for certain values, the end of the interval is included in the returned tensor.

```python3
>>> import torch
>>> t = torch.arange(0, 144962911544046900, 1449629115440469) # contains end of interval
>>> t[100]
tensor(144962911544046900)
```

There is also inconsistent behaviour when using certain data types.
```python3
>>> import torch
>>> torch.arange(-1.5, 1.5, dtype=torch.int32)
tensor([-1,  0,  1], dtype=torch.int32)
>>> torch.arange(-1.5, 1.5, dtype=torch.int64)
tensor([-1,  0])
```

### Versions

```
PyTorch version: 1.12.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.0
[pip3] torch==1.12.0
[conda] Could not collect
```

**Comment by yuguo68** [comment]
Thanks for reporting! It seems this is due to the casting to double, https://github.com/pytorch/pytorch/blob/adcf9647dc0d7ca7e2513777c0f69b8a9a7b3f6d/aten/src/ATen/native/RangeFactories.cpp#L161-L164

@ngimel shall we remove the casting in the case of dtype is int64?

**Comment by yuguo68** [comment]
verified that removing the cast fixes the first issue that end is included in the output. 
the inconsistency behavior with dtype is because for int32 args such as start, end are cast to double to compute the size of the output, whereas for int64 they are cast to int64.
