### ISSUE TITLE
Illustration of LeakyReLU is wrong

### ISSUE THREAD

**Issue by underdogliu** [pytorch/pytorch#80592]
### 🐛 Describe the bug

Hi all! I found in [the description of LeakyReLU](https://pytorch.org/docs/stable/generated/torch.nn.LeakyReLU.html), while the textual description is precisely correct, the illustrations associated seems not correct - it is still a ReLU function, without the negative slope at the left-hand side of the figure.

It would be great if we can fix it. Or I can submit a small PR? If I do it, which part of the code shall I be looking at?

### Versions

PyTorch 1.12

cc @svekars @holly1238

**Comment by ptrblck** [comment]
I don't think that's the case as described and explained [here](https://discuss.pytorch.org/t/graph-in-docs-for-leakyrelu-wrong/129891/2?u=ptrblck). The slope is just small (`1e-2`) and thus might not be clearly visible. The linked post zooms into the section and recreates the plot, too.

**Comment by underdogliu** [comment]
OK my mistake! No problem. Thanks a lot for explanation this trivial question. @ptrblck

**Comment by d-kleine** [comment]
To be honest, I was confused too - the slope in quadrant III in the cartesian coordinate system for the Leaky ReLU is so small that one can barely see the difference to the ReLU function. 
[Leaky ReLU](https://pytorch.org/docs/stable/_images/LeakyReLU.png)
[ReLU](https://pytorch.org/docs/stable/_images/ReLU.png)

I think, it would be better to update the `negative_slope` (alpha) parameter to a larger size and create a new visualization of the Leaky ReLU activation function to see the difference to ReLU.
