### ISSUE TITLE
NotImplementedError: The operator 'aten::l1_loss_backward.grad_input' is not current implemented for the MPS device. 

### ISSUE THREAD

**Issue by chikiuso** [pytorch/pytorch#80598]
### 🚀 The feature, motivation and pitch

NotImplementedError: The operator 'aten::l1_loss_backward.grad_input' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

cc @kulinseth @albanD

**Comment by qqaatw** [comment]
Should work on master, can you try the latest nightly build?

**Comment by albanD** [comment]
Tentatively closing. Feel free to re-open if this is not solved on latests master.
