### ISSUE TITLE
multiprocessing init_process_group based on gloo fails on Windows

### ISSUE THREAD

**Issue by t4rf9** [pytorch/pytorch#80638]
### 🐛 Describe the bug

```python
import torch.distributed as dist
import torch.multiprocessing as mp


def f(rank, world_size):
    dist.init_process_group(
        "gloo", init_method="tcp://127.0.0.1:12988", rank=rank, world_size=world_size
    )


if __name__ == "__main__":
    world_size = 2

    context = mp.spawn(f, args=(world_size,), nprocs=world_size, join=False)
    context.join()

```

We I try to run the above code, I received an error message:

```
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:12988 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:12988 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:12988 (system error: 10049 - 在其上下文中，该请求的地址无效。).
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:12988 (system error: 10049 - 在其上下文中，该请求的地址无效。).
```
The Chinese sentences at the end of each message basically mean that "the requested address is unavailable within its context".

When trying to print text before or after `init_process_group`, I found out that all codes before it are run first, then `init_process_group`, and finally codes after are executed.

I am not sure whether this will affect the success of inter-process communications.

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650
Nvidia driver version: 516.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.0
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.13.0+cu116
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by mantaionut** [comment]
I tried to reproduce and it looks like its failing to connect on ipv6( thats the log you see) and then connects on ipv4.
Can you try to run with set TORCH_CPP_LOG_LEVEL=0 ?
On my side I get 
\pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [LAPTOP-]:12988 (system error: 10049 - The requested address is not valid in its context.).
[I windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:725] [c10d] The client socket has connected to LAPTOP-:12988 on LAPTOP-:61645.

**Comment by H-Huang** [comment]
I've previously seen an issue in the past that on certain platforms, the dualstack IPv4/IPv6 socket uses an IPv6 address, it can only accept IPv6 connections but not IPv4.

Can you try changing `127.0.0.1` -> `localhost`

```python
import torch.distributed as dist
import torch.multiprocessing as mp


def f(rank, world_size):
    dist.init_process_group(
        "gloo", init_method="tcp://localhost:12988", rank=rank, world_size=world_size # <--- this line
    )


if __name__ == "__main__":
    world_size = 2

    context = mp.spawn(f, args=(world_size,), nprocs=world_size, join=False)
    context.join()
```

**Comment by t4rf9** [comment]
> I tried to reproduce and it looks like its failing to connect on ipv6( thats the log you see) and then connects on ipv4. Can you try to run with set TORCH_CPP_LOG_LEVEL=0 ? On my side I get \pytorch\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [LAPTOP-]:12988 (system error: 10049 - The requested address is not valid in its context.). [I windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:725] [c10d] The client socket has connected to LAPTOP-:12988 on LAPTOP-:61645.

This is true for me and it explains what happens when trying to connect in IPv4.



> I've previously seen an issue in the past that on certain platforms, the dualstack IPv4/IPv6 socket uses an IPv6 address and it can only accept IPv6 connections but not IPv4.
> 
> Can you try changing `127.0.0.1` -> `localhost`
> 
> ```python
> import torch.distributed as dist
> import torch.multiprocessing as mp
> 
> 
> def f(rank, world_size):
>     dist.init_process_group(
>         "gloo", init_method="tcp://localhost:12988", rank=rank, world_size=world_size # <--- this line
>     )
> 
> 
> if __name__ == "__main__":
>     world_size = 2
> 
>     context = mp.spawn(f, args=(world_size,), nprocs=world_size, join=False)
>     context.join()
> ```

This gives a simple method to avoid the failure and get rid of the warning messages.

The problem is well solved!
