### ISSUE TITLE
MergeBot does not preserve authorship

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#80635]
### 🐛 Describe the bug

Not sure what happened between https://github.com/pytorch/pytorch/pull/78918 and https://github.com/pytorch/pytorch/commit/682c0d2615a20b30ecb95b501cd8105327686838 but for some reason commit author is not the same as PR author...

### Versions

N/A

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by mikaylagawarecki** [comment]
Also running into this in: #80464 and [f668b7e](https://github.com/pytorch/pytorch/commit/f668b7ecb02d881e9585ff2276f7c4f54a323e7d) as well as [#80324](https://github.com/pytorch/pytorch/pull/80324) and [d7847ed](https://github.com/pytorch/pytorch/commit/d7847ed23eb8880c7541319aab8864a45e239994), I think it might related to the rebase from asking pytorchbot to rebase being the most recent commit before these PRs were merged

**Comment by janeyx99** [comment]
Related to https://github.com/pytorch/test-infra/issues/406

**Comment by seemethere** [comment]
Should we re-assign to @clee2000 since this is more related to the rebase job than it is the `trymerge.py` script?

**Comment by malfet** [comment]
Hmm, there is still a bug in trymerge, as it should pick PR author as author...
