### ISSUE TITLE
[torchvision] [Feature Request] Functional processing for points

### ISSUE THREAD

**Issue by Naman-ntc** [pytorch/pytorch#8072]
Suppose I have to detect keypoints in image (bounding box pixel coordinates, or human joints coordinates), on applying transforms like rotation, padding, obviously the values of those coordinates will change. We can by basic geometry do the calculation but it would be awesome if it could be integrated into the torchvision functional part. 
So augmenting data for say human pose estimation would be easier and feels intuitive to me. For each functionsl tranform, a transform for target pixels or something like that!

**Comment by SsnL** [comment]
You should open an issue on torchvision then (and probably better rephrase the issue because I find it hard to understand what you want.https://github.com/pytorch/vision
