### ISSUE TITLE
[MPS] AdaptiveAvgPool2D doesn't accept input spatial size smaller than output shape

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#80732]
### 🐛 Describe the bug

```
import torch

avgpool = torch.nn.AdaptiveAvgPool2d((7, 7))
a = torch.randn(64, 512, 4, 4, device='mps')
avgpool(a)
```

This issue is not observable on `cuda` or `cpu`.

Originated from discuss forum here: https://discuss.pytorch.org/t/vgg19-runtimeerror-stride-should-not-be-zero/155476
The root cause might be this stride calculation here? https://github.com/pytorch/pytorch/blob/421f04dd028aa9af384fddd917f6115508bdec46/aten/src/ATen/native/mps/operations/AdaptivePooling.mm#L25

CC @kulinseth 

### Versions

upstream

cc @kulinseth @albanD

**Comment by zhaoBowen612** [comment]
I can reproduce this issue. If the parameter, "device", is change to "cpu", it works fine. It seems the problems happen to the default value of the parameter, "stride"?

**Comment by zhaoBowen612** [comment]
I can reproduce this issue. If the parameter, "device", is change to "cpu", it works fine. It seems the problems happen to the default value of the parameter, "stride"?

**Comment by kulinseth** [comment]
@abhudev who implemented the adaptive pooling code. Can you take a look.
