### ISSUE TITLE
share_memory() on CUDA tensors no longer no-ops and instead crashes in version 1.12.0

### ISSUE THREAD

**Issue by andrewzhang505** [pytorch/pytorch#80733]
### 🐛 Describe the bug

In PyTorch version 1.12.0, `model.share_memory()` on a CUDA tensor no longer no-ops and instead crashes with error `RuntimeError: _share_fd_: only available on CPU`. Version 1.11.0 correctly no-ops

```
import torch

model = torch.nn.Linear(3, 1)
model.to(torch.device('cuda:0'))
model.share_memory()
```

Running above gets the output

```
Traceback (most recent call last):
  File "/home/andrew_huggingface_co/test.py", line 5, in <module>
    model.share_memory()
  File "/opt/conda/envs/fail/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1912, in share_memory
    return self._apply(lambda t: t.share_memory_())
  File "/opt/conda/envs/fail/lib/python3.9/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/opt/conda/envs/fail/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1912, in <lambda>
    return self._apply(lambda t: t.share_memory_())
  File "/opt/conda/envs/fail/lib/python3.9/site-packages/torch/_tensor.py", line 515, in share_memory_
    self.storage().share_memory_()
  File "/opt/conda/envs/fail/lib/python3.9/site-packages/torch/storage.py", line 595, in share_memory_
    self._storage.share_memory_()
  File "/opt/conda/envs/fail/lib/python3.9/site-packages/torch/storage.py", line 194, in share_memory_
    self._share_fd_cpu_()
RuntimeError: _share_fd_: only available on CPU
```

The problem seems to be in the `_StorageBase.share_memory_` function in `storage.py`. `self.is_cuda` is being evaluated as False which then executes `self._share_fd_cpu_()`

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: version 3.13.4
Libc version: glibc-2.28

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.19.0-20-cloud-amd64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89             h713d32c_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.22.3           py39he7a7128_0
[conda] numpy-base                1.22.3           py39hf524024_0
[conda] pytorch                   1.12.0          py3.9_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchvision               0.13.0               py39_cu102    pytorch

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
cc @kurtamohler

**Comment by xloem** [comment]
just a quick note that this also happens when the tensor is on the meta device (torch 2.0.0)
