### ISSUE TITLE
vision hash update failing

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#80745]
### 🐛 Describe the bug

The vision pinned hash is from a long time ago (2020?) and attempting to update it to a newer hash fails.  See #79256 for examples of CI failing when the hash is updated, and https://github.com/pytorch/pytorch/pull/79256#issuecomment-1169326961 for a possible reason why.  When fixed, we should add vision back into `update_pinned_hashes.yml`.

### Versions

n/a

cc @seemethere @malfet @pytorch/pytorch-dev-infra @fmassa @vfdev-5 @pmeier

**Comment by malfet** [comment]
Self-assigning myself to have a look at it

**Comment by clee2000** [comment]
fixed by https://github.com/pytorch/vision/pull/6230
