### ISSUE TITLE
CapabilityBasedPartitioner requires is node supported to only return true for CALLABLE_NODE_OPS but no assertion for this invariant exists

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#80753]
### 🐛 Describe the bug

Steps to reproduce: 
1. Write a OperatorSupport that always returns True
2. Try to run the partitioner on a graph

Expected: an error, or it fuses the entire graph
Actual: the resulting graph is malformed

@SherlockNoMad 

### Versions

master

**Comment by SherlockNoMad** [comment]
CapabilityBasedPartitioner is not handing "placeholder" and "output" nodes properly. 

Following snippet works though... 

    def is_node_supported(
        self, submodules: t.Mapping[str, Module], node: Node
    ) -> bool:

        if node.op not in CALLABLE_NODE_OPS:
            return False
        return True
        
How do we expect partitioner to behave if it needs to support "placeholder" and "output" node? 
Sounds like it should still copy the placeholder and output into the inner graph, and they should still remain in the outer graph.

**Comment by ezyang** [comment]
I think probably you should just not call `is_node_supported` on placeholder and output nodes

**Comment by ydwu4** [comment]
cc @SherlockNoMad @ezyang , can I close this issue?
