### ISSUE TITLE
`acosh` has an incorrect complex derivative

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#80763]
### 🐛 Describe the bug

`acosh` does not return `NaN` for complex tensor, which causes it cannot pass `gradcheck` for these invalid input.

```python
import torch

input = torch.tensor([-0.8137-0.1476j, -0.2749-0.2630j, -0.2163-0.7010j, -0.3824-0.2827j],
       dtype=torch.complex128, requires_grad=True)

torch.autograd.gradcheck(torch.acosh, (input))
```

```
GradcheckError: While considering the imaginary part of complex outputs only, Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[1.4551-0.4412j, 0.0000+0.0000j, 0.0000+0.0000j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.9954-0.0720j, 0.0000+0.0000j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000+0.0000j, 0.8187-0.0850j, 0.0000+0.0000j],
        [0.0000+0.0000j, 0.0000+0.0000j, 0.0000+0.0000j, 1.0149-0.1160j]],
       dtype=torch.complex128)
analytical:tensor([[-1.4551+0.4412j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j, -0.9954+0.0720j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j, -0.8187+0.0850j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j, -1.0149+0.1160j]],
       dtype=torch.complex128)
```

I think it should output the `NaN` for these invalid inputs, which is mentioned in its document.

### Versions

pytorch: 1.11.0

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @anjali411 @dylanbespalko @mruberry

**Comment by albanD** [comment]
Why should this return `NaN`?
The formula might need to be updated though as it returns `-1 *` the gradient from the numerical check.

**Comment by Lezcano** [comment]
As Alban pointed out, the the `acosh` (and any trigonometric function really) over the complex numbers may be expressed as a combination of exp / logs. As such, it may be defined (in a non-continuous way) on C, and on a holomorphic way on C minus a ray (e.g. the non-positive real numbers).

I think you may be thinking of the real case, where `cosh : R -> R^+` and thus `acosh` is not defined for negative inputs.

**Comment by upupyy** [comment]
Yes, it shouldn't return `NaN` and it seems as a gradient bug.

**Comment by Lezcano** [comment]
This was already reported in https://github.com/pytorch/pytorch/issues/50692. I'll submit a fix soon. Closing this issue in favour of that other one.
