### ISSUE TITLE
Multiarch docker image

### ISSUE THREAD

**Issue by hkad98** [pytorch/pytorch#80764]
### 🚀 The feature, motivation and pitch

Currently, the PyTorch docker image does not support ARM-based CPUs, which may be an issue for some MacBooks with Apple Silicon users. Also, this fact blocks other projects using PyTorch, e.g., https://github.com/mindsdb/mindsdb/issues/2420.

cc @malfet

**Comment by xstast24** [comment]
+1
This is really needed for anybody using pytorch-based docker images (there is plenty of them) on Macbooks. Macs are no longer sold with Intel CPUs, so this is 100% needed for the future.
Here is a simple tutorial on how to create multi-arch docker images https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way ...I don't know pytorch processes enough to implement this myself, but please please, somebody take a look at this 💟

**Comment by malfet** [comment]
@seemethere @atalman  do you think we can start building linux-arm64 PyTorch docker images?

**Comment by seemethere** [comment]
We don't actually build / upload binaries for linux-arm64 on conda so the images would be different anyways.

Most of what the docker image is just installing the binaries, I feel as though that shouldn't be terribly hard to replicate.

**Comment by seemethere** [comment]
I've submitted https://github.com/pytorch/pytorch/pull/83437 as an exploratory way to do this, but building and publishing multi-arch docker images is not really a trivial task at all

**Comment by seemethere** [comment]
@hkad98 Can you check if this image is runnable by you:

```
ghcr.io/pytorch/pytorch-nightly:1.13.0.dev20220817-runtime
```

**Comment by hkad98** [comment]
@seemethere
I tried to pull and run the docker image you sent. Everything seems fine except using GPU as a device. It is possible that I do it wrong. I try the following:
```python
import torch
torch.device("mps")
# <stdin>:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  /root/pytorch/torch/csrc/utils/tensor_numpy.cpp:68.)
#device(type='mps')
```

Also, I try to do the following:
```python
import torch
torch.backends.mps.is_available()
# False
torch.backends.mps.is_built()
# False
```
I use the following command to run docker:
```bash
docker run -it ghcr.io/pytorch/pytorch-nightly:1.13.0.dev20220817-runtime
```

**Comment by seemethere** [comment]
Docker for mac does not support GPU pass through for MPS since the docker runs in a linux VM on top of macOS.

**Comment by hkad98** [comment]
@seemethere I thought that. Thanks for the clarification. Thanks for the implementation!

**Comment by roborourke** [comment]
What's the usual turnaround time before these builds make it to Docker Hub? Looking forward to using it.

Thanks for putting the time in @seemethere.
