### ISSUE TITLE
Running pytorch on Node js server is undiscribed.

### ISSUE THREAD

**Issue by RandGor** [pytorch/pytorch#80778]
### 🐛 Describe the bug

Hello! I have NodeJS server and I want it to run my .pt model. 
There are lots of tips how to run it on devices (model is running correct), but I can't find any info about how can I run my model on Node JS server CPU.
Please help me and another searchers to find the advanced way.

### Versions

All

**Comment by ezyang** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/ In general you should be looking for nodejs bindings for PyTorch; see for example https://github.com/torch-js/torch-js (although this repo looks old and may not be working)
