### ISSUE TITLE
`xlogy` returns wrong gradient when `input` is 0

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#80770]
### 🐛 Describe the bug

`xlogy` returns wrong gradient when `input` is 0. Since it is continuous and differential at the point 0, it shouldn't return 0 as the gradient.

```py
import torch

def fn(input):
    fn_res = input.xlogy(2)
    return fn_res

input = torch.tensor([[0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)
torch.autograd.gradcheck(fn, (input))
```

```
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[0.6931, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6931, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.6931, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.6931]], dtype=torch.float64)
analytical:tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
```

### Versions

pytorch: 1.11.0

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by kaad01** [comment]
Hey @upupyy I can look into this. Do you know where the function xlogy is defined?

**Comment by ptrblck** [comment]
@kaad01 
The derivatives can be found [here](https://github.com/pytorch/pytorch/blob/e1cfac42b2b3ea96d3783c66c8d2e44244a40524/tools/autograd/derivatives.yaml#L907-L931). The forward definitions are [here](https://github.com/pytorch/pytorch/blob/e1cfac42b2b3ea96d3783c66c8d2e44244a40524/aten/src/ATen/native/native_functions.yaml#L2916-L2964) and should eventually call into [this CPU kernel](https://github.com/pytorch/pytorch/blob/f96d96a7fcaa5bb06829d2c7de1992d6ab6e9235/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp#L1078-L1104) and [this CUDA kernel](https://github.com/pytorch/pytorch/blob/1522912602bc4cc5f7adbce66cad00ebb436f195/aten/src/ATen/native/cuda/BinaryMiscOpsKernels.cu#L44-L70).

**Comment by Lezcano** [comment]
Yep, the derivative wrt `self` is wrong. We should add that as a test case to the relevant OpInfo when fixed as well.

**Comment by Lezcano** [comment]
How is this one going @kaad01? Any issues I can help with?

**Comment by kaad01** [comment]
@Lezcano The last few days I had a lot to do. But now I have time. sry. So first I tried to familiarise myself with all the files and functions.
I have some questions:

1. I don't get why we multiply the grad instead of our tensor:
```
- name: xlogy.Scalar_Other(Tensor self, Scalar other) -> Tensor
  self: grad * at::xlogy((self != 0), other)
  result: auto_element_wise
```
maybe that is what you meant above. 

So I just changed to 
```
- name: xlogy.Scalar_Other(Tensor self, Scalar other) -> Tensor
  self: at::xlogy((self != 0), other)
  result: auto_element_wise
```
and nothing changed in the example above. Which makes sense.

2. I don't understand the xlogy function. Why do we need to clearly state that if x=0 the result should be 0? Isn't 0*log(y) = 0 anyways.

I'm new to all of this. I mainly code in python. So forgive me for any stupid questions.
And thank you in advance.

**Comment by kaad01** [comment]
I have a question. I don't understand why the derivative of xlogy wrt x is grad*y.log(). I would think it should be log(y) instead. Why do we need to multiply the grad of x. How exactly does this work, what is the math behind this?
I just want to understand every detail completely.

**Comment by Lezcano** [comment]
The mathy keywords are "adjoint of the differential" or "vector Jacobian product"

**Comment by kaad01** [comment]
@Lezcano so I don't know if I understood the tests right, but there is this [BinaryUfuncInfo](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_methods_invocations.py#L17523-L17534).
I think I just have to add this line:
`sample_inputs_func=sample_inputs_elementwise_binary`
Is there something else to do?
Do I have to define the samples myself?

**Comment by kaad01** [comment]
I see do I have to test edge-cases like 'nan', '-1', 'inf', 'inf' as input. Else I would just add '0' and a '0' tensor as input.

**Comment by Lezcano** [comment]
The latter is fine.

**Comment by kaad01** [comment]
I'll commit then. I tried my best to write the functions like the rest. So the `input = scalar` case fails with a TypeError. I give `(int, Tensor, Tensor) but expected is (Number self, Tensor other, *, Tensor out)`. After I took that case out and started `pytest test/test_binary_ufuncs.py` I didn't get any errors.

But I still get an error if I test this:
```
import torch

def fn(input):
    t = torch.tensor([[3., 6., 0, 3.]], dtype=torch.float64, requires_grad=True)
    fn_res = input.xlogy(t)
    return fn_res

input = torch.tensor([[2., 0., 4., 0.]], dtype=torch.float64, requires_grad=True)
torch.autograd.gradcheck(fn, (input))
```
I get

```
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[1.0986, 0.0000, nan, 0.0000],
        [0.0000, 1.7918, nan, 0.0000],
        [0.0000, 0.0000, nan, 0.0000],
        [0.0000, 0.0000, nan, 1.0986]], dtype=torch.float64)
analytical:tensor([[1.0986., 0., 0., 0.],
        [0., 0., 0., 0.],
        [nan, nan, -inf, nan],
        [0., 0., 0., 0.]], dtype=torch.float64)
```
Could someone look over this and help me with the test case?

Thank you for your help.

**Comment by kaad01** [comment]
@Lezcano `pytest test/test_ops*.py` needs more than an hour to go through the tests and I don't even have cuda so it skips a lot. Is there a way to test a specific function? I used `pytest test/test_binary_ufuncs.py` but I'm not sure that this applies here.

**Comment by Lezcano** [comment]
`pytest --help` may help. In particular, `pytest -vk` is what you're looking for.

**Comment by kaad01** [comment]
Im in my exams right now and I have Problems with my Pytorch. I'll work on this in 3-4 days.

**Comment by kaad01** [comment]
> @kaad01 I ended up submitting a fix myself, as I needed this function to be efficient and correct to be able to fix a different bug. See the fix: [#82713 (comment)](https://github.com/pytorch/pytorch/pull/82713#issuecomment-1203828632)

I See, sorry It took so long. I really had a lot on my plate and I don't have a development environment at the moment. Still learned a lot thank you. I hope to work by your side again in the future.

**Comment by Lezcano** [comment]
No problem! And thanks for trying!

**Comment by cantonios** [comment]
We at TensorFlow are having similar discussions.  The issue with defining the gradient to return a non-zero when x is zero is that it somewhat defeats the purpose of having a `xlogy` function in the first place (as opposed to using `x * log(y)`).

The main benefit of `xlogy` is that if `x == 0` and `y <= 0`, the output is still safe (i.e. not `NaN`).  If you change the gradient to return `log(y)` even when `x` is zero, your gradient will blow up, so the function is no longer safe to use in models for training.

You currently have this issue for `xlog1py`:
```
import torch

x = torch.tensor([[0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)
y = torch.tensor([[0., 1., -1., -6.]], dtype=torch.float64, requires_grad=True)
z = torch.special.xlogy(x, 1. + y)
z.sum().backward()
print('xlogy(x, 1 + y):', x.grad)

x = torch.tensor([[0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)
y = torch.tensor([[0., 1., -1., -6.]], dtype=torch.float64, requires_grad=True)
z = x * torch.log(1. + y)
z.sum().backward()
print('x * log(1 + y): ', x.grad)

x = torch.tensor([[0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)
y = torch.tensor([[0., 1., -1., -6.]], dtype=torch.float64, requires_grad=True)
z = torch.special.xlog1py(x, y)
z.sum().backward()
print('xlog1py(x, y):  ', x.grad)

x = torch.tensor([[0., 0., 0., 0.]], dtype=torch.float64, requires_grad=True)
y = torch.tensor([[0., 1., -1., -6.]], dtype=torch.float64, requires_grad=True)
z = x * torch.log1p(y)
z.sum().backward()
print('x * log1p(y):   ', x.grad)
```
```
xlogy(x, 1 + y): tensor([[0., 0., 0., 0.]], dtype=torch.float64)
x * log(1 + y):  tensor([[0.0000, 0.6931,   -inf,    nan]], dtype=torch.float64)
xlog1py(x, y):   tensor([[0.0000, 0.6931,   -inf,    nan]], dtype=torch.float64)
x * log1p(y):    tensor([[0.0000, 0.6931,   -inf,    nan]], dtype=torch.float64)
```

What you currently have for the gradient of `xlogy` is consistent with the piecewise definition listed on the doc page.

**Comment by Lezcano** [comment]
After https://github.com/pytorch/pytorch/pull/82713, all the examples in the previous message would return the same, `x * log(1 + y):  tensor([[0.0000, 0.6931,   -inf,    nan]], dtype=torch.float64)`.

The issue, as discussed, comes from the fact that this function is not differentiable (it's not even even defined for `x != 0`) at `y = 0`. As such, there is no right or wrong answer here for what should be the gradient at that point.

We could do as @cantonios suggests, and define the gradient at `x = 0, y <= 0` to be zero, but that would be just a patch, as the gradient at `x = 1e-15` would still be `-inf` or `nan` at those points. I'm happy going either way, I'll let @albanD decide what is it that we want.

**Comment by albanD** [comment]
I do agree with the common use-case argument here and returning 0 for the gradient by continuity alongside `x=0` is not too farfetched.
So I would vote for all 0s.

> but that would be just a patch, as the gradient at x = 1e-15 would still be -inf or nan at those points. 

The same is true for many functions including norm. So that is not really an argument against doing it I think.
