### ISSUE TITLE
Affine Grid

### ISSUE THREAD

**Issue by lukasfolle** [pytorch/pytorch#80779]
### 📚 The doc issue

[affine_grid](https://pytorch.org/docs/stable/generated/torch.nn.functional.affine_grid.html#torch-nn-functional-affine-grid) does not describe what happens in case a theta matrix is supplied that is not an affine transformation matrix.

### Suggest a potential alternative/fix

Describe the actual behaviour of the function.

cc @svekars @holly1238 @fmassa @vfdev-5 @pmeier @ezyang @mruberry @ngimel

**Comment by ezyang** [comment]
I don't know what the behavior here is, but when we right the ref for this it probably will make it clear

**Comment by vfdev-5** [comment]
I see, no worries and thanks for clarification! Anyway, docs improvements could be valuable for other users, so if you spot other unclear places in the docs, feel free to open other issues.
