### ISSUE TITLE
ROCM testers often fail at setup step

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#80773]
### 🐛 Describe the bug

For example see:
 https://github.com/pytorch/pytorch/runs/7144402733?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7144402812?check_suite_focus=true
### Versions

N/A

cc @ezyang @gchanan @zou3519 @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
More:
https://github.com/pytorch/pytorch/runs/7173356374?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7173356290?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7173953548?check_suite_focus=true

**Comment by sunway513** [comment]
The data center team is actively working on the network and infrastructure to triage failures and we will keep this thread up to date on the progress.

**Comment by jithunnair-amd** [comment]
These issues have been fixed, so closing this issue.
