### ISSUE TITLE
Operation 'abs_out_mps()' does not support input type 'int64' in MPS backend.

### ISSUE THREAD

**Issue by NHarini-1995** [pytorch/pytorch#80784]
### 🐛 Describe the bug

I am trying to run a pretrained model ProtT5 (Rostlab/prot_t5_xl_half_uniref50-enc) on a Mac OS machine on GPU using the MPS backend of pytorch. 

However, I am getting the following error

Operation 'abs_out_mps()' does not support input type 'int64' in MPS backend.

Can someone help me to fix this errors? 

The entire traceback is attached below.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [11], in <cell line: 2>()
      1 # Compute embeddings and/or secondary structure predictions
----> 2 results = get_embeddings( model, tokenizer, seqs,
      3                          per_residue, per_protein) #, sec_struct
      5 # Store per-residue embeddings
      6 if per_residue:

Input In [7], in get_embeddings(model, tokenizer, seqs, per_residue, per_protein, max_residues, max_seq_len, max_batch)
     41 try:
     42     with torch.no_grad():
     43         # returns: ( batch-size x max_seq_len_in_minibatch x embedding_dim )
---> 44         embedding_repr = model(input_ids, attention_mask=attention_mask)
     45 except RuntimeError:
     46     print("RuntimeError during embedding for {} (L={})".format(pdb_id, seq_len))

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/torch/nn/modules/module.py:1186, in Module._call_impl(self, *input, **kwargs)
   1182 # If we don't have any hooks, we want to skip the rest of the logic in
   1183 # this function, and just call forward.
   1184 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1185         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1186     return forward_call(*input, **kwargs)
   1187 # Do not call functions when jit is used
   1188 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:1838, in T5EncoderModel.forward(self, input_ids, attention_mask, head_mask, inputs_embeds, output_attentions, output_hidden_states, return_dict)
   1820 r"""
   1821 Returns:
   1822 
   (...)
   1834 >>> last_hidden_states = outputs.last_hidden_state
   1835 ```"""
   1836 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
-> 1838 encoder_outputs = self.encoder(
   1839     input_ids=input_ids,
   1840     attention_mask=attention_mask,
   1841     inputs_embeds=inputs_embeds,
   1842     head_mask=head_mask,
   1843     output_attentions=output_attentions,
   1844     output_hidden_states=output_hidden_states,
   1845     return_dict=return_dict,
   1846 )
   1848 return encoder_outputs

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/torch/nn/modules/module.py:1186, in Module._call_impl(self, *input, **kwargs)
   1182 # If we don't have any hooks, we want to skip the rest of the logic in
   1183 # this function, and just call forward.
   1184 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1185         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1186     return forward_call(*input, **kwargs)
   1187 # Do not call functions when jit is used
   1188 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:1033, in T5Stack.forward(self, input_ids, attention_mask, encoder_hidden_states, encoder_attention_mask, inputs_embeds, head_mask, cross_attn_head_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
   1020     layer_outputs = checkpoint(
   1021         create_custom_forward(layer_module),
   1022         hidden_states,
   (...)
   1030         None,  # past_key_value is always None with gradient checkpointing
   1031     )
   1032 else:
-> 1033     layer_outputs = layer_module(
   1034         hidden_states,
   1035         attention_mask=extended_attention_mask,
   1036         position_bias=position_bias,
   1037         encoder_hidden_states=encoder_hidden_states,
   1038         encoder_attention_mask=encoder_extended_attention_mask,
   1039         encoder_decoder_position_bias=encoder_decoder_position_bias,
   1040         layer_head_mask=layer_head_mask,
   1041         cross_attn_layer_head_mask=cross_attn_layer_head_mask,
   1042         past_key_value=past_key_value,
   1043         use_cache=use_cache,
   1044         output_attentions=output_attentions,
   1045     )
   1047 # layer_outputs is a tuple with:
   1048 # hidden-states, key-value-states, (self-attention position bias), (self-attention weights), (cross-attention position bias), (cross-attention weights)
   1049 if use_cache is False:

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/torch/nn/modules/module.py:1186, in Module._call_impl(self, *input, **kwargs)
   1182 # If we don't have any hooks, we want to skip the rest of the logic in
   1183 # this function, and just call forward.
   1184 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1185         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1186     return forward_call(*input, **kwargs)
   1187 # Do not call functions when jit is used
   1188 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:664, in T5Block.forward(self, hidden_states, attention_mask, position_bias, encoder_hidden_states, encoder_attention_mask, encoder_decoder_position_bias, layer_head_mask, cross_attn_layer_head_mask, past_key_value, use_cache, output_attentions, return_dict)
    661 else:
    662     self_attn_past_key_value, cross_attn_past_key_value = None, None
--> 664 self_attention_outputs = self.layer[0](
    665     hidden_states,
    666     attention_mask=attention_mask,
    667     position_bias=position_bias,
    668     layer_head_mask=layer_head_mask,
    669     past_key_value=self_attn_past_key_value,
    670     use_cache=use_cache,
    671     output_attentions=output_attentions,
    672 )
    673 hidden_states, present_key_value_state = self_attention_outputs[:2]
    674 attention_outputs = self_attention_outputs[2:]  # Keep self-attention outputs and relative position weights

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/torch/nn/modules/module.py:1186, in Module._call_impl(self, *input, **kwargs)
   1182 # If we don't have any hooks, we want to skip the rest of the logic in
   1183 # this function, and just call forward.
   1184 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1185         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1186     return forward_call(*input, **kwargs)
   1187 # Do not call functions when jit is used
   1188 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:570, in T5LayerSelfAttention.forward(self, hidden_states, attention_mask, position_bias, layer_head_mask, past_key_value, use_cache, output_attentions)
    559 def forward(
    560     self,
    561     hidden_states,
   (...)
    567     output_attentions=False,
    568 ):
    569     normed_hidden_states = self.layer_norm(hidden_states)
--> 570     attention_output = self.SelfAttention(
    571         normed_hidden_states,
    572         mask=attention_mask,
    573         position_bias=position_bias,
    574         layer_head_mask=layer_head_mask,
    575         past_key_value=past_key_value,
    576         use_cache=use_cache,
    577         output_attentions=output_attentions,
    578     )
    579     hidden_states = hidden_states + self.dropout(attention_output[0])
    580     outputs = (hidden_states,) + attention_output[1:]  # add attentions if we output them

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/torch/nn/modules/module.py:1186, in Module._call_impl(self, *input, **kwargs)
   1182 # If we don't have any hooks, we want to skip the rest of the logic in
   1183 # this function, and just call forward.
   1184 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1185         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1186     return forward_call(*input, **kwargs)
   1187 # Do not call functions when jit is used
   1188 full_backward_hooks, non_full_backward_hooks = [], []

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:519, in T5Attention.forward(self, hidden_states, mask, key_value_states, position_bias, past_key_value, layer_head_mask, query_length, use_cache, output_attentions)
    517         position_bias.requires_grad = True
    518 else:
--> 519     position_bias = self.compute_bias(real_seq_length, key_length, device=scores.device)
    521 # if key and values are already calculated
    522 # we want only the last query position bias
    523 if past_key_value is not None:

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:426, in T5Attention.compute_bias(self, query_length, key_length, device)
    424 memory_position = torch.arange(key_length, dtype=torch.long, device=device)[None, :]
    425 relative_position = memory_position - context_position  # shape (query_length, key_length)
--> 426 relative_position_bucket = self._relative_position_bucket(
    427     relative_position,  # shape (query_length, key_length)
    428     bidirectional=(not self.is_decoder),
    429     num_buckets=self.relative_attention_num_buckets,
    430     max_distance=self.relative_attention_max_distance,
    431 )
    432 values = self.relative_attention_bias(relative_position_bucket)  # shape (query_length, key_length, num_heads)
    433 values = values.permute([2, 0, 1]).unsqueeze(0)  # shape (1, num_heads, query_length, key_length)

File ~/miniforge3/envs/ml/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:397, in T5Attention._relative_position_bucket(relative_position, bidirectional, num_buckets, max_distance)
    395     num_buckets //= 2
    396     relative_buckets += (relative_position > 0).to(torch.long) * num_buckets
--> 397     relative_position = torch.abs(relative_position)
    398 else:
    399     relative_position = -torch.min(relative_position, torch.zeros_like(relative_position))

TypeError: Operation 'abs_out_mps()' does not support input type 'int64' in MPS backend.

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220701
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.3)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.13.0.dev20220701
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchvision==0.14.0.dev20220701
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220701          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20220603          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220701          pypi_0    pypi

cc @kulinseth @albanD

**Comment by ezyang** [comment]
sadly the error is what it says on the tin, and I think mps support for integer dtypes is poor

**Comment by NHarini-1995** [comment]
So does that mean I cannot use this transformer model in the MPS backend? 
This error is popping in a line of the developer's original code and I cannot change that.

**Comment by NHarini-1995** [comment]
I am using a transformed model trained and published in a paper. The model is stored here (https://github.com/agemagician/ProtTrans/). 

It uses PyTorch transformers. And I am using a 2021 Macbook Pro with an M1max chip. Is this issue going to be resolved anytime soon?

**Comment by Birch-san** [comment]
@kulinseth I'm also experiencing  
```
Operation 'abs_out_mps()' does not support input type 'int64' in MPS backend.
```

with Huggingface transformers' T5 model, here:  
https://github.com/huggingface/transformers/blob/5096a654b7743bb0d36e3a2c21d67dc39a4b36a3/src/transformers/models/t5/modeling_t5.py

it's part of T5's forward pass:  
https://github.com/Birch-san/t5-booru/blob/1d8aa7c1f29d6e362b1de4235509a5f86ce3d10c/t5_lightning/model.py

**Comment by Birch-san** [comment]
for that _particular_ algorithm: I think a workaround is possible (casting to short before running `abs()`)…

https://github.com/huggingface/transformers/blob/5096a654b7743bb0d36e3a2c21d67dc39a4b36a3/src/transformers/models/t5/modeling_t5.py#L399  
```diff
- relative_position = torch.abs(relative_position)
+ relative_position = torch.abs(relative_position.to(torch.short)).to(torch.long)
```

because `relative_position` holds small values (indices of a sequence -- your query or key -- both of which I reckon would be small, like <1024 in length).

or pass a tensor of shorts into `_relative_position_bucket` at the callsite, `T5Attention#compute_bias`:  
https://github.com/huggingface/transformers/blob/5096a654b7743bb0d36e3a2c21d67dc39a4b36a3/src/transformers/models/t5/modeling_t5.py#L425-L428  
```
- context_position = torch.arange(query_length, dtype=torch.long, device=device)[:, None]
- memory_position = torch.arange(key_length, dtype=torch.long, device=device)[None, :]
+ context_position = torch.arange(query_length, dtype=torch.short, device=device)[:, None]
+ memory_position = torch.arange(key_length, dtype=torch.short, device=device)[None, :]
```

but I don't think I could upstream this kind of patch into huggingface transformers… it'd defeat the point of their using pytorch as an abstraction to free them from platform specifics.

**Comment by Birch-san** [comment]
@kulinseth I _also_ encounter:

```
Operation 'neg_out_mps()' does not support input type 'int64' in MPS backend.
```  
https://github.com/huggingface/transformers/blob/5096a654b7743bb0d36e3a2c21d67dc39a4b36a3/src/transformers/models/t5/modeling_t5.py#L401

 A couple of lines below the `torch.abs()` problem:  
```python
relative_position = -torch.min(relative_position, torch.zeros_like(relative_position))
```

in the same `modeling_t5.py::T5Attention#_relative_position_bucket`, during T5's forward pass.

**Comment by jaymegordo** [comment]
Also having this same issue on M1 MBP

**Comment by kulinseth** [comment]
@Birch-san , can you please try with latest PyTorch nightly and [MacOS 13.3](https://developer.apple.com/news/releases/?id=02282023c). The T5 network seems to be working fine:

```
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-xxl")
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-xxl", device_map="auto")

input_text = "translate English to German: How old are you?"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("mps")

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))
```

The output:

```
<pad> Wie alt sind Sie?</s>
```

**Comment by Birch-san** [comment]
@kulinseth thanks for this! I've upgraded to macOS 13.3 (b):

<img width="392" alt="image" src="https://user-images.githubusercontent.com/6141784/223275383-8ba83810-589e-4e22-bd5e-cc1c7219453e.png">

tried out `2.1.0.dev20230306` nightly (with flan-t5-small, since 10GB seemed a bit much):

```
In [1]: import torch
In [2]: torch.__version__
Out[2]: '2.1.0.dev20230306'

In [3]: from transformers import T5Tokenizer, T5ForConditionalGeneration
   ...: 
   ...: tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-small")
   ...: model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-small", device_map="auto")
   ...: 
   ...: input_text = "translate English to German: How old are you?"
   ...: input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("mps")
   ...: 
   ...: outputs = model.generate(input_ids)
   ...: print(tokenizer.decode(outputs[0]))
/Users/birch/anaconda3/envs/diffnightly/lib/python3.10/site-packages/transformers/generation/utils.py:1387: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 20 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
/Users/birch/anaconda3/envs/diffnightly/lib/python3.10/site-packages/transformers/generation/utils.py:1470: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on mps, whereas the model is on cpu. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.
  warnings.warn(
/Users/birch/anaconda3/envs/diffnightly/lib/python3.10/site-packages/transformers/generation/utils.py:2338: UserWarning: MPS: no support for int64 for min_max, downcasting to a smaller data type (int32/float32). Native support for int64 has been added in macOS 13.3. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1221.)
  if unfinished_sequences.max() == 0 or stopping_criteria(input_ids, scores):
<pad> Wie ich er bitten?</s>
```

(different result, but it's a smaller model).

hm, it had to downcast to int32? it says native support _should_ be possible on 13.3, and I _am_ on 13.3. maybe something's not gone well?
