### ISSUE TITLE
torch.arctan2() returns wrong value

### ISSUE THREAD

**Issue by suresh-guttikonda** [pytorch/pytorch#80795]
### 🐛 Describe the bug

The results of torch.arctan2() is not similar to np.arctan2() for {-pi, pi}

``` python
>>> import torch
>>> import numpy as np

>>> theta = torch.tensor(-np.pi)
>>> torch.arctan2(torch.sin(theta), torch.cos(theta))
tensor(3.1416)
>>> theta = -np.pi
>>> np.arctan2(np.sin(theta), np.cos(theta))
-3.141592653589793

>>> theta = torch.tensor(np.pi)
>>> torch.arctan2(torch.sin(theta), torch.cos(theta))
tensor(-3.1416)
>>> theta = np.pi
>>> np.arctan2(np.sin(theta), np.cos(theta))
3.141592653589793

```

### Versions

``` python
>>> torch.__version__
'1.12.0'
>>> np.__version__
'1.22.3'
```

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
Per Wikipedia, output should be negative when y is negative. So this indeed looksw rong.

**Comment by anonymousr007** [comment]
Hi @ezyang,

I'm Rishabh, an undergraduate computer engineering student and I'm new here, but I contributed to cirq-google, pennylane-Xanadu, Github, and NASA-prognostics-models.  Is it open? I want to make a PR for this issue.

Thanks & Regards
Rishabh

**Comment by ezyang** [comment]
sure go ahead

**Comment by suresh-guttikonda** [comment]
Update: It seems the bug has been there at-least since '1.9.0+cu102'

```
(base)$ conda create -n torch1.9_cu102 python=3.7
(torch1.9_cu102)$ pip install torch==1.9.0+cu102 torchvision==0.10.0+cu102 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

>>> import torch
>>> import numpy as np
>>> theta = torch.tensor(-np.pi)
>>> torch.atan2(torch.sin(theta), torch.cos(theta))
tensor(3.1416)
```

**Comment by suresh-guttikonda** [comment]
Update: turns out the issue is with default `torch.tensor(-np.pi)` returning a `float32 tensor` for a float64 input. The work around is explicitly mention dtype.
```
>>> import torch

>>> theta = torch.tensor(-torch.pi)
>>> torch.arctan2(torch.sin(theta), torch.cos(theta))
tensor(3.1416)

>>> theta = torch.tensor(-torch.pi, dtype=torch.float64)
>>> torch.arctan2(torch.sin(theta), torch.cos(theta))
tensor(-3.1416, dtype=torch.float64)
```

**Comment by suresh-guttikonda** [comment]
https://pytorch.org/docs/stable/tensor_attributes.html
```A floating point scalar operand has dtype torch.get_default_dtype() and an integral non-boolean scalar operand has dtype torch.int64. Unlike numpy, we do not inspect values when determining the minimum dtypes of an operand. Quantized and complex types are not yet supported.```
