### ISSUE TITLE
pytorchbot merge does not report an error when the merge workflow times out

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#80798]
see: https://github.com/pytorch/pytorch/pull/80752

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
I see two actions here:
1. merge bot should realize that the xla job was never going to be triggered + error out sooner
2. we should alert user when the job times out (maybe in a workflow_run action)
ccing @zengk95

**Comment by janeyx99** [comment]
Another instance: https://github.com/pytorch/pytorch/runs/7116440019?check_suite_focus=true

**Comment by ZainRizvi** [comment]
@suo, have you still been seeing this error? If not, we can close this issue

**Comment by ZainRizvi** [comment]
Closing since as per [this link](https://github.com/pytorch/pytorch/actions/workflows/trymerge.yml?query=is%3Atimed_out) we haven't seen any timeouts happen recently.

Can reopen if we find these errors again
