### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ZhuMai** [pytorch/pytorch#80802]
### 🐛 Describe the bug

I have tried training some models which have been trained normally on other machines. After some epochs, there will be a "Segmentation fault (core dumped)".  In most cases, no specific error is reported after the issue happens. Sometimes, the training is stuck. Some other times, simply "Segmentation fault (core dumped)" is reported. I only got once as follows.

```
Traceback (most recent call last):
  File "/home/my/.local/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/my/Documents/nnUNet/nnunet/run/run_training.py", line 181, in myn
    trainer.run_training(train_minutes)
  File "/home/my/Documents/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 441, in run_training
    ret = super().run_training(train_minutes)
  File "/home/my/Documents/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training(train_minutes)
  File "/home/my/Documents/nnUNet/nnunet/training/network_training/network_trainer.py", line 457, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/my/Documents/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 253, in run_iteration
    self.amp_grad_scaler.scale(l).backward()
  File "/home/my/.local/lib/python3.10/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/my/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 139861600222144)
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/home/my/.local/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
  File "/home/my/.local/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
```

### Versions

PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-40-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchvision==0.13.0+cu116
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.5           py39he7a7128_1
[conda] numpy-base                1.21.5           py39hf524024_1
[conda] numpydoc                  1.2                pyhd3eb1b0_0

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by ezyang** [comment]
Is there any chance you can turn on core dumps (or preattach gdb to the process) and get us a stacktrace when the segfault happens? Alternately, is there any way you can share repro instructions? The backtrace you have tells us something bad happened in the autograd engine, which unfortunately, isn't enough for us to usefully help you out.

**Comment by ZhuMai** [comment]
At first, I activate core dump and enable Apport in Ubuntu.
```
ulimit -c unlimited
systemctl enable apport.service
```
Next, I trained [nnUNets](https://github.com/MIC-DKFZ/nnUNet) using the following commands.
```
nnUNet_train 3d_fullres nnUNetTrainerV2 9 0
```
It is a pity that computer is always stuck but not core dump after I activate core dump.

**Comment by ZhuMai** [comment]
I reproduce the core dump by
```
nnUNet_train 3d_fullres nnUNetTrainerV2 4 0
```
However, there is no dump file under /var/crash/.

**Comment by ezyang** [comment]
Try just running it in gdb directly. `gdb --args nnUNet_train 3d_fullres nnUNetTrainerV2 4 0` and then after gdb loads up enter `run`. This may not work if `nnUNet_train` is an alias, if so, paste in the full alias contents in place of `nnUNet_train` (it may also not work if `nnUNet_train` is a shell script, in that case edit the script so that the python call has gdb --args`

**Comment by ZhuMai** [comment]
The issue vanished after I removed 16G*2 RAM from 16G*4 RAM. I will close this issue. Thank you for your help.
