### ISSUE TITLE
MPS RuntimeError: view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by Maxhirez** [pytorch/pytorch#80800]
### 🐛 Describe the bug

I've been experimenting with OpenAI's CLIP on a Mac Studio with an M1 Ultra/48 core GPU/128Gb unified now that there's a compatible Torch nightly. 
[Repo](https://github.com/openai/CLIP)

When running the sample in the README, changing line 5 to `device = "CPU"` lets it run with the expected outcome but if I switch it to `device = "mps"` it errors out:
`Traceback (most recent call last): File "/Users/jasonhoffman/Documents/python/mlv/clip_test.py", line 13, in <module> text_features = model.encode_text(text) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/clip/model.py", line 349, in encode_text x = self.transformer(x) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl return forward_call(*input, **kwargs) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/clip/model.py", line 204, in forward return self.resblocks(x) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl return forward_call(*input, **kwargs) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward input = module(input) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl return forward_call(*input, **kwargs) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/clip/model.py", line 191, in forward x = x + self.attention(self.ln_1(x)) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1131, in _call_impl return forward_call(*input, **kwargs) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/clip/model.py", line 163, in forward ret = super().forward(x.type(torch.float32)) File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 189, in forward return F.layer_norm( File "/Users/jasonhoffman/Documents/python/mlv/env/lib/python3.10/site-packages/torch/nn/functional.py", line 2501, in layer_norm return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled) RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
`

The CLIP people at OpenAi suggested I post the error here.
I realize I might be doing something obscure, but is there any reason why I should expect this error? 

### Versions

PyTorch version: 1.13.0.dev20220617
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.0.dev20220617
[pip3] torchvision==0.14.0.dev20220617
[conda] numpy                     1.22.4          py310h0a343b5_0    conda-forge
[conda] pytorch                   1.13.0.dev20220617        py3.10_0    pytorch-nightly
[conda] torchvision               0.14.0.dev20220617       py310_cpu    pytorch-nightly

cc @kulinseth @albanD

**Comment by jpc** [comment]
This one seems actually pretty easy to work around:

> in layer_norm() in functional.py (part of pytorch I guess), change to return torch.layer_norm(input.contiguous(), ...

Figured out by @filipux here:
https://github.com/CompVis/stable-diffusion/issues/25#issuecomment-1221416526

You can find the exact line number and file path where the change needs to be applied in the last lines of your stack trace.

**Comment by Maxhirez** [comment]
Thanks @jpc and @filipux I’ll give it a try!

**Comment by eellison** [comment]
This may have been fixed with https://github.com/pytorch/pytorch/pull/83457

**Comment by jpc** [comment]
I tested it today using `torch-1.13.0.dev20220823-cp39-none-macosx_11_0_arm64.whl` and it did not work for me without the workaround.

**Comment by haowang1013** [comment]
Tested with 1.13.0.dev20220830 and it's still broken.

**Comment by DenisVieriu97** [comment]
This issue is fixed in the latest PyTorch nightly. Please let me know if you see any other issues

**Comment by Maxhirez** [comment]
Thanks Denis!  I'll give it a shot again tonight.

**Comment by shanalikhan** [comment]
Its still broken on the current public release.
