### ISSUE TITLE
Assertion error - _dl_shared_seed_recv_cnt - pt 1.12 - multi node

### ISSUE THREAD

**Issue by shrinath-suresh** [pytorch/pytorch#80845]
### 🐛 Describe the bug

The following pytorch script is a sample implementation which finetunes hugging face model to classify AGNews dataset - https://github.com/chauhang/uber-prof/blob/pytorch-bert-example/training-job/pytorch_news_classifier.py . 

Observing the following error **only in pytorch 1.12** when running in **multi node setup**

```
Traceback (most recent call last):
  File "news_classifier.py", line 418, in <module>
    ddp_main(rank, WORLD_SIZE, args)
  File "news_classifier.py", line 365, in ddp_main
    model.startTraining(model)
  File "news_classifier.py", line 223, in startTraining
    train_acc, train_loss = self.train_epoch(model)
  File "news_classifier.py", line 252, in train_epoch
    for data in tqdm(self.train_data_loader):
  File "/lustre/.conda/envs/mlflow-df07e1ebdf6ec40b564b24fe1519963ccdc9fc38/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/lustre/.conda/envs/mlflow-df07e1ebdf6ec40b564b24fe1519963ccdc9fc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/lustre/.conda/envs/mlflow-df07e1ebdf6ec40b564b24fe1519963ccdc9fc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/lustre/.conda/envs/mlflow-df07e1ebdf6ec40b564b24fe1519963ccdc9fc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1009, in __init__
    super(_MultiProcessingDataLoaderIter, self).__init__(loader)
  File "/lustre/.conda/envs/mlflow-df07e1ebdf6ec40b564b24fe1519963ccdc9fc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 594, in __init__
    self._shared_seed = loader._get_shared_seed()
  File "/lustre/.conda/envs/mlflow-df07e1ebdf6ec40b564b24fe1519963ccdc9fc38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 578, in _get_shared_seed
    assert int(store.get("_dl_shared_seed_recv_cnt")) == 0
```

The same script works on single node and multi node with pytorch 1.11 - 
[pt_1.11_success.txt](https://github.com/pytorch/pytorch/files/9041736/pt_1.11_success.txt)

Even with pytorch 1.12, single node multi gpu works without any error - 
[pt_1.12_single_node_success.txt](https://github.com/pytorch/pytorch/files/9041739/pt_1.12_single_node_success.txt)

Failure is observed only on the multi node setup with pytorch 1.12 - 
[pt_1.12_error.txt](https://github.com/pytorch/pytorch/files/9041740/pt_1.12_error.txt)

Sample commands:

For single node - `torchrun --nnodes 1 --nproc_per_node 4 --rdzv_backend c10d --rdzv_id 123 --rdzv_endpoint xx.xx.xx.xx --standalone news_classifier.py --max_epochs 5`

For multi node (run on all the nodes) - `torchrun --nnodes 2 --nproc_per_node 4 --rdzv_backend c10d --rdzv_id 123 --rdzv_endpoint xx.xx.xx.xx news_classifier.py --max_epochs 5`

### Versions

**Environment output for pt.1.12**
[pt_1.12.environment.txt](https://github.com/pytorch/pytorch/files/9041745/pt_1.12.environment.txt)

**Environment output for pt 1.11** - 
[pt_1.11.environment.txt](https://github.com/pytorch/pytorch/files/9041747/pt_1.11.environment.txt)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @SsnL @VitalyFedyunin @ejguan @NivekT @ezyang

**Comment by chauhang** [comment]
cc: @VitalyFedyunin @ejguan

**Comment by VitalyFedyunin** [comment]
This is supposed to be fixed in https://github.com/pytorch/pytorch/commit/3ec9d34f21edfb330076a2e57dd9b30649070e80 I'm checking release branch to figure out if it there or not.

**Comment by VitalyFedyunin** [comment]
It is not in 1.12 branch cut, we would need some time to figure out solution here. 
@shrinath-suresh can you please check if it works fine on nightly build.

**Comment by shrinath-suresh** [comment]
@VitalyFedyunin Observing the same error(on both single node and multi node) with nightly builds as well .
[pt_13nightly_environment.txt](https://github.com/pytorch/pytorch/files/9062332/pt_13nightly_environment.txt)
[pt_1.13nightly_singlenode_failure.txt](https://github.com/pytorch/pytorch/files/9062333/pt_1.13nightly_singlenode_failure.txt)
[pt_1.13nightly_failure.txt](https://github.com/pytorch/pytorch/files/9062334/pt_1.13nightly_failure.txt)

**Comment by VitalyFedyunin** [comment]
Hello!

1) I noticed it is happening only on the second epoch, is it always the case?
2) What is your world size?

Thanks

**Comment by ejguan** [comment]
Comment regarding minor release 1.12.1, we need to do a TorchData minor release to reflect the dependency changes (PyTorch).

And the patches need to be cherry-picked for 1.12.1:
- https://github.com/pytorch/pytorch/pull/80348
- https://github.com/pytorch/pytorch/pull/81071
