### ISSUE TITLE
Mps Torch Stack Return Value

### ISSUE THREAD

**Issue by Hanyang97** [pytorch/pytorch#80850]
### 🐛 Describe the bug

```python
import torch

print(torch.stack([torch.tensor([True], device='cpu'), torch.tensor([True], device='cpu')]))
print(torch.stack([torch.tensor([True], device='mps:0'), torch.tensor([True], device='mps:0')]))
```

The return values are
```
tensor([[True], [True]])
tensor([[False], [False]], device='mps:0')
```

### Versions

$ python collect_env.py
Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.21.5           py39h2e5f0a9_1  
[conda] numpy-base                1.21.5           py39h3b1a694_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0

cc @ezyang @gchanan @zou3519 @kulinseth @albanD

**Comment by qqaatw** [comment]
I can reproduce. It stems from `cat` mps backend.

**Comment by zou3519** [comment]
High pri for silent correctness

**Comment by kulinseth** [comment]
Thanks @Hanyang97 this is indeed failing with latest master.
