### ISSUE TITLE
Custom TorchScript op causes duplicated TORCH_LIBRARY block

### ISSUE THREAD

**Issue by Belval** [pytorch/pytorch#80865]
### 🐛 Describe the bug

When wrapping CUDA kernels to use them as custom TorchScript operators, I get the following exception which I don't understand:

```
terminate called after throwing an instance of 'c10::Error'
  what():  Only a single TORCH_LIBRARY can be used to register the namespace custom_deform_conv; please put all of your definitions in a single TORCH_LIBRARY block.  If you were trying to specify implementations, consider using TORCH_LIBRARY_IMPL (which can be duplicated).  If you really intended to define operators for a single namespace in a distributed way, you can use TORCH_LIBRARY_FRAGMENT to explicitly indicate this.  Previous registration of TORCH_LIBRARY was registered at [MY_FILE]:5; latest registration was registered at [MY_FILE]:5
```

but my `custom_deform_conv.cpp` only calls it once. Additionally, you can see that both calls are from line 5. I made sure that I was not loading the resulting library twice but that did not change anything.

```cpp
#include <torch/script.h>
#include "deform_conv.h"

namespace deform_conv {
TORCH_LIBRARY(custom_deform_conv, m) {
  m.def("deform_conv_forward(Tensor input, Tensor weight, Tensor offset, Tensor output, Tensor columns, Tensor ones, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH, int group, int deformable_group, int im2col_step) -> int");
  m.def("deform_conv_backward_input(Tensor input, Tensor offset, Tensor gradOutput, Tensor gradInput, Tensor gradOffset, Tensor weight, Tensor columns, int kW, int kH, int dW, int dH, int padW, int padH, int dilationW, int dilationH, int group, int deformable_group, int im2col_step) -> int");
}

TORCH_LIBRARY_IMPL(custom_deform_conv, CUDA, m) {
  m.impl("deform_conv_forward", deform_conv_forward);
  m.impl("deform_conv_backward_input", deform_conv_backward_input);
}
}
```

`deform_conv.h` does not call/use TORCH_LIBRARY in any way.

Here is the resource I used: https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html 

Is there any more complete TorchScript CUDA extension I could have a look at?

### Versions

PyTorch version: 1.12.0a0+8a1a93a
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1031-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0a0+8a1a93a
[pip3] torch-tb-profiler==0.4.0
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.13.0a0
[pip3] torchvision==0.13.0a0
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.3           py38h99721a1_2    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.12.0a0+8a1a93a          pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.13.0a0                 pypi_0    pypi
[conda] torchvision               0.13.0a0                 pypi_0    pypi

**Comment by davidberard98** [comment]
Could you check to verify that custom_deform_conv.cpp is only initializing once during program execution?

Example: https://gist.github.com/davidberard98/716679a9bae7ba76f37a224943cdcdf1
^ When I run this, the output is "Counter: 2", indicating that _two_ CounterIncr objects are created (since x.cpp is duplicated). Could you try to run a test like this to see whether this is happening? Based on the error message I think this could be one explanation.

**Comment by Belval** [comment]
I apologize for the inconvenience, it was indeed quite self-inflicted. I used a CUDAExtension object through a `setup.py` file to build the extension and  it probably calls TORCH_LIBRARY twice.

For anyone who encounter the issue, here is my final `CMakeLists.txt` that is able to compile CUDA without any issue:

```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)
project(custom_deform_conv LANGUAGES CUDA CXX)

find_package(Torch REQUIRED)

# Define our library target
add_library(custom_deform_conv SHARED deform_conv_cuda_kernel.cu deform_conv_cuda.cu deform_conv.cpp)
include_directories(.)
add_compile_definitions(WITH_CUDA)
add_compile_options(-DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__)
# Enable C++14
target_compile_features(custom_deform_conv PRIVATE cxx_std_14)
# Link against LibTorch
target_link_libraries(custom_deform_conv "${TORCH_LIBRARIES}")
```
