### ISSUE TITLE
slow test infra cannot handle nested suites

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#80875]
### 🐛 Describe the bug

We currently categorize a selection of slow test cases in our repo to run on a particular config. We query for tests slower than a certain threshold and put these tests into a json every night. The slow tests json generated by our infra looks like: https://github.com/pytorch/test-infra/blob/generated-stats/stats/slow-tests.json.

The code in our CI that parses the JSON to detect whether or not to run the test is https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1544. Note that we perfectly match a test name with the keys of the JSON. 

This is almost always correct, except not all test suites proceed with a `__main__`, which we assume in our query here https://github.com/pytorch/test-infra/blob/main/torchci/rockset/commons/__sql/slow_tests.sql#L57.

### Solution
Let's change the logic in the test selection side to not care about `__main__` when figuring out if a test is a match.

### Versions

CI related

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by Raman-Kumar** [comment]
@janeyx99 
Hi, I want to take this issue and solve it.
I am new to this project.
Any suggestion?

**Comment by clee2000** [comment]
I think this is fixed by https://github.com/pytorch/pytorch/issues/104002
