### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_TensorBase'

### ISSUE THREAD

**Issue by DanielDagnino** [pytorch/pytorch#8088]
Hi all,
I have installed successfully Pytorch in a MacBookPro with an eGPU and everything is OK, however, when I try to install the Opencv package I have some problems that I can fix following the suggestion:
https://github.com/jrobchin/Computer-Vision-Basics-with-Python-Keras-and-OpenCV/issues/1
In short, I have created a new environment and I have installed:
```
conda install openblas=0.2.19
conda install -c conda-forge opencv --override-channels
conda uninstall opencv
conda install -c https://conda.binstar.org/menpo opencv3
```
After that, I do not have problems with Opencv but with Pytorch. The erro is the following:

> Traceback (most recent call last):
>   File "/Users/xxx/eclipse-workspace/unet/train.py", line 15, in <module>
>     from common import *
>   File "/Users/xxx/eclipse-workspace/unet/common.py", line 27, in <module>
>     import torch
>   File "/Users/xxx/anaconda3/envs/x1/lib/python3.6/site-packages/torch/__init__.py", line 184, in <module>
>     from .tensor import Tensor
>   File "/Users/xxx/anaconda3/envs/x1/lib/python3.6/site-packages/torch/tensor.py", line 12, in <module>
>     class Tensor(torch._C._TensorBase):
> AttributeError: module 'torch._C' has no attribute '_TensorBase'

I do not have idea how to fix it. Can anybody help me?
Thanks,
Dani.

**Comment by SsnL** [comment]
Can you try uninstall and reinstall? I'm assuming that you built from source. Can you also check if you have binary pytorch installed?

**Comment by soumith** [comment]
thats great to hear that you solved it :)

**Comment by priyankachapala** [comment]
module 'torch' has no attribute '_C'
how can I solve this error. I have tried the steps mentioned in this thread.

**Comment by TachikakaMin** [comment]
> module 'torch' has no attribute '_C'
> how can I solve this error. I have tried the steps mentioned in this thread.

torch._tensor._C._TensorBase

**Comment by Romeo-CC** [comment]
same here
pytorch version: 2.2.0

installed via conda and pip

**Comment by jayong-sv** [comment]
I had this problem when torch version was higher than 2.1.0. I downgraded it to 2.1.0 and works fine now.
```
--index-url https://download.pytorch.org/whl/cpu
torch==2.1.0
torchvision==2.1.0
torchaudio==0.16.0
```
