### ISSUE TITLE
TorchScript interpreter codegen Failed

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#80911]
### 🐛 Describe the bug

I got the following bug with the code snippet below.

Traceback (most recent call last):
  File "exp_small.py", line 50, in <module>
    result = scripted_f_origin(*inp_origin)
  File "../pytorch/torch/nn/modules/module.py", line 1186, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Attempting to bind T0.size[1] to 64but it's already set to 512

 PYTORCH_NVFUSER_DISABLE=fallback python main.py

```python
from functorch import make_fx
import torch
from functorch.compile import ts_compile
from functorch.compile import default_decompositions



################## Graphs before rematerialization ###################

def f_origin(relu_default_16, new_zeros_default_63, to_dtype_3, convolution_default_20, params_63, _tensor_constant40_1, _tensor_constant41_1, new_zeros_default_60):
    to_dtype_4 = torch.ops.aten.to(relu_default_16, torch.float32);  relu_default_16 = None
    le_scalar = torch.ops.aten.le(to_dtype_4, 0);  to_dtype_4 = None
    where_self = torch.ops.aten.where(le_scalar, new_zeros_default_63, to_dtype_3);  le_scalar = new_zeros_default_63 = to_dtype_3 = None
    to_dtype_5 = torch.ops.aten.to(where_self, torch.float32);  where_self = None
    native_batch_norm_backward_default = torch.ops.aten.native_batch_norm_backward(to_dtype_5, convolution_default_20, params_63, _tensor_constant40_1, _tensor_constant41_1, new_zeros_default_60, new_zeros_default_60, False, 1e-05, [True, True, True]);  convolution_default_20 = params_63 = _tensor_constant40_1 = _tensor_constant41_1 = new_zeros_default_60 = None
    getitem_63 = native_batch_norm_backward_default[0]
    getitem_64 = native_batch_norm_backward_default[1]
    getitem_65 = native_batch_norm_backward_default[2];  native_batch_norm_backward_default = None
    return (to_dtype_5, getitem_63, getitem_64, getitem_65)


################## Inputs ###################

relu_default_16 = torch.rand(torch.Size([96, 512, 4, 4]), device="cuda", requires_grad=False, dtype=torch.float32)
new_zeros_default_63 = torch.rand(torch.Size([]), device="cuda", requires_grad=False, dtype=torch.float32)
to_dtype_3 = torch.rand(torch.Size([96, 512, 4, 4]), device="cuda", requires_grad=False, dtype=torch.float32) 
convolution_default_20 = torch.rand(torch.Size([96, 512, 4, 4]), device="cuda", requires_grad=False, dtype=torch.float32) 
params_63 = torch.rand(torch.Size([512]), device="cuda", requires_grad=False, dtype=torch.float32)
_tensor_constant40_1 = torch.tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], device='cuda', requires_grad=False)
_tensor_constant41_1 = torch.tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], device='cuda', requires_grad=False)
new_zeros_default_60 = torch.rand(torch.Size([0]), device="cuda", requires_grad=False, dtype=torch.float32)

inp_origin = (relu_default_16, new_zeros_default_63, to_dtype_3, convolution_default_20, params_63, _tensor_constant40_1, _tensor_constant41_1, new_zeros_default_60)
traced_graph_origin = make_fx(f_origin, decomposition_table=default_decompositions)(*inp_origin)
scripted_f_origin = ts_compile(traced_graph_origin, 0)



with torch.no_grad():
    for i in range(5):
        result = scripted_f_origin(*inp_origin)
        torch.cuda.synchronize()
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+gitda61ec2
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (conda-forge gcc 12.1.0-16) 12.1.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.5
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1069-aws-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] botorch==0.6.4
[pip3] flowtorch==0.8
[pip3] functorch==0.3.0a0+6cfb462
[pip3] gpytorch==1.6.0
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] numpyro==0.9.2
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.13.0a0+gitda61ec2
[pip3] torch-struct==0.5
[pip3] torchaudio==0.12.0a0+4d2fa19
[pip3] torchdynamo==0.2.0
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.9.1
[pip3] torchrec-nightly==2022.4.26
[pip3] torchtext==0.13.0a0+d6e3550
[pip3] torchvision==0.14.0a0+a7e4fbd
[pip3] torchx-nightly==2022.6.8
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] botorch                   0.6.4                    pypi_0    pypi
[conda] flowtorch                 0.8                      pypi_0    pypi
[conda] functorch                 0.3.0a0+6cfb462           dev_0    <develop>
[conda] gpytorch                  1.6.0                    pypi_0    pypi
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] magma-cuda116             2.6.1                         0    pytorch
[conda] mkl                       2022.1.0                 pypi_0    pypi
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.22.0                   pypi_0    pypi
[conda] numpy-base                1.22.3           py38hf524024_0  
[conda] numpyro                   0.9.2                    pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torch                     1.13.0a0+gitda61ec2           dev_0    <develop>
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                0.12.0a0+4d2fa19           dev_0    <develop>
[conda] torchdynamo               0.2.0                     dev_0    <develop>
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchmetrics              0.9.1                    pypi_0    pypi
[conda] torchrec-nightly          2022.4.26                pypi_0    pypi
[conda] torchtext                 0.13.0a0+d6e3550           dev_0    <develop>
[conda] torchvision               0.14.0a0+a7e4fbd           dev_0    <develop>
[conda] torchx-nightly            2022.6.6                 pypi_0    pypi

cc @jjsjann123

**Comment by ngimel** [comment]
The inputs seem invalid - _tensor_constant40_1 and _tensor_constant41_1 are of size 64, whereas (running_mean and running_var) they should be of size 512. How did you obtain the inputs?
Eager mode also accepts these inputs, which seems like a mistake, but native_batch_norm_backward API is not expected to be user-facing, so some input checks are omitted.

**Comment by jjsjann123** [comment]
> The inputs seem invalid - _tensor_constant40_1 and _tensor_constant41_1 are of size 64, whereas (running_mean and running_var) they should be of size 512. How did you obtain the inputs? Eager mode also accepts these inputs, which seems like a mistake, but native_batch_norm_backward API is not expected to be user-facing, so some input checks are omitted.

Looks like updating bias/scale to size of 512 nvfuser error goes away.

**Comment by yushangdi** [comment]
Thanks!
