### ISSUE TITLE
pytorch/examples/imagenet/main.py hang when world_size value is greater than 1

### ISSUE THREAD

**Issue by cya410** [pytorch/pytorch#8091]
Hello I tried running resnet50 and imagenet using the following commands:

    python ./scripts/imagenet.py \
    --arch=resnet50 \
    --epochs=1 \
    --batch-size=64 \ 
    --lr=0.01 \
    --workers=4 \
    --world-size=2 \ 
    --dist-backend=gloo \
    --dist-url=file:///workspace/sharedfile \
    --rank=0 \
    --print-freq 10 /workspace/imagenet

The program hangs without launching anything when --world-size value is greater than 1. The problem is that the init_process_group never return.

    dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url, 
                            world_size=args.world_size, rank=0)

It is actually calling a C++ function. I added a bunch of output to make sure that the parameters are all correct:

    print("calling _dist_init_process_group with")
    print("backend ", backend)
    print("init_method", init_method)
    print("world_size", world_size)
    print("group_name", group_name)
    print("rank", rank)
    torch._C._dist_init_process_group(backend, init_method, world_size,
                                      group_name, rank)
    print("_dist_init_process_group done")

I also tried a bunch of combinations as follow and they all end up with hanging.

    --dist-url=tcp://10.1.1.20:23456
    --dist-url=tcp://127.0.0.1:29500 
    --dist-url=file:///workspace/sharedfile 
    
    --dist-backend=tcp
    --dist-backend=gloo
    --dist-backend=nccl

Any help would be appreciated, thanks.

Update: even this simple python test ended up with hanging:

    import torch.distributed as dist

    dist.init_process_group(backend='gloo', init_method='file:///workspace/sharedfile', world_size=4, rank=0)

    print('Hello from process {} (out of {})!'.format(dist.get_rank(), dist.get_world_size()))

**Comment by heitorschueroff** [comment]
@cya410, please open another issue under pytorch/examples if this is still ongoing.
