### ISSUE TITLE
It's difficult to use non-standard CUDA_HOME with ccache'd nvcc

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8092]
Here's the situation:

Ideally, you'd say something like `CUDA_HOME=/usr/local/cuda-9.1 python setup.py install` to make a build of PyTorch with a non-standard version of CUDA.

When this happens, `FindCUDA` needs to find the correct copy of nvcc to use.

If you are using ccache as per the instructions in https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#use-ccache you'll have set `CUDA_NVCC_EXECUTABLE` to your ccache binary, so that ccache happens. cmake will correctly respect this variable.

However, here's the problem: ccache's nvcc will **use your path** to determine what the real nvcc to use is, this means that you'll pick up whatever nvcc is in your PATH, which is probably not the one you want, because you're trying to use a different nvcc.

So in sum, you have to do the non-intuitive `CUDA_HOME=/usr/local/cuda-9.1 PATH=/usr/local/cuda-9.1/bin:$PATH python setup.py install` to get the whole shebang to work. The worst part is that it won't tell you if you've got it wrong, it will happily use the wrong nvcc.

I haven't gone through user submitted issues to see if anyone has succumbed to this particular bug.

**Comment by xuhdev** [comment]
A long-term solution might be getting [CMAKE_CUDA_COMPILER_LAUNCHER](https://cmake.org/cmake/help/v3.15/variable/CMAKE_LANG_COMPILER_LAUNCHER.html) to work

**Comment by peterbell10** [comment]
`CMAKE_CUDA_COMPILER_LAUNCHER` works now.
