### ISSUE TITLE
[ONNX] Tool to find mismatch in exported ONNX model

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#80973]
### 🚀 The feature, motivation and pitch

Output mismatch between exported ONNX and PyTorch models has been a hard to debug problem. Developers and data scientists usually encounter this problem in the following scenarios. 

* A new kind of model exports successfully to ONNX, but outputs don’t match. 
* An ONNX model that works correctly on a given set of inputs (usually the ones it was originally exported with), but outputs don’t match for other set of inputs. 
* An ONNX model that matched results previously, but due to package version changes the results start to differ. 

So far there hasn’t been any effective/automatic tools to help with investigation. Developers had to manually compare results between subgraph of ONNX and PyTorch. 

Usually, the root cause of mismatch problem is not hard to fix, after it was discovered. It could be any one of the following scenarios: 

* The operator use case is new and not exported correctly. 
* Dynamic value (sometimes could be configuration or hyperparameter) exported as constant. 
* Dynamic graph (controlflow) exported as static graph. 
* Discrepancies between PyTorch and ONNX operator spec/implementation.

## Proposal

Proposing a new API under `torch.onnx` module to try export the model and automatically find the first operator/node that produces mismatch results. 

## Goals 

* To find the first operator/node in ONNX model, and corresponding line in PyTorch that starts the mismatch. 
* The first version may support only tracing based export. 

## Non-Goals 

* This tool does not fix the mismatch. 
* This tool requires successful export as pre-condition: it does not fix and cannot work under export failures.

**Comment by thiagocrepaldi** [comment]
@BowenBao has this tool been designed/implemented? Should we close this issue or move it to the "design discussions" bucket for futre implementation? will leave open for visibility

**Comment by BowenBao** [comment]
Next step is to evaluate it with larger set of models. Preferably utilize work from the torch bench effort https://github.com/microsoft/onnx-converters-private/issues/100

**Comment by BowenBao** [comment]
Can try this on the mismatched ones in pytorch-jit-parity tests. Low priority tho

**Comment by BowenBao** [comment]
This is completed via https://pytorch.org/docs/stable/onnx_torchscript.html#torch.onnx.verification.find_mismatch.
