### ISSUE TITLE
TensorList Python Binding Encountering C++ TypeError

### ISSUE THREAD

**Issue by juanpaez22** [pytorch/pytorch#80979]
### 🐛 Describe the bug

I am trying to write a C++ extension for PyTorch that has a custom operation that accepts a TensorList as an input (following tutorial here: https://pytorch.org/tutorials/advanced/cpp_extension.html). In Python, this should simply bind to a list of tensors. However, a TypeError is thrown when trying to call the function.

```
TypeError: incompatible function arguments. The following argument types are supported: 
   1. (arg0: c10::ArrayRef<at::Tensor>) -> bool  
Invoked with: [tensor([1]), tensor([2])]
```

A minimal repro example was reported here: https://discuss.pytorch.org/t/typeerror-when-passing-list-of-tensors-to-c/150207

```
#include <torch/extension.h>
#include <pybind11/pybind11.h>

bool test_tensorlist(torch::TensorList x) {
  return true
}

PYBIND11_MODULE(tensorlist, m) {
    m.doc() = "Test how to pass tensor list to C++ extension.";
    m.def("test_tensorlist", &test_tensorlist, "Pass list of tensors (as torch::TensorList).")
}
```

Then, when simply importing the module in Python and calling the function (with any list of tensors), the above error is thrown.

### Versions

PyTorch version: 1.11.1+cputorchort
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-48-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.11.1+cputorchort
[pip3] torchtext==1.11.1+cputorchort
[pip3] torchvision==1.11.1+cputorchort
[conda] Could not collect

cc @malfet @zou3519

**Comment by cpuhrsch** [comment]
Hello @juanpaez22, thank you for reporting this issue! Does the error persist with the newest version of PyTorch? Thanks!

**Comment by juanpaez22** [comment]
Thanks for the response! Just tried to repro with the latest release (1.12.0+cpu). An error still occurs, but the text itself is different:
```
>>> torch.ops.my_ops.custom_op([tensor, tensor])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanpaez/pytorch_repro/venv/lib/python3.8/site-packages/torch/_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Missing cases in 'toPyObject'! Can't convert SymInt to a Python object
```

Looks like that may have been fixed here: https://github.com/pytorch/pytorch/pull/79795

Will try building from source and see if the issue persists

**Comment by juanpaez22** [comment]
The binding works correctly with nightly release (1.13.0.dev20220707+cpu). Thanks for the help!
