### ISSUE TITLE
[Prims+NVFuser] aten.to.dtype refs impl causing segfault

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/pytorch#80982]
model: pytorch_struct_forward_0
Condition: enable aten2aten decomps 

Partitions proposed:
partition 0 ['to_dtype_45', 'exp_default_2', 'sum_dim_int_list_2', 'log_default_2', 'sub_tensor_5', 'sub_tensor_4']
partition 2 ['relu_default_7', 'to_dtype_43', 'add_tensor_12', 'mul_tensor_19', 'to_dtype_40', 'mul_tensor_18', 'add_tensor_13']
partition 4 ['to_dtype_39', 'relu_default_6', 'to_dtype_36', 'add_tensor_11', 'mul_tensor_16', 'to_dtype_41', 'mul_tensor_17']
partition 6 ['add_tensor_10', 'to_dtype_35', 'relu_default_5', 'to_dtype_37', 'mul_tensor_15', 'to_dtype_32', 'mul_tensor_14', 'add_tensor_9']
partition 8 ['to_dtype_33', 'mul_tensor_13', 'add_tensor_8', 'to_dtype_31', 'to_dtype_28', 'relu_default_4', 'mul_tensor_12']
partition 10 ['to_dtype_27', 'add_tensor_7', 'mul_tensor_11', 'mul_tensor_10', 'to_dtype_29', 'to_dtype_24']
partition 13 ['log_default_1', 'sum_dim_int_list_1', 'exp_default_1', 'sub_tensor_2', 'to_dtype_23', 'sub_tensor_3']
partition 15 ['sub_tensor_1', 'log_default', 'sum_dim_int_list', 'exp_default', 'sub_tensor', 'to_dtype_21']
partition 17 ['to_dtype_16', 'add_tensor_6', 'relu_default_3', 'to_dtype_19', 'add_tensor_5', 'mul_tensor_9', 'mul_tensor_8']
partition 19 ['mul_tensor_6', 'to_dtype_17', 'mul_tensor_7', 'add_tensor_4', 'to_dtype_12', 'to_dtype_15', 'relu_default_2']
partition 21 ['mul_tensor_5', 'to_dtype_13', 'to_dtype_8', 'add_tensor_2', 'to_dtype_11', 'relu_default_1', 'add_tensor_3', 'mul_tensor_4']
partition 23 ['mul_tensor_2', 'to_dtype_9', 'mul_tensor_3', 'add_tensor_1', 'to_dtype_7', 'to_dtype_4', 'relu_default']
partition 25 ['mul_tensor', 'mul_tensor_1', 'to_dtype', 'add_tensor', 'to_dtype_3', 'to_dtype_5']

**srun: error: a100-st-p4d24xlarge-6: task 0: Segmentation fault (core dumped)**

Workaround: 
Remove "torch.ops.aten.to.dtype" from operator_support list. 

My guess:

Following ref implementation has some issue. 

def aten_to_dtype(self, dtype: torch.dtype, **kwargs):
    if len(kwargs) > 0 or not dtype:
        raise RuntimeError("No support for other to.dtype() formats other than to.dtype(self, dtype)")
    return torch._prims.convert_element_type(self, dtype)

**Comment by SherlockNoMad** [comment]
cc @davidberard98

**Comment by davidberard98** [comment]
It turns out that `aten.to` is CompositeImplicitAutograd... so we probably also need to change aten2aten decompositions so that they use `_to_copy` instead of `to` when casting inputs since we can't register CompositeImplicitAutograd ops in the decomp table.

I think that means that all the aten2aten decompositions will depend on dtypes of inputs (which I assume is okay because dynamo specializes on dtypes I think? cc @ezyang @ngimel @SherlockNoMad to confirm)

**Comment by ezyang** [comment]
dtype specialization is ok

**Comment by ezyang** [comment]
In any case, we shouldn't segfault. Is there a smaller repro, or could you give a gdb backtrace?

**Comment by davidberard98** [comment]
@SherlockNoMad can you provide the commit on which you got this issue? So far I can't repro the segfault.

**Comment by davidberard98** [comment]
Repro is in branch bahuang/repro.

Stacktrace:
```
#0  0x00007fe4b929a14e in std::__atomic_base<unsigned long>::fetch_add (__m=std::memory_order_acq_rel, __i=1, this=0x8)
    at /usr/include/c++/7/bits/atomic_base.h:514
#1  c10::detail::atomic_refcount_increment (refcount=...) at /scratch/dberard/bench-june/pytorch/c10/util/intrusive_ptr.h:199
#2  0x00007fe4b92a6f00 in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::retain_ (this=0x7ffe1c82dad0)
    at /scratch/dberard/bench-june/pytorch/c10/util/intrusive_ptr.h:269
#3  0x00007fe4b92a174c in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::intrusive_ptr (this=0x7ffe1c82dad0, rhs=...)
    at /scratch/dberard/bench-june/pytorch/c10/util/intrusive_ptr.h:356
#4  0x00007fe4b929a261 in at::TensorBase::TensorBase (this=0x7ffe1c82dad0) at /scratch/dberard/bench-june/pytorch/aten/src/ATen/core/TensorBase.h:100
#5  0x00007fe4bc64dec0 in std::pair<torch::jit::fuser::cuda::Val* const, c10::IValue>::pair<at::Tensor&, true> (this=0x560aa06d7a98, __x=
    @0x560aa0622918: 0x560a5b104d90, __y=...) at /usr/include/c++/7/bits/stl_pair.h:326
#6  0x00007fe4bc64d3ae in __gnu_cxx::new_allocator<std::pair<torch::jit::fuser::cuda::Val* const, c10::IValue> >::construct<std::pair<torch::jit::fuser::$
uda::Val* const, c10::IValue>, torch::jit::fuser::cuda::Val* const&, at::Tensor&> (this=0x7ffe1c82dbb7, __p=0x560aa06d7a98)
    at /usr/include/c++/7/ext/new_allocator.h:136
#7  0x00007fe4bc64bd61 in std::allocator_traits<std::allocator<std::pair<torch::jit::fuser::cuda::Val* const, c10::IValue> > >::construct<std::pair<torch$
:jit::fuser::cuda::Val* const, c10::IValue>, torch::jit::fuser::cuda::Val* const&, at::Tensor&> (__a=..., __p=0x560aa06d7a98)
    at /usr/include/c++/7/bits/alloc_traits.h:475
#8  0x00007fe4bc64a074 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<torch::jit::fuser::cuda::Val* const, c10::IV$
lue>, false> > >::_M_allocate_node<torch::jit::fuser::cuda::Val* const&, at::Tensor&> (this=0x560aa00a2c60)
    at /usr/include/c++/7/bits/hashtable_policy.h:2066
#9  0x00007fe4bc6470da in std::_Hashtable<torch::jit::fuser::cuda::Val*, std::pair<torch::jit::fuser::cuda::Val* const, c10::IValue>, std::allocator<std:$
pair<torch::jit::fuser::cuda::Val* const, c10::IValue> >, std::__detail::_Select1st, std::equal_to<torch::jit::fuser::cuda::Val*>, std::hash<torch::jit::$
user::cuda::Val*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable$
traits<false, false, true> >::_M_emplace<torch::jit::fuser::cuda::Val* const&, at::Tensor&> (this=0x560aa00a2c60)
    at /usr/include/c++/7/bits/hashtable.h:1644
#10 0x00007fe4bc643ce6 in std::_Hashtable<torch::jit::fuser::cuda::Val*, std::pair<torch::jit::fuser::cuda::Val* const, c10::IValue>, std::allocator<std:$
pair<torch::jit::fuser::cuda::Val* const, c10::IValue> >, std::__detail::_Select1st, std::equal_to<torch::jit::fuser::cuda::Val*>, std::hash<torch::jit::$
user::cuda::Val*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable$
traits<false, false, true> >::emplace<torch::jit::fuser::cuda::Val* const&, at::Tensor&> (this=0x560aa00a2c60) at /usr/include/c++/7/bits/hashtable.h:736
#11 0x00007fe4bc64075c in std::unordered_map<torch::jit::fuser::cuda::Val*, c10::IValue, std::hash<torch::jit::fuser::cuda::Val*>, std::equal_to<torch::j$
t::fuser::cuda::Val*>, std::allocator<std::pair<torch::jit::fuser::cuda::Val* const, c10::IValue> > >::emplace<torch::jit::fuser::cuda::Val* const&, at::$
ensor&> (this=0x560aa00a2c60) at /usr/include/c++/7/bits/unordered_map.h:387
#12 0x00007fe4bc6396f5 in torch::jit::fuser::cuda::FusionKernelRuntime::runWithInput (this=0x560aa00a2c30, inputs=..., input_id=1)
    at /scratch/dberard/bench-june/pytorch/torch/csrc/jit/codegen/cuda/kernel_cache.cpp:528
#13 0x00007fe4bc636f91 in torch::jit::fuser::cuda::FusionExecutorCache::runFusionWithInputs (this=0x560aa0079e50, inputs=...)
    at /scratch/dberard/bench-june/pytorch/torch/csrc/jit/codegen/cuda/kernel_cache.cpp:185
#14 0x00007fe51364f020 in (anonymous namespace)::PythonFusionOwner::execute (this=0x560aa0079e50, inputs=...)
    at /scratch/dberard/bench-june/pytorch/torch/csrc/jit/codegen/cuda/python_frontend/python_bindings.cpp:29
...
```
