### ISSUE TITLE
torch.utils.bottleneck spams output and crashes

### ISSUE THREAD

**Issue by dan-the-meme-man** [pytorch/pytorch#81026]
### 🐛 Describe the bug

I have a Python script that trains an NN, and am trying to optimize it using bottleneck, but I can't. The command
`python -m torch.utils.bottleneck TA_generator.py` runs through my code about 3 times and then fills the console with spam. It should be noted that `python TA_generator.py` runs without issue:

```import os
from collections import OrderedDict
from copy import deepcopy
from datetime import datetime

import torch
from torch.utils.data import DataLoader, Dataset
from transformers import BertTokenizerFast, BertForPreTraining, BertConfig

# paths
proj_dir = '/scratch/ddegenaro'
def in_proj_dir(dir):
    return os.path.join(proj_dir, dir)
pretraining_test = in_proj_dir('pretraining_test.txt')
pretraining_txt = in_proj_dir('pretraining.txt')
inits = in_proj_dir('inits')
ckpts = in_proj_dir('ckpts')
trained = in_proj_dir('trained')

print('Getting tokenizer.')
# get tokenizer and initialize teacher model mBERT
tokenizer = BertTokenizerFast.from_pretrained("bert-base-multilingual-cased", do_lower_case=False)
print('Done.')
print('Getting mBERT.')
# this line will complain that decoder bias was not in the checkpoint
mBERT = BertForPreTraining.from_pretrained("bert-base-multilingual-cased")
print('Done.')

teacher = mBERT # first network to copy from
MSELoss = torch.nn.MSELoss() # loss between logits of two models
batch_size = 65536 # batch size
epochs = 1 # num epochs - SHOULD BE 32

class BertData(Dataset):
    def __init__(self):
        print('Reading in corpus. Warning: requires ~ 50 GB of RAM.')
        self.corpus = open(pretraining_test).readlines()
        print('Done.')
    def __len__(self):
        return len(self.corpus)
    def __getitem__(self, idx):
      return tokenizer(self.corpus[idx], return_tensors='pt', padding='max_length', truncation=True, max_length=512)

dataset = BertData()

data_loader = DataLoader(dataset, batch_size=batch_size, num_workers=1, pin_memory=True) # should have num_workers=8 or 12

for i in reversed(range(11,12)): # TA builder loop - SHOULD BE 2, 12

  teacher_state_dict = teacher.state_dict()

  # create a BertConfig with a multilingual vocabulary for the next TA
  config_obj = BertConfig(vocab_size=119547, num_hidden_layers=i)

  student = BertForPreTraining(config_obj) # initialize next model and state dict
  student_state_dict = OrderedDict()

  torch.cuda.empty_cache()

  teacher.to('cuda') # use GPU
  student.to('cuda')

  print('Building student.')
  for key in teacher_state_dict: # copy architecture and weights besides top layer
    if str(i) not in key:
      student_state_dict[key] = deepcopy(teacher_state_dict[key])
  print('Done.')

  # save init for this TA
  print('Saving student.')
  torch.save(student_state_dict, os.path.join(inits, 'ta' + str(i)))
  print('Done.')

  # load next state dict into the next model
  student.load_state_dict(student_state_dict)

  student.train() # ensure training mode

  # generate Adam optimizer close to mBERT's
  optimizer = torch.optim.Adam(student.parameters(), lr=(batch_size/256*1e-4),
                             betas=(0.9, 0.999), eps=1e-06, weight_decay=0)

  optimizer.zero_grad(set_to_none=True) # just to be sure

  with torch.set_grad_enabled(True):

    for k in range(epochs):

      start = datetime.now()

      print(f'Begin epoch {k+1}/{epochs}. Current time: {datetime.now()}.')

      loss = 0 # initialize

      for batch_idx, inputs in enumerate(data_loader):

        for j in inputs:
          inputs[j] = inputs[j][0]
        inputs = inputs.to('cuda')

        # get teacher and student predictions
        teacher_logits = teacher(**inputs).prediction_logits
        student_logits = student(**inputs).prediction_logits
        
        # calculate the loss between them and update
        loss = MSELoss(teacher_logits, student_logits) / batch_size
      
        # learning step
        loss.backward()
        optimizer.step()
        optimizer.zero_grad(set_to_none=True)
        loss = 0
        print(batch_idx+1, (datetime.now()-start)/(batch_idx+1))
    
      torch.save(student.state_dict(), os.path.join(ckpts, 'ta' + str(i) + '_ckpt' + str(k)))

  # save trained model for this TA
  torch.save(student.state_dict(), os.path.join(trained, 'ta' + str(i)))

  teacher = student # prepare to initialize next network

# end for
```
`pretraining_test.txt` is simply a text file of 100,000 lines. I would post a stack trace, but the console is filled with spam so quickly that it is impossible to get any Traceback. Attached is a screencap of some spam - it's the same message on repeat.
![spam](https://user-images.githubusercontent.com/45244059/177670524-26fbb6c3-ae35-4283-8d70-db3fae4879cd.jpg)

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-180-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti

Nvidia driver version: 460.106.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0           py310h7f8727e_0
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0
[conda] mkl_random                1.2.2           py310h00e6091_0
[conda] numpy                     1.22.3          py310hfa59a62_0
[conda] numpy-base                1.22.3          py310h9585f30_0
[conda] pytorch                   1.12.0          py3.10_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.0              py310_cu113    pytorch
[conda] torchvision               0.13.0              py310_cu113    pytorch

**Comment by cpuhrsch** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by dan-the-meme-man** [comment]
I'm sorry if this is unclear, but I don't see how this isn't a bug. My script runs fine until I try to profile it using the bottleneck module, then it spams my output. I feel that something is wrong with bottleneck if this is the case.

**Comment by cpuhrsch** [comment]
@dan-the-meme-man - The issue referenced in the output is https://github.com/pytorch/pytorch/issues/6313 . The message suggests to not use this feature in conjunction with DataLoader and `num_workers > 0`. It's not spam output, but useful information that references an existing issue, which is therefore not a bug.
