### ISSUE TITLE
[FSDP] Rename `transformer_auto_wrap_policy()`

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#81050]
Per @rohan-varma's suggestion, we can rename `transformer_auto_wrap_policy()` to reflect that it works for any `layer_classes: Set[Type[nn.Module]]`, not just transformer layer classes.

https://github.com/pytorch/pytorch/blob/c0e15fe3f4d5622c7a687cf0d503902be9296596/torch/distributed/fsdp/wrap.py#L81-L86

https://github.com/pytorch/pytorch/blob/c0e15fe3f4d5622c7a687cf0d503902be9296596/torch/distributed/fsdp/wrap.py#L117-L122

---

We need to be wary of any existing model code assuming this `transformer_auto_wrap_policy()` name. If breaking this backward compatibility, then we may need to deprecate `transformer_auto_wrap_policy()` (e.g. adding a warning) and add a new function with the new name that does the exact same thing.

cc @zhaojuanmao @mrshenli @rohan-varma @ezyang

**Comment by zhaojuanmao** [comment]
transformer_auto_wrap_policy() possibly has already been used for multiple use cases, since we are working on non-recursive wrapping, once it is finalized, we can revisit naming here later on?

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/88450
