### ISSUE TITLE
dynamically change tensor with requires_grad=False by "+=" cause error but "+" doesn't

### ISSUE THREAD

**Issue by wizardk** [pytorch/pytorch#8106]
## Issue description

I'm writing an attention model with history coverage vector.
I got a RuntimeError when I accumulated this history vector with a new vector by using "+=", but "+" is OK.

Error info:
File "...\torch\autograd\__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

## Code example

```
class Attenion(nn.Module):
  def __init__(self):
    self.history = torch.zeros(..., requires_grad=False)
  def forward(self, hidden, x):
    w = ...
    self.history += w.view_as(self.history).detach()  # RuntimeError
    self.history = self.history + w.view_as(self.history).detach()  # OK
```

## System Info
- OS: Windows 10
- PyTorch version: 0.4.0
- Python version: 3.6.4
- CUDA/cuDNN version: 9.1.85, no cuDNN

**Comment by goldsborough** [comment]
`x = x + y` is something very different from `x += y` for Python semantics. The latter creates a new variable, the former modifies the variable in place.

**Comment by wizardk** [comment]
@goldsborough, thanks for your comment.
But I still don't understand it too much.
Even if it's a new variable, this variable's requires_grad is False, right? So why did this error occur?

**Comment by apaszke** [comment]
As @goldsborough mentioned it is expected. You're changing the memory that `self.history` points to, but it is needed to compute gradients later. Use the second line and the error will go away.
