### ISSUE TITLE
Add a check that tutorials are executing on build 

### ISSUE THREAD

**Issue by svekars** [pytorch/pytorch#81067]
### 📚 The doc issue

Copying from [tutorials](https://github.com/pytorch/tutorials/issues/1965) by @b0noI' request.

We want to know if a tutorial is executing while we are building it. For each tutorial, sphinx-gallery prints Total running time ([Example](https://pytorch.org/tutorials/beginner/transformer_tutorial.html) at the bottom of the page). The total running time of 0.00 might mean that the tutorial is failing. If this is the case, we want to be able to catch this while we run [build.sh](https://github.com/pytorch/tutorials/blob/master/.jenkins/build.sh#L65) and put that output to a text file for further investigation.

### Suggest a potential alternative/fix

Add script to [build.sh](https://github.com/pytorch/tutorials/blob/master/.jenkins/build.sh#L65) that check the running time of each tutorial and output the list of files that have time 0.00 to a text file or similar for further investigation.

cc @malfet @seemethere @pytorch/pytorch-dev-infra

**Comment by clee2000** [comment]
closing, as https://github.com/pytorch/tutorials/pull/2031 is merged

opened an issue https://github.com/pytorch/tutorials/issues/2033 for reducing the length of the NOT_RUN list
