### ISSUE TITLE
[ONNX] Support opset 17 operators

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#81075]
Tracking issue on the onnx opset 17 support. Contributions welcome.

- [x] Add version 17 as a known version #83287 
- [ ] fft
  - [ ] ifft
  - [ ] fft_fft
  - [ ] fft_ifft
  - [ ] fft_rfft
  - [ ] fft_irfft
  - [ ] fft_hfft
  - [ ] fft_ihfft
  - [ ] fft_fft2
  - [ ] fft_ifft2
  - [ ] fft_rfft2
  - [ ] fft_irfft2
  - [ ] fft_hfft2
  - [ ] fft_ihfft2
  - [ ] fft_fftn
  - [ ] fft_ifftn
  - [ ] fft_rfftn
  - [ ] fft_irfftn
  - [ ] fft_hfftn
  - [ ] fft_ihfftn
  - [ ] fft_fftfreq
  - [ ] fft_rfftfreq
  - [ ] fft_fftshift
  - [ ] fft_ifftshift
- [x] stft #83944 
- [ ] istft
- [ ] bartlett_window
- [ ] blackman_window
- [ ] hamming_window
- [ ] hann_window
- [ ] kaiser_window
- [x] LayerNormalization #84293

Closes #80834

**Comment by iver56** [comment]
Justin, you listed istft here, but I can't find istft in [ONNX's list of operators](https://github.com/onnx/onnx/blob/main/docs/Operators.md#STFT). Is the idea to implement istft in terms of the available onnx operators?

**Comment by justinchuby** [comment]
Hi @iver56, I can confirm that ISTFT is not in opset 17. However onnx is open to including it as a new op (please feel free to open an issue in the onnx/onnx repo if not already existed). We plan to support exporting istft from pytorch in spite of the missing ISTFI op.

**Comment by stonelazy** [comment]
If I may add, even though ISTFT is not available, both forward and inverse operations for DFT are supported by ONNX. [Reference](https://github.com/onnx/onnx/blob/main/docs/Operators.md#dft) This should help users implement ISTFT on their own.    
Would it be possible to include support for FFT as well ?

**Comment by justinchuby** [comment]
@stonelazy i think so. Do you have a list of related torch functions you think could be fitting?

**Comment by stonelazy** [comment]
> @stonelazy i think so. Do you have a list of related torch functions you think could be fitting?

I hope am not wrong, below are the torch's equivalent in ONNX.  
[Torch's FFT's](https://pytorch.org/docs/stable/generated/torch.fft.fft.html#torch.fft.fft) equivalent is [ONNX's DFT](https://github.com/onnx/onnx/blob/main/docs/Operators.md#dft)
[Torch's IFFT](https://pytorch.org/docs/stable/generated/torch.fft.ifft.html) is same [ONNX's DFT](https://github.com/onnx/onnx/blob/main/docs/Operators.md#dft) but with inverse option selected.
[Torch's Melscale](https://pytorch.org/audio/stable/transforms.html?highlight=melscale#torchaudio.transforms.MelScale) equivalent is [ONNX's Melweight](https://github.com/onnx/onnx/blob/main/docs/Operators.md#melweightmatrix).

**Comment by jonas-doevenspeck** [comment]
SInce LayerNorm is also part of opset 17, does it make sense to include it as well in this list?
https://github.com/onnx/onnx/blob/main/docs/Operators.md#layernormalization

**Comment by FrankFundel** [comment]
Will opset17 be available, only if all operators are implemented?

**Comment by justinchuby** [comment]
opset17 is enabled in torch-nightly. support for new ops will be added gradually.

**Comment by FrankFundel** [comment]
Thanks :) Hoping for stft and window functions to come soon.

**Comment by mravanelli** [comment]
That's a very important feature for [SpeechBrain](https://github.com/speechbrain/speechbrain) as well. The feature extraction part relies on fft/stft and we cannot currently fully export/import it in ONNX (@fpaissan).

**Comment by frankiedrake** [comment]
> opset17 is enabled in torch-nightly. support for new ops will be added gradually.

Hello, I've installed torch from nightly releases (`Version: 1.13.0.dev20220914+cu113`) but I'm still getting an error 
`torch.onnx.errors.UnsupportedOperatorError: Exporting the operator '::stft' to ONNX opset version 17 is not supported`
Is that me isntalled the wrong version or this feature isn't released yet?

**Comment by justinchuby** [comment]
Hi! Even though we can export to the opset17 format, support for stft is not yet added unfortunately.

**Comment by david-macleod** [comment]
Are there any plans to implement fft_fft / fft_rfft or would you accept pull requests?

**Comment by Alexey-Kamenev** [comment]
If you only need an ONNX support for real-valued FFT ops (e.g. `rfft`/`irfft`, `rfft2`/`irfft2` and so on), you can use ONNX Contrib ops, such as [Rfft](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Rfft) and [Irfft](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.irfft). You can take a look at [my project](https://github.com/Alexey-Kamenev/tensorrt-dft-plugins) which provides ONNX export + TensorRT plugins for models using FFT ops. That projects provides only a simple example of how Contrib ops can be used in ONNX export. For a complete implementation, refer to [my code in NVIDIA Modulus](https://github.com/NVIDIA/modulus/blob/main/modulus/models/layers/fft.py) project.

Note that if you plan to use ONNX models with those ops in runtime, you might need to use a custom build of ORT due to the bug in [IRFFT](https://github.com/microsoft/onnxruntime/issues/13236). The alternative is to use TRT plugins, that is, do PyTorch -> ONNX -> TRT conversion (TRT plugins do not use ORT, so are not affected by the bug).

**Comment by sammlapp** [comment]
> If you only need an ONNX support for real-valued FFT ops (e.g. `rfft`/`irfft`, `rfft2`/`irfft2` and so on), you can use ONNX Contrib ops, such as [Rfft](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Rfft) and [Irfft](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.irfft). You can take a look at [my project](https://github.com/Alexey-Kamenev/tensorrt-dft-plugins) which provides ONNX export + TensorRT plugins for models using FFT ops. That projects provides only a simple example of how Contrib ops can be used in ONNX export. For a complete implementation, refer to [my code in NVIDIA Modulus](https://github.com/NVIDIA/modulus/blob/main/modulus/models/layers/fft.py) project.
> 
> Note that if you plan to use ONNX models with those ops in runtime, you might need to use a custom build of ORT due to the bug in [IRFFT](https://github.com/microsoft/onnxruntime/issues/13236). The alternative is to use TRT plugins, that is, do PyTorch -> ONNX -> TRT conversion (TRT plugins do not use ORT, so are not affected by the bug).

@Alexey-Kamenev this sounds like it could potentially be extremely useful, but I don't really understand what I would need to do. For instance, would it be possible to create spectrograms from audio data as the first step in a PyTorch model? If so, could you describe the steps necessary?

**Comment by Alexey-Kamenev** [comment]
@sammlapp
> For instance, could I create a PyTorch model that creates spectrograms from audio, and export this model to ONNX?

Yes, you could do that, if in your PyTorch code you use something like `torch.fft.rfft`.
There is also an example of using ONNX-friendly FFT functions to implement AFNO (Adaptive Fourier Neural Operator): [code](https://github.com/NVIDIA/modulus/blob/main/modulus/models/afno/afno.py#L140), [paper](https://arxiv.org/abs/2111.13587).

> If so, could you describe the steps necessary?

Unfortunately, due to lack of support of complex type in ONNX exporter, the process is not exactly trivial - you would need to use some sort of a wrapper which would use standard PyTorch FFT functions when **not** in ONNX export mode and custom symbolic functions which emit proper ONNX operators (e.g. `Rfft` or `Irfft`) during ONNX export. Also, you would need to change your code to avoid using complex-typed tensors, essentially treating all complex tensors as if after [torch.view_as_real](https://pytorch.org/docs/stable/generated/torch.view_as_real.html).

We already did all of that in Modulus (see the AFNO example I mentioned above), but if you don't want to take the dependency on Modulus, you can implement a simpler version using the code by checking the [tests](https://github.com/Alexey-Kamenev/tensorrt-dft-plugins/blob/main/tests/test_dft.py#L35).

I know, it does not sound particularly simple, but that's the consequence of not having complex type support in ONNX exporter. Otherwise, it would have been as simple as something like calling `register_custom_op_symbolic`.

**Comment by justinchuby** [comment]
More support on the way in our new torch.onnx.dynamo_export exporter. cc @titaiwangms

**Comment by shingjan** [comment]
There is a `aten:l1_loss` not supported error for model `Super_SloMo` in torchbench. Issue reported [here](https://github.com/pytorch/pytorch/issues/100913). Wonder if this op will be supported in the future? Although it is odd that a training-related op is included for inference.

**Comment by justinchuby** [comment]
l1_loss will be supported

**Comment by TechInterMezzo** [comment]
What is the current workaround to export models with mel spectrograms? And is support for stft the only thing that is missing to make it work?

**Comment by justinchuby** [comment]
STFT is supported by the torch.onnx.dynamo_export export API

**Comment by justinchuby** [comment]
It should now be supported by `torch.onnx.dynamo_export`.

**Comment by sammlapp** [comment]
@justinchuby does this mean that there's now a simpler method for exporting pytorch models containing fft than the approach described by @Alexey-Kamenev above? Or is that approach still required? 
Thanks

**Comment by justinchuby** [comment]
Yes. The new `torch.onnx.dynamo_export` should allow a simpler experience for exporter FFT operators. The approach described by @Alexey-Kamenev will be required for the `torch.onnx.export` API.

**Comment by shanecarroll-smarsh** [comment]
Can anyone produce a working example where `torch.onnx.dynamo_export` successfully exports a `torch.stft` op?

Here is a simple MWE, with a setup common to audio signal processing models:

```python
import torch


class STFTModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self._window = torch.hann_window(window_length=320)

    def forward(self, signals: torch.Tensor) -> torch.Tensor:
        x = signals.stft(
            n_fft=512,
            hop_length=160,
            win_length=320,
            return_complex=True,  # doesn't affect errors
            window=self._window,
            pad_mode="constant",  # aten.reflection_pad1d unsupported op
        )
        return x


m = STFTModel()

# Shape [B, T] audio signals
input_signals = torch.randn([2, 16000])

args = (input_signals,)
export_options = torch.onnx.ExportOptions(dynamic_shapes=True)
torch.onnx.dynamo_export(
    m,
    *args,
    export_options=export_options,
)
```

Here are the short versions of error messages:

Without dynamic shapes (not useful to anyone using `stft`):

```text
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten.transpose.int']}. 
```

With dynamic shapes (as the example shows):

```text
torch._dynamo.exc.Unsupported: unsupported operator: aten._fft_r2c.default
```

Exporting within the context of `torch.inference_mode()`, output is slightly different (`prims` vs. `aten`): 

```text
torch._dynamo.exc.Unsupported: unsupported operator: prims.fft_r2c.default
```

**Comment by justinchuby** [comment]
> Can anyone produce a working example where `torch.onnx.dynamo_export` successfully exports a `torch.stft` op?
> 
> Here is a simple MWE, with a setup common to audio signal processing models:
> 
> ```python
> import torch
> 
> 
> class STFTModel(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self._window = torch.hann_window(window_length=320)
> 
>     def forward(self, signals: torch.Tensor) -> torch.Tensor:
>         x = signals.stft(
>             n_fft=512,
>             hop_length=160,
>             win_length=320,
>             return_complex=True,  # doesn't affect errors
>             window=self._window,
>             pad_mode="constant",  # aten.reflection_pad1d unsupported op
>         )
>         return x
> 
> 
> m = STFTModel()
> 
> # Shape [B, T] audio signals
> input_signals = torch.randn([2, 16000])
> 
> args = (input_signals,)
> export_options = torch.onnx.ExportOptions(dynamic_shapes=True)
> torch.onnx.dynamo_export(
>     m,
>     *args,
>     export_options=export_options,
> )
> ```
> 
> Here are the short versions of error messages:
> 
> Without dynamic shapes (not useful to anyone using `stft`):
> 
> ```
> torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten.transpose.int']}. 
> ```
> 
> With dynamic shapes (as the example shows):
> 
> ```
> torch._dynamo.exc.Unsupported: unsupported operator: aten._fft_r2c.default
> ```
> 
> Exporting within the context of `torch.inference_mode()`, output is slightly different (`prims` vs. `aten`):
> 
> ```
> torch._dynamo.exc.Unsupported: unsupported operator: prims.fft_r2c.default
> ```

Thanks for sharing the info. I will reproduce this and get back to you.

**Comment by justinchuby** [comment]
@titaiwangms Turns out transpose.int was not matched when the input is complex. Would it make sense for us to fall back onto the non-complex-specific implementations when we don't have complex functions?

**Comment by justinchuby** [comment]
We will continue in https://github.com/pytorch/pytorch/issues/113067 @shanecarroll-smarsh

**Comment by biendltb** [comment]
While waiting for ONNX to support `torch.istft()`, this implementation of ISTFT could be used as a workaround: https://github.com/biendltb/torch-istft-onnx

**Comment by jie-chen** [comment]
It seems the output of onnx stft is different from torch.stft . any workaround?
