### ISSUE TITLE
Sometimes the torch.save method does not work properly.

### ISSUE THREAD

**Issue by MakeDirtyCode** [pytorch/pytorch#8109]
## Issue description
When indexing a part of the tensor, the entire original tensor is saved.

## Code example

```
import torch
origin = torch.FloatTensor(128, 512, 7, 7) # original tensor (shape: [128, 512, 7, 7])
indexed = origin[0] # part of tensor (shape: [512, 7, 7])
torch.save(indexed, 'tensor.pth') # save tensor
```

I expect that divided tensors will be stored. (It will be about 100KB)
However, it is actually stored in the original matrix size. (Approximately 12MB)

## System Info

PyTorch
conda
Windows 10
0.4.0
Python 3.6
CUDA 9.0
Nvidia Geforce 1070

**Comment by apaszke** [comment]
A simple workaround would be to do `.clone()` before saving, to make sure the view doesn't share memory with the original tensor (which is what causes `torch.save` to dump the whole block).

**Comment by soumith** [comment]
this is expected behavior, so I'm closing the issue. (Adam's workaround in the comment above is sufficient for you to workaround)

If you are saving multiple views onto a larger Tensor, we want to make sure that the sharing is preserved when loading back, so the Tensor's backing storage is saved.
