### ISSUE TITLE
LayerNorm got wrong answer

### ISSUE THREAD

**Issue by jinmingyi1998** [pytorch/pytorch#81090]
### 🐛 Describe the bug

I want to implement a Inplace LayerNorm to save GPU memory.

When I check the result, I found that pytorch output a unexpected result.

```python
def torch_impl_layernorm(x):
    m = nn.LayerNorm(x.shape[-1], elementwise_affine=False)
    return m(x)


def my_impl_layernorm(x):
    v = x.var(dim=-1, unbiased=False, keepdim=True)
    e = x.mean(dim=-1, keepdim=True)
    v = v + 1e-5  # same epsilon as torch default
    v = v.sqrt()
    out = (x - e) / v
    return out

H = 2000
W = 100
n_channel = 32
a = torch.arange(H * W * n_channel).reshape((H, W, n_channel)).float()
b = my_impl_layernorm(a)
c = torch_impl_layernorm(a)
print((c - b).abs().mean()) #  output: tensor(1996.2400)
print(c)
```
## output:
tensor([[[-1.6787e+00, -1.5704e+00, -1.4621e+00,  ...,  1.4621e+00,
           1.5704e+00,  1.6787e+00],
         [-1.6787e+00, -1.5704e+00, -1.4621e+00,  ...,  1.4621e+00,
           1.5704e+00,  1.6787e+00],
         [-1.6787e+00, -1.5704e+00, -1.4621e+00,  ...,  1.4621e+00,
           1.5704e+00,  1.6787e+00],
         ...,
         [-1.6812e+00, -1.5728e+00, -1.4643e+00,  ...,  1.4643e+00,
           1.5727e+00,  1.6812e+00],
         [-1.6812e+00, -1.5728e+00, -1.4643e+00,  ...,  1.4643e+00,
           1.5727e+00,  1.6812e+00],
         [-1.6812e+00, -1.5728e+00, -1.4643e+00,  ...,  1.4643e+00,
           1.5727e+00,  1.6812e+00]],

        [[-1.6812e+00, -1.5728e+00, -1.4643e+00,  ...,  1.4643e+00,
           1.5727e+00,  1.6812e+00],
         [-1.6812e+00, -1.5727e+00, -1.4643e+00,  ...,  1.4643e+00,
           1.5727e+00,  1.6812e+00],
         [-1.6812e+00, -1.5727e+00, -1.4643e+00,  ...,  1.4643e+00,
           1.5727e+00,  1.6812e+00],
         ...,
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00]],

        [[-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         ...,
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00],
         [-1.6523e+00, -1.5457e+00, -1.4391e+00,  ...,  1.4391e+00,
           1.5457e+00,  1.6523e+00]],

        ...,

        [[-7.5684e-03, -7.0801e-03, -6.5918e-03,  ...,  6.5918e-03,
           7.0801e-03,  7.5684e-03],
         [-4.8469e+03, -4.5307e+03, -4.2145e+03,  ...,  4.3237e+03,
           4.6399e+03,  4.9561e+03],
         [-4.8396e+03, -4.5234e+03, -4.2072e+03,  ...,  4.3310e+03,
           4.6472e+03,  4.9634e+03],
         ...,
         [-4.9152e+03, -4.5990e+03, -4.2827e+03,  ...,  4.2554e+03,
           4.5717e+03,  4.8879e+03],
         [-4.9079e+03, -4.5917e+03, -4.2754e+03,  ...,  4.2627e+03,
           4.5789e+03,  4.8952e+03],
         [-4.9006e+03, -4.5844e+03, -4.2681e+03,  ...,  4.2700e+03,
           4.5862e+03,  4.9025e+03]],

        [[-4.8933e+03, -4.5771e+03, -4.2609e+03,  ...,  4.2773e+03,
           4.5935e+03,  4.9097e+03],
         [-4.8860e+03, -4.5698e+03, -4.2536e+03,  ...,  4.2846e+03,
           4.6008e+03,  4.9170e+03],
         [-4.8787e+03, -4.5625e+03, -4.2463e+03,  ...,  4.2919e+03,
           4.6081e+03,  4.9243e+03],
         ...,
         [-4.9543e+03, -4.6380e+03, -4.3218e+03,  ...,  4.2163e+03,
           4.5326e+03,  4.8488e+03],
         [-4.9470e+03, -4.6308e+03, -4.3145e+03,  ...,  4.2236e+03,
           4.5398e+03,  4.8561e+03],
         [-7.5684e-03, -7.0801e-03, -6.5918e-03,  ...,  6.5918e-03,
           7.0801e-03,  7.5684e-03]],

        [[-4.9324e+03, -4.6162e+03, -4.3000e+03,  ...,  4.2382e+03,
           4.5544e+03,  4.8707e+03],
         [-4.9251e+03, -4.6089e+03, -4.2927e+03,  ...,  4.2455e+03,
           4.5617e+03,  4.8779e+03],
         [-4.9178e+03, -4.6016e+03, -4.2854e+03,  ...,  4.2528e+03,
           4.5690e+03,  4.8852e+03],
         ...,
         [-4.8654e+03, -4.5491e+03, -4.2329e+03,  ...,  4.3052e+03,
           4.6215e+03,  4.9377e+03],
         [-4.8581e+03, -4.5419e+03, -4.2256e+03,  ...,  4.3125e+03,
           4.6288e+03,  4.9450e+03],
         [-4.8508e+03, -4.5346e+03, -4.2183e+03,  ...,  4.3198e+03,
           4.6360e+03,  4.9523e+03]]])

In my opinion, the input is from 1...31 ,32...63 ... . After Layer Norm on the last dim, it all dim should be the same as -1.6787e+00, -1.5704e+00, -1.4621e+00,  ...,  1.4621e+00,
           1.5704e+00,  1.6787e+00]. But the result is increasing.

### Versions

Collecting environment information...
PyTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-51-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090
GPU 5: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] make-torch-inplace==1.3
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] torch==1.9.1
[conda] blas                      2.113                       mkl    conda-forge
[conda] blas-devel                3.9.0            13_linux64_mkl    conda-forge
[conda] cudatoolkit               11.1.1              ha002fc5_10    conda-forge
[conda] libblas                   3.9.0            13_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            13_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            13_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            13_linux64_mkl    conda-forge
[conda] make-torch-inplace        1.3                      pypi_0    pypi
[conda] mkl                       2022.0.1           h8d4b97c_803    conda-forge
[conda] mkl-devel                 2022.0.1           ha770c72_804    conda-forge
[conda] mkl-include               2022.0.1           h8d4b97c_803    conda-forge
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] pytorch                   1.9.1           py3.9_cuda11.1_cudnn8.0.5_0    pytorch

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by jinmingyi1998** [comment]
I tried to find something in the paper and source c kernel code, but still no idea

**Comment by ngimel** [comment]
Can't repro on master

**Comment by cpuhrsch** [comment]
@jinmingyi1998 - please try again on a recent version of PyTorch.

**Comment by jinmingyi1998** [comment]
repro in pytorch 1.9.1 . And After 1.10 seems fixed it
