### ISSUE TITLE
Update Docker image base OS from ubuntu 18.04 to 20.04

### ISSUE THREAD

**Issue by ydaiming** [pytorch/pytorch#81120]
### 🚀 The feature, motivation and pitch

The ubuntu 18.04 LTS will [expire its "standard support" lifecycle in 2023/04, and enter Extended Security Maintenance (ESM)](https://ubuntu.com/about/release-cycle). Considering the event is pending in less than a year, when will the PyTorch community update the base system to maybe 20.04 or 22.04?
https://github.com/pytorch/pytorch/blob/4c57cf9a8b40dd47f5d0a21c663c873939e23b5b/Dockerfile#L10

**Comment by mattpopovich** [comment]
Still on Ubuntu 18.04.6 in PyTorch 1.13.1 released in December 2022...

**Comment by malfet** [comment]
I should have commented on that one earlier, but I would gladly review PR that updates base image version
