### ISSUE TITLE
ONNX tests fail after torchvision update

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#81121]
### 🐛 Describe the bug

Namely:
- [ ] test_roi_align
- [ ] test_roi_align_aligned
- [ ] test_roi_pool
- [ ] test_batched_nms

See https://github.com/pytorch/pytorch/runs/7246773625?check_suite_focus=true

### Versions

CI

**Comment by BowenBao** [comment]
Can be closed with #86168, #86169 and pytorch/vision#6685

**Comment by BowenBao** [comment]
Reopen since not all PRs are merged ...

**Comment by datumbox** [comment]
Sorry, the issue got auto-closed due to the merge. Could you confirm that after merging these PRs, they will be cherrypicked into the release branch of PyTorch Core? Thanks!

**Comment by BowenBao** [comment]
All PRs are merged in pytorch master. https://github.com/pytorch/pytorch/pull/86168 is cherry-picked into pytorch 1.13 release. Closing.
