### ISSUE TITLE
Transforms rotate doesn't work on 5D tensor

### ISSUE THREAD

**Issue by longyuxi** [pytorch/pytorch#81132]
### 🐛 Describe the bug

Hi, torch seems to run into an exception when I run `torchvision.transforms.functional.rotate` on a 5D tensor.
```
>>> import numpy as np
>>> import torch
>>> from torchvision import transforms
>>> a = np.random.randint(1, size=(2, 2, 3, 4, 4))
>>> b = torch.tensor(a)
>>> transforms.functional.rotate(b, 90)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/mskmind_ess/longy/miniconda3/envs/msk/lib/python3.9/site-packages/torchvision/transforms/functional.py", line 1078, in rotate
    return F_t.rotate(img, matrix=matrix, interpolation=interpolation.value, expand=expand, fill=fill)
  File "/gpfs/mskmind_ess/longy/miniconda3/envs/msk/lib/python3.9/site-packages/torchvision/transforms/functional_tensor.py", line 686, in rotate
    return _apply_grid_transform(img, grid, interpolation, fill=fill)
  File "/gpfs/mskmind_ess/longy/miniconda3/envs/msk/lib/python3.9/site-packages/torchvision/transforms/functional_tensor.py", line 586, in _apply_grid_transform
    img = grid_sample(img, grid, mode=mode, padding_mode="zeros", align_corners=False)
  File "/gpfs/mskmind_ess/longy/miniconda3/envs/msk/lib/python3.9/site-packages/torch/nn/functional.py", line 4201, in grid_sample
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)
RuntimeError: grid_sampler(): expected 4D or 5D input and grid with same number of dimensions, but got input with sizes [2, 2, 3, 4, 4] and grid with sizes [2, 4, 4, 2]
```
While this (doing for a 4D tensor)
```
>>> transforms.functional.rotate(b[:, 1, :, :, :], 90)
```
works.

### Versions

Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.53.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB

Nvidia driver version: 455.45.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.961
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pylsp-mypy==0.5.8
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchinfo==1.7.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.22.3           py39he7a7128_0  
[conda] numpy-base                1.22.3           py39hf524024_0  
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchinfo                 1.7.0                    pypi_0    pypi
[conda] torchvision               0.12.0               py39_cu113    pytorch

**Comment by cpuhrsch** [comment]
Hello @longyuxi - please open this issue over at [pytorch/vision](https://github.com/pytorch/vision). Thank you!

**Comment by longyuxi** [comment]
Got it, thank you!

I actually found the [same issue](https://github.com/pytorch/vision/issues/6008) at [pytorch/vision](https://github.com/pytorch/vision). Marking this issue here in case anyone else runs into the same problem.
