### ISSUE TITLE
Concurrency limits for `ciflow/` triggered jobs are set incorrectly

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#81148]
### 🐛 Describe the bug

Our concurrently limit for `ciflow/` triggered jobs would never be cancelled, because they are always running on different commit hashes, see
https://github.com/pytorch/pytorch/blob/0d124fc6961f5b39f1a46722dab2d88f23686783/.github/workflows/trunk.yml#L15

### Versions

CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment]
oh my

**Comment by suo** [comment]
I can look into fixing this if you haven't yet

**Comment by malfet** [comment]
I have a PR

**Comment by malfet** [comment]
Hattip to @ZainRizvi  for bringing this issue to my attention
