### ISSUE TITLE
NCCL backend hangs at initialization

### ISSUE THREAD

**Issue by VanDavv** [pytorch/pytorch#8115]
## Issue description

I'm pretty new to pytorch and I may lack some of the understanding of PyTorch concepts. 
I try to launch distributed learning on 4 GPUs connected with NV-Link, so NCCL seemed the best backend. However, after `init_process_group`, process hangs up with no response or error. The same thing happens for gloo backend.
## Code example
```
import torch 
import multiprocessing as mp
try:
    mp.set_start_method('spawn') # spawn, forkserver, and fork
except RuntimeError:
    pass

torch.distributed.init_process_group(backend='nccl', world_size=2, init_method='tcp://224.66.41.62:23456')
```

## System Info
PyTorch version: 0.4.0a0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 384.125
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2

Versions of relevant libraries:
[pip] msgpack-numpy (0.4.1)
[pip] numpy (1.14.2)
[pip] torch (0.4.0a0)
[pip] torchtext (0.2.1)
[pip] torchvision (0.2.0)
[conda] Could not collect

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by dashesy** [comment]
Can you set `NCCL_DEBUG=INFO` and see if you get where NCCL hangs, and if it uses P2P correctly. Also, what GPU models do you have? Can you also check if you have IOMMU in dmesg?

**Comment by VanDavv** [comment]
@dashesy NCCL_DEBUG=INFO also hangs leaving no info.

As you can see, I have 4 NVIDIA Tesla V100

I have no IOMMU in dmesg

**Comment by dashesy** [comment]
What init_method do you use? I have seen `file://` hangs, try `tcp://master_ip:some_port` if that is the case.

**Comment by richielo** [comment]
I am having the same issue. It hangs at initialisation without any error message. Have you solved it @VanDavv ? Thanks a lot

**Comment by VanDavv** [comment]
@richielo no, I haven't. Still awaiting for some feedback or clues

**Comment by dashesy** [comment]
@VanDavv have you checked [this](https://github.com/pytorch/pytorch/issues/1637#issuecomment-338268158) too? to check if it is [ACS-relatd](https://devtalk.nvidia.com/default/topic/883054/multi-gpu-peer-to-peer-access-failing-on-tesla-k80-/?offset=26)? I have seen it could be P2P related, in which case I was able to use 1 process per 1 GPU and NCCL worked (using IPC)

**Comment by VanDavv** [comment]
@alchemi5t unfortunatelly not, I'm not using pytorch currently so I left this issue unresolved on my side

**Comment by ezyang** [comment]
This will be difficult for us to work on until someone on our side can repro it.

**Comment by alchemi5t** [comment]
I installed and used nvidia apex(apex.parallel.multiproc) to fix this issue.

**Comment by pietern** [comment]
It is likely the original issue posted when we were still using THD and a lot has changed in the mean time.

If you're experiencing the same issue, please feel free to open a new issue and include as many details about your environment you can share.
