### ISSUE TITLE
land validation merged PR even though some trunk jobs failed

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#81152]
Here: https://github.com/pytorch/pytorch/pull/81119

the merge was successful, even though https://hud.pytorch.org/pytorch/pytorch/commit/6882717f73deffb692219ccd1fd6db258d8ed684 reported some errors on trunk

Looking through the code—are we properly retrieving all checks (e.g. getting all result pages?)

**Comment by zengk95** [comment]
Thanks for the report. Currently converting it to the graphql version so this should hopefully be fixed with that.
