### ISSUE TITLE
Numpy API: concatenate()

### ISSUE THREAD

**Issue by danijar** [pytorch/pytorch#81161]
### 🚀 The feature, motivation and pitch

There is already cat() and concat(), but PyTorch is still missing concatenate() to improve [compatibility](https://github.com/pytorch/pytorch/issues/38349) with the Numpy API.

cc @mruberry @rgommers

**Comment by rgommers** [comment]
FYI `numpy` should be adding `concat` at some point (probably by the end of the year) for array API standard compatibility. That doesn't mean that we shouldn't add `concatenate` in PyTorch, but it helps.

**Comment by vitrioil** [comment]
Just to confirm `torch.concatenate` would be an alias like `torch.concat`?
```python
concat(...)
    concat(tensors, dim=0, *, out=None) -> Tensor
    
    Alias of :func:`torch.cat`.
```

**Comment by danijar** [comment]
Basically an alias with renamed arguments. This is the Numpy API:

```
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
```

I think the casting argument can be ignored for now.

**Comment by danijar** [comment]
Thanks, @khushi-411!
