### ISSUE TITLE
[MPS] Gardening spelling

### ISSUE THREAD

**Issue by philipturner** [pytorch/pytorch#81184]
I was looking through PyTorch's memory allocator while trying to reimplement their design in [another project](https://github.com/philipturner/metal-experiment-1), and came across a minor typo. It should be `storage`, not `storge`.

https://github.com/pytorch/pytorch/blob/3c2199b159b6ec57af3f7ea22d61ace9ce5cf5bc/aten/src/ATen/mps/MPSAllocator.mm#L339

Instead of a PR, this should be kept as an issue right now. I often look through code bases, then catch small typos like this. I did so twice with [pytorch/xla](https://github.com/pytorch/xla/pulls?q=author%3Aphilipturner), but decided to not report any more typos after that. It would be better to wait a few weeks, see all the minor grammatical errors spotted, then make one PR. That would save people's time, as opposed to making a PR for every typo separately.

> CC edit made by the PyTorch bot:

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
Sounds good @philipturner. let us know when you are ready with PR.

**Comment by philipturner** [comment]
It’s been long enough; let’s fix that typo. But keep the thread open so I can track more typos in the future.
