### ISSUE TITLE
Please validate PyTorch converter with ORT 1.12 release candidate.

### ISSUE THREAD

**Issue by fatcat-z** [pytorch/pytorch#81194]
Please help us test ONNXRuntime 1.12.0 by running your tests with it installed.

Python (CPU)
https://test.pypi.org/project/ort-nightly/1.12.0.dev20220707003/

Python (GPU)
https://test.pypi.org/project/ort-nightly-gpu/1.12.0.dev20220707003/

**Comment by BowenBao** [comment]
validating via #81147
