### ISSUE TITLE
Support indexing with sequences

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#812]
Sequences just need to be converted into LongTensors. Example:
```python
x[[0, 3, 5], [2, 4, 8]]
```

**Comment by qipeng** [comment]
It would be great if this worked with `Variable` tensors and indices too.

My make-shift code for doing this right now is
```
def embedding_lookup(embeddings, indices):
     return embeddings.index_select(0, indices.view(-1)).view(*(indices.size() + embeddings.size()[1:]))
```
Hopefully this is helpful!

**Comment by zou3519** [comment]
Both tensors and Variables can be indexed with sequences on master (looks like advanced indexing implemented this behavior)
