### ISSUE TITLE
MPS-Ready, ARM64 Docker Image

### ISSUE THREAD

**Issue by MBAnslow** [pytorch/pytorch#81224]
### 🚀 The feature, motivation and pitch

It'd be very helpful to release an ARM64 pytorch docker image for running pytorch models with docker on M1 chips natively using the MPS backend.

I test and debug prototypes based on pytorch locally during development. This was totally manageable using previous intel-based macs, but now that my pytorch docker images are running in AMD64 emulation mode, it's so slow that I can't even debug and test my prototypes locally anymore.

I have tried out using the MPS backend in a virtual environment outside of docker and it's impressively fast! It's actually fast enough to plausibly run prototypes locally for demo purposes and massively speed up testing without throttling the model inference computations which is a real game changer. However, this isn't implemented in an official pytorch image yet. It'd be really great if it were.

cc @malfet @albanD @kulinseth

**Comment by mpurnyn** [comment]
Are you able to get pip to find torch in a docker container?

I have been experiencing issues with getting python3.7 pip and m1 docker to play nicely together. I keep getting this error message "Could not find a version that satisfies the requirement torch==1.4.0"

I was able to install pytorch outside of the container, however.

**Comment by kulinseth** [comment]
Thanks @MBAnslow for starting this thread. 

```
but now that my pytorch docker images are running in AMD64 emulation mode, it's so slow that I can't even debug and test my prototypes locally anymore.
```
I am not too familiar with the Docker workflow. Can you please provide more details about what your setup is and what is needed to provide PyTorch docker image ?

https://docs.docker.com/desktop/mac/apple-silicon/
These docker builds go through emulation or there is native support available?

**Comment by avril-affine** [comment]
I am experiencing the same issue. Currently, it looks like there are only linux/amd64 images on the [pytorch dockerhub](https://hub.docker.com/r/pytorch/pytorch). To get this to run on Mac M1, I need to use the `--platform linux/amd64` to force AMD64 emulation. I think the solution would be to also build and publish a linux/arm64 image to dockerhub. There is also the option of a [multiarch image](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) which docker seems to expect everyone to transition to.

  > In summary, running Intel-based containers on Arm-based machines should be regarded as “best effort” only. We recommend running arm64 containers on Apple silicon machines whenever possible, and encouraging container authors to produce arm64, or multi-arch, versions of their containers. We expect this issue to become less common over time, as more and more images are rebuilt [supporting multiple architectures](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/).

From https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

**Comment by xstast24** [comment]
I believe this issue combines 2 steps, which are currently missing in pytorch, but are really needed:

1. Make pytorch docker images multiarch - this is crucial and needed for anything that builds on top of pytorch images (many apps). Requested here https://github.com/pytorch/pytorch/issues/80764
2. Support Apple's MPS (Apple GPUs) in pytorch docker image. Image is based on ubuntu, so currently MPS is not supported there (at least I was not able to make it work), as the official pytorch guide says "MPS is supported only on latest Mac OS". So even if the latest Mac OS is hosting the pytorch docker image, the image itself can't use the power of Apple chips.

Both are very important because Apple is not selling Intel CPUs anymore, they were replaced with Apple arm chips --> Docker pytorch images (and their derivatives) on Mac are extremely slow (practically unusable), because it has to emulate amd64 architecture on arm64 + it can't use the GPU cores (via MPS).

**Comment by philipturner** [comment]
GPUs other than Nvidia GPUs are not supported in Docker, not even through OpenCL. [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) is all we have regarding GPUs in Docker. There is of course ROCm support, but that's only for AMD's Frontier supercomputer and extremely expensive accelerators. Perhaps you could set up a macOS virtual machine capable of running Metal with some other kind of software?

**Comment by malfet** [comment]
Hmm, I understand the need to regular  linux-arm64 docker, but I'm quite confused how it can be integrated with MPS, which is a feature of Mac OS.

**Comment by GoingMyWay** [comment]
See this for arm: https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/aarch64-docker-images-for-tensorflow-and-pytorch and https://hub.docker.com/r/armswdev/pytorch-arm-neoverse/tags

**Comment by johnnynunez** [comment]
any updates?

**Comment by malfet** [comment]
MPS (Metal Performance Shaders) is MacOS specific feature and as such not available on Linux-ARM64 (even if runs on Apple Silicon) 

Closing the issue for now, but please do not hesitate to file a new one, once MPS support on Linux would become available.

P.S. Please note, that Linux/aarch64 docker images with PyTorch are available, but those are good only for CPU workflows.

**Comment by seanreynoldscs** [comment]
https://rosenzweig.io/blog/first-conformant-m1-gpu-driver.html
There are now MPS drivers for Asahi Linux

**Comment by AIWintermuteAI** [comment]
Following.
_(yes, I know there is a button to Subscribe to the Issue, but I also want to show there is still interest in making Pytorch GPU in Docker for M1 work)._

**Comment by dstepan133** [comment]
It is now July 2024 ...and the M4 is around the corner. Can we ever hope to get the ARM64 pytorch docker image for running pytorch models with docker on Mx chips natively using the MPS backend? Is Apple or anybody else doing anything about it ?

**Comment by johnnynunez** [comment]
> It is now July 2024 ...and the M4 is around the corner. Can we ever hope to get the ARM64 pytorch docker image for running pytorch models with docker on Mx chips natively using the MPS backend? Is Apple or anybody else doing anything about it ?

it not depends from pytorch, only if apple provides apple silicon images

**Comment by rjurney** [comment]
Docker doesn't support MPS. It is not a question of an image. They're an NVIDIA aligned technology. Docker does not want to support your Apple GPU.

**Comment by greatvivek11** [comment]
> Docker doesn't support MPS. It is not a question of an image. They're an NVIDIA aligned technology. Docker does not want to support your Apple GPU.

Could 'Podman' be the answer here? Did anyone try using podman if Docker is where the issue lies? Honestly, I've no clue how all this virtualisation stuff works. Apple truly locked us in a garden here. smh

**Comment by anishjain123** [comment]
Anybody find any workarounds or other ways to run pytorch on M+ mac in a containerized way? @greatvivek11 @rjurney @dstepan133 @AIWintermuteAI @seanreynoldscs @johnnynunez @MBAnslow @avril-affine 

id rather not have to use CoreML but i might not have any other choice

**Comment by joselael** [comment]
🤔

**Comment by streamnsight** [comment]
Docker is based on Linux technology (containers). It runs on a linux VM on macos and Windows. 
Nvidia GPU runs on Linux, they have linux drivers. That's how they can run in Docker containers. 

However MPS is an Apple specific hardware; until somehow someone develops MPS drivers for linux, it's not possible to access the MPS hardware in Docker.

Now, considering Apple runs on macos (derived from BSD), and are not very likely to expose their code, we can only hope Apple sees the need of developers using Docker to use MPS inside it and decide to do it for all of us... 

Fingers crossed.
