### ISSUE TITLE
Guard against reused generators passed to test instantiation decorators

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#81234]
Code like this:

```
ref_ops_names = itertools.chain.from_iterable(
        [f"{path}.{op}" for op in module_all] for path, module_all in module_alls)

...

@parametrize("op", ref_ops_names)
    def test_refs_are_in_python_ref_db(self, op):
        if op in self.skip_ref_ops:
            raise unittest.SkipTest(f"{op} does not have an entry in python_ref_db")
        self.assertIn(op, self.ref_db_names)

@parametrize("op", ref_ops_names)
def test_refs_are_in_decomp_table(self, op):
```

is incorrect because the generator `ref_ops_names` is exhausted by the `@parametrize` decorator, so only one of these tests can be generated properly using it. We should add a test to ensure that generators aren't passed to decorators like `@parametrize` and `@ops`. 

cc @mruberry @jbschlosser

**Comment by vitrioil** [comment]
I want to contribute.

> We should add a test to ensure that generators aren't passed to decorators

1. So when you say `add a test`, do you mean unit test for `parametrize` or a check inside `parametrize` against generator type?
2. Should the existing test (which uses `@parametrize`) convert these generators to lists / iterable and use them?

**Comment by vitrioil** [comment]
Created draft PR #81263 for now.
Will update tests and other changes as well.

**Comment by jbschlosser** [comment]
I'm not sure I agree that the right solution here is to disallow generator usage with `@parametrize` entirely. It's a nice UX to support something like `@parametrize("x", range(5))` and it works as long as you're not reusing a generator, which is always an invalid thing to do.

As an alternative solution, we could catch instances of accidentally reused generators by throwing an error if the iterable is found to be empty at test parametrization time. I don't think it hurts us to add a restriction that `@parametrize` operates over a non-empty set. The error message could hint at checking for reused generators.

**Comment by vitrioil** [comment]
@jbschlosser - Okay, makes sense. I guess we could do something like this then for `parametrize` and `ops`:

```python3
for values in self.arg_values:
    ...
else:
    raise ValueError('Check the parameter passed to parametrize are exhausted')
```

- This will not require existing test case changes for `@ops(filter... / @parametrize(filter...`
- It will allow generator if used only once
- Error will be raised when iterables are reused if they are exhausted (for loop won't execute)


What do you think?
