### ISSUE TITLE
Typo in event_shape of TransformedDistribution?

### ISSUE THREAD

**Issue by johannespitz** [pytorch/pytorch#81254]
https://github.com/pytorch/pytorch/blob/0f37d34815fb43db689c3884b49e7dae16a26963/torch/distributions/transformed_distribution.py#L75

I believe there is a bug in the event_shape/batch_shape-"math" of the TransformedDistribution. The line linked above should probably say:
```
        event_dim = transform.codomain.event_dim + max(domain_event_dim - base_event_dim, 0)
```
or rather:
```
        event_dim = transform.codomain.event_dim + max(reinterpreted_batch_ndims, 0)
```

And I can't imagine how `reinterpreted_batch_ndims > 0` would make sense at all. Therefore, I would propose to throw an error in that case. (Then we wouldn't need the `max()` anymore.)

Or am I completely wrong here?  

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by fritzo** [comment]
:+1: Yes, I think you're right.  An equivalent expression to yours is:
```py
transform_change_in_event_dim = transform.codomain.event_dim - transform.domain.event_dim
event_dim = max(
    transform.codomain.event_dim,  # the transform is coupled
    base_dist.event_dim + transform_change_in_event_dim  # the base dist is coupled
)
```

**Comment by johannespitz** [comment]
Oh, so after thinking this through one more time, I am now convinced that the current implementation is correct. Also your snippet (@fritzo) is actually equivalent to that one, and only my suggestion is wrong :)
The reason I came across this is that I was working with a `Transform` that didn't specify the correct `codomain`.

Short explanation:
```
transform_change_in_event_dim = transform.codomain.event_dim - transform.domain.event_dim
event_dim = base_event_dim + transform_change_in_event_dim
```
is the same as 
```
event_dim = transform.codomain.event_dim + base_event_dim - transform.domain.event_dim
```
And we always want `event_dim >= transform.codomain.event_dim`

Feel free to close this issue, if you agree.
