### ISSUE TITLE
Circular import error in torchgen.api.types

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#81294]
### 🐛 Describe the bug

There is a circular import error in `torchgen.api.types`:
* `torchgen.api.types` imports `torchgen.model` imports `torchgen.api.ufunc` imports `torchgen.api.types`
 
The error can be easily reproduced as follows:

```
from torchgen.api.types import Binding
```

Trying to execute that import results in the following errors:

```
$ python3 -c "from torchgen.api.types import Binding"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../pytorch/torchgen/api/types.py", line 1, in <module>
    from torchgen.model import (
  File "/.../pytorch/torchgen/model.py", line 2475, in <module>
    import torchgen.api.ufunc as ufunc
  File "/.../pytorch/torchgen/api/ufunc.py", line 12, in <module>
    from torchgen.api.types import (
ImportError: cannot import name 'ArgName' from partially initialized module 'torchgen.api.types' (most likely due to a circular import) (/.../pytorch/torchgen/api/types.py)
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.19.6
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:53:17)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] numpydoc==1.2
[pip3] torch==1.13.0a0+gitcb5ef13
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-include               2022.0.0           hecd8cb5_105
[conda] mkl-service               2.4.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpydoc                  1.2                pyhd3eb1b0_0
[conda] torch                     1.13.0a0+git645fe20          pypi_0    pypi

cc @ezyang @bhosmer @bdhirsh

**Comment by ezyang** [comment]
the ufunc import is used in only one place so we can move it here. Send us a patch?

**Comment by huydhn** [comment]
Sound goods, it looks safe to remove ufunc import in `torchgen.model`. Let me send submit a fix for this
