### ISSUE TITLE
Lack of clear story around sub process group handling in torch.distributed

### ISSUE THREAD

**Issue by xunnanxu** [pytorch/pytorch#81291]
## Issue
The traditional SPMD full sync training requires all ranks to work together. This typically can work well with the regular gloo/nccl process group initialized in every rank.

Today some ML use cases require checkpointing/in-trainer publishing via a subset (1 or more in DDP/HSDP case) of ranks. A typical way is to create a sub process group using the `dist.new_group()` helper.
However, this creates challenges in various ways:

1. Currently the `new_group()` requires it to be called in all ranks (due to `_store_based_barrier()` call) to ensure the internal metadata (which are basically just some dicts) are consistent across all ranks. However, this means:
a. the sub pg cannot be created internally in some downstream libraries if those are then only invoked in those ranks. Sub pg creation (esp. gloo based) is useful for library authors to create more sophisticated logic for background processing.
b. it creates a potentially weird programming pattern where say if there are 2 calls in different sub groups, these groups' creation still needs to be hoisted like:

```
init_process_group() # world
sub_pg1 = new_group([1, 3, 5])
sub_pg2 = new_group([0])
if x:  # odd ranks
  save_checkpoint(sub_pg1)
if y:  # rank 0
  publish(sub_pg2)
```

It'd be more natural if it's like
```
init_process_group() # world
if x:  # odd ranks
  sub_pg1 = new_group([1, 3, 5])
  save_checkpoint(sub_pg1)
if y:  # rank 0
  sub_pg2 = new_group([0])
  publish(sub_pg2)
```

Note that this example may not be super obvious as it's simplified. In the real world a complicated trainer may have separate groups of people maintaining logic x and y.

2. Currently some of the calls (e.g. `broadcast()`) requires a `src` param to be passed in. This `src` somehow needs to be the global rank rather than the rank within the current pg. So in the case of odd ranks used, passing 0 would simply just stall the whole thing. Instead, the first rank within that group needs to be passed in which is `1`. However, there's no public methods for that except the internal `_get_global_rank()`. Even if that's possible it's weird to use. A group local rank may be more suitable here semantically.

## Proposal

The general proposal is to clarify the story around sub pg handling:
1. If some logic is needed in a subset of ranks, should caller pass a sub pg and invoke the call in that subset only (as opposed to invoke it in every rank and let non participating ranks return immediately)?
2. If a rank number is needed for certain collective calls, should the number be local to the process group?
3. Is a sub pg eligible to be created and destroyed in a subset of ranks (and updating metadata only in that sub group is allowed - this is currently not legit in existing API)?

This proposal would like to answer yes to all of the above.

In order to keep backward compatibility, the `new_group()` can be kept as is,
2 new APIs:

`new_sub_group()`: similar to `new_group()` but can be invoked in a subset of ranks.
`clone(group)`: creates a sub process group with the same parameters as the input unless specified.

can be introduced to explicitly allow for such capability.

https://gist.github.com/xunnanxu/1cc1ea37a81d10f15339f7aca80a38bb is a hacky version of allowing sub pg to be created within a library (`SPMDCounter` in this case) to demonstrate the technical possibility.

In that gist:
- `test_do_stuff_with_sub_pg` is the entry point creating 4 processes.
- The body `_work()` uses the public api `new_group()` to create the 1st sub group for odd ranks.
- Then the library `SPMDCounter` creates an internal pg, using internal methods, in the odd ranks only, for illustrative purpose for internal sync.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by aazzolini** [comment]
It seems to me that you are trying to propose a hybrid MPMD / SPMD programming paradigm -- I believe that in SPMD all ranks will need to be aware that some ranks will participate in some operations. The proposal superficially makes sense but I am not sure that it will be consistent if we deep dive into it.

**Comment by xunnanxu** [comment]
@aazzolini  I think a higher level question is whether process group in `torch.distributed` implies strict SPMD.

My understanding is it doesn't - as it basically just provides P2P and collective comm primitives and doesn't say if the program is strictly SPMD/MPMD (both can utilize those comm primitives anyway).

With regard to SPMD/MPMD model, you are right this is a complicated question. At high level this is like SPMD in a subset of ranks (as opposed to pure MPMD where very different programs are used). My limited understanding is that could be common in the future with HSDP (like if you have 4 ranks using DDP between 0,1 and 2, 3 while within each group it's FSDP), when checkpoint/publish, naturally one could do it only in 0 and 1 in that case. Having to call the same logic in replicated ranks and immediately return is kind of odd and not really SPMD either.

**Comment by aazzolini** [comment]
@xunnanxu  it would be intersting to bring in perspective from more folks. From my side, and thinking from a more abstract / higher level perspective, I see HSDP differently from MPMD in the following manner:

HSDP follows a regular mesh structure (think about 1 dimension of the mesh being the intra-host GPUs, and the other dimension of the mesh being the x-host interconnects).

As for arbitrary / irregular sub-process group, I'd actually think of them as different SPMD programs within a MPMD program, which is a bit different.

Your idea seems to be something about being able to "spawn" an SPMD sub-program from inside a larger SPMD program, which is a bit different from the 2 situations above. In this case, it seems natural that the outer-SPMD program should be collectively aware of the intent of launching a "sub-program", so i think the current semantic actually makes sense.

**Comment by divchenko** [comment]
I think if we allow new_group for a subset of ranks (and we do and there are legit uses for it as mentioned above) then requiring new_group to be called on all ranks is quite confusing. I was confused by it myself when I tried to use it for the first time.

**Comment by rohan-varma** [comment]
I think there are 2 things we should seek to understand here:

1) Whether current c10d today can support `new_group` like API if called on only a subset of ranks in a technical sense - what refactoring / changes would be required to support this, and whether it would be a flag in `new_group` API or an entirely new API as mentioned in this proposal. 

2) Whether this is semantically the right paradigm to support as @aazzolini mentioned

**Comment by kumpera** [comment]
I strongly believe it makes sense to support this scenario for many reasons.

First, this is a scalability bottleneck. On huge training jobs we might talking of tens of thousands of PGs in total while each rank only has a few.

It forces each rank to have a full understanding of the cluster and perform init in a globally sequential way. This is complex and hardly necessary.

I've looked at the code and it's surprisingly easy to overcome this limitation. I believe the following changes need to be done:

- _new_process_group_helper needs to handle naming without using _group_count.
- _store_based_barrier needs to be modified to support parallel barriers.

This is the sketch of the changes.

_new_process_group_helper creates a prefix store per PG -  we expose that per-pg store.
_store_based_barrier uses the per-pg store instead of the global one for rendezvous

_new_process_group_helper needs to be able to name a PG without depending on cluster global info.
I think the following schema works with high probability:

```python
def _process_group_name(ranks):
  global _pg_names
  pg_name = hashlib.sha1("_".join(map(str, ranks))).hexdigest()
  while pg_name in _pg_names:
   pg_name = hashlib.sha1(pg_name + "_").hexdigest() 
 return pg_name
```

This schema should work with a change of failure on the order of 10^-33 for 100 billion groups.

The core idea is that name collisions will only happen in ranks that have initialized another group with the same ranks so we don't need any global coordination.

**Comment by rohan-varma** [comment]
@kumpera Assigning this over to you since I think you've been taking up most of the efforts around this.
