### ISSUE TITLE
Feature request: range with Variable

### ISSUE THREAD

**Issue by qipeng** [pytorch/pytorch#813]
Supporting Variable as the lowerbound and upperbound (or even the stepsize) in `torch.range` might be very useful for variable length sequence operations (e.g. RNNs).

Currently this throws a `RuntimeError`.

```
>>> import torch
>>> from torch.autograd import Variable
>>> import numpy as np
>>> len = Variable(torch.from_numpy(np.array([3], dtype=np.int32)))
>>> torch.range(0,len)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Type Variable doesn't implement stateless method range
>>> torch.range(0,3)  # would want something like this

  0
  1
  2
  3
[torch.FloatTensor of size 4]
```

Let me know if I could help in any way with this!

**Comment by apaszke** [comment]
Can you please give us a hint on why would that be useful for variable length sequences?

**Comment by qipeng** [comment]
Actually after giving it a little bit more thought, this might not be as useful as I thought it would be. My immediate analogy was drawn from an example in static computational graph frameworks (tensorflow/theano), but that doesn't apply to PyTorch in hindsight.

Sorry for the confusion!
