### ISSUE TITLE
Use yaml.safe_load to replace yaml.load in the code for security.

### ISSUE THREAD

**Issue by wqh17101** [pytorch/pytorch#81329]
### 🚀 The feature, motivation and pitch

It is recommended that using `yaml.safe_load` to replace `yaml.load` in https://github.com/pytorch/pytorch/blob/1e3c6f2263c6a679dd11690e0b6c601b795dc759/caffe2/contrib/aten/gen_op.py#L236
as the things shown on the official website of pyyaml
![image](https://user-images.githubusercontent.com/26429138/178532606-b2109c8f-c6ec-4f6d-b1e0-b54b7247cf29.png)

### Alternatives

using `yaml.safe_load` to replace `yaml.load`

**Comment by albanD** [comment]
Hi,

Any reason why you wouldn't trust the input YAML stream? It comes from a local file on your drive.

**Comment by wqh17101** [comment]
From the perspective of computer security, any input is not trusted, and the software itself should be protected at the interface. @albanD

**Comment by wqh17101** [comment]
A little effort can prevent trouble before it happens, so why not?

**Comment by albanD** [comment]
Hey!
Feel free to send a PR to change that to use the safe loader and add me as a reviewer!

**Comment by wqh17101** [comment]
@albanD Ok,my pleasure.

**Comment by wqh17101** [comment]
@albanD I created a PR. There two questions.
1. how to add you as a reviewer
2. I created it before signing CLA, then there is no confirmation below my PR to continue the process

**Comment by albanD** [comment]
Added myself there.
You can force push into the PR to trigger the CLA check

**Comment by wqh17101** [comment]
> You can force push into the PR to trigger the CLA check

How to do this

**Comment by wqh17101** [comment]
@albanD Done. Thank you.

**Comment by wqh17101** [comment]
Sorry, you have already used the SafeLoader. @albanD 
https://github.com/pytorch/pytorch/blob/1e3c6f2263c6a679dd11690e0b6c601b795dc759/caffe2/contrib/aten/gen_op.py#L48-L52
So,there is no problem here.
