### ISSUE TITLE
Trunk + Binary build workflows don't get cancelled when a new commit is pushed

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#81350]
### 🐛 Describe the bug

When you tag a PR with ciflow/trunk or ciflow/binaries, future commits pushed to those PRs don't cancel the older commits.

**The Impact**: If someone has to makes quick changes back to back and pushes multiple commits out to a trunk/binaries tagged PR within minutes of each other, each of those commits will trigger a full set of workflows even though only the most recent commit has any value

This happens because the concurrency group for those workflows includes the commit sha today, which is always unique.  

Example:
```
concurrency:
  group: linux-binary-libtorch-cxx11-abi-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
```

Unlike normal PRs, these runs are actually triggered by the *commit* being given a certain tag.

### Versions

This is a problem with the ci workflows, not pytorch

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by clee2000** [comment]
do you have any examples of this happening? i just tried this with two commits ~6 minutes apart and the first commit's workflows were cancelled
![image](https://user-images.githubusercontent.com/44682903/179862899-1b41e949-7b60-47ec-b8d2-59e6c7239ab5.png)


i believe the ref_type of trunk and binary jobs run on pr is 'tag', so the sha doesnt end up getting included in the concurrency group name

**Comment by ZainRizvi** [comment]
Sorry, this seems like a false herring. I just tried reproing the issue and everything seems to have been cancelled correctly
https://hud.pytorch.org/hud/pytorch/pytorch/zain-test/1?per_page=50

I suspect what I saw was in-progress workflows taking a few minutes to get cancelled and I prob missed them actually getting cancelled later.

<img width="1882" alt="image" src="https://user-images.githubusercontent.com/4468967/180264857-f7e453f3-e42a-49b6-9ce4-8c53fee0ce27.png">
