### ISSUE TITLE
Unhandled FakeTensor Device Propagation for aten.index_put_.default, found two different devices cuda:0, cpu     

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#81387]
### 🐛 Describe the bug

Hopefully self explanatory. Don't have mini repro, to repro build with https://github.com/pytorch/pytorch/pull/80566 plus functorch fix and then `TORCH_DYNAMO_CUDAGRAPHS=1 python test/test_torch.py -k test_advancedindex_mixed_cpu_devices_cuda`

cc @eellison 

### Versions

master

**Comment by eellison** [comment]
This doesn't repro for me..

**Comment by eellison** [comment]
Hmm, I followed repro steps but fake tensor doesn't seem to be triggered, even with `use_fake_tensor = True` modified on the functorch fix.

**Comment by ezyang** [comment]
Maybe we fixed it. Closing!
