### ISSUE TITLE
Recent PR added -Werror=non-virtual-dtor make build failed

### ISSUE THREAD

**Issue by Guobing-Chen** [pytorch/pytorch#81393]
### 🐛 Describe the bug

Recent [PR #81012](https://github.com/pytorch/pytorch/pull/81012) added `-Werror=non-virtual-dtor` which make pytorch build failed (LLVM10) at `torch/csrc/jit/tensorexpr/llvm_jit.cpp`, which includes `llvm/ExecutionEngine/Orc/LLJIT.h` ---- suffer from `llvm::SCEVPredicate` has virtual function but non-virtual destructor.

Similar issue happen at torch/csrc/jit/tensorexpr/llvm_codegen.cpp with one of its included header `llvm/Analysis/TargetTransformInfo.h`. However, this header file has been waivered in the [PR #81012](https://github.com/pytorch/pytorch/pull/81012). So, quick fix is to add similar waiver at llvm_jit.cpp.

Error log:
```
In file included from /usr/lib/llvm-10/include/llvm/Analysis/LoopAnalysisManager.h:40,
                 from /usr/lib/llvm-10/include/llvm/Transforms/Scalar/LoopPassManager.h:45,
                 from /usr/lib/llvm-10/include/llvm/Passes/PassBuilder.h:23,
                 from /usr/lib/llvm-10/include/llvm/ExecutionEngine/Orc/Speculation.h:22,
                 from /usr/lib/llvm-10/include/llvm/ExecutionEngine/Orc/LazyReexports.h:21,
                 from /usr/lib/llvm-10/include/llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h:26,
                 from /usr/lib/llvm-10/include/llvm/ExecutionEngine/Orc/LLJIT.h:16,
                 from /home/neo/workspace/projects/tensorexpr/pytorch_guobing_nnc_quant_support/torch/csrc/jit/tensorexpr/llvm_jit.cpp:12:
/usr/lib/llvm-10/include/llvm/Analysis/ScalarEvolution.h:198:7: error: ‘class llvm::SCEVPredicate’ has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
  198 | class SCEVPredicate : public FoldingSetNode {
      |       ^~~~~~~~~~~~~
/usr/lib/llvm-10/include/llvm/Analysis/ScalarEvolution.h:265:7: error: base class ‘class llvm::SCEVPredicate’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
  265 | class SCEVEqualPredicate final : public SCEVPredicate {
      |       ^~~~~~~~~~~~~~~~~~
/usr/lib/llvm-10/include/llvm/Analysis/ScalarEvolution.h:302:7: error: base class ‘class llvm::SCEVPredicate’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
  302 | class SCEVWrapPredicate final : public SCEVPredicate {
      |       ^~~~~~~~~~~~~~~~~
/usr/lib/llvm-10/include/llvm/Analysis/ScalarEvolution.h:397:7: error: base class ‘class llvm::SCEVPredicate’ has accessible non-virtual destructor [-Werror=non-virtual-dtor]
  397 | class SCEVUnionPredicate final : public SCEVPredicate {
      |       ^~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```

### Versions

PyTorch version: 1.13.0a0+git3cf8cbf
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect   ---- actually I installed LLVM10 and using that for pytorch build with TE support. Not sure why cannot collect information here
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-121-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.10.0+cpu
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] numpydoc==1.1.0
[pip3] torch==1.13.0a0+git3cf8cbf
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl
[conda] intel-extension-for-pytorch 1.10.0+cpu               pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.13.0a0+git3cf8cbf          pypi_0    pypi
[conda] torchvision               0.11.3                   pypi_0    pypi

cc @malfet @seemethere

**Comment by ezyang** [comment]
can you send us the suppression? Tag me on it

**Comment by Guobing-Chen** [comment]
> Tag me on it

I created a PR to fix this issue as linked in this page already. But seems I cannot modify any label of the PR to tag you on if you mean `ezyang's list`.
