### ISSUE TITLE
Segmentation fault is raised when torch._C._nn.adaptive_avg_pool2d is called with some parameters

### ISSUE THREAD

**Issue by nrakwtnb** [pytorch/pytorch#81409]
### 🐛 Describe the bug

The segmentation fault appears when `torch._C._nn.adaptive_avg_pool2d` is called for some combinations of input and output shapes.

#### Code example

Here is the python script named `test.py`.

``` python:test.py
from __future__ import annotations
import sys
import torch

if __name__ == '__main__':
    assert len(sys.argv) == 5
    Ih, Iw, Oh, Ow = map(int, sys.argv[1:])
    _input_size = (Ih, Iw)
    _output_size = (Oh, Ow)

    torch.manual_seed(0)  # it seems seed value is irrelevant as far as I checked
    imgs = torch.randint(low=0, high=256, size=(1,)+_input_size).type(torch.float32)
    imgs_ = torch._C._nn.adaptive_avg_pool2d(imgs, _output_size)
```

By using this script,
all lines below raise `Segmentation fault (core dumped)`.

```
python test.py 5877 3697 2855 1
python test.py 5877 3697 2863 1
python test.py 4757 560 3527 2219
python test.py 5873 3693 3527 2219
```

#### A comment on parameters

Here are some combinations I found:

* input = `(1, 5877, 3697)`, output = `(2855+4*i, j)`
  for any i,j >= 0 as far as I checked

* input = `(1, 4757+4*i, j)`, output = `(3527, 2219)`
  for any i >= 0 and many j > 200 (?) as far as I checked
  examples of j are 280, 560, 867, 870, 884, >= 1060 at least

It seems there are other patterns and some rules behind but I don't know.

### Versions

The following is one example of environments for error reproductions:

```
Collecting environment information...
PyTorch version: 1.12.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.13 (main, Jul 12 2022, 12:04:02)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-4.4.0-210-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.0+cpu
[conda] Could not collect
```

#### comment

At least, I ran the above scripts with docker container whose image is `python:3.9.13-bullseye` and found the error reproduction. I also reproduced it at a laptop with Ubuntu or virtual machines with cuda as well.

**Comment by albanD** [comment]
This was fixed.
