### ISSUE TITLE
`CHECK_*` macro signatures break downstream pytorch/xla build

### ISSUE THREAD

**Issue by miladm** [pytorch/pytorch#81415]
### 🐛 Describe the bug

Tensorflow recently upgraded to C++17. PyTorch/XLA is upgrading its TF pin and by extension building its TF dependency with C++17. PyTorch/XLA continues to build its own source code in C++14 to stay consistent with the upstream PyTorch.

It turns out the compiler confuses this [definition](https://github.com/tensorflow/tensorflow/blame/master/tensorflow/core/platform/default/logging.h#L456) of `CHECK_NE` in Tensorflow with that of PyTorch in [c10/util/logging_is_not_google_glog.h](https://github.com/pytorch/pytorch/blob/master/c10/util/logging_is_not_google_glog.h#L139-L145). This leads to the following error. This issue occurs because it is not possible to place macros in a namespace. I get similar errors for `DCHECK_NE`, `CHECK_EQ`, etc. 

```
/sw/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/service/hlo_module.h: In member function ‘const xla::Shape& xla::HloModule::result_shape() const’:
/sw/pytorch/c10/util/logging_is_not_google_glog.h:141:30: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::nullptr_t’)
  141 |                              << (val1) << " vs. " << (val2) << ") "
      |                              ^
/sw/pytorch/c10/util/logging_is_not_google_glog.h:141:30: note: in definition of macro ‘CHECK_OP’
  141 |                              << (val1) << " vs. " << (val2) << ") "
      |                              ^~
/usr/local/<redact>/sw/pytorch/xla/third_party/tensorflow/bazel-tensorflow/tensorflow/compiler/xla/service/hlo_module.h:137:5: note: in expansion of macro ‘CHECK_NE’
  137 |     CHECK_NE(nullptr, entry_computation_);
      |     ^~~~~~~~
In file included from /usr/include/c++/11/iostream:39,
                 from /usr/local/google/home/miladmo/sw/pytorch/xla/torch_xla/csrc/debug_util.h:3,
                 from /usr/local/google/home/miladmo/sw/pytorch/xla/torch_xla/csrc/debug_util.cpp:1:
```

To check if the issue partially resolves by changing the `CHECK_*` macro names, I commented out CHECK_NE (only) and renamed CHECK_OP to CHECK_OPS in PyTorch. This was possible because `CHECK_NE` is not used in PT source code. I am happy to see CHECK_NE errors disappear.

**Request**

Previously, this name collision has been a compiler warning in PyTorch/XLA. Now, with the change in C++ compiler version, this has become a blocking error. At the same time, FWIW, I understand [PT migration to C++17](https://github.com/pytorch/pytorch/issues/56055) is not in the immediate term horizon. 

I'd propose to rename these macros to resolve the macro names collision. Wdyt?

CC @wconstab @ezyang @JackCaoG 

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+git6e292f1
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 11.3.0-3) 11.3.0
Clang version: 13.0.1-4
CMake version: version 3.19.6
Libc version: glibc-2.33

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.17.11-1rodete2-amd64-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.12.0a0+gitde18c28
[pip3] torch-xla==1.12
[pip3] torchvision==0.13.0a0+08cc9a7
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.12.0a0+gitcaa1177          pypi_0    pypi
[conda] torch-xla                 1.12                     pypi_0    pypi
[conda] torchvision               0.13.0a0+08cc9a7          pypi_0    pypi

cc @bdhirsh

**Comment by ezyang** [comment]
I think renaming is not quite right, because the conflict is with glog from xla (I presume), but the point of these macros is to polyfill glog when we don't compile with it. If this macro is totally unused everywhere, though, let's just delete

**Comment by miladm** [comment]
The glog source code is under `pytorch/c10/util`. PyTorch/XLA doesn't depend on these glog source files. 

These macros are used in several places across the pytorch/pytorch source code including `caffe2`, `aten/src/ATen`, `test`, `torch/csrc/jit`, `torch/csrc/jit`. Perhaps pytorch wants to keep the macros. 

What's your guidance if you were to keep them @ezyang?

**Comment by ezyang** [comment]
I guess if you were building PT from source you would compile WITH the same glog that xla was compiling with and everything is happy. But IIRC you don't actually want to build PT from source. So this is irritating. Not sure how else to do it. What if we allow swapping between glog and not glog and include time... cc @malfet

**Comment by malfet** [comment]
> What if we allow swapping between glog and not glog and include time... cc @malfet

We already have it, albeit in somewhat hacky fashion - one can pass `-DC10_UTIL_LOGGING_IS_NOT_GOOGLE_GLOG_H_` to compile flags and none of the definitions from that file would be used, or `-DC10_USE_GLOG` but that could lead to subtle differences.
IMO more prudent solution would be to hide logging primitives as implementation detail and not include it as frequent

**Comment by wconstab** [comment]
> hide logging primitives as implementation detail 

Basically, change code that calls e.g. CHECK_EQ to call a TORCH_CHECK_EQ indirection and hide the details?

**Comment by miladm** [comment]
FWIW, PT/XLA follows a similar macro naming approach - e.g. `XLA_CHECK_EQ`. 

Happy to help add the appropriate change when we are aligned here.

**Comment by wconstab** [comment]
It sounds ok to me.. although i don't think we have a TORCH_CHECK_EQ macro so it may be slightly more work than a simple PR to swap them over

**Comment by miladm** [comment]
Sounds good @wconstab. 
Please loop me in once PyTorch has a PR out for this fix so I can unblock the TF pin upgrade in PT/XLA.

**Comment by miladm** [comment]
@wconstab checking in. Looks like this issue was triaged. Not sure if it's been addressed yet.
This fix helps unblock TF update for PyTorch/XLA.

**Comment by wconstab** [comment]
I lost track of this. It isn't totally clear to me what the best fix is.  One option might be simply renaming our macros.  I kicked off a CI job and PR #81904 to see if anything unexpectedly fails, or if anyone raises objection to the approach.  If it seems viable it is pretty simple to do the others using similar sed cmds.
