### ISSUE TITLE
[onnx] Add support for prim::DictConstruct in pytorch-ONNX converter

### ISSUE THREAD

**Issue by shubhambhokare1** [pytorch/pytorch#81482]
### 🐛 Describe the bug

Current handling of dict types is very limited in pytorch-ONNX converter is extremely limited.
In tracing mode, all the dict types are flattened such that only the values in the key-value pair are preserved.
In scripting mode, no such flattening occurs, and the conversion just errors out.

### Versions

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-1014-azure-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==1.13.0a0+gitf1aeea2
[pip3] torchvision==0.13.0a0+8e5844f
[conda] mkl                       2022.0.1           h06a4308_117  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.0a0+git6997ac7          pypi_0    pypi
[conda] torchvision               0.13.0a0+8e5844f           dev_0    <develop>

**Comment by shengugang** [comment]
do you fix this bug?

**Comment by thiagocrepaldi** [comment]
this task has been deprioritized and will be closed for now
