### ISSUE TITLE
Docs: Give Format of weight parameters in KLDivLoss, fix BCELoss formatting

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#815]

**Comment by dasguptar** [comment]
@soumith I was thinking I'll take this one up, but couldn't exactly find the code for these loss layers. A search of the repository returns multiple files(.py, .c, .cu, legacy, functional, etc.). Could you point me to somewhere I could understand how the whole code is organised?

**Comment by soumith** [comment]
you just have to change the file https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/loss.py to fix this task.

**Comment by zou3519** [comment]
@soumith I don't think KLDivLoss takes weight parameters. Did you mean BCELoss? If so, I added more details on the weights for BCELoss: #3535. 

BCELoss formatting seems to have been fixed somewhere down the line:
![image](https://user-images.githubusercontent.com/5652049/32507939-cca516e6-c3b6-11e7-92c8-1940717a844f.png)
