### ISSUE TITLE
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above

### ISSUE THREAD

**Issue by knslee07** [pytorch/pytorch#81511]
### 🐛 Describe the bug

I believe this issue might have been reported before and there are suggestions. I try to replicate suggested solutions on stackoverflow, but it did not work for me.
My code worked until yesterday, but it no longer does suddenly today afternoon. I did not change anything software/hardware-wise.
I get "ImportError: TensorBoard logging requires TensorBoard version 1.15 or above", but my tensorboard version is 2.9.1.
I created a new Conda environment and installed PyTorch and Tensorboard only, but get the same error.
If I need to report this to somewhere else, not here, I apologize.

import torch
from torch.utils.tensorboard import SummaryWriter

'''
ImportError                               Traceback (most recent call last)
/mnt/c/Users/     .ipynb Cell 3' in <cell line: 1>()
----> [1](vscode-notebook-cell://wsl%2Bubuntu-20.04/mnt/c/Users/     .ipynb#ch0000002vscode-remote?line=0) from torch.utils.tensorboard import SummaryWriter
      [3](vscode-notebook-cell://wsl%2Bubuntu-20.04/mnt/c/Users/     .ipynb#ch0000002vscode-remote?line=2) tb = SummaryWriter()
      [5](vscode-notebook-cell://wsl%2Bubuntu-20.04/mnt/c/Users/     .ipynb#ch0000002vscode-remote?line=4) network = Network()

File ~/miniconda3/envs/495D/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:5, in <module>
      2 from distutils.version import LooseVersion
      4 if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
----> 5     raise ImportError('TensorBoard logging requires TensorBoard version 1.15 or above')
      7 del LooseVersion
      8 del tensorboard

ImportError: TensorBoard logging requires TensorBoard version 1.15 or above
'''

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050
Nvidia driver version: 512.77
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.22.3           py38he7a7128_0
[conda] numpy-base                1.22.3           py38hf524024_0
[conda] pytorch                   1.11.0          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py38_cu102    pytorch
[conda] torchvision               0.12.0               py38_cu102    pytorch

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/. If it turns out there's a bug, please create a new issue.
