### ISSUE TITLE
[ProxyTensor] ProxyTensor can't trace through certain kinds of slicing.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#81529]
### 🐛 Describe the bug

```
from torch.fx.experimental.proxy_tensor import make_fx
import torch

def f(x, y):
    return x[0, y:]

fx_g = make_fx(f)(torch.randn(5, 5), torch.tensor(3))
print(fx_g.code)
```

The issue is that this ends up calling `slice.Tensor`, which only takes ints.

This is also nice for vmap.

cc: @zou

### Versions

N/A

cc @ezyang @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by ezyang** [comment]
for reference the error is

```
(/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/pytorch-scratch2$ python a.py
Traceback (most recent call last):
  File "a.py", line 7, in <module>
    fx_g = make_fx(f)(torch.randn(5, 5), torch.tensor(3))
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 407, in wrapped
    t = dispatch_trace(wrap_key(f, args), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 246, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/_symbolic_trace.py", line 714, in trace
    (self.create_arg(fn(*args)),),
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 270, in wrapped
    out = f(*tree_args)
  File "a.py", line 5, in f
    return x[0, y:]
  File "/raid/ezyang/pytorch-scratch2/torch/utils/_python_dispatch.py", line 74, in wrapped
    return f(self, *args, **kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 290, in __torch_dispatch__
    return proxy_call(func_overload, args, kwargs)
  File "/raid/ezyang/pytorch-scratch2/torch/fx/experimental/proxy_tensor.py", line 85, in proxy_call
    raise RuntimeError("It appears that you're trying to get value out of a tracing tensor - erroring out! "
RuntimeError: It appears that you're trying to get value out of a tracing tensor - erroring out! It's likely that this is caused by data-dependent control flow or similar.Try torch.fx.experimental.proxy_tensor.enable_strict(False) to disable this check
```

**Comment by ezyang** [comment]
How important is the model this sources from? Can we graph break on this kind of slicing for now?

**Comment by ezyang** [comment]
To make this work, we have to do the following things:

1. Introduce a new version of `slice` which takes Tensor arguments. Irritatingly, there are three arguments where tensors could be passed; we probably don't want to do all combinations, so it would be with Tensor for all arguments, and if some of the arguments were regular ints we would have to wrap them into tensors.
2. Rewrite the slice code in torch/csrc/autograd/python_variable_indexing.cpp to not use `THPUtils_unpackSlice` which forces the slice to go to integers but instead extract possibly tensor arguments and call the overload directly
3. Check that the multi dim slice also works with this change

**Comment by bdhirsh** [comment]
Just confirming my understanding - even with the above changes, don't we need full (`nonzero`-style) dynamic shape support in order to avoid a graph break?

When you run `x[0, y:]`, the sizes of the output tensor depend on the data of `y`.

So if we want dynamo to work on this code before then, we'll need to get dynamo to graph break?

**Comment by ezyang** [comment]
Oops, you're right. On the plus side if the input tensor is a constant (as it is in the example) we can use const prop to get it to work even without a graph break
