### ISSUE TITLE
[ProxyTensor] ProxyTensor doesn't support in-place operators where the first input isn't a tensor.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#81526]
### 🐛 Describe the bug

All in-place ops used to have their first arg be a tensor. However, with the addition of ops like `c10d::broadcast_`, this is no longer true.

This line needs to be changed to work now.

https://github.com/pytorch/pytorch/blob/master/torch/fx/experimental/proxy_tensor.py#L87

This causes moco to have issues with tracing: https://github.com/pytorch/torchdynamo/issues/331

### Versions

N/A

cc @Chillee @ezyang @zou3519 @albanD @samdow

**Comment by ezyang** [comment]
We should read this info out from the schema.

**Comment by ezyang** [comment]
@bdhirsh wondering if you want to pick this up, it's pretty similar to functionalization
