### ISSUE TITLE
torch.cuda.is_available() return False（Try multiple versions）

### ISSUE THREAD

**Issue by LUO77123** [pytorch/pytorch#81549]
### 🐛 Describe the bug

I created multiple environments based on Cuda10.2 and Cuda11.6 and reported the same error on the A100 card。
nvidia-smi =11.6,    A100
1.export Cuda10.2->nvcc -V=10.2
conda create -n XXX python=3.9
conda activate XXX
conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=10.2 -c pytorch
python
import torch
torch.cuda.is_available()
return False
2.export Cuda11.6->nvcc -V=11.6
conda create -n XXX python=3.9
conda activate XXX
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge   (or)  pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116 
python
import torch
torch.cuda.is_available()
return False

Such errors are reported（UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180549130/work/c10/cuda/CUDAFunctions.cpp:112.)）

### Versions

1.nvcc=10.2,nvidia-smi=11.6,pytorch=1.10.1
![image](https://user-images.githubusercontent.com/87272337/179187241-33a6668c-6c15-4e83-84c8-57423ef77ed3.png)

2.nvcc=11.6,nvidia-smi=11.6,pytorch=1.12
![image](https://user-images.githubusercontent.com/87272337/179188059-fb66f49b-f64e-4369-9da4-e1d5dc5a7b37.png)

cc @ngimel

**Comment by kit1980** [comment]
Can you run `nvidia-smi` there?

**Comment by LUO77123** [comment]
I can.
![image](https://user-images.githubusercontent.com/87272337/179872136-4d866859-ff60-499a-bd83-a48244db722b.png)

**Comment by LUO77123** [comment]
> Can you run `nvidia-smi` there?

I can.
![image](https://user-images.githubusercontent.com/87272337/179872173-815bab41-eae0-49e4-9a8a-e194776658dc.png)

**Comment by ngimel** [comment]
Closing, looks like user environment bug. Reopen if you can run cuda samples as @ptrblck suggested
