### ISSUE TITLE
A100 -->CUDA initialization: Unexpected error from cudaGetDeviceCount()

### ISSUE THREAD

**Issue by LUO77123** [pytorch/pytorch#81542]
### 🐛 Describe the bug

I use （cuda10.2,torch1.10.1） and （cuda11.6,torch1.12）, they both make the same mistake.How do I solve it?
1->cuda10.2,torch1.10.1
![image](https://user-images.githubusercontent.com/87272337/179151470-5f7eede3-0593-41c2-b91d-e6c409d3a0ba.png)
2->cuda11.6,torch1.12
![image](https://user-images.githubusercontent.com/87272337/179151669-47bcf623-b774-4ae2-bb85-576ada2c723c.png)
How do I solve it?

### Versions

nvcc -V=10.2, nvidia-smi=11.6
![image](https://user-images.githubusercontent.com/87272337/179151164-315588d9-52eb-4603-af91-feedcc1e9875.png)
pytorch=1.10.1
![image](https://user-images.githubusercontent.com/87272337/179151409-c6daf5e7-de0a-4a2a-b42a-6fc1f0a9b343.png)

nvcc -V=11.6, nvidia-smi=11.6
![image](https://user-images.githubusercontent.com/87272337/179150676-ecbeaf33-8852-4014-a455-53259e56b5be.png)
pytorch=1.12
![image](https://user-images.githubusercontent.com/87272337/179150518-ad8bdee3-58f3-4783-93c0-6caa488035e2.png)

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/. If it turns out that there's a bug, please open a new issue.
