### ISSUE TITLE
Macbook M1 GPU support "mps" results in wrong (random) conversion when casting a tensor to LongTensor type.

### ISSUE THREAD

**Issue by Lilac-Lee** [pytorch/pytorch#81567]
### 🐛 Describe the bug

A simple test code below:
```
import torch
a=torch.tensor([9.0,3.0, 5.0, 4.0])
a=a.to(torch.device('mps'))
a.type(torch.LongTensor)
```

The output would be some random numbers, for example:
```tensor([         9,          3, 8675683992,          0])```.
If you run the code again, you could get:
```tensor([         0,          0, 4335857328, 4506956464])```.
Run again, you get:
```tensor([                   0,                    0, -8070450532247928832, -8070450532247928832])```.
Again:
```tensor([0, 0, 0, 0])```,
etc.

If you cast the tensor type to LongTensor on CPU, it would be fine:
```
import torch
a=torch.tensor([9.0,3.0, 5.0, 4.0])
a=a.type(torch.LongTensor)
a.to(torch.device('mps'))
```

Output:
```tensor([9, 3, 5, 4], device='mps:0')```.

### Versions

Python: 3.9.12,
PyTorch: stable(1.12.0), mac, conda, python, default.
Macbook: Macbook Pro with M1 Max chip, Monterey 12.4.

cc @kulinseth @albanD

**Comment by DenisVieriu97** [comment]
Hi @Lilac-Lee. Thanks for the report!
This is indeed an issue - I've put a fix at https://github.com/kulinseth/pytorch/pull/64 and currently is in PR. I'll update this thread when it gets in PyTorch master
