### ISSUE TITLE
MacOS conda caffe2 package incorrect protobuf versions.

### ISSUE THREAD

**Issue by lukemurray** [pytorch/pytorch#8158]
## Issue description

Installing the caffe2 package with `conda install -c caffe2 caffe2` installs `protobuf: 3.4.1-py36h314970b_0` as well. 

When I try to compile a C++ application with Caffe2 it complains that the protobuf headers are compiled with 3.5.x and 3.4.x is too old.

I got around this by using `brew` to install protobuf 3.5.x and my app linked against that. But I think the conda package is incorrect?

## Code example

Error with the conda protobuf
```/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:12:2: error: This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is
 ^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:13:2: error: incompatible with your Protocol Buffer headers. Please update
#error incompatible with your Protocol Buffer headers.  Please update
 ^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:14:2: error: your headers.
#error your headers.
 ^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:3384:53: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      device_detail = ::google::protobuf::internal::GetOwnedMessage(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:3438:47: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      segment = ::google::protobuf::internal::GetOwnedMessage(
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:4137:41: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      n = ::google::protobuf::internal::GetOwnedMessage(
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:4880:53: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      device_option = ::google::protobuf::internal::GetOwnedMessage(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:5337:53: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      device_option = ::google::protobuf::internal::GetOwnedMessage(
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:6339:46: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      tensor = ::google::protobuf::internal::GetOwnedMessage(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/lukemurray/anaconda3/include/caffe2/proto/caffe2.pb.h:6456:47: error: no member named 'GetOwnedMessage' in namespace 'google::protobuf::internal'
      qtensor = ::google::protobuf::internal::GetOwnedMessage(
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
10 errors generated.
```

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

- PyTorch or Caffe2: Caffe2
- How you installed PyTorch (conda, pip, source): Pytorch, PIP (in conda env), Caffe2 Conda
- Build command you used (if compiling from source):
- OS: MacOS 10.13.4
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version: none
- GPU models and configuration: none
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by pjh5** [comment]
The conda packages are built against protobuf. We chose protobuf 3.4.1 because it is fairly recent. The conda install of Caffe2 knows to install a compatible version of protobuf when it installs Caffe2. If you later change this version of protobuf to something else, then Caffe2 might not work anymore, because it is linking against a library that has different symbols. We will not build a separate Caffe2 conda package for every version of protobuf.

What do you mean by "try to compile a C++ application with Caffe2" ? What is throwing that error? Compilation of Caffe2 or compilation of your C++ application? Is it compiling with cmake and rebuilding Caffe2?

It also looks like you have your brew directories before your conda directories on your PATH. This is a bad idea, and you should move the conda directories to be first.

**Comment by lukemurray** [comment]
I am compiling my application. It includes the caffe2 headers. If I uninstall all protobuf versions except the one the conda caffe2 package installs (3.4.1) I get errors (from above) when including the caffe2 headers in my project. If I look at those headers (in conda caffe2 install dir) they seem to require version 300500.

Running the commands to check protobuf version from your FAQ shows I have 3.4.1 in this instance.

If I install protobuf 3.5.x from brew and compile my application I don't get the caffe2 errors as it now finds a newer version.

I guess I'm missing something here but I can't get my application to compile with caffe2 headers and conda protobuf (3.4.1).



________________________________

**Comment by lukemurray** [comment]
I assume this is the error getting thrown (based header file included, error message, etc.)

```#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif```

**Comment by pjh5** [comment]
It's not clear to me which protobuf you want. There are several protobufs in conda, "conda search protobuf" to see them all for your current OS. Which protobuf do you want / need? Why can you not use the protobuf that comes with Caffe2 (by "comes with" I mean the protobuf that conda decides to ship with it)?

Do you mean that on a clean install of Caffe2 into a new conda environment that you are getting an error message about protobuf version mismatches?

**Comment by lukemurray** [comment]
Yes, I mean on a clean install I get the error. I expect installing caffe2 to work without having to manually install another protobuf version.

i.e.

- I have _no_ protobuf library installed
- I install caffe2 via `conda install -c caffe2 caffe2`. This also installs protobuf 3.4.1
- I compile my application that includes depends on caffe2 (via cmake, which cmake finds)
  - App has `#include <caffe2/core/init.h>`, `#include <caffe2/core/net.h>` & `#include <caffe2/utils/proto_utils.h>`
- I receive the above errors listed above

Those errors tell me that the headers in caffe2 are compiled with a _newer_ version of protobuf than installed (installed is 3.4.1).

I install protobuf 3.5.x from brew (I can't from conda as it will uninstall caffe2). And I can now compile my application as it finds the caffe2 headers and a matching protobuf version (now 3.5.x).

So out of the box install of caffe2 I can't link against it/include it's headers.

I have no requirement on any protobuf version myself, only caffe2 does. But, for me, it doesn't work out of the box. Based on the error messages I _assumed_ that the conda package _may_ be installing the wrong protobuf version.

**Comment by pjh5** [comment]
All our packages our actually built with a statically linked custom protobuf with hidden visibility. They're not actually built against any protobuf in conda. This is to avoid tons of tricky problems involving incompatible protobuf versions and incompatible c++ compilers (e.g. ser https://github.com/caffe2/caffe2/issues/1980 ). Getting this to work requires a lot of care and separate packages for gcc4.8 or gcc5+, which is confusing to users and can mess with their conda environments.

Unfortunately, I'm going to consider your use case as advanced enough that we aren't going to support it in the pre-built conda packages but rather ask that you build from source, when you can build protobuf and link it dynamically into Caffe2. If you encounter any issues linking against Caffe2 when building from source though, please open another issue to let us know as that is something that we want to be easy

**Comment by lukemurray** [comment]
Thanks

**Comment by pjh5** [comment]
BTW, if you want to link protobuf into Caffe2 dynamically then this is the flag you'll have to turn off https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L53
