### ISSUE TITLE
WeakTensorMap as part of stdlib

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#81597]
### 🐛 Describe the bug

as @eellison discovered in his implementation of MetaTensorConverter, it is surprisingly difficult to implement a WeakTensorMap correctly. Let's add one to the standard lib so people can use it.

See also https://github.com/pytorch/pytorch/issues/7733

### Versions

master

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by ezyang** [comment]
According to @albanD at https://github.com/pytorch/pytorch/pull/83174 using the regular dictionary classes should now work

**Comment by albanD** [comment]
@eellison do you have details on how hard this is to do?
What is missing from `weakref.WeakKeyDictionary`?
Is it just about our custom fixup logic we need to use when using Tensor weakrefs?

**Comment by eellison** [comment]
I don't think https://github.com/pytorch/pytorch/pull/83174 fixes the issue. it's not the hash that's the problem, it's the `__eq__`. 
```
# torch.Tensors cannot be used as a key in a dictionary
# because they define a custom __eq__ function which when used
# to resolve hash collisions will throw when comparing tensors:
# "RuntimeError: bool value of Tensor with more than one value is ambiguous."
```

I mean, it was kind of tricky to do, but it's already done - see https://github.com/pytorch/pytorch/blob/master/torch/_subclasses/meta_utils.py#L16 and https://github.com/pytorch/pytorch/blob/master/torch/_subclasses/fake_tensor.py#L102. The remaining thing to do for stdlib would just be to make it pickle-able.

**Comment by albanD** [comment]
I think the `__eq__` issue was just a sidetrack due to bad `__torch_function__` implementation: you were creating a temporary object and return its `id` as the `hash()`.
And due to PyObject re-use in Python, every single Tensor had the same hash (which `is` being False). And so every match was trying to use `__eq__` to resolve hash conflicts.

With the fixed version, you will properly get a unique hash (with objects always being `is` True) and so `__eq__` should never be called.

**Comment by eellison** [comment]
Hmm, yea you're right. Nice! Although I'm surprised 
```
        if has_torch_function_unary(self):
            return handle_torch_function(Tensor.__hash__, (self,), self)
```
fired for FakeTensor since it doesn't define `__torch_function__`

**Comment by eellison** [comment]
Hmm, yea you're right. Nice! 

Although I'm surprised 
```
        if has_torch_function_unary(self):
            return handle_torch_function(Tensor.__hash__, (self,), self)
```
fired for FakeTensor since it doesn't define `__torch_function__`:  `__torch_function__ = torch._C._disabled_torch_function_impl`

(admittedly copy-pasta'd from https://github.com/albanD/subclass_zoo/blob/main/base_tensor.py#L22)

**Comment by albanD** [comment]
Couldn't it be due to the mode there `FakeCopyMode`?

**Comment by eellison** [comment]
The FakeCopyMode isn't actually invoked when you run the model..

**Comment by ezyang** [comment]
Unfortunately, Python's built-in weak key dictionary will attempt to do a traditional equality test

```
>>> d = weakref.WeakKeyDictionary()
>>> d[x] = 1
>>> d[x] = 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ezyang/local/pytorch-tmp-env/lib/python3.9/weakref.py", line 429, in __setitem__
    self.data[ref(key, self._remove)] = value
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

**Comment by albanD** [comment]
Well, we would need to override this one anyways to be able to call `_fix_weakref()` ?

**Comment by eellison** [comment]
> Well, we would need to override this one anyways to be able to call _fix_weakref() ?

No because we're wrapping it in `WeakTensorRefKey` which has custom `__eq__` https://github.com/pytorch/pytorch/blob/master/torch/_subclasses/meta_utils.py#L43

**Comment by ezyang** [comment]
Err, to answer Alban's question more directly, so long as the C++ stays live for the duration of the ref from weakref lifetime, I think it's OK; the invariant violated Python object quickly disappears and you're back in the C++ is owner universe. So no, I don't think it would technically be necessary to fix weakref here.

**Comment by albanD** [comment]
@ezyang should we close this now that we have `WeakTensorKeyDictionary` ?

**Comment by ezyang** [comment]
yup
