### ISSUE TITLE
ios-12-5-1-x86-64 / Run Simulator tests does not run tests against commit in question

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#81613]
### 🐛 Describe the bug

If one to look at https://github.com/pytorch/pytorch/blob/446833d11f7a99366323bf4033a579a10a9309c6/.github/workflows/_ios-build-test.yml#L161
it's easy to notice, that "Run  Simulator Tests" is not run against trunk commit, but rather against latest successful MacOS nightly build of PyTorch + torchvision and torchaudio binaries

For example CI for commit https://github.com/pytorch/pytorch/commit/0b5b10002af2dce031d4fad337728f81c58a8b10 submitted on Jul 16th were run by tests against  Jul 7th nightly build as can be seen in
https://github.com/pytorch/pytorch/runs/7369514831?check_suite_focus=true#step:9:147

When fixed, please re-enabled the test by disabling https://github.com/pytorch/pytorch/pull/81612

### Versions

CI

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by kit1980** [comment]
It looks like the nightly is installed only to generate models to use with the test.
The test itself uses the PR's pytorch.

**Comment by kit1980** [comment]
I think this is working as intended.
I dug up original PR, it has a comment that was lost to the time: "use the pytorch nightly build to generate models"  -https://github.com/pytorch/pytorch/pull/65076/files#diff-018705bb8c577c07b36b4c425393c07aa32c37d2e7fc08e0404c57f77d7c2a14R568

I'm going to re-add the comment and try enabling the test again.

**Comment by linbinyu** [comment]
I think it will be better if the model is also generated by trunk code, if it didn't take long time to build

**Comment by kit1980** [comment]
> I think it will be better if the model is also generated by trunk code, if it didn't take long time to build

Do you mean in addition to using nightly, or instead of using nightly?
