### ISSUE TITLE
M1 MPS memory leak.

### ISSUE THREAD

**Issue by mmulet** [pytorch/pytorch#81610]
### 🐛 Describe the bug

Hello!
 I was testing out mps support on my M1 max, it works great except the memory usage ballooned! (This is is in the Nightly build, the stable build does not have this problem). It reached up to 250GB of RAM after about 1100 iterations of the loop below. 
I've tried the same code below on cpu, no memory leak, and I also tried it on my PC both on windows and ubuntu with CUDA, no memory leak there either. So, the leak only happens when using mps. I also tried it with bert-base-cased, instead of distilbert-base-cased, but the memory leak remained.
```python
import torch

tokenizer = torch.hub.load("huggingface/pytorch-transformers", "tokenizer", "distilbert-base-cased",trust_repo=True)
bert = torch.hub.load("huggingface/pytorch-transformers", "model", "distilbert-base-cased",trust_repo=True)
mps_device = torch.device("mps")
bert.to(mps_device)

index_tokens = tokenizer.encode("12345678","12345678", add_special_tokens=True)
tokens_tensor = torch.tensor([index_tokens], device=mps_device)

for i in range(0,2000):
    bert(input_ids=tokens_tensor)
    if i % 100 == 0:
        print(i)
```

If it makes any difference, I had to build https://github.com/huggingface/tokenizers from source to get it to run. (I used the latest commit, which is adf90dcd722cbc20af930441988b317a19815878 at the time of writing)

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220716
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 (main, May 24 2022, 21:13:51)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220716
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchvision==0.14.0.dev20220716
[conda] Could not collect

cc @kulinseth @albanD

**Comment by razarmehr** [comment]
Thank you for reporting the issue. We could reproduce the memory grow and we're working on the fix.
