### ISSUE TITLE
LSTM segmentation fault in docker

### ISSUE THREAD

**Issue by dmitri-carpov** [pytorch/pytorch#8162]
## Issue description

LSTM module fails with Segmentation fault (exit code 139) in docker.

## Code example

```
import torch

torch.nn.LSTM(input_size=1,
              hidden_size=1,
              num_layers=3)(torch.randn(7500, 1, 1))
```

This code fails with code 139 in docker only; in python virtual env when number of layers is high enough it exists with code 137. 

To reproduce segmentation fault issue save the code above to `lstm_139.py` file and run docker: 

```
docker run --rm -it -v `pwd`/lstm_139.py:/lstm_139.py pytorch/pytorch python3 /lstm_139.py ; echo $?
```

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by zou3519** [comment]
Thank you for the report, @dmitri-carpov. 

My guess is that this is https://github.com/pytorch/pytorch/issues/5534 again, but I haven't looked at a gdb stacktrace of this yet.

**Comment by zou3519** [comment]
@dmitri-carpov the bug should be fixed on master. Could you try building from source and seeing if it goes away?

You can build a docker image from source with: https://github.com/pytorch/pytorch#docker-image

**Comment by dmitri-carpov** [comment]
Indeed, it is fixed on master.

**Comment by zou3519** [comment]
Awesome, thanks for checking!
