### ISSUE TITLE
Simple LSTM ~260x slower on AMD CPU vs Intel CPU

### ISSUE THREAD

**Issue by callumm-graphcore** [pytorch/pytorch#81634]
### 🐛 Describe the bug

When I run (the forward pass of) a simple LSTM model, it takes ~260x longer on an AMD CPU compared with an Intel CPU.

My reproducer:
```
import time

import torch

lstm = torch.nn.LSTM(input_size=256, hidden_size=256, num_layers=2, batch_first=True)

inp = torch.rand(8, 2000, 256)
h0 = torch.rand(2, 8, 256)
c0 = torch.rand(2, 8, 256)

tick = time.time()
_ = lstm(inp, (h0, c0))
tock = time.time()
print(tock - tick)
```

This takes ~0.75s on an Intel CPU and ~200s on an AMD CPU, a ~260x slowdown.

### Versions

On the AMD CPU:

```
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-110-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.0
[conda] Could not collect
```

cc @VitalyFedyunin @ngimel @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by callumm-graphcore** [comment]
The reason this is relevant for us (Graphcore) is that we currently use `torch.jit.trace` to capture the Pytorch computation as a computational graph. This requires running the model on the CPU, usually several times to ensure that the trace is the same every time. This means that a slowdown on the CPU like this can seriously impact our compilation time.

As such, we would very much appreciate any insight into why this is happening and whether we can fix it. Thank you for your time!

**Comment by albanD** [comment]
Hi,

My first guess would be that we use a fused kernel on Intel and not AMD? Not sure how these are implemented tbh cc @ngimel 
The other possibility would be that intra op parallelism is problematic on AMD because you have more cores? Can you try setting `torch.set_num_threads()` to the same value in both cases to see if that helps?

**Comment by callumm-graphcore** [comment]
Thanks @albanD, using `torch.set_num_threads()` makes a huge difference on the AMD machine! Somewhat unbelievably, calling `torch.set_num_threads()` makes a huge difference even if I don't actually change the number of threads.

I have also heard that certain kernels are implemented for Intel CPUs but not AMD CPUs, but setting the number of threads seems to be a good solution. Thank you!
