### ISSUE TITLE
code example of TORCH.USE_DETERMINISTIC_ALGORITHMS documentation is outdated

### ISSUE THREAD

**Issue by yuguo68** [pytorch/pytorch#81645]
### 📚 The doc issue

[TORCH.USE_DETERMINISTIC_ALGORITHMS](https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms)

the code example says `index_copy` and `index_add_cuda` do not have a deterministic implementation and will error out under deterministic mode, whereas in the same doc page it says both index_copy and index_add should have deterministic implementation. 

### Suggest a potential alternative/fix

update the code example to use operators that do not have deterministic implementation to illustrate the error out case. 

cc @svekars @holly1238 @mruberry @kurtamohler

**Comment by soulitzer** [comment]
Good catch, we would accept a PR to fix this.
