### ISSUE TITLE
Runtime error using nearest neighbour upsampling on tensor with channels-last memory layout

### ISSUE THREAD

**Issue by pcuenca** [pytorch/pytorch#81665]
### 🐛 Describe the bug

`torch.nn.functional.interpolate` fails with a `RuntimeError` when the following conditions are met:
- The input tensor uses the `channels_last` memory format.
- The input shape is larger than a certain threshold.

The following code works fine, producing a tensor with the expected shape `[31, 64, 1024, 1024]`:

```python
x = torch.rand((31, 64, 512, 512)).cuda().to(memory_format=torch.channels_last)
torch.nn.functional.interpolate(x, scale_factor=2, mode='nearest').shape
```
```
torch.Size([31, 64, 1024, 1024])
```

However, when the input batch dimension is `32` or larger, it fails:

```python
x = torch.rand((32, 64, 512, 512)).cuda().to(memory_format=torch.channels_last)
torch.nn.functional.interpolate(x, scale_factor=2, mode='nearest').shape
```

```
RuntimeError: upsample_nearest_nhwc only supports output tensors with less than INT_MAX elements
```

If the memory layout is **contiguous** rather than channels last, it works fine too:
```python
x = torch.rand((32, 64, 512, 512)).cuda()
torch.nn.functional.interpolate(x, scale_factor=2, mode='nearest').shape
```
```
torch.Size([32, 64, 1024, 1024])
```

The error is raised [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/UpSampleNearest2d.cu#L245). I'm not sure about the details, but I think a potential workaround could be to automatically revert to contiguous format, rather than failing.

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-91-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchvision==0.11.2+cu113
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] torchvision               0.11.2+cu113             pypi_0    pypi

----

I was using the RTX 3090 in this test. I have observed the same behaviour using other cards (RTX A6000, for instance) in other systems running different versions of Python, PyTorch and OS. 

cc @ezyang @gchanan @zou3519 @ngimel @VitalyFedyunin @jamesr66a @csarofeen @ptrblck @xwang233

**Comment by xwang233** [comment]
Thank you for raising this issue. We can probably add a `index_t` template function with `int64_t` indexing here with large tensors. https://github.com/pytorch/pytorch/blob/35d4a805ebc3b6eca1bafb2d332dffa8d0c1fc54/aten/src/ATen/native/cuda/UpSampleNearest2d.cu#L83-L95

**Comment by pcuenca** [comment]
Sounds great! Is there anything I can do to help?

**Comment by NouamaneTazi** [comment]
Any updates on this? 👀

**Comment by rtaori** [comment]
+1 have run into this issue as well!

**Comment by hadaev8** [comment]
Same here

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/87901 
Not a regression, if we are doing 1.13.1 tentatively we should pick this one fix into the branch

**Comment by yyt-2378** [comment]
same here

**Comment by gchhablani** [comment]
@malfet I am running into the same issue with PyTorch 1.12 but with Bilinear upsampling.

**Comment by ptrblck** [comment]
@gchhablani Update to the latest stable or nightly release as the fix seems to be in 1.13.1+.

**Comment by Parskatt** [comment]
I seem to still have this issue on pytorch 2.0.1, not sure how :D
Also, seem unable to reproduce it on other machines so I just added a .contiguous() in the interpolate as a workaround.

**Comment by Parskatt** [comment]
Probably because it converts the format to bchw internally. Also the related pull request only fixed nearest neighbour, but doesnt fix bilinear etc. Should be the same for them though.

**Comment by cjissmart** [comment]
> Probably because it converts the format to bchw internally. Also the related pull request only fixed nearest neighbour, but doesnt fix bilinear etc. Should be the same for them though.

Still doesnt fix bilinear.

**Comment by esdrascosta** [comment]
@Parskatt @cjissmart  yes, confirmed bilinear was never covered here, `channels_last` + `mode='bilinear'` still blows up with `invalid configuration argument` past 2**31 output elements. I opened #185788 to handle the bilinear path the same way (templated index type, `canUse32BitIndexMath` dispatch, small tensors stay on the 32-bit fast path). Let me know what you all think!
