### ISSUE TITLE
Typo in quantization documentation

### ISSUE THREAD

**Issue by zaouk** [pytorch/pytorch#81686]
### 📚 The doc issue

Within https://pytorch.org/docs/stable/quantization.html#quantized-tensor under quantization_parameters, there's a typo: it's written twice `per_tensor_affine_quantization`. While the first time it is correct, the second time it should be `per_channel_affine_quantization`.

### Suggest a potential alternative/fix

I made a fix for this in this [commit](https://github.com/zaouk/pytorch/commit/606e2a0c61e0b162053b463ec5e0212a705150a4)

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
thanks for the fix!
