### ISSUE TITLE
Shape inference of custom_domain::custom_op is missing despite setting type and shape via `setType()`

### ISSUE THREAD

**Issue by Daniel-Ehrhardt** [pytorch/pytorch#81693]
### 🐛 Describe the bug

It seems like setting type and shape information by invoking `g.op(...).setType()` inside the symbolic function is _not sufficient_ to make shape inference work for custom operators defined inside a custom ONNX domain.

I followed [this tutorial](https://pytorch.org/tutorials/advanced/cpp_extension.html#writing-a-mixed-c-cuda-extension) to implement a custom operator in C++ and CUDA that can be invoked through a pybinding. On the Python side, there exists a functional wrapper that contains the symbolic function which is responsible for the ONNX export, following https://pytorch.org/docs/1.12/onnx.html#pythonop-symbolic. This function looks like this:

```python
def symbolic_custom_op(...):
    output_shape =  ... # shape calculation

    return g.op(
        f"custom_domain::custom_op",
        inputs,
        b,
        c,
        custom_attr_i=custom_attr,
    ).setType(inputs.type().with_dtype(torch.float32).with_sizes(output_shape))

...

# Registration of symbolic function
from torch.onnx import register_custom_op_symbolic
register_custom_op_symbolic("prim::PythonOp", symbolic_custom_op, 1)
```

Despite following all the instructions, shape inference warnings still appear during ONNX export and no shape information is present in the resulting ONNX graph.

```python-traceback
WARNING: The shape inference of custom_domain::custom_op type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
```

Debugging the issue revealed that the following check in `shape_type_inference.cpp` is triggering the warning:

https://github.com/pytorch/pytorch/blob/8745118ccbed89f7d08ef6ca47eb9ba41cc12ea5/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1872-L1878

One of the following three conditions needs to be fulfilled in order for the warning to disappear:
1. `inferred`: this will always be false for my `custom_op`
2. `isTypeReliableForTracer`: this depends on a hardcoded set of `domain::operator` pairs in the same file
3. `output->node()->kind().is_onnx()`: this will always be false for my `custom_op`

I found a workaround: when adding our OP `custom_domain::op_name` to the set `nodeTypeReliableForTracer`, the warning disappears and the shape information (that was calculated and set inside the symbolic function) appears in the graph.

https://github.com/pytorch/pytorch/blob/8745118ccbed89f7d08ef6ca47eb9ba41cc12ea5/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L1855

Obviously, patching this `.cpp` file is not a solution in general.
And according to [the documentation](https://pytorch.org/docs/stable/onnx.html#pythonop-symbolic), this should not be required at all.

### Versions

* 1.10.2 
* 1.12.0
* 1.14.0.dev20221024+cu116

**Comment by justinchuby** [comment]
cc @jcwchen @BowenBao

**Comment by jcwchen** [comment]
I don't have much context about this topic, but it seems to me there is no document for it yet: https://github.com/pytorch/pytorch/issues/73871.

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

**Comment by josh-gleason** [comment]
Not sure I understand why this issue was closed. Is a fix not planned? This bug is still present in the latest pytorch-preview (1.14.0.dev20221024+cu116).

**Comment by justinchuby** [comment]
Thanks for confirming the issue still applies to preview. Reopening.

**Comment by andrei-stoian-zama** [comment]
We're using custom ONNX ops in pytorch through [brevitas](https://github.com/Xilinx/brevitas/) and we'd be very interested in a fix.

**Comment by lix19937** [comment]
https://github.com/microsoft/onnxruntime/blob/e788cc2a2370946977b91b2456166d466df4d14a/orttraining/orttraining/python/training/ortmodule/_custom_op_symbolic_registry.py#L73
