### ISSUE TITLE
PyTorch 1.12 already initializes CUDA with `import torch`

### ISSUE THREAD

**Issue by TE-StefanUhlich** [pytorch/pytorch#81758]
### 🐛 Describe the bug

The following code worked with PyTorch 1.11 but now yields a RuntimeError with PyTorch 1.12:

```python
from multiprocessing import Process
import torch

print(torch.__version__)

def f():
    torch.cuda.set_device(0)

p = Process(target=f)
p.start()
p.join()
```

**Output for PyTorch 1.11**
```
1.11.0
```

**Output for PyTorch 1.12**
```
1.12.0
Process Process-1:
Traceback (most recent call last):
  File "/disk1/deuhlics/Ana3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/disk1/deuhlics/Ana3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/disk1/deuhlics/test_init.py", line 7, in f
    torch.cuda.set_device(0)
  File "/disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 314, in set_device
    torch._C._cuda_setDevice(device)
  File "/disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 207, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

From looking at the output of running the above script with `python -vvv` I have the feeling that CUDA already gets initialized due to the import of `torch.amp`:
```bash
...
import 'torch.amp.autocast_mode' # <_frozen_importlib_external.SourceFileLoader object at 0x1496121e9be0>
import 'torch.amp' # <_frozen_importlib_external.SourceFileLoader object at 0x1496121e9100>
# /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__pycache__/__init__.cpython-39.pyc matches /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__init__.py
# code object from '/disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__pycache__/__init__.cpython-39.pyc'
# trying /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/_utils.cpython-39-x86_64-linux-gnu.so
# trying /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/_utils.abi3.so
# trying /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/_utils.so
# trying /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/_utils.py
# /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__pycache__/_utils.cpython-39.pyc matches /disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/_utils.py
# code object from '/disk1/deuhlics/Ana3/lib/python3.9/site-packages/torch/cuda/__pycache__/_utils.cpython-39.pyc'
...
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: NVIDIA TITAN X (Pascal)
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX TITAN X
GPU 3: NVIDIA TITAN X (Pascal)

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchinfo==1.7.0
[pip3] torchvision==0.13.0
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch                   1.12.0          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.0               py39_cu113    pytorch
[conda] torchinfo                 1.7.0                    pypi_0    pypi
[conda] torchvision               0.13.0               py39_cu113    pytorch
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by zou3519** [comment]
This is a duplicate of https://github.com/pytorch/pytorch/issues/80876; we've fixed this in https://github.com/pytorch/pytorch/pull/80899 and https://github.com/pytorch/pytorch/pull/80912. The fix will be in the next release of PyTorch.

**Comment by TE-StefanUhlich** [comment]
Thanks a lot @zou3519 for your quick answer - I just checked with the latest PyTorch nightly and the script is working fine again:

**PyTorch nightly**
```
1.13.0.dev20220720+cu113
```

Hence, this issue can be closed.

**Comment by piotrm-realm** [comment]
For anyone seeing this again in much newer pytorch in 2026 when dealing with fork/spawn; take a look at https://docs.pytorch.org/docs/stable/generated/torch.cuda.is_available.html and the env variable mentioned there.
