### ISSUE TITLE
pytorch conda repo broke today

### ISSUE THREAD

**Issue by divideconcept** [pytorch/pytorch#81760]
### 🐛 Describe the bug

Since today it's no longer possible to install pytorch using conda.
I'm installing pytorch almost every day on multiple machines using conda and a couple hours ago it stopped working.

`conda install -y pytorch torchvision torchaudio torchtext -c pytorch -k`

gives the following errors:

```
Downloading and Extracting Packages
pytorch-mutex-1.0    | 3 KB      |                                                                              |   0%
pytorch-1.12.0       | 1.19 GB   |                                                                              |   0%

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
Elapsed: 00:00.435837

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/win-64/pytorch-1.12.0-py3.9_cuda11.3_cudnn8_0.tar.bz2>
Elapsed: 00:00.085034

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```
It happens on all platforms (Windows/macOS/Linux).

Opening one of these links give the following xml data:
```
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>60</X-Amz-Expires>
<Expires>2022-07-20T11:36:02Z</Expires>
<ServerTime>2022-07-20T11:55:47Z</ServerTime>
<RequestId>87CJV79FMQCZW8QC</RequestId>
<HostId>afF/b8QnRCMaIJORa01QgpxxMEvJGrF0BY4jYiMi88MfpKy+LHr8+hBtipM008oKDMsTqYnz/PE=</HostId>
</Error>
```
Which, combined with the url which converts to an amazonaws url, seems to point to an AWS issue.

### Versions

Pytorch 1.12, latest conda

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by stewartbourke487** [comment]
Just to confirm I am also seeing the same issue trying to conda install cpu-only version of pytorch for windows from the pytorch channel:

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/win-64/pytorch-1.12.0-py3.9_cpu_0.tar.bz2>
Elapsed: 00:00.469780

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/cpuonly-2.0-0.tar.bz2>
Elapsed: 00:00.105516

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by Rm1n90** [comment]
Same happening to me!!! just to confirm :)

**Comment by Auth0rM0rgan** [comment]
Same, tried 20 times and failed and still not working :|

**Comment by imatiach-msft** [comment]
Same happening to all of our builds as well :(
https://github.com/microsoft/responsible-ai-toolbox
Example failing build:
https://github.com/microsoft/responsible-ai-toolbox/runs/7430426871?check_suite_focus=true

**Comment by lukeogg** [comment]
I suspect this has something to do with it: https://www.cloudflarestatus.com/incidents/fk7vpl3spf5x

**Comment by panki27** [comment]
Installations via `pip3` also seem to be affected. I'm following the [install instructions](https://pytorch.org/get-started/locally/) for Linux with CPU.

```
$ python3 --version
Python 3.7.3
$ pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu                                                           [1] Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu                                                                                                           Collecting torch                                                                                                                                                                              Using cached https://download.pytorch.org/whl/cpu/torch-1.12.0%2Bcpu-cp37-cp37m-linux_x86_64.whl                                                                                          Collecting torchvision                                                                                                                                                                        Using cached https://download.pytorch.org/whl/cpu/torchvision-0.13.0%2Bcpu-cp37-cp37m-linux_x86_64.whl                                                                                    Collecting torchaudio                                                                                                                                                                         Using cached https://download.pytorch.org/whl/cpu/torchaudio-0.12.0%2Bcpu-cp37-cp37m-linux_x86_64.whl                                                                                     Collecting typing-extensions (from torch)                                                                                                                                                   Could not install packages due to an EnvironmentError: 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/cpu/typing-extensions/
```

Looking at https://download.pytorch.org/whl/cpu/typing-extensions/ in a browser shows a weird 403 complaining about an "Error from cloudfront":

```
HTTP/2 403 Forbidden
content-type: application/xml
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 5bbaa27b453dc834289b91c14bbb4934.cloudfront.net (CloudFront)
x-amz-cf-pop: DUS51-P1
x-amz-cf-id: <blanked>
X-Firefox-Spdy: h2
```

**Comment by lukeogg** [comment]
That one's Amazon... Not sure what is going on...

**Comment by divideconcept** [comment]
> I suspect this has something to do with it: https://www.cloudflarestatus.com/incidents/fk7vpl3spf5x

Unfortunately no, incident close on Cloudflare but problem still remains with Pytorch...

**Comment by ankit255** [comment]
I just want to say how pathetic and egregiously wrong it is that pytorch cannot maintain a simple bloody mirror for its packages in case of a little network brownout like this. It's ridiculous and laughable. Useless company behind it and just even worse that it's been more than a day that this issue hasn't been mitigated through a mirror if not completely resolved. Shame on you PyTorch devs and organisation.

**Comment by AmishWarlord** [comment]
I get the same error with conda, but FYI to anyone who's lost out there, you can still use pip if conda isn't working.
https://pytorch.org/get-started/locally/
here's what I used today. Note: this command uses CUDA 11.3: 
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

**Comment by vietvo89** [comment]
Hi all

I hit the same issue. But I confirmed that @AmishWarlord is right.  I have just installed pytorch using pip successfully.

**Comment by jeongwhanchoi** [comment]
What happened on a Conda repo today? I get the same error here.

```
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
Elapsed: 00:00.827471

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by divideconcept** [comment]
All Cloudflare issues are now resolved and it seems conda pytorch is working again !

**Comment by jeongwhanchoi** [comment]
> All Cloudflare issues are now resolved and it seems conda pytorch is working again !

I've checked conda PyTorch works well.
