### ISSUE TITLE
Documentation on c10d is expected

### ISSUE THREAD

**Issue by zclyne** [pytorch/pytorch#81769]
### 📚 The doc issue

Hi, I'm trying to deploy elastic distributed pytorch training jobs on my k8s cluster and I see that c10d is the recommended backend store of pytorch-elastic. I ran into some issues about running a PytorchJob with [kubeflow/training-operator](https://github.com/kubeflow/training-operator) while using c10d store so I tried to figure out how c10d works. However, I failed to find any documentation about c10d online. Could anybody provides me the doc on c10d (especially c10d TCPStore) if there is one? Thanks!

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by mrshenli** [comment]
Hey @zclyne, this is the doc for c10d TCPStore: https://pytorch.org/docs/stable/distributed.html#torch.distributed.TCPStore

cc @d4l3k @H-Huang

**Comment by zclyne** [comment]
Thank you! I'll check it out.

**Comment by d4l3k** [comment]
@zclyne have you looked at https://pytorch.org/torchx/latest/schedulers/kubernetes.html for usage with Kubernetes? That's the new recommended way to launch pytorch on Kubernetes and should work out of the box if you have Volcano installed

**Comment by zclyne** [comment]
Thank you for your recommendation. Actually our product is using kubeflow/training-operator to manage pytorch training jobs but it's really good to have a new recommended way from the community. I'll take a look. Thanks!

**Comment by mrshenli** [comment]
Looks like this is resolved, closing this issue. Please feel free to reopen if necessary.
