### ISSUE TITLE
Improved sorting of the CI workflows in a PR

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#81810]
### 🚀 The feature, motivation and pitch

Ideally, workflows in the signalbox should be displayed in this order:

- Failed workflows
- In progress workflows
- Queued workflows
- Skipped workflows
- Successful workflows

That would make it really easy to see the most actionable stuff, especially when some builds have hundreds of workflows

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
We used to have a Google Chrome extension that would do this sorting for, but it was fragile as it was dependent on GitHub.

Workaround is to use HUD PR view--though the **action item** here would be to add queued + skipped order.

**Comment by ZainRizvi** [comment]
CI can't be sorted in the PR itself unfortunately, but they are now sorted in HUD's commit view
