### ISSUE TITLE
Dr. CI message up top feels ignorable

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#81811]
### 🚀 The feature, motivation and pitch

I don’t have an ideal solution to this, but the post with Dr. CI output at the top seemed very stale (it wasn’t actually stale, but it felt that way since it was at the top of the comment train and I didn’t realize it was being auto-updated). 

Would it be possible to add a message to the signal box (which gives a status of the jobs) saying to look at the Dr. CI comment up top for more detailed insights into their workflows?

### Alternatives

Alternate option: Delete the stale Dr. CI messages and keep reposting them as the latest comment when a change happens, so that it stays at the bottom and next to the signalbox

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
I actually like it being at the top cuz when I open it, I wanna see the summary right away, but the ignorability is a true problem.

Solutions:
- redirect people to the top with job summaries

**Comment by janeyx99** [comment]
Moving to backlog because we need to explore action items.

**Comment by ZainRizvi** [comment]
Closing this as a task. To be eventually replaced with actual action items if/when we have them
