### ISSUE TITLE
unable to install from conda on lts ubuntu server 

### ISSUE THREAD

**Issue by kurtjcu** [pytorch/pytorch#81823]
### 🐛 Describe the bug

unable to install using the conda install for stable pytorch in cudatoolkit 11+  on a fresh ubuntu server install. pytorch and torchvision packages are forbidden 

### Versions

latest LTS ubuntu server

**Comment by kit1980** [comment]
This is a Conda issue - https://github.com/conda/conda/issues/11638
Closing this as a duplicate of https://github.com/pytorch/pytorch/issues/81760
