### ISSUE TITLE
Trigger pagers after nightly builds fail two nights in a row

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#81829]
### 🐛 Describe the bug

We've had multiple weeks recently where the nightly builds remained broken for 4+ days just because no one noticed they were red.

We've discussed having pagers auto fire the morning after a nightly build fails, but as per @zengk95 our pagers don't have a "business hours only" mode.

So I'm proposing an alternate approach: 

## Proposal: We break the nightly alerting into two alerts

Alert 1 will trigger immediately whenever a nightly breaks and will send an email to the oncall. 

Alert 2 will trigger once the nightly breaks two nights in a row and will *page* the oncall. Most likely at night.

## Expectations
Hopefully the on call notices the broken build in their their email on the morning after the first break.  They'll be expected to fix the bug the same day _and trigger a new nightly builds with their fix_

If the build break was caused by flakiness, then they should still trigger a new nightly build.

Why the new nightly build? 
1. It'll verify that the build is indeed fixed
2. Having a successful nightly build will protect the oncall from getting paged the next night if a _new_ issue causes the following nightly build to fail as well

Now, if that day the oncall fails to notice the broken build email in their inbox and the build fails again the next night, they will get paged and be woken up in the middle of the night. However, they'll only be expected to ack the page, go back to sleep, and then fix the build the next morning.

### Versions

n/a

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Done!

**Comment by janeyx99** [comment]
It will now page according to on-call preferences after 2 nights in a row.
