### ISSUE TITLE
[ONNX] When converting a Pytorch model (which contains a constant) to onnx, constants are converted with double type

### ISSUE THREAD

**Issue by EmreOzkose** [pytorch/pytorch#81869]
### 🐛 Describe the bug

When I convert a Pytorch model to onnx where model contains a constant, constants are converted with double type. Although exporting is done without a problem, I cannot load it with onnxruntime. 

```python
class ExampleModule(nn.Module):
    def __init__(self) -> None:
        super().__init__()

    def forward(self, x: torch.Tensor):
        x = x - 1.0
        return x


example_module = ExampleModule()
example_in = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
example_out = example_module(example_in)

torch.onnx.export(example_module,
                  args=(example_in),
                  f="example_module.onnx",
                  input_names=["x"],
                  output_names=["output1"],
                  opset_version = 11,
                  dynamic_axes={
                      'x': {0 : 'batch_size'},
                      'output1': {0 : 'batch_size'},
                  },
                  verbose=True)

import onnx
import numpy as np
import onnxruntime as ort

model = onnx.load("example_module.onnx")
onnx.checker.check_model(model)

ort_session = ort.InferenceSession("example_module.onnx")

outputs = ort_session.run(
    None,
    {
        "x": example_in.numpy().astype(np.float32),
    },
)
```

Error:
```
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
Input In [6], in <cell line: 8>()
      5 model = onnx.load("example_module.onnx")
      6 onnx.checker.check_model(model)
----> 8 ort_session = ort.InferenceSession("example_module.onnx")
     10 outputs = ort_session.run(
     11     None,
     12     {
     13         "x": example_in.numpy().astype(np.float32),
     14     },
     15 )
     16 print(example_in)

File ~/anaconda3/envs/k2_sherpa/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:335, in InferenceSession.__init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    332 disabled_optimizers = kwargs['disabled_optimizers'] if 'disabled_optimizers' in kwargs else None
    334 try:
--> 335     self._create_inference_session(providers, provider_options, disabled_optimizers)
    336 except ValueError:
    337     if self._enable_fallback:

File ~/anaconda3/envs/k2_sherpa/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:370, in InferenceSession._create_inference_session(self, providers, provider_options, disabled_optimizers)
    368 session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    369 if self._model_path:
--> 370     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    371 else:
    372     sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from example_module.onnx failed:Type Error: Type parameter (T) of Optype (Sub) bound to different types (tensor(float) and tensor(double) in node (Sub_1).
```

I found 2 similar issues : [1](https://github.com/pytorch/pytorch/issues/20941) , [2](https://github.com/pytorch/pytorch/issues/68598), however bug still remains. 

One workaround is changing all constants like this:
```
x = x - 1.0 to  x = x - torch.ones((1),  dtype=torch.float32)
```

However converting complicated models can be difficult with this workaround.

### Versions

Collecting environment information...
PyTorch version: 1.10.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.23.2
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-124-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.4.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.0
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.17.dev20220718+cuda11.1.torch1.10.1
[pip3] numpy==1.22.4
[pip3] torch==1.10.1+cu111
[pip3] torchaudio==0.10.1+cu111
[pip3] torchvision==0.11.2+cu111
[conda] k2                        1.17.dev20220718+cuda11.1.torch1.10.1          pypi_0    pypi
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.10.1+cu111             pypi_0    pypi
[conda] torchaudio                0.10.1+cu111             pypi_0    pypi
[conda] torchvision               0.11.2+cu111             pypi_0    pypi

**Comment by AllenTiTaiWang** [comment]
Hi,

I used nightly pytorch and onnxruntime, and didn't get any error. Could you try with the latest version?

**Comment by EmreOzkose** [comment]
Yes, I didn't reproduce with the latest version, thank you.
