### ISSUE TITLE
[ONNX] `Unfold` operator unsupported when exporting to ONNX

### ISSUE THREAD

**Issue by mikel-brostrom** [pytorch/pytorch#81871]
### 🐛 Describe the bug

When running

```python
torch.onnx.export(
            model,
            (im, im),
            'wow.onnx',
            verbose=True,
            opset_version=opset,
            input_names=['t0', 't1'],
            output_names=['output'])`
```

on my model I get:

```bash
Unsupported: ONNX export of operator Unfold, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

Any idea which operation Unfold could be replaced by so that the export succeeds?

### Versions

yTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.0 (default, Dec  9 2021, 17:53:27)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1046-azure-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4

Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.6.5
[pip3] torch==1.12.0
[pip3] torch-model-archiver==0.6.0
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.13.0
[conda] Could not collect

**Comment by AllenTiTaiWang** [comment]
Hi,
It's hard to tell the issue of this here. It seems like shape inference might also have something to do with this, so if you could provide a small repro that would be great!

A little more info about onnx support if you are interested:
https://github.com/onnx/onnx/blob/main/docs/Operators.md

**Comment by thiagocrepaldi** [comment]
Although `Unfold` is not supported yet, `Fold` will be soon: https://github.com/onnx/onnx/pull/3948 and https://github.com/microsoft/onnxruntime/pull/12311/ must be merged first, but then the PyTorch ONNX converter can follow and add it too.

For the `Fold` case, which model are you working on? Is it a popular one with many users? The more popular a model is, the better changes are we get an approval for new operators in ONNX to implement this.

**Comment by thiagocrepaldi** [comment]
ANswering your question, you can implement `Im2Col` using python instead of using `torch.nn.Unfold`. `Fold` is the `col2im` operator, which is the opposite of ìm2col`

**Comment by mikel-brostrom** [comment]
Thank you for the suggestion @thiagocrepaldi!

**Comment by justinchuby** [comment]
We’ve gone ahead and closed this issue because it is **stale**.

If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

**Comment by zinaiyihua** [comment]
> Thank you for the suggestion @thiagocrepaldi!

May I ask how you solved the problem?
