### ISSUE TITLE
Hardlink to macos version of Python on https://pytorch.org/get-started/locally/

### ISSUE THREAD

**Issue by mattpopovich** [pytorch/pytorch#81913]
### 📚 The doc issue

In the ["Installing on Linux" Python section](https://pytorch.org/get-started/locally/#linux-python) (select "Linux" for "Your OS" in the top menu) of the getting started locally guide, there is a link to the Python website that links to https://www.python.org/downloads/mac-osx/

### Suggest a potential alternative/fix

I believe it should either link to https://www.python.org/downloads/ (which is the Linux/UNIX download link) or to the overarching https://www.python.org/downloads/ page. 

I'd happily make a PR but I couldn't find https://pytorch.org/get-started/locally/ on GitHub.

**Comment by kit1980** [comment]
FYI, the repo for the website is https://github.com/pytorch/pytorch.github.io

**Comment by mattpopovich** [comment]
@kit1980 thank you! I will move my issue over there.
