### ISSUE TITLE
Build Error On Ubuntu16 

### ISSUE THREAD

**Issue by aliceyayunji** [pytorch/pytorch#8193]
No conda 

make error:
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::EnforceNotMet::AppendMessage(std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::vector<double, std::allocator<double> > caffe2::ArgumentHelper::GetRepeatedArgument<double>(std::string const&, std::vector<double, std::allocator<double> > const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `gloo::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::detail::extractNetDef(caffe2::OperatorDef const&, std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::Workspace::CreateBlob(std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `long caffe2::TypeMeta::Id<std::string>()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::gRegisteredTypeNames()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `long caffe2::ArgumentHelper::GetSingleArgument<long>(std::string const&, long const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GetEmptyStringAlreadyInited()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::detail::extractLinks(caffe2::OperatorBase*, std::string const&, std::string const&, std::string const&, std::string const&, std::vector<caffe2::detail::Link, std::allocator<caffe2::detail::Link> >*)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `bool caffe2::ArgumentHelper::GetSingleArgument<bool>(std::string const&, bool const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::OpSchema::SetDoc(std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::gTypeNames()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::StringToPadMode(std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `double caffe2::ArgumentHelper::GetSingleArgument<double>(std::string const&, double const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&, void const*)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `bool caffe2::ArgumentHelper::HasSingleArgumentOfType<int>(std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `bool caffe2::ArgumentHelper::HasSingleArgumentOfType<caffe2::NetDef>(std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `unsigned short caffe2::ArgumentHelper::GetSingleArgument<unsigned short>(std::string const&, unsigned short const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `int caffe2::ArgumentHelper::GetSingleArgument<int>(std::string const&, int const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `bool caffe2::ArgumentHelper::HasSingleArgumentOfType<float>(std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::ArgumentHelper::HasArgument(std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::OpSchemaRegistry::map()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::Workspace::GetBlob(std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `short caffe2::ArgumentHelper::GetSingleArgument<short>(std::string const&, short const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::unique_ptr<caffe2::RecurrentNetworkExecutorBase, std::default_delete<caffe2::RecurrentNetworkExecutorBase> > caffe2::createRNNExecutor<caffe2::CUDAContext>(caffe2::NetDef const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >&, std::string, caffe2::ArgumentHelper)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::vector<bool, std::allocator<bool> > caffe2::ArgumentHelper::GetRepeatedArgument<bool>(std::string const&, std::vector<bool, std::allocator<bool> > const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `bool caffe2::ArgumentHelper::HasSingleArgumentOfType<long>(std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::detail::GetRecurrentMapping(std::vector<caffe2::detail::Link, std::allocator<caffe2::detail::Link> > const&, bool)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::TensorPrinter::TensorPrinter(std::string const&, std::string const&, int)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `signed char caffe2::ArgumentHelper::GetSingleArgument<signed char>(std::string const&, signed char const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::HasOutput(caffe2::OperatorDef const&, std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::ProtoDebugString(google::protobuf::Message const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GradientRegistry()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `float caffe2::ArgumentHelper::GetSingleArgument<float>(std::string const&, float const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `gloo::getCudaPCIBusID[abi:cxx11](int)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `unsigned char caffe2::ArgumentHelper::GetSingleArgument<unsigned char>(std::string const&, unsigned char const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::vector<std::string, std::allocator<std::string> > caffe2::ArgumentHelper::GetRepeatedArgument<std::string>(std::string const&, std::vector<std::string, std::allocator<std::string> > const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::CUDAOperatorRegistry()'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::vector<float, std::allocator<float> > caffe2::ArgumentHelper::GetRepeatedArgument<float>(std::string const&, std::vector<float, std::allocator<float> > const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `bool caffe2::ArgumentHelper::HasSingleArgumentOfType<std::string>(std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `google::protobuf::internal::ParseNamedEnum(google::protobuf::EnumDescriptor const*, std::string const&, int*)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::vector<long, std::allocator<long> > caffe2::ArgumentHelper::GetRepeatedArgument<long>(std::string const&, std::vector<long, std::allocator<long> > const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::detail::AddApplyLinkOps(std::vector<caffe2::detail::Link, std::allocator<caffe2::detail::Link> > const&, std::string, caffe2::DeviceOption const&, caffe2::NetDef*)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::GetArgument(caffe2::OperatorDef const&, std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::Workspace::GetNet(std::string const&)'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::string caffe2::ArgumentHelper::GetSingleArgument<std::string>(std::string const&, std::string const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `std::vector<int, std::allocator<int> > caffe2::ArgumentHelper::GetRepeatedArgument<int>(std::string const&, std::vector<int, std::allocator<int> > const&) const'
/home/pattern/install/pytorch/build/lib/libcaffe2_gpu.so: undefined reference to `caffe2::Demangle(char const*)'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/event_gpu_test.dir/build.make:110: recipe for target 'bin/event_gpu_test' failed
make[2]: *** [bin/event_gpu_test] Error 1
CMakeFiles/Makefile2:1949: recipe for target 'caffe2/CMakeFiles/event_gpu_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/event_gpu_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by aliceyayunji** [comment]
CMake List : 
pattern@ubuntu40:~/install/pytorch/build$ cmake ..
-- Does not need to define long separately.
-- std::exception_ptr is supported.
-- NUMA is available
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/home/pattern/install/pytorch/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- The BLAS backend of choice:Eigen
-- Brace yourself, we are building NNPACK
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Caffe2: Cannot find gflags automatically. Using legacy find.
-- Caffe2: Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Failed to find LLVM FileCheck
-- git Version: v0.0.0-dirty
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- Found Numa  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnuma.so)
-- OpenCV found (/usr/local/share/OpenCV)
-- Found system Eigen at /usr/local/include/eigen3
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.12", minimum required is "2.7") 
-- NumPy ver. 1.13.3 found (include: /usr/local/lib/python2.7/dist-packages/numpy/core/include)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
-- Caffe2: CUDA detected: 8.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 8.0
-- Found cuDNN: v7.0.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Set CUDA arch from CUDA_ARCH_NAME: Auto
-- Automatic GPU detection failed. Building for all known architectures.
-- Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61
-- Could NOT find NCCL (missing: NCCL_INCLUDE_DIRS NCCL_LIBRARIES) 
-- Could NOT find CUB (missing: CUB_INCLUDE_DIR) 
-- Could NOT find Gloo (missing: Gloo_LIBRARY) 
-- CUDA detected: 8.0
-- Found libcuda: /usr/local/cuda-8.0/lib64/stubs/libcuda.so
-- Found libnvrtc: /usr/local/cuda-8.0/lib64/libnvrtc.so
-- GCC 5.4.1: Adding gcc and gcc_s libs to link line
-- Include NCCL operators
-- Excluding ideep operators as we are not using ideep
-- Including image processing operators
-- Excluding video processing operators due to no opencv
-- Excluding mkl operators as we are not using mkl
-- MPI operators skipped due to no MPI support
-- Include Observer library
-- Using lib/python2.7/dist-packages as python relative installation path
-- Automatically generating missing __init__.py files.
-- A previous caffe2 cmake run already created the __init__.py files.
CMake Warning at CMakeLists.txt:341 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.  Other settings may generate files that are not well
  tested.


-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.1.11-8735-ga6305ea-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.1
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-unused-parameter -Wno-unknown-warning-option -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-variable -Wno-unused-function
--   Build type            : Release
--   Compile definitions   : 
-- 
--   BUILD_CAFFE2          : ON
--   BUILD_ATEN            : OFF
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 2.7.12
--     Python includes     : /usr/include/python2.7
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : ON
--   USE_ASAN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     USE_CUDNN           : ON
--     CUDA version        : 8.0
--     cuDNN version       : 7.0.5
--     CUDA root directory : /usr/local/cuda
--     CUDA library        : /usr/local/cuda-8.0/lib64/stubs/libcuda.so
--     cudart library      : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
--     cufft library       : /usr/local/cuda/lib64/libcufft.so
--     curand library      : /usr/local/cuda/lib64/libcurand.so
--     cuDNN library       : /usr/local/cuda/lib64/libcudnn.so
--     nvrtc               : /usr/local/cuda-8.0/lib64/libnvrtc.so
--     CUDA include path   : /usr/local/cuda/include
--     NVCC executable     : /usr/local/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--     USE_GLOO_IBVERBS    : OFF
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               : 
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : OFF
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 3.4.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pattern/install/pytorch/build

**Comment by aliceyayunji** [comment]
Protobuf Info: 
 
find / -name libproto* 2>/dev/null
/var/cache/apt/archives/libprotobuf-dev_2.6.1-1.3_amd64.deb
/var/cache/apt/archives/libprotobuf9v5_2.6.1-1.3_amd64.deb
/var/cache/apt/archives/libprotobuf-lite9v5_2.6.1-1.3_amd64.deb
/var/cache/apt/archives/libprotoc9v5_2.6.1-1.3_amd64.deb
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.triggers
/var/lib/dpkg/info/libprotobuf-dev:amd64.md5sums
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.shlibs
/var/lib/dpkg/info/libprotobuf9v5:amd64.shlibs
/var/lib/dpkg/info/libprotobuf9v5:amd64.list
/var/lib/dpkg/info/libprotoc9v5:amd64.shlibs
/var/lib/dpkg/info/libprotobuf-dev:amd64.list
/var/lib/dpkg/info/libprotoc9v5:amd64.md5sums
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.list
/var/lib/dpkg/info/libprotobuf9v5:amd64.md5sums
/var/lib/dpkg/info/libprotobuf-lite9v5:amd64.md5sums
/var/lib/dpkg/info/libprotobuf9v5:amd64.triggers
/var/lib/dpkg/info/libprotoc9v5:amd64.list
/var/lib/dpkg/info/libprotoc9v5:amd64.triggers
/home/pattern/install/pytorch/third_party/protobuf/cmake/libprotobuf.cmake
/home/pattern/install/pytorch/third_party/protobuf/cmake/libprotobuf-lite.cmake
/home/pattern/install/pytorch/third_party/protobuf/cmake/libprotoc.cmake
/home/pattern/install/pytorch/third_party/protobuf/src/libprotobuf-lite.map
/home/pattern/install/pytorch/third_party/protobuf/src/libprotoc.map
/home/pattern/install/pytorch/third_party/protobuf/src/libprotobuf.map
/home/pattern/install/pytorch/build/third_party/protobuf/cmake/CMakeFiles/libprotoc.dir
/home/pattern/install/pytorch/build/third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir
/home/pattern/install/pytorch/build/third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir
/home/pattern/install/pytorch/build/lib/libprotoc.a
/home/pattern/install/pytorch/build/lib/libprotobuf-lite.a
/home/pattern/install/pytorch/build/lib/libprotobuf.a
/home/pattern/install/opencv/build/3rdparty/protobuf/CMakeFiles/libprotobuf.dir
/usr/local/lib/libprotobuf-lite.so.15.0.0
/usr/local/lib/libprotobuf.so.15.0.0
/usr/local/lib/libprotobuf.la
/usr/local/lib/libprotobuf-lite.so
/usr/local/lib/libprotoc.la
/usr/local/lib/libprotoc.so
/usr/local/lib/libprotoc.a
/usr/local/lib/libprotobuf.so.15
/usr/local/lib/libprotobuf-lite.a
/usr/local/lib/libprotobuf-lite.la
/usr/local/lib/libprotobuf.so
/usr/local/lib/libprotobuf.a
/usr/local/lib/libprotoc.so.15
/usr/local/lib/libprotobuf-lite.so.15
/usr/local/lib/libprotoc.so.15.0.0
/usr/share/doc/libprotoc9v5
/usr/share/doc/libprotobuf-lite9v5
/usr/share/doc/libprotobuf-dev
/usr/share/doc/libprotobuf9v5
/usr/lib/x86_64-linux-gnu/libprotoc.so.9.0.1
/usr/lib/x86_64-linux-gnu/libprotobuf.so.9.0.1
/usr/lib/x86_64-linux-gnu/libprotoc.so.9
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.a
/usr/lib/x86_64-linux-gnu/libprotobuf.so.9
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9
/usr/lib/x86_64-linux-gnu/libprotobuf.so
/usr/lib/x86_64-linux-gnu/libprotobuf.a
/usr/lib/x86_64-linux-gnu/libprotobuf-lite.so.9.0.1
/usr/lib/pulse-8.0/modules/libprotocol-simple.so
/usr/lib/pulse-8.0/modules/libprotocol-cli.so
/usr/lib/pulse-8.0/modules/libprotocol-http.so
/usr/lib/pulse-8.0/modules/libprotocol-native.so

**Comment by aliceyayunji** [comment]
build pytorch  to use caffe2, command as the tutorial: 
mkdir build & cd build
cmake ..
sudo make -j8 install 
and then the error above occur....

**Comment by pjh5** [comment]
What is the output of
gcc --version
which gcc

Have you ever changed or altered the compilers on this machine? 
Can you try this by passing the following flags to cmake?
cmake -DUSE_GLOG=OFF -DUSE_GFLAGS=OFF -DUSE_GLOO=OFF -DUSE_LEVELDB=OFF -DUSE_OPENCV=OFF -DUSE_LMDB=OFF -DUSE_NCCL=OFF -DUSE_NNPACK=OFF ..

**Comment by aliceyayunji** [comment]
It is the problem of gcc version, I reinstalled gcc to 5.4.0 and everything is OK, thanks.

**Comment by manoharvhr** [comment]
> It is the problem of gcc version, I reinstalled gcc to 5.4.0 and everything is OK, thanks.

What version were you using before
