### ISSUE TITLE
[ONNX] Handle half_to_float in aten::_log_softmax in ONNX exporter

### ISSUE THREAD

**Issue by wschin** [pytorch/pytorch#81939]
The 3rd input, `half_to_float`, of `aten::_log_softmax` is boolean variable. If `half_to_float ` is `true`, the CUDA implementation of `aten::_log_softmax` will cast inputs from float16 to float32, compute the result in float32, and store the result in float32. Other implementations (e.g., CUDNN) may throw when this flag is `true`. If `half_to_float` is `false`, no type casting happens. Exporter of `aten::_log_softmax` should consider this flag and generate different sub-graph accordingly.

**Comment by AllenTiTaiWang** [comment]
Thanks for the contribution!
