### ISSUE TITLE
[caffe2]import 'caffe2.python.caffe2_pybind11_state' error

### ISSUE THREAD

**Issue by wuxindegui** [pytorch/pytorch#8194]
## Issue description
when i transform onnx to caffe2, i meet this problem:

WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
WARNING:root:Debug message: /root/anaconda3/lib/python3.6/site-packages/caffe2-0.8.2-py3.6-linux-x86_64.egg/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev
CRITICAL:root:Cannot load caffe2.python. Error: /root/anaconda3/lib/python3.6/site-packages/caffe2-0.8.2-py3.6-linux-x86_64.egg/caffe2/python/caffe2_pybind11_state.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6google4base21CheckOpMessageBuilder9NewStringB5cxx11Ev

## Code example

import onnx
import onnx_caffe2.backend  #caused by this line,in backed.py ,'from caffe2.python import core'
import numpy as np

model = onnx.load("/home/deep/FD_onnx/super_resolution.onnx")
prepared_backend = onnx_caffe2.backend.prepare(model)
W = {model.graph.input[0].name: x.data.numpy()}
c2_out = prepared_backend.run(W)[0]
np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out, decimal=3)

## System Info

- PyTorch or Caffe2: caffe2
- How you installed PyTorch (conda, pip, source):conda
- Build command you used (if compiling from source):
- OS:linux
- Torch version:0.5
- Python version:3.6
- CUDA/cuDNN version:9.0/7.1
- GPU models and configuration:
- GCC version (if compiling from source):5.4
- CMake version:3.9.4
- Versions of any other relevant libraries:

**Comment by pjh5** [comment]
Did you install both Caffe2 and onnx from conda? Which packages did you use (conda list caffe2 and conda list onnx)?

**Comment by pjh5** [comment]
This looks like a mismatch between a google library, probably protobuf, compiled with gcc4.8 in conda-forge which onnx uses and one compiled with gcc7.2 in conda-default channels that Caffe2 uses. Can you try the caffe2-gcc4.8 package or build onnx from source? You can build onnx from source by
```
git clone https://github.com/pytorch/pytorch.git --recursive
cd pytorch
PROTOBUF_INCDIR=/path/to/anaconda/env/where/caffe2/is/installed pip install third_party/onnx

**Comment by pjh5** [comment]
Looks related to #7567

**Comment by mruberry** [comment]
Closing due to age and because PyTorch is now preferred to Caffe2. If this issue is still relevant please file a new issue.
