### ISSUE TITLE
a CUDNN issue for conv2d compilation leading to performance degradation

### ISSUE THREAD

**Issue by FindHao** [pytorch/pytorch#81940]
### 🐛 Describe the bug

batch size | cuda 11.3 cudnn 8.3.2 | cuda 11.6 cudnn8.4.1
-- | -- | --
32 | 78ms | 101ms
64 | 226ms | 191ms
2x32 | 156ms | 199ms

The above table shows our experiments on A100. We tested [timm_regnet](https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models/timm_regnet)'s inference mode with different batchsize 32 and 64. The row 2x32 means we run the core computation part twice for batchsize 32. 

In our experiments with cuda 11.3 and cudnn 8.3.2 on A100, the execution time of batchsize 64 is longer than twice executions of batchsize 32. After going through the profiling results, we think the kernel `cudnn::ops::genericTranspose_kernel` takes too much time on tranpose rather than meaningful computation which doesn't occur on batchsize 32. We know cudnn uses some heuristics methods to try to generate more efficient kernels but looks like it is not so efficient. 

When we change the env to cuda 11.6 and cudnn 8.4.1, the execution time of batchsize 32 is 1.29X longer than the result on cuda 11.3 cudnn 8.3.2. We further investigated the cause of the performance degradation and found that the latest cudnn 8.4.1genereates `(ampere_scudnn_winograd_128x128_ldg1_ldg4_relu_tile148t_nt_v1, cudnn::ops::genericTranspose_kernel)` to replace the previous combination`(cudnn::winograd_nonfused::winogradForwardData4x4, ampere_sgemm_128x128_nn, cudnn::winograd_nonfused::winogradForwardOutput4x4)` even for the exact same input. We have trimmed down the code to the following gist. 

https://gist.github.com/FindHao/ff5672d8e87ef09f6ea17dfb7844ad37

For batchsize 64, there is 1.18X speedup after upgrading to cudnn8.4.1. But it is still longer than twice execution of batchsize 32 on cudnn 8.3.2. 

#### Reproduce

To reproduce the key result that cudnn 8.4.1 generates slower kernels for batchsize 32, you can download the example in the above gist, and execute `python test_conv2d.py --bs 32`. The pytorch profiler results will be generated. 

To fully reproduce the whole results, you need to install [pytorch/benchmark](https://gist.github.com/FindHao/ff5672d8e87ef09f6ea17dfb7844ad37) and run `python3 run.py -d cuda -t eval --bs 32  timm_regnet --precision fp32` for batchsize 32 on different environments. 

### Versions

PyTorch version: 1.13.0.dev20220524+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-1024-gcp-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] botorch==0.6.4
[pip3] flowtorch==0.8
[pip3] gpytorch==1.6.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] numpyro==0.9.2
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.13.0.dev20220524+cu113
[pip3] torch-struct==0.5
[pip3] torch-tb-profiler==0.4.0
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.8.2
[pip3] torchrec-nightly==2022.4.26
[pip3] torchtext==0.13.0.dev20220524
[pip3] torchvision==0.13.0.dev20220524+cu113
[pip3] torchx-nightly==2022.5.24
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] botorch                   0.6.4                    pypi_0    pypi
[conda] flowtorch                 0.8                      pypi_0    pypi
[conda] gpytorch                  1.6.0                    pypi_0    pypi
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] numpyro                   0.9.2                    pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torch                     1.13.0.dev20220524+cu113          pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchmetrics              0.8.2                    pypi_0    pypi
[conda] torchrec-nightly          2022.4.26                pypi_0    pypi
[conda] torchtext                 0.13.0.dev20220524          pypi_0    pypi
[conda] torchvision               0.13.0.dev20220524+cu113          pypi_0    pypi
[conda] torchx-nightly            2022.5.24                pypi_0    pypi

cc @csarofeen @ptrblck @xwang233

**Comment by ngimel** [comment]
cc @ptrblck

**Comment by ptrblck** [comment]
> After going through the profiling results, we think the kernel cudnn::ops::genericTranspose_kernel takes too much time on tranpose rather than meaningful computation which doesn't occur on batchsize 32. We know cudnn uses some heuristics methods to try to generate more efficient kernels but looks like it is not so efficient.

You are right that cuDNN might prefer another memory layout (channels-last in this case) and could add transpose kernels if the end2end performance would still be better. However, if should never slow down the workload.
You might want to enable benchmarking via `torch.backends.cudnn.benchmark = True` in case you are using static input shapes so that cuDNN can profile different kernels and pick the (hopefully) fastest one.

So far I cannot reproduce the `winograd` kernels you are seeing on an A100 using cuDNN8.3.2 (I'm picking it as the baseline since the binaries are using it at the moment) to isolate the regression further.

For `--bs 32` and `--bs 64` I'm seeing:
```
     58.8        501135728       1011   495683.2   470459.0    469755    602906      51678.9  sm80_xmma_fprop_implicit_gemm_tf32f32_tf32f32_f32_nhwckrsc_nhwc_tilesize128x128x16_stage4_warpsize2…
     16.6        141372663       1011   139834.5   139679.0    137982    143166        814.4  void cudnn::ops::nchwToNhwcKernel<float, float, float, (bool)1, (bool)1, (cudnnKernelDataType_t)2>(…
     15.7        134026049       1011   132567.8   132542.0    131935    133727        292.0  void cudnn::ops::nhwcToNchwKernel<float, float, float, (bool)1, (bool)1, (cudnnKernelDataType_t)0>(…
      3.0         25632662         12  2136055.2  2014077.5   1973294   2434314     198627.2  void cudnn::ops::genericTranspose_kernel<float, float, float, (bool)1, (cudnnKernelDataType_t)0>(T3…
      3.0         25194232       1011    24920.1    24703.0     23488     28736        814.2  void tensorTransformGeneric<float, float, float, (bool)1, (bool)0, (bool)0, (cudnnKernelDataType_t)…
```
Disallowing TF32 gives:
```
     98.4       5981640135       2022   2958279.0   2980054.5   2897127   3799934     104383.5  ampere_scudnn_128x64_relu_xregs_large_nn_v1         
```
Note that I've added warmup iterations and am profiling `1000` iterations.

Did you change anything else in your environment which would explain why we are seeing different kernels?
I'm seeing my reported kernels using a source build with cuDNN 8.3.2 as well as the `torch==1.12.0+cu113` binaries.

**Comment by ptrblck** [comment]
@FindHao Could you check if you have any other `libcudnn.so` in your `LD_LIBRARY_PATH` and could be running into https://github.com/pytorch/pytorch/pull/81881?

**Comment by FindHao** [comment]
Hi @ptrblck, thanks for your reply. I use `export NVIDIA_TF32_OVERRIDE=0` to disable TF32.  The only lib in my `LD_LIBRARY_PATH ` is `/usr/local/cuda-11.3/lib64`. When I change cuda and cudnn version, I just use different ssh sessions and apply different scripts. 

I'll use your torch version and add 11 warmup iterations to profile 1000 iterations.

**Comment by FindHao** [comment]
@ptrblck Before I install a new env with torch1.12, I did some tests. Here are the following results.

**Comment by FindHao** [comment]
I tested torch1.12 with cuda11.3 and cudnn8.3.2. The nsys profiling result disabling `torch.backends.cudnn.benchmark`  is the following.
```
 Time(%)  Total Time (ns)  Instances  Average   Minimum  Maximum                                                  Name                                                
 -------  ---------------  ---------  --------  -------  -------  ----------------------------------------------------------------------------------------------------
    63.2       1030281470       2022  509535.8   484962   547329  ampere_sgemm_128x128_nn                                                                             
    17.5        285444616       2022  141169.4   134336   154528  void cudnn::winograd_nonfused::winogradForwardData4x4<float, float>(cudnn::winograd_nonfused::Winog…
    16.9        275046965       2022  136027.2   113856   163488  void cudnn::winograd_nonfused::winogradForwardOutput4x4<float, float>(cudnn::winograd_nonfused::Win…
     2.3         38272753       2022   18928.2     7808    44448  void cudnn::winograd_nonfused::winogradForwardFilter4x4<float, float>(cudnn::winograd_nonfused::Win…
     0.0            71552          2   35776.0     5472    66080  void at::native::vectorized_elementwise_kernel<4, at::native::FillFunctor<float>, at::detail::Array…
```

**Comment by FindHao** [comment]
@ptrblck Do you mind trying cuda11.6 cudnn8.4.1 for bs32? Enabling and disabling the `torch.backends.cudnn.benchmark` to see the difference on your env?

**Comment by zhengwy888** [comment]
I am running into the same problem, the slow down is only happening with torch 1.12 and benchmark=False. Here is a screenshot of the tracing tool. 
![image](https://user-images.githubusercontent.com/1190730/191140499-907d8850-c5da-4f99-a8fb-13444f1d21ab.png)

**Comment by FindHao** [comment]
We have done more experiments on this issue and here are the summary of the performance regression scenarios.

1. on V100, only timm_regnet, when `cudnn.benchmark=False`
2. on A100, across various models, when `NVIDIA_TF32_OVERRIDE=0`

It is confirmed by @ptrblck and @ngimel. But since TF32 has become the default format for single precision floating point number and NVIDIA cares more about TF32 and A100 or newer GPUs, it is not emergent to focus on this issue. So I'll close it.
