### ISSUE TITLE
Build Error - libclog - "relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object"

### ISSUE THREAD

**Issue by benjaminplanche** [pytorch/pytorch#8195]
## Issue description

Getting an error when trying to compile the latest version of PyTorch, with `"recipe for target 'lib/libcaffe2.so' failed"`. More precisely, getting the following error:
> /usr/bin/ld: ../lib/libclog.a(clog.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
> ../lib/libclog.a: error adding symbols: Bad value

## Code example

```
> cd pytorch
> git pull --recurse-submodules
> python setup.py install
...
[ 43%] Built target sleef
[ 43%] Linking CXX static library ../../../../../../lib/libtbb_static.a
[ 47%] Built target tbb_static
[ 47%] Linking CXX shared library ../lib/libcaffe2.so
/usr/bin/ld: ../lib/libclog.a(clog.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../lib/libclog.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:3773: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:1015: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --with-cuda --with-nnpack --with-mkldnn nccl caffe2 nanopb libshm gloo THD'
```

## System Info

- OS: Ubuntu 16.04.2 LTS
- GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
- CMake version: version 3.6.3

- Python version: 3.6
- Is CUDA available: Could not collect
- CUDA runtime version: Cuda compilation tools, release 9.0, V9.0.176 (obtained through `nvcc --version`

- GPU models and configuration:
- GPU 0: TITAN X (Pascal)
- GPU 1: GeForce GTX 1080 Ti
- GPU 2: TITAN X (Pascal)
- GPU 3: GeForce GTX 1080 Ti
 
- Nvidia driver version: 390.42
- cuDNN version: Probably one of the following:
    - /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
    - /usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
    - /usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a
    - /usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
    - /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
    - /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
    - /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.10
    - /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.5
    - /usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a
    - /usr/local/cuda-9.0/lib64/libcudnn.so.7.1.2
    - /usr/local/cuda-9.0/lib64/libcudnn_static.a

- Versions of relevant libraries:
    - [pip3] numpy (1.14.0)
    - [conda] cuda80                    1.0                           0    soumith
    - [conda] magma-cuda80              2.3.0                         1    pytorch
    - [conda] magma-cuda90              2.3.0                         1    pytorch
    - [conda] torch                     0.4.0a0+a3d08de           <pip>
    - [conda] torchfile                 0.1.0                     <pip>

**Comment by zou3519** [comment]
try to `python setup.py clean`, pull the latest version of pytorch again, and then rebuild?

**Comment by kateiyas** [comment]
Same problem here. I've already added `-fPIC` to the CMake flags in `CMakeCache.txt` as described in the error message and [here](https://github.com/BVLC/caffe/issues/2171). Does not have any effect.

```
//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-fPIC
```

Error message: 

```
[ 83%] Linking CXX shared library ../lib/libcaffe2.so
/usr/bin/ld: /usr/local/lib/libleveldb.a(db_impl.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libleveldb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:4877: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:3402: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by orionr** [comment]
@kateiyas you shouldn't need leveldb... Try this instead?

```
cd pytorch
git pull
git submodule update --init
git clean -ffdx
USE_OPENCV=1 USE_LEVELDB=0 USE_LMDB=0 python setup.py install
```

**Comment by kateiyas** [comment]
@orionr This seems to compile and install, I can import `torch`, `caffe2`, `cv2`. I need USE_FFMPEG and LMDB for [R2Plus1D](https://github.com/facebookresearch/R2Plus1D/):
`USE_FFMPEG=1 USE_OPENCV=1 USE_LEVELDB=0 USE_LMDB=1 python setup.py install`

When I do: `from caffe2.python import workspace` I get `CRITICAL:root:Cannot load caffe2.python. Error: libcaffe2.so: cannot open shared object file: No such file or directory` now however. 

Where is `libcaffe2.so` expected to be written too? It is not inside `anaconda/lib/` and I don't see errors related to `libcaffe2.so` during running `setup.py` as described above.

**Comment by orionr** [comment]
Did you activate a conda environment before doing the install? Something like

```
conda create -yn pytorch
conda activate pytorch
USE_FFMPEG=1 USE_OPENCV=1 USE_LEVELDB=0 USE_LMDB=1 python setup.py install
```

The `libcaffe2.so` should install into site_packages/ directly next to the python code.

**Comment by orionr** [comment]
Also making change to setup.py at https://github.com/pytorch/pytorch/pull/12543

**Comment by kateiyas** [comment]
I checked out pytorch again and also made a whole new Anaconda installation (in the previous environment there were 5 different `libcaffe2.so` by now). `libcaffe2.so` can indeed be found in `./lib/python2.7/site-packages/torch/lib/libcaffe2.so`. 

I followed the [default build instructions](https://github.com/pytorch/pytorch#from-source) instructions to the word. When running `from caffe2.python import workspace` (after clearing up more issues with `conda install -c anaconda protobuf ` and `pip install future`) I now get: 

```
/anaconda/lib/python2.7/site-packages/caffe2/python/workspace.py in <module>()
     47     NumCudaDevices = C.num_cuda_devices
     48     GetCUDAVersion = C.get_cuda_version
---> 49     GetCuDNNVersion = C.get_cudnn_version
     50 
     51     def GetCudaPeerAccessPattern():

'module' object has no attribute 'get_cudnn_version'
```

 Let me know if this should be a new issue.

**Comment by kateiyas** [comment]
`NO_CUDA=1 USE_FFMPEG=1 USE_OPENCV=1 USE_LEVELDB=0 USE_LMDB=1 python setup.py install` results in 

```
//usr/lib/x86_64-linux-gnu/libopencv_highgui.so.2.4: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/pattern_net_transform_test.dir/build.make:93: recipe for target 'bin/pattern_net_transform_test' failed
make[2]: *** [bin/pattern_net_transform_test] Error 1
CMakeFiles/Makefile2:1838: recipe for target 'caffe2/CMakeFiles/pattern_net_transform_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/pattern_net_transform_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-nnpack --use-mkldnn caffe2 libshm gloo c10d THD'
```

...again from Caffe2 and OpenCV. Just let me know if these should be separate issues and I will create formal ones.

**Comment by orionr** [comment]
For that last one feel free to do `NO_TEST=1 NO_CUDA=1 ...`

**Comment by kateiyas** [comment]
@orionr Thanks, compiling without GPU and without test in another fresh Anaconda environment ran through then. When trying to use Caffe2 for extracting features I get the [Method VideoInput is not a registered operator. Did you mean: []](https://github.com/pytorch/pytorch/issues/12401) bug again however. 

```
Traceback (most recent call last):
  File "lib/extract_features.py", line 328, in <module>
    main()
  File "lib/extract_features.py", line 323, in main
    ExtractFeatures(args)
  File "lib/extract_features.py", line 126, in ExtractFeatures
    devices=gpus,
  File "/anaconda/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 34, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 219, in Parallelize
    input_builder_fun(model_helper_obj)
  File "lib/extract_features.py", line 101, in input_fn
    use_local_file=args.use_local_file,
  File "/R2Plus1D/lib/utils/model_helper.py", line 120, in AddVideoInput
    data, label, video_id = model.net.VideoInput(
  File "/anaconda/lib/python2.7/site-packages/caffe2/python/core.py", line 2171, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method VideoInput is not a registered operator. Did you mean: []
```

**Comment by zou3519** [comment]
I'm going to close this due to age because our build has changed so much since the last reply. If there is still an issue, please feel free to open us a new issue.

**Comment by ansar-hussain-QI** [comment]
still facing this issue
