### ISSUE TITLE
Complex Valued Loss Function: CrossEntropyLoss()

### ISSUE THREAD

**Issue by SantaTitular** [pytorch/pytorch#81950]
### 🚀 The feature, motivation and pitch

I'm working on complex-valued signal processing for remote sensing amongst other application and would be very usefull to use, in particular, [MSEloss](https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html#torch.nn.MSELoss) and [CrossEntropyLoss](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html#torch.nn.CrossEntropyLoss). Although I'm quite new to Pytorch I already made my MLP to start testing and was trying to do a workaround with 

```
class MyComplexCrossEntropyLoss(nn.Module):
    
    def __init__(self):
        super(MyComplexCrossEntropyLoss, self).__init__()

    def forward(self, inputs, targets):       
        real_loss = nn.CrossEntropyLoss(inputs.real, targets)
        if torch.is_complex(inputs):
            imag_loss = nn.CrossEntropyLoss(inputs.imag, targets)
            return (real_loss + imag_loss)/2
        else:
            return real_loss
```
I had already talked to @mruberry and @anjali411 at #73915 (#46642), so I though about making the feature request more official and possibly getting your input for a workaround, if possible, seeing as I get the following error: 
real_loss = nn.CrossEntropyLoss(inputs.real, targets)
RuntimeError: real is not implemented for tensors with non-complex dtypes. 😅.

Regarding motivation, I found a very good work already compiled here: [CVNN](https://complex-valued-neural-networks.readthedocs.io/en/latest/index.html) so it is easier to use as reference

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ezyang @anjali411 @dylanbespalko @Lezcano @nikitaved

**Comment by nikitaved** [comment]
Isn't cross-entropy defined for probability measures which are by definition real?

**Comment by nikitaved** [comment]
@nissy-shota , this approach kills the phase which might still carry some valuable information. You could introduce some hidden trainable layers that map complex activations to reals which are then fed into the cross-entropy loss. Maybe this could be of help.

**Comment by SantaTitular** [comment]
@Lezcano @nikitaved  Thank you, I had forgotten about the output from the MLP. Do I need to include a backward() method for the custom Loss function to work?

**Comment by nikitaved** [comment]
@SantaTitular , no, the function you defined will be implicitly differentiable.

**Comment by SantaTitular** [comment]
@nikitaved I fixed the `real` issue on the custom function (as shown below) but I get the error: `AttributeError: CrossEntropyLoss object has no attribute backward` hence the question. Am I doing something wrong for not getting the autograd to propagate?


# loss function
```
class MyComplexCrossEntropyLoss(nn.Module):
    
    def __init__(self):
        super(MyComplexCrossEntropyLoss, self).__init__()

    def forward(self, inputs, targets):       
        
        if torch.is_complex(inputs):
            real_loss = nn.CrossEntropyLoss(inputs.real, targets)
            imag_loss = nn.CrossEntropyLoss(inputs.imag, targets)
            return (real_loss + imag_loss)/2
        else:
            return nn.CrossEntropyLoss(inputs, targets)

```
# train batch
```
def train_batch(X, y, model, optimizer, criterion, **kwargs):
    "
    X (n_examples x n_features)
    y (n_examples): gold labels
    model: a PyTorch defined model
    optimizer: optimizer used in gradient step
    criterion: loss function
    "
    optimizer.zero_grad()
    out = model(X, **kwargs)
    loss = criterion(out, y)
    loss.backward()
    optimizer.step()
    return loss.item()
```
# Main

```
 ...
    model = FeedforwardNetwork(
            n_classes,
            n_feats,
            opt.hidden_sizes,
            opt.layers,
            opt.activation,
            opt.dropout
        )

    # get an optimizer
    optims = {"adam": torch.optim.Adam, "sgd": torch.optim.SGD}

    optim_cls = optims[opt.optimizer]
    optimizer = optim_cls(
        model.parameters(), lr=opt.learning_rate, weight_decay=opt.l2_decay
    )

    # get a loss criterion
    criterion = MyComplexCrossEntropyLoss()#nn.L1Loss()#

    # training loop
    epochs = torch.arange(1, opt.epochs + 1)
    train_mean_losses = []
    valid_accs = []
    train_losses = []
    for ii in epochs:
        print('Training epoch {}'.format(ii))
        for X_batch, y_batch in train_dataloader:
            loss = train_batch(
                X_batch, y_batch, model, optimizer, criterion)
            train_losses.append(loss)

        mean_loss = torch.tensor(train_losses).mean().item()
        print('Training loss: %.4f' % (mean_loss))

        train_mean_losses.append(mean_loss)
        valid_accs.append(evaluate(model, dev_X, dev_y))
        print('Valid acc: %.4f' % (valid_accs[-1]))

    print('Final Test acc: %.4f' % (evaluate(model, test_X, test_y)))


```

**Comment by Lezcano** [comment]
These sort of questions are best discussed in the forum: https://discuss.pytorch.org/

About the request, as @nikitaved pointed out, the cross entropy is mathematically defined on distributions, and as such, there's no clear extension to complex numbers. Nonetheless, the discussion here shows how some non-standard variations of the CrossEntropy to work on the real / imaginary parts of a complex tensor.

Closing this one for now.
