### ISSUE TITLE
torch.potrf fails on a positive semidefinite matrix

### ISSUE THREAD

**Issue by denkorzh** [pytorch/pytorch#8196]
Hello, I know about issue #199 but can't understand how to check the versions of BLAS, LAPACK etc.
The code I run is 
```{python}
import torch
sigma = torch.FloatTensor([[1, 20], [1, 100]])
torch.portf(sigma)
```

After that I get `RuntimeError: Lapack Error in potrf : the leading minor of order 2 is not positive definite at /pytorch/torch/lib/TH/generic/THTensorLapack.c:617`

This issue was reproduced for Pytorch 0.3.1 and 0.4.0.
Numpy solves this task successfully.

**Comment by zou3519** [comment]
I can reproduce this on master:
```
import torch
sigma = torch.FloatTensor([[1, 20], [1, 100]])
torch.potrf(sigma) # Fails

 s =sigma.numpy()
import scipy.linalg.lapack
scipy.linalg.lapack.dpotrf(s)
(array([[   1.,   20.],
        [   0., -300.]]), 2)
```
assuming that torch.potrf and scipy.linalg.lapack.dpotrf do the same thing

**Comment by vishwakftw** [comment]
From the MKL documentation, `potrf` requires the matrix to be symmetric. Could that be a reason? NumPy is not able to reproduce the matrix from the Cholesky decomposition:
```python
import torch
sigma = torch.FloatTensor([[1, 20], [1, 100]])
torch.potrf(sigma) # Fails

s = sigma.numpy()
import numpy as np
np.matmul(np.linalg.cholesky(s), np.linalg.cholesky(s).T)  # does not equal s
```

**Comment by SsnL** [comment]
[potrf requires input matrix to be symmetric in general](http://www.netlib.org/lapack/explore-html/d1/d7a/group__double_p_ocomputational_ga2f55f604a6003d03b5cd4a0adcfb74d6.html). Same applies for numpy and scipy. In @zou3519 's example, `scipy.linalg.lapack.dpotrf` returns `info` as second output (`2` here). If `info` is non-zero, it's saying that leading minor is not pd. PyTorch just explicitly raises error here, which also makes sense.
