### ISSUE TITLE
[ONNX] RReLU converted to onnx is not determenistic

### ISSUE THREAD

**Issue by SolomidHero** [pytorch/pytorch#82031]
### 🐛 Describe the bug

Hi i found that converted to onnx RReLU module's output is not consistent with torch's one. Traced function is consistent though.
Here is the reproducing code and plot:

```py3
import torch
import onnxruntime as ort

x = torch.linspace(-100, 20, 201, dtype=torch.float32)
torch.onnx.export(
    torch.nn.RReLU().eval(),
    (x,),
    'rrelu.onnx',
    input_names=['x'],
    output_names=['out'],
    dynamic_axes={
        'x': {0: 'T'},
        'out': {0: 'T'},
    },
    opset_version=16,
)


sess_options = ort.SessionOptions()
sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
ort_sess = ort.InferenceSession('rrelu.onnx', sess_options=sess_options)
out1 = ort_sess.run(['out'], {'x': x.numpy()})[0]
out2 = ort_sess.run(['out'], {'x': x.numpy()})[0]


import matplotlib.pyplot as plt
plt.figure(figsize=(7, 7))
plt.plot(x, out1, label='onnx 1')
plt.plot(x, out2, label='onnx 2')
plt.plot(x, torch.rrelu(x, training=False), color='red', label='torch')
plt.title('RReLU')
plt.legend()
plt.grid(alpha=0.2)
plt.show()
```
<img width="355" alt="Screenshot 2022-07-23 at 01 10 19" src="https://user-images.githubusercontent.com/28161779/180579324-88e83903-d475-45d4-ae57-8a2dc69c25d3.png">

Same for ORT_ENABLE_ALL, ORT_DISABLE_ALL, not defining options.

Here is converted module graph via netron:
<img width="202" alt="Screenshot 2022-07-23 at 01 12 41" src="https://user-images.githubusercontent.com/28161779/180579483-a55b70f2-e6f2-4c67-8068-521229e15ba8.png">

### Versions

```
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.13 (main, May 24 2022, 21:28:31)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)
Python platform: macOS-12.3.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.5.9
[pip3] torch==1.12.0
[pip3] torch-audiomentations==0.10.1
[pip3] torch-pitch-shift==1.2.2
[pip3] torch-time-stretch==1.0.2
[pip3] torchaudio==0.12.0
[pip3] torchmetrics==0.9.1
[pip3] torchsummary==1.5
[conda] Could not collect
```

**Comment by SolomidHero** [comment]
For a workaround I will use this version:
```py3
class RReLU(nn.RReLU):
    def forward(self, input: Tensor) -> Tensor:
        if self.training:
            return torch.rrelu(input, self.lower, self.upper, self.training, self.inplace)
        return F.leaky_relu(input, (self.lower + self.upper) / 2, self.inplace)

```
It converts to a single leaky relu block. Of course converted for inference model can't be used for training and vice-versa (you should manually rebuild graph), so I am looking for general solution.

**Comment by AllenTiTaiWang** [comment]
Hi,

please reference on this https://github.com/microsoft/onnxruntime/issues/8970

**Comment by SolomidHero** [comment]
Hi, seems they didn't solve the problem

**Comment by AllenTiTaiWang** [comment]
I see.
https://github.com/pytorch/pytorch/blob/6ca95547ac216dde9af29003648064b3569ade10/torch/onnx/symbolic_opset9.py#L4089-L4092

It seems that we had it right here, but didn't utilize the train/test mode. We will work on this.

**Comment by AllenTiTaiWang** [comment]
cc @BowenBao

**Comment by AllenTiTaiWang** [comment]
@ezyang I checked the doc of [rrelu](https://pytorch.org/docs/stable/generated/torch.nn.RReLU.html). It doesn't specify the different behavior of rrelu on training/testing(leaky-relu). Is that expected?

**Comment by ezyang** [comment]
are you sure this isn't just the onnx rng being different from torch's

**Comment by BowenBao** [comment]
> are you sure this isn't just the onnx rng being different from torch's

<img src="https://user-images.githubusercontent.com/9376104/182494945-5512784e-cd72-4c94-979b-d492642e7eaa.png" width=50% height=50%>

Looking at the image from the issue body, it appears PyTorch rrelu (red line) is not returning randomized results for `x < 0` after calling `.eval()`. This seems like undocumented behavior as it contradicts the docs https://pytorch.org/docs/stable/generated/torch.nn.RReLU.html:

<img src="https://user-images.githubusercontent.com/9376104/182495123-bd83c088-9524-4cc1-a619-223ed60210d5.png" width=65% height=65%>
