### ISSUE TITLE
Record fake tensor on FX IR while we're tracing make_fx

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#82044]
### 🐛 Describe the bug

Right now we have to run a FakeProp pass post facto to populate fake metadata, but there isn't really any need to do that; we have perfectly good fake tensors when we are running `make_fx`.

cc @ezyang @SherlockNoMad @bdhirsh @Chillee @eellison 

### Versions

master

**Comment by eellison** [comment]
Is this done ?

**Comment by ezyang** [comment]
Yep, they are stored in val
