### ISSUE TITLE
Errors in https://github.com/pytorch/pytorch/wiki/torch_quantization_design_proposal

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/pytorch#82055]
### 📚 The doc issue

Since I have no edit permission for the wiki, I report the typos in the following page below:
https://github.com/pytorch/pytorch/wiki/torch_quantization_design_proposal

```
c = torch.add(a,b)
# Works for both quantized and float tensors, scale and zero-point for c
# is set to 0 and 1.
```

It should be changed to
```
# is set to 1 and 0.
```

### Suggest a potential alternative/fix

See above.

**Comment by kit1980** [comment]
Edited, thanks!
