### ISSUE TITLE
Add pivoted QR from MAGMA (PR wanted?)

### ISSUE THREAD

**Issue by mistermult** [pytorch/pytorch#82092]
### 🚀 The feature, motivation and pitch

The pivoted QR algorithm is useful in many setting:
* I will be using it for low-rank approximations
* It is mentioned here #10454
* In the documentation of torch.qr it is mentioned that "This behavior will propably change once QR supports pivoting."

I plan to use pivoted QR geqp3 from MAGMA (https://icl.utk.edu/projectsfiles/magma/doxygen/group__magma__geqp3.html)
However, I saw that for the normal QR algorithm MAGMA was completely relplaced by cuSOVLER.

1. Is there still interest in adding the pivoted QR from MAGMA?
2. Is there also interest in a pivoted QR with early stopping, i.e. stop if the remaining columns are small (wrt. to Frobenius norm) or computing only the first k-columns of Q and R.
3. Would you prefer this in pytorch or rather as an extensions (if possible)?

### Alternatives

Alternatively, this might be implemented as an extensions. However, there accessing the same memory or the same CUDA queue might in the extensions (not checked yet).

Pivoted QR is implemented in many libraries on the CPU (LaPACK, ...). On the GPU there seems to be only MAGMA. In particular, there is no pivoted QR in cuSOLVER (only pivoted LU).

### Additional context
I will be implementing for my work in any case. The question of this issue is if this is interesting for pytorch.

**Comment by Lezcano** [comment]
This would certainly be a very cool addition.
We would need to add CPU support through LAPACK and CUDA support through MAGMA. This can be done in two different PRs. 

An example of a PR that adds one (actually two) such operation is https://github.com/pytorch/pytorch/pull/69828.

There's no need to write gradients for these functions if you're not comfortable deriving the relevant equations. I'm happy to do that in a follow up PR.

Please ping me if you have any issues doing so. Note that this would not be considered a simpler or a "first PR", but I assume that you know what you're doing as you seem comfortable with LAPACK and MAGMA.

All this being said, I'm closing this issue, and let's follow up this discussion in the original issue https://github.com/pytorch/pytorch/issues/10454

**Comment by lezcano** [comment]
@mistermult did you ever ended up having a go at implementing this one?
