### ISSUE TITLE
CUDA sparse_softmax can trigger floating point exception

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#82107]
### 🐛 Describe the bug

```
>>> import torch
>>> torch.sparse.softmax(torch.sparse_coo_tensor([[]], [], (3,), device='cuda'),0)
Floating point exception (core dumped)
```

@cpuhrsch do you know who the right person for this is?

### Versions

master

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by ezyang** [comment]
```
  TORCH_INTERNAL_ASSERT(nnz, "nnz is zero, would div by zero");
  auto nvalues = values.numel() / nnz;
```

div by zero due to nnz being zero. Not sure why CPU doesn't fail

**Comment by ezyang** [comment]
@cpuhrsch's diff fixes forward, but it looks like backward is also susceptible to the exception

**Comment by cpuhrsch** [comment]
@nikitaved - can you take a look? cc @bhosmer

**Comment by ezyang** [comment]
I posted a pr for backwards
