### ISSUE TITLE
Select coo tensor with zero NNZ does not preserve dtype (for integer types?)

### ISSUE THREAD

**Issue by amjames** [pytorch/pytorch#82150]
Index select on sparse COO tensors with zero nnz values and integral dtypes results in the reduced dimension result having dtype `int64` always. 

### 🐛 Describe the bug

```python
import torch
dtypes = [torch.bool, torch.int8, torch.int32, torch.bfloat16, torch.float32, torch.float64]
for dtype in dtypes:
    a = torch.ones((6, 1), dtype=dtype)
    a_s = a.to_sparse_coo()
    if a_s[0].dtype != dtype:
        print(f'2d->1d index select (with nnz != 0) result dtype incorrect, for dtype {dtype}, got {a_s[0].dtype}')
    if a_s[0,0].dtype != dtype:
        print(f'2d->scalar index select (with nnz != 0) result dtype incorrect, for dtype {dtype}, got {a_s[0,0].dtype}')

    b_s = (a * 0).to_sparse_coo()
    if b_s[0].dtype != dtype:
        print(f'2d->1d index select (with nnz == 0) result dtype incorrect, for dtype {dtype}, got {b_s[0].dtype}')
    if b_s[0,0].dtype != dtype:
        print(f'2d->scalar index select (with nnz == 0) result dtype incorrect, for dtype {dtype}, got {b_s[0,0].dtype}')

```
### Output
```
2d->1d index select (with nnz == 0) result dtype incorrect, for dtype torch.bool, got torch.int64
2d->scalar index select (with nnz == 0) result dtype incorrect, for dtype torch.bool, got torch.int64
2d->scalar index select (with nnz == 0) result dtype incorrect, for dtype torch.int8, got torch.int64
2d->scalar index select (with nnz == 0) result dtype incorrect, for dtype torch.int32, got torch.int64
```

### Versions

Repro generated with current master

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer @nairbv @mruberry

**Comment by cpuhrsch** [comment]
@nikitaved - can you take a look?

**Comment by amjames** [comment]
NB: This also affects CSR/(and soon CSC) index select to an extent, if there are no batch dims select is accomplished by `convert_to_coo->select`. 

BSR/CSR do not support index select except in the batch dims.

**Comment by nikitaved** [comment]
The issue is luckily not with `index_select`, so I am not to be blamed :) It is indeed with `select`. Sure, will take a look.

**Comment by cpuhrsch** [comment]
@nikitaved - I didn't mean to imply it's your fault, but rather it seems like you're the right candidate for this task given your experience and current ongoing work.

**Comment by nikitaved** [comment]
@cpuhrsch , I did not mean you implied this, it is just I do not like breaking things :) Will have a look at this first thing tomorrow.

**Comment by nikitaved** [comment]
The issue comes from `torch.sum` promoting integral empty tensor to `int64`, unfortunately. I have submitted a repro in https://github.com/pytorch/pytorch/issues/82159.

**Comment by cpuhrsch** [comment]
Alright, let's fix that and also https://github.com/pytorch/pytorch/pull/66153 while we're at it. We know that torch.sparse.sum is used and so these bugs seem worthwhile fixing.
