### ISSUE TITLE
Upload Tensor.h to docs upon master build

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8216]
A continual pain point of using ATen is that people don't know where to find all of the methods/functions available for their use. There is a `docs/Tensor.h` but it is continually out of date.

There is a very simple fix: upload the generated `Tensor.h` to https://pytorch.org/docs/stable/index.html along with the rest of the docs. All you need to do is modify the `Makefile` in `docs` to also pull in `Tensor.h`. (Because of the fact that we clean all build artifacts, you may have to do some work to find the header.)

CC @ebetica 

cc @yf225 @glaringlee @ezyang @zou3519 @jlin27

**Comment by zou3519** [comment]
Hmm, I think we have fixed this by adding documentation for the C++ API.
there's documentation for [Tensor](https://pytorch.org/cppdocs/api/classat_1_1_tensor.html?highlight=tensor) as well as the functions on it: https://pytorch.org/cppdocs/api/namespace_at.html#functions
