### ISSUE TITLE
[LTC][Codegen] Provide an alternative for GetIrValueForScalarFromCodegen

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/pytorch#82208]
### 🚀 The feature, motivation and pitch

`GetIrValueForScalarFromCodegen` is used by codegen.

https://github.com/pytorch/pytorch/blob/7bf1b1dc31132f0e599ddbef7cd639677b6fd542/torch/csrc/lazy/core/lazy_graph_executor.cpp#L532-L543

LTC upload the scalar to the CPU device and make a Device data out of it. This will create segfault on PyTorch/XLA since we expect all `Value` to be on the same device. In fact we don't support upload to the `at::CPU` since it is not a XLA device.

I have think of a couple ways to handle this
1. upload to the default device instead. Backend currently sets the default device in https://github.com/pytorch/pytorch/blob/7bf1b1dc31132f0e599ddbef7cd639677b6fd542/torch/csrc/lazy/backend/backend_interface.h#L101
2. In the op that takes scalar, it must also takes some other `at::Tensor` that is on a lazy device. We just need to pick one `at::Tensor` and upload the scalar to the same device. This is the approach is what PyTorch/XLA takes today which should be the most correct thing to do.
3. Don't wrap Scalar into IR. I tried to reuse `TreatScalarsAsConstants` that already existed, but I don't think I can use this option in the `full_codegen` section

@Krovatkin @wconstab 

### Alternatives

XLA don't codegen ops that takes scalar which is not ideal.

**Comment by wconstab** [comment]
I think your option (2) is probably the best option for you, right? If so, I think it should be possible either by 
 - using derived class (XLAGraphExecutor, or TSGraphExecutor) to customize the ::GetIrValueForScalarFromCodegen behavior.  It might make sense to make the 'default' be to use the 'default device' (or, the device other tensors used) and customize the TS version to use the cpu device.  But it also depends if XLA already plans to derived-class XLAGraphExecutor, and then its easier for you to do the change
 - add a flag: we can probably find a quick way to make TS backend set a flag one way and XLA backend set it the other way, then rely on a conditional inside LazyGraphExecutor::GetIrValueForScalarFromCodegen to choose the device.

**Comment by JackCaoG** [comment]
We do have plan to introduce XLAGraphExecutor(mostly because of SPMD and profiler hints) , but even if we take this approach we still need to pass the other tensor to the `GetIrValueForScalarFromCodegen`? Therefore function signature needs to change. 

I think we can start with
1. Change the function signature of `GetIrValueForScalarFromCodegen`
2. Update codegen to pass another tensor to `GetIrValueForScalarFromCodegen`

do you think we want to have `GraphExecutor` to take different parameter for the same function? or is it better to always take additional tensor but TS ignore it?

I think we can also start with a flag and later I will try to implement the different graphExecutor.

**Comment by wconstab** [comment]
> Change the function signature of GetIrValueForScalarFromCodegen

would it be easiest if we just make GetIrValueForScalarFromCodegen accept a 'device' argument, and then put the logic for what device to use into the codegen?

it seems at least cleaner to me to accept a device in GetIrValueForScalarFromCodegen than to accept a second tensor or list of all tensors to extract the device arg from. 

but we'd then have to solve the device issue inside the codegen or using some other helper function.   solving in the codegen would be pretty easy to do via a flag that we pass from cmdline args that says which behavior to use, but i'm not sure if there is a simpler/better way.

**Comment by JackCaoG** [comment]
```
would it be easiest if we just make GetIrValueForScalarFromCodegen accept a 'device' argument, and then put the logic for what device to use into the codegen?
```

oh yes, you right, I think this is much cleaner.
