### ISSUE TITLE
pytorch version > 1.8 init cuda env after `import torch`

### ISSUE THREAD

**Issue by FateScript** [pytorch/pytorch#82211]
### 🐛 Describe the bug

```python
import torch
import multiprocessing as mp


def foo(q):
    x = torch.Tensor([1.0]).cuda()
    print(x)
    q.put("Hello")


if __name__ == '__main__':
    q = mp.Queue()
    p = mp.Process(target=foo, args=(q,))
    p.start()
    print(q.get())
    p.join()
```

Code above will crash if torch version > 1.8, but for torch <= 1.8, it works well.
It seems that CUDA env is initialized after 1.8, and it's unexpected for users like me.
Is there anyway for users to lazy load cuda env ? (For some reasons, I must use fork as startmethod)

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.15-1.el7.elrepo.x86_64-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.8.0
[conda] Could not collect

**Comment by H-Huang** [comment]
Unfortunately, using CUDA in `fork`ed processes is not supported: https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing

**Comment by FateScript** [comment]
> Unfortunately, using CUDA in `fork`ed processes is not supported

@H-Huang  Yes, I understand that cuda env should not be initialized before `fork` is calling, but it works when `fork` method is called before cuda env is initialiezed.

For pytorch version <= 1.8, `import torch` will not make cuda env init, you might check this by the following code. But for torch version > 1.8, env is set when import happens, this might lead program crashing when upgrade pytorch version.
```python
import multiprocessing as mp


def foo(q):
    import torch
    x = torch.Tensor([1.0]).cuda()
    print(x)
    q.put("Hello")


if __name__ == '__main__':
    q = mp.Queue()
    p = mp.Process(target=foo, args=(q,))
    p.start()
    print(q.get())
    p.join()
```

I'm wondering is this expected for pytorch team? 
If not, please fix this; otherwise, could you please explain any reason of **init cuda env when import torch** or any method for users to lazy init cuda env? 

Thanks for your kindness.

**Comment by H-Huang** [comment]
> For pytorch version <= 1.8, import torch will not make cuda env init, but for torch version > 1.8, env is set when import happens, this might lead program crashing when upgrade pytorch version.

Hi @FateScript, I dont believe this is the case. I just tried on my local machine which uses pytorch 1.12

```
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.12.0+cu102'
>>> torch.cuda.is_initialized()
False
```
