### ISSUE TITLE
pixel_shuffle has inconsistent aliasing between cuda and cpu

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#82235]
### 🐛 Describe the bug

```
import torch

for device in ["cuda", "cpu"]:
    inp = torch.rand([1, 9, 2, 2], device=device)
    output = torch.nn.functional.pixel_shuffle(inp, upscale_factor=1)
    print(inp.storage()._cdata == output.storage()._cdata)

# True
# False
```

This will also cause a `storage.use_count() == 1` invariant error when run in debug mode with cuda.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are 

### Versions

master

**Comment by albanD** [comment]
We will need to add cloning to ensure that we never return the same Tensor, even when nothing needs to be done.
Otherwise, we should make this function a CompositeImplicit function to be able to make the no-op case clone-free

**Comment by bdhirsh** [comment]
Should be fixed by https://github.com/pytorch/pytorch/issues/82235
