### ISSUE TITLE
[feature request] cpp_extension inside a docker with CUDA_HOME set

### ISSUE THREAD

**Issue by dashesy** [pytorch/pytorch#8223]
Can we [build cpp extension](https://pytorch.org/tutorials/advanced/cpp_extension.html) from inside a Docker, where I have installed CUDA, but of course no runtime? this is enough to build other CUDA applications.

    python setup.py install

This line in cpp_extension.py:

    CUDA_HOME = _find_cuda_home() if torch.cuda.is_available() else None

Basically prevents the build, because even though `_find_cuda_home()` has a home, cuda.is_available() returns false. The returned error message is also confusing/wrong:

```text
    EnvironmentError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```
is incorrect.

## System Info
This is the result of collect_env.py from inside the docker:

Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: No
CUDA runtime version: 8.0.61
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn_static_v6.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py27_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] torchvision               0.2.1                    py27_1    pytorch

**Comment by SsnL** [comment]
cc @goldsborough

**Comment by ezyang** [comment]
@dashesy Is it just a matter of relaxing that if statement? If so, we'd be happy to take this patch. Submit a PR?

**Comment by goldsborough** [comment]
@dashesy are you interested in submitting a PR for this? It's easier for you to test it since you have your setup already. Otherwise I'll add it to my bucket, but can't promise super immediate resolution

**Comment by dashesy** [comment]
Just removing that second part of if statement works, can now create extension in docker
