### ISSUE TITLE
[ONNX] Remove einsum_helper from opset12 public functions

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#82245]
### 🐛 Describe the bug

The function `einsum_helper` in torch/onnx/symbolic_opset12.py is a helper. It is not meant for public consumption. We should rename it to `_einsum_helper` and remove it from `__all__`

### Versions

N/A

**Comment by killbigger** [comment]
I would like to work on this bug

**Comment by justinchuby** [comment]
@killbigger it’s yours now! Thanks for offering to contribute

**Comment by killbigger** [comment]
I have made the pull request do comment and help out
