### ISSUE TITLE
A lot of documentation pages do not load 404 error

### ISSUE THREAD

**Issue by John15321** [pytorch/pytorch#82263]
### 📚 The doc issue

Eg example tutorial for video processing does not load and many more

http://49.235.228.196/pytorch.org/intermediate/torchvision_tutorial.html

![image](https://user-images.githubusercontent.com/56229312/181118086-2233eb11-1823-4697-865c-3131a2384e65.png)

![image](https://user-images.githubusercontent.com/56229312/181118017-bcd2a30d-7d85-4678-8967-562c0227863d.png)

**Comment by kit1980** [comment]
How did you get to that page?

Here is the tutorial on the official web site - https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

**Comment by H-Huang** [comment]
That URL is unsecure and not the official pytorch docs. Please use https://pytorch.org/
