### ISSUE TITLE
[LTC][Codegen] Call `torch::lazy::GetCanonicalDimensionIndices` on dimension inputs

### ISSUE THREAD

**Issue by JackCaoG** [pytorch/pytorch#82286]
## Context
I run into this issue when trying to codegen the `amax` and `amin`. test case
```
t1 =torch.randn(4,3,4, device='xla:0')
t2 = torch.amax(t1, -2, True)
```

failed with a C++ exception that index out of bound. Reason is that the codegen does not handle converting the negative index to the corresponding positive index. 
```
  torch::lazy::NodePtr node = torch::lazy::ReuseNode<Amin>(
      lazy_self->GetIrValue(), std::vector<int64_t>(dim.begin(), dim.end()),
      keepdim);
```

LTC actually already has the helper function `GetCanonicalDimensionIndices` for this.

https://github.com/pytorch/pytorch/blob/e8f4c9cc402a43d6dd4119db2950673bd88a60b8/torch/csrc/lazy/core/helpers.h#L36-L39

## Proposal

It is not ideal to call `GetCanonicalDimensionIndices` on every `vector<int64>`. I took a quick pass at where pytorch/xla calls this helper function and I am pretty confident that if we
1. Check whether input is of type `at::IntArrayRef`
2. Check whether input of name `dim` or `dims`

when both condition meets, we can call `torch::lazy::GetCanonicalDimensionIndices` (please include the namespace since xla codegen uses a different namespace) on top of `std::vector<int64_t>(dim.begin(), dim.end())`.

@wconstab @Krovatkin @desert

### Alternatives

PyTorch/XLA does not generate the `XLANativeFunction.cpp` for these ops (14 of them calls `GetCanonicalDimensionIndices` today)

**Comment by Krovatkin** [comment]
@JackCaoG

```
It is not ideal to call GetCanonicalDimensionIndices on every vector<int64>. I took a quick pass at where pytorch/xla calls this helper function and I am pretty confident that if we

Check whether input is of type at::IntArrayRef
Check whether input of name dim or dims
```

This could work, I'm thinking if we could alternatively introduce **attributes** (say, CanonicalizeDims attribute on `amin`) on parameters which we could check when generate the logic that's constructing the IR node for an op.

This should arguably look much less complicated (thus, more maintainable) and should also be less fragile as there won't be a heuristic involved.

@bdhirsh wdyt?

I was thinking that we could maybe compute shapes inside a c-tor but this would require using handwritten IR and also special casing codegen to not call a c-tor that takes shapes. That sounds way too complicated.

**Comment by bdhirsh** [comment]
Yeah, attributes seem like a pretty good idea (and are definitely more robust), as long as it's not too much work to add them / plumb them into the LTC codegen data model. Maybe a reasonable place for the metadata so go would be in `LazyArgument`?

Also, would LTC benefit from this too? (from this proposal it sounds like similar ops that need this utility probably don't go through full LTC codegen).

**Comment by Krovatkin** [comment]
> Also, would LTC benefit from this too? (from this proposal it sounds like similar ops that need this utility probably don't go through full LTC codegen).


This is a great question. @JackCaoG what do you think? I guess what @bdhirsh is wondering if we need these attributes for all the sections or some of them only.

> Maybe a reasonable place for the metadata so go would be in LazyArgument?

Yeah I was thinking `LazyArgument` as well! I also hope it wouldn't be too much work, but I just need to try it I guess

**Comment by JackCaoG** [comment]
I think LTC will benefit from it, I am pretty sure if we pass negative index to ltc `amax` it will crash today. `LazyArgument` sgtm.

**Comment by Krovatkin** [comment]
@JackCaoG  we won't 😛 since we aren't supporting these ops today.
What's the priority of this issue? Medium-to-high?

**Comment by JackCaoG** [comment]
for pytorch/xla, we have `all`, `amax`, `amin`, `any`, `flip`, `logsumexp`, `mean`, `norm`, `permute`, `prod`, `roll`,`std`, `std_mean`, `sum`, `var`,`var_mean` a total of 16 ops that supports negative index(through `GetCanonicalDimensionIndices`). I am pretty sure LTC support some of these ops lol. This issue is blocking us from codegen these 14 ops without regression.

**Comment by Krovatkin** [comment]
touche... we must have at least `mean` 😋 

I'll try to work on this a little bit tomorrow and more on Monday.
Lmao, you already gave @desertfire a task 😄 and Will is on PTO, so there's nobody left. 
Unless... we can get Jiewen to do this task as a part of his GTI 🧠 !

**Comment by JackCaoG** [comment]
@Krovatkin Maybe this is why Will is on pto 😆

**Comment by wconstab** [comment]
IIRC we wanted to make the behavior of lazy IR match aten, which means keeping values like -1 in the IR instead of canonicalizing them.

In the TS backend this should work fine becuase we should be able to pass -1 into an op in TS interpreter and it should understand what to do with the negative value.

If that is all correct so far, then I would ask if XLA can call the canonicalization helper at the lowering step instead of the IR creation step.  That seems like the 'right' place to adapt from the semantics of aten to the semantics of XLA.

**Comment by JackCaoG** [comment]
@wconstab This is a fair point, I think I should be able to call this function in lowering time. Let me try that and reply here.

**Comment by JackCaoG** [comment]
Moving `GetCanonicalDimension` to lowering phases works for me, I think we can close this issue since it is by design.

**Comment by JackCaoG** [comment]
@wonjoolee95 FYI, when encounters one of ops listed in https://github.com/pytorch/pytorch/issues/82286#issuecomment-1198776854, we need to move `GetCanonicalDimensionIndices` call from `tensor_method.cpp` to corresponding lowering function.
