### ISSUE TITLE
How to use SwiftShader to test vulkan mobile models ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/pytorch#82304]
### 📚 The doc issue

In this tutorial [here](https://pytorch.org/tutorials/prototype/vulkan_workflow.html),

It's pointed out at the end that it will be possible to use SwiftShader to test pytorch_mobile models on Vulkan backend without needing to go to mobile.

How?

**Comment by dreiss** [comment]
See the Vulkan or SwiftShader documentation and look for instructions on using VK_ICD_FILENAMES to set the Vulkan Installable Client Driver.
