### ISSUE TITLE
Got import error for functorch memory_efficient_fusion

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#82327]
### 🐛 Describe the bug

Got import error for functorch memory_efficient_fusion

https://github.com/pytorch/pytorch/pull/81522 is likely related.

```python
import torch
from functorch.compile import memory_efficient_fusion
```

Error:
```
Traceback (most recent call last):
  File "a.py", line 2, in <module>
    from functorch.compile import memory_efficient_fusion
  File "/opt/pytorch/functorch/functorch/__init__.py", line 21, in <module>
    from ._src.eager_transforms import (
  File "/opt/pytorch/functorch/functorch/_src/eager_transforms.py", line 17, in <module>
    from .decompositions import decomposition_table, decomposition_table_for_jvp
  File "/opt/pytorch/functorch/functorch/_src/decompositions.py", line 149, in <module>
    def native_batch_norm_backward(
  File "/opt/pytorch/pytorch/torch/_decomp/__init__.py", line 122, in decomposition_decorator
    tree_map(add_op_to_table, aten_op)
  File "/opt/pytorch/pytorch/torch/utils/_pytree.py", line 179, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/opt/pytorch/pytorch/torch/utils/_pytree.py", line 179, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/opt/pytorch/pytorch/torch/_decomp/__init__.py", line 101, in add_op_to_table
    raise RuntimeError(f"duplicate registrations for {op_overload}")
RuntimeError: duplicate registrations for aten.native_batch_norm_backward.default
```

### Versions

functorch_commit: https://github.com/pytorch/functorch/commit/516a8cd319b1b2e90177ec388b368156876af61c
torch_commit: https://github.com/pytorch/pytorch/commit/9f6e3b0fe4bb3ddde47ab8ca4cc8365696e10841

cc @zou3519 @yushangdi @Chillee @ptrblck @ezyang @malfet

**Comment by Chillee** [comment]
@xwang233 trivial thing to do to unblock you is to comment out that registration :P 

But you need to rebuild functorch after this PR.

**Comment by xwang233** [comment]
@Chillee We're already building functorch from the latest commit https://github.com/pytorch/functorch/commit/516a8cd319b1b2e90177ec388b368156876af61c. Can you indicate which functorch commit would solve this issue?

**Comment by malfet** [comment]
@xwang233 functorch is now part of PyTorch repo, and it should always be buildable at the same commit (There is CI to check it, but I have not tried it myself)

**Comment by xwang233** [comment]
@malfet If I understand correctly, I should run `cd pytorch/functorch; pip install -e .` to install functorch, and the `setup.py` from pytorch root directory doesn't install functorch automatically?

**Comment by malfet** [comment]
@xwang233 yes, this is by design for now, but perhaps later top level setup.py will install both PyTorch and FuncTorch

**Comment by xwang233** [comment]
Thanks for the clarification!
