### ISSUE TITLE
Mergebot should ignore skipped/cancelled workflows

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#82335]
### 🐛 Describe the bug

mergebot failed to merge https://github.com/pytorch/pytorch/commit/28140e4008289251b695385acfb48ac7a47cd49c/checks?check_suite_id=7546696660 even though all its required signal was met because GH triggered two sets of pull and Lint for one commit and one was cancelled (the other passed).

We should just ignore the cancelled set/any cancelled jobs as if they were not run (instead of as failures).

ccing @zengk95 

### Versions

master

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
Grabbing for myself

**Comment by malfet** [comment]
Debating what would be the proper way of implementing it: simply ignore cancelled workflows if there are another status there, or preserve only latest one?
