### ISSUE TITLE
Sharing complex non-pickleable object between processes with BaseManager

### ISSUE THREAD

**Issue by wdykas** [pytorch/pytorch#82334]
### 🐛 Describe the bug

I am attempting to share a complex object that cannot be pickled between processes in a multi-gpu DDP training scenario.  The recommended pythonic way I found to do this [here](https://stackoverflow.com/questions/3671666/sharing-a-complex-object-between-processes) is using a Manager object and manipulate my object with proxies.  However when I import the following I get that the module cannot be found:
```
from torch.multiprocessing.managers import BaseManager
```

Does torch.multiprocessing not directly provide all the functionality of pythons multiprocessing and is there a better way to share non-pickleable custom objects between training processes in pytorch?

### Versions

PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: version 3.21.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: 
GPU 0: NVIDIA Tesla V100-DGXS-32GB
GPU 1: NVIDIA Tesla V100-DGXS-32GB
GPU 2: NVIDIA Tesla V100-DGXS-32GB
GPU 3: NVIDIA Tesla V100-DGXS-32GB

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] numpydoc==1.4.0
[pip3] torch==1.12.0+cu116
[pip3] torchaudio==0.12.0+cu116
[pip3] torchmetrics==0.9.2
[pip3] torchvision==0.13.0+cu116

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
@wdykas 

`torch.multiprocessing` only adds a thin layer on top of `multiprocessing` to handle `torch.Tensor`. And, technical speaking, you can still use `BaseManager` from `multiprocessing` to handle your object.

**Comment by wdykas** [comment]
@ejguan Thanks!  So all `multiprocessing` objects can be assumed with some exceptions to work with `torch.multiprocessing`
