### ISSUE TITLE
PR #81785 causes inference start up overhead on timm models.

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#82343]
### 🐛 Describe the bug

PR #81785 seems to have increased start up overhead for timm models significantly and has timed out our internal CI.

Overall throughput is about the same, but end-2-end test time for the example below has regressed 2x.

Downloading the repo from timm: `https://github.com/rwightman/pytorch-image-models.git`

run with
```
python ./pytorch-image-models/benchmark.py --bench infer --model adv_inception_v3 -b 128 --img-size 224 --fuser nvfuser --torchscript 2>&1 | ts -s
```

On commit '9a5fa15ea834399dbcb60a6c90dc9559ca4e07c3'
```
00:00:02 Benchmarking in float32 precision. NCHW layout. torchscript enabled
00:00:03 Model adv_inception_v3 created, param count: 23834568
00:00:04 Running inference benchmark on adv_inception_v3 for 40 steps w/ input size (3, 224, 224) and batch size 128.
00:00:44 /opt/pytorch/pytorch/torch/nn/modules/module.py:1186: UserWarning: operator() profile_node %3813 : bool = prim::profile_ivalue(%training)
00:00:44  does not have profile information (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:104.)
00:00:44   return forward_call(*input, **kwargs)
00:00:44 Infer [8/40]. 1833.46 samples/sec. 69.813 ms/step.
00:00:45 Infer [16/40]. 1832.86 samples/sec. 69.836 ms/step.
00:00:45 Infer [24/40]. 1833.01 samples/sec. 69.830 ms/step.
00:00:46 Infer [32/40]. 1832.72 samples/sec. 69.842 ms/step.
00:00:47 Infer [40/40]. 1832.99 samples/sec. 69.831 ms/step.
00:00:47 Inference benchmark of adv_inception_v3 done. 1832.04 samples/sec, 69.83 ms/step
00:00:47 --result
00:00:47 {
00:00:47     "model": "adv_inception_v3",
00:00:47     "infer_samples_per_sec": 1832.04,
00:00:47     "infer_step_time": 69.831,
00:00:47     "infer_batch_size": 128,
00:00:47     "infer_img_size": 224,
00:00:47     "param_count": 23.83
00:00:47 }
```

going to commit prior `1e8ef8cb205319e43fb4210bdbbf7749db2e0d73`
```
00:00:02 Benchmarking in float32 precision. NCHW layout. torchscript enabled
00:00:04 Model adv_inception_v3 created, param count: 23834568
00:00:05 Running inference benchmark on adv_inception_v3 for 40 steps w/ input size (3, 224, 224) and batch size 128.
00:00:24 /opt/pytorch/pytorch/torch/nn/modules/module.py:1186: UserWarning: operator() profile_node %3813 : bool = prim::profile_ivalue(%training)
00:00:24  does not have profile information (Triggered internally at /opt/pytorch/pytorch/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:104.)
00:00:24   return forward_call(*input, **kwargs)
00:00:24 Infer [8/40]. 1833.36 samples/sec. 69.817 ms/step.
00:00:25 Infer [16/40]. 1833.43 samples/sec. 69.814 ms/step.
00:00:26 Infer [24/40]. 1833.36 samples/sec. 69.817 ms/step.
00:00:26 Infer [32/40]. 1833.58 samples/sec. 69.809 ms/step.
00:00:27 Infer [40/40]. 1833.49 samples/sec. 69.812 ms/step.
00:00:27 Inference benchmark of adv_inception_v3 done. 1832.86 samples/sec, 69.81 ms/step
00:00:27 --result
00:00:27 {
00:00:27     "model": "adv_inception_v3",
00:00:27     "infer_samples_per_sec": 1832.86,
00:00:27     "infer_step_time": 69.812,
00:00:27     "infer_batch_size": 128,
00:00:27     "infer_img_size": 224,
00:00:27     "param_count": 23.83
00:00:27 }
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+git4bf2f14
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-97-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration:
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 470.82.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.3.0a0+516a8cd
[pip3] numpy==1.21.5
[pip3] torch==1.13.0a0+git1e8ef8c
[pip3] torchdynamo==1.13.0.dev0
[pip3] torchvision==0.14.0a0+91176e8
[conda] functorch                 0.3.0a0+516a8cd           dev_0    <develop>
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] nomkl                     3.0                           0
[conda] numpy                     1.21.5           py38h7a5d4dd_2
[conda] numpy-base                1.21.5           py38hb8be1f0_2
[conda] torch                     1.13.0a0+git1e8ef8c           dev_0    <develop>
[conda] torchdynamo               1.13.0.dev0               dev_0    <develop>
[conda] torchvision               0.14.0a0+91176e8           dev_0    <develop>

**Comment by jjsjann123** [comment]
cc'ing @xwang233 @ptrblck

**Comment by eellison** [comment]
cc @davidberard98

**Comment by davidberard98** [comment]
@jjsjann123 I think this should be fixed, can you check?

**Comment by xwang233** [comment]
I've verified that the inference overhead is recovered as of commit https://github.com/pytorch/pytorch/commit/de0e03001d31523ef86c3d7852c87cdad6d96632

**Comment by jjsjann123** [comment]
Nice~~ Looks like @xwang233 beats me to it~~
