### ISSUE TITLE
No module named caffe2.python

### ISSUE THREAD

**Issue by hello-fk** [pytorch/pytorch#8236]
```
root@kylin-os:~# cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Failure
```
```
root@kylin-os:~# python 
Python 2.7.11+ (default, Apr 25 2016, 14:00:43) 
[GCC 5.3.1 20160225] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffe2.python

```
There are no problems with the previous steps.I found out according to the  [ this info ](https://caffe2.ai/docs/faq.html#why-do-i-get-import-errors-in-python-when-i-try-to-use-caffe2) tutorial that I lack a lot of components，
```
/usr/local/                                   
  +-- bin/
    +-- python (can't find)
    +-- <other executables>
  +-- include/
    +-- <header files for c and c++ libraries>
  +-- lib/
    +-- libcaffe2.dylib （can't find)
    +-- <other Caffe2 c and c++ libraries>
    +-- <other c and c++ libraries>
    +-- python2.7/                              
      +-- site-packages/
        +-- caffe2/      (can't find)                     
        +-- <other installed python modules>
```
The path to Caffe2 is /home/kylin1/Desktop/pytorch
The path to python2.7.exe is /usr/bin
The path to libcaffe2.dylib is can't find in system

# Details

-     PyTorch or Caffe2: PyTorch
- 
-     How you installed PyTorch (conda, pip, source): source
- 
-     Build command you used (if compiling from source):cmake ..
- 
-     OS: Ubuntu 16.04.4 LTS
- 
-     PyTorch version: 0.5.0a0+c446269
- 
-     Python version: 2.7
- 
-     CUDA/cuDNN version: none
- 
-     GPU models and configuration: none
- 
-     GCC version (if compiling from source): 5.3.1
- 
-     CMake version: 3.5.1

**Comment by SsnL** [comment]
isn't this a caffe2 issue?

**Comment by Yangqing** [comment]
Quick question: how did you install the package? Is it via setup_caffe2.py or setup.py?

cc @orionr  FYI

**Comment by sgarcia22** [comment]
Can you import caffe2? What about setting the PYTHON_PATH to include the library file (make sure the actual building of Pytorch was successful)

**Comment by Luke1962** [comment]
I've the same problem after successfull build from source with raspbian.
The used build command is  ~/pi/pytorch/scripts/build_raspbian.sh
PYTHONPATH is /home/pi/ros_catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/**home/pi/pytorch/caffe2**:/home/pi/pytorch/build:/home/pi/pytorch/caffe2/python

I'm not shure if these paths (manually added) are correct.
Which is correct location of caffe2.python module and how to check if it has been built?

**Comment by jojivk73** [comment]
I am seeing a similar issue after sucessful build and install. Tried reverting to python 3.5 + reinstalling build. Tried setting PYTHONPATH to have so file dir. Let me know if there is any solution.


>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: No module named 'caffe2.python.caffe2_pybind11_state'

I am following instructions from https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile. 

Tried "python setup.py build" also. At the end of it, the folllowing message is sown
========================================================
    :
Skipped writing torch/csrc/jit/generated/aten_interned_strings.h

Copying extension caffe2.python.caffe2_pybind11_state
Copying caffe2.python.caffe2_pybind11_state from /home/hldapps/FB/pytorch/torch/lib/tmp_install/lib/python3.5/site-packages/caffe2/python/caffe2_pybind11_state.cpython-35m-x86_64-linux-gnu.so to /home/hldapps/FB/pytorch/build/lib.linux-x86_64-3.5/caffe2/python/caffe2_pybind11_state.cpython-35m-x86_64-linux-gnu.so
copying /home/hldapps/FB/pytorch/torch/lib/tmp_install/lib/python3.5/site-packages/caffe2/python/caffe2_pybind11_state.cpython-35m-x86_64-linux-gnu.so -> /home/hldapps/FB/pytorch/build/lib.linux-x86_64-3.5/caffe2/python
=======================================================

**Comment by orionr** [comment]
@jojivk73 are you installing into a conda environment or with virtualenv? Also, can you link to a paste of the full stdout/stderr output from `python setup.py install`? Thanks.

**Comment by jojivk73** [comment]
I'm installing into a conda env. it is on CentOS. No GPU on machine.
output : https://github.com/jojivk73/temp/blob/master/out.txt

**Comment by orionr** [comment]
Looks like you missed the CMake output at the top (before it starts building). Can you put all of that here as well?

In any case, looks like the pybind11 lib is being installed at

```
copying build/lib.linux-x86_64-3.7/caffe2/python/caffe2_pybind11_state.cpython-37m-x86_64-linux-gnu.so -> /root/miniconda3/envs/caffex/lib/python3.7/site-packages/caffe2/python
```
so I'm not sure why your reference is failing. Just for kicks, can you move/copy the file in /root/miniconda3/envs/caffex/lib/python3.7/site-packages/caffe2/python around and see what happens? You shouldn't need to do this, but I want to verify the library is good.

**Comment by jojivk73** [comment]
You are right. It looks like it was my bad. I was executing it from the pytorch dir. If I change the dir to any other it is fine.

**Comment by jojivk73** [comment]
Thanks for quick the responses!
