### ISSUE TITLE
[ONNX] Fail to export inception_v3 with torch script

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#82370]
### 🐛 Describe the bug

```python
import torch
import torchvision

x = torch.randn(1, 3, 299, 299)
model = torchvision.models.inception_v3()
model = torch.jit.script(model)
torch.onnx.export(model, x, 'model.onnx', verbose=True)
```

Error appears to be related to new onnx optional export.

### Versions

PyTorch version: 1.13.0a0+git795399c
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.22.2
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-44-generic-x86_64-with-debian-bullseye-sid

**Comment by vadimkantorov** [comment]
Couple years back ONNX export after scripting was almost not supported: https://github.com/pytorch/pytorch/issues/42914 not sure if things changed now...

**Comment by BowenBao** [comment]
@vadimkantorov Thanks for input, I did a quick verification for #42914 and it appears all cases are working correctly. Seems the PR for fix did work and should have closed the issue earlier.
