### ISSUE TITLE
Access denied when downloading 0.3.1 for Mac on website

### ISSUE THREAD

**Issue by maoredman** [pytorch/pytorch#8238]
Hi,

When I tried to download [`torch-0.3.1-cp35-cp35m-macosx_10_7_x86_64.whl`](http://download.pytorch.org/whl/torch-0.3.1-cp35-cp35m-macosx_10_7_x86_64.whl) from the [PyTorch website](https://pytorch.org/previous-versions/), I encountered an access denied error (as can be seen from the screenshot below). Is there any way to fix this? Thanks

<img width="945" alt="screen shot 2018-06-07 at 10 26 48 pm" src="https://user-images.githubusercontent.com/10485739/41106114-e77fc80c-6aa1-11e8-89cf-bf13441a1bf4.png">

**Comment by soumith** [comment]
thanks so much for the report. Fixed the links now on the website via https://github.com/pytorch/pytorch.github.io/commit/f7a86e9a537de14ea1c2bd15c41b3dcbd32741b2
