### ISSUE TITLE
Behavior of torch.mean (and std) compared to numpy mean (std)

### ISSUE THREAD

**Issue by Mathieu-Seurin** [pytorch/pytorch#824]
Hi,

It's not a real issue, but i was surprised that 'mean' in torch doesn't behave the same way as numpy mean (and numpy std too)

```
>>> a = np.random.rand(4,4,2)
>>> a.mean((0,1))
array([ 0.41329336,  0.68183061])
>>> b = torch.Tensor(a)
>>> b.mean((0,2))
TypeError: mean received an invalid combination of arguments - got (tuple), but expected one of:
 * no arguments
 * (int dim)
      didn't match because some of the arguments have invalid types: (tuple)
```
Looking at the docs, it's expected that i get this error, but it would be very nice to have the same behavior

Thank you

**Comment by soumith** [comment]
this is actually a good feature to have, to take the mean at once over multiple dimensions.
And I think we can achieve this without any change to our backends (.contiguous().view(...).mean(...))

we'll work on this.

**Comment by mgrachten** [comment]
This applies to `sum` as well.

**Comment by fmassa** [comment]
A WIP implementation can be found in https://github.com/pytorch/pytorch/pull/2116
But it needs someone to complete it.

**Comment by SsnL** [comment]
closing in favor of #9703
