### ISSUE TITLE
cuda runtime error (77) : an illegal memory access at pytorch\aten\src\thcunn\generic/SpatialClassNLLCriterion.cu

### ISSUE THREAD

**Issue by adizhol** [pytorch/pytorch#8240]
## Issue description

with CUDA_LAUNCH_BLOCKING=1
I get the following stack trace on the **second** iteration:

> File "C:\Users\owner\AppData\Local\Programs\Python\Python35\lib\site-packages\torch\nn\functional.py", line 1334, in nll_loss
> return torch._C._nn.nll_loss2d(input, target, weight, size_average, ignore_index, reduce)
> RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\aten\src\thcunn\generic/SpatialClassNLLCriterion.cu:131
> 

This code is using CrossEntropyLoss, but another code that uses BCEWithLogits doen't throw any exceptions.

## Code example

    model = model.cuda(GPU_ID)
    optimizer = optim.Adam(model.parameters(), lr=config_segment.LEARN_RATE, weight_decay=config_segment.WEIGHT_DECAY)
    exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=config_segment.LEARN_RATE_STEP_PPERIOD, gamma=0.1)
    criterion = torch.nn.CrossEntropyLoss(ignore_index=labels.IGNORE)

     for (images, masks) in (train_loader):
            it += 1
            model.train()  # train mode.
            images = images.cuda(GPU_ID)
            masks = masks.cuda(GPU_ID)
            train_loss = 0
            optimizer.zero_grad()
            exp_lr_scheduler.step()
            x = model(images)
            # compute loss
            loss = criterion(x, masks) # Exception thrown here
            loss.backward()
            optimizer.step()

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.10.0-rc4

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 8.0.60
GPU models and configuration: Could not collect # GTX 1080 Ti
Nvidia driver version: Could not collect
cuDNN version: Could not collect # 6.0

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by soumith** [comment]
your `masks` are having out-of-bounds memory accesses. It's likely that `masks` has value less than 0, or greater than (nClasses-1)

**Comment by adizhol** [comment]
@soumith 
Looks you are correct. Silly bug on my part...
Thanks!
