### ISSUE TITLE
[MPS] `torch.full` does not work for boolean types

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#82427]
### 🐛 Describe the bug
```
% python -c "import torch;torch.full((3, 3), True, device='mps')"

/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:343: failed assertion `unsupported datatype for constant'
zsh: abort      python -c 
```

### Versions

1.12.0/nighlty

cc @kulinseth @albanD

**Comment by malfet** [comment]
Original repro was:
```
% python -c "import torch; x=torch.tensor(False, device='mps'); x.fill_(1);print(x)"
```
but after looking at 
https://github.com/pytorch/pytorch/blob/dc53cb4536839d11ab9a32ec10a0ff0dd96a590f/aten/src/ATen/native/mps/operations/ConstantOps.mm#L38-L40
I realized that it affects all fills

**Comment by kulinseth** [comment]
@malfet , can this be closed as well ?

**Comment by malfet** [comment]
I see this issue is fixed in Ventura preview, so I guess we can. 
@kulinseth but should we have a followup tracking issue somewhere to remove all those overrides once Ventura is publicly available? 
Or is it safe to assume, that MPSGraph framework is smart enough to eliminate those additional casts from the graph?

**Comment by kulinseth** [comment]
> I see this issue is fixed in Ventura preview, so I guess we can.
> @kulinseth but should we have a followup tracking issue somewhere to remove all those overrides once Ventura is publicly available?

@malfet That's a good question. We would still need those casts for Monterey, so I am not sure when is the right time to deprecate them. I think when Monterey is available we will have the availability checks to take the right path. Maybe when Ventura+1 is available we can remove the Monterey casts, but I am not sure. What do you think?
