### ISSUE TITLE
PyTorch/XLA compiler upgrade to c++17 breaks upstream torch tests

### ISSUE THREAD

**Issue by miladm** [pytorch/pytorch#82425]
### 🐛 Describe the bug

Turns our the recent pytorch/xla transition to c++17 breaks the upstream pytorch tests. To verify and scope this issue, I opened this [PR](https://github.com/pytorch/pytorch/pull/82391).

Sample Error:
```
NFO: Found applicable config definition build:linux in file /var/lib/jenkins/workspace/xla/third_party/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes

...

ERROR: /var/lib/jenkins/workspace/xla/third_party/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:780:11: Compiling tensorflow/compiler/xla/service/cpu/runtime_custom_call_status.cc failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-8/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 31 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from tensorflow/compiler/xla/service/cpu/runtime_custom_call_status.cc:18:
./tensorflow/compiler/xla/service/custom_call_status_internal.h:26:8: error: no template named 'optional' in namespace 'std'
  std::optional<std::string> message;
  ~~~~~^
./tensorflow/compiler/xla/service/custom_call_status_internal.h:34:6: error: no template named 'optional' in namespace 'std'
std::optional<absl::string_view> CustomCallStatusGetMessage(
~~~~~^
```

Looking at the error logs, it seems the upstream stack has a conflict on `c++` version that's not present in the PyTorch/XLA CI level. As a result, PyTorch tests fail while PyTorch/XLA tests pass.

I opened this issue to track our investigation progress and push the solution.

### Versions

Collecting environment information...
PyTorch version: 1.12.0a0+git6e292f1
Is debug build: True
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 11.3.0-3) 11.3.0
Clang version: 13.0.1-6
CMake version: version 3.19.6
Libc version: glibc-2.33

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.17.11-1rodete2-amd64-x86_64-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.12.0a0+gitde18c28
[pip3] torch-xla==1.12
[pip3] torchvision==0.13.0a0+08cc9a7
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.0.1           h06a4308_117
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.12.0a0+git4afe2db          pypi_0    pypi
[conda] torch-xla                 1.12                     pypi_0    pypi
[conda] torchvision               0.13.0a0+08cc9a7          pypi_0    pypi

cc @malfet @seemethere @pytorch/pytorch-dev-infra @bdhirsh

**Comment by miladm** [comment]
CC @wconstab @Krovatkin @yeounoh @JackCaoG

**Comment by malfet** [comment]
somehow the same happened in trunk CI yesterday
Can it be that docker container build for your PR somehow affected trunk, see https://github.com/pytorch/pytorch/runs/7551419792?check_suite_focus=true

cc: @seemethere , @janeyx99

**Comment by miladm** [comment]
That's right, it must be due to [this line](https://github.com/pytorch/pytorch/runs/7551419792?check_suite_focus=true#step:10:4734) where `c++17` is called.

**Comment by miladm** [comment]
After pinning the upstream pytorch to a new [tf_pin PR](https://github.com/pytorch/xla/pull/3794), and simplifying the `c++14` commands, I continue to observe the [following line](https://github.com/pytorch/pytorch/runs/7571906654?check_suite_focus=true#step:10:4753) breaking the build in this [PR](https://github.com/pytorch/pytorch/pull/82391/).

@yeounoh turns out the bazel environment variable is not the root cause of this issue.

**Comment by miladm** [comment]
@malfet do you have a guidance on where is a good candidate starting script to look into? 

As mentioned on DM, I suspect we have an inconsistency introduced by either an environment variable, or a build call that doesn't adhere to the `c++17` commands we baked into PyTorch/XLA build script.

**Comment by JackCaoG** [comment]
eh... I figured out what happened.. this is funny. Looking at the log, the C++ opt actually coming from the tensrfolow bazel file.

```
2022-07-29T02:33:25.2975558Z [32mINFO: [0mFound applicable config definition build:linux in file /var/lib/jenkins/workspace/xla/third_party/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
```

Then I look at how upstream checkout pytorch/xla and saw, it is
```
2022-07-29T02:32:03.3373009Z + git clone --recursive --quiet https://github.com/pytorch/xla.git
2022-07-29T02:32:52.4610102Z + pushd xla
2022-07-29T02:32:52.4610389Z /var/lib/jenkins/workspace/xla /var/lib/jenkins/workspace
2022-07-29T02:32:52.4612552Z ++ cat ../.github/ci_commit_pins/xla.txt
2022-07-29T02:32:52.4625299Z + git checkout tf_june_pin2
```

If it first clone with the master, and then checkout a new commit/branch, we will have to do the submodule update. Adding that to https://github.com/pytorch/pytorch/blob/68bd687297501b89b672c5d41f71d35c0139c9ac/.jenkins/pytorch/common_utils.sh#L119 should fix the issue/

**Comment by miladm** [comment]
Thanks @JackCaoG. I will take a pass at it.

**Comment by miladm** [comment]
I added https://github.com/pytorch/pytorch/pull/82497 to resolve the comment @JackCaoG made above. This is a necessary PR, though since the failure remains, we should investigate further.

I looked into the test error logs in https://github.com/pytorch/pytorch/pull/82497. Seems like all `c++17` flags are included as intended for compilation. At the same time, the commit hash for the new tf pin is pulled as intended. It's puzzling why the code breaks despite these fixes. I wonder if the docker env we build the test has a conflicting config that causes the crash.

**Comment by miladm** [comment]
The silver lining is that the latest PR did in fact reduce the number of test failures from 3 in https://github.com/pytorch/pytorch/issues/82425 to 1 in https://github.com/pytorch/pytorch/pull/82497.

**Comment by miladm** [comment]
Closing this issue as the latest changes seem to have unblocked the pytorch failures due to pytorch/xla `c++17` migration.

**Comment by malfet** [comment]
Re-opening as I just hit it 30 min ago. From https://github.com/pytorch/pytorch/runs/7846316819?check_suite_focus=true
```
ERROR: /var/lib/jenkins/workspace/xla/third_party/tensorflow/tensorflow/compiler/xla/service/BUILD:6094:11: Compiling tensorflow/compiler/xla/service/custom_call_status.cc failed: (Exit 1): clang failed: error executing command /usr/lib/llvm-8/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 30 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from tensorflow/compiler/xla/service/custom_call_status.cc:16:
./tensorflow/compiler/xla/service/custom_call_status_internal.h:26:8: error: no template named 'optional' in namespace 'std'
  std::optional<std::string> message;
  ~~~~~^
```

**Comment by huydhn** [comment]
> Re-opening as I just hit it 30 min ago. From https://github.com/pytorch/pytorch/runs/7846316819?check_suite_focus=true

I think having https://github.com/pytorch/pytorch/pull/82497 fixes the issue:

* https://github.com/pytorch/pytorch/pull/83485 was before https://github.com/pytorch/pytorch/pull/82497 and XLA test fails
* while https://github.com/pytorch/pytorch/pull/83484 had the fix and passed without any issue

So we just need to rebase and retry

**Comment by miladm** [comment]
Looks like all is good. Closing the issue. Feel free to reopen if needed.
