### ISSUE TITLE
Cumulative matrix product

### ISSUE THREAD

**Issue by PierreGuilmin** [pytorch/pytorch#82431]
### 🚀 The feature, motivation and pitch

Exactly the same as `torch.cumprod` but using `matmul` instead of the element-wise multiplication. I'd be happy to help implementing this feature if someone can give me a few pointers.

### Additional context

Context is that I am evaluating a piecewise time constant Hamiltonian evolution using Schrödinger equation, and I'd like to cumulatively multiply the unitary evolution operator to get the system state after each step (https://en.wikipedia.org/wiki/Hamiltonian_(quantum_mechanics)#Schr%C3%B6dinger_equation).

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
I don't think we can do this better than implementing the naïve loop really. What are the benefits that you expect to have from having this implemented in core over implementing it in Python? Do you have relevant benchmarks?

**Comment by PierreGuilmin** [comment]
Not much except having a fast for loop. So you mean doing something like the following? Or do you have a smarter way in mind? (I need the reverse cumulative matrix product actually)
```python
U = ...  # tensor of dimension (d, n, n)
U_cum = [U[0]]
for u in U[1:]:
    U_cum.append(torch.matmul(u, U_cum[-1]))
U_cum = torch.stack(U_cum)  # tensor of dimension (d, n, n)
```

**Comment by Lezcano** [comment]
Exactly. I don't think we can do better than that in C++ land. The efficiency would be exactly the same as your Python implementation due to the async computations of the GPU and the fact that the code above does not synchronise. 

I'm going to tentatively close this one.

**Comment by Changkai9888** [comment]
https://github.com/Changkai9888/Pytorch_tool/blob/main/associative_law_operation_accelerator_for_pyorch.py
You can do and write calculations using my code, not just matrix multiplication, but any sequential operation that is associative. Of course, the current version is not the best, welcome your optimization.
可以使用我的代码进行并写的计算得到，不仅仅是矩阵乘法，任何符合结合律的序列运算都可以得到。当然目前这个版本并不是最好的，欢迎您的优化。
