### ISSUE TITLE
Multi-process Pipe()

### ISSUE THREAD

**Issue by Youhe-Jiang** [pytorch/pytorch#82462]
### 🚀 The feature, motivation and pitch

May I ask when the multi-process pipe will be released, and is there any test version that can be used? Thanks for any help and feedback.

cc @VitalyFedyunin

**Comment by albanD** [comment]
Hi,

Isn't `torch.multiprocessing.Pipe` working for you?

**Comment by VitalyFedyunin** [comment]
Do you mean DataPipe? If so please check https://github.com/pytorch/data for Multiprocessing support.

**Comment by Youhe-Jiang** [comment]
> Hi,
> 
> Isn't `torch.multiprocessing.Pipe` working for you?

Sorry for taking so long to reply, thanks for your help, I'll give this API a try.

**Comment by Youhe-Jiang** [comment]
> Do you mean DataPipe? If so please check https://github.com/pytorch/data for Multiprocessing support.

Thanks for your help, I'll take a look at this API.
