### ISSUE TITLE
bug: torch.linalg.svd get wrong results

### ISSUE THREAD

**Issue by wuhaozhe** [pytorch/pytorch#82473]
### 🐛 Describe the bug

When I run torch.linalg.svd() on 3 * 3 matrix, I obtained the wrong results. At first, all of U, S, Vh are zero matrices. When I run svd on the same matrices for the second time, I can obtain correct results.

```python
import numpy as np

a = np.array([[56.6896,  4.7862, 10.0108], [ 4.7059, 90.4238, 10.5659], [10.3995, 11.0197, 12.6870]])

import torch

b = torch.from_numpy(a).cuda()


print(torch.linalg.svd(b))

print(torch.linalg.svd(b))
```

I got the following results:

```
torch.return_types.linalg_svd(
U=tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', dtype=torch.float64),
S=tensor([0., 0., 0.], device='cuda:0', dtype=torch.float64),
Vh=tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0', dtype=torch.float64))
torch.return_types.linalg_svd(
U=tensor([[ 0.1703,  0.9648, -0.2005],
        [ 0.9731, -0.1967, -0.1198],
        [ 0.1550,  0.1747,  0.9723]], device='cuda:0', dtype=torch.float64),
S=tensor([92.9466, 57.5495,  9.3063], device='cuda:0', dtype=torch.float64),
Vh=tensor([[ 0.1705,  0.9739,  0.1501],
        [ 0.9659, -0.1953,  0.1702],
        [-0.1951, -0.1160,  0.9739]], device='cuda:0', dtype=torch.float64))
```

I don't know what's the problem with SVD.

### Versions

[pip3] numpy==1.22.4
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    defaults
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py39h7f8727e_0    defaults
[conda] mkl_fft                   1.3.1            py39hd3c417c_0    defaults
[conda] mkl_random                1.2.2            py39h51133e4_0    defaults
[conda] numpy                     1.22.3           py39he7a7128_0    defaults
[conda] numpy                     1.22.4                    <pip>
[conda] numpy-base                1.22.3           py39hf524024_0    defaults
[conda] pytorch                   1.12.0          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.12.0                    <pip>
[conda] torchaudio                0.12.0               py39_cu113    pytorch
[conda] torchvision               0.13.0                    <pip>
[conda] torchvision               0.13.0               py39_cu113    pytorch

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by wuhaozhe** [comment]
Updating the information about system and hardware:

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS (x86_64)
GCC version: (Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0 20181026
Clang version: Could not collect
CMake version: version 3.12.4
Libc version: glibc-2.27

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-43-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 455.38
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

**Comment by xwang233** [comment]
Thank you for reporting this. Do you see the same issue with a torch 1.12 + cuda 11.6 wheel?

**Comment by wuhaozhe** [comment]
> Thank you for reporting this. Do you see the same issue with a torch 1.12 + cuda 11.6 wheel?

I have tried torch 1.12 + cuda 10.2 and the results are correct, currently I haven't tried cuda 11.6

**Comment by xwang233** [comment]
This could be a similar issue as #70669. It could be a cusolver library issue in cuda 11.3. It's always recommended to use the latest cuda version.

**Comment by Lezcano** [comment]
closing this one as it works on the latest version. If anyone finds a repro in 11.6 we may reopen it.

That being said, it's particularly annoying that it returns silently incorrect values :(

**Comment by XiaoXiao-Woo** [comment]
I have tried torch 1.13 + cuda 11.6 and the results are still incorrect. I have opened the issue as https://github.com/pytorch/pytorch/issues/116394.
