### ISSUE TITLE
Conda repodata broken for osx arm64

### ISSUE THREAD

**Issue by divideconcept** [pytorch/pytorch#82483]
### 🐛 Describe the bug

It's impossible to install pytorch and its ecosystem using conda (`conda install pytorch torchvision torchaudio -c pytorch`) on a M1 mac (osx arm64) due to current_repodata being broken :
https://conda.anaconda.org/pytorch/osx-arm64/current_repodata.json

It only list old versions of pytorch and doesn't list torchvision or torchaudio.

```
conda install pytorch torchvision torchaudio -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - torchaudio

Current channels:

  - https://conda.anaconda.org/pytorch/osx-arm64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

It was working a week ago but it seems something changed with the repodata file recently.

See also this issue: https://github.com/pytorch/audio/issues/2536#issuecomment-1198637540

### Versions

M1 macs (osx arm64) 

cc @ezyang @gchanan @zou3519 @malfet @albanD

**Comment by malfet** [comment]
Either this one or https://github.com/pytorch/pytorch/issues/82428 should be closed

**Comment by seemethere** [comment]
Closing this one in favor of #82428
