### ISSUE TITLE
Support Quantized Slice / getitem operator

### ISSUE THREAD

**Issue by kev-zheng** [pytorch/pytorch#82480]
### 🚀 The feature, motivation and pitch

We have a model with slice operator like x[:, :, -50]

Here is a toy example:
```
from torch.ao.quantization.qconfig import (
    QConfig,
    get_default_qconfig,
    get_default_qat_qconfig,
)
from torch.quantization.quantize_fx import convert_fx
from torch.quantization.quantize_fx import prepare_fx
from torch.quantization.quantize_fx import prepare_qat_fx
import torch

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv1d(in_channels=5, out_channels=5, kernel_size=5, padding=0)
        self.conv2 = torch.nn.Conv1d(in_channels=5, out_channels=5, kernel_size=5, padding=0)
        
    def forward(self, inputs):
        # inputs: [1, 5, 10]
        x1 = self.conv1(inputs)
        # x: [1, 5, 6]
        x1 = x1 + inputs[:, :, -6:]
        
        x2 = self.conv2(x1)
        x2 = x2 + x1[:, :, -2:]
        return x2

mod = M()
mod.eval()
mod(torch.rand(1,5,10))

qconfig_dict = {"": get_default_qconfig()}
prepared = prepare_fx(mod, qconfig_dict, example_inputs=torch.rand(1,5,10))
converted = convert_fx(prepared)
```

Using FxGraphDrawer, we can visualize the converted fx graph.
<img width="685" alt="image" src="https://user-images.githubusercontent.com/24661601/181799252-6899e3be-3de9-4490-9261-73496c491885.png">

Notice that `getitem_1` is wrapped with dequant and quantize nodes.
![image](https://user-images.githubusercontent.com/24661601/181799358-f79f2e78-3b61-4e83-956b-87046cf5009e.png)

These dequant + quantize operators are causing significant latency slowdowns in our model; perhaps enabling this operator to work on quantized Tensors will work.

### Alternatives

We don't currently have any workaround to this -- any ways that we can achieve this would be much appreciated!

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by andrewor14** [comment]
Closing this since https://github.com/pytorch/pytorch/pull/82675 was merged
