### ISSUE TITLE
public/cuda.cmake uses cuda_select_nvcc_arch_flags

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#8249]
https://github.com/pytorch/pytorch/blob/346568d40f301809591ae43fb4902c6ea93edce9/cmake/public/cuda.cmake#L343
and neither requires cmake 3.9 nor adds Modules_CUDA_fix to cmake modules. This is breaking ubuntu 16.04 builds, and getting cmake 3.9 on ubuntu 16.04 is a pain. 
cc @Yangqing

**Comment by ngimel** [comment]
Yeah, I know that updating cmake would solve it, however, they should not have merged a breaking commit https://github.com/pytorch/pytorch/commit/56b1dcccf65f3b297d3a6d5edce5d26537273318

**Comment by Yangqing** [comment]
Fix PR #8271 passed our manual check (thanks @soumith) and is landed. I assume this would fix the issue, so closing this for now - feel free to reopen if problem persists!

**Comment by ngimel** [comment]
It works, thanks!

**Comment by ezyang** [comment]
@yf225 Maybe we can switch up one of our existing Docker images to be on an older version of cmake?
