### ISSUE TITLE
Unable to run pytorch unit test because CI environment variables are not available

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#82492]
### 🐛 Describe the bug

Unable to run pytorch unit test because CI environment variables are not available

PR https://github.com/pytorch/pytorch/pull/79898 introduced `BUILD_ENVIRONMENT ` which open source build doesn't have
 https://github.com/pytorch/pytorch/blob/1332182329f44848041a53036f32bf40a7172fe4/torch/testing/_internal/common_utils.py#L698

thus KeyError is raised

```python
Running test_ops ... [2022-07-28 03:25:21.888236]
Executing ['/opt/conda/bin/python', '-bb', 'test_ops.py', '-v', '--save-xml', '--import-slow-tests', '--import-disabled-tests'] ... [2022-07-28 03:25:21.888297]
Traceback (most recent call last):
  File "test_ops.py", line 1736, in <module>
    run_tests()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 716, in run_tests
    "cuda" in os.environ["BUILD_ENVIRONMENT"] and "linux" in os.environ["BUILD_ENVIRONMENT"]
  File "/opt/conda/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'BUILD_ENVIRONMENT'
test_ops failed!
```

PR https://github.com/pytorch/pytorch/pull/81915 introduced `TEST_CONFIG` which open source build doesn't have

https://github.com/pytorch/pytorch/blob/78482f9e7c95b81f403182352398bff7a0acc2ae/test/run_test.py#L871

thus KeyError is raised

```python
Traceback (most recent call last):
  File "test/run_test.py", line 1000, in <module>
    main()
  File "test/run_test.py", line 949, in main
    selected_tests = get_selected_tests(options)
  File "test/run_test.py", line 898, in get_selected_tests
    if os.environ["TEST_CONFIG"] not in test_file_times:
  File "/opt/conda/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'TEST_CONFIG'
```

Are those environment variables necessary for open source build to run pytorch unit tests? How should I setup those variables?

### Versions

4f2a475f7f00a2cbb21d5e97edadc8aba340f50c

cc @seemethere @malfet @pytorch/pytorch-dev-infra @mruberry @janeyx99 @clee2000 @ptrblck

**Comment by malfet** [comment]
Hmm, this should not have been the case. Grabbing for myself unless you already have a one liner that fixes this particular issue
