### ISSUE TITLE
Easy way of creating your own custom cuda kernels

### ISSUE THREAD

**Issue by bordingj** [pytorch/pytorch#825]
In chainer/cupy, creating your own custom kernel is as easy as:

```
@cp.util.memoize(for_each_device=True)
def _get_fill_c_next_and_h_kernel():
    cuda_lib = cp.cuda.compile_with_cache("""
    
        extern "C" __global__ void fill_c_next_and_h(
                       const float* a, const float* i, const float* f, const float* o,
                       const float* c_prev, float* c_next, float* h, 
                       int num_batches,
                       int num_samples,
                       int hidden_size) 
        {
            int batch_idx  = threadIdx.x + blockIdx.x * blockDim.x;
            int sample_idx = threadIdx.y + blockIdx.y * blockDim.y;
            int hidden_idx = threadIdx.z + blockIdx.z * blockDim.z;

            if (batch_idx < num_batches && sample_idx < num_samples && hidden_idx < hidden_size){
                
                int idx = (batch_idx*num_samples*hidden_size
                           + sample_idx*hidden_size
                           + hidden_idx);
                
                c_next[idx] = i[idx]*a[idx]+c_prev[idx]*f[idx];
                h[idx]      = o[idx]*tanhf(c_next[idx]);
            }
        }
       """)
    return cuda_lib.get_function('fill_c_next_and_h')
```
And then calling it with:

```
def get_memory_cell_and_output_batched(a, i, f, o, c_prev):
        
    num_batches = a.shape[0]
    num_samples = a.shape[1]
    hidden_size = a.shape[2]
    c_next = cp.empty_like(c_prev)
    h = cp.empty_like(c_prev)
    
    fill_c_next_and_h = _get_fill_c_next_and_h_kernel()
    
    bdim = (4,16,8)
    gdim = (int(math.ceil(num_batches/4.0)), 
            int(math.ceil(num_samples/16.0)),
            int(math.ceil(hidden_size/8.0))
            )
    fill_c_next_and_h(grid=gdim, block=bdim,
                      args = (
                              a, i, f, o,
                              c_prev, c_next, h,
                              num_batches,
                              num_samples,
                              hidden_size
                              )
                      )

    return c_next, h
```

It could be cool if something similar was possible in pytorch.

**Comment by soumith** [comment]
@szagoruyko has some scripts on creating custom kernels on the fly using pycuda. Sergey, can you share them?

**Comment by soumith** [comment]
we also provide examples of easily interfacing with CUDA code in https://github.com/pytorch/extension-ffi where you dont have to write additional bindings

**Comment by szagoruyko** [comment]
it is almost as easy as in chainer, here's im2col with pycuda on pytorch tensors https://gist.github.com/szagoruyko/89f83b6f5f4833d3c8adf81ee49f22a8. It uses NVRTC python bindings to compile PTX and pycuda to execute. This doesn't work with multigpu because pycuda is very conservative about stream sharing, so we will add a similar API to execute PTX in pytorch in non-default stream

**Comment by bordingj** [comment]
nice, thanks. 
It would be cool if you could do a similar thing without pycuda and without having you know about the pytorch C++ API.

**Comment by soumith** [comment]
i dont think we want to support agnosticism to pycuda/pytorch C++ API yet. PyCuda seems like a reasonable way forward and we'll likely try build upon that for jitting CUDA kernels.

**Comment by soumith** [comment]
i'm going to close the issue now, we're going to try craft helper libs at some point, sergey, adam and I are discussing this.

**Comment by QuantScientist** [comment]
Hello :)
So what is the best practice now? If I want to implement a mathematical function in CUDA + PyTorch, and I don't need Autograd to be involved, But I do want to enforce the use of PyTorch tensors, should I use CuPy or cffi?

**Comment by pclucas14** [comment]
Facing a similar issue, would love to know what best practice is.

**Comment by jekbradbury** [comment]
The easiest way is to use cupy like in https://github.com/szagoruyko/pyinn or https://github.com/salesforce/pytorch-qrnn, but the best practice for code that could eventually be merged into PyTorch master would be to add an ATen native function like ROI pooling [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/NativeFunctionsCuda.cu#L37).

**Comment by emited** [comment]
Is it possible to create ATen functions and add them to a already built version of pytorch ?

**Comment by soumith** [comment]
@emited not yet, we're working on ATen extensions

**Comment by legendongary** [comment]
Would it be possible to write cuda files like in Matlab with mex: [https://www.mathworks.com/help/distcomp/run-mex-functions-containing-cuda-code.html](url)

**Comment by t-vi** [comment]
Oh, I think it's just a matter of having a function that writes the kernel with some boilerplate to a file, executes an extension build, and loads it, but I think it's really neat to be able to quickly iterate those from Python rather than having to do these externally.

**Comment by goldsborough** [comment]
We have this, we call them JIT C++ extensions: https://github.com/pytorch/pytorch/blob/master/test/test_cpp_extensions.py#L200 They've been around for a few months, but they appeared after the official tutorial, so you might have missed them.

**Comment by ZahraGithub** [comment]
Hi,
I am a beginner in pytorch. I want to define my proposed kernel and add it to a CNN. I am searching about 2 or 3 days. I am so confused! Because I do not know, I should implement CNN by C++ from scratch and build it and add  it to pytorch or it is enough to implement a new convolution layer by my own kernel and add it to existing CNN in pytorch?!
I think the second solution is correct. If it is, I appreciate it if you guide me how do this 2 steps:
1. Making a c++ convolution layer
2. Add this built new layer to a CNN in pytorch

Many thanks before all
