### ISSUE TITLE
Reshape operator in ONNX does not take in 2 inputs

### ISSUE THREAD

**Issue by SherryPu1219** [pytorch/pytorch#8250]
I am converting a pytorch model to ONNX using torch.onnx.export(). My model is using view() to do a reshape. The converted model has a reshape operator that takes in two inputs: a tensor to be reshaped and another tensor specifying the new shape . But ONNX 1.0 only takes in a tensor and drop out the "shape" input and treat it as an attribute. So the converted model cannot be consumed in ONNX 1.0.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
@SherryPu1219 - That depends on the opset version. The last few releases of PyTOrch have used the later versions of ONNX (ONNX1.6, ONNX 1.7) and there Reshape op takes shape as an input. You can check the opset version in your exporter model and then check the ONNX spec for Reshape op for that opset. If you see any incinsistency please reopen this issue.
