### ISSUE TITLE
Memory leak under "full backward hook" with "backward(create_graph=True)" 

### ISSUE THREAD

**Issue by andres-fr** [pytorch/pytorch#82528]
### 🐛 Describe the bug

This minimal bug-reproducing example illustrates a memory leak in PyTorch
associated to 2 conditions:

1. Backprop is computed via ``loss.backward(create_graph=True)``
2. A handle is registered via ``register_full_backward_hook``

While I'm aware of the pitfalls associated to backward with create graph, e.g.
https://github.com/pytorch/pytorch/issues/4661#issuecomment-640335476
https://github.com/pytorch/pytorch/issues/4661

And the suggestion of using torch.autograd.grad instead, I think this issue
is different because it is specifically associated to the presence of a hook.
This other issue from Jan 9, 2022 seems identical, but was misteriously marked as complete without further remarks?
https://github.com/pytorch/pytorch/issues/71068

The leak can be tested by running this example until the GPU runs out of memory
(8GB after ca. 12 epochs) and/or by inspecting ``nvidia-smi``.

### Why this is bad:

Research on new optimizers often requires retaining the graph, and libraries like [BackPACK](https://backpack.pt/) make use of hooks to facilitate computation of derived quantities immensely. Some of those quantities require "create_graph=True" (e.g. for second-order optimization).
This memleak prevents any consistent usage of PyTorch for those applications.

```python3
#!/usr/bin/env python
# -*-coding:utf-8-*-


"""
"""


import torch
import torchvision
import torch.nn.functional as F


SEED = 123
BATCH_SIZE = 64
LR = 0.01
NUM_EPOCHS = 100
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


torch.manual_seed(SEED)
fmnist_dataset = torchvision.datasets.FashionMNIST(
    root="/tmp", train=True, download=True,
    transform=torchvision.transforms.Compose(
        [torchvision.transforms.ToTensor(),
         torchvision.transforms.Normalize((0.1307,), (0.3081,))]))

fmnist_dl = torch.utils.data.dataloader.DataLoader(
    fmnist_dataset, batch_size=BATCH_SIZE, shuffle=True)


model = torch.nn.Sequential(
    torch.nn.Flatten(start_dim=1, end_dim=-1),
    torch.nn.Linear(in_features=784, out_features=1000, bias=True),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features=1000, out_features=500, bias=True),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features=500, out_features=100, bias=True),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features=100, out_features=10, bias=True)).to(DEVICE)
loss_fn = torch.nn.BCEWithLogitsLoss()
opt = torch.optim.SGD(model.parameters(), lr=LR)

# Just having this dummy hook with backward(create_graph=True) produces a leak
hook_handle = model.register_full_backward_hook(lambda a, b, c: None)

for epoch in range(1, NUM_EPOCHS + 1):
    for i, (inputs, targets) in enumerate(fmnist_dl, 1):
        inputs = inputs.to(DEVICE)
        targets = torch.nn.functional.one_hot(
            targets, num_classes=10).to(inputs.dtype).to(DEVICE)
        #
        opt.zero_grad()
        outputs = model(inputs)
        loss = loss_fn(outputs, targets)
        loss.backward(create_graph=True)
        opt.step()

        # removing the hook fixes the leak...
        hook_handle.remove()
        # ... unless we create a new hook!
        hook_handle = model.register_full_backward_hook(lambda a, b, c: None)

        # Also note that this suggested approach doesn't help
        for param in model.parameters():
            param.grad = None

        #
        if i % 50 == 0:
            print(f"[{epoch}/{i}]:", loss.item())
```

### Versions

I don't have time to check the contents of collect_env.py right now, but I see that OS calls are involved.

My versions are:
```
python                    3.8.13               h12debd9_0  
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
Ubuntu 20.04.4 LTS 64bit
GPU: NVIDIA GeForce RTX 3070 Laptop GPU
```

And nvidia-smi:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8    16W /  N/A |     10MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1450      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      1927      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by andres-fr** [comment]
This may be some progress:

If we look at the code in `torch.nn.Module.__call__` permalinked below, we observe that specifically backward hooks get a side-effect treatment, namely the hook is registered into the `grad_fn` of the module's forward output tensor:

https://github.com/pytorch/pytorch/blob/4afd62db099f8e967a30aea66c1f345b5cbc99e2/torch/nn/modules/module.py#L371

And while our hook may lack any leaky references, *the hook is wrapped with a reference to the module before being registered*.
Therefore, `grad_fn` will store a hook, which contains a reference to the module.

My conjecture now is that when we retain the graph we also retain the `grad_fn` objects. If no backward hooks are present, this doesn't cause any leaks, but otherwise the graph we are retaining is implicitly retaining other heavyweight references, because grad_fn retains the hook, and the hook retains the module.

**Comment by andres-fr** [comment]
OK, after some tinkering with the code I found a hotfix that is able to fix the leak while keeping the hook and backward languages untouched. It goes like this:

### Inside `BackwardHook`:

https://github.com/pytorch/pytorch/blob/e3210ca184c87bfa5ba16cf6a83ed83b21865dcf/torch/utils/hooks.py#L180

We see that the line `grad_fn.register_hook(hook)` returns a handle that is not getting captured. We want to capture the handles for any registered hook into a global datastructure.

We first define a module-level list inside of `hooks.py`:

```python3
HANDLES = []
```

And then we replace the above line with the following:

```python3
handle = grad_fn.register_hook(hook)
global HANDLES
HANDLES.append(handle)
```


### In our training script (see issue description above):

Even if we wanted to keep our graph around, at some point we want to get rid of it (in our case let's say at the end of the training batch). We don't keep any python references to it and it should be garbage collected, but, as documented above, there is a leak. The leak disappears if we add 3 lines to our training loop:

```python3
for epoch in range(1, NUM_EPOCHS + 1):
    for i, (inputs, targets) in enumerate(fmnist_dl, 1):
        inputs = inputs.to(DEVICE)
        targets = torch.nn.functional.one_hot(
            targets, num_classes=10).to(inputs.dtype).to(DEVICE)
        #
        opt.zero_grad()
        outputs = model(inputs)
        loss = loss_fn(outputs, targets)
        loss.backward(create_graph=True)
        opt.step()
        #
        if i % 50 == 0:
            print(f"[{epoch}/{i}]:", loss.item())
        # these are the lines to hotfix the leak
        while torch.utils.hooks.HANDLES:
            xx = torch.utils.hooks.HANDLES.pop()
            xx.remove()
```

Note that we are doing nothing else but removing any handles that may have been created during fwprop. Also note that all prior functionality, including the hook, is retained.

-------------------------------------

# Discussion:

* Note that the fix did *not* involve setting the parameter gradients to `None`, as suggested in some places. This is a hook-specific issue.
* Note that if we don't delete the `HANDLES`, they increase by 1 on each iteration. This makes sense, since every forward pass will create a new graph and register new handles.
* Note that if we remove our original `hook_handle`, the script will leak until we remove, and then it will stop leaking but the hook will also stop running. It seems that our hook handle has global+leaky effects, while the HANDLES are specific to the batch graph.
* Furthermore, if we remove `hook_handle` and re-register it again at global level (i.e. we call `hook_handle = model.register_full_backward_hook(hook)` again inside the training loop after deleting the hook handle), the leak will persist, against our intuition. I don't have a good explanation for this.
* A colleague mentioned that the hook system got refactored in v1.7, and that backward hooks got a new "full backward hook" implementation.  Furthermore, they recall not having this leak. Looking into the sources, I recall that the "old" implementation makes use of global hooks and the new one (i.e. full backward hooks) makes use of `self` instead. Given the observations so far and the fact that the other issue identical to this one was from January 2022, I would argue that **the new implementation with full backward hooks may be behind the memory leak**. ButI would also argue that **the best fix is probably not so much going back to the old ways, but to keep proper track of the handles: the library should allow users to access all handles at all points, since as we have seen they can lead to very large, show-stopping leaks**.

In any case I hope this helps someone, and I welcome any comments on this. I am happy to make a PR if the core devs want and we agree on some specific directions (clearly this hotfix is not a permanent solution).

Cheers!
Andres

**Comment by albanD** [comment]
Hey!
Thanks a lot for the in-depth debugging on this. I am not sure that creating this global table is a good long term solution though.

I would like to know better what is the full ref cycle that creates this leak.
It is also important to keep in mind that cycles of python objects are not a problem as the gc will be able to properly clear these.
So there must be some c++ objects involved in this that make part of the cycle...

**Comment by albanD** [comment]
Actionable as we need to find the cycle and either break it or ensure the python gc can do so.

**Comment by andres-fr** [comment]
Yes, as I mentioned my hotfix is clearly not a permanent solution.
Thanks to you guys for the quick reaction, I'm glad to see that the PR fixes this at the C++ level! Keep up the great work.

Maybe others have comments about the full ref cycle that creates the leak, from my side nothing else so feel free to close the issue if desired. Cheers

**Comment by soulitzer** [comment]
Np! The full cycle should be `grad_output -> grad_output.grad_fn -> graph -> hook -> grad_output`.
Also FYI, I made a small update - previously the fix was not correct when there are multiple hooks registered.

**Comment by andres-fr** [comment]
Yes, note that my quickfix is very situational. There are many ways to register a hook, not only through modules, and also many types of hook. Ideally, the solution covers all of those cases. Thanks again!

**Comment by andres-fr** [comment]
Also, may I ask what kind of tool/procedure did you use to identify such a cycle (or more in general reference trees)?
Just inspecting the code?

**Comment by albanD** [comment]
I don't know what Jeffrey used in this case but for the python side, I usually use https://mg.pov.lt/objgraph/ 
For the part on the c++ side, you have to look at the code to see what is stored on each c++ object I'm afraid.

**Comment by SJShin-AI** [comment]
```f-dangel/backpack#258```

**Comment by SJShin-AI** [comment]
```#f-dangel/backpack#258```

**Comment by SJShin-AI** [comment]
- I am also experiencing the memory leak problem from the provided code in [](https://github.com/f-dangel/backpack/issues/258)

**Comment by albanD** [comment]
Hi,

There is no very reliable way to do it no I'm afraid.
If you can do install from source, you can get the source for the version you use and cherry pick the fix on top of it.

If not, since the fix is python only, you can actually manually change the python files in your current install to add the fix by hand (https://github.com/pytorch/pytorch/pull/82788/files). But that will be overwritten when you upgrade PyTorch in the future or re-install it.

**Comment by SJShin-AI** [comment]
Thanks for your careful reply.
Actually i am working on monkey patching on the current pytorch.
Hope it works...

**Comment by SJShin-AI** [comment]
> OK, after some tinkering with the code I found a hotfix that is able to fix the leak while keeping the hook and backward languages untouched. It goes like this:
> 
> ### Inside `BackwardHook`:
> https://github.com/pytorch/pytorch/blob/e3210ca184c87bfa5ba16cf6a83ed83b21865dcf/torch/utils/hooks.py#L180
> 
> We see that the line `grad_fn.register_hook(hook)` returns a handle that is not getting captured. We want to capture the handles for any registered hook into a global datastructure.
> 
> We first define a module-level list inside of `hooks.py`:
> 
> ```python
> HANDLES = []
> ```
> 
> And then we replace the above line with the following:
> 
> ```python
> handle = grad_fn.register_hook(hook)
> global HANDLES
> HANDLES.append(handle)
> ```
> 
> ### In our training script (see issue description above):
> Even if we wanted to keep our graph around, at some point we want to get rid of it (in our case let's say at the end of the training batch). We don't keep any python references to it and it should be garbage collected, but, as documented above, there is a leak. The leak disappears if we add 3 lines to our training loop:
> 
> ```python
> for epoch in range(1, NUM_EPOCHS + 1):
>     for i, (inputs, targets) in enumerate(fmnist_dl, 1):
>         inputs = inputs.to(DEVICE)
>         targets = torch.nn.functional.one_hot(
>             targets, num_classes=10).to(inputs.dtype).to(DEVICE)
>         #
>         opt.zero_grad()
>         outputs = model(inputs)
>         loss = loss_fn(outputs, targets)
>         loss.backward(create_graph=True)
>         opt.step()
>         #
>         if i % 50 == 0:
>             print(f"[{epoch}/{i}]:", loss.item())
>         # these are the lines to hotfix the leak
>         while torch.utils.hooks.HANDLES:
>             xx = torch.utils.hooks.HANDLES.pop()
>             xx.remove()
> ```
> 
> Note that we are doing nothing else but removing any handles that may have been created during fwprop. Also note that all prior functionality, including the hook, is retained.
> 
> # Discussion:
> * Note that the fix did _not_ involve setting the parameter gradients to `None`, as suggested in some places. This is a hook-specific issue.
> * Note that if we don't delete the `HANDLES`, they increase by 1 on each iteration. This makes sense, since every forward pass will create a new graph and register new handles.
> * Note that if we remove our original `hook_handle`, the script will leak until we remove, and then it will stop leaking but the hook will also stop running. It seems that our hook handle has global+leaky effects, while the HANDLES are specific to the batch graph.
> * Furthermore, if we remove `hook_handle` and re-register it again at global level (i.e. we call `hook_handle = model.register_full_backward_hook(hook)` again inside the training loop after deleting the hook handle), the leak will persist, against our intuition. I don't have a good explanation for this.
> * A colleague mentioned that the hook system got refactored in v1.7, and that backward hooks got a new "full backward hook" implementation.  Furthermore, they recall not having this leak. Looking into the sources, I recall that the "old" implementation makes use of global hooks and the new one (i.e. full backward hooks) makes use of `self` instead. Given the observations so far and the fact that the other issue identical to this one was from January 2022, I would argue that **the new implementation with full backward hooks may be behind the memory leak**. ButI would also argue that **the best fix is probably not so much going back to the old ways, but to keep proper track of the handles: the library should allow users to access all handles at all points, since as we have seen they can lead to very large, show-stopping leaks**.
> 
> In any case I hope this helps someone, and I welcome any comments on this. I am happy to make a PR if the core devs want and we agree on some specific directions (clearly this hotfix is not a permanent solution).
> 
> Cheers! Andres

Hi.
I actually tried your hotfix with global HANDLES in hook.py.
Sadly, my code still leaks some memories from the other side. (https://github.com/f-dangel/backpack/issues/258)
Are there any other chances of memory leaking from the register_hook?

**Comment by soulitzer** [comment]
Have you tried with the changes from https://github.com/pytorch/pytorch/pull/82788 (modifying hooks.py)?

**Comment by SJShin-AI** [comment]
Yes. 

First, i tried hotfix solution from [andres-fr](https://github.com/andres-fr) and it also leaks memory.
Second, i tried replacing the hooks.py and test_autograd.py, which are the main fixing parts from https://github.com/pytorch/pytorch/pull/82788 (modifying hooks.py).

It sadly couldn't stop the memory leakage.
I would really appreciate if someone could solve the memory leakage problem from the code below:


```python
from torch.nn import CrossEntropyLoss, Flatten, Linear, Sequential
import torch

from backpack import backpack, extend
from backpack.extensions import BatchGrad
from torchvision.datasets import MNIST
from torch.utils.data import TensorDataset, DataLoader

download_root = './MNIST_DATASET'
import torchvision.transforms as transforms
import functools



# Normalize data with mean=0.5, std=1.0
mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])
train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
# option 값 정의
batch_size = 512
train_loader = DataLoader(dataset=train_dataset,
                         batch_size=batch_size,
                         shuffle=True)
device = torch.device("cuda:0")

def compute_distance_grads_var(dict_grad_1,dict_grad_2):
    penalty = 0
    penalty += l2_between_lists(dict_grad_1, dict_grad_2)
    return penalty

def l2_between_lists(list_1, list_2):
    assert len(list_1) == len(list_2)
    return (
        torch.cat(tuple([t.view(-1) for t in list_1])) -
        torch.cat(tuple([t.view(-1) for t in list_2]))
    ).pow(2).sum()

def dist(x, y, method='mse'):
    """Distance objectives
    """
    if method == 'mse':
        dist_ = (x - y).pow(2).sum()
    elif method == 'l1':
        dist_ = (x - y).abs().sum()
    elif method == 'l1_mean':
        n_b = x.shape[0]
        dist_ = (x - y).abs().reshape(n_b, -1).mean(-1).sum()
    elif method == 'cos':
        x = x.reshape(x.shape[0], -1)
        y = y.reshape(y.shape[0], -1)
        dist_ = torch.sum(1 - torch.sum(x * y, dim=-1) /(torch.norm(x, dim=-1) * torch.norm(y, dim=-1) + 1e-6))
    elif method == 'l2_mean':
        dist_ = torch.norm(x-y, 2)
    return dist_

def get_grads(logits, y,model,bce_extended,real_sample):
    loss = bce_extended(logits, y).sum()
    with backpack(BatchGrad()):
        if real_sample:
            torch.autograd.grad(loss, list(model.parameters()))
        else:
            torch.autograd.grad(loss, list(model.parameters()),create_graph = True)

    grads_mean = []
    dict_grads_batch = []

    for name, weights in model.named_parameters():
        if real_sample:
            # grads_mean.append(weights.grad.detach().clone())
            dict_grads_batch.append(weights.grad_batch.detach().clone().view(weights.grad_batch.size(0), -1))
        else:
            # grads_mean.append(weights.grad)
            dict_grads_batch.append(weights.grad_batch.clone().view(weights.grad_batch.clone().size(0), -1))

    return grads_mean, dict_grads_batch


for i in range(100):
    model = Sequential(Flatten(), Linear(784, 128), Linear(128, 10))  # I added an additional layer here
    lossfunc = CrossEntropyLoss()
    model = extend(model)
    lossfunc = extend(lossfunc)
    model = model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    for batch_idx, (x, target) in enumerate(train_loader):
        x_syn = torch.rand(x.shape, requires_grad=True, device="cuda:0")
        y_syn = torch.ones_like(target)
        y_syn = y_syn.to(device)
        optimizer_alpha = torch.optim.Adam([x_syn], lr=1e-3)

        x = x.to(device)
        target = target.to(device)
        grad, grad_batch = get_grads(model(x), target, model, lossfunc,real_sample=True)
        optimizer.zero_grad()
        grad_syn, grad_batch_syn = get_grads(model(x_syn), y_syn, model, lossfunc,real_sample=False)
        loss =0
        loss += compute_distance_grads_var(grad_batch,grad_batch_syn)
        loss.backward()
        optimizer_alpha.step()
        optimizer_alpha.zero_grad()
```
