### ISSUE TITLE
how to build libtorch from source?

### ISSUE THREAD

**Issue by xoofee** [pytorch/pytorch#82524]
### 🐛 Describe the bug

 where is the source? I want to build libtorch-win-shared-with-deps-1.12.0%2Bcu116.zip

### Versions

as in the title

cc @malfet @seemethere @svekars @holly1238 @jbschlosser

**Comment by malfet** [comment]
Well, you are looking at it :)
There is a [build_libtorch.py](https://github.com/pytorch/pytorch/blob/master/tools/build_libtorch.py) script and here is a general documentation on how to build PyTorch https://github.com/pytorch/pytorch/#from-source

1.12.0 release were build against [v1.12.0](https://github.com/pytorch/pytorch/tree/v1.12.0) tag
