### ISSUE TITLE
False positive AVX, AVX2 and AVX512 detection with MSVC

### ISSUE THREAD

**Issue by JohT** [pytorch/pytorch#82553]
### 🐛 Describe the bug

[FindAVX.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindAVX.cmake) seems to set `CXX_AVX512_FOUND`, even if AVX-512 isn't available on the build machine. This also applies to AVX and AVX2.

MSVC doesn't seem to report compile errors, if AVX512 intrinsics are used with compile option `/arch:AVX`:
[Compiler Explorer AVX512 detection with MSVC](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIAbKQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BwA1BvmAMzByN5Y2ztueCwswQTEwQB0CCY72CYaAIJblxssTMEQ889v2wA7FZXlstgB9cEsACsXDMeA2TGOABENlCYXDwUoCODMAk8AAOCAaUgbElk0nkqmUmn/MH0hmMplM6kUtms6l05ncnn0jk09kCklc3millCiWCikisWyrb8qX8mVysUKtW00EquXqxUagFa1WSnUaP47EH6tFQ2HwjYRFGIh7m%2BmQ85MBQAa1ikg2mAAjl4xIQAJ5Qt3u%2B3o63g5AsBK4/EE0MeiBMUkRUnggCymfBbkzygAkqEACrg7AARVNTrBxEwBBWDDJjq5JkByP%2BHEWtE40N4fg4WlIqE4bms1g2CmWq0w2zMOx4pAImk7i3dIGhJO7HEkfeXQ84vAUIBJS4HndIcFgSDQsbo0XIlBv%2BPoMQAbsgEnHX1wAJzggwEJgEzgqoXp8HQgHEEeEARHuETBHUQacAuN5sIIADyDC0EhZ6kFgXxGOIuH4LWVSvkBe6YKolReIByG8JcbR7rQeARMQiEeFge5XGc9GLFQBjAAoABqeCYAA7uhCSMPRMiCCIYjsFIcnyEoah7roLQGEYKBjpY%2BisUekCLKgCQdEeHAAPR1MgSAvMJAAah5tJUHQuAw7ieE0/geb0RQlNkySpAIozNIkQUdH5/SlK07TVJMoV6BUVQCF09RRbMMUTN0iXjJMGUBVwiyTisax6FcmDrDwXY9ruuHDhwoHeiwCjvhs34/jcAFAQQGwQKOljWKSuCECQs7zqSHi3i%2B41Fbwp5aPMq7rpunA7qQ/aDg1h7Houy5LfonBmHVW0HntZ4HeRUFpCAkhAA%3D%3D)

CLang - on the other hand - does report compile errors:
[Compiler Explorer AVX512 detection with CLang](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIAbKQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BwA1BvmAMzByN5Y2ztueCwswQTEwQB0CCY72CYaAIJblxssTMEQ889v2wA7FZXlstgB9cEsACsXDMeA2TGOABENlCYXDwUoCODMAk8AAOCAaUgbElk0nkqmUmn/MH0hmMplM6kUtms6l05ncnn0jk09kCklc3millCiWCikisWyrb8qX8mVysUKtW00EquXqxUagFa1WSnUaP47EH6tFQ2HwjYRFGIh7m%2BmQ85MBQAa1ikg2mAAjl4xIQAJ5Qt3u%2B3o63g5AsBK4/EE0MeiBMUkRUnggCymfBbkzygAkqEACrg7AARVNTrBxEwBBWDDJjq5JkByP%2BHEWtE40N4fg4WlIqE4bms1g2CmWq0w2zMOx4pAImk7i3dIGhJO7HEkfeXQ84vAUIBJS4HndIcFgSDQsbo0XIlBv%2BPoMQOhmAXB2GhaNFoBGiR4QBEe4RMEdRBpwC43mwggAPIMLQEFnqQWBfEY4jIfgtZVAAbpgR7IZgqiVF4/6QbwlxtHutB4BExDgR4WB7lcZzkYsVAGMACgAGp4JgADusEJIw5EyIIIhiOwUhifIShqHuugtAYRgoGOlj6LRR6QIsqAJB0BEALRfDhqiHm0lQdC4DDuJ4TT%2BNZvRFCU2TJKkAijM0iSuR0jn9KUrTtNUkweXoFRVAIXT1L5sz%2BRM3QheMkzRc5XCLJOKxrHoVyYOsPBdj2u7IcOHCqASsQGV6GxvkYGyfjcGg3FwGwQKOljWKSuCECQs7zqSHi3i%2BPWpbwp5aPMq7rpunA7qQ/aDsVh7Houy7jfonBmIV80HstZ6rXhxApM4khAA)

Is that an intended behavior? Or is there a compile option for MSVC I missed, that will fail to compile?

I'd propose to use CHECK_C_SOURCE_RUNS instead of CHECK_C_SOURCE_COMPILES (+CXX +include) like it is done in this example: [find_avx.cmake](https://gist.github.com/UnaNancyOwen/263c243ae1e05a2f9d0e)

I'll provide a pull request for that, since this is easy to do and gives a tangible base for discussion.

### Versions

The script failed somehow. I hope the compiler explorer links above contain all necessary informations.

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
As https://github.com/pytorch/pytorch/pull/82554 is merged now, shouldn't this one be closed?
Though those are pure compile time checks - PyTorch runtime should not dispatch to AVX512-accelerated kernels unless CPU its running on supports it.

**Comment by JohT** [comment]
I'm fine with closing this issue.

Good point @malfet. 

- Runtime dispatching is not affected 
- Building with CLang is not affected, since it leads to an compile error as written above
- Building on a machine with AVX-512 won't make a difference, since all flags would be set anyway

With a [search for CXX_AVX2_FOUND](https://github.com/pytorch/pytorch/search?q=CXX_AVX2_FOUND) I found five locations, where the build depends on it:
- [caffe2/contrib/fakelowp/CMakeLists.txt](https://github.com/pytorch/pytorch/blob/7acb8b71e186869f9dd6acec2d6ce74ed4136e86/caffe2/contrib/fakelowp/CMakeLists.txt)
- [caffe2/perfkernels/CMakeLists.txt](https://github.com/pytorch/pytorch/blob/7acb8b71e186869f9dd6acec2d6ce74ed4136e86/caffe2/perfkernels/CMakeLists.txt)
- [caffe2/quantization/server/CMakeLists.txt](https://github.com/pytorch/pytorch/blob/7acb8b71e186869f9dd6acec2d6ce74ed4136e86/caffe2/quantization/server/CMakeLists.txt)
- [cmake/Codegen.cmake](https://github.com/pytorch/pytorch/blob/efe2c0422d25a237e7df1c457d1bf77430f7bc2a/cmake/Codegen.cmake)
- [cmake/MiscCheck.cmake](https://github.com/pytorch/pytorch/blob/9bb1371cc20a14907dbc47bc98e3ac5de866e34b/cmake/MiscCheck.cmake)

With a [search for CXX_AVX512_FOUND](https://github.com/pytorch/pytorch/search?q=CXX_AVX512_FOUND) I found one location, where the build depends on it:
- https://github.com/pytorch/pytorch/search?q=CXX_AVX512_FOUND

Without knowing it and without an actual error case, I can imagine that a different compile time behavior between CLang and  MSVC on build machines without AVX-512 (or even AVX2) could lead to some unexpected results. 

When I tried [FindAVX.cmake](https://github.com/pytorch/pytorch/blob/master/cmake/Modules/FindAVX.cmake) in my repository [convolution-benchmarks](https://github.com/JohT/convolution-benchmarks), my unit tests executable failed to run with MSVC on Windows on an older machine because of unknown instructions. I don't know if this could also happen to pytorch.

**Comment by JohT** [comment]
I'll close this issue for now. If there is anything left I can do, feel free to write me here.

**Comment by JohT** [comment]
If I understand you right @danfe, the check for AVX2 returns true even if your CPU doesn't support it. You found out that the piece of code that is run to check if the vector instruction set is available is optimized away by the compiler so that the check isn't done correctly.

In my opinion it would be great **if you could report that as a new issue**. It is not related to changing `CHECK_C[XX]_SOURCE_COMPILES` to `CHECK_C[XX]_SOURCE_RUNS`. It is awesome that you've already found a promising way to fix this 👍 so you could also create a pull request for that right away as a discussion base for the maintainers here.

**Comment by danfe** [comment]
> If I understand you right, the check for AVX2 returns true even if your CPU doesn't support it.

Not just for AVX2, for SIMD is general.  Depending on the CPU it could be AVX (e.g. first Intel Core generation) or AVX2 (e.g. AMD before Excavator).

> You found out that the piece of code that is run to check if the vector instruction set is available is optimized away by the compiler so that the check isn't done correctly.

Yes, that's right.

> It is not related to changing `CHECK_C[XX]_SOURCE_COMPILES` to `CHECK_C[XX]_SOURCE_RUNS`.

Tangentially related; using `CHECK_C[XX]_SOURCE_RUNS` itself is correct, but the code must be enforced so that compiler may not make it useless.

> In my opinion it would be great if you could report that as a new issue [and/or pull request].

Hm, okay.
