### ISSUE TITLE
MacOS MPS: src_total_size >= storage_byte_offset

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#82566]
### 🐛 Describe the bug

When converting a result from MPS backend to CPU, I get this error:

src_total_size >= storage_byte_offset INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":129, please report a bug to PyTorch. 

This is the code that fails:
```C++
        if (!o.device().is_cpu())
        {
            if (o.dtype() != torch::kFloat)
            {
                o = o.to(torch::kCPU, torch::kFloat);
            }
            else
            {
                o = o.to(torch::kCPU);
            }
        }
```
This, as a workaround, appears to not fail (note: the tensor is already a float):
```
if (!o.device().is_cpu())
{
    o = o.to(torch::kCPU);
}
```

It says to report it so I have put it here.

### Versions

Nightly pip for 1st August

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
Thanks @xsacha for reporting the issue. Can you please provide a small test-case to reproduce this INTERNAL_ASSERT ?

**Comment by xsacha** [comment]
The code above is what triggers the assert. Typically this code works for all other libtorch backends.
This 'o' is a tensor that is from the result of a model that used MPS. You could also just create a tensor and move it to MPS.

I can try to reproduce in python when I have time.
