### ISSUE TITLE
[MPS] `torch.expand` returns wrong results for boolean types

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#82663]
### 🐛 Describe the bug

```
 % python -c "import torch; dt=torch.bool;x=torch.tensor([[1], [0]], dtype=dt, device='mps'); y=torch.tensor([0, 1], dtype=dt, device='mps'); print(torch.equal(x.expand(2,2), y.expand(2,2)))"
True
```

but if one to change dtype to `torch.int8` or device to cpu it returns False, as expected.

I.e. it is expected for 
```
>>> torch.tensor([[1], [0]], dtype=torch.bool, device='mps').expand(2, 2)
tensor([[ True,  True],
        [False, False]])
```
and
 ```
>>> torch.tensor([0, 1], dtype=torch.bool, device='mps').expand(2, 2)
tensor([[False,  True],
        [False,  True]])

```

### Versions

1.12/nightly

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
@malfet , is this issue fixed ?

**Comment by malfet** [comment]
> @malfet , is this issue fixed ?

There is a workaround for 12.3 and the issue seems to have been fixed in MacOS Ventura preview, so yes, let's close it
