### ISSUE TITLE
Can't reproduce 20% performance gains on resnet50 using channel last memory format

### ISSUE THREAD

**Issue by Musisoul** [pytorch/pytorch#82699]
### 📚 The doc issue

In PyTorch document [performance-gains](https://pytorch.org/tutorials/intermediate/memory_format_tutorial.html#performance-gains), the Chapter "Performance Gains" says "We were able to archive over 22% perf gains with channels last comparing to contiguous format, both while utilizing ‘AMP (Automated Mixed Precision)’ training scripts". However, in our A100 machine, the average of velocity is approximately equal between using channels-last or not. We also found that the velocity of baseline is more stable than that of CL. Logs are uploaded in this repo: [channels-last-logs](https://github.com/Musisoul/channels-last-logs).
_____________________________________________________________________________________________________
**Versions**
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: A100-SXM-80GB
GPU 1: A100-SXM-80GB
GPU 2: A100-SXM-80GB
GPU 3: A100-SXM-80GB
GPU 4: A100-SXM-80GB
GPU 5: A100-SXM-80GB
GPU 6: A100-SXM-80GB
GPU 7: A100-SXM-80GB

Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] spring==0.7.2+cu112.torch1110.mvapich2.nartgpu.develop.805601a8
[pip3] torch==1.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] spring                    0.7.0+cu112.torch1110.mvapich2.pmi2.nartgpu          pypi_0    pypi
[conda] torch                     1.11.0+cu113             pypi_0    pypi
[conda] torchvision               0.12.0+cu113             pypi_0    pypi

cc @VitalyFedyunin @ngimel @jamesr66a

**Comment by xsacha** [comment]
Your speed looks all over the place at the start of your CL test.
If you look just at the 50 or so reports just before the first Test is run, the CL speed is more stable and achieves 1200-2000 (with an average of around 1500). The instability is probably due to a bottleneck elsewhere (disk/loader?).

The baseline in comparison holds on 1145, which is 30% slower.

**Comment by Jack47** [comment]
@Musisoul we can close this now because we found this is caused by I/O. After we use mocked Input, we can reproduce it now

**Comment by Musisoul** [comment]
> Your speed looks all over the place at the start of your CL test. If you look just at the 50 or so reports just before the first Test is run, the CL speed is more stable and achieves 1200-2000 (with an average of around 1500). The instability is probably due to a bottleneck elsewhere (disk/loader?). The baseline in comparison holds on 1145, which is 30% slower.
> 
> Looking at the Time outputs: CL: 0.095s - 0.166s Baseline: 0.167s

Using mocked input we got 27% gains, so it could be an I/O problem. Thanks.
