### ISSUE TITLE
[Quant] Tanh: QConfigMapping must specify fixed qparams observer for fixed qparams op

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#82708]
### 🐛 Describe the bug

When using FX to quantize an fp32 model which contains `tanh` op, error occurs in the preparation stage.
I am using the latest master branch.

Example code:
```python
import torch
import torch.quantization.quantize_fx as quantize_fx
from torch.quantization import get_default_qconfig
from torch.quantization.quantize_fx import prepare_fx, convert_fx

class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.tanh = torch.nn.Tanh()

    def forward(self, x):
        return self.tanh(x)


model_fp32 = M()
model_fp32.eval()
x = torch.randn((1,2,3,4));

qconfig = get_default_qconfig('fbgemm')
qconfig_dict = {"": qconfig}
prepared_model = prepare_fx(model_fp32, qconfig_dict, x) # error occurs here
quantized_model = convert_fx(prepared_model)
print(quantized_model)
out = quantized_model(x)
```
Error message:
```
/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/ao/quantization/fx/prepare.py:1466: UserWarning: Passing a QConfig dictionary to prepare is deprecated and will not be supported in a future version. Please pass in a QConfigMapping instead.
  warnings.warn(
/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/ao/quantization/observer.py:210: UserWarning: Please use quant_min and quant_max to specify the range for observers.                     reduce_range will be deprecated in a future release of PyTorch.
  warnings.warn(
Traceback (most recent call last):
  File "/home/weiwen/workspace/test/debug_tanh.py", line 21, in <module>
    prepared_model = prepare_fx(model_fp32, qconfig_dict, x)
  File "/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/ao/quantization/quantize_fx.py", line 348, in prepare_fx
    return _prepare_fx(
  File "/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/ao/quantization/quantize_fx.py", line 168, in _prepare_fx
    prepared = prepare(
  File "/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/ao/quantization/fx/prepare.py", line 1550, in prepare
    _validate_fixed_qparams_qconfigs(model, qconfig_map)
  File "/home/weiwen/.conda/envs/int8-dev/lib/python3.9/site-packages/torch/ao/quantization/fx/prepare.py", line 1361, in _validate_fixed_qparams_qconfigs
    raise ValueError("QConfigMapping must specify fixed qparams observer for fixed qparams op "
ValueError: QConfigMapping must specify fixed qparams observer for fixed qparams op '%tanh : [#users=1] = call_module[target=tanh](args = (%x,), kwargs = {})' type: '<class 'torch.nn.modules.activation.Tanh'>'. Please use torch.ao.quantization.get_default_qconfig_mapping or torch.ao.quantization.get_default_qat_qconfig_mapping instead.
```

### Versions

PyTorch version: 1.13.0a0+git7496937
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.13.0+cpu
[pip3] numpy==1.23.1
[pip3] pytorch-widedeep==0.3.7
[pip3] torch==1.13.0a0+git3139722
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl
[conda] intel-extension-for-pytorch 1.13.0+cpu               pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.1.0                 pypi_0    pypi
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl-static                2022.1.0                 pypi_0    pypi
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     1.13.0a0+git3139722          pypi_0    pypi
[conda] torchvision               0.13.0                   pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by andrewor14** [comment]
Hi @Xia-Weiwen, thanks for reporting the issue. The error should go away if you do this instead:
```
from torch.ao.quantization import get_default_qconfig_mapping
qconfig_mapping = get_default_qconfig_mapping()
prepared_model = prepare_fx(model_fp32, qconfig_dict, x) # error occurs here
```
This is the recommended way to specify qconfigs moving forward. We will also improve the error message you see here to point users in the right direction.

**Comment by Xia-Weiwen** [comment]
It worked. Thanks.

**Comment by Fsly** [comment]
I also encountered a similar problem. Sigmaid reported an error in dynamic quantification, and asked me to change it to static or QAT
