### ISSUE TITLE
Can't run test_ops test suite

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#82700]
### 🐛 Describe the bug

Can't run test_ops unit test

```python
root@5dda636bbab7:/opt/pytorch/pytorch# CI=1 python test/run_test.py -v -i test_ops -- -v -k cuda --save-xml
Ignoring disabled issues:  []
test/run_test.py:823: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if torch.version.cuda is not None and LooseVersion(torch.version.cuda) == "11.6":
Selected tests:
 test_ops
Running test_ops ... [2022-08-03 03:35:08.955954]
Executing ['/opt/conda/bin/python', '-bb', 'test_ops.py', '-v', '-k', 'cuda', '--save-xml', '-v'] ... [2022-08-03 03:35:08.955985]
Test results will be stored in test-reports/python-pytest/test_ops/test_ops.xml
ERROR: usage: test_ops.py [options] [file_or_dir] [file_or_dir] [...]
test_ops.py: error: unrecognized arguments: -n=4 --reruns=2
  inifile: /opt/pytorch/pytorch/pytest.ini
  rootdir: /opt/pytorch/pytorch

Traceback (most recent call last):
  File "test_ops.py", line 1835, in <module>
    run_tests()
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 736, in run_tests
    sanitize_pytest_xml(f'{pytest_report_path}')
  File "/opt/pytorch/pytorch/torch/testing/_internal/common_utils.py", line 612, in sanitize_pytest_xml
    tree = ET.parse(xml_file)
  File "/opt/conda/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/opt/conda/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'test-reports/python-pytest/test_ops/test_ops.xml'
Traceback (most recent call last):
  File "test/run_test.py", line 974, in <module>
    main()
  File "test/run_test.py", line 952, in main
    raise RuntimeError(err_message)
RuntimeError: test_ops failed!
```

### Versions

9647bec0ec41176adfd0cd5b80ab72c5bf6b2141

```
Python 3.8.13
pytest                    7.1.2                    pypi_0    pypi
```

Probably a follow-up of https://github.com/pytorch/pytorch/issues/82492

cc @mruberry @malfet @ptrblck

**Comment by albanD** [comment]
Shouldn't the `--save-xml` arg be before the `--`?

**Comment by albanD** [comment]
This is very weird. I'm not sure why the test command has all these extra arguments. Why do you pass in `CI=1`? Could that be the culprit?
Also why don't you just run the file directly via `python test/test_ops.py -v -k cuda` ?

**Comment by xwang233** [comment]
`CI=1` is needed to create xml test report.

We use `python test/run_test.py` to run the whole test suites, and `test_ops` suite fails.

The same command works before without any issue.

**Comment by albanD** [comment]
Ok. Not sure then tbh
I'm not sure who is supposed to maintain that file though.

**Comment by ngimel** [comment]
Likely caused by #79818, cc @clee2000. 
@xwang233 we'll accept a PR fixing it, but I don't think supporting non-standard CI setups is our priority.

**Comment by malfet** [comment]
Just curious, why not just run `python3 test_ops.py -v --save-xml .`?

**Comment by malfet** [comment]
@xwang233 can you please share a list of pip/conda package you have installed in the config you've attempted to run it?

**Comment by clee2000** [comment]
i think you need to install pytest-xdist and pytest-rerunfailures

**Comment by xwang233** [comment]
Hi @clee2000 , thank you for the suggestions. I installed the two pytest packages and the tests work now.

**Comment by albanD** [comment]
Should these be added to a requirements.txt file?
