### ISSUE TITLE
ConvTranspose1d doesn't work correctly on ARM

### ISSUE THREAD

**Issue by NicolasNierenbergPersyst** [pytorch/pytorch#82711]
### 🐛 Describe the bug

ConvTranspose1d produces a different result when run on the ARM GPU using 'mps' than on the CPU.  The following code illustrates.

import torch
from torch import nn
import copy

y = torch.ones(1, 1, 2)
deconv = nn.ConvTranspose1d(in_channels=1, out_channels=1, kernel_size=1, stride=2, bias=False)
deconv.weight.data = torch.ones(1,1,2)
gpudeconv = copy.deepcopy(deconv).to(device='mps')
x = deconv(y)
print (x)
ygpu = y.to(device='mps')
xgpu = gpudeconv(ygpu)
print(xgpu)

Result is:

tensor([[[1., 1., 1., 1.]]], grad_fn=<ConvolutionBackward0>)
tensor([[[1., 2., 1., 0.]]], device='mps:0', grad_fn=<ConvolutionBackward0>)

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220801
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220801
[conda] numpy                     1.22.3           py38h25ab29e_0  
[conda] numpy-base                1.22.3           py38h974a1f5_0  
[conda] pytorch                   1.13.0.dev20220801         py3.8_0    pytorch-nightly

cc @malfet @kulinseth @albanD

**Comment by datumbox** [comment]
moving the issue to Core as it seems to be related with M1/MPS cc @albanD

**Comment by kulinseth** [comment]
https://github.com/pytorch/pytorch/issues/82921, similar issue.

**Comment by NicolasNierenbergPersyst** [comment]
@kulinseth unless I'm missing something this also appears to be fixed in the latest nightly.

**Comment by kulinseth** [comment]
Yes.
