### ISSUE TITLE
Automating release process - Binary validation, Automatically generating get started page

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#82725]
### Problems details
Validation Takes to much time and not automated
Binary builds presence and installation instructions are not tested against release 
Get Started page generation is not automated

Lack of validation for artifacts based on the release matrix. We publish the following [release matrix] (TO DO  MOVE MATRIX TO OSS), and we build, test and publish the binaries to multiple repositories, such as Conda, Wheels, pypi, Iphone cocoapods, Android Maven. We publish for multiple OS versions (Linux, Windows, MacOs) and multiple package versions (CUDA, Python). However we have following gaps, for pytorch core and each of the domain libraries:
Smoke tests on clean environments are not implemented for all the binaries we produce (including Domain Libraries). To make sure binary can be loaded properly we should validate these binaries on the environment that does not have any dependencies preinstalled. 
Existing smoke tests run in the environment that has all dependencies preinstalled and hence we may miss an issue when the dependencies are missing
Binary presence and installation instructions validation for each binary. We already have a subset of the implemented when validating the get[ started page](https://pytorch.org/get-started/locally/). We also implemented a script to validate conda binaries presence. However we don’t validate all the binaries this way.

This situation leads to the following issues: 
Not releasing some binaries that are targeted for release
Releasing the binaries that could not be installed
Binaries fails to install due to regression of repository
Issues: [82428](https://github.com/pytorch/pytorch/issues/82428)
Releasing the binaries that could be installed but fails loading
Issues: [74087](https://github.com/pytorch/pytorch/issues/74087) [78490](https://github.com/pytorch/pytorch/issues/78490)

### Proposal

1. Ensure each release binary can be properly installed, and executed on target environment. 
Linux:

- [x] #83519
- [x] #84421
- [x] #82969
- [x] #82971
- [x] #82973

Windows:
- [x] #82977
- [x] #82978
- [x] #82980

Mac:
- [x] #83013
- [x] #83021

1.5 CUDA Older driver compatibility test:
- [x] #82913

2. Ensure we produce binary for every configuration declared in release matrix:
- [x] #82991

3. Generate a get started page automatically based on the release matrix.
- [x] #82996

4. Surface results on HUD and alerts for release failures
- [x] #84422

5. Extend the validation tests to cover more use cases:
- [x] #85085

6. Automate release only changes that needs to happen in order to build the release
- [x] #86491

7. Fix Official Docker build for release
- [x] #87489

8. Synchronize domain builds to be executed after core build have completed
- [ ] #87501

9. Consolidate Pytorch core and  Validation system framework matrixes and smoke tests
- [x] #88686

cc @seemethere @malfet

**Comment by malfet** [comment]
Err, don't we have it already in https://github.com/pytorch/pytorch.github.io/blob/site/.github/workflows/check-quickstartmodule.yml but just need to extend it to M1(which we didn't have at the time I wrote the workflow)

**Comment by atalman** [comment]
> Err, don't we have it already in https://github.com/pytorch/pytorch.github.io/blob/site/.github/workflows/check-quickstartmodule.yml but just need to extend it to M1(which we didn't have at the time I wrote the workflow)

Yes exactly we need to extend this idea to all the binary builds and run them regularly during the release to make sure all RCs could be installed and properly tested.

**Comment by vadimkantorov** [comment]
A bunch of related issues in https://github.com/pytorch/pytorch/issues/83519#issuecomment-1216844191

**Comment by atalman** [comment]
Thank you very much @vadimkantorov this is really handy will add these to our design doc :)

**Comment by atalman** [comment]
this is done
