### ISSUE TITLE
Primtorch nan_to_num signature does not align with aten

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#82763]
### 🐛 Describe the bug

Minimal Repro:
```
import torch
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.utils._python_dispatch import enable_torch_dispatch_mode

with enable_torch_dispatch_mode(FakeTensorMode()):
    a = torch.rand([4])
    torch.nan_to_num(a, nan=3.0),
```
> TypeError: too many positional arguments

### Versions

master

cc @ezyang @mruberry @ngimel @Chillee @zou3519 @albanD @samdow

**Comment by voznesenskym** [comment]
Thanks for opening the issue. For context, this is blocking pt upgrade in dynamo

**Comment by ngimel** [comment]
`nan_to_num` is not a valid kwarg (same error is thrown with eager), `nan` works:
```
In [4]: from torch.testing._internal.logging_tensor import LoggingTensorMode
   ...: from torch.utils._python_dispatch import enable_torch_dispatch_mode
   ...: 
   ...: with enable_torch_dispatch_mode(LoggingTensorMode()):
   ...:     torch.nan_to_num(torch.rand([4]), nan=3.0)
   ...: 
```

**Comment by eellison** [comment]
ooop nevermind, thanks @ngimel. closing until I find real source of issue.

**Comment by voznesenskym** [comment]
The kwarg in my repro is indeed `nan`. This repro may not suffice, as my repro invokes it through proxy target.

**Comment by eellison** [comment]
So, the issue is that  primtorch [nan_to_num](https://github.com/pytorch/pytorch/blob/master/torch/_refs/__init__.py#L643) is kwarg-only whereas aten [nan_to_num](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L2813) is not. Because the aten impl is not kwarg-only, `__torch_dispatch__` does not preserve the originally `kwarg`, so the arguments passed to FakeTensor are: just `(FakeTensor, 3.0)`. 

We could either:
a) mandate that primtorch follows the same signature as its corresponding aten ops.

or 

b) normalize to kwargs before every fake tensor invocation

**Comment by voznesenskym** [comment]
Do you have a preference?

**Comment by Chillee** [comment]
Another option is c. Register a slightly different primtorch signature for the aten operator.

**Comment by ngimel** [comment]
It looks like there are no design considerations for primtorch signature being different, so the easiest is to make it agree with aten and make non-kwonly.

**Comment by eellison** [comment]
okay i'm just going to fix the signature for now and we can always make changes in the future.

**Comment by ezyang** [comment]
@Chillee's solution is the right one. This is not the first time we have slightly different semantics between the aten ops and the python binding; another example is multi-out handling, where the aten ops slavishly follow the schema and give a separate kwarg for each out kwarg, whereas the native python bindings combine them together so that it's always `out=`. You have to do both in PrimTorch, one for the public Python UI, and another for the ATen UI.

One might argue that getting the public Python UI to work is a distraction. Well, it's always OK (for PT2) to do the ATen UI only, since you can always insert the primtorch decomp at the ATen level.

**Comment by ngimel** [comment]
In this case though primtorch needlessly deviates both from public python API (that has positional arguments) and aten (that follows python API and has positional arguments), so why wouldn't we fix primtorch to follow public python API, which is its stated goal, unless public API is clearly wrong and exists for legacy reasons?

**Comment by ezyang** [comment]
Oh yes, if PrimTorch is deviating from the public API then it's just wrong and should be fixed :)
