### ISSUE TITLE
DISABLED test_profiler_extra_cuda_copy_pattern_benchmark (__main__.TestExperimentalUtils)

### ISSUE THREAD

**Issue by jeffdaily** [pytorch/pytorch#82781]
Platforms: rocm

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_profiler_extra_cuda_copy_pattern_benchmark%2C%20TestExperimentalUtils)).

Caused by https://github.com/pytorch/pytorch/pull/82693.  Likely due to exact string pattern matching against a CUDA API.

**Comment by jeffdaily** [comment]
The offending commit that broke this test was reverted.  https://github.com/pytorch/pytorch/pull/82778.  I left a suggested code change that would fix ROCm CI if the PR is reworked.

**Comment by davidchencsl** [comment]
Updated and fix the issue of rocm test and merged :)
