### ISSUE TITLE
Does torch.Tensor work well with share memory list?

### ISSUE THREAD

**Issue by kunkunpang** [pytorch/pytorch#8281]
## Issue description

I was trying to share a list with large number of elements using multiprocess. However this is causing an error: 

'received 0 item with ancdata'. 

Why does this work using a numpy array but fails with pytorch array?

## Code example

We can use the code below to reproduce the problem.

```python
import multiprocessing as mp
import torch
import numpy as np

def reproduce_bug():
    a=[]              
    manager=mp.Manager()
    shm_list = manager.list([])
    for i in range(10000):    
        a.append(torch.rand(100))
        shm_list.append(torch.rand(100)) # where it cause the error
    print('pytorch!')
    

# Using numpy everything is fine
def bugfree():
    a=[]
    manager=mp.Manager()
    shm_list = manager.list([])
    for i in range(10000):
        a.append(np.random.rand(100))
        shm_list.append(np.random.rand(100))
    print('numpy!')

bugfree()
reproduce_bug()
```

## System Info
- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS:ubuntu
- PyTorch version: 0.4.0
- Python version: 3.6.4/3.6.3
- CUDA/cuDNN version:8.0/6.0
- GPU models and configuration: NA
- GCC version (if compiling from source): 
- CMake version: NA
- Versions of any other relevant libraries:

**Comment by apaszke** [comment]
Can you post the output of `ulimit -a` on your computer?

**Comment by kunkunpang** [comment]
This is the output of default `ulimit -a`:

```bash
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127966
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 127966
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I was specifically trying to increase the limit for the maximum number of files to open with using pytorch array (with the command: ulimit -n 20000). It works. But why numpy array does not require to change the limit?

**Comment by apaszke** [comment]
Because NumPy arrays don't get moved to shared memory by default (changes in one process probably won't be seen in another one). This is expected, so I'll close the issue.
