### ISSUE TITLE
Loaded network with load_state_dict has different shape but works anyway

### ISSUE THREAD

**Issue by mario98** [pytorch/pytorch#8282]
After it was verified on [discuss.pytorch](https://discuss.pytorch.org/t/loaded-network-has-different-shape-but-works-anyway/19398) that this is indeed unwanted behaviour, I am forwarding this to you:

## Issue description

I trained a model with among others had the following layer:
`final_layer.append(nn.Conv2d(64, 1, kernel_size=1))`
and then saved it to a file with state_dict and torch.save.

Then, when I wanted to load that model using load_state_dict, by accident the same layer was setup as follows:
`final_layer.append(nn.Conv2d(64, 32, kernel_size=1))`

Nevertheless, the model was loaded without error. It seemed that the weights were just duplicated 32 times, but I have not verified. So the question is how this is consistent with API documentation. I have not found a statement that says load_state_dict would somehow fix shape inconsistencies automatically. It seems you have a documentation vs reality mismatch here. (Now you need to decide which one to fix)

## Code example

```
path = './test_model.pth'

model = nn.Conv2d(64, 1, 3, 1, 1)
torch.save(model.state_dict(), path)

model = nn.Conv2d(64, 32, 3, 1, 1)
model.load_state_dict(torch.load(path))

for w in model.weight[:, :, 0, 0]:
    print(w)
```

Provided by discuss .pytorch user ptrblck

## System Info
pytorch 0.4 release

**Comment by SsnL** [comment]
we should check for exact shape match at https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L636

**Comment by ppwwyyxx** [comment]
We'd like to have an option (e.g., when using `load_state_dict(strict=False)`) to disable this check (and return the messages like it's already doing).
Loading a state-dict with a few mismatched values is common in tasks like transfer learning.

Right now, `strict=False` does the following: it allows loading a dict with missing parameters. It allows loading a dict with more parameters than needed. Why not also allow loading a dict with parameters of mismatched shape?

**Comment by SsnL** [comment]
@ppwwyyxx Could you open a new issue for this? I agree that `strict=False` should do what you described. But generally, for state dict manipulation, I would suggest changing the state dict that is being loaded, rather than using `strict=False` because the later almost always disables more checks than you would like to.
