### ISSUE TITLE
Tensor subclasses should get __hash__ automatically defined

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#82832]
Calling `nn.Module.named_parameters()` means that `memo` is a `set` of `nn.Parameter`s. This goes through `Tensor.__eq__()`, which checks tensor value equality. Apparently, it is not good that we are using a `set` of `Tensor`s.

https://github.com/pytorch/pytorch/blob/8b4fee59120b70589b043daadfe7d263d116b373/torch/nn/modules/module.py#L1660-L1671

Side note: Because the implementation only adds `v` to `memo` and not `(name, v)`, shared parameters only appear once in `nn.Module.named_parameters()`. (Shared parameters means like `linear2.weight = linear1.weight`.)

cc @ezyang @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by albanD** [comment]
Why is is not good?

Also, removing duplicate Tensor is done on purpose!

**Comment by awgu** [comment]
cc: @ezyang

**Comment by ezyang** [comment]
@albanD Isn't this not supposed to work? Tensor.__eq__ is tensor equality returning a Tensor, so I don't expect hash-based containers to work. Same deal with Tensor as key in dictionary.

**Comment by albanD** [comment]
We are defining `__hash__` on Tensor. So these containers work just fine.

**Comment by ezyang** [comment]
No but this doesn't make sense. If there is a hash collision the container has to test equality to determine which value to return...

**Comment by albanD** [comment]
hash can't colide for regular Tensors as their hash is `id(self)` :D So this is unique as long as the Tensor is alive.

**Comment by awgu** [comment]
@wanchaol also just informed me that `ShardedTensor` overrides `__hash__()` to return `id(self)`. Doing so for the `IndirectParameter` resolves the error I was seeing before.

**Comment by albanD** [comment]
Yes, `__hash__` has a weird semantic wrt sucblassing: https://docs.python.org/3/reference/datamodel.html#object.__hash__

**Comment by ezyang** [comment]
Yes, metaclass here seems like the right thing to do.
