### ISSUE TITLE
Torch.hub changes pyplot backend

### ISSUE THREAD

**Issue by jcowles** [pytorch/pytorch#82857]
### 🐛 Describe the bug

```
import matplotlib.pyplot as plt
import torch

print(plt.get_backend())

# prints TkAgg

model = torch.hub.load('ultralytics/yolov5', 'yolov5l', pretrained=True)
print(plt.get_backend())

# prints agg
```

Now pyplot is left in a state where calling Show will result in the following:

```
 UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```

And will not display plots, which is a mystifying result of calling `torch.hub.load`.

### Versions

Collecting environment information...
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Super with Max-Q Design
Nvidia driver version: 512.92
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-fid==0.2.1
[pip3] torch==1.10.2+cu113
[pip3] torchaudio==0.10.2+cu113
[pip3] torchvision==0.11.3+cu113
[conda] Could not collect

cc @nairbv @NicolasHug @vmoens @jdsgomes

**Comment by vmoens** [comment]
Thanks for reporting this @jcowles 

It seems this is a byproduct of yolov5, not torch hub itself.

https://github.com/ultralytics/yolov5/blob/916bdb1d61f23de92833bd491df54cda5c3ef0cc/utils/plots.py#L28

I guess you'll need to reset the backend after the import of that makes sense?

**Comment by jcowles** [comment]
Yeah, for any future people reading this bug, this is the fix:

```
def get_yolo():
    b = plt.get_backend()
    model = torch.hub.load('ultralytics/yolov5', 'yolov5l', pretrained=True)
    matplotlib.use(b)
    return model
```

It would be nice if Torch Hub could somehow fix this in the published model, to avoid confusion.

**Comment by NicolasHug** [comment]
@jcowles thanks for the report.

I'd suggest reaching out the authors in the model's repo: https://github.com/ultralytics/yolov5. There is nothing we can do from torchhub's side, as torchhub has no direct control over the models that it exposes. As @vmoens mentioned, the issue comes from the model's code, not from torchhub.

**Comment by jcowles** [comment]
Yes, I understood.

I wont be pursuing this bug further, because it's not negatively affecting me, but it will continue to be a negative experience for Torch.Hub users. I will leave it to the Torch.Hub team to consider fixing or not fixing.
