### ISSUE TITLE
[distributed.nn] functional collective `scatter` bug

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#82851]
### 🐛 Describe the bug

our functional `distributed.nn.functional.scatter` have two bugs:
1. it does not check/call contiguous()
2. it use group rank instead of local rank when calling `c10d.scatter`

### Versions

master

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by rohan-varma** [comment]
Do we support `distributed.nn.functional.*` APIs officially?

**Comment by wanchaol** [comment]
> Do we support `distributed.nn.functional.*` APIs officially?

I don't know tbh, I think the nn.functional.* apis are being used by other external folks, but I think we never officially putting them in the doc. The separation of two set of APIs is troublesome and there might be couple of issues like this one on the bugs of nn.functional, because we never manage to maintain it well, sigh..
