### ISSUE TITLE
Change default `rcond` parameter in `torch.linalg.lstsq` to match `numpy.linalg.lstsq`

### ISSUE THREAD

**Issue by raj-magesh** [pytorch/pytorch#82868]
### 🚀 The feature, motivation and pitch

According to [this thread](https://stackoverflow.com/a/44678023), for most practical purposes, the `rcond` parameter for `lstsq` should be set to `EPS * max(M, N)` and not just `EPS`, where `EPS` is the machine precision of `A`'s `dtype` and `A` has shape `(*, M, N)`.

This is now the default behavior in [`numpy.linalg.lstsq`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html). 

It might be a good idea to follow `numpy`'s lead and change the default `rcond` for `torch.linalg.lstsq` too.

The StackOverflow thread mentions that `scipy` sets the default `rcond` optimally, but from what I can see [in their code](https://github.com/scipy/scipy/blob/v1.9.0/scipy/linalg/_basic.py#L1179), that doesn't currently seem to be the case. Not sure why.

If this is acceptable, I could send a PR.

cc @mruberry @rgommers @jianyuh @nikitaved @pearu @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by IvanYashchuk** [comment]
Thank you for filing this issue. PyTorch already has the same default for rcond argument as NumPy.
From the documentation of `torch.linalg.lstsq`:
> If rcond= None, rcond is set to the machine precision of the dtype of A times max(m, n). Default: None.

**Comment by raj-magesh** [comment]
I didn't notice it earlier but the docs are inconsistent in the text description and the arguments, which is why I was confused about the default. I've raised a PR to fix the inconsistency.
