### ISSUE TITLE
[ONNX] Converted to onnx successful, but can not load

### ISSUE THREAD

**Issue by phamkhactu** [pytorch/pytorch#82870]
### 🐛 Describe the bug

I converted model to onnx successful, but can not load with onnx-runtime.
```python
import torch
checkpoint = "weights/bb5792a6.pt"
model = load_from_checkpoint(checkpoint, **kwargs).eval()



model_path = f"weights/model.onnx"

dummy_input = torch.randn(1, 3, 32, 128)
torch.onnx.export(model, dummy_input, model_path, verbose=False, input_names=['input'], output_names=['output'], opset_version=14)

```

my err:

```
self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from weights/model.onnx failed:This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (5287) of operator (CumSum) in node (CumSum_2919) is invalid.
```

I had issused in [onnx-repo](https://github.com/onnx/onnx/issues/4407), author reponse that: "I think it should be an issue in the exporter (torch.onnx.export), because CumSum does not allow bool as an input but it gets input from previous Equal op, which only outputs bool. The exporter should handle this by something like using a Cast op in the middle" 
Many thank for your reponse.

### Versions

Torch version: 1.10.2

**Comment by AllenTiTaiWang** [comment]
Hi @phamkhactu ,

Could you provide a repro code for this issue? We will have to look into torch/ONNX IR to know what exactly happened during the exporting process.

**Comment by phamkhactu** [comment]
> Hi @phamkhactu ,
> 
> Could you provide a repro code for this issue? We will have to look into torch/ONNX IR to know what exactly happened during the exporting process.
> 
> Also, could you try nightly PyTorch?

@AllenTiTaiWang here [repo](https://github.com/baudm/parseq/issues/9)

The code convert to onnx(author provided)
```
import torch

parseq = torch.hub.load('baudm/parseq', 'parseq', pretrained=True).eval()
dummy_input = torch.rand(1, 3, *parseq.hparams.img_size)  # (1, 3, 32, 128) by default

# To ONNX
parseq.to_onnx('parseq.onnx', dummy_input, opset_version=14)  # opset v14 or newer is required

# To TorchScript
parseq.to_torchscript('parseq-ts.pt')
```

**Comment by AllenTiTaiWang** [comment]
I was expecting an easy reproducible code that I can target the problem quickly, and get to know what's going on with this model. Could you maybe extract the CumSum part of code, and use it as a small model that can reproduce this error?

Also, if their repo claims the converter works, could you maybe also raise an issue in their repo? They should be able to target on the whole model.

**Comment by phamkhactu** [comment]
> 
Thank you @AllenTiTaiWang

**Comment by ashishpapanai** [comment]
Hi @phamkhactu ,
I am getting a similar issue on this, did you find any work around to this? or maybe fixed it?

**Comment by thiagocrepaldi** [comment]
This issue has been closed as a runnable repro was not provided.

Feel free to reopen with a runnnable repro to help us understand the issue and validate it
