### ISSUE TITLE
Unable to freeze tensor of type Int64/Float64 into constant layer

### ISSUE THREAD

**Issue by mjack3** [pytorch/pytorch#82875]
### 🐛 Describe the bug

Hello,

I am trying to convert a small invertible neural network

```
import torch.nn as nn
import FrEIA.framework as Ff
import FrEIA.modules as Fm

def subnet_conv(c_in, c_out):
    return nn.Sequential(nn.Conv2d(c_in, 256,   3, padding=1), nn.ReLU(), nn.Conv2d(256,  c_out, 3, padding=1))

def subnet_conv_1x1(c_in, c_out):
    return nn.Sequential(nn.Conv2d(c_in, 256,   1), nn.ReLU(), nn.Conv2d(256,  c_out, 1))

decoder = Ff.SequenceINN(256, 54, 54) # Init with dimension w/o batch size
for k in range(2):
    decoder.append(Fm.GLOWCouplingBlock, subnet_constructor=subnet_conv)
    decoder.append(Fm.GLOWCouplingBlock, subnet_constructor=subnet_conv_1x1)
```
In this way

```
traced_decoder = torch.jit.trace(decoder, torch.empty(1, 256, 54, 54))
trt_model = torch_tensorrt.compile(traced_decoder, inputs = [torch_tensorrt.Input((1, 256, 54, 54), dtype=torch.float32)],
                                   enabled_precisions = torch.float32)
```

Then, I am getting next

`RuntimeError: [Error thrown at core/conversion/converters/converter_util.cpp:167] Unable to freeze tensor of type Int64/Float64 into constant layer, try to compile model with truncate_long_and_double enabled`

Lastly, adding the argument truncate_long_and_double the problem get solved with some warnings 

```
WARNING: [Torch-TensorRT] - Truncating weight (constant in the graph) from Float64 to Float32
WARNING: [Torch-TensorRT] - Truncating weight (constant in the graph) from Float64 to Float32
WARNING: [Torch-TensorRT] - Sum converter disregards dtype
WARNING: [Torch-TensorRT] - Truncating weight (constant in the graph) from Float64 to Float32
WARNING: [Torch-TensorRT] - Truncating weight (constant in the graph) from Float64 to Float32
WARNING: [Torch-TensorRT] - Sum converter disregards dtype
WARNING: [Torch-TensorRT TorchScript Conversion Context] - The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
WARNING: [Torch-TensorRT TorchScript Conversion Context] - The getMaxBatchSize() function should not be used with an engine built from a network created with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag. This function will always return 1.
```
1- How can I figure out what problem make me use `truncate_long_and_double`?
2- Do I need to worry about this warnings after using `truncate_long_and_double`?

Thank you all

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Libc version: glibc-2.35

Python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.1
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.1
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.11.0+cu113
[pip3] torch-tensorrt==1.1.0
[pip3] torchvision==0.12.0+cu113
[conda] No relevant packages

**Comment by jbschlosser** [comment]
Hey @mjack3! FYI you will probably have more luck getting assistance by posting on the [PyTorch forums](https://discuss.pytorch.org/). The issues here are reserved for problems within PyTorch itself. Please feel free to reopen if a bug is encountered in PyTorch - thanks!

**Comment by mjack3** [comment]
Oh sorry! I thought I had written in Pytorch/TensorRT
