### ISSUE TITLE
torch.log test with negative numbers…

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#82885]
### 📚 The doc issue

From the docs:

```
>>> a = torch.randn(5)
>>> a
tensor([-0.7168, -0.5471, -0.8933, -1.4428, -0.1190])
>>> torch.log(a)
tensor([ nan,  nan,  nan,  nan,  nan])
```

### Suggest a potential alternative/fix

```
>>> a = torch.rand(5)
```

Also, I tried searching for "Returns a new tensor with the natural logarithm of the elements" but I couldn't locate the file on GitHub. How can one help fix these things?

cc @svekars @holly1238

**Comment by albanD** [comment]
This is already fixed in master! https://pytorch.org/docs/master/generated/torch.log.html?highlight=log#torch.log 
Thanks for the report!

**Comment by Atcold** [comment]
How can I find the fixing commit?

**Comment by albanD** [comment]
https://github.com/pytorch/pytorch/pull/78776 did it based on git blame of the doc itself: https://github.com/pytorch/pytorch/blame/6bdf89b0c71a827be2a0969afa33f151e87a32f3/torch/_torch_docs.py#L6027
