### ISSUE TITLE
Periodic IOS Workflows Are Timing Out/Flaky

### ISSUE THREAD

**Issue by zengk95** [pytorch/pytorch#82890]
### 🐛 Describe the bug

Over the past week, Periodic IOS Jobs have been timing out randomly after 4 hours on various builds and it's gotten worse over the past few days. It usually hangs at around 

```
CodeSign /Users/runner/work/pytorch/pytorch/ios/TestApp/build/Release-iphoneos/TestApp.app (in target 'TestApp' from project 'TestApp')
    cd /Users/runner/work/pytorch/pytorch/ios/TestApp
    export CODESIGN_ALLOCATE\=/Applications/Xcode_13.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
    Signing Identity:     "Apple Development: Tao Xu (Q7PV3L5FKY)"
    Provisioning Profile: "PyTorch_CI_2022"
                          (4aacbe80-cff0-4415-9ae8-c84476678cd5)
```

See HUD: https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=periodic%20%2F%20ios

![Uploading image.png…]()

### Versions

master

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by zengk95** [comment]
cc @linbinyu

**Comment by zengk95** [comment]
cc @xta0

**Comment by janeyx99** [comment]
If it is too flaky (over 5% of jobs), let's disable for the time being

**Comment by malfet** [comment]
By the way, screenshot link seems to be broken, is there a link with particular examples

**Comment by janeyx99** [comment]
Examples:
https://github.com/pytorch/pytorch/runs/7711173779?check_suite_focus=true
https://github.com/pytorch/pytorch/runs/7711173601?check_suite_focus=true

**Comment by jmdetloff** [comment]
Ah, fastlane times out the keychain after 1 hour https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/setup_ci.rb#L111

All our failed builds took longer than an hour, all our successful ones took less. This seems to be the culprit. We need to pass a timeout param into setup_ci in our fastfile to prevent this. I'll spin up a PR
