### ISSUE TITLE
PyTorch CI/binary smoke test should validate minor version compatibility feature

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#82913]
### 🐛 Describe the bug

Namely, updating the toolkit to CUDA-11.7 should not require one to update driver to 515.65, 510.47 (from CUDA-11.6) should be sufficient

Inspired by discussion in https://github.com/pytorch/pytorch/pull/81688

### Versions

CUDA-11.x

cc @ezyang @gchanan @zou3519 @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by jbschlosser** [comment]
From triage meeting: need to update runbook & change some code because we use the NVIDIA docker images

cc @ptrblck

**Comment by atalman** [comment]
@malfet @ezyang 
Is following driver acceptable to validate minor version compatibility, running on Tesla M60 on Linux :
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla M60           On   | 00000001:00:00.0 Off |                  Off |

**Comment by atalman** [comment]
closing this since implemented tests in 
https://github.com/pytorch/builder/blob/main/.github/workflows/validate-linux-binaries.yml
and 
https://github.com/pytorch/builder/blob/main/.github/workflows/validate-windows-binaries.yml
