### ISSUE TITLE
Conv1d with stride other than 1 fails on mps

### ISSUE THREAD

**Issue by NicolasNierenbergPersyst** [pytorch/pytorch#82921]
### 🐛 Describe the bug

Conv1d produces a different result on Apple M1 (mps) than on the cpu when the stride is not 1.

import torch
from torch import nn
import copy

y = torch.randn(1, 57,  40)
conv = nn.Conv1d(57, 20, stride=2, kernel_size=3, bias=False)
gpuconv = copy.deepcopy(conv).to(device='mps')
x = conv(y)
print (x)
ygpu = y.to(device='mps')
xgpu = gpuconv(ygpu)
print(xgpu)
print(torch.isclose(x, xgpu.to(device='cpu')))

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220801
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220801
[conda] numpy                     1.22.3           py38h25ab29e_0  
[conda] numpy-base                1.22.3           py38h974a1f5_0  
[conda] pytorch                   1.13.0.dev20220801         py3.8_0    pytorch-nightly

cc @ezyang @gchanan @zou3519 @kulinseth @albanD

**Comment by kulinseth** [comment]
@DenisVieriu97 , can you take a look ?

**Comment by kulinseth** [comment]
Can you please check, if this is fixed in latest nightly.

**Comment by NicolasNierenbergPersyst** [comment]
@kulinseth yes, fixed for me.
