### ISSUE TITLE
torch.add triggers INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#82956]
### 🐛 Describe the bug

import torch
arg_1 = torch.rand([0, 5, 24, 4], dtype=torch.complex32)
arg_2 = torch.randint(-32,2,[4], dtype=torch.int8)
res = torch.add(arg_1,arg_2,)

#RuntimeError: common_dtype_ != ScalarType::Undefined INTERNAL ASSERT FAILED at "..\\aten\\src\\ATen\\TensorIterator.cpp":239, please report a bug to PyTorch.

### Versions

pytorch: 1.8.1

**Comment by ngimel** [comment]
Can't repro on more recent versions
