### ISSUE TITLE
[FSDP] TypeError: load_state_dict() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by pacman100** [pytorch/pytorch#82963]
### 🐛 Describe the bug

When loading trained FSDP model, the below error is observed. The expected behaviour should be to have `load_state_dict` consistent with the PyTorch API. A similar issue is raised here https://github.com/huggingface/transformers/issues/18511 when using FSDP integration of transformers.
 
```bash
....

load_result = model.load_state_dict(state_dict, strict=False)
TypeError: load_state_dict() got an unexpected keyword argument 'strict'
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: NVIDIA TITAN RTX
GPU 1: NVIDIA TITAN RTX

Nvidia driver version: 510.73.08
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by chauhang** [comment]
cc: @suo @rohan-varma

**Comment by rohan-varma** [comment]
This seems like a bug in FSDP where we don't propagate kwargs: https://github.com/pytorch/pytorch/blob/a58876ace78df1cfeb136cad592487f34d7e02f1/torch/distributed/fsdp/fully_sharded_data_parallel.py#L2316, so we should be able to have a quick fix from our side.

Although, one workaround could be to pass in strict as an arg instead of kwarg:

```
load_result = model.load_state_dict(state_dict, False)
```

which is not great for readability, but would be good if you can try that and see if it works around the issue.

**Comment by pacman100** [comment]
Hello, Thank you for the reply and suggestion for bypassing the issue, as per https://github.com/huggingface/transformers/issues/18511#issuecomment-1211512941, the above workaround works. As a long-term thing, it would be great to have the FSDP function match the API of PyTorch for better interoperability.

**Comment by rohan-varma** [comment]
Fixed https://github.com/pytorch/pytorch/pull/83309

**Comment by sjkoelle** [comment]
I'm still seeing this error in torch 2
