### ISSUE TITLE
MPS build raises too many warnings

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#82966]
There were a lot of efforts invested in making PyTorch build almost warning free to reduce noise during compilation and ease up debugging when issues happens.
But MPS build is producing thousands of these which makes the CI job very hard to work with (as it is so long that you have to download the logs to be able to see the end of them).

We need to find a way to either silence these warnings or make sure they are not raised in the code anymore.

cc @ezyang @gchanan @zou3519 @malfet @seemethere @albanD @kulinseth

**Comment by malfet** [comment]
Grabbing for myself

**Comment by dagitses** [comment]
Alban/Nikita: are the warnings dominated by a few specific types?

**Comment by kulinseth** [comment]
> Alban/Nikita: are the warnings dominated by a few specific types?

Most of the warnings are due to Availability macro. We need to wrap the datatypes like `MPSGraph`, `MPSGraphTensor`, `MPSGraphTensorData` everywhere in the code with availability macro . One of the ways is to `typedef` it so that it can be put in one-place. @malfet , how are you planning to solve this ?

**Comment by malfet** [comment]
> Most of the warnings are due to Availability macro. We need to wrap the datatypes like `MPSGraph`, `MPSGraphTensor`, `MPSGraphTensorData` everywhere in the code with availability macro . One of the ways is to `typedef` it so that it can be put in one-place. @malfet , how are you planning to solve this ?

Just pass `target-macos-version`  to 12.3 for .mm files, but also enforce unused variables warning when compiling with `-Werror`

**Comment by malfet** [comment]
@kulinseth can you please explain what 's the following code supposed to be doing:
https://github.com/pytorch/pytorch/blob/943553965eafac2a9490d8066e072ce2fd156c57/aten/src/ATen/mps/MPSGuardImpl.mm#L13-L14

As far as I can see, `mpsEvent_t` is just a typedef for `MPSEvent*` and as such I don't think typecasting is actually doing anything, is it?
https://github.com/pytorch/pytorch/blob/943553965eafac2a9490d8066e072ce2fd156c57/aten/src/ATen/mps/MPSStream.h#L145

**Comment by kulinseth** [comment]
> @kulinseth can you please explain what 's the following code supposed to be doing:
> 
> https://github.com/pytorch/pytorch/blob/943553965eafac2a9490d8066e072ce2fd156c57/aten/src/ATen/mps/MPSGuardImpl.mm#L13-L14
> 
> As far as I can see, `mpsEvent_t` is just a typedef for `MPSEvent*` and as such I don't think typecasting is actually doing anything, is it?
> 
> https://github.com/pytorch/pytorch/blob/943553965eafac2a9490d8066e072ce2fd156c57/aten/src/ATen/mps/MPSStream.h#L145

Correct, its just typedef. This can be cleaned up.

**Comment by malfet** [comment]
> Correct, its just typedef. This can be cleaned up.
Cleaned up in https://github.com/pytorch/pytorch/pull/83048 (among other unused variable/undefined selector warnings)
