### ISSUE TITLE
Create basic ubuntu images without any dependencies

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#82969]
Option 1:
Add following dockers build: pytorch-linux-bionic-py3.9 
to:
https://github.com/pytorch/pytorch/blob/master/.github/workflows/docker-builds.yml
That would build docker image specifically for the binary validation. 
Refer to https://github.com/pytorch/pytorch/blob/master/.circleci/docker/ubuntu/Dockerfile which already parametrized

Here is an example of minimal configuration image
https://github.com/pytorch/pytorch/blob/master/.circleci/docker/build.sh#L92

Scripts located:
https://github.com/pytorch/pytorch/tree/master/.circleci/docker

Option 2
Miniconda docker image - https://hub.docker.com/r/continuumio/miniconda3 
This will make sure we are using completely different environment to setup and validate the install

Option 3:
Use Github Custom Runners 
GPU: ubuntu-20.04-m60
CPU: ubuntu-20.04

Implemented Option 3

Testing:

Test the resulting image with following installation instructions:
https://pytorch.org/get-started/locally/
Make sure we can run both pip and conda installs successfully

cc @malfet @seemethere

**Comment by malfet** [comment]
We should just use basic ubuntu image, for example https://hub.docker.com/layers/ubuntu/library/ubuntu/bionic/images/sha256-e4771b7160543c6e43968b4e9795be9ddcad9d573edd7cd7aebd3ce61326fc7a?context=explore

**Comment by atalman** [comment]
We where able to use  Github Custom Runners
GPU: ubuntu-20.04-m60
CPU: ubuntu-20.04
This makes it even simpler.
