### ISSUE TITLE
ValueError: Sequence must have length 1, got 3.

### ISSUE THREAD

**Issue by ctwangtz** [pytorch/pytorch#82964]
### 🐛 Describe the bug

class SegDataset(Dataset):
    def __init__(self, root_dir, train, size):
        self.root_dir = root_dir
        self.train = train
        self.size = size

    def __len__(self):
        list = os.listdir(self.root_dir + '/ss/')
        len_data = len(list)
        print(len_data)
        return len_data

    def __getitem__(self, index):
        # conect path
        pathImage = glob.glob(self.root_dir + '/ss/*')[index]
        pathLabel = glob.glob(self.root_dir + '/mask/*')[index]
        # read nii.gz
        Imgloader = LoadImage(image_only=True)
        Labloader = LoadImage(image_only=True, dtype=np.uint8)
        img = Imgloader(pathImage)
        lab = Labloader(pathLabel)
        
        Totnsor = ToTensor(device="cuda:0")  # numpy TO tensor √
        img = Totnsor(img)
        lab = Totnsor(lab)
        img = img.unsqueeze(dim=0)  # add channel √
        lab = lab.unsqueeze(dim=0)
        # resize √
        Resizer = Resize(spatial_size=(self.size, self.size))
        img = Resizer(img)
        lab = Resizer(lab)
        print(pathImage,pathLabel, '//',index,img.shape,lab.shape) ###################################
        # normalization & rescale
        Normaler = NormalizeIntensity(subtrahend=0, divisor=.5, nonzero=True)
        img = Normaler(img)
        Rescler = ScaleIntensity(maxv=1, minv=0)
        img = Rescler(img)

        if self.train is True:
            # rotate flip
            if random.choice([True, False]):
                Rflip = Flip(spatial_axis=0)
                img = Rflip(img)
                lab = Rflip(lab)
            if random.choice([True, False]):
                RN = np.random.randint(-45, 45, 1).item()/100
                Rrotate = Rotate(angle=(0, 0, RN))
                img = Rrotate(img)
                lab = Rrotate(lab)
        return img, lab

------------------------------------------------------------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
f:\jupyterlab\Project pipeline\mulStage.ipynb Cell 5 in <cell line: 2>()
      [3](vscode-notebook-cell:/f%3A/jupyterlab/Project%20pipeline/mulStage.ipynb#X14sZmlsZQ%3D%3D?line=2) loss, step = 0, 0
      [4](vscode-notebook-cell:/f%3A/jupyterlab/Project%20pipeline/mulStage.ipynb#X14sZmlsZQ%3D%3D?line=3) model.train()
----> [6](vscode-notebook-cell:/f%3A/jupyterlab/Project%20pipeline/mulStage.ipynb#X14sZmlsZQ%3D%3D?line=5) for img, lab in loader_train:
      [7](vscode-notebook-cell:/f%3A/jupyterlab/Project%20pipeline/mulStage.ipynb#X14sZmlsZQ%3D%3D?line=6)     print(img.shape)

File f:\Python310\lib\site-packages\torch\utils\data\dataloader.py:530, in _BaseDataLoaderIter.__next__(self)
    528 if self._sampler_iter is None:
    529     self._reset()
--> 530 data = self._next_data()
    531 self._num_yielded += 1
    532 if self._dataset_kind == _DatasetKind.Iterable and \
    533         self._IterableDataset_len_called is not None and \
    534         self._num_yielded > self._IterableDataset_len_called:

File f:\Python310\lib\site-packages\torch\utils\data\dataloader.py:570, in _SingleProcessDataLoaderIter._next_data(self)
    568 def _next_data(self):
    569     index = self._next_index()  # may raise StopIteration
--> 570     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    571     if self._pin_memory:
    572         data = _utils.pin_memory.pin_memory(data)

File f:\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py:49, in _MapDatasetFetcher.fetch(self, possibly_batched_index)
...
    151 if len(tup) == dim:
    152     return tuple(tup)
--> 154 raise ValueError(f"Sequence must have length {dim}, got {len(tup)}.")

ValueError: Sequence must have length 1, got 3.

### Versions

aiofiles             0.8.0
alembic              1.8.1
anyio                3.6.1
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
autopage             0.5.1
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
certifi              2022.6.15
cffi                 1.15.1
charset-normalizer   2.1.0
ci-info              0.2.0
click                8.1.3
cliff                3.10.1
cmaes                0.8.2
cmd2                 2.4.2
colorama             0.4.5
colorlog             6.6.0
configobj            5.0.6
configparser         5.2.0
cycler               0.11.0
debugpy              1.6.2
decorator            5.1.1
defusedxml           0.7.1
distro               1.7.0
docopt               0.6.2
einops               0.4.1
entrypoints          0.4
et-xmlfile           1.1.0
etelemetry           0.3.0
executing            0.8.3
fastjsonschema       2.15.3
filelock             3.7.1
fitz                 0.0.1.dev2
fonttools            4.34.4
frontend             0.0.3
future               0.18.2
greenlet             1.1.2
h11                  0.13.0
httplib2             0.20.4
idna                 3.3
imageio              2.19.3
imbalanced-learn     0.9.1
imblearn             0.0
ipykernel            6.15.1
ipython              8.4.0
ipython-genutils     0.2.0
ipywidgets           7.7.1
isodate              0.6.1
itsdangerous         2.1.2
jedi                 0.18.1
Jinja2               3.1.2
joblib               1.1.0
jsonschema           4.7.2
jupyter              1.0.0
jupyter-client       7.3.4
jupyter-console      6.4.4
jupyter-core         4.11.1
jupyterlab-pygments  0.2.2
jupyterlab-widgets   1.1.1
kiwisolver           1.4.3
lab                  7.1
lightgbm             3.3.2
looseversion         1.0.1
lxml                 4.9.1
Mako                 1.2.1
MarkupSafe           2.1.1
matplotlib           3.5.2
matplotlib-inline    0.1.3
mistune              0.8.4
monai                0.9.0
nbclient             0.6.6
nbconvert            6.5.0
nbformat             5.4.0
nest-asyncio         1.5.5
networkx             2.8.4
nibabel              4.0.1
nipype               1.8.3
notebook             6.4.12
numpy                1.23.1
openpyxl             3.0.10
optuna               2.10.1
packaging            21.3
pandas               1.4.3
pandocfilters        1.5.0
parso                0.8.3
pathlib              1.0.1
pbr                  5.9.0
pickleshare          0.7.5
Pillow               9.2.0
pip                  22.2.2
prettytable          3.3.0
prometheus-client    0.14.1
prompt-toolkit       3.0.30
prov                 2.0.0
psutil               5.9.1
pure-eval            0.2.2
pycparser            2.21
pydicom              2.3.0
pydot                1.4.2
Pygments             2.12.0
pykwalify            1.8.0
PyMuPDF              1.20.1
pyparsing            3.0.9
pyperclip            1.8.2
pypinyin             0.47.0
pyradiomics          3.0.1
pyreadline3          3.4.1
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2022.1
PyWavelets           1.3.0
pywin32              304
pywinpty             2.0.6
pyxnat               1.4
PyYAML               6.0
pyzmq                23.2.0
qtconsole            5.3.1
QtPy                 2.1.0
rdflib               6.1.1
requests             2.28.1
ruamel.yaml          0.17.21
ruamel.yaml.clib     0.2.6
scikit-build         0.15.0
scikit-image         0.19.3
scikit-learn         1.1.1
scipy                1.8.1
seaborn              0.11.2
Send2Trash           1.8.0
setuptools           58.1.0
SimpleITK            2.1.1.2
simplejson           3.17.6
six                  1.16.0
sklearn              0.0
sniffio              1.2.0
soupsieve            2.3.2.post1
SQLAlchemy           1.4.39
stack-data           0.3.0
starlette            0.20.4
stevedore            4.0.0
terminado            0.15.0
threadpoolctl        3.1.0
tifffile             2022.5.4
tinycss2             1.1.1
torch                1.11.0+cu113
torchaudio           0.11.0+cu113
torchvision          0.12.0+cu113
tornado              6.2
tqdm                 4.64.0
traitlets            5.3.0
traits               6.3.2
txt2tags             3.7
typing_extensions    4.3.0
urllib3              1.26.10
uvicorn              0.18.2
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.37.1
widgetsnbextension   3.6.1

cc @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Could you please provide full log of your Error? I don't think this Error comes from PyTorch.

**Comment by ejguan** [comment]
Try to check your transformation function.

**Comment by ctwangtz** [comment]
> Please try to check your transformation function.

OK THX

**Comment by ctwangtz** [comment]
check transform!!
