### ISSUE TITLE
Create Workflow to install binary builds using install instructions as per get started page for Windows

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#82978]
Similar to : https://github.com/pytorch/pytorch/issues/82971

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
This workflow should not be separate, but rather part of the same Linux/MacOS workflow (i.e. divergence between the two should be minimal)
