### ISSUE TITLE
Reuse existing Windows AMI for the validation

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#82977]
Option 1
Use existing AMI. Remove cuda/cudnn installation. And install fresh miniconda. All changes would be done in next task #82978

Option 2
Use Github Custom hosted runners (preferred option if available from GitHub)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
Two suggestions:
 - Start with CPU smoke tests
 - If using GitHub runner, it should have some working version of NVIDIA driver (but not the cuda toolkit)
