### ISSUE TITLE
Pre-install MiniConda into Windows AMI

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#83003]
### 🐛 Describe the bug

To avoid failures like the following: https://github.com/pytorch/pytorch/runs/7730532883?check_suite_focus=true

### Versions

CI

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
Thank you for the context. This is exactly what I'm doing at the moment (with help from @atalman). The PR is out for review https://github.com/pytorch/test-infra/pull/508.

Besides this, I'm also working with @atalman to see if we can improve the way we release Windows AMI. At the moment, testing new Windows AMI on canary is a bit of a pain, i.e. https://github.com/pytorch/pytorch-canary/pull/117

**Comment by huydhn** [comment]
Resolved by https://github.com/pytorch/pytorch/pull/83188
