### ISSUE TITLE
[Primtorch] Flop Calculation For All Prims

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#83000]
### 🚀 The feature, motivation and pitch

There are various flop counters implemented for pytorch. To my knowledge, none of the them have complete coverage. With the limited opset provided by decompositions/prims, full coverage should be achievable. 

cc @ezyang @mruberry @ngimel

**Comment by gchanan** [comment]
I think we need a more precise definition of what a flop counter would do here.  it's not true that a decomposition of an op has the same number of flops as the original ops -- that is close to the opposite of the purpose of a decomposition -- so it's not clear what "full coverage" means here.

**Comment by Lezcano** [comment]
A trivial remark that's worth keeping in mind: Flops mean very little in a parallel setting (CPU but even less on CPU). An svd and a matmul both are n^3 with constants that are not too far appart, but most SVD algorithms are inherently sequential and thus quite difficult to parallelise effectively.

**Comment by eellison** [comment]
> I think we need a more precise definition of what a flop counter would do here. it's not true that a decomposition of an op has the same number of flops as the original ops -- that is close to the opposite of the purpose of a decomposition -- so it's not clear what "full coverage" means here.

Flop counter would be a formula that gives the flops given a set of real inputs. This is same way that decompositions work today. I don't think they are opposing concepts.

**Comment by eellison** [comment]
closing as being more or less done w @Chillee's flop counter
