### ISSUE TITLE
[ONNX] Produce comprehensive assertion errors for quantized outputs

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#83038]
### 🚀 The feature, motivation and pitch

Currently in `_compare_ort_pytorch_outputs`, quantized tensors' zero points and scales are flattened with the int8 representation for comparison. When int8 tensors do not match, one has to print out the scales and zero points to find that the mismatch is caused by different output scales and zero points. At the same time we do not have a clear indication of whether a tensor being compared is quantized or not.

It would be helpful to handle quantized tensor comparison differently to produce clear error messages when a discrepancy is found in test.

cc @bowen

**Comment by jazzysoggy** [comment]
I have a draft pull request,  but I'm not sure if this is the results that are wanted.
