### ISSUE TITLE
cuda run time error

### ISSUE THREAD

**Issue by ahmadmubashir** [pytorch/pytorch#8303]
CUDA_VISIBLE_DEVICES=2 python train11.py
True
build vnet
  + Number of params: 45600316
{'num_workers': 10, 'pin_memory': True}
loading train dataset
loading test set
/home/mubo/anaconda3/plugins/3dvnet/vnet.py:132: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  out = self.softmax(out)
Train Epoch: 0.00 [2/459 (0%)]	Loss: 0.8428	Error: 72.000	
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu line=81 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "train11.py", line 270, in <module>
    main()
  File "train11.py", line 184, in main
    train(args, epoch, model, trainLoader, optimizer, trainF)
  File "train11.py", line 215, in train_nll
    optimizer.step()
  File "/home/mubo/anaconda3/lib/python3.6/site-packages/torch/optim/adam.py", line 93, in step
    exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:81
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.

please see this error

**Comment by soumith** [comment]
please use https://discuss.pytorch.org
