### ISSUE TITLE
FSDP device_id + CPU offload crash

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#83054]
### 🐛 Describe the bug

There is a bug in FSDP today where we move the module due to `device_id`: https://github.com/pytorch/pytorch/blob/9e65e93c39238ec05aa7913693d7c3e4523bf257/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1048

When FSDP is recursively wrapped though, this will move already wrapped modules to the GPU, but those wrapped submodules may have CPU offloaded their params, so they should not be moved. 

This will then trigger the following crash: https://github.com/pytorch/pytorch/blob/9e65e93c39238ec05aa7913693d7c3e4523bf257/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1659

### Versions

main

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by rohan-varma** [comment]
@awgu do you know if your recent refactoring has fixed this, and have we added an appropriate unittest?

**Comment by awgu** [comment]
I added a temporary fix but no unit test: https://github.com/pytorch/pytorch/blob/9c036aa112b0a8fd9afb824d1fda058e2b66ba1d/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1394-L1407

To avoid the extraneous copy from CPU to GPU, we need to change from calling `module = module.to()` ([source code for `to()`](https://github.com/pytorch/pytorch/blob/9c036aa112b0a8fd9afb824d1fda058e2b66ba1d/torch/nn/modules/module.py#L881)) to moving parameters individually unless PT-Core introduces an argument to ignore parameters in `_apply()`.

**Comment by rohan-varma** [comment]
@awgu Is this fixed and tested in any of your recent PRs? I thought it might be, but feel free to unassign if it is not and you don't intend to work on it.
