### ISSUE TITLE
torch.nn.AdaptiveMaxPool{2|3}d create tensor with negative dimension

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#83063]
### 🐛 Describe the bug

It is obvious that a tensor cannot have negative dimension. However, torch.nn.AdaptiveMaxPool{2|3}d allows negative dimension in its parameter output_size. 

```
import torch
results={}
arg_1 = -7
arg_class = torch.nn.AdaptiveMaxPool3d(arg_1,)
arg_2_0_tensor = torch.rand([1, 64, 10, 9, 8], dtype=torch.float32)
arg_2_0 = arg_2_0_tensor.clone()
arg_2 = [arg_2_0,]
results['res'] = arg_class(*arg_2)
print(results['res'].shape)
#torch.Size([1, 64, -7, -7, -7])
```

```
import torch
results={} 
arg_1 = -1
arg_class = torch.nn.AdaptiveMaxPool2d(arg_1,)
arg_2_0_tensor = torch.rand([1, 43, 8, 9], dtype=torch.float32)
arg_2_0 = arg_2_0_tensor.clone()
arg_2 = [arg_2_0,]
results['res'] = arg_class(*arg_2)
print(results['res'].shape)
#torch.Size([1, 43, -1, -1])
```

### Versions

pytorch: 1.8.1
python: 3.8.3
os: windows11

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by redmagnos** [comment]
Is there a reason why this and #83071 are separate issues? Also, running this locally what I get is:

```
RuntimeError: Trying to create tensor with negative dimension -255: [1, 64, 1, -255]
```

So it seems like this has already been fixed in some later version of PyTorch than 1.8.1?

**Comment by cheyennee** [comment]
> Is there a reason why this and #83071 are separate issues? Also, running this locally what I get is:
> 
> ```
> RuntimeError: Trying to create tensor with negative dimension -255: [1, 64, 1, -255]
> ```
> 
> So it seems like this has already been fixed in some later version of PyTorch than 1.8.1?

Because they belongs to different torch module😂. #83063 belongs to torch.nn module, while #83071 belongs to torch.nn.functional module. Some issues occur in only one module for API with the same functionality. Anyway, what's pytorch version do you use?

**Comment by redmagnos** [comment]
Oh I'm blind, yeah I see now that they're different titles.

I'm using version 1.12.0.

**Comment by cheyennee** [comment]
> Oh I'm blind, yeah I see now that they're different titles.
> 
> I'm using version 1.12.0.

Get it. Would you mind helping me to verify whether the bug #83071 is fixed in version 1.12.0?🥺

**Comment by redmagnos** [comment]
It seems fixed too, yeah.

**Comment by cheyennee** [comment]
> It seems fixed too, yeah.

Oh, thanks😊

**Comment by jbschlosser** [comment]
out of curiosity, why run this fuzzer on such an old version of PyTorch :p

**Comment by cheyennee** [comment]
> 

Oh, I just want to repro the work of a paper to see if the results are consistent with those in the paper. In this paper, pytorch version 1.8.1 is used w(ﾟДﾟ)w But it seems that it would be better if I choose latest pytorch version.
