### ISSUE TITLE
[FSDP] Parameter MP + root FSDP `summon_full_params()` does not force full precision after forward

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#83068]
If parameter mixed precision is enabled, the root FSDP instance does not `summon_full_params()` in full precision as expected if `summon_full_params()` is called after the forward (but before the backward).

The reason is that for the root FSDP, we have `self.reshard_after_forward = False`, so the unsharded flattened parameter is kept in memory after the forward. As a result, `_rebuild_full_params()` takes the no-op code path and does not force a full precision all-gather:https://github.com/pytorch/pytorch/blob/73ddd412475cce8575494096ff33e39bb6ea4784/torch/distributed/fsdp/fully_sharded_data_parallel.py#L3291-L3294

---
Repro for `FULL_SHARD`:
```
def test_mp_between_fwd_bwd(self):
    model = nn.Linear(5, 5).cuda()
    mp = MixedPrecision(torch.float16)
    fsdp_model = FSDP(model, mixed_precision=mp)  # single root FSDP instance
    out = fsdp_model(torch.randn((2, 5)).cuda())
    print(f"Model structure:\n{fsdp_model}")
    with FSDP.summon_full_params(fsdp_model):
        for param_name, param in fsdp_model.named_parameters():
            print(f"{param_name} {param.dtype}")
```
One rank's print output:
```
Model structure:
FullyShardedDataParallel(
  (_fsdp_wrapped_module): FlattenParamsWrapper(
    (_fpw_module): Linear(in_features=5, out_features=5, bias=True)
  )
)
weight torch.float16
bias torch.float16
```
---
Since the only precondition for this bug is that the `FlatParameter`'s `_full_param_padded` is kept in memory (which happens when `self.reshard_after_forward = False`), this issue affects `SHARD_GRAD_OP` similarly:

Repro for `SHARD_GRAD_OP`:
```
def test_mp_between_fwd_bwd(self):
    model = nn.Sequential(
        nn.Linear(5, 5),
        nn.Linear(5, 5),
    ).cuda()
    mp = MixedPrecision(torch.float16)
    fsdp_model = FSDP(
        model,
        mixed_precision=mp,
        auto_wrap_policy=always_wrap_policy,  # show for non-root FSDP instances too
        sharding_strategy=ShardingStrategy.SHARD_GRAD_OP,
    )
    out = fsdp_model(torch.randn((2, 5)).cuda())
    print(f"Model structure:\n{fsdp_model}")
    with FSDP.summon_full_params(fsdp_model):
        for param_name, param in fsdp_model.named_parameters():
            print(f"{param_name} {param.dtype}")
```
One rank's print output:
```
Model structure:
FullyShardedDataParallel(
  (_fsdp_wrapped_module): FlattenParamsWrapper(
    (_fpw_module): Sequential(
      (0): FullyShardedDataParallel(
        (_fsdp_wrapped_module): FlattenParamsWrapper(
          (_fpw_module): Linear(in_features=5, out_features=5, bias=True)
        )
      )
      (1): FullyShardedDataParallel(
        (_fsdp_wrapped_module): FlattenParamsWrapper(
          (_fpw_module): Linear(in_features=5, out_features=5, bias=True)
        )
      )
    )
  )
)
0.weight torch.float16
0.bias torch.float16
1.weight torch.float16
1.bias torch.float16
```
---

I am addressing this in my refactoring, so if this is not a blocking issue, then I do not think we need to land a fix before the refactoring lands.

cc @zhaojuanmao @mrshenli @rohan-varma @ezyang

**Comment by rohan-varma** [comment]
Great catch! Shall we just have summon_full_params always force a rebuild?

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/83665
