### ISSUE TITLE
[FSDP] specifying `device_id` will move ignored parameters

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#83078]
If the wrapped module is on CPU, then specifying `device_id` will move the entire wrapped module to the device corresponding to `device_id`: https://github.com/pytorch/pytorch/blob/6c60a656b02fbd09661b282bec53940b184db3ca/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1048

We should clarify the semantics for the `ignored_modules` argument and whether FSDP should move the ignored modules' parameters.

cc @zhaojuanmao @mrshenli @rohan-varma @ezyang

**Comment by awaelchli** [comment]
@awgu Today in the latest version, the ignored modules are not moved to the device. Is it expected and going to stay this way in the future?

**Comment by awgu** [comment]
@awaelchli Yep! I think not moving ignored modules to device will be the future behavior.

In that case, I think that this issue can be closed.
