### ISSUE TITLE
[GHF] Merge bot should refuse to merge ghstack changes with local edits

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#83100]
### 🐛 Describe the bug

ghstack is not designed to support GH UI edits, so we should refuse to merge PRs with local changes (overridable with `-f`)

### Versions

CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Context: Suggesting a change in a PR like the below fails on gh-stack PRs

![Image](https://user-images.githubusercontent.com/4468967/186240509-d09b28f0-0d59-42bf-89f0-e745588d0a7d.png)

**Comment by ZainRizvi** [comment]
Action: Also say ghstack is discouraged in our public wiki

**Comment by clee2000** [comment]
fixed by https://github.com/pytorch/pytorch/pull/93298
