### ISSUE TITLE
One dlpack to rule them all

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#83112]
### 🐛 Describe the bug

One here https://github.com/pytorch/pytorch/blob/master/caffe2/python/dlpack.h
And another there https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/dlpack.h
Should we make one reference to another one?

### Versions

1.12/CI

**Comment by rgommers** [comment]
This was fixed somewhere along the way, only the ATen version is left. I think this can safely be closed.
