### ISSUE TITLE
github actions having a variety of issues - please dont merge without proper signal

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#83133]
## Current Status
ongong

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
- workflows not being scheduled
- jobs failing
- gh signal boxes not loading
- links to parts of github actions leading to page not found

## Incident timeline (all times pacific)

- 8/9 4:42pm incident began, detected by failures on hud
- 8/9 5:17pm githubstatus.com updated, confirmed incident with gha

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
https://www.githubstatus.com/incidents/8tnqgcg1qkk1

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by clee2000** [comment]
closing, github status claims its been resolved

**Comment by ZainRizvi** [comment]
Action items:
- Make the mergebot block merges on sevs
