### ISSUE TITLE
QAT  the weights -->  [-128, 127] but the relu -->[0, 255] , i can change relu to [-128, 127]?

### ISSUE THREAD

**Issue by aimen123** [pytorch/pytorch#83156]
### 🐛 Describe the bug

i used (qconfig.py) default_symmetric_qnnpack_qat_qconfig， but   errors
the question :  expected activation data type QUInt8 but got QInt8
why?

### Versions

i used (qconfig.py) default_symmetric_qnnpack_qat_qconfig， but   errors
the question :  expected activation data type QUInt8 but got QInt8
why?    

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
please checkout my answer in discussion forum:
https://discuss.pytorch.org/t/pytorch-qat-quantisation-slows-down-the-training-of-vit-significantly/157490/13
