### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by douyh** [pytorch/pytorch#8318]
I use anconda to install pytorch
```
conda install pytorch torchvision -c pytorch
```
My CUDA version is 8.0 and Cudnn verison is 5.1
When I import my torch, I meet an error
```
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /export/home/dyh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libATen.so)
```
What should I do? I've tried update gcc to 7.1.0 but it didn't work.

**Comment by ezyang** [comment]
Hi, what distro are you on?

**Comment by soumith** [comment]
@douyh you are on a Linux distro that is old enough that we dont support.
In 0.4, we deprecated RHEL6/CentOS6 and Ubuntu 12.04 support.

**Comment by douyh** [comment]
@ezyang @soumith
I checked my linux distro, CentOS7.

**Comment by douyh** [comment]
I then checked my path ```/usr/lib64/```. No```libstdc++.so.6```.
But I can find it in my anaconda, so I added this sentence in my ```.basrhc``` to avoid conflicting with my caffe and tensorflow.
```export LD_LIBRARY_PATH=/export/home/dyh/anaconda3/envs/pytorch/lib:$LD_LIBRARY_PATH```
It works.
Thanks for help.

**Comment by jdhao** [comment]
It seems that the `libstdc++`  under `/usr/lib64` is too old. `strings /usr/lib64/libstdc++.so.6|grep CXXABI` shows:

> CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_TM_1

I have installed pytorch on two servers.  pytorch version is the same and the libstdc++ version is the same (both are `/usr/lib64/libstdc++.so.6.0.19`). But this error message only appear on one server.

**Comment by vrrvg** [comment]
the same condition with @jdhao 
anyone know how to solve?

**Comment by Simpatech-app** [comment]
I have the same problem, any one fine the solution?
mportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/m/.conda/envs/torch41/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

**Comment by jdhao** [comment]
> the same condition with @jdhao
> anyone know how to solve?

Just update your LD_LIBRARY_PATH to include the correct path to libstdc++.

**Comment by Yozey** [comment]
More specifically, if you are using conda, add this to your ~/.bashrc
export LD_LIBRARY_PATH="/home/username/miniconda3/lib:$LD_LIBRARY_PATH"

**Comment by huangpan2507** [comment]
> 
> 
> I use anconda to install pytorch
> 
> ```
> conda install pytorch torchvision -c pytorch
> ```
> 
> My CUDA version is 8.0 and Cudnn verison is 5.1
> When I import my torch, I meet an error
> 
> ```
> ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /export/home/dyh/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/lib/libATen.so)
> ```
> 
> What should I do? I've tried update gcc to 7.1.0 but it didn't work.


I met the same problem ,then I try to add this to my ~/.bashrc
export LD_LIBRARY_PATH="/home/myname/anaconda3/envs/maskrcnn_benchmark/lib:$LD_LIBRARY_PATH"   
nothing change in ~/.bashrc  !!!!
so i add it by hand .

the ~/.bashrc  show below:
 1
  2 # >>> conda initialize >>>
  3 # !! Contents within this block are managed by 'conda init' !!
  4 __conda_setup="$('/home/huangpan/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
  5 if [ $? -eq 0 ]; then
  6     eval "$__conda_setup"
  7 else
  8     if [ -f "/home/huangpan/anaconda3/etc/profile.d/conda.sh" ]; then
  9          . "/home/huangpan/anaconda3/etc/profile.d/conda.sh"  # commented out by conda initialize
 10     else
 11          export PATH="/home/huangpan/anaconda3/bin:$PATH"  # commented out by conda initialize
 12     fi
 13 fi
 14 unset __conda_setup
 15 # <<< conda initialize <<
 16
 17 # export PATH="/home/huangpan/anaconda3/bin:$PATH"  # commented out by conda initialize
 18
 19 # added by Anaconda3 installer
 20 # export PATH="/home/huangpan/anaconda3/bin:$PATH"  # commented out by conda initialize
 21 export PATH=$PATH:/home/huangpan/anaconda3/bin
 22
 23 # added by Anaconda3 installer
 24 export PATH="/home/huangpan/anaconda3/bin:$PATH"
 25 # added by Anaconda3 5.3.0 installer
 26 # >>> conda init >>>
 27 # !! Contents within this block are managed by 'conda init' !!
 28 __conda_setup="$(CONDA_REPORT_ERRORS=false '/home/huangpan/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
 29 if [ $? -eq 0 ]; then
 30     \eval "$__conda_setup"
 31 else
 32     if [ -f "/home/huangpan/anaconda3/etc/profile.d/conda.sh" ]; then
 33         . "/home/huangpan/anaconda3/etc/profile.d/conda.sh"
 34         CONDA_CHANGEPS1=false conda activate base
 35     else
 36         \export PATH="/home/huangpan/anaconda3/bin:$PATH"
 37     fi
 38 fi
 39 unset __conda_setup
 40 # <<< conda init <<<
 41 export LD_LIBRARY_PATH=/export/home/huangpan/anaconda3/envs/maskrcnn_benchmark/lib:$LD_LIBRARY_PATH


the last sentence I add by hand.
Then I source  ~/.bashrc  
python 
>>>import torch
the problem still appear!  who can help me ? any suggestion is appreciated

**Comment by huangpan2507** [comment]
> 
> 
> > the same condition with @jdhao
> > anyone know how to solve?
> 
> Just update your LD_LIBRARY_PATH to include the correct path to libstdc++.

Can u help me? how to add that path to  ~/.bashrc ?

**Comment by zhouyuan888888** [comment]
> > > the same condition with @jdhao
> > > anyone know how to solve?
> > 
> > 
> > Just update your LD_LIBRARY_PATH to include the correct path to libstdc++.
> 
> Can u help me? how to add that path to ~/.bashrc ?



> > > the same condition with @jdhao
> > > anyone know how to solve?
> > 
> > 
> > Just update your LD_LIBRARY_PATH to include the correct path to libstdc++.
> 
> Can u help me? how to add that path to ~/.bashrc ?

Correct the last code to： LD_LIBRARY_PATH=”/export/home/huangpan/anaconda3/envs/maskrcnn_benchmark/lib:$LD_LIBRARY_PATH“.
Then run source ~/.bashrc.
It may be work!

**Comment by TerenceCYJ** [comment]
https://discuss.pytorch.org/t/import-pytorch-failed/23199/4

**Comment by liuqi8827** [comment]
Hi,
I solved it by upgrading gcc.
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
`sudo apt-get update`
`sudo apt-get install gcc-6 g++-6`
