### ISSUE TITLE
Making quantizable LSTM scriptable

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#83211]
### 🐛 Describe the bug

Currently it errors out in https://github.com/pytorch/pytorch/blob/master/torch/nn/quantizable/modules/rnn.py#L355, wondering if it can be supported in `torch.jit.script` and how much effort is this.

### Versions

master

**Comment by jerryzh168** [comment]
Current error message:
![290595222_1423197471513165_6755654785440789984_n](https://user-images.githubusercontent.com/4958441/184032285-6a0675d0-a201-474d-a387-7b260df23e7d.png)

**Comment by davidberard98** [comment]
@jerryzh168 I think this expression can be rewritten to be scriptable like this:

e.g., this fails:
```python
import torch

def fn(x, y):
    return x.reshape(-1, *y.shape[-2:])

torch.jit.script(fn)
```

and this scripts successfully:
```python
import torch

def fn(x, y):
    return x.reshape([-1] + y.shape[-2:])

torch.jit.script(fn)
```

**Comment by jerryzh168** [comment]
that's great, thanks a lot, we'll try

**Comment by vadimkantorov** [comment]
Is this also equivalent to `flatten(end_dim = -3)`?

**Comment by andrewor14** [comment]
Related issue: https://github.com/pytorch/pytorch/issues/75042

**Comment by andrewor14** [comment]
Resolved here https://github.com/pytorch/pytorch/pull/83304
