### ISSUE TITLE
QAT the bias  is the int32, how to set the int8?

### ISSUE THREAD

**Issue by aimen123** [pytorch/pytorch#83227]
### 🐛 Describe the bug

i try to do quantization, the weight is int8 ,but the bias is int32, i want to set the bias ---> int8, what i need to do ?
thanks

### Versions

help me, thanks

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by aimen123** [comment]
please help me, i dont do it

**Comment by jerryzh168** [comment]
please checkout my answer in discussion forum:
https://discuss.pytorch.org/t/pytorch-qat-quantisation-slows-down-the-training-of-vit-significantly/157490/13
