### ISSUE TITLE
torch.addcdiv_ != torch.addcdiv (in place addcdiv_ ensures higher precision vs out of place addcdiv)

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#83231]
### 🐛 Describe the bug

While working on stochastic rounding for bfloat16 optimizer, started seeing very aberrant behaviour that ultimately came down to the following difference:

~~~
p.data = torch.addcdiv(p.data, exp_avg, centered_variance, value =-step_size)
~~~

is very different than:
~~~
p.data.addcdiv_(exp_avg, centered_variance, value =-step_size)
~~~

In reviewing the code, found this special exception:
<img width="1084" alt="addcdiv_upscale" src="https://user-images.githubusercontent.com/46302957/184072891-f0f152b6-0576-4250-b791-81d8992fbc0e.png">

link:
https://github.com/pytorch/pytorch/blob/12382f0a38f8199bc74aee701465e847f368e6de/aten/src/ATen/native/cuda/PointwiseOpsKernel.cu?fbclid=IwAR0SdS6mVAGN0TB_TAdKt0WVWWjxiBkmP6Inj9lYH8oB68wjsbQzinlH-xY#L92

It appears this upscaling and thus higher precision is happening for addcdiv_  (in place) but not for  addcdiv (out of place)..thus we get very different results depending on simply using _ or not.

Request that in place or out of place maintain matching precision/result.

(will try to make a simpler repo tomorrow but I think a quick code review will isolate this issue as well. )

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220810+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.27

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-1081-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: 
GPU 0: NVIDIA A10G
GPU 1: NVIDIA A10G
GPU 2: NVIDIA A10G
GPU 3: NVIDIA A10G

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] numpydoc==1.4.0
[pip3] torch==1.13.0.dev20220810+cu113
[pip3] torch-model-archiver==0.6.0b20220513
[pip3] torch-workflow-archiver==0.2.4b20220513
[pip3] torchserve==0.6.0b20220513
[pip3] torchtext==0.13.0
[pip3] torchvision==0.14.0.dev20220810+cu113
[conda] blas                      2.115                       mkl    conda-forge
[conda] blas-devel                3.9.0            15_linux64_mkl    conda-forge
[conda] captum                    0.5.0                         0    pytorch
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] libblas                   3.9.0            15_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            15_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            15_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            15_linux64_mkl    conda-forge
[conda] magma-cuda116             2.6.1                         0    pytorch
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-service               2.4.0            py39hb699420_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h1fd5c3a_3    conda-forge
[conda] mkl_random                1.2.2            py39h8b66066_1    conda-forge
[conda] mypy_extensions           0.4.3            py39hf3d152e_5    conda-forge
[conda] numpy                     1.22.4           py39hc58783e_0    conda-forge
[conda] numpydoc                  1.4.0              pyhd8ed1ab_1    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.13.0.dev20220810+cu113          pypi_0    pypi
[conda] torch-model-archiver      0.6.0                    py39_0    pytorch
[conda] torch-workflow-archiver   0.2.4                    py39_0    pytorch
[conda] torchserve                0.6.0                    py39_0    pytorch
[conda] torchtext                 0.13.0                     py39    pytorch
[conda] torchvision               0.14.0.dev20220810+cu113          pypi_0    pypi

**Comment by lessw2020** [comment]
As promised, here is a simple repro case.  Note that if you run at small size, it's fine ...but at larger scale, it fails which is why it was failing in optimizer use cases.

(credit to @nestordemeure for noting the size is the key issue here).

Python code for easy repro:
~~~
use_type = torch.bfloat16

alpha = .80
tsize = 2000000
data_tensor = torch.randn(tsize,dtype=use_type)

atensor = torch.randn(tsize, dtype=use_type)
btensor = torch.randn(tsize, dtype=use_type)

#clones
data_clone = data_tensor.clone()
aclone = atensor.clone()
bclone = btensor.clone()

# inplace
data_tensor.addcdiv_(atensor, btensor,value=-alpha)
# out of place
data_clone = torch.addcdiv(data_clone, aclone, bclone, value=-alpha)

# verify
torch.equal(data_tensor, data_clone)
~~~
Examples: 

Works fine (tensor size = 20)
<img width="784" alt="addcdiv_small_true" src="https://user-images.githubusercontent.com/46302957/184197272-ebe11b74-0915-4614-9e88-64f6508bccaf.png">

### Fails (tensor size = 1M):
<img width="784" alt="addcdiv_repro_case" src="https://user-images.githubusercontent.com/46302957/184197321-64f3e2d4-480f-4afe-ad5d-b3310296265b.png">

**Comment by ngimel** [comment]
This works correctly on cuda, but fails on cpu. cc @mingfeima and @frank-wei, can you please route correctly?

**Comment by mingfeima** [comment]
@CaoE, could you pleas help fix this issue?

**Comment by frank-wei** [comment]
Not sure why @CaoE could not be assignee. so I added @mingfeima.

**Comment by CaoE** [comment]
I will look at it.

**Comment by CaoE** [comment]
Sorry for missing this issue.  addcdiv was also optimized in https://github.com/pytorch/pytorch/pull/55221, doing math in float. 
@lessw2020 I use your simple repro case, and even use data_tensor = data_clone.clone() or data_clone = data_tensor.clone() in the end `torch.equal(data_tensor, data_clone)` still return False.
I also print the result in the c++ side but didn't find any different value.

**Comment by CaoE** [comment]
Close it. @lessw2020  If you have questions you can reopen it at any time.

**Comment by wcn3** [comment]
I've run into this using tensors that don't have NaN components.

**Collecting environment information...**
PyTorch version: 2.6.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.6.1 (arm64)
GCC version: Could not collect
Clang version: 17.0.6
CMake version: version 3.31.7
Libc version: N/A

Python version: 3.11.14 (main, Oct 11 2025, 02:11:58) [Clang 17.0.0 (clang-1700.0.13.5)] (64-bit runtime)
Python platform: macOS-15.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M4 Max

Versions of relevant libraries:
[pip3] mypy_extensions==1.1.0
[pip3] numpy==2.2.3
[pip3] torch==2.6.0
[conda] Could not collect

Attached is the repro for this behavior.

[repro.py](https://github.com/user-attachments/files/23829714/repro.py)
