### ISSUE TITLE
torch.lu_solve will return tensor if input contains int type tensor

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#83318]
### 🐛 Describe the bug

It's written on documentation that torch.lu_solve supports float, double, cfloat and cdouble dtypes for input excluding int type. However, I find that if input contains int type tensor, cpu will return a tensor, while gpu crashes.

```
results = dict()
import torch
arg_1 = torch.rand([2, 3, 1], dtype=torch.float32)
arg_2 = torch.rand([2, 3, 3], dtype=torch.float32)
arg_3 = torch.randint(-10,10,[2, 3], dtype=torch.int32)
try:
  results["res_cpu"] = torch.lu_solve(arg_1,arg_2,arg_3,)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
arg_4 = arg_1.clone().cuda()
arg_5 = arg_2.clone().cuda()
arg_6 = arg_3.clone().cuda()
try:
  results["res_gpu"] = torch.lu_solve(arg_4,arg_5,arg_6,)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)
print(results)
```

results={'res_cpu': tensor([[[ 0.4699],
         [-2.0710],
         [ 1.2003]],
        [[-7.0208],
         [ 7.6626],
         [-5.0952]]]), 'err_gpu': 'ERROR:CUDA error: unknown error'}

### Versions

pytorch: 1.8.1
python: 3.8.3
os: win11

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by IvanYashchuk** [comment]
The state of linear algebra functions has improved since 1.8.1 and there's no error in the latest version. The only suggestion I have is to upgrade to a newer version of PyTorch.

**Comment by Lezcano** [comment]
Even better, if using `master` / `nightly`, you'd be better off using `torch.linalg.lu_solve`
