### ISSUE TITLE
torch.tril lacks of checking 'out of bound' on cuda

### ISSUE THREAD

**Issue by taotaobear** [pytorch/pytorch#83326]
### 🐛 Describe the bug

```
results = dict()
import torch
arg_1 = torch.rand([4], dtype=torch.float32)
try:
  results["res_cpu"] = torch.tril(arg_1,)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
arg_2 = arg_1.clone().cuda()
try:
  results["res_gpu"] = torch.tril(arg_2,)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)
print(results)
```

The result is {'err_cpu': 'ERROR:Dimension out of range (expected to be in range of [-1, 0], but got -2)', 'res_gpu': tensor([0.6544, 0.0000, 0.0000, 0.0000], device='cuda:0')}.

### Versions

pytorch: 1.8.1
python: 3.8.3
os: win11

cc @ngimel

**Comment by ezyang** [comment]
Should be easy to add the dimension test for tril, if you submit a PR add me as reviewer.
