### ISSUE TITLE
when input type of torch.nn.AvgPool3d is bfloat16, cpu's running result is inconsistent with gpu

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#83321]
### 🐛 Describe the bug

```
results = dict()
import torch
arg_1_0 = 3
arg_1_1 = 2
arg_1_2 = 2
arg_1 = [arg_1_0,arg_1_1,arg_1_2,]
arg_2 = 1
arg_class = torch.nn.AvgPool3d(arg_1,stride=arg_2,)
arg_3_0_tensor = torch.rand([20, 16, 50, 44, 31], dtype=torch.bfloat16)
arg_3_0 = arg_3_0_tensor.clone()
arg_3 = [arg_3_0,]
try:
  results["res_cpu"] = arg_class(*arg_3)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
arg_class = arg_class.cuda()
arg_3_0 = arg_3_0_tensor.clone().cuda()
arg_3 = [arg_3_0,]
try:
  results["res_gpu"] = arg_class(*arg_3)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)
print(results)
```

The result is:
{'err_cpu': 'ERROR:"avg_pool3d_out_frame" not implemented for \'BFloat16\'', 'res_gpu': tensor([[[[[0.5586, 0.5234, 0.6406,  ..., 0.5820, 0.4336, 0.5156].........}.

It's unexpected that cpu outputs error message, while gpu runs successfully.

### Versions

pytorch: 1.8.1
python: 3.8.3
os: win11

**Comment by cheyennee** [comment]
Same problem was found in torch.nn.functional.softshrink.

**Comment by ngimel** [comment]
Closing as expected, same datatype support is not guaranteed for the different backends. If you need this operation file an issue requesting support.
