### ISSUE TITLE
"clamp_min_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#83322]
### 🐛 Describe the bug

```
results = dict()
import torch
arg_1 = torch.rand([3], dtype=torch.float16)
arg_2 = torch.rand([3], dtype=torch.float32)
arg_3 = None
arg_4 = None
arg_5 = "mean"
try:
  results["res_cpu"] = torch.nn.functional.binary_cross_entropy_with_logits(arg_1,arg_2,arg_3,pos_weight=arg_4,reduction=arg_5,)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
arg_1 = arg_1.clone().cuda()
arg_2 = arg_2.clone().cuda()
try:
  results["res_gpu"] = torch.nn.functional.binary_cross_entropy_with_logits(arg_1,arg_2,arg_3,pos_weight=arg_4,reduction=arg_5,)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)
print(results)
```

When I run above code, the result is {'err_cpu': 'ERROR:"clamp_min_cpu" not implemented for \'Half\'', 'res_gpu': tensor(0.6844, device='cuda:0')}. Is this an expected result since cpu's result is inconsistent with gpu's result?

### Versions

pytorch: 1.8.1
python: 3.8.3
os: win11

**Comment by malfet** [comment]
Still the case, but yes, torch.float16 half implementation is not performant, so it doesn't make much sense to add more and more explicit operators

**Comment by ngimel** [comment]
Closing as expected
