### ISSUE TITLE
Add type hints for values generated by dataloaders

### ISSUE THREAD

**Issue by bencwallace** [pytorch/pytorch#83347]
### 🚀 The feature, motivation and pitch

Given a dataloader `dataloader` of type `DataLoader[T_co]`, it should be possible to infer statically that `next(iter(dataloader))` is of type `T_co`.

The basic change required is to make [`_BaseDataLoaderIter`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L620) subclass `Generic[T_co]` and annotate its [`__next__`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L676) method to have return type `T_co`. These annotations will probably also need to be propagated to other places to make everything consistent.

I can start working on these changes but please let me know if there's some reason I've missed why this might not work or might not even be desirable. Thanks!

cc @SsnL @VitalyFedyunin @ejguan @NivekT @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by ezyang** [comment]
sgtm

**Comment by NivekT** [comment]
Closing this for now because it doesn't seem feasible based on the discussion in #83421. We are happy to re-open it if there is a feasible solution.
