### ISSUE TITLE
Massive growth in cpu memory use when loading model from cpu to gpu

### ISSUE THREAD

**Issue by lpkoh** [pytorch/pytorch#83340]
### 🐛 Describe the bug

I am building an application that uses the yolo object detector. I trained a darknet model from https://github.com/AlexeyAB/darknet which I then convert to pytorch in my app using https://github.com/Tianxiaomo/pytorch-YOLOv4.

I am facing a strange issue when I pass the model from cpu to gpu, the cpu memory usage explodes.

![image](https://user-images.githubusercontent.com/48631399/184416261-65da48b4-a8c1-40b0-89f5-8d465da39947.png)

Basically, the cpu memory usage when I create the darknet object model and load the weights is only ~0.2GB (which makes sense as the darknet weights file is 0.2GB). However, when I move the model to cuda, the cpu memory usage increases by 2.5GB.
I have torch 1.4.0, and my machine has 4 gpus. I am running the commands from inside a docker container.

I've looked at:
https://github.com/pytorch/pytorch/issues/7415
and
https://github.com/pytorch/pytorch/issues/72791
Their fixes have not worked for me.

### Versions

Had issue running the provided code, but my env is as follows:
opencv-python==4.3.0.38
tensorflow-gpu==1.15.5
scikit-learn==0.21.2
numpy==1.18.5
pydantic==1.7.4
pandas==1.3.5
pika==1.2.0
scipy==1.7.3
python-dateutil==2.8.2
protobuf==3.20.1
torch==1.4.0

**Comment by ezyang** [comment]
This is in all likelihood due to CUDA initializing the CUDA context. You can try doing a simple script with only a cuda operation in it to see.
