### ISSUE TITLE
Meta Impl of native_layer_norm (math_native_layer_norm) Errors Where Cuda Succeeds

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#83362]
### 🐛 Describe the bug

```
import torch

for device in ["cuda", "meta"]:
    a = torch.empty_strided([4, 576, 768], (442368, 1, 576), device=device)
    b = [768]
    c = torch.empty([768], device=device)
    d = torch.empty([768], device=device)
    e = .01
    args = (a, b, c, d, e)
    print(device)
    torch.ops.aten.native_layer_norm(*args)
    print("succeeds")
```
> cuda
succeeds
meta
Traceback (most recent call last):
  File "/scratch/eellison/work/pytorch/test/tmp.py", line 15, in <module>
    torch.ops.aten.native_layer_norm(*args)
  File "/scratch/eellison/work/pytorch/torch/_ops.py", line 175, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

### Versions

master

cc @ezyang @eellison @bdhirsh

**Comment by bdhirsh** [comment]
Looks like the `view()` call in `math_native_layer_norm` should be a reshape. fix coming
