### ISSUE TITLE
torch.nn.functional.conv2d runs slower on float16 type than on float32 type

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#83382]
### 🐛 Describe the bug

Float16 carries less precision information than float32, so float16 should execute faster. When I run below snippet code, float16 runs slower than float32.
```
results = dict()
import torch
import time
arg_1 = torch.rand([1, 16, 176, 320], dtype=torch.float16)
arg_2 = torch.rand([16, 16, 1, 1], dtype=torch.float16)
arg_3 = torch.rand([16], dtype=torch.float16)
arg_4 = [1,1]
arg_5 = [0,0]
arg_6 = [1,1]
arg_7 = 1
start = time.time()
results["time_low"] = torch.nn.functional.conv2d(arg_1,arg_2,arg_3,arg_4,arg_5,arg_6,arg_7,)
results["time_low"] = time.time() - start
arg_1 = arg_1.clone().type(torch.float32)
arg_2 = arg_2.clone().type(torch.float32)
arg_3 = arg_3.clone().type(torch.float32)
start = time.time()
results["time_high"] = torch.nn.functional.conv2d(arg_1,arg_2,arg_3,arg_4,arg_5,arg_6,arg_7,)
results["time_high"] = time.time() - start
print(results)
```
The result is {'time_low': 0.30806946754455566, 'time_high': 0.0019991397857666016}. Float16 is much slower than float32.

### Versions

pytorch: 1.8.1
python: 3.8.3
os: win11

cc @VitalyFedyunin

**Comment by ezyang** [comment]
You're probably not getting any specialized kernel for float16. Try upgrading PyTorch or running it on CUDA instead.
