### ISSUE TITLE
[ONNX] Convert GFPGANv1.3.pth to onnx

### ISSUE THREAD

**Issue by magicse** [pytorch/pytorch#83394]
### 🐛 Describe the bug

converting Convert GFPGANv1.3.pth to onnx give me next errors ->
```
Traceback (most recent call last):
  File "Z:\AI_SDK\CPP_GFPGAN\Pretrained_MODELS_GFPGAN\pth2onnx.py", line 41, in
<module>
    torch.onnx.export(model,inputs,onnxpath,export_params=True,verbose=True,inpu
t_names=['input'],output_names=['output'],opset_version=12)
  File "C:\Python38\lib\site-packages\torch\onnx\__init__.py", line 316, in expo
rt
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\Python38\lib\site-packages\torch\onnx\utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, outpu
t_names,
  File "C:\Python38\lib\site-packages\torch\onnx\utils.py", line 724, in _export

    _model_to_graph(model, args, verbose, input_names,
  File "C:\Python38\lib\site-packages\torch\onnx\utils.py", line 497, in _model_
to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "C:\Python38\lib\site-packages\torch\onnx\utils.py", line 216, in _optimi
ze_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Python38\lib\site-packages\torch\onnx\__init__.py", line 373, in _run
_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Python38\lib\site-packages\torch\onnx\utils.py", line 1032, in _run_s
ymbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "C:\Python38\lib\site-packages\torch\onnx\symbolic_helper.py", line 172,
in wrapper
    return fn(g, *args, **kwargs)
  File "C:\Python38\lib\site-packages\torch\onnx\symbolic_opset9.py", line 1281,
 in _convolution
    raise RuntimeError("Unsupported: ONNX export of convolution for kernel "
RuntimeError: Unsupported: ONNX export of convolution for kernel of unknown shap
e.
```
Code of converter
```python
import torch
from gfpgan.archs.gfpganv1_clean_arch import GFPGANv1Clean
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
modelpath=r"Z:\AI_SDK\CPP_GFPGAN\Pretrained_MODELS_GFPGAN\experiments\pretrained_models\GFPGANv1.3.pth"
channel_multiplier=2
model = GFPGANv1Clean(
    out_size=512,
    num_style_feat=512,
    channel_multiplier=channel_multiplier,
    decoder_load_path=None,
    fix_decoder=False,
    num_mlp=8,
    input_is_latent=True,
    different_w=True,
    narrow=1,
    sft_half=True)

w=torch.load(modelpath)
model.load_state_dict(w,strict=False)
model.to(device)
model.eval()
inputs = torch.ones((1, 3, 512,512)).to(device)
onnxpath=r"Z:\AI_SDK\CPP_GFPGAN\Pretrained_MODELS_GFPGAN\experiments\pretrained_models\GFPGANv1.3.onnx"
print(model)
torch.onnx.export(model,inputs,onnxpath,export_params=True,verbose=True,input_names=['input'],output_names=['output'],opset_version=12) 
```
[model.log](https://github.com/pytorch/pytorch/files/9334348/model.log)

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 7 Professional
GCC version: (x86_64-posix-seh-rev3, Built by MinGW-W64 project) 12.1.0
Clang version: 14.0.4
CMake version: version 3.24.0-rc1
Libc version: N/A

Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 6
4 bit (AMD64)] (64-bit runtime)
Python platform: Windows-7-6.1.7601-SP1
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] Could not collect

**Comment by AllenTiTaiWang** [comment]
Hi,

1. torch 1.10 is a bit outdated, could you please try nightly? 
2. For the model, could you try catch the difference parts between GFPGANv1Clean and GFPGANv1Clean1.3 (the model you are using I guess), I think that's the key why the latest one wouldn't work, and we should focus on that.

**Comment by magicse** [comment]
ok

**Comment by magicse** [comment]
I found some troubles from another users
1 [GFPGANCleanv1-NoCE-C2.pth to ONNX](https://github.com/TencentARC/GFPGAN/issues/184)

**Comment by magicse** [comment]
I made update of torch yo last ver. 1.12.1+cpu
But get the same problem

**Comment by magicse** [comment]
[model_2.log](https://github.com/pytorch/pytorch/files/9339519/model_2.log)

**Comment by magicse** [comment]
[model_2.log](https://github.com/pytorch/pytorch/files/9339597/model_2.log)
Log file consist from 
1 print (model)
2 I pasted the following commands into the symbolic_opset9.py file

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
