### ISSUE TITLE
LIBTORCH: Stack smashing encountered when using malloc/ free with libtorch

### ISSUE THREAD

**Issue by SM1991CODES** [pytorch/pytorch#83390]
### 🐛 Describe the bug

I am trying to use libtorch + torch_tensorrt

Since I need a large array of size 1x6x320x320, I tried using malloc to first create the array locally, then use torch::from_blob().cuda() to send it to GPU.

I can print and see the values correctly from the torch cuda tensor.
However, when I later call free to release the malloc memory, I get the following error:
![image](https://user-images.githubusercontent.com/69435296/184531691-a3309719-9aab-4cef-b4ce-920144da8406.png)

Here is the code

```
class array3DFloat
{
public:
    float* array;
    uint16_t n_rows=0, n_cols=0, n_channels=0;
    uint16_t row_index = 0, col_index = 0, gid = 0;
    uint32_t numElementsArray = 0;
    //
    array3DFloat(uint16_t n_rows, uint16_t n_cols, uint16_t n_channels, float init_val=99.99)
    {
        this->n_rows = n_rows;
        this->n_cols = n_cols;
        this->n_channels = n_channels;
        this->array = (float*)malloc(sizeof(float) * n_rows * n_cols * n_channels);
        this->numElementsArray = n_rows * n_cols * n_channels;
        //
        for(auto ch_index = 0; ch_index < this->n_channels; ch_index++)
        {
            for(auto r_index = 0; r_index < this->n_rows; r_index++)
            {
                for(auto c_index = 0; c_index < this->n_cols; c_index++)
                {
                    this->gid = this->n_rows * this->n_cols * ch_index + r_index * this->n_cols + c_index;

                    // sanity check
                    if(this->gid >= this->numElementsArray)
                    {
                        printf("ERROR: Array overflow likely...\n");
                    }
                    
                    this->array[this->gid] = init_val;
                }
            }
        }
        //
        printf("Array init done\n");
    }

    inline void releaseArray()
    {
        free(this->array);
        printf("Array release..\n");
    }
};

auto bev = array3DFloat(2, 2, 2);
auto tensor_bev = torch::from_blob(bev.array, {2, 2, 2}).cuda();
cout << tensor_bev << endl;
bev.releaseArray();
```

Please help me understand this.

Best Regards

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.11.0+cu113
[pip3] torch-tensorrt==1.1.0+c2e396a8
[pip3] torchaudio==0.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

cc @jbschlosser @ngimel

**Comment by ezyang** [comment]
Your code looks correct. I'd guess there is a problem elsewhere in your code. Try compiling with ASAN, or at least get a stack trace for the stack smash.
