### ISSUE TITLE
Error when building pytorch under develop mode

### ISSUE THREAD

**Issue by zrphercule** [pytorch/pytorch#8339]
Hi, I have got a problem when building pytorch under develop mode on Mac OS.
Here is my cmd information:

➜  pytorch git:(expand_ops) python setup.py develop
running develop
-- Building version 0.5.0a0+d16407e
running egg_info
writing torch.egg-info/PKG-INFO
writing top-level names to torch.egg-info/top_level.txt
writing dependency_links to torch.egg-info/dependency_links.txt
reading manifest file 'torch.egg-info/SOURCES.txt'
writing manifest file 'torch.egg-info/SOURCES.txt'
running build_ext
-- Building with NumPy bindings
-- Not using cuDNN
-- Not using CUDA
-- Not using MKLDNN
-- Not using NCCL
-- Building with distributed package
error: [Errno 2] No such file or directory: '/Users/zrphercule/zfacebook/pytorch/zrphercule/T30005697/pytorch/torch/lib/tmp_install/THD_deps.txt'
➜  pytorch git:(expand_ops) pwd
/Users/zrphercule/zfacebook/pytorch/zrphercule/T30005697/pytorch

expand_ops is a branch created on my own fork.

**Comment by soumith** [comment]
```
python setup.py develop
```

This has to be changed to

```
python setup.py build develop
```

**Comment by apaszke** [comment]
Why is that? It doesn't match what we used to do, and what `develop` should do (`build` should be one of its steps).

**Comment by apaszke** [comment]
Oh I think you meant `build_deps`

**Comment by zrphercule** [comment]
So the problem here is we should use:
python setup.py build develop
instead of 
python setup.py develop
