### ISSUE TITLE
Concatenate function breaks when using GPU other than 0

### ISSUE THREAD

**Issue by ajbrock** [pytorch/pytorch#834]
There's a bug in the cat() function that shows up if you try to concatenate a tensor that isn't on GPU 0; for some reason it seems to be trying to copy the concatenated tensors over to GPU 0, which then throws an illegal memory access error:

```
X,Y = torch.FloatTensor(5,4,20,20).cuda(0),torch.FloatTensor(5,8,20,20).cuda(0)
Z = torch.cat((X,Y),1)
```

works fine, but

```
X,Y = torch.FloatTensor(5,4,20,20).cuda(2),torch.FloatTensor(5,8,20,20).cuda(2)
Z = torch.cat((X,Y),1)
Z
```

returns 

`RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /data/users/soumith/miniconda2/conda-bld/pytorch-0.1.7_1485444530918/work/torch/lib/THC/generic/THCTensorCopy.c:65`

But only once you actually request the value of Z (you can still call cat() and it won't throw an error).  If you call Z.get_device() it will return 0. I have tried this in multiple ways (i.e. without the first call to cuda(0)) and have yet to have it behave any other way.

The workaround for this (say, if you're trying to run a DenseNet) is to set torch.cuda.set_device(X.get_device()) before calling cat(), but it's not exactly an elegant solution.

**Comment by apaszke** [comment]
It's a bug that's been fixed recently. I think it's in 0.1.9 already. If not, you can use the current master.

**Comment by ajbrock** [comment]
Woops, I missed that one--my bad!
