### ISSUE TITLE
Windows CI test breakages due to env variable length limit

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#83433]
## Current Status
mitigated

to be verified on [HUD](https://hud.pytorch.org/pytorch/pytorch/commit/1187dedd336e4f6c0028e0d081b676c2f5796316)

## Error looks like
```
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch\pytorch\test\test_ops.py", line 1835, in <module>
    run_tests()
  File "C:\actions-runner\_work\pytorch\pytorch\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 634, in run_tests
    os.environ['DISABLED_TESTS_DICT'] = [fp.read](http://fp.read/)()
  File "C:\Jenkins\Miniconda3\lib\[os.py](http://os.py/)", line 685, in _setitem_
    putenv(key, value)
ValueError: the environment variable is longer than 32767 characters
```

## Incident timeline (all times pacific)

* Aug 14th: PyTorch flaky test bot disabled a bunch of [tests](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+DISABLED), i.e. (test_aot_autograd_exhaustive in TestEagerFusionOpInfoCPU) on this date. This probably tipped over the env variable length limit.
* Aug 15th 9AM: OSS CI oncall was notified about the issue. There were also multiple alerts fired about trunk breakage.
* Aug 15th 10AM: The fix was reviewed https://github.com/pytorch/pytorch/pull/83426 and force merged into master to facilitate the fix. Other can now rebase to get it and re-run the Windows tests.
* Aug 15th 11AM: A minor update to the previous fix https://github.com/pytorch/pytorch/pull/83436 

## User impact
All Windows tests failed

## Root cause
Windows env variable has an upper limit of 32767 characters, and we unknowingly used an env variable to keep the list of flaky (disabled) tests so that we can refer to it from time to time. Once there were too many flaky tests (262), this step failed on Windows

## Mitigation
* https://github.com/pytorch/pytorch/pull/83426 to not keep the list of flaky (disabled) tests in an env variable on Windows. Instead, we will just load the JSON structure directly from the file. This might has a tiny perf impact on running the tests, but that should be ok
* Create a following up issue (https://github.com/pytorch/pytorch/issues/83458) to double check if:
  * It impacts other platforms (Linux, Mac, etc)
  * There's a better way to handle this, i.e. without using env variable, use multiple env variables, hashing, etc..

## Prevention/followups
* Find a better way to pass flaky (disabled) tests information around.  Loading it from file might not be that bad (if the file is small enough) https://github.com/pytorch/pytorch/issues/83458
* Keep track of the number of flaky tests using [Rockset query](https://console.rockset.com/lambdas/details/commons.flaky_tests). I'll create a TTS metric for this

**Comment by huydhn** [comment]
The [small flood of flaky tests](https://github.com/pytorch/pytorch/issues?page=2&q=is%3Aopen+is%3Aissue+author%3Aapp%2Fpytorch-bot+updated%3A%3E%3D2022-02-16) coming from functorch is supposed to be fixed by https://github.com/pytorch/pytorch/pull/83431. This has already been merged into trunk

**Comment by huydhn** [comment]
This has been mitigated. All the Windows tests in trunk are green now https://hud.pytorch.org/pytorch/pytorch/commit/1187dedd336e4f6c0028e0d081b676c2f5796316

**Comment by ZainRizvi** [comment]
PR with mitigation: https://github.com/pytorch/pytorch/pull/83466/
