### ISSUE TITLE
Look into how the CI passes the list of slow tests and disabled tests around using env variables

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#83458]
### 🐛 Describe the bug

We have a SEV https://github.com/pytorch/pytorch/issues/83433 on Windows CI in which the list of disabled tests grows too big and breaks the limit of Windows env variable length of 32767 chars.  At the moment, the CI maintains the following two lists in different env variables:

* Slow tests (SLOW_TESTS_DICT)
* Flaky (disabled) tests (DISABLED_TESTS_DICT)

We should revisit the way we are using env variables here to see if there is a better or safer way to passing these information around.  Some limits to keep in mind:

* Windows vs2019 runner has the upper limit of 32767 chars for env variable length (learn from the SEV)
* The number is 2619242 for Ubuntu 18.04 (bionic) deducted using `xargs --show-limits`
* The number is 1048576 for mac OS deducted using `getconf ARG_MAX`

So there is always a limit.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @clee2000 

### Versions

All versions

**Comment by huydhn** [comment]
A quick look into the JSON file for disabled test https://raw.githubusercontent.com/pytorch/test-infra/generated-stats/stats/disabled-tests.json shows that a lot of information about those tests are recorded there, but not alls are needed for the purpose of finding out which tests are disabled at runtime.  At least, we shouldn't need to keep this whole JSON structure as env variable, which is both inefficient and probably unsafe.

**Comment by clee2000** [comment]
fixed by https://github.com/pytorch/pytorch/pull/83487

**Comment by ZainRizvi** [comment]
Fixed by @clee2000
