### ISSUE TITLE
improve cuda graph to be memory efficient

### ISSUE THREAD

**Issue by Jack47** [pytorch/pytorch#83490]
### 🚀 The feature, motivation and pitch

CUDA graph is awesome for static graphs such as classification in CV, it greatly improves CNN's speed!

Currently I'm using CUDA graph on a big CNN model with 1k+ layers, batch size is 64. Activations in every layer is 64M level. I can train this model with activation checkpoint, but it will OOM when paring with CUDA graph, I find it's because every callable cuda graph will statically allocate [4 variables: input, output, grad output, grad input](https://github.com/pytorch/pytorch/blob/master/torch/cuda/graphs.py#L404-L406). This will cause huge memory consumption.

Can we find some way to reuse these statically allocated buffers? 
1. When using with activation checkpointing, we can reuse CUDA graph's input with activation checkpointing input. 
2. In FWD pass, grad output and grad input should be reused.
3. In BWD pass, when using with DDP, grad output and grad input can be reused when grad's allreduce finished

@mcarilli any ideas to improve this?

cc @mcarilli @ezyang

**Comment by vikalp-tomer** [comment]
Have you already checked with those of greater batch sizes i.e. above 64 ?

**Comment by Jack47** [comment]
> Have you already checked with those of greater batch sizes i.e. above 64 ?

Bigger batch size, bigger statically allocated memory for CUDA graphs

**Comment by ezyang** [comment]
This is a known problem with CUDA graphs. It is difficult to work around, because CUDA graphs burns in the memory addresses so you have to keep those exact memory addresses around. One way around this is to rewrite addresses on the cuda graph before launching it (we don't have a Python API for this, but CUDA graphs internally supports it), but we don't have support for this right now.

**Comment by Jack47** [comment]
> This is a known problem with CUDA graphs. It is difficult to work around, because CUDA graphs burns in the memory addresses so you have to keep those exact memory addresses around. One way around this is to rewrite addresses on the cuda graph before launching it (we don't have a Python API for this, but CUDA graphs internally supports it), but we don't have support for this right now.

Thanks for reply! May I known which api can rewrite addresses on the cuda graph? do you mean [cudaGraphExecKernelNodeSetParams](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__GRAPH.html#group__CUDART__GRAPH_1g119efd892d546aece0d7ebe48c37b02b)

**Comment by ezyang** [comment]
yes

**Comment by Jack47** [comment]
we are suffering from oom when capture cuda graph. Finally I find graphs.py is [capturing all fwd graphs and then reverse capture all bwd graphs](https://github.com/pytorch/pytorch/blob/master/torch/cuda/graphs.py#L287-L308), we can improve this as capturing every fwd/bwd graph when we are using checkpoint? In this way after captured single fwd/bwd graph, their activations can be release to mempool.

**Comment by Jack47** [comment]
I resovled this according to the last replay. But finally we don't use cuda graph because it's grains is minor when using large batch size which have gpu kernel execution time larger than kernel cpu launch time.

**Comment by CharlesRiggins** [comment]
It was a great discussion though.
