### ISSUE TITLE
torch.onnx not support stft

### ISSUE THREAD

**Issue by fulelan** [pytorch/pytorch#83498]
### 🚀 The feature, motivation and pitch

When I export the voiceprint recognition model to onnx format,  I got this:

`RuntimeError: Exporting the operator stft to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.`

code:

```
classifier = EncoderClassifier.from_hparams(source="best_model/", hparams_file='hparams_inference.yaml', savedir="best_model/")
audio_file = 'test_output.wav'
signal, fs = torchaudio.load(audio_file)

with torch.no_grad():
    torch.onnx.export(
        classifier,
        signal,
        "mymodel.onnx",
        opset_version=11,
        input_names=['input'],
        output_names=['output'])
```

**Comment by justinchuby** [comment]
Thanks for creating the issue. Support for stft is being tracked at #81075
