### ISSUE TITLE
Pytorch build error with `c++: error: unrecognized command-line option ‘-fcolor-diagnostics’`

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#83500]
### 🐛 Describe the bug

I was building pytorch with
```
python setup.py clean
python setup.py develop
```
as usual, but got error with `c++: error: unrecognized command-line option ‘-fcolor-diagnostics’`

### Versions

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 11.2.0
Clang version: 13.0.1
CMake version: version 3.23.20220418-g993ba4b-dirty
Libc version: glibc-2.35

I'm using GCC.

commit: 43a94daca0a141fb3d7b3cdceee3b3dc296a0aa4

Guessing https://github.com/pytorch/pytorch/pull/82883 is likely related?

cc @ezyang @gchanan @zou3519 @malfet @seemethere @ptrblck @zasdfgbnm

**Comment by malfet** [comment]
@xwang233 hmm, can you post a full cmake log? As goal of https://github.com/pytorch/pytorch/pull/82883 is to prevent those things from happening, rather than cause a new ones

**Comment by xwang233** [comment]
Hi @malfet , I think it's probably my ccache setup issue that it caches flag test from old compiler? I posted two logs here

with ccache
https://gist.github.com/xwang233/b4a4d499bacb227141e34bb102034b48

without ccache
https://gist.github.com/xwang233/81127ffa28036d4fd669709489808124

**Comment by albanD** [comment]
raising priority as more people are hitting it.

**Comment by dagitses** [comment]
This happens to me on CentOS 9.

**Comment by malfet** [comment]
As many people have a repro, let's try to figure out what is going on. Leaving as high-pri.

**Comment by dagitses** [comment]
[-fcolor-diagnostics.txt](https://github.com/pytorch/pytorch/files/11192542/-fcolor-diagnostics.txt)
[CMakeFiles.tar.gz](https://github.com/pytorch/pytorch/files/11192574/CMakeFiles.tar.gz)

**Comment by malfet** [comment]
Culprit seems to be ccache, see https://github.com/ccache/ccache/issues/740

**Comment by dagitses** [comment]
I also can confirm that everything works with my setup if I uninstall ccache.

**Comment by albanD** [comment]
Should we update our CMake to assume this option is not available if the user has an old ccache install>

**Comment by malfet** [comment]
> This happens to me on CentOS 9.

@dagitses how did you build/configured ccache on CentOS9 as it does not come preinstalled with it.

But even though I can repro the problem as described in the issue, I can not reproduce the failure even if I manually build a broken version of ccache-4.0, but I guess just adding a check there for compiler type is a safe thing to do

**Comment by malfet** [comment]
I can reproduce the issue on the same image as @dagitses, but I can not reduce it to a simpler test, i.e. on the same machine following CMakeLists.txt 
```cmake
cmake_minimum_required(VERSION 3.15)
find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
  set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PROGRAM}" CACHE STRING "C compiler launcher")
  set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}" CACHE STRING "CXX compiler launcher")
endif()
enable_language(CXX)
include(CheckCXXCompilerFlag)
project(Testing)
check_cxx_compiler_flag(-Werror HAS_WERROR)
check_cxx_compiler_flag(-fcolor-diagnostics HAS_FCOLOR_DIAGNOSTICS)
add_executable(hello hello.cpp)
```
fails as expected, so need to do a bit more digging (or may be just add compiler specific checks there)

**Comment by malfet** [comment]
Ok. I finally have a reproducer and understanding what is going on (as old issue has been fixed a while back):
```shell
docker run --rm -it ubuntu:22.04 bash -xc "apt update; apt install -y g++ ccache; ln -f /usr/bin/x86_64-linux-gnu-g++-11 /usr/bin/c++; ln -sf /usr/bin/ccache /usr/local/bin/c++; echo 'int main() { return 0; }' >src.cxx; /usr/local/bin/c++ -c src.cxx; /usr/local/bin/c++ -fcolor-diagnostics -c src.cxx"
```

**Comment by albanD** [comment]
Ho?
