### ISSUE TITLE
Provide common set of smoke tests for torch cpu, torch gpu, torchvision, torchaudio

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#83519]
Libtorch test workflow:
https://github.com/pytorch/pytorch/runs/7895164013?check_suite_focus=true
running binary_linux_test.sh and check_binary.sh

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by vadimkantorov** [comment]
Related on testing instructions (closed for some reason, maybe regression): https://github.com/pytorch/pytorch/issues/62590

https://github.com/pytorch/pytorch/issues/83507

https://github.com/pytorch/vision/issues/4260 https://github.com/pytorch/vision/issues/4665

**Comment by malfet** [comment]
Can we please have some sort of verbal definition of what smoke tests mean.
For example:
 -  PyTorch smoke tests validate that:
    -   torch module can be imported
    -  3x3 convolution works on available devices (CPU/GPU/MPS)
- TorchVision smoke tests validate that:
  - torchvision module can be imported
  - torchvision can be used to decode jpeg and png image
  - resnet50 can classify image of a cat as a cat
....

**Comment by vadimkantorov** [comment]
for torchvision there's also an imported thing: being able to decode a video (but it's contingent on general video i/o problems in torchvision) using ffmpeg

**Comment by vadimkantorov** [comment]
another recent issue about ffmpeg: https://github.com/pytorch/pytorch/issues/83977
