### ISSUE TITLE
Strange legacy constructor parsing behavior

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#8351]
In [9]: torch.LongTensor((5, 6), 1)
Out[9]: tensor([ 5,  6])

I'm not sure what this is supposed to be, but I don't think it should just ignore that argument.

**Comment by li-roy** [comment]
It's interpreting that argument as device, which is ignored because it's a cpu constructor. We also ignore cpu on the cuda constructors and just put it on device 0. Should we throw error instead?
```
>>> torch.cuda.LongTensor((5, 6), device="cpu")
tensor([5, 6], device='cuda:0')
>>> torch.cuda.LongTensor((5, 6), 1)
tensor([5, 6], device='cuda:1')
```

**Comment by gchanan** [comment]
Why does it interpret the argument as device though?  Isn't device kwarg only?
