### ISSUE TITLE
[ROCm] Bad ROCm runner(s) "worker-rocm-amd-38"

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#83539]
### 🐛 Describe the bug

Hi team,

I'm observing a bad ROCm runner `worker-rocm-amd-38` that is wreaking havoc on our CI.  All the jobs picked up by this host fail, i.e. https://github.com/pytorch/pytorch/runs/7865037015

Here are some snippet from the logs:

```
Current runner version: '2.295.0'
Runner name: 'worker-rocm-amd-38'
Runner group name: 'Default'
Machine name: 'jenkins-worker-rocm-amd-[3](https://github.com/pytorch/pytorch/runs/7865037015?check_suite_focus=true#step:1:3)8'
```

```
+ [[ linux-focal-rocm5.2-py3.7 == *rocm* ]]
+ rocminfo
ROCk module is loaded
Failed to set mem policy for GPU [0x6b0d]
hsa api call failure at: /long_pathname_so_that_rpms_can_package_the_debug_info/src/rocminfo/rocminfo.cc:1140
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.

Error: Process completed with exit code 8.
```

Please help take a look.  @seemethere has helped take this runner out of the pool to mitigate the issue for now.  Also I have this PR standing by https://github.com/pytorch/pytorch/pull/83534 if you need to temporarily disable rocm tests.

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @seemethere @malfet @pytorch/pytorch-dev-infra 

### Versions

CI issue

**Comment by huydhn** [comment]
Do we need to follow up with anything here?

**Comment by janeyx99** [comment]
Now that it's removed, I think we're okay with closing this one out?
