### ISSUE TITLE
Unable to get some head files while compiling sleef

### ISSUE THREAD

**Issue by TommeyChang** [pytorch/pytorch#8359]
## Issue description
When I install the pytorch from source code up to date, there are some errors while compiling the sleef part. The error discription are as following. I can find all of them, them I try to fix them through copy the head files to the path where  the .c files are. And I pass these errors.

/pytorch/third_party/sleef/src/libm-tester/iutsimd.c:133:26: fatal error: renamedsp256.h: No such file or directory
/pytorch/third_party/sleef/src/dft/vectortype.h:10:19: fatal error: sleef.h: No such file or directory
/pytorch/third_party/sleef/src/libm-tester/iutsimd.c:133:26: fatal error: renamedsp256.h: No such file or directory
/pytorch/third_party/sleef/src/libm-tester/iut.c:26:20: fatal error: rename.h: No such file or directory
/pytorch/third_party/sleef/src/libm-tester/iutsimd.c:56:24: fatal error: renamefma4.h: No such file or directory
/pytorch/third_party/sleef/src/libm-tester/iutsimd.c:64:24: fatal error: renameavx2.h: No such file or directory

## System Info
PyTorch version: 0.5.0a0+7924530
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424
CMake version: version 3.11.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.14.2)
[conda] Could not collect

**Comment by TommeyChang** [comment]
Another problem arrises:
pytorch/build/aten/src/ATen/Functions.h:1794:61:   required from here
/usr/include/c++/6/tuple:495:244: error: wrong number of template arguments (4, should be 2)

**Comment by soumith** [comment]
cc: @cpuhrsch

**Comment by cpuhrsch** [comment]
Hello @TommeyChang,

Is this a recent issue? Do you know the commit at which this started occurring or could you bisect it? Our CI systems include your platform and run clear, so I suspect this is related to your environment. Do you possibly have sleef already installed as part of your system?

Thanks,
Christian

**Comment by TommeyChang** [comment]
Hello @cpuhrsch,

I met the bug after I had updated all the source code with the command: git pull origin maste. And I have never installed sleef. Meanwhile, I seached sleef in my computer and got nothing. Is there another method to check it?

I think the problem is just the oppsite. You may have installed sleef, and it works fine.

Thanks,
Tommey

**Comment by cpuhrsch** [comment]
Did you update/initialize all your submodules using `git submodule update --init`? It might also help to run 'python setup.py clean' and then try installing it again.
