### ISSUE TITLE
Exploding RAM with simple code

### ISSUE THREAD

**Issue by cosmo-sterin** [pytorch/pytorch#836]
Hi all,
Please find attach a very simple code that just stocks VGG outputs:
http://pastebin.com/TSTubqrj
It requires over 4 GB of RAM on my laptop **after** the model is loaded (in the loop)
It seems really weird to me, do you think it could be a pytorch bug ?

**Comment by soumith** [comment]
you are holding on to intermediate states of the vgg graph over each forward. if you want to get the output of vgg and store it, you need to do:


import torch
import torch.nn as nn
import torchvision.models as models
from torch.autograd import Variable

vgg19 = models.vgg19(pretrained=True)

l = []
for i in range(10):
l.append(vgg19(Variable(torch.randn([1,3,224,224]))).data)

**Comment by cosmo-sterin** [comment]
Thank you very much for your answer

**Comment by apaszke** [comment]
Or better, it's inference mode only so you should run with volatile=True Varisblr flag. This will be faster and will consume less memory. Also, if your images are of the same size you might want to consider using torch.backends.cudnn.benchmark = True
