### ISSUE TITLE
`state_dict()` pre-hook

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#83613]
### 🚀 The feature, motivation and pitch

For FSDP, we want to run some unsharding logic before `state_dict()` runs for each module. With the existing FSDP design, `FullyShardedDataParallel` is a nested module wrapper, so we can override `FullyShardedDataParallel.state_dict()` to run the unsharding logic before calling `super().state_dict()`. However, in our effort to support `FullyShardedDataParallel` as a top-level-only wrapper, we want a `state_dict()` pre-hook to register on the original modules. This hook can run right before `self. _save_to_state_dict()`:
https://github.com/pytorch/pytorch/blob/bd0ad7a84f125435f9e0685f86b1ca2efd2bd43b/torch/nn/modules/module.py#L1436

### Alternatives

FSDP currently supports 3 model state dict options: full, local, and sharded. The precise differences are irrelevant. The idea to note is that[ sharded state dict](https://github.com/pytorch/pytorch/blob/1f99bdfcc4a3f97d28471a531d2b69def762f6ba/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1977) employs a "trick": It lets `super().state_dict()` run normally without any preceding logic. Then, in the `state_dict()` [post-hook](https://github.com/pytorch/pytorch/blob/bd0ad7a84f125435f9e0685f86b1ca2efd2bd43b/torch/nn/modules/module.py#L1321), it runs the unsharding logic, saves the real entries to the state dict, and deletes the (sharded) entry populated by `super().state_dict()`. In that sense, it is only really using `super().state_dict()` for the `prefix` logic.

If FSDP a top-level-only wrapper, we follow a similar approach, only moving the `state_dict()` post-hook to the original modules. However, deleting the actual entries populated by `state_dict()` seems error prone. It may not compose well with other hooks.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by awgu** [comment]
Oops. It looks like this may be duplicated with https://github.com/pytorch/pytorch/issues/75287

**Comment by albanD** [comment]
Yep. Closing as duplicate. Feel free to add anything missing to the other issue.
