### ISSUE TITLE
PyTorch can't build LongTensor from Numpy Long tensor

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#8365]
This code is not working with PyTorch 0.4, and I'm pretty sure it was working with PyTorch 0.3.

```python
import numpy as np
import torch
torch.LongTensor([x for x in np.array([2, 3])])
```

Now, it raises this error:
```RuntimeError: tried to construct a tensor from a int sequence, but found an item of type numpy.int64 at index (0)``` and this is quite inconvenient.

**Comment by fmassa** [comment]
I think a better way of doing this is the following (only works on master, as `as_tensor` was added after 0.4)
```python
torch.as_tensor(np.array([2, 3]))
```

**Comment by SsnL** [comment]
for `from_numpy`

**Comment by glample** [comment]
Problem with these methods is that you have to specify the type of the tensor, while using `torch.LongTensor` is convenient and directly give a `torch.LongTensor`. I would say casting a np.int64 array to a torch.LongTensor tensor should not be giving an error.
I understand that converting a np.int64 or a np.float32 to a torch.IntTensor might result in errors / imprecisions and could raise an error, but converting a np.int32 or an np.64 to a torch.LongTensor should not IMO.

**Comment by glample** [comment]
Also, `from_numpy` takes as input a Numpy array so it does not work here:

```python
torch.from_numpy([x for x in np.array([2, 3])])
TypeError: expected np.ndarray (got list)
```

**Comment by fmassa** [comment]
About your point that we need to specify the type of the tensor, we actually have type inference now, so that if you pass
```python
a = torch.tensor([1, 2])  # long tensor
b = torch.tensor([1.])  # float tensor
c = torch.tensor([True])  # byte tensor
```
which is very handy.

But it seems that we are missing support for numpy integer types:
```python
a = torch.tensor(np.float64(1))  # works
b = torch.tensor(np.int64(1))  # fails
```

**Comment by fmassa** [comment]
I thought the idea was to deprecate `from_numpy` in favour of `as_tensor`?
Also, I believe we have a bug that would be good to be fixed for numpy integers

**Comment by weiyangfb** [comment]
I have a naive question: since we have `torch.tensor()` that does the same thing as `torch.LongTensor()`,  why do we need `torch.LongTensor()`? Or why not just make `torch.LongTensor()`a wrapper of `torch.tensor()`?

**Comment by fmassa** [comment]
We need `torch.LongTensor` for backwards compatibility, but also note that there are a few differences between both constructors. Indeed, `torch.LongTensor` has the behaviour of `torch.tensor` and `torch.empty`, but doesn't support creating scalars

**Comment by soumith** [comment]
i checked that this is now working in 0.4.1. It was either implcitly or explicitly fixed, but the issue was not closed.

**Comment by SsnL** [comment]
@spott it works for me on master build

**Comment by spott** [comment]
Ah, it isn't working on 0.4.1: which is what soumith was referencing.

I just wanted to make sure that this didn't fall through the cracks, thanks for checking.

**Comment by MinSeok-Pons-Kim** [comment]
just stopping by...

a = torch.tensor(np.float64(1))  # works
b = torch.tensor(np.int64(1))  # fails
c = torch.tensor(np.int64(1)) # works

if you have list of np.int elements, try 

d = torch.tensor(your_list) # fails
new_list = list(map(int, your_list))
e = torch.tensor(new_list) # works

which would be the ok solution up to now?

**Comment by SsnL** [comment]
@MinSeok-Pons-Kim Upgrade to v1.0 should solve all your use cases.
