### ISSUE TITLE
[Quantization][FX] Fused module not lowered if followed by size + view

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#83658]
### 🐛 Describe the bug

I am using FX to quantize models. I found that if a fused module (e.g., `LinearReLU`) is followed by `size()` + `view()`, the module cannot be correctly converted to quantized version.
Example:
```python
import torch
from torch.ao.quantization import get_default_qconfig_mapping
from torch.quantization.quantize_fx import prepare_fx, convert_fx

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.in_feature = 16
        self.oh = 4
        self.ow = 8
        self.out_feature = self.oh * self.ow
        self.linear = torch.nn.Linear(self.in_feature, self.out_feature)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        y = self.linear(x)
        y = self.relu(y)
        return y.view(y.size(0), 1, self.oh, self.ow)
        # return y.view(x.size(0), 1, self.oh, self.ow) # This gives a similar result

model_fp32 = M().eval()

qengine = 'fbgemm'
torch.backends.quantized.engine = qengine
qconfig_mapping = get_default_qconfig_mapping(qengine)
x = torch.randn((5, 16))
prepared_model = prepare_fx(model_fp32, qconfig_mapping, x)
prepared_model(x)
quantized_model = convert_fx(prepared_model)
print(quantized_model)
```
Output:
```
GraphModule(
  (linear): LinearReLU(
    (0): QuantizedLinear(Reference)(in_features=16, out_features=32, bias=True)
    (1): ReLU()
  )
)

def forward(self, x):
    linear = self.linear(x)
    linear_scale_0 = self.linear_scale_0
    linear_zero_point_0 = self.linear_zero_point_0
    quantize_per_tensor = torch.quantize_per_tensor(linear, linear_scale_0, linear_zero_point_0, torch.quint8);  linear = linear_scale_0 = linear_zero_point_0 = None
    size = x.size(0);  x = None
    view = quantize_per_tensor.view(size, 1, 4, 8);  quantize_per_tensor = size = None
    dequantize_1 = view.dequantize();  view = None
    return dequantize_1
```
It can be seen that the `LinearReLU(Reference)` module is not lowered to `QLinearReLU`.
The quantized model is supposed to be
```
GraphModule(
  (linear): QLinearReLU(in_features=16, out_features=32, bias=True)
)

def forward(self, x):
    x_scale_0 = self.x_scale_0
    x_zero_point_0 = self.x_zero_point_0
    quantize_per_tensor = torch.quantize_per_tensor(x, x_scale_0, x_zero_point_0, torch.quint8);  x = x_scale_0 = x_zero_point_0 = None
    linear = self.linear(quantize_per_tensor);  quantize_per_tensor = None
    size = linear.size(0);  x = None
    view = linear.view(size, 1, 4, 8);  linear = size = None
    dequantize_1 = view.dequantize();  view = None
    return dequantize_1
```
Similar results with convolution + relu + size + view.

### Versions

PyTorch version: 1.13.0a0+gitbd6098c
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.10

Python version: 3.7.10 (default, Feb 26 2021, 18:47:35)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-centos-7.5.1804-Core
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.12.100
[pip3] numpy==1.21.6
[pip3] pytorch-widedeep==0.3.7
[pip3] torch==1.13.0a0+gitce7177f
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] intel-extension-for-pytorch 1.12.100                 pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.1.0                 pypi_0    pypi
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl-static                2022.1.0                 pypi_0    pypi
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpy-base                1.20.1           py37h7d8b39e_0
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     1.13.0a0+gitce7177f          pypi_0    pypi
[conda] torchaudio                0.12.0a0+eb23a24          pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @ezyang @SherlockNoMad

**Comment by Xia-Weiwen** [comment]
Hi @vkuzo May I know how it is going now please? Looks like PR https://github.com/pytorch/pytorch/pull/83784 is not updated for a while.

**Comment by vkuzo** [comment]
hi @Xia-Weiwen , unfortunately I'm not sure when I will be able to finish the PR due to time constraints.  Happy to help review if someone else is up for finishing it.

**Comment by Xia-Weiwen** [comment]
> hi @Xia-Weiwen , unfortunately I'm not sure when I will be able to finish the PR due to time constraints. Happy to help review if someone else is up for finishing it.

@vkuzo  I see. Thanks. Maybe I will take a look later to see if I am able to work on it.

**Comment by Xia-Weiwen** [comment]
Hi @vkuzo I continued with your work and opened a PR here https://github.com/pytorch/pytorch/pull/90001. It's still waiting for CI checks. Please review at your convenience. Thanks!

**Comment by andrewor14** [comment]
Looks like the fix has landed. I'm closing this.
