### ISSUE TITLE
error: redefinition of ‘struct THSByteTensor

### ISSUE THREAD

**Issue by NewEricWang** [pytorch/pytorch#8368]
Hi, When I compile source code, I get a error "/restools/tools/anaconda2/include/THS/THSTensor.h:7:40: error: redefinition of ‘struct THSByteTensor’" . The compiling command I used is "sudo python setup.py install ".  How should I resolve it?

**Comment by ezyang** [comment]
Can you try rebuilding in a clean Anaconda environment; also, don't use root to build.

**Comment by NewEricWang** [comment]
Hi, @ezyang , thank you for your replay!  I don't know what is the clean Anaconda environment?

**Comment by NewEricWang** [comment]
Hi, @ezyang, how can I do to not use root to build? I found the build directory is made by root by default.

**Comment by NewEricWang** [comment]
By the way, the error is reported when compiling ATen.

**Comment by ezyang** [comment]
Reinstall anaconda from scratch in a different folder, and set your PATH to use the binaries there.

If the build directory is root, that means you accidentally ran the build as root before which left some files chowned as root. The easiest way to fix it is to make a new build directory as non-root, and NEVER run build commands as root.
