### ISSUE TITLE
How to use accessors for fast elementwise write?

### ISSUE THREAD

**Issue by SM1991CODES** [pytorch/pytorch#83685]
### 📚 The doc issue

![image](https://user-images.githubusercontent.com/69435296/185450482-d4c8a081-68c2-4b59-9b38-3f3e7b191ad7.png)

As seen above from Libtorch documentation, accessors can be used for fast element wise read operations on Libtorch tensors.
However, is there a similar functionality for write operations as well?

The use case is when preparing a data frame, we could directly use a CPU tensor, write into it and then just copy it to CUDA.
Presently I make a normal array, copy array to CPU tensor using from_blob() and then transfer it to CUDA.

Best Regards
Sambit

**Comment by ngimel** [comment]
Please ask questions on dicsuss.pytorch.org
