### ISSUE TITLE
torch.full is broken on MPS for uint8

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#83692]
### 🐛 Describe the bug

It can not be used to initialize tensor with values greater than 127, i.e.:
```
% python -c "import torch;print(torch.full((2, 2), 247, device='mps', dtype=torch.uint8))"
tensor([[0, 0],
        [0, 0]], device='mps:0', dtype=torch.uint8)
```

But the same works for values smaller than 128:
```
% python -c "import torch;print(torch.full((2, 2), 127, device='mps', dtype=torch.uint8))"
tensor([[127, 127],
        [127, 127]], device='mps:0', dtype=torch.uint8)
```

Seems related to https://github.com/pytorch/pytorch/issues/82427

### Versions

1.12.1, nightly

cc @kulinseth @albanD

**Comment by kulinseth** [comment]
@malfet , I think this can be closed. Thanks for the fix.

**Comment by malfet** [comment]
@kulinseth the workaround for this problem is pretty ugly, and it fails in Ventura preview as well. Wouldn't it be better to keep it open until problem in the framework is fixed in the stable MacOS?

**Comment by kulinseth** [comment]
@malfet agreed.

**Comment by kulinseth** [comment]
This has been fixed in Stable release of Ventura:
```
ProductName:            macOS
ProductVersion:         13.2.1
```

```
(torch-nightly) local@mps ~ %  python -c "import torch;print(torch.full((2, 2), 127, device='mps', dtype=torch.uint8))"
tensor([[127, 127],
        [127, 127]], device='mps:0', dtype=torch.uint8)
(torch-nightly) local@mps ~ % python -c "import torch;print(torch.full((2, 2), 247, device='mps', dtype=torch.uint8))"
tensor([[247, 247],
        [247, 247]], device='mps:0', dtype=torch.uint8)
