### ISSUE TITLE
distributed tests take a long time

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#83694]
`pull / linux-bionic-cuda11.6-py3.10-gcc7 / test (distributed, 1, 2, linux.8xlarge.nvidia.gpu)` and `
trunk / linux-bionic-cuda10.2-py3.9-gcc7 / test (distributed, 1, 2, linux.8xlarge.nvidia.gpu)` are our two longest jobs on pull and trunk, respectively, each with a p90 of over 3 hours.  

We are unable to shard these jobs further because `distributed/test_distributed_spawn` is responsible for about half the test time.

Is there anyway we could either break up this file into smaller files that could be put on different shards or make these tests faster?

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by wanchaol** [comment]
hmmm @clee2000 any particular reason the `distributed/test_distributed_spawn` can't be shard? I thought they are eventually breaking down to test cases, so things like pytests could scan them out and shard them properly?

**Comment by clee2000** [comment]
our sharding is based on the test file granularity, but i could manually shard the distributed tests if you think splitting up the file is a bad idea

**Comment by huydhn** [comment]
From what I see in the log, `distributed/test_distributed_spawn` is currently run sequentially with different backends and initialization methods (env or file).  Specifically, this loop in [test_distributed](https://github.com/pytorch/pytorch/blob/master/test/run_test.py#L494-L495) is where I think we can run in parallel instead of running nccl/env -> nccl/file -> gloo/env -> gloo/file sequentially:

```
# The test backend doesn't do anything,
2022-08-21T15:38:27.4831720Z Running distributed tests for the test backend with env init_method
2022-08-21T15:38:29.5878765Z Running distributed tests for the test backend with file init_method
...
2022-08-21T15:38:31.6558267Z Running distributed tests for the nccl backend with env init_method
2022-08-21T16:01:52.0977091Z Running distributed tests for the nccl backend with file init_method
2022-08-21T16:25:10.9695303Z Running distributed tests for the gloo backend with env init_method
2022-08-21T16:51:51.0781122Z Running distributed tests for the gloo backend with file init_method
```

So my question is:

* Is this possible to run these 4 combinations on the same runner or should they be split up into different shards? One way or another, I think we can cut down the test time significantly here because each combination only takes 1/4 of the total time

**Comment by wanchaol** [comment]
> Is this possible to run these 4 combinations on the same runner or should they be split up into different shards? One way or another, I think we can cut down the test time significantly here because each combination only takes 1/4 of the total time

Yeah I think it's actually possible to separately run these 4 combinations in different shards, as these 4 combinations are stand alone with each other and could be run separately. If this helps reducing with the test time, we should do it definitely :)

**Comment by wanchaol** [comment]
> our sharding is based on the test file granularity, but i could manually shard the distributed tests if you think splitting up the file is a bad idea

@clee2000 I see, is there any reason we didn't choose to use pytest-shard directly, I recalled that's test case name hash based sharding, so it would automatically shard a big file tests.

**Comment by huydhn** [comment]
@wanchaol I have this PR https://github.com/pytorch/pytorch/pull/84034 trying to take a stab to run different backends in parallel

**Comment by huydhn** [comment]
This is probably not relevant anymore, distributed tests take about 2+h to finish like others
