### ISSUE TITLE
function torch.linalg.solve gets a different result from 'cpu' when using the 'cuda' calculation

### ISSUE THREAD

**Issue by xuanyabulema** [pytorch/pytorch#83730]
### Bug
When using 'cpu', the function torch.linalg.solve gives the same result as the function np.linalg.solve, but when using 'cuda', the two results are different.
### To Reproduce
```
import numpy as np
import torch

A = torch.randn(50, 50).cuda()
B = torch.randn(50, 2).cuda()
X = torch.linalg.solve(A, B)

A_cpu = A.cpu()
B_cpu = B.cpu()
X_cpu = torch.linalg.solve(A_cpu, B_cpu)
A_numpy = A_cpu.numpy()
B_numpy = B_cpu.numpy()
X_numpy = np.linalg.solve(A_numpy, B_numpy)

print((X.cpu() - X_cpu).sum())
print((X_cpu.numpy() - X_numpy).sum())
print((X.cpu() - X_cpu).sum() == 0)
print((X_cpu.numpy() - X_numpy).sum() == 0)
```
### Output
```
tensor(9.8203e-15)
0.0
tensor(False)
True
```
### Expected behavior
It should give the same result

###  environment information
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 516.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.6.0              hc0ea762_10    conda-forge
[conda] mkl                       2021.4.0           haa95532_640    defaults
[conda] mkl-service               2.4.0            py39h2bbff1b_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.3.1            py39h277e83a_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.2.2            py39hf11a4ad_0    https://repo.anaconda.com/pkgs/main
[conda] numpy                     1.21.5           py39h7a0a035_1    https://repo.anaconda.com/pkgs/main
[conda] numpy-base                1.21.5           py39hca35cd5_1    https://repo.anaconda.com/pkgs/main
[conda] numpydoc                  1.2                pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
[conda] pytorch                   1.12.1          py3.9_cuda11.6_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.1               py39_cu116    pytorch
[conda] torchvision               0.13.1               py39_cu116    pytorch

cc @ngimel @mruberry @rgommers @jianyuh @nikitaved @pearu @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nikitaved** [comment]
@xuanyabulema , both PyTorch and Numpy use the same Lapack routine, so it is expected that the results are same on the CPU.
However, your input is not guaranteed to be well-conditioned for solving the system of linear equations,
```python
In [1]: import torch

In [2]: a = torch.randn(5000, 50, 50)

In [3]: a_inv = torch.linalg.inv(a)

In [4]: cond_n = a.svd().S[..., 0] * a_inv.svd().S[..., 0]

In [5]: cond_n.mean()
Out[5]: tensor(1363.0404)

In [6]: cond_n.std()
Out[6]: tensor(40296.1367)

In [7]: cond_n.min()
Out[7]: tensor(30.6294)

In [8]: cond_n.max()
Out[8]: tensor(2815969.)

```
Hence different outcomes due differences in implementations and instability.

**Comment by lezcano** [comment]
Closing this one, as we cannot offer the same stability guarantees on CPU and CUDA.
