### ISSUE TITLE
Bad Example in pytorch CE

### ISSUE THREAD

**Issue by BinchaoPeng** [pytorch/pytorch#83732]
### 📚 The doc issue

```python
import torch
import torch.nn as nn
# Example of target with class probabilities
loss1 = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
print(input)
print(target)
output = loss1(input, target)
print(output)
output.backward()
print(output)
```
ref:https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html
the example of 『# Example of target with class probabilities』does not work and throws exception:
```bash
RuntimeError: 1D target tensor expected, multi-target not supported
```

### Suggest a potential alternative/fix

```python
import torch
import torch.nn as nn
# Example of target with class probabilities
loss1 = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
target = torch.argmax(target, dim=1)  # Might need it! 
print(input)
print(target)
output = loss1(input, target)
print(output)
output.backward()
print(output)
```

**Comment by mikaylagawarecki** [comment]
Thanks for the report! Could I confirm what version of pytorch you are using? Closing as this error seems that this is fixed on master. Upgrading to 1.12 should resolve the error, feel free to re-open this issue otherwise! :)

**Comment by BinchaoPeng** [comment]
> Thanks for the report! Could I confirm what version of pytorch you are using? Closing as this error seems to be fixed on master. Upgrading to 1.12 should resolve the error, feel free to re-open this issue otherwise! :)

It's right, thanks!
