### ISSUE TITLE
Flaky tests may be due to limited shared memory

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#83776]
As of August 18, 2022, pytorch/pytorch had 240 flaky tests in its system, the majority of them owned by the distributed, multiprocessing, and dataloader teams. @NivekT suggested that the dataloader tests are likely flaky due to lack of shared memory, and thus inspired the following action items we can take:

1. Track shared memory usage with `free` on Linux. Whenever a test case fails, we can print the amount of used + free memory at that moment. We may also want to check before the test + after the failure.
2. Use free before every test to see if we have enough memory at the start of the test. If not, we should skip the test with a message.

**We should:** proceed with 1 to verify that lack of shared memory is the culprit, and if so, then do 2. 

Tagging @ejguan and @VitalyFedyunin or @vitaly-fedyunin for more suggestions + confirmation that this is a reasonable next step.

cc @VitalyFedyunin @SsnL @ejguan @NivekT @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
Also tagging @rohan-varma for any thoughts from the distributed side

**Comment by huydhn** [comment]
For step 1, we might have that information already using [tools.stats.monitor](https://github.com/pytorch/pytorch/blob/master/.github/workflows/_linux-test.yml#L72).  It includes the memory used by the test process (USS and RSS memory). They are uploaded as tests artifacts to S3. CC @clee2000

**Comment by ejguan** [comment]
> For step 1, we might have that information already using [tools.stats.monitor](https://github.com/pytorch/pytorch/blob/master/.github/workflows/_linux-test.yml#L72). It includes the memory used by the test process (USS and RSS memory). They are uploaded as tests artifacts to S3. CC @clee2000

The main blocker I have encountered to figure out the culprit for running out of shared memory is:
The failed tests normally are not the ones fail to clean up the shared memory. Some test cases occupy the shared memory without releasing it and eventually cause the other tests running out of shared memory.

If this tool is able to provide real-time usage of the test, we would be able to locate which test case not clean up the shared memory sucessfully.

**Comment by ZainRizvi** [comment]
Action: Find an actual flaky test and measure how much shared memory is actually available when a test fails, or get realtime usage of memory
- We don't know if memory is _actually_ the problem.

Potential final solution: ensure test don't use up too much memory or don't ignore memory cleanup afterwards
