### ISSUE TITLE
torch.where produces confusing error messages on cpu/cuda mismatches

### ISSUE THREAD

**Issue by cle-ros** [pytorch/pytorch#8378]
## Issue description

The error messages for `torch.where` are mildly confusing when there are cuda/cpu mismatches, as many state "expect CPU but got CPU" or "expected CUDA but got CUDA".

## Code example

```python
import torch
decider = torch.randint(0, 2, size=(20, 2)).byte()
first_opt = torch.randn(size=(20, 2))
second_opt = torch.randn(size=(20, 2))
result = torch.where(decider, first_opt, second_opt)  # works, of course

result = torch.where(decider.cuda(), first_opt, second_opt)  
# RuntimeError: Expected tensor to have CUDA Backend, but got tensor with CUDA Backend (while checking arguments for CPU_tensor_apply4)
result = torch.where(decider, first_opt.cuda(), second_opt)  
# RuntimeError: Expected tensor to have CPU Backend, but got tensor with CPU Backend (while checking arguments for CUDA_tensor_apply4)
result = torch.where(decider, first_opt, second_opt.cuda())  
# RuntimeError: Expected tensor to have CUDA Backend, but got tensor with CUDA Backend (while checking arguments for CPU_tensor_apply4)
```
## System Info
Pytorch installed vida conda:
`pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch`

**Comment by vishwakftw** [comment]
The errors are not being reproduced with the code that you have given. Are you missing some `to('cuda')` calls?

**Comment by cle-ros** [comment]
Hey Vishwak! Yes, I did. Thanks for catching that.

**Comment by vishwakftw** [comment]
On `master`, these are the errors:

```RuntimeError: Expected tensor to have CPU Backend, but got tensor with CUDA Backend (while checking arguments for CPU_tensor_apply)```

```RuntimeError: Expected tensor to have CUDA Backend, but got tensor with CPU Backend (while checking arguments for CUDA_tensor_apply4)```

```RuntimeError: Expected tensor to have CPU Backend, but got tensor with CUDA Backend (while checking arguments for CPU_tensor_apply)```

**Comment by zou3519** [comment]
I remember that this was fixed on master. Thanks for the report @cle-ros, and thank you for verifying @vishwakftw
