### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Zernez** [pytorch/pytorch#83795]
### 🐛 Describe the bug

Hello, after "python setup.py install" the script shows this error and the installation fails:

fatal error: error in backend: Cannot select: intrinsic %llvm.amdgcn.ds.bpermute
clang-14: error: clang frontend command failed with exit code 70 (use -v to see invocation)
AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.2.3 22324 d6c88e5a78066d5d7a1e8db6c5e3e9884c6ad10e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hip/../llvm/bin
clang-14: note: diagnostic msg: Error generating preprocessed source(s).
CMake Error at torch_hip_generated_cub-RadixSortPairs.hip.o.cmake:200 (message):
  Error generating file
  /home/ferna/pytorch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/hip/./torch_hip_generated_cub-RadixSortPairs.hip.o

Something is missing? Thanks

### Versions

roc-5.2.3
python 3.9

cc @malfet @seemethere @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by malfet** [comment]
Looks like ROCm compiler crash to me...

**Comment by amdfaa** [comment]
This is Faa Diallo from the ROCm team. Can you provide the output from the following script for info about the environment: https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py

Also have you tried using the ROCm release containers?
For 5.2.3, this page might be helpful:
https://docs.amd.com/bundle/ROCm-Release-Notes-v5.2.3/page/ROCm_v5.2.3_Release_Notes.html

**Comment by Zernez** [comment]
Thanks for reply to me. I run the script:

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A
OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.19.6
Libc version: glibc-2.31
Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A
Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0

**Comment by amdfaa** [comment]
Can you try the following before the running the setup script:

python tools/amd_build/build_amd.py
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
I'd advise you to use the 5.2.3 release container mentioned in my above comment.
Let me know if that works!

**Comment by Zernez** [comment]
Is not working again... Thanks anyways

**Comment by hongxiayang** [comment]
Please check the latest documentations about supported GPUs: https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html

**Comment by hongxiayang** [comment]
Closing this issue
