### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'python_exit_status'

### ISSUE THREAD

**Issue by Stevew7777** [pytorch/pytorch#83791]
Hi, I had this error below running in Windows 10 as local admin user ( yeah I know..... also own a nix laptop, just using windows for this project .) :

![error](https://user-images.githubusercontent.com/67404132/185727913-5f6fa66f-d3d6-4ddb-9064-2e1a078b11c6.jpg)

![software](https://user-images.githubusercontent.com/67404132/185728035-813e6eb5-db76-4ab7-8bb4-183d841f98c2.JPG)
So i upgraded to torch 1.12.1, re-ran it and had the exact same problem.
Did a git pull for yolov5 before the run.

Training command used :

python train.py --img 64 --batch 4 --epochs 5 --data dataset.yaml --weights yolov5s.pt

Is there any way we switch off what ever is causing the error behaviour, without impacting the normal operation please?

The other issue is that when the training runs ( assuming its completing the training without issues - how do I tell? ) is that when I look in the exp directory, I get an output that looks like this , which am not sure if its reflecting the other issue or its something else

![Capture2](https://user-images.githubusercontent.com/67404132/185727931-aa65e188-5d14-4ec3-8064-688731550992.JPG)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ptrblck** [comment]
Your screenshot shows:
```
Exception ignored in: ...
```
and points to the `DataLoader`, which might be eventually causing the `NoneType` error.
Did you add code to catch and ignore exceptions or do you know which exception is ignored, as it might make sense to check this error first and try to fix it.

**Comment by Stevew7777** [comment]
Hi, if I set the workers to 0, would that kill that error do you think? I'm not sure how I would catch the errors, any suggestions would be welcome.

**Comment by ptrblck** [comment]
Setting `num_workers=0` could be a wrokaround if the error is raised by the `DataLoader` if multiprocessing is used.
However, note that it's not a fix and could slow down your code.

**Comment by ejguan** [comment]
@Stevew7777 

Could you provide minimum repro for us to see what's going on? It seems `utils` has been cleared by Python before `__del__` at https://github.com/pytorch/pytorch/blob/71d50f4f8955cde773e30b207bfeb98616206823/torch/utils/data/dataloader.py#L1433

I can send a fix.

**Comment by ejguan** [comment]
Based on [Python official doc](https://docs.python.org/3/reference/datamodel.html#object.__del__):

> [`__del__()`](https://docs.python.org/3/reference/datamodel.html#object.__del__) can be executed during interpreter shutdown. As a consequence, the global variables it needs to access (including other modules) may already have been deleted or set to None. Python guarantees that globals whose name begins with a single underscore are deleted from their module before other globals are deleted; if no other references to such globals exist, this may help in assuring that imported modules are still available at the time when the [`__del__()`](https://docs.python.org/3/reference/datamodel.html#object.__del__) method is called.
