### ISSUE TITLE
[ONNX] RuntimeError: Unsupported prim::Constant kind: `ival`

### ISSUE THREAD

**Issue by HolyWu** [pytorch/pytorch#83801]
### 🐛 Describe the bug

I got this error when exporting the module to onnx with `torch.jit.script`.

```python
from typing import Dict

import torch


class MyModule(torch.nn.Module):
    tenGrid: Dict[str, torch.Tensor]

    def __init__(self):
        super(MyModule, self).__init__()
        self.tenGrid = {}

    def forward(self, x):
        k = str(x.size())
        if k not in self.tenGrid:
            self.tenGrid[k] = torch.cat((x, x), dim=1)
        return self.tenGrid[k]


torch.onnx.export(torch.jit.script(MyModule()), torch.randn(1, 2), 'test.onnx')
```

```
Traceback (most recent call last):
  File "C:\Users\Holy\Downloads\test.py", line 20, in <module>
    torch.onnx.export(torch.jit.script(MyModule()), torch.randn(1, 2), 'test.onnx')
  File "C:\Python310\lib\site-packages\torch\onnx\__init__.py", line 350, in export
    return utils.export(
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 163, in export
    _export(
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Python310\lib\site-packages\torch\onnx\__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "C:\Python310\lib\site-packages\torch\onnx\utils.py", line 1401, in _run_symbolic_function
    return symbolic_fn(ctx, g, *inputs, **attrs)
  File "C:\Python310\lib\site-packages\torch\onnx\symbolic_opset9.py", line 5186, in Constant
    raise RuntimeError(
RuntimeError: Unsupported prim::Constant kind: `ival`. Send a bug report.
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 工作站專業版
GCC version: Could not collect
Clang version: 14.0.6
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050
Nvidia driver version: 516.94
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] torch==1.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] Could not collect

cc @ezyang @mruberry @ngimel

**Comment by AllenTiTaiWang** [comment]
Hi,

Unfortunately, dictionary is not supported currently. But I think it's in the future plan.
@shubhambhokare1 if there is anything you would like to add?

**Comment by justinchuby** [comment]
```
SymbolicValueError: Unsupported prim::Constant kind: `ival`. Please send a bug report at https://github.com/pytorch/pytorch/issues.  [Caused by the value '14 defined in (%14 : Dict(str, Tensor) = prim::Constant[value=annotate(Dict[str, Tensor],{})]()
)' (type 'Dict[str, Tensor]') in the TorchScript graph. The containing node has kind 'prim::Constant'.] 

    Inputs:
        Empty
    Outputs:
        #0: 14 defined in (%14 : Dict(str, Tensor) = prim::Constant[value=annotate(Dict[str, Tensor],{})]()
    )  (type 'Dict[str, Tensor]')
```

for error context

**Comment by justinchuby** [comment]
Stateful models are usually hard because the onnx graph is static. Is there a way for you to express your model without a changing dictionary?

**Comment by HolyWu** [comment]
Okay. Thanks for investigation.

**Comment by BowenBao** [comment]
Closing since there is no plan for support.
