### ISSUE TITLE
Leaky ReLU - "negative slope" naming issue

### ISSUE THREAD

**Issue by d-kleine** [pytorch/pytorch#83821]
### 📚 The doc issue

[PyTorch Leaky ReLU documentation](https://pytorch.org/docs/stable/generated/torch.nn.LeakyReLU.html#torch.nn.LeakyReLU)

As the author in [this](https://stackoverflow.com/questions/68867228/where-is-the-negative-slope-in-a-leakyrelu) post critizises, the naming "negative slope" for the parameter in Leaky ReLU is somewhat confusing as it is not a "negative" slope (in the narrow sense, see [here](https://image.shutterstock.com/image-vector/types-slope-negative-600w-1884989446.jpg)) but refers to the negative part (quadrant III in a [cartesian coordinate system](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Cartesian_coordinates_2D.svg/450px-Cartesian_coordinates_2D.svg.png) of the slope of the input activated by the Leaky ReLU function. 

For comparison, in TensorFlow/Keras the parameter is called alpha:
> alpha | Float >= 0. Negative slope coefficient. Default to 0.3.

[TensorFlow Leaky ReLU documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/LeakyReLU#args)

### Suggest a potential alternative/fix

* Adaption from TF: `alpha`
* Update documentation with more precise information, that `alpha` refers to the negative part (quadrant III in a cartesian coordinate system) of the slope

cc @svekars @holly1238 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by albanD** [comment]
Changing the name would be quite challenging I'm afraid due to BC reasons.
But we can update the doc to make it clearer for sure,
