### ISSUE TITLE
Get the conjugate result when use torch.exp to calculate a complex tensor.

### ISSUE THREAD

**Issue by michael080808** [pytorch/pytorch#83839]
### 🐛 Describe the bug

- In the code, the "**Holo.png**" is the following image.
  ![Holo](https://user-images.githubusercontent.com/17961659/185939118-47500f96-f574-49aa-9941-6ee76e142724.png)

When I directly use the torch.exp() function in the following source code, I get nothing in the "**Reconstruct.png**".
```python
from math import pi

import torch
from torch.fft import fft2, ifft2, fftshift
from skimage import io

# Pixel Pitch
δ = (8.0e-6, 8.0e-6)

# Wavelength
λ = 515e-9

# Distance
dist = 0.1

# Image
image = 'Holo.png'

# Main
if __name__ == '__main__':
        
    # Read Image
    target = io.imread(image, as_gray=True)

    # Image To 3D
    target = target / 255.0
    
    # Image To Tensor
    target = torch.tensor(target, dtype=torch.double, device='cuda:0')
    
    # Phase
    target = torch.ones_like(target) * torch.exp(2j * pi * target)
    
    # Index X
    indexX = torch.tensor([[i for i in range(target.shape[-1])] for _ in range(target.shape[-2])], dtype=torch.double, device='cuda:0')
    
    # Index Y
    indexY = torch.tensor([[i for _ in range(target.shape[-1])] for i in range(target.shape[-2])], dtype=torch.double, device='cuda:0')
    
    # Coordinate X
    coordX = indexX - target.shape[-1] / 2 + 0.5
    
    # Coordinate Y
    coordY = indexY - target.shape[-2] / 2 + 0.5
    
    # Fx
    diff_X = coordX / (δ[-1] * target.shape[-1])
    
    # Fy
    diff_Y = coordY / (δ[-2] * target.shape[-2])
    
    # Phase
    phi = 2 * pi * dist / λ * torch.sqrt(1 - (λ ** 2) * (diff_X ** 2 + diff_Y ** 2))
    
    # Window
    window = torch.exp(1j * phi)
    
    # Propagation #1
    middle = fftshift( fft2(fftshift(target)))
    
    # Propagation #2
    middle = middle * window
    
    # Propagation #3
    result = fftshift(ifft2(fftshift(middle)))
    
    # Result
    result = torch.abs(result) / torch.max(torch.abs(result))
    
    # Save
    io.imsave('Reconstruct.png', (result * 255).to(torch.uint8).squeeze().detach().cpu().numpy())
```
The "Reconstruct.png":
![Reconstruct](https://user-images.githubusercontent.com/17961659/185940268-4ffa5c1f-1608-4c7c-992e-bc43a5d145b5.png)

But when I add the torch.conj() out of the torch.exp() function like this:
```python
    # Window
    window = torch.conj(torch.exp(1j * phi))
```
I can get the correct result with "Girl with a Pearl Earring".
![Reconstruct](https://user-images.githubusercontent.com/17961659/185941049-4d2f4708-1a20-4c68-89e4-85521d44eded.png)

So, it seems the torch.exp() has some problems when processing complex tensor. 
I don't understand why the conjugate result output directly.

### Versions

PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 516.94
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] pytorch-ignite==0.4.9
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0              16_win64_mkl    conda-forge
[conda] cudatoolkit               11.6.0              hc0ea762_10    conda-forge
[conda] ignite                    0.4.9                      py_0    pytorch
[conda] libblas                   3.9.0              16_win64_mkl    conda-forge
[conda] libcblas                  3.9.0              16_win64_mkl    conda-forge
[conda] liblapack                 3.9.0              16_win64_mkl    conda-forge
[conda] liblapacke                3.9.0              16_win64_mkl    conda-forge
[conda] mkl                       2022.1.0           h6a75c08_874    conda-forge
[conda] mkl-devel                 2022.1.0           h57928b3_875    conda-forge
[conda] mkl-include               2022.1.0           h6a75c08_874    conda-forge
[conda] numpy                     1.23.2           py38h223ccf5_0    conda-forge
[conda] pytorch                   1.12.1          py3.8_cuda11.6_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.1               py38_cu116    pytorch
[conda] torchtext                 0.13.1                     py38    pytorch
[conda] torchvision               0.13.1               py38_cu116    pytorch

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment]
The code above seems self-contained...

**Comment by michael080808** [comment]
> For what is worth, the forum (https://discuss.pytorch.org/) may be a better place to ask questions regarding a piece of code that doesn't do what you expect it to do.

This code is a basic optical propagation process, called as "Angular Spectrum Method".
The "Holo.png" just use the [Gerchberg–Saxton algorithm](https://en.wikipedia.org/wiki/Gerchberg%E2%80%93Saxton_algorithm) generated from matlab.
I can get the correct result when I use the same code in the matlab.
However, in pytorch, the result does not seem correct.

**Comment by michael080808** [comment]
Thanks for your suggestion! I'll check deeper and ask in forum.
