### ISSUE TITLE
Minor inconsistency in description of output tensor shape in GRU docs

### ISSUE THREAD

**Issue by theodorju** [pytorch/pytorch#83843]
### 📚 The doc issue

The documentation for [GRU](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html) describes the output tensor shape in the case of unbatched input as `L, H_in`  where `L` is the sequence length and `H_in` is the input size. 

I think the output shape should be `L, H_out`, where `H_out` is the hidden size.

### Suggest a potential alternative/fix

Replace `H_in` with `H_out`. 

cc @svekars @holly1238 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by Lezcano** [comment]
This would be a good first issue. We would accept a PR for it.

**Comment by albanD** [comment]
This is fixed in master now.
