### ISSUE TITLE
[docs] Can't find font

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#8391]
On chrome:
![image](https://user-images.githubusercontent.com/5652049/41310982-0f7be432-6e51-11e8-8b1d-a8d49f9c1d75.png)

Only happens on master docs, not on stable docs.

**Comment by vishwakftw** [comment]
It seems like a 404 error, could you try refreshing? It doesn't appear on Firefox.

**Comment by zou3519** [comment]
I should probably clear out my cache and try again...

in the meantime, @vishwakftw, does this show up for you? https://pytorch.org/docs/master/_static/fonts/Lato/lato-bold.woff (it's one of the links that is 404-ing for me)

**Comment by vishwakftw** [comment]
Directly clicking the link is a 404, but when I open the page on Firefox, there is no such error:

![image](https://user-images.githubusercontent.com/23639302/41313391-d1690f38-6e57-11e8-97aa-250caa01c0e5.png)

**Comment by vishwakftw** [comment]
The error you are referring to appears on Chrome though (Ubuntu 16.04):
![image](https://user-images.githubusercontent.com/23639302/41352403-63d717e0-6ee7-11e8-9071-907ad03ba29c.png)

**Comment by zou3519** [comment]
It's a 404 for me on firefox and safari:
(firefox)
![image](https://user-images.githubusercontent.com/5652049/41356799-9ebf0218-6ef2-11e8-91be-6edb948b7ad1.png)

at any rate something fishy is going on...

**Comment by vishwakftw** [comment]
The link is a 404. I don't think Firefox redirects to that link at all, which is why there are no such errors while browsing the page on Firefox.

**Comment by SsnL** [comment]
We are switching theme so this won't be an issue
