### ISSUE TITLE
[ONNX] Export fails when the same instance of a module appears multiple times in a module list

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8392]
Example:

```
import torch

class SomeModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(4, 4))

    def forward(self, x):
        return torch.mm(x, self.param)

class MultiModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.num_mods = 3
        self.modlist = torch.nn.ModuleList([SomeModule()] * self.num_mods)

    def forward(self, x):
        for i in range(self.num_mods):
            x = self.modlist[i](x)
        return x

mm = MultiModule()
import io
f = io.BytesIO()
torch.onnx.export(mm, (torch.rand(5, 4),), f, verbose=True)
```

Output:

```
graph(%0 : Float(5, 4)
      %1 : Float(4, 4)) {
  %2 : Dynamic = onnx::Constant[value={0}](), scope: MultiModule/SomeModule
  %3 : Float(5, 4) = onnx::Gemm[alpha=1, beta=0, broadcast=1](%0, %1, %2), scope: MultiModule/SomeModule
  %4 : Dynamic = onnx::Constant[value={0}](), scope: MultiModule/SomeModule
  %5 : Float(5, 4) = onnx::Gemm[alpha=1, beta=0, broadcast=1](%3, %1, %4), scope: MultiModule/SomeModule
  %6 : Dynamic = onnx::Constant[value={0}](), scope: MultiModule/SomeModule
  %7 : Float(5, 4) = onnx::Gemm[alpha=1, beta=0, broadcast=1](%5, %1, %6), scope: MultiModule/SomeModule
  return (%7);
}

Traceback (most recent call last):
  File "multimodule.py", line 25, in <module>
    torch.onnx.export(mm, (torch.rand(5, 4),), f, verbose=True)
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/onnx/__init__.py", line 31, in export
    return utils.export(*args, **kwargs)
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/onnx/utils.py", line 87, in export
    operator_export_type=operator_export_type)
  File "/Users/jamesreed/onnx-fairseq/pytorch/torch/onnx/utils.py", line 208, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: torch/csrc/jit/export.cpp:296: encodeBlock: Assertion `b->inputs().size() >= num_initializers` failed.
```

**Comment by daniel-j-h** [comment]
Hey @jamesr66a I'm running into the exact same issue with PyTorch 0.4.1 hitting the assertion at:

https://github.com/pytorch/pytorch/blob/v0.4.1/torch/csrc/jit/export.cpp#L296

I don't think it is strictly related to the `ModuleList` though. There is a similar report [here](https://github.com/pytorch/pytorch/issues/9587).

And in my case I'm trying to export an encoder-decoder model with skip-connections where the encoder is a pre-trained resnet50 here:
- https://github.com/mapbox/robosat/blob/f67f3a7b0875e30c971d99bfe51f92f25cd835da/robosat/unet.py#L76
- https://github.com/mapbox/robosat/blob/da30c57b13f9df9e1d0f329eff415a75c2451433/robosat/tools/export.py#L40

If it helps I initially ran into what looks like an integer overflow with PyTorch 0.4.0. The Python trace ends at https://github.com/pytorch/pytorch/blob/v0.4.0/torch/onnx/utils.py#L153-L154 and then I can only see the `std::vector` throwing an exception (probably from the `vector`'s `.at` function):

```
IndexError: vector::_M_range_check: __n (which is 18446744073709551458) >= this->size() (which is 277)
```

@jamesr66a let me know if I can provide more details to get this fixed.

---

Quick side note, the exported version is still at 0.3

https://github.com/pytorch/pytorch/blob/v0.4.1/torch/csrc/jit/export.cpp#L383-L384

**Comment by lysukhin** [comment]
using `copy.deepcopy()` over the modules seem to solve the problem:

```
from copy import deepcopy

self.enc0 = nn.Sequential(deepcopy(self.resnet.conv1), deepcopy(self.resnet.bn1), deepcopy(self.resnet.relu), deepcopy(self.resnet.maxpool))
self.enc1 = deepcopy(self.resnet.layer1)
...
```

**Comment by shbnm21** [comment]
Hey @daniel-j-h can u please tell me how did u export encoder and decoder models to onnx.
I am new to this and did not find a way to export multiple models to onnx

**Comment by eellison** [comment]
The example given in the issue works now, so I'm closing. Please re-open if this is an issue for you.
