### ISSUE TITLE
[jit][script] Can't allocate zero gradients for a value without a type

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8393]
See also https://github.com/pytorch/pytorch/issues/8410

Example:
```
import torch
@torch.jit.script
def unsqueezel(x):
    return x.unsqueeze(dim=-1)
x = torch.randn((2, 2), requires_grad=True)
unsqueezel(x)
```

output:

```
Traceback (most recent call last):
  File "dim.py", line 6, in <module>
    unsqueezel(x)
RuntimeError: torch/csrc/jit/autodiff.cpp:199: createZerosLike: can't allocate zero gradient for a value without a type
```

Operator level tests that fail with this:

- `test_add`
- `test_add_broadcast_all`
- `test_add_broadcast_lhs`
- `test_add_broadcast_rhs`
- `test_add_scalar`
- `test_add_scalar_broadcast_lhs`
- `test_add_scalar_broadcast_rhs`
- `test_sub`
- `test_sub_broadcast_all`
- `test_sub_broadcast_lhs`
- `test_sub_broadcast_rhs`
- `test_sub_scalar_broadcast_lhs`
- `test_sub_scalar_broadcast_rhs`

**Comment by goldsborough** [comment]
Shouldn't all types default to `cpu/float`?

**Comment by jamesr66a** [comment]
I made this pretty hastily cleaning up tasks. The underlying problem here is that the example specifies requires_grad but the gradient for the output in undefined. We try to create a zero gradient tensor, but we don't have the type (including shape) of the output for some reason

**Comment by jamesr66a** [comment]
@zdevito was this closed by https://github.com/pytorch/pytorch/pull/8641?
