### ISSUE TITLE
Make the mergebot block merges when there's an active Sev

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#83942]
### 🐛 Describe the bug

Today, the mergebot only blocks merges if the active sev includes certain text.  We want to default to always having a sev block merges (perhaps with optional magic text to _not_ block merges)

This is a follow up to: https://github.com/pytorch/pytorch/issues/83133

### Versions

n/a

**Comment by clee2000** [comment]
kind of resolved by https://github.com/pytorch/pytorch/pull/83940 
template has magic phrase by default and getting rid of it unblocks
