### ISSUE TITLE
Can not install on Windows

### ISSUE THREAD

**Issue by yuliiasergeeva** [pytorch/pytorch#8394]
## Issue description

I have an error in script usage when I run: 

`call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11`

The error is: 

Error in script usage. The correct usage is:
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option]
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option] store
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option] [version number]
  or
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" [option] store [version number]
where [option] is: x86 | amd64 | arm | x86_amd64 | x86_arm | amd64_x86 | amd64_arm
where [version number] is either the full Windows 10 SDK version number or "8.1" to use the windows 8.1 SDK
:
The store parameter sets environment variables to support
  store (rather than desktop) development.
:
For example:
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_arm store
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64 10.0.10240.0
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_arm store 10.0.10240.0
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 8.1
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64 store 8.1
:
Please make sure either Visual Studio or C++ Build SKU is installed.

I tried few of the examples, neither of them worked (when I run the next line, `python setup.py install` it doesn't find Visual Studio.

I'd appreciate your help on this issue!

**Comment by SsnL** [comment]
cc @peterjc123

**Comment by peterjc123** [comment]
@yuliiasergeeva It seems that you are using MSVC 2015. Would you please install VC 2017 BuildTools? A detailed post [here](https://github.com/peterjc123/pytorch-scripts/issues/23).

**Comment by yuliiasergeeva** [comment]
@peterjc123 Thanks! I installed VC 2017 components that were shown there except vc++ 2017 v141 toolset (x86 x64) because it was to available. Setup.py run for 50 min and through me this:

"C:\Users\Yuliia\Install\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Users\Yuliia\Install\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\Yuliia\Install\pytorch\build\caffe2\apply_utils_test.vcxproj" (default target) (18) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'tbb.lib' [C:\Users\Yuliia\Install\pytorch\build\caffe2\apply_utils_test
.vcxproj]


"C:\Users\Yuliia\Install\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\Users\Yuliia\Install\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\Users\Yuliia\Install\pytorch\build\caffe2\tbb_init_test.vcxproj" (default target) (29) ->
  LINK : fatal error LNK1104: cannot open file 'tbb.lib' [C:\Users\Yuliia\Install\pytorch\build\caffe2\tbb_init_test.vc
xproj]

    1468 Warning(s)
    2 Error(s)


I found somewhere that it could be an issue with CMake, installed it again and tried to run setup.py again. Now it shows this:


Traceback (most recent call last):
  File "setup.py", line 776, in <module>
    include_dirs.append(np.get_include())
AttributeError: module 'numpy' has no attribute 'get_include'

What happened and how can I fix it? Thanks!

**Comment by yuliiasergeeva** [comment]
I saw your solution [here ](https://github.com/pytorch/pytorch/issues/8150) but it didn't help

**Comment by peterjc123** [comment]
@yuliiasergeeva A few questions: Did you installed tbb in the virtual environment or the root environment? Did you change the paths in the `set` commands? Did you set the paths after activating the dev shell?

**Comment by nlowell11** [comment]
I am experiencing the exact same issue in @yuliiasergeeva's recent error trace after trying the same steps mentioned in that other post. I had installed tbb to my virtual environment. I also just tried installing it to the base environment as well, but the same error occurs.

**Comment by peterjc123** [comment]
Then what about doing this?
```CMD
# Download the mkl files with tbb
curl -k https://s3.amazonaws.com/ossci-windows/mkl_2018.2.185.7z --output mkl.7z
# Extract the files from the 7z package into the directory mkl
7z x -aoa mkl.7z -omkl
# Set essential flags
set CMAKE_INCLUDE_PATH=%cd%\\mkl\\include
set LIB=%cd%\\mkl\\lib;%LIB
```
It is the steps we used to build the official one in Windows CI.

**Comment by rober42539** [comment]
@peterjc123, same issue here. Downloading mkl with tbb like the official build didn't work for me, same error.

**Comment by peterjc123** [comment]
@rober42539 Could you give me the complete log? I don't know exactly what happened without it?

**Comment by rober42539** [comment]
@peterjc123 Here it is. 

System Overview:
Windows 10 (Home), VC 2017, using instructions on https://github.com/pytorch/pytorch#from-source

Here are the commands I have run (adjusted to my system):

```
set "VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build"
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
set DISTUTILS_USE_SDK=1
set MSSdk=1

call "%VS150COMNTOOLS%\vcvarsall.bat" x64
python setup.py install
```

There's a lot of output, but here is the most important parts:

```
Build FAILED.

"H:\ML\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"H:\ML\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"H:\ML\pytorch\build\caffe2\apply_utils_test.vcxproj" (default target) (19) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'tbb.lib' [H:\ML\pytorch\build\caffe2\apply_utils_test.vcxproj]


"H:\ML\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"H:\ML\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"H:\ML\pytorch\build\caffe2\tbb_init_test.vcxproj" (default target) (32) ->
  LINK : fatal error LNK1104: cannot open file 'tbb.lib' [H:\ML\pytorch\build\caffe2\tbb_init_test.vcxproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:01:20.92

(base) H:\ML\pytorch\build>IF ERRORLEVEL 1 exit 1
Failed to run 'tools\build_pytorch_libs.bat --with-cuda --with-nnpack caffe2 nanopb libshm_windows'
```

Here's the whole output:
[Complete Log](https://docs.google.com/document/d/1sXKXD7BqeCWG4wV9JP3f0yIbUOevXisdqiMFm_YmY38/edit?usp=sharing)

If you need any system specific information, let me know.

**Comment by peterjc123** [comment]
@rober42539 I skimmed your build log. And it seems that the user flag is not properly set. Could you do the following?
```powershell
set "USER_LDFLAGS=/LIBPATH:[lib path that point to tbb.lib, e.g. %MKLProductDir%\tbb\lib\intel64_win\vc_mt]"
## ensure this one is properly set
echo %USER_LDFLAGS%
```

**Comment by rober42539** [comment]
@peterjc123 It didn't seem to work just doing that, but I was able to get it to work. I believe the location would be C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\tbb\lib\intel64_win\vc_mt, which seems right, as I can see the tbb.lib file in that folder. But when I try to set the user flag, it doesn't change the result.

`/LIBPATH:%MKLProductDir%\tbb\lib\intel64_win\vc_mt` is what it prints out. 

Still get:
```
Build FAILED.

"H:\ML\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"H:\ML\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"H:\ML\pytorch\build\caffe2\apply_utils_test.vcxproj" (default target) (19) ->
(Link target) ->
  LINK : fatal error LNK1104: cannot open file 'tbb.lib' [H:\ML\pytorch\build\caffe2\apply_utils_test.vcxproj]


"H:\ML\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"H:\ML\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"H:\ML\pytorch\build\caffe2\tbb_init_test.vcxproj" (default target) (32) ->
  LINK : fatal error LNK1104: cannot open file 'tbb.lib' [H:\ML\pytorch\build\caffe2\tbb_init_test.vcxproj]

    0 Warning(s)
    2 Error(s)
```

So, I approached it another way, by opening the tbb_initet_test and apply_utils_test and manually adding the the tbb.lib (C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\tbb\lib\intel64_win\vc_mt\tbb.lib in my case) to them both. I also added it to the INSTALL project, but not sure what impact that had. 

This seems to have worked in my case. The build was successful.

_Now it's on to figuring out how to include support for the GeForce 940MX that's in my laptop (which doesn't seem to be included by default after building). But, that's another story..._ 

Thanks for help with this!

**Comment by peterjc123** [comment]
@soumith Could we close this, please?
