### ISSUE TITLE
Calling torch.squeeze with out parameter provided throws TypeError

### ISSUE THREAD

**Issue by saeedashrraf** [pytorch/pytorch#83972]
### 🐛 Describe the bug

Running `torch.squeeze` with the argument `out` as one of the input parameters causes a TypeError despite the docs showing that the function supports the `out` parameter [here](https://pytorch.org/docs/stable/generated/torch.squeeze.html#torch.squeeze).

Minimal example:

```
import torch

x = torch.Tensor([[1.,2.]])
y = torch.Tensor([0.,0.])
z = torch.squeeze(x, out=y)
```
This results in the following TypeError:
```
TypeError: squeeze() received an invalid combination of arguments - got (Tensor, out=Tensor), but expected one of:
 * (Tensor input)
 * (Tensor input, int dim)
      didn't match because some of the keywords were incorrect: out
 * (Tensor input, name dim)
      didn't match because some of the keywords were incorrect: out
```
The function works fine if `out` is not provided. So, the following runs correctly:
```
x = torch.Tensor([[1.,2.]])
z = torch.squeeze(x)

```
resulting in `z = tensor([1., 2.])` 

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] torch==1.10.0+cpu
[pip3] torch-scatter==2.0.9
[conda] Could not collect

cc @svekars @holly1238

**Comment by ngimel** [comment]
This is docs issue, viewing operations shouldn't support `out` argument. We'll accept PR fixing the docs

**Comment by foram-chandra** [comment]
@ngimel I would like to fix this doc issue.
