### ISSUE TITLE
Implement `torch.cuda.device_count` without poison

### ISSUE THREAD

**Issue by awaelchli** [pytorch/pytorch#83973]
### 🚀 The feature, motivation and pitch

Currently, when a user calls the functions `torch.cuda.device_count` or `torch.cuda.is_available`, PyTorch initializes some CUDA context that prevents us to fork processes. We get the well known error message "Cannot re-initialize CUDA in forked subprocess" as demonstrated in the code below:

```py
import torch 

def foo(idx):
    print(idx)
    torch.cuda.set_device(idx)

torch.cuda.device_count()  # this call causes an error: "Cannot re-initialize CUDA in forked subprocess"
assert not torch.cuda.is_initialized()
torch.multiprocessing.start_processes(foo, nprocs=2, start_method="fork")
```

In general, the error is accurate because it is not very meaningful to fork processes when CUDA memory is already allocated (e.g., tensors on device, model moved to device, etc.). However, here we are dealing with simple calls to utility functions `torch.cuda.device_count` that do not require any real initialization of the device or memory allocation. There does not seem to be any obvious reason why a call to this function should prevent us from forking processes. 

With this issue, we'd like to request that this behavior be changed.

Looking at the code, we find that the Python API calls into the C++:

https://github.com/pytorch/pytorch/blob/fa241fd50e226d74af06c36482fa68f0e2a4fb3c/torch/cuda/__init__.py#L459-L464

And its implementation is here

https://github.com/pytorch/pytorch/blob/fa241fd50e226d74af06c36482fa68f0e2a4fb3c/torch/csrc/cuda/Module.cpp#L120-L125

where we can find the [`poison_fork()`](https://github.com/pytorch/pytorch/blob/fa241fd50e226d74af06c36482fa68f0e2a4fb3c/torch/csrc/cuda/Module.cpp#L58) call that prevents forked processes to re-initialize CUDA.

**Options to consider:**
- Remove the poison_fork() for the device_count function, as there is no obvious reason why it has to be there.
- Provide a function to un-initialize the CUDA context and memory so that processes can be forked

### Alternatives

In [Lightning](https://github.com/Lightning-AI/lightning), we need to call `torch.cuda.device_count` early on in the Trainer without knowing whether processes are going to be forked or not later on. We currently avoid this issue by running the call to `torch.cuda.device_count` in a subprocess like this:

```
def num_cuda_devices():
    with multiprocessing.Pool(1) as pool:
        return pool.apply(torch.cuda.device_count)
```

This way, the CUDA context gets created in the subprocess while the main process does not get "poisoned". This workaround is not ideal because launching a new process just to evaluate this function is slow. 

### Additional context

https://github.com/Lightning-AI/lightning/issues/14292
https://github.com/Lightning-AI/lightning/pull/13405

cc @ngimel @carmocca @justusschock

**Comment by gchanan** [comment]
CC @ngimel, but I don't think this can work because the cuda context needs to be enabled to query the device count.

**Comment by ngimel** [comment]
`cudaGetDeviceCount` doesn't initialize cuda context, so probably we can move things around to avoid poisoning the fork. cc @ptrblck

**Comment by vadimkantorov** [comment]
Also maybe related: https://github.com/pytorch/pytorch/issues/52675

**Comment by justusschock** [comment]
@ngimel @ptrblck what about other utility functions like `torch.cuda.is_available` and `torch.cuda.get_device_properties`?

It would be nice to have all the functions that help determining whether to use CUDA and which GPU to use without poisoning

**Comment by ptrblck** [comment]
@justusschock Yes, your suggestion makes sense and we discussed the same idea internally. @Aidyn-A will take a look at it to see which ops we can move.

**Comment by ngimel** [comment]
> @ngimel @ptrblck what about other utility functions like `torch.cuda.is_available` and `torch.cuda.get_device_properties`?
> 
> It would be nice to have all the functions that help determining whether to use CUDA and which GPU to use without poisoning

Right, unfortunately I wasn't able to find a clear list of which cuda runtime APIs don't create context (and thus can be called without poisoning), and which do, but nvidia team is looking into it.

**Comment by malfet** [comment]
I wonder if nvml call can be used to avoid that... Let me give it a stab

**Comment by Aidyn-A** [comment]
Generally forks are considered as less safe than spawn. This is the main issue in CUDA as well. 
The moment any CUDA Runtime API is called for the first time it initializes CUDA, namely [`cuInit()`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__INITIALIZE.html#group__CUDA__INITIALIZE_1g0a2f1517e1bd8502c7194c3a8c134bc3) is called under the hood. Even something as simple as:
```
#include <cuda.h>
#include <stdio.h>
#include <unistd.h>

int main() {
  cuInit(0); // with or without or the following two lines
  int deviceCount = 0;
  cudaGetDeviceCount(&deviceCount);

  if (fork() == 0) {
    int deviceCount = 0;
    cudaGetDeviceCount(&deviceCount);
    printf("deviceCount = %d \n", deviceCount);
    cudaDeviceProp prop;
    cudaGetDeviceProperties(&prop, 0);
    printf("DeviceProperties.name = %s \n", prop.name);
  }

  return 0;
}
```
Fails with an initialization error.

@malfet proposed to use NVML which does not have conflicts with subsequent CUDA calls in forks. 

Another possible workaround is to call an executable of something like below, that prints to a temp file:
```
#include <stdio.h> 

int main(int argc, char *argv[]) {
  int DeviceCount;

  cudaGetDeviceCount(&DeviceCount);
  printf("Number of Devices: %d\n", DeviceCount);
  for (int i = 0; i < DeviceCount; i++) {
    cudaDeviceProp prop;
    cudaGetDeviceProperties(&prop, i);
    printf("Device Number: %d\n", i);
    printf("  name: %s\n", prop.name);
    printf("  major: %d\n", prop.major);
    printf("  minor: %d\n", prop.minor);
    printf("  total_memory: %zuMB\n", prop.totalGlobalMem/1048576);
    printf("  multi_processor_count: %d\n", prop.multiProcessorCount);
  }
  exit(0);
}
```
Parse its output and deliver to users via Python API. 

Please let me know what do you think.

**Comment by malfet** [comment]
@Aidyn-A always doing a subprocess thing feels weird, but one can always write a very cheap-and-easy workaround:
```
def  device_count():
  if os.getenv("PYTORCH_NEEDS_FOR_FOR_DEVICE_COUNT"):
      import subprocess
      return subprocess.check_output(sys.executable, "-c", "import torch;print(torch.cuda.device_count", env=os.envion().remove("VERY_LONG_KEY"))
   ...
```

**Comment by vadimkantorov** [comment]
Can device_count change during program execution if CUDA_VISIBLE_DEVICES env. variable gets changed by the user? It's not a good idea to have it changed after initialization, just thinking about edge cases

**Comment by Aidyn-A** [comment]
Seem like there can be mismatches if `CUDA_VISIBLE_DEVICES` gets changed during the run:

```
import os
import sys

import torch

def  device_count():
  if os.environ.get("PYTORCH_NEEDS_FORK_FOR_DEVICE_COUNT"):
      import subprocess
      return subprocess.check_output(["python", "-c", "import torch; print(\" subprocess device_count = \", torch.cuda.device_count())"])

def main():
    NGPUs = torch.cuda.device_count()

    for g in range (1, NGPUs+1):
        dlist = map(str, (list(range(NGPUs+1-g))))
        device_ids = ', '.join(dlist)

        os.environ['CUDA_VISIBLE_DEVICES'] = device_ids
        cuda_n = torch.cuda.device_count()

        print("device_count =", cuda_n)
        print(device_count())

if __name__ == '__main__':
    sys.exit(main())
```
outputs:

device_count = 8
 subprocess device_count =  8
device_count = 8
 subprocess device_count =  7
device_count = 8
 subprocess device_count =  6
device_count = 8
 subprocess device_count =  5
device_count = 8
 subprocess device_count =  4
device_count = 8
 subprocess device_count =  3
device_count = 8
 subprocess device_count =  2
device_count = 8
 subprocess device_count =  1

**Comment by vadimkantorov** [comment]
So probably if memoization is done, it should be keyed on values of CUDA_VISIBLE_DEVICES, NVIDIA_VISIBLE_DEVICES and any other similar variables... Related, in https://github.com/pytorch/pytorch/issues/52675 I propose to also respect a shortcut of 0 devices if a new ~ TORCH_USE_CUDA=OFF env var is set...

**Comment by malfet** [comment]
Here is a small snippet that queries number of devices using NVML:
```
from ctypes import CDLL, c_int
nvml_h = CDLL("libnvidia-ml.so.1")
rc=nvml_h.nvmlInit()
assert rc == 0
dev_arr = (c_int * 1)(-1)
rc = nvml_h.nvmlDeviceGetCount_v2(dev_arr)
assert rc == 0
del nvml_h
print(dev_arr[0])
```

**Comment by malfet** [comment]
> Can device_count change during program execution if CUDA_VISIBLE_DEVICES env. variable gets changed by the user? 

No, any changes to `CUDA_VISIBLE_DEVICES` has any affect after first CUDA call.

**Comment by awaelchli** [comment]
@malfet Thanks so much for the suggestion. So this depends on NVML, do you know what the best way is to check whether it is available on the system, or whether libnvidia-ml.so.1 can be found?

**Comment by vadimkantorov** [comment]
@malfet you seem to be parsing only CUDA_VISIBLE_DEVICES. but should NVIDIA_VISIBLE_DEVICES parsed if it's set instead?

also, about https://github.com/pytorch/pytorch/issues/52675: is it now fixed in the sense that if CUDA_VISIBLE_DEVICES is set to empty, then torch.cuda.get_device_count() and torch.cuda.is_available() will return 0 and False without any CUDA init / CUDA librar loading / driver interaction?

**Comment by vadimkantorov** [comment]
could it first check if `_parse_visible_devices()` returns 0 and then bypass nvml as well? 

also, for the usecase of https://github.com/pytorch/pytorch/issues/52675, a separate explicit additional env variable TORCH_USE_CUDA=OFF may be useful (but not absolutely necessary)

**Comment by malfet** [comment]
@vadimkantorov do you know (preferably with the reference to documentation, whether `NVIDIA_VISIBLE_DEVICES` takes precedence over `CUDA_VISIBLE_DEVICES` or vice versa?

**Comment by vadimkantorov** [comment]
hmm, maybe I got confused about NVIDIA_VISIBLE_DEVICES. https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html it appears it's usually used for launching containers. and it seems it's somehow takes precedence and lets one specify some sort of device ids (maybe similar to CUDA_DEVICE_ORDER?), and then CUDA_VISIBLE_DEVICES select some devices from the availabe gpu's

**Comment by vadimkantorov** [comment]
_parse_visible_devices() could also differentiate between unset CUDA_VISIBLE_DEVICES and set empty string

**Comment by malfet** [comment]
Good point. Let me propose a small followup PR with two optimizations: empty string equals to no devices and in that case no need to query nvml, just return 0

**Comment by awaelchli** [comment]
@malfet I opened a PR #85024 to bring the change also to `torch.cuda.is_available`, since the issue described here is also triggered by the available() call, which is still using the `torch._C._cuda_getDeviceCount()`. Let me know what you think.

**Comment by ppwwyyxx** [comment]
https://github.com/tensorpack/tensorpack/pull/642/files here is a small NVML wrapper we made for the same purpose of avoid poisoning. It also includes support for querying device utilization, etc.
