### ISSUE TITLE
export onnx error,Warning: Constant folding in symbolic shape inference fails: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)

### ISSUE THREAD

**Issue by xiongda777** [pytorch/pytorch#83974]
### 🐛 Describe the bug

```
final=torch.zeros(1,64,1,128,128).to("cuda:0")     
 final=final.transpose(1,4)
 final[geom_feats[:, 3], geom_feats[:, 1], geom_feats[:, 2], geom_feats[:, 0],  0:64] = x
 final=final.transpose(1,4)
```

geom_feats shape is a [a,4] ,a is a dynamic number.  and x shape is [a,64]

when I export onnx:
`torch.onnx.export(model, input, "model.onnx", opset_version=13, do_constant_folding=True, input_names=input_names, output_names = output_names)`

it got :

```
[W shape_type_inference.cpp:434] Warning: Constant folding in symbolic shape inference fails: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
Exception raised from common_device_check_failure at ../aten/src/ATen/core/adaption.cpp:10 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f20cabe5d62 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f20cabe268b in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::impl::common_device_check_failure(c10::optional<c10::Device>&, at::Tensor const&, char const*, char const*) + 0x37e (0x7f211c89ebfe in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x257569b (0x7f20cd3a169b in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #4: <unknown function> + 0x2575722 (0x7f20cd3a1722 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cuda_cu.so)
frame #5: at::_ops::index_select::redispatch(c10::DispatchKeySet, at::Tensor const&, long, at::Tensor const&) + 0xb9 (0x7f211ceee649 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x3253be3 (0x7f211e86cbe3 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3254215 (0x7f211e86d215 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #8: at::_ops::index_select::call(at::Tensor const&, long, at::Tensor const&) + 0x166 (0x7f211cf6e296 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::jit::onnx_constant_fold::runTorchBackendForOnnx(torch::jit::Node const*, std::vector<at::Tensor, std::allocator<at::Tensor> >&, int) + 0x1b5f (0x7f21c661d1cf in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0xbbd6f2 (0x7f21c66646f2 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #11: torch::jit::ONNXShapeTypeInference(torch::jit::Node*, std::map<std::string, c10::IValue, std::less<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&, int) + 0xa8e (0x7f21c6669f3e in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0xbc4a44 (0x7f21c666ba44 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0xb35200 (0x7f21c65dc200 in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x2a585b (0x7f21c5d4c85b in /home/hy/anaconda3/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
```

I'm sure the problem is in  'final[geom_feats[:, 3], geom_feats[:, 1], geom_feats[:, 2], geom_feats[:, 0],  0:64] = x', so I want know how can I export onnx correctly.

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.23.0
Libc version: glibc-2.27

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-123-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090
GPU 5: NVIDIA GeForce RTX 3090
GPU 6: NVIDIA GeForce RTX 3090
GPU 7: NVIDIA GeForce RTX 3090
GPU 8: NVIDIA GeForce RTX 3090

Nvidia driver version: 470.74
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.4
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.6.0
[pip3] torch==1.11.0
[pip3] torch2trt==0.4.0
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.6.2
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] efficientnet-pytorch      0.7.1                    pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] mkl                       2021.4.0           h06a4308_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py38h95df7f1_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
[conda] numpy                     1.22.3           py38he7a7128_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.22.3           py38hf524024_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] pytorch-lightning         1.6.0                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch2trt                 0.4.0                    pypi_0    pypi
[conda] torchaudio                0.11.0               py38_cu113    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchmetrics              0.6.2                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by justinchuby** [comment]
Please try using the latest pytorch nightly version

**Comment by shubhambhokare1** [comment]
Hi @xiongda777,

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
