### ISSUE TITLE
ParameterDict assignment doesn't conform to no_grad semantics

### ISSUE THREAD

**Issue by pauldb89** [pytorch/pytorch#83998]
New tensors / parameters created in `torch.no_grad` blocks should have `requires_grad` set to `False`. This is not true when the value is placed in a `nn.ParameterDict` (see example below). Updating `ParameterDict`s in `no_grad` block may not seem like a valid use case, but it's a necessary work around until `nn.BufferDict` are introduced (https://github.com/pytorch/pytorch/issues/37386). 

Example code snippet illustrating the issue

```
import torch
from torch import nn

a = nn.Parameter(torch.rand(10))
b = nn.Parameter(torch.rand(10))
p = nn.ParameterDict()
with torch.no_grad():
    c = a + b
    p["key"] = a + b

print(c.requires_grad)
print(p["key"].requires_grad)
```

Output:
```
False
True
```

Expected:
```
False
False
```

### Versions

1.12

cc @svekars @holly1238 @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
Hi,

This is generally true for all Paramters that get created: 
```python
import torch
from torch import nn

with torch.no_grad():
  a = nn.Parameter(torch.rand(10))
print(a.requires_grad())
```

While I agree that this is a bit of a surprising behavior, changing it would be BC-breaking in a bad way I'm afraid.
We should update the doc though to reflect this.
