### ISSUE TITLE
How is "sharing CUDA tensor between processes" implemented?

### ISSUE THREAD

**Issue by helinwang** [pytorch/pytorch#840]
As mentioned in https://github.com/pytorch/pytorch/blob/ca555abcf93fe7c874705d881ba4839bef495ed0/docs/source/notes/multiprocessing.rst#sharing-cuda-tensors, CUDA tensors could be shared between processes.

Could anyone tell me how it's implemented, or point me to the code?

Thanks!
Helin

**Comment by apaszke** [comment]
I think the most important ones are [`StorageSharing.cpp`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/StorageSharing.cpp#L191-L270), and the [`multiprocessing` reductions](https://github.com/pytorch/pytorch/blob/master/torch/multiprocessing/reductions.py#L91-L123).

For the future, please ask questions [on our forums](discuss.pytorch.org). We'll be happy to discuss implementation details there, but we'd like to keep issues for bug reports and feature requests only. Thanks!
