### ISSUE TITLE
Linux cuda-11.x binary build  jobs intermittently take more than 4 hours

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#84003]
### 🐛 Describe the bug

 When we do:
```
conda install pytorch cudatoolkit=11.3 -c pytorch-nightly
```
Conda installs the CPU version:
```
pytorch            pytorch-nightly/linux-64::pytorch-1.13.0.dev20220824-py3.9_cpu_0
```

The Linux jobs upload have failed:
<img width="1058" alt="Screen Shot 2022-08-24 at 9 15 41 AM" src="https://user-images.githubusercontent.com/7563158/186431127-c16e5dab-d1dc-4e33-a32c-cbaf6bbc5bb7.png">

Github upload failed:
https://github.com/pytorch/pytorch/runs/7989185420?check_suite_focus=true

```
Uploaded /home/ec2-user/actions-runner/_work/_temp/artifacts/pytorch-1.13.0.dev20220824-py3.9_cuda11.3_cudnn8.3.2_0.tar.bz2 (90.2%) bytes 1191182336:1199570943
Total file count: 1 ---- Processed file #0 (0.0%)
Error: The operation was canceled.
```

Root cause timeout more then 4hrs:

<img width="396" alt="Screen Shot 2022-08-24 at 9 00 59 PM" src="https://user-images.githubusercontent.com/7563158/186550393-e49cb402-39dd-4d8a-8b54-1e9931e2cd3f.png">

### Versions

cuda 11.3
cuda 11.6

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by atalman** [comment]
Mitigation proposed in this PR: https://github.com/pytorch/pytorch/pull/84008

**Comment by atalman** [comment]
However we need to understand what makes it slow, and where is the regression

**Comment by malfet** [comment]
Edited the title, few weird datapoints:
- `manywheel-py3_10-cuda11_6` build time spiked from [1h45m](https://github.com/pytorch/pytorch/runs/7761367847?check_suite_focus=true) to [3h+](https://github.com/pytorch/pytorch/runs/7781878455?check_suite_focus=true) on Aug 11th
- Though conda builds always took 3+ hours, but they as well jumped from [3h15m](https://github.com/pytorch/pytorch/runs/7666916872?check_suite_focus=true) to [3h40+min](https://github.com/pytorch/pytorch/runs/7686674677?check_suite_focus=true) on Aug 5h

**Comment by malfet** [comment]
And I have a very good culprit for build time increase: https://github.com/pytorch/pytorch/pull/83173(landed on Aug10th, so would affect Aug 11th builds) cc: @peterbell10

**Comment by peterbell10** [comment]
@malfet PTAL at #83696, it restores parallel building of nccl.

**Comment by huydhn** [comment]
I'm closing this issue as this is too old and doesn't apply anymore to the current release pipeline.
