### ISSUE TITLE
"RuntimeError: src_total_size >= storage_byte_offset INTERNAL ASSERT FAILED" when training using MPS on YOLOv5

### ISSUE THREAD

**Issue by Leo-Maxwell** [pytorch/pytorch#84042]
### 🐛 Describe the bug

I was training on the latest version of YOLOv5 by the latest PyTorch nightly using MPS acceleration on an Apple Silicon based MacBook, but after just ONE successful epoch, I got this:

RuntimeError: src_total_size >= storage_byte_offset INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Copy.mm":129, please report a bug to PyTorch.

So I am reporting a bug here.

Note: the command I used to train the network is an example command that comes with the YOLOv5 train.py, I just added --device mps parameter, so I think the problem is not the way I train.

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220824
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-12.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.13.0.dev20220824
[pip3] torchaudio==0.13.0.dev20220824
[pip3] torchvision==0.14.0.dev20220824
[conda] Could not collect

cc @kulinseth @albanD

**Comment by DenisVieriu97** [comment]
Hi @Leo-Maxwell - thank you for the report!
This issue is fixed in the nightly build - could you please try the latest PyTorch nightly ( torch-1.13.0.dev20220930) and let me know if you still see any issues? Thanks!

**Comment by Leo-Maxwell** [comment]
Yes, I tried this morning (UTC 2:47) and this issue is fixed. Thank you for your kind support and fix. Wish you a good day!
