### ISSUE TITLE
Track land validation usage

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#84060]
### 🚀 The feature, motivation and pitch

We need good visibility into how often people are using land validation, and anecdotally at least some people are starting to opt out of it.  We need better visibility into who's choosing not to use it and why.

Specifically, we should be able to tell:

1. How often a PR was opted-in to land validation - these folks _like_ LV
2. How often a PR was defaulted in to land validation - these folks at least don't mind LV (or might even like it)
3. How often people OPT-OUT of land validation over time <-- these folks dislike LV and are the **most important for rollout**
  a.  Knowing how often people tried land validation and then opted out later in the same PR would be really useful here!

If we see a significant number of PRs opting out (e.g. 20% or more) then that's a sign we have a problem and need to dig deeper before rolling land validation out to more people.

Along with raw counts, we should also track which PRs had devs opting out, etc so that we can figure out *why* an opt-out occurred 

### Alternatives

This could potentially be done by:
- Extending  trymerge to emit the above data to rockset.
- Querying existing rockset data (though that might be tricky to do since rockset doesn't have a good view of when folks get opted in/out and when we proactively skip land validation due to e.g. a trunk label)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by dagitses** [comment]
Just a bystander here, but what is the advantage of opting out of land validation?

**Comment by ZainRizvi** [comment]
Reasons I've seen folks opt out:

- They didn't want to wait for 3 hours for land checks to pass 
- They use merge -f instead because:
  - Github action outage, so folks merge -f to opt out
  - Land validation used to fail if the PR itself had a failing check which the validation branch would be green on (we fixed the underlying issue for that one)

There may be other reasons as well, which tracking opt-outs should help us discover
