### ISSUE TITLE
PyTorch with cuda 11.3 does not work on cuda 11.4 as claimed

### ISSUE THREAD

**Issue by deimsdeutsch** [pytorch/pytorch#84069]
### 🐛 Describe the bug

This issue was closed without ever checking how many troubles it created. Now we are stuck as we don't have working binaries for Cuda11.4. This needs to be reopened and slammed with our faces so that it can be resolved.

https://github.com/pytorch/pytorch/issues/75992

### Versions

No binaries for cuda 11.4

**Comment by ptrblck** [comment]
The PyTorch binaries with the CUDA 11.3 runtime work on drivers supporting CUDA 11.4.
Unfortunately, your issue does not explain any use cases which fail nor do you post any errors you are seeing.
As explained in the linked issue, there is no plan to build PyTorch binaries with a CUDA 11.4 runtime.
You can build PyTorch from source if you depend on this specific CUDA toolkit version.

Based on: https://github.com/pytorch/pytorch/issues/75992#issuecomment-1226448501
> Your the creep whose creating trouble for everyone. Buddy test before you commit to such a statement.

I would also like to ask to to check your attitude before posting such comments.

**Comment by seemethere** [comment]
Going to close this one since there were no details provided. In the case of users experiencing this please feel free to submit a separate issue with details!

**Comment by seemethere** [comment]
Locking the conversation on this since the issue that was originally linked started to get spammed. If there are users who need a specific architecture that we don't support with our official builds we would highly encourage to build from source!
