### ISSUE TITLE
Mac M1 arm64 runners not available

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#84089]
## Current Status
ongoing

## Error looks like
All M1 mac arm64 tests are the queue https://hud.pytorch.org/metrics waiting for `macos-m1-12` runners. For example https://github.com/pytorch/pytorch/runs/8025452271

![Screen Shot 2022-08-25 at 15 40 21](https://user-images.githubusercontent.com/475357/186781086-b70236e0-ed6e-441f-9f60-a3958e3295d6.png)

## Incident timeline (all times pacific)
The issue started from around 10AM in the morning according to HUD https://hud.pytorch.org. Here is the first commit in trunk that fails due to time out https://hud.pytorch.org/pytorch/pytorch/commit/86e134ddf777d6f4b82a1860102698ef13bf0c33

## User impact
Mac M1 arm64 trunk tests waits till timeout. If people have `ciflow/trunk` in the PR, that would also be impacted.

## Root cause
TBD

## Mitigation
TBD

## Prevention/followups
TBD

**Comment by huydhn** [comment]
Thank @seemethere for picking up the investigation!

**Comment by malfet** [comment]
Wow, looks like we are clairvoyant:  19229d days ago is probably Jan 1st 1970

**Comment by seemethere** [comment]
Looks like an auto-update made it so that the GHA daemon was endlessly boot looping. Seems to coincide with the daemons updating.

I've submitted a fix and re-kicked the daemon on all of the hosts.

marking this a resolved

**Comment by ZainRizvi** [comment]
@seemethere any plans for RelEng to add alerting to detect these kind of failures faster in the future?
