### ISSUE TITLE
[ONNX] Move model and input to the same device when exporting

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#84123]
### 🚀 The feature, motivation and pitch

When users call the troch.onnx.export api, shape inference will error out if the model and the input are not on the same device (https://github.com/pytorch/pytorch/issues/83974). In our context manager, we can have an additional step which moves everything to the same device (most likely input to that of the model).

cc @BowenBao 

### Alternatives

Do nothing

**Comment by BowenBao** [comment]
I'm not sure if casting is a good idea. PyTorch run would also complain if they are not on the same device. It's invalid input.
For that issue, I think it warrants a closer look if it's a bug in our constant folding/shape inference code, since model execution passed the point of tracing to there.
