### ISSUE TITLE
If we block a merge due to merge rules, call out the rule that failed!

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#84147]
### 🚀 The feature, motivation and pitch

When mergebot's merge fails due to a merge rule, we should let the user know what merge rule failed and what they can do to make it succeed.

As an example, this comment I was given zero information on what to do to get my PR to actually get merged (short of doing a force merge): https://github.com/pytorch/pytorch/pull/83990#issuecomment-1227744501

# The message today:

Merge failed
Reason: PR 83990 does not match merge rules
Raised by [workflow job](https://github.com/pytorch/pytorch/actions/runs/2929562913) If you believe this is an error, you can use the old behavior with @pytorchbot merge -g (optionally with the ciflow/trunk to get land checks) or use @pytorchbot merge -f "some reason here". For more information, see the [bot wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands).
Please reach out to the [PyTorch DevX Team](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours) with feedback or questions!

# What the message should look like:

### Merge failed
Reason: PR 83990 does not meet merge rule **foo**:
To fix this:
- Get signoffs from either person A, B, or C
- Add label X and Y to run test Foo
- Do thing Z

For more information, see the [bot wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands).

Please reach out to the [PyTorch DevX Team](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours) with feedback or questions!

<details><summary>Details for DevX team</summary>
Raised by [workflow job](https://github.com/pytorch/pytorch/actions/runs/2929562913) 
</details>

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
I think this message is specific about missing signoffs from people set in [merge_rules.yaml](https://github.com/pytorch/pytorch/blob/master/.github/merge_rules.yaml#L95).  A failing test shows a slightly different message, i.e. https://github.com/pytorch/pytorch/pull/83946

> Merge failed
Reason: Refusing to merge as mandatory check(s) [pull](https://github.com/pytorch/pytorch/commit/7d933481d29b2e706e0bd6b8d5000810f5692f40/checks?check_suite_id=7950231151) failed for rule OSS CI
Raised by https://github.com/pytorch/pytorch/actions/runs/2921234279 If you believe this is an error, you can use the old behavior with @pytorchbot merge -g (optionally with the ciflow/trunk to get land checks) or use @pytorchbot merge -f "some reason here". For more information, see the [bot wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands).
Please reach out to the [PyTorch DevX Team](https://github.com/pytorch/pytorch/wiki/Dev-Infra-Office-Hours) with feedback or questions!

I could put a fix for this and close my other task that is currently assigned to me https://github.com/pytorch/test-infra/issues/421. It's was more generic than this one, but I believe @zengk95 has already addressed the majority of the issue in some of his recent updates

**Comment by ZainRizvi** [comment]
Yeah, this mainly about calling out if specific sign-offs are missing. The merge rules are a bit more generic though so it would be nice if we can capture range of issues that can occur.

At the very least, can you confirm that we now call out which people still need to sign off on a PR?

**Comment by huydhn** [comment]
This is some examples of trying to merge a PR with missing sign-offs which mergebot prevents:

* No sign-off https://github.com/pytorch/pytorch/pull/84005#issuecomment-1226094553
> but PR https://github.com/pytorch/pytorch/pull/84005 has not been reviewed yet

* Missing sign-off https://github.com/pytorch/pytorch/pull/83653#issuecomment-1220185149
> but PR https://github.com/pytorch/pytorch/pull/83653 was not reviewed yet by any of: gchanan, dzhulgakov, soumith, ezyang

Let's rebase and re-merge https://github.com/pytorch/pytorch/pull/83990 to verify this.
