### ISSUE TITLE
NNAPI failed in converting a constant defined in the model

### ISSUE THREAD

**Issue by jackmvision** [pytorch/pytorch#84161]
### 🐛 Describe the bug

When I used the following code to convert a traced model to NNAPI, it complaints about a constant in the model 

`nnapi_model = torch.backends._nnapi.prepare.convert_model_to_nnapi(traced, input_tensor)`

The constant is defined in the model like this

```python
def prep(x: Any):
    return (x - 128.0)

def forward(self, x):
        x = prep(x)
        ...
```

The error happened when the code tried to convert the constant _128.0_ used in `prep()` above.  Since it is a constant, its dim() is 0,  which causes an error in `add_tensor_operand_for_weight()` where it tries to do `tensor = tensor.permute(0, 2, 3, 1)`.  Could you help me resolve this problem? Thanks. 

```python
File ~/envs/torchvision0.11/lib/python3.8/site-packages/torch/backends/_nnapi/serializer.py:513, in _NnapiSerializer.get_tensor_operand_or_constant(self, jitval, dim_order)
    511 if operand_id is None:
    512     _, value = self.get_constant_value(jitval, "TensorType")
--> 513     operand_id = self.add_tensor_operand_for_weight(value, dim_order)
    514 return (operand_id, self.operands[operand_id])

File ~/envs/torchvision0.11/lib/python3.8/site-packages/torch/backends/_nnapi/serializer.py:451, in _NnapiSerializer.add_tensor_operand_for_weight(self, tensor, dim_order)
    448 # For NHWC NNAPI op, lay out data in the same dim order by permuting torch tensor
    450 if dim_order == DimOrder.CHANNELS_LAST:
--> 451     tensor = tensor.permute(0, 2, 3, 1)
    452 self.used_weights.append(tensor)
    453 return operand_id

RuntimeError: number of dims don't match in permute
```

### Versions

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1086-gcp-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: Tesla T4

Nvidia driver version: 455.23.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.1
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by axitkhurana** [comment]
Hi @jackmvision, at this point of time we don't support Tensor & Float subtraction in the converter. Only Equal rank tensors can be worked on for binary ops. Sorry about that!

**Comment by jackmvision** [comment]
@axitkhurana , good to know. Thanks.
