### ISSUE TITLE
Conv2d layer produces NaNs in Pytorch 1.12.1

### ISSUE THREAD

**Issue by crawlingcub** [pytorch/pytorch#84171]
### 🐛 Describe the bug

Conv2d layer produces NaNs when the input contains some large values. The problem does not happen with PyTorch 1.8.0 or when I disable cuda. Is this expected? Let me know if you need more info. Thanks!

### Repro code:
```python
import torch
import numpy
import pickle as pkl

layerinp=torch.Tensor(pkl.load(open("torch-conv-data.pkl", "rb")))
layerinp=layerinp.to("cuda")

model = torch.nn.Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
model.to("cuda")
model.eval()
with torch.no_grad():
    output=model(layerinp).cpu().data.numpy()

print("pt output", output[0][0][0])   
```

### Output:
With CUDA:
```
pt output [nan nan nan nan nan nan nan nan nan nan]
```

With CPU:
```
pt output [-1.3169583e+35 -1.2827484e+35 -3.9124191e+33 -2.5498483e+35  1.9269180e+34  1.6503930e+35  8.3835845e+34  2.5843263e+34  1.1229672e+35 -1.5421355e+35]
```

Find the data file [here](https://drive.google.com/file/d/1VOEfZ9_H62DjdZvmjvoopd8mQMRAWWg0/view?usp=sharing)

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.27

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-1081-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] pytorch2keras==0.2.4
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchinfo==1.7.0
[pip3] torchvision==0.13.1
[conda] cudatoolkit               11.7.0              hd8887f6_10    conda-forge
[conda] numpy                     1.23.2                   pypi_0    pypi
[conda] pytorch2keras             0.2.4                    pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchaudio                0.12.1                   pypi_0    pypi
[conda] torchinfo                 1.7.0                    pypi_0    pypi
[conda] torchvision               0.13.1                   pypi_0    pypi

cc @csarofeen @ptrblck @xwang233 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by ngimel** [comment]
cc @ptrblck

**Comment by ptrblck** [comment]
@crawlingcub Could you post the input range of `layerinp` and rerun your test with the PyTorch binaries using CUDA 11.x?

**Comment by crawlingcub** [comment]
Input range: `max min mean 1.020847e+36 0.0 1.9487599e+35`

Output with pt 1.12.1cu113: `pt output [-9.1903807e+34  6.6647552e+34  1.3627001e+35  2.6257416e+34
  7.9070781e+34  3.9418071e+35  1.7329477e+35  2.1276220e+35
 -5.0310690e+34 -2.9835348e+34]`

So looks like it works with cuda 11.x but not with cuda 10?

**Comment by ngimel** [comment]
cuda 11.x release has a different cudnn version. Closing, cuda 10 release won't be fixed.

**Comment by crawlingcub** [comment]
I see. Thanks! Out of curiosity, do you know the root cause of this bug? Or what could have potentially caused it?
