### ISSUE TITLE
M1 runner i-00d2de3afb92ed15f fails during `Setup Miniconda step`

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#84196]
### 🐛 Describe the bug

See https://github.com/pytorch/pytorch/runs/8067727334?check_suite_focus=true 
or https://github.com/pytorch/pytorch/runs/8065205882?check_suite_focus=true for example

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
I went ahead and remove the runner, but it would be good to have some sort of guideline how other members of infra team can remedy the situation

**Comment by ZainRizvi** [comment]
Would be great to also include how to detect the situation

**Comment by janeyx99** [comment]
To detect that a runner is failing:
- See multiple red
- check the runner that is used for each failure by looking in the logs (setup job part or just by cmd-f'ing "i-")
- if there are runners in common, those are likely culprit

**Comment by seemethere** [comment]
Submitted https://github.com/pytorch/pytorch/pull/84236 to mitigate issues like this
