### ISSUE TITLE
Fused addmm path in linear causing performance regression in XLA backend

### ISSUE THREAD

**Issue by yeounoh** [pytorch/pytorch#84244]
### 🐛 Describe the bug

Forcing a reshape (flattening a 3D image to 2D) to use `addmm` instead of (`add` + `mm`) in linear layer is causing a performance regression for XLA backend. Here is the [PR](https://github.com/pytorch/pytorch/pull/72728) that introduced the fused `addmm` path in linear.

- Performance (`50%=346ms296.633us`) with the PR reverted (without the reshape):
```
Metric: ExecuteTime
TotalSamples: 5007
Accumulator: 34m13s502ms363.138us
ValueRate: 901ms677.295us / second
Rate: 2.57566 / second
Percentiles: 1%=339ms978.601us; 5%=341ms837.850us; 10%=342ms528.681us; 20%=343ms698.133us; 50%=346ms296.633us; 80%=355ms353.758us; 90%=366ms728.914us; 95%=373ms757.265us; 99%=387ms704.938us
```

- Performance (`50%=387ms772.182us`) with the change (with the reshape):
```
Metric: ExecuteTime
TotalSamples: 5007
Accumulator: 32m29s100ms240.632us
ValueRate: 936ms700.882us / second
Rate: 2.41131 / second
Percentiles: 1%=372ms787.092us; 5%=373ms205.957us; 10%=374ms397.273us; 20%=377ms506.573us; 50%=387ms772.182us; 80%=396ms970.066us; 90%=403ms298.862us; 95%=411ms212.355us; 99%=425ms628.615us
```

the regression is 5-10% for the reference model (ViT model with 3D image input).

Would it be possible to force the fused addmm path for non-`XLA` backend? `XLA` backend is generally sensitive to a wide tensors (flattened), and the backend can't undo the op if the input is reshaped. Please help!

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-1019-gcp-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.20.3           py39hf144106_0  
[conda] numpy-base                1.20.3           py39h74d4b33_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  

cc @bdhirsh @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @ronghanghu @swolchok

**Comment by ezyang** [comment]
Yes. You can just test `is_xla` and go back to the old code path. Send a patch.
