### ISSUE TITLE
[feature request] Add CUDA 9.2 pytorch wheels

### ISSUE THREAD

**Issue by quinor** [pytorch/pytorch#8424]
CUDA 9.2 is now default on Arch Linux, please add CUDA 9.2 pytorch releases to pytorch.org. Using older (9.1) release with 9.2 produces errors for me when I'm trying to compile my own layers from CUDA (like in https://github.com/jwyang/faster-rcnn.pytorch repository)

**Comment by pranman** [comment]
Frustratingly, it appears the (now) merged Caffe2 only supports CUDA 9.0 as well.
Question - surely there is a way to make releases future compatible with minor version updates? 

For instance, would it be possible to make dynamic references to specific files, e.g cuda9.1,yy, to instead be changed to cuda9.Z.yy to retain compatibility with future minor versions?

**Comment by soumith** [comment]
we will add 9.2 wheels starting from the next minor release.

**Comment by saransha** [comment]
if you dont mind me asking, when is the next minor release?

**Comment by soumith** [comment]
release is live. links to wheels and conda packages with cuda 9.2 are on https://pytorch.org

**Comment by soumith** [comment]
@jrios6 no, we dont plan to ever release MacOS CUDA binaries. We are not officially supporting PyTorch MacOS on CUDA.
