### ISSUE TITLE
Support dict inputs and outputs when exporting to ONNX

### ISSUE THREAD

**Issue by sharvil** [pytorch/pytorch#84257]
### 🚀 The feature, motivation and pitch

I have a model that takes `features: Dict[str, Tensor]` as input and produces `predictions: Dict[str, Tensor]` as output. It's straightforward to convert this model to TorchScript, but I need to export it to ONNX for deployment. Unfortunately, the PyTorch-to-ONNX converter (`torch.onnx.export`) doesn't seem to support dictionaries as inputs/outputs even though ONNX itself does.

### Alternatives

One option is to convert the dictionaries to keyword parameters, but that approach has several drawbacks:
1. More cumbersome to iterate on code -- input features may change over the course of a model's development. Adding named parameters to a function's signature is unnecessary overhead.
2. Outputs aren't named, so we'd have to return a list/tuple. In such cases, we have to be very careful about the return value order and make sure all scripts/tools that invoke the model are updated on any additions, removals, or permutations to the output.
3. We may only have access to the TorchScript model, so changing the inputs/outputs isn't even possible for us in all cases.

### Additional context

Here's a simple script that demonstrates the missing support for this feature:

```python
import torch

from typing import Dict


class A(torch.nn.Module):
  def forward(self, features: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
    print(features['b'])
    return {
      'c': features['a'],
    }


module = torch.jit.script(A())
sample_a = torch.zeros([1,2], dtype=torch.float32)
sample_b = torch.zeros([2,1], dtype=torch.float32)
features = { 'a': sample_a, 'b': sample_b }
module(features)
torch.onnx.export(module, (features, {}), 'output.onnx')
```

**Comment by BowenBao** [comment]
IIUC, @sharvil for your use case, the keys of both input/output dictionary remain statically the same for a given exported model. @shubhambhokare1 I thought this is supported, perhaps the model has to be traced instead of scripted?

**Comment by shubhambhokare1** [comment]
@BowenBao @sharvil That is right. The export of dictionaries is supported only for tracing as of now and not scripting mode. Even in tracing mode, input/output dictionary remain statically the same as mentioned.

**Comment by sharvil** [comment]
@BowenBao, @shubhambhokare1 no the input/output dictionary don't remain statically the same for my use-case. The input dictionary is a map of features, and the output is a map of prediction results. These are specified at runtime.

This feature request is to support non-static dictionaries as inputs/outputs when exporting to ONNX in scripting mode.

**Comment by shengugang** [comment]
is theree have any solutions?I meet this questions too

**Comment by liqunfu** [comment]
Here is a modified sample code:
import io
import onnx
from onnx import reference as onnxreference
import torch
from torch import Tensor, nn

class A(nn.Module):
  def forward(self, x: dict[str, Tensor]) -> dict[str, Tensor]:
    return {
      'c': x['a'] + x['b'],
    }


module = A()
features = {"a": torch.rand((2,)), "b": torch.rand((2,))}
torch_out = module(features)
print("torch_out:", torch_out)

f = io.BytesIO()
# torch.onnx.export(module, {"x": features}, f) <== **this works but I want to avoid this**
torch.onnx.export(module, (features,), f) <== **this line fails with "A.forward() missing 1 required positional argument: 'x'"** 
onnx_model = onnx.load_model_from_string(f.getvalue())

sess = onnxreference.ReferenceEvaluator(onnx_model)
model_input_names = [i.name for i in onnx_model.graph.input]
input_dict = dict(zip(model_input_names, features.values()))
onnx_out = sess.run(None, input_dict)
print("onnx_out:", onnx_out)

**Comment by 1372072273** [comment]
> Here is a modified sample code: import io import onnx from onnx import reference as onnxreference import torch from torch import Tensor, nn
> 
> class A(nn.Module): def forward(self, x: dict[str, Tensor]) -> dict[str, Tensor]: return { 'c': x['a'] + x['b'], }
> 
> module = A() features = {"a": torch.rand((2,)), "b": torch.rand((2,))} torch_out = module(features) print("torch_out:", torch_out)
> 
> f = io.BytesIO() # torch.onnx.export(module, {"x": features}, f) <== **this works but I want to avoid this** torch.onnx.export(module, (features,), f) <== **this line fails with "A.forward() missing 1 required positional argument: 'x'"** onnx_model = onnx.load_model_from_string(f.getvalue())
> 
> sess = onnxreference.ReferenceEvaluator(onnx_model) model_input_names = [i.name for i in onnx_model.graph.input] input_dict = dict(zip(model_input_names, features.values())) onnx_out = sess.run(None, input_dict) print("onnx_out:", onnx_out)

thanks,I solved this problem

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
