### ISSUE TITLE
Support more overloads of Tensor.to in torch._refs.to

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#84264]
### 🚀 The feature, motivation and pitch

There are multiple overloads of `to`, but currently only one overload is supported in `torch._refs.to`
aten/src/ATen/native/native_functions.yaml lists all overloads:
https://github.com/pytorch/pytorch/blob/acd6ca8cfa9537284928fb5d36834d1e5ae1e6f3/aten/src/ATen/native/native_functions.yaml#L6581-L6599
Missing overloads:

- [ ]  to.dtype_layout
- [ ]  to.device
- [ ]  to.other

cc @ezyang @mruberry @ngimel @jjsjann123

**Comment by jjsjann123** [comment]
Linking my faulty PR that took us here. #83782

![image](https://user-images.githubusercontent.com/3709243/189445665-3aa8dfb1-fb9e-40cf-8f25-93dbb7ebb04c.png)

**Comment by jjsjann123** [comment]
Looks like there's some example of how `var.X` overloads are handled in refs. I'll follow that pattern and get overloads of Tensor.to plumbed through.
