### ISSUE TITLE
nn.Linear should warn the mismatched dimension on CUDA

### ISSUE THREAD

**Issue by ygtxr1997** [pytorch/pytorch#84328]
### 🐛 Describe the bug

On CUDA device, if the input dimension >= the expected dimension of nn.Linear, the code works successfully.
But if  the input dimension < the expected dimension of nn.Linear, an error will be raised.

```python
myfc = nn.Linear(512 * 7 * 6, 512).cuda()  # should move to cuda
x = torch.randn(5, 512 * 7 * 6 + 1).cuda()  # -1 is not ok, +1 is ok
out = myfc(x)
print(out.shape)
```

If ```.cuda()``` is removed, an dimension mismatch error will be raised if input dimension != expected dimension.
But on CUDA, the dimension mismatch error only occurs when input dimension < expected dimension.
I think a warning or error should occur whether input dimension < expected dimension or input dimension > expected dimension.

### Versions

PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Tencent tlinux 2.2 (Final) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.3.4

Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] (64-bit runtime)
Python platform: Linux-5.4.32-1-tlinux4-0001-x86_64-with-centos-7.2-Final
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: GRID T4-8C
Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.4.5
[pip3] torch==1.9.0+cu111
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.8.2+cu110
[conda] Could not collect

**Comment by ngimel** [comment]
This was fixed for 1.9.1
