### ISSUE TITLE
About the results of "torch.matmul" on RTX 3080

### ISSUE THREAD

**Issue by WhoTHU** [pytorch/pytorch#84334]
I encountered a problem with the results of "torch.matmul" on RTX 3080. I have checked several relative issues including 
 [this](https://github.com/pytorch/pytorch/issues/67384), [this](https://github.com/pytorch/pytorch/issues/61890#issuecomment-906728150) and [this](https://discuss.pytorch.org/t/bug-matmul-seems-to-cast-to-float16-internally/135248). I also read the [documents](https://pytorch.org/docs/stable/notes/cuda.html#tf32-on-ampere) about torch.backends.cuda.matmul.allow_tf32. 

Indeed, setting torch.backends.cuda.matmul.allow_tf32 = False can correct the results. However, I don't think  allow_tf32 = True is the cause of the incorrect results on RTX 3080, since setting torch.backends.cuda.matmul.allow_tf32 = True also produces correct results on RTX 2080. In addition, different torch versions with the same allow_tf32 value produce different results.

Here are the codes and results：

CODE:
```
import torch
device = 'cuda:0'
torch.backends.cuda.matmul.allow_tf32 = True
dtype = torch.float32
identity = torch.tensor([[1.0]], dtype=dtype, device=device)
vector = torch.tensor([1024.5], dtype=dtype, device=device)

product = vector.matmul(identity)
print(product)
```

RTX 3080, torch 1.10.0 OUTPUT:
tensor([1025.], device='cuda:0')

RTX 3080, torch 1.7.1 OUTPUT:
tensor([1024.5000], device='cuda:0')

RTX 2080, torch 1.10.0 OUTPUT:
tensor([1024.5000], device='cuda:0')
****************************************************************************************
The error (0.5) is much more than that float32 should have. And it is also different to the results of float16

CODE:
the previous code and setting
`dtype = torch.float16`

RTX 3080, torch 1.10.0 / RTX 3080, torch 1.7.1 / RTX 2080, torch 1.10.0 OUTPUT:
tensor([1024.], device='cuda:0')
****************************************************************************************
****************************************************************************************
****************************************************************************************
Here is an another code

```
import torch
import numpy as np

torch.backends.cuda.matmul.allow_tf32 = True
device = 'cuda:0'
dtype = torch.float32
a = np.load('trya.npy') # shape = (129, 129)
b = np.load('tryn.npy') # shape = (1, 129, 3)
a = torch.from_numpy(a).to(device).to(dtype)
b = torch.from_numpy(b).to(device).to(dtype)

r1 = torch.matmul(a, b)
r2 = torch.matmul(a.cpu(), b.cpu())
gt = torch.matmul(a.to(torch.float64), b.to(torch.float64))

print('Comparison 1')
print((r1.cpu() - r2).abs().sum())
print((r1.cpu() - gt.cpu()).abs().sum())
print((r2.cpu() - gt.cpu()).abs().sum())

a = torch.zeros(100, 100).uniform_().to(device).to(dtype)
b = torch.zeros(100, 100).uniform_().to(device).to(dtype)

r1 = torch.matmul(a, b)
r2 = torch.matmul(a.cpu(), b.cpu())
gt = torch.matmul(a.to(torch.float64), b.to(torch.float64))


print('Comparison 2')
print((r1.cpu() - r2).abs().sum())
print((r1.cpu() - gt.cpu()).abs().sum())
print((r2.cpu() - gt.cpu()).abs().sum())
```

RTX 3080, torch 1.10.0 OUTPUT:
Comparison 1
**tensor(0.3640)**
tensor(0.3639, dtype=torch.float64)
tensor(3.4841e-05, dtype=torch.float64)
Comparison 2
**tensor(6.7663)**
tensor(6.7664, dtype=torch.float64)
tensor(0.0297, dtype=torch.float64)

RTX 3080, torch 1.7.1 OUTPUT:
Comparison 1
**tensor(4.3363e-05)**
tensor(4.0597e-05, dtype=torch.float64)
tensor(3.4841e-05, dtype=torch.float64)
Comparison 2
**tensor(7.0006)**
tensor(7.0006, dtype=torch.float64)
tensor(0.0300, dtype=torch.float64)

RTX 2080, torch 1.10.0 OUTPUT:
Comparison 1
**tensor(4.3363e-05)**
tensor(4.0597e-05, dtype=torch.float64)
tensor(3.4841e-05, dtype=torch.float64)
Comparison 2
**tensor(0.0315)**
tensor(0.0099, dtype=torch.float64)
tensor(0.0298, dtype=torch.float64)

Only the results on RTX 2080 seems to be correct while the RTX 3080, torch 1.10.0 failed in both cases, and RTX 3080, torch 1.7.1 failed only in the second case (Comparison 2).

The weird thing is, that it is not consistent with the results of float16:
when setting "dtype = torch.float16" in the previous code, the output in all three environments becomes (similar outputs thus I put one of them)

Comparison 1
**tensor(0.2754, dtype=torch.float16)**
tensor(0.0423, dtype=torch.float64)
tensor(0.2729, dtype=torch.float64)
Comparison 2
**tensor(240.7500, dtype=torch.float16)**
tensor(39.4835, dtype=torch.float64)
tensor(242.6674, dtype=torch.float64)
****************************************************************************************
****************************************************************************************
****************************************************************************************
In addition, all these weired things will not happen if we use float64 or set torch.backends.cuda.matmul.allow_tf32 = False.

Putting things together, the results seem correct on RTX 2080, while it outputs incorrect results in both environments on RTX 3080. I guess the precision is somehow lowered on RTX 3080, and it is not simply the same as using float16.

The errors are far more than that float32 should have, and the reason may be that some GPU implementations are not consistent with RTX 30XX. Hope you can rethink these issues and fix the problem.

(trya.npy and tryn.npy are in the attachment)

[Archive.zip](https://github.com/pytorch/pytorch/files/9460346/Archive.zip)

### Versions

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.1
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-191-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 3080
GPU 1: GeForce RTX 3080
GPU 2: GeForce RTX 3080
GPU 3: GeForce RTX 3080
GPU 4: GeForce RTX 3080
GPU 5: GeForce RTX 3080
GPU 6: GeForce RTX 3080
GPU 7: GeForce RTX 3080

Nvidia driver version: 460.56
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.3.1              h9edb442_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640    defaults
[conda] mkl-service               2.4.0            py38h95df7f1_0    conda-forge
[conda] mkl_fft                   1.3.1            py38h8666266_1    conda-forge
[conda] mkl_random                1.2.2            py38h1abd341_0    conda-forge
[conda] numpy                     1.23.1           py38h6c91a56_0    defaults
[conda] numpy-base                1.23.1           py38ha15fc14_0    defaults
[conda] pytorch                   1.10.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py38_cu113    pytorch
[conda] torchvision               0.11.0               py38_cu113    pytorch

**Comment by WhoTHU** [comment]
@ngimel

**Comment by ngimel** [comment]
This is exactly the error that you would expect from tf32 - only 1024 and 1025 are representable in fp16, and you are getting one of those numbers with fp16/tf32, the exact details depend on implementation in cublas.
In pytorch 1.12 tf32 is disabled by default.

**Comment by WhoTHU** [comment]
> This is exactly the error that you would expect from tf32 - only 1024 and 1025 are representable in fp16, and you are getting one of those numbers with fp16/tf32, the exact details depend on implementation in cublas. In pytorch 1.12 tf32 is disabled by default.

Thanks, but the point is that this problem only occurs on RTX3080, while not on RTX2080. It is more obvious in the second case, where the difference of the GPU and CPU results in Comparison 1 is (both set allow_tf32=True and using tf32)

RTX 3080, torch 1.10.0 OUTPUT:
tensor(0.3640)

RTX 3080, torch 1.7.1 OUTPUT:
tensor(4.3363e-05)

RTX 2080, torch 1.10.0 OUTPUT:
tensor(4.3363e-05)

In addition, in Comparison 2, all versions of the RTX3080 pytorch output a large number like 6.7663 while RTX2080 outputs 0.0315

The error on RTX 3080, torch 1.10.0 environment is exactly **MUCH LARGER** than one would expect from tf32 while in RTX2080 the error is respectable.

In fact, I located these bugs because I got a ridiculous and definitely wrong result from a function which uses torch.matmul and tf32 ONLY on RTX3080.

**Comment by ngimel** [comment]
RTX2080 doesn't support tf32, so the switch has no effect on it, so yes, it's expected that results would be more accurate on 2080 and less accurate (because of tf32) on 3080.

**Comment by WhoTHU** [comment]
Thanks a lot, my doubts are almost solved. It is really breaking news to me, meaning I need to turn off allow_tf32 and check all my results on 3080. Honestly, I found tf32 could result in numerous errors in some cases:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/20219437/187841281-58dceb87-a75a-4659-bedb-44eff88f52cf.png">

**Comment by ptrblck** [comment]
TF32 is disabled by default in PyTorch 1.12+ for matmuls so you won't need to disable it manually.

**Comment by WhoTHU** [comment]
> Thanks a lot, my doubts are almost solved. It is really breaking news to me, meaning I need to turn off allow_tf32 and check all my results on 3080. Honestly, I found tf32 could result in numerous errors in some cases:
> 
> <img alt="image" width="815" src="https://user-images.githubusercontent.com/20219437/187841281-58dceb87-a75a-4659-bedb-44eff88f52cf.png">

The two tensors are expected to be identical. This problem only occurs with pytorch 1.10.0 while not with pytorch 1.7.1 on the same device(RTX 3080). I guess there are some automatic rules to downgrade computation precision, and these rules are different between different versions.
