### ISSUE TITLE
Runtime Error raised by `torch._native_multi_head_attention` working with `torch.cuda.amp.autocast`

### ISSUE THREAD

**Issue by wjfwzzc** [pytorch/pytorch#84396]
### 🐛 Describe the bug

Minimal reproducing example:
```python
import torch
import torch.nn as nn

class NativeMHA(nn.Module):
    """
    Modified from https://github.com/pytorch/pytorch/blob/v1.12.1/test/test_native_mha.py#L144-L166
    """

    def __init__(self, embed_dim, num_heads, qkv, proj):
        super().__init__()
        self.qkv = qkv
        self.proj = proj
        self.embed_dim = embed_dim
        self.num_heads = num_heads

    def forward(
        self, q, k, v, key_padding_mask=None, need_weights=False, average_attn_weights=True
    ):
        return torch._native_multi_head_attention(
            q,
            k,
            v,
            self.embed_dim,
            self.num_heads,
            self.qkv.weight,
            self.qkv.bias,
            self.proj.weight,
            self.proj.bias,
            key_padding_mask,
            need_weights=need_weights,
            average_attn_weights=average_attn_weights,
        )

device = "cuda:0"
dtype = torch.float32
batch_size = 2
seq_length = 4
embed_dim = 16
num_heads = 4

qkv = torch.nn.Linear(embed_dim, 3 * embed_dim, device=device, dtype=dtype)
proj = torch.nn.Linear(embed_dim, embed_dim, device=device, dtype=dtype)
m = NativeMHA(embed_dim, num_heads, qkv, proj)
x = torch.rand(batch_size, seq_length, embed_dim, device=device, dtype=dtype)

m(x, x, x)  # everything is ok
with torch.autocast("cuda"):
    m(x, x, x)  # raise runtime error
```

Expected results:
```
RuntimeError: expected scalar type Half but found Float
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1016-gcp-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.4.152
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.141.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] open-clip-torch==1.3.0
[pip3] pytorchvideo==0.1.5
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect
```

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @bhosmer @cpuhrsch @erichan1 @mcarilli @ptrblck

**Comment by erichan1** [comment]
Fix landing https://github.com/pytorch/pytorch/pull/84722.

**Comment by erichan1** [comment]
Closing as this is solved (if you use nn.MultiheadAttention). Let me know if you have any questions on usage.

**Comment by rbracco** [comment]
Hi @erichan1, I am having a similar issue and have some questions on usage. When using `nn.MultiheadAttention` for self attention, when using fp16, I get the same error `expected scalar type Half but found Float`. The error doesn't occur when I don't use self-attention, so the issue must be limited to the special optimized implementation mentioned in the [nn.MultiheadAttention docs](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html). 

```python
# In my modules __init__
self.audio_self_attention = nn.MultiheadAttention(decoder_input_channels, num_heads=16, batch_first=True)
```
```python
# in my modules forward pass
`audio_attn_out, _ = self.audio_self_attention(audio_pos, audio_pos, audio_pos)` 
```
causes it to break during validation with the above Half/Float error, but since the optimized path is only taken when the query, key and value are all the same, I managed to hack it with `audio_attn_out, _ = self.audio_self_attention(audio_pos + 1e-16, audio_pos, audio_pos)` and that prevents it from failing. Any ideas how I might be misusing nn.MultiheadAttention? Thanks

**Comment by ToBeCodeCreater** [comment]
> Hi @erichan1, I am having a similar issue and have some questions on usage. When using `nn.MultiheadAttention` for self attention, when using fp16, I get the same error `expected scalar type Half but found Float`. The error doesn't occur when I don't use self-attention, so the issue must be limited to the special optimized implementation mentioned in the [nn.MultiheadAttention docs](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html).
> 
> ```python
> # In my modules __init__
> self.audio_self_attention = nn.MultiheadAttention(decoder_input_channels, num_heads=16, batch_first=True)
> ```
> 
> ```python
> # in my modules forward pass
> `audio_attn_out, _ = self.audio_self_attention(audio_pos, audio_pos, audio_pos)` 
> ```
> 
> causes it to break during validation with the above Half/Float error, but since the optimized path is only taken when the query, key and value are all the same, I managed to hack it with `audio_attn_out, _ = self.audio_self_attention(audio_pos + 1e-16, audio_pos, audio_pos)` and that prevents it from failing. Any ideas how I might be misusing nn.MultiheadAttention? Thanks

Meet this issue too. Have you solved this issue?

**Comment by rbracco** [comment]
I never really resolved it but I did come up with a hack. Adding an extremely small scalar to one of the values causes it to not take the optimized self attention route, but should be small enough that it doesn't change the math and is still self attention. In code...

`audio_attn_out, _ = self.audio_self_attention(audio_pos+1e-8, audio_pos, audio_pos)`
