### ISSUE TITLE
Exporting the operator ::col2im to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by lws6885** [pytorch/pytorch#84408]
### 🐛 Describe the bug

When I converted the model in “.pt” format to onnx format, I received an error that the operator col2im is not supported.

## code

    import torch
    from cvnets import get_model
    from options.opts import get_segmentation_eval_arguments
    
    def pt2onnx():
        opts = get_segmentation_eval_arguments()
        model = get_model(opts)
        model.eval()
        onnx_save_path = "model/mobilevit.onnx"
        in_data = torch.randn(1, 3, 512, 512)
        torch.onnx.export(model, 
                          in_data, 
                          onnx_save_path, 
                          opset_version=11, 
                          do_constant_folding=True, 
                          input_names=["in"],
                          output_names=["out"])
        return

    if __name__ == '__main__':
        pt2onnx()

## error
Traceback (most recent call last):
  File "/home/sunseeker/project/robot_seg/code/mobilevit_seg/demo.py", line 20, in <module>
    pt2onnx()
  File "/home/sunseeker/project/robot_seg/code/mobilevit_seg/demo.py", line 13, in pt2onnx
    torch.onnx.export(model, in_data, onnx_save_path, opset_version=11, do_constant_folding=True, input_names=["in"],
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/utils.py", line 731, in _model_to_graph
    graph = _optimize_graph(
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/utils.py", line 308, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/__init__.py", line 416, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/anaconda3/envs/mobilevit/lib/python3.10/site-packages/torch/onnx/utils.py", line 1421, in _run_symbolic_function
    raise symbolic_registry.UnsupportedOperatorError(
**torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::col2im to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.**

## ENV
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-47-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050
Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] pytorchvideo==0.1.5
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.1          py310h1794996_0  
[conda] numpy-base                1.23.1          py310hcba007f_0  
[conda] pytorch                   1.12.1          py3.10_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorchvideo              0.1.5                    pypi_0    pypi
[conda] torchaudio                0.12.1              py310_cu102    pytorch
[conda] torchvision               0.13.1              py310_cu102    pytorch

**Comment by AllenTiTaiWang** [comment]
cc @thiagocrepaldi

**Comment by thiagocrepaldi** [comment]
Col2Im was just added to onnx spec (opset 18) at https://github.com/onnx/onnx/pull/3948
Now we can add this to pytorch as well. Will work on it

**Comment by thiagocrepaldi** [comment]
@lws6885 do I need to install to get access to

```python
from cvnets import get_model
from options.opts import get_segmentation_eval_arguments
```

**Comment by lws6885** [comment]
> @lws6885 do I need to install to get access to
> 
> ```python
> from cvnets import get_model
> from options.opts import get_segmentation_eval_arguments
> ```
> 
> If this is your code, I need it to repro on my end

Please refer to https://github.com/apple/ml-cvnets.

**Comment by lws6885** [comment]
> 

I try to write a symbolic function to map to ONNX op, but I can't find the definition of col2im in torch.

**Comment by lws6885** [comment]
> Col2Im was just added to onnx spec (opset 18) at [onnx/onnx#3948](https://github.com/onnx/onnx/pull/3948) Now we can add this to pytorch as well. Will work on it

I try to write a symbolic function to map to ONNX op, but I can't find the definition of col2im in torch.

**Comment by thiagocrepaldi** [comment]
I have implemented col2im for pytorch and it should be merged soon. However, this repro seems to be incomplete

```bash
$/dev/github/vision/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
2022-09-27 17:46:58 - ERROR   - Specified None. Supported models are:
         0: resnet
         1: mobilenetv1
         2: mobilenetv2
         3: mobilevit
         4: mobilevit_v2
         5: vit
         6: mobilenetv3
2022-09-27 17:46:58 - ERROR   - Exiting!!!
```

After some debugging, `model.classification.name==None` inside `opts`

**Comment by thiagocrepaldi** [comment]
You can validate on your end. To do so, 

* clone the PR https://github.com/pytorch/pytorch/pull/84594
* cd into third-party/onnx and git checkout main
* build pytorch and you normally would, but do not do git pull after changing onnx submodule to point to main
