### ISSUE TITLE
Wrong output in constraints check for positive definite matrix

### ISSUE THREAD

**Issue by Rik-ad-astra** [pytorch/pytorch#84417]
### 🐛 Describe the bug

Hi all, I am summing two matrices both positive definite, and checking that the sum is still positive definite according to the function _constraints.positive_definite_ in _constraints.py_. In theory the sum should be positive definite. However, the aforementioned function output a different result. I am attaching my code below, in which I show that the original matrices are positive definite according to _constraints_, but their sum is not, and I don't understand why this is happening. Can you please tell me if I am missing something, or if there is something wrong in the computation. Thank you in advance for your help
```
import numpy as np

import torch
import torch.distributions as dist
mvn = dist.multivariate_normal.MultivariateNormal

c = np.array([3.634745180606842041e-01,1.802540756762027740e-02,5.221439525485038757e-02,1.396142542362213135e-01,1.002049744129180908e-01,1.177366077899932861e-01,8.187864720821380615e-02,-2.091059684753417969e+00,-2.589471817016601562e+00,
1.802540756762027740e-02,1.060681104660034180e+00,6.848397254943847656e-01,1.184293746948242188e+00,3.827690780162811279e-01,3.538790345191955566e-01,3.412145078182220459e-01,2.564693212509155273e+00,5.358704566955566406e+00,
5.221439525485038757e-02,6.848397254943847656e-01,1.231363773345947266e+00,1.474114537239074707e+00,5.011656880378723145e-01,5.897534489631652832e-01,5.976498126983642578e-01,-2.910419464111328125e+00,2.011136293411254883e+00,
1.396142542362213135e-01,1.184293746948242188e+00,1.474114537239074707e+00,4.004963874816894531e+00,9.183990955352783203e-01,1.262631058692932129e+00,1.248939394950866699e+00,-8.187579154968261719e+00,3.931109189987182617e+00,
1.002049744129180908e-01,3.827690780162811279e-01,5.011656880378723145e-01,9.183990955352783203e-01,6.224450469017028809e-01,8.960403203964233398e-01,7.784516215324401855e-01,-7.009478569030761719e+00,-1.994250893592834473e+00,
1.177366077899932861e-01,3.538790345191955566e-01,5.897534489631652832e-01,1.262631058692932129e+00,8.960403203964233398e-01,1.711319088935852051e+00,1.443797707557678223e+00,-1.831859970092773438e+01,-8.436774253845214844e+00,
8.187864720821380615e-02,3.412145078182220459e-01,5.976498126983642578e-01,1.248939394950866699e+00,7.784516215324401855e-01,1.443797588348388672e+00,1.290309548377990723e+00,-1.606516075134277344e+01,-6.958739280700683594e+00,
-2.091059684753417969e+00,2.564693212509155273e+00,-2.910419464111328125e+00,-8.187578201293945312e+00,-7.009478569030761719e+00,-1.831859779357910156e+01,-1.606516075134277344e+01,1.708479858398437500e+03,1.220272949218750000e+03,
-2.589471817016601562e+00,5.358704566955566406e+00,2.011136531829833984e+00,3.931108951568603516e+00,-1.994251012802124023e+00,-8.436773300170898438e+00,-6.958739280700683594e+00,1.220272949218750000e+03,1.807371215820312500e+03])

n = np.array([3.113843267783522606e-04,6.096098331909161061e-06,9.708651305118110031e-06,1.492697447247337550e-05,2.397008756815921515e-05,-4.230576087138615549e-05,-4.493505985010415316e-04,-3.333870172500610352e+00,-1.129504442214965820e+00,
6.096098331909161061e-06,2.047196758212521672e-04,7.677515895920805633e-06,1.180412073154002428e-05,1.895533387141767889e-05,-3.345502045704051852e-05,-3.553424903657287359e-04,-2.636395215988159180e+00,-8.932021856307983398e-01,
9.708651305118110031e-06,7.677515895920805633e-06,1.041456474922597408e-03,1.879925002867821604e-05,3.018827919731847942e-05,-5.328048791852779686e-05,-5.659186863340437412e-04,-4.198724746704101562e+00,-1.422514438629150391e+00,
1.492697447247337550e-05,1.180412073154002428e-05,1.879925002867821604e-05,8.634827099740505219e-03,4.641424311557784677e-05,-8.191834058379754424e-05,-8.700956241227686405e-04,-6.455507278442382812e+00,-2.187104701995849609e+00,
2.397008756815921515e-05,1.895533387141767889e-05,3.018827919731847942e-05,4.641424311557784677e-05,2.060916461050510406e-02,-1.315464032813906670e-04,-1.397219952195882797e-03,-1.036640453338623047e+01,-3.512104749679565430e+00,
-4.230576087138615549e-05,-3.345502045704051852e-05,-5.328048791852779686e-05,-8.191834058379754424e-05,-1.315464032813906670e-04,7.221189886331558228e-02,2.466008998453617096e-03,1.829607963562011719e+01,6.198652744293212891e+00,
-4.493505985010415316e-04,-3.553424903657287359e-04,-5.659186863340437412e-04,-8.700956241227686405e-04,-1.397219952195882797e-03,2.466008998453617096e-03,2.537523508071899414e-01,1.943317871093750000e+02,6.583898162841796875e+01,
-3.333870172500610352e+00,-2.636395215988159180e+00,-4.198724746704101562e+00,-6.455507278442382812e+00,-1.036640453338623047e+01,1.829607963562011719e+01,1.943317871093750000e+02,1.449933750000000000e+06,4.884796875000000000e+05,
-1.129504442214965820e+00,-8.932021856307983398e-01,-1.422514438629150391e+00,-2.187104701995849609e+00,-3.512104749679565430e+00,6.198652744293212891e+00,6.583898162841796875e+01,4.884796875000000000e+05,5.640109375000000000e+05])

noise = torch.from_numpy(n.reshape(9,9))

covar = torch.from_numpy(c.reshape(9,9))

noisy_covar = covar + noise

print(dist.constraints.positive_definite.check(noise))
print(dist.constraints.positive_definite.check(covar))
print(dist.constraints.positive_definite.check(noisy_covar))
```

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] gpytorch==1.6.0
[pip3] numpy==1.22.3
[pip3] numpyro==0.9.2
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.11.0
[pip3] torchmetrics==0.9.0
[pip3] torchvision==0.12.0
[pip3] xitorch==0.3.0
[conda] gpytorch                  1.6.0                    pypi_0    pypi
[conda] nomkl                     1.0                  h5ca1d4c_0    conda-forge
[conda] numpy                     1.22.3           py39h18676bf_0    conda-forge
[conda] numpyro                   0.9.2                    pypi_0    pypi
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchmetrics              0.9.0                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi
[conda] xitorch                   0.3.0                    pypi_0    pypi

cc @fritzo @neerajprad @alicanb @nikitaved @jianyuh @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by fritzo** [comment]
Note that `constraints.positive_definite` has to choose a threshold and will necessarily make errors near the boundary of floating point precision.  Thus my guess is that your two matrices just barely violate the threshold.  You could look at their eigenvalues.

**Comment by Lezcano** [comment]
The issue here is that, due to precision errors, the resulting matrix of the sum is not exactly symmetric. If you symmetrise it, the test passes:
```python
>>> print(dist.constraints.positive_definite.check(0.5 * (noisy_covar + noisy_covar.mT))) 
True
```

**Comment by Rik-ad-astra** [comment]
Hey Mario and Fritz, thanks for your help. It seems indeed that there is a precision error and the sum matrix is not exactly symmetric. Now I am able to solve the issue. Thanks again
