### ISSUE TITLE
[Quant] Unit test 'TestQuantizedConv.test_qconv_transpose1d' fails randomly

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#84458]
### 🐛 Describe the bug

The unit test 'TestQuantizedConv.test_qconv_transpose1d' fails randomly on x86 CPU.
For this UT, only QNNPACK backend is used. This quantization backend is intended for ARM devices. But it looks like this UT is also run on other devices for CI. And I don't have ARM devices to run PyTorch. I am not sure if this bug can be reproduced on such devices. Could you please check if it's a bug in QNNPACK?

**How to reproduce**
Run the UT for multiple times. For example
```shell
for i in `seq 10`; do python test_quantization.py TestQuantizedConv.test_qconv_transpose1d; done
```

### Versions

PyTorch version: 1.13.0a0+git0909639
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.5
Libc version: glibc-2.31

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-27-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.13.0+cpu
[pip3] numpy==1.23.1
[pip3] pytorch-widedeep==0.3.7
[pip3] torch==1.13.0a0+git0909639
[pip3] torchvision==0.14.0a0+56fb841
[conda] blas                      1.0                         mkl
[conda] intel-extension-for-pytorch 1.13.0+cpu               pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.1.0                 pypi_0    pypi
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl-static                2022.1.0                 pypi_0    pypi
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] numpy-base                1.22.3           py39hf524024_0
[conda] torch                     1.13.0a0+git0909639          pypi_0    pypi
[conda] torchvision               0.14.0a0+56fb841          pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by andrewor14** [comment]
Hi @Xia-Weiwen, do you have the error message and the stack trace?

**Comment by Xia-Weiwen** [comment]
Fixed via https://github.com/pytorch/pytorch/pull/85463
