### ISSUE TITLE
Import TensorRT make ArrayRef iterator failed on Windows

### ISSUE THREAD

**Issue by grimoire** [pytorch/pytorch#84457]
### 🐛 Describe the bug

I am not sure whether I should report it here or to the TensorRT team.

Import tensorrt **after** torch would failed the iterator `graph.inputs()` and `graph.nodes()` on Windows.

```python
import torch
import tensorrt

graph = torch._C.Graph()
graph.addInput()

for i in graph.inputs():
    print(i)

print('finish')
```

the `print('finish')` will never been reached.
If we swap the import, the bug would disappear.
It is even weirder if we import some other module such as `mmcv._ext` or `onnxruntime`(CUDA version only). The bug would be fixed too.

### Versions

Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti
Nvidia driver version: 512.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0+cu111
[conda] numpy                     1.23.2                   pypi_0    pypi
[conda] torch                     1.8.0+cu111              pypi_0    pypi
[conda] torchaudio                0.8.0                    pypi_0    pypi
[conda] torchvision               0.9.0+cu111              pypi_0    pypi

TensorRT version:
TensorRT-8.2.3.0.cuda-11.4.cudnn8.2

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ezyang** [comment]
Try upgrading the versions of the software you're using

**Comment by grimoire** [comment]
Also failed on:
```
PyTorch: 1.11.0+cuda11.3
TensorRT: 8.2.4.2
```

and 

```
PyTorch: 1.12.1+cuda11.3
TensorRT: 8.4.3.1
```

**Comment by cristianPanaite** [comment]
Hello!

The bug is still present with the following versions: 

`PyTorch: 1.13.1`
`TensorRT: 8.5.2.2`

**Comment by mantaionut** [comment]
TensorRT crashes when an exception is thrown in another module, thats why changing the import order fixes the issue. 
The crash seems similar to this issue https://github.com/onnx/onnx/issues/3493. 
TensorRT also crashes when using a simple pybind example https://github.com/pybind/python_example when changing the code to throw an exception.
Because of that I opened an issue in TensorRT https://github.com/NVIDIA/TensorRT/issues/2853 and I will close this one .
