### ISSUE TITLE
A little improvement to torch.nn.ReflectionPad2d

### ISSUE THREAD

**Issue by MarioGalindoQ** [pytorch/pytorch#84487]
### 🚀 The feature, motivation and pitch

A little improvement, so little that I think it does not deserve to post about my intended feature and later discuss the design and implementation. Probably you can consider this little extension directly.

torch.nn.ReflectionPad2d is limited to pad to a new size less than or equal to the double of the original size.

I want to propose a new MultipleReflectionPad2d without this limitation.

```
class MultipleReflectionPad2d():
    def __init__(self, out_height, out_width):
        self.out_height = out_height
        self.out_width  = out_width
    def __call__(self, image):
        height, width = image.shape[-2:]
        while height<self.out_height or width<self.out_width:
            new_height = self.out_height
            new_width  = self.out_width
            if new_height > 2*height : new_height = 2*height
            if new_width  > 2*width  : new_width  = 2*width
            padding_top    = (new_height-height)//2
            padding_bottom = new_height-height-padding_top
            padding_left   = (new_width-width)//2
            padding_right  = new_width-width-padding_left
            padder = torch.nn.ReflectionPad2d((padding_left, padding_right, padding_top, padding_bottom))
            image  = padder(image)
            height, width = image.shape[-2:]
        return image
```

### Alternatives

May be you can rewrite ReflectionPad2d without this limitation

cc @ezyang @soumith

**Comment by ezyang** [comment]
We're unlikely to add a dedicated kernel for this, but when we get further along we should try feeding your code to inductor and see if you get good perf that way

**Comment by ydwu4** [comment]
Closed this for now. Feel free to re-open if needed.
