### ISSUE TITLE
[ONNX] Enable export_modules_as_functions tests

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#84490]
Some simple model fails export when `export_modules_as_functions=True`. We should run a pass of the unit tests setting `export_modules_as_functions=True`

**Comment by AllenTiTaiWang** [comment]
Could you provide more context on this? If you are not self-assigned?

**Comment by BowenBao** [comment]
Might be a good start to parameterize `test_pytorch_onnx_onnxruntime.py` tests with `export_modules_as_functions`. Maybe enable only on one opset version in CI to not tax us too much. I have a local branch that does some of these, can start from there if needed.
