### ISSUE TITLE
Embedding scale_grad_by_freq should probably shrink by sqrt(count)

### ISSUE THREAD

**Issue by calvinmccarter** [pytorch/pytorch#84491]
Given the analysis and experiments in "Frequency-aware SGD for Efficient Embedding Learning with Provable Benefits" (https://openreview.net/pdf?id=ibqTBNfJmi), it would seem that it would be better for `scale_grad_by_freq` to divide by sqrt(count) rather than count.

https://github.com/pytorch/pytorch/blob/0a07488ed2c47765e337e290bd138c0e6e459cbd/aten/src/ATen/native/Embedding.cpp#L133

Also, what is the reason for initializing the counter to zeros, then incrementing by 1 [here](https://github.com/pytorch/pytorch/blob/0a07488ed2c47765e337e290bd138c0e6e459cbd/aten/src/ATen/native/Embedding.cpp#L120), rather than initializing to 1?

cc @ezyang @soumith

**Comment by ezyang** [comment]
We probably can't easily change the behavior under this config; but it should be easy to rejigger our embedding decomposition with the modified behavior https://github.com/pytorch/pytorch/blob/f803fa9fc94ea7e744885926f654479e578850cf/torch/_decomp/decompositions.py#L818-L841 and then send it to a compiler like inductor

**Comment by ydwu4** [comment]
Closed for now. Feel free to reopen it if needed.
