### ISSUE TITLE
The distributed setting call in data loader constructor is invalid

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#84492]
### 🐛 Describe the bug

In the following data loader constructor for IterDataPipe (torchdata) dateset, it calls the `_get_distributed_settings` to get the world_size and rank. While in general, the process group is not yet initialized when the data loader constructor is called in the main process. So it will just return ws=1 and rank=0.

Should we put the dist call within the `_sharding_worker_init_fn` when the process group is already initialized? 

```
        if isinstance(self.dataset, IterDataPipe):
            self.dataset = _IterDataPipeSerializationWrapper(self.dataset)
            ws, rank = _get_distributed_settings()
            if num_workers > 0:
                self.worker_init_fn = functools.partial(
                    _sharding_worker_init_fn, self.worker_init_fn, ws, rank)
            else:
                torch.utils.data.graph_settings.apply_sharding(self.dataset, ws, rank)
```

### Versions

```
>>> import torch
>>> torch.__version__
'1.12.0+cu113'
```
cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @SsnL @VitalyFedyunin @ejguan @NivekT @asaluja

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by H-Huang** [comment]
cc @VitalyFedyunin @ejguan @NivekT for this data loader specific `_sharding_worker_init_fn()` question.

**Comment by ejguan** [comment]
> While in general, the process group is not yet initialized when the data loader constructor is called in the main process. So it will just return ws=1 and rank=0.

I don't agree. Your distributed process group should be initialized by that time. It behaves the same as the old `Dataset` with `DistributedSampler`. You need to create process group first in each distributed process.

> Should we put the dist call within the `_sharding_worker_init_fn` when the process group is already initialized?

Nope. `_sharding_worker_init_fn` is used in the worker (sub) process from DataLoader. And, without multiple workers, the `DataPipe` won't be distributed sharded.

**Comment by lly-zero-one** [comment]
Thanks for the reply.

For 1:
Yes, right as long as we can initialize the process group first. I was just thinking whether it can accommodate different user code. Here is the example from the[ pytorch-lightning example](https://pytorch-lightning.readthedocs.io/en/latest/notebooks/lightning_examples/mnist-hello-world.html). If we add the DDP strategy to the Trainer constructor, user can easily trigger this kind of issue, since the process group initialization is done in the underlying API.

// Init our model
mnist_model = MNISTModel()

// Init DataLoader from MNIST Dataset
train_ds = MNIST(PATH_DATASETS, train=True, download=True, transform=transforms.ToTensor())
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE)

// Initialize a trainer
trainer = Trainer(
    accelerator="auto",
    devices=1 if torch.cuda.is_available() else None,  # limiting got iPython runs
    max_epochs=3,
    callbacks=[TQDMProgressBar(refresh_rate=20)],
)

// Train the model
trainer.fit(mnist_model, train_loader)`

For 2:
The CPU data worker process should still have the access to the global number of data workers, worker_id, and rank_id as follows. So the apply_sharding should be fine?  

https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L102

**Comment by ejguan** [comment]
> If we add the DDP strategy to the Trainer constructor and plug in the torchdata, user can easily trigger this kind of issue, since the process group initialization is done in the underlying API after the dataloader constructor call.

I am not familiar with lightning. Curious about how are you going to add `DistributedSampler` to `DataLoader`? It also assumes the distributed process has been initialized. https://github.com/pytorch/pytorch/blob/ac364f8ba1a20484d118362bcc11b5730dec676a/torch/utils/data/distributed.py#L65-L72

> For multi-worker case, it might be better to raise some exception/warning to user if the process group is not initialized? or we can call the dist function within worker process to confirm.

IIRC, worker process (child process spawned from the main process) won't be able to know the distributed process group. So, we can't do that.

**Comment by ejguan** [comment]
One option might be moving the distributed call to the constructor of DataLoaderIterator.

**Comment by lly-zero-one** [comment]
Thanks. We are actually using the iterable-style dataset, so there is no sampler. 

For the data worker process calling distributed process group, it actually works in our following quick workaround. Not sure we are trying the same thing.

```
def _sharding_worker_init_fn(worker_init_fn, world_size, rank_id, worker_id):
    world_size = dist.get_world_size()
    rank_id = dist.get_rank()
    global_worker_id = worker_id
    info = torch.utils.data.get_worker_info()
    total_workers = info.num_workers
    datapipe = info.dataset
```

**Comment by ejguan** [comment]
> For the data worker process calling distributed process group, it actually works in our following quick workaround. Not sure we are trying the same thing.

Try using `spawn` as the starting method. You will find the problem

**Comment by lly-zero-one** [comment]
That's actually not directly controlled by user. I think DDP is using the spawn by default (https://pytorch.org/tutorials/intermediate/ddp_tutorial.html), and it has access to rank information, etc in each process. Also in the lightning, it uses the start_method=`spawn`. https://github.com/Lightning-AI/lightning/blob/d2459df2ff79184c596b2f5c865ffb17c3541307/src/pytorch_lightning/strategies/ddp_spawn.py#L83

**Comment by ejguan** [comment]
I was talking about the starting method for `DataLoader`. If `spawn` is used, the worker process won't be able to access the distributed process group inside `worker_init_fn`.

There might be a solution to cover your use case -> Move distributed communication until `DataLoaderIterator` is created.

**Comment by lly-zero-one** [comment]
Just to be clear, I also tried multiprocessing_context="spawn" in data loader, both seems to be fine to me. We could use some ways to make it work like what you proposed. I think the initial question is whether we could remove this kind of assumption to user code and accommodate different cases.

**Comment by ejguan** [comment]
@lly-zero-one The PR has been merged. Could you please give it a try using PyTorch nightly release?
