### ISSUE TITLE
Typo in torch/package/_mock.py

### ISSUE THREAD

**Issue by terri1102** [pytorch/pytorch#84507]
### 🐛 Describe the bug

Spot a typo in torch/package/_mock.py

* MockedOject -> MockedObject

https://github.com/pytorch/pytorch/blob/7f5da70ef0be0d3fa60d92430548d2fff6f93ef9/torch/package/_mock.py#L92

### Versions

Version is not needed for this typo fix

**Comment by H-Huang** [comment]
Approved PR and am merging
