### ISSUE TITLE
latest libtorch debug error 1.12.1 

### ISSUE THREAD

**Issue by gellston** [pytorch/pytorch#84521]
### 🐛 Describe the bug

Hi libtorch team

I am really struggling to figure out what is the problem .

```cpp
torch::Tensor a = torch::rand({ 1, 4 });
torch::Tensor b = torch::rand({ 1, 4 });
std::cout << " a = " << a << std::endl;
std::cout << " b = " << b << std::endl;
torch::Tensor c = torch::stack({ a, b }, 0);
std::cout << " c = " << c << std::endl;
```

![image](https://user-images.githubusercontent.com/42884297/188294364-30078cf7-6890-4aef-bcb9-96b73cacf3be.png)

I am using new version of library 
![image](https://user-images.githubusercontent.com/42884297/188294728-ee300242-6506-4206-b6ca-867fb6b20950.png)

Environment
OS : Windows10
Cuda : 11.6 
![image](https://user-images.githubusercontent.com/42884297/188294782-fcaf38e1-a8f6-45f6-a769-ddece0b7f680.png)

mini Dump file
[console.zip](https://github.com/pytorch/pytorch/files/9483759/console.zip)

Stack trace

Unfortunately, no special information
![image](https://user-images.githubusercontent.com/42884297/188295485-fb57dcae-a55f-40ee-b5ae-5bc8c3aca3dc.png)

please help me to find issue, or can you reproduce ? download library from official website ( 1.12.1) and run same code in clean PC? 

Thanks. 

### Versions

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.11.0+cu113
[pip3] torch-utils==0.1.2
[pip3] torchaudio==0.11.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

its not helpful but.... 

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser

**Comment by mszhanyi** [comment]
could you please check out https://github.com/pytorch/pytorch/wiki/Best-Practices-to-Edit-and-Compile-Pytorch-Source-Code-On-Windows
or 
try setting your project with the extension
https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001

**Comment by gellston** [comment]
@mszhanyi  sorry, i was busy , Let me try thanks
btw, does it support 1.12 latest version of pytorch?

**Comment by mszhanyi** [comment]
> @mszhanyi sorry, i was busy , Let me try thanks btw, does it support 1.12 latest version of pytorch?

Yes, it does

**Comment by JustKeepSilence** [comment]
@gellston 
yeah, I have encountered the same error on windows, but on debian everything is ok
and after downgrading torch version to 1.8.2 on windows, everything is ok

**Comment by gellston** [comment]
@JustKeepSilence 
yes, you are right, also i tested it 1.11.0+cu113, it works too

**Comment by gellston** [comment]
currently i downgraded pytorch version and libtorch to 1.11.0+cu113 but ... i want to know root cause .
