### ISSUE TITLE
[Nested Tensor] Indexing does not work in a nestedtensor with requires_grad=True

### ISSUE THREAD

**Issue by Acciorocketships** [pytorch/pytorch#84556]
### 🐛 Describe the bug

```python
x = torch.nested_tensor([torch.rand(1,2,requires_grad=True), torch.rand(2,2,requires_grad=True)])
x[0]
```
RuntimeError: Internal error: NestedTensorImpl doesn't support sizes. Please file an issue on https://github.com/pytorch/nestedtensor

### Versions

1.13.0.dev20220905

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
related to #83875

**Comment by mikaylagawarecki** [comment]
The snippet should now work on the 1.13.0.dev20220905 nightly :)
