### ISSUE TITLE
Update dist.scatter() documentation to provide clearer arg description

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#84566]
### 📚 The doc issue

https://pytorch.org/docs/master/distributed.html#torch.distributed.scatter documentation does not specify that scatter_list tensors must have same sizes.

Example:

```python
import torch
import torch.distributed as dist
import os
import torch.multiprocessing as mp

os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "29500"
os.environ["TORCH_SHOW_CPP_STACKTRACES"] = "1"

def work(rank, world_size):
    dist.init_process_group("gloo", rank=rank, world_size=world_size)
    print("finished creating process group")
    t_13 = torch.zeros(13)
    t_6 = torch.zeros(6)
    output_tensor = torch.zeros(13)
    if rank == 0:
        dist.scatter(output_tensor, [t_13, t_6])
    else:
        dist.scatter(output_tensor)
    print(f"rank {rank} - {output_tensor=}")

if __name__ == "__main__":
    world_size = 2
    mp.spawn(work, nprocs=world_size, args=(world_size,))
```

error:

```
RuntimeError: ProcessGroupGloo::scatter: invalid tensor size at index 1 (expected (13), got (6))
```

### Suggest a potential alternative/fix

We should also include an example usage of scatter in the documentation.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @kwen2501

**Comment by adit299** [comment]
I'm new to open source, and I feel this would be a good first issue for me to tackle

**Comment by adit299** [comment]
If someone could assign this issue to me, I would appreciate it as well.
