### ISSUE TITLE
Unnecessary uses of `copy_to` in refs implementations

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#84561]
### 🐛 Describe the bug

Many operations, for example `linalg.vector_norm`, use `x = prims.convert_element_type(x, computation_dtype)`. This unconditionally calls to `copy_to`. We should instead use `x = _maybe_convert_to_dtype(x, computation_dtype)`

### Versions

master

cc @ezyang @mruberry @ngimel

**Comment by ngimel** [comment]
@lezcano did we fix all `copy_to` patterns, or do some remain?

**Comment by lezcano** [comment]
I'd hope https://github.com/pytorch/pytorch/pull/85163 fixed all of them, but @mruberry was the main reviewer on that one, so he may have a better perspective.

**Comment by lezcano** [comment]
Do you have any particular concern?

**Comment by ngimel** [comment]
No, I don't, I was wondering if we have any unneeded `copy_to`'s coming not from dtype conversions.

**Comment by lezcano** [comment]
That may very well be the case, but if there are, there's none I'm aware of. This issue mostly concerned dtype conversions. Alas, the title was not the clearest it could have been, sorry for that.
