### ISSUE TITLE
I use pytorch1.8.0 getting error like THPVariable_Check INTERNAL ASSRT FAILED "/pytorch/torch/csrc/jit/passed/onnx/shape_type_inference.cpp":657

### ISSUE THREAD

**Issue by Aracher** [pytorch/pytorch#84562]
### 🐛 Describe the bug

THPVariable_Check INTERNAL ASSRT FAILED "/pytorch/torch/csrc/jit/passed/onnx/shape_type_inference.cpp":657

### Versions

torch1.8.0 
onnx 1.12.0
onnx_runtime 1.10.0

**Comment by justinchuby** [comment]
Please consider using the latest version of pytorch. We are unable to support torch.onnx in older versions
