### ISSUE TITLE
Sparse / dense tensors .mul operation inconsistency

### ISSUE THREAD

**Issue by Emvlt** [pytorch/pytorch#84574]
### 🐛 Describe the bug

I'm running into an inconsistent behaviour for the mul operation between sparse coo tensor and dense tensor.

**The code**
```
import torch 

input_tensor = torch.ones((1,1,512,512))

sparse = torch.sparse_coo_tensor(size=(1,10,512,512))

dense  = torch.zeros((1,10,512,512))

print(input_tensor.mul(dense).size())

print(input_tensor.mul(sparse).size())
```
**The error message**
Traceback (most recent call last):
  File "misc.py", line 11, in <module>
    print(input_tensor.mul(sparse).size())
RuntimeError: mul operands have incompatible sizes

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.5.50
GPU models and configuration: GPU 0: NVIDIA RTX A3000 Laptop GPU
Nvidia driver version: 512.36
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.4.0
[pip3] torch==1.10.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py38h2bbff1b_0
[conda] mkl_fft                   1.3.1            py38h277e83a_0
[conda] mkl_random                1.2.2            py38hf11a4ad_0
[conda] numpy                     1.21.5           py38h7a0a035_3
[conda] numpy-base                1.21.5           py38hca35cd5_3
[conda] numpydoc                  1.4.0            py38haa95532_0
[conda] pytorch                   1.10.0          py3.8_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                0.10.0               py38_cu113    pytorch
[conda] torchvision               0.11.1               py38_cu113    pytorch

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by nikitaved** [comment]
Hey, @Emvlt ! `mul(sparse, dense)` is not implemented in PyTorch 1.10. This feature was implemented in https://github.com/pytorch/pytorch/pull/82962. If you need this operation, I recommend trying a nightly build or wait for the next release.

**Comment by nikitaved** [comment]
It will work with a build that has `mul` between sparse and dense support. But are you sure you do the right thing? `sparse = torch.sparse_coo_tensor(size=(1,10,512,512))` will create an empty tensor which, if converted to dense, will be a zero tensor.

**Comment by Emvlt** [comment]
That sounds great! I'll keep an eye on the releases
As for the tensor values, it was just an example: in my case ```sparse``` will be a tensor with meaningful values :) 
Keep up with the great work! I'd be happy to contribute if i knew any c++ lol

**Comment by nikitaved** [comment]
Thank you, @Emvlt , for your kind words. Sparse tensors have recently become higher in priority, so it is being actively improved/developed. Stay tuned :)
