### ISSUE TITLE
out= not correct in narrow_copy and avg_pool3d operators when out tensor is not contiguous

### ISSUE THREAD

**Issue by srossross** [pytorch/pytorch#84577]
### 🐛 Describe the bug

`out=` argument is not correct in some operators when out tensor is not contiguous. 

In the following examples, I'm using `torch.zeros([i*2 for i in expected.shape])[::2,::2]` to create a tensor that is not contiguous whereas if I use `torch.zeros_like(expected)` these examples behave correctly:

### `nn.functional.avg_pool3d`:

```py
In [1]: import torch

In [2]: t = torch.arange(2*3*3*4*4.0).reshape(2, 3, 3, 4, 4)

In [3]: expected = torch.nn.functional.avg_pool3d(t, (2,2,2))

In [4]: in_place = torch.zeros([i*2 for i in expected.shape], dtype=expected.dtype)[::2,::2,::2,::2,::2]

In [5]: torch.nn.functional.avg_pool3d(t, (2,2,2), out=in_place)
Out[5]: 
tensor([[[[[ 10.5000,  18.5000],
           [106.5000, 114.5000]]],

         [[[  0.0000,   0.0000],
           [  0.0000,   0.0000]]],

         [[[  0.0000,   0.0000],
           [  0.0000,   0.0000]]]],

        [[[[  0.0000,   0.0000],
           [  0.0000,   0.0000]]],

         [[[  0.0000,   0.0000],
           [  0.0000,   0.0000]]],

         [[[  0.0000,   0.0000],
           [  0.0000,   0.0000]]]]])

In [6]: expected
Out[6]: 
tensor([[[[[ 10.5000,  12.5000],
           [ 18.5000,  20.5000]]],

         [[[ 58.5000,  60.5000],
           [ 66.5000,  68.5000]]],

         [[[106.5000, 108.5000],
           [114.5000, 116.5000]]]],

        [[[[154.5000, 156.5000],
           [162.5000, 164.5000]]],

         [[[202.5000, 204.5000],
           [210.5000, 212.5000]]],

         [[[250.5000, 252.5000],
           [258.5000, 260.5000]]]]])

```

### `narow_copy`:

```py
In [1]: import torch

In [2]: t = torch.arange(5*5.0).reshape(5,5)

In [3]: expected = t.narrow_copy(1, 2, 2)

In [4]: in_place = torch.zeros([i*2 for i in expected.shape])[::2,::2]

In [5]: torch.narrow_copy(t, 1, 2, 2, out=in_place)
Out[5]: 
tensor([[ 2.,  7.],
        [22.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]])

In [6]: expected
Out[6]: 
tensor([[ 2.,  3.],
        [ 7.,  8.],
        [12., 13.],
        [17., 18.],
        [22., 23.]])
```

discovered when I went to open this PR https://github.com/pytorch/pytorch/pull/84498

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+gitd62a6ca
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.27

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.3.0a0+9b361de
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] torch==1.13.0a0+gitae67099
[conda] functorch                 0.3.0a0+9b361de           dev_0    <develop>
[conda] magma-cuda117             2.6.1                         1    pytorch
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.2           py38h3a7f9d9_0    conda-forge
[conda] torch                     1.13.0a0+gitae67099           dev_0    <develop>

**Comment by mruberry** [comment]
This is true, but the issue was already known because of the xfails in our test suite. Maybe this issue could create a bullet-point list of the operators that don't handle non-contiguous `out=` tensors properly, so engineers don't have to scan the xfails in the code?

**Comment by srossross** [comment]
I can confirm that it is only these two operators `narrow_copy` and `avg_pool3d`

@amjames suggested I do a guard rather than fix the issue - It was the consensus that `out=` is not a large priority.

should I add a check like this to help any users if they run into this issue?:

```c++
TORCH_CHECK(output.is_contiguous(), "narrow_copy() out= must be contiguous");
```

**Comment by mruberry** [comment]
Erroring is better than producing incorrect results, but it's probably not that hard to implement the correct behavior, either. As a worst-case, for example, a noncontiguous `out` can be replaced with a temporary contiguous `out` tensor, and then the results copied from the temporary to the original noncontiguous `out`

**Comment by lezcano** [comment]
As discussed, this is already documented in the xfails of the relevant operations, so I'm closing this one for now.

I do not think that having an issue listing all these xfails would be reasonable (too difficult to maintain up to date), unless anyone is consistently going to work on fixing these. As such, I'm closing this one for now.
