### ISSUE TITLE
dist.scatter_object_list() NCCL support

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#84571]
### 🐛 Describe the bug

Tracking issue from https://discuss.pytorch.org/t/why-scatter-object-list-does-not-support-nccl/160515. Support for scatter() was added to NCCL but `scatter_object_list()` was not updated. We need to update the doc.

### Versions

main

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @kwen2501

**Comment by H-Huang** [comment]
Doc update here: https://github.com/pytorch/pytorch/pull/84596

**Comment by kumpera** [comment]
Fixed.
