### ISSUE TITLE
1x1 Convolution and Index Cropping are not swappable.

### ISSUE THREAD

**Issue by LiuZichuan** [pytorch/pytorch#84582]
### 🐛 Describe the bug

Below code shows the `1x1 conv2d` followed by `index cropping` is not equivalent to `cropping` followed by `1x1 conv2d`. The `diff_sum` is non-zero. It seems to be a bug. Any suggestion to fix this problem quickly before the new pytorch version release? I found this problem on at least two pytorch version. Please see the `Version` section.
```python
import torch
import torch.nn.functional as F

x = torch.randn(1, 256, 512, 512)
w = torch.randn(64, 256, 1, 1)

crop_ind = 99
conv_crop = torch.conv2d(x, w, None, [1, 1], [0, 0], [1, 1], 1)[:, :, :crop_ind, :crop_ind]
crop_conv = torch.conv2d(x[:, :, :crop_ind, :crop_ind], w, None, [1, 1], [0, 0], [1, 1], 1)
diff_sum = ((conv_crop - crop_conv) != 0).sum()
```

### Versions

Python version: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-70-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 430.64
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] msgpack-numpy==0.4.4.3
[pip3] numpy==1.19.5
[pip3] torch==1.7.1+cu101
[pip3] torchaudio==0.7.2
[pip3] torchgeometry==0.1.2
[pip3] torchtext==0.4.0
[pip3] torchvision==0.8.2+cu101

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-1023-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

Nvidia driver version: 460.106.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.0
[conda] Could not collect

**Comment by ngimel** [comment]
This is expected behavior https://pytorch.org/docs/stable/notes/numerical_accuracy.html
