### ISSUE TITLE
Update DDP checkpoint documentation

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#84589]
### 📚 The doc issue

DDP checkpoint documentation here: https://github.com/pytorch/pytorch/blob/88b1cc885cc92b9483eec95546bb48c7bccea070/torch/nn/parallel/distributed.py#L333 should be updated in light of new non-reentrant checkpoint API available. 

In particular, checkpoint with non_reentrant=True supports the use cases that are mentioned as unsupported.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by DongyuXu77** [comment]
I could work on it as a newcomer

**Comment by Shasmita** [comment]
Hi, I would like to work on this issue.

**Comment by the-tyler** [comment]
Hi, I am available to work on this very interesting issue. If you can assign it to me, then I can immediately start working on it.

**Comment by shilpiprd** [comment]
Hi!, since nobody had made any changes, i assumed that this issue was open. I changed the documentation a bit and added one example.
