### ISSUE TITLE
[primTorch] view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by rdspring1** [pytorch/pytorch#84618]
### 🐛 Describe the bug

With eager mode, `layer_norm` returns a contiguous tensor when its input is a strided tensor. However, primTorch will return a strided tensor like the input. This causes a runtime error with the `linear` layer when it views the 3D input as a 2D tensor.
(See https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Linear.cpp#L38-L44) Should the primTorch reference follow the same stride behavior as eager mode?

```
"RuntimeError: view size is not compatible with input tensor's size and stride 
(at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead."
```

```python
import torch
import torchdynamo
from torchdynamo.testing import rand_strided

class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer_norm = torch.nn.LayerNorm((768,), eps=1e-06, elementwise_affine=True)
        self.linear = torch.nn.Linear(in_features=768, out_features=2304, bias=True)

    def forward(self, transpose_0, permute_1):
        add_2 = transpose_0 + permute_1
        layer_norm_3 = self.layer_norm(add_2)
        linear_4 = self.linear(layer_norm_3)
        return (linear_4,)

args = [((5, 784, 768), (602112, 1, 784), torch.float32, 'cuda', True),
        ((5, 784, 768), (602112, 1, 784), torch.float32, 'cuda', True)]
args = [rand_strided(sh, st, dt, dev).requires_grad_(rg) for (sh, st, dt, dev, rg) in args]

mod = Repro().cuda()
opt_mod = torchdynamo.optimize("prims_nvfuser")(mod)
res = torchdynamo.debug_utils.run_fwd_maybe_bwd(opt_mod, args)
```

### Versions

master

cc @ezyang @mruberry @ngimel

**Comment by Chillee** [comment]
We could just call contiguous on the layer norm outputs. I thought we would just map view => reshape during tracing though.

Oh, I might have moved the reshape decomposition into core (instead of always in AOTautograd), so maybe you guys aren’t using it anymore.

**Comment by IvanYashchuk** [comment]
I only see `aten::_reshape_alias` that calls `view`:
https://github.com/pytorch/pytorch/blob/7c3102f3f09e0ac0bf272df2ad48dd40515eceea/torch/_decomp/decompositions.py#L1680-L1682

**Comment by jjsjann123** [comment]
> I thought we would just map view => reshape during tracing though

^^^ This sounds about right for 1.13. I don't think prim has ever made any promise on preserving memory format at this point, so any use of `view` is a shot in the dark :smile:

**Comment by rdspring1** [comment]
Linking PR to map view ops to reshape: https://github.com/pytorch/pytorch/pull/84801
