### ISSUE TITLE
lazy backend_interface.h missing include tensor.h

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#84650]
Currently on master, things build fine.  But some local builds which changed header include orders tripped up 
```
backend_interface.h:44:39: error: ‘LazyTensorPtr’ does not
 name a type                                                                                                    
   44 |   virtual bool ShouldSyncTensor(const LazyTensorPtr tensor) const;
   ```
   
Which brings up 2 questions
 1) should we be allowing backend_interface to know about LazyTensorPtr or is that a layering violation?
 2) if yes to 1, can we currently include `lazy/core/tensor.h` in backend_interface.h or is that going to cause a circular include?

Relates to recently added `ShouldSyncTensor` API (https://github.com/pytorch/pytorch/pull/84418)

cc @antoniojkim could you see if it's simple to patch in (2)?
cc @ezyang

**Comment by antoniojkim** [comment]
The circular dependency exists because `lazy/core/tensor.h` imports `lazy/backend/backend_impl_interface.h` even though (as far as I can tell) it doesn't need to. So, by removing that include from `lazy/core/tensor.h` and adding the `lazy/core/tensor.h` header in `lazy/backend/backend_impl_interface.h` should fix things

**Comment by wconstab** [comment]
agreed, I think at one point backend_impl_interface defined more stuff needed by tensor but at some point we refactored to split out ir_builder or backend_device definitions to their own headers so now it is just leftover and should be removed.

**Comment by antoniojkim** [comment]
What exactly is it that needs to be changed? I already did this refactor in #84418

**Comment by wconstab** [comment]
oh! yea your PR looks right to me, i think things should be ok on master.  maybe there was just a rebase/merge issue on some dev branches which led to the include order getting messed up locally.
