### ISSUE TITLE
Support FP16 with torch._fake_quantize_learnable_per_channel_affine & torch._fake_quantize_learnable_per_tensor_affine

### ISSUE THREAD

**Issue by Jeremalloch** [pytorch/pytorch#84652]
### 🚀 The feature, motivation and pitch

The PyTorch operators `torch._fake_quantize_learnable_per_channel_affine` and `torch._fake_quantize_learnable_per_tensor_affine` currently only support `torch.float32` datatypes, while the non-learnable scale operators `torch.fake_quantize_per_channel_affine` and `torch.fake_quantize_per_tensor_affine` support more datatypes (ie torch.float16).  This makes using the learnable scale fake quantization operators break some pipelines which use CUDA mixed precision training, and otherwise breaks the consistency between the learnable and non-learnable scale fake quantize operators.

The non-learnable scale fake quantize operators originally only supported `torch.float32` (see [this issue ](https://github.com/pytorch/pytorch/issues/50417) that ran into this problem, and [this issue](https://github.com/pytorch/pytorch/issues/42351) which tracked the implementation of more datatypes).  I'd like to know if there is a timeline to expand support for extra datatypes for the learnable scale fake quantization operators as well.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by LuletterSoul** [comment]
@jeejakp12 @jianyuh @raghuramank100 @vkuzo  In fact, using mixed precision to save GPU memory is very important in QAT. If this feature is added in the future, it will be very helpful for QAT.

**Comment by andrewor14** [comment]
@vkuzo Do you have more context on this?

**Comment by andrewor14** [comment]
Hi @Jeremalloch, learnable fake quantize is not under active development so we will unlikely add support for additional dtypes. I'm closing this for now but please feel free to work on this if this is important to your use case.

**Comment by mgoin** [comment]
Hi @andrewor14 I'm adding a +1 here - I would like to be able to apply fake quantization for one-shot calibration of bfloat16 LLMs. Currently I fail to find a kernel that can run the model

```
> python /home/michael/code/sparseml/src/sparseml/transformers/sparsification/obcq/obcq.py NousResearch/Nous-Hermes-2-Yi-34B open_platypus --recipe recipe.yaml --save True
...
  File "/home/michael/venvs/sml/lib/python3.10/site-packages/torch/ao/quantization/fake_quantize.py", line 213, in forward
    X = torch.fake_quantize_per_tensor_affine(
RuntimeError: "fake_quantize_tensor_cachemask_kernel_types" not implemented for 'BFloat16'
```

This is required because the model produces NaNs if run at float16
```
> python /home/michael/code/sparseml/src/sparseml/transformers/sparsification/obcq/obcq.py NousResearch/Nous-Hermes-2-Yi-34B open_platypus --recipe recipe.yaml --precision float16 --save True
...
  File "/home/michael/venvs/sml/lib/python3.10/site-packages/torch/ao/quantization/utils.py", line 346, in check_min_max_valid
    assert min_val <= max_val, f"min {min_val} should be less than max {max_val}"
AssertionError: min nan should be less than max nan
```

**Comment by jerryzh168** [comment]
I feel we can reimplement this in python and then use torch.compile to extract performance cc @andrewor14

**Comment by andrewor14** [comment]
> I'm adding a +1 here - I would like to be able to apply fake quantization for one-shot calibration of bfloat16 LLMs. Currently I fail to find a kernel that can run the model

Hi @mgoin, I think what you're asking for is actually not related to this issue, which is specifically talking about "learnable" fake quants. If I understand correctly you're asking for a fake quantize op that works with bfloat16 dtypes, is that correct? If so, do you mind filing a new issue for that?

**Comment by alexs131** [comment]
Hi @jerryzh168  @andrewor14, was looking into this support recently. I found this previous diff adding fp16 support to general quantization ops a few years ago https://github.com/pytorch/pytorch/pull/52612 from @HDCharles, is it basically the same process to add it to learnable quantize ops? Thanks!
