### ISSUE TITLE
[ONNX] Track non-exportable pattern as diagnostics.

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#84661]
Issue hub for tracking and organizing patterns to be added as diagnostic rules.

- [x] [#87738](https://github.com/pytorch/pytorch/issues/87738) Not non-exportable. Convert shape inference warning to diagnostic.

**Comment by titaiwangms** [comment]
Should this be closed?

**Comment by BowenBao** [comment]
Closing as not planned.
