### ISSUE TITLE
[torchaudio]`torchaudio.compliance.kaldi.mfcc` seems to produce strange energy values.

### ISSUE THREAD

**Issue by cantabile-kwok** [pytorch/pytorch#84684]
### 🐛 Describe the bug

I am using torchaudio to extract Kaldi-like MFCC features for audio. I found `torchaudio.compliance.kaldi.mfcc` function which is exactly what I need. The code runs smoothly, but when I inspect the values, I found the energy produced by this function seems incorrect and very different to the results by Kaldi `compute-mfcc-feats` command.

Here is an example audio (LJ001-0110.wav): https://drive.google.com/file/d/1p6go649Li7tyCcwJN-d0Xy0uUvvfNCg2/view?usp=sharing

```python
import torchaudio
import matplotlib.pyplot as plt
audio, sr = torchaudio.load("LJ001-0110.wav")

mfcc = torchaudio.compliance.kaldi.mfcc(audio,
                                          sample_frequency=sr,
                                          frame_shift=256 * 1000 / sr,
                                          frame_length=1024 * 1000 / sr,
                                          use_energy=True,
                                          raw_energy=False,
                                          window_type='hanning')  # generates 13-dim mfcc with energy as 0-th dim
mfcc = mfcc.cpu().numpy()

# ====== plot values ========
plt.subplots(13, 1, figsize=(20, 65))
for i in range(13):
    plt.subplot(13, 1, i+1)
    plt.plot(mfcc[:, i])
    plt.title(f"{i}-th Dimension")
# plt.savefig(target_png, dpi=100)
plt.show()
```

And this generates this figure:
![torchaudio_mfcc](https://user-images.githubusercontent.com/58417810/189044649-8b4c0f91-b6c3-45cb-b541-44fa515a6b2b.png)

As we can see, the first dimension, which is the log-energy, seems to be 0 most of the time, which some steep peaks. I don't think this are the expected values, as this natural speech should have a complex energy trajectory. I also plot the Kaldi MFCC output as follows, under the same configuration:
![kaldi_mfcc](https://user-images.githubusercontent.com/58417810/189044667-455ad3cd-f5e3-4680-a79b-330610509ac2.png)

Clearly this looks more reasonable than torchaudio output. Also, the other dimensions of torchaudio output (except the 0-th) fit well to the Kaldi output. It is only the 0-th dimension that looks strange.

### Versions

Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 8.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.9.6 (default, Aug 18 2021, 19:38:01)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-693.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 10.1.105
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.12.0
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchtyping               0.1.4                    pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

**Comment by cpuhrsch** [comment]
Hello @cantabile-kwok, did you mean to open this issue over at https://github.com/pytorch/audio ?

**Comment by cantabile-kwok** [comment]
Oh sure, I did not notice there is an audio repo. I will open one there instead.
