### ISSUE TITLE
Request deterministic support for `scatter_add_cuda_kernel` operation

### ISSUE THREAD

**Issue by nestiank** [pytorch/pytorch#84683]
### 🚀 The feature, motivation and pitch

Hello,

I am using torch_scatter (https://github.com/rusty1s/pytorch_scatter) for my project.

When I use scatter() it internally calls torch.Tensor.scatter_add_() below:

https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_add_.html

which is nondeterministic in CUDA devices.

> RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

I need to reproduce my research results when I use this.
If possible, please prioritize adding deterministic support for `scatter_add_cuda_kernel` operation!

Thanks!

cc @mikaylagawarecki

**Comment by nestiank** [comment]
Oops - I was very fortunate.
I found #50469 and it was merged by #79466 - no need to open a new issue.
Thanks!

**Comment by nestiank** [comment]
Just to make sure...
If possible, please consider releasing this fix in a moment.
I am reopening this issue just to inform you this request.

**Comment by cpuhrsch** [comment]
cc @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Hi @nestiank could I confirm which version of pytorch you are using? You can get this information by running the following script: 

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

or 

```
import torch
print(torch.__version__)
```

I believe installing the nightly should enable the use of the deterministic scatter_add from #79466 :)

**Comment by nestiank** [comment]
Does the nightly build immediately reflect all code changes? I did not notice that. You've made my day!
