### ISSUE TITLE
Fix deprecation warning in `torch.utils.tensorboard` import

### ISSUE THREAD

**Issue by milutter** [pytorch/pytorch#84712]
### 🚀 The feature, motivation and pitch

Importing the tensorboard writer yields a deprecation warning from `distutils` in python 3.10, i.e.,
`DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.`

This can be easily fixed as mentioned in the deprecation warning. One needs to replace the current lines 2 - 9 (https://github.com/pytorch/pytorch/blob/master/torch/utils/tensorboard/__init__.py#L2)
```
from distutils.version import LooseVersion

if not hasattr(tensorboard, "__version__") or LooseVersion(
    tensorboard.__version__
) < LooseVersion("1.15"):
    raise ImportError("TensorBoard logging requires TensorBoard version 1.15 or above")

del LooseVersion
```

with 

```
import packaging

if not hasattr(tensorboard, "__version__") or packaging.version.parse(
        tensorboard.__version__
) < packaging.version.Version("1.15"):
    raise ImportError("TensorBoard logging requires TensorBoard version 1.15 or above")

del packaging
```

I am happy to submit the PR but I do not know how to test against all supported python versions and changing all requirements correctly in all different build targets.

**Comment by karan6181** [comment]
+1. I am also facing the same issue. @ngimel Do you have any ETA on when will this be fixed? Thanks!

**Comment by rbracco** [comment]
I am also seeing this warning a lot.

**Comment by Jasha10** [comment]
@milutter, I tried opening a PR based on the diff from your OP above (PR #88524).
I'm seeing some test failures: `module 'packaging' has no attribute 'version'`

```text
Traceback (most recent call last):
  File "test_monitor.py", line 104, in setUp
    from torch.utils.tensorboard import SummaryWriter
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    if not hasattr(tensorboard, "__version__") or packaging.version.parse(
AttributeError: module 'packaging' has no attribute 'version'
```

(here's an example CI job failure: https://github.com/pytorch/pytorch/actions/runs/3397514945/jobs/5649878533#step:10:3456)
