### ISSUE TITLE
torch::from_blob() cause coredump

### ISSUE THREAD

**Issue by jackzhou121** [pytorch/pytorch#84746]
### 🐛 Describe the bug

my code is simple, call torch::from_blob() cause coredump.
int main()
{
    float data[]={1.0};
    auto input4 = torch::from_blob(data,{1},torch::dtype(torch::kF32)).clone();
    return 0;
}
here is the bt:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tts_mem'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f1f9bf89859 in __GI_abort () at abort.c:79
#2  0x00007f1f9c214911 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f1f9c22038c in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f1f9c2203f7 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f1f9c2206a9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f1fa70de168 in c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /opt/tritonserver/backends/pytorch/libc10.so
#7  0x00007f1fa70f33ac in c10::TensorImpl::set_storage_offset(long) () from /opt/tritonserver/backends/pytorch/libc10.so
#8  0x00005608fcbd89ed in torch::autograd::make_variable (data=..., requires_grad=<optimized out>, allow_tensor_metadata_change=<optimized out>) at /usr/include/c++/9/bits/atomic_base.h:279
#9  0x00005608fcbd92b7 in torch::from_blob (data=0x7ffde2ca999c, sizes=..., options=...) at /usr/include/c++/9/bits/atomic_base.h:539
#10 0x00005608fcbb45b4 in main () at /usr/include/c++/9/initializer_list:99

### Versions

pytorch 1.13

**Comment by ngimel** [comment]
Please provide fully runnable and reproducible example

**Comment by jackzhou121** [comment]
Reproduced code is already provided.

Natalia Gimelshein ***@***.***>于2022年9月14日 周三05:52写道：

**Comment by jackzhou121** [comment]
This issue was caused by my container env, so this is a wrong report, I
closed this.
thanks for help~

Natalia Gimelshein ***@***.***>于2022年9月14日 周三05:52写道：
