### ISSUE TITLE
UNET implementation

### ISSUE THREAD

**Issue by kanopo** [pytorch/pytorch#84743]
### 🚀 The feature, motivation and pitch

Hi guys,
Im working on a UNET  based problem for my thesis, is it possible to implement that model in the pytorch set of models?

I'll be really happy to implement it!

If you are interested, i'll make a pull request

**Comment by george-qi** [comment]
Hi, thanks for the comment and enthusiasm! The description currently seems a bit vague, but you're welcome to submit a PR for such a feature
