### ISSUE TITLE
make_data_loader error in libtorch on windows

### ISSUE THREAD

**Issue by JustKeepSilence** [pytorch/pytorch#84740]
## Issue description

when using make_data_loader on win10 in vs2022 with intel c++ 2022 compiler in debug mode in libtorch, an error occurs.
![image](https://user-images.githubusercontent.com/39700571/189265783-2996967c-b9c0-44dc-aa5d-3761557adc19.png)

## Code example
Here is my code:
```
#include <torch/torch.h>

class sample_dataloader : public torch::data::Dataset<sample_dataloader> {
public:
    torch::Tensor rand_val;
    sample_dataloader() {
        rand_val = torch::rand({ 30, 30 }); // random batch of images
    }

    torch::optional<size_t> size() const override {
        return 10;
    }

    torch::data::Example<> get(size_t index) {
        return { rand_val[index], rand_val[index] };
    }
};

int main() {
    auto train_set = sample_dataloader().map(torch::data::transforms::Stack<>());
    int batch_size = 5;
    int num_workers = 0;
    auto dl = torch::data::make_data_loader<torch::data::samplers::SequentialSampler>
        (std::move(train_set), torch::data::DataLoaderOptions().batch_size(batch_size).workers(num_workers));
    for (auto& batch : *dl) {
        auto rand_im = batch.data;
        auto targets = batch.target;
    }
}
```

## System Info

- PyTorch or Caffe2: 1.21.1
- How you installed PyTorch (conda, pip, source): https://download.pytorch.org/libtorch/cu113/libtorch-win-shared-with-deps-debug-1.12.1%2Bcu113.zip
- Build command you used (if compiling from source): intel c++ compiler 2022 debug mode
```
#pragma comment(lib, "torch")
#pragma comment(lib, "torch_cpu")
#pragma comment(lib, "c10")
#pragma comment(lib, "c10_cuda")
#pragma comment(lib, "torch_cuda")
#pragma comment(lib, "torch_cuda_cu")
#pragma comment(lib, "torch_cuda_cpp")
#pragma comment(linker, "/INCLUDE:?warp_size@cuda@at@@YAHXZ")  // enable CUDA in libtorch
#pragma comment(linker, "/INCLUDE:?ignore_this_library_placeholder@@YAHXZ")
```
- OS:win10 
- PyTorch version:1.12.1
- Python version:3.9
- CUDA/cuDNN version:11.3
- GPU models and configuration:GPU 0: RTX3050Ti
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
Can you please post the Error you have encountered?

**Comment by JustKeepSilence** [comment]
yeah, I found it is the problem of torch::stack function, see:
https://github.com/pytorch/pytorch/issues/84521
and after downgrading torch version to 1.8.2 on windows, everything is ok

**Comment by JustKeepSilence** [comment]
@ejgyeah  I found it is the problem of torch::stack function, see:
https://github.com/pytorch/pytorch/issues/84521
and after downgrading torch version to 1.8.2 on windows, everything is okuan

**Comment by JustKeepSilence** [comment]
@ejguan 
yeah, I found it is the problem of torch::stack function, see:
https://github.com/pytorch/pytorch/issues/84521
and after downgrading torch version to 1.8.2 on windows, everything is ok

**Comment by ejguan** [comment]
> yeah, I found it is the problem of torch::stack function, see:

Okay, I see.
let's close this issue and track this problem in https://github.com/pytorch/pytorch/issues/84521
