### ISSUE TITLE
Surface results on HUD  from builder repo

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#84763]
follow this doc: https://github.com/pytorch/test-infra/blob/main/torchci/docs/architecture.md

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by weiwangmeta** [comment]
https://hud.pytorch.org/hud/pytorch/builder/main/1?per_page=50 is populated, closing this task. 
Related (draft) PR is https://github.com/pytorch/test-infra/pull/742 
Successor issue is: https://github.com/pytorch/pytorch/issues/85295
