### ISSUE TITLE
exception during torch.save caused by EINTR

### ISSUE THREAD

**Issue by drlr1115** [pytorch/pytorch#8477]
I was trying below example
https://github.com/pytorch/examples/tree/master/imagenet
and made few changes in the code to get data and save checkpoints from/to cephfs.

command and arguments:
python main.py --data-dir=/mnt/data --output-dir=/mnt/output/ --epochs=1

There was a big chance that I got below error:
**doWrite<int> rc: -1 err: 4 errstr: Interrupted system call
Signal 17**
Traceback (most recent call last):
  File "main.py", line 375, in <module>
    main()
  File "main.py", line 223, in main
    }, is_best)
  File "main.py", line 326, in save_checkpoint
    torch.save(state, filename)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 161, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 118, in _with_file_like
    return body(f)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 161, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 238, in _save
    serialized_storages[key]._write_file(f, _is_real_file(f))
RuntimeError: Unknown error -1

I added some code in the source code to print the error and signal, then reproduced and got the bold lines.
Seems like save operation happened right after validation finished, exit of worker subprocesses caused the SIGCHLD, then interrupted "write" system call.

I already add some sleep time before save as a workaround, but should some retry mechanism been added into the save code or provide more specific error msg?

- PyTorch v0.4.0
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: Ubuntu16.04
- PyTorch version: 0.4.0
- Python version: 3.5.2
- CUDA/cuDNN version: 9.0/7.1.2
- GPU models and configuration: P40/K40
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by soumith** [comment]
this seems like reasonable behavior. What do you expect the behavior to be instead?

**Comment by gothos-folly** [comment]
@soumith In most contexts a syscall returning EINTR should be transparently retried instead of propagating to the calling code as an error.

**Comment by ezyang** [comment]
we fixed this

```
template <typename io>
void doWrite(io fildes, void* raw_buf, size_t nbytes) {
  char* buf = static_cast<char*>(raw_buf);
  while (nbytes > 0) {
    errno = 0; // doPartialWrite may not set errno
    // we write in 1GB blocks to avoid bugs on Mac OS X Lion
    // see https://github.com/pytorch/pytorch/issues/1031 for more details
    ssize_t r = doPartialWrite(fildes, buf, std::min<size_t>(nbytes, 1073741824));
    if (r < 0) {
      int err = errno;
      AT_ASSERTM(err != 0, "write(): impossible! r < 0, but no errno was set");
      AT_ASSERTM(err != EAGAIN, "write(): non-blocking fd ", fildes,
                                " read EAGAIN; cowardly refusing to spin-wait");
      if (err == EINTR) {
        continue;
      } else {
        AT_ERROR("write(): fd ", fildes, " failed with ", strerror(err));
      }
    }
    buf += r;
    AT_ASSERT(static_cast<size_t>(r) <= nbytes);
    nbytes -= r;
  }
}

```
