### ISSUE TITLE
[doc] torch.narrow support for `start` arg as Tensor is undocumented

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#84783]
### 📚 The doc issue

Ref: https://pytorch.org/docs/stable/generated/torch.narrow.html

https://github.com/pytorch/pytorch/blob/01c54ad6dedf2ab0206a37f6df1af4fe41afa051/aten/src/ATen/native/native_functions.yaml#L3685-L3688

cc @svekars @holly1238

**Comment by kit1980** [comment]
Thanks. Can you suggest a PR?
