### ISSUE TITLE
pytorch 0.4.0 always allocates memory on GPU:0 when the model and data are on other GPU.

### ISSUE THREAD

**Issue by yezhejack** [pytorch/pytorch#8480]
I want to only use GPU:1 to train my model. I put the gru layer and input tensor to the cuda:1. After I feed the data into gru layer there, pytorch will allocate some memory on GPU:0. As a result, it will use two GPUs. The following code will reproduce the problem.
```
import torch
with torch.cuda.device(1):
    gru = torch.nn.GRU(10, 10).to(1)
i = torch.ones(1, 1, 10)
with torch.cuda.device(1):
    i = i.to(1)

input('check the nvidia-smi')
k = gru(i)
input('check the nvidia-smi')
```

**Comment by fmassa** [comment]
I believe this has been fixed in https://github.com/pytorch/pytorch/pull/7392 , and is available in pytorch master.

Can you run your python script with
```python
CUDA_VISIBLE_DEVICES=1 python my_script.py
```
while you don't update pytorch?

**Comment by LiUzHiAn** [comment]
Hi, I met the same issue with Pytorch 1.7.0 and cudatoolkit 11.0.221. Here is my script:
```
import torch
 
while True:
    a=torch.Tensor([[-1., 1.]])
    a=a.to("cuda:1")  # Line 5
```
I was told `RuntimeError: CUDA error: invalid device ordinal` when using `CUDA_VISIBLE_DEVICES=1` running arg as @fmassa suggested. But if I change the `cuda:1` into `cuda:0`, it works well. A little bit confusing!
