### ISSUE TITLE
Build Error lib.obj not found

### ISSUE THREAD

**Issue by Vedaevolution** [pytorch/pytorch#8485]
Dear community,

i encountered a build error i can not resolve.  I'm trying to build pytorch with the specs below. The error i'm encountering is this one:

![img](https://s1.imagebanana.com/file/180614/bqRUhDP0.PNG)

## Issue description

Obviously it's lacking a dubious lib.obj for linking. The question is why it is searching for it in the standard Nvidea folder. Shouldn't the files compiled not be safed somewhere else. Furthermore there is no other error before this one in the build process. 

Can anyone help me with what has gone wrong here. I followed the instructions of the regular link:
[pytorch from source](https://github.com/pytorch/pytorch#from-source)

Best regards

## System Info

- PyTorch 
- How you installed PyTorch (conda, pip, source): Source
- Build command you used (if compiling from source): python setup.py install
- OS: Windows 10
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version: 9.0
- GPU models and configuration: GTX 1070
- Visual Studio 17 (15.7.3)
- CMake version: 3.11.1

**Comment by zou3519** [comment]
cc @peterjc123 do you know what's up here?

**Comment by peterjc123** [comment]
@Vedaevolution Could you please send me the complete log?

**Comment by Vedaevolution** [comment]
@peterjc123  Sure i can. [Get it here](https://drive.google.com/open?id=1A5_l4TVpiVNlkdrjKh2yQxMfpeNV21ir)

**Comment by peterjc123** [comment]
@Vedaevolution And your `CMake` log files, please?

**Comment by peterjc123** [comment]
It seems the FindCUDNN is bringing some wrong flags in the linking phase of `caffe2`.

**Comment by Vedaevolution** [comment]
Sorry for inconvenience, those should be the ones:

- [Error Log](https://drive.google.com/open?id=1ZkCmHDhtKe-nAVQEo-ChAMZUvThVWUQN)
- [Output Log](https://drive.google.com/open?id=12ZOdl-3sne6adDxyG7vpZdsbnec3crPv)

And what do i need to change?

**Comment by peterjc123** [comment]
It seems the `caffe2::cudnn IMPORTED_LOCATION` is not properly set by the `find_library` in `cmake\Modules\FindCuDNN.cmake` L33-39? @Vedaevolution, did you manually set the environmental variable `CUDNN_LIBRARY`? If not, then it's something wrong with the CMake script there.

**Comment by Vedaevolution** [comment]
@peterjc123  I did not change any environement variable concerning cuda. It is strange an error like that appears even though the folder is generally found. I also have no other problems with cuda or cudnn. It's just with this build process. 

I try your fix when it's in master.
