### ISSUE TITLE
torch.distributed.reduce_scatter documentation lacks op parameter description

### ISSUE THREAD

**Issue by clumsy** [pytorch/pytorch#84865]
### 📚 The doc issue

[torch.distributed.reduce_scatter](https://pytorch.org/docs/stable/distributed.html#torch.distributed.reduce_scatter) has `op` parameter but does not provide a description for it.

### Suggest a potential alternative/fix

Add the following to doc-string:

```
op (optional): One of the values from
            ``torch.distributed.ReduceOp``
            enum.  Specifies an operation used for element-wise reductions.
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by ShisuiUzumaki** [comment]
@clumsy I would like to take up this issue
