### ISSUE TITLE
Re-Running PR Sanity Check after Adding `skip-pr-sanity-checks` Label Still Fails

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#84870]
The PR https://github.com/pytorch/pytorch/pull/83665 exceeds the 2k LOC limit for the PR sanity check. After adding the label `skip-pr-sanity-checks` and re-running the failing check, the check continues to fail when the expected behavior is for it to now pass.

(I have since rebased the PR since one of the preceding PRs had some flaky build failures.)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
cc @albanD

**Comment by janeyx99** [comment]
Yea, on reruns, GitHub effectively "freezes" the context they have from the previous run, which I believe includes label information. We may want to query for the labels ourselves instead of relying on the PR context.

**Comment by huydhn** [comment]
Here is a snippet to query GitHub API for the latest labels for those who are interested https://github.com/pytorch/pytorch/blob/master/.github/scripts/filter_test_configs.py#L42-L65.  A curl command with some bash magic should also work fine in this case.  The con: this needs one API request for every single PR taking into account that the sanity check is run for every PR

**Comment by huydhn** [comment]
I think we can resolve this issue, the issue is expected and `skip-pr-sanity-checks` label is only applied when the PR is synced (updated).  We can make it work dynamically, but it's probably of low priority.
