### ISSUE TITLE
AttributeError: module 'torch' has no attribute '_TensorBase'

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#8489]
My system is:
ubuntu 16.04
Im using pytorch 0.4 (installed it via conda)
cuda 9.0
python 3.X
anaconda 3

it sounds like it does not have the _TensorBase.

When I run the following code:

```
---> 11     if isinstance(data, t._TensorBase):
     12         return data.cpu().numpy()
```

I receive this error

AttributeError: module 'torch' has no attribute '_TensorBase'

**Comment by vishwakftw** [comment]
`_TensorBase` is present in `torch._C`, not `torch`.
