### ISSUE TITLE
DISABLED test_serialization_offset (__main__.TestOldSerialization)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#84898]
Platforms: mac, macos

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_serialization_offset%2CTestOldSerialization)).

This fails again https://hud.pytorch.org/pytorch/pytorch/commit/5a29db142e4665577149e305db0583e55ef21683, so I disable this test pending the discussion in https://github.com/pytorch/pytorch/issues/84841 on how best to clean up these runners.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
I don't think this is really sustainable (nor productive) as all tests will eventually fail with no space left on device error...
Instead, we should be reclaiming space on those nodes...

**Comment by huydhn** [comment]
> I don't think this is really sustainable (nor productive) as all tests will eventually fail with no space left on device error... Instead, we should be reclaiming space on those nodes...

Yeah, this is only a temporary measure while we continue the investigation in https://github.com/pytorch/pytorch/issues/84841.  This test writes a 2GB file to disk I think.

I'll bring up the issue again tomorrow to get help from the team.  At the moment, I have no idea which one is responsible for filling up the disk.

**Comment by huydhn** [comment]
mac M1 runners has been cleaned up, resolving this one

**Comment by huydhn** [comment]
Got a fix here https://github.com/pytorch/test-infra/pull/2100 to increase the minimum space required on MacOS to be 10GB.  The current threshold of 4GB is not big enough
