### ISSUE TITLE
Issue with masked_select_ on rand generated tensors

### ISSUE THREAD

**Issue by sharath** [pytorch/pytorch#8492]
## Issue description
I think there might be an issue masked_select_. It doesn't seem to work on some source tensors.

## Code example

```python
import torch

t_size = 10000
n = torch.rand(t_size)
n_ = n.clone()

mask = (torch.rand(t_size) > 0.5)
source = torch.rand(t_size)
n.masked_scatter_(mask, source)

# what i expect masked_scatter_ to do
for i in range(len(mask)):
    if mask[i]:
        n_[i] = source[i]

for i in range(len(n)):
    assert n[i] == n_[i]
```
I get the following error.
`
Traceback (most recent call last):
  File "Untitled.py", line 17, in <module>
    assert n[i] == n_[i]
AssertionError`

This doesn't happen if source is `torch.ones(t_size)`

## System Info
- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): conda, pip
- Build command you used (if compiling from source): none
- OS: Mac OSX 10.13.5
- PyTorch version: 0.4.0
- Python version: 3.6
- CUDA/cuDNN version: no
- GPU models and configuration: no
- GCC version (if compiling from source): no
- CMake version: 3.11.3
- Versions of any other relevant libraries: numpy 1.14.4

**Comment by vishwakftw** [comment]
You seem to have provided code for `masked_scatter_`. However, even for `masked_scatter_` your version does not replicate the behaviour of `masked_scatter_`, but that of `torch.where`.

**Comment by sharath** [comment]
Thanks, that seems to do the trick
