### ISSUE TITLE
Tutorial code crashes on Windows

### ISSUE THREAD

**Issue by krikru** [pytorch/pytorch#8494]
## Problem

As reported by some Windows users, the code in the tutorial [Training a classifier](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py), which is part of the _Deep Learning with PyTorch: A 60 Minute Blitz_ tutorial, throws a `BrokenPipeError` exception and crashes when executed.

## Cause

The issue [happens](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-broken-pipe) when the child process ends before the parent process finishes sending data.

## Solution

The problem can be quick-fixed in two ways for the tutorial:

1. All code is wrapped in an `if __name__ == '__main__' :` statement

1. The `torch.utils.data.DataLoader` instances are created with the argument `num_workers` set to `0` (which is also that argument's default value)

## Reasonable measure

This Windows problem should probably be mentioned in the tutorial. One or both of the quick-fixes could also be mentioned.

**Comment by zou3519** [comment]
cc @peterjc123 what do you think?

**Comment by peterjc123** [comment]
Maybe plan 2 is a better idea. Although plan 1 helps to eliminate this issue while running the script, plan 2 ensures the code runs well under interactive mode. @krikru Could you please do me a favor and make a PR on this?

**Comment by krikru** [comment]
@peterjc123 Sure. Will [this](https://github.com/pytorch/tutorials/pull/265) do?
