### ISSUE TITLE
Get rid of expand nodes from broadcasting operators when tracing

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8495]
Historically, when we trace `add(x, y)`, this will trace as `add(expand(x), expand(y))`. This has widely been considered to be a bad idea.

We are pretty close to being able to change the tracing behavior here:

- We need to modify the Variable generation to having the broadcasting add perform a trace. This accidentally happened in https://github.com/pytorch/pytorch/pull/8409 when we moved `add` from TH to native (the expand behavior is *specifically* coded in the TH codebath; it doesn't apply in the native codepath) and it should be a relatively simple matter to flip it to the other regime.
- The JIT graph executor codepath has a pass to explicitly remove all expands. We can delete this pass.
- The ONNX exporter uses expand nodes to determine whether or not to toggle the broadcast flag. But the ONNX spec has switched to Numpy style broadcasting. So we can get rid of all of this logic, assuming we can bump our opset version late enough (there may be other blockers here.)

@colesbury also intends to delete explicit expand operations from ATen, in favor of kernels which explicitly know how to deal with broadcasting.

CC @houseroad

**Comment by gchanan** [comment]
@colesbury do we consider this closed?

**Comment by eellison** [comment]
This is fixed:
```
def fn(x, y):
    return x + y

out = torch.jit.trace(fn, (torch.tensor([2, 2]), torch.tensor([[2], [2]])))
print(out.graph)
```

```
graph(%x : Long(2),
      %y : Long(2, 1)):
  %2 : int = prim::Constant[value=1]() # test/test_jit.py:8804:0
  %3 : Long(2, 2) = aten::add(%x, %y, %2) # test/test_jit.py:8804:0
  return (%3)
```
