### ISSUE TITLE
RuntimeError: "upsample_linear1d_out_frame" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by turian** [pytorch/pytorch#84989]
### 🐛 Describe the bug

`torch.nn.Upsample` doesn't work with bfloat16

```
import torch
x = torch.rand(16, 8, 24).bfloat16().cuda()
torch.nn.Upsample(80, mode="linear", align_corners=True)(x)
```

And I get this error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 torch.nn.Upsample(80, mode="linear", align_corners=True)(x)

File /fsx/turian/inverse-audio-synthesis/venv/lib64/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /fsx/turian/inverse-audio-synthesis/venv/lib64/python3.8/site-packages/torch/nn/modules/upsampling.py:153, in Upsample.forward(self, input)
    152 def forward(self, input: Tensor) -> Tensor:
--> 153     return F.interpolate(input, self.size, self.scale_factor, self.mode, self.align_corners,
    154                          recompute_scale_factor=self.recompute_scale_factor)

File /fsx/turian/inverse-audio-synthesis/venv/lib64/python3.8/site-packages/torch/nn/functional.py:3933, in interpolate(input, size, scale_factor, mode, align_corners, recompute_scale_factor, antialias)
   3931 if input.dim() == 3 and mode == "linear":
   3932     assert align_corners is not None
-> 3933     return torch._C._nn.upsample_linear1d(input, output_size, align_corners, scale_factors)
   3934 if input.dim() == 4 and mode == "bilinear":
   3935     assert align_corners is not None

RuntimeError: "upsample_linear1d_out_frame" not implemented for 'BFloat16'
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Amazon Linux release 2 (Karoo) (x86_64)
GCC version: (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.26

Python version: 3.8.5 (default, Feb 18 2021, 01:24:20)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-12)] (64-bit runtime)
Python platform: Linux-5.10.126-117.518.amzn2.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 470.129.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] numpysane==0.35
[pip3] pytorch-lightning==1.7.2
[pip3] pytorch-memlab==0.2.4
[pip3] torch==1.12.1+cu113
[pip3] torch-ort==1.12.0
[pip3] torchaudio==0.12.1+cu113
[pip3] torchmetrics==0.9.3
[pip3] torchsynth==1.0.2
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by turian** [comment]
Related:
https://github.com/tensorflow/tensorflow/issues/32801
https://github.com/pytorch/pytorch/issues/57707
https://github.com/pytorch/pytorch/issues/80339

This open PR passes CI but is not yet merged: https://github.com/pytorch/pytorch/pull/80340

**Comment by Lezcano** [comment]
Given that this is an instance of https://github.com/pytorch/pytorch/issues/80339, let's continue the discussion there. Closing this one.
