### ISSUE TITLE
Document how to use parameters in C++ modular API (was How to use torch.nn.Parameter in libtorch cpp?)

### ISSUE THREAD

**Issue by mullerhai** [pytorch/pytorch#84988]
### 🐛 Describe the bug

HI Dear torch team:
            in pytorch python env ,we always use  torch.nn.Parameter for cache some tensor variable ,like this
```
import torch
import torch.nn as nn
        memory_value = nn.Parameter(torch.cat([self.init_memory_value.unsqueeze(0) for _ in range(batch_size)], 0).data)
        self.mem.init_value_memory(memory_value)

```
but  when I  want to use cpp  libtorch  1.12.1 , I am not found  [ torch::nn::Parameter() ], I don't  how to use Parameter in libtorch cpp env, could you help me ,thanks a lot.

### Versions

libtorch 1.12.1
cpp 20
MacOS lastest

**Comment by mullerhai** [comment]
By the way ,could we give some example tutorial to use parameter  in libtorch cpp?

**Comment by t-vi** [comment]
Similar to using modules (see https://pytorch.org/cppdocs/frontend.html#end-to-end-example ), you need to register the parameter (using the register_parameter method). Other than that, parameters can be stored in Tensor members of the module.

I'm not sure we have an example (good catch) but  torch::nn::Linear for how to do it things in C++ https://github.com/pytorch/pytorch/blob/35f6a69191ef762cf22b6cbfe94b8d9406e16674/torch/csrc/api/src/nn/modules/linear.cpp#L28-L67

**Comment by mullerhai** [comment]
@t-vi  very thanks , I got it .  but also   I have another question.
in pytorch python env, we judge the tensor  is exist or not use  tensor compare with  None ,like 
```

read_weight:    Shape (batch_size, memory_size)  pytorch tensor
if read_weight  is None:
      ....


```

but  in  libtorch cpp env: I found    some tensor method  like  tensor.defined() or  tensor.has_value() or tensor.is_***() ,I not know how to select to judge the tensor is not None in cpp, waiting for your answer, thanks

**Comment by t-vi** [comment]
So if you have a Tensor, the equivalent of None is the undefined tensor (so `! tensor.defined()`). This is used in some parts of the PyTorch API, too. The more modern thing is to use a `c10::Optional<Tensor> o`, there you would have `ot.has_value()` (or just `ot` used as a bool) and then dereference to a tensor (`auto t = *ot;`) if it is defined.

**Comment by mullerhai** [comment]
> https://discuss.pytorch.org

very thanks , I got it
