### ISSUE TITLE
What are PyTorch's plans for Onnx support in the future

### ISSUE THREAD

**Issue by chubbylemon** [pytorch/pytorch#84991]
### 🚀 The feature, motivation and pitch

Currently, there are many constraints on exporting the OnnX model from PyTorch, such as numpy，tensor.data。Will PyTorch's support for Onnx export be enhanced, extended or optimized in the future?
When there are operations in the model that do not support Onnx export, are there any suggestions other than modifying the PyTorch model according to the constraints?

**Comment by justinchuby** [comment]
cc @BowenBao @abock

**Comment by chubbylemon** [comment]
您的邮件我已收到~我会尽快回复~冷明鑫

**Comment by justinchuby** [comment]
I don't think support for numpy and tensor.data is planned. The exporter in `torch.onnx` is actively being improved and updated. Please let us know if you have any other questions!
