### ISSUE TITLE
[MPS] torch.div invoked with integral types crashes with internal assert

### ISSUE THREAD

**Issue by bablf** [pytorch/pytorch#84995]
### 🐛 Describe the bug

When calling torch.div on a tensor that is on "mps" I get the below stated error.

Here is a minimal example to reproduce:  

```python 
torch.div(torch.tensor([1,2,3,4],dtype=torch.int64), 400, rounding_mode="floor")
# works as expected: prints tensor([0, 0, 0, 0])
torch.div(torch.tensor([1,2,3,4],dtype=torch.int64).to("mps"), 400, rounding_mode="floor")
# python[41152:6175911] Error getting visible function: 
# (null) Function floorOp_i64 was not found in the library
# /AppleInternal/Library/BuildRoots/20d6c351-ee94-11ec-bcaf-7247572f23b4/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Utility/MPSKernelDAG.mm:755: failed assertion `Error getting visible function: 
 #(null) Function floorOp_i64 was not found in the library' 
# Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```
Not sure how it could be fixed, but it seems to be an Apple related error. 

mps is available: 
```python
import torch
torch.backends.mps.is_available()
# True
```

### Versions

PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.8.9 (default, Apr 13 2022, 08:48:06)  [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] pytorch-lightning==1.7.1
[pip3] torch==1.12.1
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.13.1
[conda] Could not collect

cc @kulinseth @albanD

**Comment by bablf** [comment]
Possible related issue #77764

**Comment by malfet** [comment]
No, doesn't seep to be related, looks like a bug in MPS library

**Comment by malfet** [comment]
Interestingly enough, it is a M1 only problem, I can run it just fine on x86 laptop:
```
python3 -c "import os; import torch;print(torch.__version__, os.uname().machine, torch.div(torch.tensor([1, 2, 3, 4], device='mps',dtype=torch.int64), 400, rounding_mode='floor'))"
```

**Comment by malfet** [comment]
Ok, actually rounding is unnecessary if result of the operation is integral anyway, so following will both be faster and hide the MPS bug:
```
diff --git a/aten/src/ATen/native/mps/operations/BinaryOps.mm b/aten/src/ATen/native/mps/operations/BinaryOps.mm
index b619307ef8..e650d97c4e 100644
--- a/aten/src/ATen/native/mps/operations/BinaryOps.mm
+++ b/aten/src/ATen/native/mps/operations/BinaryOps.mm
@@ -138,7 +138,8 @@ void div_mode_template(const Tensor& self, const Tensor& other,
     MPSGraphTensor* divTensor =  [mpsGraph divisionWithPrimaryTensor:primaryCastTensor
                                                      secondaryTensor:secondaryCastTensor
                                                                 name:nil];
-    if (!rounding_mode.has_value()) {
+    bool isFloatOutput = ([divTensor dataType] & MPSDataTypeFloatBit) != 0;
+    if (!rounding_mode.has_value() || !isFloatOutput) {
       return divTensor;
     } else if (*rounding_mode == "trunc") {
       return trunc_tensor(mpsGraph, divTensor);
```
