### ISSUE TITLE
Python 3.11 Wheels are broken by functorch commit

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#85006]
### 🐛 Describe the bug

We have all linux binary 3.11 wheel builds broken in nightly workflow:
https://hud.pytorch.org/hud/pytorch/pytorch/nightly

Example breakage:
https://github.com/pytorch/pytorch/actions/runs/3050769707/jobs/4918244719

Suspect is this PR:
https://github.com/pytorch/pytorch/pull/83464

### Versions

nightly 1.13

cc @seemethere @malfet @pytorch/pytorch-dev-infra @zou3519 @Chillee @samdow @soumith

**Comment by malfet** [comment]
A very simple action would be to disable functorch integration for the time being, or may be tweak dim.cpp a bit.
Will take a first stab at the problem today

**Comment by zou3519** [comment]
Another option could be to guard torchdim against Python 3.11 and figure out the problem later. I'm not sure how easy it is going to be to tweak dim.cpp, it may use python version-specific things.

**Comment by zou3519** [comment]
Also, fyi @zdevito

**Comment by malfet** [comment]
I have work in progress patch, but yes, indeed dim is doing some very low level interference...
