### ISSUE TITLE
[ONNX] Remove spammy warnings

### ISSUE THREAD

**Issue by AllenTiTaiWang** [pytorch/pytorch#85015]
- [x] `Warning: Constant folding - unsupported opset version. Constant folding not applied.`(https://github.com/pytorch/pytorch/pull/89291)
- [x] `WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.`(https://github.com/pytorch/pytorch/pull/88622)

**Comment by AllenTiTaiWang** [comment]
@justinchuby is your clean up covers these already? I don't find them in code base anymore

**Comment by justinchuby** [comment]
I don't think so! Try looking for them in the c++ passes?

**Comment by thiagocrepaldi** [comment]
@AllenTiTaiWang @justinchuby what is the status of this? Is any of you working on this? If not, feel free to close it. Leaving open for visibility

**Comment by AllenTiTaiWang** [comment]
I see couple of things related. I will work on this. Thanks!
