### ISSUE TITLE
[Missing documentation] cuSOLVER path for `linalg.lstsq` for underdetermined linear systems (on GPU)

### ISSUE THREAD

**Issue by raj-magesh** [pytorch/pytorch#85021]
### 📚 The doc issue

# `torch.linalg.lstsq` for the linear system: `AX = B`

## When the tensors are on the CPU

PyTorch uses [these LAPACK drivers](https://netlib.org/lapack/lug/node27.html), as described in the [documentation for ` linalg.lstsq`](https://pytorch.org/docs/stable/generated/torch.linalg.lstsq.html).

## When the tensors are on the GPU

- If the matrix is full-rank, PyTorch uses the MAGMA driver "*gels*"
- If the matrix is underdetermined (i.e. A is wide, not tall), the behavior is **undocumented**.

From reading through related issues (e.g. #57317), I discovered that underdetermined systems are supported using the cuSOLVER path. However, I don't know what solution is chosen: is it the minimum-norm solution? Is there documentation for the driver used to do this computation?

From some experiments I ran, the results don't match the `lstsq` implementations of either `numpy` or `scipy`, though this might be expected behavior.

### Suggest a potential alternative/fix

Documenting the behavior of the cuSOLVER path for underdetermined linear systems on GPU would be helpful, especially with information about whether the solution returned is the minimum-norm solution.

cc @svekars @holly1238 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment]
The cuSOLVER path is also `gels` and also assumes that the matrix is full-rank, **even in the wide case**. This is the only driver that's implemented in CUDA.

We should change the docs to not specify that we are using `MAGMA` really, to avoid confusions.

**Comment by Lezcano** [comment]
We would accept a fix for this :)

**Comment by nikitaved** [comment]
Yeah, the solution should be min norm iirc. @IvanYashchuk , could you please confirm?

**Comment by ShisuiUzumaki** [comment]
I would like to try it. 

- Do I have to only update docs?
- Which specific docs are to be updated?

**Comment by IvanYashchuk** [comment]
Mario is right, "gels" is used in both underdetermined and overdetermined systems. "gels" is the name of the algorithm using QR factorization to compute the least squares solution, in the case of underdetermined systems the solution is the minimum norm solution.

Documentation shouldn't mention "MAGMA", it's all Lapack interface, and different "drivers" are different algorithms to compute the solution, algorithm names are encrypted using Lapack's naming scheme.

Yes, it's only docs to be updated to be less confusing. `lstsq`'s documentation lives here: https://github.com/pytorch/pytorch/blob/0c46e3ec6684ad64ce4ef54f07a886ef67bad924/torch/linalg/__init__.py#L999

Lapack's documentation maybe offers more details: https://netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga225c8efde208eaf246882df48e590eac.html

**Comment by Shasmita** [comment]
Hi, I would like to work on this issue.

**Comment by IvanYashchuk** [comment]
There's no need to reserve the work. Anyone on GitHub can submit a pull request with the changes he'd like to contribute.
