### ISSUE TITLE
cannot import name 'VGG16_BN_Weights'

### ISSUE THREAD

**Issue by hangoctl** [pytorch/pytorch#85022]
### 🐛 Describe the bug

pip3 install torch==1.8.2 torchvision==0.9.2 torchaudio==0.8.2 --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu

### Versions

how to install VGG16_BN_Weights
ImportError: cannot import name 'VGG16_BN_Weights' from 'torchvision.models' (/usr/local/lib/python3.8/dist-packages/torchvision/models/__init__.py)

**Comment by mahdilamb** [comment]
You're using an older version of torchvision and hence weights aren't there.

For the version you're installing, try:
```python
from torchvision.models.vgg import vgg16_bn
model = vgg16_bn(pretrained=True)

```

Alternatively, you can download the weights, e.g. see the [source code of the class from the newest version of torch](https://pytorch.org/vision/main/_modules/torchvision/models/vgg.html#VGG16_BN_Weights).
