### ISSUE TITLE
[JIT] Don't support None in the script

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8502]
Operator-level tests fail because we're using `None` in the script. Example failure:

```
======================================================================
ERROR: test_clamp_max (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3473, in script_fn
    CU = torch.jit.CompilationUnit(script)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 352, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 358, in define
    self.module._define(lang, rcb, False)
RuntimeError: 
undefined value None:

def the_method(i0):
    return i0.clamp(0.5, None)
                         ~~~~ <--- HERE
```

Affected tests:

- `test_clamp_max`
- `test_clamp_max_scalar`
- `test_clamp_min`
- `test_clamp_min_scalar`

**Comment by wanchaol** [comment]
I am able to test this function using scriptMethod, and it works with no "undefined value None" shown. It seems that the problem is related to the CompilationUnit.

**Comment by zdevito** [comment]
Discussed with @wanchaol in person. These steps are needed to fix clamp. It is currently special-cased on Python:

1. Change THTensor_(clamp) to check for nan in min or max, and call cminValue or cmaxValue instead.
2. Change THCTensor_(clamp) to do the same
3. Fix derivatives.yaml to check for NaN and call the right gradient variant
4. Remove special handling of clamp in python_torch_functions.h
5. The rest of the task.

**Comment by apaszke** [comment]
What about clamp on integral types? There are no NaNs. Are we just always going to use the two-sided kernel?

**Comment by apaszke** [comment]
I'd also much rather use `inf` than `nan` to represent "no boundary"

**Comment by jramseyer** [comment]
Hi, is this being worked on?  Else I can take a look.

**Comment by wanchaol** [comment]
@jramseyer Hi Jenny, yes I am working on the fix, will send the PR out soon.
