### ISSUE TITLE
torch.bitwise_or crash with segfault

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#85046]
### 🐛 Describe the bug

`torch.bitwise_or`, `torch.bitwise_xor`, `torch.bitwise_and` crash with segfault.

All of the following 6 lines of code would cause a segmentation fault crash. 
```
torch.bitwise_or(input=torch.ones([1,1]), other=torch.tensor([1]), out=torch.ones([2,1,4,13]))
torch.bitwise_xor(input=torch.ones([1,1]), other=torch.tensor([1]), out=torch.ones([2,1,4,13]))
torch.bitwise_and(input=torch.ones([1,1]), other=torch.tensor([1]), out=torch.ones([2,1,4,13]))
torch.bitwise_or(input=torch.tensor([-1]), other=torch.tensor([1]), out=torch.ones([1,0,1]))
torch.bitwise_xor(input=torch.tensor([-1]), other=torch.tensor([1]), out=torch.ones([1,0,1]))
torch.bitwise_and(input=torch.tensor([-1]), other=torch.tensor([1]), out=torch.ones([1,0,1]))
```

Also in `torch.logical_or` and `torch.logical_xor`
```
torch.logical_or(input=torch.ones([1,1]), other=torch.tensor([1]), out=torch.ones([2,1,4,13]))
torch.logical_xor(input=torch.ones([1,1]), other=torch.tensor([1]), out=torch.ones([2,1,4,13]))
```

Output

```
Segmentation fault (core dumped)
```
Also reproduced in the [gist](https://colab.research.google.com/drive/1xBcnZtsDSdn7_WGTy5dzkIFOxc1ZgBpY?usp=sharing)

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220913+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.6 (default, Jan 8 2020, 19:59:22) [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-176-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.13.0.dev20220913+cpu
[pip3] torchaudio==0.13.0.dev20220913+cpu
[pip3] torchvision==0.14.0.dev20220913+cpu
[conda] blas 1.0 mkl
[conda] mkl 2020.2 256
[conda] mkl-service 2.3.0 py37he8ac12f_0
[conda] mkl_fft 1.3.0 py37h54f3939_0
[conda] mkl_random 1.1.1 py37h0573a6f_0
[conda] numpy 1.19.2 py37h54aff64_0
[conda] numpy-base 1.19.2 py37hfa32c7d_0
[conda] torch 1.13.0.dev20220913+cpu pypi_0 pypi
[conda] torchaudio 0.13.0.dev20220913+cpu pypi_0 pypi
[conda] torchvision 0.14.0.dev20220913+cpu pypi_0 pypi

**Comment by malfet** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/85294

(Also, examples are slightly invalid, as bitwise ops are not implemented for float tensor)
