### ISSUE TITLE
Nested matmul is broken when the nested tensors are >2D

### ISSUE THREAD

**Issue by mikaylagawarecki** [pytorch/pytorch#85064]
### 🐛 Describe the bug

This snippet breaks when the nested tensors are 3-D
```
a = torch.arange(2 * 4).reshape(1, 2, 4)
b = torch.arange(5 * 4).reshape(1, 5, 4)
nt = torch.nested_tensor([a, b], dtype=torch.float)
nt.matmul(nt.transpose(2, 3))
# RuntimeError: self must be a matrix
```

This snippet works fine when the nested tensors are 2-D

```
a = torch.arange(2 * 4).reshape(2, 4)
b = torch.arange(5 * 4).reshape(5, 4)
nt = torch.nested_tensor([a, b], dtype=torch.float)
nt.matmul(nt.transpose(1, 2))

# nested_tensor([
#   tensor([[ 14.,  38.],
#           [ 38., 126.]]),
#   tensor([[  14.,   38.,   62.,   86.,  110.],
#           [  38.,  126.,  214.,  302.,  390.],
#           [  62.,  214.,  366.,  518.,  670.],
#           [  86.,  302.,  518.,  734.,  950.],
#           [ 110.,  390.,  670.,  950., 1230.]])
# ])
```

The error message seems to come from [this check that `self.dim() == 2` in the meta func for mm](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/LinearAlgebra.cpp#L69). Might be because we use `unbind` [and then `mm`](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/nested/NestedTensorMath.cpp#L910) on the nested tensors. `torch.matmul` allows N-d matrices though

### Versions

1.13.0.dev20220914+cpu

cc @cpuhrsch @jbschlosser @bhosmer @drisspg

**Comment by vadimkantorov** [comment]
if matmul is performed across the last dim (which is actually the only option now) and nestedtensor layout is codified, unbind+rebind is not necessary, right? matmul with the inner contig representation should be already correct, right? cc @cpuhrsch

**Comment by mikaylagawarecki** [comment]
Sorry, looking at this again, it might just be an edge case for when batch_size=1.
