### ISSUE TITLE
Investigate binary validation failure nightly linux 3.9 cuda 11.6

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#85085]
### 🐛 Describe the bug

Failure:
https://github.com/pytorch/builder/actions/runs/3018052016/jobs/4939894670

```
done

+ conda run -p conda-env-3018052016 python3 ./test/smoke_test/smoke_test.py
ERROR conda.cli.main_run:execute(41): `conda run python3 ./test/smoke_test/smoke_test.py` failed. (See above for error)
Traceback (most recent call last):
  File "/root/work/builder/builder/./test/smoke_test/smoke_test.py", line 5, in <module>
    import torchaudio
  File "/root/work/builder/builder/conda-env-3018052016/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/root/work/builder/builder/conda-env-3018052016/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/root/work/builder/builder/conda-env-3018052016/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/root/work/builder/builder/conda-env-3018052016/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/root/work/builder/builder/conda-env-3018052016/lib/python3.9/site-packages/torch/_ops.py", line 481, in load_library
    ctypes.CDLL(path)
  File "/root/work/builder/builder/conda-env-3018052016/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```

### Versions

nightly 1.13

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra @weiwangmeta

**Comment by malfet** [comment]
Why do you think it's a high priority? Also, it would be nice to point out when the last known working build were produced.

**Comment by atalman** [comment]
yes, its probably torchaudio. created here because we want to fix it for a release, adding issues from other repos in release milestones seems like not possible . high priority because of the release schedule

**Comment by fduwjj** [comment]
When I try to install nightly build pytorch, I got torch vision with cu 102. Is this expected?

pytorch-nightly/linux-64::torchvision-0.14.0.dev20220915-py39_cu102

**Comment by atalman** [comment]
True you are right, I see this as well hence this is the reason of the failure:
  torchaudio         pytorch-nightly/linux-64::torchaudio-0.13.0.dev20220915-py39_cu116
  torchvision        pytorch-nightly/linux-64::torchvision-0.14.0.dev20220915-py39_cu102

**Comment by atalman** [comment]
This issue is no longer applicable, nightly build works: https://github.com/pytorch/builder/actions/runs/3018052016/jobs/4987874543

output of test:
```
+ conda run -p conda-env-3018052016 python3 ./test/smoke_test/smoke_test.py
torch: 1.13.0.dev20220919
torchvision: 0.14.0.dev20220919
torchaudio: 0.13.0.dev20220919
torch cuda: 11.6
torch cudnn: 8302
Is torchvision useable? True
```

**Comment by atalman** [comment]
Still failing on todays run: https://github.com/pytorch/builder/actions/runs/3091755112

**Comment by malfet** [comment]
Ok, so it looks like the problem is pretty simple (although devious):
 - torchvision nightlies are build against whatever version that is currently available on conda (i.e. if conda build/upload for whatever reason fails, it will be build against previous nightly version)
 - torchaudio follows the same pattern, but seems to be adding fake version
 

When conda tries to resolve version, it picks 10.2 as we do not mark 10.2 (which depends on `[cudatoolkit](https://anaconda.org/anaconda/cudatoolkit)` and as such does not conflicts with selected pytorch-cudatoolkit==11.6

Anyway, it would be good to check available versions in validation script and barf out if they are incompatible.

**Comment by atalman** [comment]
Here is what I propose to add:

1 - In Addition to torch CUDA checks:
https://github.com/pytorch/builder/blob/main/test/smoke_test/smoke_test.py#L17
Add torchvision and torchaudio cuda check

2 - We should validate that all nightly binaries come from same date, and its recent date no more then 2 days ago like this:
torch: 1.13.0.dev20220919
torchvision: 0.14.0.dev20220919
torchaudio: 0.13.0.dev20220919

3. - Extend test to validate basic libcudnn and libcublas tests. - Will be useful for new CUDA 11.7 pypi package

**Comment by izaitsevfb** [comment]
I believe this issue is resolved?

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/builder/pull/1145 should already address 1 and 2. Working on No.3 now.
