### ISSUE TITLE
DISABLED test_scatter_full_optim_state_dict_nested_use_multiple_param_groups_True_wrap_alt_False_use_diff_optim_inputs_True (__main__.TestFSDPOptimState)

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#85092]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_scatter_full_optim_state_dict_nested_use_multiple_param_groups_True_wrap_alt_False_use_diff_optim_inputs_True)).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @pietern @SciPioneer

**Comment by awgu** [comment]
Closing this in case it was related to parallelizing distributed test:
https://github.com/pytorch/pytorch/pull/86756
Apologies if that is not the reason, and we will revisit.
