### ISSUE TITLE
The tensor constructed by torch.tensor(t) and t.clone().detach() have different behavior

### ISSUE THREAD

**Issue by DoubleVII** [pytorch/pytorch#85094]
### 📚 The doc issue

# Issue description
[As the documentation mentions](https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor), letting `t` be a tensor, `torch.tensor(t)` is equivalent to `t.clone().detach()`. But the detached tensor cannot perform the `squeeze_` or `unsqueeze_` operation while the one constructed by `tensor` can.

## To reproduce
```python
t = torch.randn((3,))
torch.tensor(t).unsqueeze_(1)
```
The above code runs successfully.
```python
t = torch.randn((3,))
t.clone().detach().unsqueeze_(1)
```
The above code throws an exception:
```
RuntimeError: set_storage_offset is not allowed on a Tensor created from .data or .detach().
```
What is the difference between them?
Should I use `tensor` instead of `clone` and `detach` considering robustness, even though the documentation recommends the latter.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by bdhirsh** [comment]
On master, this runs successfully. This was probably fixed by https://github.com/pytorch/pytorch/pull/83590, so it should end up in the 1.13 release.
