### ISSUE TITLE
[ONNX][bug] `nn.Transformer` contains unsupported tensor scalar type

### ISSUE THREAD

**Issue by sharvil** [pytorch/pytorch#85116]
### 🐛 Describe the bug

PyTorch fails to export a model containing an `nn.Transformer` module. It fails with `RuntimeError: unexpected tensor scalar type`. Here's a minimal repro script:

```python
import torch
import torch.nn as nn


class M(nn.Module):
  def __init__(self):
    super().__init__()
    self.transformer = nn.Transformer(d_model=128)

  def forward(self, x, y):
    return self.transformer(x, y)


module = M()
module = torch.jit.script(module)
x = torch.randn([10, 1, 128])
y = torch.randn([10, 1, 128])
dummy_input = (x, y)
torch.onnx.export(module, dummy_input, 'test.onnx', verbose=True, opset_version=14)
```

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.27

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-118-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.0
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.942
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytest-mypy==0.9.1
[pip3] torch==1.12.1+cu113
[pip3] torch-tb-profiler==0.3.1
[pip3] torch-tensorrt==1.1.0
[pip3] torchtext==0.11.0a0+d697db5
[conda] libblas                   3.9.0            12_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            12_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            12_linux64_mkl    conda-forge
[conda] magma-cuda112             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-include               2021.3.0           h06a4308_520  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.12.1+cu113             pypi_0    pypi
[conda] torch-tb-profiler         0.3.1                    pypi_0    pypi
[conda] torch-tensorrt            1.1.0                    pypi_0    pypi
[conda] torchtext                 0.11.0a0+d697db5          pypi_0    pypi
```

**Comment by justinchuby** [comment]
@BowenBao There are three places in our code base that will raise "unexpected tensor scalar type". #84659

**Comment by sharvil** [comment]
@justinchuby, to clarify: I expect that the sample code I provided executes without any errors. This is not a diagnostic issue; rather, it's a bug in either the exporter such that it can't handle `nn.Transformer` or a bug in `nn.Transformer` where it's written in a way that it cannot be exported.

**Comment by sharvil** [comment]
FYI, this bug is a regression from earlier releases. The same code snippet I provided above exports successfully when installed with `pip install torch==1.11 --extra-index-url https://download.pytorch.org/whl/cu113`.

**Comment by justinchuby** [comment]
@sharvil Understood. Thanks for the info! We are in the process of improving diagnostics so this is relevant. Please feel free to share thoughts if you have any suggestions!

**Comment by justinchuby** [comment]
Notes: is_cuda, is_grad_enabled

**Comment by justinchuby** [comment]
I am able to export the non-scripted version of the module with the latest pytorch-nightly. Does that work for you?

**Comment by sharvil** [comment]
Yes, that works. The non-scripted version works on 1.12.1 as well, though, so this bug is kinda different.

FWIW, I'm attempting to script because JIT on my actual network (not the minified version I pasted here) takes ~45 mins to export on a trivial sequence of 3 elements. And when I try to run that network, I get random results. The network is a basic autoregressive loop with a Transformer core and a decode loop of 32 steps.

**Comment by justinchuby** [comment]
Thanks for the info. I was not able to reproduce yet because apparently nn.Transformer introduced new ops it uses internally the onnx exporter doesn't yet support. So I haven't been able to get to the type error.

@BowenBao any suggestions? I don't think it's possible to trace only the Transformer and script the rest of the decoder?

**Comment by BowenBao** [comment]
@justinchuby what you mentioned is probably achievable, but I'm more curious as how it regress from 1.11. It could be though that `nn.Transformer` has changed.

**Comment by justinchuby** [comment]
Apparently there is a `_nested_tensor_from_mask` op being used since 4 months ago 

https://github.com/pytorch/pytorch/blame/4cfd09d7bc51f700373a3ee633776bdc903f9cde/torch/nn/modules/transformer.py

**Comment by BowenBao** [comment]
Now I observe `torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'prim::is_cuda' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues`

**Comment by thiagocrepaldi** [comment]
We are not planning adding new ops to torch.onnx.export API. Please try `torch.onnx.dynamo_export` and reopen this issue with an updated repro if the issue persists
