### ISSUE TITLE
torch.nn.functional.conv1d/2d/3d crash with floating point exception

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#85111]
### 🐛 Describe the bug

`torch.nn.functional.conv1d`, `torch.nn.functional.conv2d`, and `torch.nn.functional.conv3d` crash with floating point exception when `groups=0`

```
import torch
torch.nn.functional.conv1d(input=torch.ones((1,1,1)),weight=torch.ones((1,1,1)),groups=0)
```
```
import torch
torch.nn.functional.conv2d(input=torch.ones((1,1,1,1)),weight=torch.ones((1,1,1,1)),groups=0)
```
```
import torch
torch.nn.functional.conv3d(input=torch.ones((1,1,1,1,1)),weight=torch.ones((1,1,1,1,1)),groups=0)
```

As well as `torch.nn.functional.conv_transpose1d`, `torch.nn.functional.conv_transpose2d`, and `torch.nn.functional.conv_transpose3d`

Reproducing code:
```
torch.nn.functional.conv_transpose1d(input=torch.ones((1,1,1)),weight=torch.ones((1,1,1)),groups=0)
torch.nn.functional.conv_transpose2d(input=torch.ones((1,1,1,1)),weight=torch.ones((1,1,1,1)),groups=0)
torch.nn.functional.conv_transpose3d(input=torch.ones((1,1,1,1,1)),weight=torch.ones((1,1,1,1,1)),groups=0)
```

Output:
```
Floating point exception (core dumped)
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220913+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.6 (default, Jan 8 2020, 19:59:22) [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-176-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.13.0.dev20220913+cpu
[pip3] torchaudio==0.13.0.dev20220913+cpu
[pip3] torchvision==0.14.0.dev20220913+cpu
[conda] blas 1.0 mkl
[conda] mkl 2020.2 256
[conda] mkl-service 2.3.0 py37he8ac12f_0
[conda] mkl_fft 1.3.0 py37h54f3939_0
[conda] mkl_random 1.1.1 py37h0573a6f_0
[conda] numpy 1.19.2 py37h54aff64_0
[conda] numpy-base 1.19.2 py37hfa32c7d_0
[conda] torch 1.13.0.dev20220913+cpu pypi_0 pypi
[conda] torchaudio 0.13.0.dev20220913+cpu pypi_0 pypi
[conda] torchvision 0.14.0.dev20220913+cpu pypi_0 pypi

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by khushi-411** [comment]
Hi,
I think setting `groups = 0` makes no sense as there will always be at least one input to pass through the layers. You can re-read the definition of groups in the [documentation](https://pytorch.org/docs/stable/generated/torch.nn.functional.conv3d.html).

**Comment by DNXie** [comment]
@khushi-411  Hi, thanks for looking into this. I agree `groups=0` may not be as practical. Although it would be great if it could be better handled with a clear exception message instead of a floating point exception, which is a crash.

**Comment by TestSomething22** [comment]
There is an existing issue (https://github.com/pytorch/pytorch/issues/71080) about such error and is closed by a pull request. I don't know why it still exists in the latest version

**Comment by bdhirsh** [comment]
Looks like this is still an issue on latest master (I'll remove the high-pri based on the above comments and the previous github issue though)

**Comment by Lezcano** [comment]
The issue was fixed at a module level, rather than at an operator level. We should change the error from Python to C++. We would accept a PR for this one.

**Comment by Thytu** [comment]
Hi, would be happy to contribute.

Would adding a `TORCH_CHECK`  at [ContextConv2D create](https://github.com/pytorch/pytorch/blob/e9d0f5fb17ad30939b7217f1a1d0552a6d005ba0/aten/src/ATen/native/xnnpack/Convolution.cpp#L172) be enough?

i.e
```py
TORCH_CHECK(groups > 0, error_message)
```

**Comment by XiaobingSuper** [comment]
@Thytu ,  you can add this check at https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Convolution.cpp#L538, this function is about checking the convolution's parameters. Thanks!

**Comment by Lezcano** [comment]
Acthally, I would recommend putting it at https://github.com/pytorch/pytorch/blob/dadd89a8a60f80222b8f3c3bdb83440b902c737b/aten/src/ATen/native/Convolution.cpp#L1311 in the `_convolution` function, as it's the entry point of all the convolutions. The function pointed by @XiaobingSuper only checks the shape, not the other parameters.

And yes, `TORCH_CHECK` is the right function (macro) to user :)

**Comment by Thytu** [comment]
Thanks @XiaobingSuper and @Lezcano, really appreciate your help!

Without a little boost it's hard to know where to start when it's our first PR to the code-base haha.

The PR should come in the next 24/48h (the time to install everything and familiar myself with the suits test)
