### ISSUE TITLE
Is there has some best nlp framework  process text  data  suitable  with  cpp libtorch ?

### ISSUE THREAD

**Issue by mullerhai** [pytorch/pytorch#85137]
### 🐛 Describe the bug

HI Dear Libtorch Team:
             when I first use  cpp libtorch to process the text data feel  difficult ,I  don't know any nlp framework in cpp writen and suitable with libtorch cpp, I know  the opencv cpp is suitable with libtorch in visual domain. but nlp cpp framework I don't know ,also for the recommend system cpp, do we have some sklearn framework like   skorch  in cpp version  ?https://github.com/skorch-dev/skorch 

thanks

### Versions

libtorch 1.12.1
macos
cpp 17

**Comment by bdhirsh** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
