### ISSUE TITLE
torch.nn.PixelShuffle crash with floating point exception when input has 0 size in the last three dimensions

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#85155]
### 🐛 Describe the bug

`torch.nn.PixelShuffle` crash with floating point exception when input has 0 size in the last three dimensions

```
import torch
layer = torch.nn.PixelShuffle(1)

model_input = torch.ones((1,1,1,1,0))
pred = layer(model_input)
```

Also crash when input is 
```
model_input = torch.ones((1,1,1,1,0))
model_input = torch.ones((1,1,1,0,1))
model_input = torch.ones((1,1,0,1,1))
```

Output:
```
Floating point exception (core dumped)
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220915+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.6 (default, Jan  8 2020, 19:59:22)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-176-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.13.0.dev20220915+cpu
[pip3] torchaudio==0.13.0.dev20220915+cpu
[pip3] torchvision==0.14.0.dev20220915+cpu
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.3.0            py37h54f3939_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.2           py37h54aff64_0  
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] torch                     1.13.0.dev20220915+cpu          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220915+cpu          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220915+cpu          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by bdhirsh** [comment]
Marking hi-pri for the crash (I can reproduce on master)

**Comment by Thytu** [comment]
Hi, would like to contribute if possible :) 

What the expected behaviour would be? An error raised by torch?

Would adding a `TORCH_CHECK` to [check_pixel_shuffle_shapes](https://github.com/pytorch/pytorch/blob/26c136a135fe0215195a6e0566651baaffb01159/aten/src/ATen/native/PixelShuffle.cpp#L12) be enough? 

i.e:
```py
TORCH_CHECK(self.size(-1) > 0, error_message, upscale_factor);
TORCH_CHECK(self.size(-2) > 0, error_message, upscale_factor);
TORCH_CHECK(self.size(-3) > 0, error_message, upscale_factor);
```
(ofc it's just a dummy exampleà

**Comment by Lezcano** [comment]
I don't see any reason why `torch` shouldn't support these inputs. It seems to me that the correct behaviour if the output in `pixel_shuffle_cpu` and `math_pixed_shuffle` is zero, then we should just not call the kernel and return the (empty) output.
What do you think?

**Comment by Thytu** [comment]
Roger that, submitting a PR for this is the following day(s)

**Comment by lucyjin3** [comment]
Can I work on this issue as my first-time contribution?

**Comment by mruberry** [comment]
> Can I work on this issue as my first-time contribution?

Of course! Anyone can

**Comment by Thytu** [comment]
> Can I work on this issue as my first-time contribution?

Hey, you can take a look at #85347

PR is still not ready as I currently don't know yet how to fix the _grad_ issue but taking a look at it can save you some times 🙂
