### ISSUE TITLE
torch.sparse.sampled_addmm does not behave the same on CPU and GPU

### ISSUE THREAD

**Issue by srossross** [pytorch/pytorch#85169]
## To reproduce 

```py
In [19]: torch.sparse.sampled_addmm(torch.eye(5).to_sparse_csr(), torch.zeros([5,0]), torch.zeros([0,5]), alpha=0.6, beta=0.2)
Out[19]: 
tensor(crow_indices=tensor([0, 1, 2, 3, 4, 5]),
       col_indices=tensor([0, 1, 2, 3, 4]),
       values=tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000]), size=(5, 5),
       nnz=5, layout=torch.sparse_csr)

In [20]: torch.sparse.sampled_addmm(torch.eye(5, device='cuda:0').to_sparse_csr(), torch.zeros([5,0], device='cuda:0'), torch.zeros([0,5], device='cuda:0'), alpha=0.6, beta=0.2)
Out[20]: 
tensor(crow_indices=tensor([0, 1, 2, 3, 4, 5]),
       col_indices=tensor([0, 1, 2, 3, 4]),
       values=tensor([1., 1., 1., 1., 1.]), device='cuda:0', size=(5, 5),
       nnz=5, layout=torch.sparse_csr)
```

The CPU case returns `0.2,0.2,0.2,0.2,0.2` and the CUDA case returns `1,1,1,1,1`

From @amjames 

> The cuda impl has an early exit when either of the dense args are empty (.numel() == 0, because of a bug/undocumented requirement in the CuSparseBackend). It needs to scale the result beforehand and it does not. The cpu impl is not an issue because the backend kernel handles empty matrices correctly so there is no early exit

found as a part of https://github.com/pytorch/pytorch/pull/85011

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.0 (default, Nov 15 2020, 14:28:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-147-generic-x86_64-with-glibc2.27
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[conda] numpy                     1.21.6                   pypi_0    pypi

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by amjames** [comment]
Specifically here: 

https://github.com/pytorch/pytorch/blob/d8eae6283db867a1abd75df0a86b1a48faef3043/aten/src/ATen/native/sparse/cuda/SparseBlas.cpp#L58-L61

We exit without scaling the result by `beta`
