### ISSUE TITLE
[ONNX] Revisit to abstract out the effect of operator export type

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#85170]
- https://github.com/pytorch/pytorch/pull/84382#discussion_r973282372

**Comment by thiagocrepaldi** [comment]
Cool, that would be a great opportunity to create a design for https://github.com/pytorch/pytorch/pull/84382 and expand to fit this functionality

https://github.com/microsoft/onnx-converters-private/issues/87 has some feedback on what I could gather from some code reading, bug fixing on issues related to new symbolics, etc
