### ISSUE TITLE
[JIT] Don't support empty tuple literal

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8518]
Operator level test example failure:

```
======================================================================
ERROR: test_permute_scalar (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3473, in script_fn
    CU = torch.jit.CompilationUnit(script)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 352, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 358, in define
    self.module._define(lang, rcb, False)
RuntimeError: expected ident but found ')' here:

def the_method(i0):
    return i0.permute(())
                       ~ <--- HERE
```

Affected tests:
- `test_permute_scalar`
- `test_reshape_scalar_to_scalar`
- `test_view_scalar_to_scalar`
- `test_expand_scalar_to_scalar`

**Comment by jramseyer** [comment]
Hey @jamesr66a are you still seeing these test failures?  I just re-ran the tests, and these tests pass for me now.

**Comment by jamesr66a** [comment]
@jramseyer yes still seeing it. Make sure you remove the entry for e.g. `test_permute_scalar` from the autogen test blacklist before running: https://github.com/pytorch/pytorch/blob/master/test/test_jit.py#L4574

**Comment by jramseyer** [comment]
I'm confused here--are these the test failures in test_jit or test_autograd?  Seems like autograd and jit share test names, and they pass in autograd but are blacklisted in jit.  The issue was opened for autograd, though.  

Is test_jit running test_autograd's tests?  

(Sorry for the questions; I'm new to the project).

**Comment by jamesr66a** [comment]
Hey @jramseyer, admittedly this is confusing. I made these tasks before Zach had made some revisions to the tests and moved them to test_jit. So ignore the fact that the issue says `test_autograd`, it's in fact talking about the failure in test_jit

**Comment by jramseyer** [comment]
Ah, okay, I understand.  Thanks for the explanation!  I'll un-blacklist and try to fix the test_jit behaviors.

**Comment by jramseyer** [comment]
Can you point me to where we define tuples?  I've been unable to find it.  

Quick question: what's the desired behavior here?   Do we want to add support for empty tuples "()" or to fail when parsing them?  Supporting () makes sense to me.

**Comment by jamesr66a** [comment]
Sure,

* Here's where we convert a python AST Typle node into a ListLiteral tree view: https://github.com/pytorch/pytorch/blob/feaee219688c771a12a20cfa001495411ae735f8/torch/jit/frontend.py#L432. Afaict that's already correct
* In the string frontend parser, I believe we'll hit this case when parsing that tuple argument https://github.com/pytorch/pytorch/blob/feaee219688c771a12a20cfa001495411ae735f8/torch/csrc/jit/script/parser.h#L61 which expects at least one expr, so it's failing once it it's the end paren. That should get fixed up so we can emit a similar ListLiteral instance as in the Python AST frontend


Using the Python AST frontend here's an example:

```
import torch

@torch.jit.script
def the_method(i0):
    return i0.permute(())

print(the_method.graph)
```

Which errors out with:

```
RuntimeError: expected a non-empty list of Tensors (infer_type at /Users/jamesreed/onnx-fairseq/pytorch/torch/lib/tmp_install/include/ATen/Functions.h:1126)
frame #0: torch::jit::script::createStack(torch::jit::Graph&, torch::jit::script::SourceRange const&, at::ArrayRef<torch::jit::Value*>) + 1132 (0x10356fefc in _C.cpython-36m-darwin.so)
frame #1: torch::jit::script::tryMatchSchema(torch::jit::FunctionSchema const&, torch::jit::script::SourceRange const&, torch::jit::Graph&, at::ArrayRef<torch::jit::NamedValue>, at::ArrayRef<torch::jit::NamedValue>, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 3702 (0x1035724d6 in _C.cpython-36m-darwin.so)
```

So I believe this function (https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/compiler.cpp#L270) will have to be updated to accomodate empty tuples. Hope this helps you get started!

**Comment by jramseyer** [comment]
Ah, this is very helpful!  Thank you very much!  Now I know where things are.  Thanks!

**Comment by ezyang** [comment]
@jramseyer You want to add a `Note [...]` about this in the first location you tried to find these docs at? :)

**Comment by jamesr66a** [comment]
can you check if it works in the string frontend? i.e. instantiate the same thing via `torch.jit.CompilationUnit()`. We may still need lexer + parser changes

**Comment by jramseyer** [comment]
Sure!  I can check that.

**Comment by jramseyer** [comment]
For that, all we want is torch.jit.CompilationUnit(()), correct?  No other special syntax?

**Comment by jramseyer** [comment]
Still fails for CompilationUnit; I will investigate.

**Comment by jramseyer** [comment]
This should be an allowable test, right?

import torch
def something(io):
    return torch.jit.CompilationUnit(())

something(2)

Just want to check to make sure the syntax is good.

**Comment by jramseyer** [comment]
Ah, ok, I understand!  Thanks for all of your explanations; I really appreciate it!

**Comment by jramseyer** [comment]
Got it working; I'll send a PR soon.  thanks!

graph(%i0 : Dynamic) {
  %2 : int[] = prim::ListConstruct()
  %3 : Dynamic = aten::permute(%i0, %2)
  return (%3);
}
