### ISSUE TITLE
Readme typos

### ISSUE THREAD

**Issue by zaharkogan** [pytorch/pytorch#85182]
### 📚 The doc issue

I've noticed some issues were present in the README file, fixed them + scanned the file with Grammarly.

### Suggest a potential alternative/fix

I've created a [pull request](https://github.com/pytorch/pytorch/pull/85150).

cc @svekars @holly1238

**Comment by yuguo68** [comment]
close this issue as https://github.com/pytorch/pytorch/pull/85150 closed
