### ISSUE TITLE
Activation functions for sparse tensors.

### ISSUE THREAD

**Issue by sambaPython24** [pytorch/pytorch#85208]
### 🚀 The feature, motivation and pitch

Hello, 

in my model, I would like to apply a non-linear function such as the [ReLU](https://pytorch.org/docs/stable/generated/torch.nn.ReLU.html)  module or the [torch.nn.functional.relu](https://pytorch.org/docs/stable/generated/torch.nn.functional.relu.html) function to a [sparse](https://pytorch.org/docs/stable/sparse.html) tensor but get a ```NotImplementedError```. 
Could the common activation functions be implemented for sparse tensors?

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by ezyang** [comment]
as a hack you can directly apply the activation on the values() of the sparse tensor

**Comment by sambaPython24** [comment]
Thank you, but is the chain of functions 
- ```read out values of sparse tensor```
- ```apply activation function to them```
- ```assign values back to the original tensor```
differentiable/does it break the autograd mechanism?

**Comment by ezyang** [comment]
Instead of writing back the values, just construct a new sparse tensor with the new values and the old indices, and it should be differentiable

**Comment by gau-nernst** [comment]
When working `torch.sparse`, this is also a major source of frustration for me. Constructing a new sparse tensor does not retain `.is_coalesced()` property, thus it requires the user to keep calling the expensive `.coalesce()` operation (for backward pass), even though the underlying indices are unchanged.

It will be great if PyTorch allows direct operations on `.values` data of sparse tensor. If it is supported, all element-wise operations will work on sparse tensor. I think it is also the approach by PyTorch Geometric team, by maintaining two separate tensors for indices and values, so manipulating them is much more convenient.

I guess there are constraints faced by PyTorch, such as differentiability and various backends, so it is not simple to allow such a thing.

**Comment by amjames** [comment]
@sambaPython24 I have submitted a patch which will add the missing support for ReLU. 

@gau-nernst If you are missing support for another such function please open an issue, we plan to support any zero preserving unary function but we are aware some are still missing.

**Comment by sambaPython24** [comment]
Is it going to be available in the next version or in the nightly preview?

**Comment by amjames** [comment]
This will not make it into 1.13, but will be included in the next nightly after it merges.
