### ISSUE TITLE
[JIT] Don't support torch.Size() in the script

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#8520]
Operator-level tests fail. Example failure:

```
======================================================================
ERROR: test_reshape_size (__main__.TestAutogradGenerated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_autograd.py", line 3665, in do_test
    check(name)
  File "test/test_autograd.py", line 3592, in check
    fn, (self_variable,) + args_variable)
  File "test/test_autograd.py", line 3498, in check_against_reference
    outputs_test = func(*nograd_inputs)
  File "test/test_autograd.py", line 3473, in script_fn
    CU = torch.jit.CompilationUnit(script)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 352, in __init__
    self.define(lang, _frames_up=_frames_up + 1)
  File "/data/users/zdevito/pytorch/torch/jit/__init__.py", line 358, in define
    self.module._define(lang, rcb, False)
RuntimeError: 
unknown builtin op:

def the_method(i0):
    return i0.reshape(torch.Size([25, 5]))
                      ~~~~~~~~~~ <--- HERE
```

Affected tests:
- `test_reshape_size`
- `test_view_size`

**Comment by zou3519** [comment]
torch.Size is almost the same thing as a tuple; if we wanted to support it would treating it like a tuple work?

**Comment by fmassa** [comment]
BTW, the main reason why we created `torch.Size` was to be able to use the legacy `torch.Tensor` constructor, which was overloaded on size / data.
Now that we are mainly moving towards having a data constructor `torch.tensor` and a size constructor `torch.empty`, I believe we could deprecate at some point `torch.Size`, and once (if) we drop support for `torch.Tensor` altogether, we can probably just make `tensor.size()` return a tuple as well.

**Comment by remzr7** [comment]
@fmassa when might torch.Tensor be deprecated? What's the best way to deal with torch.Size when using JIT at the moment?
