### ISSUE TITLE
RuntimeError: stride == cur_contig_stride || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by Kait0** [pytorch/pytorch#85209]
### 🐛 Describe the bug

The following runtime error ocurred when I ran inference on a model that was trained with jit script.
I set the following environment variable for debugging: PYTORCH_NVFUSER_DISABLE=fallback

the model is created with:
model = torch.jit.script(MyModel())

During the forward pass:
pred = model(input1, input2)

the following runtime error occurs during inference:
> RuntimeError: The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript (most recent call last):
> RuntimeError: stride == cur_contig_stride || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\torch\\csrc\\jit\\codegen\\cuda\\executor_utils.cpp":597, please report a bug to PyTorch. Vectorization of T0_g[ iS58{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * T0.size[1] ), 4) ), 1) ), 128) )}, iS57{1}, iS55{4}, iS59{128}, sbS2{1} ] with word size 4 not possible due to invalid stride. Domain: iS55{4}, stride: 3

During training the following warning occurs but otherwise the model runs fine:
> C:\miniconda\envs\TIL\lib\site-packages\torch\autograd\__init__.py:175: UserWarning: operator () profile_node %919 : int[] = prim::profile_ivalue(%917)
>  does not have profile information (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\codegen\cuda\graph_fuser.cpp:108.)
>   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Education N
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: N/A

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 980
Nvidia driver version: 516.94
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==0.7.1
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchvision==0.13.1+cu113
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch-lightning         0.7.1                    pypi_0    pypi
[conda] torch                     1.12.1+cu113             pypi_0    pypi
[conda] torchaudio                0.12.1+cu113             pypi_0    pypi
[conda] torchvision               0.13.1+cu113             pypi_0    pypi

Process finished with exit code 0

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by cwlseu** [comment]
Same RuntimeError at detectron2/tests/test_export_torchscript.py
```txt
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: stride == cur_contig_stride || size == 1 || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor_utils.cpp":623, please report a bug to PyTorch. Vectorization of T3_g[ iS97{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * 1 ), 2) ), 1) ), 128) )}, iS96{1}, iS94{2}, iS98{128} ] with word size 2 not possible due to invalid stride. Domain: iS97{( ceilDiv(( ceilDiv(( ceilDiv(( T0.size[0] * 1 ), 2) ), 1) ), 128) )}, stride: 4
```

**Comment by Kait0** [comment]
Unfortunately I can't share the code for this error.

**Comment by iremyux** [comment]
@Kait0 
I understand. Is it possible for you to describe the steps to reproduce the error then? If you followed a specific tutorial or any other resource, they may be quite useful for me to understand the root of problem.

**Comment by Kait0** [comment]
You might be able to reproduce the error if you try to JIT compile the [backbone](https://github.com/autonomousvision/transfuser/blob/a7d4db684c160095dec03851aff5ce92e36b2387/team_code_transfuser/model.py#L564) in this [repository](https://github.com/autonomousvision/transfuser). I did something similar.
You might need to change a few things to make it Jit compilable in the first place.
TIMM backbones were two regnety_032 I think.

**Comment by Kait0** [comment]
Can probably be closed since torch jit got replaced by pytorch 2.0 compile function anyway.
