### ISSUE TITLE
Add `persistent` option to `nn.Module.buffers`.

### ISSUE THREAD

**Issue by randolf-scholz** [pytorch/pytorch#85235]
### 🚀 The feature, motivation and pitch

For convenience, it would be nice if the [`nn.Module.buffers`](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.buffers) could distinguish between persistent and non-persistent buffers.

```python
def buffers(self, recurse: bool = False, persistent: Optional[bool] = None) -> Iterator[Tensor]:
```

Which yields an iterator for either only persistent buffers (`True`), non-persistent buffers (`False`) or both (`None`).

### Additional context

Currently, one either has to make use of the private attribute `nn.Module._non_persistent_buffers_set`, or filter `self.buffers` via the entries of the `state_dict`.

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by ezyang** [comment]
You know what, sure, send us a patch (with persistent as kwarg only) and I'll review it.
