### ISSUE TITLE
Crash with Segmentation fault in `torch.le`

### ISSUE THREAD

**Issue by jdanceze** [pytorch/pytorch#85251]
### 🐛 Describe the bug

Passing a tensor with 3 or more dimensions to `out` in `torch.le`, can lead to crash with Segmentation fault.

## code

```python
import torch

input = torch.tensor(1)
other = torch.tensor([1]) 
out = torch.empty(3, 4, 5)

torch.le(input,other,out=out)
```
## output
```bash
Segmentation fault (core dumped)
```

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.12.1
[conda] Could not collect

**Comment by jdanceze** [comment]
Found that all of these function have the same issue
- `torch.less(input,other,out=out)`
- `torch.less_equal(input,other,out=out)`
- `torch.logaddexp(input,other,out=out)`
- `torch.logaddexp2(input,other,out=out)`
- `torch.logical_and(input,other,out=out)`
- `torch.logical_or(input,other,out=out)`
- `torch.logical_xor(input,other,out=out)`
- `torch.lt(input,other,out=out)`
- `torch.maximum(input,other,out=out)`
- `torch.minimum(input,other,out=out)`
- `torch.mul(input,other,out=out)`
- `torch.multiply(input,other,out=out)`
- `torch.ne(input,other,out=out)`
- `torch.nextafter(input,other,out=out)`

**Comment by malfet** [comment]
Should probably be fixed by https://github.com/pytorch/pytorch/pull/85294
