### ISSUE TITLE
[CV] Optimize the Large Kernel DepthWise convolutions (LKDWconvs) with `nn.Conv2d` to be faster than the counterpart of `megengine`

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#85252]
### 🚀 The feature, motivation and pitch

I'm learning about [RepLKNet](https://arxiv.org/abs/2203.06717) and found, so far, the LKDWconv (Large Kernel DepthWise Convolutions) with `nn.Conv2d` had been much slower than the counterpart with [megengine](https://github.com/MegEngine). This difference could be shown in the [[test_code]](https://gist.github.com/songyuc/a8f5f3ca2bc06d506291fd2b0cc2dedf).

cc @VitalyFedyunin @ngimel

**Comment by vadimkantorov** [comment]
Maybe related: https://github.com/pytorch/pytorch/issues/18631 https://github.com/pytorch/pytorch/issues/13716 https://github.com/pytorch/pytorch/issues/75747

**Comment by ngimel** [comment]
Duplicate of #74363
