### ISSUE TITLE
Visualize nightly periodic tests on HUD

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#85295]
cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
To be frank, not sure what this task is about. Perhaps a more detailed description would be helpful.

**Comment by atalman** [comment]
This is completed, Link: https://hud.pytorch.org/hud/pytorch/builder/main/1?per_page=50&name_filter=cron
