### ISSUE TITLE
Crash in `torch.nn.utils.parametrize.ParametrizationList`

### ISSUE THREAD

**Issue by jdanceze** [pytorch/pytorch#85328]
### 🐛 Describe the bug

Invoking `torch.nn.utils.parametrize.ParametrizationList`, where `modules` is a tensor with device='meta', can cause a crash with Aborted (core dumped).

## code

```python
import torch

modules = torch.empty(1, device='meta')
original = torch.ones([1])
torch.nn.utils.parametrize.ParametrizationList(modules=modules, original=original)

```
## output

```bash
terminate called without an active exception
Aborted (core dumped)
```

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.12.1
[conda] Could not collect

cc @ezyang @eellison @bdhirsh @soumith

**Comment by ezyang** [comment]
also doesn't crash on master

```
(/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/torchdynamo$ python b.py
Traceback (most recent call last):
  File "b.py", line 5, in <module>
    torch.nn.utils.parametrize.ParametrizationList(modules=modules, original=original)
  File "/raid/ezyang/pytorch-scratch2/torch/nn/utils/parametrize.py", line 105, in __init__
    super().__init__(modules)
  File "/raid/ezyang/pytorch-scratch2/torch/nn/modules/container.py", line 266, in __init__
    self += modules
  File "/raid/ezyang/pytorch-scratch2/torch/nn/modules/container.py", line 307, in __iadd__
    return self.extend(modules)
  File "/raid/ezyang/pytorch-scratch2/torch/nn/modules/container.py", line 357, in extend
    self.add_module(str(offset + i), module)
  File "/raid/ezyang/pytorch-scratch2/torch/nn/modules/module.py", line 443, in add_module
    torch.typename(module)))
  File "/raid/ezyang/pytorch-scratch2/torch/__init__.py", line 253, in typename
    return o.type()
RuntimeError: Unimplemented backend Meta
```
