### ISSUE TITLE
Crash in `torch.optim.Optimizer`

### ISSUE THREAD

**Issue by jdanceze** [pytorch/pytorch#85327]
### 🐛 Describe the bug

Invoking `torch.optim.Optimizer`, where `params` is a tensor with device='meta', can cause a crash with Aborted (core dumped).

## code
```python
import torch

params = torch.empty(1, device='meta')
torch.optim.Optimizer(params=params, defaults=[])
```

## output
```bash
terminate called without an active exception
Aborted (core dumped)
```

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.12.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @eellison @bdhirsh @soumith

**Comment by ezyang** [comment]
This does not repro for me on master

```
$ python b.py
Traceback (most recent call last):
  File "b.py", line 4, in <module>
    torch.optim.Optimizer(params=params, defaults=[])
  File "/raid/ezyang/pytorch-scratch2/torch/optim/optimizer.py", line 54, in __init__
    torch.typename(params))
  File "/raid/ezyang/pytorch-scratch2/torch/__init__.py", line 253, in typename
    return o.type()
RuntimeError: Unimplemented backend Meta
```
