### ISSUE TITLE
Simultaneously using `torch.no_grad` and `autocast` causes `RuntimeError: expected scalar type Half but found Float` for some operations.

### ISSUE THREAD

**Issue by krenerd** [pytorch/pytorch#85340]
### 🐛 Describe the bug

Using `no_grad`, `autocast` simultaneously causes `RuntimeError: expected scalar type Half but found Float` for some operations. 
The following code can be reproduced in COLAB. 

```Python
import torchvision
import torch

from torch.cuda.amp import GradScaler, autocast

model = torchvision.models.vit_b_16().to("cuda")
model.eval()
with torch.no_grad():
    with autocast():
        y_vert_pred = model(torch.randn(16, 3, 224, 224).to("cuda"))

```

Out: `RuntimeError: expected scalar type Half but found Float`

However, 

```Python
model = torchvision.models.resnet50().to("cuda")
model.eval()
with torch.no_grad():
    with autocast():
        y_vert_pred = model(torch.randn(16, 3, 224, 224).to("cuda"))
```

and 

```Python
model = torchvision.models.vit_b_16().to("cuda")
model.eval()

with autocast():
    y_vert_pred = model(torch.randn(16, 3, 224, 224).to("cuda"))
```

works. Although I'm not familiar with how amp works under the hood, this behaviour certainly doesn't make sense to me. Is there a reason why `torch.no_grad` and `autocast` can't be used in conjunction for some operations?

### Versions

PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.14 (default, Sep  8 2022, 00:06:44)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

cc @mcarilli @ptrblck

**Comment by ezyang** [comment]
this passes on master, try upgrading to a nightly

**Comment by krenerd** [comment]
Thanks, @ezyang, it does seem so. I recently noticed that changing the order of `autocast` and `no_grad` fixes the issue, which is potentially understandable. Perhaps the original code was syntactically incorrect. 

```
import torchvision
import torch

from torch.cuda.amp import GradScaler, autocast

model = torchvision.models.vit_b_16().to("cuda")

with autocast():
  with torch.no_grad():
    y_vert_pred = model(torch.randn(16, 3, 224, 224).to("cuda"))

```

**Comment by ezyang** [comment]
Nyeh, that's not supposed to make a difference lol. 

_native_multi_head_attention is a known problem that was recently fixed https://github.com/pytorch/pytorch/issues/84396
