### ISSUE TITLE
[ONNX] Comprehensive and automated testing

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#85363]
Currently the ONNX conversion tests are manually created and sometimes fails with untested input data types. We should leverage PyTorch's testing infrastructure to create more comprehensive tests.

This will help us detect errors like #85316

How MPS tests the ops: https://github.com/pytorch/pytorch/pull/83743/files

Leverage OpInfo and module infos: 

https://github.com/pytorch/pytorch/blob/d3dec8097b847fc46755ef06ea6ff90eebc846eb/torch/testing/_internal/opinfo/core.py#L297

https://github.com/pytorch/pytorch/blob/d3dec8097b847fc46755ef06ea6ff90eebc846eb/torch/testing/_internal/common_modules.py#L1037

cc @BowenBao @wschin @abock

**Comment by AllenTiTaiWang** [comment]
Is this similar to https://github.com/pytorch/pytorch/issues/84659, or something can be worked together?

**Comment by justinchuby** [comment]
Can you elaborate?
