### ISSUE TITLE
docker pulls failing with no space left on disk

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#85362]
## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.
mitigated

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
docker pull fails with no space left on disk

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
earliest known on master: 00a1065286ef9b425cfe1d74d76b7ab5555eee83 at 10:15 AM	
<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
Looks like it is caused by the change in provisioning script: runners that work in CI are attached to 150Gb EBS volume (i-02c2b96fed1710840 for example), while failing ones (i-083df22d57b8c6112 for example) has only 10Gb EBS volumes attached to them

**Comment by malfet** [comment]
Ok, somehow we are spinning runners with 2 labels: `linux.large` and `linux.2xlarge` at the same time:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/2453524/191373391-09e89521-68aa-4090-91e1-e84aefe3cfed.png">

**Comment by malfet** [comment]
Ok, as far as I understand, what happened is the following: https://github.com/pytorch/test-infra/commit/e7634c52cb39e09ad2b59b8288cc271129c4eed6 added a logic to pass extra labels to every allocated runners, which for some mysterious reason is setup to `linux.2xlarge` in https://github.com/fairinternal/pytorch-gha-infra/blob/main/runners/main.tf 

As result, GH started to run our build jobs on `linux.large` runners, which only had 10Gb of diskspace.

I've mitigated the issue by https://github.com/pytorch/test-infra/commit/7bc79e475b7436f332e57a4e86c87dfad444d8eb 
and also changing the environment variable on scale-up lambda to `linux.huge`

**Comment by malfet** [comment]
Hmm, ok, not fully mitigated, I need to deal with those as well:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/2453524/191382071-717c2755-77aa-40db-bac9-de4a9af5b91c.png">

**Comment by kit1980** [comment]
> Ok, as far as I understand, what happened is the following: [pytorch/test-infra@e7634c5](https://github.com/pytorch/test-infra/commit/e7634c52cb39e09ad2b59b8288cc271129c4eed6) added a logic to pass extra labels to every allocated runners, which for some mysterious reason is setup to `linux.2xlarge` in https://github.com/fairinternal/pytorch-gha-infra/blob/main/runners/main.tf
> 
> As result, GH started to run our build jobs on `linux.large` runners, which only had 10Gb of diskspace.

If the added label is `linux.2xlarge`, why GH started to run the jobs on `linux.large` runners?

**Comment by kit1980** [comment]
> I've mitigated the issue by [pytorch/test-infra@7bc79e4](https://github.com/pytorch/test-infra/commit/7bc79e475b7436f332e57a4e86c87dfad444d8eb)

I've commented on the commit, there is a typo in the instance_type name, not sure how it still works.

**Comment by kit1980** [comment]
> If the added label is `linux.2xlarge`, why GH started to run the jobs on `linux.large` runners?

I think I get it now. The instances were really `linux.large`, but the label made them look like they can handle `linux.2xlarge` jobs.

**Comment by clee2000** [comment]
> I've commented on the commit, there is a typo in the instance_type name, not sure how it still works.

fixed the typo but ill let @malfet decide when to revert the mitigation

**Comment by malfet** [comment]
> > If the added label is `linux.2xlarge`, why GH started to run the jobs on `linux.large` runners?
> 
> I think I get it now. The instances were really `linux.large`, but the label made them look like they can handle `linux.2xlarge` jobs.

Yes, essentially everything instance that got allocated today by our autoscaling infrastructure have additional `linux.2xlarge` label, including Windows runners, gpu runners, etc
