### ISSUE TITLE
[ONNX: feature request]: support for linalg_pinv/ svd

### ISSUE THREAD

**Issue by fairydora** [pytorch/pytorch#85371]
### 🚀 The feature, motivation and pitch

Hello, I'm trying to export my model to ONNX.
I'm using the Savitzky-Golay filter to smooth my latent space along the temporal dimension, before decoding it to a sequence of 3d meshes.
The filter's implementation contains the linalg_pinv operator which is not supported by ONNX.
(error: "the operator linalg_pinv to ONNX opset version 13 is not supported.")
I'm wondering if I could request this support to be implemented? :)  Alternatively, could at least the svd decomposition be supported?
Thank you,

**Comment by AllenTiTaiWang** [comment]
I think SVD is tracked https://github.com/onnx/onnx/issues/3839 =>PR: https://github.com/onnx/onnx/pull/4416
More discussion on #81084

**Comment by jinfagang** [comment]
@titaiwangms After look into all these circled issues, still  can not found any clue support for SVD in torch2.0?
