### ISSUE TITLE
[ONNX] Exporting the operator ::max_unpool2d to ONNX

### ISSUE THREAD

**Issue by HarmonyHu** [pytorch/pytorch#85388]
### 🚀 The feature, motivation and pitch

Exporting the operator ::max_unpool2d to ONNX.

Try to convert [SegNet](https://github.com/vinceecws/SegNet_PyTorch/blob/master/SegNet.py) to onnx, with command below:
``` shell
net = SegNet()
input = torch.randn(1,3,224,224)
torch.onnx.export(
    net,                  # pytorch model
    input,      # input (tuple for multiple inputes)
    "segnet.onnx",          # onnx model to save
    export_params=True,        # store the trained parameter weights inside the model file
    opset_version=13,          # the ONNX version to export the model to
    do_constant_folding=True,  # whether to execute constant folding for optimization
    input_names=['input'],   # the model's input names
    output_names=['output'],  # the model's output names
)
```

it failed with message:
```
torch.onnx.symbolic_registry.UnsupportedOperatorError: Exporting the operator ::max_unpool2d to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

### Additional context

root@73c4a19564a5:/workspace/github# python collect_env.py
Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.20.0
Libc version: glibc-2.26

Python version: 3.7.5 (default, Dec  9 2021, 17:04:37)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.9.2+cpu
[conda] Could not collect

**Comment by AllenTiTaiWang** [comment]
https://github.com/onnx/onnx/blob/main/docs/Operators.md#MaxUnpool

**Comment by AllenTiTaiWang** [comment]
Looks like in MaxUnpool, torch has different Op from aten:
https://github.com/pytorch/pytorch/blob/913f5784d74bb69eff12b1cf9ac8c3d222750411/torch/nn/functional.py#L951-L980

They have an integration on parameters to get `output_size`, so I can't get those parameters in onnx converter (downstream), and `kernal_size` is a must for this Op. I will see if there's other way around.

**Comment by janofsun** [comment]
Hi Allen @AllenTiTaiWang , are you still working on this issue? I am willing to contribute to this one if you may. But I may need some of your guidance. Thank you!

**Comment by AllenTiTaiWang** [comment]
Hi, please feel free to start a PR on this. Thanks!

**Comment by AllenTiTaiWang** [comment]
A workaround: https://github.com/pytorch/pytorch/issues/25088#issuecomment-1090956803
