### ISSUE TITLE
[FSDP] Fix communication hook docs

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#85385]
### 📚 The doc issue

Communication hook is not documented correctly, the hook also takes in a `state` object which is not indicated: https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/fully_sharded_data_parallel.py#L4136

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by mrshenli** [comment]
fixed as in https://github.com/pytorch/pytorch/blob/5f881ac2d1d7aae5f73d91cf8c27d63ed1d94fed/torch/distributed/fsdp/fully_sharded_data_parallel.py#L1786
