### ISSUE TITLE
[FSDP] MixedPrecision, CPUOffload, BackwardPrefetch etc should be documented

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#85386]
### 📚 The doc issue

These are auxiliary data structures that do not show up in master documentation, should fix before 1.13 release: https://pytorch.org/docs/master/fsdp.html?highlight=fullyshardeddataparallel#torch.distributed.fsdp.FullyShardedDataParallel

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by mrshenli** [comment]
Reserving this task to help onboard IBM contributors

**Comment by spzala** [comment]
Hello @rohan-varma @mrshenli While referring to the docs, I noticed that the fsdp [doc file](https://pytorch.org/docs/master/fsdp.html?highlight=fullyshardeddataparallel#torch.distributed.fsdp.MixedPrecision) you have mentioned in the issue description was updated after the issue reporting date under different PRs for different data structures (MixedPrecision, CPUOffload, BackwardPrefetch)  (e.g. `mixed_precision` in this [PR](https://github.com/pytorch/pytorch/pull/88429/files ), and a related doc to add classes under this [PR](https://github.com/pytorch/pytorch/pull/87917/files) e.g. the [mixed_precision class](https://github.com/pytorch/pytorch/pull/87917/files#diff-6cb2bc8832db1f4d4076a15c4b697c9550e676f8a392b39088260361d47f01a3R77) with doc. I am curious if that satisfies the doc requirements as requested in this issue or if more needs to be done? Thanks!
