### ISSUE TITLE
DecompCrossRefMode not dispatching correctly

### ISSUE THREAD

**Issue by fdrocha** [pytorch/pytorch#85405]
### 🐛 Describe the bug

I came across this while working on https://github.com/pytorch/pytorch/pull/85403.

I had to implement decompositions both for both `upsample_bicubic2d.default` and `upsample_bicubic2d.vec`.
The second one is `CompositeExplicit` and just calls the first, so it seems I should haven't had to implement it?
However, if I don't, then then default decomp is never called in the relevant tests in `test/test_decomp.py`.

You can check this by commenting out the `upsample_bicubic2d_vec` in `torch/_decomp/decompositions.py` in the branch above and adding an `assert False` to first line of `upsample_bicubic2d_default`. If you then run `pytest tests/test_decomp.py -vk interpolate_bicubic` you can see that the assert never triggers.

Any thoughts @ezyang, @ngimel, @jansel, @Chillee?

### Versions

https://github.com/pytorch/pytorch/pull/85403

cc @Chillee @ezyang @zou3519 @albanD @samdow

**Comment by ezyang** [comment]
Unfortunately this is expected. CompositeExplicit are opaque from the perspective of torch dispatch mode, you don't get to "see through" them.

In your quoted PR, why don't you just do a straight transcription of the CompositeExplicit kernel, instead of duping the full logic?

**Comment by fdrocha** [comment]
> Unfortunately this is expected. CompositeExplicit are opaque from the perspective of torch dispatch mode, you don't get to "see through" them.
> 
> In your quoted PR, why don't you just do a straight transcription of the CompositeExplicit kernel, instead of duping the full logic?

Sorry, not sure I understand the difference between the two alternatives. Could you please clarify?

**Comment by ezyang** [comment]
It may break extension writers, but we have the latitude to make this sort of change. But I'm not sure it's right; there must have been a reason someone wrote an explicit AD formula for this case...

**Comment by lezcano** [comment]
Closing this issue as it's expected behaviour.
