### ISSUE TITLE
mps on apple m1 seems incorrect in matrix multiplication

### ISSUE THREAD

**Issue by cauchy7203** [pytorch/pytorch#85406]
### 🐛 Describe the bug

See the following code, 

```python
import torch

N = 3

A = torch.rand([N,N],dtype=torch.float32)*2 - 1
B = torch.rand([N,N],dtype=torch.float32)*5 - 2.5

C = A @ B


device = torch.device('mps')

aa = A.to(device)
bb = B.to(device)
cc = aa @ bb
```

see the difference:

```python
print(cc.cpu() - C)
>>>
tensor([[-0.4171,  0.6648, -1.4077],
        [-0.4928,  0.7844, -2.0337],
        [ 1.8749, -2.9994,  1.7512]])
```

Abviously, the correct result of `cc.cpu() - C` should be a zero-valued matrix.

### Versions

1.12.0 for macos (torch-nightly)

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @kulinseth @albanD

**Comment by cauchy7203** [comment]
> 

btw, the macbook is: macbook pro, m1, 13 inch (2020).

**Comment by leovinus2001** [comment]
When I see your testcase, it reminds me of issue #81185 where NaN were observed together with the use of torch.rand() More specifically, there are testcases there for CPU and MPS torch.mm() that you might find useful in narrowing down the issue. In particular, is your observation the same issue as #81185 or different :) ? The following comment might be a start

https://github.com/pytorch/pytorch/issues/81185#issuecomment-1229571793

**Comment by cauchy7203** [comment]
> [leovinus2001](/leovinus2001)

Thanks for reply!

I have read the issue you mentioned, but it is different to my obvervation.

There is NO ERROR during conversion of the data from CPU to GPU (no `NaN` appears).

I repeat the above code again, and you may see the matrix A (on cpu) and aa (on mps), they are the same:
```python
# this is aa on GPU
tensor([[ 0.5255, -0.9316,  0.0885],
        [ 0.9530, -0.7145, -0.7237],
        [ 0.3007,  0.9739, -0.9347]], device='mps:0')

# this is A on CPU
tensor([[ 0.5255, -0.9316,  0.0885],
        [ 0.9530, -0.7145, -0.7237],
        [ 0.3007,  0.9739, -0.9347]])
```

The results of the multiplication are not the same, and I didn't find any `NaN` issues:

```python

# cc -- the multiplication on GPU

tensor([[ 0.6661, -0.5107, -0.8595],
        [ 0.1683,  1.4892,  0.1642],
        [-0.9340,  2.8247,  1.6085]], device='mps:0')

# C -- the multiplication on CPU

tensor([[-0.8219, -1.0997,  1.7780],
        [ 0.1301, -1.3871,  2.9537],
        [ 1.7954,  0.4726,  0.0359]])
```

**Comment by leovinus2001** [comment]
Thanks for the insight. As I have been away for a while, I'll see whether I can find some time this week to reproduce on my end.

**Comment by cauchy7203** [comment]
I do not think the issue is caused by `torch.rand`, because from the above results we can confirm that the matrices A and B on CPU and CPU are the same. I can confirm the problem is caused by the overloaded operator `@` on mps.

Follow your idea I also tested it.

```python

mat_A = torch.Tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

mat_B = torch.Tensor([[9,8,7],
                      [6,5,4],
                      [5,4,3]])

mat_C = mat_A @ mat_B

# now let's put the matrice mat_A and mat_B to GPU:

mps_A = mat_A.to(device)
mps_B = mat_B.to(device)
mps_C = mps_A @ mps_B
```

We first check the matrices on GPU:

```python
print(mps_A)
print(mps_B)
```
[Output]:
```python
tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.0000, 6.0000],
        [7.0000, 8.0000, 9.0000]], device='mps:0')
tensor([[9.0000, 8.0000, 7.0000],
        [6.0000, 5.0000, 4.0000],
        [5.0000, 4.0000, 3.0000]], device='mps:0')
```

Thus this confirms that the values on CPU will not be changed when it is converted to GPU.




And the multilication results:

```python
print('mat_C on cpu:',mat_C)
print('mps_C on gpu:',mps_C)
```
[Output]:
```python
mat_C on cpu: tensor([[ 36.,  30.,  24.],
        [ 96.,  81.,  66.],
        [156., 132., 108.]])
mps_C on gpu: tensor([[ 46.0000,  28.0000,  22.0000],
        [118.0000,  73.0000,  58.0000],
        [190.0000, 118.0000,  94.0000]], device='mps:0')
```

It is easy to see that the result on CPU is correct, but the result on GPU is wrong.

**Comment by leovinus2001** [comment]
That is very interesting. Squinting my eyes on the "mps_C on gpu" result, I wonder whether the GPU result is different by a transpose() ? Actually, you can do a

print (mat_A @ mat_B.transpose(0,1))

and that gives exactly your GPU matrix result
tensor([[ 46.,  28.,  22.],
        [118.,  73.,  58.],
        [190., 118.,  94.]])

So, does your test case demonstrate that "mps_C on gpu:" is lacking (or doing an extra) transpose when mat_B is on the GPU? A precise problem description helps with a quick fix.

**Comment by cauchy7203** [comment]
You're right! !

Within your code, it prints:

```python
tensor([[ 46.,  28.,  22.],
        [118.,  73.,  58.],
        [190., 118.,  94.]])
```
Now it is excactly the same to that on GPU:
```python
mps_C on gpu: tensor([[ 46.0000,  28.0000,  22.0000],
        [118.0000,  73.0000,  58.0000],
        [190.0000, 118.0000,  94.0000]], device='mps:0')
```

But, is it a bug? 

Or you made it intendedly?  If so, why?

Please!

**Comment by cauchy7203** [comment]
> 

I can confirm your guess is correct now, because I tested it several times on random matrices. 

It is just the case all the operations `A @ B` are executed as `A @ B.T` on GPU(mps).

**Comment by leovinus2001** [comment]
Cool! So now to the next question - does torch.mm() exhibit the same issue as "@", or not?

Rational - actually, I am unfamiliar with the "@" operator. I just wonder whether "some" difference with torch.mm() is to blame?

In other words, is there still a MPS problem when you use
mat_C = torch.mm(A,B)
instead of
mat_C = mat_A @ mat_B
?

**Comment by cauchy7203** [comment]
The same case:

```python

import torch

N = 3

A = torch.rand([N, N], dtype=torch.float32)*2 - 1
B = torch.rand([N, N], dtype=torch.float32)*5 - 2.5

# C = A @ B.T

C = torch.mm(A, B.T)


device = torch.device('mps')

aa = A.to(device)
bb = B.to(device)
# cc = aa @ bb

cc = torch.mm(aa, bb)

# results:(also only truncated errors)

tensor([[ 1.1921e-07,  0.0000e+00, -8.5682e-08],
        [-5.9605e-08,  0.0000e+00,  1.1921e-07],
        [ 0.0000e+00,  0.0000e+00,  1.1921e-07]])
```


BTW, I have checked similar operator `@` in numpy, and it is an overloaded operator in the nd-array classed. And in PyTorch, it is the same case.


i. e. `A @ B` is absolutely the same to `torch.mm(A, B)` for tensors (Tensor()).


So based on my guess, the bug may be:

1. When overloading (or mapping) the operator `@`, someone might use the code like `return torch.mm(A @ B.T)`?
2. Or maybe you have rewrite the `torch.mm` and make transposition of `B` (the right matrix) somewhere.

**Comment by cauchy7203** [comment]
This doc may help I guess: https://docs.python.org/3/library/operator.html#mapping-operators-to-functions

<img width="651" alt="image" src="https://user-images.githubusercontent.com/9944333/192108689-f10dd1a3-7866-4375-b8bc-c057fce34e87.png">

It is actually the case that the Python itself maps `@` as the function `matmult`, so there must be a (private) method in `Tensor` or `tensor` that is defined like:

```python
def __matmul__(self, other):
      # return the reuslt of self * other 
```

So I guess it is most likely that someone has transposed the right matrix in these lines.


BTW: I have to sleep now. Hope my findings might help, and wait for your good news!

Thank you very much!

**Comment by DenisVieriu97** [comment]
> 1.12.0 for macos (torch-nightly)

@cauchy7203 thanks for the report.
This issue should be already fixed in the latest pytorch nightly (**1.13.0**.dev20220924) - could you please give a try to that and let me know if you still see any issues? Thanks!

**Comment by cauchy7203** [comment]
> > 1.12.0 for macos (torch-nightly)
> 
> @cauchy7203 thanks for the report. This issue should be already fixed in the latest pytorch nightly (**1.13.0**.dev20220924) - could you please give a try to that and let me know if you still see any issues? Thanks!

Thank you very much for your reply. I found that the version I used was "1.13.0.dev20220924".

Now I upgraded the version to "1.13.0.dev20220924", and run the tests on random matrices again, the bug has already been fixed.

```python
import torch

N = 3

A = torch.rand([N, N], dtype=torch.float32)*2 - 1
B = torch.rand([N, N], dtype=torch.float32)*5 - 2.5

# C = A @ B.T

C = torch.mm(A, B)


device = torch.device('mps')

aa = A.to(device)
bb = B.to(device)
# cc = aa @ bb

cc = torch.mm(aa, bb)

print(cc.cpu()-C)
print('mse:', ((cc.cpu()-C)**2).sum())

# results:(only truncated errors appear again)
tensor([[-1.4901e-08,  2.2352e-08,  0.0000e+00],
        [ 0.0000e+00, -2.3842e-07,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
mse: tensor(5.7565e-14)
```

Thank you very much for your help! 

It seems that I should update more frequently when I try to use the preview version of torch.

**Comment by malfet** [comment]
Should we close the issue then? (Especially if this case is now covered by unittests?)

**Comment by kulinseth** [comment]
Yeah I think we should close this issue , it’s part of test consistency . @cauchy7203 please reopen the issue if you have any concerns

**Comment by cauchy7203** [comment]
> Yeah I think we should close this issue , it’s part of test consistency . @cauchy7203 please reopen the issue if you have any concerns

Yes. 

Thank you all guys for help!
