### ISSUE TITLE
LibTorch's torch::cat() crashes in debug mode

### ISSUE THREAD

**Issue by nethtrick** [pytorch/pytorch#85404]
## Issue description

torch::cat() crashes in debug mode using CPU tensors and LibTorch 1.12. The error is "invalid IListRef tag" at line 403 of ATen/core/IListRef.h:
```
"false INTERNAL ASSERT FAILED at \"C:\\\\actions-runner\\\\_work\\\\pytorch\\\\pytorch\\\\builder\\\\windows\\\\pytorch\\\\aten\\\\src\\\\ATen/core/IListRef.h\":403, please report a bug to PyTorch. invalid IListRef tag."
```

I downloaded the precompiled library via https://pytorch.org/get-started/locally/. I created a MSVC 2019 project and copied all the LibTorch DLL files into the same folder as the generated EXE. I had previously installed PyTorch via conda on this system, and I'm not sure if there is some issue there. Incidentally, the CPP code does not detect CUDA but my PyTorch installation does.

## Code example

```c++
#include <torch/all.h>
#include <iostream>

void main() 
{
  // Using "libtorch-win-shared-with-deps-debug-1.12.1+cu116", the following error occurs in torch::cat():
  // "false INTERNAL ASSERT FAILED at \"C:\\\\actions-runner\\\\_work\\\\pytorch\\\\pytorch\\\\builder\\\\windows\\\\pytorch\\\\aten\\\\src\\\\ATen/core/IListRef.h\":403, please report a bug to PyTorch. invalid IListRef tag."
  // But using Release version "libtorch-win-shared-with-deps-1.12.1+cu116", the following executes fine.
  // The same error occurs for the CPU-only debug version "libtorch-win-shared-with-deps-debug-1.12.1+cpu"
  // But does not occur for the CPU-only release version "libtorch-win-shared-with-deps-1.12.1+cpu"
  auto x = torch::rand({ 3, 3 });
  auto y = torch::rand({ x.size(0), 2 });
  auto z = torch::cat({ x,y }, 1);
  std::cout << x << std::endl;
  std::cout << y << std::endl;
  std::cout << z << std::endl;
}
```

## System Info
```
Collecting environment information...
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 5.3.0

Clang version: Could not collect
CMake version: version 3.20.0
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.3.109

GPU models and configuration: GPU 0: Quadro P1000
Nvidia driver version: 516.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.4.0
[pip3] torch==1.11.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-points-kernels==0.7.0
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h59b6b97_2  
[conda] mkl                       2021.4.0           haa95532_640  
[conda] mkl-service               2.4.0            py39h2bbff1b_0  
[conda] mkl_fft                   1.3.1            py39h277e83a_0  
[conda] mkl_random                1.2.2            py39hf11a4ad_0  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] numpy-base                1.21.5           py39hca35cd5_3  
[conda] numpydoc                  1.4.0            py39haa95532_0  
[conda] pyg                       2.0.4           py39_torch_1.11.0_cu113    pyg
[conda] pytorch                   1.11.0          py3.9_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-cluster           1.6.0           py39_torch_1.11.0_cu113    pyg
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-scatter           2.0.9           py39_torch_1.11.0_cu113    pyg
[conda] pytorch-sparse            0.6.13          py39_torch_1.11.0_cu113    pyg
[conda] pytorch-spline-conv       1.2.1           py39_torch_1.11.0_cu113    pyg
[conda] torch-points-kernels      0.7.0                    pypi_0    pypi
[conda] torchaudio                0.11.0               py39_cu113    pytorch
[conda] torchvision               0.12.0               py39_cu113    pytorch
```

- PyTorch or Caffe2: LibTorch C++ API
- How you installed PyTorch (conda, pip, source): C++ download link from https://pytorch.org/get-started/locally/
- Build command you used (if compiling from source): N/A
- OS: Windows 10
- PyTorch version:
- Python version:
- CUDA/cuDNN version: Included in LibTorch 1.12 deps
- GPU models and configuration: NVIDIA Quadro P1000
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries: MSVC 2019

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ezyang** [comment]
cc @ysiraichi 

are you able to try on nightly?

**Comment by nethtrick** [comment]
Good call! I just tried it on the CUDA 11.7 nightly build and it works. Thank you.

**Comment by vandwalle** [comment]
This happens to me on Windows 10 with libtorch-win-shared-with-deps-1.12.1+cu116

Project compiled with VS 2019 :

		torch::Tensor t1=torch::rand({2,2});
		torch::Tensor t2=torch::rand({2,2});
		std::cout << "t1 = " << t1 << "\n";
		std::cout << "t2 = " << t2 << "\n";
		std::cout << torch::cat({t1,t2},1) << std::endl;
		
And crashes in the torch::cat() function.

Do we have a way to pick up a fix and is there a unit test that is implemented for torch::cat or other APIs on Windows, that I can monitor to check with release would have the fix?

**Comment by ysiraichi** [comment]
Hmm. It shouldn't happen on non-debug builds... I will have to check that.
Are the error messages the same?

> Do we have a way to pick up a fix

I think the only solution is to compile PyTorch yourself.

> is there a unit test that is implemented for torch::cat or other APIs on Windows, that I can monitor to check with release would have the fix?

We do have the Windows CIs... But they all seem to be passing.

**Comment by vandwalle** [comment]
Any help with getting the error message?

I am running torch from a sample VS 2019 application, (the ConsoleHello.exe from microsoft :) )

I don't get any crash log or message from torch. Is there something to enable?
