### ISSUE TITLE
_LRScheduler memory leak

### ISSUE THREAD

**Issue by Enolerobotti** [pytorch/pytorch#85410]
### 🐛 Describe the bug

There are reference cycles in `:meth:_LRScheduler.step`. To reproduce
```python
import gc
import torch
from torch.nn import Linear
from torch.optim import Adam
from torch.optim.lr_scheduler import MultiStepLR


def main():
    t = torch.randn(100, 100)
    model = Linear(100, 100)

    optimizer = Adam(params=model.parameters())
    scheduler = MultiStepLR(optimizer=optimizer, milestones=[1, 2, 3])
    t = model(t)
    t.sum().backward()
    optimizer.step()
    scheduler.step()


if __name__ == '__main__':
    gc.enable()
    gc.set_debug(gc.DEBUG_SAVEALL)
    main()
    garbage = gc.collect()

    try:
        assert not garbage, "Memory leak is occurred!"
    except AssertionError:
        import objgraph
        objgraph.show_backrefs(gc.garbage, filename='finalizers.png')
        raise
```
Please see the generated graph showing the cycle references.
I have to override the `step` on my end by moving this context manager https://github.com/pytorch/pytorch/blob/master/torch/optim/lr_scheduler.py#L146-L156 outside the method.
I hope you will fix it soon.

### Versions

$ python collect_env.py
Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] gpytorch==1.6.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] pytorch-lightning==1.5.4
[pip3] torch==1.11.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.3
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchmetrics==0.6.2
[conda] gpytorch                  1.6.0                    pypi_0    pypi
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] numpydoc                  1.2                      pypi_0    pypi
[conda] pytorch-lightning         1.5.4                    pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch-cluster             1.6.0                    pypi_0    pypi
[conda] torch-geometric           2.0.3                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.13                   pypi_0    pypi
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchmetrics              0.6.2                    pypi_0    pypi

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment]
this repros on master

**Comment by ngimel** [comment]
@alband points out that this is not an actual leak, but a ref-cycle induced holding on to memory. It would be cleared at the next gc run.

**Comment by Enolerobotti** [comment]
Anyway, users have to collect garbage manually.
