### ISSUE TITLE
[ONNX] RuntimeError: Dynamic shape axis should be no more than the shape dimension for mask_dynamic_axes_1

### ISSUE THREAD

**Issue by prashantskit** [pytorch/pytorch#85415]
### 🐛 Describe the bug

I am trying to convert tacotron2 model trained using nemo code base to onnx. And I am getting this error -> RuntimeError: Dynamic shape axis should be no more than the shape dimension for mask_dynamic_axes_1. Can anyone help me understand what is the meaning of this error and why this is coming. I could find others facing this in other forums but there is not resolution provided for it. Some of the issues are closed without any response/update. I would request you to kindly elaborate on the error and also help with the resolution. 

I am using this command to export the models 
```python
torch.onnx.export(decoder_iter, dummy_input, model.onnx",
                      opset_version=opset_version,
                      do_constant_folding=True,
                      input_names=["decoder_input",
                                   "attention_hidden",
                                   "attention_cell",
                                   "decoder_hidden",
                                   "decoder_cell",
                                   "attention_weights",
                                   "attention_weights_cum",
                                   "attention_context",
                                   "memory",
                                   "processed_memory",
                                   "mask"],
                      output_names=["decoder_output",
                                    "gate_prediction",
                                    "out_attention_hidden",
                                    "out_attention_cell",
                                    "out_decoder_hidden",
                                    "out_decoder_cell",
                                    "out_attention_weights",
                                    "out_attention_weights_cum",
                                    "out_attention_context"],
                      dynamic_axes={"attention_weights" : {1: "seq_len"},
                                    "attention_weights_cum" : {1: "seq_len"},
                                    "memory" : {1: "seq_len"},
                                    "processed_memory" : {1: "seq_len"},
                                    "mask" : {1: "seq_len"}
                                    "out_attention_weights" : {1: "seq_len"},
                                    "out_attention_weights_cum" : {1: "seq_len"}
                      }
                    )
```

Versions:
Pytorch - '1.12.1+cu102'
onnx - 1.12.0
opset - 11

```
    main()
  File "export_tacotron2_onnx.py", line 461, in main
    "out_attention_weights_cum" : {1: "seq_len"}
  File "/root/.cache/pypoetry/virtualenvs/tts-service-YwB4_FMF-py3.7/lib/python3.7/site-packages/torch/onnx/__init__.py", line 365, in export
    export_modules_as_functions,
  File "/root/.cache/pypoetry/virtualenvs/tts-service-YwB4_FMF-py3.7/lib/python3.7/site-packages/torch/onnx/utils.py", line 178, in export
    export_modules_as_functions=export_modules_as_functions,
  File "/root/.cache/pypoetry/virtualenvs/tts-service-YwB4_FMF-py3.7/lib/python3.7/site-packages/torch/onnx/utils.py", line 1085, in _export
    dynamic_axes=dynamic_axes,
  File "/root/.cache/pypoetry/virtualenvs/tts-service-YwB4_FMF-py3.7/lib/python3.7/site-packages/torch/onnx/utils.py", line 740, in _model_to_graph
    module=module,
  File "/root/.cache/pypoetry/virtualenvs/tts-service-YwB4_FMF-py3.7/lib/python3.7/site-packages/torch/onnx/utils.py", line 307, in _optimize_graph
    _C._jit_pass_onnx_set_dynamic_input_shape(graph, dynamic_axes, input_names)
RuntimeError: Dynamic shape axis should be no more than the shape dimension for seq_len
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.26

Python version: 3.7.5 (default, Dec  9 2021, 17:04:37)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-29-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.6.5
[pip3] torch==1.12.1
[pip3] torch-stft==0.1.4
[pip3] torchmetrics==0.9.3
[conda] Could not collect

**Comment by AllenTiTaiWang** [comment]
It means that there are inputs do not have axis 1 (It only has axis=0).

**Comment by AllenTiTaiWang** [comment]
We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

Thanks,
ONNX Converter team
