### ISSUE TITLE
C++ Memory Management API

### ISSUE THREAD

**Issue by collinmccarthy** [pytorch/pytorch#85436]
### 📚 The doc issue

I assume there should be a C++ memory management API like Python, since [Issue 14618](https://github.com/pytorch/pytorch/issues/14618) to do this was marked as completed. Does this API exist or no?

If not do I need to get the CUDA caching allocator and read from the `DeviceStats` struct, e.g. [here](https://github.com/pytorch/pytorch/blob/d23ce29761dbc0e817fa80dcd35d9b8d30f16bbb/c10/cuda/CUDACachingAllocator.h#L60)?  I'm assuming this isn't exactly future proof so I would rather not do this unless I have to.

### Suggest a potential alternative/fix

If you could point me to the "right way" to do this that would be sufficient.

cc @jbschlosser

**Comment by collinmccarthy** [comment]
Based on [this discussion](https://discuss.pytorch.org/t/minimal-memory-usage-in-c-interface/36596/6) it looks like this class `c10::cuda::CUDACachingAllocator` is the "C++ memory management API"?

I was able to get the memory stats by calling, e.g. `c10::cuda::CUDACachingAllocator::getDeviceStats(0);` for GPU 0.

**Comment by samdow** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/

**Comment by collinmccarthy** [comment]
@samdow It was a doc issue, the issue is there's no documentation even though the previous issue said it was implemented.
