### ISSUE TITLE
Mac M1 runners run out of space due to /System/Library/Caches/com.apple.coresymbolicationd

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#85440]
### 🐛 Describe the bug

Even after cleaning up conda installation in https://github.com/pytorch/pytorch/issues/84841, mac M1 runners still run out of disk space from time to time.  Digging a bit deeper, the cause this time is not GHA runner at all which uses only 14GB

```
du -h -d 1
764K	./.config
7.6G	./runner
4.4G	./Library
132K	./.ansible
4.0K	./.ssh
2.4G	./.cache
4.0K	./.conda
 14G	.
```

Looking into the server IO activities, they are from mdsync and coresymbolic processes. And the directory that grows in size is `/System/Library/Caches/com.apple.coresymbolicationd`

```
  0B	./com.apple.kext.caches
  0B	./com.apple.kernelcaches
  0B	./com.apple.CVMS
 41G	./com.apple.coresymbolicationd
  0B	./OnDemandResources
 41G	.
```

Some useful links people have found:

* https://apple.stackexchange.com/questions/83978/what-is-com-apple-coresymbolicationd-in-caches
* https://old.reddit.com/r/applehelp/comments/1zqbxw/comapplecoresymbolicationd_is_647_gb

We need to investigate this further to see how this can be addressed

### Versions

All mac M1 runners

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
This sums up my investigation on this so far:

* com.apple.coresymbolicationd records symbolic backtraces during the crash on Mac. The crash reports on the server can be found at `/Library/Logs/DiagnosticReports`
  * Not quite sure how to interpret the binary file under com.apple.coresymbolicationd yet.  There's little information about this around
* I'll look for a way to disable mds_store indexing on the runner.  The process mdsync was running during the issue.  I don't think we need it for anything

**Comment by huydhn** [comment]
After some further digging, I think I found the root cause for this issue. TLDR; I think we have a bad runner `i-0640cb6bb417f43bc`.  By querying Rockset, this issue happens 3 times in the past 2 days:

* https://github.com/pytorch/pytorch/actions/runs/3108736856/jobs/5038575059
* https://github.com/pytorch/pytorch/actions/runs/3108359440/jobs/5037724252
* https://github.com/pytorch/pytorch/actions/runs/3100798460/jobs/5021756601

All are on the same runner. Trying to run sysdiagnose shows some system service crashes that are likely related (`com.apple.mds`, `com.apple.mds_stores`, and  `com.apple.wifiFirmwareLoader`)

I still have no idea how to read the binary file under `com.apple.coresymbolicationd` but this's a fun topic for another day.  I will see how to replace that runner.

cc @seemethere

**Comment by huydhn** [comment]
Also I think we might want to disable mds service, but AFAIK, doing so would require temporarily reboot the runner to disable System Integrity Protection (SIP).  So it's a bit of a hassle

**Comment by ZainRizvi** [comment]
>  I think I found the root cause for this issue. TLDR; I think we have a bad runner i-0640cb6bb417f43bc

@seemethere can we replace that runner?

**Comment by malfet** [comment]
Removed `macos-m1-12` label from  `i-0640cb6bb417f43bc` so no future jobs will be scheduled on it

**Comment by huydhn** [comment]
A new runner has been put in place.  Resolving this now.

**Comment by ZainRizvi** [comment]
@huydhn  can we close this issue?

**Comment by huydhn** [comment]
Yeah, let's close this.  I haven't seen this issue again
