### ISSUE TITLE
ModuleNotFoundError: No module named 'torch.onnx.symbolic_registry'

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#85465]
### 🐛 Describe the bug

ModuleNotFoundError: No module named 'torch.onnx.symbolic_registry'

pytorch: 

```
 torch.__version__
'1.13.0.dev20220921+cu116'
>>> 

```

### Versions

 torch.__version__
'1.13.0.dev20220921+cu116'
>>>

**Comment by ADITYADAS1999** [comment]
I thing this will helpful for this issue 🤔

https://github.com/NVIDIA/retinanet-examples/issues/60

**Comment by jinfagang** [comment]
Unrelated. @ADITYADAS1999 .

Please take a look at pyotrhc master source code, seems they removed this API.

**Comment by AllenTiTaiWang** [comment]
Yes, we are refactoring registry https://github.com/pytorch/pytorch/issues/83787
@justinchuby Could you remind me here the usage of new API on registry?

**Comment by justinchuby** [comment]
We removed the registry in https://github.com/pytorch/pytorch/pull/84448. @jinfagang where does this error happen?

**Comment by ADITYADAS1999** [comment]
> 

yes i can't noticed that

**Comment by jinfagang** [comment]
@justinchuby this was related with mmcv, don't know if they catch up this modification or not. Latest nightly pytorch will break all their deploy code.

**Comment by justinchuby** [comment]
https://github.com/open-mmlab/mmcv/blob/fd3a1a16ea1d0b3def8719816007a5d6fd6b432e/mmcv/onnx/symbolic.py

@jinfagang thanks for letting us know! Would you be interested in helping us send a patch?

**Comment by jinfagang** [comment]
@justinchuby No.

**Comment by take-cheeze** [comment]
https://github.com/pytorch/pytorch/pull/84382 seems to be more relevant for this issue which is included in https://github.com/pytorch/pytorch/issues/83787

**Comment by take-cheeze** [comment]
Adding thin wrapper like https://github.com/pfnet/pytorch-pfn-extras/blob/468d85ccce8d7b4ec9c5e1b44fb485669fab93c3/pytorch_pfn_extras/onnx/symbolic_registry.py worked on my use
