### ISSUE TITLE
[onnx]Unsupported: ONNX export of convolution for kernel of unknown shape

### ISSUE THREAD

**Issue by Pirahno** [pytorch/pytorch#85464]
### 🐛 Describe the bug

I met this question when i convert my torch model to onnx ; 
I find it happend when I use the network output as the weight of the convolution, if the network output branch have some ops(like upsample), some paramters will be replace by glue operator（like concat）instead of Constant，so the convolution can‘t distinguish the shape of kernel；
```python
class Upsampling(nn.Module):
    def __init__(self):
        super().__init__()
        self.upsample = nn.Upsample(scale_factor=(2), mode='nearest') 
    
    def forward(self, input, weight):
        weight =  self.upsample(weight)
        return torch.nn.functional.conv2d(input, weight)
```
In opset 8,9,10，when I use size instead of scales in **nn.Upsample**, the scale written as **Constant**，it will not happen；
After opset 10， when I use size instead of scales in **nn.Upsample**, the scale written as glue operator（**Concat**(**Constant**, **Constant**)），it will show this problem；It is clear that the previous opset method is suitable for this situation，but the previous opset did not support many new operators.

Can you tell me what is the reason for updating this part of the code?

Thanks!

### Versions

Collecting environment information...
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: 11.3.109
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.2+cu113
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.11.3+cu113
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] torch                     1.10.2+cu113             pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.11.3+cu113             pypi_0    pypi

**Comment by AllenTiTaiWang** [comment]
I guess you are asking [Upsampling Deprecation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Upsample).
It's been deprecated, and we use Resize to do Upsampling since Opset 11.

**Comment by Pirahno** [comment]
> I guess you are asking [Upsampling Deprecation](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Upsample). It's been deprecated, and we use `Resize` to do Upsampling since Opset 11.

Thanks for your reply!  

I know Upsampling has been deprecated; My problem is when the input for convolutional weight passes through Upsampling , it will show the kernel of unknown shape. And I found In opset 8,9,10, the Upsampling written by **Constant**, like Constant[1, H, W, 1], it will not show this error; but in after opset version, the Upsampling written by Concat(Constant, Constant), it will show this error.

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/blob/833edeb020084377dcff27e8ef8b0a2af115fb27/torch/onnx/symbolic_helper.py#L1056-L1063

Looks like the concat is created here.

@Pirahno why is having concats an issue?

**Comment by justinchuby** [comment]
<img src="https://user-images.githubusercontent.com/11205048/193432597-4d9367ed-6719-4e96-b25a-3da31e8a23e4.png" width="200">

```python
import torch
from torch import nn

class Upsampling(nn.Module):
    def __init__(self):
        super().__init__()
        self.upsample = nn.Upsample(size=[2,2], mode='nearest')

    def forward(self, input, weight):
        weight =  self.upsample(weight)
        return torch.nn.functional.conv2d(input, weight)

torch.onnx.export(Upsampling(), (torch.tensor([[[[1,2],[1,2]]]], dtype=torch.float32), torch.tensor([[[[1]]]], dtype=torch.float32)), "test.onnx")
```

**Comment by Pirahno** [comment]
> <img alt="" width="200" src="https://user-images.githubusercontent.com/11205048/193432597-4d9367ed-6719-4e96-b25a-3da31e8a23e4.png">
> 
> ```python
> import torch
> from torch import nn
> 
> class Upsampling(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.upsample = nn.Upsample(size=[2,2], mode='nearest')
> 
>     def forward(self, input, weight):
>         weight =  self.upsample(weight)
>         return torch.nn.functional.conv2d(input, weight)
> 
> torch.onnx.export(Upsampling(), (torch.tensor([[[[1,2],[1,2]]]], dtype=torch.float32), torch.tensor([[[[1]]]], dtype=torch.float32)), "test.onnx")
> ```
When use **size** in nn.Upsample and in low opset version(opset<=10), it seems right, but when i ues **factor** or use high opset version(opset>=11), it will cause this problem.

**Comment by Pirahno** [comment]
> <img alt="" width="200" src="https://user-images.githubusercontent.com/11205048/193432597-4d9367ed-6719-4e96-b25a-3da31e8a23e4.png">
> 
> ```python
> import torch
> from torch import nn
> 
> class Upsampling(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.upsample = nn.Upsample(size=[2,2], mode='nearest')
> 
>     def forward(self, input, weight):
>         weight =  self.upsample(weight)
>         return torch.nn.functional.conv2d(input, weight)
> 
> torch.onnx.export(Upsampling(), (torch.tensor([[[[1,2],[1,2]]]], dtype=torch.float32), torch.tensor([[[[1]]]], dtype=torch.float32)), "test.onnx")
> ```

When use size in nn.Upsample and in low opset version(opset<=10), it seems right, but when i ues factor or use high opset version(opset>=11), it will cause this problem.

**Comment by Pirahno** [comment]
> <img alt="" width="200" src="https://user-images.githubusercontent.com/11205048/193432597-4d9367ed-6719-4e96-b25a-3da31e8a23e4.png">
> 
> ```python
> import torch
> from torch import nn
> 
> class Upsampling(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.upsample = nn.Upsample(size=[2,2], mode='nearest')
> 
>     def forward(self, input, weight):
>         weight =  self.upsample(weight)
>         return torch.nn.functional.conv2d(input, weight)
> 
> torch.onnx.export(Upsampling(), (torch.tensor([[[[1,2],[1,2]]]], dtype=torch.float32), torch.tensor([[[[1]]]], dtype=torch.float32)), "test.onnx")
> ```

When I use **size** in nn.Upsample and in low opset version(opset<=10), it seems right, but when i ues **factor** or use high opset version(opset>=11), it will cause this problem.

**Comment by justinchuby** [comment]
I was using size in a higher opset version. Do you see an error there? Could you share a script that can reproduce the error and point the error out in a screenshot? That would help a lot. Thanks!

**Comment by Pirahno** [comment]
> I was using size in a higher opset version. Do you see an error there? Could you share a script that can reproduce the error and point the error out in a screenshot? That would help a lot. Thanks!

when using size and opset = 11, 12…… , it will point this error;

when using factor it will point this error in any opset version;

**Comment by justinchuby** [comment]
Can you explain why having a Concat operator is an issue? I would assume you can still get the dimensions you need with onnx shape inferencing?

**Comment by Pirahno** [comment]
> 

I also don't understand why the shape of the weight didn't got. 
when i print the weight shape, i find the shape is (*, *, *, *).

`7 defined in (%7 : Float(*, *, *, *, strides=[4, 4, 2, 1], requires_grad=0, device=cpu) = onnx::Resize[mode="nearest"](%input, %6) # /opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:3712:0`

So I just guess if it's because the shape of the weight is not Constant when using Concat.

**Comment by justinchuby** [comment]
I see, thanks for the info. Can you test your example with the latest pytorch preview build (1.13) and report back? I was not able to reproduce. Note that the `(*, *, *, *)` shape is in PyTorch representation which is pre- onnx shape inferencing. You will need to examine the onnx proto (.onnx file) to find the info you need.

**Comment by Pirahno** [comment]
> I see, thanks for the info. Can you test your example with the latest pytorch preview build (1.13) and report back? I was not able to reproduce. Note that the `(*, *, *, *)` shape is in PyTorch representation which is pre- onnx shape inferencing. You will need to examine the onnx proto (.onnx file) to find the info you need.

lateset pytorch version still have this problem.

**Comment by Pirahno** [comment]
> 

thanks for your answer!

**Comment by parinitarahi** [comment]
@justinchuby should we consider this as closed.

**Comment by justinchuby** [comment]
Yes thanks!
