### ISSUE TITLE
[PyTorch] Output information about memory usage on OOM error

### ISSUE THREAD

**Issue by gothos-folly** [pytorch/pytorch#8549]
Currently when PyTorch encounters a cuda out-of-memory error it only prints a fixed error message and a stack trace. **It'd be nice if it also printed the size of the attempted allocation and a list of all existing allocations.**

Currently I'm using a [helper function](https://gist.github.com/gothos-folly/123b70f0cf992828f0d084673bf07d0d) that enumerates tensor objects, but that has limitations compared to a built-in solution:

* It doesn't show temporary allocations
* It doesn't know the size of the attempted allocation
* By the time the exception is printed the activations are already out of scope and freed. This can be worked around with narrowly scoped try-except blocks, but that's pretty annoying.

**Comment by SsnL** [comment]
The amounts of tensors might be on the scale of thousands, so it's probably no reasonable to print the list of tensors. Btw, your script doesn't detect tensors that only live in c++ side. You can use `torch.cuda.max_memory_allocated()` to get the current amount of memory used.

Printing the size of the attempted allocation is reasonable and I think we should do this.

**Comment by ezyang** [comment]
We print the size now.
