### ISSUE TITLE
[AO] In sparisty schedulers, rename `last_epoch` to steps

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#85492]
It's safer to define t, dt, n and t_0 in terms of steps instead of epochs, because when the data is large (takes days to run 1 epoch), users might want to prune within one epoch.

_Originally posted by @junesg in https://github.com/pytorch/pytorch/pull/85232#discussion_r977067386_

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by andrewor14** [comment]
cc @jcaip who has more context. It's been more than a year since this issue was opened. Is it still relevant or can we close this?

**Comment by jcaip** [comment]
Let's close for now, since this isn't a priority, but if someone else reading this later has a similar thought please feel free to reopen.

**Comment by jcaip** [comment]
Let's close for now, since this isn't a priority, but if someone else reading this later has a similar thought please feel free to reopen.
