### ISSUE TITLE
torch.fake_quantize_per_channel_affine : implementation and documentation mismatch 

### ISSUE THREAD

**Issue by SrivastavaKshitij** [pytorch/pytorch#85525]
### 🐛 Describe the bug

Hi, 

Please find the reproducible script 

```
import torch

print("Pytorch version", torch.__version__)
x = torch.randn(2, 2, 2)
scales = (torch.randn(2) + 1) * 0.05
zero_points = torch.zeros(2).to(torch.long)
out = torch.fake_quantize_per_channel_affine(x, scales, zero_points, 1, 0, 255)
```

1. If I run this script with Pytorch NGC container `nvcr.io/nvidia/pytorch:21.04-py3` , then the script runs fine. 

However, with later versions of Pytorch NGC container,  I run into the following error

Error with `nvcr.io/nvidia/pytorch:21.12-py3`

```
Pytorch version 1.11.0a0+b6df043
Traceback (most recent call last):
 File "test.py", line 15, in <module>
    out = torch.fake_quantize_per_channel_affine(x, scales, zero_points, 1, 0, 255)
RuntimeError: Zero-point must be Int32, Float or Half, found Long
```

Error with `nvcr.io/nvidia/pytorch:22.08-py3`

```
Pytorch version 1.13.0a0+d321be6 

Traceback (most recent call last):                                                                                                                                                   
  File "test.py", line 15, in <module>                                                                                                                                               
    out = torch.fake_quantize_per_channel_affine(x, scales, zero_points, 1, 0, 255)                                                                                                  
RuntimeError: Zero-point must be Int32, Float or Half, found Long      
```

Looking at pytorch documentation for Pytorch 1.11 and 1.13 , I dont see any change where it is mentioned not to use `torch.long` for zero point .

It would be nice to get this discrepancy fixed. 

Thanks

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0a0+b6df043

```

Thanks

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by vkuzo** [comment]
assigning to oncall, @jerryzh168 could you take a look?

**Comment by jerryzh168** [comment]
thanks for reporting the issue, I checked the history, looks like initially it is Long in https://github.com/pytorch/pytorch/pull/51255/files (Jan. 2021) and then changed to Int in https://github.com/pytorch/pytorch/pull/61318/files#diff-aacc8cdcb669b6e6f8cc105400f8f0ad85bae9a684021b2c90f9999f1575381f (July 2021), and there is no update in the documentation. will add the type constraint to documentation
