### ISSUE TITLE
import torch._thnn during initial setup transitively triggers import of C extension, leading to module 'torch' has no attribute

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8553]
Steps to reproduce:
1. Build PyTorch
2. Add a new native function and a docstring for it in `torch._torch_docs` (the key is that, there should be a new symbol added to `torch._C`, and a function in `_torch_docs` which relies on this symbol being defined)
3. Rebuild PyTorch

Expected result: It works

Actual result: In my most recent build, I get:

```
Traceback (most recent call last):
  File "tools/setup_helpers/generate_code.py", line 110, in <module>
    main()
  File "tools/setup_helpers/generate_code.py", line 106, in main
    options.install_dir)
  File "tools/setup_helpers/generate_code.py", line 80, in generate_code
    from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  File "/data/users/ezyang/pytorch-tmp/tools/nnwrap/__init__.py", line 1, in <module>
    from .generate_wrappers import generate_wrappers, wrap_function
  File "/data/users/ezyang/pytorch-tmp/tools/nnwrap/generate_wrappers.py", line 13, in <module>
    from torch._thnn import utils as thnn_utils
  File "/data/users/ezyang/pytorch-tmp/torch/__init__.py", line 292, in <module>
    from . import _torch_docs, _tensor_docs, _storage_docs
  File "/data/users/ezyang/pytorch-tmp/torch/_torch_docs.py", line 600, in <module>
    add_docstr(torch.bincount,
AttributeError: module 'torch' has no attribute 'bincount'
```

I believe the reason is the following diff in fcd9af8a257f83450ba82cccd227fe43bde7c879 (#8397):

```
-thnn_utils = import_module('torch._thnn.utils', THNN_UTILS_PATH)
+try:
+    from torch._thnn import utils as thnn_utils
+except ImportError:
+    from ..shared import import_module
+    thnn_utils = import_module('torch._thnn.utils', THNN_UTILS_PATH)
```

`torch._thnn` is inside `torch`, which means that a regular (non `import_module`) import will first try to load `torch/__init__.py`, which is what sets up the docstrings. But this is happening before we've built the C extension, so not everything you want is there.

**Comment by zdevito** [comment]
Related: If you introduce a segfault or exception throw in _C.so while developing, the build will break and will require the manual removal of _C.so to get working again.

**Comment by anderspapitto** [comment]
I'm working on replacing this code with a different approach

**Comment by anderspapitto** [comment]
the relevant code no longer exists
