### ISSUE TITLE
[pytorch][build] ‘vmsLog2’ was not declared in this scope

### ISSUE THREAD

**Issue by elanmart** [pytorch/pytorch#8554]
I tried to rebase and rebuild torch from source today, but got an error:
`../aten/src/ATen/cpu/vml.h:68:76: error: ‘vmsLog2’ was not declared in this scope`

See [full gist](https://gist.github.com/elanmart/8fca075c596378bd785abd8079567684).

For future reference, getting rid of old `mkl` install in `/opt/intel` and updating `mkl` via `conda` seems to have solved the issue.

cc @soumith @cpuhrsch

**Comment by zasdfgbnm** [comment]
Same problem here

**Comment by cpuhrsch** [comment]
Hello @elanmart and @zasdfgbnm  - If the error is mitigated by updating MKL, I consider this issue resolved. It's generally recommend to have the newest dependencies for development. We ship MKL with our binary builds and link against it statically, so this won't impact our users either.

**Comment by elanmart** [comment]
@cpuhrsch I understand, just to clarify, I opened the issue following a short discussion with @soumith , quoting relevant bit by Soumith:
> if you open an issue, I'll revert the PR and ask Christian to add a cmake check to see if VML is available, rather than assume MKL = VML-available
offending PR is https://github.com/pytorch/pytorch/pull/8458

Not sure if it's still relevant though.

**Comment by cpuhrsch** [comment]
Just talked to Soumith - I'll guard against older versions that don't have vmsLog2 available.

**Comment by cpuhrsch** [comment]
Guarding has been landed. Please retry.

**Comment by SsnL** [comment]
fixed via #8614
