### ISSUE TITLE
Contributor License Agreement Updates

### ISSUE THREAD

**Issue by zpao** [pytorch/pytorch#85559]
As part of the transition to the [PyTorch Foundation](https://pytorch.org/blog/PyTorchfoundation/), we will be moving away from the Meta CLA (Contributor License Agreement) and over to a Foundation-specific CLA. **This will occur on Monday, October 3rd.** All open pull requests not merged by this point, and all future pull requests, will require the author to be covered by a new CLA.

Initially, this new CLA will be required only for contributions to [`pytorch/pytorch`](https://github.com/pytorch/pytorch) and [`pytorch/pytorch.github.io`](https://github.com/pytorch/pytorch.github.io). All other repositories in the @pytorch organization will continue to be governed as they are today, until otherwise noted.

# Quick Links

* [Sign the CLA now.](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/29311126/65600975/86170/) This can also be used to join an existing CCLA, if your organization has signed one.
* [Sign and manage your CCLA membership.](https://organization.lfx.linuxfoundation.org/foundation/a092M00001LkQdtQAF/project/a092M00001L1BLjQAN/cla) This should be used by representatives who will be signing and/or managing on behalf of an organization. This may be somebody in your company's Legal team or Open Source Program Office.
* [Read this first if you are a Meta employee.](https://fburl.com/it1b2xto)

# FAQ

## What does this mean for current contributors?

If you have signed our current Individual Contributor License Agreement (ICLA), you will need to sign the new ICLA. If you are contributing on behalf of an organization which has signed the Corporate Contributor License Agreement (CCLA) then a representative from your organization will need to sign the new agreement.

## What's the difference between the old and new CLAs?

Both of these are based on the Apache Software Foundation's CLAs, which are used widely throughout the industry. The primary difference moving from Meta's CLAs to PyTorch Foundation's is the legal entity with which you are engaging. There are some other minor differences as well, as demonstrated in these images:

<details>
  <summary>View ICLA Diff</summary>
  <img width="839" alt="ICLA Diff" src="https://user-images.githubusercontent.com/8445/191663582-2e6c7530-0db4-4ba2-86e4-0453e5b2c6d6.png">
</details>

<details>
  <summary>View CCLA Diff</summary>
  <img width="839" alt="CCLA Diff" src="https://user-images.githubusercontent.com/8445/191663570-10b4a8b7-f47b-4c96-a19a-6c1b5b6c6e3a.png">
</details>

To reproduce these diffs, you can use these formatted copies of the CLAs (with some minimal instructions removed for ease of comparison) available [here](https://gist.github.com/zpao/a4f1e221e16870e080849087b6062805).

## If I have multiple PRs open, will I need to sign multiple times?

No. We will trigger the CLA check on each open PR. Simply follow the instructions in one of your PRs. After you are covered by a CLA, you may need to retrigger the CLA checks on other open PRs you've authored. This can be done either by clicking on the link in the instructions on each of your PRs (which will redirect back and update the status) _or_ you can comment with `/easycla`.

## How do I manage my organization when using the CCLA?

The PyTorch Foundation makes use of the same tooling that other Linux Foundation projects use - EasyCLA. This allows organizations to add and remove members easily, without any complicated process. Some documentation relevant for "CLA Managers" can be found [here](https://docs.linuxfoundation.org/lfx/easycla/v2-current/corporate-cla-managers).

**Comment by seemethere** [comment]
Pinning this issue since this is relevant for _all_ PyTorch contributors

**Comment by jayaddison** [comment]
A question that doesn't appear answered in the FAQ, or the project's issue history as far as I can tell based on searching:

Is a [Developer Certificate of Origin](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) declaration acceptable for contributions to the PyTorch Project?

**Comment by zpao** [comment]
> A question that doesn't appear answered in the FAQ, or the project's issue history as far as I can tell based on searching:
> 
> Is a [Developer Certificate of Origin](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) declaration acceptable for contributions to the PyTorch Project?

Good question, and apologies for missing it. No, a DCO is not acceptable in place of the CLA. There's a lot of fun discussion around these options but generally a project picks one or the other (or neither). This provides consistent coverage.

**Comment by zpao** [comment]
Ok, it's been ~6 months, so I'm going to close this out and unpin it. The EasyCLA process is well established and all PRs that were open at the time of cutover still have the reference to this issue for anybody who needs to catch up.
