### ISSUE TITLE
[JIT] CompilationUnit/ScriptModule doesn't print in detail

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8558]
```
> print(CU)
<torch.jit.CompilationUnit object at 0x7f16e9df4588>
> print(CU.module)
<torch._C.ScriptModule object at 0x7f309e936650>
```

Surely you can give me some useful information when I print these!

**Comment by eellison** [comment]
Compilation unit isn't a user-facing api now, and there are other more explicit issues about ScriptModule repr: https://github.com/pytorch/pytorch/issues/28517. Closing, re-open if you think this is relevant.
