### ISSUE TITLE
'result_type': is not a member of 'std::hash<T>'

### ISSUE THREAD

**Issue by bitnick10** [pytorch/pytorch#85603]
### 🚀 The feature, motivation and pitch

Please add support for cpp20 since result_type is deprecated in C++17.
Error	C2039	'result_type': is not a member of 'std::hash<T>'		
D:\libtorch-win-shared-with-deps-latest\libtorch\include\c10\util\Optional.h	1241	

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
Adding `module:windows` as it is indeed specific to a compiler, both gcc and clang still allow to compile the above code using C++20 standard. 
Not sure whether to replace this one with `std::invoke_result_t` or just `size_t`
