### ISSUE TITLE
RuntimeError: no support for _allgather_base in MPI process group

### ISSUE THREAD

**Issue by Gstevenson3** [pytorch/pytorch#85628]
### 🐛 Describe the bug

Trying to use FSDP with a CUDA-aware MPI backend, but _allgather_base is giving me an error.

```
  File ".../python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2136, in _all_gather_base
    dist._all_gather_base(indices, index, group=self.process_group)
  File ".../python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2136, in _all_gather_base
    work = group._allgather_base(output_tensor, input_tensor)
RuntimeError: no support for _allgather_base in MPI process group
```

Really hoping there are plans to implement it or get it running.
If not, would help me to be aware so I can change directions.

Thanks!

### Versions

PyTorch version: 1.12.0a0+git664058f
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Linux (ppc64le, could also move to x86)
GCC version: (GCC) 8.3.1 20190311
Clang version: 12.0.1
CMake version: version 3.19.6
Libc version: glibc-2.17

Python version: 3.9.12 (main, Jun  1 2022, 11:51:15)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.14.0-115.35.1.3chaos.ch6a.ppc64le-ppc64le-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration:
2 or 4 GPUs per node

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.12.0a0+git664058f
[conda] numpy                     1.22.3           py39h76732f4_0
[conda] numpy-base                1.22.3           py39h37faa36_0
[conda] torch                     1.12.0a0+git664058f          pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by awgu** [comment]
Unfortunately, we do not have planned support for extending the MPI backend. cc: @kwen2501 @H-Huang 

FSDP only explicitly supports NCCL backend at the moment. Would it be possible to use NCCL?

**Comment by Gstevenson3** [comment]
Thanks for letting me know. 

The NCCL backend won't work for me, because I need to mix GPU / CPU distributed operations, which the MPI backend allows me to do. 

I'm using DDP to assign copies of a model on each GPU a subsection of a large tensor and then all_reducing the results into that tensor (where that large tensor won't fit in GPU memory at scale).

**Comment by H-Huang** [comment]
Hi @Gstevenson3, thanks for explaining your requirements. Unfortunately at the moment there are no current plans in the roadmap to support allgather for the MPI backend. 

Just an FYI, in the next PyTorch release we plan to make the `ProcessGroup` operations dispatchable based on the tensor device, so you will be able to mix GPU / CPU distributed operations. The feature is currently being actively developed and I’ve created this issue (https://github.com/pytorch/pytorch/issues/86225) to track the progress and PRs publicly.

**Comment by Gstevenson3** [comment]
@H-Huang Thanks for the info. That will help me when it becomes available. Appreciate your time.

**Comment by awgu** [comment]
Closing this since it has resolution
