### ISSUE TITLE
Fix torchaudio smoke test before release 

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#85647]
### 🐛 Describe the bug

Error:
https://app.circleci.com/pipelines/github/pytorch/audio/12767/workflows/859e9b53-b308-4e89-bfea-fc814713ade2/jobs/924313

```
   "Detected that PyTorch and TorchAudio were compiled with different CUDA versions. "
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 11.7
```

### Versions

1.13

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by izaitsevfb** [comment]
Fixed in https://github.com/pytorch/audio/pull/2721
Recent workflows are green: https://app.circleci.com/pipelines/github/pytorch/audio/12844/workflows/4beb9656-2fa5-4805-a8d1-4a503811ec48
