### ISSUE TITLE
[ONNX] torch/onnx is using rank to differentiate between ScalarType and TensorType

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#85663]
### 🐛 Describe the bug

ONNX is using condition of following:
https://github.com/pytorch/pytorch/blob/6a04df3ac85714b33dcb2af20d0eeea96d131d75/torch/csrc/jit/passes/onnx/scalar_type_analysis.cpp#L209
to differentiate between ScalarType and TensorType, which is revealed as bug by the following case:

```python
import torch
from io import BytesIO
import onnx


class MulLeakyReLU(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.m = torch.nn.LeakyReLU(negative_slope=0.1)

    def forward(self, x):
        return x * self.m(x)


f = BytesIO()
torch.onnx.export(
    MulLeakyReLU(),
    torch.randn((), dtype=torch.float64),
    f,
    verbose=True,
    opset_version=14,
)
onnx_model = onnx.load_from_string(f.getvalue())
onnx.checker.check_model(onnx_model, full_check=True)
assert MulLeakyReLU()(torch.randn((), dtype=torch.float64)).dtype == torch.float64
onnx_output_type = onnx_model.graph.output[0].type.tensor_type.elem_type
assert (
    onnx_output_type == onnx.TensorProto.DataType.DOUBLE
), f"Expected output to be double but the converted ONNX model outputs is {onnx.TensorProto.DataType.Name(onnx_output_type)}"

"""
Exported graph: graph(%input : Double(requires_grad=0, device=cpu)):
  %/m/LeakyRelu_output_0 : Double(requires_grad=0, device=cpu) = onnx::LeakyRelu[alpha=0.10000000000000001, onnx_name="/m/LeakyRelu"](%input), scope: __main__.MulLeakyReLU::/torch.nn.modules.activation.LeakyReLU::m
  %/Cast_output_0 : Float(requires_grad=0, device=cpu) = onnx::Cast[to=1, onnx_name="/Cast"](%input), scope: __main__.MulLeakyReLU:: # test.py:14:0
  %/Cast_1_output_0 : Float(requires_grad=0, device=cpu) = onnx::Cast[to=1, onnx_name="/Cast_1"](%/m/LeakyRelu_output_0), scope: __main__.MulLeakyReLU:: # test.py:14:0
  %5 : Float(requires_grad=0, device=cpu) = onnx::Mul[onnx_name="/Mul"](%/Cast_output_0, %/Cast_1_output_0), scope: __main__.MulLeakyReLU:: # test.py:14:0
  return (%5)

Traceback (most recent call last):
  File "test.py", line 29, in <module>
    assert (
AssertionError: Expected output to be double but the converted ONNX model outputs is FLOAT
"""
```

NOTE: the tensor with no rank is recognized as scalar.

Actionable iitems:
1. Explore in tracing to see if we can get scalartype/tensortype information from upstream.
2. SymFloat might be a great help.

### Versions

Nightly

**Comment by AllenTiTaiWang** [comment]
cc @BowenBao in case I am not expressing the issue clearly.

**Comment by AllenTiTaiWang** [comment]
duplicate #79279

**Comment by thiagocrepaldi** [comment]
@AllenTiTaiWang @justinchuby Is this handled anyway? [The ](https://github.com/pytorch/pytorch/issues/79279) was closed without a solution, which makes me believe we still have this limitation. Is that the case?

**Comment by justinchuby** [comment]
I think that is accurate. @AllenTiTaiWang may have more info

**Comment by AllenTiTaiWang** [comment]
Still an issue, but it's tracked internally.

**Comment by thiagocrepaldi** [comment]
> Still an issue, but it's tracked internally.

Anywhere else besides https://github.com/microsoft/onnx-converters-private/issues/106? This issue is for not-going-to-fix items only

**Comment by AllenTiTaiWang** [comment]
Isn't this part of the https://github.com/microsoft/onnx-converters-private/issues/97?
The solution is to implement with symFloat/symInt to track these information.

**Comment by thiagocrepaldi** [comment]
> Isn't this part of the [microsoft/onnx-converters-private#97](https://github.com/microsoft/onnx-converters-private/issues/97)? The solution is to implement with symFloat/symInt to track these information.

his just discusses where Meta is going with PyTorch and how ONNX could leverage this. This is not a task that will fix any issue

Maybe *this* issue should be reopened and investigated further as there is no toher doing it
