### ISSUE TITLE
How to load checkpoint from .pt file

### ISSUE THREAD

**Issue by ZeyiLiao** [pytorch/pytorch#85695]
### 🐛 Describe the bug
I finetuned T5-large by pytorch lightning and saved a ckpt file.
```
ckpt = torch.load(<ckpt_path>)
print(ckpt.keys())

dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'loops', 'callbacks', 'optimizer_states', 'lr_schedulers', 'hparams_name', 'hyper_parameters'])
```
It does have state_dict which means I can use it as my inference task.
I have tried the following two snippets.

1.
This can not run correctly
```
ckpt = torch.load(<ckpt_path>)
model = AutoModelForSeq2SeqLM.from_pretrained('t5-large')
model.load_state_dict(ckpt)
print(model.lm_head.weight)
```

2. This seems don't load the weight correctly.
```
ckpt = torch.load(<ckpt_path>)
model_config = AutoConfig.from_pretrained('t5-large')
model_2 = AutoModelForSeq2SeqLM.from_pretrained(None,config = model_config,state_dict = ckpt)
print(model_2.lm_head.weight)
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-189-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000
GPU 2: Quadro RTX 8000
GPU 3: Quadro RTX 8000
GPU 4: Quadro RTX 8000
GPU 5: Quadro RTX 8000
GPU 6: Quadro RTX 8000
GPU 7: Quadro RTX 8000
GPU 8: Quadro RTX 8000
GPU 9: Quadro RTX 8000

Nvidia driver version: 470.141.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.7.7
[pip3] torch==1.12.1
[pip3] torchmetrics==0.7.2
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch-lightning         1.7.7                    pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi

**Comment by alvarobartt** [comment]
Hi @ZeyiLiao, this issue should be posted in `huggingface/transformers` instead I think, but anyway, here's the code on how to actually load a 🤗 HuggingFace Model from a checkpoint.

```python
from transformers import AutoModelForSeq2SeqLM

model =  AutoModelForSeq2SeqLM("./checkpoint")
```

I hope this helped you!

**Comment by alvarobartt** [comment]
As a follow-up on the previous comment @ZeyiLiao, according to the code you provided, the following should work:

```python
from transformers import AutoConfig, AutoModelForSeq2SeqLM

config = AutoConfig.from_pretrained("t5-large")
model = AutoModelForSeq2SeqLM(config=config)
model.load_state_dict(torch.load("checkpoint.pt"))
```

**Comment by mikaylagawarecki** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
