### ISSUE TITLE
It currently rounds toward 0 (like the 'trunc' function NOT 'floor').

### ISSUE THREAD

**Issue by ywfwyht** [pytorch/pytorch#85700]
### 🐛 Describe the bug

@svenstaro @JackDanger @eklitzke 
Hi,
When torch.onnx.export is used, the following error is reported.
Error：
/opt/conda/lib/python3.8/site-packages/einops/einops.py:202: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  inferred_length: int = length // known_product
Segmentation fault (core dumped)

### Versions

python:3.8.8
pytorch:1.12
cuda:11.1
cudnn:8.0.5
ubuntu18.04

**Comment by ptrblck** [comment]
You can avoid the warning, which is caused by e.g.:
```python
length = torch.tensor(4.)
known_product = 2
inferred_length: int = length // known_product
# UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
#  inferred_length: int = length // known_product
```
by explicitly using the suggested methods mentioned in the error message.

The segmentation fault seems to be unrelated, so could you post the stacktrace from `gdb` via:
```
gdb --args python script.py args
...
run
...
bt
```

**Comment by justinchuby** [comment]
https://github.com/pytorch/pytorch/issues/78442

**Comment by ywfwyht** [comment]
> 

thanks

**Comment by ywfwyht** [comment]
> You can avoid the warning, which is caused by e.g.:
> 
> ```python
> length = torch.tensor(4.)
> known_product = 2
> inferred_length: int = length // known_product
> # UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
> #  inferred_length: int = length // known_product
> ```
> 
> by explicitly using the suggested methods mentioned in the error message.
> 
> The segmentation fault seems to be unrelated, so could you post the stacktrace from `gdb` via:
> 
> ```
> gdb --args python script.py args
> ...
> run
> ...
> bt
> ```

Thanks.
