### ISSUE TITLE
[ONNX] Conversion failed when using dict as input to a scripted module

### ISSUE THREAD

**Issue by Lauriat** [pytorch/pytorch#85757]
### 🐛 Describe the bug

```python
import torch
from typing import Dict

class Module(torch.nn.Module):
    def forward(
        self, x: Dict[str, torch.Tensor]
    ) -> Dict[str, torch.Tensor]:
        return x

model = torch.jit.script(Module())
x = {"input": torch.zeros(1)}
torch.onnx.export(model, (x, {}), "out", opset_version=9)  # ERR

```
```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    torch.onnx.export(model, (x, {}), "out", opset_version=9)  # ERR
  File "/opt/homebrew/lib/python3.9/site-packages/torch/onnx/__init__.py", line 350, in export
    return utils.export(
  File "/opt/homebrew/lib/python3.9/site-packages/torch/onnx/utils.py", line 163, in export
    _export(
  File "/opt/homebrew/lib/python3.9/site-packages/torch/onnx/utils.py", line 1074, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/homebrew/lib/python3.9/site-packages/torch/onnx/utils.py", line 747, in _model_to_graph
    example_outputs = _get_example_outputs(model, args)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/onnx/utils.py", line 630, in _get_example_outputs
    example_outputs = model(*input_args, **input_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: forward() is missing value for argument 'x'. Declaration: forward(__torch__.Module self, Dict(str, Tensor) x) -> (Dict(str, Tensor))
```
Using dict as input raises runtime error when exporting scripted module to ONNX.

It seems the inputs are not passed to the model as they should, since in
> File .../torch/onnx/utils.py, line 630, in _get_example_outputs
    example_outputs = model(*input_args, **input_kwargs)

the variables ```input_args``` and ```input_kwargs``` are
```
input_args=()
input_kwargs={'input': tensor([0.])}
```

### Versions

PyTorch version: 1.12.0
Is debug build: False
OS: macOS 12.2.1 (arm64)
Python version: 3.9.13 (main, May 24 2022, 21:13:51)  [Clang 13.1.6 (clang-1316.0.21.2)] (64-bit runtime)

**Comment by justinchuby** [comment]
Dictionary are not very well supported especially in scripted module. Would you be able to work with a traced module? At the same time, onnx does not support a dictionary as a final output. I would flatten the output when exporting.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues, like dict support

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
