### ISSUE TITLE
Tensor subclasses as parameters: wrapped tensor does not move to cuda

### ISSUE THREAD

**Issue by interesaaat** [pytorch/pytorch#85826]
### 🐛 Describe the bug

```python
from typing import Any, Type
import torch
from torch.utils._pytree import tree_map

class WrappingTensor(torch.Tensor):
    re_wrap: bool = False

    @staticmethod
    def __new__(
        cls, t: torch.Tensor
    ):
        r = super(WrappingTensor, cls)._make_wrapper_subclass(cls, t.shape, dtype=t.dtype, requires_grad=t.requires_grad, device=t.device)  # type: ignore
        return r

    def __init__(self, t: torch.Tensor, re_wrap=False) -> None:
        self.tensor: torch.Tensor = t

    __torch_function__ = torch._C._disabled_torch_function_impl

    @classmethod
    def __torch_dispatch__(cls, func, types, args=(), kwargs=None):  # type: ignore
        def unwrap(e: Any) -> torch.Tensor:
            if isinstance(e, WrappingTensor):
                t = e.tensor
                return t
            else:
                return e
        r = func(*tree_map(unwrap, args), **tree_map(unwrap, kwargs))
        if cls.re_wrap:
            return WrappingTensor(r)
        else:
            return r

class Module(torch.nn.Module):
    def __init__(self, t: torch.Tensor):
        super().__init__()
        WrappingTensor.re_wrap = True
        p1 = WrappingTensor(t)
        self.param1 = torch.nn.Parameter(p1)

    def forward(self, t: torch):
        return self.param1

t = torch.rand((3,3))
m = Module(t)
m.to("cuda")
print(m.param1.device)
print(m.param1.tensor.device)
```

This prints 
```
cuda:0
cpu
```
but I was expecting 
```
cuda:0
cuda:0
```

### Versions

PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.10

Python version: 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:45:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1089-azure-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 450.119.03

cc @ezyang

**Comment by ezyang** [comment]
This is an unfortunate but known limitation. If you ask for device dispatch at construction time you can forward device calls to the inner tensor which will help

**Comment by interesaaat** [comment]
Thanks, I figured that this was probably going to be the solution. One thing that is not clear to me is whether I should be using `__torch_function__` or `__torch_dispatch__`. I found sort of conflicting documentation online. I tried to use both together but it didn't work (and I had some weird behavior like I was doing `.to('cuda')` on the inner tensor and something like self.view(self.shape) on the outer tensor to get the device property propagated). 

So now I have a version that only uses `__torch_function__` and I kind of have it working, but I am not sure if this is the proper way of doing this.

**Comment by ezyang** [comment]
It depends on what you're trying to do, but https://github.com/albanD/subclass_zoo can give you some ideas. In general, dispatch is good if you need to work below autograd (i.e., if autograd calls ops, do you want your subclass to see them?)
 and function is good for just syntax sugar on the Python level. You can use both together but it's a little tricky as they need to not step over each other's toes.

**Comment by interesaaat** [comment]
I checked the models and there was nothing that was working in all the use cases we are looking at. Pretty much what we need is quite simple: we need a `MetadataTensor` storing some metadata but allowing to propagate them through tensor operations, as well as using the `MetadataTensor` as a parameter and working with TorchScript. 

While we manage to get everything working now by only using `__torch_function__` for TorchScript we need to trace the model twice for some reason: one to generate the jitted model, and one to get the output metadata information because for some reason these get lost after jit (by only using `__torch_function__`).

**Comment by ezyang** [comment]
Yeah, I guess it's not surprising JIT loses the info, it post-dates torch function. In general none of the subclass stuff is supported by JIT, so I think that's about as good as it's going to get. Or you could use the new `make_fx`...

**Comment by interesaaat** [comment]
Ah cool! I am going to play with it, even if the [doc](https://github.com/pytorch/functorch#tracing-through-the-transformations) says that works only for CPU?

**Comment by ezyang** [comment]
that's the compiler integration; you can still trace any device
