### ISSUE TITLE
Combining indexing and item

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#8583]
What about combining indexing and `item()` so that
```python
one_d_tensor[index].item() is one_d_tensor.item(index)
```

**Comment by zou3519** [comment]
We discussed this and it might not be worth complicating the item API just for the 1D tensor case.

**Comment by Atcold** [comment]
Well, not necessarily for 1D `Tensors`. It would be fine simply to point to the `index`-th element in the `Storage`.

**Comment by zou3519** [comment]
Hmm I think the N-D case is a little strange.

For example, `tensor.index(3)`: would this be equivalent to `tensor.storage()[3]`, or `tensor.contiguous().view(-1)[3]`? (I think these are different)

**Comment by Atcold** [comment]
I'd say it should return `tensor.storage()[3]`.
`item` access the number contained in the `Storage`.
If the `Tensor` is `0` dimensional, then it returns the only value.
If the `Tensor` is not a scalar, then *i*-th `item` should give you the *i*-th item in the `Storage`.
At least to me this looks natural.
