### ISSUE TITLE
`torch.histc` handles NaN inconsistently on cpu and cuda

### ISSUE THREAD

**Issue by creakseek** [pytorch/pytorch#85853]
### 🐛 Describe the bug

When the input to `torch.histc` contains NaN, it ignores NaN on CUDA, but counts the NaN to the first bin on CPU, which is clearly wrong.

```
import torch
torch.manual_seed(420)
torch.cuda.manual_seed_all(420)
x = torch.randn(10, 10).log() # x contains NaN
y = torch.histc(x, bins=10, min=0, max=1)
print(y) # first element is [48, ...] which counts all the NAN elements

x = x.cuda()
y = torch.histc(x, bins=10, min=0, max=1)
print(y) # first element is only [2, ...] which does not count any NAN elements

print(torch.isnan(x.view(-1)).sum().item()) # amount of NAN is 46 = 48 -2 
```
Outputs:
```
tensor([48.,  0.,  2.,  3.,  1.,  3.,  0.,  2.,  0.,  1.])
tensor([2., 0., 2., 3., 1., 3., 0., 2., 0., 1.], device='cuda:0')
46
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.14 (default, Sep  8 2022, 00:06:44)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

cc @ezyang @gchanan @zou3519

**Comment by mruberry** [comment]
From a framework consistency perspective it does seem like this operation should ignore NaNs. While NumPy doesn't have a `histc` operation it does have `histogram`, which also ignores NaNs:

```
np.histogram([.5, 2.2, 1.2, float('nan')], bins=[0, 1, 2, 3])
: (array([1, 1, 1]), array([0, 1, 2, 3]))
```
