### ISSUE TITLE
NVidia CUDA support is outdated

### ISSUE THREAD

**Issue by atiq-cs** [pytorch/pytorch#85917]
### 🐛 Describe the bug

https://pytorch.org/get-started/locally
still offers older version of CUDA which is 11.6 instead of latest (11.7)!

What's the release schedule for support of 11.7?

`pip` cmd is outdated,

    pip3 install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

**refs**
- Official install instructions: https://pytorch.org/get-started/locally
- CUDA 11.7 on pytroch official site doesn't exist yet, https://download.pytorch.org/whl/cu117

- Platform nvidia refs
 - https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64
 - https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11

### Versions

    $ python collect_env.py
    Collecting environment information...
    PyTorch version: 1.12.1+cu116
    Is debug build: False
    CUDA used to build PyTorch: 11.6
    ROCM used to build PyTorch: N/A

    OS: Microsoft Windows 10 Enterprise
    GCC version: Could not collect
    Clang version: Could not collect
    CMake version: Could not collect
    Libc version: N/A

    Python version: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] (64-bit runtime)
    Python platform: Windows-10-10.0.19044-SP0
    Is CUDA available: True
    CUDA runtime version: Could not collect
    GPU models and configuration: GPU 0: Quadro T2000
    Nvidia driver version: 516.94
    cuDNN version: Could not collect
    HIP runtime version: N/A
    MIOpen runtime version: N/A
    Is XNNPACK available: True

    Versions of relevant libraries:
    [pip3] numpy==1.23.3
    [pip3] torch==1.12.1+cu116
    [pip3] torchaudio==0.12.1+cu116
    [pip3] torchvision==0.13.1+cu116
    [conda] Could not collect

**Comment by crcrpar** [comment]
Hi, cuda 11.7 is currently supported by PyTorch nightly builds as in the capture below

![image](https://user-images.githubusercontent.com/16191443/193139126-70247bd1-761b-4798-916e-736663d96d21.png)

**Comment by atiq-cs** [comment]
Thanks for letting me know the nighlty build.
