### ISSUE TITLE
Setup ssh sometimes fail

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#85932]
Example failure: https://github.com/pytorch/pytorch/actions/runs/3154700893/jobs/5132596332

```
Prepare all required actions
Getting action download info
Download action repository 'seemethere/add-github-ssh-key@v1' (SHA:105f7619adc4054f5f1be5f79ebd354d8[2](https://github.com/pytorch/pytorch/actions/runs/3154700893/jobs/5132596332#step:4:2)[3](https://github.com/pytorch/pytorch/actions/runs/3154700893/jobs/5132596332#step:4:3)8[4](https://github.com/pytorch/pytorch/actions/runs/3154700893/jobs/5132596332#step:4:4)638)
Run ./.github/actions/setup-ssh
Run seemethere/add-github-ssh-key@v1
Grabbing public ssh keys from https://github.com/albanD.keys
Error: Server Error

```

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Maybe a retry here would be sufficient

**Comment by albanD** [comment]
It did, but I have seen this happening a couple times on my PRs so wonder if there is something flaky there?

**Comment by seemethere** [comment]
> It did, but I have seen this happening a couple times on my PRs so wonder if there is something flaky there?

My guess is that Github itself is flaky when calling to grab the keys. I wonder if there's a caching mechanism we could use in this scenario that would make this better

**Comment by huydhn** [comment]
This error hasn't been seen for a while, so I think we can close it.
