### ISSUE TITLE
Extend math functions to ArrayRef

### ISSUE THREAD

**Issue by mmoelle1** [pytorch/pytorch#85954]
### 🚀 The feature, motivation and pitch

Can you please extend math functions like `torch::prod` to `ArrayRef`? I would need this feature for computing the total length of multi-dimensional tensors, i.e.
```cpp
torch::Tensor a(4,5,2);
torch::prod(a.sizes()); // -> 40
```

### Alternatives

Alternatively, this feature could be implemented as
```cpp
torch::Tensor a(4,5,2);
a.size(-1);
```
or as a new member functions, e.g.
```cpp
torch::Tensor a(4,5,2);
a.length();
```

**Comment by kshitij12345** [comment]
Tensor already has a member function `numel` which should do the same.

**Comment by mmoelle1** [comment]
Thanks very much for this information. I didn't know and was suggested in the discussion forum to make this a feature request. I'll close it.
