### ISSUE TITLE
`eigvals` will crash with `inf`

### ISSUE THREAD

**Issue by payphon** [pytorch/pytorch#85950]
### 🐛 Describe the bug

`eigvals` will crash with `inf`

```py
import torch

inf = float('inf')
b = torch.tensor([[inf, -inf], [inf, -inf]])
torch.linalg.eigvals(b )
```

```
Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
[1]    4093363 segmentation fault (core dumped)  python tmp_model.py
```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0.dev20220923+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.5-051905-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.13.0.dev20220923+cu116
[pip3] torchaudio==0.13.0.dev20220923+cu116
[pip3] torchvision==0.14.0.dev20220923+cu116
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220923+cu116          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220923+cu116          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220923+cu116          pypi_0    pypi
```

cc @svekars @holly1238 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
Adding the relevant error would incur in a penalty for all the valid cases. I don't think we want to perform that pesimisation really. Also, this is implemented in LAPACK, so we cannot fix this problem at the source. I think this will need to be a won't fix.

**Comment by vadimkantorov** [comment]
Ideally, this should be put in docs in some separate section and maybe added to tests (even if it is expected to crash)

**Comment by lezcano** [comment]
@IvanYashchuk @mruberry  Should this be a no-fix or a doc issue or what?
I vote no fix (not even document it), as it's the sort of behaviour that I don't think it's even documented in LAPACK and may be implementation dependent.

**Comment by lezcano** [comment]
cc @albanD for the crash concerns.

**Comment by IvanYashchuk** [comment]
> Warning
LAPACK routines assume that input matrices do not contain IEEE 754 special values such as INF or NaN values. Using these special values may cause LAPACK to return unexpected results or become unstable.

Source: https://spec.oneapi.io/versions/latest/elements/oneMKL/source/domains/lapack/lapack.html

In general, I think PyTorch users don't need to know about LAPACK, but they need to know that they should be careful with `torch.linalg` functions and implement checking for inf or nan themselves if they are willing to. That's a documentation issue.

This problem is not unique to PyTorch; NumPy, SciPy, and many other libraries and languages face it as well.
SciPy has `check_finite=True` argument:
> Whether to check that the input matrices contain only finite numbers. Disabling may give a performance gain, but may result in problems (crashes, non-termination) if the inputs do contain infinities or NaNs.

On GPUs, it's a larger performance penalty to do this check.

**Comment by lezcano** [comment]
Fair play. We should document this then. If only we had a place to put docs that are common for the whole linalg package.

**Comment by vadimkantorov** [comment]
> If only we had a place to put docs that are common for the whole linalg package.

Maybe we should? Make a single "linalg quirks" page? And then refer to secitons of it from individual functions? Maybe provide there recipes of using anomaly_detection in context of just linear algebra (outside of learning context) - maybe as is it can be helpful for debugging basic inf/nan issues

**Comment by IvanYashchuk** [comment]
> Fair play. We should document this then. If only we had a place to put docs that are common for the whole linalg package.

That's the place: https://github.com/pytorch/pytorch/blob/master/docs/source/linalg.rst
Rendered at: https://pytorch.org/docs/stable/linalg.html

**Comment by lezcano** [comment]
I think we could have these notes on the linalg module on a page entirely of its own. Then, we can link that page at the very top of the `linalg` docs, right after "Common linear algebra operations.".

**Comment by mruberry** [comment]
Adding a brief common section we can point practitioners and developers to sounds good.

It's unfortunate the error doesn't describe what happened, and could be confusing to users calling this function with large tensors. The documentation can help them understand why this might have happened, and to understand that it's expected.

Beyond this issue, there's an interesting question of how we handle data-dependent checks. I wonder if we should implement a mode for them to help with debugging. Modes aren't very discoverable, and it can be a pain to know when to enable them, but it might be preferable to the hodgepodge of data-dependent checks in PyTorch today.

**Comment by lezcano** [comment]
@albanD  mentioned that we may be able to implement asynchronous checks (at least in CUDA), which would be fantastic. If these become a thing, we could potentially have the cake and eat it :)

**Comment by albanD** [comment]
> albanD mentioned that we may be able to implement asynchronous checks (at least in CUDA), which would be fantastic.

Natalia kind of shattered my dream by explaining that even though we can have such asserts, it will only stop the current kernel and other kernels that are already queued will still run. So we will need to be careful how we use them to avoid leaving the user in a half broken state...

For this issue, I'm 100% in favor of adding a specifc doc bloc about this!

**Comment by vadimkantorov** [comment]
@lezcano the docs now say that the algorithms may return incorrect results, but segfault (if it's still produced) is not recoverable and nasty...

**Comment by lezcano** [comment]
The docs explicitly say (emph mine)
>The external libraries (backends) that ``torch.linalg`` uses provide no guarantees on their behaviour
when the inputs have non-finite values like ``inf`` or ``NaN``. As such, neither does PyTorch.
The operations may return a tensor with non-finite values, or raise an exception, **or even segfault.**

**Comment by vadimkantorov** [comment]
oh ok

**Comment by vadimkantorov** [comment]
sorry

**Comment by vadimkantorov** [comment]
Though IMO such segfaults should be reported to downstream libraries as they may indicate a bug nonetheless (even if it's a wontfix downstream) and a bug url (seems the up-to-date MKL discussion forum is https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library) should be provided in pytorch docs. An error code or bad result is understandable, but a segfault (because of what bad memory access?) is worth at least some investigation and should be encouraged to report an issue to pytorch as well

**Comment by vadimkantorov** [comment]
would you like me to report this to MKL?
