### ISSUE TITLE
'result_of': is not a member of 'std' C++20 build

### ISSUE THREAD

**Issue by bitnick10** [pytorch/pytorch#85962]
### 🚀 The feature, motivation and pitch

Please add support for cpp20 since result_of is deprecated in C++17.
Error	C2039	'result_of': is not a member of 'std'
D:\libtorch-win-shared-with-deps-latest\libtorch\include\c10\util\FunctionRef.h	58

**Comment by malfet** [comment]
Since I'm getting rid of a lot of C++14 restriction now, can take this one as well...
