### ISSUE TITLE
MPS Tensor from sliced numpy array indexing error

### ISSUE THREAD

**Issue by jedm-mf** [pytorch/pytorch#85967]
### 🐛 Describe the bug

Error when converting a sliced numpy array to mps device, using Apple M1 Pro chip on pytorch-nightly. 

Minimal example:

```
import torch
import numpy as np

a = np.array(np.arange(9).reshape((3,3)))
a = a[:,:2]
a_mps = torch.tensor(a, device=torch.device('mps'))
a_cpu = torch.tensor(a, device=torch.device('cpu'))

print(a)
# [[0 1]
#  [3 4]
#  [6 7]]

print(a_cpu)
# tensor([[0, 1],
#         [3, 4],
#         [6, 7]])  -- CORRECT

print(a_mps)
# tensor([[0, 1],
#         [2, 3],
#         [4, 5]], device='mps:0') -- INCORRECT
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220920
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.6 (main, Sep  9 2022, 11:31:09) [Clang 13.1.6 (clang-1316.0.21.2.5)] (64-bit runtime)
Python platform: macOS-12.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] torch==1.13.0.dev20220920
[pip3] torchaudio==0.13.0.dev20220911
[pip3] torchinfo==1.7.0
[pip3] torchvision==0.14.0.dev20220911
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Interesting, should be a one-liner fix...

**Comment by jedm-mf** [comment]
Cheers!
