### ISSUE TITLE
Benchmark app fails for fully-quantized model

### ISSUE THREAD

**Issue by KMCzajkowski** [pytorch/pytorch#85964]
### 🐛 Describe the bug

I tried [NNAPI tutorial](https://pytorch.org/tutorials/prototype/nnapi_mobilenetv2.html). In general, it works, but NNAPI is much slower if core quantization is being used. Moreover, full quantization does not work at all on mobile.

```
adb shell "/data/local/tmp/speed_benchmark_torch2 --model=/data/local
/tmp/mobilenetv2-quant_full-nnapi_v5r.pt" --input_dims="1,3,400,400" --input_type="uint8_t"
```

```
Starting benchmark.
Running warmup runs.
Main runs.
terminating with uncaught exception of type std::runtime_error: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/___torch_mangle_2957.py", line 11, in forward
    arg: Tensor) -> Tensor:
    mod = self.mod
    return (mod).forward(arg, )
            ~~~~~~~~~~~~ <--- HERE
  def _generate_bundled_inputs_for_forward(self: __torch__.___torch_mangle_2957.BundleWrapper) -> List[Tuple[Tensor]]:
    _bundled_inputs_deflated_forward = self._bundled_inputs_deflated_forward
  File "code/__torch__/torch/backends/_nnapi/prepare/___torch_mangle_2910.py", line 10, in forward
    arg_0: Tensor) -> Tensor:
    mod = self.mod
    retvals = (mod).forward([arg_0], )
               ~~~~~~~~~~~~ <--- HERE
    return retvals[0]
  File "code/__torch__/torch/backends/_nnapi/prepare/___torch_mangle_2909.py", line 52, in forward
        else:
          ops.prim.RaiseException("Invalid mem_fmt")
    _9 = (comp1).run(fixed_args, outs, )
          ~~~~~~~~~~ <--- HERE
    _10 = torch.len(outs)
    out_mem_fmts = self.out_mem_fmts

Traceback of TorchScript, original code (most recent call last):
  File "/home/k.czajkowski/Projects/simplenets/image-deblurring-using-deep-learning/src/their_demo.py", line 88, in forward
        def forward(self, arg):
            return self.mod(arg)
                   ~~~~~~~~ <--- HERE
  File "<string>", line 2, in forward
def forward(self, arg_0):
    retvals = self.mod([arg_0])
              ~~~~~~~~ <--- HERE
    return retvals[0]
  File "/home/k.czajkowski/anaconda3/envs/torchandroid/lib/python3.7/site-packages/torch/backends/_nnapi/prepare.py", line 65, in forward
            else:
                raise Exception("Invalid mem_fmt")
        comp.run(fixed_args, outs)
        ~~~~~~~~ <--- HERE
        assert len(outs) == len(self.out_mem_fmts)
        for idx in range(len(self.out_templates)):
RuntimeError: [enforce fail at nnapi_bind.cpp:207] . Bad dtype: 0

Aborted (core dumped)
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-124-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 510.73.08
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-complex-tensor==0.0.134
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.0+cu116
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.0+cu116
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.13.0+cu116
[pip3] torchviz==0.0.2
[conda] numpy                     1.21.6                    <pip>
[conda] pytorch-complex-tensor    0.0.134                   <pip>
[conda] pytorch-ranger            0.1.1                     <pip>
[conda] torch                     1.12.0+cu116              <pip>
[conda] torch-optimizer           0.3.0                     <pip>
[conda] torchaudio                0.12.0+cu116              <pip>
[conda] torchsummary              1.5.1                     <pip>
[conda] torchvision               0.13.0+cu116              <pip>
[conda] torchviz                  0.0.2                     <pip>

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by z-a-f** [comment]
@jerryzh168 Do you know anyone familiar with those tutorials?

**Comment by jerryzh168** [comment]
looks like David Reiss added this tutorial: https://github.com/pytorch/tutorials/commit/74b76631ca366cdfeff2bb38621b4d377d986b35, but he is no longer at PyTorch team, so this is probably not going to be fixed since no one is working on it
