### ISSUE TITLE
Requests more rocm runners for land check

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#85986]
### 🐛 Describe the bug

Land check is finally in place for everyone, and it's working well.  On the other hand, there is now a daily queue for rocm runners, which could go up to 40m https://hud.pytorch.org/metrics.  This starts to become a long pole in TTS, so I'm asking if it's possible to request for more rocm runners.

![Screen Shot 2022-09-30 at 10 47 04](https://user-images.githubusercontent.com/475357/193327442-17c16923-816d-4c89-b321-e44a44b190ae.png)

I'm not sure how many more that we need yet, but we could figure it out.

### Versions

Linux ROCM

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH @seemethere @malfet @pytorch/pytorch-dev-infra @ZainRizvi

**Comment by jithunnair-amd** [comment]
@huydhn I believe this is resolved now, since we haven't heard about any issues recently with land check times. Please reopen this if you still see issues.
