### ISSUE TITLE
Better error messages for `grid_sample` 

### ISSUE THREAD

**Issue by arogozhnikov** [pytorch/pytorch#8599]
## Issue description

`grid_sample` yields irrelevant errors when passing wrong arguments
 

## Code example

```python
import torch

from torch.nn import functional as F

matrix = torch.randn(2, 3)
images = torch.rand(1, 3, 10, 10)

grid = F.affine_grid(matrix.float()[None], images.shape)

# ok: images_new = F.grid_sample(images, grid=grid)
# ok: images_new = F.grid_sample(images.to('cuda'), grid=grid.to('cuda'))

images_new = F.grid_sample(images, grid=grid.to('cuda')) 
images_new = F.grid_sample(images.to('cuda'), grid=grid) 

```

First one:
```
FloatSpatialGridSamplerBilinear_updateOutput received an invalid combination of arguments - got (int, Tensor, Tensor, Tensor, int), but expected (int state, torch.FloatTensor input, torch.FloatTensor grid, torch.FloatTensor output, int padding_mode)
```

Second one:
```
RuntimeError: get_device is not implemented for type torch.FloatTensor
```

## System Info

- PyTorch or Caffe2: pytorch 0.4
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: ubuntu16.04
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version:
- GPU models and configuration: 1080
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by t-vi** [comment]
Thank you for the report! I'll move them to the new check for same GPU (which includes reasonable CPU vs. GPU reporting).

**Comment by t-vi** [comment]
In PyTorch master, the error message has already improved for the second case:
```
RuntimeError: Tensor for argument #2 'grid' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_grid_sampler_forward)
```

**Comment by riccardosamperna** [comment]
I am getting exactly the first error @arogozhnikov reported:

` FloatSpatialGridSamplerBilinear_updateOutput received an invalid combination of arguments - got (int, Tensor, Tensor, Tensor, int), but expected (int state, torch.FloatTensor input, torch.FloatTensor grid, torch.FloatTensor output, int padding_mode)`

and I don't understand what is the problem. Can someone help on this?

**Comment by soumith** [comment]
@riccardosamperna if you use PyTorch v0.4.1, you should get a better error message helping you on what's wrong.

**Comment by riccardosamperna** [comment]
Thanks for your reply @soumith. I found out that the problem was the hidden state in my recurrent net, I did not use the .cuda()
