### ISSUE TITLE
[MPS] tensors loaded via torch.load() -- when transferred to GPU -- do not honour indices/views

### ISSUE THREAD

**Issue by Birch-san** [pytorch/pytorch#86052]
### 🐛 Describe the bug

Transferring-to-GPU a tensor loaded via `torch.load()` may give you a tensor with incorrect contents.

**EDIT:** I found a more minimal repro; read the comment I posted after this, to see how to do this without downloading `embeddings.pt`.

I've left the original repro in this headline post for a better understanding of the context in which this was discovered.

============

I saved out a [textual inversion](embedding) for stable-diffusion, [created on MPS](https://github.com/Birch-san/stable-diffusion/blob/3548866e020ef0ddcb6b594984c2eb36d17341bd/ldm/modules/embedding_manager.py#L212-L218):  
[embeddings.pt.zip](https://github.com/pytorch/pytorch/files/9690423/embeddings.pt.zip)

I loaded it in again to attempt inference. `torch.load()` creates a CPU tensor correctly, but when the tensor is moved to GPU its contents totally change:  
https://github.com/invoke-ai/InvokeAI/pull/814#discussion_r981759629

```python
from torch import load

def main():
    device='mps'
    ckpt = load('embeddings.pt', map_location='cpu')

    assert 'string_to_token' in ckpt
    string_to_token_dict = ckpt["string_to_token"]

    placeholder_token = string_to_token_dict['*']

    cpu_item = placeholder_token.item()
    assert cpu_item == 265

    # you can prevent the problem's reproducing by uncommenting this line:
    # placeholder_token = placeholder_token.detach().clone()

    placeholder_token = placeholder_token.to(device)
    gpu_item = placeholder_token.item()
    assert gpu_item == cpu_item, f"GPU item was: {gpu_item}, expected {cpu_item}. This indicates failure to transfer tensor from CPU to GPU"

    print("Okay, if you got this far then there's no problem.")


if __name__ == '__main__':
    main()
```

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/6141784/193412973-7f4a7912-00c4-47ca-98d8-78ac88211529.png">

~~I was unable to produce a more minimal repro by saving a tensor of my own via randn();~~ I think there's something significant about how the tensor was created during training, prior to its being pickled. feels like some of the precursors in the tensor graph used to compute it are still in there.

49406 is not a random number. it's the token id for the first token in a CLIP-tokenized prompt.

Reproduces on 1.12.1 stable and on recent nightly 1.13.0.dev20220928.

### Versions

```
PyTorch version: 1.13.0.dev20220928
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.5-arm64-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.7.6
[pip3] torch==1.13.0.dev20220928
[pip3] torch-fidelity==0.3.0
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.7.0
[pip3] torchvision==0.14.0.dev20220928
[conda] numpy                     1.23.1          py310h220015d_0  
[conda] numpy-base                1.23.1          py310h742c864_0  
[conda] pytorch                   1.13.0.dev20220928        py3.10_0    pytorch-nightly
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.7.0                    pypi_0    pypi
[conda] torchvision               0.14.0.dev20220928       py310_cpu    pytorch-nightly
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by Birch-san** [comment]
okay, I found an _even more minimal_ repro which does not require loading that pickle. it's still necessary to do save + load, but you can make the tensor yourself.

```python
from torch import load, save, tensor

def main():
    device='mps'
    filename = 'test.pt'
    state = tensor([49406, 265])[1]
    save(state, filename)

    placeholder_token = load(filename, map_location='cpu')

    cpu_item = placeholder_token.item()
    assert cpu_item == 265

    # you can prevent the problem's reproducing by uncommenting this line:
    # placeholder_token = placeholder_token.detach().clone()

    placeholder_token = placeholder_token.to(device)
    gpu_item = placeholder_token.item()

    # gets 49406 instead of 265. the indexing we asked for was not honoured.
    assert gpu_item == cpu_item, f"GPU item was: {gpu_item}, expected {cpu_item}. This indicates failure to transfer tensor from CPU to GPU"

    print("Okay, if you got this far then there's no problem.")


if __name__ == '__main__':
    main()

```

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/6141784/193414141-1da88a06-f82b-405e-b438-44fae9d06829.png">

**Comment by malfet** [comment]
Thank you for the reproducer. This sounds weirdly familiar.

**Comment by malfet** [comment]
Removing this line fixes the problem, but why was it there in the first place?
https://github.com/pytorch/pytorch/blob/960b98128e475b15b66119f325232039799852cd/aten/src/ATen/native/mps/operations/Copy.mm#L213

**Comment by kulinseth** [comment]
> Removing this line fixes the problem, but why was it there in the first place?
> 
> https://github.com/pytorch/pytorch/blob/960b98128e475b15b66119f325232039799852cd/aten/src/ATen/native/mps/operations/Copy.mm#L213

It was a conservative check to update offsets only In the case of views and non contiguous tensors . Not sure if there were other scenarios where storage offset will be non zero

**Comment by malfet** [comment]
Here is one line reproducer:
```
% python -c "import torch;x=torch.arange(2);y=x[1].detach();print(y, y.to('mps'))"
tensor(1) tensor(0, device='mps:0')
```

**Comment by kulinseth** [comment]
Thanks @malfet.
