### ISSUE TITLE
DISABLED test_fake_crossref_backward_amp_linalg_lstsq_cuda_float32 (__main__.TestFakeTensorCUDA)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#86059]
### 🐛 Describe the bug

Platforms: linux

I thought that this was related to https://github.com/pytorch/pytorch/pull/85920, but it's confirmed to be not the case because the reverted PR also fails due to this flakiness test.

Some example flakiness:

* https://hud.pytorch.org/pytorch/pytorch/commit/c2d9ea7f4b54c7d4332bc457fd76238c61f129de
* https://hud.pytorch.org/pytorch/pytorch/commit/4b86a9359ae1cc0dd9e9b0480eee72850c7565b6
* https://hud.pytorch.org/pytorch/pytorch/commit/9bf9db57be42a9d2ba77e3042578ac439848aec1
* https://hud.pytorch.org/pytorch/pytorch/commit/b562987c28b37009d2d95d9506b67e3c16fab83e

### Versions

Linux CUDA 11.6

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by albanD** [comment]
cc @ezyang

**Comment by ezyang** [comment]
I can actually reproduce this locally, taking a look

**Comment by ezyang** [comment]
but clearing the autocast cache explicitly doesn't help

**Comment by ezyang** [comment]
trying https://zdevito.github.io/2022/08/16/memory-snapshots.html

**Comment by ezyang** [comment]
OK, so the issue is that autocast is caching a cast, which ordinarily would be fine as we'd clear it with clear_cache, but the cast is happening in an autograd thread, and the cache is thread local, so clearing the cache only clears the cache on the main thread, thus leak.

**Comment by huydhn** [comment]
In the new workflow to rerun disable tests [here](https://hud.pytorch.org/pytorch/pytorch/commit/1d6a188d08829b1aee28eb1e6255d5bf43a77f16), `test_fake_crossref_backward_amp_linalg_lstsq_cuda_float32 (__main__.TestFakeTensorCUDA)` is not flaky after 1600 reruns. So I will close this one by Friday Nov 25th.  Please put a comment if this still needs to be open for any reasons.

**Comment by vkuzo** [comment]
https://github.com/pytorch/pytorch/pull/86492 hopefully fixed this, sg to close if there is no more repro
