### ISSUE TITLE
[ONNX] Support `aten::trunc`

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#86084]
`aten::trunc` is created by `torch.trunc`. We just should support it for all rounding modes.

**Comment by Dante7162** [comment]
Can I contribute to this, I've never contributed to OSS before and I'm not sure where to start.

**Comment by justinchuby** [comment]
@Dante7162 Thanks! I think we have this handled

**Comment by justinchuby** [comment]
https://github.com/onnx/onnx/issues/4588
