### ISSUE TITLE
`AttributeError: module 'torch.quantization' has no attribute 'get_default_config'`

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pytorch/pytorch#86109]
### 📚 The doc issue

[On the quantization Doc](https://pytorch.org/blog/introduction-to-quantization-on-pytorch/)

```
torch.quantization.get_default_config
```
is used, while `AttributeError: module 'torch.quantization' has no attribute 'get_default_config'`

Torch Version = `1.12.1`

### Suggest a potential alternative/fix

Add the correct code

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by jerryzh168** [comment]
yeah, it's probably updated to `get_default_qconfig`, and please don't refer to blog post for apis, we have more up to date apis in https://pytorch.org/docs/stable/quantization.html and https://pytorch.org/docs/stable/quantization-support.html

**Comment by jerryzh168** [comment]
closing for now since the issue should be resolved, please feel free to reopen if it's not

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot :)
