### ISSUE TITLE
[feature request] Make from_numpy method externally visible

### ISSUE THREAD

**Issue by varunagrawal** [pytorch/pytorch#8611]
## Issue description

Currently, most Python linters complain that `torch` has no method `from_numpy`. Since converting from a numpy array to a Pytorch tensor is pretty common, it would be nice to add `from_numpy` to the `__all__` list in the `torch` module to remedy this.

I believe this to be an easy fix and not break anything, but rather make production code linters work better with Pytorch.

## Code example

```python
x = numpy.rand(3, 3)
t = torch.from_numpy(x)  # pylint complains that torch has no method from_numpy
```

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: Quadro P5000
Nvidia driver version: 384.111
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn_static.a

Versions of relevant libraries:
[pip3] msgpack-numpy (0.4.1)
[pip3] numpy (1.14.2)
[pip3] tensorboard-pytorch (0.7.1)
[pip3] torch (0.4.0)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.2.1)
[conda] tensorboard-pytorch       0.7.1                     <pip>
[conda] torch                     0.4.0                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by fmassa** [comment]
I think this is an easy fix indeed, but I wonder if `from_numpy` is not going to be deprecated in favour of `as_tensor`?

**Comment by SsnL** [comment]
Yeah I think we are deprecating `from_numpy`, but this should be fixed. The related issue is likely https://github.com/pytorch/pytorch/issues/7318

**Comment by varunagrawal** [comment]
Wouldn't that be a breaking change? I don't quite understand the need to deprecate `from_numpy` given numpy is the predominant library for numerical computing in Python.
Having `as_tensor` as an additional method would be great for extensibility.

**Comment by SsnL** [comment]
@varunagrawal Eventually, yes. But we won't suddenly do it. It will be a deprecation warning for a couple versions before we drop it.

**Comment by SsnL** [comment]
I don't remember the exact reasoning for deprecating it though. Maybe @fmassa knows?

**Comment by varunagrawal** [comment]
The reasoning seems good. Though a lot of early adopters will need to update their code once `as_tensor` becomes the standard.

I'm closing this issue in favor of #7318. Thank you for your time @SsnL and @fmassa!

**Comment by joehoeller** [comment]
Instead of a numpy array, I have a cupy array (cupy is a gpu enabled drop-in replacement for numpy).

`cupy_array = cu.array([1,2,3,4,5,6])
print(cupy_array)`

`tensor_cnv = torch.from_numpy(cupy_array)`

Error:
TypeError                                 Traceback (most recent call last)
<ipython-input-64-a81541e377fc> in <module>
----> 1 tensor_cnv = torch.from_numpy(cupy_array)
      2 print(tensor_cnv)

TypeError: expected np.ndarray (got cupy.core.core.ndarray)

**Comment by joehoeller** [comment]
I fixed it --> When working with #cupy and #pytorch, you might have to do a couple things diff to turn a #numpy / cupy array into a tensor. First you need to copy the numpy (cupy )array, this will allocate new memory for numpy array . This is to prevent  negative strides within Ndarray which are  the number of locations in memory between beginnings of successive array elements. Next, we flip it with the Axis in the array, which  tells which entries are reversed. Lastly, we can finally convert the copied array to a tensor.

```
import torch
import cupy as cu
torch.as_tensor(cu.flip(cu.copy(cu.array([1,2,3,4,5,6])),axis=0))
```

**Comment by joehoeller** [comment]
For full on GPU compute, use:

` torch.tensor(cu.flip(cu.copy(cu.array([1,2,3,4,5,6])),axis=0), dtype=torch.float16, device='cuda:0')`
