### ISSUE TITLE
torch.clear_autocast_cache() doesn't actually clear every cache

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#86136]
### 🐛 Describe the bug

This causes https://github.com/pytorch/pytorch/issues/86059

Autocast cache is thread local:

```
using weakref_type = c10::weak_intrusive_ptr<TensorImpl, UndefinedTensorImpl>;
using val_type = std::tuple<weakref_type, Tensor>;
thread_local std::unordered_map<TensorImpl*, val_type> cached_casts;
```

Clearing it only clears the local cache

```
void clear_cache() {
  cached_casts.clear();
}
```

This means if other threads (e.g., autograd backwards triggering an autocast) stash into the cache you will permanently leak. We should fix this, probably by making the cache global (and synchronizing it)

cc @gchanan @zou3519 @mcarilli @ptrblck @vkuzo 

### Versions

master

**Comment by ezyang** [comment]
cc @eellison

**Comment by vadimkantorov** [comment]
Also, should it be under torch.autocast namespace?

**Comment by ezyang** [comment]
Yeah I agree!

**Comment by vadimkantorov** [comment]
Also, maybe some debug information about what's currently cached (or at least some numbers), could be good for debugging (similar to memory snapshots)

**Comment by kshitij12345** [comment]
Potentially fixed in https://github.com/pytorch/pytorch/pull/86492

cc: @ezyang

**Comment by vkuzo** [comment]
I never had an actual repro but looks like https://github.com/pytorch/pytorch/issues/86059 is not flaky anymore so I think we can close this and reopen if there are any reports of further issues.
