### ISSUE TITLE
[feature request] No grad decorator

### ISSUE THREAD

**Issue by pimdh** [pytorch/pytorch#8621]
It would be nice if the context managers that enable/disable autograd could be used a decorator. This would allow one to write code like:
```
@torch.no_grad()
def test(args):
    pass
```
In Python 3, this can be trivially implemented with a [ContextDecorator](https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator), but for Python 2 a solutions should be easy too.

As a workaround I currently use a wrapper in Python 3:
```
@contextmanager
def no_grad():
    with torch.no_grad():
        yield
```
which works since `contextmanager` implements `ContextDecorator`,

**Comment by SsnL** [comment]
It's already implemented on master. :)
