### ISSUE TITLE
clip_grad_norm_ to handle params from multiple gpus

### ISSUE THREAD

**Issue by jpilaul** [pytorch/pytorch#8623]
This PR is a request to support parameters that are on multiple gpus in `clip_grad_norm_`. I recently did something similar to:

    class MyModel(nn.Module):
        def __init__(self, split_gpus):
            self.large_submodule1 = ...
            self.large_submodule2 = ...
            self.split_gpus = split_gpus
        if split_gpus:
            self.large_submodule1.cuda(0)
            self.large_submodule1.cuda(1)

        def forward(self, x):
            x = self.large_submodule1(x)
            if split_gpus:
                x = x.cuda(1) # P2P GPU transfer
            return self.large_submodule2(x)
(ref: https://discuss.pytorch.org/t/model-parallelism-in-pytorch-for-large-r-than-1-gpu-models/778)

and ran into issues when I tried `clip_grad_norm_(MyModel.paramaters(), clip)` --> I was getting the following error message 

> arguments are located on different GPUs

As a fix:

I have done the following in `clip_grad.py`:

    device_p = p.get_device()
            try:
                if total_norm.is_cuda and total_norm.get_device() != device_p:
                    total_norm = total_norm.cuda(device_p)
           except:
               pass

and

        device_p = p.get_device()
        if clip_coef.is_cuda and clip_coef.get_device() != device_p:
            clip_coef = clip_coef.cuda(device_p)

Thanks!

**Comment by ngimel** [comment]
Works now
