### ISSUE TITLE
CI/MergeBot actions are delayed due to GitHub Incident

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#86277]
## Current Status
Resolved (by Github)

## Error looks like
No errors as no workflows are scheduled.

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:00a incident began?
- 10/05 7:30a detected by @ezyang  observing that mergebot is not merging
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
https://www.githubstatus.com/incidents/smn1qtqvbsb6

## Mitigation
Not much...

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by ZainRizvi** [comment]
Fixed by github and webhooks are firing normally now
