### ISSUE TITLE
Error when applying CUDA Graph to a Recommendation System called DLRM

### ISSUE THREAD

**Issue by 1264089591** [pytorch/pytorch#86281]
### 🐛 Describe the bug

When I apply CUDA Graph to DLRM,
a TypeError occured: Module.apply() takes 2 positional arguments but 16 were given

### Versions

CUDA 10.4 pytorch

cc @mcarilli @ezyang

**Comment by Aidyn-A** [comment]
Hi @1264089591,

Could you please share a little more details about your use case? A minimal code snippet would be the most helpful in understanding the issue and debugging it.

**Comment by 1264089591** [comment]
> Hi @1264089591,
> 
> Could you please share a little more details about your use case? A minimal code snippet would be the most helpful in understanding the issue and debugging it.

@Aidyn-A 

Hi, Aidyn
I want to apply cuda graph to dlrm.

There exist an function to apply cuda graph after capture graph in your code:
        def functionalized(*user_args):
            # Runs the autograd function with inputs == all inputs to the graph that might require grad
            # (explicit user args + module parameters)
            # Assumes module params didn't change since capture.
            out = Graphed.apply(*(user_args + module_params))
            return out[0] if output_was_tensor else out

However, when I tried to apply cuda graph to dlrm:
a TypeError occured: Module.apply() takes 2 positional arguments but 16 were given.
user_args and module_params are 2 positional arguments, there are more input when building DLRM for user_args, it is no longer 1 positional arguments and I don't know why DLRM has more positional arguments on module_params than other models.

**Comment by Aidyn-A** [comment]
@1264089591,
Are you using https://github.com/facebookresearch/dlrm?

**Comment by Aidyn-A** [comment]
@1264089591, I am not sure what is happening in [facebookresearch/dlrm](https://github.com/facebookresearch/dlrm). However, [this DLRM](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Recommendation/DLRM) implementation was designed to work with CUDA Graphs.

**Comment by 1264089591** [comment]
@Aidyn-A Ok, thanks a lot!

**Comment by bdhirsh** [comment]
Closing for now, feel free to re-open this issue if you think there's a bug.
