### ISSUE TITLE
Replace signature in autocast registrations 

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#86294]
## Issue description

Autocast uses a macro to define rules for each operator:

https://github.com/pytorch/pytorch/blob/8c6d352bcfa3a8d2f7322d3577117b2d432cd002/aten/src/ATen/autocast_mode.cpp#L305-L309

The macro needs to accept SIGNATURE. Since we've added the at::_ops namespace, we can actually get the SIGNATURE for an op easily, it is `decltype(&ATEN_FN(op))`. This is what we do in functorch.

Deleting the `SIGNATURE` argument would let us clean up all the registrations https://github.com/pytorch/pytorch/blob/8c6d352bcfa3a8d2f7322d3577117b2d432cd002/aten/src/ATen/autocast_mode.cpp#L330-L339

One reason why we might not want to use `decltype(&ATEN_FN(op))` is because the at::_ops namespace doesn't have a good interaction with SymInt operators right now. So I'm not sure this cleanup is worth it. cc @mcarilli @ptrblck @ezyang @bdhirsh

**Comment by ezyang** [comment]
the interaction is just that if you symintify you have to immediately update the kernel as well. For autocast this is fine, we should sign up to update them immediately. So I'm pro this change.

**Comment by zou3519** [comment]
Completed by the stack starting with https://github.com/pytorch/pytorch/pull/86402
