### ISSUE TITLE
Variable.requires_grad property spread procedure behaves differently on CUDA and CPU mode

### ISSUE THREAD

**Issue by splintersu** [pytorch/pytorch#863]
`
import torch as th
from torch.autograd import Variable

x = Variable(th.Tensor([1 , 2 , 3]) , requires_grad = False)
y = Variable(th.Tensor([100]) , requires_grad = True)

x = x.cuda(0)
y = y.cuda(0)

x[0] = y

print(x.requires_grad)
`

If (x=x.cuda(0) y=y.cuda(0)) is executed then the output is False, True otherwise.
I think the result that x.requires_grad = True is more natural.

**Comment by splintersu** [comment]
I further checked some in-place operator in GPU mode(say, x = Variable(...).cuda(0) ), and find out that after the operation is done, the requires_grad of the Variable doesn't change. For example:
`
import torch as th
from torch.autograd import Variable
x = Variable(torch.Tensor([1]) , requires_grad = False)
y = Variable(torch.Tensor([2]) , requires_grad = True)

x = x.cuda(0)
y = y.cuda(0)

x.add_(y)
print(x.requires_grad)
`
the output is False

**Comment by apaszke** [comment]
It doesn't have to do with Variable holding a CUDA tensor, but rather with the fact that it's no longer a leaf. I've sent a fix in #868.

**Comment by apaszke** [comment]
Thanks for the report!
