### ISSUE TITLE
[Checkpoint] CheckpointSequential to support non-reentrant checkpoint

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#86328]
### 🚀 The feature, motivation and pitch

There are some use cases that use `checkpoint_sequential` but are limited due to lack of some features in reentrant checkpoint, we should enable non-reentrant here as well.

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @albanD

**Comment by albanD** [comment]
Yes we should add that.
