### ISSUE TITLE
M1 runner i-0ea74b8b580d2fd5a is low on disk space

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#86376]
### 🐛 Describe the bug

See:
https://github.com/pytorch/pytorch/actions/runs/3196320377/jobs/5218356674
https://github.com/pytorch/pytorch/actions/runs/3198186276/jobs/5223404230
https://github.com/pytorch/pytorch/actions/runs/3198549826/jobs/5223625308

### Versions

N/A

cc @seemethere @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
We now can use the runbook  at https://github.com/fairinternal/pytorch-gha-infra/blob/main/macos-runners/Makefile to clean them up, i.e. `make cleanup-mac-runner`.  However, the problematic issue now is they loss the ssh connection somehow while still serving traffic,  I have no clue why yet and haven't reported this few days ago https://github.com/pytorch/test-infra/issues/841

**Comment by huydhn** [comment]
Ugh, now all of them have lost SSH connection instead of only some like 3 days ago.  I wonder if a mac auto-update screws this up

**Comment by malfet** [comment]
Resolved the issues by deleting 42Gb CoreSymbolicatoionD file:
```
 42G	com.apple.coresymbolicationd
```

**Comment by malfet** [comment]
Added a little bit of automation in https://github.com/pytorch/pytorch-canary/pull/144
