### ISSUE TITLE
Improve FX naming for getitem calls

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#86446]
### 🐛 Describe the bug

When I have a tuple destructure, I end up with

```
getitem_0 = operator.getitem(add_0, 0)
getitem_1 = operator.getitem(add_0, 1)
getitem_2 = operator.getitem(add_0, 2)
getitem_3 = operator.getitem(add_0, 3)
```

names in FX IR. The getitem variable names are useless, they tell me nothing about where the name came from. A better naming scheme would see past the operator.getitem and derive a name based on the input variable name to the getitem call, e.g.,

```
add_0_0 = operator.getitem(add_0, 0)
add_0_1 = operator.getitem(add_0, 1)
add_0_2 = operator.getitem(add_0, 2)
add_0_3 = operator.getitem(add_0, 3)
```

### Versions

master

cc @SherlockNoMad @EikanWang @jgong5 @wenzhe-nrv @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith

**Comment by ezyang** [comment]
cc @SherlockNoMad

**Comment by HridayM25** [comment]
Can I have a go at this? This would be my first issue with PyTorch!
