### ISSUE TITLE
avg_pool2d/3d padding behaviour default

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#8644]
[Spotted by InnovArul/Arulkumar on the forums](https://discuss.pytorch.org/t/f-avg-pool2d-different-behavior-in-different-pytorch-versions/19901), thank you!

The documentation for avg_pool2d/3d says
```
count_include_pad: when True, will include the zero-padding in the
        averaging calculation. Default: True
```
Indeed, the default was just that up to PyTorch 0.2.
In 0.3-0.4 the default is False for 2d/3d and True 1d and the doc says it was True for all. The change in default happened when nn.yaml replaced the previous mechanism of calling THNN.

Now I was about to submit a PR reverting the default to True, but the subtle twist is that TF uses False by default.
avg_pool2d is used in the wild, e.g. by ResNet.

Should I change the docstring or should I change the default in nn.yaml?
Do you have an opinion (@soumith @colesbury maybe)?

Best regards

Thomas

**Comment by t-vi** [comment]
So after submitting this, I saw that the module interface uses count_include_pad=True all along, so the right option seems to be to have the same in the functional interface. I'll submit a PR.

**Comment by soumith** [comment]
we should indeed default functional interface to True as well. Thanks for the PR
