### ISSUE TITLE
Segfault in c10::TensorImpl::raw_mutable_data when using non-primitive dtype on non-CPU device

### ISSUE THREAD

**Issue by mergian** [pytorch/pytorch#86450]
### 🐛 Describe the bug

In `c10::TensorImpl::raw_mutable_data` ( https://github.com/pytorch/pytorch/blob/v1.12.1/c10/core/TensorImpl.h#L1805 ) memory with non-primitive dtype gets initialized via:

```cpp
data_type_.placementNew()(storage_.data(), numel_);
```

However, when the storage is located on a different device (i.e. GPU), then it's not possible to run the host's `placementNew()` method on that data. We ran into this issue when allocating data for `c10::complex<float>` and `c10::complex<double>` dtypes.

The `placementNew` runs the following code on the host, but using a device ptr, which causes a segfault.
```cpp
template <typename T>
inline void _PlacementNew(void* ptr, size_t n) {
  T* typed_ptr = static_cast<T*>(ptr);
  for (const auto i : c10::irange(n)) {
    new (typed_ptr + i) T;
  }
}
```

A reproducing code fragment (you can use any non-CPU device type)
```cpp
auto meta	= caffe2::TypeMeta::Make<c10::complex<float>>();
auto K		= c10::DispatchKey::VE;
auto D		= c10::DeviceType::VE;
auto allocator	= c10::GetAllocator(D);

// create empty storage, so the Tensor is forced to allocate new memory when resizing
auto storage = c10::make_intrusive<c10::StorageImpl>(
	c10::StorageImpl::use_byte_size_t(), 0, allocator->allocate(0), allocator, true);

// create tensor
auto th = new c10::TensorImpl(storage, c10::DispatchKeySet(K), meta);

// resize
size_t shape[] = {1, 2, 100};
th->Resize(c10::IntArrayRef(shape, 3));

// trigger segfault
th->raw_mutable_data(meta);
```

Relevant stack trace:
```
#0  0x00007fffe7410815 in void caffe2::detail::_PlacementNew<c10::complex<float> >(void*, unsigned long) ()
   from /home/xxx/.local/lib/python3.7/site-packages/torch/lib/libc10.so
#1  0x00007fffcc15a354 in c10::TensorImpl::raw_mutable_data(caffe2::TypeMeta) ()
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 10.3.0
Clang version: Could not collect
CMake version: version 3.23.1
Libc version: glibc-2.17

Python version: 3.7.12 (default, Feb  6 2022, 20:29:18)  [GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] (64-bit runtime)
Python platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Is CUDA available: False
CUDA runtime version: 11.4.120
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.12.1
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.13.1
[pip3] veda-pytorch==1.12.1.post6
[conda] Could not collect

cc @jbschlosser @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by samdow** [comment]
Not adding high pri since it seems like a non-vanilla usage

**Comment by ezyang** [comment]
Hmmm complex shouldn't get placement new-ed on construction

**Comment by mergian** [comment]
Well we are using the official Torch package from PYPI together with an C++ extension. Simplified we are doing something like this:

```python
tensor = torch.tensor([], dtype=torch.float32, device=device)
our_ctypes_lib.some_function(tensor._cdata)
```

```c++
void some_function(c10::TensorImpl* tensor) {
	int64_t shape[4] = {1, 2, 3, 4};
	tensor->Resize(c10:IntArrayRef(shape, 4));
	auto ptr = tensor->raw_mutable_data(caffe2::TypeMeta::Make<c10:complex<float>>());
	...
}
```

We chose this approach, as our C++ function computes the shape of the tensor, and we didn't want to go back and forth between C++ and Python.

As workaround we are currently allocating the ```c10::StorageImpl``` ourselves and put it into the tensor using ```set_storage_keep_dtype(...)```.

**Comment by ezyang** [comment]
The problem is probably use of Resize which is a legacy caffe2 method (not the capitals) and probably doesn't handle complex correctly on cuda

**Comment by ezyang** [comment]
The codepath where raw mutable data lazily allocates storage is also caffe2 legacy haha. But in any case the fix is to make sure complex TypeMeta doesn't report needing placement new

**Comment by mergian** [comment]
Good to know. And what is the non-deprecated way to allocate memory in an empty Tensor, that has been created within Python, and then to resize it within C++?

**Comment by ezyang** [comment]
tensor.resize_(...) or I guess if that's complaining our internal kernels usually use native::resize_output or something like that
