### ISSUE TITLE
torch.optim.lr_scheduler.LinearLR start_factor should be greater than 0

### ISSUE THREAD

**Issue by mikael10j** [pytorch/pytorch#86454]
### 🐛 Describe the bug

In `torch.optim.lr_scheduler.LinearLR`  setting `start_factor` to 0 leads to "division by zero" error.

Code to reproduce:

```
from torch.optim import Adam
from torch.optim.lr_scheduler import LinearLR
import torch.nn as nn

# Dummy net
net = nn.Linear(10, 10)
opt = Adam(net.parameters())
scheduler = LinearLR(opt, start_factor=0, total_iters=4)
for epoch in range(10):
    scheduler.step()
```
Result:
```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Input In [32], in <cell line: 9>()
      8 scheduler = LinearLR(opt, start_factor=0, total_iters=4)
      9 for epoch in range(10):
---> 10     scheduler.step()

File ~/miniconda3/envs/glearn/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:154, in _LRScheduler.step(self, epoch)
    152 if epoch is None:
    153     self.last_epoch += 1
--> 154     values = self.get_lr()
    155 else:
    156     warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)

File ~/miniconda3/envs/glearn/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:546, in LinearLR.get_lr(self)
    543 if (self.last_epoch > self.total_iters):
    544     return [group['lr'] for group in self.optimizer.param_groups]
--> 546 return [group['lr'] * (1. + (self.end_factor - self.start_factor) /
    547         (self.total_iters * self.start_factor + (self.last_epoch - 1) * (self.end_factor - self.start_factor)))
    548         for group in self.optimizer.param_groups]

File ~/miniconda3/envs/glearn/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:546, in <listcomp>(.0)
    543 if (self.last_epoch > self.total_iters):
    544     return [group['lr'] for group in self.optimizer.param_groups]
--> 546 return [group['lr'] * (1. + (self.end_factor - self.start_factor) /
    547         (self.total_iters * self.start_factor + (self.last_epoch - 1) * (self.end_factor - self.start_factor)))
    548         for group in self.optimizer.param_groups]

ZeroDivisionError: float division by zero
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro M2200
Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.6.5
[pip3] torch==1.12.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.6.0               habf752d_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            14_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            14_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            14_linux64_mkl    conda-forge
[conda] mkl                       2022.0.1           h06a4308_117    anaconda
[conda] nomkl                     2.0                           0    anaconda
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch                   1.12.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-lightning         1.6.5              pyhd8ed1ab_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchmetrics              0.9.3              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.13.0               py39_cu116    pytorch

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @vincentqb

**Comment by soulitzer** [comment]
Thanks for the catch, we'd accept a fix for this.
