### ISSUE TITLE
Mac M1 queue build up

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#86466]
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
Ongoing

## Error looks like
There is a queue build up for macos-m1-12 on https://hud.pytorch.org/metrics

## Incident timeline (all times pacific)
* Oct 7th 7AM: Queue starts to build up

## User impact
With land validation in place, people won't be able to merge there change blocking by mac m1 jobs

<img width="1693" alt="Screen Shot 2022-10-07 at 10 46 35" src="https://user-images.githubusercontent.com/475357/194618694-6199c795-bed1-4e2f-8022-50bab1ac9a90.png">

## Root cause
TBD

## Mitigation
TBD

## Prevention/followups
TBD

cc @ezyang @gchanan @zou3519

**Comment by huydhn** [comment]
From @malfet https://github.com/organizations/pytorch/settings/actions/runners?qr=label:macos-m1-12 all runners are used up to build binaries, but the link is not accessible (404) for non-admin users

**Comment by malfet** [comment]
@atalman can you please confirm it is the case? Also, how many runners we currently have online?

**Comment by huydhn** [comment]
Some runners has been taken offline, so we need someone with admin token to re-provision them @seemethere 

```
WRITE ERROR: Failed to create a session. The runner registration has been deleted from the server, please re-configure.
```

On the other hand, if the runner is offline and also non-ssh accessible, they are going to be stuck in that state I think

**Comment by huydhn** [comment]
The queue has been cleaned now, some clean up tasks will follow later

**Comment by malfet** [comment]
@huydhn can you please take an action item trying to identify, what caused a spike? I.e. it does not look like M1 runners were ever down, nor that we have much more of them now than 7 hours ago, so what happened?

**Comment by malfet** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/2453524/195181235-50fc9915-2b49-4058-a6fa-e529cfb3bd71.png">
Post factum queue times:

| Time | Queue |
|------ | ------- |
| 7AM PST  | 1.0h |
| 8AM PST | 1.9h |
| 9AM PST | 2.8h |
| 10AM PST | 3.5h |
| 11AM PST  |46min |
---------

**Comment by ZainRizvi** [comment]
@seemethere for remediation on bringing back the M1 runners which were lost
