### ISSUE TITLE
[ONNX] Simplify ort arg preparation logic, improve verification.verify compatibility

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#86471]
1.  `verification.verify` errors when certain legitimate inputs to PyTorch are passed in. For example, 

```
SampleInput(input=tensor([[ 2.8507, -7.8243,  8.4356,  6.3639,  4.9961],
        [ 1.0210,  4.1417, -2.8135, -3.1410,  4.7389],
        [ 1.4058,  8.6238,  0.1615, -0.5133,  5.2271],
        [-4.3796, -7.9953,  0.3017,  8.8549, -6.8767],
        [ 1.4129, -5.8897, -7.7333, -0.0664, -3.2023]]), args=(-2, -1), kwargs={})
```

to `torch.norm()` will throw an error.

2. The input preparation logic from torch input to ONNX runtime is complicated right now. There may be a possibility we can simplify it.

cc @BowenBao

**Comment by thiagocrepaldi** [comment]
Maybe a specific approach for https://github.com/microsoft/onnx-converters-private/issues/90?
