### ISSUE TITLE
[pytorch] `torch.autograd.gradcheck` failed with `torch.stack`, `torch.cat`

### ISSUE THREAD

**Issue by fehiepsi** [pytorch/pytorch#8649]
The following script replicates the issue:
```
import torch
def f(bx):
    return torch.stack([x for x in bx]).sum()
bx = torch.rand(2, 3, requires_grad=True)
torch.autograd.gradcheck(f, (bx,))  # Fail!
```
The same thing happened with `torch.cat`.

**Comment by SsnL** [comment]
Could you try with double precision?

**Comment by apaszke** [comment]
The precision still matters in `.sum()` (the `eps` might be too small to even be reflected in the final result).

**Comment by SsnL** [comment]
@apaszke you are right :)

**Comment by fehiepsi** [comment]
@SsnL Using double precision passes the above script. But the gradchecks for MultivariateNormal distribution still fail. There might be another reason which I will try to find out.

**Comment by SsnL** [comment]
@fehiepsi It might be useful to gradcheck `_batch_lowrank_mahalanobis` and `_batch_lowrank_logdet` separately.

**Comment by SsnL** [comment]
I'm closing this for now. But I opened an issue to warn/raise in gradcheck if input is not double precision at https://github.com/pytorch/pytorch/issues/8659.

**Comment by fehiepsi** [comment]
@SsnL I am pretty sure that the implement of `_batch_lowrank_mahalanobis` or `_batch_potrf_lower`,... is not quite relevant. I disable the Mahalanobis term, errors still happen. Instead of potrf_lower, I did `matrix.exp().tril()`, errors still happen. To me, the error is relevant to the combo of `expand`, `stack`,...

**Comment by SsnL** [comment]
@fehiepsi If you can come up with an small example that reproduces the issue on current github master, I can take a look tomorrow. Please try to just use pytorch ops, i.e. without distribution objects if you can.

**Comment by fehiepsi** [comment]
Yes, confirmed!
```
import torch
def f(bx):
    bbx = bx.expand((10,) + bx.shape)
    return torch.stack([x for x in bx]).sum()
bx = torch.rand(2, 3, dtype=torch.float64, requires_grad=True)
torch.autograd.gradcheck(f, (bx,))  # Fail!
```

**Comment by SsnL** [comment]
Ha expand + select. Might actually be related to the other issue I am fixing #8626 . Thanks! I will look tomorrow.

**Comment by SsnL** [comment]
@fehiepsi Confirm will be fixed by the patch I'm working on. But that may take 1 or 2 more days. If you need this now I can separate the fix for this into a small patch. let me know!

**Comment by fehiepsi** [comment]
@SsnL Thanks! Just take your time. It is not necessary for the mvn implementation now because it might just affect the gradcheck test.
