### ISSUE TITLE
[ONNX] Create an input adapter for suppling torch module input to onnxruntime

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#86506]
ONNX runtime does not take inputs the same way as pytorch does. Currently there is a step in the verifier that massages the input into what onnx runtime expects. It would be helpful to extract this into a standalone adapter.

**Comment by thiagocrepaldi** [comment]
Ideally, we should remove the limitation in favor or officializing the limitation

The main limitations are:
* full `dict` support @shubhamjain0594 is working on it
  * it might be an ONNX spec limitation or torch.onnx.export implementation
* full `optional` support
  * optional was recently introduced, but we probably didn't leverage its power to support "advanced inputs"
* custom types
  * I've vented the idea of adding support to `dataclass` into onnx exporter to "serialize" opaque types, but never proposed a design for it (nor validated the idea)

More limitations might exist
