### ISSUE TITLE
wrong results after `optimize_for_inference`

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#86527]
### 🐛 Describe the bug

Using the model below, the results could be wrong if I use `optimize_for_inference` to optimize the model.

```python
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile
import torch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.const = torch.rand(1,2,1,1)
        self.layer = nn.Conv2d(
            2, 1, kernel_size=(1,2),
        )

    def forward(self, i0):
        x = torch.multiply(i0, self.const)
        x = self.layer(x)
        o0 = torch.clip(x, -1.5, 1.5)
        o1 = torch.floor(x)
        return o0, o1

def build():
    inp = {
        'i0': torch.rand(1,2,2,2,),
    }

    mod = MyModule()
    exported = torch.jit.trace(mod, list(inp.values()))
    exported = torch.jit.optimize_for_inference(exported)

    out = mod(**inp)
    print(f'{out = }')

    eout = exported(**inp)
    print(f'{eout = }')

    assert torch.allclose(out[0], eout[0])

build()
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by malfet** [comment]
Likely a duplicate of https://github.com/pytorch/pytorch/issues/86556

**Comment by Co1lin** [comment]
@malfet Hi! It's ture that they look similar. But an interesting thing is that, if I remove another output tensor, only outputing the tensor produced by `clip`, the results are right.

**Comment by Co1lin** [comment]
For this issue, `floor` affects the results. For #86556, `max` affects the results.

**Comment by Co1lin** [comment]
It works fine after https://github.com/pytorch/pytorch/issues/86556 was fixed. Thank you!
