### ISSUE TITLE
[docs] torch.backends.* not documented

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#8653]

**Comment by t-vi** [comment]
I took a look here.
It is difficult to use docstrings + sphinx here for the properties using the ContextProp class - I haven't found a way trying docstrings in various forms and suggestions I found. My impression is that with the module replacement trick, ContextProp could be replaced by regular properties (I tried and it seemed to work), would that be OK, @ezyang ?

**Comment by ezyang** [comment]
@t-vi What do you mean by regular properties?

**Comment by t-vi** [comment]
@ezyang: Currently we use a custom `ContextProp` class
```
class ContextProp(object):
    def __init__(self, getter, setter):
        self.getter = getter
        self.setter = setter

    def __get__(self, obj, objtype):
        return self.getter()

    def __set__(self, obj, val):
        if not flags_frozen():
            self.setter(val)
        else:
            raise RuntimeError("not allowed to set torch.backends.cudnn flags "
                               "after disable_global_flags; please use flags() context manager instead")
```
and then in `CudnnModule`:
```
    enabled = ContextProp(torch._C._get_cudnn_enabled, torch._C._set_cudnn_enabled)
```
the [standard Python way](https://docs.python.org/3/library/functions.html#property) would be to define getter and setter like:
```
    @property
    def enabled(self):
        """Flag to enable or disable use of CuDNN if it is available"""
        return torch._C._get_cudnn_enabled()
    @enabled.setter
    def enabled(self, value):
        check_not_flags_frozen()
        torch._C._set_cudnn_enabled(value)
```
(with a new `check_not_flags_frozen` utility function to avoid the boilerplate in the properties).

It is a tad longer (at least if you have more than one or two properties), but it get's rid of reinventing the wheel and plays nicely with documentation (sphinx picks up the docstring, it shows up in `help(cudnn.backends)` etc. I've not been able to get docstrings + sphinx to work with context prop.

I know that the change is not necessary for the execution of the code and I can see the hesitation to change something that works, but if there isn't a technical reason for not changing it to the usual Python way, I'd think the better standardization and documentation might just be worth it.

**Comment by ezyang** [comment]
Aha! If it works, I'm all for it.

**Comment by t-vi** [comment]
OK, I'll send a PR.

**Comment by t-vi** [comment]
So I managed to get docstrings (and ? in IPython) to work, but I cannot get sphinx to use them :(
