### ISSUE TITLE
cuda.list_gpu_processes() uses the 'wrong' device order (PCI_BUS_ID)

### ISSUE THREAD

**Issue by adammj** [pytorch/pytorch#86539]
### 🐛 Describe the bug

As far as I can tell, all other torch.cuda functions use the same device order (where the largest or most capable GPU is ordered first, versus when it was found on the PCI bus). However, list_gpu_processes uses the bus order. 

This is easy to test if you have 2 GPUs, with the least capable one listed first in nvidia-smi. For me:

    # nvidia-smi order
    # 0. GTX 745
    # 1. GTX 1080 Ti 

    import torch
    
    # demonstrate the PyTorch cuda order
    print(torch.cuda.get_device_name(0))  # prints: NVIDIA GeForce GTX 1080 Ti
    print(torch.cuda.get_device_name(1))  # prints: NVIDIA GeForce GTX 745
    
    # specify the 0th device
    dev = torch.device("cuda", 0)

    # verify no processes
    print(torch.cuda.list_gpu_processes(0))  # prints: GPU:0 no processes are running
    print(torch.cuda.list_gpu_processes(1))  # prints: GPU:1 no processes are running
    
    # add a variable to the device
    tempvar = torch.zeros([10,10]).to(dev)
    
    # verify wrong order processes
    print(torch.cuda.list_gpu_processes(0))  # prints: GPU:0 no processes are running
    print(torch.cuda.list_gpu_processes(1))  # prints: GPU:1 process. 100492 uses 437 MB GPU memory

    
    

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 745
GPU 1: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] torch==1.12.1
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0           py310h7f8727e_0
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0
[conda] mkl_random                1.2.2           py310h00e6091_0
[conda] numpy                     1.23.1          py310h1794996_0
[conda] numpy-base                1.23.1          py310hcba007f_0
[conda] pytorch                   1.12.1          py3.10_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchvision               0.13.1              py310_cu113    pytorch

cc @ngimel

**Comment by malfet** [comment]
Yes, this is sort of expected behavior from implementation point of view, as `list_gpu_processes` uses NVML API (there are no CUDA APIs to query that information)
But its pretty straightforward to create NVML to CUDA device mapping. @ngimel  what do you think?

**Comment by ngimel** [comment]
Yeah this should be straightforward. We'll accept a PR :-)

**Comment by adammj** [comment]
I'll gladly make the PR, but I need some hint of where the NVML to CUDA mapping could come from. When I was exploring nvml there were a lot of functions to getting the device in different ways, but I found no corresponding functions in any of the other get_device-like function called by the other PyTorch functions. I was thinking the UUID mapping would be the most robust.
