### ISSUE TITLE
pytorch_jni.dll and pytorch_jni.lib missing from LibTorch Windows zip archives after 1.10.2

### ISSUE THREAD

**Issue by Dris101** [pytorch/pytorch#86536]
### 🐛 Describe the bug

`pytorch_jni.dll` and `pytorch_jni.lib` are missing from the `lib` directory in the LibTorch bundles for Windows after 1.10.2

See for example:-
[1.12.1 CUDA 11.6 Archive](https://download.pytorch.org/libtorch/cu116/libtorch-win-shared-with-deps-1.12.1%2Bcu116.zip) _et al._ and, as of writing, current nightly

See also:-

#78483
#46464

This breaks the Java TorchScript bindings unfortunately 

### Versions

LibTorch > 1.10.2

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
Thank you for reporting the issue. Will accept the PR that fixes the issues

**Comment by cristianPanaite** [comment]
Hello @Dris101,

I just made a PR that should solve this issue. @malfet Can you help me with it? https://github.com/pytorch/pytorch/pull/93057

**Comment by Dris101** [comment]
Hi @cristianPanaite. I'm seeing those dlls in the nightlies now. Thanks very much for your help! My build-foo is not up to fixing that!
