### ISSUE TITLE
NotImplementedError: The operator 'aten::_linalg_slogdet.sign' is not currently implemented for the MPS device.

### ISSUE THREAD

**Issue by d4rk-lucif3r** [pytorch/pytorch#86549]
### 🐛 Describe the bug

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/45912425/194755808-61971d57-e7c1-42d0-ae2f-cfc9c36ac9e8.png">

sigma_pos = torch.mean(torch.bmm((pos_all-mu_pos).unsqueeze(-1), (pos_al   
sigma_neg = torch.mean(torch.bmm((neg_all-mu_neg).unsqueeze(-1), (neg_al   
a = 17.0795
H = 0.25 * (torch.logdet(sigma_pos) + torch.logdet(sigma_neg))

### Error
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/45912425/194755919-fe345d91-7c5e-44fb-8e8c-9b49e319848d.png">

### Versions

PyTorch version: 1.13.0.dev20221004
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-13.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] facenet-pytorch==2.5.2
[pip3] idx2numpy==1.2.3
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytorch-tabnet==3.1.1
[pip3] torch==1.13.0.dev20221004
[pip3] torch-lr-finder==0.2.1
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchbnn==1.2
[pip3] torchray==1.0.0.2
[pip3] torchvision==0.15.0.dev20221004
[conda] facenet-pytorch           2.5.2                    pypi_0    pypi
[conda] idx2numpy                 1.2.3                    pypi_0    pypi
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch                   1.13.0.dev20221004         py3.9_0    pytorch-nightly
[conda] pytorch-tabnet            3.1.1                    pypi_0    pypi
[conda] torch                     1.13.0.dev20220621          pypi_0    pypi
[conda] torch-lr-finder           0.2.1                    pypi_0    pypi
[conda] torchaudio                0.14.0.dev20220603          pypi_0    pypi
[conda] torchbnn                  1.2                      pypi_0    pypi
[conda] torchray                  1.0.0.2                  pypi_0    pypi
[conda] torchvision               0.14.0.dev20220621          pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
As error message suggest, please discuss missing operators for MPS in  https://github.com/pytorch/pytorch/issues/77764
