### ISSUE TITLE
Confusing error message for RNN/LSTM (incorrect input dimension)

### ISSUE THREAD

**Issue by jyx-su** [pytorch/pytorch#86576]
### 🐛 Describe the bug

The error message for input shape does not match the real input for tensors with more than 3 dimensions.

```python
import torch
layer1 = torch.nn.LSTM(10,20,batch_first=True)
layer1(torch.zeros((5,100,10,10)))[0].shape
```

The error message indicates "RuntimeError: input must have 3 dimensions, got 5", but the real input has 4 dimensions only (not 5). 

I checked the source code, and it seems the issue is at line 739 of https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py. It added an additional batch dimension.

### Versions

1.12.0

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by kshitij12345** [comment]
@jyx-su Thank you for opening the issue. You are right, we add a batch dimension incorrectly before erroring.

The following line seems to be the issue where we assume if `input.dim != 3`, then it is unbatched.

https://github.com/pytorch/pytorch/blob/c6b7c33885eeff9dc125f87c7134772d59d0ba21/torch/nn/modules/rnn.py#L444

I think the fix would be to have an assert before this to ascertain `input.dim in (2, 3)`. 
Also, I think all RNN Modules (RNN, GRU, LSTM) suffer from the same issue.

@jyx-su would you be interested in sending a patch?

**Comment by jyx-su** [comment]
Sure
