### ISSUE TITLE
Strange behavior with .permute and MPS backend

### ISSUE THREAD

**Issue by hsperr** [pytorch/pytorch#86589]
### 🐛 Describe the bug

Permuting the channels of an image (converting from HxWxC to CxWxH) gave strange behavior on MPS backend. After moving individual images to and from the device sometimes the image would come back empty. While trying to narrow down the issue I found that permute doesn't behave as it should when moving to and from MPS backend (see example below)

Looking through the old issues I have the impression this could be related:
https://github.com/pytorch/pytorch/issues/79383
But is was more about `. contiguous` (in the examples functions like `squeeze()` was used maybe that triggered the misbhavior?

System: OSX Monetery (12.6) - Apple M1 Pro
torch version: 1.12.1
numpy version: 1.21.5

```
import torch
import numpy as np

array = np.array([[0, 0, 1], [0, 0, 1]])
tensor = torch.from_numpy(array)

print(tensor.permute(1, 0))

>>>tensor([[0, 0],
        [0, 0],
        [1, 1]])

tensor.permute(1, 0).to('mps').cpu()
>>> tensor([[0, 0],
        [0, 1],
        [0, 1]])
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] numpy-base                1.21.5           py39hadd41eb_3
[conda] pytorch                   1.12.1                  py3.9_0    pytorch
[conda] torchaudio                0.12.1                 py39_cpu    pytorch
[conda] torchvision               0.13.1                 py39_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
From the latest nightly I no longer see this issue, can you please give it a try?

**Comment by spiegelball** [comment]
I can't reproduce it on master neither, but I am still seeing an error with permute and bilinear interpolation on mps device.
```
int main(int argc, const char * argv[]) {
    auto t = torch::ones({1,2,2,2}).to("mps");
    auto t_permuted = t.permute({0,3,1,2});
    
    std::vector<int64_t> s;
    s.push_back(2);
    s.push_back(2);
    
    torch::nn::functional::InterpolateFuncOptions options = torch::nn::functional::InterpolateFuncOptions().size(s).mode(torch::kBilinear);
    auto bilinear = torch::nn::functional::interpolate(t, options);
    auto bilinear_permuted = torch::nn::functional::interpolate(t_permuted, options);
    
    options = torch::nn::functional::InterpolateFuncOptions().size(s).mode(torch::kArea);
    auto area_permuted = torch::nn::functional::interpolate(t_permuted, options);
    
    std::cout << "bilinear result:\n " << bilinear << std::endl;
    std::cout << "bilinear permuted result:\n " << bilinear_permuted << std::endl;
    std::cout << "area permuted result:\n " << area_permuted << std::endl;
 
}
```
which gives:
```
bilinear result:
 (1,1,.,.) = 
  1  1
  1  1

(1,2,.,.) = 
  1  1
  1  1
[ MPSFloatType{1,2,2,2} ]
bilinear permuted result:
 (1,1,.,.) = 
  0  0
  0  0

(1,2,.,.) = 
  0  0
  0  0
[ MPSFloatType{1,2,2,2} ]
area permuted result:
 (1,1,.,.) = 
  0  0
  0  0

(1,2,.,.) = 
  0  0
  0  0
[ MPSFloatType{1,2,2,2} ]
```
The bilinear interpolation on the permuted tensor on mps device is wrong.

**Comment by hsperr** [comment]
I installed `2.0.0.dev20221220` is that the correct version? 

On this version I get the expected behavior

**Comment by kulinseth** [comment]
@hsperr , thanks for checking. I can confirm, i am getting the expected behavior on latest nightly:

```
>>> import numpy as np
>>> array = np.array([[0, 0, 1], [0, 0, 1]])
>>> tensor = torch.from_numpy(array)
>>> print(tensor.permute(1, 0))
tensor([[0, 0],
        [0, 0],
        [1, 1]])
>>> tensor.permute(1, 0).to('mps').cpu()
tensor([[0, 0],
        [0, 0],
        [1, 1]])
```

**Comment by kulinseth** [comment]
@spiegelball this is the behavior I am seeing with latest PyTorch nightly:


```
[W upsampling.h:105] Warning: Default upsampling behavior when mode=kBilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details. (function interpolate)
[W upsampling.h:105] Warning: Default upsampling behavior when mode=kBilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details. (function interpolate)
bilinear result:
 (1,1,.,.) =
  1  1
  1  1

(1,2,.,.) =
  1  1
  1  1
[ MPSFloatType{1,2,2,2} ]
bilinear permuted result:
 (1,1,.,.) =
  1  1
  1  1

(1,2,.,.) =
  1  1
  1  1
[ MPSFloatType{1,2,2,2} ]
area permuted result:
 (1,1,.,.) =
  1  1
  1  1

(1,2,.,.) =
  1  1
  1  1
[ MPSFloatType{1,2,2,2} ]
```
