### ISSUE TITLE
`./test/test_public_bindings.py` does not check all modules

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#86619]
If a module is not imported at the time `./test/test_public_bindings.py` walks it, it will not be checked.  This means there are many modules that should be failing these tests, but are not.

Adding an `import X` statement in unrelated code, can cause failures in `test_public_bindings`.

https://github.com/pytorch/pytorch/pull/86461 imported these modules which do not pass this test:
```
    "torch.fx.experimental.normalize",
    "torch.fx.experimental.proxy_tensor",
    "torch.fx.experimental.schema_type_annotation",
    "torch.fx.experimental.symbolic_shapes",
    "torch.fx.passes.backends.cudagraphs",
    "torch.fx.passes.infra.partitioner",
    "torch.fx.passes.utils.fuser_utils",
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by malfet** [comment]
I wonder `test_public_bindings.py` correctly lists `module: autograd` as an owner. It should be `oncall: jit`, isn't it?

**Comment by jansel** [comment]
`test_public_bindings` is unrelated to both autograd and JIT.

**Comment by jansel** [comment]
> The goal of this test is to make sure that all the public API provided by `import torch` follow some specific rules. If you change modifies what gets imported by `import torch`, I think that it is expected that these will start to be tested?

Neither `torch._dynamo` nor `torch._inductor` should imported by running `import torch`.  They do get imported by other test infra though.

**Comment by jansel** [comment]
These modules remain not-imported-by-`import torch`:
```
>>> import torch
>>> torch.fx.passes.utils.fuser_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch.fx' has no attribute 'passes'
```

They do get imported by dynamo though:
```
>>> import torch._dynamo
>>> torch.fx.passes.utils.fuser_utils
<module 'torch.fx.passes.utils.fuser_utils' from '/home/jansel/pytorch/torch/fx/passes/utils/fuser_utils.py'>
```

**Comment by albanD** [comment]
> Neither torch._dynamo nor torch._inductor should imported by running import torch. 

I think the `initDynamoBindings` does actually import them by creating these modules and adding them to `torch.`.

**Comment by jansel** [comment]
> > Neither torch._dynamo nor torch._inductor should imported by running import torch.

Nope, just the two files in `torch._C._dynamo`:
```
>>> import torch
>>> torch._dynamo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute '_dynamo'
>>> torch._C._dynamo
<module 'torch._C._dynamo'>
>>> 
```

**Comment by zou3519** [comment]
@albanD, to clarify: do we want all modules, regardless of whether or not `import torch` imports them, to be checked for public API? For example, torch.fx.experimental.normalize looks like public API but from the issue description is not covered by the public API checks today.

**Comment by albanD** [comment]
I'm still curious where these end up being imported then? because this test only pull in `torch.testing._internal` and `torch.testing._internal.common_utils`.

> do we want all modules, regardless of whether or not import torch imports them, to be checked for public API?

That is a good question.
I think the answer is yes it should.
There are a bunch of improvements that need to happen there as well btw to support properly all non-pkg (especially in the docs checking).
I think we would be happy for a patch adding this (not sure how to do this though).
