### ISSUE TITLE
[RFC] Move distributed checkpointing from torch.distributed._shard.checkpoint to torch.distributed.checkpoint

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#86620]
### 🚀 The feature, motivation and pitch

As part of moving distributed checkpointing to a beta feature we want it to be on a public module.

Additionally, we're broadening its scope to handle other distributed gadgets like FSDP and DistributedTensor.

The renaming would place a module redirect from the old to the new one to avoid any BC breakage.

### Alternatives

There are no immediate plans to promote ShardedTensor out of the _shard module.

### Additional context

We're aiming for Distributed Checkpoint to be a beta feature on PT 1.14 and this is one important part of it.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by wanchaol** [comment]
This looks good to me, can help review once the PRs are out. Thanks for driving this for releasing beta!
