### ISSUE TITLE
Missing typecasting in Gelu backward

### ISSUE THREAD

**Issue by wchen61** [pytorch/pytorch#86673]
Need a typecasting in this kernel code, otherwise will not generate instructions expected.

https://github.com/pytorch/pytorch/blob/55479fe80ee8df9750c2a4d1022943d04c3e46d6/aten/src/ATen/native/cuda/ActivationGeluKernel.cu#L61

cc @ngimel

**Comment by soulitzer** [comment]
Good catch, we'd accept a fix for this.
