### ISSUE TITLE
NVFuser `FusionComputeAtMultiBCast_CUDA` and `FusionDetectSelfMappedDomains_CUDA` does not raise exception on sm_80+

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#86714]
### 🐛 Describe the bug

See here for example (only change that test is compiled with sm_86 and run on A10G )
https://github.com/pytorch/pytorch/actions/runs/3222501479/jobs/5272211415
```
[ RUN      ] NVFuserTest.FusionDetectSelfMappedDomains_CUDA
/home/nshulga/git/pytorch/pytorch/torch/csrc/jit/codegen/cuda/test/test_gpu.cpp:3828: Failure
Expected: tv1->computeAt(tv4, 1) throws an exception.
  Actual: it doesn't.
[  FAILED  ] NVFuserTest.FusionDetectSelfMappedDomains_CUDA (0 ms)

```

### Versions

CI

cc @ngimel @seemethere @pytorch/pytorch-dev-infra

**Comment by davidberard98** [comment]
Same issue observed when running this internally (fbcode), but on V100.

**Comment by malfet** [comment]
@davidberard98 I was told that upgrading nvfuser should help. 
@jjsjann123  any luck with pushing the update?

**Comment by jjsjann123** [comment]
Was chatting with David on the upstream PR.

Have PR squashed here: #87779 . Working through CI. Will update once it's green.
Also got a node with Maxwell card. :crossed_fingers: Hopefully that will repro the CI failure I saw in my draft.

**Comment by ZainRizvi** [comment]
Seems like this bug was fixed by your PR @jjsjann123?

**Comment by jjsjann123** [comment]
since nvfuser is no longer enabled in torchscript. we can safely close this issue.
