### ISSUE TITLE
[c10d] Automatic discovery of IP addresses to use

### ISSUE THREAD

**Issue by pietern** [pytorch/pytorch#8672]
This is what THD does today by retrieving all non-loopback addresses of a machine and sharing them via the TCP init method or file init method. Then each node tries using them and picks the first one that works out.

This is nice because it works out of the box, including when a machine's hostname resolves to localhost.

We can leverage the store for this. Every machine writes its list of addresses to the store; look for the ones from its peers; and either a) looks for a common subnet where everybody has a different address (subnet), or b) do the THD thing and try to connect a peers to find the addresses that are routeable.

Also see the comments in #8664.

**Comment by dashesy** [comment]
I have had `init_method=file://` hung on machines with many network adapters (some IB, some docker, ...). 
This is why `NCCL_SOCKET_IFNAME` could be quite life-saving. Perhaps can you have a `PYTORCH_SOCKET_IFNAME` to avoid touching the network adapters that do not resolve at all (and thus hang)?

**Comment by pietern** [comment]
@dashesy Thanks for the comment!

If you end up using gloo with THD today, you're right there is no way to select the interface you want to use. For c10d this is opposite; you have to select the interface or address. This is also why I added this issue, because it is not a great out of the box experience to have to specify an interface.

In the case where you would opt out of automatic detection, you can create and initialize a process group (the equivalent of the global process group for THD) like so:

https://github.com/pytorch/pytorch/blob/3da27312bbda7ca10eec12092e6ca5e67f3f9d9c/test/test_c10d.py#L187-L191

The `create_tcp_device` function takes either a hostname or an interface name as keyword argument. In your case where you have a ton of interfaces where some don't resolve -- and automatic discovery fails -- you can use this to lock it down to whatever device you want to use.

For the NCCL case you would still use `NCCL_SOCKET_IFNAME` to steer it to use the right one.

**Comment by teng-li** [comment]
We should have GLOO_SOCKET_IFNAME enabled for ifname to be used with Gloo. @abdallag @dashesy
