### ISSUE TITLE
bernoulli_ is very inefficient on the GPU

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#8673]
bernoulli_ call has become very inefficient recently (may be #7578 is at fault?)

```
a.bernoulli_(p) 
```
if a is gpu float or half tensor this expands to
1) fill a size-1 *double* tensor with p value (should not be neccessary, but ok)
2) expand this *double* tensor to size of a and materialize it (unnecessary expensive copy op)
3) generate *double* tensor filled with bernoulli-distributed vars (unnecessary use of double, perf penalty)
4) copy double tensor to a (no copy should be necessary for an inplace op). 

Pytorch, current master
cc @cpuhrsch, @gchanan

**Comment by ngimel** [comment]
Indeed, #7578
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L152-L153
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Distributions.cpp#L143

**Comment by SsnL** [comment]
fixed via #8682
