### ISSUE TITLE
[MPS] Add support for aten::sort.values_stable for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86750]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::sort.values_stable](https://pytorch.org/docs/stable/generated/torch.sort.html) (supported on [MacOS 13.0 onwards](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/4057352-sortwithtensor?changes=latest_minor&language=objc)) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by hxu296** [comment]
Hello! I would like to work on this issue. The pointer to the [MPS sortWithTensor](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/4057352-sortwithtensor?changes=latest_minor&language=objc) seems very helpful. However, I wonder how to implement the `stable` parameter, as MPS's `sortWithTensor` does not have this option. I also wonder where could I find more detailed MPS documentation, like that for PyTorch. Thank you!

**Comment by kulinseth** [comment]
> Hello! I would like to work on this issue. The pointer to the [MPS sortWithTensor](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/4057352-sortwithtensor?changes=latest_minor&language=objc) seems very helpful. However, I wonder how to implement the `stable` parameter, as MPS's `sortWithTensor` does not have this option. I also wonder where could I find more detailed MPS documentation, like that for PyTorch. Thank you!

Hi @hxu296 the sortWithTensor returns stable values .

**Comment by hxu296** [comment]
Got it! Thank you for the prompt reply :)

**Comment by DenisVieriu97** [comment]
> I also wonder where could I find more detailed MPS documentation, like that for PyTorch.

Hi @hxu296! You can find more documentation about the op directly in the MPSGraph headers. E.g, for the sorting ops, you can find the header (MPSGraphSortOps.h) locally in your Xcode directory:
```$(xcrun --sdk macosx --show-sdk-path)/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/Headers/MPSGraphSortOps.h```.
If you are using Xcode, clicking **Jump to Definition** on an API (such as `sortWithTensor`) will also bring you to the same header.

**Comment by hxu296** [comment]
> > I also wonder where could I find more detailed MPS documentation, like that for PyTorch.
> 
> Hi @hxu296! You can find more documentation about the op directly in the MPSGraph headers. E.g, for the sorting ops, you can find the header (MPSGraphSortOps.h) locally in your Xcode directory: `$(xcrun --sdk macosx --show-sdk-path)/System/Library/Frameworks/MetalPerformanceShadersGraph.framework/Versions/A/Headers/MPSGraphSortOps.h`. If you are using Xcode, clicking **Jump to Definition** on an API (such as `sortWithTensor`) will also bring you to the same header.

This is very useful, thank you!

**Comment by glenn-jocher** [comment]
@DenisVieriu97 thanks for working on this. This is required for YOLOv5 MPS support in https://github.com/ultralytics/yolov5/issues/10178

**Comment by DenisVieriu97** [comment]
Closed in https://github.com/pytorch/pytorch/pull/94697#event-8499374501
