### ISSUE TITLE
GPU memory leak after running simple model forward

### ISSUE THREAD

**Issue by William1Wu** [pytorch/pytorch#86783]
### 🐛 Describe the bug

Hi, I try to figure out the reason why gpu memory increase largely 0.7 GB even model is very simple only contains a conv2d layer. In addition, It seems like the gpu memory can't be release only if the process is done. I tried to delete conv2d/input and call torch.cuda.empty.cache() but the memory allocate still exist. Is there any way to release gpu memory? Please help me, thanks.

```
import cv2
import torch

def main():
    conv2d = torch.nn.Conv2d(3, 1, 1).cuda()
    input = torch.ones((1, 3, 32, 32)).cuda()

    conv2d.eval()
    with torch.no_grad():
        conv2d(input)

    print('after forward')
    cv2.waitKey(5000)

    conv2d.cpu()
    input.cpu()
    del conv2d, input
    torch.cuda.empty_cache()

    print('free memory')
    cv2.waitKey(5000)
    return

if __name__ == "__main__":
    main()
```

- This is the snapshot of task manager before running code. The GPU memory usage is 1.0 GB

![image](https://user-images.githubusercontent.com/16698410/195261797-895d8723-f5de-4237-9135-f2ad5d0b542f.png)

- This is the snapshot of task manager when printing _free memory_. The GPU memory usage is 1.7 GB

![image](https://user-images.githubusercontent.com/16698410/195261817-f08615d7-c1d0-4f0a-bbb8-912f95625e83.png)

### Versions

PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 企業版
GCC version: (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1070
Nvidia driver version: 465.89
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.10.2+cu113
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.3+cu113
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] torch                     1.10.2+cu113             pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.11.3+cu113             pypi_0    pypi

cc @csarofeen @ptrblck @xwang233 @ngimel

**Comment by William1Wu** [comment]
I'd like to add two things:
(1) GPU memory would not be increased if repeatedly passing tensor through model
(2) Increment of GPU memory usage is same even change the shape of input tensor from [1, 32, 32] to [1, 512, 512]

**Comment by Aidyn-A** [comment]
Hi @William1Wu,

This may be cause due to the `CUDA_MODULE_LOADING` is being set to `EAGER` which means that `".. all kernels from a cubin, fatbin or a PTX file are fully loaded upon corresponding cuModuleLoad* API call."`, so it consumes the memory for these kernels (see [CUDA Programming Guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html)). I suggest for you to try lazy loading like so:
```
CUDA_MODULE_LOADING=LAZY python script.py
```

**Comment by William1Wu** [comment]
Hi @Aidyn-A 

Thanks for your reply. Could you reproduce this issue and fix it by setting CUDA_MODULE_LOADING=Lazy ?
I've failed. Here are my steps. Help me if you have any suggestion, thanks.
 
1. Set CUDA_MODULE_LOADING=LAZY on Windows 10 console:
`D:\> set CUDA_MODULE_LOADING=LAZY`

2. Add one line in code to check CUDA_MODULE_LOADING variable and this actually output LAZY.
`print(os.environ.get('CUDA_MODULE_LOADING', ''))`

3. Run code
`D:\> python main.py`

**Comment by William1Wu** [comment]
Hi All, 

I got a sad answer from NVIDIA FAE on last Friday. 
This problem can't be resolved. 
Because the memory is occupied by CUDA CONTEXT and users are able to free this memory only close the process.
