### ISSUE TITLE
[MPS] Add support for aten::erfinv.out for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86808]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::erfinv.out](https://pytorch.org/docs/stable/generated/torch.erfinv.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by aaronabraham311** [comment]
Hi I would like to claim this!

**Comment by kulinseth** [comment]
> Hi I would like to claim this!

Thanks @aaronabraham311

**Comment by aaronabraham311** [comment]
Hi I was working on this issue and I wanted to confirm whether I am going down the right track.

I realized that I need to add a function in `aten/src/ATen/native/mps/operations/UnaryOps.mm` following the example laid out in [this PR](https://github.com/pytorch/pytorch/pull/87147). However, it seems like there's no easy way of calculating the inverse error function of a tensor using just matrix math.

I was digging around in the repo and I found [this code snippet](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Math.h#L151-L196) where someone had implemented the inverse error function. Would I need to port this over using the Metal operations, or is there any easier/more recommended way of doing this?

**Comment by qqaatw** [comment]
@DenisVieriu97 @kulinseth I think `erfinv` should probably not be categorized as good first issue as it relates to integral approx., and even metal standard library has not implement it. [ref](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf).

**Comment by kulinseth** [comment]
> @DenisVieriu97 @kulinseth I think `erfinv` should probably not be categorized as good first issue as it relates to integral approx., and even metal standard library has not implement it. [ref](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf).
Yes. `erfinv`, might be tricky. Currently we are not targeting it.

**Comment by shamoons** [comment]
Is this still up for grabs?

**Comment by TaiPhamD** [comment]
@shamoons I am actually done with it and it passes unit testing I just wanted to spend a bit more time to optimize the memory before I re-open my pull request.

**Comment by nullhook** [comment]
is this landing in 2.1?

**Comment by qqaatw** [comment]
> is this landing in 2.1?

I think it's in 2.1. Let me know if you have issues using it.
