### ISSUE TITLE
[MPS] Add support for aten::hardswish for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86807]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::hardswish](https://pytorch.org/docs/stable/generated/torch.nn.Hardswish.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by thomaslin2020** [comment]
Hi, I would like to try this. I'm assuming that this would follow a similar procedure as that mentioned in [this post](https://github.com/pytorch/pytorch/issues/86810#issuecomment-1277939432)/

**Comment by DenisVieriu97** [comment]
Hi @thomaslin2020 - thank you for the interest!

> I'm assuming that this would follow a similar procedure as that mentioned in https://github.com/pytorch/pytorch/issues/86810#issuecomment-1277939432?

Yes, this is right. This is an activation function and it belongs to [Activation.mm](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/Activation.mm).  As a reference, you can take a look at [threshold](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/Activation.mm#L622) ([doc](https://pytorch.org/docs/stable/generated/torch.nn.Threshold.html)) or [prelu](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/Activation.mm#L1650) ([doc](https://pytorch.org/docs/stable/generated/torch.nn.PReLU.html)), they are pretty similar.

For testing, you can use [test_threshold](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L1171) as a reference (from [test_mps.py](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py)). Then you can run your test using `python3 test_mps -k test_hardswish`).

**Comment by kulinseth** [comment]
https://github.com/pytorch/pytorch/pull/94342
https://github.com/pytorch/pytorch/pull/87952
