### ISSUE TITLE
[MPS] Add support for aten::sgn.out for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86805]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::sgn.out](https://pytorch.org/docs/stable/generated/torch.sgn.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by malfet** [comment]
This doesn't sound like a good first time issue, as MPS backend does not currently support complex dtypes, does it?

**Comment by DenisVieriu97** [comment]
https://github.com/pytorch/pytorch/pull/84739

**Comment by duckheada** [comment]
any updates on this?

**Comment by malfet** [comment]
Grabbing for myself, as I need it to properly test polar as part of https://github.com/pytorch/pytorch/pull/107324

**Comment by x4080** [comment]
Any progress on this ?

**Comment by kitkatkinderr** [comment]
Up

**Comment by geyue1** [comment]
Up
the same problem

**Comment by 410312774** [comment]
the same problem

**Comment by plannaAlain** [comment]
Same problem

**Comment by kebwi** [comment]
I'm confused why there is an Oct. 8 comment above indicating the issue is closed. I am encountering this error with a fresh PyTorch installation (v2.1.2). Is the implication of that comment that the problem is supposed to have been resolved by now?

**Comment by pattplatt** [comment]
> I'm confused why there is an Oct. 8 comment above indicating the issue is closed. I am encountering this error with a fresh PyTorch installation (v2.1.2). Is the implication of that comment that the problem is supposed to have been resolved by now?

Yes, same here with v2.1.2

**Comment by SchmidtPhilipp** [comment]
Same problem!

**Comment by TysBradford** [comment]
I have same issue. Found [this relevant discussion](https://github.com/pytorch/pytorch/pull/110829#issuecomment-1868571367).
Basically the fix is in v2.2.0 but the nightly torch package in pip still points to v2.1.2.

**Comment by frameadvisors** [comment]
Up

**Comment by Sithael** [comment]
up

**Comment by ledunguit** [comment]
Any working progress on this?

**Comment by Wang-Yu-Qing** [comment]
Up

**Comment by kmulcar** [comment]
https://sebastianraschka.com/blog/2022/pytorch-m1-gpu.html

**Comment by rafaelvareto** [comment]
Same problem here! Any possible solution? Running PyTorch 2.2.1 on a MacOs 12.7.6.

**Comment by AndrewChasen** [comment]
same problem here!

**Comment by hamada147** [comment]
Workaround here for a similar method `aten::unfold_backward`
At the beginning of the file before the torch import. I set this code `os.environ["PYTOCH_ENABLE_MPS_FALLBACK"] = "1"` which falls back to using the CPU instead of MPS for all the methods that have yet to be supported on MPS.

I hope this helps some of you till we get full support for these methods.
