### ISSUE TITLE
[MPS] Add support for aten::fmod.Tensor_out for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86810]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::fmod.Tensor_out](https://pytorch.org/docs/stable/generated/torch.fmod.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by kulinseth** [comment]
> I would like to try this! Could you give a brief overview of what to do?

Thanks for your interest @ShisuiUzumaki.  I think you can follow a general process:
1. Look at the spec of the Operation you are implementing, in this case fmod : https://pytorch.org/docs/stable/generated/torch.fmod.html
2. Being an elementwise Binary operator, it will belong in [BinaryOps.mm](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/BinaryOps.mm). you can follow the structure of the code there.
3. Also for adding an op in MPS backend, we have model PRs[ to follow:  ](https://github.com/pytorch/pytorch/pull/78408). You can also look at the recent ops added using the [MPS] tag. 
4. The graph can be constructed in this case using the operations:
```
torch.fmod(a, b) == a - a.div(b, rounding_mode="trunc") * b
```
5. For testing you can use the [TestConsistency ](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L7080). And add fmod there.

**Comment by ShisuiUzumaki** [comment]
@kulinseth I will look it up

**Comment by kulinseth** [comment]
> @kulinseth This is my first-time contribution involving C++ code, so I want to clarify a few things
> 
> First of all, the method that implements fmod op has to go to BinaryOps.mm and then I will have to map it to equivalent operation in python using YAML. Secondly, I will have to follow usual flow of MPS code, like using MPS namespaces etc., right?

Right so the function name will be same which will be added to the yaml file . Say in this case fmod_out_mps . Also yes just follow the usual flow of mps namespaces

**Comment by ShisuiUzumaki** [comment]
> > @kulinseth This is my first-time contribution involving C++ code, so I want to clarify a few things
> > 
> > First of all, the method that implements fmod op has to go to BinaryOps.mm and then I will have to map it to equivalent operation in python using YAML. Secondly, I will have to follow usual flow of MPS code, like using MPS namespaces etc., right?
> 
> Right so the function name will be same which will be added to the yaml file . Say in this case fmod_out_mps . Also yes just follow the usual flow of mps namespaces 

@kulinseth  I would like to ask something regarding YAML and that is what exactly the structure of YAMLmapping is. I am asking this just clarify my confusion

**Comment by ShisuiUzumaki** [comment]
I have gotten quite vlbusy lately so have not had the chance to work on this issue. If someone wants to take it up, feel free to do so

**Comment by suprajb** [comment]
@DenisVieriu97 
since @ShisuiUzumaki says they haven't found the time to work on this, I can pick it up.

**Comment by DenisVieriu97** [comment]
Hi @ShisuiUzumaki - sorry for the slow answer. I've added below some documentation about native_function.yaml in case you're still interested

> @kulinseth and/or @DenisVieriu97 Could you explain the structure of YAM file mapping. What I mean is could you give an example from YAML file that this C++ function is invoked when this python function is called. Like what do different keys represent in YAML file. for instance, structured, variants, dispatch, structured_inherits, structured_delegate, CompositeExplicitAutograd, etc.

These structured kernels are already implemented - they are generic functions for all vendors, that do the shape checking, memory allocation, before calling into the `out` variant.  E.g in this case, only the [fmod.Tensor_out](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L8675) function would need to be implemented:

You can read more about structured kernels at:
https://docs.google.com/presentation/d/1_PBXPBD5ArFAD8fPh7yJ1L1QHOow2akKCc7C86OwaEQ/edit#slide=id.gc36d913cc7_2_84

**Comment by DenisVieriu97** [comment]
> @DenisVieriu97
> since @ShisuiUzumaki says they haven't found the time to work on this, I can pick it up.

Hi @suprajb - sure! Please go for it
Let me know if you have any questions

**Comment by PumeTu** [comment]
@suprajb Are you still working on this, if not I would be interested in taking this issue?

**Comment by PumeTu** [comment]
I replicated how [`std::fmod`](https://en.cppreference.com/w/cpp/numeric/math/fmod) was implemented in C++ for this functionality.

**Comment by kulinseth** [comment]
https://github.com/pytorch/pytorch/pull/94722
