### ISSUE TITLE
Split (with sizes) doesn't work with 0 sizes

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#8686]
I'd expect that once we specify the sizes of the split, as long as they sum to the number of elements, they should work. But once we have zero in some of the split sizes, this doesn't hold anymore.

The following snippet illustrates the problem
```python
a = torch.rand(10)
print(a.split([5, 5]))  # works

print(a.split([5, 5, 0])  # fails with
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 10 (input tensor's size at dimension 0), but got split_sizes=[5, 5, 0, 0]

print(a.split([0, 5, 5])  # fails with
RuntimeError: length out of range
```

The first error happens because of [this early break](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorShape.cpp#L366), and the second error because `narrow` doesn't support `len=0` yet (but I believe support for this is coming very soon).

I'm using PyTorch `'0.5.0a0+db5bc71'`

**Comment by ptrblck** [comment]
@gchanan 
Would it be possible for me to have a look at it, since I've implemented the python code a while ago?
Or are you already working on it?

**Comment by fmassa** [comment]
The fix on the python side is fairly easy. Here is a quick (python) implementation (but beware that I might have missed I few checks):

```python
def split_with_sizes(tensor, split_sizes, dim=0):
    """
    Similar to split, but with a fix for
    https://github.com/pytorch/pytorch/issues/8686
    """
    assert sum(split_sizes) == tensor.shape[dim]
    result = []
    start_idx = 0
    for length in split_sizes:
        if length == 0:
            result.append(tensor.new())
            continue
        result.append(tensor.narrow(dim, start_idx, length))
        start_idx += length
    assert start_idx == tensor.shape[dim]
    return result
```

**Comment by ptrblck** [comment]
@fmassa I would start with this code and run a few tests. Since I would like to familiarize myself with the C-API, I think it could be a good starter. What do you think?

**Comment by fmassa** [comment]
I think having a look where the function is implemented in cpp would be simpler, it might just require a few changes (typing from my phone, or else I'd send you the place in the cpp code where this is implemented)

**Comment by gchanan** [comment]
you can take a look; if you require n-dimension empty tensors (i.e. tensors with shape [....0,...]) you won't be able to do it currently, though.

**Comment by fmassa** [comment]
Ideally we would want that, or else we would need to modify this function again in the future to make it consistent

**Comment by ptrblck** [comment]
I've found `split` [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorShape.cpp#L332) and `split_with_sizes` [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/TensorShape.cpp#L354).
The latter one seems to be causing the error.

**Comment by ptrblck** [comment]
I've created an initial version of the fix, which returns `torch.tensor([])` for zero-length splits.
```python
tensor = torch.randn(4, 2)
split_sizes = [0, 1, 0, 2, 0, 1]
splits = tensor.split(split_sizes, 0)
for split in splits:
    print(split.shape)

> torch.Size([0])
> torch.Size([1, 2])
> torch.Size([0])
> torch.Size([2, 2])
> torch.Size([0])
> torch.Size([1, 2])
```
Basically I've tried to implement @fmassa's Python code.

Also I've added a test case to `test_split` in `test_torch.py`.

Unfortunately the dimension for zero-sized `tensors` will be `1`, while the splits can have an arbitrary dimension.
Could this be a problem in some use cases?

**Comment by fmassa** [comment]
@gchanan when do you think we will be able to have tensors with arbitrary dimensions containing zeros?

**Comment by gchanan** [comment]
probably this week.  `split` will likely be fixed in the patch enabling it.  @ptrblck is your code available somewhere?  FWIW you can write the test and include it now by guarding it with `@skipIfNoZeroSize`, as in: https://github.com/pytorch/pytorch/blob/8e019826c985804106f3d00600b808a5ff379a58/test/test_autograd.py#L1874

You can also write the correct code by using `#ifdef USE_TH_SIZE_ZERO_DIM` and building with
`CFLAGS="-DUSE_TH_SIZE_ZERO_DIM" DEBUG=1 python setup.py build_deps develop`.

I'm happy to take a look, although I may get to it myself in a day or two when we enable zero sized dims.

**Comment by ptrblck** [comment]
@gchanan Thanks for the information on `@skipIfNoZeroSize`.
You can find the code [here](https://github.com/ptrblck/pytorch/commit/e88fb278e4115d7522dde9dde37b572f42cfc7f9).

I'll take a look at fixing the tests later this evening.

**Comment by fmassa** [comment]
Fixed in master

```python
In [16]: a = torch.rand(10)

In [18]: a.split([5, 5, 0])
Out[18]:
(tensor([0.0573, 0.5911, 0.6622, 0.1818, 0.5397]),
 tensor([0.8157, 0.0701, 0.1311, 0.5290, 0.9198]),
 tensor([]))

In [19]: a = torch.rand(1, 10)

In [20]: a.split([5, 5, 0], 1)
Out[20]:
(tensor([[0.0575, 0.2239, 0.7350, 0.0133, 0.0041]]),
 tensor([[0.2594, 0.8395, 0.9294, 0.5289, 0.6348]]),
 tensor([], size=(1, 0)))
```
