### ISSUE TITLE
Unable to use torch.save() for saving model of format torch.script

### ISSUE THREAD

**Issue by MadhuriPatil1694** [pytorch/pytorch#86896]
### 🐛 Describe the bug

Code:
import torch

model=torch.jit.load('model.ts')
model2=torch.jit.load('model2.ts')

optimizer = optim.SGD(loaded.parameters(), lr=0.001, momentum=0.9)
optimizer2 = optim.SGD(loaded.parameters(), lr=0.001, momentum=0.9)

path="model.pt"
torch.save({'modelA_state_dict': model.state_dict(), # Note: the error is here
'modelA_state_dict': model2.state_dict(),
optimizer_state_dict': optimizer.state_dict(),
optimizer_state_dict': optimizer.state_dict()}, path)

Error message:

''' File  /.local/lib/python3.6/site-packages/torch/serialization.py", line 372, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)

File  /.local/lib/python3.6/site-packages/torch/serialization.py", line 476, in _save
    pickler.dump(obj)
File  /.local/lib/python3.6/site-packages/torch/tensor.py", line 95, in __reduce_ex__
    return self._reduce_ex_internal(proto)
File  /.local/lib/python3.6/site-packages/torch/tensor.py", line 162, in _reduce_ex_internal
    args = (self.storage(),
File  RuntimeError: unsupported Storage type '''

### Versions

Versions:
PyTorch version: 1.8.2+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
Python version: 3.6.9 (default, Jun 29 2022, 11:45:57)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-128-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2070 SUPER
Nvidia driver version: 450.119.03
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.1.4
[pip3] torch==1.8.2+cu102
[pip3] torch-tensorrt==1.0.0
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.9.2+cu102

cc @mruberry

**Comment by malfet** [comment]
Does it happen for every model? I.e. I can not reproduce it with resner:
```python
import torch

def save_jit():
    import torchvision
    weights = torchvision.models.ResNet50_Weights.DEFAULT
    model = torchvision.models.resnet50(weights=weights)
    jit_model=torch.jit.script(model)
    torch.jit.save(jit_model, "jit.pk")


def load_save():
    loaded_model=torch.jit.load("jit.pk")
    torch.save({"ddo": loaded_model.state_dict()}, "foo.pth")

save_jit()
load_save()
```

**Comment by MadhuriPatil1694** [comment]
I tried with the resnet50 model that you are using it works fine. The error only occurs with the model.ts that I have trained.

**Comment by malfet** [comment]
Hmm, can not reproduce it with latest trunk nor with 1.12.1:
```
>>> import torch
>>> import torchvision
>>> m=torch.jit.load("model.ts")
>>> torch.save({"m": m.state_dict()}, "foo.pth")
>>> torch.__version__
'1.12.1+cu113'
```

**Comment by malfet** [comment]
@MadhuriPatil1694 is there a reason why you need to stick to 1.8 release?

**Comment by MadhuriPatil1694** [comment]
> @MadhuriPatil1694 is there a reason why you need to stick to 1.8 release?

Yes, the current workflow works with torch 1.8, But I will think of upgrading it if this is the case. thankyou for your support
