### ISSUE TITLE
Memory leak when adding variable to itself

### ISSUE THREAD

**Issue by ankitkv** [pytorch/pytorch#869]
The following code results in a memory leak:

```
while True:
    # old a overwritten by new variable, old a should get gc'd
    a = Variable(torch.FloatTensor(32,16).cuda())  # with and without .cuda()
    a += a
```

**Comment by ankitkv** [comment]
@apaszke added this here to keep track.

**Comment by fmassa** [comment]
Isn't this a replicate of https://github.com/pytorch/pytorch/issues/839 ?

**Comment by soumith** [comment]
Yes, looks like it. Fixed in master. I'll create binaries for `v0.1.10` tomorrow evening which will have this fix.

**Comment by ankitkv** [comment]
I was able to reproduce this on master (2b23712).

**Comment by fmassa** [comment]
Maybe [this pending PR fixes it?](https://github.com/pytorch/pytorch/pull/868)
I haven't looked in detail, but @apaszke can definitely comment on that.

**Comment by apaszke** [comment]
It's fixed in that pending PR.

**Comment by soumith** [comment]
i've merged that in now. fixed in master.
