### ISSUE TITLE
torch.nn.functional.grid_sample should throw error for invalid mode

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#8693]
The only valid mode is 'bilinear', but one can pass anything to it and it will not complain:
```
torch.nn.functional.grid_sample(array_5d, indices, mode='anything')
```

**Comment by vishwakftw** [comment]
Apparently, the `mode` is not passed to the backend function for `grid_sample`. I think it should be removed.

**Comment by zou3519** [comment]
Yes. I think the idea is that we'd like to support other modes at some point.
