### ISSUE TITLE
`narrow_copy` needs to be tested with sparse inputs

### ISSUE THREAD

**Issue by nkaretnikov** [pytorch/pytorch#86931]
### 🚀 The feature, motivation and pitch

The previous version of `narrow_copy` documentation had a note about sparsity, which was removed:

> Calling ``narrow_copy`` with ``dimemsion > self.sparse_dim()`` will return a copy with the relevant dense dimension narrowed, and ``self.shape`` updated accordingly.

For example:

```py
def reference_inputs_narrow_copy(op_info, device, dtype, requires_grad, **kwargs):
    yield from sample_inputs_narrow_copy(
        op_info, device, dtype, requires_grad, **kwargs)

    # Test sparse with input dimension > self.sparse_dim()
    # https://github.com/pytorch/pytorch/pull/84493#discussion_r967248150
    yield SampleInput(
        # s.sparse_dim() == 2
        torch.ones(2, 2, 2, 2, dtype=dtype, device=device, requires_grad=requires_grad).to_sparse(2),
        args=(3, 0, 1),
    )
```

More tests here: https://github.com/pytorch/pytorch/pull/84493#discussion_r967248150

**Note: this cannot be added right now because this will also affect primTorch ref tests. And primTorch has no sparse support at the moment.**

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer @mruberry @ezyang @ngimel @Lezcano @fdrocha

**Comment by mruberry** [comment]
I think sparse inputs just get their own sample input functions to keep them separate from all the tests that expect strided tensors:

https://github.com/pytorch/pytorch/blob/c7c09722ad5ee25c5891f863e5bbd1575ad77970/torch/testing/_internal/opinfo/core.py#L682

So I believe sparse sample inputs for `narrow_copy` can be added without affecting the primTorch tests, which rely on (strided) sample or reference inputs. 

cc @cpuhrsch

**Comment by amjames** [comment]
To elaborate context: the note was removed because it was misleading about how it could be applied to sparse tensors.

The function should work on a sparse representation regardless of the number of sparse/dense dimensions or the designation of the target dimension as sparse/dense.

**Comment by nkaretnikov** [comment]
Note: I still think that both `narrow` and `narrow_copy` should say something about sparse support. The former doesn't support sparse while the latter does.

**Comment by amjames** [comment]
Okay, the removal of the note about sparsity is not really related. That original message was misleading and the removal was appropriate. 

I am going to close this as the issue "`narrow_copy` is not tested with sparse input"  is not actually true. We do tests with sparse inputs in our one-off sparse tests in `test_sparse.py`. So it's OpInfo is missing sparse samples but many still are the functionality is tested though.  

We have a general work item to migrate as much of sparse testing to OpInfos as we can which will include this function in due time. There is currently no lapse in coverage though.
