### ISSUE TITLE
Unpredictable behavior between tensors on separate devices (mps and cpu)

### ISSUE THREAD

**Issue by brochier** [pytorch/pytorch#86975]
### 🐛 Describe the bug

While using torch on a Macbook pro with M1 ship, using python 3.8.10 and torch 1.12.1, I came across a weird bug that happened because I forgot to put a tensor on MPS. The reproducible code is the following:

```
>>> import torch
>>>
>>> # Weird behavior when two tensors are not on the same device
>>> a = torch.Tensor([[1,2],[3,4], [5,6]]).to(torch.device("mps"))
>>> a
tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]], device='mps:0')
>>> a[1:,1]
tensor([4.0000, 6.0000], device='mps:0')
>>> b = torch.Tensor([-1, -1])
>>> b
tensor([-1., -1.])
>>> a[1:,1] = b
>>> a
tensor([[ 1.0000,  2.0000],
        [ 3.0000, -1.0000],
        [-1.0000,  6.0000]], device='mps:0')
>>> 
>>> # Expected behavior when both tensors are on the same device
>>> a = torch.Tensor([[1,2],[3,4], [5,6]]).to(torch.device("mps"))
>>> b = torch.Tensor([-1, -1]).to(torch.device("mps"))
>>> a
tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]], device='mps:0')
>>> b
tensor([-1., -1.], device='mps:0')
>>> a[1:,1] = b
>>> a
tensor([[ 1.0000,  2.0000],
        [ 3.0000, -1.0000],
        [ 5.0000, -1.0000]], device='mps:0')
```

As you can see, if `a` is on MPS and `b` on CPU, the line `a[1:,1] = b` wrongly replaces the index `a[2,0]`in place of the index `a[2,1]`. I would expect to have an error saying both tensors should be on the same device instead.

### Versions

I get an error:
```
Traceback (most recent call last):
  File "collect_env.py", line 505, in <module>
    main()
  File "collect_env.py", line 488, in main
    output = get_pretty_env_info()
  File "collect_env.py", line 483, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "collect_env.py", line 330, in get_env_info
    pip_version, pip_list_output = get_pip_packages(run_lambda)
  File "collect_env.py", line 302, in get_pip_packages
    out = run_with_pip(sys.executable + ' -mpip')
  File "collect_env.py", line 290, in run_with_pip
    for line in out.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'

```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by thomaslin2020** [comment]
The error seems to happen somewhere within native/mps/operations/Copy.mm. Also I'm getting a warning "The operator 'aten::nonzero' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications" when printing tensors on MPS.

**Comment by DenisVieriu97** [comment]
Hi @thomaslin2020 - thanks for filling this issue.
> I would expect to have an error saying both tensors should be on the same device instead.

This is actually an allowed usecase (copying CPU tensors into MPS tensors / MPS -> CPU / MPS -> MPS): https://pytorch.org/docs/stable/generated/torch.Tensor.copy_.html.
The issue is on MPS side when copying a CPU tensor into a strided MPS tensor. I'll take a look.
