### ISSUE TITLE
Add CUDA suppoort for sparse CSR tensors

### ISSUE THREAD

**Issue by sambaPython24** [pytorch/pytorch#86978]
### 🚀 The feature, motivation and pitch

While the CUDA support for COO tensors exists, the documentation 
in [this link](https://pytorch.org/docs/stable/sparse.html) states that "CUDA support [for sparse csr tensors] does not exist as of now ." 

On the other hand, CUDA seems to make that possible since in [Cupy Sparse](https://docs.cupy.dev/en/stable/reference/generated/cupyx.scipy.sparse.csr_matrix.html) csr arrays are defined.

It would be great, if the CUDA support would be added.

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by amjames** [comment]
That statement should be removed from the documentation. At this point we do have CUDA support for CSR. As with all sparse layouts there are some feature still missing but I would say that CUDA/CPU are very close in terms of support. 

Is there a particular op/feature you were looking for?

**Comment by amjames** [comment]
Closing this as the statement about missing CUDA support has already been removed. It should reflect in the live docs the next time they are updated.

You should be able to use CSR layout on CUDA devices, if you are missing coverage for a particular feature please open a feature request.
