### ISSUE TITLE
Pytorch Windows installation failure

### ISSUE THREAD

**Issue by cfmh84** [pytorch/pytorch#86974]
### 🐛 Describe the bug

Windows installation failure using the following command:

conda install pytorch torchvision torchaudio cpuonly -c pytorch

### Versions

Do not know if this is the right place to post but I had hard time to install windows in Anaconda.

This is the command I used: conda install pytorch torchvision torchaudio cpuonly -c pytorch

This is the error message I received:

Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://conda.anaconda.org/pytorch/win-64'

Anyone has any idea what the issue is?

I am trying to use the following zoom link on this page https://github.com/pytorch/pytorch/wiki/Contact-Pytorch-Dev-Infra-Office for the office hour but saw an "Invalid meeting id":
https://fb.zoom.us/j/97659913934?pwd=cmxlcEgxNmZJckd2dTBUVWdRZkY3Zz09

Any help would be appreciated. Thanks!

 

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
From the error you've posted it looks like your system has a limited network access (or there was a conda outage)

So please try again, and if above link is still unaccessible, then you probably need to file an issue against Anaconda.

@ZainRizvi can you please update the link in the wiki?

**Comment by cfmh84** [comment]
"Collecting package metadata (current_repodata.json): failed"

Should file "current_repodata.json" be in the folder under "https://conda.anaconda.org/pytorch/win-64/"? I checked that website but I only found "repodata.json". There is no file called "current_repodata.json".

**Comment by ezyang** [comment]
there's a conda outage right now https://github.com/ContinuumIO/anaconda-issues/issues/13073

**Comment by cfmh84** [comment]
> there's a conda outage right now [ContinuumIO/anaconda-issues#13073](https://github.com/ContinuumIO/anaconda-issues/issues/13073)

Thank you. Do you have any expected recovery timeline of conda?

**Comment by cfmh84** [comment]
The following zoom link on this page https://github.com/pytorch/pytorch/wiki/Contact-Pytorch-Dev-Infra-Office for the office hour still shows "Invalid meeting id":
https://fb.zoom.us/j/97659913934?pwd=cmxlcEgxNmZJckd2dTBUVWdRZkY3Zz09

**Comment by cfmh84** [comment]
Successfully installed eventually. Thanks.

**Comment by Blackhex** [comment]
Seems to be resolved, closing. Please reopen with additional information, if it will show up again.
