### ISSUE TITLE
[docs] Argument names in docs don't match those actually taken by function

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#8698]
## Issue description
A bunch of functions have this behaviour. Please check the script below. The functions in the script might not be exhaustive.

EDIT: Around 40 functions have this issue.
```
Exception message: addmm() missing 3 required positional argument: "input", "mat1", "mat2"
Given argument names: ['mat', 'mat1', 'mat2']
Exception message: addmv() missing 3 required positional argument: "input", "mat", "vec"
Given argument names: ['tensor', 'mat', 'vec']
Exception message: addr() missing 3 required positional argument: "input", "vec1", "vec2"
Given argument names: ['mat', 'vec1', 'vec2']
Exception message: baddbmm() missing 3 required positional argument: "input", "batch1", "batch2"
Given argument names: ['mat', 'batch1', 'batch2']
Exception message: bmm() missing 2 required positional argument: "input", "mat2"
Given argument names: ['batch1', 'batch2']
Exception message: dot() missing 2 required positional argument: "input", "tensor"
Given argument names: ['tensor1', 'tensor2']
Exception message: ger() missing 2 required positional argument: "input", "vec2"
Given argument names: ['vec1', 'vec2']
Exception message: matmul() missing 2 required positional argument: "input", "other"
Given argument names: ['tensor1', 'tensor2']
Exception message: mm() missing 2 required positional argument: "input", "mat2"
Given argument names: ['mat1', 'mat2']
Exception message: mv() missing 2 required positional argument: "input", "vec"
Given argument names: ['mat', 'vec']
```

## Code example
```
import torch

def test_function(func, inputs):
    try:
        func(**inputs)
        print("No error with function {}".format(func.__name__))
    except Exception as e:
        print("Exception message: {}\nGiven argument names: {}".format(e, list(inputs.keys())))

if __name__ == '__main__':
    cases = [
             ('addmm', {'mat': torch.randn(2, 4), 'mat1': torch.randn(3, 2, 3), 'mat2': torch.randn(3, 3, 4)}),
             ('addmv', {'tensor': torch.randn(4), 'mat': torch.randn(3, 4, 2), 'vec': torch.randn(3, 2)}),
             ('addr', {'mat': torch.randn(2, 4), 'vec1': torch.randn(3, 2), 'vec2': torch.randn(3, 4)}),
             ('baddbmm', {'mat': torch.randn(3, 2, 4), 'batch1': torch.randn(3, 2, 3), 'batch2': torch.randn(3, 3, 4)}),
             ('bmm', {'batch1': torch.randn(3, 2, 3), 'batch2': torch.randn(3, 3, 4)}),
             ('dot', {'tensor1': torch.randn(10), 'tensor2': torch.randn(10)}),
             ('ger', {'vec1': torch.randn(2), 'vec2': torch.randn(4)}),
             ('matmul', {'tensor1': torch.randn(3, 3), 'tensor2': torch.randn(3, 4)}),
             ('mm', {'mat1': torch.randn(3, 3), 'mat2': torch.randn(3, 4)}),
             ('mv', {'mat': torch.randn(3, 3), 'vec': torch.randn(3)}),
            ]
    for case in cases:
        test_function(getattr(torch, case[0]), case[1])
```
## System Info
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source (5ca4f5b)

**Comment by zou3519** [comment]
For clarification, is the problem that the documentation lists different argument names than what is actually accepted?
i.e., 
> Exception message: matmul() missing 2 required positional argument: "input", "other"
Given argument names: ['tensor1', 'tensor2']

is the docs suggesting `torch.matmul(tensor1=foo, tensor2=bar)`?

**Comment by vishwakftw** [comment]
> For clarification, is the problem that the documentation lists different argument names than what is actually accepted?

Yes

> For this case, the docs suggests torch.matmul(tensor1, tensor2, out=None) which is not entirely a problem because "tensor1, tensor2" are supposed to be positional arguments. I do agree that it would be nice for it to match what the args actually are.

There are two fixes for this.
1. Modify Declarations.cwrap, derivatives.yaml to match docs
2. Modify docs.

I am inclined towards 1, in interest of backward compatibility.

**Comment by vishwakftw** [comment]
I think it would be better to have a note in the documentation page telling that these are positional arguments, and the names to the variables in the docs are given for understandability. What do you think? @zou3519

**Comment by zou3519** [comment]
For context, kwargs can be used in place of positional args it looks like:
```

In [8]: def foo(bar, bar2):
   ...:     print(bar)
   ...:
   ...:

In [9]: foo(bar2="abc", bar="def")
def

```

**Comment by vishwakftw** [comment]
I ran into those errors because of using them as kwargs during an experiment. Hence the issue.

**Comment by ezyang** [comment]
> I am inclined towards 1, in interest of backward compatibility.

Err, wouldn't 2 be the more backwards compatible choice?

**Comment by vishwakftw** [comment]
Well, my presumption was that people learned through the docs, which means that people might use the same keyword argument names specified in the docs more often.

**Comment by yf225** [comment]
> There are two fixes for this.
> 
> 1. Modify Declarations.cwrap, derivatives.yaml to match docs
> 2. Modify docs.

I think we should go with 2, because that would not break BC for user code that already uses the actual arg names as kwargs. For user code that is not using kwargs, this doesn't actually matter anyway.

**Comment by prasunanand** [comment]
Docs have been modified already.

Please check this script. No issues reported.

```python

import torch

def test_function(func, inputs):
    try:
        func(*inputs)
        print("No error with function {}".format(func.__name__))
    except Exception as e:
        print("Exception message: {}\nGiven argument names: {}".format(e, inputs))

if __name__ == '__main__':
    cases = [
             ('addmm', [torch.randn(2, 3), torch.randn(2, 3), torch.randn(3, 3)]),
             ('addmv', [torch.randn(2),    torch.randn(2, 3), torch.randn(3)]),
             ('addr',  [torch.zeros(3, 2), torch.arange(1., 4.), torch.arange(1., 3.)]),
             ('baddbmm', [torch.randn(3, 2, 4), torch.randn(3, 2, 3), torch.randn(3, 3, 4)]),
             ('bmm', [torch.randn(3, 2, 3), torch.randn(3, 3, 4)]),
             ('dot', [torch.randn(10), torch.randn(10)]),
             ('ger', [torch.randn(2), torch.randn(4)]),
             ('matmul', [torch.randn(3, 3), torch.randn(3, 4)]),
             ('mm', [torch.randn(3, 3), torch.randn(3, 4)]),
             ('mv', [torch.randn(3, 3), torch.randn(3)])
            ]
    for case in cases:
        test_function(getattr(torch, case[0]), case[1])
        

```

**Comment by vishwakftw** [comment]
@prasunanand: your reproduction code suggests that we use positional arguments. @zou3519 also specified this in [this comment](https://github.com/pytorch/pytorch/issues/8698#issuecomment-402301620).

But if someone tries to be verbose about the arguments, it could lead to an invalid argument error while that is not really the case.

**Comment by prasunanand** [comment]
@vishwakftw  Got your point. I misunderstood.
