### ISSUE TITLE
[ONNX] Use the ONNX reference runtime for testing

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#86983]
The ORT is in the process of increasing coverage for the ONNX spec, and there are quite a few ops/types it doesn't support. An example is Ceil on float64.

This causes us needing to skip many different combinations of tests #86182.

Since the purpose of the tests are to ensure ONNX spec conformance, we can consider using the ONNX reference runtime, which is supposed to be better covered on the ONNX spec.

The reference runtime is implemented with numpy, which doesn't support bfloat16. So does not ORT's CPU execution provider so I think we are good there.

**Comment by thiagocrepaldi** [comment]
Do you have references to `ONNX reference runtime`

**Comment by justinchuby** [comment]
There is one being reviewed at https://github.com/onnx/onnx/pull/4483
