### ISSUE TITLE
[MPS] Add support for aten::argsort for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86991]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::argsort](https://pytorch.org/docs/stable/generated/torch.argsort.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend.
MPSGraph argsort documentation can be found [here](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/4097261-argsortwithtensor?language=objc).

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by shogohida** [comment]
@DenisVieriu97 
Hi, Denis! Can I work on this? It would be great to work on this because I'm a first time contributor 👍

**Comment by DenisVieriu97** [comment]
Hi @shogohida - definitely. Thanks for the interest! Let me know if you have any questions regarding the op/implementation.

**Comment by Raman-Kumar** [comment]
@DenisVieriu97 
Hi, 
General MPS op coverage tracking issue has 74 issues.
I want to contribute. Already started tracking related issues and source code. 
I am comfortable solving issues.

Can you open an issue for Not categorized ops and assign it to me?

**Comment by DenisVieriu97** [comment]
Hi @Raman-Kumar - thanks for the interest! 
Sure, there are more issues added in https://github.com/pytorch/pytorch/issues/77764 (under category **Good first issue**) - take a look there and please comment on the issue you are interested in working. Thanks!

**Comment by shogohida** [comment]
@DenisVieriu97 
Hi Denis, thanks for your help. I have a question. Do I basically need to create a similar pull request to [this](https://github.com/pytorch/pytorch/pull/78408)? 

I mean, I thought I need to code a file called Argsort.mm which includes argsort_mps instead of eye_out_mps. [This reference page](https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend) explains as below so I thought a new native function in my case is argsort_mps.

> If MPS has an existing op for the give PyTorch function, just add a new native function that link the two. An example PR that does this can be found [here](https://github.com/pytorch/pytorch/pull/78408).

**Comment by DenisVieriu97** [comment]
Hi @shogohida

> Do I basically need to create a similar pull request to https://github.com/pytorch/pytorch/pull/78408?

Yes, please use that pull request as a reference.

> I mean, I thought I need to code a file called Argsort.mm which includes argsort_mps instead of eye_out_mps. [This reference page](https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend) explains as below so I thought a new native function in my case is argsort_mps.
Yes, you will have to create a new file with `argsort_stable_mps` implementation in it. Please name the new file **Sorting.mm** so we can add more sorting algorithms later to it. The steps would be as follows:
1. Register `argsort_stable_mps` in [native_functions.yaml:8948](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L8948) (e.g MPS: argsort_stable_mps).
2. Create a new file **Sorting.mm** (you can take a look at **Eye.mm** as a reference to see which headers you need, and the right namespaces).
3. In the new file, add support for `argsort_stable_mps` (e.g `Tensor argsort_stable(const Tensor & self, bool stable, int64_t dim, bool descending) { // Implementation  }`). MPSGraph argsort function can be found at https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/4097261-argsortwithtensor?language=objc.
4. After implementing the op, add a small testcase in [test_mps.py](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py) checking the correctness of the op. You can follow [test_mm](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L273) as an example - e.g  `self.assertEqual(argsort_mps_result, argsort_cpu_result)`

Please let me know if you have any questions.

**Comment by shogohida** [comment]
@DenisVieriu97 
Thanks a lot for giving me clear instructions! It was good to know how to name the file because there is [another issue](https://github.com/pytorch/pytorch/issues/86750) related to sorting and I was not sure how I should name the file.

I'll let you know if I have more questions.

**Comment by shogohida** [comment]
@DenisVieriu97 
I created a pull request to solve this issue. I still keep it draft because it didn't pass some tests and I wasn't sure if my implementation was right. Please let me know if you think it's fine to make it ready for review!

https://github.com/pytorch/pytorch/pull/87572

**Comment by DenisVieriu97** [comment]
Closed in https://github.com/pytorch/pytorch/pull/94697#event-8499374501
