### ISSUE TITLE
[MPS] Add support for aten::range for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#86990]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::range](https://pytorch.org/docs/stable/generated/torch.range.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend.
MPSGraph documentation can be found [here](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph).

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by Shikharishere** [comment]
Hey, @DenisVieriu97 shikhar here, I am new to open source can you guide me through this issue.

**Comment by DenisVieriu97** [comment]
Hi @Shikharishere - thanks for the interest in this op!

Below is a list of good starting points:
1. Check out the official spec for [aten::range](https://pytorch.org/docs/stable/generated/torch.range.html).
2. Register the op: for this, you will need to add the function name in [native_functions.yaml](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L4203) (e.g: MPS: `range_mps_out`) - similar as it's done for [aten::arange](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L681).
3. Add the support for the op in [RangeFactories.mm](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/RangeFactories.mm#L53) (note that if you named the function `range_mps_out` in `native_functions.yaml`, you'll need to use the same name here for the function signature (e.g `Tensor& range_mps_out(const Scalar& start, const Scalar& end, const Scalar& step, Tensor& result { .. }`). 
4. You can use [arange](https://pytorch.org/docs/stable/generated/torch.arange.html) as a reference for the implementation of `range` (they are pretty similar - in case of `range`, the final shape will differ). MPS `arange` implementation is found in [RangeFactories.mm:54](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/RangeFactories.mm#L54). 
5. After implementing the op, add a small test in [test_mps.py](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py) to check for the correctness of the op against the cpu. You can use [test_arange](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L4572) as a reference. After implementing it, you can test it using `python3 test_mps.py -k test_range`. 

We have a model PR that you can follow: https://github.com/pytorch/pytorch/pull/78408.
Please let me know if you have any questions.

**Comment by Shikharishere** [comment]
Thanks @DenisVieriu97, I am going to start applying the steps you proposed and If needed I will ask questions. Thanks once again..

**Comment by Shikharishere** [comment]
Hey, I just saw on Pytorch Documentation that this function will be discontinued in the future release.
Here -> [https://pytorch.org/docs/stable/generated/torch.range.html](url)

**Comment by DenisVieriu97** [comment]
Hi @Shikharishere. I think we'd still need this op since other networks might still use it and it hasn't been deprecated yet.  
@malfet, @albanD what do you think? Can this op be skipped?

**Comment by Shikharishere** [comment]
Yeah got it..

**Comment by Shikharishere** [comment]
Hi @DenisVieriu97 I am kinda struggling with adding the support for range_mps_out in Range_Factories.mm, like when I had a look at arrange_mps_out it didn't made any sense to me, can you please explain me? I would be great if you could....

**Comment by Shikharishere** [comment]
Hey, @DenisVieriu97 is this logic correct according to aten::range 
![image](https://user-images.githubusercontent.com/71226935/198580479-8365d319-4290-4c49-9f02-def8a188d29d.png)

**Comment by Shikharishere** [comment]
Also I did mention range_mps_out in native_functions.yaml file..

**Comment by Shikharishere** [comment]
and here's the test I wrote for range.
![image](https://user-images.githubusercontent.com/71226935/198586277-2bb71fe1-0965-4dcf-8aef-082c6e29a39e.png)

**Comment by Shikharishere** [comment]
It would be great if you reply faster. @DenisVieriu97

**Comment by Shikharishere** [comment]
@kulinseth can you have a look at this error. 
![image](https://user-images.githubusercontent.com/71226935/202807811-e1f7b96c-f06c-44fd-9534-f82a02ed283a.png)

**Comment by Shikharishere** [comment]
I got this error while testing the op for range function.

**Comment by Raman-Kumar** [comment]
@Shikharishere I think you are not using macOS, you need macOS for MPS development

**Comment by Raman-Kumar** [comment]
@Shikharishere I think you are not using macOS, you need macOS for the MPS running testing.

**Comment by Shikharishere** [comment]
Oh okay

**Comment by Shikharishere** [comment]
@DenisVieriu97 Unfortunately  I have to unassign this issue. Thanks for helping me out. @Raman-Kumar

**Comment by Shikharishere** [comment]
Hey, do you have some issues on Pytorch that I(i run windows) can do?

**Comment by Raman-Kumar** [comment]
@Shikharishere 
Look at this #88808

**Comment by Raman-Kumar** [comment]
@Shikharishere
try to do the suggested change at this issue  https://github.com/pytorch/pytorch/issues/88808

**Comment by Raman-Kumar** [comment]
@Shikharishere
try to do the suggested change at this issue https://github.com/pytorch/pytorch/issues/88808

**Comment by Raman-Kumar** [comment]
Ok, I am trying this issue
