### ISSUE TITLE
A typo about install command

### ISSUE THREAD

**Issue by pixeli99** [pytorch/pytorch#87035]
### 📚 The doc issue

`pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu113/torch_stable.html`
![image](https://user-images.githubusercontent.com/46072190/196025774-7545e771-8d68-487c-ac2a-c0086008864d.png)

Maybe we should change it to ``pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu111/torch_stable.html``?

`cu113 -> cu111`

cc @ezyang @seemethere @malfet @svekars @holly1238

**Comment by vadimkantorov** [comment]
@malfet are these old installation commands also tested with CI?

**Comment by kit1980** [comment]
Looks no longer relevant.
