### ISSUE TITLE
model.cpu()

### ISSUE THREAD

**Issue by wxthu** [pytorch/pytorch#87055]
### 🐛 Describe the bug

I  found that when I defined a DL model, I loaded it into GPU memory  to make inferences and then deleted it in place using API **_cpu()_**. Ideally, I expected that the model releasing time is close to zero and negligible. However, I  found the duration is so long ... The root cause is that torch is always to copy DL model back to CPU memory then release it , which is unreasonable I  think. Could you give some suggestions? 

### Versions

torch 1.8.1

**Comment by soumith** [comment]
if you want to delete a model, you should do `del model`, not do `model.cpu()`.

`model.cpu()` does exactly what it says, it moves the model to CPU.
