### ISSUE TITLE
ib/python3.9/site-packages/torch/include/ATen/core/interned_strings.h:345:1: error: expected unqualified-id FORALL_NS_SYMBOLS(DEFINE_SYMBOL) ^

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#87078]
### 🐛 Describe the bug

 import torch
torch.>>> torch.__version__
'1.13.0.dev20220924'

Somehow, old C++ code can built ,but no long with newest pytorch.

### Versions

 import torch
torch.>>> torch.__version__
'1.13.0.dev20220924'

**Comment by mikaylagawarecki** [comment]
Hi @jinfagang could you provide a minimal repro of the issue please, thanks!

**Comment by jinfagang** [comment]
@mikaylagawarecki Sorry, this is part of huge project, really hard to provide a repro.

However, the Got this issue becaused of in a C++ project I need include many torch c++ headers.

I didn't know from when include which file (the whole code can built before), got an error like this:


<img width="387" alt="image" src="https://user-images.githubusercontent.com/21303438/196324140-ebc7e137-34d8-4b2a-8f47-773befec3981.png">


as you can see, this is a syntax error, but the error comes from torch inside, I am really confused now, I have check all my codes many times, can't find any where missed.

**Comment by jinfagang** [comment]
solved it.
