### ISSUE TITLE
Jobs randomly fail with connection to the runner broken

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#87134]
### 🐛 Describe the bug

This manifests itself in two forms:

Form 1:
```
self-hosted runner: i-077b065c12b641163 lost communication with the server. Verify the machine is running and has a healthy network connection., wondering if anyone has any ideas?
```

Form 2 (not 100% certain that it's the same cause as Form 1, but it has a similar effect):
```
The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
```

Example:
https://github.com/pytorch/pytorch/actions/runs/3268090253/attempts/1
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4468967/196285896-a3946ff4-c213-4305-ab5e-24e9846f6a12.png">

As per @clee2000: "https://github.com/pytorch/test-infra/pull/864 seems like it could be related and was merged right before we started noticing it but theres a check to see if the runner is busy, could it be possible that theres a race and github grabs the runner right before it gets terminated?  seems unlikely tho since it happens pretty often"

### Versions

n/a

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by izaitsevfb** [comment]
I think Zain is right, this is related to our scale-down job.

For the second issue (form2) I found a matching log record in AWS cloudwatch:
```
2022-10-17T19:45:56.678Z	b0436495-b5d6-42fd-8365-88653ad62b15	WARN	Error scaling down (removeGithubRunnerOrg) 'i-067c81baf903eb307' [linux.4xlarge]: HttpError: Bad request - Runner "i-067c81baf903eb307" is still running a job"
```
(logstream: /aws/lambda/gh-ci-scale-down 2022/10/17/[$LATEST]157b1b9cd1cf4f82b90df969c0c5eaef)

**Comment by izaitsevfb** [comment]
For the record, @malfet rolled back recent terraform config changes, see:
https://github.com/fairinternal/pytorch-gha-infra/actions/runs/3269387623

cc @jeanschmidt @DanilBaibak 

see also pytorch/test-infra#901

**Comment by jeanschmidt** [comment]
Hi, thanks for identifying and reporting the issue. We reverted the offending changes and will be rolling out the fixes [in the test-infra PR](https://github.com/pytorch/test-infra/pull/904)

**Comment by jeanschmidt** [comment]
Fix is pushed and rolled out.
