### ISSUE TITLE
Conda ChecksumMismatchError error blocking CI jobs

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#87148]
## Current Status
Mitigated

## Error looks like

Conda installation of blas fails reportedly on Mac (x86-64 and arm) and Linux:

```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-arm64/blas-1.0-openblas.conda'.
  download saved to: /Users/ec2-user/runner/_work/_temp/conda_environment_3268900421/pkgs/blas-1.0-openblas.conda
  expected sha256: 4fd46cbbcfd8eea36f4b5eee916c0b973d3e9cf19931b1e046930fa087798752
  actual sha256: 7216b4a8256774e24c1a9754f162ea86fa8202643afb4effe6f8694da4423ed7
```

```
pyyaml-5.3.1         | 168 KB    | ########## | 100% 
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-openblas.conda'.
  download saved to: /Users/runner/work/_temp/conda_environment_3268900421/pkgs/blas-1.0-openblas.conda
  expected sha256: 7eea712a7368df985f977414e8f5d430d1dc110df4769d39ba6622d445137491
  actual sha256: df6aa4b828af1baedcde4f53b40b857bf23f19ff806bb20f0459543c5e6954ea
```

```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-openblas.conda'.
  download saved to: /home/runner/conda_pkgs_dir/blas-1.0-openblas.conda
  expected sha256: c85b5d0a336b5be0f415c71fd7fe2eca59e09f42221bfa684aafef5510ba5487
  actual sha256: 5dc5483db0d9785b19e021cee418a8ee03e0ff0e5ebd0b75af4927746604e187
```

Also failing on Circle CI as @clee2000 points out https://app.circleci.com/pipelines/github/pytorch/pytorch/584316/workflows/07d73f69-13c6-4560-8185-3c78247e5fc3/jobs/17180548

## Incident timeline (all times pacific)
* Oct 17th, first failing job on trunk https://hud.pytorch.org/pytorch/pytorch/commit/5acf6e0e80fb3c029fe62ff665bc5279ec00a70c

</details>

## User impact
Build and test jobs fails when conda tries to install blas

## Root cause
Potential Conda CDN upstream issue

## Mitigation
Switch temporarily to conda-forge

## Prevention/followups
TBD

**Comment by kit1980** [comment]
t looks like the issue is for every Github runner. Maybe something wrong between Github network and Conda CDN.

**Comment by huydhn** [comment]
This looks similar to https://github.com/pytorch/pytorch/issues/63006, let me check if this works locally (without GitHub network)

**Comment by huydhn** [comment]
The failed command `conda install -y numpy=1.22.3 pyyaml=6.0 setuptools=61.2.0 cmake=3.22.1 cffi ninja typing_extensions dataclasses pip` works locally for me so it's very likely that there is indeed something wrong between Github network and Conda CDN

**Comment by kit1980** [comment]
Our own M1 runner also got the same issue https://github.com/pytorch/pytorch/actions/runs/3268674002/jobs/5375694468
So the Github network theory is not correct.
Our own runners just cache the dependencies, so it takes longer to see the issue (pointed by @malfet )

**Comment by huydhn** [comment]
Yeah, so one option left to us is to cut a ticket to conda maintainers now.  Stay tuned

**Comment by huydhn** [comment]
https://github.com/Anaconda-Platform/anaconda-client/issues/622

**Comment by clee2000** [comment]
circleci jobs are also failing with same error, so definitely not just githubs network
https://app.circleci.com/pipelines/github/pytorch/pytorch/584316/workflows/07d73f69-13c6-4560-8185-3c78247e5fc3/jobs/17180548

**Comment by huydhn** [comment]
Mitigated: https://github.com/pytorch/pytorch/pull/87150 and https://github.com/pytorch/pytorch/pull/87155 have been merged to switch to conda-forge temporarily

**Comment by ZainRizvi** [comment]
Update: Either a iOS affecting segfault got merged in before the mitigation went in, or the binaries we're now getting from conda-forge are triggering a segfault.

**Comment by huydhn** [comment]
The CDN issue has been resolved upstream https://github.com/conda/conda/issues/11991#issuecomment-1282647229, running the check now before reverting the conda-forge change

**Comment by huydhn** [comment]
https://github.com/pytorch/pytorch/actions/runs/3271757229/jobs/5390403045 confirms that conda is working now, I will start the revert process now

**Comment by huydhn** [comment]
Both PRs have been reverted. We can close this one now
