### ISSUE TITLE
DISABLED test_expanded_reduction_cpu (__main__.CpuTests)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#87157]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_expanded_reduction_cpu%2CCpuTests)).

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @jansel @lezcano @fdrocha @mlazos @soumith @yanboliang

**Comment by malfet** [comment]
It started to happen as soon as dynamo ci was enabled, see https://hud.pytorch.org/pytorch/pytorch/commit/a0c2a7f2eda788a48f1d243940297f1467faf138

**Comment by leslie-fang-intel** [comment]
@zhuhaozhe please help to past the link of PR for this.

**Comment by zhuhaozhe** [comment]
https://github.com/pytorch/pytorch/pull/115620

**Comment by zhuhaozhe** [comment]
Enabled by https://github.com/pytorch/pytorch/pull/122289
