### ISSUE TITLE
Warning and breaking changes around ReduceOP in 1.13

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#87191]
### 🐛 Describe the bug

In a REPL environment, the following emits a deprecation warning:

```python
import torch.distributed.ReduceOp<TAB>
/home/carmocca/git/py310/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py:251: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
```

edit: the above seems to be only a problem in a REPL. I guess because it tries to catch `__getattribute__` values for suggestions.

---

There's been a breaking change with the introduction of `RedOpType`, as isinstance checks no longer work as expected
```python
torch.distributed.ReduceOp.SUM
<RedOpType.SUM: 0>
isinstance(torch.distributed.ReduceOp.SUM, torch.distributed.ReduceOp)
False
```
I'm unfamiliar with the specifics of the newly introduced `RedOpType`, but I suggest backwards compatibility (and deprecation messages, if considered useful) are added to still support these checks.

I would appreciate if you could share links that include motivation for the introduction of `RedOpType`

### Versions

PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Pop!_OS 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-76051900-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.5.119
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: Quadro RTX 5000 with Max-Q Design
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.3.0a0+325dcc2
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] pytorch-lightning==1.8.0.dev0
[pip3] torch==1.13.0+cu116
[pip3] torchdynamo==1.13.0.dev0
[pip3] torcheval==0.0.4
[pip3] torchmetrics==0.9.3
[pip3] torchtnt==0.0.2
[pip3] torchvision==0.14.0+cu116
[conda] Could not collect

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by carmocca** [comment]
cc @crcrpar as the author of #84243 which I think caused the `isinstance` issue

**Comment by mrshenli** [comment]
cc @kwen2501

**Comment by crcrpar** [comment]
> I'm unfamiliar with the specifics of the newly introduced `RedOpType`, but I suggest backwards compatibility (and deprecation messages, if considered useful) are added to still support these checks.
> 
> I would appreciate if you could share links that include motivation for the introduction of `RedOpType`

The motivation of `RedOpType` is to experimentally support NCCL's premul sum https://docs.nvidia.com/deeplearning/nccl/archives/nccl_21212/user-guide/docs/api/ops.html which takes some scaling values from users.

**Comment by kwen2501** [comment]
Hi @carmocca thanks for reporting this. 
Strictly speaking, per our [documentation](https://pytorch.org/docs/stable/distributed.html), it seems that we only guarantee a couple of things:
1. There is a class called `torch.distributed.ReduceOp`;
2. This class has attributes like `SUM`, `AVG`, `MIN`, etc, i.e. one can access an attribute in form of `ReduceOp.SUM`;
3. One can pass these attributes to the `all_reduce`, `reduce` or `reduce_scatter` call, and it will work.

In @crcrpar 's PR, the above three criteria are maintained (because of a compat layer @crcrpar built).

What we haven't guaranteed in the documentation is that `ReduceOp.SUM` is of type `ReduceOp`. And that's something we missed in the PR.

Now I understand the awkwardness this change caused to your code. In part, it seems to me that it also has to do with how the wrapper version of the all_reduce API is defined in your code:

**Comment by carmocca** [comment]
Thanks for your respose. I guess you could also try overriding `__isinstancecheck__` to support `RedOpType`s.

For my understanding, since `ReduceOp` now always returns a `RedOpType`, what is the benefit of the former? Is it only kept for backwards compatibility?

**Comment by kwen2501** [comment]
`ReduceOp` can carry more information than `RedOpType`. For example, for NCCL's PreMulSum op, `ReduceOp` can carry a scalar, which scales the inputs before they are summed up.

**Comment by atalman** [comment]
Closing this issue since cherry-pick posted
