### ISSUE TITLE
Flexible state dict loading for model (or optimizer)

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#872]
Currently, the state dict to load should have exactly the same elements as the state dict of model. However, for some warm start cases, it could be useful if it's allowed to load partially from the pretrained model.

Do you think there should be a flag control if the rule is strict or not?

**Comment by colesbury** [comment]
If you have partial state_dict, which is missing some keys you can do the following:

```python
state = model.state_dict()
state.update(partial)
model.load_state_dict(state)
```

**Comment by ruotianluo** [comment]
Thanks!

**Comment by IssamLaradji** [comment]
what if the state_dict has more keys than the model's ?

**Comment by apaszke** [comment]
```python
loaded_dict = {k: loaded_dict[k] for k, _ in model.state_dict()}
```

**Comment by XavierCHEN34** [comment]
what if i changed the names of some begin layers and removed the last several fc layers?
use" load_state_dict( ) with strict = False"  will this load those begin layers in order?

**Comment by apaszke** [comment]
It won't. We can't automagically figure out the correspondence between parameters if the names don't match

**Comment by XavierCHEN34** [comment]
so if i changed some layer names  or for example i want to split the sequential in pretrained VGG and load the pretrained parameters, what shoud i do?
in version 0.2 i cant assign the value of state_dict according to index if the order of layer isnt change.
but in version0.3 you use odict which cant be assigned as before...

**Comment by apaszke** [comment]
You can manually patch the state dict by updating the parameters names in the way you changed the network structure

**Comment by XavierCHEN34** [comment]
fine, thank you for your quick response

**Comment by XavierCHEN34** [comment]
i failed...could you give some hint for  updating the parameters names?

**Comment by rchavezj** [comment]
@apaszke so how's 1.0 going along? ;)

**Comment by shivangbaveja** [comment]
I have a peculiar problem. I have saved the state of the model but now I have changed the last linear layer. I want to use the weights from the saved state for all layers except the last layer which has different dimensions.

**Comment by kaltu** [comment]
I trained two part of a group of networks on two machines with different pytorch version.
And when I tries to merge the result, one is complaining missing keys `model.1.blah` another is complaining unexpected keys `model1.blah`
It is annoying that `.` in the model name is removed and no simple backward compatibility solution is available.
