### ISSUE TITLE
[MPS] Add support for aten::repeat_interleave for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#87219]
### 🐛 Describe the bug

First time contributors are welcome!
Add support for [aten::repeat_interleave](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by rishub-tamirisa** [comment]
@DenisVieriu97 Hello! I'm interested on working on this issue.

**Comment by moDallel** [comment]
Hello !
we are a group of students in second year in engineering school. We are currently interested in resolving this issue as a school project. Please let me know, if we can have your permision to start contributing.

**Comment by mommi84** [comment]
Needed to run [GPT-J-6B](https://huggingface.co/EleutherAI/gpt-j-6B) on MPS.

**Comment by tvercaut** [comment]
I stumbled onto the following limitation with respect to int64 support:
```
UserWarning: MPS: no support for int64 repeats mask, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Repeat.mm:236.
```

Current workaround for me:
```python
out = torch.repeat_interleave(in).to(dtype=in.dtype)
```

Obviously  this would be problementatic with integers larger than 32 bits.
