### ISSUE TITLE
[MPS] Add support for aten::trace for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#87221]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::trace](https://pytorch.org/docs/stable/generated/torch.trace.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by mory91** [comment]
Hi,
I would be happy to work on this, I use PyTorch on M1 from time to time so making it better would make my days better too 👯 
Since I'm new to the codebase, could you please give me some advice?

**Comment by DenisVieriu97** [comment]
Hi @mory91 - thank you for the interest in this op!

As a starting point, you can start in the following order:

1. Check out the official spec for aten::trace (https://pytorch.org/docs/stable/generated/torch.trace.html).
2. Register the op in [native_functions.yaml](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L7760): here you'll have to add a key similar as the CPU and CUDA ones (e.g MPS: `trace_mps`).
3. In [ReduceOps.mm](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/ReduceOps.mm) add support for `trace_mps`:
```
Tensor trace_mps(const Tensor& self) {
// ..

}
``` 
As a reference for this, you can use Eye.mm PR: https://github.com/pytorch/pytorch/pull/78408.
4. To select the diagonal of a tensor, you can use [bandPartWithTensor](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3925426-bandpartwithtensor?changes=_1&language=objc) op. E.g:
```

    MPSGraphTensor *bandPartWithTensor = [graph bandPartWithTensor:inputTensor
                                                          numLower:0
                                                          numUpper:0
                                                             name:nil];
```
- After selecting the diagonal, to do a sum of the elements you can use [reductionSumWithTensor](https://developer.apple.com/documentation/metalperformanceshadersgraph/mpsgraph/3580494-reductionsumwithtensor?changes=_1&language=objc), as following:
```
    MPSGraphTensor *outputTensor = [graph reductionSumWithTensor:bandPartWithTensor 
                                                            axes:@[@0, @1]
                                                            name:nil];
```



5. After implementing the op, please add a small test case in [test_mps.py](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L291) to check for the correctness of the op. You can take as example [test_bmm](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L305) - do `trace` once on a CPU tensor, once on a MPS tensor, then check that the results match with `self.assertEqual(cpu_tensor, mps_tensor)`. 
 

Please let me know if you have any questions.

**Comment by JudeDavis1** [comment]
Hello, any updates on this issue? Does this still need implementing?

**Comment by DenisVieriu97** [comment]
this was closed in https://github.com/pytorch/pytorch/pull/87910
