### ISSUE TITLE
[MPS] Add support for aten::median for MPS backend

### ISSUE THREAD

**Issue by DenisVieriu97** [pytorch/pytorch#87220]
### 🐛 Describe the bug

First time contributors are welcome! 🙂
Add support for [aten::median](https://pytorch.org/docs/stable/generated/torch.median.html) for MPS backend. Generic support for adding operations to MPS backend is captured here: https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend

### Versions

N/A

cc @kulinseth @albanD @malfet @razarmehr @abhudev

**Comment by Raman-Kumar** [comment]
@DenisVieriu97 
I want to take and work on this issue.

**Comment by Raman-Kumar** [comment]
I sent a PR for torch.median(input_tensor). test passed
[](https://github.com/pytorch/pytorch/pull/88554)



Now I am testing median with dim value

For that I used  sortWithTensor and argSortWithTensor from MPSGraph

But it will only work on macOS Ventura
Do you have any suggestions for this supporting the older versions?

**Comment by Raman-Kumar** [comment]
I sent a Pull request for torch.median(input_tensor). test passed
[pytorch/pull/88554](https://github.com/pytorch/pytorch/pull/88554) 


Now I am testing median with dim value
For that I used sortWithTensor and argSortWithTensor from MPSGraph

But it will only work on macOS Ventura
Do you have any suggestions for this supporting the older versions?

**Comment by Raman-Kumar** [comment]
checking macOS like this [PR](https://github.com/pytorch/pytorch/pull/88319/files#diff-9b23535bcb52b7ec6b73bb2b078239abcd6a55a7d238851efffa09024c81db51R11) 

I need a small help in 
the implementation function **signature** of 
`torch.median(input, dim=- 1, keepdim=False, *, out=None)`

Successfully added median_mps of entire tensor and its implementation function 

Now trying to add median op with dim 
I added Here ` MPS: median_out_mps `
https://github.com/pytorch/pytorch/blob/97be8dab612b4fbb63f0622b6ce513b64e8f3010/aten/src/ATen/native/native_functions.yaml#L3500-L3505

and gave function signature like below  replacing my median op name 
https://github.com/pytorch/pytorch/blob/7382c88df2889bf58ef62fe52ed3e1361e384811/aten/src/ATen/native/mps/operations/ReduceOps.mm#L1374-L1386

But this gives error while building 
```
../aten/src/ATen/native/mps/operations/ReduceOps.mm:1392:1: error: use of undeclared identifier 'structured_median_out_mps'; did you mean 'structured_mean_out_mps'?
TORCH_IMPL_FUNC(median_out_mps)
^
../aten/src/ATen/TensorMeta.h:63:36: note: expanded from macro 'TORCH_IMPL_FUNC'
#define TORCH_IMPL_FUNC(name) void structured_##name::impl
                                   ^
<scratch space>:17:1: note: expanded from here
structured_median_out_mps
^
aten/src/ATen/ops/mean_native.h:23:18: note: 'structured_mean_out_mps' declared here
struct TORCH_API structured_mean_out_mps : public at::meta::structured_mean_dim {
                 ^
../aten/src/ATen/native/mps/operations/ReduceOps.mm:1392:1: error: out-of-line definition of 'impl' does not match any declaration in 'at::native::structured_mean_out_mps'
TORCH_IMPL_FUNC(median_out_mps)
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../aten/src/ATen/TensorMeta.h:63:55: note: expanded from macro 'TORCH_IMPL_FUNC'
#define TORCH_IMPL_FUNC(name) void structured_##name::impl
```

What should be median_out_mps with dim function signature 
and Where it should be placed in `/native_functions.yaml`?

**Comment by Raman-Kumar** [comment]
This function signature is working
```
TORCH_API ::std::tuple<at::Tensor &,at::Tensor &> median_out_mps
(const at::Tensor & self,
 int64_t dim,
bool keepdim, 
at::Tensor & values, 
at::Tensor & indices){

  return std::tuple<Tensor&, Tensor&>(values, indices);
}
```
Going ahead with this.
