### ISSUE TITLE
pypi in no torchaudio with torch1.1.0 match

### ISSUE THREAD

**Issue by S-O294** [pytorch/pytorch#87265]
Description: The torchaudio0.2 file is available on the Pytorch website, but not in pypi.
Impact: This makes it impossible to install torchaudio0.2 with the pip command. because torch1.1.0 is used in conjunction with torchaudio0.2.0, which makes torch1.1.0 unusable.
<img width="328" alt="图片1" src="https://user-images.githubusercontent.com/60139005/196588514-09784f41-16a9-4016-ab53-a2660396214f.png">
<img width="326" alt="图片2" src="https://user-images.githubusercontent.com/60139005/196588533-d5017d1f-5a11-41b0-9065-9054618509e2.png">

cc @ezyang @seemethere @malfet

**Comment by ezyang** [comment]
these versions are ancient, we're unlikely to fix it

**Comment by S-O294** [comment]
@ezyang We are conducting compatibility testing on deep learning frameworks, thank you very much for your response.
