### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/***/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#87279]
### 🐛 Describe the bug

`import torch` triggered this error.

### Versions

PyTorch version: 1.12.1.post200
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (conda-forge gcc 10.3.0-16) 10.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:28:35) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-128-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] colossalai==0.1.6+torch1.11cu11.3
[pip3] numpy==1.22.3
[pip3] pytorch-pfn-extras==0.5.8
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.1.post200
[pip3] torch-optimizer==0.1.0
[pip3] torchaudio==0.12.1
[pip3] torchinfo==1.6.5
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.13.1
[conda] colossalai                0.1.6+torch1.11cu11.3          pypi_0    pypi
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] magma                     2.5.4                h6103c52_2    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] pytorch                   1.12.1          cuda112py310h51fe464_200    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-pfn-extras        0.5.8                    pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.1.0                    pypi_0    pypi
[conda] torchaudio                0.12.1              py310_cu116    pytorch
[conda] torchinfo                 1.6.5              pyhd8ed1ab_0    conda-forge
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.13.1              py310_cu116    pytorch

**Comment by puyuanOT** [comment]
how did you solve this error?

**Comment by songyuc** [comment]
> how did you solve this error?

Just use a new python env and install PyTorch from scratch.

**Comment by puyuanOT** [comment]
Thanks a lot!

songyuc ***@***.***> 于 2023年5月25日周四 23:28写道：

**Comment by shink** [comment]
I installedpytorch from source, and had a same errror:

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/pytorch/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: /root/anaconda3/envs/ai/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/pytorch/torch/lib/libtorch_python.so)
```

fixed by:

```shell
ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6
```
