### ISSUE TITLE
Deterministic indexing operation fails in indices size check / missing broadcast (CUDA Tensor broadcasting)

### ISSUE THREAD

**Issue by HANDSOMEJACKANDY** [pytorch/pytorch#87287]
### 🐛 Describe the bug

This is a related bug to issue #61032. However, the problem I am facing is when trying to broadcast a tensor (instead of scalar) to the masked Tensor.

The following is a short code snippet that can reproduce the bug:
```python
import torch

torch.use_deterministic_algorithms(True)

a = torch.zeros(1, 10, 16).cuda()
mask = torch.ones(1, 10, dtype=torch.bool).cuda()
b = torch.zeros(16).cuda()
a[mask] = b
```
The bug reported is as follows
```python
RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == expandedValue.numel() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1659484808560/work/aten/src/ATen/native/cuda/Indexing.cu":324, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor: 160 vs 16
```
Not that the bug would go away if b is a scalar, or when use_deterministic_algorithms is set to false.

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] pytorch-lightning==1.7.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.1
[pip3] torch-optimizer==0.3.0
[pip3] torch-stoi==0.1.2
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.12.1
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch                   1.12.1          py3.10_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-lightning         1.7.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torch-stoi                0.1.2                    pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchaudio                0.12.1              py310_cu113    pytorch
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchvision               0.13.1              py310_cu113    pytorch

**Comment by ngimel** [comment]
Closing in favor of #79987
