### ISSUE TITLE
nccl build: nvcc fatal   : redefinition of keyword 'code' 

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8729]
Steps to reproduce:
1. Get a CI CUDA docker image, e.g., `30853
5385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda9-cudnn7-py3:218`
2. Clone PyTorch, and run `python setup.py build_deps develop`

Expected result: It works

Actual result:
```
CMake Warning at /var/lib/jenkins/pytorch-1/cmake/public/utils.cmake:148 (message):
  In the future we will require one to explicitly pass TORCH_CUDA_ARCH_LIST
  to cmake instead of implicitly setting it as an env variable.  This will
  become a FATAL_ERROR in future version of pytorch.
Call Stack (most recent call first):
  CMakeLists.txt:9 (torch_cuda_get_nvcc_gencode_flag)


INFOSet NVCC_GENCODE for building NCCL: -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52
-- Configuring done
-- Generating done
-- Build files have been written to: /var/lib/jenkins/pytorch-1/third_party/build/nccl
+ make install
Scanning dependencies of target nccl
[100%] Generating lib/libnccl.so
Grabbing  src/nccl.h                          > /var/lib/jenkins/pytorch-1/third_party/build/nccl/include/nccl.h
Compiling src/libwrap.cu                      > /var/lib/jenkins/pytorch-1/third_party/build/nccl/obj/libwrap.o
Compiling src/core.cu                         > /var/lib/jenkins/pytorch-1/third_party/build/nccl/obj/core.o
nvcc fatal   : redefinition of keyword 'code' 
Makefile:136: recipe for target '/var/lib/jenkins/pytorch-1/third_party/build/nccl/obj/libwrap.o' failed
make[3]: *** [/var/lib/jenkins/pytorch-1/third_party/build/nccl/obj/libwrap.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

Workaround: set `TORCH_CUDA_ARCH_LIST=5.2` forces only one `-gencode` to be passed.

**Comment by ezyang** [comment]
CC @SsnL; is this the nccl+sccache problem you were seeing?

**Comment by SsnL** [comment]
cc @yf225 has the exact error. CI log doesn't actually post the error.

**Comment by yf225** [comment]
sccache probably doesn't allow passing multiple `-gencode` right now, I can look into it if needed.

**Comment by justinchiu** [comment]
Seeing this exact error when building for arches 5.2 6.1 and 7.0 (on centos 7.1, gcc 7.1, cuda 9.2), is there a workaround that doesn't only emit code for a single arch (and without changing gcc versions)?

**Comment by Corbin-A** [comment]
I am having this same error. How can you figure out which gencode to pass? I'm trying to build from source from a Dockerfile as well, as seen in this gist:

https://gist.github.com/Corbin-A/5061afd686973a6db5517f88b18acd13

**Comment by soumith** [comment]
@Corbin-A this is super helpful, thanks.

**Comment by Corbin-A** [comment]
@soumith just wanted to make sure you saw that this is pulling from a ppc64le (IBM Power system) docker image, so you'll run into different issues if trying to build on an x64 machine.

**Comment by soumith** [comment]
I modified it very slightly for x64: https://gist.github.com/84818f986db91428b73c78a5a70c3b6d

It seems to build pytorch successfully for me (on latest master I suppose).

**Comment by SsnL** [comment]
looking into this
