### ISSUE TITLE
[Quant] There is no default_qconfig_mapping for dynamic quantization

### ISSUE THREAD

**Issue by andrewor14** [pytorch/pytorch#87298]
https://github.com/pytorch/pytorch/blob/86a581928a4f5065a79771a7a2d87c6999c452e9/torch/ao/quantization/qconfig_mapping.py#L65

`get_default_qconfig_mapping` today only uses static qconfigs. Users who wish to use dynamic qconfigs will have to do something like the following (similar to https://github.com/pytorch/pytorch/pull/87002):

```
qconfig_mapping = get_default_qconfig_mapping().set_global(default_dynamic_qconfig)
for pattern in qconfig_mapping.object_type_qconfigs.keys():
    if pattern not in _FIXED_QPARAMS_OP_TO_OBSERVER:
        qconfig_mapping.set_object_type(pattern, default_dynamic_qconfig)
```

Maybe we should have `get_default_qconfig_mapping` accept a `default_qconfig` argument.

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by jerryzh168** [comment]
I feel this is low pri now since we are moving to pytorch 2.0 export quantization

**Comment by andrewor14** [comment]
Actually I'm closing this since there's now a way for users to express this using this helper function: https://github.com/pytorch/pytorch/blob/c435b8c10a1b9652a35e1a87cee6c3942356660d/torch/ao/quantization/qconfig_mapping.py#L156
