### ISSUE TITLE
[ONNX] test_caffe2_aten_fallback raises RuntimeError

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#87318]
### 🐛 Describe the bug

It's moved to test/onnx/test_export_modes.py after #87292. The test was skipped under test_jit.py as it's not Caffe2 build. Now under test/onnx, it's failed with Caffe2 build.

Error message
```
RuntimeError: ScalarType UNKNOWN_SCALAR is an unexpected tensor scalar type
```

### Versions

Nightly

**Comment by thiagocrepaldi** [comment]
Closing as Caffe2 ONNX exporter is being deprecated for PyTorch 2.0
https://github.com/pytorch/pytorch/pull/94994
