### ISSUE TITLE
Unexpected segmentation fault encountered in worker when using Pytorch Geometric to load dataset

### ISSUE THREAD

**Issue by sunhongmin225** [pytorch/pytorch#87336]
### 🐛 Describe the bug

I encounter the following error when using DataLoader workers to load data.
I am using [NeighborSampler in PyG](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/loader/neighbor_sampler.py) as "loader" in run_main.py line 152 to load custom dataset, and use `num_workers` of `os.cpu_count()`.

```
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1134, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1096707) is killed by signal: Segmentation fault.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_main.py", line 152, in train
    for step, _ in enumerate(loader):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1330, in _next_data
    idx, data = self._get_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1296, in _get_data
    success, data = self._try_get_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1147, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1096707) exited unexpectedly
```

I've searched a lot for this error, and found following solutions. However, they were all unhelpful.
- Using `num_workers` of 0 or 1. When I run with `num_workers` of 0, it results in "corrupted double-linked list" error. When I set `num_workers` as 1, the same error (Unexpected segmentation fault encountered in worker) still occurs. Actually, I don't want to lessen `num_workers`, because I am working on a pretty large dataset and lessening `num_workers` is a much slower option.
- Increasing shared memory size. I've done this by adding `none /dev/shm tmpfs defaults,size=MY_SIZEG 0 0` line in `/etc/fstab` and running `mount -o remount /dev/shm`. I've set MY_SIZE exactly as the size of main memory (which was previously 50% of main memory).
- Changing Python version to <= 3.6.9. I've tried this, but the same error still occurs.
- Checking that Python and dataset are mounted on the same disk. I've already verified that they are mounted on the same disk.

I've been struggling to fix this issue for several days, but I can't find the right solution, and it really makes me frustrated. Could you please help me out?

### Versions

```
user@desktop:~/work$ python3 collect_env.py
Collecting environment information...
PyTorch version: 1.12.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA TITAN Xp
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.12.0+cu116
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.14
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.12.0+cu116
[pip3] torchvision==0.13.0+cu116
[conda] Could not collect
```

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
It's apparently something wrong with `corrupted double-linked list`.  You need to check your dataset code using `num_workers=0`

**Comment by sunhongmin225** [comment]
I will check for it and try to share the results ASAP.

**Comment by sunhongmin225** [comment]
I've figured this out. I was using a customized, synthesized dataset expanded from an existing dataset. I've re-synthesized the dataset and the error disappeared when applied on this new dataset. I'm not sure why, but it seems that the previous dataset was corrupted in some way. Thanks for your advice.
