### ISSUE TITLE
[RPC][BE][Easy] Custom python UDF should catch BaseExceptions

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#87333]
### 🚀 The feature, motivation and pitch

Resolve the TODO in https://github.com/pytorch/pytorch/pull/87224/files#diff-e0abc0cc354cebd2f96a1165396c5a55f882b824c86c109a4ef54f536f1e32feR208. We should catch BaseException instead of Exception because BaseException is the pythonic way users should inherit from to define custom exceptions. This is technically BC breaking, but very minor. 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @pietern @jjlilley @mrzzd

**Comment by stefanodefeo** [comment]
Hello, @rohan-varma I'm interested on working on this issue for my first contribution.

**Comment by jazzysoggy** [comment]
Made a pull request, though I'm not quite sure if there's anything more to it than just replacing Exception with BaseException.

**Comment by balasrinivas41** [comment]
Could any one guide me,How to start open source contribution. Any recommendations

**Comment by xboluna** [comment]
https://github.com/pytorch/pytorch/pull/89540
This issue should be closed.
@kit1980 @rohan-varma
