### ISSUE TITLE
[caffe2] how to specify cudnn install directory

### ISSUE THREAD

**Issue by twmht** [pytorch/pytorch#8734]
I am trying to install caffe2.

But my cudnn is located at /opt/cudnn

how to specify this location when running cmake?

**Comment by pjh5** [comment]
Where is your cuda installation?

I think it'd be easiest for you if you hardcoded all the CuDNN-related files here https://github.com/pytorch/pytorch/blob/master/cmake/public/cuda.cmake#L63

**Comment by twmht** [comment]
@pjh5 

ok.
