### ISSUE TITLE
`torch.clamp` gives wrong values for transposed inputs on MPS

### ISSUE THREAD

**Issue by aslvrstn** [pytorch/pytorch#87348]
### 🐛 Describe the bug

```
import numpy
import torch

torch.manual_seed(2)

shape = (2, 2)

in_ = torch.randn(shape).to('mps')
min_ = torch.randn(shape).T.to('mps')
max_ = torch.randn(shape).T.to('mps')

torched = torch.clamp(in_, min_, max_)
numpyd = numpy.clip(in_.cpu().numpy(), min_.cpu().numpy(), max_.cpu().numpy())

print("INPUTS")
print(in_)
print(min_)
print(max_)

print("OUT")
print("torch:")
print(torched.cpu().numpy())
print("numpy:")
print(numpyd)
```

Gives

```
tensor([[ 0.3923, -0.2236],
        [-0.3195, -1.2050]], device='mps:0')
tensor([[ 1.0445, -0.6332],
        [ 0.5731,  0.5409]], device='mps:0')
tensor([[-0.3919, -1.0427],
        [ 1.3186,  0.7476]], device='mps:0')
OUT
torch:
[[-0.39190584 -1.0426788 ]
 [ 1.3186173   0.747639  ]]
numpy:
[[-0.39190584 -1.0426788 ]
 [ 0.57310677  0.54094744]]
 ```
 
 This does not reproduce if the tensor isn't sent to the MPS backend, or if the matrices are not transposed
 
 Found via https://github.com/pytorch/pytorch/pull/87342

### Versions

(pytorchdev) alex@Alexs-MacBook-Pro-2 pytorch % python torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 1.14.0a0+git9ceadca
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.201)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.4 (main, Mar 31 2022, 03:37:37) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.14.0a0+git70c881b
[pip3] torchvision==0.13.1
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] numpy-base                1.23.1          py310h742c864_0
[conda] torch                     1.14.0a0+git70c881b           dev_0    <develop>
[conda] torchvision               0.13.1                   pypi_0    pyp

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by aslvrstn** [comment]
```
--- a/aten/src/ATen/native/mps/operations/TensorCompare.mm
+++ b/aten/src/ATen/native/mps/operations/TensorCompare.mm
@@ -122,9 +122,15 @@ void clamp_tensor_out_mps(const Tensor& input_t,

     if(has_min) {
         min_opt_tensor = (num_min_dims < num_input_dims) ? (*min_opt).view(new_min_shape) : *min_opt;
+        if (!min_opt_tensor.is_contiguous()) {
+            min_opt_tensor = min_opt_tensor.contiguous();
+        }
     }
     if(has_max) {
         max_opt_tensor = (num_max_dims < num_input_dims) ? (*max_opt).view(new_max_shape) : *max_opt;
+        if (!max_opt_tensor.is_contiguous()) {
+            max_opt_tensor = max_opt_tensor.contiguous();
+        }
     }
```

seems to fix this issue, so I think that confirms the underlying cause. I suspect there's a better approach than having to force contiguousness, but for that I either need a while longer, or someone who speaks MPS

**Comment by aslvrstn** [comment]
Nevermind, I don't have a quick fix for this. The above doesn't actually fix, it just transmutes the error into something else.

This is complicated by the fact that the current implementation doesn't support (even buggily), a clamp with a larger min or max tensor than the input, an admittedly weird thing to do, but supported by CPU clamp and tested by `reference_inputs_elementwise_ternary` in `common_methods_invocations.py`, e.g.

```
>>> torch.clamp(torch.Tensor([3,2]), torch.Tensor([[3.5, 1], [1, 4]]), torch.Tensor([4, 3]))
tensor([[3.5000, 2.0000],
        [3.0000, 3.0000]])
```

This is somewhat consistent with the bug in https://github.com/pytorch/pytorch/issues/86239 where it seems like the MPS implementations don't have a common, consistent way of handling some of the weirder broadcasting that CPU/CUDA does. I'm looking at things like the implementation of `where` doing its own broadcasting in https://github.com/pytorch/pytorch/commit/5c07c2658216cf94a47c57ae5cabfa8aac165a13 and then `clamp` having its own checks in https://github.com/pytorch/pytorch/blob/ca69ddb4f7b1e1449756177889c454edb8bc091f/aten/src/ATen/native/mps/operations/TensorCompare.mm#L52 (which are overly tight! that's the check that discards the above shaped tensors)

@kulinseth I found https://github.com/pytorch/pytorch/wiki/MPS-Backend, but do you have any more docs or thoughts on how one might unify broadcast handling here?

**Comment by SamsTheGreatest** [comment]
Could be related. MPS backend gives wrong result when clamping `clamped = original.clamp(*minmax_ranges.to(original.device,torch.float))`.
```python
CPU:
minmax_ranges tensor[2, 784] n=1568 (6.1Kb) x∈[-1.156, 2.550e+04] μ=65.961 σ=764.947
original tensor[1024, 784] n=802816 (3.1Mb) x∈[-0.170, 0.168] μ=0.001 σ=0.031 grad SplitWithSizesBackward0
clamped tensor[1024, 784] n=802816 (3.1Mb) x∈[-0.170, 0.168] μ=0.003 σ=0.030 grad ClampBackward0

MPS:
minmax_ranges tensor[2, 784] n=1568 (6.1Kb) x∈[-1.156, 2.550e+04] μ=65.961 σ=764.947 mps:0
original tensor[1024, 784] n=802816 (3.1Mb) x∈[-0.156, 0.154] μ=0.001 σ=0.031 grad SplitWithSizesBackward0 mps:0
clamped tensor[1024, 784] n=802816 (3.1Mb) x∈[1.195, 2.550e+04] μ=132.411 σ=1.077e+03 grad ClampBackward0 mps:0
```
