### ISSUE TITLE
Torch Quantize aware training. The function prepare_qat_fx(),  should support parameter of 'concrete_args'.

### ISSUE THREAD

**Issue by hasuoshenyun** [pytorch/pytorch#87344]
### 🐛 Describe the bug

I want to do qat (quantized aware training) with the following model, but I met the errors like below. In my opinion, the 

```python
import torch
from torch import fx
from torch.fx import symbolic_trace
from torch.quantization import get_default_qat_qconfig
import torch.quantization.quantize_fx as quantize_fx


# Simple module for demonstration
class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.param = torch.nn.Parameter(torch.rand(3, 4))
        self.linear = torch.nn.Linear(4, 5)

    def forward_train(self, x, gt_label, **kwargs):
        y = self.linear(x + self.param).clamp(min=0.0, max=1.0)
        # gt = kwargs['gt_label']
        gt = gt_label
        diff = y - gt
        return torch.mean(diff)
     
    def forward(self, x, return_loss=True, **kwargs):
        if return_loss:
            return self.forward_train(x, **kwargs)
        else:
            return self.linear(x + self.param).clamp(min=0.1, max=1.0)

net = MyModule()

import copy
net_qat = copy.deepcopy(net)
net_qat.train()
qconfig = get_default_qat_qconfig('qnnpack')
qconfig_dict = {"": qconfig}
# prepare
model_prepared = quantize_fx.prepare_qat_fx(net_qat,
                                            qconfig_dict)

model = model_prepared
model.graph.print_tabular()
optimizer = torch.optim.SGD(net.parameters(), lr=0.02)
# loss_func = torch.nn.CrossEntropyLoss()
loss_func = torch.nn.L1Loss()

for i in range(100):
    x = torch.rand(3, 4)
    y = torch.rand(3, 5)
    loss = model(x, True, img_metas=None, gt_label=y)
    # print(out.shape, y.shape)
    # loss = loss_func(out, y)
    optimizer.zero_grad()
    loss.backward()
    print(loss)
    optimizer.step()

```

got the error like this

```python
Traceback (most recent call last):
  File "/home/liucb/ModelFarm/my_own_tools/torch_qat_fx.py", line 38, in <module>
    qconfig_dict,
  File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/quantization/quantize_fx.py", line 486, in prepare_qat_fx
    concrete_args=concrete_args)
  File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/quantization/quantize_fx.py", line 192, in _prepare_fx
    graph_module = GraphModule(model, tracer.trace(model, concrete_args=concrete_args))
  File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/home/liucb/ModelFarm/my_own_tools/torch_qat_fx.py", line 23, in forward
    if return_loss:
  File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/fx/proxy.py", line 251, in __bool__
    return self.tracer.to_bool(self)
  File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/fx/proxy.py", line 152, in to_bool
    raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
```

In my opinion, the prepare_qat_fx() should have the parameter of "concrete_args", because the Tracer.trace() need that parameter. I think the code should be like this. and the 'concrete_args' will be passed to `    graph_module = GraphModule(model, tracer.trace(model, concrete_args=concrete_args))
` in quantize_fx._prepare_fx()
```python
model_prepared = quantize_fx.prepare_qat_fx(net_qat,
                                            qconfig_dict,
                                            concrete_args={
                                                'return_loss': True,
                                                'img_metas': torch.fx.PH,
                                                'gt_label': torch.fx.PH
                                            })
```

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3
Libc version: glibc-2.10

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-122-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB
GPU 4: NVIDIA A100-PCIE-40GB
GPU 5: NVIDIA A100-PCIE-40GB
GPU 6: NVIDIA A100-PCIE-40GB
GPU 7: NVIDIA A100-PCIE-40GB

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl    http://mirrors.ustc.edu.cn/anaconda/pkgs/free
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h8d4b97c_729    http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] mkl-service               2.4.0            py37h402132d_0    http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_fft                   1.3.1            py37h3e078e5_1    http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] mkl_random                1.2.2            py37h219a48f_0    http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
[conda] numpy                     1.21.5           py37he7a7128_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.21.5           py37hf524024_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.10.2          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py37_cu113    pytorch
[conda] torchvision               0.11.3               py37_cu113    pytorch

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by dzdang** [comment]
fx symbolic tracing isn't in development anymore, so we've opted to keep the API as is for now

**Comment by tatami-galaxy** [comment]
> ### 🐛 Describe the bug
> I want to do qat (quantized aware training) with the following model, but I met the errors like below. In my opinion, the
> 
> ```python
> import torch
> from torch import fx
> from torch.fx import symbolic_trace
> from torch.quantization import get_default_qat_qconfig
> import torch.quantization.quantize_fx as quantize_fx
> 
> 
> # Simple module for demonstration
> class MyModule(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.param = torch.nn.Parameter(torch.rand(3, 4))
>         self.linear = torch.nn.Linear(4, 5)
> 
>     def forward_train(self, x, gt_label, **kwargs):
>         y = self.linear(x + self.param).clamp(min=0.0, max=1.0)
>         # gt = kwargs['gt_label']
>         gt = gt_label
>         diff = y - gt
>         return torch.mean(diff)
>      
>     def forward(self, x, return_loss=True, **kwargs):
>         if return_loss:
>             return self.forward_train(x, **kwargs)
>         else:
>             return self.linear(x + self.param).clamp(min=0.1, max=1.0)
> 
> net = MyModule()
> 
> import copy
> net_qat = copy.deepcopy(net)
> net_qat.train()
> qconfig = get_default_qat_qconfig('qnnpack')
> qconfig_dict = {"": qconfig}
> # prepare
> model_prepared = quantize_fx.prepare_qat_fx(net_qat,
>                                             qconfig_dict)
> 
> model = model_prepared
> model.graph.print_tabular()
> optimizer = torch.optim.SGD(net.parameters(), lr=0.02)
> # loss_func = torch.nn.CrossEntropyLoss()
> loss_func = torch.nn.L1Loss()
> 
> for i in range(100):
>     x = torch.rand(3, 4)
>     y = torch.rand(3, 5)
>     loss = model(x, True, img_metas=None, gt_label=y)
>     # print(out.shape, y.shape)
>     # loss = loss_func(out, y)
>     optimizer.zero_grad()
>     loss.backward()
>     print(loss)
>     optimizer.step()
> ```
> 
> got the error like this
> 
> ```python
> Traceback (most recent call last):
>   File "/home/liucb/ModelFarm/my_own_tools/torch_qat_fx.py", line 38, in <module>
>     qconfig_dict,
>   File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/quantization/quantize_fx.py", line 486, in prepare_qat_fx
>     concrete_args=concrete_args)
>   File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/quantization/quantize_fx.py", line 192, in _prepare_fx
>     graph_module = GraphModule(model, tracer.trace(model, concrete_args=concrete_args))
>   File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
>     self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
>   File "/home/liucb/ModelFarm/my_own_tools/torch_qat_fx.py", line 23, in forward
>     if return_loss:
>   File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/fx/proxy.py", line 251, in __bool__
>     return self.tracer.to_bool(self)
>   File "/home/liucb/anaconda3/envs/tslab/lib/python3.7/site-packages/torch/fx/proxy.py", line 152, in to_bool
>     raise TraceError('symbolically traced variables cannot be used as inputs to control flow')
> torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
> ```
> 
> In my opinion, the prepare_qat_fx() should have the parameter of "concrete_args", because the Tracer.trace() need that parameter. I think the code should be like this. and the 'concrete_args' will be passed to ` graph_module = GraphModule(model, tracer.trace(model, concrete_args=concrete_args))` in quantize_fx._prepare_fx()
> 
> ```python
> model_prepared = quantize_fx.prepare_qat_fx(net_qat,
>                                             qconfig_dict,
>                                             concrete_args={
>                                                 'return_loss': True,
>                                                 'img_metas': torch.fx.PH,
>                                                 'gt_label': torch.fx.PH
>                                             })
> ```
> 
> ### Versions
> Collecting environment information... PyTorch version: 1.10.2 Is debug build: False CUDA used to build PyTorch: 11.3 ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 20.04.4 LTS (x86_64) GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 Clang version: 10.0.0-4ubuntu1 CMake version: version 3.16.3 Libc version: glibc-2.10
> 
> Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0] (64-bit runtime) Python platform: Linux-5.4.0-122-generic-x86_64-with-debian-bullseye-sid Is CUDA available: True CUDA runtime version: Could not collect CUDA_MODULE_LOADING set to: GPU models and configuration: GPU 0: NVIDIA A100-PCIE-40GB GPU 1: NVIDIA A100-PCIE-40GB GPU 2: NVIDIA A100-PCIE-40GB GPU 3: NVIDIA A100-PCIE-40GB GPU 4: NVIDIA A100-PCIE-40GB GPU 5: NVIDIA A100-PCIE-40GB GPU 6: NVIDIA A100-PCIE-40GB GPU 7: NVIDIA A100-PCIE-40GB
> 
> Nvidia driver version: 515.65.01 cuDNN version: Probably one of the following: /usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0 /usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0 /usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0 /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0 /usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0 /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0 /usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0 HIP runtime version: N/A MIOpen runtime version: N/A Is XNNPACK available: True
> 
> Versions of relevant libraries: [pip3] numpy==1.21.5 [pip3] torch==1.10.2 [pip3] torchaudio==0.10.2 [pip3] torchvision==0.11.3 [conda] blas 1.0 mkl http://mirrors.ustc.edu.cn/anaconda/pkgs/free [conda] cudatoolkit 11.3.1 h2bc3f7f_2 http://mirrors.ustc.edu.cn/anaconda/pkgs/main [conda] ffmpeg 4.3 hf484d3e_0 pytorch [conda] mkl 2021.4.0 h8d4b97c_729 http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge [conda] mkl-service 2.4.0 py37h402132d_0 http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge [conda] mkl_fft 1.3.1 py37h3e078e5_1 http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge [conda] mkl_random 1.2.2 py37h219a48f_0 http://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge [conda] numpy 1.21.5 py37he7a7128_1 http://mirrors.ustc.edu.cn/anaconda/pkgs/main [conda] numpy-base 1.21.5 py37hf524024_1 http://mirrors.ustc.edu.cn/anaconda/pkgs/main [conda] pytorch 1.10.2 py3.7_cuda11.3_cudnn8.2.0_0 pytorch [conda] pytorch-mutex 1.0 cuda pytorch [conda] torchaudio 0.10.2 py37_cu113 pytorch [conda] torchvision 0.11.3 py37_cu113 pytorch
> 
> cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

were you able to find a solution?

**Comment by jerryzh168** [comment]
we are developing a new quantization flow: https://pytorch.org/tutorials/prototype/pt2e_quant_ptq_static.html?highlight=pytorch%20export%20quantization

**Comment by khadija23** [comment]
hello @jerryzh168  is pt2e compatible with transformers based model like wav2vec2 for example, do you plan quantization huggingface pretrained mode?

**Comment by jerryzh168** [comment]
@khadija23 please feel free to try out: https://pytorch.org/tutorials/prototype/pt2e_quant_qat.html, I'm not aware that it's been used for transformers though. cc @andrewor14 

we are also building QAT in torchao: https://github.com/pytorch/ao/tree/main/torchao/quantization/qat that can be deployed through executorch to xnnpack backend.

we have integrated torchao into huggingface as well: https://huggingface.co/docs/transformers/main/en/quantization/torchao

also what is your target device?

**Comment by khadija23** [comment]
Hello @jerryzh168  thank you for quick reply, my target device is mobile phone, the wav2vec2 model should be fine tuned though quantization aware training and then exported to mobile format

**Comment by khadija23** [comment]
I tested PT2E but encountered many issues, so now I’m using Eager mode. I managed to train the model successfully, but I can’t run inference after converting the model to int8. Here is the issue ` Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. This could be because the operator doesn't exist for this backend,` I’m facing, along with my code : `import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.ao.quantization
from torch.ao.quantization import QuantStub, DeQuantStub

import copy
import logging
from tqdm import tqdm

from transformers import Wav2Vec2Config, Wav2Vec2ForCTC

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


class Wav2Vec2QAT(nn.Module):
    """
    Wav2Vec2 model with Quantization-Aware Training (QAT).
    The official Wav2Vec2Encoder already calls pos_conv_embed internally,
    so we do NOT manually call it ourselves (to avoid double usage).
    """
    def __init__(self, processor, model_name="facebook/wav2vec2-base", device="cuda"):
        super().__init__()
        self.device = device
        self.model_name = model_name
        self.processor = processor
        
        # 1) Load config & base Wav2Vec2ForCTC
        self.config = Wav2Vec2Config.from_pretrained(model_name)
        self.config.vocab_size = len(processor.tokenizer)
        base_model = Wav2Vec2ForCTC.from_pretrained(model_name, config=self.config)
        
        # 2) Copy submodules from base model
        self.feature_extractor = copy.deepcopy(base_model.wav2vec2.feature_extractor)
        self.feature_projection = copy.deepcopy(base_model.wav2vec2.feature_projection)
        self.encoder = copy.deepcopy(base_model.wav2vec2.encoder)
        self.dropout = copy.deepcopy(base_model.dropout)
        self.lm_head = copy.deepcopy(base_model.lm_head)
        
        # Ensure pos_conv_embed bias is float32 if it exists
        if hasattr(self.encoder, "pos_conv_embed"):
            if hasattr(self.encoder.pos_conv_embed, "conv"):
                if self.encoder.pos_conv_embed.conv.bias is not None:
                    self.encoder.pos_conv_embed.conv.bias.data = \
                        self.encoder.pos_conv_embed.conv.bias.data.to(torch.float32)
        
        # 3) Define QAT stubs around major modules
        #    We skip direct stubs around pos_conv_embed because the encoder calls it internally.
        self.proj_quant = QuantStub()
        self.proj_dequant = DeQuantStub()
        
        self.encoder_quant = QuantStub()
        self.encoder_dequant = DeQuantStub()
        
        self.final_quant = QuantStub()
        self.final_dequant = DeQuantStub()
        
        # 4) CTC Loss
        self.ctc_loss_fn = nn.CTCLoss(
            blank=self.config.pad_token_id,
            reduction="mean",
            zero_infinity=self.config.ctc_zero_infinity
        )
        
        # 5) (Optionally) Freeze the feature extractor
        self._freeze_feature_extractor()
        
        self.to(device)
        logger.info(f"Initialized Wav2Vec2QAT model on {device}")
        
        self.is_prepared_for_qat = False

    def _freeze_feature_extractor(self):
        """
        Freezes the initial convolution feature extractor if you
        only want to train the projection + encoder + LM head.
        """
        for param in self.feature_extractor.parameters():
            param.requires_grad = False
        logger.info("Feature extractor frozen")

    def _remove_parametrizations(self, module):
        """Remove any param wrappers from earlier QAT attempts."""
        for name, child in module.named_children():
            if hasattr(child, "parametrizations"):
                try:
                    torch.nn.utils.parametrize.remove_parametrizations(
                        child, "weight", leave_parametrized=False
                    )
                except ValueError:
                    torch.nn.utils.parametrize.remove_parametrizations(
                        child, "weight", leave_parametrized=True
                    )
            self._remove_parametrizations(child)

    def prepare_for_qat(self):
        """
        Prepare model for QAT with the default fbgemm qconfig,
        skipping the feature_extractor.
        """
        original_device = next(self.parameters()).device
        self.cpu()
        self.train()
        
        self._remove_parametrizations(self)
        
        try:
            # Default QAT config
            default_qconfig = torch.ao.quantization.get_default_qat_qconfig("fbgemm")
            
            # Skip feature_extractor; enable QAT for everything else
            module_qconfig_dict = {
                "feature_extractor": None,
                "feature_projection": default_qconfig,
                "encoder.pos_conv_embed": default_qconfig,
                "lm_head": default_qconfig,
                "": default_qconfig
            }
            
            torch.ao.quantization.propagate_qconfig_(self, qconfig_dict=module_qconfig_dict)
            
            # Enforce pos_conv_embed conv to have the same Qconfig
            if hasattr(self.encoder, "pos_conv_embed"):
                if hasattr(self.encoder.pos_conv_embed, "conv"):
                    self.encoder.pos_conv_embed.conv.qconfig = default_qconfig
            
            torch.ao.quantization.prepare_qat(self, inplace=True)
            
            self.to(original_device)
            self.is_prepared_for_qat = True
            logger.info("Model prepared for QAT successfully.")
            return self
        
        except Exception as e:
            self.to(original_device)
            logger.error(f"Failed to prepare model for QAT: {str(e)}")
            raise

    def forward(self, input_values, attention_mask=None, labels=None):
        """
        Forward pass that mirrors the official Wav2Vec2ForCTC flow:
          1) feature_extractor => [B, freq, T]
          2) transpose => [B, T, freq]
          3) proj_quant -> feature_projection -> proj_dequant => [B, T, hidden_dim]
          4) encoder_quant -> encoder(...) -> encoder_dequant => [B, T, hidden_dim]  (pos_conv_embed is called internally)
          5) final_quant -> LM head -> final_dequant
          6) CTC loss if labels provided
        """
        device = next(self.parameters()).device
        
        # Handle single-dim input
        if isinstance(input_values, tuple):
            input_values = input_values[0]
        if input_values.dim() == 1:
            input_values = input_values.unsqueeze(0)
        
        input_values = input_values.to(device)
        
        # 1) Feature extractor => [B, freq, T]
        with torch.no_grad():
            feats = self.feature_extractor(input_values)
        
        # 2) Transpose => [B, T, freq]
        feats = feats.transpose(1, 2)
        
        # 3) Feature projection with Q stubs => [B, T, hidden_dim]
        feats = self.proj_quant(feats)
        projection_out = self.feature_projection(feats)
        if isinstance(projection_out, tuple):
            projection_out = projection_out[0]
        feats = self.proj_dequant(projection_out)
        
        # 4) Encoder (which internally calls pos_conv_embed):
        feats = self.encoder_quant(feats)
        
        # The official Wav2Vec2Encoder forward() does:
        #   -> pos_conv_embed inside if config.has pos_conv_embed
        #   -> final hidden_states
        encoder_outputs = self.encoder(
            feats,
            attention_mask=attention_mask.to(device) if attention_mask is not None else None,
            output_attentions=None,
            output_hidden_states=None,
            return_dict=True,
        )
        hidden_states = encoder_outputs.last_hidden_state
        hidden_states = self.encoder_dequant(hidden_states)
        
        # 5) Final dropout + LM head -> Q stubs
        hidden_states = self.dropout(hidden_states)
        hidden_states = self.final_quant(hidden_states)
        logits = self.lm_head(hidden_states)
        logits = self.final_dequant(logits)
        
        # 6) Compute CTC loss
        loss = None
        if labels is not None:
            labels = labels.to(device)
            loss = self._compute_loss(logits, labels)
        
        return {"logits": logits, "loss": loss}

    def _compute_loss(self, logits, labels):
        """
        Compute CTC loss for shape [B,T,vocab_size] vs. [B, U] label.
        """
        if labels.max() >= self.config.vocab_size:
            raise ValueError(f"Label values must be < {self.config.vocab_size}")
        
        log_probs = F.log_softmax(logits, dim=-1)  # [B, T, vocab_size]
        
        batch_size, seq_len, _ = log_probs.size()
        input_lengths = torch.full(
            (batch_size,),
            seq_len,
            dtype=torch.long,
            device=logits.device
        )
        
        labels_mask = labels.ne(-100)
        target_lengths = labels_mask.sum(-1, dtype=torch.long)
        
        # Replace -100 with config.pad_token_id
        labels_no_pad = torch.where(
            labels == -100,
            self.config.pad_token_id,
            labels
        )
        
        return self.ctc_loss_fn(
            log_probs.transpose(0, 1),  # => [T, B, vocab_size]
            labels_no_pad,             # => [B, U]
            input_lengths,             # => [B]
            target_lengths             # => [B]
        )

    def convert_to_quantized(self):
        """
        Convert the trained QAT model to a fully quantized model for inference on CPU.
        Must call prepare_for_qat() and train first.
        """
        if not self.is_prepared_for_qat:
            raise ValueError("Call prepare_for_qat() before convert_to_quantized().")
        
        self.eval()
        self.cpu()
        
        try:
            # Freeze all observers / fake-quant modules
            self.apply(torch.ao.quantization.disable_observer)
            self.apply(torch.ao.quantization.disable_fake_quant)
            
            quantized_model = torch.ao.quantization.convert(self)
            logger.info("Model successfully converted to a quantized model.")
            return quantized_model
        
        except Exception as e:
            logger.error(f"Error during quantization conversion: {str(e)}")
            raise


def train_qat_model(
    model,
    train_dataloader,
    val_dataloader=None,
    epochs=3,
    learning_rate=1e-5,
    warmup_steps=1000,
    validate_every=100,
    max_grad_norm=1.0,
    save_path=None
):
    """
    Typical training loop for QAT. Expects each batch from `train_dataloader`
    to have "input_values" and "labels" (both torch tensors).
    """
    # 1) Ensure model is ready for QAT
    if not model.is_prepared_for_qat:
        model.prepare_for_qat()
    
    # 2) Define optimizer & LR scheduler
    optimizer = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=learning_rate
    )
    
    total_steps = len(train_dataloader) * epochs
    scheduler = torch.optim.lr_scheduler.LambdaLR(
        optimizer, lambda step: min(step / warmup_steps, 1.0)
    )
    
    best_val_loss = float("inf")
    
    # 3) Training loop
    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        valid_steps = 0
        
        progress_bar = tqdm(train_dataloader, desc=f"Epoch {epoch+1}/{epochs}")
        
        for step, batch in enumerate(progress_bar):
            try:
                input_values = batch["input_values"].to(model.device)
                labels = batch["labels"].to(model.device)
                
                # Skip extremely short sequences to avoid weird CTC align issues
                if input_values.size(1) < 400:
                    logger.warning(f"Skipping short input of length {input_values.size(1)}")
                    continue
                
                optimizer.zero_grad()
                outputs = model(input_values, labels=labels)
                loss = outputs["loss"]
                
                if torch.isnan(loss) or torch.isinf(loss):
                    logger.warning(f"Invalid loss: {loss.item()}")
                    continue
                
                loss.backward()
                if max_grad_norm > 0:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
                
                optimizer.step()
                scheduler.step()
                
                total_loss += loss.item()
                valid_steps += 1
                
                lr_current = scheduler.get_last_lr()[0]
                progress_bar.set_postfix({
                    "loss": f"{loss.item():.4f}",
                    "lr": f"{lr_current:.2e}",
                    "valid_steps": valid_steps
                })
                
                # Periodic validation
                if val_dataloader is not None and step % validate_every == 0 and step > 0:
                    val_loss = validate(model, val_dataloader)
                    if val_loss < best_val_loss and save_path:
                        torch.save(model.state_dict(), save_path)
                        best_val_loss = val_loss
                    model.train()
            
            except Exception as e:
                logger.error(f"Error in training step: {str(e)}")
                continue
        
        avg_loss = total_loss / max(valid_steps, 1)
        logger.info(
            f"Epoch {epoch+1}/{epochs}, Avg Train Loss: {avg_loss:.4f}, Steps: {valid_steps}"
        )
    
    return model


def validate(model, val_dataloader):
    """
    Validation loop. Expects "input_values" and "labels" in each batch.
    """
    model.eval()
    total_loss = 0.0
    count = 0
    
    with torch.no_grad():
        for batch in val_dataloader:
            try:
                input_values = batch["input_values"].to(model.device)
                labels = batch["labels"].to(model.device)
                
                outputs = model(input_values, labels=labels)
                loss = outputs["loss"]
                
                # Skip NaN or inf
                if torch.isnan(loss) or torch.isinf(loss):
                    continue
                
                total_loss += loss.item()
                count += 1
            
            except Exception as e:
                logger.error(f"Error in validation: {str(e)}")
                continue
    
    avg_loss = total_loss / max(count, 1)
    logger.info(f"Validation Loss: {avg_loss:.4f}")
    return avg_loss
.`

**Comment by jerryzh168** [comment]
> I tested PT2E but encountered many issues, so now I’m using Eager mode. I managed to train the model successfully, but I can’t run inference after converting the model to int8. Here is the issue ` Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. This could be because the operator doesn't exist for this backend,` I’m facing, along with [my code](https://gist.github.com/khadyasr/c8ea9116cdf24305161457d47ccbeba1)

I see, eager mode requires careful placement of QuantStub and DeQuantStub and some modifications of the original code, this error means some of the stubs are not correctly placed, see https://pytorch.org/docs/main/quantization.html#model-preparation-for-eager-mode-static-quantization
