### ISSUE TITLE
[torch.float16] Tensor product @ produces different output when batch size is changed

### ISSUE THREAD

**Issue by helson73** [pytorch/pytorch#87355]
### 🐛 Describe the bug

**Issue:**
With torch.float16 precision, tensor product @ from several released pytorch versions produce different output results when batch size is changed. (nn.Linear is also affected)
This bug may be serious in networks with multiple stacked linear layers like Transformers, since errors could be accumlated through layers. It seems like this bug existed from version 1.10 to 1.14, and as far as I know many new models from various work were trained on these releases. 

**How to reproduce?**
```python
import torch
import random
import torch.nn as nn
from torch.cuda.amp import autocast

seed = 1234
dtype = torch.float16

random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)
torch.cuda.set_device(0)
torch.backends.cuda.matmul.allow_tf32 = False

net = nn.Linear(768, 768).to('cuda:0', dtype=dtype)
net.eval()

K = 10
N = 10
x = torch.randn(K, 768).to('cuda:0', dtype=dtype)
y = torch.randn(N, 768).to('cuda:0', dtype=dtype)
z = torch.cat([x, y], dim=0)

print('')
print('nn.Linear: ')
with torch.no_grad():
    a = net(x)
    b = net(z)
print(torch.abs(a[:K]-b[:K]).sum().item())
print('')

print('Product @: ')
with torch.no_grad():
    c = x @ net.weight.data.t() + net.bias.data.view(1, -1)
    d = z @ net.weight.data.t() + net.bias.data.view(1, -1)
print(torch.abs(c[:K]-d[:K]).sum().item())
```

**Expected behaviour:**
Zeros should be printed.

**Result:**
```bash
>>> torch.__version__
'1.14.0.dev20221020+cu117'
Env: pytorch-nightly from pip
Device: Nvidia A6000
Driver verison: 520.56.06

nn.Linear:
0.96044921875

Product @:
0.84619140625
```

```bash
>>> torch.__version__
'1.14.0.dev20221019'
Env: pytorch-nightly from conda
Device: Nvidia Titan RTX
Driver verison: 515.76

nn.Linear:
0.0

Product @:
0.0
```

```bash
>>> torch.__version__
'1.13.0a0+08820cb'
Env: NGC 22.07
Device: Nvidia A6000
Driver verison: 520.56.06

nn.Linear:
0.96044921875

Product @:
0.84619140625
```

```bash
>>> torch.__version__
'1.10.0a0+ecc3718'
Env: NGC 21.07
Device: Nvidia A6000
Driver verison: 520.56.06

nn.Linear:
0.82568359375

Product @:
0.84619140625
```

```bash
>>> torch.__version__
'1.9.0a0+df837d0'
Env: NGC 21.03
Device: Nvidia A6000
Driver verison: 520.56.06

nn.Linear:
0.0

Product @:
0.0
```

```bash
>>> torch.__version__
'1.9.0+cu102'
Env: pytorch installed from pip
Device: Nvidia Titan RTX
Driver verison: 515.76

nn.Linear:
0.0

Product @:
0.0
```

**Comment by ngimel** [comment]
This is expected, https://pytorch.org/docs/stable/notes/numerical_accuracy.html, cublas uses different kernels for different size inputs under the hood, pytorch calls directly into cublas kernels for these operations.

**Comment by helson73** [comment]
> This is expected, https://pytorch.org/docs/stable/notes/numerical_accuracy.html, cublas uses different kernels for different size inputs under the hood, pytorch calls directly into cublas kernels for these operations.

Hi, thanks for your reply. 
Even though it's expected, inconsistancy across releases is still problematic, I guess I have to do more investigation about this.

**Comment by ngimel** [comment]
Inconsistency across releases is most likely due to different cuda versions.

**Comment by helson73** [comment]
> Inconsistency across releases is most likely due to different cuda versions.

Yes, you're probably correct. Seems like cuda 11.3 has some changes on matrix production ops. But I am still wondering why nn.Linear has different behaviour with ops "@"? And more, torch.mm, torch.bmm, torch "@" are not the same. Guess they decide to use cuda kernel depends on context in different ways as well. 
Anyway, thanks for your notice and your reply saved my day.

**Comment by ngimel** [comment]
`nn.Linear` calls `addmm` that fuses addition operation to matmul, that results in a different and more accurate result than doing addition separately. With `@` you are doing addition separately. `mm` calls into cublasGemm, `bmm` calls into `cublasBatchedGemm` (even if batch size is 1), so whatever cublas decides to do in these cases.
