### ISSUE TITLE
README should link to new cpp_extension

### ISSUE THREAD

**Issue by bstriner** [pytorch/pytorch#8736]
Section titled "Extensions without Pain" (in main README.md) should probably include some links to cpp_extension. 
- Currently just links to: https://pytorch.org/tutorials/advanced/c_extension.html
- Should also link to: https://pytorch.org/tutorials/advanced/cpp_extension.html

@goldsborough Since cpp_extension is your thing, any thoughts about how to update the description in the README? It might also make sense to add a link from c_extension to cpp_extension.

Cheers

**Comment by goldsborough** [comment]
Thanks for reporting! The C extension references should actually just be replaced in favor of C++ extensions altogether.
