### ISSUE TITLE
Moving a tensor across CUDA devices gets zero tensor, CUDA 11.0

### ISSUE THREAD

**Issue by kduxin** [pytorch/pytorch#87363]
### 🐛 Describe the bug

# Environment
- GPU: A100-PCIE-40GB X 4
- CUDA: 11.0
- GPU Driver version: 450.142.00
- PyTorch: 1.8 ~ 1.13
To quickly reproduce, you can use the nvidia-docker `nvcr.io/nvidia/pytorch:22.09-py3`.

# Steps to reproduce
Moving a tensor created on `cuda:0` to `cuda:1` always gets a zero tensor.
```python
>>> import torch
>>> a = torch.tensor([1., 2.]).to('cuda:0')
>>> a
tensor([1., 2.], device='cuda:0')
>>> a.to('cuda:1')
tensor([0., 0.], device='cuda:1')        # zeros, which is wrong
```

However, if I move the tensor once to CPU and then to `cuda:1`, it works correctly. Moreover, all following direct moving on that device become normal.
```python
>>> a.to('cpu').to('cuda:1')         # move once to CPU and then to `cuda:1`
tensor([1., 2.], device='cuda:1')
>>> a.to('cuda:1')                         # now it magically returns correct result
tensor([1., 2.], device='cuda:1')
```

I am not sure whether this bug was reported before, but I am still able to reproduce this bug on latest PyTorch version 1.13. (I reproduced this bug in other versions of PyTorch like 1.8 as well)

# With other GPU cards
- With RTX3090, CUDA 11.4: OK
- With RTX2080Ti, CUDA 10.2: OK

### Versions

PyTorch version: 1.10.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.16.4
Libc version: glibc-2.26

Python version: 3.7.9 (default, May 18 2021, 15:51:21)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-136-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.0.221
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: A100-PCIE-40GB
GPU 1: A100-PCIE-40GB
GPU 2: A100-PCIE-40GB
GPU 3: A100-PCIE-40GB

Nvidia driver version: 450.142.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.10.1+cu111
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.10.1+rocm4.1
[pip3] torchdiffeq==0.0.1
[pip3] torchvision==0.11.2+cu111
[conda] Could not collect

**Comment by ngimel** [comment]
Seems like a duplicate of #84803, for which we still don't have good repro (the bug above doesn't repro for me also).
cc @ptrblck

**Comment by kduxin** [comment]
> Seems like a duplicate of #84803, for which we still don't have good repro (the bug above doesn't repro for me also). cc @ptrblck

Yes, this is a duplicate of #84803. Thank you for providing a reference.
Let me close this issue.

**Comment by alisadeghian** [comment]
Hey, I finally got time to go back to that issue, turning off IOMMU solved it for us.

**Comment by ptrblck** [comment]
@kduxin could you confirm that disabling IOMMU also fixes the issue for you?

**Comment by kduxin** [comment]
> @kduxin could you confirm that disabling IOMMU also fixes the issue for you?

@ngimel @ptrblck 
Thank you for the clue!

It seems disabling IOMMU requires BIOS configuration and rebooting.
As the server is currently used intensively, I have to schedule a maintenance this weekend to check if it works.

So let me reply later !

**Comment by kduxin** [comment]
@alisadeghian @ptrblck @ngimel 
Disabling the IOMMU functionality worked for me !
In our BIOS the configuration is done at /Advanced -> NB configurations -> IOMMU disabled.

Thank you all for the instructions.

**Comment by huweim** [comment]
I face the same question. My environment:
+ GPU: A100-PCIE-80GB X 2
+ CUDA Toolkit: 11.7
+ GPU Driver version: 550.54.15
+ PyTorch: 2.0.1

When I test:
```python
import torch
def main():
    # initialize
    tensor = torch.randn((3, 3), device='cuda:0', dtype=torch.float32)
    
    # print
    print("Initial Tensor (on GPU 0):")
    print(tensor)
    print("Initial Tensor dtype:", tensor.dtype)
    print("Initial Tensor shape:", tensor.shape)
    print("Initial Tensor device:", tensor.device)
    
    # move tensor from gpu0 to gpu1
    tensor_moved = tensor.to('cuda:1')
    
    # print
    print("\nTensor after moving to GPU 1:")
    print(tensor_moved)
    print("Moved Tensor dtype:", tensor_moved.dtype)
    print("Moved Tensor shape:", tensor_moved.shape)
    print("Moved Tensor device:", tensor_moved.device)

if __name__ == "__main__":
    main()
```

The shell print:
```shell
$ python test_move.py 
Initial Tensor (on GPU 0):
tensor([[-0.6885,  1.1974, -0.4899],
        [-0.2524,  0.2563, -0.3006],
        [-0.6876,  2.4340,  0.8452]], device='cuda:0')
Initial Tensor dtype: torch.float32
Initial Tensor shape: torch.Size([3, 3])
Initial Tensor device: cuda:0

Tensor after moving to GPU 1:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:1')
Moved Tensor dtype: torch.float32
Moved Tensor shape: torch.Size([3, 3])
Moved Tensor device: cuda:1
```

My solution:
+ Downgrade the CUDA driver from 550 to 535. It does not work. :x:
+ Downgrade the CUDA driver from 550 to 535 and disable the IOMMU. It works. ✅ 

Does only disabling IOMMU work? Not sure.

Another solution is gpu0 -> cpu -> gpu1, but it needs a manual operation and can not deal with the implicit move.
