### ISSUE TITLE
MPS Allocator Callbacks

### ISSUE THREAD

**Issue by dfalbel** [pytorch/pytorch#87374]
### 🚀 The feature, motivation and pitch

Hi,

I'm working on the [R bindings for LibTorch](https://github.com/mlverse/torch). The R language has a very lazy garbage collector, thus memory is only released to the OS when R needs more memory, LibTorch Tensors are exposed as pointer like R objects, so R is not aware of the memory they use and thus almost never calls GC. In the CUDA case we have fixed this using a callback that just calls the R garbage collector when an allocation fails.

In v1.12.1 LibTorch has support for MPS allocator callbacks:

https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/aten/src/ATen/mps/MPSAllocator.mm#L132

Although they can't really be used for that purpose (explanation below), but callbacks are no longer called since a recent PR (https://github.com/pytorch/pytorch/pull/86119).

Problems with v1.12.1 callbacks implementation:

1. They are only called late - ie. when releasing cached blocks to the OS, and this might not happen since macOS does a lot of swapping, so allocations before that never fail. It would be nice to call them by looking at memory pressure or something similar.
2. They can't free memory. If you try to release MPSAllocator allocated memory, you inevitably call [`Free`](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/aten/src/ATen/mps/MPSAllocator.mm#L198-L205) which acquires the same mutex that [`Malloc`](https://github.com/pytorch/pytorch/blob/664058fa83f1d8eede5d66418abff6e20bd76ca8/aten/src/ATen/mps/MPSAllocator.mm#L107) is using, thus deadlocking.

### Alternatives

I wonder if you would be open to a PR that:

- Re-adds support for the memory callbacks.
- Fixes the issues cited above so they can work for freeing memory.

I have a patch that we are using in our custom builds of LibTorch for arm macs [here](https://github.com/mlverse/libtorch-mac-m1/blob/2343ddd4dce743d5bf65f513fe07d0021e59383e/patch/MPSAllocator-v1.12.1.patch).

It uses a recursive mutex to fix 2. And just calls `trigger_callbacks` earlier than what happens in v1.12.1 to fix 1.

### Additional context

Thank you very much!

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by dfalbel** [comment]
Hi, 

I'm planning to port this patch to v1.13.1 and main in the next few weeks. I'd like to know if there would be any interest in reviewing a PR for this. 

Thank you very much! We got great feedback from R users using the MPS device :)

**Comment by kulinseth** [comment]
Thanks @dfalbel and @albanD , this is great . Please send us the PR .
