### ISSUE TITLE
Quantized Inference on GPU summary of resources

### ISSUE THREAD

**Issue by HDCharles** [pytorch/pytorch#87395]
### 🚀 The feature, motivation and pitch

Quantized Inference on GPU

### Additional context

Quantization support for GPU inference is an area of active development with two existing protypes

1) PyTorch quantization + fx2trt lowering, inference in TensorRT. 

You can read more about TRT at https://pytorch.org/TensorRT/#getting-started

A PTQ tutorial using TRT can be found at https://pytorch.org/TensorRT/tutorials/ptq.html#ptq

You can also find examples in https://github.com/pytorch/TensorRT/blob/master/py/torch_tensorrt/fx/test/quant/test_quant_trt.py

2) Integration with cudnn through native quantized cuda ops which is an early prototype that's been paused.
See test_qconv2d_cudnn at https://github.com/pytorch/pytorch/blob/master/test/quantization/core/test_quantized_op.py#L4608

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by collinmccarthy** [comment]
@HDCharles So in terms of CUDA-based quantization without relying on TensorRT (e.g. FX w/ QConfig converting to quantized CUDA kernels), I'm assuming that is #2 above that has been paused? Are there any plans to resume this effort anytime soon or should we just assume we need to rely on TensorRT for the foreseeable future? Thanks

**Comment by jerryzh168** [comment]
@collinmccarthy yes, we don't have plans to resume this work at this point, yeah you'll need to use TensorRT for now. but feel free to contribute if you have time, you might be able to get the cudnn path working properly for resnet, the latest on that is int8 is 2x slower than fp16, but we have asked cudnn people to fix some of the inefficiencies of the calls and add some support for broadcasting, so if you integrate these changes we might be able to get a speedup I think

**Comment by collinmccarthy** [comment]
@jerryzh168 Thanks for the update, I switched over to TensorRT (and didn't actually see any significant improvement in int8 vs. fp16) so I've moved on from quantization for now. I'm also curious what the impact of the fp8 format in Hopper will be, only time will tell... thanks.

**Comment by vjayd** [comment]
Are quantized PyTorch models supported on Vulkan? If incase needed to deploy model on Mobile GPU?

**Comment by jerryzh168** [comment]
> Are quantized PyTorch models supported on Vulkan? If incase needed to deploy model on Mobile GPU?

I haven't heard of quantization support in Vulkan, so it's probably not supported. but maybe @kimishpatel will know this better

**Comment by kimishpatel** [comment]
> > Are quantized PyTorch models supported on Vulkan? If incase needed to deploy model on Mobile GPU?
> 
> I haven't heard of quantization support in Vulkan, so it's probably not supported. but maybe @kimishpatel will know this better

It is WIP.

**Comment by laclouis5** [comment]
> @jerryzh168 Thanks for the update, I switched over to TensorRT (and didn't actually see any significant improvement in int8 vs. fp16) so I've moved on from quantization for now. I'm also curious what the impact of the fp8 format in Hopper will be, only time will tell... thanks.

What hardware, neural networks and inference configuration (batch size, image size) are you using?

I've been able to achieve near 1.5X speed-up using a quantized EfficientNetB0 with batch size of 8 and input size of 200x200 on a NVIDIA GTX 3070 8GB VRAM GPU compared to a standard FP16 TensorRT run.

**Comment by creaiter** [comment]
> I've been able to achieve near 1.5X speed-up using a quantized EfficientNetB0 with batch size of 8 and input size of 200x200 on a NVIDIA GTX 3070 8GB VRAM GPU compared to a standard FP16 TensorRT run.

@laclouis5 It looks great work! Could you specify some details of your experiments? which hardware, networks, learning and running frameworks, etc.

**Comment by andrewor14** [comment]
Hey @HDCharles is this an issue or more of a note? I'm closing this since I feel it's more like the latter. Please feel free to reopen if I'm misunderstanding.

**Comment by Shan2L** [comment]
> > > Are quantized PyTorch models supported on Vulkan? If incase needed to deploy model on Mobile GPU?
> > 
> > 
> > I haven't heard of quantization support in Vulkan, so it's probably not supported. but maybe @kimishpatel will know this better
> 
> It is WIP.

Hi, can quantized model run on vulkan now? Looking forward to your reply. Thanks!

**Comment by gurkirt** [comment]
@jerryzh168 Thank you you and rest of quantization team. I really in dire need of QAT to work on GPU. I am able to make it work using eager mode defined, but as you know it is only on CPU, it take 4x the time for QAT for 10% of original training. Which can imagine would not be scaleable. How would you recommend I approach this problem? Is [tensor-rt](https://docs.nvidia.com/deeplearning/tensorrt/pytorch-quantization-toolkit/docs/) is my only answer? or I see [FX-mode](https://pytorch.org/tutorials/prototype/fx_graph_mode_quant_guide.html) enabled QAT and [Pt2e](https://pytorch.org/tutorials/prototype/pt2e_quant_qat.html), is any one of them support GPU enabled QAT? If not, which I expect to be the answer, how can I make them support it, I am only interested in four layers like (Conv2D, Linear, BN2D, and ReLU), what would I need to do and which of Pt2e Fx-mode, or Eager-mode would be suitable for my case. I am happy to do PR if someone willing to review them.
