### ISSUE TITLE
FSDP.clip_grad_norm_'s behavior is different from documentation

### ISSUE THREAD

**Issue by l-jc** [pytorch/pytorch#87401]
### 📚 The doc issue

According to the documentation of [clip_grad_norm_ ](https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.FullyShardedDataParallel.clip_grad_norm_), this method should return the total_norm but the [code](https://pytorch.org/docs/stable/_modules/torch/distributed/fsdp/fully_sharded_data_parallel.html#FullyShardedDataParallel.clip_grad_norm_) returns nothing/None. 

### Suggest a potential alternative/fix

Return `total_norm`. 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/87479

`FullyShardedDataParallel.clip_grad_norm_()` should return the total norm like `nn.utils.clip_grad_norm_()`.
