### ISSUE TITLE
Wrong backend check for DebugLevel.DETAIL

### ISSUE THREAD

**Issue by mayurjurani** [pytorch/pytorch#87410]
Line below checks for GLOO backend availability when backend was set to NCCL.

https://github.com/pytorch/pytorch/blob/f38a88c4dd8ce006b9934d0d2f121fb93564479b/torch/distributed/distributed_c10d.py#L890

This bug eventually prevents devs to debug the distributed training issues when Pytorch is only compiled with NCCL.

(I believe it's true for other backends too) 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by zhaojuanmao** [comment]
DebugLevel.DETAIL uses a GLOO based process group wrapper, see [def _create_process_group_wrapper(](https://github.com/pytorch/pytorch/blob/f38a88c4dd8ce006b9934d0d2f121fb93564479b/torch/distributed/distributed_c10d.py#L3210)

that means DebugLevel.DETAIL requires users to compile GLOO as well

**Comment by rohan-varma** [comment]
The helper / wrapper PG needs to be Gloo since we do CPU-side communication to check / debug collective calls. So for DebugLevel.DETAIL, we do require the gloo backend regardless of the underlying backend.
