### ISSUE TITLE
Unable to use pytorch docker image on GPU enabled AWS instance

### ISSUE THREAD

**Issue by theahura** [pytorch/pytorch#87428]
### 🐛 Describe the bug

This may be the wrong place for this report, so please feel free to point me to the right forum. 

I am trying to run one of the pytorch docker images (specifically: https://hub.docker.com/layers/pytorch/pytorch/1.11.0-cuda11.3-cudnn8-devel/images/sha256-9bfcfa72b6b244c1fbfa24864eec97fb29cfafc065999e9a9ba913fa1e690a02?context=explore)

My understanding of this image is that builds pytorch, cuda, cudnn, and has the appropriate nvidia drivers all bundled in the same image. As a result, I should be able to deploy code like:

```python
import torch

print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
```

I deployed this container to a gpu-enabled ec2 instance, but got the following error: 
```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download
/index.aspx                           
```

A few questions:
- Are NVIDIA drivers not built into these images? If not, does pytorch maintain docker images that are _fully_ batteries included? 
- What are the current best practices around installing nvidia drivers and using docker containers simultaneously? How could I ensure those drivers are present on my machines without having to manually install them per machine?

Thanks in advance!

### Versions

NA

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
How do you launch the container?(i.e. do you permit container to access GPUs?)
 And what `nvidia-smi` returns on the host OS?

**Comment by theahura** [comment]
Do you mean on the OS that builds the image, or the OS that is running the image? 

On the OS that builds the image, I don't have NVIDIA drivers, so I get 
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

On the OS that runs the image, it looks like the `nvidia-smi` command does not exist:
```
root@dev-gpu-worker-ilmvgu:/# nvidia-smi                                                                                                                
bash: nvidia-smi: command not found
```
I assumed that the nvidia utils package would also be present in the docker image linked above :thinking: 

As for deployment, the containers are deployed on eks managed by terraform. The deployment resource is described here:
```
resource "kubernetes_deployment" "worker" {                                 
  metadata {                                                                
    name = var.worker_name                                                  
  }                                   
                                      
  spec {                                                                                                                                                
    replicas = 0                                                                                                                                        
    paused   = false                                                        
                                      
    selector {           
      match_labels = {                                                      
        app = var.worker_name     
      }                            
    }                                                                       
                                      
    template {                                                              
      metadata { 
        labels = {            
          app = var.worker_name
        }                
      }                                                                     
                                      
      spec {                                                                                                                                                                
        container {
          name              = var.worker_name                                                                                                           
          image             = local.image
          image_pull_policy = "Always" 
          readiness_probe {
            exec {
              command = tolist(["find", "/alive.txt", "-mmin", "-1"])
            }
            initial_delay_seconds = 5
            period_seconds        = 15
          }
          liveness_probe {
            exec {
              command = tolist(["find", "/alive.txt", "-mmin", "-1"])
            }
            initial_delay_seconds = 5
            period_seconds        = 15
          }
          lifecycle {
            pre_stop {
              exec {
                command = tolist(["touch", "/shutdown.txt"])
              }
            }
          }
        }
        service_account_name = var.service_account.name
      }
    }
  }
}
```
I didn't explicitly give the deployment GPU access, but wasn't aware that I had to. Unfortunately I don't see any good documentation from terraform about how to do this, at least not on the kubernetes_deployment resource page. 

In case it helps, the AMI that I am using is AL2_x86_64.

**Comment by theahura** [comment]
O got it -- the AMI was wrong. Switching to AL2_x86_64_GPU solved the problem and it looks like everything is working!
