### ISSUE TITLE
ONNX export renames 2D parameters, not 1D parameters

### ISSUE THREAD

**Issue by Numeri** [pytorch/pytorch#87452]
### 🐛 Describe the bug

**Describe the bug**

Exported ONNX graphs retain the names for zero dimensional and one dimensional parameters, but rename any two or more dimensional parameters. This makes writing scripts for later graph manipulation much more tedious and prone to breaking.

Note, I originally created [this issue in the NVIDIA/NeMo repository,](https://github.com/NVIDIA/NeMo/issues/5178) as that is the codebase I was using when I ran into the issue. They stated that this behavior is not due to their implementation, but due to PyTorch internals, which is why I'm here. I did my best to find the files in PyTorch's implementation responsible for this, but couldn't figure it out, and would love help finding where this is occurring and why.

**Steps/Code to reproduce bug**

```python3
from nemo.collections.nlp.models.machine_translation import MTEncDecModel

model = MTEncDecModel.from_pretrained('nmt_en_de_transformer12x2')
model.decoder.export('pretrained_decoder.onnx')
```

Open `pretrained_decoder.onnx` in [Netron](https://netron.app/) or some other ONNX graph visualizer. Find and compare the inputs to the nodes `MatMul_106` and `Add_107`.
 - `Add_107` takes 1D tensors as input, and has preserved the name of the parameters from the NeMo model. Its first input is `_decoder.layers.0.first_sub_layer.query_net.bias`.
 - `MatMul_106` requires a 2D tensor as input, and has renamed the parameter from the NeMo model from the quite helpful `_decoder.layers.0.first_sub_layer.query_net.weight` to the generic `onnx::MatMul_636`.

Some extra details that I've realized:

-  This doesn't occur with all 2D parameters: `_embedding.token_embedding.weight` is preserved, for instance, despite being a `(32000, 1024)` tensor. It does occur to most, however.
-  This might be caused by constant folding: When I call the export function with `do_constant_folding=False`, the parameters are not renamed (although the graph is different, now, of course, because constants were not folded in)

**Expected behavior**

I'd love for it to respect the names of all parameters, which would create a predictable and reliable ONNX graph that can then be further post-processed as needed. I'd simultaneously love to be able to use constant folding. At the very least, I'd love to understand why this happens and if it's necessary for some reason.

**Environment overview (please complete the following information)**

 - Environment location: Bare-metal
 - Method of NeMo install: `python -m pip install git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[nlp]` (run today, commit d933ee830d085152fbe07a8fa2b1fa0e493adf0d)

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- PyTorch version: 1.12.1
- Python version: 3.9.0

### Versions

```
Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 12.2.0
Clang version: 14.0.6
CMake version: version 3.24.2
Libc version: glibc-2.36

Python version: 3.9.0 (default, Nov 15 2020, 14:28:56)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.19.16-2-MANJARO-x86_64-with-glibc2.36
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] pytorch-lightning==1.7.4
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.1           py39h6c91a56_0  
[conda] numpy-base                1.23.1           py39ha15fc14_0  
[conda] pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-lightning         1.7.4                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.1               py39_cu113    pytorch
[conda] torchmetrics              0.9.3                    pypi_0    pypi
[conda] torchvision               0.13.1               py39_cu113    pytorch
```

**Comment by justinchuby** [comment]
cc @BowenBao do you have insights to add?

**Comment by BowenBao** [comment]
> When I call the export function with do_constant_folding=False, the parameters are not renamed

That does sound like constant folding is assigning new name to the computed output. I'm not sure if it is a good idea to preserve the exact name as the initializer/constants are changed after all. An improvement could be to assign new name with suffix. This would also help with name collision for cases where original value has multiple usages being folded.

**Comment by Numeri** [comment]
@BowenBao Any idea why it would do this with some initializers, but not others, and why it would never occur in 1D initializers (as far as I've seen)?

**Comment by BowenBao** [comment]
@Numeri It's based on how initializers are used. If it is not constant foldable, then it stays the same. This 2d case is that the weight always needs to be transposed before running `ONNX::MatMul` when converted from `aten::linear`, so it's more common.

Check out this dummy model that does something constant foldable with a 1d parameter
```python
import torch
import io

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.w_1d = torch.nn.Parameter(torch.randn(1))

    def forward(self, x):
        w_2d = self.w_1d.unsqueeze(0)  # constant fold
        return w_2d + x

f = io.BytesIO()
x = torch.randn(2, 2)
torch.onnx.export(Model(), x, f, verbose=True)
torch.onnx.export(Model(), x, f, verbose=True, do_constant_folding=False)
```

outputs:
```
Exported graph: graph(%onnx::Add_0 : Float(2, 2, strides=[2, 1], requires_grad=0, device=cpu),
      %onnx::Add_5 : Float(1, 1, strides=[1, 1], requires_grad=0, device=cpu)):
  %4 : Float(2, 2, strides=[2, 1], requires_grad=1, device=cpu) = onnx::Add[onnx_name="/Add"](%onnx::Add_5, %onnx::Add_0)
  return (%4)

========= Diagnostic Run torch.onnx.export version 2.0.0a0+gitbaefe23 ==========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Exported graph: graph(%onnx::Add_0 : Float(2, 2, strides=[2, 1], requires_grad=0, device=cpu),
      %w_1d : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %/Constant_output_0 : Long(1, strides=[1], device=cpu) = onnx::Constant[value={0}, onnx_name="/Constant"]()
  %/Unsqueeze_output_0 : Float(1, 1, strides=[1, 1], requires_grad=1, device=cpu) = onnx::Unsqueeze[onnx_name="/Unsqueeze"](%w_1d, %/Constant_output_0)
  %4 : Float(2, 2, strides=[2, 1], requires_grad=1, device=cpu) = onnx::Add[onnx_name="/Add"](%/Unsqueeze_output_0, %onnx::Add_0)
  return (%4)

========= Diagnostic Run torch.onnx.export version 2.0.0a0+gitbaefe23 ==========
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
```

**Comment by Numeri** [comment]
Thank you! I guess this is not an issue then. It does make programmatically interacting with optimized graphs a little harder, but I suppose I can live with that :) Thanks!
