### ISSUE TITLE
dynamo emits warning when using `min()`/`max()`

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#87466]
repro:
```
  @torch._dynamo.optimize("aot_eager")
  def f(x):
      a = [1, 2, 4, 3]
      b = max(a)
      return x + b

  out = f(torch.ones(2))
```
prints:
```
[2022-10-21 08:19:05,280] torch._dynamo.variables.builtin: [WARNING] incorrect arg count <bound method BuiltinVariable._call_min_max of BuiltinVariable(max)> missing a required argument: 'b'
```

It looks like dynamo sees the max() builtin, and [tries to call it's own internal](https://github.com/pytorch/pytorch/blob/aa8248cc9a80fc7fc2e5981b8238271d9642eb40/torch/_dynamo/variables/builtin.py#L356) `_call_min_max(a, b)` function, which expects to take in two tensors args, and not arbitrary lists of python objects, then fails and falls back (probably to the normal builtin?).

Seems like the output is correct, the warning just seems strange.

cc @jansel @lezcano @fdrocha @mlazos @soumith @voznesenskym @yanboliang

**Comment by voznesenskym** [comment]
Closing as dup of https://github.com/pytorch/torchdynamo/issues/1685
