### ISSUE TITLE
[FX Quantization]: Allow user to disable fusion

### ISSUE THREAD

**Issue by collinmccarthy** [pytorch/pytorch#87467]
### 🚀 The feature, motivation and pitch

There are situations such as ablation studies, custom fusion implementations and debugging that would benefit from disabling PyTorch fusion during quantization. It does not appear that this is currently possible without writing your own [`_prepare_fx`](https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L122) function.

I also think this is a reasonable request because fusion is currently supported separately via [`fuse_fx`](https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L229), but during FX quantization fusion always occurs. If the two operations are implemented separately, I don't see why the user shouldn't be able to perform them separately. 

### Alternatives

With the addition of a `prepare_custom_config` it appears the right way to do this would be to add a second `fuse_custom_config` argument to [`prepare_fx`](https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L268). Currently the `FuseCustomConfig` object is [default-constructed and cannot be modified by the user](https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L165). 

Another option would be to just add a flag like `fuse` to [`prepare_fx`](https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L268) and then only call [`_fuse_fx`](https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L166) if this flag is set. 

Thank you for considering this feature request!

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo

**Comment by fxmarty** [comment]
@collinmccarthy Agree that this would be a nice feature to have!!

From my research and the line you linked ( https://github.com/pytorch/pytorch/blob/14db44ad72f0110b484c0c8aaf520e110cc91f53/torch/ao/quantization/quantize_fx.py#L165 ), that I know of at least fusions of quantized layers can be disabled by using the key `preserved_attributes` from the argument `prepare_custom_config_dict` of `prepare_fx`: https://pytorch.org/docs/stable/generated/torch.quantization.quantize_fx.prepare_fx.html?highlight=prepare_custom_config_dict . Not sure how it is for non quantized models.

**Comment by vkuzo** [comment]
High level, this would be reasonable to add.  This should be possible today if you customize the `backend_config` argument of `prepare_fx` to remove the fusion patterns you would like to disable (they are there by default).  The `backend_config` interface is not officially documented/released yet as it's not a stable API yet, but we do have a page here (https://pytorch.org/docs/master/quantization-backend-configuration.html ) with the contents of this object.  The entries where the `pattern` key has a value of type tuple represent the fusion patterns.

cc @jerryzh168 , @andrewor14  as an FYI as we iterate on this API

**Comment by jerryzh168** [comment]
since we are moving towards pytorch 2.0 export flow: https://pytorch.org/tutorials/prototype/pt2e_quant_ptq_static.html?highlight=export%20quantization, this will be a low priority for us, and probably won't be fixed, closing for now
