### ISSUE TITLE
Build Error:  no member named 'LeakyReLU' in 'dnnl::graph::op::kind'

### ISSUE THREAD

**Issue by YangChenyuan** [pytorch/pytorch#87476]
### 🐛 Describe the bug

I am building pytorch from the latest source code but I encounter an error that "no member named 'LeakyReLU' in 'dnnl::graph::op::kind'".

I just used ` CC="clang" CXX="clang++" py setup.py install` and didn't change the CmakeList.

What other information should I provide?

### Versions

the latest source code

clang: 14.0.0-1ubuntu1

cc @malfet @seemethere @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by malfet** [comment]
Check that your submodules are uptodate, by running `git submodule update --recursive` (i.e. `mkld-dnn` module was updated recently that includes this symbol)

**Comment by malfet** [comment]
And before you run this, can you please share the output of `git diff`

**Comment by YangChenyuan** [comment]
It works! Thank you for your help!
