### ISSUE TITLE
[ONNX][WIP] Universal quantization handler

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#87508]
## Motivation

Currently to support `quantized::` ops in onnx, we need to (1) create a symbolic in the `Quantized` class (2) unpack quantized args with a function call. In some cases we need to unfuse an operator like `add_relu`. To support `aten::` ops that takes quantized inputs, we need to use the quantized_args decorator. In special `aten::` cases, we also need to specify the requantization scale and zero points.

We would like to specify as little information about the op as possible when adding support for quantized args and infer as much info as possible.

Since there is a quantized tensor representation in TorchScript, we should be able to leverage that and avoid the need for explicitly specifying which arguments are quantized.

TODO

## Related

- https://github.com/pytorch/pytorch/issues/83787
- https://github.com/pytorch/pytorch/issues/80039

**Comment by fxmarty** [comment]
Would be really neat to facilitate fx quantized model --> onnx.
