### ISSUE TITLE
torch.Tensor.get_device would not be updated for CPU tensors behavior

### ISSUE THREAD

**Issue by t2kasa** [pytorch/pytorch#87552]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.Tensor.get_device.html#torch.Tensor.get_device

`torch.Tensor.get_device` should raises `RuntimeError` for CPU tensors based on the documentation, but it seems to return `-1`.

Tested version
```console
>>> torch.__version__
'1.12.1+cu113'
```

The behavior is in my environment:
```console
>>> x = torch.randn(3, 4, 5, device='cuda:0')
>>> x.get_device()
0
>>> x.cpu().get_device()
-1
```

and in the documentation:
```console
>>> x = torch.randn(3, 4, 5, device='cuda:0')
>>> x.get_device()
0
>>> x.cpu().get_device()  # RuntimeError: get_device is not implemented for type torch.FloatTensor
```

cc @svekars @carljparker

**Comment by ngimel** [comment]
This seems like docs issue, we'll accept PR fixing the docs.

**Comment by jingxu10** [comment]
PR filed. Please take a review.
