### ISSUE TITLE
Size mismatch issues with log_sum_exp when keepdim=False

### ISSUE THREAD

**Issue by abaisero** [pytorch/pytorch#8762]
## Issue description

I've encountered two issues with `torch.distributions.utils.log_sum_exp` when using `keepdim=False`.

When the input tensor has 2 dimensions, `log_sum_exp` returns a tensor with the wrong shape (the correct output seems to be contained as the diagonal of the returned tensor;  I'm not sure what the off-diagonals represent, if anything).  In this case, a temporary workaround is to use `keepdim=True` and squeeze the returned tensor.

The docs don't mention anything about input shape, but I would assume log_sum_exp should be able to work on tensors of any shape.  When the input tensor has >2 dimensions, `log_sum_exp` raises a RuntimeError concerning size mismatch.  A temporary workaround is to reshape the input into 2 dimensions, apply the same workaround ad in the previous case, and then reshape the result back.

## Code example
```
import torch
from torch.distributions.utils import log_sum_exp

a = torch.randn(2, 3)

print(log_sum_exp(a).shape)  # should be (2, 1) and is (2, 1)
print(log_sum_exp(a, keepdim=False).shape)  # should be (2,) but is (2, 2)

b = torch.randn(2, 3, 4)

print(log_sum_exp(b).shape)  # should be (2, 3, 1) and is (2, 3, 1)
print(log_sum_exp(b, keepdim=False).shape)  # should be (2, 3) but raises "RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1"
```

## System Info

Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Debian GNU/Linux 9.4 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.7.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[pip3] numpydoc (0.6.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] torch                     0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

**Comment by zou3519** [comment]
Use https://pytorch.org/docs/master/torch.html?highlight=logsumexp#torch.logsumexp instead. It should be available on 0.4.

torch.distributions.utils.log_sum_exp is an internal function.

**Comment by abaisero** [comment]
I kinda suspected as much after opening the issue.  v0.4.0 does not have logsumexp;  Is it viable for me to use log_sum_exp with the above workarounds?  The alternative would be installing a more recent unstable version from source but I'm doubtful about doing that and would rather avoid it.

**Comment by abaisero** [comment]
Another workaround:

```
import torch.nn.functional as F

print((b[..., 0] - F.log_softmax(b, -1)[..., 0]).shape)  #  should be (2, 3) and is (2, 3)
```

I'll probably stick to one of these workarounds;  thanks!
