### ISSUE TITLE
Preserve module hierarchy information in torch.FX graph.nodes

### ISSUE THREAD

**Issue by alexmsettle** [pytorch/pytorch#87659]
### 🚀 The feature, motivation and pitch

The module hierarchy in PyTorch networks is saved in nn.module.named_modules().  This function provides a unique name that maps to each module object in the network.  However, when torch.fx.symbolic_trace() is run on a network, the module hierarchy is lost in the resulting torch.fx.GraphModule.    The unique module names effectively describe the network architecture.  Here's an example name from Hugging Face stable diffusion
**text_model.encoder.layers.0.self_attn.mul** . torchFX would convert this name to just **mul_1** .   From the HF example, just by looking at the module name we can tell the op is part of the encoder from the 0th layer in the self_attn block.  Whereas with the name **mul_1** we can't tell what part of the network this operator belongs to.  

In torch.fx the network graph is stored in the GraphModule.graph.nodes class.  However, the nodes are just a flat listing of all the operators in the network, they don't include any references to the modules which defined the nodes.  The PyTorch ONNX exporter was recently updated to include the module information in the operator unique names.  This feature request is proposing to do the same for torch.FX.

### Alternatives

Live with the current default node names and refer directly to the network source code to try and understand the network architecture.

### Additional context

Here's an example of what the unique operator (graph.node) names should look like.  Just by viewing the graph or the listing from graph.graph you can understand the network architecture which is much easier to work with than inspecting the network source code.

![image](https://user-images.githubusercontent.com/37422826/197660473-f354a0d8-1763-4fc8-89da-fe3cbfcb2020.png)

cc @ezyang @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv

**Comment by SherlockNoMad** [comment]
This is implemented in torchdynamo tracing https://github.com/pytorch/torchdynamo/pull/961
and you can find an example of graph output here https://gist.github.com/SherlockNoMad/03988cafbd08f3ca66e230d8e5543539

A snapshot of the node here: 
```
    # Module Stack: {'self_layer3': 'Sequential', 'self_layer3_1': 'BasicBlock', 'self_layer3_1__bn1': 'BatchNorm2d'}, File "/fsx/users/bahuang/conda/envs/pt_dev/lib/python3.9/site-packages/torchvision/models/resnet.py", line 91, in forward, out = self.bn1(out)
    native_batch_norm_default_13 = torch.ops.aten.native_batch_norm.default(convolution_default_13, primals_41, primals_42, primals_89, primals_90, True, 0.1, 1e-05);
```

The module structure is preserved in FX.node.meta field.

**Comment by justinchuby** [comment]
cc @BowenBao

**Comment by alexmsettle** [comment]
Thanks for the reference @SherlockNoMad, that's what I'm looking for.  Although I need to get the module stack info in the torch.fx.Tracer() class.   I just noticed there is another fx tracer class that implements the module call stack too.   

https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/fx/tracer.py#L92-L119

This code inherits from torch.fx.Tracer() then redefines call_module() and create_node() to include the recording of the module name using the **ScopeContextManager** . I think the scope context should just be moved to the base class torch.fx.Tracer() then everyone who inherits the Tracer() class gets the module names automatically.
