### ISSUE TITLE
Eager mode CPU Autocast implementation for `torch.cat` seems to be broken

### ISSUE THREAD

**Issue by sanchitintel** [pytorch/pytorch#87684]
### 🐛 Describe the bug

AMP implementation for `torch.cat` seems to be broken for CPU.

I noticed with gdb that with PyTorch 1.12, `at::native::to` is called for the second tensor with the following snippet of code, but not with PyTorch 1.13 release branch, or with the master branch:

```python
import torch
with torch.cpu.amp.autocast(cache_enabled=False, dtype=torch.bfloat16):
    a = torch.rand(24, 128, 128)
    b = torch.rand(24, 128, 128, dtype=torch.bfloat16)
    c = torch.cat([a, b], 0)
```

I strongly suspect that this is an AMP issue (probably introduced by #73350, as it doesn't happen before that PR's commit).

Also, when I run the following script (with JIT AMP disabled, tracing a function that calls `torch.cat` with eager-mode AMP),
I see an `aten::to` node with PyTorch 1.12 but not PyTorch 1.13 release branch / master branch.

 ```python
import torch
torch._C._jit_set_autocast_mode(False)

def printTracedModel(model, input):
    with torch.no_grad(), torch.cpu.amp.autocast(cache_enabled=False, dtype=torch.bfloat16):
        traced = torch.jit.trace(model, input)
        fwd_graph = traced.graph_for(*input)
        print(fwd_graph)

def test_cat_check_type_promotion():
    def cat_along_dim(d):
        def forward_cat(*inputs):
            return torch.cat(inputs, d)
        return forward_cat

    x = torch.rand(24, 128, 128)
    y = torch.rand(24, 128, 128, dtype=torch.bfloat16)
    printTracedModel(cat_along_dim(0), [x, y])

if __name__ == '__main__':
    test_cat_check_type_promotion()
```

### Versions

Master branch & Release 1.13 branch.
Release 1.12 is fine, so this is a regression (if this issue really exists)
To quickly verify, one can use:

Sep 27 nightly (has issue) - https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev20220927%2Bcpu-cp38-cp38-linux_x86_64.whl

Sep 26 nightly (without this issue) - https://download.pytorch.org/whl/nightly/cpu/torch-1.13.0.dev20220926%2Bcpu-cp38-cp38-linux_x86_64.whl

cc @VitalyFedyunin @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by jgong5** [comment]
@sanchitintel Could you please specify with a test case what the problem is? I am not seeing a problem with your example plus a result checker below:
```python
import torch
with torch.cpu.amp.autocast(cache_enabled=False, dtype=torch.bfloat16):
    a = torch.rand(24, 128, 128)
    b = torch.rand(24, 128, 128, dtype=torch.bfloat16)
    c = torch.cat([a, b], 0)
torch.allclose(c, torch.cat[a,b.to(dtype=torch.float),0]) # returns True
```
Basically, we expect `torch.cat` to promote the data type of `b` to `torch.float` and the result is expected.

**Comment by sanchitintel** [comment]
Thanks for checking it out, @jgong5!

Maybe the eager-mode AMP functionality seems has changed drastically in the last 4 weeks. 
When I JIT-trace that example after turning off AMP in JIT mode with `torch._C._jit_set_autocast_mode(False)` & using eager-mode AMP instead, I don't see any `aten::to` node for the BFloat16 tensor:

```
graph(%0 : Float(4, 8, 8, 16, strides=[1024, 128, 16, 1], requires_grad=0, device=cpu),
      %1 : BFloat16(4, 8, 8, 24, strides=[1536, 192, 24, 1], requires_grad=0, device=cpu)):
  %2 : int = prim::Constant[value=3]()
  %5 : Tensor[] = prim::ListConstruct(%0, %1)
  %6 : Float(4, 8, 8, 40, strides=[2560, 320, 40, 1], requires_grad=0, device=cpu) = aten::cat(%5, %2)
  return (%6)
  ```

**Comment by sanchitintel** [comment]
@jgong5, here's the corresponding JIT graph with PyTorch 1.12, which has an `aten::to` node:

```
graph(%0 : Tensor,
      %1 : Tensor):
  %5 : int = prim::Constant[value=0]()
  %4 : NoneType = prim::Constant()
  %3 : bool = prim::Constant[value=0]() 
  %2 : int = prim::Constant[value=6]()
  %7 : Tensor = aten::to(%1, %2, %3, %3, %4)
  %17 : Tensor[] = prim::ListConstruct(%0, %7)
  %19 : Tensor = aten::cat(%17, %5)
  return (%19)
```

Reproduction code:

```python
import torch

def printTracedModel(model, input):
    with torch.no_grad(), torch.cpu.amp.autocast(cache_enabled=False, dtype=torch.bfloat16):
        traced = torch.jit.trace(model, input)
        fwd_graph = traced.graph_for(*input)
        print(fwd_graph)

def test_cat_check_type_promotion():
    def cat_along_dim(d):
        def forward_cat(*inputs):
            return torch.cat(inputs, d)
        return forward_cat

    x = torch.rand(24, 128, 128)
    y = torch.rand(24, 128, 128, dtype=torch.bfloat16)
    printTracedModel(cat_along_dim(0), [x, y])

if __name__ == '__main__':
    test_cat_check_type_promotion()
```

**Comment by sanchitintel** [comment]
Fix has landed. Closing issue
