### ISSUE TITLE
Windows build of PyTorch with VS2022 with debug symbols

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#87691]
### Description
- For performance profiling low-level internals of the PyTorch library, it's necessary to compile it with debug symbols as no debug packages seems to be available publicly.
- This is a subtask of https://github.com/microsoft/ARM-on-Windows-Ecosystem/issues/187.

### Acceptance Criteria
- We are able to performance profile PyTorch native code on Window.

**Comment by Blackhex** [comment]
### Documentation
- Install git, Visual Studio 2022 (Visual Studio 2022 Preview must be uninstalled as the CMake prefers it).
- Install Anaconda from https://repo.anaconda.com/archive/Anaconda3-2022.05-Windows-x86_64.exe.
- Install Nvidia CUDA Toolkit 11.7.1 from https://developer.download.nvidia.com/compute/cuda/11.7.1/local_installers/cuda_11.7.1_516.94_windows.exe.
- Install Nvidia cuDNN 8.5.0 from https://developer.nvidia.com/compute/cudnn/secure/8.5.0/local_installers/11.7/cudnn-windows-x86_64-8.5.0.96_cuda11-archive.zip.
- Open Visual Studio 2022 native x64 compilation environment (`& "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat"`): 
  - `conda create –n pytorch-debug`
  - `conda activate pytorch-debug`
  - `conda install astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses`
    - Might fail with: 
      ```
      Collecting package metadata (current_repodata.json): failed 

      CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to 
      download and install packages. 

      Exception: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win- 
      64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) 
      Collecting package metadata (current_repodata.json): failed 

      CondaSSLError: OpenSSL appears to be unavailable on this machine. OpenSSL is required to 
      download and install packages. 

      Exception: HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/main/win- 
      64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) 
    - [Updated to 4.14.0 via `conda update...` - new OpenSSL unavailable message · Issue #11795 · conda/conda (github.com)](https://github.com/conda/conda/issues/11795) 
    - Resolved with:  `set "PATH=%PATH%C:\Users\Username\Anaconda3\condabin;C:\Users\Username\Anaconda3\Library\bin;"` 
  - `conda install snappy==1.1.8` (this might be needed to be done in base environment as snappy==1.1.9 contains incompatible version of benchmark.h)
  - `conda install mkl mkl-include`
  - `conda install -c conda-forge libuv`
  - `git clone --recursive https://github.com/pytorch/pytorch`
  - `cd pytorch`
  - `git submodule sync`
  - `git submodule update --init --recursive --jobs 0`
  - `python setup.py install`:
    - Random failures can arise because of the build running in parallel, restarting the build helps. 
      ```
      C:\Users\MyUser\AppData\Local\Temp\tmpxft_00004728_00000000-7_cuda.cudafe1.cpp: fatal error C1041: cannot open 
      program database 'C:\Projects\pytorch\build\third_party\gloo\gloo\CMakeFiles\gloo_cuda.dir\vc140.pdb'; if multiple CL.EXE 
      write to the same .PDB file, please use /FS 
      ```
    - Linking fails on missing python39_d.lib. 
      - References: 
        - https://stackoverflow.com/questions/61788511/how-to-bring-debug-library-python37-d-lib-to-anaconda 
        - https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build  
        - https://docs.python.org/3/using/configure.html#python-debug-build  
        - https://docs.conda.io/projects/conda-build/en/latest/index.html  
        - https://github.com/conda-forge/python-feedstock/issues/73 
        - https://github.com/conda-forge/python-feedstock/pull/86 
        - https://github.com/conda-forge/conda-forge.github.io/issues/1017  
        - https://github.com/ContinuumIO/anaconda-issues/issues/80 
        - https://github.com/conda-forge/staged-recipes/issues/1593  
        - https://gist.github.com/bombs-kim/c9848c2b09962f2fd753b48b6d2cd87f  
        - https://github.com/conda-forge/staged-recipes/pull/961 
      - Workaround: 
        - Open pyconfig.h file in your Python environment and comment out line 315: 
          ``` 
          #ifdef _DEBUG 
          //#       define Py_DEBUG 
          #endif 
          ```
        - Change line 270 of the same file to: 
          ```
          #                       else 
          #                               pragma comment(lib,"python39_d.lib") 
          #                       endif /* _DEBUG */ 
          ```
        - Copy python39.lib file in you Python environment to python39_d.lib in the same directory.

**Comment by vladimir-aubrecht** [comment]
Closing as it's not priority anymore.
