### ISSUE TITLE
KPI: Distribution of issues by Type, Kind, Severity and T-Shirt Size

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#87702]
Add the following panels to the Grafana dashboard:

- Current distribution of issues by Severity.
- Current distribution of issues by Type.
- Current distribution of issues by Kind.
- Current distribution of issues by T-Shirt Size.

**Comment by Blackhex** [comment]
@vladimir-aubrecht Can you please change title to:

> KPI: Distribution of issues by Type, Kind, Severity and T-Shirt Size by time

and description to:

> Add the following panels to the Grafana dashboard:
> 
> *   Current distribution of issues by Severity.
> *   Time series graph of distribution of issues by Severity.
> *   Current distribution of issues by Type.
> *   Time series graph of distribution of issues by Type.
> *   Current distribution of issues by Kind.
> *   Time series graph of distribution of issues by Kind.
> *   Current distribution of issues by T-Shirt Size.
> *   Time series graph of distribution of issues by T-Shirt Size.
