### ISSUE TITLE
Minor typo in torch.flip and torch.rot90

### ISSUE THREAD

**Issue by scaomath** [pytorch/pytorch#87721]
### 📚 The doc issue

From commit: 302adb7cc827adbcf5cd29c531cd8cbe52b2f7dc

https://github.com/pytorch/pytorch/blob/82dff8ee09278bfea385c27d21d88b978ef911c9/torch/_torch_docs.py#L11153-L11158

and

https://github.com/pytorch/pytorch/blob/82dff8ee09278bfea385c27d21d88b978ef911c9/torch/_torch_docs.py#L11310-L11315

### Suggest a potential alternative/fix

In both docs the phrasing should be "an n-D tensor".

cc @svekars @carljparker

**Comment by malfet** [comment]
Thank you for suggestion, please do not hesitate to submit a PR to propose the fix.

**Comment by scaomath** [comment]
> Thank you for suggestion, please do not hesitate to submit a PR to propose the fix.

Okay, thought this was too minor just me being OCD and wasn't worth an individual PR. #87724
