### ISSUE TITLE
`torch.min`/`torch.max` returns bogus values for default int tensors on MPS

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#87753]
### 🐛 Describe the bug

```
%  python -c "import torch;x=torch.tensor([1, 2, 3],device='mps');print(x, x.max(), x.min())"
tensor([1, 2, 3], device='mps:0') tensor(1, device='mps:0') tensor(0, device='mps:0')
```

### Versions

1.12.1, 1.13.0, nightly

cc @kulinseth @albanD @DenisVieriu97 @razarmehr @abhudev

**Comment by DenisVieriu97** [comment]
Thanks @malfet for filling this issue. min/max is fixed in https://github.com/kulinseth/pytorch/pull/138 (not upstreamed yet to master).

**Comment by malfet** [comment]
> Thanks @malfet for filling this issue. min/max is fixed in [kulinseth#138](https://github.com/kulinseth/pytorch/pull/138) (not upstreamed yet to master).

This sounds reasonable, but shouldn't we throw warning of some sort for int64 types?(i.e. upcasting int8 to int32 is always safe, but downcasting int32 to float32 is not). 
And perhaps the same logic should be applied to `torch.dot` (as `torch.sum` also downcasts int64 to float32)

**Comment by DenisVieriu97** [comment]
`Long` dtype should always excluded for min/max in the above commit (only the smaller dtypes than int32 get casted to it). For int64 it will raise an exception directly (https://github.com/kulinseth/pytorch/pull/138/files#diff-c5284b0274962db09774285279d7538499d357cba0e995d3175ea8e7f4669df4R1267):
```
void min_max_out_mps(...) {
     TORCH_INTERNAL_ASSERT(input_t.scalar_type() != ScalarType::Long, "min/max not supported for Long dtype on MPS");
```
`dot` should also have it also:
```
Tensor dot_mps(...) {
  TORCH_CHECK(self.scalar_type() != ScalarType::Long, "MPS: dot op doesn't support int64 input")
```
I think we should make these messages more generic, and use the same type of assert everywhere we're raising an exception.

**Comment by skotapati** [comment]
Unsupported dtype handling has been standardized now, closing unless there are any additional concerns
