### ISSUE TITLE
[YOLOv5] RuntimeError: out_ptr == out_accessor[thread_count_nonzero[tid + 1]].data() while running on MPS

### ISSUE THREAD

**Issue by 25benjaminli** [pytorch/pytorch#87764]
### 🐛 Describe the bug

`!python train.py --batch 16 --epochs 30 --data ./Bacteria-8/data.yaml --cache --device mps`

I am trying to run YOLOv5 on my macbook pro on macos ventura with apple's MPS. However, when I run the above command, the following runtime error occurs.

**Full error message below**
```
File "/Users/benjaminli/Documents/coding/mltesting/yolov5/utils/loss.py", line 216, in build_targets
    t = t.repeat((5, 1, 1))[j]
RuntimeError: out_ptr == out_accessor[thread_count_nonzero[tid + 1]].data() INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1659484780698/work/aten/src/ATen/native/TensorAdvancedIndexing.cpp":2038, please report a bug to PyTorch.
```

This should be easy to reproduce - just pass in the --device mps flag. Thanks!

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:13:39)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] pytorch                   1.12.1                  py3.8_0    pytorch
[conda] torchaudio                0.12.1                 py38_cpu    pytorch
[conda] torchvision               0.13.1                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by maghili** [comment]
Is there any solution to this? I have the same problem.

**Comment by 25benjaminli** [comment]
I updated to the latest nightly version and I am no longer receiving the same error. However, I have a new one:
```NotImplementedError: The operator 'aten::remainder.Tensor_out' is not currently implemented for the MPS device```
It appears that the issue is still being worked on here: https://github.com/pytorch/pytorch/issues/86806, so hopefully support will be available soon.

**Comment by DenisVieriu97** [comment]
@25benjaminli  these issues are fixed in latest pytorch nightly. Please give it a try and feel free to re-open this issue if you still see any problems.
To install you can use: `pip3 install --pre --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu`
