### ISSUE TITLE
[JIT] type annotations is not descending to the python signature of nn.LSTMCell after instantiazation

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#8777]
After we initialize a nn.LSTMCell and run the instance by passing the input like: 
```
lstm1 = nn.LSTMCell(1, 51)
h_t, c_t  = lstm1(input_t, (h_t, c_t))
```

The type annotation for the instance func we called [1](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/init.cpp#L50) [2](https://github.com/pytorch/pytorch/blob/master/torch/jit/annotations.py#L62) get no signature (which falls back to the default_signature), source/typeline is None. 

Mitigate:
Wrapper function for the instance func that manually add the typeline.

**Comment by eellison** [comment]
I think this is fixed with recursive scripting api.
