### ISSUE TITLE
UserWarning: The operator 'aten::bitwise_and.Tensor_out' is not currently supported on the MPS backend and will fall back to run on the CPU.

### ISSUE THREAD

**Issue by fxy591** [pytorch/pytorch#87776]
Hope the GPU can be more suitable for MacOS with M1 chips faster.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by kulinseth** [comment]
@fxy591 , can you provide a code snippet to reproduce this warning? . Also you can try at your end with latest PyTorch nightly or the 1.13 release. We have support for `bitwise_and` on `mps` device.

**Comment by kulinseth** [comment]
bitwise operators are supported:

```
>>> t = torch.tensor([-1, -2, 3], dtype=torch.int8, device='mps')
>>> torch.bitwise_and(t, torch.tensor([1, 0, 3], dtype=torch.int8, device='mps'))
tensor([1, 0, 3], device='mps:0', dtype=torch.int8)
>>>
```
