### ISSUE TITLE
`log2`, `LSTM.forward` raise SIGFPE on some args and environments

### ISSUE THREAD

**Issue by SunQpark** [pytorch/pytorch#87774]
### 🐛 Describe the bug

I have access to a few of seemingly identical servers and only some of them started raising Floating point exception (core dumped) after resetting their environments. Following two short scripts produce FPE on problematic servers, but runs fine on others. Weird thing is that, this issue does not occur when following scripts are executed right after reboot.
```python
# reproduce case 1
import torch

# the range argument matters here. (-4, 5) and (-7, 8) raises exception but (-3, 4) runs fine.
coords = torch.arange(-7, 8, dtype=torch.float32)
grid = torch.stack(torch.meshgrid(coords, coords, indexing='ij'))
abs_output = torch.abs(grid) + 1.0
print(torch.log2(abs_output)) # FPE here
```

```python
# reproduce case 2
import torch
import torch.nn as nn

rnn = nn.LSTM(10, 20, 2, batch_first=True)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 5, 20)
c0 = torch.randn(2, 5, 20)
output, (hn, cn) = rnn(input, (h0, c0)) # FPE here
```

The output I'm getting is just following.
```
Floating point exception (core dumped)
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-128-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 470.141.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.12.1+cu116
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

cc @VitalyFedyunin @frank-wei @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by SunQpark** [comment]
FYI, the following is `collect.py` output from server that does not have this issue.
```
--2022-10-26 05:25:22--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17278 (17K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py            100%[==================================>]  16.87K  --.-KB/s    in 0.004s

2022-10-26 05:25:22 (4.25 MB/s) - ‘collect_env.py’ saved [17278/17278]

Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.5 (default, Jun  4 2021, 12:28:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to:
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 470.141.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi
```

**Comment by SunQpark** [comment]
Using reproduction script with gdb additionally revealed that two script fails at the same function, which is called `mkl_vml_serv_GetMinN`. 
```shell
gdb --args python3 tests/reproduce_FPE.py


Thread 1 "python3" received signal SIGFPE, Arithmetic exception.
0x00007fffb52ff777 in mkl_vml_serv_GetMinN ()
   from /home/louis2/miniconda3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
```

**Comment by jingxu10** [comment]
Could you try torch==1.13.0+cpu? The 2 reproducers didn't crash per my testing with 1.13.0+cpu.
`pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu`

**Comment by SunQpark** [comment]
My team figured it out that all the servers having this issue also have one CPU core offline in `lscpu`, and that this was due to [this BIOS issue](https://community.amd.com/t5/server-gurus-discussions/dual-socket-epyc-7702-64-cores-shows-254-cpu-online-1-cpu/m-p/350411/highlight/true#M713) of not correctly recognizing all the CPU cores when IOMMU config is disabled. 
We changed IOMMU config to be enabled and the issue is gone.
