### ISSUE TITLE
[JIT] Don't support pass tuple in a PythonOp

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#8778]
We could not pass tuple to a PythonOp, the interpreter will complains [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/script/init.cpp#L74) for not accepting tuple. 

```
lstm1 = nn.LSTMCell(1, 51)
h_t, c_t  = lstm1(input_t, (h_t, c_t))
```

Mitigate: 
Wrapper func outside script func to avoid tuple being analyzed by the jit script

**Comment by driazati** [comment]
This is supported now as long as the Python Op has annotations
