### ISSUE TITLE
MPS throws error when using Softplus activation

### ISSUE THREAD

**Issue by LukasKarner** [pytorch/pytorch#87780]
### 🐛 Describe the bug

On the `mps` device the `Softplus` activation is not working. (on `cpu` it works fine)

```python
import torch

device = torch.device('mps')
t = torch.randn(1).to(device)
act = torch.nn.Softplus().to(device)
o = act(t)

```

```
loc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":219:0)): error: input types 'tensor<1xf32>' and 'tensor<1xi64>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
```

### Versions

PyTorch version: 1.13.0.dev20220926
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.6 (main, Oct 24 2022, 11:04:07) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.6-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.13.0.dev20220926
[pip3] torchaudio==0.13.0.dev20220926
[pip3] torchvision==0.14.0.dev20220926
[conda] numpy                     1.23.3          py310h220015d_0  
[conda] numpy-base                1.23.3          py310h742c864_0  
[conda] pytorch                   1.13.0.dev20220926        py3.10_0    pytorch-nightly
[conda] torchaudio                0.13.0.dev20220926       py310_cpu    pytorch-nightly
[conda] torchvision               0.14.0.dev20220926       py310_cpu    pytorch-nightly

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by mohamedr002** [comment]
### The bug appears on PyTorch 2.0
I want to re-open the issue for PyTorch 2.0, I get the same error when using `mps` but works fine with `cpu` 
```
import torch
device = torch.device('mps')
t = torch.randn(1).to(device)
act = torch.nn.Softplus().to(device)
o = act(t)
```
