### ISSUE TITLE
[ONNX] Graph passes analysis

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#87800]
## Objective

Categorize the different passes applied to the jit Graph during ONNX export and determine their relevance for future designs.

## Categories

- [Tracing] steps (inline autograd)
- Graph [optimization] (dce, constant folding)
- ONNX necessary [adaptation] (Scalar to tensors etc.)

## Passes

| Pass                                                     | Category     | What it does | Notes |
| -------------------------------------------------------- | ------------ | ------------ | ----- |
| _C._jit_pass_canonicalize                                | ?            |              |       |
| _C._jit_pass_canonicalize_graph_fuser_ops                | ?            |              |       |
| _C._jit_pass_constant_propagation                        | optimization |              |       |
| _C._jit_pass_cse                                         | optimization |              |       |
| _C._jit_pass_custom_pattern_based_rewrite_graph          | ?            |              |       |
| _C._jit_pass_dce                                         | optimization |              |       |
| _C._jit_pass_dce_allow_deleting_nodes_with_side_effects  | optimization |              |       |
| _C._jit_pass_erase_number_types                          | adaptation   |              |       |
| _C._jit_pass_filter_non_tensor_arguments                 | ?            |              |       |
| _C._jit_pass_fuse_addmm                                  | ?            |              |       |
| _C._jit_pass_inline                                      | tracing      |              |       |
| _C._jit_pass_inline_fork_wait                            | tracing      |              |       |
| _C._jit_pass_lint                                        | tracing      |              |       |
| _C._jit_pass_lower_all_tuples                            | adaptation   |              |       |
| _C._jit_pass_onnx                                        | ?            |              |       |
| _C._jit_pass_onnx_assign_output_shape                    | adaptation   |              |       |
| _C._jit_pass_onnx_assign_scoped_names_for_node_and_value | adaptation   |              |       |
| _C._jit_pass_onnx_autograd_function_process              | tracing      |              |       |
| _C._jit_pass_onnx_cast_all_constant_to_floating          | adaptation   |              |       |
| _C._jit_pass_onnx_clear_scope_records                    |              |              |       |
| _C._jit_pass_onnx_constant_fold                          | optimization |              |       |
| _C._jit_pass_onnx_deduplicate_initializers               | optimization |              |       |
| _C._jit_pass_onnx_eliminate_unused_items                 | optimization |              |       |
| _C._jit_pass_onnx_eval_peephole                          | optimization |              |       |
| _C._jit_pass_onnx_function_extraction                    |              |              |       |
| _C._jit_pass_onnx_function_substitution                  |              |              |       |
| _C._jit_pass_onnx_graph_shape_type_inference             | adaptation   |              |       |
| _C._jit_pass_onnx_lint                                   |              |              |       |
| _C._jit_pass_onnx_peephole                               | optimization |              |       |
| _C._jit_pass_onnx_preprocess                             | ?            |              |       |
| _C._jit_pass_onnx_preprocess_caffe2                      | ?            |              |       |
| _C._jit_pass_onnx_quantization_insert_permutes           | adaptation   |              |       |
| _C._jit_pass_onnx_remove_inplace_ops_for_onnx            | adaptation   |              |       |
| _C._jit_pass_onnx_remove_print                           | adaptation   |              |       |
| _C._jit_pass_onnx_scalar_type_analysis                   | adaptation   |              |       |
| _C._jit_pass_onnx_set_dynamic_input_shape                | adaptation   |              |       |
| _C._jit_pass_onnx_track_scope_attributes                 | adaptation   |              |       |
| _C._jit_pass_onnx_unpack_quantized_weights               | adaptation   |              |       |
| _C._jit_pass_peephole                                    | ?            |              |       |
| _C._jit_pass_prepare_division_for_onnx                   | adaptation   |              |       |

**Comment by AllenTiTaiWang** [comment]
This can be updated for internal Wiki as well.
