### ISSUE TITLE
AttributeError: 'torch.dtype' object has no attribute 'numel'

### ISSUE THREAD

**Issue by pradeepdev-1995** [pytorch/pytorch#87843]
### 🐛 Describe the bug

Tried the following code for dynamic quantization
```
import torch
from transformers import AutoConfig, AutoModel
model = AutoModel.from_pretrained("bert-base-uncased")
model_quantized = torch.quantization.quantize_dynamic(model, {torch.nn.Linear}, dtype=torch.qint8)
model_quantized.save_pretrained("quantized/")  
```
And it shows the following error while executing
```
AttributeError: 'torch.dtype' object has no attribute 'numel'
```

### Versions

Python 3.7.15
transformers==4.23.1
torch==1.12.1

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen

**Comment by leslyarun** [comment]
I'm also facing the same issue

**Versions**

Python 3.7.15
transformers==4.23.1
torch==1.14.0.dev20221027+cpu

**Comment by pradeepdev-1995** [comment]
@leslyarun 
Because the quantized model contains the ```dtype``` object which is not handle by the  ```save_pretrained``` method  now

**Comment by HDCharles** [comment]
this is all related to save_pretrained not being made to work with quantized models. quantized models have specific supported methods of saving/serialization so errors are expected when other methods are used.

in general you need to use state_dict to save https://pytorch.org/docs/stable/quantization.html#saving-and-loading-quantized-models

we have a tutorial for Bert which has code for serialization: https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html

There's also this other thread that is dealing with the same issue: https://github.com/pytorch/pytorch/issues/88077
