### ISSUE TITLE
[caffe2]Insufficient cuda driver. Cannot use cuda

### ISSUE THREAD

**Issue by danache** [pytorch/pytorch#8785]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

## Issue description

I build caffe2 with python 3.5, cuda 9, cudnn 7 with Driver Version: 390.30: 

but when I try to run this line

`python caffe2/python/operator_test/relu_op_test.py`
the out message shows that 

0622 16:52:53.349123 55004 common_gpu.cc:46] Insufficient cuda driver. Cannot use cuda.

could someone tells me that how can I run caffe2 with cuda?

**Comment by pjh5** [comment]
What's the output of nvidia-smi ?
Where are your cuda installations and what is the output of LD_LIBRARY_PATH ?

**Comment by danache** [comment]
the nvidia-smi result is :
Sat Jun 23 15:45:21 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:00:10.0 Off |                  N/A |
| 29%   23C    P8    15W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

and I compile the caffe2 with the command:
cmake -DCUDA_TOOLKIT_ROOT_DIR=/unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/ ..
and the LD_LIBRARY_PATH is : 
/unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/:/unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64:/usr/local/lib:/usr/local/nvidia/lib64

and the message when I run cmake:
******** Summary ********
-- General:
--   CMake version         : 3.5.1
--   CMake command         : /usr/bin/cmake
--   Git version           : v0.1.11-8987-g7fa81d6-dirty
--   System                : Linux
--   C++ compiler          : /usr/bin/c++
--   C++ compiler version  : 5.4.0
--   BLAS                  : Eigen
--   CXX flags             :  -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wno-invalid-partial-specialization -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wn
o-typedef-redefinition -Wno-unknown-warning-option -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-private-field -Wno-unused-result -Wno-incons
istent-missing-override -Wno-aligned-allocation-unavailable -Wno-error=deprecated-declarations
--   Build type            : Release
--   Compile definitions   :
--   CMAKE_PREFIX_PATH     :
--   CMAKE_INSTALL_PREFIX  : /usr/local
--
--   BUILD_CAFFE2          : ON
--   BUILD_ATEN            : OFF
--   BUILD_BINARY          : ON
--   BUILD_CUSTOM_PROTOBUF : ON
--     Link local protobuf : ON
--   BUILD_DOCS            : OFF
--   BUILD_PYTHON          : ON
--     Python version      : 3.5.2
--     Python includes     : /usr/include/python3.5m
--   BUILD_SHARED_LIBS     : ON
--   BUILD_TEST            : OFF
--   USE_ASAN              : OFF
--   USE_ATEN              : OFF
--   USE_CUDA              : ON
--     CUDA static link    : OFF
--     USE_CUDNN           : ON                                                                                                                                                                        [5758/5940]
--     CUDA version        : 9.0
--     cuDNN version       : 7.0.5
--     CUDA root directory : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/
--     CUDA library        : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/stubs/libcuda.so
--     cudart library      : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
--     cublas library      : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libcublas.so;/unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libcublas_device.a
--     cufft library       : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libcufft.so
--     curand library      : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libcurand.so
--     cuDNN library       : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libcudnn.so
--     nvrtc               : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/lib64/libnvrtc.so
--     CUDA include path   : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/include
--     NVCC executable     : /unsullied/sharefs/xiaotianzi/save/cuda-9.0/cuda/bin/nvcc
--     CUDA host compiler  : /usr/bin/cc
--     USE_TENSORRT        : OFF
--   USE_ROCM              : OFF
--   USE_EIGEN_FOR_BLAS    : ON
--   USE_FFMPEG            : OFF
--   USE_GFLAGS            : ON
--   USE_GLOG              : ON
--   USE_GLOO              : ON
--     USE_GLOO_IBVERBS    : OFF
--   USE_LEVELDB           : ON
--     LevelDB version     : 1.18
--     Snappy version      : 1.1.3
--   USE_LITE_PROTO        : OFF
--   USE_LMDB              : ON
--     LMDB version        : 0.9.17
--   USE_METAL             : OFF
--   USE_MKL               :
--   USE_MOBILE_OPENGL     : OFF
--   USE_MPI               : ON
--   USE_NCCL              : ON
--     USE_SYSTEM_NCCL     : OFF
--   USE_NERVANA_GPU       : OFF
--   USE_NNPACK            : ON
--   USE_OBSERVERS         : ON
--   USE_OPENCL            : OFF
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.9.1
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   Public Dependencies  : Threads::Threads;gflags;glog::glog
--   Private Dependencies : nnpack;cpuinfo;/usr/lib/x86_64-linux-gnu/liblmdb.so;/usr/lib/x86_64-linux-gnu/libleveldb.so;/usr/lib/x86_64-linux-gnu/libsnappy.so;/usr/lib/x86_64-linux-gnu/libnuma.so;opencv_core;op
encv_highgui;opencv_imgproc;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;gcc_s;gcc;dl
-- Configuring done
-- Generating done

-- Build files have been written to: /home/xiaotianzi/save2/pytorch/build

**Comment by pjh5** [comment]
Are you sure your CUDA installation is working? Can you run the included examples okay? Are you sure that your CuDNN and driver versions are compatible with your CUDA?

**Comment by soumith** [comment]
The issue looks like a broken CUDA install, and we received no response from the author, hence closing for now
