### ISSUE TITLE
torch.where: `out` kwarg support is undocumented

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#87862]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.where.html doesn't mention anything about `out` kwarg support.

Ref:
https://github.com/pytorch/pytorch/blob/aaba0bd30641c56db1dc0550b81fbc458db46276/aten/src/ATen/native/native_functions.yaml#L5653

Eg.
```python
>>> torch.where(x < 0, x, -x, out=x)
tensor([-0.6862, -0.6860, -1.4944])
```

cc @svekars @carljparker

**Comment by foram-chandra** [comment]
@lezcano @kshitij12345 I would like to work on it.

**Comment by lezcano** [comment]
go for it. You can check in `CONTRIBUTE.md` how to compile the docs.
