### ISSUE TITLE
PR Label enforcer: Make notice disappear once labels are added

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#87865]
## Context
Recently in https://github.com/pytorch/pytorch/pull/86829 we added a CI check to ensure PRs have a label added to them ([here's why](https://l.workplace.com/l.php?u=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fwiki%2FPyTorch-AutoLabel-Bot%23why-categorize-for-release-notes-and-how-does-it-work&h=AT3Z3dFMEFhUQPbx5sONqWHdIIh3GYoYnQqpOv9lFldCx9oizRT0WqQDs6WdJRwE9DdsIe30RBEKPxezqtko7HYYPIe0o7PzxFOBXpsdPeI67ZlxY8ncG2R0O9fql9hNvcNCVqS6zQwe9D6Z-eM7tCzdxNYKnqiJ7fFzqekimXzuA9Dr3A&__tn__=-UK-R&c[0]=AT06DB13UATQRey4SVEMR9Pr5CXSrY7EfjqNs6JHs5mn0ELx1qXn848TC-Wi-Dlk0lJzmEZlpwclb470x2arLMGvUJZc0tsgAKHtXw6zut09nNP1yGWTc8rK9xn9trrRpY4f1TPjNG_3DRRJOrPptPXzYiYWniNm)).

When the label is missing, the CI fails and our bot will post a comment on the PR with instructions on how to add the label

## Request
**When the CI check passes, the bot should search for the comment it may have left earlier (about how to add a label) and delete that comment.**

The code to search for any previous comments and delete them are already part of the bot (it uses them to keep the comment near the bottom of the PR), but currently it only deletes the comment if it's planning to post an updated comment instead.

## Code pointers
The relevant code is all contained in this PR: https://github.com/pytorch/pytorch/pull/86829/files

Specifically, the changes you make should only need to go in [.github/scripts/check_labels.py](https://github.com/pytorch/pytorch/blob/master/.github/scripts/check_labels.py)

### Invoking the code locally
**Environment variables**: The code requires the env var `GITHUB_TOKEN` to be set to a valid [github token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication). You can create one using the Personal Access Token [instructions here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). (Note that your personal token won't have write access to the pytorch repo, but you'll be able to run the read-only api queries)

**Execution:** With the above env var in place, run the code by executing: https://github.com/pytorch/pytorch/blob/a8e30f62174149f6dc7e5c4f705e8211ee968f9e/.github/workflows/lint.yml#L259

## Want to work on this?
Please comment below lettings us know & go ahead and start working on the ticket, and submit a pull request once it's ready.  

If you need help, feel free to also leave a comment here or reach out to me on Twitter at https://twitter.com/ZainRzv and we'll get you unblocked

**Comment by clee2000** [comment]
fixed by https://github.com/pytorch/pytorch/pull/87999
did not realize this was a bootcamp task oops

**Comment by ZainRizvi** [comment]
Lol, no worries
