### ISSUE TITLE
Need magma-cuda118 to Build from source on CUDA 11.8

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/pytorch#87881]
### 🐛 Describe the bug

Hi! 

I'm trying to build pytorch from source on CUDA 11.8. But magma-cuda117 is only latest one available. 

To build from source successfully I need  magma-cuda118. Available over anaconda. This is hindering development as Linux Kernel 5.19 does not support nvidia drivers with cuda 11.7. Cuda 11.8 is minimum requirement for which magma is not available.

### Versions

Using Ubuntu 22.10.

Linux Kernel 5.19
CUDA 11.8
Python 3.8

**Comment by pmeier** [comment]
> support nvidia drivers with cuda 11.7

The driver is backwards compatible for the CUDA versions so a newer driver should be able to build with CUDA 11.7 without issues. What driver version do you have installed on your system?

**Comment by pmeier** [comment]
Resolved offline in Slack. There is no need to have CUDA 11.8 even if one uses the latest Nvidia driver. Thus, the solution is to simply downgrade to CUDA 11.7. And that implies that the build doesn't work with `magma-cuda117` in the first place. @alexsamardzic was able to build with the setup mentioned in the top comment.

**Comment by oke-aditya** [comment]
Well what worked for me. 
I used CUDA 11.8 did not downgrade to 11.7. 
Used gcc 11 instead of 12. 
Used pytorch magma cuda 117

Built pytorch from source. It worked fine. 

Linux Kernel 5.19
Gcc 11
Cuda 11.8
Pytorch magma cuda 117
Nvidia driver 520

**Comment by oke-aditya** [comment]
Thanks a ton @pmeier and @yosuaMicheal
