### ISSUE TITLE
"No CUDA GPUs are available" coming from GHA g5 runners

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#87890]
### 🐛 Describe the bug

There is a new trend of flaky issues when the GPU seems to disappear from GHA g5 runners. There are 2 common errors:

* `RuntimeError: No CUDA GPUs are available`: https://hud.pytorch.org/failure/RuntimeError%3A%20No%20CUDA%20GPUs%20are%20available  
* `nvidia-smi` failure `nvidia-smi --query-gpu=driver_version --format=csv,noheader --> INSTALLED_DRIVER_VERSION='No devices were found'`.  They might be related
  * https://hud.pytorch.org/pytorch/pytorch/commit/bf113e38fad30fb1eec1f94563f419518ae3178c
  * https://hud.pytorch.org/pytorch/pytorch/commit/107f92a6830f61b88a7eb55934610f491623dc9b 

**Examples**:
https://hud.pytorch.org/pytorch/pytorch/commit/78b406932f0e4afd82b672f959b8cb9ce1e79f9d

### Versions

GHA g5 runners (NVIDIA A10G). Inductors and some trunk tests use them

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ZainRizvi @jeanschmidt @DanilBaibak

**Comment by malfet** [comment]
This looks like a EC2 problem to me (unless we fail to install NVIDIA driver)
@seemethere is there a process to do some smoke testing on the runner before adding it to the pool?

**Comment by seemethere** [comment]
We could add it as part of the userdata script, but would be worth it to file a support ticket to AWS about this since this seems to happen a lot

cc @jeanschmidt

**Comment by huydhn** [comment]
This hasn't happened anymore after upgrading NVIDIA driver, so we can close the issue now.
