### ISSUE TITLE
INTERNAL ASSERT FAILED t.defined() && (t.dim() == 1 || t.dim() == 0)

### ISSUE THREAD

**Issue by creakseek** [pytorch/pytorch#87958]
### 🐛 Describe the bug

t.defined() && (t.dim() == 1 || t.dim() == 0) INTERNAL ASSERT FAILED please report a bug to PyTorch.

```
import torch
import torch.nn.functional as F
input = torch.randn(1, 3, 5, 5)
weight = torch.randn(1, 3, 1, 1)
output = F.prelu(input, weight)
print(output)
```
```
RuntimeError: t.defined() && (t.dim() == 1 || t.dim() == 0) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1659484809662/work/aten/src/ATen/native/Activation.cpp":639, please report a bug to PyTorch.
```

### Versions

PyTorch 1.12.1

cc @ezyang @gchanan @zou3519

**Comment by samdow** [comment]
On 1.13.0, I'm seeing the error:
> RuntimeError: prelu: Expected `weight` to be a scalar or 1D tensor, but got ndim = 4

Could you update and check if you're seeing that too?

**Comment by creakseek** [comment]
Yes, I think this bug is fixed in the latest version
