### ISSUE TITLE
NotImplementedError: The operator 'aten::index_add.out' is not current implemented for the MPS device.

### ISSUE THREAD

**Issue by wlamcuhk** [pytorch/pytorch#87953]
I used conda to install pytorch on my MacM1. The codes ran okay and the model training was fine all along until I updated pytorch and torchvision with conda again, and it returned this error when running the line on backprop.

Have tried to revert the environment but it didn't work either.
Also tried to uninstall and reinstall pytorch as well as opening a new conda environment, it didn't work either.

Tried `PYTORCH_ENABLE_MPS_FALLBACK=1` as suggested. Same Error.

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In [1], line 59
     57     trainer.cfg.model.output_dir += f'/Fold_{str(fold).zfill(3)}'
     58 #             trainer.cfg.lr_scheduler = lr_scheduler
---> 59     trainer.run()
     61     # clean up
     62 #     sys.stdout.flush()
     63     del trainer

File ~/PolyU/Codes/US/notebook/../HBTracking/trainer.py:278, in Trainer.run(self)
    276 for epoch in range(self.cfg.train.start_epoch, self.cfg.train.end_epoch):
    277     last_epoch = time.time()
--> 278     self._train(epoch)
    279     epoch_elapsed = time.time() - last_epoch
    280     self.logger.info(
    281         f'Epoch {epoch+1}/{self.cfg.train.end_epoch} - completed in: {epoch_elapsed//60:.0f}m {epoch_elapsed%60:.0f}s\n')

File ~/PolyU/Codes/US/notebook/../HBTracking/trainer.py:164, in Trainer._train(self, epoch)
    161 loss = self.model(template.to(self.device),
    162                   search.to(self.device), labels.to(self.device))
    163 loss = torch.mean(loss)
--> 164 loss.backward()
    165 # torch.nn.utils.clip_grad_norm(self.model.parameters(), 10)
    166 mean_loss += loss.item()

File /opt/homebrew/Caskroom/miniforge/base/envs/hb-tracking/lib/python3.9/site-packages/torch/_tensor.py:396, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    387 if has_torch_function_unary(self):
    388     return handle_torch_function(
    389         Tensor.backward,
    390         (self,),
   (...)
    394         create_graph=create_graph,
    395         inputs=inputs)
--> 396 torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)

File /opt/homebrew/Caskroom/miniforge/base/envs/hb-tracking/lib/python3.9/site-packages/torch/autograd/__init__.py:173, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    168     retain_graph = create_graph
    170 # The reason we repeat same the comment below is that
    171 # some Python versions print out the first line of a multi-line function
    172 # calls in the traceback and some print out the last line
--> 173 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    174     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    175     allow_unreachable=True, accumulate_grad=True)

NotImplementedError: The operator 'aten::index_add.out' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by kulinseth** [comment]
@wlamcuhk , can you please try with latest PyTorch nightly if the issue still exists. We have added [the Op](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L7113). Also it should be available in the latest 1.13 release.

**Comment by kulinseth** [comment]
@wlamcuhk , can you provide a code snippet to test it at our end.

**Comment by kulinseth** [comment]
As mentioned above the Op should be available in the latest release of PyTorch. Also to verify you can look at [test_mps](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py#L4212) to see its working.
