### ISSUE TITLE
[PT 1.13] resize bilinear yields different results in newer versions

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#87968]
### 🐛 Describe the bug

First, I tried to generate the inputs with the following code with PyTorch 1.13.
```python
>>> import torch
>>> import torch.nn.functional as F
>>> t = torch.randn(1, 3, 128, 128)
>>> torch.save(t, 'bilinear_inputs.pt')
>>> ot = F.interpolate(t, scale_factor=2.0, mode='bilinear', align_corners=True)
>>> torch.save(ot, 'bilinear_outputs_1_13.pt')
```

Then I tried to do the comparison with the Python environment with PyTorch 1.10.
```python
>>> import torch
>>> import torch.nn.functional as F
>>> t = torch.load('bilinear_inputs.pt')
>>> ot = torch.load('bilinear_outputs_1_13.pt')
>>> y = F.interpolate(t, scale_factor=2.0, mode='bilinear', align_corners=True)
>>> torch.allclose(ot, y)
False
>>> torch.testing.assert_close(ot, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/torch/testing/_asserts.py", line 971, in assert_close
    raise error_meta.to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 609 / 196608 (0.3%)
Greatest absolute difference: 2.562999725341797e-05 at index (0, 2, 131, 145) (up to 1e-05 allowed)
Greatest relative difference: 0.07112191124437972 at index (0, 1, 135, 191) (up to 1.3e-06 allowed)
```

As can be seen, the results are not within numerical differences caused by floating point representation.

Attachments:
[bilinear_data.zip](https://github.com/pytorch/pytorch/files/9886015/bilinear_data.zip)

### Versions

PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: version 3.18.0
Libc version: N/A

Python version: 3.8.6 (default, Oct  8 2020, 14:06:32)  [Clang 12.0.0 (clang-1200.0.32.2)] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] onnx2pytorch==0.4.1
[pip3] onnx2torch==1.3.0
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.10.0
[pip3] torchmetrics==0.8.2
[pip3] torchvision==0.11.1
[conda] Could not collect

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
Fun fact, `python -c "import torch;x=torch.rand(10);torch.save('foo', x)"` crashes the runtime, we should fix it

**Comment by malfet** [comment]
@vfdev-5 does this sounds like an acceptable change of accuracy to you? But in general, 2e-5 difference for small issues seems fine.

**Comment by vfdev-5** [comment]
Checking in details the repro code on different versions: 1.10, 1.12, 1.13
IMO, precision issue is related to https://github.com/pytorch/pytorch/commit/658f958bc4bb314d9c6030eeaf3e1784792b5d15
- no issue between 1.10 and 1.12 , 1.10 and 1.13.0.dev20220802+cpu, 1.13.0.dev20220902+cpu and 1.13.0
- reported issue between 1.13.0.dev20220802+cpu and 1.13
There is no issue between 1.10, 1.12 and 1.13 if `align_corners=False`. 

@XiaobingSuper any ideas about the loss of precision here ? 
Shouldn't we also static_cast to scale here ?

https://github.com/XiaobingSuper/pytorch/blob/f3ad87eae4a0dccb2e8aa01e379e99e67194dc49/aten/src/ATen/native/UpSample.h#L289

**Comment by malfet** [comment]
Ok, reverting #83847 brings down divergence to 0.
Modified the test to compute upsample from an torch.arange, to avoid dealing with any denorms, i.e. collecting data using following script:
```
python -c "import torch;x=torch.arange(100, dtype=torch.float32).reshape(1, 1, 10, 10); y=torch.nn.functional.interpolate(x, scale_factor=2.0, mode='bilinear', align_corners=False);torch.save(y, f'y-{torch.__version__}.pt')"
```

**Comment by malfet** [comment]
Somehow following fixes it (though I'm a bit confused how, as accscalar for float should be float, isn't it?
```c++
diff --git a/aten/src/ATen/native/UpSample.h b/aten/src/ATen/native/UpSample.h
index f3dd836444..aca639cc14 100644
--- a/aten/src/ATen/native/UpSample.h
+++ b/aten/src/ATen/native/UpSample.h
@@ -447,9 +447,8 @@ static inline void compute_source_index_and_lambda(
     lambda0 = static_cast<scalar_t>(1);
     lambda1 = static_cast<scalar_t>(0);
   } else {
-    using accscalar_t = at::acc_type<scalar_t, false>;
-    const accscalar_t real_input_index =
-        area_pixel_compute_source_index<accscalar_t>(
+    const scalar_t real_input_index =
+        area_pixel_compute_source_index<scalar_t>(
             ratio, output_index, align_corners, /*cubic=*/false);
     input_index0 = static_cast<int64_t>(real_input_index);
     int64_t offset = (input_index0 < input_size - 1) ? 1 : 0;
```
