### ISSUE TITLE
The memory usage of libtorch algorithm model is different on different hardware

### ISSUE THREAD

**Issue by tensorflowt** [pytorch/pytorch#87978]
### 🐛 Describe the bug

Hi！
I used libtorch's python api to load the swin-tiny segmentation model on different hardware, and found that the memory size occupied by the model on the host side was different. What is the reason for this
![exp1](https://user-images.githubusercontent.com/37217594/198573803-fce986ed-5101-40ed-b700-1b297c8511cd.png)
?

What I am currently confused about is why the same model and the same algorithm interface call end up with different memory usage on the CPU side?

![code](https://user-images.githubusercontent.com/37217594/198574277-ae4cde06-9db6-4552-8458-f7b5c31fb752.png)

My guess here is that the 3080ti has stronger computing power, the corresponding data throughput is higher, and the memory usage of the model is higher. I wonder if this guess is correct?

Looking forward to your reply, good luck!

### Versions

![exp1](https://user-images.githubusercontent.com/37217594/198574531-b1895150-c6c6-4f38-9f43-eab9b3f8ef1d.png)

cc @ngimel

**Comment by ngimel** [comment]
Please ask questions on the forums, discuss.pytorch.org, github is for reporting bugs and feature requests.
