### ISSUE TITLE
building PyTorch from source fails on Mac OS

### ISSUE THREAD

**Issue by vkuzo** [pytorch/pytorch#87993]
### 🐛 Describe the bug

On Mac OS, created a new conda environment and tried to build PyTorch.  It didn't work due to a build error:

```
** AsmJit Summary **
   ASMJIT_DIR=/Users/vasiliy/pytorch/third_party/fbgemm/third_party/asmjit
   ASMJIT_TEST=FALSE
   ASMJIT_TARGET_TYPE=STATIC
   ASMJIT_DEPS=pthread
   ASMJIT_LIBS=asmjit;pthread
   ASMJIT_CFLAGS=-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-Wconversion;-fno-math-errno;-fno-threadsafe-statics;-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS_DBG=
   ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants
-- Using third party subdirectory Eigen.
-- Found PythonInterp: /Users/vasiliy/opt/miniconda3/envs/pytorch/bin/python (found suitable version "3.9.13", mi
nimum required is "3.0") 
CMake Error at cmake/Dependencies.cmake:1079 (if):
  if given arguments:

    "VERSION_LESS" "3"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:715 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/vasiliy/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/Users/vasiliy/pytorch/build/CMakeFiles/CMakeError.log".
FAILED: build.ninja 
```

I do have Python 3.9.13, but seems like CMake's `PYTHONLIBS_VERSION_STRING` is empty, so the build script crashes.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.6 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.27)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.13 (main, Oct 13 2022, 16:12:30)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.14.0a0+gitbad64bd
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-include               2022.1.0           hecd8cb5_209  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.23.3           py39hce7a837_0  
[conda] numpy-base                1.23.3           py39heddfccc_0  

cc @malfet @seemethere @albanD

**Comment by src-r-r** [comment]
Sounds like you need Python's development libraries. I'm not sure how to get them on mac. Perhaps check the python version, too.

**Comment by vkuzo** [comment]
this issue was from awhile ago, but it was transient.  I think it's fine to close.
