### ISSUE TITLE
SyncBatchNorm 3D is slow with torch.channels_last_3d format in DDP on GPU

### ISSUE THREAD

**Issue by myron** [pytorch/pytorch#88021]
### 🐛 Describe the bug

SyncBatchNorm runs slower with torch.channels_last_3d memory format ( DistributedDataParallel  multi-gpu training), even though channels last format is supposed to improve the performance on GPUs. 

Upon closer inspection of SyncBatchNorm:
https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#L10

https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#L107 

it seems we only check for torch.channels_last (2D case), and if the data is in torch.channels_last_3d (3D) it always gets converted to contiguous(). Commenting those lines improves the speed. 

the channels_last support  was introduced in https://github.com/pytorch/pytorch/pull/46906
the inline subfunction seems to return True only for  torch.channels_last (not torch.channels_last_3d)

```
inline bool batch_norm_use_channels_last_kernels(const at::Tensor& self) {
  return self.is_contiguous(at::MemoryFormat::ChannelsLast) || self.ndimension() == 2;
}
```

https://github.com/pytorch/pytorch/pull/46906/files#diff-e895801158bc7155ba3b61826cdd129c5e2caa5c3519171abfbe9bbe5406f52fR3

### Versions

PyTorch version: 1.13.0a0+d0d6b1f
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40
GPU 3: NVIDIA A40
GPU 4: NVIDIA A40
GPU 5: NVIDIA A40
GPU 6: NVIDIA A40
GPU 7: NVIDIA A40

Nvidia driver version: 470.129.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.3.0a0
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.0a0+d0d6b1f
[pip3] torch-tensorrt==1.3.0a0
[pip3] torchtext==0.11.0a0
[pip3] torchvision==0.14.0a0
[conda] functorch                 0.3.0a0                  pypi_0    pypi
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.22.2           py38h6ae9a64_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.13.0a0+d0d6b1f          pypi_0    pypi
[conda] torch-tensorrt            1.3.0a0                  pypi_0    pypi
[conda] torchtext                 0.11.0a0                 pypi_0    pypi
[conda] torchvision               0.14.0a0                 pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by vadimkantorov** [comment]
Also, a question, can it detect "factual" channel last by looking at strides? (at least this might optimize reads of the input in channel_last)

**Comment by rohan-varma** [comment]
@myron thanks for reporting! Had a couple of questions:

1. Do you have a repro of the issue where we run with channels_last3d vs 2d and observe a performance difference? 
2. Concretely, is the suggested fix to also check for channels_last3d memory format before converting to contiguous()?

**Comment by myron** [comment]
@rohan-varma , you can run this example to observe the performance difference

```

import torch, time
import torch.distributed as dist

def get_model_data(channels_last, rank=0):

    model = torch.nn.SyncBatchNorm(num_features=32)
    data = torch.rand((1,32,192,192,192))

    model=model.to(device=torch.device(rank))
    data=data.to(device=torch.device(rank))

    if channels_last:
        model=model.to(memory_format=torch.channels_last_3d)
        data=data.to(memory_format=torch.channels_last_3d)

    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[rank], output_device=rank, find_unused_parameters=False)

    return model, data


def run_forward_backward(model, data, iter=30):
    with torch.cuda.amp.autocast(enabled=True):
        for _ in range(int(iter)):
            for param in model.parameters(): param.grad = None 
            logits = model(data)
            loss = torch.sum(logits**2)
            loss.backward()
            torch.distributed.barrier()
    
    return loss

def main_worker(rank, ngpus_per_node):

    print(f"rank {rank}")

    dist.init_process_group(backend='nccl', init_method='tcp://127.0.0.1:23456', world_size=ngpus_per_node, rank=rank)
    torch.backends.cudnn.benchmark = True
    n_iter =  30


    model, data = get_model_data(channels_last=False, rank=rank)
    run_forward_backward(model, data, iter=1) #warmup

    tic = time.time()
    run_forward_backward(model, data, iter=n_iter)
    if rank==0: print('DDP channels_last=False, run_forward_backward, time:', time.time()-tic, 'sec')


    ###############################
    model, data = get_model_data(channels_last=True, rank=rank)
    run_forward_backward(model, data, iter=1) #warmup

    tic = time.time()
    run_forward_backward(model, data, iter=n_iter)
    if rank==0: print('DDP channels_last=True, run_forward_backward, time:', time.time()-tic, 'sec')

    torch.distributed.destroy_process_group()


def main():
    ngpus_per_node = torch.cuda.device_count()
    torch.multiprocessing.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node,))

if __name__ == "__main__":
    main()
```

**Comment by myron** [comment]
> Concretely, is the suggested fix to also check for channels_last3d memory format before converting to contiguous()?

at a minimum, instead of  
`if not input.is_contiguous(memory_format=torch.channels_last)`
you probably need to use 
`if not input.is_contiguous(memory_format=torch.channels_last) and not input.is_contiguous(memory_format=torch.channels_last_3d)`
in both forward and backward places here https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py

but, I think the proper fix should include more changes to C functions, you can see the updates files (for 2D cases here) https://github.com/pytorch/pytorch/pull/46906/files#diff-e895801158bc7155ba3b61826cdd129c5e2caa5c3519171abfbe9bbe5406f52fR3
( so everyhwere where you check for channels_last format (and at::MemoryFormat::ChannelsLast), you probably need to check for channels_last_3d )
