### ISSUE TITLE
Problem with terminating dataloader workers

### ISSUE THREAD

**Issue by warmspringwinds** [pytorch/pytorch#8805]
## Issue description

We have tried spawning a process which uses dataloader with multiple workers.
After trying to terminate the main process, the children processes created by dataloader
didn't exit and gpu memory wasn't released.

## Code example

We have used this example:
https://github.com/pytorch/examples/tree/master/mnist

and launched a process

```
from multiprocessing import Process
from main import main

process = Process(target=main)
#process.daemon = False
process.start()
```
After terminating the process with:
```
process.terminate()
process.join()
```

The memory wasn't released and we had to manually kill processes by
inspecting ```lsof /dev/nvidia0``` and using ```kill -9``` on them.
Since the worker processes are daemonic, I was expecting them to terminate once the parent process is terminated.

This behavior is only present in pytorch 0.4 and was solved in pytorch 0.5 with this commit:
https://github.com/pytorch/pytorch/pull/6606

I still don't understand why the aforementioned example doesn't work in pytorch 0.4 though.

## System Info

```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.11.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py27_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] torchvision               0.2.1                    py27_1    pytorch
```

**Comment by SsnL** [comment]
I don't see where you set the subprocess as daemonic. The flag is inherited from parent, but by default false I believe: https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Process.daemon

**Comment by warmspringwinds** [comment]
@SsnL Thank you for your reply!

It doesn't work in either ```process.daemon = False``` or ```process.daemon = True``` case.
I think the problem is relevant to this one:
https://github.com/pytorch/pytorch/issues/5736

although we are getting the same problem while to safely stop the process with ```.terminate()```

**Comment by yf225** [comment]
@warmspringwinds According to the Python doc (https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.terminate), subprocesses of the spawned process will not be terminated, and they will simply become orphaned. This can explain why gpu memory wasn't released in the dataloader worker processes.

The change in https://github.com/pytorch/pytorch/pull/6606 acts as a failsafe and will terminate the worker processes in all scenarios (with or without signal propagation between parent and workers).

**Comment by warmspringwinds** [comment]
@yf225 Thank you!

I just wanted to make sure that it is an expected behavior in pytorch <= 0.4 and not a bug.
