### ISSUE TITLE
Proposal: move Variable.version_counter to Storage

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#8806]
Currently, we store a `version_counter` in the VariableImpl wrapper that increments every time a `Variable` is modified by an in-place operation. It's used to detect modifications to variables that were saved to compute some future autograd derivative. The version counter is tracked even on Variables that do not have `requires_grad=True` because those variables may still be saved.

@ezyang suggested moving the version counter to the `Storage`. This would avoid the need for a `shared_ptr` (and the extra allocation that incurs) since Variables that share storages would implicitly share version counters.

This would change the semantics of `Variable.data`. Currently, the result of `self.data` does not share a version counter with `self`, but after this change it would.

As an "escape hatch", we could add a global, thread-local flag that disables version-counter updates during in-place operations.  For example,

```
with torch.no_version_counter():
   x += 1  # version_counter of x not modified
```

One motivation behind this change is to make sure that C10/Caffe2 does incur extra overhead for autograd if it's not used.

cc @apaszke

**Comment by karimhasebou** [comment]
is this issue still present ?

**Comment by colesbury** [comment]
I think the design has changed since the issue was written. `version_counter` is still in Variable, but I'm not sure we want to move it to Storage. We may want to combined the Storage and Tensor abstractions

**Comment by VitalyFedyunin** [comment]
Ideally we want to combine Tensor and Storage, this project will likely start mid-ish H1 2020 after Th->Aten is done.
