### ISSUE TITLE
AttributeError: 'BertModel' object has no attribute 'save'

### ISSUE THREAD

**Issue by pradeepdev-1995** [pytorch/pytorch#88077]
### 🐛 Describe the bug

Tried to save the model using jit after dynamic quantization using the following code
```
import torch
from transformers import AutoConfig,AutoModel
model = AutoModel.from_pretrained("bert-base-uncased")
model_quant = torch.quantization.quantize_dynamic(model,{torch.nn.Linear}, dtype=torch.qint8)
torch.jit.save(model_quant, 'quantized.pt')
```
But it shows the below error
```
AttributeError: 'BertModel' object has no attribute 'save'
```
Even the code 
```
torch.jit.save(model, 'quantized.pt')
```
also shows the same error

### Versions

torch @ https://download.pytorch.org/whl/cu113/torch-1.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
transformers==4.23.1
Python 3.7.15

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen

**Comment by HDCharles** [comment]
looks like this is an issue with the AutoModel object, the actual quantization didn't have any errors, its just that this custom object doesn't have a save function, did you try the state dict method?

**Comment by pradeepdev-1995** [comment]
@HDCharles 
as you suggested I tried with ```state_dict``` method like this
```
import torch
from transformers import AutoConfig,AutoModel
model = AutoModel.from_pretrained("bert-base-uncased")
model_quant = torch.quantization.quantize_dynamic(model,{torch.nn.Linear}, dtype=torch.qint8)
quantized_state_dict = model_quant.state_dict()
torch.jit.save(quantized_state_dict, 'scriptmodule.pt')
```
but it shows that
```AttributeError: 'collections.OrderedDict' object has no attribute 'save'```

**Comment by pradeepdev-1995** [comment]
@HDCharles 
Seems it is not an issue with Automodel class. Because the Bertmodel also shows the same error 
```
import torch
from transformers import BertConfig, BertModel
model = BertModel.from_pretrained("bert-base-uncased")
model_quant = torch.quantization.quantize_dynamic(model,{torch.nn.Linear}, dtype=torch.qint8)
torch.jit.save(model_quant, 'quantized.pt')
```
Shows
```AttributeError: 'BertModel' object has no attribute 'save'```

**Comment by HDCharles** [comment]
we have a tutorial for Bert: https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html

can you try the serialization code there and see if addresses this issue?

**Comment by HDCharles** [comment]
> @HDCharles as you suggested I tried with `state_dict` method like this
> 
> ```
> import torch
> from transformers import AutoConfig,AutoModel
> model = AutoModel.from_pretrained("bert-base-uncased")
> model_quant = torch.quantization.quantize_dynamic(model,{torch.nn.Linear}, dtype=torch.qint8)
> quantized_state_dict = model_quant.state_dict()
> torch.jit.save(quantized_state_dict, 'scriptmodule.pt')
> ```
> 
> but it shows that `AttributeError: 'collections.OrderedDict' object has no attribute 'save'`

also i think you are mixing up serialization (jit) with saving (state_dict)

**Comment by pradeepdev-1995** [comment]
@HDCharles  okay, could you please share the code snippet here for dynamic quantization of bert model and its save procedure using jit?

**Comment by pradeepdev-1995** [comment]
@HDCharles 
Also how can I define the second argument(example input) in torch.trace method
```
import torch
import io
from transformers import AutoConfig,AutoModel
model = AutoModel.from_pretrained("bert-base-uncased")
model_quant = torch.quantization.quantize_dynamic(model,{torch.nn.Linear}, dtype=torch.qint8)
torch.jit.trace(model_quant,<example input>)
```
What should be the **values**, **dimension** and **type** of the example input argument that ```torch.trace``` method excepts?

**Comment by HDCharles** [comment]
the serialization+save is here: https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html#serialize-the-quantized-model

the example input is a tensor input or tuple of inputs, can find more info here: https://pytorch.org/docs/stable/generated/torch.jit.trace.html?highlight=torch+jit+trace#torch.jit.trace
