### ISSUE TITLE
How to export pytorch model to onnx, with input of List[Tuple[Tensor,Tensor]] and output of List[Tuple[Tensor,Tensor]]

### ISSUE THREAD

**Issue by yszhou2019** [pytorch/pytorch#88073]
I have no idea how to export this model to onnx. One of the inputs for this model accepts a list of uncertain tuple, each of which contains 2 tensor with size of (2, 1024). This model also returns a list of tuple of two tensors(2, 1024).

How can I export it? I've already searched in pytorch community, but most of the issues have no replies.

## Code example

state[in] is a list, and state[out] is also a list.

model definition
```python
class Module(nn.Module):
    ...
    def forward(self, enc_out, enc_mask, tgt_seq,
               state: Optional[List[Tuple[torch.Tensor, torch.Tensor]]] = None,
               bias_embedding: Optional[torch.Tensor] = None):
        if state is not None:
            hid = list()
            cell = list()
            for h, c in state:
                hid.append(h)
                cell.append(c)
            state_in = (torch.stack(hid, dim=1), torch.stack(cell, dim=1))
        else:
            state_in = None
        logit, attn, state_out = self.decoder(tgt_seq, enc_out, enc_mask, state_in,
                                              bias_embedding=bias_embedding)
        hid, cell = state_out
        state = [(hid[:, j, :], cell[:, j, :]) for j in range(logit.size(0))]
        logit = logit[:, -1, :].squeeze(1)
        return torch.log_softmax(logit, -1), attn, state
```

model export
```python
    input_names = ["enc_out", "enc_mask", "tgt_seq", "cache_state", "bias_embedding"]
    output_names = ["dec_out", "attn", "state"]
    dynamic_axes = {
        "enc_out": {0: "batch_size", 1: "enc_out_len"},
        "enc_mask": {0: "batch_size", 1: "enc_out_len"},
        "tgt_seq": {0: "batch_size"},
        "dec_out": {0: "batch_size"},
        "attn": {0: "batch_size", 3: "enc_out_len"},
        "state": {1: "batch_size"},
    }
    torch.onnx.export(
        model,
        (enc_out, enc_mask, tgt_seq, cache_state, bias_embedding),
        "decoder.onnx",
        export_params=True,
        opset_version=13,
        do_constant_folding=True,
        input_names=input_names,
        output_names=output_names,
        dynamic_axes=dynamic_axes
    )
```

**Comment by justinchuby** [comment]
Hi! torch.onnx expects a fix amount of input since the onnx model graph is static. A list of Tuple will not work. Would it be possible for you to know the number of inputs beforehand?

**Comment by thiagocrepaldi** [comment]
This model should be exportable, even if the resulting graph is not dynamic in the sense it will accept inputs with different number of tuples. Please report back the issue that you have and we can help you better.

If the varying number of tuples is not generalized, one idea is to add code on a wrapper function with export logic of `torch.onnx.export` to detect input changes before every forward step, triggering a new export

If you use ONNX runtime to run the ONNX model, a more convenient solution is to use wrap your model on called [ORTModule](https://github.com/microsoft/onnxruntime/blob/main/orttraining/orttraining/python/training/ortmodule/ortmodule.py#L26) to wrap your model. `ORTModule` does track input changes and re-export ONNX accordingly every time input changes in a way ONNX cannot handle.

In this case, on your example above, all you would need to do is

```
import from onnxruntime.training.ortmodule import ORTModule, DebugOptions

model = ORTModule(module, DebugOptions(save_onnx=True, onnx_prefix="/path/to/model.onnx")
output = model(input)
```
Every time input has a different number of inputs, or inputs with different types and shapes, ORTModule will re-export ONNX for you, making sure `onnxruntime` uses the proper ONNX to execute your model

Hope that helps

**Comment by yszhou2019** [comment]
Sorry for the late reply. Thank you guys :)
