### ISSUE TITLE
Cannot print in fake tensor mode

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#88087]
### 🐛 Describe the bug

Should turn off fake tensor mode if it exists for printing only

cc @eellison 

### Versions

master

**Comment by eellison** [comment]
sorry - what did you. mean by this exactly ?

**Comment by indrajeetapache** [comment]
I think @ezyang  is referring to [FAKE tensor](https://pytorch.org/torchdistx/latest/fake_tensor.html#fake-tensor) 

But this is very useful functionalities in case of **"for inspecting large model architectures that cannot fit on a consumer-grade"**

**Comment by ezyang** [comment]
```
  import torch
  from torch._subclasses.fake_tensor import FakeTensorMode
  
  x = torch.zeros(2)
  with FakeTensorMode():
      print(x)
```
