### ISSUE TITLE
[Label Check] Move label check logic from CI to mergebot

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#88098]
Currently, we have [a CI check](https://github.com/pytorch/pytorch/blob/master/.github/workflows/check-labels.yml#L44) that checks to see if a PR has the appropriate labels on it, and fails the check if the right label is missing.

Instead of making this be something that makes the CI appear to have failed, lets make two changes:

1. Modify the CI check to only share a comment reminding the user to add the appropriate CI (without reporting a failing check)
2. Update mergebot rules in https://github.com/pytorch/pytorch/blob/master/.github/scripts/trymerge.py to 1) fail the merge if the PR is missing the required labels and 2) post a comment explaining that the merge was failed due to the missing label

Original customer request:

> Can we make the "needs labels" signal not part of the actual CI signal? I use the GitHub green/red indicator to easily check if a PR succeeded CI or not, but lack of labels turns this into a fail and obscures the signal.
> 
> Instead, **the merge bot should just reject merges if they don't have a label**. The idea being, it's very easy to immediately add the label and try again. You don't need this signal ahead of time!

**Comment by ZainRizvi** [comment]
The main risk I see this incurring then is the reviewer may stop paying attention to the PR once they've signed off, which may block the author if they don't know what label to add (and there's no good guidance around knowing the right labels today, it's currently "ask your reviewer if you don't know)

**Comment by ZainRizvi** [comment]
Turned this into bootcamp task T142113229

**Comment by Christo77793** [comment]
Hi I would like to contribute to this issue. I am getting started in the area of opensource contribution and before I even begin I would like to know what the letters CI mean in this context? Thank you.
