### ISSUE TITLE
No backward implementation for Scatter Multiply (or add) reduction 

### ISSUE THREAD

**Issue by robflynnyh** [pytorch/pytorch#88097]
### 🐛 Describe the bug

There isn't a backwards operation implemented for any of the reduction operation for scatter, and this isn't mentioned in the docs

- to reproduce:
src = torch.arange(1, 11, requires_grad=True, dtype=torch.float32).reshape((2, 5))
index = torch.tensor([[2,2,2,2,2],[1,1,1,1,1]])
out = torch.ones(3, 5, dtype=src.dtype, requires_grad=True)
out.scatter(0, index, src, reduce="multiply")

### Versions

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.3.122
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: GeForce RTX 3080
GPU 1: GeForce RTX 3080

Nvidia driver version: 460.27.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] fast-pytorch-kmeans==0.1.6
[pip3] k2==1.16.dev20220625+cuda11.3.torch1.11.0
[pip3] kmeans-pytorch==0.3
[pip3] numpy==1.22.4
[pip3] perceiver-ar-pytorch==0.0.9
[pip3] pytorch-lightning==1.6.3
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.11.0
[pip3] torch-ema==0.3
[pip3] torch-optimizer==0.3.0
[pip3] torchaudio==0.11.0
[pip3] torchmetrics==0.9.1
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] fast-pytorch-kmeans       0.1.6                    pypi_0    pypi
[conda] k2                        1.16.dev20220625+cuda11.3.torch1.11.0          pypi_0    pypi
[conda] kmeans-pytorch            0.3                      pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] perceiver-ar-pytorch      0.0.9                     dev_0    <develop>
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-ranger            0.1.1                    pypi_0    pypi
[conda] torch-ema                 0.3                      pypi_0    pypi
[conda] torch-optimizer           0.3.0                    pypi_0    pypi
[conda] torchaudio                0.11.0               py38_cu113    pytorch
[conda] torchmetrics              0.9.1                    pypi_0    pypi
[conda] torchvision               0.12.0               py38_cu113    pytorch

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mikaylagawarecki

**Comment by ezyang** [comment]
cc @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Hi! Upgrading to 1.12 or 1.13 should fix this (note that the api might be slightly different, see the bc-breaking note [here](https://github.com/pytorch/pytorch/releases/tag/v1.12.0) for details

**Comment by robflynnyh** [comment]
ahh thank you !!
