### ISSUE TITLE
[ONNX] Adopt OpInfo testing

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#88118]
# [Design Proposal] Adopt OpInfo in ONNX exporter testing

## Objective

This doc introduces a mechanism to test onnx export based on sample inputs registered in OpInfo(https://dev-discuss.pytorch.org/t/opinfos-in-pytorch-1-10/253), similar to how MPS [master/test/test_mps.py](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py) and other components of pytorch are tested.

It provides test coverage on ops and dtypes previously unattainable with manually created test models, and makes test authoring much easier for torch.onnx developers.

We can leverage OpInfo to discover gaps in the exporter support, especially for ops with partial existing support.

## Motivation

The current unit tests for the torch.onnx `export` process, mainly residing in `test/onnx/test_pytorch_onnx_onnxruntime.py`, are manually created when operator support is added in the form of various symbolic functions.

It is hard to create comprehensive tests for each op given the amount of ops we need to support. It has caused the exporter to assume support of ops for which it only has partial support on certain dtype / input combinations, leading to a degraded user experience and most recently complicated support for torchdynamo. (example #85316)

Fortunately, there exists a test generation mechanism in pytorch core which is `OpInfo`. (See https://dev-discuss.pytorch.org/t/opinfos-in-pytorch-1-10/253). OpInfos are Python objects that describe operators and how to test them, and is it adopted by tests across PyTorch components like torchscript, mps, fx and others.

It greatly reduces the need for manually creating new tests for `torch.onnx`, and enables a simple test authoring experience that allows for a comprehensive op level coverage. You can read more about OpInfo following https://dev-discuss.pytorch.org/t/opinfos-in-pytorch-1-10/253.

## Design Considerations

- The work for enabling tests for ops need to be relatively low cost and can be done incrementally.
- Developers need to be able to skip flaky test and unexpected tests.
- All opsets should be tested.

## Assumptions and Dependencies

- We assume OpInfo to continue to be the testing strategy across torch components. (The info instances are in `torch.testing._internal.common_methods_invocations.op_db`)
- All tests in the op_info will be run on all torch.supported opsets
- Models will only be tested in tracing mode. The unit tests OpInfo enables are op-level tests, which compliments existing scripting tests.
- Only cpu models are tested.
- Tests for different ops will be enable incrementally as errors are fixed.
- Current manually created test models should continue to exist, but new ops and fixes should first enable OpInfo based tests and only add new test models to `test/onnx/test_pytorch_onnx_onnxruntime.py` when needed.

## General Constraints

- It is unclear if the scripting mode is supported, since the op being tested is exposed via OpInfo. 
    - We should be reasonably confident with tracing only tests with OpInfo, because we are only testing for op support and not the graph capturing aspect with OpInfo.
- Only ops that have `OpInfo`s will be tested via this mechanism.
    - It is possible to contribute new `OpInfo` to pytorch testing core. Supplemental tests can also be created in what is done in MPS
    - At ~530 in count, the existing OpInfos cover enough ops `torch.onnx` cared about and can detect many errors in test that we previously don't have mechanism of detecting.
- The OpInfo are created for torch ops (not aten ops)
    - They have a reasonable 1-to-1 correspondence and can pinpoint errors in particular symbolic functions in practice.

## High-level System Architecture

A new test module adapting the MPS tests [master/test/test_mps.py](https://github.com/pytorch/pytorch/blob/master/test/test_mps.py) will be created for torch.onnx.

The module will contain (1) an allow list for enabling tests (2) skipping mechanism for skipping particular dtype/opset combinations for given ops (3) a mechanism to create models that contains ops provided by OpInfo, that are tracible by the torch.onnx exporter.

The proposed implementation (https://github.com/pytorch/pytorch/pull/86182) demonstrates the minimum effort needed to incrementally enable tests for ops: https://github.com/pytorch/pytorch/pull/86182/files#diff-2b7b872470e6ee3ef37f450f9fade3e23edd211da1e0dcff29405ed1f35025fbR296-R354. As well as the ability it has to detect gaps in the conversion support.

## Alternatives considered

1. Not use OpInfo. Depending on `OpInfo` means when new test samples are added to an OpInfo, there is a potentially for it breaking affected torch.onnx tests. This can make torch.onnx fail more frequently, but we want this behavior to discover gaps and to prevent bc breaking changes. The skip mechanism allows a change to circumvent particular tests.
    - Not using OpInfo however makes it much harder to improve op coverage and correctness, as shown in the torch op support matrix analysis (https://www.justinchuby.com/torch-onnx-op-matrix/). There are too many edge cases to create tests for from scratch. We should avoid this duplication of work.

cc @mruberry

**Comment by ezyang** [comment]
cc @mruberry
