### ISSUE TITLE
[JIT] Don't support torch.tensor/Tensor/FloatTensor in Script

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#8814]
We are unable to use create tensor using torch.tensor/Tensor/FloatTensor, throw unknown builtin op as below:

```
======================================================================
ERROR: test_time_sequence_prediction (__main__.TestEndToEndHybridFrontendModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_jit.py", line 4464, in test_time_sequence_prediction
    self.checkTrace(Sequence(), (torch.rand(97, 999),), verbose=True)
  File "/Users/wanchaol/pytorch/torch/jit/__init__.py", line 558, in init_then_register
    self._create_methods(asts, rcbs)
RuntimeError:
unknown builtin op:
@torch.jit.script_method
def forward(self, input, future):
    outputs = []
    h_t = torch.zeros((97, 51), dtype=torch.double)
    c_t = torch.zeros((97, 51), dtype=torch.double)
    h_t2 = torch.zeros((97, 51), dtype=torch.double)
    c_t2 = torch.zeros((97, 51), dtype=torch.double)

    # outputs2 = torch.tensor([], dtype=torch.double)
    outputs2 = torch.Tensor()
               ~~~~~~~~~~~~ <--- HERE
```

**Comment by apaszke** [comment]
Oh, because the code had the `torch.tensor` line commented out, and an error on `torch.Tensor` I assumed it's the problem only with the latter. If `torch.tensor` is broken too, then we should fix it

**Comment by wanchaol** [comment]
Agree for not supporting legacy ones, torch.tensor is not working as well so I think we should fix that.

**Comment by loopdigga98** [comment]
Hi guys, seems like JIT does not support ```torch.tensor()``` yet. How to deal with it? Do I need to pass all the tensors to function before call?

**Comment by wanchaol** [comment]
@loopdigga98, I believe torch.tensor() is already supported in JIT now, you can try it in 1.0.1 and in pytorch master.

**Comment by loopdigga98** [comment]
@wanchaol thank you i'll give it a try

**Comment by wanchaol** [comment]
Closing this as it is already supported in JIT.
