### ISSUE TITLE
Permute method of Tensor with first-class dims inconsistent with `torch.Tensor.permute`

### ISSUE THREAD

**Issue by tcbegley** [pytorch/pytorch#88187]
### 🐛 Describe the bug

Calling the `permute` method of a tensor with first-class dimensions using the keyword argument `dims` does not match the behaviour of `torch.Tensor`. 

```python
import torch
from functorch.dim import dims

t = torch.rand(2, 3, 4)
# this works
assert t.permute(dims=(1, 0, 2)).shape == t.permute(1, 0, 2).shape

d = dims(1)
t_fc = torch.rand(1, 2, 3, 4)[d]
# this doesn't
assert t_fc.permute(dims=(1, 0, 2)).shape == t_fc.permute(1, 0, 2).shape
```

In fact, calling `permute` with `dims` appears to be a no-op

```python
# this is fine
torch.testing.assert_close(t_fc.permute(dims=(1,0,2))._tensor, t_fc._tensor)

# whereas this raises an AssertionError as expected
torch.testing.assert_close(t_fc.permute(1,0,2)._tensor, t_fc._tensor)
```

Ideally the behaviour would be the same, though even a `TypeError` saying that `permute` has no keyword `dims` would be better than accepting the argument but not doing anything.

CC: @vmoens @zou3519 @ezyang @zdevito 

### Versions

PyTorch version: 1.14.0.dev20221027
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.24.0
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.982
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221027
[pip3] torchaudio==0.14.0.dev20221025
[pip3] torchvision==0.15.0.dev20221026
[conda] cpuonly                   2.0                           0    pytorch-nightly
[conda] numpy                     1.23.4           py39hefdcf20_1    conda-forge
[conda] pytorch-mutex             1.0                         cpu    pytorch-nightly
[conda] torch                     1.14.0.dev20221027          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221025          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221026          pypi_0    pypi

**Comment by samdow** [comment]
triaging since there's no first class dims module and it looks like the relevant people are cc'd

**Comment by ezyang** [comment]
cc @zdevito
