### ISSUE TITLE
`torch.topk` function giving incorect output

### ISSUE THREAD

**Issue by hirwa-nshuti** [pytorch/pytorch#88184]
### 🐛 Describe the bug

I am using `topk` function but at some points, I realized that the function is giving strange results on some given inputs

```python
import torch
x = torch.tensor([-1, -1, -1, -1])
print(torch.topk(x, 1)) # expected torch.return_types.topk(values=tensor([-1]), indices=tensor([3]))

# output from the function
# torch.return_types.topk(values=tensor([-1]), indices=tensor([2]))
```

### Versions

PyTorch version: 1.11.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-1094-azure-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==0.1.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.0
[pip3] torch==1.11.0+cpu
[pip3] torch-scatter==2.0.9
[conda] Could not collect

**Comment by jgong5** [comment]
@hirwa-nshuti May I know why do you expect `indices=tensor([3])` would be returned? The PyTorch doc doesn't specify what indices to return on equivalent values: https://pytorch.org/docs/stable/generated/torch.topk.html.

**Comment by hirwa-nshuti** [comment]
Well, I think as the function is supposed to return the index of the largest value of this input tensor it can keep searching till it reaches the end of the tensor which is 3. It seems that if we take the result from this function it is ending the search at index 2. Taking a simple example of an implementation using numpy I think it can well elaborate the reason why I expected the returned index to be 3

```python
import numpy as np
import torch
x = np.array([-1, -1, -1, -1])
for k in range(1, 5):
    val, index =  x[np.argpartition(x, -k)[-k:]], np.argpartition(x, -k)[-k:]
    print(f"top_val: {val}, Index: {index}")
# output
# top_val: [-1], Index: [3]
# top_val: [-1 -1], Index: [2 3]
# top_val: [-1 -1 -1], Index: [1 2 3]
# top_val: [-1 -1 -1 -1], Index: [0 1 2 3]

# torch.topk
y = torch.topk([-1, -1, -1, -1])
for k in range(1, 5):
    val, index =  torch.topk(y, k)
    print(f"top_val: {val}, Index: {index}")
# output
# top_val: tensor([-1]), Index: tensor([2])
# top_val: tensor([-1, -1]), Index: tensor([2, 3])
# top_val: tensor([-1, -1, -1]), Index: tensor([2, 3, 0])
# top_val: tensor([-1, -1, -1, -1]), Index: tensor([2, 3, 0, 1])

**Comment by hirwa-nshuti** [comment]
Yeah sure a feature that can make it stable can be a good way to go.
Thanks:)

**Comment by min-jean-cho** [comment]
May I know the expected behavior for duplicates of stable topk -- as @nikitaved noted, we can define the expected behavior for duplicates as sort `sort(..., stable=True)` by indices of duplicates such that higher indices have higher priority. For example, the expected behavior with this definition would be:
```
x = torch.tensor([-1, -1, -1, -1])
torch.topk(x, 1, stable=true) #indices=[3]
torch.topk(x, 2, stable=true) #indices=[2, 3]
torch.topk(x, 3, stable=true) #indices=[1, 2, 3]

x = torch.tensor([0, -1, 0, -1])
torch.topk(x, 1, stable=true) #indices=[2]
torch.topk(x, 2, stable=true) #indices=[0, 2]
torch.topk(x, 3, stable=true) #indices=[3, 0, 2]
```

 

Note that `np.argpartition` is also not stable, so we cannot define the expected behavior based on `np.argpartition`.

> It seems that if we take the result from this function it is ending the search at index 2. Taking a simple example of an implementation using numpy I think it can well elaborate the reason why I expected the returned index to be 3

Modifying the below example with `x = np.array([0, -1, 0, -1])` would also output "it is ending the search at index" 0 for k=1 (which isn't the case).
> 
> ```python
> import numpy as np
> import torch
> x = np.array([-1, -1, -1, -1])
> for k in range(1, 5):
>     val, index =  x[np.argpartition(x, -k)[-k:]], np.argpartition(x, -k)[-k:]
>     print(f"top_val: {val}, Index: {index}")
> # output
> # top_val: [-1], Index: [3]
> # top_val: [-1 -1], Index: [2 3]
> # top_val: [-1 -1 -1], Index: [1 2 3]
> # top_val: [-1 -1 -1 -1], Index: [0 1 2 3]
> ```
