### ISSUE TITLE
HUD sometimes doesn't show any/most of the tests

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#88206]
Example: https://hud.pytorch.org/pytorch/pytorch/pull/87424?sha=29236437439cdceb7a006a781eb2e40c4b1a1b97

This page only shows

![Image](https://user-images.githubusercontent.com/4468967/199283889-047a012c-d049-48dd-8074-a51832c9e698.png)

Reporter: @lezcano 

More details:

> I've got this in a couple of my PRs, so it'd be good if anyone could have a look at it.
For context, this PR was part of a stack of more PRs, and this happened after I merged a few of them and then rebased on top of master.

**Comment by clee2000** [comment]
fixed after https://github.com/pytorch/test-infra/pull/996
