### ISSUE TITLE
Improve SSH experience by moving env vars into docker image

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#88236]
cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Not entirely sure i understand the context here?

**Comment by ZainRizvi** [comment]
As per @malfet: In our docker containers, many of the environment variables are set via command line when we're starting the container.  This has the downside that when a user ssh-es into a box, unless they know to set all those env vars, they'll end up accessing a docker container that's a bit different than what the test contained since the env vars don't properly match

By moving the env vars to the image, users ssh-ing into the container (or using the image in a different location) can have a more consistent experience

**Comment by seemethere** [comment]
> As per @malfet: In our docker containers, many of the environment variables are set via command line when we're starting the container. This has the downside that when a user ssh-es into a box, unless they know to set all those env vars, they'll end up accessing a docker container that's a bit different than what the test contained since the env vars don't properly match
> 
> By moving the env vars to the image, users ssh-ing into the container (or using the image in a different location) can have a more consistent experience

Why would the user need the env vars baked into the image? SSH'ing and exec'ing into the running container will give the user the exact environment so a bit confused on what baking the env vars will gain us here

**Comment by ZainRizvi** [comment]
Fair point. @malfet, mind sharing the context you had?

**Comment by ZainRizvi** [comment]
Today people ssh into the machines to access the docker images, so they'll have the environment variables already setup

One day we'd like to have docker images be publicly available for people to download and test locally with all env vars defined, but until this isn't a priority until we try to implement that scenario, so deprioritizing this task

**Comment by qn2060** [comment]
please refer https://github.com/wxwxwwxxx/pytorch_docker_ssh
