### ISSUE TITLE
CUDA runtime error(2) : Out of memory

### ISSUE THREAD

**Issue by thFury** [pytorch/pytorch#8823]
Hello. I have been trying to figure out what is happening.

## Issue description

The python script fails here:
`RuntimeError: cuda runtime error (2) : out of memory at ..\src\THC\THCGeneral.cpp:844`.
I've read from other issues that this is because I am out of memory. Weird. I used the debugger to catch exactly when the code throws the error and then I used `nvidia-smi` to check how much VRAM I had available: 744/4095mb. How could this be?

This is my code (keep in mind that some parts are written badly and don't work, but they are not relevant to the bug report nonetheless, an example of this is the `elif epo == self.num_epochs:` doesn't work properly..)

    def get_input_layer(self, word_idx):

        x = torch.zeros(self.vocab_size).float()
        x[word_idx] = 1.0
        return x`

    def model(self, mode=1):

        
        W1 = Variable(torch.randn(self.embedding_dims, self.vocab_size).cuda().float(), requires_grad=True)
        W2 = Variable(torch.randn(self.vocab_size, self.embedding_dims).cuda().float(), requires_grad=True)

        print('Model Initialized')
        for epo in range(self.num_epochs):
            loss_val = None
            for i_batch, sample_batched in enumerate(self.data_loader):
                loss_val = 0

                x = self.get_input_layer(sample_batched[0].long()).cuda()
                y_true = Variable(torch.from_numpy(np.array(sample_batched[1])).cuda().long())

                z1 = torch.matmul(W1, x)
                z2 = torch.matmul(W2, z1)

                log_softmax = F_nn.log_softmax(z2, dim=0)

                # Loss
                loss = F_nn.nll_loss(log_softmax.view(1,-1), y_true)
                loss_val += loss.item()
                loss.backward()

                # Optimizer

                try:
                    W1.data -= self.learning_rate * W1.grad.data
                except:
                    print(GPUtil.showUtilization(useOldCode=True))
                W2.data -= self.learning_rate * W2.grad.data

                W1.grad.data.zero_()
                W2.grad.data.zero_()
            if epo % 1 == 0:
                print(f'Loss at epo {epo}: {loss_val/len(sample_batched)}')
            elif epo == self.num_epochs:
                print('Training completed. \n Final loss:',loss)
            else:
                print('Completed epoch', epo)`

## System Info
(This is the output of collect_env.py)
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 7 Ultimate
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 970
Nvidia driver version: 385.54
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy (1.14.5)

[pip] torch (0.4.0)
[conda] cuda90                    1.0                           0    pytorch

[conda] pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch

**Comment by yf225** [comment]
Could you share the code for `self.data_loader`? Also does it still OOM if `num_workers` is set to 0 in `DataLoader`?

**Comment by soumith** [comment]
closing the issue while awaiting response.
