### ISSUE TITLE
output_padding constraint

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#8826]
Currently we check that `output_padding < stride || output_padding < dilation`, e.g. [here](https://github.com/pytorch/pytorch/blob/master/aten/src/THCUNN/generic/SpatialFullDilatedConvolution.cu#L19). But the check against `dilation` doesn't quite make sense. Dilation just effectively increases the kernel size, and shouldn't cause any ambiguity in output shape of `conv` (not transpose).

So I propose to change it to only `output_padding < stride`

FWIW, 
```py
>>> # conv doesn't have ambiguity introduced by dilation in output shape
>>> F.conv2d(torch.randn(1, 3, 5, 6), torch.randn(3,3,3,3, dilation=2).shape
torch.Size([1, 3, 1, 2])
>>> F.conv2d(torch.randn(1, 3, 5, 6), torch.randn(3,3,3,3), None, dilation=(1,2)).shape
torch.Size([1, 3, 3, 2])
>>> F.conv2d(torch.randn(1, 3, 5, 6), torch.randn(3,3,3,3), None, dilation=(2,1)).shape
torch.Size([1, 3, 1, 4])
>>> # output shape is fully recover-able just using dialtion
>>> F.conv_transpose2d(torch.randn(1,3,1,2), torch.randn(3,3,3,3), dilation=2).shape
torch.Size([1, 3, 5, 6])
>>> F.conv_transpose2d(torch.randn(1,3,3,2), torch.randn(3,3,3,3), dilation=(1,2)).shape
torch.Size([1, 3, 5, 6])
>>> F.conv_transpose2d(torch.randn(1,3,1,4), torch.randn(3,3,3,3), dilation=(2,1)).shape
torch.Size([1, 3, 5, 6])
```

cc @soumith who made the original change in `torch/nn` repo

**Comment by soumith** [comment]
it's because the underlying kernel (I think one of im2col or col2im that we have) dont support that `output_padding` setting.

**Comment by soumith** [comment]
also see https://github.com/pytorch/pytorch/pull/904

**Comment by soumith** [comment]
I see.
I removed those checks, and handled that case to handle Conv double backward. When Conv with stride > 1, dilation > 1 happens, the double-backward will involve this condition, if I remember.

**Comment by SsnL** [comment]
@soumith makes sense. Thanks for explaining!
