### ISSUE TITLE
[ONNX] Throw _Map_base::at Exception When Exporting Module with torch.utils.checkpoint.checkpoint

### ISSUE THREAD

**Issue by er3x3** [pytorch/pytorch#88286]
### 🐛 Describe the bug

The bug was introduced by PR https://github.com/pytorch/pytorch/pull/74765. When exporting a module with torch.utils.checkpoint.checkpoint, it will throw "RuntimeError: _Map_base::at" exception, which is at [THIS LINE](https://github.com/pytorch/pytorch/blob/95fc0bcaaddc2d24e8759f24dbefa789d04e9e42/torch/csrc/autograd/python_function.cpp#L609). Need to handle such case to avoid exception.

Another suggestion for perf is: in [THIS LINE](https://github.com/pytorch/pytorch/blob/95fc0bcaaddc2d24e8759f24dbefa789d04e9e42/torch/csrc/jit/passes/onnx.cpp#L470), we have code to check if prim::PythonOp is registered Op to skip inlineAutograd accordingly, I think it's better to apply such logic to [HERE](https://github.com/pytorch/pytorch/blob/95fc0bcaaddc2d24e8759f24dbefa789d04e9e42/torch/csrc/autograd/python_function.cpp#L719) and [HERE](https://github.com/pytorch/pytorch/blob/95fc0bcaaddc2d24e8759f24dbefa789d04e9e42/torch/onnx/utils.py#L581) to skip handling the inline logic.

Code to reproduce:
```python
import torch
import io
from torch.utils.checkpoint import checkpoint


class A(torch.nn.Module):
    # A supported module.
    def __init__(self):
        super(A, self).__init__()
        self.l1 = torch.nn.Linear(2, 2)

    def forward(self, x):
        return self.l1(x)


class B(torch.nn.Module):
    # This module is not exportable to ONNX because it
    # uses gradient-checkpointing. However, its two sub-module's
    # are exportable, so ORTModule should be used to compute them.
    def __init__(self):
        super(B, self).__init__()
        self.l1 = torch.nn.Linear(2, 2)
        self.a = A()

    def forward(self, x):
        def custom():
            def custom_forward(x_):
                return self.a(x_)

            return custom_forward

        z = self.l1(checkpoint(custom(), x))
        return z


torch.onnx.export(
    B(),
    (torch.randn(2, 2),),
    io.BytesIO(),
)
```

Get below exception:
```
Traceback (most recent call last):
  File "tmp.py", line 36, in <module>
    torch.onnx.export(
  File "/home/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/anaconda3/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1178, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "tmp.py", line 32, in forward
    z = self.l1(checkpoint(custom(), x))
  File "/home/anaconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
RuntimeError: _Map_base::at
```

### Versions

1.13.0 and above.

Collecting environment information...
PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
Clang version: 15.0.0-++20220616064206+d0e60b6d7ec9-1~exp1~20220616184301.556
CMake version: version 3.24.1
Libc version: glibc-2.27

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-187-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-32GB
GPU 1: Tesla V100-DGXS-32GB
GPU 2: Tesla V100-DGXS-32GB
GPU 3: Tesla V100-DGXS-32GB

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.13.0+cu116
[pip3] torchaudio==0.13.0+cu116
[pip3] torchmetrics==0.7.3
[pip3] torchvision==0.14.0+cu116
[conda] blas                      1.0                         mkl  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.21.5                   pypi_0    pypi
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] torch                     1.13.0.dev20220724+cu113          pypi_0    pypi
[conda] torchaudio                0.13.0+cu116             pypi_0    pypi
[conda] torchmetrics              0.7.3                    pypi_0    pypi
[conda] torchvision               0.14.0+cu116             pypi_0    pypi

**Comment by pengwa** [comment]
Is there any any update on this? @justinchuby  @BowenBao . Is there way to disable the inline since we don't need it but it fails the exports.

**Comment by thiagocrepaldi** [comment]
Have you checked whether removing `_C._jit_pass_onnx_autograd_function_process(graph)` calls from `torch/onnx/utils.py` work?

**Comment by BowenBao** [comment]
> Have you checked whether removing `_C._jit_pass_onnx_autograd_function_process(graph)` calls from `torch/onnx/utils.py` work?

This is not going to work. The error stems from tracer at a much earlier stage. We can try 'try-catch' this and skip inlining.
Both @iK1D 's suggestions are good and on point.

**Comment by thiagocrepaldi** [comment]
@er3x3 retest this with nightly pytorch when you have a chance

**Comment by miayu79** [comment]
hi, I ran into same issue, I tried installing nightly version: pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

but it still doesn't work?
