### ISSUE TITLE
lib/python3.8/site-packages/torch/include/torch/csrc/jit/serialization/export_bytecode.h:11:10: fatal err or: torch/csrc/jit/mobile/function.h: No such file or directory  #include <torch/csrc/jit/mobile/function.h>

### ISSUE THREAD

**Issue by csukuangfj** [pytorch/pytorch#88290]
### 🐛 Describe the bug

This problem exists only in torch 1.12.x.
It works fine for torch 1.11.x and torch 1.13.x

If I use the following code
```cpp
#include "torch/csrc/jit/serialization/import_source.h"
```

It will throw the following errors:
```
In file included from /xxx/lib/python3.8/site-packages/torch/include/torch/csrc/jit/serialization/export.h:6:0
,
                 from /xxx/lib/python3.8/site-packages/torch/include/torch/csrc/jit/serialization/import_source.h:12,
                 from /xxx.cc:31:
/xxx/lib/python3.8/site-packages/torch/include/torch/csrc/jit/serialization/export_bytecode.h:11:10: fatal error: torch/csrc/jit/mobile/function.h: No such file or directory
 #include <torch/csrc/jit/mobile/function.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I checked that there is no such a directory with name
```
lib/python3.8/site-packages/torch/include/torch/csrc/jit/mobile
```

After I manually create it and copy the files from
https://github.com/pytorch/pytorch/tree/v1.12.1
, then everything compiles.

---

You can find more error logs at
https://github.com/k2-fsa/k2/actions/runs/3370757209/jobs/5592081906

<img width="1344" alt="Screen Shot 2022-11-02 at 12 41 05 PM" src="https://user-images.githubusercontent.com/5284924/199399926-229ad872-6eda-4dd5-891a-060ee27681f0.png">

### Versions

1.12.0, 1.12.1

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by malfet** [comment]
Thank you for reporting. We should add smoke test for this, but alas can not do much about 1.12.x releases.
cc: @atalman

**Comment by malfet** [comment]
Let's close this one (as not much can be done about 1.12) and open a new issue to add tests that prevents such regressions in the future
