### ISSUE TITLE
Build CUDA extension in windows 10

### ISSUE THREAD

**Issue by xiaoxiangyeyuwangye** [pytorch/pytorch#8833]
Hello, everyone.
I want to write some pytorch cuda extensions in windows 10. 
I succeed in writing c extensions in these links:
https://pytorch.org/tutorials/advanced/c_extension.html
https://pytorch.org/docs/master/notes/windows.html
I noted that most implementation of cuda extension is based on c extension, which means that python interact with c, and c interact with cuda. 
I know how to use cffi to build pure c extension in windows 10, and I succeed. 
I wonder when I use cffi to build a c extension which has interaction with cuda, does cffi build cuda file (.cu) together? Or the cuda file should be built separately? How to built the cuda file in windows 10?
Another question is: Is there any proper methods to co-debug c and cuda extensions in windows 10? Can IDEs such as Visual Studio do this job?
I am not familiar with cuda programming and debugging , thanks for any suggestion

**Comment by SsnL** [comment]
cc @peterjc123 
also I think the recommended extension methods are c++ extensions by @goldsborough , although I'm not sure if Windows is well supported.

**Comment by goldsborough** [comment]
C++ extensions are well supported on Windows, thanks to @peterjc123. 

@xiaoxiangyeyuwangye please check out https://github.com/pytorch/extension-cpp. C++ extensions are easier, actively maintained and the future.

**Comment by xiaoxiangyeyuwangye** [comment]
@goldsborough @SsnL .Thanks a lot for your suggestions. I will try. It seems that if I use c++ extension, I don't need to compile .cu file separately. If I use c extension with dffi, the .cu file need to be compiled separately and the object file need to be added into ffi extra_objects. Am I right?
