### ISSUE TITLE
DISABLED test_kineto (__main__.TestProfiler)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#88377]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_kineto)).

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb

**Comment by jithunnair-amd** [comment]
> Resolving the issue because the test is not flaky anymore after 1100 reruns without any failures and the issue hasn't been updated in 14 days. Please reopen the issue to re-disable the test if you think this is a false positive

@huydhn Is this not a false positive? I'm seeing many failures for this test in https://www.torch-ci.com/failure/test_kineto even in the CUDA runs:
![image](https://user-images.githubusercontent.com/37884920/234993078-d6206358-3281-481e-a771-400f48c77d44.png)

**Comment by jithunnair-amd** [comment]
FYI @BLOrange-AMD, since he's looking into this unit test from ROCm side, but now I'm wondering if this is a non-ROCm-specific test issue

**Comment by jithunnair-amd** [comment]
> > Resolving the issue because the test is not flaky anymore after 1100 reruns without any failures and the issue hasn't been updated in 14 days. Please reopen the issue to re-disable the test if you think this is a false positive
> 
> @huydhn Is this not a false positive? I'm seeing many failures for this test in https://www.torch-ci.com/failure/test_kineto even in the CUDA runs: ![image](https://user-images.githubusercontent.com/37884920/234993078-d6206358-3281-481e-a771-400f48c77d44.png)

WOW, nvm, the runs in question are from 4/27/**2022** lol. It'd be nice if the webpage included the year as well, threw me for a loop there! Okay, then this looks to be a ROCm-only issue at present, we will debug it and close https://github.com/pytorch/pytorch/issues/100204 when appropriate.

**Comment by huydhn** [comment]
I see that you have created https://github.com/pytorch/pytorch/issues/100204 to track the issue on ROCm, that works too.  So linux and rocm are treated as 2 different platforms on the CI, and you can see that this one only disabled it on Linux.
