### ISSUE TITLE
Summary of inductor issues observed on master

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#88388]
### 🐛 Describe the bug

As we have had inductor tests running in master for a while, here are the list of flaky issues that we have observed on master.  The CUDA GPU flakiness https://github.com/pytorch/pytorch/issues/88352 is not included here because it's related to AWS G5 runner in general, not inductor workflow.

* Fail to build triton wheel
  * https://hud.pytorch.org/pytorch/pytorch/commit/bc03aa6013e101222c9652d04a2b08e48f626dfb
* benchmarks/dynamo/timm_models.py failure with KeyError: 'cubin'
  * https://hud.pytorch.org/pytorch/pytorch/commit/8ef9bda1bf7df84483c593f55e704657887120d6
* benchmarks/dynamo/timm_models.py timeout
  * https://hud.pytorch.org/pytorch/pytorch/commit/0fc7de398636f4b53e6c3fde38b4e48a5ff5b37d
  * https://hud.pytorch.org/pytorch/pytorch/commit/f132c171ac542c8abe8f6bf54befd9f2e14ad9b6
  * https://hud.pytorch.org/pytorch/pytorch/commit/1e2c4a6e0e60dda763b53f00f25ee5c1f1e5233d
* fbnetc_100 model fails
  * https://hud.pytorch.org/pytorch/pytorch/commit/5b75b19f51837e162cc0e5e5757dfd9bef437c67   
* Internal Triton PTX codegen error
  * https://hud.pytorch.org/pytorch/pytorch/commit/7354368fd5a8dec5c9fc26dddf5f7da37f1d2499 
  * https://hud.pytorch.org/pytorch/pytorch/commit/12dd877395a47d4de382b06fda9623da37782226 

Let's try to address them to keep master green

### Versions

Inductor, A10G G5 runner, sm86

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by malfet** [comment]
For triton wheels build, we should reuse pip-wheels when they are available

**Comment by malfet** [comment]
I was able to log into one of the nodes(i-06102403c72371a37) and it feels like we are trying to install a tool old version of a driver there:
```
17667.772615] NVRM: The NVIDIA GPU 0000:00:1e.0 (PCI ID: 10de:2237)
               NVRM: installed in this system is not supported by the
               NVRM: NVIDIA 515.57 driver release.
               NVRM: Please see 'Appendix A - Supported NVIDIA GPU Products'
               NVRM: in this release's README, available on the operating system
               NVRM: specific graphics driver download page at www.nvidia.com.
```

**Comment by huydhn** [comment]
With the new debug log we have when installing NVIDIA driver, it's very easy to spot this in GitHub log itself, i.e. https://github.com/pytorch/pytorch/actions/runs/3387905182/jobs/5629590507.  But I think this is a red herring, the newer driver also fails, i.e. https://ossci-linux.s3.amazonaws.com/nvidia_driver/NVIDIA-Linux-x86_64-515.65.01.run.  I haven't tried anything newer than that.  Also GPU worked fine before the runner got itself into that state

**Comment by malfet** [comment]
``` echo "1" > /sys/bus/pci/devices/0000\:00\:1e.0/reset ``` <- fixes node state

**Comment by malfet** [comment]
Though, it would not work when we have the `nvidia.ko` module loaded and GPU disappears in the middle of the testing

**Comment by clee2000** [comment]
A number of tests fail the cuda memory leak check even though they are not run in parallel but succeed on reruns.  For example in https://github.com/pytorch/pytorch/actions/runs/3481793836/jobs/5823692415, they are

'test_variant_consistency_eager___radd___cuda_complex64'
'test_grad_nn_BatchNorm3d_eval_mode_cuda_float64'
'test_variant_consistency_eager___getitem___cuda_complex64'
'test_variant_consistency_eager_H_cuda_float32'
'test_multiple_device_transfer_nn_AdaptiveAvgPool2d_cuda_float64'
'test_multiple_device_transfer_nn_BatchNorm2d_eval_mode_cuda_float32'
'test_variant_consistency_eager___getitem___cuda_float32'
'test_factory_kwargs_nn_Conv1d_cuda_float32'
'test_factory_kwargs_nn_Bilinear_cuda_float32'
'test_variant_consistency_eager_linalg_cholesky_cuda_float32'
'test_variant_consistency_eager___rmatmul___cuda_float32'
'test_variant_consistency_eager___rmatmul___cuda_complex64'
'test_grad_nn_Bilinear_cuda_float64'
'test_variant_consistency_eager___radd___cuda_float32'
'test_factory_kwargs_nn_BatchNorm3d_eval_mode_cuda_float64'
'test_multiple_device_transfer_nn_AvgPool1d_cuda_float64'
'test_multiple_device_transfer_nn_AvgPool1d_cuda_float32'
'test_forward_nn_AdaptiveAvgPool2d_cuda_float32'
'test_multiple_device_transfer_nn_BatchNorm2d_eval_mode_cuda_float64'
'test_multiple_device_transfer_ao_nn_quantized_MaxPool2d_cuda_float32'

**Comment by eellison** [comment]
Closing, feel free to re-open if still relevant.
