### ISSUE TITLE
pytorch canot initialize cuda

### ISSUE THREAD

**Issue by lilong-epfl** [pytorch/pytorch#8838]
I installed the latest version Pytorch on Nvidia Jetson TX2 develop board. But I got the following error:

File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cannot initialize CUDA without ATen_cuda library

I checked the similar errors, but I didn't found useful answer. 
Any ideas for this problem? Thanks in advance!

**Comment by ezyang** [comment]
Hi! How did you install PyTorch; was it pre-built binaries or build from source? If build from source, how did you compile it?

**Comment by lilong-epfl** [comment]
Hi ezyang,

I built PyTorch from the source code. The command I used to install PyTorch is:

`git submodule update --init
sudo pip install -r requirements.txt
sudo python setup.py install`

Thanks for your reply!

**Comment by lilong-epfl** [comment]
@ezyang 
Hi ezyang,

I built PyTorch from the source code. The command I used to install PyTorch is:

`git submodule update --init`
`sudo pip install -r requirements.txt`
`sudo python setup.py install`

Thanks for your reply!

**Comment by ezyang** [comment]
Does a simple program like `pytorch -c "import torch"` fail this way, or is there a test script that you're using to trigger this? Is it possible to post an abridged version that triggers the error?

Also, does https://github.com/pytorch/pytorch/issues/8856 sound similar to your problem? (The error message is different though.)

**Comment by ezyang** [comment]
Hi @mjc14, how did you instlal Pytorch?

**Comment by OpenaiSeven** [comment]
Hi @ezyang , I have the same problem. I installed Pytorch using pip. But first I installed the cpu version, then I uninstall them by using 'pip uninstall torch torchvision'. It turns out successful. Then I install the gpu version, using  'pip install ll http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-win_amd64.whl' and 'pip install torchvision'. But after all that, I check torch.cuda.is_available(), it is False. And the error message comes when I implement device_gpu = torch.device("cuda") ... save_features_for_models(model_names, train_valid_dataloader, train_valid_dataloader_299, device_gpu, 'train_valid')

**Comment by mjc14** [comment]
@ezyang  i  install from source as the guide line on git.

**Comment by lilong-epfl** [comment]
My problem was solved. In my case, its not the problem of Pytorch, the reason is that I didn't install cuda driver properly.

**Comment by soumith** [comment]
@mjc14 your source install likely didn't detect CUDA. Do you have CUDA installed on your machine?

**Comment by mjc14** [comment]
thank you , it didn't detect CUDA ,i have solved my problem.

**Comment by josephkim583** [comment]
How was the problem solved?

**Comment by fycheng-code** [comment]
> My problem was solved. In my case, its not the problem of Pytorch, the reason is that I didn't install cuda driver properly.

So how did you install it properly?
