### ISSUE TITLE
Support for memory-mapped files

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#884]
In Lua torch tensor constructors accepted filenames, and could use memory mapped files as their data.

[Forum thread](https://discuss.pytorch.org/t/quickly-loading-raw-binary-files/797)

**Comment by vlasenkov** [comment]
This functionality is implemented in the core. Am I right? Here:
https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THStorage.c#L44
So, the only what is needed is to embed it into Python code somewhere?

**Comment by apaszke** [comment]
Yes, you're right. The best way would be to add a `from_file` class method to every storage and tensor type (so you could do e.g. `torch.ByteTensor.from_file('x.wav')`).

**Comment by vlasenkov** [comment]
Could you clarify where are the implementations of different storage and tensor types? Found only base classes. And should `from_file` be added to every storage? Why not to add this method just to the base classes?

**Comment by apaszke** [comment]
The implementation should be analogous to [`form_buffer`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/StorageMethods.cpp#L88-L180)

**Comment by vlasenkov** [comment]
Great, I'm working on it.

**Comment by vlasenkov** [comment]
I've implemented the same API as in [torch7 Storage](https://github.com/torch/torch7/blob/master/doc/storage.md#torchtypestoragefilename--shared--size--sharedmem). But we have different behaviours on OS X and Linux.

- On Linux shared memory file (created with `shm_open`) can be accessed as a regular file (with `open` + `mmap`) at `/dev/shm`
- On OS X there is no alternative to `/dev/shm`. So if I create a shared memory file, I can't access it with ordinary `open`/`mmap` pair.

The same problem exists in Lua Torch7. I think on Mac `from_file` should accept either `shared` or `shared_mem` argument. If both are `True` it is better to raise an error.

**Comment by vlasenkov** [comment]
It seems that with just wrapping `THStorage` proper in memory sharing is impossible on OS X. Signature of the method: `from_buffer(filename, shared, size, shared_mem)`.  On Linux one can do this:
```
s1 = torch.FloatStorage.from_file(filename, True, size, True)
s2 = torch.FloatStorage.from_file('/dev/shm/' + filename, True, size, False)
```
OS X has no anything analogous to '/dev/shm/'. So in order to use in memory sharing:
```
s1 = torch.FloatStorage.from_file(filename, True, size, True)
s2 = torch.FloatStorage.from_file(filename, True, size, True)
```
But this crashes when attempting to unlink the memory twice:
```
del s1
del s2
```
The question is whether to correct `torch/lib`?

**Comment by apaszke** [comment]
No, I think there's no way to do that in `torch/lib`. You need a way to refcount these files, but `THRefcountingMapAllocator` alone doesn't cut it, because if someone kills the process with a `SIGKILL` the files won't be deleted and they will keep consuming RAM. That's why I wrote `libshm` and this is probably what we should use in here.

**Comment by vlasenkov** [comment]
So, I'm implementing `shared_mem` for Linux only. And migration to `libshm` shoud be added as a new issue

**Comment by apaszke** [comment]
But the `del` problem isn't OS X specific right? It's going to happen on Linux too

**Comment by vlasenkov** [comment]
Of course

**Comment by vlasenkov** [comment]
It is unsafe but probably useful feature

**Comment by apaszke** [comment]
Yeah, I'll accept a PR that doesn't use libshm too. It's an advanced feature

**Comment by Santosh-Gupta** [comment]
Is there a way to use `from_file` with numpy memory maps? When I try it says 

TypeError: from_file(): argument 'filename' (position 1) must be str, not numpy.ndarray

Code

```

u_embeddings = nn.Embedding(emb_size, emb_dimension, sparse=True)
u_embeddings.weight.data.uniform_(-initrange, initrange)

ammp = np.memmap('test.mymemmap', dtype='float32', mode='r+', shape=(3500000,256))
indexess = np.random.randint(0,3500000, 65000)
with torch.no_grad():
    u_embeddings.weight.data[indexess] = torch.from_file( ammp[indexess] )

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-28-fc007ecbf3ba> in <module>()
      1 with torch.no_grad():
----> 2     skip_gram_model.u_embeddings.weight.data[indexess] = torch.from_file( ammp[indexess] )

TypeError: from_file(): argument 'filename' (position 1) must be str, not numpy.ndarray
```
