### ISSUE TITLE
Flaky dynamo test_indexing flaky with SIGKILL

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#88413]
### 🐛 Describe the bug

This job starts to be flaky with SIGKILL recently:

* https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=dynamo
* https://hud.pytorch.org/pytorch/pytorch/commit/b013825c7d104dca2c6c11cd985453d8520577f7

### Versions

Dynamo, linux-bionic-py3.7-clang9

cc @seemethere @malfet @pytorch/pytorch-dev-infra @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @mlazos @soumith @yanboliang @anijain2305 @chunyuan-w @Xia-Weiwen @desertfire @ezyang @gchanan @zou3519

**Comment by huydhn** [comment]
From what I see so far, SIGKILL always happens when test_index_put_accumulate_large_tensor_cpu is run. So I have tried to  disable that test in https://github.com/pytorch/pytorch/issues/88472 as an experiment to see if it helps and go from there

**Comment by ZainRizvi** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/118770
