### ISSUE TITLE
Enable AMP for MPS devices

### ISSUE THREAD

**Issue by justusschock** [pytorch/pytorch#88415]
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/issues/78168 States that fp16 support for mps devices in general should be possible, but autocas only works with `cpu` and `cuda` device types. When enabling it manually, on mps it does not show any additional conversions:

```python
>>> torch.set_autocast_enabled(True)
>>> with capture_logs(is_mode=True) as logs, LoggingTensorMode():
...     a = torch.rand(10, 10, dtype=torch.float, device='mps')
...     b = torch.rand(10, 10, dtype=torch.float, device='mps')
...     c = torch.addmm(a, a, b)
>>> for l in logs:
...     print(l)
```

prints the following:
```
$0 = torch._ops.aten.rand.default([10, 10], dtype=torch.float32, device=device(type='mps'), pin_memory=False)
$1 = torch._ops.aten.rand.default([10, 10], dtype=torch.float32, device=device(type='mps'), pin_memory=False)
$2 = torch._ops.aten.addmm.default($0, $0, $1)
```

given the fp16 support, it would be nice to have autocast and amp in general working on MPS devices as well

### Additional context

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev as per our discussion on slack.

**Comment by mhnatiuk** [comment]
Can one do it manually though? Is FP16 even faster on MPS architectures?

**Comment by benjaminhuo** [comment]
To finetune llama2 7B with the Lora approach on my Macbook Pro M2 with 96 GB unified memory, I have to disable fp16 like below:
```shell
        args=transformers.TrainingArguments(
            per_device_train_batch_size=micro_batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            warmup_steps=100,
            num_train_epochs=num_epochs,
            learning_rate=learning_rate,
            fp16=False,
            logging_steps=10,
            optim="adamw_torch",
            evaluation_strategy="steps",
            save_strategy="steps",
            eval_steps=200,
            save_steps=200,
            output_dir=output_dir,
            save_total_limit=3
        )
```

But got OOM finally after training for 45 minutes, @kulinseth the training process will consume less memory using fp16 than fp32 if mps supports fp16, right?

```shell
File "/Users/ben/opt/miniconda3/envs/finetune/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/Users/ben/opt/miniconda3/envs/finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/ben/opt/miniconda3/envs/finetune/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 346, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/Users/ben/opt/miniconda3/envs/finetune/lib/python3.10/site-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
RuntimeError: MPS backend out of memory (MPS allocated: 29.47 GB, other allocations: 92.82 GB, max allowed: 122.40 GB). Tried to allocate 112.50 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).
  7%|██████▎                                                                                      | 212/3125 [45:24<10:23:55, 12.85s/it]
```

**Comment by slashdottir** [comment]
I vote for this issue!

**Comment by kulinseth** [comment]
@benjaminhuo , yes I have a [PR](https://github.com/pytorch/pytorch/pull/99272), which i will need to rebase and refresh again. I will post with the update on it.

**Comment by Datamance** [comment]
Eagerly awaiting this - would love to train on my laptop!

**Comment by sr5434** [comment]
+1

**Comment by galenmarchetti** [comment]
+1

**Comment by Murattut** [comment]
mps is powerful and with float16 it speed up (I even saw 100 percentage) but in many cases , for example use optimiser adam etc. it give Nan, so AMP implementation is become more important

**Comment by mich2k** [comment]
+1 on this

**Comment by DePasqualeOrg** [comment]
Please use reactions instead of commenting "+1". It just adds to the noise for everyone who is subscribed to this issue.

**Comment by bghira** [comment]
it was a pain, but i managed to get pure bf16 training working on an M3 Max using pytorch 2.3 and my own SimpleTuner project.

we get rid of autocast and manage dtypes more strictly as mps requires.

using stochastic rounding bf16 optimizer, you can too get rid of the mixed precision requirement for training many models.

**Comment by eisneim** [comment]
@bghira any link for reference or guide would be appreciated!  👍

**Comment by joanvelja** [comment]
@bghira any heads up on what you did would be great!

**Comment by bghira** [comment]
#120376 is a good starting point for anyone looking for a workaround, with the `adamw-bf16` project on pipy now containing the mps-specific workarounds, eg. swapping pointers before doing the math operations

**Comment by bghira** [comment]
it's worth noting that training on MPS still occasionally hits a NaN in autograd during the backward pass. i haven't dug deeper because it takes >600 very slow training steps to reproduce the issue, and it doesn't occur reliably.

however, restarting training from the last ckpt will go past the point of failure.

**Comment by eisneim** [comment]
@bghira use adamw-bf16 with torch nightly 2.4 on M3 max I got this error:
```
RuntimeError: Expected scalar_type == ScalarType::Float || inputTensor.scalar_type() == ScalarType::Int || scalar_type == ScalarType::Bool to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```
seems like the there are more work need to be done on the model besides `model.to(dtype=torch.bfloat16)`  can you provide a working short example or snippet

**Comment by bghira** [comment]
```sh
git clone https://github.com/AmericanPresidentJimmyCarter/test-torch-bfloat16-vit-training    
cd test-torch-bfloat16-vit-training          
git checkout testing                                            
python main.py --dataset="mnist" --embed_dim=64 --n_attention_heads=4 --n_layers=6 --model_path="models/embed64_layers6" --wandb_run_name="embed64_layers6_bfloat16_alt_test" --precision="bfloat16_alt"
```

**Comment by eisneim** [comment]
@bghira great thanks! your example works

**Comment by janboeye** [comment]
> @benjaminhuo , yes I have a [PR](https://github.com/pytorch/pytorch/pull/99272), which i will need to rebase and refresh again. I will post with the update on it.

hi, @benjaminhuo 

How is this PR progressing? I noticed there are no changes to the MPS backend codes for autocast in this PR. Does this mean the MPS backend is ready for AMP?

Thanks
