### ISSUE TITLE
`torch.load` overwrites `pickle_module` parameter indescriminately

### ISSUE THREAD

**Issue by lopho** [pytorch/pytorch#88438]
### 🐛 Describe the bug

The `pickle_module` parameter of `torch.load` is always overriden with `pickle`.
Minimal example:
```python
import torch
import pickle
class CustomUnpickler(pickle.Unpickler):
    def load(self):
        raise
class CustomPickle:
    Unpickler = CustomUnpickler
torch.save({'nothing', None}, 'test_pickle.pt')
torch.load('test_pickle.pt', pickle_module=CustomPickle)
```
This does not raise, but must, if the custom unpickler is being used.
Specifically commit https://github.com/pytorch/pytorch/pull/86812/commits/895557d25061effa69422ced8ebb520ee986887f in PR https://github.com/pytorch/pytorch/pull/86812 adds the following, which logically always either overwrites `pickle_module=pickle` or raises a `RuntimeError`.
https://github.com/pytorch/pytorch/blob/2bda2baad787923b064c747e619e62a6af969940/torch/serialization.py#L762-L769

### Versions

Collecting environment information...
PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.10.0-18-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A6000
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.0+cu116
[pip3] torchaudio==0.13.0+cu116
[pip3] torchtext==0.14.0
[pip3] torchvision==0.14.0+cu116
[conda] Could not collect

cc @mruberry

**Comment by mikaylagawarecki** [comment]
@malfet Tagging you as you authored the linked commit!

**Comment by lopho** [comment]
fixed by https://github.com/pytorch/pytorch/pull/88570
