### ISSUE TITLE
`Tensor.type` doesn't return the original object when the type is correct on CUDA

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#88493]
### 🐛 Describe the bug

`Tensor.type` doesn't return the original object when the type is correct on CUDA. By contrast, it will return the original tensor on CPU

On CUDA
```py
import torch

tensor1 = torch.randn((1, 3), device='cuda')
tensor2 = tensor1.type('torch.FloatTensor')
torch.nn.init.constant_(tensor2, 2.0)

print(tensor1) 
print(tensor2)
# tensor([[-0.5350, -1.5041,  0.5369]], device='cuda:0')
# tensor([[2., 2., 2.]])
```

On CPU

```
import torch

tensor1 = torch.randn((1, 3))
tensor2 = tensor1.type('torch.FloatTensor')
torch.nn.init.constant_(tensor2, 2.0)

print(tensor1)
print(tensor2)
# tensor([[2., 2., 2.]])
# tensor([[2., 2., 2.]])
```

The `tensor1` and `tensor2` should be the same tensor, which means after in-place operation, they should have the same value. The CPU supports it well but CUDA fails. This behavior is [documented](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html?highlight=tensor+type#torch.Tensor.type)

### Versions

pytorch: 1.13.0
cuda: 11.6

**Comment by fuzzyswan** [comment]
My bad. The `torch.FloatTensor` is different from `torch.cuda.FloatTensor` so this behavior is intended

**Comment by vadimkantorov** [comment]
@ezyang Should tensor.type(...) be deprecated? It seems it's derived from very old LuaTorch era
