### ISSUE TITLE
allow torch.bmm on nested_tensors of dim == 3 or (dim==4 and size(1)==1)

### ISSUE THREAD

**Issue by puririshi98** [pytorch/pytorch#88519]
### 🚀 The feature, motivation and pitch

In the case of 4 dimensions, we should additionally check that the size(1)==1. This is because for us to use torch.bmm for segment_matmul,  we split a tensor of shape   (x, y, z) and we get a list of x tensors w/ shape (1,y, z). If I make a nested tensor out of these and put it into bmm it complains that it 'must be a 3D tensor' from these [checks](https://github.com/cpuhrsch/pytorch/blob/fb10e2f7069943341bd5aa0ccd44d65a41888708/aten/src/ATen/native/nested/cuda/NestedTensorTransformerFunctions.cu#L613-L614)

example:
```
>>> torch.bmm(torch.nested.nested_tensor(list(torch.randn((10,5,5)).split(1))),torch.nested.nested_tensor(list(torch.ran
dn((10,5,5)).split(1))))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: batch1 must be a 3D tensor
```

This is problematic because this is essential for our segment_matmul implementation we want the following behavior:
```
    r"""Performs dense-dense matrix multiplication according to segments along
    the first dimension of :obj:`inputs` as given by :obj:`ptr`, utilizing
    dedicated kernels that effectively parallelize over groups.

    .. code-block:: python

        inputs = torch.randn(8, 16)
        ptr = torch.tensor([0, 5, 8])
        other = torch.randn(2, 16, 32)

        out = pyg_lib.ops.segment_matmul(inputs, ptr, other)
        assert out.size() == (8, 32)
        assert out[0:5] == inputs[0:5] @ other[0]
        assert out[5:8] == inputs[5:8] @ other[1]

    Args:
        input (torch.Tensor): The left operand 2D matrix of shape
            :obj:`[N, K]`.
        ptr (torch.Tensor): Compressed vector of shape :obj:`[B + 1]`, holding
            the boundaries of segments.
        other (torch.Tensor): The right operand 3D tensor of shape
            :obj:`[B, K, M]`.

    Returns:
        torch.Tensor: The 2D output matrix of shape :obj:`[N, M]`.
    """
```

[Here](https://github.com/pyg-team/pyg-lib/pull/137) is the code I am using to allow torch>=1.14 to use torch.bmm instead of our custom kernel:
```
at::Tensor segment_matmul_kernel(const at::Tensor& input,
                                 const at::Tensor& ptr,
                                 const at::Tensor& other) {
  const auto size = pyg::utils::size_from_ptr(ptr).cpu();
  const auto sizes = at::IntArrayRef(size.data_ptr<int64_t>(), size.numel());
#if TORCH_VERSION_MINOR >= 14 or TORCH_VERSION_MAJOR > 1
  auto input_nested = at::_nested_tensor_from_tensor_list(
      input.contiguous().split_with_sizes(/*split_size=*/sizes, /*dim=*/0));
  auto other_nested = at::_nested_tensor_from_tensor_list(
                          other.contiguous().split(/*split_size=*/1, /*dim=*/0))
                          .squeeze(1);
  auto out_nested = at::native::bmm_nested_cuda(input_nested, other_nested);
  auto out = at::cat(out_nested.contiguous().unbind());
#else
  const auto out = input.new_empty({input.size(0), other.size(-1)});
  grouped_matmul_out_kernel(
      input.contiguous().split_with_sizes(/*split_size=*/sizes, /*dim=*/0),
      other.contiguous().split(/*split_size=*/1, /*dim=*/0),
      out.split_with_sizes(/*split_size=*/sizes, /*dim=*/0));
#endif

  return out;
}
```

In the case of torch>=1.14 we trigger a `batch2 must be a 3D tensor` error unless I call `squeeze(1)` on the output `other.contiguous().split(/*split_size=*/1, /*dim=*/0))` . However this is a problem since when the nested tensor consists of many subtensors this slows things down dramatically compared to the torch < 1.14 pathway. This is because our custom grouped_matmul kernel functions even when other has shape (x, 1, y, z). This should be possible for the native implementation too and it would make it feasible for us to use. As you can see from this graph, even though our custom kernel is not faster than torch.bmm we end up with a much slower op using torch 1.14 vs torch < 1.14
![image](https://user-images.githubusercontent.com/20074092/200069190-db092735-b517-4c70-abcb-be7815b4ba31.png)

### Alternatives

I have tried implementing in python and cpp and in both cases using the new method is slower even though our kernel itself is not faster

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by cpuhrsch** [comment]
Hey @puririshi98 - we just landed a shortcut into an optimized bmm via torch.matmul (seehttps://github.com/pytorch/pytorch/pull/86856). Maybe matmul is what you're looking for here?

**Comment by cpuhrsch** [comment]
@puririshi98 - can you share some typical input shapes to `matmul` for your use case (without unsqueeze etc.) or some self-contained, short code in a gist for a microbenchmark that can act as a proxy for development.

**Comment by cpuhrsch** [comment]
@puririshi98 

Instead of 
```
    inputs = torch.randn((num_nodes_per_type * num_types, n_feats)).cuda()
    ptr = torch.tensor(list(range(0, (num_types + 1) * num_nodes_per_type, num_nodes_per_type))).cuda()
    other = torch.randn((num_types, n_feats, out_feats), requires_grad=True).cuda()
    
    for i in range(60):
        if i==10:
            since=time.time()
        pyg_lib.ops.segment_matmul(inputs, ptr, other)
    times.append((time.time()-since)/50.0)
    print("Avg time for", num_types, '=', times[-1])
```
we could look into enabling (I'm making assumptions about what ptr is)
```
    inputs = torch.randn((num_nodes_per_type * num_types, n_feats), device="cuda")
    ptr = list(range(0, (num_types + 1) * num_nodes_per_type, num_nodes_per_type))
    nt = torch.nested.nested_tensor([inputs[ptr[i]:ptr[i+1]] for i in range(len(num_types + 1))])
    other = torch.randn((num_types, n_feats, out_feats), requires_grad=True, device="cuda")

    result = torch.matmul(nt, other) # instead of segment_matmul
```

What do you think about that?

**Comment by puririshi98** [comment]
yes that should be fine

**Comment by cpuhrsch** [comment]
@puririshi98 - It's fine if it's a CPU Tensor. It really just comes down to generating that list of Tensors for the `nested_tensor` constructor.

**Comment by puririshi98** [comment]
okay thats fine then

**Comment by puririshi98** [comment]
this is the code I will use with your new suggested changes:
```
  auto input_nested = at::_nested_tensor_from_tensor_list(
      input.contiguous().split_with_sizes(/*split_size=*/sizes, /*dim=*/0));
  auto out_nested = at::matmul(input_nested, other.contiguous());
  auto out = at::cat(out_nested.contiguous().unbind());
```

I am assuming the output of the matmul will be a nested tensor?

**Comment by cpuhrsch** [comment]
Yep the output is a nestedtensor

**Comment by cpuhrsch** [comment]
@puririshi98 - Your main performance issues are from doing the construction and then unbinding the resulting. Construction and then unbind is very expensive. If you time it without the construction and unbind it'll be much faster and potentially competitive for your use case. This runs on our latest nightly. Note that I'm constructing a NestedTensor from `other` via unbind + nested_tensor.

```
import torch
import time
import os
os.environ['NVIDIA_TF32_OVERRIDE'] = '0'
times = []
num_nodes_per_type = 10000
n_feats = 128
out_feats = 64

def benchmark_torch_function(iters, f, *args, **kwargs):
    f(*args, **kwargs) # warmup
    torch.cuda.synchronize()
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)
    start_event.record()
    for i in range(iters):
        f(*args, **kwargs)
    end_event.record()
    torch.cuda.synchronize()
    return start_event.elapsed_time(end_event)


for num_types in [4, 8, 16, 32, 64, 128, 256, 512, 1024]:
    inputs = torch.randn((num_nodes_per_type * num_types, n_feats)).cuda()
    ptr = list(range(0, (num_types + 1) * num_nodes_per_type, num_nodes_per_type))
    nt = torch.nested.nested_tensor([inputs[ptr[i]:ptr[i+1]] for i in range(len(ptr) - 1)], device='cuda')
    other = torch.randn((num_types, n_feats, out_feats), requires_grad=True).cuda()
    nt_other = torch.nested.nested_tensor(list(other.unbind()), device='cuda')
    time = benchmark_torch_function(1, torch.bmm, nt, nt_other)
    print(f"num_types: {num_types} time: {time}")
```

On a meta note, you could use NestedTensor as your internal representation and thus avoid this costly conversion. You'd also get various other operators as a side effect. However, NestedTensor still is in its prototype phase so there will be some breakages. From a technical perspective however, does that sound doable / interesting?

**Comment by puririshi98** [comment]
```
  auto input_nested = at::_nested_tensor_from_tensor_list(
      input.contiguous().split_with_sizes(/*split_size=*/sizes, /*dim=*/0));
  auto out_nested = at::matmul(input_nested, other.contiguous());
  auto out = at::cat(out_nested.contiguous().unbind());
```
i just attempted to uninstall torch and reinstall the nightly wheel using the above code for my op I get:
`RuntimeError: Expected both to be nested, but got a nested self and non-nested other`
I am assuming this is because your changes aren't in yet. Is there a way to pull these immediately without having to wait until tomorrow?
I use: `pip3 uninstall -y torch; pip3 install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/cu117`

**Comment by cpuhrsch** [comment]
Note that I'm converting `other` to a NestedTensor via ` nt_other = torch.nested.nested_tensor(list(other.unbind()), device='cuda')`

**Comment by puririshi98** [comment]
oh didnt notice that unbinding, thanks it works now
