### ISSUE TITLE
`tensor(1) >> 64` will return 1 on CPU (`64 * n` is magic number) 

### ISSUE THREAD

**Issue by YangChenyuan** [pytorch/pytorch#88547]
### 🐛 Describe the bug

`tensor(1) >> 64` will return 1 on CPU, where `64 * n` is a magic number which means any other value except than `64*n` will return 0.

```py
import torch

cuda_output = torch.bitwise_right_shift(torch.tensor(1).cuda(), 1)
print(cuda_output)

cpu_output = torch.bitwise_right_shift(torch.tensor(1), 64)
print(cpu_output)
```

```
tensor(0, device='cuda:0')
tensor(1)
```

Any value than 64:

```py
for i in range(1, 1000):
    cpu_output = torch.bitwise_right_shift(torch.tensor(1), i)
    if cpu_output != 0:
        print(i, cpu_output)
```

```
64 tensor(1)
128 tensor(1)
192 tensor(1)
256 tensor(1)
320 tensor(1)
384 tensor(1)
448 tensor(1)
512 tensor(1)
576 tensor(1)
640 tensor(1)
704 tensor(1)
768 tensor(1)
832 tensor(1)
896 tensor(1)
960 tensor(1)
```

### Versions

torch: 1.13.0
cuda: 11.6

cc @svekars @carljparker @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by YangChenyuan** [comment]
Besides. `1<<(-1)` will return `-9223372036854775808` on CPU but `0` on CUDA

```py
import torch

a = torch.tensor(1)
cpu_output = torch.bitwise_left_shift(a, -1)
cuda_output = torch.bitwise_left_shift(a.cuda(), -1)

print(cpu_output)
print(cuda_output)
```

```
tensor(-9223372036854775808)
tensor(0, device='cuda:0')
```

**Comment by ZailiWang** [comment]
Thanks Chenyuan for your findings, we are looking into the issue.

**Comment by lezcano** [comment]
Note that shifting by 64 is UB, so the compiler is allowed to return whatever it feels right. See [[here](https://en.cppreference.com/w/cpp/language/operator_arithmetic)]
> In any case, if the value of the right operand is negative or is greater or equal to the number of bits in the promoted left operand, the behavior is undefined. 

Same for the other examples really, you have all the gotchas of these ops in that cppreference link. 

We will not fix this, as that would incur in quite a perf hit.
 
If this is not documented, we should document this.

**Comment by jgong5** [comment]
cc @jingxu10

**Comment by YangChenyuan** [comment]
Hi @lezcano, thanks for your explanation. Maybe it would be better to document this

**Comment by mingfeima** [comment]
close this for now.

**Comment by lezcano** [comment]
I think in some other place we figured it'd be good to fix this, given that, even though it'd incur in a perf hit, this op will very rarely (never?) be the bottle neck of a program.

Let's follow up here https://github.com/pytorch/pytorch/issues/70904
