### ISSUE TITLE
`torch.cumprod` produces `nan` unexpectedly on GPU

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#88556]
### 🐛 Describe the bug

```python
input_data = torch.arange(0, 50, 0.5).cuda()
output_data = torch.cumprod(input_data, dim=0)
print(input_data)
print(output_data)
```

Since there is a `0` in `input_data`, all elements in `output_data` should be `0`, but some of them were `nan`. 

```
tensor([ 0.0000,  0.5000,  1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,
         4.0000,  4.5000,  5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,
         8.0000,  8.5000,  9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000,
        12.0000, 12.5000, 13.0000, 13.5000, 14.0000, 14.5000, 15.0000, 15.5000,
        16.0000, 16.5000, 17.0000, 17.5000, 18.0000, 18.5000, 19.0000, 19.5000,
        20.0000, 20.5000, 21.0000, 21.5000, 22.0000, 22.5000, 23.0000, 23.5000,
        24.0000, 24.5000, 25.0000, 25.5000, 26.0000, 26.5000, 27.0000, 27.5000,
        28.0000, 28.5000, 29.0000, 29.5000, 30.0000, 30.5000, 31.0000, 31.5000,
        32.0000, 32.5000, 33.0000, 33.5000, 34.0000, 34.5000, 35.0000, 35.5000,
        36.0000, 36.5000, 37.0000, 37.5000, 38.0000, 38.5000, 39.0000, 39.5000,
        40.0000, 40.5000, 41.0000, 41.5000, 42.0000, 42.5000, 43.0000, 43.5000,
        44.0000, 44.5000, 45.0000, 45.5000, 46.0000, 46.5000, 47.0000, 47.5000,
        48.0000, 48.5000, 49.0000, 49.5000], device='cuda:0')
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan], device='cuda:0')
```

It looks like the multiplication begins in the front and in the middle of the array in parallel, but lacks handling for overflowed values. 

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.15 (default, Oct 12 2022, 19:14:55) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

cc @ngimel

**Comment by fuzzyswan** [comment]
By the way, this works fine on CPU.

**Comment by lezcano** [comment]
cc @anjali411 as I think she implemented this algorithm.

**Comment by lezcano** [comment]
Couldn't we throw in an if for good measure that would handle this case? If these kernels are memory bound (I don't know if they are) this shouldn't hurt efficiency in most cases.

**Comment by ngimel** [comment]
This would require us to violate IEEE standard and say that `0*inf` is equal to `0`.

**Comment by fuzzyswan** [comment]
@ngimel I think the expected behaviour on CUDA is that the result looks as if produced by CPU, that is, multiplied in sequence. Since CPU will already underflow in the middle of your case, it is reasonable for CUDA to also produce `nan`. 
As to my case, maybe we can add a lightweight check before we add any complexity to correct the result. Since these cases are rare, this will not affect common computations a lot. The algorithm is shown below. 
``` python
output = cumprod_cuda(input)
if output [-1] == nan: # no need to correct if even the last element does not overflow
    find the first nan in output as output[i] # bisect, or use information recorded by intermediate computations
    # strategy 1: fix with serial algorithm
    output[i:n] = output[i-1] * cumprod_cpu(input[i:n])
    # strategy 2: call parallel algorithms recursively until a fixed point is reached
    ...
```
We do not want to violate IEEE 754 anyway, just make sure that CUDA does not cause more troubles than CPU in silence.

**Comment by ngimel** [comment]
>I think the expected behaviour on CUDA is that the result looks as if produced by CPU

There's no expectation for parallel algorithm results to always look like a serial algorithm results.

**Comment by lezcano** [comment]
This may help to understand what to expect and what not to expect  https://pytorch.org/docs/stable/notes/numerical_accuracy.html
In particular (emph mine):
>In modern computers, floating point numbers are represented using IEEE 754 standard. For more details on floating point arithmetics and IEEE 754 standard, please see [Floating point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic) In particular, note that floating point provides limited accuracy (about 7 decimal digits for single precision floating point numbers, about 16 decimal digits for double precision floating point numbers) and that **floating point addition and multiplication are not associative**, so the order of the operations affects the results. Because of this, PyTorch is not guaranteed to produce bitwise identical results for floating point computations that are mathematically identical. **Similarly, bitwise identical results are not guaranteed across PyTorch releases, individual commits, or different platforms. In particular, CPU and GPU results can be different even for bitwise-identical inputs and even after controlling for the sources of randomness.**

Closing as not planned as per https://github.com/pytorch/pytorch/issues/88556#issuecomment-1306229377
