### ISSUE TITLE
How Can I Know Which Convolution Algo Was Used When I Set "torch.backends.cudnn.benchmark = True"?

### ISSUE THREAD

**Issue by HITLCX** [pytorch/pytorch#88567]
### 🚀 The feature, motivation and pitch

It is validated that convolution process can be accelerated in Pytorch by setting "torch.backends.cudnn.benchmark = True".I want to know which convolution algorithm(FFT, Winograd and GEMM)was selected. Moreover, if it is possible to set the convolution algo manually?
I wonder if there is any way to know which convolution algo was used, and how to set the specific algo manually.

cc @csarofeen @ptrblck @xwang233

**Comment by janeyx99** [comment]
Hey @HITLCX, looks like this is related to https://github.com/pytorch/pytorch/issues/18536

**Comment by janeyx99** [comment]
Closing as duplicate--reopen if there are other concerns!
