### ISSUE TITLE
torch.cuda.sparse.FloatTensor is not enabled.

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#8856]
```
import torch

torch.sparse.FloatTensor(
    torch.LongTensor([[0, 1, 2]]),
    torch.FloatTensor([3,4,5]),
    torch.Size([10])).cuda()
```

on master, this fails with:

```
Traceback (most recent call last):
  File "sparse_cuda.py", line 6, in <module>
    torch.Size([10])).cuda()
RuntimeError: torch.cuda.sparse.FloatTensor is not enabled.
```

Workaround: manually initialize cuda (e.g., convert a dense tensor to cuda) before doing it on sparse.

This is almost certainly my fault (due to ATen CPU/CUDA split.)

**Comment by ezyang** [comment]
Please shout if you have this problem, so I can prioritize it accordingly.

**Comment by RLisfun** [comment]
It would be amazing to see this fixed

**Comment by ezyang** [comment]
Your request has been heard.

**Comment by laoreja** [comment]
Based on my experiments, I got error "THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory" when doing `torch.cuda.sparse.FloatTensor(...)` even with very small tensors (the one in the doc example)

**Comment by laoreja** [comment]
I find the problem, on CPU, I follow the example and do not need to specify the size, the CPU version can infer the size; however on GPU, I have to specify the size, otherwise, I got the OOM error

**Comment by qiwulun** [comment]
I have the same problem！

**Comment by ezyang** [comment]
The original bug is fixed on master. @laoreja, if your problem still arises on master, please file a new bug.

**Comment by yuzhe630** [comment]
I met this problem today. And the dense tensor is too large to be init on cuda.

**Comment by sh0416** [comment]
> The original bug is fixed on master. @laoreja, if your problem still arises on master, please file a new bug.

Can I ask you what is problem? I also encounter this problem, but I don't want to use master branch. just use 0.4.1 stable version.

**Comment by sh0416** [comment]
I don't understand what is problem, but my resolution is this.

Don't use .to(device). Use .cuda().

Also, type of indices and values must be cuda() to naturally infer the type of sparse tensor.

**Comment by ezyang** [comment]
Yes, it was because we weren't initializing CUDA on all codepaths that we should have. Basically, if you do some cuda operation before you invoke torch.cuda.sparse.FloatTensor, that will be sufficient to workaround.
