### ISSUE TITLE
cpp_extension CUDA library path hard-coded as "lib64" but may be "lib"

### ISSUE THREAD

**Issue by ar4** [pytorch/pytorch#88581]
### 🐛 Describe the bug

The path to libcudart.so is [hard-coded to be "lib64"](https://github.com/pytorch/pytorch/blob/71fe069d985e97b5947d133f2f2bde9adea01ed7/torch/utils/cpp_extension.py#L1691) when using the "load" and "load_inline" (Ninja) methods for C++ extensions. It may sometimes, however, instead be "lib". This is acknowledged in [the alternative setuptools installation method](https://github.com/pytorch/pytorch/blob/71fe069d985e97b5947d133f2f2bde9adea01ed7/torch/utils/cpp_extension.py#L1171). This will cause loading C++ extensions to fail for those whose libcudart.so is in "lib".

### Versions

N/A

cc @malfet @zou3519

**Comment by albanD** [comment]
Hi,
Thanks for the report. I think it is safe to add both path there. We would accept a PR adding this!

**Comment by spiiph** [comment]
This also happens with `libcublas.so.11` and `libcudnn.so.8` with `torch==1.13.0` when using VirtualEnv environments. The CUDA packages are installed in `<env>/lib`, but `libtorch` tries to load them as dependencies from a relative path, and `torch` is installed in `<env>/lib64`. 

See: https://github.com/pytorch/pytorch/issues/89417#issuecomment-1341838888

**Comment by brentyi** [comment]
FYI looks like this is fixed in #101285!

**Comment by albanD** [comment]
Nice thanks for pointing it out!
