### ISSUE TITLE
`MultiMarginLoss` doesn't check the value of `target` on CUDA

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#88648]
### 🐛 Describe the bug

`MultiMarginLoss` doesn't check the value of `target` on CUDA.

By the [doc](https://pytorch.org/docs/stable/generated/torch.nn.MultiMarginLoss.html) of `MultiMarginLoss`, the value of target should be `0<=v<=C−1`, where the shape of input is `C` or `N,C`. The CPU does check the validity of the value of `target` but CUDA will not and may return a value for some invalid `target`

```py
import torch

torch.manual_seed(420)
input = torch.randn(3, 5, requires_grad=True).cuda()
target = torch.tensor([1, 0, 5]).cuda()

loss = torch.nn.MultiMarginLoss()
output = loss(input, target)

print(output)
# CUDA
# tensor(0.7524, device='cuda:0', grad_fn=<MultiMarginLossBackward0>)
```

By contrast,

```py
import torch

torch.manual_seed(420)
input = torch.randn(3, 5, requires_grad=True)
target = torch.tensor([1, 0, 5])

loss = torch.nn.MultiMarginLoss()
output = loss(input, target)
# CPU
# RuntimeError: target out of range
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.15 (default, Oct 12 2022, 19:14:55) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

cc @ngimel

**Comment by ChaitanyaRS06** [comment]
It no longer gives an output on GPU(MPS) in my case however produces this result
  
   output = loss(input, target)
  File "/opt/anaconda3/envs/itestml/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1740, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/itestml/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1751, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/itestml/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 1577, in forward
    return F.multi_margin_loss(
  File "/opt/anaconda3/envs/itestml/lib/python3.9/site-packages/torch/nn/functional.py", line 4145, in multi_margin_loss
    return torch._C._nn.multi_margin_loss(
NotImplementedError: The operator 'aten::multi_margin_loss' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

**Comment by ngimel** [comment]
Original issue is fixed, open a new one for mps if needed.
