### ISSUE TITLE
distributed.scatter_object_list shows RuntimeError: Tensors must be CUDA and dense

### ISSUE THREAD

**Issue by LukeLIN-web** [pytorch/pytorch#88685]
### 📚 The doc issue

I tried  https://pytorch.org/docs/stable/distributed.html#torch.distributed.scatter_object_list codes 
```python
def run(rank, world_size, data,  dataset):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    dist.init_process_group('nccl',  rank=rank, world_size=world_size)

    torch.cuda.set_device(rank)

    if rank == 0 :
        objects = ["foo", 12, {1: 2}] # any picklable object
    else:
        objects = [None, None, None]
    objects =objects
    outputlist = [None]
    dist.scatter_object_list(outputlist, objects, src=0)
    print(outputlist)


if __name__ == '__main__':
    dataset = Reddit('/data/Reddit')
    world_size = torch.cuda.device_count()
    data = dataset[0]

    print('Let\'s use', world_size, 'GPUs!')
    data_split = (data.train_mask, data.val_mask, data.test_mask)
    mp.spawn(
        run,
        args=(world_size, data, dataset),
        nprocs=world_size,
        join=True
    )
```

But it shows:
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
    dist.scatter_object_list(outputlist, objects, src=0)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1919, in scatter_object_list
    broadcast(max_tensor_size, src=src, group=group)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1159, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: Tensors must be CUDA and dense

I have 3 GPUs, 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by LukeLIN-web** [comment]
I think it is because the NCCL doesn't support scatter op, I tried broadcast and success.
```
def run(rank, world_size, data,  dataset):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    dist.init_process_group('nccl',  rank=rank, world_size=world_size)

    torch.cuda.set_device(rank)

    if rank == 0 :
        objects = ["foo", 12, {1: 2}] # any picklable object
    else:
        objects = [None, None, None]
    
    # Note: Process group initialization omitted on each rank.
    if dist.get_rank() == 0:
        # Assumes world_size of 3.
        objects = ["foo", 12, {1: 2}] # any picklable object
    else:
        objects = [None, None, None]
    dist.broadcast_object_list(objects, src=0)
    print(objects)
```

**Comment by fduwjj** [comment]
Looks like this is expected. Closed it for now. Feel free to reopen it if this is still an issue. Thanks!
