### ISSUE TITLE
DISABLED test_dispatch_meta_outplace_fft_fft_cuda_float64 (__main__.TestMetaCUDA)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#88692]
This test appears to be intermittently segfaulting. See: https://hud.pytorch.org/failure/RuntimeError%3A%20test_meta%20failed

Examples:
- https://github.com/pytorch/pytorch/actions/runs/3422286124/jobs/5699855677
- https://github.com/pytorch/pytorch/actions/runs/3422172113/jobs/5699549575
- https://github.com/pytorch/pytorch/actions/runs/3421764896/jobs/5698679974

cc @ezyang @gchanan @zou3519 @eellison @bdhirsh @soumith

**Comment by suo** [comment]
@ezyang do you know who can look into this? It's actually not just this dtype that is segfaulting, here's another example: https://github.com/pytorch/pytorch/actions/runs/3468064625/jobs/5793726884

**Comment by ezyang** [comment]
it might be related to https://github.com/pytorch/pytorch/issues/88985

**Comment by ezyang** [comment]
cc @peterbell10

**Comment by ezyang** [comment]
the segfault is in cufft, so it's unlikely to be a meta tensor problem specifically
