### ISSUE TITLE
set_num_threads results in different calculation results

### ISSUE THREAD

**Issue by mx781** [pytorch/pytorch#88718]
### 🐛 Describe the bug

Hi! When changing the intraop parallelism thread count with `torch.set_num_threads`, the results of a simple `Linear()` call are different:

```python
import torch

size_in = 56  # the sizes here matter - these were the lowest ones that triggered the error, but many higher values also work
size_out = 444

layer = torch.nn.Linear(size_in, size_out)
t = torch.randn(size_in)

torch.set_num_threads(1)
out1 = layer(t)

torch.set_num_threads(6)
out2 = layer(t)

(out1 == out2).all(), abs(out1 - out2).max()
```

Example output:
```python
(tensor(False), tensor(5.9605e-08, grad_fn=<MaxBackward1>))
```

Is this expected? If so, it feels like worth a note in the docs for this function, and maybe under [Reproducbility](https://pytorch.org/docs/stable/notes/randomness.html) as well? The trip-up for me was that seeding + `torch.use_deterministic_algorithms` would seem sufficient for deterministic results, but calls to `set_num_threads` will change behavior, e.g. if called in asynchronous code where call time may be before/after certain ops. Happy to add a doc PR if this is expected and the proposal seems sensible.

Thanks for all your work on pytorch!

### Versions

```
PyTorch version: 1.12.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.1 (default, Feb  5 2021, 10:53:09)  [GCC 10.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: Quadro T1000
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] geotorch==0.2.0
[pip3] mypy==0.971
[pip3] mypy-boto3-ec2==1.17.41.0
[pip3] mypy-boto3-s3==1.17.41.0
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] numpy-quaternion==2022.2.10.14.20.39
[pip3] pytorch-lightning==1.2.6
[pip3] torch==1.12.0
[pip3] torchmetrics==0.7.0
[pip3] torchvision==0.13.0
[conda] Could not collect
```

cc @svekars @carljparker @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by albanD** [comment]
I think the reproducibility Note would be a good place to emphasize that all the discussion there is ONLY when using the exact same stack (CPU, GPU, lib versions) and configs (CPU num threads, enabled numerical libs like cudnn, etc)

**Comment by mx781** [comment]
@albanD what other configs are there that change behavior in this way? I'll try collate a full list to add to the docs then

**Comment by albanD** [comment]
Hi,

Unfortunately getting the list of everything that may change this is hard.
Flipping the question around, any thing that does the following might change the result:
- Use ops that are not deterministic to begin with https://pytorch.org/docs/stable/notes/randomness.html
- Change the computation that is actually done (different lib version, different hardware, different hardware flag (on cuda for example: tf32, tensorcore usage, cudnn benchmark, etc), ...)
- Change the order of computation (different parallelization, other users using the hardware, lib version, ...)
- Change the vectorization (different availability flag (at compile time or runtime), different close values, ...)

**Comment by mingfeima** [comment]
for float32, `1e-8` difference is tolerated. Actually, `nn.Linear` will eventually call into MKL on CPU, so the difference comes from MKL.
