### ISSUE TITLE
scatter_ op convert onnx exception

### ISSUE THREAD

**Issue by cqray1990** [pytorch/pytorch#88732]
### 🐛 Describe the bug

```python
input_char = torch.LongTensor(batch_size).fill_(0).to(device) 
def _char_to_onehot(self, input_char, onehot_dim=38):
        input_char = input_char.unsqueeze(1)
        batch_size = input_char.size(0)
        one_hot = torch.FloatTensor(batch_size, onehot_dim).zero_().to(device)
        one_hot = one_hot.scatter_(1, input_char, 1)
        return one_hot
```

when scatter_ op convert to onnx,,it can convert success,but then run onnx with onnxruntime.InferenceSession(ModelPath)

errors:
failed:Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(int64) in node (ScatterElements_53).

why it hints different types

### Versions

pytorch 1.6 gpu
onnx 1.8
onnxruntime 1.6 cpu

**Comment by AllenTiTaiWang** [comment]
Hi @cqray1990,

Could you try with nightly PyTorch, because the version you are using is pretty old, and this might be fixed already. And if that doesn't work, could you provide a self-contained reproducible code for us to dig into? Thanks!

**Comment by thiagocrepaldi** [comment]
Closing as there is no response from op for a long time
