### ISSUE TITLE
[Inductor] invalid argument from running resnet18 with torchbench.py

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#88734]
### 🐛 Describe the bug

The following error occurred when running resnet18 with inductor on the latest main:
```
 python benchmarks/dynamo/torchbench.py --only resnet18 --backend inductor --performance
cuda eval  resnet18                           ERROR:common:Failed for dynamo Triton Error [CUDA]: invalid argument
Traceback (most recent call last):
  File "/home/ubuntu/pytorch/benchmarks/dynamo/common.py", line 1160, in warmup
    fn(model, example_inputs)
  File "/home/ubuntu/pytorch/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "benchmarks/dynamo/torchbench.py", line 328, in forward_pass
    def forward_pass(self, mod, inputs, collect_outputs=True):
  File "/home/ubuntu/pytorch/torch/_dynamo/eval_frame.py", line 169, in _fn
    return fn(*args, **kwargs)
  File "/home/ubuntu/pytorch/functorch/_src/aot_autograd.py", line 951, in forward
    return compiled_f(
  File "/home/ubuntu/pytorch/functorch/_src/aot_autograd.py", line 942, in new_func
    return compiled_fn(args)
  File "/home/ubuntu/pytorch/functorch/_src/aot_autograd.py", line 390, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "/home/ubuntu/pytorch/functorch/_src/aot_autograd.py", line 346, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/home/ubuntu/pytorch/torch/_inductor/compile_fx.py", line 185, in run
    return model(new_inputs)
  File "/home/ubuntu/pytorch/torch/_inductor/compile_fx.py", line 202, in run
    compiled_fn = cudagraphify_impl(model, new_inputs, static_input_idxs)
  File "/home/ubuntu/pytorch/torch/_inductor/compile_fx.py", line 257, in cudagraphify_impl
    model(list(static_inputs))
  File "/tmp/torchinductor_ubuntu/2v/c2vobwskk6juajenb5fwkvswijg7tnweqyk62a5u7w6bcqougeex.py", line 846, in call
    kernel3.run(buf8, arg68_1, arg69_1, arg7_1, arg8_1, buf2, 1605632, grid=grid(1605632), stream=stream0)
  File "/home/ubuntu/pytorch/torch/_inductor/triton_ops/autotune.py", line 176, in run
    result = launcher(
  File "<string>", line 4, in launcher
RuntimeError: Triton Error [CUDA]: invalid argument
```

My repro:
```
python benchmarks/dynamo/torchbench.py --only resnet18 --backend inductor -dcuda --performance
```

cc: @jansel @Chillee 

### Versions

PyTorch version: 1.14.0a0+git652af5e
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Oct 21 2022, 23:50:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1019-aws-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] pytorch-transformers==1.2.0
[pip3] torch==1.14.0a0+git652af5e
[pip3] torch-struct==0.5
[pip3] torchaudio==0.13.0.dev20220914+cu113
[pip3] torchmetrics==0.10.2
[pip3] torchrec-nightly==2022.11.8
[pip3] torchtext==0.14.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.14.0
[pip3] torchx==0.3.0
[pip3] types-mypy-extensions==0.4.24
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] torch                     1.14.0a0+git652af5e          pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220914+cu113          pypi_0    pypi
[conda] torchmetrics              0.10.2                   pypi_0    pypi
[conda] torchrec-nightly          2022.11.8                pypi_0    pypi
[conda] torchtext                 0.14.0                   pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi
[conda] torchx                    0.3.0                    pypi_0    pypi

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by desertfire** [comment]
@eellison , you have hit the problem in the past. How did you solve it?

**Comment by shingjan** [comment]
@desertfire Thanks for the response. Thanks to @xuzhao9, now there is a workaround to run the `torchbench.py` with pytorch nightly. Also the above seems to be a problem with CUDA version mismatch between cuda toolkit and pytorch. I don't have any further context but can confirm this error persists with cuda 11.6 and 11.7 with minimal pytorch setup like the following:
```
onda create -n torch python=3.8
conda activate torch
conda install -y git-lfs
conda install -y -c pytorch magma-cuda116
pip install --pre torch torchvision torchtext torchaudio -f https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html
cd $PYTORCH
python setup.py develop
conda install pyyaml pandas scipy psutil
make triton
```

**Comment by shingjan** [comment]
For my case, this error is caused by cuda version mismatch between building pytorch from source and installing other pytorch dependencies, e.g. torchvision/audio/text from nightly builds. As pointed out by torchbenchmark [here](https://github.com/pytorch/benchmark#building-from-source), `when building PyTorch from source, torchtext and torchvision must also be built from source to make sure the C APIs match`. In my case it also helps making sure the cuda versions match.
