### ISSUE TITLE
torch.CharStorage cause abort when called with torch.save

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#88793]
### 🐛 Describe the bug

`torch.CharStorage` causes abort when called with `torch.save`.
```
import torch
input_data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
storage = torch.CharStorage(input_data)
torch.save(input_data, storage)
```
```
......
AttributeError: 'torch.CharStorage' object has no attribute 'flush'
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  AttributeError: 'torch.CharStorage' object has no attribute 'write'
abort
```
This issue is reproducible on torch 1.11.0+cu113 and 1.14.0.dev20221031, but not reproducible on 1.12.1+cu113 (will raise an exception instead of crashes). Therefore this seems like a regression bug.

### Versions

torch 1.14.0.dev20221031

cc @mruberry

**Comment by albanD** [comment]
cc @ezyang @vfdev-5

**Comment by ezyang** [comment]
cc @kurtamohler

**Comment by fuzzyswan** [comment]
I found there is another similar crash bug related to numpy array serialization:
```
import torch
import numpy as np
x = torch.randint(10, (3, 3), dtype=torch.float)
torch.save(x.cpu().numpy(), x.cpu().numpy())
```
Outputs on pytorch 1.12.1:
```
AttributeError: 'numpy.ndarray' object has no attribute 'flush'
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  AttributeError: 'numpy.ndarray' object has no attribute 'write'
abort (core dumped)
```
Dumping numpy arrays will result in abort crash on pytorch 1.11.0 and 1.12.1, but will raise an normal `AttributeError` on nightly (1.14.0.dev20221031).

I think such serialization bugs should be resolved in a unified way.

**Comment by kurtamohler** [comment]
Per the PyTorch docs, the second argument of `torch.save` is supposed to be a file-like object: https://pytorch.org/docs/stable/generated/torch.save.html?highlight=torch+save#torch.save

Are storages and ndarrays really meant to be file-like objects? Maybe the answer is yes, I just wanted to confirm before investigating further
