### ISSUE TITLE
`median` INTERNAL ASSERT FAILED with `dims < 25` on CUDA

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#88808]
### 🐛 Describe the bug

`median` INTERNAL ASSERT FAILED with `dims < 25` on CUDA. By contrast, it works well on cpu

```py
import torch
import numpy as np

input_data = torch.Tensor(np.random.uniform(size=(2, 3))).cuda()
output = torch.tensor([[[[[[[[[[[[[[[[[[[[[[[[2.3200, 4.1619, 4.2059],
                              [3.3720, 2.7839, 3.6389]]]]]]]]]]]]]]]]]]]]]]]],device='cuda:0')
input = torch.tensor([[[[[[[[[[[[[[[[[[[[[[[[[   float('nan'),    float('nan'),    float('nan')],
                               [   float('nan'),    float('nan'), 0.6918]]]]]]]]]]]]]]]]]]]]]]]]],device='cuda:0')
output = torch.mean(torch.abs((output - input)), dim=(- 1), keepdim=True)
output = torch.mean(torch.abs((output - input_data)), dim=(- 1), keepdim=True)
output = torch.mean(torch.abs((output - torch.min(output))), dim=(- 1), keepdim=True)
output = torch.median(output, dim=(- 1))
```

```
RuntimeError: dims < 25 INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1666249970276/work/aten/src/ATen/cuda/detail/TensorInfo.cuh":53, please report a bug to PyTorch
```

### Versions

torch: 1.13.0
cuda: 11.6

cc @ngimel

**Comment by albanD** [comment]
Hi,

This is expected behavior and CUDA Tensors cannot have more than 25 dimensions.
We should update that error message to not be an internal assert though

**Comment by cnemri** [comment]
Hi , I've made a pull request that hopefully solves the issue. As this behaviour is expected, I've replaced AT_ASSERT by `TORCH_CHECK(dims < MAX_TENSORINFO_DIMS, "CUDA Tensors cannot have more than ", toString(MAX_TENSORINFO_DIMS), " dimensions")`

I am new to open-source contribution. Any help is more than welcome.
