### ISSUE TITLE
torch.load is slow for CUDA models with _use_new_zipfile_serialization=True

### ISSUE THREAD

**Issue by mlucy** [pytorch/pytorch#88834]
### 🐛 Describe the bug

Hi,

I have a small model (~100KB on disk).  When I construct the model with `device='cuda'`, torch.save it, and torch.load it in another process, it's very slow.  (Unfortunately I can't share the model, but if you're unable to reproduce I can try to make an example one.)

The problem seems to specifically be caused by the `_use_new_zipfile_serialization` flag defaulting to `True`.  I get the following load times when loading the model:

```
Device  zipfile  time (sec)
CUDA    False    1.116
CUDA    True     9.923
CPU     False    0.054
CPU     True     0.003
```

10 seconds is also how long it takes to load the model on CPU and call `.to('cuda')` on it.  (Which is also odd, but probably a separate issue.)

I suspect the new zipfile serialization logic is doing something much less efficient when loading onto the GPU.

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Oct  7 2022, 20:19:58) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.971
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.11.0+cu113
[conda] numpy                     1.21.2                   pypi_0    pypi
[conda] torch                     1.11.0+cu113             pypi_0    pypi

**Comment by mlucy** [comment]
Also possibly relevant: for some reason this is only true the first time I load the model after process startup.  If I load it again in the same process, it's much faster.

**Comment by mlucy** [comment]
It turns out this was a non-issue, CUDA initialization was being very slow on our box for unrelated reasons, and for some reason the new loading code was waiting for CUDA initialization while the old code wasn't.  This isn't actually a problem since we can't do anything until CUDA is done initializing anyway.

Sorry for the issue spam.

**Comment by malfet** [comment]
@mlucy I don't see how it could be possible, as you need to initialize code in order to load weighs on GPU

**Comment by mlucy** [comment]
@malfet I'm not sure.  Empirically the `torch.load(cuda_model_file_safed_with_zipfile_serialization_false)` was able to return in about a second even on the first run after process startup, and CUDA initialization is taking longer than that on this machine.  (e.g. running `torch.randn(1, device='cuda')` takes longer than a second if it's the first line I run).  I'm not sure how that could actually be implemented under the hood.
