### ISSUE TITLE
DISABLED test_embedding_dense_backward (__main__.TestNLLLoss)

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#88840]
Platforms: mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_embedding_dense_backward%2CTestNLLLoss)).

**Comment by soumith** [comment]
wait, did you re-enable this test (and that's why you closed the task)?
Seems like a pretty important test.

**Comment by suo** [comment]
This was affecting MPS only, so I disabled the MPS test manually here: https://github.com/pytorch/pytorch/pull/88841.

Issue tracking the flakiness: https://github.com/pytorch/pytorch/issues/88679
