### ISSUE TITLE
On CPU-only machine received OSError from importing: libcublas.so.11: cannot open shared object file

### ISSUE THREAD

**Issue by weiliw-amz** [pytorch/pytorch#88869]
### 🐛 Describe the bug

On a CPU-only machine, in Amazon Linux 2 latest docker image, install latest PyTorch(1.13) via pip and import, received this error.
However in my sense, PyTorch should not install GPU related components on a CPU-only machine without CUDA and nvidia related package installed?

Steps to reproduce:
```
docker pull amazonlinux:2
docker run --rm -it amazonlinux:2 /bin/bash

bash-4.2# yum install -y python3 python3-devel python3-distutils
bash-4.2# python3 -m pip install torch
bash-4.2# python3 -c "import torch"
```
Then get error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/usr/local/lib64/python3.7/site-packages/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib64/python3.7/ctypes/__init__.py", line 359, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.11: cannot open shared object file: No such file or directory
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Amazon Linux 2 (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.2.5

Python version: 3.7.10 (default, Jun  3 2021, 00:02:01)  [GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] (64-bit runtime)
Python platform: Linux-5.4.214-134.408.amzn2int.x86_64-x86_64-with-glibc2.2.5
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] torch==1.13.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by malfet** [comment]
Can you please share entire output of `pip install` command?

**Comment by malfet** [comment]
@weiliw-amz but to unblock yourself, please consider installing a CPU-only version of pytorch, by running `python3 -m pip  install torch  --extra-index-url https://download.pytorch.org/whl/cpu`

**Comment by seemethere** [comment]
Interestingly enough, I can reproduce this with the `amazonlinux:2` image but can't reproduce this with `python:3.7`.

I wonder what makes the `amazonlinux:2` image so different in this case

**Comment by malfet** [comment]
@seemethere I guess `amazonlinux:2` is sort of a multiarch distro (i.e. supporting 32-bit and 64-bit applications)

**Comment by atalman** [comment]
@syed-ahmed @ptrblck Any recommendations on how deal with this issue ?

**Comment by malfet** [comment]
We should just set LD_LIBRARY_PATH to `sysconfig.get_paths()['purelib '] / 'nv-xyz' / 'lib'` in `torch/__init__.py` similar to how it is done  in ./backends/cudnn/__init__.py

**Comment by malfet** [comment]
It could be done, but I think will take as a while. Something like that would fix the problem and seem like a much less intrusive change that modifying the package location:
```
    try:
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
    except OSError as e:
        ctypes.CDLL("/usr/local/lib/python3.7/site-packages/nvidia/cublas/lib/libcublas.so.11")
        ctypes.CDLL("/usr/local/lib/python3.7/site-packages/nvidia/cudnn/lib/libcudnn.so.8")
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)

```
