### ISSUE TITLE
No PyTorch 1.13 builds for Android

### ISSUE THREAD

**Issue by TimPushkin** [pytorch/pytorch#88878]
PyTorch 1.13 was released half a month ago, but no official 1.13 builds have been published for Android. Will there be any?

**Comment by TimPushkin** [comment]
Any updates on this?

**Comment by malfet** [comment]
As far as I know there are no plans to publish mobile builds for 1.13 at the moment. But CI works, and I assume building from source as well.

**Comment by TimPushkin** [comment]
Seems like it is now available: https://repo1.maven.org/maven2/org/pytorch/pytorch_android/1.13.0/
