### ISSUE TITLE
torch\utils\cpp_extension.py should be fixed

### ISSUE THREAD

**Issue by wanjunling168** [pytorch/pytorch#88873]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

torch\utils\cpp_extension.py should be fixed or ninja compile will fail.

torch\utils\cpp_extension.py L1620:
```
if CUDNN_HOME is not None:
                extra_ldflags.append(os.path.join(CUDNN_HOME, 'lib/x64'))
```
obviously it cannot be used by ninja since it's a directory and there is no `/LIBPATH:` before the path
fix here:
```
if CUDNN_HOME is not None:
                extra_ldflags.append(f"/LIBPATH:{os.path.join(CUDNN_HOME, 'lib/x64')}")
```

## Code example
[I hack megatron.fused_kernels.__init__ to compile ahead of loading args, just remove args and let those if-clause=true]
```
import megatron.fused_kernels
megatron.fused_kernels.load()
```

## System Info

- PyTorch or Caffe2: `Pytorch`
- How you installed PyTorch (conda, pip, source): `conda`
- OS: `Windows 10`
- PyTorch version: `1.12.1`
- Python version: `3.9.13`
- CUDA/cuDNN version: `11.6 / 8.4.1.50`
- CMake version: `3.24.3`
- Versions of any other relevant libraries: `ninja==1.10.2`

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @malfet @zou3519

**Comment by malfet** [comment]
Thank you very much for reporting the issue
