### ISSUE TITLE
`bmm` 5x slower on Maxwell (for some sizes)

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#889]
Here's a semi-minimal repro script:

```
import torch
from torch.autograd import Variable
import time

mr = Variable(torch.cuda.FloatTensor(8192, 9, 4), requires_grad=True)
lu = Variable(torch.cuda.FloatTensor(8192, 4, 1), requires_grad=True)
s = time.time()
for i in range(300):
    u = torch.bmm(mr, lu)
    u.sum().backward()
print(time.time() - s)
```

Run this with `CUDA_LAUNCH_BLOCKING=1`, it takes 0.6s on Kepler and 3.0s on Maxwell. If you run in nvprof you'll see that Kepler routes `cublasSgemmBatched` to these faster kernels:

```
==3865486== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 53.35%  76.054ms       600  126.76us  122.82us  130.88us  void fermiPlusSgemmLDS64_batched<bool=0, bool=0, int=4, int=4, int=4, int=3, int=3, bool=1, bool=0>(float**, float**, float**, float*, float const *, float const *, int, int, int, int, int, int, __int64, __int64, __int64, float const *, float const *, float, float, int)
 26.38%  37.610ms       300  125.37us  124.93us  127.26us  void fermiPlusSgemmLDS64_batched<bool=1, bool=0, int=4, int=4, int=4, int=3, int=3, bool=1, bool=0>(float**, float**, float**, float*, float const *, float const *, int, int, int, int, int, int, __int64, __int64, __int64, float const *, float const *, float, float, int)
```

whereas Maxwell uses these slow Maxwell-specific kernels:

```
==1234091== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 67.67%  1.66077s       600  2.7679ms  2.5584ms  3.4175ms  maxwell_sgemmBatched_128x128_raggedMn_nn
 31.57%  774.71ms       300  2.5824ms  2.5525ms  3.1564ms  maxwell_sgemmBatched_128x128_raggedMn_tn
```

Not sure how to proceed. @colesbury @soumith 

cc @VitalyFedyunin @ngimel

**Comment by adamlerer** [comment]
Yeah, it looks like the Maxwell kernels are specifically slow for batches of very small `sgemm`s. For larger size, e.g. `1000x1000`, Kepler and Maxwell are about equally fast.

@ngimel who is the right person to talk to about cublas?

**Comment by soumith** [comment]
can you write a faster `bmm` this weekend please (just kidding).

**Comment by ngimel** [comment]
I've passed it to cublas team, but as you know, cublas releases are few and far between. We'll see if there's a workaround that can be applied in the meantime.

**Comment by wickedfoo** [comment]
I talked with Adam, a batched gemv and a batched dot might fulfill his needs as well, and those aren't hard to write.

**Comment by ngimel** [comment]
Probably magma's magma_sgemm_batched will be about  as good as kepler's version, but it's a bit of a pain to integrate. The API is the same as cublasSgemmBatched, but it also requires magma_queue_t parameter, which is currently not created and maintained in THC state.

**Comment by adamlerer** [comment]
For my particular purpose since the outer dimensions are so small (the inner dimension might be big), it will likely be fast enough to just do an expand, cmul, and sum.

Hopefully nobody else needs to do batched small MMs on Maxwell.

**Comment by adamlerer** [comment]
Yes, the `cmul` version is much faster on Maxwell. (only for my specific case because I'm really doing a batched mv).

```
                    bmm          cmul
Kepler           0.7              0.7          
Maxwell        2.7              0.3
```

Here's the benchmarking code if interested:

```
import torch
from torch.autograd import Variable
import time

bs = 8192
A = Variable(torch.rand(bs, 9, 4).cuda(), requires_grad=True)
B = Variable(torch.rand(bs, 4, 1).cuda(), requires_grad=True)

s = time.time()
for i in range(300):
    u = torch.bmm(A, B)
    u.sum().backward()
torch.cuda.synchronize()
print('bmm', bs, time.time() - s, u.data.norm())

s = time.time()
for i in range(300):
    Bt = B.transpose(1, 2).expand_as(A)
    u = (A * Bt).sum(2)
    u.sum().backward()
torch.cuda.synchronize()
print('cmul', bs, time.time() - s, u.data.norm())
```

**Comment by vince62s** [comment]
Hi @adamlerer 
was your conclusion Maxwell vs Kepler based on the exact same config in terms of Nvidia Driver + cuda toolkit + cudnn ?
We saw a similar issue with cuda version > 8.0.27 (ie working fine with 8.0.27 and much slower with >= 8.0.44) on a Pascal hardware.
Just curious.

**Comment by ngimel** [comment]
Awesome bmm kernels (unfortunately, only work for multiple-of-16 m,n)
https://github.com/burcer/cuda-gpu-kernels
