### ISSUE TITLE
Make 'hann' the default window in torch.stft

### ISSUE THREAD

**Issue by egrinstein** [pytorch/pytorch#88919]
### 🚀 The feature, motivation and pitch

The current default window used on Torch's Short Time Fourier Transform (STFT) method is the rectangular window.
This window has major drawbacks and is known to produce artifacts in the output (see [here](https://www.audiolabs-erlangen.de/resources/MIR/FMP/C2/C2_STFT-Window.html) for details.

Both [Scipy's implementation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.stft.html) and [Librosa's](https://librosa.org/doc/main/generated/librosa.stft.html) use the Hann window by default. Furthermore, both libraries allow for a string name to be used, abstracting the creation of the window itself.

I propose the following changes to `torch.stft`:
* Make the Hann window the default on function `torch.stft`
* Modify the interface of torch.stft to allow a string to be provided to the `window` parameter, and include common windows such as `torch.hann_window`, `torch.blackman_window` and `torch.hamming_window` 

I would be happy to work on this myself. I propose to and test the code below to `torch.stft`, and add relevant documentation as well:

```python    if isinstance(window, str):
        windows = {
            "hann": torch.hann_window,
            "hamming": torch.hamming_window,
            "blackman": torch.blackman_window
        }
        if window not in windows.keys():
            raise ValueError(f"""{window} is not a valid window name.
            			Available windows are {windows.keys()}""")
        
        else:
            win_length = n_fft if win_length is None else win_length
            window = windows[window](win_length, device=input.device)
```

I hope this will be a positive contribution to the Pytorch community. Please tell me if you prefer for this to be done in a different way.

Kind regards,

Eric

cc @mruberry @peterbell10

**Comment by mruberry** [comment]
`torch.stft` was modeled after `librosa.stft`, and allowing window selection makes sense. I think this would have to be done as follows:

1) add the option to specify the window
2) warn when the is unspecified
3) wait 180 days and two PyTorch releases ([per the BC policy](https://github.com/pytorch/pytorch/wiki/PyTorch's-Python-Frontend-Backward-and-Forward-Compatibility-Policy#minimizing-the-disruption-of-bc-breaking-changes))
4) throw an error when the window is unspecified
5) wait 180 days and two PyTorch releases
6) let `stft` be called without specifying the window and make the default window option consistent with librosa and SciPy

What do you think, @peterbell10?

**Comment by egrinstein** [comment]
Hi @mruberry @peterbell10 .

Sorry for disappearing for almost a year!
I have created a pull request which warns if the window is not provided for STFT and ISTFT,
as discussed in #89280.

I hope it's alright, but I'm sure there are things to be improved as it's my first one on the project.

Thanks and best wishes,

Eric
