### ISSUE TITLE
import torch: DLL load failed: The operating system cannot run %1. (pip installation)

### ISSUE THREAD

**Issue by homofortis** [pytorch/pytorch#8894]
## Issue description
After the installation, torch import fails with an error. 
I read the posts on other similar issues and installed intel-openml, mkl, mkl-fft, vs2017 runtime but still getting the same import error. Please note, I am not using anaconda. 
P.S. I have also installed Tensorflow which makes use of CUDA and GPU.

## Code example
`import torch
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.`

## System Info
(https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
The above script doesn't work for me as it imports torch so I have modified the code to ignore torch calls:

`PyTorch version: 0.4.0
Is debug build: 0.4.0
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 760M
Nvidia driver version: 385.54
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip3] intel-numpy (1.14.3)
[pip3] numpy (1.14.5)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect`

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip3
- Build command you used (if compiling from source):
- OS: Windows 10
- PyTorch version: 0.4.0
- Python version: 3.6.5
- CUDA/cuDNN version: 9.0
- GPU models and configuration:  NVIDIA GeForce GTX 760M
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by homofortis** [comment]
Replacing the existing numpy with **numpy‑1.14.5+mkl‑cp36‑cp36m‑win_amd64.whl** from [https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy](url) resolved the issue for me (but not before wasting hours in try-this-and-that). 
It would've been nice if this issue was mentioned on the PyTorch installation page.

**Comment by hemangjoshi37a** [comment]
@homofortis your page link is empty.
If you could just tell that what code to run or which file to temper it will be awesome.
Thank you.

**Comment by hemangjoshi37a** [comment]
@homofortis ok sir...

**Comment by hemangjoshi37a** [comment]
@homofortis there is more later released version is available  on that website, should i install that version instead??
![opera snapshot_2018-09-03_221442_www lfd uci edu](https://user-images.githubusercontent.com/12392345/44996666-d105be00-afc6-11e8-8603-559bf50838d1.png)

**Comment by homofortis** [comment]
@hemangjoshi37a I would go for the latest version provided it works for me, but there is only one way to find out :P
