### ISSUE TITLE
Tensor slicing within loop silently fails assignment, vs effective same slice assignments out of loop works as expected

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#88953]
### 🐛 Describe the bug

This issue involves unexpected behaviour within a loop while using a shared buffer tensor and slicing, whereas the same assignments when unrolled works as expected.

Repo steps:
1 - Create two tensors, x,y that are size (4,4) of ones, and a buffer tensor of size 32 (1D).  Confirm their contents and data_ptrs.  
<img width="1029" alt="abuffer_one" src="https://user-images.githubusercontent.com/46302957/201490008-597b2aa5-f447-4926-a05c-50d2ca7e53bb.png">

3 - Put x and y in an list for iteration, and within a loop, assign the contents of each to the buffer tensor and confirm buffer tensor is updated to all 1s.
<img width="885" alt="abuffer_two" src="https://user-images.githubusercontent.com/46302957/201490055-09414165-9dd5-4484-82d1-9355a2f02bfb.png">

4 - modify the buffer
<img width="741" alt="abuffer_three" src="https://user-images.githubusercontent.com/46302957/201490080-10a6eb04-58dc-490c-91fb-063b510df2cb.png">

5 - assign the updated buffer contents in a loop back to tensors x and y.  Note that x and y are not updated as expected.  However, we can see that t in the first iteration moves its data ptr to the buffer, and then in the second iteration spawns a new data storage but y is not updated to it.  
<img width="1059" alt="abuffer_five" src="https://user-images.githubusercontent.com/46302957/201490136-2ad4c0f7-cb17-4d73-b964-4520bee5c672.png">

6 - By comparison, doing the same slicing outside of a loop will update the contents of x and y as expected.  Note that X now has it's data_ptr to the buffer data_ptr, and then y is now assigned the lost tensor that was spawned above in the second loop iteration. 
<img width="1046" alt="abuffer_unrolled" src="https://user-images.githubusercontent.com/46302957/201490249-3bae0a7b-7ec9-4473-b0e3-a50c95d2bdcd.png">

Discussion - I tried this out on both cpu and gpu in case it was cpu specific issue (have seen that before where cuda works as expected but not cpu).  
The big issue here is that t in the loop is being moved and not updating the original x and y tensors for reasons unclear.  But it is quite unexpected. 
In some cases, it appears that during the first iteration of the loop, x is updated to repoint to the buffer and thus has correct data, but never y (second loop)....I could not repo that consistently. 
 
I also tested with reshape and it didn't matter, and also tested having x and y as 1D tensors to avoid the view but also same issue. 

The fix for me was to switch to using copy_ (shown commented out in the loop) at which point everything works as expected.  
However, the fact that the expected behaviour works in an unrolled fashion, but fails within a loop, is the main issue of this report.

### Versions

PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.15 (default, Oct 12 2022, 19:14:55)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

**Comment by ngimel** [comment]
This is standard python behavior that has nothing to do with pytorch, you are trying to replace references to list elements, but the original list elements are unchanged:
```
In [1]: import torch

In [2]: a={1}; b={2}

In [3]: l=[a,b]

In [4]: for i,t in enumerate(l):
   ...:     t={i}
   
In [5]: l
Out[5]: [{1}, {2}] #would be [{0}, {1}] according to your expectations
```

**Comment by lessw2020** [comment]
Thanks @ngimel for the clarification here that it's unrelated to torch.

I reproed your set example above as well as using a list:
<img width="340" alt="failing_list_assign" src="https://user-images.githubusercontent.com/46302957/201539712-a76aa0bb-d7c3-4728-98ab-84314514b877.png">


If I swap that to using assign t[0] in the loop (rather than t to a new list) to somewhat mimic that we are trying to update data within the tensor it works as expected.  
<img width="357" alt="working_list" src="https://user-images.githubusercontent.com/46302957/201539734-fe6d0fe9-48dd-4b44-9767-872f3d4ad13c.png">

I'm still unclear why this bounce out in the loop is happening though..t is a correct reference and then suddenly becomes a new object...it seems direct references to items in the container, rather than the the object itself in the loop, are the difference but if you have any insight as to why, would appreciate it.

Otherwise will close this as unrelated to PT.  
Thanks!

**Comment by ngimel** [comment]
You are reassigning temporary reference to an item in the container, items in the container remain unchanged.

**Comment by lessw2020** [comment]
Yes I see - my mental model was that t was &a, &b but it's really just a temp pointer to a,b. 
Rewriting the loop to the equivalent of direct reference and bypassing the temp var gives expected results:
<img width="323" alt="direct_loop" src="https://user-images.githubusercontent.com/46302957/201546916-c26cd169-bf6d-4cc8-af31-e33ceb2a0f6b.png">

Thanks again.
