### ISSUE TITLE
DDP multithreading SIGTERM crash

### ISSUE THREAD

**Issue by HarshitSheoran** [pytorch/pytorch#88954]
### 🐛 Describe the bug

I use something peculiar to run my codes in ddp while not opening a terminal

![image](https://user-images.githubusercontent.com/37008327/201492804-807f8247-dd5f-4b58-aa98-4dc99dc1ee4b.png)

In the image below, you can see an error

![image](https://user-images.githubusercontent.com/37008327/201492656-06bec414-f4d7-48bc-845e-c5039aa77491.png)

### Versions

The error comes irrespective of which driver version, cuda version, pytorch version, ubuntu version is installed, it happens completely randomly, and can happen on any type of code which uses pytorch ddp

I have a 4x 3090 system, 3960x (48 threads)

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by H-Huang** [comment]
Hi, torch.distributed and DDP do not work with multithreading. You will need to use multiprocessing and the convention is to use 1 process per GPU.

**Comment by HarshitSheoran** [comment]
So, how do I do this?

**Comment by H-Huang** [comment]
Here are the tutorials: https://pytorch.org/tutorials/intermediate/ddp_tutorial.html. Also note that notebooks do not support python multiprocessing

**Comment by HarshitSheoran** [comment]
Thanks!, does DataLoader with DistributedSampler with workers=N where N!=0, count as multithreading? maybe that's what's causing errors
