### ISSUE TITLE
NotImplementedError: The operator 'aten::index.Tensor' is not current implemented for the MPS device.

### ISSUE THREAD

**Issue by JayeshMD** [pytorch/pytorch#88973]
### 🐛 Describe the bug

```python
import torch
device = torch.device("mps")
v = torch.arange(10,device=device)
v = v[v>5]
```

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In [34], line 4
      2 device = torch.device("mps")
      3 v = torch.arange(10,device=device)
----> 4 v = v[v>5]

NotImplementedError: The operator 'aten::index.Tensor' is not current implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (arm64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-13.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchdiffeq==0.2.3
[pip3] torchvision==0.13.1
[conda] numpy                     1.22.4                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
It has been implemented on master.

```
device = torch.device("mps")
v = torch.arange(10,device=device)
v = v[v>5]
print(v)  # tensor([6, 7, 8, 9], device='mps:0')
```

Tested at `1.14.0a0+gitba6ee50`

**Comment by malfet** [comment]
Closing as being implemented by https://github.com/pytorch/pytorch/pull/82507
