### ISSUE TITLE
Nested FX tracing doesn't work when outer tracing mode is symbolic

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#88996]
### 🐛 Describe the bug

nvFuser executor for AOT Autograd + PrimTorch uses isolated make_fx to get decomposed subgraphs for analysis. This doesn't work if the outer tracing mode is symbolic, it fails with the following error:
```py
File ~/dev/pytorch/master/torch/fx/experimental/proxy_tensor.py:87, in get_proxy_slot(obj, tracer, default, transform)
     85 if tracer not in d:
     86     if default is no_default:
---> 87         raise KeyError(f"{obj} is not tracked with proxy for {tracer}")
     88     else:
     89         return default

KeyError: 's0 is not tracked with proxy for <torch.fx.experimental.proxy_tensor.PythonKeyTracer object at 0x7facce5006d0>'
```
Here's code to reproduce the failure:
```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx, wrapper_and_args_for_make_fx

def func(a, b):
    return b.expand([1, a.shape[0], b.shape[-1]])

a = torch.randn(3, 4, device="cuda")
b = torch.randn(4, device="cuda")

class TestMode(torch.overrides.TorchFunctionMode):
    def __torch_function__(self, func, types, args=(), kwargs=None):
        if kwargs is None:
            kwargs = {}

        if torch.overrides.resolve_name(func) in ["torch.Tensor.expand"]:
            print(f"TestMode: {func} {args} {kwargs}")
            wrapped, all_args = wrapper_and_args_for_make_fx(func, args, kwargs)
            gm = make_fx(wrapped, tracing_mode="real")(all_args)
            gm.graph.print_tabular()

        return func(*args, **kwargs)

with TestMode():
    gm = make_fx(func, tracing_mode="symbolic")(a, b)

gm.graph.print_tabular()
```

### Versions

Latest master.

cc @ezyang @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv

**Comment by jjsjann123** [comment]
cc'ing @Chillee

**Comment by ezyang** [comment]
I believe what @Chillee said is that if the outer mode is symbolic, you should using tracing_mode="real" for the inner make_fx calls

**Comment by IvanYashchuk** [comment]
"real" fails with the same error.

**Comment by IvanYashchuk** [comment]
@Chillee, do you have any other ideas about what could be the cause and how to fix the problem?

**Comment by jon-chuang** [comment]
"real" works for me. Only tested without device=cuda (not on a machine with CUDA atm).

However, I noticed some artifacts when calling nested `make_fx`:
```
call_function  detach      aten.detach.default  (b_1,)                            {}
call_function  detach_1    aten.detach.default  (detach,)                         {}
```

To my understanding, these appear when there are other traced functions being resolved in the same call. It can be disabled by disabling external proxy modes from the inner module, i.e. rewriting your above code with the `get_isolated_graphmodule` helper function:
```python
...
        if torch.overrides.resolve_name(func) in ["torch.Tensor.expand"]:
            print(f"TestMode: {func} {args} {kwargs}")
            gm = get_isolated_graphmodule(func, args, kwargs)
            gm.graph.print_tabular()
...
```

Or, every outer `make_fx` can suspend the tracing of inner `make_fx`. I believe the latter is more robust, so I've made a PR for this. https://github.com/pytorch/pytorch/pull/93290
