### ISSUE TITLE
Hanging on myTensor.cuda()

### ISSUE THREAD

**Issue by alexbw** [pytorch/pytorch#890]
Hey all, good looking library.

I'm running into the following issue, and I'm sure it's a configuration problem on my end, but I don't know how to begin to debug it.

I have two cards, a Titan X, and an older Quadro (to drive a monitor). Titan X is device 0, and Quadro is device 1. I'm on Python 3.5. I've got CUDA 8.0 installed.

```python
import torch
a = torch.randn(3,3)
a_gpu = a.cuda() # <-- hangs forever here.
```

One core of my CPU is pinned at 100%, doing something. Restarting the machine does not help. Other CUDA-backed systems, e.g. Cupy, do not have a problem.

If I interrupt the kernel, here's the traceback:
```python
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-1-ca988235a575> in <module>()
      1 import torch
      2 a = torch.randn(3,3)
----> 3 a_gpu = a.cuda() # <-- hangs forever here

/home/alexbw/anaconda/lib/python3.5/site-packages/torch/_utils.py in _cuda(self, device, async)
     49             device = -1
     50         with torch.cuda.device(device):
---> 51             return self.type(getattr(torch.cuda, self.__class__.__name__), async)
     52 
     53 

/home/alexbw/anaconda/lib/python3.5/site-packages/torch/_utils.py in _type(self, new_type, async)
     22     if new_type == type(self):
     23         return self
---> 24     return new_type(self.size()).copy_(self, async)
     25 
     26 

/home/alexbw/anaconda/lib/python3.5/site-packages/torch/cuda/__init__.py in __new__(cls, *args, **kwargs)
    255         # We need this method only for lazy init, so we can remove it
    256         del _CudaBase.__new__
--> 257         return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
    258 
    259 

KeyboardInterrupt: 
```

However, if I don't use the Titan X, everything works fine.
```python
import torch
torch.cuda.set_device(1)
a = torch.randn(3,3)
a_gpu = a.cuda() # works just fine
```

Any idea why this is? Any pointers for how to get to the bottom of it? Should I downgrade to CUDA 7.5?

**Comment by soumith** [comment]
did you install the CUDA8.0 version of pytorch?
pytorch.org has separate binaries for CUDA 7.5 and 8.0.

Also, if there's an older quadro, it's possible that it's trying to JIT kernels for the quadro, try:
`CUDA_VISIBLE_DEVICES=0 ipython`

**Comment by alexbw** [comment]
Derp, my original install was when I had 7.5, then I upgraded, and didn't fix PyTorch. Weird that it works on the Quadro, though! Thanks. Closing.
