### ISSUE TITLE
ROCm runner only shows 3 GPUs

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#89012]
### 🐛 Describe the bug

ROCm runners are expected to have [either 2 or 4](https://github.com/pytorch/pytorch/pull/89011#:~:text=expect%20to%20get.-,This%20old%20PR,-shows%20that%20historically) GPUs attached.  However, a workflow recently failed when noticing a runner with 3 GPUs:
https://github.com/pytorch/pytorch/actions/runs/3432340660/jobs/5721731207

https://github.com/pytorch/pytorch/pull/89011 modifies the ROCm workflow logic to accept any number of GPUs greater than or equal to 2, but this ticket is an ask to the ROCm team to investigate why this runner has only 3 GPUs, a nonstandard configuration.

The runner in question:
```
Current runner version: '2.299.1'
Runner name: 'worker-rocm-amd-98'
Runner group name: 'Default'
Machine name: 'jenkins-worker-rocm-amd-98'
```

cc @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by jithunnair-amd** [comment]
This was due to a faulty GPU on this CI node (jenkins-worker-rocm-amd-98) due to which only 3 GPUs were being detected. The node has been fixed by reducing GPUs to 2. The node has been added back to the CI pool.

```
amd@jenkins-worker-rocm-amd-98:/home/pytorchci/actions-runner$ rocm-smi


======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp   AvgPwr  SCLK    MCLK    Fan   Perf  PwrCap  VRAM%  GPU%
0    33.0c  17.0W   930Mhz  350Mhz  255%  auto  225.0W    0%   0%
1    34.0c  15.0W   930Mhz  350Mhz  255%  auto  225.0W    0%   0%
================================================================================
============================= End of ROCm SMI Log ==============================

```
