### ISSUE TITLE
Cleanup optimizer handling of complex numbers for LBFGS and SparseAdam

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#89021]
Follow up on https://github.com/pytorch/pytorch/issues/65711

cc @vincentqb @jbschlosser @albanD @ezyang @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by albanD** [comment]
No one on our end is working on this but we would accept a PR adding support for these.

**Comment by lezcano** [comment]
Closing in favour of https://github.com/pytorch/pytorch/issues/86340
