### ISSUE TITLE
Decline in accuracy

### ISSUE THREAD

**Issue by shaqing** [pytorch/pytorch#89039]
### 🐛 Describe the bug

hello，i convert pytorch model to onnx model, then inference the same picture with torch and onnxruntime ;
when i inference with torch，i print the first 15 nums：
[0.01681411 0.05290637 0.03931383 0.02069167 0.05464995 0.05208057
0.03364787 0.02164895 0.04400286 0.04631684 0.00424759 0.04806569
0.03491891 0.04207694 0.00969397]
when i inference with onnxruntime，i print the first 15 nums：
[1.3163207e-02 3.3286333e-02 3.0172531e-02 2.7824650e-05 5.4625902e-02
2.5197309e-02 4.4952868e-03 5.4582981e-03 2.5899781e-02 3.7061449e-02
1.8202272e-03 1.9214328e-02 3.2222427e-02 7.0376499e-03 2.4394415e-02]
why does it happen?

### Versions

torch:1.12.1+cu113
onnxruntime:1.12.1

**Comment by BowenBao** [comment]
Hi @shaqing thanks for reporting, could you please do the following?
* Try with latest pytorch and onnxruntime.
* Share a minimal self-contained repro script with us.

**Comment by thiagocrepaldi** [comment]
@shaqing closing as there is no repro script nor feedback from author. 
If this is still relevant, please reopen with a repro
