### ISSUE TITLE
Advanced indexing returns values not in tensor 

### ISSUE THREAD

**Issue by DanielDworakowski** [pytorch/pytorch#8904]
## Issue description

While indexing a tensor I am receiving values that are not contained within the tensor.  I currently do not have access to a GPU, so these results are specifically CPU only. 

### Torch:
``` import torch
a = torch.tensor([1,2,3,4,5,6])
a = a.view(6,-1)
a[:,2::6]
```
> tensor([ 2.0000e+00,  3.0000e+00,  4.0000e+00,  5.0000e+00,  6.0000e+00,
        -4.6117e+18])

### Comparison with Numpy:
```import numpy as np
a = np.array([1,2,3,4,5,6])
a = a.reshape(6,-1)
a[:,2::6]
```
>array([], shape=(6, 0), dtype=int64)

### Torch (More simplified example):
```import torch
a = torch.Tensor([1,2,3,4,5,6])
a = a.view(6,-1)
a
```
>tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.]])

`a[:,4]`
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 IndexError: index 4 is out of bounds for dimension 1 with size 1

`a[:,4:4]`

> tensor([ 2.,  3.,  4.,  5.,  6.,  0.])

## System Info
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.5
GCC version: Could not collect
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] numpy-quaternion (2017.6.5.21.19.52.dev20097538)
[pip3] numpydoc (0.7.0)
[pip3] pytorchviz (0.0.1)
[pip3] torch (0.4.0)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] pytorchviz                0.0.1                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by SsnL** [comment]
Thanks for reporting. This has been fixed on master.
