### ISSUE TITLE
Add a note to torch.round docs to indicate that the return type of out is the same as input.dtype

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#89056]
### 📚 The doc issue

One might expect that the output of [torch.round](https://pytorch.org/docs/stable/generated/torch.round.html?highlight=round#torch.round) will be an int tensor but that's not the case. Let's add a note to the doc to clarify that this is intended since it can be a little bit surprising for the user.

cc @svekars @carljparker @albanD

**Comment by JennyChristopher** [comment]
I would like to tackle this as my first issue. Would you accept a PR ?
