### ISSUE TITLE
Better ways to make CI env changes

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#8907]
Currently because of `TestCollectEnv.test_expect`, if one wants to change some CI env, e.g., CUDA driver version, they need to disable that test in a PyTorch PR, update the CI dockerfile repo, then update expect file & re-enable. There should be easier ways.

cc @zou3519 @yf225

**Comment by ezyang** [comment]
There is always necessarily going to be some interlock involved though, right? You need to always:

1. Modify pytorch to accept the new image
2. Deploy it
3. Modify pytorch to not accept the new image

I am OK with chalking up this `test_expect` test as a failed experiment and just removing it entirely. There's probably better ways to check that our CI env is consistent.

**Comment by zou3519** [comment]
Agreed, we should remove the expect test if it is too much (it seems like it is).

**Comment by SsnL** [comment]
@ezyang @zou3519 Here's my thought: we should have a CI env that uses only the absolute minimal supported versions of everything. Configs of that env should not be changed often. And we should only enable `test_expect` for that env.

**Comment by ezyang** [comment]
we killed the test
