### ISSUE TITLE
Cannot import torch after installation

### ISSUE THREAD

**Issue by Mathemilda** [pytorch/pytorch#89082]
### 🐛 Describe the bug

Hello, 
I decided to install pytorch on my machine. For this looked up your site and ran the following recommended command in my Anaconda prompt:
```
conda install pytorch torchvision torchaudio cpuonly -c pytorch
```
I followed it by `conda update --all` and `conda clean --all`. 
Then I tried in my jupyter notebook:
```
import tensorflow as tf
import torch
```
And I got an error message:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_13684\3138718728.py in <module>
      1 import tensorflow as tf
      2 #import pandas as pd
----> 3 import torch

~\miniconda3\lib\site-packages\torch\__init__.py in <module>
     19     raise Exception("Python 2 has reached end-of-life and is no longer supported by PyTorch.")
     20 
---> 21 from ._utils import _import_dotted_name, classproperty
     22 from ._utils_internal import get_file_path, prepare_multiprocessing_environment, \
     23     USE_RTLD_GLOBAL_WITH_LIBTORCH, USE_GLOBAL_DEPS

ImportError: cannot import name 'classproperty' from 'torch._utils' (C:\Users\my_account\miniconda3\lib\site-packages\torch\_utils.py)
```
I currently use Python 3.9.15 on Windows 10, 32 Gb memory, 8 i7-2600 CPU @ 3.40GHz.
I have been able to use jupyter notebooks (and Spyder) for a few years, and I never saw such problem.
I can run Python from my prompt:
```
my_account> Python
Python 3.9.15 (main, Nov  4 2022, 16:35:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
```
Please help.
Best regards,
Mya

### Versions

C:\Users\my_account\miniconda3\python.exe: can't open file 'C:\Users\my_account\collect_env.py': [Errno 2] No such file or directory

**Comment by bdhirsh** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
