### ISSUE TITLE
[ppc64le pytorch] RuntimeError: NCCL Error 13: invalid data type 

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#8909]
torch (0.5.0a0+f607794)
RH 7.5
CUDA 9.2 
cuDNN 7
GPU :  Pascal
cmake version 3.11.1

## Issue description
When running autograd test and other tests ,  tests fails with :
RuntimeError: NCCL Error 13: invalid data type
 Example:
ERROR: test_unused_output_gpu (__main__.TestAutograd)
 
Traceback (most recent call last):
  File "test_autograd.py", line 1360, in test_unused_output_gpu
    outputs = Broadcast.apply(list(range(torch.cuda.device_count())), x)
  File "/home/freddie/miniconda/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 19, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/home/freddie/miniconda/lib/python3.6/site-packages/torch/cuda/comm.py", line 40, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: NCCL Error 13: invalid data type

The build log shows that it seemed to have found the nccl2 shipped with CUDA 9.2
but later in the log it sets NCCL_ROOT_DIR==/home/****/builder/jenkins/pytorch/pytorch/torch/lib/tmp_install   which I believe is nccl1

here is the portion of the log that finds nccl2 
-- Determining NCCL version from the header file: /usr/local/cuda/include/nccl.h
-- NCCL_MAJOR_VERSION: 2
-- Found NCCL (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libnccl.so)

here is the portion that sets NCCL_ROOT_DIR
+ NCCL_ROOT_DIR=/home/****/builder/jenkins/pytorch/pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR=/home/****/builder/jenkins/pytorch/pytorch/torch/lib/tmp_install'

Previous versions of CUDA like 9.1 and less did not have this problem.  If I remember correctly CUDA 9.1 and below shipped with nccl1.    I also did not have to set NCCL_ROOT_DIR, NCCL_LIB_DIR, NCCL_INCLUDE_DIR explicitly when using CUDA 9.1 and below.

## Workaround
export USE_SYSTEM_NCCL=1
export NCCL_ROOT_DIR=/usr/local/cuda
export NCCL_LIB_DIR=/usr/local/cuda/lib64
export NCCL_INCLUDE_DIR=/usr/local/cuda/include

**Comment by soumith** [comment]
`nccl` or `nccl2` are not shipped with CUDA. Atleast last I checked. I wonder if this changed with CUDA 9.2.

**Comment by soumith** [comment]
@avmgithub that's probably as a result of installing nccl2 into `/usr/local/cuda`, like: https://github.com/pytorch/builder/blob/403fe6d58680b4bdb2f93dbb3dbddf0f5abeed73/manywheel/Dockerfile_92#L56-L61

**Comment by avmgithub** [comment]
@soumith I guess you're right.  I looked at some another system with CUDA 9.2 and they did not have the nccl2 include and libraries.   I must have picked up the nccl2 from nvdia download and installed them manually.  I'll close this
