### ISSUE TITLE
Support int16 numpy conversions

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#891]

**Comment by Teaonly** [comment]
Should we  add a ShortTensor Type,  or just convert int16 to IntTensor ?

**Comment by soumith** [comment]
We already have a `ShortTensor` type available in pytorch. We have to enable conversion in the relevant `from_numpy` function here: https://github.com/pytorch/pytorch/blob/fc6fcf23f7917a3e7d0326ca74d24f34ad92a4a3/torch/csrc/Module.cpp#L127-L152

**Comment by Teaonly** [comment]
https://github.com/pytorch/pytorch/pull/902

```
In [1]: import torch

In [2]: import numpy as np

In [3]: x = np.zeros([10,10], dtype=np.int16)

In [4]: xt = torch.from_numpy(x)

In [5]: xt
Out[5]:

    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0
[torch.ShortTensor of size 10x10]
```

Auto travis-ci failed at python2.7  :(

**Comment by acgtyrant** [comment]
Do you have any plan to support int8 numpy conversion while you have `torch.ByteTensor` too?

**Comment by apaszke** [comment]
Char tensor uses char which is not guaranteed to be signed by the C standard. We'd need to change our C code to use a `signed char`

**Comment by acgtyrant** [comment]
@apaszke I try `torch.from_numpy(np.array([0], dtype=np.int8))`, it complains ` can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8`, any idea?

**Comment by apaszke** [comment]
The error message is quite self explanatory. PyTorch doesn't support `int8` tensors at the moment.
