### ISSUE TITLE
Complex support for `log1p` and `logcumsumexp`

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#89205]
### 🚀 The feature, motivation and pitch

I'm using `log1p` and `logcumsumexp` for complex number in my case. However, as of Pytorch 1.13.0, this has not been supported.
I found a discussion [here](https://github.com/pytorch/pytorch/issues/33152#issuecomment-1103798298) and an old PR [here](https://github.com/pytorch/pytorch/pull/38465/), but it seems like the PR has been abandoned.
I would like to resurrect this and working on it if there's no one is working to implement it already.

### Alternatives

The alternative is to implement it in python, but it would be nice to have it supported in Pytorch.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment]
I will review a pr if you send us one
