### ISSUE TITLE
Dynamo + NNC: incorrect results with in-place ops on inputs

### ISSUE THREAD

**Issue by nunoplopes** [pytorch/pytorch#89219]
### 🐛 Describe the bug

```python
import torch
import torch._dynamo

def fn(x, y):
    x += y
    return x


fn2 = torch._dynamo.optimize("nnc")(fn)
print(fn(torch.ones(1), torch.ones(1)))
print(fn2(torch.ones(1), torch.ones(1)))
```

prints:
```
tensor([2.])
tensor([6.])
```

Clearly the FX -> NNC conversion (through tracing?) is not sound wrt to in-place ops.

### Versions

1.14.0.dev20221117+cpu

cc @EikanWang @jgong5 @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by anijain2305** [comment]
Closing as we are not maintaining NNC anymore.
