### ISSUE TITLE
Deprecation warning in `Tensor.storage()` should suggest alternate API

### ISSUE THREAD

**Issue by kurtamohler** [pytorch/pytorch#89224]
Since #85303 deprecated `TypedStorage`, calling `Tensor.storage()` now raises a warning about the deprecation because it returns a `TypedStorage`. The warning should be updated to mention how to get an `UntypedStorage` from the tensor. At the moment, this is done with `Tensor._storage()`, but it should be renamed to `Tensor.untyped_storage()` so that it's public, and there should be documentation for it.

It might be good for the warning to mention in which cases `UntypedStorage` and `TypedStorage` are not interchangeable.

~We should also have a function that takes an `UntypedStorage` and a `torch.dtype` and returns a tensor that wraps the storage.~ EDIT: `torch.tensor` does this

cc @albanD

**Comment by albanD** [comment]
That sounds good. The new untyped_storage API sounds good.
Not sure if we really need an API to build a Storage again? The APIs that we have today that take Storage also accept UntypedStorages right?

It would be good as well to provide 1-1 correspondance for python storage object with c++ storage like we do for Tensor. @ezyang do you think it is worth reproducing all the complexity we have for Tensor here?

**Comment by ezyang** [comment]
@eellison has been asking for it and I think is reasonable
