### ISSUE TITLE
log1p not supported on torch.FloatTensor

### ISSUE THREAD

**Issue by weiyangfb** [pytorch/pytorch#8923]
For some reason torch.log1p() is broken.

```
a = torch.rand(3)
torch.log1p(a)
```
RuntimeError: log1p not supported on torch.FloatTensor

**Comment by vishwakftw** [comment]
`log1p` seems to work fine on master.

**Comment by li-roy** [comment]
I also can't reproduce this.

**Comment by weiyangfb** [comment]
Ah, I see, it is working fine. I accidentally changed something and broke it...
