### ISSUE TITLE
RuntimeError: cuda runtime error (30), cuda-9.1, nvidia-driver-390.30

### ISSUE THREAD

**Issue by goswamig** [pytorch/pytorch#8926]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
pytorch-cuda-9.1 
RuntimeError: cuda runtime error (30) : unknown error at /opt/conda/conda-bld/pytorch_1524580938250/work/aten/src/THC/THCGeneral.cpp:70
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524580938250/work/aten/src/THC/THCGeneral.cpp line=70 error=30 : unknown error

## Code example
from torch.autograd import Variable
import torch.onnx
import torchvision

dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
print(dummy_input)

## System Info
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: No
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80
GPU 4: Tesla K80
GPU 5: Tesla K80
GPU 6: Tesla K80
GPU 7: Tesla K80

Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-9.0/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.0/lib64/libcudnn_static.a
/usr/local/cuda-9.1/lib64/libcudnn.so.7.0.5
/usr/local/cuda-9.1/lib64/libcudnn_static.a
/usr/local/cuda-9.2/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.2/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] pytorch                   0.4.0           py27_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] torchvision               0.2.1                    py27_1    pytorch
(pytorch_p27) ubuntu@ip-172-31-78-23:~$

- PyTorch or Caffe2:  PyTorch
- How you installed PyTorch (conda, pip, source):  Conda
- Build command you used (if compiling from source): N/A
- OS: Ubuntu
- PyTorch version:  0.4.0
- Python version:  2.7
- CUDA/cuDNN version:  9.1 
- GPU models and configuration:  Tesla K80
- GCC version (if compiling from source):   5.4.0
- CMake version:  3.5.1
- Versions of any other relevant libraries:

============ Cuda information might needed ================
Cuda: 9.1 
NCCL:  2.1.5 
CUDNN: 7.0.5

ls -lrt /usr/local/cuda
lrwxrwxrwx 1 root root 20 Jun 22 01:34 /usr/local/cuda -> /usr/local/cuda-9.0/

(pytorch_p27) ubuntu@ip-172-31-78-23:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/extras/CUPTI/lib64:/lib/nccl/cuda-9.1/lib:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ echo $CUDA_PATH
/usr/local/cuda-9.1

cc @ngimel

**Comment by gautamkmr** [comment]
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ ls -lrt /usr/local/cuda
lrwxrwxrwx 1 root root 20 Jun 22 01:34 /usr/local/cuda -> /usr/local/cuda-9.0/
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/extras/CUPTI/lib64:/lib/nccl/cuda-9.1/lib:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ echo $CUDA_PATH
/usr/local/cuda-9.1

**Comment by gautamkmr** [comment]
``(pytorch_p27) ubuntu@ip-172-31-78-23:~$ ls -lrt /usr/local/cuda
lrwxrwxrwx 1 root root 20 Jun 22 01:34 /usr/local/cuda -> /usr/local/cuda-9.0/
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/extras/CUPTI/lib64:/lib/nccl/cuda-9.1/lib:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:/usr/lib64/openmpi/lib/:/usr/local/lib:/usr/lib:/usr/local/mpi/lib:/lib/:
(pytorch_p27) ubuntu@ip-172-31-78-23:~$ echo $CUDA_PATH
/usr/local/cuda-9.1

**Comment by zou3519** [comment]
Could you try relinking /usr/local/cuda to /usr/local/cuda-9.1/ (instead of cuda9.0 as it appears)?

**Comment by mruberry** [comment]
Closing due to age and lack of response.
