### ISSUE TITLE
port grid sampler and affine grid generator to aten

### ISSUE THREAD

**Issue by li-roy** [pytorch/pytorch#8928]

**Comment by ailzhang** [comment]
Just found this thread. Should we also add other necesary methods when porting grid_sample to Aten?
https://github.com/pytorch/pytorch/issues/5565#issuecomment-403579583 
cc: @fmassa

**Comment by jph00** [comment]
This is looking great - thanks! We're doing some performance testing, and it's a big improvement.

FYI, at the moment `F.interpolate` is much faster than `grid_sampler` even in the case the affine matrix is identity and there's no resize.

(Also, PIL's `transform` is much faster still, at least when using pillow-simd.)

**Comment by ailzhang** [comment]
This is done, closing...
