### ISSUE TITLE
Multiple GPU, Batch Normalization - RuntimeError: the derivative for 'running_mean' is not implemented

### ISSUE THREAD

**Issue by malisit** [pytorch/pytorch#8930]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I'm not able to use batchnorm when I run the code on multiple gpu. Below code works just fine when ran on single gpu.

I tried this on 4.0 version as well, the result is same and also when I uncomment flatten_parameters() part.

## Code example

```
        self.inp1 = nn.Linear(4, 24)
        self.lstm1 = nn.LSTM(24, 24, 2, dropout=0.05)
        self.lstm1_bn = nn.BatchNorm1d(24)
        self.out1 = nn.Linear(24, 16)
```

```
        res = F.relu(self.inp1(x1))
        #self.lstm1.flatten_parameters()
        res, h__ = self.lstm1(res, h[0])
        h[0] = torch.stack(h__)
        res = F.tanh(res)
        res = self.lstm1_bn(res.view(-1, 24))
        res = res.unsqueeze(0)
        res = F.max_pool2d(res, 1, stride=1)
        res1 = F.relu(self.out1(res))
```
```
Traceback (most recent call last):
  File "train_flood.py", line 83, in <module>
    outputs = model(input)
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msit/deep/parallel/model.py", line 109, in forward
    res = self.lstm1_bn(res.view(-1, 24))
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 65, in forward
    exponential_average_factor, self.eps)
  File "/home/msit/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1229, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: the derivative for 'running_mean' is not implemented

```
## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source on conda
- Build command you used (if compiling from source): same as the instructions on README.md
- OS: RHEL 7
- PyTorch version: 0.5.0a0+290d20b
- Python version: 3.6
- CUDA/cuDNN version: 8.0.61
- GPU models and configuration: 2 X Tesla K80
- GCC version (if compiling from source): 4.8.5 20150623 (Red Hat 4.8.5-28)
- CMake version: 3.11.1
- Versions of any other relevant libraries:
[pip3] numpy (1.14.0)
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+290d20b           <pip>

**Comment by zou3519** [comment]
Could you post a minimal script that reproduces the problem?

**Comment by grantsrb** [comment]
Low chance this applies to your situation, but I got this error when I used a parameter with `requires_grad` set to `True` as the `running_mean` in the `nn.functional.batch_norm` function. Hopefully this helps someone else who finds themselves in the same situation.

**Comment by gchanan** [comment]
I believe the problem is as @grantsrb described, if you disagree please reopen.
