### ISSUE TITLE
torch.where: The exception information thrown differs from the official documentation

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89348]
### 🐛 Describe the bug

    import torch

    condition = torch.rand([3, 2], dtype=torch.float64)
    x = torch.rand([3, 2], dtype=torch.float64)
    y = torch.rand([3, 2], dtype=torch.float64)
    print(torch.where(condition, x, y))

result: RuntimeError: Expected condition to have ScalarType Byte, but got ScalarType Double

The exception that was thrown is inconsistent with the documentation, which says that the condition type is BoolTensor, but the exception that was thrown says that the expected condition type is ScalarType Byte, so it's hard to expect BoolTensor.

### Versions

pytorch: 1.8.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
Operating System：Windows

**Comment by samdow** [comment]
On 1.13, the latest version, this says
`RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Double`

**Comment by triumph-wangyuyang** [comment]
> On 1.13, the latest version, this says `RuntimeError: where expected condition to be a boolean tensor, but got a tensor with dtype Double`
