### ISSUE TITLE
Edge case: torch.nn.AvgPool1d's error message incorrectly describes what's wrong when giving an unexpected type

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89345]
### 🐛 Describe the bug

     import torch
     m = torch.nn.AvgPool1d(kernel_size="fff", stride=2)
     m(torch.tensor([[[1.,2,3,4,5,6,7]]]))

result: TypeError: avg_pool1d(): argument 'kernel_size' (position 2) must be tuple of ints, not tuple

In the test code, kernel_size is typed as str, but the exception description is tuple, which can be changed to:
ERROR:avg_pool1d(): argument 'kernel_size' (position 2) must be tuple of ints, not str

### Versions

pytorch: 1.12.1
Python version: 3.9
CUDA/cuDNN version: cuDNN 11.6
GPU models and configuration: RTX3060
Operating System：Windows 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by albanD** [comment]
This one as well has been update: `TypeError: avg_pool1d(): argument 'kernel_size' (position 2) must be tuple of ints, but found element of type str at pos 0`
That is good right?

**Comment by triumph-wangyuyang** [comment]
> 这个也已经更新了：那很好吧？`TypeError: avg_pool1d(): argument 'kernel_size' (position 2) must be tuple of ints, but found element of type str at pos 0`

Yes, the latest version's description is accurate.

**Comment by triumph-wangyuyang** [comment]
> This one as well has been update: `TypeError: avg_pool1d(): argument 'kernel_size' (position 2) must be tuple of ints, but found element of type str at pos 0` That is good right?

Yes, the latest version's description is accurate.
