### ISSUE TITLE
torch.nn.ConstantPad1d: An exception exists in the case of a particular parameter

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89347]
### 🐛 Describe the bug

pytorch 1.8.0 : 

    import torch
    m = torch.nn.ConstantPad1d((False, False), 3.5)
    input = torch.randn(1, 2, 4)
    print(m(input))

result:  tensor([[[ 0.6636, -0.4095,  0.5528, -0.5412], [ 1.1639, -0.9278,  0.2626,  0.2062]]])

pytorch 1.12 : 

    import torch
    m = torch.nn.ConstantPad1d((False, False), 3.5)
    input = torch.randn(1, 2, 4)
    print(m(input))

result:  TypeError: pad(): argument 'pad' (position 2) must be tuple of ints, not tuple

torch.nn.ConstantPad1d gets a different result on the pytorch version. For the padding parameter, the test code is (False,False), which translates to (0,0) according to python's default values. So it works on pytorch1.8, but when it runs on pytorch1.12, it throws an exception, and the exception message is incorrect. The exception message says (False,False) is not a tuple, but in fact, (False,False) is a tuple, so this torch.nn.ConstantPad1d has two exceptions in pytorch1.12.

### Versions

pytorch: 1.8.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
Operating System：Windows 

pytorch: 1.12.1
Python version: 3.9
CUDA/cuDNN version: cuDNN 11.6
GPU models and configuration: RTX3060
Operating System：Windows 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by albanD** [comment]
The arg parser was actually recently improved and the new error for this is now: `TypeError: pad(): argument 'pad' (position 2) must be tuple of ints, but found element of type bool at pos 0`.
That should be good right?

**Comment by triumph-wangyuyang** [comment]
> The arg parser was actually recently improved and the new error for this is now: .
> That should be good right?`TypeError: pad(): argument 'pad' (position 2) must be tuple of ints, but found element of type bool at pos 0`

Yes, the latest version's description is accurate.

**Comment by triumph-wangyuyang** [comment]
The same problem exists with torch.nn.ConstantPad2d and torch.nn.ConstantPad3d.
The exception message says (False, False, False, False) is not a tuple, but in fact, (False, False, False, False) is a tuple

    import torch
    m = torch.nn.ConstantPad2d((False, False, False, False), 3.5)
    input_2d = torch.randn(1, 2, 4, 4)  # 4D input tensor
    print(m(input_2d))

result: TypeError: pad(): argument 'pad' (position 2) must be tuple of ints, not tuple

    import torch
    m = torch.nn.ConstantPad3d((False, False, False, False, False, False), 3.5)
    input_3d = torch.randn(1, 2, 4, 4, 4)
    print(m(input_3d))

TypeError: pad(): argument 'pad' (position 2) must be tuple of ints, not tuple



pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.6
GPU models and configuration: RTX3060
Operating System：Windows
