### ISSUE TITLE
torch.matrix_rank: An inaccurate description of the input dimension

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89341]
### 🐛 Describe the bug

pytorch 1.9.0:

    import torch
    input = torch.rand([2, 2, 3, 1, 3], dtype=torch.float32)
    print(torch.matrix_rank(input))

result: tensor([[[1, 1, 1],[1, 1, 1]], [[1, 1, 1],[1, 1, 1]]])

In the official document, the description of input is to input a 2-D tensor, but when I input more than 2 dimensions, the code can also run successfully. Therefore, it is suggested to modify the description limit of input.

pytorch1.12.1:

    import torch
    input = torch.rand([2], dtype=torch.float32)
    print(torch.matrix_rank(input))

result: IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

torch.matrix_rank is used to returns the numerical rank of a 2-D tensor,when I enter dimension 1, I throw an exception that doesn't seem to match the real situation.

### Versions

code1:
  pytorch: 1.9.0
  Python version: 3.8
  CUDA/cuDNN version: cuDNN 11.1
  GPU models and configuration: RTX3060
  Operating System：Windows 11

code2:
  pytorch: 1.12.1
  Python version: 3.8
  CUDA/cuDNN version: cuDNN 11.3
  GPU models and configuration: RTX3060
  Operating System：Windows 11

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by samdow** [comment]
Where are you seeing that it says that input has to be a 2D tensor? [Here](https://pytorch.org/docs/1.13/generated/torch.linalg.matrix_rank.html?highlight=matrix_rank#torch.linalg.matrix_rank
) I'm seeing "A (Tensor) – tensor of shape (*, m, n) where * is zero or more batch dimension" which matches the behavior you're seeing in the first behavior

For the second, totally agree that that could be a better error messaging. I'm guessing this could be done by changing the ordering of some of the error messages

**Comment by triumph-wangyuyang** [comment]
> matrix_rank

Hello, thank you for your reply, the pytorch1.13 version has changed, but I tested the pytorch1.12 version, according to the official document of pytorch1.12 article, input (Tensor) – the input 2-D tensor, the requirement A is A two-dimensional tensor. However, the operator torch.matrix_rank has been replaced by torch.linalg.matrix_rank in the pytroch1.13 version.

**Comment by triumph-wangyuyang** [comment]
> Where are you seeing that it says that input has to be a 2D tensor? [Here](https://pytorch.org/docs/1.13/generated/torch.linalg.matrix_rank.html?highlight=matrix_rank#torch.linalg.matrix_rank) I'm seeing "A (Tensor) – tensor of shape (*, m, n) where * is zero or more batch dimension" which matches the behavior you're seeing in the first behavior
> 
> For the second, totally agree that that could be a better error messaging. I'm guessing this could be done by changing the ordering of some of the error messages

Hello, thank you for your reply, the pytorch1.13 version has changed, but I tested the pytorch1.12 version, according to the official document of pytorch1.12 article, input (Tensor) – the input 2-D tensor, the requirement A is A two-dimensional tensor. However, the operator torch.matrix_rank has been replaced by torch.linalg.matrix_rank in the pytroch1.13 version.

**Comment by lezcano** [comment]
We don't backport fixes, so there's not much we can do here. This does not even exist now in PyTorch. If you find a similar error in master on `linalg.matrix_rank` please feel free to send a new issue.
