### ISSUE TITLE
torch.numel returns a tensor instead of an int

### ISSUE THREAD

**Issue by yuguo68** [pytorch/pytorch#89350]
### 🐛 Describe the bug

This was first reported internally.  

```
import torch
a = torch.zeros([3])
torch.numel(a)
# tensor(3)
a.numel()
# 3
```

However, torch.numel should return an int as described in https://pytorch.org/docs/stable/generated/torch.numel.html. 

This seems to be a recent regression caused by https://github.com/pytorch/pytorch/pull/88956. 
Locally reverting it can fix the issue. 

cc: @SherlockNoMad @ezyang 

### Versions

on torch==1.14.0a0+git154e58c

**Comment by SherlockNoMad** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/88956/files#r1027157841
