### ISSUE TITLE
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

### ISSUE THREAD

**Issue by Nigel-Amers** [pytorch/pytorch#8935]
- CUDA/cuDNN version:8/5

[ 87%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/CUDAByteStorage.cpp.o
In file included from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:79:0:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"
  ^
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:5:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/GridSampler.cpp:27:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"
  ^
In file included from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp:28:0:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"
  ^
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:5:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/BatchNorm.cpp:31:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"
  ^
In file included from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/RNN.cpp:58:0:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"
  ^
In file included from /home/liufang/Pytorch/aten/src/ATen/cuda/detail/CUDAHooks.cpp:15:0:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:10:2: error: #error "CuDNN version not supported"
 #error "CuDNN version not supported"
  ^
In file included from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp:28:0:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
 uDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1")
                                                                               ^
[ 87%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/CUDAByteTensor.cpp.o
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:3:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp:30:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h: In member function ‘void at::native::RNNDescriptor::set(cudnnHandle_t, int, int, at::native::DropoutDescriptor&&, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t)’:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:304:11: error: ‘CUDNN_RNN_ALGO_STANDARD’ was not declared in this scope
           CUDNN_RNN_ALGO_STANDARD,
           ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        
       ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:305:19: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope
           datatype));
                   ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        
       ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
 #pragma message ("CuDNN v" STRING(CUDNN_MAJOR) " found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1")
                                                                                                                                                                                                      ^
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:5:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/GridSampler.cpp:27:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
 #pragma message ("CuDNN v" STRING(CUDNN_MAJOR) " found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1")
                                                                                                                                                                                                      ^
In file included from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/RNN.cpp:58:0:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
 #pragma message ("CuDNN v" STRING(CUDNN_MAJOR) " found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1")
                                                                                                                                                                                                      ^
[ 87%] Building CXX object caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/CUDAByteType.cpp.o
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:5:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/BatchNorm.cpp:31:
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
 #pragma message ("CuDNN v" STRING(CUDNN_MAJOR) " found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1")
                                                                                                                                                                                                      ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/cudnn-wrapper.h:9:198: note: #pragma message: CuDNN v5 found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1
 #pragma message ("CuDNN v" STRING(CUDNN_MAJOR) " found, but need at least CuDNN v6. You can get the latest version of CuDNN from https://developer.nvidia.com/cudnn or disable CuDNN with NO_CUDNN=1")
                                                                                                                                                                                                      ^
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:3:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:80:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h: In member function ‘void at::native::RNNDescriptor::set(cudnnHandle_t, int, int, at::native::DropoutDescriptor&&, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t)’:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:304:11: error: ‘CUDNN_RNN_ALGO_STANDARD’ was not declared in this scope
           CUDNN_RNN_ALGO_STANDARD,
           ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:305:19: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope
           datatype));
                   ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-aligned-allocation-unavailable’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-typedef-redefinition’
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:3:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/GridSampler.cpp:27:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h: In member function ‘void at::native::RNNDescriptor::set(cudnnHandle_t, int, int, at::native::DropoutDescriptor&&, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t)’:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:304:11: error: ‘CUDNN_RNN_ALGO_STANDARD’ was not declared in this scope
           CUDNN_RNN_ALGO_STANDARD,
           ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:305:19: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope
           datatype));
                   ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:105806: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/AffineGridGenerator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:3:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/RNN.cpp:59:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h: In member function ‘void at::native::RNNDescriptor::set(cudnnHandle_t, int, int, at::native::DropoutDescriptor&&, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t)’:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:304:11: error: ‘CUDNN_RNN_ALGO_STANDARD’ was not declared in this scope
           CUDNN_RNN_ALGO_STANDARD,
           ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:305:19: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope
           datatype));
                   ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In function ‘perf_t at::native::getBestAlgorithm(perf_t*, bool, int)’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:445:41: error: ‘CUDNN_DETERMINISTIC’ was not declared in this scope
           perfResults[i].determinism == CUDNN_DETERMINISTIC) {
                                         ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In static member function ‘static at::native::algorithm_search<cudnnConvolutionFwdAlgo_t>::perf_t at::native::algorithm_search<cudnnConvolutionFwdAlgo_t>::findAlgorithm(const at::native::ConvolutionArgs&)’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:474:38: error: ‘CUDNN_CONVOLUTION_FWD_ALGO_COUNT’ was not declared in this scope
     static constexpr int num_algos = CUDNN_CONVOLUTION_FWD_ALGO_COUNT;
                                      ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In static member function ‘static at::native::algorithm_search<cudnnConvolutionBwdDataAlgo_t>::perf_t at::native::algorithm_search<cudnnConvolutionBwdDataAlgo_t>::findAlgorithm(const at::native::ConvolutionArgs&)’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:543:38: error: ‘CUDNN_CONVOLUTION_BWD_DATA_ALGO_COUNT’ was not declared in this scope
     static constexpr int num_algos = CUDNN_CONVOLUTION_BWD_DATA_ALGO_COUNT;
                                      ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In static member function ‘static at::native::algorithm_search<cudnnConvolutionBwdFilterAlgo_t>::perf_t at::native::algorithm_search<cudnnConvolutionBwdFilterAlgo_t>::findAlgorithm(const at::native::ConvolutionArgs&)’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:612:38: error: ‘CUDNN_CONVOLUTION_BWD_FILTER_ALGO_COUNT’ was not declared in this scope
     static constexpr int num_algos = CUDNN_CONVOLUTION_BWD_FILTER_ALGO_COUNT - 1;
                                      ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In function ‘void at::native::findAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*)’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:688:65: error: ‘CUDNN_DETERMINISTIC’ was not declared in this scope
       !(args.params.deterministic && perfResults.determinism != CUDNN_DETERMINISTIC)) {
                                                                 ^
In file included from /home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:3:0,
                 from /home/liufang/Pytorch/aten/src/ATen/native/cudnn/BatchNorm.cpp:31:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h: In member function ‘void at::native::RNNDescriptor::set(cudnnHandle_t, int, int, at::native::DropoutDescriptor&&, cudnnRNNInputMode_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t)’:
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:304:11: error: ‘CUDNN_RNN_ALGO_STANDARD’ was not declared in this scope
           CUDNN_RNN_ALGO_STANDARD,
           ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Descriptors.h:305:19: error: ‘cudnnSetRNNDescriptor_v6’ was not declared in this scope
           datatype));
                   ^
/home/liufang/Pytorch/aten/src/ATen/cudnn/Exceptions.h:4:7: note: in definition of macro ‘AT_CUDNN_CHECK’
   if (STATUS != CUDNN_STATUS_SUCCESS) {                                        \
       ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In instantiation of ‘perf_t at::native::getBestAlgorithm(perf_t*, bool, int) [with perf_t = cudnnConvolutionFwdAlgoPerf_t]’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:492:86:   required from here
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:445:38: error: ‘struct cudnnConvolutionFwdAlgoPerf_t’ has no member named ‘determinism’
           perfResults[i].determinism == CUDNN_DETERMINISTIC) {
                                      ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In instantiation of ‘perf_t at::native::getBestAlgorithm(perf_t*, bool, int) [with perf_t = cudnnConvolutionBwdDataAlgoPerf_t]’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:561:86:   required from here
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:445:38: error: ‘struct cudnnConvolutionBwdDataAlgoPerf_t’ has no member named ‘determinism’
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In instantiation of ‘perf_t at::native::getBestAlgorithm(perf_t*, bool, int) [with perf_t = cudnnConvolutionBwdFilterAlgoPerf_t]’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:631:94:   required from here
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:445:38: error: ‘struct cudnnConvolutionBwdFilterAlgoPerf_t’ has no member named ‘determinism’
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In instantiation of ‘void at::native::findAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*) [with algo_t = cudnnConvolutionFwdAlgo_t]’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:708:16:   required from ‘at::native::Workspace at::native::chooseAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*) [with algo_t = cudnnConvolutionFwdAlgo_t]’
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:818:65:   required from here
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:688:62: error: ‘struct cudnnConvolutionFwdAlgoPerf_t’ has no member named ‘determinism’
       !(args.params.deterministic && perfResults.determinism != CUDNN_DETERMINISTIC)) {
                                                              ^
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In instantiation of ‘void at::native::findAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*) [with algo_t = cudnnConvolutionBwdDataAlgo_t]’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:708:16:   required from ‘at::native::Workspace at::native::chooseAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*) [with algo_t = cudnnConvolutionBwdDataAlgo_t]’
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:946:69:   required from here
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:688:62: error: ‘struct cudnnConvolutionBwdDataAlgoPerf_t’ has no member named ‘determinism’
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp: In instantiation of ‘void at::native::findAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*) [with algo_t = cudnnConvolutionBwdFilterAlgo_t]’:
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:708:16:   required from ‘at::native::Workspace at::native::chooseAlgorithm(const at::native::ConvolutionArgs&, bool, algo_t*) [with algo_t = cudnnConvolutionBwdFilterAlgo_t]’
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:1090:71:   required from here
/home/liufang/Pytorch/aten/src/ATen/native/cudnn/Conv.cpp:688:62: error: ‘struct cudnnConvolutionBwdFilterAlgoPerf_t’ has no member named ‘determinism’
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-aligned-allocation-unavailable’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-typedef-redefinition’
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:105878: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/GridSampler.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/GridSampler.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-aligned-allocation-unavailable’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-typedef-redefinition’
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:105854: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/Conv.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/Conv.cpp.o] Error 1
cc1plus: warning: unrecognized command line option ‘-Wno-aligned-allocation-unavailable’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-typedef-redefinition’
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:105998: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/cuda/detail/CUDAHooks.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/cuda/detail/CUDAHooks.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-aligned-allocation-unavailable’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-typedef-redefinition’
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:105830: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/BatchNorm.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/BatchNorm.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-aligned-allocation-unavailable’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-private-field’
cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-typedef-redefinition’
cc1plus: warning: unrecognized command line option ‘-Wno-invalid-partial-specialization’
caffe2/CMakeFiles/caffe2_gpu.dir/build.make:105902: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/RNN.cpp.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/ATen/native/cudnn/RNN.cpp.o] Error 1
CMakeFiles/Makefile2:1638: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

**Comment by vishwakftw** [comment]
Can you try updating your `cuDNN` to 7?

**Comment by li-roy** [comment]
ATen requires at least cudnn 6.

**Comment by zou3519** [comment]
Closing because of @li-roy's comment
