### ISSUE TITLE
Source build of PyTorch cannot find MKL installed in Conda lib by default

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#89360]
### 🐛 Describe the bug

Steps to reproduce:
1. Install mkl via conda
2. Build PyTorch using stock `python setup.py develop`

Expected: has MKL
Actual: doesn't. I find adding `CMAKE_PREFIX_PATH=$CONDA_PREFIX BLAS=MKL` can make it work

Related but probably different https://github.com/pytorch/pytorch/issues/73008

cc @malfet @seemethere @atalman 

### Versions

master

**Comment by ezyang** [comment]
This reliably reproduces for me on the devfair, AWS cluster and devgpu. LMK if you can't repro on your environment.

**Comment by ezyang** [comment]
Might be a dupe of https://github.com/pytorch/pytorch/issues/31598

**Comment by ezyang** [comment]
Maybe also https://github.com/pytorch/pytorch/issues/21135

**Comment by ngimel** [comment]
Instructions suggest setting conda prefix path `export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`
