### ISSUE TITLE
torch.nn.functional.embedding_bag throws an exception when it runs on a CPU, but it runs successfully on a GPU.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89362]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    input = torch.randint(-5, 1, [1, 2], dtype=torch.int64)
    weight = torch.rand([2, 3], dtype=torch.float32)
    print(torch.nn.functional.embedding_bag(input, weight))

result: RuntimeError: Index 0 is out of bounds: -1, range 0 to 2

Test on the GPU:

    import torch
    input = torch.randint(-5, 1, [1, 2], dtype=torch.int64).cuda()
    weight = torch.rand([2, 3], dtype=torch.float32).cuda()
    print(torch.nn.functional.embedding_bag(input, weight))

result: tensor([[0., 0., 0.]], device='cuda:0')
embedding_bag execution on a CPU throws an exception, but it runs successfully on a GPU.

### Versions

pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by albanD** [comment]
We would accept a PR adding a device assert in the CUDA kernel for this!

**Comment by triumph-wangyuyang** [comment]
> We would accept a PR adding a device assert in the CUDA kernel for this!

Thanks for your reply.
