### ISSUE TITLE
RuntimeError: "log_softmax_lastdim_kernel_impl" not implemented for 'Half'

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89366]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    input = torch.rand([5], dtype=torch.float16)
    print(torch.nn.functional.log_softmax(input, dim=-1))

result: RuntimeError: "log_softmax_lastdim_kernel_impl" not implemented for 'Half'

Test on the GPU:

    import torch
    input = torch.rand([5], dtype=torch.float16).cuda()
    print(torch.nn.functional.log_softmax(input, dim=-1))

result: tensor([-1.8008, -1.4404, -1.8320, -1.4131, -1.6367], device='cuda:0', dtype=torch.float16)
Why does running on a cpu throw an exception, but running on cuda doesn't?

### Versions

pytorch: 1.12
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

**Comment by vadimkantorov** [comment]
It's because most ops in float16 (half) aren't available on CPU as things aren't accelerated in hardware for float16, so most of the time one would use bfloat16 there.

There might be rare exceptions, but basically that's the reason.

**Comment by ngimel** [comment]
Right, fp16 ops are generally not supported on cpu.

**Comment by triumph-wangyuyang** [comment]
This happens with torch.tanh as well.

Test on the CPU:

    import torch
    input = torch.rand([2], dtype=torch.float16)
    out = torch.tanh(input)
    print(out)

result: RuntimeError: "tanh" "_vml_cpu" not implemented for 'Half'


Test on the GPU:

    import torch
    input = torch.rand([2], dtype=torch.float16).cuda()
    out = torch.tanh(input)
    print(out)

result: tensor([0.6851, 0.5728], device='cuda:0', dtype=torch.float16)
