### ISSUE TITLE
 torch.nn.functional.linear runs on the CPU and GPU different exception thrown.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89364]
### 🐛 Describe the bug

  Test on the CPU: 

    import torch
    input = torch.rand([5, 5, 5], dtype=torch.float64)
    weight = torch.rand([64, 64], dtype=torch.float32)
    bias = torch.rand([64], dtype=torch.float32)
    torch.nn.functional.linear(input, weight, bias)

result: RuntimeError: mat1 and mat2 shapes cannot be multiplied (25x5 and 64x64)

Test on the GPU:

    import torch
    input = torch.rand([5, 5, 5], dtype=torch.float64).cuda()
    weight = torch.rand([64, 64], dtype=torch.float32).cuda()
    bias = torch.rand([64], dtype=torch.float32).cuda()
    torch.nn.functional.linear(input, weight, bias)

result: RuntimeError: expected scalar type Double but found Float

In pytorch1.9.0 version, torch.nn.functional.linear runs on the CPU and GPU different exception thrown.

### Versions

pytorch: 1.9.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
Operating System：Windows 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel @nairbv

**Comment by albanD** [comment]
Hi,

We do not guarantee that different devices do input checking in the same order.
In particular, there are two errors here: dtype mismatch and shape error. If you fix either the dtype mismatch or the shape error, then you will see the other error in both cases. So both cases are properly checked by each implementation.

So I think this has the expected behavior.
More generally, looking at other devices, the error messages might be different as well.

**Comment by triumph-wangyuyang** [comment]
> dtype mismatch and shape error

So according to your understanding, are there two defects of dtype mismatch and shape error in the above test code of torch.nn.functional.linear?

**Comment by albanD** [comment]
> So according to your understanding, are there two defects of dtype mismatch and shape error in the above test code of torch.nn.functional.linear?

Correct. The dtype should match and the shape should enable a valid mm.
You can see this by changing the input to either all be of the same dtype or fixing the shape to be a valid mm and you'll see that you still get the other error.

**Comment by triumph-wangyuyang** [comment]
> > So according to your understanding, are there two defects of dtype mismatch and shape error in the above test code of torch.nn.functional.linear?
> 
> Correct. The dtype should match and the shape should enable a valid mm. You can see this by changing the input to either all be of the same dtype or fixing the shape to be a valid mm and you'll see that you still get the other error.

Thank you for your reply, I understand, I hope this kind of problem can be solved in the next version.
