### ISSUE TITLE
torch.nn.Linear gives different results on CPU and GPU.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89379]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    m = torch.nn.Linear(in_features=128, out_features=1)
    input = torch.rand([302], dtype=torch.float32)
    print(m(input))

result: RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x302 and 128x1)

Test on the GPU:

    import torch
    m = torch.nn.Linear(in_features=128, out_features=1).cuda()
    input = torch.rand([302], dtype=torch.float32).cuda()
    print(m(input))

result: tensor([-0.2693], device='cuda:0', grad_fn=<AddBackward0>)

torch.nn.Linear will throw an exception on the CPU on the pytorch1.9.0 version, but it can run successfully on the GPU.

### Versions

pytorch: 1.9.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
Operating System：Windows 

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by jgong5** [comment]
The error reported on CPU is expected since the input's `Hin` is not equal to `in_features`. Seems we should report errors on GPU too.

**Comment by triumph-wangyuyang** [comment]
> The error reported on CPU is expected since the input's `Hin` is not equal to `in_features`. Seems we should report errors on GPU too.

Agreed, the exception message should be consistent.

**Comment by samdow** [comment]
This errors on GPU in more recent versions (1.13)
