### ISSUE TITLE
Feature request: complex CUDA nn.silu()

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89382]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    m = torch.nn.SiLU()
    input = torch.rand([2], dtype=torch.complex64)
    print(m(input))

result: tensor([0.0490+0.3563j, 0.0439+0.1437j])

Test on the GPU:

    import torch
    m = torch.nn.SiLU().cuda()
    input = torch.rand([2], dtype=torch.complex64).cuda()
    print(m(input))

result: RuntimeError: "silu_cuda" not implemented for 'ComplexFloat'

The test code runs successfully on the torch.nn.SiLU() CPU, but throws an exception on the GPU.

The same situation exists for torch.nn.functional.silu.
### Versions

pytorch: 1.8
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel @ezyang @anjali411 @dylanbespalko @Lezcano @nikitaved

**Comment by albanD** [comment]
We would accept a PR adding this.

**Comment by shogohida** [comment]
Hi @albanD, can I work on this? It would be nice if you can give me some clues 🙏 

Should I refer to these?
https://github.com/pytorch/pytorch/issues/37925
https://github.com/pytorch/pytorch/pull/37959

**Comment by lezcano** [comment]
sure thing, @shogohida go for it. Grepping for `silu_cuda` (as in the error) should take you to the right place. The fix should be straightforward, looking at how other kernels support complex numbers.

**Comment by shogohida** [comment]
@lezcano 
Thanks for your comment! I made a pull request so please have a look. I looked at other examples and thought I needed to put `AT_DISPATCH_FLOATING_AND_COMPLEX_TYPES_AND2`

https://github.com/pytorch/pytorch/pull/89649

**Comment by triumph-wangyuyang** [comment]
The same situation exists for torch.nn.functional.silu.

Test on the CPU:  

    import torch

    input = torch.rand([2], dtype=torch.complex64)
    output = torch.nn.functional.silu(input)
    print(output)

result: tensor([0.1025+0.0591j, 0.2629+0.3254j])

Test on the GPU:  

    import torch

    input = torch.rand([2], dtype=torch.complex64).cuda()
    output = torch.nn.functional.silu(input)
    print(output)

result:RuntimeError: "silu_cuda" not implemented for 'ComplexFloat'

The test code runs successfully on the torch.nn.functional.silu() CPU, but throws an exception on the GPU.

### Versions

pytorch: 1.8
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
