### ISSUE TITLE
[Feature request] Get cell state from the last layer for each t when using LSTM

### ISSUE THREAD

**Issue by valsworthen** [pytorch/pytorch#8938]
Hello there, 

from the doc of `nn.LSTM`, the forward method outputs `output, (h_n, c_n)`. 
Currently `output` contains the "output features (h_t) from the last layer of the LSTM, for each t". I'd find it interesting if output also returned the cell state from the last layer for each t.

Indeed, when trying to feed a LSTM with its predictions (for time series) you need to also provide the "new initial" hidden state, which is *not* (`h_n`, `c_n`).

For example, for a sequence of length n, if you want to predict values t+1 for each t, you just have to input a null hidden state and the LSTM will output the predicted values. However, if now you want to predict values t+2 from the previously predicted values, you need to input a non-zero hidden state, which is (`h_1`,` c_1`) (compared to `h_n`, `c_n`).

You can easily get `h_1` from `output`, but not `c_1`. Then you have to use LSTMCell which is much slower. Not that this is not a problem for RNN / GRU.

I hope I'm making myself clear in the example and request.

Thanks

**Comment by zou3519** [comment]
Definitely clear, @valsworthen, this is something we are working on.

**Comment by t-vi** [comment]
This would preclude using CuDNN, would it?

**Comment by cyxtj** [comment]
Hi,  is there any progress or timeline for this feature?

**Comment by cassiopeiabear** [comment]
Hi, recently, I have the same problem， I want to get cell state of LSTM and newgates of GRU at each time in cuda case ,  Is therer a good solution to this problem?

**Comment by myaooo** [comment]
Hi, I have similar issues here. Is there any update on this feature?

**Comment by viking-sudo-rm** [comment]
+1, this would be a useful change to the LSTM interface!

**Comment by colesbury** [comment]
@zou3519 can you give na update on this?

**Comment by ThorJonsson** [comment]
I would love this feature!

**Comment by zou3519** [comment]
Instead of using the nn.LSTM, one alternative to get the cell state from the last layer is to write an LSTM via the PyTorch JIT and have it return what you'd like. The JIT optimizes its LSTMs pretty well so the performance should be similar to that of nn.LSTM for many use cases. 

See here for more details: https://pytorch.org/blog/optimizing-cuda-rnn-with-torchscript/

**Comment by soumith** [comment]
considering that using custom RNNs is the only way this is possible (because nn.LSTM's backing CUDNN LSTM does not allow extraction of intermediate states), I am closing this request with @zou3519 's answer above as the way forward.
