### ISSUE TITLE
nn.NLLLoss behaves differently on CPU and GPU.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89404]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    loss = torch.nn.NLLLoss()
    input = torch.randn(3, 5, requires_grad=True)
    target = torch.randint(-32, 32, torch.Size([3]))
    res = loss(input, target)

result: IndexError: Target -31 is out of bounds.

Test on the GPU:

    import torch
    loss = torch.nn.NLLLoss().cuda()
    input = torch.randn(3, 5, requires_grad=True).cuda()
    target = torch.randint(-32, 32, torch.Size([3])).cuda()
    res = loss(input, target)

nn.NLLLoss behaves differently on CPU and GPU.

### Versions

pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

**Comment by samdow** [comment]
FWIW, I was able to get GPU to also error. It's possible that the random values happened to stay within the right range on a certain run

**Comment by ngimel** [comment]
Closing, GPU error out on invalid values
