### ISSUE TITLE
torch.nn.functional.max_unpool1d exhibits different behavior on different devices.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89409]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    input = torch.rand([1, 1, 4], dtype=torch.float32)
    indices = torch.randint(-24, 24, [1, 1, 4], dtype=torch.int64)
    out = torch.nn.functional.max_unpool1d(input, indices, kernel_size=3, stride=None, padding=0, output_size=None)
    print(out)

result: RuntimeError: Found an invalid max index: -5 (output volumes are of size 12x1

Test on the GPU:

    import torch
    input = torch.rand([1, 1, 4], dtype=torch.float32).cuda()
    indices = torch.randint(-24, 24, [1, 1, 4], dtype=torch.int64).cuda()
    out = torch.nn.functional.max_unpool1d(input, indices, kernel_size=3, stride=None, padding=0, output_size=None)
    print(out)

result: tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,0.0000, 0.0000, 0.0000, 0.7101]]], device='cuda:0')

When I was learning the torch.nn.functional.max_unpool1d operator recently, I found that when an invalid input was input, I was surprised to find that there were different results on the CPU and GPU, and torch.nn.functional.max_unpool2d, torch.nn.functional.max_unpool3d, torch.nn.MaxUnpool1d, torch.nn.MaxUnpool2d, torch.nn.MaxUnpool3d have the same problem.

### Versions

pytorch: 1.8
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by albanD** [comment]
Hi,

Unfortunately, we're not able to do as much error checking on the CUDA side as we do on the CPU side. That's why some invalid inputs are let through on the CUDA side while they raise a nice error on CPU.

**Comment by triumph-wangyuyang** [comment]
> 你好
> 
> 不幸的是，我们无法在 CUDA 端进行像在 CPU 端那样多的错误检查。这就是为什么一些无效的输入在 CUDA 端被允许通过，同时它们在 CPU 上引发一个很好的错误。
> 
> 更新：我们应该在 cuda 内核中抛出一个设备断言。我们会接受添加此类支票的 PR！

If the exception is thrown properly, it can be more helpful to understand, thank you.

**Comment by albanD** [comment]
Yes!
Are you interested in working towards adding these checks by any chance?

**Comment by triumph-wangyuyang** [comment]
> Yes! Are you interested in working towards adding these checks by any chance?

'm not an expert at this to add these code checks.

**Comment by isdanni** [comment]
Looking at `CUDA_KERNEL_ASSERT(...);` in `aten/src/Aten/native/cuda`:

https://github.com/pytorch/pytorch/blob/f9a250c35bd061e2e6f4c2d92e2b1b16390e8636/aten/src/ATen/native/cuda/MaxUnpooling.cu#L46-L48

https://github.com/pytorch/pytorch/blob/f9a250c35bd061e2e6f4c2d92e2b1b16390e8636/aten/src/ATen/native/cuda/MaxUnpooling.cu#L68-L70

V.S. [aten/src/ATen/native/cpu/MaxUnpoolKernel.cpp](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cpu/MaxUnpoolKernel.cpp):

https://github.com/pytorch/pytorch/blob/f9a250c35bd061e2e6f4c2d92e2b1b16390e8636/aten/src/ATen/native/cpu/MaxUnpoolKernel.cpp#L69-L89

It seems like MaxUnpool already checks max index vs. output size, just like in CPU, not sure why there still is unmatched errors on both devices.

**Comment by albanD** [comment]
Hi,
Maybe these have been added since then.
Tentatively closing this as the tests are now there. Feel free to re-open/comment if they're still missing when using nightly.
