### ISSUE TITLE
The exception thrown by torch.sparse_coo_tensor running on GPU is confusing.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89402]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    indices = torch.rand([1, 0], dtype=torch.float32)
    values = []
    size = [1]
    out = torch.sparse_coo_tensor(indices, values, size)
    print(out)

result: tensor(indices=tensor([], size=(1, 0)), values=tensor([], size=(0,)),size=(1,), nnz=0, layout=torch.sparse_coo)

Test on the GPU:

    import torch
    indices = torch.rand([1, 0], dtype=torch.float32).cuda()
    values = []
    size = [1]
    out = torch.sparse_coo_tensor(indices, values, size)
    print(out)

result: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument values in method wrapper___sparse_coo_tensor_with_dims_and_tensors)

I'm confused about the exception thrown by torch.sparse_coo_tensor running on GPU.

### Versions

pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by amjames** [comment]
When you pass an empty list as `values` it will be converted into a tensor with the default device type, so by the time you enter the `sparse_coo_tensor` implementation you have `indices`  with device `cuda:0` and values with device `cpu`. 

Would it help if the message was explicit about which device was associated with each argument?

**Comment by triumph-wangyuyang** [comment]
> When you pass an empty list as it will be converted into a tensor with the default device type, so by the time you enter the implementation you have with device and values with device .`values``sparse_coo_tensor``indices``cuda:0``cpu`
> 
> Would it help if the message was explicit about which device was associated with each argument?

If there is an association between a device and a parameter default, I recommend stating that in the documentation.

**Comment by pearu** [comment]
Currently, the device of a constructed sparse tensor is defined by the values device, see
https://github.com/pytorch/pytorch/blob/f45fe7de3378047d4c3b34af67ecfbd4934ff537/torch/csrc/utils/tensor_new.cpp#L1146-L1165

Changing the error message as defined in
https://github.com/pytorch/pytorch/blob/d089fbdc33f75dc34b87d4eefff0fd296ef1d6a6/aten/src/ATen/core/adaption.cpp#L6-L11
does not seem as simple as one would wish.

I suggest updating the sparse tensor constructor documentation with the following note:

```diff
diff --git a/torch/_torch_docs.py b/torch/_torch_docs.py
index 34195f938b..0a36a1a85f 100644
--- a/torch/_torch_docs.py
+++ b/torch/_torch_docs.py
@@ -10471,6 +10471,18 @@ Constructs a :ref:`sparse tensor in COO(rdinate) format
 
    This function returns an :ref:`uncoalesced tensor <sparse-uncoalesced-coo-docs>`.
 
+.. note::
+
+   If the ``device`` argument is specified, the device of the
+   constructed sparse tensor as well as its ``indices`` and ``values``
+   will be the specified device. All the input tensors well be
+   converted to the specified device if needed.
+
+   If the ``device`` argument is not specified, the device of the
+   constructed sparse tensor is defined by the ``values`` device. A
+   RuntimeError exception is raised if the devices of ``indices`` and
+   ``values`` turn out to be different.
+
 Args:
     indices (array_like): Initial data for the tensor. Can be a list, tuple,
         NumPy ``ndarray``, scalar, and other types. Will be cast to a :class:`torch.LongTensor`

```

A similar note should be added to the docs of `sparse_csr/csc/bsr/bsc_tensor` functions.
