### ISSUE TITLE
torch.masked_select passes in the same parameters, but gives different results on CPU and GPU.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89415]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    input = torch.rand([8], dtype=torch.float32)
    mask = torch.randint(0, 8, [8], dtype=torch.uint8)
    out = torch.masked_select(input, mask)
    print(out)

result: RuntimeError: Mask tensor can take 0 and 1 values only

Test on the GPU:

    import torch
    input = torch.rand([8], dtype=torch.float32).cuda()
    mask = torch.randint(0, 8, [8], dtype=torch.uint8).cuda()
    out = torch.masked_select(input, mask)
    print(out)

result: tensor([0.6693, 0.7604, 0.6873, 0.3366, 0.5178, 0.5001, 0.8818],  device='cuda:0')

torch.masked_select passes in the same parameters, but gives different results on CPU and GPU.

### Versions

pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

**Comment by triumph-wangyuyang** [comment]
Is there any progress on this issue?

**Comment by mingfeima** [comment]
@CaoE , could you please investigate into this issue ?

**Comment by CaoE** [comment]
Sure. Will look at it soon.

**Comment by CaoE** [comment]
@triumph-wangyuyang This is because cuda use index for masked_select, and it will convert mask to index. In addition, indexing with dtype torch.uint8 is not recommended and torch.bool instead is recommended according to the warning raised by latest pytorch. On CPU, we can insert `mask.to(dtype=torch.bool)` to get the same result as on CUDA.

**Comment by CaoE** [comment]
Close it. @triumph-wangyuyang If you have questions you can reopen it  at any time.
