### ISSUE TITLE
torch.nn.functional.conv1 passes in the same parameters, but gets different results on CPU and GPU.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89412]
### 🐛 Describe the bug

Test on the CPU:

    import torch
    weight = torch.randn(20, 16, 5)
    input= torch.randn(33, 16, 30)
    out = torch.nn.functional.conv1d(input, weight, bias=None, stride=1, padding=0, dilation=-1, groups=1)

result: RuntimeError: could not create a descriptor for a dilated convolution forward propagation primitive

Test on the GPU:

    import torch
    weight = torch.randn(20, 16, 5).cuda()
    input= torch.randn(33, 16, 30).cuda()
    out = torch.nn.functional.conv1d(input, weight, bias=None, stride=1, padding=0, dilation=-1, groups=1)

result: RuntimeError: dilation should be greater than zero but got (1, -1) (while checking arguments for cudnn_convolution)

torch.nn.functional.conv1 passes in the same parameters, but gets different results on CPU and GPU.

### Versions

pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by jiayisunx** [comment]
The check of these args has been added in PyTorch 1.13 and master branch, and now we can get the following RuntimeError in your test: 
RuntimeError: non-positive dilation is not supported
FYI, the related PR: https://github.com/pytorch/pytorch/pull/76526.

**Comment by triumph-wangyuyang** [comment]
> The check of these args has been added in PyTorch 1.13 and master branch, and now we can get the following RuntimeError in your test: RuntimeError: non-positive dilation is not supported FYI, the related PR: #76526.

Ok, thanks for your reply.

**Comment by triumph-wangyuyang** [comment]
The same problem exists with torch.nn.Conv1d

Test on the CPU:

    import torch
    conv_layer = torch.nn.Conv1d(in_channels=16, out_channels=20, kernel_size=5, stride=1, padding=0, dilation=-1, groups=1)
    input_tensor = torch.randn(33, 16, 30)
    output_tensor = conv_layer(input_tensor)

result: RuntimeError: could not create a descriptor for a dilated convolution forward propagation primitive

Test on the GPU:

    import torch
    conv_layer = torch.nn.Conv1d(in_channels=16, out_channels=20, kernel_size=5, stride=1, padding=0, dilation=-1, groups=1).cuda()
    input_tensor = torch.randn(33, 16, 30).cuda() 
    output_tensor = conv_layer(input_tensor)

result: RuntimeError: dilation should be greater than zero but got (1, -1) (while checking arguments for cudnn_convolution)
