### ISSUE TITLE
@torch.no_grad causes pickling error when using more than one GPU

### ISSUE THREAD

**Issue by dscarmo** [pytorch/pytorch#89450]
### 🐛 Describe the bug

I was having problems spinning a 2 GPU training due to Pickle saying an object for a class in my code wasn't pickable for the multiple GPU multiprocessing. Here is the traceback:
```
Traceback (most recent call last):
  File "/Users/santosdocarmo/diedre_phd/phd/starter.py", line 260, in <module>
    trainer.fit(model, datamodule=PreprocessedSegDatasetDataModule(hparams, train_transform=transform, eval_transform=eval_transform))
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 107, in launch
    mp.start_processes(
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
    process.start()
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/santosdocarmo/miniconda3/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'transforms.ConditionalCropOrPadAndPatching'>: it's not the same object as transforms.ConditionalCropOrPadAndPatching
```

I tried to reproduce the pickle bug in Google COLAB and it seems to be caused by the @torch.no_grad decorator on one of my transforms. 

Here is the reproduction: https://colab.research.google.com/drive/1reV9eA0zB5iyjgB1wqK3nSHG3_hDovJB?usp=sharing

It spits exactly the same error that I get when trying 2 GPU training: "Can't pickle [...] it's not the same object as [..]". It doesn't happen when I don't use the decorator.

I noticed that the version is older than the current stable version, however my original code is running in 1.12.1. Is this intentional? Is the decorator just not supported by multi GPU training? Thank you. 

### Versions

> Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26
Python version: 3.7.15 (default, Oct 12 2022, 19:14:55)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment]
Hi,

This should not happen and I can't reproduce that:
```
import torch
import pickle

@torch.no_grad()
def foo(x):
    return 3

pickle.dumps((foo,))
```

Would you have an example showing this issue that we can run to reproduce this?

**Comment by dscarmo** [comment]
> Hi,
> 
> This should not happen and I can't reproduce that:
> 
> ```
> import torch
> import pickle
> 
> @torch.no_grad()
> def foo(x):
>     return 3
> 
> pickle.dumps((foo,))
> ```
> 
> Would you have an example showing this issue that we can run to reproduce this?

Hi! I reproduced it in Google Colab: https://colab.research.google.com/drive/1reV9eA0zB5iyjgB1wqK3nSHG3_hDovJB?usp=sharing

**Comment by albanD** [comment]
Thanks for the repro.

So you actually decorate the class itself!
Could you describe what you expect to happen when you do that?

My current thinking is that it doesn't do the thing you expect and we should update torch.no_grad to raise a nice error if you try to decorate a class. You can decorate specific methods if you want them not to require gradients.

**Comment by dscarmo** [comment]
Oh I see, I got that from another code that was doing the same a long time ago, and assumed no_grad worked as a class decorator (somehow making everything from the class not require gradients). 

Then the issue is solved, thank you for the clarification.
