### ISSUE TITLE
torch.renorm gets different results in different pytoch versions.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89478]
### 🐛 Describe the bug

code: 

    import torch
    input = torch.rand([2, 2, 2], dtype=torch.float64)
    out = torch.renorm(input, p=2, dim=1, maxnorm=-5)
    print(out)

pytorch 1.9.0 result:    tensor([[[-0.5690, -0.3032], [-0.9717, -3.5014]],[[-1.2529, -4.7973],[-3.2936, -0.9738]]], dtype=torch.float64)

pytorch 1.12.1 result:    RuntimeError: renorm: expected maxnorm to be >= 0 but got -5

The official documentation of torch.renorm on pytoch1.9.0 and pytorch1.12.1 is exactly the same, but the results are different.

### Versions

pytorch: 1.12.1
pytorch: 1.9.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

**Comment by H-Huang** [comment]
Seems like 1.9 could have just been a bug since a negative `maxnorm` doesn't make sense. So it looks like it is fixed in 1.12

**Comment by triumph-wangyuyang** [comment]
> Seems like 1.9 could have just been a bug / unexpected behavior since a negative doesn't make sense. So it looks like it is fixed in 1.12`maxnorm`

I understand what you mean, max_norm should not have done a reasonable check in pytorch1.9.0 version, and then added a check in pytorch1.12 and above.

**Comment by H-Huang** [comment]
Agree!
