### ISSUE TITLE
sandcastle_skip_if decorator name is confusing

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#89473]
`sandcastle_skip_if` actually also skips in OSS CI: https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L3590-L3592

This caused a lot of confusion, for example with https://github.com/pytorch/pytorch/pull/89023

The decorator should be renamed to something like `skip_oss_pass_sandcastle_if`.

cc @mruberry

**Comment by kit1980** [comment]
Same issue for `sandcastle_skip`.

**Comment by mruberry** [comment]
Should be an easy fix. Name bikeshed: `skip_but_pass_in_sandcastle_if`. Why doesn't `skipIf` just pass when in Sandcastle so we don't need this, by the way?

**Comment by kit1980** [comment]
> Why doesn't `skipIf` just pass when in Sandcastle so we don't need this, by the way?

It's `unittest.skipIf`, so it doesn't know about Sandcastle?
