### ISSUE TITLE
DDP Always get oom after running for 10+ hours in docker container.

### ISSUE THREAD

**Issue by scse-l** [pytorch/pytorch#89479]
### 🐛 Describe the bug

DDP get OOM after running for 10+ hours in docker container. It seems all right before memory increases suddenly at some time and program crashes. 

Docker image: nvcr.io/nvidia/pytorch:22.02-py3
code sample: pytorch example of imagenet (https://github.com/pytorch/examples/tree/main/imagenet)
dataset: mini imagenet dataset from kaggle (https://www.kaggle.com/datasets/ifigotin/imagenetmini-1000)
command: python main.py -a resnet50 --dist-url 'tcp://127.0.0.1:8080' --dist-backend 'nccl' --multiprocessing-distributed --world-size 1 --rank 0 --epochs 5000 /path/to/dataset

### Versions

Collecting environment information...
PyTorch version: 1.11.0a0+17540c5
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.21.3
Libc version: glibc-2.31

Python version: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.54-1.0.0.std7c.el7.2.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla V100-PCIE-32GB
GPU 2: Tesla V100-PCIE-32GB
GPU 3: Tesla V100-PCIE-32GB

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.11.0a0+17540c5
[pip3] torch-tensorrt==1.1.0a0
[pip3] torchtext==0.12.0a0
[pip3] torchvision==0.12.0a0
[conda] magma-cuda110             2.5.2                         5    local
[conda] mkl                       2019.5                      281    conda-forge
[conda] mkl-include               2019.5                      281    conda-forge
[conda] numpy                     1.22.2           py38h6ae9a64_0    conda-forge
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     1.11.0a0+17540c5          pypi_0    pypi
[conda] torch-tensorrt            1.1.0a0                  pypi_0    pypi
[conda] torchtext                 0.12.0a0                 pypi_0    pypi
[conda] torchvision               0.12.0a0                 pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by H-Huang** [comment]
Hi, a couple of questions:

- do you have the stack trace?
- is this error reproducible / deterministic?
- what does the GPU utilization look like during training?

I would also recommend that you checkpoint the model so that not all your work is gone after 10+ hours.

**Comment by scse-l** [comment]
> Hi, a couple of questions:
> 
> * do you have the stack trace?
> * is this error reproducible / deterministic?
> * what does the GPU utilization look like during training?
> 
> I would also recommend that you checkpoint the model so that not all your work is gone after 10+ hours.

Sorry for the late reply.
1. There is no stack trace.
2. For me, this is absolutely reproducible. It may occur at 170 epoch, or 500 epoch or 1000 epoch, the program always crashed after 10+ hours.
3. About 95%, it looks pretty good.

**Comment by scse-l** [comment]
@H-Huang hello, is there any update?

**Comment by scse-l** [comment]
The same as: https://github.com/pytorch/pytorch/issues/106294.
