### ISSUE TITLE
Feature Request: deterministic CUDA cumsum

### ISSUE THREAD

**Issue by agarwalmanvi** [pytorch/pytorch#89492]
### 🚀 The feature, motivation and pitch

There is no deterministic implementation for `cumsum_cuda_kernel`. It would be nice to have this!

### Additional context

This can currently still be used by setting the `warn_only` flag to `True`.
Warning:
`cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:82.)`

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @ptrblck @mruberry @kurtamohler @ngimel

**Comment by ngimel** [comment]
cc @ptrblck, @zasdfgbnm - any progress on deterministic cumsum from cub? We can make deterministic warning/error more targeted and make it fire only for cub path (if we are not doing this already), but we still rely on cub for 1d cumsums.

**Comment by vors** [comment]
We also would like to request the same :)

**Comment by vors** [comment]
Seems like it used to not error out before 1.13.0 ...
Was it because it simply was silently non-deterministic and now it's reported?

I asked my specific question on the PyTorch Forum https://discuss.pytorch.org/t/cumsum-cuda-kernel-determinism/168820

**Comment by ngimel** [comment]
Yes, it was silently non-deterministic (for floating-point numbers)

**Comment by ptrblck** [comment]
I don't see any updates from cub besides [this RFE](https://github.com/NVIDIA/cub/issues/471) to discuss adding new deterministic algorithms. We should make sure the warning/error is only raised when needed and then follow up with a CUB on the progress.

**Comment by emailweixu** [comment]
I also would like to have deterministic cumsum too.

**Comment by msaroufim** [comment]
Hi @ptrblck any chance there's an update on this? It's coming up in the context of the SAM model 

* Logs https://ossci-raw-job-status.s3.amazonaws.com/log/15075070160
* The original model definition https://github.com/pytorch/benchmark/tree/main/torchbenchmark/models/sam

**Comment by ptrblck** [comment]
CC @eqy

**Comment by ezyang** [comment]
Triton supports scans (and therefore cumsum) now, maybe we can get a deterministic implementation out of that now.

**Comment by Jamie725** [comment]
May I know if there's any updates of deterministic implementation of cumsum now? Thanks!

**Comment by eqy** [comment]
Linking the discussion from cub on this request: https://github.com/NVIDIA/cccl/issues/886

**Comment by iwehf** [comment]
I would like a deterministic cumsum too.

**Comment by bernardo-torres** [comment]
I would like to support the idea of a having deterministic cumsum!

**Comment by hypnopump** [comment]
I would like a deterministic cumsum too.

**Comment by NLHuang** [comment]
I would like to request a deterministic cumsum as well.

**Comment by janeyx99** [comment]
@kurtamohler do you plan to work on this as it looks to have garnered some popularity?

**Comment by kurtamohler** [comment]
@janeyx99, sure I will work on it this week

**Comment by kurtamohler** [comment]
Reopened since the PR was reverted
