### ISSUE TITLE
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1603729047590/work/torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch. 

### ISSUE THREAD

**Issue by docxmxm** [pytorch/pytorch#89555]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main(args)
  File "train.py", line 197, in main
    bpp, pc_coor, cd = model(points, global_step=global_step)
  File "/home/zhe/anaconda3/envs/PCT_PCC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhe/Downloads/PCTPCC/PCT_PCC/models/PCT_PCC.py", line 95, in forward
    new_feature0 = self.feature_enhence2(new_xyz0, decoder_local_feature.permute(0, 2, 1),l0_xyz).permute(0, 2, 1)
  File "/home/zhe/anaconda3/envs/PCT_PCC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zhe/Downloads/PCTPCC/PCT_PCC/models/utils.py", line 364, in forward
    downsample_num = self.get_density(xyz, l0_xyz)
  File "/home/zhe/Downloads/PCTPCC/PCT_PCC/models/utils.py", line 351, in get_density
    uniques, counts = torch.unique(ori2sample_idx[i], return_counts=True)
  File "/home/zhe/anaconda3/envs/PCT_PCC/lib/python3.7/site-packages/torch/_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "/home/zhe/anaconda3/envs/PCT_PCC/lib/python3.7/site-packages/torch/_jit_internal.py", line 265, in fn
    return if_true(*args, **kwargs)
  File "/home/zhe/anaconda3/envs/PCT_PCC/lib/python3.7/site-packages/torch/functional.py", line 756, in _return_counts
    output, _, counts = _unique_impl(input, sorted, return_inverse, return_counts, dim)
  File "/home/zhe/anaconda3/envs/PCT_PCC/lib/python3.7/site-packages/torch/functional.py", line 682, in _unique_impl
    return_counts=return_counts,
RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1603729047590/work/torch/csrc/autograd/functions/utils.h":64, please report a bug to PyTorch.

### Versions

Collecting environment information...
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.17

Python version: 3.7.15 (default, Nov  7 2022, 22:00:21)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-122-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 11.0.194
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] pytorch3d==0.3.0
[pip3] torch==1.7.0
[pip3] torchaudio==0.7.0a0+ac17b64
[pip3] torchvision==0.8.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.21.5           py37h6c91a56_3  
[conda] numpy-base                1.21.5           py37ha15fc14_3  
[conda] pytorch                   1.7.0           py3.7_cuda11.0.221_cudnn8.0.3_0    pytorch
[conda] pytorch3d                 0.3.0           py37_cu110_pyt170    pytorch3d
[conda] torchaudio                0.7.0                      py37    pytorch
[conda] torchvision               0.8.0                py37_cu110    pytorch

**Comment by jlukehubbard** [comment]
It would be helpful to see a code example that reproduces the issue, ideally a minimum-viable example instead of the entire offending file.

Here's the context where the internal assert failed. Maybe reading the code there will help you find/reproduce the issue.

https://github.com/pytorch/pytorch/blob/master/torch/csrc/autograd/functions/utils.h#L67#L81

**Comment by albanD** [comment]
There isn't much context here, this error will happen if you try to set requires_grad=True on a non-continuous dtype Tensor.
Closing this issue. Feel free to open a new issue and follow the bug report template to explain what your issue is!
