### ISSUE TITLE
dtype conversion failure when adding tensors without dimension

### ISSUE THREAD

**Issue by marlinsiebert** [pytorch/pytorch#89565]
### 🐛 Describe the bug
Data types are not cast properly when adding tensors without dimension, which can lead to errors:

```python
import torch

# adding two tensors with dimension casts dtype to `float64`
(torch.tensor([1], dtype=torch.float16) + torch.tensor([1], dtype=torch.float64)).dtype
#> torch.float64

# adding a tensor without dimension to a tensor with dimension doesn't cast the dtype to `float64`
(torch.tensor([1], dtype=torch.float16) + torch.tensor(1, dtype=torch.float64)).dtype
#> torch.float16
# expected: torch.float64 or raise an exception
# the same applies for `float32`
```

### Versions

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.8 (default, Feb 24 2021, 21:46:12)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 495.29.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch

cc @nairbv @mruberry

**Comment by marlinsiebert** [comment]
This might be true, but from a users perspective it easily leads to errors, e.g. when using mixed precision.
Maybe one should raise an error if a number with higher precision is added, but not the other way round (because this wouldn't cause any problems).

**Comment by kshitij12345** [comment]
As @jgong5 mentioned, this is a documented behaviour and here is the reference to the docs.

Ref: https://pytorch.org/docs/stable/tensor_attributes.html#type-promotion-doc

@mruberry could shed more light about this behaviour.

**Comment by mruberry** [comment]
@jgong5 and @kshitij12345 are correct, this is expected behavior. It may be surprising in some circumstances, but PyTorch gives lower priority to the datatypes of tensors with empty shapes, also known as "number" or "scalar" tensors.
