### ISSUE TITLE
PyTorch not compiling on Windows with C++17

### ISSUE THREAD

**Issue by mantaionut** [pytorch/pytorch#89577]
### 🐛 Describe the bug

I created this issue in order to track my progress on helping with the Windows build of
[85969](https://github.com/pytorch/pytorch/pull/85969)

### Versions

N/A

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
Thank you for creating the issue, but I think I've ironed out all the problems. Perhaps you can explain why changing the standard to C++17 results in `error C2872: 'std': ambiguous symbol` when compiling code with files that extend `std::hash`?

**Comment by mantaionut** [comment]
I am not sure what is causing the compiling issue. I'll have to inevstigate that. When I tested it seems that every std under if constexpr get `error C2872: 'std': ambiguous symbol`. But I fixed locally that issue by using ::std instead.

**Comment by malfet** [comment]
Yes, I understand, that one can fix it this way, but it would be good to understand is this a bug in VC++ or indeed some rule in C++17 standard that PyTorch codebase does not follow

**Comment by mantaionut** [comment]
The error happens in the branch that does not execute of an if constexpr inside a template function. It happens because there are two `std` functions defined in a namespace that is used.
I think this is a compiler issue, though the error is the only thing we see because this is in the branch that doesn't execute. Hence, I think adding the `::` is an ok workaround. Let me know if you have other ideas, I can investigate.
I managed to create a small snippet that reproduces:
```
#include <iostream>
namespace namespaceThatContainsSTD
{
    /*There are 3 functions named std defined in build\aten\src\ATen\ops\std.h in namespace at at
    //Then in torch\csrc\autograd\generated\VariableType_2.cpp there is using namespace at
    */
    void std(int i) {}
    void std(char* i){}
}

using namespace namespaceThatContainsSTD;
template<typename T>
void templateFunction()
{
    std::cout << "this one compiles\n";
    if constexpr (true)
        std::cout << "compiles";
    else
        std::cout << "does not compile";
}

int main()
{
    templateFunction<int>();
    return 0;
}

```
