### ISSUE TITLE
IndexError when using F.pad with MPS backend (Mac m1)

### ISSUE THREAD

**Issue by morkovka1337** [pytorch/pytorch#89624]
### 🐛 Describe the bug

Hi,

I'm facing the issue with using torch.nn.functional.pad with MPS backend. I've installed MMDetection version 3.x and trying to [verify the solution](https://mmdetection.readthedocs.io/en/3.x/get_started.html#verify-the-installation). 

Under the hood it fails to execute pad operation. Simplest code to reproduce:
```
import torch
t = torch.rand(3, 214, 320)
# this works
torch.nn.functional.pad(t, tuple([0, 0, 0, 10, 0, 0]), value=0)
# and this does not:
torch.nn.functional.pad(t.to(torch.device('mps')), tuple([0, 0, 0, 10, 0, 0]), value=0)
# IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
```

There was a [similar problem](https://github.com/pytorch/pytorch/issues/83343), the fix was merged, but seems like it was not fully resolved.

### Versions

PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.15 (default, Nov 10 2022, 13:14:48)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchvision==0.14.0
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by bunnell** [comment]
Is this fixed in torch version 1.13.1? I am seeing what appears to be the same issue with 2D tensors.

`t = torch.rand(21, 32)
torch.nn.functional.pad(t, tuple([0, 0, 0, 10]), value=0)  # Works fine
torch.nn.functional.pad(t.to(torch.device('mps')), tuple([0, 0, 0, 10]), value=0)  # Fails
#IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
`
This is with
Python 3.10
macOS 13.0.1
M1 Mini

**Comment by qqaatw** [comment]
> Is this fixed in torch version 1.13.1? I am seeing what appears to be the same issue with 2D tensors.
> 
> `t = torch.rand(21, 32)
> 
> torch.nn.functional.pad(t, tuple([0, 0, 0, 10]), value=0) # Works fine
> 
> torch.nn.functional.pad(t.to(torch.device('mps')), tuple([0, 0, 0, 10]), value=0) # Fails
> 
> #IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2) ` This is with Python 3.10 macOS 13.0.1 M1 Mini

I'm not seeing an error with your code on the PyTorch nightly version, can you please check if it works on nightly?

**Comment by sfc-gh-wjaskowski** [comment]
I experience the same problem on M1 with torch 1.13.1. Should be reopened. 
```
% python
Python 3.10.10 (main, Mar 21 2023, 13:41:05) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> t = torch.rand(3, 214, 320)
>>> # this works
>>> torch.nn.functional.pad(t, tuple([0, 0, 0, 10, 0, 0]), value=0)
tensor([[[0.2264, 0.6232, 0.2979,  ..., 0.1833, 0.1263, 0.3802],
         [0.4056, 0.5292, 0.3353,  ..., 0.7868, 0.3148, 0.7775],
         [0.0290, 0.7775, 0.3720,  ..., 0.4916, 0.3119, 0.1489],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.8980, 0.5363, 0.6309,  ..., 0.4083, 0.5224, 0.8857],
         [0.8306, 0.8603, 0.4049,  ..., 0.5391, 0.8727, 0.9655],
         [0.6113, 0.4171, 0.2438,  ..., 0.6680, 0.5184, 0.2632],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.5786, 0.9698, 0.1153,  ..., 0.8911, 0.6231, 0.7715],
         [0.4604, 0.0126, 0.2296,  ..., 0.3593, 0.3013, 0.0287],
         [0.9769, 0.2866, 0.3337,  ..., 0.1617, 0.6004, 0.5976],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]])
>>> # and this does not:
>>> torch.nn.functional.pad(t.to(torch.device('mps')), tuple([0, 0, 0, 10, 0, 0]), value=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
>>> # IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
KeyboardInterrupt
>>> torch.__version__
'1.13.1'
```

**Comment by kulinseth** [comment]
> I experience the same problem on M1 with torch 1.13.1. Should be reopened.
> 
> ```
> % python
> Python 3.10.10 (main, Mar 21 2023, 13:41:05) [Clang 14.0.6 ] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> t = torch.rand(3, 214, 320)
> >>> # this works
> >>> torch.nn.functional.pad(t, tuple([0, 0, 0, 10, 0, 0]), value=0)
> tensor([[[0.2264, 0.6232, 0.2979,  ..., 0.1833, 0.1263, 0.3802],
>          [0.4056, 0.5292, 0.3353,  ..., 0.7868, 0.3148, 0.7775],
>          [0.0290, 0.7775, 0.3720,  ..., 0.4916, 0.3119, 0.1489],
>          ...,
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
> 
>         [[0.8980, 0.5363, 0.6309,  ..., 0.4083, 0.5224, 0.8857],
>          [0.8306, 0.8603, 0.4049,  ..., 0.5391, 0.8727, 0.9655],
>          [0.6113, 0.4171, 0.2438,  ..., 0.6680, 0.5184, 0.2632],
>          ...,
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
> 
>         [[0.5786, 0.9698, 0.1153,  ..., 0.8911, 0.6231, 0.7715],
>          [0.4604, 0.0126, 0.2296,  ..., 0.3593, 0.3013, 0.0287],
>          [0.9769, 0.2866, 0.3337,  ..., 0.1617, 0.6004, 0.5976],
>          ...,
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
>          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]])
> >>> # and this does not:
> >>> torch.nn.functional.pad(t.to(torch.device('mps')), tuple([0, 0, 0, 10, 0, 0]), value=0)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
> >>> # IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)
> KeyboardInterrupt
> >>> torch.__version__
> '1.13.1'
> ```
 @sfc-gh-wjaskowski Can you please try with latest 2.0 release or the nightly to see if this issue exists ?

**Comment by sfc-gh-wjaskowski** [comment]
Checked. In torch 2.0 works fine but I am not ready to move yet.
