### ISSUE TITLE
`make_fx` makes tensors unpickleable

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#89626]
### 🐛 Describe the bug

The use of make_fx appears to attach something to the example input tensors which makes them unpickleable:

Output:
```
Pickling works OK before make_fx
Traceback (most recent call last):
  File "/tmp/repro2.py", line 12, in <module>
    pickle.dumps(inputs)
TypeError: cannot pickle 'weakref.ReferenceType' object
```

Repro:
```
import pickle
import torch
from torch.fx.experimental.proxy_tensor import make_fx

inputs = [torch.randn(2, 3)]
def forward(x):
    return torch.tanh(x)

pickle.dumps(inputs)
print("Pickling works OK before make_fx")
make_fx(forward)(*inputs)
pickle.dumps(inputs) # Throws exception
```

The [`dill`](https://pypi.org/project/dill/) pickler gets further and reveals that the issue is a PythonKeyTracer attached to the tensor somehow which holds an FX graph which has an OpOverloadPacket which is unpickleable:

```
#Pickling of the tensor
(<function _rebuild_tensor_v2 at 0x7f56346d56c0>, <class 'torch.Tensor'>, ( 1.0...
#In the metadata, there is:
{<object object at 0x7f557529e6b0>: <WeakKeyDictionary at 0x7f556a3efbb0>}
# In that WeakKeyDictionary there is:
{'data': {<weakref at 0x7f5615372ed0; to 'PythonKeyTracer' at 0x7f556a3ee5c0>: _...
# In the tracer, we eventually get to:
<class 'torch.fx.graph.Graph'>
# Which then leads us to
<class 'torch._ops.OpOverloadPacket'>
# Which then leads to a pickling error
TypeError("cannot pickle 'torch._C.FunctionSchema' object")
```

### Versions

PyTorch version: 1.14.0.dev20221114+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 12.2.0-3) 12.2.0
Clang version: 14.0.6-2
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov  3 2022, 15:17:13) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-5.18.16-1rodete4-amd64-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221114+cpu
[pip3] torchvision==0.15.0.dev20221114+cpu
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
Oh yeah, this is an unfortunate interaction. We store some state in a private `__dict__` entry on tensor, this used to not matter for serialization but we turned on serialization Python attributes recently. Need to exclude this from serialization woof.
