### ISSUE TITLE
[typing] `torch.nn.utils.rnn.pad_sequence` has too strict type hint.

### ISSUE THREAD

**Issue by randolf-scholz** [pytorch/pytorch#89623]
### 🐛 Describe the bug

As per definition, it accepts `Tensor | list[Tensor]`.

https://github.com/pytorch/pytorch/blob/4f5c4c022a8365d06ac401582958bbf0fd3f8337/torch/nn/utils/rnn.py#L340-L344

However, the function body only requires `Tensor | Iterable[Tensor]`. Allowing `Iterable[Tensor]` would be nice so that generator expressions can be passed without raising type errors in `mypy`.

### Versions

master branch  / 1.13

cc @zou3519 @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by zou3519** [comment]
This seems reasonable, we'd accept a patch fixing this.
