### ISSUE TITLE
[dynamo] RuntimeError: Failed running call_function aten._to_copy(*(FakeTensor(FakeTensor(...

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#89633]
### 🐛 Describe the bug

I'm seeing the following error when running with dynamo

```
  File "/usr/local/google/home/silvasean/.local/lib/python3.10/site-packages/torch/_decomp/decompositions.py", line 1395, in _to_copy
    assert device is not None or dtype is not None or memory_format is not None
AssertionError
```

repro

```python
import torch
import torch._dynamo as dynamo


@dynamo.optimize("eager")
def forward(x):
    return torch.ops.aten._to_copy(x)


forward(torch.randn(3, 2, 4))
```

Full error log: https://gist.github.com/silvasean/2ad8e534cf8c2af20d3eda5d0874f9a6

### Versions

Collecting environment information...
PyTorch version: 1.14.0.dev20221114+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 12.2.0-3) 12.2.0
Clang version: 14.0.6-2
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov 3 2022, 15:17:13) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-5.18.16-1rodete4-amd64-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221114+cpu
[pip3] torchvision==0.15.0.dev20221114+cpu
[conda] Could not collect

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ngimel** [comment]
Fixed on master
