### ISSUE TITLE
`torch._C._nn.fractional_max_pool3d` Trigger Segmentation Fault

### ISSUE THREAD

**Issue by Kristoff-starling** [pytorch/pytorch#89648]
## 🐛 Describe the bug

A test for `torch._C._nn.fractional_max_pool3d` triggers segmentation fault.
### Test
```python
import torch

def test():
    self = torch.rand([2, 1, 4, 5, 4], dtype=torch.float32)
    kernel_size = [2, 2, 1]
    output_size = 2
    random_samples = torch.rand([0, 1, 3], dtype=torch.float32)
    result = torch._C._nn.fractional_max_pool3d(self, kernel_size, output_size, random_samples)

test()
```
### Error Log
`segmentation fault`

## Versions

```
PyTorch version: 1.14.0a0+gitbdc9911
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 11.1.0-6
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.14.0a0+gitbdc9911
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] torch                     1.14.0a0+gitce2f870          pypi_0    pypi
```

cc @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by lezcano** [comment]
this looks like it's missing a `TORCH_CHECK`

**Comment by ZailiWang** [comment]
random_samples cannot have length 0 in any of the dimensions. Otherwise the coredump happens at https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/FractionalMaxPool3d.cpp
`
  at::parallel_for(0, numPlanes, 0, [&](int64_t start, int64_t end) {
    for (const auto plane : c10::irange(start, end)) {
      /* each plane contains 3 random samples,
         one for T, one for W, and one for H */
      scalar_t* randomSamplesForPlane = randomSamples + plane * 3;

      /* Generate interval sequence */
      auto sequenceT = generate_intervals<scalar_t>(
          randomSamplesForPlane[0], inputT, outputT, poolSizeT);
      auto sequenceH = generate_intervals<scalar_t>(
          randomSamplesForPlane[1], inputH, outputH, poolSizeH);
      auto sequenceW = generate_intervals<scalar_t>(
          randomSamplesForPlane[2], inputW, outputW, poolSizeW);
`
And the similar check should also be added in fractional_max_pool1d & fractional_max_pool2d.

**Comment by mingfeima** [comment]
#89992 add shape check for `_random_samples`

**Comment by mingfeima** [comment]
`random_samples` is allowed to have zero batch dimension only when input has zero batch dimension, e.g.
```
# output will also has zero batch dimension
self = torch.rand([0, 1, 4, 5, 4], dtype=torch.float32)
random_samples = torch.rand([0, 1, 3], dtype=torch.float32)
```

**Comment by mingfeima** [comment]
@Kristoff-starling , this issue should have been fixed by https://github.com/pytorch/pytorch/pull/89992
could you please double check ?

**Comment by Kristoff-starling** [comment]
Hi @mingfeima , in the nightly version the execution of the test will lead to an expected invalid argument error. Thanks for the fix!
