### ISSUE TITLE
Failed to build from source - third-party build with default /usr/bin/c++, not with gcc-11

### ISSUE THREAD

**Issue by nidjan** [pytorch/pytorch#89681]
### 🐛 Describe the bug

I have trouble with build from source same as 
https://github.com/pytorch/FBGEMM/issues/1094
(but I have Intel QQLS CPU)

I build through makepkg with CC=gcc-11 and CXX=g++-11 - many works fine, but fails.
I try to view log and i find, that all third-party cmake-files dont use GCC-11 - third-party (benchmark and fbgemm as i see) use /usr/bin/c++ and -werror flag in cmake configs.

how and where change parameters of third-party cmake?

### Versions

Build PyTorch version: 1.12.1

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 12.2.0
Clang version: 14.0.6
CMake version: version 3.24.3
Libc version: glibc-2.36

Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-6.0.8-1-clear-x86_64-with-glibc2.36
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
ROCM = 5.3.0 (opencl-amd and opencl-amd-dev)
Magma = 2.6.1

Versions of relevant libraries:
[pip3] numpy==1.23.3
[conda] Could not collect

cc @malfet @seemethere

**Comment by malfet** [comment]
I don't think there is a good way to fix it for 1.12, but this should be fixed in master. Can you please elaborate, why do you think third_party libraires do not respect CPP/CXX set by main project?

**Comment by nidjan** [comment]
i think that my problem is a build it by `makepkg -e` some times.
after that i begin another clear build, i use command 
`makepkg`
correct headers in libkineto after fail as i say here
https://github.com/rocm-arch/python-pytorch-rocm/issues/60#issuecomment-1328102387
and build command 
`env CC=gcc-11 CXX=g++-11 CMAKE_C_COMPILER="/usr/bin/gcc-11" CMAKE_CXX_COMPILER="/usr/bin/g++-11" makepkg -e`
