### ISSUE TITLE
amd windows

### ISSUE THREAD

**Issue by vincyxiroff** [pytorch/pytorch#89699]
### 🚀 The feature, motivation and pitch

add it for amd windows too

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by malfet** [comment]
Closing as duplicate of https://github.com/pytorch/pytorch/issues/109204

(Although this one was added before the other issue has much more details)
