### ISSUE TITLE
old lua torch model to pytorch, nn.JoinTable(1,3) error

### ISSUE THREAD

**Issue by KangolHsu** [pytorch/pytorch#897]
My model generator  looks like this
>nn.Sequential {
>  [input -> (0) -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> (12) -> (13) -> (14) -> output]
>  (0): nn.JoinTable
>  (1): nn.SpatialFullConvolution(118 -> 512, 4x4)
>  (2): nn.SpatialBatchNormalization
>  (3): nn.ReLU
>  (4): nn.SpatialFullConvolution(512 -> 256, 4x4, 2, 2, 1, 1)
 > (5): nn.SpatialBatchNormalization
>  (6): nn.ReLU
>  (7): nn.SpatialFullConvolution(256 -> 128, 4x4, 2, 2, 1, 1)
>  (8): nn.SpatialBatchNormalization
>  (9): nn.ReLU
>  (10): nn.SpatialFullConvolution(128 -> 64, 4x4, 2, 2, 1, 1)
>  (11): nn.SpatialBatchNormalization
>  (12): nn.ReLU
>  (13): nn.SpatialFullConvolution(64 -> 3, 4x4, 2, 2, 1, 1)
>  (14): nn.Tanh
>}

Input: 
>Z = encZ.forward(X).resize_(1,100,1,1)  
>Y = encY.forward(X).resize_(1,18)

output:    size 3x64x64

old lua model use JoinTable like this:
>nn.JoinTable(1,3)

I use the code below to generate image
>reconstX = generator.forward(Z,Y)

Error ：
>Traceback (most recent call last):
>  File "test.py", line 88, in <module>
>    reconstX = generator.forward(Z,Y)
>TypeError: forward() takes exactly 2 arguments (3 given)

I only give 2 arguments ：Z and Y
why it said 3 arguments was given？Is the something wrong with me？

**Comment by apaszke** [comment]
Because the forward looks like that `def forward(self, input):` so it expects two arguments, but it gets self, Z and Y from you. `nn.Sequential` only accepts a single input.
