### ISSUE TITLE
C++ libtorch "rot 90()" has performance problems in the loop

### ISSUE THREAD

**Issue by djdll** [pytorch/pytorch#89705]
### 🐛 Describe the bug

C++ libotch1.7.1 cuda11.0
I put the data on cuda in a loop and then did a rot90 operation on the data, but the time was very erratic, up to 15ms, which was very strange
```C++
img_in = img_in.to(at::kCUDA);
while(1){
//code......
img_in = torch::rot90(img_in, 1, { (1), (2) });  //img_in.shap:[3,500,500]
//code.....
//Calculation time
}
The running time is between 0.01ms and 15ms, which is very abnormal and the time difference is very large.
```

### Versions

Describe the bug:
I'll give you a rough code for C++ 
img_in = img_in.to(at::kCUDA);
while(1){
//code......
img_in = torch::rot90(img_in, 1, { (1), (2) });  //img_in.shap:[3,500,500]
//code.....
//Calculation time:
}
The running time is between 0.01ms and 15ms, which is very abnormal and the time difference is very large.
Excuse me, is this time fluctuation normal.
Thanks.

**Comment by jlukehubbard** [comment]
Is the second argument of `rot90()` (let's call it `k`) always equal to 1 in your program? When `k` is equal to zero or any integer multiple of four, `rot90()` returns much more quickly, because there isn't any work to do. That could be your issue.
