### ISSUE TITLE
virtual memory exhausted: Cannot allocate memory 

### ISSUE THREAD

**Issue by Suyichuan98** [pytorch/pytorch#89725]
Hello, I am downloading torch into wsl2. when I use the command: python3.9 setpy.py. I run into the issue: virtual memory exhausted: Cannot allocate memory .

The error happens at the: Building CXX object test_tensorexpr/CMakeFiles/test_tensorexpr.dir/test_quantization.cpp.o

Following by this #82888 issue I found that I need to use build <something> single-thread, but what should I put in the middle? and how the syntax looks like? Since if I put the build nccl single-thread, it says such command cannot found.

Is there any solution for this?

**Comment by kshitij12345** [comment]
You can try setting `MAX_JOBS` env variable to control build parallelism.

https://github.com/pytorch/pytorch/blob/db1f1144f1303db45e0b9d96e4bb6bdd87c80e5a/setup.py#L11-L12

Eg would look like `MAX_JOBS=1 python setup.py build`

**Comment by albanD** [comment]
Closing as this was answered. Feel free to re-open if you still have issues!
