### ISSUE TITLE
[typing] torch.norm and Tensor.norm `p` type hint 

### ISSUE THREAD

**Issue by fd0r** [pytorch/pytorch#89727]
### 🐛 Describe the bug

`torch.norm` and `Tensor.norm` as `p="fro"` as default argument, thus is considered as `str` by `mypy` and other type checks solutions.
I suggest adding type hints to solve this.

### Versions

master, 1.13

cc @ezyang @malfet @rgommers @xuzhao9 @gramster @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by jlukehubbard** [comment]
https://github.com/pytorch/pytorch/blob/1d6a188d08829b1aee28eb1e6255d5bf43a77f16/torch/functional.py#L1390#L1400

Please use one of the functions provided in `torch.linalg`. `torch.norm` is deprecated.

(P.S. you may have seen this comment appear on your PR and then disappear, I posted it there by mistake at first)

**Comment by fd0r** [comment]
My bad, I missed it!
I guess since `Tensor.norm` refers back to `torch.norm` (``r"""See :func:`torch.norm`"""``) it is also deprecated? 
Or should we make it use `torch.linalg.norm` ?

**Comment by lezcano** [comment]
I would suggest that you use `linalg.vector_norm` and `linalg.matrix_norm` as these have much better defined behaviours. `torch.norm` and `Tensor.norm` are indeed deprecated, yes.
