### ISSUE TITLE
Compiling pytorch on MacOSX 10.13.5 with support for CUDA GeForceGT 750M

### ISSUE THREAD

**Issue by joseandrespena** [pytorch/pytorch#8974]
## Issue description

Compiling pytorch on MacOSX 10.13.5 with support for CUDA GeForceGT 750M 2048MB

## Code example

Error log
/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu:222:134: warning: self-comparison always evaluates to true [-Wtautological-compare]
switch (memType) { case CUDAHistogramMemoryType::SHARED:  (__cudaPushCallConfiguration(grid, block, (CUDAHistogramMemoryType::SHARED == CUDAHistogramMemoryType::SHARED) ? sharedMem : (0), at::globalContext().getCurrentCUDAStream())) ? (void)0 : kernelHistogram1D< output_t, input_t, int64_t, 1, 2, 1, CUDAHistogramMemoryType::SHARED> (aInfo, pInfo, bInfo, binsize, totalElements, getWeightsOp); if (!((cudaGetLastError()) == (cudaSuccess))) { throw Error({__func__, "/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu", 222}, at::str(at::str("cudaGetLastError() == cudaSuccess", " ASSERT FAILED at ", "/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu", ":", 222, ", please report a bug to PyTorch. ", "kernelHistogram1D failed"))); }  ; ; break; case CUDAHistogramMemoryType::MULTI_BLOCK:  (__cudaPushCallConfiguration(grid, block, (CUDAHistogramMemoryType::MULTI_BLOCK == CUDAHistogramMemoryType::SHARED) ? sharedMem : (0), at::globalContext().getCurrentCUDAStream())) ? (void)0 : kernelHistogram1D< output_t, input_t, int64_t, 1, 2, 1, CUDAHistogramMemoryType::MULTI_BLOCK> (aInfo, pInfo, bInfo, binsize, totalElements, getWeightsOp); if (!((cudaGetLastError()) == (cudaSuccess))) { throw Error({__func__, "/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu", 222}, at::str(at::str("cudaGetLastError() == cudaSuccess", " ASSERT FAILED at ", "/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu", ":", 222, ", please report a bug to PyTorch. ", "kernelHistogram1D failed"))); }  ; ; break; default:  (__cudaPushCallConfiguration(grid, block, (CUDAHistogramMemoryType::GLOBAL == CUDAHistogramMemoryType::SHARED) ? sharedMem : (0), at::globalContext().getCurrentCUDAStream())) ? (void)0 : kernelHistogram1D< output_t, input_t, int64_t, 1, 2, 1, CUDAHistogramMemoryType::GLOBAL> (aInfo, pInfo, bInfo, binsize, totalElements, getWeightsOp); if (!((cudaGetLastError()) == (cudaSuccess))) { throw Error({__func__, "/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu", 222}, at::str(at::str("cudaGetLastError() == cudaSuccess", " ASSERT FAILED at ", "/Users/josepen/Development/pytorch/aten/src/ATen/native/cuda/SummaryOps.cu", ":", 222, ", please report a bug to PyTorch. ", "kernelHistogram1D failed"))); }  ; ; }

## System Info
josepens-mbp:pytorch josepen$ python torch/utils/collect_env.py 
Collecting environment information...
PyTorch version: 0.5.0a0+290d20b
Is debug build: No
CUDA used to build PyTorch: 9.2

OS: Mac OSX 10.13.5
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.64
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda/lib/libcudnn.7.dylib
/usr/local/cuda/lib/libcudnn.dylib
/usr/local/cuda/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.5)
[pip3] torch (0.3.1)
[pip3] torchtext (0.2.3)
[pip3] torchvision (0.2.1)
[conda] torch                     0.5.0a0+290d20b           <pip>
[conda] torchtext                 0.2.3                     <pip>
[conda] torchvision               0.2.1                     <pip>
josepens-mbp:pytorch josepen$ 

- PyTorch or Caffe2: pytorch
- How you installed PyTorch (conda, pip, source): I'm compiling from source
- Build command you used (if compiling from source):  MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++ python setup.py install
- OS: MacOSX 10.13.5 
- PyTorch version: I cloned the repo this is the hash version
josepens-mbp:pytorch josepen$ git rev-parse HEAD
290d20b094dff35da866deafa92c12a6264dc544
- Python version: 3.6
- CUDA/cuDNN version: 9.2.64
- GPU models and configuration: GeForceGT 750M
- GCC version (if compiling from source): gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
- CMake version: cmake --version
cmake version 3.11.1
CMake suite maintained and supported by Kitware (kitware.com/cmake)
- Versions of any other relevant libraries:

**Comment by bingo619** [comment]
Cuda hasn't support llvm 9.1 yet, have to use 9.0 which is Command_Line_Tools_macOS_10.13_for_Xcode_9.2 or lower versions.

**Comment by joseandrespena** [comment]
@bingo619 can you point me out where in CUDA documentation says this incompatibility?
Beg your pardon, Do I have to downgrade what Apple LLVM version 9.1.0 ? How should I proceed? 
Thank you.

**Comment by joseandrespena** [comment]
This one, right? 
Command_Line_Tools_macOS_10.13_for_Xcode_9.2.dmg
<img width="731" alt="screen shot 2018-06-27 at 11 40 46 pm" src="https://user-images.githubusercontent.com/145929/42015212-a23419f2-7a63-11e8-958a-334ac813ed1b.png">
Uninstall the current installed Command Line Tools?

**Comment by joseandrespena** [comment]
@bingo619 buddy? are you there?

**Comment by yf225** [comment]
@joseandrespena We actually need Command Line Tools from Xcode 8.2 (macOS 10.12) to build PyTorch with CUDA 9.2 on macOS (because otherwise Eigen will give compilation error). The correct steps should be:

1. Install Command Line Tools from Xcode 8.2 (macOS 10.12) from https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.12_for_Xcode_8.2/Command_Line_Tools_macOS_10.12_for_Xcode_8.2.dmg

2. Set `export DEVELOPER_DIR=/Library/Developer/CommandLineTools`, then run `python setup.py install` to build PyTorch.

**Comment by alanderex** [comment]
@yf225 According to the CUDA docs Xcode **9**.2 incl. LLVM 9.0.0 is required, isn't it:
https://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html#system-requirements

I was forced to recompile PyTorch for
MacOS 10.13.6 (17G65)
Everything **worked**
I have the same message labeled *please report to PyTorch*, please see below:

python torch/utils/collect_env.py
      Collecting environment information...
      PyTorch version: 0.5.0a0+a24163a
      Is debug build: No
      CUDA used to build PyTorch: 9.2

      OS: Mac OSX 10.13.6
      GCC version: 
            Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-            dir=/usr/include/c++/4.2.1
            Apple LLVM version 9.0.0 (clang-900.0.39.2)
            Target: x86_64-apple-darwin17.7.0
            Thread model: posix
            InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
      CMake version: version 3.12.0

      Python version: 3.6
      Is CUDA available: Yes
      CUDA runtime version: 9.2.148
      GPU models and configuration: Could not collect
      Nvidia driver version: 387.10.10.10.40.105
      cuDNN version: Probably one of the following:
      /usr/local/cuda/lib/libcudnn.7.dylib
      /usr/local/cuda/lib/libcudnn.dylib
      /usr/local/cuda/lib/libcudnn_static.a

      Versions of relevant libraries:
      [pip] numpy (1.15.1)
      [pip] torch (0.5.0a0+a24163a)
      [conda] torch                     0.5.0a0+a24163a           <pip>

NVIDIA GeForce GTX 1080:

      Chipset Model: NVIDIA GeForce GTX 1080
      Type: External GPU
      Bus: PCIe
      PCIe Lane Width: x4
      VRAM (Dynamic, Max): 8191 MB
      Vendor: NVIDIA (0x10de)
      Device ID: 0x1b80
      Revision ID: 0x00a1
      ROM Revision: VBIOS 86.04.60.00.4a
      Metal: Supported, feature set macOS GPUFamily1 v3

`/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu:222:134: warning: self-comparison always evaluates to true [-Wtautological-compare]
switch (memType) { case CUDAHistogramMemoryType::SHARED:  (__cudaPushCallConfiguration(grid, block, (CUDAHistogramMemoryType::SHARED == CUDAHistogramMemoryType::SHARED) ? sharedMem : (0), (at::globalContext().getCurrentCUDAStream()))) ? (void)0 : kernelHistogram1D< output_t, input_t, int64_t, 1, 2, 1, CUDAHistogramMemoryType::SHARED> (aInfo, pInfo, bInfo, binsize, totalElements, getWeightsOp); if (!((cudaGetLastError()) == (cudaSuccess))) { throw Error({__func__, "/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu", 222}, at::str(at::str("cudaGetLastError() == cudaSuccess", " ASSERT FAILED at ", "/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu", ":", 222, ", please report a bug to PyTorch. ", "kernelHistogram1D failed"))); }  ; ; break; case CUDAHistogramMemoryType::MULTI_BLOCK:  (__cudaPushCallConfiguration(grid, block, (CUDAHistogramMemoryType::MULTI_BLOCK == CUDAHistogramMemoryType::SHARED) ? sharedMem : (0), (at::globalContext().getCurrentCUDAStream()))) ? (void)0 : kernelHistogram1D< output_t, input_t, int64_t, 1, 2, 1, CUDAHistogramMemoryType::MULTI_BLOCK> (aInfo, pInfo, bInfo, binsize, totalElements, getWeightsOp); if (!((cudaGetLastError()) == (cudaSuccess))) { throw Error({__func__, "/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu", 222}, at::str(at::str("cudaGetLastError() == cudaSuccess", " ASSERT FAILED at ", "/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu", ":", 222, ", please report a bug to PyTorch. ", "kernelHistogram1D failed"))); }  ; ; break; default:  (__cudaPushCallConfiguration(grid, block, (CUDAHistogramMemoryType::GLOBAL == CUDAHistogramMemoryType::SHARED) ? sharedMem : (0), (at::globalContext().getCurrentCUDAStream()))) ? (void)0 : kernelHistogram1D< output_t, input_t, int64_t, 1, 2, 1, CUDAHistogramMemoryType::GLOBAL> (aInfo, pInfo, bInfo, binsize, totalElements, getWeightsOp); if (!((cudaGetLastError()) == (cudaSuccess))) { throw Error({__func__, "/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu", 222}, at::str(at::str("cudaGetLastError() == cudaSuccess", " ASSERT FAILED at ", "/Users/hendorf/code/audiodrama/pytorch-compile/aten/src/ATen/native/cuda/SummaryOps.cu", ":", 222, ", please report a bug to PyTorch. ", "kernelHistogram1D failed"))); }  ; ; }  `

**Comment by yf225** [comment]
@alanderex If we are building against CUDA 9.2 then Xcode 9.0 toolchain will also work. Xcode 8.2 is the toolchain that supports CUDA 8.0/9.0/9.1/9.2.
