### ISSUE TITLE
performance problem on  dataloader with pinned memory

### ISSUE THREAD

**Issue by chenrui17** [pytorch/pytorch#89753]
### 🐛 Describe the bug
I am observing several hundreds ms bubbles in the GPU streams like this , and don't know why , and it happened several iterators randomly
![image](https://user-images.githubusercontent.com/33319780/204279668-0252095e-fe3e-40df-936c-9681ebcd63d8.png)

### Versions

torch：1.13.0 stable
CUDA used to build PyTorch: 11.7
GPU： NVIDIA A100 40G

cc @VitalyFedyunin @ngimel @SsnL @ejguan @NivekT

**Comment by chenrui17** [comment]
> Have you turned on `prefetch_factor` in `DataLoader`?

`prefetch_factor `  default value is 2 ，Isn't the default enabled ？ i try to adjust the value to 3 or 4, but it no change

**Comment by vedantroy** [comment]
@chenrui17 Out of curiosity, is this the Chrome trace viewer?

**Comment by chenrui17** [comment]
> @chenrui17 Out of curiosity, is this the Chrome trace viewer?

@vedantroy  nvidia nsight system profile tools

**Comment by fxmarty** [comment]
@chenrui17 Sorry for the off topic, but did you pass any special parameter to be able to see the call stack in nsight? I'm having trouble with this.

**Comment by ejguan** [comment]
@chenrui17 

Wondering how much time the model spent during one iteration? It might be the problem that model is too fast and make data-loading perf becomes a bottleneck. And, When `pin_memory` is `True`, `DataLoader` simply creates a python thread to move data to the pinned memory, which is bounded by Python GIL. It does block the training step when the GIL is acquired.
https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataloader.py#L1057-L1061

**Comment by chenrui17** [comment]
> @chenrui17 Sorry for the off topic, but did you pass any special parameter to be able to see the call stack in nsight? I'm having trouble with this.

add `-t osrt` in nsys command , my cmd is like this `nsys profile -y 80 -d 60 -t cuda,nvtx,osrt,cudnn,cublas --gpu-metrics-device=0 -w true -o xxx ` @fxmarty

**Comment by chenrui17** [comment]
> Wondering how much time the model spent during one iteration? It might be the problem that model is too fast and make data-loading perf becomes a bottleneck.

Thanks for your replay,  and each one iteration about 150ms, the above problem about `sem_wait` bubble is resolved by set `torch.set_num_threads(2)` code at  https://github.com/pytorch/pytorch/blob/master/torch/utils/data/_utils/pin_memory.py#L20

and also , by update torch version to 1.13 , resolved Python GIL bubbles problem https://github.com/pytorch/pytorch/issues/77139

but now,  I meet the bubble problem too , and I proposed at https://github.com/pytorch/pytorch/issues/91353 , the CPU operation （osrt stack）corresponding to the bubble is `munmap` , as shown in the figure below, could you plese help me to   figure out what's happenning in the gap. 
![image](https://user-images.githubusercontent.com/33319780/209818036-bd436ddf-7b7a-481c-acbe-02e80e4197ca.png)

**Comment by chenrui17** [comment]
closed this issue and now new performance problem is in https://github.com/pytorch/pytorch/issues/91353
