### ISSUE TITLE
InvokeAI using MPS is broken by torch nightlies since torch-1.14.0.dev20221104 inclusive 

### ISSUE THREAD

**Issue by Vargol** [pytorch/pytorch#89784]
### 🐛 Describe the bug

I'm sorry this  is going to be very generic, but I've been occasionally testing InvokeAI, a Stable Diffusion front end with the pytorch nightlies to see if the speed lost since 13.0 has returned. 
Today is the first time I've tested in a while and it was broken, generating colour noise not an image,
so I've been going back through the nightlies to see where the breakage is.

torch-1.14.0.dev20221102 works, 
torch-1.14.0.dev20221103 works if https://github.com/pytorch/pytorch/pull/87974 is reverted
torch-1.14.0.dev20221104 is broken if https://github.com/pytorch/pytorch/pull/87974 is reverted
torch-1.14.0.dev20221105 is broken
 
 That in theory narrows it down to https://github.com/pytorch/pytorch/pull/82809 and https://github.com/pytorch/pytorch/pull/88319 if its a MPS only issue

### Versions

PyTorch version: 1.14.0.dev20221103
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.0
Libc version: N/A

Python version: 3.10.8 (main, Nov  9 2022, 16:53:27) [Clang 12.0.5 (clang-1205.0.22.9)] (64-bit runtime)
Python platform: macOS-13.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.7.7
[pip3] torch==1.14.0.dev20221103
[pip3] torch-fidelity==0.3.0
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.10.0
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.0.dev20221128
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by Vargol** [comment]
It looks like the culprit is
[MPS] Add native cumsum implementation (https://github.com/pytorch/pytorch/pull/88319)

last working commit seems to be
git checkout 52173188efb3a8b3e5053357c66fd5bde45dc929

the breakage starts with
git checkout 657f2e12f0e212b2f4afd89ab2c824c409dcc951
which is the commit for the PR above.

**Comment by Vargol** [comment]
#90635 may be related.

**Comment by Birch-san** [comment]
thanks as always for your hard work digging into this @Vargol.  
I confirm that it reproduces in version built from recent master [`2.0.0a0+git2a23dfe`](https://github.com/pytorch/pytorch/commit/2a23dfe), on macOS 13.1 Ventura public beta 4.

```python
torch.cumsum(torch.arange(0,6, device='mps'), 0)
# tensor([0, 1, 2, 3, 4, 5], device='mps:0')

torch.cumsum(torch.arange(0,6), 0)
# tensor([ 0,  1,  3,  6, 10, 15])

torch.arange(0,6, device='mps').cumsum(0)
# tensor([0, 1, 2, 3, 4, 5], device='mps:0')

torch.arange(0,6).cumsum(0)
# tensor([ 0,  1,  3,  6, 10, 15])
```

I'm using this patch to work around it for now (re-introduces the fallback-to-CPU):

`cumsum_mps_fix.py`  
```python
# monkey-patch cumsum to fallback to CPU
# https://github.com/pytorch/pytorch/issues/89784
import torch
from torch import cumsum, Tensor
torch.cumsum = lambda input, *args, **kwargs: (
  cumsum(input.cpu() if input.device.type == 'mps' else input, *args, **kwargs).to(input.device)
)
orig_cumsum = torch.Tensor.cumsum
def patched_cumsum(self: Tensor, *args, **kwargs):
    return orig_cumsum(self.cpu() if self.device.type == 'mps' else self, *args, **kwargs).to(self.device)
torch.Tensor.cumsum = patched_cumsum

reassuring_message = "monkey-patched cumsum to fallback to CPU, for compatibility on MPS backend; see https://github.com/pytorch/pytorch/issues/89784"
```

you can invoke the patch like so:

```python
from .cumsum_mps_fix import reassuring_message
print(reassuring_message) # avoid "unused" import :P
```

**Comment by malfet** [comment]
> ```python
> torch.cumsum(torch.arange(0,6, device='mps'), 0)
> # tensor([0, 1, 2, 3, 4, 5], device='mps:0')
> 
> torch.cumsum(torch.arange(0,6), 0)
> # tensor([ 0,  1,  3,  6, 10, 15])
> ```

Thank you for the reproducer, looks like `int64` problem all over again:
```
```

**Comment by skotapati** [comment]
No longer repros on MacOS 14.6.1 + Latest torch nightly, please reopen if the issue is observed again
