### ISSUE TITLE
Strided indexing behavior

### ISSUE THREAD

**Issue by rtqichen** [pytorch/pytorch#898]
Currently it seems `x[i:j:k]` with k>1 doesn't work when:
(1) j>len(x) or
(2) (j-i)%k != 0

```
a = list(range(10))
x = torch.Tensor(a)
x[::2] # works
x[::3] # fails
x[::4] # fails
x[::5] # works

# In fact, right now there's no pytorch equivalent to
a[::4] # returns [0,4,8]
x[:8:4] # works, but only returns [0,4]
```

This likely has to do with narrow not allowing condition 1:

https://github.com/pytorch/pytorch/blob/67f94557ff26428ac911d8c08c7f9b619a41950e/torch/csrc/generic/Tensor.cpp#L477

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch/pull/905
