### ISSUE TITLE
[Caffe2]Weird error during installing caffe2 from source

### ISSUE THREAD

**Issue by quinnliu4real** [pytorch/pytorch#8980]
I wanted to install caffe2 from source in my Anaconda virtual env for [Densepose](https://github.com/facebookresearch/DensePose). However I've been stuck for 2 days because of this weird error.

## Issue description

I strictly followed the instructions on [caffe2.ai](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#custom-anaconda-install).
Cmake output seems pretty normal:

Summary
-- General:
-- CMake version : 3.5.1
-- CMake command : /usr/bin/cmake
-- Git version : v0.1.11-9124-g77484d9
-- System : Linux
-- C++ compiler : /usr/bin/c++
-- C++ compiler version : 5.4.0
-- BLAS : Eigen
-- CXX flags : -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-error=deprecated-declarations
-- Build type : Release
-- Compile definitions : 
-- CMAKE_PREFIX_PATH : ~/anaconda3/envs/caffe2
-- CMAKE_INSTALL_PREFIX : /home/fangxi/anaconda3/envs/caffe2
-- BUILD_CAFFE2 : ON
-- BUILD_ATEN : OFF
-- BUILD_BINARY : ON
-- BUILD_CUSTOM_PROTOBUF : ON
-- Link local protobuf : ON
-- BUILD_DOCS : OFF
-- BUILD_PYTHON : ON
-- Python version : 2.7.13
-- Python includes : /home/fangxi/anaconda3/envs/caffe2/include/python2.7
-- BUILD_SHARED_LIBS : ON
-- BUILD_TEST : OFF
-- USE_ASAN : OFF
-- USE_ATEN : OFF
-- USE_CUDA : ON
-- CUDA static link : OFF
-- USE_CUDNN : ON
-- CUDA version : 8.0
-- cuDNN version : 5.1.10
-- CUDA root directory : /usr/local/cuda
-- CUDA library : /usr/lib/x86_64-linux-gnu/libcuda.so
-- cudart library : /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
-- cublas library : /usr/local/cuda/lib64/libcublas.so;/usr/local/cuda/lib64/libcublas_device.a
-- cufft library : /usr/local/cuda/lib64/libcufft.so
-- curand library : /usr/local/cuda/lib64/libcurand.so
-- cuDNN library : /usr/local/cuda/lib64/libcudnn.so
-- nvrtc : /home/fangxi/anaconda3/lib/libnvrtc.so
-- CUDA include path : /usr/local/cuda/include
-- NVCC executable : /usr/local/cuda/bin/nvcc
-- CUDA host compiler  : /usr/bin/cc
-- USE_TENSORRT : OFF
-- USE_ROCM : OFF
-- USE_EIGEN_FOR_BLAS : ON
-- USE_FFMPEG : OFF
-- USE_GFLAGS : ON
-- USE_GLOG : ON
-- USE_GLOO : ON
-- USE_GLOO_IBVERBS : OFF
-- USE_LEVELDB : ON
-- LevelDB version : 1.20
-- Snappy version : ..
-- USE_LITE_PROTO : OFF
-- USE_LMDB : ON
-- LMDB version : 0.9.17
-- USE_METAL : OFF
-- USE_MKL : 
-- USE_MOBILE_OPENGL : OFF
-- USE_MPI : ON
-- USE_NCCL : ON
-- USE_SYSTEM_NCCL : OFF
-- USE_NERVANA_GPU : OFF
-- USE_NNPACK : ON
-- USE_OBSERVERS : ON
-- USE_OPENCL : OFF
-- USE_OPENCV : ON
-- OpenCV version : 3.1.0
-- USE_OPENMP : OFF
-- USE_PROF : OFF
-- USE_REDIS : OFF
-- USE_ROCKSDB : OFF
-- USE_ZMQ : OFF
-- Public Dependencies  : Threads::Threads;gflags;glog::glog
-- Private Dependencies : nnpack;cpuinfo;/usr/lib/x86_64-linux-gnu/liblmdb.so;/home/fangxi/anaconda3/envs/caffe2/lib/libleveldb.so;/home/fangxi/anaconda3/envs/caffe2/lib/libsnappy.so;/usr/lib/x86_64-linux-gnu/libnuma.so;opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_video;/usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so;gloo;gcc_s;gcc;dl
-- Configuring done
CMake Warning at caffe2/CMakeLists.txt:194 (add_library):
Cannot generate a safe runtime search path for target caffe2 because there
is a cycle in the constraint graph:

    dir 0 is [/home/fangxi/anaconda3/envs/caffe2/lib]
    dir 1 is [/usr/lib/openmpi/lib]
    dir 2 is [/usr/local/cuda/lib64]
    dir 3 must precede it due to runtime library [libnvrtc.so.8.0]
    dir 3 is [/home/fangxi/anaconda3/lib]
    dir 2 must precede it due to runtime library [libcudart.so.8.0]

Some of these libraries may not be found correctly.

CMake Warning at cmake/Modules_CUDA_fix/upstream/FindCUDA.cmake:1836 (add_library):
Cannot generate a safe runtime search path for target caffe2_gpu because
there is a cycle in the constraint graph:

    dir 0 is [/home/fangxi/pytorch/build/lib]
    dir 1 is [/usr/local/cuda/lib64]
    dir 4 must precede it due to runtime library [libnvrtc.so.8.0]
    dir 2 is [/usr/local/lib]
    dir 3 is [/usr/lib/openmpi/lib]
    dir 4 is [/home/fangxi/anaconda3/lib]
    dir 1 must precede it due to runtime library [libcurand.so.8.0]
    dir 5 is [/home/fangxi/anaconda3/envs/caffe2/lib]

Some of these libraries may not be found correctly.
Call Stack (most recent call first):
cmake/public/utils.cmake:134 (cuda_add_library)
caffe2/CMakeLists.txt:230 (torch_cuda_based_add_library)

-- Generating done
-- Build files have been written to: /home/fangxi/pytorch/build

Then, I ran `make install -j8`, building began.
Error happened at 98%, it appeared like this:

[ 96%] Linking CXX shared module python/caffe2_pybind11_state_gpu.so
Scanning dependencies of target caffe2_detectron_ops_gpu
[ 96%] Built target caffe2_pybind11_state_gpu
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/select_smooth_l1_loss_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/ps_roi_pool_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/sigmoid_cross_entropy_loss_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/group_spatial_softmax_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/softmax_focal_loss_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/smooth_l1_loss_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/upsample_nearest_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/roi_pool_f_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/batch_permutation_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/spatial_narrow_as_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/sigmoid_focal_loss_op.cc.o
[ 97%] Building CXX object modules/detectron/CMakeFiles/caffe2_detectron_ops_gpu.dir/sample_as_op.cc.o
[ 98%] Linking CXX shared library ../../lib/libcaffe2_detectron_ops_gpu.so
[ 98%] Built target caffe2_detectron_ops_gpu
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

The process just stopped out of nothing and I had no idea what caused this error.
Please help me!

## System Info

- OS: Ubantu 16.04
- Python version: 2.7
- CUDA/cuDNN version: CUDA8.0, CUDNN5.1
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.5.1
- Versions of any other relevant libraries: default by [caffe2.ai](https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#custom-anaconda-install).

**Comment by pjh5** [comment]
There are several ways to install from source. If you are using anaconda, then you should use https://caffe2.ai/docs/getting-started.html?platform=mac&configuration=compile#anaconda-install-path .

The "-j8" passed to the make command tells make to build in parallel using up to 8 threads. Whenever an error occurs on a thread, 'make' still waits for the other 7 threads to stop. So to actually find the error message you have to look further up in the output. 

You seem to be mixing an Anaconda cuda package "/home/fangxi/anaconda3/lib/libnvrtc.so" with a system installed cuda package "/usr/local/cuda/lib64/libcufft.so" . This probably won't work. If you only plan on installing Caffe2 into the conda env then I'd recommend just uninstalling all conda-related packages in this conda env. Otherwise, try passing -DCUDA_HOME=/usr/local/cuda to scripts/build_anaconda.sh 

You are also mixing system opencv with conda packages, which might cause problems due to its dependencies on other libraries. You should install opencv into your conda env or pass -DUSE_OPENCV=OFF to scripts/build_anaconda.sh

If those don't fix your errors, then post the cmake output (ctrl-f for "Summary") and the actual error that's stopping make.

**Comment by quinnliu4real** [comment]
@pjh5 

Thanks for your help, Paul. Your points do make sense, and I'm going to give a try.

I'm not familiar with the conda-system-mixing thing, but I heard a bit of it, and I believe that is the cause of my error. (Actually I thought conda env was completely independent of everything, including system, HAHA..)

Anyway, your answer does help me a lot. Thanks again.
