### ISSUE TITLE
[Feature Request] tensordot

### ISSUE THREAD

**Issue by jcmgray** [pytorch/pytorch#8988]
``tensordot`` would be a useful function to have for general contractions between tensors. It looks like all the basic functionality is already present, but not a [numpy-matching api](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tensordot.html). One nice gain if this was present would be that ``pytorch`` could be used as a backend by [``opt_einsum``](https://github.com/dgasmith/opt_einsum) for order-optimized tensor contractions.

Two simple and purely python options would be:

1. a ``dot/matmul`` based method - like [__this gist__](https://gist.github.com/deanmark/9aec75b7dc9fa71c93c4bc85c5438777) (adapted from numpy's implementation itself I think)
2. an ``einsum`` based method - like in [__this PR__](https://github.com/devinamatthews/tblis/pull/17/files) (not for pytorch but similarly translates ``tensordot`` calls to ``einsum`` calls)

**Comment by t-vi** [comment]
I'd do tensordot based on the (private) sumproduct_pair function used by einsum. In fact, if we want this, I'd be glad to send a PR.
Medium-term, I'd like to incorporate the optimizations into einsum itself. (Numpy, did, too.)
