### ISSUE TITLE
[proposal] out= doesn't resize storage

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#8989]
Example use case: I allocate a buffer, and put multiple things using `out=` into the buffer (with views). Naturally I don't want any one of them to resize storage. But currently it's hard to make sure.

cc @colesbury @ezyang

**Comment by bhushan23** [comment]
We can create memory pool and enforce using it for memory operations. This will allows us to control who can resize and who can't

**Comment by mruberry** [comment]
https://github.com/pytorch/pytorch/issues/41027 is a duplicate of this, but since that issue has more and a more recent discussion I'm closing this issue in favor of it.
