### ISSUE TITLE
OS X gcc-6 pytorch has faulty math operations

### ISSUE THREAD

**Issue by szagoruyko** [pytorch/pytorch#899]
Compiles fine, but some operations do not work as expected, and some tests eg. test_csub are failing in test_torch.py
I was debugging this sometime ago, seems that the issue is with tensors which have more than 64 elements total. Lua torch doesn't have it.

**Comment by soumith** [comment]
how do i install gcc-6 on OSX?

**Comment by apaszke** [comment]
I think it's in homebrew.

brew install gcc

**Comment by ezyang** [comment]
Fixed in #1873.
