### ISSUE TITLE
Functionalization should not compute reference output if it is not needed

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#89914]
### 🐛 Describe the bug

Generated code is

```
      auto compute_reference_meta =
        self.key_set().has_backend(c10::BackendComponent::XLABit) ||
        self.key_set().has_backend(c10::BackendComponent::LazyBit);
      at::Tensor reference_tensor_output;
      {
        at::AutoDispatchSkipFunctionalize func_guard;
        c10::impl::ExcludeDispatchKeyGuard guard(exclude_keys_for_meta_dispatch);
        auto self_meta = to_meta(self);
        reference_tensor_output = at::_ops::unsqueeze::call(self_meta, dim);
      } 
```

noticed that the meta block is always called even if `compute_reference_meta` is False.

Should be an easy starter task for someone onboarding.

### Versions

master

cc @bdhirsh @soumith

**Comment by Raman-Kumar** [comment]
let me try to fix it

**Comment by wendywang3315** [comment]
Hello @ezyang , is this issue still open? If so, I would like to work on it! Can you also expand on where this fraction of code is located?

**Comment by ezyang** [comment]
Yes. grep for compute_reference_meta to find where in codegen its defined

**Comment by vishalj0501** [comment]
Hello , I'm a first timer and willing to contributor to PyTorch,
Can I take up this issue, as It's still open, else How should I proceed?
Thank you for your time!
