### ISSUE TITLE
After using unsqueeze and expand to add a new dimension to a tensor, assign value to one "page" of the tensor (such like tensor[:, :, 0] = 1) will change every "page" of the tensor. 

### ISSUE THREAD

**Issue by VirosaLi** [pytorch/pytorch#8994]
## Issue description

After using unsqueeze and expand to add a new dimension to a tensor, assign value to one "page" of the tensor (such like tensor[:, :, 0] = 1) will change every "page" of the tensor. 

## Code example
`
import torch

expand_length = 8

tensor = torch.randn(2, 2).mul(2)
expand_tensor = torch.zeros_like(tensor).unsqueeze(-1).expand(-1, -1, expand_length)
expand_tensor[:, :, 0] = 1
print(expand_tensor)
`

output:
tensor([[[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]],
        [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]])

It should be:

tensor([[[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],
        [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
         [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: Ubuntu 18.04 LTS
- PyTorch version: 0.4.0
- Python version:3.6
- CUDA/cuDNN version: 9.1.85
- GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries: Nvidia driver version: 390.48

**Comment by SsnL** [comment]
Yes, this is expected because you are expanding the tensor. Expand just changes the stride at that dimension to 0, so each slice along that dimension is sharing the same memory location.
