### ISSUE TITLE
[libtorch] error LNK2001: unresolved external symbol "const c10::intrusive_ptr_target::`vftable'"

### ISSUE THREAD

**Issue by jalvesz** [pytorch/pytorch#89957]
### 🐛 Describe the bug

Hi, I'm trying to link libtorch with a larger project. For the moment I'm just creating a small sub-project for unit-testing before intruding elsewhere. I managed to build, compile and run the test case from https://pytorch.org/tutorials/advanced/cpp_export.html by linking against the **debug** version (compiling my debug exe against libtorch debug). When I try to do the same thing in release mode I get the following error: 

error LNK2001: unresolved external symbol "const c10::intrusive_ptr_target::`vftable'" (??_7intrusive_ptr_target@c10@@6B@)

NB: Before being able to compile and run, I had to modify the following two files:

1.  libtorch-win-shared-with-deps-1.13.0+cpu/libtorch/include/c10/util/ArrayRef.h (comment)
line 368: //C10_DEFINE_DEPRECATED_USING(IntList, ArrayRef<int64_t>)

2.  libtorch-win-shared-with-deps-1.13.0+cpu/libtorch/include/c10/util/Exception.h (add)
line 472: #define TORCH_CHECK(cond, ...) {}

Without these 2 changes nothing compiles (nor debug or release, of neither 1.13.0 or nightly versions). I would get errors on constexpr ... with them I can run succesfully in debug and can build individual files in the subproject (but not the whole project itself) in release

Errors if I don't bypass TORCH_CHECK locally as in (2):
"variable in constexpr function does not have automatic storage duration"
"...\libtorch\include\c10\util\ArrayRef.h"
lines: 175, 194 and 219

Any suggestions?
Thanks!

NB2: Googling around seems like this issue is not new https://discuss.pytorch.org/t/vector-subscript-out-of-range-and-other-errors-with-intel-c/55156 (not exactly the same but the closest I found) ... no answers given there.

### Versions

OS: Windows11
CMake: 3.22
Compiler: MVS2019 with Intel C++ 19.1
Libtorch: CPU only, Stable 1.13.0 and nightly

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions:[ https://discuss.pytorch.org/](https://discuss.pytorch.org/)
