### ISSUE TITLE
[pytorch] Warnings while compiling ATen and C2 from master

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#8996]
Plenty of :
```
cc1: warning: command line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
```
while building aten, coming from NVCC, build completes successfully though.

ubuntu 16.04, cuda 8.0, gcc 5.4.0

**Comment by bhushan23** [comment]
Issue with our makefiles, 
Passing this option for c and cpp both.
https://github.com/pytorch/pytorch/blob/1a03ba51dcc8cfa5ad863ca86217beb2850b12c0/cmake/MiscCheck.cmake

**Comment by vadimkantorov** [comment]
(still happens on master)

**Comment by bhushan23** [comment]
can you list down the command you used? I am not getting this warning but bunch of -Wno-absolute-value
I followed following- let me know if I am missing something

> 1. cd aten
> 2. mkdir build
> 3. cd build
> 4. make

**Comment by vadimkantorov** [comment]
```
# on ubuntu 16.04
cd pytorch
python3 setup.py install
```

**Comment by my462** [comment]
I also have met the same problem on ubuntu 14.04

**Comment by vadimkantorov** [comment]
Still plenty of 
```
cc1: warning: command line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
```

**Comment by Wushuyi123** [comment]
I met exactly the same problem with u, The 2 warnings are the same have U solved it right now?

**Comment by Wushuyi123** [comment]
> Still plenty of
> 
> ```
> cc1: warning: command line option ‘-fvisibility-inlines-hidden’ is valid for C++/ObjC++ but not for C
> ```
> 
> Also:
> 
> ```
> /opt/vadim/env/pytorch/caffe2/operators/distance_op.cu(370): warning: the "template" keyword used for syntactic disambiguation may only be used within a template
> ```
> 
> This is on g++ 5.4.0 on ubuntu 16.04

same problem

**Comment by xzhewei** [comment]
ubuntu16.04 cuda-8.0 same problem

**Comment by mruberry** [comment]
Closing due to age and the profusion of build warnings since then.

A comprehensive build warning issue would be interesting, but it should contain detailed sub-tasks to make it actionable.
