### ISSUE TITLE
windows-binary-conda / conda-py3_10-cuda11_6 and conda-py3_10-cuda11_7 fails on MKL smoke test

### ISSUE THREAD

**Issue by Blackhex** [pytorch/pytorch#89996]
## Current Status

Still ongoing.

## Error looks like

Started since https://hud.pytorch.org/pytorch/pytorch/commit/f44ba7d75dc53b522926f270340f4f3d4509dd37 and ongoing https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=windows-binary-conda%20%2F%20conda-py3_10-cuda11

## Incident timeline (all times pacific)

- 11/22 9:03 incident began
- still ongoing

## User impact

Nigtly binaries for Python 3.10 not being built.

## Root cause

Seems like MKL conda package for Python 3.10 got a new version that fails the smoke test even if it seems to be correctly instlaled.

## Mitigation

Not yet.

## Prevention/followups

TODO

**Comment by kit1980** [comment]
This is probably the same as https://github.com/pytorch/pytorch/issues/89935

**Comment by Blackhex** [comment]
Ah, sorry, I was searching for MKL keywork.

**Comment by malfet** [comment]
Closing as duplicate https://github.com/pytorch/pytorch/issues/89935, though I have to say, this test has not been doing anything sensible for a while now.
