### ISSUE TITLE
pointnet2_batch_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: 

### ISSUE THREAD

**Issue by atta007** [pytorch/pytorch#89995]
### 🐛 Describe the bug

Hi, I am facing an error while running the training script. I am using https://github.com/LittlePey/SFD for training and inference. 
![Screenshot from 2022-12-01 13-49-13](https://user-images.githubusercontent.com/39458797/205007827-e62b6868-9c7b-4c81-9548-ac66d08b4a78.png)
![Screenshot from 2022-12-01 13-49-33](https://user-images.githubusercontent.com/39458797/205007888-3ed150d6-c6fe-4bd7-ba50-7d4649de6b0f.png)

Please guide me on how I can overcome this problem. 

### Versions

![Screenshot from 2022-12-01 13-51-00](https://user-images.githubusercontent.com/39458797/205008293-d88f52a9-2b54-4497-9c39-918f3bd8058d.png)
I am using Cuda 11.6 
and I have installed following Cuda version: pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116

**Comment by drisspg** [comment]
Hello Atta, 
There isn't enough information to work off in this issue. 
- Do you have a self-contained script which we could use to reproduce the problem? 
- Could you run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py

I also see that you added an issue on the SFD github project. I think that this is better handle over there. I am going to close this issue for now.
