### ISSUE TITLE
torch.multinomial on CUDA tensors advances RNG based on tensor size

### ISSUE THREAD

**Issue by xylankant** [pytorch/pytorch#90006]
### 🐛 Describe the bug

When evaluating large models on different machines, my co-developers and I noticed the produced results were different despite doing all we can for reproducibility (setting seeds, setting torch.backends.cudnn.deterministic = True etc.)
The differences between machines appear only when using CUDA tensors, i.e., when keeping everything on CPU, which is very slow, all machines produce the same output.

After some bug testing, we found the culprit to be torch.multinomial , which we use to sample from an output distribution. When checking the random state before and after sampling, we notice that it advances differently between machines when using CUDA tensors, but advances the same when using CPU.

We were able to get a minimal code sample to produce the same effect:

CPU example:
```python
import torch

torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

t = torch.rand(256, 100000)
s1 = torch.get_rng_state()
_ = torch.multinomial(t, 1)
s2 = torch.get_rng_state()

sum(s2-s1)
```
This leads to the same RNG advance on different machines `tensor(128, dtype=torch.uint8)` .

CUDA example:
```python
import torch

torch.manual_seed(1234)
torch.cuda.manual_seed(1234)

t = torch.rand(256, 100000).to("cuda")
s1 = torch.cuda.get_rng_state()
_ = torch.multinomial(t, 1)
s2 = torch.cuda.get_rng_state()

sum(s2-s1)
```
This leads to different RNG advances on different machines `tensor(113, dtype=torch.uint8)` vs `tensor(160, dtype=torch.uint8)` .

We were able to determine that it has to do with GPU memory size/full tensor size, i.e., when limiting the tensor shape to anything from `[1, 50000]` to `[5, 50000]`, all machines advance the CUDA RNG by the same amount (`4`) for each call of `torch.multinomial`.
However, beyond this the first machine (with smaller GPU) advances the RNG by `8`, while the machine with bigger GPU keeps steps of `4` until a size of `[13, 50000]`.

This means that despite all test machines being able to fit the network on their GPUs and perform inference with the same batch size, and us taking steps to ensure reproducibility, we still cannot reproduce results reliably without switching to CPU ( `torch.multinomial(t.to("cpu"), 1).to("cuda")` ).

Is this a known issue? Is there a way around this behaviour that does not require falling back to slow CPU-based sampling?

### Versions

Smaller GPU:
NVIDIA GeForce RTX 2080 Ti (12GB)

Bigger GPU:
Tesla V100-SXM2-16GB

Both machines use the same Docker, output on both for `python collect_env.py`:
[pip3] numpy==1.21.5
[pip3] torch==1.12.0
[pip3] torchelastic==0.2.0
[pip3] torchtext==0.13.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.5           py37he7a7128_2
[conda] numpy-base                1.21.5           py37hf524024_2
[conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchelastic              0.2.0                    pypi_0    pypi
[conda] torchtext                 0.13.0                     py37    pytorch
[conda] torchvision               0.13.0               py37_cu113    pytorch

cc @pbelevich @ezyang

**Comment by drisspg** [comment]
The multinomial function takes an optional generator: https://pytorch.org/docs/stable/generated/torch.multinomial.html. Could you try using this to see if the specified cuda generator advances the same on different machines.

**Comment by ezyang** [comment]
The generator arg is unlikely to help, imo

**Comment by xylankant** [comment]
Using a generator has the no effect **however**, using `replacement=True` in multinomial in above minimal code seems to alleviate the problem!
This is very odd, as in another test outside of the minimal problem, `replacement=True` had not effect... I will try a few more things, but maybe this is the -- way too simple -- solution.

**Comment by ezyang** [comment]
Multinomial without replacement or n=1 goes a different codepath, where we use `exponential_` to generate the RNG

**Comment by xylankant** [comment]
ok, that makes sense. Unfortunately in our scenario, sampling with replacement is not really a good option, so we are essentially stuck to the codepath that advances the rng unevenly on GPU. CPU still isn't affected by this.

**Comment by ezyang** [comment]
Unfortunately, the RNG will be different depending on tensor size and gpu. Here is the logic:

```
// utility function that calculates proper philox_offset
// for distributions utilizing TensorIterator. For distributions using
// TensorIterator, we are using a grid-stride loop with each
// thread yielding one element per thread. For the edge of the grid-stride
// loop, if the tensor size is large, the unroll loop will kick in and the float4
// from curand4 will start getting utilized (for common tensor sizes, we end up
// using rand.x from each thread). Hence, the philox_offset is
// (number of elements per thread * number of engine calls), which makes
// sure that philox offset increment is not less than the number of randoms used
// in each thread.
std::tuple<uint64_t, dim3, dim3> calc_execution_policy(int64_t total_elements) {
  const uint64_t numel = static_cast<uint64_t>(total_elements);
  const uint32_t block_size = block_size_bound;
  const uint32_t unroll = curand4_engine_calls;
  dim3 dim_block(block_size);
  dim3 grid((numel + block_size - 1) / block_size);
  uint32_t blocks_per_sm = at::cuda::getCurrentDeviceProperties()->maxThreadsPerMultiProcessor / block_size;
  grid.x = std::min(
      static_cast<uint32_t>(at::cuda::getCurrentDeviceProperties()->multiProcessorCount) * blocks_per_sm,
      grid.x);
  //number of times random will be generated per thread, to offset philox counter in thc random state
  uint64_t counter_offset = ((numel - 1) / (block_size * grid.x * unroll) + 1)
                                * curand4_engine_calls;
  return std::make_tuple(counter_offset, grid, dim_block);
}
```

The easiest fix for you is probably for us to have some way to conservatively use more offset than you actually need.

**Comment by ezyang** [comment]
But even if you bosh the same advancement, no guarantee the sampling itself will be the same across the gpus

**Comment by xylankant** [comment]
Thank you for elaborating. Looks like this is not a "bug" as such, just a somewhat unexpected behaviour under very specific circumstances -- sampling with torch.multinomial on GPU without replacement.
We'll have to find a way to work around this for reproducibility, but now we are aware, thank you :)
