### ISSUE TITLE
An error is reported when saving with a Chinese file name

### ISSUE THREAD

**Issue by zozero** [pytorch/pytorch#90040]
### 🐛 Describe the bug
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "xxxx.py", line 44, in <module>
    训练()
  File "xxxxx.py", line 40, in 训练
    执行单个训练(0, 参数, 全局模型, 某个优化器, True)
  File "xxxxxx.py", line 33, in 执行单个训练
    torch.save(全局模型.state_dict(), 临时文件路径字符串)
  File "C:\ProgramData\Anaconda\lib\site-packages\torch\serialization.py", line 427, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "C:\ProgramData\Anaconda\lib\site-packages\torch\serialization.py", line 314, in _open_zipfile_writer
    return container(name_or_buffer)
  File "C:\ProgramData\Anaconda\lib\site-packages\torch\serialization.py", line 287, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory 已训练的模型 does not exist.
python-BaseException

进程已结束,退出代码-1073741510 (0xC000013A: interrupted by Ctrl+C)

I have created the "已训练的模型 " directory。
I also try to use various Chinese paths and will report errors。

**If you save directly without adding a directory, there will be garbled characters**

### Versions

torch version '1.14.0.dev20221110'
PyCharm Community Edition 2022.1

![image](https://user-images.githubusercontent.com/40239741/205207299-a361103b-a1de-4f87-819a-a361f1a436e7.png)

cc @mruberry

**Comment by drisspg** [comment]
Hello, I am not sure if the error you are mentioning is related to pycharm or pytorch.

Two things would be helpful in diagnosing:
- Do you have a self-contained script which we could use to reproduce the problem? Something that could be invoked with `python example.py`
- Could you run and paste the output of https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py

**Comment by zozero** [comment]
```
import os

import torch
from torch import nn


# a simple model class
class 测试模型类(nn.Module):
    def __init__(self):
        super().__init__()
        self.卷积1 = nn.Conv1d(1, 8, 2, stride=1, padding=1)

    def forward(self, x):
        return self.卷积1(x)


if __name__ == "__main__":
    # The path where the model is saved
    保存的路径 = "已训练的模型"
    if not os.path.isdir(保存的路径):
        os.makedirs(保存的路径)

    # generate a simple model
    某个测试模型 = 测试模型类()
    某个测试模型.cuda()
    某个测试模型.train()
    某个测试模型(torch.randn(10, 1, 1).cuda())

    临时文件路径字符串 = os.path.join(保存的路径, "一个简单的模型_1")
    # show error code
    torch.save(某个测试模型.state_dict(), 临时文件路径字符串)

```

**Comment by zozero** [comment]
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.24.0-rc5
Libc version: N/A

Python version: 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22623-SP0
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 526.98
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.5.0
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           haa95532_640  
[conda] mkl-service               2.4.0            py39h2bbff1b_0  
[conda] mkl_fft                   1.3.1            py39h277e83a_0  
[conda] mkl_random                1.2.2            py39hf11a4ad_0  
[conda] numpy                     1.21.5           py39h7a0a035_3  
[conda] numpy-base                1.21.5           py39hca35cd5_3  
[conda] numpydoc                  1.5.0            py39haa95532_0  
[conda] pytorch                   1.13.0          py3.9_cuda11.7_cudnn8_0    pytorch
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                0.13.0                   pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi

进程已结束,退出代码0

**Comment by zozero** [comment]
I found the reason, it is a problem of win11 system。[https://blog.csdn.net/wry15082983136/article/details/126229608](url)，Method 2 here describes how to solve the problem。

**Comment by zozero** [comment]
![image](https://user-images.githubusercontent.com/40239741/205468262-843c48b2-6e20-4cd7-b758-da70fe2656ec.png)
