### ISSUE TITLE
[ReduceOP] Type bug since Torch 1.13 

### ISSUE THREAD

**Issue by chongxiaoc** [pytorch/pytorch#90072]
### 🐛 Describe the bug

Since Torch 1.13, `ReduceOP` type seems changed and the below scripts would throw out an error:

```python
        >>> from torch.distributed import ReduceOp
        >>> op = None
        >>> op in (ReduceOp.SUM, None)
        Traceback (most recent call last):
            File "<stdin>", line 1, in <module>
            TypeError: __eq__(): incompatible function arguments. The following argument types are supported:
            1. (self: torch._C._distributed_c10d.ReduceOp, arg0: c10d::ReduceOp::RedOpType) -> bool
            2. (self: torch._C._distributed_c10d.ReduceOp, arg0: torch._C._distributed_c10d.ReduceOp) -> bool
        Invoked with: <torch.distributed.distributed_c10d.ReduceOp object at 0x7fba78c9e0b0>, None
```

This impacts Horovod and Lightning end-to-end run, see Lightning side issue https://github.com/Lightning-AI/lightning/issues/15802

### Versions

1.13

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by pritamdamania87** [comment]
@crcrpar @kwen2501 This seems to be related to https://github.com/pytorch/pytorch/pull/88275
