### ISSUE TITLE
pytorch 2 on CPU 

### ISSUE THREAD

**Issue by Ascrypto** [pytorch/pytorch#90137]
### 🐛 Describe the bug

The command below installed torch 1.13.0. Is that what to expect, since it seems torch.compile() is part of v1.14?
```
pip3 install numpy --pre torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```
Are there other methods (other than torch.jit.script) I can use to speed up training since the above is not working (AttributeError: module 'torch' has no attribute 'compile')? 

Thank you.  

### Versions

-

cc @ezyang @seemethere @malfet

**Comment by Ascrypto** [comment]
Thank you. 
Collect_env: 
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.1 (x86_64)
GCC version: Could not collect
Clang version: 3.4 (tags/RELEASE_34/final)
CMake version: version 3.18.0
Libc version: N/A

Python version: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)] (64-bit runtime)
Python platform: Darwin-21.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] numpydoc==0.8.0
[pip3] torch==1.13.0
[pip3] torch-ac==1.1.0
[pip3] torchaudio==0.10.2
[pip3] torchmetrics==0.11.0
[pip3] torchrec-nightly-cpu==2022.5.12
[pip3] torchvision==0.11.3
[pip3] torchx-nightly==2022.11.30
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37hfbe908c_5  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpydoc                  0.8.0                    py37_0  
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torch-ac                  1.1.0                     dev_0    <develop>
[conda] torchaudio                0.10.2                   pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchrec-nightly-cpu      2022.5.12                pypi_0    pypi
[conda] torchvision               0.11.3                   pypi_0    pypi
[conda] torchx-nightly            2022.11.30               pypi_0    pypi


Installation log
pip install numpy --pre torch torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cpu

WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cpu
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-1.14.0.dev20221204-cp37-none-macosx_10_9_x86_64.whl (138.0 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/nightly/cpu/torchvision-0.15.0.dev20221203-cp37-cp37m-macosx_10_9_x86_64.whl (1.6 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/nightly/torchaudio-0.14.0.dev20221203-cp37-cp37m-macosx_10_9_x86_64.whl (3.3 MB)
Collecting sympy
  Using cached sympy-1.10.1-py3-none-any.whl (6.4 MB)
Collecting networkx
  Using cached networkx-2.6.3-py3-none-any.whl (1.9 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.3.0-cp37-cp37m-macosx_10_10_x86_64.whl (3.3 MB)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-1.14.0.dev20221203-cp37-none-macosx_10_9_x86_64.whl (138.0 MB)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.2.1-py3-none-any.whl (532 kB)
WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, idna, charset-normalizer, certifi, torch, requests, torchvision, torchaudio
  Attempting uninstall: mpmath
    WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
    Found existing installation: mpmath 1.1.0
ERROR: Cannot uninstall 'mpmath'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -iohttp (/Users/ascpt/anaconda3/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -inja2 (/Users/ascpt/anaconda3/lib/python3.7/site-packages)

**Comment by ezyang** [comment]
well the install log says that you installed the torch nightly. What if you `pip uninstall torch` twice (or as many times until it says its not there anymore) and then try installing again?

**Comment by Ascrypto** [comment]
This worked, thank you.
