### ISSUE TITLE
loss.backwards() cannot handle addition?

### ISSUE THREAD

**Issue by KyroChi** [pytorch/pytorch#90158]
### 🐛 Describe the bug

I don't know a better way to describe this so please feel free to change the title. 

Basically if I use a tensor like
```
t = 1 + 3 * torch.rand(20, 1, requires_grad=True)
t.requires_grad_()
```
it breaks things.

The following minimal example will not run:

```python
import torch
from torch import nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        self.stack = nn.Sequential(
            nn.Linear(2, 10),
            nn.Linear(10, 10),
            nn.Linear(10, 1)
        )

    def forward(self, x, t):
        X = torch.cat([t, x], axis=1)
        for layer in self.stack:
            X = layer(X)
        return X 

net = Net()
x = torch.FloatTensor(20, 1).uniform_(-1, 1)
x.requires_grad_()
t = 1 + 3 * torch.rand(20, 1, requires_grad=True)
t.requires_grad_()

opt = torch.optim.Adam(net.parameters(), lr=0.01)

loss = torch.mean(torch.square(net(x, t)))
opt.zero_grad()
loss.backward()
opt.step()

loss = torch.mean(torch.square(net(x, t)))
opt.zero_grad()
loss.backward()
opt.step()
```

We get:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-45-1a45cbe5d83b>](https://localhost:8080/#) in <module>
     33 loss = torch.mean(torch.square(net(x, t)))
     34 opt.zero_grad()
---> 35 loss.backward()
     36 opt.step()

1 frames
[/usr/local/lib/python3.8/dist-packages/torch/_tensor.py](https://localhost:8080/#) in backward(self, gradient, retain_graph, create_graph, inputs)
    394                 create_graph=create_graph,
    395                 inputs=inputs)
--> 396         torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
    397 
    398     def register_hook(self, hook):

[/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py](https://localhost:8080/#) in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    171     # some Python versions print out the first line of a multi-line function
    172     # calls in the traceback and some print out the last line
--> 173     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    174         tensors, grad_tensors_, retain_graph, create_graph, inputs,
    175         allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

If we change the line 
```
t = 1 + 3 * torch.rand(20, 1, requires_grad=True)
```
to
```
t = torch.rand(20, 1, requires_grad=True)
```

Then things work fine.

I am running on Google Collab.

### Versions

--2022-12-05 06:41:15--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17278 (17K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  16.87K  --.-KB/s    in 0.001s  

2022-12-05 06:41:15 (18.4 MB/s) - ‘collect_env.py’ saved [17278/17278]

Collecting environment information...
PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.27

Python version: 3.8.15 (default, Oct 12 2022, 19:14:39)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

**Comment by qqaatw** [comment]
As the message says, the intermediate values of a computational graph are freed up after you call the `loss.backward`.

Thus, if you call `loss.backward` two times consecutively, the error will be raised, for example:

```python
loss = torch.mean(torch.square(net(x, t)))
loss.backward()
loss.backward()  # error
```

However, since you call `loss = torch.mean(torch.square(net(x, t)))` before the second `loss.backward`, the `Net` is rerun, and graph is constructed again, but note that, this computation `1 + 3 * torch.rand(...` is not rerun. As a result, due to lack of intermediate values in `t` (as they're freed up in the previous backward), the error will then occur.

Then, why changing to `t = torch.rand(20, 1, requires_grad=True)` works? In this circumstance, `t` is a leaf tensor that doesn't require a grad function, so there is no intermediate values that need to be constructed. Therefore, no error will be raised.

**Comment by KyroChi** [comment]
Is this desired behavior? It seems like I should be able to treat `1 + 3 * torch.rand(...)` the same as `torch.rand(...)`? My workaround for my actual use case was to wrap everything in `torch.Tensor` which seems unnecessary. Is there an easy way to cast the `1 + ...` to a leaf tensor?

Sorry if I am being too picky.

**Comment by qqaatw** [comment]
Yes I think this is the desired behavior. If you just want to rerun the entire graph again including the computations in `t`, instead of calculating second order derivative, for example, then you can wrap the entire graph into an `nn.Module`, like so:

```python
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = Net()

    def forward(self, x, x2):
        t = 1 + 3 * x2
        return torch.mean(torch.square(self.net(x, t)))

x = torch.FloatTensor(20, 1).uniform_(-1, 1)
x.requires_grad_()
x2 = torch.rand(20, 1, requires_grad=True)

loss = Model()(x, x2)
loss.backward()

loss = Model()(x, x2)
loss.backward()
```

**Comment by KyroChi** [comment]
You're making me realize that my use case is an edge case. I am training on the same set of points over and over which, despite being the standard in my field for the type of network I am training (PINN), is probably not a best practice.

Thank you for your time.
