### ISSUE TITLE
Problem with ResNet18

### ISSUE THREAD

**Issue by FelixNgFender** [pytorch/pytorch#90155]
### 🐛 Describe the bug

I'm writing a function to process image with ResNet18 and a local saved snapshot. I encountered this error while trying to run the program.

'''python
def process_image(name, content):
    # Read image
    image = base64.b64decode(content[content.find(',') + 1:])
    image = Image.open(io.BytesIO(image))
    # Transform image
    transformation = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    image_tensor = transformation(image).float()
    image_tensor = image_tensor.unsqueeze_(0)
    # Load model
    model = models.resnet18(weights='ResNet18_Weights.IMAGENET1K_V1')
    snapshot_path = './model/checkpoint_02000.pth'
    # Load the snapshot
    checkpoint = torch.load(snapshot_path, map_location=torch.device('cpu'))
    # Load the weights into the model
    model.load_state_dict(checkpoint['state_dict'])
    # Make prediction
    output = model(image_tensor)
    _, pred = torch.max(output, 1)
    return name, pred
'''

'''
Traceback (most recent call last):
  File "C:\Users\ngthi\Desktop\computer-vision-webapp\pages\scribe-rating.py", line 71, in update_output
    children = [
  File "C:\Users\ngthi\Desktop\computer-vision-webapp\pages\scribe-rating.py", line 72, in <listcomp>
    process_image(name, content)
  File "C:\Users\ngthi\Desktop\computer-vision-webapp\pages\scribe-rating.py", line 56, in process_image
    checkpoint = torch.load(snapshot_path, map_location=torch.device('cpu'))
  File "C:\Users\ngthi\Desktop\computer-vision-webapp\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\ngthi\Desktop\computer-vision-webapp\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\ngthi\Desktop\computer-vision-webapp\venv\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_image_classification'
'''

### Versions

PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
Nvidia driver version: 512.36
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchvision==0.14.0
[conda] Could not collect

**Comment by Boaz-Yin** [comment]
Hi,

For the error,

ModuleNotFoundError: No module named 'pytorch_image_classification'

Here is the solution: 

You should list this folder/script, 'pytorch_image_classification', in the same folder with main file.
