### ISSUE TITLE
Does PyTorch 2.0 eliminate the need for custom fused operators?

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#90167]
Hello,

First of all I would like to congratulate and thank you for your great and **incredible** work on PyTorch 2.0!

Please excuse me if I'm posting in the wrong place. I was posting on the discussion forum but then switched to here thinking that the core developers of the new features might not be active there.

I was integrating to my codebase [some fused layers](https://github.com/HazyResearch/flash-attention/tree/main/training) including (in addition to FlashAttention): 

- Fused matmul+bias
- Optimized cross-entropy (xentropy)
- Fused rotary embedding 
- Fused dropout+residual+LayerNorm
 
and was wondering whether these would become unnecessary when using PyTorch 2.0 (in the sense that, without them, `torch.compile` could already match the expected performance, and adding them would not bring extra complementary speedup).

Thank you very much in advance for your response!

cc @ezyang @soumith

**Comment by gchanan** [comment]
CC @cpuhrsch @mikekgfb

**Comment by cpuhrsch** [comment]
@netw0rkf10w - *Ideally* yes. We'd want to generate code that can produce fusions for the sequences of ops you are mentioning and `torch.compile` would emit those. However, I can't know that they will match the performance of these handwritten kernels or whether they'll be available by next release without us doing some further investigation first. Have you tried factoring out the operations you want to fuse and applying `torch.compile` to see whether it provides any performance improvement?

**Comment by ezyang** [comment]
Right now, PT2 can fuse pointwise and reductions. For example, we can fuse layer norm, bias addition. A quick glance at rotary embedding suggests we may find some opportunities there. We can't fuse matrix multiplies yet, but epilogue fusion here is one of our next big ticket items.

In any case, torch.compile is pretty easy to try, so you can see if it worked well or not, and go from there.

**Comment by netw0rkf10w** [comment]
Thanks, @ezyang. That sounds very exciting! 

By the way, I've tried PT2 but obtained `AttributeError: module 'torch' has no attribute '_dynamo'`  when setting `torch._dynamo.config.verbose=True`. 

I followed the official instructions to install PT2:

```bash
pip3 install numpy --pre torch[dynamo] torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117
```

Installation went well (except for some errors that seem to be irrelevant for now):


> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> numpydoc 1.2.1 requires Jinja2<3.1,>=2.10, but you have jinja2 3.1.2 which is incompatible.
> numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.24.0rc2 which is incompatible.
> Successfully installed MarkupSafe-2.1.1 certifi-2022.9.24 charset-normalizer-2.1.1 cmake-3.25.0 filelock-3.8.2 idna-3.4 jinja2-3.1.2 mpmath-1.2.1 networkx-3.0rc1 numpy-1.24.0rc2 pillow-9.3.0 requests-2.28.1 sympy-1.11.1 torch-1.14.0.dev20221206+cu117 torchaudio-0.14.0.dev20221206+cu117 torchtriton-2.0.0+0d7e753227 torchvision-0.15.0.dev20221206+cu117 typing-extensions-4.4.0 urllib3-1.26.13

Any ideas please? 

Thank you so much!

**Comment by ezyang** [comment]
hmm, sounds like you somehow have another copy of torch installed somewhere. What happens if you `pip uninstall torch` twice (!) and then reinstall torch?

**Comment by netw0rkf10w** [comment]
@ezyang Thanks, but unfortunately the problem remains :(

```bash
(python-3.10.4) bash-4.4$ pip uninstall torch
Found existing installation: torch 1.14.0.dev20221206+cu117
Uninstalling torch-1.14.0.dev20221206+cu117:
  Would remove:
    /home/user/.local/bin/convert-caffe2-to-onnx
    /home/user/.local/bin/convert-onnx-to-caffe2
    /home/user/.local/bin/torchrun
    /home/user/.local/lib/python3.10/site-packages/functorch/*
    /home/user/.local/lib/python3.10/site-packages/torch-1.14.0.dev20221206+cu117.dist-info/*
    /home/user/.local/lib/python3.10/site-packages/torch/*
    /home/user/.local/lib/python3.10/site-packages/torchgen/*
Proceed (Y/n)? y
  Successfully uninstalled torch-1.14.0.dev20221206+cu117
(python-3.10.4) bash-4.4$ pip uninstall torch
WARNING: Skipping torch as it is not installed.
(python-3.10.4) bash-4.4$ pip uninstall torch
WARNING: Skipping torch as it is not installed.
(python-3.10.4) bash-4.4$ pip3 install --pre torch[dynamo]  --extra-index-url https://download.pytorch.org/whl/nightly/cu117
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/nightly/cu117
Collecting torch[dynamo]
  Using cached https://download.pytorch.org/whl/nightly/cu117/torch-1.14.0.dev20221206%2Bcu117-cp310-cp310-linux_x86_64.whl (1814.9 MB)
Requirement already satisfied: typing-extensions in /home/user/.local/lib/python3.10/site-packages (from torch[dynamo]) (4.4.0)
Requirement already satisfied: networkx in /home/user/.local/lib/python3.10/site-packages (from torch[dynamo]) (3.0rc1)
Requirement already satisfied: sympy in /home/user/.local/lib/python3.10/site-packages (from torch[dynamo]) (1.11.1)
Requirement already satisfied: torchtriton==2.0.0+0d7e753227 in /home/user/.local/lib/python3.10/site-packages (from torch[dynamo]) (2.0.0+0d7e753227)
Requirement already satisfied: jinja2 in /home/user/.local/lib/python3.10/site-packages (from torch[dynamo]) (3.1.2)
Requirement already satisfied: filelock in /home/user/.local/lib/python3.10/site-packages (from torchtriton==2.0.0+0d7e753227->torch[dynamo]) (3.8.2)
Requirement already satisfied: cmake in /home/user/.local/lib/python3.10/site-packages (from torchtriton==2.0.0+0d7e753227->torch[dynamo]) (3.25.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/user/.local/lib/python3.10/site-packages (from jinja2->torch[dynamo]) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /home/user/.local/lib/python3.10/site-packages (from sympy->torch[dynamo]) (1.2.1)
Installing collected packages: torch
Successfully installed torch-1.14.0.dev20221206+cu117
```

**Comment by netw0rkf10w** [comment]
I've checked the version and it is the correct one:
```
>>> torch.__version__
'1.14.0.dev20221206+cu117'
```

**Comment by netw0rkf10w** [comment]
And it has `compile` as well:
```python
>>> import torch
>>> torch.compile
<function compile at 0x1470c2a98700>
```

**Comment by netw0rkf10w** [comment]
@ezyang That works lol. Good catch! Thanks a lot!

**Comment by ezyang** [comment]
lol, can you file a bug about this haha

**Comment by ezyang** [comment]
looks the same as https://github.com/pytorch/torchdynamo/issues/1593

**Comment by ezyang** [comment]
@jansel tells me he has a mega refactor of this code which deletes the erroring line in Q, not sure how far it is from landing

**Comment by jansel** [comment]
#90482 should land soon (need to deal with some rebasing issues preventing exporting the latest version)

For now you should be able to run without max_autotune mode which enables the old Triton matmuls that PR replaces.

**Comment by netw0rkf10w** [comment]
@jansel That is great. Thank you!

**Comment by mikekgfb** [comment]
@netw0rkf10w can we close this issue?
