### ISSUE TITLE
Optimizer operations as a graph

### ISSUE THREAD

**Issue by thisIsBaggio** [pytorch/pytorch#90165]
### 🚀 The feature, motivation and pitch

Hello everyone, I hope you're having a glorious day. I'm coming with a question/proposition/bug, I'm not sure which category this should be in, so I'm putting it as feature request.

I just checked latest PT 2.0 code version and tried to use some kind of simple LeNet topology with new torch.compile function.

![image](https://user-images.githubusercontent.com/101342783/205603032-63d82b3e-a3ed-4197-a84c-261fd7751944.png)

(I'm running this on CPU BTW)

I decided to do tracing of above code to see how well it creates the graphs from this function. Results looks like this:
![image](https://user-images.githubusercontent.com/101342783/205604061-4a2a17d9-9351-4b9f-ba0f-87a3cfb726d7.png)

As you can see, FWD and BWD became graph optimized by Inductor backend. This is what we would like to achieve usually on high-end accelerator, right? But, on high-end accelerator we wouldn't like to have basically any operations outside of the graphs, and as you can see there, in the beginning there is grad zeroing which doesn't seem to be a part of any graph (is ran eagerly), same for grad accumulation and what is the worst here - optimizer itself.

There are topologies with quite heavy optimizers and this would cause accelerator to be very poorly utilized here, hence my questions:

1. Are you planning to support compilation of optimizer part? I'd like to be able to compile it in the backend (e.g. Inductor) same way is done with FWD/BWD. Could be as third graph, for example.
2. Generalizing on above - are you planning to support whole-function graph optimization? Ideally, I'd like to see WHOLE function as a single merged graph at some point in the backend to get maximum optimization opportunities (with some exceptions, but this is what partitioners are for, right? Sometimes it would be best to work on FWD, BWD, OPT graphs, and sometimes on FWD+BWD, OPT graphs, and so on...). I'm not saying it should be default behaviour - I'd just like to see it being an option.

If any of those can be done already now and it's just me not knowing how to use compilation properly, please tell me!

Cheers,
--mb

cc @vincentqb @jbschlosser @albanD @janeyx99 @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
Yes, supporting compiling through optimizers is one of our top priorities for what to enable next on the compiler.

**Comment by ezyang** [comment]
cc @mlazos

**Comment by thisIsBaggio** [comment]
Great, thanks for reply! Looking forward for this.

**Comment by gchanan** [comment]
CC @albanD

**Comment by mlazos** [comment]
This should be enabled once #90709 completes

**Comment by mlazos** [comment]
This is blocked by https://github.com/pytorch/torchdynamo/issues/1985 currently, looking into that before I complete  #90709

**Comment by thisIsBaggio** [comment]
@mlazos I checked latest PT and optimizer.step seems to be fine. Although zero_grad is still not traced:
![image](https://user-images.githubusercontent.com/101342783/209148374-d77e730c-accf-41f5-a745-925036833772.png)

Is this expected behaviour?

**Comment by mlazos** [comment]
Yes, we don't expect to get speedups from compiling zero_grad.
