### ISSUE TITLE
Trying pytorch 2.0 snippet from the website - sm89 error

### ISSUE THREAD

**Issue by vince62s** [pytorch/pytorch#90170]
### 🐛 Describe the bug

trying the snippet from the website
```
import torch
import torchvision.models as models

model = models.resnet18().cuda()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
compiled_model = torch.compile(model)

x = torch.randn(16, 3, 224, 224).cuda()
optimizer.zero_grad()
out = compiled_model(x)
out.sum().backward()
optimizer.step()
```

I got Value 'sm_89' is not defined for option 'gpu-name'
I am indeed using a rtx4090 and cuda 11.6
BUT works fine without torch.compile

### Versions

Collecting environment information...
PyTorch version: 1.14.0.dev20221205+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.10 (default, Jun 22 2022, 20:18:18)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 525.60.11
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.7.7
[pip3] torch==1.14.0.dev20221205+cu116
[pip3] torch-tb-profiler==0.4.0
[pip3] torchaudio==0.14.0.dev20221204+cu116
[pip3] torchtext==0.14.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221204+cpu
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] faiss-gpu                 1.7.2           py3.8_h28a55e0_0_cuda11.3    pytorch
[conda] libfaiss                  1.7.2           hfc2d529_0_cuda11.3    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.4           py38h14f4228_0  
[conda] numpy-base                1.23.4           py38h31eccc5_0  
[conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.14.0.dev20221204+cu117          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221204+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221204+cpu          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by Aidyn-A** [comment]
By default `compile` uses `inductor` as backend. Currently, inductor supports Volta and Ampere devices only. Your RTX 4090 is based Ada Lovelace architecture, which is not supported by the torch inductor. 
There are other backends available in `torch.compile`. 

For example:
```
compiled_model = torch.compile(model, fullgraph=True, backend='nvprims_aten')
```
worked on my 3080.

You may get a list of available backends like so:
```
import torch._dynamo as dynamo
print(dynamo.list_backends())
```

**Comment by malfet** [comment]
The issue likely in Triton, that needs to limit the compilation to latest architecture supported by toolkit rather than GPU sm arch. Updating cudatoolkit might solve the problem as well (as 11.6 to the best of my knowledge does not support Lovelace)

**Comment by vince62s** [comment]
But if I install cuda 11.8 will I be able to install pytorch from wheels ? I think it offers only 11.6 and 11.7 at the moment.

**Comment by vince62s** [comment]
Using backend='nvprims_aten' worked.

**Comment by ngimel** [comment]
Yeah if you install cuda 11.8 you can still use pytorch compiled with any other cuda version, you just need 11.8 ptxas, not even necessarily in your PATH, just discoverable by `TRITON_PTXAS_PATH`

**Comment by vince62s** [comment]
no luck. 
Installed cuda 11.8
tried to set `TRITON_PTXAS_PATH` to `/usr/local/cuda-11.8` or `/usr/local/cuda-11.8/bin` (where ptxas is) and I am now getting this message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/vincent/.local/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 488, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/home/vincent/.local/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 59, in precompile
    self.launchers = [
  File "/home/vincent/.local/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 60, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/home/vincent/.local/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 74, in _precompile_config
    triton.compile(
  File "/home/vincent/.local/lib/python3.8/site-packages/triton/compiler.py", line 1256, in compile
    asm, shared, kernel_name = _compile(fn, signature, device, constants, configs[0], num_warps, num_stages,
  File "/home/vincent/.local/lib/python3.8/site-packages/triton/compiler.py", line 901, in _compile
    name, asm, shared_mem = _triton.code_gen.compile_ttir(backend, module, device, num_warps, num_stages, extern_libs, cc)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/fileZVMk93, line 6; error   : PTX .version 7.4 does not support .target sm_89
ptxas fatal   : Ptx assembly aborted due to errors
```
plus subsequent more related errors but always due to .target sm_89

**Comment by ngimel** [comment]
We are working on it.

**Comment by ConnorBaker** [comment]
I took a stab at it with https://github.com/openai/triton/pull/1038.

I've got a Docker image I'm building using pytorch with triton's new MLIR backend on my 4090 and it seems to be working reasonably well.

If anyone is blocked by the lack of support for newer architectures, let me know and I can post it somewhere.

**Comment by buptorange** [comment]
Hi @ConnorBaker! Thank you for the work on newer architectures!
Could you please post it for us to try the new features🤩?

**Comment by ConnorBaker** [comment]
> Hi @ConnorBaker! Thank you for the work on newer architectures!
> Could you please post it for us to try the new features🤩?

Here you go: https://gist.github.com/ConnorBaker/10988159828943187d75737566c7e342

I'm working on a version which uses some of the optimizations Polly provides but I don't know if they'll make an impact/I'll be able to get it working.

**Comment by vince62s** [comment]
closing since https://github.com/openai/triton/pull/1039 is merged.

**Comment by ConnorBaker** [comment]
@vince62s the code example in your original post won't work unless the user installs Triton from master or cherry-picks that commit into their own build, or PyTorch updates the version of Triton they're using to do the same. The version of Triton PyTorch uses is pinned here: https://github.com/pytorch/pytorch/blob/master/.github/ci_commit_pins/triton.txt

I understand that they're holding off on updating to newer Triton releases until the Triton team has ironed out more of the performance regressions caused by the MLIR rewrite.

**Comment by vince62s** [comment]
Right, good to clarify.
I had just quick hacked the llvm.cc file so indeed used and built the master.
I am stuck by dynamic shapes anyway, so have to wait longer ... :)
