### ISSUE TITLE
Different memory in torch2onnx from differ version.

### ISSUE THREAD

**Issue by www516717402** [pytorch/pytorch#90175]
### 🐛 Describe the bug

When use torch.export in same code (same model) with different torch version.
Get 204KB by torch-1.13.0-cu116 on linux platform
Get 188KB by torch-1.12.1 on windows platform

### Versions

Get 204KB by torch-1.13.0-cu116 on linux platform
Get 188KB by torch-1.12.1 on windows platform

**Comment by BowenBao** [comment]
Hello @www516717402, small model size difference between different pytorch version is expected. There could be many factors involved: changes in exported meta data, onnx opset version, pytorch aten signatures etc. 

Closing. But feel free to re-open if you think there is something wrong with the exported onnx model structure, whether it's not passing onnx checker or not producing correct results in onnx runtimes.
