### ISSUE TITLE
Confidential and proprietary notices on several files

### ISSUE THREAD

**Issue by vchhasatia** [pytorch/pytorch#90187]
### 📚 The doc issue

Hello pytorch team,

I saw confidential and proprietary notices ((c) Facebook, Inc. and its affiliates. Confidential and proprietary.) in following files:
pytorch/android/pytorch_android/src/androidTest/cpp/pytorch_jni_common_test.cpp
pytorch/aten/src/ATen/native/metal/mpscnn/tests/MetalOpTestRunner.h
pytorch/aten/src/ATen/native/metal/mpscnn/tests/MetalOpTestRunner.mm
pytorch/caffe2/utils/knob_patcher.cc
pytorch/caffe2/utils/knobs.cc
pytorch/torch/csrc/distributed/c10d/ParamCommsUtils.cpp
pytorch/torch/csrc/distributed/c10d/quantization/quantization.h
pytorch/torch/csrc/distributed/c10d/quantization/quantization_gpu.h
pytorch/torch/csrc/distributed/c10d/quantization/quantization_utils.h
pytorch/torch/csrc/jit/backends/coreml/cpp/preprocess.cpp
pytorch/torch/csrc/jit/backends/xnnpack/xnnpack_graph_builder.cpp
pytorch/torch/csrc/jit/backends/xnnpack/xnnpack_graph_builder.h
pytorch/torch/csrc/jit/backends/xnnpack/compiler/xnn_compiler.cpp
pytorch/torch/csrc/jit/backends/xnnpack/compiler/xnn_compiler.h
pytorch/torch/csrc/jit/backends/xnnpack/executor/xnn_executor.h
pytorch/torch/csrc/jit/backends/xnnpack/serialization/serializer.cpp
pytorch/torch/csrc/jit/backends/xnnpack/serialization/serializer.h

### Suggest a potential alternative/fix

I am confused by seeing confidential and proprietary notices on GitHub. Would it be possible to either removing these notices?

Thank you for reviewing my issue.

**Comment by jbschlosser** [comment]
Marking as triage review for visibility.
