### ISSUE TITLE
Help needed in torch.diag()

### ISSUE THREAD

**Issue by mirraaj** [pytorch/pytorch#9022]
```
class ContinousActorCritic(nn.Module):
  def __init__(self, observation_space, action_space, hidden_size, sigma=0.3):
    super(ContinousActorCritic, self).__init__()
    self.sigma = torch.tensor([sigma])
    self.state_size = observation_space.shape[0]
    # Action Space for COntinous Space
    self.action_size = action_space.shape[0]

    self.relu = nn.ReLU(inplace=True)
    
    self.fc1 = nn.Linear(self.state_size, hidden_size)
    self.fc2 = nn.Linear(hidden_size, hidden_size)

    self.fc_actor = nn.Linear(hidden_size, self.action_size)
    self.var_layer = nn.Linear(hidden_size, self.action_size)
    self.var = nn.Softplus() # To get the softplus results
    self.fc_critic_value = nn.Linear(hidden_size, 1)

    self.action_input_layer = nn.Linear(self.action_size, hidden_size)
    self.fc_critic_advantage = nn.Linear(hidden_size, 1)

  def forward(self, x0):
    Q = None
    state = x0
    x1 = self.relu(self.fc1(x0))
    h = self.fc2(x1)  # h is (hidden state, cell state)
    x = h # TODO : Remove this line from code
    policy = self.fc_actor(x)  # Prevent 1s and hence NaNs

    var_layer = self.var_layer(x)
    var = self.var(var_layer)
    print (var, policy)
    sleep(10)

    # action = policy.data + torch.normal(torch.zeros(policy.size()), torch.ones(policy.size())*0.01)
    m = MultivariateNormal(policy, torch.diagnol(var))
    action = m.sample()
    print (action)
    sleep(100)
    action_samples = [Variable(m.sample()) for _ in range(5)]
    advantage_samples = torch.cat([self.Advantage(x, action_sample).unsqueeze(-1) for action_sample in action_samples], -1)
    print (advantage_samples)
    sleep(100)
    A = self.Advantage(x, action)
    Q = V + A - advantage_samples.mean(-1)
    return policy, Q, V, action#, var.log()
```

I am using the following code as a neural network for my reinforcement learning codes. I need to sample actions from a Gaussian distribution. My objective is to get the variance from the neural network and diagonalize it for sampling. Please let me know how should I proceed. It seems that torch.diag doesn't support batches of input.

**Comment by zou3519** [comment]
I think you are looking for [torch.diagflat](https://pytorch.org/docs/master/torch.html?highlight=diag#torch.diagflat).

This issue isn't a bug report or feature request, so I am closing this. Please feel free to reopen if it is any of those.

**Comment by mirraaj** [comment]
@zou3519, I think you do not get my doubt. What I want to do is get the diagnol matrix of the given tensor in this form:

a = tensor([[ 1.,  2.],
                  [ 3.,  4.],
                  [ 5.,  6.]])
  
torch.fuction(a) should now return three 2D arrays with following tensors as their diagnol values. 

My main focus is to sample values from multivariate Gaussian using mean and variance matrix. This seems to be working when I am using a batch size of 1, however, I am getting errors for a batch size greater than 1. Please let me know how to proceed.

**Comment by soumith** [comment]
@mirraaj 

> torch.fuction(a) should now return three 2D arrays with following tensors as their diagnol values.

What are the Tensors in the example, you forgot to put them in your comment

**Comment by mirraaj** [comment]
@soumith , Apologies for not being clear.

What I want is to sample values from a multivariate Gaussian distribution during runtime. It seems to be a bit undoable because the following line returns error whenever the batch size is greater than 1. It will be ver helpful if you could help me out with this. Please look at the code snippet I posted in my first comment. You will find that I have used this following code snippet under the `forward()` implementation.

 ```
m = MultivariateNormal(policy, torch.diagnol(var))
action = m.sample()
 ```

**Comment by soumith** [comment]
but what do you expect to be the input and output of torch.diagonal? and what is the shape of `var`?

**Comment by mirraaj** [comment]
Let me be a bit more clear. Suppose I need to sample a value of shape (n,1) from a multivariate Gaussian distribution, I need to sample such value from the mean and covariance matrix. I am now assuming that the covariance matrix is a diagonal matrix. The values of the diagonal are the output from a neural network. Now, this seems to be working good when I keep the batch size to be 1. When I want a batch size greater than one (take m), I want to sample m of such values from m different Gaussian distribution having different mean and variance. Implementing this has become a challenge for me. I am not getting any issue which has tackled this before.
