### ISSUE TITLE
KPI: Add issues velocity graph

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#90278]
We already estimate tickets for a while and it's time to start leveraging the data for future planning.
For that we need know team's velocity per given time period.

**Expectations**
- Graph will show how many points we manage to process during given time period (proposal is 1 week, check with team).
- Discuss with team how we want to collect points

**Proposals for points collection**

**Option 1**
As we are having t-shirt sizes one option is to sum sum t-shirt sizes with formula:
- S = 1 point
- M = 3 points
- L = 5 points
- XL = 8 points
- Not defined = 100 points

Benefits:
- It would work retroactively
- It would help with preventing creating of mindset where people map numbers with amount of time (days).

Disbenefits:
- Graphs will require translation (for example velocity of 100 points would mean we can take 20 L tickets).

**Option 2**
- Migrate from T-Shirt sizes to points in issues itself
- Sum the points.

Benefits:
- It's more straightforward for usage

Disbenefits:
- Require additional work for legacy issues if we want to keep historical data.
- It's easier to slip to time based estimates.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by iremyux** [comment]
Closing this issue as we have concluded that KPI Dashboard implementation no longer holds a high priority. In the future, should we choose to prioritize this issue further, we can consider opening a new issue accordingly.
