### ISSUE TITLE
Problem with pytorch 2.0 installation: torchvision 0.15 compiled for CPU only

### ISSUE THREAD

**Issue by MoPl90** [pytorch/pytorch#90272]
### 🐛 Describe the bug

I followed the instructions to [install pytorch 2.0](https://pytorch.org/get-started/pytorch-2.0/#getting-started); however, I cannot get torchvision to install with CUDA support. This prevents me from compiling any pretrained torchvision models. I have CUDA 11.7 installed, all other packages install with CUDA support. Specifying a CUDA supported version did not help either. Any ideas?

```
> pip3 install numpy --pre torch[dynamo] torchvision torchaudio --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117

Successfully installed torch-1.14.0.dev20221205+cu117 torchaudio-0.14.0.dev20221205+cu117 torchtriton-2.0.0+0d7e753227 torchvision-0.15.0.dev20221205+cpu typing-extensions-4.4.0 urllib3-1.26.13
```

This leads to errors when compiling models:

```
import torch
from torchvision.models.detection import fasterrcnn_resnet50_fpn, FasterRCNN_ResNet50_FPN_Weights
device = torch.device("cuda")
model = fasterrcnn_resnet50_fpn(weights=FasterRCNN_ResNet50_FPN_Weights.COCO_V1)

model.eval()
model.to(device)
model = torch.compile(model)
model(torch.randn(1,3,64,64).to(device))
```

```NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.```

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.0rc2
[pip3] torch==1.14.0.dev20221205+cu117
[pip3] torchaudio==0.14.0.dev20221205+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221205+cpu
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.24.0rc2                pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.14.0.dev20221205+cu117          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221205+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221205+cpu          pypi_0    pypi

cc @ezyang @gchanan @zou3519 @seemethere @malfet @soumith

**Comment by lindylin1817** [comment]
@MoPl90 I can installed torchvision with CUDA. After installing the pytorch 1.14(nightlybuild), I didn't use pip install for torchvision. Instead, I downloaded the torchvision source, and compile it. Then, it can work.

**Comment by malfet** [comment]
@osalpekar does it look as another regression caused by Nova?

**Comment by MoPl90** [comment]
Sorry for not coming back to this. It seems that as of Jan 2023 the issue has been fixed. And installation of torchvision via pip works:

`pip3 install numpy --pre torch torchvision --force-reinstall --extra-index-url https://download.pytorch.org/whl/nightly/cu117`
