### ISSUE TITLE
KPI: Introduce backup/collaboration config of Grafana in Git

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#90285]
Expectations:
- Export of dashboard config Grafana in json format.
- Pushing dashboard config to Git (open question: which Git).
- Importing of modified dashboard config (contribution from other author) from Git to verify that it works.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Which grafana config is this referencing? If it's about metrics.pytorch.org, that page was deprecated a while back

**Comment by mantaionut** [comment]
I've created this git repo for holding Grafana configs https://github.com/mantaionut/GrafanaConfigs.

**Comment by vladimir-aubrecht** [comment]
Latest Grafana configuration pushed with documentation on how to import and export.
