### ISSUE TITLE
Torchtext nightly CPU version for Linux not available from December 01 (12/01/2022)

### ISSUE THREAD

**Issue by ajindal1** [pytorch/pytorch#90309]
## Issue description

Torchtext nightly 0.15.0 had a CPU version for linux released daily till 11/30, but has not been released since then. It can be checked on the pytorch nighly link(https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html). Is there any plan to make this package available for Linux?

- PyTorch or Caffe2: Pytorch
- OS: Ubuntu 20.04
- PyTorch version: Nightly
- Python version: 3.8
- CUDA/cuDNN version: 11.6

**Comment by soulitzer** [comment]
You might want to post to https://github.com/pytorch/text instead.
