### ISSUE TITLE
Investigate FSDP mixed precision with manual wrapping

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#90319]
### 🐛 Describe the bug

FSDP Mixed precision and manual wrap might run into some issues, i.e. if m1 is wrapped with mixed precision and m2 is not, m2 might get a low precision activation but have high precision parameters, leading to an error. We should at the least add a unittest for this. 

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by aazzolini** [comment]
@rohan-varma  could you provide more details on what m1 and m2 are, or maybe a simple repro script?

**Comment by awgu** [comment]
This is a known issue with module-level mixed precision. `MixedPrecision.cast_forward_inputs` helps alleviate some cases but not all.
