### ISSUE TITLE
TorchDynamo example crashes on Apple Silicon with `-march=native` flag not supported

### ISSUE THREAD

**Issue by kulinseth** [pytorch/pytorch#90362]
### 🐛 Describe the bug

The torch dynamo code on Apple Silicon CPU is crashing. Minimal code example:

```python
import torch
from typing import List
import torch._dynamo

def toy(a, b):
    x = a / (torch.abs(a) + 1)
    if (b.sum() < 0):
        b = b* -1
    return x*b
compiled_toy = torch.compile(toy)
print(compiled_toy(torch.randn(4), torch.randn(4)))
```

The Output is:

```
BackendCompilerFailed: _compile_fn raised CppCompileError: C++ compile error

Command:
g++ /tmp/torchinductor_kulinseth/rf/crfks4ygnmnznafczrgu2spfbjzqasuvauzpfyqipjvsqvwpk2u5.cpp -shared -fPIC -Wall -std=c++14 -Wno-unused-variable -I/Users/kulinseth/miniconda3/envs/repro/lib/python3.9/site-packages/torch/include -I/Users/kulinseth/miniconda3/envs/repro/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/Users/kulinseth/miniconda3/envs/repro/lib/python3.9/site-packages/torch/include/TH -I/Users/kulinseth/miniconda3/envs/repro/lib/python3.9/site-packages/torch/include/THC -I/Users/kulinseth/miniconda3/envs/repro/include/python3.9 -lgomp -march=native -O3 -ffast-math -fno-finite-math-only -fopenmp -D C10_USING_CUSTOM_GENERATED_MACROS -o/tmp/torchinductor_kulinseth/rf/crfks4ygnmnznafczrgu2spfbjzqasuvauzpfyqipjvsqvwpk2u5.so

Output:
clang: error: the clang compiler does not support '-march=native'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'


Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```
Currently Clang doesn't have support for `-march=native` on Apple Silicon. This is currently on Monterey. I can check on latest Ventura if this flag is added.

### Versions

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.5 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.11.23)
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)  [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.5-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.2
[conda] numpy                     1.23.2           py39h3668e8b_0    conda-forge
```

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by kulinseth** [comment]
On x86 Mac it crashes with:
```
Output:
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'

```

**Comment by soumith** [comment]
i had a PR that is now stale that fixes the OSX issues. 
https://github.com/pytorch/torchdynamo/pull/1488

**Comment by EikanWang** [comment]
@soumith , Do you have a plan to port this PR from torchdynamo repo to the PyTorch repo? Or I can take a look. For the longer term, I'm thinking we should invoke `at::parallel` directly to remove OMP parallel dependency in TorchInductor, just like what we have done for TorchInductor vectorization by invoking `at::vectorize` directly.

**Comment by kulinseth** [comment]
> Okay. let me prepare the PR first and then we can have more discussions on this new PR. By the way, I'm kind of confused because the CI has covered MacOS, both ARM and X86. ![image](https://user-images.githubusercontent.com/55483091/206340808-dbf259bd-bb6c-4766-ae5d-bbb236e1948a.png)

Sorry didn't follow, yeah we have separate builds for both x86 and Apple Silicon platforms.

**Comment by jgong5** [comment]
> By the way, I'm kind of confused because the CI has covered MacOS, both ARM and X86.

PyTorch CI on OSX uses GCC which supports those options (`-fopenmp` and `-march=native`). It would be good to add CI with LLVM compiler as well since I guess LLVM compiler is more frequently used on OSX.

**Comment by EikanWang** [comment]
> Sorry didn't follow, yeah we have separate builds for both x86 and Apple Silicon platforms.

I mean the CI has covered MacOS both ARM and X86 and the crash issue should be captured. But as Jiong mentioned, it depends on the compiler as the CI's compiler is GCC. Then, the root cause is how to enable the TorchIndcutor CPU backend to support CLang.

**Comment by malfet** [comment]
Grabbing for myself, as I have a PR for it (already approved), that I just need to rework, see https://github.com/pytorch/pytorch/pull/89262

**Comment by EikanWang** [comment]
@malfet , the user is required to change the `config.cpp.threads` manually to disable `openmp` w/ https://github.com/pytorch/pytorch/pull/89262. We can dry-compile and dry-run a naive code snippet to detect whether the current platform supports both `omp` and `-march=native` to enhance the situation. Just paste my PR to enhance the situation for your information - https://github.com/pytorch/pytorch/pull/90830
