### ISSUE TITLE
Adam's parameter "differentiable" is not documented

### ISSUE THREAD

**Issue by felixdivo** [pytorch/pytorch#90467]
### 📚 The doc issue

`Adam`'s parameter `differentiable` is not documented. See [here](https://pytorch.org/docs/stable/generated/torch.optim.Adam.html).

### Suggest a potential alternative/fix

Dunno, but the parameter was introduced here:  #82205.

cc @svekars @carljparker @vincentqb @jbschlosser @albanD @janeyx99

**Comment by gchanan** [comment]
CC @albanD

**Comment by janeyx99** [comment]
It looks like none of the optimizers with a `differentiable` parameter have had their docs updated after @emcastillo's changes. Would @emcastillo be interested in updating the documentation here perhaps?

In general, though, is a long term solution to add a linter of sorts to ensure API synchronization between docs + the actual API?
