### ISSUE TITLE
torch.cat fails with "INTERNAL ASSERT FAILED" on MPS device/backend

### ISSUE THREAD

**Issue by selimarikan** [pytorch/pytorch#90479]
### 🐛 Describe the bug

While doing a simple `cat` operation with tensors on `mps` device, the program fails with the following runtime error:
> RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm":277, please report a bug to PyTorch. Placeholder tensor is empty!

Same operation works without any issues on `cpu` and `cuda` devices.
Working example:
```python
t1 = torch.Tensor()

for i in range(2):
    t_temp = torch.Tensor([i])
    t1 = torch.cat((t1, t_temp), dim=0)
```
```bash
tensor([0., 1.])
```

Failing example:
```python
t2 = torch.Tensor().to("mps")

for i in range(2):
    t_temp = torch.Tensor([i]).to("mps")
    t2 = torch.cat((t2, t_temp), dim=0)
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [22], line 5
      3 for i in range(2):
      4     t_temp = torch.Tensor([i]).to("mps")
----> 5     t2 = torch.cat((t2, t_temp), dim=0)

RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm":277, please report a bug to PyTorch. Placeholder tensor is empty!
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.9.6 (default, Oct  6 2022, 11:37:11)  [Clang 14.0.0 (clang-1400.0.29.102)] (64-bit runtime)
Python platform: macOS-12.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-boto3-s3==1.24.76
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] torch==1.12.1
[pip3] torcheval==0.0.5
[pip3] torchtnt==0.0.4
[pip3] torchvision==0.13.1
[conda] No relevant packages

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Hmm, I can't reproduce this on trunk
