### ISSUE TITLE
FSDP: root cause and remove try/except in state_dict_post_hook

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#90495]
### 🚀 The feature, motivation and pitch

For more context, see https://github.com/pytorch/pytorch/pull/90436/files#r1043756086. This try/except should not be needed, but it is not clear why some keys exist and are popped while others are not in the dictionary (i.e. "flat_param" is there, but "_fsdp_wrapped_module.flat_param" is not). We should root cause this and fix by removing the try/except.

cc @ezyang @gchanan @zou3519 @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
I do not see any `try` in that link, so I am closing this.
