### ISSUE TITLE
nn.LSTM not working together with functional_call for calculating the gradient

### ISSUE THREAD

**Issue by cijerezg** [pytorch/pytorch#90500]
### 🐛 Describe the bug

I have the following code:

```
import torch
from torch.nn.utils.stateless import functional_call
import torch.autograd as autograd
import torch.nn as nn

# This is the model
class Encoder(nn.Module):
    def __init__(self, action_dim, z_dim, skill_length):
        super().__init__()
        print(action_dim)
        self.lin1 = nn.Linear(action_dim, action_dim)
        self.lstm = nn.LSTM(input_size=action_dim, hidden_size=z_dim, batch_first=True)
        self.lin2 = nn.Linear(z_dim, z_dim)

    def forward(self, skill):
        a, b, c = skill.shape
        skill = skill.reshape(-1, skill.shape[-1])
        embed = self.lin1(skill)
        embed = embed.reshape(a, b, c)
        mean, _ = self.lstm(embed)
        mean = mean[:, -1, :]
        mean = self.lin2(mean)

        return mean

# This is the initialization function
def pars(model):
    params = {}
    for name, param in model.named_parameters():
        if len(param.shape) == 1:
            init = torch.nn.init.constant_(param, 0)
        else:
            init = torch.nn.init.orthogonal_(param)
        params[name] = nn.Parameter(init)
    return params

# Initializating the model
model = Encoder(4, 2, 5)
x = torch.rand(3, 5, 4)
params = pars(model)


# Running the model with functional_call and calculating gradient.
samp = functional_call(model, params, x)
grad_f = autograd.grad(torch.mean(samp), params.values(),
                       retain_graph=True, allow_unused=True)
print(grad_f)
# grad_f has gradient for the linear layer, but None for the LSTM layer.

# Running the model without functional_call and calculating gradient.
samp = model(x)
grad = autograd.grad(torch.mean(samp), model.parameters(), retain_graph=True)
print(grad)
# grad has gradient for all layers, e.g., linears and lstm.
```

I know the problem is with the LSTM layer because when I use a linear layer with ```nn.Linear```, then the gradient depends on std as well as the linear layer. Unfortunately, I do not know to resolve this problem. I'd appreciate any help.

*Edit: I heavily edited the code provided just to further simplify the example. This code can be copied and run.

**Update Dec 11, 2022**

```
class Encoder(nn.Module):
    def __init__(self, action_dim, z_dim, skill_length):
        super().__init__()
        print(action_dim)
        self.lin1 = nn.Linear(action_dim, action_dim)
        self.lstm = nn.LSTM(input_size=action_dim, hidden_size=z_dim, batch_first=True)
        self.lin2 = nn.Linear(z_dim, z_dim)

    def forward(self, skill):
        a, b, c = skill.shape
        skill = skill.reshape(-1, skill.shape[-1])
        embed = self.lin1(skill)
        embed = embed.reshape(a, b, c)
        mean, _ = self.lstm(embed)
        pdb.set_trace()
        grad1 = autograd.grad(mean.mean(), params.values(),
                              retain_graph=True, allow_unused=True)
        # This gives gradient for the self.lin1 layer, and None for the LSTM
        grad2 = autograd.grad(mean.mean(), self.parameters(),
                              retain_graph=True, allow_unused=True)
        # This gives gradient the LSTM, but None for the self.lin1 layer
        mean = mean[:, -1, :]
        mean = self.lin2(mean)

        return mean
```

When I run it the regular without `functional_call` and calling directly the model, then `autograd.grad(mean.mean(), self.parameters(), allow_unused=True, retain_graph=True)` has gradient for the self.lin1 and LSTM layer.

I don't know if this information is useful, but putting out there just in case.

### Versions

--2022-12-08 16:03:15--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17278 (17K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  16.87K  --.-KB/s    in 0s

2022-12-08 16:03:15 (108 MB/s) - ‘collect_env.py’ saved [17278/17278]

Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Fedora Linux 36 (Workstation Edition) (x86_64)
GCC version: (GCC) 12.2.1 20220819 (Red Hat 12.2.1-2)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.8 (main, Oct 12 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)] (64-bit runtime)
Python platform: Linux-6.0.7-200.fc36.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 520.56.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by cijerezg** [comment]
I was reading the documentation of `functional_call` [see here](https://pytorch.org/docs/stable/generated/torch.nn.utils.stateless.functional_call.html). A note was added saying

```
If the module has active parametrizations, passing a value in the parameters_and_buffers argument with the name set
to the regular parameter name will completely disable the parametrization. If you want to apply the parametrization 
function to the value passed please set the key as {submodule_name}.parametrizations.{parameter_name}.original.
```

In my case, instead of having the key `'lstm.weight_ih_10'`, I used `'lstm.parametrization.weight_ih_10.original'`, which is what I understand from that note, but then I get the error: `AttributeError: 'LSTM' object has no attribute parametrizations`. I suppose I haven't understood the note. I'd appreciate any clarification.

**Comment by jbschlosser** [comment]
Thanks for reporting this, @cijerezg! This issue exists because there is a discrepancy between what `nn.LSTM` reports via `parameters()` / `named_parameters()` and what it uses in its `forward()` call - it uses `self._flat_weights`, flattened versions of the advertised parameters, for performance. Thus, using `functional_call()` to swap in parameters does not have the desired effect.

This is definitely something we need to address, as `functional_call()` is utilized by PT2.
