### ISSUE TITLE
[Dynamo] torch._dynamo.exc.BackendCompilerFailed: tvm raised AttributeError: Can't pickle local object 'WeakValueDictionary.__init__.<locals>.remove'

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#90511]
### 🐛 Describe the bug

This looks like subgraph not able to pickle whatever output eager mode is returning. And if I remove `torch.save(result, filename)` at line 111 of `_dynamo/optimization/subgraph.py`, a seg fault is thrown.

My repro:
```
@dynamo.optimize("tvm")
def toy_example(a, b):
    a = torch.cos(a)
    return a * torch.sin(b)


for _ in range(100):
    toy_example(torch.randn(10), torch.randn(10))
```

complete stacktrace:
```
Traceback (most recent call last):
  File "/home/yj/pytorch/torch/_dynamo/output_graph.py", line 586, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.fake_example_inputs())
  File "/home/yj/pytorch/torch/_dynamo/debug_utils.py", line 915, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs, **kwargs)
  File "/home/yj/pytorch/torch/_dynamo/optimizations/backends.py", line 51, in inner
    return inner(SubGraph(model, example_inputs, tmp), **kwargs)
  File "/home/yj/pytorch/torch/_dynamo/optimizations/backends.py", line 56, in inner
    return fn(model, **kwargs)
  File "/home/yj/pytorch/torch/_dynamo/optimizations/backends.py", line 536, in tvm
    return subgraph.wrap_returns(
  File "/home/yj/pytorch/torch/_dynamo/optimizations/subgraph.py", line 201, in wrap_returns
    expected = self.example_outputs
  File "/home/yj/pytorch/torch/_dynamo/optimizations/subgraph.py", line 25, in inner
    result = fn(self)
  File "/home/yj/pytorch/torch/_dynamo/optimizations/subgraph.py", line 111, in example_outputs
    torch.save(result, filename)
  File "/home/yj/pytorch/torch/serialization.py", line 436, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/yj/pytorch/torch/serialization.py", line 648, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'WeakValueDictionary.__init__.<locals>.remove'
```

### Versions

PyTorch version: 1.14.0a0+gitd957829
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov  4 2022, 20:59:55)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070
Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.1
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.0
[pip3] CoCa-pytorch==0.0.6
[pip3] dalle2-pytorch==1.10.5
[pip3] ema-pytorch==0.0.10
[pip3] functorch==1.14.0a0+408bcf1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.1.5
[pip3] torch==1.14.0a0+git1b1301f
[pip3] torch-fidelity==0.3.0
[pip3] torch-struct==0.5
[pip3] torchaudio==0.14.0a0+8ba323b
[pip3] torchdata==0.6.0a0+d218f79
[pip3] torchmetrics==0.10.3
[pip3] torchrec-nightly==2022.11.21
[pip3] torchtext==0.15.0a0+ed78e3b
[pip3] torchvision==0.15.0a0+4a310f2
[pip3] torchx==0.3.0
[pip3] vector-quantize-pytorch==0.10.11
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] blas                      1.0                         mkl  
[conda] clip-anytorch             2.5.0                    pypi_0    pypi
[conda] coca-pytorch              0.0.6                    pypi_0    pypi
[conda] dalle2-pytorch            1.10.5                   pypi_0    pypi
[conda] ema-pytorch               0.0.10                   pypi_0    pypi
[conda] functorch                 1.14.0a0+408bcf1          pypi_0    pypi
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.1.5                    pypi_0    pypi
[conda] torch                     1.14.0a0+git1b1301f           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                0.14.0a0+8ba323b          pypi_0    pypi
[conda] torchdata                 0.6.0a0+d218f79          pypi_0    pypi
[conda] torchmetrics              0.10.3                   pypi_0    pypi
[conda] torchrec-nightly          2022.11.21               pypi_0    pypi
[conda] torchtext                 0.15.0a0+ed78e3b          pypi_0    pypi
[conda] torchvision               0.15.0a0+4a310f2          pypi_0    pypi
[conda] torchx                    0.3.0                    pypi_0    pypi
[conda] vector-quantize-pytorch   0.10.11                  pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by jansel** [comment]
Related to https://github.com/pytorch/pytorch/issues/89626 ?

**Comment by shingjan** [comment]
@jansel Thanks for the reply! It is possible that this issue is related to #89626. One odd thing is that this error seems to be a problem of saving `example_outputs` from eager mode while running `tvm` as a backend. But if that is the case, then all other non-eager mode backends should have the same error but I can't get a repro on inductor or ts on the same workload.

**Comment by jansel** [comment]
@shingjan inductor never tries to pickle the example_inputs/example_outputs, so it won't his pickling errors.

We should fix pickling, but possible workarounds are:
1) Don't save the tensors to disk
2) Copy to a fresh tensor before saving

Looks like @ezyang has a fix for the other pickling issue in #90628 -- can you test if that fixes this issue too?

**Comment by shingjan** [comment]
@jansel Thanks for the reply! I saw that @ezyang 's PR is merged so I did a rebase but unfortunately this error persists. Should we put in a workaround for non eager mode saving backends for dynamo for now?

**Comment by jansel** [comment]
Ideally we would fix pickling.

Either way, let's just make SubGraph not save example_outputs() to disk.  I'm not convinced that caching optimization is worth it.

**Comment by shingjan** [comment]
close as this is fixed
