### ISSUE TITLE
Update the website to show Python 3.10 is supported for Windows

### ISSUE THREAD

**Issue by aliencaocao** [pytorch/pytorch#90530]
### 📚 The doc issue

Right now, on the website, it shows pytorch on windows only supports python 3.7 to 3.9. However, 3.10 wheels are being released publicly for very long. The website should be updated to not mislead people.

Please correct me if Python 3.10 is NOT officially supported yet (but somehow have stable wheels being made available?)

### Suggest a potential alternative/fix

![image](https://user-images.githubusercontent.com/20109683/206644395-985ab053-ef3c-4abf-a2b0-26ad2e62b978.png)

Change to 3.7 to 3.10.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by nursik** [comment]
It seems that the documentation has been updated and reflects that Python 3.8-3.11 can be used with Pytorch
