### ISSUE TITLE
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'quantized::elu' to ONNX opset version 14 is not supported

### ISSUE THREAD

**Issue by Juelianqvq** [pytorch/pytorch#90533]
### 🐛 Describe the bug

model_quantized = quantize_fx.convert_fx(model_prepared.cpu())
the model_quantized is printable but it's hard to export
Is there any way to have a workaround?

### Versions

1.13.0

**Comment by justinchuby** [comment]
We are overhauling the onnx exporter so new ops may be slow to be supported in the meantime.

You may follow the `quantized_leaky_relu` example to implement `quantized::elu` and register it as a custom operator with `torch.onnx.register_custom_op_symbolic()`

https://github.com/pytorch/pytorch/blob/23a6e1532142a2858d5e5445b5bcd2e468e80a66/torch/onnx/symbolic_opset10.py#L727-L736

**Comment by justinchuby** [comment]
Closing this with the interim solution above.
