### ISSUE TITLE
torch._foreach_copy_

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#90539]
### 🚀 The feature, motivation and pitch

PyTorch provides more than 100 `foreach` operator, but surprisingly `_foreach_copy_` is not one of them. Please consider implementing this.

cc @jbschlosser

**Comment by vadimkantorov** [comment]
currently can be maybe worked around as `torch._foreach_lerp_(dst_tensor_list, src_tensor_list, weight = 1.0)`

**Comment by netw0rkf10w** [comment]
> currently can be maybe worked around as `torch._foreach_lerp_(dst_tensor_list, src_tensor_list, weight = 1.0)`, but of course this is not very ideal / straight-forward

That's a nice trick, but the question is whether it's really faster than the for loop...

**Comment by vadimkantorov** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/107226

**Comment by vadimkantorov** [comment]
@janeyx99 could you please close this too? It seems fixed in that recent PR :)

**Comment by janeyx99** [comment]
yup! indeed
