### ISSUE TITLE
CUDA_VISIBLE_DEVICES is not parsed correctly

### ISSUE THREAD

**Issue by javierbg** [pytorch/pytorch#90543]
## Issue description

The syntax for `CUDA_VISIBLE_DEVICES`, [as defined in the NVIDIA docs](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars) is a comma separated list of identifiers. These identifiers can be integers (as shown in `nvidia-smi`) but they also may be a device UUID preceded by `GPU-`, e.g. `GPU-8932f937-d72c-4106-c12f-20bd9faed9f6`, or even a partial UUID (only the necessary characters to uniquely identify the device), e.g. `GPU-8932f9`.

Right now `torch.cuda.device_count()` uses internally `torch.cuda._parse_visible_devices()`, which assumes that all identifiers are integers. If GPUs are identified by UUID in `CUDA_VISIBLE_DEVICES` instead, those entries are ignored and `torch.cuda.device_count()` returns 0.

This has raised a bug in our job scheduling system (HTCondor), as it uses the devices' UUIDs to allocate GPUs to specific jobs instead of integer IDs.

## Code example

Run python with `CUDA_VISIBLE_DEVICES` set to a device specified by its UUID as follows:

```
CUDA_VISIBLE_DEVICES="GPU-<deviceUUID>" python
```
And then:
```python
import torch
print(torch.cuda.device_count())
```
The result should be 1, but it is 0.

## System Info

```
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (x86_64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.18.4
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.0-19-amd64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti
GPU 6: NVIDIA GeForce RTX 2080 Ti
GPU 7: NVIDIA TITAN Xp
GPU 8: NVIDIA GeForce RTX 2080 Ti
GPU 9: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 515.76
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.8.4
[pip3] torch==1.13.0
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.14.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-lightning         1.8.4                    pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi
```

cc @ngimel

**Comment by ngimel** [comment]
cc @malfet

**Comment by vadimcn** [comment]
Bug was introduced by PR #84879

**Comment by vermesr** [comment]
Hello,

I am confronted with the same problem : the devices ID are not only integers.
Changing the UUID of the GPUs does not seem to be the correct solution for us. We have to stay with previous version of pytorch for now (< 1.13).

Do you know if a later version of pytorch will fix this?

Thank you,
Regards

**Comment by malfet** [comment]
Few remarks, which are missing from the doc:
 - Repeating device index renders visible devices empty (would be nice to confirm if this is an intended behavior or a bug): 
     ```
    $ CUDA_VISIBLE_DEVICES=0,1,1 ./a.out 
    count=0
    ```
- Adding negative number also aborts the sequence:
   ```
    CUDA_VISIBLE_DEVICES=0,1,-1,2 ./a.out 
    count=2
    ```
- `GPU-` prefix is case sensitive:
    ```
    $ CUDA_VISIBLE_DEVICES=GPU-9e8d35e3 ./a.out 
    count=1
    $ CUDA_VISIBLE_DEVICES=gpu-9e8d35e3 ./a.out 
    count=0
    ```
