### ISSUE TITLE
AOT Autograd should differentiate intermediate leaves.

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#90552]
This failure was first noticed by @desertfire in https://github.com/pytorch/pytorch/issues/93589.

A minimum repro looks like this:
```
@torch.compile(...)
def f(x):
    leaf = torch.ones(2, requires_grad=True)
    return leaf, leaf * 2

leaf, out = f(torch.ones(2, requires_grad=True))
out.backward()

# This incorrectly prints None. autograd-ing through "out" should have populated `leaf.grad`.
print(leaf.grad)
```

This case (hopefully) is pretty uncommon: Most autograd leaves in user code come from model parameters, which are always guaranteed to be function inputs. The bad situation happens when you create a differentiable leaf tensor through a factory function, inside of a graph (so it's not a graph input), and return both (leaf, tensor-computation-on-leaf) as outputs.

The problem is that when AOT Autograd traces a fwd + bwd graph, it only differentiates w.r.t graph inputs. One solution (from talking with @ezyang) would be to detect this situation, and "lift" leaves into graph inputs inside of AOT Autograd.

Ideally, we should do this in a way that doesn't add too much overhead to compilation (i.e. it would be nice handling this situation didn't require running the forward() an extra time during compilation).

cc @ezyang @soumith @msaroufim @wconstab @ngimel @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
There is a more complicated version of this problem, https://docs.google.com/document/d/1kBQUNIt1tRyKSiXV-db3C4dTvLYF2fC53dxCXqk08GQ/edit which is substantially harder to fix
