### ISSUE TITLE
Installing PyTorch from source on Raspberry Pi: 

### ISSUE THREAD

**Issue by ashah03** [pytorch/pytorch#9058]
## Issue description

Trying to install PyTorch from source on Raspberry Pi Zero (ARMv6).

## Code example

Here is the trace: 

 90%] Linking CXX executable ../bin/scalar_test
/home/pi/git/pytorch/build/lib/libcaffe2.so: undefined reference to `cpuinfo_arm_linux_init'
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/scalar_test.dir/build.make:95: recipe for target 'bin/scalar_test' failed
make[2]: *** [bin/scalar_test] Error 1
CMakeFiles/Makefile2:681: recipe for target 'caffe2/CMakeFiles/scalar_test.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/scalar_test.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-nnpack caffe2 nanopb libshm'

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Source
- Build command you used (if compiling from source):  `python3 setup.py install`
- OS:
- PyTorch version: Latest (0.4.0)
- Python version: 3.5.3
- CUDA/cuDNN version: None
- GPU models and configuration: None
- GCC version (if compiling from source): 6.3.0
- CMake version: 3.7.2

**Comment by vishwakftw** [comment]
If you are installing PyTorch, you should use `python setup.py install`.

**Comment by soumith** [comment]
@ashah03 Could you paste the full build log, it would be really helpful.
I compiled on an RPi about 4 weeks ago, and it went fine.

**Comment by ashah03** [comment]
@vishwakftw I did use python setup.py install.

**Comment by weiyangfb** [comment]
Maybe try to update submodules `git submodule update --init --recursive` ?

**Comment by zacario-li** [comment]
@ashah03 modify /scpipts/build_raspbian.sh   
about line 39, add "-DUSE_GLOO=OFF"  
this works for me.

**Comment by pprp** [comment]
hello @zacario-li , thank you very much for the link you provided, but I wonder how to use it. Is it built correctly? I met the same problem and I cannot solve it. Could you tell me how to use your files? Thank you very much

**Comment by pprp** [comment]
# Caffe2 python run does not have GPU support



### system info

- PyTorch or Caffe2: Caffe2
- OS: ubuntu16.04
- How I installed Caffe2: source
- Python version: python 3.6.0
- CUDA/cuDNN version:8.0.61/7.0.5
- GPU models and configuration:Nvidia GTX 1080
- GCC version:5.4.0
- cmake version: 3.5.1
- miniconda

### What I did

- I have tried to build caffe2 from source (following [this](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support)):

After I installed the dependencies on that page and clone the repository, I run this command `FULL_CAFFE2=1 python setup.py install`. I test `from caffe2.python import core` and I got `Failure`

- Then I find a solution in github [following this(@kaisark)](https://github.com/pytorch/pytorch/issues/6259)

I passed the test and got Success but I found it doesn't support GPU.

### Test caffe2 python core

```
(cf2) caffe@learner-pc:~$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from caffe2.python import core
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
>>>
```

### Relavent Information

```
(cf2) caffe@learner-pc:~$ which python
/home/caffe/miniconda3/envs/cf2/bin/python
(cf2) caffe@learner-pc:~$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.
(cf2) caffe@learner-pc:~$ echo $PYTHONPATH

(cf2) caffe@learner-pc:~$ echo $PATH
/home/caffe/miniconda3/envs/cf2/bin:/home/caffe/bin:/home/caffe/.local/bin:/sbin:/home/caffe/miniconda3/bin:/usr/local/cuda-8.0/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/local/protobuf/bin
(cf2) caffe@learner-pc:~$ echo $LD_LIBRARY_PATH
/usr/local/lib:/usr/local/cuda-8.0/lib64::/usr/local/protobuf/lib:/home/caffe/github/nccl/build/lib
(cf2) caffe@learner-pc:~$
```

### Thanks for any help!

**Comment by mruberry** [comment]
Closing due to age. If there's still an issue installing a new version of PyTorch please file a new issue.
