### ISSUE TITLE
CUDA error with torch.multinomial

### ISSUE THREAD

**Issue by Oktai15** [pytorch/pytorch#9062]
I have the following code:
`a = torch.multinomial(b, 5)`
where `b` is 
`tensor([ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0.], device='cuda:0')`

I notice that tensor has one non-zero element.

I got the next CUDA error when I ran my code:

/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/THCTensorRandom.cuh:109: void renormRowsL1(T *, long, long) [with T = float]: block: [0,0,0], thread: [0,0,0] Assertion `THCNumerics<T>::gt(sum, zero)` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCTensorMathScan.cu line=74 error=59 : device-side assert triggered

RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1524586445097/work/aten/src/THC/generic/THCTensorMathScan.cu:74

Also I noticed that everything is okay if I transfer tensor to CPU

**Comment by SsnL** [comment]
All zero tensor is not a valid probability distribution (weighting considered or not). It's now a hard error on CPU too.

**Comment by Oktai15** [comment]
@SsnL it's not true. Everything is okay if I transfer tensor to CPU

**Comment by SsnL** [comment]
When i said “it’s an error now” I meant that it errors on master.

And erroring is the correct thing to do in this situation.

**Comment by Oktai15** [comment]
@SsnL Please, check this issue again. 

https://github.com/wengong-jin/icml18-jtnn/issues/13#issuecomment-421145545

Not only me found this problem.

**Comment by SsnL** [comment]
Ah yes. Sorry about that. I reran your code and it incorrectly triggers an assert error on master.

**Comment by SsnL** [comment]
```
>>> b = torch.tensor([ 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.
, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0
., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.
, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0
., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.
, 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], devi
ce='cuda:0')
>>> a = torch.multinomial(b, 5)
>>> a
THCudaCheck FAIL file=../aten/src/THC/generic/THCTensorCopy.cpp line=68 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssnl/sftp/pytorch/torch/tensor.py", line 60, in __repr__
    return torch._tensor_str._str(self)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 286, in _str
    tensor_str = _tensor_str(self, indent)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 204, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/ssnl/sftp/pytorch/torch/_tensor_str.py", line 76, in __init__
    copy = torch.empty(tensor.size(), dtype=torch.long).copy_(tensor).view(tensor.nelement())
RuntimeError: cuda runtime error (59) : device-side assert triggered at ../aten/src/THC/generic/THCTensorCopy.cpp:68
```

**Comment by t-vi** [comment]
I'll go have a look.

**Comment by asanakoy** [comment]
Looks like it's still not fixed.

**Comment by t-vi** [comment]
@asanakoy: You think that because you did ... and got ... instead of the expected ... ? Could you please fill in the ...?

**Comment by asanakoy** [comment]
I can reproduce exactly the same issue as in https://github.com/pytorch/pytorch/issues/12260 which was closed without fix.

**Comment by t-vi** [comment]
So here we moved GPU to the then CPU behaviour of not raising an error.
Now CPU has raises errors (after fixing #12260) but GPU does not. Checking could be device asserts (as we used to) or sync to CPU after each sample. Neither seems attractive.

**Comment by asanakoy** [comment]
Ok, I see. It was decided to throw an error in https://github.com/pytorch/pytorch/pull/12490.
But the error is not seen for me. I have reported it in https://github.com/pytorch/pytorch/pull/12490.
