### ISSUE TITLE
Magma installed via conda, not found during build

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/pytorch#9063]
## Issue description

I am building PyTorch, and have Magma installed using conda. However, this is not being found during the build.

### Build Log

This is the [build log](https://gist.github.com/vishwakftw/b705ca3322de7c45ea70f8ef63d8932f) relevant to the issue.

## System Info
PyTorch version: 0.5.0a0+33c75a0
Is debug build: No
CUDA used to build PyTorch: 8.0.44

OS: Ubuntu 16.04.2 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
CMake version: version 3.11.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: GPU 0: GeForce 940M
Nvidia driver version: 367.57
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.1.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] torch (0.5.0a0+33c75a0, /media/vishwak/Official/Projects/pytorch)
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+33c75a0           <pip>

**Comment by soumith** [comment]
that is weird. is your $CMAKE_PREFIX_PATH correctly set to `"$(dirname $(which conda))/../"`?

**Comment by vishwakftw** [comment]
I set it to `"(dirname $(which conda))/../"`, and now it compiles with MAGMA. Thanks.
