### ISSUE TITLE
[build] pass nvcc arch flags to gloo

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9065]
pytorch log:
```
-- Autodetected CUDA architecture(s): 6.1 6.1 
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
```

gloo log:
```
-- CUDA detected: 9.1
-- Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 sm_70
```

Other built libs I've seen, including libshm, nccl, c10d, use the correct arch flags.

cc @malfet @seemethere @walterddr

**Comment by mruberry** [comment]
@malfet I wonder if this is still an issue?

**Comment by malfet** [comment]
Most likely it's already fixed, but let me check that after the break.

**Comment by walterddr** [comment]
I checked with multiple different env setting of `TORCH_CUDA_ARCH_LIST` and verify that cmake build/third_part/gloo is correctly contains the build command with NVCC flags. closing this. please reopen if it is not addressed correctly.
