### ISSUE TITLE
Update Reducer.cpp to not call into ops.cpp

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#90659]
Once https://github.com/pytorch/pytorch/pull/88330 is landed and ProcessGroup.hpp calls the ops directly, we should replace all reference to ops.cpp such as https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/reducer.cpp#L732 to be just `process_group->(...)`

I am creating this issue as I am referencing this in a TODO comment on the PR.

**Comment by awgu** [comment]
I recommend using permalinks in case someone updates `reducer.cpp`:
https://github.com/pytorch/pytorch/blob/8fd31ac4dade93a10822ba32c1f2293827b2b2f3/torch/csrc/distributed/c10d/reducer.cpp#L732
