### ISSUE TITLE
Fix cudnnHandle_t in Handles.cpp

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#907]
There are two problems with the way we manage cudnnHandles in [Handles.cpp](https://github.com/pytorch/pytorch/blob/master/torch/csrc/cudnn/Handles.cpp):

1. We sometimes see SIGSEGV on exit when the handles are destructed
2. They don't work on non-default streams

We tried making the handles table thread-local, but that causes slow downs and deadlocks because the handles can be destructed after every forward pass in a data parallel module.

We should figure out a better solution.

**Comment by gchanan** [comment]
Removing high-priority since it was removed previously and added back with no new justification.
