### ISSUE TITLE
Importing torch causes segfault when using python installed with conda

### ISSUE THREAD

**Issue by vedantroy** [pytorch/pytorch#90749]
### 🐛 Describe the bug

Cross-posted to: https://discuss.pytorch.org/t/importing-torch-causes-segfault-when-using-python-installed-with-conda/168212

I create a conda environment with: `conda create -y -n dev python=3.7`.
In install torch with:
```
conda run -n dev pip install torch==1.14.0.dev20221027+cu116 --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu116
```

running: `python3 -c import torch` gives a segfault.
Here's the gdb backtrace:

```
-c (gdb) r -c 'import torch'
Starting program: /opt/conda/envs/dev/bin/python3 -c 'import torch'
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 31265]

Program received signal SIGSEGV, Segmentation fault.
0x000055555564d27c in type_name (context=<optimized out>, type=0x555558aa7630)
    at /home/conda/feedstock_root/build_artifacts/python_1635226063427/work/Objects/typeobject.c:433
433	/home/conda/feedstock_root/build_artifacts/python_1635226063427/work/Objects/typeobject.c: No such file or directory.
```

### Versions

The script segfaults.

cc @seemethere @malfet @osalpekar @atalman @ezyang @gchanan @zou3519

**Comment by sam-ulrich1** [comment]
Same happens to me (ran gdb to confirm reasoning) including using venv except I can run pytorch when executing scripts through pycharm if my environment is configured in pycharm

**Comment by ezyang** [comment]
bumping priority due to activity

**Comment by malfet** [comment]
From the backtrace it looks like one somehow installed two version of PyTorch which conflict with each other (as suggested by `/home/conda/feedstock_root/build_artifacts/python_163522606342` path in the backtrace, as all binaries build by PyTorch binary pipelines should start with `/var/jenkins` or `/pytorch` path)

Closing, but please do not hesitate to open a new one if it happens again (and please run `python3 -mtorch.utils.collect_env` to make such mixed up installations easier to detect)
