### ISSUE TITLE
 cuda.h: No such file or directory - when using torch.compile() in 2.0 in a new conda environment 

### ISSUE THREAD

**Issue by jphdotam** [pytorch/pytorch#90757]
### 🐛 Describe the bug

I've made a new conda venv today using the install command recommended on the PyTorch homepage (since last night's fix related to CUDA).

I can train and evaluate non-compiled networks and CUDA works normally in traditional eager mode.

When I try to `torch.compile()` the model, however, get the error:

```
/tmp/tmpj75i_m99/main.c:2:10: fatal error: cuda.h: No such file or directory
    2 | #include "cuda.h"
      |          ^~~~~~~~
compilation terminated.
```

### Versions

PyTorch version: 2.0.0.dev20221210
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe

Nvidia driver version: 525.60.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-lightning==1.8.4.post0
[pip3] torch==2.0.0.dev20221210
[pip3] torchaudio==0.14.0.dev20221212
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.15.0.dev20221212
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0           py310h7f8727e_0
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0
[conda] mkl_random                1.2.2           py310h00e6091_0
[conda] numpy                     1.23.4          py310hd5efca6_0
[conda] numpy-base                1.23.4          py310h8e6c178_0
[conda] pytorch                   2.0.0.dev20221210 py3.10_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch-nightly
[conda] pytorch-lightning         1.8.4.post0              pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                0.14.0.dev20221212     py310_cu117    pytorch-nightly
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227           py310    pytorch-nightly
[conda] torchvision               0.15.0.dev20221212     py310_cu117    pytorch-nightly

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
Yeah unfortunately packaging issues for pytorch 2.0 are not ironed out yet. It requires a working cudatoolkit in an accessible location (in particular, cuda.h and ptxas). cc @malfet

**Comment by malfet** [comment]
Yeah, plan to package the two in torch and pass those to triton somehow.

**Comment by malfet** [comment]
Related to https://github.com/pytorch/pytorch/issues/90377

**Comment by rwightman** [comment]
I ran into this issue but it seems to be model specific, which strikes me as odd if it's a packaging issue? 

Ie ran through many models w/o issue and then it hit one that always fails with `main.c:2:10: fatal error: cuda.h: No such file or directory` ... are there different code gen paths based on model where a tooling issue would be exposed?

**Comment by ngimel** [comment]
That's odd, `#include "cuda.h"` is used in absolutely every compiled kernel. @rwightman can you try setting `compile_threads` to 1 in `_inductor/config.py` and see if it gets you around the error for that model? The only model specific thing is how the kernels to compile would be doled out to worker processes, I can't imagine how that would affect search paths, but I don't have any other ideas.

**Comment by jphdotam** [comment]
Dear @rwightman I got this trying to compile a `tf_efficientnet_b5_ns` (or maybe it was b3, not sure) from your `timm` package. I didn't try other ones.

**Comment by rwightman** [comment]
> 

I'm actually running through tests on the efficientnet models right now, that one worked fine, it was another variant that failed. Interesting. I think I might actually have an include path issue on my system after apt flipped an alternatives symbolic link on me, but really weird that most models succeed compilation and only some fail...

**Comment by rwightman** [comment]
@ngimel k, I fixed the path issue, an apt update installed cublas 11.8 while holdiing back cuda/cudnn (currently 11.7) so alternatives path for incl was changed to cuda-11-8 w/ only cublas headers in there but bin path was still 11-7 for nvcc. Weird state, and weirder still that most torch.compiles worked but some specific ones didn't.

I reset cuda alternative back to 11-7 and the failure cases work now. So @jphdotam I compiled every model in efficientnet.py w/o issue just now (testing some refactoring, but no modelling changes what would have made it work where it didn't before).

**Comment by ngimel** [comment]
@rwightman compilation happens here https://github.com/openai/triton/blob/8650b4d1cbc750d659156e2c17a058736614827b/python/triton/compiler.py#L1156, it's possible that `cuda_home_dirs()` is somehow cached differently for different models. I agree it shouldn't happen, we'll try to work with triton to see what's going on.

**Comment by nisheethlahoti** [comment]
Ran into the same problem. Temporary fix is to set the `CUDA_HOME` environment variable to the conda env path.
i.e. call the script as `CUDA_HOME=$CONDA_PREFIX python ...` instead of `python ...`

**Comment by virtadpt** [comment]
I ran into the same thing (though I'm not using Conda).  I worked around it in much the same way: `CUDA_HOME=/opt/cuda python train.py`

Note that, in my case at least, CUDA_PATH was set, not CUDA_HOME.

**Comment by ngimel** [comment]
`cuda.h` is now packaged with pytorch_triton and triton package.
