### ISSUE TITLE
PR author cannot rebase PR using pytorchbot

### ISSUE THREAD

**Issue by qqaatw** [pytorch/pytorch#90758]
### 🐛 Describe the bug

PR author cannot rebase PR using pytorchbot, an example: https://github.com/pytorch/pytorch/pull/89864#issuecomment-1348298051.

The [wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) says `You, along with any member of the pytorch organization, can rebase your PR.`, where the PR author should have the permission to rebase.

### Versions

unrelated

**Comment by H-Huang** [comment]
cc @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment]
Sorry, the wiki is out of date, the PR author hasn't been able to rebase a PR since September due to security loopholes it exposed https://github.com/pytorch/test-infra/pull/779

I'll update the wiki

**Comment by qqaatw** [comment]
Hey @ZainRizvi, seems like now regular contributors can rebase their PRs using pytorchbot, should we update the wiki?

**Comment by ZainRizvi** [comment]
Thanks for the call out. Updated the wiki and proposed a PR to update the bot's help text as well:
https://github.com/pytorch/test-infra/pull/4134

**Comment by qqaatw** [comment]
Thanks @ZainRizvi.
