### ISSUE TITLE
cmake error in all machines when trying to rebuild from source

### ISSUE THREAD

**Issue by AlexLuya** [pytorch/pytorch#9077]
Hello,
    I followed the instruction here:https://github.com/pytorch/pytorch#installation to build pytorch from source
instead using:
`    sudo python2 setup.py install`
I used:
`     cmake .. & sudo make install -j `nproc``

and the same thing was did in 3 ubuntu 16.04 machine,and pytorch works in these machines now,but when trying to run:
`      cd build & rm -rf * & cmake ..  `
I got all kinds of errors like:
```
CMake Error at cmake/External/nnpack.cmake:73 (set_property):
  set_property could not find TARGET nnpack.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:94 (include)
  CMakeLists.txt:206 (include)


CMake Error at cmake/External/nnpack.cmake:74 (set_property):
  set_property could not find TARGET pthreadpool.  Perhaps it has not yet
  been created.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:94 (include)
  CMakeLists.txt:206 (include)
```
and I have tried in 3 machines,and they all give similar cmake errors,what did I wrong?

**Comment by soumith** [comment]
please use the instructions in the README and dont use `cmake .. && make install`. PyTorch wont install that way, and we dont support it.

**Comment by AlexLuya** [comment]
@soumith,if I can,I will,why,
```
I installed caffe2 from source by
make &sudo make install
not by
python setup.py install
due to
CUDA_NVCC_EXECUTABLE
not found even
echo $CUDA_NVCC_EXECUTABLE
will print out
/usr/local/cuda/bin/nvcc
and 'nvcc' is actually being here
```
by the way,the problem is still there,can you help to reinstall it?
