### ISSUE TITLE
[Inductor] decompose aten.uniform_

### ISSUE THREAD

**Issue by min-jean-cho** [pytorch/pytorch#90815]
### 🚀 The feature, motivation and pitch

Currently `aten.uniform_` fallbacks to `FallbackKernel: torch.ops.aten.uniform_.default`. 
```python
import torch

def foo(x):
    return x.uniform_(-1, 1)

opt_foo = torch.compile(foo)
print(opt_foo(torch.randn(10)))
```
`aten.uniform_` is decomposable to something like `(high - low) * torch.rand(x) + low`. 

### Correctness
```
X ~ U(0, 1) 
[0,1)

(θ_high - θ_low) * X ~ U(0, (θ_high - θ_low))
[0, θ_high - θ_low)

(θ_high - θ_low) * X + θ_low ~ U(θ_low, θ_high)
[0 + θ_low, θ_high - θ_low + θ_low)
=[θ_low, θ_high)
```

 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by jgong5** [comment]
> Hi @ashokei @jgong5, Please help let me know if any comments on this.

Sounds good to me.

**Comment by Chillee** [comment]
Also sounds good to me.

**Comment by min-jean-cho** [comment]
Thanks for verifying @Chillee ~ I'll work on this.

**Comment by jansel** [comment]
Looks reasonable, any links to non-overflow formula?

**Comment by min-jean-cho** [comment]
Thanks @lezcano, @jansel for the comments, regarding overflow:

```
let MAX = max possible value 
let MIN = min possible value

(high-low) * Uniform(0,1) + low  ?> MAX
(MAX-MIN) * 1 + MIN ?> MAX (max value sampled from Uniform(0,1))
MAX - MIN + MIN ?> MAX
MAX !> MAX
=> no overflow 
```

I'm not sure if this formula will overflow.. Please correct me if I'm missing something. 

By the way, I also see numpy uses the same formula https://github.com/numpy/numpy/blob/main/numpy/random/src/distributions/distributions.c#L394-L396

**Comment by ngimel** [comment]
Suppose high is close to max possible value for the datatype, and low is close to min, then `uniform(low, high)` is ok, but `(high-low)` will overflow. I don't think that's a practical concern though.

**Comment by lezcano** [comment]
I mentioned this because we hit exactly that problem when sampling extremal values within the testing suit when implementing `make_tensor`. 
For a stable implementation, see
https://github.com/pytorch/pytorch/blob/a01c1ee5940c808e62d95bed38eb3611f80fcce1/torch/testing/_creation.py#L22-L28

Note that the `if` condition works for floating points as they overflow to `inf`.

**Comment by ngimel** [comment]
This is not a problem for `uniform_` decomposition though, because `uniform_` itself errors out in this case, so the only thing decomposition needs to do is error out in the same way:
```
In [3]: a.uniform_(-3e38, 3e38)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 a.uniform_(-3e38, 3e38)

RuntimeError: uniform_ expects to-from <= std::numeric_limits<Float>::max(), but found to=3e+38 and from=-3e+38 which result in to-from to exceed the limit

```

**Comment by min-jean-cho** [comment]
Thanks @ngimel, @lezcano for the helpful comments. 

> because uniform_ itself errors out in this case, so the only thing decomposition needs to do is error out in the same way

May I ask why decomposition needs to error out in the same way? Since `uniform_` itself errors out which is caught when running the node with the given `low` and `high` values here https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/utils.py#L1064-L1066. 

```
def foo(x):
    return x.uniform_(-3e38, 3e38)
    
opt_foo = torch.compile(foo)
x = torch.randn(10)
print("opt_foo: ", opt_foo(x))
```
```
RuntimeError: Failed running call_method uniform_(*(FakeTensor(FakeTensor(..., device='meta', size=(10,)), cpu), -3e+38, 3e+38), **{}):
uniform_ expects to-from <= std::numeric_limits<Float>::max(), but found to=3e+38 and from=-3e+38 which result in to-from to exceed the limit
```

**Comment by lezcano** [comment]
I'd say that accepting the wider range may be a plus, but whatever works really.

**Comment by jansel** [comment]
> I'd say that accepting the wider range may be a plus, but whatever works really.

If eager errors out, I'd expect an error to get raised from FakeTensor tracing -- so it doesn't matter what the decomp does.
