### ISSUE TITLE
[feature request] scatter_mul_, scaller_div_, etc.

### ISSUE THREAD

**Issue by ptrblck** [pytorch/pytorch#9081]
I would like to ask, if there is a need for additional `scatter_XXX` functions.
Currently I'm implementing `scatter_mul_`, `scatter_div_` and `scatter_sub_`.

I didn't come up with a valid use case yet, but if you think these functions would be beneficial for PyTorch I can create a merge request after finalizing the code.

**Comment by SsnL** [comment]
Thanks for submitting the issue. We track this request at https://github.com/pytorch/pytorch/issues/6850 . There are some discussions there too.
