### ISSUE TITLE
dynamo.export does not provide node.meta["tensor_meta"]

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#90839]
### 🐛 Describe the bug

dynamo.export doesn't seem to be annotating the "tensor_meta" metadata on the nodes in the graph. But using make_fx directly does annotate it. Our use case in Torch-MLIR will require "tensor_meta" to be annotated on the graph.

```python
import torch
import functorch
import torch._dynamo as dynamo

def f(x):
    return x * x

example_inputs = (torch.randn(3, 4),)
gm, guards = dynamo.export(f, *example_inputs, aten_graph=True)
#gm = functorch.make_fx(f)(*example_inputs)


for node in gm.graph.nodes:
    if "tensor_meta" in node.meta:
        tensor_meta = node.meta["tensor_meta"]
        print(f"{tensor_meta} on node {node}")
    else:
        print(f"No tensor_meta on node {node}")
```

Output:

```
No tensor_meta on node arg0
No tensor_meta on node mul_tensor
No tensor_meta on node output
```

But if you uncomment the make_fx line, we see:

```
TensorMetadata(shape=torch.Size([3, 4]), dtype=torch.float32, requires_grad=False, stride=(4, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={}) on node x_1
TensorMetadata(shape=torch.Size([3, 4]), dtype=torch.float32, requires_grad=False, stride=(4, 1), memory_format=torch.contiguous_format, is_quantized=False, qparams={}) on node mul
No tensor_meta on node output
```

### Versions

PyTorch version: 2.0.0.dev20221213+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 12.2.0-3) 12.2.0
Clang version: 14.0.6-2
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.8 (main, Nov  3 2022, 15:17:13) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-5.19.11-1rodete1-amd64-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0rc2
[pip3] torch==2.0.0.dev20221213+cpu
[pip3] torchvision==0.15.0.dev20221213+cpu
[conda] Could not collect

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by silvasean** [comment]
I also don't see tensor_meta when using aot_autograd for dynamo in non-export mode. Having tensor_meta available is one of the killer features that we are expecting to get from PT2 and it allows us to delete a large portion of our codebase. Any help on getting tensor_meta available through dynamo would be very appreciated :pray:

**Comment by silvasean** [comment]
I found that `node.meta["val"]` contains a FakeTensor with similar metadata available -- is there a reason to prefer `node.meta["tensor_meta"]` vs `node.meta["val"]`? And is there a way to know when each are available?

**Comment by Chillee** [comment]
Generally, I think w're moving towards preferring using `node.meta['val']`, and relying on that as our primary source of metadata.

The general reason to prefer `node.meta['val']` is that it's the *actual* tensor captured during tracing. So things like aliasing relations will also be captured appropriately. And in the future, other tensor types like sparse tensors could also be represented correctly.

Finally, it unifies between the "metadata" for tensor values as well as non-tensor values (such as symints).

**Comment by silvasean** [comment]
Ah nice. Thanks for that info. Does that mean that `node.meta['val']` is potentially keeping alive tons of activation memory on device? I noticed a "symbolic" tracing mode but I still see mention of tracing modes that "actually run the code".

**Comment by Chillee** [comment]
No, `node.meta['val']` always holds a `FakeTensor` (which doesn't associate any real memory with it). We didn't always trace with FakeTensors, which is why we used to use `meta['tensor_meta']` and the state is in a bit of a mess right now.

**Comment by silvasean** [comment]
Got it! Thanks! Closing this now :)
