### ISSUE TITLE
torch.compile: Warning for torch.distributions.Independent

### ISSUE THREAD

**Issue by mctigger** [pytorch/pytorch#90834]
### 🐛 Describe the bug

When compiling a function that uses torch.distributions.Independent some of the methods throw warnings:

```
[2022-12-14 13:09:34,087] torch._dynamo.symbolic_convert: [WARNING] /home/clearml-agent/miniconda3/envs/core-2.0/lib/python3.8/site-packages/torch/distributions/independent.py <function Independent.log_prob at 0x7f46f5cf7160> [TensorVariable()] {} missing a required argument: 'value'
```

or 

```
[2022-12-14 13:04:58,211] torch._dynamo.symbolic_convert: [WARNING] /home/clearml-agent/miniconda3/envs/core-2.0/lib/python3.8/site-packages/torch/distributions/independent.py <function Independent.rsample at 0x7fe66cd46790> [] {} missing a required argument: 'self'
```

Example Code:

```
import torch
from torch.distributions import Normal, Independent

def fn(tensor):
    normal = Normal(tensor, torch.tensor(1))
    independent = Independent(normal, 1)
    return independent.log_prob(tensor) # also for rsample()

a = torch.rand(5, 2)
fn(a)
fn_compiled = torch.compile(fn)
fn_compiled(a)
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20221210+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB
GPU 4: NVIDIA A100-PCIE-40GB
GPU 5: NVIDIA A100-PCIE-40GB

Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0rc2
[pip3] torch==2.0.0.dev20221210+cu117
[pip3] torchaudio==0.14.0.dev20221210+cu117
[pip3] torchmetrics==0.11.0
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20221210+cu117
[conda] numpy                     1.24.0rc2                pypi_0    pypi
[conda] torch                     2.0.0.dev20221210+cu117          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221210+cu117          pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221210+cu117          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by yanboliang** [comment]
This is a bug, the reason is dynamo using ```inspect.getattr_static``` to get attribute from a ```UserDefinedObjectVariable``` for most cases including this one, but it returns a python ```function``` type rather than ```bound method``` type which has ```self``` as the first argument. I opened [an issue](https://github.com/python/cpython/issues/100418) at cpython to check if this is a bug of ```inspect.getattr_static```, otherwise, I'll send a fix for dynamo.

**Comment by ezyang** [comment]
They have responded it is not a bug
