### ISSUE TITLE
Optimize CUDA svd and eig

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9083]
For `eig`, when `eigenvector=False`, do not force the row-major-contiguous input to be column-major-contiguous because `A` and `A^T` have same evalues.

For `svd`, when input is row-major-contiguous, calculate `svd` as if `svd` is done on the input's transpose, and then return `r0^T, r1, r2`, where `(r0, r1, r2)` are from magma `gesdd`.

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @VitalyFedyunin

**Comment by vishwakftw** [comment]
@SsnL Considering this is a thread related to SVD and eig, I thought if I could ask a question here:

Would it be beneficial if we had an option like `compute_uv` in NumPy for SVD? Both LAPACK and MAGMA seem to support this option, and I think this would make `matrix_rank` and other implementations depending on the singular values alone faster than earlier.

**Comment by dvirginz** [comment]
I think that until this is fixed, torch documentation should mention the fact and recommend working on the CPU for small matrices. The boost is up to 100(!) times faster on the CPU for 3X3 batched matrices

**Comment by mruberry** [comment]
> I think that until this is fixed, torch documentation should mention the fact and recommend working on the CPU for small matrices. The boost is up to 100(!) times faster on the CPU for 3X3 batched matrices

This is a fine idea if it's still the case, and we would accept a PR better describing the performance characteristics of these functions in a note. However, per https://github.com/pytorch/pytorch/issues/52293#issuecomment-779998187, we should verify what the current performance is on the latest nightly first.
