### ISSUE TITLE
Cuda not available despite compatible installs

### ISSUE THREAD

**Issue by eliegoudout** [pytorch/pytorch#90845]
### 🐛 Describe the bug

Hello,

I'm trying to enable CUDA on my Torch setup. I tried lots of things and I really don't know what to do more.

### Known Requirements:

From the information I could gather, I know that for CUDA to be available, I need to:
- Have a CUDA capable GPU (I have a _GeForce GTX 1080 Ti_, no problem here),
- Have a CUDA adapted driver,
- Install Torch for the corresponding CUDA version.

### What I did:
I have a 64-bit Windows version `1703`. Sadly, [DCH drivers are not supported on Windows versions older than 1803](https://nvidia.custhelp.com/app/answers/detail/a_id/4777/~/nvidia-dch%2Fstandard-display-drivers-for-windows-10-faq). So I'm stuck with [the latest NVIDIA _**standard**_ driver](https://www.nvidia.com/Download/Find.aspx?lang=en-us), which is version `472.84`.

Then, according to [this page](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html) (_Table 3_), the latest CUDA Toolkit I can install is version `11.4.4`, which I found [here](https://developer.nvidia.com/cuda-toolkit-archive).

After I installed my NVIDIA driver and the 11.4.4 CUDA Toolkit, I went to [pytorch.org](https://pytorch.org/get-started/locally/) to find out how to install needed packages, after which I ran:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu114
```
I changed last bit to `cu114` thinking I had to since I would use CUDA `11.4.4`.

Everything installed properly, after which I tried the following
```pycon
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
```

...to my great disapointment.

The only last idea iI have is that for some reason, when I start Python, it says `[...] on win32`. But I don't get why. My system says I'm on a 64-bit system and I installed Python 3.10.8 from 64-bit installer...

I anyone can help, it'd be greeeaaatly appreciated.

Thank you!

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Professionnel
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.15063-SP0
Is CUDA available: False
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] Could not collect
```

**Comment by mikaylagawarecki** [comment]
It seems from the versions section that the version of pytorch you installed is `1.13.0+cpu` the CPU version, might you perhaps have multiple versions of pytorch installed?

**Comment by eliegoudout** [comment]
Hi, thank you for your answer.
Sorry I have not had time to boot up my computer...

I can see that indeed, but I don't know how to fix it, since I did download torch with `https://download.pytorch.org/whl/cu114`. I don't think I have multiple torch, I uninstalled everything before doing exactly what I described higher. I don't really know how I could check, but I have this
```
C:\Users\Me>pip show torch
Name: torch
Version: 1.13.0 
ummary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:[...]\python310\lib\site-packages
Requires: typing-extensions
Required-by: stable-baselines3, torchaudio, torchvision
```

If you know what I could try, I'd really appreciate it!
Thanks again.

**Comment by mikaylagawarecki** [comment]
I would suggest creating a [conda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) environment and installing torch in the conda environment

**Comment by eliegoudout** [comment]
Thank you for your help. Would you mind explaining to me why this would be susceptible to help? I don't have conda installed, but I made sure to install my torch properly as described.

**Comment by eliegoudout** [comment]
I think I actually found the problem: There is [no install for CUDA 11.4](https://github.com/pytorch/pytorch/issues/75992#issuecomment-1228948650). So I'll will try with CUDA 11.3 as soon as I can (since I cannot install CUDA 11.6 compatible driver on my Windows) and keep you updated.

**Comment by eliegoudout** [comment]
Using the following install (found [here](https://pytorch.org/get-started/previous-versions/)), for CUDA 11.3 did work:
```
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
```
```pycon
>>> import torch
>>> torch.cuda.is_available()
True
```

Thanks again for trying to help!
