### ISSUE TITLE
Exporter for ONNX GroupNormalization operator

### ISSUE THREAD

**Issue by yuanyao-nv** [pytorch/pytorch#90878]
### 🚀 The feature, motivation and pitch

GroupNormalization has been introduced into ONNX opset 18. https://github.com/onnx/onnx/blob/main/docs/Operators.md#GroupNormalization

It would be more efficient if the torch-to-ONNX converter could directly export to this new op instead of using a combination of primitive ops.

**Comment by justinchuby** [comment]
Thanks. We expect support after bumping onnx to the latest version in PyTorch.

**Comment by thiagocrepaldi** [comment]
As we are currently focusing on `torch.onnx.dynamo_export` as the new ONNX exporter, we don't plan to support new operators ourserves for the `torch.onnx.export` API.

As of https://github.com/pytorch/pytorch/pull/118828, the onnx exporter supports new operators for opset version 18 up to 20.
Your contribution with GroupNormalization would be appreciated.
