### ISSUE TITLE
PyTorch 2.0: RuntimeError: Inference tensors do not track version counter.

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#90882]
### 🐛 Describe the bug

When training ViT with `torch.compile`, I obtained the following error:
 
```bash
WARNING:root:Failed to collect metadata on function, produced code may be suboptimal.  Known situations this can occur are inference mode only compilation involving resize_ or prims (!schema.hasAnyAliasInfo() INTERNAL ASSERT FAILED); if your situation looks different please file a bug to PyTorch.
Traceback (most recent call last):
  File "/home/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 1163, in aot_wrapper_dedupe
    fw_metadata, _out, _num_aliasing_metadata_outs = run_functionalized_fw_and_collect_metadata(
  File "/home/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 272, in inner
    outs = f(*f_args)
  File "/home/.local/lib/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 2065, in functional_call
    out = Interpreter(mod).run(*args[params_len:], **kwargs)
  File "/home/.local/lib/python3.10/site-packages/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/home/.local/lib/python3.10/site-packages/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/home/.local/lib/python3.10/site-packages/torch/fx/interpreter.py", line 265, in call_method
    return getattr(self_obj, target)(*args_tail, **kwargs)
  File "/home/.local/lib/python3.10/site-packages/torch/_inductor/overrides.py", line 37, in __torch_function__
    return func(*args, **kwargs)
RuntimeError: Inference tensors do not track version counter.

While executing %expand : [#users=1] = call_method[target=expand](args = (%self_cls_token, 40, -1, -1), kwargs = {})
Original traceback:
Module stack: {}
  File "/home/code/ViT/models/ViT.py", line 436, in forward_features
    cls_tokens = self.cls_token.expand(N, -1, -1)  # stole cls_tokens impl from Phil Wang, thanks
 |   File "/home/code/ViT/models/ViT.py", line 468, in forward
    x = self.forward_features(x)
```

I am not sure what caused the error, but the training is still running. Please help me to fix this error.

### Versions

1.14.0.dev20221206+cu117

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by desertfire** [comment]
Can you please run the minifier to produce a small repro (instructions at https://pytorch.org/docs/master/dynamo/troubleshooting.html)? Thanks.

**Comment by ezyang** [comment]
the vit in torchbench as well as timm models passes with torch.compile. So we won't be able to diagnose your problem without knowing the exact version of ViT.py you're using. As another potential workaround, try turning off inference mode before running torch.compile (this is poorly tested and it would not surprise me if it did not work well.)

**Comment by netw0rkf10w** [comment]
@desertfire @ezyang I'm really sorry I was unable to follow this issue and then I forgot. @ezyang is right, that was an issue with `inference_mode()`.
For the sake of future viewers of this thread, this is how one should do:

```python
    # We shouldn't used compiled model for evaluation
    # https://github.com/pytorch/pytorch/issues/90882
    model_eval = model
    if args.compile:
        model = torch.compile(model)
    model.to(device)
    # Then use `model` for training and `model_eval ` for evaluation
```

**Comment by desertfire** [comment]
> inference_mode()

To be clear, what @ezyang meant is if you don't use `with inference_mode():` in your code, then `torch.compile` still works for the inference side, meaning in your code you can still use the optimized `model` for eval.

**Comment by netw0rkf10w** [comment]
> > inference_mode()
> 
> To be clear, what @ezyang meant is if you don't use `with inference_mode():` in your code, then `torch.compile` still works for the inference side, meaning in your code you can still use the optimized `model` for eval.

Thanks. This is indeed what I understood, but yes my comment above was a bit misleading. There are two ways of dealing with this issue: either replacing `with torch.inference_mode():` with `with torch.no_grad():`, or using the non-compiled model for evaluation (with `inference_mode()`). I have updated my comment to add this clarification.
