### ISSUE TITLE
torch ModuleNotFoundError in ipython 

### ISSUE THREAD

**Issue by pedropgusmao** [pytorch/pytorch#909]
Hi,

I installed pytorch from source using anacoda3 but ipython does not seem to be able to import the torch module somehow. 

```
(pytorch) pedro@hal9000:~/workspace$ ls
benchmarks
(pytorch) pedro@hal9000:~/workspace$ python 
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.1.9+0720ba5'
>>> 
(pytorch) pedro@hal9000:~/workspace$ ipython
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import torch
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c031d3dd82fc> in <module>()
----> 1 import torch

ModuleNotFoundError: No module named 'torch'

In [2]: 
```
Any ideas? 

Thanks

**Comment by apaszke** [comment]
print `sys.module_path` in both and check if they're any different

**Comment by pedropgusmao** [comment]
ipython path does not seem to include pytorch...

```
(pytorch) pedro@hal9000:~/workspace$ python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', '/home/pedro/anaconda3/envs/pytorch/lib/python36.zip', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/lib-dynload', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/site-packages', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision-0.1.7-py3.6.egg', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/site-packages/six-1.10.0-py3.6.egg', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/site-packages/Pillow-4.0.0-py3.6-linux-x86_64.egg', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/site-packages/olefile-0.44-py3.6.egg', '/home/pedro/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg']
>>>
(pytorch) pedro@hal9000:~/workspace$ ipython3
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import sys

In [2]: print(sys.path)
['', '/home/pedro/anaconda3/bin', '/home/pedro/anaconda3/lib/python36.zip', '/home/pedro/anaconda3/lib/python3.6', '/home/pedro/anaconda3/lib/python3.6/lib-dynload', '/home/pedro/anaconda3/lib/python3.6/site-packages', '/home/pedro/anaconda3/lib/python3.6/site-packages/Sphinx-1.5.1-py3.6.egg', '/home/pedro/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg', '/home/pedro/anaconda3/lib/python3.6/site-packages/IPython/extensions', '/home/pedro/.ipython']

In [3]: import torch
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c031d3dd82fc> in <module>()
----> 1 import torch

ModuleNotFoundError: No module named 'torch'

In [4]:
```

**Comment by soumith** [comment]
your pytorch is installed in an env called pytorch (maybe you did this on purpose), but ipython is actually installed in the root env. You presumably need to first install ipython in the "pytorch" env and launch that ipython to have `import torch` work.

**Comment by pedropgusmao** [comment]
Great, it worked when I removed it from root and installed it after sourcing the environment . 
Thanks

**Comment by cleemesser** [comment]
I think this is some weirdness interaction with ipython and conda environments and possibly bash's caching of the path. I installed pytorch but forgot to install ipython into the new environment initially. Ipython (from root enviroment) couldn't find torch on import --this was expected.

But it still couldn't import torch from ipythonn even after I installed ipython into my pytorch environment. Surprising!

It resolved though just by starting up a new shell and activated the environment again and it worked.

**Comment by ictunit** [comment]
Hello,
I have the same problem here, but it works on the command prompt and doesn't work on the Jupyter Notebook. it shows same error.



['', 'C:\\Users\\Mohammed', 'C:\\Users\\Mohammed\\Anaconda3\\python37.zip', 'C:\\Users\\Mohammed\\Anaconda3\\DLLs', 'C:\\Users\\Mohammed\\Anaconda3\\lib', 'C:\\Users\\Mohammed\\Anaconda3', 'C:\\Users\\Mohammed\\Anaconda3\\lib\\site-packages', 'C:\\Users\\Mohammed\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Mohammed\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Mohammed\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Mohammed\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Mohammed\\.ipython']

import torch
import torch
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-eb42ca6e4af3> in <module>()
----> 1 import torch

ModuleNotFoundError: No module named 'torch'



Any idea please. thank you all.

**Comment by Naldoza** [comment]
1. try to uninstall your installed pytorch.
2. conda install -c peterjc123 pytorch-cpu
3. on your conda type python
4. import torch
