### ISSUE TITLE
Filling a tensor uses all cpu cores

### ISSUE THREAD

**Issue by root20** [pytorch/pytorch#9094]
## Issue description
When I generate a tensor with the function main2() in the following code, the code runs one process and uses only one cpu core.
However, when I fill (using .fill_(0)) the tensor with 0 (or multiply it with 0, or generate a tensor using torch.zeros(...)), the code runs multiple processes and uses whole cpu cores.
Is this behavior intended?

In my code, at every iteration I need a zero tensor, so if I run the code, all of the cpu cores are occupied by my code. 
If I run two such codes at the same time, computation speed becomes very slow.

## Code example

```
import torch

def main1():
    torch.Tensor(1, 100, 1025).fill_(0)
    import pdb;pdb.set_trace()

def main2():
    torch.Tensor(1, 100, 1025)
    import pdb;pdb.set_trace()

if __name__ == '__main__':
    # main1()     # This code runs multiple processes which use whole cpu cores
    # main2()    # This code runs one process and uses only one cpu core

```

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 396.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by SsnL** [comment]
It is intended. You can also use `torch.set_num_threads` to control the amount of parallelism: https://pytorch.org/docs/master/torch.html?highlight=threads#torch.set_num_threads
