### ISSUE TITLE
Add support for torch.zero_grad in dynamo w/ dynamic shapes

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#90952]
### 🐛 Describe the bug

curr graph breaks on call_method NNModuleVariable() zero_grad [ConstantVariable(bool)] {}'

### Versions

.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by mlazos** [comment]
So I disabled this because dynamo was very slow to trace this. The changes from https://github.com/pytorch/torchdynamo/issues/1803 may have helped but I haven't benchmarked it since I disabled it explicitly

**Comment by williamwen42** [comment]
@mlazos is the graph break still necessary?

**Comment by mlazos** [comment]
Actually this wasn't what I thought. I think we can support this, PR incoming

**Comment by mlazos** [comment]
inlining should fix this, I'll close when that's landed.

**Comment by mlazos** [comment]
https://github.com/pytorch/pytorch/pull/132053 is closed, closing
