### ISSUE TITLE
Uninitialised access to member of torch::indexing::TensorIndex

### ISSUE THREAD

**Issue by lnw** [pytorch/pytorch#90951]
### 🐛 Describe the bug

`torch::indexing::TensorIndex` has several ctors that leave some members unintialised, for example `boolean_`. It doesn't have a user provided copy-ctor, so one is generated by the compiler.

As a consequence, writing `std::vector<torch::indexing::TensorIndex> test = {torch::indexing::None};` (or equally for Ellipsis, Slice, etc), will first construct a `TensorIndex` object from `None`, and copy that new `TensorIndex` into the vector using the compiler generated copy-ctor.  Inside the copy-ctor there is an access to the uninitialised `boolean_`.

Using gcc-12 / Debian / libtorch-1.13, a maybe-uninitialised warning is emitted at compile time.  When compiling with UBSan, an error is emitted at runtime (<some number> is not a valid value for bool), ie, an uninitialised bool is read.

Would it be an appropriate solution to give `bool boolean_`  and `int64_t integer_` default values (`false` / `0`)?

cheers, lukas wirz

### Versions

(I'm on a different computer just now, but have previously analysed the issue on three different installations.)
Libtorch-1.12 as well as 1.13 are affected. I have reproduced the issue on Linux (Debian testing, Centos 7) and Windows (10 / msvc 16.11).

**Comment by albanD** [comment]
Hi,

We do access this uninitialized memory but copy it into a field that is never read after. So that is ok right?

**Comment by lnw** [comment]
Yes, the target field is not accessed afterwards (for all I know).  However, it leads to the described warnings at compile and runtime.  Furthermore, I think a very aggressive but standard conform compiler might optimise away any code path leading to the UB, which would cause wrong behavior -- so I think this should be addressed.
I don't assume there would be a relevant performance impact when we give default values to the bool + int64_t?  I'd then make a PR with those two lines.

**Comment by albanD** [comment]
Thanks for the details!
We would definitely accept a PR fixing this!

**Comment by albanD** [comment]
Thanks for sending a fix!
