### ISSUE TITLE
Some of the problems with torch.quantization.quantize_dynamic( ) 

### ISSUE THREAD

**Issue by Smile-L-up** [pytorch/pytorch#90986]
### 🐛 Describe the bug

Reference code, The model is based on bert-tiny
```
quantized_model = torch.quantization.quantize_dynamic(
    model, {torch.nn.Linear}, dtype=torch.qint8
)
```
```python
torch.onnx.export(quantized_model,
                  (inputs[0], inputs[1]),
                  'quantized_model.onnx',
                  opset_version=13,
                  do_constant_folding=True,  
                  input_names=["batch_input_ids", "batch_att_mask"],  
                  output_names=["logits"], 
                  dynamic_axes={"batch_input_ids": [0], "batch_att_mask": [0],
                                "logits": [0]})
```
Errors
```python
1、
NotImplementedError: Could not run 'quantized::linear_dynamic' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build)
2、
AttributeError: 'LinearPackedParams' object has no attribute '_modules'
```

### Versions

When I use torch.quantization.quantize_dynamic to quantify Bert, I find that. Can't use GPU training anymore. You can still train on the CPU. Another troubling problem is that the quantified model does not support the conversion into onnx. I find from historical issues that the quantization model does not seem to support the GPU. Do you have any plans for this aspect in the future?

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by jcaip** [comment]
Hi @Smile-L-up 

Yes currently GPU quantization is not supported but @HDCharles is currently working on this. 

For ONNX export, this is not something our team plans to support or is on our roadmap, although it is a common issue so we welcome any external contributions to add support. You can check out [this thread](https://discuss.pytorch.org/t/onnx-export-of-quantized-model/76884/32) for some workarounds that may apply to your model:
