### ISSUE TITLE
CUDA 12 Support

### ISSUE THREAD

**Issue by edward-io** [pytorch/pytorch#90988]
### 🚀 The feature, motivation and pitch

CUDA was [released](https://developer.nvidia.com/blog/cuda-toolkit-12-0-released-for-general-availability/) on December 12 2022, with support for FP8 operations. Getting PyTorch to build using CUDA 12 would unlock performance gains, especially for Lovelace and Hopper architectures, e.g. using [Transformer Engine](https://github.com/NVIDIA/TransformerEngine).

Magma may need to be updated as CUDA 12 dropped deprecated functions. Relevant issue: [Magma: Can't build with CUDA 12](https://bitbucket.org/icl/magma/issues/65/cant-build-with-cuda-12)

cc: @malfet 

Related: https://github.com/pytorch/pytorch/issues/74627 (cc: @ezyang)

cc @ngimel

**Comment by ptrblck** [comment]
We are working on the CUDA12 bringup internally and will follow up with needed code changes.

**Comment by edward-io** [comment]
@ptrblck: awesome! Is there a rough timeline on when it'll be available?

**Comment by johnnynunez** [comment]
> We are working on the CUDA12 bringup internally and will follow up with needed code changes.

and python 3.11 please :P

**Comment by guillermoJacquez** [comment]
Is cuda 11.8 getting skipped?

**Comment by edward-io** [comment]
@guillermoJacquez NVIDIA's PyTorch docker container uses 11.8: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-22-11.html#rel-22-11

**Comment by ptrblck** [comment]
> Is cuda 11.8 getting skipped?

No, we are working to enable nightly builds for 11.8 here: https://github.com/pytorch/pytorch/pull/90826

> Is there a rough timeline on when it'll be available?

We are working on some critical issues we need to fix before enabling the support.

**Comment by albanD** [comment]
Closing this in favor of https://github.com/pytorch/pytorch/issues/91122 which has a lot more details on the plan.
