### ISSUE TITLE
Caffe2 Train your own image

### ISSUE THREAD

**Issue by aswin1980** [pytorch/pytorch#9099]
Hi,
I would like to train my own set of images(Railroad signals). I would like to know how to do that from scratch. The tutorial is inadequate and does not explain how to do image training from scratch but explains in using a pre-trained dataset/models(e.g iris or handwriting).

Appreciate if the tutorial can be relooked in explaining how to train images from scratch.

Thanks

**Comment by goodlux** [comment]
We are in the process of writing new tutorials, and this topic should definitely be covered clearly. In the meantime, check out this thread:

https://github.com/caffe2/caffe2/issues/1755

Hopefully this helps in the meantime.

**Comment by BIGBALLON** [comment]
@aswin1980 
what about this one? [caffe2_demo](5118f8de3a1692439f5e6158774f8a181bfdf2ec)

you can check this [code](https://github.com/BIGBALLON/Caffe2_Demo/blob/master/02_cifar10/caffe2_cifar10.py) which train images from scratch (without lmdb, just use memory data)

```
def train_epoch(model, train_x, train_y):
    loss_sum = 0.0
    correct = 0.0
    batch_num = args.train_images // args.batch_size + 1
    for i in range(0, batch_num):
        # data, label = next_batch(i, args.batch_size, train_x, train_y, args.train_images)
        data, label = next_batch_random(args.batch_size, train_x, train_y)
        if args.use_augmentation:
            data = data_augmentation(data)

        workspace.FeedBlob("data", data, device_option=device_opts)
        workspace.FeedBlob("label", label, device_option=device_opts)
        workspace.RunNet(model.net)

```

**Comment by aswin1980** [comment]
@BIGBALLON Thanks for letting me know. Where is the way to pass the image folder
Below is the image I need to train. This is a signal post. The image is taken from the video and it is having a transparent background.

![105](https://user-images.githubusercontent.com/4591328/42442095-6d4ddde0-8387-11e8-95bb-d7f13e5c2cdc.png)

**Comment by MatthewInkawhich** [comment]
@aswin1980 Check out the "CIFAR10_Part1" and "CIFAR10_Part2" tutorials in the [caffe2/tutorials](https://github.com/caffe2/tutorials/) repo. Part 1 specifically shows how to take a custom image dataset (in this case .png mirror of the CIFAR-10 dataset), format it, create image LMDBs, and train a model on them.

**Comment by aswin1980** [comment]
@MatthewInkawhich Thanks for the info. I will check it.

**Comment by Samjith888** [comment]
Hii,

      How to train and build a caffe2 model by using custom image data sets for object detection? I found for Image classification only. Any suggestion  please?
