### ISSUE TITLE
torch.where signature mismatch

### ISSUE THREAD

**Issue by LucaLumetti** [pytorch/pytorch#91003]
### 📚 torch.where signature mismatch

Based on the page of `torch.where` [1], the signature of that function should be
`torch.where(condition, x, y)`

When i try to call such function with:
`torch.where(condition=t, x=1, y=2)`
where `t` is a boolean `torch.tensor` i get the following error:

```
TypeError: where() received an invalid combination of arguments - got (Tensor, x=int, y=int), but expected one of:
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other)
      didn't match because some of the keywords were incorrect: x, y
 * (Tensor condition, Number self, Tensor other)
      didn't match because some of the keywords were incorrect: x, y
 * (Tensor condition, Tensor input, Number other)
      didn't match because some of the keywords were incorrect: x, y
 * (Tensor condition, Number self, Number other)
      didn't match because some of the keywords were incorrect: x, y
```

This means that the keywords of the function are: `condition, input, other` `instead of condition, x, y`, as can be seen in the source code [2].

[1]: https://pytorch.org/docs/stable/generated/torch.where.html
[2]: https://github.com/pytorch/pytorch/blob/583d216c1a767fcb9a8fc33fc2f7a19ff20eba95/aten/src/ATen/native/TensorCompare.cpp#L511

### Suggest a potential alternative/fix

Is it possible to change the signature of the where function by changing the keyword names. I would avoid changing the documentation and leaving such naming as most of the frameworks use `where(condition, x, y)`, thus PyTorch should also adopt that signature.
I would be honored to do such contribution.

cc @albanD

**Comment by albanD** [comment]
Good catch!
Could you send a PR updating the doc here: https://github.com/pytorch/pytorch/blob/0b255b3f80d9d365b5f4a064c88278270d6bfac4/torch/_torch_docs.py#L12493-L12514 ?

**Comment by LucaLumetti** [comment]
@albanD yes I would be happy to!
Just a quick question, how would I handle the fact that the key arguments change based on the type?
When you pass `(Tensor, Tensor, Tensor)` or `(Tensor, Tensor, Number)` the keys are `(condition, input, other)`
When you pass `(Tensor, Number, Tensor)` or `(Tensor, Number, Number)` the keys are `(condition, self, other)`
I'm not even sure why keeping such naming convention would be better than changing the key parameters to something that is more standard across other different frameworks.

**Comment by albanD** [comment]
Ho this is weird, I though they were all (condition, self, other) from the definition:
https://github.com/pytorch/pytorch/blob/bc764f453d02f59560fb97c77f72e86451aec182/aten/src/ATen/native/native_functions.yaml#L5927-L5948

**Comment by LucaLumetti** [comment]
It is not completely clear to me how the key params are mapped from the C++ implementation to the python frontend but this is what PyTorch wants as key arguments (which I took from the error I've written in the first issue message):
```
 * (Tensor condition)
 * (Tensor condition, Tensor input, Tensor other)
 * (Tensor condition, Number self, Tensor other)
 * (Tensor condition, Tensor input, Number other)
 * (Tensor condition, Number self, Number other)
```
For reference, this happens in both torch stable (`1.13.1+cu117`) and torch nightly (`2.0.0.dev20221230+cpu`). I cannot find anywhere where such `input` keyword is taken from as both in C++ implementation and the definition you cited, they are all `(condition, self, other)`. Any guess where this may come from?

**Comment by albanD** [comment]
This is done by the codegen in https://github.com/pytorch/pytorch/blob/34f2d3e6ae56744c20c2f859f97101dff291bbbc/torchgen/api/python.py#L230-L231 for Tensor inputs.

I'm sure we could update this code to also rename `Number` to make sure it remains consistent and everything becomes "input".
