### ISSUE TITLE
[pytorch, bug] Indexing inconsistencies

### ISSUE THREAD

**Issue by arogozhnikov** [pytorch/pytorch#9101]
## Issue description

when indexing from negative number to zero, results are

- inconsistent with numpy
- inconsistent for different axes
- sometimes results in crashes

## Code example

```python
x = numpy.zeros([10, 10])
x.shape          # (10, 10)
x[-3:0].shape    # (0, 10)
x[-3:0, :].shape # (0, 10)
x[:, -3:0].shape # (10, 0)

x = torch.zeros(10, 10)
x.shape          # torch.Size([10, 10])
x[-3:0].shape    # torch.Size([0])
x[-3:0, :].shape # error
x[:, -3:0].shape # torch.Size([10])
```

## System Info

Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] deepvoice3-pytorch (0.0.4+708a241, /home/arogozhn/projects/deepvoice3_pytorch)
[pip3] numpy (1.14.0)
[pip3] torch (0.4.0)
[pip3] torchtext (0.2.1)
[pip3] torchvision (0.2.0)
[conda] Could not collect

**Comment by fmassa** [comment]
This is fixed in 1.0 thanks to support for tensors with zero in its dimensions
