### ISSUE TITLE
Large tensor support in all_to_all

### ISSUE THREAD

**Issue by H-Huang** [pytorch/pytorch#91030]
### 🐛 Describe the bug

Reported by @pritamdamania87. We are putting large embedding tables (ex: 14GB) into DDP. As a result, for such a large tensor the length of it overflows int32. We should probably look into this and support large tensors.

https://github.com/pytorch/pytorch/blob/bd94ee66ea361e97158d37d6ddd8dbbeb8b624ef/torch/csrc/distributed/c10d/Utils.hpp#L453-L456

Creating this issue to track this

### Versions

main

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @kwen2501 @awgu

**Comment by kwen2501** [comment]
https://github.com/pytorch/pytorch/pull/98368 fixes this issue.
