### ISSUE TITLE
How to set USE_OPENCV=ON when 'python setup_caffe2.py install'

### ISSUE THREAD

**Issue by AlexLuya** [pytorch/pytorch#9104]
When using cmake & make,we can set options like this:
    `-D USE_**=ON`
How to do same thing when using
     ` python setup.py install`

**Comment by pjh5** [comment]
AFAIK setuptools just doesn't support this. We can add code to read environment flags and add them to the cmake flags (like this https://github.com/pytorch/pytorch/blob/master/setup.py#L153 ) but we have to do it manually for every flag that we want to support. The easiest thing for you to do is to just add the flag manually to this list https://github.com/pytorch/pytorch/blob/master/setup_caffe2.py#L140 .

I will close b/c this is a shortcoming of setuptools. And setup_caffe2.py and setup.py will be merged soon, so setting up manual flag propogation for all cmake, Caffe2, and Pytorch flags would be a lot of code to maintain for not that much added convenience.

**Comment by dqbruce** [comment]
export USE_OPENCV=On
and then run
python setup.py install

----
--   USE_OPENCV            : ON
--     OpenCV version      : 2.4.9.1
