### ISSUE TITLE
[RFC] [Inductor] decompose aten.normal_

### ISSUE THREAD

**Issue by min-jean-cho** [pytorch/pytorch#91085]
### 🚀 The feature, motivation and pitch

Currently `aten.normal_` fallbacks to `FallbackKernel: torch.ops.aten.normal_.default`. 

```python
import torch

def foo(x):
    return x.normal_()

opt_foo = torch.compile(foo)
x = torch.randn(10)
print("opt_foo: ", opt_foo(x))
```

`aten.normal_` is decomposable using [Polar method](https://en.wikipedia.org/wiki/Marsaglia_polar_method#:~:text=The%20Marsaglia%20polar%20method%20is,of%20the%20Monte%20Carlo%20method.) to something like:

```python
import torch

def standard_normal():
    # Polar method: more efficient version of Box-Muller method 
    while True:
        # step 1 
        u1 = torch.rand(1) # u1 ~ Uniform(0,1)
        u2 = torch.rand(1) # u2 ~ Uniform(0,1)
        # step 2 
        v1 = 2 * u1 - 1
        v2 = 2 * u2 - 1 
        s = v1 ** 2 + v2 ** 2
        # step 3
        if s <= 1 and s != 0:
            break 
    x = ((-2 * torch.log(s) / s) ** 0.5) * v1 # x ~ Normal(0, 1)
    return x

def normal(mean, std):
    # mean = loc 
    # std = scale
    x = standard_normal() 
    return x * std + mean # x ~ Normal(mean, std**2)


s = []
for _ in range(10000):
    s.append(normal(10, 2))
print(torch.mean(torch.tensor(s))) # verify sampled mean is close to 10 
print(torch.std(torch.tensor(s))) # verify sampled std is close to 2
```

### Alternatives

I should highlight that the above is based on [Polar method](https://en.wikipedia.org/wiki/Marsaglia_polar_method#:~:text=The%20Marsaglia%20polar%20method%20is,of%20the%20Monte%20Carlo%20method.), which is the method Numpy used in their legacy code, [here](https://github.com/numpy/numpy/blob/main/numpy/random/src/legacy/legacy-distributions.c#L18-L40). But a more recent method is based on [Ziggurat algorithm](https://en.wikipedia.org/wiki/Ziggurat_algorithm), which is the method Numpy uses now, [here](https://github.com/numpy/numpy/blob/main/numpy/random/src/distributions/distributions.c#L137-L170). However, to be honest, I don't have an understanding of the Ziggurat algorithm. 

### Additional context

Decomposing standard normal distribution is the important part, and from which normal distribution is composed, other distributions (e.g., log-normal distribution) can be easily composed as well. 

```python
def log_normal(mean, std):
    x = normal(mean, std) # x ~ Normal(mean, std**2)
    return torch.exp(x) # x ~ LogNormal(mean, std**2)
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by min-jean-cho** [comment]
Hi @jgong5, @ashokei, Please help let me know if any comments on this.

**Comment by jgong5** [comment]
I'm not sure about the numerical aspect of this decomposition but as I commented in https://github.com/pytorch/torchdynamo/issues/327#issuecomment-1357113455, we'd better also consider how easy it is for the backend to leverage the decomposed pattern for better performance. In particular, in this decomposition implementation, the polar method (which is one type of acceptance-rejection methods) relies on a while loop to accept random values and looks hard to the backend to optimize.

**Comment by min-jean-cho** [comment]
> the polar method (which is one type of acceptance-rejection methods) relies on a while loop to accept random values

Just wanted to add that the while loop, `if s <= 1 and s != 0`, will be true for almost all majority of the cases.

**Comment by min-jean-cho** [comment]
> I'm curious where the normal_ call in the graph is coming from. Is it getting injected by a decomp somewhere? Is it in user code?

I see a model here https://github.com/pytorch/torchdynamo/issues/1385 uses `uniform_` for instance. I would guess that other similar models may use `normal_`.

**Comment by min-jean-cho** [comment]
Hi @jansel , could you please help provide some context here: https://github.com/pytorch/pytorch/blob/master/test/inductor/test_torchinductor_opinfo.py#L404 - why `randn` is not tested for `assert_equal`, and `inductor_override_kwargs` ? thanks!

**Comment by ngimel** [comment]
Because `randn` in eager and inductor produces different values, so the test cannot compare them.
