### ISSUE TITLE
PyTorch 1.13.1 Docker image has 1.13.0 installed

### ISSUE THREAD

**Issue by janvdp** [pytorch/pytorch#91097]
### 🐛 Describe the bug

Running the 1.13.1 containers, the installed PyTorch version is 1.13.0:

Run either of these bash commands to start the container:

```bash
docker run -it --rm pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel
```

or 

```bash
docker run -it --rm pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
```

The (relevant) output of 
```bash
conda list | grep pytorch
```
is the following, which lists 1.13.0 instead of 1.13.1.

```bash
dnspython                 2.2.1                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
ipython                   8.7.0           py310h06a4308_0  
python                    3.10.8               haa1d7c7_0  
python-etcd               0.4.5                    pypi_0    pypi
python-libarchive-c       2.9                pyhd3eb1b0_1  
pytorch                   1.13.0          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.1          py310h06a4308_0  
torchtext                 0.14.0                    py310    pytorch
torchvision               0.14.0              py310_cu116    pytorch
```

### Versions

Install wget:

```bash
apt-get update
apt-get install wget -y
```

The script output:

root@4a3c041ea5e1:/workspace# python collect_env.py
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.27

Python version: 3.10.8 (main, Nov  4 2022, 13:48:29) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0
[pip3] torchelastic==0.2.2
[pip3] torchtext==0.14.0
[pip3] torchvision==0.14.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.22.3          py310hfa59a62_0  
[conda] numpy-base                1.22.3          py310h9585f30_0  
[conda] pytorch                   1.13.0          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtext                 0.14.0                    py310    pytorch
[conda] torchvision               0.14.0              py310_cu116    pytorch
root@4a3c041ea5e1:/workspace# 

cc @ezyang @gchanan @zou3519 @seemethere @malfet

**Comment by seemethere** [comment]
Looks like that was my mistake, I'll re-build them today

**Comment by seemethere** [comment]
@janvdp this should be fixed now, ran a check on my local machine but would you mind checking on your side as well?

**Comment by janvdp** [comment]
@seemethere Thanks for fixing this! 

I have tested on multiple machines and the version is now correct. 

The machine that already pulled the image needs to pull again or build with --no-cache...
