### ISSUE TITLE
vmap support for torch.complex

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#91175]
## Tasks
Add vmap support for the following PyTorch operations. That is, each one needs a batching rule.
- [ ] torch.complex

## Expected behavior
Currently, when one does vmap over them, they raise a warning suggesting the batching rule is not implemented:
```py
import torch
from functorch import vmap
x = torch.randn(32, 2, 3)
y = torch.randn(32, 2, 3)
z = vmap(torch.complex)(x, y)
#  UserWarning: There is a performance drop because we have not yet implemented the batching rule
```
We expect to not see a warning

## Read this!

See this note for more context https://github.com/pytorch/pytorch/blob/master/functorch/writing_batching_rules.md

If you're new to developing PyTorch and/or function transforms, we would recommend reading through https://github.com/pytorch/pytorch/wiki/Core-Frontend-Onboarding#unit-8-function-transforms-optional

Should likely be similar to https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/functorch/BatchRulesBinaryOps.cpp

## Testing

`pytest test/functorch/test_vmap.py -v -k "op_has_batch_rule and complex"` should pass (currently, it is an expected failure).

cc @Chillee @samdow @soumith

**Comment by lorenzbaraldi** [comment]
I would like to try implement it

**Comment by HazemHassine** [comment]
I'd like to try to implement this vmap asap

**Comment by Siddharth11235** [comment]
If it isn't done, I'd love to give it a shot.

**Comment by AliE02** [comment]
Hi, I would like to try implementing this if still open.
