### ISSUE TITLE
vmap support for torch.copysign

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#91176]
## Tasks
Add vmap support for the following PyTorch operations. That is, each one needs a batching rule.
- [ ] torch.copysign

## Expected behavior
Currently, when one does vmap over them, they raise a warning suggesting the batching rule is not implemented:
```py
import torch
from functorch import vmap
x = torch.randn(32, 2, 3)
y = torch.randn(32, 2, 3)
z = vmap(torch.copysign)(x, y)
#  UserWarning: There is a performance drop because we have not yet implemented the batching rule
```
We expect to not see a warning

## Read this!

See this note for more context https://github.com/pytorch/pytorch/blob/master/functorch/writing_batching_rules.md

If you're new to developing PyTorch and/or function transforms, we would recommend reading through https://github.com/pytorch/pytorch/wiki/Core-Frontend-Onboarding#unit-8-function-transforms-optional

Should likely be similar to https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/functorch/BatchRulesBinaryOps.cpp

## Testing

`pytest test/functorch/test_vmap.py -v -k "op_has_batch_rule and copysign"` should pass (currently, it is an expected failure).

cc @Chillee @samdow @soumith

**Comment by malfet** [comment]
Grabbing for myself, just for fun.

**Comment by jasonkhadka** [comment]
@malfet Are you still working on this? Else, I will take a shot at it.

**Comment by malfet** [comment]
@jasonkhadka please give me until Mon ;)

**Comment by jasonkhadka** [comment]
Sure, give me a ping if you can't make it. I would like to work on it.

> @jasonkhadka please give me until Mon ;)

**Comment by debasis9658** [comment]
Hello @malfet . I am interested in this project and would love to learn more about this. We can have a conversation if you need any help. Thank You

**Comment by malfet** [comment]
> Sure, give me a ping if you can't make it. I would like to work on it.
> 
> > @jasonkhadka please give me until Mon ;)

Feel free to grab the issue for youself.
