### ISSUE TITLE
Conda Install: PackageNotFoundError 

### ISSUE THREAD

**Issue by lucashu1** [pytorch/pytorch#9120]
Hi, I'm trying to install Pytorch on MacOS (High Sierra) with Conda 4.3.15, Python 3.5.

I ran:
```
conda create -n pytorch
source activate pytorch
conda install pytorch torchvision -c pytorch
```

However, I keep getting a blank `PackageNotFoundErrror`:
```
Fetching package metadata .............
Solving package specifications: 


PackageNotFoundError: Package not found: Conda could not find '
```

Has anyone seen this issue before? I'm pretty sure I'm following the instructions correctly, so I'm wondering where things are going wrong. 

If I run `conda create -n pytorch anaconda` to include all Anaconda packages, and then run `conda update --all`, I still get the same issue, so I don't think it has anything to do with dependencies.

In case the info is helpful, running `conda info` returns:
```
platform : osx-64
          conda version : 4.3.15
       conda is private : False
      conda-env version : 4.3.15
    conda-build version : 3.0.19
         python version : 3.5.3.final.0
       requests version : 2.14.2
       root environment : /Users/lucashu/anaconda  (writable)
    default environment : /Users/lucashu/anaconda/envs/pytorch
       envs directories : /Users/lucashu/anaconda/envs
                          /Users/lucashu/.conda/envs
          package cache : /Users/lucashu/anaconda/pkgs
                          /Users/lucashu/.conda/pkgs
           channel URLs : http://conda.anaconda.org/gurobi/osx-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/lucashu/.condarc
           offline mode : False
             user-agent : conda/4.3.15 requests/2.14.2 CPython/3.5.3 Darwin/17.6.0 OSX/10.13.5
                UID:GID : 501:20
```

Thanks in advance!

**Comment by WenjinTao** [comment]
Got the same error on win10. 
Running `conda install -c anaconda mkl` before installing pytorch solved my problem.

**Comment by lucashu1** [comment]
@WenjinTao after I run `conda install -c anaconda mkl` and then try running `conda install pytorch -c pytorch` again, I get:
```
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - pytorch
Use "conda info <package>" to see the dependencies for each package.
```
So unfortunately it doesn't seem like that fixes things for me.

**Comment by pjh5** [comment]
I can't repro this on conda 4.5.4, so upgrading might fix this.

Can you try specifying the python version when you create the conda environment? For example:
```conda create -n pytorch python=3``` and then trying to install?

Running ```conda create -n pytorch python=3``` will populate the conda environment with the barebones Python packages (including Python and setuptools) needed for a functional Python installation. 

Running ```conda create -n pytorch anaconda``` installs lots and lots of packages, which all have dependencies with one another that make can it hard to install another package (e.g. pytorch) with its own dependencies on top of that.

Running ```conda create -n pytorch``` without specifying "anaconda" nor "python=#" will install no packages, not even Python itself. It will install Python and other required python packages only when you install your first package in it. This means that if you create an env like this and do not install anything into it, then you will essentially still be in your root env, even after a ```source activate pytorch```.

**Comment by lucashu1** [comment]
@pjh5 

Updating conda to 4.5.4 and then running `conda create -n pytorch python=3` instead of `conda create -n pytorch anaconda` fixed it! I'm able to properly install pytorch now by running `conda install pytorch torchvision -c pytorch`. 

Thanks for the help.
