### ISSUE TITLE
Does Fx mode quantization support S8S8 perchannel quant

### ISSUE THREAD

**Issue by DeepTrial** [pytorch/pytorch#91225]
### 🐛 Describe the bug

I have tried the fx mode for graph quantization for resnet on X86 server. But I can only get a fused (conv+relu, conv+bn+relu) model without quantization, I think there may be some bugs for my quantization settings since fbgemm can generate quantizated model . Anyone help?
 

```python
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT).eval()

# quantization settings here for perchannel S8S8 quant
qconfig = torch.ao.quantization.qconfig.QConfig(
    activation=MinMaxObserver.with_args(dtype=torch.qint8,qscheme=torch.per_tensor_symmetric, reduce_range=True),
    weight=default_per_channel_weight_observer
)

qconfig_mapping = QConfigMapping().set_global(qconfig)

model_prepared = quantize_fx.prepare_fx(model, qconfig_mapping, torch.randn(1,3,224,224))
calibrate(model_prepared, calib_data_loader)
model_quantized = quantize_fx.convert_fx(model_prepared)
```

### Versions

my pytorch is installed by pip with version of 1.13.1+cu116 on Ubuntu 20.04

**Comment by ngimel** [comment]
Please use forums discuss.pytorch.org for questions

**Comment by Rickustc** [comment]
the same error,you may need to change your backend_confg(such as tensorRT) or write a new backend_config.
anyway when lower a reference reference quantized model to quantized model ,I got "RuntimeError: quantized::conv2d_relu (ONEDNN): data type of input should be QUint8." if there are any solution to fix it?

**Comment by xiangyun-hz** [comment]
> the same error,you may need to change your backend_confg(such as tensorRT) or write a new backend_config. anyway when lower a reference reference quantized model to quantized model ,I got "RuntimeError: quantized::conv2d_relu (ONEDNN): data type of input should be QUint8." if there are any solution to fix it?

@Rickustc I have also encountered the same problem. May I ask if you have solved it？thank!
