### ISSUE TITLE
[Caffe2 Bug] Error about test_is_hashable with Visual Studio 2017

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#9122]
## Issue description

Windows related bug.
Looks like it fails the compilation when doing hash(NotHashable) rather than fall back to false_type

```
    30>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(377): error C2338: The C++ Standard doesn't provide a hash for this type. (compiling source file ~\AppData\Local\Temp\pytorch\caffe2\utils\TypeTraits_test.cpp) [~\AppData\Local\Temp\pytorch\build\caffe2\utils\c10_utils_cpu_test.vcxproj]
         ~\AppData\Local\Temp\pytorch\caffe2/utils/TypeTraits.h(23): note: see reference to class template instantiation 'std::hash<T>' being compiled
                 with
                 [
                     T=`anonymous-namespace'::test_is_hashable::NotHashable
                 ] (compiling source file ~\AppData\Local\Temp\pytorch\caffe2\utils\TypeTraits_test.cpp)
```

```
       "~\AppData\Local\Temp\pytorch\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "~\AppData\Local\Temp\pytorch\build\caffe2\utils\c10_utils_cpu_test.vcxproj" (default target) (25) ->
       (ClCompile target) ->
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstddef(377): error C2338: The C++ Standard doesn't provide a hash for this type. (compiling source file ~\AppData\Local\Temp\pytorch\caffe2\utils\TypeTraits_test.cpp) [~\AppData\Local\Temp\pytorch\build\caffe2\utils\c10_utils_cpu_test.vcxproj]
         ~\AppData\Local\Temp\pytorch\caffe2\utils\TypeTraits_test.cpp(36): error C2338:  [~\AppData\Local\Temp\pytorch\build\caffe2\utils\c10_utils_cpu_test.vcxproj]
```

Code related:
https://github.com/pytorch/pytorch/blob/a34211bd790dd900311b3993104cc563bb11ef8e/caffe2/utils/TypeTraits.h#L23
https://github.com/pytorch/pytorch/blob/50392cc55444672a4b63b335455040a6ba53ae32/caffe2/utils/TypeTraits_test.cpp#L27-L31

## System Info

- PyTorch or Caffe2: Caffe2
- How you installed Caffe2(conda, pip, source): source
- Build command you used (if compiling from source): cmake
- OS: Win10
- VS version (if compiling from source): 2017.6
- CMake version: 3.11.4

**Comment by xkszltl** [comment]
I wonder if it's related to SFINAE in Visual Studio 2017.6.
Never tried 2017.7 since it's not supported by nvcc.

**Comment by peterjc123** [comment]
@xkszltl `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC` is the PATH of VS2015. You are using the wrong version.

**Comment by Semen52** [comment]
Hi @xkszltl,

Did you find the solution?

**Comment by fatalfeel** [comment]
namespace {
namespace test_is_hashable {
    static_assert(is_hashable<int>::value, "");
    static_assert(is_hashable<Hashable>::value, "");
    //static_assert(!is_hashable<NotHashable>::value, "");   //mark this line and build ok
}

NotHashable not include in vs2015

**Comment by peterjc123** [comment]
@fatalfeel Do it at your risk. And we don't provide support for VS 2015 anymore.
