### ISSUE TITLE
Two typos in `torch.distributed.distributed_c10d::broadcast_object_list`

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/pytorch#91236]
Words `processed groups` and `responsiblity` are misspelled in
https://github.com/pytorch/pytorch/blob/8992eec781e4479acce518263aa0e4493cf6808c/torch/distributed/distributed_c10d.py#L2179-L2182

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @svekars @carljparker

**Comment by malfet** [comment]
Thank you for the report and PR. Please sign CLA and the change will be merged.
