### ISSUE TITLE
torch.stack() is very slow compared numpy.stack()

### ISSUE THREAD

**Issue by sipkatom** [pytorch/pytorch#91242]
### 🐛 Bug

The torch.stack() is much slower compared to the numpy.stack(). See the snippet:

``` Python
import torch
import numpy as np
import time

with torch.no_grad():
    x_torch = [torch.rand(1,3,1000, 1200) for _ in range(10)]
    start = time.time()
    for i in range(100):
        torch.stack(x_torch)
    duration = time.time() - start
    print("Pytorch stack: ", duration)

    x_torch = [torch.rand(1,3,1000, 1200) for _ in range(10)]
    start = time.time()
    for i in range(100):
        torch.from_numpy(np.stack([x.numpy() for x in x_torch]))
    duration = time.time() - start
    print("NumPy stack: ", duration)

    x1 = torch.stack(x_torch)
    x2 = torch.from_numpy(np.stack([x.numpy() for x in x_torch]))
    is_equal = torch.equal(x1, x2)
    print("Is equal: ", is_equal)
```

**The output:**

```
Pytorch stack:  25.13597846031189
NumPy stack:  2.3550522327423096
Is equal:  True
```

**Expected output:**
Since numpy.stack() and torch.stack() produces the same result, the execution time should be similar.

### Versions

PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe
GPU 4: NVIDIA A100 80GB PCIe
GPU 5: NVIDIA A100 80GB PCIe
GPU 6: NVIDIA A100 80GB PCIe
GPU 7: NVIDIA A100 80GB PCIe

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.13.1
[pip3] torch-tb-profiler==0.4.0
[pip3] torchdata==0.5.1
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @ngimel

**Comment by jlehrer1** [comment]
Huh, this is pretty concerning. Thanks for bringing it up.

**Comment by drisspg** [comment]
On my machine: 
```
Pytorch stack:  1.5874087810516357
NumPy stack:  4.992428779602051
Is equal:  True
````

**Comment by sipkatom** [comment]
Is it perhaps some kind of thread overhead? By default, I get 64 threads by calling
```
torch.get_num_interop_threads()
torch.get_num_threads()
```
when I reduce the number of threads to around 10 I get:
```
NumPy stack:  2.2290523052215576
Pytorch stack:  4.266260385513306
```
but the torch is always approx. 2x slower

**Comment by Vasud-ha** [comment]
On my machine, I am unable to replicate it most of the time NumPy is slower, and sometimes it's similar to a torch. I tested on 1.13.0+cu116

Pytorch stack:  3.133920431137085
NumPy stack:  4.967101573944092

**Comment by ngimel** [comment]
Closing, as it doesn't repro

**Comment by guillaume-troadec** [comment]
Hey, we're still seeing this bug

```
Pytorch stack:  6.050511360168457
NumPy stack:  1.9705729484558105
Is equal:  True
```

I guess not quite the 10x difference as OP reported, but still a substantial 3x difference. Seems like it's something worthwhile looking into considering how common it is for ML projects to use `torch.stack()`
