### ISSUE TITLE
Use dynamo to detect incorrect op schemas automatically

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#91249]
A known issue that's bitten people in the past is when someone adds a new pytorch operator to the dispatcher that either mutates or aliases its inputs, but doesn't add proper alias annotations to the op's [schema](https://github.com/pytorch/pytorch/blob/15af4b1ceea3b689354ad664675b930486804c8e/test/test_schema_check.py#L331).

This will cause silent correctness issues across in the stack, both when using autograd, and when using functionalization (which runs by default when using `torch.compile()`).

We now have some [infra](https://github.com/pytorch/pytorch/blob/master/test/test_schema_check.py#L331) for automatically detecting improperly annotated schema using a `TorchDispatchMode`, which runs for a handful of ATen ops. However, it doesn't "automatically" run for custom user operators, and can cause models to silently break when using `torch.compile()`.

There's an open question of what the UX should look like though, because these checks are expensive to run. (Yet another) new debugging knob? Have it run automatically in the `aot_eager` backend?

One option would be to run this mode automatically under the `torch.compile(backend="aot_eager")`, likely inside of aot_autograd's tracing. The `aot_eager` backend is getting more debug checks added to it soon, so there's some precedent for using it as a catch-all for adding extra asserts.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by bdhirsh** [comment]
Actually - one annoying thing is that we need real tensors to detect the input mutations ([code](https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/schema_check_mode.py#L25)). So we can't just run this as an extra piece of infra that happens automatically during tracing. We'd need to do the (expensive) thing of cloning all real tensor inputs, and running that mode with the cloned inputs.

I could imagine that still being useful, but it's probably too expensive to run by default in `aot_eager`. It would also need to live in dynamo somewhere, because dynamo is what has access to the real tensor inputs.

**Comment by bdhirsh** [comment]
Another way to make this a lot cheaper to run would be to selectively only run it for ops outside of the ATen namespace. That's a bit risky - it assumes that our OSS CI is good enough that we're confident that all of our ATen schemas are annotated properly. But if custom ops make up a small percent of a model, then it would mean we run this check much less frequently.

**Comment by ezyang** [comment]
I think there is a big philosophical difference if you want to treat this as infrequent and expensive fuzzing, or as cheap usually turned on assert.  If we can assume that this is infrequent/expensive, this gives a lot of rope; if we can solve how to generate inputs, we can just run sweeps on all of the custom operators in fbcode looking for schema violations and then yell at people when there are violations. This is totally feasible to do in fbcode. There's no need to have to tie it to model runs, that just makes matters more complicated.

If we want something cheap and usually turned on, we need to figure out how to (1) run the real code (since that's the truth) and (2) cheaply detect if any of the inputs got mutated by the kernel. This... seems difficult. I don't know how to do it, personally.

**Comment by bdhirsh** [comment]
> I think there is a big philosophical difference if you want to treat this as infrequent and expensive fuzzing, or as cheap usually turned on assert.

Yeah, I agree that this type of check feels more like it should fall in the first category.

My only real counterpoint is that tying the check to model runs is less work:

(1) building infra to find all ops in fbcode, generate inputs that cover all cases for them and run the fuzzed inputs on some cadence is all pretty non-trivial. Although maybe "use Z3 to generate inputs that hit all branches of an op" is work that we already want to do at some point

(2) tying to model runs isn't too big of an issue if we already (want to?) advertise a slower, debug-checks-enabled way to run PT2. But you're totally right, these "debug checks" are philosophically very different from the existing checks we run.

**Comment by ezyang** [comment]
If running alongside the model is ruinously expensive (or worse, uses so much memory that you start OOMing), no one is going to run it with the models and so you're in the same spot as where you started. If the concern is generating inputs to cover cases for them, we're supposed to be getting this data from kineto logging to scuba or something, and even if we're not we can have a cheap debug mode that does record this information. Z3 to generate satisfying inputs also works great if you've got a meta function (which we are going to make people do, right?)

**Comment by williamwen42** [comment]
@zou3519 `opcheck` tests accomplish this now, right?
