### ISSUE TITLE
pytorch install error

### ISSUE THREAD

**Issue by wjx2** [pytorch/pytorch#9124]
my linux python version 2.7.6, 64bit. cuda8.0.pip version 10.0.1.
and I use pip install torch torchvision, it gets errors below:
Looking in indexes: http://pypi.v2ex.com/simple/
Collecting torch
  The repository located at pypi.v2ex.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.v2ex.com'.
  Could not find a version that satisfies the requirement torch (from versions: )
No matching distribution found for torch
The repository located at pypi.v2ex.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host pypi.v2ex.com'.

**Comment by soumith** [comment]
it looks like you are using a private PyPI server `pypi.v2ex.com`. On this server, the `torch` package does not exist. Maybe you are on a private firewall that restricts which pypi packages you can install?
