### ISSUE TITLE
torch.compile for calling func(**kwargs)

### ISSUE THREAD

**Issue by hoangmit** [pytorch/pytorch#91274]
### 🐛 Describe the bug

See code:
```python
def func(a, b):
    return a + b

def func1(**kwargs):
    return func(a=1, **kwargs)

c_f = torch.compile(func1, fullgraph=True)
c_f(b=torch.rand([2]))
```

At the moment, when you compile with `torch.compile(func, fullgraph=True)`, it throws `Unsupported: missing: BUILD_MAP_UNPACK_WITH_CALL`. When you compile in normal mode, it produces a graph break, because the python op_code for "func(... **kwargs)" is not supported.

I know that torchscript does not support **kwargs. However, I wonder if torch.compile(fullgraph) is going to support this?

### Versions

Pytorch version: pre-release version 2.0.0a0+fb

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
This is an oversight. We should support this and it shouldn't be hard to do. I can advise if someone wants to attempt it

**Comment by hoangmit** [comment]
Notes, we also need to support BUILD_TUPLE_UNPACK_WITH_CALL opcode.

The example is extracted from a library code for generic residual (i.e. skip connection) module that wrap some sub-module and use *args, and **kwargs to forward extra parameters to that sub-module.

**Comment by williamwen42** [comment]
This is a Python 3.8 specific problem. Verified that it is fixed.
