### ISSUE TITLE
[RFC] [Inductor] decompose aten.exponential_

### ISSUE THREAD

**Issue by min-jean-cho** [pytorch/pytorch#91276]
### 🚀 The feature, motivation and pitch

Currently aten.exponential_ fallbacks to `FallbackKernel: torch.ops.aten.exponential_.default`.

```python
import torch

def foo(x):
    return x.exponential_()
    
opt_foo = torch.compile(foo)
x = torch.randn(100)
print(opt_foo(x))
```

`aten.exponential_` is decomposable using `torch.rand` to something like:

```python
def exponential(rate=1):
    return -1 * (1/rate) * torch.log(1 - torch.rand(1))


x = []
for _ in range(1000):
    x.append(exponential(25))

print(torch.mean(torch.tensor(x))) # verify E[X] is around 1/rate = 0.04
print(torch.mean(torch.randn(1000).exponential_(25))) 1/rate # verify E[X] is around 1/rate = 0.04
```

### Correctness
```
X ~ Exponential(λ)
E[X] = 1/λ

PDF of exponential distribution: f(x) = λe^(-λx)
CDF of exponential distribution: F(x) = 1 - e^(-λx)

Let u := F(x)
u = 1 - e^(-λx) 
e^(-λx) = 1 - u
-λx = log(1 - u)
x = -(1/λ) log (1 - u) ≡ -scale * log (1 - u)

Then, U ~ Uniform(0,1)
X = -(1/λ) log (1 - U),     X ~ Exponential(λ)
note: u should not be 1, if u ~ Uniform(0,1) 1 must be exclusive, which is the case of torch.rand
```

### Additional context

This is the same method Numpy used in their legacy code, [here](https://github.com/numpy/numpy/blob/main/numpy/random/src/legacy/legacy-distributions.c#L227-L229)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by min-jean-cho** [comment]
I am aware of the discussion regarding Prim Op --vs-- inductor-unique decomposed Aten Op, https://github.com/pytorch/torchdynamo/issues/327#issuecomment-1354409046, I've put the [Inductor] tag in the title as of now.

**Comment by min-jean-cho** [comment]
Hi @jgong5, @ashokei, please help let me know if any comments this.

**Comment by ezyang** [comment]
Yeah this seems fine. We will need to revisit all of this if we want to line up the RNG behavior with eager mode, but absent that having a decomp for exponential is very reasonable

**Comment by min-jean-cho** [comment]
Thanks @ezyang,

> We will need to revisit all of this if we want to line up the RNG behavior with eager mode

I see there is a TODO comment `migrate everything to philox_rand_like()` for `rand`, `randn` lowering https://github.com/pytorch/pytorch/blob/master/torch/_inductor/lowering.py#L1086. So guessing this is already in plan

**Comment by ezyang** [comment]
Well, can it really be called a plan if no one is committed to implementing it right now lol

**Comment by ngimel** [comment]
Please see how eager is transforming uniformly distributed input to get exponential distribution https://github.com/pytorch/pytorch/blob/5030929c5d124e68e4d73b8933973f754d2d5d43/aten/src/ATen/core/TransformationHelper.h#L131-L142, some care is needed to make sure 0 values are not produced

**Comment by min-jean-cho** [comment]
Thanks @ngimel, that's a good point. 

Since `rand` samples from Uniform in range `[0, 1)`, we use `log(1 - U)` (rather than `log(U)` if Uniform were to be in range (0, 1] ). In `rand` case with `log(1 - U)`, to avoid `log(1) = 0` when `u` is 0 or close to 0, I think we can use the similar approach to set log to -epsilon/2.  I wonder why this is already not done here though

https://github.com/pytorch/pytorch/blob/5030929c5d124e68e4d73b8933973f754d2d5d43/aten/src/ATen/core/TransformationHelper.h#L141

**Comment by ngimel** [comment]
It's probably not done here because on cpu fast log approximation is not used, thus the workaround is not needed.

**Comment by min-jean-cho** [comment]
Thanks @ngimel, I wonder if regardless for cpu, 
with this decomposition, particularly the `torch.log(1 - torch.rand(1))`
and with the cpu implementation in `TransformationHelper.h`, particularly the `at::log(static_cast<T>(1.0) - val)`, 
we would also need to handle for the case that `we need log to be not 0` when `torch.rand` or `val` (range is in `[0, 1)`) samples very close to 1. 

Specifically, I was thinking of something like the following:
```python
u = 1 - 1e-17 # uniform sample is very close to 1 (extremely rare, probably not a practical issue)
rate = 1
exponential = -1/rate * torch.log(torch.tensor(1 - u)) # log(0)
```
