### ISSUE TITLE
[Bug]  Segmentation fault when importing fastText (with v0.4.0)

### ISSUE THREAD

**Issue by cympfh** [pytorch/pytorch#9129]
Related #8358 ?

I got segfault in importing torch (0.4.0) after importing `fastText`.
I found it is caused by `from torch._C import *` (https://github.com/pytorch/pytorch/blob/master/torch/__init__.py#L80).

```bash
$ python --version
Python 3.6.4 :: Anaconda, Inc.

$ conda --version
conda 4.4.10

$ cat test.py
import fastText
import torch._C

$ python test.py
zsh: segmentation fault  python test.py
```

## gdb

```
(gdb) run test.py
Starting program: /home/cympfh/.pyenv/versions/anaconda3-5.1.0/bin/python test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /home/cympfh/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
[New Thread 0x7fffecfa8700 (LWP 10028)]
[New Thread 0x7fffec7a7700 (LWP 10029)]
[New Thread 0x7fffe9fa6700 (LWP 10030)]
[New Thread 0x7fffe77a5700 (LWP 10031)]
[New Thread 0x7fffe4fa4700 (LWP 10032)]
[New Thread 0x7fffe27a3700 (LWP 10033)]
[New Thread 0x7fffdffa2700 (LWP 10034)]
[New Thread 0x7fffdd7a1700 (LWP 10035)]
[New Thread 0x7fffdafa0700 (LWP 10036)]
[New Thread 0x7fffd879f700 (LWP 10037)]
[New Thread 0x7fffd5f9e700 (LWP 10038)]
[New Thread 0x7fffd379d700 (LWP 10039)]
[New Thread 0x7fffd0f9c700 (LWP 10040)]
[New Thread 0x7fffce79b700 (LWP 10041)]
[New Thread 0x7fffcbf9a700 (LWP 10042)]
[Thread 0x7fffd0f9c700 (LWP 10040) exited]
[Thread 0x7fffcbf9a700 (LWP 10042) exited]
[Thread 0x7fffe9fa6700 (LWP 10030) exited]
[Thread 0x7fffce79b700 (LWP 10041) exited]
[Thread 0x7fffdafa0700 (LWP 10036) exited]
[Thread 0x7fffd379d700 (LWP 10039) exited]
[Thread 0x7fffdffa2700 (LWP 10034) exited]
[Thread 0x7fffd5f9e700 (LWP 10038) exited]
[Thread 0x7fffe4fa4700 (LWP 10032) exited]
[Thread 0x7fffdd7a1700 (LWP 10035) exited]
[Thread 0x7fffecfa8700 (LWP 10028) exited]
[Thread 0x7fffd879f700 (LWP 10037) exited]
[Thread 0x7fffe27a3700 (LWP 10033) exited]
[Thread 0x7fffec7a7700 (LWP 10029) exited]
[Thread 0x7fffe77a5700 (LWP 10031) exited]
Detaching after fork from child process 10045.

Program received signal SIGSEGV, Segmentation fault.
pybind11::detail::make_new_python_type (rec=...) at /opt/conda/conda-bld/pytorch_1524586445097/work/third_party/pybind11/include/pybind11/detail/class.h:576
576     /opt/conda/conda-bld/pytorch_1524586445097/work/third_party/pybind11/include/pybind11/detail/class.h: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64

```

**Comment by zou3519** [comment]
@cympfh how did you install fasttext?

It would greatly help debugging if you could reproduce this inside a docker image, but I will also try to repro it.

**Comment by weiyangfb** [comment]
I can repro #8358, but not this one. 

```
>>> import fastText
>>> import torch._C
>>> help(fastText.FastText)
Help on module fastText.FastText in fastText:

NAME
    fastText.FastText

DESCRIPTION
    # Copyright (c) 2017-present, Facebook, Inc.
    # All rights reserved.
    #
    # This source code is licensed under the BSD-style license found in the
    # LICENSE file in the root directory of this source tree. An additional grant
    # of patent rights can be found in the PATENTS file in the same directory.

FUNCTIONS
```

My env:
```
python -V
Python 3.6.6 :: Anaconda, Inc.

conda -V
conda 4.5.4
```

fastText: https://github.com/facebookresearch/fastText

**Comment by xtannier** [comment]
Hi,
I have the same exact problem. 
On my laptop, everything is fine. 
On my cluster login node or computing node, the same segfault as described above.

In both cases, 
Python 3.6.6 :: Anaconda, Inc.
conda 4.5.4

On my cluster:
[GCC 7.2.0] on linux

On my laptop:
[GCC 4.8.2] on linux

**Comment by zou3519** [comment]
Can any of you reproduce this in a docker image? That would be helpful for debugging.

A stack trace of the segfault would be great as well; if you do something like
```
gdb python
> run crash.py
```
and then type "backtrace" when it crashes.

**Comment by xtannier** [comment]
Here are two traces.
The first one for
```
import fasttext
import torch
```
[test-import-fasttest-import-torch.txt](https://github.com/pytorch/pytorch/files/2185753/test-import-fasttest-import-torch.txt)
Note that this one looks for files in the directory `/opt/conda/conda-bld/pytorch_1524586445097/work/third_party/pybind11/include/pybind11/detail/`, that do not exist.

(It may be important to notice that I created my local conda env with `conda env create -p $HOME/conda/pytorch`, because on the cluster I don't have sufficient permissions to run conda env create without a local directory; while on my laptop -- where I don't have any segfault problem -- I created it without -p)



The second trace is for the python script
```
import torch
import fasttext
```
[test-import-torch-import-fasttext.txt](https://github.com/pytorch/pytorch/files/2185754/test-import-torch-import-fasttext.txt)

Here it looks for the file $HOME/conda/pytorch/include/python3.6m/pybind11/detail/class.h, which exists, but it still segfaults...

As for the docker image, I've never done that, and I'm not even sure that I can do it on the cluster, with the few permissions I have.

**Comment by weiyangfb** [comment]
@xtannier Thanks for the gdb trace! Could you try creating a new conda env without `-p`, and then install both of pytorch and fastText from source?

**Comment by xtannier** [comment]
Interestingly pytorch `python setup install` from sources failed (I followed the instructions here https://github.com/pytorch/pytorch#from-source) while it works on my laptop. Could it be related?
Here is the log
[out-install-pytorch.txt](https://github.com/pytorch/pytorch/files/2187844/out-install-pytorch.txt)

Anyway I'll continue to investigate why it failed to compiled.

**Comment by xtannier** [comment]
No, I built from the github repo (`git clone --recursive https://github.com/pytorch/pytorch`).
I'm pretty sure I followed strictly the instructions from https://github.com/pytorch/pytorch#from-source.

I suspect a problem with the cluster installation, but I don't really know what to do at this point. 
pytorch installed from conda works like a charm without fasttext

**Comment by weiyangfb** [comment]
I see, I think you are doing it correctly! And I just tried using `conda install pytorch`, it works fine too. Also, not 100% sure but this issue #358 might be related

**Comment by xtannier** [comment]
Do you mean #8358 (instead on #358) ?

**Comment by weiyangfb** [comment]
I meant this one: https://github.com/onnx/onnx/issues/358

**Comment by weiyangfb** [comment]
Hi @xtannier, any update? Were you able to install fastText from source?

**Comment by weiyangfb** [comment]
@cympfh would you like to try installing pytorch (0.4.0) and fastText from source and see if it works?

**Comment by xtannier** [comment]
Hi, yes, I got fastText installed with `pip install .` from git clone, but with a warning on wheel and pybind11, which could be related again to https://github.com/onnx/onnx/issues/358
[pip_install_fasttext.txt](https://github.com/pytorch/pytorch/files/2195702/pip_install_fasttext.txt)

**Comment by weiyangfb** [comment]
@xtannier Thanks for the updates! Yeah, I feel like the installation log is bit strange.. Mine was the following:

```
>> pip install .
Processing /private/home/weiyang/fastText
Requirement already satisfied: pybind11>=2.2 in /private/home/weiyang/.conda/envs/pytorch-master/lib/python3.6/site-packages (from fasttext==0.8.22) (2.2.3)
Requirement already satisfied: setuptools>=0.7.0 in /private/home/weiyang/.conda/envs/pytorch-master/lib/python3.6/site-packages (from fasttext==0.8.22) (39.2.0)
Requirement already satisfied: numpy in /private/home/weiyang/.conda/envs/pytorch-master/lib/python3.6/site-packages (from fasttext==0.8.22) (1.14.5)
Building wheels for collected packages: fasttext
  Running setup.py bdist_wheel for fasttext ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-m7l70u5t/wheels/f0/02/94/662fd2cafa933c0b360eec3622821c5a90abe388c6b3ef33e3
Successfully built fasttext
Installing collected packages: fasttext
Successfully installed fasttext-0.8.22
```

I remember you had python3.6 at your previous conda env, but this time it became python2.7? Can I see your `conda list`?

**Comment by weiyangfb** [comment]
@xtannier I am looking into this. In the meanwhile, would you like to provide your system info following the issue template? You can probably get them from running `python collect_env.py`. Thanks!

**Comment by xtannier** [comment]
Result of `python collect_env.py`

```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: SUSE Linux Enterprise Server 12 SP2
GCC version: (SUSE Linux) 4.8.5
CMake version: version 3.5.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Quadro K5200
GPU 1: Quadro K5200

Nvidia driver version: 384.69
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.13.3)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch
```

**Comment by weiyangfb** [comment]
@xtannier Thanks for the system info! I have a quick question. So you successfully installed pytorch 0.4.0? Is the issue still persistent when importing both of fastText and torch?

**Comment by weiyangfb** [comment]
@xtannier also, to build from source, I will do the following:
```
- pip uninstall torch
- pip uninstall torch
- python setup.py clean
- python setup.py install
```

**Comment by SsnL** [comment]
@xtannier Hi, I've looked into this. Basically if two libs both using `pybind11` are compiled using incompatible compilers, this will happen (see https://github.com/pybind/pybind11/issues/1262). By "incompatible" I mean e.g., `gcc` and `clang`, `gcc < 4.9.2` and `gcc >= 4.9.2`. To avoid such issue as much as possible, we compile our release binaries with `gcc 4.9.2`. So if you are compiling `fasttext` with a `gcc < 4.9.2` it will segfault. Can you look into the gcc version used?

**Comment by xtannier** [comment]
Good catch!
```
(testsegfault9) tannier@mesu4:~> gcc --version
gcc (SUSE Linux) 4.8.5
```

See next comment for the happy conclusion!

**Comment by xtannier** [comment]
For the record, the problem was:
 - in a conda environment, I installed pytorch with `conda install`(as described on pytorch web site) and fastText with `pip install .` from their git clone.
 - that resulted in a segfault when doing `import fastText` and `import torch` 

Reason:
 - pytorch is compiled with gcc 4.9.2
 - conda's default gcc is 4.8.5

Fix:
 - install gcc-4.9 in conda (e.g. `conda install -c serge-sans-paille gcc_49`)
 - install pytorch with `conda install` (in my case, `conda install pytorch torchvision cuda90 -c pytorch`)
 - install fastText with gcc-4.9 compiler: `CC=gcc-4.9 pip install .` in the fastText git clone

That's it! Thanks a lot @weiyangfb and @SsnL for your help!

**Comment by SsnL** [comment]
Thanks for writing the procedure out!
