### ISSUE TITLE
[Torch 2.0] Fake Tensor Fails for codegen model

### ISSUE THREAD

**Issue by PoodleWang** [pytorch/pytorch#91306]
### 🐛 Describe the bug

```
import torch
from transformers import AutoModelForCausalLM,AutoTokenizer
import torch._dynamo as dynamo
from datetime import datetime
from torch._dynamo.optimizations import backends
tokenizer = AutoTokenizer.from_pretrained('Salesforce/codegen-6B-mono')
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-6B-mono").to(device="cuda:0").eval()
model = dynamo.optimize("inductor")(model) # This is the only line of code that we changed
inputs = tokenizer(
    "func FormatInt(i int64, base int) string{      ",  # Nvidia example prompt
    add_special_tokens=True,
    return_tensors="pt",
).to(device="cuda:0")

p0 = datetime.utcnow()
output = model(**inputs)
# output = model.generate(inputs, max_new_tokens=256, max_time=20.0, do_sample=True,
#                                    temperature=0.8, top_p=0.95, use_cache=True,
#                                    pad_token_id=tokenizer.eos_token_id, num_return_sequences=1)
p1 = datetime.utcnow()
print(f"Time difference is {(p1 - p0).total_seconds()} seconds")
print (output)
```

### Error logs

/home/tiger/.local/lib/python3.7/site-packages/torch/_dynamo/eval_frame.py:373: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled.Consider setting `torch.set_float32_matmul_precision('high')`
  "TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled."
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_dynamo/utils.py", line 1054, in run_node
    return node.target(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_subclasses/fake_tensor.py", line 915, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_prims_common/wrappers.py", line 209, in _fn
    result = fn(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_prims_common/wrappers.py", line 119, in _fn
    result = fn(**bound.arguments)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_refs/__init__.py", line 1782, in where
    lambda: f"expected predicate to be bool, got {pred.dtype}",
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_prims_common/__init__.py", line 1552, in check
    raise exc_type(s())
RuntimeError: expected predicate to be bool, got torch.uint8

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_dynamo/utils.py", line 1014, in get_fake_value
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_dynamo/utils.py", line 704, in wrap_fake_exception
    return fn()
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_dynamo/utils.py", line 1014, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/tiger/.local/lib/python3.7/site-packages/torch/_dynamo/utils.py", line 1065, in run_node
    ) from e
RuntimeError: Failed running call_function <built-in method where of type object at 0x7f89b9347040>(*(FakeTensor(FakeTensor(..., device='meta', size=(1, 1, 14, 14), dtype=torch.uint8), cuda:0), FakeTensor(FakeTensor(..., device='meta', size=(1, 16, 14, 14), grad_fn=<DivBackward0>), cuda:0), FakeTensor(FakeTensor(..., device='meta', size=()), cuda:0)), **{}):
expected predicate to be bool, got torch.uint8
(scroll up for backtrace)

### Versions

my environment:
torch                     2.0.0.dev20221222+cu116
torch-tensorrt        1.3.0
torchaudio                2.0.0.dev20221221+cu116
torchtriton               2.0.0+0d7e753227
torchvision               0.15.0.dev20221221+cu116

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by bdhirsh** [comment]
It looks like this model calls `torch.where` with a uint8 conditional tensor, which is deprecated in eager mode([code](https://github.com/pytorch/pytorch/blob/014946767747cec49931f7d75b875d72e0de829d/aten/src/ATen/native/TensorCompare.cpp#L493)), but doesn't currently work in our primtorch decomps ([code](https://github.com/pytorch/pytorch/blob/014946767747cec49931f7d75b875d72e0de829d/torch/_refs/__init__.py#L1781)).

We should just allow it in the primtorch decomp, and emit the same deprecation warning.

**Comment by ngimel** [comment]
I'm not sure we should allow it in primtorch, or use this as a forcing function to finally be able to deprecate it.

**Comment by bdhirsh** [comment]
fair point :)

**Comment by ezyang** [comment]
@PoodleWang you should modify your code to use a bool tensor instead of a byte tensor, do you need guidance on how to do so

**Comment by PoodleWang** [comment]
> @PoodleWang you should modify your code to use a bool tensor instead of a byte tensor, do you need guidance on how to do so

If you have a guide. Please send me.

**Comment by ngimel** [comment]
`dtype` here https://github.com/huggingface/transformers/blame/52dd2b61bff8af5b6409fdd5ec92a9b3114f3636/src/transformers/models/codegen/modeling_codegen.py#L101 has to be changed to `torch.bool`
