### ISSUE TITLE
AOT Autograd should allow backend compilers to see input mutations

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#91310]
Today, AOT Autograd has special handling for input mutations. Given a user code / captured graph like this:
```
def user_f(x):
    x.mul_(2)
    out = x * 3
    return out
```

AOT Autograd will split it into (1) a purely functional graph for the compiler, and (2) an epilogue that runs after, and applies any global side effects (aka input mutations):

```
// gets sent to a compiler
def compiled_functional_graph(x):
    x_updated = x.mul(2)
    out = x_updated * 3
    return x_updated_out

// wrapper that aot autograd calls
def wrapper_run_compiled_graph_and_epilogue(x):
    x_updated, out = compiled_functional_graph(x)
    x.copy_(x_updated)
    return out
```

This technically leaves some performance on the table: an out-of-place mul() + a copy_() takes twice as many operations as an inplace mul.

Once we start running functionalization all the time in AOT Autograd, and once we capture the optimizer step in a graph that gets sent to AOT Autograd, then this will likely have a larger impact on the performance of optimizer graphs: An optimizer graph consists of a large number of mutations to graph inputs (the parameters), and all of those mutations will now take 2 operations instead of one, and require extra memory - their out-of-place equivalent, and a copy_() call.

The most general way to fix this would be to give backend compilers the ability to indicate to AOT Autograd that they're ok with seeing input mutations in their graph and handling them.

One complication is that AOT Autograd also runs min-cut-partitioning and DCE, which either won't work, or will require even more special handling if there are input mutations in the graph. A simpler version of this github issue would be to only allow input mutations in the graph when we are not generating a backward graph and running partitioning, since graphs capturing the optimizer step should (mostly) fall into this bucket.

cc @ezyang @msaroufim @wconstab @anijain2305 @zou3519 @Chillee @samdow @kshitij12345 @janeyx99 @soumith @ngimel

**Comment by ezyang** [comment]
The simplest strategy is probably to run the reinplacer (@bdhirsh, it's back from the dead!) after partitioning. But remember we also have to play games with making sure the autograd graph is still valuable even if the compiler doesn't know how to handle it. For the optimizer case this is simple because the mutated inputs never require grad and so we can move stuff in/out of the custom autograd function with impunity.

**Comment by williamwen42** [comment]
@mlazos any comments on this (due to your optimizer work)?

**Comment by Chillee** [comment]
I think this may have already been solved. cc: @bdhirsh ?

**Comment by bdhirsh** [comment]
Yep this has been solved (pass this config to AOTAutograd: https://github.com/pytorch/pytorch/blob/main/torch/_inductor/compile_fx.py#L1174)
