### ISSUE TITLE
[Bootcamp] Have all Dr. CI failure links point to HUD instead of GH Actions

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#91320]
## What
When a PR has fails any CI checks, we have a github bot called Dr. CI which leaves a comment at the top of the PR calling out the failures. Today, those failures link to the Github jobs page for the failing checks.

However, PyTorch has build our own HUD that offers better debugging information to devs.  This will allow devs to root cause their failures faster.

Goal: Repoint those links to our custom HUD

This will require two changes:
1. Change the [PR summary page](https://hud.pytorch.org/pr/87488) on HUD to add anchors (html `id`s) to the list of jobs under each workflow
2. Change Dr. CI's message to point to those anchor links

Bonus points:
- Add the failure line that HUD shows under the failed jobs to Dr. CI as well
- Show both the old and new links in an aesthetic way (aesthetic meaning the list doesn't look too noisy)

## Context & References:
For getting started with development read these READMEs:
- https://github.com/pytorch/test-infra/blob/main/README.md
- https://github.com/pytorch/test-infra/blob/main/torchci/README.md

React code for generating the workflow links: https://github.com/pytorch/test-infra/blob/55f446be3d8712433a92ad47605302a2b79bae20/torchci/components/CommitStatus.tsx#L101

Dr CI bot entrypoint (triggered by Github webhooks): https://github.com/pytorch/test-infra/blob/main/torchci/lib/bot/drciBot.ts

Example Dr. CI output with CI failures: 
- https://github.com/pytorch/pytorch/pull/87488#issuecomment-1287282815
Those links should be pointing to the relevant id under https://hud.pytorch.org/pr/87488 instead

**Comment by clee2000** [comment]
additional things to consider: including both links, adding the failure line in dr ci

**Comment by ZainRizvi** [comment]
Fyi, it's not necessary to link to the specific anchor link. Just a link to the commit's CI page is okay

**Comment by clee2000** [comment]
fixed by https://github.com/pytorch/test-infra/pull/3799
