### ISSUE TITLE
Remove deprecated numpy dtype alias to be compatible with numpy1.24

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#91329]
### 🐛 Describe the bug

In numpy 1.24, np.object, np.bool, np.float, np.complex, np.str, and np.int no longer exists. However some of these are still used in PyTorch (though mainly in unittests), for example [these](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/pytorch/pytorch%24+np.float%5B%5E136_%5D+rev:refs/tags/v1.13.1&patternType=regexp&sm=1).

(numpy release notes: https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations )

### Versions

Using torch 1.13.1 but these usage exist in current HEAD.

cc @ezyang @malfet @rgommers @xuzhao9 @gramster @mruberry

**Comment by drisspg** [comment]
Thanks for bringing this up, if you wanted to submit a PR fixing this I would be happy to review.

**Comment by ShisuiUzumaki** [comment]
Is this issue still open @drisspg ?

**Comment by drisspg** [comment]
Yes

**Comment by ShisuiUzumaki** [comment]
> Yes

I am interested. Can you guide me?

**Comment by ppwwyyxx** [comment]
@ShisuiUzumaki you can search all use of `np.float` and change it to `float`. Same for `np.bool`, `np.int`, ... etc.

**Comment by ShisuiUzumaki** [comment]
> @ShisuiUzumaki you can search all use of `np.float` and change it to `float`. Same for `np.bool`, `np.int`, ... etc.

@ppwwyyxx  I will have to perform search across all of pytorch repo, and not just the tests, right? And since you mentioned replacing `np.float` with `float` does that mean `numpy` also uses built-in python types now, just taking a guess here
