### ISSUE TITLE
Use c10 namespace in public headers for classes like DeviceType (and Device ?)

### ISSUE THREAD

**Issue by bsergean** [pytorch/pytorch#91338]
### 🚀 The feature, motivation and pitch

We have an existing DeviceType class all over the place in our code base, and it conflicts with the one that is used in torch. Thankfully the pytorch DeciceType enum class is under the c10 namespace.

```
In file included from /xxx/build/_deps/torch-src/../../aten/src/ATen/ops/view.h:5:
/xxx/_deps/torch-src/aten/src/ATen/Context.h:265:14: error: reference to 'DeviceType' is ambiguous
    if (p == DeviceType::HIP) {
             ^
/xxx/include/Common_types.h:178:8: note: candidate found by name lookup is 'DeviceType'
struct DeviceType {
       ^
/xxx/build/_deps/torch-src/c10/../c10/core/DeviceType.h:32:12: note: candidate found by name lookup is 'c10::DeviceType'
enum class DeviceType : int8_t {
```

cc @jbschlosser @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by albanD** [comment]
Sure, let's do that.

**Comment by anthonyalayo** [comment]
@albanD this PR had the support needed, but it didn't get merged due to some sort of lint line:
https://github.com/pytorch/pytorch/pull/91342

Can you tell me exactly what should be there? I can copy/paste it into the PR.

**Comment by albanD** [comment]
Hey!
The linter should be a 5 lines copy-paste + change `std::once_flag` with `c10::DeviceType` so should be pretty simple to add.
Note that you can also add a rule there that will auto-add this `c10::` namespace automatically. So once the linter rule is added, you can `lintrunner -a` to fix everything and send that as a PR!
