### ISSUE TITLE
RNN/LSTM are not being correctly traced with JIT/ONNX (with a fix)

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#91351]
### 🐛 Describe the bug

Currently, RNN/LSTM networks are not being correctly JIT-traced because of a few int() casts that break the trace. Here is a patch that fixes that (line numbers may differ, I did that against NVIDIA 'upstream' fork): 
```
diff --git a/torch/nn/modules/rnn.py b/torch/nn/modules/rnn.py
index f94728653b..2320fc1f15 100644
@@ -731,7 +731,6 @@ class LSTM(RNNBase):
         if isinstance(orig_input, PackedSequence):
             input, batch_sizes, sorted_indices, unsorted_indices = input
             max_batch_size = batch_sizes[0]
-            max_batch_size = int(max_batch_size)
         else:
             batch_sizes = None
             assert (input.dim() in (2, 3)), f"LSTM: Expected input to be 2-D or 3-D but received {input.dim()}-D tensor"
@@ -739,7 +738,7 @@ class LSTM(RNNBase):
             batch_dim = 0 if self.batch_first else 1
             if not is_batched:
                 input = input.unsqueeze(batch_dim)
-            max_batch_size = input.size(0) if self.batch_first else input.size(1)
+            max_batch_size = torch.as_tensor(input.size(0) if self.batch_first else input.size(1))
             sorted_indices = None  
             unsorted_indices = None
 
@@ -922,7 +921,6 @@ class GRU(RNNBase):
         if isinstance(orig_input, PackedSequence):
             input, batch_sizes, sorted_indices, unsorted_indices = input
             max_batch_size = batch_sizes[0]
-            max_batch_size = int(max_batch_size)
         else:
             batch_sizes = None
             assert (input.dim() in (2, 3)), f"GRU: Expected input to be 2-D or 3-D but received {input.dim()}-D tensor"
@@ -939,7 +937,7 @@ class GRU(RNNBase):
                 if hx is not None and hx.dim() != 3:
                     raise RuntimeError(
                         f"For batched 3-D input, hx should also be 3-D but got {hx.dim()}-D tensor")
-            max_batch_size = input.size(0) if self.batch_first else input.size(1)
+            max_batch_size = torch.as_tensor(input.size(0) if self.batch_first else input.size(1))
             sorted_indices = None  
             unsorted_indices = None
```

### Versions

Collecting environment information...
PyTorch version: 1.14.0a0+410ce96
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1  
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.23.2.dev20221221+cuda11.8.torch1.14.0a0
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.8.6
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.14.0a0+410ce96
[pip3] torch-tensorrt==1.3.0a0
[pip3] torchaudio==0.14.0
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.15.0a0
[conda] Could not collect

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by vadimkantorov** [comment]
I think, some problem happened with markdown code formatting...

**Comment by borisfom** [comment]
Thanks @vadimkantorov !

**Comment by borisfom** [comment]
Oh, also this change is in order: 
--- a/torch/nn/utils/rnn.py
+++ b/torch/nn/utils/rnn.py
@@ -243,13 +243,14 @@ def pack_padded_sequence(
     Returns:
         a :class:`PackedSequence` object
     """
-    if torch._C._get_tracing_state() and not isinstance(lengths, torch.Tensor):
-        warnings.warn('pack_padded_sequence has been called with a Python list of '
-                      'sequence lengths. The tracer cannot track the data flow of Python '
-                      'values, and it will treat them as constants, likely rendering '
-                      'the trace incorrect for any other combination of lengths.',
-                      stacklevel=2)
-    lengths = torch.as_tensor(lengths, dtype=torch.int64)
+    if not isinstance(lengths, torch.Tensor):
+        if torch._C._get_tracing_state():
+            warnings.warn('pack_padded_sequence has been called with a Python list of '
+                          'sequence lengths. The tracer cannot track the data flow of Python '
+                          'values, and it will treat them as constants, likely rendering '
+                          'the trace incorrect for any other combination of lengths.',
+                          stacklevel=2)
+        lengths = torch.as_tensor(lengths, dtype=torch.int64)
     if enforce_sorted:
         sorted_indices = None
     else:

**Comment by titaiwangms** [comment]
Hi @borisfom,
Thank you very much for the contribution.
Could you open a PR with this fix and a test case?
