### ISSUE TITLE
nop_partitioner for AOTAutograd

### ISSUE THREAD

**Issue by k-badz** [pytorch/pytorch#91356]
### 🚀 The feature, motivation and pitch

Hello everyone, I've got an idea I'd like to share with you. It is about graph partitioners in AOTAutograd.

Currently, there are two partitioners defined (default_partition and min_cut_rematerialization_partition) which always result in two separate graphs, one for FWD and second for BWD. I would like to have an option to get whole joint graph containing both FWD and BWD to get most of optimization opportunities for my torch.compile backend.

I tried to implement such "nop_partitioner" myself that would just pass the joint graph back, as well as tried changing default_partition to gather more outputs into single graph, but it always resulted in some kind of crash. I assume that in current AOTAutograd code there might be hidden assumptions on this mechanism that do not allow this kind of operation (or my programming skills just suck, that's also possible).

Is it possible for you to create such "nop_partitioner" as part of PT2.0 release so it could be used by everyone?

Thanks,
--mb

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by ngimel** [comment]
cc @Chillee

**Comment by ezyang** [comment]
This is a reasonable thing to ask for but not so easy, as we would need to design an entirely new calling convention for such backends. We can't just pass a joint graph to a backend and expect to be able to deal with an opaque compiled blob for both forwards backwards returned to us, we *must* be able to split it into the forward/backward stage to actually integrate it into the rest of PT computation. There's no way for us to run just the joint graph.

If you are able to factor your backend's logic into a separate partitioner, you could just plug your custom partitioner in and then pass it on to the backend after it did a good split.
