### ISSUE TITLE
[JIT] Difference in output between ONNX model created via torch.onnx.export and original PyTorch model

### ISSUE THREAD

**Issue by veelken** [pytorch/pytorch#91357]
### 🐛 Describe the bug

Hi,

I have trained a PyTorch model that uses the equivalent of the TensorFlow function "unsorted_segment_sum".
The PyTorch implementation of this function is based on the thread
  https://discuss.pytorch.org/t/pytorch-equivalent-to-tf-unsorted-segment-sum/25275

The conversion of the PyTorch model via torch.onnx.export proceeds without errors, but the output of the ONNX model does not agree with the output of the original PyTorch model.

I have produced a minimal example that demonstrates the issue.
To run the example, please do:
```
  git clone https://github.com/veelken/UnsortedSegmentExample
  cd UnsortedSegmentExample
  python3 test_UnsortedSegmentExample.py --mode="sum" -outputFile="test_UnsortedSegmentExample.onnx"
```
The example produces no warnings or errors.
The issue is solely that the output of the ONNX model does not agree with the output of the original PyTorch model.

Thank you very much for your help,

Christian

### Versions

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==1.12.1
[pip3] torch-cluster==1.6.0+pt112cu113
[pip3] torch-geometric==2.2.0
[pip3] torch-scatter==2.1.0+pt112cu113
[pip3] torch-sparse==0.6.15+pt112cu113
[pip3] torch-spline-conv==1.2.1+pt112cu113
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch                   1.12.1          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-cluster             1.6.0+pt112cu113          pypi_0    pypi
[conda] torch-geometric           2.2.0                    pypi_0    pypi
[conda] torch-scatter             2.1.0+pt112cu113          pypi_0    pypi
[conda] torch-sparse              0.6.15+pt112cu113          pypi_0    pypi
[conda] torch-spline-conv         1.2.1+pt112cu113          pypi_0    pypi
[conda] torchtext                 0.13.1                     py37    pytorch
[conda] torchvision               0.13.1               py37_cu113    pytorch

**Comment by BowenBao** [comment]
We are developing a validation tool `find_mismatch` to help investigate this kind of issues. Would you mind trying https://github.com/pytorch/pytorch/blob/ef495b7d6453da445861a105b3cc6f24d840da3a/torch/onnx/verification.py#L1723 via pytorch master/nightly build? The doc can be found in this PR https://github.com/pytorch/pytorch/pull/90728/files#diff-90f9695ec7b61901958ca716ce786ad00bac581f6be40f9357945fc678e63990.

**Comment by veelken** [comment]
Hi, 

I have updated my PyTorch installation to the version 2.0.0.dev20230110+cu116 and extended my example code such that the function find_mismatch gets called via:
  find_mismatch(torch_model, (data)) ,
similarly to how I call the torch.onnx.export function.

When I run this modified example code, the code aborts with an assertion in line 1639 when executing the find_mismatch function:
Traceback (most recent call last):
  File "/home/veelken/LorentzNet_tau_woWeights/LorentzNet-release/test_UnsortedSegmentExample.py", line 142, in <module>
    find_mismatch(torch_model,
  File "/opt/conda/lib/python3.9/site-packages/torch/onnx/verification.py", line 1780, in find_mismatch
    graph_info.find_mismatch(options)
  File "/opt/conda/lib/python3.9/site-packages/torch/onnx/verification.py", line 1639, in find_mismatch
    assert len(self.input_args) + len(self.params_dict) == len(
AssertionError: Number of graph inputs(1) does not match the provided tensor arguments(18 + 0).

I added some debug output before this line and I see that list(self.graph.inputs()) is of type
    [data defined in (%data : Float(18, 4, strides=[4, 1], requires_grad=0, device=cpu) = prim::Param())]
It seems to me that there is a problem with creating this list: instead of containing 18 entries with 4 floating point numbers per entry, the list seems to contain a single object that holds all the numbers, hence the mismatch when comparing the length of objects in line 1639.

**Comment by BowenBao** [comment]
Hi @veelken, thanks for the detailed response.

Could you try `find_mismatch(torch_model, (data, ))`? The `input_args` argument of `find_mismatch` needs to be a tuple of tensors.

**Comment by veelken** [comment]
Hi @BowenBao , thank you very much for your help. After replacing ```(data)``` by ```(data, )```, the ```find_mismatch```function works without problems and produces the output attached below [*].

Do you see where the problem is in the ```unsorted_segment_sum`` function ?

The model is defined in: https://github.com/veelken/UnsortedSegmentExample/blob/main/UnsortedSegmentExample.py

Thank you very much again for your help!

- - - - - - - -

[*]

```
===================== Mismatch info for graph partition : ======================
================================ Mismatch error ================================
Tensor-likes are not close!

Mismatched elements: 24 / 24 (100.0%)
Greatest absolute difference: 11.353199481964111 at index (0, 0) (up to 1e-07 allowed)
Greatest relative difference: 0.8846849397345333 at index (0, 3) (up to 0.001 allowed)
==================================== Tree: =====================================
5 X   __2 ✓
id:  |  id: 0
     |
     |__3 X    __1 ✓
        id: 1 |  id: 10
              |
              |__2 X     __1 ✓
                 id: 11 |  id: 110
                        |
                        |__1 X (aten::scatter_add)
                           id: 111
=========================== Mismatch leaf subgraphs: ===========================
['111']
============================= Mismatch node kinds: =============================
{'aten::scatter_add': 1}
```

**Comment by veelken** [comment]
I confirm that the problem with exporting the model to ONNX format is indeed due to the ```scatter_add``` function.

I managed to compute the same result without using the ```scatter_add``` function in the example model and in this case the ONNX export works. You can find the example model that works here: https://github.com/veelken/UnsortedSegmentExample/blob/main/UnsortedSegmentExample_fixed.py

I will now see if I can export my full PyTorch model to ONNX format also, if I apply the same changes to my full PyTorch model.

I think it will still be good to understand why the ONNX export fails if the model uses the ```scatter_add``` function.

**Comment by BowenBao** [comment]
@veelken , glad you found the root cause! It is a known issue #32960 that `scatter_add` may be unstable for opset version < 16. Would you mind give a try exporting with `opset_version=16`?

**Comment by veelken** [comment]
Hi @BowenBao, I confirm that the ONNX export of the original example (the one with  the ```scatter_add``` function) works and the ONNX model produces the same output as the PyTorch model if I use ```opset_version=16```.

Replacing the ```scatter_add``` function by a combination of one-hot-encoding the segments_ids and using regular matrix multiplication also fixes my full model.

I am closing this issue now.

The only small thing that I noticed is that the ```find_mismatch``` function keeps reporting the ```scatter_add``` function as a mismatch. It would be useful if the ```find_mismatch``` function could be extended to show a warning with a hint to use ```opset_version=16``` instead of reporting a mismatch.

**Comment by veelken** [comment]
Thank you very much again for your help!
