### ISSUE TITLE
Input grad of LPPool error

### ISSUE THREAD

**Issue by skyleaworlder** [pytorch/pytorch#91361]
### 🐛 Describe the bug

```python
import torch
import torch.nn as nn

def save_gradient(module, grad_input, grad_output):
    print(f"{module.__class__.__name__} output grad:\n{grad_output}")
    print(f"{module.__class__.__name__} input grad:\n{grad_input}")

relu = nn.ReLU()
m = nn.LPPool2d(3, 2, stride=2)
relu2 = nn.ReLU()
relu.register_backward_hook(save_gradient)
m.register_backward_hook(save_gradient)
relu2.register_backward_hook(save_gradient)

x = torch.tensor([float(i) for i in range(1, 50)], requires_grad=True).reshape(1, 1, 7, 7)
x = torch.transpose(x, 2, 3)
x = relu(x)
x = m(x)
x = relu2(x)

x.backward(gradient=x)
```

Here is the output:

<details>

```text
ReLU output grad:
(tensor([[[[10.7722, 31.1708, 52.9788],
          [13.4294, 34.2547, 56.1203],
          [16.2184, 37.3533, 59.2653]]]], grad_fn=<ReluBackward0>),)
ReLU input grad:
(tensor([[[[10.7722, 31.1708, 52.9788],
          [13.4294, 34.2547, 56.1203],
          [16.2184, 37.3533, 59.2653]]]]),)

LPPool2d output grad:
(tensor([[[[10.7722, 31.1708, 52.9788],
          [13.4294, 34.2547, 56.1203],
          [16.2184, 37.3533, 59.2653]]]]),)
LPPool2d input grad:
(tensor([[[[0.0309, 0.0107, 0.0063],
          [0.0248, 0.0097, 0.0059],
          [0.0206, 0.0089, 0.0056]]]]),)

ReLU output grad:
(tensor([[[[ 0.0928,  5.9412,  7.2183, 15.5274, 15.8743, 24.4626,  0.0000],
          [ 0.3713,  7.5194,  8.2128, 16.9710, 16.9879, 25.8405,  0.0000],
          [ 0.6702,  7.4463,  8.4368, 16.8152, 17.1239, 25.7305,  0.0000],
          [ 1.1914,  9.0101,  9.4586, 18.2457, 18.2465, 27.1025,  0.0000],
          [ 1.5415,  8.8788,  9.6645, 18.0975, 18.3750, 26.9972,  0.0000],
          [ 2.2197, 10.4203, 10.7086, 19.5163, 19.5055, 28.3640,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]]]),)
ReLU input grad:
(tensor([[[[ 0.0928,  5.9412,  7.2183, 15.5274, 15.8743, 24.4626,  0.0000],
          [ 0.3713,  7.5194,  8.2128, 16.9710, 16.9879, 25.8405,  0.0000],
          [ 0.6702,  7.4463,  8.4368, 16.8152, 17.1239, 25.7305,  0.0000],
          [ 1.1914,  9.0101,  9.4586, 18.2457, 18.2465, 27.1025,  0.0000],
          [ 1.5415,  8.8788,  9.6645, 18.0975, 18.3750, 26.9972,  0.0000],
          [ 2.2197, 10.4203, 10.7086, 19.5163, 19.5055, 28.3640,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]]]),)
```
</details>

The size of LPPool2d input grad, I think, should probably be (7\*7), instead of (3\*3).

And LPPool2d input grad are supposed to be the same as the second ReLU output grad:

```text
(tensor([[[[ 0.0928,  5.9412,  7.2183, 15.5274, 15.8743, 24.4626,  0.0000],
          [ 0.3713,  7.5194,  8.2128, 16.9710, 16.9879, 25.8405,  0.0000],
          [ 0.6702,  7.4463,  8.4368, 16.8152, 17.1239, 25.7305,  0.0000],
          [ 1.1914,  9.0101,  9.4586, 18.2457, 18.2465, 27.1025,  0.0000],
          [ 1.5415,  8.8788,  9.6645, 18.0975, 18.3750, 26.9972,  0.0000],
          [ 2.2197, 10.4203, 10.7086, 19.5163, 19.5055, 28.3640,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]]]),)
```

### Versions

```text
1.13.0+cu116
```

---

But bp is okay. So I think it's only a problem related to `backward_hook` output. Additionally, at the beginning, I failed to figure out the relationship between current `grad_input` and `grad_output` of LPPool for I'm new to pytorch. @StellaEaves told me the relationship:

We all know LPPool computes result on each window by:

$$
f(X) = (\sum_{x \in X} x^p)^{\frac{1}{p}}
$$

The current output is:

$$
result= f(X) \times \dfrac{1}{p} (\sum_{x \in X} x^p)^{\frac{1}{p} - 1}
$$

Due to the above way to compute result, the number of f(X) is the size of `output_grad`. And I think it might be:

$$
result = \sum_{x \in X} (x^{p - 1} f(X)^{1 - p})
$$

---

I'm new to pytorch, so I hope to give me a break and ignore this inexperienced issue if I misunderstand something basic and important :)

**Comment by ZailiWang** [comment]
Hi, your analysis is correct. In latest version you should get a warning

> UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.

And if you use register_full_backward_hook() instead of register_backward_hook() as the warning instructed, you'll get the 7x7 grad_input for LPPool2d layer, same as grad_output of relu1.

**Comment by skyleaworlder** [comment]
> Hi, your analysis is correct. In latest version you should get a warning
> 
> > UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
> 
> And if you use register_full_backward_hook() instead of register_backward_hook() as the warning instructed, you'll get the 7x7 grad_input for LPPool2d layer, same as grad_output of relu1.

Thank you! Make sense!
