### ISSUE TITLE
Benchmark compare_ddp.py failed

### ISSUE THREAD

**Issue by LukeLIN-web** [pytorch/pytorch#91378]
### 🐛 Describe the bug

I tried `python compare_ddp.py`

The DDPOption.DDP_CPP_CORE,            DDPOption.PYTHON_DDP_ASYNC_REDUCTION are success.
But 
https://github.com/pytorch/pytorch/blob/789b1437e945336f83c915ab2f2dd283ac472191/benchmarks/distributed/ddp/compare/compare_ddp.py#L242
this failed.

Measuring option: DDPOption.PYTHON_DDP_SYNC_REDUCTION ...
Invoked run_ddp rank 0
setting up ...
Invoked run_ddp rank 1
setting up ...
setup done
setup done
_build_buckets_for_params called
len(param_to_bucket)=161, len(buckets)=11
Epoch 0/120 ...
_build_buckets_for_params called
len(param_to_bucket)=161, len(buckets)=11
Epoch 0/120 ...
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /opt/conda/conda-bld/pytorch_1634272168290/work/third_party/gloo/gloo/transport/tcp/pair.cc:510] op.preamble.length <= op.nbytes. 1007960 vs 701784
Traceback (most recent call last):
  File "compare_ddp.py", line 257, in <module>
    main()
  File "compare_ddp.py", line 250, in main
    join=True)
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in join
    signal_name=name
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGABRT

### Versions

GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB

Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torch-geometric==2.1.0.post1
[pip3] torch-quiver==0.1.0
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torchelastic==0.2.0
[pip3] torchtext==0.11.0
[pip3] torchvision==0.11.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.2           py37h20f2e39_0
[conda] numpy-base                1.21.2           py37h79a1101_0
[conda] pytorch                   1.10.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch-geometric           2.1.0.post1              pypi_0    pypi
[conda] torch-quiver              0.1.0                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.13                   pypi_0    pypi
[conda] torchelastic              0.2.0                    pypi_0    pypi
[conda] torchtext                 0.11.0                     py37    pytorch
[conda] torchvision               0.11.0               py37_cu113    pytorch

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by mrshenli** [comment]
I confirm I can reproduce this. 

Hey @LukeLIN-web, is this hang blocking your work? I just wanna clarify that crashed version is not the official DDP implementation. Instead it is pure Python DDP benchmark that we tried a while back. This pure Python benchmark DDP is no longer in active development. https://github.com/pytorch/pytorch/blob/master/benchmarks/distributed/ddp/compare/python_ddp.py

If this is not blocking your work, I'd prefer to retire it from the benchmark folder as it does not offer any new feature, and might confuse users.

**Comment by LukeLIN-web** [comment]
> I confirm I can reproduce this.
> 
> Hey @LukeLIN-web, is this hang blocking your work? I just wanna clarify that crashed version is not the official DDP implementation. Instead it is pure Python DDP benchmark that we tried a while back. This pure Python benchmark DDP is no longer in active development. https://github.com/pytorch/pytorch/blob/master/benchmarks/distributed/ddp/compare/python_ddp.py
> 
> If this is not blocking your work, I'd prefer to retire it from the benchmark folder as it does not offer any new features, and might confuse users.

Thank you for your reply! It is not blocking my work.

**Comment by zhaojuanmao** [comment]
I will retire https://github.com/pytorch/pytorch/blob/master/benchmarks/distributed/ddp/compare/python_ddp.py then

**Comment by LukeLIN-web** [comment]
> I will retire https://github.com/pytorch/pytorch/blob/master/benchmarks/distributed/ddp/compare/python_ddp.py then
