### ISSUE TITLE
DISABLED test_sharded_tensor_to_cpu (__main__.TestShardedTensorEnumerable)

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#91381]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_sharded_tensor_to_cpu%2CTestShardedTensorEnumerable)).

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by mrshenli** [comment]
cc @fduwjj @wanchaol
