### ISSUE TITLE
concat layers/models to run them in parallel

### ISSUE THREAD

**Issue by DanTaranis** [pytorch/pytorch#91380]
### 🚀 The feature, motivation and pitch

feature: 
parallel_layer = nn.ConcatModuleLIst([nn.Conv2D(...), nn.Conv2D])
or
parallel_layer = nn.ConcatModuleDict(["model_1":nn.Conv2D(...), "model_2": nn.Conv2D])

motivation: 
There are many use cases for running two layers or models completely in parallel: bagging small models, mixture of experts, model soups, multi-model (clip like) models, running a variety of kernel sized convolutions in parallel. 

pitch: ensembles of models are super effective - as was recently reiterated by [models soup](https://arxiv.org/abs/2203.05482). However, in order to train multiple small models together pytorch requires the models' forward pass to be in sequence - often severely underutilizing GPUs.   

### Alternatives

out = []
for model in model_list:
    out.append(model(x))

or
out = {}
for name, model in model_dict.items():
    out[name] = model(x)

**Comment by soumith** [comment]
we prefer models as code, and hence we offer very limited structured layer flow.
So, we prefer you write it out as code, as you've written in `Alternatives` and unlikely want to add what you propose into `torch.nn`.

The previous version of PyTorch (torch7) used to have a [suite of structured container layers](https://github.com/torch/nn/blob/master/doc/table.md#nn.TableLayers), and it honestly gets crazy after a point and a meta-programming in itself.

**Comment by DanTaranis** [comment]
@soumith thanks for your quick answer. I completely understand. 
As an alternative - Is there maybe a way to run over such a group of layers in a parfor?

**Comment by soumith** [comment]
you can use `zip` in python: https://stackoverflow.com/questions/1663807/how-do-i-iterate-through-two-lists-in-parallel

**Comment by soumith** [comment]
that won't necessarily run the actual computation in parallel, as pytorch layers are all run in a single cuda stream, but there are ways to make that right as well, but it's a bit advanced: https://pytorch.org/docs/stable/notes/cuda.html#cuda-streams

**Comment by DanTaranis** [comment]
yeah - I think that's closer to what I'm looking for 
thanks!
