### ISSUE TITLE
Different behavior between Tensor.sub() and Tensor.sub_() after expanded

### ISSUE THREAD

**Issue by tete1030** [pytorch/pytorch#9138]
## Issue description

The behavior between `Tensor.sub()` and `Tensor.sub_()` can be different after the Tensor is expanded.

I can see why the inplace version `sub_()` produced such result. Each time `a` is subtracted, it is actually applied on original storage of `a`. So the three-time subtraction is applied on the same memory place.

However, if such behavior is intended, I suggest add note in the document of `sub_()`, and `add_()` etc, instead of only saying 'In-place version of `sub()`' , which is confusing considering AFAIK for most cases the inplace version function produces the same result as its normal version.

## Code example

```
a = torch.tensor([[1,2]]).expand(3, -1)
b = torch.tensor([[10], [20], [30]])
```

`a.sub(b)` returns
```
tensor([[ -9,  -8],
        [-19, -18],
        [-29, -28]])
```
while `a.sub_(b)` returns
```
tensor([[-59, -58],
        [-59, -58],
        [-59, -58]])
```

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.5
GCC version: Could not collect
CMake version: version 3.9.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy (1.14.3)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by fmassa** [comment]
Related issues:

https://github.com/pytorch/pytorch/issues/906
https://github.com/pytorch/pytorch/issues/8212

I believe this will try to be addressed in the future. Closing this in favour of #8212.
