### ISSUE TITLE
vmap support for torch.tril, torch.triu

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#91403]
## Tasks
Add vmap support for the following PyTorch operations. That is, each one needs a batching rule.
- [ ] torch.tril
- [ ] torch.triu

These already have batching rules implemented, but the batching rules are incorrect.

## Expected behavior
Currently, when one does vmap over them using a 2D input, it succeeds:
```py
import torch
from functorch import vmap
x = torch.randn(32, 3)
y = vmap(torch.triu)(x)
```
This should actually raise an exception. The mental model here is that vmap should be equivalent to performing a for-loop over the arguments. The following expression does raise an exception, so vmap should as well:
```
results = []
for xi in x:
  y = torch.triu(xi)
  results.append(y)
```

## Read this!

See this note for more context https://github.com/pytorch/pytorch/blob/master/functorch/writing_batching_rules.md

If you're new to developing PyTorch and/or function transforms, we would recommend reading through https://github.com/pytorch/pytorch/wiki/Core-Frontend-Onboarding#unit-8-function-transforms-optional

For this issue, you'll likely need to implement something similar to the vmap support for torch.clone:
- https://github.com/pytorch/pytorch/blob/06bdd491fb431a7c7cc58c2402e485fcb8406ef9/aten/src/ATen/functorch/BatchRulesUnaryOps.cpp#L95

## Testing

`pytest test/functorch/test_vmap.py -v -k "test_op_has_batch_rule_tril"` should pass (currently, it is an expected failure). Ditto for triu.

cc @Chillee @samdow @soumith

**Comment by benjamintli** [comment]
ill give this a try!

**Comment by benjamintli** [comment]
ill give this a shot

**Comment by sunmorgan** [comment]
ill take this in

**Comment by sunmorgan** [comment]
@zou3519 It seems like torch.tril and torch.triu uses the "VARIADIC_BDIMS_BATCH_RULE" method from BatchRulesHelper.h shown below:

https://github.com/pytorch/pytorch/blob/0a00858095977e5c5563297322ce4a43e658d1a8/aten/src/ATen/functorch/BatchRulesHelper.h#L109

https://github.com/pytorch/pytorch/blob/df4b3b13bc84e5016854670e61a8ff0c635e2d7c/aten/src/ATen/functorch/BatchRulesViews.cpp#L542

https://github.com/pytorch/pytorch/blob/df4b3b13bc84e5016854670e61a8ff0c635e2d7c/aten/src/ATen/functorch/BatchRulesViews.cpp#L543

Then should the method be removed? It doesn't look like the method is being used anywhere else
