### ISSUE TITLE
vmap support for linalg.lu_factor

### ISSUE THREAD

**Issue by samdow** [pytorch/pytorch#91415]
## Tasks
Add vmap support for the following PyTorch operations. That is, each one needs a batching rule.
- [ ] torch.linalg.lu_factor

## Expected behavior
Currently, when one does vmap over them, they raise a warning suggesting the batching rule is not implemented:
```py
import torch
from functorch import vmap
x = torch.randn(4, 3, 2)
z = vmap(torch.linalg.lu_factor)(x)
#  UserWarning: There is a performance drop because we have not yet implemented the batching rule
```
We expect to not see a warning

Linalg ops are not quite as simple as some of the other unary ops since they have other restrictions around the shape of the input. Currently, the linalg batching rule checks that it has at least two dimensions because vmap will appear to add an extra dimension. 

Please [check the native implementation](https://github.com/pytorch/pytorch/blob/67c53d50e5b34a536cce2ad98b9ca5f65ff8a34d/aten/src/ATen/native/BatchLinearAlgebra.cpp#L1524) and [check the docs](https://pytorch.org/docs/stable/generated/torch.linalg.lu_factor.html?highlight=lu_factor#torch.linalg.lu_factor) if there's other restrictions. Most, like dtype and square-ness of the last two dimensions, will be maintained when we send down the vanilla tensor. However, if this is something that's not maintained, we'll have to write a custom batching rule that checks that restriction too

## Read this!

See this note for more context https://github.com/pytorch/pytorch/blob/master/functorch/writing_batching_rules.md

If you're new to developing PyTorch and/or function transforms, we would recommend reading through https://github.com/pytorch/pytorch/wiki/Core-Frontend-Onboarding#unit-8-function-transforms-optional

Should likely be similar to the unary operators in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/functorch/BatchRulesLinearAlgebra.cpp

Please reach out on this issue if there's any questions!

## Testing

`pytest test/functorch/test_vmap.py -v -k "op_has_batch_rule and lu_factor"` should pass (currently, it is an expected failure).

cc @zou3519 @Chillee @soumith

**Comment by MDK8888** [comment]
I would like to work on this!

**Comment by maxsuel-fa** [comment]
Hi @samdow, it is my first time contributing, can I try this one?

**Comment by viveksingh-ctrl** [comment]
I would like to contribute in this one, can i get any reference ?

**Comment by utkarsh172** [comment]
Hi @samdow , since there is no progress in this issue can I try?

**Comment by Chillee** [comment]
@utkarsh172 go for it!
