### ISSUE TITLE
[JIT] Input variable is changed

### ISSUE THREAD

**Issue by wizardk** [pytorch/pytorch#91438]
### 🐛 Describe the bug

```
import torch

class Test(torch.nn.Module):
    def __init__(self, add):
        super().__init__()
        self.add = add

    def forward(self, x):
        x += self.add
        return x

m = Test(1)
m.eval()
x = torch.randn(1, 1, 10)
m = torch.jit.trace(m, x)
m.save('Test.jit')

m = torch.jit.load('Test.jit')
m.eval()
x = torch.randn(1, 1, 10)
print(x)
with torch.no_grad():
    y = m(x)
    print(x)  # <-- x is changed
```

### Versions

PyTorch version: 1.10.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home China
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.0+cpu
[pip3] torchaudio==0.10.0+cu113
[pip3] torchvision==0.11.0+cpu
[conda] blas                      1.0                         mkl    defaults
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38hb782905_0    defaults
[conda] mkl_fft                   1.2.0            py38h45dec08_0    defaults
[conda] mkl_random                1.1.1            py38h47e9c7a_0    defaults
[conda] numpy                     1.19.2           py38hadc3359_0    defaults
[conda] numpy-base                1.19.2           py38ha3acd2a_0    defaults
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
[conda] torch                     1.10.0+cpu               pypi_0    pypi
[conda] torchaudio                0.10.0+cu113             pypi_0    pypi
[conda] torchvision               0.11.0+cpu               pypi_0    pypi

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by ZailiWang** [comment]
Hi, as in Test.forward() you changed x by 
x += self.add
The output is as expected.

**Comment by wizardk** [comment]
> 



> Hi, as in Test.forward() you changed x by x += self.add The output is as expected.

Hi @ZailiWang , but the 1.8.4 version is not working like this.

**Comment by ZailiWang** [comment]
Hi, as  current behavior is expected, I assume it was a bug and have been fixed in recent version.
