### ISSUE TITLE
The float type is converted to the long type, and the gradient information is lost

### ISSUE THREAD

**Issue by liyang159357** [pytorch/pytorch#91431]
### 🐛 Describe the bug

The predicted type is float, but it actually needs to be converted to long type. However, if it is converted to long type, the gradient will be lost. How to convert it

**Comment by samdow** [comment]
Hi @liyang159357! Could you please provide us with some more information like a code reproduction. What is the expected behavior?

**Comment by liyang159357** [comment]
您好！您的来信我已经收到，我会尽快给您回复。谢谢！——李杨

**Comment by liyang159357** [comment]
code:
 print("float_x:",x)
 print("float_x_grad_fn:", x.grad_fn)
 x=x.long()
 print("long_x:",x)
 print("long_x_grad_fn:", x.grad_fn)

result:
float_x: tensor([2.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 2.1620e+03, 2.1620e+03,
        2.1620e+03], device='cuda:0', grad_fn=<ClampBackward>)
float_x_grad_fn: <ClampBackward object at 0x000002072ABAA280>
long_x: tensor([   2,    0,    0,  ..., 2162, 2162, 2162], device='cuda:0')
long_x_grad_fn: None

How to convert it?

**Comment by liyang159357** [comment]
Hi @samdow 
code:
print("float_x:",x)
print("float_x_grad_fn:", x.grad_fn)
x=x.long()
print("long_x:",x)
print("long_x_grad_fn:", x.grad_fn)

result:
float_x: tensor([2.0000e+00, 0.0000e+00, 0.0000e+00, ..., 2.1620e+03, 2.1620e+03,
2.1620e+03], device='cuda:0', grad_fn=)
float_x_grad_fn: <ClampBackward object at 0x000002072ABAA280>
long_x: tensor([ 2, 0, 0, ..., 2162, 2162, 2162], device='cuda:0')
long_x_grad_fn: None

How to convert it?

**Comment by ZhaoqiongZ** [comment]
It seems that "Only Tensors of floating point and complex dtype can require gradients", same issue can be found at [issue 40264](https://github.com/pytorch/pytorch/issues/40264)

**Comment by samdow** [comment]
As @ZhaoqiongZ said, this is expected behavior. I'm going to close but if you have a specific use case for this, please do let us know though
