### ISSUE TITLE
Asymmetry in implementation of autograd.Function and functorch interaction

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#91451]
There are a couple of asymmetries in the implementation of autograd.Function that make me feel a bit uncomfortable. Looking for opinions.

## generate_vmap_rule = True

This is an optional class attribute that a user can add. If the user does not add it, we assume False as the default somewhere in the implementation.

Other class attributes on autograd.Function are either True or False, but they are always defined. e.g. [is_traceable](https://github.com/pytorch/pytorch/blob/cc11edb084bf3388a29ec66cb5f993b209ab9b11/torch/autograd/function.py#L414-L415).

I'm thinking of changing `generate_vmap_rule` to have two states, True or False, instead of {True, False, not defined}. This makes future developer's lives a bit easier (and also makes it clearer what the default of generate_vmap_rule is).

## vmap staticmethod

backward(), jvp() are all declared on autograd.Function: [backward](https://github.com/pytorch/pytorch/blob/cc11edb084bf3388a29ec66cb5f993b209ab9b11/torch/autograd/function.py#L318), [jvp](https://github.com/pytorch/pytorch/blob/cc11edb084bf3388a29ec66cb5f993b209ab9b11/torch/autograd/function.py#L348).

vmap is not. The behavior is:
- if generate_vmap_rule=True and vmap staticmethod defined, we error in vmap
- if generate_vmap_rule=False and vmap staticmethod defined, we use the vmap staticmethod
- if generate_vmap_rule=True and vmap staticmethod not defined, we generate the vmap behavior
- if generate_vmap_rule=False and vmap staticmethod not defined, we error in vmap

There are two things that make me uncomfortable but may not be important:
- If `generate_vmap_rule=True`, there isn't actually a vmap staticmethod. e.g. hasattr(MyFunc, 'vmap') is False. This is probably OK.
- vmap is not defined by default on autograd.Function. We could define it and then instead change the above behavior to check if the vmap staticmethod has been overriden or not. 

## setup_context staticmethod

backward(), jvp() are all declared on autograd.Function: [backward](https://github.com/pytorch/pytorch/blob/cc11edb084bf3388a29ec66cb5f993b209ab9b11/torch/autograd/function.py#L318), [jvp](https://github.com/pytorch/pytorch/blob/cc11edb084bf3388a29ec66cb5f993b209ab9b11/torch/autograd/function.py#L348).

setup_context is not. The autograd.Function implementation uses the existence of setup_context to branch between which type of autograd.Function we have.

This seems OK, it's just not consistent (i.e. setup_context is not present on base autograd.Function).

Thoughts? cc @ezyang @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @Chillee @samdow @soumith 

label cc:

**Comment by lezcano** [comment]
I'm +1 on making all these points uniform, but let's see what @albanD  has to say.

**Comment by albanD** [comment]
I agree that making things consistent is good.
For the `generate_vmap_rule` flag, we can just set the default value on the class to False for sure.

For the vmap static method. We can also define it and either add the generation logic there or assume that it will get replaced and never called when `generate_vmap_rule=True`.

For `setup_context`, it would be good to define it as well to be able to document it more easily.
We can change the check from `hasattr(fn, "setup_context")` to `fn.setup_context != _SingleLevelFunction.setup_context`.

**Comment by zou3519** [comment]
Thanks for the feedback, I'll change it to be more consistent
