### ISSUE TITLE
LinearLayer precision problem

### ISSUE THREAD

**Issue by jfolt** [pytorch/pytorch#9146]
I have a problem with LinearLayer (code snippet attached below). I expected to see the difference between the two output tensors to be exactly 0, but that is not the case. The problem occurs on Ubuntu and Windows, on CPU and GPU, Pytorch 0.4. Seems like a precision issue in the matrix multiplication/addition?
```
import torch

inputSize = 70
outputSize = 50
batchSize = 20

linear = torch.nn.Linear(inputSize, outputSize)

inp = torch.Tensor(range(batchSize*inputSize)).reshape(batchSize, inputSize)

out1 = linear(inp)

lst = []
for i in range(batchSize):
    o = linear(inp[i:i+1])
    lst.append(o)
out2 = torch.cat(lst, 0)

print("diff=", (out1-out2).abs().sum().item())

```

**Comment by weiyangfb** [comment]
I just looked into this, sounds like it is an issue of float32 vs float64, use float64 gives diff=0:

```
import torch

inputSize = 70
outputSize = 50
batchSize = 20

linear = torch.nn.Linear(inputSize, outputSize).double()

inp = torch.Tensor(range(batchSize*inputSize)).reshape(batchSize, inputSize).double()

out1 = linear(inp)

lst = []
for i in range(batchSize):
    o = linear(inp[i:i+1])
    lst.append(o)
out2 = torch.cat(lst, 0)

print("diff=", (out1-out2).abs().sum().item())
```
('diff=', 0.0)

**Comment by soumith** [comment]
@jfolt the two results are absolutely not equal, in any scientific computing sense.

What you are seeing is floating point precision playing with your intuition. You have an `inp` that contains a range between `0 to 1399`, which covers a bunch of exponent range. Then, you are doing a `W * X + b` operation here, where W is quite small (mean = 0.0002). You are doing a lot of multiplying large number with small number and adding another small number.
In such cases, the ordering of the operations affects the effective precision quite a lot, and you see floating point errors blow up.

Instead, if you make `inp` to be small, i.e. `inp = torch.randn(batchSize, inputSize)`, then you will see that even in float precision, the `diff` is in the range of `1e-5`, more in line with well-behaved floating precision expectations.

This is not a bug.

**Comment by jfolt** [comment]
Thanks for commenting.

Yes, there is a float rounding involved in those operations. But that is not the point.

Those 2 are equivalent operations. In the first case I run all batch members through the linear layer (W*X+b) in one operation, and in second case I do exactly the same but one batch member at a time.

Whatever rounding occurs in the first case, should happen in exactly the same way in the second case.

Feel free to ignore this request. I thought fixing it would lead a more deterministic behavior in LinearLayer, so it could help pytorch. But I can implement the same using basic matrix multiplication/addition like torch.mm() which works fine.

**Comment by soumith** [comment]
@jfolt 

> Whatever rounding occurs in the first case, should happen in exactly the same way in the second case.

This is not how it works. Depending on the input shape, the BLAS library (that does matrix multiplication) will order the for loops wildly differently. There's a whole set of schemes to determine which loop-ordering to use. And the loop ordering determines the order in which the elements get added up / multiplied.
Almost always you dont notice these things because generally in floating point you dont operate on large numbers combined with small numbers very frequently. But when you do, you notice as the errors amplify.
