### ISSUE TITLE
torch.compile loud error on functorch transforms

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#91470]
## Issue description

I would have expected these to fall back to eager mode, given that functorch transforms have try-catch blocks and context managers that dynamo should bail out of.

## Code example
```py
 def f(x):
     y = x * x * x * x * x * 1. * 1. * 1.
     return y

 def g(x):
     return torch.vmap(f)(x)

 cg = torch.compile(backend='aot_eager')(g)

 x = torch.randn(5)
 # Very loud error: dynamo/fake_tensor needs to peek into storage()
 # result = cg(x)
 expected = g(x)

 def g(x):
     return torch.func.grad(f)(x)

 cg = torch.compile(backend='aot_eager')(g)

 x = torch.randn([])
 expected = g(x)
 # Very loud error: dynamo needs to peek into storage()
 # result = cg(x)

 assert torch.allclose(result, expected)
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @Chillee @samdow @kshitij12345 @janeyx99 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @mlazos @yanboliang @chunyuan-w @Xia-Weiwen @desertfire

**Comment by ngimel** [comment]
@voznesenskym @ezyang what's our position on suppressing dynamo errors? Should we turn it on to let dynamo fall back?

**Comment by ezyang** [comment]
Dynamo should fall back. It'll require a little closer inspection to see what exactly is not properly raising unimplemented though
