### ISSUE TITLE
ONNX exporter : wrong constants generated for onnx::range() if onnx::LSTM follows 

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#91526]
### 🐛 Describe the bug

Here, in this example - onnx::range(1, ...) is generated from torch.arange(0, ...) - only if certain operations follow. In my case, LSTM triggered that - if you look at the ONNX graph printout, you will see the constant generated to be passed as argument 0 to onnx::range(), becomes changes from 0 (if I return context*mask) to 1 (if I pass that further to LSTM). 
Subsequently, execution fails because result of onnx::range comes out shorter that expected: 
```
2022-12-30 02:42:11.808521909 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running Mul node. Name:'/Mul' Status Message: /Mul: right operand cannot broadcast on dim 1 LeftShape: {7,555,256}, RightShape: {7,554,1}
Traceback (most recent call last):
  File "lstme.py", line 125, in <module>
    x_onnx = sess.run(None, {'input': input2[0].cpu().numpy(), 'lens' : input2[1].cpu().numpy()})[0]
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Mul node. Name:'/Mul' Status Message: /Mul: right operand cannot broadcast on dim 1 LeftShape: {7,555,256}, RightShape: {7,554,1}
```
jit.trace(), as the code illustrates, does not have same problem. Passing 'do_constant_folding' arg to export() does not affect this bug either.

```python
import torch
import onnx
from typing import Tuple
from torch import nn, Tensor
import numpy as np
import onnxruntime
from torch.nn import functional as F
from torch.nn.utils.rnn import PackedSequence

@torch.jit.script
def sort_tensor(context: Tensor, lens: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
    lens_sorted, ids_sorted = torch.sort(lens, descending=True)
    unsort_ids = torch.zeros_like(ids_sorted)
    for i in range(ids_sorted.shape[0]):
        unsort_ids[ids_sorted[i]] = i
    context = context[ids_sorted]
    return context, lens_sorted, unsort_ids

class BiLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=1, max_batch_size=64):
        super().__init__()
        self.bilstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=True)
        # Create a buffer of zeroes to be passed as hx parameter to LSTM()                                                                                                                    
        self.real_hidden_size: int = self.bilstm.proj_size if self.bilstm.proj_size > 0 else self.bilstm.hidden_size
        self.n_dir: int = int(self.bilstm.num_layers * 2)
        h_zeros = torch.zeros(self.n_dir * max_batch_size * max(self.real_hidden_size, self.bilstm.hidden_size))
        self.register_buffer('h_zeros', h_zeros, persistent=False)
        self.bilstm.flatten_parameters()

    def lstm_tensor(self, context: Tensor, lens: Tensor, enforce_sorted: bool = False) -> Tuple[Tensor, Tensor]:
        seq = nn.utils.rnn.pack_padded_sequence(
            context, lens.long().cpu(), batch_first=True, enforce_sorted=enforce_sorted
        )
        return self.lstm_sequence(seq)

    def lstm_sequence(self, seq: PackedSequence) -> Tuple[Tensor, Tensor]:
        if not (torch.jit.is_scripting() or torch.jit.is_tracing()):
            self.bilstm.flatten_parameters()
            ret, _ = self.bilstm(seq)
        else:
            # Calculate sizes and prepare views to our zero buffer to pass as hx                                                                                                              
            max_batch_size = seq.batch_sizes[0]
            common_shape = (self.n_dir, max_batch_size)
            # borisf: ONNX inssists on having self.n_dir float                                                                                                                                
            common_size = max_batch_size.float().mul(self.n_dir).long()
            h_shape = (*common_shape, self.real_hidden_size)
            c_shape = (*common_shape, self.bilstm.hidden_size)
            hx = (
                self.h_zeros[: common_size.mul(self.real_hidden_size)].view(h_shape),
                self.h_zeros[: common_size.mul(self.bilstm.hidden_size)].view(c_shape),
            )
            ret, _ = self.bilstm(seq, hx)
        return nn.utils.rnn.pad_packed_sequence(ret, batch_first=True)

    def forward(self, context: Tensor, lens: Tensor) -> Tensor:
        context, lens, unsort_ids = sort_tensor(context, lens)
        dtype = context.dtype
        return self.lstm_tensor(context, lens, enforce_sorted=True)[0][unsort_ids]

def get_mask_from_lengths_and_val(lengths, val):
    max_len = val.shape[-1]
    ids = torch.arange(0, max_len, device=lengths.device, dtype=lengths.dtype)
    mask = ids < lengths.unsqueeze(1)
    return mask

class ConvLSTMLinear(nn.Module):
    def __init__(self,n_channels=256):
        super(ConvLSTMLinear, self).__init__()
        self.bilstm = BiLSTM(n_channels, int(n_channels // 2), 1)
        self.embedding = torch.nn.Embedding(185, 256)

    def forward(self, context: Tensor, lens: Tensor) -> Tensor:
        context = self.embedding(context).transpose(1, 2)
        mask = get_mask_from_lengths_and_val(lens, context).unsqueeze(1)
        # borisfom: works if you return any of those commented out, but fails with LSTM.                                                                                                      
        # return context * mask                                                                                                                                                               
        # return sort_tensor(context, lens)[0]                                                                                                                                                
        return self.bilstm((context * mask).transpose(1,2), lens)

def get_sample(max_batch, max_dim, device='cuda'):
    inp = torch.randint(16, 32, (max_batch, max_dim), device=device, dtype=torch.int64)
    lens = torch.randint(max_dim // 8, max_dim // 4, (max_batch,), device=device, dtype=torch.int64)
    return (inp, lens)
with torch.no_grad(), torch.inference_mode():
    model = ConvLSTMLinear().cuda().eval()
    model2 = ConvLSTMLinear().cuda().eval()

    input = get_sample(1, 333)
    input2 = get_sample(7, 555)

    output = model(*input2)
    output2 = model2(*input2)
    model  = torch.jit.trace_module(model,
                                   { 'forward': input},
                                   strict = True,
                                   check_trace = [input2])

    print ("Running traced model")
    output1 = model(*input2)
    print("Traced model comparison: ", output1.sum()-output.sum())

    print ("ONNX export")
    # export with `dynamic_axes`                                                                                                                                                              
    torch.onnx.export(model2, input, 'lstm.onnx',
                      input_names=['input', 'lens', ],
                      output_names=['output',],
                      dynamic_axes={'input': {0: 'batch', 1: 'sequence'},
                                    'output': {0: 'batch', 1: 'sequence'},
                                    'lens': {0: 'batch'},
                                    },
                      opset_version=17,
                      verbose=True
    )
    onnx_model = onnx.load('lstm.onnx')
    onnx.checker.check_model(onnx_model)
    print ("ONNX export is done")

    onnx_session_opt = onnxruntime.SessionOptions()
    onnx_session_opt.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_EXTENDED
    sess = onnxruntime.InferenceSession(
        onnx_model.SerializeToString(), sess_options=onnx_session_opt, providers=['CUDAExecutionProvider']
    )

x_onnx = sess.run(None, {'input': input2[0].cpu().numpy(), 'lens' : input2[1].cpu().numpy()})[0]

print(output.shape, x_onnx.shape)
np.testing.assert_almost_equal(x_onnx, output2.cpu().detach(), decimal=3)
print("All comparisons passed")
```

### Versions

Collecting environment information...
PyTorch version: 1.14.0a0+410ce96
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] k2==1.23.2.dev20221221+cuda11.8.torch1.14.0a0
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.8.6
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.14.0a0+410ce96
[pip3] torch-tensorrt==1.3.0a0
[pip3] torchaudio==0.14.0
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.15.0a0
[conda] Could not collect

**Comment by borisfom** [comment]
This testcase also can be used to debug another ONNX issue : 
if you change line 'common_size = max_batch_size.float().mul(self.n_dir).long()' to 'common_size = max_batch_size * self.n_dir' (which is perfectly legal) you will get the following ONNXruntime error:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) of Optype (Mul) bound to different types (tensor(int64) and tensor(float) in node (/bilstm/Mul).
Looking at ONNX graph, self.n_dir is indeed generated as float constant, even though it was explicitly declared as int.

**Comment by borisfom** [comment]
Additional info: LSTM has the same effect on preceding operations other than Range, too: I had similar issue with Slice() - axis 0 becomes axis 1 and crashes there.

**Comment by borisfom** [comment]
@itaiwangms: any updates?

**Comment by titaiwangms** [comment]
Unfortunately, no. I am distracted by some other developments. I will find a time to look into this.

**Comment by titaiwangms** [comment]
Hi @borisfom ,

Thanks for this well-explained repro! The issue is not solved, but I would like to share some findings.

Found the root cause in here if you are interested,
https://github.com/pytorch/pytorch/blob/8d7f9e2f792adc30dff56103103dff25935a7a05/torch/csrc/jit/passes/onnx/peephole.cpp#L310-L337

The second input in onnx::Gather is forced to become 1 from 0, and is actually shared from onnx::range in your case, which leads to this error. I tried to create an independent onnx::Constant, instead of modifying the existing one. This can give you a successful exported and runnable model, but not match with torch on shape.

The PR needs to pass all CI, and I will have to create a even more simple repro to make sure this fix worth staying in codebase. Also, I will be looking into this shape issue if CI pass.

**Comment by borisfom** [comment]
Thanks @titaiwangms ! Too bad PyTorch does not have a version of LSTM::forward with padded input AND lengths vector. The way it is now I can't work around the bug without either losing efficiency in Pytorch (not using packed at all) or writing symbolic() for my BiLSTM to route padded input and lengths directly to onnx::LSTM (which may not be such a bad idea, actually - what do you think ?)

**Comment by titaiwangms** [comment]
I thought you could try paste the fix and build it from source?

**Comment by borisfom** [comment]
@titaiwangms : shapes off may be because of Python code issue I was fixing here: 
https://github.com/pytorch/pytorch/pull/92970
Would appreciate your review and/or help pushing that PR through!  
I was actually able to add a repro to this issue to the unit test I was modifying in my PR : just add any operation before LSTM.

**Comment by titaiwangms** [comment]
@borisfom I will take a look, but it also involves the files out of onnx folders which we will have to wait for Meta folks to review it.
