### ISSUE TITLE
Error in setup.py [fatal error: THC/THCGeneral.hpp: No such file or directory]

### ISSUE THREAD

**Issue by pjspillai** [pytorch/pytorch#9155]
Trying to build pytorch from source.

I ran `sudo python setup.py install` and got the error displayed below.
Installing in conda environment

> -- Caffe2: Found protobuf with new-style protobuf targets.
> -- Caffe2: Protobuf version 3.5.0
> -- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.0") 
> -- Caffe2: CUDA detected: 9.2
> -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr/local/cuda
> -- Caffe2: Header version is: 9.2
> -- Found cuDNN: v7.1.4  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so.7)
> -- Autodetected CUDA architecture(s): 6.1 
> -- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
> -- Gloo_LIBRARY: /home/pikachu/sandbox/python/pytorch/torch/lib/tmp_install/lib/libgloo_cuda.a
> -- Gloo_NATIVE_LIBRARY: /home/pikachu/sandbox/python/pytorch/torch/lib/tmp_install/lib/libgloo.a
> -- Gloo_INCLUDE_DIR: /home/pikachu/sandbox/python/pytorch/torch/lib/tmp_install/include
> -- MPI_INCLUDE_PATH: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include
> -- MPI_LIBRARIES: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
> -- MPIEXEC: /usr/bin/mpiexec
> -- Determining NCCL version from the header file: /usr/include/nccl.h
> -- NCCL_MAJOR_VERSION: 2
> -- Found NCCL (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libnccl.so)
> -- NCCL_LIBRARIES: /usr/lib/x86_64-linux-gnu/libnccl.so
> -- NCCL_INCLUDE_DIRS: /usr/include
> -- NCCL Version 2 or higher found, will compile with NCCL distributed backend
> -- Found CUDA: /usr/local/cuda (found version "9.2") 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/pikachu/sandbox/python/pytorch/torch/lib/build/c10d
> + make install -j12
> Scanning dependencies of target c10d
> [ 12%] Building CXX object CMakeFiles/c10d.dir/Utils.cpp.o
> [ 12%] Building CXX object CMakeFiles/c10d.dir/TCPStore.cpp.o
> [ 12%] Building CXX object CMakeFiles/c10d.dir/ProcessGroup.cpp.o
> [ 16%] Building CXX object CMakeFiles/c10d.dir/CUDAUtils.cpp.o
> [ 20%] Building CXX object CMakeFiles/c10d.dir/ProcessGroupGloo.cpp.o
> [ 29%] Building CXX object CMakeFiles/c10d.dir/ProcessGroupMPI.cpp.o
> [ 29%] Building CXX object CMakeFiles/c10d.dir/ProcessGroupNCCL.cpp.o
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/**### ProcessGroupNCCL.cpp:5:10: fatal error: THC/THCGeneral.hpp: No such file or directory**
>  #include <THC/THCGeneral.hpp>
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/c10d.dir/build.make:230: recipe for target 'CMakeFiles/c10d.dir/ProcessGroupNCCL.cpp.o' failed
> make[2]: *** [CMakeFiles/c10d.dir/ProcessGroupNCCL.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> In file included from /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/CUDAUtils.cpp:3:0:
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/CUDAUtils.cpp: In destructor ‘c10d::CUDAEvent::~CUDAEvent()’:
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/./private/CUDAUtils.hpp:25:40: warning: throw will always call terminate() [-Wterminate]
>        throw std::runtime_error(ss.str()); \
>                                         ^
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/CUDAUtils.cpp:36:5: note: in expansion of macro ‘C10D_CUDA_CHECK’
>      C10D_CUDA_CHECK(cudaEventDestroy(event_));
>      ^~~~~~~~~~~~~~~
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/./private/CUDAUtils.hpp:25:40: note: in C++11 destructors default to noexcept
>        throw std::runtime_error(ss.str()); \
>                                         ^
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/CUDAUtils.cpp:36:5: note: in expansion of macro ‘C10D_CUDA_CHECK’
>      C10D_CUDA_CHECK(cudaEventDestroy(event_));
>      ^~~~~~~~~~~~~~~
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/ProcessGroupGloo.cpp: In member function ‘c10d::AlgorithmEntry* c10d::ProcessGroupGloo::checkout(const c10d::AlgorithmKey&)’:
> /home/pikachu/sandbox/python/pytorch/torch/lib/c10d/ProcessGroupGloo.cpp:423:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    if (vec.size() != cacheNumAlgorithmEntries_) {
>        ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/c10d.dir/all' failed
> make[1]: *** [CMakeFiles/c10d.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2
> **### Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack caffe2 nanopb libshm gloo THD c10d'**
>

**Comment by Jorghi12** [comment]
Can you run "python setup.py clean" and try again?

**Comment by vishwakftw** [comment]
I think this has been fixed on `master`.

**Comment by soumith** [comment]
will be fixed by https://github.com/pytorch/pytorch/pull/9157

**Comment by vishwakftw** [comment]
I believe the same changes were made in https://github.com/pytorch/pytorch/pull/9159.

**Comment by SsnL** [comment]
should be fixed!

**Comment by pjspillai** [comment]
Thank You!
