### ISSUE TITLE
Crash when running torch.nn.functional.max_unpool3d in pytorch 1.8.0 and 1.12.0

### ISSUE THREAD

**Issue by nimashiri** [pytorch/pytorch#91555]
### 🐛 Describe the bug

If torch.nn.functional.max_unpool3d is given negative input tensor, it results in crash:

```
import torch
import numpy as np
arg_1_tensor = torch.neg(torch.rand([1, 2, 4, 6, 3], dtype=torch.float64))
arg_1 = arg_1_tensor.clone()
arg_2_tensor = torch.randint(-1,32,[1, 2, 4, 6, 3], dtype=torch.int64)
arg_2 = arg_2_tensor.clone()
arg_3 = 3
arg_4_0 = 2
arg_4_1 = 1
arg_4_2 = 2
arg_4 = [arg_4_0,arg_4_1,arg_4_2,]
arg_5 = 1
arg_6_0 = 1
arg_6_1 = 2
arg_6_2 = 6
arg_6_3 = 6
arg_6_4 = 5
arg_6 = [arg_6_0,arg_6_1,arg_6_2,arg_6_3,arg_6_4,]
try:
  res = torch.nn.functional.max_unpool3d(arg_1,arg_2,kernel_size=arg_3,stride=arg_4,padding=arg_5,output_size=arg_6,)
except Exception as e:
  print("Error:"+str(e))
```

The log message is:

```
terminate called after throwing an instance of 'c10::Error'
  what():  found an invalid max index -2 (output volumes are of size 3x6x5
Exception raised from max_unpooling3d_forward_out_cpu_frame at /pytorch/aten/src/ATen/native/MaxUnpooling.cpp:204 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7fc440e9a2f2 in /home/nimashiri/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7fc440e9767b in /home/nimashiri/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x1021e10 (0x7fc422edfe10 in /home/nimashiri/.local/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x16405 (0x7fc442f09405 in /home/nimashiri/.local/lib/python3.8/site-packages/torch/lib/libgomp-a34b3233.so.1)
frame #4: <unknown function> + 0x8609 (0x7fc4caa38609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #5: clone + 0x43 (0x7fc4cab72163 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```

Please follow this [link](https://colab.research.google.com/gist/nimashiri/23e554ae8933bee3e4abed9e4cd77106/tensorflow-python-ops-gen_list_ops-tensor_list_from_tensor.ipynb)

### Versions

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.0.194
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.5.6
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.8.0
[pip3] torch-geometric==2.0.4
[pip3] torch-tb-profiler==0.4.0
[conda] Could not collect

**Comment by samdow** [comment]
Have you tried on our latest stable version, 1.13? There I'm getting the error "Error:Found an invalid max index: -1 (output volumes are of size 6x6x5" which should point you to the issue

**Comment by nimashiri** [comment]
> Have you tried on our latest stable version, 1.13? There I'm getting the error "Error:Found an invalid max index: -1 (output volumes are of size 6x6x5" which should point you to the issue

The recent version is ok. I am running my fuzzer on 1.12.0 only, so this bug is for this version.

**Comment by soumith** [comment]
we do not do fixes for older versions, so I'll go ahead and close this.
