### ISSUE TITLE
Floating point exception when running torch.nn.functional.conv_transpose3d in pytorch 1.8.0 and 1.12.0 

### ISSUE THREAD

**Issue by nimashiri** [pytorch/pytorch#91550]
### 🐛 Describe the bug

If torch.nn.functional.conv_transpose3d is given this input combination, it results in floating point exception in pytorch 1.8.0 and 1.12.0.

```
import torch
import numpy as np
arg_1_tensor = torch.rand([1, 3, 4, 4, 4], dtype=torch.complex64)
arg_1 = arg_1_tensor.clone()
arg_2_tensor = torch.rand([3, 3, 3, 3, 3], dtype=torch.complex64)
arg_2 = arg_2_tensor.clone()
arg_3_tensor = torch.rand([3], dtype=torch.complex64)
arg_3 = arg_3_tensor.clone()
arg_4_0 = 2
arg_4_1 = 2
arg_4_2 = 2
arg_4 = [arg_4_0,arg_4_1,arg_4_2,]
arg_5 = 2
arg_6_0 = 1
arg_6_1 = 1
arg_6_2 = 1
arg_6 = [arg_6_0,arg_6_1,arg_6_2,]
arg_7 = 0
try:
  res = torch.nn.functional.conv_transpose3d(arg_1,arg_2,arg_3,stride=arg_4,padding=arg_5,output_padding=arg_6,groups=arg_7,)
except Exception as e:
  print("Error:"+str(e))
```
```
Floating point exception (core dumped)
```
I couldn't get traceback for this bug.

To test on 1.12.0, please run [link to gist](https://colab.research.google.com/gist/nimashiri/263d9f5d4bc4b7b1e52edbc8b582d451/tensorflow-python-ops-gen_list_ops-tensor_list_from_tensor.ipynb)

### Versions

Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.0.194
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[pip3] pytorch-lightning==1.5.6
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.8.0
[pip3] torch-geometric==2.0.4
[pip3] torch-tb-profiler==0.4.0
[conda] Could not collect

**Comment by samdow** [comment]
Have you tried this on the latest release, 1.13.0? I'm getting that it errors because it's a non-positive number of groups and I'm wondering if that's manifesting as a seg fault in earlier versions

**Comment by nimashiri** [comment]
> Have you tried this on the latest release, 1.13.0? I'm getting that it errors because it's a non-positive number of groups and I'm wondering if that's manifesting as a seg fault in earlier versions

The recent version is ok. I am running my fuzzer on 1.12.0 only, so this bug is for this version.

**Comment by soumith** [comment]
we do not do fixes for older versions, so I'll go ahead and close this.
