### ISSUE TITLE
[RFC] FP8 dtype introduction to PyTorch

### ISSUE THREAD

**Issue by australopitek** [pytorch/pytorch#91577]
### 🚀 The feature, motivation and pitch

Proposal of adding native fp8 dtypes in PyTorch.

Motivation and details in rfcs PR: https://github.com/pytorch/rfcs/pull/51

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by samdow** [comment]
Adding quantization oncall since it may relate to their fp8 discussions

**Comment by albanD** [comment]
Some high level update on this on the current state.

This is still under heavy discussion so there are no "just working" solution at the moment. We are focusing on allowing users to experiment with this new dtype easily.

We have developed an agreement to add the unscaled dtypes (`_fp8_e4m3`, `_fp8_e5m2`) to core PyTorch with the following functionality:
1) Add trivial factory functions to be able to create such Tensor
2) Add conversion ops to be able to create them
3) Add basic ops as requested / needed (that don’t require scale)
4) Add new native ops for the fp8 ops we care about like _mm_scaled(m1, scale1, m2, scale2, scaleout) bound to the fast cublas/cudnn.
5) Inductor should be able to handle these at least by falling back to eager and at best by generating nice code for it
6) Inductor needs to be able to fuse ops that involve _fp8_* dtypes

Separately, we are investigating how these new dtypes will be able to interact with distributed constructs (mainly FSDP) both for the collectives and the FSDP code itself.

It is expected that users will (for now) continue to handle scaling (if they want it) themselves. And we recommend either Module replacement or a Tensor subclass as a simple way to introduce this behavior.
For these experiments (even before the native dtypes are added), you can check out examples from protoquant https://github.com/facebookexperimental/protoquant/pull/23 , a subclass version https://github.com/albanD/subclass_zoo/blob/fp8/fp8_example.py and a Module version https://github.com/albanD/subclass_zoo/blob/fp8_v2/fp8_subclass_v2.py .

Please share any comment/feedback here!

**Comment by australopitek** [comment]
Thank you for the detailed answer, @albanD .
Our Habana Gaudi2 accelerator supports these both fp8 variants, and for testing/research purposes we have added the native torch.fp8_e5m2 and torch.fp8_e4m3 dtypes in our forked pytorch. 
This implementation fullfills points 1-3 of intended functionality listed in your comment, including full cpp implementation aligned with std::numeric_limits, similar to existing half and bfloat16. 
It adds support for fp8 dtypes to some basic ops like mm, conv, add, eq e.t.c. 
Additionally, for the research purposes, we have added support for stochastic rounding to these dtypes, implemented as an optional parameter to .to() operator. 

If your implementation is not finished yet, I'll be happy to align our code with the master branch and share, e.g. as a draft pull request. 

Few questions from my side: 
1. Are these two recommended methods for scales handling - Module replacement and Tensor subclassing - fully compatible with torch.compile/dynamo? Will they be captured to the fx graph? 
2. The same question about custom ops from linked examples, registered on the python and cpp level. 
3. Will scaled ops, e.g. mm_scaled, handle fp8 inputs and fp32/bf16 output? 
4. Maybe it's worth to implement also scaled variant of .to() op, since casting float/bfloat to fp8 is almost always connected with scaling the input? 
5. Do you plan any e2e solution for fp8 usage in topologies? Like an internal pytorch module handling automatic per tensor scaling based on previous iterations.

**Comment by albanD** [comment]
> Are these dtypes the ones supported in the H100 or something else?

They are the two variants that are generally available on different hardware (including but not limited to H100).

@australopitek  the implementation will be done by @vkuzo (he's on holiday now but back soon). I think that any code you already have would be great to speed up his work on this. A draft PR with him cc-ed would be a great way to share the code and jump start our work here.

For your specific questions:
1. Basic enablement for Module replacement is done Subclass is almost done. For fully integrated in the compiler stack (like inductor fused kernel) this will be done after the native dtypes are added as mentioned above.
2. CustomOps are being built explicitly to work with compile. They will only be kept as-is for now though and if we want fancy fusion, the plan is going to be about teaching inductor about these ops.
3. I would give a two part answer here:
  - When binding cublas kernels, we should provide the same flexibility as them
  - You should be able to add custom ops that do anything you want and have your subclass point to these. So what we do here should not block you from doing any of this!
4. The scale will be handled outside of the native dtype. You can add a custom kernel for that in the subclass as needed (maybe we can get that through inductor easily?)
5. My expectation long term here is going to be that users will use either Param replacement in low precision or autocast to do things. And scale handling will need to be handled there depending on which one we use. The current idea is that we're postponing this discussion to later once we have better understanding on how scale needs to be handled.

**Comment by australopitek** [comment]
@albanD ,
thank you for answers, now it's clear. I'll rebase my implementation to master and share as a pull request.

**Comment by jakeh-gc** [comment]
> > Are these dtypes the ones supported in the H100 or something else?
> 
> They are the two variants that are generally available on different hardware (including but not limited to H100).

@albanD  I would be keen for PyTorch to take an open approach to the fp8 dtypes supported. There's a family of types available in hardware https://mlir.llvm.org/docs/Dialects/Builtin/#float8e4m3b11fnuztype.

At Graphcore we have commercially available hardware with FP8 support that we would like to make available to PyTorch users [C‍6‌0‌0 IPU-PROCESSO‌‍R‌ PC‍IE C‍A‌R‌‍D‌](https://www.graphcore.ai/products/c600) and the instruction set for this hardware [Tile vertex ISA for the Mk2 IPU with FP8 support](https://docs.graphcore.ai/projects/isa/en/latest/_static/TileVertexISA-IPU21-1.3.1.pdf).

**Comment by australopitek** [comment]
@albanD , @vkuzo ,
As promised, I have pushed my implementation of float8 dtypes as a draft PR - https://github.com/pytorch/pytorch/pull/104242
It contains support for few ops and some basic tests. Please, review and decide if it should be further implemented as this PR or just used in the ongoing implementation of @vkuzo .

**Comment by jakeh-gc** [comment]
> Are you looking at doing integrations for all these types variants for fp8 at the moment?

We (Graphcore) are looking to provide support for the types we support in hardware (Float8E5M2FNUZ and Float8E4M3FNUZ) in PyTorch.

**Comment by vkuzo** [comment]
Hi folks, apologies for a very delayed reply to all of this, I was on a leave but back now.

@australopitek , thanks for your awesome work on https://github.com/pytorch/pytorch/pull/104242 !  We would love to land this once we are done with review + iteration.  Note that the final land will have to be by a Meta employee (I can help) since there are some Meta-only changes that are needed when adding new dtypes.

@jakeh-gc , we are open to more float8 flavors being added as long as they have hardware support and there is enough evidence of their viability.  You are welcome to follow a similar approach to https://github.com/pytorch/pytorch/pull/104242 for adding these flavors, it would be great if you can just summarize what current and future hardware could be enabled by these flavors.

**Comment by jakeh-gc** [comment]
> @jakeh-gc , we are open to more float8 flavors being added as long as they have hardware support and there is enough evidence of their viability. You are welcome to follow a similar approach to #104242 for adding these flavors,

Sounds good. 👍 

> it would be great if you can just summarize what current and future hardware could be enabled by these flavors

To my knowledge there is the [Graphcore C600](https://www.graphcore.ai/products/c600) and the [AMD MI300 GPUs](https://reviews.llvm.org/D143956). The C600 has been available for a while and in use by customers. We've been relying on type punning to int8 for that and would like to offer a better and more "native PyTorch" experience.

> future hardware

I would need to get permission to talk about any future products. 🤐

**Comment by eqy** [comment]
Are there any updates on achieved milestones for this issue? I see e.g., evidence that there is some support for E4M3 and E5M2: e.g., https://github.com/search?q=repo%3Apytorch%2Fpytorch%20float8_e4m3fn&type=code

**Comment by vkuzo** [comment]
> Add trivial factory functions to be able to create such Tensor
> Add conversion ops to be able to create them
> Add basic ops as requested / needed (that don’t require scale)
> Add new native ops for the fp8 ops we care about like _mm_scaled(m1, scale1, m2, scale2, scaleout) bound to the fast cublas/cudnn.

These are mostly code complete, and polish is in progress.

> Inductor should be able to handle these at least by falling back to eager and at best by generating nice code for it
> Inductor needs to be able to fuse ops that involve fp8* dtypes

These are planned for the near future.

We are also working on a `Float8Linear` module (out of core) as an e2e worklfow example of using float8 in native PyTorch - will share more soon!

**Comment by vkuzo** [comment]
Thanks for the hard work getting this in! Closing since this is completed.

Also, we just posted https://dev-discuss.pytorch.org/t/float8-in-pytorch-1-x/1815 which may be relevant to folks on this RFC.
