### ISSUE TITLE
setting CUDA_VISIBLE_DEVICES just has no effect

### ISSUE THREAD

**Issue by MrWanter** [pytorch/pytorch#9158]
Hi! I'm adding `os.environ['CUDA_VISIBLE_DEVICES'] = "2"` in my code does not work, the code always select first GPU, however `CUDA_VISIBLE_DEVICES=2 python train.py` works, I'm struggling to find the reason, but still has no clue...

**Comment by SsnL** [comment]
You need to do that before import pytorch.

**Comment by kmario23** [comment]
Ideally, `train.py` should look something like:

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "2"
import json
import torch
import torch.nn as nn
....
```

As @SsnL mentioned, the key is to add the two lines at the very top of the module.

**Comment by dlutwy** [comment]
try to use 
`export CUDA_VISIBLE_DEVICES='2'` rather than
 `os.environ['CUDA_VISIBLE_DEVICES'] = "2"`

**Comment by Patrickwhj** [comment]
If you have to do that after importing pytorch, please use it before the first usage of cuda.

**Comment by Iam-Jane** [comment]
" use it before importing pytorch!" This seems not work for me！It's strange that my code works in the morning ,but this error occurs at night. I am confused.

**Comment by hadilou** [comment]
> " use it before importing pytorch!" This seems not work for me！It's strange that my code works in the morning ,but this error occurs at night. I am confused.

torch.cuda.set_device(device_num) works fine (always for me) with pytorch. It is more common to use the above solution in tf

**Comment by ash-jha** [comment]
thanks @hadilou. I tried all of the other options above like setting `os.environ['CUDA_VISIBLE_DEVICES'] = "2"` before importing pytorch and no luck, but running `torch.cuda.set_device(2)` after importing torch did the trick!

**Comment by sammilei** [comment]
`export CUDA_VISIBLE_DEVICES='2'` then `python train.py` so that you don't need to hardcode it.

**Comment by takuma-yoneda** [comment]
`torch.cuda.set_device(2)` sounds like a good approach. 
But pytorch cannot use GPU2 if the envvar `CUDA_VISIBLE_DEVICES` is already set to something else.

[PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.cuda.set_device.html) also says
> In most cases it’s better to use CUDA_VISIBLE_DEVICES environmental variable.

If you want to go with `os.environ['CUDA_VISIBLE_DEVICES']="2"`, I learned that it doesn't need to be placed before importing pytorch.
Rather, it must be placed **before (some) pytorch function is evaluated**.

For example:
```
import torch
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "2"
```
^ This works fine.
```
import torch
import os
print('Is cuda available?:', torch.cuda.is_available())
os.environ['CUDA_VISIBLE_DEVICES'] = "2"
```
^ This fails (i.e., PyTorch doesn't respect `CUDA_VISIBLE_DEVICES="2"`)
