### ISSUE TITLE
Double free or coruption when running torch.lu_solve

### ISSUE THREAD

**Issue by nimashiri** [pytorch/pytorch#91586]
### 🐛 Describe the bug

```
import torch
import numpy as np
arg_1_tensor = torch.neg(torch.rand([2, 1, 3, 4, 2], dtype=torch.float32))
arg_1 = arg_1_tensor.clone()
arg_2_tensor = torch.rand([4, 4], dtype=torch.float32)
arg_2 = arg_2_tensor.clone()
arg_3_tensor = torch.randint(-64,32,[4], dtype=torch.int32)
arg_3 = arg_3_tensor.clone()
try:
  res = torch.lu_solve(arg_1,arg_2,arg_3,)
except Exception as e:
  print("Error:"+str(e))
```

Error:

```
double free or corruption (out)
Aborted

```

### Versions

PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 525.60.11
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h2bc3f7f_2
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0 py39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 py39h51133e4_0
[conda] numpy 1.23.5 py39h14f4228_0
[conda] numpy-base 1.23.5 py39h31eccc5_0
[conda] pytorch 1.12.0 py3.9_cuda11.3_cudnn8.3.2_0 pytorch
[conda] pytorch-mutex 1.0 cuda pytorch
[conda] torchaudio 0.12.0 py39_cu113 pytorch
[conda] torchvision 0.13.0 py39_cu113 pytorch

**Comment by samdow** [comment]
In more recent versions, I'm getting `Error:Pivots given to lu_solve must all be greater or equal to 1. Did you properly pass the result of lu_factor?` which can probably help diagnose the issue

**Comment by nimashiri** [comment]
> In more recent versions, I'm getting `Error:Pivots given to lu_solve must all be greater or equal to 1. Did you properly pass the result of lu_factor?` which can probably help diagnose the issue

The recent version is ok. I am running my fuzzer on 1.12.0 only, so this bug is for this version.

**Comment by soumith** [comment]
we do not do fixes for older versions, so I'll go ahead and close this.
