### ISSUE TITLE
Documentation of `bucketize()` is wrong, and is contradicting itself.

### ISSUE THREAD

**Issue by raaaaaymond** [pytorch/pytorch#91580]
### 📚 The doc issue

The documentation of the [bucketize function](https://pytorch.org/docs/stable/generated/torch.bucketize.html), specifically the `right` argument, is wrong. I mean, is it wrong or am I going mad? It says if "right is False (default), then the left boundary is closed". While this makes sense, it's in direct contradiction with the reference table directly below that sentence, and the actual behaviour of the function (which agrees with the reference table but contradicts the aforementioned sentence).

As a further complaint, while that sentence "if right is False (default), then the left boundary is closed" agrees with Numpy's equivalent [digitize function](https://numpy.org/doc/stable/reference/generated/numpy.digitize.html), the actual behaviour is the opposite of Numpy's `digitize()` (with respect to the `right` argument). Why??? Why not just make them behave the same way??????

### Suggest a potential alternative/fix

Ideally I'd like the behaviour `bucketize()` to change (slightly), so that it agrees with the (currently false) sentence "if right is False (default), then the left boundary is closed" in the documentation, and as such agrees with the behaviour of Numpy's `digitize()`, and **not** with the reference table also in the documentation, but I know that's probably not going to happen because, you know, it's behaviour-changing. But let's at least change that sentence in the documentation so that it doesn't contradict itself. That sentence should read "if `right` is `False` (default), then the _right_ boundary is closed".

By the way I apologise if it turns out I'm the one in the wrong. I've stared at that sentence for 2 hours now and it still seems wrong to me.

cc @svekars @carljparker

**Comment by samdow** [comment]
> It says if "right is False (default), then the left boundary is closed". While this makes sense, it's in direct contradiction with the reference table directly below that sentence, and the actual behaviour of the function (which agrees with the reference table but contradicts the aforementioned sentence).

Sorry I'm seeing that the reference table does have a closed left boundary (i.e. `boundaries[i-1] < input[m][n]...[l][x]`) and that this matches the examples where this gives us the lower bound of `i` when there's a value lies on a bin value. If it helps,  I think the kwarg description for right explains it pretty well: `In other words, if False, gets the lower bound index for each value in input from boundaries. If True, gets the upper bound index instead.`

**Comment by raaaaaymond** [comment]
To quote, `boundaries[i-1] < input[m][n]...[l][x]` is by definition _not_ a closed left boundary. Mathematically, a _closed_ left boundary means non-strict inequality `<=`, _not_ strict inequality `<`.

I'm going to use simpler notation below, and just use `x` to mean `input[m][n]...[l][x]`, I hope that simplifies things without making things confusing. Also, I'll be using mathematical notations such as `[x, y]` for a fully closed interval (between real numbers `x` and `y` where let's assume `x < y`), `(x, y)` for a fully open interval, `[x, y)` for a half-open interval that is closed _on the left_, and `(x, y]` for a half-open interval that is closed _on the right_. These are correct mathematical definitions and these are standard mathematical notation. 

So as I've said before, the reference table does agree with the actual examples and behaviour. With `right = False` (default), the reference table (and the actual behaviour) is such that each input x is allocated to a bucket based on the condition `boundary[i-1] < x <= boundary[i]`. In mathematical notation, this is the half-open interval `( boundary[i-1], boundary[i] ]`, which is _closed on the right_, not left. In other words, with `right = False`, the buckets are actually the half-open intervals `( boundary[0], boundary[1] ],  ( boundary[1], boundary[2] ],  ( ... ]`. These are half-open intervals that are closed on the _right_ boundary, _not_ the _left_ boundary, as claimed in the documentation in the sentence "if right is False (default), then the left boundary is closed". This is the sentence that I object to. 

Finally, regarding the documentation in the "Keyword Arguments" section, some of which you have quoted, I personally find it very confusing anyway, and I don't disagree with it (at least for now). I kind of wish it was omitted because I find it even more confusing that if it weren't there but that's my subjective view and let's leave that for another conversation. ( Don't bother reading the following but I mean, it just says "gets the lower bound index [...]", without a pronoun. And I'm like, _what_ "gets" the lower bound index? Do _I_ get it? Does the _function_ get it? What? Anyway after reading it, it looks correct, if confusing. So let's not get into that here.)

**Comment by raaaaaymond** [comment]
My friend just pointed out that my tone isn't good, after he read it LOL. I'm sorry if I come across rude, I don't mean to. I really appreciate your time and attention in addressing this @samdow . Thank you. And thank you everyone else who is looking into this.

**Comment by clane9** [comment]
+1 I also thought this was confusing
