### ISSUE TITLE
Apple M1 (mps backend): torch.eye not working with dtype=bool in device="mps"

### ISSUE THREAD

**Issue by hypnopump** [pytorch/pytorch#91620]
### 🐛 Describe the bug

To reproduce: 
```python
import torch as th
# this works
a = th.eye(9, device="mps").bool()
print(a.shape)
# this fails
th.eye(9, dtype=bool, device="mps")
```
Gets the following output: 
```
/AppleInternal/Library/BuildRoots/.../Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:343: failed assertion `unsupported datatype for constant'
[1]    6692 abort      python
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.2 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.10.8 (main, Nov 24 2022, 08:09:04) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] equiformer-pytorch==0.0.34
[pip3] numpy==1.24.1
[pip3] torch==1.13.1
[conda] equiformer-pytorch        0.0.34                   pypi_0    pypi
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Seems to be working fine in 13.2, but would be good to add a test for it
