### ISSUE TITLE
Merge type stubs for torch.nn.parallel

### ISSUE THREAD

**Issue by ringohoffman** [pytorch/pytorch#91648]
### 🐛 Describe the bug

[The `DataParallel` type stubs as they exist now](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/data_parallel.pyi#L6-L14) are pretty bare bones. They do not include stubs for:

- `forward`
- `replicate`
- `scatter`
- `parallel_apply`
- `gather`

https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/data_parallel.py#L150-L184

---

This leaves derived classes of `DataParallel` looking to extend these methods via `super()` with type checking errors.

```python
from typing import Iterable, List

from torch import nn


class MyDataParallel(nn.DataParallel):
    def replicate(self, module: nn.Module, device_ids: Iterable[int]) -> List[nn.Module]:
        replicas = super().replicate(module, device_ids)
        ...
        return replicas

```

```
[misc] mypy(error): "replicate" undefined in superclass
Pylance[reportGeneralTypeIssues]: Object of type "Tensor" is not callable
```

### Versions

```console
$ python collect_env.py 
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.10.6 (main, Oct 24 2022, 11:04:34) [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-boto3-s3==1.26.0.post1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchdata==0.5.0
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.14.0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torchdata                 0.5.0                    pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by ezyang** [comment]
The back story here is that in #19089 we added pyi stubs for nn modules, but when we got off Python 2 we started merging the pyi stubs directly into the py files, e.g., as in #43044. But not all the modules got the treatment. We should merge in the data parallel pyi stubs into py and delete the pyi too here. Happy to review a PR if someone does it.
