### ISSUE TITLE
Segmentation fault when running torch.nn.functional.fractional_max_pool2d on torch 1.13.1

### ISSUE THREAD

**Issue by nimashiri** [pytorch/pytorch#91659]
### 🐛 Describe the bug

```
import torch
import numpy as np
arg_1_tensor = torch.rand([1, 3, 5, 7], dtype=torch.float64)
arg_1 = arg_1_tensor.clone()
arg_2_0 = 2
arg_2_1 = 2
arg_2 = [arg_2_0,arg_2_1,]
arg_3 = None
arg_4_0 = 0.5
arg_4_1 = 0.5
arg_4 = [arg_4_0,arg_4_1,]
arg_5 = False
arg_6_tensor = torch.tensor([], dtype=torch.float64)
arg_6 = arg_6_tensor.clone()
try:
  res = torch.nn.functional.fractional_max_pool2d(arg_1,arg_2,arg_3,arg_4,arg_5,_random_samples=arg_6,)
except Exception as e:
  print("Error:"+str(e))
```

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] blas 1.0 mkl
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0 py39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 py39h51133e4_0
[conda] numpy 1.23.5 py39h14f4228_0
[conda] numpy-base 1.23.5 py39h31eccc5_0
[conda] pytorch 1.13.1 py3.9_cuda11.6_cudnn8.3.2_0 pytorch
[conda] pytorch-cuda 11.6 h867d48c_1 pytorch
[conda] pytorch-mutex 1.0 cuda pytorch
[conda] torchaudio 0.13.1 py39_cu116 pytorch
[conda] torchvision 0.14.1 py39_cu116 pytorch

**Comment by zou3519** [comment]
I get `Expect _random_samples to have 3 dimensions, got 1` on master, so this appears to be resolved.

**Comment by nimashiri** [comment]
> I get `Expect _random_samples to have 3 dimensions, got 1` on master, so this appears to be resolved.

I still get segfault on both 1.12.0 and 1.13.1

**Comment by zou3519** [comment]
@nimashiri -- can you install a pytorch nightly and try again please?

**Comment by ZailiWang** [comment]
This should have been fixed in https://github.com/pytorch/pytorch/pull/89992
Please try with nightly.

**Comment by nimashiri** [comment]
> @nimashiri -- can you install a pytorch nightly and try again please?

Sure, I will let you know.
