### ISSUE TITLE
Dynamo does not support methods defined on NamedTuples

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#91662]
```
from typing import NamedTuple

class MyTuple(NamedTuple):
    first: torch.Tensor
    second: torch.Tensor

    def add(self):
        return first + second

def my_fn(x):
    return x.add()

torch._dynamo.export(my_fn, MyTuple(first=torch.tensor(1), second=torch.tensor(2)))
```

raises `torch._dynamo.exc.Unsupported: NamedTupleVariable.add`

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by suo** [comment]
seems a relatively simple fix, we support methods on user defined classes after all

**Comment by ShisuiUzumaki** [comment]
@suo would you be accepting a PR for this? If so, and it is not too difficult to implement, I am interested, though would require instructions from your end

**Comment by ShisuiUzumaki** [comment]
@zou3519 Could you give some initial instructions on how to tackle this issue

**Comment by ezyang** [comment]
Need to trigger inlining translation on the method call, symmetric with how UserDefinedObject can inline. Also cc @wconstab who has worked on inlining

**Comment by wconstab** [comment]
I could help guide you @ShisuiUzumaki, unless you are already connecting with others on the thread.  You can ping me on pytorch slack for more 1:1, and here are some starting pointers.

1) the [NamedTupleVariable class](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/lists.py#L403) is dynamo's way of modeling behaviors that are supported on this type of object if it's encountered during tracing.  It needs to implement`call_method`.
2) NamedTupleVariable already extends from TupleVariable which implements`call_method'.  So it may be that you just want to extend TupleVariable's call_method to be more general.
3) TupleVariable extends from `BaseListVariable` and that also implements `call_method` in a slightly more general way than TupleVariable, and then delegates to the ultimate base class 'VariableTracker' which handles a couple more cases and finally raises Unimplemented.

The trivial part of this PR would be just adding general support to handle 'call_method' at the NamedTupleVariable layer.
For this part you can take inspiration from [how 'UnspecializedNNModuleVariable.call_method' calls inline_user_function_return](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/nn_module.py#L595) after constructing a VariableTracker for the Function object.

One thing I'm not sure about is, how much of the generality should be allowed only for NamedTuple vs Tuple vs List?  Is a user allowed to define a custom List with methods, or not?  cc @suo

**Comment by suo** [comment]
I think `NamedTuple` is the only one we really need to support atm. Theoretically you could inherit from `List` and define some methods, but no one really does that. In contrast, it's fairly common to hang some methods off your `NamedTuple`.

**Comment by ShisuiUzumaki** [comment]
> I could help guide you @ShisuiUzumaki, unless you are already connecting with others on the thread. You can ping me on pytorch slack for more 1:1, and here are some starting pointers.
> 
> 1. the [NamedTupleVariable class](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/lists.py#L403) is dynamo's way of modeling behaviors that are supported on this type of object if it's encountered during tracing.  It needs to implement`call_method`.
> 2. NamedTupleVariable already extends from TupleVariable which implements`call_method'.  So it may be that you just want to extend TupleVariable's call_method to be more general.
> 3. TupleVariable extends from `BaseListVariable` and that also implements `call_method` in a slightly more general way than TupleVariable, and then delegates to the ultimate base class 'VariableTracker' which handles a couple more cases and finally raises Unimplemented.
> 
> The trivial part of this PR would be just adding general support to handle 'call_method' at the NamedTupleVariable layer. For this part you can take inspiration from [how 'UnspecializedNNModuleVariable.call_method' calls inline_user_function_return](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/nn_module.py#L595) after constructing a VariableTracker for the Function object.
> 
> One thing I'm not sure about is, how much of the generality should be allowed only for NamedTuple vs Tuple vs List? Is a user allowed to define a custom List with methods, or not? cc @suo

I have a bit of confusion. NamedTuple is coming from typing, so how does this involve pytorch dynamo. The question might be a childish one, but this is the first time I am working on an issue that is not a `good-first-issue`.

**Comment by ShisuiUzumaki** [comment]
> I could help guide you @ShisuiUzumaki, unless you are already connecting with others on the thread. You can ping me on pytorch slack for more 1:1, and here are some starting pointers.
> 
> 1. the [NamedTupleVariable class](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/lists.py#L403) is dynamo's way of modeling behaviors that are supported on this type of object if it's encountered during tracing.  It needs to implement`call_method`.
> 2. NamedTupleVariable already extends from TupleVariable which implements`call_method'.  So it may be that you just want to extend TupleVariable's call_method to be more general.
> 3. TupleVariable extends from `BaseListVariable` and that also implements `call_method` in a slightly more general way than TupleVariable, and then delegates to the ultimate base class 'VariableTracker' which handles a couple more cases and finally raises Unimplemented.
> 
> The trivial part of this PR would be just adding general support to handle 'call_method' at the NamedTupleVariable layer. For this part you can take inspiration from [how 'UnspecializedNNModuleVariable.call_method' calls inline_user_function_return](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/nn_module.py#L595) after constructing a VariableTracker for the Function object.
> 
> One thing I'm not sure about is, how much of the generality should be allowed only for NamedTuple vs Tuple vs List? Is a user allowed to define a custom List with methods, or not? cc @suo

I am taking a guess here. Do you mean to say that I need to implement the `call_method` in NamedTuple class? How does that help in implementing the methods like `add`? My question may be a childish one, but I am not that much familiar with dynamo module

**Comment by ShisuiUzumaki** [comment]
@wconstab do you think something like this might work

```
    def call_method(
        self,
        tx,
        name,
        args: "List[VariableTracker]",
        kwargs: "Dict[str, VariableTracker]",
    ) -> "VariableTracker":
        options = VariableTracker.propagate(self, args, kwargs.values())
        if (
            name in ("__add__", "__iadd__")
            and len(args) == 1
            and isinstance(args[0], NamedTupleVariable)
        ):
            assert not kwargs
            return NamedTupleVariable(
                [x + y for x, y in zip(self.items, args[0].items)],
                self.tuple_cls,
                **options,
            )
        elif (
            name in ("__add__", "__iadd__")
            and len(args) == 1
            and isinstance(args[0], variables.ConstantVariable)
        ):
            assert not kwargs
            return NamedTupleVariable(
                [x + args[0] for x in self.items],
                self.tuple_cls,
                **options,
            )
        return super(NamedTupleVariable, self).call_method(tx, name, args, kwargs)
```

**Comment by wconstab** [comment]
> @wconstab do you think something like this might work

This seems like an attempt to define a new 'add' behavior for dynamo that is specific to a NamedTupleVariable + a constant.

I understood this PR as a more general need to support _any_ type of method a user might have written on a class that derives from NamedTupleVariable.

The way I would envision it looking is more like 

```
elif hasattr(self.value, name):   # does our object actually have this method that we're trying to call?
   method = inspect.getattr_static(type(self.value), name)   # get the actual method off our actual obj
   
   # now, you have to consider multiple cases where 'method' is a staticmethod, a function, etc. and implement these differently.  (See my hint above for how a staticmethod can be handled; slight variation would be needed for a bound function).
   
    if isinstance(method, staticmethod):
        # the source helps dynamo keep track of what real py obj we are working with
        source = AttrSource(
            AttrSource(AttrSource(self.source, "__class__"), name), "__func__"
        )
        
        # the inline call tells dynamo to start tracing more code
        return tx.inline_user_function_return(
            # the UserFunctionVariable is an object that models the underlying py function and lets dynamo track interactions with it.  inline_user_function will be tracing through the code of `method.__func__` in this case
            variables.UserFunctionVariable(
                method.__func__, source=source, **options
            ),
            args,
            kwargs,
        )

**Comment by ShisuiUzumaki** [comment]
> 

@wconstab Are you referring to the `elif` part of the code I mentioned earlier? Do you think the `If` part is ok?

**Comment by wconstab** [comment]
sorry, I actually didn't read the if part closely. i was assuming the if part was pre-existing and you were adding the elif part.

So my comment could apply to both the if and elif parts.  Those parts both add 'specialized' behavior to dynamo to teach dynamo how to add namedtuples together.  neither of them lets dynamo actually read the code of a custom function a user wrote and support that function.  I think that's what you want to do instead of specializing.

As a concrete example, imagine the user wrote a method named 'special_add' that adds the  first 2 elements of the tuple but then just takes the other elements from the first tuple.  We don't  want our dynamo code to have to be updated to handle this, we just want dynamo to analyze the python for `special_add` and incorporate that into its program trace.

**Comment by ShisuiUzumaki** [comment]
> sorry, I actually didn't read the if part closely. i was assuming the if part was pre-existing and you were adding the elif part.
> 
> So my comment could apply to both the if and elif parts. Those parts both add 'specialized' behavior to dynamo to teach dynamo how to add namedtuples together. neither of them lets dynamo actually read the code of a custom function a user wrote and support that function. I think that's what you want to do instead of specializing.
> 
> As a concrete example, imagine the user wrote a method named 'special_add' that adds the first 2 elements of the tuple but then just takes the other elements from the first tuple. We don't want our dynamo code to have to be updated to handle this, we just want dynamo to analyze the python for `special_add` and incorporate that into its program trace.

I see. Also, what about the intuition behind `call_method`? Could you give me some insight into that? I mean the classes named tuple inherited from are implementing specialized add right? At least that is what it felt like to me.

**Comment by Jegp** [comment]
:+1: 

Any news on this? :-) We're using NamedTuple extensively for our stateful neuron models in https://github.com/norse/norse
