### ISSUE TITLE
Redundant code in distributed

### ISSUE THREAD

**Issue by Stonesjtu** [pytorch/pytorch#9167]
It seems like the `descriptors` is not used at all. Could someone tell me why don't directly `push_back` to `raw_descriptors`?

https://github.com/pytorch/pytorch/blob/4b2b6907929093634c1e452aa2a5a85e4dd9a793/torch/csrc/distributed/Module.cpp#L786

**Comment by apaszke** [comment]
It's a legacy thing, we can remove it.

**Comment by Stonesjtu** [comment]
I'm willing to create a PR for this.

Adam Paszke <notifications@github.com> 于2018年7月6日周五 下午8:17写道：

**Comment by apaszke** [comment]
Please go ahead
