### ISSUE TITLE
Serialization of data within a tensor is slow

### ISSUE THREAD

**Issue by mrocklin** [pytorch/pytorch#9168]
## Issue description

When naively serializing a pytorch tensor (or model) with pickle the process takes longer than it probably should when comparing it to Numpy serialization of the same data.  It appears that at some point we're converting things into a list rather than returning the buffers directly.

## Code example

```python
In [1]: import numpy, torch, pickle

In [2]: x = numpy.random.random((10000, 10000))

In [3]: t = torch.tensor(x)

In [4]: %time len(pickle.dumps(x)) / 1e6                    # around 1GB/s
CPU times: user 298 ms, sys: 415 ms, total: 713 ms
Wall time: 711 ms
Out[4]: 800.000162

In [5]: %time len(pickle.dumps(t)) / 1e6                    # around 50MB/s
CPU times: user 14.6 s, sys: 1.03 s, total: 15.7 s
Wall time: 15.7 s
Out[5]: 900.200098
```
The majority of this time is spent in converting the `t.storage()` object into a list

```python
In [11]: %time _ = t.storage().tolist()
CPU times: user 12.3 s, sys: 891 ms, total: 13.2 s
Wall time: 13.2 s
```

Instead, we might consider passing around a numpy array, `buffer`, or `memoryview`, each of which will serialize much more quickly than converting to many Python objects

```python
In [1]: import torch

In [2]: torch.__version__
Out[2]: '0.4.0'
```

**Comment by soumith** [comment]
the standard pickler will be slow. if you use `torch.save` to a file or file-like object, it'll be much faster, as it goes through our custom pickling logic.

Have a look here: https://github.com/pytorch/pytorch/blob/master/torch/serialization.py#L212-L286

**Comment by mrocklin** [comment]
Right, I'm suggesting making Torch's implementation of pickle fast.

**Comment by mrocklin** [comment]
Separately, what is the most efficient way to convert a torch model/tensor into a set of bytes?  Pass an `io.BytesIO` to the save function?

**Comment by soumith** [comment]
@mrocklin the fastest way is to do `t.numpy()` and use whatever you'd do to numpy arrays. We dont natively provide conversion to the PyBuffer interface.

**Comment by soumith** [comment]
`t.numpy()` is a free operation, no memcpy, not much going on except to setup some C structs.

**Comment by mrocklin** [comment]
I understand.  Would the PyTorch community accept a PR that uses numpy within the `__reduce__` methods in order to improve serialization performance of tensor and model objects with naive use of pickle?

**Comment by mrocklin** [comment]
For others, looks like using io.BytesIO gets up to about 1GB/s.

```python
In [1]: from torchvision.models.resnet import resnet18
   ...: model = resnet18(pretrained=True)
   ...: 
   ...: 

In [2]: import torch

In [3]: import io

In [4]: bio = io.BytesIO()

In [5]: %%time
   ...: torch.save(model, bio)
   ...: b = bio.getvalue()
   ...: 
CPU times: user 32 ms, sys: 16.4 ms, total: 48.4 ms
Wall time: 47.7 ms

In [6]: len(b) / 0.047 / 1e6 # MB/s
Out[6]: 996.619
```

And then we can reconstitute 

```python
io = io.BytesIO(b)
model2 = torch.load(io)
```

**Comment by mrocklin** [comment]
For context, I maintain a parallel computing library, Dask, and users are naively passing around PyTorch objects and getting poor performance.  I can special-case PyTorch models to use the trick above, but it might be a good idea to make PyTorch's general serialization solution decently fast.  I think that this is probably pretty easy to do.

https://github.com/dask/dask-ml/issues/281#issuecomment-402497872

**Comment by soumith** [comment]
> Would the PyTorch community accept a PR that uses numpy within the __reduce__ methods in order to improve serialization performance

I'll discuss with the team and get back to you in a couple of days. We've avoided a dependence on numpy for functionality so far, but it's been a while since we discussed this.

> I can special-case PyTorch models to use the trick above

for the moment, this seems like a good idea.

**Comment by mrocklin** [comment]
Alternatively is there a nice way to get a memoryview out of a storage
object?

**Comment by mrocklin** [comment]
This would be the pure python native solution

**Comment by soumith** [comment]
MemoryView requires us to implement the Py_buffer interface, which we haven't. Implementing Py_buffer interface across Py2 and Py3 is really complicated (notes from last time we tried doing it).

**Comment by mrocklin** [comment]
Would you welcome a PR implementing the buffer protocol?

**Comment by mrocklin** [comment]
Short term, here is a possible workaround that reuses `torch.save` within `_StorageBase.__reduce__`: https://github.com/pytorch/pytorch/pull/9184

**Comment by zou3519** [comment]
@mrocklin we'll discuss and get back to you

**Comment by fmassa** [comment]
@zou3519 actually, I think this can be closed since https://github.com/pytorch/pytorch/pull/9184 was merged.

**Comment by andrei-pokrovsky** [comment]
I would like it so pickle could serialize structures containing torch.Tensors fast without installing custom picklers so I don't have to parse them.

**Comment by andrei-pokrovsky** [comment]
```
import pickle
import time
import torch

class profctx:
  def __init__(self, name):
    self.name = name
  def __enter__(self):
    self.t0 = time.time()
  def __exit__(self, a, b, c):
    self.t1 = time.time()
    print(self.name, (self.t1-self.t0)*1000)

for do_numpy in [True, False]:
    if do_numpy:
        print(".numpy() variant")
    else:
        print("regular torch.Tensor() variant")
    t = torch.Tensor([100, 100, 100, 100])
    t1 = torch.Tensor([100, 10, 100, 100])
    if do_numpy:
       t = t.numpy()
       t1 = t1.numpy()
    tmp = [t, t1]*100

    with profctx("dumps"):
        bts = pickle.dumps(tmp)

    with open("tmp.pickle", "wb") as f:
       f.write(bts)

    with open("tmp.pickle", "rb") as f1:
       unp = f1.read()

    with profctx("loads"):
        res = pickle.loads(unp)
```

Output:
.numpy() variant
dumps 0.0705718994140625
loads 0.09202957153320312
regular torch.Tensor() variant
dumps 0.576019287109375
loads 0.46825408935546875

**Comment by tstandley** [comment]
Not to reanimate this zombie, but this issue really isn't solved. It seems like it is solved for pickling models (in the above PR) but it is not solved for tensors themselves. If I pickle a tensor ".numpy()" i get much smaller pickles and much faster reads of those pickles (at least 12x faster reads).
