### ISSUE TITLE
chunk/split do as many cudaGetDevice/cudaSetDevice calls as there are results

### ISSUE THREAD

**Issue by apaszke** [pytorch/pytorch#917]
They do one pair of these calls for each slicing operation.

**Comment by colesbury** [comment]
Does this actually have a performance impact? These calls tend to be very quick

**Comment by jekbradbury** [comment]
Yes, it's a major reason why small unrolled LSTMs (which involve in addition to two GEMMs: a chunk into four gates, for 4 pairs of calls, five unary pointwise ops, for 5 more, and five binary pointwise ops, for another 5) are much slower than they are in Theano and TensorFlow.

**Comment by ngimel** [comment]
Also, there are excessive cudaGetDevice calls for each pointwise operation (9 cudaGetDevice) even without chunking, as in the following repro code:
```.py
import torch
from torch.autograd import Variable
from torch.nn import functional as F

x = Variable(torch.randn(100000).cuda())

for i in range(20):
   z = F.sigmoid(x)
```
As @jekbradbury, for small unrolled LSTMs it does show up.

**Comment by apaszke** [comment]
This should no longer be an issue, now that `split` is implemented as a native ATen function. I think we're still using the Python version for tensors, but this will be resolved soon when we stop using tensors altogether.
