### ISSUE TITLE
torch.save() and nn.DataParallel()

### ISSUE THREAD

**Issue by linzhiqiu** [pytorch/pytorch#9176]
As pointed out in this [post](https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686), when model is trained using DataParallel(), the saved model state_dict will have prefix "module." before the names of all layers. 

Is there a reason for such a prefix? Why couldn't this prefix be removed?

**Comment by SsnL** [comment]
The module is added as a submodule of the `DataParallel` module.

**Comment by zou3519** [comment]
@linzhiqiu is the "module" prefix a problem for you?

**Comment by linzhiqiu** [comment]
It is a problem when I want to reload the weight but not using model.DataParallel() 
I currently manually remove all the "module" prefix, but other people may have the same issue

**Comment by flauted** [comment]
I usually do:
```
try:
    state_dict = model.module.state_dict()
except AttributeError:
    state_dict = model.state_dict()
```

**Comment by linzhiqiu** [comment]
@flauted Genius.. Let me close this issue

**Comment by lufol** [comment]
I think it would be helpfull if `torch.save` would be able to unwrap the module from the model to be saved, as I saw several pytorch training libraries all implementing the very same code as @flauted.

Therefore I believe adding sth. like a `unwrap` flag to the method would be nice.
