### ISSUE TITLE
torch.compile burns-in device numbers, leading to errors when called with tensors on new device

### ISSUE THREAD

**Issue by bertmaher** [pytorch/pytorch#91777]
### 🐛 Describe the bug

🐛 Describe the bug:

If I compile a function, and call it with tensors on one device (e.g. `cuda:2`), then with tensors on another device (`cuda:3`), I get a `RuntimeError: Expected all tensors to be on the same device`.

Repro:
```python
import torch

torch.set_float32_matmul_precision('high')

def gemm(x, y):
    return x @ y

gemm_opt = torch.compile(gemm)

x2 = torch.randn(1024, 1024, device="cuda:2")
y2 = torch.randn(1024, 1024, device="cuda:2")

print(gemm(x2, y2).device)
print(gemm_opt(x2, y2).device)

x3 = x2.to("cuda:3")
y3 = y2.to("cuda:3")
print(gemm(x3, y3).device)
print(gemm_opt(x3, y3).device)
```

Digging into the generated code, we're burning in `device(2)`:
```python
def call(args):
    arg0_1, arg1_1 = args
    args.clear()
    with torch.cuda.device(2):
        buf0 = empty_strided((1024, 1024), (1024, 1), device='cuda', dtype=torch.float32)
        aten.mm.out(arg0_1, arg1_1, out=buf0)
        del arg0_1
        del arg1_1
        return (buf0, )
```

Seems like it should either recompile for a new device, or add some preamble to infer the device from args.

Versions

### Versions

local build from a5f32f89788befb083aa664d7911bafcbf98e3cb

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by voznesenskym** [comment]
This is a gap in guards, we currently guard on dispatch_key_, which was thought to be a good-enough representative of device, but would not fully capture device # iiuc. 

I loathe to add device str guards to every tensor check - I think if this only matters for `to` we should consider letting `to` calls accumulate a special guard here.
