### ISSUE TITLE
 subfunction can not use new parameters cover old parameters！！！

### ISSUE THREAD

**Issue by SongFGH** [pytorch/pytorch#9178]
## Issue description
When we use a subfunction in a model, however this subfunction is not included in a model, if we repeatedly delivery parameters into this subfunction, this subfunction can not use new parameters cover old parameters. Maybe this is a bug

## Code example
```
  #subfunction
 def obtain_idx_of_tree(tree, idx_tree = [], idx_idy = [], y = 0):
     if tree.num_children == 0:
        tree.idy = y
        idx_idy.append(tree.idy) #节点在树中的指标
        idx_tree.append(tree.idx) #节点在数据集中的指标
        return idx_tree, idx_idy, y        
    else:
        for i in range(tree.num_children):
            temp_tree, temp_idy, y = obtain_idx_of_tree(tree.children[i], idx_tree, idx_idy, y)
            idx_tree + temp_tree
            idx_idy + temp_idy
            y = y + 1
        tree.idy = y
        idx_idy.append(tree.idy)
        idx_tree.append(tree.idx)
        return idx_tree, idx_idy, y
          
class SentimentTrainer(object):
    def __init__(self, args, model, criterion, optimizer, embedding_model = None):
        super(SentimentTrainer, self).__init__()
        self.args       = args
        self.model      = model
        if embedding_model:
            self.feature_embedding = embedding_model[0]
            self.label_embedding = embedding_model[1]
            self.stru_embedding = embedding_model[2]
        self.criterion  = criterion
        self.optimizer  = optimizer
        self.epoch      = 0

    # helper function for training
    def train(self, dataset, alltrees):
        self.model.train()
        self.optimizer.zero_grad()
        loss, k = 0.0, 0
        accuracies = torch.zeros(len(dataset[0]))
        pred_label = []
        true_label = []
        for idx in tqdm(range(len(dataset[0])),desc='Training epoch '+str(self.epoch+1)+''):
            double_tree = dataset[0][idx]
            label = dataset[1][idx]
            tree0 = alltrees[double_tree[0]]
            idx_tree0, idx_idy0, y0 = obtain_idx_of_tree(tree0)
```

## System Info
Windows, 
Anaconda 3.6
Pytorch 0.4.0
cuda 0.9

##
when we delivery parameters into obtain_idx_of_tree(()), this function will use old parameters but not the new parameters

**Comment by SsnL** [comment]
What do you mean by "old parameters" and "new parameters"? From what I can see here, `obtain_idx_of_tree` takes in `tree0`, which is an element of the input arg `alltrees`, which doesn't seem to be mutated.

**Comment by SongFGH** [comment]
when idx = 0, according to idx_tree0, idx_idy0, y0 = obtain_idx_of_tree(tree0), we will obtain idx_tree = [0, 1, 2].
When idx = 1, if we jump into obtain_idx_of_tree(tree0), idx_tree should be  [], however we find idx_tree = [0, 1, 2]!!!
So, now you undersatnd what I mean

**Comment by SsnL** [comment]
well 

1. `obtain_idx_of_tree` is a pure python function, so it's not pytorch's problem
2. you gave the default values as empty list, e.g., `, idx_tree = []`. by python semantics, this will construct **a single list object and use that as the default value whenever it is needed**, which means that if you mutate that list, the default value will not be an empty list any more.

**Comment by SongFGH** [comment]
Yeah, you’re right.
Thanks for your solution!

发送自 Windows 10 版邮件应用

发件人: Tongzhou Wang
发送时间: 2018年7月5日 22:32
收件人: pytorch/pytorch
抄送: Long Wu; Author
主题: Re: [pytorch/pytorch] subfunction can not use new parameters cover old parameters！！！ (#9178)

well
1. obtain_idx_of_tree is a pure python function, so it's not pytorch's problem
2. you gave the default values as empty list, e.g., , idx_tree = []. by python semantics, this will construct a single list object and use that as the default value whenever it is needed, which means that if you mutate that list, the default value will not be an empty list any more.
