### ISSUE TITLE
Tried to use torch.compile() to optimize model but didn't experience acceleration when running

### ISSUE THREAD

**Issue by Hippopotamus0308** [pytorch/pytorch#91794]
Hello, when I use torch.compile() to optimize resnet18 model, I tried to count execution time of the model, but the time seems longer than not using torch.compile(), could you explain the reason?

the result on cpu using google colab:
[test1-cpu](https://github.com/Hippopotamus0308/torch2-test/blob/feat-basic-test/torch2_test.ipynb)
[test2-cpu](https://github.com/Hippopotamus0308/torch2-test/blob/feat-basic-test/torch2_test_compile_mode.ipynb)

some code on GPU machine:
[test3-gpu](https://github.com/Hippopotamus0308/torch2-test/blob/feat-basic-test/test_speedup_torch_compile.py)
[gpu-test-result](https://github.com/Hippopotamus0308/torch2-test/blob/feat-basic-test/README.md)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ZailiWang** [comment]
Hi, please wrap the model inference code snippet with torch.no_grad() or torch.inference_mode() and try again

**Comment by Hippopotamus0308** [comment]
> Hi, please wrap the model inference code snippet with torch.no_grad() or torch.inference_mode(), and call model.eval() before calling torch.compile() and try again

Hi, I tried to use torch.no_grad, the code is like:
```
model = torch.hub.load('pytorch/vision:v0.10.0', 'resnet18', pretrained=True)
opt_model_default = torch.compile(model, mode="default")
with torch.no_grad():
  opt_model_default(torch.randn(i, 3, 128, 128))
```
The code worked only when i = 1, it shows `BackendCompilerFailed: debug_wrapper raised AssertionError: Fusion only for eval!` when i > 1, and even when i = 1, the result is still
```
-------------Median Time---------------
no opt median time: 0.03842329978942871
mode = defualt: 0.046271443367004395
mode = reduce overhead: 0.04429292678833008
mode = max autotune: 0.04421067237854004
-------------Mean Time---------------
no opt mean time: 0.040084338188171385
mode = defualt: 0.04720733165740967
mode = reduce overhead: 0.04452712535858154
mode = max autotune: 0.04482107162475586
```

**Comment by ezyang** [comment]
what GPU are you using

**Comment by ezyang** [comment]
This is float32 from our perf dashboard on resnet18

```
|               name                |  bs  | eager  | aot_eager | inductor | inductor_no_cudagraphs |
|             resnet18              |  16  | 0.982  |  0.7113   |  1.267   |         1.044          |
```

https://github.com/pytorch/torchdynamo/issues/681#issuecomment-1377675740

Without cuda graphs we don't improve too much but you are supposed to get 4% on an A100. CUDA graphs helps quite a bit, you can enable it with `mode="reduce-overhead"`. If you turn on mixed precision with AMP that will also get you speedups.

**Comment by ZailiWang** [comment]
Hi @Hippopotamus0308 the error when bs > 1 is op fusion in compile() is for models in eval mode only, so you need to explicitly call model.eval() after model = torch.hub.load(...) line.

I tested with your test1-cpu code adding model.eval(), the results seems good.

--------------
testing with data of (1,3,64,64)
default model median time: 0.004123330116271973
opt model median time: 0.0027909278869628906
--------------
testing with data of (2,3,64,64)
default model median time: 0.00713193416595459
opt model median time: 0.00393068790435791
--------------
testing with data of (4,3,64,64)
default model median time: 0.008058547973632812
opt model median time: 0.005119800567626953
--------------
testing with data of (8,3,64,64)
default model median time: 0.01009368896484375
opt model median time: 0.00794994831085205
--------------
testing with data of (16,3,64,64)
default model median time: 0.011916160583496094
opt model median time: 0.006797432899475098

**Comment by Hippopotamus0308** [comment]
Thanks for your reply, I tried by myself, the results is good using eval model 😉
