### ISSUE TITLE
Is unsqueeze supported for ONNX (looks like yes, but doc doesn't say it)

### ISSUE THREAD

**Issue by sytelus** [pytorch/pytorch#9179]
Looks like PyTorch ONNX support [does include](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L738) `unsqueeze` operator. However [doc here](https://pytorch.org/docs/stable/onnx.html#supported-operators) doesn't mention it. I'm wondering if doc just need to be updated or if there is something else missing to support `unsqueeze` operator.

**Comment by soumith** [comment]
cc: @houseroad @bddppq

**Comment by houseroad** [comment]
Yes, it's supported, please check here: https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L1196

Created issue to remind me updating the doc. https://github.com/pytorch/pytorch/issues/17098
