### ISSUE TITLE
[FSDP] clip_grad_norm_ always move total_norm to cpu

### ISSUE THREAD

**Issue by l-jc** [pytorch/pytorch#91817]
## Issue description

[This line](https://github.com/pytorch/pytorch/blob/49444c3e546bf240bed24a101e747422d1f8a0ee/torch/distributed/fsdp/fully_sharded_data_parallel.py#L3672) in `clip_grad_norm_` always move `total_norm` to cpu.
```python
        if self.cpu_offload:
            total_norm = total_norm.cpu()
```

Should it be
```python
        if self.cpu_offload.offload_params:
            total_norm = total_norm.cpu()
```
Or just remove it since `total_norm` is just a scalar which doesn't take a lot of GPU memory but moving it between devices will hurt performance. 

## Code example

N/A

## System Info

PyTorch 1.13.1

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
Good catch! Let me fix this.

**Comment by awgu** [comment]
This was already fixed in https://github.com/pytorch/pytorch/pull/86337.
