### ISSUE TITLE
Tracemalloc giving wrong numbers for memory

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [pytorch/pytorch#91823]
### 🐛 Describe the bug

Hi, 

I've already discussed [here](https://discuss.pytorch.org/t/tracemalloc-giving-wrong-numbers-for-memory/167891) on PyTorchForums my question, but since it didn't get resolved, I assume it's a bug. 
The bug consists in the module `tracemalloc` giving a wildly inaccurate (false) memory consumption of PyTorch tensors. 

Here is an MWE to reproduce: 

```python
import torch
import tracemalloc

tracemalloc.start()
x = torch.ones((3, 1024, 1024, 1024), dtype=torch.uint8)
current, peak = tracemalloc.get_traced_memory()
print(f'Current: {current / 1024**2:.2f} [MB], peak: {peak / 1024**2:.2f} [MB]')
```
**Output**: 
```python
Current: 0.00 [MB], peak: 0.00 [MB]
```
Obviously, we expect a tensor with a size of about 3 GB, so this looks bad. 

However, doing the same thing with a NumPy array instead of PyTorch tensor: 
```python
import tracemalloc
import numpy as np

tracemalloc.start()
a = np.ones((3, 1024, 1024, 1024), dtype=np.uint8)
current, peak = tracemalloc.get_traced_memory()
print(f'Current: {current / 1024**2:.2f} [MB], peak: {peak / 1024**2:.2f} [MB] / 1024**2')
```
yields: 
```python
Current: 3072.00 [MB], peak: 3072.00 [MB]
```
So somehow, the interplay of `tracemalloc` and `torch` doesn't work properly...  I also tried the same code with `torch.rand()` instead of `torch.ones()` - though I had to use `dtype = torch.float32` in that case - and basically observed the same behavior. 

### Versions

Python version: 3.9.13
[conda] numpy                    1.21.5              py39h6c91a56_3  
[conda] pytorch                   1.13.1              py3.9_cpu_0    pytorch

**Comment by ZhaoqiongZ** [comment]
Hi @ImahnShekhzadeh, you could try use Pytorch profiler to track the memory use.
Here is the example code:
`
import torch
from torch.profiler import profile, record_function, ProfilerActivity


with profile(activities=[ProfilerActivity.CPU],
        profile_memory=True, record_shapes=True) as prof:
            x = torch.ones((3, 1024, 1024, 1024), dtype=torch.uint8)

print(prof.key_averages().table(sort_by="self_cpu_memory_usage", row_limit=10))

`

and the output is as following:
`
---------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
           Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg       CPU Mem  Self CPU Mem    # of Calls  
---------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
    aten::empty         0.02%      51.000us         0.02%      51.000us      51.000us       3.00 Gb       3.00 Gb             1  
     aten::ones         0.04%      78.000us       100.00%     220.307ms     220.307ms       3.00 Gb           0 b             1  
    aten::fill_        99.94%     220.178ms        99.94%     220.178ms     220.178ms           0 b           0 b             1  
---------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  
Self CPU time total: 220.307ms


`
