### ISSUE TITLE
[Dynamo] Integrate a new dynamo backend called hidet

### ISSUE THREAD

**Issue by yaoyaoding** [pytorch/pytorch#91824]
### 🚀 The feature, motivation and pitch

Dear PyTorch team,

We would like to add a new torch dynamo backend based on [hidet](https://github.com/hidet-org/hidet). 

# About hidet
Hidet is an end-to-end compilation-based inference framework. It originates from a research work from EcoSystem research lab and AWS. Inside it, we proposed a new way to schedule tensor programs, called task-mapping programming paradigm. We build hidet from scratch using python and all cuda kernels are generated by hidet itself (no dependency on vendor library such as cublas/cutlass/cudnn or compiler such as tvm/xla). Although Hidet also generates cpu kernels, we currently only focus on cuda platform. 
- GitHub: https://github.com/hidet-org/hidet
- Documentation: https://docs.hidet.org/
- ArXiv Paper: https://arxiv.org/pdf/2210.09603.pdf (to appear in ASPLOS 2023)

# Performance
The following figure shows the performance of hidet comparied with PyTorch 1.11 (eager mode), ONNX Runtime 1.11.1, AutoTVM, Ansor (in TVM 0.9.dev) on NVIDIA RTX 3090 GPU: 
![image](https://user-images.githubusercontent.com/23381083/211100578-19dc7ff4-460e-4151-b62d-89a631692e56.png)
(fp32 result. Figure from Figure 13 of our paper)

# Tuning Time
It takes us 1 to 2 minutes to tune a matrix multiplication kernel (about 10x to 20x less than AutoTVM/Ansor)
![image](https://user-images.githubusercontent.com/23381083/211102370-d9e06306-7054-429f-a366-89b4302a1713.png)
(The tuning time almost only depends on the performance of CPU. Intel i9-12900K is used in above experiment.)

# Existing method
We have implemented a pytorch frontend in hidet. The following example shows the current usage of hidet to accelerate PyTorch model (with the help of torch dynamo):
```python
import hidet
import torch

# take resnet18 as an example
x = torch.randn(1, 3, 224, 224).cuda()
model = torch.hub.load(
    'pytorch/vision:v0.9.0', 'resnet18', pretrained=True, verbose=False
)
model = model.cuda().eval()

# we should register the hidet backend for pytorch dynamo
# only need to do this if you import hidet before torch. Otherwise, it is done automatically
hidet.torch.register_dynamo_backends()

# currently, hidet only support inference
with torch.no_grad():
    # optimize the model with 'hidet' backend
    model_opt = torch.compile(model, backend='hidet')

    # run the optimized model
    y1 = model_opt(x)
    y2 = model(x)

    # check the correctness
    torch.testing.assert_close(actual=y1, expected=y2, rtol=1e-2, atol=1e-2)
```
There are some configs to control the behavior of hidet backend:
```python
hidet.torch.dynamo_config.set_search_space(2)  # schedule search space, choices: 0 (default), 1, 2 
hidet.torch.dynamo_config.correctness_report()  # show numerical difference of each hidet op vs. torch op, default False
hidet.torch.dynamo_config.use_cuda_graph(False) # use cuda graph, default True
hidet.torch.dynamo_config.use_fp16(True)  # cast to fp16, default False
hidet.torch.dynamo_config.use_fp16_reduction(True)  # use fp16 for reduction, default False
hidet.torch.dynamo_config.print_input_graph(True)  # print the recieved torch.fx.Graph from dynamo, default False
```

# Proposed method
We hope to provide a convient user inferface for PyTorch users. Currently, we need the users to manually register the backend via:
```python
hidet.torch.register_dynamo_backends()
```
We hope to add the registration of hidet backend to [torch/_dynamo/optimizations/backends.py](https://github.com/pytorch/pytorch/blob/69acc34083233bc5e51ce7f744c0b7d3f7229ca9/torch/_dynamo/optimizations/backends.py) so that users do not need to manually register hidet backend. 

# Discussion
I am still now sure what is the better way to deal with the configs. Now, `torch.compile(..., mode: str, passes: Dict[str, Any])` supports `mode` and `passes` to configure the the compilation. But these arguments are not passed to other backends except the default indcutor backend. It would be great if there is a machanism to config other backends through `torch.compile`.

Let me know if you have interest in integrating hidet into pytorch. If so, I can craft a PR to add the registration of hidet backend to pytorch. 

Thank you!

### Alternatives

# Register hidet backend when import hidet
We can also register the hidet backend automatically when users import hidet package. But this would force hidet to import torch when it is installed. This would slow down the speed of importing hidet, and is not a good default behaivor for users who only wants to optimize models from other frontend (e.g., onnx). 

cc @svekars @carljparker @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
Generally it makes the most sense for this to live out of tree. We understand that having hidet import torch is bad experience so we should figure out some API where you can register backends without forcing a torch import. One possibility is to avoid the "stringly" interface and instead pass some hidet python object directly to backend=. How does that sound?

**Comment by voznesenskym** [comment]
There is a tangentially related workstream I am exploring, wherein we remove the string and fn based interface in favor of a full Backend struct we pass into torch.compile/torch._dynamo.optimize. It needs a lot more thinking and feedback though. I will post any relevant updates here.

**Comment by yaoyaoding** [comment]
Hi @ezyang and @voznesenskym, thanks for your reply. Sorry for the late response.  

Personally speaking, I was hoping the following API
```python
import torch
model_opt = torch.compile(model, backend='hidet', configs=configs)
```
and the registration happends inside pytorch (similar like the existing TVM/TensorRT/OnnxRuntime dynamo backends). 
I agree that we can put the registration out of tree, as I understand that you might not want to add some extra registration code in the tree (as it would get crowd soon if you allow everyone to do so). Thus, a better registration mechanism is need. Looking forward to your update on this part. 

Before the registration mechanism gets more mature, I can use the exsiting torch frontend API of hidet or add a API like
```python
import hidet
model_opt = hidet.torch.compile(model, **configs)
```

**Comment by dzhulgakov** [comment]
For registration out of tree, we can utilize Python's entry_points as a plugin interface: https://packaging.python.org/en/latest/specifications/entry-points/ . We can make PyTorch to sweep through the entry points for "torch_dynamo_backends" if `torch.compile()` is invoked with an unknown backend. This way the user would just need to `pip install hidet` and won't even need to import it explicitly, worry about the import order or call an additional function
