### ISSUE TITLE
logsumexp reference produces wrong results and doesn't follow references conventions

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#91843]
- [x] For integer dtypes it uses unstabilized computation (why?), resulting in overflow. Eager mode uses stabilized computation
```
In [2]: a=torch.tensor([20, 30, 100])

In [5]: a.logsumexp(0)
Out[5]: tensor(100.)

In [6]: torch._refs.logsumexp(a, 0)
Out[6]: tensor(inf)
```

- [x] For 0 element tensor ref errors out (because it attempts to compute `.max()`)
```
n [7]: a=torch.tensor(())

In [8]: a.size()
Out[8]: torch.Size([0])

In [9]: a.logsumexp(0)
Out[9]: tensor(-inf)

In [10]: torch._refs.logsumexp(a, 0)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 torch._refs.logsumexp(a, 0)

File /scratch/ngimel/work/pytorch/torch/_prims_common/wrappers.py:209, in out_wrapper.<locals>._out_wrapper.<locals>._fn(out, *args, **kwargs)
    206         if k not in kwargs:
    207             kwargs[k] = out_attr
--> 209 result = fn(*args, **kwargs)
```
- [x] Instead of using `torch.*` wherever possible it uses `amax`, `where` and `prims.squeeze`

cc @ezyang @mruberry @Lezcano @peterbell10 @IvanYashchuk

**Comment by lezcano** [comment]
@nkaretnikov perhaps you could have a stab at this one?

**Comment by ngimel** [comment]
What's needed is pretty much moving `logsumexp` function from `_decomp/decompositions.py` here, func in `decompositions` doesn't have the problems listed above.
