### ISSUE TITLE
Further explanation about license using

### ISSUE THREAD

**Issue by Ashley123456789** [pytorch/pytorch#91847]
### 🚀 The feature, motivation and pitch

When I **import** torch as a third-party dependency, 

- Should I comply with the LICENSE (i.e., BSD 3-Clause)? Is the **import** action considered as **Redistribution and use** in the LICENSE text?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than BSD 3-Clause for my projects?

**Comment by soumith** [comment]
> Is the import action considered as Redistribution and use in the LICENSE text?

`import torch` doesn't constitute redistribution

> Do I need to pay attention to license compatibility, i.e., can I claim a less strict license than BSD 3-Clause for my projects?

You can choose any license that is compatible with having a BSD 3-Clause licensed library as a dependency. Most open-source licenses are okay with that.
