### ISSUE TITLE
NotImplementedError: Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend

### ISSUE THREAD

**Issue by AAnirudh07** [pytorch/pytorch#91875]
### 🐛 Describe the bug

I am trying to load a deep learning model with randomly initialized weights, quantize it, and perform inference using my computer's CPU. I am able to load the model & quantize it. However, I receive the following error message when I try to perform inference using the model: 

```NotImplementedError: Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::add.out' is only available for these backends: [CPU, Meta, MkldnnCPU, SparseCPU, SparseCsrCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].``` 

I am not using a custom build process.

**Code for loading & quantizing the model:**
```python
import torch
import segmentation_models_pytorch as smp
import torch.ao.quantization as tq

model = smp.Unet(
    encoder_name='mobilenet_v2',       
    in_channels=3,                  
    classes=1,               
)

model = tq.QuantWrapper(model)
model.qconfig = tq.get_default_qat_qconfig('fbgemm')
q_model = tq.prepare_qat(model)
int8_model = tq.convert(q_model)
```

Thank you in advance for any assistance!

### Versions

PyTorch version: 1.13.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 512.78
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.1
[pip3] numpy==1.24.1
[pip3] segmentation-models-pytorch==0.3.2
[pip3] torch==1.13.1
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by jerryzh168** [comment]
please follow https://pytorch.org/docs/stable/quantization.html#model-preparation-for-eager-mode-static-quantization to see how to use eager mode quantization, looks like you might need to manually modify add operation and use FloatFunctional module instead

**Comment by AAnirudh07** [comment]
Thank you!

**Comment by AAnirudh07** [comment]
Hi @akashdhamasia12,
Here's the inference code:

```python
image = image.to('cpu')
logits_mask = model(image)
prob_mask = logits_mask.sigmoid()
pred_mask = (prob_mask > 0.5).float()
```

The `QuantizedCPU` error occurs even without using DataLoader for the dataset.


Thank you for helping!

**Comment by kitrak-rev** [comment]
@jerryzh168 I tried using Quant Stub as shown below, but it didn't quantize the data tensor and the dtype remained `float32`
```
quant = torch.quantization.QuantStub()
data = torch.rand(1, 3, 224, 224)
print(quant(data).dtype)
```
Am I using it the wrong way?

**Comment by kitrak-rev** [comment]
@AAnirudh07 as pointed out by @jerryzh168  the issue was in the addition of 2 quantized tensors , which wasn't solved even after using `Float Functional add module` specifically dedicated for this, 

The solution was to dequantize and quantize back at the following line number, the if condition is used to prevent code errors for normal run
change the forward function to the snippet given below,in line number 60 in mobilenetv2.py inside torchvision/models/ package
```    
def forward(self, x: Tensor) -> Tensor:
        if self.use_res_connect:
            if(x.is_quantized):
                temp = x.dequantize()
                temp = temp + self.conv(x).dequantize()
                scale, zero_point = 1e-4, 2
                dtype = torch.quint8
                temp = torch.quantize_per_tensor(temp, scale, zero_point, dtype)
                return temp
            else:
                return x + self.conv(x)
        else:
            return self.conv(x)
            ```
And I am not aware of the usage of zero_point in quantization, if anyone knows redirect me to the resource, Thanks :)

**Comment by AAnirudh07** [comment]
Thanks @kitrak-rev !
