### ISSUE TITLE
Profiler spam lots with warnings

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#91886]
See detailed description in https://stackoverflow.com/questions/74027680/pytorch-profiler-with-scheduler-prints-unwanted-message-at-step

In particular things like `[W kineto_shim.cpp:337] Profiler is not initialized: skipping step() invocation` should be proper python warnings (use TORCH_WARN) and could be changed to be generated only once to reduce spam (TORCH_WARN_ONCE).

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb

**Comment by ngimel** [comment]
Additional complaints about profiler spam #83383

**Comment by aaronenyeshi** [comment]
We've removed this warning in https://github.com/pytorch/pytorch/pull/107216
