### ISSUE TITLE
Difference between aot_function and aot_module in AOT Autograd?

### ISSUE THREAD

**Issue by Siyuluan** [pytorch/pytorch#91882]
https://pytorch.org/functorch/nightly/aot_autograd.html

Does aot_module perform compilation like aot_function? If I want to compile the forward graph and backward graph of a PyTorch DNN, should I call aot_module or aot_function?

**Comment by ngimel** [comment]
Please ask questions on the forum, discuss.pytorch.org, github is for bug reports/feature requests
