### ISSUE TITLE
Is it possible to draw a graphviz figure of a nn.Module after a forward?

### ISSUE THREAD

**Issue by maplewizard** [pytorch/pytorch#919]
I wonder whether we can draw a graphviz graph after we execute the forward function? I hope the input and output tensor size can be shown in the fiture.

**Comment by jekbradbury** [comment]
See discussion here https://discuss.pytorch.org/t/print-autograd-graph/692

**Comment by apaszke** [comment]
And please use the forums to ask questions. GitHub issues are for bugs and feature requests.
