### ISSUE TITLE
ONNXRuntime outputs numerically incorrect results for mixed precision models.

### ISSUE THREAD

**Issue by YUNQIUGUO** [pytorch/pytorch#91902]
### 🐛 Describe the bug

https://github.com/microsoft/onnxruntime/issues/14189

Transferring onnx pytorch exporter related issues.

### Versions

See attached original issue link. Thanks.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues, including quantization

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
