### ISSUE TITLE
from torch import * does not import dtypes

### ISSUE THREAD

**Issue by asmeurer** [pytorch/pytorch#91908]
### 🐛 Describe the bug

There are several names on the `torch` module that are not included in `__all__`:

```py
>>> d = {}
>>> exec('from torch import *', d)
>>> import torch
>>> sorted([i for i in set(dir(torch)) - set(d) if not i.startswith('_')])
['Any', 'BFloat16Storage', 'BFloat16Tensor', 'Callable', 'ComplexDoubleStorage', 'ComplexFloatStorage', 'HalfStorage', 'HalfTensor', 'LoggerBase', 'PRIVATE_OPS', 'QInt32Storage', 'QInt8Storage', 'QUInt2x4Storage', 'QUInt4x2Storage', 'QUInt8Storage', 'Set', 'Storage', 'StorageBase', 'TYPE_CHECKING', 'USE_GLOBAL_DEPS', 'USE_RTLD_GLOBAL_WITH_LIBTORCH', 'Union', 'amp', 'ao', 'attr', 'autocast', 'autograd', 'backends', 'bfloat16', 'bool', 'broadcast_shapes', 'builtins', 'candidate', 'cdouble', 'cfloat', 'chalf', 'channels_last', 'channels_last_3d', 'classes', 'classproperty', 'compiled_with_cxx11_abi', 'complex128', 'complex32', 'complex64', 'contiguous_format', 'cpu', 'ctypes', 'cuda', 'distributed', 'distributions', 'double', 'eig', 'fft', 'float', 'float16', 'float32', 'float64', 'from_dlpack', 'functional', 'futures', 'fx', 'get_file_path', 'half', 'hub', 'inspect', 'int', 'int16', 'int32', 'int64', 'int8', 'jit', 'legacy_contiguous_format', 'library', 'linalg', 'long', 'lstsq', 'lu', 'masked', 'matrix_rank', 'multiprocessing', 'name', 'nested', 'nn', 'obj', 'onnx', 'ops', 'optim', 'os', 'overrides', 'package', 'pca_lowrank', 'per_channel_affine', 'per_channel_affine_float_qparams', 'per_channel_symmetric', 'per_tensor_affine', 'per_tensor_symmetric', 'platform', 'prepare_multiprocessing_environment', 'preserve_format', 'profiler', 'qint32', 'qint8', 'quantization', 'quantized_gru', 'quantized_lstm', 'quasirandom', 'quint2x4', 'quint4x2', 'quint8', 'random', 'return_types', 'serialization', 'set_default_dtype', 'set_grad_enabled', 'short', 'solve', 'sparse', 'sparse_bsc', 'sparse_bsr', 'sparse_coo', 'sparse_csc', 'sparse_csr', 'special', 'storage', 'strided', 'svd_lowrank', 'sys', 'testing', 'textwrap', 'to_dlpack', 'torch', 'torch_version', 'types', 'uint8', 'unique', 'utils', 'version']
```

Most of these are just submodules and types so are probably intentionally not included, but it seems to me that the dtype names (`int8`, `int16`, `float32`, etc.) should be included.

### Versions

Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.2 (x86_64)
GCC version: Could not collect
Clang version: 11.1.0
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:55:37)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-12.6.2-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] numpydoc==1.5.0
[pip3] torch==1.13.0
[conda] cpuonly                   1.0                           0    pytorch-nightly
[conda] mkl                       2022.2.1         h44ed08c_16952    conda-forge
[conda] numpy                     1.23.5           py39hdfa1d0c_0    conda-forge
[conda] numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
[conda] pytorch                   1.13.0          cpu_py39h0a103a1_0    conda-forge
[conda] torch                     1.11.0a0+git5347dab           dev_0    <develop>

cc @albanD

**Comment by albanD** [comment]
Hi,

This is most likely missing entries in the `__all__` list there.
Someone needs to check where these types are coming from and make sure they are properly added to this list like we do for C bound code here https://github.com/pytorch/pytorch/blob/1892c75a45f599bd7ea652b10c379325abca8648/torch/__init__.py#L371-L373

**Comment by TamirCohen** [comment]
Hi, I would like to try solving this issue.
My idea is to iterate all the attributes of torch module in the `__init__.py` and check which is of type `torch.dtype`.
I thought to add something like this:
```
import torch
for attribute in dir(torch):
    if getattr(torch, attribute).__class__ == torch.dtype:
        __all__.append(attribute)
```
@albanD What do you think?

**Comment by albanD** [comment]
We should have a test now that checks that APIs are correct. The historically bad ones should be listed in https://github.com/pytorch/pytorch/blob/main/test/allowlist_for_publicAPI.json (we should fix them and remove them from that list).

Not sure why the dtypes are not all caught there though :thinking:

**Comment by albanD** [comment]
Ho yes, we skipped non callable/classes from there.
The problem is that these other objects don't have a `__module__` attribute (for example you can't add it to torch.e that is a 'float' type).
That being said, our dtypes (like torch.float, etc) are classes, so they should properly trip that test.

**Comment by TamirCohen** [comment]
I checked it using `inspect.isclass` and it returned false:
```
>>> inspect.isclass(torch.float)
False
```
`torch.dtype` is a class and I think `torch.float` is not a class, its an instance of `torch.dtype`
```
>>> isinstance(torch.float, torch.dtype)
True
>>> isinstance(torch.float, type) # equivelent to inspect.isclass
False
```

**Comment by albanD** [comment]
Ho right...
I don't think sphinx coverage will catch these but I agree it would be good to make sure they are covered by the API checks.
Updating this check to accept instance of torch.dtype and adding a comment explaining why we have this special case sounds good
