### ISSUE TITLE
[PT2.0 Feature Proposal] GNN inference and training optimization on CPU

### ISSUE THREAD

**Issue by fzhao3** [pytorch/pytorch#91951]
### 🚀 The feature, motivation and pitch

This ticket is per request from Ibrahim Siddiqui as part of PT2.0 feature proposal process. The feature proposal has also been submitted @ https://docs.google.com/spreadsheets/d/1TzGkWuUMF1yTe88adz1dt2mzbIsZLd3PBasy588VWgk/edit#gid=790902532 

Graph Neural Networks (GNNs) is a powerful tool to analyze graph structure data. This proposed feature is targeted at improving GNN inference and training performance on CPU. PyG is a very popular library built upon PyTorch for GNN.  Performance of PyG strongly depends on PyTorch. Currently on CPU, GNN models of PyG run extremely slow due to the lack of GNN-related sparse matrix multiplication ops (i.e., spmm_reduce) and the lack of several critical kernel level optimizations (scatter/gather, etc.) tuned for GNN compute. 
We submitted PRs to optimize the more critical hot spots, and demonstrated a 2-5x performance speedup on PyG benchmarks/examples, OGB benchmarks for single node inference and training. 
To be specific, the following kernels are optimized from torch side (for inference and training stage, targeting at torch 2.0):

- scatter_add and scatter_reduce: this is the hotspot in Message Passing when the edge index is stored in COO, which takes 49% of runtime in SAGE + Reddit.
- spmm_reduce: this is the hotspot in Message Passing when the edge index is stored in CSR, which takes 97% of runtime in GCN + ogbn-products.
- Gather: backward of scatter_add. Current implementation from ATen is not efficient when the index is an expanded tensor.
- sampled_addmm: this one can be used for feature aggregation when the edge index is in CSR, the current CPU impl is a reference design which converts the sparse tensor back to dense for computation.

The following will be nice to have:

- segment_reduce: used when the edge index is logically CSR but physically stored in individual dense tensors. The current impl in torch is a reference (single thread and non-vectorized).
- Multi-Aggregation mode: for scatter_reduce or spmm_reduce, the graph might want to initiate multiple ‘reduce’ types spontaneously. Allowing multi-aggregation mode would greatly save time for such scenarios since the src feature matrix (which is usually very large and accessed in an in-direct order) could be only read once.

### Additional context

**Here are the PRs that are required for this feature:**
* #82703
* #83727 
* #87586 

**There PRs are nice to have for PT2.0.**
* #90978 
* #91500 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by soumith** [comment]
this is a nice summary and the work is pretty exciting. thanks for the context!

**Comment by ezyang** [comment]
From all the PRs being closed, I guess so!
