### ISSUE TITLE
sympy failure on model when dynamic_shapes=True

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#91982]
Error looks like: 
```
Traceback (most recent call last):
  File "torch/_dynamo/utils.py", line 1078, in run_node
    return node.target(*args, **kwargs)
RuntimeError: TypeError: cannot determine truth value of Relational
At:
  sympy/core/relational.py(297): __nonzero__
  torch/fx/experimental/symbolic_shapes.py(943): _maybe_guard_eq
  torch/fx/experimental/symbolic_shapes.py(989): evaluate_expr
  torch/fx/experimental/symbolic_shapes.py(209): bool_
```
This is happening on an internal model. Full stack trace: P595091810.

Repro: patch D42443834 and run the command in the comment: https://fburl.com/diff/f5nphw9a

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
cc @Chillee

**Comment by bhack** [comment]
I don't see the model as it is internal. Are you using `from einops.layers.torch import Rearrange`?

**Comment by bhack** [comment]
I cannot see the model/stack as it is internal.. Is this going to be solved by https://github.com/pytorch/pytorch/issues/107277

**Comment by ezyang** [comment]
we got CrystalDPR working so I assume we actually fixed this
