### ISSUE TITLE
Add environment variable to specify g++ compiler to compile inductor generated code

### ISSUE THREAD

**Issue by vermouth1992** [pytorch/pytorch#91997]
### 🚀 The feature, motivation and pitch

Currently, torchinductor compiles generated code using the compiler by searching "g++" in the PATH. However, this creates problems on Mac m1 machine because native clang doesn't support '-fopenmp' and '-march=native'.

Although it is possible to soft link the "g++" to point to the homebrew install gcc, search g++ compiler via environment variable is more reasonable as users can specify the desired compiler easily.

The changes can be implemented in this function https://github.com/pytorch/pytorch/blob/d7dc1c2fd58a2b2c7972c81779903fda4fa4ec1d/torch/_inductor/codecache.py#L143 to allow environment variable CXX to prioritize searching g++ the in the $PATH.

I can submit a pull request if it helps.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
Sure, send us the patch.

**Comment by vermouth1992** [comment]
> @vermouth1992 This doesn't work for you? https://github.com/pytorch/pytorch/blob/b8cf01013975dfabe40966b8dc4555a2e069336c/torch/_inductor/codecache.py#L485:L488

It works now, but it doesn't work at the time this issue was created. Not sure whether the feature that users can specify compiler on their own is necessary.

**Comment by vermouth1992** [comment]
The environment variable CXX should actually work now.
