### ISSUE TITLE
PyTorch Windows build errors out because of older Caffe2

### ISSUE THREAD

**Issue by sytelus** [pytorch/pytorch#9200]
If you try to build PyTorch latest master following instructions, you will ultimately get this error:

```
"C:\GitHubSrc\pytorch\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"C:\GitHubSrc\pytorch\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"C:\GitHubSrc\pytorch\pytorch\build\caffe2\apply_test.vcxproj" (default target) (4) ->
"C:\GitHubSrc\pytorch\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (17) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\GitHubS
rc\pytorch\pytorch\build\caffe2\caffe2_gpu.vcxproj]

    332 Warning(s)
    1 Error(s)
```

The cause of the error is that the version of [Caffe2](https://github.com/pytorch/pytorch/tree/master/caffe2) included with PyTorch has [issue](https://github.com/caffe2/caffe2/issues/774) compiling with VS2017. Looks like this issue was fixed in Caffe2 so may be updating version in PyTorch might fix current build issue.

**Comment by sytelus** [comment]
I think I figured out the cause of error. I'd CUDA 8.0/cuDNN 6.1 installed which expected VS2015 toolchain. After I uninstalled those and installed CUDA 9.2/cuDNN 7.1, I'm now past above error. I would suggest to add this in docs for WIndows build section because instructions there mentions VS2017 which would only work for CUDA 9.x/cuDNN7.x.

**Comment by peterjc123** [comment]
I'm on this. Unfortunately, building PyTorch with VS2015 at present will be finally blocked by #9092.

**Comment by jerrygaoLondon** [comment]
I still encountered this error with today's master branch and CUDA 9.2 + cuDNN-9.2-v7.2.1.38 + VS 2017.

``` C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [C:\python\pytorch\build
\caffe2\caffe2_gpu.vcxproj]```

**Comment by peterjc123** [comment]
@jerrygaoLondon 
Would you please give me the full log? This error message is not the root cause of the build failure.
I’m afraid that you are using the wrong version of VS. I have not tested VS 14.15 before so I don't know exactly whether it is supported by CUDA 9.2. However, you can try to install 14.11. That’s the version we used in CI.
