### ISSUE TITLE
PYTORCH_NO_CUDA_MEMORY_CACHING=1 doesn't work

### ISSUE THREAD

**Issue by Xu-Kai** [pytorch/pytorch#92074]
### 🐛 Describe the bug

I try to set PYTORCH_NO_CUDA_MEMORY_CACHING, but it doesn't work. 
Then I compile pytorch from source to figure out.
I update function forceUncachedAllocator in c10/cuda/CUDACachingAllocator.cpp to check PYTORCH_NO_CUDA_MEMORY_CACHING. 
The origin forceUncachedAllocator  is 
```c
bool forceUncachedAllocator() {
  static bool force_uncached =
      getenv("PYTORCH_NO_CUDA_MEMORY_CACHING") != nullptr;
  return force_uncached;
}
```
I add header file  #include \<iostream\>
Then I update the forceUncachedAllocator  
```c
bool forceUncachedAllocator() {
  static bool force_uncached =
      getenv("PYTORCH_NO_CUDA_MEMORY_CACHING") != nullptr;

  char *value = getenv("PYTORCH_NO_CUDA_MEMORY_CACHING");
  if (value != NULL)
  {
    std::cout << "PYTORCH_NO_CUDA_MEMORY_CACHING value: " << value << std::endl;
    std::cout << "force_uncached: " << force_uncached  << std::endl;
  }
  else
  {
    std::cout << "PYTORCH_NO_CUDA_MEMORY_CACHING is NULL" << std::endl;
    std::cout << "force_uncached: " << force_uncached  << std::endl;
  }
  
  return force_uncached;
}
```
The python code is 

```python 
import torch
import os

a = torch.rand((2,2))
b = a.to("cuda")

print("set PYTORCH_NO_CUDA_MEMORY_CACHING=1")
os.environ["PYTORCH_NO_CUDA_MEMORY_CACHING"]="1"
c = torch.rand((2,2))
d  = c.to("cuda")
```

The output is: 

```
PYTORCH_NO_CUDA_MEMORY_CACHING is NULL
force_uncached: 0
set PYTORCH_NO_CUDA_MEMORY_CACHING=1
PYTORCH_NO_CUDA_MEMORY_CACHING value: 1
force_uncached: 0
```

After I set PYTORCH_NO_CUDA_MEMORY_CACHING =1, the force_uncached is still 0. 

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+git723d764
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Rocky Linux release 8.6 (Green Obsidian) (x86_64)
GCC version: (GCC) 9.4.0
Clang version: 15.0.5
CMake version: version 3.22.1
Libc version: glibc-2.28

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB

Nvidia driver version: 470.63.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0a0+git723d764
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2    anaconda
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.5           py39h14f4228_0  
[conda] numpy-base                1.23.5           py39h31eccc5_0  
[conda] torch                     2.0.0a0+git723d764           dev_0    <develop>

cc @ngimel

**Comment by drisspg** [comment]
Can you try setting the variable before starting the Python process?

**Comment by ngimel** [comment]
It works as expected, environment variables are checked on initialization only.
