### ISSUE TITLE
Quantized fasterrcnn_mobilenet_v3_large_fpn not export to onnx

### ISSUE THREAD

**Issue by enfild** [pytorch/pytorch#92084]
### 🐛 Describe the bug

After good training i start script for export and quanize the trained model to onnx:
```
import os
import torch
import onnx
from model import create_model
from torch_utils import utils
from ptflops import get_model_complexity_info
from onnxruntime.quantization import quantize_dynamic, QuantType
from config import NUM_CLASSES, DEVICE, RESIZE_WIDTH, RESIZE_HEIGHT, OUT_DIR

model = torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn(num_classes=NUM_CLASSES)
model_path = os.path.join(OUT_DIR, "best_model.pth")
checkpoint = torch.load(model_path, map_location=DEVICE)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval()

model_int8 = torch.quantization.quantize_dynamic(
    model,  # the original model
    {torch.nn.Linear},  # a set of layers to dynamically quantize
    dtype=torch.qint8)  # the target dtype for quantized weights
model_int8.eval()

path_quant_onnx = os.path.join(OUT_DIR, "quant_onnx_model.onnx")
x_input = torch.randn(1, 3, RESIZE_HEIGHT, RESIZE_WIDTH)

torch.onnx.export(model_int8,               # model being run
                  x_input,                  # model input (or a tuple for multiple inputs)
                  path_quant_onnx,   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=12,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'])
```
After start script i've got Error:
```
RuntimeError: Type 'Tuple[Tensor, NoneType]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be traced
``` 
If i try export `model`(non quant) - all is fine.
Changing Opset not help. Changing `x_input` to '(x_input)' or '[x_input]' not help. Dynamic axes not help
Changing `x_input` to `[x_input, x_input]` or '(x_input, x_input)' get me next out:
```
AttributeError: 'Tensor' object has no attribute 'items'
```
If i try use tracing:
``` qmodel_traced = torch.jit.trace(model_int8, example_inputs = x_input)```
Output is:
``` RuntimeError: Only tensors, lists, tuples of tensors, or dictionary of tensors can be output from traced functions ```

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==1.13.1
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.14.1
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by BowenBao** [comment]
Hello @enfild , the issue seems to be that `quantize_dynamic` is un-traceable. Please give a try exporting with `torch.quantization.prepare` + `torch.quantization.convert`.
