### ISSUE TITLE
Mobile Upgrader Is Unusable, Preventing Making Updates to Operators 

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#92092]
### 🐛 Describe the bug

Running the mobile upgrader without any other changes should be a no-op, however running it on master causes test failures. See https://github.com/pytorch/pytorch/pull/89886. This prevents adding new rules and therefore making changes to operators, as in https://github.com/pytorch/pytorch/pull/89797 which fixes a torchinductor error. 

### Versions

master

**Comment by eellison** [comment]
cc @gmagogsfm would you help triage ?

**Comment by eellison** [comment]
cc @tugsbayasgalan @cccclai

**Comment by eellison** [comment]
@tugsbayasgalan this is closed now right ?

**Comment by tugsbayasgalan** [comment]
yep
