### ISSUE TITLE
load_state_dict: KeyError: 'unexpected key in state_dict'

### ISSUE THREAD

**Issue by anantzoid** [pytorch/pytorch#921]
`state_dict` does not acknowledge custom layers before calling the forward function. 
```
class AuxNet(nn.Module):
    def __init__(self, num_pieces):
        super(AuxNet, self).__init__()

    def forward(self, input):
        shape = input.size()
        self.linear = nn.Linear(shape[-1], shape[-1], bias=False)
        # Do some stuff..
        return input
       
class SNet(nn.Module):
    def __init__(self):
        super(SNet, self).__init__()
        self.main = nn.Sequential(
                nn.Conv2d(3, 32, 5, 1, 0, bias=False),
                nn.Dropout(0.2),
                AuxNet()
            )
    def forward(self, input):
        return self.main(input)
  
n = SNet()
print n.state_dict().keys()
n(Variable(torch.FloatTensor(10,3,16,16)))
print n.state_dict().keys()
```

The above code prints the following output:
```
['main.0.weight']
['main.0.weight', 'main.2.linear.weight']
```

Thus, `load_state_dict` gives the following error when called just after initialising the net:
`KeyError: 'unexpected key "main.2.linear.weight" in state_dict'`

**Comment by jekbradbury** [comment]
Unless you're doing something very unusual, you should be initializing `AuxNet`'s child `Linear` layer in `__init__` and not the forward pass. Otherwise you're creating a new module with independent, randomly-initialized weights with each forward pass -- so the `.weight` of this new `Linear` module isn't really a part of the stored parameter state (i.e., `state_dict`) of your model since it disappears each time.
(And if you are doing something unusual involving modules that can only be defined at runtime, you should probably look at the `nn.functional` interface)

**Comment by apaszke** [comment]
Also, how can the module be possible detected before the forward pass if it doesn't even exist until then? It's 100% expected behaviour.

**Comment by apaszke** [comment]
You'll need to forward a single batch to ensure that the layers are added before reloading your model. I'd recommend parametrizing it by the input size in the constructor and creating modules there.

**Comment by anantzoid** [comment]
My Auxnet is a Maxout layer that permutes channel to last dimension, performs linear transformation, creates extra dimension and take max of it and then changes back dimension of channel:

```
class Maxout(nn.Module):
    def __init__(self, num_pieces):
        super(Maxout, self).__init__()
        self.num_pieces = num_pieces

    def forward(self, input):
        input = input.permute(0, 2, 3, 1)
        shape = input.size()
        self.linear = nn.Linear(shape[-1], shape[-1] * self.num_pieces, bias=False)
        if isinstance(input.data, torch.cuda.FloatTensor):
            self.linear.cuda()

        input = self.linear(input.contiguous().view(-1, shape[-1])).view(
                                shape[0], shape[1], shape[2], shape[3] * self.num_pieces)
        shape = input.size()
        num_filters = shape[-1] // self.num_pieces
        new_shape = shape[:-1] + (num_filters, self.num_pieces)
        last_dim = len(new_shape) - 1
        m,i = input.contiguous().view(*new_shape).max(last_dim)
        return m.squeeze(last_dim).permute(0, 3, 1, 2)
```

Should I be using the `nn.functional` interface for this?

**Comment by anantzoid** [comment]
@apaszke Thanks!

**Comment by apaszke** [comment]
I don't really know what's your plan. As @jekbradbury noticed, you're reinitializing the layer at every forward. You probably want to do sth like that:
```python
class Maxout(nn.Module):
    def __init__(self, num_pieces, input_shape):
        super(Maxout, self).__init__()
        self.num_pieces = num_pieces
        self.linear = nn.Linear(input_shape, input_shape * num_pieces, bias=False)

    def forwad(self, input):
        # here you can use self.linear
```

**Comment by ashdtu** [comment]
`print('Accuracy of the network on the 10000 test images: %d %%' % (
    100 * correct / total))`
