### ISSUE TITLE
[feature request] Convert "indices" variable in "torch.utils.data.dataset.random_split" to list 

### ISSUE THREAD

**Issue by floatn** [pytorch/pytorch#9211]
## Issue description
random_split fills indices variable using torch.randperm function, which returns tensor. Through Subset class its values goes to Dataset.__getitem__. If I override getitem, tensor values are ok for indexing list, but with pandas DataFrame it raises TypeError. Maybe it would be better to convert indices to list variable at start.
## Code example
df = pd.DataFrame([1, 2])
tn = torch.tensor([0, 1])
df.iloc[tn[0]]
...
...
TypeError: len() of unsized object

**Comment by fmassa** [comment]
I think we can just add a `.tolist()` after [the code in here](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataset.py#L120). Could you send a PR?

**Comment by floatn** [comment]
Done. #9237 .

**Comment by soumith** [comment]
closed via the discussion in #9237
