### ISSUE TITLE
Add strict mode to functional_call

### ISSUE THREAD

**Issue by albanD** [pytorch/pytorch#92153]
As described in https://github.com/pytorch/pytorch/issues/49171#issuecomment-1374091277 today, extra keys are simply ignored.
We should have mode that makes it an error (similar to the strict mode in load_state_dict).

cc @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @zou3519 @Chillee @samdow @soumith

**Comment by ain-soph** [comment]
I can help working on a PR if any help is needed.

**Comment by albanD** [comment]
A PR adding this new kwarg (disabled by default) would be very welcome!

**Comment by jbschlosser** [comment]
The `strict` arg for `load_state_dict()` checks for both unexpected and missing keys.

Should we follow that here? Is there any value in erroring for unexpected keys only (say the user wants to swap only a subset of the parameters)?
