### ISSUE TITLE
Generator: when I want to use a  new backend, how to create a Generator with the  new backend?

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#92202]
### 🐛 Describe the bug

 I want to add a new backend, so I add my backend  by referring to this tutorial.  https://github.com/bdhirsh/pytorch_open_registration_example

But how to create a Generator with my new backend ?
I see the code related to 'Generator' is in the file, https://github.com/pytorch/pytorch/blob/master/torch/csrc/Generator.cpp

static PyObject* THPGenerator_pynew(
    PyTypeObject* type,
    PyObject* args,
    PyObject* kwargs) {
  HANDLE_TH_ERRORS
  static torch::PythonArgParser parser({"Generator(Device device=None)"});
  torch::ParsedArgs<1> parsed_args;
  auto r = parser.parse(args, kwargs, parsed_args);
  auto device = r.deviceWithDefault(0, at::Device(at::kCPU));

  THPGeneratorPtr self((THPGenerator*)type->tp_alloc(type, 0));
  if (device.type() == at::kCPU) {
    self->cdata = make_generator<CPUGeneratorImpl>();
  }
#ifdef USE_CUDA
  else if (device.type() == at::kCUDA) {
    self->cdata = make_generator<CUDAGeneratorImpl>(device.index());
  }
#elif USE_MPS
  else if (device.type() == at::kMPS) {
    self->cdata = make_generator<MPSGeneratorImpl>();
  }
#endif
  else {
    AT_ERROR(
        "Device type ",
        c10::DeviceTypeName(device.type()),
        " is not supported for torch.Generator() api.");
  }
  return (PyObject*)self.release();
  END_HANDLE_TH_ERRORS
}

So how to create a Generator  with my new backend named "privateuseone" ? 

### Versions

new backend 
python:3.7.5 
pytorch: 2.0.0
CUDA: None

**Comment by bdhirsh** [comment]
@heidongxianhua thanks for filing the issue! It looks like the code in that file needs to be updated to also account for the PrivateUse1 DeviceType, here: https://github.com/pytorch/pytorch/blob/3aa6cec18cf662913e0625d539945ee5ee6406f0/torch/csrc/Generator.cpp#L72. We would accept a PR fixing that!

**Comment by heidongxianhua** [comment]
> @heidongxianhua thanks for filing the issue! It looks like the code in that file needs to be updated to also account for the PrivateUse1 DeviceType, here:
> 
> https://github.com/pytorch/pytorch/blob/3aa6cec18cf662913e0625d539945ee5ee6406f0/torch/csrc/Generator.cpp#L72
> 
> . We would accept a PR fixing that!

ok I will give a PR soon, thank your reply.

**Comment by heidongxianhua** [comment]
> @heidongxianhua thanks for filing the issue! It looks like the code in that file needs to be updated to also account for the PrivateUse1 DeviceType, here:
> 
> https://github.com/pytorch/pytorch/blob/3aa6cec18cf662913e0625d539945ee5ee6406f0/torch/csrc/Generator.cpp#L72
> 
> . We would accept a PR fixing that!

ok  And I have push a PR, and you may forget to review it, haha. Could you please review it again? 
https://github.com/pytorch/pytorch/pull/93920

I will be very very excited to merge it to pytorch, haha.

**Comment by jick-nice** [comment]
My graphics card is AMD6700xt and I get an error when I run it, and Device type privateuseone is not supported for torch. Generator() api. Do you have any solution, thank you very much!
