### ISSUE TITLE
RuntimeError: derivative for aten::mps_linear_backward is not implemented

### ISSUE THREAD

**Issue by wooodswu** [pytorch/pytorch#92206]
### 🐛 Describe the bug

when I calculate the second  derivative of the model, using my MacBook Air with M1, the bug is shown as below
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/87766834/212471926-f4df0537-ac7e-42dc-b80e-a9d063314a14.png">

Another question: what amazes me most is that when I using the other computer with Windows PyTorch on cuda, the codes can run successfully...

I just want to know how to solve the problem on my MacBook shown in the picture above.

### Versions

     15 u_pred = model(f_tmp)
     16 du_df=torch.autograd.grad(outputs =u_pred, inputs = f_tmp,
     17                             grad_outputs = torch.ones_like(u_pred).to(device),
     18                             create_graph = True,
     19                             allow_unused=True
     20                             )[0]
---> 21 ddu_ddf=torch.autograd.grad(outputs =du_df, inputs = f_tmp,
     22                             grad_outputs = torch.ones_like(du_df).to(device),
     23                             create_graph = True,
     24                             allow_unused=True
     25                             )[0]

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @kulinseth @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by albanD** [comment]
Hey!
We need to add a derivative formula for the linear_backward that was added (in derivatives.yaml). We should make it composite (not a native function) such that it is infinitely differentiable.
We would accept a PR adding this!

**Comment by mukurgupta** [comment]
I'm still facing this issue. Did anyone find a fix?

**Comment by jakesanghavi** [comment]
Same here. Still having the issue with PyTorch 2.1.0, although now the error message is simply: RuntimeError: derivative for aten::linear_backward is not implemented.

I only get this error if I move the data to mps, it works if I do not.

**Comment by enewhuis** [comment]
Me three.  :)

**Comment by pedro-sousamartins** [comment]
... and me four... with PyTorch 2.1.0 and error, 'RuntimeError: derivative for aten::linear_backward is not implemented
' as reported by @jakesanghavi

**Comment by albanD** [comment]
I'm very confused here... 
@qqaatw could you double check if the double backward formula we added works fine. I do see it in derivatives.yaml so not sure how this would not work.

**Comment by qqaatw** [comment]
Hi @mukurgupta @jakesanghavi @enewhuis @pedro-sousamartins, can you provide a minimal reproducer for this issue?

**Comment by jakesanghavi** [comment]
> Hi @mukurgupta @jakesanghavi @enewhuis @pedro-sousamartins, can you provide a minimal reproducer for this issue?

Here is my stab at a MWE, hopefully this is suitable: [https://github.com/jakesanghavi/jakesanghavi/blob/main/pytorch_bug.py](https://github.com/jakesanghavi/jakesanghavi/blob/main/pytorch_bug.py)

**Comment by qqaatw** [comment]
Hi @jakesanghavi, I just tested your script, `pytorch_bug.py`, and it worked without the error. 

Can you paste the output of the script below?

```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by julsanmer** [comment]
I've been suffering this same issue when trying to train physics informed neural networks with M1. I'm not able to make the training work on 'mps' but works fine on 'cpu'. I suspect something does not allow to do the backward call if the loss depends on a gradient w.r.t. input data (in my case). 

@jakesanghavi bug script does not work on my end: 
RuntimeError: derivative for aten::linear_backward is not implemented

which is the usual error I get. My output for @qqaatw script is:

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.9.11 (v3.9.11:2de452f8bf, Mar 16 2022, 10:44:40)  [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-13.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.1
[conda] Could not collect

**Comment by jakesanghavi** [comment]
> Hi @jakesanghavi, I just tested your script, `pytorch_bug.py`, and it worked without the error.
> 
> Can you paste the output of the script below?
> 
> ```
> wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
> # For security purposes, please check the contents of collect_env.py before running it.
> python collect_env.py
> ```

I'm sorry, I lost this email notification in my inbox. Below is the complete raw output. I am using a Jupyter Notebook.

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.0 (arm64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch                   2.0.1           gpu_mps_py310h20d1048_0  
[conda] torch                     2.1.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

**Comment by qqaatw** [comment]
Hi @julsanmer and @jakesanghavi, the commit is not in the PyTorch `2.0` release branch, can you upgrade to `2.1` and try again?

```
(pytorch_source) qqaatw@allans-mbp pytorch % git branch -r --contain 7776653a0cd63fb446b095ab8684368640dd4493 |grep release/
  upstream/orig/release/2.1
  upstream/release/2.1
```

**Comment by julsanmer** [comment]
It works with 2.1. Thank you @qqaatw !
