### ISSUE TITLE
Pytorch worker status on preempted pods

### ISSUE THREAD

**Issue by asm582** [pytorch/pytorch#92214]
### 🐛 Describe the bug

We are running Pytorch with multiple workers on Kubernetes. In our setup, one Pytorch worker is one pod. When one of the pod is preempted by Kubernetes, PyTorch reports that one of the workers was killed by SIGKILL. 

For our use case, we need the ability to differentiate between workers getting preempted by Kubernetes. 

is it possible to propagate preemption status in the `Message` field when one does `oc describe pytorch <job-name>` ?

### Versions

1.13.1

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by fduwjj** [comment]
I am not sure if I get this completely. Are you referring to the message in RPC or the error message?

**Comment by asm582** [comment]
Hi @fduwjj, I think preemption is not an error. In Kubernetes, such events are communicated in the `status` block. Whenever Kube-scheduler decides to preempt pod we would like the job status to be preempted instead of failed.
