### ISSUE TITLE
CapabilityBasedPartitioner incorrectly sorts the graph, causing optimizer return/output node to be first

### ISSUE THREAD

**Issue by kbadz-pl** [pytorch/pytorch#92245]
### 🐛 Describe the bug

Hello. I prepared code to test custom backends for torch.compile functionality. One of the things my backend is doing is using fx.Interpreter to go through all operations (via fake tensors) and propagate device info. Then I use this information to cluster some of the operations via CapabilityBasedPartitioner. For purpose of this bug I have simplified the code, it is available here:
https://gist.github.com/kbadz-pl/9bff0459fa37f4231125c0163aec4b89

Issue is that when I try to run partitioning and merging over optimizer code, it seems to wrongly treat return/output node because it has no arguments/predecessors. It ends up being first and effectively causing optimizer to not run at all (checked in the run traces).

SGD graph before partitioning:
![image](https://user-images.githubusercontent.com/122799060/212693505-fb75ea68-d5eb-4c90-943c-e496b900f38e.png)

SGD graph after partitioning and merging:
![image](https://user-images.githubusercontent.com/122799060/212693793-df170ca8-5315-4809-8e64-6376e44482b4.png)

### Versions

PyTorch version: 2.0.0.dev20230116+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230116+cpu
[pip3] torchaudio==2.0.0.dev20230115+cpu
[pip3] torchvision==0.15.0.dev20230115+cpu
[conda] Could not collect

cc @ezyang @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv @msaroufim @wconstab @ngimel @bdhirsh

**Comment by bdhirsh** [comment]
My guess is that the `CapabilityBasedPartitioner` assumes a functional graph (cc @SherlockNoMad ?).

One option is to use `aot_module_simplified/aot_function_simplified` from aot_autograd, which will functionalize the graph (and convert mutated inputs to graph outputs, and perform the input mutations in an epilogue), which would side-step the issue of "the graph returns no outputs".

**Comment by kbadz-pl** [comment]
```
def custom_aot_backend(gm, example_inputs):
    functorch.compile.config.use_functionalize = True
    functorch.compile.config.use_fake_tensor = use_fake
    return aot_autograd(
        fw_compiler=custom_compiler_inner,
        bw_compiler=custom_compiler_inner,
    )(gm, example_inputs)
```

I have something like this in the code. I set use_functionalize to True, and even with it I get graph without output for optimizer. All isn't that enough to functionalize the graph?

**Comment by ezyang** [comment]
Is it possible that none of your inputs require grad? There is a known bug that we don't functionalize in that case

**Comment by kbadz-pl** [comment]
I'm not sure how to asnwer that queston. This is the topology from linked sample:
![image](https://user-images.githubusercontent.com/122799060/213388621-9861db74-9e49-4016-9043-528a35f7b0bb.png)

It have normal forward and backward graphs and they just work according to logs. It's just the optimizer part that have this issue - maybe optimizer graph inputs do not require grad and this is the cause that it's not functionalized? Even if so, we would still want to functionalize optimizers as well, right?

**Comment by bdhirsh** [comment]
Oh, this probably won't trigger the functionalization code path in AOT Autograd (we're working on that, see https://github.com/pytorch/pytorch/issues/90759).

As a workaround, you should be able to compile just the forward + backward (minus the optimizer step), using:
```
model_compiled = torch.compile(model, backend=custom_aot_backend)

def iteration(x, y):
    optimizer.zero_grad()
    result = model_compiled(x)
    loss = result.sum().abs()
    loss.backward()
    optimizer.step()
    return loss, result
```

FWIW, "full_graoh_compiled" above won't actually compile fwd + bwd + optimizer into a single graph, because dynamo graph breaks on .backward() calls today.

**Comment by kbadz-pl** [comment]
Got it, thanks. 

Looking forward for this getting addressed then!

**Comment by williamwen42** [comment]
Is this still broken? `torch.compile` support for optimizers has since been added. 

I have an updated repro here: https://gist.github.com/williamwen42/f97f02e266e0e5ca79c71b6085e1e848. I don't see any more `return ()` statements.

**Comment by bdhirsh** [comment]
The issue I mentioned above (not functionalizing in the inference case) was fixed a few months later. So if that was indeed the issue, then it should be fixed
