### ISSUE TITLE
Infinite recursion when tracing through lift_fresh_copy OP in Adam optimizer

### ISSUE THREAD

**Issue by kbadz-pl** [pytorch/pytorch#92244]
### 🐛 Describe the bug

Hello. I prepared code to test custom backends for torch.compile functionality. One of the things my backend is doing is using fx.Interpreter to go through all operations (via fake tensors) and propagate device info. Then I use this information to cluster some of the operations via CapabilityBasedPartitioner. For purpose of this bug I have simplified the code, it is available here: https://gist.github.com/kbadz-pl/53d6cf36ac467039a0fa3170e7d5157b

Issue is that when fx.Interpreter tries to run_node over **lift_fresh_copy** operation, it goes into infinite recursion and crashes.
![image](https://user-images.githubusercontent.com/122799060/212691735-68ec7688-4733-4b76-ab0b-030bac53c9f8.png)

I did not see such issue with other OPs. Issue does not occur for example for SGD (it does not contain such OP) or by disabling fake tensors. You can test it by changing to SGD in line 106 or disabling fake tensors in line 15 of my file.

### Versions

PyTorch version: 2.0.0.dev20230116+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230116+cpu
[pip3] torchaudio==2.0.0.dev20230115+cpu
[pip3] torchvision==0.15.0.dev20230115+cpu
[conda] Could not collect

cc @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @eellison @soumith @ngimel

**Comment by bdhirsh** [comment]
It looks like the error is because when `FakeTensorMode` encounters a lift operator (like `lift_fresh_copy`), it expects the input to be a real tensor, that it can treat as a constant in the graph (backed by real data, in case the user e.g. calls .item() on it later). There's a note for that here: https://github.com/pytorch/pytorch/blob/f65945200985cb863d6cd4a654b323bcb8e0a93e/torch/_subclasses/fake_tensor.py#L786

Is there a reason that you need to manually fakeify in your backend? The example inputs passed to you through torch.compile should already be fake (except for... graph constants like the above lift_fresh_copy example, and potentially module params).

**Comment by kbadz-pl** [comment]
Yeah, so I use the same backend for FWD, BWD and optimizer. And from what I've seen the BWD part sometimes got non-fake inputs (maybe that's a real bug here?). This is why now I just make sure everything is fake.

As I understand the solution for that should be to not fakeify lift_fresh_copy inputs. Is there any other OP with such constraint?

**Comment by kbadz-pl** [comment]
Update:

This discussion inspired me, so I did following:
1. When I detect that example_inputs are not in fake_mode (in bwd graph), I `deepcopy_to_fake_tensor` them and then use resulting tensor to propagate device info.
```
    fake_mode = fake_mode_from_tensors(example_inputs)
    if fake_mode is None:
        fake_mode = torch._subclasses.FakeTensorMode()
        fake_inputs = deepcopy_to_fake_tensor(example_inputs, fake_mode)
    else:
        fake_inputs = example_inputs
        
    DeviceProp(gm, fake_mode).propagate(*fake_inputs)
```
2. I removed my manual fakification of every input to every op and manual execution, now I just do:
```
with self.fake_mode:
    result = super().run_node(n)
```

With that, I no longer get infinite recursion. Is it valid approach @bdhirsh ? Also, what will happen with optimizer in such case? I don't `deepcopy_to_fake_tensor` the whole module like in example ShapeProp because it causes infinite recursion again. Won't it cause update on real Parameters? 

Thanks.

**Comment by eellison** [comment]
Ughhh, I think there was a small memory increase when I did that, that I didn't look into further at the time. We can try to turn it on but let's resolve https://github.com/pytorch/pytorch/issues/92659 first 😢

**Comment by eellison** [comment]
You know, it's very possible I was confused that I didn't observe memory reduction in  https://github.com/pytorch/pytorch/pull/88248 because I was running on a fresh build versus one that already had a cached kernels. Either way we should check before re-enabling.

**Comment by eellison** [comment]
This no longer repros. I had to update it a little bit for outdated apis.

```
import random

import torch
import torch.nn as nn

import functorch

import torch._dynamo
from torch._dynamo.backends.common import aot_autograd
# from torch._dynamo.optimizations.training import aot_autograd as aot_autograd
# from torch._dynamo.utils import fake_mode_from_tensors
from torch._guards import detect_fake_mode

from torch.fx.passes.infra.partitioner import CapabilityBasedPartitioner
from torch.fx.passes.operator_support import OperatorSupport

# PART 1 - define custom backend
use_fake = True # Change to False to not use fake mode and make infinite recursion disappear
class DeviceProp(torch.fx.Interpreter):
    def __init__(self, gm, fake_mode = None):
        super().__init__(gm)
        if fake_mode is None:
            fake_mode = torch._subclasses.FakeTensorMode()
        self.fake_mode = fake_mode

    def run_node(self, n):
        print("Node:", n, " Op:", n.op, "Target:", n.target)
        
        if not use_fake:
            result = super().run_node(n)
        else:
            with self._set_current_node(n):
                args, kwargs = self.fetch_args_kwargs_from_env(n)
                new_args = []
                assert self.fake_mode
                for arg in args:
                    if isinstance(arg, torch.Tensor) and not isinstance(
                        arg, torch._subclasses.FakeTensor
                    ):
                        new_args.append(self.fake_mode.from_tensor(arg))
                    else:
                        new_args.append(arg)
            
                result = getattr(self, n.op)(n.target, new_args, kwargs)

        # Stuff related to device discovery
        # (...)
        
        return result

    def propagate(self, *args):
        return super().run(*args)

class MockOperatorSupport(OperatorSupport):
    def is_node_supported(self, submodules, node) -> bool:
        # Just mock for now, move all 'call_function' nodes into fused submodules.
        return node.op == "call_function"

def custom_compiler_inner(gm: torch.fx.GraphModule, example_inputs):
    print("####input FX graph:")
    gm.print_readable()
    
    # Take inputs' fake_mode and use it to trace through module and get actual devices placement
    fake_mode = detect_fake_mode(example_inputs)
    print("####FAKE_MODE: ", fake_mode)
    DeviceProp(gm, fake_mode).propagate(*example_inputs)
    
    # Use partitioner to partition out all necessary operations
    support_mock = MockOperatorSupport()
    partitioner = CapabilityBasedPartitioner(gm, support_mock, allows_single_node_partition=True)
    partitions = partitioner.propose_partitions()
    print("#### Partitions:")
    print(partitions)
    
    # Fuse these together again.
    fused_graph = partitioner.fuse_partitions(partitions)
    print("####fused FX graph:")
    fused_graph.print_readable()

    return functorch.compile.make_boxed_func(fused_graph.forward)

def custom_aot_backend(gm, example_inputs):
    # functorch.compile.config.use_functionalize = True
    # functorch.compile.config.use_fake_tensor = use_fake
    return aot_autograd(
        fw_compiler=custom_compiler_inner,
        bw_compiler=custom_compiler_inner,
    )(gm, example_inputs)

# PART 2 - define topology and iteration function.
num_classes = 10
learning_rate = 0.001

class MiniNetNoLinear(nn.Module):
    def __init__(self, num_classes):
        super().__init__()
        self.layer1 = nn.Conv2d(1, 256, kernel_size=2, stride=2, padding=0)
        self.relu1 = nn.ReLU()
        self.layer2 = nn.Conv2d(256, num_classes, kernel_size=2, stride=2, padding=0)

    def forward(self, x):
        out = self.layer1(x)
        out = self.relu1(out)
        out = self.layer2(out)
        
        return out

model = MiniNetNoLinear(num_classes)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate) # Change to SGD to make infinite recursion disappear
criterion = torch.nn.CrossEntropyLoss()

def iteration(x, y):
    optimizer.zero_grad()
    result = model(x)
    loss = result.sum().abs()
    loss.backward()
    optimizer.step()
    return loss, result

# PART 3 - compile and run

full_graph_compiled = torch.compile(iteration, backend=custom_aot_backend)

images = torch.rand(8, 1, 4, 4)
labels = torch.rand(8, 1)

for i in range(10):
    loss, _ = full_graph_compiled(images, labels)
    print("Iteration", i,":: Loss:", loss)
```
