### ISSUE TITLE
Unify Sampler API

### ISSUE THREAD

**Issue by funnym0nk3y** [pytorch/pytorch#92268]
### 🚀 The feature, motivation and pitch

I'm a torch beginner and recently learned to use samplers for Dataloaders. There I noticed that the API of the `RandomSampler` and the `WeightedRandomSampler` are very different. `WeightedRandomSampler` doesn't need a dataset, where as `RandomSampler` does. I'm still not sure if I understood it correctly. This all adds to the learning needed for understanding samplers, like how they work etc. 

It would be much easier if all the samplers had the same basic API (e.g. give it data and a number of samples return) and would only differ in sampler specific parameters like the weight samples for the sample distribution. 

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment]
The request to have a unified API makes sense to me.
We are welcome to accept any PR to unify them and still preserve the backward compatibility.
