### ISSUE TITLE
warn if batchsize < #gpu in data parallel

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9226]

**Comment by colesbury** [comment]
I'm not sure this should be a warning. It can happen at the end of an epoch where the left-over batch is much smaller.

**Comment by SsnL** [comment]
@colesbury solid point... uhh, I really want to have an actual code warning if people try to use DP with suboptimal batch size because it seems that many users don't really understand DP and just treat it as a blackbox.
