### ISSUE TITLE
ONNX expand and expand_as operators

### ISSUE THREAD

**Issue by sytelus** [pytorch/pytorch#9228]
Currently many graphs containing expand and expand_as operators fail to export to ONNX (for example, SSD model). Looking in to [onnx/symbolic.py](https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L234) we see `expand` implemented as:

```
# There is no translation for it, but we don't want to raise an error yet
def expand(g, self, size, implicit):
    return None
```

I'm wondering if this is complete implementation . Also, currently `expand_as` not implemented at all. Any idea how do we implement these two operators for ONNX?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment]
We do not have this file onnx/symbolic.py in the repo. Also I don't see this line anywhere either.
`# There is no translation for it, but we don't want to raise an error yet`

It seems like you may be using an older version of PyTorch. Could you please try with the latest version and reopen this issue if you see any issue? Thanks.
