### ISSUE TITLE
The shape inference of com.microsoft::MultiscaleDeformableAttnPlugin_TRT type is missing

### ISSUE THREAD

**Issue by liuxubit** [pytorch/pytorch#92293]
### 🐛 Describe the bug

Hello，
     when I use a fake op to export  .pth to .onnx, it's like:
![image](https://user-images.githubusercontent.com/39891612/212855795-731487b9-3cce-425c-9026-beb62ca78f60.png)
And I use it like:
![image](https://user-images.githubusercontent.com/39891612/212855992-3cc9cfd6-1b72-47bd-8fa3-7b41299d8dc7.png)
Then I transfer the model to onnx, the process says:
![image](https://user-images.githubusercontent.com/39891612/212856208-286de7d4-3703-4db5-81f0-a0b581c924b0.png)
And when I transfer .onnx to .engine(trt)，it will fail. 
Right now my solution is add a reshape like this:
![image](https://user-images.githubusercontent.com/39891612/212856511-b681fc21-3e7b-44bb-911e-c2b970c13ba6.png)
It can be done.
But I‘m wondering if there is a way to fix this problem without a reshape block

### Versions

torch1.10

**Comment by titaiwangms** [comment]
Hi @liuxubit ,

For custom Op, please make sure that you utilize the [`setType` API](https://pytorch.org/docs/stable/onnx.html#torch.onnx.register_custom_op_symbolic) and some usages can be found in https://github.com/pytorch/pytorch/blob/master/test/onnx/test_custom_ops.py

Please make sure that you use a latest version or a version at least after this [PR](https://github.com/pytorch/pytorch/pull/88622) which has a fix about setType API.
