### ISSUE TITLE
Evaluate whether libtorch Windows Arm64 binaries are working

### ISSUE THREAD

**Issue by Blackhex** [pytorch/pytorch#92304]
TBD

Scope: Create minimal "hello world" application using libtorch and test it on Volterra device.

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by iremyux** [comment]
Arm64 Libtorch debug and release versions have been tested using a simple C++ VS2022 project. In this project, basic torch functions and tensor operations were used. The results have been successful and we saw meaningful output.
