### ISSUE TITLE
[bazel] ERROR: infinite symlink expansion detected

### ISSUE THREAD

**Issue by vors** [pytorch/pytorch#92308]
### 🐛 Describe the bug

If you run (on recent master b05f509601b2f03819f5057e3ee4ab5ff4e97858)
```
bazel query //...
```

Instead of the query output, you will get

```
ERROR: infinite symlink expansion detected
[start of symlink chain]
/app/third_party/ittapi/rust/ittapi-sys/c-library
/app/third_party/ittapi
[end of symlink chain]
ERROR: Infinite symlink expansion, for third_party/ittapi/rust/ittapi-sys/c-library, skipping: Infinite symlink expansion
ERROR: Evaluation of query "//..." failed due to BUILD file errors
Loading: 20 packages loaded
```

I fixed a similar problem in the past in https://github.com/pytorch/pytorch/pull/78870
And now it came back again. This time the workaround applied previously doesn't work...

### Versions

b05f509601b2f03819f5057e3ee4ab5ff4e97858

cc @malfet @seemethere

**Comment by dagitses** [comment]
@vors have you figured out a workaround for this yet?

**Comment by dagitses** [comment]
OK, I have a fix. We can put third_party/ittapi/ in .bazelignore!
