### ISSUE TITLE
warn if user tries to build from source on windows & python 2.7

### ISSUE THREAD

**Issue by yes7rose** [pytorch/pytorch#9232]
install from source, run the test, i got error:

 File "D:\CashmereRuntime\Applications\python\2.7.11\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\CashmereRuntime\Applications\python\2.7.11\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "D:\CashmereRuntime\PythonLibraries\pytorch\0.4.0\lib\torch\utils\data\dataloader.py", line 92, in _worker_loop
    watchdog = ManagerWatchdog()
  File "D:\CashmereRuntime\PythonLibraries\pytorch\0.4.0\lib\torch\utils\data\dataloader.py", line 48, in __init__
    self.manager_pid = os.getppid()

**Comment by SsnL** [comment]
no, getppid is a thing. it stands for "get parent pid".

what's the error?

**Comment by yes7rose** [comment]
Python 2.7.11 (default, Jul  1 2016, 02:08:48) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getppid()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getppid'
>>> os.getpid()
22828

**Comment by yf225** [comment]
@yes7rose We don't support Python 2.7 on Windows, could you try with Python 3.6 instead?

**Comment by zou3519** [comment]
We should probably have a runtime warning if one runs on Windows under python 2.7

**Comment by Stonesjtu** [comment]
@zou3519 For the runtime check, we can just omit the python2.7 channel of pip on windows. If not supported, why provided.

**Comment by zou3519** [comment]
@yes7rose said he installed from source, so maybe we should have a check in setup.py that exits immediately on windows if python is 2.7

**Comment by Stonesjtu** [comment]
I thought #4226 has added the python2.7 support for windows, when did we drop that.

**Comment by yf225** [comment]
@Stonesjtu Support for Python 2.7 on Windows is still a work in progress, as there are a few tests that doesn't pass in https://github.com/pytorch/pytorch/pull/4226. @peterjc123 may be able to chime in for more information.

**Comment by yes7rose** [comment]
I am a TD in a 3D animation studio and we use Maya as main 3D software. Just now, all the industry software use Python2.7.x, so i have to build it from source, with the Maya version Python. Will pytorch for 2.7 support be Droped and when?  The using of Python2.7 in our studio will get to keep on at least 2 years, on Maya will use Python2.7 for a long time.

**Comment by soumith** [comment]
@yes7rose at the moment we dont have any plans to drop support for python 2.7 on Linux and OSX platforms. On Windows platform, we haven't supported 2.7 officially because of the reasons outlaid by peterjc123.
