### ISSUE TITLE
how do I freeze whole module with simple code

### ISSUE THREAD

**Issue by MrWanter** [pytorch/pytorch#9241]
Hi I googled freeze module, I only get something like 
https://discuss.pytorch.org/t/freeze-the-learnable-parameters-of-resnet-and-attach-it-to-a-new-network/949
which is for freeze some defined sequentials in the module, however if I have a complex module and would like to freeze whole module, how to do it quickly, I tried 
```
 for param in my_module.parameters():
      param.requires_grad = False
```
but this seems not work, is my code right?

**Comment by MrWanter** [comment]
this actually works, sorry

**Comment by soumith** [comment]
please use https://discuss.pytorch.org for questions
