### ISSUE TITLE
[pytorch] [feature request] torch.eye_like

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9244]
Would be useful for regularisation code.

Currently, to create an identity matrix on the same device we need to pass both `device` and `dtype` explicitly to `torch.eye`.

Maybe all dimensions except the last two, can be considered as batch dimensions.

**Comment by vishwakftw** [comment]
Something like this should do:
```python
def eye_like(tensor):
    return torch.eye(*tensor.size(), out=torch.empty_like(tensor))
```

**Comment by vadimkantorov** [comment]
I am proposing to add a simple helper like this into core to complete existing `ones_like`, `zeros_like` etc

**Comment by vishwakftw** [comment]
I am sending in a PR.

**Comment by soumith** [comment]
closing. See discussion on #9281 on why we wont implement this.

**Comment by vadimkantorov** [comment]
Given the `dim1`, `dim2` pattern in `torch.diagonal`, `torch.diag_embed`, can this be reconsidered?

**Comment by vadimkantorov** [comment]
It seems that ONNX has EyeLike op :)

https://github.com/pytorch/pytorch/pull/41357

**Comment by Pedrexus** [comment]
Hello all, any update on this issue? Could it really be reconsidered?

**Comment by ACMCMC** [comment]
<img src="https://i.imgflip.com/9pr0tr.jpg" title="made at imgflip.com"/>
