### ISSUE TITLE
[pytorch] [docs] torch.trtrs works in fact on CUDA contrary to docs

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9247]
https://pytorch.org/docs/master/torch.html#torch.trtrs mentions "This method is NOT implemented for CUDA tensors."

but following doesn't break:
```python
a = torch.Tensor(512, 64).cuda()
b = torch.Tensor(512, 512).cuda()
torch.trtrs(a, b)[0].shape
```

Obsolete documentation?

**Comment by SsnL** [comment]
fixed via #9239
