### ISSUE TITLE
Transpose/Permute + MaxPool = MPSNDArrayPooling Error

### ISSUE THREAD

**Issue by joaopalotti** [pytorch/pytorch#92531]
### 🐛 Describe the bug

The issue happens when using MaxPool after a transpose operation:

Error is:
```base
/AppleInternal/Library/BuildRoots/5b8a32f9-5db2-11ed-8aeb-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArrayPooling.mm:1956: failed assertion `Error: destination values and indices length mismatch along axis 0'
```

You should be able to reproduce it by running this on a Mac M1 using MPS as a device:

```python
import torch

device = "mps"
m = torch.nn.MaxPool1d(3, stride=2).to(device)
input = torch.randn(20, 16, 50, device=device)


print("Shape: ", input.shape)
print("Shape: ", m(input).shape)
print("Shape: ", m(input.transpose(1,2)).shape)
```

Potentially linked to #88183 as when I add `.clone(memory_format=torch.contiguous_format)` the code at least executes:

```python
print("Shape: ", m(input.transpose(1,2).clone(memory_format=torch.contiguous_format)).shape)
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (arm64)
GCC version: (Homebrew GCC 12.2.0) 12.2.0
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.24.1
Libc version: N/A

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:48:25)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] numpy                     1.23.5           py39hefdcf20_0    conda-forge
[conda] pytorch                   1.13.1                  py3.9_0    pytorch
[conda] torchaudio                0.13.1                 py39_cpu    pytorch
[conda] torchvision               0.14.1                 py39_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by razarmehr** [comment]
Thanks for reporting the issue. I'm not able to reproduce this with the latest nightly build, and I get the following output from the test code you sent. Most probably the #94348 has fixed the issue. Please try the latest nightly build and feel free to reopen the issue if you see it again. Thank you. 
```
>>> print("Shape: ", input.shape)
Shape:  torch.Size([20, 16, 50])
>>> print("Shape: ", m(input).shape)
Shape:  torch.Size([20, 16, 24])
>>> print("Shape: ", m(input.transpose(1,2)).shape)
Shape:  torch.Size([20, 50, 7])
```
