### ISSUE TITLE
Spurious side effect diff when cond branches call different functions in outer scope

### ISSUE THREAD

**Issue by avikchaudhuri** [pytorch/pytorch#92561]
### 🐛 Describe the bug

Consider the following code where we're calling `cond` with branches `shallow` and `deep`, such that `deep` references functions in outer scope that `shallow` doesn't.

```python
class Module(torch.nn.Module):
    def forward(self, pred, x):
        return self.indirection(pred, x)

    def indirection(self, pred, x):
        def true_fn(y):
            return y + 2

        def false_fn(y):
            return y - 2

        def shallow(x):
            return x * 2

        def deep(x):
            return cond(
                x[0][0] > 0,
                true_fn,
                false_fn,
                [x],
            )

        return cond(pred, shallow, deep, [x])
```

Trying to export this code leads to an exception:
```
<snip>
  File "<snip>/torch/_dynamo/variables/torch.py", line 831, in call_function
    unimplemented(true_cmp.diff(false_cmp))
  File "<snip>/torch/_dynamo/exc.py", line 67, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: id_to_variable keys: odict_keys([140465014772608, 140465014771968, 140465014772496]) != odict_keys([])
```

### Versions

PyTorch version: 1.14.0a0+gited9cd47
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.13 (main, Aug 25 2022, 18:29:29)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.4.0
[pip3] torch==1.14.0a0+gited9cd47
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-include               2022.1.0           hecd8cb5_209
[conda] mkl-service               2.4.0            py39h9ed2024_0
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0
[conda] mkl_random                1.2.2            py39hb2f4e1b_0
[conda] numpy                     1.21.5           py39h2e5f0a9_3
[conda] numpy-base                1.21.5           py39h3b1a694_3
[conda] numpydoc                  1.4.0            py39hecd8cb5_0
[conda] torch                     1.14.0a0+gited9cd47           dev_0    <develop>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by williamwen42** [comment]
Repro no longer fails - closing as fixed.
