### ISSUE TITLE
ModuleNotFoundError: No module named 'peachpy.x86_64.avx'

### ISSUE THREAD

**Issue by jiapei100** [pytorch/pytorch#9257]
```
[ 72%] Built target onnx
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "....../peachpy/x86_64/__init__.py", line 25, in <module>
    from peachpy.x86_64.function import Function, LocalVariable
  File "....../peachpy/x86_64/function.py", line 16, in <module>
    import peachpy.x86_64.avx
ModuleNotFoundError: No module named 'peachpy.x86_64.avx'
confu-deps/NNPACK/CMakeFiles/nnpack.dir/build.make:64: recipe for target 'confu-deps/NNPACK/src/x86_64-fma/2d-fourier-8x8.py.o' failed
make[2]: *** [confu-deps/NNPACK/src/x86_64-fma/2d-fourier-8x8.py.o] Error 1

```

Can anybody just give out a manual, how to successfully build **pytorch** with **caffe2** after **caffe2** is integrated into **pytorch**？

Thank you

**Comment by pjh5** [comment]
Are you submodules fully updated? Use `git submodule update --init --recursive` to update them.

We are trying to keep the exact same installation instructions working as we integrate Caffe2 into Pytorch. For example, `python setup.py install` will still install Pytorch correctly. If you also want to build Caffe2, then you can use `FULL_CAFFE2=1 python setup.py install` to build all of Caffe2 along with Pytorch.

**Comment by llv22** [comment]
@jiapei100 
[orlando-for-patch-torch1.8-mac.patch.txt](https://github.com/pytorch/pytorch/files/5436600/orlando-for-patch-torch1.8-mac.patch.txt)
change orlando-for-patch-torch1.8-mac.patch, then apply it. 
This is caused by installation for submodule peachpy, but in cmake no instruction generation has been triggered.

**Comment by izdeby** [comment]
Please, use our [forums](http://discuss.pytorch.org/) for questions. thank you
