### ISSUE TITLE
memory leak for PyTorch -> dlpack -> CuPy

### ISSUE THREAD

**Issue by t-vi** [pytorch/pytorch#9261]
Hi again,

for this one, I'm not sure whether it is a cupy or pytorch issue, either, but I don't think this should run out of memory:
```
import cupy
import torch.utils.dlpack
import gc
for i in range(10000):
  b = torch.randn(1000,1000, device='cuda')
  a = cupy.fromDlpack(torch.utils.dlpack.to_dlpack(b))
  gc.collect()
```
`torch.cuda.memory_allocated()` will be high. Again it could be a refcounting thing that things are not going out of scope properly. (In which case it would be more of a CuPy issue.)

Best regards

Thomas

**Comment by ezyang** [comment]
Does it leak if you omit `cupy.fromDlpack`? If so, sounds like a cupy issue. PyTorch's `to_dlpack` function returns a capsule, and from there it's cupy's job to make sure they free it when they're done with it.

**Comment by t-vi** [comment]
My impression is that CuPy implements a contract to be similar to the numpy/PyTorch sharing of data and PyTorch doesn't and instead interprets the contract you describe .

I must admit that I haven't seen the specs to argue about it but intuitively, the CuPy implementation makes much more sense to me.

I can still access a tensor I pass to to_dlpack. What happens with that when CuPy decides it doesn't need the capsule anymore?

**Comment by t-vi** [comment]
So I think that the problem here is that CuPy doesn't call the deleter.
I'll submit a PR to CuPy.

**Comment by t-vi** [comment]
CuPY PR: https://github.com/cupy/cupy/pull/1445
