### ISSUE TITLE
FakeTensor with device='cuda' fails on .backward()

### ISSUE THREAD

**Issue by aazzolini** [pytorch/pytorch#92627]
### 🐛 Describe the bug

The following valid code errors out:

```python
import torch
from torch._subclasses.fake_tensor import FakeTensorMode

if __name__ == '__main__':
    torch.cuda.set_device(0)
    # torch.set_default_device('cuda')
    with FakeTensorMode():
        p = torch.randn(4, 2, requires_grad=True, device='cuda')
        x = torch.randn(8, 4, device='cuda')
        y = torch.mm(x, p).square().sum()
        y.backward()
```

Stack trace:

```
Traceback (most recent call last):
  File "/fsx/users/azzolini/conda/envs/pt/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/fsx/users/azzolini/conda/envs/pt/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/fsx/users/azzolini/ptwork/tau/experimental/test_fake_backward.py", line 16, in <module>
    debug_fake_backwards()
  File "/fsx/users/azzolini/ptwork/tau/experimental/test_fake_backward.py", line 12, in debug_fake_backwards
    pg, = torch.autograd.grad(y, p)
  File "/fsx/users/azzolini/ptwork/pytorch/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Event device type CUDA does not match blocking stream's device type CPU.
Exception raised from block at /fsx/users/azzolini/ptwork/pytorch/c10/core/impl/InlineEvent.h:89 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f19519b4cdb in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xbf (0x7f19519afb1f in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + 0x3dc113e (0x7f195f1e013e in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x3db89b6 (0x7f195f1d79b6 in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x3dba7ef (0x7f195f1d97ef in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x1ea (0x7f195f1def2a in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x99 (0x7f195f1d55d9 in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x6c (0x7f19660ca62c in /fsx/users/azzolini/ptwork/pytorch/torch/lib/libtorch_python.so)
```

Creating a concrete cuda tensor beforehand fixes the issue. Specifically I added this on the firts line and the program ran fine afterwards.
```
torch.randn(1, device='cuda')
```
FRom @bdhirsh : 
"fwiw - it seems like the autograd engine expects some cuda context to be initialized by time you run the backward, but it hasn't yet. I tried allocating a cuda tensor at the beginning of your repro, and the error went away".

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+git1ca9d43
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~18.04) 9.4.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.25.0
Libc version: glibc-2.27

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-1069-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.991
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==2.0.0a0+git469c14c
[conda] blas                      1.0                         mkl
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-include               2022.1.0           h06a4308_224
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.4           py39h14f4228_0
[conda] numpy-base                1.23.4           py39h31eccc5_0
[conda] torch                     2.0.0a0+git469c14c           dev_0    <develop>

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @ngimel

**Comment by eellison** [comment]
cc @albanD, do you have any idea what cuda state needs to be initialized before backward ?

**Comment by albanD** [comment]
During the backward, we assume that the full cuda context is initialized (since you must have done a full forward on cuda already).
In this repro, adding a `torch.rand(2, device="cuda")` before the mode fixes the issue.
Not sure why that leads to recording a CPU stream haha

**Comment by eellison** [comment]
@albanD yea I just make fake tensor create a cuda tensor once and it fixed the issue. we could separately expose whatever apis are needed to initialize cuda context but i dont know if its worth it.
