### ISSUE TITLE
DLL load failed: The specified module could not be found. After installed using pip in python 3.5 windows.

### ISSUE THREAD

**Issue by JafferWilson** [pytorch/pytorch#9263]
I am using windows 10 OS with Python 3.5.
I am trying to run a program related to torch. So I installed Pytorch with the help of the instructions specified on their website:[ Pytorch installation](https://pytorch.org/)

See the following image for selection of the downloadable:
![pytorch](https://user-images.githubusercontent.com/13446197/42447420-7271a044-8397-11e8-98b1-db55469a787a.PNG)

I installed it using :

```
pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-win_amd64.whl 
pip install torchvision
```
I have encountered the following error:
```

Error
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\twisted\trial\runner.py", line 701, in findByName
    __import__(name)
  File "C:\Users\aims\Desktop\CNN\source\cnn4matrix.py", line 4, in <module>
    import torch
  File "C:\Python35\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\twisted\trial\runner.py", line 803, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "C:\Python35\lib\site-packages\twisted\trial\runner.py", line 704, in findByName
    return self.loadFile(_name, recurse=recurse)
  File "C:\Python35\lib\site-packages\twisted\trial\runner.py", line 674, in loadFile
    module = SourceFileLoader(name, fileName).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\aims\Desktop\CNN\source\cnn4matrix.py", line 4, in <module>
    import torch
  File "C:\Python35\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```
After searching a lot I couldn't found anything related. Instead I found that I have tried: Reinstall with upgrade mode, the numpy library. But my efforts were in vain.

Please let me know what I can try.  

I have just tried this: `import torch`

**Comment by peterjc123** [comment]
@JafferWilson Have you tried https://gist.github.com/peterjc123/6b804651288e76db7b5fabe5348e1f03?

**Comment by JafferWilson** [comment]
@peterjc123  Might work. But I m not using Anaconda. I have mention this in the titl. You can see: DLL load failed: The specified module could not be found. After **installed using pip in python 3.5 windows**.

**Comment by peterjc123** [comment]
@JafferWilson Yes, there is `For wheels package` in that passage. Could you please try `pip install intel-openmp` first?

**Comment by JafferWilson** [comment]
Sure let me try it out.

**Comment by JafferWilson** [comment]
I tried it see the result: 
```
C:\Users\aims>pip install intel-openmp
Collecting intel-openmp
  Downloading https://files.pythonhosted.org/packages/92/6e/13102aa9d378966f870f28851f18d76de23aa875f19c582fdbf68ac7946f/intel_openmp-2018.0.3-py2.py3-none-win_amd64.whl (1.9MB)
    100% |################################| 1.9MB 2.4MB/s
Installing collected packages: intel-openmp
Successfully installed intel-openmp-2018.0.3

C:\Users\aims>python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by peterjc123** [comment]
@JafferWilson, what about `pip install numpy mkl`? If that doesn't help, then you may the environmental variable `PATH`. Make sure it points to the following locations:
```
[PythonRoot]
[PythonRoot]\Library\bin
[PythonRoot]\Scripts
[PythonRoot]\bin
%SYSTEMROOT%
```

**Comment by JafferWilson** [comment]
Ok Let me give it a try.

**Comment by mhusseinsh** [comment]
hello @JafferWilson did you solve your problem ? I already have the same

**Comment by JafferWilson** [comment]
@mhusseinsh No sir it didn't work for me the same error.

**Comment by JafferWilson** [comment]
```
C:\Users\aims>where python.exe
C:\Python35\python.exe
C:\Users\aims\Anaconda3\python.exe

C:\Users\aims>where pip.exe
C:\Python35\Scripts\pip.exe
C:\Users\aims\Anaconda3\Scripts\pip.exe

C:\Users\aims>where libiomp5md.dll
C:\Users\aims\Anaconda3\Library\bin\libiomp5md.dll

C:\Users\aims>where mkl_rt.dll
C:\Users\aims\Anaconda3\Library\bin\mkl_rt.dll

C:\Users\aims>where msvcp140.dll
C:\Windows\System32\msvcp140.dll
C:\Users\aims\Anaconda3\msvcp140.dll
C:\Users\aims\Anaconda3\Library\bin\msvcp140.dll

C:\Users\aims>where api-ms-win-crt-utility-l1-1-0.dll
C:\Users\aims\Anaconda3\api-ms-win-crt-utility-l1-1-0.dll
C:\Users\aims\Anaconda3\Library\bin\api-ms-win-crt-utility-l1-1-0.dll
```
The above output is what I got. Please check it @peterjc123

**Comment by peterjc123** [comment]
@JafferWilson There're two environments. One is pure python `C:\Python35` and the other is Anaconda3 `C:\Users\aims\Anaconda3`. Since you've got Anaconda, why don't you install torch into Anaconda directly: `conda install -c pytorch pytorch-cpu`?
If you stick to use the first environment, you should list the dirs of it in front of those of the Anaconda environment.

**Comment by JafferWilson** [comment]
@peterjc123  I didn't got your point 

> If you stick to use the first environment, you should list the dirs of it in front of those of the Anaconda environment.
What does it means?
Anaconda is something that I have I stalled after no solution available for my previous problem. But I am not using anaconda anyways. I just kept Anaconda in case if nothing worked then I need to go on for Anaconda which is not my choice to do work. I try to keep everything in the local environment then to go for a virtual env.

**Comment by peterjc123** [comment]
@JafferWilson What is your PATH? Suppose it is `abcdasdjsakdkasjkdjaskd`, then it should be `C:\Python35;C:\Python35\Scripts;C:\Python35\bin;C:\Python35\Library\bin;abcdasdjsakdkasjkdjaskd`.

**Comment by peterjc123** [comment]
@JafferWilson Then could you try the following steps?
1. Install intel-openmp `pip install intel-openmp mkl`
2. Check iomp5 library existence 
```cmd
where mkl_rt.dll
where libiomp5md.dll
```
3. Install VC 2017 Redist https://aka.ms/vs/15/release/VC_redist.x64.exe
4. Check VC 2017 library existence `where api-ms-win-crt-utility-l1-1-0.dll`

**Comment by JafferWilson** [comment]
I tried But see what I got:  
```
C:\Users\aims>pip install intel-openmp mkl
Requirement already satisfied: intel-openmp in c:\python35\lib\site-packages (2018.0.3)
Requirement already satisfied: mkl in c:\python35\lib\site-packages (2018.0.3)

C:\Users\aims>where libiomp5md.dll
INFO: Could not find files for the given pattern(s).

C:\Users\aims>where mkl_rt.dll
INFO: Could not find files for the given pattern(s).

C:\Users\aims>where libiomp5md.dll
INFO: Could not find files for the given pattern(s).

C:\Users\aims>where api-ms-win-crt-utility-l1-1-0.dll
INFO: Could not find files for the given pattern(s).

```

**Comment by peterjc123** [comment]
@JafferWilson  Would you please restart the cmd window and do `echo %PATH%`?

**Comment by kdavila** [comment]
@peterjc123 . Hello. I experiencing this issue only on one of my window systems. I think my problem might be visual studio related but no Idea what else to do to fix it. I first tried installing the VC Redist package. Then, I installed the community edition for the Visual Studio 2017.  However, I am still getting:

C:\Users\Mauricio>where api-ms-win-crt-utility-l1-1-0.dll
INFO: Could not find files for the given pattern(s).

When I try the dependency walker on the "_C.cp35-win_amd64.pyd", it marks that all references are correct and the "api-ms-win-crt-utility-l1-1-0.dll" is being mapped to "C:\Windows\system32\ucrtbase.dll", but on the python console I am still getting the following error:

    from torch._C import *
ImportError: DLL load failed: The specified procedure could not be found.

I even moved from the CUDA 9.2 to cpu-only to reduce the dependencies, but still no luck. Any suggestions?

**Comment by peterjc123** [comment]
@kdavila Would you please try this [script](https://raw.githubusercontent.com/peterjc123/pytorch/c33d3ce84a3b6dca98206a1b2b4ad5cb2961ca0a/torch/utils/check_import.py)?

**Comment by kdavila** [comment]
@peterjc123 Thanks for your reply. However, I am afraid the script won't show any useful information with respect to the original cause of the problem, since I just tried compiling from source. and now it works just fine on my system. 

I have to say that I had all the required dependencies on place, but import would still fail until just before uninstalling, and then compiling/installing from source.

**Comment by peterjc123** [comment]
@kdavila Probably it is caused by the version mismatch of some DLL files.

**Comment by rohitj559** [comment]
> @peterjc123 Thanks for your reply. However, I am afraid the script won't show any useful information with respect to the original cause of the problem, since I just tried compiling from source. and now it works just fine on my system.
> 
> I have to say that I had all the required dependencies on place, but import would still fail until just before uninstalling, and then compiling/installing from source.
I had the same problem and tried these steps. But it did not work. Assistance required!!! please...

**Comment by rohitj559** [comment]
> @kdavila Would you please try this [script](https://raw.githubusercontent.com/peterjc123/pytorch/c33d3ce84a3b6dca98206a1b2b4ad5cb2961ca0a/torch/utils/check_import.py)?

I had the same problem and tried these steps. But it did not work. Assistance required!!! please...

**Comment by peterjc123** [comment]
What do you mean by saying "did not work"? What is the result of this script?

**Comment by rohitj559** [comment]
Well....  The script printed out a senetence to copy the dll from a source path and paste it into env variables path. I tried out the instruction of the script but nothing worked. After doing more research, I found that my PC(Windows 10) didnot have any gpus within and so I had to run the command - “conda install -c peterjc123 pytorch-cpu” by removing the pytorch version installed earlier for cuda compatibility. Things worked fine then onwards. Thank you peter. Great work setting up pytorch compatibility with windows.

**Comment by peterjc123** [comment]
@rohitj559 I see. Then there must be something wrong in judging whether the PyTorch package is CUDA version. Could you tell me which version you installed previously?

**Comment by valtron** [comment]
Also getting "specified _procedure_ could not be found". PyTorch 1.0.0 wheel from site, py3.6, win10, CUDA 10.0 (installed and in `$PATH`). Script says "It seems `import torch` should work.".

The "procedure" part of the error indicates that it's likely a version problem with a dll, but I don't know which DLL. (Anyone know how to debug this error directly?).

Process Monitor's "Process and Thread Activity" shows:

![image](https://user-images.githubusercontent.com/123696/50050922-0a20f480-00c5-11e9-8e29-24c1fa7d798b.png)

Previously I had PyTorch 0.4.1, CUDA 9.0.

**Comment by peterjc123** [comment]
@valtron Could you try the CPU package? If that works, then could you please try removing the dynamic libraries in `D:\dev\python36\Lib\site-packages\torch\lib` that have the prefix `nv` or `cu`?

**Comment by valtron** [comment]
@peterjc123 Thanks for the reply. Same issue with the CPU version. But that did lead me to find `lib/torch_python.dll`, whose previous unknown location prevented me from debugging with Dependency Walker. Here's what I did/found:

- Added `D:\dev\python36\Lib\site-packages\torch\lib` to `$PATH`
- Opened `_C.cp36-win_amd64.pyd` with [Dependency Walker](http://dependencywalker.com); (this takes a minute or two)
- Under the left side I saw PYTHON36.dll was red:

![image](https://user-images.githubusercontent.com/123696/50059312-72fa8200-0142-11e9-9fe2-1b54d5b56a0e.png)

- In the right side (function list) I saw `PySlice_Unpack` was missing

`PySlice_Unpack` was only added in Python 3.6.1 (https://docs.python.org/3.7/c-api/slice.html#c.PySlice_Unpack) whereas I'm using 3.6.0. So, this wheel must have been built with >= 3.6.1.

**Comment by Hrishikesh97** [comment]
Hi, i am using python 3.6.5 and installed tensorflow. However when i try to import tensorflow, it gives me this error.

Traceback (most recent call last):
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

please help

**Comment by peterjc123** [comment]
@Hrishikesh97 Why do you post the Tensorflow issues here?

**Comment by Hrishikesh97** [comment]
@peterjc123 sorry but i think the error issue is same as dll files are not loaded.

**Comment by peterjc123** [comment]
@Hrishikesh97 Well, you could try these methods. But I could not give more suggestions because I'm not familiar with it.

**Comment by michaeljyt** [comment]
I fix the issue after I **upgrade** the python 3.6.0 to **3.6.8**. Hope this infomation helpful to you.

**Comment by Hrishikesh97** [comment]
Hi,
Thank you for your guidance. I still require your help. I want to implement
this super resolution using GAN based on PyTorch based Implementation
similar to this link. [https://github.com/leftthomas/SRGAN]. Can you please
list me out which python software version and PyTorch installation would
support this project. And all the required libraries that need to be
installed with proper versions that can run this code, Hope to hear from
you soon.

Thanks and Regards,
Hrishikesh Patel

**Comment by peterjc123** [comment]
@Hrishikesh97 The author has already listed the dependencies in https://github.com/leftthomas/SRGAN#requirements. And for user questions. please post to the forum instead. https://discuss.pytorch.org/

**Comment by Hrishikesh97** [comment]
@peterjc123 , I installed pytorch using Anaconda3 from pytorch website command, but it got stuck on executing transaction step for hours. I can not figure out the cause of this issue. Please help. Thanks

**Comment by peterjc123** [comment]
@Hrishikesh97 Please try pip install.

**Comment by lal1234** [comment]
> @JafferWilson There're two environments. One is pure python `C:\Python35` and the other is Anaconda3 `C:\Users\aims\Anaconda3`. Since you've got Anaconda, why don't you install torch into Anaconda directly: `conda install -c pytorch pytorch-cpu`?
> If you stick to use the first environment, you should list the dirs of it in front of those of the Anaconda environment.

i have anaconda installed on windows10 with intel4000 graphic card..i try installing pytorch in env other than the base using pip package with python 3.7..after successfull installation it shows the dls load failed error..i retry the same with python 3.6 but doesn't work and also i have no other python version installed in my system beside the anaconda..pls help

**Comment by peterjc123** [comment]
@lal1234 Please downgrade your Python to 3.6.7 or 3.7.1.

**Comment by chitransh89** [comment]
I installed pytorch through pip. I was also having this problem of **DLL load failed: procedure could not be found**. I was using Python 3.6.0 on Windows 10. Upgrading to Python 3.6.8 solved the problem

**Comment by rabi24** [comment]
> Hi, i am using python 3.6.5 and installed tensorflow. However when i try to import tensorflow, it gives me this error.
> 
> Traceback (most recent call last):
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow__init__.py", line 24, in
> from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python__init__.py", line 49, in
> from tensorflow.python import pywrap_tensorflow
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in
> raise ImportError(msg)
> ImportError: Traceback (most recent call last):
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in
> from tensorflow.python.pywrap_tensorflow_internal import *
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in
> _pywrap_tensorflow_internal = swig_import_helper()
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
> _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 243, in load_module
> return load_dynamic(name, filename, file)
> File "C:\Users\hrishi97\AppData\Local\Programs\Python\Python36\lib\imp.py", line 343, in load_dynamic
> return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> 
> Failed to load the native TensorFlow runtime.
> 
> please help

same error. How to solve this

**Comment by chitransh89** [comment]
Did you try upgrading Python to 3.6.8?

**Comment by rabi24** [comment]
> Did you try upgrading Python to 3.6.8?

I'm using python 3.7.8 and 3.8.5

**Comment by peterjc123** [comment]
@rabi24 Looking into the log, isn't the error coming from importing tensorflow? I didn't get why do you want to post a tensorflow-related issue in the PyTorch repo.
