### ISSUE TITLE
Dynamo or FakeTensor mode doesn't work properly if torch.div returns 1-element tensor

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#92655]
### 🐛 Describe the bug

Minimized repo:
```
import torch
import torch._dynamo
import logging

torch._dynamo.config.log_level = logging.DEBUG
torch._dynamo.config.verbose = True

def fn(x):
    y = torch.div(4, 4, rounding_mode='trunc')
    # y = torch.tensor(1)     <- this way works well
    return x.view(y, 16)


opt_fn = torch._dynamo.optimize("eager", nopython=True)(fn)
print(opt_fn(x))
```

Error:
```
Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1091, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
TypeError: view() received an invalid combination of arguments - got (FakeTensor, int), but expected one of:
 * (torch.dtype dtype)
 * (tuple of ints size)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1048, in get_fake_value
    return wrap_fake_exception(
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 723, in wrap_fake_exception
    return fn()
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1049, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/utils.py", line 1101, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_method view(*(FakeTensor(FakeTensor(..., device='meta', size=(4, 4)), cpu), FakeTensor(FakeTensor(..., device='meta', size=(), dtype=torch.int64), cpu), 16), **{}):
view() received an invalid combination of arguments - got (FakeTensor, int), but expected one of:
 * (torch.dtype dtype)
 * (tuple of ints size)
```

### Versions

Not version specific

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
Sigh, number number binary op calls lol

**Comment by yanboliang** [comment]
@ezyang Is this what we should support? It passed on eager mode.

**Comment by yanboliang** [comment]
@Chillee mentioned this is relevant to [```FakeTensor.constant```](https://github.com/pytorch/pytorch/blob/493a6ced74ea9271fc7ab16d6493f08750ecb5f4/torch/_subclasses/fake_tensor.py#L576).

**Comment by ezyang** [comment]
I mean, yes lol. But it's probably ok to special case it. The list of ops that do this are the allow numbers as scalars list I think

**Comment by ezyang** [comment]
I misdiagnosed the issue.

The real issue is that we permit Tensor arguments to places where we expect an integer. But if it's fake, then there's no way for actually do this. So the real solution is to constant propagate through torch.div(number, number) (cc @eellison ) or use dynamic shapes with unbacked symint (but for the synthetic example here, it's unnecessary to do the dynamci shapes solution)
