### ISSUE TITLE
Make True the default for set_to_none in Optimizer.zero_grad for 2.0 release

### ISSUE THREAD

**Issue by ntenenz** [pytorch/pytorch#92656]
### 🚀 The feature, motivation and pitch

When calling `Optimizer.zero_grad`, the default value of `set_to_none` is currently False to ensure backwards compatibility. However, a value of True will generally reduce memory consumption and can improve training performance. Given the forthcoming release of PyTorch 2.0, there is a limited opportunity to make the breaking change in a SemVer-consistent fashion and default to the more performant alternative. This would also mean that new users, who may not be aware of this option, would automatically see performance benefits rather than having to opt-in.

### Alternatives

Retain the status quo and have users manually specify the more performant option when desired.

cc @ngimel @ezyang @gchanan @vincentqb @jbschlosser @albanD @janeyx99

**Comment by janeyx99** [comment]
This sounds like a good idea--as long as there aren't other implications that bc-breaking. @albanD thoughts?

**Comment by ngimel** [comment]
We've discussed with @albanD, let's do this! We hope that even though optimizer would produce slightly different updates, convergence behavior won't change, as has been the case for people who started using `set_to_none=True`

**Comment by milesial** [comment]
Can we do the same for `nn.Module`?

**Comment by ntenenz** [comment]
Thanks @janeyx99 !
