### ISSUE TITLE
[inductor] Dtype wrong for arange with floating point step

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#92676]
### 🐛 Describe the bug

```
import torch
from torch.nn import *

class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self):
        arange_1 = torch.arange(512, -512, -1.0)
        return arange_1

mod = Repro()
opt_mod = torch.compile(mod)
print(opt_mod().dtype)
print(mod().dtype)
```
```
torch.int64
torch.float32
```

### Versions

N/A

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by eellison** [comment]
I think this is actually fairly high-pri since arange is used a lot in decomps
