### ISSUE TITLE
sum() not working for SparseTensor

### ISSUE THREAD

**Issue by Acciorocketships** [pytorch/pytorch#92757]
### 🐛 Describe the bug

```python
>>> import torch
>>> i = [[1, 1]]
>>> v =  [3, 4]
>>> s = torch.sparse_coo_tensor(i, v, (3,))
>>> s.sum(dim=0)
```

NotImplementedError: Could not run 'aten::sum.dim_IntList' with arguments from the 'SparseCPU' backend.

### Versions

Python 3.10.6
Pytorch 1.13.1

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by cpuhrsch** [comment]
@nikitaved - can you look into this?

**Comment by cpuhrsch** [comment]
Maybe it's time we implemented this feature. The main difference between `torch.sparse.sum` and `torch.sum` will be the gradient. `torch.sparse.sum` has masked, sparse gradients whereas `torch.sum` will have dense gradients. Seems like the forward kernel is the hardest part and we already have it. The backwards formula will be a call to `expand`.

**Comment by Acciorocketships** [comment]
In the meantime I have implemented a workaround using torch.unique and torch.scatter_reduce_

**Comment by cpuhrsch** [comment]
@Acciorocketships - does that mean you want masked gradients? If so https://pytorch.org/docs/master/generated/torch.sparse.sum.html might be exactly what you want.

**Comment by Acciorocketships** [comment]
My implementation doesn't use a mask over a dense tensor, if that's what you're asking.
