### ISSUE TITLE
autocast() docstring is missing mandatory parameters in example invocations

### ISSUE THREAD

**Issue by jxtps** [pytorch/pytorch#92803]
### 📚 The doc issue

https://pytorch.org/docs/stable/amp.html#torch.autocast reads: 

`CLASS torch.autocast(device_type, dtype=None, enabled=True, cache_enabled=None)`
...
`with autocast():`

The mandatory `device_type` parameter is missing, and there's no `import` which makes the `autocast()` reference ambiguous. 

(there are several examples in the docstring)

### Suggest a potential alternative/fix

It should presumably read `with torch.autocast('cuda'):`

cc @svekars @carljparker @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by ashok-kumar-kannan** [comment]
Hi, I'd like to work on and be assigned this issue if possible, thanks!

**Comment by jxtps** [comment]
Nice work!

**Comment by ashok-kumar-kannan** [comment]
Thanks @jxtps
