### ISSUE TITLE
ROCm machines out of disk space

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#92822]
### 🐛 Describe the bug

After a recent hiccup with downloading docker images, some ROCm machines have gotten into a bad state where they're out of disk space and workflows fail while pulling docker images with the error:

```
74711b60232e: Pull complete
e968de764a03: Pull complete
9aed670494cd: Download complete
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /opt/rocm-5.3.0/share/miopen/db/gfx906_64.kdb: no space left on device
Error: Process completed with exit code 1.
```

Sample workflow:
Runner name: 'worker-rocm-amd-34'
https://github.com/pytorch/pytorch/actions/runs/3988204875/jobs/6839488621

Not sure how many other runners are affected.

### Versions

n/a

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by jeffdaily** [comment]
Worker 34 has had its docker purged.  We are working on a PR to catch this scenario.

**Comment by huydhn** [comment]
Here is another instance of this issue https://github.com/pytorch/pytorch/actions/runs/4016325790/jobs/6899634679 happening just few hours ago.  Interestingly, it's the same worker-rocm-amd-34 I think

**Comment by jeffdaily** [comment]
Worker 34 has now had its entire /var/lib/docker purged and docker reinstalled.  It seems when we moved from jenkins + docker to GHA + rootless docker, there were old docker images and containers that hadn't been removed.
