### ISSUE TITLE
Nightly conda CUDA builds timeout since Sat Jan 21th 2023

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#92852]
Failing conda nightly :
https://hud.pytorch.org/hud/pytorch/pytorch/nightly

Here are the failures:
https://github.com/pytorch/pytorch/actions/runs/3984411372/jobs/6842256518

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
Thank you for failing, change the status that they are failing for 3 days in a row (also, was it detected by the nightly testing framework?)

**Comment by atalman** [comment]
Yes here are the nightly failures: https://github.com/pytorch/builder/actions/runs/3987413677/jobs/6837209867

**Comment by seemethere** [comment]
Is this just a case where we need to bump the timeout here?

**Comment by seemethere** [comment]
> Is this just a case where we need to bump the timeout here?

Submitted https://github.com/pytorch/pytorch/pull/92859 to check to see if that helps resolve

**Comment by malfet** [comment]
To be frank, I'm suspicious of this PR https://github.com/pytorch/builder/pull/1263 and especially it's lack of testplan (I don't see how https://github.com/pytorch/pytorch/pull/92629/files could have tested it)

**Comment by malfet** [comment]
For the last successful build:
```
2023-01-20T08:54:22.9080065Z [ 93%] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Unique.cu.o
2023-01-20T09:23:14.9242618Z [ 93%] Linking CXX shared library ../lib/libtorch_cuda.so
```
For the failing build:
```
2023-01-21T08:55:06.9220423Z [ 93%] Building CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Unique.cu.o
2023-01-21T10:15:50.2154578Z [ 93%] Linking CXX shared library ../lib/libtorch_cuda.so
```
I.e. Unique.cu somehow takes 90+ min to compile... Does this rings a bell @ptrblck ?

**Comment by malfet** [comment]
Ok, I forgot that we run [manywheel-py3_7-cuda11_6](https://hud.pytorch.org/hud/pytorch/pytorch/master/3?per_page=50&name_filter=manywheel-py3_7-cuda11_6) on trunk which immediately highlights PR that caused the latency:
https://github.com/pytorch/pytorch/pull/90847 <- before it build time was at 85 min, after 120 min.

**Comment by albanD** [comment]
Oups!
Should we try and use the jiterator in this context?

**Comment by malfet** [comment]
> Oups! Should we try and use the jiterator in this context?

According to @ngimel it uses cub and therefore not JITeratable. But probably a complex one can be composite

**Comment by malfet** [comment]
Nightlies are green again
