### ISSUE TITLE
DISABLED test_variable_sequence_cuda_float32 (__main__.TestNNDeviceTypeCUDA)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#92886]
Platforms: linux
This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_variable_sequence_cuda_float32%2CTestNNDeviceTypeCUDA)).

cc @albanD @mruberry @jbschlosser @walterddr @saketh-are

**Comment by jbschlosser** [comment]
My initial thought is that the tolerances should be tweaked, but the value diffs are pretty high. For example:
```
AssertionError: Tensor-likes are not close!
Mismatched elements: 8 / 56 (14.3%)
Greatest absolute difference: 0.2987147867679596 at index (0, 2, 0) (up to 1e-05 allowed)
Greatest relative difference: 28.935338405389786 at index (1, 2, 0) (up to 0 allowed)
```'

Needs further investigation..
