### ISSUE TITLE
Running Attention with batch size and sequence length of one is very slow (CPU)

### ISSUE THREAD

**Issue by sidhiadkoli** [pytorch/pytorch#92892]
### 🐛 Describe the bug

The model is a standard transformer. I wanted to implement caching in the decoder so that auto-regressive decoding in inference time becomes faster. Inference is always run with batch size of 1. I noticed that considering just the last token for decoding is approx 10 times slower than using the full sequence. This entire experiment was done on the CPU.

Here is a trimmed down version of the code that is representative of the slow-down:
```
import time
import torch


def main():
    # Embedding dim = 128, number of heads = 2.
    self_attn = torch.nn.modules.activation.MultiheadAttention(128, 2, dropout=0.1, batch_first=True)
    multihead_attn = torch.nn.modules.activation.MultiheadAttention(128, 2, dropout=0.1, batch_first=True)

    # Inference mode.
    self_attn.eval()
    multihead_attn.eval()

    # Determines the sequence length for the query tensor.
    seqlen = 1

    total_time = 0

    # Run six iterations of self-attn and multihead-attn.
    # This for loop emulates six runs of an auto-regressive 1-layer decoder.
    for i in range(1, 7):
        target = torch.rand([1, i, 128])  # B, sequence length, E
        target_last = torch.rand([1, seqlen, 128])  # B, seqlen, E. This is typically the last token in the target sequence.
        memory = torch.rand([1, 7, 128])  # B, seqlen, E

        start = time.time()
        self_attn(target_last, target, target, need_weights=False)
        multihead_attn(target_last, memory, memory, need_weights=False)
        total_time += time.time() - start

    print(f"time: {total_time}")


if __name__ == '__main__':
    main()
```

Here are the average execution times (across 50 runs of the above script) for difference sequence lengths (`seqlen`).
```
seqlen = 1. Time: 0.0856 s
seqlen = 2. Time: 0.0065 s
seqlen = 3. Time: 0.007 s
seqlen = 10. Time: 0.007 s
seqlen = 20. Time: 0.014 s
seqlen = 30. Time: 0.0145 s 
```

As you can see from the above results, sequence length of 1 (for the query tensor) is more than 10 times slower than the same run for longer sequence lengths. Not sure why this is the case. Any insight into this would be much appreciated.

### Versions

PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB
GPU 2: NVIDIA A100-PCIE-40GB
GPU 3: NVIDIA A100-PCIE-40GB

Nvidia driver version: 515.86.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] pytorch-wpe==0.0.1
[pip3] torch==1.12.1+cu116
[pip3] torch-complex==0.4.3
[pip3] torchaudio==0.12.1+cu116
[pip3] torchmetrics==0.11.0
[pip3] torchvision==0.13.1+cu116
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.4           py39h14f4228_0  
[conda] numpy-base                1.23.4           py39h31eccc5_0  
[conda] pytorch-wpe               0.0.1                    pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torch-complex             0.4.3                    pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

cc @jbschlosser @bhosmer @cpuhrsch @erichan1

**Comment by vishnumadhu365** [comment]
Ran the profiler for various seqlen's for 100 iterations.
Profiler data below shows aten:bmm call is considerably slower for seqlen 1. Need to inspect torch.bmm() in torch/nn/functional.py: multi_head_attention_forward()

Seqlen : 1

                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
         profile_attention         3.20%     358.399ms       100.00%       11.200s       11.200s             1
                 aten::bmm        88.78%        9.943s        88.78%        9.943s       4.143ms          2400
              aten::linear         0.34%      38.616ms         5.08%     569.020ms     158.061us          3600
               aten::addmm         4.12%     461.575ms         4.38%     489.996ms     136.110us          3600


Seqlen :2

                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
         profile_attention        23.15%     466.351ms       100.00%        2.014s        2.014s             1
                 aten::bmm        36.09%     727.082ms        36.09%     727.091ms     302.955us          2400
              aten::linear         2.54%      51.241ms        16.62%     334.860ms      93.017us          3600
               aten::addmm         7.80%     157.087ms         9.91%     199.673ms      55.465us          3600

Seqlen : 10

                      Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls
         profile_attention        15.61%     282.043ms       100.00%        1.807s        1.807s             1
                 aten::bmm        57.63%        1.042s        57.63%        1.042s     434.008us          2400
              aten::linear         1.58%      28.585ms        11.33%     204.691ms      56.859us          3600
               aten::addmm         6.39%     115.423ms         7.66%     138.372ms      38.437us          3600

**Comment by mingfeima** [comment]
@sidhiadkoli thanks for the findings!

There are a couple of issues in this issue:
1. `bmm` on the CPU path has two paths: given two tensors of shape [B, M, K] and [B, K, N], `baddbmm_cpu_kernel` is used when MNK < 400 and `baddbmm_with_gemm_` is used when MNK >= 400. So your tests will use both paths.
2. the grain size in `baddbmm_cpu_kernel` is not correct, this will lead to parallel implementation even for very small input shape. (usually we would want to go sequential implementation for small input shape, since it is not worth paralleling it)
3. your benchmark script has too few iterations, need to add more iterations in the benchmark to get reasonable result. (I updates the script with 1000 iters)
4. since the input shape is not very big ( which means the workload would be latency bound), using more CPU cores would not get better results.

I have fixed the 2. with this https://github.com/pytorch/pytorch/pull/98297, and the following is results on my machine:

(unit: ms per iteration)

seq length | 1 core | 4 cores | 20 cores
-- | -- | -- | --
1 | 2.534 | 2.595 | 7.694
2 | 2.670 | 2.792 | 4.210
10 | 2.840 | 2.839 | 4.495
20 | 2.906 | 3.010 | 4.678
30 | 3.096 | 3.119 | 4.708


You can see that using 20 cores would have even worse performance. One more thing I want to emphasize is the environment setting, you need to set NUMA on Xeon later than Skylake, for example:
```
# using the first 4 cores from numa node 0:
numactl --physcpubind=0-3 --membind=0 OMP_NUM_THREADS=4 python script.py
```
