### ISSUE TITLE
concat tensor

### ISSUE THREAD

**Issue by munziliashali** [pytorch/pytorch#9298]
Hi all,

I have two tensors of different dimensions:
A = tensor([[-1.9314, -1.9754, -1.9867, -2.2567, -2.2533, -2.2397],
        [-1.9754, -1.9867, -1.9641, -2.2533, -2.2397, -2.2318]])
B = tensor([-2.2320, -2.2240])

I want to create a new tensor that looks like this:
C = tensor([[-1.9314, -1.9754, -1.9867,  -2.2567, -2.2533, -2.2397], [-2.2320],
        [-1.9754, -1.9867, -1.9641,  -2.2533, -2.2397, -2.2318], [-2.2240]])
In Python I can easily do it with looping:
C = []
for i in range(len(A)):
        C.append([A[i],B[i]])

Any idea, the Pytorch way to do it?

**Comment by fmassa** [comment]
In PyTorch we don't currently support tensors having different sizes in the same dimension.
You might be able to simulate that using [`PackedSequence`](https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/rnn.py#L12), or with the experimental [`BatchTensor`](https://github.com/pytorch/pytorch/pull/9198), but I'm not sure that we will be adding explicit support for that in PyTorch core soon.

**Comment by munziliashali** [comment]
Hi @fmassa thanks for the quick response. So, what if of the same dimension? I had a hard time trying to append with torch.cat.. Please help..

**Comment by fmassa** [comment]
You can specify the dimension where to concatenate the tensors.
```python
a = torch.rand(3, 3)
b = torch.rand(3, 6)
c = torch.cat((a, b), dim=1)
```

Also, questions like those are better suited for https://discuss.pytorch.org/
