### ISSUE TITLE
Pytorch 1.13.0 Profiler generate invalid separator path inside JSON using tensorboard_trace_handler.

### ISSUE THREAD

**Issue by Molem7b5** [pytorch/pytorch#92988]
## Issue description
On windows, tensorboard_trace_handler use the separador \ in the file path instead of / or \\ breaking the json file.

It is identical to a previous issue #60187

## Code example

1. Setup the Profiler. Example:
`with torch.profiler.profile( activities=[ torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA], schedule=torch.profiler.schedule( wait=2, warmup=3, active=6), on_trace_ready=torch.profiler.tensorboard_trace_handler('./result', worker_name='worker0'), record_shapes=True, profile_memory=True, with_stack=True   ) as p:`

Use Kineto to try to profile the file `tensorboard --logdir=./result`

It results in an error of the kind` json.decoder.JSONDecodeError: Invalid \escape: line 1748355 column 56 (char 160536060)`

## System Info
- PyTorch 1.13.0
- How you installed PyTorch (conda, pip, source): conda
- OS: Windows 10 Enterprise Version 10.0.19044 
- PyTorch version: 1.13.0
- Python version: 3.8
- CUDA/cuDNN version: 11.7
- GPU models and configuration: Nvidia GTX 3090

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb

**Comment by yelu** [comment]
I have the same issue. The profiler generates log file containing invalid windows file path separator for json file.

![image](https://user-images.githubusercontent.com/1885805/219907902-e424daa8-0c2a-46fc-8c65-a4a53380a064.png)

**Comment by aaronenyeshi** [comment]
This should be fixed.
