### ISSUE TITLE
why doe torch.inference_mode() requires 'with' keyword  

### ISSUE THREAD

**Issue by Poojan1015** [pytorch/pytorch#93058]
### 📚 The doc issue

why does torch.inference_mode() requires 'with' keyword

**Comment by varunponda** [comment]
`with` helps us to wrap the execution of a block of code with the methods defined by the context manager . So once the execution of the code is finished the context manager automatically exits the inference mode, restoring the previous state of the model.

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org
