### ISSUE TITLE
DISABLED test_roi_align_dynamic_shapes_cuda (__main__.CudaTests)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#93054]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/test_roi_align_dynamic_shapes_cuda%2CCudaTests)).

This actually comes from a broken trunk commit https://hud.pytorch.org/pytorch/pytorch/commit/c11b301bcda123711f678754647bef7b9b17f760 but the commit is so massive that reverting it could take more effort than finding a forward fix, so disabling the test here temporarily to keep trunk green.

cc @ezyang @gchanan @zou3519 @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
cc @jjsjann123 @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment]
I try to look a bit closer into how the test was run before and after the change.  In the commit `0a57a20c02132577a48f5283ffbdf04257af1dbf ` that you refer to, the test was skipped with `test_roi_align_dynamic_shapes_cuda (__main__.CudaTests) ... skip: requires torchvision` in https://ossci-raw-job-status.s3.amazonaws.com/log/10893618567.  On the other hand, it started to run in https://hud.pytorch.org/pytorch/pytorch/commit/c11b301bcda123711f678754647bef7b9b17f760 where torchvision is installed.  Does this ring any bells?

**Comment by jjsjann123** [comment]
I don't think it's introduced in the build refactor PR.

I went through the log in HUD: https://www.torch-ci.com/ 
On commit `0a57a20c02132577a48f5283ffbdf04257af1dbf` (the commit before the refactor), inductor test is running in shard 3. `trunk / linux-bionic-cuda11.6-py3.10-gcc7-sm86 / test (default, 3, 4, linux.g5.4xlarge.nvidia.gpu)`
Going into the log, we have:
```
2023-01-26T04:00:43.8543723Z   test_roi_align_dynamic_shapes_cuda (__main__.CudaTests) ... skip: requires torchvision (0.000s)
```
So it just slipped through CI. I have no idea how torchvision is skipped though.

**Comment by jjsjann123** [comment]
> I try to look a bit closer into how the test was run before and after the change. In the commit `0a57a20c02132577a48f5283ffbdf04257af1dbf ` that you refer to, the test was skipped with `test_roi_align_dynamic_shapes_cuda (__main__.CudaTests) ... skip: requires torchvision` in https://ossci-raw-job-status.s3.amazonaws.com/log/10893618567. On the other hand, it started to run in https://hud.pytorch.org/pytorch/pytorch/commit/c11b301bcda123711f678754647bef7b9b17f760 where torchvision is installed. Does this ring any bells?

Haha, you beat me to it.

So it's a failure coming from upstream inductor. I don't know how torchvision setup changed in CI. I'm suspecting that's an infra issue though. cc'ing @malfet for CI infra.
Meanwhile, @jansel on the inductor dynamic shape issue.

**Comment by huydhn** [comment]
I will try to take a look now.  The step responsible for this is `install_torchvision` in the CI, let me check if there is any recent changes there

**Comment by jjsjann123** [comment]
Want to also point out that sharding behavior seems to have changed.

Inductor tests were part of shard 1 in the refactor PR, while it's in shard 3 in the commit prior. Not sure if there's any setup differences between those jobs.

**Comment by huydhn** [comment]
> Want to also point out that sharding behavior seems to have changed.
> 
> Inductor tests were part of shard 1 in the refactor PR, while it's in shard 3 in the commit prior. Not sure if there's any setup differences between those jobs.

Oh, that part is nothing out of ordinary.  These shards are equivalent, the CI has a way to dynamically distribute tests among them so that the time taken to run tests on each shards is as close as possible (balance shards).  So it's possible that a test can be run in different shards, moving from one to another.
