### ISSUE TITLE
Getting Warning on qnnpack quantization

### ISSUE THREAD

**Issue by sridhardev07** [pytorch/pytorch#93140]
### 🐛 Describe the bug

Getting the warning:
Currently, qnnpack incorrectly ignores reduce_range when it is set to true; this may change in a future release.

When using the quantization:
torch.backends.quantized.engine = 'qnnpack'
quantize_dynamic(modl, {torch.nn.Linear}, dtype=torch.qint8)

### Versions

Torch 1.13.1

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by supriyar** [comment]
the reduce_range=true is required to be set to true only if you are running using the fbgemm backend. If running on qnnpack/mobile backend this flag can be set to false (or it will be ignored).

**Comment by Pchatain** [comment]
How do you turn this off @supriyar @sridhardev07 ? I am having trouble figuring out how to turn this setting off, since I never explicitly turned it on in the first place.

**Comment by jacobhp-heni** [comment]
@Pchatain did you ever work this out?

**Comment by Pchatain** [comment]
> [@Pchatain](https://github.com/Pchatain) did you ever work this out?

Last I remember no. Just had to workaround the warnings.
