### ISSUE TITLE
No matching distribution found for torch on pyenv apple silicon

### ISSUE THREAD

**Issue by davidceka** [pytorch/pytorch#93148]
### 🐛 

Hi everyone, i've just bought a new apple silicon machine with M2 pro in it. I'm trying to install torch inside a pyenv but pip cant seem to find any version for it. the pyenv environment i have set up is on python 3.11.1, and i've also tried to upgrade pip but it's already updated (22.3.1). Do you have any suggestions on what to do?
i'm running ventura 13.2.
Also, i tried to install torch audio and there are matching distributions but it won't install cause torch is a dependency.

edit: it will find it on 3.8.13, but would still like to know as why it won't work on newer version
### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.2 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.1 (main, Jan 24 2023, 17:36:15) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.2-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.24.1
[conda] Could not collect

**Comment by tiagovrtr** [comment]
Duplicate of #86566

**Comment by davidceka** [comment]
> Duplicate of #86566

thank you kind sir, i'll mark as closed
