### ISSUE TITLE
qr is not implemented for type torch.cuda.HalfTensor

### ISSUE THREAD

**Issue by tbenst** [pytorch/pytorch#9315]
A number of operations are not implemented for HalfTensors, which makes it more difficult to leverage Tensor Cores.

## Code example

```python
import torch
import torch.nn as nn
conv1 = nn.Parameter(torch.HalfTensor(64,1,5,5).cuda())
nn.init.orthogonal_(conv1, nn.init.calculate_gain('relu'))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-7fcd63ce6604> in <module>()
      1 conv1 = nn.Parameter(T.HalfTensor(64,1,5,5).cuda())
----> 2 nn.init.orthogonal_(conv1, nn.init.calculate_gain('relu'))

/home/ubuntu/anaconda3/envs/pytorch_p27/lib/python2.7/site-packages/torch/nn/init.pyc in orthogonal_(tensor, gain)
    326 
    327     # Compute the qr factorization
--> 328     q, r = torch.qr(flattened)
    329     # Make Q uniform according to https://arxiv.org/pdf/math-ph/0609050.pdf
    330     d = torch.diag(r, 0)

RuntimeError: qr is not implemented for type torch.cuda.HalfTensor
```

**Comment by vishwakftw** [comment]
I can think of one way of solving this: initialize with `float32` and then downcast to `float16`. I am not sure what problems this might cause.
```
conv1 = nn.Parameter(torch.Tensor(64,1,5,5).cuda())
nn.init.orthogonal_(conv1, nn.init.calculate_gain('relu'))
conv1 = conv1.to(torch.float16)
```

**Comment by bhushan23** [comment]
@vishwakftw then we are not taking advantage of fp16 also, we might face precision issues

**Comment by vishwakftw** [comment]
There is an obvious problem due to downcasting, yes. I was concerned about whether this could be trainable, and how costly training would be.

MAGMA does not have support for `float16` qr factorization, and so does LAPACK I think.

**Comment by Lezcano** [comment]
Given that the backend libraries that we use do not have support for half dtypes, the current take is that we will not be offering support in `torch.linalg` for this dtypes any time soon.

In the meantime, one can cast the inputs to float, perform the operations in 32-bit precision, and then downcast the results, as @vishwakftw suggested.

Closing for now.
