### ISSUE TITLE
Extra outputs when after torch.onnx.export

### ISSUE THREAD

**Issue by likvidon** [pytorch/pytorch#93157]
### 🐛 Describe the bug

Hello, guys!

I'am converting my model with one output from pytorch to ONNX-format. Converted model correct and works fine.
But when i see model scheme with https://netron.app/, i see that model have four outputs. This may be due to the presence of the transpose function:
![Screenshot from 2023-01-27 19-55-32](https://user-images.githubusercontent.com/41129705/215147459-c71977b8-3634-4f39-8439-e10732d615e7.png)

![Screenshot from 2023-01-27 19-56-05](https://user-images.githubusercontent.com/41129705/215147451-ebec31d3-26ed-4121-8d7a-5791e45a4920.png)

Next step, when I'am converting ONNX-model to engine, engine-format has wrong output as main and all results incorrect.
I try to change some params and convertation methods, but problem wasn't solved.

I will be grateful for any help!

### Versions

[pip3] numpy==1.23.4
[pip3] torch==1.13.0
[pip3] torch2trt==0.4.0
[pip3] torchvision==0.14.1

**Comment by thiagocrepaldi** [comment]
@likvidon can you provide a repro of this issue?

It may be possible the exported model has extra outputs appended to the end
One example that I recall is when converting detectron2 models. They have a flattening function that appends metadata to the output to allow unflattening in later stages. Such metadata will appear on the output of the model, but will no influence anything.

**Comment by likvidon** [comment]
You can download the model from the link https://drive.google.com/drive/folders/15GUjY0HmS1hL-453PA8IRvtZoGiu9JQy

The extra outputs do look size-aligned, when using the ONNX format they don't get in the way. But if converted into TensorRT, then one of the outputs is used as the main one, as far as I understand it, and the results are incorrect.

It would be great if you tried to convert the proposed model to ONNX format without additional outputs, I used the yolov5 exporter for this (The results are presented above)

**Comment by thiagocrepaldi** [comment]
@likvidon I want to help you, but I will; need your help first :) 

please provide a full script that consumes the model.pt and call onnx exporter with some data and all flags you used, etc

**Comment by thiagocrepaldi** [comment]
@likvidon can you provide a repro of this issue? As per our policy, we only work on issues with full repro; otherwise, we close them as-is

**Comment by thiagocrepaldi** [comment]
Closing as no repro was provided. Feel free to reopen when a runnable repro is available
