### ISSUE TITLE
Segmentation fault between Numpy and Pytorch using torch.bmm

### ISSUE THREAD

**Issue by gautierronan** [pytorch/pytorch#93161]
### 🐛 Describe the bug

When running the following script (taken from the torch.bmm documentation) in terminal:
```python
# test.py
import numpy as np
import torch

mat1 = torch.randn(10, 3, 4)
mat2 = torch.randn(10, 4, 5)
res = torch.bmm(mat1, mat2)
print(res.size())
```
The terminal returns
```
> python test.py
zsh: segmentation fault  python3 test.py
```
However, importing `torch` **before** `numpy` works as expected, and the terminal returns
```
> python test.py
torch.Size([10, 3, 5])
```
I am running on Python 3.9.16, Pytorch 1.13.1, and Numpy 1.21.2.

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 10:02:19)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] functorch==1.13.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.9.0
[pip3] torch==1.13.1
[pip3] torchaudio==0.10.1
[pip3] torchcde==0.2.5
[pip3] torchdiffeq==0.2.3
[pip3] torchdyn==1.0.3
[pip3] torchmetrics==0.11.0
[pip3] torchode==0.1.3
[pip3] torchsde==0.2.5
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl  
[conda] functorch                 1.13.1                   pypi_0    pypi
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.21.2           py39h4b4dc7a_0  
[conda] numpy-base                1.21.2           py39he0bd621_0  
[conda] pytorch-lightning         1.9.0                    pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchaudio                0.10.1                 py39_cpu    pytorch
[conda] torchcde                  0.2.5                    pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchdyn                  1.0.3                     dev_0    <develop>
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchode                  0.1.3                    pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchtyping               0.1.4                    pypi_0    pypi
[conda] torchvision               0.11.2                 py39_cpu    pytorch

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
Something tells me it's an OpenMP initialization... @gautierronan can you please run `lldb -- python test.py` and when it crashes, share a backtrace (by typing `bt`)

**Comment by malfet** [comment]
Hmm, can't repro the crash on x86 MacOS either, but I guess it has something to do with intel-openmp version (or may be another version of the OpenMP runtime installed on the system)

**Comment by gautierronan** [comment]
> Something tells me it's an OpenMP initialization... @gautierronan can you please run `lldb -- python test.py` and when it crashes, share a backtrace (by typing `bt`)

How can I do that?
Running these two commands in the terminal (in the right folder) yields

```
$ lldb -- python test.py
(lldb) target create "python"
Current executable set to 'python' (x86_64).
(lldb) settings set -- target.run-args  "test.py"
(lldb) bt
error: invalid process
```

**Comment by malfet** [comment]
Sorry, I forgot that you need to add `run` command

**Comment by gautierronan** [comment]
Here is what I get.
```c
$ lldb -- python crash.py
(lldb) target create "python"
Current executable set to 'python' (x86_64).
(lldb) settings set -- target.run-args  "crash.py"
(lldb) run
Process 46856 launched: '/Users/rgautier/miniconda3/bin/python' (x86_64)
Process 46856 stopped
* thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x540)
    frame #0: 0x0000000105ae899e libomp.dylib`__kmp_suspend_initialize_thread + 30
libomp.dylib`:
->  0x105ae899e <+30>: movl   0x540(%rdi), %eax
    0x105ae89a4 <+36>: movl   0x2e1fe(%rip), %ebx       ; __kmp_fork_count
    0x105ae89aa <+42>: incl   %ebx
    0x105ae89ac <+44>: cmpl   %ebx, %eax
  thread #3, stop reason = EXC_BAD_ACCESS (code=1, address=0x540)
    frame #0: 0x0000000105ae899e libomp.dylib`__kmp_suspend_initialize_thread + 30
libomp.dylib`:
->  0x105ae899e <+30>: movl   0x540(%rdi), %eax
    0x105ae89a4 <+36>: movl   0x2e1fe(%rip), %ebx       ; __kmp_fork_count
    0x105ae89aa <+42>: incl   %ebx
    0x105ae89ac <+44>: cmpl   %ebx, %eax
  thread #4, stop reason = EXC_BAD_ACCESS (code=1, address=0x540)
    frame #0: 0x0000000105ae899e libomp.dylib`__kmp_suspend_initialize_thread + 30
libomp.dylib`:
->  0x105ae899e <+30>: movl   0x540(%rdi), %eax
    0x105ae89a4 <+36>: movl   0x2e1fe(%rip), %ebx       ; __kmp_fork_count
    0x105ae89aa <+42>: incl   %ebx
    0x105ae89ac <+44>: cmpl   %ebx, %eax
Target 0: (python) stopped.
(lldb) bt
* thread #2, stop reason = EXC_BAD_ACCESS (code=1, address=0x540)
  * frame #0: 0x0000000105ae899e libomp.dylib`__kmp_suspend_initialize_thread + 30
    frame #1: 0x0000000105ae949e libomp.dylib`void __kmp_suspend_64<false, true>(int, kmp_flag_64<false, true>*) + 62
    frame #2: 0x00000001062e2698 libiomp5.dylib`bool _INTERNAL_25_______src_kmp_barrier_cpp_a115b87c::__kmp_wait_template<kmp_flag_64<false, true>, true, false, true>(kmp_info*, kmp_flag_64<false, true>*, void*) + 712
    frame #3: 0x00000001062deaaa libiomp5.dylib`_INTERNAL_25_______src_kmp_barrier_cpp_a115b87c::__kmp_hyper_barrier_release(barrier_type, kmp_info*, int, int, int, void*) + 266
    frame #4: 0x00000001062e6fba libiomp5.dylib`__kmp_fork_barrier(int, int) + 1226
    frame #5: 0x000000010631e8b3 libiomp5.dylib`__kmp_launch_thread + 227
    frame #6: 0x00000001063609e4 libiomp5.dylib`_INTERNAL_26_______src_z_Linux_util_cpp_f925d962::__kmp_launch_worker(void*) + 340
    frame #7: 0x00007ff813465259 libsystem_pthread.dylib`_pthread_start + 125
    frame #8: 0x00007ff813460c7b libsystem_pthread.dylib`thread_start + 15
```
