### ISSUE TITLE
[dynamo] dupe guards can be invalid when aot_autograd is invoked on graph intermediates

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#93170]
The current DDPOptimizer that dynamo uses relies on splitting a graph into subgraphs, and invoking the user's compiler on each subgraph (which will usually involve running aot autograd on that subgraph.

One consequence of that: today, aot autograd has logic to guard on duplicate inputs, and propagate those guards up to dynamo. However: if the inputs that it was given are not "user" inputs (because they came from one of the subgraphs from DDP), we don't actually want to guard on the duplicate inputs.

There are probably a few options for handling this situation. However, right now it feels like there's a mismatch in concerns:
- AOT Autograd is responsible for adding extra guards related to inputs, that dynamo doesn't currently handle (one example is input dupes, another that isn't complete yet is input aliasing logic
- that only really seems valid if aot autograd is given the same graph as dynamo, and the same set of example inputs. These guards make less sense when AOT Autograd is fed a subgraph, and a set of inputs that dynamo is unaware of.

Brainstorming some options:
(1) move these extra guards out of aot autograd, into dynamo (one annoying separation of concerns here is that aot autograd is the one that cares about this logic: handling aliasing and dupes to ensure autograd correctness)
(2) have dynamo annotate which args are "dynamo inputs", so aot autograd can distinguish them from non-dynamo args when generating guards.
(3) change everything: force backends to accept that dynamo and aot_autograd should always operate on the same graph, and refactor stuff so DDP doesn't end up calling aot_autograd on a subgraph (not sure how feasible this actually is)

@voznesenskym interested in your thoughts

I made a repro that doesn't directly involve DDP below. It's a bit annoying, but I created a mini partitioner that partitions the user graph in two, and calls aot autograd on each subgraph (similar to what the DDP Optimizer does)

```
diff --git a/test/dynamo/test_aot_autograd.py b/test/dynamo/test_aot_autograd.py
index 1f4a464875..335ad240d9 100644
--- a/test/dynamo/test_aot_autograd.py
+++ b/test/dynamo/test_aot_autograd.py
@@ -376,6 +376,64 @@ class AotAutogradFallbackTests(torch._dynamo.test_case.TestCase):
         self.assertEqual(cc.frame_count, 2)
         self.assertEqual(failure_reason, "x is y")

+    def test_multiple_aot_autograd_calls_dupe_args(self):
+        def maybe_dupe_op(x):
+            y = x + 1
+            z = x + 2
+            if x.numel() < 5:
+                return y, y
+            else:
+                return y, z
+        aten = torch.ops.aten
+        lib = torch.library.Library("custom", "DEF")
+        lib.define("maybe_dupe_op(Tensor a) -> (Tensor, Tensor)")
+        lib.impl("maybe_dupe_op", maybe_dupe_op, "CPU")
+        lib.impl("maybe_dupe_op", maybe_dupe_op, "Meta")
+
+        # this is just dealing with the fact that
+        # aot_module_simplified expects submods to always return tuples/lists
+        class WrapperModule(torch.nn.Module):
+            def __init__(self, mod):
+                super().__init__()
+                self.mod = mod
+
+            def forward(self, *args):
+                out = self.mod(*args)
+                if isinstance(out, (list, tuple)):
+                    return out
+                return (out,)
+
+        def compile_submod(input_mod, args):
+            from torch._functorch.aot_autograd import aot_module_simplified
+            from functorch.compile import nop
+
+            class WrapperModule(torch.nn.Module):
+                def __init__(self):
+                    super().__init__()
+                    self.original = input_mod
+                    self.submod = aot_module_simplified(input_mod, args, nop)
+
+                def forward(self, *args):
+                    return self.submod(*args)
+            return WrapperModule()
+
+        def test_compile(fx_g, example_inps):
+            split_gm = torch.fx.passes.split_module.split_module(
+                fx_g, None, lambda node: 1 if 'mul' in str(node) else 0
+            )
+            submod_1_inps = split_gm.submod_0(*example_inps)
+            split_gm.submod_0 = compile_submod(WrapperModule(split_gm.submod_0), example_inps)
+            split_gm.submod_1 = compile_submod(WrapperModule(split_gm.submod_1), submod_1_inps)
+            return split_gm
+
+        @torch._dynamo.optimize(test_compile)
+        def f(a):
+            b, c = torch.ops.custom.maybe_dupe_op(a)
+            return b.mul_(c),
+
+        f(torch.ones(4))
+        f(torch.ones(6))
+
     @patch("torch._functorch.config.debug_assert", True)
     def test_arg_metadata_mutation_on_input_causes_recompile(self):
         class F(torch.nn.Module):
```

running the above gives:
```
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/guards.py", line 550, in __init__
    self.check_fn = self.compile_check_fn(
  File "/scratch/hirsheybar3/work/pytorch/torch/_dynamo/guards.py", line 607, in compile_check_fn
    assert pos_b < len(self.output_graph.graphargs) and pos_a < len(
AssertionError: Deduped args out of bounds
```

Why? `AOTAutograd tries to generate a guard on DuplicateInput(b, b)`. But... it shouldn't! b and c aren't inputs to the dynamo graph, so dynamo doesn't know about them. Whether or not they alias will already have be pre-determined by dynamo's input guards (in this case, whether a.numel() < 5)

cc @ezyang @soumith @msaroufim @wconstab @ngimel @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
@bdhirsh can you close this issue if Voz's PR fixed this, otherwise unassign yourself

**Comment by bdhirsh** [comment]
yep Voz's fix fixes this https://github.com/pytorch/pytorch/pull/93137
