### ISSUE TITLE
Add Python 3.11 for torchaudio

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#93207]
Add Python 3.11 for torchaudio

**Comment by weiwangmeta** [comment]
(py311_audio) weiwangmeta@:~/repos/audio$ pip list |grep torch
torch             2.0.0.dev20230206+cpu
torchaudio        2.0.0a0+9368f33       /fsx/users/weiwangmeta/conda/envs/py311_audio/lib/python3.11/site-packages/torchaudio-2.0.0a0+9368f33-py3.11-linux-x86_64.egg
torchaudio        2.0.0a0+9368f33       /data/home/weiwangmeta/repos/audio
(py311_audio) weiwangmeta@:~/repos/audio$ . test/smoke_test/run_smoke_test.sh 
+++ dirname -- test/smoke_test/run_smoke_test.sh
++ cd -- test/smoke_test
++ python smoke_test.py
(py311_audio) weiwangmeta@:~/repos/audio/test/smoke_test$ 

For linux, it seems py311 works out of box, no change needed to get it working. But the binary is in the form of .egg.

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/test-infra/actions/runs/4111525650/jobs/7095380824 
Linux wheel works for cpu, cuda11.7, cuda11.8.

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/test-infra/pull/2458

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/test-infra/actions/runs/4117263694/jobs/7108391176 MacOS M1 wheels works for CPU.

**Comment by weiwangmeta** [comment]
https://download.pytorch.org/whl/nightly/torchaudio now contains 3.11 wheels. 

[torchaudio-2.0.0.dev20230209+cpu-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-2.0.0.dev20230209%2Bcpu-cp311-cp311-linux_x86_64.whl)
[torchaudio-2.0.0.dev20230209-cp311-cp311-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-2.0.0.dev20230209-cp311-cp311-macosx_10_9_x86_64.whl)
[torchaudio-2.0.0.dev20230209-cp311-cp311-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchaudio-2.0.0.dev20230209-cp311-cp311-macosx_11_0_arm64.whl)
[torchaudio-2.0.0.dev20230209+cu117-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu117/torchaudio-2.0.0.dev20230209%2Bcu117-cp311-cp311-linux_x86_64.whl)
[torchaudio-2.0.0.dev20230209+cu118-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchaudio-2.0.0.dev20230209%2Bcu118-cp311-cp311-linux_x86_64.whl)
