### ISSUE TITLE
`torch.set_num_threads` cannot accelerate the inference performance with increasing the number of cpu cores

### ISSUE THREAD

**Issue by so2bin** [pytorch/pytorch#93247]
### 🐛 Describe the bug

I want to increase the inference performance of pytorch model by increase the number of cpu cores. My machine has totally 72 CPU cores, but the model performance got worse when the cpu number increase by set `torch.set_num_threads`. I got the same result with 2 model, one is Restnet50, another is a NLP transformer model.
* This is the performance curve with cpu cores:
![cpu-resnet](http://zh-ai-group.ks3-cn-beijing.ksyun.com/tmp/cpu-resnet.png)

* This is the performance curve with cpu cores:
![cpu-nlp](http://zh-ai-group.ks3-cn-beijing.ksyun.com/tmp/cpu-nlp.png)

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.11.0+cpu
[pip3] numpy==1.22.4
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

**Comment by min-jean-cho** [comment]
Hi @so2bin , few things you may want to try to finding the optimal number of threads on a given system. Keep in mind that simply increasing the number of threads can cause oversubscription. 

(1) if your system has multiple sockets (can check with `lscpu` command), try setting the thread affinity to a specific socket (e.g., socket 0) to avoid overhead from cross-socket thread migration, remote memory accesses, etc

(2) if your system has hyperthreading enabled (can check with `lscpu` command), try setting the thread affinity to physical cores only. The operators in ResNet50 like GEMM, conv, are compute-intensive ops, which generally benefit from using non-hyperthreading (the overhead from sharing the same core resource for these heavy ops is generally greater than the gain from running both threads at the same time). 

While tuning for the optimal number of threads requires some experimentation, I've generally set the thread affinity and number of threads to the number of physical cores on a single socket as a good starting ground. 

You may also be interested in this tutorial https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#tuning-the-number-of-threads .

**Comment by jingxu10** [comment]
Please also take a reference to https://intel.github.io/intel-extension-for-pytorch/cpu/latest/tutorials/performance_tuning/tuning_guide.html

We also have integrated a launch script to simplify the execution. Please take a reference to https://github.com/pytorch/pytorch/blob/master/torch/backends/xeon/run_cpu.py

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions:[ https://discuss.pytorch.org/](https://discuss.pytorch.org/)

**Comment by so2bin** [comment]
> 

Thank you very much. I will try your sugguestion.
