### ISSUE TITLE
Bad conversion from torch.split(2d_tensor,splitsize_list) to SplitToSequence OP (onnx export)

### ISSUE THREAD

**Issue by enerai** [pytorch/pytorch#93264]
### 🐛 Describe the bug

```python
torch.split(concat_feat_mat,idx_list)
```
When I use the instruction in model define and try to export it as onnx model, some execution errors are found. 

> the onnx converter will construct a SplitToSequence with seq(tensor(int64)) type input, which is not supported.

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.10.8 (main, Nov 24 2022, 08:09:04) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.15.7-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-model-summary==0.1.1
[pip3] torch==1.13.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==0.13.1
[pip3] torchinfo==1.7.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0           py310hca72f7f_0  
[conda] mkl_fft                   1.3.1           py310hf879493_0  
[conda] mkl_random                1.2.2           py310hc081a56_0  
[conda] numpy                     1.23.5          py310h9638375_0  
[conda] numpy-base                1.23.5          py310ha98c3c9_0  
[conda] pytorch                   1.13.1                 py3.10_0    pytorch
[conda] pytorch-model-summary     0.1.1                      py_0    conda-forge
[conda] torch-tb-profiler         0.4.1                    pypi_0    pypi
[conda] torchaudio                0.13.1                py310_cpu    pytorch
[conda] torchinfo                 1.7.1              pyhd8ed1ab_0    conda-forge
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.14.1                py310_cpu    pytorch

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by enerai** [comment]
> `torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.
> 
> Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

Thanks, I will try it.
