### ISSUE TITLE
Higher order derivatives are very time consuming in pytorch

### ISSUE THREAD

**Issue by HongLouyemeng** [pytorch/pytorch#93270]
### 🚀 The feature, motivation and pitch

The Nth order Taylor approximation requires the computation of higher order derivatives, but pytorch needs to create a new computational graph when computing higher order derivatives, which is very time consuming. Can you provide a new function to compute higher order derivatives efficiently?

### Alternatives

`def taylor(fun, point, degree):
    taylor_series = [fun.data]
    for i in torch.arange(0, degree, device=point.device):
        grads = grad(fun, point, create_graph=True)[0]
        data = grads.data / torch.lgamma(i + 2).exp()
        taylor_series.append(data)
        fun = grads
    return taylor_series`

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @jianyuh @mruberry @walterddr @IvanYashchuk @xwang233

**Comment by lezcano** [comment]
You probably want to have a look at https://pytorch.org/functorch/nightly/generated/functorch.jvp.html and iterating it if you want to compute the Taylor approximation to a function fast. Would that work?

**Comment by HongLouyemeng** [comment]
> You probably want to have a look at https://pytorch.org/functorch/nightly/generated/functorch.jvp.html and iterating it if you want to compute the Taylor approximation of a function fast. Would that work?

func_output in **jvp** is not callable..

**Comment by IvanYashchuk** [comment]
PyTorch and JAX have good compatibility due to DLPack, making it simple to use JAX (refer to this link for an example: https://gist.github.com/mattjj/e8b51074fed081d765d2f3ff90edf0e9
So it's very easy to get started with https://jax.readthedocs.io/en/latest/jax.experimental.jet.html.

An external package for PyTorch that integrates JAX's jets could be useful for others interested in this feature. However, implementing it effectively within PyTorch would require a lot of effort and is unlikely to happen in the near future.
Paper describing JAX implementation: https://openreview.net/forum?id=SkxEF3FNPH

**Comment by HongLouyemeng** [comment]
> PyTorch and JAX have good compatibility due to DLPack, making it simple to use JAX (refer to this link for an example: https://gist.github.com/mattjj/e8b51074fed081d765d2f3ff90edf0e9 So it's very easy to get started with https://jax.readthedocs.io/en/latest/jax.experimental.jet.html.
> 
> An external package for PyTorch that integrates JAX's jets could be useful for others interested in this feature. However, implementing it effectively within PyTorch would require a lot of effort and is unlikely to happen in the near future. Paper describing JAX implementation: https://openreview.net/forum?id=SkxEF3FNPH

Thanks for your reply.

**Comment by lezcano** [comment]
What do you mean by `func_output`? What is the issue exactly with the solution I proposed above?

As Ivan mentioned, there may be faster ways of computing this. For example, that paper mentions that this sort of computation benefits from using CSE. This will be automatically done by `torch.compile` whenever forward AD (and its repeated application) is supported in PyTorch 2.0 (cc @Chillee)

**Comment by HongLouyemeng** [comment]
> What do you mean by `func_output`? What is the issue exactly with the solution I proposed above?
> 
> As Ivan mentioned, there may be faster ways of computing this. For example, that paper mentions that this sort of computation benefits from using CSE. This will be automatically done by `torch.compile` whenever forward AD (and its repeated application) is supported in PyTorch 2.0 (cc @Chillee)

Hi, **lezcano, Thanks for your attention**, I can't get higher order derivatives with **jvp**, because the input of **jvp** needs to be a function, But the return value of **jvp** is two values. Using the loop, I can only get the first order derivative repeatedly. I wonder if this is why I am using it incorrectly.

**Comment by lezcano** [comment]
What about
```python
from functools import lru_cache, partial
import torch
from torch.func import jvp

one = torch.ones(())
f = torch.sin


@lru_cache()
def d(x, n):
    if n == 1:
        return jvp(f, (x,), (one,))[1]
    else:
        return jvp(partial(d, n=n-1), (x,), (one,))[1]


z = torch.zeros(())
print(d(z, 1))
print(d(z, 2))
print(d(z, 3))
print(d(z, 4))
```

**Comment by lezcano** [comment]
I just realised that the LRU cache is not intelligent enough as to not recompute things in this case, but it should be clear that, if what you want is the Taylor approximation, you can compute it iteratively.

Note also that here I used functions from R to R for simplicity, but you can do the same with functions from R^n to R^k. You should be able to compute the n-th order derivative at (v_1, ..., v_n). You may also compute its Taylor series which in geometry, as Ivan mentioned, is sometimes called the n-th Jet of a map.

**Comment by HongLouyemeng** [comment]
> I just realised that the LRU cache is not intelligent enough as to not recompute things in this case, but it should be clear that, if what you want is the Taylor approximation, you can compute it iteratively.
> 
> Note also that here I used functions from R to R for simplicity, but you can do the same with functions from R^n to R^k. You should be able to compute the n-th order derivative at (v_1, ..., v_n). You may also compute its Taylor series which in geometry, as Ivan mentioned, is sometimes called the n-th Jet of a map.



> 

**Thanks for your advice**😊

**Comment by lezcano** [comment]
Closing this for now. If anyone wants to propose a CSE-based algorithm like that of JAX, we can discuss it in a different issue, but again, we will get these once we have jvp in PyTorch 2.0
