### ISSUE TITLE
fully_shard: load optim state not tested

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#93280]
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/blob/master/test/distributed/_composable/fully_shard/test_fully_shard_optim_checkpoint.py are unittests for fully_shard + optim checkpoint, but these do not appear to actually test the load API. 

Marking as high pri due to the composability effort requiring this.

cc @ezyang @gchanan @zou3519 @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @vincentqb @jbschlosser @albanD @janeyx99

**Comment by janeyx99** [comment]
@rohan-varma could you specify what type of effort you would want to see here?

**Comment by rohan-varma** [comment]
@janeyx99 I think this is mostly a task for distributed team, sorry if it wasn't clear. We have some custom optim state dict loading APIs and need to test them in this file: https://github.com/pytorch/pytorch/blob/master/test/distributed/_composable/fully_shard/test_fully_shard_optim_checkpoint.py
