### ISSUE TITLE
Convention for printing the "internal representation" of compiled functions from inductor/other backends

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93315]
### 🐛 Describe the bug

It doesn't really make sense to print a function wrapped in torch.compile, but as a framework developer sometimes I am dealing with compiled_fn prior to frame installation and it would be nice to be able to debug print them and see what was compiled with them. Typically you don't get anything useful because it's some trampoline function (like `align_inputs`) before eventually getting to some eval'ed code. But maybe keeping the graph around for printing here would be handy? IDK, food for thought.

BTW, printing compiled_fn (via a series of hacks) is how I diagnosed #93308

### Versions

master

cc @mlazos @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by eellison** [comment]
logging has fixed this i belive
