### ISSUE TITLE
[feature request] Low-discrepancy quasi-random sampler (Sobol sequences)

### ISSUE THREAD

**Issue by Balandat** [pytorch/pytorch#9332]
It would be nice to have a native low-discrepancy quasi-random sampler available in pytorch (for things like qMC numerical integration etc.).

Ideally that would be implemented on a low-level in ATen, and have a convenience constructor on the python side (not sure exactly where that would live).

I have cython code for a Sobol generator with Owen scrambling that I'd be willing to port over for this, provided if that would be of interest.

**Comment by soumith** [comment]
@vishwakftw would you be interested in implementing this?

**Comment by vishwakftw** [comment]
I could have a look at it and let you know in a day or two, if that's fine.

**Comment by Balandat** [comment]
As I said, I have a cython implementation must of which is plain C, so porting that shouldn't be all that bad.

**Comment by Balandat** [comment]
cc @kkashin

**Comment by vishwakftw** [comment]
@Balandat could you point me to the Cython implementation? I am interested in getting an idea of how this would be implemented.

**Comment by Balandat** [comment]
@vishwakftw, please see the attached files (should be `sobol.pyx` and `test_sobol.py`). At the core are the array literals defined up top, the actual logic is written in low-level C functions. 

Calling `draw` on an instance of `SobolEngine` will generate points of a space-filling sequence. The important thing to note is that in order to continue filling the `[0, 1]^dimen` space "in between" the already drawn points, draws need to continue in sequence (i.e. the `num_generated` variable should not be reset). A barebones implementation would just not deal with that complexity, but instead just so a single draw of N points in `[0, 1]^dimen`. 

See the test cases for some more context on how to use this.

Let me know if you have any questions.

[sobol.txt](https://github.com/pytorch/pytorch/files/2193404/sobol.txt)
[test_sobol.txt](https://github.com/pytorch/pytorch/files/2193441/test_sobol.txt)

**Comment by Balandat** [comment]
@vishwakftw, do you think it's feasible to port this over? 

(@darbour, @bletham, @bkarrer, @gpleiss, @jacobrgardner, this would be nice to have for qMC, for our purposes in particular for MC evaluation of batch acquisition functions)

**Comment by vishwakftw** [comment]
Sorry for the delay @Balandat . I did go through the CPython implementation, and I think this can be ported into ATen. I should be able to start working on it in a couple days and will keep you posted.

**Comment by vishwakftw** [comment]
@Balandat I have some primitive designs for the implementation, and I thought I should clear up which one to use proceeding further:
1. `SobolEngine` in Python: Since the implementation in `CPython` is available, it should not be hard to reproduce this in PyTorch. This would include writing a new class, and the methods associated with it in pure Python.

- Pros: Not required to deal with a `at::Generator` object, and seeding becomes easier. Code is much more easy to read
- Cons: Possibly slow due to Python itself.

2. `SobolEngine` in `ATen`. This would involve a lot more extra lines of code. Similar to the above, make a new class named `SobolEngine`, and methods associated with it.

- Pros: Should be faster than the Python implementation.
- Cons: Seeding is not easy I think, requirement of `at::Generator` object.

Please let me know your views.

**Comment by Balandat** [comment]
@vishwakftw, no sure I completely follow (I'm not familiar with the `at::Generator` objects).

1. Do you suggest doing al the looping etc. that's done in the C-code in python? That would be inadmissibly slow (that's why this was moved to cython). In general, performance in generating these Sobol samples is critical, since it would be used to do things like quasi-Monte-Carlo integration, for which more samples are better (we're talking millions of samples here).

2. What's the requirement of the `at::Generator` object for seeding? Do you think it would be a challenge to keep track of the position in the sequence of samples? This relates to my comment above:
> Calling draw on an instance of `SobolEngine` will generate points of a space-filling sequence. The important thing to note is that in order to continue filling the `[0, 1]^dimen` space "in between" the already drawn points, draws need to continue in sequence (i.e. the num_generated variable should not be reset).

**Comment by vishwakftw** [comment]
Thank you, @Balandat. Actually, I think I should be able to circumvent the problem with `at::Generator` and porting to C++ won’t be an issue. The reason I thought it was required is because of the `randint` in the CPython implementation.

I just wanted to confirm how you would have liked the implementation to be, hence the question.

**Comment by vishwakftw** [comment]
@soumith 

I have a question about integrating the `SobolEngine` in Python. There are two approaches:
1. Define the key methods involved for the `SobolEngine` in ATen, and write the class in Python in the usual way:
```
class SobolEngine(object):
    def __init__(self ,.... ):
        # the usual definitions
```
The methods for `SobolEngine` will be taken exposed via `ATen` as done for general native functions, except for the fact that the methods exposed will be private i.e., prefixed with a `_` and then used (e.g.: `_unique`, `broadcast_tensors`). This will prevent general use while satisfying the requirements.

2. Create a class `SobolEngine` in `ATen` itself, and then interface it to Python by creating bindings in `torch/csrc`, as done for `torch.device`.

Approach 1 is less complex compared to Approach 2 and Approach 2 is possibly unnecessary, but I am not sure if Approach 1 would cause any performance issues.

Please let me know your thoughts about this, after which I can send in a PR. Thank you.

**Comment by Balandat** [comment]
Maybe this provides some useful side context: One of the main use cases will be qMC integration. E.g. if `f : [0, 1]^d -> (-inf, inf)` then we'll often want to do something like

```
sobol = torch.<SOMEWHERE>.Sobol(dim=d, scramble=True)
xqmc = sobol.draw(10000)
fqmc = f(xqmc).mean()
```

Or one could have a top-level function of the form `xqmc = torch.sobol(10000, dim=d)` to reduce boilerplate code.

**Comment by Balandat** [comment]
#10505 implements this, but is still significantly slower than the Cython implementation, possibly due to some unwanted autograd involvement (see discussion on the PR).

@soumith, @ezyang, @apaszke, who would be able to figure out these perf issues?
