### ISSUE TITLE
aten::int_repr not supported in torch.onnx.export

### ISSUE THREAD

**Issue by mgehre-amd** [pytorch/pytorch#93345]
### 🚀 The feature, motivation and pitch

```python
import torch.onnx
import torch

class Model(torch.nn.Module):
    def forward(self, x):
        y = torch.quantize_per_tensor(x, 1., 0, torch.qint8)
        return y.int_repr()

model = Model()
model.eval()
args = torch.ones(1, 1, 28, 28)
print(model(args))

torch.onnx.export(model,               # model being run
                  args,                         # model input (or a tuple for multiple inputs)
                  "out.onnx",   # where to save the model (can be a file or file-like object)
                  opset_version=16,          # the ONNX version to export the model to
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'])
```
currently says
```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::int_repr' to ONNX opset version 16 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

I'd like to see this supported.

quantize_per_tensor+ int_repr + clamp is a useful way to represent quantization to less than 8 bits.

### Additional context

I have never developed on pytorch. But considering that dequantize(quantize_per_tensor(x)) already emits a cast op in ONNX,
I think the effort to do this would be small. I might be able to do it you could provide pointers about where to implement and where to add tests.

**Comment by thiagocrepaldi** [comment]
'aten::int_repr' is not supproted by torch.onnx.export and there is no plan to support it

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
