### ISSUE TITLE
Dynamo doesn't support user defined decorator

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#93340]
### 🐛 Describe the bug

Repro
```
def fn(x):
    return torch.distributions.Categorical(probs=x).entropy()

opt_fn = torch._dynamo.optimize("eager")(fn)
x = torch.rand([4, 4])
print(opt_fn(x))
```
Error
```
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 990, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/scratch/ybliang/work/repos/pytorch/torch/_dynamo/variables/torch.py", line 205, in call_function
    self.as_python_constant()(
TypeError: finfo(): argument 'type' (position 1) must be torch.dtype, not NoneType

from user code:
   File "/scratch/ybliang/work/repos/pytorch/debug/debug1.py", line 23, in fn
    return torch.distributions.Categorical(probs=x).entropy()
  File "/scratch/ybliang/work/repos/pytorch/torch/distributions/categorical.py", line 130, in entropy
    min_real = torch.finfo(self.logits.dtype).min
```
This is because ```self.logits``` is decorated by ```lazy_property``` and Dynamo doesn't support generic decorator well.
https://github.com/pytorch/pytorch/blob/91a4947e2838be0420cc920ad35968f742dab24b/torch/distributions/categorical.py#L90-L92

I think there are two options to consider:
* If decorator is a common pattern used when writing neural network(personally I doubt), we should figure out a way to support it.
* Otherwise, maybe just special handle the ```Categorical.logits``` and similar attribute.

### Versions

N/A

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by jon-chuang** [comment]
@yanboliang 

I think in this case we can dispatch getattr on `@lazy_property`.

However, more generically, I think it is possible to fix by dispatching if the property has a `__get__` attribute: `if hasattr(subobj, "__get__")`

I don't think there are generic ways to handle wrappers.
