### ISSUE TITLE
[pt2] compiled model with cat and expand gives wrong results

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#93357]
### 🐛 Describe the bug

`torch.compile` leads to wrong results in the following program. This only happens if we operate on a parameter of a model. Please see the comments for the results of the variants. 

```python
import torch
import torch.nn as nn

p0 = torch.nn.parameter.Parameter(torch.tensor([4, 4, 5, 5, 4, 4, 4, 7, 4]), requires_grad=False)
def fn():
    m = torch.cat([p0, p0], dim=0)
    o = m.expand(1, 1, 1, 18)
    return o

with torch.no_grad():
    ret_eager = fn()

    compiled = torch.compile(fn, backend='inductor', mode='default', dynamic=False, fullgraph=True, )
    ret_compiled = compiled()

    assert torch.allclose(ret_eager, ret_compiled), (ret_eager, ret_compiled) # right; no error

print(f'==== fn OK! ====')

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.p1 = torch.nn.parameter.Parameter(torch.tensor([4, 4, 5, 5, 4, 4, 4, 7, 4]), requires_grad=False) # (9,)
        # self.p1 = torch.nn.parameter.Parameter(torch.randint(-5, 5, (9,)), requires_grad=False) # NOTE: also error
        # self.p1 = torch.nn.parameter.Parameter(torch.tensor([4, 4, 5, 5, 4, 4, 4, 7, 4]).float(), requires_grad=False) # NOTE: also error
        # self.p1 = torch.tensor([4, 4, 5, 5, 4, 4, 4, 7, 4]) # NOTE: also error

    def forward(self, ):
        v0 = torch.cat([self.p1, self.p1], dim=0) # v0: (18,)
        # NOTE: directly return v0 works fine
        # NOTE: torch.cat([p0, p0], dim=0) works fine
        v5 = v0.expand(1, 1, 1, 18) # v5: (1, 1, 1, 18)
        return v5

with torch.no_grad():
    model = Model()
    ret_eager = model()

    compiled = torch.compile(model, backend='inductor', mode='default', dynamic=False, fullgraph=True, )
    ret_compiled = compiled()

    assert torch.allclose(ret_eager, ret_compiled), '\n'.join(map(str, ["", ret_eager, ret_compiled]))

'''
Traceback (most recent call last):
  File "/home/colin/code/bug.py", line 38, in <module>
    assert torch.allclose(ret_eager, ret_compiled), '\n'.join(map(str, ["", ret_eager, ret_compiled]))
AssertionError: 
tensor([[[[4, 4, 5, 5, 4, 4, 4, 7, 4, 4, 4, 5, 5, 4, 4, 4, 7, 4]]]])
tensor([[[[136450624, 136476736,         5,         5,         4,         4,
                   4,         7,         4,         4,         4,         5,
                   5,         4,         4,         4,         7,         4]]]])
'''

print(f'==== model OK! ====')
```

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230131+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230131+cu117
[pip3] torchaudio==2.0.0.dev20230131+cu117
[pip3] torchvision==0.15.0.dev20230131+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230131+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230131+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230131+cu117          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @chunyuan-w @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
@Co1lin to help us triage these issues: are you running a fuzzer on pt2, or are these extracted from real models?

**Comment by ganler** [comment]
@ezyang Hi, we (@Co1lin, @Kristoff-starling and me) are running a fuzzer (wll be upstreamed later to [nnsmith](https://github.com/ise-uiuc/nnsmith) when it becomes stable) against PT2 recently (after https://github.com/pytorch/pytorch/issues/92674#issuecomment-1398701626). **So by default you can assume bugs reported by us are fuzzing bugs.**

To explain a bit our workflow: We only report bugs with distinct error messages after careful inspection (including those you marked as potential similar ones) by filtering those w/ (i) dup error msg, (ii) same structure after bug minimization, and (iii) human inspection to see if the model is too ood to be impactful. These error-inducing models, though look odd, are actually similar to those in PyTorch's developer tests as we did the program synthesis by "learning" from "actual" usage. Meanwhile, all the models are made to ganrantee structural validity (with some PL magic lol) (for example, giving -1 to a kernel size may produce bugs but is impossible to be user-facing or compiled).

Please kindly let us know if any kind of bugs are unwanted or anything we should be aware of when reporting a fuzzing bug! We are more than happy to tweak the fuzzer to respect PyTorch's issue reporting guidelines.

**Comment by ezyang** [comment]
It's fine. PT2 has a lot of bugs right now, so while we do want to fix these, we are probably going to prioritize ones that show up in actual models in the short term.

**Comment by ganler** [comment]
All right, we will then explicitly say that our bugs are fuzzing bugs and please do prioritize other real-model bugs.

**Comment by ngimel** [comment]
That said, the bugs you've reported are high quality, and as you say, don't look like specially fuzzed set that's impossible to see in practice. They did reveal a few common themes that are easy to encounter in practice (even if they are not in our common testing/benchmarking suite), like inplace ops handling (we are working on that), or cpu codegen errors caused by improper use of `__restrict__` (also working on that).
