### ISSUE TITLE
[ONNX] Will symbolic function be deprecated?

### ISSUE THREAD

**Issue by likholat** [pytorch/pytorch#93370]
### 🚀 The feature, motivation and pitch

I usually use the `symbolic` function to support custom operators: 

https://github.com/pytorch/pytorch/blob/6f4dea562de0a1388f3d63b5ae1ecc15a47d254f/test/onnx/test_custom_ops.py#L65-L74

But with PyTorch `1.13.1` I get the warning:
```
FutureWarning: 'torch.onnx._patch_torch._graph_op' is deprecated in version 1.13 and will be removed in version 1.14.
Please note 'g.op()' is to be removed from torch.Graph. 
Please open a GitHub issue if you need this functionality.
```

Does this mean the [static symbolic method](https://pytorch.org/docs/stable/onnx.html#static-symbolic-method) will be deprecated?

### Alternatives

Is there a new way to support unsupported operators?

### Additional context

I've found the similar issue, but there is no answer: https://github.com/pytorch/pytorch/issues/90054

**Comment by justinchuby** [comment]
Hi! We are making some internal changes that should not affect the interface

**Comment by likholat** [comment]
Hi, @justinchuby! Thanks for the reply!

**Comment by Daniel-Ehrhardt** [comment]
So to summarize, the `g.op()` function will stay and the deprecation warning is wrong? @justinchuby 

By the way, it's still suggested to use for custom symbolic functions in the [v2.0 documentation](https://pytorch.org/docs/stable/onnx.html#onnx-exporter-internals).

**Comment by justinchuby** [comment]
Yes. The warning should have been removed in 2.0. Let us know if that’s not the case.

**Comment by ekaden** [comment]
@justinchuby Unfortunately, Commit #94746 breaks the following code:

```python
import torch


class SubModelImpl(torch.autograd.Function):
  @staticmethod
  def symbolic(g, x):
    return g.op('custom::Identity', x).setType(x.type())

  @staticmethod
  def forward(ctx, x):
    return x


class SubModel(torch.nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return SubModelImpl.apply(x)


class Model(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.submodel_trace = torch.jit.trace(SubModel(), torch.randn((5, ), dtype=torch.float32))

  def forward(self, x: torch.Tensor, n: int) -> torch.Tensor:
    for _ in range(n):
      x = self.submodel_trace(x)
    return x


model_script = torch.jit.script(Model())
x = torch.randn((5, ), dtype=torch.float32)
n = 3

torch.onnx.export(
  model_script,
  (x, n),
  '/tmp/test.onnx',
  verbose=True)
```

The error message reads:
```
RuntimeError: 0 INTERNAL ASSERT FAILED at "/tmp/pytorch/torch/csrc/jit/ir/ir.cpp":587, please report a bug to PyTorch. 6 not in scope
```

The example does not function with the latest nightly PyTorch build either, but it works as expected in PyTorch v1.13.1. I was wondering if you could provide any suggestions or recommendations?

**Comment by justinchuby** [comment]
Please create a new issue and the errors are different. Thanks!
