### ISSUE TITLE
AssertionError: torch.* op returned non-Tensor int call_function aten.len

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#93429]
### 🐛 Describe the bug

The following fails with the error

```
AssertionError: torch.* op returned non-Tensor int call_function aten.len
```

```
import torch
import torch._dynamo as dynamo

@dynamo.optimize()
def f():
    return torch.ops.aten.len("hello")

f()
```

Since torch.ops.* accesses the JIT operator registry instead of just the c10 registry, it is possible to access many non-Tensor functions. 11 Torch-MLIR e2e tests fail because of this.

### Error logs

Full stacktrace here: https://gist.github.com/silvasean/a5e60ef6cc777132fe90953b6fdbb019

### Minified repro

See above.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
this is fixed

```
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ cat > a.py
import torch
import torch._dynamo as dynamo

@dynamo.optimize()
def f():
    return torch.ops.aten.len("hello")

f()
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ python a.py
(/home/ezyang/local/a/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/a/pytorch (f987a3be)]$ 
```
