### ISSUE TITLE
Accuracy minifier should also work even if an exception is raised

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93436]
### 🐛 Describe the bug

If you use accuracy minifier on a model that errors when optimized, the accuracy minifier does nothing. But accuracy minification should be a superset of both testing for accuracy failures AND raised exceptions.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Do we still want to keep this issue open? Or it's ok to close it?
