### ISSUE TITLE
Should torchdynamo specialize on nn.Module

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#93432]
This is an open design question with several discussion threads, and unclear motivations and perf/risk tradeoffs.  I'm opening the issue in part to organize the discussion, and see if we can align on a direction.

There are 2 behaviors that are interesting and somewhat orthogonal.

1. dynamo **specializes** on nn.module instances, meaning it places a (ref?) to the module in its traced graphmodule's `.parameters` field, and guards only on the id() of the nn.module matching at runtime.  It also monkeypatches the module's __setattr__ so that it can detect (most) changes to the module at runtime, and invalidate the specialization, causing a recompile
2. **`call_module`** nodes are inserted in the graph for nn.Modules, rather than tracing into the module and recording torch function calls.

(1) is a potential issue in that we cannot detect modifications to C++ part of nn.Module that don't go through python API, e.g. some sketchy stuff FSDP does).  But it is also an important perf optimization because it reduces the number of guards in the system, and provides a way for backend compilers to keep a list of .parameters() tensors separate from input tensors, and apply specializing optimizations just to the parameters.

(2) could be an issue if code inside nn.modules isn't well behaved- tracing deeper would be safer, at the cost of more exposure to having graph-breaks.  It has been proposed to change just (2) to unify dynamo's IR trace level, even if (1) is left as it is.  

For now i'm not proposing to rush to a change or a decision, but i'd like to sharpen the above description, including the set of constraints and problems and goals based on your feedback.

cc @ezyang @soumith @msaroufim @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Is this issue still relevent? Do we want to keep it open?
