### ISSUE TITLE
Partitioner that doesn't require functionalized graph

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93438]
### 🐛 Describe the bug

We should have a partitioner that doesn't require functionalized graph; this would allow us to easily ablate functionalization when debugging issues caused by functionalization.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Is this still an issue?

**Comment by ezyang** [comment]
This is still a thing, although I haven't recently had to debug functionalization issues.
