### ISSUE TITLE
AOTAutograd generates useless tangent inputs for SymInt outputs

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93442]
### 🐛 Describe the bug

If you AOTAutograd a graph that returns an int, the joint forward-backward will take an int tangent for this argument. This is useless. It is also wrong: the int tangent will be specified to be a specific symbolic int, but in fact you will always get None instead from the autograd engine. 

This is annoying to fix because we must determine what the tangents to pass in are outside of the joint forwards backwards, but the calculation what actually needs tangents is inside joint forward backwards. Need to hoist it out.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @bhdirsh

**Comment by ydwu4** [comment]
Is this still an issue? Do we want to keep it open?
