### ISSUE TITLE
Partitioner generates useless constant SymInt edges between forward-backwards

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93443]
### 🐛 Describe the bug

Suppose you have a size saved for backwards; at time of tracing that node, it was symbolic. However, later, we discovered it was in fact constant (because, e.g., we added it to a parameter). The FX graph still passes the symbolic shape around, but we happen to know it's constant. Fine. Then, we run the partitioner. The partitioner can't tell that a SymInt is constant, and will generate an edge from forwards to backwards to transfer the constant int, which is totally unnecessary.

Symbolic shapes branch is currently hacking around this with https://github.com/pytorch/pytorch/pull/84246/commits/1a5ff545370639f17d40f5f6157eefd9fc74d93b which forces constant nodes to get const propagated before we partition.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Is this issue still relevant?
