### ISSUE TITLE
TensorWithTFOverrideVariable don't store fake tensor (they store real tensor)

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93453]
### 🐛 Describe the bug

The proximal cause for the problem is this line in utils.py:

```
    def wrap_to_fake_tensor(e, fake_mode):
        if type(e) in (torch.Tensor, torch.nn.Parameter):
            return wrap_fake_exception(
                lambda: make_fake_tensor(
                    e, fake_mode, static_shapes=config.dynamic_shapes is False
                )
            )
        else:
            return e
```

When we attempt to wrap the tensor to become fake, we bypass this process if it's not exactly a Tensor or Parameter. This means the real tensor gets stored on `example_value`.

This causes problems for dynamic shape guards as failing to fakeify the tensor here means subsequent call to `super().__torch_function__` looks at the returned tensor and says "well golly I've never seen this tensor before, I guess it must be an input" and generates guards that are impossible to actually fulfill.

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @vkuzo

**Comment by ydwu4** [comment]
Is this issue still relevant?

**Comment by ezyang** [comment]
I think lazos hit this with a refactor
