### ISSUE TITLE
Strategy for optimizing away transient dynamic shapes / device syncs

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93466]
### 🐛 Describe the bug

Context: https://github.com/pytorch/xla/issues/4248

The key subtlety here is that although in principle we can perform these optimizations, we need to make sure not to "give up" too early by graph breaking immediately when the sync/dynamically sized output occurs. This may mean some metadata associated with tensors has to be computed more lazily (since to compute it eagerly would require a sync.) Also related to unbacked symints.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym

**Comment by ydwu4** [comment]
Is this issue still relevant?

**Comment by ezyang** [comment]
Going to obsolete this issue, but the general idea is still valid. @yanboliang implemented the boolean mask to torch where optimization
