### ISSUE TITLE
ONNX export question (using torchdynamo)

### ISSUE THREAD

**Issue by zfigov** [pytorch/pytorch#93492]
### 🐛 Describe the bug

I would like to export a model that can be run either as an ONNX file. My model fails with both the scripting and the trace options. Using PyTorch 2.0 I (uses the torchdynamo) I can create convert my model (to an optimized on) that runs. Is there a way to export the model to ONNX without a dependency on trace/script? 

Model_dynamo = torch.compile(model,backend="onnxrt_cpu",mode="max-autotune")
Here an export for ONNX? 
exported_model = torch._dynamo.export(Model_dynamo , input)

### Error logs

no error

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
What that error message is saying is your model is trying to update weights. The export isn't going to capture this weight update, and so it is telling you so. If you don't need weight updates, try removing it from your model and exporting. If you do need it, I believe @SherlockNoMad got some alignment on how we were going to represent export graphs with mutations--do you know who is signed up to implement it?

**Comment by zvif** [comment]
I don't need the weight updates (I can freeze the model)
Is this just to set requires_grad of all the layers to False? Or something else? Could you point me to the documentation? 
Thanks

**Comment by ezyang** [comment]
We aren't updating the backwards/optimizer step, so it must be something else in the model that is causing updates. Setting eval() might help. Otherwise you will need to look. You could also unsafely comment out the error that's failing

**Comment by williamwen42** [comment]
Is this still an issue?
