### ISSUE TITLE
TH/THC/THNN/THCUNN etc latests

### ISSUE THREAD

**Issue by an-kumar** [pytorch/pytorch#935]
this pytorch repo has an explicit lib/ directory with copies of TH, THC, THNN, etc. But there are also, seemingly not necessarily the same (at least, not from a git submodule standpoint), copies of those libraries across the torch/ github repo (in torch7, cutorch, nn, etc). I'm looking to use some of these interfaces in a project of mine, and I'd like to set it up so that I can continually get the most recent version of these libraries. Where should I clone from, and is there plans to set up a seperate, stand-alone torch library for the code in lib/?

By the way, if this is on the roadmap, I would be interesting in helping out set it up.

**Comment by soumith** [comment]
they are git subtrees. If you want your local copies to have the latest of these libs, have a look at these commands to update them:
https://github.com/pytorch/pytorch/wiki/Updating-TH,-THC,-THNN,-THCUNN-subtrees
