### ISSUE TITLE
iter(TensorVariable) fail

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#93514]
### 🐛 Describe the bug

Dynamo does not support iterating thru a tensor variable so far. Dynamo fail to trace even if the first dimension of the TensorVariable is static. In this case, the fix is simple since we can unroll the loop and generated items by calling `getitem`. But the problem becomes more complex if the first dimension of the tensor variable is dynamic.

We have discussions between shunting314 , @ezyang , @voznesenskym , @suo , @Chillee . Here are some thoughts for possible solutions
- rewrite user code by using torch.map explicitly
- let user pass in the information indicating if a dimension is dynamic or not
- assume the dimension to be static, specialize on that when compiling the fx graph and add a guard to the guard set

So the underlying problem is how we handle loop with potentially variable number of iterations.

User code that fail to be traced: https://www.internalfb.com/code/fbsource/[ca89130b9eae0efd5bb1cbbff1006cc1556d0b4f]/fbcode/vision/fair/detectron2/detectron2/export/c10.py?lines=483-489 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by williamwen42** [comment]
Looks like dynamo supports this today?
```python
import torch

inp = torch.rand(3, 10)

def f(inp):
    return torch.cat(
        [torch.relu(x) for x in inp], dim=0
    )

opt_f = torch.compile(f)
print(opt_f(inp))
print(opt_f(torch.rand(5, 20)))
```
Closing as fixed.
