### ISSUE TITLE
 [feature request]- torchvision.transforms.ColorJitter Enhancement

### ISSUE THREAD

**Issue by neherh** [pytorch/pytorch#9351]
Currently, the ColorJitter function only takes in a single float value for the parameters brightness, contrast, saturation and hue. The value is chosen uniformly from  [max(0, 1 - brightness), 1 + brightness] (minus hue). What would improve this function is to be able to set your min and max bounds by inputting a tuple as a parameter.

**Comment by vishwakftw** [comment]
Please open this issue in [vision](https://github.com/pytorch/vision).

**Comment by SsnL** [comment]
See @vishwakftw 's comment above. Thank you!
