### ISSUE TITLE
[Question] How to debug "munmap_chunk(): invalid pointer" when compiling to triton?

### ISSUE THREAD

**Issue by vedantroy** [pytorch/pytorch#93516]
I'm trying to  use torchdynamo to compile a function to triton.
My logs indicate that the function optimizes without issue,

but when running the function on a given input, I just get "munmap_chunk(): invalid pointer" w/o a stack trace / any useful debugging information.

I'm wondering how to go about debugging such an error.
Are any developers familiar with what this indicates?

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
this passes now, try upgrading

```
$ python a.py
Finished optimizing ...
/data/users/ezyang/a/pytorch/torch/_inductor/compile_fx.py:90: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(

```
