### ISSUE TITLE
Test for multiple instances inference

### ISSUE THREAD

**Issue by Valentine233** [pytorch/pytorch#93524]
Need to add a test for multiple instances inference.

One scenario is the cache contention, please see [#1400 ](https://github.com/pytorch/torchdynamo/pull/1400).

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by ezyang** [comment]
cc @xw285cornell

**Comment by chunyuan-w** [comment]
WIP: https://github.com/pytorch/pytorch/issues/93522

**Comment by chunyuan-w** [comment]
I'll un-assign myself since CPP wrapper has already fixed the GIL issue: https://github.com/pytorch/pytorch/pull/111888

**Comment by leslie-fang-intel** [comment]
We have multi process testing on multi numa nodes system since we will run process per numa node.

**Comment by leslie-fang-intel** [comment]
I am going to close this issue since we already have the testcase for Realtime test scenario which runs 4 cores/per process.
