### ISSUE TITLE
invalidation policy for codecache

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#93527]
Currently inductor's code cache ([codecache.py](https://github.com/pytorch/torchdynamo/blob/main/torchinductor/codecache.py)) is never invalidated. That means that any improvements or bugfixes downstream of source code generation will not show up, which has bitten people a few times. In the case of a bug (e.g. a triton bug), currently the only way to fix it is to manually delete the cache.

@voznesenskym proposed that we use the git commit hash to invalidate the cache. That's pretty easy; basically just add `torch.__version__` to the cache dir name and call it a day. That way, if the user gets a new version of PyTorch with improvements/bugfixes they can be sure that torchinductor will make use of them.

@eellison doesn't like invalidating by git commit hash very much. It would slow down development, as each commit would bust the inductor cache and trigger lots of annoying compilations.

Middle grounds:
- Take the hash of some subtree that affects codegen (torchinductor/ + triton version?), so that other changes to PyTorch don't bust your cache during development.
- Use an explicit version number that we manually bump.

Thoughts?

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by wconstab** [comment]
any update on this?

**Comment by jansel** [comment]
I believe this was fixed on the triton side.
