### ISSUE TITLE
[TorchInductor] Add support for Pascal GPUs (P100, GTX 1080, etc)

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93528]
According to @ptillet supporting Pascal GPUs with Triton should be possible if we:
1) Disable float16 support (and give a good error message saying fp16 requires a newer GPU)
2) Use `aten` backend for matmul/conv
3) May need to remove an assert on the Triton side?
4) Test it to make sure things work

This might be a good first issue if someone has a Pascal GPU handy to test on.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
Any updates on this? It would be nice to have working pascal support for CI purposes, since many of our CI boxes are still running Tesla M60

**Comment by ngimel** [comment]
M60 is maxwell

**Comment by ezyang** [comment]
I guess that means "never" 😭
