### ISSUE TITLE
Inductor ignores global pytorch `deterministic` setting

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#93537]
Pytorch generates scatter and indexing kernels that use atomic ops/ have non-deterministic behavior with repeating indexing, and won't throw errors/use fallbacks when deterministic mode is set in pytorch. We should use fallback in those cases. 

cc @mruberry @kurtamohler @ezyang @soumith @msaroufim @wconstab @bdhirsh

**Comment by ezyang** [comment]
cc @kurtamohler
