### ISSUE TITLE
Inductor indexing kernels don't check for valid indices

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#93538]
When eager mode gets invalid indices for indexing operations (e.g. negative or larger than input size) it generates kernel assert and hard errors with invalidated context. Inductor isn't set up to error, it can produce silent wrong results or error out with illegal memory access, depending on the caching allocator state and indices values. 
It's unclear if triton can have internal asserts in its kernels, but we should still think what our behavior should be in these cases, see https://github.com/pytorch/torchdynamo/issues/1515#issuecomment-1277897873 

cc @ezyang @soumith @msaroufim @wconstab @bdhirsh

**Comment by ngimel** [comment]
PR on the triton side is landed https://github.com/openai/triton/pull/1143, we need updating triton pin to land to be able to use it https://github.com/pytorch/pytorch/pull/95896

**Comment by lezcano** [comment]
@colesbury I have a prototype for this already working. Do you mind me fixing this one? I can add you as a reviewer

**Comment by colesbury** [comment]
@lezcano - sure. Did you see the Triton caching issue related to assertions (fixed in https://github.com/openai/triton/commit/859952a0aa2edef76a2a6800347c52669c56101d)? We may need to update triton to get the assertions properly working.

**Comment by lezcano** [comment]
I hadn't, but funnily enough I did struggle with that issue when getting this to work (cc @peterbell10). I'll update the hash when I submit the PR.

**Comment by ngimel** [comment]
Please update triton hash in a separate PR, usually enough things go wrong to not sneak it in with another PR.
