### ISSUE TITLE
Support single-arg min/max

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93539]
We should add support for:
```
tmp = (1,2,3)
return min(tmp)
```

Currently, this generates a warning:
```
WARNING:torch._dynamo.variables.builtin:incorrect arg count <bound method BuiltinVariable._call_min_max of BuiltinVariable(max)> missing a required argument: 'b'
WARNING:torch._dynamo.variables.builtin:incorrect arg count <bound method BuiltinVariable._call_min_max of BuiltinVariable(max)> missing a required argument: 'b'
```

I noticed this in:
```
./benchmarks/dynamo/torchbench.py --performance --inductor --only speech_transformer
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by vkrishnamurthy11** [comment]
is someone still working on this? Would like to tackle it as a first issue.

**Comment by ezyang** [comment]
no. @itang00's old PR got staled, please look it at it

**Comment by Zhang-Tianxu** [comment]
After looking at the code, I think the problem has been solved
https://github.com/pytorch/pytorch/blob/987eade3f38cde7113c7241831030c829879bf9b/torch/_dynamo/variables/builtin.py#L582-L590
