### ISSUE TITLE
Use new input clearing mechanism for aot_eager

### ISSUE THREAD

**Issue by IvanYashchuk** [pytorch/pytorch#93548]
@Chillee 
![image](https://user-images.githubusercontent.com/13822661/195258429-54a3927b-d2a7-4f96-a146-a9e5ffcefa2e.png)

Is this optimization already enabled for `aot_eager`? The numbers seem to suggest that it's not. Should we try to enable it with `aot_eager` first just as a confirmation that nothing new has creeped into the memory footprint?

_Originally posted by @anijain2305 in https://github.com/pytorch/torchdynamo/issues/1600#issuecomment-1275613843_
      

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by eellison** [comment]
This was landed in https://github.com/pytorch/pytorch/pull/100417.
