### ISSUE TITLE
more cudagraphs tests

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#93540]
After https://github.com/pytorch/pytorch/pull/87058 and https://github.com/pytorch/pytorch/pull/87060 and the issues that prompted those PRs, I can think of a bunch of edge-cases that we should add tests for within the cudagraph codepath:

1. Inputs are views of a larger storage

```python
input_parent = torch.randn(1000, requires_grad=True)
input1 = input_parent[0:100]
input2 = input_parent[300:400]
out = model(input1, input2)
out.sum().backward()
```

2. Same as (1), but model parameters share storage

```python
class Repro(torch.nn.Module):
    def __init__(self):
        super(Repro, self).__init__(device)
        self.weight1 = torch.nn.Parameter(
            torch.randn(2, 2, requires_grad=True, device=device)
        )
        self.weight2 = nn.Parameter(self.weight1.detach())
       # the weights wont remain tied across a `model.to(device)` or `model.cuda()` call, so this has to be carefully constructed with the weights already on the target device

    def forward(self, x):
        # assert(self.weight1.data_ptr() == self.weight2.data_ptr())
        x = torch.matmul(x, self.weight1)
        x = torch.matmul(x, self.weight2)
        return x
```

3. Inputs have actual overlap

```python
input_parent = torch.randn(1000, requires_grad=True)
input1 = input_parent[0:100]
input2 = input_parent[50:200]
out = model(input1, input2)
out.sum().backward()
```

cc: @eellison 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @ngimel

**Comment by ezyang** [comment]
reupping this for the new cudagraph tapes @eellison is working on

**Comment by eellison** [comment]
There are many tests in https://github.com/pytorch/pytorch/blob/main/test/inductor/test_cudagraph_trees.py, closing.
