### ISSUE TITLE
Dynamo+FSDP overall triage

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#93546]
Let me post various issues here first and then graduate some of them to their own issue rather than opening tons of issues in the beginning, since some of these may be minor/cosmetic/easy to fix.

- [ ] FakeTensor + FlatParamsWrapper Bug  (WIP: pytorch/pytorch#93688 )
- [ ] `[WARNING] Graph break: inline in skipfiles: forward` -- triaging below
- [ ] toy_model: `RuntimeError: The size of tensor a (159567000) must match the size of tensor b (319134000) at non-singleton dimension 0` -- triaging below
- [ ]  hf_Bert/hf_T5: `NotImplementedError: UserDefinedObjectVariable(_GenericAlias) is not a constant` -- possible dupe of pytorch/pytorch#93695 ?

cc @zhaojuanmao @mrshenli @rohan-varma @awgu @fegin @penguinwu @kwen2501 @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @H-Huang @wanchaol @fduwjj @wz337 @kiukchung @d4l3k @lucasllc @XilunWu @tianyu-l @soumith @ngimel

**Comment by penguinwu** [comment]
Will, is the issue still unresolved? If mostly fixed, please close this one and open new issues for remaining problems.

**Comment by wconstab** [comment]
we can close this. @voznesenskym has the latest relevant issues for compiled FSDP. and user-filed issues take priority for any non-compiled FSDP stuff.
