### ISSUE TITLE
Use A Memory Pool For Cudagraph Input Tensors

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#93541]
Currently, we separately allocate tensors for each invocation of cudagraphs. Especially for cases with numerous graph breaks, this can lead to a lot of wasted space. We should use a memory pool and share storage across invocations.  

For HF Big Bird, implementing this was shown to improve the memory compression ratio from .96 -> 1.05. When there are more dynamic inputs and recompilations separately allocating inputs will be even more wasteful. 

WIP PR: https://github.com/pytorch/torchdynamo/pull/1679

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
@eellison is still working on this, in https://github.com/pytorch/pytorch/issues/89146
