### ISSUE TITLE
[Bug]: Benchmark script is once again not giving meaningful error traces on error

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93550]
### 🐛 Describe the bug

On symbolic-shapes branch:

```
TORCH_SHOW_CPP_STACKTRACES=1 AOT_FX_GRAPHS_JOINT=1 TORCHDYNAMO_DYNAMIC_SHAPES=1 AOT_DYNAMIC_SHAPES=1 time python benchmarks/dynamo/torchbench.py --only hf_BigBird --accuracy --backend aot_eager --training
```

gives

```
TorchDynamo optimized model failed to run because of following error
FAIL
```

### Error logs

n

### Did Dynamo succeed?

- [ ] Does dynamo.optimize("eager") succeed?

### Did AOT succeed?

- [ ] Did dynamo.optimize("aot_eager") succeed?

### Did Inductor succeed?

- [ ] Does dynamo.optimize("inductor") succeed?

### Minified repro

n

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
This must be fixed?
