### ISSUE TITLE
[Bug]: the custom op cannot be included in the FX graph captured by torchdynamo

### ISSUE THREAD

**Issue by jiayisunx** [pytorch/pytorch#93554]
### 🐛 Describe the bug

The custom op registered via PyTorch registration mechanism cannot be included in the FX graph captured by torchdynamo.

### Error logs

the graph of JIT trace includes "torch_ipex::convolution_forward", but the graph of dynamo doesn't include it and got a warnning "Graph break: inline in skipfiles".

the graph of JIT trace:
graph(%self.1 : __torch__.torch.fx.graph_module.___torch_mangle_2.GraphModule,
      %x : Tensor):
  %self.conv.ctx : __torch__.torch.classes.ipex_prepack.ConvolutionOpContext = prim::Constant[value=object(0x556930639580)]()
  %self.conv.weight : Tensor = prim::Constant[value=<Tensor>]()
  %self.conv.bias : Tensor = prim::Constant[value=0.01 * -7.6438  3.1947 -6.6860 [ CPUFloatType{3} ]]()
  %5 : Tensor = prim::CallMethod[name="get_data_handle"](%self.conv.ctx), scope: __module.conv
  %8 : Tensor = prim::profile[profiled_type=Float(3, 6, 10, 10, strides=[600, 1, 60, 6], requires_grad=0, device=cpu), seen_none=0](%x)
  %9 : Tensor = prim::profile[profiled_type=Float(1, 6, 3, 3, 16, strides=[864, 144, 48, 16, 1], requires_grad=0, device=cpu), seen_none=0](%self.conv.weight)
  %10 : Tensor = prim::profile[profiled_type=Float(3, strides=[1], requires_grad=0, device=cpu), seen_none=0](%self.conv.bias)
  %11 : Tensor = prim::profile[profiled_type=Long(1, strides=[1], requires_grad=0, device=cpu), seen_none=0](%5)
  %input : Tensor = torch_ipex::convolution_forward(%8, %9, %10, %11), scope: __module.conv # /home/jiayisun/anaconda3/envs/ipex/lib/python3.8/site-packages/torch/_ops.py:175:0
  %12 : Tensor = prim::profile[profiled_type=Float(3, 3, 8, 8, strides=[192, 1, 24, 3], requires_grad=0, device=cpu), seen_none=0](%input)
  %7 : Tensor = aten::relu_(%12) # /home/jiayisun/anaconda3/envs/ipex/lib/python3.8/site-packages/torch/nn/functional.py:1455:0
  %13 : Tensor = prim::profile[profiled_type=Float(3, 3, 8, 8, strides=[192, 1, 24, 3], requires_grad=0, device=cpu), seen_none=0](%7)
   = prim::profile()
  return (%13)

the graph of dynamo with JIT backend:
torchdynamo.symbolic_convert: [WARNING] Graph break: inline in skipfiles: forward /home/jiayisun/gitlab/frameworks.ai.pytorch.ipex-cpu/build/Release/packages/intel_extension_for_pytorch/nn/utils/_weight_prepack.py from user code at File "<eval_with_key>.4", line 5, in forward
    conv = self.conv(x);  x = None
graph(%self : __torch__.torch.fx.graph_module.___torch_mangle_6.GraphModule,
      %_stack0 : Tensor):
  %4 : Tensor = prim::profile[profiled_type=Float(3, 3, 8, 8, strides=[192, 1, 24, 3], requires_grad=0, device=cpu), seen_none=0](%_stack0)
  %2 : Tensor = aten::relu_(%4) # /home/jiayisun/anaconda3/envs/ipex/lib/python3.8/site-packages/torch/nn/functional.py:1455:0
  %5 : Tensor = prim::profile[profiled_type=Float(3, 3, 8, 8, strides=[192, 1, 24, 3], requires_grad=0, device=cpu), seen_none=0](%2)
  %3 : (Tensor) = prim::TupleConstruct(%5)
   = prim::profile()
  return (%3)

### Minified repro

Here is the example:
```python
class Conv_Bn_Relu(nn.Module):
    def __init__(self):
        super(Conv_Bn_Relu, self).__init__()

        self.conv = torch.nn.Conv2d(6, 3, 3)
        self.bn = torch.nn.BatchNorm2d(3, eps=0.001)

    def forward(self, x):
        return F.relu(self.bn(self.conv(x)), inplace=True)

def compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    traced_gm = torch.jit.trace(gm.eval(), example_inputs).eval()
    traced_gm = torch.jit.freeze(traced_gm)
    print(traced_gm.graph_for(*example_inputs))
    return traced_gm

model = Conv_Bn_Relu().to(memory_format=torch.channels_last).eval()
x = torch.randn(3, 6, 10, 10).to(memory_format=torch.channels_last)

# In the weight prepack process, aten::conv is replaced by their optimized counterparts in Intel® Extension for PyTorch* via the registration mechanism.
model = ipex.optimize(model)

# jit
with torch.no_grad():
    traced_gm = torch.jit.trace(model, x).eval()
    traced_gm = torch.jit.freeze(traced_gm)
    print(traced_gm.graph_for(x))

# dynamo
m = torchdynamo.optimize(compiler)(model)

with torch.no_grad():
    m(x)
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Close the issue as it seems error is gone in following repro:
```python
import torch
import intel_extension_for_pytorch as ipex
import torch.nn.functional as F
from typing import List


class Conv_Bn_Relu(torch.nn.Module):
    def __init__(self):
        super(Conv_Bn_Relu, self).__init__()

        self.conv = torch.nn.Conv2d(6, 3, 3)
        self.bn = torch.nn.BatchNorm2d(3, eps=0.001)

    def forward(self, x):
        return F.relu(self.bn(self.conv(x)), inplace=True)

def compiler(gm: torch.fx.GraphModule, example_inputs: List[torch.Tensor]):
    traced_gm = torch.jit.trace(gm.eval(), example_inputs).eval()
    traced_gm = torch.jit.freeze(traced_gm)
    print(traced_gm.graph_for(*example_inputs))
    return traced_gm

model = Conv_Bn_Relu().to(memory_format=torch.channels_last).eval()
x = torch.randn(3, 6, 10, 10).to(memory_format=torch.channels_last)

# In the weight prepack process, aten::conv is replaced by their optimized counterparts in Intel® Extension for PyTorch* via the registration mechanism.
model = ipex.optimize(model)

# dynamo
m = torch.compile(model, backend=compiler)

with torch.no_grad():
    m(x)

```
