### ISSUE TITLE
[dynamo] Clean fake tensor code

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93569]
* Check how can we save the input tensor as fake tensor format. Some relevant comments here - https://github.com/pytorch/pytorch/pull/87513#discussion_r1002536732. We are storing the input of the graph as a real tensor. So, refactor the code such that we don't need to save the input tensor at all. This can solve OOM problem when there are tons of graph breaks.

* There is a lot of fake tensor code to check if fake tensor is available etc. This was around 1.12 release. We can potentially clean that up and reduce many bool conditions. We should still have `fake_tensor_propagation` flag in config.py, but we should get rid of `fake_tensors_available` boolean.

@bdhirsh assigning to you for now.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
think this is all done
