### ISSUE TITLE
[Bug]: TorchInductor Input As_Strided Calls Dont Compose With Offset Inputs

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#93562]
### 🐛 Describe the bug

Torchinductor will compile some operators like `aten.select.int` to `as_strided` calls which have the signature:

`as_strided(Tensor(a) self, SymInt[] size, SymInt[] stride, SymInt? storage_offset=None) -> Tensor(a)`

When the input has a non-zero storage offset that offset is ignored. 

### Error logs

...

### Did Dynamo succeed?

- [X] Does dynamo.optimize("eager") succeed?

### Did AOT succeed?

- [X] Did dynamo.optimize("aot_eager") succeed?

### Did Inductor succeed?

- [ ] Does dynamo.optimize("inductor") succeed?

### Minified repro

```
import torch


def foo(x):
    return torch.ops.aten.select.int(x, 1, 2)

foo_opt = torch._dynamo.optimize("inductor")(foo)

y = torch.rand([3, 4, 5, 6])
z = y[2]

out_opt = foo_opt(z)
out_eager = foo(z)
print(out_opt.storage_offset() == out_eager.storage_offset())  
print(torch.allclose(out_opt, out_eager))
```
> False
False

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
This would be fixed if we rewrite as_strided calls to use view_strided. cc @dagitses

**Comment by ydwu4** [comment]
Close as error fixed on main.

Log:
```
True
True
```
