### ISSUE TITLE
Blanket disable torch function/dispatch mode/subclass in dynamo

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93600]
I noticed in https://github.com/pytorch/pytorch/pull/88218 that there are a lot of one off DisableTorchFunction all over the torchdynamo codebase. This seems unsustainable. We ought to have some clear invariant about how dynamically scoped state and subclasses affect dynamo. What is this invariant? The obvious one to me is that all modes / context managers are disabled in the compiler, and you explicitly restore the modes if you want to evaluate through them. Is this what we are doing?

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Close the issue as I think this issue is not longer valid since we've started to support tensor subclass tracing and adding support for context managers etc in dynamo.
