### ISSUE TITLE
Make the The Nop AOT Autograd Backend Free Input References

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#93605]
Similar to https://github.com/pytorch/torchdynamo/pull/1600 - this might be nice for debugging memory issues.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
this is still valid!!! and it's pretty simple to do too

**Comment by avisinghal6** [comment]
Hi @ezyang, I am a newbie and would like to contribute. Can I take up this issue?

**Comment by ezyang** [comment]
yup

**Comment by avisinghal6** [comment]
Thanks @ezyang, could you guide me on how to get started to solve this issue? the related files that I should look at and get started.

**Comment by ezyang** [comment]
The nop backend in is in _functorch/compilers.py. It current calls into an FX graph. FX automatically frees inputs when they are free, so you just need to change it to the new calling convention.

**Comment by eellison** [comment]
@ezyang 

> The nop backend in is in _functorch/compilers.py. It current calls into an FX graph. FX automatically frees inputs when they are free, so you just need to change it to the new calling convention.

Hmm I'm not sure this is accurate. the inputs would still exist in the calling frame. I think you need to make a few more changes than that.
