### ISSUE TITLE
Enable pyre

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#93619]
I had an unused variable in a PR today, pyre (https://github.com/facebook/pyre-check) would have caught it 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by ydwu4** [comment]
Is this still relevant? Close it for now but feel free to re-open.
