### ISSUE TITLE
API For Registering Stride Preferences For User Fallback Kernels

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#93614]
Calling `.contiguous()` or `.contiguous(memory_format=torch.channels_last)` within extern kernels instead of the inputs being passed in the right layout can lead to perf regression as seen by https://github.com/pytorch/torchdynamo/issues/1833. 

We should either have an API for registering stride preferences or default to contiguous.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Hi @eellison , is this still interesting?
