### ISSUE TITLE
[inductor] Accuracy failure in torchbench hf_T5

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#93612]
initially thought this was a DDP-Dynamo issue.  Turns out to be an inductor issue, with or without DDP.

Log: https://gist.github.com/wconstab/1dfd032ed5cf4ff86b105aa4da6fa32c#file-torchbench_hf_t5_inductor_ddp_no_optimimze-log

@anijain2305 could you triage this?  Insofar as, just close the issue if you are already aware/tracking this accuracy failure, or put it in a backlog otherwise?

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ydwu4** [comment]
Hi @wconstab , is this issue still valid?
