### ISSUE TITLE
Replace decompositions in torchinductor/decompositions with refs/decomps in pytorch proper

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#93623]
We should audit existing decompositions and replace them with refs/decomps where appropriate, e.g. `clamp` decomposition currently incorrectly type promotes and doesn't handle non-number boundaries (see also pytorch/pytorch#93784). 

cc @ezyang @soumith @msaroufim @wconstab @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
This is still a thing (for example see rsub). It is easier to do now that the repos are merged

**Comment by ydwu4** [comment]
Is this issue still valid? Can I close it?
