### ISSUE TITLE
Functionalization on by default issue tracker

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#93621]
Making this issue to track progress for turning on `use_functionalization=True` and `normalize_ir=False` by default for dynamo (and then eventually, hopefully removing all of the functionalization code that lives in dynamo once the functionalization from core is always-on).

I've been running the torchbench suite using AOTAutograd + the eager (no-op) backend, so I'll record the failures that I was seeing before/after here.

I'm also seeing several model failures even without functionalization turned on, so I'm recording them here for tracking (and to confirm that these are all known issues).

### Failures with functionalization turned off (default)
These are the existing model failures that I saw, just when running all of torchbench (with AOTAutograd + eager)

`fastNLP_Bert`
Fails with "Accuracy failed for key name bert.model.encoder.pooler.dense.weight.grad"

`hf_Reformer `
Fails with "AssertionError: If you want to train `ReformerModel` and its variations, make sure to use `model.train()` to put the model into training mode."

`speech_transformer`
Fails with "INCORRECT - Variation in Eager runs itself"

(There are also two more models that fail for me because of an issue with the version of GLIBCXX on my A100, which I'm ignoring for now).

### Additional failures with functionalization turned on

All of the above models still fail when I turn on functionalization, as well as a few more. Tracking the additional failures here, and their fixes.

(1) `resnet18` and `speech_transformer` (and 2 other models, can't remember their names)

Fails with an internal functionalization error: ""mutating a non-functional tensor with a functional tensor is not allowed. Please ensure that all of your inputs are wrapped inside of a functionalize() call."

This is now fixed by https://github.com/pytorch/pytorch/pull/83207

(2) `mobilenet_v2_quantized_qat` and `resnet50_quantized_qat`

These both fail with: “RuntimeError: set_sizes_contiguous is not allowed on a Tensor created from .data or .detach().”

(3) `vision_maskrcnn`

vision_maskrcnn now fails at tracing time, with "RuntimeError: It appears that you're trying to get value out of a tracing tensor - erroring out!”.

(4) `yolov3`

yolov3 now fails with "RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward."

**Comment by ezyang** [comment]
All done!
