### ISSUE TITLE
tabulate.tabulate causes a lot of memory to be allocated in yolov3

### ISSUE THREAD

**Issue by mlazos** [pytorch/pytorch#93635]
Calling tabulate.tabulate to render the output graph causes 1 GB of additional memory allocation in yolov3.

This is gated on the log level now, but as a result when DEBUG or INFO log levels are set, this will cause additional memory to be allocated.

https://github.com/pytorch/torchdynamo/blob/0e4d5ee9db6dfeba4d424b2e5d2ad96c79f1dffa/torchdynamo/utils.py#:~:text=tabulate(node_specs%2C%20headers%3D%5B%22opcode%22%2C%20%22name%22%2C%20%22target%22%2C%20%22args%22%2C%20%22kwargs%22%5D) 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by ydwu4** [comment]
Can we close this issue if it's not relevant anymore?

**Comment by mlazos** [comment]
I think it still happens, but I'm not sure it's affecting anyone

**Comment by ydwu4** [comment]
Maybe let's close it for now and wait to see if anyone is still interested in it.
