### ISSUE TITLE
[inductor] Lower aten.cumsum

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#93631]
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @soumith

**Comment by lezcano** [comment]
I think this needs a new IR, something like `AssociativeScan`. 
Implementing splits on this will need its own heuristic (perhaps something can be recycled from the reduction heuristics though).

I think the usual strategy for splitting associative scans without memory synchronisation is to split it into chunks, compute the scan on each chunk, then take the last element of each chunk, create a new array, compute the scan of this array, and then "add" (or whichever operation) the elements of this array to the respective chunks. This same strategy also works when doing non-persistent reductions within a kernel.

We will also probably need a new decorator with new heuristics for this node.

**Comment by lezcano** [comment]
btw, @peterbell10 is on PTO until the end of the month.

**Comment by ezyang** [comment]
Once we have the new IR, I'd like to then extend it so that users can plug in their own operators as the reducing function.

**Comment by lezcano** [comment]
For that, it'll be best to wait for Peter, as he's the one that has been working on generalising the IR for reductions.

As a side note, something that has been tricky is that the current IR has baked in the assumption that each IR node just produces one tensor, so he's been having some trouble implementing `var_mean`. Perhaps we might be able to do it just for reductions that generate one tensor.

**Comment by Chillee** [comment]
From discussions with Jason, i think the right way to support this would probably be a new IR node, although I think it can mostly be treated as a reduction until codegen.

If it's a persistent reduction then it can mostly be done the same as reductions, but if it's a looped reduction then we'll need to handle it specially. It's kinda finicky, since Triton doesn't support it well.

![image](https://github.com/pytorch/pytorch/assets/6355099/4ac10248-be08-48a9-bd6d-59834f60b147)

**Comment by lezcano** [comment]
Not yet. We still need to update the triton pin. See https://github.com/pytorch/pytorch/pull/106581
