### ISSUE TITLE
[nvfuser] view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93648]
Instructions 
* Uncompress Repro file - [repro.tar.gz](https://github.com/pytorch/torchdynamo/files/9436625/repro.tar.gz)
* Run `python repro/repro.py`

The repro is minified using https://github.com/pytorch/torchdynamo/pull/1056
This only fail with `aot_nvfuser` backend.

 

cc @ezyang @msaroufim @wconstab @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ezyang** [comment]
our new attitude is that backends MUST match original eager striding exactly... at least until @dagitses finishes stride agnostic pytorch.

**Comment by jjsjann123** [comment]
> at least until @dagitses finishes stride agnostic pytorch.

Is that currently a WIP? Sounds like a pretty big endeavor, do we have any guesstimation on delivery time?

**Comment by ezyang** [comment]
it's a big endeavor, no estimate on timing

**Comment by ngimel** [comment]
In the meantime, the existing tracing mechanisms (mostly) correctly propagate strides (a few quirks here and there, mostly for the ambiguous strides of tensors with 0 elements or size-1 dimensions), and those can be queried on the fx graph nodes, so backends don't need to develop their own systems of stride propagation, they only need to query and match the strides that tracer gives them at the boundaries of the compiled region.

**Comment by ydwu4** [comment]
It's difficult to come up with a repro. Label it as an inductor issue since it's specific to backend.

**Comment by jjsjann123** [comment]
FYI, nvfuser has been removed from TorchScript. we should close this issue.

I see an `inductor` label added. not sure if that's intended or just by mistake.
