### ISSUE TITLE
Large number of WONT CONVERTs on detectron2 model

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#93643]
Repro: n2409433.

Dynamo is really choking on this model—there's many WONT CONVERTS and as a result we only get 17 ops out of the whole thing. I pulled out pytorch/torchdynamo#1010 and pytorch/torchdynamo#1009 into self-contained repros, but the rest of them probably need someone to look at the model directly.

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @soumith @wconstab @ngimel

**Comment by yf225** [comment]
Need to try to repro on latest PyTorch nightly.

**Comment by anijain2305** [comment]
Closing this because of staleness. We are tracking detectron2 in OSS benchmarks. We have some work done on supporting custom `__setattr__`.
