### ISSUE TITLE
torchdynamo fails on torchbench r50 in certain cases

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#93641]
I actually hit these errors when trying to use distributed (DDP) version of r50 but reduced to a small repro.
1)
```
from torchbenchmark.models.resnet50 import Model as R50Model
import torchdynamo
class MyR50(R50Model):
    
    @torchdynamo.optimize("aot_nvfuser")
    def train(self, niter=1):
        for _ in range(niter):
            self.optimizer.zero_grad()
            for data, target in zip(self.real_input, self.real_output):
                pred = self.model(data)
                self.loss_fn(pred, target).backward()
                self.optimizer.step()

r50 = MyR50('train', 'cuda')
r50.train()
```
produces 
`torchdynamo.exc.BackendCompilerFailed: ? raised RuntimeError: profiler::_record_function_enter() expected at most 2 argument(s) but received 3 argument(s). Declaration: profiler::_record_function_enter(str name, str? args=None) -> Tensor`

2) (with optimizer.zero_grad commented out)
```
from torchbenchmark.models.resnet50 import Model as R50Model
import torchdynamo
class MyR50(R50Model):
    
    @torchdynamo.optimize("aot_nvfuser")
    def train(self, niter=1):
        for _ in range(niter):
            #self.optimizer.zero_grad()
            for data, target in zip(self.real_input, self.real_output):
                pred = self.model(data)
                self.loss_fn(pred, target).backward()
                self.optimizer.step()

r50 = MyR50('train', 'cuda')
r50.train()
```

I see `torchdynamo.exc.BackendCompilerFailed: ? raised TypeError: iadd() takes no keyword arguments`

my build is few days behind tip, so apologies if this has already been fixed.

cc @ezyang @soumith @msaroufim @ngimel @bdhirsh

**Comment by ezyang** [comment]
guessing this fixed
