### ISSUE TITLE
Refactor Capture Scalar Outputs to use SymInts/SymFloats

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#93660]
Currently, in order to support tracking`.item()` calls, `capture_scalar_outputs ` will wrap the output of `.item()` with a 0-element tensor. We should refactor this to work with SymInts/SymFloats for a few reasons:

- fake tensor / proxy tensors will be doing their own internal constant tracking which can distinguish between calls of .item() which are statically known and those that are not, and the torchdynamo `.item()` handling interferes with this 

- this aligns with the other work ongoing to trace out integers/floats operations in the dynamic work stream 

- the current wrapping of scalars to tensors only defers the `.item()` call into the dispatcher. For instance, in adagrad, `param.addcdiv_(grad, std, value=-clr)`, `-clr` in user code is a float but because of `capture_scalar_outputs` in dynamo tracing is a 0-element tensor. when `addcdiv` is invoked in the dispatcher, the `-clr` will get converted to a scalar just as `.item()` call does. See [this issue](https://github.com/pytorch/pytorch/issues/84597) for more context. With [this pr](https://github.com/pytorch/pytorch/pull/83567), this will trigger a graph break, so the current `.item()` handling is insufficient. 
- There might be subtle semantics mismatches in the current handling, e.g., right now we are truncating python floats from double precision to floats.

**Comment by ezyang** [comment]
I did this! https://github.com/pytorch/pytorch/pull/93150
