### ISSUE TITLE
Use graph partitioner to remove ops that can be captured with cudagraphs in TorchInductor

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93666]
Currently, in TorchInductor cudagraphs usage is all-or-nothing. This test decided if we use it:
https://github.com/pytorch/torchdynamo/blob/116ae7f868fc46c197cb08094f3117525d1b9de8/torchinductor/compile_fx.py#L63-L68

This could lead to some performance cliffs where adding a single bad op to your graph flips off cudagraphs and hurts performance for unrelated ops.

We should try partitioning the graph to allow using cudagraphs on fragments where it is supported.  Many of the huggingface models use CPU tensors, which forces cudagraphs off.  It possible we could see some speedups there.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by penguinwu** [comment]
@jansel Is the issue still relevant? If not, please close.
