### ISSUE TITLE
Explore TBB for TorchInductor C++ backend

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93665]
Currently, the TorchInductor C++ backend uses OpenMP, though especially for small kernels there is pretty high warmup time to launch threads.  And we have seen our 1-thread performance give bigger speedups over eager than our N-thread performance.

[Thread Building Blocks](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onetbb.html) might deliver better performance here, so we should explore it as an alternative.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Are people are still interested in this? Closed it for now but feel free to re-open if it's still of interest.
