### ISSUE TITLE
Need operator fallback stats

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#93675]
In our internal benchmark enablement work, we had to set `.debug=True` and eyeball the logs to know if inductor or nvfuser is running. If we have the stats for which ops fall back to eager vs. which ops are run with inductor (or nvfuser) it will be much easier to tell if the desired backend is being used, which will be super helpful.

Format-wise it could be (just one idea):
op_name | fallback to eager
| --- | ----------- |
aten::mm | no
aten::cat | yes

Best if we can show the source line of the op (where it is in the original module file), but without it is fine too.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ngimel** [comment]
@yf225 is it still an issue?

**Comment by penguinwu** [comment]
@yf225 Is this still an issue? If not, please close.

**Comment by ydwu4** [comment]
Close due to inactivity but feel free to re-open if necessary.
