### ISSUE TITLE
Need easier way to tell which step of the optimized path fails (dynamo + inductor)

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#93674]
During internal benchmark enablement, there are multiple times where Dynamo silently starts to not generate any graph and not calling Inductor, but the workflow doesn't throw any error because Dynamo is (rightfully) "optional" with graceful eager fallback.

I learned from Michael Lazos that he plans to add operator stats to show which ops fall back to eager vs. using Inductor. But I believe more importantly we need easier way to tell which step of the compilation workflow has issue that causes the fallback, so that on the performance engineer side we can go in and figure out why the fallback happens.

Specifically it would be great to have:
1. A mode where we always error on fallback (maybe some ops only have fallback? in that case can have whitelist for those ops)
2. We want a way to know which step failed. The logs is currently a bit long and I also don’t know exactly what they mean in terms of what fails. If we can have “Step 1: XYZ, Step 2: XYZ, Step 3: XYZ, failed!” printed in the log, it’s easier to know that it's Step 3 that failed.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by anijain2305** [comment]
I am closing this because we now use TORCH_LOGS to understand compilation.
