### ISSUE TITLE
Minifier improvements/consistency

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93673]
- [x] Add tests
- [x] TORCHDYNAMO_REPRO_AFTER="dynamo" should also write to `minifier_launcher.py` similar to "aot" counterpart.
- [x] Extending accuracy testing for REPRO_AFTER="aot"
- [x] Consistent usage of REPRO_LEVEL between "dynamo" and "aot"
- [x] Better code sharing wherever possible
- [x] Enable seg fault repro as well for "Dynamo". It already exists for "aot"

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Close as all issues are fixed.
