### ISSUE TITLE
Bad g++ version downloaded from conda-forge when using None Path

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/pytorch#93687]
When using None path, the g++ version downloaded from conda-forge  has a mismatched version stdlib/compiler. 

This can be mitigated by commenting out the None

```
class cpp:
    threads = -1  # set to cpu_count()
    simdlen = None
    min_chunk_size = 4096
    cxx = (
        # None,  # download gcc12 from conda-forge if conda is installed
        "g++-12",
        "g++-11",
        "g++-10",
        "clang++",
        "g++",
    )
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
@SherlockNoMad reopen if still an issue
