### ISSUE TITLE
AOTAutograd not working with empty size tensor 

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/pytorch#93690]
Repro step 
1. remove "native_layer_norm" line from inductor_skips["cpu"] in test_torchinductor_opinfo.py
2. pytest test/test_torchinductor_opinfo.py -k native_layer_norm_cpu_float32

Root cause 
1. sample_inputs_layer_norm in common_methods_invocation.py produce an empty input with size [0, 1] 
2. AOTAutograd will generated a joint graph without backward subgraph
3. MinCutPartitioner will then produce a invalid backward subgraph like this 
```
graph():
    %tangents_1 : [#users=0] = placeholder[target=tangents_1]
    %tangents_2 : [#users=0] = placeholder[target=tangents_2]
    %tangents_3 : [#users=0] = placeholder[target=tangents_3]
    return [Invalid Node]
```
4. graph.compile() failed with this invalid graph

A few potential fixes
- Check for empty tensor at AOTAutograd, use symbolic tracing mode 
- Error out for empty tensor at AOTAutograd, if the tracing mode is real ? 
- partitioner should defensively produce an empty by valid graph ? 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @Chillee, @ngimel

**Comment by ezyang** [comment]
I think I'm tracking an unrelated bug that will fix this

**Comment by ezyang** [comment]
The referenced skip no longer exists. And even if there was still a bug, I'm guessing https://github.com/pytorch/pytorch/pull/96653/ fixes this
