### ISSUE TITLE
TorchInductor CUDA memory leak / memory corruption debugging master task

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#93693]
There's been an increase in memory and corruption bugs surfaced in inductor tests, mostly through the op tests.

ex: [#1362](https://github.com/pytorch/torchdynamo/pull/1362) - among others.

Of all the current enabled ops, these were detected as memory leaking through `compute-sanitizer`. There may be more leaks in other ops, we have not check all - only all enabled in the op info test as of https://github.com/pytorch/torchdynamo/pull/1340. 

- [x] 1. ___rmatmul__ float16
- [x] 2. ___rmatmul__ float32
- [x] 3. ___rmatmul__ float64
- [ ] 4. __masked_cumprod float32
- [ ] 5. __masked_cumprod float64
- [ ] 6. __masked_cumprod int32
- [ ] 7. __masked_cumprod int64
- [ ] 8. __masked_cumsum float16
- [ ] 9. __masked_cumsum float32
- [ ] 10. __masked_cumsum float64
- [ ] 11. __masked_cumsum int32
- [ ] 12. __masked_cumsum int64
- [ ] 13. __masked_logsumexp float16
- [ ] 14. __masked_logsumexp float32
- [ ] 15. __masked_logsumexp int32
- [ ] 16. __masked_logsumexp int64
- [ ] 17. __masked_norm float16
- [ ] 18. __masked_norm float32
- [ ] 19. _allclose float16
- [ ] 20. _allclose float32
- [ ] 21. _allclose float64
- [ ] 22. _argwhere bool
- [ ] 23. _argwhere float16
- [ ] 24. _argwhere float32
- [ ] 25. _argwhere float64
- [ ] 26. _bernoulli float32
- [ ] 27. _bernoulli float64
- [ ] 28. _bincount int32
- [ ] 29. _bincount int64
- [ ] 30. _combinations bool
- [ ] 31. _combinations float16
- [ ] 32. _combinations float32
- [ ] 33. _combinations float64
- [ ] 34. _combinations int32
- [ ] 35. _combinations int64
- [ ] 36. _copysign float16
- [ ] 37. _copysign float32
- [ ] 38. _copysign float64
- [ ] 39. _corrcoef float16
- [ ] 40. _corrcoef float32
- [ ] 41. _cov float16
- [ ] 42. _cov float32
- [ ] 43. _cov float64
- [ ] 44. _cov int32
- [ ] 45. _dist float32
- [ ] 46. _dist float64
- [ ] 47. _equal bool
- [ ] 48. _erf float16
- [ ] 49. _erf float32
- [ ] 50. _fmax float16
- [ ] 51. _fmax float32
- [ ] 52. _fmin float16
- [ ] 53. _fmin float32
- [ ] 54. _fmin float64
- [ ] 55. _jiterator_2inputs_2outputs bool
- [ ] 56. _jiterator_4inputs_with_extra_args float16
- [ ] 57. _jiterator_4inputs_with_extra_args float32
- [ ] 58. _jiterator_4inputs_with_extra_args float64
- [ ] 59. _jiterator_binary float64
- [ ] 60. _jiterator_binary int32
- [ ] 61. _jiterator_binary int64
- [ ] 62. _jiterator_binary_return_by_ref bool
- [ ] 63. _jiterator_binary_return_by_ref int32
- [ ] 64. _jiterator_unary float16
- [ ] 65. _jiterator_unary float32
- [ ] 66. _linalg_cholesky float32
- [ ] 67. _linalg_inv float32
- [ ] 68. _linalg_inv float64
- [ ] 69. _linalg_norm float16
- [ ] 70. _linalg_norm float32
- [ ] 71. _linalg_qr float32
- [ ] 72. _linalg_qr float64
- [ ] 73. _logsumexp float32
- [ ] 74. _nn_functional__scaled_dot_product_attention float16
- [ ] 75. _nn_functional__scaled_dot_product_attention float32
- [ ] 76. _nn_functional__scaled_dot_product_attention float64
- [ ] 77. _nn_functional_feature_alpha_dropout_without_train float32
- [ ] 78. _nn_functional_fractional_max_pool2d float16
- [ ] 79. _nn_functional_fractional_max_pool2d float32
- [ ] 80. _nn_functional_fractional_max_pool2d float64
- [ ] 81. _nn_functional_fractional_max_pool3d float16
- [ ] 82. _nn_functional_fractional_max_pool3d float32
- [ ] 83. _nn_functional_fractional_max_pool3d float64
- [ ] 84. _nn_functional_hardswish float32
- [ ] 85. _nn_functional_interpolate_bicubic float16
- [ ] 86. _nn_functional_interpolate_bicubic float32
- [ ] 87. _nn_functional_interpolate_bicubic float64
- [ ] 88. _nn_functional_triplet_margin_with_distance_loss float16
- [ ] 89. _nn_functional_triplet_margin_with_distance_loss float32
- [ ] 90. _nn_functional_triplet_margin_with_distance_loss float64
- [ ] 91. _nn_functional_triplet_margin_with_distance_loss int32
- [ ] 92. _nn_functional_triplet_margin_with_distance_loss int64
- [ ] 93. _pca_lowrank float32
- [ ] 94. _rand_like float16
- [ ] 95. _rand_like float32
- [ ] 96. _rand_like float64
- [ ] 97. _randint_like float16
- [ ] 98. _randint_like float32
- [ ] 99. _randint_like float64
- [ ] 100. _randn_like float16
- [ ] 101. _randn_like float32
- [ ] 102. _randn_like float64
- [ ] 103. _svd_lowrank float32

cc @ptrblck @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by eellison** [comment]
Closing, reopen if you think it's still relevant. We check memory in dashboard so i think probably not.
