### ISSUE TITLE
When you call tensor.size(), dynamo returns a tuple, instead of a torch.Size

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93706]
I have this fragment of code, based off of the bug report https://github.com/pytorch/torchdynamo/issues/1462

```
         elif input_ids is not None:
              input_shape = input_ids.size()
              input_ids = input_ids.view(-1, input_shape[-1])
          elif inputs_embeds is not None:
              input_shape = inputs_embeds.size()[:-1]
          else:
              err_msg_prefix = "decoder_" if self.is_decoder else ""
              raise ValueError(f"You have to specify either {err_msg_prefix}input_ids or {err_msg_prefix}inputs_embeds  ")      
          print("early input shape: ", input_shape)
```

what I have done is inserted the print. When I run model normally, this print says

```
early input shape:  torch.Size([2, 1024])
```

however, when it's run under dynamo, I don't get a torch.Size

```
early input shape:  (2, 1024)
```

This is unexpected and can lead to behavior divergence.

I can try to minimize the repro if you like, but I'm guessing it is very obvious that we are not doing this correctly.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ydwu4** [comment]
Close as issue seems to be fixed. Repro:
```python
import torch
def test_size(t):
    size = t.size()
    print(size)
    return size
out = torch.compile(test_size, backend="eager")(torch.randn(10, 10))
```
