### ISSUE TITLE
Replace same with TestCase assertEqual

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93701]
In TorchDynamo tests, we use `same` function to check for accuracy. But for many cases, we can rely on TestCase assertEqual which has pre-defined atol/rtol for different dtypes. We should migrate the tests to `assertEqual`  as much as possible. Thanks to @SherlockNoMad for pointing this out.

cc @ezyang @msaroufim @wconstab @bdhirsh @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @williamwen42 if you are interested.

**Comment by teerthap** [comment]
I'm interested. I can go ahead and switch all usages of same

**Comment by tpenumatcha** [comment]
I'm interested. I can go ahead and switch all the usages of same

**Comment by masnesral** [comment]
Looks like a good intern starter task. @sdingcn can do some of these...
