### ISSUE TITLE
opinfo test: RuntimeError: Negation, the `-` operator, on a bool tensor is not supported.

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#93710]
Repro:
Remove this line https://github.com/pytorch/torchdynamo/blob/a83c21a7acdfdaecc6c03b3700c68df67321ff76/test/test_torchinductor_opinfo.py#L341, and then run
```
 pytest test/test_torchinductor_opinfo.py -k test_comprehensive_erf_cuda_bool
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
erf is no longer skipped, guessing this is fixed
