### ISSUE TITLE
Use opinfo segfaulting list to protect inductor run internally

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#93712]
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ydwu4** [comment]
Label as inductor issue to let inductor folks to take a look and decide.
