### ISSUE TITLE
Make invalidating code free memory

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93728]
Currently, `GuardedCode.invalidate()` just sets a flag causing guard checks to always fail.
https://github.com/facebookresearch/torchdynamo/blob/055396468d1cea35cfae8955e59d29299290d592/torchdynamo/guards.py#L364

GuardedCode.invalidate() is called by [weakref](https://docs.python.org/3/library/weakref.html#weakref.ref.__callback__) when something we guarded on is destructed.

This means the memory and compiled artifacts are not freed until one calls `torchdynamo.reset()`.
This could be a problem if the compiled artifacts hold pointers to tensors, and could cause a memory leak.

Ideally we would have some sort of garbage collection where we walk [code cache](https://github.com/facebookresearch/torchdynamo/blob/055396468d1cea35cfae8955e59d29299290d592/torchdynamo/_eval_frame.c#L120) and remove anything that has been invalidated.

We should also do some testing to ensure TorchDynamo is not holding pointers to things and preventing memory from being freed.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
I think this is fixed now, reopen if it isn't
