### ISSUE TITLE
Write user-facing documentation and tutorial for inference acceleration

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93734]
An early milestone of TorchDynamo is to release a product that can be used to speed up inference with PyTorch.  This will have a somewhat different user experience than the training acceleration version, as there are numerous inference-only backend compilers.

A lot of the pieces of that are already there.  One could throw a `@torchdynamo.optimize("ofi")`, `@torchdynamo.optimize("tensorrt")`, or `@torchdynamo.optimize("autotune")` decorator on your PyTorch model, and it may go faster.

Things we need:
- Installation guide (including external dependencies like TensorRT)
- API documentation
- Tutorial
- Optimization guide, with tips for exploring different backends, `nopython=True`, and tuning options

cc @svekars @carljparker @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
The focus shifted towards training for now.
