### ISSUE TITLE
Improve specialization for Python float/int

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93740]
Currently, something like this:
```
for _ in range(100):
    with torchdynamo.optimize(...)
        foo(random.random())
```

Will cause problems because torchdynamo will specialize on the exact value from `random.random()`, resulting in guards failing and hitting `cache_size_limit` quickly.  Another example of this issue is something like a counter, which monotonically increases.

We should add support for not specializing on a Python int/float, and instead passing it as an input into the graph.  An earlier version of TorchDynamo actually did this, but I removed bit because backends had poor support for Python types, so it caused downstream issues.  To do this in a compatible way, we may need to wrap these values in 1-element Tensors before handing them to the backend.

The tricky part seems to be coming up with a good heuristic to decide when to specialize and when not to.  A few thoughts of the inputs to this heuristic:
1) Use the variable source: if something is a code constant, we know for sure the value is fixed.  Similarly, if something as an attribute of a `nn.Module` or a global it is also usually fixed.  If something is a default arg (`def foo(x, alpha=0.0)`) it may also be fixed.  If it is the return value of `random.random()`, it likely isn't.
2) Use the value itself: values like `0`, `1`, `0.5`, `math.pi` all might be good to specialize on, while a less common value might be not be.
3) Use the usages of the value: if a value goes into control flow, it may be better to specialize on it for bigger graphs.
4) Use prior guard failures: if we have failed guards on a value changing, the next graph compile to decide to do less specialization and back-off.

All of these seem reasonable.  I might start with a mix of 1/2, as they seem the easiest to implement, but it would be a good thing to iterate on.  If it doubt, we should default to not-specializing.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
Dynamic shapes has put in a lot of infra that you might want for this, but we haven't actually converted this into working wins in the frontend
