### ISSUE TITLE
Add documentation for adding training backends to README.md

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93747]
Currently, [README.md documents adding inference backends](https://github.com/jansel/torchdynamo#adding-backends), but not training backends with AOT Autograd.

We should add some details on this, and also perhaps make it a bit easier.

One thing that could help streamline the process would be to extend AOTAutogradStrategy:
https://github.com/jansel/torchdynamo/blob/8db8efc7681e4ae5851c3a298250993660d16e55/torchdynamo/optimizations/training.py#L17
to take a training compiler as an argument, so people don't need to subclass it.

While we are at it, we should also document python_key_normalize:
https://github.com/jansel/torchdynamo/blob/8db8efc7681e4ae5851c3a298250993660d16e55/torchdynamo/optimizations/python_key.py#L47
as a way to get the same IR format for both training and inference, and explain the difference between FX.Torch and FX.Aten.

cc @svekars @carljparker @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
We should do this!
