### ISSUE TITLE
Better handling for exec

### ISSUE THREAD

**Issue by anijain2305** [pytorch/pytorch#93749]
https://github.com/facebookresearch/torchdynamo/pull/184 introduces a band-aid fix to skip Dynamo on the `exec` frame. This issue is so that we don't forget to find a better solution.

For some reason, running the exec frame through Dynamo changes the `f_globals` dictionary. We can use the tests in the above PR to repro the failure.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ydwu4** [comment]
Is this issue still relevant?

**Comment by anijain2305** [comment]
Unable to repro. Closing
