### ISSUE TITLE
Make it possible to use TorchDynamo from within PyTorch core

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93745]
We have been discussing using TorchDynamo to implement some parts of PyTorch, for example composite operators.

Today you can't actually use TorchDynamo from within the `torch.*` module because of [skipfiles.py](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/skipfiles.py) and [allowed_functions.py](https://github.com/facebookresearch/torchdynamo/blob/main/torchdynamo/allowed_functions.py).
- skip_files causes TorchDynamo to skip all frames coming from specific files (including torch.*).
- allowed_functions.py controls what is mapped to a [TorchVariable](https://github.com/facebookresearch/torchdynamo/blob/78056e2287b50c0439079f62c1360de914762168/torchdynamo/variables/torch.py#L20) and becomes a node in the generated FX graph.  It is currently generated by walking the `torch.*` module hierarchy.

We will need to make both of these checks finer grained. 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by anijain2305** [comment]
Closing this task as the problem statement would change given the progress since the issue was created.
