### ISSUE TITLE
Off main thread symbolic evaluation

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93746]
Standard JIT design has compilation run off-thread, so that normal user code can continue running while compilation is still occurring. Unfortunately, torchdynamo's implementation in Python makes this difficult to do, as in standard Python there is a GIL which prevents useful parallelization of Python work. This means that we need to think about our off main thread strategy earlier rather than later, as it may imply architectural changes that are easier to do earlier in this project's lifetime.

I can imagine a number of possible ways to skin this cat:

* Put torchdynamo evaluation in a separate process
* Put torchdynamo in a subinterpreter in the same process
  * All strategies involving a separate Python interpreter will have to somehow transmit all of the frame information as well as locals for evaluation
* Rewrite torchdynamo in C++ (ugh)
* Rewrite torchdynamo in RPython
* Do nothing and pray the host program spends enough time in PyTorch operations that we can make useful progress with standard threading
* Do nothing for symbolic evaluation, but offload FX graph compilation to another thread

It would be good to know the PoR here.

cc @bhosmer @smessmer @ljk53 @bdhirsh @msaroufim @wconstab @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by anijain2305** [comment]
Marking this low priority, but accepting design/PRs if anyone is interested.
