### ISSUE TITLE
Run TorchDynamo on HuggingFace spaces

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93750]
@soumith suggested running TorchDynamo on [HuggingFace Spaces](https://huggingface.co/spaces) which contains a large number of models to try to find cases where it fails and we can improve things.

They are basically UI apps -- some javascript tagged to a flask-ish server.
And some example inputs.
The "end to end" might involve us provisioning a docker image or conda env, and sending the inputs as CURL / JSON requests or something -- unless we figure out how to send inputs directly.

We should do this to a stress-test for Python coverage.  It also might be a good source of performance data.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by anijain2305** [comment]
Closing as nobody is interested.
