### ISSUE TITLE
TorchInductor failing inference models tracker

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93759]
This is meta issue to track multiple issues with TorchInductor inference models in TorchBench.

Note all the models tracked by pytorch/torchdynamo#331 also don't work with TorchInductor.

Reproduce with:
`./torchbench.py -dcuda --inductor --float16 --no-skip -k <name>`

Updated list as of 8/26/2022:

- [x] pytorch/pytorch#93788
- Accuracy Error:
  - [x] pytorch/torchdynamo#622
  - [x] pytorch/torchdynamo#838
  - [x] pytorch/torchdynamo#634
  - [x] pytorch/torchdynamo#630 
  - [x] pytorch/torchdynamo#1039

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ydwu4** [comment]
Close issue since all issues are done.
