### ISSUE TITLE
allowed_functions_module_string_ignorelist doesn't work very well

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93763]
I noticed that adding torch.utils._pytree to the ignore list wasn't enough to induce dynamo into inlining it; I had to add it to the explicitly excluded functions list.

My hypothesis for why this is happening is that sometimes PyTorch modules accidentally reexport identifiers from other modules. These then get picked up and shoved into the allowlist.

To be honest, it's not clear to me why we ignorelist rather than explicitly allowlist what we put into graphs.

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by gchanan** [comment]
@ezyang should this be closed?

**Comment by ezyang** [comment]
This function is still here and I don't think it got changed, so yes, I think so.

**Comment by ydwu4** [comment]
Is this issue still relevant?

**Comment by ezyang** [comment]
subsumed by @yanboliang work
