### ISSUE TITLE
Add support for `torch.cuda.is_available()` and `torch.cuda.current_device()`

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#93769]
cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ngimel** [comment]
Is this still an issue?

**Comment by yanboliang** [comment]
```torch.cuda.is_available``` has been supported, ```torch.cuda.current_device``` not yet.
