### ISSUE TITLE
RuntimeError: Found an argument of type numpy.int64 at index 0. 

### ISSUE THREAD

**Issue by yushangdi** [pytorch/pytorch#93766]
I got the following error when using `aot_module` on model fastNLP_Bert and speech_transformer .

RuntimeError: Found an argument of type numpy.int64 at index 0. Non-tensor arguments must be marked static. Please set the static_argnums correctly to mark the argument at index 0 static.

The aot_module is used like below:

```
def save_fx(gm, example_inputs):
    from functorch.compile import aot_module, aot_module_simplified

    def graph_saver_forward(gm, _):
        gm.to_folder(...)
        return gm

    def graph_saver_backward(gm, _):
        gm.to_folder(...)
        return gm

    return aot_module(gm, fw_compiler=graph_saver_forward, bw_compiler=graph_saver_backward) 

optimize_ctx = torchdynamo.optimize(    
            save_fx, # aot_module(gm, fw_compiler=graph_saver_forward, bw_compiler=graph_saver_backward)
            nopython=args.nopython,
        )

with optimize_ctx:
           model_iter_fn(model, example_inputs, collect_outputs=False)
```

@anijain2305 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
This is not a supported way of calling `aot_module`
