### ISSUE TITLE
analysis.has_mutation version tracker does not capture all mutation

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#93776]
```
>>> import torch
>>> x = torch.rand([4])
>>> x._version
0
>>> x.resize_([4, 1])
>>> x._version
```

Since `ShapeAliasingAndMutationProp` exclusively uses `_version` to capture mutation it does not capture all mutation. I'm still not yet sure when `_version` gets updated.

cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @bdhirsh @soumith @msaroufim @wconstab @ngimel

**Comment by ezyang** [comment]
we want to dump this for functionalization. This is still being used though so keeping the bug open

**Comment by gchanan** [comment]
@ezyang why is this on the pt2 oncall?

**Comment by ezyang** [comment]
Because it was transferred? I think the quoted analysis is in dynamo

**Comment by gchanan** [comment]
fair enough, although it's not really a PT2 issue.

**Comment by albanD** [comment]
This is because our implementation in `VariableTypeManual.cpp` is not properly bumping the version counter.
We would accept a PR fixing that for sure!

**Comment by albanD** [comment]
cc @kshitij12345 if you have space cycles!
