### ISSUE TITLE
Add support for torch.nn.quantized.modules.FloatFunctional

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#93772]
cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @saketh-are @soumith @ngimel @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by vkuzo** [comment]
what's the context on the missing support?  Judging from the tags, is it related to pt2?

**Comment by ydwu4** [comment]
Is this issue still valid?

**Comment by ydwu4** [comment]
Close it for not due to inactivity but feel free to reopen.
