### ISSUE TITLE
detectron2 models in torchbench fail in TorchDynamo

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93779]
https://github.com/pytorch/benchmark/pull/955 added a bunch of new benchmarks to torchbench.

It seems that these new models are failing if you run 
```
./benchmarks/torchbench.py -dcuda --isolate -k detectron2
```

The failures are:
- `detectron2_fasterrcnn_r_*`, `detectron2_maskrcnn_r_*`: `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument max in method wrapper_clamp_Tensor)`; this looks like an issue in handling of `clamp`
- detectron2_fcos_r_50_fpn: `SyntaxError: invalid syntax`; an issue in `slice` printing in guards

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by gchanan** [comment]
Just checked this with:
`benchmarks/dynamo/torchbench.py -dcuda -k detectron2 --performance` and it passed.
