### ISSUE TITLE
Support for DistributedDataParallel (DDP) based Multi-GPU Training in TorchDynamo

### ISSUE THREAD

**Issue by kevinstephano** [pytorch/pytorch#93773]
HuggingFace models currently are restricted from using DDP for training with TorchDynamo. It would be good to either add this support or validate it is working.

```
    @require_torch_non_multi_gpu
    @require_torchdynamo
    def test_torchdynamo_memory(self):
        # torchdynamo at the moment doesn't support DP/DDP, therefore require a single gpu
        class CustomTrainer(Trainer):
            def compute_loss(self, model, inputs, return_outputs=False):
                x = inputs["x"]
                output = model(x)
                if self.args.n_gpu == 1:
                    return output.mean()
                return output
```

https://github.com/huggingface/transformers/blob/6a5272b2054622e27b4843e0c9722cc716d5458d/tests/trainer/test_trainer.py#L1827-L1837

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by wconstab** [comment]
this should probably (?) be fixed now.  @kevinstephano have you tried recently?
