### ISSUE TITLE
Catch value errors if cell in match_nested_cell is empty

### ISSUE THREAD

**Issue by voznesenskym** [pytorch/pytorch#93770]
```
symbolic_convert.py", line 1250, in match_nested_cell
    value = cell.cell_contents
ValueError: Cell is empty
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by gchanan** [comment]
not sure if this is a bug, @voznesenskym can you provide a reproduction or close?

**Comment by ydwu4** [comment]
Is this issue still valid?

**Comment by ydwu4** [comment]
Close it for now due to inactivity but feel free to reopen.
