### ISSUE TITLE
Support capturing fully qualified name of a submodule

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#93771]
I'm trying to see how we can implement quantization on subgraphs captured by torchdynamo. In quantization, we have configurations specified for submodules:
for example:
```
qconfig_mapping = QConfigMapping.set_module_name("blocks.0.conv1", qconfig)
```
Full prepare_fx API can be found in https://pytorch.org/docs/master/generated/torch.quantization.quantize_fx.prepare_fx.html#torch.quantization.quantize_fx.prepare_fx

So we need to know the fully qualified name of a submodule in a torchdynamo fx subgraph so that we can set the qconfig for it properly. Wondering if we can capture this and store them in somewhere so that we can get it when we are implementing a `quant_compiler_fn`?

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @jansel

**Comment by ezyang** [comment]
Sherlock fixed this
