### ISSUE TITLE
[feature request] Multivariate Gamma function

### ISSUE THREAD

**Issue by Balandat** [pytorch/pytorch#9378]
Looks like there currently is no implementation of the (log-) multivariate Gamma function? That would be useful for implementing Wishart / inverse Wishart distributions.

The straightforward way to do this would be to reduce it to multiple `lgamma` evaluations using the identity 35.3.4 from https://dlmf.nist.gov/35.3. For a float `a` the `p`-dim multivariate Gamma function in python is just

```
def log_mv_gamma(p, a):
    C = p * (p - 1) / 4 * math.log(math.pi)
    return C + torch.lgamma(a - 0.5 * torch.arange(p, dtype=torch.float)).sum()
```

I'm not sure how numerically stable this simple approach is, but it doesn't look too bad at first glance.

**Comment by alicanb** [comment]
Wishart (+multivariate lgamma) is on the to-do list https://github.com/probtorch/pytorch/issues/94, we haven't been able to get to it yet 😄 If you already have an implementation/ would like to take it on, you're definitely more than welcome.

**Comment by vishwakftw** [comment]
I can work on this. @soumith in `aten/src/ATen/native` there is no file open for miscellaneous math operations, so where can I put this?

**Comment by soumith** [comment]
@vishwakftw `ATen/native/random.cpp` if you are adding rng functions, and `ATen/native/misc.cpp` otherwise, probably?

**Comment by Balandat** [comment]
Many thanks!
