### ISSUE TITLE
Guide for diagnosing excess graph breaks

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93793]
Something a user using torchdynamo might want to do is figure out why they are having lots of graph breaks. We have tools for doing this, but they are not documented. Prior to the PT2 release it would be good to document them. cc @svekars @carljparker @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by anijain2305** [comment]
There is a link here - https://pytorch.org/docs/stable/torch.compiler_troubleshooting.html#identifying-the-cause-of-a-graph-break
