### ISSUE TITLE
Reordering test in PyTorch test suite induces dynamo failure

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93791]
See https://github.com/pytorch/pytorch/pull/82169

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by ydwu4** [comment]
Is this issue still relevant?

**Comment by ezyang** [comment]
I'll close this as nonactionable but it's definitely still a thing
