### ISSUE TITLE
resnet50_quantized_qat & mobilenet_v2_quantized_qat not loading correctly with cuda

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#93806]
Hi,

I tried loading the above mentioned two models by `python benchmarks/torchbench.py --only <model_name> --backend ts --device cuda` with torchdynamo/torchbench but got the following error:
```
WARNING:root:<model_name> failed to load
```
Those two models runs fine on llvm/cpu. I wonder if there is more context to it. Or maybe this is an issue from the torchbench side? Thanks!

cc: @jansel @xuzhao9 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by gchanan** [comment]
These don't look pt2 related, e.g.
```
> benchmarks/dynamo/torchbench.py --only resnet50_quantized_qat --nothing --device cuda --performance
The eval test only supports CPU.
```

**Comment by shingjan** [comment]
close this one as those models are cpu-only.
