### ISSUE TITLE
Segmentation fault when hipifying code.

### ISSUE THREAD

**Issue by SingL3** [pytorch/pytorch#93827]
### 🐛 Describe the bug

I am trying to hipify code from [flash-attention](https://github.com/HazyResearch/flash-attention), which has a dependency of cutlass.
I adapt the setup.py and when hipifying cutlass, segmentation fault happens. I debugged and the main reason is that there are some .h files that include each other. For example, [simd.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/simd.h#L122) and [simd_sm60.h](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/arch/simd_sm60.h#L37). Because the preprocessor will try to process the files that it includes and itself was not yet hipified successfully. This results in infinite loop.

### Versions

torch 1.10

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by malfet** [comment]
@SingL3 does it reproduce using PyTorch-1.13.1. Also, issue can you please post some sort of logs (even partial) to get a better sense at what is going on?

**Comment by SingL3** [comment]
Sorry I don't have a rocm pytorch 1.13 env here. 
Log
`File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 792, in preprocessor
    output_source = RE_QUOTE_HEADER.sub(mk_repl('#include "{0}"', True), output_source)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 785, in repl
    clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 177, in preprocess_file_and_save_result
    hip_clang_launch, is_pytorch_extension, clean_ctx, show_progress)
  File "/root/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/hipify/hipify_python.py", line 722, in preprocessor
    output_source = fin.read()
RecursionError: maximum recursion depth exceeded while calling a Python object`

and I add this to the code:

`
sys.setrecursionlimit(1000000)
`

And I got this:
`
  torch.__version__  = 1.10.0
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/cmake/nop.cu -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/cmake/nop.hip skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/cmake/version.h.in -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/cmake/version.h.in ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/aligned_buffer.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/aligned_buffer.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/array.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/array.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/array_planar_complex.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/array_planar_complex.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/array_subbyte.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/array_subbyte.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/bfloat16.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/bfloat16.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/blas3.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/blas3.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/complex.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/complex_hip.h skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/constants.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/constants.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/coord.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/coord.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/core_io.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/core_io_hip.h skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/cutlass.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/cutlass.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/device_kernel.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/device_kernel_hip.h skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/fast_math.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/fast_math.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/functional.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/functional.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/half.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/half_hip.h skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/integer_subbyte.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/integer_subbyte.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/kernel_launch.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/kernel_launch.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/matrix.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/matrix.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/matrix_coord.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/matrix_coord.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/matrix_shape.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/matrix_shape.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/numeric_conversion.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/numeric_conversion.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/numeric_types.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/numeric_types.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/pitch_linear_coord.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/pitch_linear_coord.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/predicate_vector.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/predicate_vector.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/quaternion.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/quaternion.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/real.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/real.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/relatively_equal.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/relatively_equal.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/semaphore.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/semaphore_hip.h skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/subbyte_reference.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/subbyte_reference.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_coord.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_coord.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_ref.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_ref.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_ref_planar_complex.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_ref_planar_complex.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_view.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_view.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_view_planar_complex.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tensor_view_planar_complex.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tfloat32.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/tfloat32.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/trace.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/trace.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/uint128.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/uint128.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/wmma_array.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/wmma_array.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/complex_hip.h -> None ignored
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/core_io_hip.h -> None ignored
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/device_kernel_hip.h -> None ignored
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/half_hip.h -> None ignored
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/semaphore_hip.h -> None ignored
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/arch.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/arch.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/cache_operation.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/cache_operation.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm75.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm75.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm80.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm80.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm75.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm75.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm80.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/memory_sm80.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm50.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm50.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm60.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm60_hip.h skipped
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm61.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm61.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm70.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm70.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm75.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm75.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm80.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sm80.h ok
  /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sparse_sm80.h -> /home/thanks3q/dcu_pkg/flash-attention/csrc/flash_attn/cutlass/include/cutlass/arch/mma_sparse_sm80.h ok
  Segmentation fault (core dumped)
`

**Comment by fungos** [comment]
I can confirm this and get past the issue by skipping headers that trigger cyclic dependency:

```python
if fin_path.endswith('/array.h') or fin_path.endswith('/array_subbyte.h') or fin_path.endswith('/mma.h') or fin_path.endswith('/mma_sm50.h') or fin_path.endswith('/mma_tensor_op.h') or fin_path.endswith('/mma_tensor_op_fast_f32.h') or fin_path.endswith('/memory.h') or fin_path.endswith('/memory_sm80.h') or fin_path.endswith('/default_mma_tensor_op.h') or fin_path.endswith('/default_mma_tensor_op_sm80.h'):
        return {"hipified_path": fin_path, "status": "[SKIPPED, debug]"}
```

output:

```bash
xformers on  main [!?] took 4s ➜ python setup.py | rg debug
/src/xformers/third_party/cutlass/include/cutlass/gemm/warp/default_mma_tensor_op.h -> /src/xformers/third_party/cutlass/include/cutlass/gemm/warp/default_mma_tensor_op.h [skipped, debug]
/src/xformers/third_party/cutlass/include/cutlass/array.h -> /src/xformers/third_party/cutlass/include/cutlass/array.h [skipped, debug]
/src/xformers/third_party/cutlass/include/cutlass/arch/mma.h -> /src/xformers/third_party/cutlass/include/cutlass/arch/mma.h [skipped, debug]
Successfully preprocessed all matching files.
/src/xformers/third_party/cutlass/include/cutlass/arch/memory.h -> /src/xformers/third_party/cutlass/include/cutlass/arch/memory.h [skipped, debug]
/src/xformers/third_party/cutlass/include/cutlass/gemm/warp/mma.h -> /src/xformers/third_party/cutlass/include/cutlass/gemm/warp/mma.h [skipped, debug]
/src/xformers/third_party/cutlass/include/cutlass/gemm/thread/mma.h -> /src/xformers/third_party/cutlass/include/cutlass/gemm/thread/mma.h [skipped, debug]
/src/xformers/third_party/cutlass/include/cutlass/gemm/warp/mma_tensor_op.h -> /src/xformers/third_party/cutlass/include/cutlass/gemm/warp/mma_tensor_op.h [skipped, debug]
```

So `preprocessor` is not caching already visited files and is getting lost in the cyclic dependency for these headers on the `cutlass` project.

Related issues:
https://github.com/ROCm-Developer-Tools/HIPIFY/issues/660
https://github.com/facebookresearch/xformers/issues/485
https://github.com/ROCmSoftwarePlatform/hipify_torch/issues/47
https://github.com/ROCmSoftwarePlatform/hipify_torch/issues/39

Not sure if this report should be here or at https://github.com/ROCmSoftwarePlatform/hipify_torch, probably there, but that project issues doesn't seem to be moving forward, which is very sad.

**Comment by feffy380** [comment]
@fungos When you say you're able to get past the issue, does that mean you're able to compile?

**Comment by Wongboo** [comment]
@fungos, Where did you add these lines? somewhere in hipify_python.py?
```
if fin_path.endswith('/array.h') or fin_path.endswith('/array_subbyte.h') or fin_path.endswith('/mma.h') or fin_path.endswith('/mma_sm50.h') or fin_path.endswith('/mma_tensor_op.h') or fin_path.endswith('/mma_tensor_op_fast_f32.h') or fin_path.endswith('/memory.h') or fin_path.endswith('/memory_sm80.h') or fin_path.endswith('/default_mma_tensor_op.h') or fin_path.endswith('/default_mma_tensor_op_sm80.h'):
        return {"hipified_path": fin_path, "status": "[skipped, debug]"}
```

**Comment by jithunnair-amd** [comment]
@singL3 we fixed the circular recursion issue in an upstream PyTorch PR: https://github.com/pytorch/pytorch/issues/93827 .... the latest PyTorch nightly wheels should contain this fix in hipify. Our internal testing with flash_attention repo seems to indicate this issue is resolved. Can you please verify on your end?

NOTE: We will not be able to back-port this fix into PyTorch stable wheels.

**Comment by groenenboomj** [comment]
AMD has an fork of this repository where we reimplemented the CUTLASS portions in Composable Kernels.  The hipify issue should be addressed as indicated but take a look at this repo for Flash Attention on ROCm:
https://github.com/ROCmSoftwarePlatform/flash-attention/tree/flash_attention_for_rocm

**Comment by SingL3** [comment]
Thank you all! Closing now.
