### ISSUE TITLE
ONNX Export Fails: Model input type is Dict[str, Tensor] 

### ISSUE THREAD

**Issue by yingcanw** [pytorch/pytorch#93838]
### 🐛 Describe the bug

I tried to export a pytorch model to onnx and the model input type is Dict[str, Tensor],  but it fails with _**Couldn't lower all tuples**_ errror.
sorry I can't upload model as it's our internal one.

The same input, the model can output normally as below:
```python
import torch
from typing import Dict, List, Tuple
device = torch.device("cuda")
model = torch.load("model.pt")
input_dict: Dict[str, torch.Tensor] ={'input1': torch.tensor([1],dtype=torch.float64,device=device),
'input2': torch.tensor([1],dtype=torch.float64,device=device),
'input3': torch.tensor([1],dtype=torch.float64,device=device)
}
model(input_dict)
```
And I will get output as below:

```python
Output(prediction=tensor([[19.3254]], device='cuda:0', grad_fn=<ReluBackward0>))
```

But when I use the same input for onnx export：
```python
torch.onnx.export(user_model, (input_dict, {}), "onnx_model.onnx", verbose = True, input_names = ["input1","input2","input3"], output_names = ["output_spec"])
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 582, in _optimize_graph
    _C._jit_pass_lower_all_tuples(graph)
RuntimeError: Couldn't lower all tuples.
```

### Versions

PyTorch version: 1.13.1+cu117
CUDA used to build PyTorch: 11.7
OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CMake version: version 3.24.3
Libc version: glibc-2.31

Python version: 3.8.10 
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
Nvidia driver version: 450.51.06
Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.1
[pip3] torchsummary==1.5.1

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
