### ISSUE TITLE
[pytorch] Intel MKL ERROR when doing torch.eig on a CUDA tensor

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9384]
[S.pt7.gz](https://github.com/pytorch/pytorch/files/2189021/S.pt7.gz)

What does this error mean and why is MKL involved in computing eigendecomposition of a CUDA tensor (the result tensor is also on CUDA)?

```python
import torch, gzip
a = torch.load(gzip.open('S.pt7.gz'))

print(a.device)
# cuda:0

a.eig()
#Intel MKL ERROR: Parameter 2 was incorrect on entry to SGEHD2.

#(tensor([[ 1.0000,  0.0000],
#        [ 0.5825,  0.0000],
#        [ 0.1131,  0.0000],
#        ...,
#        [ 0.0000,  0.0000],
#        [ 0.0000, -0.0000],
#        [ 0.0000,  0.0000]], device='cuda:0'), tensor([], device='cuda:0'))
```

**Comment by vadimkantorov** [comment]
It seems this error comes out from MAGMA. A side question: should not PyTorch manage how downstream libraries report errors? should this not be a full-blown PyTorch error?

**Comment by zou3519** [comment]
Does this succeed when running on CPU?

**Comment by vadimkantorov** [comment]
I didn't try (it was a throw-away expermiment for visualization, I moved on to other things), but the attached file should repro it on GPU. Does it repro on your machine?

**Comment by vadimkantorov** [comment]
Maybe there's an underlying MKL bug that needs to be submitted to Intel..

**Comment by yaroslavvb** [comment]
btw, just tried on AWS DLAMI (with MKL + PyTorch configured) and the crash isn't there anymore

```
import os, torch, gzip
os.system('wget https://github.com/pytorch/pytorch/files/2189021/S.pt7.gz')

a = torch.load(gzip.open('S.pt7.gz'))

print(a.device)
# cuda:0

a.eig()
```

**Comment by zhangguanheng66** [comment]
Intel should be notified if there is an issue in MKL.

**Comment by vadimkantorov** [comment]
Maybe it was a magma bug. To repro, one would need to install PyTorch/Magma/MKL that were released at time of this issue creation...

**Comment by albanD** [comment]
Closing as this not crash anymore.
Re-open if you see this happening with an up to date version.

**Comment by vadimkantorov** [comment]
ok!
