### ISSUE TITLE
EmbeddingBag to support mini-batches with offsets

### ISSUE THREAD

**Issue by alexshtf** [pytorch/pytorch#93843]
### 🚀 The feature, motivation and pitch

Currently, the `forward` method of `EmbeddingBag`, when offsets are passed, supports only 1D inputs. Hence, training / inference on mini-batches of data isn't supported with offsets.

Offsets are very useful when training on tabular datasets with "multi-valued" cells, such as movie genres, since we may want to sum / average the embeddings associated with several genres to a single vector.  There can also be weighted multi-valued cells, for example, when the multiple values are generated by an auxiliary model, and the weights represent the confidence of the model in its prediction. For example, consider automatic extraction of movie genres from their title and description.

### Alternatives

Two possible alternatives:

1. Using a regular `torch.nn.Embedding` class, extract the embedding vectors, multiply by weights manually, and aggregate them. In this case we lose the efficiency of the EmbeddingBag class, which doesn't have to actually create the full embedding tensor. This idea is relevant only if the number of features in each mini-batch item is the same.
2. Use an EmbeddingBag in our model, decompose the mini-batch to its constituent items, and compute the output of the model for each item using a for-loop.

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by vadimkantorov** [comment]
Maybe instead of offsets, a NestedTensor could be used to represent these sequences or older PackedSequence type  https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.PackedSequence.html#torch.nn.utils.rnn.PackedSequence

**Comment by alexshtf** [comment]
@vadimkantorov That's a viable alternative. In any case, at least for the things we are working on, an efficient way to aggregate embeddings extracted from a mini-batch of data is useful.
