### ISSUE TITLE
torchdim can not be compiled for Python-3.11 on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#93854]
### 🐛 Describe the bug

As it uses _PyOpcode_Deopt and _PyOpcode_Caches that are not guaranteed to be a public symbols
So attempts to compile fails as follows:
```
dim.cpp.obj : error LNK2019: unresolved external symbol _PyOpcode_Caches referenced in function "struct _object * __cdecl _dims<&struct py::object __cdecl create_dim(struct py::object,struct py::handle)>(struct _object *,struct _object * const *,__int64,struct _object *)" (??$_dims@$1?create_dim@@YA?AUobject@py@@U23@Uhandle@3@@Z@@YAPEAU_object@@PEAU0@PEBQEAU0@_J0@Z)
```

So it was disabled during the build, see 
https://github.com/pytorch/pytorch/blob/3d062f9abe9db13119b31bf810cc4834dc2d9a26/functorch/csrc/dim/dim.cpp#L1520-L1523

Which probably make something like the following fail on Windows+Python-3.11:
```
python -c "import functorch.dim; i, j = functorch.dim.dims();print(i)"
```
### Versions

CI

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by Blackhex** [comment]
@malfet AFAIK, the Win32 is not a supported platform, right? Can you please explain for what use-case this is an issue?

**Comment by mantaionut** [comment]
@malfet can you please explain what this issue should fix. I checked the history of why the implementation changed to use _PyOpcode_Deopt and _PyOpcode_Cache  https://github.com/pytorch/pytorch/issues/91246 and I see the posted code works without right now without using those symbols on py-3.11 on Windows. I opened an issue in Cpython about the reason why those symbols are in python.so and not .lib https://github.com/python/cpython/issues/111767 and the feedback I got was mostly that those symbols are internal and should not be used.

**Comment by kalaskarsanket** [comment]
@malfet  following on Ionut's question above.

**Comment by malfet** [comment]
Updated PR description, perhaps this will make it a bit cleaner. 
Please try running following test on Win + Python-3.11 if it passes, then this issue can be closed https://github.com/pytorch/pytorch/blob/7a9012d7e847a6265e70873e9baab70838edd601/test/functorch/test_dims.py#L109

**Comment by kalaskarsanket** [comment]
@malfet  can you please review the PR.
