### ISSUE TITLE
save_config/load_config for torch._dynamo.config and friends hardcodes file paths

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#93852]
### 🐛 Describe the bug

bad!!!

### Versions

master

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by gchanan** [comment]
I couldn't find any hardcoded paths in https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/config_utils.py but this issue is ambiguous enough that I'm not sure I was looking int the correct place.

**Comment by ezyang** [comment]
This is specifically referring to the config that is produced when you `save_config`.

**Comment by williamwen42** [comment]
Repro for current main:
```python
import torch

torch._dynamo.config.verbose = True

@torch.compile(backend="relu_compile_error_TESTING_ONLY")
def fn(x):
    for _ in range(10):
        x = torch.sin(x)
    x = torch.relu(x)
    for _ in range(10):
        x = torch.cos(x)
    return x

fn(torch.randn(20, 20))
```

What are some examples of hardcoded file paths in the config?

**Comment by ezyang** [comment]
Stuff like

```
base_dir = dirname(dirname(dirname(abspath(__file__))))
```
