### ISSUE TITLE
[Feature request] Add `Tensor.device_as`

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#9386]
When we want to create a tensor in the middle of training process, because of consistency of `dtype` and `device`, it would be very nice to support a function `Tensor.device_as`, similar to that of `Tensor.type_as`

**Comment by SsnL** [comment]
`a.to(b.device)` is of the same length. is there anything wrong with it?

**Comment by soumith** [comment]
indeed, we made `to` the concise and powerful function to cover all of the typecasting / device-moving ops. I dont see a huge value in `device_as` vs a.to(b.device)`
