### ISSUE TITLE
Placeholder source builds for PyPI

### ISSUE THREAD

**Issue by lukeyeager** [pytorch/pytorch#939]
Current status:

* `pip install torch`: tries to install v0.1.2 but dies with `ImportError: No module named setup_helpers.env`
* `pip install pytorch`: tries to install v0.1 but dies with `ImportError: No module named setup_helpers.env`

As discussed at https://github.com/pytorch/pytorch/issues/707#issuecomment-284469744, I think it would be nice if the PyPI package threw a more helpful error.

I think the simplest thing to do is upload a source distribution which throws a `RuntimeError`.

If you agree, anyone with permissions to push to PyPI can use this branch:
https://github.com/lukeyeager/pytorch/tree/tmp-pypi-upload

And run these commands:
```sh
rm -rf dist/
PYTORCH_ALLOW_BUILD=true PYTORCH_PKG_NAME=torch   python setup.py sdist
PYTORCH_ALLOW_BUILD=true PYTORCH_PKG_NAME=pytorch python setup.py sdist
twine upload dist/*
```

**Comment by lukeyeager** [comment]
Obviously, feel free to take that code and run with it if you want to edit the README text, etc.

**Comment by soumith** [comment]
Thanks Luke.
I've done this for `pip install torch`.
I'm not the owner/maintainer of pytorch, @graingert is, and he said he'll transfer it to me / give commit rights. Once he gives me those rights, will do for `pip install pytorch` too.

**Comment by soumith** [comment]
this is now done. thanks Luke.

**Comment by lukeyeager** [comment]
Woah. @graingert got a little fancier with his exception than I did!

**Comment by graingert** [comment]
@lukeyeager I based it on django-unchained.

If pytorch.org adds an element:

```html
<div class="pip-install-pytorch">...</div>
```

with css:

```css
#pip-install-pytorch {
    display: none;
}

#pip-install-pytorch:target {
    display: block;
}
```

It will show that div when `pip install pytorch` launches the pytorch.org website.
