### ISSUE TITLE
Conflict between conda colab and Pytorch at Colab.

### ISSUE THREAD

**Issue by drorhunvural** [pytorch/pytorch#93908]
### 🐛 Describe the bug

I'm having problems running Colab and Pytorch at the same time

If I just run the installation code block below, `torch.cuda.is_available()` returns `True`, so there is no problem.

`!pip install torch==1.7.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

After installing condacolab like below in Colab, the problem starts.
```

!pip install -q condacolab
import condacolab
condacolab.install()
```

Please try as I gave the example below, because I still get True in the notebook, but when I create a python file in the drive and run it as below, I get False.

Let's assume we have a example.py and its content is as below. 
```
import torch
print(torch.cuda.is_available())
```

I get False output when I run the run block below
`!python '/content/example2.py'`

My opinion: `condacolab `package changing the environment that PyTorch is running in. The condacolab.install() function may be modifying the environment to disable GPU support

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.6
Libc version: glibc-2.31

Python version: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35)  [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.10
Is CUDA available: False
CUDA runtime version: 11.2.152
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] blas                      2.106                       mkl    conda-forge
[conda] cudatoolkit               11.2.2              hbe64b41_11    conda-forge
[conda] libblas                   3.9.0                     6_mkl    conda-forge
[conda] libcblas                  3.9.0                     6_mkl    conda-forge
[conda] liblapack                 3.9.0                     6_mkl    conda-forge
[conda] liblapacke                3.9.0                     6_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.24.1           py38h10c12cc_0    conda-forge
[conda] pytorch                   1.13.1              py3.8_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.1                 py38_cpu    pytorch
[conda] torchvision               0.14.1                 py38_cpu    pytorch

cc @ezyang @seemethere @malfet

**Comment by ezyang** [comment]
your environment says

```
[conda] pytorch 1.13.1 py3.8_cpu_0 pytorch
[conda] pytorch-mutex 1.0 cpu pytorch
```

so of course you don't have cuda support. You could try reinstlaling pytorch after condacolab, that might fix it
