### ISSUE TITLE
[Dynamo] Don't graph break on einops

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#93905]
### 🚀 The feature, motivation and pitch

Einops is a very popular library in PyTorch code, so we should aim to not graph break on it. For example, see https://github.com/lucidrains/vit-pytorch/blob/main/vit_pytorch/cait.py#L95

It currently causes dynamo to graph break.
```
import torch
from einops import rearrange
from torch._dynamo import allow_in_graph

# allow_in_graph(rearrange)

@torch.compile(fullgraph=True)
def f(x):
    x = x.cos()
    return rearrange(x, 'b n -> (b n)').sin()

f(torch.randn(20, 20, device='cuda'))
```

If you uncomment the `allow_in_graph` though, it works.
`cast(Tensor, tensor)` causes the break (for pytorch tensors it's a no-op). 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @gchanan @Xia-Weiwen @ipiszy @soumith @ngimel @desertfire @mlazos @yanboliang

**Comment by ezyang** [comment]
Maybe we can get einops to add the `allow_in_graph` clal.

**Comment by ngimel** [comment]
hi pri due to user activity

**Comment by vadimkantorov** [comment]
einops.rearrange is also all over the place in flash-attention repo (and also likely in lucidrains codes?): https://github.com/HazyResearch/flash-attention/blob/ad113948a6c3864fbe48156a9857e97a38ce758c/flash_attn/bert_padding.py#L97

**Comment by wconstab** [comment]
Is this fixed now? I worked with the Einops team to get https://github.com/pytorch/pytorch/issues/99031 landed, and I am not sure if there are additional issues.

**Comment by wconstab** [comment]
Closing this, as I confirmed the above repro with 'rearrange' works without a graphbreak by default on latest main, no need to uncomment the 'allow_in_graph'.  For clarity: the allow_in_graph is still happening, but it's done by default inside einops with some help from torchdynamo for einops versions earlier than 0.6.1 iirc.

**Comment by msaroufim** [comment]
Hey @ezyang @wconstab I'm gonna reopen this just to ask the question of whether we also expect einops to work well with dynamic shapes?

Got this issue with the openai/whisper model, repro here https://gist.github.com/msaroufim/a6f911eed16126a120dde9e3a6f5b8ff - just change add dynamic = True to compile step

**Comment by Chillee** [comment]
On latest einops + pytorch nightly this also works with dynamic shapes.

```
from einops import rearrange, reduce
import torch

@torch.compile(dynamic=True)
def f(x):
    y = rearrange(x, 'b c h w -> b h w c')
    y2 = reduce(x, 'b c h w -> b c', reduction='mean')
    return y, y2

print(f(torch.randn(10, 32, 100, 200)))
print(f(torch.randn(5, 32, 100, 200)))
```

<img width="889" alt="image" src="https://github.com/pytorch/pytorch/assets/6355099/61f960eb-cbdc-44c1-b1ec-9e60c95b20bc">

**Comment by vadimkantorov** [comment]
@Chillee btw wasn't a reimpl of rearrange integrated into core?
