### ISSUE TITLE
backward pass different behaviors with inplace operation

### ISSUE THREAD

**Issue by anshulpaigwar** [pytorch/pytorch#9391]
## Issue description
Strange behaviour with inplace operation in the backward pass

## Code example

Using sigmoid function and then inplace operation raises the error on backward pass

```
>>> a = torch.tensor([1,2,3.], requires_grad = True)
>>> b = a.sigmoid()
>>> b
tensor([ 0.7311,  0.8808,  0.9526])
>>> b[1]= 2
>>> b.sum().backward()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

```

inplace operation here does not raise the error on backward pass:

```
>>> a = torch.tensor([1,2,3.], requires_grad = True)
>>> b = 1/((-a).exp()+1)
>>> b
tensor([ 0.7311,  0.8808,  0.9526])
>>> b[1]= 2
>>> b.sum().backward()
>>> a.grad
tensor([ 0.1966,  0.0000,  0.0452])
```

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.14.2)
[pip] pytorchviz (0.0.1)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] Could not collect

**Comment by soumith** [comment]
this is fully expected.

`b` is needed to correctly compute the gradient of `a`. Hence, modifying `b` in-place cannot allow correct gradients to be computed for `a`.

**Comment by anshulpaigwar** [comment]
I agree @soumith for the first case but my doubt was shouldn't the second case also raise an error?? after all `b = a.sigmoid()` and `b = 1/((-a).exp()+1)` are the same so both the cases should raise an error

**Comment by soumith** [comment]
in the second case, b is the result of `1 / x`, and the derivative wrt `x` is `-1 / x^2`, which does not require `b` in the formula. In this case, if you make `c = ((-a).exp()+1); b = 1 / c` and then do an in-place operation on `c`, the backward will complain the same.

**Comment by anshulpaigwar** [comment]
Now I get it thanks for explaining :+1:
