### ISSUE TITLE
pytorch/torch/torch_version.py

### ISSUE THREAD

**Issue by Shikamaru5** [pytorch/pytorch#93953]
Maybe I've overlooked something but both in my code and in the docs on github as far as I can tell torch_version calls, from .version import __version__ as internal_version. However in order for that to work there'd have to be a version script with __version__ in it which I don't see.

**Comment by Shikamaru5** [comment]
Looks like I managed to fix it by changing it to:

      import packaging
      from packaging.version import Version as internal_version

That got around the silliness, however, it appears that __init__.py is doing something similar so I'll need to change that one as well.

**Comment by albanD** [comment]
The `version.py` is generated at build time via https://github.com/pytorch/pytorch/blob/master/tools/generate_torch_version.py#L61
It is part of the binary we ship via pip/conda. Or if you install from source, it is generated as part of the build process.
