### ISSUE TITLE
[pytorch] Strange tensor printing behavior

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9395]
Is there any reason the second tensor is printed as _exactly_ zero?

Seems scientific notation is enabled for some cases, but gets disabled past some number (why 2e-5 is worse than 1e-5?)

Stumbled on this while examining some tensor which appeared to be all zeros, except in fact none of the elements were zero.

```
In [31]: torch.Tensor([1e-5])
Out[31]: tensor([1.0000e-05])

In [32]: torch.Tensor([2e-5])
Out[32]: tensor([0.0000])
```

at 0.5.0a0+8d38460

**Comment by vishwakftw** [comment]
Try `torch.set_printoptions(precision=5)`. It should give the correct output.

However, there is a nit in the docs, the default value of precision seems to be 4.

**Comment by vishwakftw** [comment]
That being said, I find some inconsistencies in the printing format, similar to @vadimkantorov's report:
```python
torch.tensor([1e-05])
tensor([1.0000e-05])

torch.tensor([2e-05])
tensor([0.00002])
```
Here the `precision` was set to 5.

**Comment by vadimkantorov** [comment]
Here: https://pytorch.org/docs/master/torch.html#torch.set_printoptions
it says "precision – Number of digits of precision for floating point output (default = 8)." which made me think the default was actually 8 (and I didn't find any `torch.get_printoptions`)

It also seems quite strange that 1e-05 and 2e-05 get printed differently at precision 4, since the number of digits to be printed in scientific notation is the same.

**Comment by vishwakftw** [comment]
In `torch/_tensor_str.py`, you can find the default options.

**Comment by vadimkantorov** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/12746
