### ISSUE TITLE
pytorch/torch __init__.py

### ISSUE THREAD

**Issue by Shikamaru5** [pytorch/pytorch#94001]
Line 84 from .version import cuda as cuda_version I assume it's actually supposed to be something along the lines of:
      from CUDA import v12
      from v12.version import cuda as cuda_version
I'm wondering because packaging.version does not have a cuda in it so I'm guessing that straight up wouldn't work to import from that package?

**Comment by malfet** [comment]
Would it be possible to share an error log or something along those line?

If you have a general suggestion on improving PyTorch coding style, please do not hesitate to create a post in https://dev-discuss.pytorch.org/

If you have a question on how to use PyTorch, please post https://discuss.pytorch.org/


Closing this issue, but please do not hesitate to open a new one with more details
