### ISSUE TITLE
Type promotion mismatch between eager and inductor pow

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#94010]
### 🐛 Describe the bug

`CpuTests.test_pow2` is failing because of the mismatch between scalar type promotion for eager and inductor, see 
https://github.com/pytorch/pytorch/blob/37a28255cb9c2a78fd2a27ed7921e8c9672a57ab/aten/src/ATen/native/cpu/PowKernel.cpp#L112-L115
vs
```c++
extern "C" void kernel(const float* __restrict__ in_ptr0,
                       float* __restrict__ out_ptr0,
                       float* __restrict__ out_ptr1)
{
    #pragma omp parallel num_threads(12)
    {
        {
            #pragma omp for 
            for(long i0=0; i0<256; i0+=1)
            {
                auto tmp1 = in_ptr0[i0];
                auto tmp0 = static_cast<float>(1000);
                auto tmp2 = std::pow(tmp0, tmp1);
                auto tmp3 = std::pow(tmp1, tmp0);
                out_ptr0[i0] = tmp2;
                out_ptr1[i0] = tmp3;
            }
        }
    }
}
```
generated for
https://github.com/pytorch/pytorch/blob/7db4d813c3e30cdc6c9937e0c2ff68f4a84edf49/test/inductor/test_torchinductor.py#L2991-L2992

Moving type to `torch.float64` make test pass

### Versions

CI

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by malfet** [comment]
@ngimel do you think it'll be BC breaking change to make eager pow use `float` instead of `double` for `torch.pow(x, scalar)`? if x is torch.float32? As here it's not really an accumulator type, but rather a weird implementation detail

**Comment by ngimel** [comment]
Yeah I think it's fine to use `float` in eager, it's just some legacy behavior, I doubt someone relies on it.

**Comment by williamwen42** [comment]
Is this fixed? Verify with https://github.com/pytorch/pytorch/pull/114912
