### ISSUE TITLE
FX quantization: getCudnnDataTypeFromScalarType() not supported for QUInt8

### ISSUE THREAD

**Issue by eezhang123** [pytorch/pytorch#94030]
### 🐛 Describe the bug

''
Quantization Tutorial
''
import torch
from torch import nn
from torch.ao.quantization import QConfigMapping
import torch.quantization.quantize_fx as quantize_fx
import copy

class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 3, 1)
        self.conv2 = nn.Conv2d(6, 4, 3, 1)
    
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        return x
model = M()
model.cuda()
model.eval()

model_to_quantize = copy.deepcopy(model)
qconfig_mapping = QConfigMapping().set_global(torch.quantization.get_default_qconfig('qnnpack'))
#prepare
model_prepared = quantize_fx.prepare_fx(model_to_quantize, qconfig_mapping, torch.randn(32, 3, 224, 224))
#calibrate
output = model_prepared(torch.randn(32, 3, 224, 224))

model_quantized = quantize_fx.convert_fx(model_prepared)

images = torch.randn(32, 3, 224, 224)
output = model_quantized(images)

‘’
Bug
‘’
   output = model_quantized(images)
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.6", line 8, in forward
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/nn/intrinsic/quantized/modules/conv_relu.py", line 92, in forward
    return torch.ops.quantized.conv2d_relu(
  File "/root/anaconda3/envs/fx/lib/python3.10/site-packages/torch/_ops.py", line 442, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: getCudnnDataTypeFromScalarType() not supported for QUInt8

### Versions

/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  1
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7763 64-Core Processor
Stepping:            1
CPU MHz:             1542.932
CPU max MHz:         2450.0000
CPU min MHz:         1500.0000
BogoMIPS:            4890.45
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-63
NUMA node1 CPU(s):   64-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.0
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl
[conda] efficientnet-pytorch      0.7.0                    pypi_0    pypi
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0           py310h7f8727e_0
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0
[conda] mkl_random                1.2.2           py310h00e6091_0
[conda] numpy                     1.23.5          py310hd5efca6_0
[conda] numpy-base                1.23.5          py310h8e6c178_0
[conda] pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.1              py310_cu116    pytorch
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.14.1              py310_cu116    pytorch

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by Coderx7** [comment]
As far as I remember PyTorch never provided quantized operator implementations on CUDA, only CPU was supported for testing quantized models. see [this](https://pytorch.org/docs/1.10/quantization.html#natively-supported-backends)

**Comment by jerryzh168** [comment]
yeah we don't have official GPU support right now, see: https://discuss.pytorch.org/t/quantization-frequently-asked-questions/161251#quantized-inference-in-gpu-3
