### ISSUE TITLE
Segmentation fault with large dilated Conv2d

### ISSUE THREAD

**Issue by denjots** [pytorch/pytorch#9404]
## Issue description

Pytorch 0.4.0 gives a segmentation fault with dilated 2D convolutions over a specific size.

## Code example

import torch
import torch.nn as nn
model = nn.Conv2d(in_channels=64, out_channels=64, kernel_size=5, dilation=2)
model(torch.zeros([1, 64, 1166, 1166]))  # This runs
model(torch.zeros([1, 64, 1167, 1167]))  # This crashes

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: TITAN X (Pascal)
GPU 2: Quadro K2200

Nvidia driver version: 390.59
cuDNN version: Probably one of the following:
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.10
/usr/local/cuda-7.5/lib64/libcudnn.so.5.1.3
/usr/local/cuda-7.5/lib64/libcudnn_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.10
/usr/local/cuda-8.0/lib64/libcudnn_static.a

**Comment by ezyang** [comment]
@SsnL, do you think this is the same as the segfault you showed me a week ago on convolution?

**Comment by SsnL** [comment]
@ezyang ah yes. int overflow. I only fixed conv3d because I didn’t want to hurt perf. I’ll fix all of them.
