### ISSUE TITLE
Consider upgrade to Python 3.8+ syntax with `pyupgrade`

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#94040]
### 🚀 The feature, motivation and pitch

PyTorch now supports Python 3.8+ only.

https://github.com/pytorch/pytorch/blob/ca8450849bcfd694c4ddfb9160cd87648cfcec48/setup.py#L216-L222

But there are still many legacy Python syntaxes in the codebase. Such as:

Redundant `object` inherence:

```diff
- class A(object):
+ class A:
      ...
```

`super` call:

```diff
  class A:
      pass

  class B(A):
      def __init__(self):
-         super(B, self).__init__()
+         super().__init__()
```

string format:

```diff
- '%s' % x
+ f"{x}"
- '{}'.format(x)
+ f"{x}"
```

There is a tool [`pyupgrade`](https://github.com/asottile/pyupgrade) that can automatically update the code. The migration can be easily done by:

```bash
pyupgraede --py38-plus $(find torch -name '*.py' -o -name '*.pyi')
lintrunner -a
```

It would be nice if you consider `pre-commit` integration to apply this for future code changes.

cc @malfet @seemethere @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by Skylion007** [comment]
Yeah, I was planning on doing this at some point anyway

**Comment by ezyang** [comment]
The last time someone did this for super(), the PR got stuck because it also threw in some non semantics preserving changes. I suggest structuring the PRs so it does only *one* transform at a time (e.g., conversion to super()) so that the obviously semantics preserving changes can go through.

**Comment by Skylion007** [comment]
I started merging fixes in with #94308 #94309

**Comment by XuehaiPan** [comment]
Opened a PR to move some imports from `typing_extensions` to `typing` #94490.

**Comment by XuehaiPan** [comment]
> The last time someone did this for super(), the PR got stuck because it also threw in some non semantics preserving changes.

Rewrite `super` call in a single inheritance case is safe. The `super` proxy object is returned based on the `mro`. In single inheritance, the `mro` entries are simple and clear.

https://docs.python.org/3/library/functions.html#super

> There are two typical use cases for super. In a class hierarchy with single inheritance, super can be used to refer to parent classes without naming them explicitly, thus making the code more maintainable. This use closely parallels the use of super in other programming languages.

**Comment by XuehaiPan** [comment]
I have seen many references to the [six](https://pypi.org/project/six) and [future](https://pypi.org/project/future) libraries. Can they be removed? I have also seen some tests for Python 2 backward compatibility tests. Do we need them in PyTorch 2.0? Is it necessary to test for a Python 2 extension now?

**Comment by Skylion007** [comment]
We've been working on removing six and future from the codebase where possible. There is also our custom torch._six module that should also be cleaned up a bit.

**Comment by XuehaiPan** [comment]
Opened a PR:

- #94709

Some Python 2 specific blocks are not touched. Only removes the imports and pip-install.

**Comment by Skylion007** [comment]
> Opened a PR:
> 
>     * [[BE] Remove dependency on `six` and `future` #94709](https://github.com/pytorch/pytorch/pull/94709)
> 
> 
> Some Python 2 specific blocks are not touched. Only removes the imports and pip-install.

We still have Python 2 specific code blocks?

**Comment by XuehaiPan** [comment]
> We still have Python 2 specific code blocks?

Yes. You can search for `python2` and `Python 2`.

https://github.com/pytorch/pytorch/search?q=python2&type=

**Comment by Skylion007** [comment]
Most of those can probably be removed in Torch at least since we don't support Python2 anymore.

**Comment by bryant1410** [comment]
Hey, I went ahead and ran pyupgrade in #101508. I'm happy to divide it into multiple PRs if others think it's more convenient.

**Comment by XuehaiPan** [comment]
> I'm happy to divide it into multiple PRs if others think it's more convenient.

Hi @bryant1410, you may run [`ruff`](https://github.com/charliermarsh/ruff) (a reimplementation of a bunch of linters in Rust) with [`UPnnn` code](https://beta.ruff.rs/docs/rules/#pyupgrade-up).

It would be best to create a PR for one rule code at a time. For example:

```bash
# UP031: Use format specifiers instead of percent format
git checkout main
git checkout -b pyupgrade-up031
ruff check --target-version=py38 --select=UP031 --fix --verbose torch
```

```bash
# UP032: Use f-string instead of `format` call
git checkout main
git checkout -b pyupgrade-up032
ruff check --target-version=py38 --select=UP032 --fix --verbose torch
```

```bash
# UP034: Avoid extraneous parentheses
git checkout main
git checkout -b pyupgrade-up034
ruff check --target-version=py38 --select=UP034 --fix --verbose torch
```

Then submit 3 PRs separately.

**Comment by bryant1410** [comment]
Opened #101606 to remove the extraneous parentheses.

**Comment by Skylion007** [comment]
Closed by ruff's pyupgrade rules being enabled.
