### ISSUE TITLE
pytorch/torch __init__.py, V1.0

### ISSUE THREAD

**Issue by Shikamaru5** [pytorch/pytorch#94058]
I was informed that my previous issue didn't have enough details so I'll try again but with a log from my git terminal, which will hopefully explain a little clearer.

![pytorch error](https://user-images.githubusercontent.com/86502093/216684132-fddf641e-6e9f-4a96-8746-0ad5fa8316d6.jpg)

I just had an issue in pytorch/torch torch_version.py where it tried to call from the packaging program's version.py and once I made it so that it directly did that instead of lazy importing it, it worked. So I was wondering if I could change the .version in __init__.py in the same manner?
Could line 84 from .version import cuda as cuda_version be something along the lines of:

      from CUDA import v12
      from v12.version import cuda as cuda_version

**Comment by malfet** [comment]
Do you mind running `python3 -mtorch.utils.collect_env` and post results here. Or describe how did you build PyTorch? (I.e. I've never seen pytorch installed as `pytorch.torch`

**Comment by Shikamaru5** [comment]
When I ran python3 -mtorch.utils.collect_env, it told me that python wasn't found and to run without arguments to download from the Microsoft Store. I've recently had to reboot my computer and redownload everything, so I'm not sure that everything is back to normal, and when downloading PyTorch as instructed it gave me a Pytorch-master file which I renamed to Pytorch so that I could make it easier for one of my scripts to import because it wouldn't simply import torch. However, before my computer had to rebooted it worked perfectly fine. When I downloaded Pytorch I used pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 because that was the latest version of Cuda the Pytorch site recommended, although maybe I should've gone with CPU. I do want the functionality to use my GPU though, and my Cuda is a later version than 11.7 though, it's CUDA V12.0.

**Comment by malfet** [comment]
> I do want the functionality to use my GPU though, and my Cuda is a later version than 11.7 though, it's CUDA V12.0.

NVIDIA/CUDA drivers are forward compatible: I.e. one can have CUDA-12 toolkit installed, but use CUDA-11.7 prebuilt binaries. So unless you have 4090 (which is not supported by 11.7, but is supported by 11.8), 11.7 build would most likely work in your case.

**Comment by Shikamaru5** [comment]
Oh ok, ya I don't have the 4090, so at least that isn't the worrisome part, do you think that I should just delete the Pytorch folder and reinstall again to see if it works correctly with the new install?

**Comment by malfet** [comment]
Cloning pytorch repository into `python-3.11/lib/site-package` is not a supported way of installing PyTorch from source, for more information see https://github.com/pytorch/pytorch/#from-source

**Comment by Shikamaru5** [comment]
Right, I got PyTorch off the site, but with this link that's like saying the exact opposite, do you mean I should download Anaconda, delete Pytorch, go back to the pytorch.org and try reinstalling it with conda instead of pip?

**Comment by malfet** [comment]
> Right, I got PyTorch off the site, but with this link that's like saying the exact opposite do you mean I should download Anaconda, delete Pytorch, go back to the pytorch.org and try reinstalling it with conda instead of pip?

**Comment by malfet** [comment]
Closing, as this does not seem like a pytorch problem, but rather the installation hurdles. Please use issues to report bugs in PyTorch and https://discuss.pytorch.org as general forums to ask questions/seek help.
