### ISSUE TITLE
[jit][script] support tensor.expand([-1,-1,10,-1,-1])

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#9408]
The topic of this issue has changed. 

Original content:
~~Currently pytorch has `torch.expand` and `torch.expand_like`, which allow expanding the shape of a tensor to a fully specified shape(directly as in `expand` or indirectly as in `expand_like`). It would be more conveniently in some cases to write user code if we add a `torch.expand_dim`.~~

~~For example, if you have a tensor `(5, 3, 1, 4, 8)`, doing a `tensor.expand_dim(2, 10)` gives a tensor of shape `(5, 3, 10, 4, 8)`.~~

~~`expand_dim` vs `expand` is like `flatten` vs `reshape`. There is no new function, just some convenience.~~

~~Also, if the pytorch team confirm that this is contribute welcome, I can do the job to add it to ATen.~~

New topic:

It seems that the following code is not supported in JIT well

```python
x = torch.randn(4,5,1,3,3)

@torch.jit.script
def f(x):
    return x.expand([-1,-1,10,-1,-1])

f(x)
```

Currently it gives RuntimeError `input: Assertion inputs_.size() == 1` failed.

**Comment by gchanan** [comment]
I think there are a couple of issues with this:
1) Naming: https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html already exists and does unsqueeze, basically.  Users aren't going to expect expand_dim to do what you are proposing here.
2) I don't really the see the use case; most of the time the expands happen implicitly, you rarely want to expand a single dimension explicitly.

**Comment by zasdfgbnm** [comment]
@gchanan 
1. I think we can name it `expand_at` instead
2. Explicit expand might be useful for ops that does not support broadcast, such as `stack`, `cat`. Also useful in JIT:
```python
import torch

a = torch.randn([4,5,1,3,3])

@torch.jit.script
def f(x):
    new_shape = list(x.shape)
    new_shape[2] = 10
    return x.expand(new_shape)

print(f(a))
```
Currently it gives
```

**Comment by t-vi** [comment]
The right IMO way to do this is by using -1 for the other dimensions (and I would expect the case of having a variable number of dimensions to be particular enough to not warrant a general torch api for it).
```
x = torch.randn(4,5,1,3,3)

@torch.jit.script
def f(x):
    return x.expand([-1,-1,10,-1,-1])

f(x)
```
Supporting (more of) expand would be nice for the JIT, though...

**Comment by zasdfgbnm** [comment]
@t-vi Yes, this do looks better. Currently it gives RuntimeError `input: Assertion inputs_.size() == 1 failed.` I can take a look at that.

**Comment by fmassa** [comment]
I think there are some people voting for adding a `broadcast` function. That would solve your problems, right?

**Comment by zasdfgbnm** [comment]
@fmassa Do you mean https://github.com/pytorch/pytorch/issues/8076? Yes, it solves the problem for using things like stack.

**Comment by zou3519** [comment]
It sounds like the conclusion is that the JIT should have better support for this

**Comment by zasdfgbnm** [comment]
solved
