### ISSUE TITLE
[feature request] Allow `torch.unsqueeze` to insert multiple new dims

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#9410]
I suggest change the API of `unsqueeze` to `self.unsqueeze(dim, n=1) → Tensor` such that user can do a
```python
tensor.unsqueeze(0, 4)
```
rather than 
```python
tensor.unsqueeze(0).unsqueeze(0).unsqueeze(0).unsqueeze(0)
```

**Comment by gchanan** [comment]
I don't think the value is really there; you can already do something like:
```
tensor[(None,)*n]
```

**Comment by zasdfgbnm** [comment]
@gchanan 
Hmmm, basically what I'm thinking was, I'm trying to JIT some code, below is a demo

```python
import torch

a = torch.randn(5,3)

#@torch.jit.script
def f(x):
    return x[:, None, None, :]

@torch.jit.script
def g(x):
    return x.unsqueeze(1).unsqueeze(1)

print(g(a).shape)
```

Trying to script `f` would get a
```
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
```
and `g` looks really ugly...

**Comment by tshadley** [comment]
> I don't think the value is really there; you can already do something like:
> 
> ```
> tensor[(None,)*n]
> ```

That works if you want to unsqueeze at the front of the array but what about at the end?

```
import torch
t = torch.Tensor(3) 
t_f = t[(None,)*3]
print(t_f.shape)
t_b = t[...,(None,)*3]
print(t_b.shape)
```

This gives an error for the second. 
```
*** TypeError: an integer is required (got type NoneType)
```

Although 
```
t[...,None,None,None] 
```
works fine.

Torch version 1.0.0

**Comment by apaszke** [comment]
Another argument to against this extension of unsqueeze is that it is not clear if the indices are equivalent to a sequence of unsqueeze calls, or do they use the original dimensions of that tensor.

**Comment by AshwinRJ** [comment]
Fair enough

**Comment by mrTsjolder** [comment]
@tshadley 

> ```
> import torch
> t_b = t[...,(None,)*3]
> print(t_b.shape)
> ```

To unsqueeze at the end, you could try to use `t_b = t[(..., ) + (None, ) * 3]` (works for me on version 1.1.0).

**Comment by francois-rozet** [comment]
To unsqueeze `n` times at dim `d`,  `t[(slice(None),) * d + (None, ) * n]` works for me.

**Comment by vadimkantorov** [comment]
An alternative proposed way: `tensor.unsqueeze(dim = (1, 1, 1, 2))`. The indexing would be wrt to the initial dimensions, e.g. equivalent to:
```python
for d in sorted(dim, reverse = True):
    tensor = tensor.unsqueeze(d)
```
This could be more explicit way compared to dances with slices with None and multiplication of tuples

Advantage of this way: more close to other multidim methods.
Disadvantage: still requires preparation of array, but it's easier: tensor.unsqueeze(dim = (-1,) * n)

These unsqueezes are needed for preparing for expand operations e.g. as in https://github.com/pytorch/pytorch/issues/52743#issuecomment-785053464

**Comment by hushell** [comment]
> @tshadley
> 
> > ```
> > import torch
> > t_b = t[...,(None,)*3]
> > print(t_b.shape)
> > ```
> 
> To unsqueeze at the end, you could try to use `t_b = t[(..., ) + (None, ) * 3]` (works for me on version 1.1.0).

Another idea (probably more readable): `t_b = t.reshape( t.shape + (1,) * 3 )`

**Comment by viviankessler** [comment]
Try
``
n = 4

tensor.view(*[1]*n + [-1])
``

**Comment by vadimkantorov** [comment]
there're plenty of workarounds, but they are inconvenient and not torchscriptable
