### ISSUE TITLE
[feature request] add `torch.find` to find the indices of values

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#9413]
I'm suggesting to add the following operator to pytorch:
```python
result = torch.find(tensor, from_)
```
This operator outputs a long tensor of the same shape as the argument `tensor`, where the `result[i,j,..]` is the first index at vector `from_` whose value is the same as `tensor[i,j,..]`.

For example:
```python
a = torch.tensor([0, 10, 20, 30])
b = torch.tensor([[ 0, 30, 5],
                  [20,  1, 0]])
torch.find(b, a)
```
should give
```python
tensor([[ 0, 3,-1],
        [ 2,-1, 0]])
```
If the pytorch team can confirm that this feature is helpful to add to pytorch, I will do the job of implementing it in ATen.

**Comment by hmc-cs-mdrissi** [comment]
As a note, I'd also find the first arg scalar version of this feature helpful as I have one model that is currently using the convert to list and index stuff. I use it because the model at each step chooses which weight matrix to use based off a value it computed at the prior step.

**Comment by zasdfgbnm** [comment]
@fmassa 

Not really, for example:
```python
import torch
tensor = torch.randint(10,[3,4,5], dtype=torch.long)
values = torch.arange(10, dtype=torch.long)
result = torch.nonzero(tensor[..., None] == values)
print(result.shape)
```
gives
```
torch.Size([60, 4])
```
But what I want is
```
torch.Size([3, 4, 5])
```

**Comment by fmassa** [comment]
The information that you want is in the returned tensor from my function, it just needs a transformation to add your `-1` indices. The last column is the index of the retrieved value
