### ISSUE TITLE
[pt2] The min and max parameters of torch.clamp do not support numpy format

### ISSUE THREAD

**Issue by hhaAndroid** [pytorch/pytorch#94174]
### 🐛 Describe the bug

```python
import torch
import numpy as np


def fn(input):
    max_ratio = np.abs(np.log(4))
    dwh = input.clamp(min=-max_ratio, max=max_ratio)
    return dwh

x = torch.rand([1]).cuda()

ret_eager = fn(x)
print('==== Eager mode OK! ====')

compiled = torch.compile(fn, backend='eager')
ret_compiled = compiled(x)
print('==== torchcomp mode OK! ====')
```

```shell
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument min in method wrapper_CUDA_clamp_Tensor)
```

### Versions

Pytorch version: 2.0.0.dev20230131+cu116

cc @ezyang @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @msaroufim @wconstab @zou3519 @aakhundov @soumith @ngimel @yanboliang @Xia-Weiwen @desertfire

**Comment by soumith** [comment]
this seems like a higher priority bug, as it as correctness issue

**Comment by ngimel** [comment]
This is not a silent correctness issue (dynamo errors out), backend="inductor" (default) works, the reason for "eager" backend erroring out is dynamo wraps numpy variables into a 0d cpu tensor, and `clamp` eager doesn't support it (inductor `clamp` is permissive enough to support this):
```
torch.clamp(torch.randn(4, device="cuda"), min=torch.tensor(-3.), max=torch.tensor(3.)) # same error
```

**Comment by maxshatskiy** [comment]
It seems that I have error related to this problem.

I use _F.interpolate(g, size=input_size[2:], mode=upsample_mode)_ and get following error:

### File "/usr/local/lib/python3.10/dist-packages/torch/_decomp/decompositions.py", line 2821, in upsample_bilinear2d
    x_ceil = torch.ceil(x).clamp(max=in_h - 1).to(torch.int64)

### RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument max in method wrapper_CUDA_clamp_Tensor)

Is there any work around?

**Comment by lezcano** [comment]
This is expected. It works if you do `max_ratio = abs(math.log(4))`. Using NumPy here is overkill.
If you still insist on using NumPy code here, you can do it as discussed here:
https://pytorch.org/docs/main/torch.compiler_faq.html#can-i-execute-numpy-code-on-cuda-and-compute-gradients-via-torch-compile
by using `torch.device` as a context manager.

Alas, this is expected behaviour, as `torch.compile(numpy)` handles NumPy scalars as tensors, as documented in that FAQ.
