### ISSUE TITLE
Cannot install PyTorch: http error 403

### ISSUE THREAD

**Issue by Leedehai** [pytorch/pytorch#942]
OS: OSX
Python version: 2.7
CUDA: none
I tried to install PyTorch using pip, but it shows:

$ pip install https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl
Collecting torch==0.1.10.post2 from https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl
  HTTP error 403 while getting https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl
  Could not install requirement torch==0.1.10.post2 from https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl because of error 403 Client Error: Forbidden for url: https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl
Could not install requirement torch==0.1.10.post2 from https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl because of HTTP error 403 Client Error: Forbidden for url: https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl for URL https://s3.amazonaws.com/pytorch/whl/torch-0.1.10.post2-cp27-none-macosx_10_7_x86_64.whl

**Comment by soumith** [comment]
Thanks for the report. I just updated the commands on the website to be correct. See the updated commands on http://pytorch.org

**Comment by Leedehai** [comment]
Thanks! Successfully installed.
