### ISSUE TITLE
aarch64 MKLDNN_ACL: Arm Compute Library(ACL) patching for PyTorch2.0

### ISSUE THREAD

**Issue by snadampal** [pytorch/pytorch#94264]
Hi PyTorch team, we have these two commits from Arm Compute Library that improve the aarch64 pytorch inference by ~25%.

> https://review.mlplatform.org/c/ml/ComputeLibrary/+/8655 (merged)
> https://review.mlplatform.org/c/ml/ComputeLibrary/+/9068/3..4 (under review)

These  are part of the next ACL release happening end of February. Since the release timelines do not match with PT2.0, we need to carry them as patches for the PT2.0 release. Please guide me on how to make them part of the release.  Thank you!

cc @malfet @seemethere

**Comment by ZailiWang** [comment]
@jgong5

**Comment by malfet** [comment]
@snadampal if those changes have already been merged, and ACL is build from source, one is free to select any commit hash to be included into the build. So just propose a PR against the build script, and we'll accept it

**Comment by snadampal** [comment]
Thanks @malfet . on a similar note, we have the below 3 PRs (2 on pytorch and 1 on ideep) under review which again improved the pytorch inference performance substantially. If they are not merged before the PT2.0 cutoff, is it acceptable to take them into the builder script for aarch64 wheel building alone?

> https://github.com/intel/ideep/pull/158
> https://github.com/pytorch/pytorch/pull/93888
> https://github.com/pytorch/pytorch/pull/91763

**Comment by malfet** [comment]
@snadampal I don't know about ideep PR (@jgong5 do you know who would be the right reviewer for that one?), but we can not accept contributions to PyTorch if author have not signed contributor CLA. (#91763 was approved almost a month ago, but couldn't go in until CLA is signed )

**Comment by jgong5** [comment]
> I don't know about ideep PR (@jgong5 do you know who would be the right reviewer for that one?)

@XiaobingSuper and I will take a look.

**Comment by jgong5** [comment]
@snadampal I left some additional suggestions/questions in https://github.com/intel/ideep/pull/158. Please check. As long as these comments are addressed, we are good to accept the changes. BTW, I noticed that you intended to catch these changes in the PT 2.0 release. But AFAIK, PT 2.0 branch cut would happen soon, not sure if we can still catch the deadline...

**Comment by jgong5** [comment]
cc @fzhao3

**Comment by snadampal** [comment]
Hi @fzhao3 , @malfet , the ideep PR (https://github.com/intel/ideep/pull/162) got merged last night. I'm not sure who owns the ideep submodule commit updates in PyTorch. could you please let me know who can help. thank you!
cc: @jgong5

**Comment by jgong5** [comment]
@snadampal I believe I have the rights to land it. We are doing some tests internally to make sure the updated ideep is in good shape. Let us land it as soon as the tests are green.

**Comment by fzhao3** [comment]
@snadampal https://github.com/pytorch/pytorch/pull/94719 is the one to upgrade ideep submodule commit. @jgong5 will land it as soon as the tests are green.

**Comment by snadampal** [comment]
Thank you so much @jgong5 , @fzhao3 .

**Comment by malfet** [comment]
Reopening the issue. So iDeep changes has been integrated, not sure about ACL though. If they are already part of trunk, one can tweak the build script to use particular commit, but I would prefer to avoid patching the codebase.
