### ISSUE TITLE
InstanceNorm2d not working when using torch_directml device

### ISSUE THREAD

**Issue by casonwight** [pytorch/pytorch#94271]
### 🐛 Describe the bug

I am creating a WGAN, and there is a bug with the `torch.nn.InstanceNorm2d` class when I pass the Module to a torch_directml device. I followed the steps [here](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-pytorch-windows) to use non-cuda GPUs for deep learning. Everything has been fine until I tried to use the `torch.nn.InstanceNorm2d` class.  

Minimum reproducible example:
```python 
import torch_directml
import torch
from torch import nn

gpu_device = torch_directml.device()
  
class Model(nn.Module):
     def __init__(self):
          super().__init__()
          self.net = nn.InstanceNorm2d(3, affine=True)

     def forward(self, x):
          return self.net(x)

model = Model().to(gpu_device)
x = torch.randn(10, 3, 64, 64).to(gpu_device)
y = model(x)
```

Error:
```
Traceback (most recent call last):
  File "C:\Users\cason\repos\cats-GAN\src\models\discriminator.py", line 80, in <module>
    y = model(x)
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\cason\repos\cats-GAN\src\models\discriminator.py", line 72, in forward
    return self.net(x)
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\nn\modules\instancenorm.py", line 74, in forward
    return self._apply_instance_norm(input)
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\nn\modules\instancenorm.py", line 34, in _apply_instance_norm
    return F.instance_norm(
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\nn\functional.py", line 2495, in instance_norm
    return torch.instance_norm(
RuntimeError: op.is_output INTERNAL ASSERT FAILED at "C:\\cb\\pytorch_1000000000000\\work\\aten\\src\\ATen\\TensorIterator.cpp":349, please report a bug to PyTorch. Found type undefined input tensor!
```

I have also noticed that without affine=True, I get other errors as well (that aren't the same as when using cpu device). I can add examples of these other issues if wanted, but I suspect it is likely the same root issue of InstanceNorm2d not integratingf with torch_directml.

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3501
DeviceID=CPU0
Family=205
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3501
Name=Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
ProcessorType=3
Revision=24067

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==1.13.1
[pip3] torch-directml==0.1.13.1.dev230119
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2022.1.0           h858461b_193
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch                   1.13.1              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch-directml            0.1.13.1.dev230119          pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment]
Thank you for reporting the issue. Let me try to route it to the folks that developed it.
@vladimir-aubrecht do you know what would be the right repository to report DirectML issues?
cc: @chauhang

**Comment by casonwight** [comment]
Relevant issue with BatchNorm2d: https://github.com/pytorch/pytorch/issues/94359

**Comment by vladimir-aubrecht** [comment]
@malfet I believe it's this one 😊 
https://github.com/microsoft/DirectML

**Comment by iremyux** [comment]
Hi @casonwight , 
It seems like the right place to report this issue is DirectML instead of Pytorch as stated before. Can you please open a new issue in [DirectML repo](https://github.com/microsoft/DirectML)?
