### ISSUE TITLE
torch.cuda.is_available() False

### ISSUE THREAD

**Issue by bropines** [pytorch/pytorch#94291]
### 🐛 Describe the bug

Maybe I'm doing something wrong or maybe I'm dumb, but 3 times I completely removed python, video card drivers and cudatoolkit. The effect is zero.
![image](https://user-images.githubusercontent.com/57861007/217191138-3000d43e-57b7-459c-9fcf-0a4962066674.png)
![image](https://user-images.githubusercontent.com/57861007/217191160-1783a3d2-b15a-4b3f-8bf2-dd0eb5b01ec2.png)
![image](https://user-images.githubusercontent.com/57861007/217191238-1a7d7370-25ff-4ec6-b4f7-01475be7dcaf.png)

### Versions

```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\bropi\Рабочий стол> python .\collect_env.py
Collecting environment information...
PyTorch version: 2.0.0.dev20230203+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22623-SP0
Is CUDA available: False
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1050 Ti
Nvidia driver version: 528.33
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3400
DeviceID=CPU0
Family=107
L2CacheSize=3072
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3400
Name=AMD Ryzen 5 2600 Six-Core Processor
ProcessorType=3
Revision=2050

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230203+cu118
[pip3] torchaudio==2.0.0.dev20230204+cu118
[pip3] torchvision==0.15.0.dev20230204+cu118
[conda] Could not collect
```

cc @ezyang @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel

**Comment by malfet** [comment]
GTX 1050 is Pascal, so it should be supported.
@bropines can you please run `python -c "import torch;print(torch._C._cuda_getDeviceCount(), torch.cuda._raw_device_count_nvml())"` and post results here?

**Comment by bropines** [comment]
```
Microsoft Windows [Version 10.0.22623.1037]
(c) Microsoft Corporation. All rights reserved.

C:\Users\bropi>python -c "import torch;print(torch._C._cuda_getDeviceCount(), torch.cuda._raw_device_count_nvml())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bropi\AppData\Roaming\Python\Python39\site-packages\torch\cuda\__init__.py", line 494, in _raw_device_count_nvml
    nvml_h = CDLL("libnvidia-ml.so.1")
  File "C:\Program Files\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'libnvidia-ml.so.1' (or one of its dependencies). Try using the full path with constructor syntax.

C:\Users\bropi>
```

> GTX 1050 is Pascal, so it should be supported. @bropines can you please run `python -c "import torch;print(torch._C._cuda_getDeviceCount(), torch.cuda._raw_device_count_nvml())"` and post results here?

**Comment by malfet** [comment]
And what if you run just the first part of the command, i.e. "python -c "import torch;print(torch._C._cuda_getDeviceCount()"

**Comment by bropines** [comment]
> And what if you run just the first part of the command, i.e. `python -c "import torch;print(torch._C._cuda_getDeviceCount())"`

```Microsoft Windows [Version 10.0.22623.1037]
(c) Microsoft Corporation. All rights reserved.

C:\Users\bropi>python -c "import torch;print(torch._C._cuda_getDeviceCount())"
0

C:\Users\bropi>
```

**Comment by ngimel** [comment]
cc @ptrblck, any known problems for v 528 driver + pytorch compiled with 11.8?

**Comment by bropines** [comment]
Is this my mistake, or did nvidia break something?

**Comment by ptrblck** [comment]
I'm not aware of any 528 driver issues and have recently helped another user running into a driver install issue where installing the 528.33 WHQL driver fixed it. This was on an A100 node, so not the same setup.

@malfet Do you know which tests use Pascal GPUs on Windows in CircleCI?

**Comment by malfet** [comment]
@ptrblck CircleCI is long gone, so we don't have any CI for sm_60 at the moment. But I should have 1070 at home (which is also Pascal, if I'm not mistaken). Let me give it a try a bit later today.

**Comment by bropines** [comment]
I upgraded to version 528.49. Nothing has changed.)

**Comment by bropines** [comment]
> @bropines Do you still have issues with installing PyTorch?

During this time, I changed my computer, but there was no such bug on it. We can close this issue
