### ISSUE TITLE
What type of attributes does symbolic function support?

### ISSUE THREAD

**Issue by 1049451037** [pytorch/pytorch#94292]
### 📚 The doc issue

I read the doc of [symbolic](https://pytorch.org/docs/stable/onnx.html#static-symbolic-method) but no related introduction.

I read the source code and get supported [suffix](https://github.com/pytorch/pytorch/blob/master/torch/onnx/_patch_torch.py#L15), but I still don't know what types each letter represents.

### Suggest a potential alternative/fix

By the way, I want to ask whether symbolic support boolean attributes and integer array attributes?

**Comment by titaiwangms** [comment]
Hi @1049451037 
A comprehensive tutorial can be found here: https://pytorch.org/tutorials/beginner/onnx/intro_onnx.html
