### ISSUE TITLE
The sample code of document incorrectly wraps the function decorator

### ISSUE THREAD

**Issue by DoubleVII** [pytorch/pytorch#94305]
### 📚 The doc issue

I'm reading the [Extending PyTorch](https://pytorch.org/docs/stable/notes/extending.html) of Developer Notes. In the section of [Extending torch](https://pytorch.org/docs/stable/notes/extending.html#extending-torch), there is an example code that confuses me, i.e.,
```python
import functools
def implements(torch_function):
    """Register a torch function override for ScalarTensor"""
    @functools.wraps(torch_function)
    def decorator(func):
        HANDLED_FUNCTIONS[torch_function] = func
        return func
    return decorator
```
This define a decorator that add the implementation to the `HANDLED_FUNCTIONS` dispatch table dictionary. The code `@functools.wraps(torch_function)` seems to update the information of `torch_function` to the decorator, which doesn't make sense to me. I think the right thing to do here is to update the `func` based on `torch_function`,  or am I missing something?

### Suggest a potential alternative/fix

I give my implementation below.
```python
import functools
def implements(torch_function):
    """Register a torch function override for ScalarTensor"""
    def decorator(func):
        functools.update_wrapper(func, torch_function)
        HANDLED_FUNCTIONS[torch_function] = func
        return func
    return decorator
```

cc @svekars @carljparker

**Comment by soulitzer** [comment]
Good catch, we'd accept a PR to fix this.
