### ISSUE TITLE
Calling `nested_tensor.transpose(-1, -2)` causes autograd error

### ISSUE THREAD

**Issue by JeremyDouglas91** [pytorch/pytorch#94303]
### 🐛 Describe the bug

When calling `loss.backward()` after passing a nested tensor `x` through a self-attention module, I get the error `RuntimeError: Expected nested_tensor_impl_is_contiguous(nt_grad_output) to be true, but got false.`.

After investigating, I found this was caused by transposing the key tensor, as in `k.transpose(-1, -2)`, where `k` is also a nested tensor produced by passing `x` through a linear layer.

The only way to make it work is to "unbind" `k`, transpose each tensor in the batch individually, and then package them up again with `torch.nested.as_nested_tensor()`

Here is the code required to reproduce the bug:

```
class MiniAttention(torch.nn.Module):
    def __init__(self, E):
        super(MiniAttention, self).__init__()
        self.k_proj = nn.Linear(E, E)
        self.q_proj = nn.Linear(E, E)
        self.v_proj = nn.Linear(E, E)
    
    def forward(self, x):
        B, E = x.size(0), x.size(2)
        k, q, v, = self.k_proj(x), self.q_proj(x), self.v_proj(x)
        # kT = torch.nested.as_nested_tensor([y.transpose(-1, -2) for y in k.unbind(0)]) # works
        kT = k.transpose(-1, -2) # does not work
        attn_weights =  q @ kT
        attn_output = attn_weights @ v
        attn_output = torch.nested.to_padded_tensor(attn_output, padding=0.).mean(dim=1) # mean pooling
        return attn_output

L, E = (1, 2), 3
x = torch.nested.nested_tensor([
    torch.rand(L[0], E), 
    torch.rand(L[1], E)
])

model = MiniAttention(E)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
output = model(x)
loss = (0. - output).pow(2).sum()
loss.backward() # RuntimeError: Expected nested_tensor_impl_is_contiguous(nt_grad_output) to be true, but got false.

print(model.k_proj.weight.grad) # None
print(model.k_proj.bias.grad) # None
```

### Versions

PyTorch version: 2.0.0.dev20230206
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 (main, Oct 13 2022, 16:12:30)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230206
[pip3] torchaudio==2.0.0.dev20230206
[pip3] torchvision==0.15.0.dev20230206
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpy-base                1.23.5           py39h9cd3388_0  
[conda] torch                     2.0.0.dev20230206          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230206          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230206          pypi_0    pypi

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by drisspg** [comment]
Thanks for reporting this! I was able to reproduce and the fix is this PR: https://github.com/pytorch/pytorch/pull/94317.

**Comment by JeremyDouglas91** [comment]
@drisspg thank you so much - really appreciated!
