### ISSUE TITLE
Bicubic interpolation does not follow opencv result

### ISSUE THREAD

**Issue by VasLem** [pytorch/pytorch#94335]
### 🐛 Describe the bug

This issue is meant to revive a [past one](https://github.com/pytorch/pytorch/issues/19650#issue-436451822). Specifically, running in Pytorch 1.13.0, the example code
```
import cv2
import torch
import torch.nn.functional as F

SIZE_HW = (247, 111)
SIZE_WH = (111, 247)

t = torch.rand(1, 17, 64, 64)


pt_result = F.interpolate(t, size=SIZE_HW, mode="bicubic", align_corners=True)
cv_result = torch.from_numpy(cv2.resize(t.squeeze(0).permute(1, 2, 0).numpy(), SIZE_WH, interpolation=cv2.INTER_CUBIC)).permute(2, 0, 1).unsqueeze(0)


print("max abs diff:", (pt_result - cv_result).abs().max())
print("max rel diff:", ((1 - pt_result) / cv_result).abs().max())
print("MSE:", ((pt_result - cv_result) ** 2).mean())
```
 returns:
```
max abs diff: tensor(0.4889)
max rel diff: tensor(79371.5156)
MSE: 
tensor(0.0096)
```
Are you able to reproduce this issue? And if so, is it possible to add the above code into tests?

I noticed that the issue occurs mainly when the output shape is increased, so when the interpolation takes place. When the shape is reduced, the results are similar.
### Versions

PyTorch version: 1.13.0+cpu     
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A 

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:43:00) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=1805
DeviceID=CPU0
Family=198
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1805
Name=11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torch-tb-profiler==0.4.0
[pip3] torchvision==0.14.0
[pip3] opencv==4.6.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py38h2bbff1b_0
[conda] mkl_fft                   1.3.1            py38h277e83a_0
[conda] mkl_random                1.2.2            py38hf11a4ad_0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] numpy-base                1.23.5           py38h4da318b_0
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @saketh-are

**Comment by jbschlosser** [comment]
@VasLem `align_corners=False` is needed to make the interpolation match that of OpenCV (see comment [here](https://github.com/pytorch/vision/issues/1708#issuecomment-570294308)).

Running your code with `align_corners=False` shows negligible differences:
```
max abs diff: tensor(7.0035e-06)
max rel diff: tensor(114374.8203)
MSE: tensor(8.7183e-13)
```

Closing as expected behavior, but please feel free to reopen if you think there is still an issue within PyTorch.

**Comment by VasLem** [comment]
The previous result appears to work only for float images between 0 and 1, trying to test it on uint8 input, I receive a large error margin, non analogous to the increase in values, meaning that ithe correspondence does not scale well when increasing the maximum value of the image. Trying the following:
```
import cv2
import torch
import torch.nn.functional as F

SIZE_HW = (247, 111)
SIZE_WH = (111, 247)

t = torch.randint(0,255, (1, 17, 64, 64)).to(torch.uint8)

pt_result = torch.clamp(F.interpolate(t.float(), size=SIZE_HW, mode="bicubic", align_corners=False), 0, 255).to(torch.uint8)
cv_result = torch.from_numpy(cv2.resize(t.squeeze(0).permute(1, 2, 0).numpy(), SIZE_WH, interpolation=cv2.INTER_CUBIC)).permute(2, 0, 1).unsqueeze(0)



print("max abs diff:", (pt_result.float() - cv_result.float()).abs().max())
print("MSE:", ((pt_result.float() - cv_result.float()) ** 2).mean())

t = t/255.0

pt_result = torch.clamp(F.interpolate(t.float(), size=SIZE_HW, mode="bicubic", align_corners=False), 0, 1)
cv_result = torch.from_numpy(cv2.resize(t.squeeze(0).permute(1, 2, 0).numpy(), SIZE_WH, interpolation=cv2.INTER_CUBIC)).permute(2, 0, 1).unsqueeze(0)

print("max abs diff:", (pt_result.float() - cv_result.float()).abs().max())
print("MSE:", ((pt_result.float() - cv_result.float()) ** 2).mean())
```

I get:
```
max abs diff: tensor(1.)
MSE: tensor(0.4874)

max abs diff: tensor(0.2159)
MSE: tensor(5.4718e-05)
```

Is this still an expected behavior?

**Comment by VasLem** [comment]
Bump.
