### ISSUE TITLE
Perform release candidate perf smoke test

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#94334]

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/benchmark/actions/runs/4139464599/jobs/7157056338

**Comment by weiwangmeta** [comment]
Benchmark;pytorch-1.13.1-cuda-11.7;pytorch-v2.0.0.dev20230208-cuda-11.7
mnist-cpu_memory;3385.77;3501.79
mnist-gpu_memory;0.0;0.0
mnist-latency;19.00;21.72
mnist_hogwild-cpu_memory;348.445;400.715
mnist_hogwild-gpu_memory;0.0;0.0
mnist_hogwild-latency;514.10;541.70
wlm_cpu_lstm-cpu_memory;836.621;831.086
wlm_cpu_lstm-gpu_memory;0.0;0.0
wlm_cpu_lstm-latency;6846.87;5295.49
wlm_cpu_trans-cpu_memory;882.785;902.965
wlm_cpu_trans-gpu_memory;0.0;0.0
wlm_cpu_trans-latency;5993.27;5492.76
wlm_gpu_lstm-cpu_memory;2974.24;3074.69
wlm_gpu_lstm-gpu_memory;0.0;0.0
wlm_gpu_lstm-latency;194.05;188.58
wlm_gpu_trans-cpu_memory;2510.96;2612.88
wlm_gpu_trans-gpu_memory;0.0;0.0
wlm_gpu_trans-latency;214.36;223.19

latency wise, looks good. But why gpu memory is all 0?

**Comment by weiwangmeta** [comment]
A100 runner issue. Ran on T4 instead, GPU memory was fine. Job link: https://github.com/pytorch/benchmark/actions/runs/4359236586/jobs/7620786448
