### ISSUE TITLE
torch.autograd.grad doesn't work on BatchNorm2d when using torch_directml

### ISSUE THREAD

**Issue by casonwight** [pytorch/pytorch#94359]
### 🐛 Describe the bug

I am trying to implement a wgan in pytorch using the torch_directml library (to use my non-cuda local gpu). For the wgan, I have to calculate a gradient penalty, which needs the torch.autograd.grad function. When I use BatchNorm2d in the discriminator, I get an error. I want to eventually use InstanceNorm2d instead, but that is also having problems with torch_directml (see [my relevant open ticket](https://github.com/pytorch/pytorch/issues/94271)).

Here is the minimum reproducible example I could create. If I change the device to 'cpu' or I remove BatchNorm2d from the Sequential model, the code works. 
```python
import torch
from torch import nn
import torch_directml

gpu_device = torch_directml.device() # When set to 'cpu', code works

x_in = torch.rand(10, 3, 64, 64, requires_grad=True).to(gpu_device)
model = nn.Sequential(nn.Conv2d(3, 16, 3), nn.BatchNorm2d(16)).to(gpu_device) # Without BatchNorm, code works
y_out = model(x_in)

gradient = torch.autograd.grad(
    inputs=x_in,
    outputs=y_out,
    retain_graph=True,
    create_graph=True,
    grad_outputs=torch.ones_like(y_out)                       
)[0]

gp = ((gradient.norm(2, dim=1) - 1) ** 2).mean()
gp.backward()
```

Error
```
Traceback (most recent call last):
  File "C:\Users\cason\repos\cats-GAN\src\dml_problem.py", line 20, in <module>
    gp.backward()
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "C:\Users\cason\anaconda3\envs\cats_gan_env\lib\site-packages\torch\autograd\__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: 'devices' argument must be DML
```

Thanks!

### Versions

Versions
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3501
DeviceID=CPU0
Family=205
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3501
Name=Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
ProcessorType=3
Revision=24067

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==1.13.1
[pip3] torch-directml==0.1.13.1.dev230119
[pip3] torchvision==0.14.1
[conda] blas 1.0 mkl
[conda] cpuonly 2.0 0 pytorch
[conda] mkl 2022.1.0 h858461b_193
[conda] numpy 1.24.1 pypi_0 pypi
[conda] pytorch 1.13.1 py3.9_cpu_0 pytorch
[conda] pytorch-mutex 1.0 cpu pytorch
[conda] torch-directml 0.1.13.1.dev230119 pypi_0 pypi
[conda] torchvision 0.14.1 pypi_0 pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ZailiWang** [comment]
@jgong5

**Comment by iremyux** [comment]
Hi @casonwight ,
Similar to #94271, it seems like the right place to report this issue is DirectML instead of Pytorch.
Can you please open a new issue in [DirectML repo](https://github.com/microsoft/DirectML)?
