### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED, when F.conv2d is called

### ISSUE THREAD

**Issue by hmura** [pytorch/pytorch#94383]
### 🐛 Describe the bug

Hello, I am new to pytorch.
I checked the error message with the same title, but could not figure out how to handle it, so I am sending you the python file I ran the test on (attached test.py.txt) and the error message (attached error_message.txt).
I would appreciate your comments or advice.

[test.py.txt](https://github.com/pytorch/pytorch/files/10683273/test.py.txt)

[error_message.txt](https://github.com/pytorch/pytorch/files/10683276/error_message.txt)

### Versions

[torch_utils_collect_env_20230208.txt](https://github.com/pytorch/pytorch/files/10683254/torch_utils_collect_env_20230208.txt)
[nvcc-version_report.txt](https://github.com/pytorch/pytorch/files/10683255/nvcc-version_report.txt)
[nvidia-smi_report.txt](https://github.com/pytorch/pytorch/files/10683257/nvidia-smi_report.txt)
I have attached the information about the execution environment.

cc @csarofeen @ptrblck @xwang233 @ngimel

**Comment by ptrblck** [comment]
It seems you are using PyTorch `1.4.0` with CUDA 10.1. Could you update PyTorch to the latest release and check if you would still run into this issue, please?

**Comment by hmura** [comment]
Thank you very much for your comment.

I am using cuda 10.1 and I think the following version mentioned on pytorch's Official site is the most recent version, but is the latest version OK?

https://pytorch.org/get-started/previous-versions/
v.1.7.1
# CUDA 10.1
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by ngimel** [comment]
cuda 10.1 is no longer supported.

**Comment by hmura** [comment]
I would  consider changing the CUDA version.
Thank you very much for your comment.
