### ISSUE TITLE
jacfwd and jacrev should *always* return a matrix, even if it's a [1,2] or a [1,1] or a [2,1] matrix

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#94398]
### 🐛 Describe the bug

The Jacobian is the matrix representation of a linear operator (the differential) of a function. As such, we should always return a matrix.

If we do this, we can test for identities like `jacfwd(f)(x) == jacrev(f)(x).mT` and others. 

Current behaviour:
```python
>>> def f(a): return (a[0]**2 + a[1]**2).sqrt()
>>> jacfwd(f)(torch.tensor([0.5000, 1.7000]))
tensor([0.2822, 0.9594])
>>> jacrev(f)(torch.tensor([0.5000, 1.7000]))
tensor([0.2822, 0.9594])
```

### Versions

master

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by zou3519** [comment]
A lot of the things we do are for consistency with jax. jax's APIs also do not return a matrix in this case.
![image](https://user-images.githubusercontent.com/5652049/223847473-c65da423-64dc-479b-9bf8-f401fe19cb58.png)

**Comment by lezcano** [comment]
my my... Let's leave it as it is then
