### ISSUE TITLE
Suggestion: About issue reporting format

### ISSUE THREAD

**Issue by Leedehai** [pytorch/pytorch#944]
I hope there is a universal format to report issues (like PyTorch version, python version, operating system version, CUDA version, steps to reproduce, etc.) like in TensorFlow or VSCode's GitHub repo:
https://github.com/tensorflow/tensorflow/issues/new
https://github.com/Microsoft/vscode/issues/new

**Comment by apaszke** [comment]
No we don't have anything like that and I don't think it's necessary at this point. If we need any additional info about system configuration we'll just ask. No need to require additional effort form the issue author's if it's unnecessary.
