### ISSUE TITLE
[Dispatch/`toPyObject`]: `Stream` arguments are not handled

### ISSUE THREAD

**Issue by danthe3rd** [pytorch/pytorch#94403]
### 🐛 Describe the bug

Minimal repro code:

```python
import torch
from torch.utils._python_dispatch import TorchDispatchMode, _pop_mode_temporarily
import torch._dispatch.python
from functools import partial

class DummyDispatcher(TorchDispatchMode):
    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        return func(*args, **kwargs)

x = torch.zeros([10, 10], device="cuda")
x.record_stream(torch.cuda.Stream())
with DummyDispatcher():
    # Boom
    x.record_stream(torch.cuda.Stream())

```

Result:
```
Traceback (most recent call last):
  File "/scratch/stream_toPyObject.py", line 44, in <module>
    x.record_stream(torch.cuda.Stream())
RuntimeError: Missing cases in 'toPyObject'! Can't convert Stream to a Python object
```

### Versions

PyTorch version: 2.0.0.dev20230208+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-1025-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230208+cu117
[pip3] torchaudio==2.0.0.dev20230208+cu117
[pip3] torchvision==0.15.0.dev20230208+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230208+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230208+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230208+cu117          pypi_0    pypi

cc @Chillee @ezyang @zou3519 @albanD @samdow @fmassa @artkorenev

**Comment by danthe3rd** [comment]
NOTE: I'm using this as a workaround at the moment:

```python
class TorchFuncMockNoDispatch:
    """
    Wraps a method to call it without the custom
    pytorch dispatcher
    """
    def __init__(self, pt_impl):
        self.pt_impl = pt_impl
    def __get__(self, obj, c):
        return partial(self, obj)
    def __call__(self, obj, *args, **kwargs):
        with _pop_mode_temporarily():
            return self.pt_impl(obj, *args, **kwargs)

class DispatcherWithoutBrokenFuncs(TorchDispatchMode):
    TENSOR_FUNCS_NO_DISPATCH = [
        # Can't convert Stream argument to Python object
        'record_stream'
    ]
    def __enter__(self) -> None:
        self._pt_impls = {}
        for k in self.TENSOR_FUNCS_NO_DISPATCH:
            impl = getattr(torch.Tensor, k)
            self._pt_impls[k] = impl
            setattr(torch.Tensor, k, TorchFuncMockNoDispatch(impl))
        return super().__enter__()
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        for k in self.TENSOR_FUNCS_NO_DISPATCH:
            setattr(torch.Tensor, k, self._pt_impls[k])
        return super().__exit__(exc_type, exc_val, exc_tb)
```

**Comment by albanD** [comment]
Thanks for the report!

We should add support for converting Stream objects in https://github.com/pytorch/pytorch/blob/fe0e28ab87ddda38a82efe74dd3eaf05e926f117/torch/csrc/jit/python/pybind_utils.cpp#L670 indeed.
Would you be able to send a PR adding that with your example as a test?
