### ISSUE TITLE
log_prob returns positive values for small cov

### ISSUE THREAD

**Issue by Dorozhko-Anton** [pytorch/pytorch#9442]
## Issue description

Log prob returns positive value for small covariance matrix.
Is it a bug or I did something wrong ?

## Code example
```

mu = torch.Tensor([-0.4855,  6.7255,  2.6253,  1.1761,  1.5928])
cov = torch.Tensor(
       [[ 5.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  5.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  5.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  5.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  5.0000]]) * 0.001

x = torch.Tensor([-0.6090,  6.8870,  2.6622,  1.2581,  1.6615])

p = torch.distributions.MultivariateNormal(loc=mu,
                                          covariance_matrix=cov)

print(p.log_prob(x)) // tensor(3.2371)
```

## System Info

[environment collection script]
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 860M
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] numpydoc (0.6.0)
[pip3] torch (0.4.0)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.2.1)
[conda] faiss-cpu                 1.2.1            py36_cuda0.0_2    pytorch
[conda] pytorch                   0.4.0            py36hd73e86b_0  
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

**Comment by vishwakftw** [comment]
The values of the `pdf` can be arbitrarily large but never negative. This is completely acceptable, and I am sure this is not a bug.

Simple example: normal distribution with standard deviation = 0.000001 and mean = 0. The `pdf` at `x = 0` is `1000 / (2 * pi)`, and the natural log of this is clearly greater than 0.

**Comment by Dorozhko-Anton** [comment]
Sorry, you are right. That's log of density

**Comment by cucrui** [comment]
> The values of the `pdf` can be arbitrarily large but never negative. This is completely acceptable, and I am sure this is not a bug.
> 
> Simple example: normal distribution with standard deviation = 0.000001 and mean = 0. The `pdf` at `x = 0` is `1000 / (2 * pi)`, and the natural log of this is clearly greater than 0.

When the optimization object is to minimize -log(density), will -log(density) being less than 0 affect the learning of the model?
