### ISSUE TITLE
CUDA 8.7+PTX isn't in the list of supported arches

### ISSUE THREAD

**Issue by manbehindthemadness** [pytorch/pytorch#94438]
### 🐛 Describe the bug

This error on build:
File "/opt/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1793, in _get_cuda_arch_flags
    raise ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
ValueError: Unknown CUDA arch (8.7+PTX) or GPU not supported

This arch works just fine with both pytorch and torchvision; it's just being named different on later model jetsons.

### Versions

HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       3
Vendor ID:                       ARM
Model:                           1
Model name:                      ARMv8 Processor rev 1 (v8l)
Stepping:                        r0p1
CPU max MHz:                     2201.6001
CPU min MHz:                     115.2000
BogoMIPS:                        62.50
L1d cache:                       768 KiB
L1i cache:                       768 KiB
L2 cache:                        3 MiB
L3 cache:                        6 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-pfn-extras==0.6.3
[pip3] pytorch3d==0.7.2
[pip3] torch==1.13.0a0+git49444c3
[pip3] torch-tensorrt==1.4.0.dev0+5fa63743
[pip3] torch2trt==0.4.0
[pip3] torchvision==0.13.1a0+bddbd7e

cc @ngimel @ptrblck @puririshi98

**Comment by ptrblck** [comment]
CC @eqy I thought we have added sm_87, but it seems we have only fixed some issues here: https://github.com/pytorch/pytorch/pull/88644?

**Comment by eqy** [comment]
Opened #95008 for this

**Comment by manbehindthemadness** [comment]
Ah, then just mark it as a duplicate, thanks for looking into it.

**Comment by pmeier** [comment]
Closed in #95008.
