### ISSUE TITLE
RuntimeError: The size of tensor a  must match the size of tensor b  at non-singleton dimension 0 pytorch

### ISSUE THREAD

**Issue by praveenkumarchandaliya** [pytorch/pytorch#9446]
def forward(self, input, hidden):
        hx, cx = hidden
        **gates = self.conv_ih(input) + self.conv_hh(hx)**

RuntimeError: The size of tensor a (32) must match the size of tensor b (18) at non-singleton dimension 0
i am using pytorch 0.3.1 version

**Comment by praveenkumarchandaliya** [comment]
i am using pytorch 0.3.1 version

**Comment by SsnL** [comment]
You used some op that expects two inputs to have same size, but they don't. This is not a bug in the framework, but in your code.

**Comment by praveenkumarchandaliya** [comment]
Same code running of 8581 image but when i have added any image then give this error

**Comment by ctivanovich** [comment]
I have this issue as well, but all of my images are square (600, 600, 3 color channels). I use `transforms.Resize(224, Image.BICUBIC)` when this error occurs. More specifically, `RuntimeError: The size of tensor a (224) must match the size of tensor b (3) at non-singleton dimension 3
`. It doesn't seem to be an issue of dimensionality on my end though, Image can display my images without trouble.

**Comment by ctivanovich** [comment]
Never mind, the error had nothing to do with Resize (I write this for anyone who encounters the same issue), it just seems that way because it's talking about dimensions. I was passing mean/std parameters to Normalize after the Resize step as an array rather than in a tuple: e.g. (m1, m2, m3).

**Comment by bhavika** [comment]
Another possible source of the issue could be that your C dimension from the tensor must appear first. For example, if you get a tensor (600, 600, 3) - the shape for your transform may need to be (3, 600, 600). 

You can achieve this using - 

`image = image.view(3, 600,600)`

Now pass this image to your transform. Hope this helps!

**Comment by tehreemnaqvi** [comment]
Hi, I also got this error. How to fix this?

**RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 3**

**Comment by vickykhan89** [comment]
Hello all, good day!
I have two tensor a[100,8] and b[100,8], I need to change the shape/dimensions values in b[100,8] to b[8,100]. How can i do this need a piece of code. will be very thankful.

**Comment by slayeren** [comment]
To change a tensors shape, you need to transpose it using torch.transpose(your_tensor, 0, 1), which will transpose it on the 0 and first dimension.

**Comment by Akbarkhan87** [comment]
Error; 
The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 3

I want to change the network of vgg16 into vgg19 this type of error occurred, when I just train the model. Any one can help me in this regard

**Comment by Akbarkhan87** [comment]
**Model.py** 
What can i add and need your kind help to solve this issue as mentioned in the previous comment @bhavika 
Error;
**The size of tensor a (32) must match the size of tensor b (128) at non-singleton dimension 3**

import torch.nn as nn
import torch
from torchvision import models
from utils import save_net,load_net

class CSRNet(nn.Module):
    def __init__(self, load_weights=False):
        super(CSRNet, self).__init__()
        self.seen = 0
        self.frontend_feat = [64, 64, 'M', 128, 128, 'M', 256, 256, 256, 'M', 512, 512, 512, 'M', 512, 512, 512, 'M']
        self.backend_feat  = [512, 512, 512,256,128,64]
        self.frontend = make_layers(self.frontend_feat)
        self.backend = make_layers(self.backend_feat,in_channels = 512,dilation = True)
        self.output_layer = nn.Conv2d(64, 1, kernel_size=1)
        if not load_weights:
            mod = models.vgg16(pretrained = True)
            self._initialize_weights()
            for i in range(len(self.frontend.state_dict().items())):
                list(self.frontend.state_dict().items())[i][1].data[:] = list(mod.state_dict().items())[i][1].data[:]
    def forward(self,x):
        x = self.frontend(x)
        x = self.backend(x)
        x = self.output_layer(x)
        return x
    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, std=0.01)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            
                
def make_layers(cfg, in_channels = 3,batch_norm=False,dilation = False):
    if dilation:
        d_rate = 2
    else:
        d_rate = 1
    layers = []
    for v in cfg:
        if v == 'M':
            layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
        else:
            conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=d_rate,dilation = d_rate)
            if batch_norm:
                layers += [conv2d, nn.BatchNorm2d(v), nn.ReLU(inplace=True)]
            else:
                layers += [conv2d, nn.ReLU(inplace=True)]
            in_channels = v
    return nn.Sequential(*layers)

**Comment by eosayamen** [comment]
I have an error trying to use a github python script. Is there a way anyone can help me? I was trying to use a script that allows you to make an obj model from a photograph. Here is the link: GitHub - shunsukesaito/PIFu: This repository contains the code for the paper "PIFu: Pixel-Aligned Implicit Function for High-Resolution Clothed Human Digitization". I was able to install it using google collab. It worked with the original image, but when I changed the sample image I started seeing the error. I am not sure what the error means. The error states: The size of tensor a (245) must match the size of tensor b (244) at non-singleton dimension 2. Do you know if it means I need to resize my image? I think the error has something to do with the new image I added. Here is my link:
https://colab.research.google.com/drive/1-tAYm2kd5yNxGWZ-ooexSvd12V6f3ZQo?usp=sharing
