### ISSUE TITLE
Does pytorch have a mechanism to disable cublas

### ISSUE THREAD

**Issue by weiyu-Liu** [pytorch/pytorch#94466]
### 🚀 The feature, motivation and pitch

Hello, 
For some reasons, does pytorch have a mechanism to disable cublas ?
If so, how to do it. 
if not, I think I need to modify the source code, which part of the code do I need to modify so that pytorch will not call cublas functions ?
Thanks !

**Comment by H-Huang** [comment]
You can set the `CUDA_BLAS_PROVIDER` from cublas to another provider via

```
export CUDA_BLAS_PROVIDER=<xyz>
```

or in python
```
import os
os.environ['CUDA_BLAS_PROVIDER'] = <xyz>
```
