### ISSUE TITLE
`torch.cuda.utilization()` does not work when `CUDA_VISIBLE_DEVICES` is set

### ISSUE THREAD

**Issue by jnordberg** [pytorch/pytorch#94472]
### 🐛 Describe the bug

When monitoring from a different process torch.cuda.utilization() returns zero unless `CUDA_VISIBLE_DEVICES` unset or set to `0`.

To reproduce:

monitor.py
```py
import torch
import time

while True:
    print(torch.cuda.utilization())
    time.sleep(1)
```

work.py
```py
import torch

while True:
    t = torch.ones(10000, 10000).cuda()
    t = t * t
```

Results:

```
$ export CUDA_VISIBLE_DEVICES=0; python monitor.py & python work.py & sleep 10; kill %1 %2
0
9
17
12
14
18
17
16
14
```

```
$ export CUDA_VISIBLE_DEVICES=1; python monitor.py & python work.py & sleep 10; kill %1 %2
0
0
0
0
0
0
0
0
0
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          124
On-line CPU(s) list:             0-123
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       124
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7542 32-Core Processor
Stepping:                        0
CPU MHz:                         2899.998
BogoMIPS:                        5799.99
Virtualization:                  AMD-V
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       7.8 MiB
L1i cache:                       7.8 MiB
L2 cache:                        62 MiB
L3 cache:                        2 GiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-123
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT disabled
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat npt nrip_save umip rdpid arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] rotary-embedding-torch==0.1.5
[pip3] torch==1.13.1+cu117
[pip3] torchaudio==0.13.1+cu117
[pip3] torchvision==0.14.1+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] rotary-embedding-torch    0.1.5                    pypi_0    pypi
[conda] torch                     1.13.1+cu117             pypi_0    pypi
[conda] torchaudio                0.13.1+cu117             pypi_0    pypi
[conda] torchvision               0.14.1+cu117             pypi_0    pypi

cc @ngimel

**Comment by gchanan** [comment]
CUDA_VISIBLE_DEVICES is not a binary on/off, you are not letting the two processes see the same device.

**Comment by jnordberg** [comment]
> CUDA_VISIBLE_DEVICES is not a binary on/off, you are not letting the two processes see the same device.

In the example above first both scripts see device 0, then device 1, no?

**Comment by ngimel** [comment]
@jnordberg correct, `utilization()` uses nvml and thus ignores the order set by CUDA_VISIBLE_DEVICES, we should fix this. Would you like to submit a fix? The functions are in torch/cuda/__init__.py, look at `utilization()` (it calls into pynvml) and `_parse_visible_devices` to get a mapping between nvml devices and devices that pytorch sees.

**Comment by jnordberg** [comment]
@ngimel Sure! I'll give it a shot
