### ISSUE TITLE
Embed more kdb files for MIOpen performance databases in pytorch wheels

### ISSUE THREAD

**Issue by rhighs** [pytorch/pytorch#94482]
### 🚀 The feature, motivation and pitch

Recently I've started using pytorch on my machine running an AMD GPU. Everything looks just fine until I start training models on some data and I get this annoying warning about MIOpen's performance databases:

`MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_16.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package`

### Alternatives

What stated [here](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1606) might be a solution, as guys from MIOpen said pytorch wheels are self contained and this is not a problem you can solve by just getting a kdb file in your filesystem (people get this same warning anyways).

### Additional context

As far as I can see this isn't really a big deal, in fact training runs fast enough either way. Not having ever put hands on pytorch myself, I wonder how could we go about this?

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by jithunnair-amd** [comment]
https://github.com/pytorch/builder/pull/1407 and other follow-up PRs for ROCm5.5 nightly wheels will allow users to use MIOpen kdb files with the PyTorch wheels. However, **please note** that it won't be embedding these kdb files into the wheels, but will instead build MIOpen in a manner that allows users to install kdb files and use them with the PyTorch wheels. The instructions on how to do that are here right now: https://github.com/ROCmSoftwarePlatform/pytorch/wiki/Using-MIOpen-kdb-files-with-ROCm-PyTorch-wheels.

We will update this issue when ROCm5.5 nightly wheels are available.

**Comment by jithunnair-amd** [comment]
Should be enabled by wheels in https://download.pytorch.org/whl/nightly/rocm5.5/ and later
