### ISSUE TITLE
[Feature Request] enable C++ frontend support on Windows

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#9450]
at a minimum, this will require removing the setting of NO_API in tools/build_pytorch_libs.bat as discussed here: https://github.com/pytorch/pytorch/pull/8792#discussion_r202519792

**Comment by SsnL** [comment]
cc @goldsborough

**Comment by peterjc123** [comment]
Looks like it's solved by https://github.com/pytorch/pytorch/pull/11716.
