### ISSUE TITLE
Support min/max ops for int64 on MPS

### ISSUE THREAD

**Issue by mmisiewicz** [pytorch/pytorch#94515]
### 🚀 The feature, motivation and pitch

Many HuggingFace generative models can't be run on MPS today due to:

```
RuntimeError: MPS does not support min/max ops with int64 input
```

Tested on today's nightly.

Previous issues #78848 and #80784 discuss this matter. 

Some discussion [here](https://github.com/pytorch/pytorch/issues/80784#issuecomment-1203336336) discusses a hack that would break abstraction of PyTorch. 

Getting this working would allow usage of these huggingface models on MPS. 

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Actually, I think solution can be to change default int dtype for mps tensors to be int32

**Comment by mukulpatnaik** [comment]
@malfet @mmisiewicz I was able to get the flan-t5 transformer model running on MPS by making sure `relative_position` in in the function `[_relative_position_bucket](https://github.com/huggingface/transformers/blob/5096a654b7743bb0d36e3a2c21d67dc39a4b36a3/src/transformers/models/t5/modeling_t5.py#L374)` the file `modeling_t5.py` was always `int32`. Like so:

`relative_position = relative_position.to(torch.int32)`

and change `relative_position_if_large` from `torch.long` to `torch.int32` on [line 413](https://github.com/huggingface/transformers/blob/5096a654b7743bb0d36e3a2c21d67dc39a4b36a3/src/transformers/models/t5/modeling_t5.py#L413)

**Comment by mukulpatnaik** [comment]
@malfet would this be the solution you mentioned above? - 

> "I think solution can be to change default int dtype for mps tensors to be int32".

 How could I expand this change such that any HuggingFace model can be run on the MPS backend without running into the errors described in issues [#78848](https://github.com/pytorch/pytorch/issues/78848) and [#80784](https://github.com/pytorch/pytorch/issues/80784)? Would appreciate any help, thanks :)

**Comment by DenisVieriu97** [comment]
@mukulpatnaik min/max ops (and bunch of other ops) are supporting natively int64 in macOS 13.3 (see https://github.com/pytorch/pytorch/pull/95817).

**Comment by kulinseth** [comment]
@mmisiewicz , can you please verify on MacOS 13.3 with latest nightly, if this indeed solves the issue you are seeing ?

**Comment by ahoho** [comment]
@kulinseth I think this gets solved on 13.3; my previous pytorch install throws an error on the `relative_position` line in `modeling_t5.py` (mentioned above) when using a T5-based model, but pytorch-nightly runs fine.

**Comment by kulinseth** [comment]
Thanks @ahoho for confirming. @mmisiewicz please re-open if the issue still exists

**Comment by mmisiewicz** [comment]
@kulinseth Thank you very much for the followup! As soon as 13.3 leaves beta (hopefully in the next few weeks!) I'll give it a shot. 

I did confirm the model also runs on 13.2 with MPS acceleration, albeit with and expected INT32/INT64 downcast warning. 

When 13.3 is out of beta I'll give it a shot and file new issue(s) if anything goes awry (not expected).

**Comment by ccodykid** [comment]
I'm on 13.3 and pytorch 2.0.0 and still get the warning `MPS: no support for int64 min/max ops, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1271.)`

**Comment by DenisVieriu97** [comment]
@ccodykid could you please try latest nightly version of torch? There was an issue with the OS version check in 2.0.

**Comment by melton1968** [comment]
Using macOS 13.4.1 (c) and PyTorch 2.0.1, I still get the warning about `MPS` not supporting min/max ops for`int64`.  

I got the `3b_v2` [openllama](https://github.com/openlm-research/open_llama) model to run successfully by changing line 736 of the `modeling_llama.py` file in the HuggingFace transformers package from,
```
 position_ids = attention_mask.long().cumsum(-1) - 1
```
to,
```
 position_ids = attention_mask.int().cumsum(-1) - 1
```

If `MPS` supported `int64` reduce operations, it would allow more models to run out of the box.

**Comment by melton1968** [comment]
Yes, I tried the nightly build, and indeed everything ran smoothly with no warnings or errors.

There was a behavior change, though. With PyTorch 2.0.1, the model defaulted to `mps` while the tokenizer defaulted to `cpu`.  I had to manually call `input_ids.to("mps)" when passing the `ids` to `model.generate`. With the nightly build, however, both the tokenizer and model default to the `cpu`. Using `to("mps")` gets everything to run on the `gpu`.

**Comment by ioma8** [comment]
> > If `MPS` supported `int64` reduce operations, it would allow more models to run out of the box.
> 
> Hi @melton1968 - reduce ops with int64 support in MPS are supported in nightly builds of torch (pip3 install --pre torch --force-reinstall --index-url https://download.pytorch.org/whl/nightly/cpu)

Can confirm, the nightly build fixes it.

**Comment by PlugNPush** [comment]
Does anybody knows when this will be pushed to actual releases?
