### ISSUE TITLE
dist.init_process_group() doesn't work in multiple gpu training

### ISSUE THREAD

**Issue by jacksonly** [pytorch/pytorch#9453]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I want to training LeNet on two GPU cards, but I have always got error ("proc_group_name != group_name") when I ran my code. I only modified dist.init_process_group() in https://github.com/seba-1511/dist_tuto.pth/blob/gh-pages/train_dist.py.

## Code example

def mpi_get_rank():
    if 'OMPI_COMM_WORLD_RANK' in os.environ:
        return int(os.environ['OMPI_COMM_WORLD_RANK'])
    else:
        return None

def mpi_get_world_size():
    if 'OMPI_COMM_WORLD_SIZE' in os.environ:
        return int(os.environ['OMPI_COMM_WORLD_SIZE'])
    else:
        return None

def init_processes(rank, size, fn, backend='gloo'):
    if mpi_get_rank() != None:
        time.sleep(mpi_get_rank())
    else:
        time.sleep(random.randint(0, 4 * size))
    """ Initialize the distributed environment. """
    print('*'*10)
    print('Before Initialize:')
    print('*'*10)
    dist.init_process_group(backend=backend, init_method="file:///hdfs/pnrsy/v-yalu2/shared/{}".format('shared_file_common'), world_size=size)
    print('*'*10)
    print('Finished Initialization!!!')
    print('*'*10)
    fn(rank, size)

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: Linux Ubuntu 16.04
- PyTorch version: 0.3.1
- Python version: 3.6.1
- CUDA/cuDNN version: 9.0
- GPU models and configuration: Tesla P100
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by jacksonly** [comment]
RuntimeError: proc_group_name != group_name at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THD/process_group/General.cpp:17

**Comment by ailzhang** [comment]
Hi @jacksonly , would you minding sending a minimal complete script for the repro? Thanks!

**Comment by jacksonly** [comment]
Okay, this is my complete script. 
#!/usr/bin/env python

import os
import torch
import torch.distributed as dist
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import time
import random
from math import ceil
from random import Random
from torch.multiprocessing import Process
from torch.autograd import Variable
from torchvision import datasets, transforms


class Partition(object):
    """ Dataset-like object, but only access a subset of it. """

    def __init__(self, data, index):
        self.data = data
        self.index = index

    def __len__(self):
        return len(self.index)

    def __getitem__(self, index):
        data_idx = self.index[index]
        return self.data[data_idx]


class DataPartitioner(object):
    """ Partitions a dataset into different chuncks. """

    def __init__(self, data, sizes=[0.7, 0.2, 0.1], seed=1234):
        self.data = data
        self.partitions = []
        rng = Random()
        rng.seed(seed)
        data_len = len(data)
        indexes = [x for x in range(0, data_len)]
        rng.shuffle(indexes)

        for frac in sizes:
            part_len = int(frac * data_len)
            self.partitions.append(indexes[0:part_len])
            indexes = indexes[part_len:]

    def use(self, partition):
        return Partition(self.data, self.partitions[partition])


class Net(nn.Module):
    """ Network architecture. """

    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x)


def partition_dataset():
    """ Partitioning MNIST """
    dataset = datasets.MNIST(
        r'./data',
        transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307, ), (0.3081, ))
        ]))
    size = dist.get_world_size()
    bsz = 128 / float(size)
    partition_sizes = [1.0 / size for _ in range(size)]
    partition = DataPartitioner(dataset, partition_sizes)
    partition = partition.use(dist.get_rank())
    train_set = torch.utils.data.DataLoader(
        partition, batch_size=bsz, shuffle=True)
    return train_set, bsz


def average_gradients(model):
    """ Gradient averaging. """
    size = float(dist.get_world_size())
    for param in model.parameters():
        dist.all_reduce(param.grad.data, op=dist.reduce_op.SUM, group=0)
        param.grad.data /= size


def run(rank, size):
    """ Distributed Synchronous SGD Example """
    torch.manual_seed(1234)
    train_set, bsz = partition_dataset()
    model = Net()
#    model = model
    model = model.cuda(rank)
    optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.5)

    num_batches = ceil(len(train_set.dataset) / float(bsz))
    for epoch in range(10):
        epoch_loss = 0.0
        for data, target in train_set:
#            data, target = Variable(data), Variable(target)
            data, target = Variable(data.cuda(rank)), Variable(target.cuda(rank))
            optimizer.zero_grad()
            output = model(data)
            loss = F.nll_loss(output, target)
            epoch_loss += loss.data[0]
            loss.backward()
            average_gradients(model)
            optimizer.step()
        print('Rank ',
              dist.get_rank(), ', epoch ', epoch, ': ',
              epoch_loss / num_batches)

def mpi_get_rank():
    if 'OMPI_COMM_WORLD_RANK' in os.environ:
        return int(os.environ['OMPI_COMM_WORLD_RANK'])
    else:
        return None

def mpi_get_world_size():
    if 'OMPI_COMM_WORLD_SIZE' in os.environ:
        return int(os.environ['OMPI_COMM_WORLD_SIZE'])
    else:
        return None

def init_processes(rank, size, fn, backend='gloo'):
    if mpi_get_rank() != None:
        time.sleep(mpi_get_rank())
    else:
        time.sleep(random.randint(0, 4 * size))
    """ Initialize the distributed environment. """
    print('*'*10)
    print('Before Initialize:')
    print('*'*10)
    dist.init_process_group(backend=backend, init_method="file:///xxx/shared/{}".format('shared_file_common'), world_size=size)
    print('*'*10)
    print('Finished Initialization!!!')
    print('*'*10)
    fn(rank, size)


if __name__ == "__main__":
    size = 2
    processes = []
    for rank in range(size):
        p = Process(target=init_processes, args=(rank, size, run))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()

**Comment by jacksonly** [comment]
I always got this Runtime error: 
Torch.distributed.init_process_group: RuntimeError: proc_group_name != group_name

**Comment by ailzhang** [comment]
@jacksonly If I understand correctly, you are initializing with Gloo backend instead of MPI.

`def init_processes(rank, size, fn, backend='gloo'):`
`p = Process(target=init_processes, args=(rank, size, run))`

**Comment by jacksonly** [comment]
yeah, I want to use Gloo as backend.

**Comment by ailzhang** [comment]
@jacksonly , I can run your script without any issue though. Could you switch to master branch and try again?

```
 λ ~ python 9453.py
**********
Before Initialize:
**********
**********
Before Initialize:
**********
**********
Finished Initialization!!!
**********
**********
Finished Initialization!!!
**********
9453.py:71: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
9453.py:118: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  epoch_loss += loss.data[0]
9453.py:71: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.log_softmax(x)
9453.py:118: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  epoch_loss += loss.data[0]
Rank  1 , epoch  0 :  tensor(1.3128, device='cuda:1')
Rank  0 , epoch  0 :  tensor(1.3204, device='cuda:0')
Rank  0 , epoch  1 :  tensor(0.5571, device='cuda:0')
Rank  1 , epoch  1 :  tensor(0.5456, device='cuda:1')
Rank  0 , epoch  2 :  tensor(0.4210, device='cuda:0')
Rank  1 , epoch  2 :  tensor(0.4190, device='cuda:1')
Rank  0 , epoch  3 :  tensor(0.3641, device='cuda:0')
Rank  1 , epoch  3 :  tensor(0.3587, device='cuda:1')
Rank  0 , epoch  4 :  tensor(0.3235, device='cuda:0')
Rank  1 , epoch  4 :  tensor(0.3176, device='cuda:1')
Rank  1 , epoch  5 :  tensor(0.2900, device='cuda:1')
Rank  0 , epoch  5 :  tensor(0.2980, device='cuda:0')
Rank  0 , epoch  6 :  tensor(0.2781, device='cuda:0')
Rank  1 , epoch  6 :  tensor(0.2674, device='cuda:1')
Rank  0 , epoch  7 :  tensor(0.2545, device='cuda:0')
Rank  1 , epoch  7 :  tensor(0.2498, device='cuda:1')
Rank  0 , epoch  8 :  tensor(0.2438, device='cuda:0')
Rank  1 , epoch  8 :  tensor(0.2418, device='cuda:1')
```

**Comment by ailzhang** [comment]
Closing, please reopen if you still see the problem.
