### ISSUE TITLE
ROCm jobs fail to access AMD apt repo

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#94555]
## Current Status
Mitigated

## Error looks like
`Failed to fetch http://repo.radeon.com/rocm/apt/5.4.2/pool/main/r/rocm-llvm/rocm-llvm_15.0.0.22506.50402-104~20.04_amd64.deb  Connection failed [IP: 13.82.220.49 80]`

## Incident timeline (all times pacific)

* Oncall notices the issue
* Contact AMD, they are aware of the issue and internal teams are on it

## User impact
ROCm build jobs fail

## Root cause
Upstream network issue

## Mitigation
* Temporarily mitigated by moving ROCm job to unstable https://github.com/pytorch/pytorch/pull/94550

## Prevention/followups
TBD

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by huydhn** [comment]
If you need ROCm jobs on your PRs, please add `cilfow/unstable` to run

**Comment by pruthvistony** [comment]
@huydhn ,
Checking with our internal devops team regarding connection issues with repo.radeon.

**Comment by weiwangmeta** [comment]
@pruthvistony  Any updates? Thx!

**Comment by pruthvistony** [comment]
Our IT team has fixed the issue.
See builds are passing - https://github.com/pytorch/pytorch/actions/runs/4147502282/jobs/7174454762.
will wait for few more builds and move ROCm out of unstable.

**Comment by weiwangmeta** [comment]
> Our IT team has fixed the issue. See builds are passing - https://github.com/pytorch/pytorch/actions/runs/4147502282/jobs/7174454762. will wait for few more builds and move ROCm out of unstable.
> 
> cc @weiwangmeta

Thank you @pruthvistony  for the wonderful Friday update! Have a nice weekend~

**Comment by weiwangmeta** [comment]
https://github.com/pytorch/pytorch/actions/runs/4147739987/jobs/7174969657 is observed to be working

**Comment by weiwangmeta** [comment]
How about this failure? https://github.com/pytorch/pytorch/actions/runs/4147502282/jobs/7175391632

**Comment by pruthvistony** [comment]
Not sure why the docker pull is failing, since no change done on that part.

Have raised a PR to revert - https://github.com/pytorch/pytorch/pull/94550
https://github.com/pytorch/pytorch/pull/94631

Will wait for successful CI run.

**Comment by huydhn** [comment]
Close this now as this has been resolved
