### ISSUE TITLE
flake8 version reporting in collect_env

### ISSUE THREAD

**Issue by mpearce25** [pytorch/pytorch#94571]
### 🚀 The feature, motivation and pitch

# Feature
Add flake8 version reporting to https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py
This should be a one line change in `def get_pip_packages(run_lambda):`
```
                for name in {
                    "torch",
                    "numpy",
                    "mypy",
                    "flake8", # add this
                }
```

# Motivation
Flake8 is an important Pytorch and torchvision development dependency but does not get reported in collect_env unlike other packages such as mypy. This hinders troubleshooting differences between contributors environments as demonstrated by https://github.com/pytorch/vision/issues/7200 

### Additional context

I'm happy to make the PR if this is useful

**Comment by malfet** [comment]
Sounds good to me, please do not hesitate to propose a PR
