### ISSUE TITLE
error when using torch.compile

### ISSUE THREAD

**Issue by mactavish91** [pytorch/pytorch#94585]
### 🐛 Describe the bug

This code can run normally on the gpu without using compile, but adding compile will cause the following error:
```
import torch
import torchvision.models as models
model = models.resnet18().cuda()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
compiled_model = torch.compile(model)
x = torch.randn(16, 3, 224, 224).cuda()
optimizer.zero_grad()
out = compiled_model(x)
out.sum().backward()
optimizer.step()
```

### Error logs

/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/torch/_inductor/compile_fx.py:89: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
//usrusr//binbin/ld: /cannotld :find  cannot- lcudafind
 -lcuda
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
/collect2: error: ld returned 1 exit status
usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lcuda
collect2: error: ld returned 1 exit status
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 548, in _worker_compile
    kernel.precompile(warm_cache_only_with_cc=cc)
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 67, in precompile
    self.launchers = [
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 68, in <listcomp>
    self._precompile_config(c, warm_cache_only_with_cc)
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/torch/_inductor/triton_ops/autotune.py", line 81, in _precompile_config
    triton.compile(
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/triton/compiler.py", line 1239, in compile
    so = _build(fn.__name__, src_path, tmpdir)
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/site-packages/triton/compiler.py", line 1169, in _build
    ret = subprocess.check_call(cc_cmd)
  File "/mnt/data2/wwh/anaconda3/envs/wwh/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/gcc', '/tmp/tmpg5k_52zd/main.c', '-O3', '-I/usr/local/cuda/include', '-I/mnt/data2/wwh/anaconda3/envs/wwh/include/python3.8', '-I/tmp/tmpg5k_52zd', '-shared', '-fPIC', '-lcuda', '-o', '/tmp/tmpg5k_52zd/triton_.cpython-38-x86_64-linux-gnu.so']' returned non-zero exit status 1.
"""

### Versions

PyTorch version: 2.0.0.dev20230210+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-51-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 57 bits virtual
CPU(s):                          124
On-line CPU(s) list:             0-123
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       124
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           134
Model name:                      Intel Xeon Processor (Icelake)
Stepping:                        0
CPU MHz:                         2593.894
BogoMIPS:                        5187.78
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       3.9 MiB
L1i cache:                       3.9 MiB
L2 cache:                        496 MiB
L3 cache:                        2 GiB
NUMA node0 CPU(s):               0-123
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb fsgsbase bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230210+cu117
[pip3] torchaudio==2.0.0.dev20230209+cu117
[pip3] torchmetrics==0.11.1
[pip3] torchvision==0.15.0.dev20230209+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-lightning         1.9.0                    pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230210+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230209+cu117          pypi_0    pypi
[conda] torchmetrics              0.11.1                   pypi_0    pypi
[conda] torchvision               0.15.0.dev20230209+cu117          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
Kind of looks like the CUDA install is borked

**Comment by zjjott** [comment]
find cannot- lcuda
you can run `ldconfig -p|grep cuda` output, check if libcuda exists,and which version it is

**Comment by yifanpu001** [comment]
I would like to show how I solve this problem.
1. run ```ldconfig -p|grep libcuda```, then i find something like this
![image](https://user-images.githubusercontent.com/59505338/226829841-dcc21aef-39e8-4a01-8a9a-81908dec723b.png)
2. create a soft link 
```ln -s /usr/lib/x86_64-linux-gnu/libcuda.so.1 /usr/bin/libcuda.so```
then the above error ```/usr/bin/ld: cannot find -lcuda``` is solved.

**Comment by zjjott** [comment]
@yifanpu001 actually you can should add cuda.conf in  /etc/ld.conf.d/ , include content like
```
/usr/local/cuda/lib
```
then ld can search this path

**Comment by SomeoneSerge** [comment]
I think this is a duplicate of https://github.com/pytorch/pytorch/issues/92745, having to do with https://github.com/openai/triton/blob/bd5c2117f62c73a9e922d5e93353a39ab3ac269b/python/triton/compiler.py#L1389

**Comment by Chillee** [comment]
Seems like this issue has been resolved. Closing for now.
