### ISSUE TITLE
Lots of different `nn.Sequence` instances trigger the Dynamo cache limits

### ISSUE THREAD

**Issue by achicu** [pytorch/pytorch#94609]
### 🐛 Describe the bug

I am optimizing the training of an internal model. The entire forward call becomes 3x slower when enabling pytorch inductor. I've been profiling it a bit and turns out the lookup for the `check_fn` calls takes between 5ms and 10ms for each "Sequential.forward" call.

Turns out we have a lot of nn.Sequential instances in our model. All these container instances contain modules that are very different from each other. However, they all share the same "Sequence.forward" method that gets optimized by dynamo. This means, dynamo will try to optimize the method for each particular instance of the Sequential class and push those optimizations into the same cache list.

When it executes one `Sequential.forward` instance, it will have to iterate through all the cached `check_fn` functions by calling them one by one. There's an optimization in the `eval_frame.c:lookup` method that remembers the last `check_fn` that validated and optimizes for that particular call by moving it to the top of the list. 

However, chances are that same Sequential will not actually execute until the next training iteration, which means it will have to search through all other `check_fns` again for the next Sequential call.

To make matters worse, the check_fn has a lot of `Sequential[index]` calls, that sometimes look deep inside without caching the `Sequential[index]` values. That means, the check_fn ends up calling a lot of the `sequential.__getitem__`. Now if we analyze that method, it is not particularly cheap as the Sequential stores its list of modules in the "_modules" dict structure, so it has to iterate through all `dict.values()` to get the requested one.

### Error logs

Performance is 3x slower when inductor is enabled.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-1023-aws-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-80GB
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.0
[pip3] open-clip-torch==2.11.1
[pip3] pytorch-lightning==1.9.0
[pip3] rotary-embedding-torch==0.1.5
[pip3] torch==2.0.0
[pip3] torchdata==0.5.1
[pip3] torchdistx==0.3.0.dev0+cu118
[pip3] torchmetrics==0.11.1
[pip3] torchvision==0.15.0a0+2d6e663
[conda] Could not collect
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @gchanan @Xia-Weiwen @ipiszy @soumith @ngimel @mlazos @yanboliang @desertfire

**Comment by achicu** [comment]
I will try to reduce this to a simple example over the weekend.

**Comment by ezyang** [comment]
Your diagnosis looks pretty spot on. A workaround would be to wrap each Sequential call in a distinct function, so that we get separate frames for each. But it seems to me like we should store frames on a per object basis when methods are involved.

**Comment by achicu** [comment]
Not all methods are like that though. I believe Containers like structures have this particular edgy behavior. Maybe a flag on the forward method could be used to trigger a slightly different cache lookup behavior. We could use that to mark the Sequential.forward method.

I am looking for a solution for the wrapping. If I just wrap it, wouldn't it end up having the same f_code anyway? I am looking to "clone" the function somehow and have a subclass of Sequential that does that on __init__.

**Comment by yanboliang** [comment]
I think the similar issue has been discussed at https://github.com/pytorch/pytorch/issues/93774.

**Comment by voznesenskym** [comment]
Good find. This has to do with how we construct guards (the source for where check_fn comes from) for when we unroll a sequential:

```
NNModuleSource(GetItemSource(self.source, idx))
```

There is a soundness / speed tradeoff here - we could replace sequential unrolling with just storing and guarding on the entire sequential (id only), or a little more fine grain (id, length, and id of elements?) - and not build a source for every element in the sequential.

**Comment by achicu** [comment]
This is what I've used to workaround the issue.

```python
def clone_function(f: types.FunctionType):
    c = f.__code__
    new_code = types.CodeType(
        c.co_argcount, c.co_posonlyargcount, c.co_kwonlyargcount, c.co_nlocals,
        c.co_stacksize, c.co_flags, c.co_code, c.co_consts, c.co_names, c.co_varnames,
        c.co_filename, c.co_name, c.co_firstlineno, c.co_lnotab, c.co_freevars, c.co_cellvars)
    return types.FunctionType(new_code, f.__globals__, f.__name__, 
        argdefs = f.__defaults__,  closure = f.__closure__)

class CustomSequential(nn.Sequential):
    def __init__(self, *args):
        super().__init__(*args)
        self.forward = types.MethodType(clone_function(self.forward), self)
```

I've used this workaround in other cases where this was needed in my model, so could be useful to add this is as a generic decorator for the methods. 

Note that the performance is still not optimal in my particular case due to the amount of guard checks on a particular method that I have in my model. This method uses a couple of modules stored in a nested `nn.ModuleList`. A single `check_fn` takes around 80% of the time the function that it is guarding takes. Looking at the checks, there's a lot of `self.module_list[NUMBER].property`. I believe that storing the value of the `self.module_list[NUMBER]` on the stack would help avoid calling the `__getitem__` of the ModuleList. I should be able to workaround it though, so maybe not a giant issue.

Also, the initial version of this method I am trying to optimize was requesting a slice of the `ModuleList` using `self.module_list[:-1]` and that was generating an entire new class during the forward call. That seems like bad practice in general, but something that maybe dynamo should detect and warn about.

**Comment by ezyang** [comment]
@ysiraichi your CSE on guards would help here too

**Comment by ezyang** [comment]
We also ran into this on one of our internal models. In this case, there was a layer which was instantiated many times, but because each layer was individually wrapped with FSDP we had to compile each separately. There were enough layers that this hit cache limits.

**Comment by ezyang** [comment]
@awgu also tells me that LLaMa-65B has 64 transformer blocks/layers, each wrapped with FSDP

**Comment by williamwen42** [comment]
Is this still an issue? cc @anijain2305 we previously talked about improving the dynamo cache.

**Comment by ezyang** [comment]
This was fixed by @anijain2305's work

**Comment by williamwen42** [comment]
This should be an updated workaround for creating new code objects that is independent of Python version:

```python
def clone_code(code):
    # copy hack since deepcopy doesn't actually give a new code object
    return code.replace()
```
