### ISSUE TITLE
MacOS M1 CPU/MPS tests are backlogged due to HW availability

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#94607]
## Current Status
*ongoing*

## Error looks like
Long queue times for M1 runners, which results in longer than usual merges/timeouts

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2453524/218155131-48628732-6574-4081-b56b-a3a5a2e40979.png">

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
Looks like we only have 16 runners for the entire org.

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment]
As a mitigation I propose to move M1 testing to periodic

**Comment by weiwangmeta** [comment]
I see an area where we can improve in the meanwhile: the domain libraries workflow (e.g. https://github.com/pytorch/audio/actions/workflows/build-wheels-m1.yml) are contributing to the increase of the load. We need to implement cancel in progress jobs, e.g. I do not see a need to run #1043 job if #1044 with the same PR is waiting. I will try to add concurrency cancelling (correctly) today.

**Comment by jeanschmidt** [comment]
The incident looks related to the instances being kicked out to AWS, I am investigating

**Comment by jeanschmidt** [comment]
New instances of mac runners are now deployed, and live, I few of them are a bit stubborn, but I believe most are back.

**Comment by malfet** [comment]
There are number of idle runners, reverting the change, let's see what will happen

**Comment by malfet** [comment]
No queueing right now

**Comment by ZainRizvi** [comment]
Follow up: RelEng is focusing on the queuing problem
