### ISSUE TITLE
torch.compile doesn't seem to work with DataParallel

### ISSUE THREAD

**Issue by y-zheng18** [pytorch/pytorch#94636]
### 🐛 Describe the bug

Codes look like this:
```
model_opt = torch.nn.DataParallel(model, device_ids=device_ids)
model_opt = torch.compile(model_opt)
...
```
When using single GPU, i.e., device_ids=[0] will lead to a 1.5 faster training, but for multi-gpu it falls back to the non-compile speed. Am I missing something or are there more things to pay attention to for using DataParallel on multi-gpu machines? It seems DataParallel is not mentioned in the [documentation](https://pytorch.org/docs/master/dynamo/index.html), only DDP and FSDP.

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230209+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-65-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No devices found.
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          40
On-line CPU(s) list:             0-39
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           62
Model name:                      Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
Stepping:                        4
CPU MHz:                         1200.596
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4400.38
Virtualization:                  VT-x
L1d cache:                       640 KiB
L1i cache:                       640 KiB
L2 cache:                        5 MiB
L3 cache:                        50 MiB
NUMA node0 CPU(s):               0-9,20-29
NUMA node1 CPU(s):               10-19,30-39
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230209+cu117
[pip3] torchaudio==2.0.0.dev20230209+cu117
[pip3] torchvision==0.15.0.dev20230209+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230209+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230209+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230209+cu117          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by wconstab** [comment]
Actually, I don't know how DataParallel works, and we didn't do anything to make sure it works with torch.compile.  I only verified DDP works.  (DDP being DistributedDataParallel, which is generally the most popular/recommended api for data parallel).  Just curious- do you prefer DataParallel instead of DDP for some reason?

**Comment by y-zheng18** [comment]
oh I use DataParallel since it's easier to incorporate that in some existing codebases (without additional efforts to modify logging / printing / etc.) And I think Dataparallel might work with similar efficiency compared to DDP in my case. Also, I found some interesting comments [here](https://github.com/pytorch/pytorch/pull/91779#issuecomment-1375564928). Maybe it could be a good feature to have DataParallel working with torch.compile?

**Comment by ngimel** [comment]
No new features will be added to DataParallel, it's in maintenance mode #65936. Wrappers make launching distributed jobs really easy, give them a try.
