### ISSUE TITLE
run pytorch using GPU on windows

### ISSUE THREAD

**Issue by mhusseinsh** [pytorch/pytorch#9464]
Hello,
I am using windows 10 and I have pytorch installed and I have a GPU
when running a pytorch script, it uses by default the CPU, not the GPU, and accordingly, I have `cuda runtime error: out of memory
`
How can I force the script to uses GPU not the CPU ?

In lunix platform, I usually write `CUDA_VISIBLE_DEVICES=x` but that is not possible on windows

any idea ?

If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by peterjc123** [comment]
Why is that not possible on Windows? The environment settings process is only a bit different.
```powershell
set CUDA_VISIBLE_DEVICES=x
```

**Comment by soumith** [comment]
if you have questions please use https://discuss.pytorch.org , not github issues.
