### ISSUE TITLE
Unable to load float value with torch.load(weights_only=True)

### ISSUE THREAD

**Issue by nagadomi** [pytorch/pytorch#94670]
### 🐛 Describe the bug

```python
import torch

# OK
data = {"a": 1, "b": "str"}
torch.save(data, "data.pth")
torch.load("data.pth", weights_only=True)
print("PASS 1")

# Error
data = {"a": 1, "b": "str", "c": 1e-6}
torch.save(data, "data.pth")
torch.load("data.pth", weights_only=True)
print("PASS 2")
```
output
```
PASS 1
Traceback (most recent call last):
  File "weights_only/bug.py", line 10, in <module>
    torch.load("data.pth", weights_only=True)
  File ".venv/lib/python3.10/site-packages/torch/serialization.py", line 788, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 71
```

### Versions

PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3070 Ti
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian

(Deleted for security reasons)

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] perlin-numpy==0.0.0
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @mruberry

**Comment by albanD** [comment]
cc @malfet

**Comment by malfet** [comment]
Thank you very much for reporting. This should not be the case, looking into it.
