### ISSUE TITLE
☂️ Tests disabled after Triton update

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#94687]
After updating Triton to https://github.com/openai/triton/commit/3fa8a5a864c48a490625648387a86be3eb7c2c06 following tests start to fail

- `test_empty_meta` + `test_format_scalar_meta` from `test_torch.py`, see https://github.com/pytorch/pytorch/actions/runs/4152596189/jobs/7183804405
- `test_comprehensive_byte_cuda_float16` + `test_comprehensive_byte_cuda_float32` from `test_torchinductor_opinfo.py`, see https://github.com/pytorch/pytorch/actions/runs/4152595273/jobs/7183800623

Accuracy failure:
 - timm_vision_transformer

Performance regressions:
 - hf_Bert increases perf [by 1.175x](https://github.com/pytorch/pytorch/actions/runs/4160130336/jobs/7197026851#step:11:1545), compared to [previous 1.19x ](https://github.com/pytorch/pytorch/pull/94249#discussion_r1104007945)
### Versions

CI

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ngimel** [comment]
`timm_vision_transformer` and `byte` tests are fixed

**Comment by ngimel** [comment]
We do `skipIfDynamo` on `empty_meta` tests, I don't think they are high pri to fix.

**Comment by malfet** [comment]
I guess issue can be closed at this point
