### ISSUE TITLE
thpp Tensor templatized over Device (and maybe Density, e.g sparse vs dense)

### ISSUE THREAD

**Issue by an-kumar** [pytorch/pytorch#947]
Right now, THPP exposes four templatized classes:

`THTensor<T>, THCTensor<T>, THCSTensor<T>, and THSTensor<T>.`

I propose to consolidate these into a single class, like so:
```
TorchTensor<Type,Device,Density> (or at least, <Type,Device>).
```
We can then do the following:
```
template <typename T>
using THTensor = TorchTensor<T,CPU,Dense>

template <typename T>
using THCTensor = TorchTensor<T,GPU,Dense>
```
and so on.

In this fashion, nothing about the current API would change (and so all current code that uses THPP would all work the same), but users of THPP would be able to choose what level of templatization they want. If there are some current methods that are only in some subset of the classes, we can either do template class specialization, or simply make those methods part of all the classes.

I am interested in this because I am using THPP in a separate project, in which it would be cleaner to have the Tensor class to be templatized over at least the Device (in addition to the Type), as it is in most other frameworks (e.g MXNet).

I am happy to do this and submit a PR if the developers are interested, otherwise I will just make those changes locally.

**Comment by soumith** [comment]
I'm not sure merging over density makes sense, as the function signatures themselves might want to be different (we want to retain this flexibility)

**Comment by an-kumar** [comment]
fair enough -- I didn't really look at that, I'm only really interested in the Dense tensors anyways.

We can do something like:
```
TorchTensor<T,D>
and
TorchSparseTensor<T,D>
```

Or even just the `TorchTensor<T,D>`.

Would that be good with you guys?

**Comment by soumith** [comment]
will wait for @colesbury and @apaszke to respond, they are the heavy users of THPP.

**Comment by apaszke** [comment]
I think we could add that, but can you first tell me how would you like to implement that?

**Comment by an-kumar** [comment]
I would probably do it very similar to how it's done now.

Different files in generic/ for the different devices, the explicit template instantiation over <real,device> instead of just <real>. That would allow for the real differences in implementation between cuda and cpu, thought i would bet there's a way to reconcile it into one implementation w/ different macros, that just doesn't seem worth it though.

Then, unify the interface, the only thing different atm in the interface as far as I can tell is that THCTensor has a THCState* state whereas the THTensor doesn't. I think I would change that to void* state in both, anyways I think it would be good to give the cpu Tensor a void* state (or at least, maybe, change state to be a virtual function returning a void* which is NULL for THTensor), because the THNN functions now take a THNNState* anyways which as far as I can tell is just void*, and expected to be NULL. This would help unify the code that would bring THNN and THCUNN into c++ land as well (what I am working on involves this too).

**Comment by apaszke** [comment]
So you mean to remove `THTensor`, etc.? Wouldn't it be simpler to just implement some kind of a trait struct?
```cpp
template<typename real, thd::Device device, thd::Kind kind>
struct tensor_traits {};

template<>
struct tensor_traits<float, thd::Device::GPU, thd::Kind::Dense> {
    using tensor_type = THCTensor<float>;
}
```

In your code you could do this then:

```cpp
template <typename T>
using MyTensor = tensor_traits<T, thd::Device::CPU, thd::Kind::Dense>;
```

**Comment by an-kumar** [comment]
yeah, that's possible, and that's what I've done right now.

it's really just a convenience/cleanliness thing to me. pretty much everything is templatized over <T,D> when you are writing code in c++, and currently I have something like this everywhere:

template <typename T, typename D>
some_templatized_thing
{
using TTensor = TDTensorTraits<T,D>::TensorType;
}

and then I use TTensor as my type. It just feels a little weird/unclean in c++ world to me, because most things are templatized over <T,D>, it's odd that the fundamental class (Tensor) isn't.

but you're right it's not a functional difference

**Comment by soumith** [comment]
THPP is being/has been completely phased out in favor of the auto-generated library https://github.com/zdevito/aten which to an extent does what you want.
