### ISSUE TITLE
why the output shape can't be infered in the exported in the onnx graph when registering a custome operator by the Function class 

### ISSUE THREAD

**Issue by DaZhUUU** [pytorch/pytorch#94703]
### 🐛 Describe the bug

here's my code

```python
import torch
import torch.nn as nn
from torch.autograd import Function
import torch.onnx

#custom op onnx representation
class MyStrangeOp(Function):
   #for onnx node representation, symbolic function must be defined and specified static.
   @staticmethod
   def symbolic(g, input, weight, bias, floatAttr, intAttr):
      #because forward function return 2 outputs, so this func also have to return 2 outputs
      #this is my expriment result, I didn't find any docs, fuck it!
      return g.op("MyStrangeOp", input, weight, bias, float_attr_f=floatAttr, int_attr_i=intAttr), \
             g.op("MyStrangeOp", input, weight, bias, float_attr_f=floatAttr, int_attr_i=intAttr)

   @staticmethod
   def forward(ctx, input, weight, bias, floatAttr, intAttr):
      #this op return 2 outputs
      return input + weight, input * weight + bias

myStrangeOpForward = MyStrangeOp.apply

#layer
class MyStrangeOpLayer(nn.Module):
   def __init__(self, weight, bias, floatAttr, intAttr):
      super(MyStrangeOpLayer, self).__init__()
      self.weight = weight
      self.bias = bias
      self.floatAttr = floatAttr
      self.intAttr = intAttr

   def forward(self, x):
      return myStrangeOpForward(x, self.weight, self.bias, self.floatAttr, self.intAttr)

#model
class MyStrangeNet(nn.Module):
   def __init__(self):
      super(MyStrangeNet, self).__init__()
      self.myLayer1 = MyStrangeOpLayer(weight=nn.Parameter(torch.ones(1, 3, 4, 4)), bias=nn.Parameter(torch.ones(1, 3, 4, 4)), floatAttr=[0.1, 0.5], intAttr=[2, 2])
      self.myLayer2 = MyStrangeOpLayer(weight=nn.Parameter(torch.ones(1, 3, 4, 4)), bias=nn.Parameter(torch.ones(1, 3, 4, 4)), floatAttr=[0.5, 0.5], intAttr=[3, 3])
      self.conv1    = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, padding=1, stride=1, bias=True)
      self.conv2    = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, padding=1, stride=1, bias=True)
      self.conv3    = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, padding=1, stride=1, bias=True)
      self.conv4    = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3, padding=1, stride=1, bias=True)

   def forward(self, x):
      x1, x2 = self.myLayer1(x)
      x3, x4 = self.myLayer2(x)
      x1     = self.conv1(x1)
      x2     = self.conv1(x2)
      x3     = self.conv1(x3)
      x4     = self.conv1(x4)
      return x1 + x2 + x3 + x4



model = MyStrangeNet()
t = torch.ones(1, 3, 4, 4, dtype=torch.float32)
torch.onnx.export(model, (t,), 'fuckIt.onnx', opset_version=13, input_names=["inputTensor"], output_names=["outputTensor"],
                  operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
```

![mmexport1676215091925](https://user-images.githubusercontent.com/53418069/218320153-04d14488-8e07-4329-8cb9-7eeedc8cf222.png)
![mmexport1676215089819](https://user-images.githubusercontent.com/53418069/218320158-57077f3b-ab9f-488a-8fc5-c73975d4313f.png)

my onnx graph doesn't have output shape

### Versions

any version

**Comment by titaiwangms** [comment]
The ONNX shape inference does its best to inference on "ONNX official Ops", which you can find in https://github.com/onnx/onnx/tree/main/onnx/shape_inference. 
For those custom operators, ONNX has no clue of what it is, and what it does. So in torch.onnx document, we highly suggest users to provide those op shapes and types to the graph with setType API( [custom operator documentation](https://pytorch.org/docs/stable/onnx.html#custom-operators), [register](https://pytorch.org/docs/stable/onnx.html#torch.onnx.register_custom_op_symbolic), and [setType example](https://github.com/pytorch/pytorch/blob/a005dd1c01f965f9292b249e47c88b2b144e1d25/test/onnx/test_operators.py#L1189-L1215)).

More detail of usage from other users can be found in this thread: https://github.com/pytorch/pytorch/issues/81693

**Comment by DaZhUUU** [comment]
> The ONNX shape inference does its best to inference on "ONNX official Ops", which you can find in https://github.com/onnx/onnx/tree/main/onnx/shape_inference. For those custom operators, ONNX has no clue of what it is, and what it does. So in torch.onnx document, we highly suggest users to provide those op shapes and types to the graph with setType API( [custom operator documentation](https://pytorch.org/docs/stable/onnx.html#custom-operators), [register](https://pytorch.org/docs/stable/onnx.html#torch.onnx.register_custom_op_symbolic), and [setType example](https://github.com/pytorch/pytorch/blob/a005dd1c01f965f9292b249e47c88b2b144e1d25/test/onnx/test_operators.py#L1189-L1215)).
> 
> More detail of usage from other users can be found in this thread: #81693

But it still can't work

`def mycast_op(ctx, g, x, to):
    output = g.op("mycast", x, "to_i": to)
    return output.setType(x.type().with_dtype(torch.float32).with_sizes(_get_tensor_sizes(x)))

torch.onnx.register_custom_op_symbolic("myop::mycast", mycast_op, 11)

class mycast(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, to):
        return x.type(torch.float32)`

when I use mycast, it occurrs a error 
RuntimeError: ONNX export failed: Couldn't export Python operator mycast

How I solve the problem?

Thanks for answering!

**Comment by titaiwangms** [comment]
I suppose the op: `myop::mycast` wasn't in your aten graph? Is it? You should register on the op you would want to convert.

Most likely, it should be prim::PythonOp if torch doesn't recognize it.
```python
torch.onnx.register_custom_op_symbolic("prim::PythonOp", mycast_op, 11)
```

**Comment by DaZhUUU** [comment]
> 

It still occurrs the error

Maybe I use it by a wrong way?

```
def mycast_op(ctx, g, x, to):
    output = g.op("mycast", x, "to_i": to)
    return output.setType(x.type().with_dtype(torch.float32).with_sizes(_get_tensor_sizes(x)))

torch.onnx.register_custom_op_symbolic("prim::PythonOp", mycast_op, 11)

class mycast(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x, to):
        return x.type(torch.float32)

class cast(torch.nn.Module):
    def __init__(self):
        super(cast, self).__init__()
        self.castop = mycast.apply
    def foward(a):
        return self.castop(a, 1)
```

**Comment by titaiwangms** [comment]
I think you will find this file helpful: https://github.com/pytorch/pytorch/blob/master/test/onnx/test_custom_ops.py

**Comment by jasonlove521** [comment]
@DaZhUUU 
can you tell me whether you solve this problem

**Comment by lix19937** [comment]
Similar issue https://github.com/pytorch/pytorch/issues/125902
