### ISSUE TITLE
`nn.ReLU` and `nn.GELU` backward ops not implemented for `nested_tensor`

### ISSUE THREAD

**Issue by JeremyDouglas91** [pytorch/pytorch#94701]
### 🐛 Describe the bug

Calling `loss.backward()` after passing a `nested_tensor` through `nn.ReLu` or `nn.GELU` raises a `NotImplementedError`.

```python
import torch
import torch.nn as nn

L, E = (1, 2), 3
x = torch.nested.nested_tensor([
    torch.rand(L[0], E), 
    torch.rand(L[1], E)
])

linear = nn.Linear(E, E)
act = nn.GELU()

x = act(linear(x))
x = torch.nested.to_padded_tensor(x, padding=0.).mean()
loss = 0. - x
loss.backward() # NotImplementedError: Could not run 'aten::gelu_backward' with arguments from the 'NestedTensorCPU' backend.
```

### Versions

PyTorch version: 2.0.0.dev20230212
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 10:02:19)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230212
[pip3] torchaudio==2.0.0.dev20230212
[pip3] torchvision==0.15.0.dev20230212
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.23.5           py39he696674_0  
[conda] numpy-base                1.23.5           py39h9cd3388_0  
[conda] pytorch                   2.0.0.dev20230212         py3.9_0    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230212        py39_cpu    pytorch-nightly
[conda] torchvision               0.15.0.dev20230212        py39_cpu    pytorch-nightly

cc @cpuhrsch @jbschlosser @bhosmer @drisspg @mikaylagawarecki

**Comment by mikaylagawarecki** [comment]
Hi @JeremyDouglas91, thank you for the issue, we indeed do not have backward registrations for relu, gelu and layernorm yet but we can add these.

I see that you have filed a couple issues regarding nested tensor autograd support, would you be willing to share about your use case? :)

**Comment by JeremyDouglas91** [comment]
@mikaylagawarecki OK, I suspected as much but wasn't sure - if you could aff them, I would be most appreciative as it would allow me to proceed straightforwardly with my research, thank you!

I would be very happy to explain a little more about my work - I am doing my MSc at the University of Cape Town in partnership with [the RAIL lab ](https://www.raillab.org/) on attention in Deep Reinforcement Learning. 

The main idea is to extend the ideas in the Paper Deep [Recurrent Q Network](https://arxiv.org/pdf/1512.01693.pdf), the objective being to improve sample efficiency (the amount of information taken to learn to perform a task) by allowing and incentivizing (via reward shaping) the agent to mask incoming state information, and avoid performing computation on it altogether. 

We were inspired by the recent papers: 

- [Masked Auto Encoders Are Scalable Vision Learners ](https://arxiv.org/abs/2111.06377)(Facebook), where the authors are able to train a transformer-based VAE by exlcuding ("hard" masking) up to 75% of the patches in the input image.
- [The Sensory Neuron as a Transformer: Permutation-Invariant Neural Networks for Reinforcement Learning](https://arxiv.org/abs/2109.02869), where the authors show (i) it is possible to learn control tasks from scratch with a lightweight transformer-based policy network and (ii) it is possible for an agent to perform given only a subset of the patches of the input (state) image

We, therefore, decided to use a transformer-based policy (a lightweight version of the ViT architecture) because the mathematical structure of the self-attention mechanism allows for a varied number of embedding vectors along the sequence dimension, i.e. a different number of embedded patches in a vision-based control task like Pong. This gives the agent the ability to mask varied proportions of the observed state (i.e. a varied number of patch embeddings) from time step to time step. However, in order to make this work properly we need to use a `NestedTensor` - ordinary masking (using `-inf` before applying `softmax` doesn't work as well because it doesn't allow for skip connections and is far less computationally efficient). Our architecture is visualized below:
 
![Screenshot 2023-02-14 at 09 23 44](https://user-images.githubusercontent.com/22117288/218693437-c82a5fc0-7dab-4f4c-8fa3-9e45177f565e.png)

As I say, if you could help me with this by implementing the backward pass functionality for at least `GELU` and `LayerNorm` (those are the only things prohibiting me from proceeding as far as I know), I would be most appreciative.

**Comment by JeremyDouglas91** [comment]
Thank you so much for the support @drisspg and @mikaylagawarecki !!
