### ISSUE TITLE
Investigate queue disparity between `windows.4xlarge` and `linux.4xlarge`

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#94711]
### 🐛 Describe the bug

See graph below: in last 7 day there were rarely any queueing for `linux.4xlarge` instances, but `windows.4xlarge` seems hard to come by:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/2453524/218336344-46c3d0a1-9757-4670-a2d6-6244b2f5b291.png">

But according to https://github.com/pytorch/test-infra/blob/90ee2adb46a542babe3f8c016b06b135f211e6b8/.github/scale-config.yml they are allocated on a very similar resources: `c5.4xlarge` vs `c5d.4xlarge`. 
Two questions:
 - Can they be move to the same resources? (in case `c5d.4xlarge` are harder to come by)
 - Does our scaling algorithm prefers Linux to Windows?(as one can also observe by observing queueing times for `linux.g5.4xlarge.nvidia.gpu` vs `windows.g5.4xlarge.nvidia.gpu`)

cc @ezyang @gchanan @zou3519 @seemethere @pytorch/pytorch-dev-infra @jeanschmidt

**Comment by jeanschmidt** [comment]
According to https://www.apptio.com/blog/aws-ec2-c5-instances/ the only difference is the use of NVMe-based SSD, that I believe might have a insignificant difference in total build time, especially considering the total time due to the queue time

**Comment by seemethere** [comment]
It's also a difference in that `linux.4xlarge` is non-ephemeral and `windows.4xlarge` is ephemeral. That could explain the discrepancy.
