### ISSUE TITLE
Nightlies fail on a simple `torch.linalg.solve()` call with "undefined symbol: sgebak_"

### ISSUE THREAD

**Issue by xuzhao9** [pytorch/pytorch#94751]
### 🐛 Describe the bug

The latest pytorch nightly failed torchbench drq train cuda test:
https://github.com/pytorch/benchmark/actions/runs/4164233087/jobs/7205604182

PyTorch version:
```
$ python -c "import torch; print(torch.__version__)"
2.0.0.dev20230213+cu117
```

Minimal reproduction:
```
$ python -c "import torch;A = torch.randn(200,200).cuda(); B = torch.randn(200).cuda(); torch.linalg.solve(A, B)"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Error in dlopen: /home/ubuntu/miniconda3/envs/torchbench-v2-nightly-ci/lib/python3.8/site-packages/torch/lib/libtorch_cuda_linalg.so: undefined symbol: sgebak_
```

Can we add a unit test for this?

### Versions

Broken: 2.0.0.dev20230213+cu117

The previous nightly build (2.0.0.dev20230212+cu117) is good.

cc @ezyang @gchanan @zou3519 @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by seemethere** [comment]
Marking this as https://github.com/pytorch/pytorch/labels/high%20priority since we'll need to resolve this prior to the 2.0 release

**Comment by weiwangmeta** [comment]
Bad commit: 
(debug_linagl_regression) nm .../lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so  |grep sgebak
                 U sgebak_

Good commit: 
(debug_linagl_regression) nm .../lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so  |grep sgebak
00000000008797f0 T mkl_lapack__sgebak_
                 U mkl_lapack_sgebak
0000000000879ad0 T mkl_lapack__sgebak_64_
00000000008797f0 T sgebak
00000000008797f0 T sgebak_
0000000000879ad0 T sgebak_64
0000000000879ad0 T sgebak_64_

**Comment by malfet** [comment]
As @atalman pointed out in another thread, this is likely a cause of regression: https://github.com/pytorch/pytorch/pull/94402 

Doing a revert and testing whether it will fix it in https://github.com/pytorch/pytorch/pull/94762

**Comment by xuzhao9** [comment]
@malfet Can we add a unit test for this?

**Comment by atalman** [comment]
@malfet I guess we can use output of this job to validate: https://github.com/pytorch/pytorch/actions/runs/4157496803

**Comment by weiwangmeta** [comment]
Tried to use some of the binaries, but encountered many issues like either: 1) libmpi.so cannot open 2) libmkl_intel_xx.so cannot open. 
The discrepancy between nightly builds and CI binary makes bi-sect not as straightforward as it seems. Unless we try to build from source, which I'm trying now.

**Comment by huydhn** [comment]
One small question:  I'm trying to understand why this failure shows up as flaky on HUD https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=binary.  I kind of expect it to fails consistency, but that doesn't seem to be the case.  That doesn't sound right, but may be I miss something

**Comment by malfet** [comment]
Sorry, I should have posted it earlier, I've added regression testing in https://github.com/pytorch/builder/commit/56177bebc95b8739687fc4500d340a2001e479f4 , which would affect binary builds until revert is landed. If you re-run previous manywheel test on trunk, you should see consistent failures since offending  PR was merged until it got reverted.

**Comment by xuzhao9** [comment]
I confirm that this problem has been fixed: https://github.com/pytorch/benchmark/actions/runs/4184654744
