### ISSUE TITLE
BiLSTM incorrect on MPS

### ISSUE THREAD

**Issue by FrankVerhoef** [pytorch/pytorch#94754]
### 🐛 Describe the bug

Hi, I been testing various NLP models on MPS, and I observe various strange things. It seems that bidirectional LSTM on MPS is not working correctly.

```
import torch
import torch.nn as nn

print("Torch version: ", torch.__version__)
torch.manual_seed(123)
embeddings = torch.rand(3,1,2)  # L, B, E

model = nn.LSTM(input_size=2, hidden_size=2, bidirectional=True)
print(model(embeddings)[0])

model.to("mps")
print(model(embeddings.to("mps"))[0])
```

Results are below. CPU above, MPS below. How can results on CPU be different than on MPS?

```
Torch version:  2.0.0.dev20230205
tensor([[[ 0.0054,  0.2338, -0.1167,  0.2263]],
        [[ 0.0200,  0.3305, -0.0967,  0.2075]],
        [[ 0.0422,  0.3740, -0.0590,  0.1553]]], grad_fn=<CatBackward0>)
tensor([[[0.2325, 0.2447, 0.4149, 0.4394]],
        [[0.3524, 0.3702, 0.3516, 0.3785]],
        [[0.4139, 0.4346, 0.2306, 0.2531]]], device='mps:0',
       grad_fn=<CatBackward0>)
```

### Versions

I’m testing on MacBook Pro with M1PRO, 32GB, 10-core CPU, 16-core GPU.

```
PyTorch version: 2.0.0.dev20230205
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 10:02:19)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230205
[pip3] torchaudio==2.0.0.dev20230205
[pip3] torchvision==0.15.0.dev20230205
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.23.5           py39he696674_0  
[conda] numpy-base                1.23.5           py39h9cd3388_0  
[conda] pytorch                   2.0.0.dev20230205         py3.9_0    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230205        py39_cpu    pytorch-nightly
[conda] torchvision               0.15.0.dev20230205        py39_cpu    pytorch-nightly
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by FrankVerhoef** [comment]
Hi, I tested again with the torch version 2.0.0.dev20230217

Good news: BiLSTM now gives identical results on CPU and MPS when batch size is 1.
Bad new: for batch_size > 1 the results between CPU and MPS are still different.

See code and results below:

```
import torch
import torch.nn as nn

print("Torch version: ", torch.__version__)
torch.manual_seed(123)

L = 3
E = 2
H = 2
B = 2

embeddings = torch.rand(L, B, E)

model = nn.LSTM(input_size=E, hidden_size=H, bidirectional=True)
print(model(embeddings)[0])

model.to("mps")
print(model(embeddings.to("mps"))[0].cpu())
```

Results:
```
Torch version:  2.0.0.dev20230217
tensor([[[0.0951, 0.1953, 0.2797, 0.2260],
         [0.0947, 0.2093, 0.2565, 0.2200]],

        [[0.1123, 0.3291, 0.3117, 0.1985],
         [0.0853, 0.2484, 0.2476, 0.1765]],

        [[0.1098, 0.3561, 0.2160, 0.1431],
         [0.1133, 0.3230, 0.1860, 0.1473]]], grad_fn=<CatBackward0>)
tensor([[[ 0.0795, -0.1824,  0.1861,  0.6133],
         [-0.0501, -0.0310,  0.0836, -0.1889]],

        [[ 0.1875, -0.1214,  0.0998,  0.4282],
         [ 0.0080, -0.0500,  0.1600,  0.0134]],

        [[ 0.1676, -0.1952,  0.0444,  0.2389],
         [-0.0549, -0.0234,  0.0399, -0.2643]]], grad_fn=<ToCopyBackward0>)
```

**Comment by AlexRoar** [comment]
There are some serious issues in `master` LSTM implementation right now. Most of them are adressed in #95137. But additional work is required to make `bidirectional` work

**Comment by AlexRoar** [comment]
> Hi, I tested again with the torch version 2.0.0.dev20230217
> 
> Good news: BiLSTM now gives identical results on CPU and MPS when batch size is 1. Bad news: for batch_size > 1 the results between CPU and MPS are still different.
> 
> See code and results below:
> 
> ```
> import torch
> import torch.nn as nn
> 
> print("Torch version: ", torch.__version__)
> torch.manual_seed(123)
> 
> L = 3
> E = 2
> H = 2
> B = 2
> 
> embeddings = torch.rand(L, B, E)
> 
> model = nn.LSTM(input_size=E, hidden_size=H, bidirectional=True)
> print(model(embeddings)[0])
> 
> model.to("mps")
> print(model(embeddings.to("mps"))[0].cpu())
> ```
> 
> Results:
> 
> ```
> Torch version:  2.0.0.dev20230217
> tensor([[[0.0951, 0.1953, 0.2797, 0.2260],
>          [0.0947, 0.2093, 0.2565, 0.2200]],
> 
>         [[0.1123, 0.3291, 0.3117, 0.1985],
>          [0.0853, 0.2484, 0.2476, 0.1765]],
> 
>         [[0.1098, 0.3561, 0.2160, 0.1431],
>          [0.1133, 0.3230, 0.1860, 0.1473]]], grad_fn=<CatBackward0>)
> tensor([[[ 0.0795, -0.1824,  0.1861,  0.6133],
>          [-0.0501, -0.0310,  0.0836, -0.1889]],
> 
>         [[ 0.1875, -0.1214,  0.0998,  0.4282],
>          [ 0.0080, -0.0500,  0.1600,  0.0134]],
> 
>         [[ 0.1676, -0.1952,  0.0444,  0.2389],
>          [-0.0549, -0.0234,  0.0399, -0.2643]]], grad_fn=<ToCopyBackward0>)
> ```

Works correctly with #95563 fix. Hope that it will be merged soon
