### ISSUE TITLE
[ONNX] Circular import issue between torch.onnx and torch.onnx._internal.fx

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#94800]
torch.onnx and torch.onnx._internal.fx can't share common files right now due to circular import problems. If this can be fixed, the common functions in files, such as onnx_proto_utils.py/verification.py/options.py, could be used from both sides.

cc @BowenBao @justinchuby @wschin

**Comment by BowenBao** [comment]
I thought it wouldn't be an issue for `torch.onnx._internal.fx` to import the common files, and not the other way around?

**Comment by justinchuby** [comment]
What caused the issue?

**Comment by titaiwangms** [comment]
> I thought it wouldn't be an issue for `torch.onnx._internal.fx` to import the common files, and not the other way around?

Oh yup, you are right! I should just move the common files outside of _internal.fx. Then this doesn't seem to be an issue to be fixed.

**Comment by titaiwangms** [comment]
> What caused the issue?

torch.onnx -> _internal.fx -> torch._dynamo -> torch.onnx -> circular

**Comment by BowenBao** [comment]
> torch.onnx -> _internal.fx -> torch._dynamo -> torch.onnx -> circular

We cannot have "torch.onnx -> _internal.fx". Otherwise, we will need to handle the "onnx-script not installed problem" because "torch.onnx" is imported when "import torch".

Could you share a concrete example?

**Comment by BowenBao** [comment]
> moving any function in fx.exporter.py to onnx_proto_utils.py

Does this make `onnx_proto_utils.py` import things in `torch.onnx._internal.fx`?

**Comment by titaiwangms** [comment]
> > moving any function in fx.exporter.py to onnx_proto_utils.py
> 
> Does this make `onnx_proto_utils.py` import things in `torch.onnx._internal.fx`?

Oh yes...
