### ISSUE TITLE
Make `torch.onnx.utils._optimize_graph` use several CPU cores

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#94821]
### 🚀 The feature, motivation and pitch

As per title, the function `_optimize_graph` from `torch/onnx/utils.py` uses a single core. This can be checked using `mpstat -P ALL 1` and putting some prints to pin down where the export is hanging.

https://github.com/pytorch/pytorch/blob/d1d5d16df3766bc6a6c9ebe1168ff652bcdcaa5e/torch/onnx/utils.py#L564

This is probably a factor in some exports being extremely slow, maybe linked https://github.com/pytorch/pytorch/issues/63734

In particular, I notice that I am hanging in https://github.com/pytorch/pytorch/blob/d1d5d16df3766bc6a6c9ebe1168ff652bcdcaa5e/torch/onnx/utils.py#L665 which apparently maps to https://github.com/pytorch/pytorch/blob/d1d5d16df3766bc6a6c9ebe1168ff652bcdcaa5e/torch/csrc/jit/passes/onnx.cpp#L165 that takes a very long time, with a single core active.

It would be useful for the method to use several cores.

### Alternatives

Stop using `torch.onnx.export` altogether, stay in PyTorch all the way.

### Additional context

PyTorch version: 1.13.1

cc @ngimel

**Comment by handicraftsmanthk** [comment]
I meet the same problem.But I need to export to onnx.What can I do?

**Comment by emcastillo** [comment]
We are also having several issues with this :(

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is being replaced by `torch.onnx.dynamo_export` which doesn't use this optimization mechanism.
Closing as this task would require a lot of work for a legacy exporter
