### ISSUE TITLE
make size mismatch assert user-friendly / understandable

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#94841]
### 🚀 The feature, motivation and pitch

It's very difficult to make sense of this assert:

```
    output = input.matmul(weight.t())
RuntimeError: size mismatch, got 15, 15x2048,0
```

it's very difficult to figure out what the numerical part of the assert means, as it mixes both tensor sizes together.

Could we please change this to the well written size mismatch assert of other ops, like:

```
RuntimeError: size mismatch, m1: [64 x 103], m2: [550 x 50]
```

I have identified at least 2 of these asserts:

```
aten/src/ATen/native/Blas.cpp:     "size mismatch, got ", self.size(0), ", ", mat.size(0), "x", mat.size(1), ",", vec.size(0));
torch/_decomp/decompositions.py:        lambda: f"size mismatch, got {self.size(0)}x{self.size(1)},{vec.size(0)}",
```
I don't know if there are others like that.

Thank you!

**Comment by albanD** [comment]
Ho yes we should definitely improve those. I'm happy to review a PR fixing these.
