### ISSUE TITLE
functionalization + make_fx is inconsistent with make_fx for max_pool2d

### ISSUE THREAD

**Issue by ar0ck** [pytorch/pytorch#94856]
### 🐛 Describe the bug

Not a bug per se, just a (perhaps unnecessary) inconsistency with `max_pool2d` when using `make_fx(functionalize(...))` instead of `make_fx(...)`. To illustrate this, consider the following block of code:
```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx

decompositions = {
    torch.ops.aten.max_pool2d.default: lambda x, *_: x
}

def fwd(x):
    return torch.max_pool2d(x, (1, 1))

with torch.inference_mode():
    # fwd = torch.func.functionalize(fwd)
    fx = make_fx(fwd, decompositions)(torch.randn(1, 1, 1, 1))
fx.graph.print_tabular()
```

This yields the following output:

```
opcode       name    target    args    kwargs
-----------  ------  --------  ------  --------
placeholder  x_1     x_1       ()      {}
output       output  output    (x_1,)  {}
```

However, with the call to `functionalize` un-commented, we instead obtain:
```
opcode         name                     target                                args                          kwargs
-------------  -----------------------  ------------------------------------  ----------------------------  --------
placeholder    x_1                      x_1                                   ()                            {}
call_function  max_pool2d_with_indices  aten.max_pool2d_with_indices.default  (x_1, [1, 1])                 {}
call_function  getitem                  <built-in function getitem>           (max_pool2d_with_indices, 0)  {}
call_function  getitem_1                <built-in function getitem>           (max_pool2d_with_indices, 1)  {}
output         output                   output                                (getitem,)                    {}
```

Digging into it a bit, it seems that after functionalization, `torch.max_pool2d` is dispatched directly to `aten.max_pool2d_with_indices`, even with `return_indices=False`. Underlying issue is probably https://github.com/pytorch/pytorch/issues/41099.

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230214+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         805.818
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       768 KiB
L1i cache:                       512 KiB
L2 cache:                        20 MiB
L3 cache:                        24 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230214+cpu
[pip3] torchaudio==2.0.0.dev20230214+cpu
[pip3] torchvision==0.15.0.dev20230214+cpu
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by jansel** [comment]
@bdhirsh is this expected behavior?

**Comment by ezyang** [comment]
Looks like a bug to me

**Comment by bdhirsh** [comment]
This isn't really specific to functionalization - it happens to be the case today that `torch.inference_mode()` doesn't play too well with tracing. This usually isn't too big of a problem, since `torch.inference_mode()` is mainly meant to reduce eager mode overhead in some cases, and you probably don't want to turn it on when you're tracing.

The issue is that `max_pool2d` **always** decomposes into `max_pool2d_with_indices`, but that decomposition is registered to the autograd dispatch keys. When `torch.inference_mode()` is turned on, autograd dispatch keys are completely disabled, so that decomposition never runs.

If you remove inference mode in your repro, you get the same results with/without funcitonalization:
```
import torch
from torch.fx.experimental.proxy_tensor import make_fx

decompositions = {
    torch.ops.aten.max_pool2d.default: lambda x, *_: x
}

def fwd(x):
    return torch.max_pool2d(x, (1, 1))

#fwd = torch.func.functionalize(fwd)
fx = make_fx(fwd, decompositions)(torch.randn(1, 1, 1, 1))
fx.graph.print_tabular()
```

that gives:
```
opcode         name                     target                                args                          kwargs
-------------  -----------------------  ------------------------------------  ----------------------------  --------
placeholder    x_1                      x_1                                   ()                            {}
call_function  max_pool2d_with_indices  aten.max_pool2d_with_indices.default  (x_1, [1, 1])                 {}
call_function  getitem                  <built-in function getitem>           (max_pool2d_with_indices, 0)  {}
call_function  getitem_1                <built-in function getitem>           (max_pool2d_with_indices, 1)  {}
output         output                   output                                (getitem,)                    {}
```

**Comment by ar0ck** [comment]
@bdhirsh thanks, that makes sense.

So in order to avoid these inconsistencies, is the recommendation to not trace with `torch.inference_mode()` enabled? Would it be possible (or even desirable) for functionalization to "respect" inference mode's dispatch?

**Comment by bdhirsh** [comment]
Yep, I would recommend not tracing with `torch.inference_mode()` enabled.

> Would it be possible (or even desirable) for functionalization to "respect" inference mode's dispatch?

I'm not sure it's worth bending over backwards to try to get this to work, mostly because I don't think that the current interaction between inference mode and tracing (silently preventing certain decomps from running) is really a "feature" to try to generalize.
