### ISSUE TITLE
Benchmarking of Cudnn convolutions is bugged when Tensor Cores are used.

### ISSUE THREAD

**Issue by rotabulo** [pytorch/pytorch#9486]
## Issue description

The CUDNN function `cudnnFindConvolutionForwardAlgorithmEx` (used in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cudnn/Conv.cpp#L481) searches an optimal algorithm satisfying the provided workspace constraint by varying the algorithm type but also by changing the math type. The current code fixes the math type to `CUDNN_TENSOR_OP_MATH` if fp16 is used (see https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cudnn/Descriptors.h#L199) irrespective of the math type of the optimal algorithm returned by `cudnnFindConvolutionForwardAlgorithmEx`. The worst consequence of this oversight is that the workspace that gets allocated under the wrong math type assumption violates the actual memory constraint estimated with `getMaxWorkspaceSize`, resulting in a `CUDA Out Of Memory`.

A possible solution to this issue could be to cache the `cudnnConvolutionFwdAlgoPerf_t` structures rather than `cudnnConvolutionFwdAlgo_t`. In this way the information about the correct `math type` is available and can be properly set before computing the actual workspace and before running the convolution.

The issue does not affect only the forward pass, but also eventually `BwdData` and `BwdFilter`.

**Comment by zou3519** [comment]
cc @ezyang what do you think?

**Comment by zou3519** [comment]
Could be related: #9465

**Comment by rotabulo** [comment]
@zou3519 this and #9465 are two different bugs. The only thing in common is that both are affected by the use of fp16.

**Comment by ezyang** [comment]
@rotabulo The proposed solution sounds good to me. Are you planning to submit a PR?

**Comment by ezyang** [comment]
Thanks @rotabulo. Do you have a repro, by any chance?

**Comment by ngimel** [comment]
Closing due to age, benchmarking of cudnn algorithms has been redone since.
