### ISSUE TITLE
`multi_tensor_apply()` with size-0 tensors can corrupt stack

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#94865]
Since I am not familiar enough with the foreach testing infra (like in `test/test_foreach.py`), I decided to open an issue. I also do not know which label to add, so thanks in advance to the person triaging!

**Repro**
```
# Define this to be large enough to trigger stack corruption
NUM_SIZE0_TENSORS = 1000
def test_multi_tensor_apply_size0_tensors_cuda(self):
    size0_tensors = [
        torch.empty(0, device="cuda") for _ in range(NUM_SIZE0_TENSORS)
    ]
    # Check that this does not segfault
    torch._foreach_mul_(size0_tensors, 0.1)
```
We can repeat this for all different variations of the foreach ops. What matters is that they call into `multi_tensor_apply()`.

**Details**
For size-0 tensors, in `multi_tensor_apply()`, `loc_tensor_info` gets incremented but never reset because the core inner `for` loop does not run. This means that addresses and numels are written to the stack-allocated `tensorListMeta` unboundedly, which can cause stack corruption and a segfault.

We can fix this by simply adding a check for size-0 tensors and continuing. See https://github.com/pytorch/pytorch/pull/94655 for what I mean. Since the change is only to CPU-side code and is quite minimal, I think it should be pretty safe to add without risk for performance regressions.

cc @crcrpar @mcarilli @ngimel

**Comment by zhaojuanmao** [comment]
cc @ngimel

**Comment by ngimel** [comment]
cc @crcrpar

**Comment by awgu** [comment]
Thanks @ngimel  for taking a look at the PR (https://github.com/pytorch/pytorch/pull/94655)!

Hi @crcrpar! If you had any guidance on improving the unit testing in https://github.com/pytorch/pytorch/pull/94655, I can do that and then land that PR. (Right now, the unit tests are just added to FSDP code and only check one foreach op.) Otherwise, feel free to open your own PR as well if that is more time efficient.

**Comment by crcrpar** [comment]
I guess it'd require some changes in e.g. https://github.com/pytorch/pytorch/blob/1d7133c542fd5f87cd4efd87da449d4484050aaa/torch/testing/_internal/opinfo/core.py#L2544, https://github.com/pytorch/pytorch/blob/1d7133c542fd5f87cd4efd87da449d4484050aaa/torch/testing/_internal/common_methods_invocations.py#L8020

both could be convoluted at glance so I'm happy to do myself :)

**Comment by awgu** [comment]
> I guess it'd require some changes in e.g.
> 
> https://github.com/pytorch/pytorch/blob/1d7133c542fd5f87cd4efd87da449d4484050aaa/torch/testing/_internal/opinfo/core.py#L2544
> 
> ,
> https://github.com/pytorch/pytorch/blob/1d7133c542fd5f87cd4efd87da449d4484050aaa/torch/testing/_internal/common_methods_invocations.py#L8020
> 
> both could be convoluted at glance so I'm happy to do myself :)

Yes, for sure. Please go ahead and do it yourself :)

Thanks so much!
