### ISSUE TITLE
jvp + nn.DataParallel throws RuntimeError

### ISSUE THREAD

**Issue by gortizji** [pytorch/pytorch#94896]
### 🐛 Describe the bug

I am trying to create a new class `LinearizedModel` that takes as input an `nn.Module` and creates a linearized version of it that can be trained transparently as any other `nn.Module`, i.e., a PyTorch alternative to the [`linearize` function of `neural_tangents`](https://neural-tangents.readthedocs.io/en/latest/_autosummary/neural_tangents.linearize.html).

```python
import torch.nn as nn
from functorch import make_functional, jvp

class LinearizedModel(nn.Module):
    """Creates a linearized version of a nn.Module.

    The linearized version of a model is a proper PyTorch model and can be
    trained as any other nn.Module.

    Args:
        model (nn.Module): The model to linearize.
    """

    def __init__(self, model: nn.Module) -> None:
        """Initializes the linearized model."""
        super().__init__()
        func0, params0 = make_functional(model.eval(), disable_autograd_tracking=True)

        # We wrap the func0 module in a lambda function to hide its "meta"
        # parameters from the parameter list.
        self.func0 = lambda params, x: func0(params, x)

        self.params = nn.ParameterList([nn.Parameter(p.clone()) for p in params0])
        self.params0 = nn.ParameterList(params0)

        # We don't want to train the initialization parameters.
        for p in self.params0:
            p.requires_grad = False

    def __call__(self, x) -> torch.Tensor:
        """Computes the linearized model output using a first-order Taylor decomposition."""
        dparams = [p - p0 for p, p0 in zip(self.params, self.params0)]
        _, dp = jvp(
            lambda param: self.func0(param, x),
            (tuple(self.params0),),
            (tuple(dparams),),
        )
        return self.func0(self.params0, x) + dp

```

My code works fine as long as I run on a single GPU, but the moment I wrap my `LinearizedModel` with `nn.DataParallel` I get: `RuntimeError: data.find(layerId) == data.end() INTERNAL ASSERT FAILED at "../aten/src/ATen/functorch/DynamicLayer.cpp":256, please report a bug to PyTorch.`

This is a short snippet to reproduce the previous error:
```python
import torch
import torch.nn as nn
from functorch import make_functional, jvp

class LinearizedModel(nn.Module):
  ...

model = nn.Sequential(nn.Linear(2, 2), nn.ReLU(), nn.Linear(2, 1))
linearized_model = LinearizedModel(model)

devices = [0, 1]
parallel_model = nn.DataParallel(linearized_model, device_ids=devices)
parallel_model = parallel_model.cuda()

x = torch.randn(10, 2).cuda()
y = parallel_model(x)
```
and the full traceback of the exception:
```
Traceback (most recent call last):
  File "/home/gortiz/projects/task_vectors_ntk/dp_bug.py", line 51, in <module>
    y = parallel_model(x)
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/gortiz/projects/task_vectors_ntk/dp_bug.py", line 35, in __call__
    _, dp = jvp(
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 788, in jvp
    return _jvp_with_argnums(func, primals, tangents, argnums=None, strict=strict, has_aux=has_aux)
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/home/gortiz/.conda/envs/task-arithmetic/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 824, in _jvp_with_argnums
    level = _jvp_increment_nesting()
RuntimeError: data.find(layerId) == data.end() INTERNAL ASSERT FAILED at "../aten/src/ATen/functorch/DynamicLayer.cpp":256, please report a bug to PyTorch.
```

### Versions

PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.15.0-115-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.4.120
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB

Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              72
On-line CPU(s) list: 0-71
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
Stepping:            7
CPU MHz:             3526.872
BogoMIPS:            5200.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70
NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] open-clip-torch==2.10.1
[pip3] torch==1.13.1+cu116
[pip3] torchaudio==0.13.1+cu116
[pip3] torchvision==0.14.1+cu116
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-fft                   1.3.1                    pypi_0    pypi
[conda] mkl-random                1.2.2                    pypi_0    pypi
[conda] mkl-service               2.4.0                    pypi_0    pypi
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0
[conda] mkl_random                1.2.2           py310h00e6091_0
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.23.5          py310h8e6c178_0
[conda] open-clip-torch           2.10.1                   pypi_0    pypi
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torch                     1.13.1+cu116             pypi_0    pypi
[conda] torchaudio                0.13.1+cu116             pypi_0    pypi
[conda] torchvision               0.14.1+cu116             pypi_0    pypi

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by ngimel** [comment]
DataParallel is in maintenance mode, and bugs related to DataParallel aren't fixed.

**Comment by gortizji** [comment]
I see. Well, in case someone stumbles upon the same problem: I just tried using `DistributedDataParallel` instead and my code seems to work fine. I will close the issue, then.

Thanks!
