### ISSUE TITLE
Compile PyTorch/Caffe2 with /MD runtime library

### ISSUE THREAD

**Issue by iamhatesz** [pytorch/pytorch#9490]
## Issue description

I have a VS project with a lot of dependencies compiled for /MD runtime. By default, Caffe2 compiles into /MT runtime, so it's not working together. I read somewhere that setting BUILD_SHARED_LIBS to ON sets runtime to /MD, but for me it results with the following linker error:

`       "C:\Users\XXX\Libs\pytorch\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Users\XXX\Libs\pytorch\build\caffe2\caffe2_pybind11_state.vcxproj" (default target) (22) ->
       (Link target) ->
         pybind_state.obj : error LNK2019: unresolved external symbol "public: __cdecl onnx_c2::TensorProto::TensorProt
       o(void)" (??0TensorProto@onnx_c2@@QEAA@XZ) referenced in function "public: class pybind11::bytes __cdecl <lambda
       _ec355006db76b188803f2103fd5aad3c>::operator()(class caffe2::onnx::Caffe2Backend &,class pybind11::bytes const &
       ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<la
       mbda_ec355006db76b188803f2103fd5aad3c>@@QEBA?AVbytes@pybind11@@AEAVCaffe2Backend@onnx@caffe2@@AEBV12@AEBV?$basic
       _string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\Users\XXX\Libs\pytorch\build\caffe2\caffe2_pybi
       nd11_state.vcxproj]
         pybind_state.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl onnx_c2::TensorProto::~T
       ensorProto(void)" (??1TensorProto@onnx_c2@@UEAA@XZ) referenced in function "public: class pybind11::bytes __cdec
       l <lambda_ec355006db76b188803f2103fd5aad3c>::operator()(class caffe2::onnx::Caffe2Backend &,class pybind11::byte
       s const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const
       " (??R<lambda_ec355006db76b188803f2103fd5aad3c>@@QEBA?AVbytes@pybind11@@AEAVCaffe2Backend@onnx@caffe2@@AEBV12@AE
       BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\Users\XXX\Libs\pytorch\build\caffe2\ca
       ffe2_pybind11_state.vcxproj]
         C:\Users\XXX\Libs\pytorch\build\caffe2\python\Release\caffe2_pybind11_state.cp37-win_amd64.pyd : fatal erro
       r LNK1120: 2 unresolved externals [C:\Users\XXX\Libs\pytorch\build\caffe2\caffe2_pybind11_state.vcxproj]
`

I am building using vs141 toolchain in Release mode.

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): build_windows.bat
- OS: Windows 10
- PyTorch version: latest master
- Python version: 3.7.0
- CUDA/cuDNN version: none
- GPU models and configuration: none
- GCC version (if compiling from source): vs141 toolchain (Visual Studio 2017)
- CMake version: 3.12.0
- Versions of any other relevant libraries: -

**Comment by iamhatesz** [comment]
After brief investigation of generated caffe2_pybind11_state.vcxproj for both BUILD_SHARED_LIBS=ON and OFF configurations, I see onnx libs are not being linked, when building with BUILD_SHARED_LIBS=ON. Why is that? Should I build it on my own and provide it to the linker?

**Comment by zou3519** [comment]
cc @peterjc123

**Comment by pjh5** [comment]
FYI there is /MD fiddling here https://github.com/pytorch/pytorch/blob/master/CMakeLists.txt#L241 .

I don't think this is actually related to ONNX; I don't think Caffe2 links against ONNX and you don't need ONNX to build Caffe2. Can you find that missing symbol in an onnx library or somewhere else?

**Comment by iamhatesz** [comment]
I did diff between above-mentioned caffe2_pybind11_state.vcxproj files, and here's what I've found:

caffe2_pybind11_state.vcxproj @ /MT
`<AdditionalDependencies>C:\Users\XXX\AppData\Local\Programs\Python\Python37\libs\python37.lib;-WHOLEARCHIVE:C:/Users/XXX/Libs/pytorch/build/lib/Release/caffe2.lib;-WHOLEARCHIVE:C:/Users/XXX/Libs/pytorch/build/lib/Release/caffe2_protos.lib;..\lib\Release\nomnigraph.lib;..\lib\Release\cpuinfo.lib;..\lib\Release\onnxifi_loader.lib;-WHOLEARCHIVE:C:/Users/XXX/Libs/pytorch/build/lib/Release/onnx.lib;..\lib\Release\onnx_proto.lib;..\lib\Release\libprotobuf.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib</AdditionalDependencies>`

caffe2_pybind11_state.vcxproj @ /MD
`<AdditionalDependencies>C:\Users\XXX\AppData\Local\Programs\Python\Python37\libs\python37.lib;..\lib\Release\caffe2.lib;..\lib\Release\libprotobuf.lib;..\lib\Release\nomnigraph.lib;kernel32.lib;user32.lib;gdi32.lib;winspool.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;comdlg32.lib;advapi32.lib</AdditionalDependencies>`

So in /MT there is a lot of additional libraries being linked. Is this a desired behavior?

**Comment by peterjc123** [comment]
It is now compiled with /MD.
