### ISSUE TITLE
Slight output difference when converting to ONNX

### ISSUE THREAD

**Issue by traverso-inspectifai** [pytorch/pytorch#94984]
### 🐛 Describe the bug

I have to convert my pytorch model to ONNX. In the following function I check that the conversion is fine, i.e. the difference between the pytorch model and the onnx model is below ``rtol=1e-03, atol=1e-05``. Particularly, I check that for the first 2000 tensors from my data loader. The conversion is ok (below the tolerance values) for 1999 tensors and above for one of them.

I checked the tensor causing the problem and seems to be ok: same shape, same min value and same max value. The difference is 0.0001233667. 

I guess this is a bug and not a problem in the way I am doing the conversion. Otherwise, the mismatch of the values would occur more often.

```python

def compare_model_outputs_onnx(model: nn.Module, model_onnx: ort.InferenceSession, data_generator: torch.utils.data.DataLoader[Tuple[torch.Tensor, torch.Tensor, str]]) -> None:
    input_name = model_onnx.get_inputs()[0].name
    output_diffs = []
    for image_tensor, _, _ in itertools.islice(data_generator, 10000):
        if torch.cuda.is_available():
            image_tensor = image_tensor.cuda()

        # compute ONNX Runtime output prediction
        onnx_input = to_numpy(image_tensor)

        ort_inputs = {input_name: onnx_input}
        ort_outs = model_onnx.run(None, ort_inputs)

        torch_output = to_numpy(model(image_tensor))
        onnx_output = ort_outs[0]

        # compare ONNX Runtime and PyTorch results

        if not np.allclose(torch_output, onnx_output, rtol=1e-03, atol=1e-5):
            print(f"The max difference {np.abs(onnx_output - torch_output).max()} is larger than the atol {5e-5}")
            raise RuntimeError("Prediction of onnx model model not identical to trained model")
```

I tested it with Pytorch 1.12.0 and 1.13.1 with the same results.

### Versions

torch = "1.12.0"
onnxruntime = "1.13.1"
pytorch-lightning = "1.9.0"

**Comment by BowenBao** [comment]
Hi @traverso-inspectifai we've recently introduced a tool to help diagnose the mismatch between exported onnx model and pytorch model. Would you mind give it a try with pytorch nightly?

https://pytorch.org/docs/master/onnx.html#torch.onnx.verification.find_mismatch

**Comment by traverso-inspectifai** [comment]
Hi @BowenBao,

I ran the following code:

```
model = LitModel.load_from_checkpoint(checkpoint_path)
model.eval()

for image_tensor, _, path in val_generator:
    if path[0] == r"C:\training-reports\2022-10-28T08-54-26/data/validation\bad\3185718d-ffd6-45cc-8405-ced4b5870333.bmp":
        graph_info = verification.find_mismatch(model.model, (image_tensor,), opset_version=11, do_constant_folding=True)
        print(graph_info)
```

where model.model is a `torchvision.models.mobilenet_v3_small`. As you see, I had to check the filepath because not all of the tensors are giving problems.

The output of the code is the following:
[onnx_verification_output.txt](https://github.com/pytorch/pytorch/files/10906890/onnx_verification_output.txt)


I can't publish the tensor nor the model weights because of NDA agreements. However, I can tell you that the tensor has a shape of (1, 3, 224, 224), the dtype is torch.float32, the device is cpu and `requires_grad=False`. The values are among 0 and 1.

**Comment by BowenBao** [comment]
Hi @traverso-inspectifai, posting the summary in comment for reference. It shows that the mismatch can only be observed till subgraph `000`, and not any further. Usually this type of mismatch is caused by accumulation of slight differences in operators. There are a few ways to further verify this.

1. Tighten the verification atol/rtol until individual mismatch nodes can be observed. This can be done by providing an `option` argument to `find_mismatch`.
2. Inspect and extract a minified ONNX repro from the erroring subgraph. This can be done by https://pytorch.org/docs/master/generated/torch.onnx.verification.GraphInfo.html#torch.onnx.verification.GraphInfo.find_partition and https://pytorch.org/docs/master/generated/torch.onnx.verification.GraphInfo.html#torch.onnx.verification.GraphInfo.export_repro

```
==================================== Tree: =====================================
160 X   __80 X   __40 X    __20 X     __10 ✓
id:    |  id: 0 |  id: 00 |  id: 000 |  id: 0000
       |        |         |          |
       |        |         |          |__10 ✓
       |        |         |             id: 0001
       |        |         |
       |        |         |__20 ✓
       |        |            id: 001
       |        |
       |        |__40 ✓
       |           id: 01
       |
       |__80 ✓
          id: 1
=========================== Mismatch leaf subgraphs: ===========================
['000']
============================= Mismatch node kinds: =============================
{}
```

**Comment by traverso-inspectifai** [comment]
HI @BowenBao,

 I asked my supervisor if I can upload a subgraph of the model with its inputs. Meanwhile, I reduced the atol until 1e-50 and this is the output:
 
```
===================== Mismatch info for graph partition : ======================
================================ Mismatch error ================================
Tensor-likes are not close!

Mismatched elements: 2 / 2 (100.0%)
Greatest absolute difference: 1.4990568161010742e-05 at index (0, 1) (up to 1e-50 allowed)
Greatest relative difference: 0.36870075132856883 at index (0, 1) (up to 0.001 allowed)
==================================== Tree: =====================================
160 X   __80 X   __40 X    __20 X     __10 ✓
id:    |  id: 0 |  id: 00 |  id: 000 |  id: 0000
       |        |         |          |
       |        |         |          |__10 X      __5 ✓
       |        |         |             id: 0001 |  id: 00010
       |        |         |                      |
       |        |         |                      |__5 ✓
       |        |         |                         id: 00011
       |        |         |
       |        |         |__20 ✓
       |        |            id: 001
       |        |
       |        |__40 ✓
       |           id: 01
       |
       |__80 X   __40 ✓
          id: 1 |  id: 10
                |
                |__40 X    __20 ✓
                   id: 11 |  id: 110
                          |
                          |__20 X     __10 ✓
                             id: 111 |  id: 1110
                                     |
                                     |__10 X      __5 ✓
                                        id: 1111 |  id: 11110
                                                 |
                                                 |__5 ✓
                                                    id: 11111
=========================== Mismatch leaf subgraphs: ===========================
['0001', '1111']
============================= Mismatch node kinds: =============================
{}
```
 
 If I understand the output correctly:
- The first mistmatch with 1e-100 happens in 0001 and 1111.
- The subgraphs of 0001 and 1111 do not show any mismatch.
- The mismatch occurs when aggregating the results of, on one side 11110 and 11111, and on the other side 00010 and 00011

Am I missing something or is my explanation right? Should I reduce even more the atol?

**Comment by BowenBao** [comment]
@traverso-inspectifai you could try tighten the rtol at the same time. But at this point it shows that the mismatch is most likely a result of small numerical difference between different backends.

**Comment by jbaumgart0** [comment]
I realize I'm late to this thread, but I ran across this issue when trying to figure out a similar problem I was seeing.  Try adding the following line of code when inferencing with PyTorch and compare again with the ONNX model's output:

`torch.backends.cudnn.benchmark = True`

In my case, this resolved the problem.

**Comment by traverso-inspectifai** [comment]
I included recently this line in my code for speed reasons. I did not check if there was a change in the behavior of the ONNX conversion. I will take a look. Thanks!
