### ISSUE TITLE
Move ConstantPadNd into ATen

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9499]
`ConstantPadNd` is currently implemented in Python at [torch/nn/_functions/padding.py](https://github.com/pytorch/pytorch/blob/master/torch/nn/_functions/padding.py). We'd like it to be implemented as a native function in ATen. Note that you will need to update `pad(..)` in `nn/functional.py` after porting.

Reading material:

1. How to add a native function: https://github.com/pytorch/pytorch/tree/master/aten/src/ATen/native/
2. Derivatives are added in `tools/autograd/derivatives.yaml`

Tips:
  There is no context object in native functions; instead, if something needs to be reused in `backward`, 
  + if it is an input argument or output of `forward`, you can use it directly in `tools/autograd/derivatives.yaml`.
  + otherwise, make it an output of the `forward`

**Comment by vishwakftw** [comment]
Sorry about this: `ConstantPadNd` resides in `torch/nn/_functions/padding.py`.

**Comment by wdhorton** [comment]
Hi @SsnL! I'd like to take this on

**Comment by SsnL** [comment]
@wdhorton Thanks! Let me know if you have any questions. :)

**Comment by wdhorton** [comment]
Hi @SsnL, I've been working on this, feel like I have most of the `forward` function moved over the C++, but I had a question about this line:
```
output = input.new(input.size()[:(ctx.l_diff)] + new_dim).fill_(ctx.value)
```

I can't seem to track down the C++ equivalent of the `.new` method being called here. Any suggestions on how I should translate that?

**Comment by SsnL** [comment]
Use `at::empty(shape, input.options())`. The original python code was written a long time ago and isn't optimal with the current standard. So don't feel compelled to do a line-by-line translation, :)

**Comment by wdhorton** [comment]
@SsnL I've got a PR here: #10885 if you have a chance to review

**Comment by peterbell10** [comment]
The linked porting PR was merged.
