### ISSUE TITLE
[Inductor] [CPU] Crash failure in torchbench model vision_maskrcnn

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#95029]
### 🐛 Describe the bug

On WW07.4 from  [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1434019397) , we observed crash failure in torchbench model vision_maskrcnn.

Log:

```
Traceback (most recent call last):
  File "benchmarks/dynamo/torchbench.py", line 385, in <module>
    torchbench_main()
  File "benchmarks/dynamo/torchbench.py", line 381, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 1833, in main
    return maybe_fresh_cache(run, args.cold_start_latency and args.only)(
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 918, in inner
    return fn(*args, **kwargs)
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2164, in run
    ) = runner.load_model(device, model_name, batch_size=batch_size)
  File "benchmarks/dynamo/torchbench.py", line 282, in load_model
    benchmark = benchmark_cls(
  File "/workspace/benchmark/torchbenchmark/util/model.py", line 19, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/workspace/benchmark/torchbenchmark/models/vision_maskrcnn/__init__.py", line 72, in __init__
    dataset = CocoDetection(root=os.path.join(DATA_DIR, COCO_DATA[COCO_DATA_KEY][0]),
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/coco.py", line 33, in __init__
    super().__init__(root, transforms, transform, target_transform)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/vision.py", line 39, in __init__
    if isinstance(root, torch._six.string_classes):
AttributeError: module 'torch' has no attribute '_six'
ERROR

```

SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[de11145](https://github.com/pytorch/pytorch/commit/de1114554c38322273c066c091d455519d45472d)|[c10acb8](https://github.com/pytorch/pytorch/commit/c10acb834d73f399589ce08a9fea1e4520a8c02c)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

### Versions

Repro:

```

python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only vision_maskrcnn  --cold_start_latency


```

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ezyang** [comment]
upgrade torchvision
