### ISSUE TITLE
[TorchInductor] Op fusion provenance tracking is incorrect

### ISSUE THREAD

**Issue by parthmannan** [pytorch/pytorch#95022]
### 🐛 Describe the bug

Origin tracking in Inductor FusedSchedulerNode is incorrect. Checking `node.origins` leads to list of ops that may or may not have been a part of the Fused Node.
This is likely to not be a short-term fix but reporting it for tracking.

Example files attached below - 
If use `comment_origin=True` and track the origins in the printed output_code.py debug, it can be seen that incorrect ops are part of the node (such as `mm.default` part of fused kernel that does no matrix multiplication)
[ir_post_fusion.txt](https://github.com/pytorch/pytorch/files/10762563/ir_post_fusion.txt)
[output_code.txt](https://github.com/pytorch/pytorch/files/10762579/output_code.txt)

### Versions

Torch version - 2.0.0a0+git5a54537

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by jansel** [comment]
Can you share the original code?

**Comment by parthmannan** [comment]
Apologies for the late response. Here's a full example on how to reproduce this error with minimal script.
```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parameter import Parameter

from torch._inductor import config
config.comment_origin = True

class Net(nn.Module):
    def __init__(self, config):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(config['input_units'], config['hidden_units'], bias=True)
        self.ln = nn.LayerNorm(config['hidden_units'])
        self.fc2 = nn.Linear(config['hidden_units'], config['output_units'], bias=False)
        
    def forward(self, x, residuals):
        out      = self.fc1(x)
        out      = F.dropout(out, p=0.1, training=True)
        ln_input = out + residuals
        ln_out   = self.ln(ln_input)
        out      = self.fc2(ln_out)

        return out

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

config = {'input_units': 768, 'hidden_units': 768, 'seq_len': 512, 'batch_size': 64, 'output_units': 2048}

net = Net(config)
net.cuda()
net = net.half()

input_shape    = [config['seq_len'], config['batch_size'], config['input_units']]
residual_shape = [config['seq_len'], config['batch_size'], config['hidden_units']]
target_shape   = [config['seq_len'], config['batch_size'], config['output_units']]

network_fn = torch.compile(net)

bench_iters = 10

for idx in range(bench_iters):

    inp_tensor = torch.rand(input_shape, dtype=torch.float16, requires_grad=True, device='cuda')
    res_tensor = torch.rand(residual_shape, dtype=torch.float16, requires_grad=True, device='cuda')
    tgt_tensor = torch.rand(target_shape, dtype=torch.float16, requires_grad=True, device='cuda')

    outputs = network_fn(inp_tensor, res_tensor)
    outputs.backward(tgt_tensor)

```
[ir_post_fusion.txt](https://github.com/pytorch/pytorch/files/10798604/ir_post_fusion.txt)
[output_code.txt](https://github.com/pytorch/pytorch/files/10798631/output_code.txt)

If we use `TORCH_COMPILE_DEBUG=1` and look at the output_code.py generated in the backward pass, we can see that most kernels have `mm.default` as one of the origins but there is no matmul fusion in the kernel.

**Comment by parthmannan** [comment]
@mlazos @jansel Any update on this? Was the issue able to be reproduced? Thanks!

**Comment by mlazos** [comment]
I will take a look at this later today or tomorrow, haven't had a chance to look yet. Thanks for sharing the code

**Comment by mlazos** [comment]
This may be fixed by https://github.com/pytorch/pytorch/pull/959015, I can try running this tomorrow

**Comment by parthmannan** [comment]
I haven't extensively tested this but a couple small examples seem to be running as expected now. Thanks for fixing this folks :)
Closing this for now.
