### ISSUE TITLE
[Inductor] [CPU] Torchbench model hf_Longformer performance regression > 10% on ww07.4

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#95033]
### 🐛 Describe the bug

There is a performance regression on Torchbench model hf_Longformer on ww07.4 [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1434019577)  compare with ww07.2 as bellow:

|  ww07.4   |   |     |   |  ww07.2   |   |     |   | Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|1.0426	|1.0742891	|1.120053816	|1	|1.1938	|0.943502	 |1.126352688	|0.87	|1.01	|0.88

Please find sw info from [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531) 

Graph dump by cosim:

WW07.4:
[graph.txt](https://github.com/pytorch/pytorch/files/10765423/graph.txt)

WW07.2:
[graph.txt](https://github.com/pytorch/pytorch/files/10765435/graph.txt)

Repro:

```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only hf_Longformer  --cold_start_latency --batch_size 1 --threads 1
```

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @yanboliang @anijain2305 @Xia-Weiwen @desertfire

**Comment by leslie-fang-intel** [comment]
Merge it into https://github.com/pytorch/pytorch/issues/95037, since sync with @blzheng, they are the same root-cause.
