### ISSUE TITLE
[pytorch] torch.meshgrid to return a tensor

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9503]
Currently it returns a sequence of tensors of same size 
 (https://github.com/pytorch/pytorch/blob/master/torch/_torch_docs.py#L5890)

Should it not return a (stacked over dim0) tensor instead? Users will still be able to deconstruct it as: 
```python
xs, ys = torch.meshgrid([torch.arange(2), torch.arange(4)])
```
meshgrid can further be used in expressions for computing distances between cell positions (or position encoding), which is more convenient if coordinates are in a tensor directly.

Is there a reason for it to return a sequence?

**Comment by zou3519** [comment]
I think we wanted `torch.meshgrid` to follow numpy semantics. `numpy.meshgrid` returns a list of ndarrays:
```
In [95]:  x = np.arange(0, 5, 1)

In [96]: y = np.arange(0, 5, 1)

In [97]: np.meshgrid(x, y)
Out[97]:
[array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]), array([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]])]
```
I'm not sure what would be useful: having a stacked tensor or returning two outputs. Perhaps we could add an option to meshgrid to return a stacked tensor?

**Comment by fmassa** [comment]
I think we should still return a tuple of tensors, as they can directly be passed as inputs to a tensor for advanced indexing.

As an example, it is annoying that `nonzero` returns a stacked tensor in PyTorch, it would have been better if it directly returned a tuple of tensors (as in numpy), for the same reasons as above (indexing).
This is specially annoying while we don't have full support for tensors with arbitrary-zero I it's dimensions, but that is coming soon.

**Comment by vadimkantorov** [comment]
(my usecase for stacked returned tensor is to create a grid in order to evaluate some function on an image, depending on spatial coordinates - happens in PDEs too)

**Comment by mruberry** [comment]
Closing this in favor of the more recent https://github.com/pytorch/pytorch/issues/50276.
