### ISSUE TITLE
I found a parameter redundancy problem in RNNCell, and this problem also occurs in other occasions.

### ISSUE THREAD

**Issue by itmorn** [pytorch/pytorch#95056]
### 🐛 Describe the bug

![1](https://user-images.githubusercontent.com/32835189/219613773-d5129a4c-5bdf-4e33-9349-58c0c50d5b89.png)
![2](https://user-images.githubusercontent.com/32835189/219613794-babb9221-ba87-4da1-b4b0-02207f9ccead.png)
In the red box, two parameter vectors are used, which increases the complexity of the model and the computational burden, but in fact, one parameter vector can be deleted. If we fix it, RNNCell can save **hidden_size** parameters. For RNN, we can save **hidden_size * num_layers * D** parameters.

### Versions

torch  1.13.1

**Comment by ngimel** [comment]
This was done for compatibility with cudnn APIs, in absolute terms, the memory savings are negligible compared to activations and weights (that are O(D*D), not O(D))

**Comment by itmorn** [comment]
thanks
