### ISSUE TITLE
A100 Perf Job artifact zipfiles unzip to generic folder that loses job information

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#95074]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/4984825/219733418-4359a47f-fcd0-4da2-b443-f5b856e794b5.png">

My use case is probably typical: i want to compare perf on my PR with perf on a baseline, so I may download 8 artifact zips.
* 4 zips per job (one per benchmark suite)
* 2 jobs (baseline and PR)

The first issue is that once i double click one of the downloaded zips, it generates a folder that has a generic name like `test-reports` or `test-reports2` etc.  Now when i'm working with the files I'm getting confused.

Luckily the .csv files inside the folders bear the name of the benchmark suite, but they do not bear the name of the PR or the baseline, so I can't actually tell what is what unless I am very careful to rename the `test-reports` folders as i unzip them.

It's probably a good idea to be as redundant as possible here, and put the info about the PR/job AND benchmark suite into both the unzipped folder AND csv filenames, just so no matter what workflow or scripts people write, the info is easy to find.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
cc @ZainRizvi

**Comment by PaliC** [comment]
likely fixed
