### ISSUE TITLE
Make artifacts easier to discover on HUD

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#95075]
## Feature request:

See description in https://github.com/pytorch/pytorch/issues/95075#issuecomment-1435171782

---

## Original request:

See this job run for reference.
https://github.com/pytorch/pytorch/actions/runs/4196727169

The main issues are
1) discoverability: 

i found it straightforward to identify the perf job and open it up, look for the 'upload' step of the job and read the logs.  I found filenames here, but was hoping for download URLs or some instructions about where to look for them.
<img width="1948" alt="image" src="https://user-images.githubusercontent.com/4984825/219737660-bee902a9-19da-47f8-93a8-9f4185401587.png">

2) When I assumed the artifacts are hosted in github (as opposed to S3 bucket or something), I still can't find them
* I followed this instruction: https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts
* But when I clicked around in the github UI I never saw the 'artifacts' pane, and assumed maybe we weren't using gh artifacts at all.
* The issue is that the artifacts pane renders below some warnings so it does not show up unless you scroll down.

Not sure what to do about this, but perhaps putting some message in the job log step saying where to look?  (or, if you can generate a download URL to throw in the log even better!) 

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
cc'ing @ZainRizvi

**Comment by janeyx99** [comment]
I do think that the HUD PR page (https://hud.pytorch.org/pr/94512) is much more useful for artifacts searching/naming (related to #95074) but there seems to be a lack of discoverability for that. From this, I think a useful action item may be to reroute people to the HUD PR link + add instructions for expanding the artifacts.

Generally, it'd be good to reroute people to the HUD PR view as much as possible if the GH UI remains unideal.

**Comment by huydhn** [comment]
+1 for the HUD usage.  On the other hand, the artifact link is at the top right if you are still looking for it on GitHub, and the list of GitHub artifacts is at the bottom https://github.com/pytorch/pytorch/actions/runs/4196727169#artifacts as part of the workflow summary.  GitHub artifacts will eventually be uploaded to S3 once the workflow finishes.

Also I notice that GitHub artifacts will only become available once the whole workflow finishes, not individual job which generates them (may be this is the issue you encounter)

**Comment by ZainRizvi** [comment]
HUD would prob be a lot more discoverable if we implemented https://github.com/pytorch/pytorch/issues/91320 to have the failing job links point to HUD instead of to the Github Action Runs page

**Comment by ZainRizvi** [comment]
Capturing one more idea to also make artifacts more prominent on HUD:

Show the artifacts under the job if (and only if) the job failed
![image](https://user-images.githubusercontent.com/4468967/219780048-7192149b-7749-45d8-a5f7-2629eec8eb41.png)

**Comment by wconstab** [comment]
Btw, I am not sure if I am missing something, but now that I know about the HUD having artifacts, and I am doing my second round of measuring perf on this PR, I am unable to find the particular artifacts i'm looking for:

1. The PR ([#95248](https://github.com/pytorch/pytorch/pull/95248)), 
2. The GH actions page where the artifacts _are_ found: ([link](https://github.com/pytorch/pytorch/actions/runs/4249923945))
3. the name of one artifact for example "[test-reports-runattempt1-test-inductor_huggingface_perf-1-1-linux.gcp.a100_11540342091.zip](https://github.com/pytorch/pytorch/suites/11151646209/artifacts/569227843)"
4. The HUD page for my PR, where I thought I should find the artifacts: https://hud.pytorch.org/pr/95248
5. The part of the HUD page where I expected the artifacts: <img width="855" alt="image" src="https://user-images.githubusercontent.com/4984825/220941681-dc931c56-8433-4644-b704-b88f1bca39e7.png">

**Comment by huydhn** [comment]
Let me take a look into this.  Normally, GitHub artifacts would be uploaded to S3 after the workflow finishes.  The artifacts are there on GitHub.  Inductor workflow has some artifacts from `gcp.a100`.  So this looks like a bug on the CI.

**Comment by huydhn** [comment]
Got a fix for the missing artifacts in https://github.com/pytorch/pytorch/pull/95401.  As GPC A100 doesn't have direct access to S3 AFAIK.  The artifacts are uploaded post hoc to S3 in `.github/workflows/upload-test-stats.yml` similar to other runners with the same limit (macos, rocm)

**Comment by clee2000** [comment]
This seems like a combination of https://github.com/pytorch/test-infra/issues/609 (which is completed) and https://github.com/pytorch/test-infra/issues/3492, so I will close this in favor of those.
