### ISSUE TITLE
AOTAutograd can add extra as_strided() calls when graph outputs alias inputs

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#95103]
A simple example:

```
import torch

@torch.compile(backend="aot_eager")
def f(x):
    return x.unsqueeze(-1)

a = torch.ones(4)
b = a.view(2, 2)
out = f(b)
```

If you put a breakpoint at [this line](https://github.com/pytorch/pytorch/blob/c16b2916f15d7160c0254580f18007eb0c373abc/torch/_functorch/aot_autograd.py#L498) of aot_autograd.py, you'll see it getting hit.

Context: When AOTAutograd sees a graph with an output that aliases an input, it tries to "replay" the view on the input in eager mode, outside of the compiled `autograd.Function` object. It makes a best effort to replay the exact same set of views as the original code, but it isn't always able to.

The reason it can't in this case is because the input to the graph, `b`, is itself a view of another tensor, `a`. Morally, all we want to do is replay the call to `b.unsqueeze()`. Autograd has some view replay logic, but it requires us to replay *all* of the views from `out`'s base, including the views from the base (a) to the graph input (b). Since that view was created in eager mode, the view that autograd records is an as_strided, so we're forced to run an as_strided() call as part of view replay.

as_strided has a slower backward formula compared to most other view ops. If we want to optimize this, there are a few things that we can do:

(1) Wait for `view_strided()`: @dagitses is working on a compositional view_strided() op that we should be able to replace this as_strided() call with, that should have a more efficient backward formula

(2) make autograd's view replay API smarter (`_view_func`). What we could do is allow for you to do "partial view-replay". E.g. in the above example, if I ran `out._view_func(b)`, it would be nice if it just performed a single call to `.unsqueeze()` instead of needing to go through the entire view chain.

(3) Manually keep track of view chains in AOTAutograd. This would take more work, but in theory we could track all the metadata we need on exactly what the chain of view ops from an input to an output is during tracing, and manually replay it at runtime, instead of relying on autograd's view-replay.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @msaroufim @wconstab @anijain2305 @soumith @ngimel @davidberard98

**Comment by bdhirsh** [comment]
@albanD making `_view_func()` smarter seems like the easiest / quickest to get working of the options. Does it sound reasonable to you? If it does I can take a look at it.

**Comment by ezyang** [comment]
Personally, at this point I would probably just write a little function that can infer a sequence of view operations from a pre and post stride from as_strided. If you only allow permutes it's trivial; and even if you allow adding broadcast dims / collapsing dims together, it should still be feasible. IDK if @dagitses has already written one of these as part of stride agnostic.

**Comment by albanD** [comment]
From offline discussions: any option here is going to be quite tricky. So we should make sure it is worth doing before actually jumping on them.
In particular, there are cases where as_strided_backward is expected to be expensive (for example if it represents an expand, the backward will be a sum() which is non-trivial).

**Comment by bdhirsh** [comment]
This issue should be subsumed by https://github.com/pytorch/pytorch/issues/109237
