### ISSUE TITLE
`accept2run` label missing

### ISSUE THREAD

**Issue by qqaatw** [pytorch/pytorch#95114]
### 🐛 Describe the bug

The `Other` section in [Bot commands wiki](https://github.com/pytorch/pytorch/wiki/Bot-commands) states that one can add `accept2run` label to a PR. This label is missing in the label list of PyTorch repo.

### Versions

unrelated

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by janeyx99** [comment]
cc @ZainRizvi

**Comment by clee2000** [comment]
removed
