### ISSUE TITLE
`torch.linalg.matmul` and  `torch.Tensor.matmul` with `torch.bfloat16` return incorrect result

### ISSUE THREAD

**Issue by ILoveSE** [pytorch/pytorch#95125]
### 🐛 Describe the bug

`torch.linalg.matmul` and  `torch.Tensor.matmul` with `torch.bfloat16` can still run without mkldnn and return incorrect results, even in PyTorch 1.13.1 (the latest released docker environment)
This unexpected behavior is related to [#83863](https://github.com/pytorch/pytorch/issues/83863).

### To Reproduce
```python
import torch

def check_correctness(a, b, expected):
    for mkldnn_flag in [True, False]:
        with torch.backends.mkldnn.flags(enabled=mkldnn_flag):
            def test():
                tmp_result= torch.linalg.matmul(a, b)
                # tmp_result= torch.Tensor.matmul(a, b)
                return tmp_result
            c = test()
            assert(torch.all(c == expected)), "Incorrect result with\n" \
                                              f"torch.backends.mkldnn.flags(enabled={mkldnn_flag}),\n" \
                                              f"and dtypes: {a.dtype}, {b.dtype}, {c.dtype}\n" \
                                              f"expected: {expected}\n" \
                                              f"got: {c}\n"

val = 1024
a = torch.ones(val, val)
b = torch.ones(val, val)

check_correctness(a, b, expected=val)

a = a.to(torch.bfloat16)
b = b.to(torch.bfloat16)

check_correctness(a, b, expected=val)
```

The error result is
```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    check_correctness(a, b, expected=val)
  File "test.py", line 13, in check_correctness
    assert(torch.all(c == expected)), "Incorrect result with\n" \
AssertionError: Incorrect result with
torch.backends.mkldnn.flags(enabled=False),
and dtypes: torch.bfloat16, torch.bfloat16, torch.bfloat16
expected: 1024
got: tensor([[256., 256., 256.,  ..., 256., 256., 256.],
        [256., 256., 256.,  ..., 256., 256., 256.],
        [256., 256., 256.,  ..., 256., 256., 256.],
        ...,
        [256., 256., 256.,  ..., 256., 256., 256.],
        [256., 256., 256.,  ..., 256., 256., 256.],
```

### Expected behavior
Hopefully, this bug can be fixed, or disable `torch.bfloat16` matmul operations without mkldnn.

### Versions

docker pull command:
```
docker pull pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime
docker pull pytorch/pytorch:1.13.0-cuda11.6-cudnn8-runtime
docker pull pytorch/pytorch:latest
```

<details>
  <summary>pytorch 1.12.0 (from docker)</summary>
  <pre><code>
  [pip3] numpy==1.21.5
  [pip3] torch==1.12.0
  [pip3] torchelastic==0.2.0
  [pip3] torchtext==0.13.0
  [pip3] torchvision==0.13.0
  [conda] blas                      1.0                         mkl  
  [conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py37h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py37hd3c417c_0  
  [conda] mkl_random                1.2.2            py37h51133e4_0  
  [conda] numpy                     1.21.5           py37he7a7128_2  
  [conda] numpy-base                1.21.5           py37hf524024_2  
  [conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.0                    pypi_0    pypi
  [conda] torchtext                 0.13.0                     py37    pytorch
  [conda] torchvision               0.13.0               py37_cu113    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.12.0 (from docker)</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.0
  [pip3] torchtext==0.14.0
  [pip3] torchvision==0.14.0
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py39h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py39hd3c417c_0  
  [conda] mkl_random                1.2.2            py39h51133e4_0  
  [conda] numpy                     1.22.3           py39he7a7128_0  
  [conda] numpy-base                1.22.3           py39hf524024_0  
  [conda] pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchtext                 0.14.0                     py39    pytorch
  [conda] torchvision               0.14.0               py39_cu116    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.1 (latest, from docker)</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.1
  [pip3] torchelastic==0.2.2
  [pip3] torchtext==0.14.1
  [pip3] torchvision==0.14.1
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0           py310h7f8727e_0  
  [conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
  [conda] mkl_random                1.2.2           py310h00e6091_0  
  [conda] numpy                     1.22.3          py310hfa59a62_0  
  [conda] numpy-base                1.22.3          py310h9585f30_0  
  [conda] pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.2                    pypi_0    pypi
  [conda] torchtext                 0.14.1                    py310    pytorch
  [conda] torchvision               0.14.1              py310_cu116    pytorch/code></pre>
</details>

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by zhuhaozhe** [comment]
As mentioned in https://github.com/pytorch/pytorch/issues/83863. BF16 matmul without mkldnn with run with "reference path" which is pretty slow and inaccurate. Please use BF16 matmul with mkldnn support.

**Comment by ILoveSE** [comment]
> As mentioned in #83863. BF16 matmul without mkldnn will run with "reference path" which is pretty slow and inaccurate. Please use BF16 matmul with mkldnn support.

Thank you very much for your reply.
As a supplement, I want to ask: Will this 'slow and inaccurate' feature be clarified in `matmul`'s documentation in the future?(e.g., adding 'if you are using BF16 data, it is recommended to enable MKLdnn support' to the docs) 
Or, as an alternative, are there plans to directly disable BF16+CPUs in `matmul`?
