### ISSUE TITLE
[dynamo] import torch._dynamo error "module 'transformers' has no attribute 'configuration_utils'"

### ISSUE THREAD

**Issue by zejun-chen** [pytorch/pytorch#95131]
### 🐛 Describe the bug

Hi,

Here is a import error. I install the following env, while i got a error when importing torch._dynamo
torch                  2.0.0.dev20230218+cpu
torchaudio         2.0.0.dev20230218+cpu
torchvision         0.15.0.dev20230218+cpu

```
>>> import torch
>>> import torch._dynamo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/miniconda3/envs/zejun_L4/lib/python3.9/site-packages/torch/_dynamo/__init__.py", line 1, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/home/a/miniconda3/envs/zejun_L4/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 29, in <module>
    from .output_graph import OutputGraph
  File "/home/a/miniconda3/envs/zejun_L4/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 23, in <module>
    from . import config, logging as torchdynamo_logging, variables
  File "/home/a/miniconda3/envs/zejun_L4/lib/python3.9/site-packages/torch/_dynamo/variables/__init__.py", line 45, in <module>
    from .torch import TorchVariable
  File "/home/a/miniconda3/envs/zejun_L4/lib/python3.9/site-packages/torch/_dynamo/variables/torch.py", line 113, in <module>
    transformers.configuration_utils.PretrainedConfig.__eq__ = (
AttributeError: module 'transformers' has no attribute 'configuration_utils'
```

It looks like the package name has been changed ? Any comments ?
Thank you :)

### Versions

torch                  2.0.0.dev20230218+cpu
torchaudio         2.0.0.dev20230218+cpu
torchvision         0.15.0.dev20230218+cpu

Ubuntu 20.04
install command: pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

**Comment by zejun-chen** [comment]
`pip install transformers==4.20.1`

**Comment by eonu** [comment]
Hi @zejun-chen, is this the appropriate fix for this issue?

I don't see why installing `transformers` should be required in order to use `torch`, i.e. this seems like a bug.

Unless my understanding of the `torch._dynamo` package is wrong and it for some reason relies on `transformers`.

**Comment by mct-lrh** [comment]
> Hi @zejun-chen, is this the appropriate fix for this issue?
> 
> I don't see why installing `transformers` should be required in order to use `torch`, i.e. this seems like a bug.
> 
> Unless my understanding of the `torch._dynamo` package is wrong and it for some reason relies on `transformers`.

I guess it's required just for `dynamo`.  It's unfortunate, because `transformers` requires `torch`, making this a circular dependency.
