### ISSUE TITLE
[jit] support at::optional

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9513]
Currently we can't use `at::optional` in input argument of a native function. I am aware of some on-going work for this which plans to trace `None` numeric types as `nan`. IMO, this isn't ideal because:
1. `nan` is a perfect valid input, and we can't differentiate python input `None` from `math.nan`.
2. `nan` doesn't make sense for integral types.
3. what about other types like `at::optional<std::string>`?

**Comment by zou3519** [comment]
cc @wanchaol 

@SsnL the nan is a temporary stopgap. I believe the end state is indeed to support `at::optional` or something similar.

**Comment by wanchaol** [comment]
Yes ultimately we want to use at::optional to represent None, the nan solution is temporary in JIT/ATen to support the clamp use case.

**Comment by wanchaol** [comment]
I am working on this.

**Comment by SsnL** [comment]
@wanchaol Thanks! Assigning it to you!
