### ISSUE TITLE
Test binaries are not built with rpath to libnccl.so.1

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#9517]
Steps to reproduce:
1. Do a build
2. Try to run `build/bin/atest` or any other binary

Actual result: complains that libnccl.so.1 could not be found.

Workaround: prepend `LD_LIBRARY_PATH=$PWD/third_party/build/nccl/lib`

**Comment by ezyang** [comment]
@anderspapitto I remember you were fixing rpaths recently; is this fixed now?

**Comment by ngimel** [comment]
Closing due to age
