### ISSUE TITLE
Error: selected processor does not support `vudot.u8 q0,q9,d6[0]' in ARM mode

### ISSUE THREAD

**Issue by RiccaDS** [pytorch/pytorch#95171]
### 🐛 Describe the bug

I am trying to build PyTorch on Raspberry Pi 3 B (armv7l). After cloning, I run 
python setup.py build
Build stops

### Error logs

I guess the error is mainly this:
Error: selected processor does not support `vudot.u8 q0,q9,d6[0]' in ARM mode
present in many lines on different addresses. Excuse me I am pretty new to compilation so I am not really sure what we are talking about. I attach a complete output log from the command line.  
[log.log](https://github.com/pytorch/pytorch/files/10787477/log.log)

### Minified repro

Should I use this? sorry, newbie. 

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Raspbian GNU/Linux 11 (bullseye) (armv7l)
GCC version: (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
Clang version: Could not collect
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.2 (default, Mar 12 2021, 04:06:34)  [GCC 10.2.1 20210110] (32-bit runtime)
Python platform: Linux-5.15.84-v7+-armv7l-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     1200,0000
CPU min MHz:                     600,0000
BogoMIPS:                        76.80
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.5
[conda] No relevant packages

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by RiccaDS** [comment]
I didn't resolve the problem in itself. However my point was getting PyTorch installed on Raspberry Pi 3, and I found that pip offers a version for 64bit raspberry OS, which I installed and I finally got installed without too many hassles. If this proves helpful to someone.

**Comment by albanD** [comment]
I am then assuming that this is due to a 32-bit python runtime that was not detecting CPU capabilities properly.
Closing this for now.

cc @malfet as this is related to minimum CPU capabilities discussion.
