### ISSUE TITLE
Model loading fails on iOS: Unknown custom class type quantized.Conv2dPackedParamsBase

### ISSUE THREAD

**Issue by evekeen** [pytorch/pytorch#95175]
### 🐛 Describe the bug

Cannot load PyTorch-Mobile model on iOS:
```
ibc++abi: terminating with uncaught exception of type torch::jit::ErrorReport: 
Unknown custom class type quantized.Conv2dPackedParamsBase. Please ensure it is registered.:
quantized::conv1d(Tensor qx, __torch__.torch.classes.quantized.Conv2dPackedParamsBase packed_weight, float output_scale, int output_zero_point) -> Tensor
                                                               ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
```

### Versions

PyTorch version: 1.14.0.dev20221110
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.0
Libc version: N/A

Python version: 3.9.12 (main, Jun  1 2022, 06:34:44)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] numpydoc==1.2
[pip3] torch==1.14.0.dev20221110
[pip3] torchaudio==0.14.0.dev20221110
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.0.dev20221110
[conda] nomkl                     3.0                           0
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] numpydoc                  1.2                pyhd3eb1b0_0
[conda] torch                     1.14.0.dev20221110          pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221110          pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.15.0.dev20221110          pypi_0    pypi

**Comment by evekeen** [comment]
Pod versions:
```
  - LibTorch-Lite (1.13.0.1):
    - LibTorch-Lite/Core (= 1.13.0.1)
  - LibTorch-Lite/Core (1.13.0.1):
    - LibTorch-Lite/Torch
  - LibTorch-Lite/Torch (1.13.0.1)
```

**Comment by hadiidbouk** [comment]
I am facing the same error when I try to run my unit tests while I have `LibTorch-Lite` installed via Cocoapods:

```ruby
platform :ios, '16.0'

use_frameworks!

target 'MyApp' do
	pod 'LibTorch-Lite'

	target 'MyAppTests' do
		pod 'LibTorch-Lite'
	end
end

```
