### ISSUE TITLE
[PT2.0][compile] embedding scale_grad_by_freq=True causes broadcast error

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#95182]
### 🐛 Describe the bug

Please use below code to reproduce the error:
```
import torch


class BasicModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input_dict):
        return torch.nn.functional.embedding(**input_dict)


if __name__ == "__main__":
    input_dict = {
        "input": torch.tensor([[7, 2, 3, 4], [8, 4, 4, 7]]),
        "weight": torch.randn([10,3], dtype=torch.float16, requires_grad=True),
        "padding_idx": 1,
        "scale_grad_by_freq": True,
    }

    model = BasicModule()
    model = torch.compile(model)
    fwd_res = model(input_dict)
    print(fwd_res)

```

Error:
```
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: Attempting to broadcast a dimension of length 4 at -1! Mismatching argument at index 1 had torch.Size([2, 1, 4]); but expected shape should be broadcastable to [2, 4, 3]
```

Same graph works fine in eager exeuction

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230209+cpu
[pip3] torchaudio==2.0.0.dev20230209+cpu
[pip3] torchvision==0.15.0.dev20230209+cpu

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by bdhirsh** [comment]
Looks like a refs/prims issue, I can repro with the `aot_eager` backend but not with the `eager` backend.

**Comment by bdhirsh** [comment]
Tentative fix here: https://github.com/pytorch/pytorch/pull/95499

**Comment by jay746** [comment]
Thanks @bdhirsh , I have validated and it fixes the issue
