### ISSUE TITLE
ONNX Exporter for circular padding mode in convolution ops

### ISSUE THREAD

**Issue by yuanyao-nv** [pytorch/pytorch#95229]
### 🚀 The feature, motivation and pitch

Circular/wrap-around padding has recently been added to the Pad operator in ONNX opset 19:
https://github.com/onnx/onnx/blob/main/docs/Operators.md#Pad

When exporting convolution operators with `padding_mode` set to `circular`, one can directly make use of the new Pad operator instead of having to do concatenation.

**Comment by leimao** [comment]
Is this problem fixed?

**Comment by thiagocrepaldi** [comment]
torch.onnx.export doesn't imeplement opset 19 ops and there is no plan to support them as this API is in maintenance mode

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by yuanyao-nv** [comment]
@thiagocrepaldi I see that there are files for opset 19 and 20 [here](https://github.com/pytorch/pytorch/tree/main/torch/onnx). Are these being actively worked on or are they just placeholders?

**Comment by leimao** [comment]
> torch.onnx.export doesn't imeplement opset 19 ops and there is no plan to support them as this API is in maintenance mode
> 
> Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

Sounds like `torch.onnx.export` will be deprecated in the future?

**Comment by thiagocrepaldi** [comment]
> @thiagocrepaldi I see that there are files for opset 19 and 20 [here](https://github.com/pytorch/pytorch/tree/main/torch/onnx). Are these being actively worked on or are they just placeholders?

Some new ops might come to opset19 and 20, but not the full opset. We are investing more on torch.onnx.dyanmo_export lately

**Comment by thiagocrepaldi** [comment]
> > torch.onnx.export doesn't imeplement opset 19 ops and there is no plan to support them as this API is in maintenance mode
> > Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
> 
> Sounds like `torch.onnx.export` will be deprecated in the future?

right now we are kind of in a maintenance mode, but we don't have plans to remove this API anytime soon. We need dynamo to be more stable and feature compelte before we consider this move

**Comment by Mugutech62** [comment]
@thiagocrepaldi 
Can you please share me how to achieve wrap around padding in a pytorch model? what pytorch function is used to suppose in pad layer, how can we export pad layer with wrap mode from pytorch to onnx>
Thanks
