### ISSUE TITLE
file size of saved tensor generated by `torch.chunk`

### ISSUE THREAD

**Issue by jaesuny** [pytorch/pytorch#95278]
### 🐛 Describe the bug

When I save a tensor chunked by `chunk`, it is saved at the file size of the original tensor before it was chunked.

```python
import torch


d = torch.rand(10000)
v = torch.chunk(d, 10)

torch.save(d, "data.pt")
torch.save(v, "data_chunked.pt")

for i, e in enumerate(v):
    if i == 3:
        break
    torch.save(e, 'chunk_{}.pt'.format(i))
    torch.save(e.clone(), 'chunk_{}_clone.pt'.format(i))
```

As a result, files sizes of saved tensors are followings.
```
.rw-r--r-- user staff  40 KB Wed Feb 22 17:54:48 2023  chunk_0.pt
.rw-r--r-- user staff 4.6 KB Wed Feb 22 17:54:48 2023  chunk_0_clone.pt
.rw-r--r-- user staff  40 KB Wed Feb 22 17:54:48 2023  chunk_1.pt
.rw-r--r-- user staff 4.6 KB Wed Feb 22 17:54:48 2023  chunk_1_clone.pt
.rw-r--r-- user staff  40 KB Wed Feb 22 17:54:48 2023  chunk_2.pt
.rw-r--r-- user staff 4.6 KB Wed Feb 22 17:54:48 2023  chunk_2_clone.pt
.rw-r--r-- user staff  40 KB Wed Feb 22 17:54:48 2023  data.pt
.rw-r--r-- user staff  40 KB Wed Feb 22 17:54:48 2023  data_chunked.pt
```

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.9 (main, Jan 25 2022, 15:23:43)  [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-13.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.22.1
[pip3] torch==1.13.1
[pip3] torchvision==0.11.3
[conda] Could not collect

cc @mruberry

**Comment by vadimkantorov** [comment]
This is a known semantics peculiarity of torch.save intersected with view-generated inputs (like in your case): it saves separately the storage and storageoffsets.

I would say, this could be converted into a feature request for torch.save that would optimize for file size / drop the larger input tensor storages, without forcing the user to do clone and wasting memory on this clone.

**Comment by albanD** [comment]
This is indeed a known issue as discussed in https://github.com/pytorch/pytorch/issues/65604

**Comment by jaesuny** [comment]
Thanks!
