### ISSUE TITLE
`torch.logdet` return inconsistent results between Cuda and CPU. 

### ISSUE THREAD

**Issue by ILoveSE** [pytorch/pytorch#95281]
### 🐛 Describe the bug

When the value of the input is quite small (close to 0), the results calculated by `torch.logdet` will be completely different on Cuda and CPU.
Execute the following code in the PyTorch1.13.1 environment, and the result on Cuda will be:
```
[nan nan nan nan nan nan nan nan nan]
```

However, the result on CPU will be:
```
[-inf -inf -inf -inf -inf -inf -inf -inf -inf]
```

In addition, it is mentioned in the [documentation](https://pytorch.org/docs/stable/generated/torch.logdet.html?highlight=torch+logdet#torch.logdet) corresponding to `logdet`:
```
It returns -inf if the input has a determinant of zero, and NaN if it has a negative determinant.
```
Does this mean that in the above calculation, the input obtained by Cuda backend is a series of negative determinant, while the value obtained by CPU is close to 0?
Are there some implicit differences between these inputs on different backends?

### To Reproduce
```python
import torch
torch.manual_seed(0)

batch=9
# 8
# 2
# 1
func_cls=torch.logdet
A = torch.tensor([[1e-40, 1e-40], [1e-40, 1e-40]])


B = torch.tile(A, [batch,1,1])
# print(B)
x = func_cls(B).cpu().detach().numpy()

D = torch.tile(A, [batch,1,1]).cuda()
# print(D)
y = func_cls(D).cpu().detach().numpy()
print(f'Cuda result: {y}')
print(f'CPU result: {x}')
```

### Error Result.

I adjusted the `batch` value on multiple versions for multiple tests, and got interesting results.

1. In 1.12.0/1.13.0/1.13.1, batch=9
```
Cuda result: [nan nan nan nan nan nan nan nan nan]
CPU result: [-inf -inf -inf -inf -inf -inf -inf -inf -inf]
```
2. In 1.12.0, batch=8
```
Cuda result: [-inf -inf -inf -inf -inf -inf -inf -inf]
CPU result: [-inf -inf -inf -inf -inf -inf -inf -inf]
```
3. In 1.13.0/1.13.1, batch=8
```
Cuda result: [nan nan nan nan nan nan nan nan]
CPU result: [-inf -inf -inf -inf -inf -inf -inf -inf]
```
4. In 1.12.0, batch=2
```
Cuda result: [-inf -inf]
CPU result: [-inf -inf]
```
5. In 1.13.0/1.13.1, batch=2
```
Cuda result: [nan nan]
CPU result: [-inf -inf]
```
6. In 1.12.0, batch=1
```
Cuda result: [-inf]
CPU result: [-inf]
```
7. In 1.13.0/1.13.1, batch=1
```
Cuda result: [-inf]
CPU result: [-inf]
```

We can observe that in 1.13.0 and 1.13.1, the difference between the outputs on Cuda and CPU starts from batch≥2.
However, in 1.12.0, it starts from batch≥9.
I'm not sure if the root cause of the above behaviors is related to [#73622](https://github.com/pytorch/pytorch/issues/73622).

### Expected behavior

Perhaps this function should maintain the consistency of outputs on Cuda and CPU backends with different batch values, otherwise the explaination about input values in [documentation](https://pytorch.org/docs/stable/generated/torch.logdet.html?highlight=torch+logdet#torch.logdet) may confuse users with this unexpected behavior.
Or the docs could add a clearer description of the interesting output of such batch changes.

### Versions

<details>
  <summary>pytorch 1.12.0</summary>
  <pre><code>
  [pip3] numpy==1.21.5
  [pip3] torch==1.12.0
  [pip3] torchelastic==0.2.0
  [pip3] torchtext==0.13.0
  [pip3] torchvision==0.13.0
  [conda] blas                      1.0                         mkl  
  [conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py37h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py37hd3c417c_0  
  [conda] mkl_random                1.2.2            py37h51133e4_0  
  [conda] numpy                     1.21.5           py37he7a7128_2  
  [conda] numpy-base                1.21.5           py37hf524024_2  
  [conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.0                    pypi_0    pypi
  [conda] torchtext                 0.13.0                     py37    pytorch
  [conda] torchvision               0.13.0               py37_cu113    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.0</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.0
  [pip3] torchtext==0.14.0
  [pip3] torchvision==0.14.0
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py39h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py39hd3c417c_0  
  [conda] mkl_random                1.2.2            py39h51133e4_0  
  [conda] numpy                     1.22.3           py39he7a7128_0  
  [conda] numpy-base                1.22.3           py39hf524024_0  
  [conda] pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchtext                 0.14.0                     py39    pytorch
  [conda] torchvision               0.14.0               py39_cu116    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.1</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.1
  [pip3] torchelastic==0.2.2
  [pip3] torchtext==0.14.1
  [pip3] torchvision==0.14.1
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0           py310h7f8727e_0  
  [conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
  [conda] mkl_random                1.2.2           py310h00e6091_0  
  [conda] numpy                     1.22.3          py310hfa59a62_0  
  [conda] numpy-base                1.22.3          py310h9585f30_0  
  [conda] pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.2                    pypi_0    pypi
  [conda] torchtext                 0.14.1                    py310    pytorch
  [conda] torchvision               0.14.1              py310_cu116    pytorch</code></pre>
</details>

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment]
Alas, this is expected. See https://pytorch.org/docs/master/notes/numerical_accuracy.html#extremal-values-in-linalg

Note that `logdet` is not differentiable at singular matrices.

**Comment by ILoveSE** [comment]
> Alas, this is expected. See https://pytorch.org/docs/master/notes/numerical_accuracy.html#extremal-values-in-linalg
> 
> Note that `logdet` is not differentiable at singular matrices.

Thank you very much for your explanation! Now I understand the reason for this interesting behavior.
