### ISSUE TITLE
torch.onnx export Segmentation fault

### ISSUE THREAD

**Issue by fancyerii** [pytorch/pytorch#9528]
I trained a simple linear regression model and wanted to export it using onnx. 
import torch.onnx
input = Variable(torch.zeros(1, 1, dtype=torch.float))
model_path="/home/lili/lr.onnx"
torch.onnx.export(model, input, model_path) 

the last line exit with: "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"
full codes can be found here: https://gist.github.com/fancyerii/0287893fa1d23c100449a19d3640f88c

## System Info
$ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: Quadro P3000
Nvidia driver version: 390.48
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so
/usr/local/cuda-8.0/lib64/libcudnn.so.6
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a
/usr/local/cuda-9.1/lib64/libcudnn.so
/usr/local/cuda-9.1/lib64/libcudnn.so.7
/usr/local/cuda-9.1/lib64/libcudnn.so.7.1.2
/usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.5)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by caogang** [comment]
The same error : torch.onnx export Segmentation fault. 

PyTorch version: 0.4.1

**Comment by Sucran** [comment]
The same error: torch.onnx export Segmentation fault.

PyTorch version: 0.4.1
CUDA version: 8.0
