### ISSUE TITLE
torch.compile(model, backend="inductor") not working

### ISSUE THREAD

**Issue by mariecwhite** [pytorch/pytorch#95348]
### 🐛 Describe the bug

`torch.compile()` or `dynamo.optimize("inductor")(model)` doesn't seem to work on my pretrained model (bert-base-uncased from HuggingFace). When enabled, the GPU latency does not change.

### Error logs

No errors

### Minified repro

```
git clone https://github.com/mariecwhite/torch.git
cd torch

bash setup_venv.sh
source torch.venv/bin/activate

python3 torch_inductor_test.py
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230220+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.25.2
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1018-gcp-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 515.43.04
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        7
BogoMIPS:                        4400.42
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        6 MiB (6 instances)
L3 cache:                        38.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] pytorch-triton==2.0.0+c8bfe3f548
[pip3] torch==2.0.0.dev20230220+cu117
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ZailiWang** [comment]
Hi, would you try to diagnose with approaches in https://pytorch.org/docs/master/dynamo/troubleshooting.html
For your specific case, I think you can first try torch._dynamo.explain() to check if the graph is generated as expected rather than breaking into many subgraphs.
An example of usage is https://pytorch.org/docs/master/dynamo/troubleshooting.html#identifying-the-cause-of-a-graph-break
but please note in latest nightly versions dynamo.explain() has extended returning elements to 6.

**Comment by ZailiWang** [comment]
In addition, you should call torch.cuda.synchronize( ) to get an accurate time cost for GPU inference.

**Comment by bdhirsh** [comment]
for what it's worth _ i added the synchronize calls, and I still don't see much of a speedup. I used `torch._dynamo.explain()` to see that there's only one graph break (see a basic usage of that API [here](https://pytorch.org/tutorials/intermediate/dynamo_tutorial.html#torchdynamo-and-fx-graphs))


I also ran with `TORCH_COMPILE_DEBUG=1 python repro.py` to get a rough idea of what the inductor output is, and in the output_code.py file I see a pretty large number of individual triton kernels getting called.

Not sure that this immediately points to an inductor problem, but it might be worth investigating some more.

**Comment by mariecwhite** [comment]
Thanks for taking a look at it @bdhirsh. I ran this model with TorchInductor a few months ago and was seeing 2.1ms latencies when timed from the Python layer. Now it's ~14ms using the same hardware.

Are you seeing similar latencies with and without Inductor? If so, and if Inductor kernels are being called when enabled, this looks to be a regression.

**Comment by mariecwhite** [comment]
Hi Folks, after updating to the latest nightly and adding the `mode="max-autotune"` flag, I'm getting the expected ~2.7ms latency. This was crashing in the previous release.

**Comment by Chillee** [comment]
It sounds like the issue is resolved? Unless previously you didn't need `mode="max-autotune"` to get 2.7ms latency? Btw, just another idea, is it perhaps an overhead issue? Perhaps if you try `mode='reduce-overhead'` that'll also perform well.

Feel free to reopen if you need more help.
