### ISSUE TITLE
`torch.Tensor.aminmax` crash with `INTERNAL ASSERT FAILED` when input's shape contains 0

### ISSUE THREAD

**Issue by ILoveSE** [pytorch/pytorch#95349]
### 🐛 Describe the bug

When `torch.Tensor.aminmax` recieves an empty input tensor on cuda, it will crash with `INTERNAL ASSERT FAILED`.
However, the same code can run well on CPU device and return:
```
torch.return_types.aminmax(
min=tensor([]),
max=tensor([]))
```

This unexpected behavior occurs on PyTorch 1.11.0\1.12.0\1.13.0\1.13.1, and even in the nightly version(2.0.0.dev20230219).
It should be related to [#85439](https://github.com/pytorch/pytorch/issues/85439)

### To Reproduce
```python
import torch

def test(input):
    return torch.Tensor.aminmax(input,dim=0)

# device = "cpu"
device = "cuda"
input = torch.ones([10, 0], dtype=torch.float32)
x=test(input.to(device))
print(x)
```

The error result is
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    x=test(input.to(device))
  File "test.py", line 4, in test
    return torch.Tensor.aminmax(input,dim=0)
RuntimeError: iter.numel() > 0 && iter.ntensors() - iter.noutputs() == 1 && iter.noutputs() >= 1 INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/Reduce.cuh":1134, please report a bug to PyTorch.
```

### Expected behavior
I hope this function could maintain consistent behavior on CPU and Cuda (e.g., fix crash behavior on Cuda).

### Versions

<details>
  <summary>pytorch 1.12.0</summary>
  <pre><code>
  [pip3] numpy==1.21.5
  [pip3] torch==1.12.0
  [pip3] torchelastic==0.2.0
  [pip3] torchtext==0.13.0
  [pip3] torchvision==0.13.0
  [conda] blas                      1.0                         mkl  
  [conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py37h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py37hd3c417c_0  
  [conda] mkl_random                1.2.2            py37h51133e4_0  
  [conda] numpy                     1.21.5           py37he7a7128_2  
  [conda] numpy-base                1.21.5           py37hf524024_2  
  [conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.0                    pypi_0    pypi
  [conda] torchtext                 0.13.0                     py37    pytorch
  [conda] torchvision               0.13.0               py37_cu113    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.0</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.0
  [pip3] torchtext==0.14.0
  [pip3] torchvision==0.14.0
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py39h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py39hd3c417c_0  
  [conda] mkl_random                1.2.2            py39h51133e4_0  
  [conda] numpy                     1.22.3           py39he7a7128_0  
  [conda] numpy-base                1.22.3           py39hf524024_0  
  [conda] pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchtext                 0.14.0                     py39    pytorch
  [conda] torchvision               0.14.0               py39_cu116    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.1</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.1
  [pip3] torchelastic==0.2.2
  [pip3] torchtext==0.14.1
  [pip3] torchvision==0.14.1
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0           py310h7f8727e_0  
  [conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
  [conda] mkl_random                1.2.2           py310h00e6091_0  
  [conda] numpy                     1.22.3          py310hfa59a62_0  
  [conda] numpy-base                1.22.3          py310h9585f30_0  
  [conda] pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.2                    pypi_0    pypi
  [conda] torchtext                 0.14.1                    py310    pytorch
  [conda] torchvision               0.14.1              py310_cu116    pytorch</code></pre>
</details>

<details>
  <summary>pytorch nightly</summary>
  <pre><code>
  [pip3] numpy==1.11.3
  [pip3] torch==2.0.0.dev20230219
  [pip3] torchaudio==2.0.0.dev20230219
  [pip3] torchvision==0.15.0.dev20230219
  [conda] blas                      1.0                         mkl  
  [conda] mkl                       2020.2                      256  
  [conda] mkl-service               2.3.0            py38he904b0f_0  
  [conda] numpy                     1.11.3          py38h7e9f1db_12  
  [conda] numpy-base                1.11.3          py38hde5b4d6_12  
  [conda] pytorch                   2.0.0.dev20230219 py3.8_cuda11.7_cudnn8.5.0_0    pytorch-nightly
  [conda] pytorch-cuda              11.7                 h778d358_3    pytorch-nightly
  [conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
  [conda] torchaudio                2.0.0.dev20230219      py38_cu117    pytorch-nightly
  [conda] torchtriton               2.0.0+c8bfe3f548            py38    pytorch-nightly
  [conda] torchvision               0.15.0.dev20230219      py38_cu117    pytorch-nightly</code></pre>
</details>

cc @ngimel

**Comment by ngimel** [comment]
It shouldn't error, it should return 0 element tensor, CPU behavior is correct.

**Comment by ILoveSE** [comment]
> It shouldn't error, it should return 0 element tensor, CPU behavior is correct (patch will be appreciated @ILoveSE )

Thank you very much for your reply. I would like to do this and I will find time to submit a patch later  :-)
