### ISSUE TITLE
but torch.cuda.is_available() is False.

### ISSUE THREAD

**Issue by ChangliangSun** [pytorch/pytorch#9535]
Very strange error. I compiled the pytorch by source. It can import success. But when I run my video_test.py. I got an error.
My platform is Nvidia TX2
![_20180718225336](https://user-images.githubusercontent.com/33341284/42889916-13c6bbda-8ade-11e8-90d0-9ebc33dfb069.jpg)

**Comment by soumith** [comment]
please use our issue template. There's no information in this issue.

**Comment by soumith** [comment]
is this master branch, or did you use a versioned branch?

**Comment by ChangliangSun** [comment]
Yes, It is the master branch. The error log reminder me that Cuda is not available. But if I run `torch.cuda.is_available()`, It shows True.

**Comment by ChangliangSun** [comment]
Sorry, I made a mistake.
