### ISSUE TITLE
isGenericDict()INTERNAL ASSERT FAILED at \"C:\\\\w\\\\b\\\\windows\\\\pytorch\\\\aten\\\\src\\\\ATen/core/ivalue_inl.h\":1392, please report a bug to PyTorch. Expected GenericDict but got None

### ISSUE THREAD

**Issue by swilson314** [pytorch/pytorch#95362]
### 🐛 Describe the bug

I'm trying to move a state_dict from python to c++ per the following code and pickle_load() fails with an error requesting that I report the bug. I've attached the zipped version of ScriptUntrained_LibTorchTest03Cmb.ptsd.

Python
`
torch.save(model.state_dict(), Folder + 'ScriptUntrained_LibTorchTest03Cmb.ptsd')
`

C++
```
std::vector<char> get_the_bytes(const std::string& filename)
{
	std::ifstream input(filename, std::ios::binary);
	std::vector<char> bytes((std::istreambuf_iterator<char>(input)), (std::istreambuf_iterator<char>()));
	input.close();
	return bytes;
}

	auto bytes = get_the_bytes(Folder + "ScriptUntrained_LibTorchTest03Cmb.ptsd");
	// pytorch 1.10.2 and 1.13 (pytorch110 and Anaconda 2021.05)
	// "isGenericDict()INTERNAL ASSERT FAILED at \"C:\\\\w\\\\b\\\\windows\\\\pytorch\\\\aten\\\\src\\\\ATen/core/ivalue_inl.h\":1392, please report a bug to PyTorch. Expected GenericDict but got None"
	auto Dict = torch::pickle_load(bytes);
```

[ScriptUntrained_LibTorchTest03Cmb.zip](https://github.com/pytorch/pytorch/files/10810407/ScriptUntrained_LibTorchTest03Cmb.zip)

### Versions

libtorch-win-shared-with-deps-1.10.2+cu113

(base) F:\Dev\LibTorch\pytorch\torch\utils>python collect_env.py
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows Server 2019 Standard
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.17763-SP0
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration:
GPU 0: Tesla V100S-PCIE-32GB
GPU 1: Tesla V100S-PCIE-32GB
GPU 2: Tesla V100S-PCIE-32GB
GPU 3: Tesla V100S-PCIE-32GB

Nvidia driver version: 516.94
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torchinfo==1.7.1
[pip3] torchvision==0.14.0
[conda] blas 1.0 mkl
[conda] mkl 2021.2.0 haa95532_296
[conda] mkl-service 2.3.0 py38h2bbff1b_1
[conda] mkl_fft 1.3.0 py38h277e83a_2
[conda] mkl_random 1.2.1 py38hf11a4ad_2
[conda] mypy_extensions 0.4.3 py38_0
[conda] numpy 1.20.1 py38h34a8a5c_0
[conda] numpy-base 1.20.1 py38haf7ebc8_0
[conda] numpydoc 1.1.0 pyhd3eb1b0_1
[conda] pytorch 1.13.0 py3.8_cuda11.6_cudnn8_0 pytorch
[conda] pytorch-cuda 11.6 h867d48c_0 pytorch
[conda] pytorch-mutex 1.0 cuda pytorch
[conda] torchaudio 0.13.0 pypi_0 pypi
[conda] torchinfo 1.7.1 pyhd8ed1ab_0 conda-forge
[conda] torchvision 0.14.0 pypi_0 pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser @mruberry @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by swilson314** [comment]
May be related to this bug: https://github.com/pytorch/pytorch/issues/92560#issue-1538443073

**Comment by ezyang** [comment]
Do you know if this happens on Linux?

**Comment by swilson314** [comment]
Sorry, I don't know. I don't have a linux installation for testing.

**Comment by swilson314** [comment]
I just saw this and will try it. https://github.com/pytorch/pytorch/issues/36577#issuecomment-1450163197

**Comment by swilson314** [comment]
This was indeed fixed by saving as a python dict, rather than a state-dict:

```
w = {k: v for k, v in model.state_dict().items()}
torch.save(w, Folder + 'ScriptUntrained_LibTorchTest03Cmb.ptsd')

```
