### ISSUE TITLE
`torch.sparse.log_softmax` crash with `Floating point exception (core dumped)` in PyTorch 1.12.0

### ISSUE THREAD

**Issue by ILoveSE** [pytorch/pytorch#95371]
### 🐛 Describe the bug

In PyTorch 1.12.0, `torch.sparse.log_softmax` will crash directly with the specific input on Cuda device , without any valid error message returned.
Similar problems also occur in 1.11.0 or earlier versions.
The root cause seems to be similar to [#82107](https://github.com/pytorch/pytorch/issues/82107)

### To Reproduce
```python
import torch
input=torch.sparse_coo_tensor([[]], [], (3,), device='cuda')
def test():
    result=torch.sparse.log_softmax(input,0)
    return result
print(test())
```

The error result is 
```
Floating point exception (core dumped)
```

### Expected behavior

Not crash, return empty tensor or print error message.

### Versions

<details>
  <summary>pytorch 1.11.0</summary>
  <pre><code>
  [pip3] numpy==1.21.6
  [pip3] pytorch-lightning==1.6.3
  [pip3] torch==1.11.0
  [pip3] torch-tb-profiler==0.4.0
  [pip3] torchaudio==0.11.0
  [pip3] torchmetrics==0.9.0
  [pip3] torchvision==0.12.0
  [conda] blas                      1.0                         mkl  
  [conda] cudatoolkit               11.3.1               h2bc3f7f_2  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py38h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py38hd3c417c_0  
  [conda] mkl_random                1.2.2            py38h51133e4_0  
  [conda] numpy                     1.19.5                   pypi_0    pypi
  [conda] numpy-base                1.21.5           py38hf524024_1  
  [conda] pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
  [conda] pytorch-lightning         1.6.3                    pypi_0    pypi
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torch                     1.10.0                   pypi_0    pypi
  [conda] torch-tb-profiler         0.4.0                    pypi_0    pypi
  [conda] torchaudio                0.11.0               py38_cu113    pytorch
  [conda] torchmetrics              0.9.0                    pypi_0    pypi
  [conda] torchvision               0.12.0               py38_cu113    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.12.0</summary>
  <pre><code>
  [pip3] numpy==1.21.5
  [pip3] torch==1.12.0
  [pip3] torchelastic==0.2.0
  [pip3] torchtext==0.13.0
  [pip3] torchvision==0.13.0
  [conda] blas                      1.0                         mkl  
  [conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py37h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py37hd3c417c_0  
  [conda] mkl_random                1.2.2            py37h51133e4_0  
  [conda] numpy                     1.21.5           py37he7a7128_2  
  [conda] numpy-base                1.21.5           py37hf524024_2  
  [conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.0                    pypi_0    pypi
  [conda] torchtext                 0.13.0                     py37    pytorch
  [conda] torchvision               0.13.0               py37_cu113    pytorch</code></pre>
</details>

cc @ezyang @gchanan @zou3519 @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @ngimel

**Comment by ezyang** [comment]
Someone forgot to guard a division for zero numel case. Patch should be easy, I can help review.

**Comment by amjames** [comment]
It appears that this was fixed with @cpuhrsch 's fix for #82107. The discussion there mentions that the backward is vulnerable to the same problem. This does not appear to be true. Adding a variant of  https://github.com/pytorch/pytorch/blob/32558910f3887c3cf8a78cfe2f16c0a039f4a035/test/test_sparse.py#L3501 for `log_softmax` and extending both to test the derivative does not cause any errors or a crash. 

I can submit a PR with the expanded tests as this is a hole in our coverage, but I believe that this issue and #82107 can be closed as the problematic behavior is no longer present.

**Comment by amjames** [comment]
I must not have tagged the PR correctly, but closing via #95646.

**Comment by Jup11ter** [comment]
@amjames Thank you very much for your effort!  I have seen this fix pr.

**Comment by ILoveSE** [comment]
@amjames Thank you very much for your effort! I have seen this pr.
