### ISSUE TITLE
SWA AveragedModel saving issue: avg_fn is unpickable

### ISSUE THREAD

**Issue by okbalefthanded** [pytorch/pytorch#95376]
### 🐛 Describe the bug

Hi,
I've encountered a ```AttributeError: Can't pickle local object 'AveragedModel.__init__.<locals>.avg_fn' ``` issue while using the ```torch.optim.swa_utils.AveragedModel```, the error is raised at the call of ```torch.save()``` for model saving.

here's a small notebook for reproducing the issue:
https://colab.research.google.com/drive/1bs04ahdxVjoW2s3Kbmc5IA3S3i2UKSQD?usp=sharing

PS: the same behavior was seen on a win7 PC with python 3.7.6 and torch 1.13 cpu versions. 

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.6
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                        0
CPU MHz:                         2199.998
BogoMIPS:                        4399.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        55 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.1+cu116
[pip3] torchaudio==0.13.1+cu116
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by llinauer** [comment]
Hey,
I think the problem is not that you cannot pickle a function (which you should be able to in python 3.8.10) but the local definition of avg_fn inside the __init__ (https://github.com/pytorch/pytorch/blob/master/torch/optim/swa_utils.py#L110)
This is also reflected in the error message: "Can't pickle local object …"

If so (and I may be mistaken), my proposed solution would be to define the default avg_fn outside the AveragedModel class (or somewhere else for that matter) and not locally.

**Comment by janeyx99** [comment]
@llinauer happy to review a PR with your proposed solution (it looks to not at all be mutually exclusive from @ezyang's!) along with a test case showing that it would now be pickleable (similar to `test_cycle_lr_state_dict_picklable` in test_optim.py).

**Comment by okbalefthanded** [comment]
> Hey, I think the problem is not that you cannot pickle a function (which you should be able to in python 3.8.10) but the local definition of avg_fn inside the **init** (https://github.com/pytorch/pytorch/blob/master/torch/optim/swa_utils.py#L110) This is also reflected in the error message: "Can't pickle local object …"
> 
> If so (and I may be mistaken), my proposed solution would be to define the default avg_fn outside the AveragedModel class (or somewhere else for that matter) and not locally.

As a quick hack I'de taken the definition of the avg_fn outside the class. this fix I think breaks the API.

**Comment by code-mj12** [comment]
Putting the avg_fn function outside the class might fix the issue
