### ISSUE TITLE
Investigate/add Windows Arm64 support for cpuinfo

### ISSUE THREAD

**Issue by iremyux** [pytorch/pytorch#95380]
pytorch/cpuinfo arm64 support should be investigated and added if not already present.

- [ ] Support for M1 and M2 needs to be merged to pytorch/cpuinfo

A PR to pytorch/pytorch (updating cpuinfo submodule) will be created after the tasks are completed.

**Comment by ezyang** [comment]
why Windows?

**Comment by Blackhex** [comment]
@ezyang Can you please explain a bit what is your qestion about?

**Comment by ezyang** [comment]
thanks, title rename resolves it

**Comment by iremyux** [comment]
Closing this issue since third_party/cpuinfo seems to be updated and covers all changes regarding Windows Arm64.
