### ISSUE TITLE
Add log highlights to Dr. CI's failed jobs

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#95394]
When a job fails, the Dr CI message should call out the specific log lines that show the failure, showing the text that HUD shows today:

![Image](https://user-images.githubusercontent.com/4468967/221003507-23c99dd9-4bf7-4c9d-89a5-e6530c14d98d.png)
(The old Dr CI had a similar feature)

Expected benefits:
- Devs can see the exact failure faster
- Devs are less likely to incorrectly assume that a failure is unrelated based just on the job name

Feature inspired by https://github.com/pytorch/pytorch/pull/95232#issuecomment-1442089616

**Comment by clee2000** [comment]
Added in https://github.com/pytorch/test-infra/pull/4809
