### ISSUE TITLE
tensor __setitem__ incorrect on mps when dtypes mismatch

### ISSUE THREAD

**Issue by hchau630** [pytorch/pytorch#95417]
### 🐛 Describe the bug

On my M1 Macbook, `torch.Tensor.__setitem__` yields incorrect result when using mps and when the dtype of the assigned elements is not the same as the dtype of the tensor on which `__setitem__` is called.
```
import torch

device = torch.device('mps')

t = torch.zeros(5, device=device)
u = torch.ones(2, device=device).long()
t[2:4] = u
print(t)
```
Output:
```tensor([1., 1., 0., 0., 0.], device='mps:0')```

Expected:
```tensor([0., 0., 1., 1., 0.], device='mps:0')```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 (main, Oct 13 2022, 16:12:19)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.6.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.1
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
```

cc @nairbv @mruberry @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by hchau630** [comment]
this still seems to be a problem in 2.0.0 (though it works in the latest nightly build), even though the fix is merged into the main branch 3 weeks ago. Is it to be expected? @ezyang

**Comment by ezyang** [comment]
no it didn't make it into 2.0.0. I have proposed it for inclusion in 2.0.1.
