### ISSUE TITLE
Wrong type hint in `Module.register_full_backward_hook`

### ISSUE THREAD

**Issue by ValerianRey** [pytorch/pytorch#95422]
### 📚 The doc issue

Link to the method's docstring: https://pytorch.org/docs/stable/_modules/torch/nn/modules/module.html#Module.register_full_backward_hook

In the method definition, hook is defined as: 
```python
hook: Callable[['Module', _grad_t, _grad_t], Union[None, Tensor]]
```
i.e. the return type of the hook to register should be `Union[None, Tensor]`

But then in the documentation it says: 

> The hook should have the following signature::
hook(module, grad_input, grad_output) -> tuple(Tensor) or None

If I make a hook that returns a simple Tensor, I get an exception, but if I make a hook that returns a tuple of tensors it works, so I guess that the documentation is right and the type hint is wrong.

### Suggest a potential alternative/fix

Change
```python
hook: Callable[['Module', _grad_t, _grad_t], Union[None, Tensor]]
```
to
```python
hook: Callable[['Module', _grad_t, _grad_t], Union[None, Tuple[Tensor, ...]]]
```
in the method's definition.

cc @albanD @mruberry @jbschlosser @walterddr @saketh-are

**Comment by albanD** [comment]
Thanks for the report. I think this was already fixed on master: https://pytorch.org/docs/master/_modules/torch/nn/modules/module.html#Module.register_full_backward_hook
