### ISSUE TITLE
Bug generating block_size characters when using MPS

### ISSUE THREAD

**Issue by MarcMV** [pytorch/pytorch#95448]
### 🐛 Describe the bug

When running the [following code](https://github.com/karpathy/ng-video-lecture/blob/master/gpt.py ) using MPS...

Be sure to replace 
"device = 'cuda' if torch.cuda.is_available() else 'cpu'" 
for 
"device = 'mps' if torch.backends.mps.is_available() else 'cpu'"

and download [the text input file](https://github.com/karpathy/ng-video-lecture/blob/master/input.txt)

...it bugs after generating block_size characters. 

**Expected results** 
It generates as much text as you asked it to, in the linked example its asking for 500 characters `max_new_tokens=500`

**Actual results:** 
Regardless of how much you ask - it bugs after 256 characters and starts creating gibberish

<img width="813" alt="Screenshot 2023-02-23 at 9 43 12 PM" src="https://user-images.githubusercontent.com/42256287/221101390-6e4924eb-0089-46ba-886b-37502b684a32.png">

I've tested the exact code with cuda AND cpu, in both cases it works as expected. 

### Versions

[pip3] numpy==1.23.2
[pip3] torch==1.13.1
[pip3] torchaudio==2.0.0.dev20230212
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by Ronian526** [comment]
Could you please try PyTorch nightly (2.0.0.dev20230228)? This should be fixed in that build.

**Comment by MarcMV** [comment]
Thanks @Ronian526 , trying `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu` is saying I'm already updated. Should I be calling something different?

**Comment by kulinseth** [comment]
Can you check what’s the ‘pip list’ if not you may have to force reinstall it

**Comment by kulinseth** [comment]
@MarcMV , I tried with latest Nightly and [MacOS 13.3 Beta](https://developer.apple.com/news/releases/?id=02282023c) and this is the output I got:

```
10.788929 M parameters
step 0: train loss 4.2221, val loss 4.2315
step 500: train loss 1.7884, val loss 1.9224
step 1000: train loss 1.4098, val loss 1.6189
step 1500: train loss 1.2741, val loss 1.5291
step 2000: train loss 1.1970, val loss 1.5006
step 2500: train loss 1.1319, val loss 1.4825
step 3000: train loss 1.0753, val loss 1.4858
step 3500: train loss 1.0232, val loss 1.5002
step 4000: train loss 0.9695, val loss 1.5175
step 4500: train loss 0.9151, val loss 1.5360
step 4999: train loss 0.8649, val loss 1.5746

ell things, never aught to repution like corion of flyings: now 'tis fit thought, with the lives from deep becad it.

KING RICHARD III: Westerate, you the loss and men on dark doth our feeding and means, you may prove with the life: I being quarrelmenting have left thee so good men feel And met these words are purposed intermorance.

CLARENCE: To without eventious work In blood-reved feeling delays, head on compoulate Thee will be touch. Then myself will assure to unto her heart; And, by disobed

```

**Comment by MarcMV** [comment]
Yes! Can confirm, solved using

[pip3] numpy==1.24.2
[pip3] torch==2.1.0.dev20230305
[pip3] torchaudio==2.0.0.dev20230305
[pip3] torchvision==0.15.0.dev20230305
[conda] Could not collect

<img width="538" alt="Screenshot 2023-03-05 at 7 10 14 PM" src="https://user-images.githubusercontent.com/42256287/223010851-11870a32-b198-43f7-9290-5b902f45dd95.png">
