### ISSUE TITLE
`topk` returned indices contain invalid values

### ISSUE THREAD

**Issue by shavarani** [pytorch/pytorch#95455]
### 🐛 Describe the bug

I found a problem in my code which lead to discovering this issue. The following snippet shows that the indices returned by `topk` contain invalid values.

```python 
import torch
a = torch.rand(size=[10, 212, 500000]).to('cuda:0')
p, i = a.topk(20, sorted=False, dim=-1)
print(i.max())
# prints tensor(2033619248, device='cuda:0')
# while I expect to receive something like tensor(499999, device='cuda:0')
```
This behaviour does not appear when the code is not on GPU.

```python
import torch
a = torch.rand(size=[10, 212, 500000])  # .to('cuda:0')
p, i = a.topk(20, sorted=False, dim=-1)
print(i.max())
# correctly prints tensor(499997)
```

As well, for smaller sizes of tensors even on GPU this behaviour vanishes.
```python
import torch
a = torch.rand(size=[2, 3, 500000]).to('cuda:0')
p, i = a.topk(20, sorted=False, dim=-1)
print(i.max())
# correctly prints tensor(498704, device='cuda:0')
```

### Versions

PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.7 (default, Feb  8 2021, 16:03:32)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 6GB
Nvidia driver version: 470.161.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU family:                      6
Model:                           60
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        3
CPU max MHz:                     3900.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7002.59
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        1 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Unknown: No mitigations
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] pytorch-lightning==1.2.5
[pip3] torch==1.13.1
[pip3] torch-struct==0.5
[pip3] torchdata==0.5.1
[pip3] torchmetrics==0.6.0
[pip3] torchtext==0.14.0
[pip3] torchviz==0.0.1
[conda] No relevant packages

**Comment by ngimel** [comment]
Can't repro on master/A100. cc @zasdfgbnm

**Comment by ptrblck** [comment]
The issue is reproducible in `1.13.1` and `compute-sanitizer` shows the same invalid memory access as reported in https://github.com/pytorch/pytorch/issues/93006:
```
========= COMPUTE-SANITIZER
========= Invalid __global__ read of size 4 bytes
=========     at 0x8d0 in void at::native::mbtopk::gatherTopK<float, unsigned int, (int)2>(at::cuda::detail::TensorInfo<T1, T2>, T2, T2, bool, unsigned int, T2, at::cuda::detail::TensorInfo<T1, T2>, T2, at::cuda::detail::TensorInfo<long, T2>, T2, unsigned int, unsigned int, T1 *, unsigned int *, unsigned int *)
=========     by thread (64,0,0) in block (245,1,0)
=========     Address 0x7fdad8f4c980 is out of bounds
=========     and is 1362497 bytes after the nearest allocation at 0x7fdad8dfff00 of size 64 bytes
```
@zasdfgbnm already fixed it in https://github.com/pytorch/pytorch/pull/93095 and I cannot reproduce the issue using the current nightly release or a master build as also reported by @ngimel.

@shavarani Could you update PyTorch to the latest nightly release as described [here](https://pytorch.org/get-started/locally/) and verify the fix, please?

**Comment by ngimel** [comment]
closing per @ptrblck's comment, please reopen if still an issue on master.

**Comment by shavarani** [comment]
Thanks @ptrblck, I confirm that installing the latest nightly release with the command `pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu117` fixes this issue. For anyone who wants to try this fix, the version that I have after installing the release is `2.0.0.dev20230226+cu117`.
