### ISSUE TITLE
hf_GPT2_large CPU inference shows random failure on CI

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#95474]
https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=inductor_torchbench_cpu

https://github.com/pytorch/pytorch/pull/95473 takes hf_GPT2_large off from the CI test, but it still needs investigation.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by williamwen42** [comment]
I don't see hf_GPT2_large being skipped anywhere in the code except for accuracy checks since the model is too large. Closing as fixed.
