### ISSUE TITLE
FakeTensor doesn't work with torch.Tensor subclass

### ISSUE THREAD

**Issue by kumpera** [pytorch/pytorch#95496]
### 🐛 Describe the bug

I'm trying to run under FakeTensorMode and it fails when I try to create a tensor subclass.

This requires master PT:

```python
import torch
import torch.distributed._functional_collectives as ft_c
from torch.testing._internal.common_distributed import spawn_threads_and_init_comms,
from torch._subclasses.fake_tensor import FakeTensorMode

@spawn_threads_and_init_comms(world_size=2)
def fake_main(self):
    with FakeTensorMode() as fake:
        _ = ft_c.all_reduce(torch.rand(4), "sum", [0, 1])

fake_main(None)
```

It fails with this error message:

```
  File "/pytorch/torch/distributed/_functional_collectives.py", line 115, in __new__
    r = torch.Tensor._make_subclass(cls, t, require_grad=t.requires_grad)
RuntimeError: Creating a new Tensor subclass AsyncCollectiveTensor but the raw Tensor object is already associated to a python object of type FakeTensor
```

Is there a proper way to use torch.Tensor subclasses with FakeTensor or a workaround to make it work in this case?

### Versions

master

cc @ezyang @msaroufim

**Comment by ezyang** [comment]
No, unfortunately, this is a known problem with no easy fix, as it is fundamental to OO subclassing. cc @eellison

**Comment by eellison** [comment]
Maybe we could have an API for sublcasses "fakify-ing" themselves ? CC @bdhirsh you had some work on making subclasses work with FakeTensor, right

**Comment by bdhirsh** [comment]
Yeah - my (very WIP) prototype for AOTDispatch so far basically requires the subclass to implement two extra methods, `_unwrap_tensor` an `_wrap_tensor`, that implement the manual conversion between "subclass tensor -> inner tensor" and "inner tensor(s) + ctx -> subclass tensor".

That could probably be used as a building block for getting fakeifying subclasses to work, but I think there's still some UX stuff to be figured out to get the repro code above to work automatically

**Comment by bdhirsh** [comment]
Although that will only work for "wrapper" subclasses that container an inner tensor, that we can fakeify. It looks like this example uses an "is-a" tensor, where I don't think we can fix the problem the same way.

**Comment by kumpera** [comment]
With help from @bdhirsh, I switched to a wrapper subclass as it works for our scenario and now FakeTensorMode seems to be working.
