### ISSUE TITLE
dynamo+aot improperly handles dupe args via *args

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#95501]
### 🐛 Describe the bug

A simple repro is a new test case for `pytorch/test/dynamo/test_aot_autograd.py` based on the existing test `test_arg_dupe_via_dynamo_recompiles_many_args_param`.

Basically, if a user module accepts *args format to forward, we don't deal with duplicate args correctly.

This shows up in real life once we make dynamo call `__call__` instead of .forward(), since __call__ (or rather, NNModule._call_impl) accepts *args rather than the typical usercode .forward which accepts an explicit list of args.

Dynamo+AOT may need to handle 'LocalInputSource' a little differently, to account for this.

```

    @patch("torch._functorch.config.debug_assert", True)
    def test_arg_dupe_via_dynamo_recompiles_star_args(self):
        class F(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.mean = torch.nn.Parameter(torch.randn(3, 3))

            def forward(self, *args):
                a, b, c, d = args
                a.t_()
                b.t_()
                c.t_()
                d.t_()
                return a + b + c + d + self.mean

        a = torch.randn(3, 3, requires_grad=True)
        b = torch.randn(3, 3, requires_grad=True)
        a1, a2, a3, a4 = a.clone(), a.clone(), a.clone(), a.clone()
        b1, b2, b3, b4 = b.clone(), b.clone(), b.clone(), b.clone()

        failure_reason = None

        def guard_fail_fn(failure):
            nonlocal failure_reason
            failure_reason = failure[0]

        self.assertTrue(failure_reason is None)

        cc = torch._dynamo.testing.CompileCounterWithBackend("aot_eager")

        f = torch._dynamo.optimize(cc, guard_fail_fn=guard_fail_fn)(F())
        f(a1, a1, a1, a1)

        # This raises the AssertionError pasted below
        f(a2, b2, b2, b2)

```

AssertionError that is raised:
```
 # AssertionError: At compilation time, graph 0 was compiled under the assumption that input 1 would be a duplicate of input 0, but at runtime this was not the case.  This indicates a guard bug in AOTAutograd or Dynamo, please file a bug to PyTorch.
```

Expected behavior: dynamo guard failure triggers recompile

### Versions

pytorch @ bc438af6fed4fe1fd0ed80e6d5f5ea17c3ca30bb

cc @ezyang @soumith @msaroufim @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire @Chillee

**Comment by wconstab** [comment]
@voznesenskym do you know if this is fixed by your redo of arg handling?

**Comment by williamwen42** [comment]
@wconstab what's the status of this test `test_arg_dupe_via_dynamo_recompiles_star_args`? It's not in the codebase right now, but if I add it, it passes.
