### ISSUE TITLE
Long queue on MacOS M1 runners

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#95510]
## Current Status
ongoing

## Error looks like
Long queue on MacOS M1 runners

## Incident timeline (all times pacific)
* Feb 24th: long queue notice 

![Screenshot 2023-02-24 at 13 58 27](https://user-images.githubusercontent.com/475357/221301184-92278966-6f34-4bc0-81d2-c8076d954e6a.png)

## User impact
People cannot merge normally as all runners have stopped running

## Root cause
TBD

## Mitigation
* Disable the job https://github.com/pytorch/pytorch/pull/95509
* Re-add the runners during the weekend

## Prevention/followups
* https://github.com/fairinternal/pytorch-gha-infra/pull/127

**Comment by kulinseth** [comment]
@malfet , is there an ETA on when we can expect these runners will be restored? Its affecting the testing for release/2.0

**Comment by malfet** [comment]
@kulinseth The runners are back and I've reenabled MPS testing as part of my xfail PR

**Comment by malfet** [comment]
@huydhn looks like runners are back online, so I've re-enabled MPS testing, we probably should re-enable the rest as well. Do we know what have caused it? Have we lost all runners or just exceeded the capacity of the existing pool?

**Comment by huydhn** [comment]
> @huydhn looks like runners are back online, so I've re-enabled MPS testing, we probably should re-enable the rest as well. Do we know what have caused it? Have we lost all runners or just exceeded the capacity of the existing pool?

Thank @seemethere for bringing the runners up during the weekend.  We lost all the runners on Friday.  I will re-enable the test now.

An observation I had on Friday was that many x86_64 jobs failed too right before the queue started to build up (see those F for retry).  That was unusual, so I suspected that it could be something from GitHub, i.e. runner version update.  GitHub brought those x86_64 runners back for us, while we need to handle ARM64 runners ourselves.

![Screenshot 2023-02-27 at 10 21 49](https://user-images.githubusercontent.com/475357/221650373-4e31a284-4cfc-47a3-9771-7250b84fe035.png)

**Comment by huydhn** [comment]
Resolve this now as macos m1 runners are back.
