### ISSUE TITLE
v2.0.0-rc2 package is not utilizing cuda/cuda.h in third_party directory 

### ISSUE THREAD

**Issue by weiwangmeta** [pytorch/pytorch#95523]
### 🐛 Describe the bug

See description in https://github.com/pytorch/builder/issues/1318#issuecomment-1444635570 

We need to make sure examples would work even in absence of "export CUDA_HOME=/usr/local/cuda-11.7". 

### Versions

v2.0.0-rc2.

**Comment by weiwangmeta** [comment]
![image](https://user-images.githubusercontent.com/109318740/221329091-bef02aba-3d87-4316-9ece-d5500ffe1106.png)
Issue is verified to be fixed by #95540

**Comment by ptrblck** [comment]
Thanks for great and quick fix!
Just confirming that `2.0.0.dev20230225+cu118` fixes this issue in the previously broken environment.
