### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by seawater668** [pytorch/pytorch#95549]
cuda11.0+pytorch1.7.1
run：
import torch
>>>torch.cuda.is_available()
>>>True
>>>torch.cuda.device_count()
>>>1
>>>torch.cuda.get_device_name(0)
>>>'NVIDIA GeForce RTX 3060'
>>>torch.tensor([1.0, 2.0]).cuda()
>>>tensor([1., 2.], device='cuda:0')

There is no problem with the above operation，But there is a problem when running the following demo, what's going on?
https://github.com/williamyang1991/DualStyleGAN/issues/67

**Comment by ptrblck** [comment]
Could you update PyTorch to the latest stable or nightly release as `1.7.1` is quite old by now, please?

**Comment by seawater668** [comment]
@ptrblck 
>>> torch.__version__
'1.12.0'
>>> torch.cuda.is_available()
True
>>> torch.version.cuda
'11.3'
>>> torch.backends.cudnn.version()
8302
>>> torch.cuda.get_device_name(0)
'NVIDIA GeForce RTX 3060'
>>> torch.tensor([1.0, 2.0]).cuda()
tensor([1., 2.], device='cuda:0')

There is no problem with the above operation，But there is a problem when running the following demo, what's going on?
https://github.com/williamyang1991/DualStyleGAN/issues/67
