### ISSUE TITLE
Mysterious IMA from MAX_AUTOTUNE=1 resnet50

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#95542]
So I found a workaround for this one, but still have no idea what is going on, and I don't feel like the root cause is actually fixed.  Recording my progress in case others hit similar issues.  This is run with the latest Triton (7eecc4d4ade21cf83237b4865b84ba00306a4386), so post-MLIR.

While running:
```
TORCHINDUCTOR_MAX_AUTOTUNE=1 ./benchmarks/dynamo/torchbench.py --performance --only resnet50 --inductor --float32
```
During the autotuning of an `addmm()` where M=32, N=1000, K=2048. I would get an error `RuntimeError: CUDA error: an illegal memory access was encountered`.

The failure came from just one config, where: `{"BLOCK_M": 32, "BLOCK_N": 32, "BLOCK_K": 128}`, and all the other configs pass.

After this failure, the PyTorch processes would be totally hosed.  Every single operation would raise `CUDA error: an illegal memory access was encountered` and the only way to recover would be to restart.  This makes it super annoying to debug, and impossible to catch the error and recover.

My first thought was maybe this is a Triton bug (since all but one config works fine).  So I pulled out a [repro.py](https://gist.github.com/jansel/42a2f3273f465a2f16045c5d6a1d9295) that as far as I can tell represents the code being run.  Sadly, the repro runs fine in isolation.  Yet the error is reproducible in the context the full model.  I tried a bit to debug it in-place, but none of the things I tried helped.

The "fix" I will submit shortly is just:
```diff
diff --git a/torch/_inductor/kernel/mm_common.py b/torch/_inductor/kernel/mm_common.py
index 17f7fc9bbff..a35aef5244a 100644
--- a/torch/_inductor/kernel/mm_common.py
+++ b/torch/_inductor/kernel/mm_common.py
@@ -43,9 +43,9 @@ def mm_configs():
         triton.Config(
             {"BLOCK_M": 64, "BLOCK_N": 64, "BLOCK_K": 64}, num_stages=3, num_warps=8
         ),
-        triton.Config(
-            {"BLOCK_M": 32, "BLOCK_N": 32, "BLOCK_K": 128}, num_stages=2, num_warps=8
-        ),
         triton.Config(
             {"BLOCK_M": 64, "BLOCK_N": 64, "BLOCK_K": 16}, num_stages=2, num_warps=4
         ),
```
which is kind of a frustrating workaround.

If anyone has other ideas please chime in.  

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @bertmaher @nmacchioni

**Comment by ngimel** [comment]
This is fixed in #95339

**Comment by jansel** [comment]
Oh awesome, thanks @ngimel!  We should cherry-pick that fix to the release branch.

**Comment by ngimel** [comment]
We did!
