### ISSUE TITLE
Incorrect example in documentation for `autocast`

### ISSUE THREAD

**Issue by eliphatfs** [pytorch/pytorch#95547]
### 🚀 The feature, motivation and pitch

There is not much space for the actual design choice for users in the device type of `autocast`. The rule is simple: use the device type of the underlying tensor operations.

~~Another consideration is the backward compatibility. The older API (1.7.0, for example) for automp autocast only accepts a `enabled` parameter, while there is a **required** parameter `device_type` in the new API, making them incompatible with each other. Users have to write an ugly if-else to support multiple pytorch APIs.~~

### Alternatives

1. At least, the examples on the page [`https://pytorch.org/docs/stable/amp.html`](https://pytorch.org/docs/stable/amp.html) need to be updated with `device_type`. The documentation is inconsistent by the time of writing.
~~2. If the proposal above is not possible due to technical reasons, a default value of `"cuda"` to `device_type` can be added to enhance compatibility between PyTorch versions.~~

Update: `torch.cuda.amp.autocast` is the old API and `torch.autocast` is the new API. I have been confusing them with each other. However, I would like to say that they *are* confusing.

cc @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by ezyang** [comment]
I'm down for deprecating torch.cuda.amp.autocast. Is torch.autocast also confusing? Part of the reason we split them is because CPU autocast and CUDA autocast do different things by different: what autocasting you get depends on the device.

**Comment by jgong5** [comment]
@eliphatfs Echo @ezyang  You may find more info from the RFC (https://github.com/pytorch/pytorch/issues/55374) about why we decided to provide separate autocast APIs for different devices - different supported low-precision dtypes, different default dtypes, different autocast policies per devices. Explicit APIs are more clear to users.

**Comment by eliphatfs** [comment]
I read from the thread that:

> Yes, we agree that autocast to be device independent in the API level is more user-friendly.

So it is due to the implementation that we do not allow that. Then I think we had better do a little bit with the documentation.

Currently, the two things most confusing are:
1. the incorrect example here <https://pytorch.org/docs/stable/amp.html#torch.autocast> without specifying `device_type`. This is probably a legacy example where `autocast` refers to `torch.cuda.amp.autocast` instead of `torch.autocast`, but it is listed under `torch.autocast` now.
2. running code with `torch.autocast`, introduced in 1.10, in an older PyTorch version. Perhaps some pointers or notes can be added to the documentation.

**Comment by ezyang** [comment]
Sounds good. Send some PRs and tag me or jgong5 on them.

**Comment by eliphatfs** [comment]
I have a small question: Do we have anything like doctest here? Can I / shall we somehow automatically verify that examples in the documentation work?

**Comment by ezyang** [comment]
yes we do! @Erotemic set us up. There are plenty of examples all around.

**Comment by Erotemic** [comment]
Any code in a docstring prefixed with `>>> ` should run as a doctest via [xdoctest](https://github.com/Erotemic/xdoctest), unless it has an `# xdoctest: +SKIP` (or other conditional directive) or it is explicitly disabled in [run_tests.py](https://github.com/pytorch/pytorch/blob/ad782ff7df950dfda64e271dd4ee3c6128971103/test/run_test.py#L653). Note a lot of disabled doctests just need a little bit of maintence and they can be enabled.
