### ISSUE TITLE
torch.to_dense backward ignores unspecified elements in sparse inputs

### ISSUE THREAD

**Issue by pearu** [pytorch/pytorch#95550]
## Issue description

For historical reasons, torch.to_dense backward on sparse inputs implements masked semantics that contradicts the current interpretation of sparse tensors, that is, sparse tensors are semantically equivalent to strided tensors. The use of a sparse format is considered merely a memory optimization that does *not* define a mask for operations on sparse tensors.

The masked semantics of tensors is currently implemented in `torch.masked` (the future) and `torch.sparse` (to be deprecated).

This issue breaks autograd on sparse tensors because the use of `to_dense` method is required for operations resulting in sparse tensors, for example:

```python
>>> import torch
>>> a = torch.tensor([[0, 1], [2, 3]], dtype=torch.float64).to_sparse().requires_grad_()
>>> torch.autograd.gradcheck(torch.Tensor.t, a)
<snip>
ValueError: Sparse output is not supported at gradcheck yet. Please call to_dense() on the output of fn for gradcheck.
```

## Code example

When using the recommendation from the above example, gradcheck using non-masked semantics fails:
```python
>>> torch.autograd.gradcheck(lambda x: torch.Tensor.t(x).to_dense(), a, masked=False)
<snip>
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.0000, 0.0000],
        [0.0000, 1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.0000]], dtype=torch.float64)
analytical:tensor([[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]], dtype=torch.float64)
```
but succeeds under masked semantics:
```python
>>> torch.autograd.gradcheck(lambda x: torch.Tensor.t(x).to_dense(), a, masked=True, check_sparse_nnz=True)
True
```

## Possible solutions

1. A solution is implemented in https://github.com/pytorch/pytorch/pull/94728 that introduces a global Context flag that defines how the operations and their backward implementations should interpret the unspecified elements of sparse tensors.

2. Introduce a `masked` kw argument (default is `False`) to `to_dense` that enables explicit control of semantics when using `to_dense` method. For example, the following examples should succeed:

```python
torch.autograd.gradcheck(lambda x: torch.Tensor.t(x).to_dense(masked=False), a, masked=False)

torch.autograd.gradcheck(lambda x: torch.Tensor.t(x).to_dense(masked=True), a, masked=True)
```

## Discussion

Both solutions have pros and cons (see discussions in https://github.com/pytorch/pytorch/pull/94728) and both will be BC-breaking because the default semantics of operations in `torch` namespace need to switch to non-masked semantics. This cannot be avoided when pursuing the idea of considering sparse tensors semantically equivalent to strided tensors. Fortunately, most tensor operations (from `torch` namespace) on sparse tensors already implement non-masked semantics, for example:
```python
>>> torch.autograd.gradcheck(lambda x: torch.Tensor.t(x)[0, 0], a, masked=False)
True
>>> torch.autograd.gradcheck(lambda x: torch.Tensor.t(x)[0, 0], a, masked=True, check_sparse_nnz=True)
<snip>
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[0.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64)
analytical:tensor([[1.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64)
>>> torch.autograd.gradcheck(lambda x: torch.Tensor.t(x)[0, 1], a, masked=True, check_sparse_nnz=True)
True
>>> torch.autograd.gradcheck(lambda x: torch.Tensor.t(x)[0, 1], a, masked=False)
True
```
The failure above is expected because both transposing and indexing use non-masked semantics (the use of indexing op circumvents "Sparse output is not supported at gradcheck yet" exception and the current issue with `to_dense`).

From the future perspective, when the masked and non-masked semantics will be well separated between `torch.masked` and `torch` namespaces, the use of `masked` kw argument both in `gradcheck` and `to_dense` become unnecessary because the semantics will be defined by the operations (whether these are from `torch.masked` or `torch` namespaces). Ironically, this sounds very similar to the original plan of having `torch.sparse` and `torch` namespaces for different semantics. I guess the main difference is that the memory optimization and masked semantics features from using sparse tensors become uncoupled features.

## System Info

- PyTorch version:

https://github.com/pytorch/pytorch/pull/95405 that implements `masked` kw argument support to `gradcheck`.

cc @alexsamardzic @nikitaved @cpuhrsch @amjames @bhosmer @ezyang @gchanan @albanD @zou3519 @gqchen @soulitzer @Lezcano @Varal7

**Comment by vadimkantorov** [comment]
Personally, I'm in favor of more explicit solutions (such as `masked=True` arguments) first, and then if needed - context managers.

**Comment by nikitaved** [comment]
I am not sure we have to enforce any masked semantics, be it autograd and/or context managers, because:
1. We have the tools to implement any sparse semantics with differentiable `sparse_mask` ([95165](https://github.com/pytorch/pytorch/pull/95165)).
For example, using `sparse_mask` it is easy to mimic the behavior of `torch.sparse.mm`:
```python
In [1]: import torch

In [2]: x_data = torch.rand(3, 3)

In [3]: y_data = torch.rand(3, 3)

In [4]: x1 = x_data.mul(x_data < 0.5).to_sparse().requires_grad_(True)

In [5]: x2 = x_data.mul(x_data < 0.5).to_sparse().requires_grad_(True)

In [6]: y1 = y_data.mul(y_data < 0.5).to_sparse().requires_grad_(True)

In [7]: y2 = y_data.mul(y_data < 0.5).to_sparse().requires_grad_(True)

In [8]: def custom_sparse_mm(x, y):
   ...:     x = x.sparse_mask(x)
   ...:     y = y.sparse_mask(y)
   ...:     res = x @ y
   ...:     res = res.sparse_mask(res)
   ...:     return res
   ...: 

In [9]: torch.autograd.grad(custom_sparse_mm(y1, x1), (y1, x1), torch.ones(3, 3).to_sparse())
<ipython-input-8-4d9400ee8449>:4: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /home/nik/git/Quansight/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:54.)
  res = x @ y
Out[9]: 
(tensor(indices=tensor([[0, 1, 2, 2, 2],
                        [1, 0, 0, 1, 2]]),
        values=tensor([0.8071, 0.6476, 0.6476, 0.8071, 0.2095]),
        size=(3, 3), nnz=5, layout=torch.sparse_coo),
 tensor(indices=tensor([[0, 0, 0, 1, 1, 1, 2],
                        [0, 1, 2, 0, 1, 2, 2]]),
        values=tensor([0.1705, 0.1705, 0.1705, 0.6261, 0.6261, 0.6261, 0.3517]),
        size=(3, 3), nnz=7, layout=torch.sparse_coo))

In [10]: torch.autograd.grad(torch.sparse.mm(y2, x2), (y2, x2), torch.ones(3, 3).to_sparse())
Out[10]: 
(tensor(indices=tensor([[0, 1, 2, 2, 2],
                        [1, 0, 0, 1, 2]]),
        values=tensor([0.8071, 0.6476, 0.6476, 0.8071, 0.2095]),
        size=(3, 3), nnz=5, layout=torch.sparse_coo),
 tensor(indices=tensor([[0, 0, 0, 1, 1, 1, 2],
                        [0, 1, 2, 0, 1, 2, 2]]),
        values=tensor([0.1705, 0.1705, 0.1705, 0.6261, 0.6261, 0.6261, 0.3517]),
        size=(3, 3), nnz=7, layout=torch.sparse_coo))


In [11]: x1
Out[11]: 
tensor(indices=tensor([[0, 0, 0, 1, 1, 1, 2],
                       [0, 1, 2, 0, 1, 2, 2]]),
       values=tensor([0.0543, 0.1362, 0.4572, 0.0271, 0.4451, 0.3349, 0.2095]),
       size=(3, 3), nnz=7, layout=torch.sparse_coo, requires_grad=True)

In [12]: y1
Out[12]: 
tensor(indices=tensor([[0, 1, 2, 2, 2],
                       [1, 0, 0, 1, 2]]),
       values=tensor([0.3481, 0.0818, 0.0887, 0.2780, 0.3517]),
       size=(3, 3), nnz=5, layout=torch.sparse_coo, requires_grad=True)

```

In general, any composition of operations `(f_n o ... o f_1)(x)` can be turned into a "masked" operation
 `[(m_n o f_n) o ... o (m_1 o f_1)](x.sparse_mask(x))`, where `m_i(x) := id(x) or x.sparse_mask(mask_i)` with `mask_i` potentially equal to `x`.

This approach:
a. Is very flexible and does not rely on any global behavior but just sparse being an optimization layout.
b. Masking of type `x.sparse_mask(x)` is a trivial operation with the only overhead of creating additional node in the computational graph.
c. Masks can trivially be shared along the composition of functions for reduced memory footprint.

2. Masked semantics implies sparse parametrization only in some cases. i.e equal size/sparsity and with element-wise operations. This is not the case in more complicated cases say, with matrix multiplications:

```python
In [1]: import torch

In [2]: x = torch.rand(3, 3).to_sparse().requires_grad_(True)

In [3]: y_data = torch.rand(3)

In [4]: y = torch.diag_embed(y_data).to_sparse().requires_grad_(True)

In [5]: torch.sparse.mm(x, y).to_dense().sum().backward()
<ipython-input-5-6ecffd1ed0d0>:1: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /home/nik/git/Quansight/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:54.)
  torch.sparse.mm(x, y).to_dense().sum().backward()

In [6]: y.grad
Out[6]: 
tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([0.3369, 1.0641, 1.7735]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)

In [7]: x.grad
Out[7]: 
tensor(indices=tensor([[0, 0, 0, 1, 1, 1, 2, 2, 2],
                       [0, 1, 2, 0, 1, 2, 0, 1, 2]]),
       values=tensor([0.3163, 0.8530, 0.5432, 0.3163, 0.8530, 0.5432, 0.3163,
                      0.8530, 0.5432]),
       size=(3, 3), nnz=9, layout=torch.sparse_coo)

In [8]: x = x.detach().to_dense().requires_grad_(True)

In [9]: y1 = torch.tensor([y[0, 0]], requires_grad=True)

In [10]: y2 = torch.tensor([y[1, 1]], requires_grad=True)

In [11]: y3 = torch.tensor([y[2, 2]], requires_grad=True)

In [12]: (x * (y1 + y2 + y3)).sum().backward()

In [13]: y1.grad
Out[13]: tensor([3.1745])

In [14]: y2.grad
Out[14]: tensor([3.1745])

In [15]: y3.grad
Out[15]: tensor([3.1745])

```

As you can see, sparse mask semantics just projects the gradients onto NSE elements, which is not the same as sparse parametrization.

3. Instead of Masked semantics, it is better to have a notion of sparse parametrization. This is what is expected from sparse in some cases: https://github.com/pytorch/pytorch/issues/87358#issuecomment-1287686505.

**Comment by pearu** [comment]
> I am not sure we have to enforce any masked semantics, be it autograd (looking at to_dense specifically), torch.masked and/or context managers.

@nikitaved Do you agree or disagree that `to_dense_backward` implementation is currently wrong in that it applies input as mask to grad when the input is a tensor with a sparse layout?

**Comment by nikitaved** [comment]
@pearu, I agree with that statement.

**Comment by pearu** [comment]
> @pearu, I agree with that statement. But I also propose an alternative solution to the ones you posited.

Great!

IIUC, your solution is to not have `masked` kw arguments neither in `gradcheck` nor in `to_dense`. Both will assume non-masked semantics. That is:
- in `gradcheck` implementation, sparse inputs will be always densified for numerical jacobian calculations
- in `to_dense` backward implementation, remove `sparse_mask` call

With the above, `torch.sparse.mm` numerical jacobian will be the same as the numerical jacobian of `torch.mm` but the corresponding analytical jacobians will be different.

So, how would you test `torch.sparse.mm` autograd correctness using gradcheck?
