### ISSUE TITLE
[Reproducibility]replication_pad2d_backward_cuda does not have a deterministic implementation

### ISSUE THREAD

**Issue by berniewang8177** [pytorch/pytorch#95578]
### 🚀 The feature, motivation and pitch

Hi, I am following the instruction from [here](https://pytorch.org/docs/stable/notes/randomness.html#cuda-convolution-determinism) to set torch.use_deterministic_algorithms(True)

However, i encounter an error as shown in title.

### Alternatives

I have tried:
torch.use_deterministic_algorithms(True, warn_only=True)
and it works for me.

### Additional context

I not sure why its happening. But my implementation does involves padding. The main architecture contains convolution (Unet-encoder), a transformer encoder, and a Unet-decoder with upsampling.

cc @mruberry @kurtamohler @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by berniewang8177** [comment]
Besides, 
this one seems also lacking a deterministic implementaition.
"upsample_bilinear2d_backward_out_cuda does not have a deterministic implementation,"

I'm using this version: os.environ["CUBLAS_WORKSPACE_CONFIG"]=":16:8"

**Comment by ezyang** [comment]
Unfortunately, the error message is pretty self explanatory. Maybe we can do a deterministic impl using pt2

**Comment by ezyang** [comment]
We should apply the same playbook here as in https://github.com/pytorch/pytorch/pull/101115

**Comment by kurtamohler** [comment]
I'll try to do this soon

**Comment by kurtamohler** [comment]
There doesn't seem to be a decomposition for any of the padding functions in `torch/_decomp/decompositions.py`, so it doesn't seem like we can do this yet

**Comment by Sudayberry** [comment]
Have you solved the problem? And if set torch.use_deterministic_algorithms as False, could it be reproduced?
