### ISSUE TITLE
I'm not able to install Pytorch.

### ISSUE THREAD

**Issue by PierrunoYT** [pytorch/pytorch#95574]
### 🐛 Describe the bug

I try to download pytorch and torchvision

ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

ERROR: Could not find a version that satisfies the requirement torchvision (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
ERROR: No matching distribution found for torchvision

### Versions

I'm not able to run this on on Windows

**Comment by ezyang** [comment]
ask at https://discuss.pytorch.org/ they will give better advice
