### ISSUE TITLE
torch.unique output incorrect when tensor contains NaNs

### ISSUE THREAD

**Issue by hchau630** [pytorch/pytorch#95583]
### 🐛 Describe the bug

I saw some other issues that reported bugs with torch.unique when the tensor contains NaNs, but I observed two other seemingly different bugs.

```
import torch

t = torch.tensor([0., torch.nan, 2., torch.nan, 2., 1., 0., 1., 2., 0.])
print(t.unique(sorted=True, dim=None))
print(t.unique(sorted=True, dim=0))
```

Output:
```
tensor([1., nan, 2., nan, 0.])
tensor([0., nan, 2., nan, 0., 1., 2.])
```

Expected:
```
tensor([0., 1., 2., nan, nan])
tensor([0., 1., 2., nan, nan])
```

I'm not sure whether there should be two nans in the output or just one, since torch.unique doesn't have the equal_nan argument like numpy.unique.

In the first unique() call, the output is not sorted even though sorted=True. The second unique() call just gives a completely wrong output, since it contains duplicate non-nan values.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 (main, Oct 13 2022, 16:12:19)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.6.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==1.13.1
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
```

**Comment by ezyang** [comment]
I'm not sure what the "correct" result here is

**Comment by hchau630** [comment]
The "correct" result should be either the result under the section "Expected" in my post, i.e.
```
tensor([0., 1., 2., nan, nan])
tensor([0., 1., 2., nan, nan])
```
or 
```
tensor([0., 1., 2., nan])
tensor([0., 1., 2., nan])
```
depending on how torch.unique is designed to handle NaNs. The documentation doesn't say anything about removing duplicate NaNs, so I'm assuming the first option is more "correct".

**Comment by mruberry** [comment]
Closing in favor of the earlier https://github.com/pytorch/pytorch/issues/76571. 

It is unfortunate that the behavior of `unique` on tensors with `NaN` values is not expected. See also https://github.com/pytorch/pytorch/issues/94106. Maybe these issues should be rolled up together. 

We would accept a PR fixing the behavior of `unique` on tensors with `NaN` values, so long as there was not a significant performance impact.

**Comment by hchau630** [comment]
I just noticed that the first bug is unique to macOS on cpu (i.e. it works on linux on cpu but not on macOS). Should I open another issue about it? @mruberry

To be explicit, if I run the code
```
import torch

t = torch.tensor([0., torch.nan, 2., torch.nan, 2., 1., 0., 1., 2., 0.])
print(t.unique(sorted=True, dim=None))
```
on macOS 12.6.3, torch==1.13.1, python==3.9.13, I get the output
```
tensor([1., nan, 2., nan, 0.])
```
but on Linux 3.10.0, torch==1.13.1+cu117, python==3.9.7, I get the output
```
tensor([0., 1., 2., nan, nan])
```
