### ISSUE TITLE
load_lua yields "object has no attribute 'running_var'" for BatchNormalization

### ISSUE THREAD

**Issue by thnkim** [pytorch/pytorch#956]
When I try to load OpenFace model (https://storage.cmusatyalab.org/openface-models/nn4.small2.v1.t7) as:

    model = load_lua('nn4.small2.v1.t7',unknown_classes=True),

then, to convert unknown classes. 
But, I got the errors at the line below:

torch/utils/serialization/read_lua_file.py", line 269, in BatchNorm_reader
    obj.running_var = obj.running_var.pow(-2).add(-obj.eps)

Thank you.

**Comment by soumith** [comment]
This is a really old torch model.
A fix would be to load it in LuaTorch and save it back. Then the issue should be fixed.
So:
```
$ th -lnn
> m = torch.load("nn4.small2.v1.t7")
> torch.save("nn4.small2.v1.t7", m)
```

**Comment by thnkim** [comment]
thank you, so much!!!

Best Regards,
Tae-hoon Kim

**Comment by TwoBranchDracaena** [comment]
I load and save the t7 model with the latest lua torch.

But when I try to load it in PyTorch, I get this error:

File "/usr/local/lib/python3.5/site-packages/torch/utils/serialization/read_lua_file.py", line 357, in storage_to_size
    value = getattr(obj, attr)
AttributeError: 'DepthConcat' object has no attribute 'outputSize'

Anybody has the same problem?

**Comment by liorshk** [comment]
The whole code looks like this:

Torch:
```
require 'nn'
require 'dpnn'
require 'cunn'
model = torch.load('n4.small2.v1.t7')

-- Forward pass a random tensor
x = torch.FloatTensor()
model:forward(x:resize(3,96,96))

torch.save('nn4.small2.v1.resaved.t7',model)
```

Then in pytorch:
```
from torch.utils.serialization import load_lua
model = load_lua('nn4.small2.v1.resaved.t7',unknown_classes=True)
```

**Comment by galli-leo** [comment]
@liorshk Is there a reason why the new `nn4.small2.v1.resaved.t7` produces a different output than the original one? I haven't changed anything else.
