### ISSUE TITLE
forward_hook doesn't work with nn.ReLU(inplace=True) 

### ISSUE THREAD

**Issue by bpfrd** [pytorch/pytorch#95617]
### 🐛 Describe the bug

```python
x = torch.tensor([1.23, -4.56])
m = nn.ReLU(inplace=True)

def my_hook(m, input, output):
    print('hook', m , input, output)
    
def my_pre_hook(m, input):
    print('pre hood', m, input)
    
m.register_forward_pre_hook(my_pre_hook)
m.register_forward_hook(my_hook)

m(x)
```
output:
```
pre hood ReLU() (tensor([1.2300, -4.5600]),)
hook ReLU() (tensor([1.2300, 0.0000]),) tensor([1.2300, 0.0000])
tensor([1.2300, 0.0000])
```

The input to the hook is already ReLUed! but everything is fine for ```nn.ReLU(inplace=False)```

### Versions

```
torch.__version__
'1.13.1'
```

**Comment by ptrblck** [comment]
Double post from [here](https://discuss.pytorch.org/t/how-to-modify-a-pretrained-model/60509/18?u=ptrblck) with a follow-up.

**Comment by ngimel** [comment]
The docs say that forward hook runs after the forward is completed https://pytorch.org/docs/master/generated/torch.nn.Module.html?highlight=register_forward_hook#torch.nn.Module.register_forward_hook so results are expected for an inplace op.
