### ISSUE TITLE
Pytorch Home Page does not specify which version of python it requires

### ISSUE THREAD

**Issue by fredm73** [pytorch/pytorch#95628]
### 🐛 Describe the bug

When using the pip command to install pytorch suggested by the page https://pytorch.org/  , which is 
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
pip returns 'no matching distribution found". I guess this is because I have installed python 3.11. If I go back to python 3.10, pytorch installs correctly. I suggest that the pytorch home page clearly state that pytorch is not supported under windows/pip for python 3.11. If this is not possible, how can I know when pytorch will be supported for windows under python 3.11?
I am running Windows version 10.

![image](https://user-images.githubusercontent.com/7177684/221648620-41e61a9a-563a-45a6-992f-ff685ef202d7.png)

### Versions

C:\Users\fredm>wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
'wget' is not recognized as an internal or external command,
operable program or batch file.

So, that command does not work under Windows. How about one that does?

cc @svekars @carljparker

**Comment by malfet** [comment]
@atalman , @seemethere we've talked about it earlier today

**Comment by atalman** [comment]
@malfet @seemethere One place to include python information could be in the installation instructions at the bottom. Something like "Supported  Python version: >=3.8, <=3.10"
<img width="772" alt="Screenshot 2023-02-28 at 4 14 42 PM" src="https://user-images.githubusercontent.com/7563158/221981857-d1ff7f05-fb0d-48f4-a296-b624fe6d67dc.png">

**Comment by malfet** [comment]
Moving to 2.2.0

**Comment by atalman** [comment]
Validated Python version in:
https://pytorch.org/get-started/locally/#linux-python
https://pytorch.org/get-started/locally/#mac-python
https://pytorch.org/get-started/locally/#windows-python
