### ISSUE TITLE
Failed to compile PyTorch on IBM Power8 arch same as  #8787

### ISSUE THREAD

**Issue by bapriddy** [pytorch/pytorch#9564]
@zuoxingdong ,  @avmgithub , @soumith   see  #8787

I am also using the IBM Power 8 architecture (ppc64le) with CUDA 9.2 and latest cudnn/6.0 and nvcc/9.2. Since none of this is supported with conda or pip installs, I attempeted a build from the source instruction after reading the same issue posted by @zuoxingdong.   It get the following error...

~    /pytorch$ python setup.py install
running install
running build_deps
+ USE_CUDA=0
+ USE_ROCM=0
+ USE_NNPACK=0
+ USE_MKLDNN=0
+ USE_GLOO_IBVERBS=0
+ USE_DISTRIBUTED_MW=0
+ FULL_CAFFE2=0
+ [[ 9 -gt 0 ]]
+ case "$1" in
+ USE_CUDA=1
+ shift
+ [[ 8 -gt 0 ]]
+ case "$1" in
+ USE_NNPACK=1
+ shift
+ [[ 7 -gt 0 ]]
+ case "$1" in
+ break
+ CMAKE_INSTALL='make install'
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ uname
+ '[' Linux == Darwin ']'
++ dirname tools/build_pytorch_libs.sh
+ cd tools/..
+++ pwd
++ printf '%q\n'  /pytorch
+ PWD= /pytorch
+ BASE_DIR= /pytorch
+ TORCH_LIB_DIR= /pytorch/torch/lib
+ INSTALL_DIR= /pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR= /pytorch/third_party
+ CMAKE_VERSION=cmake
+ C_FLAGS=' -I" /pytorch/torch/lib/tmp_install/include"   -I" /pytorch/torch/lib/tmp_install/include/TH" -I" /pytorch/torch/lib/tmp_install/include/THC"   -I" /pytorch/torch/lib/tmp_install/include/THS" -I" /pytorch/torch/lib/tmp_install/include/THCS"   -I" /pytorch/torch/lib/tmp_install/include/THNN" -I" /pytorch/torch/lib/tmp_install/include/THCUNN"'
+ C_FLAGS=' -I" /pytorch/torch/lib/tmp_install/include"   -I" /pytorch/torch/lib/tmp_install/include/TH" -I" /pytorch/torch/lib/tmp_install/include/THC"   -I" /pytorch/torch/lib/tmp_install/include/THS" -I" /pytorch/torch/lib/tmp_install/include/THCS"   -I" /pytorch/torch/lib/tmp_install/include/THNN" -I" /pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS='-L" /pytorch/torch/lib/tmp_install/lib" '
+ LD_POSTFIX=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ LDFLAGS='-L" /pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ GLOO_FLAGS=
+ THD_FLAGS=
+ NCCL_ROOT_DIR= /pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR= /pytorch/torch/lib/tmp_install'
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ CWRAP_FILES=' /pytorch/torch/lib/ATen/Declarations.cwrap; /pytorch/torch/lib/THNN/generic/THNN.h; /pytorch/torch/lib/THCUNN/generic/THCUNN.h; /pytorch/torch/lib/ATen/nn.yaml'
+ CUDA_NVCC_FLAGS=' -I" /pytorch/torch/lib/tmp_install/include"   -I" /pytorch/torch/lib/tmp_install/include/TH" -I" /pytorch/torch/lib/tmp_install/include/THC"   -I" /pytorch/torch/lib/tmp_install/include/THS" -I" /pytorch/torch/lib/tmp_install/include/THCS"   -I" /pytorch/torch/lib/tmp_install/include/THNN" -I" /pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ [[ -z '' ]]
+ CUDA_DEVICE_DEBUG=0
+ '[' -z 160 ']'
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p torch/lib/tmp_install
+ for arg in '"$@"'
+ [[ nccl == \n\c\c\l ]]
+ pushd  /pytorch/third_party
 /pytorch/third_party  /pytorch
+ build_nccl
+ mkdir -p build/nccl
+ pushd build/nccl
 /pytorch/third_party/build/nccl  /pytorch/third_party  /pytorch
+ cmake ../../nccl -DCMAKE_MODULE_PATH= /pytorch/cmake/Modules_CUDA_fix -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX= /pytorch/torch/lib/tmp_install '-DCMAKE_C_FLAGS= -I" /pytorch/torch/lib/tmp_install/include"   -I" /pytorch/torch/lib/tmp_install/include/TH" -I" /pytorch/torch/lib/tmp_install/include/THC"   -I" /pytorch/torch/lib/tmp_install/include/THS" -I" /pytorch/torch/lib/tmp_install/include/THCS"   -I" /pytorch/torch/lib/tmp_install/include/THNN" -I" /pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1 ' '-DCMAKE_CXX_FLAGS= -I" /pytorch/torch/lib/tmp_install/include"   -I" /pytorch/torch/lib/tmp_install/include/TH" -I" /pytorch/torch/lib/tmp_install/include/THC"   -I" /pytorch/torch/lib/tmp_install/include/THS" -I" /pytorch/torch/lib/tmp_install/include/THCS"   -I" /pytorch/torch/lib/tmp_install/include/THNN" -I" /pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1  -std=c++11  ' -DCMAKE_SHARED_LINKER_FLAGS= -DCMAKE_UTILS_PATH= /pytorch/cmake/public/utils.cmake -DNUM_JOBS=160
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error: Error in cmake code at
 /pytorch/cmake/Modules_CUDA_fix/upstream/FindPackageHandleStandardArgs.cmake:6:
Parse error.  Expected "(", got newline with text "
".
CMake Error at  /pytorch/cmake/Modules_CUDA_fix/upstream/FindCUDA.cmake:1102 (include):
  include could not find load file:

     /pytorch/cmake/Modules_CUDA_fix/upstream/FindPackageHandleStandardArgs.cmake
Call Stack (most recent call first):
   /pytorch/cmake/Modules_CUDA_fix/FindCUDA.cmake:11 (include)
  CMakeLists.txt:5 (FIND_PACKAGE)

-- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.0") 
-- Autodetected CUDA architecture(s): 6.0 6.0 
-- Set NVCC_GENCODE for building NCCL: -gencode=arch=compute_60,code=sm_60
-- Configuring incomplete, errors occurred!
See also " /pytorch/third_party/build/nccl/CMakeFiles/CMakeOutput.log".
See also " /pytorch/third_party/build/nccl/CMakeFiles/CMakeError.log".
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'
 ~

**Comment by bapriddy** [comment]
I may have solved it. I'll repost if it fails

**Comment by kelsiuss** [comment]
@bapriddy what was your solution?

**Comment by bapriddy** [comment]
@kelsiuss  I installed everything but resnet failed to actually run.  I'm going to re-visit the problem next week.

**Comment by aky15** [comment]
For me, updating the following packages solves the problem.
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
