### ISSUE TITLE
[dynamo] Breaking changes to Huggingface accelerate

### ISSUE THREAD

**Issue by ymwangg** [pytorch/pytorch#95641]
### 🐛 Describe the bug

I happened to find https://github.com/pytorch/pytorch/pull/92125 is potentially causing some coverage issue while I'm working on stable diffusion model. The following code used to work prior to this change:
```py
import torch
import accelerate
from diffusers import UNet2DConditionModel

torch.manual_seed(0)
cuda_device = torch.device("cuda:0")

accelerator = accelerate.Accelerator(mixed_precision="fp16", dynamo_backend="inductor")

unet = UNet2DConditionModel.from_pretrained(
    "CompVis/stable-diffusion-v1-4", subfolder="unet", revision=None
)

unet.train()
unet.to(cuda_device)
unet = accelerator.prepare_model(unet)

x = torch.rand([2, 4, 64, 64], dtype=torch.float16, device=cuda_device)
t = torch.randint(0, 1000, size=(2,), device=cuda_device)
hidden = torch.rand([2, 77, 768], dtype=torch.float16, device=cuda_device)

model_pred = unet(x, t, hidden).sample
print(model_pred)
```

Inside `accelerator.prepare_model`, the `model.forward` call is overwritten after calling dynamo.optimize.
```py
model = dynamo.optimize(self.state.dynamo_backend.value.lower())(model)
model.forward = torch.cuda.amp.autocast(dtype=torch.float16)(model.forward)
model.forward = convert_outputs_to_fp32(model.forward)
```
This error can be resolved by switching this order. Not sure if the user should modify the model like this after calling torch.compile.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh
### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+gitd68b06c
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

**Comment by wconstab** [comment]
> This error can be resolved by switching this order.

Can you share the error you're getting or which part is breaking?

Also, which order works? (can you give the working example, just the few lines you have to change)

> Not sure if the user should modify the model like this after calling torch.compile

Hmm. I'm not sure what our 'policy' should be here.

What is the behavior you are looking for- do you want amp to be applied on top of the compiled model, or you want to compile the 'amped model'?
 
cc @voznesenskym @ezyang

**Comment by ngimel** [comment]
`amp` should not be applied on top of compiled model, it's too late at that point.

**Comment by msaroufim** [comment]
We've had issues with people wanting to compose old pytorch optimizations with newer ones
* JIT
* AMP
* Inference mode

Anything else? I can take a look at hard erroring on all of the above

**Comment by ymwangg** [comment]
@wconstab The following order works:
```
model.forward = torch.cuda.amp.autocast(dtype=torch.float16)(model.forward)
model.forward = convert_outputs_to_fp32(model.forward)
model = dynamo.optimize(self.state.dynamo_backend.value.lower())(model)
```
The following order throws error:
```
model = dynamo.optimize(self.state.dynamo_backend.value.lower())(model)
model.forward = torch.cuda.amp.autocast(dtype=torch.float16)(model.forward)
model.forward = convert_outputs_to_fp32(model.forward)
```
Error message:
```
Traceback (most recent call last):
  File "/home/ubuntu/src/pytorch/torch/_dynamo/utils.py", line 1199, in run_node
    return nnmodule(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/ubuntu/src/pytorch/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same
```

As @ngimel suggested, this should be a bug on Huggingface accelerate, though it happened to work prior to https://github.com/pytorch/pytorch/pull/92125. I'll fix it in accelerate.

**Comment by wconstab** [comment]
ok. i'm guessing that is the right place to fix in this case, but let me know if it doesn't fully work.

Should we also change dynamo's `OptimizedModule` to warn if you modify its .forward or something?

**Comment by ngimel** [comment]
I think that's a good idea.

**Comment by wconstab** [comment]
Ok I put a couple PRs above, need reviews

**Comment by ezyang** [comment]
@ngimel Why not? We are JIT compiler, the AMP context should invalidate the old product and we recompile

**Comment by ngimel** [comment]
Ok, if torch.amp invalidates it then sure.

**Comment by wconstab** [comment]
Are we going to fix anything further on the pytorch side (besides the warnings, which landed)?

Or is the real fix just on the HF side?

**Comment by wconstab** [comment]
closing as it sounded like HF would fix, please reopen otherwise
