### ISSUE TITLE
torch.compile compilation time on huggingface regressed ~11%

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#95660]
From looking at the perf [dashboard](https://github.com/pytorch/pytorch/issues/93794), https://github.com/pytorch/pytorch/pull/95134 regressed inductor compilation time by about ~11% across the huggingface benchmark suite, from a mean compilation time of `65.56s` to `72.57s`.

I tested locally with `MBartForConditionalGenerationq`.

Before: 82.49s
After: 91.90s

We can close this issue if we think this isn't worth digging into further (another option is to look into inductor compile time more holistically instead of looking at regressions in this specific PR).

cc @ezyang @soumith @msaroufim @wconstab @ngimel

**Comment by ngimel** [comment]
cc @nmacchioni

**Comment by nmacchioni** [comment]
Turning off cache search by default #95662
