### ISSUE TITLE
torch custom backward not called

### ISSUE THREAD

**Issue by Mary199810** [pytorch/pytorch#95678]
### 🐛 Describe the bug

I am writing my own backward function. So far I am just checking whether the backward method implemented is being called. You can reproduce the error by running the code below. The print message is never displayed and I obtain an error from the standard autograd function

```
class DDE_adjoint(torch.autograd.Function):
    def forward(ctx, X, x0, tau, T, *parameters):
        ctx.X = X
        ctx.x0 = x0
        ctx.tau = tau
        ctx.T = T
        with torch.no_grad():
            ans = dde_solve(X, x0, tau, T)
            ctx.save_for_backward(ans, *parameters)
        return ans.clone()
        
 
    def backward(ctx, grad_y):
        print('custom backward called')
        return None 

solution = DDE_adjoint.apply
sol = solution(v_field, torch.tensor(1, dtype = float, requires_grad = True), torch.tensor(1,dtype = float, requires_grad = True), torch.tensor(10) )
sol.backward()
```

### Error logs

RuntimeError                              Traceback (most recent call last)
Cell In[257], line 4
      2 sol = solution(v_field, torch.tensor(1, dtype = float, requires_grad = True), torch.tensor(1,dtype = float, requires_grad = True), torch.tensor(10) )
      3 #plt.plot(sol)
----> 4 sol.backward()

File /opt/anaconda3/envs/math/lib/python3.8/site-packages/torch/_tensor.py:488, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    478 if has_torch_function_unary(self):
    479     return handle_torch_function(
    480         Tensor.backward,
    481         (self,),
   (...)
    486         inputs=inputs,
    487     )
--> 488 torch.autograd.backward(
    489     self, gradient, retain_graph, create_graph, inputs=inputs
    490 )

File /opt/anaconda3/envs/math/lib/python3.8/site-packages/torch/autograd/__init__.py:190, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    186 inputs = (inputs,) if isinstance(inputs, torch.Tensor) else \
    187     tuple(inputs) if inputs is not None else tuple()
    189 grad_tensors_ = _tensor_or_tensors_to_tuple(grad_tensors, len(tensors))
--> 190 grad_tensors_ = _make_grads(tensors, grad_tensors_, is_grads_batched=False)
    191 if retain_graph is None:
    192     retain_graph = create_graph

File /opt/anaconda3/envs/math/lib/python3.8/site-packages/torch/autograd/__init__.py:85, in _make_grads(outputs, grads, is_grads_batched)
     83 if out.requires_grad:
     84     if out.numel() != 1:
---> 85         raise RuntimeError("grad can be implicitly created only for scalar outputs")
     86     new_grads.append(torch.ones_like(out, memory_format=torch.preserve_format))
     87 else:

RuntimeError: grad can be implicitly created only for scalar outputs

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.15 (default, Nov 24 2022, 09:04:07)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchdiffeq==0.2.3
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637
[conda] mkl-service               2.4.0            py38h9ed2024_0
[conda] mkl_fft                   1.3.1            py38h4ab4a9b_0
[conda] mkl_random                1.2.2            py38hb2f4e1b_0
[conda] numpy                     1.23.5           py38he696674_0
[conda] numpy-base                1.23.5           py38h9cd3388_0
[conda] pytorch                   1.13.1                  py3.8_0    pytorch
[conda] torchaudio                0.13.1                 py38_cpu    pytorch
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchvision               0.14.1                 py38_cpu    pytorch

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
The error message is pretty clear, you cannot call `.backward` on a non-scalar output, and your `sol` is not scalar.
