### ISSUE TITLE
[Inductor] [CPU] Timm model regnety_002 performance regression > 10% on ww09.2

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#95684]
### 🐛 Describe the bug

Compare with the ww08.4, there is a performance regression on timm model regnety_002 on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1447448011) on ww09.2 as bellow:

|  ww09.2  |   |     |   |  ww08.4   |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|1.449	|0.0072255	|0.01046975	|1	|1.7044	|0.0062312	|0.010620457	|0.85	|1.01	|0.86

WW09.2 SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[3313e86](https://github.com/pytorch/pytorch/commit/3313e86c033331a19d9bbea8dde343ca6f8320be)|[a88bfc6](https://github.com/pytorch/pytorch/commit/a88bfc60c75d22a047f03787aaa43130c6a8d6d9)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

WW08.4 SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[5a6cf28](https://github.com/pytorch/pytorch/commit/5a6cf2804b0ee0c5da9a74322b2e2d0d836cdeb8)|[286d821](https://github.com/pytorch/pytorch/commit/286d821e61e29de8fd6c81abd78b84fea5a44c0b)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

Graph dump by cosim:
WW09.2:
[graph.txt](https://github.com/pytorch/pytorch/files/10846153/graph.txt)

WW08.4:
[graph.txt](https://github.com/pytorch/pytorch/files/10846159/graph.txt)

### Versions

Minified repro:

```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/timm_models.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only regnety_002  --cold_start_latency --batch_size 1 --threads 1
```

cc @ngimel @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by XiaobingSuper** [comment]
The regression was caused by https://github.com/pytorch/pytorch/pull/92125, need to further see why to have such big performance regression.

**Comment by wconstab** [comment]
could you guys try this patch and see if it helps perf for you? I haven't done perf benchmarks on it yet and still seeing if i can get it to pass CI or if it's an OK approach. 
https://github.com/pytorch/pytorch/pull/95931

Also, i'm wondering why cpu perf got hit harder than cuda perf for this same model.  (I am not sure but do we run this model in our cuda benchmarks?)  I would expect in general, the overhead from dynamo guards is the same for cuda or cpu on the same model, but the cuda runtime is faster than the cpu runtime.  If those are both true, then the impact of the slow guards should show up as a worse overall regression for cuda than for CPU.  Maybe we just haven't tested this model on cuda.

**Comment by wconstab** [comment]
I already landed #95931 but would like to ask if you can rerun the benchmark and confirm the impact.

**Comment by ESI-SYD** [comment]
Thanks @XiaobingSuper @wconstab ,Performance data improved to **0.0065393** in 2023-03-05 nightly release benchmark.

**Comment by XiaobingSuper** [comment]
> could you guys try this patch and see if it helps perf for you? I haven't done perf benchmarks on it yet and still seeing if i can get it to pass CI or if it's an OK approach. #95931
> 
> Also, i'm wondering why cpu perf got hit harder than cuda perf for this same model. (I am not sure but do we run this model in our cuda benchmarks?) I would expect in general, the overhead from dynamo guards is the same for cuda or cpu on the same model, but the cuda runtime is faster than the cpu runtime. If those are both true, then the impact of the slow guards should show up as a worse overall regression for cuda than for CPU. Maybe we just haven't tested this model on cuda.

@wconstab, thanks, yes I need to see why cpu perf got hit harder than cuda perf for this same model at the next step.
