### ISSUE TITLE
Counter-intuitive behavior of expand and arithmetic op

### ISSUE THREAD

**Issue by MatthiasKohl** [pytorch/pytorch#957]
I don't know if this is a bug (and it might have been reported already but I didn't find anything).
But it could at least be added to the documentation for the `expand` operation on a tensor:
```python
import torch
T = torch.Tensor([2]).expand(1,3)
print(T.mul_(2))  # expected a Tensor with [4 4 4] here, got [16, 16, 16]
```
Even if you are aware that expand doesn't copy data, I believe most will find this result quite counter-intuitive. Of course, this can be fixed atm either by replacing `expand` by `repeat` or `mul_` by `mul`, but that requires more memory. It would be awesome if the arithmetic ops like `mul` had a special case when the tensor's `stride` is 0 in some dimension

Edit: My torch version string is `0.1.10_2`

**Comment by apaszke** [comment]
Yeah it's a known thing and it is expected. We could think on improving that in the future, but it's super low priority. It's been like that in Lua torch for years now. That's why we don't recommend using in-place ops, unless you're aware of how the library works, and really want to squeeze out the last bits of perf.

**Comment by fmassa** [comment]
There are a lot of caveats that happen when you use zero-strided tensors and inplace operations, another example can be found in [here](https://github.com/torch/torch7/issues/289).
I'd go with @apaszke recommandation of using in-place ops with care.

**Comment by MatthiasKohl** [comment]
Ok I wasn't aware this was already a known thing in torch, I didn't come across it before. Thank you for the insight !
