### ISSUE TITLE
[FSDP] slow init phase

### ISSUE THREAD

**Issue by mehdidc** [pytorch/pytorch#95728]
### 🐛 Describe the bug

There is currently a WIP to integrate FSDP into OpenCLIP (https://github.com/mlfoundations/open_clip/pull/358), which would be extremely useful to train bigger models, thanks a lot btw for all the work that has been done on FSDP.

I observed that at the first forward pass, the run takes a lot of time and the time is proportional to both number of FSDP
units and number of GPU workers. After tracing the runs ,e.g. with 1024 GPUs, I found out that the code takes a lot of time in these these two for loops: https://github.com/pytorch/pytorch/blob/85e0fd0280948a342a916429448fed2486e82aa5/torch/distributed/fsdp/_exec_order_utils.py#L235  https://github.com/pytorch/pytorch/blob/85e0fd0280948a342a916429448fed2486e82aa5/torch/distributed/fsdp/_exec_order_utils.py#L255
With a world size of 1024  the full starting phase (time needed to complete the first forward pass) took **13mins** for ViT-B/32, **16mins** for ViT-L/14, and **28mins** for ViT-g/14. Here, we wrap each residual block as an FSDP unit, and since the `check_order` function is called for each FSDP unit, it is slower as we use deeper models.

After investigating, I found that that the reason it is so slow is that there is a repeated access to a Tensor that is in GPU to make a comparison https://github.com/pytorch/pytorch/blob/85e0fd0280948a342a916429448fed2486e82aa5/torch/distributed/fsdp/_exec_order_utils.py#L242 (in the `if` statement ) e.g. with 1024 world size, we do that around 1M times  (~0.5M for each for loop) for each FSDP unit.

There might be another solution, but a simple solution I  found to have acceptable starting phase time is just to move the tensors (`world_num_valid_indices` and `world_indices`) to cpu with `.cpu()` before the for loops, after doing that the starting phase took much less time, e.g. each for loop took ~12 secs before (if in gpu), and 1.5 secs if we move to cpu. I could open a PR on that if that would be a possible solution.

Simple example to reproduce:

```python
import itertools
import torch
import time
t0 = time.time()
world_size = 1024
ws = torch.range(0, world_size)
ws = ws.cuda() # or cpu() to compare
c = itertools.combinations( ((rank,ws[rank]) for rank in range(world_size)), 2)
for (r1, n1), (r2, n2) in c:
    if n1 != n2:
        pass
print(time.time() - t0)
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230218+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.7 (Green Obsidian) (x86_64)
GCC version: (GCC) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.28

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB

Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        8
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7402 24-Core Processor
Stepping:            0
CPU MHz:             2800.000
CPU max MHz:         2800.0000
CPU min MHz:         1500.0000
BogoMIPS:            5600.23
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-5,48-53
NUMA node1 CPU(s):   6-11,54-59
NUMA node2 CPU(s):   12-17,60-65
NUMA node3 CPU(s):   18-23,66-71
NUMA node4 CPU(s):   24-29,72-77
NUMA node5 CPU(s):   30-35,78-83
NUMA node6 CPU(s):   36-41,84-89
NUMA node7 CPU(s):   42-47,90-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] open-clip-torch==2.11.0
[pip3] pytorch-lightning==1.7.6
[pip3] pytorch-triton==2.0.0+c8bfe3f548
[pip3] segmentation-models-pytorch==0.1.3
[pip3] torch==2.0.0.dev20230218+cu117
[pip3] torchaudio==2.0.0.dev20230218+cu117
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.0
[pip3] torchsde==0.2.5
[pip3] torchvision==0.15.0.dev20230218+cu117
[conda] cudatoolkit               11.7.0              hd8887f6_11    conda-forge
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] open-clip-torch           2.11.0                    dev_0    <develop>
[conda] pytorch-lightning         1.7.6                    pypi_0    pypi
[conda] pytorch-triton            2.0.0+c8bfe3f548          pypi_0    pypi
[conda] segmentation-models-pytorch 0.1.3                    pypi_0    pypi
[conda] torch                     2.0.0.dev20230218+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230218+cu117          pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
[conda] torchmetrics              0.11.0                   pypi_0    pypi
[conda] torchsde                  0.2.5                    pypi_0    pypi
[conda] torchvision               0.15.0.dev20230218+cu117          pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
Thanks for the detailed investigation!

Please feel free to open the PR implementing the solution you mentioned. Do you know if that solution is sufficient for your OpenCLIP use case, or do we need to triage further?
