### ISSUE TITLE
free(): invalid pointer Aborted (core dumped)

### ISSUE THREAD

**Issue by never-to-never** [pytorch/pytorch#95770]
### 🐛 Describe the bug

I am using pytroch2.0 for model training. When I did not use torch.compile to compile a model, the network was trained normally, but when I used torch.compile, an error appeared after the training "free(): invalid pointer Aborted (core dumped)", what is the cause of this?

### Error logs

![image](https://user-images.githubusercontent.com/27321035/222084590-ee3eff4a-188b-462f-859f-2497be292fc6.png)

### Minified repro

Below is the main file I run：

import numpy as np
import json
import matplotlib.pyplot as plt
from time import time as tm
import TorchSeq2PC as T2PC
import torch 
torch.manual_seed(0)
from torchvision.datasets import MNIST, CIFAR10
import torchvision 
import torch.nn as nn
torch.set_float32_matmul_precision('high')

train_dataset = MNIST('./datasets/', 
      train=True, 
      transform=torchvision.transforms.ToTensor(),  
      download=True)

m = len(train_dataset)

batch_size = 300      # Batch size to use with training data

# Create data loader. 
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=True)

# Choose device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('device = ',device)

# Define the nunmber of epochs, learning rate, 
# and how often to print progress
num_epochs=10
LearningRate=.002
PrintEvery=50

# Choose an optimizer
WhichOptimizer=torch.optim.Adam

# Compute size of each batch
steps_per_epoch = len(train_loader) 
total_num_steps  = num_epochs*steps_per_epoch
print("steps per epoch (mini batch size)=",steps_per_epoch)

model=nn.Sequential(
    
    nn.Sequential(nn.Conv2d(1,10,3),
    nn.ReLU(),
    nn.MaxPool2d(2)
    ),

    nn.Sequential(
    nn.Conv2d(10,5,3),
    nn.ReLU(),
    nn.Flatten()
    ),

 nn.Sequential(    
    nn.Linear(5*11*11,50),
    nn.ReLU()
    ),

 nn.Sequential(    
    nn.Linear(50,30),
    nn.ReLU()
    ),

nn.Sequential(
   nn.Linear(30,10)
 )

).to(device)

model = torch.compile(model)

# Define the loss function
LossFun = nn.CrossEntropyLoss()

# Compute one batch of output and loss to make sure
# things are working
with torch.no_grad():
  TrainingIterator=iter(train_loader)
  X,Y=next(TrainingIterator)  
  X=X.to(device)
  Y=Y.to(device)
  Yhat=model(X).to(device)
  print('output shape = ',Yhat.shape)
  print('loss on initial model = ',LossFun(Yhat,Y).item())

NumParams=sum(p.numel() for p in model.parameters() if p.requires_grad)
print('Number of trainable parameters in model =',NumParams)

"""
# The next code cell defines hyperparameters for `PCInfer`

The hyperparameter `ErrType` controls which algorithm to use for computing the
beliefs and prediction errors. It should be equal to `'Strict'`, `'FixedPred'`,
or `'Exact'`. `'Strict'` uses a strict interpretation of predictive coding 
(without the fixed prediction assumption), `'FixedPred'` uses the fixed prediction
assumption, and `'Exact'` computes the exact gradients (same as those computed by 
backpropagation). See "On the relationship between predictive coding and 
backpropagation" for more information on these algorithms.
"""
ErrType="Exact"
eta=.1
n=20

def loss_fun(predict, target):
    pass

def acc_fun(predict, target):
    return (torch.sum(torch.argmax(predict, axis=1) == target) / len(predict)).item()  

# Define the optimizer
optimizer = WhichOptimizer(model.parameters(), lr=LearningRate)

# Initialize vector to store losses
LossesToPlot=np.zeros(total_num_steps)

j=0     # Counters
jj=0   
epoch_time_list = []
step_time_list = []
loss_list = []
acc_list = []
 # Get start time
for k in range(num_epochs):
  t1=tm()
  # Re-initialize the training iterator (shuffles data for one epoch)
  TrainingIterator=iter(train_loader)
  
  # for i in range(steps_per_epoch): # For each batch
  for i in range(steps_per_epoch): # For each batch
    step_time_start = tm()
    # Get one batch of training data, reshape it
    # and send it to the current device        
    X,Y=next(TrainingIterator)  
    X=X.to(device)
    Y=Y.to(device)

    # Perform inference on this batch
    vhat,Loss,dLdy,v,epsilon=T2PC.PCInfer(model,LossFun,X,Y,ErrType,eta,n)
    acc = acc_fun(vhat[-1], Y)
    # print("",Loss)
    # Update parameters    
    optimizer.step() 

    # Zero-out gradients     
    model.zero_grad()
    optimizer.zero_grad()
    step_time_end = tm()
    
    #  将每一个batch_size的时间统计下来
    step_time_list.append(step_time_end -step_time_start)
    # loss_list.append(Loss.item())
    # acc_list.append(acc_fun(vhat[-1], Y))

    # Print and store loss
    # with torch.no_grad():
    #   if(i%PrintEvery==0):
    #     print('epoch =',k,'step =',i,'Loss =',Loss.item())
    #   LossesToPlot[jj]=Loss.item() 
    #   jj+=1

  # Compute and print time spent training
  tTrain=tm()-t1
  epoch_time_list.append(tTrain)
  print('Epoch: {} / {} \t acc:{} \t loss: {} '.format(k, tTrain, acc, Loss))

with open("./{}_cifar10.json".format(ErrType), "w") as f:
  json.dump({"epoch_time": epoch_time_list,  "step_time": step_time_list}, f)
  # json.dump({"epoch_time": epoch_time_list, "train_acc": acc_list, "train_loss": loss_list, "step_time": step_time_list}, f)

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230202+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100 80GB PCIe
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.4.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         1004.080
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5800.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1 MiB
L2 cache:                        40 MiB
L3 cache:                        48 MiB
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230202+cu116
[pip3] torchaudio==2.0.0.dev20230201+cu116
[pip3] torchvision==0.15.0.dev20230201+cu116
[conda] Could not collect

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by mlazos** [comment]
Hi @never-to-never, can you paste all of your code as one block of text that I can copy and paste to run? The formatting under "Compute size of each batch" isn't correct and I'm not sure exactly what code I should be running from there.

**Comment by never-to-never** [comment]
[example_mnist.txt](https://github.com/pytorch/pytorch/files/10866542/example_mnist.txt)
[TorchSeq2PC.txt](https://github.com/pytorch/pytorch/files/10866543/TorchSeq2PC.txt)

@mlazos I uploaded two text files with the code that I run

**Comment by never-to-never** [comment]
@mlazos Sorry to bother you, are you currently sure what the problem is and do you have a solution?

**Comment by mlazos** [comment]
closing in favor of https://github.com/pytorch/pytorch/issues/96047
