### ISSUE TITLE
Can we add nn.ZeroPad1d/3d like nn.ZeroPad2d ?

### ISSUE THREAD

**Issue by liufeimath** [pytorch/pytorch#95796]
### 🚀 The feature, motivation and pitch

Feature request: Add nn.ZeroPad1d/3d like nn.ZeroPad2d.
Motivation:
1. Improve usability.
2. To be consistent with the other padding layers. `Reflection`, `Replication` and `Constant` Padding all have 1d/2d/3d available. Only `ZeroPad` is 2d exclusive (for now). We should do this small improvement to make it a little bit nicer.

cc @albanD @mruberry @jbschlosser @walterddr @saketh-are

**Comment by soulitzer** [comment]
Thanks for your request, we'd be happy to review a PR to add this feature.

**Comment by soulitzer** [comment]
@liufeimath would you be interested in taking a look at this?

**Comment by liufeimath** [comment]
I'm sorry but I'm not familiar with the detailed structure of the pytorch source code repo. I'd rather leave it to professionals like you folks to handle this. Thank you!

**Comment by soulitzer** [comment]
For anyone interested in working on this:
- Note that ZeroPadNd is a special case of ConstantPadNd, and we should only need to subclass the corresponding constant pad module `torch/nn/modules/padding.py`
- Similar case for the cpp module `torch/csrc/api/src/nn/modules/padding.cpp`
- For testing, look at examples in `torch/testing/_internal/common_modules.py`

**Comment by guptaaryan16** [comment]
Hey can I take up this issue, I am new to PyTorch codebase and may need some time to be familiar but think I can work on this issue

**Comment by rishub-tamirisa** [comment]
@soulitzer Hello, I see that the issue is already assigned, but this is part of the codebase I was already familiar with from a prior project and I was able to get a working implementation ready for a PR. I hope it's still acceptable to submit!

**Comment by soulitzer** [comment]
Thanks @rishub-tamirisa for the quick PR. Yes, anyone is free to work on anything and we'll happily review and merge things that satisfy our requirements.
