### ISSUE TITLE
FSDP - Avoid loading all parameters to GPU before cpu offloading, which is necessary to load large models

### ISSUE THREAD

**Issue by jingqiao** [pytorch/pytorch#95813]
### Context 
We are working on large language models with FSDP. We turn on cpu offloading to explore larger models.

### Issue
The largest model we can load with cpu offloading seems upper-bounded by the size of the whole model, instead of a Transformer block being wrapped by FSDP. This significantly limits the maximal size of large models we can explore.

### Reason
After diving deep, we find the limitation comes from `_move_module_to_device` in [torch/distributed/fsdp/_init_utils.py](https://github.com/pytorch/pytorch/blob/ef731cdaf04ef67dce99e42dc98bfc3722f8d89a/torch/distributed/fsdp/_init_utils.py#L802) 
```
        if param.device == cpu_device:
            # NOTE: This includes moving ignored modules' parameters.
            module = module.to(device_from_device_id)
            # TODO: This is a temporary fix to move already-constructed
            # `FlatParameter`s back to CPU if needed. This is needed to
            # make CPU offload work with `device_id`.
            for submodule in module.modules():
                if (
                    isinstance(submodule, fsdp_file.FullyShardedDataParallel)
                    and submodule.cpu_offload.offload_params
                ):
                    for handle in submodule._handles:
                        handle.flat_param_to(torch.device("cpu"))
```
Obviously, the whole module is loaded to GPU before its submodules are offloaded back to cpu. In the FSDP initialization, a model and its submodules are recursively called and wrapped by FSDP. A very last step is to wrap the whole model, and causes the issue we observed above. 

There is a `NOTE` in the above code, making us think it might be due to a design choice for some other good reasons. So, it seems suitable for us to submit this as a feature request, instead of reporting it as a bug. There is also a `TODO` in the above code; however it is not clear whether it is to exactly address the same issue we discussed here. 

### Workaround
As a workaround, we define a function `_move_modules_not_under_fsdp_offload_to_device` to only load to GPU the modules that are not under another FSDP modules with cpu_offload. That is, we replace the line of
```
            module = module.to(device_from_device_id)
```
by 
```
            _move_modules_not_under_fsdp_offload_to_device(module, device_from_device_id)
```
with the following def:
```
def _move_modules_not_under_fsdp_offload_to_device(module, device):    
    if not (
        isinstance(module, fsdp_file.FullyShardedDataParallel)
        and module.cpu_offload.offload_params
    ):
        for key, param in module._parameters.items():
            if param is not None:
                module._parameters[key] = param.to(device, non_blocking=True)

        for submodule in module.children():
            _move_modules_not_under_fsdp_offload_to_device(submodule, device)
```

### Feature Request
We's like to request a feature that avoids loading all parameters to GPU before cpu offloading, because it is important to load large models. 

Please review if the above workaround makes sense (or better off to combine it with the subsequence code of cpu offloading in `_move_module_to_device`). We are willing to submit a PR if it helps.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
Thanks for this issue! This is a great investigation and point.

Like the other backward resharding issue, let me discuss with the other FSDP developers, though this one should be easier to fix (especially since you already have one way to fix).

**Comment by jon-chuang** [comment]
Related: https://github.com/pytorch/pytorch/issues/91165, https://github.com/pytorch/pytorch/issues/94511

**Comment by awgu** [comment]
@albanD What do you think about support for a `nn.Module.to()` method / `nn.Module._apply()` that does not apply recursively to all submodules but only the target module?

For FSDP, we may want to only move some modules but not _all_ submodules to GPU.
