### ISSUE TITLE
Tensor dtype convert without clone

### ISSUE THREAD

**Issue by CuiJinku** [pytorch/pytorch#95828]
### 🚀 The feature, motivation and pitch

For some models, they use [`._to`](https://github.com/pytorch/pytorch/blob/master/torch/storage.py#L132)  to convert a tensor to a specific data type but the original tensors never are used again. In such cases, the [`storage.clone()`](https://github.com/pytorch/pytorch/blob/master/torch/storage.py#L137) here will introduce redundant memory usage. Is it possible to create a new API named `._to_wo_clone`  that gets rid of this storage.clone()?

**Comment by vadimkantorov** [comment]
In a way, are you requesting for inplace `to`?

I guess the main difficulty of src and dst would be if the bitwidths are not the same. So in some cases reallocation would still be needed, and in others the storage would hold on to too much space.

What src/dst dtypes did you have in mind?

(Also if you're interested, there is a `.view(dtype)` method which just reinterprets the same storage without actualy conversion - useful for viewing a byte tensor as float32 tensors)

**Comment by cpuhrsch** [comment]
I'd also like to suggest `.view(dtype)` here if that's what you have in mind?

**Comment by vadimkantorov** [comment]
@albanD if they are the same width, inplace type cast is not the same view (which does reinterpret), so I can imagine in some memory-conscious scenarios, it may be useful to convert inplace int32<>float32 or int16<>bfloat16

**Comment by albanD** [comment]
Well, inplace changing the dtype of a Tensor is very shady business. I'm not sure you ever want to argue for that :p 
And the view(dtype) is not more expensive (both runtime and memory) than the inplace version.

**Comment by vadimkantorov** [comment]
IMO both are shady business. and `.view(dtype)` is not equivalent at all to `.to_(dtype)`

I guess it may make sense for memory savings reasons, e.g. for audio int16<>bfloat16 or some other

**Comment by albanD** [comment]
What would be the exact use case you have in mind?
They are not equivalent for sure, I'm arguing that `.view(dtype)` is easier to use, will work better with other PT components and is not as big a footgun as `.to_(dtype)`.
