### ISSUE TITLE
`Mapper` datapipes: method name as `fn` argument

### ISSUE THREAD

**Issue by PierreGtch** [pytorch/pytorch#95878]
### 🚀 The feature, motivation and pitch

It would be nice to have the possibility to pass a method name as `fn` argument of the `Mapper` datapipes. This would be useful if the `data` elements yielded by the mapper's input datapipe are objects from which a method should be called. That would allow not to have to write a function expressly for that.

```python
class MapperIterDataPipe(IterDataPipe):
    def _apply_fn(self, data):
        if isinstance(self.fn, str):
            return getattr(data, self.fn)()
        else:
            ....
```

Example:
```python
from pathlib import Path
from torch.utils.data.datapipes.iter import IterableWrapper

dp = IterableWrapper([Path('~/file1'), Path('~/file2')])
list(dp.map('expanduser'))
# [Path('/home/joe/file1'), Path('/home/joe/file2')]
```

A potential drawback would be to loose some typing.

### Alternatives

The simple alternative is to write a new function:
```python
from pathlib import Path
from torch.utils.data.datapipes.iter import IterableWrapper

dp = IterableWrapper([Path('~/file1'), Path('~/file2')])
list(dp.map(lambda data: data.expanduser()))
# [Path('/home/joe/file1'), Path('/home/joe/file2')]
```

**Comment by Skylion007** [comment]
Another alternative:
```python
from operator import attrgetter
from pathlib import Path
from torch.utils.data.datapipes.iter import IterableWrapper

dp = IterableWrapper([Path('~/file1'), Path('~/file2')])
list(dp.map(attrgetter('expanduser')))
```
should work as well right? I don't see any need to add a complex Python str overload.

**Comment by PierreGtch** [comment]
Thanks! I didn't know about methodcaller. Indeed it works
