### ISSUE TITLE
The Benchmark test for dynamo runs stuck

### ISSUE THREAD

**Issue by fuaq** [pytorch/pytorch#95874]
### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/40196111/222394368-cb101449-5564-41e3-bc1a-84036edb7316.png

Stay here for a long time, no errors and no warnings.I just want to know what happend

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @soumith

**Comment by fuaq** [comment]
@ezyang

**Comment by mlazos** [comment]
@fuaq, I ran this on nightly pytorch commit fafb410985d2cb94bd95f12f0c392bad9385b643 and it successfully ran, can you try attaching a debugger on your end to see where it is hanging?

**Comment by fuaq** [comment]
> 



> 

@mlazos  it is hanging in Triton ttir to ttgir

**Comment by mlazos** [comment]
Which commit are you running it on? Can you try it on the one I tried? (I'll try it on yours to verify too). I didn't see it in the snippet you posted above.

**Comment by fuaq** [comment]
@mlazos  
![image](https://user-images.githubusercontent.com/40196111/223101030-95d72617-693c-4130-9816-b2dc5943bae4.png)

**Comment by anijain2305** [comment]
@fuaq Do you still see this issue?

**Comment by williamwen42** [comment]
Benchmark doesn't seem to exist anymore.
