### ISSUE TITLE
Unable to convert models to ONNX with Sequential of Sequential in single Module

### ISSUE THREAD

**Issue by ksemianov** [pytorch/pytorch#9587]
## Issue description

Unable to convert models to ONNX  with Sequential of Sequential in single Module. Code example is self explanatory. 

## Code example

```
import torch
from torch import nn

class Net1(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Conv2d(4, 4, 1))

    def forward(self, x):
        return self.net(x)

class Net2(nn.Module):
    def __init__(self):
        super().__init__()
        self.subnet = nn.Sequential(nn.Conv2d(4, 4, 1))
        self.net = nn.Sequential(self.subnet)

    def forward(self, x):
        return self.net(x)

dummy_input = torch.Tensor(1, 4, 256, 256)

print('Started conversion of Net1')
torch.onnx.export(Net1(), dummy_input, 'net1.proto')
print('Finished conversion of Net1')

print('Started conversion of Net2')
torch.onnx.export(Net2(), dummy_input, 'net2.proto')
print('Finished conversion of Net2')
```

Output
```
Started conversion of Net1
Finished conversion of Net1
Started conversion of Net2
Traceback (most recent call last):
  File "export2ONNX.py", line 28, in <module>
    torch.onnx.export(Net2(), dummy_input, 'net2.proto')
  File "/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 26, in export
    return utils.export(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 94, in export
    operator_export_type=operator_export_type)
  File "/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 232, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, operator_export_type)
RuntimeError: /home/pytorch/torch/csrc/jit/export.cpp:296: encodeBlock: Assertion `b->inputs().size() >= num_initializers` failed.
```

## System Info
PyTorch version: 0.5.0a0+54db14e
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.5
GCC version: Could not collect
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.1)
[pip] torch (0.5.0a0+54db14e)
[conda] torch                     0.5.0a0+54db14e           <pip>

PyTorch build command: ```MACOSX_DEPLOYMENT_TARGET=10.13 CC=clang CXX=clang++ python setup.py install```
Clang version: Apple LLVM version 9.1.0 (clang-902.0.39.2)

cc @BowenBao @neginraoof

**Comment by arogozhnikov** [comment]
However, same example works if Net2 is the following.
```
class Net2(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(nn.Sequential(nn.Conv2d(4, 4, 1)))

    def forward(self, x):
        return self.net(x)
```

Hence the problem is in overlapping of parameters for submodels.

**Comment by soumith** [comment]
cc: @houseroad @bddppq

**Comment by daquexian** [comment]
I can confirm this issue still exists in 1.0.0 when parameters overlap @soumith @houseroad @bddppq

**Comment by raghavsonavane** [comment]
https://github.com/pytorch/pytorch/issues/8392#issuecomment-431863763
I was facing the same issue, this resolved my problem.

**Comment by garymm** [comment]
I can't reproduce with latest pytorch nightly version. I'm guessing this got fixed at some point. @ksemianov please check with latest nightly version and close if not reproducible.

**Comment by ksemianov** [comment]
I checked with stable 1.9.0 and it doesn't reproduce anymore
