### ISSUE TITLE
```load_sharded_optimizer_state_dict``` error on multi node

### ISSUE THREAD

**Issue by cavdard** [pytorch/pytorch#95892]
### 🐛 Describe the bug

I am hitting the following error when loading optimizer using FSDP with 2 nodes. No issues when saving/loading optimizer with single node.

```
optim_state = load_sharded_optimizer_state_dict(
    model_state_dict=state_dict["model"],
    optimizer_key="optimizer",
    storage_reader=checkpoint.FileSystemReader(checkpoint_dir),
)
```
Error:
```
optim_state = load_sharded_optimizer_state_dict(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/checkpoint/optimizer.py", line 281, in load_sharded_optimizer_state_dict
    state_dict[key] = _shard_tensor(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/_shard/api.py", line 69, in _shard_tensor
    st = sharding_spec.shard(tensor, src_rank=src_rank, process_group=process_group)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/_shard/sharding_spec/chunk_sharding_spec.py", line 166, in shard
    local_tensor = torch.empty(
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```

### Versions

```
PyTorch version: 2.0.0.dev20230227+cu117
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by mrshenli** [comment]
cc @wz337 for distributed checkpoint issues

> RuntimeError: CUDA error: invalid device ordinal

Looks like the checkpoint was saved on a node with more devices than where it is loaded?

**Comment by ShinoharaHare** [comment]
Encounter same problem here.

**Comment by wz337** [comment]
> Encounter the same problem here. It seems to try to create a tensor on device like `cuda:31`, which is a global rank index.

Could you provide a bit context of your setup as well? Thanks!

**Comment by ShinoharaHare** [comment]
> > Encounter the same problem here. It seems to try to create a tensor on device like `cuda:31`, which is a global rank index.
> 
> Could you provide a bit context of your setup as well? Thanks!

I used 8 nodes with 8 V100 on each node, and save/load the sharded state dict using the following code.

```python
with FSDP.state_dict_type(
    model,
    StateDictType.SHARDED_STATE_DICT,
):
    state_dict = {
        'model': model.state_dict(),
        'optimizer': FSDP.optim_state_dict(model, optimizer)
    }

    save_state_dict(state_dict, FileSystemWriter(ckpt_path))
```

```python
with FSDP.state_dict_type(
    model,
    StateDictType.SHARDED_STATE_DICT,
):
    storage_reader = FileSystemReader(ckpt_path)
    state_dict = {
        'model': model.state_dict(),
    }
    load_state_dict(state_dict, storage_reader)
    state_dict |= load_sharded_optimizer_state_dict(
        model_state_dict=state_dict['model'],
        optimizer_key='optimizer',
        storage_reader=storage_reader,
    )
```

Error occurred during `load_sharded_optimizer_state_dict` call.

**Comment by ShinoharaHare** [comment]
@wz337
Sorry for bothering, I know here is not for questions, but just a quick question, I wonder if the sharded state dict supports loading on different network topology.

**Comment by wz337** [comment]
> > > Encounter the same problem here. It seems to try to create a tensor on device like `cuda:31`, which is a global rank index.
> > 
> > 
> > Could you provide a bit context of your setup as well? Thanks!
> 
> I used 8 nodes with 8 V100 on each node, and save/load the sharded state dict using the following code.
> 
> ```python
> with FSDP.state_dict_type(
>     model,
>     StateDictType.SHARDED_STATE_DICT,
> ):
>     state_dict = {
>         'model': model.state_dict(),
>         'optimizer': FSDP.optim_state_dict(model, optimizer)
>     }
> 
>     save_state_dict(state_dict, FileSystemWriter(ckpt_path))
> ```
> 
> ```python
> with FSDP.state_dict_type(
>     model,
>     StateDictType.SHARDED_STATE_DICT,
> ):
>     storage_reader = FileSystemReader(ckpt_path)
>     state_dict = {
>         'model': model.state_dict(),
>     }
>     load_state_dict(state_dict, storage_reader)
>     state_dict |= load_sharded_optimizer_state_dict(
>         model_state_dict=state_dict['model'],
>         optimizer_key='optimizer',
>         storage_reader=storage_reader,
>     )
> ```
> 
> Error occurred during `load_sharded_optimizer_state_dict` call.

Thanks for sharing. I just landed a fix that should fix the invalid device ordinal. https://github.com/pytorch/pytorch/pull/98063

**Comment by wz337** [comment]
> @wz337 Sorry for bothering, I know here is not for questions, but just a quick question, I wonder if the sharded state dict supports loading on different network topology.

What specific network topology are you looking for?

Note that load_sharded_optimizer_state_dict() currently only works with FSDP.

**Comment by ShinoharaHare** [comment]
> > @wz337 Sorry for bothering, I know here is not for questions, but just a quick question, I wonder if the sharded state dict supports loading on different network topology.
> 
> What specific network topology are you looking for?
> 
> Note that load_sharded_optimizer_state_dict() currently only works with FSDP.

For example, I first used 8 nodes to train and save the sharded state dict, can I load it on 4 nodes or 16 nodes to continue the training? Or when the training is done, can I load it on a machine with no GPU, then somehow extract only the model weights for deployment?

**Comment by wz337** [comment]
Ye. You would be able to do that. SHARDED_STATE_DICT supports resharding. So you can save and load from different number of GPUs. 

As for inference, I believe you can use FULL_STATE_DICT with the offload_to_cpu option. However, you do need a machine with GPU as FSDP works with GPU only.

Reference code pointer: https://github.com/pytorch/pytorch/blob/fb7b3984795a35155e58736b6d415eb64a1f4b66/torch/distributed/fsdp/fully_sharded_data_parallel.py#L608

**Comment by ShinoharaHare** [comment]
I see. Thanks a lot for explaining patiently!
