### ISSUE TITLE
Segmentation fault (segfault) when returning a None gradient for a part of a graph that requires gradient

### ISSUE THREAD

**Issue by MatthiasKohl** [pytorch/pytorch#959]
This is more of an enhancement, but the following code will produce a segfault:

```python
import torch
import torch.nn as nn
from torch.autograd import Function, Variable


class Foo1(Function):

    def __init__(self):
        super(Foo1, self).__init__()

    def forward(self, i, label):
        self.save_for_backward(i, label)
        # return -i.sum()
        return -i.sum(0).sum(1).view(1)

    def backward(self, grad_output):
        i, label = self.saved_tensors
        return -grad_output.expand_as(i), None


class Foo1Loss(nn.Module):

    def __init__(self):
        super(Foo1Loss, self).__init__()

    def forward(self, i, label):
        return Foo1()(i, label)


f = Foo1Loss()
v_in = Variable(torch.randn(1, 10), requires_grad=True)
v_lab = Variable(torch.Tensor([1]), requires_grad=True)
v_out = f(v_in, v_lab)
v_out.backward()
```

I followed the implementation of a custom Loss/Module closely as in the docs/source code. This code will produce a segfault on my machine (Linux Debian 3.16.36, torch version `0.1.10_2`). The segfault might be related to issue #531 .

By the way, when uncommenting the `return -i.sum()` line in `forward` of `Foo1`, the error is `RuntimeError: data must be a Tensor`. This is of course because `forward` is not returning a `Tensor` but the error description is not so obvious as it happens only when the `Foo1Loss` module returns that value, so it's not that obvious what the error means. Maybe changing it to `returned data must be a Tensor` would be a bit clearer, but I guess I'm being pedantic :)

**Comment by albanD** [comment]
Cannot reproduce from current master (b1c2714ad51fb765710f8c5b8fd7d8253219eca1), I get the following error message
```
Traceback (most recent call last):
  File "tmp.py", line 34, in <module>
    v_out.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 146, in backward
    self._execution_engine.run_backward((self,), (gradient,), retain_variables)
RuntimeError: Function 'Foo1' missing gradient at 1
```

**Comment by apaszke** [comment]
I can confirm that it raises a clear error in a master build.
