### ISSUE TITLE
Feature request: `dynamo.export` to support `fake` model and inputs

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#95900]
### 🚀 The feature, motivation and pitch

In `dynamo.export`, unlike `dynamo.optimize`, users mostly don't care about the `result_traced` produced by running the `optimize_assert` wrapped callable. In fact the `result_traced` is not returned by `dynamo.export` anyway. The goal of export is to retrieve only the exported fx graph and guards. 

Hence it would be great if `dynamo.export` could support models and inputs that are already in fake mode. To greatly increase export efficiency and reduce memory requirements. Currently a segfault is produced.

Looking forward to hear your thoughts on this.

@jansel @voznesenskym 

### Example

```python
import torch
import torch._dynamo
from torch._subclasses import fake_tensor


class Model(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.linear = torch.nn.Linear(2, 2)
        self.linear2 = torch.nn.Linear(2, 2)

    def forward(self, x):
        return self.linear2(self.linear(x))

with fake_tensor.FakeTensorMode(allow_non_fake_inputs=True, allow_fallback_kernels=False):
    model = Model()
    x = torch.rand(2, 2)

    print("fake eager:", model(x))

    print("fake dynamo export:")
    graph_module, guards = torch._dynamo.export(
        model, x, aten_graph=True
    )
    graph_module.print_readable()
```
```
$ python fake_export.py 
fake eager: FakeTensor(FakeTensor(..., device='meta', size=(2, 2), grad_fn=<AddmmBackward0>), cpu)
Segmentation fault (core dumped)
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by jansel** [comment]
I think this is a good idea.  I suspect it should be relatively easy to implement.

For your example, it looks like the model is real and so the fake mode is a bit redundant with `tracing_mode="symbolic"` (which does the same thing).

**Comment by BowenBao** [comment]
@jansel Glad to hear it's do-able. Do you have suggestions for a couple of starting points?

For the example I'm moving the model initialization into the context, hope it makes more sense now. Essentially to not do real computations in `export`. The `tracing_mode` argument seems a bit overloaded as it also controls the `dynamic` flag for `optimize_assert`, but I guess we could drop it for now.

**Comment by Chillee** [comment]
cc: @ezyang (and @voznesenskym ) who recently just looked at turning on fake-mode tracing.

**Comment by ezyang** [comment]
IMO export should *default* to fake tracing, and I think it's a bug that it's running it with real inputs. I discussed it with @voznesenskym and Voz was going to look into it.

**Comment by BowenBao** [comment]
@ezyang just to be clear we are talking about fake tracing for these two calls (mainly the first one) right?
https://github.com/pytorch/pytorch/blob/ac07de4a61831bd23e2d3d270890cde3983d9257/torch/_dynamo/eval_frame.py#L680

https://github.com/pytorch/pytorch/blob/ac07de4a61831bd23e2d3d270890cde3983d9257/torch/_dynamo/eval_frame.py#L738-L743

**Comment by jansel** [comment]
@ezyang I think the OP was going a bit further.  It mentioned fake model weights as well as fake inputs.  Also, the ability to create a fake context outside of the call export.

For fake model weights, I think that should work if we remove some asserts.

**Comment by ezyang** [comment]
The problem is dynamo.export also calls the module f with real inputs. jansel's request is also reasonable and we should support it too.

**Comment by wconstab** [comment]
dist compiler also wants a way to init a fake model before tracing.  i think @jansel's proposal is what we want.  cc @anj-s @mrshenli @fegin @lessw2020

**Comment by thiagocrepaldi** [comment]
> The problem is dynamo.export also calls the module f with real inputs. jansel's request is also reasonable and we should support it too.

@ezyang do you think the changes done at https://github.com/pytorch/pytorch/pull/99320 would conflict with the ones needed in this issue? I've just got started on it and will try to enable fake parameters and input through torch.export

**Comment by ezyang** [comment]
It won't, minifier doesn't use torch.export.

**Comment by andrewor14** [comment]
Just want to add that this is affecting the PT2 QAT flow as well. In particular, we're seeing the BN running mean and variance being updated in the export call, which I believe is unexpected. E.g. in this PR (https://github.com/pytorch/pytorch/pull/100271), in order to get the numerics to match between PT2 and FX, we have to add an extra call to BN in the FX flow to mimic this behavior. Any guidance on when a fake tracing alternative will be available is much appreciated.

**Comment by tugsbayasgalan** [comment]
This issue is still present as dynamo is modifying
