### ISSUE TITLE
autograd.functional.jacobian : Return numerical value of f(x).

### ISSUE THREAD

**Issue by maka89** [pytorch/pytorch#95915]
### 🚀 The feature, motivation and pitch

Hi, 
When calculation the jacobian of a (vector) function f(x), it would be nice if the jacobian function could also return the numerical value of f(x) in addition to its jacobian. 
For performance reasons. 
One often ends up needing both. And I would think this would be more performant.. (?)

Basically, one now writes:
```
gi = ginv(x)
dgi = torch.autograd.functional.jacobian(ginv,x)
```

Would be nice if this could end up as:
```
dgi, gi = torch.autograd.functional.jacobian(ginv,x)
```
------

Here is an example of a library that uses this approach... 
https://github.com/autodiff/autodiff/blob/main/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by soulitzer** [comment]
Closing in favor of https://github.com/pytorch/pytorch/issues/70870.
