### ISSUE TITLE
Pylance: torch.cuda.OutOfMemoryError is not a valid exception class

### ISSUE THREAD

**Issue by gerhean** [pytorch/pytorch#95936]
### 🐛 Describe the bug

Pylance does not recognize torch.cuda.OutOfMemoryError as an exception. Using python extension on visual studio code.

Code runs properly, so this is just a typing issue.

## Example use case
```
try:
    self.model = self.model.to("gpu")
except torch.cuda.OutOfMemoryError: 
    self.model = self.model.to("cpu")
```

## Error
![image](https://user-images.githubusercontent.com/16630400/222615800-ff7e3394-e117-4ff5-95b7-91bae6bf57f5.png)

### Versions

PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 12.0.76
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Ti
Nvidia driver version: 528.49
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2100
DeviceID=CPU0
Family=198
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2100
Name=12th Gen Intel(R) Core(TM) i7-12700
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==1.13.1+cu116
[pip3] torchaudio==0.13.1+cu116
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

cc @ngimel @ezyang @malfet @rgommers @xuzhao9 @gramster

**Comment by albanD** [comment]
We would accept a PR fixing this!
