### ISSUE TITLE
computing the KL divergence between normal distribution posterior and Gaussian Mixture model prior

### ISSUE THREAD

**Issue by neuronphysics** [pytorch/pytorch#95955]
### 🚀 The feature, motivation and pitch

Is there any way to compute the KL divergence between a posterior normal distribution  (as an encoder) and a Gaussian Mixture model prior ([MixtureSameFamily](https://pytorch.org/docs/stable/distributions.html#torch.distributions.mixture_same_family.MixtureSameFamily))? Maybe for building a model similar to [this paper](https://arxiv.org/pdf/1611.02648.pdf)?

**Comment by albanD** [comment]
Hi,

We use github issues only for bugs or feature requests.
Please use the forum to ask questions: https://discuss.pytorch.org/
