### ISSUE TITLE
torch.onnx.exporter optimization for expand_as causes error in runtime

### ISSUE THREAD

**Issue by guyang3532** [pytorch/pytorch#95961]
### 🐛 Describe the bug

The exported onnx graph executed wrong with error:
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Expand node. Name:'/Expand' Status Message: invalid expand shape

This may because the optimization of expand_as in https://github.com/pytorch/pytorch/commit/f0054e1a6e04feb2a1a791d5c02da17dadf6d904 

A simple example to reproduce the error:

```
import torch
import onnxruntime

class Model(torch.nn.Module):
  def forward(self, x):
    aa = torch.tensor([[0],[1],[2]])
    return aa.expand_as(x)

x = torch.ones(3,2)
model = Model()
print(model(x))
model_path='./model.onnx.pb'
torch.onnx.export(model,(x,),model_path, input_names=["x"],dynamic_axes={"x": [0, 1]})


ort_session = onnxruntime.InferenceSession(model_path, providers=['CPUExecutionProvider'])

ort_inputs = { 'x': x.numpy() }
output_columns = []
ort_outs = ort_session.run(output_columns, ort_inputs)
```

### Versions

Collecting environment information...
PyTorch version: 1.14.0.dev20221107+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.0
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.0.0-1032-azure-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124

**Comment by guyang3532** [comment]
@BowenBao

**Comment by guyang3532** [comment]
Try to fix it at https://github.com/pytorch/pytorch/pull/95962

**Comment by titaiwangms** [comment]
Close as it's fixed. Thanks for the contribution!
