### ISSUE TITLE
ONNX conversion of JIT scripted model fails

### ISSUE THREAD

**Issue by zshn25** [pytorch/pytorch#95964]
### 🐛 Describe the bug

ONNX conversion of JIT scripted model fails 

```python
import torch
from torchvision.models import resnet18

class Encoder(nn.Module):
    def __init__(self, **kwargs):
        super().__init__()
        self.encoder = resnet18(**kwargs)

    @torch.no_grad()
    def forward(self, x):
        features = []
        x = self.encoder.conv1(x)
        x = self.encoder.bn1(x)
        features.append(self.encoder.relu(x))
        features.append(self.encoder.layer1(self.encoder.maxpool(features[-1])))
        features.append(self.encoder.layer2(features[-1]))
        features.append(self.encoder.layer3(features[-1]))
        features.append(self.encoder.layer4(features[-1]))

        return features
    
enc = Encoder(pretrained=True).eval().to("cuda")
input_image_pytorch = torch.randn((1, 3, 480, 768), requires_grad=False).to("cuda").detach()
scripted_enc = torch.jit.script(enc, input_image_pytorch)

# Export the model
torch.onnx.export(scripted_enc,               # model being run
                  input_image_pytorch,                         # model input (or a tuple for multiple inputs)
                  "encoder.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                #   opset_version=17,          # the ONNX version to export the model to
                  # do_constant_folding=True,  # whether to execute constant folding for optimization. buggy in torch == 1.12
                  input_names = ['input'],   # the model's input names
                  output_names = ['f1', 'f2', 'f3', 'f4', 'f5'], # the model's output names
                  )
```

with the following error

```bash
====== Diagnostic Run torch.onnx.export version 2.0.0a0+ec3941ad.nv23.02 =======
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_5173/4228192073.py", line 2, in <module>
    torch.onnx.export(scripted_model,               # model being run
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1533, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1868, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_helper.py", line 380, in wrapper
    return fn(g, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset9.py", line 1330, in relu
    return _op_with_optional_float_cast(g, "Relu", input, opset_before=14)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/symbolic_opset9.py", line 1296, in _op_with_optional_float_cast
    dtype_0 = _type_utils.JitScalarType.from_value(inputs[0])
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/_type_utils.py", line 197, in from_value
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Cannot determine scalar type for this '<class 'torch.TensorType'>' instance and a default value was not provided.  [Caused by the value 'out.3 defined in (%out.3 : Tensor = onnx::BatchNormalization[epsilon=1.0000000000000001e-05, momentum=0.90000000000000002, training_mode=0](%out, %encoder.encoder.layer1.0.bn1.weight, %encoder.encoder.layer1.0.bn1.bias, %encoder.encoder.layer1.0.bn1.running_mean, %encoder.encoder.layer1.0.bn1.running_var), scope: Model:: # /usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:2450:11
)' (type 'Tensor') in the TorchScript graph. The containing node has kind 'onnx::BatchNormalization'.] 
    (node defined in   File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2450
        _verify_batch_size(input.size())

    return torch.batch_norm(
           ~~~~~~~~~~~~~~~~ <--- HERE
        input, weight, bias, running_mean, running_var, training, momentum, eps, torch.backends.cudnn.enabled
    )
)

    Inputs:
        #0: out defined in (%out : Tensor = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%151, %encoder.encoder.layer1.0.conv1.weight), scope: Model:: # /usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py:459:15
    )  (type 'Tensor')
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+ec3941ad.nv23.02
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (aarch64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.104-tegra-aarch64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          6
On-line CPU(s) list:             0-3
Off-line CPU(s) list:            4,5
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       2
Vendor ID:                       Nvidia
Model:                           0
Model name:                      ARMv8 Processor rev 0 (v8l)
Stepping:                        0x0
CPU max MHz:                     1907.2000
CPU min MHz:                     115.2000
BogoMIPS:                        62.50
L1d cache:                       256 KiB
L1i cache:                       512 KiB
L2 cache:                        4 MiB
L3 cache:                        4 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm dcpop

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] torch==2.0.0a0+ec3941ad.nv23.2
[pip3] torchaudio==0.13.1+b90d798
[pip3] torchvision==0.14.1a0+5e8e2f1
[conda] Could not collect

**Comment by zshn25** [comment]
Also occurs with Pytorch 1.13, 1.12. I think, the problem is with the features list in the forward pass

**Comment by BowenBao** [comment]
Looks like an issue with shape inference with `features list` if model is scripted. Without JIT it should work. Is there any reason to use JIT though?

**Comment by disirulla** [comment]
```
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.siglayer = nn.Sigmoid()
        self.rellayer = nn.ReLU()

    def forward(self, x):
        x = self.rellayer(x)
        return self.siglayer(x)

circuit = Model()

torch.onnx.export(circuit,  torch.rand((1,3,8,8)), "relusig.onnx")
```

When running this code, I am getting the following error, 
```
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
```

Not using JIT. What might be the issue ?

**Comment by zshn25** [comment]
@disirulla, it’s not an error. Seems like export worked

**Comment by BowenBao** [comment]
@zshn25 Usually for onnx export, scripting is only recommended when you have dynamic control flows in your model, which tracing cannot handle. ref: https://pytorch.org/docs/master/onnx.html#tracing-vs-scripting

Closing.
