### ISSUE TITLE
error occured when I convert quantized model to onnx

### ISSUE THREAD

**Issue by liuxubit** [pytorch/pytorch#95970]
### 🐛 Describe the bug

Hello,
      error occured when I convert quantized model to onnx.
      I used torch.fx to do the ptq for yolov5. And after the quantization, the torch2onnx failed. The error shows:
![image](https://user-images.githubusercontent.com/39891612/222759243-a4c385ce-2fb8-4306-beeb-9634a5b1baf7.png)
What can I do to make the concat op support quant?

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by abock** [comment]
Please run `collect_env.py` and provide the output.
