### ISSUE TITLE
[inductor][cpp] xcit_large_24_p8_224 OOM

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#95984]
`xcit_large_24_p8_224` has been hitting OOM intermittently on CI, see https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=inductor_timm_cpu_acc . https://github.com/pytorch/pytorch/pull/94822 somehow makes the issue repeatable.

**Comment by EikanWang** [comment]
Thanks, Bin. I will investigate it.
