### ISSUE TITLE
Encourage dynamo.export users to assume static by default if they call nonzero / unbacked SymInt

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#96033]
### 🐛 Describe the bug

@tugsbayasgalan has observed that on latest master you can end up with a bunch of "cannot guard on unbacked SymInt" failures that look something like `Ne(i0*((s2//2 - 1)//8)**2 + 2*i0*((s2//2 - 1)//8) + i0, ((s2//2 - 1)//8)**2 + 2*((s2//2 - 1)//8) + 1)`. These look complicated but they actually are quite trivial if you can substitute in s2 (in this case, the substitued guard is `Ne(36*i0, 36)`). This could be a legitimate problem if s2 was actually dynamic, but it's pretty common for it to actually be static (and we're just trying to export a "maximally" dynamic model). In this case, upfront marking it as static would solve the problem. We should encourage export users (perhaps by defaulting this way) to assume inputs are static.

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @ngimel @soumith @avikchaudhuri @voznesenskym 

### Versions

master

**Comment by BowenBao** [comment]
> upfront marking it as static would solve the problem

Curious, how to do this?

**Comment by ezyang** [comment]
assume_static_by_default
