### ISSUE TITLE
No speedup and a null pointer exception

### ISSUE THREAD

**Issue by never-to-never** [pytorch/pytorch#96047]
### 🐛 Describe the bug

When I use torch.compile, I don't see any speedup effect, and an error appears after training: "free(): invalid pointer
Aborted (core dumped)“

### Error logs

The running result of torch.compile is not used.
![image](https://user-images.githubusercontent.com/27321035/222939561-c2232e3f-aa2c-47b6-a689-acb05cc14102.png)

Running results after using torch.compile
![image](https://user-images.githubusercontent.com/27321035/222939569-83d6e495-f728-4c88-908f-5b9737494279.png)

### Minified repro

This is the python file I run and I put the code in a text file
[example_mnist.txt](https://github.com/pytorch/pytorch/files/10890684/example_mnist.txt)
[TorchSeq2PC.txt](https://github.com/pytorch/pytorch/files/10890685/TorchSeq2PC.txt)

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230202+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-81-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Quadro GV100
GPU 1: Quadro GV100

Nvidia driver version: 510.73.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          72
On-line CPU(s) list:             0-71
Thread(s) per core:              2
Core(s) per socket:              18
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
Stepping:                        7
CPU MHz:                         1191.653
CPU max MHz:                     3900.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        5200.00
Virtualization:                  VT-x
L1d cache:                       1.1 MiB
L1i cache:                       1.1 MiB
L2 cache:                        36 MiB
L3 cache:                        49.5 MiB
NUMA node0 CPU(s):               0-17,36-53
NUMA node1 CPU(s):               18-35,54-71
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230202+cu116
[pip3] torchaudio==2.0.0.dev20230201+cu116
[pip3] torchvision==0.15.0.dev20230201+cu116
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @soumith

**Comment by mlazos** [comment]
This is a dupe of https://github.com/pytorch/pytorch/issues/95770. 

When I ran this on the nightly I was able to succeed with a batch size of 3, but when running with the original batch_size of 200 I hit an issue with multiprocessing in TorchInductor codegen, I wasn't able to repro your specific issue. Can you try running the nightly and see if the issue still repros (or if you see the issue I'm seeing with multiprocessing?)

**Comment by lukasugar** [comment]
I'm experiencing the same issue. There's no speedup and I get the `free(): invalid pointer` error.

I'm using pytorch 2.0, and my code is running on SageMaker `ml.g4dn.xlarge` instance.

The training completes successfully, but then it crashes because of this error.

**Comment by Chillee** [comment]
Can we get a repro? It's hard to say what the issue might be without an example.

**Comment by sramaswami30** [comment]
Was this issue ever solved? I am also having this.

**Comment by Chillee** [comment]
@sramaswami30 Do you have a repro?

**Comment by sramaswami30** [comment]
I can make one -- my jobs are completing with `backend="eager"` but not with `backend="aot"`. Are there any steps to take to debug in this case? Only see documentation for torchinductor and dynamo errors.

**Comment by tugsbayasgalan** [comment]
Could we get a minified repro for this issue?
