### ISSUE TITLE
Add arm64 builds for libtorch on MacOS with mps support

### ISSUE THREAD

**Issue by kulinseth** [pytorch/pytorch#96046]
### 🚀 The feature, motivation and pitch

I would like to request `arm64` builds for libtorch on MacOS with MPS support enabled. 

cc @malfet @albanD

**Comment by malfet** [comment]
There is already an issue to enable libtorch builds for arm64, and even a PR to do that, but it would be much more efficient to produce it as a side effect of regular wheel build.

**Comment by kulinseth** [comment]
> There is already an issue to enable libtorch builds for arm64, and even a PR to do that, but it would be much more efficient to produce it as a side effect of regular wheel build.

Are there plans to enable arm64 builds ? @malfet. 
Since we are deprecating the x86 ones it will be good to enable the arm64 ones?

**Comment by malfet** [comment]
We had to them since 2.2, so closing this one.
