### ISSUE TITLE
MPS Not Available on Mac 13.x

### ISSUE THREAD

**Issue by source-transformer** [pytorch/pytorch#96066]
### 🐛 Describe the bug

Running a docker container on a mac running Mac OS 13.0 can't run pytorch operations on the GPU.  I.E. 

```
torch.backends.mps.is_available()
```

returns false.

I was going to append to this existing issue (that is already closed):
https://github.com/pytorch/pytorch/issues/78343

but the circumstances are different.

I created the following devcontainer to minimally demonstrate the issue:
https://github.com/source-transformer/docker-pytorch

Just open a terminal and run:

```
python3 test_pytorch.py 
```

Is it possible to give docker containers running on a Mac using 12.3+ the ability to run operations on the GPU?

Thanks!

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (aarch64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          7
On-line CPU(s) list:             0-6
Thread(s) per core:              1
Core(s) per socket:              7
Socket(s):                       1
Vendor ID:                       0x00
Model:                           0
Stepping:                        0x0
BogoMIPS:                        48.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==1.13.1
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
I feel it would be unlikely to get MPS run inside a docker container.

1. The docker runtime should expose Apple Silicon GPU to the container, where I don't see such information noted on the docker docs.
2. Some requirements should be satisfied to get `MPS_FOUND` flag ON so that MPS frameworks can be linked and related functionalities can be enabled.
https://github.com/pytorch/pytorch/blob/dbd41cfa91170458092057397e4ff68f841b83e3/CMakeLists.txt#L103-L134
3. Other issues possibly happen after the above requirements are satisfied.

**Comment by malfet** [comment]
Metal Performance Shader framework is not available on Linux (only available on MacOS/iOS) and therefore it would not accessible inside Linux docker container.
