### ISSUE TITLE
New images CircleCI

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/pytorch#96092]
### 🚀 The feature, motivation and pitch

https://discuss.circleci.com/t/cuda-11-8-gpu-cuda-image-any-plans/47240/3
- windows-server-2022-gui:2022.10.1
- linux-cuda-11:2023.02.1 --> cuda 11.8 and cuda 11.6. They are working to cuda 12.0 end of the month
- ubuntu-2204:2023.02.1 --> ubuntu 22.04

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment]
Howdy! Not entirely sure what the context for this is. We migrated most of our workloads off of CircleCI so this is not really relevant anymore.

**Comment by seemethere** [comment]
Going to go ahead and close this along with the PR associated with this since we don't use these workflows anymore.

**Comment by peri044** [comment]
Hello @johnnynunez  How do I use `linux-cuda-11:2023.02.1` image ?  I couldn't find references to it in https://github.com/pytorch/pytorch/pull/96090. Can you provide any suggestions? Thanks
