### ISSUE TITLE
small bug in torchvision.datasets.ImageFolder

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#9612]
This is not a huge bug, but it is kinda a bug.
In linux sometimes the names are like img.JPEG instead of img.jpeg, and apparently `torchvision.datasets.ImageFolder` is not happy with that and throw an error that it just likes the jpeg not JPEG.
If you guys can consider that that would be nice.
Thanks

**Comment by vishwakftw** [comment]
Please open this issue in [vision](https://github.com/pytorch/vision).
