### ISSUE TITLE
[inductor] Failing HF Models

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#96173]
- [ ] `DebertaV2ForQuestionAnswering` fails with OOM (with cudagraphs enabled). Due to a large number of AutogradFunctions Deberta produces a very large number of graphs:
```
python benchmarks/dynamo/huggingface.py  --accuracy  --backend inductor --float32 --training --dashboard --only DebertaV2ForQuestionAnswering --disable-cudagraphs --explain
cuda train DebertaV2ForQuestionAnswering       PASS
Dynamo produced 101 graphs covering 828 ops with 87 graph breaks (11 unique)
```
we really should fix that (that also regresses performance). @voznesenskym you had an idea how to address that? Unfortunately since we can't change model source we can't slap @allow_in_graph on AutogradFunctions
- [ ] `AllenaiLongformerBase` fails with 
```
AssertionError: Found <class 'torch._inductor.ir.DynamicScalar'>, which is not a supported top level IR node. See [Note: Inductor IR]
ERROR:common:inductor raised LoweringException: AssertionError: Found <class 'torch._inductor.ir.DynamicScalar'>, which is not a supported top level IR node. See [Note: Inductor IR]
  target: aten._local_scalar_dense.default
```
I think it used to be DCE'd, DynamicScalar has the following comment in the code https://github.com/pytorch/pytorch/blob/8ca3c881db3e3510fcb7725389f6a0633c9b992c/torch/_inductor/ir.py#L2929-L2935. It errors out in validate_ir function added in #94361, perhaps the check is overly aggressive. cc @ezyang @soumith @msaroufim @wconstab @bdhirsh

**Comment by ezyang** [comment]
BTW, AllenaiLongformerBase is skipped in CI, which is why regular CI runs did not catch the regression.

**Comment by davidberard98** [comment]
fyi, the torchbench `hf_Longformer` model has the same issue as `AllenaiLongformerBase`. It was missed in the dashboard because it had previously been skipped due to eager_variation.

**Comment by ngimel** [comment]
fwiw I couldn't repro AlllenaiLongformerBase issue locally on yesterdays build, and in any case it should be fixed #96221. @davidberard98 if you have a repro, can you please check if hf_Longformer is fixed?

**Comment by davidberard98** [comment]
hf_Longformer is fixed (or at least the error is now replaced by an OOM)

**Comment by eellison** [comment]
As of https://github.com/pytorch/pytorch/pull/96154 I can at least run DebertaV2ForQuestionAnswering without OOM (although compression is bad because we hit cache limit and fallback to eager).

**Comment by ngimel** [comment]
Right, the proper fix for Deberta is to figure out how to not graph break.
