### ISSUE TITLE
torch.testing.make_tensor does not work for low=high for integral dtypes

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#96179]
It should only fail for 

https://github.com/pytorch/pytorch/blob/3326c14e86ffb8db72219be24302f0804fcbfb57/torch/testing/_creation.py#L88

but

```pycon
>>> torch.testing.make_tensor(5, dtype=torch.float32, device="cpu", low=3, high=3)
tensor([3., 3., 3., 3., 3.])
>>> torch.testing.make_tensor(5, dtype=torch.int32, device="cpu", low=3, high=3)
[...]
RuntimeError: random_ expects 'from' to be less than 'to', but got from=3 >= to=3
```

**Comment by pmeier** [comment]
Thinking about this more, I think the behavior  is somewhat undefined here. Since `high` is exclusive, `low == high` yield the interval `[low, low)`, which doesn't include any values.
It seems that `torch.uniform_`, which we are using for floating point and complex sampling is the outlier since it allows this. `torch.randint`, which we use for integers, or `torch.distributions.Uniform` don't:

```pycon
>>> low = high = 3
>>> torch.empty((5,)).uniform_(low, high)
tensor([3., 3., 3., 3., 3.])
>>> torch.randint(low, high, (5,))
RuntimeError: random_ expects 'from' to be less than 'to', but got from=3 >= to=3
>>> torch.distributions.Uniform(low, high).sample((5,))
ValueError: Uniform is not defined when low>= high
```

IMO, we should raise an expressive error message in these cases and not let the floating point shenanigans slip through.

**Comment by mruberry** [comment]
I would also prefer we throw an error for these empty ranges. What about continuing to allow it with a warning, for now, for float and complex dtypes. That is informative and will start the deprecation process, should we want to continue it. We can raise the proper error for exact dtypes, of course
