### ISSUE TITLE
wrong matrix multiplocation on GPU

### ISSUE THREAD

**Issue by gongshichina** [pytorch/pytorch#96186]
### 🐛 Describe the bug

```python

import torch
# turn off the speed-up that may hurts the precision
torch.backends.cuda.matmul.allow_tf32 = False
torch.backends.cudnn.allow_tf32 = False
torch.backends.cudnn.benchmark = False

print(torch.__version__)
# Out: 1.9.1+cu111

# Suppose I have two SE(3) matrix [R | t], and the t is very big in milllions. 
x = torch.tensor([[-4.6716669202e-01,  8.8406556845e-01, -1.3541741297e-02,
         -3.6795465000e+06],
        [-8.8412499428e-01, -4.6693515778e-01,  1.7163248733e-02,
          2.4627352500e+06],
        [ 8.8503211737e-03,  1.9990688190e-02,  9.9976092577e-01,
         -9.2138648438e+04],
        [ 0.0000000000e+00,  0.0000000000e+00,  0.0000000000e+00,
          1.0000000000e+00]])

y = torch.tensor([[-4.6641114354e-01, -8.8452386856e-01,  8.8395737112e-03,
          4.5921921875e+05],
        [ 8.8449001312e-01, -4.6621400118e-01,  1.7941327766e-02,
          4.4047410000e+06],
        [-1.1748399585e-02,  1.6186550260e-02,  9.9979996681e-01,
          2.0620735168e+01],
        [ 0.0000000000e+00,  0.0000000000e+00,  0.0000000000e+00,
          1.0000000000e+00]])

res_t = x @ y
print(res_t)
# Out:
# tensor([[ 1.0000e+00,  8.3714e-04, -1.8073e-03,  1.2500e+00],
#        [-8.3536e-04,  1.0000e+00,  9.6709e-04,  0.0000e+00],
#       [ 1.8081e-03, -9.6558e-04,  1.0000e+00,  7.8125e-03],
#        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])

res_t = x.cuda() @ y.cuda()
print(res_t)
# Out:
# tensor([[ 1.0000e+00,  8.3715e-04, -1.8073e-03,  1.0000e+00],
#        [-8.3536e-04,  1.0000e+00,  9.6709e-04,  0.0000e+00],
#       [ 1.8081e-03, -9.6558e-04,  1.0000e+00,  7.8125e-03],
#        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]], device='cuda:0')
```
I know the different results comes from big t, but how it occurs? Would you please explain the reason?

### Versions

> Collecting environment information...
PyTorch version: 1.9.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

> OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (GCC) 8.2.0
Clang version: 3.8.0 (tags/RELEASE_380/final)
CMake version: version 3.16.0
Libc version: glibc-2.27

> Python version: 3.8 (64-bit runtime)
Python platform: Linux-4.14.0_1-0-0-36-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: A100-SXM4-40GB
GPU 1: A100-SXM4-40GB
GPU 2: A100-SXM4-40GB
GPU 3: A100-SXM4-40GB
GPU 4: A100-SXM4-40GB
GPU 5: A100-SXM4-40GB
GPU 6: A100-SXM4-40GB
GPU 7: A100-SXM4-40GB

> Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

> Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.1+cu111
[pip3] torchaudio==0.9.1
[pip3] torchvision==0.10.1+cu111
[conda] Could not collect

**Comment by drisspg** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: [ https://discuss.pytorch.org/](https://discuss.pytorch.org/)
