### ISSUE TITLE
SyncBatchNorm doesn't work with FP16 mixed precision training with multiple GPUs

### ISSUE THREAD

**Issue by leonid-pishchulin** [pytorch/pytorch#96203]
### 🐛 Describe the bug

I encountered runtime error when calling `model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)` while using mixed precision training with multiple GPUs.

```
# python -m torch.distributed.launch --nproc_per_node=2 this_file.py
import torch
from torchvision import datasets, transforms
import os
from torch.utils.data.distributed import DistributedSampler
import torch.distributed as dist
import torch.nn as nn
from torch.nn.parallel import DistributedDataParallel as DDP

class SimpleModel(torch.nn.Module):
    def __init__(self, hidden_dim, empty_grad=False):
        super(SimpleModel, self).__init__()
        self.linear = torch.nn.Linear(hidden_dim, hidden_dim)
        self.BatchNorm1d = torch.nn.BatchNorm1d(hidden_dim)
        if empty_grad:
            self.layers2 = torch.nn.ModuleList([torch.nn.Linear(hidden_dim, hidden_dim)])
        self.cross_entropy_loss = torch.nn.CrossEntropyLoss()

    def forward(self, x, y):
        hidden = x
        hidden = self.linear(hidden)
        hidden = self.BatchNorm1d(hidden)

        return self.cross_entropy_loss(hidden, y)

def get_data_loader(model, total_samples, hidden_dim, device):
    batch_size = 8
    train_data = torch.randn(total_samples, hidden_dim, device=device).half()
    train_label = torch.empty(total_samples,
                              dtype=torch.long,
                              device=device).random_(hidden_dim)
    train_dataset = torch.utils.data.TensorDataset(train_data, train_label)
    sampler = DistributedSampler(train_dataset)
    train_loader = torch.utils.data.DataLoader(train_dataset,
                                               batch_size=batch_size,
                                               sampler=sampler)
    return train_loader

def main():
    dist.init_process_group("nccl")
    rank = dist.get_rank()

    hidden_dim = 4
    device_id = rank % torch.cuda.device_count()
    model = SimpleModel(hidden_dim, empty_grad=False).to(device_id)
    model = model.half()
    model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
    ddp_model = DDP(model, device_ids=[device_id]).half()

    data_loader = get_data_loader(model=ddp_model,
                                  total_samples=1000,
                                  hidden_dim=hidden_dim,
                                  device=ddp_model.device)

    for n, batch in enumerate(data_loader):
        loss = ddp_model(batch[0], batch[1])
        if dist.get_rank() == 0:
            print("LOSS:", loss.item())

        if n == 1: break

if __name__ == "__main__":
    main()
```

The issue turns out to be with this function, [torch.batch_norm_gather_stats_with_counts](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=global%20mean%20%26%20invstd-,mean%2C%20invstd%20%3D%20torch.batch_norm_gather_stats_with_counts(,),-self.save_for_backward), which requires count_all, running_mean, running_var to have same dtype. In fp16 mode, running_mean, running_var are fp16, but, count_all is fp32 because it has same dtype as [mean](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=(1)%2C-,dtype%3Dmean.dtype%2C,-device%3Dmean), which is computed [line 25](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=mean%2C%20invstd%20%3D%20torch.batch_norm_stats(input%2C%20eps)) (whose return dtype is fp32 although input's dtype is fp16).

So one solution could be instead of assigning [count.dtype=mean.dtype, line27](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/_functions.py#:~:text=(1)%2C-,dtype%3Dmean.dtype%2C,-device%3Dmean), let count.dtype=running_mean.dtype, or convert count_all.view(-1).to(running_mean.dtype) when calling batch_norm_gather_stats_with_counts

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03)  [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.31
Is CUDA available: N/A
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:                        1
CPU MHz:                         3000.000
CPU max MHz:                     3000.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        4600.01
Hypervisor vendor:               Xen
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsa\
veopt

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torch-model-archiver==0.5.3b20220226
[pip3] torch-workflow-archiver==0.2.6b20221212
[pip3] torchaudio==0.13.1
[pip3] torchserve==0.6.0b20220513
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl    conda-forge
[conda] captum                    0.5.0                         0    pytorch
[conda] cudatoolkit               11.7.0              hd8887f6_11    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] magma-cuda117             2.6.1                         1    pytorch
[conda] mkl                       2022.2.1         h84fe81f_16997    conda-forge
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-cuda              11.7                 h67b0de4_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torch-model-archiver      0.5.3                    py39_0    pytorch
[conda] torch-workflow-archiver   0.2.6                    py39_0    pytorch
[conda] torchaudio                0.13.1               py39_cu117    pytorch
[conda] torchserve                0.6.0                    py39_0    pytorch
[conda] torchtext                 0.14.1                     py39    pytorch
[conda] torchvision               0.14.1               py39_cu117    pytorch
[conda] torchviz                  0.0.2                    pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @mcarilli @ptrblck @leslie-fang-intel @jgong5

**Comment by awgu** [comment]
I want to first double check that your intention is to have `running_mean` and `running_var` in FP16, while the batch norm statistics computed as `mean, invstd = torch.batch_norm_stats(input, eps)` are computed using FP32.

1. Changing `count.dtype=running_mean.dtype` would additionally require casting `mean` and `invstd` to `running_mean.dtype` so that `torch.cat()` can consume the same dtype from all arguments.
https://github.com/pytorch/pytorch/blob/44d8e6c2aa80dbeb2afc1e4471dc1b66bf47779a/torch/nn/modules/_functions.py#L30

2. Adding `count_all.view(-1).to(running_mean.dtype)` might be preferred since it preserves full precision on `mean` and `invstd`, assuming that they do not also need to be cast down to FP16.
https://github.com/pytorch/pytorch/blob/44d8e6c2aa80dbeb2afc1e4471dc1b66bf47779a/torch/nn/modules/_functions.py#L96

As far as I can tell, the second approach should be okay. cc: @mrshenli

**Comment by leonid-pishchulin** [comment]
agree, 2. seems to be a better solution
