### ISSUE TITLE
Dynamic batch size support when combine `torchdynamo.export` and `compile_fx`

### ISSUE THREAD

**Issue by leslie-fang-intel** [pytorch/pytorch#96274]
### 🐛 Describe the bug

When running resnet50, it supports case with batch size changed in eager model. Same as if we capture the fx graph through `torchdynamo.export` with `tracing_mode = "symbolic"`. However, if we combine  `torchdynamo.export` and `compile_fx` together, the generated code still has [fixed batch size value](https://gist.github.com/leslie-fang-intel/8d4e6185aafb86ce93a03e5d6481139d#file-generated-code-py-L5119).
Here is the [example code](https://gist.github.com/leslie-fang-intel/e3f105fda6619c9db8a009aab425ccc9) to reproduce this error. And the running command is: `clear && TORCHDYNAMO_DYNAMIC_SHAPES=1 python test_rn50.py`

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git9e3f173
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.8.10 (default, Jun  4 2021, 15:09:15)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.19.5-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    1
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Genuine CPU
Stepping:              10
CPU MHz:               1341.019
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27
NUMA node1 CPU(s):     28-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==2.1.0a0+git9e3f173
[pip3] torchvision==0.15.0a0+5850f37
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-service               2.4.0           py38h3605609_14    intel
[conda] mkl_fft                   1.3.1           py38hcab1719_22    intel
[conda] mkl_random                1.2.2           py38hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py38hf66a691_32    intel
[conda] numpy                     1.22.3           py38hf0956d0_5    intel
[conda] numpy-base                1.22.3           py38h45c9ace_5    intel

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by leslie-fang-intel** [comment]
cc @Chillee, Please advise where should be the start point to look into this issue. Thanks.

**Comment by leslie-fang-intel** [comment]
cc @Xia-Weiwen @jgong5 @EikanWang

**Comment by leslie-fang-intel** [comment]
@ezyang Thanks for the comment. The actual use scenario is for quantization 2.0. As you can see in the example code [here](https://github.com/pytorch/pytorch/blob/44d8e6c2aa80dbeb2afc1e4471dc1b66bf47779a/test/quantization/fx/test_quantize_pt2e.py#L204-L223). `torchdynamo.export` is used to capture the fx graph and passed into quantization flow of `prepare_pt2e` and `prepare_pt2e`. Then we can lower the quantized graph into inductor. Since it's already a fx graph, we try to avoid re-tracing again in `torch.compile` by using `compile_fx` directly. cc @jerryzh168 here.

**Comment by ezyang** [comment]
ok well the short answer is, you must pass fake tensor example inputs to compile_fx, and the fake tensors have to have symbolic sizes for their inputs

**Comment by williamwen42** [comment]
Is this resolved?
