### ISSUE TITLE
Sparse and CosineLoss only support Float on CUDA

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#963]
These two lines introduce bugs and as @fmassa pointed out, have to be changed to `.is_cuda`
https://github.com/pytorch/pytorch/blob/79f5bf84e54d57a4c81912aeedb0b8a27f97c27e/torch/nn/_functions/loss.py#L13
https://github.com/pytorch/pytorch/blob/28220134371bf9944412e6d232ca20b827a849b4/torch/nn/_functions/thnn/sparse.py#L80

**Comment by fmassa** [comment]
If nobody is working on fixing it, I'll send a PR later today

**Comment by soumith** [comment]
go for it (and thanks :) )

**Comment by fmassa** [comment]
Do you think we should we enable `half`/`double` tests for all `nn` modules?
Enabling tests fro `half` might be tricky because they don't have a CPU counterpart...

**Comment by apaszke** [comment]
Yeah we should do that. We should just compare `half` with `float`

**Comment by fmassa** [comment]
The differences [might be reasonably high though](https://github.com/soumith/cudnn.torch/blob/master/test/test.lua#L12-L16). Maybe we can for the moment assume that if it works for float and double, it should work for half as well, and we add tests for `half` later on?

**Comment by soumith** [comment]
yes. half later on sounds good.
