### ISSUE TITLE
Write a decomp for aminmax

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#96307]
### 🐛 Describe the bug

The operator is

```
- func: aminmax(Tensor self, *, int? dim=None, bool keepdim=False) -> (Tensor min, Tensor max)
  device_check: NoCheck   # TensorIterator
  structured_delegate: aminmax.out
  variants: function, method
```

Look in torch/_decomp/decompositions.py for examples. It may be important to ensure that the decomposition does NOT actually get applied in inductor compilation, as inductor has a direct lowering for aminmax.

Once you're done python test/test_proxy_tensor.py -k aminmax should xpass. Remove the xfail for aminmax. Other tests may xpass too

### Versions

master

cc @SherlockNoMad @ngimel

**Comment by ngimel** [comment]
aminmax decomposition was landed recently, anything wrong with it?
https://github.com/pytorch/pytorch/pull/96039/files#diff-d25ad317caf41c3fdf1de3bcfc730102c9e4a3e68639559017ae45cb0bc26911R3337

**Comment by ezyang** [comment]
my wc too old lol
