### ISSUE TITLE
Self-built of pytorch wheel without having to install mkl in the target environment

### ISSUE THREAD

**Issue by OscarLlorente** [pytorch/pytorch#96303]
### 🐛 Describe the bug

I have built from tag 1.13.1 my own wheel for installation. I tried to use the same features as the official version for cpu (1.13.1+cpu) and that is why I have used mkl for compiling. However, when I try to install my pytorch version in a new environment this error is raised:

```OSError: libmkl_intel_lp64.so: cannot open shared object file: No such file or director```

I know that this will be solved by installing mkl, but how can I create the wheel without this being a requirement, since with the official version this is not required

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
CPU(s):                          8
Model name:                      Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
Hypervisor vendor:               Microsoft

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.1
[pip3] torchvision==0.14.1
[conda] Could not collect

**Comment by dagitses** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions:[ https://discuss.pytorch.org/](https://discuss.pytorch.org/)
