### ISSUE TITLE
Delete functorch-specific CI shards and integrate them into the regular CI configurations

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#96347]
## Motivation

functorch is a part of PyTorch Core and has been for a couple of months. The functorch tests run in [functorch-specific shards](https://github.com/pytorch/pytorch/blob/f5c39b7ba29772c0a40a0b2a12066342b8679aa4/.github/workflows/pull.yml#L30) for CI configurations (instead of the ["default" shards](https://github.com/pytorch/pytorch/blob/master/.github/workflows/pull.yml#L30) that all the other PyTorch Core tests run in).

To make things consistent, we would like the functorch tests to behave just like any other PyTorch Core tests (e.g. autograd, nn) -- they should just go in the "default" shards. This also has the advantage that when new CI configurations are added (e.g. dynamo, other devices), folks won't need to specifically add a functorch shard since functorch tests will be in the default set.

## Things to consider

- Time to signal for PyTorch tests. We don't want to regress this.

## Proposal

For each job configuration (e.g. linux-focal-py3_8-gcc7-build):
1. Delete the functorch shard (if it exists)
2. Make the functorch tests run as a part of the "default" shards
3. Increase the "default" shard count by 1, unless it doesn't make sense.
4. This will make functorch tests run on more configurations than before (e.g. rocm, dynamo). We can either selectively add expected failures and skips to tests or just add one big skip and make it more fine-grained later.

This is almost equivalent to just saying we are turning the functorch shard into a default shard.

Thoughts? If this sounds good, I can start putting up PRs for it. cc @seemethere @malfet @pytorch/pytorch-dev-infra @Chillee @samdow @soumith @kshitij12345 @janeyx99 @huydhn, @pytorch/pytorch-dev-infra

**Comment by malfet** [comment]
cc: @huydhn
