### ISSUE TITLE
Unify _cast_fp_inputs_to_dtype and buffer dtype casting with DDP

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#96380]
### 🐛 Describe the bug

DDP mixed precision uses similar methods as FSDP to cast inputs and buffers, we should unify these under torch.distributed.utils.

### Versions

n/a

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by awgu** [comment]
Marking as triaged because @rohan-varma has self-assigned.
