### ISSUE TITLE
max-autotune mode fails because of dependency on jinja2

### ISSUE THREAD

**Issue by agunapal** [pytorch/pytorch#96445]
### 🐛 Describe the bug

Calling torch.compile with max-autotune mode, asserts because of dependency on jinja2

opt_model = torch.compile(model, mode="max-autotune")

You can find the complete code here

https://github.com/agunapal/examples/blob/pt2.0_example/pt2.0/mnist/main.py#L140:L146

```pip install jinja2``` resolves the issue

### Error logs

)
[2023-03-09 20:54:57,582] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
[2023-03-09 20:54:57,589] torch._inductor.graph: [ERROR] Error from lowering
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/graph.py", line 333, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 225, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/kernel/mm.py", line 133, in tuned_addmm
    mm_template.generate(
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 343, in generate
    assert self.template, "requires jinja2"
AssertionError: requires jinja2
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/graph.py", line 333, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/lowering.py", line 225, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/kernel/mm.py", line 133, in tuned_addmm
    mm_template.generate(
  File "/home/ubuntu/anaconda3/envs/test_2.0_py310/lib/python3.10/site-packages/torch/_inductor/select_algorithm.py", line 343, in generate
    assert self.template, "requires jinja2"
AssertionError: requires jinja2

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1031-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         2799.834
BogoMIPS:                        5599.66
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.0+cu118
[pip3] torchvision==0.15.0+cu118
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.0.0+cu118              pypi_0    pypi
[conda] torchaudio                2.0.0+cu118              pypi_0    pypi
[conda] torchvision               0.15.0+cu118             pypi_0    pypi

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by malfet** [comment]
Jinja2 is a manadatory dependency on trunk, but I was told it's not in release/2.0. Investigating

**Comment by atalman** [comment]
test on 2.0 rc:
```
python testn.py 
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to ../data/MNIST/raw/train-images-idx3-ubyte.gz
100.0%
Extracting ../data/MNIST/raw/train-images-idx3-ubyte.gz to ../data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to ../data/MNIST/raw/train-labels-idx1-ubyte.gz
100.0%
Extracting ../data/MNIST/raw/train-labels-idx1-ubyte.gz to ../data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to ../data/MNIST/raw/t10k-images-idx3-ubyte.gz
100.0%
Extracting ../data/MNIST/raw/t10k-images-idx3-ubyte.gz to ../data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to ../data/MNIST/raw/t10k-labels-idx1-ubyte.gz
100.0%
Extracting ../data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../data/MNIST/raw

[2023-03-09 21:19:46,105] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Train Epoch: 1 [0/60000 (0%)]   Loss: 2.305176
Train Epoch: 1 [6400/60000 (11%)]       Loss: 2.310328
Train Epoch: 1 [12800/60000 (21%)]      Loss: 2.338834
Train Epoch: 1 [19200/60000 (32%)]      Loss: 2.310786
Train Epoch: 1 [25600/60000 (43%)]      Loss: 2.319447
Train Epoch: 1 [32000/60000 (53%)]      Loss: 2.327923
Train Epoch: 1 [38400/60000 (64%)]      Loss: 2.342568
Train Epoch: 1 [44800/60000 (75%)]      Loss: 2.277673
Train Epoch: 1 [51200/60000 (85%)]      Loss: 2.333785
Train Epoch: 1 [57600/60000 (96%)]      Loss: 2.336644
[2023-03-09 21:20:00,208] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Training Time: 22.459798828125

Test set: Average loss: 2.3118, Accuracy: 1066/10000 (11%)

Evaluation Time: 2.059452392578125
Train Epoch: 2 [0/60000 (0%)]   Loss: 2.306753
Train Epoch: 2 [6400/60000 (11%)]       Loss: 2.290078
Train Epoch: 2 [12800/60000 (21%)]      Loss: 2.319357
Train Epoch: 2 [19200/60000 (32%)]      Loss: 2.294908
Train Epoch: 2 [25600/60000 (43%)]      Loss: 2.315574
Train Epoch: 2 [32000/60000 (53%)]      Loss: 2.318267
Train Epoch: 2 [38400/60000 (64%)]      Loss: 2.313136
Train Epoch: 2 [44800/60000 (75%)]      Loss: 2.319537
Train Epoch: 2 [51200/60000 (85%)]      Loss: 2.335049
Train Epoch: 2 [57600/60000 (96%)]      Loss: 2.334135
Training Time: 9.8962734375

Test set: Average loss: 2.3118, Accuracy: 1066/10000 (11%)

Evaluation Time: 1.448700439453125
Train Epoch: 3 [0/60000 (0%)]   Loss: 2.308559
Train Epoch: 3 [6400/60000 (11%)]       Loss: 2.301503
Train Epoch: 3 [12800/60000 (21%)]      Loss: 2.334244
Train Epoch: 3 [19200/60000 (32%)]      Loss: 2.317338
Train Epoch: 3 [25600/60000 (43%)]      Loss: 2.326974
Train Epoch: 3 [32000/60000 (53%)]      Loss: 2.282091
Train Epoch: 3 [38400/60000 (64%)]      Loss: 2.357560
Train Epoch: 3 [44800/60000 (75%)]      Loss: 2.311811
Train Epoch: 3 [51200/60000 (85%)]      Loss: 2.362643
Train Epoch: 3 [57600/60000 (96%)]      Loss: 2.303794
Training Time: 11.1475

Test set: Average loss: 2.3118, Accuracy: 1066/10000 (11%)

Evaluation Time: 1.739639404296875
Train Epoch: 4 [0/60000 (0%)]   Loss: 2.314524
Train Epoch: 4 [6400/60000 (11%)]       Loss: 2.319013
Train Epoch: 4 [12800/60000 (21%)]      Loss: 2.298557
Train Epoch: 4 [19200/60000 (32%)]      Loss: 2.322405
Train Epoch: 4 [25600/60000 (43%)]      Loss: 2.301838
Train Epoch: 4 [32000/60000 (53%)]      Loss: 2.298177
Train Epoch: 4 [38400/60000 (64%)]      Loss: 2.324036
Train Epoch: 4 [44800/60000 (75%)]      Loss: 2.308752
Train Epoch: 4 [51200/60000 (85%)]      Loss: 2.319532
Train Epoch: 4 [57600/60000 (96%)]      Loss: 2.324502
Training Time: 11.11202734375

Test set: Average loss: 2.3118, Accuracy: 1066/10000 (11%)

Evaluation Time: 1.7393426513671875
```
