### ISSUE TITLE
'aten::affine_grid_generator' to ONNX opset version 14 is not supported

### ISSUE THREAD

**Issue by john09282922** [pytorch/pytorch#96449]
### 🐛 Describe the bug

UnsupportedOperatorError: Exporting the operator 'aten::affine_grid_generator' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues

### Versions

torch 1.13.1

**Comment by thiagocrepaldi** [comment]
'aten::affine_grid_generator' is not supported by torch.onnx.export and there is no plan to support it

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
