### ISSUE TITLE
control_flow.{cond/map} graph break due to "output.tracked_fakes mismatch"

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#96473]
### 🐛 Describe the bug

This was reported from Meta internal user case, I managed to have the following minimized repo:
```
import torch
import torch._dynamo
import logging
from functorch.experimental.control_flow import cond
import torch.quantization
from torch.ao.quantization.quantize_fx import prepare_qat_fx
from torch.ao.quantization.experimental.qconfig import uniform_qconfig_8bit

class MyModule(torch.nn.Module):

    def __init__(self):
        super().__init__()
        qconfig_dict = {"object_type": [(torch.nn.Linear, uniform_qconfig_8bit)]}
        example_inputs = (torch.randn(5, 5),)
        self.model = torch.nn.Linear(5, 5)
        self.quantized_model = prepare_qat_fx(self.model, qconfig_dict, example_inputs=example_inputs)

    def forward(self, pred, x):
        def true_fn(x):
            return x.sin() + self.quantized_model(x)

        def false_fn(x):
            return x.cos() + self.model(x)

        return cond(pred, true_fn, false_fn, [x])

module = MyModule()
pred = torch.tensor(True)
x = torch.rand((5, 5))
opt_m = torch._dynamo.optimize("eager")(module)
print(module(pred, x))
print(opt_m(pred, x))
```

This is not an error, it's a graph break which is not expected when working together with ```cond/map```.
```
torch._dynamo.exc.Unsupported: output.tracked_fakes mismatch: ......
```

This is because in [this line](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/torch.py#L927) we check if the ```tracked_fakes``` is identical from true branch and false branch. However, it's different in this example:
```
true_fn: x, pred, self.quantized_model.weight, self.quantized_model.bias)
false_fn: x, pred
```

The quantized model has 2 additional tracked_fakes. After internal discussion, we decide to allow the tracked_fakes divergence, so we propose just remove the above lines.

 

### Versions

N/A

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
You can't just delete the lines. You need to union the tracked fakes together!

**Comment by yanboliang** [comment]
@ezyang I didn't see downstream using the tracked fakes.

**Comment by yanboliang** [comment]
As we discussed, we suspect they are used for guard creation, but I found no. Actually we already merge guards from two branches:
https://github.com/pytorch/pytorch/blob/2f6a371ae901fa266d69fb16585436e04c52d87f/torch/_dynamo/variables/torch.py#L930-L932

Do I understand it correctly?

**Comment by ezyang** [comment]
Tracked fakes are used for SHAPE_ENV guard creation

```
    def SHAPE_ENV(self, guard: Guard):
        # Let's handle ShapeEnv guards.  To do this, we will resolve
        # shape variables to sources from tracked_fakes.  This must happen after
        # tensor checks.
        assert guard.name == ""
        output_graph = self.check_fn_manager.output_graph
        # NB: self.output_graph can be None in the debug_nops tests
        fs = output_graph.tracked_fakes
        guards = output_graph.shape_env.produce_guards(
            [a.fake for a in fs],
            [a.source for a in fs],
            source_ref=self.source_ref,
        )
        for shape_guard in guards:
            self._produce_guard_code(guard, [shape_guard], shape_env=True)
```

Those guards don't go in `dynamo_guards`.

**Comment by yanboliang** [comment]
I see, that makes sense. Thanks for your guidance, I'll send a PR soon.
