### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by albert-github** [pytorch/pytorch#96515]
https://github.com/pytorch/pytorch/blob/987eade3f38cde7113c7241831030c829879bf9b/torch/csrc/jit/docs/serialization.md?plain=1#L136

`constantspkl-Constants-in-code` should be `constantspkl-constants-in-code`

https://github.com/pytorch/pytorch/blob/987eade3f38cde7113c7241831030c829879bf9b/torch/csrc/jit/docs/serialization.md?plain=1#L245

`(#tensors-How-tensors-are-serialized)` should probably be `(#data-how-tensors-are-serialized)`

https://github.com/pytorch/pytorch/blob/987eade3f38cde7113c7241831030c829879bf9b/torch/csrc/jit/JIT-AUTOCAST.md?plain=1#L17
The link `(#mixing-eager-mode-and-scripting-autocast)` doesn't point to anything

https://github.com/pytorch/pytorch/blob/987eade3f38cde7113c7241831030c829879bf9b/torch/csrc/jit/OVERVIEW.md?plain=1#L595

`(#Block)` should be `(#block)`

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @svekars @carljparker @mruberry

**Comment by RishabhSpark** [comment]
Hi! I'd like to take this issue, if possible. Can someone please guide me through this as i'm new to open source and pytorch

**Comment by albert-github** [comment]
Looks like the link in respect to `mixing-eager-mode-and-scripting-autocast` has not been addressed.

**Comment by RishabhSpark** [comment]
> Looks like the link in respect to `mixing-eager-mode-and-scripting-autocast` has not been addressed.

Was unable to find a correct link for that~

**Comment by albert-github** [comment]
I couldn't find anything either (hence there was no suggestion from my side), maybe the line should be removed.
