### ISSUE TITLE
Text and link in RELEASE.md

### ISSUE THREAD

**Issue by albert-github** [pytorch/pytorch#96514]
https://github.com/pytorch/pytorch/blob/987eade3f38cde7113c7241831030c829879bf9b/RELEASE.md?plain=1#L274-L275

Twice the same text?
Link `(#drafting-rcs-release-candidates) ` does not exist, maybe `(#drafting-rcs-release-candidates-for-pytorch-and-domain-libraries)`

cc @malfet @seemethere

**Comment by janeyx99** [comment]
cc @atalman
