### ISSUE TITLE
Tensor flip works unexpectedly on Apple's MPS backend

### ISSUE THREAD

**Issue by vickkot** [pytorch/pytorch#96558]
### 🐛 Describe the bug

torch.flip works differently on "cpu" and "mps" devices: 

flip by first dimension  on cpu
```python
import torch
print(torch.flip(torch.Tensor([ [1, 2, 3] ]).to(torch.device('cpu')), [0]))
```
returns expected result:
```python
tensor([[1., 2., 3.]])
```

flip on mps 
```python
import torch
print(torch.flip(torch.Tensor([ [1, 2, 3] ]).to(torch.device('mps')), [0]))
```
returns different result:
```python
tensor([[3., 2., 1.]], device='mps:0')
```
where internal element's content is reverted
is this expected?

thanks

### Versions

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] numpy                     1.23.5          py310hb93e574_0    anaconda-main-remote
[conda] numpy-base                1.23.5          py310haf87e8b_0    anaconda-main-remote
[conda] pytorch                   1.13.1                 py3.10_0    pytorch-remote
[conda] torchaudio                0.13.1                py310_cpu    pytorch-remote
[conda] torchvision               0.14.1                py310_cpu    pytorch-remote

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by vickkot** [comment]
@qqaatw 
Could you please check that your fix also fixes the following similar type of the problem?

```python
print(torch.flip(torch.Tensor([
    [ [1,2,3] ],
    [ [4,5,6] ]
    ]).to(torch.device('mps')), [1]))
```
returns
```python
tensor([[[6., 5., 4.]],
        [[3., 2., 1.]]], device='mps:0')
```
thank you

**Comment by qqaatw** [comment]
> @qqaatw Could you please check that your fix also fixes the following similar type of the problem?
> 
> ```python
> print(torch.flip(torch.Tensor([
>     [ [1,2,3] ],
>     [ [4,5,6] ]
>     ]).to(torch.device('mps')), [1]))
> ```
> 
> returns
> 
> ```python
> tensor([[[6., 5., 4.]],
>         [[3., 2., 1.]]], device='mps:0')
> ```
> 
> thank you

Yes.

```python
>>> torch.flip(torch.Tensor([ [ [1,2,3] ], [ [4,5,6] ] ]).to(torch.device('cpu')), [1])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])
>>> torch.flip(torch.Tensor([ [ [1,2,3] ], [ [4,5,6] ] ]).to(torch.device('mps')), [1])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]], device='mps:0')
```

**Comment by vickkot** [comment]
@qqaatw 
awesome
thank you so much for your help
