### ISSUE TITLE
tests for linearize fail under the dynamo CI config

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#96559]
See skips over at https://github.com/pytorch/pytorch/blob/acd9df8a72195c226ddbe08fa0381f29cf502f0c/test/functorch/test_eager_transforms.py#L2532

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @Chillee @samdow @kshitij12345 @janeyx99 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @Xia-Weiwen @desertfire

**Comment by malfet** [comment]
@zou3519 please add respective labels when details are there

**Comment by bdhirsh** [comment]
@williamwen42 is this fixed thanks to https://github.com/pytorch/pytorch/pull/114649?

**Comment by williamwen42** [comment]
No, I abandoned the PR because it's failing in CI (but not locally).

**Comment by anijain2305** [comment]
@zou3519 Is this still valid given we are changing how vmap + dynamo works?

**Comment by zou3519** [comment]
This needs to be fixed, but I'd wait for @guilhermeleobas's work on adding support for the other functorch transforms (vmap, grad, jvp) first to see if this issue is relevant after that

**Comment by tugsbayasgalan** [comment]
@zou3519 is there any updates on this?

**Comment by guilhermeleobas** [comment]
@tugsbayasgalan, just submitted https://github.com/pytorch/pytorch/pull/121830 which should remove the `skipIfTorchDynamo` decorator from `TestLinearize`.
