### ISSUE TITLE
Unit test for test_unary_ufuncs.py

### ISSUE THREAD

**Issue by yhl48** [pytorch/pytorch#96607]
### 🐛 Describe the bug

To narrow down the unit test by testing an individual test function, usually the following can be done, as quoted from the PyTorch technical contribution guide

>You can narrow down what you're testing even further by specifying the name of an individual test with TESTCLASSNAME.TESTNAME. Here, TESTNAME is the name of the test you want to run, and TESTCLASSNAME is the name of the class in which it is defined.
Going off the above example, let's say you want to run test_Sequential, which is defined as part of the TestJit class in test/test_jit.py. Your command would be:
`python test/test_jit.py TestJit.test_Sequential`

However, that does not seem to work for `test/test_unary_ufuncs.py`. Running the command

```
python test_unary_ufuncs.py TestUnaryUfuncs.test_float_domains
```

throws the following the error

```
E
======================================================================
ERROR: TestUnaryUfuncs (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'TestUnaryUfuncs'. Did you mean: 'TestUnaryUfuncsCPU'?

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

and replacing `TestUnaryUfuncs` with `TestUnaryUfuncsCPU` gives the following error instead

```
E
======================================================================
ERROR: test_float_domains (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: type object 'TestUnaryUfuncsCPU' has no attribute 'test_float_domains'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)
```

I might be missing something here, any pointer will be much appreciated!

### Versions

```
Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] torch==2.1.0a0+git3e2af70
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2023.0.0         h6d00ec8_25399  
[conda] mkl-include               2023.0.0         h06a4308_25399  
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     2.1.0a0+git3e2af70           dev_0    <develop>
```

**Comment by soulitzer** [comment]
The test with the specific name `TestUnaryUfuncsCPU.test_float_domains` doesn't exist, only the parametrized versions of it exist.

So, I think your options are:
1. Test the exact test: `python test/test_unary_ufuncs.py TestUnaryUfuncsCPU.test_float_domains_erfinv_cpu_float64`
2. Match a pattern: `python test/test_unary_ufuncs.py -k TestUnaryUfuncsCPU.test_float_domains`
