### ISSUE TITLE
MPS cumsum issue - RuntimeError: MPS does not support cumsum op with int64 input. Support has been added in macOS 13.3

### ISSUE THREAD

**Issue by jacobmlloyd** [pytorch/pytorch#96610]
### 🐛 Describe the bug

I'm on a Macbook Pro M1 Pro and I've upgraded to 13.3 Beta 3 - I am running into the `cumsum` issue. I've created 2 new conda environment and installed the nightly version on 3/11/2023 at 12PM PST using
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
and the other using
conda install pytorch torchvision torchaudio -c pytorch-nightly
but I'm still getting `cumsum` errors.
It looks like https://github.com/pytorch/pytorch/pull/96512 may have broken the previous patch, unless I'm missing something? I'm new to this so any help is greatly appreciated!

Code: 
```python3
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model = "Salesforce/codegen-350M-mono"
device = torch.device("mps")

# Load the CodeGen tokenizer and model
print("[+] Initializing Tokenizer")
tokenizer = AutoTokenizer.from_pretrained(model)
print("[+] Finished Initializing Tokenizer")
print("[+] Initializing Model")
model = AutoModelForCausalLM.from_pretrained(model).to(device)
print("[+] Finished Initializing Model")

prompt = "write a hello world function"

# Tokenize the description and generate the code
inputs = tokenizer(prompt, return_tensors="pt")
outputs = model.generate(
    inputs["input_ids"].to('mps'),
    attention_mask = inputs["attention_mask"].to(device),
    min_new_tokens = 10,
    max_new_tokens = 1000,
    pad_token_id = 0,
    eos_token_id = tokenizer.eos_token_id,
    do_sample = True)

generated_code = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(generated_code)
```

Traceback:
```
/Users/lloyd/miniforge3/envs/coding2/lib/python3.9/site-packages/transformers/generation/utils.py:662: UserWarning: MPS: no support for int64 repeats mask, casting it to int32. Support has been added in macOS 13.3 (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1678522277666/work/aten/src/ATen/native/mps/operations/Repeat.mm:229.)
  input_ids = input_ids.repeat_interleave(expand_size, dim=0)
Traceback (most recent call last):
  File "/Users/lloyd/Projects/machine-learning/models/salesforce-live.py", line 155, in <module>
    outputs = model.generate(
  File "/Users/lloyd/miniforge3/envs/coding2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/lloyd/miniforge3/envs/coding2/lib/python3.9/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.sample(
  File "/Users/lloyd/miniforge3/envs/coding2/lib/python3.9/site-packages/transformers/generation/utils.py", line 2440, in sample
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/lloyd/miniforge3/envs/coding2/lib/python3.9/site-packages/transformers/models/codegen/modeling_codegen.py", line 646, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
**RuntimeError: MPS does not support cumsum op with int64 input. Support has been added in macOS 13.3**
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0.dev20230311
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.2
Libc version: N/A

Python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0.dev20230311
[pip3] torchaudio==2.0.0.dev20230311
[pip3] torchvision==0.15.0.dev20230311
[conda] numpy                     1.24.2           py39hff61c6a_0    conda-forge
[conda] pytorch                   2.1.0.dev20230311         py3.9_0    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230311        py39_cpu    pytorch-nightly
[conda] torchvision               0.15.0.dev20230311        py39_cpu    pytorch-nightly

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by kulinseth** [comment]
@jacobmlloyd , I tried the attached script on latest nightly and it didn't show me the error message. Below was the print out.
```
write a hello world function
print(func())
print()

# 2. def a():
# _____________________________________
# 1) def a():
# 2)     return a+b
# 3)     def b():
# 5)       pass
# 5)           return b2
# ______________________________________
print()

# a simple decorator print(print if you want)
def a():   # a(self)
    print("a function")

def b(x):   # b(self, x)
    x


print()
print(f"Before calling b2: {b}")
b(a())
print()

print(f"After calling b2: {b}")
```
 
Here is the pip list:
```
tokenizers                            0.13.2
torch                                 2.1.0.dev20230313
torchaudio                            2.0.0.dev20230222
torchmetrics                          0.11.3
torchvision                           0.15.0.dev20230222
tqdm                                  4.65.0
```

**Comment by jacobmlloyd** [comment]
Hey Kulinseth,

I've started a new Conda environment and installed all packages to those same versions and I still have the same issue. After asking others on M1's, it seems to be the same result. Here is one example: https://github.com/microsoft/visual-chatgpt/issues/37#issuecomment-1465149007

I am on macOS 13.3 Beta 3. Any ideas as to how to solve this issue?

**Comment by kulinseth** [comment]
> Hey @kulinseth ,
> 
> I've started a new Conda environment and installed all packages to those same versions and I still have the same issue. After asking others on M1's, it seems to be the same result. Here is one example: [microsoft/visual-chatgpt#37 (comment)](https://github.com/microsoft/visual-chatgpt/issues/37#issuecomment-1465149007)
> 
> I am on macOS 13.3 Beta 3. Any ideas as to how to solve this issue?

You are indeed right, the MacOS selector check was broken with Beta 1 onwards. With this [PR](https://github.com/pytorch/pytorch/pull/96733), it should be fixed. You can give this a try if you would like, otherwise I will update here when it lands in Nightly.

**Comment by kulinseth** [comment]
Thanks for bringing this up @jacobmlloyd

**Comment by jacobmlloyd** [comment]
> Thanks for bringing this up @jacobmlloyd

Seems to be working with this PR! I appreciate you fixing the issue. Let me know when it's in the latest nightly, thanks!

**Comment by jacobmlloyd** [comment]
> Thanks for bringing this up @jacobmlloyd

Any ETA on a land in nightly? Really appreciate it!

**Comment by kulinseth** [comment]
It should be in nightly . Can you please check

**Comment by gagangayari** [comment]
Updated to macOS13.3 today. I am still getting this error.

**Comment by marcusc** [comment]
Updated to macOS 13.3 today. The error is gone. It works on my M1 as well as my M2 Pro.

**Comment by okpatil4u** [comment]
Getting similar error, but it doesn't mention the OS "RuntimeError: MPS does not support cumsum op with int64 input"

I am on macOS 13.3 and using pytorch nightly. What may be going wrong ?

**Comment by iHamzaKhanzada** [comment]
Guys make sure you are not using the stable Pytorch build but rather Preview (nightly) build and you have MacOS 13.3 to fix this issue, I updated to macOS 13.3 today and installed preview nightly build of Pytorch and the error is gone.

To Install preview nightly build run the command on your terminal: (pip version)
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

source: https://pytorch.org/get-started/locally/

**Comment by kechan** [comment]
M2 Max:

Updated to macOS 13.3

Ran pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

Fixed this issue for me as well.

**Comment by jacobmlloyd** [comment]
Issue fixed.

**Comment by vittorio88** [comment]
> Updated to macOS13.3 today. I am still getting this error.



> Getting similar error, but it doesn't mention the OS "RuntimeError: MPS does not support cumsum op with int64 input"
> 
> I am on macOS 13.3 and using pytorch nightly. What may be going wrong ?

@gagangayari @okpatil4u Try making sure you are installing the packages with pip using the same python version as the one you are running the script with. In my case, pip3 pointed to pip3.10 while python3 pointed to python3.11.

vitto@Vittorios-Air vitto-nlp-scripts % python3 --version
Python 3.11.3
vitto@Vittorios-Air vitto-nlp-scripts % pip3 --version
pip 23.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)

Re-running the pip torch nightly command with the correct version of pip the unsupported cumsum issue.

**Comment by M00N-MAN** [comment]
Hello @kulinseth and @iHamzaKhanzada

Could your please share the exact reason why macos 13.3 required and by which software?

**Comment by warkcod** [comment]
$ python --version
Python 3.10.9
$ pip3 --version
pip 23.1.2 from /usr/local/anaconda3/lib/python3.10/site-packages/pip (python 3.10)

Intel CPU 
MacOS 13.4


@iHamzaKhanzada  Ran pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

Also ran python -m pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

The issue still exists, any ideas? Any help is very appreciated, Thank you very much!

> Guys make sure you are not using the stable Pytorch build but rather Preview (nightly) build and you have MacOS 13.3 to fix this issue, I updated to macOS 13.3 today and installed preview nightly build of Pytorch and the error is gone.
> 
> To Install preview nightly build run the command on your terminal: (pip version) pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
> 
> source: https://pytorch.org/get-started/locally/

**Comment by g0t4** [comment]
@warkcod have you tried creating a new `venv` and running `pip install` again? I had the same problem as above and fixed it with the nightly on my M1 mbp.

**Comment by kulinseth** [comment]
> OS 13.4

@warkcod , can you try PyTorch nightly and see if it works?
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

as @g0t4 suggested.

**Comment by cliffrowley** [comment]
I am using miniforge on macOS 13.4 (M2) and I'm getting the same error. Installing PyTorch nightly as suggested has not fixed it for me.

**Comment by crux82** [comment]
I also have the same problem. I have macOS 13.4 (M2). 

I used Python 3.8. Here the installed packages via pip

```
accelerate==0.19.0
certifi==2023.5.7
charset-normalizer==3.1.0
filelock==3.12.0
fsspec==2023.5.0
huggingface-hub==0.14.1
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.2
mpmath==1.3.0
networkx==3.1
numpy==1.24.3
packaging==23.1
peft==0.3.0
Pillow==9.5.0
psutil==5.9.5
PyYAML==6.0
regex==2023.5.5
requests==2.31.0
sentencepiece==0.1.99
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tqdm==4.65.0
transformers==4.29.2
typing_extensions==4.6.2
urllib3==2.0.2
```

and here the error

```
  warnings.warn(
/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/transformers/generation/utils.py:719: UserWarning: MPS: no support for int64 repeats mask, casting it to int32 (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Repeat.mm:236.)
  input_ids = input_ids.repeat_interleave(expand_size, dim=0)
Traceback (most recent call last):
  File "evaluate.py", line 160, in <module>
    gen_outputs = model.generate(
  File "/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/peft/peft_model.py", line 731, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/transformers/generation/utils.py", line 1604, in generate
    return self.beam_search(
  File "/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/transformers/generation/utils.py", line 2900, in beam_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/user/anaconda3/envs/myenv/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 737, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
RuntimeError: MPS does not support cumsum op with int64 input
```
is there anything I can do?
Thank you very much for your support!

**Comment by aqgasa** [comment]
@crux82 have you tried with PyTorch nightly as @g0t4 suggested?

**Comment by crux82** [comment]
Yes, I used 

``pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu``

Is it correct?

**Comment by kumarravigithub** [comment]
I'm facing the same problem.

**Comment by crux82** [comment]
Does it make sense to replace

[position_ids = attention_mask.long().cumsum(-1) - 1](https://github.com/huggingface/transformers/blob/17a55534f5e5df10ac4804d4270bf6b8cc24998d/src/transformers/models/llama/modeling_llama.py#L736)

with 

position_ids = attention_mask.int().cumsum(-1) - 1

?

**Comment by aqgasa** [comment]
@crux82 For me the @jacobmlloyd's code runs on a Apple M2 Pro in a virtual environment:
```
OS: macOS 13.3.1 (arm64)
Python version: 3.11.3


Package            Version
------------------ ------------------
certifi            2022.12.7
charset-normalizer 2.1.1
filelock           3.9.0
fsspec             2023.4.0
huggingface-hub    0.14.1
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.2
mpmath             1.2.1
networkx           3.0rc1
numpy              1.24.1
packaging          23.1
Pillow             9.3.0
pip                23.1.2
PyYAML             6.0
regex              2023.5.5
requests           2.28.1
setuptools         67.7.2
sympy              1.11.1
tokenizers         0.13.3
torch              2.1.0.dev20230526
torchaudio         2.1.0.dev20230526
torchvision        0.16.0.dev20230526
tqdm               4.65.0
transformers       4.29.2
typing_extensions  4.4.0
urllib3            1.26.13
wheel              0.40.0
```

**Comment by x4080** [comment]
@crux82 , @aqgasa confirmed, run on my m2 pro 16gb using @jacobmlloyd - but lot of disk swap

**Comment by x4080** [comment]
@aqgasa do you know why pytorch use a lot of memory, for example in stable diffusion, it uses lot of memory even when using --medvram (little out of context)

**Comment by patniemeyer** [comment]
Just to save someone the trouble of looking it up - If you want to update your existing environment that already has an older nightly build you can do:

`pip3 install --upgrade --no-deps --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu`

**Comment by x4080** [comment]
@patniemeyer Thats very useful, thanks

**Comment by crux82** [comment]
@patniemeyer It is now running. Thanks!

**Comment by x4080** [comment]
@jacobmlloyd i tried your code yesterday and it seems using lot of disk swap, I'm using m2 16gb. Do you experience lot of disk swap too?

**Comment by aqgasa** [comment]
@x4080 I hope that we will soon have mixed precision in pytorch for mps. I suppose that should reduce memory footprint and increase performance

**Comment by x4080** [comment]
@aqgasa cool, thats what I expected. Will this fixed the huge memory usage in stable diffusion too ? Thanks for the hard work

**Comment by ShepardZhao** [comment]
same issue here, RuntimeError: MPS does not support cumsum op with int64 input. 

I even tried above re-install stuff, still not wokring, waiting for fix this issue, and i don't want to downgrade

**Comment by cmann50** [comment]
I got it to work on a Mac M1 64 GB memory.  I had to:
- Upgrade to Ventura 13.5
- After upgrade, delete the files from the one-click installer
`rm -rf ~/oobabooga_macos/installer_files/text-generation-webui`
- Uninstall Pytorch from system python install
`pip3 uninstall torch torchvision torchaudio`
 - Reinstall one-click installer by running `.start_macos.sh`
 - Uninstall PyTorch from oobabooga
```
conda activate ~/oobabooga_macos/installer_files/env
~/oobabooga_macos/installer_files/env/bin/pip uninstall torch torchvision torchaudio
```
- Install nightly  PyTorch to oobabooga and restart the app.
```
~/oobabooga_macos/installer_files/env/bin/pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
./start_macos.sh
```
It worked fine by downloading model via the UI `https://huggingface.co/EleutherAI/pythia-6.9b-deduped` and using the text generation tab.

**Comment by x4080** [comment]
@cmann50 Is torch still using lot of memory?

**Comment by cmann50** [comment]
It should work with 13.3 or above (though I didn't test that version).  I upgraded to 13.5 since it was the latest available when I wrote that message.

**Comment by davideuler** [comment]
> 

I've test the method to replace ```attention_mask.long()``` with ```attention_mask.int()```,  it does not work. After upgrade MacOS to 13.4, and torch to nightly version, it works.
```
pip3 install --upgrade --no-deps --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by kulinseth** [comment]
> > 
> 
> I've test the method to replace `attention_mask.long()` with `attention_mask.int()`, it does not work. After upgrade MacOS to 13.4, and torch to nightly version, it works.
> 
> ```
> pip3 install --upgrade --no-deps --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
> ```

Yes, unfortunately the cumsum fix didn't make it to 2.0 stable release, so its available on nightlies for now. It will be available in 2.1 release.

**Comment by elo-siema** [comment]
For people still getting this issue after reinstalling pytorch in Jupyter, restarting the kernel solved it.

**Comment by cfmbrand** [comment]
I'm running a Mac M1 Pro 2021 16GB, have set up a virtual environment with python 3.10.9, and have MacOs Ventura 13.5.2. I had the same issue as everyone else above, and while I'm not getting the same error having updated to the 'nightly' install of PyTorch, inference time is unusably slow (like 0.01 tokens/sec). Does anyone have any further ideas as to why this might be? Thanks in advance.

**Comment by jprachir** [comment]
> For people still getting this issue after reinstalling pytorch in Jupyter, restarting the kernel solved it.

Yes, the trick of uninstalling--> reinstalling the nightly version of torch works (same for Apple M2 max with Ventura 13).

**Comment by vincent507cpu** [comment]
Hello everyone, I use a M1 Max with 32GB RAM with MacOS 14. Env info is Python 3.9.13 with torch-2.2.0.dev20230930 (latest dev), still got `RuntimeError: MPS does not support cumsum op with int64 input`. I don't know what should I do. Thanks for help!
