### ISSUE TITLE
Build errors in two Vulkan files

### ISSUE THREAD

**Issue by zboszor** [pytorch/pytorch#96617]
### 🐛 Describe the bug

Build problems occur in two files with GCC 12.2.0:
```
aten/src/ATen/native/vulkan/impl/Arithmetic.cpp:20:1: error: control reaches end of non-void function [-Werror=return-type]
aten/src/ATen/native/vulkan/impl/Registry.cpp:36:27: error: loop variable 'key' of type 'const std::string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char* const' [-Werror=range-loop-construct]
```

### Versions

I am trying to build v2.0.0-rc6 from the release/2.0 branch.

**Comment by dvrogozh** [comment]
This issues is still relevant and occurs for me on main branch (as of 353f2dbd9cd56212d0beac63d93181c50335cf74) and v2.1.2 (I did not try other branches). There was an effort by @zboszor to fix this issue (see #96618), but this was not finished. I provided other PR (see #115976) addressing review feedback given in #96618.
