### ISSUE TITLE
torch.cuda.graph "Invalid capture" with torch.linalg.solve

### ISSUE THREAD

**Issue by chaopengshen** [pytorch/pytorch#96632]
### 🐛 Describe the bug

I'm trying a simple CUDAGraph capture example. It works with a torch.matmul operation but reported "Invalid Capture" with torch.linalg.solve. See below. I'm hoping to understand what is ok and what is not ok with torch.cuda.graph. If this is due to un-determined number of iterations inside torch.linalg.solve, if we can set a fix number of iterations.

```
import torch
N = 640

# Placeholders used for capture
A = torch.randn(N, N, device='cuda')
b = torch.randn(N, 1, device='cuda')

# warmup
s = torch.cuda.Stream()
s.wait_stream(torch.cuda.current_stream())
with torch.cuda.stream(s):
    for i in range(3):
        #dat = torch.matmul(A, b) # this command runs
        dat = torch.linalg.solve(A, b) # this command does NOT run
torch.cuda.current_stream().wait_stream(s)

# capture
g = torch.cuda.CUDAGraph()
with torch.cuda.graph(g):
    #dat = torch.matmul(A, b) # this command runs
    dat = torch.linalg.solve(A, b) # this command does NOT run

real_inputs = [torch.rand_like(A) for _ in range(10)]
real_targets = [torch.rand_like(b) for _ in range(10)]

for data, target in zip(real_inputs, real_targets):
    # Fills the graph's input memory with new data to compute on
    A.copy_(data)
    b.copy_(target)
    g.replay()
#print(dat - torch.matmul(A, b))
```

The returned information is
```
---------------------------------------------------------------------------
_LinAlgError                              Traceback (most recent call last)
[<ipython-input-2-f302cf725f49>](https://localhost:8080/#) in <module>
     22     #dat = torch.matmul(A, b) # this command runs
---> 23     dat = torch.linalg.solve(A, b) # this command does NOT run
     24 

_LinAlgError: torch.linalg.solve: The solver failed because the input matrix is singular.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
2 frames
[<ipython-input-2-f302cf725f49>](https://localhost:8080/#) in <module>
     21 with torch.cuda.graph(g):
     22     #dat = torch.matmul(A, b) # this command runs
---> 23     dat = torch.linalg.solve(A, b) # this command does NOT run
     24 
     25 real_inputs = [torch.rand_like(A) for _ in range(10)]

[/usr/local/lib/python3.9/dist-packages/torch/cuda/graphs.py](https://localhost:8080/#) in __exit__(self, exc_type, exc_value, traceback)
    157 
    158     def __exit__(self, exc_type, exc_value, traceback):
--> 159         self.cuda_graph.capture_end()
    160         self.stream_ctx.__exit__(exc_type, exc_value, traceback)
    161         # returning None should propagate exceptions from either capture_end or stream_ctx.__exit__()

[/usr/local/lib/python3.9/dist-packages/torch/cuda/graphs.py](https://localhost:8080/#) in capture_end(self)
     79         which call ``capture_end`` internally.
     80         """
---> 81         super(CUDAGraph, self).capture_end()
     82 
     83     def replay(self):

RuntimeError: Invalid capture.
```

### Versions

--2023-03-13 01:51:20--  https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21415 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  20.91K  --.-KB/s    in 0.001s  

2023-03-13 01:51:20 (23.4 MB/s) - ‘collect_env.py’ saved [21415/21415]

Collecting environment information...
PyTorch version: 1.13.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.22.6
Libc version: glibc-2.31

Python version: 3.9.16 (main, Dec  7 2022, 01:11:51)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.147+-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.85.12
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:                        0
CPU MHz:                         2299.998
BogoMIPS:                        4599.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.13.1+cu116
[pip3] torchaudio==0.13.1+cu116
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.14.1
[pip3] torchvision==0.14.1+cu116
[conda] Could not collect

cc @mcarilli @ezyang @eellison

**Comment by ezyang** [comment]
Yeah the problem is linalg.solve has some syncs (IIRC, to see if it converged). Maybe we can add a parameter that says how many iterations to do and then you can eliminate the sync and then it would be cuda graphable. Do you think you could write this patch?

cc @lezcano

**Comment by lezcano** [comment]
For a version that doesn't synchronise, see [`torch.linalg.solve_ex`](https://pytorch.org/docs/stable/generated/torch.linalg.solve_ex.html).

**Comment by ezyang** [comment]
I don't think linalg.solve mentions ex, it should

**Comment by lezcano** [comment]
Many `linalg` ops have `_ex` variants that don't synchronise, but rather return a tensor that represents the errors that may have happened during the computation. We should probably link them in the see also part of the docs
