### ISSUE TITLE
nonzero_static operator for export

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#96679]
The `nonzero` op (and other data-dependent ops like it) present an issue for export with static shapes.

Today, we will return unbacked symints to represent the the data-dependent output shape, but this has many caveats. For example, downstream operations may choke, and shape information may be affected for the rest of the graph.

In practice, many times the the shape is statically known. For example, we often call `nonzero` on a 1-hot vector. For cases like this, we can learn from, e.g. JAX and offer a variant that has statically known output shape and potentially pads the output if necessary.

The semantics would be similar to [jax.numpy.nonzero](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.nonzero.html), except that we would define an entirely new op (`aten.nonzero_static`) for it.

**Comment by guangy10** [comment]
@suo Instead of making an overload of `nonzero()`, e.g. `nonzero(self, *, size=t)` why is making a entirely new op preferred?
