### ISSUE TITLE
[LTC] `GetBackendDevice` implementation broken

### ISSUE THREAD

**Issue by antoniojkim** [pytorch/pytorch#96676]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/95942 broke the implementation of `GetBackendDevice`. In `master` the header file declares
https://github.com/pytorch/pytorch/blob/3f1efadea5846ffca62111e3c891df03725a6a82/torch/csrc/lazy/backend/backend_device.h#L82-L83
but the definition was changed to
https://github.com/pytorch/pytorch/blob/3f1efadea5846ffca62111e3c891df03725a6a82/torch/csrc/lazy/backend/backend_device.cpp#L77-L78
Which means that the `torch::lazy::GetBackendDevice(c10::optional<c10::Device>)` has no definition anymore, causing linking errors:
```
undefined reference to `torch::lazy::GetBackendDevice(c10::optional<c10::Device>)'
```

CC: @cyyever @Skylion007 @wconstab 

### Versions

N/A

**Comment by cyyever** [comment]
The PR aims to replace const parameters to const referenced ones . Some required changes are missed in it.
