### ISSUE TITLE
[Inductor] [CPU] Huggingface model MobileBertForQuestionAnswering performance regression > 10% on 2023-03-12 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#96713]
### 🐛 Describe the bug

Compare with the 2023-03-08, there is a performance regression on huggingface model **MobileBertForQuestionAnswering** on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1467230382) on 2023-03-12 as bellow:

|  2023-03-12  |   |     |   |  2023-03-08  |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|1.2856	|0.0493953	|0.063502598	|1	|1.5266	|0.0414146	|0.063223528	|0.84	|1	|0.84

2023-03-12 nightly release SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|[82d3d05](https://github.com/pytorch/pytorch/commit/82d3d05)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

2023-03-08 nightly release SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[47cb449](https://github.com/pytorch/pytorch/commit/47cb449)|[3a42752](https://github.com/pytorch/pytorch/commit/3a42752)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

Graph dump by cosim:
2023-03-12:
[graph.txt](https://github.com/pytorch/pytorch/files/10963542/graph.txt)

2023-03-08:
[graph.txt](https://github.com/pytorch/pytorch/files/10963543/graph.txt)

### Versions

Minified repro:

```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/huggingface.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only MobileBertForQuestionAnswering  --cold_start_latency --batch_size 1 --threads 1
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @ngimel @soumith

**Comment by XiaobingSuper** [comment]
@blzheng, could you help see this issue? it may be caused by https://github.com/pytorch/pytorch/commit/2f6a371ae901fa266d69fb16585436e04c52d87f.

**Comment by wconstab** [comment]
Yes, we expect the regression due to having to revert that fix.  We should fix it again but it might take a couple weeks.

**Comment by williamwen42** [comment]
Did the reverted PR ever get fixed?

**Comment by leslie-fang-intel** [comment]
@wconstab does the PR get relanded?

**Comment by blzheng** [comment]
According to the latest report ( https://github.com/pytorch/pytorch/issues/93531#issuecomment-1873648432 ), the performance speedup is back (1.549694x).

**Comment by wconstab** [comment]
The PR didn't get relanded bc it was fundamentally a bad way to do it, but I think @voznesenskym or someone else landed something kind of similar that got the perf back.
