### ISSUE TITLE
how to post a new topic at pytorch forum?

### ISSUE THREAD

**Issue by youkaichao** [pytorch/pytorch#9672]
Sorry that I asked such a  silly question. But in order to post a new topic, I have to load all topics here until I reach the end, then I can see "Why not create a topic?.". This is annoying when I want to add a new topic for autograd which has almost 1K topics -- I have to load them all in order to post a new topic!

What's worse, when I post a topic, the site says **You are not permitted to view the requested resource.**. So annoying!

Any thoughts to help?

Sorry to put something here, but I can't add a topic at pytorch forum, so I have no other options.

**Comment by soumith** [comment]
there should be a "New Topic" button right at the top.
If you cant see it, your account must have been auto-flagged to not have the ability to post new topics.

<img width="1132" alt="screen shot 2018-07-20 at 9 02 42 pm" src="https://user-images.githubusercontent.com/1310570/43030598-5a92d1ba-8c60-11e8-9c08-ba87f8ca76f4.png">

**Comment by youkaichao** [comment]
why I'm auto-flagged to not have the ability to post new topics? how can I fix it?
