### ISSUE TITLE
in test files when run test_reductions.py::TestReductionsCPU::test_prod_bool_cpu issue module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by nccvir** [pytorch/pytorch#96734]
### 🐛 Describe the bug
run test like this:
python run_test.py -i test/test_reductions.py::TestReductionsCPU::test_prod_bool_cpu
error:
AttributeError: module 'numpy' has no attribute 'bool'.

### Versions

by torch version v1.13.1

cc @mruberry @rgommers

**Comment by nccvir** [comment]
update code  like this
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here

**Comment by malfet** [comment]
Grabbing for myself to be fixed tomorrow

**Comment by malfet** [comment]
Actually, this already been fixed by https://github.com/pytorch/pytorch/issues/91329
