### ISSUE TITLE
Discrepancy in Internal/external newline-at-end-of-file behavior for C++ files

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#96747]
### 🐛 Describe the bug

https://github.com/pytorch/pytorch/pull/96668#issuecomment-1468029259 had to be reverted since it caused an internal failure (due to a missing newline) when the external, github build showed no problems

Ask: Investigate the discrepancy and modify either the internal or external builds to match the other one (most likely we'll modify the external one)

Note: this is prob be a C++ compiler flag mismatch issue, not a linter error. The exact failure was:

```
torch/csrc/api/include/torch/mps.h:21:21: error: no newline at end of file [-Werror,-Wnewline-eof]
} // namespace torch
```
([source](https://www.internalfb.com/diff/D44048366))

Perhaps we need to add the `-Wnewline-eof` flag to our external C++ compiler

cc @malfet @seemethere @kit1980 @huydhn @clee2000

**Comment by malfet** [comment]
Hmm, internal linters should not run for PyTorch codebase (i.e. OSS linters is source of truth)
