### ISSUE TITLE
We have not yet implemented the batching rule for aten::where.Scalar.

### ISSUE THREAD

**Issue by TheCleric** [pytorch/pytorch#96741]
UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::where.Scalar. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1673856678067/work/aten/src/ATen/functorch/BatchedFallback.cpp:84.)

cc @ezyang @gchanan @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by zou3519** [comment]
We should be able to do this. Tentatively marking hi-pri for common operator and likely simple fix.
