### ISSUE TITLE
Implementing the batching rule for aten::bucketize.Tensor.

### ISSUE THREAD

**Issue by sandylaker** [pytorch/pytorch#96740]
Dear maintainers of functorch,

I tried to use `functorch.vmap` to implement an extended version of `torch.bucketize`, so that I can bucketize a batched tensor with heterogeneous boundaries. 

I got the a `UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::bucketize.Tensor`.

It would be great if the batching rule could be implemented for `torch.bucketize`.

Thanks a lot.

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by Chillee** [comment]
Fixed by https://github.com/pytorch/pytorch/pull/95783
