### ISSUE TITLE
[inductor] flaky rexnet_100 accuracy tests

### ISSUE THREAD

**Issue by davidberard98** [pytorch/pytorch#96759]
### 🐛 Describe the bug

rexnet_100 has accuracy flakiness, sometimes marking accuracy failure due to `stem.bn.weight.grad`.

#96691 and #96474 disable rexnet_100 in CI.

For an example, see https://github.com/pytorch/pytorch/actions/runs/4402868441/jobs/7710977874.

### Versions

master / CI

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @soumith

**Comment by Chillee** [comment]
It seems like this shows up even without dynamic shapes, right?

**Comment by davidberard98** [comment]
Yes. After https://github.com/pytorch/pytorch/pull/96691 it should be disabled on both dynamic and non-dynamic shapes timm CI jobs.

**Comment by anijain2305** [comment]
The flakiness might be gone now. We will retry running this.

**Comment by williamwen42** [comment]
I don't see code that skips rexnet_100 anymore and CI is green. Closing as fixed.
