### ISSUE TITLE
build_pytorch_libs.bat should be end with CRLF.

### ISSUE THREAD

**Issue by shkit** [pytorch/pytorch#9677]
## Issue description

I try to build PyTorch on Windows, but build fails on some machines with following message.
~~~
The system cannot find the batch label specified read_loop
~~~
When I convert tools\build_pytorch_libs.bat' EOL from LF to CRLF, build succeeds.

Not all machines fail to build with LF, but batch file should be end with CRLF, I think.

**Comment by peterjc123** [comment]
@shkit Why is this a problem? Git should handle this well if you set `core.autocrlf` to `true`, which should be a default value in Git. So how did you get the code? Did you try to copy the files from Linux to Windows?

**Comment by shkit** [comment]
@peterjc123  I set `core.autocrlf` to `false` manually on Windows, because it is problematic setting for me. (I sometimes copies from/to Unix-like systems, and so on)
Doing `git --local core.autocrlf true` in local repository also fixes this problem, but I think adding `.gitattributes` file (like below) could be a appropriate fix. (bat's EOL is always set CRLF whatever user settings is)
~~~
*.bat  text eol=crlf
~~~
How about?

**Comment by peterjc123** [comment]
@shkit Nice idea, could you submit a PR on this?

**Comment by shkit** [comment]
@peterjc123 Thanks for comment. Ok, I'll submit PR.
Though I plan to add only `.bat` to .attributes file, any other suffixes should be added?
(Looking into some files, I suspect adding '.bat' is sufficient)

**Comment by peterjc123** [comment]
@shkit Yes, `.bat` is enough.

**Comment by shkit** [comment]
Thanks!
