### ISSUE TITLE
lintrunner's ufmt tries to format my entire codebase

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#96794]
### 🐛 Describe the bug

When I run `lintrunner` in my local repo, rather than run ufmt on the changed files, it computes that all 700 python files are changed and attempts to format them (verified by using -v and looking at what files are passed to ufmt).

When checking what lintrunner does to compute what files to change it runs a line like:
```
execve("/usr/bin/git", ["git", "merge-base", "HEAD", "master"], 0x7ffcd59a3a18 /* 64 vars */) = 0 
```

However, there is no guarantee that the local `master` is meaningful or up-to-date. In fact, in this particular repo my master is nearly 3 years out of date, because the `ghstack` workflow doesn't require using branches of master to do work:

```
commit 3c0110f8ec299c2642c6a175a5893a5bf1b7791b (master)
Author: Zachary DeVito <zdevito@fb.com>
Date:   Tue Sep 22 14:31:23 2020 -0700

    temp work
```

Its possible this computation would be more meaningful using `origin/master` which is fetched when using ghstack.

### Versions

all versions

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by msaroufim** [comment]
+1 `lintrunner -ma` should probably be the default setting
