### ISSUE TITLE
Docs request: combination of LogSoftmax and NLLLoss in CrossEntropyLoss

### ISSUE THREAD

**Issue by jamesbraza** [pytorch/pytorch#96795]
### 📚 The doc issue

From https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html

> Note that this case is equivalent to the combination of [`LogSoftmax`](https://pytorch.org/docs/stable/generated/torch.nn.LogSoftmax.html#torch.nn.LogSoftmax) and [`NLLLoss`](https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html#torch.nn.NLLLoss).

This requires readers to have to look at each formula, and figure out how to combine them.  It would be better to explicitly state how they are combined.

### Suggest a potential alternative/fix

I think the below wording is equally concise, but more informative:

> Note that this case is equivalent to a [`LogSoftmax`](https://pytorch.org/docs/stable/generated/torch.nn.LogSoftmax.html#torch.nn.LogSoftmax) passed into a [`NLLLoss`](https://pytorch.org/docs/stable/generated/torch.nn.NLLLoss.html#torch.nn.NLLLoss).

If you like this, I can open a PR!

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by soulitzer** [comment]
Thanks for the suggestion @jamesbraza, we'd accept a PR to update this.
