### ISSUE TITLE
Documentation for torchvision.RandomAffine() refers to a wrong URL

### ISSUE THREAD

**Issue by vmirly** [pytorch/pytorch#9682]
The doc for the **resample** option in `torchvision.RandomAffine()` refers to Pillow docs version 3.4.x but this link gives **Permission Denied**. However, the links for version 5.2.0 and the stable version work, so I think it will be good to update the link.

Documentation Page for `torchvision.RandomAffine()`: 
https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomAffine

Current URL (not working/permission denied):
http://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html#filters

Working URL (5.2.0):
http://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#filters

**Working URL (stable):**
http://pillow.readthedocs.io/en/stable/handbook/concepts.html#filters

**Comment by vishwakftw** [comment]
Please open this issue in [vision](https://github.com/pytorch/vision) .

**Comment by vmirly** [comment]
Right, so I close this issue here and open one in vision.
