### ISSUE TITLE
[doc] linalg.ldl_factor : Shape of tensor `A` is rendered incorrectly

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#96864]
### 📚 The doc issue

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/19503980/225397739-6b9aae28-5c3a-40c0-9710-7dfb01e21f8d.png">

Ref: https://pytorch.org/docs/master/generated/torch.linalg.ldl_factor.html?highlight=ldl_solve

### Suggest a potential alternative/fix

Shape for `A` should render as `(*, n, n)`.

cc @svekars @carljparker @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Noodulz** [comment]
Hi I'd like to work on and be assigned this issue if possible, thanks!

**Comment by choudharynishu** [comment]
I would like to help on this

**Comment by jai-bhardwaj** [comment]
Can I work on this issue?

**Comment by Avashist1998** [comment]
I would like to fix this issue.

**Comment by lezcano** [comment]
Now @isdanni already went on and sent the start of a fix. For simple fixes like this one, it may be easier to simply send the fix. If you tag it properly, it'll already tag the right reviewers in most cases.
