### ISSUE TITLE
[feature request] Transpose() should not check dimensions

### ISSUE THREAD

**Issue by tobyclh** [pytorch/pytorch#9687]
Currently, applying transpose `some_tensor.t()`, 
on 1D Tensor, pytorch throws error as discussed at #301

my desired behaviour
`some_tensor.t() == some_tensor` should be true

This follows numpy's behaviour, make it much easier to port code from numpy and seems to me more natural and practical.

Thank you.

**Comment by bhushan23** [comment]
Current implementation only support transpose for 2D tensors.
We should implement generic for N-D tensors.

**Comment by zou3519** [comment]
@bhushan23 `torch.transpose()` supports ND tensors. `tensor.t()` only supports 2D tensors. It is an open discussion for if `tensor.t()` should match numpy's ndarray.T behavior, and/or if we should add an uppercase T attribute.

**Comment by bhushan23** [comment]
Adding stakeholder's as per the git history for transpose
@apaszke @ezyang @gchanan @zou3519 what are your views on following? 
1. Make .t() behavior similar to numpy
2. Do not introduce .T attribute
