### ISSUE TITLE
MPS devices, Nvidia MPS

### ISSUE THREAD

**Issue by phalexo** [pytorch/pytorch#96881]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I have tried all kinds of ways to build PyTorch with MPS support. Is Nvidia MPS only available on Apple machines?
USE_MPS=1 or USE_CUDA_MPS=1 or USE_NVIDIA_MPS=1 do not work in forcing PyTorch to be built with MPS support.

1) Is MPS supported for Ubuntu 20.04 with PyTorch 2.1? Is there any version of PyTorch that supports it?

Provide a short description.

## Code example

>>> x.to('mps')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: PyTorch is not linked with support for mps devices

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by malfet** [comment]
Please use https://discuss.pytorch.org to general question about using PyTorch and issue to report a bug or propose a new feature. 

I'm not sure what do you mean by "Nvidia MPS", but MPS is short for [Metal Performance Shaders](https://developer.apple.com/documentation/metalperformanceshaders) and at the moment is framework is only available and supported on MacOS

**Comment by phalexo** [comment]
Nvidia Multi Process Service.

**Comment by malfet** [comment]
Today I've learned, thank you @phalexo .
If I remember correctly, one does not need to recompile client applications to enable Multi-Process Service support. If it does not work out of box, please do not hesitate to open a new issue. 
But, as I've mentioned above,  PyTorch `mps` devices are only avail on MacOS platform and are used to communicate with MacOS/iOS GPUs via Metal Performance Shaders Graph framework.
