### ISSUE TITLE
pip3 install torch torchvision is getting torch 2.0 and not 1.3

### ISSUE THREAD

**Issue by nikky4D** [pytorch/pytorch#96884]
### 🐛 Describe the bug
Doing a pip install does not get version 1.13 but instead version 2.0. I used the code below:
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116

taken from pytorch.org site:

![image](https://user-images.githubusercontent.com/7451106/225431023-34ffdc90-59e8-463f-a361-e3256e0f923d.png)

### Versions

Using the install page on pytorch.org, I do not get the 1.13 version but 2.0.

**Comment by malfet** [comment]
PyTorch 2.0 was release today, so this is expected. Website update will be live in a few minutes and installation instructions for previous versions will be available shortly.

**Comment by seemethere** [comment]
Hello! We actually dropped support for CUDA 11.6 as part of 2.0 you can utilize the CUDA 11.7 binaries to get support for 2.0

**Comment by seemethere** [comment]
Reference blog post: https://pytorch.org/blog/deprecation-cuda-python-support/
