### ISSUE TITLE
How to get the output shape of a layer via caffe2?

### ISSUE THREAD

**Issue by duhaijun** [pytorch/pytorch#9689]
The title already contains the full question, any help would be appreciated.

**Comment by jerryzh168** [comment]
are you using caffe2's python API? are you asking about the shape of the output of a caffe2 operator? If so, you could run the net and get the blob from workspace.

**Comment by XiongChengxin** [comment]
Hi@jerryzh168 , How could I get the name of each layer? The blob name I get from 'net.Proto()' are too similar, the details are as follows. I can't distinguish which is I need. Looking forward to your reply, thanks in advance.


external_input: "gpu_1/comp_13_conv_2_w"
external_input: "gpu_1/comp_13_spatbn_2_s"
external_input: "gpu_1/comp_13_spatbn_2_b"
external_input: "gpu_1/comp_13_spatbn_2_rm"
external_input: "gpu_1/comp_13_spatbn_2_riv"
external_input: "gpu_1/shortcut_projection_13_w"
external_input: "gpu_1/shortcut_projection_13_spatbn_s"
external_input: "gpu_1/shortcut_projection_13_spatbn_b"
external_input: "gpu_1/shortcut_projection_13_spatbn_rm"
external_input: "gpu_1/shortcut_projection_13_spatbn_riv"
external_input: "gpu_1/comp_14_conv_1_middle_w"
external_input: "gpu_1/comp_14_spatbn_1_middle_s"
external_input: "gpu_1/comp_14_spatbn_1_middle_b"
external_input: "gpu_1/comp_14_spatbn_1_middle_rm"
external_input: "gpu_1/comp_14_spatbn_1_middle_riv"
external_input: "gpu_1/comp_14_conv_1_w"
external_input: "gpu_1/comp_14_spatbn_1_s"
external_input: "gpu_1/comp_14_spatbn_1_b"
external_input: "gpu_1/comp_14_spatbn_1_rm"
external_input: "gpu_1/comp_14_spatbn_1_riv"
external_input: "gpu_1/comp_14_conv_2_middle_w"
external_input: "gpu_1/comp_14_spatbn_2_middle_s"
external_input: "gpu_1/comp_14_spatbn_2_middle_b"
external_input: "gpu_1/comp_14_spatbn_2_middle_rm"
external_input: "gpu_1/comp_14_spatbn_2_middle_riv"
external_input: "gpu_1/comp_14_conv_2_w"
external_input: "gpu_1/comp_14_spatbn_2_s"
external_input: "gpu_1/comp_14_spatbn_2_b"
external_input: "gpu_1/comp_14_spatbn_2_rm"
external_input: "gpu_1/comp_14_spatbn_2_riv"
external_input: "gpu_1/comp_15_conv_1_middle_w"
external_input: "gpu_1/comp_15_spatbn_1_middle_s"
……

**Comment by jerryzh168** [comment]
@XiongChengxin the you can find that in the definition of operators in the proto file. There are inputs and outputs for each operator definition.

**Comment by XiongChengxin** [comment]
@jerryzh168 Thanks for your reply. I don't understand what do you mean by 'proto file'. Do you mean the information returned by command 'net.Proto()', or is there similar file like the prototxt file in caffe? If the former, the information I get is also ambiguous. This op don't have names(I copied part of it down here), so I still can't distinguish them. Any help would be appreciated.

op {
  input: "gpu_2/comp_2_conv_2_w_grad"
  input: "gpu_2/ONE"
  input: "gpu_2/comp_2_conv_2_w"
  input: "gpu_2/wd"
  output: "gpu_2/comp_2_conv_2_w_grad"
  name: ""
  type: "WeightedSum"
  device_option {
    device_type: 1
    cuda_gpu_id: 2
  }
}
op {
  input: "gpu_2/comp_2_spatbn_2_s_grad"
  input: "gpu_2/ONE"
  input: "gpu_2/comp_2_spatbn_2_s"
  input: "gpu_2/wd"
  output: "gpu_2/comp_2_spatbn_2_s_grad"
  name: ""
  type: "WeightedSum"
  device_option {
    device_type: 1
    cuda_gpu_id: 2
  }
}
op {
  input: "gpu_2/comp_3_conv_1_middle_w_grad"
  input: "gpu_2/ONE"
  input: "gpu_2/comp_3_conv_1_middle_w"
  input: "gpu_2/wd"
  output: "gpu_2/comp_3_conv_1_middle_w_grad"
  name: ""
  type: "WeightedSum"
  device_option {
    device_type: 1
    cuda_gpu_id: 2
  }
}

**Comment by XiongChengxin** [comment]
Thanks!
