### ISSUE TITLE
[proposal] PixelUnshuffle

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9692]
I have a basic implementation. Will submit a PR next week.

**Comment by vishwakftw** [comment]
This was brought up earlier in https://github.com/pytorch/pytorch/issues/2456 .

**Comment by SsnL** [comment]
I guess I'll do this in contrib.

**Comment by SsnL** [comment]
closing in favor of https://github.com/pytorch/contrib/issues/10

**Comment by PiotrDabkowski** [comment]
@SsnL It would be nice to have this implementation in the main repo. Not sure why #2456 decided otherwise.
