### ISSUE TITLE
Link in 2.0 release notes to torch.set_default_device point to incorrect place.

### ISSUE THREAD

**Issue by gilfree** [pytorch/pytorch#96939]
### 📚 The doc issue

https://pytorch.org/blog/pytorch-2.0-release/

In this paragraph:
https://pytorch.org/blog/pytorch-2.0-release/#beta-torchset_default_device-and-torchdevice-as-context-manager

The "here" points to: https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html

cc @svekars @carljparker

**Comment by gchanan** [comment]
CC @drisspg

**Comment by ezyang** [comment]
The correct link is https://pytorch.org/tutorials/recipes/recipes/changing_default_device.html?highlight=device
