### ISSUE TITLE
Build issue: ld: library not found for -lgcc_s

### ISSUE THREAD

**Issue by alexskates** [pytorch/pytorch#9695]
## Issue description

I'm trying to build pytorch, and have tried both with and without CUDA. Both fail. I get the error:
```
ld: library not found for -lgcc_s
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe2.dylib] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
make: *** [all] Error 2
```
The output from the install script can be found [here](https://gist.github.com/alexskates/e911aa975efe45fabed19702c6353183)

Also, some of the steps I'd taken to try and get it to work had been detailed in [this issue on discuss](https://discuss.pytorch.org/t/keeps-referencing-wrong-version-of-gcc-when-building-from-source/19492/4).

## System Info
- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):  
export CMAKE_PREFIX_PATH=/Users/askates/anaconda3/envs/torch_gpu/
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
MACOSX_DEPLOYMENT_TARGET=10.9 python setup.py install
- OS: OSX 10.12.6
- PyTorch version: most recent master
- Python version: 3.5.5
- CUDA/cuDNN version: 8.0/6.0
- GPU models and configuration: NVIDIA GeForce GT 750M
- GCC version (if compiling from source): 5.5.0
- CMake version: 3.12.0
- Versions of any other relevant libraries:

Thanks, it's driving me nuts not being able to install any new versions of pytorch. Namely because I am currently experiencing something akin to [this issue](https://github.com/pytorch/pytorch/issues/199) but am unable to attempt to fix it.

**Comment by yf225** [comment]
@alexskates We actually need Command Line Tools from Xcode 8.2 (macOS 10.12) to build PyTorch with CUDA on macOS. The correct steps should be:

1. Install Command Line Tools from Xcode 8.2 (macOS 10.12) from https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.12_for_Xcode_8.2/Command_Line_Tools_macOS_10.12_for_Xcode_8.2.dmg

2. Set `export DEVELOPER_DIR=/Library/Developer/CommandLineTools`, then run `MACOSX_DEPLOYMENT_TARGET=10.9 NO_CUDA=0 CC=clang CXX=clang++ python setup.py install` to build PyTorch.

**Comment by alexskates** [comment]
I keep trying to use clang, but it uses gcc every time. I've tried passing it into command I'm using to build (as in your example), ensuring it was added to PATH (first), setting the environment variables $CC, $CXX, $CMAKE_C_COMPILER, $CMAKE_CXX_COMPILER and so on but every time it references gcc-5. Am I missing something?

**Comment by alexskates** [comment]
`rm -r build` fixed it!
