### ISSUE TITLE
Compile gives weird error about CUDA on MPS device (apple Macbook)

### ISSUE THREAD

**Issue by tcapelle** [pytorch/pytorch#96976]
### 🐛 Describe the bug

In PyTorch 2.0 on an Apple Macbook running latest OS.
```python
from torch import nn
from torchvision.models import resnet50

torch.set_default_device('mps')

img = torch.rand(1,3,64,64)
r50 = resnet50()

ccompiled_r50 = torch.compile(r50)
ccompiled_r50(img)
```
You get a weird error about `CUDA` ! 🤯
```
BackendCompilerFailed: debug_wrapper raised AssertionError: Torch not compiled with CUDA enabled

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.23.1
Libc version: N/A

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] numpy                     1.24.2          py310h3d2048e_0    conda-forge
[conda] pytorch                   2.0.0                  py3.10_0    pytorch
[conda] torchaudio                2.0.0                 py310_cpu    pytorch
[conda] torchvision               0.15.0                py310_cpu    pytorch

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by tcapelle** [comment]
cc @msaroufim

**Comment by msaroufim** [comment]
Problem seems to be when creating an inductor backend we error out on this line

`device_props = torch.cuda.get_device_properties(device)` 

So fix should be simple which is to raise a runtime error if `mps` is detected earlier so the error message is more understandable https://github.com/pytorch/pytorch/blob/master/torch/_inductor/scheduler.py#L1153

**Comment by laclouis5** [comment]
I got the same issue. Also, note that setting the advised debug flag `torch._dynamo.config.verbose=True` fails with error:

```
AttributeError: module 'torch' has no attribute '_dynamo'
```

**Comment by ezyang** [comment]
import torch._dynamo

**Comment by khaled-alkilane** [comment]
Any solution for this problem??

**Comment by msaroufim** [comment]
@khaled-alkilane yes once this PR is merged https://github.com/pytorch/pytorch/pull/96980

**Comment by tanhevg** [comment]
Looks like the error is still there in 2.1.0, although #96980 has been merged a few months ago. Should this be re-opened?

CPU=Mac m2 Pro
torch=2.1.0
OS=Mac OS Sonoma 14.0

**Comment by a1eaiactaest** [comment]
The same thing on M1 Air, none of the mentioned solutions seem to fix the problem.

**Comment by abhishek0093** [comment]
Still there in 2.4.1 torch version for m1 pro. Any working solution out there? 
```
BackendCompilerFailed: backend='inductor' raised:
AssertionError: Device mps not supported

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```
