### ISSUE TITLE
Allow fused optimizer's `zero_grad` to call `_foreach_zero_`

### ISSUE THREAD

**Issue by crcrpar** [pytorch/pytorch#97032]
now that by default `set_to_none` is `True` though, it'd be reasonable to let `fused` optimizers call `_foreach_zero_` instead of calling `.zero_` on every single parameter.

The required change would be to add `self.defaults.get('fused', False)` to  https://github.com/pytorch/pytorch/blob/8ce296ae2c88e9694a73130f4ea451350b72329c/torch/optim/optimizer.py#L450

cc @vincentqb @jbschlosser @albanD @janeyx99

**Comment by janeyx99** [comment]
Nice observation! I've put up #97159. We should go a few steps further though:
1. Write grouping logic to group things into foreachable device+dtype (where everything not foreachable goes in the cpu bucket)
2. Make foreach true all the time here
