### ISSUE TITLE
multidim operators

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9703]
- [x] mean
- [x] var, std
- [ ] max, min

cc @VitalyFedyunin @ngimel

**Comment by vadimkantorov** [comment]
also it would be nice if `F.normalize` supported multidim

**Comment by JoyChopra1298** [comment]
Any progress?

**Comment by jatentaki** [comment]
Hi, I proposed a quick-and-dirty fix for those operators on slack and got an enthusiastic response from @apaszke. The idea is to just permute the tensor such that the reduction dimensions land at the end, flatten them and call the existing operators. Below is a sample implementation omitting most of error handling

```python
import torch
from functools import partial

def _reduce_many(tensor, dim, keepdim=False, operation='std', **kwargs):
    if not (isinstance(dim, tuple) and all(isinstance(d, int) for d in dim)):
        return getattr(tensor, operation)(dim, keepdim=keepdim, **kwargs)

    def to_positive(ix):
        return ix if ix >= 0 else tensor.dim() + ix

    to_reduce = [to_positive(d) for d in dim]
    to_keep = [i for i in range(tensor.dim()) if i not in to_reduce]

    permuted = tensor.permute(*to_keep, *to_reduce)
    reshaped = permuted.reshape(*[tensor.shape[i] for i in to_keep], -1)
    reduced = getattr(reshaped, operation)(dim=-1, **kwargs)

    if not keepdim:
        return reduced

    shape = [(tensor.shape[i] if i in to_keep else 1) for i in range(tensor.dim())]
    return reduced.reshape(*shape)

std = partial(_reduce_many, operation='std')
mean = partial(_reduce_many, operation='mean')
max = partial(_reduce_many, operation='max')
min = partial(_reduce_many, operation='min')

tensor = torch.randn(10, 10, 10, 10, 10)
reduced = std(tensor, dim=(1, 3), keepdim=True)
print(reduced.shape)

reduced = std(tensor, dim=(3, 4), keepdim=False)
print(reduced.shape)

reduced = std(tensor, dim=1, keepdim=True)
print(reduced.shape)
```

This is what I had on mind when writing on slack. To make it elegantly fit in the codebase would be significantly more complex because the reduction functions do not explicitly exist anywhere in Python, as far as I can tell, but are autogenerated based on some `yaml`. Also, this is probably far from the most performant solution, since it involves unnecessary transpositions. I'll be happy to work on that issue if I can get some guidance from a more experienced contributor.

**Comment by colesbury** [comment]
@umanwizard is working on multi-dim reductions

**Comment by ezyang** [comment]
@umanwizard @colesbury Did this get landed already? If so, can we close this?

**Comment by dashesy** [comment]
Currently `std`/`var` behave differently from the rest

```python

a = torch.rand(5, 4,10, 4)

print(torch.mean(a, (1,2,3)).shape)
print(torch.sum(a, (1,2,3)).shape)
print(torch.std(a, (1,2,3)).shape)
```


> TypeError: std() received an invalid combination of arguments - got (Tensor, tuple), but expected one of:                                                                                                                                                                        > * (Tensor input, bool unbiased)                                                                                                                                                                                                                                                      > didn't match because some of the arguments have invalid types: (Tensor, tuple)                                                                                                                                                                                             > * (Tensor input, int dim, bool unbiased, bool keepdim, Tensor out)


```python
print(torch.std(a, (1,2,3), True).shape)
```

> TypeError: std(): argument 'dim' (position 2) must be int, not tuple

**Comment by umanwizard** [comment]
@dashesy 

What version are you on?

**Comment by dashesy** [comment]
@umanwizard 1.0.1.post2

**Comment by umanwizard** [comment]
IIRC the multi-dim `std` and `var` went out in 1.1.0
