### ISSUE TITLE
torch dynamo optimization

### ISSUE THREAD

**Issue by wm901115nwpu** [pytorch/pytorch#97065]
### 🐛 Describe the bug

about torch._dynamo.optimizations, in recent release, I find it removed, where can I find it.

### Error logs

No

### Versions

No

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by Chillee** [comment]
I'm not totally sure what you're looking for in there, but I think most of it just got moved into `torch/_dynamo/backends`: https://github.com/pytorch/pytorch/tree/master/torch/_dynamo/backends
