### ISSUE TITLE
[compile] `assert "source" in options and options["source"] is not None`

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#97077]
### 🐛 Describe the bug

`model.compile()` (defaults) gives me:

```
          - 15485 - torch._dynamo.symbolic_convert - Step 1: torchdynamo start tracing get_rng_state
E           Traceback (most recent call last):
E             File "/actions-runner/_work/m4/m4/m4/training/main.py", line 176, in <module>
E               train_logs = trainer.train()
E             File "/actions-runner/_work/m4/m4/m4/training/trainer.py", line 1438, in train
E               ) = self._do_batch(
E             File "/actions-runner/_work/m4/m4/m4/training/trainer.py", line 560, in _do_batch
E               vl_output = self.vl_model(
E             File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E               return forward_call(*args, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
E               ret_val = func(*args, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/engine.py", line 1832, in forward
E               loss = self.module(*inputs, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E               return forward_call(*args, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 82, in forward
E               return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
E               return fn(*args, **kwargs)
E             File "/actions-runner/_work/m4/m4/m4/models/vgpt2/modeling_vgpt2.py", line 1213, in forward
E               transformer_outputs = self.transformer(
E             File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
E               return forward_call(*args, **kwargs)
E             File "/actions-runner/_work/m4/m4/m4/models/vgpt2/modeling_vgpt2.py", line 944, in forward
E               inputs_embeds = self.wte(input_ids)
E             File "/actions-runner/_work/m4/m4/m4/models/vgpt2/modeling_vgpt2.py", line 1023, in <graph break in forward>
E               outputs = torch.utils.checkpoint.checkpoint(
E             File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 249, in checkpoint
E               return CheckpointFunction.apply(function, preserve, *args)
E             File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 506, in apply
E               return super().apply(*args, **kwargs)  # type: ignore[misc]
E             File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 81, in forward
E               ctx.fwd_cpu_state = torch.get_rng_state()
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
E               return callback(frame, cache_size, hooks)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
E               result = inner_convert(frame, cache_size, hooks)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
E               return fn(*args, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
E               return _compile(
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
E               r = func(*args, **kwargs)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
E               out_code = transform_code_object(code, transform)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
E               transformations(instructions, code_options)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 311, in transform
E               tracer.run()
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
E               super().run()
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
E               and self.step()
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
E               getattr(self, inst.opname)(inst)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
E               return inner_fn(self, inst)
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
E               self.call_function(fn, args, {})
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
E               self.push(fn.call_function(self, args, kwargs))
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/torch.py", line 368, in call_function
E               return wrap_fx_proxy(
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
E               return wrap_fx_proxy_cls(
E             File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/variables/builder.py", line 812, in wrap_fx_proxy_cls
E               assert "source" in options and options["source"] is not None
E           AssertionError:
E           
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
E           from user code:
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
E              File "/usr/local/lib/python3.8/dist-packages/torch/random.py", line 23, in get_rng_state
E               return default_generator.get_state()
```

### Versions

pt-2.0

@Chillee 

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by Chillee** [comment]
@yanboliang Could you take a look as to whether this raises any bells?

**Comment by yanboliang** [comment]
@stas00 Do you have a repo that I can use to debug?

**Comment by stas00** [comment]
noting simple at the moment, as it's part of a huge thing. If the trace isn't enough, please feel free to ignore it for now - `compile` breaks in so many different ways at moment anyway - I have run into some 6-7 unrelated breakages the few times I have tried.

**Comment by ezyang** [comment]
This probably can probably be solved by good old fashioned code reading up the backtrace.

**Comment by ezyang** [comment]
@yanboliang Actually, @wanchaol ran into this recently, he has a repro: https://www.internalfb.com/phabricator/paste/view/P661760772

**Comment by yanboliang** [comment]
I can reproduce with https://www.internalfb.com/phabricator/paste/view/P661760772, thanks @ezyang @wanchaol.

Just took a cursory look, it seems ```default_generator.get_state()``` is a random generator who doesn't have ```source```, so triggered this error. I think we can follow [what we did for python ```random```](https://github.com/pytorch/pytorch/blob/master/torch/_dynamo/variables/user_defined.py#L260), to have a dedicated ```TorchRandomSource``` to save the random state, or just extend the existing ```RandomValueSource``` to support torch random generator.

I'll further verify my proposal tomorrow and send a PR.

**Comment by valine** [comment]
I was having this same bug running Dreambooth with dynamo. I was able to trace the issue back to this code in utils/checkpoint.py. The call to torch.get_rng_state seems to trigger the exception. 

https://github.com/pytorch/pytorch/blob/116a4f23016ecea430c947785d07702f20290bbd/torch/utils/checkpoint.py#L82-L87

Disabling "preserve_rng_state" fixed the issue for me, no more exception when training. Obviously not a solution long term, just sharing in case anyone needs a quick fix.

**Comment by yanboliang** [comment]
I sent #97403 which would fix the dynamo issue in @wanchaol's repro, but there is another AOT issue(I believe).
* With my fix and ```backend = "eager"```, the repro passed. 
* With my fix and aot_eager or inductor backend, the repro failed because ```Exception: Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. Found in aten.clone.default ... ```

**Comment by 3113911626** [comment]
> 我也有同样的虫子和迪纳摩一起运行Dreambooth。我能够将问题追溯到utils/checkpoint.py中的这段代码。对torch.get_rng_state 的调用似乎触发了异常。
> 
> https://github.com/pytorch/pytorch/blob/116a4f23016ecea430c947785d07702f20290bbd/torch/utils/checkpoint.py#L82-L87
> 
> 禁用“preserve_rng_state”为我解决了这个问题，在训练时没有更多的例外。

Can you tell me how? My Pytorch 2.0 training sd _ dreambooth _ extension has been failing

**Comment by jonathan-whitaker** [comment]
> > 我也有同样的虫子和迪纳摩一起运行Dreambooth。我能够将问题追溯到utils/checkpoint.py中的这段代码。对torch.get_rng_state 的调用似乎触发了异常。
> > https://github.com/pytorch/pytorch/blob/116a4f23016ecea430c947785d07702f20290bbd/torch/utils/checkpoint.py#L82-L87
> > 
> > 禁用“preserve_rng_state”为我解决了这个问题，在训练时没有更多的例外。
> 
> Can you tell me how? My Pytorch 2.0 training sd _ dreambooth _ extension has been failing

I ran into this and got passed it by turning off `Gradient Checkpointing` under setting tab

**Comment by gelatin-blunter12** [comment]
am i supposed to change anything about the code?
i have the same error even after turning off Gradient Checkpointing

**Comment by T-Atlas** [comment]
the same

**Comment by dailingx** [comment]
> > 我也有同样的虫子和迪纳摩一起运行Dreambooth。我能够将问题追溯到utils/checkpoint.py中的这段代码。对torch.get_rng_state 的调用似乎触发了异常。
> > https://github.com/pytorch/pytorch/blob/116a4f23016ecea430c947785d07702f20290bbd/torch/utils/checkpoint.py#L82-L87
> > 
> > 禁用“preserve_rng_state”为我解决了这个问题，在训练时没有更多的例外。
> 
> Can you tell me how? My Pytorch 2.0 training sd _ dreambooth _ extension has been failing

Did you solve this problem, I would also like to know how.
I can't turning off Gradient Checkpointing under setting tab beaucuse my GPU is not powerful enough.

**Comment by anijain2305** [comment]
As of today, torch.compile does not work with activation checkpointing. This is the top of our priority, and we are working on supporting it.

**Comment by LanceGao97** [comment]
> I ran into this and got past it by turning off `Gradient Checkpointing` under setting tab

Hi， can you give me a screen shot,  where this , " turning off `Gradient Checkpointing"  is under settings tab
I can't find it,  they translated it ,

**Comment by traveller6168** [comment]
File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/ui_functions.py", line 727, in start_training
    result = main(class_gen_method=class_gen_method)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1372, in main
    return inner_loop()
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/memory.py", line 119, in decorator
    return function(batch_size, grad_size, prof, *args, **kwargs)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1170, in inner_loop
    noise_pred = unet(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/utils/operations.py", line 495, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 582, in forward
    sample, res_samples = downsample_block(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 828, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(create_custom_forward(resnet), hidden_states, temb)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 250, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 82, in forward
    ctx.fwd_cpu_state = torch.get_rng_state()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 342, in wrapper
    return inner_fn(self, inst)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 965, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 474, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/variables/torch.py", line 368, in call_function
    return wrap_fx_proxy(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 754, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 812, in wrap_fx_proxy_cls
    assert "source" in options and options["source"] is not None


when set preserve_rng_state = Flase in  checkpoint.py and set unet=accelerator.unwrap_model(unet._torchdynamo_orig_callable.__self__, keep_fp32_wrapper=True) and in train_dreambooth.py torch._dynamo.config.verbose=True ,it also 
raise 
torch._dynamo.exc.Unsupported: Guard setup for uninitialized class <class 'torch.nn.modules.container.ModuleList'>
