### ISSUE TITLE
Inconsitent results before/after compilation for squeeze + tensor mutation + if statement

### ISSUE THREAD

**Issue by soodoshll** [pytorch/pytorch#97083]
### 🐛 Describe the bug

Hi! I found the following snippet produces different result before/after compilation.

```
import torch
def forward():
    a = torch.tensor([1])
    a = a[0:1]
    b = a.squeeze()
    a[0] = 0 #(*)
    if a[0] < 1e5:
        pass
    a[0] = 2
    return b

with torch.no_grad():
	print(forward()) # return 2
	fn_compiled = torch.compile(forward)
	print(fn_compiled()) # return 0
```

If commenting out the line highlighted with (*), we can get consistent results. However, a new warning emerges:

```
[2023-03-18 03:39:09,359] torch._inductor.graph: [WARNING] error in realize_users_of
Traceback (most recent call last):
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/graph.py", line 254, in realize_users_of
    visit(value)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/graph.py", line 248, in visit
    if value.is_user_of(name):
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/ir.py", line 353, in is_user_of
    return any(name == dep.name for dep in self.get_reads())
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/ir.py", line 3879, in __getattr__
    fn = getattr(self.data, name)
  File "/home/su/accdiff/thirdparty/pytorch/torch/_inductor/ir.py", line 3879, in __getattr__
    fn = getattr(self.data, name)
AttributeError: 'bool' object has no attribute 'get_reads'
```

Is this normal?

### Versions

PyTorch version: 2.1.0a0+gitfe05266
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.6.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           1
Model name:                      AMD Ryzen Threadripper 1950X 16-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        6786.49
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       1 MiB
L2 cache:                        8 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+git4805441
[pip3] triton==2.0.0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel

**Comment by ezyang** [comment]
I'm planning on looking into the get_reads warning

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/97251 gives us a more informative assert

```
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 217, in run
    return super().run(*args)
  File "/data/users/ezyang/a/pytorch/torch/fx/interpreter.py", line 137, in run
    self.env[node] = self.run_node(node)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 448, in run_node
    result = super().run_node(n)
  File "/data/users/ezyang/a/pytorch/torch/fx/interpreter.py", line 179, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 364, in call_function
    raise LoweringException(e, target, args, kwargs).with_traceback(
  File "/data/users/ezyang/a/pytorch/torch/_inductor/graph.py", line 361, in call_function
    out = lowerings[target](*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/lowering.py", line 227, in wrapped
    out = decomp_fn(*args, **kwargs)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/lowering.py", line 1024, in handler
    return pytree.tree_map(
  File "/data/users/ezyang/a/pytorch/torch/utils/_pytree.py", line 196, in tree_map
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/data/users/ezyang/a/pytorch/torch/utils/_pytree.py", line 196, in <listcomp>
    return tree_unflatten([fn(i) for i in flat_args], spec)
  File "/data/users/ezyang/a/pytorch/torch/_inductor/ir.py", line 3911, in create
    return TensorBox(StorageBox(data))
  File "<string>", line 4, in __init__
  File "/data/users/ezyang/a/pytorch/torch/_inductor/ir.py", line 3879, in __post_init__
    assert isinstance(object.__getattribute__(self, 'data'), IRNode)
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
LoweringException: AssertionError: 
  target: aten._has_same_storage_numel.default
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cpu', torch.int64, size=[1], stride=[1]))
  ))
  args[1]: TensorBox(StorageBox(
    InputBuffer(name='arg0_1', layout=FixedLayout('cpu', torch.int64, size=[1], stride=[1]))
  ))


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

```

We can see that the problem is we're putting a bool into a StorageBox, which violates invariants.

**Comment by ezyang** [comment]
> If commenting out the line highlighted with (*), we can get consistent results. However, a new warning emerges:

One more interesting thing: the commented out model actually returns wrong result: 

```
AssertionError: The values for attribute 'shape' do not match: torch.Size([]) != torch.Size([1]).
```

**Comment by williamwen42** [comment]
Using backend `eager` results in outputs
```
tensor(2)
tensor(2)
```
Using backend `aot_eager`/`aot_eager_decomp_partition` results in outputs
```
tensor(2)
tensor([2])
```
Using backend `inductor` gives wrong results, even with `dynamic=False`
```
tensor(2)
tensor(0)
```
