### ISSUE TITLE
TypeError when creating a custom extension

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#9709]
## Issue description

TypeError when compiling master branch

```
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    extra_compile_args=extra_compile_args,
  File "/home/carmocca/PyLaia/PyLaia-env/local/lib/python2.7/site-packages/torch/utils/ffi/__init__.py", line 179, in 
create_extension
    kwargs['extra_compile_args'] = ['-std=c99'] + kwargs.get('extra_compile_args', [])
TypeError: can only concatenate list (not "dict") to list
```

Where `kwargs.get('extra_compile_args', [])` is `{'cxx': ['-std=c++11', '-O2', '-fopenmp'], 'nvcc': ['-std=c++11', '-O2', '-ccbin=gcc-4.9']}`

## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source): `python setup.py install`
- OS: Ubuntu 16.04.4 LTS
- PyTorch version: 0.5.0a0+1afdc57
- Python version: 2.7
- CUDA version: 9.0.176
- GPU models and configuration: GPU 0: GeForce GTX 1080
- GCC version (if compiling from source): (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
- CMake version: version 3.5.1
- Versions of any other relevant libraries: [pip] 8.1.1

**Comment by zou3519** [comment]
Could you try the following:
- pip uninstall torch
- pip uninstall torch (yes, twice)
- reinstall pytorch and see if the error still happens?

At any rate the logic does look wrong, so we'll look into it

**Comment by carmocca** [comment]
Hi, thank you for your reply.

```
$ pip uninstall torch
Uninstalling torch-0.5.0a0+9ee5133:
  Would remove:
    /home/carmocca/PyLaia/PyLaia-env/lib/python2.7/site-packages/torch
    /home/carmocca/PyLaia/PyLaia-env/lib/python2.7/site-packages/torch-0.5.0a0+9ee5133-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled torch-0.5.0a0+9ee5133

$ pip uninstall torch
Skipping torch as it is not installed.

$ python setup.py install
... Everything OK.
```

Doing the steps you mentioned I realized that I am not getting the TypeError when installing Torch but a custom extension of mine (My bad!).

However, it uses the class `BuildExtension` from torch/utils/cpp_extension.py which has the following [comment](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L126-L127):

> When using :class:`BuildExtension`, it is allowed to supply a dictionary for ``extra_compile_args`` (rather than the usual list)

This seems to suggest that the logic between ffi/create_extension and utils/cpp_extension has diverged.

Any idea?
