### ISSUE TITLE
RuntimeError: only batches of spatial targets supported (3D tensors) but got targets of dimension: 1

### ISSUE THREAD

**Issue by LeoMyMe** [pytorch/pytorch#97094]
### 🐛 Describe the bug

I want to train a graphic model，

  **class PPD_Data(Dataset):
      def __init__(self,Root_Dir,Label_Dir,TransForm):
          self.Root_Dir=Root_Dir
          self.Label_Dir=Label_Dir
          self.Full_Path = os.path.join(self.Root_Dir,self.Label_Dir)
          self.Path = os.listdir(self.Full_Path)
          self.TransForm = TransForm
  
      def __getitem__(self, index):
          Pic_Name=self.Path[index]
          Pic_Path=os.path.join(self.Root_Dir,self.Label_Dir,Pic_Name) 
          Picture=Image.open(Pic_Path).convert("RGB")
          Label=int(self.Label_Dir)
          Picture = self.TransForm(Picture)
          return Picture,Label
      
      def __len__(self):
          return len(self.Path)**

This is my Dataset.
And this is my data in DataLoader(Down):

**[0.5608, 0.5608, 0.5608,  ..., 0.5608, 0.5608, 0.5608],
[0.5608, 0.5608, 0.5608,  ..., 0.5608, 0.5608, 0.5608],
[0.5608, 0.5608, 0.5608,  ..., 0.5608, 0.5608, 0.5608]]]]), tensor([1, 1])]**

In Dataset,When I change _Label=int(self.Label_Dir)_ to _Label=self.Label_Dir_.It will cause:**TypeError: cross_entropy_loss(): argument 'target' (position 2) must be Tensor, not tuple**.If I don't change it,it whill cause as same as the title.

So,please tell me how can I fix this?Thank you.

### Versions

torch:2.0.0
python:3.8.16(conda)
OS:Windows 11

**Comment by cpuhrsch** [comment]
Hi, We use github issues only for bug reports or feature requests. Please use the forum to ask questions: https://discuss.pytorch.org/
