### ISSUE TITLE
Inconsistent results when mutating a tensor with shared storage in a nested function

### ISSUE THREAD

**Issue by soodoshll** [pytorch/pytorch#97130]
### 🐛 Describe the bug

Hi! I found the next snippet will generate different results before/after compilation. It exists for both CPU and CUDA backend. I'm not sure but it might be related to #97083 and #97115.

```
import torch

def forward():
    a = torch.ones(2)
    b = a.reshape(2)
    c = a[0:2] # So a, b, c share the same storage?

    def subfunc():
        b[0] = 2
        if b.sum() >= -1e5:
            pass

    subfunc()
    return c

print(forward()) # [2., 1.]
fn_compiled = torch.compile(forward)
print(fn_compiled()) # [1., 1.]


```

### Versions

<details>
PyTorch version: 2.1.0a0+gitfe05266
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.9.5 (default, Nov 23 2021, 15:27:38)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070
Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-11.3/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.6.0
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.6.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.7.0
/usr/local/cuda-11.7/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           1
Model name:                      AMD Ryzen Threadripper 1950X 16-Core Processor
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3400.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        6786.49
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       1 MiB
L2 cache:                        8 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT vulnerable
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0a0+git5d33f9c
[pip3] triton==2.0.0.post1
</details>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ngimel** [comment]
cc @bdhirsh, looks like mutation is not copied back?

**Comment by ezyang** [comment]
Workaround is to replace reshape with view. So it is definitely reshape shenanigans.

cc @dagitses for stride agnostic PyTorch.

**Comment by ezyang** [comment]
Note that this code still works under CoW reshape because a is never referenced after mutation.

**Comment by ezyang** [comment]
Actually, the script as is works on master 85112b0dccb2e2d2f3cd568ceffc2dda850d5756 . @soodoshll can you check a more recent nightly?

**Comment by ezyang** [comment]
Also repros with view() now.

**Comment by bdhirsh** [comment]
I see a `copy_()` in the graph that aot_autograd sends to the backend. I also confirmed that this passes with `backend='aot_eager'`.

**Comment by bdhirsh** [comment]
Looks like inductor isn't handling the `copy_()` well. Here's the aot_autograd FX graph, and the output inductor code:

FX graph:
```
def forward(self, arg0_1):
    _tensor_constant0 = self._tensor_constant0
    lift_fresh_copy = torch.ops.aten.lift_fresh_copy.default(_tensor_constant0);  _tensor_constant0 = None
    select = torch.ops.aten.select.int(arg0_1, 0, 0)
    device_put = torch.ops.prims.device_put.default(lift_fresh_copy, device(type='cuda', index=0));  lift_fresh_copy = None
    convert_element_type = torch.ops.prims.convert_element_type.default(device_put, torch.float32);  device_put = None
    select_scatter = torch.ops.aten.select_scatter.default(arg0_1, convert_element_type, 0, 0);  convert_element_type = None
    select_1 = torch.ops.aten.select.int(select_scatter, 0, 0)
    sum_1 = torch.ops.aten.sum.default(select_scatter)
    ge = torch.ops.aten.ge.Scalar(sum_1, -100000.0);  sum_1 = None
    copy_ = torch.ops.aten.copy_.default(arg0_1, select_scatter);  arg0_1 = select_scatter = None
    return (ge,)
```

inductor code:
```
from ctypes import c_void_p, c_long
import torch
import math
import random
from torch import empty_strided, as_strided, device
from torch._inductor.codecache import AsyncCompile
from torch._inductor.select_algorithm import extern_kernels

aten = torch.ops.aten
assert_size_stride = torch._C._dynamo.guards.assert_size_stride
async_compile = AsyncCompile()

import triton
import triton.language as tl
from torch._inductor.triton_ops.autotune import grid, start_graph, end_graph
from torch._C import _cuda_getCurrentRawStream as get_cuda_stream


# kernel path: /tmp/torchinductor_hirsheybar/gs/cgsmrhhnelkxo5fhek25abfqvgi4zsx2jkg4rrovzqbziq3mfa4z.py
# Original ATen: aten.copy, aten.ge, aten.sum, aten.select_scatter, aten.lift_fresh

# aten.copy => device_put
# aten.ge => ge
# aten.sum => sum_1
# aten.select_scatter => select_scatter
# aten.lift_fresh => lift_fresh_copy
triton_fused_copy_ge_lift_fresh_select_scatter_sum_0 = async_compile.triton('''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_ops.autotune import persistent_reduction
from torch._inductor.utils import instance_descriptor

@persistent_reduction(
    size_hints=[1, 2],
    reduction_hint=ReductionHint.INNER,
    filename=__file__,
    meta={'signature': {0: '*fp32', 1: '*fp32', 2: '*i1', 3: 'i32', 4: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': [], 'configs': [instance_descriptor(divisible_by_16=(0, 1, 2), equal_to_1=())]}
)
@triton.jit
def triton_(in_ptr0, out_ptr0, out_ptr1, xnumel, rnumel, XBLOCK : tl.constexpr, RBLOCK : tl.constexpr):
    xnumel = 1
    rnumel = 2
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:, None]
    xmask = xindex < xnumel
    rindex = tl.arange(0, RBLOCK)[None, :]
    rmask = rindex < rnumel
    r0 = rindex
    tmp4 = tl.load(in_ptr0 + (r0), rmask, other=0)
    tmp0 = r0
    tmp1 = 0
    tmp2 = tmp0 == tmp1
    tmp3 = 2.0
    tmp5 = tl.where(tmp2, tmp3, tmp4)
    tmp7 = tl.where(rmask, tmp5, 0)
    tmp8 = tl.sum(tmp7, 1)[:, None]
    tmp9 = -100000.0
    tmp10 = tmp8 >= tmp9
    tl.store(out_ptr1 + (0 + tl.zeros([XBLOCK, 1], tl.int32)), tmp10, None)
    tl.store(out_ptr0 + 0 + tl.zeros([XBLOCK, 1], tl.int32), tmp8, None)
''')


# kernel path: /tmp/torchinductor_hirsheybar/cd/ccdbesvbxyknip36ln46yecgrmmvdpy23y5bbt4qm3kbi2f4lhwl.py
# Original ATen: aten.copy, aten.select_scatter, aten.lift_fresh

# aten.copy => device_put
# aten.select_scatter => select_scatter
# aten.lift_fresh => lift_fresh_copy
triton_fused_copy_lift_fresh_select_scatter_1 = async_compile.triton('''
import triton
import triton.language as tl
from torch._inductor.ir import ReductionHint
from torch._inductor.ir import TileHint
from torch._inductor.triton_ops.autotune import pointwise
from torch._inductor.utils import instance_descriptor

@pointwise(size_hints=[2], filename=__file__, meta={'signature': {0: '*fp32', 1: '*fp32', 2: 'i32'}, 'device': 0, 'constants': {}, 'mutated_arg_names': ['in_ptr0', 'out_ptr1'], 'configs': [instance_descriptor(divisible_by_16=(0, 1), equal_to_1=())]})
@triton.jit
def triton_(in_ptr0, out_ptr1, xnumel, XBLOCK : tl.constexpr):
    xnumel = 2
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp4 = tl.load(in_ptr0 + (x0), xmask)
    tmp0 = x0
    tmp1 = 0
    tmp2 = tmp0 == tmp1
    tmp3 = 2.0
    tmp5 = tl.where(tmp2, tmp3, tmp4)
    tl.store(out_ptr1 + (x0 + tl.zeros([XBLOCK], tl.int32)), tmp5, xmask)
''')


async_compile.wait(globals())
del async_compile

def call(args):
    arg0_1, = args
    args.clear()
    with torch.cuda._DeviceGuard(0):
        torch.cuda.set_device(0) # no-op to ensure context
        buf0 = empty_strided((), (), device='cuda', dtype=torch.float32)
        buf3 = empty_strided((), (), device='cuda', dtype=torch.bool)
        stream0 = get_cuda_stream(0)
        triton_fused_copy_ge_lift_fresh_select_scatter_sum_0.run(arg0_1, buf0, buf3, 1, 2, grid=grid(1), stream=stream0)
        triton_fused_copy_lift_fresh_select_scatter_1.run(arg0_1, arg0_1, 2, grid=grid(2), stream=stream0)
        del arg0_1
        return (buf3, )
```

**Comment by williamwen42** [comment]
Most recent repro is no longer giving incorrect result - both function calls give the same output.
