### ISSUE TITLE
Segmentation fault in forward pass with torch 2.1.0 - BEiTv2

### ISSUE THREAD

**Issue by isdj** [pytorch/pytorch#97145]
### 🐛 Describe the bug

When trying to run BEiT V2 with the new `model.compile` function I seem to get a segmentation fault. I reproduced with stock repository.

You can see my fork of unilm [here](https://github.com/isdj/unilm). You can use the conda environment [beit2/environment.yml](https://github.com/isdj/unilm/blob/master/beit2/environment.yml).
Command which fails:
`cd <unilm_path>/beit2/semantic_segmentation; python tools/train.py configs/beit/upernet/upernet_beit_base_12_512_slide_160k_21ktoade20k.py --work-dir /tmp/beit2_test/`

This command fails when I uncomment the model.compile in [beit2/semantic_segmentation/mmcv_custom/train_api.py](https://github.com/isdj/unilm/blob/master/beit2/semantic_segmentation/mmcv_custom/train_api.py):86 with a segmentation fault.

Stdout once forward pass is called:
```
[2023-03-20 10:52:08,616] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
/opt/conda/lib/python3.9/site-packages/torch/_inductor/compile_fx.py:93: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
[2023-03-20 10:52:23,150] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Segmentation fault (core dumped)
```
I am running on a [g5 instance ](https://aws.amazon.com/ec2/instance-types/g5/) with one GPU, Cuda117

Please note you need to have Ade20K dataset available and set data root path in [beit2/semantic_segmentation/configs/_base_/datasets/ade20k.py](https://github.com/isdj/unilm/blob/master/beit2/semantic_segmentation/configs/_base_/datasets/ade20k.py)

Core Can't be shared on github due to size (over 8Gb).

### Versions

PyTorch version: 2.1.0.dev20230307+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.10.167-147.601.amzn2.x86_64-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7R32
Stepping:                        0
CPU MHz:                         2018.643
BogoMIPS:                        5599.90
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        8 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] pytorch-triton==2.0.0+b8b470bc59
[pip3] sagemaker-pytorch-training==2.7.0
[pip3] torch==2.1.0.dev20230307+cu117
[pip3] torchaudio==2.0.0.dev20230307+cu117
[pip3] torchdata==0.5.1
[pip3] torchmetrics==0.10.3
[pip3] torchnet==0.0.4
[pip3] torchvision==0.15.0.dev20230306+cu117
[conda] magma-cuda117             2.6.1                         1    pytorch
[conda] mkl                       2022.2.1         h84fe81f_16997    conda-forge
[conda] mkl-include               2023.0.0         h84fe81f_25396    conda-forge
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+b8b470bc59          pypi_0    pypi
[conda] sagemaker-pytorch-training 2.7.0                    pypi_0    pypi
[conda] torch                     2.1.0.dev20230307+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230307+cu117          pypi_0    pypi
[conda] torchdata                 0.5.1                    pypi_0    pypi
[conda] torchmetrics              0.10.3                   pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.15.0.dev20230306+cu117          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by Chillee** [comment]
@isdj Is it possible to run the minifier? Run `TORCHDYNAMO_REPRO_AFTER="aot"`, and then either run that resulting script (ideal) or at least send that code here.

**Comment by isdj** [comment]
@Chillee I set the environment variable as requested but I still get a segmentation fault - not a minified version

**Comment by isdj** [comment]
@Chillee  I am also receiving a segmentation error with the [Segmenter model](https://github.com/rstrudel/segmenter) - anothe ViT based model
