### ISSUE TITLE
Create a process for automated update of Triton pin

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#97165]
Currently updating triton pin is more involved than it should be, due to frequent errors in triton wheel build scripts that have some hardcoded versions. A lot of hardcoding has been fixed by @malfet (thanks!), with hopefully last bit being fixed in #96730. 

We need relatively frequent triton updates, as a lot of bug fixes and perf improvements are happening there. Ideally, devinfra should handle infra parts of the update (making sure that wheels are building) with inductor team fixing test errors that appear due to moving pin. 

I anticipate moving pin approx every 2 weeks, but can be more or less frequent depending on whether critical bugs are discovered. Some fixes critical bugs can be cherry-picked into triton stable branch, to make updates easier. 

cc @malfet @seemethere @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by malfet** [comment]
@clee2000 @atalman would any of you have bandwith of automating this step?
