### ISSUE TITLE
DISABLED test_cpp_wrapper_cpu (__main__.CpuTests)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#97194]
Platforms: macos, mac

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/inductor%2Ftest_torchinductor.py%3A%3ACpuTests%3A%3Atest_cpp_wrapper_cpu)).

Test is constantly failing in trunk, so disable it while investigate.  The test wasn't run before because it was marked as slow

```
inductor/test_torchinductor.py::CpuTests::test_cpp_wrapper_cpu SKIPPED (test is slow; run with PYTORCH_TEST_WITH_SLOW to enable test) [ 32%]
```

Now it runs and is failing for MacOS in trunk.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @albanD @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by clee2000** [comment]
I'm fairly sure this test either got renamed or doesn't exist anymore
