### ISSUE TITLE
aten::sym_size is not using torch._ops.OpOverload in FX graph

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#97201]
### 🐛 Describe the bug

aten::sym_size has two overloads, but none of them are used. In FX graph, OverloadPacket itself seems to be used. Not sure if this is intended, or it's a bug, but it seems to be inconsistent to other ops.

```python
import torch
from torch.fx.experimental.proxy_tensor import make_fx

class MyModule(torch.nn.Module):
    def forward(self, x):
        return torch.flatten(x, start_dim=2, end_dim=3)

x = torch.randn(3, 5, 4, 5)
m = make_fx(MyModule(), tracing_mode="symbolic")(x)

for node in m.graph.nodes:
    if isinstance(node.target, torch._ops.OpOverloadPacket):
        print(type(node.target))  # <class 'torch._ops.OpOverloadPacket'>
        print(node.target.overloads())  # ['default', 'int']
```

### Versions

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] pytorch==2.1.0a0+git3e6bde0
[pip3] torchaudio==0.13.0.dev20220912+cpu
[pip3] torchvision==0.15.0a0+511924c
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.1           py39h6c91a56_0  
[conda] numpy-base                1.23.1           py39ha15fc14_0  
[conda] pytorch                   2.1.0a0+git3e6bde0           dev_0    <develop>
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.13.0.dev20220912+cpu          pypi_0    pypi
[conda] torchvision               0.15.0a0+511924c          pypi_0    pypi

cc @ezyang @BowenBao

**Comment by SherlockNoMad** [comment]
We are aware of this issue. 
https://github.com/pytorch/pytorch/pull/92402 would resolve the issue, but it's reverted due to breaking internal build.

**Comment by Chillee** [comment]
@SherlockNoMad Is that issue actually connected to this? Or is this issue just about tracing the overload instead of the overloadpacket?

**Comment by SherlockNoMad** [comment]
> @SherlockNoMad Is that issue actually connected to this? Or is this issue just about tracing the overload instead of the overloadpacket?

aten::sym_size has an aten-op-liked signature, and lives in Fx-Aten graph, and user would naturally expect it to behave like other aten ops. However, it's actually not even an OpOverload, due the way it's authored today :) 

Functionality-wise, aten::sym_size works fine. In this sense, this is not a "bug". 
However, we do want aten.sym_size to have the uniformed behavior as other aten ops.

**Comment by BowenBao** [comment]
@SherlockNoMad Could you enlighten more on what type to expect for `node.target` from dynamo traced fx graph
* Are there other types than `OpOverloadPacket` and `OpOverload`?
* Under what circumstances would an op appear as `OpOverloadPacket`?

**Comment by titaiwangms** [comment]
Also, sym_size is not in torh.ops.aten
