### ISSUE TITLE
Illegal instruction (core dumped) : PyTorch 2.0 on Raspberry Pi 4.0 8gb 

### ISSUE THREAD

**Issue by P-Blackburn** [pytorch/pytorch#97226]
### 🐛 Describe the bug

Virgin install on Raspberry Pi 4.0 8gb

```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
python3 -c "import torch;print(torch.__version__)"
```
results in:  
```Illegal instruction.```  and a core dump (on Ubuntu) and fails on the basic 64 Raspberry Pi Debian based OS...

HOWEVER:

Ignoring the installation instructions on [https://pytorch.org/](https://pytorch.org/), and instead installing with:

```pip3 install https://download.pytorch.org/whl/torch-2.0.0-cp310-cp310-manylinux2014_aarch64.whl```

results in version of torch 2.0.0 that will work on the Raspberry Pi 4

### Versions

executing:

```bash
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
also results in ```Illegal instruction```

(further - uninstalling torch 2.0.0 and attempting to install 1.13.1 per the instructions on [https://pytorch.org/get-started/previous-versions/](https://pytorch.org/get-started/previous-versions/) i.e. 
```bash
pip install torch==1.13.1+cpu torchvision==0.14.1+cpu torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cpu
```

results in 
```bash
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cpu
ERROR: No matching distribution found for torch==1.13.1+cpu
```
that said an install of the form:

```bash
pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cpu
```

works a treat and 
```bash
python3 -c "import torch;print(torch.__version__);print(torch.rand(3))"
```
returns what is expected: 
```bash
1.13.1
tensor([0.1033, 0.6867, 0.4403])
```

python collect_env.py against the 1.13.1 works and returns:

Collecting environment information...
PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 11 (bullseye) (aarch64)
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110] (64-bit runtime)
Python platform: Linux-6.1.19-v8+-aarch64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1800.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
L1d cache:                       128 KiB
L1i cache:                       192 KiB
L2 cache:                        1 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
@P-Blackburn can you please attach gdb to the process and print the instruction that causes an issue?
Also, can you try installing torch==1.13.0 and see if invalid instruction issue reproduces there. (I suspect it's ACL/MKLDNN integration)

**Comment by P-Blackburn** [comment]
Hi yes torch==1.13.0 works, also as I said in the main post ```pip3 install https://download.pytorch.org/whl/torch-2.0.0-cp310-cp310-manylinux2014_aarch64.whl```    'works' with a version of PyTorch 2.0.0.   

What doesn't work is ```pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu```  which essentially is the equivalent of ```pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/torch-2.0.0-1-cp310-cp310-manylinux2014_aarch64.whl```

I am not very familiar with gdb, so please bear with me and direct me if I need to do something differently....
I installed gdb with ```sudo apt install gdb``` and installed ```sudo pip install pygdbmi```

I then created a test.py of:
```python
import torch
print(torch.__version__)
```

having then installed PyTorch with:  ```pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu```

I get the following output:

```bash
pi@TRACY:~$ vi test.py
pi@TRACY:~$ python3 test.py
Illegal instruction (core dumped)
pi@TRACY:~$ gdb python3
GNU gdb (Ubuntu 12.1-3ubuntu2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) run test.py
Starting program: /usr/bin/python3 test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000ffffed488930 in std::string::_Rep::_M_dispose(std::allocator<char> const&) [clone .part.0] () from /usr/local/lib/python3.10/dist-packages/torch/lib/../../torch.libs/libarm_compute-d27e629c.so
```

I removed PyTorch and installed torch==1.13.0 and also put that through gdb and the output was:
```bash
pi@TRACY:~$ python3 test.py
1.13.0
pi@TRACY:~$ gdb python3
GNU gdb (Ubuntu 12.1-3ubuntu2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) run test.py
Starting program: /usr/bin/python3 test.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xffffeb34f1a0 (LWP 12077)]
[New Thread 0xffffeab3f1a0 (LWP 12078)]
[New Thread 0xffffe632f1a0 (LWP 12079)]
1.13.0
[Thread 0xffffe632f1a0 (LWP 12079) exited]
[Thread 0xffffeab3f1a0 (LWP 12078) exited]
[Thread 0xffffeb34f1a0 (LWP 12077) exited]
[Inferior 1 (process 12075) exited normally]

```

**Comment by malfet** [comment]
@P-Blackburn thank you very much for detailed repro (alas, my Raspberry Pi is still running 32-bit linux, guess it's time to upgrade)
Most likely regression caused by https://github.com/pytorch/builder/pull/1291 and the fact that ACL integration was enabled, see https://github.com/pytorch/pytorch/issues/96983
@snadampal is it really necessary to compile ACL with arch=armv8.2-a

**Comment by snadampal** [comment]
Hi @malfet , I'm surprised it's working on PT 1.13.0 but not on 2.0.0.1 because we have enabled the MKLDNN+ACL integration in 1.13.0 itself, and ACL was built with`arch=armv8.2-a`  even for 1.13.0. Of course we have upgraded the ACL version this time. Let me check if `armv8a` is sufficient.

**Comment by snadampal** [comment]
Hi @P-Blackburn , just to be double sure your 1.13.0 has mkldnn+acl, could you please run this on 1.13.0 installation and share the output.
`$ python -c "import torch; print(torch.__version__, torch.backends.mkldnn.is_available())"`

Is the illegal instruction coming from any particular gemm kernel?  I'm trying to understand whether the issue is specific to PT2.0 ACL version or present even on PT1.13 ACL.

**Comment by P-Blackburn** [comment]
Hi @snadampal - I installed and tested 1.13.0 and 1.13.1 one was True the other was False

# torch==1.13.0 True

```bash
peter@TRACY:~$ sudo pip install torch==1.13.0                                       Collecting torch==1.13.0
  Downloading torch-1.13.0-cp310-cp310-manylinux2014_aarch64.whl (73.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.2/73.2 MB 1.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch==1.13.0) (4.5.0)
Installing collected packages: torch
Successfully installed torch-1.13.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
peter@TRACY:~$ python3 -c "import torch; print(torch.__version__, torch.backends.mkldnn.is_available())"
1.13.0 True
peter@TRACY:~$


```

# torch==1.13.1  False

```bash
peter@TRACY:~$ sudo pip install torch==1.13.1
Collecting torch==1.13.1
  Using cached torch-1.13.1-cp310-cp310-manylinux2014_aarch64.whl (60.5 MB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch==1.13.1) (4.5.0)
Installing collected packages: torch
Successfully installed torch-1.13.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
peter@TRACY:~$ python -c "import torch; print(torch.__version__, torch.backends.mkldnn.is_available())"
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
peter@TRACY:~$ python3 -c "import torch; print(torch.__version__, torch.backends.mkldnn.is_available())"
1.13.1 False
peter@TRACY:~$
```

**Comment by P-Blackburn** [comment]
Hi @snadampal  in answering the part of your question "Is the illegal instruction coming from any particular gemm kernel"  Please do forgive me if I have not understood the question properly.  However, I believe that simply trying to "import torch" when the installed version is torch-2.0.0-1-cp310-cp310-manylinux2014_aarch64.whl  (which is the version installed following the instructions on the PyTorch.org installation page giving installation as: ```pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu```   immediately causes the illegal instruction and core dump

**Comment by P-Blackburn** [comment]
Hi @malfet  

I have: added keys, and a root account, and opened ssh ports, along with assigning a static address to  nikita@nikita.casecare.com  

I will be rebuilding this Pi when you have done with it, but in the meantime in the objectively reasonable context of PyTorch testing you can use this machine, install uninstall etc as you need for the testing.

Please let me know when you are 'in' and then I can expunge this post ;)  
I left a README in the $HOME folder

**Comment by malfet** [comment]
@P-Blackburn thank you very much, I'm in

**Comment by nSircombe** [comment]
Hi @malfet 
I'm able to reproduce the illegal instruction running ACL's validation quite on Cortex-A72. I've not gone back to check earlier releases. It looks like an issue with the 'multi-isa' build, we'll have to take a closer look.

**Comment by P-Blackburn** [comment]
Hi @malfet and @nSircombe   - I have also tested on the Raspberry Pi3 and found that the same illegal instruction and core dump also affects Cortex-A53.

**Comment by malfet** [comment]
nSircombe, at the very least, there are no global constructor issue if one uses [22.05](https://github.com/ARM-software/ComputeLibrary/tree/v22.05) vs v22.11

**Comment by malfet** [comment]
Small update: the same crash is observable on [AWS A1 instances](https://aws.amazon.com/ec2/instance-types/a1/)

**Comment by 35grain** [comment]
Can confirm this is happening with the latest torch 2.0.0 version when importing the package on Raspberry Pi 4 4GB Ubuntu.

**Comment by atalman** [comment]
cc @snadampal . Thank for for cherry-picks. Please make sure to have all cherry-picks ready for April 14, 5PM PST.


This issue is in the  milestones :[ https://github.com/pytorch/pytorch/milestone/36?closed=1](https://github.com/pytorch/pytorch/milestone/36?closed=1), if you want to see your fix included in this minor release. Please post it as a cherry-pick into the [[v2.0.1] Release Tracker](https://github.com/pytorch/pytorch/issues/97272). 

**The deadline is April 14, 5PM PST.**

**Only issues that have ‘cherry-picks’ will be considered for the release.**

Common FAQs:

Q1: Where can I find more information on the release process and terminology?

A: [pytorch/RELEASE.md at master · pytorch/pytorch · GitHub](https://github.com/pytorch/pytorch/blob/master/RELEASE.md)

Q2: Am I guaranteed to be included in the cherry-pick if I do above?

A: No, it is not guaranteed, the Release Team will review all submissions against the listed criteria before making the final decision on what to include on 4/17.

Q3: When is 2.1 going to be released?

A: We do not have a formal date at this time but will update the community when we do. Our immediate focus is 2.0.1. Note that 1.12 was released on 6/28/22, 1.13 on 10/28/22 and 2.0 on 3/15/23.

Q4: **I missed the 4/14 5PM PST deadline, is there any option to have an extension?**

A: **No, in order to meet our 4/28 goal, we must hold 4/14 as our deadline and will not accept any requests after the fact. We are over communicating the timelines and process with the community to avoid such issues.**

Q5: Where should I double check to see if my issue is in the cherry pick tracker?

A: [[v2.0.1] Release Tracker · Issue #97272 · pytorch/pytorch · GitHub](https://github.com/pytorch/pytorch/issues/97272)

Q6: Where can I find the Release Compatibility Matrix for PyTorch?

A: [pytorch/RELEASE.md at master · pytorch/pytorch · GitHub](https://github.com/pytorch/pytorch/blob/master/RELEASE.md#release-compatibility-matrix)

Please contact OSS Releng team members if you have any questions/comments. Again we appreciate everyone’s time and commitment to the community, PyTorch and 2.0 and 2.01 releases!


Please refer to this post for more details: https://dev-discuss.pytorch.org/t/pytorch-release-2-0-1-important-information/1176

**Comment by snadampal** [comment]
thanks, @atalman . I have posted this cherrypick request in the PyTorch 2.0.1 release tracker
- https://github.com/pytorch/pytorch/issues/97272#issuecomment-1496354441

**Comment by malfet** [comment]
Tested that 2.0.1 release candidate binaries (available at https://download.pytorch.org/whl/test/cpu ) no longer exhibit the problem on AWS A1 instances:
```
$ pip3 install torch --index-url https://download.pytorch.org/whl/test/cpu
$ python3 -mtorch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (aarch64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1031-aws-aarch64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       ARM
Model name:                      Cortex-A72
Model:                           3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       2
Stepping:                        r0p3
BogoMIPS:                        166.66
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
L1d cache:                       256 KiB (8 instances)
L1i cache:                       384 KiB (8 instances)
L2 cache:                        4 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening, BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] torch==2.0.1
[conda] Could not collect
$ python3 -c "import torch;x=torch.rand(3, 3);print(torch.linalg.svd(torch.mm(x,x.t())))"
<string>:1: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /root/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
torch.return_types.linalg_svd(
U=tensor([[-0.4932, -0.0094, -0.8699],
        [-0.8040, -0.3770,  0.4599],
        [-0.3322,  0.9262,  0.1783]]),
S=tensor([1.9125e+00, 6.0053e-01, 1.5409e-03]),
Vh=tensor([[-0.4932, -0.8040, -0.3322],
        [-0.0094, -0.3770,  0.9262],
        [-0.8699,  0.4599,  0.1783]]))

**Comment by aseok** [comment]
Same issue with pytorch 2.0.1 rocm 5.4.2 on a pentium g4400.

**Comment by Vigilans** [comment]
This issue has been seen to reproduce in torch 2.4.0:
```
Thread 1 "python3" received signal SIGILL, Illegal instruction.
0x0000ffff3deff800 in std::string::_Rep::_M_dispose(std::allocator<char> const&) [clone .part.0] ()
   from /usr/local/lib/python3.8/site-packages/torch/lib/../../torch.libs/libarm_compute-6cddc52f.so
(gdb) disassemble
Dump of assembler code for function _ZNSs4_Rep10_M_disposeERKSaIcE.part.0:
   0x0000ffff3deff7d4 <+0>:     adrp    x2, 0xffff3e128000 <_ZTVN8arm_conv7pooling24PoolingDepthfirstGenericIDhDhNS0_7NothingEEE+24>
   0x0000ffff3deff7d8 <+4>:     ldr     x2, [x2, #3472]
   0x0000ffff3deff7dc <+8>:     cbnz    x2, 0xffff3deff7f8 <_ZNSs4_Rep10_M_disposeERKSaIcE.part.0+36>
   0x0000ffff3deff7e0 <+12>:    ldr     w2, [x0, #16]
   0x0000ffff3deff7e4 <+16>:    sub     w3, w2, #0x1
   0x0000ffff3deff7e8 <+20>:    str     w3, [x0, #16]
   0x0000ffff3deff7ec <+24>:    cmp     w2, #0x0
   0x0000ffff3deff7f0 <+28>:    b.le    0xffff3deff808 <_ZNSs4_Rep10_M_disposeERKSaIcE.part.0+52>
   0x0000ffff3deff7f4 <+32>:    ret
   0x0000ffff3deff7f8 <+36>:    add     x3, x0, #0x10
   0x0000ffff3deff7fc <+40>:    mov     w2, #0xffffffff                 // #-1
=> 0x0000ffff3deff800 <+44>:    ldaddal w2, w2, [x3]
   0x0000ffff3deff804 <+48>:    b       0xffff3deff7ec <_ZNSs4_Rep10_M_disposeERKSaIcE.part.0+24>
   0x0000ffff3deff808 <+52>:    b       0xffff3d9484f0 <_ZNSs4_Rep10_M_destroyERKSaIcE@plt>
End of assembler dump.
```
* Python version: 3.8.19
* CPU model: FT-2000+/64
```
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x70
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0x662
CPU revision    : 2
```

Is it a regression bug?

**Comment by guylevinairo** [comment]
> This issue has been seen to reproduce in torch 2.4.0:
> 
> ```
> Thread 1 "python3" received signal SIGILL, Illegal instruction.
> 0x0000ffff3deff800 in std::string::_Rep::_M_dispose(std::allocator<char> const&) [clone .part.0] ()
>    from /usr/local/lib/python3.8/site-packages/torch/lib/../../torch.libs/libarm_compute-6cddc52f.so
> (gdb) disassemble
> Dump of assembler code for function _ZNSs4_Rep10_M_disposeERKSaIcE.part.0:
>    0x0000ffff3deff7d4 <+0>:     adrp    x2, 0xffff3e128000 <_ZTVN8arm_conv7pooling24PoolingDepthfirstGenericIDhDhNS0_7NothingEEE+24>
>    0x0000ffff3deff7d8 <+4>:     ldr     x2, [x2, #3472]
>    0x0000ffff3deff7dc <+8>:     cbnz    x2, 0xffff3deff7f8 <_ZNSs4_Rep10_M_disposeERKSaIcE.part.0+36>
>    0x0000ffff3deff7e0 <+12>:    ldr     w2, [x0, #16]
>    0x0000ffff3deff7e4 <+16>:    sub     w3, w2, #0x1
>    0x0000ffff3deff7e8 <+20>:    str     w3, [x0, #16]
>    0x0000ffff3deff7ec <+24>:    cmp     w2, #0x0
>    0x0000ffff3deff7f0 <+28>:    b.le    0xffff3deff808 <_ZNSs4_Rep10_M_disposeERKSaIcE.part.0+52>
>    0x0000ffff3deff7f4 <+32>:    ret
>    0x0000ffff3deff7f8 <+36>:    add     x3, x0, #0x10
>    0x0000ffff3deff7fc <+40>:    mov     w2, #0xffffffff                 // #-1
> => 0x0000ffff3deff800 <+44>:    ldaddal w2, w2, [x3]
>    0x0000ffff3deff804 <+48>:    b       0xffff3deff7ec <_ZNSs4_Rep10_M_disposeERKSaIcE.part.0+24>
>    0x0000ffff3deff808 <+52>:    b       0xffff3d9484f0 <_ZNSs4_Rep10_M_destroyERKSaIcE@plt>
> End of assembler dump.
> ```
> 
> * Python version: 3.8.19
> * CPU model: FT-2000+/64
> 
> ```
> Features        : fp asimd evtstrm crc32 cpuid
> CPU implementer : 0x70
> CPU architecture: 8
> CPU variant     : 0x1
> CPU part        : 0x662
> CPU revision    : 2
> ```
> 
> Downgrade pytorch to 2.0.1 works. Is it a regression bug?

I can reproduce it on 2.4.0 as well

**Comment by christinaburge** [comment]
Hi! Thanks for bringing this to our attention, we will take a look and update you when we know more!

**Comment by afsara-ben** [comment]
using python==3.9.13 and torch==1.13.1 worked. otherwise nothing was working
