### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by Lmy0217** [pytorch/pytorch#97258]
### 🐛 Describe the bug

```python
from torch.utils.tensorboard import SummaryWriter
```

```
Traceback (most recent call last):
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-2775babaea59>", line 1, in <cell line: 1>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "C:\Users\myluo\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
```

### Versions

PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 企业版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.19.2
Libc version: N/A

Python version: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.0.221
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 516.94
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2904
DeviceID=CPU0
Family=198
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2904
Name=Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] adabelief-pytorch==0.2.1
[pip3] denoising-diffusion-pytorch==1.2.2
[pip3] efficientnet-pytorch==0.7.1
[pip3] ema-pytorch==0.2.1
[pip3] lion-pytorch==0.0.6
[pip3] mypy-extensions==0.4.3
[pip3] nfnets-pytorch==0.1.3
[pip3] numpy==1.24.2
[pip3] pytorch-lightning==1.9.0
[pip3] pytorch3d==0.7.1
[pip3] revtorch==0.2.4
[pip3] robust-loss-pytorch==0.0.2
[pip3] segmentation-models-pytorch==0.3.0
[pip3] torch==2.0.0+cu118
[pip3] torch-dct==0.1.5
[pip3] torchaudio==2.0.1+cu118
[pip3] torchio==0.18.86
[pip3] torchmetrics==0.11.1
[pip3] torchshow==0.5.0
[pip3] torchstat==0.0.7
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.15.1+cu118
[pip3] vit-pytorch==0.40.2
[conda] Could not collect

tensorboard                       2.12.0
tensorboard-data-server           0.7.0
tensorboard-plugin-wit            1.8.1
tensorflow                        2.11.0
tensorflow-estimator              2.11.0
tensorflow-intel                  2.11.0
tensorflow-io                     0.31.0
tensorflow-io-gcs-filesystem      0.31.0

**Comment by Lmy0217** [comment]
#https://github.com/tensorflow/tensorboard/pull/6135

**Comment by Lmy0217** [comment]
#https://github.com/tensorflow/tensorboard/pull/6135

**Comment by SilverDash** [comment]
This issue is still present. Why was this closed?

**Comment by Lmy0217** [comment]
@SilverDash I didn't have this issue after reinstalling tensorflow and tensorboard.

**Comment by SubeBila** [comment]
I'm having this problem too, but I don't know how to go about fixing it

**Comment by wzhgba** [comment]
If this happens in the case that you've pip installed and uninstalled the tensorflow before, try totally delete the tensorflow folder under the site_packages, otherwise the tensorflow is in the state that the package is uninstalled however the `import tensorflow` doesn't raise exception, so the tensorboard continues to use the tensorflow instead of tensorflow_stub, and raise the exception you mentioned.
