### ISSUE TITLE
release/2.0 branch gives OSError: libnvToolsExt: ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by ajindal1** [pytorch/pytorch#97266]
Current issue summary:
1. release/2.0 branch of builder repo with Pytorch release/2.0 branch gives the below error
2. main branch of builder repo with Pytorch release/2.0 branch is working fine

OS and other details:
Ubuntu 20.04
Pytorch 2.0
CUDA 11.7
CUDNN 8.5.0

While using the latest release/2.0 branch from builder and Pytorch, I am unable to build the Torch 2.0 image. The error first shows up while building Torch 2.0 from source with MPI but did not break the pipeline. However, after installing Pytorch and running "import torch" gives the error again. The error details are as follows.
Steps followed:
1. Using Builder release/2.0 branch, Pytorch release/2.0 branch
2. Build base docker image from builder repo using this command:
`GPU_ARCH_TYPE=cuda GPU_ARCH_VERSION=${DESIRED_CUDA:0:2}.${DESIRED_CUDA:2:1} manywheel/build_docker.sh`
3. Build Pytorch from source with MPI on the above base image, gives the below error at this step. The error comes silently and doesn't break the pipeline. There are 11 errors on "error while loading shared libraries" for libnvToolsExt-847d78f2.so.1, libgomp-a34b3233.so.1, libnvrtc-d833c4f3.so.11.2, libcudart-e409450e.so.11.0. Logs:
```
Successfully installed torch-2.0.0
++ for installed_lib in '"${installed_libraries[@]}"'
++ ldd /opt/python/cp38-cp38/lib/python3.8/site-packages/torch/_C_flatbuffer.cpython-38-x86_64-linux-gnu.so
/opt/python/cp38-cp38/lib/python3.8/site-packages/torch/_C_flatbuffer.cpython-38-x86_64-linux-gnu.so: error while loading shared libraries: libnvToolsExt-847d78f2.so.1: ELF load command address/offset not properly aligned
/opt/python/cp38-cp38/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so: error while loading shared libraries: libnvToolsExt-847d78f2.so.1: ELF load command address/offset not properly aligned
```
4. Install Pytorch which was build in the previous step.
5. Run `import torch` and it throws the below error.
```
++ python -c 'import torch;print(torch.__version__)'
Traceback (most recent call last):
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 168, in _load_global_deps
ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
File "/opt/conda/envs/ptca/lib/python3.8/ctypes/__init__.py", line 373, in _init
self._handle = _dlopen(self._name, mode)
OSError: libnvToolsExt-847d78f2.so.1: ELF load command address/offset not properly aligned
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 228, in <module>
_load_global_deps()
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 189, in _load_global_deps
_preload_cuda_deps(lib_folder, lib_name)
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['', '/opt/conda/envs/ptca/lib/python38.zip', '/opt/conda/envs/ptca/lib/python3.8', '/opt/conda/envs/ptca/lib/python3.8/lib-dynload', '/opt/conda/envs/ptca/lib/python3.8/site-packages']
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ajindal1** [comment]
I can try to share the two torch builds, one which is working fine (using main branch of builder) and the other which gives the above error (using release/2.0 branch of builder repo). Would that work for you?

**Comment by malfet** [comment]
@ajindal1 sure, though it would be better if those containers would include broken package as well (otherwise they shoudl be identical to containers already published to ghcr.io, wouldn't they?)

**Comment by ajindal1** [comment]
@malfet This was fixed by changing the github branch for patchelf as shown in this PR https://github.com/pytorch/builder/commit/18c5017d9eedd2e5e203608e9ad6c05a2324b3ac

Basically in file common/install_patchelf.sh replace this:
git clone https://github.com/NixOS/patchelf
with:
git clone -b 0.17.2 --single-branch https://github.com/NixOS/patchelf
