### ISSUE TITLE
Torch Dynamo allow_in_graph doesn't capture the custom function in graph

### ISSUE THREAD

**Issue by pallavides** [pytorch/pytorch#97295]
### 🐛 Describe the bug

I tried running the following example to try out the torch dynamo allow_in_graph option, expecting a graph that contains 'my_custom_function' instead of torch.add operator, however, the graph returned by `make_fx` resolves to torch operator as shown in (2)

1. Example run:

```python

def my_custom_function(x):
    return x + 1

def test_allow_in_graph():
    torch._dynamo.allow_in_graph(my_custom_function)
    @torch._dynamo.optimize("aot_eager")
    def fn(a):
        x = torch.add(a, 1)
        x = torch.add(x, 1)
        x = my_custom_function(x)
        x = torch.add(x, 1)
        x = torch.add(x, 1)
        return x

    fn(torch.randn(10))
```

2. Graph obtained from pdb session contains the torch operator instead of my_custom_function

```
-> return t
(Pdb) p t.print_readable()
class <lambda>(torch.nn.Module):
    def forward(self, arg0_1: f32[10]):

        add: f32[10] = torch.ops.aten.add.Tensor(arg0_1, 1);  arg0_1 = None
        
        add_1: f32[10] = torch.ops.aten.add.Tensor(add, 1);  add = None
        
        add_2: f32[10] = torch.ops.aten.add.Tensor(add_1, 1);  add_1 = None
        
        add_3: f32[10] = torch.ops.aten.add.Tensor(add_2, 1);  add_2 = None
        
        add_4: f32[10] = torch.ops.aten.add.Tensor(add_3, 1);  add_3 = None
        return (add_4,)
        
'class <lambda>(torch.nn.Module):\n    def forward(self, arg0_1: f32[10]):\n               
add: f32[10] = torch.ops.aten.add.Tensor(arg0_1, 1);  arg0_1 = None\n        \n                
add_1: f32[10] = torch.ops.aten.add.Tensor(add, 1);  add = None\n        \n               
add_2: f32[10] = torch.ops.aten.add.Tensor(add_1, 1);  add_1 = None\n        \n               
add_3: f32[10] = torch.ops.aten.add.Tensor(add_2, 1);  add_2 = None\n        \n                
add_4: f32[10] = torch.ops.aten.add.Tensor(add_3, 1);  add_3 = None\n        
return (add_4,)\n        '


### Versions

python collect_env.py
Collecting environment information...
PyTorch version: 2.1.0.dev20230310+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 13 2023, 10:26:41)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz
Stepping:                        7
CPU MHz:                         3800.000
CPU max MHz:                     4600.0000
CPU min MHz:                     1200.0000
BogoMIPS:                        7599.80
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        6 MiB
L3 cache:                        8.3 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0.dev20230310+cpu
[pip3] torchvision==0.15.0.dev20230310+cpu
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by SherlockNoMad** [comment]
this is a known issue for `dynamo.allow_in_graph`, which doesn't prevent make_fx from tracing into your custom op. 

@zou3519 is working on custom op authoring API that would allow you preserving `my_custom_function` throughout the PT2 stack, including dynamo, aotautograd and inductor. 

More discussion can be found here https://docs.google.com/document/d/1rVg1tRInZcwWknsrVQwCxHsQhjOfxTgEzr4g9tJRMGI/edit#heading=h.40qxbvm41rpv

**Comment by zou3519** [comment]
@pallavides could you elaborate a bit more on your use case please?
- Are you trying to plumb a custom operator through the entire PT2 stack?
- Does the custom operator only consist of PyTorch operators, or do you have some custom C++/CUDA/etc implementation for it?

**Comment by pallavides** [comment]
@zou3519 We have a custom operator with custom C++ implementation. We would like dynamo to capture the custom op without tracing (without decomposition) into its C++ impl, to be run in our own runtime. I believe this use-case is also being captured in [this Google doc](https://docs.google.com/document/d/1rVg1tRInZcwWknsrVQwCxHsQhjOfxTgEzr4g9tJRMGI/edit#heading=h.40qxbvm41rpv).

**Comment by alihassanijr** [comment]
Jumping in here because I'm having an issue with dynamo and I want to check first before opening a duplicate.

I'm trying to get the compiled graph to not break on my custom op (it's custom autograd functions that are binded to C++/CUDA functions we wrote), and when I wrap them in `allow_in_graph` and add the torch compile decorator to the forward function calling them, they end up failing because they get passed `FakeTensor` types.
If I get the C functions to ignore tensors whose data pointers are null, it will avoid the error, but of course it will ignore everything passed to the compiled model and just return empty tensors.

Is that somewhat similar to the issue you're having @pallavides ?

I guess my question is how would one go about allowing FakeTensor inputs to C++/CUDA kernels, because I couldn't really find any documentation on it, nor was I able to figure anything out by searching issues, PRs, and ATen's source code.

**Comment by zou3519** [comment]
@alihassanijr you are indeed running into the same problem, though as you noted your use case is different. The solution is that PyTorch needs to provide an API to teach the torch.compile stack to not peek into custom ops. This would also avoid the FakeTensor issue (FakeTensor should never directly be inputs to the C++/CUDA kernels, but something went wrong here).

> Do we have a timeline for this feature? Please let us know.

Given the amount of user requests, this feature is high-priority for us to ship by PyTorch 2.1 (which is the next PyTorch release - PyTorch releases are usually 3 months apart). As for when it'll be in the nightlies for testing, around 2-4 weeks is my estimate -- I'll keep you folks updated.

**Comment by zou3519** [comment]
Follow-up question, @alihassanijr - what are the reasons why you don't want the compiled graph to break on your custom op?

**Comment by pallavides** [comment]
@alihassanijr Yes, we are hitting the same issue where the custom op's C++ impl is invoked with FakeTensor types. As @zou3519 shared, we are looking for a solution where torch.compile does not trace into the C++ impl, but preserves the custom op node in the graph.

**Comment by alihassanijr** [comment]
@zou3519 
So in our case we're not seeing as noticeable of an improvement when compiling models and my first guess was that the breaks in the graph could be the reason, especially since `max-autotune` even undoes some of the improvement we do get.
And these are all in comparison to a model with identical architecture but one where the custom operations are swapped with one we know to be of higher latency, and as far as I know compiling shouldn't really affect the backend kernels that are dispatched (i.e. something that used to call an ATen kernel won't suddenly end up calling a cuBLAS routine just because it gets compiled.)

So anyway I figured getting the graph not to break on our op would be a step in the right direction in figuring out what's going on.

@pallavides Thanks for the clarification, we're in a similar boat I guess.

**Comment by zou3519** [comment]
And some more questions: do any of you anticipate creating custom operators that either mutate the input of the operation or returns a view of any of the inputs (like a slice of the input)?

**Comment by alihassanijr** [comment]
Just speaking for our case, I don't think so. Outputs are new tensors.

**Comment by pallavides** [comment]
@zou3519 yes, we can have custom ops that mutate the inputs (in-place ops)

**Comment by zou3519** [comment]
@pallavides for some context, we're trying to figure out if we should support in-place custom operations or if we should only support out-of-place custom operations.

If we assume that we support in-place custom operations, here's what will happen:
- Let's assume the program uses custom ops that mutate inputs
- the graph that you (the backend) will receive is supposed to be purely functional. That is, PyTorch will actually run a pass to remove in-place operations and replace them with out-of-place operations before passing it to you.
- So, for every in-place custom op, there should exist an out-of-place one (or we could autogenerate one).

Now, I'm not sure how useful the graph you receive will be to you, given that it will not have any in-place operations. This is why we're considering not supporting in-place custom operations: backends will end up receiving a functional graph.

**Comment by pallavides** [comment]
Thanks, @zou3519. Could you please share how parameter/gradient update will be supported?

**Comment by ashari4** [comment]
hi @zou3519, i'm running into the same issue when using DTensor on a custom op with a C++ implementation. DTensor invokes the op with `FakeTensors` and incorrectly goes to the C++ implementation. 

standard ops like `aten.detach` work as expected by using proxy_tensor's `__torch_dispatch__` to cook up a fake output:

```
inner_torch_dispatch (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:558)
__torch_dispatch__ (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:533)
wrapper (\home\ashari\pytorch\torch\utils\_stats.py:20)
__call__ (\home\ashari\pytorch\torch\_ops.py:398)
wrapped (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:674)
wrapped (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:484)
flatten_fn (\home\ashari\pytorch\torch\fx\_symbolic_trace.py:652)
trace (\home\ashari\pytorch\torch\fx\_symbolic_trace.py:778)
dispatch_trace (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:467)
wrapped (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:771)
get_isolated_graphmodule (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:820)
_propagate_tensor_meta (\home\ashari\pytorch\torch\distributed\_tensor\sharding_prop.py:164)
```

but for custom ops, proxy_tensor's `__torch_dispatch__` function is not called:

```
__call__ (\home\ashari\pytorch\torch\_ops.py:398)
wrapped (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:674)
wrapped (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:484)
flatten_fn (\home\ashari\pytorch\torch\fx\_symbolic_trace.py:652)
trace (\home\ashari\pytorch\torch\fx\_symbolic_trace.py:778)
dispatch_trace (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:467)
wrapped (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:771)
get_isolated_graphmodule (\home\ashari\pytorch\torch\fx\experimental\proxy_tensor.py:820)
_propagate_tensor_meta (\home\ashari\pytorch\torch\distributed\_tensor\sharding_prop.py:164)
```

**Comment by zou3519** [comment]
> but for custom ops, proxy_tensor's __torch_dispatch__ function is not called:

Well, it depends on how the custom op was registered. The new API we're working on will allow `__torch_dispatch__` to interpose by default. It's a bit difficult for me to give you suggestions right now without seeing the code -- are you using the TORCH_LIBRARY API and did you register an implementation to DispatchKey::Autograd?

**Comment by ashari4** [comment]
> are you using the TORCH_LIBRARY API?

yes - something like

```
TORCH_LIBRARY(custom_ops, m) {
  m.def("my_custom_op", TORCH_FN(custom_ops::my_custom_op_fn));
```

>  did you register an implementation to DispatchKey::Autograd

no I did not. do you have any pointers on how to that? I'm @Ashwin Hari on the pytorch slack if you want to further discuss there.

**Comment by apriyan9295** [comment]
Also facing similar issue, we have some custom function implementations which are not Fake Tensor friendly but allow_in_graph traces inside those. Looking for a way to avoid tracing into these custom functions.

**Comment by williamwen42** [comment]
Using `TORCH_LOGS="graph_code"` on a sample script based on the repro results in an FX graph containing the custom op. Closing task as completed.

**Comment by williamwen42** [comment]
The custom op is captured by dynamo, as revealed by `TORCH_LOGS="graph_code"` output, but it seems to be lost in AOTAutograd, shown by `TORCH_LOGS="aot_graphs"`.

**Comment by bdhirsh** [comment]
cc @zou3519 for the custom op q's

**Comment by parthmannan** [comment]
Also facing the same issue with custom operators. The graph breaks are hurting performance significantly and unfortunately `reduce-overhead` is running into errors so I am hoping to somehow register the custom operator so that TorchDynamo can understand them without tracing into it.
Has there been any solution to this that I may have missed?

**Comment by zou3519** [comment]
Use the torch.library APIs to register a custom op, instead of using allow_in_graph: https://pytorch.org/docs/main/library.html

**Comment by zou3519** [comment]
> Just curious if there is any example/test anywhere where it shows how to integrate a custom kernel which already has python bindings with torch.library impl and the FX graph generated? Would be a super helpful resource.

See https://docs.google.com/document/d/1ZuCVyMfibExwvtzhd9cfMWk5zXT3Dhy1b3kuvAIkBoU/edit

> And I can see there is some detailed reporting on how to make C++ kernels work well with PT2. Is the Python usage of torch.library APIs also considered sufficient to work with TorchDynamo forward and backward?

Yes.

**Comment by parthmannan** [comment]
Thanks @zou3519 I tried this and it does seem to prevent a graph break around custom ops but the execution seems to be weird. The custom operator never gets executed?

Here's a short reproducible script
```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.fx.experimental.proxy_tensor import make_fx

from apex.contrib.group_norm import GroupNorm

norm = GroupNorm(num_groups=32, num_channels=320, eps=1e-5, affine=True, act="silu")

def custom_op(x):
    return norm(x)

torch.library.define("mylibrary::my_norm_impl", "(Tensor x) -> Tensor")
torch.library.impl("mylibrary::my_norm_impl", "cuda", custom_op)

@torch.library.impl_abstract("mylibrary::my_norm_impl")
def custom_func_abstract(x):
    return torch.empty_like(x)

class Block(nn.Module):
    def __init__(
        self,
    ):
        super().__init__()

        self.in_layers = nn.Sequential(
            nn.Dropout(p=0.1),
        )
    
    def forward(self, x):
        out = F.gelu(x)
        out = torch.ops.mylibrary.my_norm_impl(out)
        out = self.in_layers(x)

        return out

model = Block()
model = model.to("cuda")
#print(make_fx(model, tracing_mode="symbolic")(torch.randn([1, 320, 128, 128], dtype=torch.float32, device='cuda', requires_grad=True)))

net = torch.compile(model, fullgraph=True)

num_batch = 20
profile_batch = 15

for i in range(num_batch):

    input_t = torch.randn([1, 320, 128, 128], dtype=torch.float32, device='cuda', requires_grad=True)
    input_t = input_t.to(memory_format=torch.channels_last)

    target_t = torch.randn([1, 320, 128, 128], dtype=torch.float32, device='cuda')
    target_t = target_t.to(memory_format=torch.channels_last)

    if i == profile_batch:
        torch.cuda.cudart().cudaProfilerStart()
    
    out = net(input_t)    
    out.backward(target_t)

    if i == profile_batch:
        torch.cuda.cudart().cudaProfilerStop()
```
  
The output of `make_fx` seems as expected with the full graph but when I execute it and profile it on the GPU, I only see `dropout` kernels executed which are after the GeLU and custom_op. I also verified with `TORCH_COMPILE_DEBUG=1` and only see dropout kernels in the `output_code.py`
Am I doing something wrong?
