### ISSUE TITLE
[ONNX] Handle multiple outputs of node

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#97301]
https://github.com/pytorch/pytorch/blob/af440c427bffddd7edc2db800a0c34ae8f1107d0/torch/onnx/_internal/fx/passes/fx_to_onnxscript.py#L351

Let's say we have an Op like topk, which has multiple outputs. Currently, we treat the whole output as an unit, and the graph trying to use each of the output element to different nodes is not supported.

cc @justinchuby @BowenBao

**Comment by titaiwangms** [comment]
fx graph handles multiple outputs with `getitem`, so each output would be recorded independently.

For example,

```python
class TopKModel(torch.nn.Module):
    def forward(self, x):
        values, _ = torch.topk(x, 3)
        return torch.sum(values)
```

```
sclass <lambda>(torch.nn.Module):
    def forward(self, arg0: f32[s0]):
        # File: /home/titaiwang/pytorch/test/onnx/test_fx_to_onnx.py:74, code: values, _ = torch.topk(x, 3)
        topk = torch.ops.aten.topk.default(arg0, 3);  arg0 = None
        getitem: f32[3] = topk[0]
        getitem_1: i64[3] = topk[1];  topk = None
        
        # File: /home/titaiwang/pytorch/test/onnx/test_fx_to_onnx.py:75, code: return torch.sum(values)
        sum_1: f32[] = torch.ops.aten.sum.default(getitem);  getitem = None
        return sum_1
```

**Comment by BowenBao** [comment]
Is there a covering test case already? If not, could you add the above

**Comment by titaiwangms** [comment]
Yes, I plan to include it in https://github.com/pytorch/pytorch/pull/96350 by extending test_multiple_outputs_op_with_evaluator in test_fx_to_onnx.py
