### ISSUE TITLE
Change worker process's attribute while set persistent_worker = True

### ISSUE THREAD

**Issue by ytwanghaoyu** [pytorch/pytorch#97326]
### 🚀 The feature, motivation and pitch

For example, in my dataset, I have an attribute called `epoch`, which means what epoch it is right now, I update this attribute while training.
But since I set `persistent_workers` to True, the worker will always be the same with an `epoch` equal to the initialization value.
But since the time cost of initializing a dataset is pretty long, therefore I want to keep `persistent_workers` to True. So how can I change worker's `epoch` attribute? 

cc @SsnL @VitalyFedyunin @ejguan @NivekT @dzhulgakov @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by rohan-varma** [comment]
Might be more of a dataloader question.

**Comment by NivekT** [comment]
You should be able to do this with `multiprocessing.Value`, pass that value into `worker_init_fn`, and save that to your worker's copy of the Dataset. For example:

```python
from torch.utils.data import DataLoader, get_worker_info, Dataset
from multiprocessing import Value
from functools import partial

class CustomDataset(Dataset):

    def __init__(self):
        self.data = [0, 1]
        self.epoch = None

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        print(f"{self.epoch.value = }")
        return self.data[index]


def init_fn(epoch_n, worker_id):
    info = get_worker_info()
    info.dataset.epoch = epoch_n


if __name__ == '__main__':
    epoch_n = Value('i', 0)
    dl = DataLoader(dataset=CustomDataset(), num_workers=2, persistent_workers=True, worker_init_fn=partial(init_fn, epoch_n))
    for epoch in range(2):
        print(f"{epoch = }")
        for _ in dl:
            pass
        epoch_n.value += 1
```

Feel free to re-open this if necessary.

**Comment by gurdeepmaurya** [comment]
Hi @NivekT 
Would it be wise to pass `epoch_n` as a parameter to `__init__()` function of `CustomDataset` class?, 
That way code won't have any dependency on `init_fn()`, `get_worker_info()`, and  `partial`.

**Comment by NivekT** [comment]
I think it is up to you, but you would have to re-create `CustomDataset` at every epoch.
