### ISSUE TITLE
torch.onnx.export crashes on ReduceMax operator with onnx opset 18

### ISSUE THREAD

**Issue by datinje** [pytorch/pytorch#97344]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

Provide a short description.
I can successfully export my model with torch.onnx.export  to onnx and run it with onnxruntime when selecting the onnx opset 17.

But when attempting to run torch.onnx.export on my model using onnx opset 18 , the export crashes in the ReduceMax operator.
 
here is the trace dump:

/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_opset9.py:5589: UserWarning: Exporting aten::index operator of advanced indexing in opset 18 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
warnings.warn(
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1636, in _export
_C._check_onnx_proto(proto)
RuntimeError: Unrecognized attribute: axes for operator ReduceMax

==> Context: Bad node spec for node. Name: /model/ReduceMax OpType: ReduceMax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/cad-engine/export_onnx.py", line 359, in
main()
File "/cad-engine/export_onnx.py", line 332, in main
onnx_model = export_tracing(torch_model, sample_inputs, args, logger)
File "/cad-engine/export_onnx.py", line 115, in export_tracing
torch.onnx.export(
File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 506, in export
_export(
File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1638, in _export
raise errors.CheckerError(e) from e
torch.onnx.errors.CheckerError: Unrecognized attribute: axes for operator ReduceMax

==> Context: Bad node spec for node. Name: /model/ReduceMax OpType: ReduceMax

## Code example

Please try to provide a minimal example to repro the bug.
Error messages and stack traces are also helpful.

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

python collect_env.py
Collecting environment information...
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.35

Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.3.18-150300.59.63-default-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 515.76
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   45 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Gold 6258R CPU @ 2.70GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       2
Stepping:                        7
BogoMIPS:                        5387.34
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Hypervisor vendor:               VMware
Virtualization type:             full
L1d cache:                       512 KiB (16 instances)
L1i cache:                       512 KiB (16 instances)
L2 cache:                        16 MiB (16 instances)
L3 cache:                        77 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

- PyTorch or Caffe2: PyTorch (there is no caffe module in my Pytorch install!)/ Use tracing , not torchscript 
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source): N/A
- OS: ununtu 22.04
- PyTorch version: 2.0.0
- Python version:3.10.6
- CUDA/cuDNN version:11.8
- GPU models and configuration: N/A for export 
- GCC version (if compiling from source):N/A
- CMake version:N/A
Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==2.0.0+cu118
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[pip3] detectron2 0.6
[conda] Could not collect

I have no idea where in the pytorch code (actually Detectron2 code) the exporter  fails  here is the export command)

   #this is inspired from [detectron2 v0.6] detectron2/tree/main/tools/deploy/export_model.py

    traceable_model = TracingAdapter(torch_model, inputs, inference)
    with PathManager.open(os.path.join(args.output, "faster_rcnn_fpn.onnx"), "wb") as f:
        torch.onnx.export(
              traceable_model, 
              (image,), 
              f, 
              do_constant_folding=True,
              export_params=True,
              input_names=["image"], # the model's input names
              output_names=["boxes", "labels", "scores", "image_dims"], # the model's output names
              dynamic_axes={
                "image"      : {1: "height", 2: "width"},
                "boxes"      : {0: "findings"}, # boxes is a tensor of shape [number of findings, 4] 
                "labels"     : {0: "findings"},
                "scores"     : {0: "findings"}
                },
              verbose=False, 
              opset_version=18)

**Comment by justinchuby** [comment]
Thanks for reporting this. It is expected because in opset18 a static attribute in the reduce ops was promoted to a dynamic one. The decomposition of many operators relies on the fact that reduce* take a static attribute. There are too many ops to fix for the new opsets. As we are evolving the new exporter, you can expect opset18 support in the coming few months

**Comment by datinje** [comment]
Thanks for the answer. I will use opset17 until then(it works). For my information, is there a recommanded way to export from pytorch to onnx? I am thinking between tracing and scripting. It seems that scripting us becoming the method of choice from the doc. Why is that so? Is it because tensor flow does not require inputs to trace to be exported. For me it is kind of tracing is having lots of constraints.

**Comment by justinchuby** [comment]
We tend to recommend tracing unless there are units in your model that has dynamic control flows (e.g. if/for loops that depend on the input date), which need to be scripted. There are edge cases with scripted models and they tend to be harder to convert in our experience.

**Comment by datinje** [comment]
thanks for the recommendation.

**Comment by datinje** [comment]
just reopening it : I can run the model with onnx::ReduceMax generated with torch.export.onnx and opset17 with onnxruntime and CPU or Cuda execution provider , but not with TensorRT execution provider

When generating the onnx model with orch.export.onnx  and verbose =True , I noticed :
- sometimes the onnx generated is :  %max_coordinate : Float(device=cpu) = **onnx::ReduceMax[keepdims=0]**  
=> no axes parameter in the call to the onnx::Reduce function
- sometimes the onnx generated is : %/model/ReduceMax_output_0 : Long(2, strides=[1], requires_grad=0, device=cpu) = **onnx::ReduceMax[axes=[0]**, keepdims=0, onnx_name="/model/ReduceMax"] 
=> this is wrong : onnx::ReduceMax should not take an axes parameter. This seems to work in inference with onnxrtime with CPU EP and CUDA EP , but TensorRT EP yells about it.

what I also noticed is that in the :
-proper case, code came from : python3.10/dist-packages/torchvision/ops/boxes.py:91:21
-the wrong case , code came from : python3.10/dist-packages/detectron2/structures/image_list.py:83:0

indeed I am converting a faster-rcnn-rpn model made with detectron2 over pytorch . 
I am using detectron2 latest (0.6) and pytorch latest (2.0)

I already fixed an onnx convertion issue in my detectron2 code that was specialized over detectron2, but here this seems to be official detectron2 code

any help appreciated , currently I cant do inference of my model with onnxrt and tensorrt EP

**Comment by datinje** [comment]
weirdly enough     onnx.checker.check_model(onnx_model, full_check=True) passes 
while 
  graph = onnx_model.graph
  onnx.checker.check_graph(graph) 
fails with 
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: axes for operator ReduceMax

**Comment by WildChlamydia** [comment]
Issue can be workarounded for a while with manual graph rewrite. Something like:
```python
        for node in graph.node:
            if "ReduceMax" in node.op_type:
                for index in range(len(node.attribute)):
                    if node.attribute[index].name == "axes":
                        del node.attribute[index]
                        axes_input = onnx.helper.make_tensor_value_info("axes", onnx.TensorProto.INT64, [1])
                        axes_value = numpy_helper.from_array(np.array([1]), "axes")
                        onnx_model.graph.input.extend([axes_input])
                        onnx_model.graph.initializer.extend([axes_value])
                        # Update the node inputs to include the new axes input
                        node.input.append("axes")
                        break
```

**Comment by thiagocrepaldi** [comment]
Closed as there is a workaround. However, latest pytorch main branch finally got support to opset >= 18 including reduction, so that could work there too

Nonetheless, you can also try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
