### ISSUE TITLE
Confused as to where a script is.

### ISSUE THREAD

**Issue by Shikamaru5** [pytorch/pytorch#97364]
According to pytorch/torch/_C/__init__.pyi.in there's supposed to be a torch/aten script but I can't find it, has this been phased out, because if it has is it in an older version of PyTorch? It's just without it, it completely stops one of the programs I downloaded from working, called Colossalai. It tries to call from aten.upsample_nearest2d_backward.vec and can't. According to ChatGPT the last version of PyTorch it saw, PyTorch 1.9.0 has aten in it, but both versions that you can download from the get started on the PyTorch website don't have it. Any recommendations would be great thanks.

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org

**Comment by ngimel** [comment]
`aten.upsample_nearest2d_backward.vec` is not a public API (for a list of public APIs please see documentation). Otherwise, please provide a minimum runnable code reproducing the failure.
