### ISSUE TITLE
inductor illegal memory access on indirect load on cpu

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#97365]
### 🐛 Describe the bug

The following program proves an illegal memory access whereas the version without `torch.compile` works.

``` 
import torch

@torch.compile
def indexit(A, b):
    return A[b - 1]

A = torch.rand(20)
b = torch.zeros(4)

print(indexit(A, b))
```

```
Traceback (most recent call last):
  File "/scratch/zdevito/pytorch/hi.py", line 11, in <module>
    print(indexit(A, b))
  File "/scratch/zdevito/pytorch/torch/_tensor.py", line 426, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/scratch/zdevito/pytorch/torch/_tensor_str.py", line 636, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/scratch/zdevito/pytorch/torch/_tensor_str.py", line 567, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/scratch/zdevito/pytorch/torch/_tensor_str.py", line 327, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/scratch/zdevito/pytorch/torch/_tensor_str.py", line 115, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Inductor kernel:
```
@triton.jit
def triton_(in_ptr0, in_ptr1, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xnumel = 4
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), xmask)
    tmp1 = 1
    tmp2 = tmp0 - tmp1
    tmp3 = tl.load(in_ptr1 + (tmp2), xmask)
    tl.store(out_ptr0 + (x0 + tl.zeros([XBLOCK], tl.int32)), tmp3, xmask)
```

Note that indexing by -1 is valid and means to read the _last_ element similar to python, but the code being generated here does not appear to have any handling for this case.

This bug has been running in the GPT2ForSequenceClassification benchmark for some time but is covered up by the fact that slight reads off the end of tensors do not always generate illegal memory faults.

### Versions

Collecting environment information...
PyTorch version: 2.0.0a0+git6a6776f
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.2
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1019-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.112
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         3000.042
BogoMIPS:                        6000.08
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] torch==2.1.0a0+git797e31d
[pip3] torchvision==0.15.0a0+120e7af
[pip3] triton==2.0.0a2
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] torch                     2.1.0a0+git797e31d           dev_0    <develop>
[conda] torchvision               0.15.0a0+120e7af           dev_0    <develop>
[conda] triton                    2.0.0a2                  pypi_0    pypi

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @ngimel @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @soumith @anijain2305 @desertfire

**Comment by Chillee** [comment]
I think for this one, we probably just need to add modulo logic around all of our indexing?

**Comment by ngimel** [comment]
Eager is inconsistent about when it errors on negative indices, and when it wraps them.

**Comment by abdulazizab2** [comment]
I tried to reproduce this bug in order to try and resolve it and it seems to not give illegal memory access (torch 2.1.0.dev) but it always give a zero value of any element with negative index

**Comment by lezcano** [comment]
Fixed in https://github.com/pytorch/pytorch/pull/98590

**Comment by ngimel** [comment]
Reopening, the snippet above works in eager (because eager wraps negative indices), and errors out with device assert in torch.compile.

**Comment by lezcano** [comment]
ooops. I'll submit a fix

**Comment by lezcano** [comment]
Keeping it open as this still breaks on CPU. I'll work on this issue soon.
