### ISSUE TITLE
`torch.device` gives odd results with AMD GPU: `for i in range(0, 300): print(torch.device(i))`; `cuda:-128`

### ISSUE THREAD

**Issue by SamuelMarks** [pytorch/pytorch#97390]
### 🐛 Describe the bug

I'm trying to get my GPU to work with PyTorch, I have a Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M]. I ran:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
```

```python
import torch
for i in range(0, 300): print(torch.device(i))
```

Gives:

```
cuda:0
cuda:1
cuda:2
cuda:3
cuda:4
cuda:5
cuda:6
cuda:7
cuda:8
cuda:9
cuda:10
cuda:11
cuda:12
cuda:13
cuda:14
cuda:15
cuda:16
cuda:17
cuda:18
cuda:19
cuda:20
cuda:21
cuda:22
cuda:23
cuda:24
cuda:25
cuda:26
cuda:27
cuda:28
cuda:29
cuda:30
cuda:31
cuda:32
cuda:33
cuda:34
cuda:35
cuda:36
cuda:37
cuda:38
cuda:39
cuda:40
cuda:41
cuda:42
cuda:43
cuda:44
cuda:45
cuda:46
cuda:47
cuda:48
cuda:49
cuda:50
cuda:51
cuda:52
cuda:53
cuda:54
cuda:55
cuda:56
cuda:57
cuda:58
cuda:59
cuda:60
cuda:61
cuda:62
cuda:63
cuda:64
cuda:65
cuda:66
cuda:67
cuda:68
cuda:69
cuda:70
cuda:71
cuda:72
cuda:73
cuda:74
cuda:75
cuda:76
cuda:77
cuda:78
cuda:79
cuda:80
cuda:81
cuda:82
cuda:83
cuda:84
cuda:85
cuda:86
cuda:87
cuda:88
cuda:89
cuda:90
cuda:91
cuda:92
cuda:93
cuda:94
cuda:95
cuda:96
cuda:97
cuda:98
cuda:99
cuda:100
cuda:101
cuda:102
cuda:103
cuda:104
cuda:105
cuda:106
cuda:107
cuda:108
cuda:109
cuda:110
cuda:111
cuda:112
cuda:113
cuda:114
cuda:115
cuda:116
cuda:117
cuda:118
cuda:119
cuda:120
cuda:121
cuda:122
cuda:123
cuda:124
cuda:125
cuda:126
cuda:127
cuda:-128
cuda:-127
cuda:-126
cuda:-125
cuda:-124
cuda:-123
cuda:-122
cuda:-121
cuda:-120
cuda:-119
cuda:-118
cuda:-117
cuda:-116
cuda:-115
cuda:-114
cuda:-113
cuda:-112
cuda:-111
cuda:-110
cuda:-109
cuda:-108
cuda:-107
cuda:-106
cuda:-105
cuda:-104
cuda:-103
cuda:-102
cuda:-101
cuda:-100
cuda:-99
cuda:-98
cuda:-97
cuda:-96
cuda:-95
cuda:-94
cuda:-93
cuda:-92
cuda:-91
cuda:-90
cuda:-89
cuda:-88
cuda:-87
cuda:-86
cuda:-85
cuda:-84
cuda:-83
cuda:-82
cuda:-81
cuda:-80
cuda:-79
cuda:-78
cuda:-77
cuda:-76
cuda:-75
cuda:-74
cuda:-73
cuda:-72
cuda:-71
cuda:-70
cuda:-69
cuda:-68
cuda:-67
cuda:-66
cuda:-65
cuda:-64
cuda:-63
cuda:-62
cuda:-61
cuda:-60
cuda:-59
cuda:-58
cuda:-57
cuda:-56
cuda:-55
cuda:-54
cuda:-53
cuda:-52
cuda:-51
cuda:-50
cuda:-49
cuda:-48
cuda:-47
cuda:-46
cuda:-45
cuda:-44
cuda:-43
cuda:-42
cuda:-41
cuda:-40
cuda:-39
cuda:-38
cuda:-37
cuda:-36
cuda:-35
cuda:-34
cuda:-33
cuda:-32
cuda:-31
cuda:-30
cuda:-29
cuda:-28
cuda:-27
cuda:-26
cuda:-25
cuda:-24
cuda:-23
cuda:-22
cuda:-21
cuda:-20
cuda:-19
cuda:-18
cuda:-17
cuda:-16
cuda:-15
cuda:-14
cuda:-13
cuda:-12
cuda:-11
cuda:-10
cuda:-9
cuda:-8
cuda:-7
cuda:-6
cuda:-5
cuda:-4
cuda:-3
cuda:-2
cuda
cuda:0
cuda:1
cuda:2
cuda:3
cuda:4
cuda:5
cuda:6
cuda:7
cuda:8
cuda:9
cuda:10
cuda:11
cuda:12
cuda:13
cuda:14
cuda:15
cuda:16
cuda:17
cuda:18
cuda:19
cuda:20
cuda:21
cuda:22
cuda:23
cuda:24
cuda:25
cuda:26
cuda:27
cuda:28
cuda:29
cuda:30
cuda:31
cuda:32
cuda:33
cuda:34
cuda:35
cuda:36
cuda:37
cuda:38
cuda:39
cuda:40
cuda:41
cuda:42
cuda:43
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.10 (x86_64)
GCC version: (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.36

Python version: 3.10.7 (main, Mar 10 2023, 10:47:39) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-6.2.8-060208-generic-x86_64-with-glibc2.36
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 9 6900HX with Radeon Graphics
CPU family:                      25
Model:                           68
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        1
Frequency boost:                 enabled
CPU(s) scaling MHz:              48%
CPU max MHz:                     4933.8862
CPU min MHz:                     1600.0000
BogoMIPS:                        6587.70
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] triton==2.0.0
[conda] Could not collect

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by jithunnair-amd** [comment]
@SamuelMarks This issue is not specific to AMD/ROCm. Even on a CUDA build of PyTorch, I see the same output:
```
# pip list | grep torch
torch               2.0.0+cu118
# python
Python 3.9.13 (main, May 23 2022, 22:01:06)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.device(0))
cuda:0
>>> print(torch.device(100))
cuda:100
>>> print(torch.device(200))
cuda:-56
>>> print(torch.device(300))
cuda:44
>>> print(torch.device(400))
cuda:-112
```

Anyway, I'm not sure what you intend to do with the code snippet in your question. Is there a use-case?

Side-note: Since your end goal is to get PyTorch working on your Navi22 card, unfortunately, Navi22 is not currently supported by ROCm stack. https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.4.2/page/Prerequisites.html#d5641e302

Closing this issue for  now.

**Comment by SamuelMarks** [comment]
@jithunnair-amd Actually it looks like it *might* work with latest master of ROCm https://github.com/RadeonOpenCompute/ROCm/pull/1991
