### ISSUE TITLE
CPU calculation and GPU calculation results are severely misaligned

### ISSUE THREAD

**Issue by 464hee** [pytorch/pytorch#97410]
### 🐛 Describe the bug

pytorch-1.13-cuda11.7
python3.9

### Versions

a = torch.randn(5, 3)
u, s, v = torch.svd(a)
print(u)
print('-----------------------------')
u, s, v = torch.svd(a.cuda())
print(u)

########################################################
tensor([[-0.0082, -0.5516, -0.3018],
        [ 0.3816, -0.3874, -0.0766],
        [-0.8132,  0.0514,  0.2636],
        [-0.3100,  0.1309, -0.9043],
        [-0.3112, -0.7252,  0.1260]])
-----------------------------
tensor([[ 0.0082, -0.5516, -0.3018],
        [-0.3816, -0.3874, -0.0766],
        [ 0.8132,  0.0514,  0.2636],
        [ 0.3100,  0.1309, -0.9043],
        [ 0.3112, -0.7252,  0.1260]], device='cuda:0')

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by 464hee** [comment]
@svenstaro @JackDanger @eklitzke @infil00p

**Comment by ZailiWang** [comment]
CPU path results are aligned with numpy.
```
import numpy as np
import torch

a = torch.randn(5, 3)
print("Input tensor:")
print(a)

#CPU
uc, sc, vc = torch.linalg.svd(a)
print("CPU SVD output U:")
print(uc)

#cuda
ug, sg, vg = torch.linalg.svd(a.cuda())
print("GPU SVD output U:")
print(ug)

un, sn, vn = np.linalg.svd(a)
# use full_matrices=False to get same results with torch.svd()
print("Numpy SVD output U:")
print(un)
```
Output:
```
Input tensor:
tensor([[ 0.9085, -0.9975,  0.5875],
        [ 0.9578, -0.3963, -1.4691],
        [-0.4015, -1.2633, -1.0136],
        [ 1.3823, -1.4734, -0.7894],
        [-0.1638,  1.4122, -1.6311]])
CPU SVD output U:
tensor([[-0.3476,  0.3681, -0.2978, -0.6603,  0.4680],
        [-0.4411, -0.4502, -0.2394, -0.3656, -0.6417],
        [-0.3693, -0.1636,  0.8825, -0.1902,  0.1478],
        [-0.7127, -0.0403, -0.2126,  0.6212,  0.2436],
        [ 0.2008, -0.7958, -0.1730, -0.0910,  0.5368]])
GPU SVD output U:
tensor([[-0.3476,  0.3681,  0.2978, -0.6603,  0.4680],
        [-0.4411, -0.4502,  0.2394, -0.3656, -0.6417],
        [-0.3693, -0.1636, -0.8825, -0.1902,  0.1478],
        [-0.7127, -0.0403,  0.2126,  0.6212,  0.2436],
        [ 0.2008, -0.7958,  0.1730, -0.0910,  0.5368]], device='cuda:0')
Numpy SVD output U:
[[-0.3476046   0.3681314  -0.29784355 -0.6602744   0.46795005]
 [-0.44110972 -0.4502427  -0.23938444 -0.36558813 -0.6416729 ]
 [-0.3692584  -0.16359241  0.88254064 -0.19020227  0.14775276]
 [-0.7126865  -0.04034515 -0.21256591  0.6212305   0.24359532]
 [ 0.20079716 -0.7958458  -0.17298    -0.09098791  0.5367579 ]]
```

**Comment by 464hee** [comment]
Can I specify a calculation method or parameter variable to achieve consistency between CPU and GPU calculation results

**Comment by ngimel** [comment]
Please see the docs, since results are not unique different results are expected https://pytorch.org/docs/master/generated/torch.linalg.svd.html?highlight=svd#torch.linalg.svd

**Comment by 464hee** [comment]
> Please see the docs, since results are not unique different results are expected https://pytorch.org/docs/master/generated/torch.linalg.svd.html?highlight=svd#torch.linalg.svd

Oh, I see
