### ISSUE TITLE
Support running torch.compile with meta tensors

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#97414]
### 🐛 Describe the bug

Steps to repro:

Patch in https://github.com/pytorch/pytorch/pull/97275/

```
PYTORCH_TEST_WITH_INDUCTOR=1 python test/test_torch.py -k test_upsample_nearest2d_meta
```

fails with

```
======================================================================
ERROR: test_upsample_nearest2d_meta (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/ezyang/c/pytorch/test/test_torch.py", line 7594, in test_upsample_nearest2d_meta
    def test_upsample_nearest2d_meta(self):
  File "/data/users/ezyang/c/pytorch/torch/_dynamo/eval_frame.py", line 235, in _fn
    return fn(*args, **kwargs)
  File "/data/users/ezyang/c/pytorch/torch/_functorch/aot_autograd.py", line 3067, in forward
    return compiled_fn(full_args)
  File "/data/users/ezyang/c/pytorch/torch/_functorch/aot_autograd.py", line 1187, in g
    return f(*args)
  File "/data/users/ezyang/c/pytorch/torch/_functorch/aot_autograd.py", line 2098, in runtime_wrapper
    all_outs = call_func_with_args(
  File "/data/users/ezyang/c/pytorch/torch/_functorch/aot_autograd.py", line 1212, in call_func_with_args
    out = normalize_as_list(f(args))
  File "/tmp/torchinductor_ezyang/cr/ccratlcqupckmlekrr3wiwo4xs77rfbn2x47ii6wi3722dmjv52e.py", line 61, in call
    streamNone = get_cuda_stream(None)
RuntimeError: invalid argument to getCurrentStream

----------------------------------------------------------------------
```

I don't see any user reports of this error so maybe low priority.

Generated code: https://gist.github.com/ezyang/199c5be44c0744f571620bfbc7d5993d

ATen graph looks valid, shouldn't be a bug in the DCE PR:

```
    def forward(self):
        # File: /data/users/ezyang/c/pytorch/test/test_torch.py:7602, code: x = torch.empty(4, 3, 8, 8, device='meta')
        empty: f32[4, 3, 8, 8] = torch.ops.aten.empty.memory_format([4, 3, 8, 8], device = device(type='meta'), pin_memory = False)
        
        # File: /data/users/ezyang/c/pytorch/test/test_torch.py:7604, code: torch._C._nn.upsample_nearest2d(x, (16, 16), out=out)
        upsample_nearest2d: f32[4, 3, 16, 16] = torch.ops.aten.upsample_nearest2d.default(empty, [16, 16])
        return (empty, upsample_nearest2d)
```

### Versions

master

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel @Xia-Weiwen @desertfire

**Comment by jgong5** [comment]
I saw this error message from CI...

**Comment by ezyang** [comment]
yeah, I reverted the DCE pr which caused it

**Comment by ngimel** [comment]
Why are we getting graphs with `meta` device?

**Comment by ngimel** [comment]
What is expected behavior for this? My hot take is inductor should not get graphs with meta tensors, I can make it explicitly error on meta tensors, but that won't make the test pass. 
If the expected behavior is fallback, the problem is that we cannot always trust that `val` is present in meta (cc @eellison) to reliably fallback. Otherwise if we do want to "support" meta @eellison can you modify your cpu fallback PR to also always fallback for "meta" device?

**Comment by eellison** [comment]
Yea i can add the fallback here
