### ISSUE TITLE
There is a performance drop because we have not yet implemented the batching rule for aten::matmul

### ISSUE THREAD

**Issue by ipostr08** [pytorch/pytorch#97425]
### 🚀 The feature, motivation and pitch

Just doing what the warning told me to do:

```
torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing <graph break in splitLinearFast>
/home/tech/.local/lib/python3.10/site-packages/torch/_functorch/vmap.py:619: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::matmul. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
```

This is using vmap and torch.compile using a workaround to posted by @Chillee https://github.com/pytorch/pytorch/issues/94674

Prioritizing it would be nice!

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by Chillee** [comment]
Do you have a repro? This is a little bit unexpected I think.

**Comment by zou3519** [comment]
I've seen something similar before in the context of using allow_in_graph with functorch. For some reason operators that have batching rules that are decompositions never get them triggered underneath allow_in_graph and torch.compile.

**Comment by ipostr08** [comment]
> Do you have a repro? This is a little bit unexpected I think.

Running under WSL 2 (Windows 10).
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Dec 7 2022, 01:12:00) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

```
import torch
from torch._dynamo import allow_in_graph
from functools import wraps

def traceable(f):
    f = allow_in_graph(f)

    @wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)

    return wrapper


def splitLinearFast(x):
   batch_mul = torch.vmap(torch.matmul)
   ret = batch_mul(torch.stack([x]), torch.stack([x]))
   return ret

def splitLinearFastCompiled(x):
   return torch.compile(traceable(splitLinearFast))(x)

x = torch.randn(1, 1)
print("ok = ", splitLinearFast(x))
print("warn = ", splitLinearFastCompiled(x))

```

ok =  tensor([[[1.0199]]])
warn =  tensor([[[1.0199]]])
/home/tech/.local/lib/python3.10/site-packages/torch/_functorch/vmap.py:619: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::matmul. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at .[./aten/src/ATen/functorch/BatchedFallback.cpp:82](https://vscode-remote+wsl-002bubuntu-002d20-002e04.vscode-resource.vscode-cdn.net/mnt/r/midi_new/aten/src/ATen/functorch/BatchedFallback.cpp:82).)
  batched_outputs = func(*batched_inputs, **kwargs)
/home/lech/.local/lib/python3.10/site-packages/torch/_inductor/overrides.py:38: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::matmul. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at .[./aten/src/ATen/functorch/BatchedFallback.cpp:82](https://vscode-remote+wsl-002bubuntu-002d20-002e04.vscode-resource.vscode-cdn.net/mnt/r/midi_new/aten/src/ATen/functorch/BatchedFallback.cpp:82).)
  return func(*args, **kwargs)
/home/tech/.local/lib/python3.10/site-packages/torch/_inductor/overrides.py:38: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::matmul. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at .[./aten/src/ATen/functorch/BatchedFallback.cpp:82](https://vscode-remote+wsl-002bubuntu-002d20-002e04.vscode-resource.vscode-cdn.net/mnt/r/midi_new/aten/src/ATen/functorch/BatchedFallback.cpp:82).)
  return func(*args, **kwargs)
/home/tech/.local/lib/python3.10/site-packages/torch/_inductor/overrides.py:38: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::matmul. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at .[./aten/src/ATen/functorch/BatchedFallback.cpp:82](https://vscode-remote+wsl-002bubuntu-002d20-002e04.vscode-resource.vscode-cdn.net/mnt/r/midi_new/aten/src/ATen/functorch/BatchedFallback.cpp:82).)
  return func(*args, **kwargs)

**Comment by kshitij12345** [comment]
@zou3519 I will try and investigate more about the issue as this seems to be related to `functorch and PT2.0 integration`.

**Comment by kshitij12345** [comment]
This seems to be happening due to the interaction of `FakeTensorMode's __torch_dispatch__`.

**Comment by zou3519** [comment]
Um, does python dispatcher handle functorch's DynamicLayerFrontMode and DynamicLayerBackMode keys? (My guess is no, because I'm not sure how it would do that)
