### ISSUE TITLE
Developer warnings are not disabled in official release 

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#97449]
## Repro

Seen here https://discuss.pytorch.org/t/what-can-cause-warning-devicecopy-in-input-program/175566/8

```python
import torch

def fun(x):
    x = x.to("cuda:0")
    
fun_compiled = torch.compile(fun)

x = torch.randn(1)
out = fun_compiled(x)
```

@ptrblck produced the simple repro

## Logs

`[2023-03-23 17:53:06,641] torch._inductor.utils: [WARNING] DeviceCopy in input program`

## pip list

```
(torchofficial) ubuntu@ip-172-31-38-220:~/test$ pip list
Package           Version
----------------- -----------
cmake             3.25.0
filelock          3.9.0
Jinja2            3.1.2
lit               15.0.7
MarkupSafe        2.1.2
mpmath            1.2.1
networkx          3.0
pip               23.0.1
setuptools        67.6.0
sympy             1.11.1
torch             2.0.0+cu118
triton            2.0.0
typing_extensions 4.4.0
wheel             0.40.0
```

## Solution

Bug seems to be here 

`developer_warnings = is_fbcode() or "+" in torch.__version__` https://github.com/pytorch/pytorch/blob/master/torch/_inductor/config.py#L105 where the + is matching on the cu118

cc @ezyang @soumith @wconstab @ngimel @bdhirsh

**Comment by bhack** [comment]
What is the action item of this warning?
