### ISSUE TITLE
Cannot install GPU version of pytorch 2.0

### ISSUE THREAD

**Issue by Michael-H777** [pytorch/pytorch#97457]
### 🐛 Describe the bug

i tried multiple times to install latest pytorch 2.0 using conda instruction listed on the website, not luck. thought was environment issue, and created an empty conda env to test this. (conda version is 23.1.0)

     conda create --name testing python 

got python version 3.11.0

then run this code 

    conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia

got this error: 

    Collecting package metadata (current_repodata.json): ...working... done
    Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): ...working... done
    Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: ...working... 
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed
    UnsatisfiableError: The following specifications were found
    to be incompatible with the existing python installation in your environment:
    
    Specifications:
    
      - torchaudio -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
      - torchvision -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']
    
    Your python: python=3.11
    
    If python is on the left-most side of the chain, that's the version you've asked for.
    When python appears to the right, that indicates that the thing on the left is somehow
    not available for the python version you are constrained to. Note that conda will not
    change your python version to a different minor version unless you explicitly specify
    that.
    
    The following specifications were found to be incompatible with each other:
    
    Output in format: Requested package -> Available versions
    
    Package pytorch conflicts for:
    torchaudio -> pytorch[version='1.10.0|1.10.1|1.10.2|1.11.0|1.12.0|1.12.1|1.13.0|1.13.1|2.0.0|1.9.1|1.9.0|1.8.1|1.8.0|1.7.1|1.7.0|1.6.0|1.5.1']
    torchvision -> pytorch[version='1.1.*|1.10.0|1.10.1|1.10.2|1.11.0|1.12.0|1.12.1|1.13.0|1.13.1|2.0.0|1.9.1|1.9.0|1.8.1|1.8.0|1.7.1|1.7.0|1.6.0|1.5.1|1.7.1.*|1.3.1.*|1.2.0.*|>=0.4|>=0.3']
    
    Package pytorch-cuda conflicts for:
    torchaudio -> pytorch-cuda[version='11.6.*|11.7.*|11.8.*']
    torchvision -> pytorch==2.0.0 -> pytorch-cuda[version='>=11.6,<11.7|>=11.7,<11.8|>=11.8,<11.9']
    torchvision -> pytorch-cuda[version='11.6.*|11.7.*|11.8.*']
    torchaudio -> pytorch==2.0.0 -> pytorch-cuda[version='>=11.6,<11.7|>=11.7,<11.8|>=11.8,<11.9']
    
    Package ca-certificates conflicts for:
    pytorch -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
    torchvision -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
    python=3.11 -> openssl[version='>=1.1.1t,<1.1.2a'] -> ca-certificates
    
    Package typing conflicts for:
    pytorch -> typing_extensions -> typing[version='>=3.7.4']
    pytorch -> typing
    torchvision -> pytorch -> typing[version='>=3.7.4']The following specifications were found to be incompatible with your system:
    
      - feature:/linux-64::__glibc==2.35=0
      - feature:|@/linux-64::__glibc==2.35=0
      - python=3.11 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
      - torchaudio -> cudatoolkit[version='>=11.6,<11.7'] -> __glibc[version='>=2.17,<3.0.a0']
      - torchvision -> __glibc[version='>=2.17,<3.0.a0']
      - torchvision -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
    
    Your installed version is: 2.35

checked glibc by running `ldd --version`, and got: 

    ldd (Ubuntu GLIBC 2.35-0ubuntu3.1) 2.35
    Copyright (C) 2022 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    Written by Roland McGrath and Ulrich Drepper.

i have two gpu installed in the server. running `nvidia-smi` reports (first one is 3090, second one is 3080ti): 

    Thu Mar 23 15:08:18 2023       
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |                               |                      |               MIG M. |
    |===============================+======================+======================|
    |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
    |  0%   38C    P8    28W / 400W |      1MiB / 24576MiB |      0%      Default |
    |                               |                      |                  N/A |
    +-------------------------------+----------------------+----------------------+
    |   1  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
    |  0%   40C    P8    19W / 350W |      1MiB / 12288MiB |      0%      Default |
    |                               |                      |                  N/A |
    +-------------------------------+----------------------+----------------------+
                                                                                   
    +-----------------------------------------------------------------------------+
    | Processes:                                                                  |
    |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
    |        ID   ID                                                   Usage      |
    |=============================================================================|
    |  No running processes found                                                 |
    +-----------------------------------------------------------------------------+

both gpu are detectable when using pytorch 1.13.1 (i have multiple envs installed, switched to an old one, and checked via `torch.cuda.is_available()` and `torch.cuda.device_count()`)

please help. 
let me know what else you need to fix this. 

Sincerely, 
Michael 

### Versions

    Collecting environment information...
    PyTorch version: N/A
    Is debug build: N/A
    CUDA used to build PyTorch: N/A
    ROCM used to build PyTorch: N/A
    
    OS: Ubuntu 22.04.2 LTS (x86_64)
    GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    Clang version: Could not collect
    CMake version: Could not collect
    Libc version: glibc-2.35
    
    Python version: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0] (64-bit runtime)
    Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
    Is CUDA available: N/A
    CUDA runtime version: Could not collect
    CUDA_MODULE_LOADING set to: N/A
    GPU models and configuration: 
    GPU 0: NVIDIA GeForce RTX 3090
    GPU 1: NVIDIA GeForce RTX 3080 Ti
    
    Nvidia driver version: 510.108.03
    cuDNN version: Could not collect
    HIP runtime version: N/A
    MIOpen runtime version: N/A
    Is XNNPACK available: N/A
    
    CPU:
    Architecture:                    x86_64
    CPU op-mode(s):                  32-bit, 64-bit
    Address sizes:                   39 bits physical, 48 bits virtual
    Byte Order:                      Little Endian
    CPU(s):                          20
    On-line CPU(s) list:             0-19
    Vendor ID:                       GenuineIntel
    Model name:                      Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    CPU family:                      6
    Model:                           165
    Thread(s) per core:              2
    Core(s) per socket:              10
    Socket(s):                       1
    Stepping:                        5
    CPU max MHz:                     5200.0000
    CPU min MHz:                     800.0000
    BogoMIPS:                        7200.00
    Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
    Virtualization:                  VT-x
    L1d cache:                       320 KiB (10 instances)
    L1i cache:                       320 KiB (10 instances)
    L2 cache:                        2.5 MiB (10 instances)
    L3 cache:                        20 MiB (1 instance)
    NUMA node(s):                    1
    NUMA node0 CPU(s):               0-19
    Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
    Vulnerability L1tf:              Not affected
    Vulnerability Mds:               Not affected
    Vulnerability Meltdown:          Not affected
    Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
    Vulnerability Retbleed:          Mitigation; Enhanced IBRS
    Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
    Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
    Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
    Vulnerability Srbds:             Mitigation; Microcode
    Vulnerability Tsx async abort:   Not affected
    
    Versions of relevant libraries:
    [pip3] No relevant packages
    [conda] No relevant packages

**Comment by Michael-H777** [comment]
just to clarify, all the info from the version part of the ticket is run under the `testing` env, which should be empty. 

i run the same script for the 1.13.1 pytorch env, and got this: 

    Collecting environment information...
    PyTorch version: 1.13.1+cu117
    Is debug build: False
    CUDA used to build PyTorch: 11.7
    ROCM used to build PyTorch: N/A
    
    OS: Ubuntu 22.04.2 LTS (x86_64)
    GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
    Clang version: Could not collect
    CMake version: Could not collect
    Libc version: glibc-2.35
    
    Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
    Python platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
    Is CUDA available: True
    CUDA runtime version: Could not collect
    CUDA_MODULE_LOADING set to: LAZY
    GPU models and configuration: 
    GPU 0: NVIDIA GeForce RTX 3090
    GPU 1: NVIDIA GeForce RTX 3080 Ti
    
    Nvidia driver version: 510.108.03
    cuDNN version: Could not collect
    HIP runtime version: N/A
    MIOpen runtime version: N/A
    Is XNNPACK available: True
    
    CPU:
    Architecture:                    x86_64
    CPU op-mode(s):                  32-bit, 64-bit
    Address sizes:                   39 bits physical, 48 bits virtual
    Byte Order:                      Little Endian
    CPU(s):                          20
    On-line CPU(s) list:             0-19
    Vendor ID:                       GenuineIntel
    Model name:                      Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    CPU family:                      6
    Model:                           165
    Thread(s) per core:              2
    Core(s) per socket:              10
    Socket(s):                       1
    Stepping:                        5
    CPU max MHz:                     5200.0000
    CPU min MHz:                     800.0000
    BogoMIPS:                        7200.00
    Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
    Virtualization:                  VT-x
    L1d cache:                       320 KiB (10 instances)
    L1i cache:                       320 KiB (10 instances)
    L2 cache:                        2.5 MiB (10 instances)
    L3 cache:                        20 MiB (1 instance)
    NUMA node(s):                    1
    NUMA node0 CPU(s):               0-19
    Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
    Vulnerability L1tf:              Not affected
    Vulnerability Mds:               Not affected
    Vulnerability Meltdown:          Not affected
    Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
    Vulnerability Retbleed:          Mitigation; Enhanced IBRS
    Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
    Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
    Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
    Vulnerability Srbds:             Mitigation; Microcode
    Vulnerability Tsx async abort:   Not affected
    
    Versions of relevant libraries:
    [pip3] numpy==1.24.0
    [pip3] torch==1.13.1
    [pip3] torchvision==0.14.1
    [conda] numpy                     1.24.0                   pypi_0    pypi
    [conda] torch                     1.13.1                   pypi_0    pypi
    [conda] torchvision               0.14.1                   pypi_0    pypi

**Comment by ngimel** [comment]
As stated in the release blog, python 3.11 is not supported on conda https://pytorch.org/blog/pytorch-2.0-release/#python-311-support-on-anaconda-platform, downgrade your python version to 3.10 or use pip wheel

**Comment by Michael-H777** [comment]
oh i see, my apology. closing the ticket now,
