### ISSUE TITLE
Batching rule for aten::complex

### ISSUE THREAD

**Issue by yhl48** [pytorch/pytorch#97479]
### 🚀 The feature, motivation and pitch

```
UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::complex. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
```

Is there a plan to implement this? I am happy to help implement it but could probably use some guides :)

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by kshitij12345** [comment]
Batch rule for complex was added recently https://github.com/pytorch/pytorch/pull/96032. It should be available in nightly and will be part of next release.

Also, if you are interested helping implementing batching rules, please have a look at https://github.com/pytorch/functorch/issues/1088 (only a few remain)

Thank you!
