### ISSUE TITLE
Unable to run `torch.ops.aten.convolution_backward_overrideable` on CPU

### ISSUE THREAD

**Issue by ramiro050** [pytorch/pytorch#97481]
### 🐛 Describe the bug

The following code

```python
import torch

x = torch.rand(1, 1, 1, 1)
torch.ops.aten.convolution_backward_overrideable(x, x, x,
                                                 stride=[1, 1],
                                                 padding=[0, 0],
                                                 dilation=[1, 1],
                                                 transposed=False,
                                                 output_padding=[0, 0],
                                                 groups=1,
                                                 output_mask=[True, True, True])
```

results in the error

```
NotImplementedError: convolution_backward_overrideable: You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function
```

Since the the tensor `x` is on the CPU backend, I would've expected this op to work.

### Versions

PyTorch version: 2.1.0.dev20230317+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux rodete (x86_64)
GCC version: (Debian 12.2.0-10) 12.2.0
Clang version: 14.0.6
CMake version: version 3.22.5
Libc version: glibc-2.36

Python version: 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-5.19.11-1rodete1-amd64-x86_64-with-glibc2.36
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:                      6
Model:                           85
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
Stepping:                        3
BogoMIPS:                        4000.37
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB (48 instances)
L1i cache:                       1.5 MiB (48 instances)
L2 cache:                        48 MiB (48 instances)
L3 cache:                        77 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX flush not necessary, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] functorch==0.3.0a0+0feda8a
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] pytorch-transformers==1.2.0
[pip3] torch==2.1.0.dev20230317+cpu
[pip3] torch-struct==0.5
[pip3] torchdynamo==1.13.0.dev0
[pip3] torchfile==0.1.0
[pip3] torchmetrics==0.9.2
[pip3] torchrec-nightly==2022.4.26
[pip3] torchvision==0.16.0.dev20230317+cpu
[pip3] torchx-nightly==2022.7.1
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by ngimel** [comment]
Why are you attempting to call this op on cpu?

**Comment by ramiro050** [comment]
> Why are you attempting to call this op on cpu?

This is for testing purposes in [Torch-MLIR](https://github.com/llvm/torch-mlir). Because we currently import models into MLIR using TorchScript, we need to handle all the dispatch ops we encounter, and this is one of the ops users have encountered when lowering certain models.

In our testing framework, using `torch.ops...` has allowed us to test directly the op we are getting in the TorchScript graph except for this op.

**Comment by jbschlosser** [comment]
> Is this op not meant to work on CPU?

This op is a relic of times past that will eventually be removed. Does calling the higher-level `torch.ops.aten.convolution_backward()` not work for you? That one will dispatch to the one you're trying to call under certain circumstances.

**Comment by ngimel** [comment]
@jbschlosser I guess the question is can this op appear in traces that Torch-MLIR acquires. Under what circumstances would we dispatch to `convolution_backward_overrideable`?

**Comment by jbschlosser** [comment]
> Under what circumstances would we dispatch to convolution_backward_overrideable?

Only if no other conv backend applies. Vulkan / XLA / ipex are the cases I'm aware of that use this now (ideally they should switch to implementing `convolution_backward` directly).

For CPU / CUDA / cuDNN / MPS, it's not expected that `convolution_backwards_overrideable` will be called, and in fact there is no implementation of it unless it has been inserted via e.g. a `TORCH_LIBRARY_IMPL` call.

**Comment by ngimel** [comment]
If that's the case, should we rename the function to `_convolution_....` to indicate that it's non-public and that backends acquiring traces by standard means shouldn't expect to see it. 
cc @SherlockNoMad, what's the status of core aten APIs that we can point backends to to list the ops they should expect to encounter in traces and thus need to support?

**Comment by jbschlosser** [comment]
From internal discussion: for backends that don't have a dispatch key, it won't be possible for them to just override `convolution` / `convolution_backward` directly. We may have to just live with the overrideable overloads. It's also a huge pain to rename, so we should stick with defining the aten op support surface very clearly.

**Comment by SherlockNoMad** [comment]
> If that's the case, should we rename the function to `_convolution_....` to indicate that it's non-public and that backends acquiring traces by standard means shouldn't expect to see it. cc @SherlockNoMad, what's the status of core aten APIs that we can point backends to to list the ops they should expect to encounter in traces and thus need to support?

There you go :). https://pytorch.org/docs/stable/ir.html

These is the set of core aten operators backend should expect to see, after running decomposition with core_aten_decompositions(). 

Backend is expected to work with aten.convolution_backward.

**Comment by ramiro050** [comment]
Thanks for all the responses. Since the conclusion is that `convolution_backward_overrideable` is never expected to appear in standard traces, I will go ahead and close this issue.
