### ISSUE TITLE
PyTorch Build From Source Error: ppc64le + gcc 7.3.1 + cuda 11.8 + python 3.9

### ISSUE THREAD

**Issue by kvndhrty** [pytorch/pytorch#97497]
### 🐛 Describe the bug

About 50% of the way through the `setup.py ` script I get a fatal error that kills the build process. I've got everything installed via `conda` as per the Build From Source instructions, and have had no problems building 1.12 on the same system. 

I attached the output of `python setup.py install` since I'm not sure how to parse it. I've tried different versions of cmake, as well as cleaning and reinitializing the submodules. There are a number of other compilers on the system, but since I've had luck with gcc 7.3.1 on PyTorch 1.12 in the past (and this didn't seem to be a gcc error) I haven't messed around with the compiler much. I have gotten the same error with gcc 8.3.1 as well. I have nsight-compute/2022.3.0 loaded but no cuDNN for now. 

[install.log](https://github.com/pytorch/pytorch/files/11058270/install.log)
[env.txt](https://github.com/pytorch/pytorch/files/11058284/env.txt)

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.9 (Maipo) (ppc64le)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: 12.0.1
CMake version: version 3.25.0
Libc version: glibc-2.17

Python version: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:27)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-4.14.0-115.35.1.3chaos.ch6a.ppc64le-ppc64le-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB

Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                176
On-line CPU(s) list:   0-175
Thread(s) per core:    4
Core(s) per socket:    22
Socket(s):             2
NUMA node(s):          6
Model:                 2.1 (pvr 004e 1201)
Model name:            POWER9, altivec supported
CPU max MHz:           3800.0000
CPU min MHz:           2300.0000
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              10240K
NUMA node0 CPU(s):     0-87
NUMA node8 CPU(s):     88-175
NUMA node252 CPU(s):   
NUMA node253 CPU(s):   
NUMA node254 CPU(s):   
NUMA node255 CPU(s):

Versions of relevant libraries:
[pip3] numpy==1.23.4
[conda] numpy                     1.23.4           py39hea7066a_1    conda-forge

cc @malfet @seemethere

**Comment by cdeepali** [comment]
I have a patch that works for me for CPU with PyTorch 2.0. Would you like to try it? @kvndhrty

**Comment by cdeepali** [comment]
@kvndhrty pls check with the patch 
[fallback_cpu_kernel_VSX.patch](https://github.com/pytorch/pytorch/files/11172185/fallback_cpu_kernel_VSX.patch)

I will raise a PR for this later.

**Comment by ax3l** [comment]
Hi,

I am right now compiling pyTorch 2.0.1 on ppc64le with CUDA (Summit at OLCF w/ Tesla V100-SXM2-16GB GPUs).
@kvndhrty's patch reversions fixed the compile errors I saw for the CPU vectorization code in ATen.

For reference, I was building with
```bash
USE_CUDA=1 BLAS=OpenBLAS MAX_JOBS=8 ATEN_AVX512_256=OFF python3 setup.py develop
```
with CUDA 11.7, GCC 9.3.0, Python 3.8.10.

Will try @cdeepali's PR #98511 next and comment there :)
