### ISSUE TITLE
torch.nn.functional.scaled_dot_product_attention bug when using mem_efficient = True and providing a mask

### ISSUE THREAD

**Issue by LarsHill** [pytorch/pytorch#97514]
### 🐛 Describe the bug

I'm currently experimenting with the new scaled dot product attention in pytorch 2.0.
Since I am using an Nvidia V100 32GB GPU, flash attention is currently not supported. However, `xformers` memory efficient attention kernel is. Running the below code works without any problem and the memory footprint is drastically reduced compared to the normal `math` mode:

```python
import torch

torch.manual_seed(42)
device = "cuda:0"
dtype = torch.float32

B = 4
H = 12
N = 2**12
D = 1024

q = torch.rand(B, H, N, D, dtype=dtype, device=device)
k = torch.rand(B, H, N, D, dtype=dtype, device=device)
v = torch.rand(B, H, N, D, dtype=dtype, device=device)

with torch.backends.cuda.sdp_kernel(enable_flash=False, enable_math=False, enable_mem_efficient=True):
    out = torch.nn.functional.scaled_dot_product_attention(q, k, v)
```

However, when providing an additional attention matrix the following error occurs:
```RuntimeError: No available kernel.  Aborting execution.```

Code:
```python
import torch

torch.manual_seed(42)
device = "cuda:0"
dtype = torch.float32

B = 4
H = 12
N = 2**12
D = 1024

q = torch.rand(B, H, N, D, dtype=dtype, device=device)
k = torch.rand(B, H, N, D, dtype=dtype, device=device)
v = torch.rand(B, H, N, D, dtype=dtype, device=device)

m = torch.ones((N, N), dtype=torch.bool, device=device).triu(N - N + 1)
m = m.float().masked_fill(m, float("-inf"))

with torch.backends.cuda.sdp_kernel(enable_flash=False, enable_math=False, enable_mem_efficient=True):
    out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=m)
```

I then tested the original implementation of `xformers`, and there providing a mask works like a charm and the same speed up plus memory saving is achieved.
```python
import torch
import xformers.ops as xops

torch.manual_seed(42)
device = "cuda:0"
dtype = torch.float32

B = 4
H = 12
N = 2**12
D = 1024

q = torch.rand(B, H, N, D, dtype=dtype, device=device)
k = torch.rand(B, H, N, D, dtype=dtype, device=device)
v = torch.rand(B, H, N, D, dtype=dtype, device=device)

m = torch.ones((N, N), dtype=torch.bool, device=device).triu(N - N + 1)
m = m.float().masked_fill(m, float("-inf"))

# xformers attention expects shape B, N, H, D instead of B, H, N, D
q = q.transpose(1, 2)
k = k.transpose(1, 2)
v = v.transpose(1, 2)

out = xops.memory_efficient_attention(q, k, v, attn_bias=m)
```

I would expect that the pytorch implementation of the memory efficient `xformers` implementation works exactly the same and supports attention masks as well.

### Versions

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.27

Python version: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.45.1.el7.x86_64-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB

Nvidia driver version: 470.86
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              80
On-line CPU(s) list: 0-79
Thread(s) per core:  2
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
Stepping:            4
CPU MHz:             2399.853
CPU max MHz:         3700.0000
CPU min MHz:         1000.0000
BogoMIPS:            4800.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            28160K
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d

Versions of relevant libraries:
[pip3] memory-efficient-attention-pytorch==0.1.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] triton==2.0.0
[conda] memory-efficient-attention-pytorch 0.1.2                    pypi_0    pypi
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @ngimel

**Comment by dagitses** [comment]
@drisspg

**Comment by drisspg** [comment]
The verison of xformers code that is currenlty within PyTorch Core is not the same as the on that is Xformer. There were updates made to allow for an arbitrary attention mask in the fused kernesl that have not been upstreamed yet. I am planning on upstreaming the newer verison by 2.1 release:

See this comment: https://github.com/pytorch/pytorch/issues/96099#issuecomment-1458609375
