### ISSUE TITLE
Failed to run "build_android.sh"  i686-linux-android-g++: error: unrecognized command line option '-fno-limit-debug-info'

### ISSUE THREAD

**Issue by avrum** [pytorch/pytorch#9752]
## Issue description

I want to compile all the android native libraries (.a & .so) to x86 processor.
While running the "build_android.sh" script i'm getting failed error regarding the make file.

## Code example

I tried running both for x86 and arm64, failed to do so in both scenarios:

 ./scripts/build_android.sh -DANDROID_ABI=arm64-v8a -DANDROID_TOOLCHAIN=clang
./scripts/build_android.sh -DANDROID_ABI=x86 -DANDROID_TOOLCHAIN=clang

## System Info

Mac 10.12.6
Android NDK - R14
cmake version 3.12.0
clang Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0

## The error while running the build with x86 is :

Android: Selected GCC toolchain 'x86-4.9'
-- Check for working CXX compiler: /Users/myuser/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-g++
-- Check for working CXX compiler: /Users/myuser/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-g++ -- broken
CMake Error at /usr/local/Cellar/cmake/3.12.0/share/cmake/Modules/CMakeTestCXXCompiler.cmake:45 (message):
  The C++ compiler

    "/Users/myuser/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/myuser/Workspaces/pytorch_source_code/pytorch/build_android/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_6ad89/fast"
    /Users/myuser/Downloads/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/cmTC_6ad89.dir/build.make CMakeFiles/cmTC_6ad89.dir/build
    Building CXX object CMakeFiles/cmTC_6ad89.dir/testCXXCompiler.cxx.o
    /Users/myuser/Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-g++ --target=i686-none-linux-android --sysroot=/Users/myuser/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-x86   -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-x86/usr/include -isystem /Users/myuser/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-x86/usr/include/i686-linux-android  -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -frtti -fexceptions   -O0 -fno-limit-debug-info  -fPIE   -o CMakeFiles/cmTC_6ad89.dir/testCXXCompiler.cxx.o -c /Users/myuser/Workspaces/pytorch_source_code/pytorch/build_android/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    i686-linux-android-g++: error: unrecognized command line option '-fno-limit-debug-info'
    make[1]: *** [CMakeFiles/cmTC_6ad89.dir/testCXXCompiler.cxx.o] Error 1
    make: *** [cmTC_6ad89/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/myuser/Workspaces/pytorch_source_code/pytorch/build_android/CMakeFiles/CMakeOutput.log".
See also "/Users/myuser/Workspaces/pytorch_source_code/pytorch/build_android/CMakeFiles/CMakeError.log".

**Comment by jerryzh168** [comment]
@Maratyszcza  do you know?

**Comment by Maratyszcza** [comment]
@avrum NDK 14 is very old, and for some reason your build doesn't use clang (`i686-linux-android-g++` is gcc). I tried the same command with NDK r15c, the oldest we support, and it builds just fine.

**Comment by avrum** [comment]
@Maratyszcza 

Thanks for the quick replay, I just tried it again on my Ubuntu machine (14) with:
NDK: r17b
cmake: 3.12
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu

I managed to run successfully the "build_android.sh" without any parameters
but when run:

./build_android.sh -DANDROID_ABI=x86 -DANDROID_TOOLCHAIN=clang

## I'm now getting this error:
(*Attaching the first line of summary from the build output too)

-- 
-- ******** Summary ********
-- General:
--   CMake version         : 3.12.0
--   CMake command         : /home/aviram/Downloads/cmake-3.12.0-Linux-x86_64/bin/cmake
--   Git version           : v0.1.11-9444-gba634c1
--   System                : Android
--   C++ compiler          : /home/aviram/Downloads/android-ndk-r17b/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++
--   C++ compiler version  : 4.9.0
--   BLAS                  : Eigen
--   CXX flags             : -isystem /home/aviram/Downloads/android-ndk-r17b/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions  -Wno-deprecated -fvisibility-inlines-hidden -DONNX_NAMESPACE=onnx_c2 -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -s
--   Build type            : Release

...
...

--   USE_NNPACK            : ON
--   USE_OBSERVERS         : OFF
--   USE_OPENCL            : OFF
--   USE_OPENCV            : OFF
--   USE_OPENMP            : OFF
--   USE_PROF              : OFF
--   USE_REDIS             : OFF
--   USE_ROCKSDB           : OFF
--   USE_ZMQ               : OFF
--   Public Dependencies  : Threads::Threads
--   Private Dependencies : nnpack;cpuinfo;log;onnxifi_loader;dl
-- Configuring done
WARNING: Target "libprotoc" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
WARNING: Target "protoc" has EXCLUDE_FROM_ALL set and will not be built by default but an install rule has been provided for it.  CMake does not define behavior for this case.
-- Generating done
-- Build files have been written to: /home/aviram/Workspaces/pytourch/pytorch/build_android
[  0%] Building CXX object third_party/protobuf/cmake/CMakeFiles/js_embed.dir/__/src/google/protobuf/compiler/js/embed.cc.o
[  0%] Linking CXX executable ../../../bin/js_embed
i686-linux-android-g++: error: unrecognized command line option '-nostdlib++'
i686-linux-android-g++: error: unrecognized command line option '-Qunused-arguments'
third_party/protobuf/cmake/CMakeFiles/js_embed.dir/build.make:83: recipe for target 'bin/js_embed' failed
make[2]: *** [bin/js_embed] Error 1
CMakeFiles/Makefile2:128: recipe for target 'third_party/protobuf/cmake/CMakeFiles/js_embed.dir/all' failed
make[1]: *** [third_party/protobuf/cmake/CMakeFiles/js_embed.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2



Not sure what am I missing...
Did you tries the command with the x86 argument?

**Comment by avrum** [comment]
Ammm doesn't look like it...
I just print all env variable and it doesn't there:

**root@aviram-VirtualBox:~/Workspaces/pytourch/pytorch/scripts# printenv**
LC_PAPER=he_IL.UTF-8
LC_ADDRESS=he_IL.UTF-8
LC_MONETARY=he_IL.UTF-8
SHELL=/bin/bash
TERM=xterm-256color
LC_NUMERIC=he_IL.UTF-8
OLDPWD=/home/aviram/Workspaces/pytourch/pytorch
USER=root
LC_TELEPHONE=he_IL.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SUDO_USER=aviram
SUDO_UID=1000
USERNAME=root
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
LC_IDENTIFICATION=he_IL.UTF-8
PWD=/home/aviram/Workspaces/pytourch/pytorch/scripts
LANG=en_US.UTF-8
LC_MEASUREMENT=he_IL.UTF-8
SHLVL=1
SUDO_COMMAND=/bin/bash
HOME=/home/aviram
LANGUAGE=en_US
LOGNAME=root
LESSOPEN=| /usr/bin/lesspipe %s
ANDROID_NDK=/home/aviram/Downloads/android-ndk-r17b
SUDO_GID=1000
DISPLAY=:0
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=he_IL.UTF-8
XAUTHORITY=/home/aviram/.Xauthority
LC_NAME=he_IL.UTF-8
_=/usr/bin/printenv
root@aviram-VirtualBox:~/Workspaces/pytourch/pytorch/scripts#

**Comment by Maratyszcza** [comment]
@avrum Have you deleted your previous `build_*` directories? CMake may not properly re-generate all files when you re-configure for a new platform in the same directory

**Comment by avrum** [comment]
No....
I'll give it a try

**Comment by soumith** [comment]
Fixed on master via @ljk53 's PRs
