### ISSUE TITLE
Batching rule for aten::max_pool1d and aten::huber_loss

### ISSUE THREAD

**Issue by yhl48** [pytorch/pytorch#97558]
### 🚀 The feature, motivation and pitch

Related to https://github.com/pytorch/functorch/issues/1088.

```
UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::max_pool1d. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
```

```
UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::huber_loss. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at ../aten/src/ATen/functorch/BatchedFallback.cpp:82.)
```

Would like to help implement these if they have not already been implemented, would appreciate it if some pointers are given!

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by zou3519** [comment]
@yhl48 some pointers are over at https://github.com/pytorch/pytorch/wiki/vmap-Basics if you're interested in giving these a try

**Comment by yhl48** [comment]
Also for `aten::smooth_l1_loss`

**Comment by qqaatw** [comment]
I took `huber_loss` here: #99235 :)
