### ISSUE TITLE
torch.bincount errors on empty input

### ISSUE THREAD

**Issue by davidbau** [pytorch/pytorch#9756]
## Issue description

`torch.bincount` gives an error when given an empty tensor, rather than just returning zero counts like `numpy.bincount`.  Trips up edge cases when counting filtered data.

## Code example

```
>>> import torch, numpy
>>> numpy.bincount([1]), numpy.bincount([]), numpy.bincount([], minlength=10)
(array([0, 1]), array([], dtype=int64), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

>>> torch.bincount(torch.LongTensor([]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: bincount only supports 1-d non-negative integral inputs.

>>> torch.bincount(torch.LongTensor([]), minlength=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: bincount only supports 1-d non-negative integral inputs.
```

**Comment by zou3519** [comment]
@davidbau Numpy doesn't document this behavior [docs here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html) for the `numpy.bincount([])` case.

The docs suggest the output should be
> out : ndarray of ints
The result of binning the input array. The length of out is equal to np.amax(x)+1.

but if `x` is `[]`, the size of the output isn't well defined. Do you think `torch.bincount(torch.LongTensor([])) = torch.tensor([])` makes sense?

**Comment by davidbau** [comment]
Producing an empty vector from an empty count makes sense to me, although I find that in practice, I'm always using minlength, in which case the right output shape is unambiguous.
