### ISSUE TITLE
If we have any detail information of each CI in PyTorch's Github?

### ISSUE THREAD

**Issue by sanbuphy** [pytorch/pytorch#97587]
### 🚀 The feature, motivation and pitch

Hello, I have been studying the actions (CI) of various open source projects on Github recently.
I noticed that PyTorch has a well-established CI, so I would like to further understand its composition and structure. Do you have any relevant materials that I can study and refer to? Thank you.

**Comment by msaroufim** [comment]
There's no substitute to just writing your own CI scripts, I'd browse through the shortest examples here and see what sticks https://github.com/pytorch/pytorch/tree/master/.github/workflows

**Comment by sanbuphy** [comment]
> There's no substitute to just writing your own CI scripts, I'd browse through the shortest examples here and see what sticks https://github.com/pytorch/pytorch/tree/master/.github/workflows
> 
> And overall I believe this is a good question for https://discuss.pytorch.org/

Thank you very much.
