### ISSUE TITLE
MultiHeadAttention remove the constraint that the input dimension equals the output dimension

### ISSUE THREAD

**Issue by pi-tau** [pytorch/pytorch#97607]
### 🚀 The feature, motivation and pitch

The `MultiHeadAttention` accepts a single parameter `embed_dim` which dictates both the number of input features as well as the number of output features. I propose to split this parameter into two separate parameters, namely: `in_features` and `out_features`.

My concern is that all `q_proj_weight`, `k_proj_weight` and `v_proj_weight` project to the same space as the input space `embed_dim` ([here](https://github.com/pytorch/pytorch/blob/512ec181ec1bac5ced0d7199da08aca2f244732a/torch/nn/modules/activation.py#L962)). I propose instead to have these matrices project to the space `out_features`:
```python3
        if not self._qkv_same_embed_dim:
            self.q_proj_weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
            self.k_proj_weight = Parameter(torch.empty((out_features, self.kdim), **factory_kwargs))
            self.v_proj_weight = Parameter(torch.empty((out_features, self.vdim), **factory_kwargs))
            self.register_parameter('in_proj_weight', None)
        else:
            self.in_proj_weight = Parameter(torch.empty((3 * out_features, in_features), **factory_kwargs))
            self.register_parameter('q_proj_weight', None)
            self.register_parameter('k_proj_weight', None)
            self.register_parameter('v_proj_weight', None)
```

In addition the `out_proj_weight` matrix should now be of shape `(out_features, out_features)` ([here](https://github.com/pytorch/pytorch/blob/512ec181ec1bac5ced0d7199da08aca2f244732a/torch/nn/modules/activation.py#L977)).

I believe this change would allow the `MultiHeadAttention` layer to be applied to a more broad variety of tasks, and not only to the specific use case of the Transofmer encoder and decoder, where the number of input features match then number output of output features.
And even in the transformer model, I don't see a reason why this would be the case? In the [paper](https://arxiv.org/pdf/1706.03762) the authors even go as far as to propose the $W_V$ projection matrix to project to a different space $d_v$ and the `out_proj_weight` to be of shape `(d_v, out_features)`.

### Alternatives

As a workaround I add an additional embedding matrix prior to the `MultiHeadAttention` layer.
Let's say I have the following input on which I want to apply the multi-head attention:
```python3
x = torch.randn(shape=(B, T, D))
```

Then if I simply apply the layer I get the following:
```python3
mha = torch.nn.MultiHeadAttention(embed_dim=D, n_heads=nh)
att, att_w = mha(x, x, x)
print(att.shape) # (B, T, D)
```

But if my input features are to few (e.g. `D=16, 32`) or if they are too many (e.g. `D=10000`), then I want the multi-head attention layer to work with a different embedding space. Thus, I need to apply an embedding matrix prior to that:
```python3
embed = torch.nn.Linear(D, out_features, bias=False)
att, att_w = mha(embed(x), embed(x), embed(x))
print(att.shape) # (B, T, out_features)
```

In my opinion it doesn't make much sense to be learning both the embedding matrix $W_E$ and the query, key, value matrices $W_Q$, $W_K$, $W_V$ separately. Instead, with the proposed change the four matrices will be collapsed to three matrices  $W_{Qe} = W_E W_Q$, $W_{Ke} = W_E W_K$, $W_{Ve} = W_E W_V$. Note also that in the first scenario the number of trainable parameters is: `D * out_features + out_features * out_features * 3`, while in the second scenario we have `D * out_features * 3`.
To put this into perspective if I start out with `D=32` and want to project into `out_features=512`, then in the first case I have `802816` parameters, while in the second case `49152`, i.e. 16 times less.

### Additional context

Please note that I am not working with text problems and in my case these embeddings do not refer to word-vector embeddings.
I simply have some input of shape `(batch_size, time_steps, in_features)` and I want to apply multi-head attention on it, but I want to progressively expand and then contract the size of the feature space with every MHA layer. Currently I have to apply an additional embedding matrix prior to every multi-head attention layer.

I'd be happy to add the feature myself if approved.

**Comment by drisspg** [comment]
We are not currently looking to extend the API surface of torch.nn.MultiheadAttention. You could take a look at [scaled_dot_product_attention](https://docs-preview.pytorch.org/94008/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention) which can be used to create more customizable Attention setup. For Instance here is an implementation of CausalAttention using SDPA: https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html#causal-self-attention
