### ISSUE TITLE
torch.onnx.export support sparse tensor format

### ISSUE THREAD

**Issue by erwangccc** [pytorch/pytorch#97652]
### 🚀 The feature, motivation and pitch

I have a simply model just like a conv2d with a sparse weight in my case. The forward like following

```
# self.weight is sparsed with coo format
x = torch.sparse.mm(self.weight, x)
```

When i want to convert to onnx model. This error occur.

```
    tuple(x.clone(memory_format=torch.preserve_format) for x in args)
RuntimeError: unsupported memory format option Preserve
```

I think maybe torch.onnx.export module doesn't support SparseTensor?

**Comment by justinchuby** [comment]
torch.onnx doesn't support SparseTensor as far as I know. cc @BowenBao

**Comment by thiagocrepaldi** [comment]
sparse tensors are not supported by `torch.onnx.export`

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
