### ISSUE TITLE
ATen: Possibly ill-formed C++ code on List.h:484?

### ISSUE THREAD

**Issue by GregTheMadMonk** [pytorch/pytorch#97689]
### 🐛 Describe the bug

Hello!

I've recently switched to C++20 and was trying to verify that the code (C++ and CUDA) compiles with the new standard. I was greeted with `nvcc` errors such as:
```
/usr/include/c++/12.2.1/bits/stl_vector.h(1124): error: expression must be a pointer to a complete object type
   return *(this->_M_impl._M_start + __n);
            ^
          detected during instantiation of "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 484 of /usr/include/ATen/core/List.h
```

This error did not occur when I was using C++17. Digging into it, I've discovered that the reason for it is the fact that some functions in standard library were marked `constexpr` for C++20 standard which causes both `clang` and `nvcc` to throw an error in the case of a function making use of a template of incomplete type, while `g++` allows such behavior on `constexpr` funtions (see [this Gobolt example](https://godbolt.org/z/W7196Gb3T). It compiles on all three compilers without `-DCONSTEXPR`, but doesn't on `clang` and `nvcc` with `-DCONSTEXPR`. Errors read:
* `clang`: `error: arithmetic on a pointer to an incomplete type 'S'`
* `nvcc`: `error: expression must be a pointer to a complete object type`

The code that fails is:
https://github.com/pytorch/pytorch/blob/fcc312e9454eecdc388d673833dd69c5b9864faa/aten/src/ATen/core/List.h#L483-L485

We can see that it's basically the same issue here: it tries to call `constexpr operator[]` on a vector of incomplete type and fails.

[This StackOverflow answer](https://stackoverflow.com/questions/41713945/clang-template-incomplete-type) refers to the standard to pronounce code like this ill-formed. ([The standard](https://isocpp.org/files/papers/N4860.pdf), page 387 (399th page of PDF).

### Versions

Collecting environment information...
PyTorch version: 2.0.0rc5
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.2.1 20230201
Clang version: 15.0.7
CMake version: version 3.26.1
Libc version: glibc-2.37

Python version: 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] (64-bit runtime)
Python platform: Linux-6.2.8-zen1-1-zen-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GT 1030
Nvidia driver version: 530.41.03
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.8.0
/usr/lib/libcudnn_adv_infer.so.8.8.0
/usr/lib/libcudnn_adv_train.so.8.8.0
/usr/lib/libcudnn_cnn_infer.so.8.8.0
/usr/lib/libcudnn_cnn_train.so.8.8.0
/usr/lib/libcudnn_ops_infer.so.8.8.0
/usr/lib/libcudnn_ops_train.so.8.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 5 3600 6-Core Processor
CPU family:                      23
Model:                           113
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        7199.85
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                  AMD-V
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        3 MiB (6 instances)
L3 cache:                        32 MiB (2 instances)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] oldest-supported-numpy==2022.11.19
[pip3] torch==2.0.0rc5
[conda] Could not collect

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @jbschlosser

**Comment by GregTheMadMonk** [comment]
Forgot to put the output of other errors arising from ATen:
```
/usr/include/c++/12.2.1/bits/stl_vector.h(367): error: expression must be a pointer to a complete object type
          _M_impl._M_end_of_storage - _M_impl._M_start);
          ^
          detected during:
            instantiation of "std::_Vector_base<_Tp, _Alloc>::~_Vector_base() noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h
            instantiation of class "std::vector<_Tp, _Alloc> [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h

/usr/include/c++/12.2.1/type_traits(910): error: static assertion failed with "template argument must be a complete class or an unbounded array"
        static_assert(std::__is_complete_or_unbounded(__type_identity<_Tp>{}),
        ^
          detected during:
            instantiation of class "std::is_destructible<_Tp> [with _Tp=c10::IValue]" at line 188 of /usr/include/c++/12.2.1/bits/stl_construct.h
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator=c10::IValue *]" at line 850 of /usr/include/c++/12.2.1/bits/alloc_traits.h
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_Tp> &) [with _ForwardIterator=c10::IValue *, _Tp=c10::IValue]" at line 731 of /usr/include/c++/12.2.1/bits/stl_vector.h
            instantiation of "std::vector<_Tp, _Alloc>::~vector() noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h

/usr/include/c++/12.2.1/bits/stl_construct.h(162): error: expression must be a pointer to a complete object type
     for (; __first != __last; ++__first)
                                 ^
          detected during:
            instantiation of "void std::_Destroy_aux<<unnamed>>::__destroy(_ForwardIterator, _ForwardIterator) [with <unnamed>=false, _ForwardIterator=c10::IValue *]" at line 193
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator=c10::IValue *]" at line 850 of /usr/include/c++/12.2.1/bits/alloc_traits.h
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_Tp> &) [with _ForwardIterator=c10::IValue *, _Tp=c10::IValue]" at line 731 of /usr/include/c++/12.2.1/bits/stl_vector.h
            instantiation of "std::vector<_Tp, _Alloc>::~vector() noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h

/usr/include/c++/12.2.1/bits/stl_construct.h(88): error: pointer to incomplete class type "c10::IValue" is not allowed
   __location->~_Tp();
   ^
          detected during:
            instantiation of "void std::destroy_at(_Tp *) [with _Tp=c10::IValue]" at line 149
            instantiation of "void std::_Destroy(_Tp *) [with _Tp=c10::IValue]" at line 163
            instantiation of "void std::_Destroy_aux<<unnamed>>::__destroy(_ForwardIterator, _ForwardIterator) [with <unnamed>=false, _ForwardIterator=c10::IValue *]" at line 193
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator=c10::IValue *]" at line 850 of /usr/include/c++/12.2.1/bits/alloc_traits.h
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_Tp> &) [with _ForwardIterator=c10::IValue *, _Tp=c10::IValue]" at line 731 of /usr/include/c++/12.2.1/bits/stl_vector.h
            instantiation of "std::vector<_Tp, _Alloc>::~vector() noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h

/usr/include/c++/12.2.1/bits/stl_construct.h(195): error: an incomplete class type is not allowed
        std::_Destroy_aux<__has_trivial_destructor(_Value_type)>::
                          ^
          detected during:
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator=c10::IValue *]" at line 850 of /usr/include/c++/12.2.1/bits/alloc_traits.h
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_Tp> &) [with _ForwardIterator=c10::IValue *, _Tp=c10::IValue]" at line 731 of /usr/include/c++/12.2.1/bits/stl_vector.h
            instantiation of "std::vector<_Tp, _Alloc>::~vector() noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h

/usr/include/c++/12.2.1/bits/stl_construct.h(162): error: expression must be a pointer to a complete object type
     for (; __first != __last; ++__first)
                                 ^
          detected during:
            instantiation of "void std::_Destroy_aux<<unnamed>>::__destroy(_ForwardIterator, _ForwardIterator) [with <unnamed>=<error-constant>, _ForwardIterator=c10::IValue *]" at line 196
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator) [with _ForwardIterator=c10::IValue *]" at line 850 of /usr/include/c++/12.2.1/bits/alloc_traits.h
            instantiation of "void std::_Destroy(_ForwardIterator, _ForwardIterator, std::allocator<_Tp> &) [with _ForwardIterator=c10::IValue *, _Tp=c10::IValue]" at line 731 of /usr/include/c++/12.2.1/bits/stl_vector.h
            instantiation of "std::vector<_Tp, _Alloc>::~vector() noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 29 of /usr/include/ATen/core/List.h

/usr/include/c++/12.2.1/bits/stl_vector.h(1124): error: expression must be a pointer to a complete object type
   return *(this->_M_impl._M_start + __n);
            ^
          detected during instantiation of "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) noexcept [with _Tp=c10::IValue, _Alloc=std::allocator<c10::IValue>]" at line 484 of /usr/include/ATen/core/List.h
```

**Comment by GregTheMadMonk** [comment]
https://github.com/pytorch/pytorch/blob/64077ce511f9e77b439ec3d8b7e19b2ba92dd258/aten/src/ATen/core/List.h#L483-L485
is realtively easy to fix: instead of taking an address to the first element of vector, which asks compiler to perform pointer arithmetic, `std::vector::data()` could be used.

https://github.com/pytorch/pytorch/blob/64077ce511f9e77b439ec3d8b7e19b2ba92dd258/aten/src/ATen/core/List.h#L27-L29
is harder. The definition for this constructor should be placed after `IValue` was complete, either by putting it at the end of `ivalue.h` or by including `ivalue.h` in `List.h`.
In `ivalue.h` does not include `List.h` and I didn't see any code in `ivalue.h` that requires `List` to be complete, so, unless there's a more complicated include cycle, it should be safe to (even without modifying line 485) fix the issue. I will try it myself when I have the chance if no one does it by that point

**Comment by ezyang** [comment]
Yes, go ahead and send us the PRs, thanks for the nice sleuthing.

**Comment by GregTheMadMonk** [comment]
Closed by https://github.com/pytorch/pytorch/pull/93978
