### ISSUE TITLE
AOTAutograd intermediate_base logic is leaving perf on the table

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#97691]
@jansel pointed out that AOTAutograd's intermediate_base logic is not great for inductor performance: it can prevent inductor from fusing things, and potentially force inductor to generate extra copies. In particular, it's preventing the ability to swap out an attention pattern for flash attention

As a quick recap, "intermediate base" handling was original created to handle graph that exhibit the below structure. If you have an `autograd.Function` that creates an intermediate and returns a view of the intermediate, autograd will yell at you if you attempt to mutate the graph intermediate.
```
class MyFunc(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        intermediate = x + 1
        return intermediate.view(-1)

    @staticmethod
    def backward(ctx, *args):
        raise RuntimeError("UNUSED")


a = torch.ones(2, requires_grad=True)
out = MyFunc.apply(a)
out.mul_(2)
```

To deal with this, AOTAutograd works pretty hard to detect "intermediate bases", and force the compiler to return intermediate bases as outputs. It then uses those intermediate to manually regenerate the output views, in an epilogue that runs after the compiled graph, outside of the custom `autograd.Function`.

As you can see in the above case though, we don't really care about the view relationship. In fact, in the above case it would be fine if we completely hid the fact that the output was a view.

The case where this **does** matter though is if you have two outputs that alias each other. This case is probably much rarer, but will require us to carefully preserve aliasing relationships:
```
def f(x):
    intermediate = x + 1
    return intermediate, intermediate.view(-1)
```

**Proposal**

There are several ways to deal with this. To unblock, I'll propose what I think is the simplest proposal: keep doing intermediate_base logic in the rarer case of having outputs that alias each other, but attempt to hide the aliasing relationships from autograd otherwise.

(1) AOTAutograd should detect for cases when two outputs of the program are aliased to each other.

(2) If there are any, then we'll continue doing the intermediate-base logic we have today

(3) If there are not any, then:

(a) we will **not** generate any intermediate_base logic.
(b) For any output that is an alias of an intermediate, we will add an `out = aten._unsafe_view(out.shape)` to the graph, hiding the alias relationship from autograd.

cc @ezyang @soumith @msaroufim @wconstab @ngimel

**Comment by ezyang** [comment]
This sounds good to me.

**Comment by ngimel** [comment]
Do you still need the replay logic for outputs that are views of inputs? 
Doing _unsafe_view on intermediates sounds good to me, that's precisely what `_unsafe_view` is for, to return view of an intermediate without recording view relationships because no one else can possible have access to an intermediate.

**Comment by bdhirsh** [comment]
> Do you still need the replay logic for outputs that are views of inputs?

I think we still do, yes (if the user mutates an output, that should be reflected in the autograd graph for the input). But AOTAutograd handles this independently from "intermediate base" handling - it removes the view from the graph completely, and regenerates it in the epilogue.
