### ISSUE TITLE
dynamo sometimes hits the cache size limit due to the foreach flag in optimizer.step()

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#97711]
### 🐛 Describe the bug

When one torch.compile()'s the optimizer.step() for certain models and optimizers, dynamo sometimes hits the cache size limit due to the foreach flag. It should not try recompiling a graph for the foreach flag currently since we should just be tracing single-tensor for now. This will likely be fixed by @mlazos's foreach + optimizer changes and this issue is a tracker to make sure it is not forgotten. 

### Error logs

```
Warning: 27 21:42:30,628] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (64)
   function: 'nadam' (/home/ubuntu/miniconda3/envs/userbenchmarks-ci/lib/python3.10/site-packages/torch/optim/nadam.py:160)
   reasons:  ___check_obj_id(foreach, 7698112)
to diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
```

### Repro

I'm not sure this is easy to repro in a small way, but this happens when I run my benchmarking script from https://github.com/pytorch/benchmark/pull/1473 with `python -m userbenchmark.optim.__init__`. 

### Versions

2.0, nightlies

cc @vincentqb @jbschlosser @albanD @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire @lazos

**Comment by yanboliang** [comment]
cc @mlazos

**Comment by anijain2305** [comment]
@mlazos is this still valid?

**Comment by mlazos** [comment]
This is fixed, we fullgraph compile 11/13 optimizers, and are disabled on the other two.

**Comment by janeyx99** [comment]
To clarify, the full graph compilation only applies to when you unwrap the use_grad wrapper from `step`, as there is still a graph break due to no_grad modification. We are looking to remove this and this issue is tracked in https://github.com/pytorch/pytorch/issues/104053, but if someone tried compiling `optimizer.step` as is today, it won't be a full graph.
