### ISSUE TITLE
Dynamo generates invalid frame when graph-breaking due to opacus_cifar10 hooks

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#97718]
### 🐛 Describe the bug

When running torchbench opacus_cifar10 today in CI, hooks are silently ignored on modules such as `torch.nn.modules.conv.Conv2d` since this is 'allowed' in graph and hooks aren't traced by dynamo.  Some of the hook behavior might actually be burned into the AOT trace, and this is at best shaky or more likely incorrect (I didn't read carefully what the hooks do but it's not trivial) - [capture_activations_hook](https://github.com/pytorch/opacus/blob/main/opacus/grad_sample/grad_sample_module.py#L267), [capture_backprops_hook](https://github.com/pytorch/opacus/blob/main/opacus/grad_sample/grad_sample_module.py#L290)

There is a related gh issue (#96722) where dynamo skips hooks on 'allowed' modules.  PR #97184 fixes this by graph-breaking on allowed_modules that have hooks.  See the PR desc for more discussion on alternative fixes.

After graph-breaking on allowed modules with hooks, opacus fails with what looks like an invalid dynamo frame generated.

Checkout: `ghstack checkout https://github.com/pytorch/pytorch/pull/97184`
Repro:
`TORCH_COMPILE_DEBUG=1 python benchmarks/dynamo/torchbench.py --only opacus_cifar10 --performance --backend aot_eager > opacus.log 2>&1`

Log: https://gist.github.com/wconstab/50e752cc4a6db010549c2f5cdfff67ac

**Notable excerpts from log:**

This graphbreak is expected, due to the change in #97184

```
[2023-03-27 23:34:30,451] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason="Can't support hooks on 'allowed' modules (<class 'torch.nn.modules.conv.Conv2d'>) becuase allowed modules don't get traced through.",
```

Not sure why getattr fails here, unless it's becuase the hook didn't modify the dynamo's copy of the module and the hook is actually mutating the module via setattr.  (The hook does actually store stuff on the module) 

```
[2023-03-27 23:34:30,456] torch._dynamo.symbolic_convert: [DEBUG] FAILED INLINING <code object __getattr__ at 0x7ff33221e3a0, file "/scratch/whc/work/pytorch/torch/nn/modules/module.py", line 1601>
[2023-03-27 23:34:30,456] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-03-27 23:34:30,457] torch._dynamo.symbolic_convert: [DEBUG] step triggered compile
```

?
```
torch._dynamo.exc.Unsupported: class property GradSampleModule getset_descriptor
[2023-03-27 23:34:30,457] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-03-27 23:34:30,457] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='step_unsupported', user_stack=[<FrameSummary file /scratch/whc/work/py38/lib/python3.8/site-packages/opacus/grad_sample/gsm_base.py, line 71 in __getattr__>])
ERROR:common:Backend dynamo failed in warmup()
```

And finally we bottom out with a stackframe that's invalid.
```
  File "/scratch/whc/work/pytorch/torch/_dynamo/bytecode_analysis.py", line 185, in stacksize_analysis
    assert low >= 0
AssertionError: 
```

### Versions

PR (see above)

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @anijain2305 @Xia-Weiwen @desertfire

**Comment by Adesoji1** [comment]
have you tried this? 
Verify that Opacus is up to date:
pip install --upgrade opacus

Check if your hooks are modifying the module's attributes, which could cause issues with Dynamo. If possible, avoid modifying the module attributes within the hooks, and instead consider implementing a custom module that integrates the desired behavior.

You can attempt to use PyTorch JIT (Just-In-Time) compilation to see if the issue still persists. This may help isolate the problem and identify whether it is specific to the AOT compilation. To use JIT, you can trace or script your model:

import torch
import torchvision

# Example using a pre-trained model from torchvision
model = torchvision.models.resnet18(pretrained=True)

# Use torch.jit.trace or torch.jit.script depending on your use case
scripted_model = torch.jit.script(model)

# Save the scripted model
scripted_model.save("resnet18_scripted.pt")

**Comment by ESI-SYD** [comment]
Tracked https://github.com/pytorch/pytorch/issues/93531#issuecomment-1558372237

**Comment by anijain2305** [comment]
Does not repro on main. A lot of fixes have gone in for different issues listed here in past year.
