### ISSUE TITLE
Support for ppc64el arch?

### ISSUE THREAD

**Issue by bapriddy** [pytorch/pytorch#9771]
When will there be support for ppc64el arch?  I read an old post that said never!  Is this still the consensus?

**Comment by avmgithub** [comment]
pytorch is supported on ppc64le  (both Ubuntu 16.04 and above and  RH 7.4 and above).   You have to build it from source.  See this for reference : https://github.com/ppc64le/build-scripts/tree/master/pytorch

**Comment by zou3519** [comment]
We should add a line to the readme about this

**Comment by heitorschueroff** [comment]
Closing this issue, @zou3519 do we still want to add a line to readme? If so, I think another issue should be created for that.
