### ISSUE TITLE
Foreach optimizers use higher memory due to intermediates

### ISSUE THREAD

**Issue by yongyanrao** [pytorch/pytorch#97712]
### 🐛 Describe the bug

Use https://github.com/pytorch/examples/tree/main/word_language_model, and apply the following changes to `main.py`, since the original script does not use any optimizer.
```
diff --git a/word_language_model/main.py b/word_language_model/main.py
index 23bda03..5ae6877 100644
--- a/word_language_model/main.py
+++ b/word_language_model/main.py
@@ -114,6 +114,8 @@ else:

 criterion = nn.NLLLoss()

+optim = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=0.01)
+
 ###############################################################################
 # Training code
 ###############################################################################
@@ -184,12 +186,16 @@ def train():
             hidden = repackage_hidden(hidden)
             output, hidden = model(data, hidden)
         loss = criterion(output, targets)
+
+        optim.zero_grad()
         loss.backward()
+        optim.step()

         # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
-        torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
-        for p in model.parameters():
-            p.data.add_(p.grad, alpha=-lr)
+        # torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip)
+        # for p in model.parameters():
+        #     p.data.add_(p.grad, alpha=-lr)
+

         total_loss += loss.item()
```
And then training with 
```
python main.py --cuda --epochs 6 --model Transformer --lr 0.001 --nhead 40 --nhid 5120 --nlayers 12 --emsize 800
```
By training with PyTorch-1.13.1 and PyTorch-2.0.0, we can find the latter one uses higher memory.

### Versions

```
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100-SXM4-40GB
GPU 1: NVIDIA A100-SXM4-40GB
GPU 2: NVIDIA A100-SXM4-40GB
GPU 3: NVIDIA A100-SXM4-40GB
GPU 4: NVIDIA A100-SXM4-40GB
GPU 5: NVIDIA A100-SXM4-40GB
GPU 6: NVIDIA A100-SXM4-40GB
GPU 7: NVIDIA A100-SXM4-40GB

Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Stepping:                        7
CPU MHz:                         2999.998
BogoMIPS:                        5999.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] sagemaker-pytorch-training==2.7.0
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchtnt==0.0.7
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] magma-cuda118             2.6.1                         1    pytorch
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.5          py310h53a5b5f_0    conda-forge
[conda] pytorch                   2.0.0           aws_py3.10_cuda11.8_cudnn8.7.0_0    https://aws-ml-conda-pre-prod-sm.s3.us-west-2.amazonaws.com
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch-test
[conda] pytorch-mutex             1.0                        cuda    pytorch-test
[conda] sagemaker-pytorch-training 2.7.0                    pypi_0    pypi
[conda] torchaudio                2.0.1               py310_cu118    pytorch-test
[conda] torchtnt                  0.0.7                    pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.1              py310_cu118    pytorch-test
```

cc @ezyang @gchanan @zou3519 @vincentqb @jbschlosser @albanD @janeyx99 @crcrpar @mcarilli @ngimel

**Comment by drisspg** [comment]
@janeyx99

**Comment by rahul003** [comment]
@yongyanrao Can you add some numbers on how much higher is the memory usage in this scenario?

**Comment by yongyanrao** [comment]
For the example above, `nvidia-smi` shows memory usage difference:
`1.13.1+cu117`: 5515MiB
`2.0.0+cu118`: 6802MiB

**Comment by malfet** [comment]
@yongyanrao can you please compare `cu117` and `cu117` version? (`cu118` might have a higher memory footprint)

**Comment by MaxxP0** [comment]
I am having the same issue.
Pytorch1.13.1+cu117 uses 5.4gb VRAM
Pytorch2.0.0+cu117 uses 7gb VRAM

**Comment by MaxxP0** [comment]
i just found out that setting the optimizer parameter fused:False, fixes this issue for me.

**Comment by janeyx99** [comment]
One major difference between 1.13 and 2.0 is that we now default to the faster foreach implementation (setting foreach=True) for most optimizers, including Adam. The default switching is disabled when one passes in certain kwargs, like fused=False. @MaxxP0 Thus, based on your comment, it seems like there is a memory disparity between the foreach and the for-loop implementation. I’ll take a look into why later today.

**Comment by janeyx99** [comment]
Aha. I have discovered the reason why peak memory differs, and it very much does have to do with the tradeoff between perf vs memory for the foreach and for-loop implementations.

The slow OG implementation of most optimizers is the for-loop implementation, which is the straightforward go param by param update. The foreach implementation recognizes that it would save lots of time if we did the update all at once by globbing the params together into one big multi-tensor. However! As this issue points out, the peak memory usage with the globbed computation is much higher, _because the intermediates are also now huge globbed tensorlists_.

To better illustrate with code, this is the adam.py for-loop weight decay update:
https://github.com/pytorch/pytorch/blob/234df29901a5fca1e23594a338a2f2201a28032f/torch/optim/adam.py#L335

Note that this is NOT an inplace update, so grad would point to an intermediate Tensor that is not the same as the grad of the param, using up extra memory for one intermediate Tensor.

The foreach equivalent has a whole tensorlists of grads as an intermediate, using up len(params) * Tensor amount of memory:
https://github.com/pytorch/pytorch/blob/234df29901a5fca1e23594a338a2f2201a28032f/torch/optim/adam.py#L442

This is why the peak memory usage differs so greatly. I am going to rename the issue title accordingly and prioritize fixing this.

**Comment by robieta** [comment]
I agree with your assessment that this is due to converting many small allocations and frees into a small number of monster allocations and frees. I put together [this gist](https://gist.github.com/robieta/fbb0cd709fdc910edf1ffad9b0cd1d1b) to profile a simple stack of linear layers:

<img width="1486" alt="Screenshot 2023-06-15 at 4 10 54 PM" src="https://github.com/pytorch/pytorch/assets/13089297/116e3ab3-7ceb-4109-a523-c83a84e85ec2">

If we pull apart the events to get python calls around the memory peak (in the gist) we get:
```
37665345024 <built-in method _foreach_add of type object at 0x7f91f1875120>  (called from)  torch/optim/adam.py(512): _multi_tensor_adam
  5368742400 5368742400

32296602624 <built-in method _foreach_sqrt of type object at 0x7f91f1875120>  (called from)  torch/optim/adam.py(510): _multi_tensor_adam
  5368742400 5368742400

26927860224 <built-in method _foreach_add of type object at 0x7f91f1875120>  (called from)  torch/optim/adam.py(448): _multi_tensor_adam
  5368742400 5368742400
```


L448 (`if weight_decay != 0: device_grads = ...`) was identified above, but there are two other large blocks. (And unlike weight decay, they occur with default hyperparameters.)

https://github.com/pytorch/pytorch/blob/fa893f3f58d4fbbf498132586e6e9c335d800d2e/torch/optim/adam.py#L510-L512

As much as I love the idea of foreach optimizers, IMHO the default should be rolled back until the memory problem has been solved. It is a serious and hard to diagnose regression for anyone training parameter heavy models and only delivers a modest overhead reduction for a comparatively modest range of models.

CC @aaronenyeshi, @zdevito

**Comment by janeyx99** [comment]
Alright, let me prioritize this within the next week

**Comment by zdevito** [comment]
An optimizer that globs all the parameters together is naturally going to run after the backward is done (and activations are freed). So one possibility here is that memory usage doesn't actually need to be higher, it is just the case that those big allocations cannot fit in the segments for the smaller tensors and end up being allocated separately. If the process was actually under memory pressure (e.g. memory got entirely filled), then those small segments would get freed, the big ones would be allocated in their place, and the next pass would likely be able to run by using the big allocated memory.  

If the above is what is happening the expandable_segments:True allocator option would prevent extra memory use but I don't think that is a general solution.

**Comment by janeyx99** [comment]
Due to planning and several other things that have popped up this week, I won't be able to get to opening a fix by the end of this week :(. However, it is clear what needs to be done: we need to use more in place operators and fewer intermediates in each of the foreach optimizer implementations. I am hoping to do this in the coming weeks for each optimizer, but if you are blocked, please submit a PR and I will be happy to review.

**Comment by janeyx99** [comment]
@yongyanrao @robieta I've starting minimizing memory as much as I could in the Adam family. There is a minimum budget of 1 intermediate (with size equal to the sum of the sizes of the parameters) as we cannot inplace modify saved state.

Could y'all give the latest nightly a whirl to verify the memory usage has decreased? It also looks like runtime should have gotten slightly faster as well based on my dash:
<img width="900" alt="image" src="https://github.com/pytorch/pytorch/assets/31798555/b95013dd-45ca-4224-bfba-d9274afc6ba0">

**Comment by janeyx99** [comment]
All current foreach optimizers have been evaluated for peak memory usage and the PRs hto minimize intermediate usage have all landed as of https://github.com/pytorch/pytorch/pull/105193. With this, I am closing this issue.

**Comment by garrett361** [comment]
This was a great discussion and analysis. Stumbled on this when looking for information on what `for_each` does. Very informative.  Thanks everyone.
