### ISSUE TITLE
[ONNX] `fx_name_to_onnxscipt_value` is annotated the wrong type

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#97728]
https://github.com/pytorch/pytorch/blob/1c15cd48e213db3fe13f01056021f34fd5326ca7/torch/onnx/_internal/fx/passes/fx_to_onnxscript.py#L555-L557

Should it be TorchScriptTensor? We should not have any visible torch.Value anywhere in the fx exporter.

cc @BowenBao

**Comment by titaiwangms** [comment]
Sure, I can change this in my next PR.

**Comment by justinchuby** [comment]
NBD. I didn't know it was discovered so. Feel free to close
