### ISSUE TITLE
pytorch-cpu conda v2.0.0

### ISSUE THREAD

**Issue by samhorsfield96** [pytorch/pytorch#97762]
### 🚀 The feature, motivation and pitch

Hi, are there plans to update the pytorch-cpu conda recipe (https://anaconda.org/conda-forge/pytorch-cpu) to pytorch v2.0.0? I currently rely on an old version of the recipe in my code (https://github.com/samhorsfield96/ggCaller). Many thanks, Sam

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment]
Please file an issue against https://github.com/conda-forge/pytorch-cpu-feedstock
