### ISSUE TITLE
Arm64 LibTorch pdb files are missing from the CI Built binaries

### ISSUE THREAD

**Issue by iremyux** [pytorch/pytorch#97771]
The .pdb files of the libraries in libtorch/bin folder are missing. The created artifacts for debug can be found [here](https://github.com/pytorch/pytorch/actions/runs/4435546827?pr=95283) and for release can be found [here](https://github.com/pytorch/pytorch/actions/runs/4435546833?pr=95283) .

The missing .pdb files are:
- asmjit.pdb
- c10.pdb
- fbgemm.pdb
- fbjni.pdb
- pytorch_jni.pdb
- torch_cpu.pdb

**Comment by Blackhex** [comment]
Resolved with 76f9ffb.
