### ISSUE TITLE
inductor: NameError: name 'math_floor' is not defined when running fx_graph_runnable.py

### ISSUE THREAD

**Issue by XiaobingSuper** [pytorch/pytorch#97778]
### 🐛 Describe the bug

For inductor dynamic shape case, when running the debug code ```fx_graph_runnable.py```, some models always meet the following error:
```
NameError: name 'math_floor' is not defined
```
or 
```
NameError: name 'math_ceil' is not defined
```

you can directly run https://gist.github.com/XiaobingSuper/4592434a70779eca591f0cc5cf3a02e7#file-fx_graph_runnable-py, and will report ```NameError```.

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git33dfded
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] clip-anytorch==2.5.2
[pip3] CoCa-pytorch==0.0.7
[pip3] dalle2-pytorch==1.10.5
[pip3] ema-pytorch==0.2.2
[pip3] functorch==1.14.0a0+408bcf1
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.1
[pip3] pytorch-transformers==1.2.0
[pip3] pytorch-warmup==0.1.1
[pip3] rotary-embedding-torch==0.2.1
[pip3] torch==2.1.0a0+git5aa4046
[pip3] torch-fidelity==0.3.0
[pip3] torch-struct==0.5
[pip3] torchaudio==2.0.0a0+a8f4e97
[pip3] torchdata==0.7.0a0+f1283eb
[pip3] torchmetrics==0.11.4
[pip3] torchrec-nightly==2023.3.23
[pip3] torchtext==0.15.0a0+46e7eef
[pip3] torchvision==0.15.0a0+98c5815
[pip3] vector-quantize-pytorch==1.1.2
[conda] bert-pytorch              0.0.1a4                   dev_0    <develop>
[conda] clip-anytorch             2.5.2                    pypi_0    pypi
[conda] coca-pytorch              0.0.7                    pypi_0    pypi
[conda] dalle2-pytorch            1.10.5                   pypi_0    pypi
[conda] ema-pytorch               0.2.2                    pypi_0    pypi
[conda] functorch                 1.14.0a0+408bcf1          pypi_0    pypi
[conda] mkl                       2023.0.0         h6d00ec8_25399
[conda] mkl-include               2023.0.0         h06a4308_25399
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] pytorch-transformers      1.2.0                    pypi_0    pypi
[conda] pytorch-warmup            0.1.1                    pypi_0    pypi
[conda] rotary-embedding-torch    0.2.1                    pypi_0    pypi
[conda] torch                     2.1.0a0+git5aa4046           dev_0    <develop>
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-struct              0.5                      pypi_0    pypi
[conda] torchaudio                2.0.0a0+a8f4e97          pypi_0    pypi
[conda] torchdata                 0.6.0                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchrec-nightly          2023.3.23                pypi_0    pypi
[conda] torchtext                 0.15.0a0+46e7eef          pypi_0    pypi
[conda] torchvision               0.15.0a0+98c5815           dev_0    <develop>
[conda] vector-quantize-pytorch   1.1.2                    pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by XiaobingSuper** [comment]
I find that fx always convert ```math.floor``` to ```math_floor``` or ```math.ceil``` to ```math_ceil```:
https://github.com/pytorch/pytorch/blob/c785f1903a0d46a76d11e60b7768c8f5eb52a6f5/torch/fx/graph.py#L141

It doesn't make sense.

**Comment by ezyang** [comment]
assigning to @Chillee since he was working on improving the minifier

**Comment by ezyang** [comment]
This is still happening

**Comment by anijain2305** [comment]
Is there a way to repro this? I mean having an original model that dumps out the `math_floor` op in the graph?

@ezyang

**Comment by angelayi** [comment]
Chatted with Animesh on this and I think I figured out a way to repro:
```
import torch

def f(a, b, c):
    d = (torch.matmul(a, b) + c) / 2
    d_s0 = d.shape[0]
    d_s1 = d.shape[1]
    d_s3 = math.floor(d_s0 * d_s1)
    e = d.view(d_s3)
    return torch.cat([e, e])


import torch._export
from torch._export import export, dynamic_dim

inputs = (torch.randn(2, 4), torch.randn(4, 7), torch.randn(2, 7))
constraints = [
    dynamic_dim(inputs[0], 0),
    dynamic_dim(inputs[2], 0),
    dynamic_dim(inputs[2], 0) == dynamic_dim(inputs[0], 0),
]
gm = export(f, inputs, constraints).graph_module
graph_module.to_folder("debug")
```

debug/module.py contains:
```
import torch
from math import inf
from math import nan
NoneType = type(None)
import torch
from torch import device
import torch.fx._pytree as fx_pytree
import torch.utils._pytree as pytree

from torch.nn import *
class FxModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.load_state_dict(torch.load(r'debug/state_dict.pt'))

    
    
    def forward(self, arg0_1, arg1_1, arg2_1):
        mm = torch.ops.aten.mm.default(arg0_1, arg1_1);  arg1_1 = None
        add = torch.ops.aten.add.Tensor(mm, arg2_1);  mm = arg2_1 = None
        div = torch.ops.aten.div.Tensor(add, 2);  add = None
        sym_size = torch.ops.aten.sym_size(arg0_1, 0);  arg0_1 = None
        mul = sym_size * 7;  sym_size = None
        floor = math_floor(mul);  mul = None
        view = torch.ops.aten.view.default(div, [floor]);  div = floor = None
        cat = torch.ops.aten.cat.default([view, view]);  view = None
        return (cat,)
```

It should have something like: `import math.floor as math_floor` at the top.

**Comment by eellison** [comment]
```
import torch
import math

@torch.compile(dynamic=True)
def f(a, b, c):
    d = (torch.matmul(a, b) + c) / 2
    d_s0 = d.shape[0]
    d_s1 = d.shape[1]
    d_s3 = math.floor(d_s0 * d_s1)
    e = d.view(d_s3)
    return torch.cat([e, e])

inputs = (torch.randn(2, 4), torch.randn(4, 7), torch.randn(2, 7))
f(*inputs)
```

No longer fails. If this is an issue please re-open.
