### ISSUE TITLE
clamp_ has inconsistent behaviour

### ISSUE THREAD

**Issue by lemairecarl** [pytorch/pytorch#9778]
## Issue description

`tensor.clamp_` has inconsistent behaviour when used on subtensors produced with different indexing methods.

### Exhibit 1

```python
In[56]: m = torch.tensor([1, 0]).byte()
In[57]: a = torch.ones(2)

In[58]: a[m].clamp_(min=2)  # in-place
Out[58]: tensor([ 2.])
In[59]: a
Out[59]: tensor([ 1.,  1.])  # Unexpected output

In[60]: a[m] = a[m].clamp(min=2)  # out-of-place + assignment
In[61]: a
Out[61]: tensor([ 2.,  1.])  # Expected output
```

### Exhibit 2

```python
In[43]: a = torch.ones(2)
In[44]: a
Out[44]: tensor([ 1.,  1.])
In[45]: m = torch.tensor([1, 0]).byte()

In[46]: a[m].clamp_(min=2)
Out[46]: tensor([ 2.])
In[47]: a
Out[47]: tensor([ 1.,  1.])  # Unexpected output

In[48]: a[[0]].clamp_(min=2)
Out[48]: tensor([ 2.])
In[49]: a
Out[49]: tensor([ 1.,  1.])  # Unexpected output

In[50]: a[0].clamp_(min=2)
Out[50]: tensor(2.)
In[51]: a
Out[51]: tensor([ 2.,  1.])  # Expected output
```

## System Info

```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 390.59
cuDNN version: Probably one of the following:
/usr/local/cuda-9.1/lib64/libcudnn.so.7.1.4
/usr/local/cuda-9.1/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.5)
[pip] torch (0.4.0)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] pytorch                   0.4.0           py36_cuda9.1.85_cudnn7.1.2_1  [cuda91]  pytorch
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch
```

**Comment by t-vi** [comment]
The fundamental reason you're seeing this is that a[m] and a[[0]] is a new tensor with elements copied from a and a[0] is a view of a.

Numpy does very tricky things to support a[m] and a[[0]] on the left hand side of assignments:
```
a = numpy.random.randn(10)
a[a>0] = 1
print(a) # a has 1
b = numpy.random.randn(10)
c = b[b>0]
c[:] = 1
print (b) # b won't have 1
```

**Comment by lemairecarl** [comment]
Are you sure? What bothers me the most is this:

```python
In[57]: a = torch.ones(2)
In[58]: a[m].clamp_(min=2)  # in-place
Out[58]: tensor([ 2.])
In[59]: a
Out[59]: tensor([ 1.,  1.])
In[60]: a[m] = a[m].clamp(min=2)  # out-of-place + assignment
In[61]: a
Out[61]: tensor([ 2.,  1.])
```

If the second method above works, I think the first one (in-place) should also work. Also, the in-place method makes the code a bit cleaner.

I will add this snippet to the issue message.

**Comment by t-vi** [comment]
I am relatively sure because I double checked. What happens is that `a[m] = something` translates to the Python `__setitem__` method, where the slicing is handled as a view. When you have `a[m]` "anywhere else than in an assignment", it will translate to `__getitem__`. That returns a tensor with new storage when used with boolean indexing. It's not limited to `clamp_`, either, any inplace (e.g. `.add_(1000)`) will have the same behaviour.
To implement the behaviour you expect, you would essentially need to introduce a new "tensor view" object (or extend tensor to be able to use one), which is a rather hefty feature request.

**Comment by lemairecarl** [comment]
Ah, I see.

>`a[m] = something` translates to the Python `__setitem__` method

This is what I missed. I thought pytorch provided tensor view objects to support this.  Thanks for your time.
