### ISSUE TITLE
THPDtypeType.tp_dict == nullptr INTERNAL ASSERT FAILED at "../torch/csrc/Dtype.cpp":135, please report a bug to PyTorch. 

### ISSUE THREAD

**Issue by caglacolak** [pytorch/pytorch#97805]
### 🐛 Describe the bug

 import torch

THPDtypeType.tp_dict == nullptr INTERNAL ASSERT FAILED at "../torch/csrc/Dtype.cpp":135, please report a bug to PyTorch. 

### Versions

pip install tourch

cc @malfet @seemethere

**Comment by janeyx99** [comment]
Hello, could you provide more information regarding the environment for which this was run on? For example, what OS version and python version are you running on? When you use pip install torch, which version was installed?

**Comment by janeyx99** [comment]
Okay, I'm going to close the issue as it's been resolved. Don't hesitate to reopen if this same issue happens again.
