### ISSUE TITLE
gumbel_softmax doesn't work as expected

### ISSUE THREAD

**Issue by lucklove** [pytorch/pytorch#97851]
### 🐛 Describe the bug

```
import torch
import torch.nn.functional as F

xs = []
logits = torch.tensor([0.1, 0.2, 0.3, 0.4])
for _ in range(10000):
    xs.append(F.gumbel_softmax(logits, hard=True).numpy())
sum(xs)
```

The desired result should be close to:

```
[1000, 2000, 3000, 4000]
```

but the out of sum(xs) is

```
[2158., 2319., 2589., 2934.]
```

### Versions

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-159-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           94
Model name:                      Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
Stepping:                        3
CPU MHz:                         2394.356
BogoMIPS:                        4788.71
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        16 MiB
L3 cache:                        27.5 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 arat

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] nomkl                     1.0                  h5ca1d4c_0    conda-forge
[conda] numpy                     1.21.5           py39haac66dc_0    conda-forge
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torchaudio                0.11.0                   pypi_0    pypi
[conda] torchvision               0.12.0                   pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by lucklove** [comment]
I looked at the implementation in the master branch, there are some things that strange me:

- the gumbel noise is generated by [empty_like](https://github.com/pytorch/pytorch/blob/597b558c51007c6d9b7751df1a5c893024377d4d/torch/nn/functional.py#L1895) instead of rand_like. Is it a typo or by design? Does empty_like generate random number ~ [0, 1]?
- [the paper](https://arxiv.org/pdf/1611.01144.pdf) shows that should take the log of pi (the logits) first, and then add the gumbel noise, but the implementation doesn't do so. Is it an optimization?

**Comment by gchanan** [comment]
> the gumbel noise is generated by [empty_like](https://github.com/pytorch/pytorch/blob/597b558c51007c6d9b7751df1a5c893024377d4d/torch/nn/functional.py#L1895) instead of rand_like. Is it a typo or by design? Does empty_like generate random number ~ [0, 1]?

No, it's just uninitialized data, so depends on what is already there.

**Comment by arnauqb** [comment]
The function returns the expected result when passing the log of the probabilities, as I think it is intended since it takes `logits` as an argument.

```python
import torch
probs = torch.tensor([0.1, 0.2, 0.3, 0.4])
N = 10_000
exp = torch.zeros(4)
for i in range(N):
    exp += torch.nn.functional.gumbel_softmax(probs.log(), tau=0.1, hard=True)
exp
```
returns
```python
tensor([ 961., 2046., 3051., 3942.])
```

Nonetheless, I agree that the call to `torch.empty_like` instead of `torch.rand_like` is confusing and so are the calls to `exponential_` and then `log()`. These seem to generate a non-trivial result but I'm not sure why.

**Comment by lucklove** [comment]
From ChatGPT:

The line you're referring to is actually generating random samples from the Gumbel distribution.

The Gumbel distribution is a continuous probability distribution that is often used to model the maximum of a set of random variables. The distribution has a location parameter mu and a scale parameter beta, but in the case of the Gumbel-Softmax, we set mu to 0 and beta to 1, which means that we are sampling from the standard Gumbel distribution.

To sample from the Gumbel distribution, we first sample from the uniform distribution on [0, 1] and apply the inverse cumulative distribution function (CDF) of the Gumbel distribution, which is -log(-log(U)). This transformation generates random samples from the Gumbel distribution.

In the code you provided, the line

```py
-torch.empty_like(logits, memory_format=torch.legacy_contiguous_format).exponential_().log()
```

generates a tensor with the same shape as the logits tensor, fills it with samples from the exponential distribution (with a mean of 1), and then takes the negative logarithm of these samples. This is equivalent to sampling from the uniform distribution on [0, 1] and applying the inverse CDF of the Gumbel distribution, as described above.


Seems right...

**Comment by arnauqb** [comment]
Oh, thank you for the detailed explanation! It makes sense now.
