### ISSUE TITLE
torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator unsafe_chunk, unknown dimension size.

### ISSUE THREAD

**Issue by dshwei** [pytorch/pytorch#97861]
### 🐛 Describe the bug

from speechbrain.pretrained import Tacotron2
from speechbrain.pretrained import HIFIGAN
tacotron2 = Tacotron2.from_hparams(source="speechbrain/tts-tacotron2-ljspeech", savedir="tmpdir_tractron2")
hifi_gan = HIFIGAN.from_hparams(source="speechbrain/tts-hifigan-ljspeech", savedir="tmpdir_hifi")
torch.onnx.export(tacotron2.mods.model )

### Versions

torch=2.0

**Comment by SchweitzerGAO** [comment]
Any updates? Same problem

**Comment by zhuoran-guo** [comment]
Any updates? Same problem

**Comment by thiagocrepaldi** [comment]
I did `pip install speechbrain` and still got `ModuleNotFoundError: No module named 'speechbrain.pretrained'`

Please try the new ONNX exporter and reopen this issue if it also doesn't work for you with a full repro/env: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
