### ISSUE TITLE
LibTorch 2.0.0: undefined symbol: _ZN2at4_ops5randn4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

### ISSUE THREAD

**Issue by harshitAgr** [pytorch/pytorch#97878]
### 🐛 Describe the bug

# minimal C++ example fails during runtime with latest libtorch downloaded from libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip.

# CMakeLists.txt

cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(example)

find_package(Torch REQUIRED)

add_executable(example example.cpp)
target_link_libraries(example "${TORCH_LIBRARIES}")
set_property(TARGET example PROPERTY CXX_STANDARD 14)

# example.cpp

#include <torch/torch.h>
#include<iostream>

int main() {
	torch::Tensor tensor= torch::rand({1,2,10,10});
}

# cmake 

-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda-11.8 (found version "11.8") 
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda-11.8/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Caffe2: CUDA detected: 11.8
-- Caffe2: CUDA nvcc is: /usr/local/cuda-11.8/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.8
-- Caffe2: Header version is: 11.8
-- /usr/local/cuda-11.8/lib64/libnvrtc.so shorthash is 672ee683
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- Autodetected CUDA architecture(s):  8.6 8.6
-- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
-- Found Torch: /home/me/Downloads/libtorch/lib/libtorch.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/me/projects/libtorch_min/project/build

# build

[ 50%] Building CXX object CMakeFiles/example.dir/example.cpp.o
[100%] Linking CXX executable example
[100%] Built target example

# error
./example: symbol lookup error: ./example: undefined symbol: _ZN2at4_ops4rand4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

### Versions

libtorch: libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip.
cmake: 3.22.1
cuda : 11.8

cc @seemethere @malfet @jbschlosser

**Comment by malfet** [comment]
Symbol in question is `at::_ops::randn::call(c10::ArrayRef<c10::SymInt>, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>)`
Trying to get a repro. In the meantime, can you please try amending your CMakeFile by setting the language standard to C++17?

**Comment by harshitAgr** [comment]
Thanks. C++17 gives the same error.

**Comment by malfet** [comment]
Hmm, I've downloaded `libtorch-cxx11-abi-shared-with-deps-2.0.0%2Bcpu.zip` and can't reproduce the issue so far. Trying CUDA one next

**Comment by grybouilli** [comment]
Hello @harshitAgr, I'm getting a similar error, could you describe in a bit more details how you fixed yours please?
