### ISSUE TITLE
Type conversion between float/complex

### ISSUE THREAD

**Issue by gautierronan** [pytorch/pytorch#97888]
### 🚀 The feature, motivation and pitch

It would be nice to have a simple way to convert between float and complex types of the same precision. Something like
```python
dtype = torch.float32
print(dtype.to_complex())
# torch.complex64

dtype = torch.complex128
print(dtype.to_float())
# torch.float64

dtype = torch.float64
print(dtype.to_float())
# torch.float64
```

### Alternatives

1. building a dictionnary that stores conversions from float to complex types of the same precision
2. using this unpleasant/difficult to read workaround: `getattr(torch, torch.finfo(dtype).dtype)`

### Additional context

We are building a library for the simulation of quantum systems built on torch (see [torchqdynamics](https://github.com/PierreGuilmin/torchqdynamics)), and conversion between float and complex types happens all the time. Quantum objects are always complex, but time is always float-like, and it's essential that they are of the same precision.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by Skylion007** [comment]
Isn't this what view_as_real and view_as_complex are for?

**Comment by ngimel** [comment]
You can use `torch._prims_common.corresponding_real_dtype`

**Comment by gautierronan** [comment]
Thanks for pointing this function out, I didn't know it existed. One drawback is that it doesn't support float to float or complex to complex conversion (which does nothing, but it could come in handy). And it's lacking documentation in case other users would want to same feature as me.

**Comment by ezyang** [comment]
Easy enough to add. Would you mind PRing it?

**Comment by gautierronan** [comment]
Sure I can write something up, could you just point me to where in the code it should be added?
