### ISSUE TITLE
Problem building pytorch under Windows

### ISSUE THREAD

**Issue by ZmeiGorynych** [pytorch/pytorch#9791]
## Issue description
Trying to build PyTorch on a new laptop, Windows 10 Pro and a fresh install of VS2017 Community with every build tool option that looked remotely useful. 

Following the changes to the standard instructions described [here](https://github.com/pytorch/pytorch/issues/6109) I can get the build script to start; however it then fails with the following error: 
```
-- Build files have been written to: C:/Users/egork/Dropbox/GitHub/pytorch/build
Microsoft (R) Build Engine version 4.7.2556.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 24/07/2018 22:25:03.
Project "C:\Users\egork\Dropbox\GitHub\pytorch\build\INSTALL.vcxproj" on node 1 (default targets).
C:\Users\egork\Dropbox\GitHub\pytorch\build\INSTALL.vcxproj(29,3): error MSB4019: The imported project "C:\Microsoft.Cp
p.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists
on disk.
Done Building Project "C:\Users\egork\Dropbox\GitHub\pytorch\build\INSTALL.vcxproj" (default targets) -- FAILED.
```
After googling the above error, I tried setting the VCTargetsPath variable, for example to `set VCTargetsPath=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets` (a full search of my disk found two files with the name Microsoft.Cpp.Default.props, I tried both locations, the other being C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140 ). 

When trying to run the install script afterwards, the error changes to 
```
Microsoft (R) Build Engine version 4.7.2556.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 24/07/2018 22:19:02.
Project "C:\Users\egork\Dropbox\GitHub\pytorch\build\INSTALL.vcxproj" on node 1 (default targets).
Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to res
olve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVers
ion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://g
o.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.DesignTime.targets
(488,5): error MSB4062: The "SetEnv" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual
 Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Build.CppTasks.Common.dll. Could not load file or assembly 'M
icrosoft.Build.Utilities.Core, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its depend
encies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assemb
ly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Fr
amework.ITask. [C:\Users\egork\Dropbox\GitHub\pytorch\build\INSTALL.vcxproj]
Done Building Project "C:\Users\egork\Dropbox\GitHub\pytorch\build\INSTALL.vcxproj" (default targets) -- FAILED.
```
and in fact Microsoft.Build.Utilities.Core is in neither of the directories in which 
Microsoft.Build.CppTasks.Common.dll can be found. 

Any suggestions on fixing that?

Thanks a lot,
E.

**Comment by peterjc123** [comment]
```
# Probable related message:
Project file contains ToolsVersion="15.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVers
ion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
```
So the reason seems to be that you haven't installed the complete toolset.

**Comment by ZmeiGorynych** [comment]
I have installed every toolbox I could find, both VS and build tools, rebooted :), and am still getting the same behavior. After doing that, a third file called Microsoft.Cpp.Default.props has appeared under C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets, and setting the VCTargetsPath to that gives exactly the same behavior.

![image](https://user-images.githubusercontent.com/22304254/43209547-cf8590ee-9024-11e8-9cef-bf280d3769e9.png)
![image](https://user-images.githubusercontent.com/22304254/43209601-f6d7f754-9024-11e8-8c7c-abb1783fa771.png)

**Comment by peterjc123** [comment]
@ZmeiGorynych You are not picking the correct `msbuild.exe`. It should be the one in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin`.

**Comment by heitorschueroff** [comment]
Closing this issue as an answer was provided.
