### ISSUE TITLE
torch.compile doesn't respect resize_() on graph inputs

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#97921]
I get a different error with inductor vs. aot_eager backends.

inductor: silently doesn't apply the resize to the input
aot_eager: fails in AOTAutograd, with:
```
RuntimeError: setStorage: sizes [6], strides [1], storage offset 0, and itemsize 4 requiring a storage size of 24 are out of bounds for storage of size 16
```
example repro:
```
import torch


@torch.compile(backend="aot_eager")
def f(x):
    x.resize_(6)
    x.mul_(2)
    return x

def g(x):
    x.resize_(6)
    x.mul_(2)
    return x

a = torch.ones(4)
b = torch.ones(4)
out = f(a)
out2 = g(b)
print(a.shape)
print(b.shape)
print(torch.allclose(a, b))
print(torch.allclose(out, out2))
```

Getting resize_() handling to work properly in all cases is pretty hard - a simple fix for now would be for dynamo to graph break on resize_() calls.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by yanboliang** [comment]
cc @ngimel

**Comment by ngimel** [comment]
Graph breaking on `resize_` sounds good to me

**Comment by eellison** [comment]
We could graph break on resize_ if the fake tensor mode is present in the real->fake cache - that would indicate it's an input

**Comment by yanboliang** [comment]
> We could graph break on resize_ if the fake tensor mode is present in the real->fake cache - that would indicate it's an input

Actually we can check ```if source is None``` to determinate if it's an input.
