### ISSUE TITLE
YoloV7 ONNX export fails with RuntimeError: r INTERNAL ASSERT FAILED at jit_type_base.h:549

### ISSUE THREAD

**Issue by tkupek** [pytorch/pytorch#97987]
### 🐛 Describe the bug

I'm trying to export a YoloV7 model with `torch.onnx.export`.

The code for the YoloV7 implementation can be found here:
https://github.com/Chris-hughes10/Yolov7-training

I'm trying to export the model with

```python
        input = torch.randn((1, 3, 640, 640))

        onnx_filename = os.path.join(f"test_default.onnx")
        dynamic_axes = {"input": {0: "batch_size"}, "output": {0: "batch_size"}}
        torch.onnx.export(
            self.model,
            input,
            onnx_filename,
            input_names=["input"],
            output_names=["output"],
            opset_version=12,
            dynamic_axes=dynamic_axes,
        )
```

The error I'm getting is
```
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "...\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "...\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "...\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "...\lib\site-packages\torch\onnx\utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "...\lib\site-packages\torch\onnx\symbolic_opset9.py", line 6874, in onnx_placeholder
    return torch._C._jit_onnx_convert_pattern_from_subblock(block, node, env)
  File "...\lib\site-packages\torch\onnx\utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "...\lib\site-packages\torch\onnx\symbolic_opset11.py", line 226, in index_put
    if symbolic_helper._is_bool(indices_list[idx_]):
  File "...\lib\site-packages\torch\onnx\symbolic_helper.py", line 746, in _is_bool
    return _type_utils.JitScalarType.from_value(
  File "...\lib\site-packages\torch\onnx\_type_utils.py", line 190, in from_value
    scalar_type = value.type().scalarType()
RuntimeError: r INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\aten\\src\\ATen/core/jit_type_base.h":549, please report a bug to PyTorch. 

Process finished with exit code -1

```

I have tried different opset versions, disabled dynamic axes and more, without success.
Any hints are much appreciated.

### Versions

PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3070 Ti Laptop GPU
GPU 1: NVIDIA GeForce GTX 1080

Nvidia driver version: 531.41
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3301
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3301
Name=AMD Ryzen 9 6900HX with Radeon Graphics
ProcessorType=3
Revision=17409

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] pytorch-lightning==2.0.0
[pip3] torch==2.0.0+cu117
[pip3] torchmetrics==0.11.1
[pip3] torchvision==0.15.1+cu117
[conda] Could not collect

**Comment by thiagocrepaldi** [comment]
@tkupek please provide a full repro script that defines `self.model` and has all imports, etc

**Comment by tkupek** [comment]
Sorry for the late response.

Here is a script to export the model. It requires the installation of this package:

```
pip install git+https://github.com/Chris-hughes10/Yolov7-training.git
```

However, I noticed that the export is working out of the box. Only if I append the model.postprocess method to the forward function, the mentioned issue appears.

I guess ONNX cannot process the [postprocessing ](https://github.com/Chris-hughes10/Yolov7-training/blob/77eebd89cfa07ed99442323df4dd06876afe181a/yolov7/models/yolo.py#L67) method.

It's probably expected that not all of the postprocessing operations are supported in ONNX?


```
import os

import torch
from yolov7 import create_yolov7_model

model = create_yolov7_model(architecture="yolov7")

input = torch.randn((1, 3, 640, 640))

dynamic_axes = {"input": {0: "batch_size"}, "output": {0: "batch_size"}}
torch.onnx.export(
    model,
    input,
    os.path.join(f"output.onnx"),
    input_names=["input"],
    output_names=["output"],
    opset_version=12,
    dynamic_axes=dynamic_axes,
)

```

**Comment by thiagocrepaldi** [comment]
The original assert issue is fixed by https://github.com/pytorch/pytorch/pull/101608

However, I think there might need more work to make the postprocess to be exported
