### ISSUE TITLE
Size discrepencey of libAten.so on same binary 

### ISSUE THREAD

**Issue by gautamkmr** [pytorch/pytorch#9800]
I am trying to understand the pytorch pip binary available on pytorch.org and manually building using the build_wheel.sh available under builder repository.

The interesting thing is pytorch.org pip binary for python-2.7 is of size 75MB while using the build_wheel.sh its size is 49 MB.

I am building for CPU with NO_CUDA=1 and pytorch.org binary is also for cpu. 
After extracting the wheel package I found that 

pytorch.org binary has **libATen.so** of size **100MB**
build_wheel.sh produces binary has **libAten.so** of size **11M**

**Comment by gautamkmr** [comment]
@soumith  any help?

**Comment by soumith** [comment]
the wheel on pytorch.org statically links MKL, and hence the additional size.
