### ISSUE TITLE
sqrt does not work with permute for MPS backend

### ISSUE THREAD

**Issue by jdb78** [pytorch/pytorch#98074]
### 🐛 Describe the bug

When applying `permute()` and a subsequent `sqrt()`, the mps backend does not process numbers correctly. Running on "cpu" is fine. I assume something is going wrong in `permute()`

Here is a reproducible example:

```python
import torch
x = torch.tensor([[[ 5.4682e+01,  4.6808e+01,  3.0052e-01,  7.9335e-01,  2.9827e-02,
          -1.2526e-01, -1.4951e-01,  2.0965e-02, -3.8951e-02, -6.4755e-02,
          -1.1634e-01, -1.3664e-01,  7.6581e-02, -6.7145e-02],
         [ 5.4682e+01,  4.6808e+01,  3.0221e-01,  8.0021e-01,  4.3539e-02,
          -1.1973e-01, -1.5327e-01,  1.8146e-02, -4.9131e-02, -7.4980e-02,
          -1.2084e-01, -1.5291e-01,  9.5669e-02, -6.9044e-02],
         [ 5.4682e+01,  4.6808e+01,  2.9350e-01,  7.9190e-01,  4.5278e-02,
          -1.1613e-01, -1.6498e-01,  1.5942e-02, -5.6110e-02, -7.5458e-02,
          -1.3216e-01, -1.5973e-01,  9.6978e-02, -7.3055e-02]],

        [[ 5.4682e+01,  4.6808e+01,  2.9427e-01,  8.2911e-01,  3.4680e-02,
          -1.3831e-01, -1.0695e-01,  3.5526e-02,  1.1863e-02, -3.8334e-02,
          -8.2048e-02, -1.0484e-01,  3.4512e-02, -6.4307e-02],
         [ 5.4682e+01,  4.6808e+01,  2.9440e-01,  8.2899e-01,  3.4583e-02,
          -1.3845e-01, -1.0717e-01,  3.5825e-02,  1.2162e-02, -3.7982e-02,
          -8.2242e-02, -1.0442e-01,  3.3953e-02, -6.4481e-02],
         [ 5.4682e+01,  4.6808e+01,  2.9492e-01,  8.2421e-01,  3.2992e-02,
          -1.3719e-01, -1.1099e-01,  3.4481e-02,  7.2558e-03, -4.1264e-02,
          -8.5311e-02, -1.0641e-01,  3.7364e-02, -6.3753e-02]]],
       device='mps:0')

x.permute(1, 0, 2)[..., 3].sqrt()
```

results in

```python
tensor([[7.3947, 0.8907],
        [6.8417, 0.1727],
        [0.5482,    nan]], device='mps:0')
```

which is obviously wrong.

All the following alternative operations (which should do just the same) just work fine

```python
x[..., 3].sqrt().T
x.permute(1, 0, 2)[..., 3].clone().sqrt()
x.permute(1, 0, 2)[..., 3].pow(0.5)
```

producing the expected result of

```python
tensor([[0.8907, 0.9106],
        [0.8945, 0.9105],
        [0.8899, 0.9079]], device='mps:0')
```

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.2
Libc version: N/A

Python version: 3.10.9 (main, Mar  1 2023, 12:20:14) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] flake8==5.0.4
[pip3] mypy==1.1.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-forecasting==0.0.0
[pip3] pytorch-lightning==2.0.0
[pip3] pytorch-optimizer==2.5.1
[pip3] torch==2.0.0
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.1
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.21.5           py39h42add53_3  
[conda] numpy-base                1.21.5           py39hadd41eb_3  
[conda] numpydoc                  1.4.0            py39hca03da5_0  

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by pat749** [comment]
It seems that in this case, the combination of the `permute()` and `sqrt()` operations is not being handled correctly by the `mps` backend. Specifically, the NaN value in the result suggests that there may be some numerical instability or precision errors.

One possible solution is to avoid using the mps backend and instead use the CPU or CUDA backend for this operation. You can do this by specifying the device when creating the tensor.

**Comment by malfet** [comment]
This bug affects all unary ops, for example with neg:
```
python -c "import torch; x=torch.arange(84,dtype=torch.float, device='mps').reshape(2, 3, 14); y=x.permute(1, 0, 2)[..., 3];print(y+y.neg())"
tensor([[ 3., 42.],
        [16., 55.],
        [29., 68.]], device='mps:0')
```

**Comment by tvercaut** [comment]
Could it be the same root cause as https://github.com/pytorch/pytorch/issues/89673#issuecomment-1472381665 ?
