### ISSUE TITLE
[dynamo] hf_Reformer's graph break has increased

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#98087]
https://github.com/pytorch/pytorch/pull/98003 updated the torchbench version that CI uses. While it does pick up a transformers upstream change which fixes graph break in Bert, it increase hf_Reformer's graph break from 5 to 26 for inference and from 51 to 67 for training. 

cc: @ngimel 

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel

**Comment by voznesenskym** [comment]
I can take this.

**Comment by anijain2305** [comment]
Turning this low priority because hf_Reformer has manual_seed sprinkled all over the model. I also think this will be well covered in AOT export workstream. So, making this low priority.

**Comment by desertfire** [comment]
Close since the stats has improved
