### ISSUE TITLE
PyTorch pip installed package doesn't can't be linked to a project that builds agains googletest

### ISSUE THREAD

**Issue by jjsjann123** [pytorch/pytorch#98093]
## bug

Project can't link against googletest along with pytorch.

What I have is a trivial example using googletest
```
# CMakeLists.txt
add_executable(testt ./main.cpp)
set_property(TARGET testt PROPERTY CXX_STANDARD 17)
target_link_libraries(testt PRIVATE gtest_main)
# commenting out ${TORCH_LIBRARIES} linking seems to get it to work
target_link_libraries(testt PRIVATE ${TORCH_LIBRARIES})
```

```
root@c4464de3e772:/workspace/pytorch_gtest_repro/build# make
[ 20%] Built target gtest
[ 40%] Built target gtest_main
[ 50%] Linking CXX executable testt
/usr/bin/ld: CMakeFiles/testt.dir/main.cpp.o: in function `add_negative_flag(std::string const&)':
main.cpp:(.text+0x2b): undefined reference to `testing::FLAGS_gtest_filter'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/testt.dir/build.make:114: testt] Error 1
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/testt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

## background

Note1: This only repros with pip package from upstream. If I switch the system to use my locally built pytorch pip wheel, it actually compiles fine. So I'm pretty convinced that there's something wrong with upstream pip package.

Note2: In my desperate debugging, peeking into the binaries
```
root@e09e5ed6d13a:/workspace/pytorch_gtest_repro/build# nm /usr/local/lib/python3.10/site-packages/torch/lib/lib*.so | grep -i FLAGS_ | grep gflags
000000000001f560 t _GLOBAL__sub_I_flags_use_no_gflags.cpp
```
```
root@c4464de3e772:/workspace/pytorch_gtest_repro/build# nm /usr/local/lib/python3.10/site-packages/torch/lib/lib*.so  | grep -i FLAGS_ | grep gflags
00000000000254b0 t _GLOBAL__sub_I_flags_use_no_gflags.cpp
```
Looks like neither upstream pip wheel nor my local pip build uses gflags.
The real error also expands to more than just the FLAGS_gtest_filter on my full project, so I don't think it's a gflag only problem.

### Versions

Repro is pushed here: https://github.com/jjsjann123/pytorch_gtest_repro

```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
git clone https://github.com/jjsjann123/pytorch_gtest_repro.git
cd pytorch_gtest_repro
git submodule update --init --recursive
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH="$(python -c 'import torch.utils; print(torch.utils.cmake_prefix_path)')" ..
make -j 10  # this is where it fails.
```

cc @malfet @seemethere

**Comment by ppwwyyxx** [comment]
You should grep this library instead:
```
$ nm lib/libgtest.a | grep FLAGS_gtest_filter | c++filt

0000000000000040 B testing::FLAGS_gtest_filter[abi:cxx11]
```

That shows that the googletest library is compiled with cxx11abi, while the main source inherits pytorch's pip package's flag `-D_GLIBCXX_USE_CXX11_ABI=0`. Hence they cannot be linked together.

**Comment by malfet** [comment]
Unfortunately there isn't much one can do about it: pip linux binaries are for manylinux_2014 should still be linked with pre-cxx11 flags, which are correctly passed to cmake targets depending on those...

**Comment by jjsjann123** [comment]
Ha, thanks a lot for pointing me to that~ Looks like it's indeed only the ABI issue. We do build googletest from source. I'll just have to keep it consistent with `TORCH_CXX_FLAGS` then.
