### ISSUE TITLE
aten::random_

### ISSUE THREAD

**Issue by AIWithShrey** [pytorch/pytorch#98118]
### 🚀 The feature, motivation and pitch

Looks like this current operation is not supported on an MPS backend. Would love to see this implemented.

### Additional context

I ran into this error when I set the default device to MPS and tried training a DNN.

cc @pbelevich @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
This looks like a very trivial oversight in native_functions.yaml:
```yaml
diff --git a/aten/src/ATen/native/native_functions.yaml b/aten/src/ATen/native/native_functions.yaml
index 893715750e5..812122b3c25 100644
--- a/aten/src/ATen/native/native_functions.yaml
+++ b/aten/src/ATen/native/native_functions.yaml
@@ -8123,6 +8123,7 @@
   variants: method
   dispatch:
     CPU, CUDA: random_
+    MPS: random_mps_
     Meta: random_meta_
   autogen: random, random.out
```
