### ISSUE TITLE
Shape function for transpose convolution is incorrect

### ISSUE THREAD

**Issue by navahgar** [pytorch/pytorch#98129]
### 🐛 Describe the bug

The shape function for transposed convolution defined here  https://github.com/pytorch/pytorch/blob/master/torch/jit/_shape_functions.py#L805

```
if transposed:
            kernel = dilation_ * (weight[d] - 1)
            output_size.append((input[d] - 1) * stride[d - 2] - 2 * padding[d - 2] + kernel + 1)
```

does not include `output_padding`, whereas the shape function for this op, as defined by the documentation here https://pytorch.org/docs/stable/generated/torch.nn.ConvTranspose2d.html#torch.nn.ConvTranspose2d, includes `output_padding`. That looks like a bug. 

### Versions

This was observed while using the latest TorchMLIR, which in turn refers to these shape functions.

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by mingfeima** [comment]
@CaoE , could you please take a look at this one?

**Comment by CaoE** [comment]
Sure, I will look at it.
