### ISSUE TITLE
Wrong url in previous versions page

### ISSUE THREAD

**Issue by kylematoba** [pytorch/pytorch#98139]
### 📚 The doc issue

There's a bug at https://pytorch.org/get-started/previous-versions/, this line:

```
# CUDA 11.1
pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

### Suggest a potential alternative/fix

Should be

```
# CUDA 11.1
pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/cu111/torch_stable.html
```

cc @svekars @carljparker

**Comment by MylesJP** [comment]
I can look into this one.

**Comment by aidenfoxivey** [comment]
Hi there @svekars, just had a look through the page and it doesn't seem like this is still currently an issue. I believe #101798 and https://github.com/pytorch/pytorch.github.io/commit/ca482d4e5eaa10479bfbf8105b60d20a10e7abc4 have already covered this issue.

I think this might be a good candidate to be closed?

**Comment by kylematoba** [comment]
Agreed with @aidenfoxivey -- whatever was the problem seems to have been fixed in the intervening months.
