### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by kanza-ali** [pytorch/pytorch#9814]
## Issue description
I am new with deep learning and pytorch. This is the first project I am trying to work. 
I am training a network but when I run training commands I have the following error:

raise AssertionError("Invalid device id")
AssertionError: Invalid device id

## Code example

python3 train.py --lr 0.0003 --batch-size 80 --arch resnet152 \
        --data-name ucf101 --representation iframe \
        --data-root data/ucf101/mpeg4_videos \
        --train-list data/datalists/ucf101_split1_train.txt \
        --test-list data/datalists/ucf101_split1_test.txt \
        --model-prefix ucf101_iframe_model \
        --lr-steps 150 270 390  --epochs 510 \
        --gpus 0 1 2 3

## System Info

Processor: Intel® Xeon(R) CPU E3-1246 v3 @ 3.50GHz × 8 
Graphic: GeForce GTX 1080/PCIe/SSE2
OS: Ubuntu 16.04 (64bit)

- PyTorch 
- How you installed PyTorch: conda
- OS: Ubuntu 16.04 (64bit)
- PyTorch version: 0.4.0
- Python version: 3
- CUDA/cuDNN version: 8
- GPU models and configuration: GeForce GTX 1080/PCIe/SSE2
- GCC version (if compiling from source): 5.4.0
- CMake version:
- Versions of any other relevant libraries:

**Comment by SsnL** [comment]
can you post a minimal working example or a full trace please?

**Comment by kanza-ali** [comment]
![3](https://user-images.githubusercontent.com/33715985/43236331-82f2ff50-90bf-11e8-8005-eb3b4e4dd55a.png)

**Comment by soumith** [comment]
the code you are running must be for 2-GPU or 4-GPU and you probably have lesser GPUs than what it's hard-coded for.

In the future, post questions at https://discuss.pytorch.org
