### ISSUE TITLE
nn.Residual Module (and ParallelSum)

### ISSUE THREAD

**Issue by BorisTheBrave** [pytorch/pytorch#98165]
### 🚀 The feature, motivation and pitch

Many models feature residual blocks, aka skip connections, where some computation is done, and then the original tensor is added to the result at the end of the block. 

Also common are models where the same input is processed in two independent ways, before being summed. Residual blocks can be seen as a special case of this, where one branch is nn.Identity.

I think having a built in module for either of these setups would be very convenient. ResNet, in torchvision, for example would no longer need custom modules for BasicBlock or Bottleneck. The readability would be higher too.

I would propose syntax like:

```python
nn.Residual(
  nn.Sequential(...)
)

nn.ParallelSum(
  module1,
  module2
)
```

### Alternatives

The alternative currently is to write a custom module. While it's not much code, it is 90% boilerplate, and I think there is some clarity in having named operations for residuals.

There was a proposal for [nn.Parallel](https://github.com/pytorch/pytorch/issues/36459) which is somewhat similar to this, but it was rejected as too niche. 

I searched the issues, and couldn't find this suggestion put forward before.

### Additional context

I believe this would be fairly straightforward to implement and am happy to put together a PR if this feature is desired.

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by BorisTheBrave** [comment]
I've added a draft PR sketching this idea further.

Please let me know if it's worth pursuing (either both modules, or just Residual on its own).

**Comment by BorisTheBrave** [comment]
I've also reviewed the [Developer FAQ](https://github.com/pytorch/pytorch/wiki/Developer-FAQ#i-have-a-new-function-or-feature-id-like-to-add-to-pytorch-should-it-be-in-pytorch-core-or-a-library-like-torchvision):

> Typically a new function or feature requires an issue for discussion, followed by a consensus that the function/feature will be accepted into PyTorch Core. Good candidates for acceptance have one or more of the following properties:
> * further a current PyTorch UX or functionality goal

Convenience and readability are presumably key issues of UX.

> * are derived from frequently used and established research that's been vetted for 2+ years

I think this is clearly the case for residual connections.

> * add necessary functionality to support research that does not conflict with PyTorch's UX

This proposal doesn't add anything necessary, it is purely utility.

**Comment by cpuhrsch** [comment]
@BorisTheBrave - Thank you for your feature request. I'm wondering if you maybe even already have an example implementation for this?

**Comment by cpuhrsch** [comment]
Oh joy, I just saw that you already even sent a PR https://github.com/pytorch/pytorch/pull/98855

**Comment by cpuhrsch** [comment]
So essentially these modules implement

ParallelAdd

```
    def forward(self, input) -> torch.Tensor:
        total = None
        for module in self:
            result = module(input)
            assert isinstance(result, torch.Tensor), "forward method expects contained modules to return objects of class Tensor"
            if total is None:
                total = result
            else:
                total = total + result
```

and

Residual

```
    def forward(self, input: Tensor) -> Tensor:
        return self._modules["inner"](input) + input
```

Why not just do this by writing that Python code instead of adding a class?

**Comment by BorisTheBrave** [comment]
> Why not just do this by writing that Python code instead of adding a class?

Yes, well this is the main question that needs to be answered. The case is strongest for nn.Residual alone.

In short, because this is a common operation and it's convenient to have a shorthand for that.

To expand on that:
* Having a named object makes the code more readable. Anyone can easily identify a residual connection in unfamiliar code 
* in many circumstances (such as the torch vision code), one must make a whole module just to do the residual, significantly bloating the user's code with pointless boilerplate.
* in principal, nn.Residual could rework named parameters so it doesn't add a prefix. Ive not actually implemented this part; currently it adds "inner." to all parameters. But it's less trivial once you include this.

**Comment by albanD** [comment]
btw if you want a seamless Residual that doesn't change the params naming. You can do it in one line with a hook:
```python
mod.register_forward_hook(lambda _, ins, outs: outs + ins[0])
```

**Comment by BorisTheBrave** [comment]
@albanD @cpuhrsch 

Can I get an actual decision? I'm reluctant to continue implementing when there is a still doubt about whether it would be merged.

**Comment by LaurenceA** [comment]
I'd like to re-emphasise the importance of this.

There are lots of research situations where you'd like to transform a pre-existing model.  Adding in LoRA adapters is one easy example.  But there are others.  In my situation, I'm trying to come up with a "linear" version of an existing model by deleting the nonlinearities.  This is much _much_ easier if models aren't implemented as custom modules, and instead everything is implemented using base PyTorch modules like nn.Sequential and the proposed nn.Residual.

The problem is that at the moment real models are implemented using custom modules, because you _can't_ implement them any other way (the lack of nn.Residual or similar means you can't implement residual connections).

These days, ~all models need residual connections, we end up in a situation where ~all models are implemented as custom modules. That makes lots of things much harder, from loading models to model-surgery, to understanding / printing / visualising models: there's so much interesting stuff you can do if you can assume that no custom modules are present, and you just have to handle a small set of base PyTorch modules.

**Comment by AssafR** [comment]
> I'd like to re-emphasise the importance of this.
> 
> There are lots of research situations where you'd like to transform a pre-existing model. Adding in LoRA adapters is one easy example. But there are others. In my situation, I'm trying to come up with a "linear" version of an existing model by deleting the nonlinearities. This is much _much_ easier if models aren't implemented as custom modules, and instead everything is implemented using base PyTorch modules like nn.Sequential and the proposed nn.Residual.
> 
> The problem is that at the moment real models are implemented using custom modules, because you _can't_ implement them any other way (the lack of nn.Residual or similar means you can't implement residual connections).
> 
> These days, ~all models need residual connections, we end up in a situation where ~all models are implemented as custom modules. That makes lots of things much harder, from loading models to model-surgery, to understanding / printing / visualising models: there's so much interesting stuff you can do if you can assume that no custom modules are present, and you just have to handle a small set of base PyTorch modules.

I concur.
