### ISSUE TITLE
AttributeError: '_OpNamespace' 'aten' object has no attribute '_int_mm'

### ISSUE THREAD

**Issue by nima10khodaveisi** [pytorch/pytorch#98176]
### 🐛 Describe the bug

```torch.compile``` doesn't work properly. 

```python
import torch
from torch import nn

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        return x

model = MyModule().eval()
model = torch.compile(model, dynamic=True)

x = torch.randn([1, 512, 32, 32])
y = model(x)
print(y)
```

This is the output: 

```
Traceback (most recent call last):
  File "/Users/nimakhodaveisi/Projects/pytorch/torch/_ops.py", line 705, in __getattr__
    op, overload_names = torch._C._jit_get_operation(qualified_op_name)
RuntimeError: No such operator aten::_int_mm

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nimakhodaveisi/Projects/pytorch/test.py", line 1, in <module>
    import torch
  File "/Users/nimakhodaveisi/Projects/pytorch/torch/__init__.py", line 1621, in <module>
    from . import _meta_registrations
  File "/Users/nimakhodaveisi/Projects/pytorch/torch/_meta_registrations.py", line 1396, in <module>
    @register_meta([aten._int_mm])
  File "/Users/nimakhodaveisi/Projects/pytorch/torch/_ops.py", line 709, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'aten' object has no attribute '_int_mm'
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.10.9 (main, Mar  8 2023, 04:44:30) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M2

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.1.0a0+gitb73e8cd
[conda] numpy                     1.23.5          py310hb93e574_0  
[conda] numpy-base                1.23.5          py310haf87e8b_0  
[conda] torch                     2.1.0a0+gitb73e8cd           dev_0    <develop>

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by yanboliang** [comment]
@nima10khodaveisi I can't reproduce this with master branch, can you verify it?
