### ISSUE TITLE
UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX is not supported.

### ISSUE THREAD

**Issue by ADD-eNavarro** [pytorch/pytorch#98190]
### 🚀 The feature, motivation and pitch

Unable to export to ONNX a model that uses the operation 'aten::unflatten'.

### Alternatives

I have tried adding the operation to symbolic_opsetxx.py as per [this guide](https://pytorch.org/docs/stable/onnx.html#aten-operators), but as per [this issue](https://github.com/pytorch/pytorch/issues/97262) it seems this wouldn't suffice (it will produce a ONNX model file but it won't work).

### Additional context

So, in issue #97262  we got to use a script to register "aten::scaled_dot_product_attention" as a custom operation. 
Will need to do the same for "aten::unflatten" until it's supported in an upcoming opset version.

Here's the full script (minus the symbolic_opset18.py changes):

```python
import onnxscript
import torch

# Assuming you use opset18
from onnxscript.onnx_opset import opset18 as op

custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=18)


@onnxscript.script(custom_opset)
def ScaledDotProductAttention(
    query,
    key,
    value,
    dropout_p,
):
    # Swap the last two axes of key
    key_shape = op.Shape(key)
    key_last_dim = key_shape[-1:]
    key_second_last_dim = key_shape[-2:-1]
    key_first_dims = key_shape[:-2]
    # Contract the dimensions that are not the last two so we can transpose
    # with a static permutation.
    key_squeezed_shape = op.Concat(
        op.Constant(value_ints=[-1]), key_second_last_dim, key_last_dim, axis=0
    )
    key_squeezed = op.Reshape(key, key_squeezed_shape)
    key_squeezed_transposed = op.Transpose(key_squeezed, perm=[0, 2, 1])
    key_transposed_shape = op.Concat(key_first_dims, key_last_dim, key_second_last_dim, axis=0)
    key_transposed = op.Reshape(key_squeezed_transposed, key_transposed_shape)

    embedding_size = op.CastLike(op.Shape(query)[-1], query)
    scale = op.Div(1.0, op.Sqrt(embedding_size))

    # Scale q, k before matmul for stability see https://tinyurl.com/sudb9s96 for math
    query_scaled = op.Mul(query, op.Sqrt(scale))
    key_transposed_scaled = op.Mul(key_transposed, op.Sqrt(scale))
    attn_weight = op.Softmax(
        op.MatMul(query_scaled, key_transposed_scaled),
        axis=-1,
    )
    attn_weight, _ = op.Dropout(attn_weight, dropout_p)
    return op.MatMul(attn_weight, value)


def custom_scaled_dot_product_attention(g, query, key, value, attn_mask, dropout, is_causal, scale=None):
    return g.onnxscript_op(ScaledDotProductAttention, query, key, value, dropout).setType(query.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::scaled_dot_product_attention",
    symbolic_fn=custom_scaled_dot_product_attention,
    opset_version=18,
)

# Custom operation registered, we can produce our onnx model

from dp.model.model import load_checkpoint
from dp.phonemizer import Phonemizer
from dp.preprocessing.text import Preprocessor

model, checkpoint = load_checkpoint('latin_ipa_forward.pt')

dummy_input = {"batch": {"text":torch.rand((32,32)).long()}}

torch.onnx.export(
    model,                      # PyTorch Model
    dummy_input,                # Input tensor
    "latin_ipa_forward.onnx",   # Output file (eg. 'output_model.onnx')
    custom_opsets = {"torch.onnx": 18},           
    opset_version=18,           # Operator support version
    input_names=['embedding'],  # Input tensor name (arbitary)
    output_names=['fc_out']     # Output tensor name (arbitary)
)
```

Also @raman-r4334 may be interested in this one.

**Comment by ADD-eNavarro** [comment]
It seems there's a workaround in #49538 (I couldn't get it to work).
It seems too that it's being worked on: #97131, but still not merged.

Would be great, in the meantime, to have it as a custom operation.

**Comment by titaiwangms** [comment]
Still needs https://github.com/microsoft/onnxruntime/pull/15409,

```python
@onnxscript.script(custom_opset)
def aten_unflatten(self: TReal, dim: INT64, sizes: INT64):
    """unflatten(Tensor(a) self, int dim, SymInt[] sizes) -> Tensor(a)"""

    self_size = op.Shape(self)

    if dim < 0:
        # PyTorch accepts negative dim as reversed counting
        self_rank = op.Size(self_size)
        dim = self_rank + dim

    head_start_idx = op.Constant(value_ints=[0])
    head_end_idx = op.Reshape(dim, op.Constant(value_ints=[1]))
    head_part_rank = op.Slice(self_size, head_start_idx, head_end_idx)

    tail_start_idx = op.Reshape(dim + 1, op.Constant(value_ints=[1]))
    tail_end_idx = op.Constant(value_ints=[_INT64_MAX])
    tail_part_rank = op.Slice(self_size, tail_start_idx, tail_end_idx)

    final_shape = op.Concat(head_part_rank, sizes, tail_part_rank, axis=0)

    return op.Reshape(self, final_shape)
```

**Comment by scarletshroud** [comment]
Hello. 
When running the implementation from @ADD-eNavarro I get the following error from onnx-script:
```python
Traceback (most recent call last):
  File "J:\algorithms\MiDaS-master\tf\make_onnx_model.py", line 250, in <module>
    run(MODEL_PATH)
  File "J:\algorithms\MiDaS-master\tf\make_onnx_model.py", line 239, in run
    torch.onnx.export(model, sample, ntpath.basename(model_path).rsplit('.', 1)[0]+'.onnx',  custom_opsets = {"torch.onnx": 18}, opset_version=18)
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 506, in export
    _export(
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\utils.py", line 1891, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "J:\algorithms\MiDaS-master\tf\make_onnx_model.py", line 82, in custom_unflatten
    return g.onnxscript_op(aten_unflatten, self, dim, shape).setType(self.type())
  File "C:\Users\nooba\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\onnx\_internal\jit_utils.py", line 142, in onnxscript_op
    symbolic_name = f"{onnx_fn.opset.domain}::{onnx_fn.opname}"
AttributeError: 'OnnxFunction' object has no attribute 'opname'
```
I built onnxruntime 1.16 version from source, but it did not help. 
What can be the problem?

Additional: onnx script that I used
```python
custom_opset = onnxscript.values.Opset(domain="torch.onnx", version=18)

@onnxscript.script(custom_opset)
def aten_unflatten(self, dim, sizes):
    """unflatten(Tensor(a) self, int dim, SymInt[] sizes) -> Tensor(a)"""

    self_size = op.Shape(self)

    if dim < 0:
        # PyTorch accepts negative dim as reversed counting
        self_rank = op.Size(self_size)
        dim = self_rank + dim

    head_start_idx = op.Constant(value_ints=[0])
    head_end_idx = op.Reshape(dim, op.Constant(value_ints=[1]))
    head_part_rank = op.Slice(self_size, head_start_idx, head_end_idx)

    tail_start_idx = op.Reshape(dim + 1, op.Constant(value_ints=[1]))
    tail_end_idx = op.Constant(value_ints=[9223372036854775807]) # = sys.maxint, exactly 2^63 - 1 -> 64 bit int
    tail_part_rank = op.Slice(self_size, tail_start_idx, tail_end_idx)

    final_shape = op.Concat(head_part_rank, sizes, tail_part_rank, axis=0)

    return op.Reshape(self, final_shape)

def custom_unflatten(g, self, dim, shape):
    return g.onnxscript_op(aten_unflatten, self, dim, shape).setType(self.type().with_sizes([1, 2, 3, 4, 5])) 

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::unflatten",
    symbolic_fn=custom_unflatten,
    opset_version=18,
)
```

**Comment by titaiwangms** [comment]
@scarletshroud you can now export it with torch nightly. no need to use custom op as long as your opset version is >= 13

**Comment by scarletshroud** [comment]
@titaiwangms Thank you! It works.

**Comment by Yshuo-Li** [comment]
> Still needs [microsoft/onnxruntime#15409](https://github.com/microsoft/onnxruntime/pull/15409),
> 
> ```python
> @onnxscript.script(custom_opset)
> def aten_unflatten(self: TReal, dim: INT64, sizes: INT64):
>     """unflatten(Tensor(a) self, int dim, SymInt[] sizes) -> Tensor(a)"""
> 
>     self_size = op.Shape(self)
> 
>     if dim < 0:
>         # PyTorch accepts negative dim as reversed counting
>         self_rank = op.Size(self_size)
>         dim = self_rank + dim
> 
>     head_start_idx = op.Constant(value_ints=[0])
>     head_end_idx = op.Reshape(dim, op.Constant(value_ints=[1]))
>     head_part_rank = op.Slice(self_size, head_start_idx, head_end_idx)
> 
>     tail_start_idx = op.Reshape(dim + 1, op.Constant(value_ints=[1]))
>     tail_end_idx = op.Constant(value_ints=[_INT64_MAX])
>     tail_part_rank = op.Slice(self_size, tail_start_idx, tail_end_idx)
> 
>     final_shape = op.Concat(head_part_rank, sizes, tail_part_rank, axis=0)
> 
>     return op.Reshape(self, final_shape)
> ```

Excuse me, what is ''op''?

**Comment by rudransh2004** [comment]
This is an issue with the pytorch2.0 version, In my case, I simply downgraded to pytorch 1.13.1 and it worked with the opset version of 11

**Comment by ArnyWu** [comment]
`python=`
import onnxscript
from onnxscript.onnx_opset import opset18 as op
# Assuming you use opset18
import torch
import onnx
import torch.onnx
custom_opset = onnxscript.values.Opset(domain="torch_onnx", version=18)


# 定義自定義 'LGamma' 操作
@onnxscript.script(custom_opset)
def LGamma(X):
    abs_gamma_x = op.Abs(X)
    output = op.Log(abs_gamma_x)
    return output

# 定義 'custom_lgamma' 函數
def custom_lgamma(g, X):
    return g.onnxscript_op(LGamma, X).setType(X.type())

# 註冊 'custom_lgamma' 函數，使用 'aten::lgamma' 作為 symbolic_name
torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::lgamma",  # 使用 'aten::lgamma' 作為 symbolic_name
    symbolic_fn=custom_lgamma,
    opset_version=18,  # 與您的 opset 版本一致
)


# 定義自定義'unflatten'操作
@onnxscript.script(custom_opset)
def aten_unflatten(self, dim, sizes):
    """unflatten(Tensor(a) self, int dim, SymInt[] sizes) -> Tensor(a)"""

    self_size = op.Shape(self)

    if dim < 0:
        # PyTorch accepts negative dim as reversed counting
        self_rank = op.Size(self_size)
        dim = self_rank + dim

    head_start_idx = op.Constant(value_ints=[0])
    head_end_idx = op.Reshape(dim, op.Constant(value_ints=[1]))
    head_part_rank = op.Slice(self_size, head_start_idx, head_end_idx)

    tail_start_idx = op.Reshape(dim + 1, op.Constant(value_ints=[1]))
    #tail_end_idx = op.Constant(value_ints=[_INT64_MAX])
    tail_end_idx = op.Constant(value_ints=[9223372036854775807]) # = sys.maxint, exactly 2^63 - 1 -> 64 bit int
    tail_part_rank = op.Slice(self_size, tail_start_idx, tail_end_idx)

    final_shape = op.Concat(head_part_rank, sizes, tail_part_rank, axis=0)

    return op.Reshape(self, final_shape)

def custom_unflatten(g, *dim, **shape):
    return g.onnxscript_op(aten_unflatten, *dim, **shape)    

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::unflatten",
    symbolic_fn=custom_unflatten,
    opset_version=18,
)


# 定義自定義'scaled_dot_product_attention'操作
@onnxscript.script(custom_opset)
def ScaledDotProductAttention(
    query,
    key,
    value,
    dropout_p,
):
    # Swap the last two axes of key
    key_shape = op.Shape(key)
    key_last_dim = key_shape[-1:]
    key_second_last_dim = key_shape[-2:-1]
    key_first_dims = key_shape[:-2]
    key_squeezed_shape = op.Concat(
        op.Constant(value_ints=[-1]), key_second_last_dim, key_last_dim, axis=0
    )
    key_squeezed = op.Reshape(key, key_squeezed_shape)
    key_squeezed_transposed = op.Transpose(key_squeezed, perm=[0, 2, 1])
    key_transposed_shape = op.Concat(key_first_dims, key_last_dim, key_second_last_dim, axis=0)
    key_transposed = op.Reshape(key_squeezed_transposed, key_transposed_shape)

    embedding_size = op.CastLike(op.Shape(query)[-1], query)
    scale = op.Div(1.0, op.Sqrt(embedding_size))

    # Scale q, k before matmul for stability see https://tinyurl.com/sudb9s96 for math
    query_scaled = op.Mul(query, op.Sqrt(scale))
    key_transposed_scaled = op.Mul(key_transposed, op.Sqrt(scale))
    attn_weight = op.Softmax(
        op.MatMul(query_scaled, key_transposed_scaled),
        axis=-1,
    )
    attn_weight, _ = op.Dropout(attn_weight, dropout_p)
    return op.MatMul(attn_weight, value)


def custom_scaled_dot_product_attention(g, query, key, value, attn_mask, dropout, is_causal, scale=None):
    return g.onnxscript_op(ScaledDotProductAttention, query, key, value, dropout).setType(query.type())

torch.onnx.register_custom_op_symbolic(
    symbolic_name="aten::scaled_dot_product_attention",
    symbolic_fn=custom_scaled_dot_product_attention,
    opset_version=18,
)

**Comment by Jingranxia** [comment]
> This is an issue with the pytorch2.0 version, In my case, I simply downgraded to pytorch 1.13.1 and it worked with the opset version of 11
it work, great!
