### ISSUE TITLE
cuda related *.so files are missing in torch 2.0.0+cu117 whl

### ISSUE THREAD

**Issue by Ps7ch3** [pytorch/pytorch#98196]
### 🐛 Describe the bug

It seems that some cuda-related so files are missing in the 2.0.0+cuda117 version of the package.

```
# 1.13.1 whl
$ unzip -l torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl | grep libtorch_cuda_cpp
264587265  12-09-2022 04:40   torch/lib/libtorch_cuda_cpp.so
# 2.0.0 whl
$ unzip -l torch-2.0.0+cu117-cp38-cp38-linux_x86_64.whl | grep libtorch_cuda_cpp

# 1.13.1 whl
$ unzip -l torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl | grep libtorch_cuda_cu.so
741315209  12-09-2022 04:40   torch/lib/libtorch_cuda_cu.so
# 2.0.0 whl
$ unzip -l torch-2.0.0+cu117-cp38-cp38-linux_x86_64.whl | grep libtorch_cuda_cu.so
```

```
# install from https://download.pytorch.org/whl/cu117
$ pip3 install torch==1.13.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
$ pip3 install torch==2.0.0+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

# *.whl sha1sum
$ sha1sum *
6bb496242931a6223d5db12c0704034f35a6ef56  torch-1.13.1+cu117-cp38-cp38-linux_x86_64.whl
de42494c456955d5e8f6345e0a79b87518722624  torch-2.0.0+cu117-cp38-cp38-linux_x86_64.whl
```

### Versions

torch-2.0.0+cu117

**Comment by michaelroyzen** [comment]
has this been fixed?

**Comment by Ps7ch3** [comment]
@michaelroyzen I have no idea... This issue was closed only because I found these *.so files not needed for faster transformer compilation if torch v2.0.0 installed.

**Comment by huijiawu0** [comment]
Actually some memory efficient methods such as FlashAttn need libtorch_cuda_cpp.so to execute, and the models using FlashAttn may not compile with torch v2.0.0+.

**Comment by michaelroyzen** [comment]
yep, using flash attention with torch v2.0+ is exactly why this is an issue for me.

**Comment by dongfeicui** [comment]
https://github.com/commaai/apex/releases
https://github.com/commaai/apex/releases/download/pytorch2.0.0%2Bcu11.8/apex-0.1-cp38-cp38-linux_x86_64.whl
