### ISSUE TITLE
Pytorch 2.0.0 Release - Resources to download

### ISSUE THREAD

**Issue by Bronomor** [pytorch/pytorch#98206]
Could you add the .tar.gz package to the 2.0.0 release with the all submodule files included? In all previeus version there were three type of assets, but in version 2.0.0 we only have source code packages in resources.

cc @seemethere @malfet @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by Bronomor** [comment]
Yes, It is in the github releases. 
https://github.com/pytorch/pytorch/releases/tag/v2.0.0 
Inside into assets section is missing something like pytorch-v2.0.0.tar.gz

**Comment by malfet** [comment]
Ok, so there is an automation in place for the release, but the job were cancelled for 2.0 release, see https://github.com/pytorch/pytorch/actions/runs/4430269832/attempts/1, re-started it
