### ISSUE TITLE
`Tensor.uniform_` misses `generator` arg

### ISSUE THREAD

**Issue by albertz** [pytorch/pytorch#98202]
### 📚 The doc issue

https://pytorch.org/docs/stable/generated/torch.Tensor.uniform_.html

It just specifies the signature `Tensor.uniform_(from=0, to=1) → Tensor` but actually it also supports the `generator` argument.

### Suggest a potential alternative/fix

Add `generator` to the arguments.

cc @svekars @carljparker @pbelevich

**Comment by soulitzer** [comment]
Thanks for the report, we'd accept a PR to fix this. @albertz do you think you'd be interested?
