### ISSUE TITLE
onnx.export bug : Exporting the operator 'aten::diag' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: 

### ISSUE THREAD

**Issue by Sigrid-Z** [pytorch/pytorch#98205]
### 🐛 Describe the bug

I've already updated pytorch to the newest 2.0.0, but when I try onnx.export with different  opset versions:
Exception has occurred: UnsupportedOperatorError
Exporting the operator 'aten::diag' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

### Versions

Exception has occurred: UnsupportedOperatorError
Exporting the operator 'aten::diag' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by liqunfu** [comment]
needs to add an onnx_symbolic function for "diag" with this logic: input * torch.eye(len(input))

**Comment by Sigrid-Z** [comment]
Solved, thank you
