### ISSUE TITLE
torch.nn.functional.linear throws different exception information on different devices

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#98211]
### 🐛 Describe the bug

torch.nn.functional.linear throws different exception information on different devices

Test on the CPU:

    import torch
    in_features = 128
    out_features = 1
    weight = torch.rand(out_features, in_features)
    bias = torch.rand(out_features)
    input = torch.rand([302], dtype=torch.float32)
    output = torch.nn.functional.linear(input, weight, bias)
    print(output)

result: RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x302 and 128x1)

Test on the GPU:

    import torch
    in_features = 128
    out_features = 1
    weight = torch.rand(out_features, in_features).cuda()
    bias = torch.rand(out_features).cuda()
    input = torch.rand([302], dtype=torch.float32).cuda()
    output = torch.nn.functional.linear(input, weight, bias)
    print(output)

result: RuntimeError: mat1 dim 1 must match mat2 dim 0

### Versions

pytorch: 1.8.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
Operating System：Windows

cc @malfet @kulinseth @albanD @DenisVieriu97 @razarmehr @abhudev

**Comment by triumph-wangyuyang** [comment]
The same problem exists with torch.nn.Linear

Test on the CPU:

    import torch
    m = torch.nn.Linear(in_features=128, out_features=1)
    input = torch.rand([302], dtype=torch.float32)
    print(m(input))

result: RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x302 and 128x1)

Test on the GPU:

    import torch
    m = torch.nn.Linear(in_features=128, out_features=1).cuda()
    input = torch.rand([302], dtype=torch.float32).cuda()
    print(m(input))

result: RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by pat749** [comment]
The difference in the error messages on CPU and GPU might be due to different implementations of matrix multiplication on these devices. However, the root cause of the error is the same. You can try to transpose the weight tensor to match the shapes of the input and weight tensors.
Here is the code which is throwing same error on different version(CPU, GPU) : 
```
import torch
in_features = 128
out_features = 1
weight = torch.rand(in_features, out_features) # Transpose the weight tensor
bias = torch.rand(out_features)
input = torch.rand([302], dtype=torch.float32)
output = torch.nn.functional.linear(input, weight, bias)
print(output)
```

Here is the correct code: 
```
import torch

in_features = 128
out_features = 1
weight = torch.rand(out_features, in_features)
bias = torch.rand(out_features)
input = torch.rand([302, in_features], dtype=torch.float32)
output = torch.nn.functional.linear(input, weight, bias)

print(output)
```
Here is the implementation in [google colab](https://colab.research.google.com/drive/1s09aCm6tBNU3Rom5i8YQWU5HXF_W9Zy-?usp=sharing) , please see it . 
Thank you

**Comment by triumph-wangyuyang** [comment]
> The difference in the error messages on CPU and GPU might be due to different implementations of matrix multiplication on these devices. However, the root cause of the error is the same. You can try to transpose the weight tensor to match the shapes of the input and weight tensors. Here is the code which is throwing same error on different version(CPU, GPU) :
> 
> ```
> import torch
> in_features = 128
> out_features = 1
> weight = torch.rand(in_features, out_features) # Transpose the weight tensor
> bias = torch.rand(out_features)
> input = torch.rand([302], dtype=torch.float32)
> output = torch.nn.functional.linear(input, weight, bias)
> print(output)
> ```
> 
> Here is the correct code:
> 
> ```
> import torch
> 
> in_features = 128
> out_features = 1
> weight = torch.rand(out_features, in_features)
> bias = torch.rand(out_features)
> input = torch.rand([302, in_features], dtype=torch.float32)
> output = torch.nn.functional.linear(input, weight, bias)
> 
> print(output)
> ```
> 
> Here is the implementation in [google colab](https://colab.research.google.com/drive/1s09aCm6tBNU3Rom5i8YQWU5HXF_W9Zy-?usp=sharing) , please see it . Thank you

Thank you, but what I mentioned above is indeed a problem with the operator itself.

**Comment by pat749** [comment]
@triumph-wangyuyang Yes that is indeed a problem

**Comment by laclouis5** [comment]
I encountered a similar issue when using `torch.nn.Linear` using a MPS device (Apple GPU). When there is a size mismatch on this device, this results in a segmentation fault:

```
(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:39:0: error: 'mps.matmul' op contracting dimensions differ 64 & 32
(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:39:0: note: see current operation: %6 = "mps.matmul"(%arg0, %4) {transpose_lhs = false, transpose_rhs = false} : (tensor<2x64xf32>, tensor<32x4xf32>) -> tensor<2x4xf32>
[1]    70937 segmentation fault  python
```

Code to reproduce:

```python
import torch

x = torch.randn(2, 32, device="mps")
l = torch.nn.Linear(64, 4, device="mps")
y = l(x)
```

Environment:

```
PyTorch version: 2.0.0
Python version: 3.10.9
Computer Model: MacBook Pro M1 Pro
Operating System: macOS 13.3 Ventura
```

**Comment by ezyang** [comment]
The mps thing is a legit bug and should get fixed. However, we don't guarantee the same error message across different backends, just that we will consistently report SOME error if there is a problem.
