### ISSUE TITLE
Wrong results for GELU forward pass (CPU vs MPS) while  inferencing a GLPN model from huggingface

### ISSUE THREAD

**Issue by arybnikov** [pytorch/pytorch#98212]
### 🐛 Describe the bug

Hi, there. I've discovered strange behaviour when using MPS device. When infer the same model with the same input on "mps" device, the result is numerically wrong and meaningless. 
@amyeroberts from huggingface narrowed down the scope of the problem to GELU layer, more information is here: https://github.com/huggingface/transformers/issues/22468

The issue makes it impossible to use GLPN architecture with MPS device.

Here are some examples:

MPS            |  CPU
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/126671893/228804909-71194936-a266-4511-9ae0-1c667f762faa.png)  |  ![](https://user-images.githubusercontent.com/126671893/228804919-9916e01f-f4cd-43a2-be74-a7cb8eeb9c6f.png)

Thanks in advance for the help!

### Versions

PyTorch version: 2.1.0.dev20230329
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Mar 10 2023, 20:16:38)  [Clang 14.0.3 (clang-1403.0.22.14.1)] (64-bit runtime)
Python platform: macOS-13.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Max

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0.dev20230329
[pip3] torchaudio==2.1.0.dev20230329
[pip3] torchvision==0.16.0.dev20230329
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment]
Taking an AI to simplify the repro

**Comment by velaia** [comment]
This is still an issue. I've been trying to use 🤗 GLPN model on MPS and my depth map looks like this:

![image](https://github.com/pytorch/pytorch/assets/1515904/c88a18d4-6bdd-420c-9c60-879ef1a601bf)

The corresponding 🤗 issue is here: https://github.com/huggingface/transformers/issues/22468

**Comment by jparismorgan** [comment]
Hi there, we are also being impacted by the issue here: https://github.com/RaymondWang987/NVDS/issues/28

But like others have said, changing from `F.gelu(x)` to `F.gelu(x.contiguous())` fixed the issue, so we are not blocked (though other users who cannot find this GitHub issue may be).
