### ISSUE TITLE
[bug/feature request] Slice export not propagating negative indexes

### ISSUE THREAD

**Issue by cbecker** [pytorch/pytorch#9822]
## Issue description
When exporting a pytorch model to ONNX that contains a slice operation with negative indexes, i.e.
```
class MyModel(nn.Module):
    def forward(self, x):
        return x[:, :, :, 1:-1]
```

Then the ONNX slice operation does not contain the negative indexes, but are instead replaced by positive indexes depending on the input's size at the time of the trace/export.

This can be very limiting because in the case of FCNNs that use a crop or other slicing operation it means that one is bound to a single patch size, as the slicing won't adapt correctly to inputs with different sizes.

I went through the python code and the tracer, and so far it looks like the issue is within the torch C/C++ code. I would be glad to contribute if someone can point me to where to look, and also if this is an issue we want to tackle or a desired behavior.

## Code example
Running
```
import torch
import torch.onnx as tonnx
import torch.nn as nn
from torch.autograd import Variable

class MyModel(nn.Module):
    def forward(self, x):
        return x[:, :, :, 1:-1]

dummy_input = Variable(torch.randn(1, 3, 224, 224))
model = MyModel()

tonnx.export(model, dummy_input, "/tmp/model.onnx", verbose=True)
```

yields:
```
graph(%0 : Float(1, 3, 224, 224)) {
  %1 : Float(1, 3, 224!, 222) = onnx::Slice[axes=[3], ends=[223], starts=[1]](%0), scope: MyModel
  return (%1);
}
```

I would expect `ends` to be `[-1]` instead of `[223]`.

This is on the latest install with pip.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by soumith** [comment]
cc: @houseroad

**Comment by garymm** [comment]
This seems to have been fixed at some point.

The same model being exported now shows negative indices being preserved:
```
graph(%0 : Float(1, 3, 224, 224, strides=[150528, 50176, 224, 1], requires_grad=0, device=cpu)):
  %1 : Float(1, 3, 224, 222, strides=[150528, 50176, 224, 1], requires_grad=0, device=cpu) = onnx::Slice[axes=[3], ends=[-1], starts=[1]](%0) # <ipython-input-14-26c5a257312a>:5:0
  return (%1)
```

Please re-open if this is still an issue on pytorch latest nightly.
