### ISSUE TITLE
inductor `compile_fx_inner()` segfaults on `torch.isinf`

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#98237]
minimal repro:
```
import torch
from torch._inductor.compile_fx import compile_fx_inner
from torch._subclasses import FakeTensorMode
from torch.fx.experimental.proxy_tensor import make_fx

def f(x):
    isinf = torch.isinf(x)
    return [isinf]

with FakeTensorMode():
    inp = torch.ones(2048, device='cuda')
    fx_g = make_fx(f)(inp)
    fx_inner = compile_fx_inner(fx_g, [inp])
```

This fails with:
```
  File "/tmp/torchinductor_hirsheybar/3h/c3hkvftvlgct3scdmbgllet56gcfozfyloqidc57nlxmixrk5ioq.py", line 45, in <module>
    async_compile.wait(globals())
  File "/scratch/hirsheybar1/work/pytorch/torch/_inductor/codecache.py", line 876, in wait
    scope[key] = result.result()
  File "/scratch/hirsheybar1/work/pytorch/torch/_inductor/codecache.py", line 734, in result
    self.future.result()
  File "/scratch/hirsheybar1/work/py38/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/scratch/hirsheybar1/work/py38/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by bdhirsh** [comment]
When I set `torch._inductor.config.compile_threads = 1`, then I get a proper segfault (my understanding is that this removes the async bit of inductor compile process).

**Comment by desertfire** [comment]
What "proper" error msg are you seeing? I can't reproduce with the latest master code.

**Comment by bdhirsh** [comment]
hmm I am in fact on a branch, although I don't think I made any real inductor changes in it. Thanks, I'll see if I can repro on master / if it's an issue with my environment.

> What "proper" error msg are you seeing

Just that it segfaults (with "invald pointer"):
```
realloc(): invalid pointer
Aborted (core dumped)
```

**Comment by bdhirsh** [comment]
@desertfire I actually am able to repro this on master (I made sure to nuke my inductor cache and re-install triton based off the the pinned commit hash). Which commit were you running on?

pytorch commit: 8e5f57a2b19104a32f5423804a3fe93be76927b0
triton commit: 46672772b46b103db7341c9e10fbad7f643557d4

**Comment by desertfire** [comment]
I updated to the same commit as yours, but still can't reproduce. @eellison also helped to run but can't reproduce either. If it happens in `async_compile`, I suppose it is a triton issue. Not sure how you installed triton, but can you run `make triton` locally and that may do a "proper" triton installation?
