### ISSUE TITLE
Pytorch Install error -Segmentation Fault 

### ISSUE THREAD

**Issue by srams2018** [pytorch/pytorch#9824]
Configuration Info:-
# python /data/apps/pytorch/torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Server 7.2 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
CMake version: version 3.5.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5.0.5
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn_static.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.3
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.12.1)
[pip3] numpydoc (0.6.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] magma-cuda90              2.3.0                         1    soumith
[conda] torch                     0.4.0                     <pip>
[conda] torchvision               0.2.1                     <pip>

========================================
# python setup.py install
running install
running build_deps
+ USE_CUDA=0
+ USE_ROCM=0
+ USE_NNPACK=0
+ USE_MKLDNN=0
+ USE_GLOO_IBVERBS=0
+ USE_DISTRIBUTED_MW=0
+ FULL_CAFFE2=0
+ [[ 9 -gt 0 ]]
+ case "$1" in
+ USE_CUDA=1
+ shift
+ [[ 8 -gt 0 ]]
+ case "$1" in
+ USE_NNPACK=1
+ shift
+ [[ 7 -gt 0 ]]
+ case "$1" in
+ break
+ CMAKE_INSTALL='make install'
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ uname
+ '[' Linux == Darwin ']'
++ dirname tools/build_pytorch_libs.sh
+ cd tools/..
+++ pwd
++ printf '%q\n' /data/apps/pytorch
+ PWD=/data/apps/pytorch
+ BASE_DIR=/data/apps/pytorch
+ TORCH_LIB_DIR=/data/apps/pytorch/torch/lib
+ INSTALL_DIR=/data/apps/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/data/apps/pytorch/third_party
+ CMAKE_VERSION=cmake
+ C_FLAGS=' -I"/data/apps/pytorch/torch/lib/tmp_install/include"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/TH" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THC"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THS" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCS"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THNN" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCUNN"'
+ C_FLAGS=' -I"/data/apps/pytorch/torch/lib/tmp_install/include"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/TH" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THC"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THS" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCS"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THNN" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS='-L"/data/apps/pytorch/torch/lib/tmp_install/lib" '
+ LD_POSTFIX=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ LDFLAGS='-L"/data/apps/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ GLOO_FLAGS=
+ THD_FLAGS=
+ NCCL_ROOT_DIR=/data/apps/pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR=/data/apps/pytorch/torch/lib/tmp_install'
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ CWRAP_FILES='/data/apps/pytorch/torch/lib/ATen/Declarations.cwrap;/data/apps/pytorch/torch/lib/THNN/generic/THNN.h;/data/apps/pytorch/torch/lib/THCUNN/generic/THCUNN.h;/data/apps/pytorch/torch/lib/ATen/nn.yaml'
+ CUDA_NVCC_FLAGS=' -I"/data/apps/pytorch/torch/lib/tmp_install/include"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/TH" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THC"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THS" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCS"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THNN" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ [[ -z '' ]]
+ CUDA_DEVICE_DEBUG=0
+ '[' -z 48 ']'
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p torch/lib/tmp_install
+ for arg in '"$@"'
+ [[ nccl == \n\c\c\l ]]
+ pushd /data/apps/pytorch/third_party
/data/apps/pytorch/third_party /data/apps/pytorch
+ build_nccl
+ mkdir -p build/nccl
+ pushd build/nccl
/data/apps/pytorch/third_party/build/nccl /data/apps/pytorch/third_party /data/apps/pytorch
+ cmake ../../nccl -DCMAKE_MODULE_PATH=/data/apps/pytorch/cmake/Modules_CUDA_fix -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/data/apps/pytorch/torch/lib/tmp_install '-DCMAKE_C_FLAGS= -I"/data/apps/pytorch/torch/lib/tmp_install/include"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/TH" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THC"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THS" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCS"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THNN" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1 ' '-DCMAKE_CXX_FLAGS= -I"/data/apps/pytorch/torch/lib/tmp_install/include"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/TH" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THC"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THS" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCS"   -I"/data/apps/pytorch/torch/lib/tmp_install/include/THNN" -I"/data/apps/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1  -std=c++11  ' -DCMAKE_SHARED_LINKER_FLAGS= -DCMAKE_UTILS_PATH=/data/apps/pytorch/cmake/public/utils.cmake -DNUM_JOBS=48
-- Autodetected CUDA architecture(s): 6.0 6.0 6.0 6.0
-- Set NVCC_GENCODE for building NCCL: -gencode=arch=compute_60,code=sm_60
-- Configuring done
-- Generating done
-- Build files have been written to: /data/apps/pytorch/third_party/build/nccl
+ make install -j48
[100%] Built target nccl
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /data/apps/pytorch/torch/lib/tmp_install/include/nccl.h
+ mkdir -p /data/apps/pytorch/torch/lib/tmp_install/lib
+ cp lib/libnccl.so.1 /data/apps/pytorch/torch/lib/tmp_install/lib/libnccl.so.1
+ '[' '!' -f /data/apps/pytorch/torch/lib/tmp_install/lib/libnccl.so ']'
+ popd
/data/apps/pytorch/third_party /data/apps/pytorch
+ popd
/data/apps/pytorch
+ for arg in '"$@"'
+ [[ caffe2 == \n\c\c\l ]]
+ [[ caffe2 == \g\l\o\o ]]
+ [[ caffe2 == \c\a\f\f\e\2 ]]
+ pushd /data/apps/pytorch
/data/apps/pytorch /data/apps/pytorch
+ build_caffe2
+ [[ -z '' ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS=()
+ [[ -n '' ]]
+ [[ -n /data/anaconda/4.3.1/3/lib/python3.6/site-packages ]]
+ EXTRA_CAFFE2_CMAKE_FLAGS+=("-DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH")
+ mkdir -p build
+ pushd build
/data/apps/pytorch/build /data/apps/pytorch /data/apps/pytorch
+ cmake .. -DBUILDING_WITH_TORCH_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CAFFE2=0 -DBUILD_TORCH=ON -DBUILD_ATEN=ON -DBUILD_PYTHON=0 -DBUILD_BINARY=OFF -DBUILD_SHARED_LIBS=ON -DONNX_NAMESPACE=onnx_torch -DUSE_CUDA=1 -DUSE_ROCM=0 -DUSE_NNPACK=1 -DCUDNN_INCLUDE_DIR=/usr/local/cuda/include -DCUDNN_LIB_DIR=/usr/local/cuda/lib64 -DCUDNN_LIBRARY=/usr/local/cuda/lib64/libcudnn.so.7 -DUSE_MKLDNN=0 -DMKLDNN_INCLUDE_DIR= -DMKLDNN_LIB_DIR= -DMKLDNN_LIBRARY= -DCMAKE_INSTALL_PREFIX=/data/apps/pytorch/torch/lib/tmp_install -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= '-DCMAKE_EXE_LINKER_FLAGS=-L"/data/apps/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN ' '-DCMAKE_SHARED_LINKER_FLAGS=-L"/data/apps/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN ' -DCMAKE_PREFIX_PATH=/data/anaconda/4.3.1/3/lib/python3.6/site-packages
-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64
-- Performing Test CAFFE2_LONG_IS_INT32_OR_64 - Success
-- Does not need to define long separately.
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE
-- Performing Test CAFFE2_IS_NUMA_AVAILABLE - Failed
-- NUMA is not available
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Failed
-- Turning off deprecation warning due to glog.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extention. Will build perfkernels.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
tools/build_pytorch_libs.sh: line 239: 53362 Segmentation fault      ${CMAKE_VERSION} .. ${CMAKE_GENERATOR} -DBUILDING_WITH_TORCH_LIBS=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_CAFFE2=$FULL_CAFFE2 -DBUILD_TORCH=$BUILD_TORCH -DBUILD_ATEN=ON -DBUILD_PYTHON=$FULL_CAFFE2 -DBUILD_BINARY=OFF -DBUILD_SHARED_LIBS=ON -DONNX_NAMESPACE=$ONNX_NAMESPACE -DUSE_CUDA=$USE_CUDA -DUSE_ROCM=$USE_ROCM -DUSE_NNPACK=$USE_NNPACK -DCUDNN_INCLUDE_DIR=$CUDNN_INCLUDE_DIR -DCUDNN_LIB_DIR=$CUDNN_LIB_DIR -DCUDNN_LIBRARY=$CUDNN_LIBRARY -DUSE_MKLDNN=$USE_MKLDNN -DMKLDNN_INCLUDE_DIR=$MKLDNN_INCLUDE_DIR -DMKLDNN_LIB_DIR=$MKLDNN_LIB_DIR -DMKLDNN_LIBRARY=$MKLDNN_LIBRARY -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_FLAGS="$USER_CFLAGS" -DCMAKE_CXX_FLAGS="$USER_CFLAGS" -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS $USER_LDFLAGS" -DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS $USER_LDFLAGS" ${EXTRA_CAFFE2_CMAKE_FLAGS[@]}
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack nccl caffe2 nanopb libshm gloo THD c10d'

Appreciate if there is any fix for the above error. Even with pip install ,iam getting segmentation fault while running pytorch python programs.

**Comment by soumith** [comment]
`Segmentation fault ${CMAKE_VERSION} .. ` when running CMake / gcc, that just looks fundamentally broken. I dont have an idea of what's going on. Try upgrading your CMake and see if it helps. Use a different compiler, maybe gcc 4.9.2 from [devtoolset-3](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-3/)

**Comment by srams2018** [comment]
Thanks @soumith .it worked with latest cmake.
