### ISSUE TITLE
hf_Longformer regression caused by https://github.com/pytorch/pytorch/pull/98119

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#98268]
Bisect points to https://github.com/pytorch/pytorch/pull/98119 and reverting it makes the error go away.

Repro:
```
python benchmarks/dynamo/torchbench.py  --inductor --amp --training --accuracy  --device cuda --only hf_Longformer
```

Error msg:
```
ValueError: Cannot view a tensor with shape torch.Size([4, 12, 1024, 513]) and strides (6303744, 513, 6156, 1) as a tensor with shape (48, 4, 256, 513)!
```

Q: Why is this not caught by CI?
A: Because `hf_Longformer` uses more than 24GB GPU memory, it is currently skipped on CI. I will fix this by running larger models on A100 instances.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by jansel** [comment]
Did you try the minifier on this one?

**Comment by desertfire** [comment]
> Did you try the minifier on this one?

Yeah, but unfortunately, minifier didn't work.
```
RuntimeError: Input graph did not fail the tester
```

**Comment by Vitor-Almeida** [comment]
I'm having this exact issue. Does anyone know what could be causing it? I've tried looking it breefly but got nowhere.

**Comment by desertfire** [comment]
@anijain2305 , have you looked into this one as a part of the coverage bringup?

**Comment by bdhirsh** [comment]
I tested locally on my fix for inductor's `copy()` lowering ([PR](https://github.com/pytorch/pytorch/pull/100115)), and it fixes this issue.
