### ISSUE TITLE
[Inductor] [CPU] Huggingface model BartForCausalLM & MBartForCausalLM & OPTForCausalLM & PLBartForCausalLM performance regression > 10% on 2023-04-02 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#98273]
### 🐛 Describe the bug

Compare with the 2023-03-29, there is a performance regression on huggingface model**BartForCausalLM & MBartForCausalLM & OPTForCausalLM & PLBartForCausalLM** on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1495275117) on 2023-04-02 as bellow:

|     |  2023-04-02  |   |     |   |  2023-03-29  |   |     |   |  Result Comp  |     |   |
|  ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| model  | batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
| BartForCausalLM	| 1	| 0.8682	| 3.6489689	| 3.168034799	| 1	| 1.0814	| 2.9063651	| 3.142943219	| 0.8	| 0.99	| 0.8
| MBartForCausalLM	| 1	| 0.8722	| 3.6418691	| 3.176438229	| 1	| 1.08	| 2.9201856	| 3.153800448	| 0.81	| 0.99	| 0.8
| OPTForCausalLM	| 1	| 0.7925	| 7.1054617	| 5.631078397	| 1	| 1.1534	| 4.8903451	| 5.640524038	| 0.69	| 1	| 0.69
| PLBartForCausalLM	| 1	| 0.8884	| 1.4350074	| 1.274860574	| 1	| 1.1012	| 1.1629979	| 1.280693287	| 0.81	| 1	| 0.81

2023-04-02 nightly release SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[5775e1c1](https://github.com/pytorch/pytorch/commit/5775e1c1)|[7fcff01](https://github.com/pytorch/pytorch/commit/7fcff01)
Torchbench|/|[83a316df](https://github.com/pytorch/benchmark/commit/83a316df)
torchaudio|[375e751](https://github.com/pytorch/audio/commit/375e751)|[a8f4e97](https://github.com/pytorch/audio/commit/a8f4e97)
torchtext|[9749082](https://github.com/pytorch/text/commit/9749082)| [46e7eef](https://github.com/pytorch/text/commit/46e7eef)
torchvision|[8d15ca7](https://github.com/pytorch/vision/commit/8d15ca7)|[98c5815](https://github.com/pytorch/vision/commit/98c5815)
torchdata|[b3048d5](https://github.com/pytorch/data/commit/b3048d5)|[f1283eb](https://github.com/pytorch/data/commit/f1283eb)
dynamo_benchmarks|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|/

2023-03-29 nightly release SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[f1f0a4f](https://github.com/pytorch/pytorch/commit/f1f0a4f)|[91166ef](https://github.com/pytorch/pytorch/commit/91166ef)
Torchbench|/|[83a316df](https://github.com/pytorch/benchmark/commit/83a316df)
torchaudio|[375e751](https://github.com/pytorch/audio/commit/375e751)|[a8f4e97](https://github.com/pytorch/audio/commit/a8f4e97)
torchtext|[9749082](https://github.com/pytorch/text/commit/9749082)| [46e7eef](https://github.com/pytorch/text/commit/46e7eef)
torchvision|[8d15ca7](https://github.com/pytorch/vision/commit/8d15ca7)|[98c5815](https://github.com/pytorch/vision/commit/98c5815)
torchdata|[b3048d5](https://github.com/pytorch/data/commit/b3048d5)|[f1283eb](https://github.com/pytorch/data/commit/f1283eb)
dynamo_benchmarks|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|/

Graph dump by cosim:

### Versions

Minified repro:

```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/huggingface.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only BartForCausalLM  --cold_start_latency --batch_size 1 --threads 1
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @soumith @ngimel @Xia-Weiwen @desertfire

**Comment by zxd1997066** [comment]
These four models have the same suspected guilty commit: https://github.com/pytorch/pytorch/commit/6b319d152525c002d8cf87a2a1845c0599c1530a
[huggingface-BartForCausalLM-inference-float32-static-default-performance-single-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14443290/huggingface-BartForCausalLM-inference-float32-static-default-performance-single-drop_guilty_commit.log)

**Comment by jiayisunx** [comment]
The guilty commit(https://github.com/pytorch/pytorch/commit/6b319d152525c002d8cf87a2a1845c0599c1530a) fixed a type of the frequent graph breaks in HF models, resulting in a significant reduction in the number of graph breaks in HF models, but the code-gen kernels generated by Inductor based on the more complete FX graph are not well vectorized, which leads to performance regression. But the latest PyTorch no longer has this problem, and there is no obvious regression anymore.

The following are the benchmark results on 2024_03_04. Compare with the benchmark results on 2023-03-29, the performance regression on the four huggingface models (BartForCausalLM & MBartForCausalLM & OPTForCausalLM & PLBartForCausalLM) are both less than 10%.
model  | batch_size  | speedup | inductor  | eager
  ----  |  ----  | ----  |  ----  | ----  
| BartForCausalLM	  | 1	| 0.8682	| 3.6489689	| 3.168034799
| MBartForCausalLM  | 1	| 0.8722	| 3.6418691	| 3.176438229
| OPTForCausalLM	  | 1	| 0.7925	| 7.1054617	| 5.631078397
| PLBartForCausalLM | 1	| 0.8884	| 1.4350074	| 1.274860574

**Comment by leslie-fang-intel** [comment]
Close this issue as it's close to the data before regression.
