### ISSUE TITLE
The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.

### ISSUE THREAD

**Issue by ke1thw** [pytorch/pytorch#98272]
### 🚀 The feature, motivation and pitch

I'm trying to train musiclm model on my m1-mac with mps. However, it reports an issue "NotImplementedError:  The operator 'aten::_fft_r2c' is not currently implemented for the MPS device."

### Alternatives

The system suggest change the environment set to "PYTORCH_ENABLE_MPS_FALLBACK=1", though it would slow the training time.

### Additional context

Hope more functions would be added to support mps soon.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by kulinseth** [comment]
Its tracked in the "Uncategorized" ops to be implemented: https://github.com/pytorch/pytorch/issues/77764#issuecomment-1211503363

**Comment by malfet** [comment]
Duplicate of https://github.com/pytorch/pytorch/issues/78044 which will be discussed during next triage review meeting
