### ISSUE TITLE
svd_cuda_gesvdjBatched not implemented for BFloat16

### ISSUE THREAD

**Issue by jamaliki** [pytorch/pytorch#98308]
Hi Everyone,

It seems like svd is not implemented for any of the half types. Is this by design? I believe all it takes is to just change the dispatch macro here, which I would be happy to do:
https://github.com/pytorch/pytorch/blob/42cbf7120a4c05ce7584ae46e0794c6e34f5f8ae/aten/src/ATen/native/cuda/linalg/BatchLinearAlgebraLib.cpp#L718

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ezyang** [comment]
Sure, send us a patch

**Comment by IvanYashchuk** [comment]
It's not supported by design because we're using cuSOLVER which doesn't support low precision types for gesvdjBatched. You can check the documentation here https://docs.nvidia.com/cuda/cusolver/#cusolverdn-t-gesvdjbatched
