### ISSUE TITLE
MacOS M1 testing is backlogged

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#98362]
## Current Status
*mitigated*.

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 4/4 12:00am incident began
- 4/4 3:00pm detected by observing long queueing times on PR
- 4/4 5:00 pm root caused as fallout of incomplete `terraform apply`
- 5/5 1:00 pm mitigated by provisioning new runners
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
Number of instances allocated for running the actions is down to 20.

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/2453524/230089157-1001423c-1289-4eed-a374-90310bb5bd17.png">

**Comment by malfet** [comment]
Recovering: 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/2453524/230214742-c2d991b7-2bbc-4440-ae71-65255dc92124.png">

**Comment by huydhn** [comment]
As a new error starts to show up and it looks like a provisioning issue, I've disabled the workflow temporarily https://github.com/pytorch/pytorch/issues/98468.  Here are some examples:

* Build failure https://github.com/pytorch/pytorch/actions/runs/4623796293/jobs/8177974437
* Test failure https://github.com/pytorch/pytorch/actions/runs/4622994740/jobs/8177554640

**Comment by malfet** [comment]
Closed the issue, as it protects only against test, but not the build failures.
