### ISSUE TITLE
Add methods for StorageImpl to obtain its subclass information.

### ISSUE THREAD

**Issue by ykddd** [pytorch/pytorch#98410]
### 🚀 The feature, motivation and pitch

We found that the Storageimpl class no longer has the final keyword. So third-party extensions sometimes inherit StorageImpl to record hardware-related information, just like `received_cuda_`, but Storage is a class visible on the python side. Sometimes we want to directly obtain subclass information from Storage, but We only have the parent class pointer `c10::intrusive_ptr<StorageImpl> storage_impl_;` in Storage class.
So one idea I had was to add a method to StoageImpl and Storage, something like
``` C++
  // in StorageImpl
  virtual void* get_extra_info() {
    TORCH_CHECK(false, "You are getting extra infomation form StorageImpl");
    return nullptr;
  };

  // in Storage
  void* GetExtraInfo() {
    return storage_impl_->get_extra_info();
  }
```
But this has the disadvantage that subclasses must put all their extra information in only one class for recovery from void* pointer.I don't know if this is reasonable, or if there is any other better implementation. Please give your valuable suggestions.

**Comment by bdhirsh** [comment]
One question that I have is: what sort of information do you want to stash away in a StorageImpl subclass that is not suitable for you to put directly on your `TensorImpl` subclass instead?

**Comment by ykddd** [comment]
@bdhirsh Just like FunctionalStorageImpl, since storageimpl is inheritable, there must be some scenarios where subclasses will add their own additional information. For me, I want to add some description to describe what format this data is stored in. These formats may be strongly hardware dependent. Like C4HWC4 in MNN.But this information is actually strongly related to memory layout, so it is more suitable to be placed in storeageimpl instead of Tensorimpl.

**Comment by ykddd** [comment]
And we can directly call `tensor.set_(storage)` on the python side, if placed in tensorimpl, we cannot get the data storage information mentioned above.

**Comment by ykddd** [comment]
@ezyang

**Comment by ezyang** [comment]
I am not really a fan of increasing API surface area on storage. Instead of adding more methods on storage, make a function that gets the Storage, casts it to your subclass, and then does the access.

**Comment by ykddd** [comment]
Got it.
