### ISSUE TITLE
Need better error message when a merge cancelled because of timeout

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#98465]
As suggested by @malfet, the error message needs improvements.

See this as an example: https://github.com/pytorch/pytorch/pull/98201#issuecomment-1497216298

The merge was cancelled because MacOS jobs time-outed - see https://github.com/pytorch/pytorch/issues/98362
The error message on the PR is just "The merge job was canceled. If you believe this is a mistake,then you can re trigger it through pytorch-bot", which is not very informative.

Should be something like this instead:

{timeout//60} hours have passed, but {len(jobs_pending} job(s) are still running, first few of them are ...)

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by clee2000** [comment]
Timed out merge message got changed in https://github.com/pytorch/pytorch/pull/124947.  It is not the change suggested in this issue, but it does provide explanation for what happened and what to do next
