### ISSUE TITLE
torch.fx.GraphModule inside custom backend has `training` attribute always set to `True` regardless of the user settings

### ISSUE THREAD

**Issue by piotrchmiel** [pytorch/pytorch#98487]
### 🐛 Describe the bug

Calling `eval()` and `train()` on either the original `torch.nn.Module` or `OptimizedModule` returned by `torch.compile` has no effect on the `training` attribute of `torch.fx.GraphModule` that is passed to custom backend function.

### Minified repro

```
import torch

def my_custom_backend(gm, example_inputs):
    print(gm.training)
    return gm.forward

class MockModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        if self.training:
            return x + 2
        else:
            return x + 3

mod = MockModule()

optimized_mod = torch.compile(mod, backend=my_custom_backend)

mod.eval()
optimized_mod.eval()
print(optimized_mod(torch.zeros(10)))
print(optimized_mod(torch.zeros(10)))

mod.train()
optimized_mod.train()
print(optimized_mod(torch.zeros(10)))
print(optimized_mod(torch.zeros(10)))

mod.eval()
optimized_mod.eval()
print(optimized_mod(torch.zeros(10)))
print(optimized_mod(torch.zeros(10)))
```

Result:

```
True
tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
True
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])
```

### Versions

Torch 2.0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @soumith @wconstab @ngimel

**Comment by tugsbayasgalan** [comment]
@yanboliang  any updates?

**Comment by anijain2305** [comment]
@piotrchmiel The behavior is correct. The user information whether the grad was set or not is captured in guards, and not in extracted graph module. Therefore, you should not use `gm.training` flag.

If you are thinking about whether its a forward or a backward graph, you might need to look into AOT Autograd (search for `aot_eager` in `torch/_dynamo/backends/debugging.py`).




Closing this for now.
