### ISSUE TITLE
F.scaled_dot_product_attention should return the attention weights as well

### ISSUE THREAD

**Issue by netw0rkf10w** [pytorch/pytorch#98505]
### 🚀 The feature, motivation and pitch

Attention weights are useful for all kinds of analysis, so making `torch.nn.functional.scaled_dot_product_attention` return them (in addition to the out tensor) would be very useful. As I understand, this won't cause any computational or memory overhead.

cc @jbschlosser @bhosmer @cpuhrsch @erichan1

**Comment by Chillee** [comment]
No, this is *precisely* why `torch.nn.functional.scaled_dot_product_attention` is faster than attention implemented naively - it's not materializing the attention weights.

**Comment by netw0rkf10w** [comment]
> No, this is _precisely_ why `torch.nn.functional.scaled_dot_product_attention` is faster than attention implemented naively - it's not materializing the attention weights.

@Chillee I see, thanks! I thought the attention weights had been computed anyways, but this is not true.
