### ISSUE TITLE
MacOS build/tests randomly failure as wrong Python is selected

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#98532]
## Current Status
Ongoing

## Error looks like
MacOS uses conda 3.10 from system instead of the expected conda 3.9, and it causes all kind of trouble along the way

## Incident timeline (all times pacific)
April 6th

## User impact
Flaky MacOS

## Root cause
TBD

## Mitigation
TBD

## Prevention/followups
TBD

**Comment by malfet** [comment]
I think short-term solution, is to modify `macos-build.sh`/`macos-test.sh` to take `PYTHON3` environment variable (and define it to `which python3` by default. Longer term solution is to figure out why conda activation is not working as expected on some nodes.

**Comment by huydhn** [comment]
The fix is in https://github.com/pytorch/pytorch/pull/98522.  So far so good, I haven't seen it fails anymore on the commit.  Let's wait for some few more commits before resolving this sev.

**Comment by malfet** [comment]
Hmm, here is one more reproducer: https://github.com/pytorch/pytorch/actions/runs/4633856271/jobs/8199661303

**Comment by huydhn** [comment]
All looks green now after the last fix https://github.com/pytorch/pytorch/pull/98559, so I'll resolve this sev
