### ISSUE TITLE
Build pytorch with cutlass

### ISSUE THREAD

**Issue by Qiyu8** [pytorch/pytorch#98593]
### 🐛 Describe the bug

I just download pytorch 1.11.0 from [here](https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp38-cp38-linux_x86_64.whl), I find out that `lib/libtorch_cuda_cpp.so` and` lib/libtorch_cuda_cu.so` is compiled with cutlass, but AFAIK, cutlass is introduced to pytorch at 1.13.0, Why is this library compiled in advance?

### Versions

1.11.0

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
Please ask questions on discuss.pytorch.org
