### ISSUE TITLE
NotImplementedError: Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. 

### ISSUE THREAD

**Issue by husnejahan** [pytorch/pytorch#98596]
### 🐛 Describe the bug

Inference with quantized model facing error.

NotImplementedError: Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. 

### Details

NotImplementedError: Could not run 'aten::add.out' with arguments from the 'QuantizedCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective[/custom](https://file+.vscode-resource.vscode-cdn.net/custom) build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::add.out' is only available for these backends: [CPU, CUDA, Meta, MkldnnCPU, SparseCPU, SparseCUDA, SparseCsrCPU, SparseCsrCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

**Comment by husnejahan** [comment]
Integer operations are implemented taking into account on quantized model as int8 number. So I replaced all operation as such

   self.cat = nn.quantized.FloatFunctional()
   self.add_relu = torch.nn.quantized.FloatFunctional()
   self.add = torch.nn.quantized.FloatFunctional()
   self.mul = torch.nn.quantized.FloatFunctional()

**Comment by chinmayeeb96** [comment]
I am facing the same error but I am using the MobilenetV2 model. Also, I got the same error resnet18. So where to make the above changes in such type of architecture?

**Comment by nkhlS141** [comment]
Hey @chinmayeeb96 did you solve this problem. I encountered a same issue trying quantization on resnet18.
