### ISSUE TITLE
LD_LIBRARY_PATH environment variable 

### ISSUE THREAD

**Issue by NerdPollution** [pytorch/pytorch#986]
I have installed pytorch in a python virtualenv.

So, when the [cudnn.py](https://github.com/pytorch/pytorch/blob/c0fc07eca031c47a75faf36e23a296bb897fd80d/torch/backends/cudnn/__init__.py) library is looking for cudnn v5.1 it is not using the LD_LIBRARY_PATH environment variable but instead using a relative path (i.e. libpaths = ['', path.join(thisdir, '../../lib')]). That relative path is where ever my python virtualenv is located. So, I am getting a run time error, "RuntimeError: dropout supported only in cudnn v5.1 and above".

Should this python module use the environment variable instead of the relative path?  Because when updating to cudnn you update the libs in the $LD_LIBRARY_PATH path  (i.e. libpaths = os.environ['LD_LIBRARY_PATH'].split(":")) ?

**Comment by apaszke** [comment]
`libpath = ''` is the case that will search in system dirs and `LD_LIBRARY_PATH` (that's what `ctypes` does). It might be the case that you have an older cuDNN version installed somewhere in the system, and it's the one getting picked up instead of the one we provide in the binaries.
