### ISSUE TITLE
Error raised importing torch.utils.cpp_extension for non-ROCM builds

### ISSUE THREAD

**Issue by ryannikolaidis** [pytorch/pytorch#98629]
### 🐛 Describe the bug

Importing `torch.utils.cpp_extension` raises `NotADirectoryError` for non-ROCM builds.

Context: I'm installing detectron2 which imports constants from torch, on setup [here](https://github.com/facebookresearch/detectron2/blob/main/setup.py#L11). This triggers the exception.

Adding `NotADirectoryError` to the exceptions caught [here](https://github.com/pytorch/pytorch/blob/master/torch/utils/hipify/cuda_to_hip_mappings.py#L37) does resolve the issue entirely.

### Traceback
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/usr/local/lib/python3.8/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/usr/local/lib/python3.8/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.7 (Green Obsidian) (aarch64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.8.15 (default, Apr  7 2023, 21:02:28)  [GCC 8.5.0 20210514 (Red Hat 8.5.0-16)] (64-bit runtime)
Python platform: Linux-5.15.49-linuxkit-aarch64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              6
On-line CPU(s) list: 0-5
Thread(s) per core:  1
Core(s) per cluster: 6
Socket(s):           -
Cluster(s):          1
Vendor ID:           0x00
Model:               0
Stepping:            0x0
BogoMIPS:            48.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint

Versions of relevant libraries:
[pip3] torch==2.0.0
[conda] Could not collect

cc @malfet @zou3519 @jbschlosser @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by ryannikolaidis** [comment]
More color and digging. I am compiling Python in the steps preceding the error. I found that if I started a new session that I would get the expected `FileNotFoundError` rather than `NotADirectoryError` which is then caught in that block and handled as hoped. Looks like this is a result of having `/usr/bin/gcc` still in my PATH. Removing does fix. Not sure if this is necessarily a bug, but worth a heads up. Either way, easy enough to resolve on my end, so feel free to close this.

**Comment by ryannikolaidis** [comment]
More color and digging. I am compiling Python in the steps preceding the error. I found that if I started a new session that I would get the expected FileNotFoundError rather than NotADirectoryError which is then caught in that block and handled as hoped. Looks like this is a result of having /usr/bin/gcc still in my PATH. Removing does fix. The issue in my case is that I need this to install `detectron2` (which hits that import line in setup [here](https://github.com/facebookresearch/detectron2/blob/1bc3a33a71991142c2c67bc99e1559d6101fb009/setup.py#L11)).

**Comment by ryannikolaidis** [comment]
It looks like just adding `hipconfig` to my path (despite this not actually pointing anywhere), is enough to get back to the `FileNotFoundError` rather than `NotADirectoryError`, which at least unblocks on my end.

**Comment by mayankverk** [comment]
I'm still unclear on the solution for this. I'm using NVIDIA A6000 GPUs so I don't understand how hipconfig is relevant.

**Comment by LiWentomng** [comment]
Hello, I'm also still unclear on the solution for this.  Any detailed information can be  provided?

**Comment by flckv** [comment]
What was the solution for this?

**Comment by flckv** [comment]
> I'm still unclear on the solution for this. I'm using NVIDIA A6000 GPUs so I don't understand how hipconfig is relevant.
> 
> Edit: tfsingh's fix above worked for me.

hi, @mayankverk, did you install pytorch with the fix from https://pytorch.org/get-started/locally/  or from source?

**Comment by ryannikolaidis** [comment]
@flckv iirc my workaround at the time was just to add hipconfig to my PATH variable. e.g. something like: `export PATH="hipconfig:$PATH"`. This was simply to get it to trigger the caught FileNotFoundError rather than NotADirectoryError. [That fix](https://github.com/pytorch/pytorch/pull/99980/files) as implemented does resolve the problem (assuming it's in the version you have).

**Comment by SalvatoreCognetta** [comment]
> @flckv iirc my workaround at the time was just to add hipconfig to my PATH variable. e.g. something like: `export PATH="hipconfig:$PATH"`. This was simply to get it to trigger the caught FileNotFoundError rather than NotADirectoryError. [That fix](https://github.com/pytorch/pytorch/pull/99980/files) as implemented does resolve the problem (assuming it's in the version you have).

I solved this issue with the solution provided by @ryannikolaidis, modifying directly the torch/utils/hipify/cuda_to_hip_mappings.py file by adding the "NotADirectory" exception.

**Comment by achiverram28** [comment]
> That fix

Yes , this fixed for me as well
