### ISSUE TITLE
[PT2] FSDP raises `DuplicateInputs` assertion

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#98625]
Script that requires torchrun and 2 GPUs:
```
"""
torchrun --standalone --nproc_per_node=2 test/fsdp_dup_repro.py
"""
import os
import torch
import torch.distributed as dist
import torch.nn as nn

from torch.distributed.fsdp import FullyShardedDataParallel as FSDP


class Model(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.register_buffer("_buf", torch.randn((3,), requires_grad=False, device="cuda"))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # `self._buf` gets used twice in this compiled forward
        z = self._add_buf(x)
        z += self._mul_buf(self._buf)
        return z

    def _add_buf(self, z: torch.Tensor) -> torch.Tensor:
        z += self._buf
        return z
    
    def _mul_buf(self, buf: torch.Tensor):
        buf.mul_(2)
        return buf + buf


dist.init_process_group(backend="nccl")
gpu_id = int(os.environ["LOCAL_RANK"])
device = f"cuda:{gpu_id}"
torch.cuda.set_device(device)

model = Model()
fsdp_model = FSDP(model, use_orig_params=True)
fsdp_model = torch.compile(fsdp_model)
inp = torch.randn((2, 3), device="cuda")
fsdp_model(inp)

```

Raises:
```
...
File "/.../pytorch/torch/_guards.py", line 244, in __post_init__
    assert self.input_source_a != self.input_source_b
```

cc @zhaojuanmao @mrshenli @rohan-varma @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by awgu** [comment]
`OutputGraph.create_graph_arg()` gets called three times:
```
create_graph_input: x
create_graph_input: self_buf
create_graph_input: self_buf_0
```
where `self._buf` gets represented twice due to its two usages in the compiled `forward()`.

```
x is placeholder and has dynamo source LocalInputSource(local_name='x', pos=1)
self_buf is placeholder and has dynamo source AttrSource(base=FSDPNNModuleSource(inner=LocalInputSource(local_name='self', pos=0)), member='_buf')
self_buf_0 is placeholder and has dynamo source AttrSource(base=FSDPNNModuleSource(inner=LocalInputSource(local_name='self', pos=0)), member='_buf')
```
Both `self_buf` and `self_buf_0` have the same `Source` since they are the same tensor.
```
aot_autograd_arg_pos_to_source: [LocalInputSource(local_name='x', pos=1), AttrSource(base=FSDPNNModuleSource(inner=LocalInputSource(local_name='self', pos=0)), member='_buf'), AttrSource(base=FSDPNNModuleSource(inner=LocalInputSource(local_name='self', pos=0)), member='_buf')]
```
`add_dupe_map`:
```
0 0
1 1
2 1
```
Since `2 != 1` for the last entry, AOTAutograd will create a `DuplicateInputs` object, passing in the same `AttrSource`, causing the assertion error.

Should Dynamo add some de-duplication logic in `create_graph_input()`  to avoid creating if the same source has already been seen?

**Comment by bdhirsh** [comment]
Does dynamo need to create graph args out of the buffers in the first place?

I tried running this repro without FSDP. And (part of the reason we don’t run into trouble is because the graph that dynamo hands AOTAutograd does have buffers as inputs. This is fine, since AOTAutograd has its own logic to lift Params/buffers.

**Comment by awgu** [comment]
> Does dynamo need to create graph args out of the buffers in the first place?

Dynamo does not have to create graph args out of the buffers. However, in my understanding, we would need to add some machinery to differentiate between FSDP-managed modules' parameters vs. buffers in Dynamo.

For context, FSDP uses its own `VariableTracker` similar to `UnspecializedNNModuleVariable` so that the "parameters" are passed as graph args. This is needed since FSDP creates new `Tensor` views each iteration to represent the logical parameters, and registering the parameters like normal `nn.Module`s, would bake in the first iteration's stale views. I do not see any technical reason why buffers need to follow this behavior as well.

Correct me if I am wrong, but I recall that DDP also treats buffers as graph args. For your repro without FSDP, I am guessing you ran it without DDP either?

---
As I am writing this up, I realized something tangential that we should revisit. For `NNModuleVariable`, Dynamo guards on `self.training`. I think we need to add that to `FSDPNNModuleVariable`, especially given the recently landed https://github.com/pytorch/pytorch/pull/97645.

**Comment by awgu** [comment]
I should also mention that this issue should be separate from the issue of whether the following dictionary lookup can confound different `FakeTensor`s (and any other similar hashing of `FakeTensor`s):
https://github.com/pytorch/pytorch/blob/387feaa1312995e33f987175bc27790742272bd4/torch/_functorch/aot_autograd.py#L1872

I need to see if I can repro this in a simpler script. If that lookup can confound different `FakeTensor`s, then there may be AOTAutograd de-dup guards constructed that incorrectly check `a is b` since it thinks that `a` and `b` are the same when they are not.

**Comment by ezyang** [comment]
This is the buffers problem where we can detect and dedupe parameters but not buffers. Just need to make these treated uniformly.

**Comment by awgu** [comment]
> This is the buffers problem where we can detect and dedupe parameters but not buffers. Just need to make these treated uniformly.

Could you point me to the parameter de-dup logic? Is this separate from `register_attr_or_module()`?
https://github.com/pytorch/pytorch/blob/e016dec66e55ce346c8c7da0702e8f4fbf60f44a/torch/_dynamo/output_graph.py#L390
https://github.com/pytorch/pytorch/blob/e016dec66e55ce346c8c7da0702e8f4fbf60f44a/torch/_dynamo/output_graph.py#L471-L474

I ask because FSDP does not go through this path at all, so I was wondering if there was logic somewhere else as well.
https://github.com/pytorch/pytorch/blob/e016dec66e55ce346c8c7da0702e8f4fbf60f44a/torch/_dynamo/variables/builder.py#L749-L753

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/issues/98743 indicates that we actually don't have any dedupe logic. awgu is going to work to fix this.

**Comment by awgu** [comment]
https://github.com/pytorch/pytorch/pull/98775
