### ISSUE TITLE
Run ONNX tests as part of the standard run_test script

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#98626]
### 🐛 Describe the bug

At the moment, ONNX tests are handled in a different way than other Python test using `run_test.py`.  Specifically, it shells out to pytest directly in https://github.com/pytorch/pytorch/blob/master/scripts/onnx/test.sh.  The main issue with the current approach is that none of the feature of `run_test.py` is available to ONNX such as flaky bot, retry, slow test to name a fews.  For example, it won't work when I try to disable a flaky ONNX test https://github.com/pytorch/pytorch/issues/98622.  Now that `run_test.py` uses pytest by default, it's time to have onnx as part of it too

### Versions

PyTorch CI, ONNX

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ZainRizvi @kit1980 @clee2000

**Comment by kit1980** [comment]
cc @BowenBao

**Comment by huydhn** [comment]
Interestingly, I saw an example ONNX flaky failure today https://github.com/pytorch/pytorch/actions/runs/4662975326/jobs/8254048180 where the retry logic ran.  But tries failed with the same failure:

```
=================================== FAILURES ===================================
[31m[1m________________ test/onnx/test_fx_to_onnx_with_onnxruntime.py _________________[0m
[gw1] linux -- Python 3.8.16 /opt/conda/envs/py_3.8/bin/python
worker 'gw1' crashed while running 'test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_True::test_flatten_dynamic_axes'

....
RETRY
...

=================================== FAILURES ===================================
[31m[1m________________ test/onnx/test_fx_to_onnx_with_onnxruntime.py _________________[0m
[gw0] linux -- Python 3.8.16 /opt/conda/envs/py_3.8/bin/python
worker 'gw0' crashed while running 'test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_True::test_flatten_dynamic_axes'
```

**Comment by titaiwangms** [comment]
> Interestingly, I saw an example ONNX flaky failure today https://github.com/pytorch/pytorch/actions/runs/4662975326/jobs/8254048180 where the retry logic ran. But tries failed with the same failure:
> 
> ```
> =================================== FAILURES ===================================
> �[31m�[1m________________ test/onnx/test_fx_to_onnx_with_onnxruntime.py _________________�[0m
> [gw1] linux -- Python 3.8.16 /opt/conda/envs/py_3.8/bin/python
> worker 'gw1' crashed while running 'test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_True::test_flatten_dynamic_axes'
> 
> ....
> RETRY
> ...
> 
> =================================== FAILURES ===================================
> �[31m�[1m________________ test/onnx/test_fx_to_onnx_with_onnxruntime.py _________________�[0m
> [gw0] linux -- Python 3.8.16 /opt/conda/envs/py_3.8/bin/python
> worker 'gw0' crashed while running 'test/onnx/test_fx_to_onnx_with_onnxruntime.py::TestFxToOnnxWithOnnxRuntime_op_level_debug_False_dynamic_shapes_True::test_flatten_dynamic_axes'
> ```
> 
> May be this is just a rare case, an infra issue, or the test is just really flaky.

Hi @huydhn,

We think the issue was caused by ORT-unsupported dynamic tests which I disabled now. Please let us know if you still see the flaky failure on tests!

**Comment by BowenBao** [comment]
@huydhn I took a quick initial look at `run_test.py`. 

* Is it possible to add `--onnx` as argument that onnx tests run if and only if the argument is set?
* Is it possible to exclude based on test files for running pytest with parallel? (Extending the list for `must_serial`?)
* If above is done, all we'd need is to update `scripts/onnx/test.sh` to call `run_test.py`, similarily to how it is done in `.ci/pytorch/test.sh`, correct?

Please let me know if there is anything I've missed.

**Comment by huydhn** [comment]
Thank you picking this up!

* Is it possible to add --onnx as argument that onnx tests run if and only if the argument is set?  Yes, this is possible.  There are similar arguments, i.e. `--distributed` to run only distributed test
* Is it possible to exclude based on test files for running pytest with parallel? Yes, the same example for distributed test also applies here.  Specifically, all distributed test discovered by `DISTRIBUTED_TESTS = [test for test in TESTS if test.startswith("distributed")]` are run serially https://github.com/pytorch/pytorch/blob/master/test/run_test.py#L1093-L1103
* If above is done, all we'd need is to update scripts/onnx/test.sh to call run_test.py, similarily to how it is done in .ci/pytorch/test.sh, correct? Exactly, I'm thinking something like `run_test.py --onnx` plus few more params

**Comment by BowenBao** [comment]
For the first point though, does it always require explicit exclusion (I saw there is `exclude_distributed_tests`)? We probably won't want onnx tests to be run anywhere else due to the dependencies.

**Comment by huydhn** [comment]
> For the first point though, does it always require explicit exclusion (I saw there is `exclude_distributed_tests`)? We probably won't want onnx tests to be run anywhere else due to the dependencies.

Yes, that's true.  The exclusion is there to avoid running these tests on the default test suite.  By default, distributed tests are all excluded unless `--distributed` is set

**Comment by BowenBao** [comment]
Hmm.. So I guess ideally we should be doing the exclusion for onnx in the else branch of `if options.onnx:` right? Then we won't need to upgrade all the default test suite command elsewhere.

**Comment by BowenBao** [comment]
@huydhn should be ready at #99215. Please let me know if you find anything missing!
