### ISSUE TITLE
Allow custom arguments to `torch.compile` backends

### ISSUE THREAD

**Issue by gs-olive** [pytorch/pytorch#98663]
### 🚀 The feature, motivation and pitch

Some `torch.compile` backends use optional arguments, such as the tvm backend: https://github.com/pytorch/pytorch/blob/c68a94c5ead758cb0b3fa8a71d731fe131228b12/torch/_dynamo/backends/tvm.py#L17

There is already a field in `torch.compile` for `options`, but these only apply to Torch Inductor
https://github.com/pytorch/pytorch/blob/c68a94c5ead758cb0b3fa8a71d731fe131228b12/torch/__init__.py#L1533-L1566

The `options` argument could be expanded to allow providing custom arguments to _any_ backend. Alternatively, a `**kwargs` could be added to the function signature, for keyword arguments which are passed to the backend directly, if specified.

### Alternatives

One alternative to providing optional arguments to `torch.compile` is to use `functools.partial` or `lambda` expressions to pre-populate keyword arguments in backends, but this leads to function implementations which are neither clean nor one-liners, and require building a custom backend for each set of desired keyword arguments. This can also require additional infrastructure on the backend side, which can unnecessarily increase the size of backend code. For example, to specify keyword arguments currently, one would need to do:

```python
custom_backend = lambda gm, inputs : my_backend(gm, inputs, a=a, b=b, c=c)
torch.compile(model, backend=custom_backend)
```

As opposed to the much simpler:
```python
torch.compile(model, backend=custom_backend, a=a, b=b, c=c)

##### OR #####

torch.compile(model, backend=custom_backend, options={"a": a, "b": b, "c": c})
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by desertfire** [comment]
Similar to https://github.com/pytorch/pytorch/issues/98486

**Comment by Fami64** [comment]
Hey @gs-olive,
I have a question about this issue as I am actually trying to add support for more input options to configure the tvm backend. Wouldn't placing custom arguments in an "options" dict allow us to do this?
```
torch.compile(model, backend=custom_backend, options={"a": a, "b": b, "c": c})
```
For example, in tvm, it would be changing the tvm backend's input arguments from
 ```
 def tvm(gm, example_inputs, *, scheduler=None, trials=20000):
 ```
 to 
  def tvm(gm, example_inputs, *, options= {"scheduler":None, "trials":20000}):

solve the issue? I don't get why they are defined like that in the first place.

P.S. Apologies in advance if I'm not getting the point right, I'm new to pytorch.

**Comment by gs-olive** [comment]
Hi @Fami64 - thanks for the comment, yes this seems to work now, as you proposed! This issue was filed before `options` arguments were being passed through to the backends, so I will mark this as closed now, since options can be passed to custom backends.

**Comment by wlepera** [comment]
Can someone offer some insight on the syntax needed on both the custom backend side and the torch.compile side to pass these options?  I've been trying various combinations but keep getting
```
  File "/usr/local/lib64/python3.9/site-packages/torch/__init__.py", line 1607, in __call__
    return self.compiler_fn(model_, inputs_, **self.kwargs)
torch._dynamo.exc.BackendCompilerFailed: backend='foo' raised:
TypeError: compiler_fn() got an unexpected keyword argument 'options'
```
My most recent attempt was `def foo_compiler(gm, expected_inputs, *, options={}):`, with a caller of `output = torch.compile(model,backend="foo",fullgraph=True, options={"key":"value"})`

Thanks

**Comment by sahilsuneja1** [comment]
Did you ever get it to work, @wlepera ?

**Comment by sahilsuneja1** [comment]
@wlepera 
An update-- passing options using the following approach does indeed work for me:
```import torch
from torch._functorch.aot_autograd import aot_module_simplified

def inspect_backend2(gm, sample_inputs, options={'x':0}):
    x = options.get('x', 0)
    print(x)

    def fw(gm, sample_inputs):
        gm.print_readable()
        return gm.forward

    return aot_module_simplified(gm, sample_inputs, fw_compiler=fw)


def f(x,y):
    x = torch.sin(x)
    y = torch.cos(y)
    z = x + y
    return z


def g():
    x = torch.randn(10,10)
    y = torch.randn(10,10)
    f_compile = torch.compile(f, backend=inspect_backend2, options={'x':2})
    z = f_compile(x,y)

g()
