### ISSUE TITLE
[doc] Improvements to documentation of `torch.gradient`

### ISSUE THREAD

**Issue by gusty1g** [pytorch/pytorch#98693]
### 📚 The doc issue

In the documentation of `torch.gradient`, in the following lines:

https://github.com/pytorch/pytorch/blob/9d363616011bb1ababffe78a97eec2597145fc2f/torch/_torch_docs.py#L4686-L4699

between the first eqn and second eqn, it will be nice if additional context could be provided on the what `h_l` represents and how `h_r` and `h_l` are estimated.

cc @svekars @carljparker

**Comment by zou3519** [comment]
We would a PR fixing this

**Comment by zou3519** [comment]
Please feel free
