### ISSUE TITLE
[Problem report] GPU 0 out of memory even if assigning one GPU for each model in multiprocessing

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#9871]
I am using Python multiprocessing to train a model with different random seeds (not using PyTorch multiprocessing because we do not want to share the model or the memory, but independent training). For example I have 7 GPUs in the server and created 7 training script each for a different random seeds. And in each file assign a specific gpu i.e. `torch.device(f'cuda:{i}')` where i is in the range [0, 6]. 

However, although this should be expected to work fine, but from the second script to the last, they give a `CUDA Runtime Error with out of memory`. It seems GPU 0 always occupy a lot of memory for each script even if they are assigned with other GPUs. 

The PyTorch version is `0.5.0a0+1597fc5`

**Comment by soumith** [comment]
@zuoxingdong can you also set `torch.cuda.set_device(f'cuda:{i}')` right after `import torch` in the child process.

**Comment by soumith** [comment]
the amount consumed by GPU0 shoudn't be large, maybe ~200MB per process. If it's larger than that, I suggest to see upgrading to master and see if it fixes things. Also https://github.com/pytorch/pytorch/pull/7392 fixed some issues around default device initialization.

**Comment by heitorschueroff** [comment]
Fixed by https://github.com/PyTorchLightning/pytorch-lightning/pull/1349
