### ISSUE TITLE
torch.ops.aten.sym_size output error with negative diment

### ISSUE THREAD

**Issue by yanbing-j** [pytorch/pytorch#98729]
### 🐛 Describe the bug

`torch.ops.aten.sym_size` will get output error when the input dimension is negative number.

### Reproduce

>>> import torch
>>> a = torch.randn(2,3,4,5)
>>> a.size(-2)
4
>>> torch.ops.aten.sym_size(a, -2)
140024983873072

### Versions

PyTorch version: 2.0.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Clang version: Could not collect
CMake version: version 3.22.2
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          160
On-line CPU(s) list:             0-159
Thread(s) per core:              2
Core(s) per socket:              40
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         897.750
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Virtualization:                  VT-x
L1d cache:                       3.8 MiB
L1i cache:                       2.5 MiB
L2 cache:                        100 MiB
L3 cache:                        120 MiB
NUMA node0 CPU(s):               0-39,80-119
NUMA node1 CPU(s):               40-79,120-159
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0+cpu
[pip3] torch_geometric==2.4.0
[pip3] torch-scatter==2.1.1+pt20cpu
[pip3] torch-sparse==0.6.17+pt20cpu
[pip3] torchaudio==2.0.1+cpu
[pip3] torchvision==0.15.1+cpu
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0+cpu                pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-scatter             2.1.1+pt20cpu            pypi_0    pypi
[conda] torch-sparse              0.6.17+pt20cpu           pypi_0    pypi
[conda] torchaudio                2.0.1+cpu                pypi_0    pypi
[conda] torchvision               0.15.1+cpu               pypi_0    pypi

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by amritangshudey** [comment]
In the context of torch.ops.aten.sym_size, which is likely intended to compute the size of a symbolic shape or dimension, negative dimensions do not have a meaningful interpretation and should not be allowed.


To fix this:-
The torch.ops.aten.sym_size function should include a check at the beginning to validate that the input dimension is not negative, and raise an appropriate error or exception if it is.

example:-
def sym_size(dim):
    if dim < 0:
        raise ValueError("Input dimension must be non-negative")

**Comment by amritangshudey** [comment]
can you assign me this issue?

**Comment by yanbing-j** [comment]
Could you please explain more about why the negative dimension in symbolic shape is not meaningful? In my opinion, it should be the same as common `size()` to represent the number to last of the shape.

**Comment by yanbing-j** [comment]
Is there any updates of this issue? Thanks! @ezyang @bhosmer @smessmer @ljk53 @bdhirsh

**Comment by ezyang** [comment]
No, this seems low priority to me absent a real world case where this is failing. The patch is simple though.

**Comment by yrom1** [comment]
Noticed this issue seemed to have been fixed already in the most recent version. I believe it may have been #103107 that fixed it:

`torch==2.1.0a0+gitd997969` d997969
```py
>>> import torch
>>> a = torch.randn(2,3,4,5)
>>> a.size(-2)
4
>>> torch.ops.aten.sym_size(a, -2)
4
```

The previous commit, `torch==2.1.0a0+git0cb5bc3` 0cb5bc3 has the issue still:
```py
>>> import torch
>>> a = torch.randn(2,3,4,5)
>>> a.size(-2)
4
>>> torch.ops.aten.sym_size(a, -2)
4342133968
```
Assuming I was able to compile it correctly.

**Comment by yanbing-j** [comment]
Thanks for the notification @yrom1 , the issue is fixed already in PyTorch master. Will close this issue.
