### ISSUE TITLE
torch.mps.manual_seed() attribute error

### ISSUE THREAD

**Issue by Killpit** [pytorch/pytorch#98740]
### 📚 The doc issue

Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/PyTorchFCC/classification.py", line 148, in <module>
    torch.mps.manual_seed(42)
AttributeError: module 'torch' has no attribute 'mps'

Followed PyTorch documentation but I got the attribute error when writing torch.mps.manual_seed()

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
I can reproduce. You can use `torch.manual_seed` to set mps RNG seed, which should be equivalent to `torch.mps.manual_seed`.

**Comment by Killpit** [comment]
So I can directly use `torch.manual_seed` without a problem, but what about `torch.cuda.manual_seed`

**Comment by albanD** [comment]
torch.manual_seed is indeed setting the seed on all current devices (including cpu/cuda/mps).
So you can use that if you want to seed everything.

If you want to do it today, you need to explicitly import the mps module: `from torch import mps` before being able to access `torch.mps`.
@qqaatw 's PR linked above will fix that soon.
