### ISSUE TITLE
Inconsistent parameter name in documentation for torch.func.functional_call(()

### ISSUE THREAD

**Issue by BarunKGP** [pytorch/pytorch#98766]
### 📚 The doc issue

The parameter description on the docs for [torch.func.functional_call](https://pytorch.org/docs/stable/generated/torch.func.functional_call.html) lists `parameters_and_buffers` as a parameter, which is incorrect and confusing as the function signature uses `parameter_and_buffer_dicts` to refer to this. The expected input type is `Union[Dict, Sequence]` which then gets converted to the `parameters_and_buffers` dictionary in the function after performing a few checks.

Included screenshots of the docs to illustrate the issue:
![image](https://user-images.githubusercontent.com/24320788/230959586-6c91fc5b-515b-4974-a279-28a1ab8d9795.png)
![image](https://user-images.githubusercontent.com/24320788/230959711-b655b3e0-dd18-4b34-8970-915a4d2f734a.png)

### Suggest a potential alternative/fix

Modify the docstring for the function definition at `_functorch/functional_call.py`. We only need to change the parameter description to `parameter_and_buffer_dicts` and it should be correctly picked up by the doc generators. 

If this sounds good, I am happy to create a PR to fix this, if this.

cc @svekars @carljparker

**Comment by BarunKGP** [comment]
Note that there are also other parts in the same docstring that seem to mention `parameters_and_buffers` which can be quite confusing unless you know the underlying implementation of `functional_call()`. They should also be changed to `parameter_and_buffer_dicts` for consistency.

**Comment by zou3519** [comment]
We would accept a PR fixing this (and the other parts of the docstring that mention parameters_and_buffers)
