### ISSUE TITLE
feature request, linear normalization

### ISSUE THREAD

**Issue by isalirezag** [pytorch/pytorch#9878]
Can pytorch consider providing a linear normalization for tensors.
Meaning, if I have tensor `BxCxDxD`, I can make each layer or whole tensor or other each batch, etc to be normalized and have the values between `[a b] `

**Comment by soumith** [comment]
@isalirezag you can do this easily with autograd ops (i.e. mean, std and subtraction, division), or with special ops like InstanceNorm, LayerNorm
