### ISSUE TITLE
Sparse Tensor sum not working for PyG example

### ISSUE THREAD

**Issue by puririshi98** [pytorch/pytorch#98796]
### 🐛 Describe the bug

failing example:
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/correct_and_smooth.py

Error:
```
Traceback (most recent call last):
  File "examples/correct_and_smooth.py", line 70, in <module>
    deg = adj_t.sum(dim=1).to(torch.float)
RuntimeError: torch.empty: Only batched sparse compressed (non-block) tensors are supported, but got size [2449029]
```

printed size of adj_t:
`adj_t.size() = torch.Size([2449029, 2449029])
`

### Versions

root@146707bd8311:/opt/pyg/pytorch_geometric# python collect_env.py
Collecting environment information...
PyTorch version: 2.0.0a0+1767026
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.24.1
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-104-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA Graphics Device
Nvidia driver version: 470.57.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.8.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.8.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           94
Model name:                      Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
Stepping:                        3
CPU MHz:                         3659.620
CPU max MHz:                     3900.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6599.98
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        6 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

Versions of relevant libraries:
[pip3] flake8==5.0.3
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.22.3
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.0.0a0+1767026
[pip3] torch_geometric==2.4.0
[pip3] torch-tensorrt==1.4.0.dev0
[pip3] torchmetrics==0.9.3
[pip3] torchtext==0.13.0a0+fae8e8c
[pip3] torchvision==0.15.0a0
[pip3] triton==2.0.0
[pip3] tritonclient==2.29.0

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by puririshi98** [comment]
using torch sparse sum results in the following issue. adj_t is sparsely represented edge_indices sampled from a graph, and yes it should represent this. @rusty1s 
```
adj_t= tensor(crow_indices=tensor([        0,       174,       263,  ...,
                            123718105, 123718114, 123718152]),
       col_indices=tensor([    384,    2412,    7554,  ..., 1787657, 1864057,
                           2430488]),
       values=tensor([1., 1., 1.,  ..., 1., 1., 1.]), device='cuda:0',
       size=(2449029, 2449029), nnz=123718152, layout=torch.sparse_csr)
Traceback (most recent call last):
  File "examples/correct_and_smooth.py", line 71, in <module>
    deg = adj_t.sum(dim=1).to(torch.float)
RuntimeError: torch.empty: Only batched sparse compressed (non-block) tensors are supported, but got size [2449029]

Traceback (most recent call last):
  File "examples/correct_and_smooth.py", line 70, in <module>
    deg = torch.sparse.sum(adj_t, dim=1).to(torch.float)
  File "/usr/local/lib/python3.8/dist-packages/torch/sparse/__init__.py", line 212, in sum
    return torch._sparse_sum(input, dim)
NotImplementedError: Could not run 'aten::_indices' with arguments from the 'SparseCsrCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::_indices' is only available for these backends: [SparseCPU, SparseCUDA, SparseMeta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

SparseCPU: registered at /opt/pytorch/pytorch/build/aten/src/ATen/RegisterSparseCPU.cpp:1379 [kernel]
SparseCUDA: registered at /opt/pytorch/pytorch/build/aten/src/ATen/RegisterSparseCUDA.cpp:1562 [kernel]
SparseMeta: registered at /opt/pytorch/pytorch/build/aten/src/ATen/RegisterSparseMeta.cpp:249 [kernel]
BackendSelect: fallthrough registered at /opt/pytorch/pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at /opt/pytorch/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
Functionalize: registered at /opt/pytorch/pytorch/build/aten/src/ATen/RegisterFunctionalization_2.cpp:21438 [kernel]
Named: registered at /opt/pytorch/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /opt/pytorch/pytorch/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at /opt/pytorch/pytorch/aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at /opt/pytorch/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/ADInplaceOrViewType_0.cpp:4733 [kernel]
AutogradOther: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradCPU: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradCUDA: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradHIP: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradXLA: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradMPS: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradIPU: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradXPU: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradHPU: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradVE: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradLazy: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradMeta: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradMTIA: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradPrivateUse1: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradPrivateUse2: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradPrivateUse3: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
AutogradNestedTensor: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_1.cpp:14991 [autograd kernel]
Tracer: registered at /opt/pytorch/pytorch/torch/csrc/autograd/generated/TraceType_1.cpp:15816 [kernel]
AutocastCPU: fallthrough registered at /opt/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:487 [backend fallback]
AutocastCUDA: fallthrough registered at /opt/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:354 [backend fallback]
FuncTorchBatched: registered at /opt/pytorch/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:815 [backend fallback]
FuncTorchVmapMode: fallthrough registered at /opt/pytorch/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at /opt/pytorch/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1073 [backend fallback]
VmapMode: fallthrough registered at /opt/pytorch/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at /opt/pytorch/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:210 [backend fallback]
PythonTLSSnapshot: registered at /opt/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at /opt/pytorch/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
PythonDispatcher: registered at /opt/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]

```

**Comment by mingfeima** [comment]
@yanbing-j could you please help fix this one ?

**Comment by mingfeima** [comment]
This issue can be worked around with:
```
torch._sparse_csr_sum(a, dim=1, keepdim=True)
```

But I still don't quite understand why a.sum(dim=1) does not work, and I failed to find the correct dispatch key under `native_fuctional.yaml` for sum:

```
- func: sum.dim_IntList(Tensor self, int[1]? dim, bool keepdim=False, *, ScalarType? dtype=None) -> Tensor
  structured_delegate: sum.IntList_out
  device_check: NoCheck   # TensorIterator
  variants: function, method
  dispatch:
    NestedTensorCPU: NestedTensor_sum_dim_CPU
    SparseCPU, SparseCUDA: sum_sparse_coo
  tags: core
```

**Comment by cpuhrsch** [comment]
@mingfeima - I don't think we currently support sum(a, dim=1) for CSR given that there are no kernels registered for the corresponding overloads. Note that we do have support for sum(a) as indicated here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml#L5375 . Maybe `sum_csr` can be extended, but it seems like we need support for CUDA here as well.

**Comment by puririshi98** [comment]
@mingfeima using `deg= torch._sparse_csr_sum(adj_t, dim=1, keepdim=True)`
works but then we fail in the next line w/:
```
  File "examples/correct_and_smooth.py", line 71, in <module>
    deg_inv_sqrt = deg.pow_(-0.5)
```

**Comment by puririshi98** [comment]
any updates on this @yanbing-j ?

**Comment by yanbing-j** [comment]
Hi @puririshi98 , the PR is almost finished, I will try to fix the CI failures these days.
