### ISSUE TITLE
[doc] example tensor printings are not updated

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9885]
@li-roy

**Comment by vadimkantorov** [comment]
Also, many docs use e.g. `torch.rand(3, 3)` to generate matrices. In many cases a fixed matrix like `torch.arange(9).view(3, 3)` may be more preferable for repeatability.

**Comment by mruberry** [comment]
This issue is lacking details needed to make it actionable. @SsnL, do you recall which examples you were thinking of updating?

**Comment by SsnL** [comment]
@mruberry this was created in the context that tensor printing format was changed in 0.4. it is not valid anymore.
