### ISSUE TITLE
module.load_state_dict doesn't load the state_dict modified for contiguous

### ISSUE THREAD

**Issue by jerrychenhf** [pytorch/pytorch#98906]
### 🐛 Describe the bug

We modified state_dict for making sure every Tensor is contiguious  and then use load_state_dict to load the modified state_dict to the module. The load_state_dict returned without error but we found the Tensor for the parameter was not updated and still not contiguious.

The following code reproduce the problem:

        from torchvision import models
        import torch
        import copy
        
        def make_contiguous(module):
            with torch.no_grad():
                state_dict = module.state_dict()
                state_dict=copy.deepcopy(state_dict)
                print("Non contiguous state dict:")
                for name, param in state_dict.items():
                    if not param.is_contiguous():
                        print(name)
                        print(param.is_contiguous())
                        state_dict[name] = param.contiguous()
                        print(state_dict[name].is_contiguous())
        `
            print("New non contiguous state dict:")
            module.load_state_dict(state_dict)
            for name, param in module.state_dict().items():
                if not param.is_contiguous():
                    print(name)
                    print(param.is_contiguous())
        
        def train(learning_rate):
            # Set up standard model.
            model = getattr(models, "resnet50")()
            model = model.to(memory_format=torch.channels_last)
            make_contiguous(model)

        if __name__ == '__main__':
            train(0.1)

The output of the above code is:

        Non contiguous state dict:
        conv1.weight
        False
        True
        layer1.0.conv2.weight
        False
        True
        layer1.1.conv2.weight
        False
        True
        layer1.2.conv2.weight
        False
        True
        layer2.0.conv2.weight
        False
        True
        layer2.1.conv2.weight
        False
        True
        layer2.2.conv2.weight
        False
        True
        layer2.3.conv2.weight
        False
        True
        layer3.0.conv2.weight
        False
        True
        layer3.1.conv2.weight
        False
        True
        layer3.2.conv2.weight
        False
        True
        layer3.3.conv2.weight
        False
        True
        layer3.4.conv2.weight
        False
        True
        layer3.5.conv2.weight
        False
        True
        layer4.0.conv2.weight
        False
        True
        layer4.1.conv2.weight
        False
        True
        layer4.2.conv2.weight
        False
        True
        New non contiguous state dict:
        conv1.weight
        False
        layer1.0.conv2.weight
        False
        layer1.1.conv2.weight
        False
        layer1.2.conv2.weight
        False
        layer2.0.conv2.weight
        False
        layer2.1.conv2.weight
        False
        layer2.2.conv2.weight
        False
        layer2.3.conv2.weight
        False
        layer3.0.conv2.weight
        False
        layer3.1.conv2.weight
        False
        layer3.2.conv2.weight
        False
        layer3.3.conv2.weight
        False
        layer3.4.conv2.weight
        False
        layer3.5.conv2.weight
        False
        layer4.0.conv2.weight
        False
        layer4.1.conv2.weight
        False
        layer4.2.conv2.weight
        False

But we expect after load_state_dict, all the tensors are contiguious.

### Versions

        Collecting environment information...
        PyTorch version: 1.13.1+cpu
        Is debug build: False
        CUDA used to build PyTorch: None
        ROCM used to build PyTorch: N/A
        
        OS: Ubuntu 20.04.5 LTS (x86_64)
        GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
        Clang version: Could not collect
        CMake version: version 3.16.3
        Libc version: glibc-2.31
        
        Python version: 3.9.16 (main, Mar  1 2023, 18:22:10)  [GCC 11.2.0] (64-bit runtime)
        Python platform: Linux-5.15.0-1028-aws-x86_64-with-glibc2.31
        Is CUDA available: False
        CUDA runtime version: No CUDA
        CUDA_MODULE_LOADING set to: N/A
        GPU models and configuration: No CUDA
        Nvidia driver version: No CUDA
        cuDNN version: No CUDA
        HIP runtime version: N/A
        MIOpen runtime version: N/A
        Is XNNPACK available: True
        
        CPU:
        Architecture:                    x86_64
        CPU op-mode(s):                  32-bit, 64-bit
        Byte Order:                      Little Endian
        Address sizes:                   46 bits physical, 48 bits virtual
        CPU(s):                          4
        On-line CPU(s) list:             0-3
        Thread(s) per core:              1
        Core(s) per socket:              4
        Socket(s):                       1
        NUMA node(s):                    1
        Vendor ID:                       GenuineIntel
        CPU family:                      6
        Model:                           79
        Model name:                      Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
        Stepping:                        1
        CPU MHz:                         2299.988
        BogoMIPS:                        4600.14
        Hypervisor vendor:               Xen
        Virtualization type:             full
        L1d cache:                       128 KiB
        L1i cache:                       128 KiB
        L2 cache:                        1 MiB
        L3 cache:                        45 MiB
        NUMA node0 CPU(s):               0-3
        Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
        Vulnerability L1tf:              Mitigation; PTE Inversion
        Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
        Vulnerability Meltdown:          Mitigation; PTI
        Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
        Vulnerability Retbleed:          Not affected
        Vulnerability Spec store bypass: Vulnerable
        Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
        Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
        Vulnerability Srbds:             Not affected
        Vulnerability Tsx async abort:   Not affected
        Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
        
        Versions of relevant libraries:
        [pip3] intel-extension-for-pytorch==1.13.100+cpu
        [pip3] numpy==1.23.5
        [pip3] torch==1.13.1+cpu
        [pip3] torchvision==0.14.1+cpu
        [conda] blas                      1.0                         mkl    intel
        [conda] intel-extension-for-pytorch 1.13.100+cpu             pypi_0    pypi
        [conda] mkl                       2023.0.0            intel_25398    intel
        [conda] mkl-include               2023.0.0            intel_25398    intel
        [conda] mkl-service               2.4.0           py39h3605609_14    intel
        [conda] mkl_fft                   1.3.1           py39hcab1719_22    intel
        [conda] mkl_random                1.2.2           py39hbf47bc3_22    intel
        [conda] mkl_umath                 0.1.1           py39hf66a691_32    intel
        [conda] numpy                     1.23.5                   pypi_0    pypi
        [conda] numpy-base                1.22.3           py39h45c9ace_5    intel
        [conda] torch                     1.13.1+cpu               pypi_0    pypi
        [conda] torchvision               0.14.1+cpu               pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by jerrychenhf** [comment]
A little deep dive into the load_state_dict implementation and we found that it uses the following code to update the Tensor:

    with torch.no_grad():
        param.copy_(input_param)

Even if input_param is contiguious, we found that after param.copy_, param is still not contguious.
If I changed copy_ to set_, the result param is contiguious.

**Comment by albanD** [comment]
Hey!
As you found, this is the expected behavior indeed where the current Parameter/Buffer is kept and the content from the state dict is copied into it.

I think it would be a good addition to add the option to load the state dict by assignment instead of copy in the existing one. Doing `self._parameters[name] = input_param`.
This will have quite a deep impact (where the Tensor object is not preserved, the state_dict device will be preserved instead of the Module's one, etc) but I think it will bee a useful addition.

**Comment by jerrychenhf** [comment]
@albanD Thank you for looking into this and give the explanation.

The need here is to make sure all the parameters and buffers are contiguious because Hovovod check this.

For parameters, we can update with:

        with torch.no_grad():
                for name, param in module.named_parameters():
                    param.set_(param.contiguous())

While I don't find a way to update the buffers to contiguious and the load_state_dict is the way I found. But it seems the copy_ doesn't update for contiguious.

If there is no other to way to update the buffers for contiguious, an option for load_state_dict to allow this to be achieved is great.

**Comment by jbschlosser** [comment]
Discussed internally: an option to load by assignment (not set) instead of copy could be useful for more memory-efficient loading as well (some related issues around this proposing alternative solutions: #64601, #79967, #64327).

I don't believe this is a full solution itself, because there will still be 2 sets of parameters before `load_state_dict()` is called - one in the module itself and one in the `state_dict` to be passed to `load_state_dict()`, but combining it with a meta-instantiated module should avoid the need for the former copy. cc @albanD is my thinking here correct?

If we go this route, we will need to explicitly warn that anything that linked to the parameters before will be broken (e.g. optimizers pointing to the old parameters will need to be re-created, etc.).

Bikeshed area: flag to `load_state_dict()` could be `assign=False`.

**Comment by mikaylagawarecki** [comment]
Hey, you should be able to achieve the desired outcome if you use [`nn.Module.load_state_dict(assign=True)`](https://pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict). This available on main/the nightly but not yet in the latest release.

I reran your script with this argument and all the parameters were now contiguous :)

```
from torchvision import models
import torch
import copy

def make_contiguous(module):
    with torch.no_grad():
        state_dict = module.state_dict()
        state_dict=copy.deepcopy(state_dict)
        print("Non contiguous state dict:")
        for name, param in state_dict.items():
            if not param.is_contiguous():
                print(name)
                print(param.is_contiguous())
                state_dict[name] = param.contiguous()
                print(state_dict[name].is_contiguous())

    print("New non contiguous state dict:")
    module.load_state_dict(state_dict, assign=True)
    for name, param in module.state_dict().items():
        if not param.is_contiguous():
            print(name)
            print(param.is_contiguous())

def train(learning_rate):
    # Set up standard model.
    model = getattr(models, "resnet50")()
    model = model.to(memory_format=torch.channels_last)
    make_contiguous(model)

if __name__ == '__main__':
    train(0.1)
```

Output
```
Non contiguous state dict:
conv1.weight
False
True
layer1.0.conv2.weight
False
True
layer1.1.conv2.weight
False
True
layer1.2.conv2.weight
False
True
layer2.0.conv2.weight
False
True
layer2.1.conv2.weight
False
True
layer2.2.conv2.weight
False
True
layer2.3.conv2.weight
False
True
layer3.0.conv2.weight
False
True
layer3.1.conv2.weight
False
True
layer3.2.conv2.weight
False
True
layer3.3.conv2.weight
False
True
layer3.4.conv2.weight
False
True
layer3.5.conv2.weight
False
True
layer4.0.conv2.weight
False
True
layer4.1.conv2.weight
False
True
layer4.2.conv2.weight
False
True
New non contiguous state dict:
```

Closing as complete since this should be resolved. Feel free to reopen if you have further questions!
