### ISSUE TITLE
torch.tensor.argmax will get a error output when device='mps'

### ISSUE THREAD

**Issue by alsers** [pytorch/pytorch#98919]
### 🐛 Describe the bug

x = torch.tensor([[0.8639, 0.9540, 0.6444, 0.1574, 0.9168, 0.4858, 0.0886, 0.3538, 0.8792, 0.4206]]).to('mps')
x.argmax(1)

### Versions

(DML) alsers@zhuchenggangdeMacBook-Pro 2023.2 % python collect_env.py
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Jan 11 2023, 10:02:19)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.4.0           h89fa619_689    conda-forge
[conda] mkl-service               2.4.0            py39h9ed2024_0  
[conda] mkl_fft                   1.3.1            py39h4ab4a9b_0  
[conda] mkl_random                1.2.2            py39hb2f4e1b_0  
[conda] numpy                     1.23.5           py39he696674_0  
[conda] numpy-base                1.23.5           py39h9cd3388_0  
[conda] pytorch                   2.0.0                   py3.9_0    pytorch
[conda] torchaudio                2.0.0                  py39_cpu    pytorch
[conda] torchvision               0.15.0                 py39_cpu    pytorch

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment]
Related: #92311 #98191

**Comment by kulinseth** [comment]
Thanks @alsers for filing this issue. This issue is being tracked in https://github.com/pytorch/pytorch/issues/92311.
