### ISSUE TITLE
14k github models PT2 compilation time tracking 

### ISSUE THREAD

**Issue by shunting314** [pytorch/pytorch#98997]
We found some internal models have long compilation time. While people are debugging them, we also want to check if for the 14K oss models, some of them take especially long compilation time.

Here are the plan
- gather statistics for the compilation time for each of the 14K models
- analyze the distribution
- for the super slow ones, dig a bit.

A full run ( `PYTHONPATH=paritybench/ time python main.py` ) takes 3hour18minutes.
Overall output:
```
dynamo inductor ParityBench:
          total  passing  score
projects   1391     1152  82.8%
tests     12977    12573  96.9%
```

The compilation time metric: https://gist.github.com/shunting314/020220a36bfec3104422bbc5da293ca1 

From all the tests, only 5 models have wall time exceeding 100s:

```
model_id                                       dynamo_wall_time    eager_wall_time    wall_time_diff    _compile
-------------------------------------------  ------------------  -----------------  ----------------  ----------
test_D_X_Y_landmark_detection.HourglassNet              142.481              0.13            142.352     142.44
test_HazyResearch_butterfly.ResNet1202                  240.92               0.326           240.594     240.61
test_MandyMo_pytorch_HMR.HourGlass                      164.308              0.125           164.183     164.264
test_weiaicunzai_pytorch_cifar100.Attention             102.091              2.427            99.664      96.789
test_wwlCape_HAN.FullConvRes1                           462.473             65.151           397.323     384.731
```

Note:
- for some rows like `test_zudi_lin_pytorch_connectomics.ZeroPad1d 0.000 0.000 0.000 0.000` we found all the time metrics are 0. That's because the model is too simply and all the time are too small. With more precision, we can see: `test_zudi_lin_pytorch_connectomics.ZeroPad1d 0.000244206 0.000104298 0.000139908 0.000000000` .

- Checked 'test_wwlCape_HAN.FullConvRes1', inductor (`compile_fx` function) is not called. Should check dynamo why it does not call inductor. I've confirmed the backend name is 'inductor'
- `test_HazyResearch_butterfly.ResNet1202` : this one is a resnet. It's slow to compile because this is a version of resnet that contains too many blocks.  Note that resnet50 inference FX graph contains 1453 nodes, while this one contains 31845 nodes. It's 22x larger than resnet50!
- `test_MandyMo_pytorch_HMR.HourGlass` also has a large graph of 21119 nodes (14.5x larger than resnet50)
- `test_D_X_Y_landmark_detection.HourglassNet` has a graph with 18984 nodes (13x larger than resnet50)

To further understand the relationship between number of nodes and compilation time (or dynamo wall time as an estimation). Here I plot all the 12 tests in test_D_X_Y_landmark_detection.py. (Raw log here: https://gist.github.com/shunting314/d4eaa724570d0c4a876b354e2295a553 ,  Google spreadsheet: https://docs.google.com/spreadsheets/d/1hJEtf24dcITvTc2Lzdx5aZK9J1wExPf54t_HDW1MHZQ/edit#gid=0  )

<img width="697" alt="Screenshot 2023-04-12 at 11 17 42 PM" src="https://user-images.githubusercontent.com/52589240/231670514-9aa2aaee-2d6a-426c-b771-f7afb00944c9.png">

We can see a quite good relation between number of FX nodes and dynamo wall time.

cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @yanboliang @bertmaher @ngimel

**Comment by anijain2305** [comment]
@shunting314 closing this as this seem high priority. But please feel free to reopen if my conclusion is wrong.
