### ISSUE TITLE
Download speed is too slow in China.

### ISSUE THREAD

**Issue by benwu232** [pytorch/pytorch#990]
I tried to install pytorch in China. I tried pip or conda, both are two slow, only several kb/s, the download process can take a couple of days. After a while, the install process is terminated because of no response.

Is there any mirror in China? or can you add the installation package into pypi, so they can be automatically synchronized to the servers in China.

Thanks!

**Comment by soumith** [comment]
hi @benwu232 
Thanks for your feedback.

We just added cloudfront caching to our pip wheel downloads, so that a mirror in China will be able to download it fast and we serve them via https://downloads.pytorch.org

You can find the new pip download URLs on our website: http://pytorch.org/

**Comment by benwu232** [comment]
Thanks @soumith for your quick response! :)

Just had a try. Faster on new address, now it is about 100 KB/s. 
Still not on the mirror in China. 

I'm not sure about the mirror structure. If the command is like this:
pip install pytorch
or 
conda install pytorch
it can be synchronized by the mirror sites. 
Because the package is too big, it is worth doing this.
Thanks!

**Comment by tigerneil** [comment]
maybe use browser to download it first through proxy. 6mb/s

**Comment by shayanrc** [comment]
Facing the same problem here in India. Download speed ~ 15 kb/ps

**Comment by quoniammm** [comment]
Facing the same problem here in China again. Download speed ~ 8 kb/ps

**Comment by yangorwell** [comment]
recommend pip install, very fast

**Comment by CDLuminate** [comment]
I submitted a Mirror request at TUNA https://github.com/tuna/issues/issues/363

[TUNA](http://mirrors.tuna.tsinghua.edu.cn/) is the open source mirror of TsingHua University (China).

@soumith Are the python whls downloaded from pytorch.org redistributable? If so, TUNA members will be able to create a mirror for Pytorch without legal risk.

**Comment by soumith** [comment]
@CDLuminate for the TUNA project we grant redistributable permission. I can make a comment on that issue.

**Comment by data83** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/

**Comment by MindExp** [comment]
Finally solved this problem...

setp1: download the corresponding pytorch bz2 file form：**[https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/](https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/)**.      [extremly fast]

step2: install the bz2 file in anaconda through: **`conda install [your .bz2 directory]`**

ok, pytorch will be  installed  successfully no more than 1 minites...

AND THEN:

**`conda install torchvision`**

done.
Have fun with pytorch!

**Comment by andrewfowlie** [comment]
FYI, you can configure your pip to always use the China mirror by adding this to `~/.pip/pip.conf `
```
[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by chaoxiongTian** [comment]
Description : https://mirror.tuna.tsinghua.edu.cn/help/anaconda/
first:
```
# ubuntu
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
# for legacy win-64
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
```
second:
Description : https://pytorch.org/
```conda install pytorch torchvision -c pytorch```

**Comment by zxytim** [comment]
TUNA is going to stop mirroring anaconda packages due to authorization issue from Anaconda Inc.  Complete shutdown will be taken action in one month.
Here is a translated (into English) version of their statement:
https://translate.google.com/translate?source=osdd&sl=auto&tl=en&u=https%3A%2F%2Fmirrors.tuna.tsinghua.edu.cn%2Fnews%2Fclose-anaconda-service%2F

**Comment by andrewfowlie** [comment]
I guess the pip solution is unaffected? So using pip rather than conda would still work

**Comment by hzitoun** [comment]
Ended up doing like @MindExp with pytorch 1.1.0, CUDA 10 !

**Comment by leosh64** [comment]
> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple [some-package]
> you can use it to speed up.

This works in general, but the mirror seems to be outdated. E.g. when trying to install scipy this way, the mirror distributes version 1.2.x, while the "official" pypi mirror distributes version. 1.4.x

**Comment by jamestiotio** [comment]
> > pip install -i https://pypi.tuna.tsinghua.edu.cn/simple [some-package]
> > you can use it to speed up.
> 
> This works in general, but the mirror seems to be outdated. E.g. when trying to install scipy this way, the mirror distributes version 1.2.x, while the "official" pypi mirror distributes version. 1.4.x

Seems like the list is updated now. However, the list of PyTorch wheel packages [there](https://pypi.tuna.tsinghua.edu.cn/simple/torch/) does not seem to include the CUDA GPU versions.

**Comment by jasonrichdarmawan** [comment]
> > > pip install -i https://pypi.tuna.tsinghua.edu.cn/simple [some-package]
> > > you can use it to speed up.
> > 
> > 
> > This works in general, but the mirror seems to be outdated. E.g. when trying to install scipy this way, the mirror distributes version 1.2.x, while the "official" pypi mirror distributes version. 1.4.x
> 
> Seems like the list is updated now. However, the list of PyTorch wheel packages [there](https://pypi.tuna.tsinghua.edu.cn/simple/torch/) does not seem to include the CUDA GPU versions.

2024-09-24, there is no `cu124` on Tsinghua Open Source Mirror
