### ISSUE TITLE
create_graph_input and add_grapharg should be combined into one function

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#99007]
### 🐛 Describe the bug

@awgu came up with this: https://github.com/pytorch/pytorch/pull/98775#issuecomment-1503293308

It seems to me that the correct invariant is that they should always be called in lockstep. Maybe there is some funny business with constant source but that could be toggled with a kwarg. We should combine these two methods.

### Versions

master

cc @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @chauhang @aakhundov @soumith @anijain2305 @Xia-Weiwen @desertfire

**Comment by ezyang** [comment]
delisting this, I think I am hard blocked before this happens

**Comment by ezyang** [comment]
OK, so the reason we can't refactor this, is because there's an ordering problem. You need to create the proxy (insert the placeholder to FX) to make the TensorVariable, to get the fake tensor, but the GraphArg needs the fake tensor. Maybe you could do this all in one go, but the variable creation is shared with a lot of other code and wouldn't be so easy to extract.

**Comment by anijain2305** [comment]
@ezyang Any update on this one. Should we look into this?
