### ISSUE TITLE
3.7 cpu wheel compiled without numpy

### ISSUE THREAD

**Issue by jayanthkoushik** [pytorch/pytorch#9903]
The 3.7 wheel for cpu/linux appears to have been compiled without numpy support.

    $ python --version
    Python 3.7.0 (default, Jul 15 2018, 05:19:52)
    [GCC 8.1.0]
    $ python -m venv test_env
    $ source test_env/bin/activate
    (test_env) $ pip install numpy
    (test_env) $ pip install  http://download.pytorch.org/whl/cpu/torch-0.4.1-cp37-cp37m-linux_x86_64.whl
    (test_env) $ python
    >>> import numpy as np
    >>> import torch
    >>> torch.from_numpy(np.random.rand(1))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    RuntimeError: PyTorch was compiled without NumPy support
    >>>
    (test_env) $ wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
    $ python collect_env.py
    Collecting environment information...
    PyTorch version: 0.4.1
    Is debug build: No
    CUDA used to build PyTorch: Could not collect

    OS: CentOS release 6.9 (Final)
    GCC version: (GCC) 8.1.0
    CMake version: version 3.11.1

    Python version: 3.7
    Is CUDA available: No
    CUDA runtime version: 8.0.61
    GPU models and configuration:
    GPU 0: GeForce GTX 1080 Ti
    GPU 1: GeForce GTX 1080 Ti
    GPU 2: GeForce GTX 1080 Ti
    GPU 3: GeForce GTX 1080 Ti
    Nvidia driver version: 384.111
    cuDNN version: Could not collect
    Versions of relevant libraries:
    [pip3] numpy (1.15.0)[pip3] torch (0.4.1)
    [conda] Could not collect

**Comment by MillionIntegrals** [comment]
I'm getting the same issue with CUDA wheels for 3.7 as well.

**Comment by soumith** [comment]
sorry, i know what the issue is. We'll regenerate binaries and upload in a few hours.

**Comment by soumith** [comment]
the binaries have been regenerated, uploaded to PyPI and links to wheels have been updated on https://pytorch.org

Thanks a ton for reporting the issue.

**Comment by Kefas** [comment]
I'm still getting this issue for CUDA 9.0 python 3.7 wheel 
`http://download.pytorch.org/whl/cu90/torch-0.4.1-cp37-cp37m-linux_x86_64.whl`

**Comment by ozancaglayan** [comment]
Still the same for me as well.

**Comment by soumith** [comment]
@ozancaglayan just fyi afaik the issue is fixed now on nightly
