### ISSUE TITLE
torch.rand returns wrong 

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#99034]
### 🐛 Describe the bug

import torch
tensor = torch.rand([10, 1, 1048575, 1, 14, 11, 16, 8, 8, 0, 7, 8, 0, 14, 1], dtype=torch.float16)
print(tensor )

```
tensor([], size=(10, 1, 1048575, 1, 14, 11, 16, 8, 8, 0, 7, 8, 0, 14, 1), dtype=torch.float16)
```

The result returned is clearly wrong.

### Versions

pytorch: 2.0.0 + cu118

**Comment by Dragon-GCS** [comment]
I think this is because your dimensions contains zero. This error disappear when drop those zeros
