### ISSUE TITLE
Libtorch batch inference error

### ISSUE THREAD

**Issue by DavideCatto** [pytorch/pytorch#99036]
### 🐛 Describe the bug

I'm working in _Windows 10 Pro_ with _libtorch_ (libtorch-shared-2.0.0cpu) using VS2019 and I'm trying to execute the model in c++. I have exported the model using Python api and everything work without errors.
```python
traced_script_module.save("model.pt")
```
I have successfully loaded and execute the model using c++ (just only one tensor) and verify the correctness of the output model. Now i'm trying to execute a batch inference using more images, but it crash. 
Example code (_W=256, _H=256, inputMat=cv::Mat::zeros((256, 256)):
```c++
std::vector<torch::jit::IValue> inputs;
torch::Tensor inputTensor = torch::from_blob(inputMat.data, { 1, _W, _H, 3 }, torch::kFloat32);
inputTensor = inputTensor.permute({ 0, 3, 1, 2 }).to(_device); // BCHW format

// Using a batch = 1
inputs.push_back(inputTensor);
auto outputTensor = _model.forward(inputs).toTensor(); // Execution is OK!

// Usign batch = 2 (if modify the previous rows)
inputs.push_back(inputTensor);
inputs.push_back(inputTensor);
auto outputTensor = _model.forward(inputs).toTensor(); // CRASH!
```
Someone can help me? 

### Versions

OS: Microsoft Windows 10 Pro
CMake version: version 3.20.0-rc2

Python version: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: N/A

CPU:
Architecture=9
CurrentClockSpeed=3408
DeviceID=CPU0
Family=198
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3408
Name=Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
ProcessorType=3
Revision=24067

cc @jbschlosser

**Comment by cpuhrsch** [comment]
Hi @DavideCatto - can you share more detail on the crash in form of a gist or such?

**Comment by DavideCatto** [comment]
@cpuhrsch, trying to give you much information about the errors, i found the solution. 
I didnt have added to the execute path the *.pdb file (in order to debug errors) and after added these files the error was that for doing the forward process it s necessary to pass a Tensor and not a List of Tensor. So I have tried something like that and it works now:

```c++
// Concatenate a batch of tensors.
at::Tensor input1 = torch::ones({ 1,3,256,256});
at::Tensor input2 = torch::ones({ 1,3,256,256 });
at::Tensor inputsStacked = torch::cat({ input1,input2 }, 0);
// execute model

inputs.push_back(inputsStacked);
try
{
	auto test = _model.forward(inputs).toTensor(); // Now works!
}
catch (std::exception& e)
{
	std::cout << e.what() << std::endl;
}
```

Ty!
