### ISSUE TITLE
incorrect error message for cuda.FloatTensor.numpy()

### ISSUE THREAD

**Issue by willwhitney** [pytorch/pytorch#991]
When I try to call `.numpy()` on a tensor that's on the GPU, it says:

```
RuntimeError: numpy conversion for FloatTensor is not supported
```

This is pretty misleading. The fully-qualified name (`cuda.FloatTensor`) would be much clearer.

**Comment by fmassa** [comment]
Do you have latest install? I was expecting it to be fixed since https://github.com/pytorch/pytorch/commit/873ed4e6b6d9ebe89c7ffc469f08e807620922d2

**Comment by soumith** [comment]
yes, 0.1.10 has this fix. you are probably on 0.1.9?

**Comment by willwhitney** [comment]
Yup my bad.
