### ISSUE TITLE
Limitations of ValueRangeAnalysis

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#99102]
### 🐛 Describe the bug

When running `pytest test/inductor/test_torchinductor_dynamic_shapes.py -vk test_reflection_pad2d_backward_dynamic_shapes_cuda -s`, the last kernel generated has expressions like:

```python
    tmp3 = x0
    tmp4 = 1
    tmp5 = tmp3 >= tmp4
    tmp6 = tmp3 <= tmp4
    tmp7 = tmp5 & tmp6
```
Then `tmp7` is used in a number of loads.  I reckon that this sort of pattern should be caught and elided via the range analysis? cc @soumith @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @eellison 

### Versions

master

**Comment by lezcano** [comment]
FWIW, I found this when working on https://github.com/pytorch/pytorch/pull/98590. The CSE performed for the `device_assserts` includes the mask. This issue of having a mask that's the identity, implies that we are generating `device_asserts` for `mask` and `mask & True`

**Comment by eellison** [comment]
@lezcano I think is just an optimization that is not applied yet, but we should. Currently we're only using ValueRangeAnalysis in inductor codegen to turn int64 indexing expressions -> int32 indexing

**Comment by lezcano** [comment]
Discussing this one with @ysiraichi we realised that there's not much that can be simplified here from a value analysis point of view. Closing.
