### ISSUE TITLE
Invalid Reference to Class

### ISSUE THREAD

**Issue by SrivastavaKshitij** [pytorch/pytorch#99107]
### 📚 The doc issue

In this file, https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/_learnable_fake_quantize.py#L11

`For literature references, please see the class _LearnableFakeQuantizePerTensorOp.` 

`Class _LearnableFakeQuantizePerTensorOp's` implementation is missing in the repo. 

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by supriyar** [comment]
thanks for reporting. We will update the documentation.
 
assigning @andrewor14  for now

**Comment by rk7697** [comment]
Sorry, as a question, I don't think I see any existing documentation for learnable fake quantization in the [quantization documentation](https://pytorch.org/docs/stable/quantization.html#module-torch.ao.quantization) or in [this](https://pytorch.org/blog/introduction-to-quantization-on-pytorch/) quantization introduction blog. I'm also not very familiar with this concept. Would it be better to just remove the sentence "For literature references, please see the class _LearnableFakeQuantizePerTensorOp."? I was not sure if this would be helpful, though, sorry.
