### ISSUE TITLE
The CTCLoss method doc does not specify what the `sum` option in `reduction` does

### ISSUE THREAD

**Issue by grazder** [pytorch/pytorch#99141]
### 📚 The doc issue

The CTCLoss method doc does not specify what the `sum` option in `reduction` does

https://github.com/pytorch/pytorch/blob/6a50b83b739c2d37d0f518f98b8e624eca0ea153/torch/nn/modules/loss.py#L1624

### Suggest a potential alternative/fix

Specify what `sum` does

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by grazder** [comment]
![image](https://user-images.githubusercontent.com/21354805/232023511-8ddcdabb-b95b-4373-b8b4-3f5db107cd5f.png)

also there is no output form specification for reduction types

**Comment by jbschlosser** [comment]
Sure, we'd accept a PR clarifying this in the docs.
