### ISSUE TITLE
TORCH_COMPILE_ABLATE envvar

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#99155]
### 🐛 Describe the bug

I propose we add this envvar. Here's what it does:

* `TORCH_COMPILE_ABLATE=inductor`: stop using inductor in all torch.compile calls, if it was being used
* `TORCH_COMPILE_ABLATE=aot`: stop using AOTAutograd in all torch.compile calls, if it was being used. This implies inductor
* anything else people want to add. For example, we could ablate optimizations, etc

You can use this to easily pinpoint if a particular component is causing a problem.

Bikeshedding name is also OK. Other proposal is `TORCH_COMPILE_DISABLE`

### Versions

master

cc @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @soumith @ngimel @desertfire

**Comment by wconstab** [comment]
I have similar concerns.

1) ABLATE=inductor is a bit specific; it's gonna disable inductor if enabled, but no-op for other backends.  i'm wondering if we want it to be an inductor specific env or a compile specific env.  Should it just be COMPILE_DISABLE?
2) COMPILE_DISABLE seems also a bit risky: if it is set and then compile is silently not working, we should be sure to at least issue a warn_once
3) disabling wholesale seems like a useful thing, but i can imagine more use cases for disabling specific backend features.  Do we want to solve just the wholesale problem first?

**Comment by ezyang** [comment]
> What problem are you trying to solve? Is it "I want to be able to write a 1-2 sentence comment to tell someone how to ablate their compilation problem instead of of linking to a debugging page that no one will read?" :).

Yes! In particular, I suspect that when we get users who are turning on PT2 via some indirect configuration knob (i.e., they never wrote `torch.compile` themselves), an envvar will be the most reliable way to instruct them how to ablate.

> Instead, you typically want to be able to ablate with a higher-level (possibly bisection-style) script or something anyway. So in this case you just need ways of controlling optimization levels via command line or environment variables and a nice script wrapper that does ablation for you. You don't add any complexity or BC concerns to the main program either.

Except in fbcode setting, I typically have no control over the high level runner which is running my program, and so there is no logical place to do this interposition (library vs framework distinction).

> ABLATE=inductor is a bit specific; it's gonna disable inductor if enabled, but no-op for other backends.

The point is that once you ablate a component, if it is still bugged, you know it wasn't that component's fault.

> COMPILE_DISABLE seems also a bit risky: if it is set and then compile is silently not working, we should be sure to at least issue a warn_once

Agreed, definitely should warn. Maybe even figure out how to do the warning at both the beginning and end of execution.

> disabling wholesale seems like a useful thing, but i can imagine more use cases for disabling specific backend features. Do we want to solve just the wholesale problem first?

I think the envvar can grow to support disabling all sorts of random things. But ablating inductor and aotautograd are the most useful things right now.

**Comment by anijain2305** [comment]
@ezyang turning on low priority for this one. Feel free to remove it.
