### ISSUE TITLE
`torch.autograd.graph.Node.register_hook` can override `grad_inputs`, not `grad_outputs`

### ISSUE THREAD

**Issue by olokshyn** [pytorch/pytorch#99165]
### 📚 The doc issue

The docs on [torch.autograd.graph.Node.register_hook](https://pytorch.org/docs/stable/generated/torch.autograd.graph.Node.register_hook.html#torch.autograd.graph.Node.register_hook) method state that:

> The hook should not modify its argument, but it can optionally return a new gradient which will be used in place of `grad_outputs`.

However, the return value (if any) of the hook is used instead of `grad_inputs`, NOT `grad_outputs`.

Using the hook's return value as `grad_inputs` makes much more sense, as that's the gradient value a user may want to override with the hook, while overriding `grad_outpus` is pointless since `grad_inputs` is already computed and will be used by upstream nodes.

This can be easily demonstrated by registering a hook on the `AddBackward0` node that has two inputs and only one output. The mismatch in the number of inputs and outputs is important, as it dictates the sizes of the tuples inside the hook. When the hook returns `grad_inputs` unmodified, the code works. On the other hand, returning `grad_outputs` unmodified results in a `RuntimeError`.

```python
from typing import Optional

import torch


def node_hook(
    grad_inputs: tuple[torch.Tensor],
    grad_outputs: tuple[torch.Tensor],
) -> Optional[tuple[torch.Tensor]]:
  print(
      f"grad_inputs: {grad_inputs}\n"
      f"grad_outputs: {grad_outputs}"
  )
  # Returning `grad_inputs` work, but returning `grad_outputs` fails.
  return grad_inputs
  # return grad_outputs  # RuntimeError: hook 'node_hook' has returned an incorrect number of values (got 1, but expected 2)


a = torch.tensor([1.0], requires_grad=True)
b = torch.tensor([2.0], requires_grad=True)
c = a + b
# c.grad_fn is AddBackward0 which has two inputs and one output.
c.grad_fn.register_hook(node_hook)
c.backward()

```

### Suggest a potential alternative/fix

Just replace `grad_outputs` with `grad_inputs` in the docs:

```
diff --git a/torch/autograd/graph.py b/torch/autograd/graph.py
index c0cce511307..a0530c482e3 100644
--- a/torch/autograd/graph.py
+++ b/torch/autograd/graph.py
@@ -58,7 +58,7 @@ class Node(abc.ABC):
 
 
         The hook should not modify its argument, but it can optionally return
-        a new gradient which will be used in place of :attr:`grad_outputs`.
+        a new gradient which will be used in place of :attr:`grad_inputs`.
 
         This function returns a handle with a method ``handle.remove()``
         that removes the hook from the module.
```

cc @svekars @carljparker @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by olokshyn** [comment]
Can I get a write access to this repo?
```
olehlokshyn:~/Projects/pytorch$ git push --set-upstream origin fix/docs-node-register_hook
ERROR: Permission to pytorch/pytorch.git denied to olokshyn.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I can `git pull` from the repo, though.

**Comment by ezyang** [comment]
I'd suggest pushing to a fork and then opening a PR from it.
