### ISSUE TITLE
vmap-jacrev normalisation bug

### ISSUE THREAD

**Issue by Atcold** [pytorch/pytorch#99187]
## 🐛 Describe the bug

`vmap` and `jacrev` won't work when a normalisation is performed.

```python
import torch
from torch.func import vmap, jacrev
t_data = torch.randn(3, 2)
f = lambda t: torch.nn.functional.normalize(t)
J = vmap(jacrev(f))
J_t = J(t_data)
```
returns
```
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```
Same happens when
```python
def normalise(t):
    n = t.norm(dim=1, keepdim=True)
    return t / n
f = normalise
```
If I define my own norm and alternative normalisation
```python
norm = lambda t: t[:,[0]].pow(2).add(t[:,[1]].pow(2)).sqrt()
def normalise2(t):
    n = norm(t)
    return t / n
f = normalise2
```
the error changes to
```python
Cell In[141], line 1, in <lambda>(t)
----> 1 norm = lambda t: t[:,[0]].pow(2).add(t[:,[1]].pow(2)).sqrt()

IndexError: too many indices for tensor of dimension 1
```

## Workaround

Omitting `vmap` lets me get around the issue.
```python
J = jacrev(f)
J_t = J(t_data)
```
runs without problems. So, I'm running an ugly `for`-loop within Python, at the moment.

## Context

All I'm trying to compute here is:

$$f(x,y) =
\begin{pmatrix}
\displaystyle \frac{x}{\sqrt{x^2+y^2}} \\
\displaystyle \frac{y}{\sqrt{x^2+y^2}} 
\end{pmatrix}, \quad
\nabla \cdot f(x,y) = \frac{1}{\sqrt{x^2+y^2}}
$$

and evaluate $\nabla \cdot f(x,y)$ over a batched input (*i.e.* an input grid).

Here's $f(x,y)$:

![image](https://user-images.githubusercontent.com/2119355/232138454-d07ca236-8f4f-4753-93c9-1c426ee41587.png)

And here's $\nabla \cdot f(x,y)$:

![image](https://user-images.githubusercontent.com/2119355/232138598-df34bb19-21dc-47bb-9f15-a069d3bfe642.png) ![image](https://user-images.githubusercontent.com/2119355/232138618-b8510dd3-c95b-4c5b-93c5-c3538dd387f7.png)

## Versions

PyTorch 2.0

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by zou3519** [comment]
Something is likely wrong in a batching rule somewhere, we'll try to prioritize this.

**Comment by zou3519** [comment]
I'm a bit confused. For the first example:
```py
import torch
from torch.func import vmap, jacrev
t_data = torch.randn(3, 2)
f = lambda t: torch.nn.functional.normalize(t)
J = vmap(jacrev(f))
J_t = J(t_data)
```
the semantics of this are as if we were running jacrev(f) in a for-loop over t_data:
```py
import torch
from torch.func import vmap, jacrev
t_data = torch.randn(3, 2)
f = lambda t: torch.nn.functional.normalize(t)
J = [jacrev(f)(t_data_i) for t_data_i in t_data.unbind(0)]
```
Both of the above scripts give us the error message "IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)", so it looks like things are working as expected.
"
Did you just want the following code?
```py
import torch
from torch.func import vmap, jacrev
t_data = torch.randn(3, 2)
f = lambda t: torch.nn.functional.normalize(t, dim=0)
J = vmap(jacrev(f))
J_t = J(t_data)
```

**Comment by Atcold** [comment]
Yes, I want to get the Jacobian for a batch of data.

> so it looks like things are working as expected.

No, it's not expected to break.
`t_data` is a batch of `3` vectors of size `2`.
`f` is making these vectors unit-norm.

Also, what is `unbind(0)`? I've never seen that before.

**Comment by Atcold** [comment]
Ah… What I should have used is `dim=-1`… 😐😐😐
I wonder whether this should be the default for `torch.nn.functional.normalize`.

**Comment by zou3519** [comment]
> Also, what is unbind(0)? I've never seen that before.

tensor.unbind(dim) "un-stacks" the tensor at the dimension. i.e. it returns `[tensor.select(dim, 0), tensor.select(dim, 1), ...]`

> Ah… What I should have used is dim=-1… 😐😐😐
I wonder whether this should be the default for torch.nn.functional.normalize.

It likely should have been the default, but at this point we will have BC problems if we change it :/

**Comment by Atcold** [comment]
> > Ah… What I should have used is `dim=-1`… 😐😐😐
> > I wonder whether this should be the default for `torch.nn.functional.normalize`.
> 
> It likely should have been the default, but at this point we will have BC problems if we change it :/

Would it?
Can you make / find a case where someone relies on `dim=1` which is not meant to be `dim=-1`?
