### ISSUE TITLE
a bug occurs in torch.nn.Linear 

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#99226]
### 🐛 Describe the bug

```
import torch
arg_1 = 1024
arg_2 = 64
arg_3 = False
arg_class = torch.nn.Linear(in_features=arg_1,out_features=arg_2,bias=arg_3,)
arg_4_0_tensor = torch.randint(-4096,1,[11, 0, 1024], dtype=torch.int16)
arg_4_0 = arg_4_0_tensor.clone()
arg_4 = [arg_4_0,]
res = arg_class(*arg_4)
print(res)
```
When above code runs, it throw an exception: `RuntimeError: isDifferentiableType(variable.scalar_type()) INTERNAL ASSERT FAILED at "../torch/csrc/autograd/functions/utils.h":75, please report a bug to PyTorch. ` But all parameters are valid. Is this problem caused by the API not being able to handle data of type int16? If so, it should throw an exception for the reason rather than show above exception message.

### Versions

pytorch version: 2.0.0+cu118

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by gusty1g** [comment]
I think it is to do with `torch.randint(-4096, 1, [11, 0, 1024])`. Here, when one of the dimension is 0, the tensor is None.

Setting `arg_4_0_tensor = torch.randint(-4096, 1, [11, 1, 1024], dtype=torch.int16)`, pytorch throws a meaningful error `RuntimeError: expected scalar type Short but found Float`

**Comment by cheyennee** [comment]
@gusty1g I tried it and it was indeed like you said. But I think that when tensor is None, it should also need to display meaningful error information, otherwise users don't know why the error is reported here.

**Comment by albanD** [comment]
This is most likely due to a weird interaction in the type promotion with int16 that leads to the output being of integer type but trying to require gradients (not possible since it is not a continuous dtype).
This most likely means that either type promotion is bad or an autograd formula output differentiability needs to be updated to skip some dtypes.

**Comment by jbschlosser** [comment]
Actually, I think there are things that depend on being able to pass an empty input, so we can't error for that case. Deferring to @albanD's comment :)
