### ISSUE TITLE
Intel Mac build fails with “.intel_syntax” errors in FBGEMM

### ISSUE THREAD

**Issue by rlanday** [pytorch/pytorch#99223]
### 🐛 Describe the bug

I am trying to build master on an Intel Mac (with Apple clang version 14.0.3 on macOS 13.2.1) and got errors in these files (not necessarily an exhaustive list, since the build stopped):

- FbgemmFP16UKernelsAvx2.cc
- FbgemmFP16UKernelsAvx512.cc
- FbgemmFP16UKernelsAvx512_256.cc

The errors are of the form:
```
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:16:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:188:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:386:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:548:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:729:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
/Users/rlanday/Documents/source/pytorch/third_party/fbgemm/src/FbgemmFP16UKernelsAvx2.cc:929:8: error: unknown token in expression
      ".intel_syntax noprefix\t\n"
       ^
<inline asm>:2:18: note: instantiated into assembly here
        mov [rbp - 56], %r14    
                        ^
6 errors generated.
```

A related issue was reported in https://github.com/pytorch/pytorch/issues/85956 and then reportedly fixed, but then apparently there was a clang change that broke it again (someone replied in that issue that the fix didn’t actually work, so that’s another possibility). The issue was re-fixed in https://github.com/pytorch/FBGEMM/pull/1254 but the fbgemm dependency needs to be updated in PyTorch to include that change.

Is building on Intel Mac still a supported configuration? I noticed the CI machines all seem to running macOS 12 (Monterey) on Apple Silicon:

https://hud.pytorch.org/

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.0
Libc version: N/A

Python version: 3.10.0 (default, Oct 17 2021, 22:59:24) [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-13.2.1-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] torch==1.13.0
[conda] mkl                       2022.1.0           hf3af037_209  
[conda] mkl-include               2022.1.0           hecd8cb5_209  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.20.3           py37h0fa1045_0  
[conda] numpy-base                1.20.3           py37hbbe2e76_0  
[conda] torch                     1.9.0                    pypi_0    pypi

cc @malfet @seemethere @albanD

**Comment by rlanday** [comment]
After fixing some other issues with my setup (I also had to straighten out a protobuf header issue by running “brew uninstall protobuf pytorch”), I can confirm that rolling forward the fbgemm dependency is sufficient to make the build complete on my Intel Mac.

**Comment by malfet** [comment]
Taking an AI to update fbgemm pin. @rlanday please confirm which version of fbgemm have you used. 
And yes, building for x86 is still supported, you can find Intel Mac configs in hud as well, see https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=macos-12-py3-x86_64

**Comment by rlanday** [comment]
Thanks for pointing that out. According to the note on the fix in https://github.com/pytorch/FBGEMM/pull/1254, the issue is specific to Clang 14, which might explain why the issue is not occurring on macOS 12.

I tested with fbgemm at e07dda2d50562f534abc682b0dc79a8cd5ce819d.
