### ISSUE TITLE
the error message of torch.nn.functional.embedding_bag is not clear

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#99221]
### 🐛 Describe the bug

```
import torch
arg_1 = torch.as_tensor([2])
arg_2 = torch.rand([2, 3], dtype=torch.float32)
arg_3 = torch.as_tensor([0])
res = torch.nn.functional.embedding_bag(input=arg_1,weight=arg_2,offsets=arg_3)
print(res)
```
Above code will throw an exception: `RuntimeError: Index 0 is out of bounds: 2, range 0 to 2`. This error message is not clear, because the range of `Index 0` is greater than or equal to 0 and less than 2. The message `range 0 to 2` is a little confused and people will think that `Index 0` can take the value of 2.

### Versions

pytorch version: 2.0.0+cu118

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by MylesJP** [comment]
Hi Cheyennee, I can take a look at this if it's still open. I'm looking for a documentation-related issue for a school project so this should work well.

**Comment by jbschlosser** [comment]
@MylesJP Feel free to open a PR addressing this and we'll review it
