### ISSUE TITLE
default_collate inconsistently structured data

### ISSUE THREAD

**Issue by YodaEmbedding** [pytorch/pytorch#99227]
### 🐛 Describe the bug

`default_collate` changed behavior between PyTorch v1 and v2:

**v1.x (expected, type-theoretically sound):**

```python
>>> default_collate([{"strings": b"abc"}])
{'strings': [b'abc']}

>>> default_collate([{"strings": b"abc"}, {"strings": b"ABC"}])
{'strings': [b'abc', b'ABC']}


>>> default_collate([{"strings": [b"abc"]}])
{'strings': [(b'abc',)]}

>>> default_collate([{"strings": [b"abc"]}, {"strings": [b"ABC"]}])
{'strings': [(b'abc', b'ABC')]}
```

**v2.x (unpredictable, inconsistent types):**
```python
>>> default_collate([{"strings": b"abc"}])
{'strings': b'abc'}

>>> default_collate([{"strings": b"abc"}, {"strings": b"ABC"}])
{'strings': [tensor([97, 65]), tensor([98, 66]), tensor([99, 67])]}


>>> default_collate([{"strings": [b"abc"]}])
{'strings': [b'abc']}

>>> default_collate([{"strings": [b"abc"]}, {"strings": [b"ABC"]}])
{'strings': [[tensor([97, 65]), tensor([98, 66]), tensor([99, 67])]]}
```

Is this the intended behavior? Can users still access the old behavior? The old behavior preserves the correct structure, and is effectively a "[transpose](https://stackoverflow.com/questions/5558418/list-of-dicts-to-from-dict-of-lists) and batching" of the input data.

### Versions

<details>

<summary>Click to expand</summary>

Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 12.2.1 20230201
Clang version: 15.0.7
CMake version: version 3.26.0
Libc version: glibc-2.37

Python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-6.2.2-arch1-1-x86_64-with-glibc2.37
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1060 6GB
Nvidia driver version: 525.89.02
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.6.0
/usr/lib/libcudnn_adv_infer.so.8.6.0
/usr/lib/libcudnn_adv_train.so.8.6.0
/usr/lib/libcudnn_cnn_infer.so.8.6.0
/usr/lib/libcudnn_cnn_train.so.8.6.0
/usr/lib/libcudnn_ops_infer.so.8.6.0
/usr/lib/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
CPU family:                      6
Model:                           94
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        3
CPU(s) scaling MHz:              22%
CPU max MHz:                     3600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6402.62
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        1 MiB (4 instances)
L3 cache:                        6 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-msssim==0.2.1
[pip3] torch==2.0.0
[pip3] torchvision==0.15.1
[pip3] triton==2.0.0
[conda] Could not collect

</details>

cc @ezyang @gchanan @zou3519 @VitalyFedyunin @ejguan @NivekT @dzhulgakov

**Comment by NivekT** [comment]
@jbschlosser is correct. @YodaEmbedding please let us know if you still see this issue in the nightly version. Otherwise, this is resolved.
