### ISSUE TITLE
accessing the attributes of grad_fn such as kernel_size, stride

### ISSUE THREAD

**Issue by Weyne168** [pytorch/pytorch#9922]
## Issue description
Are there any methods to get the conv module input params from the ‘grad_fn’ in the newest version of pytorch?

in pytorch 0.2, we can get convolution parameters, such as kernel_size, padding, and stride from grad_fn, this way is very useful to convert the trained model to caffe prototxt.
but, in pytorch 0.4, the ThnnConv2DBackward and CudnnConvolutionBackward  do not support this way.

for example,in pytorch version 0.2,

## Code example
modle = nn.Conv2d(in_channels=3 out_channels=32, kernel_size=3,stride=2, padding=1, dilation=1))
y = modle(x)

Then, we can get the input param’s values like kernel_size、stride、padding value use y.grad_fn.kernel_size，y.grad_fn.padding,……

but now, in pytorch 0.4, it report that 
"AttributeError: 'CudnnConvolutionBackward' object has no attribute 'kernel_size'"

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by zou3519** [comment]
cc @apaszke what do you think?

**Comment by Weyne168** [comment]
I want to convert the parameters trained by PyTorch 0.4.0 to prototxt of caffe and caffemodel

**Comment by daodao316** [comment]
Have you solved this problem?

**Comment by blueardour** [comment]
+1

**Comment by zym1119** [comment]
i find the same problem as well
when print dir(out.grad_fn)
in 0.2.0 you will get 
['__call__', '__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_register_hook_dict', 'dilation', 'groups', 'next_functions', 'output_padding', 'padding', 'register_hook', 'stride', 'transposed'] which has many parameters
in 0.4.0 you will get
['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_register_hook_dict', 'metadata', 'next_functions', 'register_hook', 'requires_grad']
i can only get weights and bias from next_functions

**Comment by albanD** [comment]
This behavior is due to the fact that the conv Function was moved from python code to cpp code for efficiency.
So all the parameters are now passed directly to the cpp Functionsand are not accessible from python.

**Comment by blueardour** [comment]
Hi, @albanD  Thank you for pointing out the reason. I wonder if it is still possible to export the kernel size, stride... parameters from the cpp code for conv or pooling layer?  Would the export impact the elegance of the code?  I'm not quite familiar with whole pytorch code currently, even though I'm struggling to read it. Could you talk a bit more about why the parameters are not likely to be available after moving into cpp code?

**Comment by yxchng** [comment]
Any updates on this?

**Comment by zou3519** [comment]
I don't think we have a plan to expose grad_fn internal in Python. Given the amount of support on this issue, though, we are open to reconsidering.

**Comment by blueardour** [comment]
Hi, I original focused on the issue because I want to convert pytorch model to caffe. I noticed some other people (for example @Weyne168) in this thread also had the same request.

As the thread was not updated for a while, I later found another solution to finish the task. The hint is to convert pytorch to onnx first and then convert onnx to caffe.  Thus, from my aspect, I might not require the feature anymore. 
Maybe still there's  demand for the feature from other people.  Just bless~     ^_^

**Comment by taoari** [comment]
For those who are still interested. One of the possible solutions:

```python

import torch
import torch.nn as nn

def hook(module, inputs, output):
    if torch.is_tensor(output):
        if 'module' not in output.grad_fn.metadata:
            output.grad_fn.metadata['module'] = module
        if 'output' not in output.grad_fn.metadata:
            output.grad_fn.metadata['output'] = output
            
def register_forward_hooks(model, hook):
    for name, mod in model.named_modules():
        if not mod._modules: # is a leaf module
            mod.register_forward_hook(hook)    
        
model = nn.Conv2d(10, 10, 3)
register_forward_hooks(model, hook)
inputs = (torch.randn(2,10,32,32),)
output = model(*inputs)
print(output.grad_fn.metadata['module'].kernel_size)
print(output.grad_fn.metadata['output'].shape)
```

Really hope that there is an official way to trace back module and output shape info from grad_fn, e.g. `grad_fn.module` to retrieve all the module information.
