### ISSUE TITLE
Cuda 9.2 pip install having trouble finding the right cuda

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [pytorch/pytorch#9923]
## Issue description

As the binaries for 0.4.1 just added support for 9.2, I decided to upgrade to cuda 9.2 and upgrade pytorch. I purged my cuda 9.0 install and made sure locate cuda-9-0 gave no results and also made sure that the LD_LIBRARY_PATH, PATH, and CUDA_HOME all don't reference cuda-9-0 anymore. nvcc -V also shows 9.2 as the version present. When I try importing torch, I get this error 

ImportError: libcurand.so.9.0: cannot open shared object file: No such file or directory

indicating it's still looking for cuda 9.0 for some reason. Is there anything else besides those 3 environment variables that I'd need to fix?

- PyTorch or Caffe2: Pytorch
- How you installed PyTorch (conda, pip, source): pip
- OS: Ubuntu 16.04
- PyTorch version: 0.4.1
- Python version: 3.5 (although I tried with 3.6 and that failed too)
- CUDA/cuDNN version: 9.2/7.1.4
- GPU models and configuration: 1080 ti * 4

**Comment by soumith** [comment]
what is the command that you used to install?

There's absolutely no question of the cuda 9.2 binary being dependent on `libcurand.so`, as we statically link to curand. I double-checked the binaries just now to see that they declare no such dependencies. Are you loading any other library that needs CUDA?

**Comment by aosokin** [comment]
Had very similar issue when upgrading to pytorch 4.1 with conda. Reboot solved the problem.

**Comment by hmc-cs-mdrissi** [comment]
The command I used to install it was:

sudo -H python3.6 -m pip install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl (for 3.5 same thing just swapping the 3.6/36 by 3.5/35)

As for what I load, to get the error I just run python 3.6, and then in the interactive shell, just type import torch and that's enough to trigger the error. The full interactive shell output just looks like:

Python 3.6.6 (default, Jun 28 2018, 04:42:43) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: libcurand.so.9.0: cannot open shared object file: No such file or directory

As I was trying to explore it, I discovered that sudo python3/python3.6 and then import torch works fine. That made me guess it'd be an environment variable, except the values of path/ld_library_path/cuda_home/cuda_root look the same when echo them with/without sudo. There values are,

Path - /home/mehdi2277/Android/Sdk/tools:/home/mehdi2277/Android/Sdk/platform-tools:/home/mehdi2277/.local/share/umake/bin:/home/mehdi2277/torch/install/bin:/home/mehdi2277/bin:/home/mehdi2277/.local/bin:/home/mehdi2277/torch/install/bin:/opt/intel/compilers_and_libraries_2017.4.196/linux/bin/intel64:/home/mehdi2277/opam-coq.8.6/4.01.0/bin:/home/mehdi2277/Android/Sdk/tools:/home/mehdi2277/Android/Sdk/platform-tools:/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/mehdi2277/Android/Sdk/tools/bin

LD_LIBRARY_PATH - /home/mehdi2277/torch/install/lib:/home/mehdi2277/torch/install/lib:/opt/intel/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2017.4.196/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2017.4.196/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2017.4.196/linux/tbb/lib/intel64_lin/gcc4.7:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/lib

CUDA_HOME - /usr/local/cuda

CUDA_ROOT - /usr/local/cuda/bin

Any other ideas for why it works fine with sudo, but not fine without it?

**Comment by soumith** [comment]
@hmc-cs-mdrissi you probably have some library that is being loaded that is looking for `libcudart.so`. Running with `strace python` might give you a hint
