### ISSUE TITLE
Broken link for torch dynamo FAQ in docs

### ISSUE THREAD

**Issue by abdulazizab2** [pytorch/pytorch#99247]
### 📚 The doc issue

I was reading in the docs and learning about torch dynamo (its very cool ;)). There was a broken link that redirects the user to a "dead end" page. I created a PR to correct the link in the docs.

#99242 

### Suggest a potential alternative/fix

Correct the link as in the PR (maybe?)

**Comment by MylesJP** [comment]
Mind if I take a shot at this for a school project?

**Comment by mingxzhao** [comment]
New Getting Started doc located at 

docs/source/torch.compiler_get_started.rst 

Shares folder with master compiler_faq doc, issue can be closed 

@msaroufim
