### ISSUE TITLE
[Caffe2]Build caffe2 for android having large .a lib

### ISSUE THREAD

**Issue by wang5566** [pytorch/pytorch#9925]
I built caffe2 for android using script/build_android.sh and passed through. But I got libcaffe2.a not libcaffe2.so and the .a lib is too large about 1G. Is it normal?

**Comment by soumith** [comment]
@wang5566 yes this is normal. After linking in app, size becomes much smaller, because most symbols and debug info are removed

**Comment by zhyj3038** [comment]
with pytorch1.0, my libcaffe2.a is 2.1G,  after linking in app, the *.so is about 9m, and the apk size increse 4M.  can it be smaller?

**Comment by dragen1860** [comment]
@zhyj3038 Hi, I am interested in pytorch deployment. But i am not familiar with android. May i ask how to convert libcaffe2.a to libcaffe2.so? Please give me some tips.
