### ISSUE TITLE
torch.repeat_interleave works when there is no input

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#99259]
### 🐛 Describe the bug

```
import torch
arg_1 = torch.randint(0,512,[2], dtype=torch.int64)
res = torch.repeat_interleave(repeats=arg_1,)
print(res)
# res: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,......
```
Above code works, when there is no input tensor. But according to [doc](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html), `input` is needed，not optional. 

### Versions

pytorch version: 2.0.0+cu118

cc @svekars @carljparker

**Comment by PSY222** [comment]
I did some additional experiments to check the outputs of torch.repeat_interleave without an 'input' argument. (torch.__version__ is 2.0.0+cu118')

```
res1 = torch.repeat_interleave(arg_1)
res2 = torch.repeat_interleave(repeats=arg_1)
res3 = torch.repeat_interleave(repeats=arg_1,)
```

If we suppose the result of torch.randint(0,512,[3]) as a tensor([a,b,c[) value, all the results(res1,res2,res3) show identical results; 'a' numbers of zero, 'b' numbers of one and 'c' numbers of two. 

It seems like 'input' argument is not raising TypeError with a message stating that 'input' argument is required, but instead automatically repeating each number in the range(n) numbers as much as given one dimensional vector arg_1.

**Comment by jbschlosser** [comment]
At the bottom of the [`repeat_interleave()` docs](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html), the behavior for the `repeats`-only overload is documented. Ideally, we should fix the doc formatting so this overload is at the same indentation level as the first overload.

**Comment by cheyennee** [comment]
@jbschlosser I just saw the description at the bottom of the document😂. The documentation should indeed be modified, otherwise it is easy to confuse users.
