### ISSUE TITLE
libtorch multi-thread

### ISSUE THREAD

**Issue by wxthu** [pytorch/pytorch#99263]
### 🐛 Describe the bug

I made DL inferences under multiple threads in libtorch as following:
```
#include <torch/torch.h>
#include <torch/script.h>

#include <nvToolsExt.h>
#include <unistd.h>
#include <iostream>
#include <string>
#include <vector>
#include <thread>
#include <semaphore.h>
#include <pthread.h>
#include <atomic>

torch::Device device(torch::kCUDA);
int thread_num = 2;
sem_t barrier;
std::atomic<int> count(thread_num);

void solo_run(torch::jit::script::Module& model, std::vector<torch::jit::IValue>& imgs)
{
	model.to(device);
	for (int i = 0; i < 100; ++i)
		model.forward(imgs);

	torch::cuda::synchronize();
}

void parallel(torch::jit::script::Module model)
{
	model.to(device);
	torch::Tensor img = torch::rand({4, 3, 224, 224}).to(device);
	std::vector<torch::jit::IValue> imgs;
	imgs.push_back(img);

	count--;
	if (count == 0) {
		for (int i = 0; i < thread_num; ++i) {
			sem_post(&barrier);
		}
	}
	sem_wait(&barrier);

	nvtxRangePushA("PARALLEL");
	for (int i = 0; i < 100; ++i)
		model.forward(imgs);
	
	nvtxRangePop();
}

int main(int arc, char** argv) {
	sem_init(&barrier, 0, 0);

	c10::InferenceMode guard(true);
	torch::Tensor img = torch::rand({4, 3, 224, 224}).to(device);
	std::vector<torch::jit::IValue> inputs;
	inputs.push_back(img);
	std::string model_path = argv[1];

	torch::jit::script::Module model = torch::jit::load(model_path);
	// auto model = torch::jit::load(model_path);

	std::vector<torch::jit::script::Module> models;
	for (int i = 0; i < thread_num; ++i) {
		models.push_back(torch::jit::load(model_path));
	}
	if(torch::cuda::is_available()) {
		std::cout << "CUDA now is available ! Inference on GPU." << std::endl;
	}
	
	// warm up
	solo_run(model, inputs);

	nvtxRangePushA("Single");
	solo_run(model, inputs);
	nvtxRangePop();

	std::cout << "Start parallel inference !!!" << std::endl;
	std::vector<std::thread> threads;
	threads.reserve(thread_num);

	for (int j = 0; j < thread_num; ++j) {
		threads.emplace_back(parallel, models[j]);
	}

	for (int k = 0; k < thread_num; ++k) {
		threads[k].join();
	}


	torch::cuda::synchronize();
	std::cout << "Finished successfully !!!" << std::endl;

	sem_destroy(&barrier);
	
}
```
and when I complied the program then execute it as **_./my_program ./resnet152.pt_** , I met the following error:
![image](https://user-images.githubusercontent.com/73052387/232309142-b955b376-70e4-4519-a521-035f580d5233.png)
I was confused and could you help me?

notes: **_resnet152.pt_** was converted from torchvision :

```
import torch
from torchvision import models

model = models.resnet152(pretrained=True)
for param in model.parameters():
	param.requires_grad = False

example_input = torch.rand(4, 3, 224, 224)
script_module = torch.jit.trace(model, example_input)
script_module.save('resnet152.pt')
```

### Versions

libtorch : 2.0.0+cu118
torchvision: 0.13.1a0
gcc: 9.4.0

**Comment by wxthu** [comment]
@svenstaro

**Comment by jbschlosser** [comment]
Hey @wxthu, I suggest asking for help in the [PyTorch forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. The issues here are reserved for problems within PyTorch itself. Closing for now but feel free to reopen if you identify a possible bug within PyTorch.

**Comment by vinodlahire** [comment]
> ###  Describe the bug
> I made DL inferences under multiple threads in libtorch as following:
> 
> ```
> #include <torch/torch.h>
> #include <torch/script.h>
> 
> #include <nvToolsExt.h>
> #include <unistd.h>
> #include <iostream>
> #include <string>
> #include <vector>
> #include <thread>
> #include <semaphore.h>
> #include <pthread.h>
> #include <atomic>
> 
> torch::Device device(torch::kCUDA);
> int thread_num = 2;
> sem_t barrier;
> std::atomic<int> count(thread_num);
> 
> void solo_run(torch::jit::script::Module& model, std::vector<torch::jit::IValue>& imgs)
> {
> 	model.to(device);
> 	for (int i = 0; i < 100; ++i)
> 		model.forward(imgs);
> 
> 	torch::cuda::synchronize();
> }
> 
> void parallel(torch::jit::script::Module model)
> {
> 	model.to(device);
> 	torch::Tensor img = torch::rand({4, 3, 224, 224}).to(device);
> 	std::vector<torch::jit::IValue> imgs;
> 	imgs.push_back(img);
> 
> 	count--;
> 	if (count == 0) {
> 		for (int i = 0; i < thread_num; ++i) {
> 			sem_post(&barrier);
> 		}
> 	}
> 	sem_wait(&barrier);
> 
> 	nvtxRangePushA("PARALLEL");
> 	for (int i = 0; i < 100; ++i)
> 		model.forward(imgs);
> 	
> 	nvtxRangePop();
> }
> 
> int main(int arc, char** argv) {
> 	sem_init(&barrier, 0, 0);
> 
> 	c10::InferenceMode guard(true);
> 	torch::Tensor img = torch::rand({4, 3, 224, 224}).to(device);
> 	std::vector<torch::jit::IValue> inputs;
> 	inputs.push_back(img);
> 	std::string model_path = argv[1];
> 
> 	torch::jit::script::Module model = torch::jit::load(model_path);
> 	// auto model = torch::jit::load(model_path);
> 
> 	std::vector<torch::jit::script::Module> models;
> 	for (int i = 0; i < thread_num; ++i) {
> 		models.push_back(torch::jit::load(model_path));
> 	}
> 	if(torch::cuda::is_available()) {
> 		std::cout << "CUDA now is available ! Inference on GPU." << std::endl;
> 	}
> 	
> 	// warm up
> 	solo_run(model, inputs);
> 
> 	nvtxRangePushA("Single");
> 	solo_run(model, inputs);
> 	nvtxRangePop();
> 
> 	std::cout << "Start parallel inference !!!" << std::endl;
> 	std::vector<std::thread> threads;
> 	threads.reserve(thread_num);
> 
> 	for (int j = 0; j < thread_num; ++j) {
> 		threads.emplace_back(parallel, models[j]);
> 	}
> 
> 	for (int k = 0; k < thread_num; ++k) {
> 		threads[k].join();
> 	}
> 
> 
> 	torch::cuda::synchronize();
> 	std::cout << "Finished successfully !!!" << std::endl;
> 
> 	sem_destroy(&barrier);
> 	
> }
> ```
> 
> and when I complied the program then execute it as **_./my_program ./resnet152.pt_** , I met the following error: ![image](https://user-images.githubusercontent.com/73052387/232309142-b955b376-70e4-4519-a521-035f580d5233.png) I was confused and could you help me?
> 
> notes: **_resnet152.pt_** was converted from torchvision :
> 
> ```
> import torch
> from torchvision import models
> 
> model = models.resnet152(pretrained=True)
> for param in model.parameters():
> 	param.requires_grad = False
> 
> example_input = torch.rand(4, 3, 224, 224)
> script_module = torch.jit.trace(model, example_input)
> script_module.save('resnet152.pt')
> ```
> 
> ### Versions
> libtorch : 2.0.0+cu118 torchvision: 0.13.1a0 gcc: 9.4.0

@wxthu Have you found solution to this ??
