### ISSUE TITLE
Wrong version number for the 0.4.1 release

### ISSUE THREAD

**Issue by EKami** [pytorch/pytorch#9926]
## Issue description

The `__version__` provided by Pytorch is wrong

See [this line](https://github.com/pytorch/pytorch/blob/v0.4.1/setup.py#L246)

**Comment by vishwakftw** [comment]
The `__version__` is set correctly. See https://github.com/pytorch/pytorch/issues/7954#issuecomment-394443358 .

**Comment by EKami** [comment]
In that case the `__version__` isn't set correctly somewhere else because I compiled Pytorch from source on the `0.4.1` branch and here is what I get:
```
$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.5.0a0+a24163a'
```

**Comment by vishwakftw** [comment]
Please check the source code link in that comment. `export PYTORCH_BUILD_VERSION=0.4.1` changes the build version for the release. Installation from source is `0.5.0a0`. @soumith

**Comment by soumith** [comment]
indeed, if you compile from source, and you want the "binary" version numbers, please export:

```
export PYTORCH_BUILD_VERSION=0.4.1
export PYTORCH_BUILD_NUMBER=1
```

**Comment by soumith** [comment]
See https://github.com/pytorch/builder/blob/master/manywheel/build.sh#L3-L4 for reference.

**Comment by scott-vsi** [comment]
Here's a permalink: https://github.com/pytorch/builder/blob/7b30eb5388fdb6905b88b297b6727a264940dfb7/manywheel/build.sh#L3-L4

**Comment by GitHubGS** [comment]
> indeed, if you compile from source, and you want the "binary" version numbers, please export:
> 
> ```
> export PYTORCH_BUILD_VERSION=0.4.1
> export PYTORCH_BUILD_NUMBER=1
> ```

I tried, but not works, still version number:0.5.0a0+a24163a
I did the following:
export PYTORCH_BUILD_VERSION=0.4.1
export PYTORCH_BUILD_NUMBER=1
sudo python3 setup.py install

then open python3
import pytorch
print(torch.__version__)
 0.5.0a0+a24163a

**Comment by GitHubGS** [comment]
@soumith thank you sir,
PYTORCH_BUILD_VERSION=0.4.1 PYTORCH_BUILD_NUMBER=1 sudo -E python3 setup.py install
it works!
