### ISSUE TITLE
[docs] Missing docs for torch.as_strided

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9928]
https://pytorch.org/docs/master/search.html?q=as_strided&check_keywords=yes&area=default is empty.

I was looking to PyTorch'ify matting laplacian NumPy code and it uses `as_strided`: https://github.com/NVIDIA/FastPhotoStyle/blob/master/photo_smooth.py#L96

**Comment by SsnL** [comment]
Thanks for bring this up. Added to https://github.com/pytorch/pytorch/issues/9886 !

**Comment by vadimkantorov** [comment]
@SsnL Thanks! Can you please also add there our old friend `softplus`? https://github.com/pytorch/pytorch/issues/4819

**Comment by faroit** [comment]
@vadimkantorov @SsnL since `as_strided` has similar functionality to `Tensor.unfold` is there a significant difference between them or is `unfold` generally to be preferable e.g. for chunking/windowing data?

**Comment by vadimkantorov** [comment]
@faroit No idea :)

**Comment by SsnL** [comment]
@faroit use unfold. as_strided is error-prune and has a more complex backward.

**Comment by faroit** [comment]
@SsnL thanks for the info. `as_strided` is used for `STFT`. Maybe it makes sense to switch to `unfold` there, then?

One more thing: since `Tensor.unfold` and `nn.functional.unfold` are quite different (the latter is more targeted towards images) and probably implemented differently. Shouldn't we also have a simple folding operation equivalent to `Tensor.unfold`?

**Comment by SsnL** [comment]
@faroit Yeah, feel free to submit a PR to update it with `unfold`. Thanks for pointing it out.

`Fold` is more properly defined with images, i.e., being col2im. In the general case for `unfold`, it is unclear if one should do `sum` or `mean` in the corresponding `fold`. And `fold` can't be a view op, unlike `unfold`. So I think it's better left this way.

**Comment by f0k** [comment]
> as_strided is error-prune and has a more complex backward.

If the backward of as_strided is slower, shouldn't it use the backward of unfold when it can? And shouldn't unfold just call as_strided?

> In the general case for `unfold`, it is unclear if one should do `sum` or `mean` in the corresponding `fold`.

Could be specified via a `reduction` keyword argument that defaults to`'sum'`. Could also be fixed to just always sum just like `nn.Fold`; a keyword argument could still be added later.

> And `fold` can't be a view op, unlike `unfold`.

True. `fold` would give access to the backward pass of `unfold`.

I think it's mostly a question of how big the demand is. For audio synthesis, it would be nice to have the overlap-add backward pass of `unfold` available somewhere.

Sorry, this should all be discussed in a separate issue!

**Comment by SsnL** [comment]
> shouldn't it use the backward of unfold when it can?
It can, but it doesn't yet. If you look at `as_strided_backward `https://github.com/pytorch/pytorch/blob/ffc7158bf2f97916305217e4203ef846c00161ce/tools/autograd/templates/Functions.cpp#L937-L1488 , it is already really really complicated. In theory we can always add more if-statements to make it call more efficient backwards. But it will make the code much more complex. In fact, `as_strided_backward` isn't much slower for contiguous inputs, and may even be faster for overlapping inputs. Further, things that use `unfold`-like views, should mostly come from `unfold`, so we didn't bother.

> And shouldn't unfold just call as_strided?
Under the hood, yes. But it has a custom backward. It is the same reason that we don't let autograd figure out conv's backward by differentiating each addition and multiplication.  

>  it would be nice to have the overlap-add backward pass of unfold available somewhere.
Yes I agre. However, the backward of `unfold` isn't some magical thing. It's just an `index_add_`, which one can write themselves. I think the correct place for the operation you described to live in is to make `nn.Fold` and `nn.Unfold` support 1d inputs. https://github.com/pytorch/pytorch/blob/ffc7158bf2f97916305217e4203ef846c00161ce/tools/autograd/templates/Functions.cpp#L640-L652
