### ISSUE TITLE
[pytorch] torch.einsum: minor API discrepancy with NumPy and TensorFlow

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9929]
In NumPy it accepts `*operands`, in PyTorch it accepts `operands`.

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.einsum.html:
```python
numpy.einsum(subscripts, *operands, ...)
```

https://pytorch.org/docs/master/torch.html?highlight=einsum#torch.einsum:
```python
torch.einsum(equation, operands)
```

https://www.tensorflow.org/api_docs/python/tf/einsum:
```python
tf.einsum(equation, *inputs, **kwargs)
```

Are there good reasons for keeping it different from NumPy / TensorFlow?

**Comment by t-vi** [comment]
PyTorch's python argument parsing doesn't handle varargs except in very special cases (ints and only varargs, no direct args).
I would have implemented it, but without having more than one function to use it, it didn't fly with @apaszke for the added complexity (which would involve allocating and deallocating the vararg vector where now the argument vector just doubles for the vararg vector).

**Comment by vadimkantorov** [comment]
Maybe this would be moree justifiable if `torch.meshgrid` (https://github.com/pytorch/pytorch/issues/9503#issuecomment-407425625) and unimplemented `torch.broadcast` (https://github.com/pytorch/pytorch/issues/8076) use the varargs way as well.

**Comment by t-vi** [comment]
If you do the lobbying, I can do the coding. :wink:

**Comment by vadimkantorov** [comment]
@apaszke @colesbury What do you think? Does NumPy/TF API compat for `torch.einsum`, `torch.meshgrid`, `torch.broadcast` (not implemented yet) justify re-evaluation of varargs functionality for the argument parser?

**Comment by zou3519** [comment]
Couldn't we write a wrapper function in python to match the API (and handle variable args?)

**Comment by t-vi** [comment]
Thank you!  I'm doing that for tensordot at the moment and will also do it for eimsum.

**Comment by vadimkantorov** [comment]
Should I file another issue for tracking `torch.meshgrid` varargs'izing?
