### ISSUE TITLE
[pytorch] torch.einsum processes ellipsis differently from NumPy

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9930]
```python
import torch
import numpy as np

a = torch.rand(32, 48, 9, 3)
print(np.einsum('...ji,...jk ->...ik', a, a).shape)
# (32, 48, 3, 3)

print(torch.einsum('...ji,...jk ->...ik', [a, a]).shape)
# RuntimeError: ellipsis must represent 2 dimensions in all terms
```

Found during porting matting laplacian to PyTorch: https://github.com/NVIDIA/FastPhotoStyle/blob/master/photo_smooth.py#L76

**Comment by t-vi** [comment]
Thank you for the report. I'll look into it.

**Comment by t-vi** [comment]
It's not the ..., it's the space. We don't allow spaces (yet?) but here we assumed there aren't any and that number of explicit indices = length of term - 3 when there is an ellipsis.
