### ISSUE TITLE
torch.as_strided error message wrong

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#99307]
### 🐛 Describe the bug

```
import torch
arg_1 = (2, 2)
arg_2 = [25,40]
arg_3 = 1
results = torch.as_strided(size=arg_1,stride=arg_2,storage_offset=arg_3,)
```
I provide arguments `size` and `stride`, but above code throw an exception `TypeError: as_strided() missing 3 required positional argument: "input", "size", "stride"`. I know I need to provide arguments `input`, but I think the error message should be shown as `TypeError: as_strided() missing 1 required positional argument: "input"`.

### Versions

pytorch version: 2.0.0+cu118

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @malfet

**Comment by RB100-git** [comment]
The size, stride, and storage_offset arguments can only be passed if there is an input argument provided. The input argument specifies the tensor that will be used as a basis for creating the new strided tensor. The confusion will be cleared up if you try creating an empty tensor first and write the line 'results' to see if this is the matter.

**Comment by ezyang** [comment]
You probably want `empty_strided`.
