### ISSUE TITLE
NCCL Runtime Error

### ISSUE THREAD

**Issue by ggordonhall** [pytorch/pytorch#9932]
## Issue description

I'm trying to run an OpenNMT-py model across 4 Nvidia P100 GPUs but I receive this error:

```
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /home/ggordo04/pytorch/torch/lib/THD/process_group/General.cpp:17
```
This surprised me because I have NCCL2 on my system (Ubuntu 16.04, CUDA 9.2, CuDNN 7.1) and PyTorch picks it up. When I run `torch.cuda.nccl.version()` I get `2213`. Also, I pass the NCCL tests at https://github.com/NVIDIA/nccl-tests. 

Has anyone run into this problem?

My build log is here:
https://gist.github.com/ggordonhall/175817c36549ef17f9a3465c383ca492

## System Info

- PyTorch 0.5 - Source installation
- Ubuntu 16.04
- Python version: 3.6
- CUDA/cuDNN version: 9.2, 7.1
- GPU models and configuration: 4 x Nvidia P100
- GCC 5.4
- CMake 3.1
- NCCL 2.213

**Comment by soumith** [comment]
If you see https://gist.github.com/ggordonhall/175817c36549ef17f9a3465c383ca492#file-gistfile1-txt-L4165-L4171 it says it found PyTorch's own source-compiled NCCL1. This happens because NCCL2 wasn't auto-detected / found.

Can you export:

```
export NCCL_ROOT_DIR=[path to your NCCL2]
```

And then recompile PyTorch.

For example, my $NCCL_ROOT_DIR has the contents:

```
$ ls  $NCCL_ROOT_DIR
COPYRIGHT.txt  include  lib  NCCL-SLA.txt
```

**Comment by ggordonhall** [comment]
Thanks! I'll give that a go.

**Comment by heitorschueroff** [comment]
Closing this issue as it seems to have been resolved. @ggordonhall let us know if you still have this issue.
