### ISSUE TITLE
[pytorch] [feature request] Batched matrix inverse

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9933]
```python
import torch, numpy as np
a = torch.rand(2,3,4,4)

print(np.linalg.inv(a).shape)
# (2, 3, 4, 4)

print(torch.inverse(a).shape)
# RuntimeError: invalid argument 1: A should be 2 dimensional at .../aten/src/TH/generic/THTensorLapack.cpp:492
```

If implemented, this would also replace https://github.com/pytorch/pytorch/blob/master/torch/distributions/multivariate_normal.py#L50

Please feel free to close this issue if tracking in https://github.com/pytorch/pytorch/issues/7500 is preferred.

**Comment by soumith** [comment]
closed in favor of #7500
