### ISSUE TITLE
[pytorch] Inconsistent automatic conversion of GPU tensors to NumPy arrays on CPU

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9934]
It seems that implicit conversion will copy onto CPU, while explicit won't, found this somewhat confusing.

```python
import torch, numpy as np

a = torch.eye(2, 2).cuda()
print(np.linalg.inv(a))
# [[1. 0.]
# [0. 1.]]

print(np.linalg.inv(a.numpy()))
# TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

print(torch.__version__)
# '0.5.0a0+bcd20f9'
```

**Comment by vadimkantorov** [comment]
probably related: https://github.com/pytorch/pytorch/pull/9651 (discusses the relevant piece of logic)

**Comment by fmassa** [comment]
The problem is actually in [`__array__` in here](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L391-L393). It actually converts the data to `.cpu()` before doing `.numpy()`.

**Comment by ailzhang** [comment]
What's the expected behavior should be here?

**Comment by vadimkantorov** [comment]
I think `__array__` should not include an automatic `cpu` call, and just be equivalent to `tensor.numpy()`

**Comment by boeddeker** [comment]
Is there a **recomented** way to convert an input (`Tensor` or `ndarray`) to something that works with numpy?
Before that fix `np.asarray(array)` returned always a numpy `nparray`. Now it is confusing that it works on my notebook (without gpu), but not on my workstation (with gpu). I personally liked the old behaviour more.

Maybe something like the opposite of `torch.from_numpy`?
```python
def to_numpy(array):
    if isinstance(array, torch.Tensor):
        array = array.cpu()

    # torch only supports np.asarray for cpu tensors
    return np.asarray(array)
```

Related: https://discuss.pytorch.org/t/how-to-transform-variable-into-numpy/104/7
