### ISSUE TITLE
no meta kernel for a decomp but the decomp got traced out with no 'val'

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#99356]
### 🐛 Describe the bug

Recently I tried tracing a inplace op with a hand written [decomp](https://github.com/pytorch/pytorch/blob/cdab6c8df9ff9331126f69ea59c23f06109f03d7/torch/distributed/_spmd/api.py#L317) that decomps `aten.fused_adam_.default` to `aten.fused_adam.default`, it only have inplace meta registration https://github.com/pytorch/pytorch/blob/08ffe34621ded20cdb0825a890b334354a06e03c/torch/_meta_registrations.py#L1402

This decomp then passed to `make_fx`, I can successfully trace the graph out, but the `aten.fused_adam.default` node does not have `val` field in node's meta.

Maybe there's a bug somewhere when populating the `val` with decomposed graph 

### Versions

master

cc @ezyang @eellison @bdhirsh @soumith @msaroufim @wconstab @ngimel @mrshenli

**Comment by wconstab** [comment]
hmm, wondering if you're abusing decomp here when you really want functionalization? cc @bdhirsh

**Comment by wanchaol** [comment]
> hmm, wondering if you're abusing decomp here when you really want functionalization?

Yeah it should be functionalization rather than decomp I agree, currently we are using decomp to work around it in particular for fused adam.

I think the bug itself might still hold, even if it's a non-inplace op, if it registered a decomp on the op and the decomposed ops does not have meta kernels, it looks like it could still trace out but with no `val` in the meta field

**Comment by ezyang** [comment]
Can you post a repro? My guess is that you need to write a meta for the `fused_adam`. There's also probably something else going on where fake tensor is using a fallback or something and then val is not being set, would be easiest to diagnose with the repro.

**Comment by wanchaol** [comment]
> Can you post a repro? My guess is that you need to write a meta for the `fused_adam`. There's also probably something else going on where fake tensor is using a fallback or something and then val is not being set, would be easiest to diagnose with the repro.

Yeah added a `meta` for it and most things works (i.e. the following `getitem` nodes can get the correct output vals from it! But it seems like the `fused_adam` node itself does not have `val`. Agree that it's probaby a fake tensor fallback issue and the returned `val` should be a `Tuple[List[Tensor], List[Tensor], ..]` which might not be handled yet.

I just drafted a minimal repro on this, hope it helps diagnosing :) 
https://gist.github.com/wanchaol/93056bca54b4ef46c8a59ed8821a4652

**Comment by ezyang** [comment]
OK, I see the problem; it's because adam returns a tuple of lists and we don't handle this.
