### ISSUE TITLE
torch.compile error

### ISSUE THREAD

**Issue by LitPrice** [pytorch/pytorch#99390]
### 🐛 Describe the bug

When I used torch.compile to compile and accelerate this code https://github.com/CompVis/stable-diffusion/blob/21f890f9da3cfbeaba8e2ac3c425ee9e998d5229/scripts/txt2img.py#L303, this error occurred.

In file included from /tmp/torchinductor_hujiahao1/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:8:0,
                 from /tmp/torchinductor_hujiahao1/ke/ckeyipvhzljoe53twvjbo23ihq2q26ser2onsutamnzl7ytce5dn.cpp:2:
/home/hujiahao1/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/include/ATen/core/PhiloxRNGEngine.h:199:35: error: enclosing class of constexpr non-static member function ‘float at::philox_engine::uint32_to_uniform_float(uint32_t)’ is not a literal type
   C10_HOST_DEVICE constexpr float uint32_to_uniform_float(uint32_t value) {
                                   ^
In file included from /tmp/torchinductor_hujiahao1/zt/cztcl2vp5yqlnhofzpqfficjcxgyict6e3xhfdd7sdbkipp4p44x.h:8:0,
                 from /tmp/torchinductor_hujiahao1/ke/ckeyipvhzljoe53twvjbo23ihq2q26ser2onsutamnzl7ytce5dn.cpp:2:
/home/hujiahao1/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/include/ATen/core/PhiloxRNGEngine.h:68:7: note: ‘at::philox_engine’ is not literal because:
 class philox_engine {
       ^
/home/hujiahao1/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/include/ATen/core/PhiloxRNGEngine.h:68:7: note:   ‘at::philox_engine’ is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
/tmp/torchinductor_hujiahao1/ke/ckeyipvhzljoe53twvjbo23ihq2q26ser2onsutamnzl7ytce5dn.cpp: In function ‘void kernel(float*)’:
/tmp/torchinductor_hujiahao1/ke/ckeyipvhzljoe53twvjbo23ihq2q26ser2onsutamnzl7ytce5dn.cpp:13:26: error: ‘simdlen’ is not valid for ‘#pragma omp simd’
         #pragma omp simd simdlen(4) 
                          ^

Set torch._dynamo.config.verbose=True for more information

You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True

### Versions

not found collect_env.py
my env:
torch 2.0.0
cuda 11.8
gcc 5.3
cmake 3.26.3

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @soumith @ngimel

**Comment by jgong5** [comment]
@Joker-co Can you share the steps and scripts to repro the problem?

**Comment by leslie-fang-intel** [comment]
Close as can't reproduce, feel free to re-open.
