### ISSUE TITLE
Support `cond` branches that reference variables defined in an outer scope

### ISSUE THREAD

**Issue by avikchaudhuri** [pytorch/pytorch#99401]
### 🚀 The feature, motivation and pitch

Related: https://github.com/pytorch/pytorch/issues/90469

Attempting to inline a nested function that closes over variables in outer scopes results in an error. For example, the following module cannot be exported:

```
class ModuleClosureReproError(torch.nn.Module):
            # error
            def __init__(self):
                super().__init__()
                self.linear = torch.nn.Linear(3, 3)

            def forward(self, pred, x):
                y = x + x

                def true_fn(val):
                    return self.linear(val) * (x + y)

                def false_fn(val):
                    return val * (y - x)

                return cond(pred, true_fn, false_fn, [x])
```

### Alternatives

The workaround today is to rewrite such functions to take closed-over variables as additional arguments.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @Xia-Weiwen @soumith @ngimel @desertfire

**Comment by Chillee** [comment]
cc: @zou3519 @voznesenskym

**Comment by anijain2305** [comment]
@ydwu4 @avikchaudhuri Do we need this now?

**Comment by ydwu4** [comment]
yeah
