### ISSUE TITLE
Error passing non-tensor argument to the function returned by torch.func.jacrev

### ISSUE THREAD

**Issue by roastduck** [pytorch/pytorch#99405]
### 🐛 Describe the bug

It is described in `torch.func.jacrev` that the function to be differentiated is *"A Python function that takes one or more arguments, one of which must be a Tensor, and returns one or more Tensors"*. In other words, it does not require *all* arguments to be tensors. However, there will be an error when at least one argument is *not* a tensor. To reproduce, run the following code:

```python
import torch

def f(x, n):
    return x + n

x = torch.randn(5, 5)
torch.func.jacrev(f, argnums=0)(x, 1)
```

The error is:

```
Traceback (most recent call last):
  File "/home/rd/tmp/test.py", line 7, in <module>
    torch.func.jacrev(f, argnums=0)(x, 1)
  File "/home/rd/.local/lib/python3.9/site-packages/torch/_functorch/eager_transforms.py", line 488, in wrapper_fn
    error_if_complex("jacrev", args, is_input=True)
  File "/home/rd/.local/lib/python3.9/site-packages/torch/_functorch/eager_transforms.py", line 347, in error_if_complex
    if arg.dtype.is_complex:
AttributeError: 'int' object has no attribute 'dtype'
```

The root cause is `error_if_complex` checks for *all arguments* of the function, and assumes they are tensors. But if I understand correctly, checking *only the arguments that needs Jacobian (arguments specified in `argnums`)* should be enough.

### Versions

I can't get `collect_env.py` according to the issue-posting guide because of HTTP 404. Please fix it.

I was running PyTorch 2.0.0+cu118. Contact me if you need more environment details. (but I think this issue is platform-agnostic).

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by kshitij12345** [comment]
This was fixed in https://github.com/pytorch/pytorch/pull/97746. The fix is currently available in nightly and will be part of the next release. Thanks!

**Comment by roastduck** [comment]
Thanks. Closing since it is duplicated.
