### ISSUE TITLE
python_default_init behavior incorrect when auto generating aten functions 

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#9941]
Any non-empty input defined in the python_default_init in the ATen's native_functions.yaml will generate a default 'None' here, see [generation logic](https://github.com/pytorch/pytorch/blob/master/tools/autograd/gen_python_functions.py#L729) when generating python functions/methods in pytorch.

```python
        if arg.get('python_default_init') is not None:
            default = 'None'
``` 

It should not be a correct behavior for other default args when generating the functions as it does not give the correct default values to the function.

**Comment by SsnL** [comment]
If `python_default_init` is set, we assert that no default value is given here: https://github.com/pytorch/pytorch/blob/5e4de0821a251a88097809e16a370141c438c58d/aten/src/ATen/native_parse.py#L77

**Comment by wanchaol** [comment]
@SsnL The default I mentioned above is when we generating the function signature for native function, for the argument who have `python_default_init`, the argument default in that function signature will always be "None", which I think should not be the case as we see here:

https://github.com/pytorch/pytorch/blob/ce0b895a0c6c691be7b7424361ec65370271145e/aten/src/ATen/native/native_functions.yaml#L1556

In norm, p has a default value of 2 in python_default_init, so when generating the function signature, the argument should have a default value of 2 rather than None (which is the current case).

**Comment by SsnL** [comment]
@wanchaol if you think about the python behavior, it is: if `norm` is given **kwarg** `dim=` then `p` will have default value `2`. This is different from having a default value of `2`.

**Comment by wanchaol** [comment]
I see, is the python_default_init the way to resolve overloading functions with arguments matching without confusion?

**Comment by SsnL** [comment]
Yeah.. currently that is our way to provide default values that is impossible as c++ function signature.
