### ISSUE TITLE
DISABLED test_fsdp_ddp_parity_with_grad_scaler_offload_false_none_mixed_precision_use_orig_params (__main__.TestShardedGradScalerParityWithDDP)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#99427]
Platforms: linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/distributed%2Ffsdp%2Ftest_fsdp_sharded_grad_scaler.py%3A%3ATestShardedGradScalerParityWithDDP%3A%3Atest_fsdp_ddp_parity_with_grad_scaler_offload_false_none_mixed_precision_use_orig_params)).

This is failing multigpu test in trunk after https://github.com/pytorch/pytorch/pull/99175.  In the forward fix, please add `Fixes https://github.com/pytorch/pytorch/issues/99427` in your commit message and attach `ciflow/periodic` label to the PR to run the test

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by speediedan** [comment]
As discussed in [#99485](https://github.com/pytorch/pytorch/pull/99485), all relevant `periodic` tests are [now passing](https://github.com/pytorch/pytorch/actions/runs/4738073998/jobs/8411862508). Thanks for catching this and alerting us! Certainly let me know if there's anything else you need from me. @awgu @huydhn

**Comment by huydhn** [comment]
I can close this now just to make sure that the test is run (you can also double check GitHub log to see that it's not skipped)
