### ISSUE TITLE
0.4.0 binaries aren't listed in previous versions

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [pytorch/pytorch#9943]
Now that 0.4.1 is released, the page on previous versions needs to be updated to include the 0.4.0 binaries.

**Comment by fcalvet** [comment]
Not directly on this issue but related: the conda binaries for windows aren't updated on the official pytorch channel which is a bit confusing since it's the case on soumith channel.
Is this expected ?

**Comment by soumith** [comment]
@fcalvet I'm not sure how our uploader broke this badly on Windows. It indeed uploaded to the `soumith` channel rather than `pytorch`. We've uploaded the packages to `pytorch` now and are fixing the script. Thanks a ton for reporting.

**Comment by soumith** [comment]
@hmc-cs-mdrissi thanks for reporting. fixed via https://github.com/pytorch/pytorch.github.io/commit/3a7186420c0e11a1bbf85dc9073957a8de1cd43f
