### ISSUE TITLE
[dynamo] ONNX and TVM backend don't work with GraphModule with no outputs

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#99437]
### 🐛 Describe the bug

The issue essentially boiled down to the fact that onnxrt and tvm don't support a graph with no outputs. And right now dynamo will fail to compile a model if one subgraph contains no outputs for those two backends without `TORCHDYNAMO_SUPPRESS_ERRORS` set to True. Would that make sense if an explicit fallback can be added for those backends? Something like:
```
if not example_outputs:
    # warning this gm falls back to eager blahblah
    return gm.forward
```

Would that break backward compatibility?

my repro
```python
@dynamo.optimize("onnxrt"/"tvm", dynamic=True)
def func(a, b):
    x = a / (torch.abs(a) + 1)
    dynamo.graph_break()
    if b.sum() < 0:
        b = b * -1

func(torch.randn(10), torch.randn(10))
```

### Versions

torch                     2.1.0a0+git80eab63 /home/yj/pytorch

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by anijain2305** [comment]
AFAIC, returning `gm.forward` from `tvm`/`onnxrt` dynamo compiler would not break any backward compatibility.

So, for now, feel free to short-cut before you are about to call the actual `tvm.compile` call. We do something similar for inductor here - https://github.com/pytorch/pytorch/blob/main/torch/_inductor/compile_fx.py#L169-L170
