### ISSUE TITLE
aten._cdist_backward not implemented

### ISSUE THREAD

**Issue by tsengalb99** [pytorch/pytorch#99445]
### 🐛 Describe the bug

I'm getting this error when running torch.compile'd code involving backproping through cdist.

```
torch._dynamo.exc.BackendCompilerFailed: backend='debug_wrapper' raised:
UnsupportedOperatorException: aten._cdist_backward.default
```

Forked off https://github.com/pytorch/pytorch/issues/98853

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh 

### Versions

Same as https://github.com/pytorch/pytorch/issues/98853

**Comment by bdhirsh** [comment]
Do you have a repro?

Locally I'm able to run this code without error:
```
import torch

def f(a, b):
    return torch.cdist(a, b)

f2 = torch.compile(f)

a = torch.randn(10, 3, requires_grad=True)
b = torch.randn(11, 3, requires_grad=True)
out = f2(a, b)
out.sum().backward()
```

**Comment by ezyang** [comment]
Add dynamic=True

```
import torch

def f(a, b):
    return torch.cdist(a, b)

f2 = torch.compile(f, dynamic=True)

a = torch.randn(10, 3, requires_grad=True)
b = torch.randn(11, 3, requires_grad=True)
out = f2(a, b)
out.sum().backward()
```

**Comment by yanboliang** [comment]
Seems Inductor use fallback for ```aten._cdist_backward```, not sure why dynamic shapes doesn't work.
https://github.com/pytorch/pytorch/blob/495e1b4d0e0092de22160c83a0a51d948df6d69f/torch/_inductor/lowering.py#L1429

**Comment by tsengalb99** [comment]
Hi, any updates on this?
