### ISSUE TITLE
Long queue for windows.4xlarge

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#99476]
## Current Status
Mitigated

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by jeanschmidt** [comment]
![Screenshot 2023-04-19 at 12 31 44](https://user-images.githubusercontent.com/4520845/233048376-148300d8-ddde-4f17-a519-cdabf85a304b.png)

After requesting the instantiation of extra runner instances, new ones became available ~05:00 am CET.

![Screenshot 2023-04-19 at 12 34 39](https://user-images.githubusercontent.com/4520845/233049098-950bdcf1-0a9f-4132-b5ad-2e754c5268f8.png)

**Comment by malfet** [comment]
@jeanschmidt this is likely because we've stopped Windows CI on core and thus drained the queue, but it would be good to understand, what have caused it in the first place.
