### ISSUE TITLE
[Inductor] make_fallback(aten.cumprod)

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/pytorch#99474]
### 🐛 Describe the bug

While I was running inductor with LLaMA, I hit the following warning:
```
[2023-04-18 22:54:24,618] torch._inductor.utils: [WARNING] make_fallback(aten.cumprod): a decomposition exists, we should switch to it
```
And not sure what it means.

Will need sometime to prepare a reduced case. @wconstab suggests that this warning and potential workaround may be obvious to the inductor team.

### Versions

Nightly

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by ngimel** [comment]
This is a benign warning and we removed it already.
