### ISSUE TITLE
backward of -torch.prod(x) missing negative sign

### ISSUE THREAD

**Issue by angelleng** [pytorch/pytorch#995]
example: 
```
s = Variable(torch.FloatTensor([2,3]), requires_grad=True)
prod = -s.prod()
prod.backward()
print(s.grad)
```
gives 3,2 instead of -3,-2.

**Comment by fmassa** [comment]
I think the bug is in [here](https://github.com/pytorch/pytorch/blob/master/torch/autograd/_functions/reduce.py#L49), as it does not multiply by `grad_output`

**Comment by fmassa** [comment]
I wonder how the tests were passing before, as this case is tested in [here](https://github.com/pytorch/pytorch/blob/master/test/test_autograd.py#L1005], and the [`grad_output` is different from 1 in the tests](https://github.com/pytorch/pytorch/blob/master/test/test_autograd.py#L1248)...

**Comment by Teaonly** [comment]
https://github.com/pytorch/pytorch/blob/master/test/test_autograd.py#L1248 just test Prod with inplace=True flag, not testing Prod self.
