### ISSUE TITLE
hipSOLVER support?

### ISSUE THREAD

**Issue by maharjun** [pytorch/pytorch#99508]
### 🚀 The feature, motivation and pitch

currently cuSOLVER and MAGMA are supported as backends. However, for my use case, which runs on AMD GPU's, cuSOLVER is not available, and the magma backend does not have support for QR decomposition (it only does for small matrices according to the comment in orgqr_kernel_impl in /aten/src/ATen/native/cuda/linalg/BatchLinearAlgebra.cpp). Is it not possible to have the hipiify_python script translate cuSOLVER code to hipSOLVER code? has anyone tried this?

hipSOLVER claims to have a very compatible interface for the functions it implements, so I hope this is not too hard. If anyone has any suggestions on how to go about it please let me know.

This is currently for pytorch 1.13, which I've compiled using ROCM 5.4.3, ubuntu 20.04, gcc 9, and hipMAGMA. Everything else works, SVD works perfectly (owing to the MAGMA backend).

### Alternatives

Anything that gives me QR decomposition in pytorch on an AMD GPU is welcome

### Additional context

Given the popularity of AMD GPU's in Supercomputer stackes and cloud providers alike, and the maturity of the ROCm and HIP stack, I think the time is apt to consider this.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by malfet** [comment]
I think I've seen some hipSOLVER PR's coming, but I'll let @jeffdaily to comment on those.

**Comment by jithunnair-amd** [comment]
https://github.com/pytorch/pytorch/pull/97370 is merged. We are still working on switching more operators to the hipsolver backend. Please let us know if there are specific operators you are interested in for the hipsolver backend.

cc @alugorey @xinyazhang

**Comment by alugorey** [comment]
@maharjun QR decomp should have been enabled in the aforementioned PR. Please let us know if it still is not working as expected after you pick up that change.
