### ISSUE TITLE
Tensor data dtype ComplexFloat not supported for NCCL process group

### ISSUE THREAD

**Issue by pfeatherstone** [pytorch/pytorch#99518]
### 🐛 Describe the bug

```
net = torch.nn.Conv1d(1,1,dtype=torch.complex64)
```
Now try to use that in distributed training.
You get the error:
```
RuntimeError: Input tensor data type is not supported for NCCL process group: ComplexFloat
```

### Versions

I'm using torch  2.0.0+cu117

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment]
dupe of https://github.com/pytorch/pytorch/issues/71613

**Comment by pfeatherstone** [comment]
is there a workaround for this?

**Comment by ezyang** [comment]
there's some workarounds on the thread, see if any of them help you
