### ISSUE TITLE
Inserting observer bug in FX quantization

### ISSUE THREAD

**Issue by fmo-mt** [pytorch/pytorch#99524]
### 🐛 Describe the bug

Following the tutorial or [FX quantization](https://pytorch.org/tutorials/prototype/fx_graph_mode_ptq_static.html),  when running `prepare_fx` of a float point model, basically pytorch would just insert an observer between two modules, for example a `Conv2d -> Conv2d` module would be: `Conv2d -> Observer -> Conv2d`, then these `Conv2d` modules will be converted to `QuantizeConv2d` modules after acting `convert_fx`

Buf for some customize structure of models, this function failed to insert, a simple way to reprod:
```
class M(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(3,16,3,1,1)
    self.bn1 = nn.BatchNorm2d(16)
    self.check = nn.BatchNorm2d(16) 

  def forward(self, x):
    x = self.check((self.bn1(self.conv1(x)))
    return x
```
and the graph after running `prepare_fx`:
```
GraphModule(
  (activation_post_process_0): HistogramObserver(min_val=inf, max_val=-inf)
  (conv1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (check): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (activation_post_process_1): HistogramObserver(min_val=inf, max_val=-inf)
)
```
after graph after convert:
```
GraphModule(
  (conv1): QuantizedConv2d(Reference)(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (check): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)
```
see, the `conv1` is still a `Reference` module and `check` is still a float-point version.

### Versions

PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe
GPU 4: NVIDIA A100 80GB PCIe
GPU 5: NVIDIA A100 80GB PCIe
GPU 6: NVIDIA A100 80GB PCIe
GPU 7: NVIDIA A100 80GB PCIe

Nvidia driver version: 515.48.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Gold 6346 CPU @ 3.10GHz
Stepping:                        6
Frequency boost:                 enabled
CPU MHz:                         3574.472
CPU max MHz:                     3600.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6200.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1 MiB
L2 cache:                        40 MiB
L3 cache:                        72 MiB
NUMA node0 CPU(s):               0-15,32-47
NUMA node1 CPU(s):               16-31,48-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] clip-anytorch==2.5.0
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.9.2
[pip3] torch==1.13.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.1
[pip3] torchsde==0.2.5
[pip3] torchvision==0.14.1
[conda] Could not collect

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by fmo-mt** [comment]
Discussed in https://discuss.pytorch.org/t/question-about-prepare-fx/177439/7

**Comment by HDCharles** [comment]
@fmo-mt This is a bit of a gray area because putting 2 batchnorms after one another is not something our code is intended to handle. Can you maybe elaborate on this usecase? Because I fail to see a situation where a single batchnorm wouldn't work. 

Having said that the code itself is doing something a bit weird, walking through the steps:
1) prepare_fx sees graph: conv1, bn1, check1, only potential fusion is conv1 bn1 which in practice
fuses bn1 into the weight of conv1, removing bn1 from the graph, new graph: conv1 check1
2) prepare_fx tries to match a quantization pattern to each node starting from end moving backwards, and matches the (bn, conv) pattern to (check1, conv1). *
3) given this 2-node pattern, prepare_fx inserts observers before conv1 and after check1 (obs, conv1, check1, obs)
4) calibration
5) convert_fx sees conv1, identifies it as a standalone module and converts it to reference quantized conv2d
6) convert_fx does not convert bn1 since it isn't listed in the various lists of backend_config
7) convert_fx does not lower  reference quantized conv2d (making it not a reference op) because it is not surrounded by qdq blocks (because due to the fusion pattern identified it only inserted the other qdq block after check)
8) convert_fx does not lower bn1 because its not surrounded by qdq blocks

*step 2 seems to be a bug given that it seems to be matching as a fused op, but then nothing happens to the other piece of the fused op throughout prepare and convert. Seems like either it shouldn't be matching with that fused pattern in prepare if we're always expecting to fuse away the batchnorm, or something else down the line.

@jerryzh168, @andrewor14  What are your thoughts on this?

```
class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 16, 3, 1, 1)
        self.bn1 = nn.BatchNorm2d(16)
        self.check = nn.BatchNorm2d(16)

    def forward(self, x):
        x = self.check(self.bn1(self.conv1(x)))
        return x


model = M().eval()
x = torch.randn(1, 3, 32, 32)
qconfig_mapping = torch.ao.quantization.get_default_qconfig_mapping()
prep_mod = prepare_fx(model, qconfig_mapping, (x))
prep_mod(x)
conv_mod = convert_fx(prep_mod)
print("converted", conv_mod)

------------

converted GraphModule(
  (conv1): QuantizedConv2d(Reference)(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (check): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)



def forward(self, x):
    conv1_input_scale_0 = self.conv1_input_scale_0
    conv1_input_zero_point_0 = self.conv1_input_zero_point_0
    quantize_per_tensor = torch.quantize_per_tensor(x, conv1_input_scale_0, conv1_input_zero_point_0, torch.quint8);  x = conv1_input_scale_0 = conv1_input_zero_point_0 = None
    dequantize = quantize_per_tensor.dequantize();  quantize_per_tensor = None
    conv1 = self.conv1(dequantize);  dequantize = None
    check = self.check(conv1);  conv1 = None
    check_scale_0 = self.check_scale_0
    check_zero_point_0 = self.check_zero_point_0
    quantize_per_tensor_1 = torch.quantize_per_tensor(check, check_scale_0, check_zero_point_0, torch.quint8);  check = check_scale_0 = check_zero_point_0 = None
    dequantize_1 = quantize_per_tensor_1.dequantize();  quantize_per_tensor_1 = None
    return dequantize_1
    
# To see more debug info, please use `graph_module.print_readable()`
```

**Comment by jerryzh168** [comment]
> @fmo-mt This is a bit of a gray area because putting 2 batchnorms after one another is not something our code is intended to handle. Can you maybe elaborate on this usecase? Because I fail to see a situation where a single batchnorm wouldn't work.
> 
> Having said that the code itself is doing something a bit weird, walking through the steps:
> 
> 1. prepare_fx sees graph: conv1, bn1, check1, only potential fusion is conv1 bn1 which in practice
>    fuses bn1 into the weight of conv1, removing bn1 from the graph, new graph: conv1 check1
> 2. prepare_fx tries to match a quantization pattern to each node starting from end moving backwards, and matches the (bn, conv) pattern to (check1, conv1). *
> 3. given this 2-node pattern, prepare_fx inserts observers before conv1 and after check1 (obs, conv1, check1, obs)
> 4. calibration
> 5. convert_fx sees conv1, identifies it as a standalone module and converts it to reference quantized conv2d
> 6. convert_fx does not convert bn1 since it isn't listed in the various lists of backend_config
> 7. convert_fx does not lower  reference quantized conv2d (making it not a reference op) because it is not surrounded by qdq blocks (because due to the fusion pattern identified it only inserted the other qdq block after check)
> 8. convert_fx does not lower bn1 because its not surrounded by qdq blocks
> 
> *step 2 seems to be a bug given that it seems to be matching as a fused op, but then nothing happens to the other piece of the fused op throughout prepare and convert. Seems like either it shouldn't be matching with that fused pattern in prepare if we're always expecting to fuse away the batchnorm, or something else down the line.
> 
> @jerryzh168, @andrewor14 What are your thoughts on this?
> 
> ```
> class M(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.conv1 = nn.Conv2d(3, 16, 3, 1, 1)
>         self.bn1 = nn.BatchNorm2d(16)
>         self.check = nn.BatchNorm2d(16)
> 
>     def forward(self, x):
>         x = self.check(self.bn1(self.conv1(x)))
>         return x
> 
> 
> model = M().eval()
> x = torch.randn(1, 3, 32, 32)
> qconfig_mapping = torch.ao.quantization.get_default_qconfig_mapping()
> prep_mod = prepare_fx(model, qconfig_mapping, (x))
> prep_mod(x)
> conv_mod = convert_fx(prep_mod)
> print("converted", conv_mod)
> 
> ------------
> 
> converted GraphModule(
>   (conv1): QuantizedConv2d(Reference)(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
>   (check): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
> )
> 
> 
> 
> def forward(self, x):
>     conv1_input_scale_0 = self.conv1_input_scale_0
>     conv1_input_zero_point_0 = self.conv1_input_zero_point_0
>     quantize_per_tensor = torch.quantize_per_tensor(x, conv1_input_scale_0, conv1_input_zero_point_0, torch.quint8);  x = conv1_input_scale_0 = conv1_input_zero_point_0 = None
>     dequantize = quantize_per_tensor.dequantize();  quantize_per_tensor = None
>     conv1 = self.conv1(dequantize);  dequantize = None
>     check = self.check(conv1);  conv1 = None
>     check_scale_0 = self.check_scale_0
>     check_zero_point_0 = self.check_zero_point_0
>     quantize_per_tensor_1 = torch.quantize_per_tensor(check, check_scale_0, check_zero_point_0, torch.quint8);  check = check_scale_0 = check_zero_point_0 = None
>     dequantize_1 = quantize_per_tensor_1.dequantize();  quantize_per_tensor_1 = None
>     return dequantize_1
>     
> # To see more debug info, please use `graph_module.print_readable()`
> ```

thanks @HDCharles for the detailed explanations, yeah I think step 2 is problematic, maybe we could tweak backend_config a bit to separate the configurations for fusion and configurations for quantization, but since we are moving to pt2 export flow this is probably not a priority for us.

**Comment by fmo-mt** [comment]
@jerryzh168 Since pt2 doesn't provide a quantization tool, I think we can use torch.compile to trace model graphs, as well as a compiled model, and then we can quantize model graphs by using torch.fx.quantization. Does it is supported?

**Comment by fmo-mt** [comment]
@jerryzh168 Since pt2 doesn't provide a quantization tool, I think we can use torch.compile to trace model graphs, as well as a compiled model, and then we can quantize model graphs by using torch.fx.quantization. Does it is supported?

**Comment by jerryzh168** [comment]
we are developing quantization tools in pt2, you can find example of quantizing resnet here: https://github.com/pytorch/pytorch/blob/main/test/quantization/pt2e/test_quantize_pt2e.py#L1730 (API subject to change)

**Comment by fmo-mt** [comment]
Thanks Jerry, I'll follow this, hope to see the official documents soon :)

**Comment by andrewor14** [comment]
Since this is kind of a niche use case and something I don't think we plan to support, I'm going to close this for now. @fmo-mt If this is still an issue in the PT2 export quantization flow please let us know. Here are the the docs: https://pytorch.org/tutorials/prototype/quantization_in_pytorch_2_0_export_tutorial.html
