### ISSUE TITLE
Incorrect documentation/implementation of the new gate in GRU

### ISSUE THREAD

**Issue by jangroter** [pytorch/pytorch#99531]
### 📚 The doc issue

In the official pytorch documentation of the Gated Recurrent Unit ([torch.nn.GRU](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html?highlight=gru#torch.nn.GRU)), the new gate $n_t$ is calculated using the following equation (eq1):

eq1: $n_t = \text{tanh}(W_{in}x_t + b_{in} + r_t * (W_{hn}H_{(T-1)} + b_{hn})) $

However, in the [original paper](https://arxiv.org/pdf/1406.1078.pdf) and in the book [Dive into deep learning](https://d2l.ai/chapter_recurrent-modern/gru.html) the Hadamard product ($*$) between $r_t$ and the previous hidden state $h_{(T-1)}$ is done before multiplication with the weight matrix and addition of the bias. This is to allow certain elements from the previous hidden state to be 'reset' and therefore removed from the candidate state or new gate $n_t$. In the current implementation, all hidden state values still contribute to the new gate because of the matrix multiplication.

### Suggest a potential alternative/fix

I, therefore, propose to update the documentation (and code if necessary) such that the new gate is calculated using the following equation (eq2), or that a reason is provided in the documentation for why pytorch' implementation differs from literature.

eq2: $n_t = \text{tanh}(W_{in}x_t + b_{in} + W_{hn}(r_t * H_{(T-1)})  + b_{hn}) $

To test this I implemented both versions and evaluated it on the MNIST 1-D dataset and found a (albeit marginal) improvement over this implementation versus the previous one.

Results (n=3):

Hadamard after Weight Matrix (eq1):
 
Trainacc (96.44):               96.31, 96.96, 96.05
Testacc (90.96):                 91.04, 92.90, 88.93                         
Trainloss (0.119):              0.121, 0.113, 0.124
Testloss (0.318):               0.301, 0.234, 0.418
 
Hadamard before Weight Matrix (eq2):
 
Trainacc (96.96):               97.66, 97.30, 95.93
Testacc (92.26):                 92.97, 92.45, 91.38                         
Trainloss (0.103):              0.092, 0.095, 0.121
Testloss (0.244):               0.251, 0.224, 0.258

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @zou3519

**Comment by albanD** [comment]
Hi,

I'm afraid that changing the current implementation would be backward incompatible and we would be very careful about that. If the doc doesn't match the implementation, we should definitely fix that though!

**Comment by jangroter** [comment]
Alright! I believe the current implementation does match the documentation, so that wouldn't be necessary to change in this case. 

It would in this case be nice then to specify that Pytorch' implementation is slightly different from the original maybe to prevent confusion.

**Comment by jbschlosser** [comment]
Actionable to add a note / warning indicating the difference between PyTorch's implementation and that of the original paper.
