### ISSUE TITLE
pyi missing for `torch.fx` in wheel builds

### ISSUE THREAD

**Issue by lkct** [pytorch/pytorch#99530]
### 🐛 Describe the bug

I'm getting type-checking errors with `torch.fx`. After looking into the problem, I found that everything should be correctly typed in https://github.com/pytorch/pytorch/blob/main/torch/fx/__init__.pyi, but this file does not exist in wheel distributions.

The version I installed is https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp38-cp38-linux_x86_64.whl.

I also randomly checked some newest stable and nightly builds and the problem persists (didn't exhaustively check but I assume all the same).

### Versions

torch-2.0.0+cu117-cp38-cp38-linux_x86_64

Also in nightly (20230419)

cc @ezyang @malfet @rgommers @xuzhao9 @gramster @SherlockNoMad @soumith @EikanWang @jgong5 @wenzhe-nrv

**Comment by malfet** [comment]
Thank you very much for reporting. There is no harm in adding to release
