### ISSUE TITLE
`dynamo.export` generates empty arg to constant input.

### ISSUE THREAD

**Issue by titaiwangms** [pytorch/pytorch#99534]
### 🐛 Describe the bug

Constant input is captured as an empty node (arg1) consumed by no one, and the expected user of that node (aten:add) has a constant 8.0 instead.

```python
import torch
from torch import _dynamo as dynamo

def func(x, b=1.0):
    y = x + b
    z = y.relu()
    return (y, z)

x = torch.randn(1, 1, 2, dtype=torch.float32)
gm_fun, _ = dynamo.export(func, x, b=8.0, aten_graph=True, tracing_mode="real")

gm_fun.print_readable()
# class GraphModule(torch.nn.Module):
#     def forward(self, x, b):
#         arg0: f32[1, 1, 2], arg1, = fx_pytree.tree_flatten_spec(([x, b], {}), self._in_spec)
#         # File: /home/titaiwang/pytorch/test_constant_input.py:5, code: y = x + b
#         add_tensor: f32[1, 1, 2] = torch.ops.aten.add.Tensor(arg0, 8.0);  arg0 = None

#         # File: /home/titaiwang/pytorch/test_constant_input.py:6, code: z = y.relu()
#         relu_default: f32[1, 1, 2] = torch.ops.aten.relu.default(add_tensor)
#         return pytree.tree_unflatten([add_tensor, relu_default], self._out_spec)
```

### Versions

main

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by ezyang** [comment]
This will not be supported. To make it work, convert the float argument into a 0d tensor

**Comment by BowenBao** [comment]
Thanks for tips. On a related note is it correct to understand tensor defaults are also not supported? https://github.com/pytorch/pytorch/issues/96379 
I'm curious what's the contract over dynamo traced inputs/outputs?

**Comment by ezyang** [comment]
Hmm, we should support tensor defaults, so that seems like a legit bug. But note that the exported graph will either burn in the tensor default as a constant, or have an input for it, it will not simultaneously model both possibilities.
