### ISSUE TITLE
RuntimeError: "clamp_scalar_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by bhack** [pytorch/pytorch#99563]
### 🚀 The feature, motivation and pitch

Pytorch vision has some assumption about the Tensor data type but as in some API it internally used `clamp_scalar_cpu` is going to fail when we work with `float16` images.

### Additional context

Please check:
https://github.com/pytorch/vision/issues/4915#issuecomment-1515367700

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by jgong5** [comment]
Being addressed at https://github.com/pytorch/pytorch/pull/98493

**Comment by jgong5** [comment]
> This raises a really interesting question on what to do about half on CPU: x86_64 does not support it natively, but ARM does, so I guess they should be treated slightly different on those platforms

Yes, I think the op implementations would work on the same scalar and vectorization abstractions of half. The differences are in the scalar and vectorization implementation of different CPU architectures. For vectorization, we already have a good mechanism to dispatch to the right per-arch vectorized intrinsics. For ARM, it would be just adding its counterpart. For scalar, we call the std functions directly with type-cast and compute in single precision. Maybe, for ARM, this can be implemented directly.

**Comment by jiayisunx** [comment]
"clamp_scalar_cpu" already supports float16 data type, please try again with the latest PyTorch.

**Comment by bruce2233** [comment]
Use <your-tensor>.cuda() first.
