### ISSUE TITLE
torch.gather function doesn't work correctly

### ISSUE THREAD

**Issue by GeoChoi** [pytorch/pytorch#99595]
### 🐛 Describe the bug

torch.gather function doesn't work correctly when 'input' tensor is a floating point tensor

brief about function
torch.gather(input, dim, index) function extract element of 'input' tensor by "index" argument as described at [TORCH.GATHER docs](https://pytorch.org/docs/stable/generated/torch.gather.html?highlight=tensor+gather)

but It doesn't work as docs describe in some condition

I checked just for when 'input' tensor is an the 2D matrix. 
I didn't check the function works properly if 'input' matrix is a higher dimension tensor than 2D. but It seems to work fine when testing it simply. but not sure.

anyway here is the code you can see the bug

```
import torch

m = torch.tensor([[0,1,2,3,4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34],[40,41,42,43,44]])
m_f = m.type(torch.float)
print("m:", m)
print("m_f:", m_f)

index = torch.tensor([[0],[1],[2],[3],[4]])
print("index:", index)

print(torch.gather(m, dim=0, index=index ))
print(torch.gather(m_f, dim=0, index=index ))

```

the output is 
```
m: tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])
m_f: tensor([[ 0.,  1.,  2.,  3.,  4.],
        [10., 11., 12., 13., 14.],
        [20., 21., 22., 23., 24.],
        [30., 31., 32., 33., 34.],
        [40., 41., 42., 43., 44.]])
index: tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[ 0],
        [10],
        [20],
        [30],
        [40]])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
```

as you see output should be 
```
tensor([[ 0],
        [10],
        [20],
        [30],
        [40]])
```
as like when 'input' tensor is integer tensor.
It work well. The results are consistent with the explanation in docs
result[i][j] = m[index[i][j]][j]

but when I just turn the 'input' tensor to a float tensor which has the same value but just a different data type,
the result is different and it is wrong
```
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
```

here is a condition I found when torch.gather function doesn't work correctly
when the 'input' matrix is 2D
1. type of  'input' matrix is floating type.
2. argument 'dim' is 0
3. 'index' matrix is a one-line vertical tensor like `torch.tensor([[0],[1],[2],[3],[4]])

It works fine 
when dtype of 'input' matrix is an integer type. 
or
when 'index' matrix is not one-line vertical matrix like `torch.tensor([[0,4],[1,3],[2,2],[3,1],[4,0]])`
or
'dim' is 1

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      25
Model:                           80
Model name:                      AMD Ryzen 5 5600U with Radeon Graphics
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1600.000
CPU max MHz:                     2300.0000
CPU min MHz:                     1600.0000
BogoMIPS:                        4591.60
Virtualization:                  AMD-V
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        3 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   2.0.0              py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                2.0.0                 py310_cpu    pytorch
[conda] torchvision               0.15.0                py310_cpu    pytorch

cc @mikaylagawarecki

**Comment by soulitzer** [comment]
I was unable to repro this, you may want to try a newer version of pytorch. I am seeing:
```
m: tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])
m_f: tensor([[ 0.,  1.,  2.,  3.,  4.],
        [10., 11., 12., 13., 14.],
        [20., 21., 22., 23., 24.],
        [30., 31., 32., 33., 34.],
        [40., 41., 42., 43., 44.]])
index: tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[ 0],
        [10],
        [20],
        [30],
        [40]])
tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.]])
   ```

**Comment by GeoChoi** [comment]
currently, I'm using pytorch version 2.0.0 which is the latest version among the stable versions.
what is your pytorch version?

**Comment by mingfeima** [comment]
@soulitzer @GeoChoi our validation team has reproduced this on nightly build, this should be a CPU bug. Will have it fixed in near future.

**Comment by mingfeima** [comment]
https://github.com/pytorch/pytorch/pull/99709 is to fix this issue.

the output with this patch would be
```
m: tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44]])
m_f: tensor([[ 0.,  1.,  2.,  3.,  4.],
        [10., 11., 12., 13., 14.],
        [20., 21., 22., 23., 24.],
        [30., 31., 32., 33., 34.],
        [40., 41., 42., 43., 44.]])
index: tensor([[0],
        [1],
        [2],
        [3],
        [4]])
tensor([[ 0],
        [10],
        [20],
        [30],
        [40]])
tensor([[ 0.],
        [10.],
        [20.],
        [30.],
        [40.]])

```
