### ISSUE TITLE
Add support for dynamic control flow in torch.fx 

### ISSUE THREAD

**Issue by lix19937** [pytorch/pytorch#99598]
### 🚀 The feature, motivation and pitch

More and more post-processing code is incorporated into the model, and post-processing code often has dynamic control flow logic. 

cc @zou3519 @Chillee @samdow @soumith @kshitij12345 @janeyx99 @ezyang

**Comment by ezyang** [comment]
Does torch.cond fit your bill here?

**Comment by lix19937** [comment]
for example,  follow case 
`Proxy object cannot be iterated`    
`Proxy cannot be used as inputs to control flow`    
`'len' is not supported in symbolic tracing by default`    

Although there are some workaround solutions, they are still not perfect

**Comment by ezyang** [comment]
can't use symbolic_trace for this, need to use make_fx

**Comment by lix19937** [comment]
@ezyang Thanks, can you provide an example of make_fx ?

**Comment by ezyang** [comment]
check test/test_proxy_tensor.py

**Comment by lix19937** [comment]
@ezyang  ok, thanks !
