### ISSUE TITLE
DISABLED test_save_graph_repro (__main__.TestAfterAot)

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#99602]
Platforms: Linux

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/dynamo%2Ftest_after_aot.py%3A%3ATestAfterAot%3A%3Atest_save_graph_repro)).

This is a new test coming from https://github.com/pytorch/pytorch/pull/99538.  It starts failing in trunk now, but I'm not sure why the failure appears in a few commits after.  I only try to disable the test now to keep trunk green.  If we decide to revert the PR, this issue can be closed. cc @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @kit1980 @ezyang

**Comment by kit1980** [comment]
I didn't see this issue before reverting the PR.
As the PR is reverted, closing the issue.

**Comment by huydhn** [comment]
Reopen this to avoid failing this test for folks till https://github.com/pytorch/pytorch/pull/99627 lands
