### ISSUE TITLE
Segfault in torch.tensor with invalid arguments

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#9963]
The following segfaults:

```python
torch.tensor([0,'1'])
```

Also:

```python
torch.as_tensor([0,'1'])
```

**Comment by colesbury** [comment]
The bug is that the string `'1'`is also a sequence, so `infer_scalar_type` gets into an infinite recursion in torch/csrc/utils/tensor_new.cpp

**Comment by colesbury** [comment]
Not surprisingly, this infinite sequence also segfaults:

```
x = [0]
x += [x]
torch.tensor(x)
```

**Comment by vishwakftw** [comment]
I think I have fixed this locally, but it involves one extra pass over the elements of the sequence to check if the type is consistent.

NumPy also seems to do this, as shown here https://github.com/numpy/numpy/blob/0df35634a2bf2bfff0acfb5d6a6b26eea0265e56/numpy/core/src/multiarray/common.c#L449-L453 .

If this approach of double-passing is fine (I couldn't think of a better way), I could send in a PR.
