### ISSUE TITLE
Variable name error in NCCL_MAJOR

### ISSUE THREAD

**Issue by ajindal1** [pytorch/pytorch#99643]
### 🐛 Describe the bug

There is a typing error in nccl.cpp file https://github.com/pytorch/pytorch/blob/aa4ed332c33a63324cf76574ae5df3107f02cadb/torch/csrc/cuda/nccl.cpp#L20 

It has been fixed in this PR, can someone take a look: https://github.com/pytorch/pytorch/pull/99482

cc @eqy

### Versions

NA

**Comment by eqy** [comment]
Nice catch, thanks for the fix!
