### ISSUE TITLE
Conda MacOS installation install pytorch-1.13 rather than 2.0 as of Apr 4th

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#99653]
### 🐛 Describe the bug

See https://hud.pytorch.org/hud/pytorch/builder/main/1?per_page=50&name_filter=cron%20%2F%20release%20%2F%20mac%20%2F%20conda-py3

Last successful run: https://github.com/pytorch/builder/actions/runs/4619355597/jobs/8168032918

First faulty run: https://github.com/pytorch/builder/actions/runs/4629742465/jobs/8190405098

### Versions

2.0

cc @ezyang @gchanan @zou3519 @seemethere

**Comment by malfet** [comment]
Looks like switch happened on Anaconda from using `blas=mkl` to `blas=openblas`

**Comment by malfet** [comment]
@seemethere which brings back an interesting question: how important is Anaconda for us?

**Comment by bdhirsh** [comment]
fixed by https://github.com/pytorch/test-infra/pull/4058
