### ISSUE TITLE
ROCm runner 'worker-rocm-amd-108' is out of storage space

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#99656]
### 🐛 Describe the bug

Multiple ROCm jobs are failing with the error:

`Error: No space left on device : '/home/pytorchci/actions-runner/_diag/Worker_20230420-194436-utc.log'`

These all occur on the runner  `worker-rocm-amd-108`

Example: https://github.com/pytorch/pytorch/actions/runs/4758073637/jobs/8456080762

### Versions

n/a

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by ZainRizvi** [comment]
This is a continuation of https://github.com/pytorch/pytorch/issues/99578

**Comment by jithunnair-amd** [comment]
Diskspace issues should be resolved with -108 now:
```
pytorchci@jenkins-worker-rocm-amd-108:~$ df -kh .
Filesystem                                  Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--server--x8664--vg-root  879G  132G  703G  16% /
```
