### ISSUE TITLE
[CI] the workflow failed because of `no module named triton`

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#99688]
### 🐛 Describe the bug

in my PR of https://github.com/pytorch/pytorch/pull/99540, I just make the func in C++ not be private, but the ci workflow [win-vs2019-cpu-py3 / test (default, 3, 3, windows.4xlarge)](https://hud.pytorch.org/pr/pytorch/pytorch/99540#12893750040) ([gh](https://github.com/pytorch/pytorch/actions/runs/4753502817/jobs/8446123810)) failed, `no module named triton`
And I saw the error caused by this PR https://github.com/pytorch/pytorch/pull/97203/files   torch/_inductor/coordinate_descent_tuner.py , could you have a look? @kit1980 

### Versions

pytorch/main 2023.4.21

**Comment by kit1980** [comment]
The #97203 was reverted, but your branch probably still includes the reverted commit.
I've triggered a rebase  for your PR, that should fix the issue.

**Comment by heidongxianhua** [comment]
> The #97203 was reverted, but your branch probably still includes the reverted commit. I've triggered a rebase for your PR, that should fix the issue.

hhaha, yeah, thank you

**Comment by malfet** [comment]
Please base/re-base your PRs against `viable/strict` to get signal on  failures caused by your changes.
