### ISSUE TITLE
ImportError: libpython3.6m.so.1.0

### ISSUE THREAD

**Issue by sparseinference** [pytorch/pytorch#997]
I thought I would try pytorch : torch-0.1.10.post2-cp36-cp36m-linux_x86_64

On the first example I tried (MNIST), it fails:

`Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import torch
  File "/home/peter/python36/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory`

 .. which is correct, there is no such shared object on my system.

Any ideas?

**Comment by soumith** [comment]
can you elaborate on how you installed pytorch?

**Comment by soumith** [comment]
oh, i see that the problem is loading `libpython3.6m.so.1.0` itself. Hmmm, for a python 3.6 install this does need to exist, or at least it seems to exist on other machines. 
Can you see what `libpython*so*` exists on your system?

**Comment by sparseinference** [comment]
@soumith   There are some older libpython3.5m.so*  files but I don't use them since moving to 3.6 .
I built Python 3.6 from source and installed it to a directory in my home directory. Maybe that's why the .so file doesn't exist?

**Comment by colesbury** [comment]
Perhaps you forgot "--enable-shared" when you built Python.

**Comment by sparseinference** [comment]
@colesbury  That's probably true. I didn't think of it since the Python installation README doesn't mention it at all (i think).

**Comment by sparseinference** [comment]
@soumith  @colesbury    Thanks for your help!

**Comment by jaara** [comment]
I solved the same issue by installing a libpython3.6-dev package on Ubuntu system.
