### ISSUE TITLE
Support batches in pca_lowrank

### ISSUE THREAD

**Issue by pbsds** [pytorch/pytorch#99705]
### 🚀 The feature, motivation and pitch

Currently, `torch.pca_lowrank` computes the pca for all data points, but common in ML is using large independent batches of data.

Given a batch `(B, N, K)`, one currently has to split it into `B` x `(N, K)` batches and compute their PCA separately, before stacking the results back into a single tensor. To stack the `S` output one would have to do something like:

```python
S = torch.stack(tuple(
    torch.pca_lowrank(data[i])[1]
    for i in range(data.shape[0])
), dim=0)
```

Much better would be something like

```python
U, S, V = torch.pca_lowrank(data, dim=(1,)) # matches torch.mean, may affect backward compat
#or
U, S, V = torch.batched_pca_lowrank(data, dim=(1,))
```

### Alternatives

Doing nothing \shrug

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by nikitaved** [comment]
CC @pearu . Shouldn't be hard, I guess.

**Comment by pearu** [comment]
`pca_lowrank` already supports batches if input data is a strided tensor. For example:
```python
>>> import torch
>>> from torch.testing._internal.common_utils import random_lowrank_matrix
>>> a = random_lowrank_matrix(2, 7, 4, 2)
>>> b = random_lowrank_matrix(3, 7, 4, 2)
>>> a[1] = b[1]  # just to make batches rank-variable
>>> torch.pca_lowrank(a)[1]
tensor([[9.9470e-01, 1.1127e-01, 2.5204e-17, 9.6509e-19],
        [5.8583e-01, 3.5981e-01, 8.5951e-02, 4.3136e-19]], dtype=torch.float64)
```

**Comment by lezcano** [comment]
Seems like it's working in master
