### ISSUE TITLE
torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing) 

### ISSUE THREAD

**Issue by GitHub-TXZ** [pytorch/pytorch#99708]
Where should I find the original C++code for this line of code? Thank you

**Comment by GitHub-TXZ** [comment]
Where should I find the original C++code for this line of code? Thank you.

**Comment by ezyang** [comment]
aten/src/ATen/native/LossNLL.cpp
