### ISSUE TITLE
`cross_entropy` fails in `FakeTensorMode` with label_smoothing+weight

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#99726]
This is very similar to #99250 but with an added weight, #99255 fixed that one but notes in the comment this case is not handled.

Creating an issue, so this is tracked.  #98894 modifies a test to not hit this issue.

Repro
```py
import torch
from torch._subclasses import FakeTensorMode


with FakeTensorMode():
    input = torch.randn(3, 5)
    target = torch.empty(3, dtype=torch.long).random_(5)
    torch.nn.functional.cross_entropy(input, target, label_smoothing=0.5, weight=torch.randn(5))
```
Output
```py
Traceback (most recent call last):
  File "/home/jansel/pytorch/repro.py", line 8, in <module>
    torch.nn.functional.cross_entropy(input, target, label_smoothing=0.5, weight=torch.randn(5))
  File "/home/jansel/pytorch/torch/nn/functional.py", line 3051, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
  File "/home/jansel/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 1095, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 1286, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/home/jansel/pytorch/torch/_subclasses/fake_tensor.py", line 446, in dyn_shape
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.masked_select.default
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
I can handle it, but it would require making copy of weights, and result in worse perf in non-fake model. I haven't found a way to have different paths for fake/non-fake modes in c++.
cc @jbschlosser on whether it's acceptable to regress perf of the smoothing + weights case.

**Comment by jansel** [comment]
Could we define a meta function for `cross_entropy` that wouldn't need to run the decomposed version?

**Comment by ezyang** [comment]
If you don't actually want to decomp, yeah, a direct meta would work.

**Comment by ngimel** [comment]
This is composite implicit, could we prevent decomposing it?

**Comment by ezyang** [comment]
Natalia and I discussed this, and Natalia is going to try avoiding the data dependent op if the tensors involved are "like python subclass" which would trigger during tracing.
