### ISSUE TITLE
vision.py missing required `_six` attribute from torch for MNIST download?

### ISSUE THREAD

**Issue by Ethan-Loo** [pytorch/pytorch#99813]
### 🐛 Describe the bug

While attempting to walk through a simple MNIST test of Pytorch, I seem to be unable to download the mnist dataset in the latest stable build of pytorch. Below is the code I'm using when the problem is generated:
```
import torch 
import torchvision
import torchvision.transforms as transforms

# Define the transformation to be applied to the images
transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])

# Load the train and test datasets
trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
testset = torchvision.datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# Define the data loaders to load the data in batches
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False)
```

This results in the following error in DataSpell:
DataSpell 2022.3.3
Build #DS-223.8836.46, built on March 13, 2023

For educational use only.
Runtime version: 17.0.6+1-b653.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 24
Registry:
    python.scientific.show_help_window=false
    python.scientific.always_use_sci_view=true

Non-Bundled Plugins:
    club.nutsoft.Github3Theme (1.2.0)
    IdeaVIM (2.1.0)
    com.github.copilot (1.2.5.2507)

```
Traceback (most recent call last):
  File "C:\Users\IceManLoo\AppData\Roaming\Python\Python39\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-6120b7da4b1b>", line 1, in <cell line: 1>
    runfile('C:\\Users\\IceManLoo\\Documents\\PyTorch_Testing\\where_is_torch_running.py', wdir='C:\\Users\\IceManLoo\\Documents\\PyTorch_Testing')
  File "C:\Program Files\JetBrains\DataSpell 2021.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\DataSpell 2021.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\IceManLoo\Documents\PyTorch_Testing\where_is_torch_running.py", line 18, in <module>
    trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
  File "C:\Users\IceManLoo\AppData\Roaming\Python\Python39\site-packages\torchvision\datasets\mnist.py", line 91, in __init__
    super().__init__(root, transform=transform, target_transform=target_transform)
  File "C:\Users\IceManLoo\AppData\Roaming\Python\Python39\site-packages\torchvision\datasets\vision.py", line 39, in __init__
    if isinstance(root, torch._six.string_classes):
AttributeError: module 'torch' has no attribute '_six'
```

When running my script via the Anaconda3 command prompt I receive the following error:
![image](https://user-images.githubusercontent.com/45986326/233826025-49921db8-b8ff-44f1-9785-7d9e626d5a7c.png)

Along with a similar AttributeError:
```
Traceback (most recent call last):
  File "C:\Users\User\Documents\PyTorch_Testing\where_is_torch_running.py", line 18, in <module>
    trainset = torchvision.datasets.MNIST(root='./data', train=True, download=True, transform=transform)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\torchvision\datasets\mnist.py", line 91, in __init__
    super().__init__(root, transform=transform, target_transform=target_transform)
  File "C:\Users\User\AppData\Roaming\Python\Python39\site-packages\torchvision\datasets\vision.py", line 39, in __init__
    if isinstance(root, torch._six.string_classes):
AttributeError: module 'torch' has no attribute '_six'
```
Something I noticed that that `torch` no longer contains a `_six` or `six` object/function when trying to call it in a script. It's simply missing from the library. I'm assuming there's a new way to access this functionality that's different in 2.0.0 or this was missing from the build somehow. 

This appears to be a 2.0.0-specific issue, as I've used a previous version of pytorch without running into this. Is there a workaround for this or a new or different way to download datasets in 2.0.0? Presumably, this is not isolated to mnist dataset retrieval.

Edit: Upon further inspection `_six` exists in the torch library but doesn't seem to be accessing it. Instead, it's reaching for the package from AppData/Roaming, when it should be looking in the `envs` library. This may be a personal issue with how Anaconda is handling this. Will investigate further.

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 531.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3701
DeviceID=CPU0
Family=107
L2CacheSize=6144
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3701
Name=AMD Ryzen 9 5900X 12-Core Processor
ProcessorType=3
Revision=8450

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] pytorchDL==0.6.6
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0+cu116
[pip3] torchvision==0.14.0
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.23.5           py39h3b20f71_0
[conda] numpy-base                1.23.5           py39h4da318b_0
[conda] pytorch                   2.0.0           py3.9_cuda11.8_cudnn8_0    pytorch
[conda] pytorch-cuda              11.8                 h24eeafa_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torchaudio                2.0.0                    pypi_0    pypi
[conda] torchvision               0.15.0                   pypi_0    pypi

**Comment by meghbhalerao** [comment]
were you able to resolve this? @Ethan-Loo

**Comment by ElinorG11** [comment]
I get the same problem, any ideas? @Ethan-Loo  @meghbhalerao 
Thanks

**Comment by Ethan-Loo** [comment]
I was able to fix this. I had two versions of Pytorch installed on my machine. I think this is more related to how your environment handles the versions/installations and less to Pytorch itself. 

In my case I had an older version of pytorch installed in a venv and was attempting to install in conda. I had to remove all versions of pytorch from all directories and do a fresh install because the newer version of pytorch was attempting to pull modules and/or other dependencies from the venv versions of those modules and libs. 

My suggestion is to wipe Pytorch from _all_ environments and directories inside and outside of conda and do a fresh install where you want it.

**Comment by yunxiaoliCB** [comment]
I was running a script based on torchdrug and encountered this error using torch=2.0.0. 
I tried [Ethan-Loo](https://github.com/Ethan-Loo)'s fix (uninstalling all torch in all environments) and didn't work it out. I find that indeed there isn't a _six.py in torch module v2.0.0. There is one for version v1.13.0. I copied that _six.py file into torch module (inside site-packages directory under conda env) and import it in the __init__.py file. That fixes the problem for me, though I know that modifying an installed package in that way is a bad idea.

**Comment by zbjumper** [comment]
I also encountered the same problem.

**Comment by Kin-Zhang** [comment]
I think maybe it's for 2.0.0 only, I tested the latest version 2.5.1, and no error anymore.

**Comment by kpierce8** [comment]
Getting this today with a fresh 2.4.1 environment
