### ISSUE TITLE
[Quant][pt2e] Fail to run RN50 QAT training after prepare_qat

### ISSUE THREAD

**Issue by leslie-fang-intel** [pytorch/pytorch#99858]
### 🐛 Describe the bug

When trying to run the RN50 QAT training with PyTorch 2.0 Quantization flow in this [script](https://gist.github.com/leslie-fang-intel/ba5f37035bf63fb787a4f831fa09f911). It throws error message that some `NoneType` input is not supported.
Details of the error message:
```
--------------PyTorch 2.0 QAT -----------
Traceback (most recent call last):
  File "/home/lesliefang/pytorch_1_7_1/torch_inductor/torch_script/inductor/int8/qat/test_issue.py", line 54, in <module>
    pytorch_pt2e_qat(model_fp, data)
  File "/home/lesliefang/pytorch_1_7_1/torch_inductor/torch_script/inductor/int8/qat/test_issue.py", line 28, in pytorch_pt2e_qat
    m = prepare_qat_pt2e_quantizer(m, quantizer)
  File "/home/lesliefang/pytorch_1_7_1/inductor_quant/pytorch/torch/ao/quantization/_quantize_pt2e.py", line 77, in prepare_qat_pt2e_quantizer
    _fuse_conv_bn_qat(model)
  File "/home/lesliefang/pytorch_1_7_1/inductor_quant/pytorch/torch/ao/quantization/_pt2e/qat_utils.py", line 120, in _fuse_conv_bn_qat
    if original_node.target == torch.ops.aten.convolution.default:
AttributeError: 'NoneType' object has no attribute 'target'
```
1. After some triage, I think this issue relates to  [_fused_qat_conv2d_bn_pattern](https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/_pt2e/qat_utils.py#L35) when the `conv_bias` is None.
2. I have another open is that in above case when after `convert_pt2e`, the `BN` node still exists in the FX graph. In our Quantization 2.0 QAT design, where do we plan to do the conv bn fusion into a single conv node?

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+git79c9e82
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.17

Python version: 3.9.10 (main, Mar  2 2022, 12:02:00)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-4.19.5-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    1
Core(s) per socket:    28
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel Genuine CPU
Stepping:              10
CPU MHz:               2343.622
CPU max MHz:           2900.0000
CPU min MHz:           1200.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              39424K
NUMA node0 CPU(s):     0-27
NUMA node1 CPU(s):     28-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.0+git95d588e
[pip3] numpy==1.22.3
[pip3] torch==2.1.0a0+git79c9e82
[pip3] torchvision==0.16.0a0+5579995
[conda] mkl                       2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0            intel_25398    intel
[conda] mkl-include               2023.0.0                  <pip>
[conda] mkl-service               2.4.0           py39h3605609_14    intel
[conda] mkl-static                2023.0.0                  <pip>
[conda] mkl_fft                   1.3.1           py39hcab1719_22    intel
[conda] mkl_random                1.2.2           py39hbf47bc3_22    intel
[conda] mkl_umath                 0.1.1           py39hf66a691_32    intel
[conda] numpy                     1.22.3           py39hf0956d0_5    intel
[conda] numpy-base                1.22.3           py39h45c9ace_5    intel
[conda] torchvision               0.16.0a0+5579995           <pip>

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen

**Comment by leslie-fang-intel** [comment]
@andrewor14 Could you kindly take a look of this issue?

**Comment by leslie-fang-intel** [comment]
Hi @andrewor14, really thanks for helping looking into this issue and looking forward to the fix. Regarding to the conv bn folding for QAT flow, to be clearer: will quantization team provides a extra API after convert ( as part of quantization flow) to do the folding? or backend development needs to provide this pass by each backend?

**Comment by jerryzh168** [comment]
> Hi @andrewor14, really thanks for helping looking into this issue and looking forward to the fix. Regarding to the conv bn folding for QAT flow, to be clearer: will quantization team provides a extra API after convert ( as part of quantization flow) to do the folding? or backend development needs to provide this pass by each backend?

we'll do conv-bn folding as part of the convert, I have a diff in phabricator right now actually, will export it soon

**Comment by leslie-fang-intel** [comment]
Got it and thanks.

**Comment by andrewor14** [comment]
Hi @leslie-fang-intel, this should be working now so I'm closing this issue. See this [unit test](https://github.com/pytorch/pytorch/blob/eb4a1a07afecda3a04693c8077c167a3ccf64465/test/quantization/pt2e/test_quantize_pt2e.py#L2022C9-L2022C26).

**Comment by leslie-fang-intel** [comment]
Great. Thanks @andrewor14.
