### ISSUE TITLE
Logs output_code and inductor do not interact as expected

### ISSUE THREAD

**Issue by lezcano** [pytorch/pytorch#99866]
### 🐛 Describe the bug

As discussed in https://github.com/pytorch/pytorch/issues/94788#issuecomment-1515441713, setting `inductor` does not generate the `output_code` artefact. This goes against the definition that `output_code` is an artifact owned by `inductor`. This issue lead to the discussion in https://github.com/pytorch/pytorch/pull/99038 of wanting to log the output folder at two different levels, which signals that there's something a bit off about the whole thing. The better way of controlling this would be via logging the output file and the code at two different verbosity levels.

cc @mlazos @kurtamohler 

### Versions

master

**Comment by mlazos** [comment]
I'm closing this, this is expected behavior and we've added documentation and recipes since.
