### ISSUE TITLE
wrong results from torch.dot

### ISSUE THREAD

**Issue by husisy** [pytorch/pytorch#99868]
## reproduce the wrong result

create `env-conda-forge` environment

```bash
conda create -y -n env-conda-forge
conda install -y -n env-conda-forge -c conda-forge -c pytorch mkl=2022.1 pytorch=2.0 torchvision torchaudio cpuonly
```

Python code

```Python
import numpy as np
import torch
print(np.__version__) #1.24.3
print(torch.__version__) #2.0.0
# print(torch.__config__.show())

x = torch.tensor([1], dtype=torch.complex128)
print(torch.dot(x, x)) #tensor(0.+0.j, dtype=torch.complex128)
# expected: tensor(1, dtype=torch.complex128)
```

expect `1+0j` but get `0+0j`.

## some tests

create three environments to make a comparison

```bash
# for mamba/conda-forge user, mkl=2022.1 is default and latest, so i name it env-conda-forge
# "-c conda-forge" is necessary, without it, "conda install" will raise UnsatisfiableError
conda create -y -n env-conda-forge
conda install -y -n env-conda-forge -c conda-forge -c pytorch mkl=2022.1 pytorch=2.0 torchvision torchaudio cpuonly

# no conda-forge
conda create -y -n env-no-conda-forge
conda install -y -n env-no-conda-forge -c pytorch mkl pytorch torchvision torchaudio cpuonly

# create a environment, install pytorch with pip
conda create -y -n env-pip python=3.10
conda activate env-pip
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```

`print(torch.__config__.show())` shows the only difference is

```text
## env-conda-forge
  - Intel(R) oneAPI Math Kernel Library Version 2022.1-Product Build 20220311 for Intel(R) 64 architecture applications
## env-no-conda-forge
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
## env-pip
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
```

in summary,

| env-name | MKL | `np.__version__` | `torch.__version__` | `torch.dot(xxxx)` |
| :-: | :-: | :-: | :-: | :-: |
| env-conda-forge | 2022.1 | 1.24.3 | 2.0.0 | `0+0j` (wrong) |
| env-no-conda-forge | 2021.4 | 1.23.5 | 2.0.0 | `1+0j` (correct) |
| env-pip | 2022.2 | 1.24.1 | 2.0.0+cpu | `1+0j` (correct) |

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: 14.0.0-1ubuntu1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.19.0-40-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          16
On-line CPU(s) list:             0-15
Vendor ID:                       AuthenticAMD
Model name:                      AMD Ryzen 7 5800H with Radeon Graphics
CPU family:                      25
Model:                           80
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     4462.5000
CPU min MHz:                     1200.0000
BogoMIPS:                        6388.03
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
Virtualization:                  AMD-V
L1d cache:                       256 KiB (8 instances)
L1i cache:                       256 KiB (8 instances)
L2 cache:                        4 MiB (8 instances)
L3 cache:                        16 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] cpuonly                   2.0                           0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.24.3          py310ha4c1d20_0    conda-forge
[conda] pytorch                   2.0.0              py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                2.0.0                 py310_cpu    pytorch
[conda] torchvision               0.15.0                py310_cpu    pytorch

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @rgommers @jianyuh @pearu @walterddr @IvanYashchuk @xwang233

**Comment by ezyang** [comment]
strange indeed. Could it be an MKL problem? 🤔

**Comment by whu-dft** [comment]
> strange indeed. Could it be an MKL problem? 🤔

Yes, I think it's just the MKL problem.

**Comment by lezcano** [comment]
It works for me on 2021.3, so it looks like it's an issue of version 2021.1. The easiest way to patch this would be not to take the MKL path for `complex128` on versions of MKL <= 2021.1. This should still be reasonably fast, as it'll go through the BLAS implementation. 

We would accept a fix for this.

**Comment by jgong5** [comment]
I cannot repro with MKL 2022.1 locally. I only installed the necessary libs for the repro below:
```python
import torch
print(torch.__version__)
x = torch.tensor([1], dtype=torch.complex128)
print(torch.dot(x, x))
```
```bash
conda install -y -c pytorch mkl=2022.1 pytorch=2.0
```
I got output below
```bash
$ python test.py
2.0.0
test.py:3: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /opt/conda/conda-bld/pytorch_1678402316912/work/torch/csrc/utils/tensor_numpy.cpp:84.)
  x = torch.tensor([1], dtype=torch.complex128)
tensor(1.+0.j, dtype=torch.complex128)

$ conda list
# packages in environment at /home/jgong5/miniconda3/envs/pytorch_bin:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
ca-certificates           2023.01.10           h06a4308_0  
filelock                  3.9.0            py38h06a4308_0  
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py38heeb90bb_0  
intel-openmp              2022.1.0          h9e868ea_3769  
jinja2                    3.1.2            py38h06a4308_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
markupsafe                2.1.1            py38h7f8727e_0  
mkl                       2022.1.0           hc2b9512_224  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.2.1            py38h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
networkx                  2.8.4            py38h06a4308_1  
openssl                   1.1.1t               h7f8727e_0  
pip                       23.0.1           py38h06a4308_0  
python                    3.8.16               h7a1cb2a_3  
pytorch                   2.0.0               py3.8_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
readline                  8.2                  h5eee18b_0  
setuptools                66.0.0           py38h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.11.1           py38h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
typing_extensions         4.5.0            py38h06a4308_0  
wheel                     0.38.4           py38h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0
```

**Comment by husisy** [comment]
I can repro your repro in some way. Two environments: `env-test00` is just like you (not include `numpy`), `env-test02` add `-c conda-forge` to include `numpy`

```bash
# [correct] no numpy
conda create -y -n env-test00
conda install -y -n env-test00 -c pytorch mkl=2022.1 pytorch=2.0

# [fail] fail to solve environment
# conda create -y -n env-test01
# conda install -y -n env-test01 -c pytorch mkl=2022.1 pytorch=2.0 numpy

# [wrong] same as env-conda-forge at the beginning, take more than 5 minutes to solve environment
conda create -y -n env-test02
conda install -y -n env-test02 -c conda-forge -c pytorch mkl=2022.1 pytorch=2.0 numpy
```

Two python files: `main-no-np.py` and `main-with-np.py` (import `numpy` at the beginning)

```Python
# main-no-np.py
import torch
x = torch.tensor([1], dtype=torch.complex128)
print(torch.dot(x, x))
```

```Python
# main-with-np.py
import numpy as np
import torch
x = torch.tensor([1], dtype=torch.complex128)
print(torch.dot(x, x))
```

results: (your repro is at the first line @jgong5 )

| env-name | python-file | `torch.dot(xxx)` |
| --- | --- | --- |
| `env-test00` | `main-no-np.py` | `1+0j` (correct) |
| `env-test00` | `main-with-np.py` | - |
| `env-test02` | `main-no-np.py` | `1+0j` (correct) |
| `env-test02` | `main-with-np.py` | `0+0j` (wrong) |

let me explain why i try `env-test02` (or `env-conda-forge`): as a micromamba/conda-forge user, i install pytorch using the following command. then all above happened. thx for help.

```bash
micromamba create -y -n env-test03
micromamba install -y -n env-test03 -c pytorch pytorch torchvision torchaudio cpuonly
```

**Comment by husisy** [comment]
After some trials, I find that I should not mix `pytorch` and `conda-forge` channel. The following two environments produce correct results.

```bash
conda create -y -n env00
conda install -y -n env00 -c pytorch pytorch
conda install -y -n env00 numpy

# for mamba/micromamba user (conda-forge as default)
micromamba create -y -n env01
micromamba install -y -n env01 -c conda-forge pytorch numpy

# do not mix conda-forge and pytorch channel
```
