### ISSUE TITLE
It's unclear if `MultiheadAttention` uses `FlashAttention` or not

### ISSUE THREAD

**Issue by grazder** [pytorch/pytorch#99878]
### 🚀 The feature, motivation and pitch

There are a lot of conditions for activating FlashAttention [from doc](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html), and it is easy to miss one. So the default implementation will work. And to find out if FlashAttention works, I have to profile model. 
It would be great if there was a warning that the default implementation works.

cc @jbschlosser @bhosmer @cpuhrsch @erichan1

**Comment by Skylion007** [comment]
Or better yet just add a logger message that it's be used.

**Comment by cpuhrsch** [comment]
cc @drisspg

**Comment by drisspg** [comment]
This section in the tutorial covers this: https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html#explicit-dispatcher-control

If a user wants to inforce that a  fused kernel is called they should turn off the math fallback using sdp_kernel context manager.

**Comment by lms-mt** [comment]
@drisspg  Hi, does `torch.nn.functional.scaled_dot_product_attention` supports backward? I see into the Pytorch source and found that Xformer has `run_fmha_bwd` interface, but it wasn't called in torch.  Glad to have your reply.

**Comment by drisspg** [comment]
@lms-mt yes scaled_dot_product_attention has backward support
