### ISSUE TITLE
Many models are failing on periodic dynamic shape benchmark tests dynamic_aot_eager

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#99893]
### 🐛 Describe the bug

For example, https://hud.pytorch.org/pytorch/pytorch/commit/ab0a8215bb73c508ecfaabead6f3118beef2547f.  There are more than one root cause here I think.  I have moved the test to unstable in the meantime https://github.com/pytorch/pytorch/pull/99895

### Versions

PyTorch CI

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
https://github.com/pytorch/pytorch/pull/99889 should help but we may need to just update the xfails
