### ISSUE TITLE
Falling to turn shape into Tensor

### ISSUE THREAD

**Issue by tobyclh** [pytorch/pytorch#9989]
## Issue description
When directly trying to turn a torch.size object into tensor, the resulting tensor contains random value.

## Code example
```
a = torch.ones(10,10)
b = torch.Tensor(a.shape)  ## tensor with random value
b.shape # torch.Size([10, 10])
s = [*a.shape] ## s = [10, 10]
b = torch.Tensor(s) ##expected result 
b = torch.Tensor([*a.shape]) #tensor with random value / sometimes expected result
```

## System Info
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip
- Build command you used (if compiling from source):
- OS: Ubuntu 18.04
- PyTorch version: 0.4
- Python version: 3.6
- CUDA/cuDNN version: 9.1
- GPU models and configuration: 1060
- GCC version (if compiling from source):
- CMake version:

**Comment by fmassa** [comment]
Do
```python
a = torch.ones(10, 10)
b = torch.tensor(a.shape)
print(b)
# tensor([10, 10])
```
Also, questions like this are better suited for https://discuss.pytorch.org/
