### ISSUE TITLE
Can the CUDA device LUID be exposed as part of _CudaDeviceProperties?

### ISSUE THREAD

**Issue by mbechard** [pytorch/pytorch#99903]
### 🚀 The feature, motivation and pitch

CUDA devices can be ordered in a few different ways (FASTEST_FIRST, PCI_BUS_ID). The device LUID is the more modern way of describing a GPU in a unique way. It's particularly useful when using CUDA along with other APIs such as Vulkan or DirectX.
Can the LUID that the cudaDeviceProp structure contains be made visible in _CudaDeviceProperties as well?
https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html#structcudaDeviceProp_1b1fe931f3f41d1b97c8679c8b15d94e3

Thanks

cc @ngimel

**Comment by malfet** [comment]
Looks like this property is only available on Windows...

**Comment by ngimel** [comment]
There's a uuid that's universally available https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html#structcudaDeviceProp_1626c20637498c7be1381db55a6261308

**Comment by mbechard** [comment]
Ah sorry, uuid may be more appropriate then
https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html#structcudaDeviceProp_1626c20637498c7be1381db55a6261308
Although luid seems to be useful for interop with DirectX on Windows systems

**Comment by ngimel** [comment]
We'll accept a PR adding this
