### ISSUE TITLE
Build fails in caffe2 git master with OpenCL ON

### ISSUE THREAD

**Issue by dbermond** [pytorch/pytorch#9990]
I'm getting the following compile error when trying to build caffe2 git master:
```
[ 52%] Building CXX object caffe2/CMakeFiles/caffe2.dir/contrib/opencl/context.cc.o
In file included from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/registry.h:21,
                 from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/flags.h:23,
                 from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/logging.h:10,
                 from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/allocator.h:6,
                 from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/context.h:9,
                 from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/contrib/opencl/context.h:4,
                 from /storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/contrib/opencl/context.cc:1:
/storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/contrib/opencl/context.cc:10:18: error: ‘caffe2::Tensor’ is not a template
 CAFFE_KNOWN_TYPE(Tensor<OpenCLContext>);
                  ^~~~~~
/storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/typeid.h:403:28: note: in definition of macro ‘CAFFE_KNOWN_TYPE’
   CaffeTypeId TypeMeta::Id<T>() {                                                  \
                            ^
/storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/typeid.h:403:15: error: redefinition of ‘static caffe2::CaffeTypeId caffe2::TypeMeta::Id() [with T = caffe2::Tensor]’
   CaffeTypeId TypeMeta::Id<T>() {                                                  \
               ^~~~~~~~
/storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/contrib/opencl/context.cc:10:1: note: in expansion of macro ‘CAFFE_KNOWN_TYPE’
 CAFFE_KNOWN_TYPE(Tensor<OpenCLContext>);
 ^~~~~~~~~~~~~~~~
/storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/typeid.h:425:22: note: ‘static caffe2::CaffeTypeId caffe2::TypeMeta::Id() [with T = caffe2::Tensor]’ previously declared here
   inline CaffeTypeId TypeMeta::Id<T>() {  \
                      ^~~~~~~~
/storage/linux/abs/caffe2-cpu-git/src/pytorch-git/caffe2/core/typeid.h:446:1: note: in expansion of macro ‘CAFFE_DECLARE_KNOWN_TYPE’
 CAFFE_DECLARE_KNOWN_TYPE(1, Tensor);
 ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/build.make:362: caffe2/CMakeFiles/caffe2.dir/contrib/opencl/context.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1737: caffe2/CMakeFiles/caffe2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

- Cmake command and output: [https://bpaste.net/show/f14fd917039e](https://bpaste.net/show/f14fd917039e)

- Caffe2 from pytorch stable release v0.4.1 builds fine with the same cmake options as above (OpenCL ON).

- Caffe2 git master builds fine when using the same cmake options as above and switching OpenCL to `-DUSE_OPENCL:BOOL='OFF'`.

- The error seems be **not** related to the gcc version used. The same error occurs with gcc8, gcc7 and gcc5.4.

**System Information:**
**OS:** Arch Linux x86_64
**Compiler:** gcc 8.1.1 (as mentioned, the same error also occurs with gcc7 and gcc5.4)
**Caffe2:** git master
**OpenCL headers:** 2.2.20170516

**Comment by junwenchen** [comment]
I am facing the same problem. Have you solved it?

**Comment by dbermond** [comment]
> Have you solved it?

There is still no solution currently.

**Comment by maxgillett** [comment]
Is there a plan to make Tensor a template again? If not, is there a workaround for OpenCL/AMD support besides compiling from around the time that it was originally added (see commit cd86d4c5548c15e0bc9773565fa4fad73569f948)

**Comment by soumith** [comment]
@maxgillett the answer is no to both questions. However Rocm / AMD support exists and is tested in continuous integration (though the builds for that are undocumented)

**Comment by soumith** [comment]
closing with wontfix tag

**Comment by jiapei100** [comment]
Just disable OpenCL?

**Comment by EmmaJaneBonestell** [comment]
Piss-poor solution. Perhaps at least add this into the CMake files to prevent people wasting build time.

**Comment by zboszor** [comment]
I just ran into this with 2.0.1. Besides, there are more to OpenCL than just Intel and AMD.

For one, ROCm was impossible to cross-compile under Yocto the last time I tried.

A generic GPU accelerated solution would also be good. Is the Vulkan compute stuff in PyTorch comparable to other GPU accelerated paths?
