### ISSUE TITLE
[pt2] TORCH_COMPILE_DEBUG=0 prints debug logs.

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#99906]
### 🐛 Describe the bug

Even if one sets `TORCH_COMPILE_DEBUG=0`, the debug logs are still printed. It would be handy to disable the log if set to 0 or false.

### Versions

master

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment]
cc @mlazos

**Comment by kshitij12345** [comment]
@mlazos I have a patch-ready in case you haven't started this.

**Comment by mlazos** [comment]
Yeah I haven't started, feel free to PR the patch and put me as a reviewer, thank you!
