### ISSUE TITLE
[torch.compile] support `torch.repeat_interleave` with constant repeats as input

### ISSUE THREAD

**Issue by shingjan** [pytorch/pytorch#99929]
### 🐛 Describe the bug

my repro:

```
import torch
import torch._dynamo as dynamo

@dynamo.optimize()
def func():
    a = torch.rand(1,1,1)
    b = a.repeat(10, 1, 1)
    c = a.repeat_interleave(repeats=10, dim=0)
    return b, c

b, c = func()
torch.equal(b, c)
```

`torch.repeat_interleave` is marked `dynamic output shape` in  `aten/src/ATen/native/native_functions.yaml` and is not included in `fake_tensor` dispatch pipeline. I wonder if we could add `torch.repeat_interleave` into the dispatch of fake tensor, something like [this](https://github.com/pytorch/pytorch/compare/main...shingjan:pytorch:shingjan/add_repeat_interleave) and make a special case if `repeats` is passed as a constant, as the output shape would be deterministic given the constant repeats. This will help to avoid many unnecessary graph breaks in some recent models like SAM. Thanks!

### Versions

PyTorch version: 2.0.0a0+gitc263bd4
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment]
Yes, we'll accept a PR adding that.

**Comment by ezyang** [comment]
I think we fixed this in https://github.com/pytorch/pytorch/pull/99528

**Comment by ezyang** [comment]
cc @jgong5

**Comment by shiqingzhangCSU** [comment]
same issue when doing cudagraph capturing !

**Comment by xnerhu** [comment]
I also have the same issue

**Comment by jgong5** [comment]
> I also have the same issue

Are you still encountering the problem? I thought it has been fixed.
