### ISSUE TITLE
benchmarks/dynamo/ci_expected_accuracy/update_expected.py truncates file if only one shard succeeds

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#99923]
### 🐛 Describe the bug

If you run benchmarks/dynamo/ci_expected_accuracy/update_expected.py on a run where one shard failed for some reason, it will delete all the entries associated with that shard. We should instead merge the entries from the shard

### Versions

master

cc @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by anijain2305** [comment]
cc @desertfire

**Comment by tugsbayasgalan** [comment]
@desertfire  any updates?
