### ISSUE TITLE
Docs meant to demonstrate speedup show slowness

### ISSUE THREAD

**Issue by ArturNiederfahrenhorst** [pytorch/pytorch#99939]
### 📚 The doc issue

https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html#basic-usage
means to show speedups of torch compile.

Meanwhile, the outputs captured in these docs actually show a slow-down.
<img width="895" alt="Screenshot 2023-04-24 at 15 40 45" src="https://user-images.githubusercontent.com/9356806/234131711-da934787-2dcd-40d8-b69f-7bfe1b6b3f21.png">

cc @svekars @carljparker @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by msaroufim** [comment]
cc @williamwen42

**Comment by malfet** [comment]
@clee2000 tried moving the runners to V100, which demonstrated 1.2x perf gain: https://github.com/pytorch/tutorials/pull/2301

**Comment by williamwen42** [comment]
Also switched the tutorial model to demonstrate better speedup on average, though the compile time is higher: https://github.com/pytorch/tutorials/pull/2297. I can also add a check for GPU capability.

**Comment by svekars** [comment]
@williamwen42 can you add the GPU check to close the loop on this?

**Comment by msaroufim** [comment]
My take is we shouldn't be sharing these benchmarks on runners that are responsible for my building docs, just describe the machine and hardcode the numbers. Otherwise we should consider running these on A100 (probably not realistic) since 1.2x is still less than the gains we advertise
