### ISSUE TITLE
[pytorch] [feature request] Entropy function

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9993]
Exists in SciPy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html, in PyTorch can be something like:

```python
def entropy(p, dim = -1, keepdim = None):
   return -torch.where(p > 0, p * p.log(), p.new([0.0])).sum(dim = dim, keepdim = keepdim) # can be a scalar, when PyTorch.supports it
```

I agree it is more specialized, but is still useful sometimes.

One other place it may be put in is `torch.distributions[.functional]`

**Comment by alicanb** [comment]
you can calculate this via `distributions.Categorical(probs=p).entropy()`?

**Comment by vadimkantorov** [comment]
A-ha, that's a valid way.

It's nicer than coding it from scratch, but still is a little bit verbose. Of course it's a question of taste / PyTorch API cohesion / etc...

**Comment by xpe** [comment]
@vadimkantorov Ok to close this issue?

**Comment by vadimkantorov** [comment]
Yes :)

**Comment by vadimkantorov** [comment]
Now exists in https://pytorch.org/docs/stable/special.html#torch.special.entr
