### ISSUE TITLE
“kthvalue CUDA does not have a deterministic implementation” ，hope you will prioritize adding definitive support for this operation. 

### ISSUE THREAD

**Issue by WeiweiZhang1** [pytorch/pytorch#99959]
> NOTE: Remember to label this issue with "`ci: sev`"

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*

UserWarning: kthvalue CUDA does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True, warn_only=True)'. You can file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation. (Triggered internally at ../aten/src/ATen/Context.cpp:71.)
threshold, _ = torch.kthvalue(global_scores, residual_k)

**Comment by huydhn** [comment]
This is not how `ci: sev` should be used.  If you have an issue, please create an issue.
