### ISSUE TITLE
AttributeError: 'UpsamplingBilinear2d' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by lhc741** [pytorch/pytorch#99977]
### 🐛 Describe the bug

I can run it correct in pytorch=1.10

```python
class SegmentationHead(nn.Sequential):

    def __init__(self, in_channels, out_channels, kernel_size=3, activation=None, upsampling=1):
        super(SegmentationHead, self).__init__()
        self.conv2d = nn.Conv2d(in_channels, out_channels, kernel_size=kernel_size, padding=kernel_size // 2)
        self.upsampling = nn.UpsamplingBilinear2d(scale_factor=upsampling) if upsampling > 1 else nn.Identity()
        self.activation = Activation(activation)
    def forward(self, x):
        x = self.conv2d(x)
        x = self.upsampling(x)
        x = self.activation(x)
        return x
```
but, when I update it to pytorch=1.12 or pytorch=2.0,
I will get AttributeError: 'UpsamplingBilinear2d' object has no attribute 'recompute_scale_factor'
And other projects also with this trouble like:
https://github.com/search?q=AttributeError%3A+%27Upsample%27+object+has+no+attribute+%27recompute_scale_factor%27&type=issues

It seems like some wrong from pytorch=1.11:
https://github.com/pytorch/pytorch/blob/bc2c6edaf163b1a1330e37a6e34caf8c553e4755/torch/nn/modules/upsampling.py#L140

### Versions

from pytorch=1.11~2.0 

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by drisspg** [comment]
I am going to clsoe this issue because I can not reproduce

**Comment by lhc741** [comment]
Sorry, I mean it can't infer the  old model  in new version, but I see the recompute_scale_factor param is optional.
