### ISSUE TITLE
[pytorch] [docs] Mention that sparse COO tensors support duplicate indices

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9998]
https://pytorch.org/docs/stable/torch.html?highlight=sparse_coo_tensor#torch.sparse_coo_tensor doesn't mention it and doesn't have examples.

SciPy mentions (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html) that the corresponding values are to be summed.

Would be useful for new users of PyTorch sparse package (like myself).

**Comment by fadel** [comment]
Check out https://pytorch.org/docs/stable/sparse.html
> Our sparse tensor format permits uncoalesced sparse tensors, where there may be duplicate coordinates in the indices; in this case, the interpretation is that the value at that index is the sum of all duplicate value entries. Uncoalesced tensors permit us to implement certain operators more efficiently.

**Comment by vadimkantorov** [comment]
This is a nice explanation of coalesced sparse tensors. A suggestion: add a link to this page from `torch.sparse_coo_tensor` doc, saying that details about duplicate indices are there?
