### ISSUE TITLE
Torch not locating AMD GPUs after workaround

### ISSUE THREAD

**Issue by egolfbr** [pytorch/pytorch#99983]
### 🐛 Describe the bug

I have an ubuntu 22.04 server that I am trying to install ROCm and Pytorch on. I use the version matrix on pytorch's website which tells me to install pytorch using 
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
```
After, I run a simple line 
```
torch.cuda.is_available()
```
which always returns false. 

I then checked to make sure a cuda runtime was installed by running 
```
>>python3 -m torch.utils.collect_env
```
Which crashes and says 
```
File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/utils/collect_env.py", line 437, in get_env_info
    hip_runtime_version = [s.rsplit(None, 1)[-1] for s in cfg if 'HIP Runtime' in s][0]
IndexError: list index out of range
```
Finally, when I try and print the cuda version 
```
print(torch.version.cuda)
```
it returns ```None```. My conclusion is that I am not installing the right pytorch version somehow. 

I have tried the following software configurations all on Ubuntu 22.04: 
- ROCm 5.4.3, torch 2.0, python3.10
- ROCm 5.4.2, torch 2.0, python3.10
- ROCm 5.4.2, torch 2.1, python3.10
- ROCm 5.3, torch 2.0, python3.10

I know rocm is picking up my GPUs  by running ```rocminfo```

### Versions

Unfortunately running the collect_env script gave an error
```
Collecting environment information...
Traceback (most recent call last):
  File "/home/ubuntu/collect_env.py", line 606, in <module>
    main()
  File "/home/ubuntu/collect_env.py", line 589, in main
    output = get_pretty_env_info()
  File "/home/ubuntu/collect_env.py", line 584, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/ubuntu/collect_env.py", line 437, in get_env_info
    hip_runtime_version = [s.rsplit(None, 1)[-1] for s in cfg if 'HIP Runtime' in s][0]
IndexError: list index out of range
```

**Comment by drisspg** [comment]
This sounds like this runtime error was specific to your environment. Is it okay to close this issue?

**Comment by egolfbr** [comment]
yes

**Comment by egolfbr** [comment]
Fixed by updating versions of both ROCm and Pytorch. Not sure why it works now, maybe not a full install on the ROCm side
