### ISSUE TITLE
Change misleading error message for type mismatch in LSTM forward

### ISSUE THREAD

**Issue by TamirCohen** [pytorch/pytorch#99998]
### 🚀 The feature, motivation and pitch

The following code:
```
import torch
lstm = torch.nn.LSTM(1, 200, 2, batch_first=True)
input = torch.zeros(20, 36, 1).long()
lstm(input, None)
```
Raises the error:
`RuntimeError: expected scalar type Long but found Float`
Which is misleading - because the solution is to pass input as float tensor
Suggested solution - perform a type check on the input in rnn.forward

If you think its worth something I'd be happy to implement it

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by drisspg** [comment]
Sure, we would accept an implementation of this, feel free to tag me on the review.
